### ISSUE TITLE
[PRE REVIEW]: scikit-fem: A Python package for finite element assembly

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2301]
**Submitting author:** @kinnala (<a href="http://orcid.org/0000-0003-1611-5032">Tom Gustafsson</a>)
**Repository:** <a href="https://github.com/kinnala/scikit-fem" target ="_blank">https://github.com/kinnala/scikit-fem</a>
**Version:** v1.1.0
**Editor:** @meg-simula
**Reviewers:** thelfer, @AnjaliSandip
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kinnala. **Currently, there isn't an JOSS editor assigned** to your paper.

@kinnala if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.1173115 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1145/2998441 is OK
- 10.1007/s10444-019-09666-0 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1149/osf.io/67ckj is OK
- 10.21914/anziamj.v60i0.14058 is OK
- 10.4171/PM/2016 is OK
- 10.1137/19M1246869 is OK
- 10.5281/zenodo.3862391 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02301/joss.02301/10.21105.joss.02301.pdf)

**Comment by kyleniemeyer** [comment]
👋 @kinnala - Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by kinnala** [comment]
Here is a list of reviewer candidates from the list, starting from the bottom:
- yangbai90: Python, finite element method
- AnjaliSandip/: Python, Numerical methods (finite element/volume)
- capitalaslash: Python, Finite elements
- Thelfer: Python, Finite Element Analysis

**Comment by kyleniemeyer** [comment]
Hi @meg-simula, do you have the bandwidth to edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by kinnala** [comment]
> [ point_right Check article proof page_facing_up point_left ](https://github.com/openjournals/joss-papers/blob/joss.02301/joss.02301/10.21105.joss.02301.pdf)

The proof looks correct. My coauthor @gdmcbain can also confirm.

**Comment by meg-simula** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by gdmcbain** [comment]
> The proof looks correct. My coauthor @gdmcbain can also confirm.

LGTM too, thank you.

**Comment by meg-simula** [comment]
Thanks @kinnala for the submission. This looks very much ready for review. I'll reach out to the reviewers suggested and get back to you.

**Comment by meg-simula** [comment]
@yangbai90, @AnjaliSandip,  @capitalaslash, @thelfer Would you like to review this submission for JOSS? Feel free to take a look at our reviewer guidelines here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .

**Comment by thelfer** [comment]
@meg-simula I'd like to, but I need to know when you expect to have my review to see if it fits in my agenda.

**Comment by meg-simula** [comment]
Thanks for the prompt response @thelfer. JOSS is currently in a "reduced service mode". For reviews, this means in particular that (cf. https://blog.joss.theoj.org/2020/05/reopening-joss): 

> Revised (extended) review time: Before the suspension, we encouraged reviewers to complete their reviews in two weeks. In this reduced service mode, we’re asking that reviewers try to complete their reviews in six weeks. Reviewers are of course welcome to complete their reviews faster than this and given the iterative nature of JOSS reviews we still encourage everyone to start their review as soon as possible.

**Comment by thelfer** [comment]
@meg-simula That's fine for me. Ok for the review.

**Comment by meg-simula** [comment]
Great, thanks!

**Comment by meg-simula** [comment]
@whedon assign thelfer as reviewer

**Comment by whedon** [comment]
OK, thelfer is now a reviewer

**Comment by AnjaliSandip** [comment]
I am open to reviewing this as well.

**Comment by meg-simula** [comment]
Great, thanks @AnjaliSandip!

**Comment by meg-simula** [comment]
@whedon add @AnjaliSandip as reviewer

**Comment by whedon** [comment]
OK, @AnjaliSandip is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2369.
