### ISSUE TITLE
[PRE REVIEW]: GenC: Student Concession Card Generator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2302]
**Submitting author:** @jagannathbhat (<a href="http://orcid.org/0000-0002-9110-7457">Jagannath Bhat</a>)
**Repository:** <a href="https://gitlab.com/hexify/genc-asiet" target ="_blank">https://gitlab.com/hexify/genc-asiet</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jagannathbhat. **Currently, there isn't an JOSS editor assigned** to your paper.

@jagannathbhat if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/978-981-13-1056-0_56 may be missing for title: Transforming JavaScript-Based Web Application to Cross-Platform Desktop with Electron

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (251.3 files/s, 44186.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              6              5              5           6499
JavaScript                      39            247              7           2211
Markdown                         2             51              0            118
JSON                             2              0              0            104
TeX                              1              3              0             24
YAML                             1              0              0             18
CSS                              1              1              0             13
HTML                             1              0              0             12
-------------------------------------------------------------------------------
SUM:                            53            307             12           8999
-------------------------------------------------------------------------------


Statistical information for the repository '2302' was gathered on 2020/06/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Abhijith                         1            23              6            0.29
Abhijith P                       6          1502            222           17.16
Jagannath Bhat                  25          4732           3564           82.56

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Abhijith                     15           65.2          1.0                0.00
Abhijith P                  561           37.4          1.2               15.86
Jagannath Bhat             1889           39.9          0.8                7.83
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02302/joss.02302/10.21105.joss.02302.pdf)

**Comment by kyleniemeyer** [comment]
Hi @jagannathBhat, thank you for your interest in JOSS.

The JOSS editors have considered your submission and, while it looks useful, it does not appear to be within the scope of JOSS, which only publishes research software / software with a clear research application. Specifically, as listed in our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html):
> The software should have an *obvious* research application.

Based on our review of your software, the article, and our discussion, your software does not appear to have an obvious research application. (This is not a judgment on its overall usefulness or quality.) Thanks again for your interest.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
