### ISSUE TITLE
[PRE REVIEW]: georg: Towards an Automated Data Pipeline for theIdentification of Geographically Proximal andPharmaceutically Relevant Compounds

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2304]
**Submitting author:** @grindhold (<a href="http://orcid.org/0000-0003-2451-7170">Daniel</a>)
**Repository:** <a href="https://codeberg.org/grindhold/georg" target ="_blank">https://codeberg.org/grindhold/georg</a>
**Version:** v0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @grindhold. **Currently, there isn't an JOSS editor assigned** to your paper.

@grindhold if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (247.5 files/s, 31362.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2             51              0            312
Python                           3             51             34            256
TeX                              1             27              0            154
Bourne Shell                     1              0              0              2
-------------------------------------------------------------------------------
SUM:                             7            129             34            724
-------------------------------------------------------------------------------


Statistical information for the repository '2304' was gathered on 2020/06/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
grindhold                        5           326             14          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
grindhold                   312           95.7          0.0                7.69
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1021/acs.jmedchem.6b01594 is OK
- 10.1021/ci100384d is OK

MISSING DOIs

- https://doi.org/10.1186/1758-2946-3-33 may be missing for title: Open Babel: An open chemical toolbox
- https://doi.org/10.1016/c2012-0-06670-7 may be missing for title: Basic Principles of Drug Discovery and Development

INVALID DOIs

- http://dx.doi.org/10.1093/nar/gky1033 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.15482/USDA.ADC/1239279 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02304/joss.02304/10.21105.joss.02304.pdf)

**Comment by kyleniemeyer** [comment]
👋 @grindhold - Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by Kevin-Mattheus-Moerman** [comment]
@grindhold thank you for your submission. The editorial board has decided this work is not in scope for JOSS (see also our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and statements on "Minor ‘utility’ packages, including ‘thin’ API clients, and single-function packages").  Of course this conclusion says nothing about the value/usefulness of the work submitted, it merely means JOSS is not the right place to publish it. We will therefore proceed to reject this work as it stands.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
