### ISSUE TITLE
[REVIEW]: geemap: A Python package for interactive mapping with Google Earth Engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2305]
**Submitting author:** @giswqs (<a href="http://orcid.org/0000-0001-5437-4073">Qiusheng Wu</a>)
**Repository:** <a href="https://github.com/giswqs/geemap" target ="_blank">https://github.com/giswqs/geemap</a>
**Version:** v0.7.6
**Editor:** @hugoledoux
**Reviewer:** @fbiljecki, @steflhermitte
**Archive:** <a href="https://doi.org/10.6084/m9.figshare.12608834.v1" target="_blank">10.6084/m9.figshare.12608834.v1</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/91af8757c56e3fed2535fcd165137116/status.svg)](https://joss.theoj.org/papers/91af8757c56e3fed2535fcd165137116)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/91af8757c56e3fed2535fcd165137116"><img src="https://joss.theoj.org/papers/91af8757c56e3fed2535fcd165137116/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/91af8757c56e3fed2535fcd165137116/status.svg)](https://joss.theoj.org/papers/91af8757c56e3fed2535fcd165137116)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/giswqs/geemap" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@fbiljecki & @steflhermitte, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @hugoledoux know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/giswqs/geemap">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@giswqs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/giswqs/geemap">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@giswqs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @fbiljecki, @steflhermitte it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.rse.2017.06.031 is OK
- 10.1126/science.1244693 is OK
- 10.3390/rs9121315 is OK
- 10.3390/rs10050691 is OK
- 10.1038/s41893-020-0521-x is OK
- 10.1038/nature20584 is OK
- 10.1016/j.rse.2019.04.015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by hugoledoux** [comment]
👋🏼 @fbiljecki @steflhermitte this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#2305` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

It's for both of you the first review here, so it can be a bit overwhelming. Please feel free to ping me (@hugoledoux) if you have any questions/concerns.

**Comment by hugoledoux** [comment]
@fbiljecki I see you ticked several checkboxes above, but not all. If you haven't done some yet it's fine, but if you have questions or think the software/docs should be modified, the idea is that you state so here in a new comment. If it's something complex you can open a new issue in the repo of the project and put a link here too.

**Comment by giswqs** [comment]
@fbiljecki Thank you very much for taking the time to review the repo! Regarding the two unchecked items:

- **Performance**: There are no performance claims of the package.
- **Automated tests**: I have some automated tests in [tests/test_geemap.py](https://github.com/giswqs/geemap/blob/master/tests/test_geemap.py) as well as [py-check.yaml](https://github.com/giswqs/geemap/blob/master/.github/workflows/py-check.yaml). Would these be sufficient?

I would be happy to make improvement if needed. Thank you.

**Comment by fbiljecki** [comment]
Thanks @giswqs, nice job on the software.
I recommend the acceptance of this submission.

**Comment by giswqs** [comment]
@fbiljecki Thank you very much for your time. Appreciated.

**Comment by steflhermitte** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by steflhermitte** [comment]
@hugoledoux Practical question: how do I tick the review checklist? I see the checkboxes, but can't check them.

**Comment by giswqs** [comment]
> Dear @giswqs,
> 
> First I would like to thank you for the development of what looks at first sight/experience an extremely useful, powerful and well-designed package for interacting with GEE. Looking forward to explore it further in the coming days when finishing the review.
> 
> When installing the package I faced some initial glitches as `pip install geemap` failed to correctly install the ipyleaflet and ipytree dependencies (on macports + pip). They should have been automatically installed (I did receive any error message), but I could not load them in my notebook. I managed to solve it by manually re-installing these packages. I don't think it is necessarily a geemap issue, but it could provide a hurdle for others. I don't know how to handle this though in your package description and/or if it is needed, but wanted to mention it.
> 
> Hope to finish the rest of the review in the coming hours/days.
> 
> Groet,
> Stef

@steflhermitte Thank you very much for taking to time to test the package. The ipyleaflet dependency sometime can be a bit tricky to install, as it might conflict with some of you existing packages. The best way to install geemap is to create a fresh conda environment, if you have Anaconda or Miniconda installed on your computer. I also have a [YouTube video](https://youtu.be/h0pz3S6Tvx0) showing users how to install the package using conda. Hope it helps. Thanks. 

https://github.com/giswqs/geemap#installation

```
conda create -n gee python=3.7
conda activate gee
conda install mamba -c conda-forge
mamba install geemap -c conda-forge
```

**Comment by giswqs** [comment]
> @hugoledoux Practical question: how do I tick the review checklist? I see the checkboxes, but can't tick them.

You might have received an invitation email earlier on. You will need to click the link in that email to accept the invitation. After that, you should be able to tick the review checklist.

**Comment by steflhermitte** [comment]
@giswqs Thanks for the clarifications! I agree that your manual is very clear. I was just testing it in my own environment and that seems to work (after solving the conflicting dependencies).

The invitation seems not to work any longer `Sorry, we couldn't find that repository invitation It is possible that the invitation was revoked or that you are not logged into the invited account.` I am logged in with the correct account, so I guess that I need to be re-invited to be able to tick the boxes.

**Comment by danielskatz** [comment]
@whedon re-invite @steflhermitte as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@steflhermitte please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by steflhermitte** [comment]
Dear @giswqs and @hugoledoux,

I have been reviewing the software and accompanying paper and want to congratulate @giswqs on the nice piece of software. Geemap contains very useful tools for the designed audience that want to use Google Earth Engine in a Jupyter Notebook environment. The tools are simple, perform good and are well documented by example notebooks and accompanying Youtube videos.

Based on this review I recommend the acceptance of this submission.

Best regards,
Stef Lhermitte

**Comment by giswqs** [comment]
@steflhermitte Thank you very much for your support! Appreciated.

**Comment by hugoledoux** [comment]
Nice work @giswqs, this review was very smooth! The 2 reviewers now recommend acceptance so we're reaching the end of the review!

At this point could you:

- [ ] accept the PR I made to your paper, there was a small typo in the acknowlegment
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.

Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by giswqs** [comment]
Dear @hugoledoux, I have made the requested changes. Thanks.

1. Merged your pull request.
2. Made a tagged version [v0.7.6](https://github.com/giswqs/geemap/releases/tag/v0.7.6)
3. Archived the software in [figshare](https://doi.org/10.6084/m9.figshare.12608834.v1)
4. Figshare citation: Wu, Q., 2020. geemap: A Python package for interactive mapping with Google Earth Engine. https://doi.org/10.6084/m9.figshare.12608834.v1

**Comment by FainazInamdeen** [comment]
i have installed geemap through Anaconda, but when I coding in Jupiter notebook, I cannot open the map as you shown in video, what would be the wrong?

**Comment by giswqs** [comment]
@FainazInamdeen Did you create a fresh conda env to install geemap? Check the [installation guidelines](https://github.com/giswqs/geemap#installation). If you still encounter issues, please open a new issue [here](https://github.com/giswqs/geemap/issues). This thread is for the joss-review paper only, not for trouble shooting package installation issues.

```
conda create -n gee python=3.7
conda activate gee
conda install mamba -c conda-forge
mamba install geemap -c conda-forge
```

**Comment by FainazInamdeen** [comment]
@Qiusheng Wu
Sorry didn't notice, btw I have sorted the issue. I think it was because
jupyter notebook before I opened through IE after I changed it into google
chrome, now its working. Thank you for an amazing tutorial.

**Comment by hugoledoux** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02305/joss.02305/10.21105.joss.02305.pdf)

**Comment by hugoledoux** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.rse.2017.06.031 is OK
- 10.1126/science.1244693 is OK
- 10.3390/rs9121315 is OK
- 10.3390/rs10050691 is OK
- 10.1038/s41893-020-0521-x is OK
- 10.1038/nature20584 is OK
- 10.1016/j.rse.2019.04.015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by hugoledoux** [comment]
@whedon set 10.6084/m9.figshare.12608834.v1 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.12608834.v1" target="_blank">10.6084/m9.figshare.12608834.v1</a> is the archive.

**Comment by hugoledoux** [comment]
@whedon set v0.7.6 as version

**Comment by whedon** [comment]
OK. v0.7.6 is the version.

**Comment by hugoledoux** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.rse.2017.06.031 is OK
- 10.1126/science.1244693 is OK
- 10.3390/rs9121315 is OK
- 10.3390/rs10050691 is OK
- 10.1038/s41893-020-0521-x is OK
- 10.1038/nature20584 is OK
- 10.1016/j.rse.2019.04.015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1546

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1546, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by hugoledoux** [comment]
Congratulations @giswqs  your submission is now accepted! Your paper will be handled and published in the near future.

Thanks to @fbiljecki  and @steflhermitte  for the reviews and feedback!

**Comment by giswqs** [comment]
@hugoledoux @fbiljecki @steflhermitte Thank you very much for taking the time to review the package. Much appreciated.

**Comment by giswqs** [comment]
@whedon @hugoledoux Is there anything I need to do on my end? It seems the paper is not moving forward.

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by hugoledoux** [comment]
@giswqs no you don't, it should be picked up by one of the journal editor. It's summer I guess, sorry for delay

**Comment by danielskatz** [comment]
@giswqs - sorry this slipped by - I'll work on now

**Comment by danielskatz** [comment]
@giswqs - Please merge the changes in https://github.com/giswqs/geemap/pull/115 then we can proceed to publication

**Comment by giswqs** [comment]
@danielskatz I have merged your pull request. Thank you very much for your help!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.rse.2017.06.031 is OK
- 10.1126/science.1244693 is OK
- 10.3390/rs9121315 is OK
- 10.3390/rs10050691 is OK
- 10.5194/essd-11-881-2019 is OK
- 10.1038/s41893-020-0521-x is OK
- 10.1038/nature20584 is OK
- 10.1016/j.rse.2019.04.015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1573

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1573, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1283378349843382272) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1574
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02305](https://doi.org/10.21105/joss.02305)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @fbiljecki & @steflhermitte for reviewing and @hugoledoux for editing! 

Congratulations to @giswqs (Qiusheng Wu)!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02305/status.svg)](https://doi.org/10.21105/joss.02305)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02305">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02305/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02305/status.svg
   :target: https://doi.org/10.21105/joss.02305
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02305/status.svg)](https://doi.org/10.21105/joss.02305)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
