### ISSUE TITLE
[REVIEW]: Methods and Algorithms for Correlation Analysis in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2306]
**Submitting author:** @DominiqueMakowski (<a href="http://orcid.org/0000-0001-5375-9967">Dominique Makowski</a>)
**Repository:** <a href="https://github.com/easystats/correlation" target ="_blank">https://github.com/easystats/correlation</a>
**Version:** v0.3.0
**Editor:** @mikldk
**Reviewer:** @markhwhiteii, @mmrabe
**Archive:** <a href="https://doi.org/10.5281/zenodo.3943771" target="_blank">10.5281/zenodo.3943771</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/40579b4c55e01a7119c54cf70bbe3d74/status.svg)](https://joss.theoj.org/papers/40579b4c55e01a7119c54cf70bbe3d74)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/40579b4c55e01a7119c54cf70bbe3d74"><img src="https://joss.theoj.org/papers/40579b4c55e01a7119c54cf70bbe3d74/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/40579b4c55e01a7119c54cf70bbe3d74/status.svg)](https://joss.theoj.org/papers/40579b4c55e01a7119c54cf70bbe3d74)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/easystats/correlation" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@markhwhiteii & @mmrabe, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mikldk know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/easystats/correlation">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@DominiqueMakowski) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/easystats/correlation">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@DominiqueMakowski) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @markhwhiteii, @mmrabe it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01412 is OK
- 10.21105/joss.01541 is OK
- 10.21105/joss.01686 is OK
- 10.3758/s13428-016-0702-8 is OK
- 10.1093/biomet/48.1-2.29 is OK

MISSING DOIs

- https://doi.org/10.18637/jss.v046.i11 may be missing for title: Fast R functions for robust correlations and hierarchical clustering

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by mikldk** [comment]
@DominiqueMakowski: Thank you for the submission. I have now started the review.

@markhwhiteii, @mmrabe: Thanks for agreeing to review. Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If possible create issues (and cross-reference) in the submission's repository to avoid too specific discussions in this review thread.

@DominiqueMakowski, @markhwhiteii, @mmrabe: The paper seems fairly long. It could be an idea to make it shorter (maybe by moving content to the vignettes). The reviewers might have more specific comments on this so I will let them have a look at it.

If any of you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@markhwhiteii, @mmrabe: Can I ask what the status of the review is? Let me know if you need any help.

**Comment by mmrabe** [comment]
@mikldk, thanks for assigning me as a reviewer and sorry for not responding since then. I'm still perfectly happy with reviewing this paper but won't be able to do so before 29-06-2020 as mentioned in the pre-review issue. I'm planning to complete the review by the end of this month if that is acceptable. Sorry for the delay!

**Comment by mikldk** [comment]
@mmrabe Thanks. Yes, that will do. Thank you.

**Comment by markhwhiteii** [comment]
[correlation_review_mhwii.txt](https://github.com/openjournals/joss-reviews/files/4795775/correlation_review_mhwii.txt)

**Comment by markhwhiteii** [comment]
- There's no reference to or explanation of Figure 1 in the text. 
    It is a little confusing, as it is a barplot with a scatterplot 
    layered over it. Given the length of the document, I would 
    suggest perhaps removing Figure 1.  
- The print output of calls to `correlation()` run off the edge of
    the page. Is there a way to shrink the text size or to cut off 
    the columns that run wider than the rest of the text?
- The doi for Langfelder & Horvath (2012) seems to be missing, but
    I did some Googling, and it does appear as though there is not 
    one.
- The second figure, the correlation heatmap, does not have a
    figure number or caption corresponding to it.
- The third figure is listed as the second figure, and it has a
    redundant figure number in the caption.
- I think it would be useful to readers to include a citation to a
    high-level explanation of GGM in the GGM section.
- Similarly, I think it would be useful to provide a citation in 
    the multilevel model section so that the reader can look into 
    the details of how these correlations are calculated, if they
    would like to know.

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by mikldk** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.15 s (563.4 files/s, 86752.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            26           1319            317           4979
R                               38            620            523           1524
XML                              1              0             42           1484
Markdown                         3            143              0            449
CSS                              3             79             51            298
JavaScript                       3             41             18            151
Rmd                              3            143            173            122
TeX                              1             12              0            122
YAML                             4             27             10            121
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            83           2384           1135           9261
-------------------------------------------------------------------------------


Statistical information for the repository '2306' was gathered on 2020/06/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel                           1            12              0            5.36
Dominique Makowski               2           205              7           94.64

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel                       12          100.0          0.0               16.67
DominiqueMakowski           198          100.0          0.1                8.08
```

**Comment by DominiqueMakowski** [comment]
Dear @markhwhiteii, thanks for your comments and suggestions ☺️ We have addressed and fixed all of your points in separate issues (see https://github.com/easystats/correlation/issues?q=is%3Aissue+is%3Aclosed). Let us know if there is anything more.

**Comment by mmrabe** [comment]
I was now able to complete my review. All in all, the paper is a very useful introduction to the package. I don't have a lot to add to what @markhwhiteii already mentioned and has been fixed in the meantime. I only have a few minor suggestions, which I added as Github issues. I do agree with @mikldk that the paper is a bit too long for a JOSS submission. I would recommend selecting two representative examples and maybe shorten the very informative but too detailed intros to different types of correlations.

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by DominiqueMakowski** [comment]
Dear @mmrabe, thanks again for your comments. We have also addressed them all in the issues you opened. Let us know if there is anything more 🤗

**Comment by mikldk** [comment]
@DominiqueMakowski @mmrabe @markhwhiteii : I am worried with the length of the paper. It is currently approx 2,500 words and <https://joss.readthedocs.io/en/latest/submitting.html> says "The paper should be between 250-1000 words.". The [issue](https://github.com/easystats/correlation/issues/96) did not track commits so it is difficult to follow what changes was made. I suggest that author reopens the issue and work on moving content from paper to vignettes and also re-read <https://joss.readthedocs.io/en/latest/submitting.html>. What do you think @mmrabe and @markhwhiteii?

**Comment by DominiqueMakowski** [comment]
Thanks @mikldk for your feedback. We'll try shortening it. However, note that the current length and format of the paper was mostly inspired by the previous JOSS papers of the other easystats papers (https://joss.theoj.org/papers/10.21105/joss.01541; https://joss.theoj.org/papers/10.21105/joss.01412) which length also exceeds the said recommendation. Our concern is that the paper is typically aimed at a different audience (for instance posted on researchgate), such as academics, that are less used to explore the features on GitHub and in the vignettes. Hence we wanted the paper to also showcase some of the features (rather than be just a container of links), but we'll see what we can do ☺️

**Comment by mmrabe** [comment]
@mikldk Are there more detailed guidelines what exactly counts toward the 250-1000 words or how one should determine the word count? Ignoring figures, output, and equations, I count approx. 1080 words.

@DominiqueMakowski I've also noticed that many R users won't look at vignettes but given that your audience does care about papers, wouldn't the paper be a good place to make them aware of that feature? You should also consider that your paper will remain static but you can always add, extend, and revise package vignettes after publication. That may be advantageous, too.

**Comment by mikldk** [comment]
@mmrabe: I simply took the markdown without the header.

@DominiqueMakowski : Please put examples in the software documentation and link to that in the paper. This can both be in vignettes or in the README. Also only include high-level summary of the different functionalities that the package supports in the paper and refer to the documentation for a complete summary of functionality.

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by DominiqueMakowski** [comment]
Thanks for your suggestions.

@mikldk we shorten the paper and linked to the vignettes and documentation.

**Comment by mikldk** [comment]
@DominiqueMakowski : Thank you for the progress. The vignette "Correlation Types" does not contain as many details (formulas) as the paper. I think it should be the other way around. Also, you still have `R` examples in the paper. Please see if you can improve the vignette(s) with what is in the paper (e.g. details on correlation) and try to keep the paper without examples (move to vignettes/README).

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by DominiqueMakowski** [comment]
Thanks for your feedback @mikldk. We have addressed the issues regarding the vignettes so that they include all the details about the types.

Regarding the two `R` chunks that we left in the paper, I would like to ask for the reconsideration of the possibility of keeping them, as they are not really "examples" of features per se but rather just the demonstration of the main function and its output. I think it's important that the audience reading the paper can have a glimpse of how the workflow looks like, so that they can decide if they want to further explore the features by visiting the documentation/vignettes.

**Comment by mmrabe** [comment]
I agree with @DominiqueMakowski that it would probably be helpful for most readers if the paper contains a very brief demonstration of the main functionality, as it does now.

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by mikldk** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1155/2020/7398324 is OK
- 10.21105/joss.01412 is OK
- 10.3389/fpsyg.2019.01050 is OK
- 10.21105/joss.01541 is OK
- 10.21105/joss.01686 is OK
- 10.3758/s13428-017-0862-1 is OK
- 10.3389/fpsyg.2017.00456 is OK
- 10.3758/s13428-016-0702-8 is OK
- 10.1093/biomet/48.1-2.29 is OK

MISSING DOIs

- https://doi.org/10.18637/jss.v046.i11 may be missing for title: Fast R functions for robust correlations and hierarchical clustering

INVALID DOIs

- None
```

**Comment by mikldk** [comment]
@DominiqueMakowski :

* Please add DOI 10.18637/jss.v046.i11 for `@langfelder2012fast`
* Please have a final read though of the paper, checking language etc.
* Have a final check of the proofs with `@whedon generate pdf`
* Please make a tagged release and archive (e.g. with [Zenodo](https://zenodo.org/)), and report the version number and archive DOI in this thread. Please verify that the archive deposit has the correct metadata (title and author list), or edit these if that is not the case.

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by DominiqueMakowski** [comment]
Dear @mikldk, regarding the first point, as mentioned [here](https://github.com/easystats/correlation/issues/87), we weren't able to find a DOI for this ref.

We checked the paper and the metadata. 

The zenodo release version is 0.3.0 and its number: **10.5281/zenodo.3943771** (https://zenodo.org/record/3943771).

Thanks a lot.

**Comment by mmrabe** [comment]
@DominiqueMakowski 
The DOI `10.18637/jss.v046.i11` that @mikldk mentioned is listed under the URL linked in the [package citation](https://cran.r-project.org/web/packages/flashClust/citation.html). Also, while looking at the bibliography again, could you maybe escape all occurences of {R} in your .bib so that it appears in upper case in the rendered version?

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by DominiqueMakowski** [comment]
> The DOI 10.18637/jss.v046.i11 that @mikldk mentioned

Apologies, I misread this and missed the DOI given by @mikldk ☺️ 

> escape all occurences of {R} in your .bib

It should be done, thansk a lot @mmrabe !!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by DominiqueMakowski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by DominiqueMakowski** [comment]
@mikldk I think everything's in order :)

**Comment by mikldk** [comment]
@whedon set 10.5281/zenodo.3943771 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3943771" target="_blank">10.5281/zenodo.3943771</a> is the archive.

**Comment by mikldk** [comment]
@whedon set <v0.0.3> as version

**Comment by whedon** [comment]
OK. <v0.0.3> is the version.

**Comment by mikldk** [comment]
@whedon set v0.0.3 as version

**Comment by whedon** [comment]
OK. v0.0.3 is the version.

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by DominiqueMakowski** [comment]
@mikldk please note that the version is 0.3.0 (I think you entered 0.0.3)

**Comment by mikldk** [comment]
@whedon set v0.3.0 as version

**Comment by whedon** [comment]
OK. v0.3.0 is the version.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1155/2020/7398324 is OK
- 10.21105/joss.01412 is OK
- 10.3389/fpsyg.2019.01050 is OK
- 10.21105/joss.01541 is OK
- 10.21105/joss.01686 is OK
- 10.3758/s13428-017-0862-1 is OK
- 10.3389/fpsyg.2017.00456 is OK
- 10.3758/s13428-016-0702-8 is OK
- 10.18637/jss.v046.i11 is OK
- 10.1093/biomet/48.1-2.29 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mikldk** [comment]
@whedon check references

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1155/2020/7398324 is OK
- 10.21105/joss.01412 is OK
- 10.3389/fpsyg.2019.01050 is OK
- 10.21105/joss.01541 is OK
- 10.21105/joss.01686 is OK
- 10.3758/s13428-017-0862-1 is OK
- 10.3389/fpsyg.2017.00456 is OK
- 10.3758/s13428-016-0702-8 is OK
- 10.18637/jss.v046.i11 is OK
- 10.1093/biomet/48.1-2.29 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02306/joss.02306/10.21105.joss.02306.pdf)

**Comment by mikldk** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1155/2020/7398324 is OK
- 10.21105/joss.01412 is OK
- 10.3389/fpsyg.2019.01050 is OK
- 10.21105/joss.01541 is OK
- 10.21105/joss.01686 is OK
- 10.3758/s13428-017-0862-1 is OK
- 10.3389/fpsyg.2017.00456 is OK
- 10.3758/s13428-016-0702-8 is OK
- 10.18637/jss.v046.i11 is OK
- 10.1093/biomet/48.1-2.29 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1570

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1570, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1283697133879795712) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1581
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02306](https://doi.org/10.21105/joss.02306)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @DominiqueMakowski, your JOSS paper is published! 🚀 

Huge thanks to our editor: @mikldk, and reviewers: @markhwhiteii, @mmrabe 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02306/status.svg)](https://doi.org/10.21105/joss.02306)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02306">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02306/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02306/status.svg
   :target: https://doi.org/10.21105/joss.02306
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02306/status.svg)](https://doi.org/10.21105/joss.02306)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by DominiqueMakowski** [comment]
Thanks a lot to everybody involved, as always, it has been a pleasure ☺️ 🎉
