### ISSUE TITLE
[PRE REVIEW]: pyrolite: Python for geochemistry

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2309]
**Submitting author:** @morganjwilliams (<a href="http://orcid.org/0000-0003-4764-9555">Morgan Williams</a>)
**Repository:** <a href="https://github.com/morganjwilliams/pyrolite" target ="_blank">https://github.com/morganjwilliams/pyrolite</a>
**Version:** 0.2.7
**Editor:** @arfon
**Reviewers:** @arfon
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @morganjwilliams. **Currently, there isn't an JOSS editor assigned** to your paper.

@morganjwilliams if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2309 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.62 s (466.9 files/s, 65288.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         169           4288           8212          14519
reStructuredText                75           3579           3259           1973
Markdown                         9            126              0            317
TeX                              1             19              0            220
Jupyter Notebook                24              0           3504            186
CSS                              1              8              8             57
YAML                             4             12             10             55
DOS Batch                        1              8              1             27
make                             1              4              6             10
JSON                             3              0              0              3
INI                              1              0              0              2
-------------------------------------------------------------------------------
SUM:                           289           8044          15000          17369
-------------------------------------------------------------------------------

**Comment by arfon** [comment]
@morganjwilliams - will this submission eventually be part of the pyOpenSci GitHub organization? If so, it might be worth waiting until that last step is complete before processing this paper so that the URLs to the software are correct?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02309/joss.02309/10.21105.joss.02309.pdf)

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by morganjwilliams** [comment]
@arfon migration to the pyOpenSci org isn't planned at this stage, so the links should be OK.

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, @arfon is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2314.
