### ISSUE TITLE
[REVIEW]: flusight

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#231]
**Submitting author:** @lepisma (<a href="http://orcid.org/0000-0001-7137-0728">Abhinav Tushar</a>)
**Repository:** <a href="https://github.com/reichlab/flusight" target ="_blank">https://github.com/reichlab/flusight</a>
**Version:** v1.3.3
**Editor:** @arfon
**Reviewer:** @rneher
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.573580" target="_blank">10.5281/zenodo.573580</a>

## Status

[![status](http://joss.theoj.org/papers/474aabe851a65d08df9431305f8b9d0d/status.svg)](http://joss.theoj.org/papers/474aabe851a65d08df9431305f8b9d0d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/474aabe851a65d08df9431305f8b9d0d"><img src="http://joss.theoj.org/papers/474aabe851a65d08df9431305f8b9d0d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/474aabe851a65d08df9431305f8b9d0d/status.svg)](http://joss.theoj.org/papers/474aabe851a65d08df9431305f8b9d0d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/reichlab/flusight" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/reichlab/flusight">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1.0)?
- [x] **Authorship:** Has the submitting author (lepisma) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @rneher it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @rneher - please take a look at the reviewer guidelines (http://joss.theoj.org/about#reviewer_guidelines) and update the checklist above as you go. If you have any questions for me or the submitting author just ask us here.

**Comment by rneher** [comment]
thanks. will get back to you if I have questions.

**Comment by rneher** [comment]
flusight is a useful and intuitive visualization of flu prediction data. I managed to run a local dev server without problems. I don't see anything fundamental preventing acceptance. A few minor things

  - references don't render in the `paper.md`
  - a few additional sentences on how these predictions are visualized and evaluated now would help. Are there any similar efforts?
  - the tool tip for the prediction should explicitly mention "1 week ahead", "2 week ahead" etc. 
  - historical traces are almost invisible, consider making them a little darker
  - an `about` page would help. Explain what is being predicted, what is used as input etc
  - the input prediction files have prediction for HHS regions but the website only offers US national. Is this intended?

**Comment by arfon** [comment]
Thanks @rneher. @lepisma - please let me know when you've had a chance to review this feedback.

On this point:

> references don't render in the paper.md

These will be compiled in at then end when we produce the PDF with Pandoc.

**Comment by lepisma** [comment]
Thanks for your comments @rneher !

For points
> - a few additional sentences on how these predictions are visualized and evaluated now would help. Are there any similar efforts?
> - an about page would help. Explain what is being predicted, what is used as input etc

Will add a github wiki page about this and link to the application.

> - the tool tip for the prediction should explicitly mention "1 week ahead", "2 week ahead" etc.
> - historical traces are almost invisible, consider making them a little darker

Working on these now.

> - the input prediction files have prediction for HHS regions but the website only offers US national. Is this intended?

The region to view predictions for can be selected by clicking on the map. This is mentioned in the interactive help (when we press the <kbd>help</kbd> button on the top right of site). Should this be more clearly mentioned somewhere else (like a dropdown menu)?

**Comment by lepisma** [comment]
Updates:

- There is a simple about page [here](https://github.com/reichlab/flusight/wiki/About) and is linked in the application (navbar).
- Chart tooltips show `x wks ahead` text.
- Historical traces are darker.
- The region to view predictions for can be selected via a dropdown (as well as the original method of clicking on the map).

**Comment by nickreich** [comment]
In response to the comment 

> a few additional sentences on how these predictions are visualized and evaluated now would help. Are there any similar efforts?

I just committed a few additional links in the first paragraph of the About page. 

We have completed our round of revisions, based on comments from @rneher and will wait to hear from JOSS about next steps. Thanks for the review!

**Comment by arfon** [comment]
@rneher - would you be able to take another look at this submission in response to the reviewer updates?

**Comment by rneher** [comment]
all my comments have been addressed.

**Comment by arfon** [comment]
@lepisma - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by lepisma** [comment]
We have updated the version to [v1.3.3](https://github.com/reichlab/flusight/releases/tag/v1.3.3).
DOI : [https://doi.org/10.5281/zenodo.573580](https://doi.org/10.5281/zenodo.573580).

**Comment by arfon** [comment]
@rneher - many thanks for your review here ✨ 

@lepisma - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00231 ⚡️ 🚀 :boom:
