### ISSUE TITLE
[PRE REVIEW]: A parallel global multiobjective framework for optimization: pagmo

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2310]
**Submitting author:** @bluescarni (<a href="http://orcid.org/0000-0002-3491-1828">Francesco Biscani</a>)
**Repository:** <a href="https://github.com/esa/pagmo2-paper" target ="_blank">https://github.com/esa/pagmo2-paper</a>
**Version:** v2.15.0
**Editor:** @eloisabentivegna
**Reviewers:** @dgoldri25, @jangmys
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @bluescarni. **Currently, there isn't an JOSS editor assigned** to your paper.

@bluescarni if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.3702783 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- https://doi.org/10.1016/j.parco.2010.04.002 may be missing for title: On the impact of the migration topology on the island model
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02310/joss.02310/10.21105.joss.02310.pdf)

**Comment by arfon** [comment]
:wave: @bluescarni - thanks for your submission to JOSS. Could you please explain where the software is associated with this submission? We prefer the JOSS paper to be housed together with the software if at all possible.

Additionally, as described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier a week or so ago we've had > 70 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by bluescarni** [comment]
Hi @arfon 

the software lives in two repositories:

https://github.com/esa/pagmo2
https://github.com/esa/pygmo2

Would you like me to move the paper in a branch in the first repo?

**Comment by arfon** [comment]
Got it, thanks @bluescarni. I think this is OK as it seems like we're going to want to review both packages as part of this review.

While I look for an editor, please take a look at the DOI fixes that Whedon suggested above (https://github.com/openjournals/joss-reviews/issues/2310#issuecomment-640899613).

**Comment by arfon** [comment]
@whedon invite @eloisabentivegna as editor

@eloisabentivegna - what do you think about taking this submission on as one of your first papers? It is _slightly_ unusual in that the author is submitting two packages (https://github.com/esa/pagmo2 & https://github.com/esa/pygmo2) as part of the same submission which look to be C++ and Python implementations of the same library. As a result, the paper is in a standalone repository which will require a little manual work by `@openjournals/dev` at the end of the review but we've handled similar things before.

**Comment by whedon** [comment]
@eloisabentivegna has been invited to edit this submission.

**Comment by bluescarni** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by bluescarni** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02310/joss.02310/10.21105.joss.02310.pdf)

**Comment by bluescarni** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.3702783 is OK
- 10.1016/j.parco.2010.04.002 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by bluescarni** [comment]
> While I look for an editor, please take a look at the DOI fixes that Whedon suggested above ([#2310 (comment)](https://github.com/openjournals/joss-reviews/issues/2310#issuecomment-640899613)).

Cheers, I think it should be fixed now.

**Comment by eloisabentivegna** [comment]
@arfon -- Certainly!

@whedon assign @eloisabentivegna as editor

**Comment by arfon** [comment]
Excellent, thanks @eloisabentivegna. One minor thing, Whedon only responds to comments at the start of a post or as standalone comments. i.e. if you now type `@whedon assign @eloisabentivegna as editor` in its own comment then Whedon will assign you.

**Comment by eloisabentivegna** [comment]
@whedon assign @eloisabentivegna as editor

@arfon, I suspected that. Thanks for clarifying!

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by eloisabentivegna** [comment]
@whedon add @dgoldri25 as reviewer

**Comment by whedon** [comment]
OK, @dgoldri25 is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon add @jangmys as reviewer

**Comment by whedon** [comment]
OK, @jangmys is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2338.
