### ISSUE TITLE
[PRE REVIEW]: Tools21cm: A python package to analyse the large-scale 21 cm signal from the Epoch of Reionization and Cosmic Dawn

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2312]
**Submitting author:** @sambit-giri (<a href="http://orcid.org/0000-0002-2560-536X">Sambit Kumar Giri</a>)
**Repository:** <a href="https://github.com/sambit-giri/tools21cm" target ="_blank">https://github.com/sambit-giri/tools21cm</a>
**Version:** v2.1
**Editor:** @pibion
**Reviewers:** @nicholebarry, @aureliocarnero
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sambit-giri. **Currently, there isn't an JOSS editor assigned** to your paper.

@sambit-giri if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.19 s (353.9 files/s, 48811.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          49           1328           2847           3802
reStructuredText                10             76            109            112
Jupyter Notebook                 2              0            628             86
Markdown                         2             16              0             32
DOS Batch                        1              8              1             26
YAML                             1              3              0             10
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            66           1435           3592           4077
-------------------------------------------------------------------------------


Statistical information for the repository '2312' was gathered on 2020/06/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Garrelt Mellema                  4           100              8            0.12
Sambit Giri                     16           172             69            0.26
Sambit Kumar Giri               77         20976          14306           37.69
sambit-giri                    105         29581          28389           61.93

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Garrelt Mellema              49           49.0          0.1               20.41
Sambit Giri                  74           43.0          0.5                0.00
Sambit Kumar Giri          7854           37.4         24.5                6.26
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2312 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
:wave: @sambit-giri - thanks for your submission to JOSS. Can you tell me if this submission accompanies a paper in a AAS journal?

**Comment by arfon** [comment]
Also, from what I can find, there's no `paper.md` (or other JOSS-related materials) in this repository. Please familiarize yourself with our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html) and let us know when you've added your paper.

**Comment by sambit-giri** [comment]
@arfon There is no accompanying a paper in an AAS journal.
We have put the paper for submission in the [repository](https://github.com/sambit-giri/tools21cm/tree/master/paper).
I apologise for the inconvenience.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02312/joss.02312/10.21105.joss.02312.pdf)

**Comment by arfon** [comment]
@whedon invite @pibion as editor

:wave: @pibion - what do you think about taking on this as one of your first papers to edit?

**Comment by whedon** [comment]
@pibion has been invited to edit this submission.

**Comment by sambit-giri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02312/joss.02312/10.21105.joss.02312.pdf)

**Comment by sambit-giri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02312/joss.02312/10.21105.joss.02312.pdf)

**Comment by pibion** [comment]
@arfon is it okay that my expertise is squarely in the "particle" part of particle astrophysics?  I do have some basic familiarity with this topic and am happy to review, but we should definitely have someone on the team who is expert in this kind of analysis.

@sambit-giri do you have any reviewers you could recommend?

**Comment by arfon** [comment]
> @arfon is it okay that my expertise is squarely in the "particle" part of particle astrophysics? I do have some basic familiarity with this topic and am happy to review, but we should definitely have someone on the team who is expert in this kind of analysis.

Yeah, I think this is OK :-) . Let's just make sure we get some expert reviewers as you say. 

@pibion - The next step here is to ask Whedon to assign this paper to you. You can do either `@whedon assign me as editor` or `@whedon assign @pibion as editor`.

**Comment by pibion** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pibion

**Comment by pibion** [comment]
@sambit-giri thanks for your patience while I find an editor or two with analysis experience relevant to this software.  Just a heads up, this may take a few days.

**Comment by sambit-giri** [comment]
@pibion Thanks for informing. I can wait.

**Comment by pibion** [comment]
@whedon add @nicholeberry as reviewer

**Comment by whedon** [comment]
OK, @nicholeberry is now a reviewer

**Comment by pibion** [comment]
@whedon remove @nicholeberry as reviewer

**Comment by whedon** [comment]
OK, @nicholeberry is no longer a reviewer

**Comment by pibion** [comment]
@whedon add @nicholebarry as reviewer

**Comment by whedon** [comment]
OK, @nicholebarry is now a reviewer

**Comment by arfon** [comment]
Is everything working OK here now @pibion?

**Comment by pibion** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by pibion** [comment]
@arfon I'm not sure whedon has successfully added @nicholebarry as a reviewer.

**Comment by pibion** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by pibion** [comment]
@arfon never mind, this looks good!

**Comment by pibion** [comment]
@sambit-giri we've now got one reviewer; we need one more and then we can begin the review process.

**Comment by pibion** [comment]
@whedon add @aureliocarnero as reviewer

**Comment by whedon** [comment]
OK, @aureliocarnero is now a reviewer

**Comment by arfon** [comment]
@pibion - now you have two reviewers in place, if you're ready, you can move this forward to review with `@whedon start review`

**Comment by pibion** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2363.
