### ISSUE TITLE
[REVIEW]: BiRank: Fast and Flexible Ranking on Bipartite Networks with R and Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2315]
**Submitting author:** @yangkcatiu (<a href="http://orcid.org/0000-0003-4627-9273">Kai-Cheng Yang</a>)
**Repository:** <a href="https://github.com/BrianAronson/birankr" target ="_blank">https://github.com/BrianAronson/birankr</a>
**Version:** v1.0
**Editor:** @drvinceknight
**Reviewer:** @gvegayon, @nikoleta-v3
**Archive:** <a href="https://doi.org/10.5281/zenodo.3939045" target="_blank">10.5281/zenodo.3939045</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/748a91d9443eca60f7681b1eeb32659d/status.svg)](https://joss.theoj.org/papers/748a91d9443eca60f7681b1eeb32659d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/748a91d9443eca60f7681b1eeb32659d"><img src="https://joss.theoj.org/papers/748a91d9443eca60f7681b1eeb32659d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/748a91d9443eca60f7681b1eeb32659d/status.svg)](https://joss.theoj.org/papers/748a91d9443eca60f7681b1eeb32659d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/BrianAronson/birankr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gvegayon & @nikoleta-v3, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @drvinceknight know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/BrianAronson/birankr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@yangkcatiu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/BrianAronson/birankr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@yangkcatiu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gvegayon, @nikoleta-v3 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/TKDE.2016.2611584 is OK
- 10.1103/PhysRevE.76.046115 is OK
- 10.1145/324133.324140 is OK
- 10.1371/journal.pone.0112022 is OK
- 10.1145/1557019.1557051 is OK
- 10.1109/WI-IAT.2011.60 is OK
- 10.1145/1291233.1291378 is OK
- 10.1103/PhysRevE.78.016108 is OK
- 10.1038/nmeth.2728 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02315/joss.02315/10.21105.joss.02315.pdf)

**Comment by Nikoleta-v3** [comment]
Hello @yangkcatiu 👋 I am one of the reviewers. I am currently completing the **Documentation** checklist. I opened the following issues:

- https://github.com/BrianAronson/birankr/issues/19
- https://github.com/BrianAronson/birankr/issues/20
- https://github.com/BrianAronson/birankr/issues/21

Please comment on the issues if you have any questions.

**Comment by yangkcatiu** [comment]
@Nikoleta-v3 Thank you for the feedback, we really appreciate it! We will start to address these issues.

**Comment by yangkcatiu** [comment]
👋 @gvegayon thank you for agreeing to review for our work, we really appreciate it and low forward to your feedback!

**Comment by gvegayon** [comment]
Sure! Happy to help. I won't start working on this until the end of this
month since I'm defending my Ph.D. soon (sorry!). I'll start with the
review ASAP.

George
<https://ggvy.cl>

**Comment by yangkcatiu** [comment]
@gvegayon good luck with the defense!

**Comment by Nikoleta-v3** [comment]
👋 @yangkcatiu.  I am now completing the **Software paper** checklist. I opened the following issues:

- https://github.com/BrianAronson/birankr/issues/23
- https://github.com/BrianAronson/birankr/issues/24

Please comment on the issues if you have any questions.

**Comment by yangkcatiu** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by yangkcatiu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/TKDE.2016.2611584 is OK
- 10.1103/PhysRevE.76.046115 is OK
- 10.1145/324133.324140 is OK
- 10.1371/journal.pone.0112022 is OK
- 10.1145/1557019.1557051 is OK
- 10.1109/WI-IAT.2011.60 is OK
- 10.1145/1291233.1291378 is OK
- 10.1103/PhysRevE.78.016108 is OK
- 10.1038/nmeth.2728 is OK
- 10.31235/osf.io/hazvs is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Nikoleta-v3** [comment]
@drvinceknight I have finished my review. Let me know if there is anything else I need to do 😄

@yangkcatiu thank you for your work 👍

**Comment by gvegayon** [comment]
Hi there! I'm back :). I started the review, but I was trying to mark the checklist and it seems that I'm no longer able to do so. I tried re-opening the collab link sent by JOSS but it expedited. What can I do? I'm still reviewing and will let you know when all is done.

**Comment by danielskatz** [comment]
@whedon re-invite @gvegayon as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@gvegayon please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by gvegayon** [comment]
Hey! So everything looks good on my side. I tested the package, compiled it, and run the checks using R CMD check. The authors addressed a couple of key issues that submitted regarding testing and documentation. Issue 28 is regarding some R CMD check notes that are very easy to address, so with that, we are good to go!

**Comment by drvinceknight** [comment]
That's great, thanks @gvegayon. 

@yangkcatiu if you could comment here when that issue is addressed that would be great :+1:

**Comment by yangkcatiu** [comment]
@drvinceknight we have addressed the issue.

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by drvinceknight** [comment]
@whedon check references

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02315/joss.02315/10.21105.joss.02315.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/TKDE.2016.2611584 is OK
- 10.1103/PhysRevE.76.046115 is OK
- 10.1145/324133.324140 is OK
- 10.1371/journal.pone.0112022 is OK
- 10.1145/1557019.1557051 is OK
- 10.1109/WI-IAT.2011.60 is OK
- 10.1145/1291233.1291378 is OK
- 10.1103/PhysRevE.78.016108 is OK
- 10.1038/nmeth.2728 is OK
- 10.31235/osf.io/hazvs is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by drvinceknight** [comment]
> @drvinceknight we have addressed the issue.

Thanks, I've made some minor type edits in https://github.com/BrianAronson/birankr/pull/29

Once that's merged could you:

Make a tagged release and archive, and report the version number and archive DOI here. Please ensure that the archive deposit has the correct metadata  so that the title and author list match the paper.

**Comment by yangkcatiu** [comment]
We appreciate the edits!

- [x] Merge the edits
- [x] Make a tagged release: v1.0 release at https://github.com/BrianAronson/birankr/releases 
- [x] Make an archive: DOI 10.5281/zenodo.3939045

**Comment by drvinceknight** [comment]
@whedon set 10.5281/zenodo.3939045 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3939045" target="_blank">10.5281/zenodo.3939045</a> is the archive.

**Comment by drvinceknight** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by drvinceknight** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/TKDE.2016.2611584 is OK
- 10.1103/PhysRevE.76.046115 is OK
- 10.1145/324133.324140 is OK
- 10.1371/journal.pone.0112022 is OK
- 10.1145/1557019.1557051 is OK
- 10.1109/WI-IAT.2011.60 is OK
- 10.1145/1291233.1291378 is OK
- 10.1103/PhysRevE.78.016108 is OK
- 10.1038/nmeth.2728 is OK
- 10.31235/osf.io/hazvs is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1559

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1559, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1281672261628559360) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1561
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02315](https://doi.org/10.21105/joss.02315)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @yangkcatiu on your article's publication in JOSS!

Many thanks to @gvegayon and @Nikoleta-v3 for reviewing this, and @drvinceknight for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02315/status.svg)](https://doi.org/10.21105/joss.02315)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02315">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02315/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02315/status.svg
   :target: https://doi.org/10.21105/joss.02315
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02315/status.svg)](https://doi.org/10.21105/joss.02315)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by yangkcatiu** [comment]
I want to thank @gvegayon , @Nikoleta-v3 , and @drvinceknight for your work on behalf of our team!

**Comment by drvinceknight** [comment]
Congratulations @yangkcatiu and thank you @gvegayon and @Nikoleta-v3 without your contribution JOSS would not work so it's really appreciated :)
