### ISSUE TITLE
[REVIEW]: PyStokes: Stokesian hydrodynamics in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2318]
**Submitting author:** @rajeshrinet (<a href="http://orcid.org/0000-0003-0266-9691">Rajesh Singh</a>)
**Repository:** <a href="https://github.com/rajeshrinet/pystokes" target ="_blank">https://github.com/rajeshrinet/pystokes</a>
**Version:** v2.2.0
**Editor:** @harpolea
**Reviewer:** @fcooper8472, @khinsen
**Archive:** <a href="https://doi.org/10.5281/zenodo.3923867" target="_blank">10.5281/zenodo.3923867</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3523556d9ab3254a27c8c890a81720b2/status.svg)](https://joss.theoj.org/papers/3523556d9ab3254a27c8c890a81720b2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3523556d9ab3254a27c8c890a81720b2"><img src="https://joss.theoj.org/papers/3523556d9ab3254a27c8c890a81720b2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3523556d9ab3254a27c8c890a81720b2/status.svg)](https://joss.theoj.org/papers/3523556d9ab3254a27c8c890a81720b2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/rajeshrinet/pystokes" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@fcooper8472 & @khinsen, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @harpolea know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rajeshrinet/pystokes">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rajeshrinet) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rajeshrinet/pystokes">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rajeshrinet) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @fcooper8472, @khinsen it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/1.9780898718003.bm is OK
- 10.1007/978-3-319-12787-3 is OK
- 10.1007/BF01194638 is OK
- 10.1063/1.5090179 is OK
- 10.1088/2399-6528/aaab0d is OK
- 10.1103/PhysRevLett.117.228002 is OK
- 10.1039/C7CS00461C is OK
- 10.1039/B918598D is OK
- 10.1146/annurev.fl.21.010189.000425 is OK
- 10.1103/PhysRevLett.124.088003 is OK
- 10.1017/S0022112075001486 is OK
- 10.1017/S0022112082000627 is OK
- 10.1017/CBO9780511624124 is OK
- 10.1017/S0022112095003260 is OK
- 10.1016/j.enganabound.2004.12.001 is OK
- 10.1073/pnas.1718807115 is OK

MISSING DOIs

- https://doi.org/10.2307/3613759 may be missing for title: The mathematical theory of viscous incompressible flow
- https://doi.org/10.1080/17797179.2017.1294829 may be missing for title: Fluctuating hydrodynamics and the Brownian motion of an active colloid near a wall
- https://doi.org/10.1088/1742-5468/2015/06/p06017 may be missing for title: Many-body microhydrodynamics of colloidal particles with active boundary layers

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02318/joss.02318/10.21105.joss.02318.pdf)

**Comment by khinsen** [comment]
@harpolea I did a first pass looking at the code and the paper. It was a lot of fun: this is a very nice implementation of hydrodynamic and phoretic interactions which invites users to play with it, in particular by including visualization tools, and that is just great for doing research. The next time I do work in this domain, I'll happily abandon [my own 25-year-old Fortran library](https://github.com/khinsen/HYDROLIB) and use PyStokes instead!

I have made a few suggestions for improvements via issues/pull requests on the code repository, which the authors have handled immediately. Interactive reviewing is a fun experience :-)

There are a few open points in the review checklist as of today:

1. There are no tests, only examples. This being number-crunching code, it is very difficult to write tests that are meaningful and predictable, given how little control programmers have over the details of float arithmetic (shameless self-advertising: [The Approximation Tower in Computational Science: Why Testing Scientific Software Is Difficult](https://hal.archives-ouvertes.fr/hal-01171382)). Does JOSS have an editorial policy concerning tests for number-crunching software? Or at least recommendations for authors? I didn't find anything.

2. Community guidelines: There are instructions for reporting issues and for seeking support, but not for contributing to the software. See https://github.com/rajeshrinet/pystokes/issues/6.

3. High-level summary in the paper: The current summary is clear enough for potential users of the software, but maybe not "for a diverse, non-specialist audience". But this should best be judged by someone unfamiliar with the field.

4. State of the field: the paper doesn't provide comparisons with other commonly-used packages, but then there are no competing commonly used packages, as far as I can tell. But the authors should definitely say something about this, even if it's only a confirmation of my suspicion.

**Comment by khinsen** [comment]
Contribution guidelines were just added!

**Comment by harpolea** [comment]
@khinsen Thank you for your review! 

As you probably read, the JOSS reviewer criteria for testing can be found [here](https://joss.readthedocs.io/en/latest/review_criteria.html#tests). While not required, it is strongly encouraged that some kind of automated testing suite is set up to test the functionality of the code. 

As you said, testing codes such as these can be tricky. I am not that familiar with this particular branch of CFD, however I imagine there may be some simple, standard test problems with (semi-)analytic solutions? E.g. simple advection tests, tests to demonstrate energy conservation, etc

Regression tests could also be another option. In the codes I work on, we save the output from a selection of problems as benchmarks, then test against these whenever changes are made to the code to ensure that they do not change the output.

**Comment by rajeshrinet** [comment]
@khinsen and @harpolea there are some tests, which run every time someone pushes to the repo (it runs four tests and checks all the notebooks). the folder contains tests is somewhat hidden: pystokes/tests: https://github.com/rajeshrinet/pystokes/tree/master/pystokes/tests 

It does the test of [Stoke's law](https://en.wikipedia.org/wiki/Stokes%27_law) for rotation and translation in an unbounded domain and near a plane wall.

**Comment by rajeshrinet** [comment]
I have now added one more test: compare mobility of a sedimenting lattice with known results in literature (Zick and Homsy, 1982) and moved `tests`  at start of folder tree.

**Comment by khinsen** [comment]
@rajeshrinet I had indeed overlooked the tests! Thanks for making them more visible. And yes, the old Zick/Homsy paper makes for a nice test based on well-known results. Could you add instructions to the README for how to run the tests? That would also ensure their visibility.

**Comment by rajeshrinet** [comment]
@khinsen I have now added it to the README. Thanks for this suggestion.

**Comment by khinsen** [comment]
@rajeshrinet @harpolea Looks good (and the tests all pass on my machine)! I am happy with the software in its current state. I have suggestions for a revision of the paper (see above), but you may prefer to wait for @fcooper8472's feedback before attacking the paper.

**Comment by fcooper8472** [comment]
I think the software looks very good.

I found a few problems with installation, but @rajeshrinet addressed those very quickly - it's great for this to be happening in real time!

In terms of the formal checklist, I have the same two checkboxes un-checked as @khinsen:

- **Summary**: I have some experience in this area (I once coded up a spectral method for solving Navier-Stokes on a periodic domain), but I am not a domain expert and do not understand the whole of the first paragraph.  Even after a bit of time on Google I'm still not certain I know what the phoretic field is, for instance.  I think a "diverse non-specialist audience" would benefit from a paragraph up-front with a higher level overview of what the software is designed to do.

- **State of the field**: I cannot tell from reading the paper whether there is other software available that does a similar task.  Either way, I think this needs stating in the paper.

Other than that, a couple of suggestions:

- The README (until very recently) stated that PyStokes works with Python 2.6+ or Python 3.4+: I've not been able to verify this, but it would be very useful for users to know which versions it works with.  It would be very easy to add a GitHub workflow to test on multiple Python version.  @rajeshrinet would you be interested in a PR that implements that?

- Testing (outside of checking that examples run - which is great!) is fairly thin.  I would encourage coverage checking (suggested [here](https://github.com/rajeshrinet/pystokes/issues/10) to assess what proportion of code is covered by tests, but on top of that it would be great to see a unit testing framework in use.  I understand that some of the number crunching can be very hard to test effectively: but even boring things like the utils would benefit from some testing.

**Comment by rajeshrinet** [comment]
@fcooper8472 and @khinsen many thanks for your comments above and for several suggestions on the repo which have already helped improved the codebase. I am now working on the paper and would update it in the light of your comments.  I will post a comment here when done. 

@fcooper8472, indeed PyStokes was first written in Python 2 and was later modified to support Python 3. Thus, it supports both Python 2 and 3. I have now added GitHub workflow which checks both Python 2 and 3. See the result at: https://github.com/rajeshrinet/pystokes/runs/806434265. I now mention this in the README as well. I am now working on getting the coverage bit up and running.

**Comment by fcooper8472** [comment]
@rajeshrinet this is great!

Just to be clear I do not think the general suggestions I have made about PyStokes are strictly required for publication in JOSS, though it is great that you're addressing these.

**Comment by rajeshrinet** [comment]
@harpolea: thank you very much for your editorial assistance in reviewing our [submission](https://github.com/rajeshrinet/pystokes/blob/master/docs/paper/paper.md). We, the authors (@rajeshrinet and @ronojoy), have revised the manuscript in response to the reviewers suggestions. We detail the changes below and hope that, with these changes, the manuscript can now accepted in JOSS. 


Referee A: @khinsen. 

> @harpolea I did a first pass looking at the code and the paper. It was a lot of fun: this is a very nice implementation of hydrodynamic and phoretic interactions which invites users to play with it, in particular by including visualization tools, and that is just great for doing research. The next time I do work in this domain, I'll happily abandon [my own 25-year-old Fortran library](https://github.com/khinsen/HYDROLIB) and use PyStokes instead!
> 
> I have made a few suggestions for improvements via issues/pull requests on the code repository, which the authors have handled immediately. Interactive reviewing is a fun experience :-)

We thank the referee for a positive evaluation of our code and paper. It has indeed been fun to interactively improve the codebase through discussion on the issue tracker. Responses to specific comments are below:

> 
> There are a few open points in the review checklist as of today:
> 
> 1. There are no tests, only examples. This being number-crunching code, it is very difficult to write tests that are meaningful and predictable, given how little control programmers have over the details of float arithmetic (shameless self-advertising: [The Approximation Tower in Computational Science: Why Testing Scientific Software Is Difficult](https://hal.archives-ouvertes.fr/hal-01171382)). Does JOSS have an editorial policy concerning tests for number-crunching software? Or at least recommendations for authors? I didn't find anything.

We have now upgraded our testing and made it more visible. We followed the referee's suggestion to add details to the REAMDE on how to test the code. 

> 2. Community guidelines: There are instructions for reporting issues and for seeking support, but not for contributing to the software. See [rajeshrinet/pystokes#6](https://github.com/rajeshrinet/pystokes/issues/6).

A [CONTRIBUTING.md](https://github.com/rajeshrinet/pystokes/blob/master/CONTRIBUTING.md) was added. 

> 3. High-level summary in the paper: The current summary is clear enough for potential users of the software, but maybe not "for a diverse, non-specialist audience". But this should best be judged by someone unfamiliar with the field.

We have now added a new paragraph at the start of the paper and added a new figure. Both are at page 1. We hope that this will be helpful as a high-level summary. 

> 4. State of the field: the paper doesn't provide comparisons with other commonly-used packages, but then there are no competing commonly used packages, as far as I can tell. But the authors should definitely say something about this, even if it's only a confirmation of my suspicion.

We have now clearly described on page 3 of our paper that hydrodynamic interactions of active particles are obtained in terms of mobility matrices and propulsion tensors. Two libraries which compute mobility matrices have been cited, while we are not aware of any library, other than PyStokes, that evaluates propulsion tensors to compute hydrodynamic interactions of active particles. 


Referee 2: @fergusc

> I think the software looks very good.
> 
> I found a few problems with installation, but @rajeshrinet addressed those very quickly - it's great for this to be happening in real time!
> 
> In terms of the formal checklist, I have the same two checkboxes un-checked as @khinsen:
> 

We thank the referee for a positive evaluation and comments on our submission. It was indeed very helpful in improving installation instructions using PyPI. 

> * **Summary**: I have some experience in this area (I once coded up a spectral method for solving Navier-Stokes on a periodic domain), but I am not a domain expert and do not understand the whole of the first paragraph.  Even after a bit of time on Google I'm still not certain I know what the phoretic field is, for instance.  I think a "diverse non-specialist audience" would benefit from a paragraph up-front with a higher level overview of what the software is designed to do.
> * **State of the field**: I cannot tell from reading the paper whether there is other software available that does a similar task.  Either way, I think this needs stating in the paper.
> 

As mentioned in response to referee A (@khinsen), we have now revised the paper and added more details for a non-specialist audience including a figure on page 1 which gives a high-level summary. 

> Other than that, a couple of suggestions:
> 
> * The README (until very recently) stated that PyStokes works with Python 2.6+ or Python 3.4+: I've not been able to verify this, but it would be very useful for users to know which versions it works with.  It would be very easy to add a GitHub workflow to test on multiple Python version.  @rajeshrinet would you be interested in a PR that implements that?

We have now updated the testing and it is available for both python 2.7 and 3.7 using GitHub workflow. We have also added a badge in the README: [![Python Version](https://img.shields.io/pypi/pyversions/pystokes)](https://pypi.org/project/pystokes). 


> * Testing (outside of checking that examples run - which is great!) is fairly thin.  I would encourage coverage checking (suggested [here](https://github.com/rajeshrinet/pystokes/issues/10) to assess what proportion of code is covered by tests, but on top of that it would be great to see a unit testing framework in use.  I understand that some of the number crunching can be very hard to test effectively: but even boring things like the utils would benefit from some testing.

As discussed [here](https://github.com/rajeshrinet/pystokes/issues/10), coverage checking for a cython codebase leads to performance loss. Thus, we have decided against coverage checking, pending a solution that does not compromise on speed.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02318/joss.02318/10.21105.joss.02318.pdf)

**Comment by harpolea** [comment]
@rajeshrinet Great – thanks for your quick response!

@khinsen and @fcooper8472: are you happy with these changes, and do you think that they satisfy the requirements to check off the last points in the review checklist?

**Comment by fcooper8472** [comment]
The additional paragraph at the start really helps - it's clear and certainly makes it more accessible to a non-specialist.

The only remaining concern is still about other software packages.  I still do not think there is an assertion that no other similar software exists, or a description of other packages, so I'm still not 100% sure I can tick

"Do the authors describe how this software compares to other commonly-used packages?"

@rajeshrinet are there other packages that do anything in the same vein?  If not could you add a sentence to this effect?

**Comment by rajeshrinet** [comment]
@fcooper8472 thanks for your comments. 

A  search on GitHub does not find anything comparable to PyStokes. There are libraries, such as Ludwig (from EPCC, Edinburgh) which simulates the hydrodynamics of point particles, resolving the fluid degrees of freedom. It does not include phoretic interactions. In terms of the functionality of simultaneously resolving both phoretic and hydrodynamic interactions, we think that PyStokes is, as of this writing, unique. Thus we note in our revision that:

> To the best of our knowledge, PyStokes is the only numerical implementation of propulsion tensors to model suspensions of active particles.

**Comment by fcooper8472** [comment]
Ah! My apologies @rajeshrinet, I missed that sentence.

@harpolea I can confirm that the current version is acceptable as far as I'm concerned.

**Comment by harpolea** [comment]
Great, thanks @fcooper8472 !

**Comment by khinsen** [comment]
@harpolea @rajeshrinet I am happy with the updated paper as well. Figure 1 in particular is a very nice summary of how everything fits together. The authors' description of the state of the art looks accurate as well. So... I just ticked off the last boxes of my checklist! Ready for take-off!

**Comment by khinsen** [comment]
Ahhh.... a minor nitpick I noticed while closing the open PDF file! The proper title for Odqvist 1930 is "Über die Randwertaufgaben der Hydrodynamik zäher Flüssigkeiten", with all capitalization required by German grammar.

**Comment by rajeshrinet** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02318/joss.02318/10.21105.joss.02318.pdf)

**Comment by rajeshrinet** [comment]
@fcooper8472 and @khinsen thanks very much for your comments. @khinsen thanks for suggesting fix in the reference. It has now been updated.

**Comment by harpolea** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/1.9780898718003.bm is OK
- 10.1137/1.9781611973242 is OK
- 10.1007/978-3-319-12787-3 is OK
- 10.1007/BF01194638 is OK
- 10.1063/1.5090179 is OK
- 10.1088/2399-6528/aaab0d is OK
- 10.1103/PhysRevLett.117.228002 is OK
- 10.1039/B918598D is OK
- 10.1146/annurev.fl.21.010189.000425 is OK
- 10.1103/PhysRevLett.124.088003 is OK
- 10.1017/S0022112075001486 is OK
- 10.1017/S0022112082000627 is OK
- 10.1017/CBO9780511624124 is OK
- 10.1017/S0022112095003260 is OK
- 10.1016/j.enganabound.2004.12.001 is OK
- 10.1073/pnas.1718807115 is OK
- 10.1016/0010-4655(95)00029-F is OK
- 10.1146/annurev.fl.09.010177.002011 is OK

MISSING DOIs

- https://doi.org/10.2307/3613759 may be missing for title: The mathematical theory of viscous incompressible flow
- https://doi.org/10.1080/17797179.2017.1294829 may be missing for title: Fluctuating hydrodynamics and the Brownian motion of an active colloid near a wall
- https://doi.org/10.1088/1742-5468/2015/06/p06017 may be missing for title: Many-body microhydrodynamics of colloidal particles with active boundary layers

INVALID DOIs

- None
```

**Comment by harpolea** [comment]
Thanks @khinsen!

@rajeshrinet: I'm just going through the references now. As whedon pointed out, there are a couple that are missing DOIs (the first one doesn't seem to match up, but the latter two look good to me). Would you be able to add them?

**Comment by rajeshrinet** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/1.9780898718003.bm is OK
- 10.1137/1.9781611973242 is OK
- 10.1007/978-3-319-12787-3 is OK
- 10.1007/BF01194638 is OK
- 10.1063/1.5090179 is OK
- 10.1088/2399-6528/aaab0d is OK
- 10.1080/17797179.2017.1294829 is OK
- 10.1103/PhysRevLett.117.228002 is OK
- 10.1088/1742-5468/2015/06/p06017 is OK
- 10.1039/B918598D is OK
- 10.1146/annurev.fl.21.010189.000425 is OK
- 10.1103/PhysRevLett.124.088003 is OK
- 10.1017/S0022112075001486 is OK
- 10.1017/S0022112082000627 is OK
- 10.1017/CBO9780511624124 is OK
- 10.1017/S0022112095003260 is OK
- 10.1016/j.enganabound.2004.12.001 is OK
- 10.1073/pnas.1718807115 is OK
- 10.1016/0010-4655(95)00029-F is OK
- 10.1146/annurev.fl.09.010177.002011 is OK

MISSING DOIs

- https://doi.org/10.2307/3613759 may be missing for title: The mathematical theory of viscous incompressible flow

INVALID DOIs

- None
```

**Comment by harpolea** [comment]
@rajeshrinet thanks! I've made a PR with fixes to a couple of the references. One was missing a title and for another the DOI pointed to a different article

**Comment by harpolea** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02318/joss.02318/10.21105.joss.02318.pdf)

**Comment by rajeshrinet** [comment]
> @rajeshrinet thanks! I've made a PR with fixes to a couple of the references. One was missing a title, and for another the DOI pointed to a different article

Thanks @harpolea. It has now beed merged.

**Comment by harpolea** [comment]
@rajeshrinet Thanks! 

At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g. figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by rajeshrinet** [comment]
@harpolea , 

* I have now added a new tagged release: [v2.2.0](https://github.com/rajeshrinet/pystokes/releases/tag/v2.2.0)

* the version has been archived on Zeonodo: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3923867.svg)](https://doi.org/10.5281/zenodo.3923867) <br/>

**Comment by harpolea** [comment]
@rajeshrinet the Zenodo release seems to have been mistakenly dated to November 2014. Could you fix that? (I think you should be able to edit the metadata?)

**Comment by harpolea** [comment]
@rajeshrinet I see that's now fixed - must have just been a Zenodo bug!

**Comment by rajeshrinet** [comment]
@harpolea thanks, just fixed it:

![Screenshot 2020-06-30 at 1 57 23 PM](https://user-images.githubusercontent.com/5037991/86128770-b70d6780-bad9-11ea-81f5-fa95ce1ee5ff.png)

**Comment by harpolea** [comment]
@whedon set 10.5281/zenodo.3923867 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3923867" target="_blank">10.5281/zenodo.3923867</a> is the archive.

**Comment by harpolea** [comment]
@whedon set v2.2.0 as version

**Comment by whedon** [comment]
OK. v2.2.0 is the version.

**Comment by harpolea** [comment]
@rajeshrinet: this all looks good to me, so I'm going to go ahead and recommend this for acceptance

@khinsen and @fcooper8472: thank you again for your work reviewing this submission!

**Comment by harpolea** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/1.9780898718003.bm is OK
- 10.1007/978-3-319-12787-3 is OK
- 10.1007/BF01194638 is OK
- 10.1063/1.5090179 is OK
- 10.1088/2399-6528/aaab0d is OK
- 10.1080/17797179.2017.1294829 is OK
- 10.1103/PhysRevLett.117.228002 is OK
- 10.1088/1742-5468/2015/06/p06017 is OK
- 10.1039/B918598D is OK
- 10.1146/annurev.fl.21.010189.000425 is OK
- 10.1103/PhysRevLett.124.088003 is OK
- 10.1017/S0022112075001486 is OK
- 10.1017/S0022112082000627 is OK
- 10.1017/CBO9780511624124 is OK
- 10.1017/S0022112095003260 is OK
- 10.1016/j.enganabound.2004.12.001 is OK
- 10.1073/pnas.1718807115 is OK
- 10.1016/0010-4655(95)00029-F is OK
- 10.1146/annurev.fl.09.010177.002011 is OK

MISSING DOIs

- https://doi.org/10.2307/3613759 may be missing for title: The mathematical theory of viscous incompressible flow

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1520

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1520, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1277959504001458176) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1521
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02318](https://doi.org/10.21105/joss.02318)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @fcooper8472 & @khinsen for reviewing!
And to @harpolea for editing!

Congratulations to @rajeshrinet (Rajesh Singh) and co-author!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02318/status.svg)](https://doi.org/10.21105/joss.02318)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02318">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02318/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02318/status.svg
   :target: https://doi.org/10.21105/joss.02318
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02318/status.svg)](https://doi.org/10.21105/joss.02318)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
