### ISSUE TITLE
[PRE REVIEW]: shinyssdtools: A web application for fitting Species Sensitivity Distributions (SSDs)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2319]
**Submitting author:** @sebdalgarno (<a href="http://orcid.org/0000-0002-3658-4517">Sebastian Dalgarno</a>)
**Repository:** <a href="https://github.com/bcgov/shinyssdtools" target ="_blank">https://github.com/bcgov/shinyssdtools</a>
**Version:** v0.0.1
**Editor:** @marcosvital
**Reviewers:** @elimillera, @meenakshi-kushwaha, @nanhung
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sebdalgarno. **Currently, there isn't an JOSS editor assigned** to your paper.

@sebdalgarno if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (426.3 files/s, 25749.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               17            171             87           1318
Markdown                         9            112              0            276
CSS                              1             31              3            175
TeX                              1              5              0             48
SVG                              9              0              0              9
-------------------------------------------------------------------------------
SUM:                            37            319             90           1826
-------------------------------------------------------------------------------


Statistical information for the repository '2319' was gathered on 2020/06/11.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2319 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon.rb:210:in `[]': no implicit conversion of String into Integer (TypeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon.rb:210:in `block in parse_affiliations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon.rb:209:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon.rb:209:in `parse_affiliations'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon.rb:195:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon.rb:91:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01082 is OK
- 10.21105/joss.00785 is OK

MISSING DOIs

- https://doi.org/10.1201/9781420032314 may be missing for title: Species Sensitivity Distributions in Ecotoxicology

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@openjournals/dev -- this paper is throwing an error at compilation: please help

**Comment by arfon** [comment]
This is because the YAML header is malformed. @sebdalgarno - please update the YAML header of your `paper.md` to look like this:

```
---
title: 'shinyssdtools: A web application for fitting Species Sensitivity Distributions (SSDs)'
date: '2020-06-02'
authors:
- affiliation: 1
  name: Seb Dalgarno
  orcid: 0000-0002-3658-4517
affiliations:
- name: Poisson Consulting, Nelson, British Columbia
  index: 1
bibliography: paper.bib
tags:
   - R
   - Shiny
   - ssdtools
   - species sensitivity distributions
---
```

**Comment by sebdalgarno** [comment]
I've pushed a fix - thanks

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02319/joss.02319/10.21105.joss.02319.pdf)

**Comment by sebdalgarno** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by sebdalgarno** [comment]
meenakshi-kushwaha may be a suitable reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@sebdalgarno thank you for your submission. The editorial board has decided this work is unfortunately not in scope for JOSS (see also our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and statements on "Minor ‘utility’ packages, including ‘thin’ API clients, and single-function packages").  Of course this conclusion says nothing about the value/usefulness of the work submitted, it merely means JOSS is not the right place to publish it. We will therefore proceed to reject this work as it stands.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by sebdalgarno** [comment]
Hi @Kevin-Mattheus-Moerman I've just updated our README to indicate the additional functionality and value that this software adds to ssdtools. This includes: translation to French; generation of R code for user to reproduce results; further customization of plot and table outputs.

**Comment by joethorley** [comment]
Hi @Kevin-Mattheus-Moerman as a reviewer for JOSS and  the co-author of the underlying ssdtools R package I'd ask that you reconsider your initial decision based on the additional information provided by @sebdalgarno. shinyssdtools is an R package of over 1,300 lines of code and 14 functions that took @sebdalgarno than 110 hours to program (I'm also his line-manager!). In addition to providing a multi-panel user-friendly GUI, and adding the functionality indicated above, it also provides substantially more features than the shinyssd R package that was recently published in JOSS  ([D'Andrea et al. 2019](https://joss.theoj.org/papers/10.21105/joss.00785)). shinyssdtools was commissioned by the BC/Canadian government, is being considered for adoption by the Australian government and represents an important development for many users in the field. I recommended to @sebdalgarno that he attempt to publish in JOSS as I am a co-author on a paper that is ready for submission with 8 other Canadian/Australian scientists that reviews the software available for fitting SSDs. I am hoping that we will be able to cite shinyssdtools so that @sebdalgarno receives full credit for his work.

**Comment by sebdalgarno** [comment]
hi @Kevin-Mattheus-Moerman is there a chance of reconsideration or appeal for this paper?

**Comment by joethorley** [comment]
@Kevin-Mattheus-Moerman Is it possible to respond to our questions?

**Comment by Kevin-Mattheus-Moerman** [comment]
@joethorley @sebdalgarno apologies for the delay in getting back to you. I will consider your comments and will bring this up with the board soon. 
You say you expanded the readme with notes on functionality. Can you create/reproduce a clear description of the key functionality here and also work it into the paper? Can you make sure you include a clear description of the significant impact this software has on scientific research? This would help us when we reconsider this work. 
I'll recreate the paper here now too and you can run `@whedon generate pdf` to update the paper if you like.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02319/joss.02319/10.21105.joss.02319.pdf)

**Comment by sebdalgarno** [comment]
Hi @Kevin-Mattheus-Moerman. Thanks for the suggestions to expand on functionality that shinyssdtools provides in addition to sddtools and it’s impact contribution to the scientific community. I’ve now added these to the paper and will now regenerate the pdf.

With respect to additional functionality, shinyssdtools provides: translation to French; generation of R code to reproduce results from a session; further customization of plot and table outputs; download of tables and plot outputs. 

With respect to impact on scientific community: It has been adopted by the governments of British Columbia, Canada and Australia to set water quality benchmarks and to characterize the effects of chemical contaminants for water quality and/or ecological risk assessment purposes. 

Finally, it’s worth noting that a manuscript which reviews Species Sensitivity Distribution software in Environmental Toxicology and Chemistry (Manuscript ID ETCJ-Jun-20-00450) has been accepted needing major revisions. If this shinyssdtools manuscript is accepted by August 7th, it will be cited in that manuscript.

**Comment by sebdalgarno** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02319/joss.02319/10.21105.joss.02319.pdf)

**Comment by sebdalgarno** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02319/joss.02319/10.21105.joss.02319.pdf)

**Comment by sebdalgarno** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02319/joss.02319/10.21105.joss.02319.pdf)

**Comment by arfon** [comment]
@whedon check repository

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (402.5 files/s, 29109.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               17            171             87           1330
HTML                             1             88              5            398
Markdown                         9            115              0            283
CSS                              1             31              3            175
TeX                              1              5              0             48
SVG                              9              0              0              9
-------------------------------------------------------------------------------
SUM:                            38            410             95           2243
-------------------------------------------------------------------------------


Statistical information for the repository '534ea4ea9e7fd90d96a91b24' was
gathered on 2020/10/26.
No commited files with the specified extensions were found.
```

**Comment by arfon** [comment]
@sebdalgarno - looks like this submission got lost in our editorial processes. I've flagged this for an additional editorial review will will likely take another week or so.

**Comment by sebdalgarno** [comment]
thanks @arfon I look forward to the review!

**Comment by Kevin-Mattheus-Moerman** [comment]
@sebdalgarno after further review we decided this work is in scope for JOSS. We will now proceed to find an editor to handle this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@KristinaRiemer @marcosvital @luizirber can one of you handle this submission? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@KristinaRiemer @marcosvital @luizirber can you help with this submission?

**Comment by marcosvital** [comment]
I'll be happy handle this submission, @Kevin-Mattheus-Moerman.

**Comment by marcosvital** [comment]
@whedon assign @marcosvital as editor

**Comment by whedon** [comment]
OK, the editor is @marcosvital

**Comment by marcosvital** [comment]
Hi, @sebdalgarno, I will be the editor of your submission.

I see you already sent one reviewer suggestion (meenakshi-kushwaha), and I'll start looking for two more - let me know if you have any other potential reviewers to suggest, ok? If you haven't see it yet, we have [this list of people](https://bit.ly/joss-reviewers) that have agreed to review for JOSS.

In the meantime, please include the "statement of need" a separate paragraph, it should look like [this](https://joss.theoj.org/papers/10.21105/joss.02584) or [this](https://joss.theoj.org/papers/10.21105/joss.02342).

Also, do you think you can expand the explanation on what does the package do with a more general, less technical explanation? JOSS guidelines for the summary asks for a "description of the high-level functionality and purpose of the software for a diverse, non-specialist audience". Usually, this can be easily achieved with one or two phrases at the beggening of the summary (and I think that both papers linked above are good examples for that).

**Comment by marcosvital** [comment]
Dear @meenakshi-kushwaha, @puruckertom and @elimillera, would you be willing to review this submission for JOSS?

We carry out an open checklist-driven reviews here in GitHub issues, and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review issue, and once there are enough reviewers we will move on to a new issue where the review will take place. If you are not able to review, please let us know if you have recommendations for other reviewers that could help with this submission.

If you are willing to review this submission, please take a look at [JOSS Conflict of Interest Policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy).

**Comment by elimillera** [comment]
@marcosvital I would be happy to review. I don't have any conflicts of interests to report. Thanks!

**Comment by meenakshi-kushwaha** [comment]
@marcosvital I will be happy to review. Thanks!

**Comment by marcosvital** [comment]
Thank you so much, @elimillera and @meenakshi-kushwaha. I will try to find a third reviewer, so we can move on to reviwieng.

**Comment by marcosvital** [comment]
Dear @nanhung would you be willing to review this submission for JOSS?

We carry out an open checklist-driven reviews here in GitHub issues, and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review issue, and once there are enough reviewers we will move on to a new issue where the review will take place. If you are not able to review, please let us know if you have recommendations for other reviewers that could help with this submission.

If you are willing to review this submission, please take a look at JOSS Conflict of Interest Policy.

**Comment by nanhung** [comment]
@marcosvital I am willing to review. I have no COI. Thanks!

**Comment by sebdalgarno** [comment]
> Hi, @sebdalgarno, I will be the editor of your submission.
> 
> I see you already sent one reviewer suggestion (meenakshi-kushwaha), and I'll start looking for two more - let me know if you have any other potential reviewers to suggest, ok? If you haven't see it yet, we have [this list of people](https://bit.ly/joss-reviewers) that have agreed to review for JOSS.
> 
> In the meantime, please include the "statement of need" a separate paragraph, it should look like [this](https://joss.theoj.org/papers/10.21105/joss.02584) or [this](https://joss.theoj.org/papers/10.21105/joss.02342).
> 
> Also, do you think you can expand the explanation on what does the package do with a more general, less technical explanation? JOSS guidelines for the summary asks for a "description of the high-level functionality and purpose of the software for a diverse, non-specialist audience". Usually, this can be easily achieved with one or two phrases at the beggening of the summary (and I think that both papers linked above are good examples for that).

Thanks @marcosvital ! I've made the requested revisions (statement of need and some added context at beginning). I've also added reference to a recently published article on recent advances in SSD methods and added a section to the contributions section comparing shinyssdtools to the US EPA ssd Toolbox

**Comment by sebdalgarno** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02319/joss.02319/10.21105.joss.02319.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02319/joss.02319/10.21105.joss.02319.pdf) :page_facing_up: :point_left:

**Comment by marcosvital** [comment]
Thanks for the revisions, @sebdalgarno. The proof seems ready for revision.

@nanhung, thank you. We will start the revision process right away.

**Comment by marcosvital** [comment]
@whedon assign @elimillera as reviewer

**Comment by whedon** [comment]
OK, @elimillera is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @meenakshi-kushwaha  as reviewer

**Comment by whedon** [comment]
OK, @meenakshi-kushwaha  is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @nanhung as reviewer

**Comment by whedon** [comment]
OK, @nanhung is now a reviewer

**Comment by marcosvital** [comment]
OK, we will now move on to a new issue for the reviewing process.

**Comment by marcosvital** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2848.

**Comment by arfon** [comment]
@marcosvital - apologies for the small hiccup with Whedon there.
