### ISSUE TITLE
[PRE REVIEW]: Rawls: A Python package for managing .rawls image files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2320]
**Submitting author:** @jbuisine (<a href="http://orcid.org/0000-0001-6071-744X">Jérôme BUISINE</a>)
**Repository:** <a href="https://github.com/prise-3d/rawls" target ="_blank">https://github.com/prise-3d/rawls</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jbuisine. **Currently, there isn't an JOSS editor assigned** to your paper.

@jbuisine if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.42 s (243.2 files/s, 69131.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      11           2200           2239           8326
HTML                            36           4209             35           5989
SVG                              1              0              0           2671
CSS                              4            164             34            642
Python                          15            350            584            582
Markdown                         3            106              0            195
reStructuredText                27            319            298            154
TeX                              1              7              0             66
YAML                             2             10              4             51
make                             1              5              6             11
Bourne Shell                     2              4              2             10
-------------------------------------------------------------------------------
SUM:                           103           7374           3202          18697
-------------------------------------------------------------------------------


Statistical information for the repository '2320' was gathered on 2020/06/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jérôme BUISINE                  33         27384          13103          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jérôme BUISINE            14281           52.2          2.9               17.81
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/978-3-642-56046-0_19 may be missing for title: Efficient bidirectional path tracing by randomized quasi-Monte Carlo integration
- https://doi.org/10.1145/2532708 may be missing for title: Boosting monte carlo rendering by ray histogram fusion
- https://doi.org/10.1111/cgf.13231 may be missing for title: Bayesian collaborative denoising for Monte Carlo rendering
- https://doi.org/10.1145/3072959.3073601 may be missing for title: Interactive reconstruction of Monte Carlo image sequences using a recurrent denoising autoencoder

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02320/joss.02320/10.21105.joss.02320.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@hugoledoux is this something you could handle as editor? @bmcfee I know you are quite busy but if this is still available at a later point perhaps you can consider this one too.

**Comment by hugoledoux** [comment]
I already have 4 running and I'm afraid I won't be able to do them all, sorry.

**Comment by Kevin-Mattheus-Moerman** [comment]
@hugoledoux that is okay. However given our "reduced service mode" (explained above) it is okay if we are slower dealing with the submission. If this work is in your domain it would be great to assign this to you now. However you can just get to it and deal with this work once you have time for it? Does that sound okay? If you'd rather not right now that is fine too. Thanks either way.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jbuisine While we are working to assign an editor, perhaps you can make some changes to your paper in the mean time. Our system is showing you might be missing DOI's in your citations. Can you work on adding them? You can call `@whedon generate pdf` and also `@whedon check references` here to see if they pass the test after making changes.

**Comment by jbuisine** [comment]
@Kevin-Mattheus-Moerman Thanks for your advice, I'll update the paper quickly with the changes.

**Comment by jbuisine** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-642-56046-0_19 is OK
- 10.1145/2532708 is OK
- 10.1111/cgf.13231 is OK
- 10.1145/3072959.3073601 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbuisine** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02320/joss.02320/10.21105.joss.02320.pdf)

**Comment by hugoledoux** [comment]
If it's really impossible to find someone else I could do it, but it might be slow... I don't really know that field though...

**Comment by Kevin-Mattheus-Moerman** [comment]
@hugoledoux okay. No worries, thanks. I'll look for others to help and will ping you if I get stuck.

**Comment by arfon** [comment]
@jbuisine - many thanks for your submission to JOSS. After consulting with the JOSS editorial team, we have deemed that this submission is out of scope and does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). Specifically, while this package looks useful, it fails into out 'minor utility' category.

Thanks again for your interest in JOSS.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
