### ISSUE TITLE
[PRE REVIEW]: ojsr: Crawler/scraper for Open Journal System

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2321]
**Submitting author:** @gastonbecerra (<a href="http://orcid.org/0000-0001-9432-8848">gastón becerra</a>)
**Repository:** <a href="https://github.com/gastonbecerra/ojsr" target ="_blank">https://github.com/gastonbecerra/ojsr</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gastonbecerra. **Currently, there isn't an JOSS editor assigned** to your paper.

@gastonbecerra if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (342.5 files/s, 31511.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                6            118            181            355
Markdown                         4             42              0            107
TeX                              1             24              0             96
Rmd                              1             78            116             77
YAML                             1              0              0              2
-------------------------------------------------------------------------------
SUM:                            13            262            297            637
-------------------------------------------------------------------------------


Statistical information for the repository '2321' was gathered on 2020/06/11.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1108/07378830510636300 is OK
- 10.1051/0004-6361/201629272 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.1108/07378830510636300 is OK

MISSING DOIs

- https://doi.org/10.3201/eid1209.060643 may be missing for title: The Access Principle. The Case for Open Access to Research and Scholarship

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02321/joss.02321/10.21105.joss.02321.pdf)

**Comment by labarba** [comment]
@gastonbecerra -- After a pre-review of your submission, and an assessment by the editorial board at large, we find that it does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). In particular, while the software seems useful, it falls under the 'Minor utility' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.

**Comment by labarba** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
