### ISSUE TITLE
[PRE REVIEW]: MATLAB codes for finding dense and sparse spanning trees of a given graph

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2322]
**Submitting author:** @mustafaozen (<a href="http://orcid.org/0000-0002-7708-6549">Mustafa Ozen</a>)
**Repository:** <a href="https://github.com/mustafaozen/Dense-Sparse-Spanning-Trees-Genetic-Algorithm" target ="_blank">https://github.com/mustafaozen/Dense-Sparse-Spanning-Trees-Genetic-Algorithm</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mustafaozen. **Currently, there isn't an JOSS editor assigned** to your paper.

@mustafaozen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (456.2 files/s, 21783.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                           9            101            113            162
Markdown                         2             29              0             93
TeX                              1              6              0             69
-------------------------------------------------------------------------------
SUM:                            12            136            113            324
-------------------------------------------------------------------------------


Statistical information for the repository '2322' was gathered on 2020/06/11.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/S0305-0548(00)00007-1 is OK
- 10.1371/journal.pone.0184912 is OK
- 10.20429/tag.2016.030101 is OK
- 10.19139/soic-2310-5070-855 is OK
- 10.1007/s11590-013-0665-y is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02322/joss.02322/10.21105.joss.02322.pdf)

**Comment by labarba** [comment]
@mustafaozen -- After a pre-review of your submission, and an assessment by the editorial board at large, we find that it does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). In particular, while the software seems useful, it falls under the 'Minor utility' category, and we therefore decided not to put it through review. 

Thank you for considering JOSS as a venue for your software, and I hope you'll submit other software with research application in the future.

**Comment by labarba** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
