### ISSUE TITLE
[PRE REVIEW]: pyomeca: An Open-Source Framework for Biomechanical Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2323]
**Submitting author:** @romainmartinez (<a href="http://orcid.org/0000-0001-9681-9448">Romain Martinez</a>)
**Repository:** <a href="https://github.com/pyomeca/pyomeca/" target ="_blank">https://github.com/pyomeca/pyomeca/</a>
**Version:** 2020.0.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @BKillen05,  @mitkof6
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @romainmartinez. **Currently, there isn't an JOSS editor assigned** to your paper.

@romainmartinez if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.45 s (150.4 files/s, 214851.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             12              0            134          25912
Python                          32            821           1241           2147
Markdown                        13            241              0            711
JavaScript                       2             37              1            260
Jupyter Notebook                 2              0          63713            147
YAML                             3             15              1            109
TeX                              1             10              0            101
CSS                              1             12              0             51
make                             1              6              1             19
-------------------------------------------------------------------------------
SUM:                            67           1142          65091          29457
-------------------------------------------------------------------------------


Statistical information for the repository '2323' was gathered on 2020/06/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Pariterre                       73         27028          15724           31.81
Romain Martinez                136         38155          48521           64.49
pariterre                       19           863            211            0.80
romain                          29          3383            517            2.90

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Pariterre                    63            0.2          5.7               14.29
romain                     4444          131.4          1.2                2.79
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02323/joss.02323/10.21105.joss.02323.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.5334/jors.148 may be missing for title: xarray: N-D labeled Arrays and Datasets in Python
- https://doi.org/10.25080/majora-92bf1922-00a may be missing for title: Data structures for statistical computing in python
- https://doi.org/10.1109/mcse.2007.55 may be missing for title: Matplotlib: A 2D Graphics Environment
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy Array: A Structure for Efficient Numerical Computation
- https://doi.org/10.1016/j.cmpb.2016.11.007 may be missing for title: biomechZoo: An open-source toolbox for the processing, analysis, and visualization of biomechanical movement data
- https://doi.org/10.21105/joss.00927 may be missing for title: CusToM: a Matlab toolbox for musculoskeletal simulation
- https://doi.org/10.1007/s00530-019-00633-9 may be missing for title: RMoCap: an R language package for processing and kinematic analyzing motion capture data

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@modenaxe @moorepants @ekjchadwick @Juanfrandepatech would you be interested in reviewing this submission for JOSS? 

The review is on GitHub and focuses on [the software](https://github.com/pyomeca/pyomeca/) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02323/joss.02323/10.21105.joss.02323.pdf).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @BKillen05 as reviewer

**Comment by whedon** [comment]
OK, @BKillen05 is now a reviewer

**Comment by modenaxe** [comment]
Hi @Kevin-Mattheus-Moerman, I won't be able to help with this submission, I am on annual leave. [Dimitar](https://github.com/mitkof6) could be a potential good alternative reviewer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mitkof6 would you be able to help with this review?

**Comment by mitkof6** [comment]
Hi @Kevin-Mattheus-Moerman I can review this. When is the deadline?

**Comment by Kevin-Mattheus-Moerman** [comment]
@mitkof6 we tend to aim for 2 weeks but we can be flexible

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add  @mitkof6 as reviewer

**Comment by whedon** [comment]
OK,  @mitkof6 is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2431.
