### ISSUE TITLE
[PRE REVIEW]: MetalWalls: A classical molecular dynamics software dedicated to the simulation of electrochemical systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2324]
**Submitting author:** @salanne (<a href="http://orcid.org/0000-0002-1753-491X">Mathieu Salanne</a>)
**Repository:** <a href="https://gitlab.com/ampere2/metalwalls" target ="_blank">https://gitlab.com/ampere2/metalwalls</a>
**Version:** version 1
**Editor:** @richardjgowers
**Reviewers:** @mattwthompson, @hmacdope
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @salanne. **Currently, there isn't an JOSS editor assigned** to your paper.

@salanne if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1063/1.469429 may be missing for title: Influence of Surface-Topology and Electrostatic Potential on Water Electrode Systems
- https://doi.org/10.1038/nmat3260 may be missing for title: On the Molecular Origin of Supercapacitance in Nanoporous Carbon Electrodes
- https://doi.org/10.1073/pnas.1301596110 may be missing for title: Hydration of metal surfaces can be dynamically heterogeneous and hydrophobic
- https://doi.org/10.1021/acsnano.6b03753.s001 may be missing for title: Dynamic Response in Nanoelectrowetting on a Dielectric
- https://doi.org/10.1103/physrevx.8.021024 may be missing for title: Blue Energy and Desalination with Nanoporous Carbon Electrodes: Capacitance from Molecular Simulations to Continuous Models
- https://doi.org/10.1063/1.5055704 may be missing for title: Communication: Constrained molecular dynamics for polarizable models
- https://doi.org/10.1039/d0cp00163e may be missing for title: Adiabatic motion and statistical mechanics via mass zero constrained dynamics
- https://doi.org/10.1063/5.0007192 may be missing for title: Mass-zero constrained molecular dynamics for electrode charges in simulations of electrochemical systems
- https://doi.org/10.1103/physrevlett.123.195501 may be missing for title: Simulating Electrochemical Systems by Combining the Finite Field Method with a Constant Potential Electrode

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02324/joss.02324/10.21105.joss.02324.pdf)

**Comment by labarba** [comment]
👋  @jgostick -- the submitting author suggested you as handling editor: please have a look and let us know if you are willing and able to take this one.

**Comment by salanne** [comment]
Hello, I looked at the list of joss_reviewers and I found the following list of people who may be suitable: luthaf, hmacdope, masrul, thesketh, amritagos, bjmorgan . Concerning bjmorgan we had some collaborations before but he knows very well the models tackled by the code.

**Comment by labarba** [comment]
@whedon invite @jgostick as editor

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by jgostick** [comment]
I'm doing one already and it's not going too smoothly, so I think I'd best pass on this.

**Comment by salanne** [comment]
No problem! Maybe I can suggest @richardjgowers ?

**Comment by richardjgowers** [comment]
@Whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by salanne** [comment]
I have updated the missing DOIs in the paper.bib file

**Comment by richardjgowers** [comment]
@bjmorgan @hmacdope @luthaf are you free to review this?

**Comment by hmacdope** [comment]
@richardjgowers happy to review. :)

**Comment by Luthaf** [comment]
I don't think I'll have time for this one, I have a lot of other things going on right now =)

**Comment by richardjgowers** [comment]
@mattwthompson fancy reviewing this?

**Comment by mattwthompson** [comment]
Sure!

I'd like to briefly note that Mathieu and I had a meeting or two about collaborating in 2014 or 2015, but that never materialized (and no other collaborations or affiliations since, with him or any other author). My reading of the JOSS COI policy is that this does not qualify COI, and I don't think I'm unable to impartially review the work. Just thought I'd note. If this sounds fine @richardjgowers I'll get started over this weekend.

**Comment by richardjgowers** [comment]
@mattwthompson yep that sounds fine, it's hard not to know people :)

**Comment by richardjgowers** [comment]
@whedon assign @hmacdope as reviewer

**Comment by whedon** [comment]
OK, @hmacdope is now a reviewer

**Comment by richardjgowers** [comment]
@whedon assign @mattwthompson as reviewer

**Comment by whedon** [comment]
OK, @mattwthompson is now a reviewer

**Comment by richardjgowers** [comment]
@whedon add @hmacdope as reviewer

**Comment by whedon** [comment]
OK, @hmacdope is now a reviewer

**Comment by richardjgowers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2373.
