### ISSUE TITLE
[PRE REVIEW]: VRPy: A Python package for solving a range of vehicle routing problems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2325]
**Submitting author:** @Kuifje02 (<a href="http://orcid.org/0000-0003-3139-4519">Romain Montagne</a>)
**Repository:** <a href="https://github.com/Kuifje02/vrpy" target ="_blank">https://github.com/Kuifje02/vrpy</a>
**Version:** 0.2.0
**Editor:** @bstabler
**Reviewers:** @skadio
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Kuifje02. **Currently, there isn't an JOSS editor assigned** to your paper.

@Kuifje02 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (214.9 files/s, 50423.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          29            455            843           3240
reStructuredText                 8            378            522            340
TeX                              2             29              0            299
Markdown                         3             52              0            124
YAML                             2              9             14             83
Jupyter Notebook                 1              0           4320             81
INI                              1              0              0              4
-------------------------------------------------------------------------------
SUM:                            46            923           5699           4171
-------------------------------------------------------------------------------


Statistical information for the repository '2325' was gathered on 2020/06/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
David Torres Sánchez            39          2343           1763           16.13
Romain MONTAGNÉ                194         12548           8800           83.86
torressa                         1             2              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Romain MONTAGNÉ            3992           31.8          1.0               11.77
torressa                    546        27300.0          1.1               13.74
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02325/joss.02325/10.21105.joss.02325.pdf)

**Comment by Kuifje02** [comment]
> @Kuifje02 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

jamiehadd
skadio
seba-1511
hanson
alex-konovalov
stsievert
gabrielspadon
drvinceknight

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer could you handle this submission? Alternatively @arfon, perhaps this could be a good first issue for @kakiac to handle (despite it being off topic perhaps)?

**Comment by arfon** [comment]
What do you think @kakiac?

**Comment by arfon** [comment]
This might also be a good fit for @bstabler?

**Comment by kyleniemeyer** [comment]
If @bstabler is already overloaded, then I could, but this does seem like a better fit for him.

**Comment by kyleniemeyer** [comment]
@whedon invite @bstabler as editor

**Comment by whedon** [comment]
@bstabler has been invited to edit this submission.

**Comment by kakiac** [comment]
A bit off topic, but would be happy to pick this up (and possibly ask for @bstabler 's help if stuck?) If that's ok with you, feel free to assign me as editor 😃

**Comment by arfon** [comment]
@whedon assign @kakiac as editor

**Comment by whedon** [comment]
OK, the editor is @kakiac

**Comment by arfon** [comment]
> A bit off topic, but would be happy to pick this up (and possibly ask for @bstabler 's help if stuck?) If that's ok with you, feel free to assign me as editor 😃

Thanks @kakiac!

**Comment by bstabler** [comment]
happy to review or help @kakiac review, thanks

**Comment by bstabler** [comment]
@whedon add me as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by bstabler** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @bstabler

**Comment by kakiac** [comment]
:wave: @jamiehadd, @skadio, @seba-1511, @hausen, @stsievert, @gabrielspadon, @drvinceknight would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by kakiac** [comment]
I have additionally emailed the reviewers above 😃

**Comment by skadio** [comment]
I would be join the review.

**Comment by arfon** [comment]
@kakiac @bstabler - just checking who is planning on editing this submission? I see @bstabler listed as the editor but @kakiac it looks like you're working on this one too?

**Comment by kakiac** [comment]
Yes, I think we agreed to collaborate, but whedon does not seem to like to have us both, so we have left @bstabler's username for now. Is there a way to add 2 editors?

**Comment by kakiac** [comment]
> I would be happy to join the review.

@skadio many thanks! I will add you as a reviewer now,

**Comment by kakiac** [comment]
whedon assign @skadio as reviewer

**Comment by arfon** [comment]
> Yes, I think we agreed to collaborate, but whedon does not seem to like to have us both, so we have left @bstabler's username for now. Is there a way to add 2 editors?

Got it, thanks. Unfortunately we don't support this.

**Comment by kakiac** [comment]
> > Yes, I think we agreed to collaborate, but whedon does not seem to like to have us both, so we have left @bstabler's username for now. Is there a way to add 2 editors?
> 
> Got it, thanks. Unfortunately we don't support this.

No problem!

**Comment by kakiac** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kakiac

**Comment by kakiac** [comment]
whedon assign @skadio as reviewer

**Comment by kakiac** [comment]
@whedon assign @skadio as reviewer

**Comment by whedon** [comment]
OK, @skadio is now a reviewer

**Comment by kakiac** [comment]
@whedon assign @bstabler as editor

**Comment by whedon** [comment]
OK, the editor is @bstabler

**Comment by bstabler** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2408.
