### ISSUE TITLE
[PRE REVIEW]: ‘Bioassays’; a new package in R for analyzing cellular assays

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2326]
**Submitting author:** @anwarbio (<a href="http://orcid.org/0000-0002-1693-1219">ANWAR PALAKKAN</a>)
**Repository:** <a href="https://github.com/anwarbio/bioassays" target ="_blank">https://github.com/anwarbio/bioassays</a>
**Version:** Version 0.1.0
**Editor:** @fboehm
**Reviewers:** @tomsing1
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @anwarbio. **Currently, there isn't an JOSS editor assigned** to your paper.

@anwarbio if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2326 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2326 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s10295-006-0086-3 is OK
- 10.1002/em.22014 is OK
- 10.1007/978-1-4939-2742-5_11 is OK
- 10.1016/j.bios.2015.05.018 is OK
- 10.1038/srep42383 is OK
- 10.1093/bioinformatics/btr664 is OK
- 10.1186/s12859-019-2891-5 is OK

MISSING DOIs

- None

INVALID DOIs

- NBK144065 is INVALID
```

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02326/joss.02326/10.21105.joss.02326.pdf)

**Comment by labarba** [comment]
👋  @anwarbio -- you've provided a link to a repository that contains _just the paper_. We expect a repository containing _the code_, with the paper contained within. Can you re-arrange things?

**Comment by anwarbio** [comment]
@labarba -- Sorry for the issue. I have now uploaded all the files on GitHub. 
Kind regards,
Anwar

**Comment by labarba** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (817.0 files/s, 41117.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               36            265            184            735
Rmd                              3            255            287            222
TeX                              1             16              0            104
Markdown                         3             36              0             60
-------------------------------------------------------------------------------
SUM:                            43            572            471           1121
-------------------------------------------------------------------------------


Statistical information for the repository '2326' was gathered on 2020/06/12.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by labarba** [comment]
The submission does not currently satisfy our Review Criteria, which require the use of an OSI-approved [Software License](https://joss.readthedocs.io/en/latest/review_criteria.html?highlight=license#software-license).

**Comment by anwarbio** [comment]
Hi, I have updated the software License as GPL 3.  Hope this will be fine.
Regards,
Anwar

**Comment by Kevin-Mattheus-Moerman** [comment]
@anwarbio I cannot see the license yet. I recommend that you add a plain LICENSE file to your main repository folder. This also means that GitHub "discovers" it so it renders a clear license badge e.g. as circled in blue below. 
![Screenshot from 2020-06-18 11-18-40](https://user-images.githubusercontent.com/8392709/85008994-a6620680-b155-11ea-9a04-72454ec98ada.png)
Furthermore I recommend referring to and linking to your LICENSE file in your README document.

**Comment by Kevin-Mattheus-Moerman** [comment]
@anwarbio this is not a requirement but I recommend that you change the title to: 
`Bioassays: a new package in R for analyzing cellular assays`
i.e. to remove the "special characters"  `'` and `;`. My comment is just to improve accuracy of potential citations to your work in the future.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon could this be a good first submission for @fboehm to handle? Alternatively perhaps @mikldk could consider this one?

**Comment by arfon** [comment]
@whedon invite @fboehm as editor

👍 @Kevin-Mattheus-Moerman - this looks like it could be a great first submission for @fboehm.

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by anwarbio** [comment]
Hi, 
I have made all the suggested edits. Details are given below.
1) LICENSE file is added to the repository folder.
2) LICENSE file is  linked to your README document
3) Changed the title as Bioassays: a new package in R for analyzing cellular assays

Regards,
Anwar

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by fboehm** [comment]
@whedon assign @tomsing1 as reviewer

**Comment by whedon** [comment]
OK, @tomsing1 is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2402.

**Comment by arfon** [comment]
:wave: @fboehm - just checking you're planning on finding a second reviewer for this submission?

**Comment by fboehm** [comment]
Yes, @arfon, thanks for checking in - I just now found a second reviewer. i'll add him.

**Comment by fboehm** [comment]
@whedon add @homoneclocom as reviewer

**Comment by whedon** [comment]
OK, @homoneclocom is now a reviewer

**Comment by fboehm** [comment]
I've emailed Ricardo - whose github user name is listed as @homoneclocom - to see if he is using a new github username. I'm unable to find @homoneclocom when I search github. We may need to update the reviewer database.

**Comment by arfon** [comment]
> @whedon add @homoneclocom as reviewer

@fboehm - I'm not sure if you know this already, but you'll need to manually add a checklist for the second reviewer in https://github.com/openjournals/joss-reviews/issues/2402 as Whedon doesn't know how to do this yet.

**Comment by fboehm** [comment]
@arfon - thanks for the reminder!
