### ISSUE TITLE
[PRE REVIEW]: Talisman: a JavaScript archive of fuzzy matching, information retrieval and record linkage building blocks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2327]
**Submitting author:** @Yomguithereal (<a href="http://orcid.org/0000-0003-4916-8472">Guillaume Plique</a>)
**Repository:** <a href="https://github.com/Yomguithereal/talisman" target ="_blank">https://github.com/Yomguithereal/talisman</a>
**Version:** 1.1.2
**Editor:** @kakiac
**Reviewers:** @Fil, @atanikan
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Yomguithereal. **Currently, there isn't an JOSS editor assigned** to your paper.

@Yomguithereal if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.67 s (339.8 files/s, 43960.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                     221           3019           4639          15686
JSON                             2              0              0           5415
TeX                              1             48              0            417
Markdown                         4             91              0            301
YAML                             1              0              0              8
-------------------------------------------------------------------------------
SUM:                           229           3158           4639          21827
-------------------------------------------------------------------------------


Statistical information for the repository '2327' was gathered on 2020/06/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Emily Marigold Klass             1             2              2            0.01
Mark Vasilkov                    1             5              5            0.02
Michael Henretty                 1            56             23            0.13
Paul Girard                      3             4              4            0.01
Yomguithereal                  408         42819          19509           99.81
cbbfcd                           1             2              1            0.00
jfseb                            1             3              2            0.01
tuzepoito                        1             6              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Emily Marigold Klass          1           50.0          3.7              100.00
Mark Vasilkov                 4           80.0         23.3                0.00
Michael Henretty             56          100.0         20.0               46.43
Yomguithereal             23280           54.4         43.2               19.81
cbbfcd                        2          100.0          4.2                0.00
jfseb                         1           33.3         39.0                0.00
tuzepoito                     6          100.0          0.1                0.00
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02327/joss.02327/10.21105.joss.02327.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MEDITEC.2016.7835390 is OK
- 10.1145/358027.358048 is OK
- 10.1109/SEQUEN.1997.666900 is OK
- 10.1145/1963405.1963487 is OK

MISSING DOIs

- https://doi.org/10.1007/3-540-45735-6_24 may be missing for title: String matching with metric trees using an approximate distance
- https://doi.org/10.1145/363958.363994 may be missing for title: A technique for computer detection and correction of spelling errors
- https://doi.org/10.2307/1932409 may be missing for title: Measures of the amount of ecologic association between species
- https://doi.org/10.1080/00182494.1976.10112645 may be missing for title: Surname spellings and computerized record linkage
- https://doi.org/10.1111/j.1469-8137.1912.tb05611.x may be missing for title: The distribution of the flora in the alpine zone. 1
- https://doi.org/10.1080/01621459.1989.10478785 may be missing for title: Advances in record-linkage methodology as applied to matching the 1985 census of Tampa, Florida
- https://doi.org/10.1002/sim.4780140510 may be missing for title: Probabilistic linkage of large public health data files
- https://doi.org/10.6028/nbs.sp.500-2 may be missing for title: Accessing individual records from personal data files using non-unique identifiers
- https://doi.org/10.1016/0022-2836(81)90087-5 may be missing for title: Identification of common molecular subsequences
- https://doi.org/10.2307/1532326 may be missing for title: FONEM: Un code de transcription phonétique pour la reconstitution automatique des familles saguenayennes
- https://doi.org/10.1109/itcc.2002.1000354 may be missing for title: Improving precision and recall for soundex retrieval
- https://doi.org/10.1145/2348828.2348830 may be missing for title: Hybrid matching algorithm for personal names
- https://doi.org/10.1002/(sici)1097-4571(199301)44:1<1::aid-asi1>3.0.co;2-1 may be missing for title: Stemming of French words based on grammatical categories
- https://doi.org/10.1002/(sici)1097-4571(1999)50:10<944::aid-asi9>3.0.co;2-q may be missing for title: A stemming procedure and stopword list for general French corpora
- https://doi.org/10.1108/eb026966 may be missing for title: A stemming algorithm for Latin text databases
- https://doi.org/10.1145/101306.101310 may be missing for title: Another stemmer
- https://doi.org/10.1162/coli.2006.32.4.485 may be missing for title: Unsupervised multilingual sentence boundary detection

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@Yomguithereal we are currently trying to find an editor to handle this submission. In the meantime please check our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and amend your paper where needed. In particular you should cite "A list of key references, including to other software addressing related needs". 
With sentences in your paper like this:
`Thus, even if Talisman obviously provides state-of-the-art functions that are still being used in an industrial context, it also aims at being a safe harbor for less known or clunkier techniques, for historical and archival purposes.`
You have the opportunity to cite these works/methods you are referring to. Please also briefly discuss other existing software projects addressing similar functionality. 
After adding citations please do check that you've added DOI's where possible. 
You can call `@whedon generate pdf` and `@whedon check references` here yourself too.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mjsottile @VivianePons @jedbrown @gkthiruvathukal could one of you handle this submission? Thanks

**Comment by arfon** [comment]
@kakiac might also be a good fit as an editor here.

**Comment by kakiac** [comment]
Happy to be assigned as the editor!

**Comment by kakiac** [comment]
@whedon assign @kakiac as editor

**Comment by whedon** [comment]
OK, the editor is @kakiac

**Comment by kakiac** [comment]
> 
> 
> @Yomguithereal we are currently trying to find an editor to handle this submission. In the meantime please check our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and amend your paper where needed. In particular you should cite "A list of key references, including to other software addressing related needs".
> With sentences in your paper like this:
> `Thus, even if Talisman obviously provides state-of-the-art functions that are still being used in an industrial context, it also aims at being a safe harbor for less known or clunkier techniques, for historical and archival purposes.`
> You have the opportunity to cite these works/methods you are referring to. Please also briefly discuss other existing software projects addressing similar functionality.
> After adding citations please do check that you've added DOI's where possible.
> You can call `@whedon generate pdf` and `@whedon check references` here yourself too.

👋 @Yomguithereal thanks for your submission to JOSS. 

I am in the process of assigning reviewers to this submission, but if you have any suggestions for reviewers please let me know.

In the meantime, can you please address @Kevin-Mattheus-Moerman 's comment above and update your submission?

Many thanks!

**Comment by kakiac** [comment]
:wave: @richardlitt, @fil & @abuccts, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by Fil** [comment]
Yes (next week)

**Comment by kakiac** [comment]
Thanks @fil!

@whedon assign @fil as reviewer

@whedon generate pdf

**Comment by kakiac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02327/joss.02327/10.21105.joss.02327.pdf)

**Comment by kakiac** [comment]
@whedon assign @Fil as reviewer

**Comment by whedon** [comment]
OK, @Fil is now a reviewer

**Comment by Yomguithereal** [comment]
> @Yomguithereal we are currently trying to find an editor to handle this submission. In the meantime please check our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and amend your paper where needed. In particular you should cite "A list of key references, including to other software addressing related needs".
> With sentences in your paper like this:
> `Thus, even if Talisman obviously provides state-of-the-art functions that are still being used in an industrial context, it also aims at being a safe harbor for less known or clunkier techniques, for historical and archival purposes.`
> You have the opportunity to cite these works/methods you are referring to. Please also briefly discuss other existing software projects addressing similar functionality.
> After adding citations please do check that you've added DOI's where possible.
> You can call `@whedon generate pdf` and `@whedon check references` here yourself too.

Hello everyone, sorry for the delay.

I have an extensive bibliography [here](https://github.com/Yomguithereal/talisman/blob/master/paper/paper.bib) but I did not find how to automatically generate it under the `References` section of the abstract. Should I only pick a limited amount?

Also, regarding links to similar software endeavors can I just edit my repo and then ping you when this is done?

Finally, regarding DOIs I tried as much as possible to get them but I am afraid that most of my references don't have one. Or maybe there is a way to find DOI easily (most of my bibtex comes straight from google scholar & zbib).

Have a good day and thanks for agreeing to review the library.

**Comment by arfon** [comment]
> I have an extensive bibliography here but I did not find how to automatically generate it under the References section of the abstract. Should I only pick a limited amount?

@Yomguithereal - You need to cite them directly please for them to be rendered into the document (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)).

**Comment by danielskatz** [comment]
And just to add, JOSS does not publish papers that are surveys, so the bibliography (and ideally the .bib file due to a limitation in our tooling) should only contain items that are referenced in the paper.

**Comment by Yomguithereal** [comment]
All the references existing in the .bib files are papers describing methods actually implemented by the library. So do you agree I should list every reference in the abstract under `References` then? If so I will probably create a script to do so if such script does not already exist.

**Comment by danielskatz** [comment]
In my opinion, if you describe the method in the paper, it would be reasonable to cite a reference for that method.  The best thing to do is to look at your paper, and decide where you need to place citations to references, then to include those references in the .bib file.  Pandoc as called by whedon will then build the reference list in the pdf.

**Comment by Yomguithereal** [comment]
The paper does not describe a specific method but rather explains the scope and stake of the library as an aggregation of implementations of various fuzzy matching etc. methods. The lib implements a large amount of different methods/functions etc. which are nearly exhaustively referenced by papers, collected in the current bibliography. So I guess I am misunderstanding the framing the paper should have. For instance, if we take the example of scikit-learn, do you expect to have few references linking towards machine learning as a field or rather the exhaustive list of papers that have been used to implement their large collection of algorithms?

**Comment by danielskatz** [comment]
I think my answer is yes.  An academic paper on scikit-learn might go into a lot of detail about all the methods, with citations to references for each method, but this is probably not appropriate for a JOSS paper.

See https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain for guidance on what a JOSS paper should contain.

**Comment by Fil** [comment]
I'm ready to start reviewing *talisman* but I can't find the usual checklist? has the review process changed in some mysterious way since I last did [a review](https://github.com/openjournals/joss-reviews/issues/1628)? What should I do?

**Comment by danielskatz** [comment]
This is still the pre-review issue, where reviewers are being sought.  Once the editor, @kakiac, has a second reviewer, he will start the review.

**Comment by kakiac** [comment]
Thanks all, I have additionally just emailed @kinow @atanikan and @b-freitas. I will be in touch once I hear from one of them, but hopefully they should be in touch soon.

**Comment by kakiac** [comment]
@whedon add @atanikan as reviewer

**Comment by whedon** [comment]
OK, @atanikan is now a reviewer

**Comment by kakiac** [comment]
Hello everyone, many thanks to the reviewers for volunteering, I will now move this to the REVIEW stage, so you should be receiving an update with the new issue and the reviewer checklists.

**Comment by kakiac** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2405.
