### ISSUE TITLE
[REVIEW]: CollatriX: A GUI to collate MorphoMetriX outputs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2328]
**Submitting author:** @cbirdferrer (<a href="http://orcid.org/0000-0001-7763-7761">Clara Bird</a>)
**Repository:** <a href="https://github.com/cbirdferrer/collatrix" target ="_blank">https://github.com/cbirdferrer/collatrix</a>
**Version:** v1.0.5
**Editor:** @KristinaRiemer
**Reviewer:** @evaristor, @katmratliff
**Archive:** <a href="https://doi.org/10.5281/zenodo.3937611" target="_blank">10.5281/zenodo.3937611</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b8a3517580cb619a25a2932b08006639/status.svg)](https://joss.theoj.org/papers/b8a3517580cb619a25a2932b08006639)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b8a3517580cb619a25a2932b08006639"><img src="https://joss.theoj.org/papers/b8a3517580cb619a25a2932b08006639/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b8a3517580cb619a25a2932b08006639/status.svg)](https://joss.theoj.org/papers/b8a3517580cb619a25a2932b08006639)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cbirdferrer/collatrix" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@evaristor & @katmratliff, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @KristinaRiemer know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cbirdferrer/collatrix">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cbirdferrer) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cbirdferrer/collatrix">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cbirdferrer) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @evaristor, @katmratliff it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01825 is OK
- 10.1002/ecs2.1468 is OK
- 10.3389/fmars.2017.00366 is OK
- 10.3354/meps12522 is OK
- 10.1111/mms.12527 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02328/joss.02328/10.21105.joss.02328.pdf)

**Comment by KristinaRiemer** [comment]
@arfon is whedon supposed to auto-assign both reviewers as assignees to the Review issue? It looks like it missed @katmratliff here.

**Comment by arfon** [comment]
@KristinaRiemer - Whedon can only do this once the reviewer has accepted the invite (which it looks like they now have). Whedon then updates assignments nightly so by tomorrow the assignments should look correct.

**Comment by evaristor** [comment]
This software will be very useful to the users of MorphoMetriX since it automates the collation of the MorphoMetriX outputs with the aid of a friendly GUI. I suggest the authors make the following **Minor Revisions** before acceptance.

### From the checklist

**[Automated tests](https://github.com/cbirdferrer/collatrix/issues/2):** There are no automated tests. I suggest using [pytest-qt](https://pytest-qt.readthedocs.io) (or [Qt Test](https://doc.qt.io/qt-5/qttest-index.html)) in conjunction with GitHub Actions or Travis. You can find more information here:

- [PyQt: GUI Testing](https://wiki.python.org/moin/PyQt/GUI_Testing)
- [Test PyQt GUIs with QTest and unittest](http://johnnado.com/pyqt-qtest-example/)

**[Community guidelines](https://github.com/cbirdferrer/collatrix/issues/3):** Please add a section in the README with guidelines for third parties wishing to 1) contribute to the software, 2) report issues or problems with the software, and 3) seek support.

### Additional suggestions

**[Help messages](https://github.com/cbirdferrer/collatrix/issues/4):** The messages in the dialog boxes (titles and names of fields) are too brief. On the other hand, the description in the README (and even the comments in the code) are satisfactorily detailed. I suggest adding text boxes to the GUI with more detailed information.

**[Commented-out code](https://github.com/cbirdferrer/collatrix/issues/5):** Please remove the commented-out code. Lines [2](https://github.com/cbirdferrer/collatrix/blob/master/setup.py#L2) and [19](https://github.com/cbirdferrer/collatrix/blob/master/setup.py#L19) of `setup.py` and lines [6](https://github.com/cbirdferrer/collatrix/blob/master/meta.yaml#L6), [12](https://github.com/cbirdferrer/collatrix/blob/master/meta.yaml#L12), [16](https://github.com/cbirdferrer/collatrix/blob/master/meta.yaml#L16), and [17](https://github.com/cbirdferrer/collatrix/blob/master/meta.yaml#L17) of `meta.yaml` are commented out. You can find more information about why that is considered a bad idea here:

- [Please, don’t commit commented-out code](https://kentcdodds.com/blog/please-dont-commit-commented-out-code)
- [Don’t share commented-out code](https://www.nayuki.io/page/dont-share-commented-out-code)

**[Build](https://github.com/cbirdferrer/collatrix/issues/6):** Please show how to build the package. You could add a shell script, a Makefile, or a GitHub Actions (or Travis) configuration file that includes the command used to build the conda package.

**[Output](https://github.com/cbirdferrer/collatrix/issues/7):** The header in column 1 of the output CSV file is blank. Please add a header to the first column of the output to ensure that it is a valid CSV file.

I added these suggestions as issues on the CollatriX repo.

**Comment by KristinaRiemer** [comment]
Hi @katmratliff, have you had a chance to look at this submission yet?

**Comment by katmratliff** [comment]
Hi @KristinaRiemer I am planning to complete my review this week.

**Comment by KristinaRiemer** [comment]
Great, thanks so much @katmratliff!

**Comment by katmratliff** [comment]
Hi @KristinaRiemer, I have completed my review and have submitted the following suggestions via issues in the repository:
- https://github.com/cbirdferrer/collatrix/issues/8
- https://github.com/cbirdferrer/collatrix/issues/9
- https://github.com/cbirdferrer/collatrix/issues/10
- https://github.com/cbirdferrer/collatrix/issues/11

Under the **Documentation** checklist, I have currently left **Functionality documentation** unchecked because additional information is needed in the input dialog boxes (or a link to the documentation). I have also left **Automated tests** unchecked because there is currently no documentation on how to run the tests manually.

**Comment by evaristor** [comment]
@KristinaRiemer: I recommend accepting this paper in its current form

**Comment by KristinaRiemer** [comment]
@evaristor thank you for confirming your acceptance! @katmratliff if you are also satisfied with this at this point, could you please confirm that?

**Comment by katmratliff** [comment]
@KristinaRiemer yes I recommend accepting as well

**Comment by KristinaRiemer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02328/joss.02328/10.21105.joss.02328.pdf)

**Comment by KristinaRiemer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01825 is OK
- 10.1002/ecs2.1468 is OK
- 10.3389/fmars.2017.00366 is OK
- 10.3354/meps12522 is OK
- 10.1111/mms.12527 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by KristinaRiemer** [comment]
Thank you for your reviews @evaristor and @katmratliff! 

@cbirdferrer, I'm just going through the article proof linked above for correct DOIs, typos, etc., which you should do also to make sure it looks good to you. 

I only found a couple minors things that you can fix when you get a chance: 

- Dawson (2017) reference is missing some authors
- There is inconsistency between whether or not a comma follows "i.e."; I've been taught that it should always be "i.e.,"?

**Comment by cbirdferrer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02328/joss.02328/10.21105.joss.02328.pdf)

**Comment by cbirdferrer** [comment]
Thanks @KristinaRiemer! Fixed both!

**Comment by cbirdferrer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02328/joss.02328/10.21105.joss.02328.pdf)

**Comment by cbirdferrer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01825 is OK
- 10.1002/ecs2.1468 is OK
- 10.3389/fmars.2017.00366 is OK
- 10.3354/meps12522 is OK
- 10.1111/mms.12527 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by KristinaRiemer** [comment]
That looks great @cbirdferrer! 

The next steps are to: 1) [create a tagged release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release) on GitHub and 2) archive the code (on Zenodo, figshare, institutional repository, etc.) to generate a DOI. If you can post a link to the DOI here when you're done please.

**Comment by cbirdferrer** [comment]
@KristinaRiemer here's the link to the DOI 
https://zenodo.org/record/3937611#.XwdcpZNKhTY  
DOI: 10.5281/zenodo.3937611

**Comment by KristinaRiemer** [comment]
@whedon set v1.0.5 as version

**Comment by whedon** [comment]
OK. v1.0.5 is the version.

**Comment by KristinaRiemer** [comment]
@whedon set 10.5281/zenodo.3937611 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3937611" target="_blank">10.5281/zenodo.3937611</a> is the archive.

**Comment by KristinaRiemer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01825 is OK
- 10.1002/ecs2.1468 is OK
- 10.3389/fmars.2017.00366 is OK
- 10.3354/meps12522 is OK
- 10.1111/mms.12527 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1555

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1555, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
All looks good here, thanks!

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1281312708999237633) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1556
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02328](https://doi.org/10.21105/joss.02328)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congratulations @cbirdferrer on your article's publication in JOSS!

Many thanks to @evaristor and @katmratliff for reviewing this, and  @KristinaRiemer for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02328/status.svg)](https://doi.org/10.21105/joss.02328)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02328">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02328/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02328/status.svg
   :target: https://doi.org/10.21105/joss.02328
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02328/status.svg)](https://doi.org/10.21105/joss.02328)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
