### ISSUE TITLE
[PRE REVIEW]: stella: Convolutional Neural Networks for Flare Identification in TESS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2332]
**Submitting author:** @afeinstein20 (<a href="http://orcid.org/0000-0002-9464-8101">Adina Feinstein</a>)
**Repository:** <a href="https://github.com/afeinstein20/stella" target ="_blank">https://github.com/afeinstein20/stella</a>
**Version:** v0.0.5
**Editor:** @arfon
**Reviewers:** @pearsonkyle, @RuthAngus
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @afeinstein20. **Currently, there isn't an JOSS editor assigned** to your paper.

@afeinstein20 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.29 s (143.7 files/s, 19835.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          13            509            870           1255
SVG                              1              0              0            520
HTML                             7             67              2            516
Jupyter Notebook                 3              0           1202            122
JavaScript                       2             22             14            121
Markdown                         3             35              0            100
TeX                              1              4              0             75
YAML                             2              7              0             45
Bourne Shell                     2              6              9             36
reStructuredText                 4             27             38             27
make                             1              4              6             13
CSS                              2              0              5              2
-------------------------------------------------------------------------------
SUM:                            41            681           2146           2832
-------------------------------------------------------------------------------


Statistical information for the repository '2332' was gathered on 2020/06/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adina Feinstein                235         10552           7761          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adina Feinstein            2791           26.4          4.1               10.07
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1089/ast.2006.0128 is OK
- 10.3847/0004-637X/830/2/77 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02332/joss.02332/10.21105.joss.02332.pdf)

**Comment by afeinstein20** [comment]
The proof looks good!

**Comment by arfon** [comment]
:wave: @afeinstein20. Does this JOSS submission accompany a paper in a AAS journal?

**Comment by afeinstein20** [comment]
Hi @arfon it does! We just received the referee report for that paper.

**Comment by arfon** [comment]
> Hi @arfon it does! We just received the referee report for that paper.

Great! Thanks for letting me know. We'll try and move this quickly along so we can get these published at a similar time.

@afeinstein20 - could you suggest a few names who might be able to give this submission a good review?

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
/ cc @crawfordsm for visibility

**Comment by arfon** [comment]
:wave: @RuthAngus - would you be willing to review this submission for JOSS?

**Comment by arfon** [comment]
:wave: @warrickball - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by warrickball** [comment]
Hi @arfon, I'm afraid I won't be able to review this submission. Sorry!

**Comment by afeinstein20** [comment]
Hi @arfon Monica Bobra may also be a good potential reviewer

**Comment by arfon** [comment]
> Hi @arfon, I'm afraid I won't be able to review this submission. Sorry!

Got it. Thanks for letting me know @warrickball.

**Comment by afeinstein20** [comment]
Hi @arfon  some good reviewers would be Kyle Pearson, Hugh Osborn, Krisztián Vida, or Jason Dittman

**Comment by arfon** [comment]
:wave: @pearsonkyle @hposborn @vidakris - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by pearsonkyle** [comment]
I'm happy to review it.

**Comment by arfon** [comment]
Great, thanks @pearsonkyle! I'll add you to the review here but the actual review process won't start for real until there's a second reviewer (which hopefully won't be too long).

**Comment by arfon** [comment]
@whedon add @pearsonkyle as reviewer

**Comment by whedon** [comment]
OK, @pearsonkyle is now a reviewer

**Comment by RuthAngus** [comment]
@arfon I'm happy to review this too!

**Comment by arfon** [comment]
@whedon add @RuthAngus as reviewer

**Comment by whedon** [comment]
OK, @RuthAngus is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2347.

**Comment by arfon** [comment]
@pearsonkyle, @RuthAngus - thanks so much for agree to review this submission. See you over in #2347 where the actual review will take place.
