### ISSUE TITLE
[PRE REVIEW]: rsudp: A Python package for real-time seismic monitoring with Raspberry Shake instruments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2333]
**Submitting author:** @iannesbitt (<a href="http://orcid.org/0000-0001-5828-6070">Ian Nesbitt</a>)
**Repository:** <a href="https://github.com/raspishake/rsudp" target ="_blank">https://github.com/raspishake/rsudp</a>
**Version:** v1.0.1
**Editor:** @jedbrown
**Reviewers:** @eileenrmartin
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @iannesbitt. **Currently, there isn't an JOSS editor assigned** to your paper.

@iannesbitt if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1785/0220180251 is OK
- 10.1785/0220190211 is OK
- 10.3389/feart.2020.00009 is OK
- 10.3389/feart.2020.00073 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1785/gssrl.81.3.530 is OK
- 10.4401/ag-4838 is OK
- 10.1088/1749-4699/8/1/014003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02333/joss.02333/10.21105.joss.02333.pdf)

**Comment by labarba** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.54 s (228.4 files/s, 75609.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            34           4044             34           9347
JavaScript                      11           2201           2239           8337
SVG                              3              2              2           4513
Python                          25            936           1802           2771
reStructuredText                31            762            696            995
CSS                              4            165             34            645
Bourne Shell                     4             51             41            438
DOS Batch                        5             66              0            258
Markdown                         3             24              0            145
TeX                              1              7              0            111
YAML                             1              0              0             28
make                             1              5              6             12
-------------------------------------------------------------------------------
SUM:                           123           8263           4854          27600
-------------------------------------------------------------------------------


Statistical information for the repository '2333' was gathered on 2020/06/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ian Nesbitt                    279          9465           7007           44.43
Justin Long                      4           319             19            0.91
Richard Boaz                     1           188              0            0.51
iannesbitt                     160         17698           2366           54.12
ivor                             1             7              7            0.04

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ian Nesbitt               17966          189.8          2.9               14.91
Justin Long                 294           92.2          1.3                9.86
ivor                         26          371.4          0.5                0.00
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@kbarnhart @leouieda @jedbrown could one of you handle this submission? Thanks

**Comment by kbarnhart** [comment]
@Kevin-Mattheus-Moerman I can't take on another paper right now. If no one can take this on between now the end of next week. I should be able to take on another one or two papers then.

**Comment by Kevin-Mattheus-Moerman** [comment]
Okay thanks @kbarnhart. It may come to that actually but that is fine. Thanks again.

**Comment by Kevin-Mattheus-Moerman** [comment]
@kbarnhart would you be okay with me assigning this paper to you now, but that it is okay that you pick this up once you have time e.g. in 1-2 weeks? It is acceptable that we are slower handling things given our "reduced service mode", so we can wait until you are ready.

**Comment by jedbrown** [comment]
I could take this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by arfon** [comment]
:wave: @jedbrown - just checking in on this paper to see how you're getting on identifying reviewers?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02333/joss.02333/10.21105.joss.02333.pdf)

**Comment by arfon** [comment]
@jedbrown ☝️ looks like https://github.com/openjournals/whedon-api/pull/108 works nicely.

**Comment by jedbrown** [comment]
Sorry about the slow start here. I found a great reviewer and a likely second and will start the review.

**Comment by jedbrown** [comment]
@whedon add @eileenrmartin as reviewer

**Comment by whedon** [comment]
OK, @eileenrmartin is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2565.
