### ISSUE TITLE
[PRE REVIEW]: HPX - The C++ Standard Library for Parallelism and Concurrency

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2335]
**Submitting author:** @diehlpk (<a href="http://orcid.org/0000-0003-3922-8419">Patrick Diehl</a>)
**Repository:** <a href="https://github.com/STEllAR-GROUP/hpx" target ="_blank">https://github.com/STEllAR-GROUP/hpx</a>
**Version:** 1.4.1
**Editor:** @danielskatz
**Reviewers:** @bhatele, @davidbeckingsale
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @diehlpk. **Currently, there isn't an JOSS editor assigned** to your paper.

@diehlpk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2335 with the following error: 

 Can't find any papers to compile :-(

**Comment by diehlpk** [comment]
@whedon generate pdf from branch hpx/joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch hpx/joss. Reticulating splines etc...
```

**Comment by diehlpk** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2335 with the following error: 

 error: pathspec 'joss' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by diehlpk** [comment]
We have the paper in the following branch https://github.com/STEllAR-GROUP/hpx/tree/JOSS, since we want to keep the paper aligned with the latest stable release.

**Comment by diehlpk** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02335/joss.02335/10.21105.joss.02335.pdf)

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @diehlpk - do you have suggestions for potential reviewers? If so, please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by diehlpk** [comment]
@danielskatz People working on AMT as well: crtrott and ibaned (Kokkos), stwhite91 and bhatele (Charm++)

**Comment by diehlpk** [comment]
@hkaiser @parsa @sithhell @zkhatami88 @khuck @biddisco @stevenrbrandt Can you help to identify potential reviewers? Please add them to my previous comment.

**Comment by danielskatz** [comment]
To the people mentioned in the previous comment - please do not tag potential reviewers, just provide their github usernames or some other contact info

**Comment by danielskatz** [comment]
👋 @crtrott and @ibaned - would one of you be willing to review this submission?

**Comment by danielskatz** [comment]
👋 @stwhite91 and @bhatele  - would one of you be willing to review this submission?

**Comment by diehlpk** [comment]
> To the people mentioned in the previous comment - please do not tag potential reviewers, just provide their github usernames or some other contact info

These are my co-authors and I asked them for help to suggest reviewers.

**Comment by danielskatz** [comment]
Yes. I was saying this to them, not to you

**Comment by bhatele** [comment]
@danielskatz I'd be happy to review this submission.

**Comment by danielskatz** [comment]
Thanks @bhatele - I'll add you to the system now, but we won't start the review until there's at least one more reviewer as well.

**Comment by danielskatz** [comment]
@whedon assign @bhatele as reviewer

**Comment by whedon** [comment]
OK, @bhatele is now a reviewer

**Comment by danielskatz** [comment]
👋 @G-071, @davidbeckingsale - Would one of of you be willing to review this submission for JOSS?  We openly review both the short paper and the software in a GitHub issue, based on a [checklist](https://joss.readthedocs.io/en/latest/review_criteria.html#review-items)

**Comment by davidbeckingsale** [comment]
@danielskatz - yes, I would be happy to review this.

**Comment by danielskatz** [comment]
Thanks - I'll add you and we can start the review

**Comment by danielskatz** [comment]
@whedon add @davidbeckingsale as reviewer

**Comment by whedon** [comment]
OK, @davidbeckingsale is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2352.

**Comment by crtrott** [comment]
I have a conflict of interest with the HPX folks is my guess.

**Comment by danielskatz** [comment]
Thanks for letting us know, though we've now found sufficient reviewers and started the review.
