### ISSUE TITLE
[PRE REVIEW]: CRED-nf online checklist: An R Shiny tool to facilitate completion of the Consensus on the reporting and experimental design of clinical and cognitive-behavioural neurofeedback studies (CRED-nf) checklist

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2337]
**Submitting author:** @hugaped (<a href="http://orcid.org/0000-0002-7813-3749">Hugo Pedder</a>)
**Repository:** <a href="https://github.com/hugaped/CRED-nf" target ="_blank">https://github.com/hugaped/CRED-nf</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @hugaped. **Currently, there isn't an JOSS editor assigned** to your paper.

@hugaped if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (417.0 files/s, 35564.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                5             65             19            489
JSON                             5             10              0            311
Rmd                              1             32             50            103
Markdown                         2             30              0             63
TeX                              1              1              0             21
-------------------------------------------------------------------------------
SUM:                            14            138             69            987
-------------------------------------------------------------------------------


Statistical information for the repository '2337' was gathered on 2020/06/14.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/brain/awaa009 is OK
- 10.1159/000371714 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02337/joss.02337/10.21105.joss.02337.pdf)

**Comment by hugaped** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02337/joss.02337/10.21105.joss.02337.pdf)

**Comment by arfon** [comment]
@hugaped - many thanks for your submission to JOSS. After consulting with the JOSS editorial team, we have deemed that this submission is out of scope and does not meet our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). Specifically, while this package looks useful, it fails into out 'minor utility' category.

Thanks again for your interest in JOSS.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
