### ISSUE TITLE
[REVIEW]: MorphoPy: A python package for feature extraction of neural morphologies.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2339]
**Submitting author:** @visdoom (<a href="http://orcid.org/0000-0001-9532-788X">Sophie Laturnus</a>)
**Repository:** <a href="https://github.com/berenslab/MorphoPy" target ="_blank">https://github.com/berenslab/MorphoPy</a>
**Version:** v0.71
**Editor:** @oliviaguest
**Reviewer:** @Emptymalei, @mstimberg
**Archive:** <a href="https://doi.org/10.5281/zenodo.3956644" target="_blank">10.5281/zenodo.3956644</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c2c0b27b7eb01516d3808e8dd309543f/status.svg)](https://joss.theoj.org/papers/c2c0b27b7eb01516d3808e8dd309543f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c2c0b27b7eb01516d3808e8dd309543f"><img src="https://joss.theoj.org/papers/c2c0b27b7eb01516d3808e8dd309543f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c2c0b27b7eb01516d3808e8dd309543f/status.svg)](https://joss.theoj.org/papers/c2c0b27b7eb01516d3808e8dd309543f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/berenslab/MorphoPy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Emptymalei & @mstimberg, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @oliviaguest know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/berenslab/MorphoPy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@visdoom) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/berenslab/MorphoPy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@visdoom) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Emptymalei, @mstimberg it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s12021-010-9093-7 is OK
- 10.1371/journal.pone.0182184 is OK
- 10.1007/s12021-017-9341-1 is OK
- 10.1038/s41467-019-12058-z is OK
- 10.1101/2020.02.03.929158 is OK
- 10.1038/nprot.2008.51 is OK
- 10.1016/j.cell.2007.01.040 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02339/joss.02339/10.21105.joss.02339.pdf)

**Comment by oliviaguest** [comment]
👋 👋 👋

Hi everybody!

@Visdoom, @emptymalei, @mstimberg — welcome to where the review itself is going to be.

Any questions please ask me. Any *very* code-related issues use the repo of the code and open an issue and link to it from here. All other issues, feedback, questions for me or the author, please use this issue. Anything you need, check above first as there is a lot of into up there, but also please feel free to ask me. 😸 

Thank you all again and I hope this is a nice experience for us all! 🌼 🌸 🌷

**Comment by oliviaguest** [comment]
Can @emptymalei and @mstimberg give me a rough ETA on their reviews please? ☺️

**Comment by oliviaguest** [comment]
Oh, @emptymalei can you link to issues you open in the code repo here, please? Thank you! 😊 

So far we have:

* https://github.com/berenslab/MorphoPy/issues/105
* https://github.com/berenslab/MorphoPy/issues/104

👍

**Comment by mstimberg** [comment]
@oliviaguest I hope to do it before the end of the week :alarm_clock:

**Comment by emptymalei** [comment]
@oliviaguest 
I have tested most of the functions. Will finish this by the end of the week, too.

**Comment by emptymalei** [comment]
It's done on my side. 😸

**Comment by oliviaguest** [comment]
@emptymalei thank you! Have you opened an issue in the code repo for this? 

>  Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

**Comment by emptymalei** [comment]
@oliviaguest 

I have a question here. 
In fact, the code repo has a nicely illustrated tutorial jupyter notebook. It is neither unit test nor automated but it can serve as a very good manual test notebook.
I didn't check the box only because this is not automated. But based on this following section of the guidelines

> OK: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)

It is not bad. 

In this case, shall I create an issue or only provide this as an feedback here?

**Comment by oliviaguest** [comment]
If you have a very specific code-related suggestion, then yes, otherwise just here is fine, @emptymalei. 😊

**Comment by mstimberg** [comment]
Ok, here's my review, adding to @emptymalei's remarks

I opened a few specific issues in the MorphoPy repository (berenslab/MorphoPy#106, berenslab/MorphoPy#107, berenslab/MorphoPy#108, berenslab/MorphoPy#109)

I agree with @emptymalei that the package structure is surprising and support changing it to a more standard organization.

I also wonder whether the API documentation could be made more accessible somehow? One option would be sphinx+readthedocs, but I see that the authors already have generated HTML documentation in `html_docs`. Maybe this could be put online in some way (Github pages, for example)?

 Regarding the test discussion:
 * Given that this tool computes statistics and can be used to gather these statistics automatically for large amounts of data, I think some kind of automated test suite would be really important. I'm sure that the authors checked the correctness of the statistical measurements extensively, but codifying this into some test would increase trust of potentially users. This would not have to be very complicated, I could imagine having an artificially created SWC file where the correct answers to all measurements are known and can therefore be directly compared to the results from the tool. Orthogonal to that would be some kind of regression test (to make sure that future changes to the software do not change the results). One possible "brute-force" solution would be to run the tool on all the files in the `data` directory and store the CSV result files in the repository as well; one could then easily run a script to check whether the results are still the same.
 * Testing that the plots are correct and do not change with changes in the software would of course be more complicated, and I do not think automatizing this in some way would be worth the effort. Having a tutorial notebook is a great solution for this part and also acts as useful documentation.
 * The same goes for the comparison to the TMD tool – I'm happy with a manual comparison in a notebook (but see berenslab/MorphoPy#109).

The software paper itself looks very good to me (apart from the Umlaut issue in the author affiliations, but that seems already having been corrected) – I wonder whether the code examples are a bit too technical, though? Maybe move them to the documentation (if they are not already mentioned there)?

All in all, great work, I think I'm going to use MorphoPy in the future myself!

**Comment by Visdoom** [comment]
Hi @oliviaguest , @emptymalei  and @mstimberg , 

thank you for your reviewing efforts so far. Your feedback has been very helpful and your intend on future use @mstimberg is a great encouragement, thanks!
The remaining issues you have created via github will be addressed in the coming week. The biggest "issue" is to update the PyPi installation to the new folder structure but we are on it.

Regarding the automated test, we hope to provide both, the artificial test_swc morphometrics as well as the "brute-force" solution for checking the validity of future versions. 
How is this handled though? Will I just let you know here when we have implemented that?

Best wishes, Sophie

**Comment by oliviaguest** [comment]
@Visdoom Hey Sophie, yes, you got off make any and all changes you fancy and report back here. Ideally if you can link from here or however you want highlight the changes you make, so the reviewers can easily spot them. Does that make sense? ☺️

**Comment by Visdoom** [comment]
@oliviaguest yes, that makes sense. Thank you.

**Comment by oliviaguest** [comment]
Oh, and if you need advice from the reviewers, @Visdoom, of course also ask them here! 🌷

**Comment by emptymalei** [comment]
> I think I'm going to use MorphoPy in the future myself!

Also talked to my friend who's been doing such statistics by hand. She said this covers most of the statistics she's been looking at and will try out on the next project.

**Comment by philippberens** [comment]
Let us know if there is anything to add!

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02339/joss.02339/10.21105.joss.02339.pdf)

**Comment by oliviaguest** [comment]
Hey @Visdoom just a quick check in, what are you currently planning on working on for this? 😊

**Comment by Visdoom** [comment]
Hey @oliviaguest, 
thanks for checking in. We have created some tests but the automated integration into gitHub has a hick-up that I need to fix. I meant to do it yesterday and then ran out of time. So we are almost there. I will give you a wrap up here once everything has been addressed.

**Comment by Visdoom** [comment]
Dear @oliviaguest, @emptymalei and @mstimberg, 	
again, thank you for taking the time to review the code and the paper to our package MorphoPy. Your input has been valuable and we believe, that the package has improved majorly. The most prominent change has been the updated folder structure where now `morphopy` is the parent folder to all functional subfolders.
 |-- morphopy
    |-- computations
    |-- neurontree
    |-- about
….
The new importing structure that this implies has been updated for all notebooks and code-snippets within the paper. 
Furthermore, the full documentation of the package is now available under  https://morphopy.readthedocs.io/en/latest/. 
Additionally, we have added a testing suite in the the folder `tests`, which is run every time a push or a pull request is performed for the master branch on gitHub. 
Within these tests we mainly check if the current implementation of feature representations is consistent with an older precomputed version that is stored in cvs-files in `tests/test_data/` for four realistic neuron files. 
If you as reviewers want to run the tests separately you can do that by cloning the repository and running `pytest ./tests/` from the main folder - note, that `pytest` has to be installed for that.
Lastly, all the gitHub issues raised by the reviewers have been fixed.
Please be aware, that the updated package version is not available on PyPi yet. We will be releasing it soon as version 0.7.1 in case you want to recheck via the pip installation. 

Thank you very much and we hope we have addressed all your concerns, 
Team Berenslab

**Comment by mstimberg** [comment]
You put some serious work into these improvements, that's great to see. I am very happy with the state of the package now, and I can confirm that the test suite runs fine on my machine. A few minor issues:
* The JOSS manuscript still describes the outdated `-f`/`-d` syntax for the command line tool
*  The documentation on readthedocs should probably make it a bit clearer that it is only the API documentation and that the more high-level general introduction is in the README on github (or include this documentation directly), also not sure whether you link to readthedocs anywhere?
* In the readthedocs documentation, [Command Line Script](https://morphopy.readthedocs.io/en/latest/command.html) links to an empty page.

From my side, I'll be happy to see this published as it is (pending the minor changes suggested above, in particular the first point). @oliviaguest: I will be out of office for the three coming weeks, but consider this my formal publication endorsement, no need to block the publication until you hear back from me.

Thanks and bye everyone :wave:

PS: A mere suggestion because I saw that some tests were quite redundant (testing the same thing for several files, etc.). You might want to have a look at pytest's [parametrize](https://docs.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions) decorator that makes it possible to express such tests more concisely.

**Comment by emptymalei** [comment]
Great work. Checked all the items in the checklist. Agree to publish. 👍 

Thank you for this useful package.


Two possible minor improvements for later updates maybe. I believe these should not be blockers to the paper itself. 

The first one is for the automated test. I had a look at the Actions workflow. 
[This line in the workflow](https://github.com/berenslab/MorphoPy/blob/4cd7672d4f27909e90f671a2c9d8b9d0348257cf/.github/workflows/test.yml#L30)
```
         python3 -m pip install git+https://github.com/berenslab/MorphoPy
```
would only test the remote master branch. In this case, it works but a bit strange since you already have exactly the same files locally.

The test actually could be done for [all branches on a matrix of platforms](https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#excluding-a-version). When the `checkout` action is used, you actually have all the content on the action server "locally" so you could install and test right using all the local file. Also, the test can also be done on a matrix of platforms and many different versions of python.

The second one is about the versions of requirements. I should have mentioned this earlier. It is considered a good habit to pin the package versions in the `requirements.txt` file. For example, networkx has many breaking changes in different versions (such as members of DiGraphView) and it would be more stable if one could pin the version or range of versions in `requirements.txt`. (From a data scientist's experience, `requirements.txt` without version restrictions will drive our data dev ops crazy. 😸  )

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02339/joss.02339/10.21105.joss.02339.pdf)

**Comment by oliviaguest** [comment]
Awesome work all. So @Visdoom are you happy to move to publication? And thank you so much to @emptymalei, @mstimberg for their wonderful and useful feedback. 👏

**Comment by oliviaguest** [comment]
🔔 👋  @Visdoom yes? 😄

**Comment by Visdoom** [comment]
@oliviaguest yes! 
Sorry about the delay. I have dived head first into tutoring for the neuromatch academy and it's been hard to break to the surface of the 'other' world ever since.
Thank you so much for reviewing! ❤️

**Comment by oliviaguest** [comment]
@Visdoom ah no worries! 🤣 

Right, so we need to archive the code, can you post it on, e.g., Zenodo, figshare, etc., and post the archive DOI here, please? 😊

**Comment by oliviaguest** [comment]
@Visdoom ah, also I spotted a tiny typo: https://github.com/berenslab/MorphoPy/pull/113

When you merge that feel free to ask @whedon to recompile the PDF. 😸

**Comment by Visdoom** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02339/joss.02339/10.21105.joss.02339.pdf)

**Comment by Visdoom** [comment]
@oliviaguest the code is uploaded to Zenodo now: https://doi.org/10.5281/zenodo.3956644

**Comment by oliviaguest** [comment]
@whedon set 10.5281/zenodo.3956644 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3956644" target="_blank">10.5281/zenodo.3956644</a> is the archive.

**Comment by oliviaguest** [comment]
@whedon set v0.71 as version

**Comment by whedon** [comment]
OK. v0.71 is the version.

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02339/joss.02339/10.21105.joss.02339.pdf)

**Comment by oliviaguest** [comment]
@Visdoom is this PDF looking good to you, shall we move to acceptance? ☺️

**Comment by oliviaguest** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s12021-010-9093-7 is OK
- 10.1371/journal.pone.0182184 is OK
- 10.1007/s12021-017-9341-1 is OK
- 10.1038/s41467-019-12058-z is OK
- 10.1101/2020.02.03.929158 is OK
- 10.1038/nprot.2008.51 is OK
- 10.1016/j.cell.2007.01.040 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s12021-010-9093-7 is OK
- 10.1371/journal.pone.0182184 is OK
- 10.1007/s12021-017-9341-1 is OK
- 10.1038/s41467-019-12058-z is OK
- 10.1101/2020.02.03.929158 is OK
- 10.1038/nprot.2008.51 is OK
- 10.1016/j.cell.2007.01.040 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1608

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1608, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by oliviaguest** [comment]
@openjournals/joss-eics please check this one and I'll email @Visdoom right now to make sure they check this thread carefully.

**Comment by oliviaguest** [comment]
Ah! I just saw the ❤️ react, @Visdoom! Fantastic! 👏

**Comment by Visdoom** [comment]
@oliviaguest I noticed a minor issue in the text where it says Fig. Figure X. Can I still update it? Otherwise it is also not a tragedy.

**Comment by oliviaguest** [comment]
@Visdoom yes, update it and we can fix it. 😺

**Comment by Visdoom** [comment]
Great, it is fixed in the 'paper.md'.

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02339/joss.02339/10.21105.joss.02339.pdf)

**Comment by oliviaguest** [comment]
@Visdoom if that looks good, perfect. If it needs more changes, make them and run the command: `@whedon generate pdf` and lemme know. Does it look OK now? 🌸

**Comment by Visdoom** [comment]
Yes! Now it looks perfect. Thank you!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s12021-010-9093-7 is OK
- 10.1371/journal.pone.0182184 is OK
- 10.1007/s12021-017-9341-1 is OK
- 10.1038/s41467-019-12058-z is OK
- 10.1101/2020.02.03.929158 is OK
- 10.1038/nprot.2008.51 is OK
- 10.1016/j.cell.2007.01.040 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1611

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1611, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@Visdoom  - please merge https://github.com/berenslab/MorphoPy/pull/114 before we proceed to acceptance

**Comment by Visdoom** [comment]
@danielskatz All done!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s12021-010-9093-7 is OK
- 10.1371/journal.pone.0182184 is OK
- 10.1007/s12021-017-9341-1 is OK
- 10.1038/s41467-019-12058-z is OK
- 10.1101/2020.02.03.929158 is OK
- 10.1038/nprot.2008.51 is OK
- 10.1016/j.cell.2007.01.040 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1612

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1612, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1290295280256954369) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1613
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02339](https://doi.org/10.21105/joss.02339)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @emptymalei & @mstimberg for reviewing, and @oliviaguest for editing!

Congratulations to @Visdoom (Sophie Laturnus) and co-authors!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02339/status.svg)](https://doi.org/10.21105/joss.02339)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02339">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02339/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02339/status.svg
   :target: https://doi.org/10.21105/joss.02339
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02339/status.svg)](https://doi.org/10.21105/joss.02339)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by oliviaguest** [comment]
@emptymalei, @mstimberg thank you so much for all you have done here! 👏 

@Visdoom congratulations! 🥳

**Comment by emptymalei** [comment]
@Visdoom Congratulations! 🎉
