### ISSUE TITLE
[REVIEW]: bíogo/ncbi: interfaces to NCBI services for the Go language

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#234]
**Submitting author:** @kortschak (<a href="http://orcid.org/0000-0001-8295-2301">Robert Daniel Kortschak</a>)
**Repository:** <a href="https://github.com/biogo/ncbi" target ="_blank">https://github.com/biogo/ncbi</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @ngoto
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.582354" target="_blank">10.5281/zenodo.582354</a>

## Status

[![status](http://joss.theoj.org/papers/f1c472b8ac1d894e12bb7bbc6e9c7e2d/status.svg)](http://joss.theoj.org/papers/f1c472b8ac1d894e12bb7bbc6e9c7e2d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f1c472b8ac1d894e12bb7bbc6e9c7e2d"><img src="http://joss.theoj.org/papers/f1c472b8ac1d894e12bb7bbc6e9c7e2d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f1c472b8ac1d894e12bb7bbc6e9c7e2d/status.svg)](http://joss.theoj.org/papers/f1c472b8ac1d894e12bb7bbc6e9c7e2d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/biogo/ncbi" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/biogo/ncbi">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (kortschak) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @ngoto it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by pjotrp** [comment]
@kortschak review has started by @ngoto who runs the bioruby project(!). @kortschak please help us by ticking above boxes for us first. @ngoto, you can start after when @kortschak is ready. Thanks!

**Comment by kortschak** [comment]
@ngoto I think this is ready for you to take a look.

**Comment by ngoto** [comment]
I'm sorry too late.

I'd like to run examples in README.md.
I tried to copy-and-paste code from README.md, saved and builded, but following errors:

```
$ go build  readme-entrez.go 
# command-line-arguments
./readme-entrez.go:38: undefined: query
$ go build readme-blast.go
can't load package: 
readme-blast.go:1:1: expected 'package', found 'const'
readme-blast.go:3:2: expected ';', found 'IDENT' tool
```

**Comment by kortschak** [comment]
Sorry. I have fixed the entrez example. That was a copy-paste error. The issue with the BLAST example is that it is not intended to be a complete runnable program; providing the harness for all that would detract from the code I have provided. I have clarified this in the preamble to that example.

Please comment at [this PR](https://github.com/biogo/ncbi/pull/5).

**Comment by kortschak** [comment]
@ngoto I believe I have addressed all of your concerns.

**Comment by ngoto** [comment]
> Performance: Have any performance claims of the software been confirmed?
It seems that no description about performance (only a phrase "light weight" ?). I suppose the running performance is fully depended on NCBI.

**Comment by kortschak** [comment]
We make no claims about performance since the vast majority of computational effort is made by the NCBI servers or the local BLAST executable.

I don't believe that syntactic weight constitutes performance, but I guess that could be assessed by comparison of exported function count or SLOC with other similar suites.

**Comment by pjotrp** [comment]
Thanks @ngoto! Looks like we are pretty much done. There are no real claims on performance, so it is OK not to tick that box. If you are happy we can push for publication.

**Comment by ngoto** [comment]
Thanks. Finished. Sorry for delay.

**Comment by pjotrp** [comment]
Thank you so much @ngoto! @arfon we are ready to R&R!

**Comment by arfon** [comment]
@kortschak - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by kortschak** [comment]
@arfon Done.

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.582354.svg)](https://doi.org/10.5281/zenodo.582354)

`doi:10.5281/zenodo.582354`

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.582354 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.582354" target="_blank">10.5281/zenodo.582354</a> is the archive.

**Comment by arfon** [comment]
@ngoto - many thanks for your review here and thanks to @pjotrp for editing this submission ✨ 

@kortschak - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00234 ⚡️ 🚀 💥
