### ISSUE TITLE
[REVIEW]: FIPS: An R Package for Biomathematical Modelling of Human Fatigue Related Impairment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2340]
**Submitting author:** @humanfactors (<a href="http://orcid.org/0000-0003-4143-7308">Michael David Wilson</a>)
**Repository:** <a href="https://github.com/humanfactors/FIPS" target ="_blank">https://github.com/humanfactors/FIPS</a>
**Version:** v0.1.1
**Editor:** @oliviaguest
**Reviewer:** @craddm, @anibalsolon
**Archive:** <a href="https://doi.org/10.5281/zenodo.3945615" target="_blank">10.5281/zenodo.3945615</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/114047c1eaa8b3df707632a2b94a9d47/status.svg)](https://joss.theoj.org/papers/114047c1eaa8b3df707632a2b94a9d47)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/114047c1eaa8b3df707632a2b94a9d47"><img src="https://joss.theoj.org/papers/114047c1eaa8b3df707632a2b94a9d47/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/114047c1eaa8b3df707632a2b94a9d47/status.svg)](https://joss.theoj.org/papers/114047c1eaa8b3df707632a2b94a9d47)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/humanfactors/FIPS" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@craddm & @anibalsolon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @oliviaguest know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/humanfactors/FIPS">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@humanfactors) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/humanfactors/FIPS">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@humanfactors) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @craddm, @anibalsolon it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2340 with the following error: 

 Can't find any papers to compile :-(

**Comment by oliviaguest** [comment]
Hey everybody! @craddm, @anibalsolon, @humanfactors welcome to where the review itself is going to be! 

First off, thank you so much to the reviewers for agreeing and generally being so speedy and excited to get this paper and code reviewed. ☺️  

If you have any very code-related issues use the repo of the code and open an issue and link to it from here. All other issues, feedback, questions for me or the author, please use this issue. Anything you need, check above first as there is a lot of into up there, but also please feel free to ask me. 🌷

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2340 with the following error: 

 Can't find any papers to compile :-(

**Comment by oliviaguest** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02340/joss.02340/10.21105.joss.02340.pdf)

**Comment by oliviaguest** [comment]
Can @craddm and @anibalsolon give me a rough ETA on their reviews please? ☺️

**Comment by anibalsolon** [comment]
Hi @oliviaguest , my ETA is at most this Wednesday, Jun 24!

**Comment by craddm** [comment]
@oliviaguest It's next on my list of reviews. will at least start by this Thursday.

**Comment by oliviaguest** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper
. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2340 with the following error: 

 error: pathspec 'joss-paper
' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2340 with the following error: 

 Can't find any papers to compile :-(

**Comment by oliviaguest** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper
. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2340 with the following error: 

 error: pathspec 'joss-paper
' did not match any file(s) known to git.
Can't find any papers to compile :-(

**Comment by oliviaguest** [comment]
@openjournals/dev is this `Can't find any papers to compile :-(` a GitHub thing or a @whedon thing?

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02340/joss.02340/10.21105.joss.02340.pdf)

**Comment by danielskatz** [comment]
@oliviaguest - maybe a transient error?  anyhow, seems ok now

**Comment by oliviaguest** [comment]
Hey @humanfactors — are you currently working on anything for this? ☺️

**Comment by humanfactors** [comment]
Hi @oliviaguest, I assume you mean in terms of package?

Currently, we are not working on any features beyond bug fixes, and will likely remain like this for a couple of months. There are future development plans to extend the modelling interface (potentially), improve theming of the plots, and incorporate an additional model. However, this is likely to be based on demand, resources, and package reception.

More broadly, we currently have a couple of papers in progress that directly depend on FIPS, so we are regularly working with FIPS.

Not sure if that answers the question though. Thanks again for assistance thus far.

**Comment by oliviaguest** [comment]
Ah, cool. I was wondering for this JOSS paper specifically, but that all sounds very organised — nice. Have you all @craddm, @anibalsolon, @humanfactors discussed what needs to be done for this to have all boxes ticked/checked above? ☺️

**Comment by craddm** [comment]
hi @oliviaguest, @humanfactors  - I can answer that - no. I'm back to it this morning.

**Comment by oliviaguest** [comment]
@craddm fabulous and thank you. No massive pressure really, I just felt the need to check in on you all. 🌸

**Comment by craddm** [comment]
Hi @humanfactors, 

This seems like an interesting package, and everything I've tried with it so far has worked great. A couple of comments, in no particular order:

- I initially thought there were a few functions that don't currently have examples (e.g. `expand_sleep_series()`) that would benefit from them. But then I realized that those functions aren't exported, user-facing functions. You might want to make them internal functions (e.g. using `@keywords internal`) so that they don't show up in the user-facing API docs

- I'm not generally familiar with the area so have no example data of my own to test the package out. The package has a great vignette that generates data of the appropriate type, but one thing I'm left a little curious about is how you *normally* get data of that type. Specifically, there's a function mentioned in the pdf, `parse_sleepwake_sequence()`, that's intended for dealing with a common format used by other software for sleep/wake sequences. Examples of this type of data and the use of the function would be appreciated.

-  I can see you have some tests set up using `testthat`, which is great. But I'd also suggest hooking them up to a continuous integration service such as Travis-CI.

Matt

**Comment by humanfactors** [comment]
Hi @craddm 

Thanks for your feedback, very much appreciated. I've now opened a pull request (see above) with several changes to the repository to address your review comments. Feel free to add any detailed comments there.

In reference to your second point, I would like to clarify:

1. Were you suggesting any changes in the manuscript are required to make clearer typical data sources? Currently, I haven't made changes to the paper.
2. Have the changes in vignettes and documentation addressed the concerns about data sources? There are quite a number of _exact_  data file types [that come from sleep tracking tech], but in our experience almost all use the bitvector as the core outputted data. 

Also cheers @oliviaguest for following up on this.

**Comment by anibalsolon** [comment]
Hi all,

Thank you for the follow-up, @oliviaguest!

----

Thank you for the contribution @humanfactors I am sure several will benefit from an open-source solution of these models!
Here are my two cents:

1. Following @craddm comments, CI integration is a great addition, and I am glad you got that working already. As a suggestion, adding code coverage to the CI pipeline provides you with some information about how much of your code has been tested, giving you a perspective on what is missing. Some references for that: https://github.com/r-lib/covr
 　
 Together with coverage, adding a linting tool helps to see what the tired eyes might not get, such as styling and misreference to/unused variables. Here is an example of how to integrate with a CI tool: https://cran.r-project.org/web/packages/lintr/readme/README.html#continuous-integration
 　
 And here is an example of `lintr` for `R/FIPS_df.R` on RStudio:
![image](https://user-images.githubusercontent.com/562525/86938497-1ab11980-c106-11ea-8a51-fd77a0265d7d.png)


2. I saw you added the `CONTRIBUTING.md` file to the repo, which is good! It gives newcomers a better sense of how things work for your project (personally, it reduces a lot of anxiety). I would like to suggest to take a look at the Contributing guidelines from fMRIPrep, they did a great job here: https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md
 　
 I do not believe it needs to be this thorough, so I point to two main aspects of it: **Issues and Pull requests**.
  * For **issues**, I would suggest you could give some pointers on which information is needed so the collaborators can understand the problem and help the user debug it, hopefully reaching a fix. So, let's say, it would prevent one to open an issue like "It does not work!!1!1!", although people have been much more reasonable these days. Along with that, Github provides issue templates, in which you can provide some basic text for which information would smooth out the debugging process e.g. R version, Operational System, FIPS version. This is how it works: https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
  * For **pull requests**, you can also provide a template for the relevant information for the PR e.g. what it solves, why is it needed, etc. But also, it would be nice including to the Contributing guidelines some technical aspects like code formatting, function documentation with docstring, and how to run tests locally during development.

The manuscript is well-written, and it seems to me that it covers the required details of this package.

**Comment by humanfactors** [comment]
Thank you @anibalsolon for your insightful review. I've added our changes directly to the already open pull request on the `joss-craddm` branch https://github.com/humanfactors/FIPS/pull/3

> As a suggestion, adding code coverage to the CI pipeline provides you with some information about how much of your code has been tested, giving you a perspective on what is missing. Some references for that: https://github.com/r-lib/covr

We really appreciated this suggestion, as I had often wondered how coverage reports were generated. I've now added this to the Travis CI script and also run the function locally. I'm satisfied with the coverage, and in fact was surprised it was that high. Moreover, adding this detected a missing `tests/testthat.R` file!

![image](https://user-images.githubusercontent.com/16096044/87013520-5975cb00-c1fd-11ea-8e26-d82d769d086e.png)

> Together with coverage, adding a linting tool helps to see what the tired eyes might not get, such as styling and misreference to/unused variables. 

We carefully considered including a linting tool in the automated builds. Indeed, @lukestrickland and I both went through the linting suggestions run by `lintr`. We found only a small subset of the enormous number of suggestions were of significant importance, but have corrected issues that clearly violated our code style guide. In line with this, we do now recognize the need for our conventions to be mapped out more explicitly to better support potential contributors. In response to your second point, we have now added additional documentation to the `CONTRIBUTING.md` file (e.g., 120 column max). 

We hope the package will experience more community growth, and will certainly revisit the need for automated linting and a custom `.lintr` specification at that future time.

> I saw you added the CONTRIBUTING.md file to the repo, which is good! It gives newcomers a better sense of how things work for your project (personally, it reduces a lot of anxiety). I would like to suggest to take a look at the Contributing guidelines from fMRIPrep, they did a great job here: https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md

We have now clarified and expanded our `CONTRIBUTING.md` file, and adopted your suggestion of providing a Github Issue Template for bug reports. Once again, I appreciate your keen eye of the features of Github as I didn't know this existed and indeed may save effort following up "lower quality" bug reports.

> For pull requests, you can also provide a template for the relevant information for the PR e.g. what it solves, why is it needed, etc. But also, it would be nice including to the Contributing guidelines some technical aspects like code formatting, function documentation with docstring, and how to run tests locally during development.

The `CONTRIBUTING.md` now includes descriptions of:

- Package-specific code style
- The automated testing software run for local development `testthat`
- The automatic documentation generator (`roxygen2`)

In the spirit of transparency, we've also added a note to specify that we would prefer potential contributors to reach out to us prior to making a large pull request. This is for three reasons:

1. We do have some development efforts planned for the future. Ideally, we want to prevent any duplicated efforts.
2. Knowledge that others are interested in working on the package would help us determine how best to position a more expansive `CONTRIBUTING.md`, similar to that of `fmriprep`.
3. [Most importantly], it would make us very happy to hear other users of the package.

---------------

If there's no further additions, I will merge the open pull request into master.

Cheers,

Michael

**Comment by craddm** [comment]
> Hi @craddm
> 
> Thanks for your feedback, very much appreciated. I've now opened a pull request (see above) with several changes to the repository to address your review comments. Feel free to add any detailed comments there.
> 
> In reference to your second point, I would like to clarify:
> 
> 1. Were you suggesting any changes in the manuscript are required to make clearer typical data sources? Currently, I haven't made changes to the paper.
> 2. Have the changes in vignettes and documentation addressed the concerns about data sources? There are quite a number of _exact_  data file types [that come from sleep tracking tech], but in our experience almost all use the bitvector as the core outputted data.
> 
> Also cheers @oliviaguest for following up on this.

1) No 2) Yes :) I'm happy with the changes you've made. Thanks!

**Comment by anibalsolon** [comment]
That's a fine work, @humanfactors, I am really happy with its results. Thank you!

The coverage is pretty high indeed and what is not covered does not seem to impact the core features of that package. So, 🎉 

I understand your point about linting, they can be nit-picky. Your details in the Contributing doc is good enough for new collaborators.

That said, the new modifications are good to go, in my opinion. Congratulations on the project, and thank you for open-sourcing it!

**Comment by oliviaguest** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper
. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02340/joss.02340/10.21105.joss.02340.pdf)

**Comment by oliviaguest** [comment]
@humanfactors I am happy with this and happy to accept now. Is there anything you want edit or add?

**Comment by oliviaguest** [comment]
Reviewers, @craddm, @anibalsolon, thank you so much for all your useful input here. 👏

**Comment by humanfactors** [comment]
Hi @oliviaguest. I've made a few minor tweaks on the master branch. I'll try build from that below.

I will just await my co-authors final check of this (should be tomorrow morning). Thank you!

**Comment by humanfactors** [comment]
@whedon generate pdf from branch master

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch master. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02340/joss.02340/10.21105.joss.02340.pdf)

**Comment by humanfactors** [comment]
@whedon generate pdf from branch master

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch master. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02340/joss.02340/10.21105.joss.02340.pdf)

**Comment by lukestrickland** [comment]
@humanfactors This all looks ready to me. Thank you @craddm @anibalsolon @oliviaguest

**Comment by humanfactors** [comment]
Perfect thankyou @lukestrickland ! I have no further changes @oliviaguest, happy to progress this. Yet again, appreciative of your time and effort. Kind regards.

**Comment by oliviaguest** [comment]
Great! Can you archive the code please at your favourite place to do so, so create an archive (on Zenodo, figshare, or other) and post the archive DOI here? ☺️

**Comment by oliviaguest** [comment]
@whedon check references

**Comment by oliviaguest** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1080/07420520802110613 is OK
- 10.1016/j.aap.2015.11.032 is OK
- 10.1016/j.aap.2009.12.030 is OK
- 10.1080/00140139.2017.1417641 is OK
- 10.5665/sleep.5358 is OK
- 10.18637/jss.v076.i01 is OK
- 10.18637/jss.v059.i10 is OK
- 10.1007/s42113-019-00054-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@humanfactors sorry for not tagging you above, but yes, when you get a chance post the DOI.

**Comment by humanfactors** [comment]
Cheers for that. I've now worked out how to upload via Zenodo.

https://zenodo.org/record/3945615 see `10.5281/zenodo.3945615`

☺ Thanks

**Comment by oliviaguest** [comment]
@whedon set 10.5281/zenodo.3945615 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3945615" target="_blank">10.5281/zenodo.3945615</a> is the archive.

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1080/07420520802110613 is OK
- 10.1016/j.aap.2015.11.032 is OK
- 10.1016/j.aap.2009.12.030 is OK
- 10.1080/00140139.2017.1417641 is OK
- 10.5665/sleep.5358 is OK
- 10.18637/jss.v076.i01 is OK
- 10.18637/jss.v059.i10 is OK
- 10.1007/s42113-019-00054-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1571

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1571, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by oliviaguest** [comment]
@humanfactors please check the final version of the PDF when you have a moment and let me know if it's looking good from your end. 😊

**Comment by labarba** [comment]
The version tag in the repository does not reflect here. Can you confirm it should be updated to v0.1.1?

**Comment by labarba** [comment]
@humanfactors -- Could you update the title of the Zenodo deposit to match the title of the JOSS paper? Thx.

**Comment by humanfactors** [comment]
Hi @labarba , I'll admit confusion here on my end, apologies for that.

> The version tag in the repository does not reflect here. Can you confirm it should be updated to v0.1.1?

I updated the version number in light of the changes made through the review process, so `0.1.1` is correct. I thought I should delineate between pre-review and post-review repository. Let me know if that wasn't correct step.

> Could you update the title of the Zenodo deposit to match the title of the JOSS paper? Thx.

I've changed now, I hadn't used Zenodo prior, and linked with this the release.

Cheers!

**Comment by labarba** [comment]
I found just one typo in the caption of the figure: "indicting" for "indicating."

**Comment by labarba** [comment]
@whedon set v0.1.1 as archive

**Comment by whedon** [comment]
v0.1.1 doesn't look like an archive DOI.

**Comment by labarba** [comment]
@whedon set v0.1.1 as version

**Comment by whedon** [comment]
OK. v0.1.1 is the version.

**Comment by labarba** [comment]
Typo fix here: https://github.com/humanfactors/FIPS/pull/6

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02340/joss.02340/10.21105.joss.02340.pdf)

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by labarba** [comment]
@openjournals/dev -- is `whedon` taking a nap?

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1283483551707561990) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1576
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02340](https://doi.org/10.21105/joss.02340)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @humanfactors, your JOSS paper is published! 🚀 

Huge thanks to our editor: @oliviaguest, and reviewers: @craddm, @anibalsolon 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02340/status.svg)](https://doi.org/10.21105/joss.02340)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02340">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02340/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02340/status.svg
   :target: https://doi.org/10.21105/joss.02340
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02340/status.svg)](https://doi.org/10.21105/joss.02340)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by oliviaguest** [comment]
Yes, indeed! Thank you all @craddm @anibalsolon @labarba and congratulations to @humanfactors! 🥳 💓

**Comment by arfon** [comment]
@editorialbot re-accept

**Comment by arfon** [comment]
@editorialbot reaccept

**Comment by arfon** [comment]
@editorialbot reaccept
