### ISSUE TITLE
[PRE REVIEW]: xai2cloud: the R package for automated cloud deployment of machine learning models with XAI REST API

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2344]
**Submitting author:** @Adamoso (<a href="http://orcid.org/0000-0002-4805-9015">Adam Rydelek</a>)
**Repository:** <a href="https://github.com/ModelOriented/xai2cloud" target ="_blank">https://github.com/ModelOriented/xai2cloud</a>
**Version:** v1.0.0
**Editor:** @bmcfee
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Adamoso. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @terrytangyuan.

@Adamoso if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.02 s (856.5 files/s, 56368.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               11             63            160            409
YAML                             6             34              0            235
TeX                              1             19              0            177
Markdown                         2             63              0            136
Rmd                              1             12             41             33
-------------------------------------------------------------------------------
SUM:                            21            191            201            990
-------------------------------------------------------------------------------


Statistical information for the repository '2344' was gathered on 2020/06/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adamoso                          2           361            361          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01444 is OK
- 10.1109/TVCG.2019.2934619 is OK
- 10.21105/joss.01798 is OK
- 10.18637/jss.v082.i11 is OK
- 10.12688/f1000research.20843.1 is OK
- 10.1080/10618600.2019.1585259 is OK
- 10.32614/RJ-2018-072 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02344/joss.02344/10.21105.joss.02344.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@bmcfee @mjsottile @danielskatz could one of you handle this submission?

**Comment by bmcfee** [comment]
I've got a bit of a full plate right now, but could pick it up if nobody else can.

**Comment by mjsottile** [comment]
I cannot: I’m saturated for the next month or so.

**Comment by danielskatz** [comment]
@bmcfee - if you are comfortable with this, please take it.  I'm not really an R person...

**Comment by Kevin-Mattheus-Moerman** [comment]
@bmcfee I'll assign you as editor. We've clarified to authors that the review process will take longer than usual (see post linked to above) so this submission can wait until you are able to pick it up once your "plate" has cleared up a bit.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
OK, the editor is @bmcfee

**Comment by Kevin-Mattheus-Moerman** [comment]
@Adamoso as mentioned above JOSS is operating in a reduced service mode. It has been challenging for us to find reviewers/editors and operate at our usual efficiency. We apologize for the inconvenience. The handling editor @bmcfee will pick this up once they are able to. 

In the mean time it would be helpful if you could suggest reviewers. You also have time to review our guidelines to and update your paper if needed (simply call `@whedon generate pdf` here to update your paper). You can also work on adding contributor guidelines (if you haven't yet), and other such requirements, to your repository.

**Comment by Adamoso** [comment]
@Kevin-Mattheus-Moerman thank you for the response. I'm aware of the situation and restrictions associated with it, so I was prepared for a longer waiting time and this is not an issue.
I've checked the JOSS document for suitable reviewers and would like to suggest martinju, expectopatronum, ja-thomas, and acolum.

**Comment by bmcfee** [comment]
Ok, no problem. Things should clear up for me after next week.

**Comment by Adamoso** [comment]
Hello @bmcfee, @Kevin-Mattheus-Moerman,
I'm aware that there are many inconveniences associated with Covid but I would like to ask, whether there is any progress on the editing site?

**Comment by bmcfee** [comment]
Hi @Adamoso -- attempted progress to be sure, though I'm still working on finding reviewers.  (Invitations have gone out, but no accepts as of yet.)  I'll keep at it though!

**Comment by Adamoso** [comment]
Thank you for the update, glad to hear that!

**Comment by bmcfee** [comment]
Indeed -- I've been trying, oh how I've been trying! -- but august is tough even in good times.  I'll put out another blast shortly.

**Comment by kthyng** [comment]
@bmcfee Sorry to intervene here but I'd like to kick this back to the editorial board for discussion.

@Adamoso This package is just above our minimum size for submissions so it is JOSS policy now to query the scope before going out to review. If you have any context or additional information you'd like to add for our consideration, feel free to do so in this pre-review issue, but it isn't necessary.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hi @Adamoso - unfortunately, the JOSS editors have decided that this submission does not meet the substantial scholarly effort criterion for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
