### ISSUE TITLE
[PRE REVIEW]: Hydro Explorer: An interactive web app to investigatechanges in runoff seasonality and runoff timing all overthe world

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2345]
**Submitting author:** @ERottler (<a href="http://orcid.org/0000-0003-3072-2189">Erwin Rottler</a>)
**Repository:** <a href="https://github.com/ERottler/meltimr" target ="_blank">https://github.com/ERottler/meltimr</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ERottler. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@ERottler if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (650.6 files/s, 50957.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               21            415            310           1061
Markdown                         2             38              0             58
CSS                              1              5              6             38
TeX                              1              3              0             24
-------------------------------------------------------------------------------
SUM:                            25            461            316           1181
-------------------------------------------------------------------------------


Statistical information for the repository '2345' was gathered on 2020/06/15.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02345/joss.02345/10.21105.joss.02345.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@ERottler thank you for your submission. The editorial board has decided this work is not in scope for JOSS (see also our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and statements on "Minor ‘utility’ packages, including ‘thin’ API clients, and single-function packages"). 
Of course this conclusion says nothing about the value/usefulness of the work submitted, it merely means JOSS is not the right place to publish it. We will therefore proceed to reject this work as it stands.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
