### ISSUE TITLE
[PRE REVIEW]: PyMMS: Implementation of a non-numeric spacetime model with the Minkowski metric

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2346]
**Submitting author:** @vgurianov (<a href="http://orcid.org/0000-0003-2667-4241">Vasyliy Gurianov</a>)
**Repository:** <a href="https://github.com/vgurianov/srt" target ="_blank">https://github.com/vgurianov/srt</a>
**Version:** v1.0.9
**Editor:** @eloisabentivegna
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vgurianov. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @eloisabentivegna.

@vgurianov if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (390.0 files/s, 66309.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            808            629           2373
Markdown                        16            415              0           1559
HTML                             2              9              3             66
YAML                             4              2              2             41
TeX                              1              4              0             40
-------------------------------------------------------------------------------
SUM:                            35           1238            634           4079
-------------------------------------------------------------------------------


Statistical information for the repository '2346' was gathered on 2020/06/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vasyliy I. Gurianov             53          8693           4883          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vasyliy I. Gurianov        3810           43.8          1.3               13.65
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02346/joss.02346/10.21105.joss.02346.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@eloisabentivegna @xuanxu @dfm @harpolea could one of you handle this submission? Thanks

**Comment by vgurianov** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02346/joss.02346/10.21105.joss.02346.pdf)

**Comment by vgurianov** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02346/joss.02346/10.21105.joss.02346.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@eloisabentivegna @xuanxu @dfm @harpolea could one of you handle this submission? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @eloisabentivegna as editor

**Comment by whedon** [comment]
@eloisabentivegna has been invited to edit this submission.

**Comment by eloisabentivegna** [comment]
@whedon assign @eloisabentivegna as editor

@Kevin-Mattheus-Moerman Yes, I can handle this.

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by vgurianov** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02346/joss.02346/10.21105.joss.02346.pdf)

**Comment by eloisabentivegna** [comment]
Dear @vgurianov, thanks for your submission to JOSS. After a discussion with the other editors, it was determined that PyMMS’s functionality is both too limited and lacking a clear research application. It therefore does not satisfy the [requirements for submission to JOSS](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and is presently not suitable for publication in this journal.

**Comment by eloisabentivegna** [comment]
@whedon reject

**Comment by whedon** [comment]
I'm sorry @eloisabentivegna, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by eloisabentivegna** [comment]
@Kevin-Mattheus-Moerman, can you help?

**Comment by danielskatz** [comment]
@eloisabentivegna  - you should tag @openjournals/joss-eics for this to get the on-duty person each week, but I'll take care of it.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by eloisabentivegna** [comment]
@danielskatz, thanks for your help and guidance.
