### ISSUE TITLE
[REVIEW]: pypillometry: A Python package for pupillometric analyses

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2348]
**Submitting author:** @ihrke (<a href="http://orcid.org/0000-0003-0205-7353">Matthias Mittner</a>)
**Repository:** <a href="https://github.com/ihrke/pypillometry" target ="_blank">https://github.com/ihrke/pypillometry</a>
**Version:** v1.0.0
**Editor:** @oliviaguest
**Reviewers:** @samhforbes, @szorowi1, @tjmahr
**Archive:** <a href="https://doi.org/10.5281/zenodo.3925528" target="_blank">10.5281/zenodo.3925528</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3b06f4f3d5b703fd99c7e622b7edebe4/status.svg)](https://joss.theoj.org/papers/3b06f4f3d5b703fd99c7e622b7edebe4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3b06f4f3d5b703fd99c7e622b7edebe4"><img src="https://joss.theoj.org/papers/3b06f4f3d5b703fd99c7e622b7edebe4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3b06f4f3d5b703fd99c7e622b7edebe4/status.svg)](https://joss.theoj.org/papers/3b06f4f3d5b703fd99c7e622b7edebe4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ihrke/pypillometry" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@samhforbes & @szorowi1, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @oliviaguest know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ihrke/pypillometry">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ihrke) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ihrke/pypillometry">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ihrke) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ihrke/pypillometry">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ihrke) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @samhforbes, @szorowi1 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5334/joc.18 is OK
- 10.1126/science.132.3423.349 is OK
- 10.3758/s13428-020-01374-8 is OK
- 10.1146/annurev.neuro.28.061604.135709 is OK
- 10.3758/cabn.10.2.252 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02348/joss.02348/10.21105.joss.02348.pdf)

**Comment by oliviaguest** [comment]
Hi all! 👋  Thank you so much, @samhforbes, @szorowi1, for accepting to review this software package and paper by @ihrke! 😊 

Any questions, feedback on the paper, etc., please post here. Any *very* code-specific questions, suggestions, etc., please use the issues in the code repo and link to them from this thread so we can all keep track of them. 🌸 

Thank you again, Sams!

**Comment by oliviaguest** [comment]
@whedon add @tjmahr as reviewer

**Comment by whedon** [comment]
OK, @tjmahr is now a reviewer

**Comment by oliviaguest** [comment]
Can @samhforbes, @szorowi1, and @tjmahr give me a rough ETA on their reviews please? ☺️

**Comment by samhforbes** [comment]
Installation instructions: Is there a clearly-stated list of dependencies? Link to more in depth installation instructions for PySTan:
https://github.com/ihrke/pypillometry/issues/4

 Example usage and functionality documentation 
ideally would have documentation on modelling data. https://github.com/ihrke/pypillometry/issues/1

 Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
https://github.com/ihrke/pypillometry/issues/2

 References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?
DOIs need to be included for a number of papers. See https://github.com/ihrke/pypillometry/issues/3

**Comment by ihrke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2348 with the following error: 

 Can't find any papers to compile :-(

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02348/joss.02348/10.21105.joss.02348.pdf)

**Comment by oliviaguest** [comment]
@whedon add @tjmahr as reviewer

**Comment by whedon** [comment]
OK, @tjmahr is now a reviewer

**Comment by oliviaguest** [comment]
@whedon re-invite @tjmahr as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@tjmahr please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by szorowi1** [comment]
Hi all, had the pleasure of trying out `pypillometry` this week. I was successfully able to install `pypillometry` and then load in my own data, perform preprocessing (blink detection + correction, filtering, rescaling) with ease, and compute/plot ERPDs. The examples were more than enough help to adapt the code to my data, and the API was detailed and easy to read. Overall, the package is very impressive, especially the natural chaining/logging of preprocessing steps. Really cool stuff, @ihrke!

I've made a couple of minor suggestions about installation details here, https://github.com/ihrke/pypillometry/issues/5. I also agree with @samhforbes that more documentation about the modeling functions would be helpful, as is currently being discussed here, https://github.com/ihrke/pypillometry/issues/1.

**Comment by ihrke** [comment]
Thanks @samhforbes and @szorowi1 for nice comments and suggestions! I have tried to address them in the issues over at ihrke/pypillometry and added the `propose-close` label. If you are happy with the changes, can you close the respective issues?
The remaining issues are

- ihrke/pypillometry#1 (documentation of modeling: I added two notebooks with hopefully helpful information)
- ihrke/pypillometry#5 (installation via pypi: I have added this functionality and updated the installation instructions)
- ihrke/pypillometry#6 (fixed some typos)

Thanks for a great process so far and looking forward to further comments!

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02348/joss.02348/10.21105.joss.02348.pdf)

**Comment by samhforbes** [comment]
@ihrke I'm satisfied that you've answered my queries, and I've ticked those remaining boxes. Well done on what I feel is a really important package.

**Comment by oliviaguest** [comment]
@samhforbes thank you so much! I might ask you all to check the very final version one last time when all reviewers have given comments and @ihrke has made all edits (e.g., in the rare case there are any divergences of opinion or feedback needed on anything), but for now feel free to go off and do other stuff, Sam H.! 👏

**Comment by tjmahr** [comment]
Thank you for this opportunity to review this package. I have written a few lab-specific in-house R packages for managing eyetracking data, so I applaud the effort to provide a general-purpose tool for working with eyetracking data. 

I have two disclaimers: I have not formally analyzed pupil data beyond the data-cleaning stage and I seldom use Python.

The documentation is comprehensive and generously provides several notebooks with binder links. The installation instructions helped me use virtual environments for the first time ever. Functions that provide fake data also help learners play with the package. 

I have Python 3.6.4 via Anaconda on Windows 10. Installation via cloning from Github and installing dependencies with pip 18.1 went smoothly. I tested the package on some 60 Hz Tobii data I had from an eyetracking task with preschoolers. I created csvs of gaze measurements and event onsets in R. Then in Python I was able to create a plot of pupil diameter over time with trial events annotated. It was cool to move from my own csvs to a nice default plot in a few steps.

I was unable to use velocity based blink detection (it raised an error), so I looked up the API reference for `blink_detect()` and tried
`d.blinks_detect(strategies = ["zero"])`. This worked, but it treated all of the intertrial intervals (during which the eyetracker is not running) in the dataset as blinks (below). Fair enough. 

![image](https://user-images.githubusercontent.com/1890315/86173894-52a4d500-bae6-11ea-8384-2794c296e13d.png)

After downsampling to 5 Hz, I noticed that these same blinks were changed to one spurious blink.

![image](https://user-images.githubusercontent.com/1890315/86173990-77994800-bae6-11ea-8ebd-86aa11f80981.png)

At this point, I gave up on trying to use blink detection or interpolation on my data because it was far too noisy and from a task that was never meant to analyze pupil size. That said, the availability of diagnostic plotting, as in `d.blinks_interp_mahot(plot=True, plot_dim=(7,4))`, is a user-friendly addition.

I have to ask: Is there a minimum sampling frequency required for blink analysis? Does the package make any assumptions about the capability of the eyetracker? How should missing eyetracking data be coded in csv file?

The pipeline based processing is a terrific design. By storing the data in a `PupilData` object,  the data can keep track of the changes made to it. And because the history is itself data, it can be applied to other objects with the `apply_history()`. This set of features is awesome for reproducibility and usability. 

In eyetracking, we often want to see how gaze measures change in response to some event and adjust times around that event. This package's ERPD (event-related pupil dilation) nicely handles this process by allowing users to select an event and time window before and after this event. It also provides automatic plotting of aggregating gaze measurements. I was not able to get it to work on my noisy Tobii data, but I reproduced the plots in the notebook using the supplied data.

I ran through the phasic and tonic components to confirm that I was able to get pystan to do the modeling.

***

I would recommend this package to any person analyzing pupil data. The history feature is a really smart way to let users prototype a workflow on a single dataset and then quickly apply it to several datasets. My only concern is that it was not clear what requirements are placed on the data.

**Comment by szorowi1** [comment]
Just wanted to say that with the closing of https://github.com/ihrke/pypillometry/issues/1, I'm totally satisfied! 

Again, really nice work @ihrke! Will absolutely be recommending this package to the folks collecting pupillometry data in my center

**Comment by ihrke** [comment]
Thanks @tjmahr and @szorowi1 for nice and thorough reviews!

Re your experiences with Tobii data, @tjmahr: the question about requirements for data-quality is a good one and one that is hard to answer in general. With the "spotty" data in your figures, many of the blink-features that are based on velocity profiles and detecting points surrounding the blinks are indeed bound to fail. I also see a couple of non-blink artifacts in your dataset which will seriously lead astray the blink-detection/interpolation. Generalizing from these plots to the rest of the data, to make any valid inferences about PD in the presence of so many missing data may be doubtful. One strategy would be to try and interpolate consistent blinks (i.e., with visible pre-post transients) and then go for a more aggressive interpolation-strategy (i.e., interpolate across all missing data) for the remaining time-series. 

`pypillometry` was developed using mainly data from three eyetrackers in our lab (two different Eyelinks and a SMI) which is collected during stationary laboratory tasks typically using chin-rests and under constant lighting conditions. Hence, data-quality was likely high and `pypillometry`'s functions will be necessarily tailored and biased towards this data. I hope that with time, as more people and labs start using the package, we will be able to get experience with more diverse datasets and match functionality of the package. Perhaps you would like to upload an example data-file and some details about the problems in an issue over at https://github.com/ihrke/pypillometry? I'll leave the decision about whether this is critical for acceptance of the JOSS-paper or not to you.

**Comment by tjmahr** [comment]
Thanks for the response. (I forgot that some eye trackers have chin rests. I was using data from a 4 year old with a free field eye tracker.) I don’t think it’s critical to address for publication.

I’m satisfied. Ship it. 👁

**Comment by oliviaguest** [comment]
> I’m satisfied. Ship it. 👁

@tjmahr LMFAO! 👏 

Thank you so much, all! @szorowi1 @samhforbes @tjmahr — great work! 💯

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02348/joss.02348/10.21105.joss.02348.pdf)

**Comment by oliviaguest** [comment]
@ihrke is that looking good to you? If you need to make any changes, please do and compile the PDF again (as I did above). ☺️

**Comment by ihrke** [comment]
This looks great to me @oliviaguest! Thanks again @samhforbes, @tjmahr and @szorowi1 for a constructive round of reviews!

**Comment by oliviaguest** [comment]
Oh, nice, we can get this published then! @ihrke can you create an archive of the code (on Zenodo, figshare, or other) and post the archive DOI here, please?

**Comment by ihrke** [comment]
sure thing! https://doi.org/10.5281/zenodo.3925528

**Comment by oliviaguest** [comment]
@whedon set 10.5281/zenodo.3925528 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3925528" target="_blank">10.5281/zenodo.3925528</a> is the archive.

**Comment by oliviaguest** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5334/joc.18 is OK
- 10.1177/1745691611427305 is OK
- 10.1126/science.132.3423.349 is OK
- 10.3758/s13428-020-01374-8 is OK
- 10.21105/joss.02285 is OK
- 10.1146/annurev.neuro.28.061604.135709 is OK
- 10.1016/j.neuron.2015.11.028 is OK
- 10.1016/j.tics.2016.06.004 is OK
- 10.3758/cabn.10.2.252 is OK
- 10.3233/978-1-61499-649-1-87 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by oliviaguest** [comment]
@openjournals/joss-eics please accept this! ✨

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1529

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1529, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by oliviaguest** [comment]
@ihrke dunno why @whedon ignored me the first time — check final proof please and an EiC will pop by soon and do the deal fully. 🥳

**Comment by ihrke** [comment]
this looks nice, all links in the final PDF are functioning 👍

**Comment by danielskatz** [comment]
@ihrke - can you edit the metadata in the zenodo archive so that the title matches the title of the paper?

**Comment by danielskatz** [comment]
Once you do so, this appears ready to publish

**Comment by ihrke** [comment]
Thanks @danielskatz, I fixed it.

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1278664499503955968) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1535
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02348](https://doi.org/10.21105/joss.02348)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @samhforbes, @szorowi1, @tjmahr for reviewing!
And @oliviaguest for editing!

Congratulations to @ihrke (Matthias Mittner)!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02348/status.svg)](https://doi.org/10.21105/joss.02348)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02348">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02348/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02348/status.svg
   :target: https://doi.org/10.21105/joss.02348
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02348/status.svg)](https://doi.org/10.21105/joss.02348)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
