### ISSUE TITLE
[REVIEW]: impedance.py: A Python package for electrochemical impedance analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2349]
**Submitting author:** @mdmurbach (<a href="http://orcid.org/0000-0002-6583-5995">Matthew D. Murbach</a>)
**Repository:** <a href="https://github.com/ECSHackWeek/impedance.py" target ="_blank">https://github.com/ECSHackWeek/impedance.py</a>
**Version:** v1.0.1
**Editor:** @mbobra
**Reviewer:** @ma-sadeghi, @EricaEgg
**Archive:** <a href="https://doi.org/10.5281/zenodo.3955199" target="_blank">10.5281/zenodo.3955199</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1d6e062c3098f6121227eece6ecfe342/status.svg)](https://joss.theoj.org/papers/1d6e062c3098f6121227eece6ecfe342)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1d6e062c3098f6121227eece6ecfe342"><img src="https://joss.theoj.org/papers/1d6e062c3098f6121227eece6ecfe342/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1d6e062c3098f6121227eece6ecfe342/status.svg)](https://joss.theoj.org/papers/1d6e062c3098f6121227eece6ecfe342)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ECSHackWeek/impedance.py" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ma-sadeghi & @EricaEgg, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ECSHackWeek/impedance.py">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mdmurbach) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ECSHackWeek/impedance.py">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mdmurbach) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ma-sadeghi, @EricaEgg it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0013-4686(93)85083-B is OK
- 10.1149/2.0711811jes is OK
- 10.21105/joss.01057 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s40964-018-0054-2 is OK
- 10.1016/j.electacta.2014.01.034 is OK
- 10.1149/2.1021802jes is OK
- 10.1149/2.1051908jes is OK
- 10.1016/S0167-2738(02)00185-6 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1016/0013-4686(95)00440-8 is OK
- 10.1016/S0378-7753(99)00351-1 is OK
- 10.1016/j.electacta.2005.02.148 is OK
- 10.1149/1.1836485 is OK
- 10.1016/S0013-4686(98)00138-8 is OK
- 10.1114/1.1366675 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02349/joss.02349/10.21105.joss.02349.pdf)

**Comment by mbobra** [comment]
Thank you so much for reviewing this submission, @ma-sadeghi and @EricaEgg! If you have any questions, please feel free to ask -- I'm always here to help ☀️

**Comment by EricaEgg** [comment]
@mbobra, I have a question regarding the COI guidelines. One of the authors (Brian Gerwe) and I are both PhD students within UW ChemE, therefore "employed at the same institution". However, we are NOT in the same lab group, so is that acceptable? Just want to make sure we are within the regulations. Thanks!

**Comment by arfon** [comment]
> @mbobra, I have a question regarding the COI guidelines. One of the authors (Brian Gerwe) and I are both PhD students within UW ChemE, therefore "employed at the same institution". However, we are NOT in the same lab group, so is that acceptable? Just want to make sure we are within the regulations. Thanks!

@EricaEgg - do you believe this will affect your ability to give an impartial review? If not, please proceed :-)

**Comment by EricaEgg** [comment]
> > @mbobra, I have a question regarding the COI guidelines. One of the authors (Brian Gerwe) and I are both PhD students within UW ChemE, therefore "employed at the same institution". However, we are NOT in the same lab group, so is that acceptable? Just want to make sure we are within the regulations. Thanks!
> 
> @EricaEgg - do you believe this will affect your ability to give an impartial review? If not, please proceed :-)

Thanks @arfon, it will not. I am happy to review.

**Comment by mbobra** [comment]
@ma-sadeghi and @EricaEgg Please let me know if you need any help with the review or have any questions!

**Comment by ma-sadeghi** [comment]
@mdmurbach From your repository, I see that there are 7 people who have contributed 1000+ lines of code, but I only see 4 people named as co-authors of the paper. Is that right?

**Comment by ma-sadeghi** [comment]
Hi @mbobra, I have a question for you: does the writing have to be strictly formal, or a few informalities here and there are acceptable?

**Comment by mdmurbach** [comment]
Hi @ma-sadeghi, thanks for your time with the review!

Yes, you're right. If you look at the timeline/content of the commits ([1](https://github.com/ECSHackWeek/impedance.py/commits?author=Jbonezzi22), [2](https://github.com/ECSHackWeek/impedance.py/commits?author=dacb), [3](https://github.com/ECSHackWeek/impedance.py/commits?author=pangq2)) for the 3 folks who are not listed as authors, they were in the initial setup of the repository structure during the Electrochemical Society (ECS) Hackweek and not in the actual content of the package being published. In this case, I don't think it makes sense to use LOC as a metric for contributions and the four authors were selected as they have all made substantial contributions to the work.

**Comment by ma-sadeghi** [comment]
@mdmurbach Sure, I completely understand. I just wanted to make sure this was not by mistake.

**Comment by ma-sadeghi** [comment]
> Hi @mbobra, I have a question for you: does the writing have to be strictly formal, or a few informalities here and there are acceptable?

Hi @mbobra, apart from this, it should be good to go. Well done @mdmurbach!

**Comment by EricaEgg** [comment]
@mdmurbach The README references an examples/ directory, but I do not see that on the master branch. Should users just reference the readthedocs examples instead? Just want to clarify. Thanks!

**Comment by mdmurbach** [comment]
Good catch @EricaEgg! Yes, the directory was moved into docs/source, so you can find them [here](https://github.com/ECSHackWeek/impedance.py/tree/master/docs/source/examples). These notebook files become the examples rendered in the documentation using [nbsphinx](https://nbsphinx.readthedocs.io/en/0.7.1/).

I will update the README to fix that discrepancy as well.

**Comment by EricaEgg** [comment]
Great work everyone! I just have a few documentation recommendations, but other than that I would say it is good to go!

Doc recs:
1) In the notebook, _fitting_example.ipynb_, part 4a, numpy is called without an import. Import line needs to be added in this block or earlier. 
2) In the notebook _plotting_example.ipynb_, part 3a, I am getting an error. There could be a bug in the function `circuit.plot`. (error attached as photo)
<img width="507" alt="Screen Shot 2020-07-17 at 2 30 21 PM" src="https://user-images.githubusercontent.com/46461002/87832095-0d004000-c83a-11ea-9e52-f70a309ca514.png">
If the above errors are due to errors I've done, might be useful to mention in documentation for users. 
Since these are small things, I went ahead and marked the corresponding boxes.

**Comment by EricaEgg** [comment]
> Great work everyone! I just have a few documentation recommendations, but other than that I would say it is good to go!
> 
> Doc recs:
> 
> 1. In the notebook, _fitting_example.ipynb_, part 4a, numpy is called without an import. Import line needs to be added in this block or earlier.
> 2. In the notebook _plotting_example.ipynb_, part 3a, I am getting an error. There could be a bug in the function `circuit.plot`. (error attached as photo)
> 
> <img alt="Screen Shot 2020-07-17 at 2 30 21 PM" width="507" src="https://user-images.githubusercontent.com/46461002/87832095-0d004000-c83a-11ea-9e52-f70a309ca514.png">
> 
> If the above errors are due to errors I've done, might be useful to mention in documentation for users. Since these are small things, I went ahead and marked the corresponding boxes.

Created an issue on target repo

**Comment by mdmurbach** [comment]
Awesome, thanks for taking the time to review @EricaEgg! I've added those changes as well as a few thoughts to the plotting error issue (I think it's potentially an adblocker or versioning issue rather than anything related to the package).

**Comment by EricaEgg** [comment]
> Awesome, thanks for taking the time to review @EricaEgg! I've added those changes as well as a few thoughts to the plotting error issue (I think it's potentially an adblocker or versioning issue rather than anything related to the package).

Thanks again @mdmurbach! Everything looks great from my end now. Good to go!

**Comment by mdmurbach** [comment]
Great! Thanks again for your reviews @EricaEgg and @ma-sadeghi! 😄

**Comment by mbobra** [comment]
Thank you for all your hard work @EricaEgg and @ma-sadeghi! I really appreciate it.

@mdmurbach We're almost there! Can you please cut a new release (it doesn't have to be a major release, something like v1.0.1 is fine), [archive your release on Zenodo](https://guides.github.com/activities/citable-code/) to obtain a DOI, and then put that DOI in your `README.md` file? After that I think we're done 🎉

**Comment by mdmurbach** [comment]
Linked with Zenodo, released v1.0.1, and added our shiny new DOI to [the README](https://github.com/ECSHackWeek/impedance.py/blob/master/README.md). Thanks for all of your time as well @mbobra! Please let me know if there is anything else you need

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02349/joss.02349/10.21105.joss.02349.pdf)

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0013-4686(93)85083-B is OK
- 10.1149/2.0711811jes is OK
- 10.21105/joss.01057 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s40964-018-0054-2 is OK
- 10.1016/j.electacta.2014.01.034 is OK
- 10.1149/2.1021802jes is OK
- 10.1149/2.1051908jes is OK
- 10.1016/S0167-2738(02)00185-6 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1016/0013-4686(95)00440-8 is OK
- 10.1016/S0378-7753(99)00351-1 is OK
- 10.1016/j.electacta.2005.02.148 is OK
- 10.1149/1.1836485 is OK
- 10.1016/S0013-4686(98)00138-8 is OK
- 10.1114/1.1366675 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.3955199 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3955199" target="_blank">10.5281/zenodo.3955199</a> is the archive.

**Comment by mbobra** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by mbobra** [comment]
@openjournals/joss-eics This paper is ready for final processing!

**Comment by BGerwe** [comment]
Thanks for all your hard work @mbobra @EricaEgg @ma-sadeghi!! 👏 💯

**Comment by mbobra** [comment]
@openjournals/joss-eics This paper is ready for final processing!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0013-4686(93)85083-B is OK
- 10.1149/2.0711811jes is OK
- 10.21105/joss.01057 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s40964-018-0054-2 is OK
- 10.1016/j.electacta.2014.01.034 is OK
- 10.1149/2.1021802jes is OK
- 10.1149/2.1051908jes is OK
- 10.1016/S0167-2738(02)00185-6 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1016/0013-4686(95)00440-8 is OK
- 10.1016/S0378-7753(99)00351-1 is OK
- 10.1016/j.electacta.2005.02.148 is OK
- 10.1149/1.1836485 is OK
- 10.1016/S0013-4686(98)00138-8 is OK
- 10.1114/1.1366675 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1620

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1620, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@mdmurbach - I notice the zenodo software author list has more people than the JOSS paper author list - is this intentional?  normally, we expect them to be the same, but this is not required.

**Comment by danielskatz** [comment]
@mdmurbach - can you also add countries to your affiliations in the author list?

**Comment by danielskatz** [comment]
@mdmurbach - in the paper:
- The journal for Hunter should be Computing in Science & Engineering (the & is missing)
- for Rodrigues et al. Should A.C. be in caps in the title?

**Comment by mdmurbach** [comment]
@danielskatz great catch on these. Thanks! 😄 

- I've added the `&` to the Hunter paper
- a.c. is not capitalized in the original [Rodrigues reference](https://www.sciencedirect.com/science/article/abs/pii/S0378775399003511?via%3Dihub), so I left that as is
- added the countries to the author list
- Fixed the Zenodo affiliations to match

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0013-4686(93)85083-B is OK
- 10.1149/2.0711811jes is OK
- 10.21105/joss.01057 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1007/s40964-018-0054-2 is OK
- 10.1016/j.electacta.2014.01.034 is OK
- 10.1149/2.1021802jes is OK
- 10.1149/2.1051908jes is OK
- 10.1016/S0167-2738(02)00185-6 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1016/0013-4686(95)00440-8 is OK
- 10.1016/S0378-7753(99)00351-1 is OK
- 10.1016/j.electacta.2005.02.148 is OK
- 10.1149/1.1836485 is OK
- 10.1016/S0013-4686(98)00138-8 is OK
- 10.1114/1.1366675 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1622

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1622, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1290427908738166785) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1623
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02349](https://doi.org/10.21105/joss.02349)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @ma-sadeghi, @EricaEgg for reviewing, and @mbobra for editing!

Congratulations to @mdmurbach (Matthew D. Murbach) and co-authors!!

(I will close this issue once the PDF appears, which has been taking a little longer than normal lately)

**Comment by mdmurbach** [comment]
Wonderful! Big thanks again for all of your time, @ma-sadeghi, @EricaEgg, @mbobra and @danielskatz! This was an awesome review process all around :smile: 

:confetti_ball:  congrats @BGerwe, @nealde, and @lktsui!! :tada:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02349/status.svg)](https://doi.org/10.21105/joss.02349)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02349">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02349/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02349/status.svg
   :target: https://doi.org/10.21105/joss.02349
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02349/status.svg)](https://doi.org/10.21105/joss.02349)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
