### ISSUE TITLE
[PRE REVIEW]: biorbd: A C++, Python and MATLAB library to analyze and simulate the human body biomechanics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2350]
**Submitting author:** @pariterre (<a href="http://orcid.org/0000-0002-5031-1048">Benjamin Michaud</a>)
**Repository:** <a href="https://github.com/pyomeca/biorbd" target ="_blank">https://github.com/pyomeca/biorbd</a>
**Version:** 1.3.2
**Editor:** @trallard
**Reviewers:** @trallard, @abhishektha
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pariterre. **Currently, there isn't an JOSS editor assigned** to your paper.

@pariterre if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/S0021-9290(00)00155-X is OK
- 10.1007/s11044-017-9587-2 is OK
- 10.1016/j.simpat.2006.09.001 is OK
- 10.1007/978-3-540-36119-0_4 is OK
- 10.1109/ROBOT.2000.844153 is OK
- 10.1007/s10514-016-9574-0 is OK
- 10.1007/s00530-019-00633-9 is OK
- 10.1115/1.4029304 is OK
- 10.1016/j.jbiomech.2012.05.042 is OK
- 10.1016/j.jbiomech.2016.03.052 is OK
- 10.1007/s12206-018-1154-0 is OK
- 10.1145/1576246.1531386 is OK
- 10.1016/S0021-9290(03)00152-0 is OK
- 10.1080/00140139.2019.1571245 is OK
- 10.3389/fnbot.2019.00048 is OK
- 10.1371/journal.pcbi.1006223 is OK
- 10.1115/1.1531112 is OK
- 10.1016/j.jbiomech.2019.01.045 is OK
- 10.3389/fpsyg.2020.01159 is OK
- 10.1007/s10107-004-0559-y is OK

MISSING DOIs

- https://doi.org/10.1007/s12532-018-0139-4 may be missing for title: CasADi – A Software Framework for Nonlinear Optimization and Optimal Control
- https://doi.org/10.1080/10255842.2010.491958 may be missing for title: Estimation of the 3D Kinematics in Kayak Using an Extended Kalman Filter Algorithm: A Pilot Study
- https://doi.org/10.1201/9781315220352 may be missing for title: Robotics and Automation Handbook

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02350/joss.02350/10.21105.joss.02350.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@trallard can you handle this one? If not I can.

**Comment by Kevin-Mattheus-Moerman** [comment]
@pariterre we are currently looking for an editor for this submission. It may take us a bit longer than usual (see post referred to above). 
In the mean time you can work on refining your paper. In particular fix those missing DOI's detected here :point_up:.  You can run `@whedon generate pdf` to update the paper and use `@whedon check references` to check the references.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @trallard as editor

**Comment by whedon** [comment]
@trallard has been invited to edit this submission.

**Comment by trallard** [comment]
Hello, and thanks for your patience. I will be editing your submission. 

@pariterre do you have any reviewers already in mind? If not, please check our list of available reviewers <https://bit.ly/joss-reviewers> and list some names here (without tagging them with @)

**Comment by danielskatz** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by pariterre** [comment]
Dear @trallard 
Thanks for accepting being editor on my submission, this is highly appreciated!

I've had a look at the list you referred and I got 4 names that seems to fit the profile of my submission:
CELavecchia
nnadeau
abhishektha
trallard

Is this sufficient? 
Thanks!

**Comment by trallard** [comment]
Dear potential reviewers, 

On behalf of JOSS I would like to invite you to review the following submission:

**Title**: biorbd: A C++, Python and MATLAB library to analyze and simulate the human body biomechanics
**Repository**: https://github.com/pyomeca/biorbd
**Submitting author**: @pariterre 
**Article**: <https://github.com/openjournals/joss-papers/blob/joss.02350/joss.02350/10.21105.joss.02350.pdf>

@CELavecchia are you able and willing to take this review?
@nnadeau are you able and willing to take this review?
@abhishektha are you able and willing to take this review?


Once we have at least 2 reviewers we can proceed.

FYI our reviewing guidelines can be found [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) in case you need too have a look

**Comment by trallard** [comment]
@whedon assign @trallard as reviewer

**Comment by whedon** [comment]
OK, @trallard is now a reviewer

**Comment by abhishektha** [comment]
Yes I'm able to review!

**Comment by trallard** [comment]
Thanks @abhishektha!

**Comment by trallard** [comment]
@whedon add @abhishektha as reviewer

**Comment by whedon** [comment]
OK, @abhishektha is now a reviewer

**Comment by trallard** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2562.
