### ISSUE TITLE
[REVIEW]: dms-view: Interactive visualization tool for deep mutational scanning data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2353]
**Submitting author:** @skhilton (<a href="http://orcid.org/0000-0001-9278-3644">Sarah K. Hilton</a>)
**Repository:** <a href="https://github.com/dms-view/dms-view.github.io" target ="_blank">https://github.com/dms-view/dms-view.github.io</a>
**Version:** v1.1.0
**Editor:** @csoneson
**Reviewer:** @afrubin, @andrefaure, @thorvere
**Archive:** <a href="https://doi.org/10.5281/zenodo.3986155" target="_blank">10.5281/zenodo.3986155</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/264a4369f33d68a818922a9cccf66a7c/status.svg)](https://joss.theoj.org/papers/264a4369f33d68a818922a9cccf66a7c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/264a4369f33d68a818922a9cccf66a7c"><img src="https://joss.theoj.org/papers/264a4369f33d68a818922a9cccf66a7c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/264a4369f33d68a818922a9cccf66a7c/status.svg)](https://joss.theoj.org/papers/264a4369f33d68a818922a9cccf66a7c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dms-view/dms-view.github.io" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@afrubin & @andrefaure & @thorvere, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dms-view/dms-view.github.io">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@skhilton) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dms-view/dms-view.github.io">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@skhilton) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dms-view/dms-view.github.io">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@skhilton) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @afrubin, @andrefaure, @thorvere it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/j.celrep.2015.06.005 may be missing for title: Identification of hemagglutinin residues responsible for H3N2 antigenic drift during the 2014–2015 influenza season
- https://doi.org/10.1038/nmeth.3027 may be missing for title: Deep mutational scanning: a new style of protein science.
- https://doi.org/10.1186/s13073-019-0698-7 may be missing for title: Recommendations for the collection and use of multiplexed functional data for clinical variant interpretation
- https://doi.org/10.1186/s12859-015-0590-4 may be missing for title: Software for the analysis and visualization of deep mutational scanning data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02353/joss.02353/10.21105.joss.02353.pdf)

**Comment by csoneson** [comment]
@afrubin, @andrefaure, @thorvere - thanks for accepting to review this submission! This issue is where the review happens. You will find your respective checklist, and some additional instructions, in the post above. Don't hesitate to ping me if you have any questions!

**Comment by csoneson** [comment]
@skhilton - I'll move my comment from the pre-review issue here so it doesn't get lost: when you get a chance, please add DOIs to the references in your paper (you can then ask whedon to generate a new article proof with `@whedon generate pdf`)

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02353/joss.02353/10.21105.joss.02353.pdf)

**Comment by csoneson** [comment]
Whedon needs its instructions in a separate comment :)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/j.celrep.2015.06.005 may be missing for title: Identification of hemagglutinin residues responsible for H3N2 antigenic drift during the 2014–2015 influenza season
- https://doi.org/10.1038/nmeth.3027 may be missing for title: Deep mutational scanning: a new style of protein science.
- https://doi.org/10.1186/s13073-019-0698-7 may be missing for title: Recommendations for the collection and use of multiplexed functional data for clinical variant interpretation
- https://doi.org/10.1186/s12859-015-0590-4 may be missing for title: Software for the analysis and visualization of deep mutational scanning data

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
Hm, it seems that the link to the repository (which was changed in the pre-review issue) did not follow over to the review issue.

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.celrep.2015.06.005 is OK
- 10.1038/nmeth.3027 is OK
- 10.1186/s13059-019-1845-6 is OK
- 10.7554/eLife.49324 is OK
- 10.1016/j.ajhg.2017.07.014 is OK
- 10.1016/j.sbi.2016.11.001 is OK
- 10.1186/s13073-019-0698-7 is OK
- 10.1186/s13059-017-1272-5 is OK
- 10.1186/s12859-015-0590-4 is OK
- 10.1038/nrg.2015.18 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02353/joss.02353/10.21105.joss.02353.pdf)

**Comment by danielskatz** [comment]
> Hm, it seems that the link to the repository (which was changed in the pre-review issue) did not follow over to the review issue.

Is this ok now?

**Comment by csoneson** [comment]
@danielskatz - I manually changed the link in the first issue above.

**Comment by andrefaure** [comment]
@csoneson  the target repository (https://github.com/jbloomlab/dms-view-ms) is not where "the source code for this software" is available as indicated in the checklist above - not sure if this is intended...

**Comment by csoneson** [comment]
Thanks @andrefaure, should be fixed now. I forgot to update the link in the checklist when I updated it in the summary above.

**Comment by csoneson** [comment]
👋 Hi all - just a quick check to see how the reviews are coming along. I see that there are some issues opened and being worked on in the source repository - that's great! Just a reminder to also update the checklists in the first post in this issue - that helps us keep track of things. It can also be helpful to link to this issue in the issues that you open in the target repository, in that way they will show up here as well. Thanks!

**Comment by andrefaure** [comment]
Ok I have added the JOSS review issues 6-9 linked above in the target repository. In summary, dms-view is a useful and thoughtfully designed piece of software. The documentation, including case studies and tutorials, is helpful and detailed. I have completed the review checklist and the only point currently unchecked is "State of the field", although as mentioned in JOSS review issue #7 I consider this a minor point i.e. not an acceptance blocker; @csoneson shall I just go ahead and check this one too?

**Comment by csoneson** [comment]
Thanks @andrefaure! I would suggest to leave it unchecked for now - I agree that it would be good to have a short statement on this in the paper.

**Comment by afrubin** [comment]
This is a really nice piece of software that will be very useful for the DMS community. I have raised a few issues in the repository (links below), and will probably have a bit more to say once I finish putting a MaveDB dataset into dms-view using the provided instructions.

https://github.com/dms-view/dms-view.github.io/issues/157
https://github.com/dms-view/dms-view.github.io/issues/158
https://github.com/dms-view/dms-view.github.io/issues/159
https://github.com/dms-view/dms-view.github.io/issues/160

**Comment by csoneson** [comment]
👋 Just checking in again to see where we're at. 
@thorvere - could you give an update on the status of your review (I see some opened issues in the software repository, but no checked boxes in the checklist above)?
@skhilton - it looks like you've gotten some good feedback (and already worked through some of it). Let us know if you have questions, and when you feel like you're ready for the reviewers to have a second look.
Thanks everyone!

**Comment by csoneson** [comment]
@thorvere - could you give an update on the status of your review (I see some opened issues in the software repository, but no checked boxes in the checklist above)? Thanks!

**Comment by thorvere** [comment]
dms-view is a well-designed visualization tool allowing to interactively analyze DMS data in the context of protein structures.  Upon addressing some minor modifications for which I opened issues, I think it is a very useful contribution for the scientific community. Thus, I can recommend it for publication.

**Comment by csoneson** [comment]
Thanks @thorvere! 

@afrubin - could you update us on the status of your review? 

@andrefaure - I think the authors added a comment on the state of the field. Could you see if that satisfies your concerns above?

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2353 with the following error: 

 Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Error producing PDF.
! Unable to load picture or PDF file '/tmp/tex2pdf.-3e75ed72c64ab793/65f7baa306
7c14aacf360e65551ad78a3784b8fe.pdf'.
<to be read again> 
                   }
l.502 ...baa3067c14aacf360e65551ad78a3784b8fe.pdf}

Looks like we failed to compile the PDF

**Comment by csoneson** [comment]
@openjournals/dev - any idea what could cause this compilation issue? 🤔

**Comment by xuanxu** [comment]
It seems there's a problem rendering the `dms.pdf` file. 

https://github.com/dms-view/dms-view.github.io/blob/master/paper/dms.pdf

Maybe it's not a well formatted pdf?

**Comment by csoneson** [comment]
@skhilton - could you check this? 

> It seems there's a problem rendering the dms.pdf file.
https://github.com/dms-view/dms-view.github.io/blob/master/paper/dms.pdf
Maybe it's not a well formatted pdf?

**Comment by skhilton** [comment]
@csoneson: This should be fixed now! One of the pdfs was not formatted correctly. The version on the master branch complies nicely using https://whedon.theoj.org/ for me. Let me know if there is trouble on your end

**Comment by skhilton** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02353/joss.02353/10.21105.joss.02353.pdf)

**Comment by csoneson** [comment]
Looks like it worked! 😃

**Comment by andrefaure** [comment]
> @andrefaure - I think the authors added a comment on the state of the field. Could you see if that satisfies your concerns above?

Yes thanks - all my concerns are now satisfied and I have checked the corresponding checkbox above.

**Comment by skhilton** [comment]
@csoneson: @huddlej and I finished addressing this round of reviewer comments. We are happy to go back and re-open discussions/issues where appropriate.

**Comment by afrubin** [comment]
@csoneson Looks great to me!

@skhilton I did find https://github.com/dms-view/dms-view.github.io/issues/179 when was checking over the changes, but that should be easy to handle.

The manuscript cites MaveVis using its Zenodo DOI, but as it was initially described in Esposito et al. (the MaveDB paper) you could use that citation instead if you prefer.

**Comment by csoneson** [comment]
Thanks @afrubin!

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02353/joss.02353/10.21105.joss.02353.pdf)

**Comment by csoneson** [comment]
👋 @skhilton - I submitted a pull request with a couple of minor fixes to the text. Please check and merge if it looks ok. For consistency, could you represent the country in all affiliations in the same way (now there's USA, United States and United States of America 😃)? Also, it would be good to indicate somewhere what the asterisk means.  

The next steps are the following: 
- [ ] Create a tagged release of the software, and report back the version tag here
- [ ] Archive the release in Zenodo
- [ ] Check that the Zenodo archive has the same title and author list as the paper. 
- [ ] Report back the Zenodo DOI here

**Comment by huddlej** [comment]
@csoneson, @skhilton and I intended for the asterisks to indicate shared co-first authorship. Is there a more formal way to represent this authorship status for JOSS, or is it sufficient to add a legend below the authorship section describing what the asterisk means? Thank you!

**Comment by csoneson** [comment]
@huddlej - the way we often recommend for indicating shared co-first authorship is to include a footnote, e.g., as done here: https://joss.theoj.org/papers/10.21105/joss.02145

**Comment by skhilton** [comment]
@csoneson: The new tagged version of the software is v1.1.0 (https://github.com/dms-view/dms-view.github.io/releases/tag/v1.1.0) and the zenodo doi is 10.5281/zenodo.3986155. @huddlej updated the affiliations. Let us know if there are any issues!

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02353/joss.02353/10.21105.joss.02353.pdf)

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.3986155 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3986155" target="_blank">10.5281/zenodo.3986155</a> is the archive.

**Comment by csoneson** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by csoneson** [comment]
@skhilton, @huddlej - looks good! I'll hand over to an AEiC for the final steps.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.celrep.2015.06.005 is OK
- 10.1038/nmeth.3027 is OK
- 10.1186/s13059-019-1845-6 is OK
- 10.7554/eLife.49324 is OK
- 10.1016/j.ajhg.2017.07.014 is OK
- 10.1016/j.sbi.2016.11.001 is OK
- 10.1186/s13073-019-0698-7 is OK
- 10.1186/s13059-017-1272-5 is OK
- 10.1186/s12859-015-0590-4 is OK
- 10.1038/nrg.2015.18 is OK
- 10.5281/zenodo.3432882 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1641

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1641, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1295238290866667520) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1643
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02353](https://doi.org/10.21105/joss.02353)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @skhilton on your article's publication in JOSS!

Many thanks to @afrubin, @andrefaure, and @thorvere for reviewing this, and @csoneson for editing it.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02353/status.svg)](https://doi.org/10.21105/joss.02353)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02353">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02353/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02353/status.svg
   :target: https://doi.org/10.21105/joss.02353
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02353/status.svg)](https://doi.org/10.21105/joss.02353)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by huddlej** [comment]
@csoneson Thank you for all of your help with this review process! I just noticed a minor issue in the author list on the right-hand navigation of the paper's page (https://joss.theoj.org/papers/10.21105/joss.02353) where my name is listed as "John Huddleston$". I think this has to do with the Latex code I added to place an asterisk next to my name.

Is it possible to change this to remove the "$" from the end somehow? Should I open a separate issue for this? Thanks again!

**Comment by kyleniemeyer** [comment]
@openjournals/dev can you help @huddlej update the paper?

**Comment by skhilton** [comment]
@csoneson, @kyleniemeyer: Could we also change the link software repository link from https://github.com/jbloomlab/dms-view-ms to https://github.com/dms-view/dms-view.github.io/. During the review process we moved the manuscript to the main software repository. Thanks!
