### ISSUE TITLE
[PRE REVIEW]: DearScholar: A mobile application to conduct qualitative and quantitative diary research

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2354]
**Submitting author:** @pmkruyen (<a href="http://orcid.org/0000-0003-0109-1744">Peter Kruyen</a>)
**Repository:** <a href="https://github.com/pmkruyen/dearscholar" target ="_blank">https://github.com/pmkruyen/dearscholar</a>
**Version:** 1.48
**Editor:** @cMadan
**Reviewers:** @gcdeshpande, @kinow
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pmkruyen. **Currently, there isn't an JOSS editor assigned** to your paper.

@pmkruyen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02354/joss.02354/10.21105.joss.02354.pdf)

**Comment by arfon** [comment]
👋 @pmkruyen - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by pmkruyen** [comment]
Thanks @arfon for your message. Completely understand. Your bot Whedon is asking me to suggest reviews in the first message above, should I do this or wait till further notice? 

Regards,
Peter

**Comment by arfon** [comment]
> Thanks @arfon for your message. Completely understand. Your bot Whedon is asking me to suggest reviews in the first message above, should I do this or wait till further notice?

Feel free to suggest some reviewers now (please avoid mentioning them directly to avoid unnecessary GitHub notifications for folks) which will help when an editor is assigned.

**Comment by pmkruyen** [comment]
My suggestions for reviewers based on their expertise:

- gcdeshpande (mobile apps)
- olade014 (android)
- alletsee (survey research and longitudinal data collection)
- darthpathos (survey research and longitudinal data collection)
- andytwoods  (javascript, psychology, online research)

**Comment by arfon** [comment]
@whedon check repository

**Comment by kthyng** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=16.09 s (92.7 files/s, 37931.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                     650          24592          21278         185751
C                                4          15087          70293         140007
CSS                             91             54           1210          53217
Markdown                       143           6762              0          20157
LESS                           255            453            553          19910
JSON                            91              0              0          13392
TypeScript                     107            541           2499           4764
Java                            24            861            829           4738
Objective C                     15            990            467           3934
C/C++ Header                    22            504          10073           1994
XML                             32            177            214           1879
HTML                            12             95             44            564
Sass                            14             18             12            556
CoffeeScript                     2            110             61            507
C#                               3             67             63            305
C++                              4             32              2            127
Swift                            1             22              1            120
TeX                              1             10              0            110
DOS Batch                        3              3              0             75
YAML                             8              6              0             61
PowerShell                       1              8             20             39
Bourne Shell                     1             10             23             33
make                             1             11              3             22
Gradle                           1              4              8             18
Ruby                             2              4              1             16
INI                              1              0              0             13
SVG                              2              0              0              6
-------------------------------------------------------------------------------
SUM:                          1491          50421         107654         452315
-------------------------------------------------------------------------------

**Comment by arfon** [comment]
@pmkruyen - @kthyng and I are trying to get an idea of the code contribution here. Could you point to the main areas of the repository where you've written new code for this project? It looks like a lot of the code in here comes from the framework you've been using.

**Comment by pmkruyen** [comment]
@arfon @kthyng thanks for checking... I have build DearScholar using Framework7; dearscholar.js--the heart of the project and a lot of work--; all the html-files plus and dearscholar.css are mine (code solely written by me); also see the table at the bottom of the README file. Best Peter

**Comment by pmkruyen** [comment]
@arfon @kthyng thanks for checking... I have build DearScholar using Framework7; dearscholar.js--the heart of the project and a lot of work--; plus all the html-files and dearscholar.css are mine (code solely written by me); also see the table at the bottom of the README file. Best Peter

**Comment by pmkruyen** [comment]
@arfon @kthyng thanks for checking... I have built DearScholar using Framework7 indeed; dearscholar.js--the heart of the project and a lot of work--; plus all the html-files and dearscholar.css are mine (code solely written by me); also see the table at the bottom of the README file. Best Peter

**Comment by pmkruyen** [comment]
@arfon and @kthyng To follow up, I just realized, I included the complete codebase of Framework7 in my repro as matter of convenience, but (obviously) not everything is needed for DearScholar to work.

**Comment by danielskatz** [comment]
👋 @cMadan - you were suggested as the editor for this submission - would you be willing to do so?

**Comment by danielskatz** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by cMadan** [comment]
@whedon set @cMadan as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by danielskatz** [comment]
thanks!

**Comment by cMadan** [comment]
@pmkruyen, I've looked over your submission and have three initial comments:

1. Your license has some additional text at the top, in addition to a standard OSI license. Publishing in JOSS requires that you *only* use a standard OSI-compliant license with no modifications.

1. I would appreciate if you could add a few screenshots (just one picture concatenating a screenshots from a few different parts of the app). Since it's very front-end oriented in that research participants would be using it, it would be helpful to see how it looks 'out of the box', though I do understand that it's just a bit of HTML code for another researcher to change this.

1. It would be helpful to provide the MySQL database initialisation code for setting up the databases for the first time. I have a feeling that with 10 tables, someone could easily make a typo, or set a column to the wrong data format, so it would be great to provide the syntax for automating that step.

**Comment by pmkruyen** [comment]
@cMadan thanks for being the editor of my submission and your initial comments:

1. I deleted the modifications. My university wants me to include those lines; I now included them in the README file (under copyright). Hope that this is acceptable. Or should these lines be included in the separate files?

2. Screenshots were included in the App Store and Google Play but not on Github. With some trial and error, I managed to include a few screenshots in the README file too.

3. Aha. I added a file containing the MySQL code for the database and tables, plus the user rights assignment settings (see the mysql text file). 

Best, 
Peter

**Comment by cMadan** [comment]
@pmkruyen, thanks for making those changes.

1. I think that should be fine now. JOSS submissions need to be released under an (unmodified) OSI license, but it's fine to have an additional copyright statement. (@openjournals/joss-eics, can you confirm this text is suitable?)

2. Thanks for including the screenshots in the README, I think it makes the app functions much clearer for new users.

3. I also appreciate you adding th MySQL initialisation code.

Do you have any additional suggestions for reviewers (see the initial comment in this issue for some guidance) ?

**Comment by pmkruyen** [comment]
Hi @cMadan, thanks for your reply.

1. To be sure: I searched for [at]openjournals/joss-eics, because I thought I had to check something. On rereading your response, I believe you would like the joss team to confirm your response? The link to [at]openjournals/joss-eics throws a 400 error however.

2. :)

3. Triggered by your MySQL suggestion, I'm now working on a example php script that can researchers use as template to let DearScholar communicate with the server (but there are some delays here because Phonegap is no longer working for iOS production and, consequently, I need invest some time to set up the building tools locally).

With regard to suggestions for reviewers, do you would me to suggest additional reviewers besides the potential reviewers I suggested above?

> gcdeshpande (mobile apps)
> olade014 (android)
> alletsee (survey research and longitudinal data collection)
> darthpathos (survey research and longitudinal data collection)
> andytwoods (javascript, psychology, online research)

Best,
Peter

**Comment by danielskatz** [comment]
> I think that should be fine now. JOSS submissions need to be released under an (unmodified) OSI license, but it's fine to have an additional copyright statement. (@openjournals/joss-eics, can you confirm this text is suitable?)

It seems fine

**Comment by cMadan** [comment]
@pmkruyen, sorry, I hadn't noticed that you had already suggested reviewers earlier on!

**Comment by cMadan** [comment]
@gcdeshpande @alletsee @andytwoods, would you be available and interested in reviewing this submission? Thanks for your consideration!

**Comment by gcdeshpande** [comment]
Yes


Thanks and Regards
Gajendra C. Deshpande
Assistant Professor, CSE@KLS.GIT
Belgaum - 590008
Karnataka, INDIA

Blog: http://gajendramoksha.wordpress.com
Website: http://sites.google.com/a/git.edu/gcd
Facebook: https://www.facebook.com/gcdeshpande


[http://csta.acm.org/Membership/sub/badge.jpg]


________________________________

**Comment by alletsee** [comment]
Thanks for reaching out. Before deciding if I accept to review, I think it makes sense to discuss expectations regarding the programming languages. I have minimal experience with JavaScript and no experience with mobile app development. However, I think that my knowledge about survey research would be good enough to review the paper itself.

In essence, I'm not sure if it makes sense to review in a situation where my ability to review the software contribution is very limited. Is there a guideline / recommendation from the JOSS team on this, @cMadan ?

**Comment by andytwoods** [comment]
I am sorry. Afraid I can't review right now, due to childcare issues (7 and 3 year old) and full time jobs. Life's not fun at the moment. Apologies.

**Comment by gcdeshpande** [comment]
@cMadan request you to kindly share the evaluation criteria and process.

**Comment by kyleniemeyer** [comment]
Hello @gcdeshpande, here is a link to our review criteria: https://joss.readthedocs.io/en/latest/review_criteria.html

@alletsee Thanks for responding—if you are not really able to review the software, then we might prefer to find alternate reviewers (JOSS papers are fairly short). However, if you feel comfortable at least reviewing the functionality and documentation of the software, bringing your domain expertise into account, then that would still be helpful for us.

**Comment by kyleniemeyer** [comment]
@whedon add @gcdeshpande as reviewer

**Comment by whedon** [comment]
OK, @gcdeshpande is now a reviewer

**Comment by pmkruyen** [comment]
Hi @gcdeshpande, thank you for your willingness to review my submission. 

For your information, inspired by @cMadan 's initial suggestions, I took the opportunity-while my submission still being in 'pre-review'-to write a sample php script to let DearScholar communicate with the server (`dearscholar.php`). Also, I wrote a php file to set up a sample study (`samplestudy.php`). Both files are in the root of the repro. Last, I fixed some minor bugs caused by changes in the compilation process for iOS. If you need more information to get DearScholar running, let me know.

Best,
Peter

**Comment by cMadan** [comment]
@sarathsp06 @kinow@mbod, would you be available and interested in reviewing this submission? Thanks for your consideration!

@pmkruyen @gcdeshpande, we typically require two reviewers and are currently one short... so hopefully we can get one more person to agree and then will move on to the actual review.

**Comment by kinow** [comment]
@cMadan hello. Finished reading the comments in this issue, and also the link to the review criteria above, as well as having a quick look at the paper PDF.

I'd be happy to review it. It would be my first review for JOSS, so let me know if there's anything else I need to read besides the review criteria (even though that document seems to cover most of what I could imagine for reviewing a paper about a software).

I used Cordova before too (~4 years ago I think?), and at work I have a co-worker actively maintaining a phonegap/ionic app. So I should be able to review the project code, confirm it works, and finally review the paper as well.

Thanks!
Bruno

**Comment by pmkruyen** [comment]
Thank you @kinow to serve as a reviewer for my submission.

Best,
Peter

**Comment by kinow** [comment]
Just waiting for confirmation before starting review :+1:

**Comment by arfon** [comment]
:wave: I expect @cMadan will be back here shortly to set up the review. Thanks for your patience all :-)

**Comment by cMadan** [comment]
@whedon add @kinow as reviewer

**Comment by whedon** [comment]
OK, @kinow is now a reviewer

**Comment by cMadan** [comment]
@pmkruyen @kinow @gcdeshpande, thank you for your patience. I think we're all set to start the review, so I will set that up and we can begin the actual review process.

@kinow, thanks for mentioning this is your first JOSS review, feel free to ask me questions in the review issue if you're not sure about something!

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2506.

**Comment by pmkruyen** [comment]
Hi @cMadan, haha, I just wanted to ask you if you could give me (us) an update on the review process, but I see that you are working on it :) Thanks!
