### ISSUE TITLE
[PRE REVIEW]: set6: R6 Mathematical Sets Interface

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2355]
**Submitting author:** @RaphaelS1 (<a href="http://orcid.org/0000-0001-9225-4654">Raphael E. B. Sonabend</a>)
**Repository:** <a href="https://github.com/xoopR/set6" target ="_blank">https://github.com/xoopR/set6</a>
**Version:** v0.1.4
**Editor:** @dpsanders
**Reviewers:** @dmbates, davidjohannesmeyer, @davidjohannesmeyer
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @RaphaelS1. **Currently, there isn't an JOSS editor assigned** to your paper.

@RaphaelS1 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.68 s (135.9 files/s, 11219.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               80            620           2192           3700
Markdown                         5             72              0            304
YAML                             3             31             47            184
JSON                             1              0              0            149
TeX                              1             13              0            101
C++                              2             12              6             78
Rmd                              1             40             84             44
-------------------------------------------------------------------------------
SUM:                            93            788           2329           4560
-------------------------------------------------------------------------------


Statistical information for the repository '2355' was gathered on 2020/06/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Raphael                          2            98              2          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Raphael Sonabend             96          100.0          0.0                6.25
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.2647458 is OK
- 10.1093/carcin/bgs084 is OK
- 10.18637/jss.v031.i02 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02355/joss.02355/10.21105.joss.02355.pdf)

**Comment by arfon** [comment]
👋 @RaphaelS1 - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by RaphaelS1** [comment]
Thanks for the update!

**Comment by dpsanders** [comment]
@arfon I volunteer to edit this submission.

**Comment by dpsanders** [comment]
Guess that message should have been directed to @Kevin-Mattheus-Moerman, sorry.

**Comment by arfon** [comment]
@whedon assign @dpsanders as editor

**Comment by whedon** [comment]
OK, the editor is @dpsanders

**Comment by arfon** [comment]
Thanks @dpsanders - you can always grab the paper yourself with `@whedon assign me as editor`

**Comment by dpsanders** [comment]
👋 Hi @RaphaelS1 -- thanks for submitting to JOSS!

Looking at the paper, I have a couple of questions and suggestions: 

- Could you please add a couple of usage examples
- Describe in more detail how your package compares to the `sets` package
- What do you mean by the "symbolic representation" and "lazy evaluation" in this context? Maybe you could give examples.
- Please add the title, date and journal for the Meyer-Hornik paper in the bibliography.
- How does this compare to similar packages in other computer languages?

Thanks!

**Comment by dpsanders** [comment]
Also, could you please comment about the necessity for the C++ code in the submission?

**Comment by RaphaelS1** [comment]
Hi @dpsanders thanks for the speedy feedback! I've added to the paper as suggested and pushed the latest copy to the same repo as before (I have assumed the questions were intended to be answered in the paper and not here but let me know otherwise).

**Comment by dpsanders** [comment]
Thanks @RaphaelS1. You can make sure that the latest version is correct with the following command

**Comment by dpsanders** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02355/joss.02355/10.21105.joss.02355.pdf)

**Comment by RaphaelS1** [comment]
Thanks @dpsanders, that's indeed the latest version

**Comment by dpsanders** [comment]
Thanks @RaphaelS1, the new version of the paper nicely explains the scope and use of the package. BTW, some more possibly relevant Julia packages include LazySets.jl, DomainSets.jl and SpecialSets.jl. But for example your lazy power set functionality looks pretty unique to me.

**Comment by dpsanders** [comment]
Could you please suggest possible reviewers from the list mentioned in the first post above (without tagging them with `@`).

**Comment by RaphaelS1** [comment]
@dpsanders suggestions as follows: jkanche, tylerwmarrs, kinow, billchenxi, mcavs, jaeyk

**Comment by dpsanders** [comment]
:wave: Hi @mcavs, @chlalanne and @drvinceknight! Would any of you be available and willing to review this submission to JOSS? Thanks!

**Comment by even4void** [comment]
@dpsanders Unfortunately I don't really feel qualified to review this article. Maybe Dirk Eddelbuettel would be a better fit given the scope of the paper?

**Comment by dpsanders** [comment]
@even4void OK, thanks for the suggestion!

**Comment by dpsanders** [comment]
👋 @eduPH, @mdavezac and @adibender: Would any of you be available and able to review this submission to JOSS? Thanks!

**Comment by mdavezac** [comment]
Apologies, I'm currently involved in another JOSS review and in crunch time in other things.

**Comment by RaphaelS1** [comment]
@adibender and I are collaborators on other projects so probably not a fair reviewer here unfortunately

**Comment by EduPH** [comment]
I am sorry but Im really busy these days.

**Comment by dpsanders** [comment]
@whedon add @dmbates as reviewer

**Comment by whedon** [comment]
OK, @dmbates is now a reviewer

**Comment by dpsanders** [comment]
👋 @labarba. Yes this submission has proved challenging! I'm waiting on responses from more people I've reached out to by email.

**Comment by dpsanders** [comment]
@whedon add davidjohannesmeyer as reviewer

**Comment by whedon** [comment]
OK, davidjohannesmeyer is now a reviewer

**Comment by dpsanders** [comment]
@whedon add @davidjohannesmeyer as reviewer

**Comment by whedon** [comment]
OK, @davidjohannesmeyer is now a reviewer

**Comment by dpsanders** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2598.
