### ISSUE TITLE
[PRE REVIEW]: textnets: A Python package for text analysis with networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2356]
**Submitting author:** @jboynyc (<a href="http://orcid.org/0000-0003-2118-4702">John Boy</a>)
**Repository:** <a href="https://github.com/jboynyc/textnets" target ="_blank">https://github.com/jboynyc/textnets</a>
**Version:** v.0.4.2
**Editor:** @gkthiruvathukal
**Reviewers:** @sara-02, @tresoldi
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jboynyc. **Currently, there isn't an JOSS editor assigned** to your paper.

@jboynyc if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.36 s (101.5 files/s, 28509.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              3              0              0           7847
Python                          10            249            447            786
reStructuredText                13            224            144            355
make                             2             26              6             79
TeX                              1              0              0             68
YAML                             4              4              5             43
DOS Batch                        1              8              1             27
Nix                              1              3              0             27
INI                              1              3              3             19
Markdown                         1              4              0             11
-------------------------------------------------------------------------------
SUM:                            37            521            606           9262
-------------------------------------------------------------------------------


Statistical information for the repository '2356' was gathered on 2020/06/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
John Boy                         5           810            173           23.77
John D. Boy                    148          1870           1011           69.67
jdboy                           27           129            142            6.55

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
John Boy                    222           27.4          8.6               33.78
John D. Boy                1244           66.5          0.3                9.89
jdboy                        16           12.4         11.5                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2356 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02356/joss.02356/10.21105.joss.02356.pdf)

**Comment by arfon** [comment]
👋 @jboynyc - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by jboynyc** [comment]
Sounds good, thanks! Possible reviewers include contributors to [cbail/textnets](https://github.com/cbail/textnets), alexhanna, cmaimone, tresoldi, and nniiicc. I'll update this comment if I find any more.

**Comment by arfon** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
Hi @jboynyc, can you please suggest some potential reviewers from the list of people (see top of this thread)? Thanks.

**Comment by jboynyc** [comment]
Possible reviewers I've been able to identify include alexhanna, cmaimone, tresoldi, and nniiicc. Contributors to [cbail/textnets](https://github.com/cbail/textnets) would also be well suited (but don't appear in the reviewer list).

**Comment by gkthiruvathukal** [comment]
@alexhanna and @cmaimone, I am in need of 2 reviewers for this JOSS submission. Are either or both of you willing to serve as reviewers?

**Comment by cmaimone** [comment]
I've got 2 open reviews. I'd like to complete those before committing to
any additional ones.

**Comment by gkthiruvathukal** [comment]
@cmaimone Thank you for your quick response. I should have checked your reviewer workload first!

**Comment by alexhanna** [comment]
I don't have the bandwidth for this right now. Check with me in two weeks.

**Comment by sara-02** [comment]
Hey @jboynyc @gkthiruvathukal I am looking for more packages to review, and even though I have not contributed to textnets, I have knowledge about spacy and text analysis and community detection algorithms.
I would be happy to take this up.

**Comment by gkthiruvathukal** [comment]
Thanks, @sara-02, I will assign now now!

**Comment by gkthiruvathukal** [comment]
@whedon assign @sara-02 as reviewer.

**Comment by whedon** [comment]
OK, @sara-02 is now a reviewer

**Comment by tresoldi** [comment]
@gkthiruvathukal yes, glad to help, but I can only work on it from next week on (currently on vacation)

**Comment by gkthiruvathukal** [comment]
@tresoldi Thanks so much! That is not a problem at all. I will add you now and get this review started.

**Comment by gkthiruvathukal** [comment]
@whedon add @tresoldi as reviewer

**Comment by whedon** [comment]
OK, @tresoldi is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2594.
