### ISSUE TITLE
[PRE REVIEW]: Viime: Visualization and Integration of Metabolomics Experiments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2358]
**Submitting author:** @waxlamp (<a href="http://orcid.org/0000-0003-3898-4626">Roni Choudhury</a>)
**Repository:** <a href="https://github.com/girder/viime" target ="_blank">https://github.com/girder/viime</a>
**Version:** v0.1.0
**Editor:** @lpantano
**Reviewers:** @joannawolthuis, @rowlandm
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @waxlamp. **Currently, there isn't an JOSS editor assigned** to your paper.

@waxlamp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.62 s (105.8 files/s, 11806.1 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Vuejs Component                  60            810            218           7984
Python                           40           1057            324           3601
JavaScript                       24            199            144           2159
R                                15            371            323            620
JSON                              5              0              0            351
YAML                              3             25              0            314
SVG                               5              0              0            117
Markdown                          2             31              0             95
INI                               2             20              0             73
TypeScript                        3             12              2             60
HTML                              1              6              3             45
Pug                               3              7              0             41
Mako                              1              7              0             18
Bourne Again Shell                2              2              0             16
XML                               1              0              0              9
Bourne Shell                      1              1              0              4
Dockerfile                        1              2              0              4
CSS                               1              0              0              4
Stylus                            1              0              0              3
--------------------------------------------------------------------------------
SUM:                            171           2550           1014          15518
--------------------------------------------------------------------------------


Statistical information for the repository '2358' was gathered on 2020/06/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Brandon Davis                   61          2864           1334           20.18
Daniel Chiquito                  4            11             15            0.12
Jeffrey Baumes                   8            96              7            0.50
Jonathan Beezley               112          7024           3811           52.07
Mike VanDenburgh                 3            12              5            0.08
Roni Choudhury                  35           442            191            3.04
Samuel Gratzl                  201          3745           1209           23.81
subdavis                         1            13             28            0.20

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Brandon Davis              1452           50.7         11.8                8.33
Daniel Chiquito              11          100.0          0.4                9.09
Jeffrey Baumes               36           37.5          9.5                2.78
Jonathan Beezley           2935           41.8         12.1                3.41
Mike VanDenburgh              7           58.3          0.4               14.29
Roni Choudhury              187           42.3         10.2                8.02
Samuel Gratzl              2856           76.3          7.8                4.38
```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by arfon** [comment]
👋 @waxlamp - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02358/joss.02358/10.21105.joss.02358.pdf)

**Comment by waxlamp** [comment]
Hi @arfon, thanks for your help!

The submission instructions had me suggest one reviewer from the list: Lorena Pantano seemed like a good fit for our paper.

**Comment by arfon** [comment]
@whedon invite @lpantano as editor

:wave: @lpantano - would you be able to take on this submission for us?

**Comment by whedon** [comment]
@lpantano has been invited to edit this submission.

**Comment by lpantano** [comment]
@whedon assign @lpantano as reviewer

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@whedon check references

**Comment by lpantano** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by lpantano** [comment]
@whedon check references

**Comment by lpantano** [comment]
Hi @sctyner, @rowlandm, @joannawolthuis,

based on your experience maybe you be interested in reviewing this tool?

**Comment by rowlandm** [comment]
I could do this,  but the turn around time would be end of July.

Regards,

Rowland Mosbergen

Strategy Analyst | Big Data Analytics & Digital Transformation Lead |
Diversity & Inclusion
B of Eng (Aerospace Avionics)
Mob: 0423 030 626
Email: rowland.mosbergen@gmail.com
Web: https://www.linkedin.com/in/rowlandm-gaicd/

**Comment by lpantano** [comment]
Thank you @rowlandm, I may wait a couple of days, but if not I will assign you as a reviewer.

**Comment by lpantano** [comment]
@Nienke, based on your GitHub experience maybe you be interested in reviewing this tool?

**Comment by joannawolthuis** [comment]
Hi Lorena! I'm interested, what are the expectations exactly? :)

---------- Forwarded message ---------
Van: Lorena Pantano <notifications@github.com>
Date: wo 24 jun. 2020 om 00:02
Subject: Re: [openjournals/joss-reviews] [PRE REVIEW]: Viime: Visualization
and Integration of Metabolomics Experiments (#2358)
To: openjournals/joss-reviews <joss-reviews@noreply.github.com>
Cc: joannawolthuis <jcwolthuis93@gmail.com>, Mention <
mention@noreply.github.com>


Hi @sctyner <https://github.com/sctyner>, @rowlandm
<https://github.com/rowlandm>, @joannawolthuis
<https://github.com/joannawolthuis>,

based on your experience maybe you be interested in reviewing this tool?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/2358#issuecomment-648451425>,
or unsubscribe

**Comment by lpantano** [comment]
@joannawolthuis, thank you! this are the guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html and we normally expect reviews in two weeks or so. It should be a pretty nice experience :)

**Comment by lpantano** [comment]
@wheddon assign @joannawolthuis as reviewer

**Comment by arfon** [comment]
@whedon assign @joannawolthuis as reviewer

**Comment by whedon** [comment]
OK, @joannawolthuis is now a reviewer

**Comment by arfon** [comment]
@lpantano you had a typo :-)

**Comment by sctyner** [comment]
I am not available at this time. Thanks.

**Comment by lpantano** [comment]
@ionlights, would you be interested to review this tool, I think you visualization experience could help to review this nice tool. Thanks

**Comment by lpantano** [comment]
@whedon add @rowlandm as reviewer

**Comment by whedon** [comment]
OK, @rowlandm is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2410.

**Comment by rowlandm** [comment]
Sorry Lorena,

I had to decline as my position is not being extended and I have to look
for work add a priority outside of research software.

Regards,

Rowland Mosbergen

Strategy Analyst | Big Data Analytics & Digital Transformation Lead |
Diversity & Inclusion
B of Eng (Aerospace Avionics)
Mob: 0423 030 626
Email: rowland.mosbergen@gmail.com
Web: https://www.linkedin.com/in/rowlandm-gaicd/
