### ISSUE TITLE
[PRE REVIEW]: toughio: Pre- and post-processing Python library for TOUGH

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2359]
**Submitting author:** @keurfonluu (<a href="http://orcid.org/0000-0001-7927-0019">Keurfon Luu</a>)
**Repository:** <a href="https://github.com/keurfonluu/toughio" target ="_blank">https://github.com/keurfonluu/toughio</a>
**Version:** v1.3.0
**Editor:** @jgostick
**Reviewers:** @rreinecke
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @keurfonluu. **Currently, there isn't an JOSS editor assigned** to your paper.

@keurfonluu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.cageo.2012.04.008 is OK
- 10.1111/j.1745-6584.2008.00462.x is OK
- 10.1016/j.cageo.2016.09.009 is OK
- 10.1002/nme.2579 is OK
- 10.5281/zenodo.3888325 is OK
- 10.21105/joss.01450 is OK
- 10.1029/WR012i001p00057 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02359/joss.02359/10.21105.joss.02359.pdf)

**Comment by arfon** [comment]
@whedon check repository

**Comment by arfon** [comment]
👋 @keurfonluu - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.39 s (255.8 files/s, 28819.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          84           1897           1317           7352
Markdown                         3             82              0            234
TeX                              1             12              0            137
YAML                             4              9              0             62
reStructuredText                 5             79             76             61
DOS Batch                        1              8              1             26
make                             1              4              7              9
JSON                             2              0              0              6
-------------------------------------------------------------------------------
SUM:                           101           2091           1401           7887
-------------------------------------------------------------------------------


Statistical information for the repository '2359' was gathered on 2020/06/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Keurfon Luu                    595         76364          81658          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Keurfon Luu               10566           13.8          3.0                6.37
```

**Comment by arfon** [comment]
@whedon invite @jgostick as editor

:wave: @jgostick - would you be able to take on this submission?

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by jgostick** [comment]
@whedon assign @rreinecke as reviewer

**Comment by whedon** [comment]
OK, @rreinecke is now a reviewer

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2412.
