### ISSUE TITLE
[PRE REVIEW]: BigX: A geographical dataset visualisation tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2365]
**Submitting author:** @geekysquirrel (<a href="http://orcid.org/0000-0003-3030-9853">Stefanie Wiegand</a>)
**Repository:** <a href="https://gitlab.com/geekysquirrel/bigx" target ="_blank">https://gitlab.com/geekysquirrel/bigx</a>
**Version:** 2.1
**Editor:** @hugoledoux
**Reviewers:** @liberostelios, @jvdkwast
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @geekysquirrel. **Currently, there isn't an JOSS editor assigned** to your paper.

@geekysquirrel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5258/SOTON/P0014 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.84 s (200.3 files/s, 73892.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                     133           7332           8728          29268
JSON                             6              0              0          10795
CSS                             11            171             64           1700
HTML                             3             61             27           1057
Markdown                         5            256              0            897
Python                           6            192            200            780
SVG                              2              0              0            293
YAML                             1              6             10             98
TeX                              1              4              0             23
-------------------------------------------------------------------------------
SUM:                           168           8022           9029          44911
-------------------------------------------------------------------------------


Statistical information for the repository '2365' was gathered on 2020/06/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Stef                           238         97589          51089          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Stef                      46500           47.6          0.6               19.46
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02365/joss.02365/10.21105.joss.02365.pdf)

**Comment by arfon** [comment]
:wave: @geekysquirrel - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the month we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by danielskatz** [comment]
👋 @leouieda - is there any chance you would be willing and able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invited @leouieda as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@whedon invite @leouieda as editor

**Comment by whedon** [comment]
@leouieda has been invited to edit this submission.

**Comment by hugoledoux** [comment]
I see that @leouieda is not taking this one up? I could do this, I teach stuff related to this, it's in my area. Let me know.

**Comment by danielskatz** [comment]
Great, thanks!

**Comment by danielskatz** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by hugoledoux** [comment]
@whedon assign @liberostelios as reviewer

**Comment by whedon** [comment]
OK, @liberostelios is now a reviewer

**Comment by hugoledoux** [comment]
@whedon add @jvdkwast as reviewer

**Comment by whedon** [comment]
OK, @jvdkwast is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2537.
