### ISSUE TITLE
[PRE REVIEW]: ptsuite: An R-package for Fast Tail Index Estimation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2366]
**Submitting author:** @RM-cyber (<a href="http://orcid.org/0000-0002-4059-8735">Ranjiva Munasinghe</a>)
**Repository:** <a href="https://github.com/RM-cyber/ptsuite" target ="_blank">https://github.com/RM-cyber/ptsuite</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @RM-cyber. **Currently, there isn't an JOSS editor assigned** to your paper.

@RM-cyber if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (133.1 files/s, 28057.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              2             37              5            486
C++                              2            132            278            387
R                                4             67            476            142
Markdown                         2             26              0             72
-------------------------------------------------------------------------------
SUM:                            10            262            759           1087
-------------------------------------------------------------------------------


Statistical information for the repository '2366' was gathered on 2020/06/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
RM-cyber                         1           797              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
RM-cyber                    797          100.0          0.0               34.88
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02366/joss.02366/10.21105.joss.02366.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18637/jss.v040.i08 is OK
- 10.1007/978-1-4614-6868-4 is OK
- 10.7287/peerj.preprints.3188v1 is OK
- 10.1007/978-0-8176-4619-6 is OK
- 10.9734/JAMCS/2019/v33i130169 is OK

MISSING DOIs

- https://doi.org/10.2202/1544-6115.1128 may be missing for title: A General Framework for Weighted Gene Co-Expression Network Analysis
- https://doi.org/10.2139/ssrn.2244876 may be missing for title: Estimation of Social Exclusion Indicators from Complex Surveys: The R Package laeken
- https://doi.org/10.1002/9780470057339.vae043.pub2 may be missing for title: EnvStats:  An R Package for Environmental Statistics

INVALID DOIs

- None
```

**Comment by RM-cyber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02366/joss.02366/10.21105.joss.02366.pdf)

**Comment by RM-cyber** [comment]
possible reviewers (not in order): amoeba, wrathematics, soodoku

**Comment by RM-cyber** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by RM-cyber** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18637/jss.v040.i08 is OK
- 10.1007/978-1-4614-6868-4 is OK
- 10.7287/peerj.preprints.3188v1 is OK
- 10.1007/978-0-8176-4619-6 is OK
- 10.9734/JAMCS/2019/v33i130169 is OK
- 10.2202/1544-6115.1128 is OK
- 10.2139/ssrn.2244876 is OK
- 10.1002/9780470057339.vae043.pub2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by RM-cyber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02366/joss.02366/10.21105.joss.02366.pdf)

**Comment by arfon** [comment]
:wave:  @RM-cyber - Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by RM-cyber** [comment]
@arfon thanks for your feedback.
