### ISSUE TITLE
[REVIEW]: HOOMD-TF: GPU-Accelerated, Online Machine Learning in the HOOMD-blue Molecular Dynamics Engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2367]
**Submitting author:** @RainierBarrett (<a href="http://orcid.org/0000-0002-5728-9074">Rainier Barrett</a>)
**Repository:** <a href="https://github.com/ur-whitelab/hoomd-tf/" target ="_blank">https://github.com/ur-whitelab/hoomd-tf/</a>
**Version:** v1.0
**Editor:** @richardjgowers
**Reviewer:** @malramsay64, @rmeli
**Archive:** <a href="https://doi.org/10.5281/zenodo.3962305" target="_blank">10.5281/zenodo.3962305</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5d1323eadec82aabe86c65a403ff8f90/status.svg)](https://joss.theoj.org/papers/5d1323eadec82aabe86c65a403ff8f90)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5d1323eadec82aabe86c65a403ff8f90"><img src="https://joss.theoj.org/papers/5d1323eadec82aabe86c65a403ff8f90/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5d1323eadec82aabe86c65a403ff8f90/status.svg)](https://joss.theoj.org/papers/5d1323eadec82aabe86c65a403ff8f90)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ur-whitelab/hoomd-tf/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@malramsay64 & @rmeli, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @richardjgowers know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ur-whitelab/hoomd-tf/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@RainierBarrett) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ur-whitelab/hoomd-tf/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@RainierBarrett) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @malramsay64, @rmeli it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2367 with the following error: 

 Can't find any papers to compile :-(

**Comment by richardjgowers** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02367/joss.02367/10.21105.joss.02367.pdf)

**Comment by richardjgowers** [comment]
@RMeli @malramsay64 we're starting the review in this issue.  Usually if you find issues in the course of the review it's best to open issues on the github repo to track these.  Let me know if you have any questions.

**Comment by RMeli** [comment]
This is not seem to qualify as a [COI](https://github.com/openjournals/joss/blob/master/COI.md) but  I'll mention it here anyway, for transparency: as @richardjgowers is aware, I am a [MDAnalysis](https://github.com/MDAnalysis/mdanalysis) contributor. 

MDAnalysis is used in HOOMD-TF to work with trajectories produced by MD engines other than HOOMD-blue. Despite this, I think I am able to make an impartial assessment of the work.

**Comment by RMeli** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02367/joss.02367/10.21105.joss.02367.pdf)

**Comment by RMeli** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02367/joss.02367/10.21105.joss.02367.pdf)

**Comment by richardjgowers** [comment]
Hi @RainierBarrett has [this preprint](https://chemrxiv.org/articles/A_GPU-Accelerated_Machine_Learning_Framework_for_Molecular_Simulation_Hoomd-Blue_with_TensorFlow/8019527) been submitted elsewhere?

**Comment by RainierBarrett** [comment]
@richardjgowers I'm in the midst of wrapping up my PhD thesis right now, sorry for the delayed reply. This pre-print is not submitted or under review anywhere presently, and this JOSS submission is the only manuscript we have describing the HOOMD-TF package. We had previously submitted the content in that pre-print to a comp chem journal, but as you may have guessed they didn't like a software-only paper so we've arrived here. We're debating what to do about the chemrxiv pre-print, perhaps linking here as the final version should our article be accepted at JOSS.

**Comment by richardjgowers** [comment]
@RainierBarrett ok thanks, that's fine. @malramsay64 @RMeli how is the review going?

**Comment by RMeli** [comment]
@richardjgowers , I think only https://github.com/ur-whitelab/hoomd-tf/issues/201 is outstanding which should be addressed by https://github.com/ur-whitelab/hoomd-tf/pull/208.

**Comment by malramsay64** [comment]
Yes just the single outstanding issue highlighted by @RMeli

**Comment by RMeli** [comment]
@richardjgowers all outstanding issues seem to  be closed now and I don't have any further comments.

**Comment by richardjgowers** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2367 with the following error: 

 Can't find any papers to compile :-(

**Comment by richardjgowers** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by richardjgowers** [comment]
@whedon check references

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02367/joss.02367/10.21105.joss.02367.pdf)

**Comment by richardjgowers** [comment]
@RainierBarrett I think we're ready to move ahead with this, can you make a release on github and archive it on zenodo so we can pin the paper against that?

**Comment by RainierBarrett** [comment]
Okay, we've bumped to v1.0 and I set up a zenodo here: https://zenodo.org/record/3952665

**Comment by whitead** [comment]
Hi @richardjgowers, is there anything else your need from us to complete this review? Thanks!

**Comment by RMeli** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02367/joss.02367/10.21105.joss.02367.pdf)

**Comment by richardjgowers** [comment]
@whedon set 10.21105/joss.02367 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.21105/joss.02367" target="_blank">10.21105/joss.02367</a> is the archive.

**Comment by richardjgowers** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by richardjgowers** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2367 with the following error: 

 Can't find any papers to compile :-(

**Comment by richardjgowers** [comment]
@whedon accept from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1126/sciadv.1603015 is OK
- 10.1039/C6SC05720A is OK
- 10.1021/acscentsci.8b00913 is OK
- 10.1103/PhysRevLett.108.058301 is OK
- 10.1002/qua.24836 is OK
- 10.1002/adfm.201501919 is OK
- 10.1021/ct300857j is OK
- 10.1016/j.commatsci.2019.109363 is OK
-  10.25080/Majora-629e541a-00e  is OK
- 10.1002/jcc.21787 is OK
- 10.1016/j.sbi.2019.12.016 is OK
- 10.3389/fmolb.2019.00025 is OK
- 10.1039/C6SC05720A is OK
- 10.1063/1.4981796 is OK
- 10.1021/ct900369w is OK
- 10.1021/acs.jcim.0c00451 is OK
- 10.1016/j.commatsci.2019.109363 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1590

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1590, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss-paper-branch 
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@RainierBarrett Here are some additional points to work on for your paper: 

- [ ] Please complete your affiliations to include city, state (if applicable), and country (do not use acronyms for states and countries). 
- [ ] Please amend the Zenodo archive to have its own independent Zenodo DOI. I believe currently you made it have the same DOI as the (future) JOSS paper. This is not permitted as both should have their own DOI, so you have to change the archived version DOI (@richardjgowers for future reference please check that the archive DOI is accurate/appropriate in this sense) and report back with it here.

**Comment by RainierBarrett** [comment]
@Kevin-Mattheus-Moerman I updated author affiliations in the manuscript on joss-paper-branch. Unfortunately, the zenodo website isn't allowing me to change the DOI to a zenodo-specific one. When I try to ask it to reserve one in the edit process, it gives an error:

> Digital Object Identifier: The prefix 10.5281 is administrated locally. 

How shall we proceed?

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev @arfon do you know more about this. Can you help advise on what to do. The archive accidentally caries the joss DOI reserved for this paper. The author says they cannot alter it but we are still looking into it. 

@RainierBarrett I just checked and I clicked edit on one of my archived software projects. It looks like I can alter the DOI and there is a comment that says: `Please note that it is NOT possible to edit a Zenodo DOI once it has been registered by us, while it is always possible to edit a custom DOI.`. You should have the latter case. Admittedly I did not click proceed as I didn't want to change the DOI but perhaps you can check it again yourself.

**Comment by RainierBarrett** [comment]
@Kevin-Mattheus-Moerman yeah I saw that as well, so I tried to totally delete the DOI entry and click the "Reserve DOI" button, that's what caused this error. If I just leave the DOI field blank it simply keeps the JOSS one from before.

**Comment by Kevin-Mattheus-Moerman** [comment]
> @Kevin-Mattheus-Moerman yeah I saw that as well, so I tried to totally delete the DOI entry and click the "Reserve DOI" button, that's what caused this error. If I just leave the DOI field blank it simply keeps the JOSS one from before.

Okay. Lets wait to see what @arfon @openjournals/dev come back with

**Comment by RMeli** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by arfon** [comment]
> @Kevin-Mattheus-Moerman yeah I saw that as well, so I tried to totally delete the DOI entry and click the "Reserve DOI" button, that's what caused this error. If I just leave the DOI field blank it simply keeps the JOSS one from before.

I'm afraid you're going to have to ask Zenodo support for help here. The DOI you've reserved is the JOSS DOI that will be used for the paper (and can't resolve to Zenodo). Please ask them to delete this record and allow you to make another one.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon if deletion is a long and slow process, there is an ugly work around. If the authors minted a new release (annoying but works), they could create a new archive with a different DOI. This way we could move on with this paper (and the other archived version can be removed at a later point). Let's try waiting for deletion first though.

**Comment by RainierBarrett** [comment]
Thanks @arfon I'll try asking Zenodo to delete and get back as soon as I hear from them.

**Comment by RainierBarrett** [comment]
Alright all @arfon @Kevin-Mattheus-Moerman @RMeli @richardjgowers, Zenodo support was quick to reply and we just had to delete the old archive and re-upload to get a specific DOI for the archive. It's up now at https://zenodo.org/record/3962305. Thanks for your patience, and sorry for the confusion.

**Comment by RMeli** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02367/joss.02367/10.21105.joss.02367.pdf)

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.3962305 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3962305" target="_blank">10.5281/zenodo.3962305</a> is the archive.

**Comment by kthyng** [comment]
Hi @RainierBarrett! Do you want 1.0 or 1.0.1 as your version?

**Comment by kthyng** [comment]
Your paper looks good. 👍

**Comment by RainierBarrett** [comment]
Hi @kthyng , since the Zenodo archive was made with 1.0, I guess that makes the most sense for this, too. Any updates since publication should be easy enough to find :)

**Comment by kthyng** [comment]
@whedon accept deposit=true from branch joss-paper-branch

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1288178440517058562) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1599
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02367](https://doi.org/10.21105/joss.02367)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats to @RainierBarrett on your new publication! Thanks to editor @richardjgowers and to reviewers @malramsay64, @RMeli. This process wouldn't be possible without your time and expertise!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02367/status.svg)](https://doi.org/10.21105/joss.02367)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02367">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02367/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02367/status.svg
   :target: https://doi.org/10.21105/joss.02367
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02367/status.svg)](https://doi.org/10.21105/joss.02367)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by whitead** [comment]
Thank you everyone, especially @malramsay64 and @RMeli for your reviews! Congrats @RainierBarrett

**Comment by RainierBarrett** [comment]
Thanks everyone for your review work and help in the process!

**Comment by RMeli** [comment]
Congratulations @RainierBarrett, @whitead and all the HOOMD-TF team!

**Comment by malramsay64** [comment]
Congratulations to @RainierBarrett and the HOOMD-TF team. In addition to the great software you also have a fantastic process for making and reviewing changes :+1: . 

Also thanks to @RMeli for leading most of this review, definitely made it easier for me.
