### ISSUE TITLE
[PRE REVIEW]: Chips-n-Salsa: A Java Library of Customizable, Hybridizable, Iterative, Parallel, Stochastic, and Self-Adaptive Local Search Algorithms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2368]
**Submitting author:** @cicirello (<a href="http://orcid.org/0000-0003-1072-8559">Vincent A Cicirello</a>)
**Repository:** <a href="https://github.com/cicirello/Chips-n-Salsa" target ="_blank">https://github.com/cicirello/Chips-n-Salsa</a>
**Version:** v1.0
**Editor:** @galessiorob
**Reviewers:** @mbdemoraes, @nnadeau
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @cicirello. **Currently, there isn't an JOSS editor assigned** to your paper.

@cicirello if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.21 s (261.1 files/s, 70502.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           144            150           6415          44075
Java                           164           2709          11530          19019
CSS                              1             10             31            533
TeX                              1             28              0            247
Markdown                         3             38              0            110
Ant                              1             13             16            106
JavaScript                       1              1              0             29
-------------------------------------------------------------------------------
SUM:                           315           2949          17992          64119
-------------------------------------------------------------------------------


Statistical information for the repository '2368' was gathered on 2020/06/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vincent Cicirello                1         33288              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vincent Cicirello         33288          100.0          0.0               34.66
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-030-24202-2_7 is OK
- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1145/1143997.1144177 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1126/science.220.4598.671 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK

MISSING DOIs

- https://doi.org/10.4108/eai.3-12-2015.2262346 may be missing for title: Genetic Algorithm Parameter Control: Application to Scheduling with Sequence-Dependent Setups
- https://doi.org/10.1016/0004-3702(96)00007-0 may be missing for title: Artificial Intelligence: A Modern Approach
- https://doi.org/10.1016/b978-0-08-049944-4.50022-7 may be missing for title: Systematic and Nonsystematic Search Strategies
- https://doi.org/10.1109/icec.1995.489178 may be missing for title: Gaussian mutation and self-adaption for numeric genetic algorithms
- https://doi.org/10.1109/proc.1987.13916 may be missing for title: Nonconvex optimization by fast simulated annealing
- https://doi.org/10.1109/dac.1988.14775 may be missing for title: Performance of a New Annealing Schedule

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02368/joss.02368/10.21105.joss.02368.pdf)

**Comment by arfon** [comment]
:wave: @cicirello - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the month we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02368/joss.02368/10.21105.joss.02368.pdf)

**Comment by cicirello** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by cicirello** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-030-24202-2_7 is OK
- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1145/1143997.1144177 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1126/science.220.4598.671 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1109/icec.1995.489178 is OK
- 10.1109/proc.1987.13916 is OK
- 10.1109/dac.1988.14775 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK

MISSING DOIs

- https://doi.org/10.4108/eai.3-12-2015.2262346 may be missing for title: Genetic Algorithm Parameter Control: Application to Scheduling with Sequence-Dependent Setups
- https://doi.org/10.1016/0004-3702(96)00007-0 may be missing for title: Artificial Intelligence: A Modern Approach

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon invite @galessiorob as editor

:wave: @galessiorob - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by galessiorob** [comment]
@whedon start review

**Comment by galessiorob** [comment]
👋 Hi @cicirello!

I am in the process of assigning reviewers to this submission, but if you have any suggestions for reviewers please let me know.

In the meantime, it looks like you're only missing 2 DOIs, if you could nail those down that would great.

Many thanks!
______________

**Basic checks:**

* [x]  There’s a general description of the software
* [x] The software is within scope as research software
* [x] OSI-approved license: GNU General Public License (GPL)

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02368/joss.02368/10.21105.joss.02368.pdf)

**Comment by cicirello** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-030-24202-2_7 is OK
- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/eai.3-12-2015.2262346 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1145/1143997.1144177 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1126/science.220.4598.671 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1109/icec.1995.489178 is OK
- 10.1109/proc.1987.13916 is OK
- 10.1109/dac.1988.14775 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK

MISSING DOIs

- https://doi.org/10.1016/0004-3702(96)00007-0 may be missing for title: Artificial Intelligence: A Modern Approach

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon assign @galessiorob as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by cicirello** [comment]
Hi @galessiorob,

I added the one actually missing doi.  The other identified by whedon is not correct.  The reference is to a book that doesn't have a doi, and whedon incorrectly identified a doi to someone's review of the book.  I added the isbn of the book instead.  That seems to accomplish essentially the same thing in that the pdf that whedon generated added a link to a permanent record of the book in worldcat.

Here are a couple possible reviewers (mbdemoraes, danieledipompeo, professoralkmin).  I don't know them, and don't know their availability.  I found them by skimming JOSS's reviewer list.

**Comment by galessiorob** [comment]
@cicirello thanks for the suggestions, let me reach out to them and check their availability.

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02368/joss.02368/10.21105.joss.02368.pdf)

**Comment by galessiorob** [comment]
@whedon assign @mbdemoraes as reviewer

Thanks for volunteering to review Matheus!

**Comment by whedon** [comment]
OK, @mbdemoraes is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @nnadeau as reviewer

**Comment by whedon** [comment]
OK, @nnadeau is now a reviewer

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02368/joss.02368/10.21105.joss.02368.pdf)

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2448.
