### ISSUE TITLE
[PRE REVIEW]: Grafoscopio: A moldable tool for literate computing and reproducible research

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#237]
**Submitting author:** @offray (<a href="http://orcid.org/0000-0002-4640-6984">Offray Vladimir Luna Cárdenas</a>)
**Repository:** <a href="http://mutabit.com/repos.fossil/grafoscopio/" target ="_blank">http://mutabit.com/repos.fossil/grafoscopio/</a>
**Version:** 1.3.8
**Editor:** @arfon
**Reviewer:** @SergeStinckwich

**Author instructions**

Thanks for submitting your paper to JOSS @offray. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@offray if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @offray - I'm looking for a potential reviewer for this submission. Could you point me to the source code for the package? Also, what programming language is this written in?

**Comment by offray** [comment]
Hi Arfon,

Thanks for your work with this.

The package is written in Pharo Smalltalk. We have two source 
repositories for it, on for code at [1] and other for documentation and 
issues at [2]

[1] smalltalkhub.com/#!/~Offray/Grafoscopio
[2] http://mutabit.com/repos.fossil/grafoscopio/

Let me know anything else I can help with.

Cheers,

Offray

**Comment by arfon** [comment]
OK thanks @offray. Based on our pool of existing reviewers (https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) I think I'm going to struggle to find someone who is able to review this submission.

Do you have any suggestions for possible reviewers?

**Comment by offray** [comment]
Hi Arfon,

I suggested two reviewers in the submission process @acabunoc and 
@jakevdp, but I could find some reviewers in the Pharo community, if 
that's fine. Let me know and I will send the request ASAP.

Cheers,

Offray

**Comment by arfon** [comment]
> Let me know and I will send the request ASAP.

@offray - yes, that would be great. I think a major challenge for reviewers is going to be verifying the functionality of the software as most people don't know Smalltalk.

**Comment by jakevdp** [comment]
I wouldn't even know where to begin to be honest :smile:

**Comment by offray** [comment]
OK. I will ask some help from the Pharo community here.

Cheers,

Offray

**Comment by SergeStinckwich** [comment]
I can help if needed but as I know Offray there might be a comflict of interest.

**Comment by offray** [comment]
Hi all,

Thanks @SergeStinckwich for your offering and for the proper disclaimer. Pharo, having a small community will have less degrees of separation. Despite of that, I think that in an open journal like JOSS, the "blindness" of peer review is not the main property, but its transparency. 

@arfon and others are you fine with Serge offering? Stephan Ducasse has also offered as a reviewer.

Cheers,

**Comment by arfon** [comment]
> @arfon and others are you fine with Serge offering? Stephan Ducasse has also offered as a reviewer.

:+1: I'm happy for @SergeStinckwich to handle this.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @SergeStinckwich as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @SergeStinckwich

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/251. Feel free to close this issue now!

**Comment by arfon** [comment]
@SergeStinckwich please head over to #251 for the actual review thread.
