### ISSUE TITLE
[PRE REVIEW]: Bloatectomy: A python package for the identification and removal of duplicate text in the bloated notes of electronic health records and other documents

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2370]
**Submitting author:** @1fmusic (<a href="http://orcid.org/0000-0002-6886-3983">Summer Rankin</a>)
**Repository:** <a href="https://github.com/MIT-LCP/bloatectomy" target ="_blank">https://github.com/MIT-LCP/bloatectomy</a>
**Version:** v0.0.12
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @1fmusic. **Currently, there isn't an JOSS editor assigned** to your paper.

@1fmusic if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (128.0 files/s, 15557.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2            138              0            466
TeX                              1             16              0            256
Python                           4             35             70            216
Jupyter Notebook                 2              0            408             90
HTML                             3              0              0              3
DOS Batch                        1              0              0              2
Bourne Shell                     1              0              0              1
-------------------------------------------------------------------------------
SUM:                            14            189            478           1034
-------------------------------------------------------------------------------


Statistical information for the repository '2370' was gathered on 2020/06/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alistair Johnson                 1           319              0           96.96
Rankin_summer                    3             5              4            2.74
Summer K. Rankin                 1             1              0            0.30

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alistair Johnson            315           98.7          0.0               14.29
Rankin_summer                 5          100.0          0.0               20.00
Summer K. Rankin              1          100.0          0.0                0.00
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.4300/JGME-D-15-00201.1 is OK
- 10.4338/ACI-2016-09-R-0150 is OK
- 10.1097/01.CCM.0000104112.34142.79 is OK
- 10.1186/1471-2105-14-10 is OK
- 10.1371/journal.pone.0087555 is OK
- 10.7326/0003-4819-157-1-201206190-00429 is OK
- 10.1016/S0022-2836(05)80360-2 is OK
- 10.13026/C2XW26 is OK
- 10.1103/PhysRevX.5.011007 is OK
- 10.1016/j.ijmedinf.2006.06.004 is OK
- 10.1197/jamia.M3390 is OK

MISSING DOIs

- https://doi.org/10.1038/sdata.2016.35 may be missing for title: MIMIC-III, a freely accessible critical care database
- https://doi.org/10.25080/majora-92bf1922-00a may be missing for title: Data structures for statistical computing in python
- https://doi.org/10.1055/s-0038-1638592 may be missing for title: Extracting information from textual documents in the electronic health record: a review of recent research
- https://doi.org/10.1109/icicic.2008.422 may be missing for title: Plagiarism Detection Using the Levenshtein Distance and Smith-Waterman Algorithm
- https://doi.org/10.1109/mc.1984.1659158 may be missing for title: A Technique for High-Performance Data Compression

INVALID DOIs

- 10.5555/1593511 is INVALID
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02370/joss.02370/10.21105.joss.02370.pdf)

**Comment by 1fmusic** [comment]
potential reviewer: Darthpathos

**Comment by 1fmusic** [comment]
potential reviewer username: jkanche email: 
jayaram.kancherla@gmail.com

**Comment by 1fmusic** [comment]
>  INVALID DOIs
> 
> - 10.5555/1593511 is INVALID

I'm not sure why this is invalid? it's the python reference manual...
[http://citebay.com/how-to-cite/python/](url)

> @book{10.5555/1593511,
 author = {Van Rossum, Guido and Drake, Fred L.},
 title = {Python 3 Reference Manual},
 year = {2009},
 isbn = {1441412697},
 publisher = {CreateSpace},
 address = {Scotts Valley, CA}
}

**Comment by arfon** [comment]
...well https://doi.org/10.5555/1593511 doesn't resolve so whatever this DOI is, it's not a valid one :-)

**Comment by 1fmusic** [comment]
ok, took it out

**Comment by 1fmusic** [comment]
the others do not have a doi.

**Comment by 1fmusic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02370/joss.02370/10.21105.joss.02370.pdf)

**Comment by 1fmusic** [comment]
@whedon generate pdf

**Comment by 1fmusic** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02370/joss.02370/10.21105.joss.02370.pdf)

**Comment by 1fmusic** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.4300/JGME-D-15-00201.1 is OK
- 10.4338/ACI-2016-09-R-0150 is OK
- 10.1097/01.CCM.0000104112.34142.79 is OK
- 10.1186/1471-2105-14-10 is OK
- 10.1371/journal.pone.0087555 is OK
- 10.7326/0003-4819-157-1-201206190-00429 is OK
- 10.1016/S0022-2836(05)80360-2 is OK
- 10.1038/sdata.2016.35 is OK
- 10.13026/C2XW26 is OK
- 10.1103/PhysRevX.5.011007 is OK
- 10.25080/majora-92bf1922-00a is OK
- 10.1055/s-0038-1638592 is OK
- 10.1109/icicic.2008.422 is OK
- 10.1016/j.ijmedinf.2006.06.004 is OK
- 10.1109/mc.1984.1659158 is OK
- 10.1197/jamia.M3390 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
:wave: @1fmusic - thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
