### ISSUE TITLE
[PRE REVIEW]: Publink: A Python package for discovering relationships between data and publications

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2371]
**Submitting author:** @dwief-usgs (<a href="http://orcid.org/0000-0003-1554-7992">Daniel Wieferich</a>)
**Repository:** <a href="https://github.com/usgs-biolab/publink" target ="_blank">https://github.com/usgs-biolab/publink</a>
**Version:** v0.2.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @dwief-usgs. **Currently, there isn't an JOSS editor assigned** to your paper.

@dwief-usgs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (344.8 files/s, 21983.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          10            208            436            540
reStructuredText                13            179            202            197
make                             2             24              6             75
Markdown                         3             18              0             59
YAML                             2              5              4             53
TeX                              1              5              0             48
JSON                             1              8              0             39
DOS Batch                        1              8              1             27
INI                              1              4              3             19
-------------------------------------------------------------------------------
SUM:                            34            459            652           1057
-------------------------------------------------------------------------------


Statistical information for the repository '2371' was gathered on 2020/06/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Brandon S Serna                  1             6              5            0.37
Brandon Serna                    6           265            269           17.73
Langseth                         1            31             13            1.46
Wieferich, Daniel Jo             4             7              7            0.46
dwief                           19          1783            616           79.67
dwief-usgs                       1             4              5            0.30

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Brandon Serna               187           70.6          0.7                0.00
Langseth                     17           54.8          0.8               11.76
dwief                       980           55.0          0.7               17.65
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1087/20090411 is OK
- 10.1038/sdata.2018.259 is OK
- 10.25490/a97f-egyk is OK
- 10.14454/7xq3-zf69 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02371/joss.02371/10.21105.joss.02371.pdf)

**Comment by arfon** [comment]
:wave: @dwief-usgs - thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
