### ISSUE TITLE
[REVIEW]: DVRlib: A C++ library for geometric mesh improvement using Directional Vertex Relaxation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2372]
**Submitting author:** @rram84 (<a href="http://orcid.org/0000-0001-7403-7728">Ramsharan Rangarajan</a>)
**Repository:** <a href="https://bitbucket.org/rram/dvrlib/src/joss/" target ="_blank">https://bitbucket.org/rram/dvrlib/src/joss/</a>
**Version:** v1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @hugoledoux, @jhale, @jonwong12
**Archive:** <a href="https://doi.org/10.5281/zenodo.3995623" target="_blank">10.5281/zenodo.3995623</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9b16f05d126e812c783e4b34061160a3/status.svg)](https://joss.theoj.org/papers/9b16f05d126e812c783e4b34061160a3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9b16f05d126e812c783e4b34061160a3"><img src="https://joss.theoj.org/papers/9b16f05d126e812c783e4b34061160a3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9b16f05d126e812c783e4b34061160a3/status.svg)](https://joss.theoj.org/papers/9b16f05d126e812c783e4b34061160a3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://bitbucket.org/rram/dvrlib/src/joss/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@hugoledoux & @jhale & @jonwong12, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/rram/dvrlib/src/joss/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rram84) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/rram/dvrlib/src/joss/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rram84) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/rram/dvrlib/src/joss/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rram84) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @hugoledoux, @jhale, @jonwong12 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02372/joss.02372/10.21105.joss.02372.pdf)

**Comment by hugoledoux** [comment]
@rram84 I am working on the review and I opened a few issues in your repository for the cmake dependencies (https://bitbucket.org/rram/dvrlib/issues/1/), and the fact that the unit tests are not compiling for me (https://bitbucket.org/rram/dvrlib/issues/2/).

Also, I spotted a few typos and things that could be improved in the paper, simpler to just give you my handwritten notes: https://hugoledoux.stackstorage.com/s/2b4KXD6ZqeqfEHJ

**Comment by hugoledoux** [comment]
## Community guidelines

While there is a section about contribution deep inside the docs (https://rram.bitbucket.io/dvr-docs/html/contributing.html), maybe better to add a file `CONTRIBUTING.md` to the root of the repository? This is more standard in my opinion.

**Comment by hugoledoux** [comment]
## State of the field

In the paper, there is not really links to other similar software. Also, in the docs there is a nice summary of what your software is *not*, and that should be added I reckon. 

  > It is also important to note what DVRlib is not:
    DVRlib is not a mesh generator, but can be coupled to one.
    DVRlib is not a tool for adaptive mesh refinement, but can improve an adaptively refined mesh.
    DVRlib is not a mesh untangling tool, but can improve an untangled mesh.
    DVRlib is not a mesh simplification tool.

  > A large number of software libraries provide a variety of tools for generating, improving and manipulating unstructured meshes. In this context, it is important to note that DVRlib is neither intended to be, nor is it a comprehensive mesh improvement toolbox. DVRlib performs a very specific type of mesh improvement, commonly termed as geometric mesh optimization, to improve mesh quality. It can be coupled with a broader suite of operations, including topological operations such as face swapping and vertex insertion/removal.

**Comment by rram84** [comment]
> ## Community guidelines
> While there is a section about contribution deep inside the docs (https://rram.bitbucket.io/dvr-docs/html/contributing.html), maybe better to add a file `CONTRIBUTING.md` to the root of the repository? This is more standard in my opinion.

@hugoledoux Thank you for taking up the review for this submission.
I added CONTRIBUTING.md to the root directory, and linked to in README.md.

**Comment by rram84** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02372/joss.02372/10.21105.joss.02372.pdf)

**Comment by rram84** [comment]
> ## State of the field
> In the paper, there is not really links to other similar software. Also, in the docs there is a nice summary of what your software is _not_, and that should be added I reckon.
> 
> > It is also important to note what DVRlib is not:
> > DVRlib is not a mesh generator, but can be coupled to one.
> > DVRlib is not a tool for adaptive mesh refinement, but can improve an adaptively refined mesh.
> > DVRlib is not a mesh untangling tool, but can improve an untangled mesh.
> > DVRlib is not a mesh simplification tool.
> 
> > A large number of software libraries provide a variety of tools for generating, improving and manipulating unstructured meshes. In this context, it is important to note that DVRlib is neither intended to be, nor is it a comprehensive mesh improvement toolbox. DVRlib performs a very specific type of mesh improvement, commonly termed as geometric mesh optimization, to improve mesh quality. It can be coupled with a broader suite of operations, including topological operations such as face swapping and vertex insertion/removal.

@hugoledoux 
The paper now includes a section on what DVRlib does  and doesn't, as you suggested. I made a number of other small revisions to improve the paper. 

The paper now cites the following softwares:
Mesh generators (which use relaxation libraries under the hood): Hypermesh, CGAL, TetGen, Gmsh. The documentation pages include examples using DVRlib to improve meshes generated by these softwares.
Dedicated mesh relaxation libraries: Optimesh, Mesquite and GETMe. 

I also cite:
- Netgen, which is much broader in scope, but has popular mesh generation/improvement routines. 
- Budd et al (2009) on mesh motion for r-adaptivity.

**Comment by rram84** [comment]
> @rram84 I am working on the review and I opened a few issues in your repository for the cmake dependencies (https://bitbucket.org/rram/dvrlib/issues/1/), and the fact that the unit tests are not compiling for me (https://bitbucket.org/rram/dvrlib/issues/2/).

I addressed these issues with changes to CMakeLists.txt and a more detailed set of instructions in README.md. Please see the comments under each issue.

> Also, I spotted a few typos and things that could be improved in the paper, simpler to just give you my handwritten notes: https://hugoledoux.stackstorage.com/s/2b4KXD6ZqeqfEHJ
> and btw, in JOSS all the DOIs for papers should be given, you have none. Better to add them now.

Thank you for the notes. The paper and references have been revised.

**Comment by jonwong12** [comment]
Sorry. I've just gotten around to do a review, but the invitation expired. Can you please re-invite and I'll accept it on time this time.

@rram84 Not sure if you're aware of this [work](https://github.com/crawforddoran/quartet), but I believe it does some "random" mesh relaxation.

**Comment by danielskatz** [comment]
@whedon re-invite @jonwong12 as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@jonwong12 please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by rram84** [comment]
@jonwong12 
Hi Jonathan, Thank you for the reference to isosurface meshing. I am going over it. If required, I will include a short discussion/citation in the manuscript.

**Comment by hugoledoux** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02372/joss.02372/10.21105.joss.02372.pdf)

**Comment by hugoledoux** [comment]
@rram84 I went over your changes and opened 2 small issues/PRs in your repo (https://bitbucket.org/rram/dvrlib/pull-requests/1 + https://bitbucket.org/rram/dvrlib/issues/3/pdf-small-issue). All the rest is working for me and I find the paper improved and clearer. I am happy and recommend acceptance.

**Comment by jonwong12** [comment]
@rram84 I noticed that `DVRDIR` is required to run the executable otherwise in `Release` mode one will get segmentation faults. I have a small suggestion which is to reduce reliance in the tutorials on `DVRDIR` if possible. It's somewhat documented in the README.md that `DVRDIR` is necessary because of relative paths, I can see how it can be easy to miss in certain situations (reloading a shell environment).

My suggestion is to somehow use CMAKE variables to reference `PROJECT_SOURCE_DIR` and then write that path directly into a header file (stackoverflow)[https://stackoverflow.com/questions/22259279/passing-a-cmake-variable-to-c-source-code]. This way you don't need to define `DVRDIR` and users don't have to worry about this for the tutorial examples. I think this would help a lot with "first-impressions", but it's just a suggestion.

**Comment by jonwong12** [comment]
@rram84 I think it would also be beneficial to have the files in `help-*.md` available and built (either by default or with a CMAKE_OPTION) in the build directory. For `toy.cpp` you could use GTEST or just perform a simple check to make sure the output is within a particular tolerance. It would be beneficial to hook that up to `ctest` in cmake and use `make test` to run the test problems to very the installation.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jhale this is just a friendly checkup to see how you are getting on with your review. Let me know if you have any questions.

**Comment by rram84** [comment]
> @rram84 I think it would also be beneficial to have the files in `help-*.md` available and built (either by default or with a CMAKE_OPTION) in the build directory. For `toy.cpp` you could use GTEST or just perform a simple check to make sure the output is within a particular tolerance. It would be beneficial to hook that up to `ctest` in cmake and use `make test` to run the test problems to very the installation.

@jonwong12 
Thanks for the suggestion to detect the project source directory with cmake. It makes sense for the examples in test/ and tutorial/ folders.

Using gtest in test/ folders is also helpful. I contemplated doing this before, but wanted to keep the requirements small since the library itself is quite small. I will give it a try this week. 

I will also incorporate your suggestion to build the help files as a way of testing the requirements for DVRlib.

**Comment by jhale** [comment]
The paper is excellent and clearly constitutes start-of-the-art academic research in this area.

I had one academic question: Is it possible to constrain boundary vertices to lie on a parametric domain prescribed by e.g. an OpenCASCADE geometry? This would require e.g. interaction with gmsh.

I have some small comments about the software aspects:

- The package is header-only but I still want a way to install it. CMake provides a way to 'build' header-only libraries, and to automatically produce the file to allow my own CMake project to 'find' e.g. DVRlib. See: https://dominikberner.ch/cmake-interface-lib/ and https://gitlab.com/libeigen/eigen/-/blob/master/CMakeLists.txt#L576 A nice side effect here is that if I see `CMakeLists.txt` in the root I know immediately how to install the library without worrying too much about the details.
- `LICENSE` all-caps is the convention for naming the license file.
- I agree with @hugoledoux the demos output should also form a test by checking the output is sane or at least matches a well known 'good version' of your library.
- Continuous integration badge based on the above would be good, e.g. using Bitbucket Pipelines. Personally, I would not use a project that does not have a CI system setup.
- A `Dockerfile` based on a well-known image e.g. `ubuntu:20.04` would provide an easy to read and precise specification of the dependencies and the precise way in which to build/install the software.
- Running multiple tutorials in the same working directory produces a bit of a mess. Split them out into their own directory? Write to an `output/` directory?
- The C++ is relatively modern, i.e. uses STL and C++11 features.
- Throughout the C++ code there is a mix of tabs, spaces, and a lot of 'hanging' white space.
- Whitespace is non-standard according to multiple style guides I am aware of.
- These previous issues could be fixed reasonably quickly with an linter, e.g. `clang-tidy`. This could also form part of the CI tests.

**Comment by rram84** [comment]
@jhale 
Thank you for the detailed suggestions. I will be working to address them over this coming week.

**Comment by rram84** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02372/joss.02372/10.21105.joss.02372.pdf)

**Comment by rram84** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02372/joss.02372/10.21105.joss.02372.pdf)

**Comment by rram84** [comment]
@jonwong12 and @jhale

I have made a number of changes to DVRlib based on your suggestions:

- DVRlib is now installable using cmake as follows:
```mkdir build; cd build
cmake path-to-dvrlib/ 
make 
make test
make install
```
- Unit tests verifying correctness were previously located within src/. These have now been moved to a more visible location under test/ in the root directory.
- Simple tests to verify usage of GSL and OpenMP  are included in the list of unit tests.
- Unit tests compile and run automatically.
- The directory structure for DVRlib is more consistent with common practice.
- Using the library does not require setting an environment variable anymore (previously required DVRDIR).
- README.md and the Doxygen pages provide revised instructions for :
           - Installation and testing.
           - Compiling and running tutorial examples 
           - Using DVRlib in a project with or without CMake
- Build testing is enabled using bitbucket's pipelines. The file bitbucket-pipeline.yml has been added for this purpose. A CI badge has been added. 
- The tutorial examples now write output files within respective folders (within the build folder).
     
A couple of things I did not include at this time:
- gtest:  This would be nice. Since there are only about a dozen unit tests, I thought that adding a new dependency just to run them was not essential. 
- clang-format: The headers are littered with doxygen comments for documentation. clang-format seems to break the documentation. It is possible to toggle clang-format so that the documentation is left untouched. I intend to do this soon. But I did not want to delay responding to the review because of it.

**Comment by rram84** [comment]
@jhale

**About relaxing nodes constrained to on a boundary:** 

DVRlib currently provides a way to do this for implicitly specified boundaries (in 2D and 3D), see the example tutorial/dvr-constraint.cpp.
The user provides a level set function, which is used to compute the closest point projection map. The latter in turn helps to constrain the node location to the boundary manifold during relaxation.

The same is possible, at least in principle, for parametric curves/surfaces too. We will have to address 2 questions:
- a representation for the geometry. As you mentioned, this this is best done using libraries like opencascade. 
- a nonlinear solver to compute closest point projection map.

This would be a nice feature. I know of open cascade, but haven't used it.  I hope to work on this in the near future.

**Comment by jhale** [comment]
The authors have satisfactorily addressed the comments in my initial review, so I am pleased to recommend to @Kevin-Mattheus-Moerman that the article be accepted.

**Comment by rram84** [comment]
@jonwong12 
Hi Jonathan, 
I wanted to check if you had a chance to examine the revisions to DVRlib. If there is a specific revision you want to see included, I can work on it.

**Comment by jonwong12** [comment]
@rram84 Sorry. I was trying to use DVRlib of a sample un-optimiezd mesh I have lying around a few weeks ago. I got a little distracted, but I should be able to verify in the next 2 to 3 days.

**Comment by jonwong12** [comment]
@rram84 Do the `tutorial` still compile? Not sure if the instructions need to be updated.

**Comment by rram84** [comment]
@jonwong12 
Hi Jonathan, 
To verify that the examples in `tutorial/` compile & run, I added a few additional steps in bitbucket-pipelines.yml.
You can examine the build results for the latest commit: https://bitbucket.org/rram/dvrlib/addon/pipelines/home#!/results/32

Could you check that `make install` did in fact install DVRlib?
If you provided a custom install location with `-DCMAKE_INSTALL_PREFIX`, using `-DCMAKE_PREFIX_PATH` when building `tutorial/ `may be needed by cmake to find DVRlib.

**Comment by jonwong12** [comment]
Hmm. So I have used a specific `CMAKE_INSTALL_PREFIX`.

I added a `build-install` directory in the repository root and installed to that location.

```
$ cmake ../tutorial -DCMAKE_PREFIX_PATH=$(pwd)/build-install
CMake Error at <path>/dvrlib/build/DVRlibConfig.cmake:27 (include):
  include could not find load file:

    <path>/dvrlib/build/DVRlibTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:13 (find_package)
```

**Comment by rram84** [comment]
@jonwong12
Hi Jonathan, 
I couldn't reproduce the issue you encountered on my machine. 
I followed these steps to mimic your workflow using bitbucket pipelines:

```
mkdir build              # build library here
mkdir build-install   # install here
mkdir tutorial-build # build tutorial as a project here
cd build
cmake ../ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=./../build-install
make
make test
make install             # library installed in build-install
cd ../
ls build-install/        # should show include/ and share/
cd tutorial-build      # build the tutorial here
cmake ../tutorial/ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_PREFIX_PATH=./../build-install
make
```

You will find this sequence of steps reproduced verbatim in bitbucket-pipelines.yml.
The successful build report is here: https://bitbucket.org/rram/dvrlib/addon/pipelines/home#!/results/33

Could there be some issue in where you built and where you installed?
Thanks!

**Comment by rram84** [comment]
@jonwong12
Hi Jonathan, 
I couldn't reproduce the issue you encountered on my machine. 
I followed these steps to mimic your workflow using bitbucket pipelines:

```
mkdir build              # build library here
mkdir build-install   # install here
mkdir tutorial-build # build tutorial as a project here
cd build
cmake ../ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=./../build-install
make
make test
make install             # library installed in build-install
cd ../
ls build-install/        # should show include/ and share/
cd tutorial-build      # build the tutorial here
cmake ../tutorial/ -DCMAKE_CXX_COMPILER=g++ -DCMAKE_PREFIX_PATH=./../build-install
make
```

You will find this sequence of steps reproduced verbatim in bitbucket-pipelines.yml.
The successful build report is here: https://bitbucket.org/rram/dvrlib/addon/pipelines/home#!/results/33

Could there be some issue in where you built and where you installed?
Thanks!

**Comment by jonwong12** [comment]
@rram84 I just pulled a fresh copy and was able to verify that it works! It must have been some leftover cmake files that were causing the error.

**Comment by rram84** [comment]
@jwong12 
Thank you for the review Jonathan!

**Comment by rram84** [comment]
@Kevin-Mattheus-Moerman 
I think all three reviews have been completed.

**Comment by Kevin-Mattheus-Moerman** [comment]
@hugoledoux, @jhale, @jonwong12 thanks for your review efforts here!!! 

Since all boxes are ticked I will proceed with processing this work for acceptance in JOSS.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02372/joss.02372/10.21105.joss.02372.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/16M1089101 is OK
- 10.1007/s10589-017-9903-z is OK
- 10.1145/2629697 is OK
- 10.1002/nme.2579 is OK
- 10.1007/BFb0014497 is OK
- 10.1007/978-3-540-75103-8_1 is OK
- 10.1137/S0036144503429121 is OK
- 10.1016/S0045-7949(02)00002-0 is OK
- 10.1002/nme.5960 is OK
- 10.1002/nme.5949 is OK
- 10.1002/nme.341 is OK
- 10.1017/S0962492906400015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@rram84 can you work on these final steps: 

**Points on the paper:**
- [ ] You mention `simulating models` in the first sentence. I feel models are the entities used to perform simulations. So one does not simulate a model but one uses a model to do simulations. I suggest you rephrase this. Perhaps you can just say: `The success of finite element simulations arising in....` 

- [ ] Check and fix the questions marks in the paper at `Overloaded vertex and mesh optimization routines for serial
and thread-parallel execution, see ??.`

Once you've complete these points for the paper please run `@whedon generate pdf` here to update the proof. Also run `@whedon check references`, if you've added/changed references. 

**General points:** 
- [ ] Check and report back with the latest version tag for this software, has it moved on from `v1.0`? 

- [ ] Archive a copy of the software on ZENODO and report back here with the archive DOI. Please use the DOI suggested by ZENODO and do not edit it or enter a custom one. Please ensure metadata for this archived version matched that of the paper in therms of the title and authors.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.3995623 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3995623" target="_blank">10.5281/zenodo.3995623</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/16M1089101 is OK
- 10.1007/s10589-017-9903-z is OK
- 10.1145/2629697 is OK
- 10.1002/nme.2579 is OK
- 10.1007/BFb0014497 is OK
- 10.1007/978-3-540-75103-8_1 is OK
- 10.1137/S0036144503429121 is OK
- 10.1016/S0045-7949(02)00002-0 is OK
- 10.1002/nme.5960 is OK
- 10.1002/nme.5949 is OK
- 10.1002/nme.341 is OK
- 10.1017/S0962492906400015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1668

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1668, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1298218873221677058) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1669
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02372](https://doi.org/10.21105/joss.02372)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02372/status.svg)](https://doi.org/10.21105/joss.02372)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02372">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02372/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02372/status.svg
   :target: https://doi.org/10.21105/joss.02372
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02372/status.svg)](https://doi.org/10.21105/joss.02372)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
