### ISSUE TITLE
[PRE REVIEW]: tspex: a tissue-specificity calculator for gene expression data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2375]
**Submitting author:** @apcamargo (<a href="http://orcid.org/0000-0003-3913-2484">Antonio P Camargo</a>)
**Repository:** <a href="https://github.com/apcamargo/tspex" target ="_blank">https://github.com/apcamargo/tspex</a>
**Version:** v0.6.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @apcamargo. **Currently, there isn't an JOSS editor assigned** to your paper.

@apcamargo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1006/rwgn.2001.0639 is OK
- 10.5281/zenodo.3509134 is OK

MISSING DOIs

- https://doi.org/10.1093/bib/bbw008 may be missing for title: A benchmark of gene expression tissue-specificity metrics
- https://doi.org/10.1371/journal.pcbi.1005274 may be missing for title: Tissue-specificity of gene expression diverges slowly between orthologs, and rapidly between paralogs
- https://doi.org/10.1101/311563 may be missing for title: A systematic survey of human tissue-specific gene expression and splicing reveals new opportunities for therapeutic target identification and evaluation
- https://doi.org/10.1093/nar/gkx850 may be missing for title: TissGDB: tissue-specific gene database in cancer
- https://doi.org/10.1093/bioinformatics/bti042 may be missing for title: Genome-wide midrange transcription profiles reveal expression level relationships in human tissue specification
- https://doi.org/10.1007/s10888-011-9188-x may be missing for title: The origins of the Gini index: extracts from Variabilità e Mutabilità (1912) by Corrado Gini
- https://doi.org/10.1186/gb-2005-6-4-r33 may be missing for title: Promoter features related to tissue specificity as measured by Shannon entropy
- https://doi.org/10.1093/bioinformatics/bts169 may be missing for title: PaGeFinder: quantitative identification of spatiotemporal pattern genes
- https://doi.org/10.1093/nar/gkp866 may be missing for title: Modeling tissue-specific structural patterns in human and mouse promoters
- https://doi.org/10.1093/bioinformatics/btq109 may be missing for title: TiSGeD: a database for tissue-specific genes
- https://doi.org/10.1101/gad.17446611 may be missing for title: Integrative annotation of human large intergenic noncoding RNAs reveals global properties and specific subclasses
- https://doi.org/10.1038/s41588-018-0154-4 may be missing for title: Using an atlas of gene regulation across 44 human tissues to inform complex disease-and trait-associated variation
- https://doi.org/10.1093/oxfordjournals.molbev.a026239 may be missing for title: Determinants of substitution rates in mammalian genes: expression pattern affects selection intensity but not mutation rate
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02375/joss.02375/10.21105.joss.02375.pdf)

**Comment by apcamargo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2375 with the following error: 

 Error reading bibliography ./paper.bib (line 32, column 3):
unexpected "p"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by apcamargo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02375/joss.02375/10.21105.joss.02375.pdf)

**Comment by apcamargo** [comment]
Possible reviewers: @azneto @a-slide @ctb @luizirber

**Comment by apcamargo** [comment]
Possible reviewers: azneto, a-slide, ctb, luizirber

**Comment by kthyng** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.24 s (88.0 files/s, 14620.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            180            630            735
Markdown                         5            122              0            332
TeX                              1             22              0            239
YAML                             2             10              0             69
Jupyter Notebook                 1              0           1081             37
CSS                              1              4              0             16
RobotFramework                   1              0              0             11
INI                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            21            338           1711           1442
-------------------------------------------------------------------------------


Statistical information for the repository '2375' was gathered on 2020/06/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Antonio Camargo                 50          1801            286           97.94
Antônio Pedro Camarg             3             2              4            0.28
adriayumi                        3            35              3            1.78

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Antonio Camargo            1528           84.8          1.9               16.36
adriayumi                    17           48.6         15.0               11.76
```

**Comment by kthyng** [comment]
Hi @apcamargo, and thanks for your submission. Can you give some more information about your code? We at the editorial board think this package looks useful, but possibly too small in scope. Are there other equivalent packages available to do this sort of calculation? We will accept small packages if they truly fulfill a significant need, but that need should be justified and clearly established.

**Comment by apcamargo** [comment]
Hi @kthyng. The scope of this package is intentionally restricted to be good and simple to use to perform one relevant task. It was originally developed due to the importance of identifying tissue-specific lncRNAs, the then upcoming release of [GTEx](https://www.gtexportal.org/home/) v8 and the lack of user-friendly tools designed to compute tissue-specificity metrics.

The target audience is molecular biologists that want to identify tissue-specific genes without having to learn R or Python. Some of the most useful metrics are complicated to implement in something like Excel and we provide a very simple [web interface](https://github.com/apcamargo/tspex) where the user can just upload their expression matrix and get in-browser results.

Regarding other packages that perform the same kind of calculation, I don't think there's any other one. A few metrics could be computed using functions available in R or Python packages, while others were implemented as functions in a library for the first time. But tspex is the first package that provides an all-in-one and easy to use solution for this task.

Given the importance of tissue-specificity for a diverse range of fields in molecular biology (such as cancer and lncRNA research and drug discovery), we were motivated to develop tspex as a solution to address the lack of tools designed to be accessible to a broad audience of researchers.

**Comment by ctb** [comment]
hi all, since whedon made the mistake of tagging me in :), I can say: my group works fairly extensively in this area, and the response by @apcamargo seems spot on to me. I would be happy to review this submission, but can't get to it until after July 8th. If that's acceptable, and the ed board accepts this for review, sign me up!

**Comment by kthyng** [comment]
@ctb were you notified about being mentioned here without the "@"? I didn't know that was possible!

**Comment by ctb** [comment]
indeed I was - not sure why, but I'm OK with it :)

**Comment by danielskatz** [comment]
I wonder if @apcamargo made suggestions in a comment with an @, then deleted that comment and replaced it with one without them?

**Comment by apcamargo** [comment]
My fault! I tagged the suggest reviewers (force of habit) and submitted the comment before noticing it. whedon fas faster to pick it up than I was to edit the original comment.

Anyway, thanks @ctb!

**Comment by apcamargo** [comment]
Yes, that's what happened @danielskatz. If this is against the editorial policies I can suggest different reviewers

**Comment by danielskatz** [comment]
no, it's fine. (well, of course we try to avoid tagging lots of people, but mistake happen)

**Comment by arfon** [comment]
:wave: @apcamargo - Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
