### ISSUE TITLE
[REVIEW]: COVID-19 Data Hub

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2376]
**Submitting author:** ArdiaD (<a href="http://orcid.org/0000-0003-2823-782X">David Ardia</a>)
**Repository:** <a href="https://github.com/covid19datahub/COVID19/" target ="_blank">https://github.com/covid19datahub/COVID19/</a>
**Version:** v2.0.3
**Editor:** @will-rowe
**Reviewers:** @linuxscout, @will-rowe
**Archive:** <a href="https://doi.org/10.5281/zenodo.3939184" target="_blank">10.5281/zenodo.3939184</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/171be0f59e52bf0a4f24b76a58c55659/status.svg)](https://joss.theoj.org/papers/171be0f59e52bf0a4f24b76a58c55659)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/171be0f59e52bf0a4f24b76a58c55659"><img src="https://joss.theoj.org/papers/171be0f59e52bf0a4f24b76a58c55659/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/171be0f59e52bf0a4f24b76a58c55659/status.svg)](https://joss.theoj.org/papers/171be0f59e52bf0a4f24b76a58c55659)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/covid19datahub/COVID19/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@linuxscout & @mbod, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @will-rowe know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/covid19datahub/COVID19/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (ArdiaD) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/covid19datahub/COVID19/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (ArdiaD) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @linuxscout, @mbod it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/s1473-3099(20)30120-1 may be missing for title: An interactive web-based dashboard to track COVID-19 in real time

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02376/joss.02376/10.21105.joss.02376.pdf)

**Comment by will-rowe** [comment]
Hey @linuxscout and @mbod - just checking in and seeing how the reviews are going. Let me know if you need anything!

**Comment by linuxscout** [comment]
Hey @will-rowe, I have defended my PhD thesis these days, I will work on review soon.

**Comment by linuxscout** [comment]
@will-rowe, I need some explanation from authors, on this feature!

> 

>  Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

**Comment by ArdiaD** [comment]
Hi @linuxscout; I see you've almost finished the review. Thx a lot! @mbod any chance to go over it over the coming days? thx again for your help!

**Comment by ArdiaD** [comment]
> @will-rowe, I need some explanation from authors, on this feature!
> 
> > 
> 
> > Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

@emanuele-guidotti what would you say here?

**Comment by ArdiaD** [comment]
> Hey @linuxscout and @mbod - just checking in and seeing how the reviews are going. Let me know if you need anything!

thx @will-rowe for following up!

**Comment by ArdiaD** [comment]
> @will-rowe, I need some explanation from authors, on this feature!
> 
> > 
> 
> > Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

Hi @linuxscout. We have implemented a set of unit testing functions in the package. This is available here: https://github.com/covid19datahub/COVID19/tree/master/tests/testthat

We follow the standard practice in R, using testthat.

**Comment by linuxscout** [comment]
@ArdiaD  thanks

**Comment by linuxscout** [comment]
@will-rowe  I finished my review

**Comment by ArdiaD** [comment]
> @will-rowe I finished my review

Thx @linuxscout for your review! This is much appreciated!

**Comment by will-rowe** [comment]
Thank you very much @linuxscout - it looks like you are happy with the submission.

**Comment by will-rowe** [comment]
@mbod - can you please let us know how you are getting on? If you are no longer able to review, please do let us know as I can sort out alternatives. I'll give you a couple of days to respond to this message

**Comment by will-rowe** [comment]
@whedon remind @will-rowe in two days

**Comment by whedon** [comment]
Reminder set for @will-rowe in two days

**Comment by ArdiaD** [comment]
@will-rowe seems like @mbod has been off for a while. Would you be kind to take over?

**Comment by will-rowe** [comment]
Yes - I'll review this today in place of @mbod

**Comment by will-rowe** [comment]
@whedon remove @mbod as reviewer

**Comment by whedon** [comment]
OK, @mbod is no longer a reviewer

**Comment by will-rowe** [comment]
@whedon add @will-rowe as reviewer

**Comment by whedon** [comment]
OK, @will-rowe is now a reviewer

**Comment by will-rowe** [comment]
@whedon generate pdf

**Comment by will-rowe** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/s1473-3099(20)30120-1 may be missing for title: An interactive web-based dashboard to track COVID-19 in real time

INVALID DOIs

- None
```

**Comment by ArdiaD** [comment]
@will-rowe thx a lot for taking care of that!

**Comment by will-rowe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02376/joss.02376/10.21105.joss.02376.pdf)

**Comment by will-rowe** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/s1473-3099(20)30120-1 may be missing for title: An interactive web-based dashboard to track COVID-19 in real time

INVALID DOIs

- None
```

**Comment by will-rowe** [comment]
Hey @ArdiaD - just a couple of comments for you to respond to over at the above issue

**Comment by ArdiaD** [comment]
@will-rowe all fixed! thx again for your comments!

**Comment by will-rowe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02376/joss.02376/10.21105.joss.02376.pdf)

**Comment by will-rowe** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/S1473-3099(20)30120-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by will-rowe** [comment]
Great - thank you for your prompt responses @ArdiaD and @emanuele-guidotti 

You've addressed my comments as a reviewer, and in addition to @linuxscout's review, I think we're ready to proceed to acceptance!

As a side note, I just suggested adding a build status badge (https://github.com/covid19datahub/COVID19/pull/91), but this is not required by JOSS.

@ArdiaD - please could you now make a tagged release and archive, and report the version number and archive DOI in this thread.

**Comment by ArdiaD** [comment]
Great, thx @will-rowe 

DOI is 10.5281/zenodo.3939184

Thanks!

**Comment by will-rowe** [comment]
@whedon set 0.5281/zenodo.3939184 as archive

**Comment by whedon** [comment]
0.5281/zenodo.3939184 doesn't look like an archive DOI.

**Comment by will-rowe** [comment]
@whedon set v2.0.3 as version

**Comment by whedon** [comment]
OK. v2.0.3 is the version.

**Comment by will-rowe** [comment]
@whedon set 10.5281/zenodo.3939184 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3939184" target="_blank">10.5281/zenodo.3939184</a> is the archive.

**Comment by will-rowe** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1560

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1560, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hi @ArdiaD, we are nearly done here, but I have just a few things for you to fix in the paper:

- Please put commas between the lists on page 2 (both in the Data Collection section)
- please remove either "e.g." or "etc." in the "geographic information ..." bullet on page 2; you should only have one or the other of these

Thanks!

**Comment by ArdiaD** [comment]
hi @emanuele-guidotti could you proceed?

**Comment by emanuele-guidotti** [comment]
Should be fixed now. Thanks!

**Comment by ArdiaD** [comment]
Hi @kyleniemeyer this is fixed; thx!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02376/joss.02376/10.21105.joss.02376.pdf)

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/S1473-3099(20)30120-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1562

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1562, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1281682205073387520) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1563
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02376](https://doi.org/10.21105/joss.02376)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by ArdiaD** [comment]
thx a lot to @linuxscout @will-rowe  and @kyleniemeyer  for your help in the process!

**Comment by kyleniemeyer** [comment]
Congrats @ArdiaD and @emanuele-guidotti on your article's publication in JOSS!

Many thanks to @linuxscout and @will-rowe for reviewing this, and @will-rowe for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02376/status.svg)](https://doi.org/10.21105/joss.02376)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02376">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02376/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02376/status.svg
   :target: https://doi.org/10.21105/joss.02376
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02376/status.svg)](https://doi.org/10.21105/joss.02376)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
