### ISSUE TITLE
[PRE REVIEW]: Sit2StandPy: An Open-Source Python Package for Detecting and Quantifying Sit-to-Stand Transitions Using an Accelerometer on the Lower Back'

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2380]
**Submitting author:** @LukasAdamowicz (<a href="http://orcid.org/0000-0001-6992-9545">Lukas Adamowicz</a>)
**Repository:** <a href="https://github.com/PfizerRD/sit2standpy" target ="_blank">https://github.com/PfizerRD/sit2standpy</a>
**Version:** v1.0.0
**Editor:** @galessiorob
**Reviewers:** @jsgalan, @gweissman
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @LukasAdamowicz. **Currently, there isn't an JOSS editor assigned** to your paper.

@LukasAdamowicz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.20 s (265.8 files/s, 23302.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          30            665           1333           1843
Markdown                         4             68              0            168
TeX                              1             13              0            117
reStructuredText                14             67            116             86
DOS Batch                        1              8              1             26
YAML                             1              5             10             14
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                            52            830           1466           2263
-------------------------------------------------------------------------------


Statistical information for the repository '2380' was gathered on 2020/06/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Lukas Adamowicz                295         14545          10674          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Lukas Adamowicz            3841           26.4          7.0               10.18
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MCSE.2011.37 is OK
- 10.21105/joss.01237 is OK
- 10.5281/zenodo.3898987 is OK

MISSING DOIs

- https://doi.org/10.1088/0967-3334/33/11/1947 may be missing for title: Inertial sensor motion analysis of gait, sit–stand transfers and step-up transfers: differentiating knee patients from healthy controls
- https://doi.org/10.1016/j.jbiomech.2009.06.023 may be missing for title: Age impairs sit-to-walk motor performance
- https://doi.org/10.1016/j.gaitpost.2012.10.008 may be missing for title: Automated approach for quantifying the repeated sit-to-stand using one body fixed sensor in young and older adults
- https://doi.org/10.1186/s12984-017-0241-2 may be missing for title: Auto detection and segmentation of daily living activities during a Timed Up and Go task in people with Parkinson’s disease using multiple inertial sensors
- https://doi.org/10.1186/s12984-015-0026-4 may be missing for title: Auto detection and segmentation of physical activities during a Timed-Up-and-Go (TUG) task in healthy older adults using multiple inertial sensors
- https://doi.org/10.3389/fneur.2018.00652 may be missing for title: Validation of a Lower Back “Wearable”-Based Sit-to-Stand and Stand-to-Sit Algorithm for Patients With Parkinson’s Disease and Older Adults in a Home-Like Environment
- https://doi.org/10.1016/j.patrec.2018.03.020 may be missing for title: Probabilistic identification of sit-to-stand and stand-to-sit with a wearable sensor
- https://doi.org/10.1093/geronj/49.2.m85 may be missing for title: A Short Physical Performance Battery Assessing Lower Extremity Function: Association With Self-Reported Disability and Prediction of Mortality and Nursing Home Admission

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02380/joss.02380/10.21105.joss.02380.pdf)

**Comment by arfon** [comment]
:wave: @LukasAdamowicz - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the month we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by arfon** [comment]
@whedon invite @galessiorob as editor

:wave: @galessiorob - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by galessiorob** [comment]
@whedon start review

**Comment by galessiorob** [comment]
👋 Hi @LukasAdamowicz!

I am in the process of assigning reviewers to this submission, but if you have any suggestions for reviewers please let me know in a comment without tagging them directly.

In the meantime, it looks like you're missing some DOIs, if you want to start adding those that would be great.

Many thanks!
______________

**Basic checks:**

* [x]  There’s a general description of the software
* [x] The software is within scope as research software
* [x] OSI-approved license: MIT License

**Comment by danielskatz** [comment]
@galessiorob  - when you agree to edit a submission, you should
@whedon assign @galessiorob as editor
(or @whedon assign me as editor)
and if the submission has been waitlisted, remove the waitlist label
I'll do this now for your 2 that you agreed to edit

**Comment by danielskatz** [comment]
@whedon assign @galessiorob as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by galessiorob** [comment]
@whedon assign @jsgalan as reviewer

**Comment by whedon** [comment]
OK, @jsgalan is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @gweissmane as reviewer

**Comment by whedon** [comment]
OK, @gweissmane is now a reviewer

**Comment by galessiorob** [comment]
@whedon remove @gweissmane as reviewer

**Comment by whedon** [comment]
OK, @gweissmane is no longer a reviewer

**Comment by galessiorob** [comment]
@whedon add @gweissman as reviewer

**Comment by whedon** [comment]
OK, @gweissman is now a reviewer

**Comment by jsgalan** [comment]
Hi all, 

I made an initial install, all the requirements were satisfied


<img width="1086" alt="Screen Shot 2020-07-07 at 8 46 00 PM" src="https://user-images.githubusercontent.com/971958/86864561-04b64100-c093-11ea-93cc-ddf3a9616781.png">

Two test failed as can be seen:

<img width="940" alt="Screen Shot 2020-07-07 at 8 44 34 PM" src="https://user-images.githubusercontent.com/971958/86864603-1a2b6b00-c093-11ea-801f-da1dcee8e742.png">

<img width="938" alt="Screen Shot 2020-07-07 at 8 44 59 PM" src="https://user-images.githubusercontent.com/971958/86864637-26172d00-c093-11ea-9fce-ea6029581f25.png">

and one .h5 file was missing somehow.

<img width="1074" alt="Screen Shot 2020-07-07 at 8 45 31 PM" src="https://user-images.githubusercontent.com/971958/86864642-29121d80-c093-11ea-93a9-47a9891d62a3.png">

should this example data should be downloaded from anywhere else?

Best,

**Comment by arfon** [comment]
@galessiorob - is this one ready to move forward to the main review?

**Comment by galessiorob** [comment]
@arfon Yes! 

@whedon start review

@jsgalan the checklist will be generated for you in the review issue, thanks for diving right in!

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2449.
