### ISSUE TITLE
[REVIEW]: xrdfit: A Python package for fitting synchrotron X-ray diffraction spectra

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2381]
**Submitting author:** @merrygoat (<a href="http://orcid.org/0000-0002-5430-6924">Peter Crowther</a>)
**Repository:** <a href="https://github.com/LightForm-group/xrdfit" target ="_blank">https://github.com/LightForm-group/xrdfit</a>
**Version:** v1.1.2
**Editor:** @jgostick
**Reviewers:** @KedoKudo, @mikapfl
**Archive:** <a href="https://doi.org/10.5281/zenodo.3997251" target="_blank">10.5281/zenodo.3997251</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9e83f6fcd8df37f75d81d26772670c6b/status.svg)](https://joss.theoj.org/papers/9e83f6fcd8df37f75d81d26772670c6b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9e83f6fcd8df37f75d81d26772670c6b"><img src="https://joss.theoj.org/papers/9e83f6fcd8df37f75d81d26772670c6b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9e83f6fcd8df37f75d81d26772670c6b/status.svg)](https://joss.theoj.org/papers/9e83f6fcd8df37f75d81d26772670c6b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/LightForm-group/xrdfit" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@KedoKudo, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jgostick know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LightForm-group/xrdfit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@merrygoat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LightForm-group/xrdfit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@merrygoat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @KedoKudo it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/ZENODO.11813 is OK
- 10.1016/j.msea.2008.05.017 is OK
- 10.3390/met5042252 is OK
- 10.1016/j.msea.2016.01.059 is OK
- 10.1016/j.actamat.2017.04.028 is OK
- 10.1107/s1600576717004708 is OK
- 10.1107/s1600576715004306 is OK
- 10.1107/s1600577515002283 is OK
- 10.1107/s1600576715010390 is OK
- 10.1080/08957959608201408 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02381/joss.02381/10.21105.joss.02381.pdf)

**Comment by arfon** [comment]
@jgostick - you can add a new reviewer here (when you've identified one) with `@whedon add @reviewer2 as reviewer`. Unfortunately you'll need to do a small amount of manual work to add a checklist for the second reviewer (Whedon doesn't know how to do this yet). Any issues, let me know :-)

**Comment by jgostick** [comment]
@whedon add @mikapfl as reviewer

**Comment by whedon** [comment]
OK, @mikapfl is now a reviewer

**Comment by KedoKudo** [comment]
@jgostick - I finished my review of `xrdfit` and submitted my feedbacks to the developers on the corresponding repo (https://github.com/LightForm-group/xrdfit/issues/39, https://github.com/LightForm-group/xrdfit/issues/38).

@merrygoat and @christopher-daniel - please feel free to ping me if you have any questions about the feedbacks.

**Comment by merrygoat** [comment]
@KedoKudo Thank you very much for your feedback. I will address the feedback items individually on the issues you have raised in the `xrdfit` repository.

**Comment by jgostick** [comment]
Thanks @KedoKudo! @merrygoat can you let me know in this issue when you've made the changes?

@mikapfl, how is your review coming along?  It's only been 3 weeks, but things seem to move so fast at JOSS.

**Comment by mikapfl** [comment]
Hi,

I've been down with a cold the last week, but hope to do some progress with the review this weekend.

Cheers

Mika

**Comment by merrygoat** [comment]
Thanks @jgostick. Done the easy changes already. My colleague @christopher-daniel is on holiday this week but we will meet to resolve the outstanding issues next week.

**Comment by mikapfl** [comment]
Hi,

I've looked into the paper itself. I think it is a nice and short description of the the capabilities of `xrdfit` and motivates well what the purpose of `xrdfit` is. I found only a couple of minor things which could be clearer:
* In the first paragraph, you write:
> The experiment requires a beamline, such as Diamond Light Source […]

However, the Diamond Light Source is a synchrotron radiation facility comprising many beamlines, so this is not quite correct. Maybe something along the lines "The experiment requires a beamline at a synchrotron radiation facily such as […]" or such might be better.

* A little later you write:
> However, since many intensity profiles are collected during each
experiment, with detectors recording at speeds of up to 250 Hz (Diamond Light Source Ltd,
2020b),

Here, I think the web page of the I12 beamline at Diamond might not be an ideal citation. Maybe https://doi.org/10.1109/NSSMIC.2012.6551180 would be the best citation for the recording speeds of PILATUS3 X CdTe detectors? This is the best description of the PILATUS3 ASIC I know of. They specify a maximum frame rate of 500 Hz, which is not realized in the commercial 2M detector, which is described in detail at the web page of dectris: https://www.dectris.com/products/pilatus3/pilatus3-x-cdte-for-synchrotron/pilatus3-x-cdte-2m/ .

* In figure 2, your choice of the colours red and green for the two right axes and the lines for temperature and deformation is not optimal, because it is not colourblind-friendly. Consider using colours with different grey levels or something like dotted or dashed lines.

Best Regards,

Mika

**Comment by jgostick** [comment]
Hi  @merrygoat, did you notice the comments from @mikapfl above?  He has a few 'unchecked' boxes for you to address, but this is almost over the finish line!

**Comment by merrygoat** [comment]
Thank you yes - we have added those paper changes [here](https://github.com/LightForm-group/xrdfit/commit/72f923164bd66fb82eb92ae42f49ace08bd20053) and [here](https://github.com/LightForm-group/xrdfit/commit/434660e240a52a48e1e18f10e2fde18d184be9ed). 

We are just finishing up the last of the issues the reviewers raised, and adding a little more documentation for the data preparation step and we should be good.

**Comment by merrygoat** [comment]
That's it - I think we have addressed all of the outstanding issues. Let me know if I have missed anything!

**Comment by jgostick** [comment]
@merrygoat  Here is a list of what to do next:

- [ ] Double check authors and affiliations (including ORCIDs)
- [ ] Make a release of the software with the latest changes from the review and post the version number here. This is the version that will be used in the JOSS paper.
- [ ] Archive the release on Zenodo/figshare/etc and post the DOI here.
- [ ] Make sure that the title and author list (including ORCIDs) in the archive match those in the JOSS paper.

**Comment by merrygoat** [comment]
@jgostick Thank you.

- ORCIDs and Names checked
- Release v1.1.1 - https://github.com/LightForm-group/xrdfit/releases/tag/v1.1.1
- Zenodo DOI: 10.5281/zenodo.3991638
- Names match between Zenodo and paper

**Comment by jgostick** [comment]
@whedon set 10.5281/zenodo.3991638 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3991638" target="_blank">10.5281/zenodo.3991638</a> is the archive.

**Comment by jgostick** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/ZENODO.11813 is OK
- 10.1016/j.msea.2008.05.017 is OK
- 10.3390/met5042252 is OK
- 10.1016/j.msea.2016.01.059 is OK
- 10.1016/j.actamat.2017.04.028 is OK
- 10.1107/s1600576717004708 is OK
- 10.1107/s1600576715004306 is OK
- 10.1107/s1600577515002283 is OK
- 10.1107/s1600576715010390 is OK
- 10.1080/08957959608201408 is OK
- 10.1107/S1600576716000455 is OK
- 10.1107/S0021889869006558 is OK
- 10.1017/S0885715613001346 is OK
- 10.1109/NSSMIC.2012.6551180 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1663

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1663, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by jgostick** [comment]
Hi @merrygoat this paper is now acceptable, and an Editor in Chief will come make the final acceptance. Thanks to the reviewers for time!

**Comment by mikapfl** [comment]
In the generated pdf (https://github.com/openjournals/joss-papers/blob/5c52f575ebfaac4c6c44846620f181dd6859ae5a/joss.02381/10.21105.joss.02381.pdf) the citations at the end of the first paragraph look funny. They somehow use `[]` instead of `()` and the `Hammersley_2016` also doesn't look right.

**Comment by merrygoat** [comment]
@mikapfl Thank you - you are right, we had missed an @ symbol there. Corrected and released as version v1.1.2. 

@jgostick Is it possible to tell whedon to use another version? The updated doi is: `10.5281/zenodo.3997251`

We would also like to thank both reviewers - your comments were insightful and lead to significant improvements.

**Comment by arfon** [comment]
@whedon set v1.1.2 as version

**Comment by whedon** [comment]
OK. v1.1.2 is the version.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3997251 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3997251" target="_blank">10.5281/zenodo.3997251</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1672

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1672, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/ZENODO.11813 is OK
- 10.1016/j.msea.2008.05.017 is OK
- 10.3390/met5042252 is OK
- 10.1016/j.msea.2016.01.059 is OK
- 10.1016/j.actamat.2017.04.028 is OK
- 10.1107/s1600576717004708 is OK
- 10.1107/s1600576715004306 is OK
- 10.1107/s1600577515002283 is OK
- 10.1107/s1600576715010390 is OK
- 10.1080/08957959608201408 is OK
- 10.1107/S1600576716000455 is OK
- 10.1107/S0021889869006558 is OK
- 10.1017/S0885715613001346 is OK
- 10.1109/NSSMIC.2012.6551180 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@merrygoat These are some required steps before we proceed: 

- [ ] Please amend the archive meta data, in terms of the title and authors (you can edit this on ZENODO) such that it matches your paper (@jgostick, thanks for handling this submission. For future reference this :point_up: is a check the handling editor should also). 
- [ ] I've checked your paper and it seems in order. This work is about to be processed for acceptance. If you haven't already re-read your paper now is the time to give it a final check (in particular author names, affiliations, and acknowledgements).

**Comment by merrygoat** [comment]
@Kevin-Mattheus-Moerman Ah yes - thank you. I forgot I would have to update the metadata again with the new version. I have done that now.

I am also happy with the proof.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/ZENODO.11813 is OK
- 10.1016/j.msea.2008.05.017 is OK
- 10.3390/met5042252 is OK
- 10.1016/j.msea.2016.01.059 is OK
- 10.1016/j.actamat.2017.04.028 is OK
- 10.1107/s1600576717004708 is OK
- 10.1107/s1600576715004306 is OK
- 10.1107/s1600577515002283 is OK
- 10.1107/s1600576715010390 is OK
- 10.1080/08957959608201408 is OK
- 10.1107/S1600576716000455 is OK
- 10.1107/S0021889869006558 is OK
- 10.1017/S0885715613001346 is OK
- 10.1109/NSSMIC.2012.6551180 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1687

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1687, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1300419890998804481) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1688
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02381](https://doi.org/10.21105/joss.02381)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02381/status.svg)](https://doi.org/10.21105/joss.02381)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02381">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02381/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02381/status.svg
   :target: https://doi.org/10.21105/joss.02381
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02381/status.svg)](https://doi.org/10.21105/joss.02381)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by Kevin-Mattheus-Moerman** [comment]
Congratulations @merrygoat. 

@KedoKudo, @mikapfl thanks for reviewing this work for JOSS!
