### ISSUE TITLE
[PRE REVIEW]: hal9001: Scalable highly adaptive lasso regression in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2383]
**Submitting author:** @nhejazi (<a href="http://orcid.org/0000-0002-7127-2789">Nima Hejazi</a>)
**Repository:** <a href="https://github.com/tlverse/hal9001" target ="_blank">https://github.com/tlverse/hal9001</a>
**Version:** v0.2.6
**Editor:** @mikldk
**Reviewers:** @daviddewhurst, @rrrlw
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @nhejazi. **Currently, there isn't an JOSS editor assigned** to your paper.

nhejazi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2383 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2383 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02383/joss.02383/10.21105.joss.02383.pdf)

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.34 s (303.6 files/s, 140622.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            35           1763            486          39003
R                               33            341            912           1470
C++                              7            130            265            671
Rmd                              5            197            326            511
CSS                              3             99             48            428
Markdown                         5            102              0            373
JavaScript                       3             64             32            256
TeX                              2             24              0            233
YAML                             5             26              4            116
C/C++ Header                     3             25             26            114
XML                              1              0              0             87
make                             1              9              0             21
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                           104           2780           2100          43294
-------------------------------------------------------------------------------


Statistical information for the repository '2383' was gathered on 2020/06/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jeremy Coyle                    13          1779            843           61.01
Nima Hejazi                     21          1222            454           38.99

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jeremy Coyle                880           49.5         28.8               14.66
Nima Hejazi                 703           57.5         15.9               27.60
```

**Comment by arfon** [comment]
:wave: @nhejazi - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the month we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@nhejazi Thank you for your patience. I am editing this submission.

The references in the paper are not all properly typeset (lower/upper case letters). Can you please fix that?

Do you have any suggestions for reviewers or should I go ahead and search for reviewers?

**Comment by nhejazi** [comment]
Thank you for taking on editing of this submission, @mikldk.

We'll go ahead and fix the typos in the bibliography shortly. I don't have any suggestions for reviewers, probably best if you proceed with an initial selection.

**Comment by mikldk** [comment]
@wrathematics, @tianxzhu: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@daviddewhurst, @ihrke: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by ihrke** [comment]
sorry, going on vacation from tomorrow and won’t be back before middle of August. So I will have to let that one go...

**Comment by daviddewhurst** [comment]
@mikldk Sure, I can review this.

**Comment by mikldk** [comment]
@martinmodrak: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by martinmodrak** [comment]
@mikldk Hi, the package looks interesting and somewhat within my expertise, however I am currently leaving on vacation and I was also asked to review #2471 (which I find a bit closer to my area of interest and hence prefer for review). So realistically, I don't think I could start working on the review sooner than Aug 1st, maybe even a bit later.  If that's OK, I can review it. (I am also OK if you look for other reviewers who can react faster and fall back on me only if that fails).

**Comment by mikldk** [comment]
@mdogucu: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mdogucu** [comment]
@mikldk, thank you for thinking of me. Due to the challenges of the COVID-19 pandemic, like JOSS, I am also currently operating in a "reduced service mode".  I unfortunately am not available for reviewing this package.

**Comment by mikldk** [comment]
@paragkulkarni11, @chlalanne, @jacobsoj: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@ha0ye, @kdpeterson51, @rrrlw: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by rrrlw** [comment]
I would be happy to review.

**Comment by mikldk** [comment]
@whedon assign @daviddewhurst as reviewer

**Comment by whedon** [comment]
OK, @daviddewhurst is now a reviewer

**Comment by mikldk** [comment]
@whedon add @rrrlw as reviewer

**Comment by whedon** [comment]
OK, @rrrlw is now a reviewer

**Comment by mikldk** [comment]
Thanks, @daviddewhurst and @rrrlw . I will create the review issue shortly.

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2526.
