### ISSUE TITLE
[PRE REVIEW]: A web application to estimate differences in diagnostic efficiency based on differences between single-condition cases

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2386]
**Submitting author:** @gasparl (<a href="http://orcid.org/0000-0001-9401-4830">Gáspár Lukács</a>)
**Repository:** <a href="https://github.com/gasparl/esdi" target ="_blank">https://github.com/gasparl/esdi</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gasparl. **Currently, there isn't an JOSS editor assigned** to your paper.

@gasparl if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (189.8 files/s, 84212.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             4             32              0           4509
R                                4             19              3            528
Markdown                         3             66              0            106
TeX                              1              4              0             56
-------------------------------------------------------------------------------
SUM:                            12            121              3           5199
-------------------------------------------------------------------------------


Statistical information for the repository '2386' was gathered on 2020/06/24.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3389/fpsyg.2013.00863 is OK
- 10.1177/2515245918770963 is OK
- 10.5334/irsp.181 is OK

MISSING DOIs

- https://doi.org/10.1016/c2013-0-10517-x may be missing for title: Statistical power analysis for the behavioral sciences

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02386/joss.02386/10.21105.joss.02386.pdf)

**Comment by gasparl** [comment]
Thanks for the quick start @arfon .

Some potential reviewers from your list could be: @markhwhiteii (who I now notice did [something similar](https://github.com/markhwhiteii/power_twoway) for a different issue), @mmrabe, @lebebr01, @aj2duncan

Perhaps I should mention that I originally suggested @akeshavan as editor. (Or otherwise perhaps @mikldk.)

**Comment by arfon** [comment]
:wave: @gasparl - Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
