### ISSUE TITLE
[PRE REVIEW]: Astraea: A Python package for predicting long rotation periods from short light curves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2387]
**Submitting author:** @lyx12311 (<a href="http://orcid.org/0000-0003-4769-3273">Yuxi Lu</a>)
**Repository:** <a href="https://github.com/lyx12311/Astraea" target ="_blank">https://github.com/lyx12311/Astraea</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lyx12311. **Currently, there isn't an JOSS editor assigned** to your paper.

@lyx12311 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (231.1 files/s, 34657.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            218            289            569
TeX                              1             14              0            558
Jupyter Notebook                 1              0           1266             85
reStructuredText                 6             55             57             49
YAML                             2              0             14             33
Markdown                         1              6              0             32
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            22            305           1634           1361
-------------------------------------------------------------------------------


Statistical information for the repository '2387' was gathered on 2020/06/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Lucy Lu                          1             0             52            0.18
Yuxi Lu                         56         14722          13594           99.82

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Yuxi Lu                    1076            7.3          3.9               14.68
```

**Comment by arfon** [comment]
:wave: @lyx12311 - Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
