### ISSUE TITLE
[PRE REVIEW]: IBCAO_py: A matplotlib library for using the International Bathymetric Chart of the Arctic Ocean with cartopy and matplotlib

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#239]
**Submitting author:** @gauteh (<a href="http://orcid.org/0000-0002-5653-1447">Gaute Hope</a>)
**Repository:** <a href="https://github.com/gauteh/ibcao_py" target ="_blank">https://github.com/gauteh/ibcao_py</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @dvalters

**Author instructions**

Thanks for submitting your paper to JOSS @gauteh. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@gauteh if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@Mankoff - would you be willing to review this submission for JOSS?

**Comment by dvalters** [comment]
@arfon if not I would be happy to - quite interested in cartopy/matplotib things.

**Comment by arfon** [comment]
> @arfon if not I would be happy to - quite interested in cartopy/matplotib things.

👍 great!

**Comment by arfon** [comment]
@whedon assign @dvalters as reviewer

**Comment by arfon** [comment]
@whedon ping

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon assign @dvalters as reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @dvalters as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dvalters

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/250. Feel free to close this issue now!

**Comment by arfon** [comment]
@dvalters please head over to #250 to carry out the actual review.
