### ISSUE TITLE
[PRE REVIEW]: `reval`: a Python package to determine the best number of clusters with stability-based relative clustering validation.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2390]
**Submitting author:** @IIT-LAND (<a href="http://orcid.org/0000-0003-4212-4709">Isotta Landi</a>)
**Repository:** <a href="https://github.com/IIT-LAND/reval_clustering" target ="_blank">https://github.com/IIT-LAND/reval_clustering</a>
**Version:** v0.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @IIT-LAND. **Currently, there isn't an JOSS editor assigned** to your paper.

@IIT-LAND if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.22 s (253.2 files/s, 108392.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      12           2223           2272           8441
SVG                              1              0              0           2671
HTML                            13           1505             13           2495
CSS                              7            365             68           1379
Python                          10            140            206            540
reStructuredText                 6            252            404            183
TeX                              1             14              0            141
Markdown                         2             33              0            141
DOS Batch                        1              8              1             26
make                             2              5              7             11
-------------------------------------------------------------------------------
SUM:                            55           4545           2971          16028
-------------------------------------------------------------------------------


Statistical information for the repository '2390' was gathered on 2020/06/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
landiisotta                     14         14312            490          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
landiisotta               13822           96.6          0.7               17.07
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1016/j.patcog.2006.06.026 may be missing for title: Model-based evaluation of clustering validation measures
- https://doi.org/10.1198/106186005x59243 may be missing for title: Cluster validation by prediction strength
- https://doi.org/10.1007/springerreference_63711 may be missing for title: Clustering Validity
- https://doi.org/10.1002/nav.20053 may be missing for title: The Hungarian method for the assignment problem
- https://doi.org/10.18637/jss.v061.i06 may be missing for title: NbClust: An R Package for Determining the Relevant Number of Clusters in a Data Set
- https://doi.org/10.18637/jss.v025.i04 may be missing for title: clValid: An R Package for Cluster Validation
- https://doi.org/10.1016/0377-0427(87)90125-7 may be missing for title: Silhouettes: a graphical aid to the interpretation and validation of cluster analysis

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02390/joss.02390/10.21105.joss.02390.pdf)

**Comment by arfon** [comment]
:wave: @IIT-LAND - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the month we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by arfon** [comment]
:wave: @IIT-LAND - Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

Also, you might like to consider contributing this functionality to packages such as scikit-learn: https://github.com/scikit-learn-contrib

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
