### ISSUE TITLE
[PRE REVIEW]: argopy: A Python library for Argo ocean data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2391]
**Submitting author:** @gmaze (<a href="http://orcid.org/0000-0001-7231-2095">Guillaume Maze</a>)
**Repository:** <a href="https://github.com/euroargodev/argopy" target ="_blank">https://github.com/euroargodev/argopy</a>
**Version:** v0.1.4
**Editor:** @kthyng
**Reviewers:** @dhruvbalwada, @DamienIrving
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gmaze. **Currently, there isn't an JOSS editor assigned** to your paper.

@gmaze if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2391 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02391/joss.02391/10.21105.joss.02391.pdf)

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (543.7 files/s, 69587.2 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           28           1027           1372           3617
CSS                              36             28             70           2567
reStructuredText                 10            230            172            271
Markdown                          3             58              0            182
Jupyter Notebook                  8              0           2154            178
YAML                              5             23             27            120
JSON                              1              1              0             86
JavaScript                        1              1              8             26
HTML                              2              0             25             20
Bourne Again Shell                2              5              4             15
--------------------------------------------------------------------------------
SUM:                             96           1373           3832           7082
--------------------------------------------------------------------------------


Statistical information for the repository '2391' was gathered on 2020/06/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Guillaume Maze                 166         13031           7838           93.27
quai20                          40          1217            289            6.73

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Guillaume Maze             5584           42.9          1.3               14.11
quai20                      466           38.3          1.2               12.88
```

**Comment by kthyng** [comment]
Hi! As the resident oceanographer I am happy to edit this submission. Thanks for your submission!

**Comment by kthyng** [comment]
@whedon assign kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @gmaze! Do you have any suggestions for reviewers, either from [this list](https://bit.ly/joss-reviewers) or elsewhere? Please don't use the "@" to mention them here to limit extraneous email.

**Comment by gmaze** [comment]
Hi @kthyng 
Thanks for being our editor !

Possible reviewers from the list:
- edoddridge
- malmans2
- ali-ramadhan
- callumrollo
- koldunovn
- bradyrx
- DamienIrving

Elsewhere:
-  Loïc Houpert: lhoupert
-  Pedro Vélez: PedroVelez 
- Dhruv Balwada: dhruvbalwada

**Comment by kthyng** [comment]
Thanks @gmaze!

**Comment by kthyng** [comment]
@dhruvbalwada are you interested in reviewing this submission to JOSS? We are asking for reviews within about 6 weeks currently. You can see how the process goes here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by kthyng** [comment]
Also have an email request out currently to another potential reviewer.

**Comment by dhruvbalwada** [comment]
Yes, it will be fun to review this. How do I get started?

**Comment by kthyng** [comment]
@dhruvbalwada excellent! I'll assign you as reviewer to start, and we'll wait here in the pre-review until I get a second reviewer. After we have two reviewers, I'll start the actual review issue. This one will be closed, and everything else will happen there. There will be a checklist for you to follow, in addition to information in the docs, and you can always ask me questions too. Generally, though, issues that need or can be addressed should go into separate issues that are linked into the review issue. So, wait for now and I'll let you know when we move to the next stage!

**Comment by kthyng** [comment]
@whedon assign @dhruvbalwada as reviewer

**Comment by whedon** [comment]
OK, @dhruvbalwada is now a reviewer

**Comment by kthyng** [comment]
@DamienIrving are you interested in reviewing this submission for JOSS? We are asking for reviews in about 6 weeks.

**Comment by DamienIrving** [comment]
@kthyng Sure thing. I'd be happy to review 😄

**Comment by kthyng** [comment]
@DamienIrving awesome! I’ll add you as a reviewer now and then start up the review issue.

**Comment by kthyng** [comment]
@Whedon add @DamienIrving as reviewer

**Comment by whedon** [comment]
OK, @DamienIrving is now a reviewer

**Comment by kthyng** [comment]
@Whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2425.

**Comment by kthyng** [comment]
@dhruvbalwada and @DamienIrving head over time the new issue for the review. Thanks!
