### ISSUE TITLE
[REVIEW]: Implicit measures with reproducible results: The implicitMeasures package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2394]
**Submitting author:** @OttaviaE (<a href="http://orcid.org/0000-0001-8552-568X">Ottavia M. Epifania</a>)
**Repository:** <a href="https://github.com/OttaviaE/implicitMeasures/" target ="_blank">https://github.com/OttaviaE/implicitMeasures/</a>
**Version:** v0.2.0
**Editor:** @oliviaguest
**Reviewer:** @eirini-zormpa, @wjakethompson, @jflournoy
**Archive:** <a href="https://doi.org/10.5281/zenodo.3961817" target="_blank">10.5281/zenodo.3961817</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4216c9905f79a183a02a801e9d256be1/status.svg)](https://joss.theoj.org/papers/4216c9905f79a183a02a801e9d256be1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4216c9905f79a183a02a801e9d256be1"><img src="https://joss.theoj.org/papers/4216c9905f79a183a02a801e9d256be1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4216c9905f79a183a02a801e9d256be1/status.svg)](https://joss.theoj.org/papers/4216c9905f79a183a02a801e9d256be1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/OttaviaE/implicitMeasures/tree/master" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@eirini-zormpa & @wjakethompson & @jflournoy, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @oliviaguest know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/OttaviaE/implicitMeasures">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@OttaviaE) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/OttaviaE/implicitMeasures">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@OttaviaE) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/OttaviaE/implicitMeasures/tree/master">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@OttaviaE) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @eirini-zormpa, @wjakethompson, @jflournoy it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2394 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2394 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by oliviaguest** [comment]
Hi everybody! @eirini-zormpa, @wjakethompson, @jflournoy — welcome to where the review itself is going to be.

Any questions please ask me. Any very code-related issues use the repo of the code and open an issue and link to it from here. All other issues, feedback, questions for me or the author, please use this issue. Anything you need, check above first as there is a lot of into up there, but also please feel free to ask me. 😸

Thank you all again and I hope this is a nice experience for us all! 🌼 🌸

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02394/joss.02394/10.21105.joss.02394.pdf)

**Comment by wjakethompson** [comment]
Hi @oliviaguest!

This is very minor, but the `repository_url` link in the checklist is taking me to [`implicitMeasures/inst/`](https://github.com/OttaviaE/implicitMeasures/tree/master/inst) instead of the main repo page (i.e., [`implicitMeasures`](https://github.com/OttaviaE/implicitMeasures)). This doesn't bother me at all, but thought I'd drop a note in case it was indicative of some mistake in the metadata that may cause problems down the line.

**Comment by oliviaguest** [comment]
Ah, yes! @danielskatz noticed this (and even called this) previously. I'll tag @openjournals/dev see what they say and how it can be fixed. I manually edited it above in one place (see history of OP), but that might not be enough.

**Comment by xuanxu** [comment]
If the url is corrected in the issue body that should be enough. The paper compiler extracts the info from there.

**Comment by OttaviaE** [comment]
Hi @wjakethompson and @oliviaguest the paper is in implicitMeasures/inst/ instead of the main repo implicitMeasures beacuse the package and its repository is available on CRAN and CRAN dosen't allow anything else to be on the leel but a folder named "inst"

**Comment by oliviaguest** [comment]
@OttaviaE does the PDF look OK at least?

**Comment by OttaviaE** [comment]
@oliviaguest it does!

**Comment by xuanxu** [comment]
Yeah, the paper files can be located anywhere in the repo, whedon will look for them in all subfolders.

**Comment by oliviaguest** [comment]
@xuanxu thank you for all your help and checking this is all OK. 🌼

**Comment by danielskatz** [comment]
I fixed the 2 links in the checklist items for "repository URL"

**Comment by OttaviaE** [comment]
@danielskatz thank you =)

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02394/joss.02394/10.21105.joss.02394.pdf)

**Comment by OttaviaE** [comment]
Hey @oliviaguest, I noticed that there is a part of the code that is truncated (nothing important actually). Can I commit the changes in the md file so that the code is not truncated anymore?

**Comment by oliviaguest** [comment]
@OttaviaE yes, you can make any edits and then you can ask @whedon like I did above to compile the pdf again! ☺️

**Comment by OttaviaE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02394/joss.02394/10.21105.joss.02394.pdf)

**Comment by OttaviaE** [comment]
@oliviaguest thank you =)

**Comment by eirini-zormpa** [comment]
I have completed my review. As far as I can tell, everything is well-document and works as intended!

**Comment by oliviaguest** [comment]
> I have completed my review. As far as I can tell, everything is well-document and works as intended!

Fabulous @eirini-zormpa, thank you! Can you tick/check off the last few boxes above in the OP, please, then? ☺️

**Comment by eirini-zormpa** [comment]
> 
> 
> > I have completed my review. As far as I can tell, everything is well-document and works as intended!
> 
> Fabulous @eirini-zormpa, thank you! Can you tick/check off the last few boxes above in the OP, please, then? ☺️

oops sorry, I thought I had 😬 done now!

**Comment by oliviaguest** [comment]
Terrific! Perfect — thank you. 👏

**Comment by OttaviaE** [comment]
Thank you @eirini-zormpa =)

**Comment by oliviaguest** [comment]
Ah, and for the benefit of the other reviewers (and myself):

* https://github.com/OttaviaE/implicitMeasures/issues/3
* https://github.com/OttaviaE/implicitMeasures/issues/2

**Comment by eirini-zormpa** [comment]
thank you for inviting me, this was a really nice experience 😊

**Comment by oliviaguest** [comment]
Hey @wjakethompson, @jflournoy can you give a rough ETA on your reviews, please? 🌼

**Comment by wjakethompson** [comment]
I will hopefully finish up today, but by end of day on Friday at the latest. Thanks!

**Comment by wjakethompson** [comment]
I've completed my review and overall I think it looks great! I have two open issues, one that is super minor and is not acceptance blocker (OttaviaE/implicitMeasures#4), and one that I think is a little more important and should be considered prior to publication (OttaviaE/implicitMeasures#5). I'm happy to answer any questions as you look through my suggestions!

**Comment by OttaviaE** [comment]
Thanks @wjakethompson, your suggestions were really useful and I think they improved the package. I pushed all the code modifcations and the data sets for the replicability check on Git Hub, so you can have a look at them if you wish. However, I'll wait for the comments of the other reviewer before submitting the package with the new features on CRAN. Thanks again =)

**Comment by wjakethompson** [comment]
Everything looks good to me! I think I've completed everything in my check list, but @oliviaguest let me know if I missed anything. Thanks for inviting me to participate!

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02394/joss.02394/10.21105.joss.02394.pdf)

**Comment by oliviaguest** [comment]
Thank you so much @wjakethompson for the review. @jflournoy would you be able to give us a rough ETA? 

@OttaviaE are you currently making any edits, additions, etc? 😊

**Comment by OttaviaE** [comment]
Hey @oliviaguest nope, not now. I edited the code as @wjakethompson (thank you =)) suggested, pushed the changes on GitHub and that's all so far.
Thanks!

**Comment by oliviaguest** [comment]
OK, let's give @jflournoy a week or so to reply and then I'll email him.

**Comment by jflournoy** [comment]
Please pardon my delay and not seeing the above messages! I've opened three new issues. The first is in regard to the unit tests, two of which fail on my machine. I'm happy to dig deeper if this is not reproducible on your end, @OttaviaE. 

https://github.com/OttaviaE/implicitMeasures/issues/6

I'm not sure if this is the right way to do this, but here are a few recommendations for the language in the paper:
https://github.com/OttaviaE/implicitMeasures/issues/7

And finally, some minor suggestions on function naming that may help users remember the names of and find the functions they're looking for: 

https://github.com/OttaviaE/implicitMeasures/issues/8

**Comment by OttaviaE** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02394/joss.02394/10.21105.joss.02394.pdf)

**Comment by jflournoy** [comment]
Okay, @oliviaguest, I believe all boxes are checked. Thank you so much, @OttaviaE, for being so responsive; I'm glad my suggestions were harmonious with your goals for this software and the paper. And more so, thanks for writing this package!

**Comment by OttaviaE** [comment]
Thank you so much @jflournoy I really appreciated your help and suggestions, they definetly improved `implicitMeasures` =)
Thanks

**Comment by oliviaguest** [comment]
@jflournoy oooh! fabulous! thank you for all this! 🥳

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by oliviaguest** [comment]
@OttaviaE can you deposit the code in a repository (on Zenodo, figshare, or other) and post the archive DOI here?

**Comment by OttaviaE** [comment]
@oliviaguest of course! it should be https://doi.org/10.5281/zenodo.3961817 but I guess it still has to be activated

**Comment by OttaviaE** [comment]
@oliviaguest it appears that the archive DOI is finally active!

**Comment by oliviaguest** [comment]
Oh, perfect! @OttaviaE Can you make the title of the zenodo repo be exactly: ` Implicit measures with reproducible results: The implicitMeasures package`, please?

**Comment by OttaviaE** [comment]
@oliviaguest of course! done

**Comment by oliviaguest** [comment]
@whedon set 10.5281/zenodo.3961817 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3961817" target="_blank">10.5281/zenodo.3961817</a> is the archive.

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02394/joss.02394/10.21105.joss.02394.pdf)

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1037/0022-3514.85.2.197 is OK
- 10.1080/19312458.2015.1096330 is OK
- 10.1037/1089-2699.6.1.101 is OK
- 10.1037/0022-3514.74.6.1464 is OK
- 10.1037/0022-3514.91.1.16 is OK
- 10.1177/0146167216684131 is OK
- 10.21105/joss.01764 is OK
- 10.4473/TPM27.2.4 is OK
- 10.31124/advance.11914416.v1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1605

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1605, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by oliviaguest** [comment]
@openjournals/joss-eics please do the thing! 💖

**Comment by kthyng** [comment]
Hi @OttaviaE! I see the title of your package at Zenodo is the same as your paper title – excellent – but can you also have the author list match your paper?

Also, can I verify the version that you want associated with your JOSS submission? It looks to me like it should be v0.2.0?

**Comment by kthyng** [comment]
I'll just note here that there is an issue that is still [open](https://github.com/OttaviaE/implicitMeasures/issues/7) that appears to be associated with this review that I am waiting to hear back about.

**Comment by OttaviaE** [comment]
Hey @kthyng! I added my co-authors on Zenodo, but I also left @oliviaguest in the author list. 

Regarding the version, yes, the version associated to my joss submission is version v0.2.0

**Comment by kthyng** [comment]
@OttaviaE and @oliviaguest Is @oliviaguest being added as an author of this submission?

**Comment by kthyng** [comment]
@whedon set v0.2.0 as version

**Comment by whedon** [comment]
OK. v0.2.0 is the version.

**Comment by oliviaguest** [comment]
I do not think I should be an author. Why am I being added as an author? 😅

**Comment by OttaviaE** [comment]
@oliviaguest I actually don't know! I found your name as an author on Zenodo, but I didn't do it!

**Comment by oliviaguest** [comment]
@OttaviaE Oh, please edit me to be not an author. 😆

**Comment by OttaviaE** [comment]
Okay @oliviaguest, I removed your name from the authors list on Zenodo!

**Comment by oliviaguest** [comment]
Fab! @openjournals/joss-eics I think we're good to go?

**Comment by danielskatz** [comment]
I'll process this in an hour or so - thanks

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1037/0022-3514.85.2.197 is OK
- 10.1080/19312458.2015.1096330 is OK
- 10.1037/1089-2699.6.1.101 is OK
- 10.1037/0022-3514.74.6.1464 is OK
- 10.1037/0022-3514.91.1.16 is OK
- 10.1177/0146167216684131 is OK
- 10.21105/joss.01764 is OK
- 10.4473/TPM27.2.4 is OK
- 10.31124/advance.11914416.v1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1615

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1615, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@OttaviaE -  can you merge the small changes in https://github.com/OttaviaE/implicitMeasures/pull/10 ?  Then we can finish the acceptance

**Comment by OttaviaE** [comment]
@danielskatz done!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1037/0022-3514.85.2.197 is OK
- 10.1080/19312458.2015.1096330 is OK
- 10.1037/1089-2699.6.1.101 is OK
- 10.1037/0022-3514.74.6.1464 is OK
- 10.1037/0022-3514.91.1.16 is OK
- 10.1177/0146167216684131 is OK
- 10.21105/joss.01764 is OK
- 10.4473/TPM27.2.4 is OK
- 10.31124/advance.11914416.v1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1618

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1618, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1290320308856119296) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1619
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02394](https://doi.org/10.21105/joss.02394)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @eirini-zormpa & @wjakethompson & @jflournoy for reviewing and @oliviaguest for editing!

Congratulations @OttaviaE (Ottavia M. Epifania) and co-authors!!

**Comment by danielskatz** [comment]
@openjournals/dev  - while the DOI is resolving, the PDF does not seem to load - can you check?

**Comment by labarba** [comment]
GitHub pages sometimes has delays refreshing. This is normal.

**Comment by danielskatz** [comment]
It's now there!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02394/status.svg)](https://doi.org/10.21105/joss.02394)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02394">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02394/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02394/status.svg
   :target: https://doi.org/10.21105/joss.02394
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02394/status.svg)](https://doi.org/10.21105/joss.02394)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by oliviaguest** [comment]
Congratulations @OttaviaE! 🥳 

Massive thanks to @eirini-zormpa, @wjakethompson, @jflournoy, for their useful and constructive feedback! 👏

**Comment by eirini-zormpa** [comment]
> 
> 
> Congratulations @OttaviaE! 🥳
> 
> Massive thanks to @eirini-zormpa, @wjakethompson, @jflournoy, for their useful and constructive feedback! 👏

Congratulations @OttaviaE 🎉

**Comment by OttaviaE** [comment]
@danielskatz thank you!

And also, thank you @eirini-zormpa, @jflournoy, and @wjakethompson for your kind and useful comments, you all definetly helped in improving my package =)
Of course, thank you @oliviaguest for being such a great editor!
