### ISSUE TITLE
[PRE REVIEW]: cerebra: A tool for fast and accurate summarizing of variant calling format (VCF) files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2396]
**Submitting author:** @lincoln-harris (<a href="http://orcid.org/0000-0003-2544-4225">Lincoln Harris</a>)
**Repository:** <a href="https://github.com/czbiohub/cerebra" target ="_blank">https://github.com/czbiohub/cerebra</a>
**Version:** v1.1.0
**Editor:** @lpantano
**Reviewers:** @betteridiot, @afrubin
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lincoln-harris. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @lpantano.

@lincoln-harris if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1093/bioinformatics/btl647 may be missing for title: Nested Containment List (NCList): a new algorithm for accelerating interval query of genome alignment and interval databases
- https://doi.org/10.1093/bioinformatics/btp324 may be missing for title: Fast and accurate short read alignment with Burrows-Wheeler Transform
- https://doi.org/10.1016/j.cell.2017.09.004 may be missing for title: Single-Cell Analysis of Human Pancreas Reveals Transcriptional Signatures of Aging and Somatic Mutation Patterns
- https://doi.org/10.1038/s41587-019-0074-6 may be missing for title: An open resource for accurately benchmarking small variant and reference calls
- https://doi.org/10.1038/nbt.2835 may be missing for title: Integrating human sequence data sets provides a resource of benchmark SNP and indel genotype calls
- https://doi.org/10.1101/201178 may be missing for title: Scaling accurate genetic variant discovery to tens of thousands of samples
- https://doi.org/10.1186/s13059-017-1248-5 may be missing for title: BRIE: transcriptome-wide splicing quantification in single cells

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.20 s (243.8 files/s, 33401.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          23            820            639           2034
RobotFramework                   1              0              0           1400
Markdown                         7            222              0            592
make                             3             73             53            291
DOS Batch                        1             29              1            212
YAML                             3              1              0            150
TeX                              1             10              0             68
reStructuredText                 9             36             29             48
Dockerfile                       1              2              0              4
-------------------------------------------------------------------------------
SUM:                            49           1193            722           4799
-------------------------------------------------------------------------------


Statistical information for the repository '2396' was gathered on 2020/06/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Lincoln Harris                 161         11421           9338           78.62
Olga Botvinnik                   1             1             15            0.06
Rohan Vanheusden                73          2785           1038           14.48
Ubuntu                          32           888            919            6.84

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Lincoln Harris             1941           17.0          1.9               18.39
Olga Botvinnik                1          100.0          1.3                0.00
Rohan Vanheusden           1551           55.7         10.7                9.09
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02396/joss.02396/10.21105.joss.02396.pdf)

**Comment by kthyng** [comment]
Hi @lincoln-harris!

Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the month we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by lpantano** [comment]
@kthyng, I can edit that if you don't have another person in mind :)

**Comment by kthyng** [comment]
Sounds great @lpantano! Thanks!

**Comment by kthyng** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1093/bioinformatics/btl647 may be missing for title: Nested Containment List (NCList): a new algorithm for accelerating interval query of genome alignment and interval databases
- https://doi.org/10.1093/bioinformatics/btp324 may be missing for title: Fast and accurate short read alignment with Burrows-Wheeler Transform
- https://doi.org/10.1016/j.cell.2017.09.004 may be missing for title: Single-Cell Analysis of Human Pancreas Reveals Transcriptional Signatures of Aging and Somatic Mutation Patterns
- https://doi.org/10.1038/s41587-019-0074-6 may be missing for title: An open resource for accurately benchmarking small variant and reference calls
- https://doi.org/10.1038/nbt.2835 may be missing for title: Integrating human sequence data sets provides a resource of benchmark SNP and indel genotype calls
- https://doi.org/10.1101/201178 may be missing for title: Scaling accurate genetic variant discovery to tens of thousands of samples
- https://doi.org/10.1186/s13059-017-1248-5 may be missing for title: BRIE: transcriptome-wide splicing quantification in single cells

INVALID DOIs

- None
```

**Comment by lpantano** [comment]
@lincoln-harris, can you make sure all the references has DOI, please?

**Comment by lpantano** [comment]
@chrisleitzinger, I found your profile in GitHub and I thought you may be interested on reviewing this nice VCF reader tool. This are the guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks!

**Comment by lpantano** [comment]
hey @naumenko-sa, I think you may be interested in reviewing this tool? let me know!

**Comment by lpantano** [comment]
hey @Adrianzo, @afrubin, @betteridiot, @Nazeeefa, would any of you like to review this paper?

**Comment by betteridiot** [comment]
I would be happy to review this @lpantano

**Comment by afrubin** [comment]
@lpantano Happy to review this as well.

**Comment by lpantano** [comment]
@whedon assign @betteridiot as reviewer

**Comment by whedon** [comment]
OK, @betteridiot is now a reviewer

**Comment by lpantano** [comment]
@whedon add @afrubin as reviewer

**Comment by whedon** [comment]
OK, @afrubin is now a reviewer

**Comment by lpantano** [comment]
Thanks both, I will start the review process then!

**Comment by lpantano** [comment]
@whedon star review

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2432.

**Comment by Nazeeefa** [comment]
Hi, I'd be happy to review/test it @lpantano

**Comment by lpantano** [comment]
Hi @Nazeeefa, I got two reviewers here, but I need one more for this other tool: https://github.com/openjournals/joss-reviews/issues/2410 would you be up for that one? It is a visualization tool of metabolomic data. It would be great to have you there!

**Comment by Nazeeefa** [comment]
Hi @lpantano No worries. Sorry, I'm afraid I have to say no as I do not know much about that topic. Thank you for asking. I appreciate your time and work.
