### ISSUE TITLE
[PRE REVIEW]: `swiftsimio`: A python library for reading SWIFT data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2397]
**Submitting author:** @JBorrow (<a href="http://orcid.org/0000-0002-1327-1921">Josh Borrow</a>)
**Repository:** <a href="https://github.com/swiftsim/swiftsimio" target ="_blank">https://github.com/swiftsim/swiftsimio</a>
**Version:** v4.0.0
**Editor:** @dfm
**Reviewers:** @dmentipl, @mtremmel
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JBorrow. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @harpolea.

@JBorrow if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.02 s (236.8 files/s, 19654.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2             27              0            156
TeX                              1             10              0            116
JSON                             1              0              0             23
-------------------------------------------------------------------------------
SUM:                             4             37              0            295
-------------------------------------------------------------------------------


Statistical information for the repository '2397' was gathered on 2020/06/26.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1088/0067-0049/192/1/9 is OK
- 10.1111/j.1365-2966.2005.09655.x is OK
- 10.21105/joss.00809 is OK
- 10.1145/2929908.2929916 is OK
- 10.1093/mnras/stu2058 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02397/joss.02397/10.21105.joss.02397.pdf)

**Comment by kthyng** [comment]
Hi @JBorrow!

Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the month we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by kthyng** [comment]
Also, @JBorrow, can you state here what the repo is that contains your submission?

**Comment by JBorrow** [comment]
Ah - apologies - I had tried to use the yaml metadata at the top... But must have done something wrong.

The submission is at https://github.com/swiftsim/swiftsimio and docs at swiftsimio.readthedocs.org.

**Comment by kthyng** [comment]
Ok, I updated the site above. 

@openjournals/dev at this pre-review stage, does this repo name need to be updated in the system so that it is properly used in the review?

**Comment by arfon** [comment]
@JBorrow - could you move the contents of this repository (https://github.com/SWIFTSIM/swiftsimio-joss-paper) into https://github.com/swiftsim/swiftsimio. It can be in a separate branch if you like.

**Comment by arfon** [comment]
Also, @JBorrow - could you tell me if this submission is associated with a paper in a AAS journal?

**Comment by arfon** [comment]
@whedon invite @dfm as editor 

:wave: @dfm - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by JBorrow** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02397/joss.02397/10.21105.joss.02397.pdf)

**Comment by JBorrow** [comment]
I have moved the paper inside the main repo into the `joss-paper` branch.

**Comment by JBorrow** [comment]
> Also, @JBorrow - could you tell me if this submission is associated with a paper in a AAS journal?

This is not associated with any submission in an AAS journal, no - it is a standalone JOSS submission.

**Comment by JBorrow** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.23 s (341.3 files/s, 50936.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          59           2047           3284           4480
reStructuredText                12            393            540            538
Markdown                         3             57              0            223
DOS Batch                        1              8              1             26
YAML                             1              3              0             13
make                             1              4              7              9
Bourne Shell                     1              2              1              6
-------------------------------------------------------------------------------
SUM:                            78           2514           3833           5295
-------------------------------------------------------------------------------


Statistical information for the repository '2397' was gathered on 2020/06/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aidan Chalk                      3           229             43            1.47
Alexei Borissov                 97          4409           1804           33.55
Folkert Nobels                   1             3              3            0.03
JBorrow                          9           172             81            1.37
Jacob Kegerreis                  1             2              0            0.01
Josh Borrow                    227          9259           2512           63.57

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aidan Chalk                 152           66.4         14.7                7.89
Alexei Borissov            2940           66.7          1.6                6.60
Folkert Nobels                2           66.7         15.7                0.00
Jacob Kegerreis               2          100.0         16.7                0.00
Josh Borrow                6537           70.6          8.4               11.93
```

**Comment by dfm** [comment]
@arfon: yes - I'm happy to edit!

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@JBorrow: Based on an initial skim of the paper: can you double check the HDF and pnbody citations? They don't seem to have all the necessary BibTeX info.

**Comment by JBorrow** [comment]
Thanks, I've updated them. I used the 'official' HDF citation but this had 1997-NNNN in it's date field, I have changed this to just be 1997.

I've changed pnbody to use their ASCL citation.

**Comment by JBorrow** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02397/joss.02397/10.21105.joss.02397.pdf)

**Comment by dfm** [comment]
@whedon assign @dmentipl as reviewer

**Comment by whedon** [comment]
OK, @dmentipl is now a reviewer

**Comment by dfm** [comment]
@dmentipl has agreed to be one of the reviewers - thanks Daniel!

Once we have a second reviewer, I'll get the main review started.

**Comment by JBorrow** [comment]
Great, thanks! As this is generally a post-processing code I am happy to provide some more exciting snapshots for the reviewers to use, should they wish. They can also alternatively use the data downloaded for the unit tests, but this is quite boring (essentially a uniform box).

**Comment by dfm** [comment]
@whedon add @mtremmel as reviewer

**Comment by whedon** [comment]
OK, @mtremmel is now a reviewer

**Comment by dfm** [comment]
We have our two reviewers (thanks, Michael!) so I'll start the main review thread and we can head over there to complete the review. If any of you have questions as we go please don't hesitate to ask!

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2430.
