### ISSUE TITLE
[PRE REVIEW]: matchms - processing and similarity evaluation of mass spectrometry data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2398]
**Submitting author:** @florian-huber (<a href="http://orcid.org/0000-0002-3535-9406">Florian Huber</a>)
**Repository:** <a href="https://github.com/matchms/matchms" target ="_blank">https://github.com/matchms/matchms</a>
**Version:** 0.4.0
**Editor:** @arfon
**Reviewers:** @bittremieux, @kaibioinfo
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @florian-huber. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @will-rowe.

@florian-huber if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.46 s (262.1 files/s, 45937.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              4              1              1          13639
Python                          98           1383            943           3436
YAML                             9             29             10            504
Markdown                         3             82              0            291
TeX                              1             18              0            281
reStructuredText                 3            115            223            132
JSON                             1              0              0             66
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           121           1640           1185          18384
-------------------------------------------------------------------------------


Statistical information for the repository '2398' was gathered on 2020/06/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christiaan Meijer                8            80            108            0.16
Cunliang Geng                    4           137             93            0.20
Faruk D                         24          5133           4764            8.63
Florian Huber                   29           131             52            0.16
Jurriaan H. Spaaks             274         39754          43823           72.90
Stefan Verhoeven                36           466            148            0.54
florian-huber                  351         14280           5684           17.41

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Christiaan Meijer            14           17.5          1.0                0.00
Faruk D                      36            0.7          2.4                5.56
Jurriaan H. Spaaks         2285            5.7          1.6                4.03
Stefan Verhoeven            394           84.5          0.5                7.36
florian-huber              3033           21.2          0.6                9.10
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/nbt.3597 is OK
- 10.1073/pnas.1203689109 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1021/acs.jproteome.8b00717 is OK
- 10.1093/nar/gkz1019 is OK
- 10.1002/jms.1777 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
- 10.1021/jasms.8b04453 is INVALID
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02398/joss.02398/10.21105.joss.02398.pdf)

**Comment by kthyng** [comment]
Hi @florian-huber!

Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the month we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by florian-huber** [comment]
Reviewers from the list that could fit both topic-wise (Cheminformatics, mass spectroscopy) and language-wise (Python):

- hannahbrucemacdonald
- abotzki
- mberacochea
- thesketh
- RMeli
- bovee

Further suggestions (not from the list): 
- lfnothias
- mwang87

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @thesketh @hannahbrucemacdonald, @lfnothias - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by thesketh** [comment]
Hi @arfon, unfortunately I'm just about to change jobs so I'm a bit overloaded at the moment! In any case, I'm not sure I know enough about mass spectrometry to review this.

**Comment by lfnothias** [comment]
Dear editing team of JOSS, I prefer to decline as I am not an expert in software/python. However, let me connect you with the most qualified reviewers for that submission. @bittremieux @kaibioinfo

**Comment by arfon** [comment]
Thanks @lfnothias! 

@bittremieux @kaibioinfo - would you both be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by bittremieux** [comment]
Yes, I'm willing to review this work.

**Comment by arfon** [comment]
@whedon add @bittremieux as reviewer

**Comment by whedon** [comment]
OK, @bittremieux is now a reviewer

**Comment by arfon** [comment]
> Yes, I'm willing to review this work.

Thanks @bittremieux! I'll start the main review issue once we have a second reviewer assigned here too. In the meantime, feel free to take a look at our reviewer documentation here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by kaibioinfo** [comment]
Hi, yes I can review this work.

**Comment by arfon** [comment]
@whedon add @kaibioinfo as reviewer

**Comment by arfon** [comment]
@whedon add @kaibioinfo as reviewer

**Comment by whedon** [comment]
OK, @kaibioinfo is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2411.

**Comment by arfon** [comment]
@bittremieux, @kaibioinfo - many thanks for agreeing to review this submission, see you over in #2411 where the actual review will take place.
