### ISSUE TITLE
[PRE REVIEW]: CoBaye: Correlation by Bayesian Inference

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2399]
**Submitting author:** @pedrorfigueira (<a href="http://orcid.org/0000-0001-8504-283X">Pedro Figueira</a>)
**Repository:** <a href="https://github.com/pedrorfigueira/CoBaye" target ="_blank">https://github.com/pedrorfigueira/CoBaye</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pedrorfigueira. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@pedrorfigueira if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (255.7 files/s, 45827.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             93            159            194
Markdown                         2             42              0             87
Jupyter Notebook                 4              0            862             86
TeX                              1              6              0             84
-------------------------------------------------------------------------------
SUM:                             9            141           1021            451
-------------------------------------------------------------------------------


Statistical information for the repository '2399' was gathered on 2020/06/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
pedrorfigueira                   5           492             46          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
pedrorfigueira              446           90.7          0.1                9.42
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s11084-016-9490-5 is OK
- 10.1109/MCSE.2011.37 is OK

MISSING DOIs

- None

INVALID DOIs

- http://doi.org/10.1525/collabra.78 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.7717/peerj-cs.55 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1109/MCSE.2007.55 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02399/joss.02399/10.21105.joss.02399.pdf)

**Comment by kthyng** [comment]
Hi @pedrorfigueira!

Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the month we've had a very large number of papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by arfon** [comment]
👋 @pedrorfigueira - Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
