### ISSUE TITLE
[PRE REVIEW]: Pandarus: GIS toolkit for regionalized life cycle assessment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#240]
**Submitting author:** @cmutel (<a href="http://orcid.org/0000-0002-7898-9862">Chris Mutel</a>)
**Repository:** <a href="https://github.com/cmutel/pandarus" target ="_blank">https://github.com/cmutel/pandarus</a>
**Version:** 1.0.1
**Editor:** @arfon
**Reviewer:** @hugoledoux

**Author instructions**

Thanks for submitting your paper to JOSS @cmutel. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@cmutel if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cmutel** [comment]
@jsta, @nuest, @sgrieve or especially @hugoledoux - would any of you have time for this? Nothing too revolutionary, buts fills a specific needs in a research community that is not very geographically-aware.

**Comment by sgrieve** [comment]
I'd be happy to review this, but am happy to give @hugoledoux first refusal.

**Comment by arfon** [comment]
> I'd be happy to review this, but am happy to give @hugoledoux first refusal.

👍 thanks @sgrieve. @hugoledoux - would you interested in helping out with this?

**Comment by hugoledoux** [comment]
Yes I will.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @hugoledoux as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hugoledoux

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/244. Feel free to close this issue now!

**Comment by arfon** [comment]
@hugoledoux - many thanks for agreeing to review this submission. Please head over to #244 where the review should take place.
