### ISSUE TITLE
[PRE REVIEW]: Science Capsule - Capturing the Data Life Cycle

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2401]
**Submitting author:** @dghoshal-lbl (<a href="http://orcid.org/0000-0002-6819-6949">Devarshi Ghoshal</a>)
**Repository:** <a href="https://bitbucket.org/sciencecapsule/sciencecapsule" target ="_blank">https://bitbucket.org/sciencecapsule/sciencecapsule</a>
**Version:** v0.1.0
**Editor:** @pibion
**Reviewers:** @cmbiwer
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @dghoshal-lbl. **Currently, there isn't an JOSS editor assigned** to your paper.

@dghoshal-lbl if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2401 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2401 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2401 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:153:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:153:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:151:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:151:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2401 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:153:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:153:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:151:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:151:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:88:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@dghoshal-lbl - please remove the blank `orcid` entries for the two authors:

```
 - name: Abdelilah Essiari
   orcid: 
   affiliation: 1
 - name: Michael Beach
   orcid: 
   affiliation: "1, 2"
```

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (353.0 files/s, 52135.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          41           1446            410           3861
JSON                             5              0              0           1143
JavaScript                       3            140             36            621
Markdown                         4            233              0            512
HTML                             1             60              4            360
CSS                              2             32              2            132
Ruby                             1             28             12            106
Dockerfile                       2             43             13             85
Bourne Shell                     1             18              7             65
YAML                             3              2              8             63
TeX                              1              1              0             10
-------------------------------------------------------------------------------
SUM:                            64           2003            492           6958
-------------------------------------------------------------------------------


Statistical information for the repository '2401' was gathered on 2020/06/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ludovico Bianchi               173         11901           9046           68.58
Michael Beach                    3           867              0            2.84
abessiari                        2             7              0            0.02
dghoshal-lbl                    31          5781           2920           28.49
unknown                          2            16              5            0.07

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Abdelilah Essiari             7          100.0          0.8                0.00
Ludovico Bianchi           5652           47.5          1.8                5.68
dghoshal-lbl                855           14.8         13.4                7.84
```

**Comment by arfon** [comment]
@whedon invite @pibion as editor

:wave: @pibion - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@pibion has been invited to edit this submission.

**Comment by dghoshal-lbl** [comment]
> @dghoshal-lbl - please remove the blank `orcid` entries for the two authors:
> 
> ```
>  - name: Abdelilah Essiari
>    orcid: 
>    affiliation: 1
>  - name: Michael Beach
>    orcid: 
>    affiliation: "1, 2"
> ```

@arfon I have removed the blank orcid entries.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02401/joss.02401/10.21105.joss.02401.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @dghoshal-lbl - can you explain how this is research software that will be cited by users, as opposed to infrastructure software (like operating systems and compilers) that is important to research but is not research software?

**Comment by pibion** [comment]
@whedon assign @pibion as editor

**Comment by whedon** [comment]
OK, the editor is @pibion

**Comment by pibion** [comment]
:wave: @dghoshal-lbl I have the same question as @danielskatz.

**Comment by danielskatz** [comment]
👋 @pibion - FYI, I was holding off on inviting any editors for this submission until the research application was clear, since if we decide this is not research software, we will reject it as out-of-scope for JOSS. I'm happy you've volunteered, but please keep me in the loop for the time being.

**Comment by dghoshal-lbl** [comment]
@danielskatz @pibion Science Capsule has been built to support experimental, observation, and simulation workflows. Reproducibility and reusability are increasingly becoming critical for research experiments. Existing methods are ad-hoc and often do not include the associated metadata and processing information that is necessary for data to be usable. Science Capsule provides the foundation that is necessary for making research experiments and results reproducible and reusable. The software is aimed at capturing and organizing the artifacts of a research experiment for improving the knowledge and understanding about the experiment and its data. Our prototype software is currently being used in the context of workflows from Advanced Light Source and Materials Project.

**Comment by danielskatz** [comment]
@dghoshal-lbl - I don't think you answered my question:

> Can you explain how this is research software that will be cited by users, as opposed to infrastructure software (like operating systems and compilers) that is important to research but is not research software?

**Comment by LRamakrishnan** [comment]
@danielskatz -  I guess we are a bit confused since we are trying to understand how exactly you define research software. ScienceCapsule is a toolkit that allows users to capture events related to their workflow. It is meant to be a user-level research software that complements science user’s scripts and tools. It is definitely not infrastructure software by design but presumably someone could setup a service around it long-term. Right now it is meant to be downloaded by users and used with their research workflows. I would put it closer to the category of monitoring or workflow tools. I looked at recent JOSS entries and here are some that I would say are similar category to what ScienceCapsule does. 

GridTest: testing and metrics collection for Python
Jabberwocky: an ontology-aware toolkit for manipulating text
niacin: A Python package for text data enrichment
profileR: An R package for profile analysis 

Let us know if this isn’t in scope for JOSS and we will withdraw.

**Comment by danielskatz** [comment]
@LRamakrishnan - This might or might not be in scope for JOSS, but I'm still uncertain about this because the question I am asking, about how this will be cited by users, is still unclear to me.
Would you expect a user to cite this software in the methods section of their research paper? 
Are there examples of users who have cited or discussed this software in their research papers?

For context, in https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements, we describe the scope requirements for JOSS papers, which include

- The software should have an **obvious** research application.
- The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler).

And we say
> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar.

**Comment by LRamakrishnan** [comment]
@danielskatz - Thanks! I did read the submission requirements earlier. It is a good question. I would expect people to cite this in the methods section of their paper, if they were to use it. But nope, we do not have an example yet.

**Comment by danielskatz** [comment]
Ok, let's go ahead with the review and see if reviewers bring this up.  If so, we can revisit it then. Sorry for the delay.

@pibion - over to you to proceed...

**Comment by pibion** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by pibion** [comment]
:wave: @dghoshal-lbl I'm in the process of inviting reviewers for this submission.  This can take somewhere between a few days to a few weeks, I'll keep you updated on this thread.

**Comment by pibion** [comment]
@whedon assign @colbrydi as reviewer

**Comment by whedon** [comment]
OK, @colbrydi is now a reviewer

**Comment by pibion** [comment]
@whedon assign @cmbiwer as reviewer

**Comment by whedon** [comment]
OK, @cmbiwer is now a reviewer

**Comment by pibion** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2484.
