### ISSUE TITLE
[REVIEW]: ‘Bioassays’; a new package in R for analyzing cellular assays

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2402]
**Submitting author:** @anwarbio (<a href="http://orcid.org/0000-0002-1693-1219">ANWAR PALAKKAN</a>)
**Repository:** <a href="https://github.com/anwarbio/bioassays" target ="_blank">https://github.com/anwarbio/bioassays</a>
**Version:** v1.0.1
**Editor:** @fboehm
**Reviewers:** @tomsing1, @homonecloco
**Archive:** <a href="https://doi.org/10.5281/zenodo.4075110" target="_blank">10.5281/zenodo.4075110</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/68721e17fcb3d07413631c8d395dff5c/status.svg)](https://joss.theoj.org/papers/68721e17fcb3d07413631c8d395dff5c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/68721e17fcb3d07413631c8d395dff5c"><img src="https://joss.theoj.org/papers/68721e17fcb3d07413631c8d395dff5c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/68721e17fcb3d07413631c8d395dff5c/status.svg)](https://joss.theoj.org/papers/68721e17fcb3d07413631c8d395dff5c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/anwarbio/bioassays" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tomsing1, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @fboehm know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/anwarbio/bioassays">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@anwarbio) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?

The vignettes needed proofreading. I have suggested changes and submitted [a pull request](https://github.com/anwarbio/bioassays/pull/4) for the author to review. (I also included a few other minor suggestions in the pull request, which he might find useful.)

- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/anwarbio/bioassays">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@anwarbio) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tomsing1 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2402 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2402/paper.md): mapping values are not allowed in this context at line 2 column 17 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@anwarbio - your paper title needs quoting, i.e. change this: `title: Bioassays: a new package in R for analyzing cellular assays` to this `title: "Bioassays: a new package in R for analyzing cellular assays"` in your `paper.md`.

**Comment by anwarbio** [comment]
@arfon - The above change is made in the `title`  of `paper.md`

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02402/joss.02402/10.21105.joss.02402.pdf)

**Comment by anwarbio** [comment]
@whedon, @arfon 
Few mistakes were in the `article proof`, and is now corrected in `paper.md`. 
Details of the correction are
1)` Line 25` 1st paragraph last line: _high-throughput_ is corrected as _High-throughput_
2) `Line 27` 2nd paragraph 3rd line: _us_ is corrected as _use_
3) `Line 29` 3rd paragraph 1st line: _server_ is corrected as _serve_
4) `Line 39` 7th paragraph 1st line: An extra _convert_ is deleted.
Thanking you,
Anwar

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by fboehm** [comment]
Thanks, @anwarbio.

**Comment by fboehm** [comment]
@whedon remove homoneclocom as reviewer

**Comment by whedon** [comment]
OK, homoneclocom is no longer a reviewer

**Comment by fboehm** [comment]
@whedon add @homonecloco as reviewer

**Comment by whedon** [comment]
OK, @homonecloco is now a reviewer

**Comment by tomsing1** [comment]
@fboehm I think I waited too long to accept the https://github.com/openjournals/joss-reviews/invitations invite. Would you mind refreshing it so I can edit the checklist? Many thanks!

**Comment by danielskatz** [comment]
@whedon re-invite @tomsing1 as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@tomsing1 please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by homonecloco** [comment]
Hi @anwarbio , 
I started the review with the documentation. I am still to read the paper, but I'll give you my comments of what I have reviewed so far, so you can consider them. 


1. The API documentation (https://cran.r-project.org/web/packages/bioassays/bioassays.pdf)  has the beginning looking incomplete or misformated. The documentation of the actual functions seems ok, but having so many NA at the beginning of the document is not recommended. 
2. The vignette with examples (https://cran.r-project.org/web/packages/bioassays/vignettes/bioassays-examples.html) refers to some files, like  “L DIFF P3 72HRS.csv”. I couldn’t find that file in the repository. I appreciate that the examples may be included as part of the package, but for this particular document, having the actual file used can help the users to format their tables. 
3. In some packages, the documentation is in html and in PDF. It would be useful to have the same option for the vignettes of this packages. The PDFs are hard to copy and paste.

**Comment by anwarbio** [comment]
Hi **@homonecloco** 

Thank you for reviewing the package and your suggestions are really helpful in improving the package. I have made the below changes in github files. Once all are happy with contents, then I can go for an update on CRAN with all changes.  

1. The API documentation (https://cran.r-project.org/web/packages/bioassays/bioassays.pdf) has the beginning looking incomplete or misformated. The documentation of the actual functions seems ok, but having so many NA at the beginning of the document is not recommended.
**comment: I have now corrected this**

2. The vignette with examples (https://cran.r-project.org/web/packages/bioassays/vignettes/bioassays-examples.html) refers to some files, like “L DIFF P3 72HRS.csv”. I couldn’t find that file in the repository. I appreciate that the examples may be included as part of the package, but for this particular document, having the actual file used can help the users to format their tables.
**comment: All the files used in the examples are now added in the exdata folder and is now mentioned in 'vignette with examples'**

3. In some packages, the documentation is in html and in PDF. It would be useful to have the same option for the vignettes of this packages. The PDFs are hard to copy and paste.
**comment: The vignettes are in html format. Adding both html and pdf file might be difficult as the images of  'heatplate' appear in different dimensions in pdf and html.  I might need separate rmd files for html and pdf, I doubt if CRAN will allow this.**

Thanking you,
Amwar

**Comment by homonecloco** [comment]
Hi @anwarbio , 
Thanks for making the updates so fast. Is there a way I can preview them? Specially I would like to see the NAs go away. In any case, I see you uploaded the file, and it is fine if you only have the html documentation. As long it is available in either format, in an easy to copy and paste (so you can test that the commands are working as expected), is fine. 
Best, 
Ricardo.

**Comment by anwarbio** [comment]
Hi @homonecloco ,
Thank you for the reply. I have made few more edits today to put each function in separate line (you can see them in the github). I do not know how to share the preview file, so I have shared you a screenshot showing the functions arranged neatly. 
Thanking you,
Anwar

![Picture1](https://user-images.githubusercontent.com/7861503/86975899-41586a00-c171-11ea-8957-75ea84540b56.jpg)

**Comment by fboehm** [comment]
@tomsing1 and @homonecloco - I hope that your reviews are going well. Please feel free to complete the checklists when you're satisfied with the submission and to suggest revisions until you're satisfied. Please let me know how I might help.

**Comment by fboehm** [comment]
@tomsing1 and @homonecloco - I see that @tomsing1 opened three issues in the package repository: https://github.com/anwarbio/bioassays

 @anwarbio responded to the three issues - should we consider the issues closed? Or is more discussion needed? 

Thanks again!

**Comment by homonecloco** [comment]
In general, I like the extensions to ggplot to display the plates. I can see this plots useful by themselves. It is nice to have some functions that force the structure of the data to the input of the plots, but I don’t think it is completely necessary for a user proficient in R. 

- There is a contradiction when comparing the software with DRfit. I would remove the comparison, as DRfit is designed to be user friendly. It may not scale well, but it is not designed for programmers. Also, in the last part of the summary, Bioassays claims to be customisable by anyone using R, which is equivalent to knowing Java to extend Drift. 

- The core text oversells the usability of the packages. It is indeed consistent with the user experience that you would get in R, but it is not as “user-friendly” as a graphical interfase. I would tone down the language. For example, the phrase "Since even the most naive computer users know how to change the names of files, this provides a very simple way to pass data of this type into the analysis.”, reads condescending. 

- In Acknowledgment, the frase "Support from lab members are acknolegment.” Has a spelling error, and it is not clear which lab members are acknloedege, or at least to which research group. 

- The contributions.md stats that there is continues integration in Travis, can you make the link more accessible, to be able to monitor if the current state of the code is running?

**Comment by anwarbio** [comment]
Hi @homonecloco,

Thank you for the comments. I have made correction as suggested. Details are given below.

1.  In general, I like the extensions to ggplot to display the plates. I can see this plots useful by themselves. It is nice to have some functions that force the structure of the data to the input of the plots, but I don’t think it is completely necessary for a user proficient in R.
**Reply: Any multi-well plate data can be structured for the plots (function 'heatplate') by using functions 'data2plateformat', 'plate2df', 'matrix96' alone or in combinations (depending on the input data). I have included this as a new sentence in line 41**

2. There is a contradiction when comparing the software with DRfit. I would remove the comparison, as DRfit is designed to be user friendly. It may not scale well, but it is not designed for programmers. Also, in the last part of the summary, Bioassays claims to be customisable by anyone using R, which is equivalent to knowing Java to extend Drift.
**Reply: In line 29 the sentence  "They are also limited to the options provided by the software, unless a user is willing to write additional JAVA code, a skill not particularly common among cell biologists" is now removed.**

3. The core text oversells the usability of the packages. It is indeed consistent with the user experience that you would get in R, but it is not as “user-friendly” as a graphical interfase. I would tone down the language. For example, the phrase "Since even the most naive computer users know how to change the names of files, this provides a very simple way to pass data of this type into the analysis.”, reads condescending.
**Reply: This sentence (line 37) is now modified as "This function provides a very easy way to pass data of this type into the analysis by simply editing file names."  Another sentence in line 31 (Moreover, it is strongly documented in a manner designed to be easy for even beginners to grasp.) is modified as "Moreover, we have provided examples (bioassays-examples) in the vignettes, which will be very helpful for beginners to grasp how this package can be used."**

4. In Acknowledgment, the frase "Support from lab members are acknolegment.” Has a spelling error, and it is not clear which lab members are acknloedege, or at least to which research group.
**Reply: The spelling mistake in acknowledgment is now corrected. Lab details are also provided (line 50).**

5. The contributions.md stats that there is continues integration in Travis, can you make the link more accessible, to be able to monitor if the current state of the code is running?
**Reply: The link is now updated.**


Thanking you,
Anwar

**Comment by fboehm** [comment]
@anwarbio thank you for the updates! @homonecloco and @tomsing1 - Thanks for your work with the reviews. If you find that you can't yet check some of the boxes in the checklist, please continue to suggest improvements. Please let me know if I can help with anything. Thanks again!!

**Comment by homonecloco** [comment]
@fboehm , can you produce the PDF again, so I can check the changes?

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2402 with the following error: 

 pandoc-citeproc: reference homonecloco not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.331 }

Looks like we failed to compile the PDF

**Comment by fboehm** [comment]
@anwarbio - I failed to produce the pdf. It looks like there's a problem with pandoc-citeproc. By chance did you use the text  "@homonecloco" somewhere in your document? If so, you might need to specify that you aren't intending to cite the key "homonecloco" in your text. You might be able to do this by preceding the at sign by two backslashes, but I could be mistaken on that.

**Comment by arfon** [comment]
I can fix the issue here folks, looks like Pandoc is getting confused with the reviewer handles and citations. Pls hold...

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02402/joss.02402/10.21105.joss.02402.pdf)

**Comment by fboehm** [comment]
Thanks, @arfon !

**Comment by fboehm** [comment]
@homonecloco and @tomsing1 - we have the updated pdf now. What are your feelings about it and the package in the current state? As you work through the last of the checklists, please feel free to continue offering suggestions for improvement as needed, and please do let me know how I can assist you. Thanks again!!

**Comment by fboehm** [comment]
@homonecloco and @tomsing1 - I hope that your reviews are progressing well. Is there something that I can assist with right now? With help from Arfon, we've created the pdf. Do you feel that additional revisions are needed? Are there any checkboxes that need attention from @anwarbio ? Thanks again!!

**Comment by fboehm** [comment]
@tomsing1 and @homonecloco - It seems that there hasn't been much activity on this review over the last couple of weeks. When you have a moment, would you see if you're comfortable with checking more of the boxes from the checklist? If you're not comfortable checking some boxes, we should be sure that @anwarbio is aware of your concerns. Thanks again!

**Comment by homonecloco** [comment]
Hi, 
I'm sorry for not commenting earlie. I'm mostly satisfied now. The only thing missing from the guideline is a community guideline on how to contribute to the project. A simple statement in the main readme should be enough. 

Best, 
Ricardo.

**Comment by anwarbio** [comment]
Hi,
@homonecloco Thank you very much.  I have now added a paragraph on contribute in readme.

Kind regards,
Anwar

**Comment by homonecloco** [comment]
@anwarbio , thanks for the prompt update. 
@fboehm , I can canfirm that, from my side, this project meets all the requirements in the guideline.

**Comment by anwarbio** [comment]
Hi  @tomsing1 ,
Please let me know the concerns you may have. I am happy to consider them and make necessary modifications.
Thanks,
Anwar

**Comment by fboehm** [comment]
Thanks, @homonecloco, for your review! @tomsing1 - how is your review progressing? Please let me know if I can assist with something. Thanks again!

**Comment by tomsing1** [comment]
Dear @fboehm and @anwarbio, I have now finished my review. (Thank you for your patience.) I suggested a few improvements in [this pull request](https://github.com/anwarbio/bioassays/pulls). I mainly corrected spelling or grammar mistakes in the vignettes and also added the `.Rbuildignore` file. (I also found one last typo in the paper itself.) The manuscript now fulfills all of the requirements on the list. Good to go!

**Comment by anwarbio** [comment]
Dear @tomsing1 , Thank you very much for the corrections. I have now applied these changes. 
Thanks!

**Comment by fboehm** [comment]
Thank you, @tomsing1 and @anwarbio !

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02402/joss.02402/10.21105.joss.02402.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02402/joss.02402/10.21105.joss.02402.pdf) :page_facing_up: :point_left:

**Comment by fboehm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10295-006-0086-3 is OK
- 10.1002/em.22014 is OK
- 10.1007/978-1-4939-2742-5_11 is OK
- 10.1016/j.bios.2015.05.018 is OK
- 10.1038/srep42383 is OK
- 10.1093/bioinformatics/btr664 is OK
- 10.1186/s12859-019-2891-5 is OK

MISSING DOIs

- None

INVALID DOIs

- NBK144065 is INVALID
```

**Comment by fboehm** [comment]
@anwarbio - whedon suggests that NBK144065 is an invalid doi. Can you double-check this doi?

**Comment by anwarbio** [comment]
@fboehm - This is a eBook reference and do not have a doi. Reference is now corrected

**Comment by fboehm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10295-006-0086-3 is OK
- 10.1002/em.22014 is OK
- 10.1007/978-1-4939-2742-5_11 is OK
- 10.1016/j.bios.2015.05.018 is OK
- 10.1038/srep42383 is OK
- 10.1093/bioinformatics/btr664 is OK
- 10.1186/s12859-019-2891-5 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02402/joss.02402/10.21105.joss.02402.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02402/joss.02402/10.21105.joss.02402.pdf) :page_facing_up: :point_left:

**Comment by anwarbio** [comment]
@fboehm -  I have fixed this by removing the word "Journal Article". 
Also I have double checked all the dois hyperlink. I can confirm you that all of them are working and directing to correct article.
Thanks

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02402/joss.02402/10.21105.joss.02402.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02402/joss.02402/10.21105.joss.02402.pdf) :page_facing_up: :point_left:

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02402/joss.02402/10.21105.joss.02402.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02402/joss.02402/10.21105.joss.02402.pdf) :page_facing_up: :point_left:

**Comment by anwarbio** [comment]
@fboehm - Figures are now corrected. Thanks

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02402/joss.02402/10.21105.joss.02402.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02402/joss.02402/10.21105.joss.02402.pdf) :page_facing_up: :point_left:

**Comment by fboehm** [comment]
@anwarbio - the reviewers have recommended your submission for publication. Before we accept it, I need you to make an archive and a Github tagged release. Once you do that, please comment here with the doi of the archive and the version number for the tagged release. Please double-check that the archive has the same author and same title as your submission.

**Comment by anwarbio** [comment]
@fboehm - Thank you very much for the wonderful review and accepting the paper for publication. The doi and version number is given below.
doi: 10.5281/zenodo.4075110 , link: https://doi.org/10.5281/zenodo.4075110
version: v1.0.1

Thanks,
Anwar

**Comment by fboehm** [comment]
@whedon set 10.5281/zenodo.4075110 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4075110" target="_blank">10.5281/zenodo.4075110</a> is the archive.

**Comment by fboehm** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by fboehm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10295-006-0086-3 is OK
- 10.1002/em.22014 is OK
- 10.1007/978-1-4939-2742-5_11 is OK
- 10.1016/j.bios.2015.05.018 is OK
- 10.1038/srep42383 is OK
- 10.1093/bioinformatics/btr664 is OK
- 10.1186/s12859-019-2891-5 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1795

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1795, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
Ok I can take over from here! I see that the version and Zenodo archive are taken care of! Paper looks good too. We can move forward.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1314975187318853640) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1796
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02402](https://doi.org/10.21105/joss.02402)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @anwarbio!  Thanks to editor @fboehm and reviewers @tomsing1 and @homonecloco for your time and expertise!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02402/status.svg)](https://doi.org/10.21105/joss.02402)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02402">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02402/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02402/status.svg
   :target: https://doi.org/10.21105/joss.02402
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02402/status.svg)](https://doi.org/10.21105/joss.02402)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
