### ISSUE TITLE
[REVIEW]: Talisman: a JavaScript archive of fuzzy matching, information retrieval and record linkage building blocks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2405]
**Submitting author:** @Yomguithereal (<a href="http://orcid.org/0000-0003-4916-8472">Guillaume Plique</a>)
**Repository:** <a href="https://github.com/Yomguithereal/talisman" target ="_blank">https://github.com/Yomguithereal/talisman</a>
**Version:** 1.1.3-zenodo
**Editor:** @kakiac
**Reviewer:** @Fil, @atanikan
**Archive:** <a href="https://doi.org/10.5281/zenodo.4247869" target="_blank">10.5281/zenodo.4247869</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4f169de181f43c9dbf6b368dab7cea52/status.svg)](https://joss.theoj.org/papers/4f169de181f43c9dbf6b368dab7cea52)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4f169de181f43c9dbf6b368dab7cea52"><img src="https://joss.theoj.org/papers/4f169de181f43c9dbf6b368dab7cea52/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4f169de181f43c9dbf6b368dab7cea52/status.svg)](https://joss.theoj.org/papers/4f169de181f43c9dbf6b368dab7cea52)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Yomguithereal/talisman" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Fil & @atanikan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kakiac know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Yomguithereal/talisman">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Yomguithereal) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Yomguithereal/talisman">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Yomguithereal) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Fil, @atanikan it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02405/joss.02405/10.21105.joss.02405.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/MEDITEC.2016.7835390 is OK
- 10.1145/358027.358048 is OK
- 10.1109/SEQUEN.1997.666900 is OK
- 10.1145/1963405.1963487 is OK

MISSING DOIs

- https://doi.org/10.1007/3-540-45735-6_24 may be missing for title: String matching with metric trees using an approximate distance
- https://doi.org/10.1145/363958.363994 may be missing for title: A technique for computer detection and correction of spelling errors
- https://doi.org/10.2307/1932409 may be missing for title: Measures of the amount of ecologic association between species
- https://doi.org/10.1080/00182494.1976.10112645 may be missing for title: Surname spellings and computerized record linkage
- https://doi.org/10.1111/j.1469-8137.1912.tb05611.x may be missing for title: The distribution of the flora in the alpine zone. 1
- https://doi.org/10.1080/01621459.1989.10478785 may be missing for title: Advances in record-linkage methodology as applied to matching the 1985 census of Tampa, Florida
- https://doi.org/10.1002/sim.4780140510 may be missing for title: Probabilistic linkage of large public health data files
- https://doi.org/10.6028/nbs.sp.500-2 may be missing for title: Accessing individual records from personal data files using non-unique identifiers
- https://doi.org/10.1016/0022-2836(81)90087-5 may be missing for title: Identification of common molecular subsequences
- https://doi.org/10.2307/1532326 may be missing for title: FONEM: Un code de transcription phonétique pour la reconstitution automatique des familles saguenayennes
- https://doi.org/10.1109/itcc.2002.1000354 may be missing for title: Improving precision and recall for soundex retrieval
- https://doi.org/10.1145/2348828.2348830 may be missing for title: Hybrid matching algorithm for personal names
- https://doi.org/10.1002/(sici)1097-4571(199301)44:1<1::aid-asi1>3.0.co;2-1 may be missing for title: Stemming of French words based on grammatical categories
- https://doi.org/10.1002/(sici)1097-4571(1999)50:10<944::aid-asi9>3.0.co;2-q may be missing for title: A stemming procedure and stopword list for general French corpora
- https://doi.org/10.1108/eb026966 may be missing for title: A stemming algorithm for Latin text databases
- https://doi.org/10.1145/101306.101310 may be missing for title: Another stemmer
- https://doi.org/10.1162/coli.2006.32.4.485 may be missing for title: Unsupervised multilingual sentence boundary detection

INVALID DOIs

- None
```

**Comment by kakiac** [comment]
@whedon re-invite @atanikan as reviewer

**Comment by whedon** [comment]
@atanikan already has access.

**Comment by kakiac** [comment]
👋  @Fil many thanks for your comments - @yomguithereal can you let us know once you have addressed @Fil 's comments?

@atanikan let me know if you need any help with the reviewing process - the review criteria you need to follow are outlined here: https://joss.readthedocs.io/en/latest/review_criteria.html and a useful checklist is above (with comments and explanations here: https://joss.readthedocs.io/en/latest/review_checklist.html) feel free to check the boxes directly!

Many thanks all for all your hard work in improving the library and the paper,

**Comment by Yomguithereal** [comment]
> @Yomguithereal can you let us know once you have addressed @Fil 's comments?

Sure, I will tell you when this is done. I first need to find a little bit of time to do so, hope there is no time limit on this :) Thanks for reviewing the library.

**Comment by atanikan** [comment]
@kakiac Thanks for the reminder :)
@Yomguithereal The installation works. I checked some of your functions and they work well. Minor suggestions, Personally I'd find it more intuitive to do 
`var talis = require('talisman'); 
talis.metrics.cosine([1,2],[3,4]);`
over
`var cos = require('talisman/metrics/cosine'); 
cos([1,2],[3,4]);` 
I guess the [issue](https://github.com/Yomguithereal/talisman/issues/10) does speak to it.
A comparative benchmark study as mentioned [here](https://github.com/Yomguithereal/talisman/issues/170) which can also be added to your documentation website would be super useful.

**Comment by Yomguithereal** [comment]
> I guess the issue does speak to it.

Yes the issue is indeed about this point. The reason why this was implemented thusly, in the beginning, is because it was written at a time where tree-shaking bundler were not yet a thing and since the library is really heavy on its own, it was the only way to make sure people would only require pieces of it on a need-to basis. But I agree this is somewhat unnecessary when using the library in node.js

I will add a centralized endpoint in a near future but I need some time to be sure I can do so while supporting ES6 imports, CommonJS & TypeScript which is unfortunately always a drag.

> A comparative benchmark study as mentioned here which can also be added to your documentation website would be super useful.

This issue (imprecisely) refer to the fact that you can use the library to benchmark several methods such as phonetic encoders against a database of, say, given names. I was not refering to performance benchmark against other similar libraries. Is that what you had in mind?

**Comment by atanikan** [comment]
> I will add a centralized endpoint in a near future but I need some time to be sure I can do so while supporting ES6 imports, CommonJS & TypeScript which is unfortunately always a drag.

That's fair! I guess we can pass on it for now.

> This issue (imprecisely) refer to the fact that you can use the library to benchmark several methods such as phonetic encoders against a database of, say, given names. I was not referring to performance benchmark against other similar libraries. Is that what you had in mind?

Then yes, I meant performance benchmarking with other similar libraries. I understand Talisman aims to be an archive/collection of several text-based search/information retrieval techniques. And not exactly a brand new algorithm. I however feel some benchmarking, be it in terms of accuracy or speed of execution by taking a large dataset as an example, may prove to be useful for wider use and a greater acceptance of your library.

**Comment by kakiac** [comment]
Thanks all!

@Yomguithereal, re this:
> hope there is no time limit on this :) 

No, please take your time to implement the changes as suggested by the reviewers - once you are happy (and the reviewers are happy 😃 ) we can move the submission forward to the next step!

**Comment by Yomguithereal** [comment]
Hello @labarba. Sorry for the delay. I haven't progressed much but I should be able to find time to do so in september. Times indeed are tough :). Thanks for enquiring.

**Comment by kakiac** [comment]
@whedon remind @Yomguithereal in two weeks

**Comment by whedon** [comment]
Reminder set for @Yomguithereal in two weeks

**Comment by whedon** [comment]
:wave: @Yomguithereal, please update us on how things are progressing here.

**Comment by kakiac** [comment]
👋 @Yomguithereal - hope you are well! I am just following up to see how things are progressing with implementing the reviewer's suggestions? Let me know if there is something I can do to help our end :) Hope you are well 👍

**Comment by Yomguithereal** [comment]
Hello @kakiac. I should have some time thursday to act on those suggestions. So far I need to update the paper to change its framing a bit, add some references to similar tools and switch to a leaner bibliography (as opposed to the one containing all of the papers describing the implemented functions and methods). I also have some one related to the library's packaging. I would like to address those but later since it is very time consuming.

**Comment by Yomguithereal** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02405/joss.02405/10.21105.joss.02405.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02405/joss.02405/10.21105.joss.02405.pdf) :page_facing_up: :point_left:

**Comment by Yomguithereal** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02405/joss.02405/10.21105.joss.02405.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02405/joss.02405/10.21105.joss.02405.pdf) :page_facing_up: :point_left:

**Comment by Yomguithereal** [comment]
@atanikan I have added a note regarding module imports and `require` [here](https://yomguithereal.github.io/talisman/).

Regarding:

> Then yes, I meant performance benchmarking with other similar libraries. I understand Talisman aims to be an archive/collection of several text-based search/information retrieval techniques. And not exactly a brand new algorithm. I however feel some benchmarking, be it in terms of accuracy or speed of execution by taking a large dataset as an example, may prove to be useful for wider use and a greater acceptance of your library.

There exists some speed benchmarks regarding some functions of the library (notably Levenshtein distance, because this library was used as an experimental starting point for the creation of many very fast implementation of the distance in JavaScript) but for most of the method there is nothing to benchmark against because nobody implemented those functions.

Regarding precision/recall etc. the issue here is that the relevant databases that could enable such benchmarks don't exist yet because most of those methods were created as heuristics geared toward the resolution of particular problems and so it made no sense to most of their authors to compare them to others. This said, I believe there is a point to be made regarding some classes of functions present in the library such as phonetic algorithms geared towards proper names and their precision/recall. I personally intend to develop such a benchmark and I have started created a database that could be used for this purpose (along with another phonetic algorithm I am developing right now), but unfortunately this is an ongoing work which won't be finished anywhere soon.

This said, do you want me to, at least, try to compile some speed benchmarks regarding a subset of the library's functions that have some other JavaScript implementations?

**Comment by Fil** [comment]
My review is complete. Thank you @Yomguithereal!

**Comment by atanikan** [comment]
> This said, do you want me to, at least, try to compile some speed benchmarks regarding a subset of the library's functions that have some other JavaScript implementations?

It's fine. I see the article does speak to the fact that one can benchmark if they would like. Since the article nor the library makes an outright claim to have the "fastest"/"best". I suppose we can benchmarking stats for now. Appreciate the changes made in the documentation as well. @kakiac My review is complete as well. Thanks, @Yomguithereal. Fantastic job.

**Comment by kakiac** [comment]
@atanikan @Fil @Yomguithereal thank you so much for all your efforts and hard work on this! A fantastic submission :) I will now be initiating final checks and push through the last editorial steps for publication.

**Comment by kakiac** [comment]
**Editor's "After reviewers recommend acceptance" checks:**
 - [ ] Get a new proof with the @whedon generate pdf command.
 - [ ] Download the proof, check all references have DOIs, follow the links and check the references.
 - [ ] Whedon can help check references with the command @whedon check references
 - [ ] Proof-read the paper and ask authors to fix any remaining typos, badly formed citations, awkward wording, etc..
 - [ ] Ask the author to make a tagged release and archive, and report the version number and archive DOI in the review thread.
 - [ ] Check the archive deposit has the correct metadata (title and author list), and request the author edit it if it doesn’t match the paper.
 - [ ] Run @whedon set <doi> as archive.
 - [ ] Run @whedon set <v1.x.x> as version if the version was updated.
 - [ ] Run @whedon accept to generate the final proofs, which has Whedon notify the @openjournals/joss-eics team that the paper is ready for final processing.
 - [ ] Mention EiC to take over

**Comment by kakiac** [comment]
@whedon generate pdf

**Comment by kakiac** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02405/joss.02405/10.21105.joss.02405.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02405/joss.02405/10.21105.joss.02405.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-642-31164-2 is OK

MISSING DOIs

- 10.1111/j.1469-8137.1912.tb05611.x may be a valid DOI for title: The distribution of the flora in the alpine zone. 1
- 10.1007/0-387-69505-2 may be a valid DOI for title: Data quality and record linkage techniques

INVALID DOIs

- None
```

**Comment by Yomguithereal** [comment]
I pushed a commit adding the missing DOIs to the paper's bibliography.

**Comment by kakiac** [comment]
Thanks @Yomguithereal!

**Comment by Yomguithereal** [comment]
Sorry, what do you mean by "archive the repo"?

**Comment by kakiac** [comment]
@Yomguithereal apologies - I should have been clearer - Upon successful completion of the review, you need to make a tagged release of the software (via github, see here for info https://git-scm.com/book/en/v2/Git-Basics-Tagging), and deposit a copy of the repository with a data-archiving service such as Zenodo or figshare.

You then need to get the DOI you will be assigned from them (it is automatically assigned once you create a repository).

As soon as you have both copy the release version number (from github) and the DOI in this thread.

See here for more info under section **The review process** https://joss.readthedocs.io/en/latest/submitting.html#submitting-your-paper - let me know if you need any help!

**Comment by kthyng** [comment]
@kakiac Please wait to ping openjournals/joss-eics until a submission is ready to be taken over, if possible. Just saves a little bit of email traffic for us. Your last checkbox isn't needed since that happens with `@whedon accept`.

**Comment by Yomguithereal** [comment]
@kakiac the release is `1.1.3-zenodo` and the attached DOI is `10.5281/zenodo.4247869` (but the [https://doi.org/10.5281/zenodo.4247869](https://doi.org/10.5281/zenodo.4247869) url does not yet work as I write this message. I guess it is just Zenodo lag?).

**Comment by kakiac** [comment]
Yes, no worries it worked for me just now, I think it takes some time to get registered in the doi database, I think. Thanks for doing that!

**Comment by kakiac** [comment]
> @kakiac Please wait to ping openjournals/joss-eics until a submission is ready to be taken over, if possible. Just saves a little bit of email traffic for us. Your last checkbox isn't needed since that happens with `@whedon accept`.

Oh apologies! I thought I needed to get that tagged if accepted by reviewers! Will bear that in mind in the future!

**Comment by kthyng** [comment]
@kakiac Your list looks correct now! Thanks!

**Comment by kakiac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02405/joss.02405/10.21105.joss.02405.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02405/joss.02405/10.21105.joss.02405.pdf) :page_facing_up: :point_left:

**Comment by kakiac** [comment]
@whedon set 1.1.3-zenodo as version

**Comment by whedon** [comment]
OK. 1.1.3-zenodo is the version.

**Comment by kakiac** [comment]
@Yomguithereal not sure if you spotted my message above - it seems that the authors list of your JOSS paper and the zenodo archive does not match. Can you please make sure they align?

**Comment by kakiac** [comment]
@whedon set 10.5281/zenodo.4247869 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4247869" target="_blank">10.5281/zenodo.4247869</a> is the archive.

**Comment by Yomguithereal** [comment]
Is this ok now?

**Comment by kakiac** [comment]
Yes, thank you :)

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.1469-8137.1912.tb05611.x is OK
- 10.1080/01621459.1969.10501049 is OK
- 10.1007/978-3-642-31164-2 is OK
- 10.1007/0-387-69505-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1902

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1902, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
Hi @Yomguithereal! We also prefer that the title in your Zenodo archive matches your JOSS paper exactly. Would you want to update that?

**Comment by kthyng** [comment]
Paper looks good! We can proceed after hearing about the Zenodo archive.

**Comment by Yomguithereal** [comment]
@kthyng this should be ok now.

**Comment by kakiac** [comment]
Thank you @Yomguithereal :) 🌟

**Comment by kthyng** [comment]
Excellent! We can wrap up now.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1326183868483899392) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1904
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02405](https://doi.org/10.21105/joss.02405)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @Yomguithereal! Thanks to editor @kakiac and reviewers @Fil and @atanikan for your time and expertise!!

(I will leave this issue open until the DOI resolves)

**Comment by Yomguithereal** [comment]
Thanks everyone for your work and dedication :)

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02405/status.svg)](https://doi.org/10.21105/joss.02405)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02405">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02405/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02405/status.svg
   :target: https://doi.org/10.21105/joss.02405
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02405/status.svg)](https://doi.org/10.21105/joss.02405)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
