### ISSUE TITLE
[PRE REVIEW]: lattice_mc: A Python Lattice-Gas Monte Carlo Module

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#241]
**Submitting author:** @bjmorgan (<a href="http://orcid.org/0000-0002-3056-8233">Benjamin J. Morgan</a>)
**Repository:** <a href="https://github.com/bjmorgan/lattice_mc" target ="_blank">https://github.com/bjmorgan/lattice_mc</a>
**Version:** 1.0.0
**Editor:** @labarba
**Reviewer:** @asmit3

**Author instructions**

Thanks for submitting your paper to JOSS @bjmorgan. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bjmorgan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @labarba - the submitting author suggested you as an editor for this submission.

**Comment by labarba** [comment]
The code repository needs *A statement of need*, which means ... 

> The authors should clearly state what problems the software is designed to solve and who the target audience is.

I was not able to find this, @bjmorgan.

**Comment by bjmorgan** [comment]
@labarba I have amended the README.md and paper.md. Hopefully the additional information is suitable and appropriate for the JOSS requirements.

**Comment by labarba** [comment]
The title in the paper metadata appears as *"lattice_mc: A Python Lattice-Gas Monte Carlo Module"*. I"m not sure why this full title does not appear in the title of the pre-review issue ... it should also probably match the heading in the README.

I'm looking for a reviewer now.

**Comment by arfon** [comment]
> The title in the paper metadata appears as "lattice_mc: A Python Lattice-Gas Monte Carlo Module". I"m not sure why this full title does not appear in the title of the pre-review issue ... it should also probably match the heading in the README.

I just updated this.

**Comment by labarba** [comment]
@whedon assign @labarba as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @labarba

**Comment by labarba** [comment]
Sorry ... I was demonstrating the JOSS bot to a chief librarian and hit "Enter" in the process ... Ignore the actions just above!

**Comment by labarba** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by labarba** [comment]
@arfon : Does our bot have a command to _unassign_ a reviewer? I assigned myself by mistake.

**Comment by arfon** [comment]
> @arfon : Does our bot have a command to unassign a reviewer? I assigned myself by mistake.

Not right now sorry, you're on the hook for reviewing now :trollface:. In all seriousness, when we find a reviewer just use the `@whedon assign username as reviewer` and it will clobber your assignment.

**Comment by labarba** [comment]
@whedon assign asmit3 as reviewer

**Comment by whedon** [comment]
OK, the reviewer is asmit3

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/247. Feel free to close this issue now!
