### ISSUE TITLE
[REVIEW]: Viime: Visualization and Integration of Metabolomics Experiments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2410]
**Submitting author:** @waxlamp (<a href="http://orcid.org/0000-0003-3898-4626">Roni Choudhury</a>)
**Repository:** <a href="https://github.com/girder/viime" target ="_blank">https://github.com/girder/viime</a>
**Version:** v1.0.1
**Editor:** @lpantano
**Reviewers:** @joannawolthuis, @rowlandm, @jkanche
**Archive:** <a href="https://doi.org/10.5281/zenodo.4086165" target="_blank">10.5281/zenodo.4086165</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/77cf7a1d8ffd00c8278a42c449914bb1/status.svg)](https://joss.theoj.org/papers/77cf7a1d8ffd00c8278a42c449914bb1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/77cf7a1d8ffd00c8278a42c449914bb1"><img src="https://joss.theoj.org/papers/77cf7a1d8ffd00c8278a42c449914bb1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/77cf7a1d8ffd00c8278a42c449914bb1/status.svg)](https://joss.theoj.org/papers/77cf7a1d8ffd00c8278a42c449914bb1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/girder/viime" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@joannawolthuis & @rowlandm, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lpantano know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/girder/viime">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@waxlamp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/girder/viime">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@waxlamp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @joannawolthuis, @rowlandm it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2410 with the following error: 

 Can't find any papers to compile :-(

**Comment by lpantano** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02410/joss.02410/10.21105.joss.02410.pdf)

**Comment by lpantano** [comment]
@whedon check references

**Comment by lpantano** [comment]
@luizirber, would you like to review this tool?

**Comment by lpantano** [comment]
@waxlamp, if you know somebody who could be a reviewer let me know, still trying to find the second one. Thanks

**Comment by lpantano** [comment]
@camillescott, would you like to review this visualization tool of metabolomic data?

**Comment by lpantano** [comment]
Hi @a-slide, @rabdill, Would you like to review this tool? thanks!

**Comment by rabdill** [comment]
@lpantano this looks like a really cool project, but I just don't have time to do a review right now, I'm sorry.

**Comment by lpantano** [comment]
Hi @jkanche, @carleshf, would you like to review this tool? thanks!

**Comment by jkanche** [comment]
I am happy to review this!

**Comment by lpantano** [comment]
@whedon add @jkanche as reviewer

**Comment by whedon** [comment]
OK, @jkanche is now a reviewer

**Comment by joannawolthuis** [comment]
Hi @lpantano ! I'm taking a look - but here's a perhaps noob question: this is my first review, should I be writing a more extensive document (and if so, where should I submit it?) using the checklist as a backbone/guide? Or is this a very modern type of review where it is just the checklist? :)

**Comment by lpantano** [comment]
Hi @joannawolthuis, you don't need to write an extensive review. If you want to comment on something, you can do it. But the important it all the items in the checklist are checked. If not, you can open an issue in the tool repository to address the issue, so they can fix it and you can mark all the items in the checklist.

**Comment by waxlamp** [comment]
> @waxlamp, if you know somebody who could be a reviewer let me know, still trying to find the second one. Thanks

Hi @lpantano! Looks like we have two reviewers now, is that right? I have a suggested name in case you need someone else.

**Comment by lpantano** [comment]
yes, we have two!

**Comment by waxlamp** [comment]
Great, thanks for confirming!

**Comment by carleshf** [comment]
Hi!

Sorry for the delay, I'm happy to review the tool too if I'm not too late.

*Carles Hernández*


Missatge de Roni Choudhury <notifications@github.com> del dia dl., 27 de
jul. 2020 a les 23:59:

**Comment by lpantano** [comment]
Hey @joannawolthuis, @jkanche, how is the reviewing going? Any updates on this?

Thanks @carleshf, hopefully we don't need more reviewers for now. Thank you!

**Comment by jkanche** [comment]
Hi @lpantano , I opened an issue on the Vilme repo, once they are figured/answered, I can get back to the review

**Comment by joannawolthuis** [comment]
Hi @lpantano! Same as @jkanche, have opened some issues. One question - for the 'installation' checkmark, does that still count if this aimed to be a webserver? If so I need to ask them to clarify their installation procedure..

**Comment by jkanche** [comment]
I agree with @joannawolthuis, I would also like to see more detailed installation instructions. I am confused on how one can setup an instance Viime for their datasets. 

May be provide a docker container or instructions on how one can set everything up will be good.

**Comment by lpantano** [comment]
Thank you for the updates @joannawolthuis, @jkanche. Yes, the installation needs to be addressed as well for servers. It is a very good point.

**Comment by joannawolthuis** [comment]
Just checking in, thanks for your patience! I have opened some more issues. The installation works well now, just have some issues on startup in terms of example datasets etc. (opened an issue on their github)
Just another question - they are currently dealing with some bugs, as one always has with a tool, new updates will always add new bugs - should i only check off the mark for expected/promised functionality once they have ironed those out? (some plots are just not showing at all, etc).

**Comment by joannawolthuis** [comment]
Oh, one more - is there a supplemental info or something for this paper? Otherwise they have no comparison at all with other tools/state of the art, should I address that on their Github page or through another channel?

**Comment by joannawolthuis** [comment]
@lpantano, whoops forgot to tag you  :)

**Comment by lpantano** [comment]
@joannawolthuis, if they don't point to anything else in the paper, there is not. You can address this by an issue in their repo and you can add that is related to this review. Thanks!

**Comment by joannawolthuis** [comment]
@lpantano  Alright, thanks, opened an issue! And for their bugfixing, I'll just wait until they get it all working properly and then check the box, is that OK? :)

**Comment by lpantano** [comment]
Absolutely!

**Comment by waxlamp** [comment]
@lpantano, @joannawolthuis, and @jkanche, thank you all for serving as reviewers and providing valuable feedback to us!

I've been trying to keep up with the various issues and requests, and I *believe* I've at least addressed everything that has been brought up so far. That is, we have fixed some bugs, made documentation updates to explain certain things better, and filed issues for other bugs. My goal is to get the software and paper up to review standards, since (unfortunately) we don't have the person-hours to fix everything, while filing issues for the rest (to be fixed once we have more funding/FTEs).

I am hoping to sync up with everyone by sending this message. When you get a chance, could you look things over and let me know what still needs to be done?

Thanks again for your time and effort in being our reviewers!

**Comment by lpantano** [comment]
Hi @joannawolthuis , @jkanche, let me know if the last version addresses all your comments. Thanks!

**Comment by joannawolthuis** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02410/joss.02410/10.21105.joss.02410.pdf)

**Comment by joannawolthuis** [comment]
@lpantano Hi! There are still some bugs open, but I know from experience that that can keep going on forever, so I will not hunt for more after the ones I currently addressed are fixed, then that is done :) I would ideally like some improvements to the State of the Field section, I opened an issue here, do you agree @jkanche? https://github.com/girder/viime/issues/624

**Comment by lpantano** [comment]
Thank you @joannawolthuis.
@jkanche, can you share your thoughts for the state of the changes? Thanks

**Comment by jkanche** [comment]
Most of the issues I had before were addressed. I agree with @joannawolthuis on the "Related Work" section. The focus of this section has been based on one tool - MetaboAnalyst. I think it would be great if the authors can talk about other metabolomics tools out there.

**Comment by waxlamp** [comment]
Thank you for the feedback. My team is working on improving the related work section, and I will send a ping from here when we're ready for a new round of reviewing.

**Comment by waxlamp** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02410/joss.02410/10.21105.joss.02410.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02410/joss.02410/10.21105.joss.02410.pdf) :page_facing_up: :point_left:

**Comment by waxlamp** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02410/joss.02410/10.21105.joss.02410.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02410/joss.02410/10.21105.joss.02410.pdf) :page_facing_up: :point_left:

**Comment by waxlamp** [comment]
@lpantano, @joannawolthuis, @jkanche: we have reworked the Related Work section to discuss a wider range of tools in the space. I think it does a good job of surveying the field and explaining what makes Viime unique.

**Comment by lpantano** [comment]
@joannawolthuis, @jkanche, let me know if this addresses everything. Thanks!

**Comment by jkanche** [comment]
@lpantano I think this addresses most of my concerns! Thanks for the updates @waxlamp!

**Comment by joannawolthuis** [comment]
@lpantano Same here, looks good! :) Thanks @waxlamp and VIIME team!

**Comment by lpantano** [comment]
Excellent! thank you so much.

**Comment by lpantano** [comment]
@waxlamp, can you create a zenodo archive of the repository and share here? Title and authors should match the paper information. Thanks!

**Comment by waxlamp** [comment]
> @waxlamp, can you create a zenodo archive of the repository and share here? Title and authors should match the paper information. Thanks!

Definitely. The team is working on fixing some typos (no changes to content) and once that's ready, I will take care of this. Thank you!

**Comment by waxlamp** [comment]
> @waxlamp, can you create a zenodo archive of the repository and share here? Title and authors should match the paper information. Thanks!

@lpantano, here you go: https://zenodo.org/record/4075591, with DOI 10.5281/zenodo.4075591.

Please let me know if there's anything else I can do.

**Comment by lpantano** [comment]
Thanks, this should work. I just noticed that the version in setup.py is 0.1.0: https://github.com/girder/viime/blob/master/setup.py#L26. Any chance to update that to the right number and update the tar.gz file so the 1.0.0 version match the code version? it is ok if you need to create a 1.0.1 or any other solution. Thanks!

**Comment by waxlamp** [comment]
Thank you for catching this, @lpantano. I just reuploaded a fixed version to Zenodo: https://zenodo.org/record/4086165, with DOI 10.5281/zenodo.4086165.

Hopefully this is ok for proceeding. If you think it makes sense, I can also delete the 1.0.0 bundle from Zenodo; please advise.

Thanks!

**Comment by lpantano** [comment]
@whedon set 10.5281/zenodo.4086165 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4086165" target="_blank">10.5281/zenodo.4086165</a> is the archive.

**Comment by lpantano** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by lpantano** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s11306-016-1094-6 is OK
- 10.1038/nrd.2016.32 is OK
- 10.1186/1471-2164-7-142 is OK
- 10.1007/s00216-016-9538-4 is OK
- 10.1002/wics.1246 is OK
- 10.1093/nar/gkp356 is OK
- 10.1093/nar/gky310 is OK
- 10.1002/elps.201500352 is OK
- 10.1007/s11306-017-1242-7 is OK
- 10.1186/1471-2105-11-395 is OK
- 10.1093/bioinformatics/btu136 is OK
- 10.1021/ac1021166 is OK
- 10.1002/0471250953.bi1411s37 is OK
- 10.1093/bioinformatics/btu813 is OK
- 10.1186/s13742-016-0115-8 is OK
- 10.1007/978-1-0716-0239-3_17 is OK
- 10.1021/ac300698c is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1819

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1819, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
👋 @waxlamp - There are some small changes needed in the paper.  See https://github.com/girder/viime/pull/687.  Also, in line 194 of that file, is "-log10" correct?  I don't understand the "-".

Finally, for @lpantano - this paper is far, far too long.  Much of the content should be in the documentation, and just pointed to from the paper.  The ideal for a JOSS paper is 250-1000 words, as described in https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain  At this point, we'll let this proceed without asking the authors to cut it, but for next time, please check to rough length of the paper during the review process.

**Comment by lpantano** [comment]
Thanks, I will do that. I wasnt sure how much longer was the limit(sorry).
The -log10 of the p-value is a common transformation to get small values
(<0.00*) to be large positive numbers. I think probably the transformation
is -1*log10.

**Comment by waxlamp** [comment]
>  @waxlamp - There are some small changes needed in the paper. See [girder/viime#687](https://github.com/girder/viime/pull/687). Also, in line 194 of that file, is "-log10" correct? I don't understand the "-".
> 

Thank you!

As @lpantano mentioned, "-log10" refers to negative log-base-10 of the p-value.

@lpantano, now that the requested fixes are applied, what are the next steps?

**Comment by danielskatz** [comment]
that's it

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s11306-016-1094-6 is OK
- 10.1038/nrd.2016.32 is OK
- 10.1186/1471-2164-7-142 is OK
- 10.1007/s00216-016-9538-4 is OK
- 10.1002/wics.1246 is OK
- 10.1093/nar/gkp356 is OK
- 10.1093/nar/gky310 is OK
- 10.1002/elps.201500352 is OK
- 10.1007/s11306-017-1242-7 is OK
- 10.1186/1471-2105-11-395 is OK
- 10.1093/bioinformatics/btu136 is OK
- 10.1021/ac1021166 is OK
- 10.1002/0471250953.bi1411s37 is OK
- 10.1093/bioinformatics/btu813 is OK
- 10.1186/s13742-016-0115-8 is OK
- 10.1007/978-1-0716-0239-3_17 is OK
- 10.1021/ac300698c is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1822

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1822, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1317906964127621120) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1823
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02410](https://doi.org/10.21105/joss.02410)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @waxlamp (Roni Choudhury) and co-authors!!

And thanks to @lpantano for editing, and @joannawolthuis & @jkanche for reviewing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02410/status.svg)](https://doi.org/10.21105/joss.02410)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02410">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02410/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02410/status.svg
   :target: https://doi.org/10.21105/joss.02410
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02410/status.svg)](https://doi.org/10.21105/joss.02410)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by waxlamp** [comment]
Thank you @lpantano, @joannawolthuis, @jkanche, and @danielskatz!
