### ISSUE TITLE
[REVIEW]: toughio: Pre- and post-processing Python library for TOUGH

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2412]
**Submitting author:** @keurfonluu (<a href="http://orcid.org/0000-0001-7927-0019">Keurfon Luu</a>)
**Repository:** <a href="https://github.com/keurfonluu/toughio" target ="_blank">https://github.com/keurfonluu/toughio</a>
**Version:** v1.3.2
**Editor:** @jgostick
**Reviewers:** @rreinecke, @ma-sadeghi
**Archive:** <a href="https://doi.org/10.5281/zenodo.3961279" target="_blank">10.5281/zenodo.3961279</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b3de87290226774b4182b49e02ebb438/status.svg)](https://joss.theoj.org/papers/b3de87290226774b4182b49e02ebb438)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b3de87290226774b4182b49e02ebb438"><img src="https://joss.theoj.org/papers/b3de87290226774b4182b49e02ebb438/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b3de87290226774b4182b49e02ebb438/status.svg)](https://joss.theoj.org/papers/b3de87290226774b4182b49e02ebb438)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/keurfonluu/toughio" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rreinecke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jgostick know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/keurfonluu/toughio">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@keurfonluu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/keurfonluu/toughio">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@keurfonluu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rreinecke it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.cageo.2012.04.008 is OK
- 10.1111/j.1745-6584.2008.00462.x is OK
- 10.1016/j.cageo.2016.09.009 is OK
- 10.1002/nme.2579 is OK
- 10.5281/zenodo.3888325 is OK
- 10.21105/joss.01450 is OK
- 10.1029/WR012i001p00057 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02412/joss.02412/10.21105.joss.02412.pdf)

**Comment by jgostick** [comment]
@whedon as @ma-sadeghi as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by jgostick** [comment]
@whedon add @ma-sadeghi as reviewer

**Comment by danielskatz** [comment]
@arfon - whedon seems to be having some problems and missing some commands today

**Comment by danielskatz** [comment]
@whedon add @ma-sadeghi as reviewer

**Comment by whedon** [comment]
OK, @ma-sadeghi is now a reviewer

**Comment by danielskatz** [comment]
@jgostick - sometimes the answer is just to try again

**Comment by rreinecke** [comment]
A very clean and well prepared submission @keurfonluu 
Only a very small issue with the test currently open in keurfonluu/toughio#52
Besides that I think it is good to go from my side.

**Comment by rreinecke** [comment]
> A very clean and well prepared submission @keurfonluu
> Only a very small issue with the test currently open in [keurfonluu/toughio#52](https://github.com/keurfonluu/toughio/issues/52)
> Besides that I think it is good to go from my side.

Has been fixed. All good to go.

**Comment by ma-sadeghi** [comment]
- [ ] Documentation (keurfonluu/toughio#60)
- [ ] Automated testing (keurfonluu/toughio#59)

**Comment by jgostick** [comment]
Hi @ma-sadeghi Automated testing is not always necessary, since someone can write solid scientific code that does not know how to automate their testing.  The only requirement is that there is some sort of testing, like a script with several cases in it...more like un-automated integration tests.  Given this, do you still think they need to address the testing part?

**Comment by ma-sadeghi** [comment]
@jgostick I was just following the JOSS checklist (in which "Automated tests" is listed)

Anyways, it turns out they do have automated testing, the badge was just not showing up, which is now fixed. It's all good now.

**Comment by jgostick** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.cageo.2012.04.008 is OK
- 10.1111/j.1745-6584.2008.00462.x is OK
- 10.1016/j.cageo.2016.09.009 is OK
- 10.1002/nme.2579 is OK
- 10.5281/zenodo.3888325 is OK
- 10.21105/joss.01450 is OK
- 10.1029/WR012i001p00057 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jgostick** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02412/joss.02412/10.21105.joss.02412.pdf)

**Comment by jgostick** [comment]
@keurfonluu Everything looks great.  My only suggestion would be to add some sort of concluding remark(s) to the paper after the figure, since it seems to end rather abruptly.  This is only a suggestion though.  

Here is a list of what to do next:

- [ ] Double check authors and affiliations (including ORCIDs)
- [ ] Make a release of the software with the latest changes from the review and post the version number here. This is the version that will be used in the JOSS paper.
- [ ] Archive the release on Zenodo/figshare/etc and post the DOI here.
- [ ] Make sure that the title and author list (including ORCIDs) in the archive match those in the JOSS paper.

**Comment by keurfonluu** [comment]
Sorry for the delay, got a couple of deadlines.

I've added a short conclusion to the paper after the example. Please find below the release version number and DOI:
- version: v1.3.2
- DOI: 10.5281/zenodo.3961279

**Comment by jgostick** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by jgostick** [comment]
@whedon set 10.5281/zenodo.3961279 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3961279" target="_blank">10.5281/zenodo.3961279</a> is the archive.

**Comment by jgostick** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by jgostick** [comment]
Hi @keurfonluu this paper is now accepted.  Thanks to the reviewers for time!

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.cageo.2012.04.008 is OK
- 10.1111/j.1745-6584.2008.00462.x is OK
- 10.1016/j.cageo.2016.09.009 is OK
- 10.1002/nme.2579 is OK
- 10.5281/zenodo.3888325 is OK
- 10.21105/joss.01450 is OK
- 10.1029/WR012i001p00057 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1593

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1593, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon set v1.3.2 as version

**Comment by whedon** [comment]
OK. v1.3.2 is the version.

**Comment by kthyng** [comment]
@keurfonluu I'm wrapping up the publication of your paper this week. Can you change the metadata on your Zenodo archive so that the title and author list exactly matches your paper? This is not a requirement, but it looks better and is preferred.

**Comment by keurfonluu** [comment]
> @keurfonluu I'm wrapping up the publication of your paper this week. Can you change the metadata on your Zenodo archive so that the title and author list exactly matches your paper? This is not a requirement, but it looks better and is preferred.

Done!

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1287823981509312512) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1594
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02412](https://doi.org/10.21105/joss.02412)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats to @jgostick on your new publication!! Thanks so much for @rreinecke and @ma-sadeghi for reviewing, and to @jgostick for editing — this whole process cannot happen without you and your expertise!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02412/status.svg)](https://doi.org/10.21105/joss.02412)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02412">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02412/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02412/status.svg
   :target: https://doi.org/10.21105/joss.02412
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02412/status.svg)](https://doi.org/10.21105/joss.02412)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
