### ISSUE TITLE
[PRE REVIEW]: Pyntheon: A Functional Analysis Framework for Protein Modifications and Mutations of 83 Model Organisms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2413]
**Submitting author:** @AhmedArslan (<a href="http://orcid.org/0000-0002-5325-6558">Ahmed Arslan</a>)
**Repository:** <a href="https://github.com/AhmedArslan/Pyntheon" target ="_blank">https://github.com/AhmedArslan/Pyntheon</a>
**Version:** v1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @AhmedArslan. **Currently, there isn't an JOSS editor assigned** to your paper.

@AhmedArslan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (95.6 files/s, 10360.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5             97             50            445
Markdown                         1             28              0             30
-------------------------------------------------------------------------------
SUM:                             6            125             50            475
-------------------------------------------------------------------------------


Statistical information for the repository '2413' was gathered on 2020/07/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ahmed Arslan                     9            21             18            6.23
AhmedArslan                      6           585              2           93.77

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ahmed Arslan                 10           47.6          2.0                0.00
AhmedArslan                 582           99.5          0.2                4.47
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2413 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@AhmedArslan - where is paper you are submitting?  See https://joss.readthedocs.io/en/latest/submitting.html - your paper should be in the repository that you are submitting.

**Comment by danielskatz** [comment]
Additionally, I am fairly confident that the JOSS editors will find that this software is a minor utility package - see https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements.  Rather than putting a lot of work into this submission, and the other you submitted at the same time, you might want to withdraw both and think about a larger, more complex submission that is a library/package that implements multiple functions.

**Comment by AhmedArslan** [comment]
Sorry for confusion, I have completed ''paper.md" file.

**Comment by danielskatz** [comment]
@whedon generate pdf

note to @AhmedArslan - you can do this too if you make changes and want to rebuild

**Comment by whedon** [comment]
PDF failed to compile for issue #2413 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:145:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon query scope

**Comment by danielskatz** [comment]
@AhmedArslan - The JOSS editor have determined that this submission is out of scope as a minor utility due to its small size. If you want the software to be cite, you might consider getting a DOI for it via zenodo.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
