### ISSUE TITLE
[PRE REVIEW]: E-dish: A Repository for Functional Analyses of E coli Genomes on Desk

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2414]
**Submitting author:** @AhmedArslan (<a href="http://orcid.org/0000-0002-5325-6558">Ahmed Arslan</a>)
**Repository:** <a href="https://github.com/CSB-KUL/E-dish" target ="_blank">https://github.com/CSB-KUL/E-dish</a>
**Version:** v1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @AhmedArslan. **Currently, there isn't an JOSS editor assigned** to your paper.

@AhmedArslan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (20.5 files/s, 5217.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1             69             13            406
Markdown                         1              8              0             14
-------------------------------------------------------------------------------
SUM:                             2             77             13            420
-------------------------------------------------------------------------------


Statistical information for the repository '2414' was gathered on 2020/07/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ahmed Arslan                     2           489              1          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ahmed Arslan                488           99.8          0.0                2.46
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2414 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@AhmedArslan - where is paper you are submitting? See https://joss.readthedocs.io/en/latest/submitting.html - your paper should be in the repository that you are submitting.

**Comment by danielskatz** [comment]
Additionally, I am fairly confident that the JOSS editors will find that this software is a minor utility package - see https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements.  Rather than putting a lot of work into this submission, and the other you submitted at the same time, you might want to withdraw both and think about a larger, more complex submission that is a library/package that implements multiple functions.

**Comment by arfon** [comment]
@whedon query scope

**Comment by danielskatz** [comment]
@AhmedArslan - The JOSS editor have determined that this submission is out of scope as a minor utility due to its small size. If you want the software to be cite, you might consider getting a DOI for it via zenodo.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
