### ISSUE TITLE
[PRE REVIEW]: Chromatiblock: scalable whole-genome visualization of structural differences in prokaryotes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2416]
**Submitting author:** @mjsull (<a href="http://orcid.org/0000-0001-9076-6963">Mitchell</a>)
**Repository:** <a href="https://github.com/mjsull/chromatiblock/" target ="_blank">https://github.com/mjsull/chromatiblock/</a>
**Version:** v0.4.2
**Editor:** @will-rowe
**Reviewers:** @telatin, @rpetit3
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mjsull. **Currently, there isn't an JOSS editor assigned** to your paper.

@mjsull if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (79.3 files/s, 31620.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2            107            124           1334
Markdown                         3            242              0            844
TeX                              1             10              0            123
XML                              1              0              0              6
-------------------------------------------------------------------------------
SUM:                             7            359            124           2307
-------------------------------------------------------------------------------


Statistical information for the repository '2416' was gathered on 2020/07/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
mjsull                          10          4404           3506          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
mjsull                       10            0.2          3.0                0.00
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1186/1471-2164-12-402 is OK
- 10.1093/bioinformatics/btq665 is OK
- 10.1101/gr.2289704 is OK
- 10.1186/1471-2164-13-202 is OK
- 10.1093/bioinformatics/btq413 is OK
- 10.1093/bioinformatics/bts217 is OK
- 10.1101/gr.092759.109 is OK
- 10.1101/548123 is OK
- 10.1093/bioinformatics/btr039 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-642-40453-5_17 may be missing for title: Sibelia: A Scalable and Comprehensive Synteny Block Generation Tool for Closely Related Microbial Genomes

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02416/joss.02416/10.21105.joss.02416.pdf)

**Comment by arfon** [comment]
@whedon query scope

**Comment by danielskatz** [comment]
👋 @will-rowe - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @will-rowe as editor

**Comment by whedon** [comment]
@will-rowe has been invited to edit this submission.

**Comment by will-rowe** [comment]
sure - sounds good @danielskatz

**Comment by will-rowe** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hey @happykhan - would you be interested in reviewing this JOSS submission?

**Comment by will-rowe** [comment]
Hi @abotzki - would you also be able to review this submission for JOSS?

**Comment by happykhan** [comment]
@will-rowe    . @mjsull is a good friend so I don't think its fair if I review it. I can suggest @leomrtns @lskatz @telatin or @thanhleviet

**Comment by will-rowe** [comment]
Thanks @happykhan - and thank you very much for the suggestions. @leomrtns, @lskatz and @telatin - would any of you be able to review this (even better if two of you could). I think this looks like a really useful tool for our field and it would be great to get your takes on it.

**Comment by telatin** [comment]
I can review this 👍

**Comment by will-rowe** [comment]
Great - thanks @telatin! We'll wait on one more reviewer and then kick things off.

**Comment by abotzki** [comment]
Hi @will-rowe I am on holidays for 3 weeks. If still of help, I could have a look at the software around end of July.

**Comment by will-rowe** [comment]
Thanks for getting back to me @abotzki  - I'll see if I can get someone with some more availability. Have a good holiday!

**Comment by will-rowe** [comment]
Hey @rpetit3 and @coughls. Would either of you be able to review this submission for JOSS please?

**Comment by rpetit3** [comment]
I can review it.

**Comment by leomrtns** [comment]
Hi @will-rowe I can start the review in ~10 days, I'll keep an eye here in case you don't find anybody

**Comment by will-rowe** [comment]
Brilliant - thanks @rpetit3!

@leomrtns - we have 2 reviewers now, thank you anyway.

**Comment by will-rowe** [comment]
@whedon assign @telatin as reviewer

**Comment by whedon** [comment]
OK, @telatin is now a reviewer

**Comment by will-rowe** [comment]
@whedon add @rpetit3 as a reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by will-rowe** [comment]
@whedon add @rpetit3 as reviewer

**Comment by whedon** [comment]
OK, @rpetit3 is now a reviewer

**Comment by will-rowe** [comment]
Thank you again for agreeing to review @telatin and @rpetit3 

I'll kick the review process off now. This will start a new thread with instructions at the top. Please ping me if you need anything.

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2451.
