### ISSUE TITLE
[PRE REVIEW]: Extracting, Computing and Exploring the Parameters of Statistical Models using R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2417]
**Submitting author:** @strengejacke (<a href="http://orcid.org/0000-0002-8895-3206">Daniel Lüdecke</a>)
**Repository:** <a href="https://github.com/easystats/parameters" target ="_blank">https://github.com/easystats/parameters</a>
**Version:** 0.8.1
**Editor:** @sbenthall
**Reviewers:** @cmaimone
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @strengejacke. **Currently, there isn't an JOSS editor assigned** to your paper.

@strengejacke if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=2.40 s (141.8 files/s, 30013.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           156           7879           2023          37357
R                              154           3807           4363          11054
XML                              1              0             42           1484
Markdown                         5            209              0            548
Rmd                              9            443            711            517
CSS                              4            112             54            449
JavaScript                       4             64             34            266
YAML                             4             42              3            265
TeX                              2             43              0            201
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                           340          12599           7231          52152
-------------------------------------------------------------------------------


Statistical information for the repository '2417' was gathered on 2020/07/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel                           7           337             17           63.90
Dominique Makowski               1           200              0           36.10

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel                      332           98.5          2.2               13.25
DominiqueMakowski           188          100.0          0.0                8.51
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01541 is OK
- 10.21105/joss.01412 is OK
- 10.18637/jss.v016.i09 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by strengejacke** [comment]
Thank you, @danielskatz, for opening this pre-review. I'd suggest following reviewers, with no particular order:

@cmaimone 
@Ohlsen
@benmarwick
@amoeba
@briatte

**Comment by strengejacke** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02417/joss.02417/10.21105.joss.02417.pdf)

**Comment by strengejacke** [comment]
(truncated lines that exceeded page margins)

@whedon generate pdf

**Comment by strengejacke** [comment]
@whedon generate pdf

(truncated lines that exceeded page margins)

**Comment by danielskatz** [comment]
@strengejacke  - as requested, please do not tag potential reviewers so that they are not forced to join this thread until an editor chooses to ask them.  Also, a command to whedon needs to be the first (or only) think in a new comment

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02417/joss.02417/10.21105.joss.02417.pdf)

**Comment by strengejacke** [comment]
@danielskatz sorry for tagging reviewers, have overlooked this and was used to suggesting reviewers this way in a previous submission.

**Comment by danielskatz** [comment]
suggesting is great, but without the @ please

**Comment by danielskatz** [comment]
👋 @sbenthall - you were suggested as the editor for this submission - Are you willing to edit it?

**Comment by danielskatz** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by sbenthall** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @sbenthall

**Comment by sbenthall** [comment]
@cmaimone Would you be willing to review this entry?

**Comment by sbenthall** [comment]
@Ohlsen Would you be willing to review this entry?

**Comment by Ohlsen** [comment]
@sbenthall sure
@whedon assign me as reviewer

**Comment by Ohlsen** [comment]
@whedon assign @Ohlsen as reviewer

**Comment by whedon** [comment]
I'm sorry @Ohlsen, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by cmaimone** [comment]
@sbenthall I can review

**Comment by sbenthall** [comment]
@whedon assign @Ohlsen as reviewer

**Comment by whedon** [comment]
OK, @Ohlsen is now a reviewer

**Comment by sbenthall** [comment]
@whedon assign @cmaimone as reviewer

**Comment by whedon** [comment]
OK, @cmaimone is now a reviewer

**Comment by sbenthall** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2445.
