### ISSUE TITLE
[PRE REVIEW]: chirps: API Client for the CHIRPS Precipitation Data in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2418]
**Submitting author:** @kauedesousa (<a href="http://orcid.org/0000-0002-7571-7845">Kauê de Sousa</a>)
**Repository:** <a href="https://github.com/ropensci/chirps" target ="_blank">https://github.com/ropensci/chirps</a>
**Version:** v0.1.0
**Editor:** @danielskatz
**Reviewers:** @danielskatz
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kauedesousa. **Currently, there isn't an JOSS editor assigned** to your paper.

@kauedesousa if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02418/joss.02418/10.21105.joss.02418.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/sdata.2015.66 is OK
- 10.1029/2005JD006119 is OK
- 10.1016/j.jrurstud.2018.09.018 is OK
- 10.32614/RJ-2018-009 is OK
- 10.1175/2010JCLI3812.1 is OK
- 10.1073/pnas.1813720116 is OK
- 10.21105/joss.01686 is OK
- 10.4269/ajtmh.16-0696 is OK
- 10.3390/ijerph15040709 is OK

MISSING DOIs

- https://doi.org/10.1201/b19518-17 may be missing for title: Identifying Climate Patterns during the Crop-Growing Cycle from 30 Years of CIMMYT Elite Spring Wheat International Yield Trials

INVALID DOIs

- None
```

**Comment by kauedesousa** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by kauedesousa** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/sdata.2015.66 is OK
- 10.1029/2005JD006119 is OK
- 10.1016/j.jrurstud.2018.09.018 is OK
- 10.32614/RJ-2018-009 is OK
- 10.1175/2010JCLI3812.1 is OK
- 10.1073/pnas.1813720116 is OK
- 10.21105/joss.01686 is OK
- 10.1201/b19518-17 is OK
- 10.4269/ajtmh.16-0696 is OK
- 10.3390/ijerph15040709 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kauedesousa** [comment]
This package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/357, @melvidoni

**Comment by danielskatz** [comment]
@thanks @kauedesousa  - I'll move this along in that case, likely sometime today...

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as reviewer

**Comment by whedon** [comment]
OK, @danielskatz is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2419.

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.34 s (181.7 files/s, 52708.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                             8             31             24           9211
HTML                            17            815            225           2716
R                               17            653            827           1021
CSS                              3             99             48            428
JavaScript                       5             65             37            277
TeX                              2             41              0            255
JSON                             1              0              0            250
Markdown                         4            110              0            208
SVG                              2              0              1            113
XML                              1              0              1             18
Rmd                              1             76            141              0
-------------------------------------------------------------------------------
SUM:                            61           1890           1304          14497
-------------------------------------------------------------------------------


Statistical information for the repository '84eb197c76d8956c67976ce1' was
gathered on 2020/10/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adam H. Sparks                   7           600            435           82.21
Kauê de Sousa                    1             7              5            0.95
kauedesousa                      2           212              0           16.84

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adam H. Sparks              379           63.2          0.0                9.76
```
