### ISSUE TITLE
[PRE REVIEW]: filling: Matrix Completion in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2420]
**Submitting author:** @kyoustat (<a href="http://orcid.org/0000-0002-8584-459X">Kisung You</a>)
**Repository:** <a href="https://github.com/kyoustat/filling" target ="_blank">https://github.com/kyoustat/filling</a>
**Version:** v0.2.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kyoustat. **Currently, there isn't an JOSS editor assigned** to your paper.

@kyoustat if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.12 s (225.2 files/s, 21270.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              2             37              0            460
HTML                             1             88              5            404
R                               17             66            718            379
C++                              4             47             47            221
Markdown                         3             21              0             57
-------------------------------------------------------------------------------
SUM:                            27            259            770           1521
-------------------------------------------------------------------------------


Statistical information for the repository '2420' was gathered on 2020/07/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
kisungyou                        4           342             27          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kisung                      315          100.0          0.0               14.92
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1002/mpr.329 is OK
- 10.1137/080738970 is OK
- 10.1007/s10208-009-9045-5 is OK
- 10.1109/JPROC.2009.2035722 is OK
- 10.1214/14-AOS1272 is OK
- 10.1109/JSTSP.2016.2539100 is OK
- 10.18637/jss.v040.i08 is OK
- 10.1016/j.csda.2013.02.005 is OK
- 10.1007/s11063-019-10163-0 is OK
- 10.1109/TIT.2010.2046205 is OK
- 10.1007/s10462-019-09709-4 is OK
- 10.4172/2155-6180.1000224 is OK
- 10.1145/1102351.1102441 is OK
- 10.21105/joss.00026 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02420/joss.02420/10.21105.joss.02420.pdf)

**Comment by arfon** [comment]
@whedon query scope

**Comment by kyoustat** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by danielskatz** [comment]
👋 @kyoustat - After discussion by the OSS editors, we have determined that is is out-of-scope for JOSS as a minor utility. See https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements 

If your goal is to have this software cited, you might consider:

- Follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.
 - Enquire whether your software might be considered by communities such as [rOpenSci](https://ropensci.org) and [pyOpenSci](https://pyopensci.org).

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
