### ISSUE TITLE
[PRE REVIEW]: GeoBO: Python package for Multi-Objective Bayesian Optimisation and Joint Inversion in Geosciences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2421]
**Submitting author:** @sebhaan (<a href="http://orcid.org/0000-0002-5994-5637">Sebastian Haan</a>)
**Repository:** <a href="https://github.com/sebhaan/geobo" target ="_blank">https://github.com/sebhaan/geobo</a>
**Version:** v1.0.0
**Editor:** @hugoledoux
**Reviewers:** @npetra
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sebhaan. **Currently, there isn't an JOSS editor assigned** to your paper.

@sebhaan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02421/joss.02421/10.21105.joss.02421.pdf)

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (319.2 files/s, 103595.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                        10            874              0           3979
HTML                             7            341              0           3772
Python                          12            274            572            992
YAML                             5             90            210            199
TeX                              1              6              0             51
-------------------------------------------------------------------------------
SUM:                            35           1585            782           8993
-------------------------------------------------------------------------------


Statistical information for the repository '2421' was gathered on 2020/07/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Seb Haan                         7          1952            106          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Seb Haan                   1846           94.6          0.0               13.54
```

**Comment by jedbrown** [comment]
:wave: @sebhaan Could you explain a bit more about related software. Perhaps https://hippylib.github.io/, for example? This would be a good thing to add to your README/documentation as well as the paper.

**Comment by arfon** [comment]
@whedon query scope

**Comment by sebhaan** [comment]
> 👋 @sebhaan Could you explain a bit more about related software. Perhaps https://hippylib.github.io/, for example? This would be a good thing to add to your README/documentation as well as the paper.

@jedbrown Have added a new section about related software (hippylib, Obsidian, and GemPy) to the README and three more references to these bayesian inversion tools in the paper.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02421/joss.02421/10.21105.joss.02421.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00940 is OK

MISSING DOIs

- https://doi.org/10.5194/gmd-12-2941-2019 may be missing for title: Efficiency and robustness in Monte Carlo sampling for 3-D geophysical inversions with Obsidian v0. 1.2: setting up for success
- https://doi.org/10.5194/gmd-12-1-2019 may be missing for title: GemPy 1.0: open-source stochastic geological modeling and inversion

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@hugoledoux - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @hugoledoux as editor

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by hugoledoux** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by hugoledoux** [comment]
@jedbrown would you like to review this paper?

**Comment by jedbrown** [comment]
If needed (quite busy already with JOSS editing), but perhaps @uvilla or @npetra would be available?

**Comment by hugoledoux** [comment]
I have already asked 2 other persons (on the JOSS reviewers list). 

I just saw it was close to your expertise and thought that would be an easy way to recruit the first reviewer! But I understand, let's wait then.

**Comment by hugoledoux** [comment]
Would @uvilla or @npetra would be available for this review? I didn't get any response from the 2 on the JOSS list, unfortunately.

**Comment by uvilla** [comment]
Hi Hugo,
 I’m on a family leave until the end of the semester, and unfortunately I
won’t be able to serve as a reviewer for Joss this time around.

I’m looking forward to serve in a future occasion.

Kind regards,

Umberto

**Comment by npetra** [comment]
Hi Hugo (@hugoledoux),

I can help with this review. What is the deadline, etc.?

Best,
Noemi

**Comment by hugoledoux** [comment]
@npetra great. We try to do the reviews <1mo, would that be possible?

I don't know if you've done reviews for JOSS before? If not, you should know that the review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged.

JOSS reviews involve downloading and installing the software, and inspecting the repository
and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html

Editors and reviewers post comments on the Review issue, and authors respond to the comments
and improve their submission until acceptance (or withdrawal, if they feel unable to
satisfy the review).

Let me know if possible, if not, if you could please propose alternatives that would be great; their github username here (without the "@" so that they don't get automatically the notification).

**Comment by hugoledoux** [comment]
> I’m looking forward to serve in a future occasion.

@uvilla no problem, thanks for getting back to me quickly.

**Comment by npetra** [comment]
@hugoledoux 1 month should be fine. Thanks for the details. This is the first time I am reviewing for JOSS, will take a look at the review criteria and get back to you if I have questions.

**Comment by hugoledoux** [comment]
@whedon assign @npetra as reviewer

**Comment by whedon** [comment]
OK, @npetra is now a reviewer

**Comment by hugoledoux** [comment]
@npetra super. The actual review is done in another issue, you'll be notified. At the top of the issue there are instructions about what you should do. It's a bit overwhelming at first, so don't hesitate to ask me questions. 

You are allowed--and expected!--to interact directly with the authors. You can say "hey this and that doesn't work" and we expect them to fix those. It's a dialogue that goes back and forth.

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2690.

**Comment by npetra** [comment]
@hugoledoux I am ready to submit my review (sorry for the slight delay) but unfortunately it looks like the invite has expired. Is it possible to renew the invite? Thanks!

**Comment by hugoledoux** [comment]
@whedon re-invite @npetra as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@npetra please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations
