### ISSUE TITLE
[PRE REVIEW]: WikiRevParser: a Python Library for Parsing Wikipedia Revision Histories

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2422]
**Submitting author:** @ajoer (<a href="http://orcid.org/0000-0002-2568-4360">Anna Jørgensen</a>)
**Repository:** <a href="WikiRevParser" target ="_blank">WikiRevParser</a>
**Version:** 0.0.8
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ajoer. **Currently, there isn't an JOSS editor assigned** to your paper.

@ajoer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2422 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@ajoer - I'm going to reject this, as you didn't put in a repository, just WikiRevParser - this needs to be a complete path to a repository...  Please feel free to submit a new version with the link to a repository

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
