### ISSUE TITLE
[PRE REVIEW]: PyMatting: A Python Library for Alpha Matting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2423]
**Submitting author:** @99991 (<a href="http://orcid.org/0000-0003-1355-7724">Thomas Germer</a>)
**Repository:** <a href="https://github.com/pymatting/pymatting" target ="_blank">https://github.com/pymatting/pymatting</a>
**Version:** v1.0.6
**Editor:** @gkthiruvathukal
**Reviewers:** @ziatdinovmax, @macrocosme
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @99991. **Currently, there isn't an JOSS editor assigned** to your paper.

@99991 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.14 s (649.0 files/s, 52622.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          67           1329           1395           3091
TeX                              1             22              0            202
Markdown                         6             67              0            202
C                                2             72            114            141
C++                              2             47             12            129
reStructuredText                 6             98            122            117
Bourne Shell                     2              9              0             39
DOS Batch                        1              8              1             26
YAML                             1              1              0             26
make                             1              4              7              9
HTML                             1              0              0              7
-------------------------------------------------------------------------------
SUM:                            90           1657           1651           3989
-------------------------------------------------------------------------------


Statistical information for the repository '2423' was gathered on 2020/07/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
99991                           14          6511            500           81.96
Joseph Adams                     1             2              2            0.05
Tobias Uelwer                    9           100            137            2.77
germer                           2           372            366            8.63
uelwer                          12           457            107            6.59

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
99991                      5540           85.1          0.3                7.47
Tobias Uelwer               520          520.0          3.3                1.73
germer                      270           72.6          0.0               11.11
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2423 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02423/joss.02423/10.21105.joss.02423.pdf)

**Comment by danielskatz** [comment]
@whedon check references from branch joss-submission

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-submission
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/TPAMI.2013.18 is OK
- 10.1016/j.parco.2011.09.001 is OK
- 10.1109/TPAMI.2007.1177 is OK
- 10.1109/ICCV.2009.5459326 is OK
- 10.1145/992200.992206 is OK
- 10.1134/S1995080219050056 is OK
- 10.1137/S0895479899358194 is OK
- 10.1534/genetics.115.179887 is OK
- 10.1109/TPWRS.2017.2789187 is OK
- 10.1109/CVPR.2010.5539896 is OK
- 10.1109/CVPR.2009.5206503 is OK
- 10.1109/CVPR.2011.5995665 is OK
- 10.1145/200979.200981 is OK

MISSING DOIs

- https://doi.org/10.2172/751785 may be missing for title: SuperLU users’ guide
- https://doi.org/10.1016/j.parco.2005.07.004 may be missing for title: Hybrid scheduling for the parallel solution of linear systems
- https://doi.org/10.1016/j.jocs.2017.08.013 may be missing for title: Enhancing the scalability of selected inversion factorization algorithms in genomic prediction
- https://doi.org/10.1016/0021-9991(78)90098-0 may be missing for title: The incomplete Cholesky—conjugate gradient method for the iterative solution of systems of linear equations
- https://doi.org/10.1201/9781351069397-24 may be missing for title: Methods of conjugate gradients for solving linear systems

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@99991 - please take a look at the references above - if correct, please add them to your .bib file then use the same commands to whedon that I did to regenerate the paper and check the references

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @gkthiruvathukal as editor

**Comment by whedon** [comment]
@gkthiruvathukal has been invited to edit this submission.

**Comment by gkthiruvathukal** [comment]
@danielskatz Yes, I'm willing to edit it!

**Comment by danielskatz** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by 99991** [comment]
@whedon check references from branch joss-submission

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-submission
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/TPAMI.2013.18 is OK
- 10.1016/j.parco.2011.09.001 is OK
- 10.1109/TPAMI.2007.1177 is OK
- 10.1109/ICCV.2009.5459326 is OK
- 10.2172/751785 is OK
- 10.1145/992200.992206 is OK
- 10.1134/S1995080219050056 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1109/CVPR.2010.5539896 is OK
- 10.1109/CVPR.2009.5206503 is OK
- 10.1016/0021-9991(78)90098-0 is OK
- 10.1201/9781351069397-24 is OK
- 10.1109/CVPR.2011.5995665 is OK
- 10.1145/200979.200981 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by 99991** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02423/joss.02423/10.21105.joss.02423.pdf)

**Comment by 99991** [comment]
We would like to suggest the potential reviewers faroit, ziatdinovmax and macrocosme.

**Comment by gkthiruvathukal** [comment]
@99991 Thanks for these suggestions. I will try to get review started over the weekend!

**Comment by gkthiruvathukal** [comment]
@faroit and @ziatdinovmax, I am in need of two reviewers for this JOSS submission. Would either or both of you be willing to contribute a review for this JOSS submission?

**Comment by faroit** [comment]
@gkthiruvathukal I could do that but computer vision is not my level of expertise. If you still can't find a suitable reviewer from a close field, just ping me

**Comment by ziatdinovmax** [comment]
@gkthiruvathukal Yes, I will be happy to help with a review.

**Comment by gkthiruvathukal** [comment]
@whedon assign @ziatdinovmax as reviewer

**Comment by whedon** [comment]
OK, @ziatdinovmax is now a reviewer

**Comment by gkthiruvathukal** [comment]
@macrocosme Would you be willing to contribute a review for this JOSS submission? I need a second, since this is outside @faroit's expertise. 

@faroit Even when not entirely your expertise, the goal is to know whether the software meets the JOSS criteria and can perform its mission successfully. I hope you'd be willing to be the second reviewer, if @macrocosme is not available.

**Comment by macrocosme** [comment]
@gkthiruvathukal I will be happy to contribute a review for this JOSS submission.

**Comment by gkthiruvathukal** [comment]
@whedon add @macrocosme as reviewer

**Comment by whedon** [comment]
OK, @macrocosme is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2481.
