### ISSUE TITLE
[REVIEW]: argopy: A Python library for Argo ocean data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2425]
**Submitting author:** @gmaze (<a href="http://orcid.org/0000-0001-7231-2095">Guillaume Maze</a>)
**Repository:** <a href="https://github.com/euroargodev/argopy" target ="_blank">https://github.com/euroargodev/argopy</a>
**Version:** v0.1.6
**Editor:** @kthyng
**Reviewer:** @dhruvbalwada, @DamienIrving
**Archive:** <a href="https://doi.org/10.5281/zenodo.4010160" target="_blank">10.5281/zenodo.4010160</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9e31b212f63c2bacb4006b14bb8a743f/status.svg)](https://joss.theoj.org/papers/9e31b212f63c2bacb4006b14bb8a743f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9e31b212f63c2bacb4006b14bb8a743f"><img src="https://joss.theoj.org/papers/9e31b212f63c2bacb4006b14bb8a743f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9e31b212f63c2bacb4006b14bb8a743f/status.svg)](https://joss.theoj.org/papers/9e31b212f63c2bacb4006b14bb8a743f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/euroargodev/argopy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dhruvbalwada & @DamienIrving, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/euroargodev/argopy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@gmaze) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/euroargodev/argopy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@gmaze) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dhruvbalwada, @DamienIrving it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2425 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@Whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2425 with the following error: 

 Can't find any papers to compile :-(

**Comment by dhruvbalwada** [comment]
@kthyng @whedon - how do I stop from getting my email inbox bombarded by JOSS? I am getting an email for what seems to be like a review of every single paper on JOSS. 

![Screen Shot 2020-07-02 at 4 14 39 PM](https://user-images.githubusercontent.com/18236610/86416565-27092280-bc7f-11ea-882e-dcf214674583.png)

**Comment by danielskatz** [comment]
sorry about that - see the instructions in this thread above, specifically: https://github.com/openjournals/joss-reviews/issues/2425#issuecomment-653246380

**Comment by gmaze** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02425/joss.02425/10.21105.joss.02425.pdf)

**Comment by kthyng** [comment]
Hi @dhruvbalwada, @DamienIrving! Just a friendly reminder about the existence of this submission to review. Thanks!

**Comment by DamienIrving** [comment]
I've finished my review. My overall comment is that this package is a much needed resource for the oceanographic community and I commend the authors for taking on the task of developing and releasing argopy. I recommend that this paper be published with JOSS after consideration of a few minor comments relating to the following criteria in the checklist:
* **Community guidelines:** It might be a good idea to explicitly state that users can get support at the argopy gitter channel (https://github.com/euroargodev/argopy/issues/42) and to move the `contributing.rst` file to the root directory of the GitHub repo (https://github.com/euroargodev/argopy/issues/41) 
* **Quality of writing:** I've made some minor suggested changes to the text of the JOSS paper (https://github.com/euroargodev/argopy/pull/40)

**Comment by dhruvbalwada** [comment]
argopy is a software that I have always hoped and wished for, and it will really help fill a very important gap that scientists had to climb through to start using Argo data. There is a lot of great functionality that is part of this release, and there are excellent plans to add more features in the near future. I recommend the publication of this article in JOSS. 

I have looked through the minor writing edits suggested above, and second them. I have added some addition suggestions to at https://github.com/DamienIrving/argopy/pull/1 (since I not super familiar with github I was not sure how to create them as a pull request to the main directory, but maybe @DamienIrving can merge them before @gmaze merges Damien's request).

I have also created a couple of minor requests - one issue and one pull request.

**Comment by kthyng** [comment]
@gmaze how are your responses to the reviewers going along?

**Comment by gmaze** [comment]
Hi @kthyng 
I've taken into account all reviewers comments (thank you @DamienIrving and @dhruvbalwada ) and basically finished a [more complete contribution guidelines on the documentation webpage](https://argopy.readthedocs.io/en/joss-paper/contributing.html). I've also incorporated all edits to the manuscript.
So, I guess I'm done do address reviews and the JOSS-paper branch is now up to date and ready to merge if you accept my answers to reviews.
Do you want me to formally address reviews in the comments above ? I've done it directly in the PR and issues raised on the software repo.
g

**Comment by kthyng** [comment]
Excellent @gmaze! 

@dhruvbalwada, @DamienIrving I see that you have both spoken highly of this package and think the review is nearly complete. Could you each review the final work from @gmaze and confirm if you are satisfied?

**Comment by DamienIrving** [comment]
I'm satisfied :smile:

**Comment by dhruvbalwada** [comment]
I am also satisfied.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2425 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02425/joss.02425/10.21105.joss.02425.pdf)

**Comment by kthyng** [comment]
@whedon check references

**Comment by kthyng** [comment]
@gmaze Just read through your paper. Looks good, but can you edit your references? I see that "Argo" is not coming through capitalized, in particular. You'll need to put {} around "Argo", like "{Argo}", to preserve capitalization. Please look at your references in detail to see if there are other tweaks too.

**Comment by kthyng** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3389/fmars.2019.00439 is OK
- 10.1038/nclimate2872 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.17882/48531 is INVALID because of 'https://doi.org/' prefix
```

**Comment by gmaze** [comment]
> @gmaze Just read through your paper. Looks good, but can you edit your references? I see that "Argo" is not coming through capitalized, in particular. You'll need to put {} around "Argo", like "{Argo}", to preserve capitalization. Please look at your references in detail to see if there are other tweaks too.

Done !

@whedon check references from branch joss-paper

**Comment by gmaze** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3389/fmars.2019.00439 is OK
- 10.1038/nclimate2872 is OK
- 10.17882/48531 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by gmaze** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "Year" (NAME) [#<BibTeX::Bibliography data=[2]>, "@", #<BibTeX::Entry >, {:author=>["Annie Wong and coauthors"], :journal=>["Frontiers in Marine Science, section Ocean Observation"], :title=>["{Argo} 1999-2019: two million temperature-salinity profiles and subsurface velocity observations from a global array of profiling floats"], :volume=>["in press"], :doi=>["10.3389/fmars.2020.00700"]}]

**Comment by gmaze** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3389/fmars.2019.00439 is OK
- 10.1038/nclimate2872 is OK
- 10.17882/48531 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.3389/fmars.2020.00700 is INVALID
```

**Comment by gmaze** [comment]
@kthyng One of the reference has just been accepted, I have the DOI, but it's not online yet, that's why whedon fails to find the doi. 
What do you recommend in this situation ?

**Comment by kthyng** [comment]
@gmaze if that is the correct doi, let's just proceed with it as is.

**Comment by kthyng** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02425/joss.02425/10.21105.joss.02425.pdf)

**Comment by gmaze** [comment]
> @gmaze if that is the correct doi, let's just proceed with it as is.

Yes, I have double-checked

**Comment by kthyng** [comment]
@gmaze The author list is incorrect for the first reference, and NetCDF should be properly capitalized too.

**Comment by gmaze** [comment]
@kthyng Thanks for your careful reading ! Refs should now be ok.

**Comment by gmaze** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02425/joss.02425/10.21105.joss.02425.pdf)

**Comment by gmaze** [comment]
Proof ok for me !

**Comment by kthyng** [comment]
Ok great! 

Next, please make a tagged release of the repository in github and then archive it at a place like Zenodo. After that, report the version number and archive DOI in the review thread please.

**Comment by gmaze** [comment]
ok,

I've merged the PR and specific JOSS-paper branch back to master 

I've created a new release [version **v0.1.6**](https://github.com/euroargodev/argopy/releases/tag/v0.1.6) with the paper in the main master branch.

The release has been archived at zenodo under doi: 10.5281/zenodo.4009264
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4009264.svg)](https://doi.org/10.5281/zenodo.4009264)

thanks !

**Comment by kthyng** [comment]
@whedon set v0.1.6 as version

**Comment by whedon** [comment]
OK. v0.1.6 is the version.

**Comment by kthyng** [comment]
Excellent, got the version.

Can you change the title of your Zenodo archive to match the title of your JOSS paper? Also it looks strange as an archive, usually the files are all shown. For example, following are links to two of the last zenodo archives I've dealt with: https://zenodo.org/record/3996524#.X01br_hKjOQ and https://zenodo.org/record/4009224#.X01bsvhKjOQ.  Is yours different just because of the tar file or something more significant?

**Comment by gmaze** [comment]
ok:

1. I updated the zenodo archive with the JOSS paper title
1. To have files more explicit, I uploaded a .zip instead of .tar.gz for zenodo to be able to display files.
But this changed the zenodo DOI, it's now: **10.5281/zenodo.4010160** 

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4010160.svg)](https://doi.org/10.5281/zenodo.4010160)

([both files comes from the github tagged release v0.1.6](https://github.com/euroargodev/argopy/releases/tag/v0.1.6))

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.4010160 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4010160" target="_blank">10.5281/zenodo.4010160</a> is the archive.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fmars.2019.00439 is OK
- 10.1038/nclimate2872 is OK
- 10.17882/48531 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.3389/fmars.2020.00700 is INVALID
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1693

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1693, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1300787259231416321) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1694
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02425](https://doi.org/10.21105/joss.02425)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats to @gmaze on your new publication!!! Many thanks to reviewers @dhruvbalwada and @DamienIrving — we couldn't make this happen without your time and expertise.

**Comment by gmaze** [comment]
> Congrats to @gmaze on your new publication!!! Many thanks to reviewers @dhruvbalwada and @DamienIrving — we couldn't make this happen without your time and expertise.

Thanks to you @kthyng and reviewers @dhruvbalwada and @DamienIrving !
