### ISSUE TITLE
[PRE REVIEW]: OmniCV - A library for Omnidirectional Cameras

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2426]
**Submitting author:** @kaustubh-sadekar (<a href="http://orcid.org/0000-0001-8895-5319">kaustubh sadekar</a>)
**Repository:** <a href="https://github.com/kaustubh-sadekar/OmniCV-Lib" target ="_blank">https://github.com/kaustubh-sadekar/OmniCV-Lib</a>
**Version:** v1.0
**Editor:** @mjsottile
**Reviewers:** @nnadeau, @ionlights
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kaustubh-sadekar. **Currently, there isn't an JOSS editor assigned** to your paper.

@kaustubh-sadekar if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.35 s (254.0 files/s, 80853.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      11           2201           2239           8333
HTML                            14           1649             14           3125
SVG                              1              0              0           2671
C++                             17            470            210           1631
CSS                              6            312             54           1180
Python                          14            360            214           1090
reStructuredText                13            607            659            496
Markdown                         6             94              0            292
TeX                              1             17              0            150
CMake                            2             33              6             73
C/C++ Header                     1              7              0             35
XML                              1             14             36             29
YAML                             1              0              0             18
Bourne Shell                     1              1              0             11
-------------------------------------------------------------------------------
SUM:                            89           5765           3432          19134
-------------------------------------------------------------------------------


Statistical information for the repository '2426' was gathered on 2020/07/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
kaustubh sadekar                12         18645           1855          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
kaustubh sadekar          16790           90.1          0.0               15.67
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-0-387-31439-6_488 is OK
- 10.1145/3278471.3278479 is OK
- 10.1016/j.cviu.2006.06.003 is OK
- 10.1007/3-540-45053-X_29 is OK
- 10.1007/PL00013269 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- https://doi.org/10.1109/icra.2016.7487210 may be missing for title: Benefit of large field-of-view cameras for visual odometry
- https://doi.org/10.1007/978-3-030-20876-9_3 may be missing for title: CubemapSLAM: A Piecewise-Pinhole Monocular Fisheye SLAM System
- https://doi.org/10.1109/3dv.2018.00069 may be missing for title: The Double Sphere Camera Model
- https://doi.org/10.1109/icassp.2016.7471935 may be missing for title: A data set providing synthetic and real-world fisheye video sequences

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02426/joss.02426/10.21105.joss.02426.pdf)

**Comment by danielskatz** [comment]
👋 @mjsottile - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @mjsottile as editor

**Comment by whedon** [comment]
@mjsottile has been invited to edit this submission.

**Comment by mjsottile** [comment]
@danielskatz sure.  It might be a couple days to start the process with the holiday weekend.

**Comment by mjsottile** [comment]
@whedon assign @mjsottile as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mjsottile** [comment]
:wave: @kaustubh-sadekar - In order to start the review process I need to identify 2-3 reviewers.  Do you have any that you would suggest before I look for some on my own?

**Comment by kaustubh-sadekar** [comment]
I would like to suggest NitinJSanket as a potential reviewer. Following is the link to his webpage: https://nitinjsanket.github.io/index.html

**Comment by mjsottile** [comment]
:wave: @nnadeau, @NitinJSanket, @jizecn  Would you be interested in reviewing this submission for JOSS?  We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by mjsottile** [comment]
@kaustubh-sadekar apologies for the delay - I was unexpectedly distracted for a few days and am just getting to my backlog of tasks.

**Comment by kaustubh-sadekar** [comment]
@mjsottile no worries at all. I totally understand.

**Comment by nnadeau** [comment]
@mjsottile, if there's no rush, I can schedule some time next week to review :)

**Comment by mjsottile** [comment]
@nnadeau That works - next week is fine.

**Comment by mjsottile** [comment]
@whedon assign @nnadeau as reviewer

**Comment by whedon** [comment]
OK, @nnadeau is now a reviewer

**Comment by mjsottile** [comment]
:wave: @paul92, @innat : Would you be interested in reviewing this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by mjsottile** [comment]
@kaustubh-sadekar Just an update - I’m having some trouble finding a second reviewer.  This is not unique to your paper - at the moment I’m noticing it’s harder than usual to get responses from folks across reviews, both finding reviewers and getting reviews from people who agreed to review.  I assume it is in part due to the weird times right now and people having generally less capacity than usual.  I’ll keep trying and keep you up to date.

**Comment by mjsottile** [comment]
:wave: @ionlights Would you be interested in reviewing this submission for JOSS? Based on your information in the potential-reviewers spreadsheet, this appears to be near your areas of interest.  We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by ionlights** [comment]
👋 @mjsottile What's the desired timeline to review this? Until about Aug 15, I'm quite swamped. So I could start reviewing around then, but can't before.

**Comment by mjsottile** [comment]
@ionlights That should be fine - if you can perform the review in mid-August that would work.  Shall I add you as a reviewer?

**Comment by ionlights** [comment]
Sure! 🙂  If someone else can review sooner, just let me know.

**Comment by mjsottile** [comment]
@whedon add @ionlights as reviewer

**Comment by whedon** [comment]
OK, @ionlights is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2533.
