### ISSUE TITLE
[PRE REVIEW]: WikiRevParser: a Python Library for Parsing Wikipedia Revision Histories

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2427]
**Submitting author:** @ajoer (<a href="http://orcid.org/0000-0002-2568-4360">Anna Jørgensen</a>)
**Repository:** <a href="https://github.com/ajoer/WikiRevParser" target ="_blank">https://github.com/ajoer/WikiRevParser</a>
**Version:** 0.0.8
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ajoer. **Currently, there isn't an JOSS editor assigned** to your paper.

@ajoer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (335.4 files/s, 25488.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5            142             66            373
reStructuredText                 3             99             25            167
Markdown                         2             31              0             86
DOS Batch                        1              8              1             26
TeX                              1              0              0             17
make                             1              4              7              9
Bourne Shell                     1              1              0              2
-------------------------------------------------------------------------------
SUM:                            14            285             99            680
-------------------------------------------------------------------------------


Statistical information for the repository '2427' was gathered on 2020/07/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Anna Jørgensen                  29          1404           1123           87.50
Anna Katrine Jørgens             3           331             30           12.50

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Anna Jørgensen              383           27.3          3.0               13.32
Anna Katrine Jørgens        199           60.1          0.2                8.04
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.5210/fm.v24i5.9530 may be missing for title: Breaking news on Wikipedia: Collaborating, collating and competing
- https://doi.org/10.1177/1464884914545739 may be missing for title: Infoboxes and cleanup tags: Artifacts of Wikipedia newsmaking

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02427/joss.02427/10.21105.joss.02427.pdf)

**Comment by arfon** [comment]
@whedon query scope

**Comment by danielskatz** [comment]
@ajoer - The JOSS editors have determined that this submission is out of scope as a minor utility due to its small size. An alternative way of having the software be cited is to get a DOI for it via zenodo.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
