### ISSUE TITLE
[PRE REVIEW]: Multitaper.jl: A Julia package for frequency domain analysis of time series

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2428]
**Submitting author:** @lootie (<a href="http://orcid.org/0000-0003-3996-773X">Charlotte Haley</a>)
**Repository:** <a href="https://bitbucket.org/clhaley/Multitaper.jl" target ="_blank">https://bitbucket.org/clhaley/Multitaper.jl</a>
**Version:** v1.0.0
**Editor:** @VivianePons
**Reviewers:** @daviddewhurst, @felixcremer
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lootie. **Currently, there isn't an JOSS editor assigned** to your paper.

@lootie if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (672.1 files/s, 92410.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           16            232            161           1537
Markdown                         4            147              0            447
Jupyter Notebook                 6              0            947            198
TeX                              1             15              0            143
TOML                             1              3              0             20
-------------------------------------------------------------------------------
SUM:                            28            397           1108           2345
-------------------------------------------------------------------------------


Statistical information for the repository '2428' was gathered on 2020/07/02.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/LSP.2017.2719943 is OK
- 10.1109/ACSSC.2011.6190385 is OK

MISSING DOIs

- https://doi.org/10.1093/gji/ggz280 may be missing for title: A multitaper spectral estimator for time-series with missing data
- https://doi.org/10.1017/jfm.2018.366 may be missing for title: Frequency–wavenumber spectral analysis of spatio-temporal flows
- https://doi.org/10.1016/0098-3004(94)00067-5 may be missing for title: Multiple-taper spectral analysis: A stand-alone C-subroutine
- https://doi.org/10.1016/j.cageo.2008.06.007 may be missing for title: A Fortran 90 library for multitaper spectrum analysis
- https://doi.org/10.1007/s13137-011-0016-z may be missing for title: Spatiospectral concentration in the Cartesian plane
- https://doi.org/10.1098/rspa.2014.0101 may be missing for title: Spacing and shape of random peaks in non-parametric spectrum estimates
- https://doi.org/10.1109/proc.1982.12433 may be missing for title: Spectrum estimation and harmonic analysis
- https://doi.org/10.1109/jproc.2007.894712 may be missing for title: Solar Modal Structure of the Engineering Environment

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02428/joss.02428/10.21105.joss.02428.pdf)

**Comment by danielskatz** [comment]
👋 @VivianePons - would be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @VivianePons as editor

**Comment by whedon** [comment]
@VivianePons has been invited to edit this submission.

**Comment by lootie** [comment]
Reviewers: daviddewhurst, felixcremer, fneum, anowacki, declanol

@whedon generate pdf

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by VivianePons** [comment]
@whedon assign @daviddewhurst as reviewer

**Comment by whedon** [comment]
OK, @daviddewhurst is now a reviewer

**Comment by daviddewhurst** [comment]
@lootie I'm currently not able to install the package as directed by `README.md`.:

```
(v1.1) pkg> add git://bitbucket.org/clhaley/Multitaper.jl.git
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `git://bitbucket.org/clhaley/Multitaper.jl.git`
ERROR: failed to clone from git://bitbucket.org/clhaley/Multitaper.jl.git, error: GitError(Code:ERROR, Class:OS, failed to connect to bitbucket.org: Operation timed out)
```
However, **using `add https://bitbucket.org/clhaley/Multitaper.jl.git` works fine**. Just a heads-up for you (and other reviewers / editor) that they might encounter this as well.

**Comment by VivianePons** [comment]
@whedon add @felixcremer as reviewer

**Comment by whedon** [comment]
OK, @felixcremer is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2463.
