### ISSUE TITLE
[REVIEW]: SaffronTree: Fast, reference-free pseudo-phylogenomic trees from reads or contigs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#243]
**Submitting author:** @andrewjpage (<a href="http://orcid.org/0000-0001-6919-6062">Andrew Page</a>)
**Repository:** <a href="https://github.com/sanger-pathogens/saffrontree" target ="_blank">https://github.com/sanger-pathogens/saffrontree</a>
**Version:** v0.1.2
**Editor:** @biorelated
**Reviewer:** @brainstorm
**Archive:** <a href="http://dx.doi.org/10.6084/m9.figshare.4964378.v1" target="_blank">10.6084/m9.figshare.4964378.v1</a>

## Status

[![status](http://joss.theoj.org/papers/a001aa2b1e0d6068cd3da1295c9d8299/status.svg)](http://joss.theoj.org/papers/a001aa2b1e0d6068cd3da1295c9d8299)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a001aa2b1e0d6068cd3da1295c9d8299"><img src="http://joss.theoj.org/papers/a001aa2b1e0d6068cd3da1295c9d8299/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a001aa2b1e0d6068cd3da1295c9d8299/status.svg)](http://joss.theoj.org/papers/a001aa2b1e0d6068cd3da1295c9d8299)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/sanger-pathogens/saffrontree" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sanger-pathogens/saffrontree">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.2)?
- [x] **Authorship:** Has the submitting author (@andrewjpage) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @brainstorm it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @brainstorm - this is where the actual review should take place. Please shout if you have any problems working through the checklist above.

**Comment by brainstorm** [comment]
Hi @andrewjpage! I've successfully installed the python packages locally in an Anaconda python3 environment, but there seems to be assumptions about where "KMC" is setup and the tests end up failing:

```
(joss) romanvgs-Air:saffrontree romanvg$ ./run_tests.sh
Tests should not be run pathpipe-farm3
..E..Running: kmc -k10 -fq -ci10 -cx200 -t1 /Users/romanvg/tmp/saffrontree/saffrontree/tests/data/kmcfastq/S_typhi_CT18_chromosome_1.fastq.gz /Users/romanvg/tmp/saffrontree/tmp_samplekmers_m5_6c8b0/fastq_kmers /Users/romanvg/tmp/saffrontree/tmp_samplekmers_m5_6c8b0
.F......FE
======================================================================
ERROR: test_kmc_command (KmcDetectVersion_test.TestKmcVersionDetect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/romanvg/tmp/saffrontree/saffrontree/tests/KmcDetectVersion_test.py", line 11, in test_kmc_command
    k = KmcVersionDetect(False)
  File "/Users/romanvg/tmp/saffrontree/saffrontree/KmcVersionDetect.py", line 11, in __init__
    self.kmc_version = self.find_version()
  File "/Users/romanvg/tmp/saffrontree/saffrontree/KmcVersionDetect.py", line 21, in find_version
    kmc_output = check_output(["kmc"], universal_newlines=True)
  File "/Users/romanvg/.miniconda/envs/joss/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/romanvg/.miniconda/envs/joss/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/romanvg/.miniconda/envs/joss/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/romanvg/.miniconda/envs/joss/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'kmc'

======================================================================
ERROR: test_fastq_files (SaffronTree_test.TestSaffronTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/romanvg/tmp/saffrontree/saffrontree/tests/SaffronTree_test.py", line 40, in test_fastq_files
    st = SaffronTree(options)
  File "/Users/romanvg/tmp/saffrontree/saffrontree/SaffronTree.py", line 37, in __init__
    self.kmc_major_version = KmcVersionDetect(self.verbose).major_version()
  File "/Users/romanvg/tmp/saffrontree/saffrontree/KmcVersionDetect.py", line 11, in __init__
    self.kmc_version = self.find_version()
  File "/Users/romanvg/tmp/saffrontree/saffrontree/KmcVersionDetect.py", line 21, in find_version
    kmc_output = check_output(["kmc"], universal_newlines=True)
  File "/Users/romanvg/.miniconda/envs/joss/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/romanvg/.miniconda/envs/joss/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/romanvg/.miniconda/envs/joss/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/romanvg/.miniconda/envs/joss/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'kmc'

======================================================================
FAIL: test_running_kmc_command (KmcFastq_test.TestKmcFastq)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/romanvg/tmp/saffrontree/saffrontree/tests/KmcFastq_test.py", line 46, in test_running_kmc_command
    self.assertTrue(os.path.exists(os.path.join(k.temp_working_dir,'fastq_kmers.kmc_pre')))
AssertionError: False is not true

======================================================================
FAIL: test_running_intersection_and_counting_kmers (KmcIntersect_test.TestKmcIntersect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/romanvg/tmp/saffrontree/saffrontree/tests/KmcIntersect_test.py", line 64, in test_running_intersection_and_counting_kmers
    self.assertTrue(os.path.exists('results.kmc_pre'))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 15 tests in 0.051s

FAILED (failures=2, errors=2)
```

That is because after `source install_dependencies.sh`, KMC ends up under `build` directory:

```
$ find . -iname kmc
./build/kmc
```

Just a minor detail, the docker counterpart works fine!

**Comment by andrewjpage** [comment]
Hi @brainstorm, 
Thanks for trying the software out. The install dependancies script is for travis, so I've renamed it to avoid confusion and I've added [installation instructions for Anaconda](https://github.com/sanger-pathogens/saffrontree/blob/master/README.md).
Andrew

**Comment by brainstorm** [comment]
Fantastic! Thanks for that @andrewjpage for that, it worked like a charm. I'll move on to the functionality aspects of the package, thanks!

**Comment by brainstorm** [comment]
Just a minor observation as I proceed with the review, the following online newick tree viewer states that trees should start with parenthesis:

http://trex.uqam.ca/index.php?action=newick

The generated trees from the example data begin with `[&R]` instead... also the online tool claims that the object length names should not exceed 50 characters.

FigTree does work fine though, but other alternative and tested viewers/libraries for newick on the FAQ would be great to have.

**Comment by brainstorm** [comment]
Fantastic tool otherwise, was a pleasure to review/try it out, thanks! ;)

**Comment by andrewjpage** [comment]
Thanks @brainstorm for reviewing the software. I've added a note about the generated tree.

**Comment by biorelated** [comment]
Thank you @brainstorm for your review. @arfon please do you mind to merge and accept this work for publication?

**Comment by arfon** [comment]
@andrewjpage - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by andrewjpage** [comment]
I've popped the reviewed software on Figshare:

*https://doi.org/10.6084/m9.figshare.4964378.v1
<https://doi.org/10.6084/m9.figshare.4964378.v1>*

*Regards,*

*Andrew*

**Comment by arfon** [comment]
@whedon set 10.6084/m9.figshare.4964378.v1 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.6084/m9.figshare.4964378.v1" target="_blank">10.6084/m9.figshare.4964378.v1</a> is the archive.

**Comment by arfon** [comment]
@brainstorm - many thanks for your review here and to @biorelated for editing this one ✨ 

@andrewjpage - your submission is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00243 ⚡️ 🚀 💥 

In other news, this is the 100th accepted JOSS paper 🎉! Nice to see this coming from the Sanger (I worked in the Production Software Group in ~2008/2009)

**Comment by andrewjpage** [comment]
Thanks @arfon its great to have the privilege of being the 100th.  I also worked in Production Software from Sept 2009 to 2011, so must have just missed you.

**Comment by arfon** [comment]
Ha! Small world... 😁
