### ISSUE TITLE
[REVIEW]: pyomeca: An Open-Source Framework for Biomechanical Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2431]
**Submitting author:** @romainmartinez (<a href="http://orcid.org/0000-0001-9681-9448">Romain Martinez</a>)
**Repository:** <a href="https://github.com/pyomeca/pyomeca/" target ="_blank">https://github.com/pyomeca/pyomeca/</a>
**Version:** 2020.0.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @BKillen05, @mitkof6
**Archive:** <a href="https://doi.org/10.5281/zenodo.4012118" target="_blank">10.5281/zenodo.4012118</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/07ff3224d80639610c786723df121834/status.svg)](https://joss.theoj.org/papers/07ff3224d80639610c786723df121834)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/07ff3224d80639610c786723df121834"><img src="https://joss.theoj.org/papers/07ff3224d80639610c786723df121834/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/07ff3224d80639610c786723df121834/status.svg)](https://joss.theoj.org/papers/07ff3224d80639610c786723df121834)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pyomeca/pyomeca/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@BKillen05 & @ @mitkof6, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pyomeca/pyomeca/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@romainmartinez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pyomeca/pyomeca/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@romainmartinez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @BKillen05, @ @mitkof6 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.5334/jors.148 may be missing for title: xarray: N-D labeled Arrays and Datasets in Python
- https://doi.org/10.25080/majora-92bf1922-00a may be missing for title: Data structures for statistical computing in python
- https://doi.org/10.1109/mcse.2007.55 may be missing for title: Matplotlib: A 2D Graphics Environment
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy Array: A Structure for Efficient Numerical Computation
- https://doi.org/10.1016/j.cmpb.2016.11.007 may be missing for title: biomechZoo: An open-source toolbox for the processing, analysis, and visualization of biomechanical movement data
- https://doi.org/10.21105/joss.00927 may be missing for title: CusToM: a Matlab toolbox for musculoskeletal simulation
- https://doi.org/10.1007/s00530-019-00633-9 may be missing for title: RMoCap: an R language package for processing and kinematic analyzing motion capture data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2431 with the following error: 

 pandoc-citeproc: reference mitkof6 not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.371 }

Looks like we failed to compile the PDF

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2431 with the following error: 

 pandoc-citeproc: reference mitkof6 not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.371 }

Looks like we failed to compile the PDF

**Comment by Kevin-Mattheus-Moerman** [comment]
@romainmartinez can you check the reference mitkof6 mentioned in this error message? You can run `@whedon generate pdf` here to check if the paper compiles.

**Comment by romainmartinez** [comment]
> @romainmartinez can you check the reference mitkof6 mentioned in this error message? You can run @whedon generate pdf here to check if the paper compiles.

@Kevin-Mattheus-Moerman I don't have any references for `mitkof6`, which seems to be the reviewer's username.

In the current issue (#2431), @mitkof6 is displayed with two `@` while @BKillen05 has only one.
Maybe the problem is here?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon remove  @mitkof6 as reviewer

**Comment by whedon** [comment]
OK,  @mitkof6 is no longer a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon remove @mitkof6 as reviewer

**Comment by whedon** [comment]
OK, @mitkof6 is no longer a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @mitkof6 as reviewer

**Comment by whedon** [comment]
OK, @mitkof6 is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon remove @ @mitkof6 as reviewer

**Comment by whedon** [comment]
OK, @ @mitkof6 is no longer a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02431/joss.02431/10.21105.joss.02431.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev :point_up: I think this might be an interesting case to analyze. Somehow the system assigned the reviewer `@mitkof6` as `@ @mitkof6`, despite everything looking fine over at https://github.com/openjournals/joss-reviews/issues/2323#issuecomment-653506616. This surfaced when we got a paper compilation error and `whedon` oddly picked it up as a reference error in paper compilation. I was able to unassign the double @ version and assign the correct reviewer but this does seem like a funny kink in the cable somewhere.

**Comment by Kevin-Mattheus-Moerman** [comment]
@BKillen05 @mitkof6 @romainmartinez apologies for a minor bug in our system. It is now resolved and the draft paper is available here:  :point_right: [Check article proof :page_facing_up:](https://github.com/openjournals/joss-papers/blob/joss.02431/joss.02431/10.21105.joss.02431.pdf) :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reinvite @BKillen05 as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon re-invite @BKillen05 as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@bkillen05 please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon re-invite @mitkof6 as reviewer

**Comment by whedon** [comment]
@mitkof6 already has access.

**Comment by mitkof6** [comment]
https://github.com/pyomeca/pyomeca/issues/103

**Comment by romainmartinez** [comment]
> pyomeca/pyomeca#103

Should be fixed in [#104](https://github.com/pyomeca/pyomeca/pull/104), thank you.

**Comment by romainmartinez** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02431/joss.02431/10.21105.joss.02431.pdf)

**Comment by mitkof6** [comment]
https://github.com/pyomeca/pyomeca/issues/105

**Comment by mitkof6** [comment]
https://github.com/pyomeca/ezc3d/issues/108

**Comment by Kevin-Mattheus-Moerman** [comment]
@romainmartinez can you give an update on progress in relation to responding to the issues raised?

**Comment by romainmartinez** [comment]
Sorry for the delay @Kevin-Mattheus-Moerman , I plan to address the issues raised before the end of the week.

I'll update the status of the issues here:

- :heavy_check_mark: [Done in PR [#136](https://github.com/pyomeca/ezc3d/pull/136)] [Make install requires sudo (Linux) for copying Python bindings](https://github.com/pyomeca/ezc3d/issues/108) by @mitkof6 
- :white_check_mark: [Waiting for [PR #108](https://github.com/pyomeca/pyomeca/pull/108) to be merged] [Proper citation in JOSS](https://github.com/pyomeca/pyomeca/issues/103) by @mitkof6 
- :construction: [Work in progress] [Future directions](https://github.com/pyomeca/pyomeca/issues/105) by @mitkof6 
- :construction: [Work in progress] [Running EMG Example](https://github.com/pyomeca/pyomeca/issues/106) by @BKillen05 
- :construction: [Work in progress] [Additional examples for other data](https://github.com/pyomeca/pyomeca/issues/107) by @BKillen05

**Comment by mitkof6** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02431/joss.02431/10.21105.joss.02431.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@romainmartinez any more updates :point_up: ?

**Comment by Kevin-Mattheus-Moerman** [comment]
@mitkof6 I see your boxes are all ticked, are you happy to formulate a recommendation on this submission? E.g. accept?

**Comment by mitkof6** [comment]
Yes, I was OK with #105. The authors will have to update the manuscript based on our discussion.

**Comment by romainmartinez** [comment]
> @romainmartinez any more updates point_up ?

I still have two more points to address among the [issues](https://github.com/openjournals/joss-reviews/issues/2431#issuecomment-669236807).

I have one more point to address in [#105](https://github.com/pyomeca/pyomeca/issues/105).
I am waiting for @BKillen05 to approve [#107](https://github.com/pyomeca/pyomeca/issues/107).

**Comment by romainmartinez** [comment]
> Yes, I was OK with #105 The authors will have to update the manuscript based on our discussion.

Done in [PR #109](https://github.com/pyomeca/pyomeca/pull/109) @mitkof6.

**Comment by romainmartinez** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02431/joss.02431/10.21105.joss.02431.pdf)

**Comment by romainmartinez** [comment]
@Kevin-Mattheus-Moerman, with issue [#107](https://github.com/pyomeca/pyomeca/issues/107) just accepted and closed, [all issues](https://github.com/openjournals/joss-reviews/issues/2431#issuecomment-669236807) have been addressed 🎉 .

Perhaps @mitkof6 could confirm that the modifications made in the paper [here](https://github.com/pyomeca/pyomeca/pull/109) are suitable for him.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mitkof6 it looks like changes were made to the paper. Can you review them? :point_up: thanks! 

@BKillen05 your only unticked box is "references". Can you comment on that or can that box be ticked now too? 

@mitkof6, @BKillen05, if, after reviewe the changes made, you are happy to formulate a recommendation e.g. to accept this submission, please do so. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5334/jors.148 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1016/j.cmpb.2016.11.007 is OK
- 10.21105/joss.00927 is OK
- 10.1007/s00530-019-00633-9 is OK
- 10.1016/0021-9290(74)90060-8 is OK
- 10.1016/j.simpat.2006.09.001 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mitkof6** [comment]
On my part I accept the paper. Congratulations to the authors for their nice work.

**Comment by BKillen05** [comment]
@Kevin-Mattheus-Moerman I have checked the references and now checked this box

As @mitkof6  , I am happy with the changes the authors have made to the documentation and also the manuscript.

Congratulations and good work from the authors

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02431/joss.02431/10.21105.joss.02431.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@romainmartinez 

I've reviewed your paper. Here are some final comments (fee free to disagree with these): 

- [ ] Throughout this paper it seems to be the word "biomechanics" is used to refer to "musculoskeletal biomechanics", or at least biomechanics research featuring motion capture data. Given this, the following sentence (and some others) feels overly general: `While biomechanics branches into several subfields, the data used are remarkably similar.`. This may be true for musculoskeletal biomechanics research, however for image-based modelling and soft tissue biomechanics (a domain I work in) tables and scalar 1D data sets are rarer than multidimensional and multi-model image data (like 3D MRI, CT, and stereo-photography data). If you agree that the focus on musculoskeletal biomechanics is more accurate perhaps rephrase the first paragraph and perhaps wording throughout the text. This is only a recommendation, feel free to argue your way out of it. 

- [ ] Please consider (suggestion, not required) to replace `not free of charge` by `proprietary`

- [ ] Capitalize `python` -> `Python` in the text

- [ ] Consider rephrasing `By offering a single, efficient and flexible implementation, pyomeca standardizes these procedures and avoids wasting valuable research time writing functions that have, sometimes, nothing to do with the research interests`, e.g. something like `By offering a single, efficient, and flexible implementation, pyomeca standardizes these procedures, freeing up valuable research time, thereby allowing researchers to focus on the scientific research questions at hand.`

- [ ] `...which is a step towards the adoption of programming in biomechanics`, Perhaps rephrase this sentence. This is perhaps too general again. Programming is used in biomechanics research quite intensively. It should be used more but this sentence seems confusing to me. Do you meant to say that these tools enhance reproducibility by enabling automated and code based analysis (as opposed to manual)?

- [ ] Should this `the xarray features set` be `the xarray feature set`?

- [ ] Spell out/introduce the EMG acronym

- [ ] Should this `skin markers position` be `skin marker positions`(check I think this occurs twice in the text)?

- [ ] In Figure 4 only the red, brown and purple lines can be distinguished. If this was intentional ignore this but if not consider changing the plotting order/type of visualization so more curves can be seen. 

- [ ] You mention `numpy, scipy, matplotlib and xarray`, could you also cite these works? 

If you implement changes please call `@whedon generate pdf` here to update the article proof.

**Comment by romainmartinez** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02431/joss.02431/10.21105.joss.02431.pdf)

**Comment by romainmartinez** [comment]
Thanks for your comments @Kevin-Mattheus-Moerman.

> - [x] Throughout this paper it seems to be the word "biomechanics" is used to refer to "musculoskeletal biomechanics", or at least biomechanics research featuring motion capture data. Given this, the following sentence (and some others) feels overly general: While biomechanics branches into several subfields, the data used are remarkably similar.. This may be true for musculoskeletal biomechanics research, however for image-based modelling and soft tissue biomechanics (a domain I work in) tables and scalar 1D data sets are rarer than multidimensional and multi-model image data (like 3D MRI, CT, and stereo-photography data). If you agree that the focus on musculoskeletal biomechanics is more accurate perhaps rephrase the first paragraph and perhaps wording throughout the text. This is only a recommendation, feel free to argue your way out of it.

You are absolutely right, done in [`45429fa`](https://github.com/romainmartinez/pyomeca/commit/45429fa3c1ed06146358e4aca2c5e611793497c5).

> - [x] Please consider (suggestion, not required) to replace not free of charge by proprietary

Done in [`b30b116`](https://github.com/romainmartinez/pyomeca/commit/b30b116c470994d142f66cee9f96045f2e822c41).

> - [x] Capitalize python -> Python in the text

Done in [`37b7a55`](https://github.com/romainmartinez/pyomeca/commit/37b7a551e7504589105d50f7f7efd9336ca64542).

> - [x] Consider rephrasing By offering a single, efficient and flexible implementation, pyomeca standardizes these procedures and avoids wasting valuable research time writing functions that have, sometimes, nothing to do with the research interests, e.g. something like By offering a single, efficient, and flexible implementation, pyomeca standardizes these procedures, freeing up valuable research time, thereby allowing researchers to focus on the scientific research questions at hand.

Done in [`0ac60bb`](https://github.com/romainmartinez/pyomeca/commit/0ac60bb490d4f64f82d32d9f5ecf89f9a903d655).

> - [x] ...which is a step towards the adoption of programming in biomechanics, Perhaps rephrase this sentence. This is perhaps too general again. Programming is used in biomechanics research quite intensively. It should be used more but this sentence seems confusing to me. Do you meant to say that these tools enhance reproducibility by enabling automated and code based analysis (as opposed to manual)?

Done in [`6660860`](https://github.com/romainmartinez/pyomeca/commit/66608605e1ea63e811b57abb4a58e53ebc698d62).
Is this sentence better: "By providing labeled querying and computation, efficient algorithms and persistent metadata, the integration of `xarray` facilitates usability, which seems to be relevant in a context where scientists do not always receive extensive training in programming."

> - [x]  Should this the xarray features set be the xarray feature set?

Done in [`331d680`](https://github.com/romainmartinez/pyomeca/commit/331d680e59c982c3dfd0416f9828b6658a7642c1).

> - [x] Spell out/introduce the EMG acronym

Done in [`04716e2`](https://github.com/romainmartinez/pyomeca/commit/04716e2dfddb9f43ef982abab31247b325dfe27e).

> - [x] Should this skin markers position be skin marker positions(check I think this occurs twice in the text)?

Done in [`51805d7`](https://github.com/romainmartinez/pyomeca/commit/51805d711e305aabc9049d3d2a368bb25d450167).

> - [x] In Figure 4 only the red, brown and purple lines can be distinguished. If this was intentional ignore this but if not consider changing the plotting order/type of visualization so more curves can be seen.

The curves intentionally overlap to show the raw data without taking up too much space. The purpose of this figure is to show that the data is raw, rather than to identify individual curves.
The following figure (5) shows the individual curves.

> - [x] You mention numpy, scipy, matplotlib and xarray, could you also cite these works?

Done in [`ddc1b3a`](https://github.com/romainmartinez/pyomeca/commit/ddc1b3a1546d2cd9a6a4ebb2c1d82ca4a4fa8b9a).
Thanks for the heads up, these libraries were cited in the rest of the paper except in the acknowledgements section.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02431/joss.02431/10.21105.joss.02431.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5334/jors.148 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1016/j.cmpb.2016.11.007 is OK
- 10.21105/joss.00927 is OK
- 10.1007/s00530-019-00633-9 is OK
- 10.1016/0021-9290(74)90060-8 is OK
- 10.1016/j.simpat.2006.09.001 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@romainmartinez I've checked my requested changes and all seems fine now. Below are final steps. 

- [ ] Can you archive a copy of the software on ZENODO and report back here with the DOI of the archived version (do not alter or set the DOI yourself, please accept the ZENODO generated DOI)? Please ensure that the title and author list is the same as the JOSS paper for this ZENODO archived version (you may need to edit this meta-data manually). 

- [ ] Can you inform me about the version tag for the published work. Is it still at `2020.0.1` or has it moved on?

**Comment by romainmartinez** [comment]
Thanks @Kevin-Mattheus-Moerman.

> Can you archive a copy of the software on ZENODO and report back here with the DOI of the archived version (do not alter or set the DOI yourself, please accept the ZENODO generated DOI)? Please ensure that the title and author list is the same as the JOSS paper for this ZENODO archived version (you may need to edit this meta-data manually).

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4012118.svg)](https://doi.org/10.5281/zenodo.4012118)

> Can you inform me about the version tag for the published work. Is it still at 2020.0.1 or has it moved on?

Yes, the current version is still `2020.0.1`.

> Your paper is about to be accepted in JOSS. I recommend that you review the paper yourself once more, and that you also check the author list, affiliations, and the acknowledgements section for accuracy. (call @whedon generate pdf here to update the paper).

I reread the paper, checked the author list, affiliations, and the acknowledgements section for accuracy, and all seems fine.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.4012118 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4012118" target="_blank">10.5281/zenodo.4012118</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@romainmartinez Minor point, the paper title is `pyomeca: An Open-Source Framework for Biomechanical Analysis`, while the archive is: `Pyomeca: a Python toolbox for biomechanics analysis`. 

- [ ] Can you update the archive title to match that of the paper (fix use of capital letters)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5334/jors.148 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1016/j.cmpb.2016.11.007 is OK
- 10.21105/joss.00927 is OK
- 10.1007/s00530-019-00633-9 is OK
- 10.1016/0021-9290(74)90060-8 is OK
- 10.1016/j.simpat.2006.09.001 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1700

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1700, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by romainmartinez** [comment]
> Can you update the archive title to match that of the paper (fix use of capital letters)

@Kevin-Mattheus-Moerman, It is done. Sorry I was not sure if the DOI was attached to the GitHub repo or the paper.

**Comment by kthyng** [comment]
Hi @romainmartinez, I am the EIC on rotation this week and will help finish publishing your paper. Your references were not capitalized all correctly. Please check the edits I made [here](https://github.com/pyomeca/pyomeca/pull/112) and if you agree, merge them in.

**Comment by romainmartinez** [comment]
> Hi @romainmartinez, I am the EIC on rotation this week and will help finish publishing your paper. Your references were not capitalized all correctly. Please check the edits I made here and if you agree, merge them in.

Hi @kthyng and thanks for the edits. I just merged them.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5334/jors.148 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1016/j.cmpb.2016.11.007 is OK
- 10.21105/joss.00927 is OK
- 10.1007/s00530-019-00633-9 is OK
- 10.1016/0021-9290(74)90060-8 is OK
- 10.1016/j.simpat.2006.09.001 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1703

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1703, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1301515840567881730) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1704
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02431](https://doi.org/10.21105/joss.02431)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations to @romainmartinez on your new publication! Thanks to @Kevin-Mattheus-Moerman and reviewers @BKillen05 and @mitkof6. This process couldn't happen without your time and expertise!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02431/status.svg)](https://doi.org/10.21105/joss.02431)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02431">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02431/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02431/status.svg
   :target: https://doi.org/10.21105/joss.02431
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02431/status.svg)](https://doi.org/10.21105/joss.02431)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by romainmartinez** [comment]
Thanks @BKillen05, @mitkof6 and @Kevin-Mattheus-Moerman for your time and your valuable comments.
I would also like to thank the JOSS journal and @kthyng for the smooth and fresh workflow for paper publication.
