### ISSUE TITLE
[PRE REVIEW]: DetectorChecker: analyzing patterns of defects in detector screens

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2434]
**Submitting author:** @tomaslaz (<a href="http://orcid.org/0000-0002-8351-9857">Tomas Lazauskas</a>)
**Repository:** <a href="https://github.com/alan-turing-institute/DetectorChecker" target ="_blank">https://github.com/alan-turing-institute/DetectorChecker</a>
**Version:** 1.0.8
**Editor:** @fboehm
**Reviewers:** @janfreyberg
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tomaslaz. **Currently, there isn't an JOSS editor assigned** to your paper.

@tomaslaz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.78 s (48.6 files/s, 73107.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              9              0              0          50480
R                               17            919           1193           2161
HTML                             1             89              5            878
Markdown                         5            149              0            424
Rmd                              1            158            256            205
TeX                              1             17              0            111
JSON                             1              0              0             48
YAML                             2              8              2             12
make                             1              6              0             11
-------------------------------------------------------------------------------
SUM:                            38           1346           1456          54330
-------------------------------------------------------------------------------


Statistical information for the repository '2434' was gathered on 2020/07/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Oscar Giles                      2           107            107          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1088/0031-9155/42/1/001 is OK
- 10.1002/9781118658222 is OK
- 10.1002/bimj.201600178 is OK

MISSING DOIs

- https://doi.org/10.1038/146150e0 may be missing for title: Statistical method from the viewpoint of quality control

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02434/joss.02434/10.21105.joss.02434.pdf)

**Comment by kyleniemeyer** [comment]
Hi @tomaslaz, while we are finding an editor to handle your submission, could you revise your paper to include a Statement of Need? This is now a required section for JOSS articles, as described in our [documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Thanks!

**Comment by kyleniemeyer** [comment]
Hi @fboehm, could you take this submission on for us?

**Comment by kyleniemeyer** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by fboehm** [comment]
Yes, I'm happy to be the editor for this submission. 
@whedon assign @fboehm as editor

**Comment by kyleniemeyer** [comment]
@fboehm thanks! FYI, I think whedon commands need to be by themselves in a comment.

**Comment by kyleniemeyer** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
you're welcome. And yes, I guess you're right about whedon commands :)

**Comment by fboehm** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by fboehm** [comment]
@whedon assign @janfreyberg as reviewer

**Comment by whedon** [comment]
OK, @janfreyberg is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2474.
