### ISSUE TITLE
[REVIEW]: OMG: A Scalable and Flexible Simulation and TestingEnvironment Toolbox for Intelligent Microgrid Control

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2435]
**Submitting author:** @stheid (<a href="http://orcid.org/0000-0002-9461-7372">Stefan Heid</a>)
**Repository:** <a href="https://github.com/upb-lea/openmodelica-microgrid-gym" target ="_blank">https://github.com/upb-lea/openmodelica-microgrid-gym</a>
**Version:** 0.2.0-2
**Editor:** @dhhagan
**Reviewer:** @katyhuff, @gonsie
**Archive:** <a href="https://doi.org/10.5281/zenodo.4041278" target="_blank">10.5281/zenodo.4041278</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/bdb34bbb22dcdb5f7bee986ef2064d02/status.svg)](https://joss.theoj.org/papers/bdb34bbb22dcdb5f7bee986ef2064d02)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/bdb34bbb22dcdb5f7bee986ef2064d02"><img src="https://joss.theoj.org/papers/bdb34bbb22dcdb5f7bee986ef2064d02/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/bdb34bbb22dcdb5f7bee986ef2064d02/status.svg)](https://joss.theoj.org/papers/bdb34bbb22dcdb5f7bee986ef2064d02)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/upb-lea/openmodelica-microgrid-gym" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@katyhuff & @gonsie, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dhhagan know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/upb-lea/openmodelica-microgrid-gym">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@stheid) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/upb-lea/openmodelica-microgrid-gym">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@stheid) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed? (unable to evaluate)
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.) (unable to evaluate)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @katyhuff, @gonsie it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02435/joss.02435/10.21105.joss.02435.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.5334/jors.188 may be missing for title: PyPSA: Python for Power System Analysis
- https://doi.org/10.1109/tpwrs.2018.2829021 may be missing for title: Pandapower: An Open-Source Python Tool for Convenient Modeling, Analysis, and Optimization of Electric Power Systems
- https://doi.org/10.1109/tie.2012.2194969 may be missing for title: Advanced Control Architectures for Intelligent Microgrids, Part I: Decentralized and Hierarchical Control
- https://doi.org/10.1109/tie.2012.2196889 may be missing for title: Advanced Control Architectures for Intelligent Microgrids, Part II: Power Quality, Energy Storage, and AC/DC Microgrids

INVALID DOIs

- None
```

**Comment by dhhagan** [comment]
@whedon remind @katyhuff in 2 days

**Comment by whedon** [comment]
Reminder set for @katyhuff in 2 days

**Comment by dhhagan** [comment]
@whedon remind @gonsie in 2 days

**Comment by whedon** [comment]
Reminder set for @gonsie in 2 days

**Comment by whedon** [comment]
:wave: @katyhuff, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @gonsie, please update us on how your review is going.

**Comment by katyhuff** [comment]
## katyhuff Review
This is an interesting tool for testing control system approaches for microgrids. I'm genuinely interested in testing it out further and doing more exploring with it. I think the purpose of the tool is fairly clear and the audience certainly exists. It builds cleanly from source and the pip install approach works cleanly as well. While the build succeeds, the tests fail on my MacBook (`pyfmi.fmi.FMUException: Error loading the binary. The FMU contains no binary for this platform.`). Upon reflection, the README indicated this might be the case. So, I redid this on my ubuntu machine and things went better. The tests themselves cover the majority of functions in the code, though most are more in the style of integration tests rather than unit tests. In those cases, the expected results take the form of hdf5 files and are named somewhat vaguely (test_main2, test_main3), so the purpose of these particular tests is a bit mysterious to a new user attempting to learn from them. The API has documentation is available online and there are appropriate guides for new developers and users. I tried running some of the examples, which went ok. There are a few boxes that I'm not ready to check. I'll make specific comments regarding each of those items.


### Contribution and authorship:
The submitting author (@stheid) has made major contributions to the software and the full list of paper authors seems complete. However, one entry seems to be potentially worth clarifying in the text of the paper. The contribution from Eyke Hüllermeier is not clear based on the repository history. Presumably, this individual (Eyke Hüllermeier) has contributed conceptually and intellectually. They do not seem to have committed code to the repository. This is fine, as far as I'm concerned, but should be clarified, either here in this review discussion, or potentially in the acknowledgments section of the text.

### Functionality: 
If the functional claims of the software were a bit more clear in the paper, then I could better confirm them. A few of the functional claims statements (particularly in the bulleted list in the paper) are a bit vague (see comments in PDF attached at the bottom of this review. Clear examples of the use of the tool are found in the codebase and will be sufficient to confirm this functionality when aspects like "many software auxiliaries" are made more precise.


### Performance:
The authors briefly mention that this tool is for "fast simulation" but no quantitative measure of "fast" is provided, so I have chosen to check this box at the moment. However, I would recommend that the authors either drop the "fast" qualifier or quantify it specifically.  This is just a suggestion and I'll leave it up to the authors whether to incorporate it.

### Installation Instructions:
I've checked this box, but I would recommend that the readme state more clearly that there are no FMU binaries for MacOSX, so one must build them oneself (and, in order to do so must install omc on their mac and run the fmu creation script.)  This is just a suggestion and I'll leave it up to the authors whether to incorporate it.

### Example Usage:
The repository contains examples which are clear and are discussed well in the readme. The paper could potentially benefit from a brief explanation of one of those examples. But, it's not 100% necessary. It just might bring the conceptual level of the paper discussion up to the level of discussing real world applications. This is just a suggestion and I'll leave it up to the authors whether to incorporate it.

### Quality of writing: 
There are a handful of instances in which the paper is not very clear. Actually, the README was much more informative, in part because it used clearer, more direct language. I recommend the authors consider improving their paper clarity by approaching the clear direct style of the README. In any case, I have made some scribbles on [the pdf here](https://github.com/openjournals/joss-reviews/files/4963806/10.21105.joss.02435.pdf)
 which give suggestions regarding grammar, sentence structure, and diction which might improve the clarity of the work. 

### References: 
The references are in great need of review and effort. The list of references may not be complete. It seems as if there are some software tools heavily used which are either not cited (PyFMI) or possibly cited improperly (Open Modelica). I have made notes in [the pdf here](https://github.com/openjournals/joss-reviews/files/4963806/10.21105.joss.02435.pdf) regarding this. 
All references are missing DOIs. Whedon picked up on the following, but a few more DOIs are missing beyond those. Please include all of the DOIs I have noted as missing in [the pdf](https://github.com/openjournals/joss-reviews/files/4963806/10.21105.joss.02435.pdf). Note especially the missing DOIs noticed by whedon:

- https://doi.org/10.5334/jors.188 may be missing for title: PyPSA: Python for Power System Analysis
- https://doi.org/10.1109/tpwrs.2018.2829021 may be missing for title: Pandapower: An Open-Source Python Tool for Convenient Modeling, Analysis, and Optimization of Electric Power Systems
- https://doi.org/10.1109/tie.2012.2194969 may be missing for title: Advanced Control Architectures for Intelligent Microgrids, Part I: Decentralized and Hierarchical Control
- https://doi.org/10.1109/tie.2012.2196889 may be missing for title: Advanced Control Architectures for Intelligent Microgrids, Part II: Power Quality, Energy Storage, and AC/DC Microgrids

**Comment by stheid** [comment]
@katyhuff Thanks a lot for the detailed review! We are currently working on incorporating your issues and will come back to you in the upcomming weeks.

**Comment by stheid** [comment]
@katyhuff The master branch contains all changes proposed (https://github.com/upb-lea/openmodelica-microgrid-gym/commit/4d902722f090d8b0fb81b1b0c7ac5f0434338127).

right now the CI does not properly build the master, but this issue is already solved in develop. however, the develop is currently not in a mergable state, therefore i only cherry picked the changes to the pdf and readme from that branch

**Comment by stheid** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02435/joss.02435/10.21105.joss.02435.pdf)

**Comment by dhhagan** [comment]
Reminder set for @gonsie in 2 days

**Comment by stheid** [comment]
@gonsie Is there anything we can do to continue the review progress.

@dhhagan maybe can you send out a new reminder?

**Comment by dhhagan** [comment]
Hi @stheid - I will send another reminder to @gonsie but otherwise will give them one more week to complete their review within the six-week period.

**Comment by gonsie** [comment]
## gonsie review

Sorry for the delay in my review. Unfortunately, I had many technical issues: I only have access to a Mac and I seem unable to mark the checkboxes in my review section at the top of this issue 😞 That said, here is my best effort at reviewing the documentation and paper.

- [X] conflict of interest
- [X] code of conduct
- [X] repo
- [X] License
- [X] contribution and authorship
- [X] installation
  Does not install on Mac. Unclear why this is not possible, nothing in PyFMI documentation indicates that Mac is an issue, yet pip install fails. Readme does make a note of this.
- [ ] functionality **unable to evaluate**
- [ ] performance **unable to evaluate**
- [ ] statement of need
  Does not exist within documentation
- [ ] installation instructions
  Make a note of the issues with Mac on documentation page.
- [ ] example usage
  The examples seem incomplete (though I may be missing some context). The pages under Basic Examples are incomplete and missing instructions/details. The ‘creating an environment' page does not have any instructions. The image on 'creating an agent...' page does not load correctly.
- [X] functionality documentation
- [X] automated tests
- [X] community guidelines
  It would be great if the CONTRIBUTING guide could be found on the website.
- [ ] summary
  The paper starts with the statement of need and never quite provides a clear summary of the contribution of this software. In one paragraph, please identify the key contributions of this software.
- [X] statement of need
- [ ] state of the field
  It would be great if the features section clearly identified which aspects are unique contributions of this work. Point 3 mentions "easy exchange of models between computing platforms", citing PyFMI. Yet, PyFMI is a limiting factor when building this software for Mac. Does OMG contribute to the portability, or merely take advantage of existing (or not) portability of its dependencies?
  This features section also mentions that OMG many examples, use cases, and software auxiliaries. Please identify these (only examples are made explicit) or cite your arxiv whitepaper.
  The 'state of the field' section is missing any comparison with similar work.
- [ ] quality of writing
  Needs some grammatical edits. Both "i.e." and "e.g." should be followed by a comma (e.g., like so).
- [ ] references
  Some references in the area machine learning / reinforcement learning are needed.

**Comment by stheid** [comment]
@gonsie Thank you for your review. We will discuss it this friday in our team and try to also find a solution for mac, but it will probably be impossible to provide lasting OSX support as our group does not have regular access to a Mac.

In general it is possible to use FMI on Mac, but the precompiled FMUs provided by us are only built for Linux and Windows as we have not mac available and didn't deem the work in crosscompilation reasonable.

**Comment by gonsie** [comment]
Thanks @stheid. Perhaps a container image could be made available? 

In any case, I’m sure that @katyhuff ‘s review covers most of the issues with actually running the software.

**Comment by stheid** [comment]
You are absolutely right. Something went broken with the linking to the source code, perhaps we renamed files. We will definetly check it again. Thanks a lot for discovering that !

**Comment by stheid** [comment]
Dear @gonsie, all changes are now merged to master.

**Comment by dhhagan** [comment]
@whedon remind @gonsie in 3 days

**Comment by whedon** [comment]
Reminder set for @gonsie in 3 days

**Comment by whedon** [comment]
:wave: @gonsie, please update us on how your review is going.

**Comment by dhhagan** [comment]
@whedon remind @gonsie in 2 days

**Comment by whedon** [comment]
Reminder set for @gonsie in 2 days

**Comment by whedon** [comment]
:wave: @gonsie, please update us on how your review is going.

**Comment by gonsie** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02435/joss.02435/10.21105.joss.02435.pdf)

**Comment by gonsie** [comment]
@stheid Thanks for the changes. I’m satisfied with my review.

@dhhagan Thanks, I’ve completed my review.

**Comment by dhhagan** [comment]
Hi @katyhuff - any chance you've had time to review the proposed changes by @stheid per your review? Thanks!

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3384/ecp18154206 is OK
- 10.1109/MPE.2008.918718 is OK
- 10.1016/j.energy.2017.05.123 is OK
- 10.5334/jors.188 is OK
- 10.1109/TPWRS.2018.2829021 is OK
- 10.1109/TIE.2012.2194969 is OK
- 10.1109/TIE.2012.2196889 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by katyhuff** [comment]
@dhhagan I have had a chance to review and I'm willing to accept, though I still have one concern:

Most of my comments were either optional or were handled by the authors. My concern about functionality was primarily regarding the clarity of examples and clarity of the functional claims in the paper. I made a comment previously that the functional claims of the software should be made more clear in the paper. The authors added a brief list of keywords to clarify what was meant by "auxiliaries," which helps. But, I still think the paper could benefit from even more clarity regarding exactly what is being claimed as functionality contributed by the work.

**Comment by stheid** [comment]
@katyhuff Thanks for the additional clarification.

We had another discussion in the Team, but we find it difficult to add more than the bulleted list we have added. Therefore we would ask, if it would be possible to successfully close the review with the given state.

**Comment by katyhuff** [comment]
Ok. If you feel it is as clear as it can be, then the final assessment is in the hands of @dhhagan.

**Comment by dhhagan** [comment]
@katyhuff Thanks for your feedback and review. @stheid: I would like to see a bit more information about the *many software auxiliaries* listed in the **Features** section. It doesn't currently tell me what is possible/available, which I think would be beneficial and help make the paper itself more clear. In addition, there are a few areas where the language could be cleaned up - I will send a PR with suggestions in a little bit and you can take/leave the ones you want and/or feel are necessary.

**Comment by dhhagan** [comment]
@stheid I've made a PR (https://github.com/upb-lea/openmodelica-microgrid-gym/pull/81) with some suggested text changes in addition to what was mentioned above about expanding the clarity of examples and *many software auxiliaries* listed above. Please let me know when you've had time to review these and I'll take another look.

**Comment by stheid** [comment]
Thank you very much for the PR, it is already merged :)

Additionally, we clarified this paragraph further. https://github.com/upb-lea/openmodelica-microgrid-gym/commit/de90dc9a74c1bcbe2581f7d680cfa2879ea9f6e6

**Comment by dhhagan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02435/joss.02435/10.21105.joss.02435.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02435/joss.02435/10.21105.joss.02435.pdf) :page_facing_up: :point_left:

**Comment by dhhagan** [comment]
@Stefan-Heimersheim Thanks for those updates. Can you please create an archive of your repo using Zenodo, FigShare or similar? Once that's done, please report the DOI of the archive back here. Let me know if you need any help with this.

**Comment by stheid** [comment]
It seems like Zenodo forces us to make a new release in order to get a DOI. We are currently discussing it we make a small release just for this technical reasons or if we wait for the master to be in release worthy shape.

**Comment by stheid** [comment]
This should be the DOI https://doi.org/10.5281/zenodo.4041278

Zenodo seems to have issues in their infrastructure right now, because the creation of this DOI took more than 4 hours. Therefore i think it should not consern that the DOI cannot be resolved yet. Hopefully it will work tomorrow.

**Comment by dhhagan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3384/ecp18154206 is OK
- 10.1109/MPE.2008.918718 is OK
- 10.1016/j.energy.2017.05.123 is OK
- 10.5334/jors.188 is OK
- 10.1109/TPWRS.2018.2829021 is OK
- 10.1109/TIE.2012.2194969 is OK
- 10.1109/TIE.2012.2196889 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dhhagan** [comment]
@stheid It looks like the Zenodo archive doesn't contain the full/correct author list. Could you correct that and then post the final OMG version and DOI archive? As soon as that's updated, I can accept this manuscript. 👍

**Comment by stheid** [comment]
Oh, thanks a lot. I completely overlooked that i have to edit the entry to be consistent. Its corrected now.

I think the DOI did not change. As said currently the versions state is for the technical reason in a bit of an unfortunate state, and we are not ready to roll out a new release right now. So we would keep everything at 0.2.0-2 if this is ok.

Where is the DOI of the release connected to JOSS. Do we need to update the something for future releases, because i assume after the reviewing process here is finished, the project will still continue to grow.

**Comment by dhhagan** [comment]
@arfon Can you chime in on the last part of @stheid's request above?

**Comment by arfon** [comment]
> I think the DOI did not change. As said currently the versions state is for the technical reason in a bit of an unfortunate state, and we are not ready to roll out a new release right now. So we would keep everything at 0.2.0-2 if this is ok.

The thing we (JOSS) care about here is that the archive of the software includes the changes that have resulted from this review.

> Where is the DOI of the release connected to JOSS. Do we need to update the something for future releases, because i assume after the reviewing process here is finished, the project will still continue to grow.

We reference this archive in the JOSS metadata and it's linked to from the paper and the website.

**Comment by stheid** [comment]
> The thing we (JOSS) care about here is that the archive of the software includes the changes that have resulted from this review.

that is the case! :)

> We reference this archive in the JOSS metadata and it's linked to from the paper and the website.

In that case maybe using the version-agnostic DOI is better? 10.5281/zenodo.4041277
But in any case if you are fine with everything, we are too.

Thanks a lot for clearing things up.

**Comment by arfon** [comment]
I think we would prefer to link to `10.5281/zenodo.4041278` as this is the version most closely associated with the review. Don't forget that the paper also links to the software repository in the margin too so readers will have a link to the live software repository to access the latest version of the code.

**Comment by stheid** [comment]
yeah, thats ok for us.

**Comment by dhhagan** [comment]
@whedon set 10.5281/zenodo.4041278 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4041278" target="_blank">10.5281/zenodo.4041278</a> is the archive.

**Comment by dhhagan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3384/ecp18154206 is OK
- 10.1109/MPE.2008.918718 is OK
- 10.1016/j.energy.2017.05.123 is OK
- 10.5334/jors.188 is OK
- 10.1109/TPWRS.2018.2829021 is OK
- 10.1109/TIE.2012.2194969 is OK
- 10.1109/TIE.2012.2196889 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1764

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1764, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@dhhagan thanks for editing this one. I'll process this now for acceptance in JOSS. One point, for future reference, please always check that the ZENODO meta data (authors, title, version tag) match that of the paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
@stheid I'll be processing this work for acceptance in JOSS. Please work on the remaining minor points below, thanks: 

- [ ] The reviewed submission is at `v0.1.3` while the provided archived version is at `v0.2.0-2`. Please create a new archived version for `v0.1.3`. When you do this also make sure the ZENODO meta-data for the author names and the title match as well. **You may need to manually edit this.** 

- [ ] Please add city and country information for all affiliations (do not use acronyms for countries)

- [ ] This work is about to be accepted in JOSS. We recommend you proofread your paper once more yourself at this stage, and also verify the accuracy of the author names, affiliations, and acknowledgments.

**Comment by stheid** [comment]
That all sounds good :)

@Kevin-Mattheus-Moerman How to create a zenodo archive of a already released version. I have the impression this is impossible (that was the only reason we created 0.2.0-2 in the first place)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 0.2.0-2 as version

**Comment by whedon** [comment]
OK. 0.2.0-2 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@stheid I've now changed the version tag listed for this review so that seems to have removed that discrepancy. Please still update the archive title/authors if these deviate from the paper.

**Comment by stheid** [comment]
- The authors already matched up, i just alligned the ordering.
- i corrected the title.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3384/ecp18154206 is OK
- 10.1109/MPE.2008.918718 is OK
- 10.1016/j.energy.2017.05.123 is OK
- 10.5334/jors.188 is OK
- 10.1109/TPWRS.2018.2829021 is OK
- 10.1109/TIE.2012.2194969 is OK
- 10.1109/TIE.2012.2196889 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1776

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1776, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@stheid 

- [ ] Please add city/county information to your affiliations

**Comment by stheid** [comment]
![image](https://user-images.githubusercontent.com/2736207/94928182-93d0ca80-04c3-11eb-911c-14381997753b.png)
like this? To be honest i don't understand where exactly the issue is.

**Comment by Kevin-Mattheus-Moerman** [comment]
@stheid please edit the affiliation in the YAML at the top of your `paper.md` file.

**Comment by stheid** [comment]
Like so https://github.com/upb-lea/openmodelica-microgrid-gym/commit/6eeabca6163c399f8ab494f57c297d3235b81fbf?

**Comment by Kevin-Mattheus-Moerman** [comment]
> Like so [upb-lea/openmodelica-microgrid-gym@6eeabca](https://github.com/upb-lea/openmodelica-microgrid-gym/commit/6eeabca6163c399f8ab494f57c297d3235b81fbf)?

@stheid yes but please also add the city

**Comment by stheid** [comment]
https://github.com/upb-lea/openmodelica-microgrid-gym/commit/a259b405cf4760bc3af1979f6d51b4ce2e00c555

Sorry, i thought it would be clear enough ^^;  But i added it now.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3384/ecp18154206 is OK
- 10.1109/MPE.2008.918718 is OK
- 10.1016/j.energy.2017.05.123 is OK
- 10.5334/jors.188 is OK
- 10.1109/TPWRS.2018.2829021 is OK
- 10.1109/TIE.2012.2194969 is OK
- 10.1109/TIE.2012.2196889 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1781

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1781, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1313083515286716418) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1782
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02435](https://doi.org/10.21105/joss.02435)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@katyhuff, @gonsie - many thanks for your reviews here and to @dhhagan for editing this submission ✨ 

@stheid - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02435/status.svg)](https://doi.org/10.21105/joss.02435)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02435">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02435/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02435/status.svg
   :target: https://doi.org/10.21105/joss.02435
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02435/status.svg)](https://doi.org/10.21105/joss.02435)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
