### ISSUE TITLE
[REVIEW]: CancerSim: A python3 package for stochastic cancer simulation in 2D

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2436]
**Submitting author:** @CFGrote (<a href="http://orcid.org/0000-0002-2579-5546">Carsten Fortmann-Grote</a>)
**Repository:** <a href="https://github.com/mpievolbio-scicomp/cancer_sim" target ="_blank">https://github.com/mpievolbio-scicomp/cancer_sim</a>
**Version:** 2.0.1
**Editor:** @pdebuyl
**Reviewer:** @jenzopr, @blakeaw
**Archive:** <a href="https://doi.org/10.5281/zenodo.4034071" target="_blank">10.5281/zenodo.4034071</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/03998bcb956325e7641c3ead54ad20da/status.svg)](https://joss.theoj.org/papers/03998bcb956325e7641c3ead54ad20da)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/03998bcb956325e7641c3ead54ad20da"><img src="https://joss.theoj.org/papers/03998bcb956325e7641c3ead54ad20da/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/03998bcb956325e7641c3ead54ad20da/status.svg)](https://joss.theoj.org/papers/03998bcb956325e7641c3ead54ad20da)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mpievolbio-scicomp/cancer_sim" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jenzopr & @blakeaw, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @pdebuyl know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mpievolbio-scicomp/cancer_sim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@CFGrote) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mpievolbio-scicomp/cancer_sim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@CFGrote) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jenzopr, @blakeaw it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41576-019-0114-6 is OK
- 10.1038/ng.3489 is OK
- 10.1038/nrc4029 is OK
- 10.1186/s12885-019-5597-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02436/joss.02436/10.21105.joss.02436.pdf)

**Comment by pdebuyl** [comment]
@blakeaw , @jenzopr ,  make sure to accept the invitation to the reviewers group and to have a look at the reviewer guidelines.

The review process will happen in this issue page, so questions to the author or to me can be added as comments here.

**Comment by blakeaw** [comment]
@pdebuyl, can you resend my reviewer group invitation? I just tried to accept but it said it had expired.

**Comment by pdebuyl** [comment]
@whedon re-invite @blakeaw as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@blakeaw please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by pdebuyl** [comment]
@blakeaw this should work again, let me know if there are issues.

**Comment by pdebuyl** [comment]
@jenzopr reminder for the review of "CancerSim: A python3 package for stochastic cancer simulation in 2D"

**Comment by blakeaw** [comment]
Hi @CFGrote, based on your software's commit history it looks like you are the only author that made direct contributions to the code itself. Would you mind briefly stating what contributions the other authors listed in the paper made to the project?

**Comment by blakeaw** [comment]
Possible step missing in the Installation instructions: Issue https://github.com/mpievolbio-scicomp/cancer_sim/issues/5

**Comment by jenzopr** [comment]
Problems with reproducing the Example usage from README and the docs: Issue https://github.com/mpievolbio-scicomp/cancer_sim/issues/6

**Comment by blakeaw** [comment]
Recommendation for additional documentation of simulation outputs: https://github.com/mpievolbio-scicomp/cancer_sim/issues/8

**Comment by blakeaw** [comment]
Low-level API documentation (autogenerated) appears to be missing and possibly didn't build properly: https://github.com/mpievolbio-scicomp/cancer_sim/issues/9

**Comment by CFGrote** [comment]
dear reviewers, thanks for all the comments so far. i'm currently on
vacation with very limited internet/email access. i'll pick up
immediately after my return on july 27th.

cfg

**Comment by jenzopr** [comment]
I reviewed the paper in https://github.com/mpievolbio-scicomp/cancer_sim/issues/11 and will grade the submission in category 3) Major revision.

**Comment by CFGrote** [comment]
> Hi @CFGrote, based on your software's commit history it looks like you are the only author that made direct contributions to the code itself. Would you mind briefly stating what contributions the other authors listed in the paper made to the project?

All the commits are from me because I moved the code (initially developed by my co-authors) from a plain directory into github and then took care of integrating new features.

## Contributions by author:
- **Luka Opasic**: Development of the algorithm, initial version of the code, writing of manuscript
- **Jacob Scott** : contributed to the concept of the software and supervised its
development 
- **Arne Traulsen**: supervised the development of the software.
- **Carsten Fortmann-Grote**: OO porting of the code, writing the manuscript, reference manual, documentation of code and examples, development of the test suite

**Comment by blakeaw** [comment]
I have reviewed the CancerSim paper in https://github.com/mpievolbio-scicomp/cancer_sim/issues/16 and I grade the overall submission as Category 3) Major Revision. 
Please note that this represents my initial evaluation and does not take into account recent efforts by @CFGrote to address some issues logged in the cancer_sim repository Issue tracker.

**Comment by pdebuyl** [comment]
@jenzopr @blakeaw thank you for the reviews.

@CFGrote the bulk of the review so far concerns the paper and the documentation, can you propose a reply to the reviewers?

Regarding the paper, I will only point out that we request for JOSS to not include configuration files or tutorial-type instructions for running the code in the paper. We ask that this type of documentation remains in the README or the documentation of the code.

**Comment by CFGrote** [comment]
thanks for the reviews. responses are in preparation.

**Comment by CFGrote** [comment]
ok, we addressed all issues, but let me check the pdf before marking as "resubmitted". btw, am i supposed/allowed to mark those checkboxes in the review reports or will the reviewers do that as they see fit?

**Comment by CFGrote** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf)

**Comment by pdebuyl** [comment]
@CFGrote the review checkboxes are for the reviewers of course.

**Comment by CFGrote** [comment]
sorry for not being specific:
i meant the checkboxes in the lists of review comments in  https://github.com/mpievolbio-scicomp/cancer_sim/issues/16 and  https://github.com/mpievolbio-scicomp/cancer_sim/issues/11 .

**Comment by CFGrote** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf)

**Comment by CFGrote** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf)

**Comment by CFGrote** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by CFGrote** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41576-019-0114-6 is OK
- 10.1038/ng.3489 is OK
- 10.1038/nrc4029 is OK
- 10.1186/s12885-019-5597-1 is OK
- 10.1038/nature14971 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by CFGrote** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf)

**Comment by CFGrote** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf)

**Comment by CFGrote** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf)

**Comment by pdebuyl** [comment]
@CFGrote even though these are issues in your repository, I think that it makes sense for the reviewers to check them. They will go through their remarks anyway while assessing the changes.

**Comment by pdebuyl** [comment]
@jenzopr @blakeaw , @CFGrote update his submissions, can you provide an update to the review?

**Comment by blakeaw** [comment]
@pdebuyl, yes, I will start looking over the submission updates.

**Comment by CFGrote** [comment]
not done yet
Aug 13, 2020 22:12:42 Pierre de Buyl <notifications@github.com>:

**Comment by pdebuyl** [comment]
@CFGrote sorry, I thought it was. You can notify us when the update is ready.

**Comment by CFGrote** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf)

**Comment by CFGrote** [comment]
I have just submitted our responses to the reviews: https://github.com/mpievolbio-scicomp/cancer_sim/issues/11#issuecomment-683706999 and https://github.com/mpievolbio-scicomp/cancer_sim/issues/16#issuecomment-683707010 All relevant changes are pushed to the master branch in https://github.com/mpievolbio-scicomp/cancer_sim. 

Thanks again to @blakeaw  and @jenzopr for the careful reading and detailed comments.

**Comment by jenzopr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf)

**Comment by pdebuyl** [comment]
Thank you @jenzopr for your review!

**Comment by pdebuyl** [comment]
@blakeaw the reply to your review is at https://github.com/mpievolbio-scicomp/cancer_sim/issues/16

**Comment by pdebuyl** [comment]
I am not subscribed to the issues at the repo and did not see @blakeaw 's positive evaluation of the changes at https://github.com/mpievolbio-scicomp/cancer_sim/issues/16 . @CFGrote I will proceed to the coming editorial steps in the coming days.

**Comment by blakeaw** [comment]
Sorry about that @pdebuyl. I forgot to come back and comment here after I finished reviewing the changes.  
I've checked off all the boxes in my Reviewer Checklist except the Functionality:Functionality one. For that, I'm planning to execute a few more test simulations with different parameter sets to make sure the code operates smoothly outside of the provided template/examples. I'll update within the next day or two. 
Also, it looks like @jenzopr still had an issue with installation and unit tests of the updated code: recorded in https://github.com/mpievolbio-scicomp/cancer_sim/issues/6.

**Comment by pdebuyl** [comment]
@blakeaw thanks for the correction. I am not used yet to parts of the review occurring at the software's repository. I'll make sure to check the checklist here and the issues there!

**Comment by blakeaw** [comment]
Hi @pdebuyl, I've completed my Review Checklist.

**Comment by pdebuyl** [comment]
Thank you @blakeaw ! I see that "Functionality" is still unchecked, does this checkbox need more work?

**Comment by pdebuyl** [comment]
@CFGrote there still is a testing issue open at your software's repository. I could run the tests just file (python 3.7 linux amd64 using pip), so I guess that the issue can be resolved by updating completely the software on the user's machine.

**Comment by jenzopr** [comment]
My checklist is complete now.

**Comment by pdebuyl** [comment]
Thank you @jenzopr for the review!

**Comment by blakeaw** [comment]
Hi @pdebuyl, Functionality doesn't require any additional work. You can consider it checked.
(The checkbox is showing up as checked on my end. Maybe refreshing the page will update?)

**Comment by pdebuyl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02436/joss.02436/10.21105.joss.02436.pdf) :page_facing_up: :point_left:

**Comment by pdebuyl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02436/joss.02436/10.21105.joss.02436.pdf) :page_facing_up: :point_left:

**Comment by pdebuyl** [comment]
@CFGrote can you archive a release of the code on zenodo? When it is done, I would need the corresponding doi and the version of the release to include in the paper.

**Comment by CFGrote** [comment]
I drafted the zenodo deposit, the reserved DOI is 10.5281/zenodo.4034071. I'm waiting my co-authors to give their "Ok" before publishing, will let you know. 
BTW I bumped the version of cancer_sim to 2.0.1.

**Comment by pdebuyl** [comment]
@whedon set 10.5281/zenodo.4034071 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4034071" target="_blank">10.5281/zenodo.4034071</a> is the archive.

**Comment by pdebuyl** [comment]
@whedon set 2.0.1 as version

**Comment by whedon** [comment]
OK. 2.0.1 is the version.

**Comment by pdebuyl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02436/joss.02436/10.21105.joss.02436.pdf) :page_facing_up: :point_left:

**Comment by pdebuyl** [comment]
@CFGrote you can consider the latest pdf as a proof. Let me know when I can validate the publication. At that point, an editor in chief of JOSS will take over the publication.

**Comment by jenzopr** [comment]
Well done, @CFGrote ! The review was not "cheap" and you did a lot of work to enhance the manuscript and software! Congratulations 🎉

**Comment by CFGrote** [comment]
> I drafted the zenodo deposit, the reserved DOI is 10.5281/zenodo.4034071. I'm waiting my co-authors to give their "Ok" before publishing, will let you know.
> BTW I bumped the version of cancer_sim to 2.0.1.

v2.0.1 is now published on zenodo: https://dx.doi.org/10.5281/zenodo.4034071

**Comment by pdebuyl** [comment]
@CFGrote should I take this as confirmation to proceed?

**Comment by CFGrote** [comment]
> @CFGrote should I take this as confirmation to proceed?

please wait, i'm checking the binder link, last item on my to do list for the proofs.

**Comment by CFGrote** [comment]
@wdedon commands

**Comment by CFGrote** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02436/joss.02436/10.21105.joss.02436.pdf) :page_facing_up: :point_left:

**Comment by CFGrote** [comment]
@pdebuyl , all good, please proceed.

**Comment by CFGrote** [comment]
@pdebuyl, @jenzopr, @blakeaw , thank you very much for your comments, corrections and guidance through the process. It was a very good experience!

**Comment by pdebuyl** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41576-019-0114-6 is OK
- 10.1038/ng.3489 is OK
- 10.1038/nrc4029 is OK
- 10.1186/s12885-019-5597-1 is OK
- 10.1038/nature14971 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1740

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1740, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by CFGrote** [comment]
@blakeaw , there's still one checkbox unchecked here (Review Checklist for blakeaw -> Functionality -> Functionality): https://github.com/openjournals/joss-reviews/issues/2436#issue-650881744 . Could you check, please?

**Comment by blakeaw** [comment]
@CFGrote Ok, it should be checked. Let me know if it is registering as checked now. 
(I unchecked that particular box and then re-checked it, as it was already registering as being checked on my end.)

**Comment by CFGrote** [comment]
> @CFGrote Ok, it should be checked. Let me know if it is registering as checked now.
> (I unchecked that particular box and then re-checked it, as it was already registering as being checked on my end.)

@blakeaw, looks good now, thanks!

**Comment by kyleniemeyer** [comment]
Hi @CFGrote, I'm the EIC on duty this week, and doing some final checks before publishing.

In the paper, I noticed a few issues:
- In your title, I think "python3" should be changed to "Python 3"
- You do not have an explicit Statement of Need, one of our [required elements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), that illustrates the research purpose of the software (you can probably just reorganize your existing text slightly)
- please put commas after "i.e" or "e.g."
- in the third paragraph, I think you can remove the "(see e.g. Ref", and then the final outer ")", and just have the reference directly. With the nested parentheses it looks a little awkward right now.

**Comment by pdebuyl** [comment]
@kyleniemeyer the paper was submitted before we required the "statement of need", which is why I didn't check for it (or whedon indeed).

Should the software archive be updated if only the paper is modified or can the author keep the current version 2.0.1 and the corresponding zenodo archive?

**Comment by kyleniemeyer** [comment]
@pdebuyl no worries! 

If only the software is modified, the archive does not need to be updated, since we (JOSS) archive the software.

**Comment by CFGrote** [comment]
> Hi @CFGrote, I'm the EIC on duty this week, and doing some final checks before publishing.
> 
> In the paper, I noticed a few issues:
> 
>     * In your title, I think "python3" should be changed to "Python 3"
> 
>     * You do not have an explicit Statement of Need, one of our [required elements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), that illustrates the research purpose of the software (you can probably just reorganize your existing text slightly)
> 
>     * please put commas after "i.e" or "e.g."
> 
>     * in the third paragraph, I think you can remove the "(see e.g. Ref", and then the final outer ")", and just have the reference directly. With the nested parentheses it looks a little awkward right now.

done, thanks for the comments.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02436/joss.02436/10.21105.joss.02436.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02436/joss.02436/10.21105.joss.02436.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Looks good to me!

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41576-019-0114-6 is OK
- 10.1038/ng.3489 is OK
- 10.1038/nrc4029 is OK
- 10.1186/s12885-019-5597-1 is OK
- 10.1038/nature14971 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1747

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1747, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1308907574977232896) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1748
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02436](https://doi.org/10.21105/joss.02436)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
I see the paper at https://joss.theoj.org/papers/10.21105/joss.02436, but the DOI does not seem to be resolving. I'll hold off closing this until it does.

**Comment by kyleniemeyer** [comment]
But, in the meantime, congrats @CFGrote on your article's publication in JOSS!

Many thank to @jenzopr and @blakeaw for reviewing this, and @pdebuyl for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02436/status.svg)](https://doi.org/10.21105/joss.02436)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02436">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02436/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02436/status.svg
   :target: https://doi.org/10.21105/joss.02436
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02436/status.svg)](https://doi.org/10.21105/joss.02436)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
