### ISSUE TITLE
[PRE REVIEW]: oolong: An R package for validating automated content analysis tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2437]
**Submitting author:** @chainsawriot (<a href="http://orcid.org/0000-0002-6232-7530">Chung-hong Chan</a>)
**Repository:** <a href="https://github.com/chainsawriot/oolong" target ="_blank">https://github.com/chainsawriot/oolong</a>
**Version:** 0.3.8
**Editor:** @kakiac
**Reviewers:** @pdwaggoner, @mbod
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @chainsawriot. **Currently, there isn't an JOSS editor assigned** to your paper.

@chainsawriot if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18637/jss.v040.i13 is OK
- 10.21105/joss.00774 is OK
- 10.1080/10584609.2020.1723752 is OK
- 10.1080/19312458.2018.1458084 is OK
- 10.1093/pan/mps028 is OK
- 10.1140/epjds/s13688-016-0085-1 is OK
- 10.18637/jss.v091.i02 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.43 s (111.8 files/s, 14323.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         7            318              0           1363
R                               26            176            224           1163
HTML                             1             12              3            606
Rmd                              9            395            642            604
XML                              1              0              2            441
TeX                              1             20              0            121
make                             1              6              0             25
YAML                             2              2              1             23
-------------------------------------------------------------------------------
SUM:                            48            929            872           4346
-------------------------------------------------------------------------------


Statistical information for the repository '2437' was gathered on 2020/07/04.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02437/joss.02437/10.21105.joss.02437.pdf)

**Comment by danielskatz** [comment]
👋 @kakiac - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @kakiac as editor

**Comment by whedon** [comment]
@kakiac has been invited to edit this submission.

**Comment by chainsawriot** [comment]
suggestions for potential reviewers: pdwaggoner mbod

**Comment by kakiac** [comment]
Thanks @danielskatz, happy to edit this submission :)

**Comment by kakiac** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kakiac

**Comment by kakiac** [comment]
👋  @chainsawriot thanks for your submission to JOSS.

Your submission fulfils our submission criteria (https://joss.readthedocs.io/en/latest/submitting.html), so I will be contacting your suggested reviewers shortly. 

In the meantime, can you please include a "Statement of need" section in your paper?

Many thanks and I will be in touch!

**Comment by kakiac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02437/joss.02437/10.21105.joss.02437.pdf)

**Comment by kakiac** [comment]
👋  @pdwaggoner, @mbod would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by chainsawriot** [comment]
@whedon generate pdf

**Comment by chainsawriot** [comment]
@kakiac A statement of need is added to the paper.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02437/joss.02437/10.21105.joss.02437.pdf)

**Comment by kakiac** [comment]
@chainsawriot Many thanks! 🌟

**Comment by kakiac** [comment]
I have just sent a notification to the reviewers by email, as well, we should have some news in the next couple of days :)

**Comment by mbod** [comment]
@kakiac I am happy to review this submission - just replied to your email

**Comment by pdwaggoner** [comment]
Hi @kakiac - thanks for reaching out. Happy to review this submission!

**Comment by akbaritabar** [comment]
Dear @kakiac , thanks a lot for giving me the chance. I am really sorry. I read the paper and checked the review guidelines, but I don't feel confident enough to evaluate the technical aspects of this package. The paper is well written, but I cannot be a good judge to say anything about the functionality as it is not my area of expertise.

It is a pity, as it could have been my first JOSS review :( and I am looking forward to help.

**Comment by kakiac** [comment]
Thanks all! @akbaritabar no problem at all, I am sure there will be another opportunity :) @mbod, @pdwaggoner many thanks for volunteering, I will be adding you as reviewers now and move the submission to the review stage, which will generate your reviewer's checklists!

**Comment by kakiac** [comment]
@whedon assign @pdwaggoner as reviewer

@whedon add @mbod as reviewer

**Comment by whedon** [comment]
OK, @pdwaggoner is now a reviewer

**Comment by kakiac** [comment]
@whedon add @mbod as reviewer

**Comment by whedon** [comment]
OK, @mbod is now a reviewer

**Comment by kakiac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02437/joss.02437/10.21105.joss.02437.pdf)

**Comment by kakiac** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2461.
