### ISSUE TITLE
[PRE REVIEW]: sonipy: A Perceptually Uniform Sonification Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2438]
**Submitting author:** @lockepatton (<a href="http://orcid.org/0000-0002-7640-236X">Locke Patton</a>)
**Repository:** <a href="https://github.com/lockepatton/sonipy" target ="_blank">https://github.com/lockepatton/sonipy</a>
**Version:** v1.0
**Editor:** @harpolea
**Reviewers:** @faroit, @benjaminrose
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lockepatton. **Currently, there isn't an JOSS editor assigned** to your paper.

@lockepatton if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (83.0 files/s, 23978.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          10            836            960           1489
Markdown                         3             97              0            178
Jupyter Notebook                 1              0            678             52
TeX                              1              3              0             39
-------------------------------------------------------------------------------
SUM:                            15            936           1638           1758
-------------------------------------------------------------------------------


Statistical information for the repository '2438' was gathered on 2020/07/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Locke                           10          2305            985           62.25
Locke Patton                     2          1980             15           37.75

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Locke                      1306           56.7          2.0                9.34
Locke Patton               1979           99.9          0.0               17.43
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-540-49127-9_4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02438/joss.02438/10.21105.joss.02438.pdf)

**Comment by danielskatz** [comment]
👋 @harpolea - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @harpolea  as editor

**Comment by whedon** [comment]
@harpolea has been invited to edit this submission.

**Comment by harpolea** [comment]
@danielskatz I'd be happy to edit this submission!

**Comment by harpolea** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @harpolea

**Comment by harpolea** [comment]
Hi @lockepatton, thanks for your submission! 

Do you have any suggestions for potential reviewers? If so, then please mention them here in this thread (without tagging them with an @). In addition, this [list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by lockepatton** [comment]
Hi @harpolea ! Thanks for volunteering to be the editor. Looking through the list, there are three people that stood out. On the audio / signal processing side, there's **expectopatronum** and **faroit**. On the astronomy side, there's **benjaminrose** who works with supernova. I'd lean towards an audio/signal processing reviewer as the astronomy side is purely motivation, but any/all would work! My background is in astronomy, so any audio folks would have a fresh perspective. Cheers.

**Comment by harpolea** [comment]
Great, thanks!

:wave: @expectopatronum & @faroit, would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by faroit** [comment]
@harpolea with pleasure.

**Comment by harpolea** [comment]
Thanks @faroit!

**Comment by harpolea** [comment]
@whedon assign @faroit as reviewer

**Comment by whedon** [comment]
OK, @faroit is now a reviewer

**Comment by lockepatton** [comment]
Thanks @faroit for reviewing!

**Comment by expectopatronum** [comment]
This package sounds very interesting! I'll go on vacation soon though and currently don't have the time to do any reviewing. I hope you'll find someone else!

**Comment by harpolea** [comment]
@expectopatronum no worries, thanks for letting me know!

**Comment by harpolea** [comment]
:wave: @benjaminrose! Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by benjaminrose** [comment]
I can review this submission. As a heads up, I’m moving at the end of the month, so I’ll be unreachable for several weeks starting August 24th. Though I expect to finish my review by then.

**Comment by harpolea** [comment]
Great, thanks @benjaminrose! 

Sure, if at any point you feel that you will no longer be able to complete the review before that time, then please let me know.

**Comment by harpolea** [comment]
@whedon add @benjaminrose as reviewer

**Comment by whedon** [comment]
OK, @benjaminrose is now a reviewer

**Comment by harpolea** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2446.
