### ISSUE TITLE
[REVIEW]: htmldate: A Python package to extract publication dates from web pages

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2439]
**Submitting author:** @adbar (<a href="http://orcid.org/0000-0002-8079-8694">Adrien Barbaresi</a>)
**Repository:** <a href="https://github.com/adbar/htmldate" target ="_blank">https://github.com/adbar/htmldate</a>
**Version:** v0.7.0
**Editor:** @danielskatz
**Reviewer:** @geoffbacon, @proycon
**Archive:** <a href="https://doi.org/10.5281/zenodo.3966235" target="_blank">10.5281/zenodo.3966235</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/71cfb002bbc47d453586f1bf2ab30b85/status.svg)](https://joss.theoj.org/papers/71cfb002bbc47d453586f1bf2ab30b85)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/71cfb002bbc47d453586f1bf2ab30b85"><img src="https://joss.theoj.org/papers/71cfb002bbc47d453586f1bf2ab30b85/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/71cfb002bbc47d453586f1bf2ab30b85/status.svg)](https://joss.theoj.org/papers/71cfb002bbc47d453586f1bf2ab30b85)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/adbar/htmldate" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@geoffbacon & @proycon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/adbar/htmldate">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@adbar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/adbar/htmldate">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@adbar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @geoffbacon, @proycon it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1515/zgl-2017-0017 is OK
- 10.18653/v1/w16-2602 is OK
- 10.1162/coli.2007.33.1.147 is OK
- 10.1007/s10579-009-9081-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02439/joss.02439/10.21105.joss.02439.pdf)

**Comment by danielskatz** [comment]
👋 @geoffbacon & @proycon - thanks for agreeing to review this submission. Please be sure to read the comments above, and let me know if you have any questions.  Basically, your job is to check the article proof and repository and check items off your checklist above.

If you see small problems that need to be discussed, feel free to discuss them here.  But if you can, create a new issue in the <a href="https://github.com/adbar/htmldate" target="_blank">target repository</a> and link to this review thread in that issue to create a corresponding breadcrumb trail here.

I look forward to seeing how this review goes!

**Comment by geoffbacon** [comment]
Thanks @danielskatz - I will have this done by Friday 10th July (PDT).

**Comment by proycon** [comment]
I completed my review, ticking the boxes in the original post (@danielskatz I assume there's some protection layer there confirming that I was the one ticking them right?). 

**Overal summary:** I think it's a well written paper and useful software package, suitable for publication in JOSS.

**Some extra comments:**

> Contribution and authorship: Has the submitting author (@adbar) made major contributions to the software? Does the full list           of paper authors seem appropriate and complete?

The 2nd contributor (@DerKozmonaut) I assume to be the person Yannick Kozmus that is explicitly acknowledged in the acknowledgements section, this seems appropriate and complete to me.

I evaluated some of the software's functionality by running it on a few arbitrary URLs: 

   * A recent blogpost of mine - https://proycon.anaproy.nl/post/break_free_do_not_be_a_prisoner_of_your_software/ - correctly dated
   * An article on a popular dutch news site - https://www.nu.nl/coronavirus/6063124/nederland-stelt-opnieuw-inreisverbod-in-voor-servie-en-montenegro.html - correctly dated
   * A reddit post - https://www.reddit.com/r/postmarketOS/comments/hc38e3/does_postmarketos_support_wifi_calling/ - not dated at all
   * A forum post (phpBB3) - https://forum.unilang.org/viewtopic.php?f=1&t=58214 - correctly dated
   * A wikipedia article - https://en.wikipedia.org/wiki/Constitution_of_Russia - incorrectly dated? Returns a date but it is not the original publication date (according to wikipedia history) nor the latest edit date. (I also tried with the explicit original_date option)

For the developers, I'd say there's possible room for future improvement in adding some specific heuristics for some big platforms like reddit and wikipedia. (should be easy pickings)

**Comment by danielskatz** [comment]
@proycon - thanks!

> I completed my review, ticking the boxes in the original post (@danielskatz I assume there's some protection layer there confirming that I was the one ticking them right?).

no, but the fact that you have written here about the paper being suitable implies that *you* have also checked off all the items, or at least, that you agree with their status as being checked off.

**Comment by geoffbacon** [comment]
Hi @danielskatz - I'll be able to get to this on Monday, thanks for understanding.

**Comment by geoffbacon** [comment]
Finished my review. Like @proycon,  I find htmldate to be a useful utility library with a clear motivation. I particularly appreciated the evaluation suite that tests the library against numerous other existing solutions.

**Comment by danielskatz** [comment]
Thanks @geoffbacon

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02439/joss.02439/10.21105.joss.02439.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1515/zgl-2017-0017 is OK
- 10.18653/v1/w16-2602 is OK
- 10.1162/coli.2007.33.1.147 is OK
- 10.1007/s10579-009-9081-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@adbar- to finish this process, I've suggested some changes to the paper in https://github.com/adbar/htmldate/pull/15 
Please also fix the references, for example the booktitle in Hamborg et al. has some incorrect cases, as does at least on python (that should be Python).  Please check all the references carefully, and use {}s in the bibtex to protect cases.

Then use `@whedon generate pdf` to regenerate the PDF to check.

Once you are happy with this, please
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by adbar** [comment]
@proycon @geoffbacon thank you for your feedback!

@danielskatz thank you for the suggestions and the guidelines, I'll proceed as instructed above.

**Comment by danielskatz** [comment]
👋 @adbar - I haven't seen an update in 15 days, and there's certainly nothing major left to do.  How are you proceeding on these final steps?

**Comment by adbar** [comment]
@danielskatz I'm actually working on it right now ;) I had a few pull requests to process and improvements to make, I'll be contacting you shortly with the final version.

**Comment by adbar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02439/joss.02439/10.21105.joss.02439.pdf)

**Comment by adbar** [comment]
- tagged release: v0.7.0
- Zenodo DOI: 10.5281/zenodo.3966235

Are we good to go?

**Comment by adbar** [comment]
@proycon The issue with Wikipedia is now solved. Reddit doesn't currently display dates that are extractable in a straightforward way, I'll keep this case in mind.

**Comment by danielskatz** [comment]
@adbar - can you merge https://github.com/adbar/htmldate/pull/20 as well?

**Comment by adbar** [comment]
@danielskatz yes, thank you for the revision!

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02439/joss.02439/10.21105.joss.02439.pdf)

**Comment by danielskatz** [comment]
@whedon set v0.7.0 as version

**Comment by whedon** [comment]
OK. v0.7.0 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3966235 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3966235" target="_blank">10.5281/zenodo.3966235</a> is the archive.

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1515/zgl-2017-0017 is OK
- 10.18653/v1/w16-2602 is OK
- 10.1162/coli.2007.33.1.147 is OK
- 10.1007/s10579-009-9081-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1515/zgl-2017-0017 is OK
- 10.18653/v1/w16-2602 is OK
- 10.1162/coli.2007.33.1.147 is OK
- 10.1007/s10579-009-9081-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1603

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1603, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1288827489113038850) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1604
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02439](https://doi.org/10.21105/joss.02439)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @geoffbacon & @proycon for reviewing!

Congratulations to @adbar!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02439/status.svg)](https://doi.org/10.21105/joss.02439)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02439">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02439/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02439/status.svg
   :target: https://doi.org/10.21105/joss.02439
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02439/status.svg)](https://doi.org/10.21105/joss.02439)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
