### ISSUE TITLE
[PRE REVIEW]: hebnoRms: Affect Norms for Hebrew

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2441]
**Submitting author:** @almogsi (<a href="http://orcid.org/0000-0003-2629-2913">Almog Simchon</a>)
**Repository:** <a href="https://github.com/almogsi/hebnoRms" target ="_blank">https://github.com/almogsi/hebnoRms</a>
**Version:** 0.2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @almogsi. **Currently, there isn't an JOSS editor assigned** to your paper.

@almogsi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (252.7 files/s, 27865.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             6            257             77            685
CSS                              3             99             48            428
JavaScript                       3             64             32            256
TeX                              2             11              0            128
Markdown                         2             42              0             71
R                                2              6             58             28
SVG                              1              0              1             11
YAML                             2              3              0             11
-------------------------------------------------------------------------------
SUM:                            21            482            216           1618
-------------------------------------------------------------------------------


Statistical information for the repository '2441' was gathered on 2020/07/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Almog Simchon                    1           352              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Almog Simchon               352          100.0          0.0                9.09
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.21105/joss.00774 may be missing for title: quanteda: An R package for the quantitative analysis of textual data
- https://doi.org/10.21105/joss.00037 may be missing for title: tidytext: Text mining and analysis using tidy data principles in R
- https://doi.org/10.1162/tacl_a_00051 may be missing for title: Enriching Word Vectors with Subword Information

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02441/joss.02441/10.21105.joss.02441.pdf)

**Comment by danielskatz** [comment]
👋 @almogsi - This is not a sufficient contribution to be reviewed and published by JOSS.  If your goal is to have this software cited, you might consider:

- Follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.
 - Enquire whether your software might be considered by communities such as [rOpenSci](https://ropensci.org) and [pyOpenSci](https://pyopensci.org).

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
