### ISSUE TITLE
[PRE REVIEW]: Datos: datasets translations to promote diversity, equity, and inclusion

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2442]
**Submitting author:** @pachamaltese (<a href="http://orcid.org/0000-0003-1017-7574">Mauricio Vargas</a>)
**Repository:** <a href="https://github.com/cienciadedatos/datos" target ="_blank">https://github.com/cienciadedatos/datos</a>
**Version:** 0.3.0.9000
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pachamaltese. **Currently, there isn't an JOSS editor assigned** to your paper.

@pachamaltese if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (668.7 files/s, 65282.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            43           2101            595           5407
R                               50             24             53           2108
YAML                            34              5              1           2031
CSS                              3             99             48            428
JavaScript                       3             64             32            256
Markdown                         4             59              0            153
Rmd                              1             24             35             36
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                           139           2376            765          10430
-------------------------------------------------------------------------------


Statistical information for the repository '2442' was gathered on 2020/07/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Edgar Ruiz                       1             5              7            1.00
Mauricio Vargas                  4           400            400           66.78
Riva Quiroga                     2           170             16           15.53
raynamharris                     1           200              0           16.69

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Riva Quiroga                163           95.9          0.0                9.82
raynamharris                189           94.5          0.0                8.47
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2442 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
👋 @pachamaltese - where is the paper associated with this software?  We expect in the software repository.  See https://joss.readthedocs.io/en/latest/submitting.html

**Comment by pachamaltese** [comment]
@danielskatz Hi. Sorry, it was on a separate repo. I moved all together here: https://github.com/cienciadedatos/datos/blob/master/inst/paper.md

**Comment by pachamaltese** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02442/joss.02442/10.21105.joss.02442.pdf)

**Comment by danielskatz** [comment]
@pachamaltese - the paper does not appear to be complete - the Spanish parts in particular towards then have phrases that end with ...s

Additionally, it's not clear to me that this is research software. I have no doubt that it is useful software, but it seems more useful in education than in research. Can you explain what kinds of researchers you think would use this software (and would be likely to cite it)?

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by pachamaltese** [comment]
@danielskatz Hi. With respect to the spanish parts, we wanted to summarise the article in spanish once this pre-submission is considered feasible. We have seen a lot of people using the datos package who are citing it in educational materials, as you mentioned. Here I'm looking for an opinion: Would you consider JOSE a better place?

**Comment by danielskatz** [comment]
If you want to discuss a submission, it would be better to use an pre-submission issue - https://github.com/openjournals/joss/issues/new?title=Pre-submission%20enquiry (as discussed in https://joss.theoj.org/about#submitting) rather than submitting to JOSS as a complete paper/submission.

I'm going to mark this as withdrawn for now, and suggest the discussion should be done in a pre-submission issue - please open one there.

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
