### ISSUE TITLE
[REVIEW]: Chips-n-Salsa: A Java Library of Customizable, Hybridizable, Iterative, Parallel, Stochastic, and Self-Adaptive Local Search Algorithms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2448]
**Submitting author:** @cicirello (<a href="http://orcid.org/0000-0003-1072-8559">Vincent A Cicirello</a>)
**Repository:** <a href="https://github.com/cicirello/Chips-n-Salsa" target ="_blank">https://github.com/cicirello/Chips-n-Salsa</a>
**Version:** v1.3.0
**Editor:** @galessiorob
**Reviewers:** @nnadeau, @mbdemoraes
**Archive:** <a href="https://doi.org/10.5281/zenodo.3974614" target="_blank">10.5281/zenodo.3974614</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ff6046b4dd41979ff6eb38a8517b4b1b/status.svg)](https://joss.theoj.org/papers/ff6046b4dd41979ff6eb38a8517b4b1b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ff6046b4dd41979ff6eb38a8517b4b1b"><img src="https://joss.theoj.org/papers/ff6046b4dd41979ff6eb38a8517b4b1b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ff6046b4dd41979ff6eb38a8517b4b1b/status.svg)](https://joss.theoj.org/papers/ff6046b4dd41979ff6eb38a8517b4b1b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cicirello/Chips-n-Salsa" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mbdemoraes & @nnadeau, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @galessiorob know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cicirello/Chips-n-Salsa">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cicirello) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cicirello/Chips-n-Salsa">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cicirello) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mbdemoraes, @nnadeau it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-030-24202-2_7 is OK
- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/eai.3-12-2015.2262346 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1145/1143997.1144177 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1126/science.220.4598.671 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1109/icec.1995.489178 is OK
- 10.1109/proc.1987.13916 is OK
- 10.1109/dac.1988.14775 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK

MISSING DOIs

- https://doi.org/10.1016/0004-3702(96)00007-0 may be missing for title: Artificial Intelligence: A Modern Approach

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02448/joss.02448/10.21105.joss.02448.pdf)

**Comment by cicirello** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by cicirello** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-030-24202-2_7 is OK
- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/eai.3-12-2015.2262346 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1145/1143997.1144177 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1126/science.220.4598.671 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1109/icec.1995.489178 is OK
- 10.1109/proc.1987.13916 is OK
- 10.1109/dac.1988.14775 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK

MISSING DOIs

- https://doi.org/10.1016/0004-3702(96)00007-0 may be missing for title: Artificial Intelligence: A Modern Approach

INVALID DOIs

- None
```

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02448/joss.02448/10.21105.joss.02448.pdf)

**Comment by cicirello** [comment]
@whedon check references
@whedon generate pdf

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-030-24202-2_7 is OK
- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/eai.3-12-2015.2262346 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1145/1143997.1144177 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1126/science.220.4598.671 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1109/icec.1995.489178 is OK
- 10.1109/proc.1987.13916 is OK
- 10.1109/dac.1988.14775 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK

MISSING DOIs

- https://doi.org/10.1016/0004-3702(96)00007-0 may be missing for title: Artificial Intelligence: A Modern Approach

INVALID DOIs

- None
```

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02448/joss.02448/10.21105.joss.02448.pdf)

**Comment by galessiorob** [comment]
@whedon add  @mbdemoraes as reviewer

**Comment by whedon** [comment]
OK,  @mbdemoraes is now a reviewer

**Comment by galessiorob** [comment]
👋 @mbdemoraes and @nnadeau this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#REVIEW_NUMER` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@galessiorob) if you have any questions/concerns.

**Comment by cicirello** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1201/9781351236423 is OK
- 10.1007/978-3-319-91086-4_1 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1145/3377930.3390185 is OK
- 10.1145/1516512.1516520 is OK
- 10.1145/3371425.3371641 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK
- 10.1145/3321707.3321715 is OK
- 10.1016/j.cie.2017.06.019 is OK
- 10.1007/s10732-018-9366-0 is OK

MISSING DOIs

- https://doi.org/10.1002/9781119136378.ch1 may be missing for title: Evolutionary Algorithms

INVALID DOIs

- None
```

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2448 with the following error: 

 pandoc-citeproc: reference mbdemoraes not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.333 }

Looks like we failed to compile the PDF

**Comment by cicirello** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1201/9781351236423 is OK
- 10.1007/978-3-319-91086-4_1 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1145/3377930.3390185 is OK
- 10.1145/1516512.1516520 is OK
- 10.1145/3371425.3371641 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK
- 10.1145/3321707.3321715 is OK
- 10.1016/j.cie.2017.06.019 is OK
- 10.1007/s10732-018-9366-0 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1002/9781119136378 is INVALID because of 'https://doi.org/' prefix
```

**Comment by cicirello** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1201/9781351236423 is OK
- 10.1007/978-3-319-91086-4_1 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1145/3377930.3390185 is OK
- 10.1002/9781119136378 is OK
- 10.1145/1516512.1516520 is OK
- 10.1145/3371425.3371641 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK
- 10.1145/3321707.3321715 is OK
- 10.1016/j.cie.2017.06.019 is OK
- 10.1007/s10732-018-9366-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2448 with the following error: 

 pandoc-citeproc: reference mbdemoraes not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.333 }

Looks like we failed to compile the PDF

**Comment by cicirello** [comment]
@galessiorob I just made a few edits to the paper.md and paper.tex.  When generating the pdf with whedon, I got a very strange error that appears to be related to one of the reviewer ids (see the part of the error that says: "pandoc-citeproc: reference mbdemoraes not found"), and not at all due to the paper.  See the error in the result from whedon above.  I just tried the preview service (https://whedon.theoj.org/) to confirm that it isn't due to paper.md or paper.tex.  The paper compiles fine with the preview service.

Any idea how to correct this?

**Comment by danielskatz** [comment]
@whedon generate pdf

it's often worth just trying again in case the problem is transient

**Comment by whedon** [comment]
PDF failed to compile for issue #2448 with the following error: 

 pandoc-citeproc: reference mbdemoraes not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.333 }

Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @openjournals/dev  - can you take a look at this?

**Comment by galessiorob** [comment]
thank you @danielskatz !

**Comment by cicirello** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1201/9781351236423 is OK
- 10.1007/978-3-319-91086-4_1 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1145/3377930.3390185 is OK
- 10.1002/9781119136378 is OK
- 10.1145/1516512.1516520 is OK
- 10.1145/3371425.3371641 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK
- 10.1145/3321707.3321715 is OK
- 10.1016/j.cie.2017.06.019 is OK
- 10.1007/s10732-018-9366-0 is OK
- 10.1145/3319619.3326865 is OK
- 10.1016/j.ejor.2019.01.018 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2448 with the following error: 

 pandoc-citeproc: reference mbdemoraes not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.333 }

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2448 with the following error: 

 pandoc-citeproc: reference mbdemoraes not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.333 }

Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02448/joss.02448/10.21105.joss.02448.pdf)

**Comment by arfon** [comment]
Looks like there was some weirdness going on with whitespace at the top of the issue (I'm still trying to figure out exactly what went wrong here but it seems to be fixed now)

**Comment by nnadeau** [comment]
@cicirello almost there! Great job so far! I believe these should be the last issues:

- https://github.com/cicirello/Chips-n-Salsa/issues/25
- https://github.com/cicirello/Chips-n-Salsa/pull/22
- https://github.com/cicirello/Chips-n-Salsa/issues/24
- https://github.com/cicirello/Chips-n-Salsa/issues/23

**Comment by galessiorob** [comment]
@whedon add @mbdemoraes  as reviewer

**Comment by whedon** [comment]
OK, @mbdemoraes  is now a reviewer

**Comment by galessiorob** [comment]
@mbdemoraes just re-added you, let me know if you have issues. Thanks!

**Comment by mbdemoraes** [comment]
@galessiorob thank you! I've accepted the invitation.

**Comment by galessiorob** [comment]
@cicirello thanks for working out the install and run instructions with @mbdemoraes!

@mbdemoraes thank you so much for your review, the only [item to check-off](https://github.com/openjournals/joss-reviews/issues/2448#issue-652769899) is `Performance`, which based on the article you can check because there are no performance claims.

@nnadeau thank you too for your review, the only missing items from[ your checklist](https://github.com/openjournals/joss-reviews/issues/2448#issue-652769899) are `Installation instructions` and `Community guidelines`, mind checking those off if you're satisfied or giving notes on what is missing if so?

Almost there! 🎉

**Comment by nnadeau** [comment]
done

**Comment by mbdemoraes** [comment]
Hello! I've finished my review. Everything checked now.

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02448/joss.02448/10.21105.joss.02448.pdf)

**Comment by galessiorob** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @galessiorob, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by galessiorob** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1201/9781351236423 is OK
- 10.1007/978-3-319-91086-4_1 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1145/3377930.3390185 is OK
- 10.1002/9781119136378 is OK
- 10.1145/1516512.1516520 is OK
- 10.1145/3371425.3371641 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK
- 10.1145/3321707.3321715 is OK
- 10.1016/j.cie.2017.06.019 is OK
- 10.1007/s10732-018-9366-0 is OK
- 10.1145/3319619.3326865 is OK
- 10.1016/j.ejor.2019.01.018 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by galessiorob** [comment]
@cicirello we're almost ready to publish! Could you please deposit your software in Zenodo and post the DOI here?

After that, we can set the final version and accept the paper 🎉 

@mbdemoraes and @nnadeau thank you both so much for your time and expertise ✨

**Comment by cicirello** [comment]
@galessiorob the Zenodo doi for all versions is https://doi.org/10.5281/zenodo.3959773 . I think that is probably the one you want. It looks like zenodo also generates a doi for each release, so if you want the one that goes to a specific release then it is https://doi.org/10.5281/zenodo.3974614 .

**Comment by cicirello** [comment]
@nnadeau and @mbdemoraes thank you both for your time, expertise, and very helpful feedback in your reviews.

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02448/joss.02448/10.21105.joss.02448.pdf)

**Comment by galessiorob** [comment]
@whedon set v1.3.0 as version

**Comment by whedon** [comment]
OK. v1.3.0 is the version.

**Comment by galessiorob** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by galessiorob** [comment]
@whedon set 10.5281/zenodo.3974614 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3974614" target="_blank">10.5281/zenodo.3974614</a> is the archive.

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02448/joss.02448/10.21105.joss.02448.pdf)

**Comment by galessiorob** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1201/9781351236423 is OK
- 10.1007/978-3-319-91086-4_1 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1145/3377930.3390185 is OK
- 10.1002/9781119136378 is OK
- 10.1145/1516512.1516520 is OK
- 10.1145/3371425.3371641 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK
- 10.1145/3321707.3321715 is OK
- 10.1016/j.cie.2017.06.019 is OK
- 10.1007/s10732-018-9366-0 is OK
- 10.1145/3319619.3326865 is OK
- 10.1016/j.ejor.2019.01.018 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1638

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1638, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02448/joss.02448/10.21105.joss.02448.pdf)

**Comment by galessiorob** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00950 is OK
- 10.1109/TEVC.2015.2477284 is OK
- 10.4108/icst.bict.2014.257872 is OK
- 10.1007/s10732-005-6997-8 is OK
- 10.1201/9781351236423 is OK
- 10.1007/978-3-319-91086-4_1 is OK
- 10.1016/b978-0-08-049944-4.50022-7 is OK
- 10.1609/aimag.v17i3.1232 is OK
- 10.1145/3377930.3390185 is OK
- 10.1002/9781119136378 is OK
- 10.1145/1516512.1516520 is OK
- 10.1145/3371425.3371641 is OK
- 10.1016/0020-0190(93)90029-9 is OK
- 10.1016/S0004-3702(00)00081-3 is OK
- 10.1145/3321707.3321715 is OK
- 10.1016/j.cie.2017.06.019 is OK
- 10.1007/s10732-018-9366-0 is OK
- 10.1145/3319619.3326865 is OK
- 10.1016/j.ejor.2019.01.018 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1639

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1639, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by galessiorob** [comment]
@cicirello could you please give this last version a final proof read? An editor in chief will take it from here and get it published now ✨

**Comment by cicirello** [comment]
@galessiorob I proofread the latest version, and it looks fine. Thank you for your time and expertise overseeing the review.

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1295220312028717057) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1642
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02448](https://doi.org/10.21105/joss.02448)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @cicirello on your article's publication in JOSS!

Many thanks to @nnadeau and @mbdemoraes for reviewing this, and @galessiorob for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02448/status.svg)](https://doi.org/10.21105/joss.02448)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02448">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02448/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02448/status.svg
   :target: https://doi.org/10.21105/joss.02448
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02448/status.svg)](https://doi.org/10.21105/joss.02448)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
