### ISSUE TITLE
[PRE REVIEW]: pyhector: A Python interface for the simple climate model Hector

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#245]
**Submitting author:** @swillner (<a href="http://orcid.org/0000-0001-6798-6247">Sven N. Willner</a>)
**Repository:** <a href="https://github.com/openclimatedata/pyhector/" target ="_blank">https://github.com/openclimatedata/pyhector/</a>
**Version:** v0.6.0
**Editor:** @arfon
**Reviewer:** @sgrieve

**Author instructions**

Thanks for submitting your paper to JOSS @swillner. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@swillner if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by swillner** [comment]
coauthors: @rgieseke, @cahartin

**Comment by swillner** [comment]
@sgrieve, @betatim, @mankoff: we would be glad if you could review our submission

**Comment by swillner** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by sgrieve** [comment]
I'd be happy to review. I should be able to work on it early next week at the latest.

**Comment by rgieseke** [comment]
Thanks @sgrieve!

We've just updated Pyhector to v0.6.0. Is there a `whedon` command to change/regenerate the metadata?

**Comment by sgrieve** [comment]
I think that might be a question for @arfon ...

**Comment by arfon** [comment]
> I think that might be a question for @arfon ...

👍 it's a manual process right now (I've just done it)

**Comment by arfon** [comment]
@whedon assign @sgrieve as reviewer

**Comment by arfon** [comment]
@whedon assign @sgrieve as reviewer

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @sgrieve as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sgrieve

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/248. Feel free to close this issue now!

**Comment by arfon** [comment]
@sgrieve - please head over to #248 to actually carry out the review
