### ISSUE TITLE
[REVIEW]: arcos (R) and arcospy (Python): twin software packages to access the DEA ARCOS database from 2006 to 2014

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2450]
**Submitting author:** @jeffcsauer (<a href="http://orcid.org/0000-0002-8581-6919">Jeffery Sauer</a>)
**Repository:** <a href="https://github.com/jeffcsauer/arcos_arcospy_information" target ="_blank">https://github.com/jeffcsauer/arcos_arcospy_information</a>
**Version:** <v1.1.1>
**Editor:** @bmcfee
**Reviewer:** @jaeyk, @edonnachie
**Archive:** <a href="https://doi.org/10.5281/zenodo.4029306" target="_blank">10.5281/zenodo.4029306</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6f07ed5bbfdee442cb34926c4dc52eb5/status.svg)](https://joss.theoj.org/papers/6f07ed5bbfdee442cb34926c4dc52eb5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6f07ed5bbfdee442cb34926c4dc52eb5"><img src="https://joss.theoj.org/papers/6f07ed5bbfdee442cb34926c4dc52eb5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6f07ed5bbfdee442cb34926c4dc52eb5/status.svg)](https://joss.theoj.org/papers/6f07ed5bbfdee442cb34926c4dc52eb5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jeffcsauer/arcos_arcospy_information" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jaeyk & @edonnachie, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @bmcfee know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jeffcsauer/arcos_arcospy_information">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jeffcsauer) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jeffcsauer/arcos_arcospy_information">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jeffcsauer) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
Comment: No automated tests, but steps to test functionality are clear
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jaeyk, @edonnachie it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- doi:10.1016/j.drugpo.2019.03.024 is OK
- doi:10.1016/j.jpainsymman.2004.01.003 is OK
- doi:10.1001/jama.283.13.1710 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02450/joss.02450/10.21105.joss.02450.pdf)

**Comment by jaeyk** [comment]
@jeffcsauer I will review the package starting today. Could you reorganize `paper.md` in the package git repository so that it could be more consistent with the standard format used in JOSS? An example is [here](https://github.com/ComtekAdvancedStructures/cmstatr/blob/master/paper.md). Specifically, I would like to see a separate section on the statement of need.

**Comment by jaeyk** [comment]
@jeffcsauer Also, it would be great, if you could add a short but detailed documentation on the functions provided by the package. An example is [here](https://keyatm.github.io/keyATM/articles/pkgdown_files/Options.html). The R and Python examples provided in the usage section are not user-friendly. You already have the vignettes. Thus, I believe that this is easily doable.

**Comment by jeffcsauer** [comment]
@jaeyk thank you for the quick input! Absolutely - I will carry out the suggestions over the next few days and tag you when they are completed.

**Comment by jaeyk** [comment]
@jeffcsauer Thanks. I plan to review software paper -> documentation -> functionality. The package is already in good shape. My focus will be improving user-interface.

**Comment by jeffcsauer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.drugpo.2019.03.024 is OK
- 10.1016/j.jpainsymman.2004.01.003 is OK
- 10.1001/jama.283.13.1710 is OK
- 10.4137/sart.s2345 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jeffcsauer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02450/joss.02450/10.21105.joss.02450.pdf)

**Comment by jeffcsauer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02450/joss.02450/10.21105.joss.02450.pdf)

**Comment by jeffcsauer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02450/joss.02450/10.21105.joss.02450.pdf)

**Comment by jeffcsauer** [comment]
@jaeyk wanted to ping you as I have incorporated your suggestions into the paper. A summary of changes include:

- Addition of a 'Statement of Need' section. This contextualizes the dataset as a major addition to analyzing prescription opioid data due to the dearth of existing datasets on the topic. The section also states the core goals of the software (i.e. data access, relevant metrics, and language flexibility).
- Expansion of 'Data Availability' section to include some examples of 'Basic Usage'.
- Slight re-organization of paper structure to improve readability (i.e. 'API Structure' section now comes before 'Data Availability and Basic Usage' section).
- Addition of link to shared repository under 'Availability' section.
- A few grammar and writing changes to improve readability.

Regarding your concern about users finding the functions, I have added a table of the available functions on the [shared arcos/arcospy repository](https://github.com/jeffcsauer/arcos_arcospy_information) as well as linking to the table/repository in the paper (appears in a 'Data Availability and Basic Usage' and 'Availability' sections). Let me know if this is helpful or if you were thinking of a different solution!

**Comment by jaeyk** [comment]
@jeffcsauer Thanks for the quick update. They look great. I have a couple more minor suggestions:

- Provide references at the bottom of the `paper.md`. (You already have in-text citations and have a section heading for citations. So, I believe that you plan to do this.)
- Provide more structure to contributions. Take a look at [this example](https://github.com/keyATM/keyATM/issues). For instance, when create issues, are issues about bugs/features? When users report bugs/features, what kind of the format they should follow? Are they required to report their environment (e.g., session information)? Should they provide a minimal reproducible example? Having this sort of clear guideline helps users to create issues also helps you to include issues in a development roadmap.

**Comment by jeffcsauer** [comment]
@jaeyk thanks for the additional input! I will am working on bullet point 2 and will get back to you in a few days when done. 

Quick question regarding bullet point 1. Should I add an additional 'Citations' section in the `paper.md` file that is commented out? The above article preview generated by Whedon appears to be generating a correct and completed 'Citations' section. Apologies for my confusion on this point.

**Comment by jaeyk** [comment]
@jeffcsauer Then, disregard my comment on adding "Citations" section. Sorry for making you confused about this. (Honestly, I didn't know that that section is auto-generated.)

**Comment by jeffcsauer** [comment]
@jaeyk No need to apologize! Thanks for the quick response.

Following up on your suggestion to "Provide more structure to the `contributing.md`...", I have carried out the following changes:

- Updated `contributing.md` to describe the purpose of the `arcos_arcospy_information` repository, namely centralizing and standardizing issues/feature requests. I also added guidelines to help identify whether an issue/feature request applies to the core ARCOS data or the `arcos` and `arcospy` software. Added detail to several sub-sections of `contributing.md` in general.
- Adopted Github templates on the shared `arcos_arcospy_information` repository. As now explained in `contributing.md`, issues/feature requests posted to the separate `arcos` and `arcospy` repositories will now be cross-posted and standardized on the shared `arcos_arcospy_information` repository. 
- Notifications are set up to notify the maintainers of the R/Python software when an issue is raised on the opposite repository. I have taken on the responsibility to cross-post the issues to the shared `arcos_arcospy_information` repository.

**Comment by jaeyk** [comment]
@jeffcsauer The `contributing.md` looks great. Thanks for your update. I have a paper deadline this week. I will do performance test starting next week.

**Comment by jaeyk** [comment]
@jeffcsauer Could you rename [the Articles section in the tab in the reference page](https://wpinvestigative.github.io/arcos/articles/per-capita-pharmacies.html) for something more intuitive (e.g. User's Guide)? As of now, it's not very clear what it means.

**Comment by jaeyk** [comment]
@jeffcsauer  It would be great, if you include some unit tests. For instance, 

```r
states <- combined_buyer_annual(key="WaPo")


```

**Comment by jaeyk** [comment]
Functionality checks for the R version 

- [ ] combined_buyer_annual()
- [ ] total_pharmacies_county()
- [ ] drug_list()
- [ ] drug_county_biz()
- [ ] total_pharmacies_state()
- [ ] county_population()
- [ ] buyer_address()
- [ ] pharmacy_raw()

**Comment by jaeyk** [comment]
@jeffcsauer Could you provide the vignette for the Python version package? Currently, the reference in the Python package is linked to the vignette section of the R version package.

**Comment by jeffcsauer** [comment]
@jaeyk thanks for the additional comments! A few follow-up points/questions:
- I have opened [an issue](https://github.com/wpinvestigative/arcos/issues/7) on the R/arcos repository to field possible renames for the button. I agree, this button should likely be renamed to something more intuitive. 
- I have re-arranged (and added) [additional notebooks to the R/arcospy repository](https://github.com/jeffcsauer/arcospy/tree/master/docs) (more to come!). When you say 'vignette for the Python version', what kind of vignette were you envisioning (e.g. read the docs, notebooks, or something else)? The primary reason for the many links back to the R/arcos docs is that R/arcos was created first with the python version coming later. Early discussions between the R and python authors wanted to avoid duplication of documentation given the primacy and quality of the R/arcos materials. I would be happy to include a prominent statement explaining this to users.

**Comment by jaeyk** [comment]
@jeffcsauer 

re1: Great!

re2: I appreciate the detailed R documentation but it would be great if there's R & Python side-by-side vignette as that would help users to see how parallel the two packages are. For instance, users might have questions about whether the Python version has identical function names, arguments, etc. So, provide a minimum vignette that clarifies this potential confusion. 

See the vignette page of the [{prophet}](https://facebook.github.io/prophet/docs/saturating_forecasts.html#forecasting-growth) package which is also available both in R and Python. The usage of the two packages are almost identical but you can also notice that a slight difference. For instance, `prophet()` in R is equivalent to `Prophet()` in Python.

**Comment by jeffcsauer** [comment]
@jaeyk 

Ah thank you so much for the clarification and example! I was misunderstanding the original point. Will do - I will work on a brief vignette that does side-by-side comparison and will make it prominently displayed on the shared arcos/arcospy repository, as well as linking on the specific software. I will ping you when it is done!

**Comment by jeffcsauer** [comment]
@jaeyk 

I have [created a vignette](https://github.com/jeffcsauer/arcos_arcospy_information/tree/master/docs) that does provides side-by-side comparison for installing the package, a quick start example, and a more involved example use case. I also highlight key considerations for users of the data (as highlighted in the paper) and provide some additional useful links. The vignette resides on the shared arcos/arcospy repository and is prominently placed in the first text block. Thanks again for this suggestion - it is indeed an easier starting point than going back-and-forth! Let me know what else I can do!

**Comment by jaeyk** [comment]
@jeffcsauer The vignette looks great. I'm done with the functionality test. Thanks for the quick incorporation of the previous feedback!

**Comment by jeffcsauer** [comment]
@jaeyk, no problem! If it's alright, might I ask what the next steps look like? Happy to incorporate feedback from @edonnachie.

**Comment by jaeyk** [comment]
@jeffcsauer Done with my part of the review and informed the editor regarding the current status.

**Comment by jeffcsauer** [comment]
Hi @bmcfee @edonnachie, would it be possible to get an update on the review status? Apologies as know summer is wrapping up and a new semester is kicking off.

**Comment by jeffcsauer** [comment]
@edonnachie thank you for the quick response! Totally understand, it has indeed been a pressing and unique situation these past few months. I look forward to integrating your comments and feedback.

**Comment by edonnachie** [comment]
Before I get to the package itself, here are a few initial comments on the paper:

__Summary:__

- It would be helpful to explain what the Opoid Overdose Crisis is, perhaps with link to the [CDC](https://www.cdc.gov/opioids/strategy.html). It's not clear to me whther the overdoses are accidental (due to overuse of this drug therapy) or suicide-related (due to the controls being too lax).

- You write that data was released until 2012. You should mention here that the data for 2013-2014 is now also available. 

- You write that patient confidentiality is one reason that access to ARCOS is usually restricted. If this were true, then providing wide access to this data would be legally and ethically problematic (at least from a european perspective). However, I would tend to the view that the risk of revealing information about patients is negligible. Either way, this needs some explaining.

- Both from a technical and a data protection perspective, it would seem important to explain what is behind the API: How and where are the data stored? Who controls and maintains this database? Are reqiests logged, and if so, are personally identifiable data kept (e.g. IP address)?

__Statement of Need:__

- You should explain why the ARCOS database is useful. How does this compare with other sources of prescribing data (pharmacy data centres, medicaid etc)? I suspect that the main advantage lies in the analysis of how market dynamics facilitated the epidemic.

- Repeated word: "In raw format, the the ARCOS database "

__Data Availability and Basic Usage:__

- Should "from 2006 to 2012" not be "from 2006 to 2014"?

__Conclusion:__

- The statement "while still maintaining individual medical privacy " is confusing, see above.

- What you don't mention is that the data provide a different perspective to the medical claims data that would usually be used for such analyses. If I understand correctly, you're not looking at who received an opoid, but at how these substances travelled across the supply chain (and in what quantity). I think this is an important and interesting distinction to be made.

**Comment by jeffcsauer** [comment]
Thanks for these detailed initial comments! I will incorporate them over the next couple of days and tag you when done.

**Comment by jeffcsauer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02450/joss.02450/10.21105.joss.02450.pdf)

**Comment by jeffcsauer** [comment]
Hi @edonnachie,

Thank you so much for the detailed comments! They were very helpful for improving the paper. I have updated the `paper.md` with several changes and provide responses to each of your comments below. 

---

*Author responses to reviewer comments:*

> Comment #1: It would be helpful to explain what the Opioid Overdose Crisis is, perhaps with link to the CDC. It's not clear to me whether the overdoses are accidental (due to overuse of this drug therapy) or suicide-related (due to the controls being too lax).

This is an excellent point. I have done a few things to address your comment. Firstly, I rewrote the opening of the introduction to contextualize the U.S. Opioid Overdose Epidemic. Secondly, I added the phrase "all-cause" when describing the increases in opioid-involved mortality as the Opioid Overdose Epidemic is concerned with both unintentional, intentional, and homicidal drug-involved deaths. The system-level *cause* (e.g. 'overuse of this drug therapy' or 'controls being too lax') remains an active area of research.  

> Comment #2: You write that data was released until 2012. You should mention here that the data for 2013-2014 is now also available.

Clarified that additional data for 2013-2014 is now also available. 

> Comment #3: You write that patient confidentiality is one reason that access to ARCOS is usually restricted. If this were true, then providing wide access to this data would be legally and ethically problematic (at least from a European perspective). However, I would tend to the view that the risk of revealing information about patients is negligible. Either way, this needs some explaining.

After consultation with co-authors I have reworked this sentence. Firstly, I replaced the word 'restricted' with 'only for approved requests (e.g. research or litigation)'. I have also added a citation for the Drug Enforcement Administration (DEA) Privacy Impact Assessment, which offers extremely detailed information on potential privacy concerns for the ARCOS data. I have also added the word 'anonymized' in the following sentence to clarify that no patient-level identifying information (e.g. name) exists in the present ARCOS data. The present ARCOS data represents *shipments* of controlled opioid medications from manufacturers to distributors, so you are correct in that  revealing information about patients is negligible. The original wording of the sentence was unclear and we hope that the new phrasing is helpful.

> Comment #4: Both from a technical and a data protection perspective, it would seem important to explain what is behind the API: How and where are the data stored? Who controls and maintains this database? Are requests logged, and if so, are personally identifiable data kept (e.g. IP address)?

I have added additional information on the API in the **API Structure** section including API specification and guidelines on use. I have reached out to members of the Data Reporting Team at *The Washington Post* for exact details on your comments regarding if and what personal identifiable information is stored.

> Comment #5: You should explain why the ARCOS database is useful. How does this compare with other sources of prescribing data (pharmacy data centres, medicaid etc)? I suspect that the main advantage lies in the analysis of how market dynamics facilitated the epidemic.

This is a great point. We feel that the first part of the comment ("How does this compare with other sources of prescribing data (pharmacy data centres, medicaid etc)?") is addressed by the sentences in the **Statement of Need** section. However, we have added additional sentences relating to the second point of the comment ("I suspect that the main advantage lies in the analysis of how market dynamics facilitated the epidemic.") as this is indeed a very important aspect of the Opioid Overdose Epidemic that has ample room left for exploration and quantification. 

> Comment #6: Repeated word: "In raw format, the the ARCOS database "

Deleted repeated word.

> Comment #7: Should "from 2006 to 2012" not be "from 2006 to 2014"?

Changed 2012 to 2014.

> Comment #8: The statement "while still maintaining individual medical privacy " is confusing, see above.

This is a great point. I have removed the quoted phrase as it is confusing and unnecessary.

> Comment #9: What you don't mention is that the data provide a different perspective to the medical claims data that would usually be used for such analyses. If I understand correctly, you're not looking at who received an opioid, but at how these substances traveled across the supply chain (and in what quantity). I think this is an important and interesting distinction to be made.

See author response to Comment #5 above. We agree and have added additional sentences relating to potential analyses of opioid prescription market dynamics.

**Comment by edonnachie** [comment]
Hi @jeffcsauer ,

Thanks for the detailed response, the updated paper looks good and better explains some of the background. I'm almost through with the review and hope to complete by the end of the week.

@bmcfee : I can't edit the reviewer checklist above; my invitation has expired. Do you need to issue a new invitation or am I missing something?

**Comment by danielskatz** [comment]
@whedon re-invite @edonnachie as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@edonnachie please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by edonnachie** [comment]
Thank you @danielskatz. I am now able to edit.

**Comment by edonnachie** [comment]
@bmcfee @jeffcsauer I've now completed my review. The paper, package documentation and functionality are quite impressive. I submitted one minor pull request to bring the documentation up to date  (2014 instead of 2012). Otherwise, I don't find any further issues.

**Comment by jeffcsauer** [comment]
Sounds good, I have notified the `arcos` maintainers of your PR and it will be addressed shortly.

Thank you very much for the detailed feedback @edonnachie and @jaeyk! Your review has greatly improved the packages and will surely enhance the experience of future users. We greatly appreciate your time and effort during the JOSS reduced service mode. 

If there is anything else we can do, please let us know! 😃

**Comment by bmcfee** [comment]
Thanks @edonnachie and @jaeyk for your reviews!  It looks like this is all good to go now.

**Comment by bmcfee** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02450/joss.02450/10.21105.joss.02450.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02450/joss.02450/10.21105.joss.02450.pdf) :page_facing_up: :point_left:

**Comment by bmcfee** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.drugpo.2019.03.024 is OK
- 10.15585/mmwr.mm6626a4 is OK
- 10.2105/AJPH.2007.131714 is OK
- 10.15585/mmwr.mm6928a1 is OK
- 10.1016/j.drugpo.2019.03.024 is OK
- 10.1016/j.jpainsymman.2004.01.003 is OK
- 10.1001/jama.283.13.1710 is OK
- 10.4137/sart.s2345 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by bmcfee** [comment]
@jeffcsauer the paper looks to be in great shape! :tada: 

The last step for you is to make an updated release of the package(s) to reflect any changes made during the review process, and deposit the new version(s) at a DOI-minting repository like Figshare or Zenodo.  When that's done, we can link up the DOIs to the paper and move on to publication.

**Comment by jeffcsauer** [comment]
@bmcfee great, sounds good! I have created a Zenodo repository with both `arcos` and `arcospy` [here](https://zenodo.org/record/4029306).

**Comment by bmcfee** [comment]
@whedon set 10.5281/zenodo.4029306 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4029306" target="_blank">10.5281/zenodo.4029306</a> is the archive.

**Comment by bmcfee** [comment]
@whedon set <v1.1.1> as version

**Comment by whedon** [comment]
OK. <v1.1.1> is the version.

**Comment by bmcfee** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.drugpo.2019.03.024 is OK
- 10.15585/mmwr.mm6626a4 is OK
- 10.2105/AJPH.2007.131714 is OK
- 10.15585/mmwr.mm6928a1 is OK
- 10.1016/j.drugpo.2019.03.024 is OK
- 10.1016/j.jpainsymman.2004.01.003 is OK
- 10.1001/jama.283.13.1710 is OK
- 10.4137/sart.s2345 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1728

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1728, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by jeffcsauer** [comment]
@bmcfee in my final review of the paper I pushed a few small grammar edits, caught a few typos, and added a missing period. Otherwise it is ready on my end! 👍

**Comment by bmcfee** [comment]
Thanks for the final pass @jeffcsauer !  At this point it's ready to bump up to the EICs.

**Comment by bmcfee** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02450/joss.02450/10.21105.joss.02450.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02450/joss.02450/10.21105.joss.02450.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1306289665251704834) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1732
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02450](https://doi.org/10.21105/joss.02450)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @jeffcsauer on your article's publication in JOSS!

Many thanks to @jaeyk and @edonnachie for reviewing this, and @bmcfee for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02450/status.svg)](https://doi.org/10.21105/joss.02450)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02450">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02450/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02450/status.svg
   :target: https://doi.org/10.21105/joss.02450
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02450/status.svg)](https://doi.org/10.21105/joss.02450)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
