### ISSUE TITLE
[PRE REVIEW]: MiTfAT: A Pyhton-based fMRI Analysis Tool, Made in Tübingen

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2452]
**Submitting author:** @vahid-sb (<a href="http://orcid.org/0000-0001-6544-7960">Vahid S. Bokharaie</a>)
**Repository:** <a href="https://github.com/vahid-sb/MiTfAT" target ="_blank">https://github.com/vahid-sb/MiTfAT</a>
**Version:** v0.1.6
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vahid-sb. **Currently, there isn't an JOSS editor assigned** to your paper.

@vahid-sb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2452 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (143.9 files/s, 29944.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          24            763           1500           3067
reStructuredText                 1             29              7             43
YAML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            26            792           1507           3111
-------------------------------------------------------------------------------


Statistical information for the repository '2452' was gathered on 2020/07/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vahid Bokharaie                 49         68932          63070          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vahid Bokharaie            5862            8.5          4.1               16.31
```

**Comment by kyleniemeyer** [comment]
Hi @vahid-sb, it looks like your repository is missing the actual JOSS paper. Please review our [submission criteria](https://joss.readthedocs.io/en/latest/submitting.html), and let me know here when you have completed the paper. In the meantime, I will pause this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@vahid-sb, also Python is spelled wrong in the title and I suggest you rewrite the title and remove "Made in Tübingen"

**Comment by oliviaguest** [comment]
Happy to edit this when it's in better shape. 

@Kevin-Mattheus-Moerman not that it matters... but I think the "Made in Tübingen" is the MiT in the initialism/acronym.

**Comment by jni** [comment]
👋 Hi everyone! Brand new editor here, but I'd also be happy to be editor for this paper once it's ready to move forward.

**Comment by danielskatz** [comment]
@vahid-sb - given 25 days with no response from you, I am going to mark this as rejected.

Feel free to resubmit after fixing the problem - If you do so, please mention this issue when you resubmit

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by vahid-sb** [comment]
@danielskatz @jni @kyleniemeyer Just wanted to apologise to you all for not responding to you all in a timely manner. I thought I get an email notification when I receive a message in github, but apparently not. Hence, I completely missed this conversation. So, my sincere apologies for missing out on your messages. 
I will add the pdf files following the journal guidelines to the repo and will submit it for review again.
