### ISSUE TITLE
[PRE REVIEW]: CPgeneProfiler: A lightweight R package to profile the Carbapenamase genes from genome assemblies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2453]
**Submitting author:** @ramadatta (<a href="http://orcid.org/0000-0002-9254-2557">Prakki Sai Rama Sridatta</a>)
**Repository:** <a href="https://github.com/ramadatta/CPgeneProfiler" target ="_blank">https://github.com/ramadatta/CPgeneProfiler</a>
**Version:** v2.1.0
**Editor:** @will-rowe
**Reviewers:** @fmaguire, @boasvdp
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ramadatta. **Currently, there isn't an JOSS editor assigned** to your paper.

@ramadatta if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2453 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2453 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1093/bioinformatics/btx364 may be missing for title: UpSetR: an R package for the visualization of intersecting sets and their properties
- https://doi.org/10.1186/1471-2105-10-421 may be missing for title: BLAST+: architecture and applications
- https://doi.org/10.1186/s13073-014-0090-6 may be missing for title: SRST2: rapid genomic surveillance for public health and hospital microbiology labs
- https://doi.org/10.1093/jac/dks261 may be missing for title: Identification of acquired antimicrobial resistance genes
- https://doi.org/10.1093/nar/gkw1009 may be missing for title: MEGARes: an antimicrobial resistance database for high throughput sequencing
- https://doi.org/10.1093/nar/gkw1004 may be missing for title: CARD 2017: expansion and model-centric curation of the comprehensive antibiotic resistance database
- https://doi.org/10.1128/aac.01310-13 may be missing for title: ARG-ANNOT, a new bioinformatic tool to discover antibiotic resistance genes in bacterial genomes
- https://doi.org/10.1099/mgen.0.000131 may be missing for title: ARIBA: rapid antimicrobial resistance genotyping directly from sequencing reads
- https://doi.org/10.3389/fpubh.2019.00242 may be missing for title: Using genomics to track global antimicrobial resistance
- https://doi.org/10.1093/ofid/ofx176 may be missing for title: Prevalence of carbapenem-resistant Gram-negative infections in the United States predominated by Acinetobacter baumannii and Pseudomonas aeruginosa
- https://doi.org/10.1016/j.jinf.2018.11.003 may be missing for title: Whole genome sequencing detects inter-facility transmission of carbapenem-resistant Klebsiella pneumoniae
- https://doi.org/10.1128/aac.02282-18 may be missing for title: Cocarriage of distinct blaKPC-2 and blaOXA-48 plasmids in a single sequence type 11 carbapenem-resistant Klebsiella pneumoniae isolate
- https://doi.org/10.1093/cid/ciz824 may be missing for title: Epidemiology and diagnostics of carbapenem resistance in gram-negative bacteria

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @ramadatta, thanks for your submission. It looks like there is a problem with your `paper.md` file. As a start, can you try removing these fields from the header?
```
citation_author: Prakki et. al.
year: 2020
output: rticles::joss_article
csl: apa.csl
journal: JOSS
```

(just leave the bibliography field in that section of lines, and `date` is ok too)

As you edit this, you can use this page to test that the paper builds properly: https://whedon.theoj.org

**Comment by kyleniemeyer** [comment]
Hi @will-rowe, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @will-rowe as editor

**Comment by whedon** [comment]
@will-rowe has been invited to edit this submission.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02453/joss.02453/10.21105.joss.02453.pdf)

**Comment by ramadatta** [comment]
> Hi @ramadatta, thanks for your submission. It looks like there is a problem with your `paper.md` file. As a start, can you try removing these fields from the header?
> 
> ```
> citation_author: Prakki et. al.
> year: 2020
> output: rticles::joss_article
> csl: apa.csl
> journal: JOSS
> ```
> 
> (just leave the bibliography field in that section of lines, and `date` is ok too)
> 
> As you edit this, you can use this page to test that the paper builds properly: https://whedon.theoj.org

Dear @kyleniemeyer, thank you very much! I have edited `paper.md` according to your advice. The modified `paper.md` builds properly with the Whedon paper preview service.

**Comment by will-rowe** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hi @flashton2003, @fmaguire, @alexwailan. Do you have time to review this for JOSS?

**Comment by fmaguire** [comment]
@will-rowe sure, I'd be more than happy to review this submission.

**Comment by will-rowe** [comment]
Great - thanks @fmaguire! Let me find one more reviewer and then we'll kick of the review thread.

**Comment by will-rowe** [comment]
Hi @boasvdp - would you be able to review this submission please?

**Comment by boasvdp** [comment]
@will-rowe Sure thing! Count me in

**Comment by will-rowe** [comment]
Thanks folks! We'll start the review process now. Let me know if you need anything.

**Comment by will-rowe** [comment]
@whedon assign @fmaguire as reviewer

**Comment by whedon** [comment]
OK, @fmaguire is now a reviewer

**Comment by will-rowe** [comment]
@whedon add @boasvdp as reviewer

**Comment by whedon** [comment]
OK, @boasvdp is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2473.
