### ISSUE TITLE
[PRE REVIEW]: PySocialForce: A Python Implementation of the Extended Social Force Model for Pedestrian Dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2454]
**Submitting author:** @yuxiang-gao (<a href="http://orcid.org/0000-0001-6183-2482">Yuxiang Gao</a>)
**Repository:** <a href="https://github.com/yuxiang-gao/PySocialForce" target ="_blank">https://github.com/yuxiang-gao/PySocialForce</a>
**Version:** v1.0.0
**Editor:** @pdebuyl
**Reviewers:** @ixjlyons, @xuqiancheng
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @yuxiang-gao. **Currently, there isn't an JOSS editor assigned** to your paper.

@yuxiang-gao if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1103/PhysRevE.51.4282 is OK
- 10.1098/rspb.2009.0405 is OK
- 10.1371/journal.pone.0010047 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02454/joss.02454/10.21105.joss.02454.pdf)

**Comment by kyleniemeyer** [comment]
Hi @pdebuyl, can you edit this submission for us?

**Comment by kyleniemeyer** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@moorepants @jackbrookes would you review the article "PySocialForce: A Python Implementation of the Extended Social Force Model for Pedestrian Dynamics" for the Journal of Open Source Software?

**Comment by moorepants** [comment]
Sorry I'm committed to review a JOSS article already.

**Comment by pdebuyl** [comment]
Thank you @moorepants for the quick reply!

**Comment by pdebuyl** [comment]
@ixjlyons would you review the article "PySocialForce: A Python Implementation of the Extended Social Force Model for Pedestrian Dynamics" for the Journal of Open Source Software?

**Comment by ixjlyons** [comment]
@pdebuyl sure, I'd be happy to review.

**Comment by pdebuyl** [comment]
Thank you @ixjlyons

**Comment by pdebuyl** [comment]
@whedon assign @ixjlyons as reviewer

**Comment by whedon** [comment]
OK, @ixjlyons is now a reviewer

**Comment by pdebuyl** [comment]
The review will occur in a second github issue page once we have a second reviewer

**Comment by pdebuyl** [comment]
@yuxiang-gao do you have suggestions for reviewers?

**Comment by pdebuyl** [comment]
@xuqiancheng would you review the article "PySocialForce: A Python Implementation of the Extended Social Force Model for Pedestrian Dynamics" for the Journal of Open Source Software?

**Comment by xuqiancheng** [comment]
@pdebuyl Yes, I would like to review the article.

**Comment by pdebuyl** [comment]
@whedon add @xuqiancheng as reviewer

**Comment by whedon** [comment]
OK, @xuqiancheng is now a reviewer

**Comment by pdebuyl** [comment]
Thank you @xuqiancheng.

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2494.
