### ISSUE TITLE
[PRE REVIEW]: bridge-sim: A Python library for concrete slab bridge simulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2455]
**Submitting author:** @barischrooneyj (<a href="http://orcid.org/0000-0002-8441-212X">Jeremy Barisch-Rooney</a>)
**Repository:** <a href="https://github.com/barischrooneyj/bridge-sim" target ="_blank">https://github.com/barischrooneyj/bridge-sim</a>
**Version:** v0.0.7
**Editor:** @diehlpk
**Reviewers:** @skreimeyer, @manparvesh
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @barischrooneyj. **Currently, there isn't an JOSS editor assigned** to your paper.

@barischrooneyj if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.52 s (282.9 files/s, 79161.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            37           1698              0          21452
Python                          90           2130           2419          13271
Markdown                         1             18              0            102
Bourne Shell                    14             15             20             91
Tcl/Tk                           2             32             14             58
TeX                              1              4              0             43
YAML                             2              5              3             21
INI                              1              6              0             13
-------------------------------------------------------------------------------
SUM:                           148           3908           2456          35051
-------------------------------------------------------------------------------


Statistical information for the repository '2455' was gathered on 2020/07/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jeremy Barisch-Roone           154         77102          61124           99.85
barischrooneyj                   1           213              0            0.15

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jeremy Barisch-Roone      17820           23.1          1.3               10.06
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/mcse.2011.66 may be missing for title: OpenSees: a framework for earthquake engineering simulation
- https://doi.org/10.1109/mcse.2007.55 may be missing for title: Matplotlib: A 2D graphics environment

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02455/joss.02455/10.21105.joss.02455.pdf)

**Comment by kyleniemeyer** [comment]
Hi @poulson, could you edit this submission? I realize the application is a bit outside your area.

**Comment by kyleniemeyer** [comment]
@whedon invite @poulson as editor

**Comment by whedon** [comment]
@poulson has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hi @barischrooneyj, thanks for your submission to JOSS. While we are getting started, could you add a Statement of Need to your article? This is now required for articles, as described in our [documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Thanks!

**Comment by poulson** [comment]
I'm weary about being the editor on this and would prefer that a civil engineer do so. I would be comfortable reviewing this if it was over the FEM itself, but I feel there are deeper constraints here due to the safety implications of bridge design and my blindness to which types of models are considered in bounds.

**Comment by kyleniemeyer** [comment]
@poulson understood—unfortunately, I don't think we have any civil engineers on the editorial board. But, I'll still look for someone else.

**Comment by kyleniemeyer** [comment]
Hi @diehlpk, would you be able to edit this submission?

**Comment by diehlpk** [comment]
@kyleniemeyer Sure, I can take it. 

@whedon assign @diehlpk as editor

**Comment by diehlpk** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by diehlpk** [comment]
Hey, @TheBeachLab @skreimeyer @dukenmarga @ebrahimraeyat @manparvesh @ipsumium would you be interested in reviewing this paper?

**Comment by diehlpk** [comment]
@barischrooneyj Can you please recommend some potential reviewers without the `@` in front of their GitHub handle?

**Comment by skreimeyer** [comment]
Patrick,

I will look over the code, but it may be this weekend before I get to it.

Regards,
Sam

**Comment by diehlpk** [comment]
@skreimeyer Thanks for letting me know. Take your time, we anticipate that you finish the review in the next six weeks.

**Comment by diehlpk** [comment]
@whedon assign @skreimeyer as reviewer

**Comment by whedon** [comment]
OK, @skreimeyer is now a reviewer

**Comment by barischrooneyj** [comment]
> @barischrooneyj Can you please recommend some potential reviewers without the `@` in front of their GitHub handle?

zhuminjie may be a good reviewer. The software I wrote makes heavy use of the OpenSees finite element program, and he does work related to OpenSees.

**Comment by barischrooneyj** [comment]
> Hi @barischrooneyj, thanks for your submission to JOSS. While we are getting started, could you add a Statement of Need to your article? This is now required for articles, as described in our [documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Thanks!

I have changed one heading to "Statement of need", the contents were already as such but with a different heading.

**Comment by barischrooneyj** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02455/joss.02455/10.21105.joss.02455.pdf)

**Comment by diehlpk** [comment]
@zhuminjie Would you be interested to review this paper?

**Comment by diehlpk** [comment]
Hey @javidibaghban @spapadopoulos would you be interested in reviewing this paper?

**Comment by diehlpk** [comment]
Hi @barischrooneyj, can you provide reviewer suggestions? We are still missing one reviewer to start the review

**Comment by diehlpk** [comment]
@whedon add @manparvesh as reviewer

**Comment by whedon** [comment]
OK, @manparvesh is now a reviewer

**Comment by diehlpk** [comment]
@manparvesh There will be a new issue with a check list you can follow.

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2496.

**Comment by diehlpk** [comment]
@whedon remove @skreimeyer as reviewer

**Comment by whedon** [comment]
OK, @skreimeyer is no longer a reviewer

**Comment by diehlpk** [comment]
@whedon add @andybond13 as reviewer

**Comment by whedon** [comment]
OK, @andybond13 is now a reviewer
