### ISSUE TITLE
[PRE REVIEW]: DrWatson: the perfect sidekick for your scientific inquiries

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2456]
**Submitting author:** @tamasgal (<a href="http://orcid.org/0000-0001-7821-8673">Tamás Gál</a>)
**Repository:** <a href="https://github.com/JuliaDynamics/DrWatson.jl" target ="_blank">https://github.com/JuliaDynamics/DrWatson.jl</a>
**Version:** v1.13.2
**Editor:** @dpsanders
**Reviewers:** @jpfairbanks, @kescobo
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tamasgal. **Currently, there isn't an JOSS editor assigned** to your paper.

@tamasgal if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (192.0 files/s, 23362.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           19            412            320           2091
Markdown                         9            223              0            913
Lisp                             1             26              0             93
TeX                              1              0              0             70
YAML                             3              5              1             59
TOML                             2              5              0             41
-------------------------------------------------------------------------------
SUM:                            35            671            321           3267
-------------------------------------------------------------------------------


Statistical information for the repository '2456' was gathered on 2020/07/09.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.6084/m9.figshare.3115156.v2 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.jsc.2003.04.002 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02456/joss.02456/10.21105.joss.02456.pdf)

**Comment by kyleniemeyer** [comment]
Hi @tamasgal, as we are getting started here, could you please add a Statement of Need section? This is now required for articles, as described in [our documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).

Also, it looks like there is a problem with a DOI ☝️

**Comment by kyleniemeyer** [comment]
Hi @melissawm and @dpsanders, as our resident Julia experts I'm wondering if either of you has the bandwidth to edit this submission? Thanks!

**Comment by dpsanders** [comment]
Yes, I would like to edit this.

**Comment by kyleniemeyer** [comment]
@whedon assign @dpsanders as editor

**Comment by whedon** [comment]
OK, the editor is @dpsanders

**Comment by tamasgal** [comment]
Thanks for both of you! We will add the statement of need section tomorrow and also fix the DOI.

**Comment by tamasgal** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02456/joss.02456/10.21105.joss.02456.pdf)

**Comment by tamasgal** [comment]
OK looks like whedon doesn't listen to me. ;) The DOI is fixed and the "Statement of need" section is now there.

**Comment by tamasgal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by tamasgal** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.jsc.2003.04.002 is OK
- 10.6084/m9.figshare.3115156.v2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dpsanders** [comment]
:wave @tamasgal Sorry for the delay. 

Could you please check for each piece of software that you cite whether there is a related published paper. For example, `sumatra` has an associated paper.

Software also often has a preferred means of citing the software listed in the repository.

Are there any other non-software references, i.e. published papers, that are relevant?

**Comment by tamasgal** [comment]
No worries, thanks for the feedback! Yes I’ll check again and go through the list of refs.

I think the list is complete but we will check that too.

**Comment by tamasgal** [comment]
Alright, improved a bit but for the remaining packages I could not find better citations or papers. Those are mostly R packages...

Thanks for the hint with the Sumatra paper, I totally overlooked that.

**Comment by tamasgal** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.jsc.2003.04.002 is OK
- doi:10.5063/F1GF0RF6 is OK
- 10.6084/m9.figshare.3115156.v2 is OK

MISSING DOIs

- https://doi.org/10.1201/9781315373461-3 may be missing for title: Sumatra: A Toolkit for Reproducible Research

INVALID DOIs

- None
```

**Comment by tamasgal** [comment]
The missing DOI is now added.

@whedon check references

**Comment by tamasgal** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.jsc.2003.04.002 is OK
- doi:10.1201/9781315373461-3 is OK
- doi:10.5063/F1GF0RF6 is OK
- 10.6084/m9.figshare.3115156.v2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by tamasgal** [comment]
This issue probably got a bit lost due to JuliaCon 😅

**Comment by dpsanders** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02456/joss.02456/10.21105.joss.02456.pdf)

**Comment by Datseris** [comment]
Hello,

I'd like to suggest a reviewer for our paper: James Fairbanks, PhD ( @jpfairbanks ) is familiar with the Julia language, is already familiar with various software for scientific assistanship, and is unaffiliated with DrWatson.

@dpsanders could you please consider him as a reviewer and possibly start the review process? I am meanwhile searching for a second reviewer as well.

best,
George

**Comment by Datseris** [comment]
Hi @dpsanders , I'd like to suggest a second reviewer, Kevin Bonham, PhD @kescobo

**Comment by kescobo** [comment]
:wave: I'm willing to review if appropriate. Haven't used the package before, but it could be relevant. Would be a good excuse to kick the tires.

**Comment by dpsanders** [comment]
👋 @tamasgal and @Datseris: Apologies for the delay and thanks for the help with reviewers.

Thanks to @jpfairbanks and @kescobo for volunteering!

**Comment by dpsanders** [comment]
@whedon add @jpfairbanks as reviewer

**Comment by whedon** [comment]
OK, @jpfairbanks is now a reviewer

**Comment by dpsanders** [comment]
@whedon add @kescobo as reviewer

**Comment by whedon** [comment]
OK, @kescobo is now a reviewer

**Comment by dpsanders** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2673.

**Comment by tamasgal** [comment]
Thanks for all of you so far! No worries David, I appreciate your comments and feedback!
