### ISSUE TITLE
[PRE REVIEW]: CoReCon: an open, community-powered collection of Reionization constraints

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2457]
**Submitting author:** @EGaraldi (<a href="http://orcid.org/0000-0002-6021-7020">Enrico Garaldi</a>)
**Repository:** <a href="https://github.com/EGaraldi/corecon" target ="_blank">https://github.com/EGaraldi/corecon</a>
**Version:** v0.3.1
**Editor:** @eloisabentivegna
**Reviewers:** @ngnedin, @afialkov, @Stefan-Heimersheim
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @EGaraldi. **Currently, there isn't an JOSS editor assigned** to your paper.

@EGaraldi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.33 s (507.4 files/s, 28468.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         137           1907            632           5126
reStructuredText                17            459            316            326
Markdown                         2             26              0            105
YAML                             2             37             90             59
TeX                              1              8              0             56
HTML                             3              2              0             40
DOS Batch                        1              8              1             26
make                             1              5              7             17
Bourne Shell                     1              2              0              2
-------------------------------------------------------------------------------
SUM:                           165           2454           1046           5757
-------------------------------------------------------------------------------


Statistical information for the repository '2457' was gathered on 2020/07/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Enrico Garaldi                  65         35404          28936           98.14
akshit                           1          1209             12            1.86

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Enrico Garaldi             6570           18.6          2.0                5.77
akshit                     1095           90.6          6.5                7.31
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02457/joss.02457/10.21105.joss.02457.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.3909340 is OK

MISSING DOIs

- https://doi.org/10.1109/mcse.2007.55 may be missing for title: Matplotlib: A 2D graphics environment
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @EGaraldi, thanks for your submission to JOSS. As we are getting started, could you please revise your paper to include an explicit Statement of Need section, as described in [our documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)? Also, it looks like some DOIs may be missing for some references. Thanks!

**Comment by kyleniemeyer** [comment]
Hi @eloisabentivegna, the author suggested you as editor for this submission. Can you take this?

**Comment by kyleniemeyer** [comment]
@whedon invite @eloisabentivegna as editor

**Comment by whedon** [comment]
@eloisabentivegna has been invited to edit this submission.

**Comment by eloisabentivegna** [comment]
@whedon assign @eloisabentivegna as editor

@kyleniemeyer, I am happy to edit this submission!

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by eloisabentivegna** [comment]
@whedon add @ngnedin as reviewer

**Comment by whedon** [comment]
OK, @ngnedin is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon add @afialkov as reviewer

**Comment by whedon** [comment]
OK, @afialkov is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon add @Stefan-Heimersheim as reviewer

**Comment by whedon** [comment]
OK, @Stefan-Heimersheim is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2495.

**Comment by eloisabentivegna** [comment]
@whedon remove @gnedin as reviewer

@ngnedin has declared a conflict of interest with this submission's author (a recent common publication), and has stepped down.

**Comment by whedon** [comment]
OK, @gnedin is no longer a reviewer
