### ISSUE TITLE
[PRE REVIEW]: pirecorder: Controlled and automated image and video recording with the raspberry pi

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2458]
**Submitting author:** @JolleJolles (<a href="http://orcid.org/0000-0001-9905-2633">Jolle Wolter Jolles</a>)
**Repository:** <a href="http://github.com/jollejolles/pirecorder" target ="_blank">http://github.com/jollejolles/pirecorder</a>
**Version:** v3.1.0
**Editor:** @marcosvital
**Reviewers:** @lucask07, @DerJH
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JolleJolles. **Currently, there isn't an JOSS editor assigned** to your paper.

@JolleJolles if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (331.6 files/s, 44532.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                        18            320              0           1150
Python                           9            291            402           1093
HTML                             2             12              0            180
TeX                              1              1              0            139
Jupyter Notebook                 3              0            973             52
Sass                             1              8              0             30
YAML                             1              5             21             23
-------------------------------------------------------------------------------
SUM:                            35            637           1396           2667
-------------------------------------------------------------------------------


Statistical information for the repository '2458' was gathered on 2020/07/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jolle Jolles                   215          4066           3746           30.09
JolleJolles                      9           604            421            3.95
joljols                        448          9213           7910           65.96

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jolle Jolles                204            5.0         12.0                7.35
joljols                    1582           17.2          5.9                3.29
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41598-019-43845-9 is OK
- 10.1111/2041-210X.13005 is OK
- 10.1371/journal.pcbi.1006959 is OK
- 10.1371/journal.pbio.2003026 is OK
- 10.1016/j.cub.2017.08.004 is OK
- 10.1098/rspb.2017.2629 is OK
- 10.1016/j.anbehav.2019.06.022 is OK
- 10.1371/journal.pone.0169758 is OK
- 10.1016/j.dsr.2019.103136 is OK
- 10.1111/jofo.12182 is OK
- 10.1371/journal.pone.0220751 is OK
- 10.1089/zeb.2016.1412 is OK
- 10.3389/fevo.2018.00026 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02458/joss.02458/10.21105.joss.02458.pdf)

**Comment by kyleniemeyer** [comment]
Hi @JolleJolles, thanks for your submission to JOSS. As we are getting started, could you please revise your paper to include an explicit Statement of Need section, as described in [our documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)?

**Comment by kyleniemeyer** [comment]
Hi @marcosvital, the author suggested you as editor for this submission. Are you interested/available to take this one?

**Comment by kyleniemeyer** [comment]
@whedon invite @marcosvital as editor

**Comment by whedon** [comment]
@marcosvital has been invited to edit this submission.

**Comment by JolleJolles** [comment]
> Hi @JolleJolles, thanks for your submission to JOSS. As we are getting started, could you please revise your paper to include an explicit Statement of Need section, as described in [our documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)?

Dear @kyleniemeyer, thanks for your help. I have now updated ([commit](https://github.com/JolleJolles/pirecorder/commit/c2f23e4376c21bcafd6588e83650b258673644ab)) the paper to include a more explicit statement of need .

**Comment by marcosvital** [comment]
Hi, @kyleniemeyer! Yes, I can edit this submission.

**Comment by marcosvital** [comment]
@whedon assign @marcosvital as editor

**Comment by whedon** [comment]
OK, the editor is @marcosvital

**Comment by marcosvital** [comment]
Hi, @JolleJolles, I will be the editor of your submission.

I'll generate a second version of your manuscript proof, so you can start by checking if everything seems to be ok with it, as it will be the version used to start revision if nothing else changes. If you make any changes, you can use the same whedon command I will use below to create a new proof (or just let me know and I'll do it).

At the same time, we can start looking for reviewers for you submission. We usually ask the authors for suggestions, so let me know if you have anyone in mind that could do this - you can paste the github profile of anyone you think that could do it (but please don't tag anyone yet).
You can also check [this list of people](https://bit.ly/joss-reviewers) that have agreed to review for JOSS, and see if any of them may be suitable to review this submission.

**Comment by marcosvital** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02458/joss.02458/10.21105.joss.02458.pdf)

**Comment by JolleJolles** [comment]
> Hi, @JolleJolles, I will be the editor of your submission.
> 
> I'll generate a second version of your manuscript proof, so you can start by checking if everything seems to be ok with it, as it will be the version used to start revision if nothing else changes. If you make any changes, you can use the same whedon command I will use below to create a new proof (or just let me know and I'll do it).
> 
> At the same time, we can start looking for reviewers for you submission. We usually ask the authors for suggestions, so let me know if you have anyone in mind that could do this - you can paste the github profile of anyone you think that could do it (but please don't tag anyone yet).
> You can also check [this list of people](https://bit.ly/joss-reviewers) that have agreed to review for JOSS, and see if any of them may be suitable to review this submission.

Hi @marcosvital, thanks for your help. 

The generated proof looks good.

In terms of potential reviewers in my field, Jan Heuschele at the University of Oslo, Sajid Nazir at the London South Bank University, Robin Whytock at the University of Stirling and Mason Youngblood at the City University of New York all use the raspberry pi in their biological work. Going through the reviewer list and looking for keywords, people with some relevant expertise might be lucask07, nilesch-patil, jsta, djmitche, ethanwhite, sonal-raj, DanNixon, felixhenninger.

Hope that helps. Thanks!

**Comment by marcosvital** [comment]
Thank you for the reviewers suggestions, @JolleJolles. I'm contacting some of them by email, and will let you know when they reply. I might also invite some reviewers here at this topic, when we are able to identify their github profile, so you will be able to follow those.

**Comment by marcosvital** [comment]
Dear @lucask07, would you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review, once there are enough reviewers, we will move on to a new issue where the review will take place.

If you are not able to review, please let us know if you have recommendations for other reviewers.

**Comment by lucask07** [comment]
Hi, @marcosvital I am willing to review but do not have a RaspberryPi, camera combo. I'll let you decide if the ability to run the code completely with the appropriate hardware is required of the reviewers.

**Comment by marcosvital** [comment]
Thank you, @lucask07! I'll let you know soon, ok?

**Comment by marcosvital** [comment]
Hi, @JolleJolles, a quick update: Jan Heuschele agreed to be one of the reviewers. He is out of office right now, but it'll return in a week. My initial intent is to wait a little more to start review so we can have him, are you ok with that?

**Comment by marcosvital** [comment]
@lucask07, I think it will be ok with you not having the hardware if we got other reviewers to do that, so I would love if you could review this submission. Let me know if you are still available for that - we are likely to start next week.

**Comment by JolleJolles** [comment]
Great. Looking forward.

**Comment by lucask07** [comment]
OK @marcosvital, sounds good.

**Comment by marcosvital** [comment]
Hi, @JolleJolles, thank you so much for you patience. We are finally ready to start the reviewing process, and @DerJH will join us for that, along with @lucask07.

This will make us move to a new issue, and this one will be closed soon.

**Comment by marcosvital** [comment]
@whedon assign @lucask07 as reviewer

**Comment by whedon** [comment]
OK, @lucask07 is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @DerJH as reviewer

**Comment by whedon** [comment]
OK, @DerJH is now a reviewer

**Comment by marcosvital** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2584.
