### ISSUE TITLE
[PRE REVIEW]: The o80 C++ templated toolbox: Designing customized Python APIs for synchronizing realtime processes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2459]
**Submitting author:** @vincentberenz (<a href="http://orcid.org/0000-0003-2226-9660">Vincent Berenz</a>)
**Repository:** <a href="https://github.com/intelligent-soft-robots/o80" target ="_blank">https://github.com/intelligent-soft-robots/o80</a>
**Version:** 1.0
**Editor:** @gkthiruvathukal
**Reviewers:** @giodegas, @traversaro
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vincentberenz. **Currently, there isn't an JOSS editor assigned** to your paper.

@vincentberenz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.12 s (566.3 files/s, 52399.4 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
C/C++ Header                     43            595            624           3316
Markdown                         10            283              0            608
C++                              10             75              9            480
TeX                               1              8              0             79
CMake                             1             17             19             45
XML                               1              3              0             22
Bourne Again Shell                1              3              0             14
--------------------------------------------------------------------------------
SUM:                             67            984            652           4564
--------------------------------------------------------------------------------


Statistical information for the repository '2459' was gathered on 2020/07/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vincent Berenz                   1          2772              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vincent Berenz             2772          100.0          0.0               20.09
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/lra.2018.2795645 may be missing for title: Real-time Perception meets Reactive Motion Generation
- https://doi.org/10.1109/iros.2012.6386109 may be missing for title: MuJoCo: A physics engine for model-based control.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02459/joss.02459/10.21105.joss.02459.pdf)

**Comment by kyleniemeyer** [comment]
Hi @vincentberenz,  thanks for your submission to JOSS. As we are getting started, could you please revise your paper to include an explicit Statement of Need section, as described in [our documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)? Also, it looks like some DOIs may be missing for some references. Thanks!

**Comment by kyleniemeyer** [comment]
Hi @gkthiruvathukal, the author suggested you as editor for this submission. Are you interested/can you take this on?

**Comment by kyleniemeyer** [comment]
@whedon invite @gkthiruvathukal as editor

**Comment by whedon** [comment]
@gkthiruvathukal has been invited to edit this submission.

**Comment by gkthiruvathukal** [comment]
@kyleniemeyer Yes, I can add this to my plate! I may not get to editing until early next week.

**Comment by vincentberenz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02459/joss.02459/10.21105.joss.02459.pdf)

**Comment by vincentberenz** [comment]
@kyleniemeyer @gkthiruvathukal 
Thanks a lot for starting all this. First submission to JOSS, so looking forward to see how the review goes !

**Comment by HaoZeke** [comment]
Would be happy to review this.

**Comment by vincentberenz** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by vincentberenz** [comment]
From the provided list, possible suitable reviewers: giodegas, stevemacenski, traversaro, carlosjoseRG, mosteo

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@vincentberenz Thank you for suggesting possible reviewers.

**Comment by gkthiruvathukal** [comment]
@giodegas and @stevemacenski, would you be willing to contribute a review for this JOSS submission?

**Comment by giodegas** [comment]
@gkthiruvathukal ok I can try, if the deadline is not too close. Where can I get the paper?
(I never done it before here, so be patient :-) )

**Comment by giodegas** [comment]
Ok, I got the paper.

**Comment by SteveMacenski** [comment]
I don't think I'm suited to this paper, I'm a robotics expert.

**Comment by gkthiruvathukal** [comment]
@giodegas If you scroll up, you can see the "Check article proof" link. 

@SteveMacenski Thank you for responding.

**Comment by gkthiruvathukal** [comment]
@giodegas You had asked about the review process and criteria. Here are some helpful links from our journal docs:

Here are the reviewer guidelines:
https://joss.readthedocs.io/en/latest/reviewer_guidelines.html  

And here is a bit more detail about the review criteria:
https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by gkthiruvathukal** [comment]
@traversaro, Are you willing to contribute a review for this JOSS submission? I need two reviewers before I can proceed.

**Comment by giodegas** [comment]
Great, thank you @gkthiruvathukal  .

**Comment by gkthiruvathukal** [comment]
@whedon assign @giodegas as reviewer

**Comment by whedon** [comment]
OK, @giodegas is now a reviewer

**Comment by gkthiruvathukal** [comment]
@carlosjoseRG, Are you willing to contribute a review for this JOSS submission? I need two reviewers before I can proceed.

**Comment by vincentberenz** [comment]
@gkthiruvathukal Hi, any chance this may go forward ?

**Comment by gkthiruvathukal** [comment]
Hi @vincentberenz. Yes, it will more forward. I need a second reviewer. Thank you for your patience. Trying to keep up with everything as my academic year started two weeks ago. Going to invite anotehr now to join @giodegas.

**Comment by gkthiruvathukal** [comment]
@carlosjoseRG Are you willing to contribute a review for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@stevemacenski Are you willing to contribute a review for this JOSS submission?

**Comment by vincentberenz** [comment]
@gkthiruvathukal Anything I can do to help this going forward ?

**Comment by traversaro** [comment]
> @traversaro, Are you willing to contribute a review for this JOSS submission? I need two reviewers before I can proceed.

Sorry for the delay, I will be happy to review this submission.

**Comment by gkthiruvathukal** [comment]
@whedon add @traversaro as reviewer

**Comment by whedon** [comment]
OK, @traversaro is now a reviewer

**Comment by gkthiruvathukal** [comment]
@traversaro Thanks for your willingness to serve. I will move this to the review stage now.

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2752.

**Comment by vincentberenz** [comment]
@traversaro @giodegas 

I am working on generating a debian for o80. I will finalize this in the upcoming days (i.e. broader support, documentation, etc), but I though sharing it with you early on may help with the review.

https://owncloud.tuebingen.mpg.de/index.php/s/saSsfK6G5G7aAj9

```bash
sudo apt install ./o80_1.00-1.deb
```

limitations:
- only amd64
- assumes default python3 is python3.6.*

I tested on both my desktop (ubuntu 18.04) and a vanilla ubuntu 18.04 docker image.

This may require fyplot:

```bash
sudo pip3 install fyplot
```

To sanity check installation worked, in a python3 terminal:

```python
import o80
```

if this works (thanks for letting me know of any difficulty), you should be able to run the demos:

```bash
git clone https://github.com/intelligent-soft-robots/o80_example.git
cd o80_example/demos
```

in a first terminal:

```bash
python3 ./standalone_backend.py
# note: has to be python3
```

in a second terminal:

```bash
python3 ./duration_commands.py
# or another demo
```

If first there is another configuration you'd like me to test this on (e.g. other version of ubuntu), please let me know

**Comment by giodegas** [comment]
cannot do the review, sorry.
