### ISSUE TITLE
[PRE REVIEW]: tidyHeatmap: an R package for modular heatmap production based on tidy principles

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2460]
**Submitting author:** @stemangiola (<a href="http://orcid.org/0000-0001-7474-836X">Stefano Mangiola</a>)
**Repository:** <a href="https://github.com/stemangiola/tidyHeatmap" target ="_blank">https://github.com/stemangiola/tidyHeatmap</a>
**Version:** v1.1.0
**Editor:** @karthik
**Reviewers:** @rlbarter, @AliciaSchep
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @stemangiola. **Currently, there isn't an JOSS editor assigned** to your paper.

@stemangiola if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.13 s (246.8 files/s, 36230.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               11            589            968           1969
HTML                             1             33              2            372
Markdown                         3             76              0            270
TeX                              1              3              0             95
Rmd                              3             73            123             93
YAML                             4             16              2             90
SVG                             10              6              1             63
-------------------------------------------------------------------------------
SUM:                            33            796           1096           2952
-------------------------------------------------------------------------------


Statistical information for the repository '2460' was gathered on 2020/07/09.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.01686 is OK

MISSING DOIs

- https://doi.org/10.1093/bioinformatics/btw313 may be missing for title: Complex heatmaps reveal patterns and correlations in multidimensional genomic data
- https://doi.org/10.1093/bioinformatics/btu393 may be missing for title: circlize implements and enhances circular visualization in R

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02460/joss.02460/10.21105.joss.02460.pdf)

**Comment by kyleniemeyer** [comment]
Hi @stemangiola,  thanks for your submission to JOSS. As we are getting started, could you please resolve a few issues?
- Please revise your paper to include an explicit Statement of Need section, as described in [our documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)? 
- We cannot find an open-source license in your repository. 
- Also, it looks like some DOIs may be missing for some references.

Thanks!

**Comment by kyleniemeyer** [comment]
Hey @karthik, could you edit this one?

**Comment by kyleniemeyer** [comment]
@whedon invite @karthik as editor

**Comment by whedon** [comment]
@karthik has been invited to edit this submission.

**Comment by stemangiola** [comment]
> 
> 
> Hi @stemangiola, thanks for your submission to JOSS. As we are getting started, could you please resolve a few issues?
> 
>     * Please revise your paper to include an explicit Statement of Need section, as described in [our documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)?
> 
>     * We cannot find an open-source license in your repository.
> 
>     * Also, it looks like some DOIs may be missing for some references.
> 
> 
> Thanks!

Thanks. Those to issues were resolved.

**Comment by stemangiola** [comment]
Could I/you please invite the other author @ papenfuss to this review?

**Comment by stemangiola** [comment]
The statement of need has been added to paper.md

**Comment by kyleniemeyer** [comment]
Hi @stemangiola, the review issues are fully open so anyone can join— @papenfuss, feel free to chime in here/follow this issue!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02460/joss.02460/10.21105.joss.02460.pdf)

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
@whedon add @rlbarter as reviewer

**Comment by whedon** [comment]
OK, @rlbarter is now a reviewer

**Comment by karthik** [comment]
Hello @AliciaSchep Would you be able to serve as a second reviewer on this submission? 🙏

**Comment by AliciaSchep** [comment]
Sure!

**Comment by karthik** [comment]
@Whedon add @AliciaSchep as reviewer

**Comment by whedon** [comment]
OK, @AliciaSchep is now a reviewer

**Comment by karthik** [comment]
@Whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2472.
