### ISSUE TITLE
[REVIEW]: Grama: A Grammar of Model Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2462]
**Submitting author:** @zdelrosario (<a href="http://orcid.org/0000-0003-4676-1692">Zachary del Rosario</a>)
**Repository:** <a href="https://github.com/zdelrosario/py_grama" target ="_blank">https://github.com/zdelrosario/py_grama</a>
**Version:** v0.1.3
**Editor:** @mjsottile
**Reviewer:** @BastinRobin, @rodrigokataishi
**Archive:** <a href="https://doi.org/10.6084/m9.figshare.12725066.v2" target="_blank">10.6084/m9.figshare.12725066.v2</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c99258e95bfd954b708da1ada5f2c0c1/status.svg)](https://joss.theoj.org/papers/c99258e95bfd954b708da1ada5f2c0c1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c99258e95bfd954b708da1ada5f2c0c1"><img src="https://joss.theoj.org/papers/c99258e95bfd954b708da1ada5f2c0c1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c99258e95bfd954b708da1ada5f2c0c1/status.svg)](https://joss.theoj.org/papers/c99258e95bfd954b708da1ada5f2c0c1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/zdelrosario/py_grama" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@BastinRobin & @rodrigokataishi, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mjsottile know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zdelrosario/py_grama">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@zdelrosario) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zdelrosario/py_grama">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@zdelrosario) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @BastinRobin, @rodrigokataishi it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2514/6.2020-0414 is OK
- 10.1073/pnas.1319030111 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.21105/joss.01686 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.1016/j.commatsci.2018.05.018 is OK
- 10.1061/9780784413609.257 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02462/joss.02462/10.21105.joss.02462.pdf)

**Comment by BastinRobin** [comment]
@mjsottile  I have completed my review.

**Comment by rodrigokataishi** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by mjsottile** [comment]
:wave: @rodrigokataishi I saw some activity on this issue from you.  Do you need any assistance completing your review?  Let me know if I can be of help.

**Comment by rodrigokataishi** [comment]
@mjsottile Dear Mathiew. I can´t edit the checklist. It appears to be closed. 
Any help will be welcome. I already accepted the invitation. But I can not edit the list to confirm the items. 
Thanks

**Comment by mjsottile** [comment]
@whedon re-invite @rodrigokataishi as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@rodrigokataishi please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by mjsottile** [comment]
@rodrigokataishi That should fix your problem accessing the checklist.  Let me know if it doesn’t.

**Comment by rodrigokataishi** [comment]
@mjsottile I have completed my review. Thanks for your help!

**Comment by mjsottile** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2514/6.2020-0414 is OK
- 10.1073/pnas.1319030111 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.21105/joss.01686 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.1016/j.commatsci.2018.05.018 is OK
- 10.1061/9780784413609.257 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mjsottile** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02462/joss.02462/10.21105.joss.02462.pdf)

**Comment by mjsottile** [comment]
@zdelrosario : Please fix the citations in the last section of the paper.  It appears that you use commas to separate multiple entries in a single citation block, which is causing the reference names to appear in the text instead of the correct citations.  Instead you should use semicolons.  See: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

Once you've fixed that, please archive a tagged release of your submission on an archive site such as Zenodo or figshare, and post the DOI for the archive to this issue thread.  Finally, ensure that the version number for the submission at the top of this issue matches the version of the archived code.  If it does not, let me know what the correct version number should be so I can set it.

**Comment by zdelrosario** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02462/joss.02462/10.21105.joss.02462.pdf)

**Comment by zdelrosario** [comment]
@mjsottile I have uploaded py_grama v0.1.3 (matching version above) to Figshare, under the DOI: https://doi.org/10.6084/m9.figshare.12725066.v1

**Comment by mjsottile** [comment]
@whedon set https://doi.org/10.6084/m9.figshare.12725066.v1 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.12725066.v1" target="_blank">10.6084/m9.figshare.12725066.v1</a> is the archive.

**Comment by mjsottile** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2514/6.2020-0414 is OK
- 10.1073/pnas.1319030111 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.21105/joss.01686 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.1016/j.commatsci.2018.05.018 is OK
- 10.1061/9780784413609.257 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1595

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1595, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
Hi @zdelrosario! I'm taking over to finish publication of this paper. I'm not so familiar with figshare, but can you edit the metadata on your archive there so that the title and author list match your paper for this publication? It's nice to have it consistent.

**Comment by zdelrosario** [comment]
Hi @kthyng! I've updated the Figshare title to match and have confirmed that the author is me. In case it's useful here's the DOI again: https://doi.org/10.6084/m9.figshare.12725066.v2

**Comment by kthyng** [comment]
@zdelrosario excellent! Your paper looks good to me, so we're ready to finish!

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1288130490625675265) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1596
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02462](https://doi.org/10.21105/joss.02462)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
@whedon set https://doi.org/10.6084/m9.figshare.12725066.v2 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.12725066.v2" target="_blank">10.6084/m9.figshare.12725066.v2</a> is the archive.

**Comment by kthyng** [comment]
I'm going to leave this issue open until the doi resolves, but in the meantime...

Congrats to @zdelrosario on your new publication!! Thanks to @mjsottile for editing and to @BastinRobin and @rodrigokataishi for reviewing. This process would not be possible without your time and expertise!

**Comment by zdelrosario** [comment]
Thanks @kthyng, @mjsottile , @BastinRobin , and @rodrigokataishi! This is my first time publishing with JOSS, and I'm super-impressed by your speed and process.

**Comment by kthyng** [comment]
@openjournals/dev the doi still isn't resolving for me — can you take a look?

**Comment by kthyng** [comment]
@openjournals/dev just kidding! Sorry for the bother. 

Everything looks to be in order!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02462/status.svg)](https://doi.org/10.21105/joss.02462)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02462">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02462/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02462/status.svg
   :target: https://doi.org/10.21105/joss.02462
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02462/status.svg)](https://doi.org/10.21105/joss.02462)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
