### ISSUE TITLE
[PRE REVIEW]: Gridap: An extensible Finite Element toolbox in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2464]
**Submitting author:** @fverdugo (<a href="http://orcid.org/0000-0003-3667-443X">Francesc Verdugo</a>)
**Repository:** <a href="https://github.com/gridap/Gridap.jl" target ="_blank">https://github.com/gridap/Gridap.jl</a>
**Version:** v0.12.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @PetrKryslUCSD, @TeroFrondelius
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @fverdugo. **Currently, there isn't an JOSS editor assigned** to your paper.

@fverdugo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.01 s (292.5 files/s, 24204.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              1              0              0            234
Markdown                         2             10              0             57
JSON                             1              0              0             30
-------------------------------------------------------------------------------
SUM:                             4             10              0            321
-------------------------------------------------------------------------------


Statistical information for the repository '2464' was gathered on 2020/07/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/1163641.1163644 is OK
- 10.1145/1268776.1268779 is OK
- 10.5281/zenodo.3357100 is OK
- 10.1007/978-3-319-52462-7 is OK
- 10.1145/1644001.1644009 is OK
- 10.1137/141000671 is OK
- 10.1145/2998441 is OK
- 10.1016/j.cpc.2019.107059 is OK
- 10.1007/s11831-017-9244-1 is OK
- 10.5334/jors.151 is OK
- 10.5334/jors.182 is OK
- 10.1145/1731022.1731030 is OK
- 10.11588/ans.2015.100.20553 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02464/joss.02464/10.21105.joss.02464.pdf)

**Comment by kyleniemeyer** [comment]
Hi @fverdugo, it looks like you have placed your paper in a separate repository from the software itself. We strongly encourage authors to put the paper in the same repository as the software, and in fact a lot of the checks that our bot @whedon does relies on this. (Right now we have no connection to the software repository.)

Do you have a particular reason for putting the paper in a separate repo? We do support the whole publication process with the paper being in a non-default branch, so if you prefer to not include the paper in your main/master branch, you could do that.

cc @arfon

**Comment by fverdugo** [comment]
Hi @kyleniemeyer,

I have moved the paper to the repo https://github.com/gridap/Gridap.jl branch `joss`. Hope it is now OK!

cc @santiagobadia

**Comment by kyleniemeyer** [comment]
Thanks @fverdugo! 

@arfon, could you update the repo URL in the system?

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02464/joss.02464/10.21105.joss.02464.pdf)

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.45 s (794.1 files/s, 100237.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                          324           8272           1289          32523
Markdown                        21            350              0           1294
Lisp                             6            226              0            687
YAML                             2              6              1            109
TOML                             2              5              0             49
-------------------------------------------------------------------------------
SUM:                           355           8859           1290          34662
-------------------------------------------------------------------------------


Statistical information for the repository '2464' was gathered on 2020/07/11.
No commited files with the specified extensions were found.
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer this looks very interesting to me!! If others (e.g. @labarba or @meg-simula ? ) cannot take this to edit I'd be interested. Alternatively I can join as a reviewer. 
Also folks from the Julia FEM community might be good candidates to serve as reviewers: https://github.com/JuliaFEM

I just wanted to point out their pre-print as well https://arxiv.org/abs/1910.01412

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@maikkirapo @ahojukka5 @KristofferC @ChrisRackauckas @burcugrbz would you be interested in reviewing this submission for [JOSS](https://joss.theoj.org/)? 

_Gridap: An extensible Finite Element toolbox in Julia_
**Paper**: https://github.com/openjournals/joss-papers/blob/joss.02464/joss.02464/10.21105.joss.02464.pdf
**Software**: https://github.com/gridap/Gridap.jl

The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on the software and a short paper. 

Let me know if you are interested and I'll add you as reviewer. 

Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@fverdugo can you comment on this pre-print https://arxiv.org/abs/1910.01412 ? We do not allow duplicate publication at JOSS. Can you please clarify the difference between this pre-print (has it been published/submitted anywhere else yet?) and the JOSS paper?

**Comment by fverdugo** [comment]
The preprint in arxiv is a completely different and separate thing.  It is just a paper-like version of our tutorials in https://github.com/gridap/Tutorials. Not under review nor published anywhere.

If you open the two PDFs, you would clearly see the differences. E.g.,

 https://arxiv.org/abs/1910.01412 has 31 pages.

[Our JOSS submission](https://github.com/openjournals/joss-papers/blob/joss.02464/joss.02464/10.21105.joss.02464.pdf) has 3 pages.

**Comment by Kevin-Mattheus-Moerman** [comment]
@fverdugo thanks that is what I thought. Good to formally confirm it here.

**Comment by Kevin-Mattheus-Moerman** [comment]
@fverdugo as you can see I started inviting reviewers. Mainly those related to the JuliaFEM community. Let me know if you had any other reviewers in mind. You can mention any suggested reviewers here if you like (leave out @ in their GitHub handles please).

**Comment by fverdugo** [comment]
Perhaps @PetrKryslUCSD would like to review

**Comment by Kevin-Mattheus-Moerman** [comment]
@PetrKryslUCSD would you be interested in reviewing this submission for [JOSS](https://joss.theoj.org/)? 

_Gridap: An extensible Finite Element toolbox in Julia_
**Paper**: https://github.com/openjournals/joss-papers/blob/joss.02464/joss.02464/10.21105.joss.02464.pdf
**Software**: https://github.com/gridap/Gridap.jl

The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on the software and a short paper. 

Let me know if you are interested and I'll add you as reviewer. 

Thanks!

**Comment by PetrKryslUCSD** [comment]
Sure, I'll be happy to help.
Petr Krysl
Prof. and Vice chair for undergraduate education
Structural engineering department
University of California, San Diego

**Comment by ChrisRackauckas** [comment]
I'm sorry but I won't have time right now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @PetrKryslUCSD as reviewer

**Comment by whedon** [comment]
OK, @PetrKryslUCSD is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@maikkirapo @ahojukka5 @KristofferC @burcugrbz would you be interested in reviewing this submission for [JOSS](https://joss.theoj.org/)? 

_Gridap: An extensible Finite Element toolbox in Julia_
**Paper**: https://github.com/openjournals/joss-papers/blob/joss.02464/joss.02464/10.21105.joss.02464.pdf
**Software**: https://github.com/gridap/Gridap.jl

The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on the software and a short paper. 

Let me know if you are interested and I'll add you as reviewer. 

Thanks!

**Comment by TeroFrondelius** [comment]
I am on vacation, but I can do the review in the beginning of August (after a week or so). Also, this would be my first JOSS review, thus possible some learning due to this.

**Comment by Kevin-Mattheus-Moerman** [comment]
Excellent @TeroFrondelius could you also share (or add on your GitHub profile) a professional profile or ORCID link (is this you?: http://orcid.org/0000-0003-2288-0902)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @TeroFrondelius as reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@TeroFrondelius do you think you could convince another juliafem person to join this review?

**Comment by PetrKryslUCSD** [comment]
I have to admit I can't make sense of the instructions.
Do the reviewers submit issues in a repository specifically for this paper?
Where is it? Or are the issues to be filed in the repository of the package
that is
being reviewed? Is there an example of such a review process?

Thanks,
Petr Krysl

**Comment by PetrKryslUCSD** [comment]
I guess what confuses me is the variety of conversations here. This does not seem to be focused on the review itself.
But looking at the other issues, perhaps this is how it is supposed to look. Meaning reviewers submitting their comments here. Am I right?

**Comment by Kevin-Mattheus-Moerman** [comment]
> I guess what confuses me is the variety of conversations here. This does not seem to be focused on the review itself.
> But looking at the other issues, perhaps this is how it is supposed to look. Meaning reviewers submitting their comments here. Am I right?

Apologies for any confusion, let me clarify. This is a prereview issue where we assign editors/reviewers. The actual review will take place in a dedicated review issue. I'm hoping to recruit one more reviewer.
In the review issue there will be a checkbox list to guide you through the process. You can leave comments to the authors there and also link to issues on their main repository for larger issues.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @TeroFrondelius as reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @TeroFrondelius as reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon @openjournals/dev it seems whedon is stuck. It won't assign a reviewer. Can you help?

**Comment by arfon** [comment]
@whedon add @TeroFrondelius as reviewer

**Comment by whedon** [comment]
OK, @TeroFrondelius is now a reviewer

**Comment by arfon** [comment]
> @arfon @openjournals/dev it seems whedon is stuck. It won't assign a reviewer. Can you help?

Not sure what was going on here sorry. Minor hiccup...

**Comment by TeroFrondelius** [comment]
> another juliafem person to join this review

@ahojukka5 what you think, would you have time for this review?

**Comment by Kevin-Mattheus-Moerman** [comment]
@PetrKryslUCSD @TeroFrondelius I'll start the review issue now to avoid further delay. @ahojukka5 if you are able to help that would be great and I can still add you as a reviewer later.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2520.

**Comment by KristofferC** [comment]
FWIW, if still needed, I can probably look at it as well.

**Comment by Kevin-Mattheus-Moerman** [comment]
@KristofferC great I'll add you over at the review issue #2520
