### ISSUE TITLE
[PRE REVIEW]: MiTepid_sim: A repository to simulate the spread of COVID-19 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2466]
**Submitting author:** @vahid-sb (<a href="http://orcid.org/0000-0001-6544-7960">Vahid S. Bokharaie</a>)
**Repository:** <a href="https://github.com/vahid-sb/MiTepid_sim" target ="_blank">https://github.com/vahid-sb/MiTepid_sim</a>
**Version:** v0.0.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vahid-sb. **Currently, there isn't an JOSS editor assigned** to your paper.

@vahid-sb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.14 s (80.1 files/s, 16333.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            237            636           1175
reStructuredText                 1             41              5            148
YAML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            11            278            641           1324
-------------------------------------------------------------------------------


Statistical information for the repository '2466' was gathered on 2020/07/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vahid Bokharaie                 23          4571           2523          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vahid Bokharaie            2048           44.8          0.7                8.84
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2466 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @vahid-sb, thanks for your interest in JOSS! Before we get started, it doesn't look like your repository actually has a paper. Unless I am missing it somehow, please write your paper following our [guidelines](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain); in the meantime, I am going to pause this submission.

**Comment by sara-02** [comment]
Hey @kyleniemeyer @vahid-sb let me know when you guys resume working on this one, I would be interested to review it. I recently worked on epidemic models for one my projects, and have some idea about them. Would love to learn more about them.

**Comment by oliviaguest** [comment]
Happy to edit this when the time comes. I have a deep interest in COVID modelling, know appropriate reviewers, and co-organised a session at ICML 2020 on COVID.

**Comment by danielskatz** [comment]
@vahid-sb - I'm also rejecting this for the same reason - no response in 24 days...

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by vahid-sb** [comment]
@danielskatz @oliviaguest @kyleniemeyer @sara-02 Just wanted to apologise to you all for not responding to you all in a timely manner. I thought I get an email notification when I receive a message in github, but apparently not. Hence, I completely missed this conversation. So, my sincere apologies for missing out on your messages. 
I will add the pdf files following the journal guidelines to the repo and will submit it for review again.
