### ISSUE TITLE
[PRE REVIEW]: causal-curve: A Python Causal Inference Package to Estimate Causal Dose-Response Curves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2467]
**Submitting author:** @ronikobrosly (<a href="http://orcid.org/0000-0003-0363-9662">Roni Kobrosly</a>)
**Repository:** <a href="https://github.com/ronikobrosly/causal-curve" target ="_blank">https://github.com/ronikobrosly/causal-curve</a>
**Version:** v0.3.2
**Editor:** @oliviaguest
**Reviewers:** @cmparlettpelleriti, @tomfaulkenberry, @alexjonesphd
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ronikobrosly. **Currently, there isn't an JOSS editor assigned** to your paper.

@ronikobrosly if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (389.8 files/s, 51520.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            512            609           1483
reStructuredText                11            292             80            561
Jupyter Notebook                 1              0            427            323
Markdown                         2             56              0            142
TeX                              1              8              0             53
DOS Batch                        1              8              1             26
YAML                             1              7              3             15
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            35            887           1127           2612
-------------------------------------------------------------------------------


Statistical information for the repository '2467' was gathered on 2020/07/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Roni Kobrosly                   44          4262           1658          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Roni Kobrosly              2604           61.1          1.3               10.33
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1177/0962280209340213 is OK
- 10.2202/1557-4679.1181 is OK
- 10.1037/a0020761 is OK

MISSING DOIs

- https://doi.org/10.2202/1557-4679.1043 may be missing for title: Targeted maximum likelihood learning.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02467/joss.02467/10.21105.joss.02467.pdf)

**Comment by ronikobrosly** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by kyleniemeyer** [comment]
Hi @cMadan, this is slightly outside your field, but could you edit this one?

**Comment by kyleniemeyer** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by ronikobrosly** [comment]
Hello, thanks so much for considering this work. I looked over the list of
possible reviewers and think the following people would be great, due to
their experience with causal inference or epidemiology:

*usernames*:

nhejazi
seabbs
acolum

**Comment by cMadan** [comment]
@kyleniemeyer, sorry, I don't think I can take on another right now.

**Comment by ronikobrosly** [comment]
@kyleniemeyer , is it okay to, say, add a sentence or make a small edit at this step in the process? Or should I hold off until reviewers give feedback?

**Comment by kyleniemeyer** [comment]
@ronikobrosly yes, feel free to make edits right now, since we are still working to find an editor and reviewers.

**Comment by ronikobrosly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02467/joss.02467/10.21105.joss.02467.pdf)

**Comment by ronikobrosly** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by ronikobrosly** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1177/0962280209340213 is OK
- 10.2202/1557-4679.1181 is OK
- 10.1037/a0020761 is OK

MISSING DOIs

- https://doi.org/10.2202/1557-4679.1043 may be missing for title: Targeted maximum likelihood learning.

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
@whedon assign @tomfaulkenberry as reviewer

**Comment by whedon** [comment]
OK, @tomfaulkenberry is now a reviewer

**Comment by oliviaguest** [comment]
@ronikobrosly when you get a sec, please add the missing DOI and then recompile the PDF using the `@whedon generate pdf` command. ☺️

**Comment by ronikobrosly** [comment]
of course @oliviaguest !

**Comment by ronikobrosly** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02467/joss.02467/10.21105.joss.02467.pdf)

**Comment by ronikobrosly** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1177/0962280209340213 is OK
- 10.2202/1557-4679.1181 is OK
- 10.1037/a0020761 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ronikobrosly** [comment]
@oliviaguest , because it was a Berkeley internal dept paper and it seems like the other TMLE reference covers it I ended up removing that reference.

**Comment by oliviaguest** [comment]
@ronikobrosly awesome and thanks!

**Comment by oliviaguest** [comment]
@whedon assign @cmparlettpelleriti as reviewer

**Comment by whedon** [comment]
OK, @cmparlettpelleriti is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @tomfaulkenberry as reviewer

**Comment by whedon** [comment]
OK, @tomfaulkenberry is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @cmparlettpelleriti as reviewer

**Comment by whedon** [comment]
OK, @cmparlettpelleriti is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @alexjonesphd as reviewer

**Comment by whedon** [comment]
OK, @alexjonesphd is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2523.

**Comment by oliviaguest** [comment]
👋 @cmparlettpelleriti, @tomfaulkenberry, @alexjonesphd: please go to #2523 to get the review started! ✨
