### ISSUE TITLE
[PRE REVIEW]: NO-DOUBT: A Decision Support Web Platform based on AHP

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2469]
**Submitting author:** @gdede-hua (<a href="http://orcid.org/0000-0003-2947-7470">Georgia Dede</a>)
**Repository:** <a href="https://github.com/gdede-hua/decision-survey-platform" target ="_blank">https://github.com/gdede-hua/decision-survey-platform</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gdede-hua. **Currently, there isn't an JOSS editor assigned** to your paper.

@gdede-hua if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2469 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2469/paper.md): mapping values are not allowed in this context at line 113 column 55 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.85 s (331.1 files/s, 129916.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
PHP                            264          12935          35731          56957
SQL                              1             67            102           1853
CSS                              5            259             47           1259
Markdown                         3            122              0            330
HTML                             1             42              1            316
JavaScript                       7             41            194            199
TeX                              1             42              0            161
-------------------------------------------------------------------------------
SUM:                           282          13508          36075          61075
-------------------------------------------------------------------------------


Statistical information for the repository '2469' was gathered on 2020/07/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dimitrios Alexandrak             1           434              0           17.67
gdede-hua                        1          2022              0           82.33

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dimitrios Alexandrak        434          100.0          0.0               44.70
gdede-hua                  2022          100.0          0.0               10.68
```

**Comment by kyleniemeyer** [comment]
Hi @gdede-hua, thanks for your interest in JOSS.

It looks like your paper is missing some important elements, and also has some formatting/commands that we don't support. Please take a look at the [documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) on what papers should contain, and the example, and let me know when you've updated your paper.

**Comment by kyleniemeyer** [comment]
Hi @sbenthall, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@sbenthall, could you handle this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by sbenthall** [comment]
I'm concerned: this library is in PHP, and there are no listed editors in the reviewer spreadsheet that have PHP as listed expertise. I'm not sure where I would start searching for reviewers.

**Comment by danielskatz** [comment]
Well, it's now been 18 days without the authors doing what they were asked to, so let's pause it for now, and if there is no response in next week or so, we will reject it.

**Comment by sbenthall** [comment]
I see now that there are listed PHP reviewers, and that my inability to find them earlier was due to a networking error.

I'd be happy to edit this once it is unpaused.

**Comment by danielskatz** [comment]
@whedon reject

given no response from the authors

But feel free to resubmit if you make the requested changes in the future.

**Comment by whedon** [comment]
Paper rejected.
