### ISSUE TITLE
[REVIEW]: lattice_mc: A Python Lattice-Gas Monte Carlo Module

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#247]
**Submitting author:** @bjmorgan (<a href="http://orcid.org/0000-0002-3056-8233">Benjamin J. Morgan</a>)
**Repository:** <a href="https://github.com/bjmorgan/lattice_mc" target ="_blank">https://github.com/bjmorgan/lattice_mc</a>
**Version:** 1.0.0
**Editor:** @labarba
**Reviewer:** @asmit3
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.582402" target="_blank">10.5281/zenodo.582402</a>

## Status

[![status](http://joss.theoj.org/papers/6940b7bb0d59be86b8823a10780caae0/status.svg)](http://joss.theoj.org/papers/6940b7bb0d59be86b8823a10780caae0)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/6940b7bb0d59be86b8823a10780caae0"><img src="http://joss.theoj.org/papers/6940b7bb0d59be86b8823a10780caae0/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/6940b7bb0d59be86b8823a10780caae0/status.svg)](http://joss.theoj.org/papers/6940b7bb0d59be86b8823a10780caae0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bjmorgan/lattice_mc" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bjmorgan/lattice_mc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [x] **Authorship:** Has the submitting author (@bjmorgan) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @asmit3 it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by asmit3** [comment]
I was able to tick off all the boxes except the one on Community Guidelines since the LICENSE file appears incomplete (no year or full name of author). Also I didn't see an email address for correspondence. 
The default unittest given in the README file throws 3 errors when I run on my mac with python 3.5 (see attachment)
![screenshot 2017-05-01 12 06 07](https://cloud.githubusercontent.com/assets/10836284/25590814/cb3d5f9c-2e66-11e7-9e77-cd67ebe677d4.png)

The ipython notebook was very useful in explaining how the code works.

**Comment by bjmorgan** [comment]
The errors under python 3.5 were due to test methods that were introduced with version 3.6. I have replaced these with 3.5+ compatible versions:
https://github.com/bjmorgan/lattice_mc/commit/695e679e66e2331b6e6c23c70e983addf555ec38

I have added the year and my name to the LICENSE file:
https://github.com/bjmorgan/lattice_mc/commit/eb706fb5160b018ec134a532c49b49bd189c26b2

My email is given in `setup.py`, and I have added it to `paper.md`:
https://github.com/bjmorgan/lattice_mc/commit/0d3287bc5ce02823b032d29105998b6cd63a4195

I don't know if you would recommend including my email address elsewhere in the package?

**Comment by asmit3** [comment]
The changes are satisfactory for me. I don't have any more comments. Thanks

**Comment by labarba** [comment]
@arfon -- We are ready to accept this paper.

**Comment by arfon** [comment]
@bjmorgan - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by bjmorgan** [comment]
@arfon Would it be appropriate to bump the version number to e.g. 1.0.1 to differentiate from the as submitted version?

**Comment by bjmorgan** [comment]
The doi for the "as accepted" version (1.0.1) is 10.5281/zenodo.582402
The doi for the original submitted version (1.0.0) is 10.5281/zenodo.546262

**Comment by labarba** [comment]
@asmit3 : Thank you for your review, and I hope you enjoyed being part of this new publishing model and you'll consider submitting to JOSS in the future!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.582402 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.582402" target="_blank">10.5281/zenodo.582402</a> is the archive.

**Comment by arfon** [comment]
Hi @bjmorgan - could you move the references you currently have in the `paper.md` file into a `paper.bib` file and cite them directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)). They are automatically compiled into the PDF when we process the paper.

**Comment by bjmorgan** [comment]
@arfon: I have updated the `paper.md`.

https://github.com/bjmorgan/lattice_mc/commit/3ec30748f24614b5404da739b64171d0549806b7
https://github.com/bjmorgan/lattice_mc/commit/4fc9d0380177dc1ca2994a2440acd11840be4d20

**Comment by arfon** [comment]
@asmit3 many thanks for your review and to @labarba for editing this submission ✨ 

@bjmorgan - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00247 ⚡️:rocket: :boom:
