### ISSUE TITLE
[PRE REVIEW]: PulseqDiffusion: PyPulseq implementation of Diffusion-Weighted Echo Planar Imaging

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2470]
**Submitting author:** @ritagnunes (<a href="http://orcid.org/0000-0001-7425-5717">Rita G. Nunes</a>)
**Repository:** <a href="https://github.com/ritagnunes/PulseqDiffusion" target ="_blank"> https://github.com/ritagnunes/PulseqDiffusion</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @mathieuboudreau, @grlee77
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ritagnunes. **Currently, there isn't an JOSS editor assigned** to your paper.

@ritagnunes if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2470 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
Hi @ritagnunes, it looks like the URL you included when submitting is incorrect. Can you fix this?

**Comment by ritagnunes** [comment]
The full URL should be:  https://github.com/ritagnunes/PulseqDiffusion
Thanks

**Comment by kyleniemeyer** [comment]
@arfon can we tell whedon to update the repo URL to https://github.com/ritagnunes/PulseqDiffusion for checking and building the paper?

**Comment by kyleniemeyer** [comment]
I edited the metadata above manually, but I assume that doesn't change anything internally

**Comment by arfon** [comment]
> @arfon can we tell whedon to update the repo URL to https://github.com/ritagnunes/PulseqDiffusion for checking and building the paper?

I've fixed this on the back end too. For now there's not a Whedon-way to do this.

**Comment by kyleniemeyer** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.22 s (218.8 files/s, 22313.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                          24            271            399           1432
Python                          11            410            439           1357
Markdown                         6             72              0            214
TeX                              1             14              0            139
reStructuredText                 5             57             75             62
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            49            836            921           3239
-------------------------------------------------------------------------------


Statistical information for the repository '2470' was gathered on 2020/07/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Keerthi Sravan Ravi              4           478            368            7.26
PavanPoojar                      1           647              0            5.55
Rita G. Nunes                   17          3246           2821           52.08
opennog                         12          2636           1454           35.11

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Keerthi Sravan Ravi         352           73.6          0.1                0.00
Rita G. Nunes               794           24.5          1.0               17.51
opennog                    1060           40.2          1.2               17.74
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02470/joss.02470/10.21105.joss.02470.pdf)

**Comment by kyleniemeyer** [comment]
Hey @Kevin-Mattheus-Moerman, I know you've already got a lot on your plate, but this looks to be up your alley, and builds on a previous paper that you edited. Can you take this one on?

**Comment by kyleniemeyer** [comment]
@whedon invite @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
@Kevin-Mattheus-Moerman has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@grlee77, @mathieuboudreau, @spinicist thanks for your review efforts to date! Would you be interested in helping with this review? It is related to this work you reviewed for us: https://github.com/openjournals/joss-reviews/issues/1725
@mfroeling this also looks like your cup of tea, would you be interested in helping? Thanks! 

Paper: https://github.com/openjournals/joss-papers/blob/joss.02470/joss.02470/10.21105.joss.02470.pdf
Software: https://github.com/ritagnunes/PulseqDiffusion

Also do let me know if I am overloading you with review requests.

**Comment by mathieuboudreau** [comment]
I can, but I'm only available in about a week as I'm currently on vacation.

**Comment by grlee77** [comment]
yes, I am available

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @mathieuboudreau as reviewer

**Comment by whedon** [comment]
OK, @mathieuboudreau is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
> I can, but I'm only available in about a week as I'm currently on vacation.

That is fine thank you so much!

**Comment by Kevin-Mattheus-Moerman** [comment]
> yes, I am available

Thanks!!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @grlee77 as reviewer

**Comment by whedon** [comment]
OK, @grlee77 is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2478.

**Comment by spinicist** [comment]
Hello,
I didn't get a chance to respond - as the others have kindly volunteered and I am very busy at the moment, I will decline this invitation. Thanks to @mathieuboudreau and @grlee77
