### ISSUE TITLE
[PRE REVIEW]: NetworkChange: Analyzing Network Changes in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2471]
**Submitting author:** @ysohn (<a href="http://orcid.org/0000-0002-9496-1907">Yunkyu Sohn</a>)
**Repository:** <a href="https://github.com/jongheepark/NetworkChange" target ="_blank">https://github.com/jongheepark/NetworkChange</a>
**Version:** v0.6
**Editor:** @kakiac
**Reviewers:** @akbaritabar, @marcjwilliams1, @martinmodrak
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ysohn. **Currently, there isn't an JOSS editor assigned** to your paper.

@ysohn if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (391.9 files/s, 113099.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              2            408              8           4230
R                               31            448           1926           2780
Rmd                              1             39            148             64
Markdown                         1              7              0             42
-------------------------------------------------------------------------------
SUM:                            35            902           2082           7116
-------------------------------------------------------------------------------


Statistical information for the repository '2471' was gathered on 2020/07/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.18637/jss.v024.i05 may be missing for title: Fitting position latent cluster models for social networks with latentnet
- https://doi.org/10.1214/19-ba1147 may be missing for title: Detecting Structural Changes in Longitudinal Network Data
- https://doi.org/10.1214/15-aoas839 may be missing for title: Multilinear tensor regression for longitudinal relational data
- https://doi.org/10.21236/ada458734 may be missing for title: Latent space approaches to social network analysis

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02471/joss.02471/10.21105.joss.02471.pdf)

**Comment by kyleniemeyer** [comment]
Hi @ysohn, thanks for your submission to JOSS. It looks like there are a few issues that need to be resolved as we get started:

- Your software repository does not appear to include an open source license
- Your paper is missing an explicit Statement of Need section, which is now required for articles as described in [our documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)
- Please remove these lines from your paper's YAML header: `aas-doi: 10.3847/xxxxx` and `aas-journal: Journal of Open Source Software.`
- Also, overall your paper is quite short. Although JOSS papers are generally only one or two pages on average (250-1000 words), your paper just barely passes that mark. I would recommend adding a bit more content, perhaps an example or more explanation/details of how the package works.
- It looks like a few of your references may be missing DOIs

Thanks!

**Comment by kyleniemeyer** [comment]
Hi @kakiac, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @kakiac as editor

**Comment by whedon** [comment]
@kakiac has been invited to edit this submission.

**Comment by kakiac** [comment]
Sure, @kyleniemeyer happy to edit this!

@whedon assign me as editor

**Comment by kakiac** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kakiac

**Comment by kakiac** [comment]
👋  @ysohn thanks for your submission to JOSS! 🥳  

I think I would like us to work on @kyleniemeyer 's comments above: https://github.com/openjournals/joss-reviews/issues/2471#issuecomment-656894068 before I pass this on to reviewers to review, as it will substantially improve the submission before they review it. Will you be able to address them? 

See for example this paper for an example of what a JOSS paper looks like: https://joss.theoj.org/papers/10.21105/joss.02265 

Many thanks and looking forward to working with you on this submission,

**Comment by kakiac** [comment]
👋  @akbaritabar @marcwilliams1 @martinmodrak @ejolly would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by kakiac** [comment]
👋  @marcjwilliams1 would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by akbaritabar** [comment]
@kakiac Thanks for reaching out. I will try and do my best for the review (with my limited knowledge, of course).

**Comment by marcjwilliams1** [comment]
@kakiac also happy help out for this review.

**Comment by ejolly** [comment]
@kakiac Unfortunately I don't think I'll be that helpful for this review, since it's be quite a while since I've worked natively with R (predominantly python these days). Happy to attempt it though if no other reviewers are available. @kakiac Is it also possible to edit my "Other Languages" on the joss review list to remove R and Matlab? Would be good so I'm not a time bottleneck on future submissions that require reviewers for those language.

**Comment by martinmodrak** [comment]
@kakiac Hi, the package looks interesting and I'd be glad to review it. Unfortunately, I am currently leaving for vacation until July 26th and will probably have a bunch of stuff on my plate after the return. So realistically, I might not have an initial review ready sooner than Aug 1st. If that's OK, I can review it. (I am also OK if you look for other reviewers who can react faster and fall back on me only if that fails).

**Comment by ysohn** [comment]
> Hi @ysohn, thanks for your submission to JOSS. It looks like there are a few issues that need to be resolved as we get started:
> 
> * Your software repository does not appear to include an open source license
> * Your paper is missing an explicit Statement of Need section, which is now required for articles as described in [our documentation](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)
> * Please remove these lines from your paper's YAML header: `aas-doi: 10.3847/xxxxx` and `aas-journal: Journal of Open Source Software.`
> * Also, overall your paper is quite short. Although JOSS papers are generally only one or two pages on average (250-1000 words), your paper just barely passes that mark. I would recommend adding a bit more content, perhaps an example or more explanation/details of how the package works.
> * It looks like a few of your references may be missing DOIs
> 
> Thanks!

Hello @kyleniemeyer, thank you very much for the comments. We made updates based on the list and committed to the master.

**Comment by ysohn** [comment]
> @kakiac Thanks for reaching out. I will try and do my best for the review (with my limited knowledge, of course).

@kakiac Thank you very much for your time. We made an update to the package based on the editor's comments.

**Comment by ysohn** [comment]
> 👋 @ysohn thanks for your submission to JOSS! 🥳
> 
> I think I would like us to work on @kyleniemeyer 's comments above: [#2471 (comment)](https://github.com/openjournals/joss-reviews/issues/2471#issuecomment-656894068) before I pass this on to reviewers to review, as it will substantially improve the submission. Will you be able to address them?
> 
> Maybe you can include elements from this page: https://cran.r-project.org/web/packages/NetworkChange/vignettes/NetworkChange.html
> 
> See for example this paper for an example of what a JOSS paper looks like: https://joss.theoj.org/papers/10.21105/joss.02265
> 
> Many thanks and looking forward to working with you on this submission,

@kakiac We made updates. Thank you very much!

**Comment by ysohn** [comment]
@kakiac Dear editor, I'd appreciate if you could let me know if there is anything we need to do in the pre-review stage. Thank you!

**Comment by arfon** [comment]
@ysohn - I've just emailed @kakiac to ask her to check in with this submission.

**Comment by ysohn** [comment]
@arfon Thank you very much!

**Comment by kakiac** [comment]
Thanks everyone for your help and work with the submission so far - my apologies for the delay in moving this submission forward!

@ysohn thanks for the changes to the submission, you have greatly improved the paper 👍 

@akbaritabar @marcjwilliams1 @ejolly @martinmodrak thanks all for your expressions of interest. I am aware it has been a bit of time since I asked you of your availability to review, but I have added @akbaritabar @marcjwilliams1 and @martinmodrak as reviewers for this submission. Please let me know if you are no longer available to review :)

(@arfon, as always, many thanks for your support!)

**Comment by kakiac** [comment]
@whedon generate pdf

**Comment by kakiac** [comment]
@whedon assign @akbaritabar as reviewer

**Comment by whedon** [comment]
OK, @akbaritabar is now a reviewer

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02471/joss.02471/10.21105.joss.02471.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02471/joss.02471/10.21105.joss.02471.pdf) :page_facing_up: :point_left:

**Comment by kakiac** [comment]
@whedon add @marcjwilliams1 as reviewer

**Comment by whedon** [comment]
OK, @marcjwilliams1 is now a reviewer

**Comment by kakiac** [comment]
@whedon add @martinmodrak as reviewer

**Comment by whedon** [comment]
OK, @martinmodrak is now a reviewer

**Comment by kakiac** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2708.

**Comment by kakiac** [comment]
@ejolly re this https://github.com/openjournals/joss-reviews/issues/2471#issuecomment-658327413 I have requested a change in the spreadsheet, so hopefully you will not be getting more requests on R!

**Comment by ejolly** [comment]
Thanks @kakiac !
