### ISSUE TITLE
[PRE REVIEW]: GENRE (GPU Elastic-Net REgression): A CUDA-Accelerated Package for Massively Parallel Linear Regression with Elastic-Net Regularization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2475]
**Submitting author:** @Christopher-Khan (<a href="http://orcid.org/0000-0003-3201-3423">Christopher Khan</a>)
**Repository:** <a href="https://github.com/VU-BEAM-Lab/GENRE" target ="_blank">https://github.com/VU-BEAM-Lab/GENRE</a>
**Version:** v1.0
**Editor:** @sjpfenninger
**Reviewers:** @marouenbg, @krystophny
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Christopher-Khan. **Currently, there isn't an JOSS editor assigned** to your paper.

@Christopher-Khan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (115.2 files/s, 34526.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CUDA                             4            499            546           1080
Markdown                         2             77              0            264
MATLAB                           3             87            153            185
TeX                              1             10              0             96
-------------------------------------------------------------------------------
SUM:                            10            673            699           1625
-------------------------------------------------------------------------------


Statistical information for the repository '2475' was gathered on 2020/07/12.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/j.1467-9868.2005.00503.x is OK
- 10.18637/jss.v033.i01 is OK
- 10.1109/tuffc.2014.2928 is OK
- 10.1109/tuffc.2015.007004 is OK
- 10.1109/tuffc.2017.2729944 is OK
- 10.1186/1753-6561-6-s2-s10 is OK
- 10.3389/fgene.2013.00270 is OK
- 10.1016/j.neuroimage.2008.08.020 is OK
- 10.1109/isbi.2014.6868131 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02475/joss.02475/10.21105.joss.02475.pdf)

**Comment by arfon** [comment]
@whedon query scope

**Comment by Christopher-Khan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Christopher-Khan** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by Christopher-Khan** [comment]
Potential Reviewers: 
marouenbg 
Markbasham
casperdcl
mskwark
krystophny
Scivision
MikeLydeamore
billchenxi

**Comment by danielskatz** [comment]
@sjpfenninger - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @sjpfenninger as editor

**Comment by whedon** [comment]
@sjpfenninger has been invited to edit this submission.

**Comment by sjpfenninger** [comment]
@danielskatz Yes, I can edit this

**Comment by sjpfenninger** [comment]
@whedon assign @sjpfenninger as editor

**Comment by whedon** [comment]
OK, the editor is @sjpfenninger

**Comment by sjpfenninger** [comment]
@mlxd and @marouenbg would you be willing to review this submission for JOSS?

**Comment by mlxd** [comment]
@sjpfenninger Sorry, but I do not have access to a MATLAB license on a CUDA-capable machine, and so would be unable to properly review this.

**Comment by sjpfenninger** [comment]
@mlxd No worries and thanks for the rapid response

**Comment by sjpfenninger** [comment]
@whedon add @marouenbg as reviewer

**Comment by whedon** [comment]
OK, @marouenbg is now a reviewer

**Comment by sjpfenninger** [comment]
@whedon add @krystophny as reviewer

**Comment by whedon** [comment]
OK, @krystophny is now a reviewer

**Comment by sjpfenninger** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2644.

**Comment by sjpfenninger** [comment]
@marouenbg, @krystophny thanks for agreeing to review. Let's head over to #2644 for the actual review!
