### ISSUE TITLE
[PRE REVIEW]: Disimpy: A massively parallel Monte Carlo simulator for synthesizing diffusion-weighted MRI data in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2476]
**Submitting author:** @kerkelae (<a href="http://orcid.org/0000-0001-9446-4305">Leevi Kerkelä</a>)
**Repository:** <a href="https://github.com/kerkelae/disimpy" target ="_blank">https://github.com/kerkelae/disimpy</a>
**Version:** v0.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @DARSakthi, @grlee77, @ritagnunes
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kerkelae. **Currently, there isn't an JOSS editor assigned** to your paper.

@kerkelae if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (241.8 files/s, 38262.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          13            303            429           1805
TeX                              1             15              0            137
Markdown                         1             23              0            129
reStructuredText                 5             46             27            105
Jupyter Notebook                 1              0            464            100
DOS Batch                        1              8              1             26
make                             1              5              7              9
-------------------------------------------------------------------------------
SUM:                            23            400            928           2311
-------------------------------------------------------------------------------


Statistical information for the repository '2476' was gathered on 2020/07/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
kerkelae                        13          2720            183          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
kerkelae                   2537           93.3          0.0                6.90
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/978-3-642-15745-5_50 may be missing for title: High-fidelity meshes from tissue samples for diffusion MRI simulations
- https://doi.org/10.1016/j.jmr.2012.10.015 may be missing for title: Isotropic diffusion weighting in PGSE NMR by magic-angle spinning of the q-vector
- https://doi.org/10.1063/1.1695690 may be missing for title: Spin diffusion measurements: spin echoes in the presence of a time-dependent field gradient
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation
- https://doi.org/10.1109/tmi.2009.2015756 may be missing for title: Convergence and parameter choice for Monte-Carlo simulations of diffusion MRI
- https://doi.org/10.1016/j.neuroimage.2007.02.016 may be missing for title: Robust determination of the fibre orientation distribution in diffusion MRI: non-negativity constrained super-resolved spherical deconvolution
- https://doi.org/10.1002/nbm.3998 may be missing for title: Quantifying brain microstructure with diffusion MRI: Theory and parameter estimation
- https://doi.org/10.1101/140459 may be missing for title: The role of diffusion MRI in neuroscience
- https://doi.org/10.1109/hotchips.2008.7476516 may be missing for title: Scalable parallel programming with CUDA

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02476/joss.02476/10.21105.joss.02476.pdf)

**Comment by arfon** [comment]
@whedon query scope

**Comment by kerkelae** [comment]
The following reviewers, for example, may be suitable for this submission: arokem mstimberg RainierBarrett Fipanther hanayik

**Comment by kerkelae** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by DARSakthi** [comment]
Hi, this paper seems pretty interesting, I'd be happy to review it if needed. Let me know. Cheers

**Comment by Kevin-Mattheus-Moerman** [comment]
@kerkelae can you work on those missing DOI's? You can call `@whedon generate pdf` to regenerate the paper and use `@whedon check references` to see if the DOI's are fixed.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @DARSakthi as reviewer

**Comment by whedon** [comment]
OK, @DARSakthi is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@mathieuboudreau, @grlee77, would you be interested in reviewing this work? You appear to have become my go-to-reviewers for MRI related stuff. Please do let me know if you feel I'm inviting you too often. 

@ritagnunes @mfroeling this work may also interest you. Would you be able to help with this review too? 

Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@mstimberg @hanayik would you be interested in reviewing this work for JOSS? 
The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and will focus on the [short paper](https://github.com/openjournals/joss-papers/blob/joss.02476/joss.02476/10.21105.joss.02476.pdf) and [the software](https://github.com/kerkelae/disimpy). 

This is a pre-review issue where editors/reviewers are assigned. If you are interested in helping with this review you can reply here. I'll trigger a dedicated review issue once sufficient reviewers have been found. 

Thanks.

**Comment by mathieuboudreau** [comment]
What's the typical turnaround time you expect from reviewers? I'd be interested in reviewing, however my next three weeks or so are pretty packed because of the annual ISMRM (MRI) conference, and I am also already a reviewer for another JOSS submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mathieuboudreau thanks for getting back to me. I understand. We typically aim for 2 weeks but with all the COVID mayhem we've slowed down quite a bit. I hope to find 3 reviewers. I'll keep you on standby if that is okay and will add you if I cannot find sufficient reviewers. If so we will of course be patient to accommodate your time schedule.

**Comment by grlee77** [comment]
I am interested, but would not be able to start my review until Aug. 5th.

**Comment by Kevin-Mattheus-Moerman** [comment]
@grlee77 that is fine. Thanks again for your help!!! :clap:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @grlee77 as reviewer

**Comment by whedon** [comment]
OK, @grlee77 is now a reviewer

**Comment by ritagnunes** [comment]
Hi Kevin,

my schedule is also tight in the next few weeks with ISMRM, but as long as
it is not urgent, I am happy to review it too.

Thanks
Rita

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @ritagnunes as reviewer

**Comment by whedon** [comment]
OK, @ritagnunes is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2527.
