### ISSUE TITLE
[REVIEW]: pyhector: A Python interface for the simple climate model Hector

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#248]
**Submitting author:** @swillner (<a href="http://orcid.org/0000-0001-6798-6247">Sven N. Willner</a>)
**Repository:** <a href="https://github.com/openclimatedata/pyhector/" target ="_blank">https://github.com/openclimatedata/pyhector/</a>
**Version:** v0.7.0
**Editor:** @arfon
**Reviewer:** @sgrieve
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.569492" target="_blank">10.5281/zenodo.569492</a>

## Status

[![status](http://joss.theoj.org/papers/684175c9ecc01d88a5bb0e1d3d2619c4/status.svg)](http://joss.theoj.org/papers/684175c9ecc01d88a5bb0e1d3d2619c4)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/684175c9ecc01d88a5bb0e1d3d2619c4"><img src="http://joss.theoj.org/papers/684175c9ecc01d88a5bb0e1d3d2619c4/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/684175c9ecc01d88a5bb0e1d3d2619c4/status.svg)](http://joss.theoj.org/papers/684175c9ecc01d88a5bb0e1d3d2619c4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/openclimatedata/pyhector/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/openclimatedata/pyhector/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.7.0)?
- [x] **Authorship:** Has the submitting author (@swillner) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @sgrieve it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by sgrieve** [comment]
I have updated the version number in the review comment, as it didn't copy across from the pre-review. I'm hoping to have time to work on this review tomorrow. I will post any questions I have here, and if I find any bugs I will open issues on the source repo.

**Comment by sgrieve** [comment]
I have been working on this today and overall I am very happy with the quality of the code and documentation. I'd like to thank the authors for this contribution, its been a very enjoyable day working through this submission (much better than marking exams!).

I have checked all of the items on the checklist and so the minor issues I raise below are not severe, but are more suggestions that I think may improve the paper and the code.

* In the readme, the usage guide is placed before the installation information. It might flow better to have the install guide before the usage section.
* When running the example code and some of the code from the jupyter workbook, I had problems because of the use of the unicode degree symbol in the plot y axis labels. I was able to fix this easily, but being thrown an error message right off the bat may discourage some users, so it might be a good idea to avoid using the degree symbol to eliminate that possible barrier to entry.
* I would suggest adding ``plt.show()`` to the last line of the complex example in the readme, if someone runs the code in a non-interactive session no plot will display otherwise.
* When reading the API, it states:

> List of requested output variables as strings. if set to “all” returns all available variables. Defaults to global temperature, CO2 concentration and forcing. A full list is in variables

But I cannot find this full list. I was able to generate it easily from the code to play around with the model, but it would be useful to have this list reproduced somewhere in the documentation.

* In a similar vein, the descriptions in the API for ``pyhector.constants`` through to ``pyhector.units`` are quite sparse. I think it would help a prospective user to see some examples here, if not the full range of value for each of these variables.

* I just want to check about the authorship of the paper, there are 3 authors, yet only 2 have been involved in the development of pyhector based on the commit history of the repo. Have all authors contributed to this submission?

* In the paper, it would be better to cite pandas rather than using a footnote. Information on citing it can be found here: https://www.scipy.org/citing.html#pandas

Once these comments have been addressed I will be delighted to accept this paper.

**Comment by rgieseke** [comment]
Many thanks for the detailed review! Answers to the suggested changes below:

> In the readme, the usage guide is placed before the installation information. It might flow better to have the install guide before the usage section.

Good idea, done.

>    When running the example code and some of the code from the jupyter workbook, I had problems because of the use of the unicode degree symbol in the plot y axis labels. I was able to fix this easily, but being thrown an error message right off the bat may discourage some users, so it might be a good idea to avoid using the degree symbol to eliminate that possible barrier to entry.

A colleague reported just that when testing, so this might be very useful change. Not sure whether there is a nice Python2/3 workaround so going with a plain text unit.

> I would suggest adding plt.show() to the last line of the complex example in the readme, if someone runs the code in a non-interactive session no plot will display otherwise.

Good catch, spoiled by mostly plotting from Notebooks these days!

> List of requested output variables as strings. if set to “all” returns all available variables. Defaults to global temperature, CO2 concentration and forcing. A full list is in variables
> But I cannot find this full list. I was able to generate it easily from the code to play around with the model, but it would be useful to have this list reproduced somewhere in the documentation.
> In a similar vein, the descriptions in the API for pyhector.constants through to pyhector.units are quite sparse. I think it would help a prospective user to see some examples here, if not the full range of value for each of these variables.

Very good point, the configuration dictionaries in the sub-modules have now more detailed documentation in the API-docs section. They are auto-generated so they should stay up-to-date when Hector variables change.

> I just want to check about the authorship of the paper, there are 3 authors, yet only 2 have been involved in the development of pyhector based on the commit history of the repo. Have all authors contributed to this submission?

@cahartin contributed as a Hector developer with explaining and adapting Hector and by ensuring that Hector and Pyhector produce identical results. The Pyhector software requires the hector-wrapper and slightly modified Hector mentioned in the Readme. We therefore think we should archive the PyPI release which includes everything required to build Pyhector.

> In the paper, it would be better to cite pandas rather than using a footnote. Information on citing it can be found here: https://www.scipy.org/citing.html#pandas

Done!

**Comment by swillner** [comment]
@sgrieve Thank you very much! We have tagged the revised version "v0.7.0". Could you update that again,  please? ;)

**Comment by sgrieve** [comment]
Great. I've updated the version number and I'm happy that my suggestions have all been addressed. So I am happy to accept the paper :rocket:

I think the next step is for you to generate a doi for the package using zenodo or figshare.

@arfon Is there anything else I need to do?

**Comment by swillner** [comment]
Cool! We have uploaded the pypi-archive (since pyhector is a multi-repo software) to zenodo:
https://doi.org/10.5281/zenodo.569492

@whedon set 10.5281/zenodo.569492 as archive

**Comment by swillner** [comment]
@whedon set 10.5281/zenodo.569492 as archive

**Comment by whedon** [comment]
I'm sorry @swillner, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.569492 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.569492" target="_blank">10.5281/zenodo.569492</a> is the archive.

**Comment by arfon** [comment]
> @arfon Is there anything else I need to do?

@sgrieve - many thanks. I'll move ahead with processing this shortly.

**Comment by arfon** [comment]
@sgrieve many thanks for your review here ✨ 

@swillner - your paper is now accepted into JOSS. The DOI is http://dx.doi.org/10.21105/joss.00248 :zap: 🚀 💥
