### ISSUE TITLE
[REVIEW]: pyBEMT: An implementation of the Blade Element Momentum Theory in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2480]
**Submitting author:** @kegiljarhus (<a href="http://orcid.org/0000-0002-4144-0454">Knut Erik Teigen Giljarhus</a>)
**Repository:** <a href="https://github.com/kegiljarhus/pyBEMT" target ="_blank">https://github.com/kegiljarhus/pyBEMT</a>
**Version:** v1.0
**Editor:** @sjpfenninger
**Reviewer:** @rafmudaf, @antviro
**Archive:** <a href="https://doi.org/10.5281/zenodo.4016951" target="_blank">10.5281/zenodo.4016951</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c4265723b2dc3b8e5e403a15c10948e9/status.svg)](https://joss.theoj.org/papers/c4265723b2dc3b8e5e403a15c10948e9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c4265723b2dc3b8e5e403a15c10948e9"><img src="https://joss.theoj.org/papers/c4265723b2dc3b8e5e403a15c10948e9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c4265723b2dc3b8e5e403a15c10948e9/status.svg)](https://joss.theoj.org/papers/c4265723b2dc3b8e5e403a15c10948e9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kegiljarhus/pyBEMT" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rafmudaf & @antviro, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @sjpfenninger know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kegiljarhus/pyBEMT">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@kegiljarhus) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kegiljarhus/pyBEMT">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@kegiljarhus) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rafmudaf, @antviro it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2514/6.2013-4220 is OK
- 10.2172/15014831 is OK
- 10.2172/5428795 is OK
- 10.1139/juvs-2017-0005 is OK
- 10.1016/j.renene.2020.04.005 is OK
- 10.1016/j.renene.2006.01.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02480/joss.02480/10.21105.joss.02480.pdf)

**Comment by sjpfenninger** [comment]
@kegiljarhus just to remind you that some minor rewording of the paper is still waiting to happen as per your response in the pre-review issue:

> Thank you for the elaboration, I see what you mean. The key aspect is the combination of both propellers and turbines in one package, which is nice especially for educational purposes. With respect to propellers, it is also the only package I am aware of with a model for coaxial rotors. I will reword the paper to emphasize these points.

**Comment by kegiljarhus** [comment]
> @kegiljarhus just to remind you that some minor rewording of the paper is still waiting to happen as per your response in the pre-review issue:

Dear @sjpfenninger . I apologize for the delay, I have been away on summer holiday. I did in fact make two commits with slight rewording just after your comment in the pre-review, they are included in the current article proof here. Please let me know if I should further clarify the statement of need before proceeding with the review.

**Comment by sjpfenninger** [comment]
Thanks @kegiljarhus, let's wait for the reviews to come in. @antviro @rafmudaf Are you able to complete your reviews within the next 1-2 weeks so we can move this forward? Thanks!

**Comment by antviro** [comment]
Yes I will try to finish mine during the next week. Sorry for the delay!

**Comment by antviro** [comment]
I have already my review report:
- I think it is a good idea to publish a BEM code in Python, despite there are already some free software which include such method (like the ones cited in the paper). A python BEM package allows its use in teaching and thesis which is interesting, moreover, this package also allows propellers to be simulated.
- Regarding its use in Wind Power, I think it would be interesting to add in the INI files some pitch variable to the case section ([case]) which would be summed afterwards to every pitch value (usually called twist) under the section [turbine]. So it would make easier its use to assess typical WT control.
- As API documentation states, airfoils are read by using AeroDYN/OpenFast type of file. Perhaps, it is interesting to mention in the paper (like airfoil file from XX is used as input) Anyway, I think the documentation could improve by including something about selecting another airfoil it in the "usage documentation", as well as by including some example of how to use another airfoil. Regarding the later, it would be nice that a local airfoil file can be used (like with ini files), for at the moment it seems users should include the airfoil file in a particular directory (in my case /usr/local/lib/python3.7/dist-packages/pybemt-0.1.0-py3.7.egg/pybemt/airfoils/ ) to use it.

**Comment by rafmudaf** [comment]
> Thanks @kegiljarhus, let's wait for the reviews to come in. @antviro @rafmudaf Are you able to complete your reviews within the next 1-2 weeks so we can move this forward? Thanks!

Sorry for the hold up. I'm going through the review now and will continue to work on it through the week.

**Comment by kegiljarhus** [comment]
Thank you for the nice comments and constructive suggestions, @antviro. I have the following replies:

- Adding a global adjustment to the pitch is an excellent suggestion. This has been implemented in commit kegiljarhus/pyBEMT@c905ee45db6fc89dcb8a4f0ea6b9e41b6a2521e6. It may be confusing to mix pitch and twist in these definitions, so other suggestions for names are appreciated.
- I have added a description on how to add airfoils in commit kegiljarhus/pyBEMT@75106b395fd16e2b369a6deddc1e191f5b4c32bd . I want to keep the configuration and installation simple so I decided not to have a separate path for airfoils.

**Comment by sjpfenninger** [comment]
Thanks @antviro for completing your review, can you confirm here if you are happy with the changes @kegiljarhus made in response to your comments?

**Comment by sjpfenninger** [comment]
Thanks @rafmudaf for keeping this moving. Can you confirm here once you are done with your review?

**Comment by rafmudaf** [comment]
My comments to the repository have been addressed, and I've finished reviewing. This tool is a great addition to the existing suite of simulation software for turbine and propeller aerodynamics. I recommend to publish.

**Comment by antviro** [comment]
My comments are also addressed. And as I mentioned before I think the project is quite interesting, so I also recommend to publish.

**Comment by antviro** [comment]
> * Adding a global adjustment to the pitch is an excellent suggestion. This has been implemented in commit [kegiljarhus/pyBEMT@c905ee4](https://github.com/kegiljarhus/pyBEMT/commit/c905ee45db6fc89dcb8a4f0ea6b9e41b6a2521e6). It may be confusing to mix pitch and twist in these definitions, so other suggestions for names are appreciated.

It is hard to suggest as the names are going to be used in different machines (propeller and turbines), I would write in the opposite way pitch for the global one, and twist for the one linked to each blade element (as it is usually called in wind power). However, I also consider it good as it is right now, as the explanation is clear enough, so that the user knows what is setting when changing any of the variables.

**Comment by sjpfenninger** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02480/joss.02480/10.21105.joss.02480.pdf)

**Comment by sjpfenninger** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2514/6.2013-4220 is OK
- 10.2172/15014831 is OK
- 10.2172/5428795 is OK
- 10.1139/juvs-2017-0005 is OK
- 10.1016/j.renene.2020.04.005 is OK
- 10.1016/j.renene.2006.01.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by sjpfenninger** [comment]
@kegiljarhus Almost ready for acceptance! Can you check [my PR](https://github.com/kegiljarhus/pyBEMT/pull/2) for some minor fixing up of the paper. I notice that you do not provide a PyPI package. It might make sense to do so to make installation easier, but that's not mandatory.

After addressing the above, to proceed to acceptance, can you make a tagged release on GitHub and archive that on a repository such as  Zenodo or figshare, then report the version number and archive DOI here?

**Comment by kegiljarhus** [comment]
Thank you, @sjpfenninger! I have merged your PR and tagged a v1.0 release.

Here is the Zenodo DOI: [10.5281/zenodo.4016951](https://zenodo.org/record/4016951)

**Comment by sjpfenninger** [comment]
@whedon set 10.5281/zenodo.4016951 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4016951" target="_blank">10.5281/zenodo.4016951</a> is the archive.

**Comment by sjpfenninger** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by sjpfenninger** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2514/6.2013-4220 is OK
- 10.2172/15014831 is OK
- 10.2172/5428795 is OK
- 10.1139/juvs-2017-0005 is OK
- 10.1016/j.renene.2020.04.005 is OK
- 10.1016/j.renene.2006.01.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1714

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1714, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by sjpfenninger** [comment]
@kegiljarhus Almost there! @rafmudaf @antviro Many thanks for your reviews!

**Comment by danielskatz** [comment]
👋 @kegiljarhus - this looks almost ready to accept, which I am working on.  I see some reference issues that need to be fixed first, mostly by protecting cases with {}s:
 - Glauert has "Aerodynamic theory" which should be "Aerodynamic Theory" I think
 - in Gohard, should the "tr" in the middle of the tech report number be "TR"?
 - Hericzek et al. has "uav" in the title which I think should be UAV
 - Marten et al. - can you spell out IJETAE?
 - Silvestre et al. - please fix the cases on the conference title to be Title Case

**Comment by kegiljarhus** [comment]
:wave: @danielskatz, thank you for the suggestions, they are implemented now in the latest commit.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02480/joss.02480/10.21105.joss.02480.pdf)

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2514/6.2013-4220 is OK
- 10.2172/15014831 is OK
- 10.2172/5428795 is OK
- 10.1139/juvs-2017-0005 is OK
- 10.1016/j.renene.2020.04.005 is OK
- 10.1016/j.renene.2006.01.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1715

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1715, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1303034232739180546) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1716
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02480](https://doi.org/10.21105/joss.02480)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Thanks to @rafmudaf & @antviro for reviewing and @sjpfenninger for editing!

And congratulations to @kegiljarhus (Knut Erik Teigen Giljarhus)!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02480/status.svg)](https://doi.org/10.21105/joss.02480)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02480">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02480/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02480/status.svg
   :target: https://doi.org/10.21105/joss.02480
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02480/status.svg)](https://doi.org/10.21105/joss.02480)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
