### ISSUE TITLE
[REVIEW]: PyMatting: A Python Library for Alpha Matting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2481]
**Submitting author:** @99991 (<a href="http://orcid.org/0000-0003-1355-7724">Thomas Germer</a>)
**Repository:** <a href="https://github.com/pymatting/pymatting" target ="_blank">https://github.com/pymatting/pymatting</a>
**Version:** v1.0.7
**Editor:** @gkthiruvathukal
**Reviewer:** @ziatdinovmax, @macrocosme
**Archive:** <a href="https://doi.org/10.5281/zenodo.4081416" target="_blank">10.5281/zenodo.4081416</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9766cab65bfbf07a70c8a835edd3875a/status.svg)](https://joss.theoj.org/papers/9766cab65bfbf07a70c8a835edd3875a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9766cab65bfbf07a70c8a835edd3875a"><img src="https://joss.theoj.org/papers/9766cab65bfbf07a70c8a835edd3875a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9766cab65bfbf07a70c8a835edd3875a/status.svg)](https://joss.theoj.org/papers/9766cab65bfbf07a70c8a835edd3875a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pymatting/pymatting" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ziatdinovmax & @macrocosme, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @gkthiruvathukal know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pymatting/pymatting">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@99991) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pymatting/pymatting">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@99991) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ziatdinovmax, @macrocosme it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2481 with the following error: 

 Can't find any papers to compile :-(

**Comment by 99991** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02481/joss.02481/10.21105.joss.02481.pdf)

**Comment by macrocosme** [comment]
@99991 @gkthiruvathukal First of all, I would like to congratulate the authors on their clean and useful software. The code is well documented, includes tests, and benchmarks. The code was easily installable, and examples ran as expected (except for a few path issues that have now been fixed). Instructions on how to set and run the benchmarks have also been simple to follow and worked as expected. I have a few minor comments regarding the submission. 

* Many Figures do not include axes labels. Labels are required for all Figures, even when described in the Figure caption. 
* There is no hardware and OS description available describing how the benchmarks' results were obtained, which may be suitable.

Regarding  the [community guidelines criteria](https://joss.readthedocs.io/en/latest/review_checklist.html#documentation): 
* there are clear guidelines for third parties wishing to **contribute to the software**. I think it would be useful to add a mention in the README directing to the CONTRIBUTING.md file;
* Unless I missed it, there are no clear guidelines about how to **report issues or problems with the software**;
* Unless I missed it, there are no clear guidelines about how to **seek support**. However, I must note that there is the "chat on gitter" badge where it is clearly possible to do so. 

I would like to ask the authors to apply these changes, after which I will accept this submission.

**Comment by gkthiruvathukal** [comment]
@macrocosme Thank you for your quick turnaround and helpful comments for @99991.

I will await feedback from @ziatdinovmax, who may need a bit more time.

**Comment by tuelwer** [comment]
Thanks for the fast review and the helpful comments, @macrocosme! We really appreciate this.

Regarding your minor comments:

- We added axes labels for Figure 2 and Figure 3 in commit https://github.com/pymatting/pymatting/commit/845e5e82094ef99e65777abc0040969b3271ab36.
- Furthermore, we added hardware and OS description at the end of the performance comparison section in commit https://github.com/pymatting/pymatting/commit/c61f6a2b81e42478d393b16018539fa2ecff41c3.
- We updated the content of the [CONTRIBUTING.md](https://github.com/pymatting/pymatting/blob/master/CONTRIBUTING.md) file. Now we have guidelines for reporting bugs and requesting support. We also added issue templates to our repository.

**Comment by tuelwer** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02481/joss.02481/10.21105.joss.02481.pdf)

**Comment by ziatdinovmax** [comment]
My apologies for the delay in responding... Congrats to the authors on their very nice library! It installs and runs smoothly, and the documentation is in good order. The only minor comment that I have is about the paper. When I was reading it, I kept wondering (perhaps out of my ignorance) who is the target audience and what specific applications it can be used for. The statement at the beginning of the paper that it is “important for many image editing tasks” seems to be a bit vague.  Perhaps listing several potential applications e.g. in the field of scientific and/or medical imaging together with references will be helpful.

**Comment by gkthiruvathukal** [comment]
@99991, thanks for the excellent follow up. I think adding these applications would be helpful.

@ziatdinovmax, does @99991's follow up address your concern about audience?

**Comment by ziatdinovmax** [comment]
@gkthiruvathukal  Yes, it does.

**Comment by gkthiruvathukal** [comment]
@ziatdinovmax Thanks! 

@99991 Please go ahead and make the revisions you proposed for including proper references.  Then I think we can move toward acceptance. (I will post a final checklist of things we need to do, once your article is updated.)

**Comment by tuelwer** [comment]
@ziatdinovmax @gkthiruvathukal thank you for your fast responses! We added the references to the paper and included the statement about the target audience in the first section of the paper.

We also made some further changes to the first section and the formatting of the references.

**Comment by tuelwer** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02481/joss.02481/10.21105.joss.02481.pdf)

**Comment by gkthiruvathukal** [comment]
@99991 and @tuelwer It seems like we're moving closer. If you're done, and our reviewers @ziatdinovmax and @macrocosme are satisfied, I can post the final checklist.

**Comment by 99991** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by 99991** [comment]
@gkthiruvathukal We are ready. :+1:

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02481/joss.02481/10.21105.joss.02481.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02481/joss.02481/10.21105.joss.02481.pdf) :page_facing_up: :point_left:

**Comment by tuelwer** [comment]
@gkthiruvathukal Is there anything we can do at the moment?

**Comment by danielskatz** [comment]
👋 @gkthiruvathukal - it looks like this is ready for you to "@whedon accept" and then pass on?

**Comment by gkthiruvathukal** [comment]
@danielskatz Thanks for the gentle nudge!

@99991 I'm ready to move forward with acceptance. There are a few final checks:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

**Comment by tuelwer** [comment]
@gkthiruvathukal We created a [tagged release](https://github.com/pymatting/pymatting/releases/tag/v1.0.7) of our package. The version number is 1.0.7 and the Zenodo DOI is [`10.5281/zenodo.4081416`](https://zenodo.org/record/4081416).

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by gkthiruvathukal** [comment]
@whedon set v1.0.7 as version

**Comment by whedon** [comment]
OK. v1.0.7 is the version.

**Comment by gkthiruvathukal** [comment]
@whedon set 10.5281/zenodo.4081416 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4081416" target="_blank">10.5281/zenodo.4081416</a> is the archive.

**Comment by gkthiruvathukal** [comment]
@openjournals/joss-eics  Ok, we're all set to move forward with accepting this JOSS submission.

**Comment by danielskatz** [comment]
@gkthiruvathukal - the next step is for you to do a ```@whedon accept``` and make sure everything looks good, then tell @openjournals/joss-eics

**Comment by gkthiruvathukal** [comment]
Thanks, @danielskatz. I think we're ready to go here!  I am still classically conditioned to my "early days" of JOSS where I wasn't doing the whedon accept.

**Comment by gkthiruvathukal** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2481 with the following error: 

 Can't find any papers to compile :-(

**Comment by tuelwer** [comment]
@gkthiruvathukal I think you have to add `from branch joss-submission`. 👍

**Comment by gkthiruvathukal** [comment]
Thank you, @tuelwer!
The problem is that was triggered by the whedon accept. I'm pretty sure your paper is building fine but can do it again.

**Comment by gkthiruvathukal** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02481/joss.02481/10.21105.joss.02481.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02481/joss.02481/10.21105.joss.02481.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon accept from branch joss-submission

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TIP.2018.2885495 is OK
- 10.1007/978-3-642-15705-9_26 is OK
- 10.1109/WACV.2011.5711528 is OK
- 10.1109/TPAMI.2013.18 is OK
- 10.1016/j.parco.2011.09.001 is OK
- 10.1109/TPAMI.2007.1177 is OK
- 10.1109/ICCV.2009.5459326 is OK
- 10.2172/751785 is OK
- 10.1145/992200.992206 is OK
- 10.1134/S1995080219050056 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1109/CVPR.2010.5539896 is OK
- 10.1109/CVPR.2009.5206503 is OK
- 10.1016/0021-9991(78)90098-0 is OK
- 10.1201/9781351069397-24 is OK
- 10.1109/CVPR.2011.5995665 is OK
- 10.1145/200979.200981 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
Looks good to me

**Comment by danielskatz** [comment]
@whedon accept deposit=true from branch joss-submission

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1316064197223088129) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1808
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02481](https://doi.org/10.21105/joss.02481)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to  @99991 (Thomas Germer), @tuelwer & co-authors!!

Thanks for editing @gkthiruvathukal and for reviewing to @ziatdinovmax & @macrocosme!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02481/status.svg)](https://doi.org/10.21105/joss.02481)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02481">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02481/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02481/status.svg
   :target: https://doi.org/10.21105/joss.02481
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02481/status.svg)](https://doi.org/10.21105/joss.02481)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by 99991** [comment]
Thank you all for making this possible! :tada:
