### ISSUE TITLE
[REVIEW]: memr: An R package for medical free-text records embedding and visualization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2482]
**Submitting author:** @adamgdobrakowski (<a href="http://orcid.org/0000-0001-6460-3079">Adam Dobrakowski</a>)
**Repository:** <a href="https://github.com/MI2DataLab/memr" target ="_blank">https://github.com/MI2DataLab/memr</a>
**Version:** v0.1.0
**Editor:** @karthik
**Reviewer:** @cmaimone, @timchurches
**Archive:** Pending

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6abc67f9eef76ffe33b0ab2c3b2d253b/status.svg)](https://joss.theoj.org/papers/6abc67f9eef76ffe33b0ab2c3b2d253b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6abc67f9eef76ffe33b0ab2c3b2d253b"><img src="https://joss.theoj.org/papers/6abc67f9eef76ffe33b0ab2c3b2d253b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6abc67f9eef76ffe33b0ab2c3b2d253b/status.svg)](https://joss.theoj.org/papers/6abc67f9eef76ffe33b0ab2c3b2d253b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MI2DataLab/memr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@cmaimone & @ @timchurches, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @karthik know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MI2DataLab/memr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@adamgdobrakowski) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MI2DataLab/memr">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@adamgdobrakowski) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cmaimone, @ @timchurches it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2482 with the following error: 

 pandoc-citeproc: reference timchurches not found
Error producing PDF.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\let \@xs@assign \@xs@expand@and@detokenize...
l.330 }

Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3115/v1/D14-1162 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by cmaimone** [comment]
@karthik the pdf for this submission looks like it failed to compile.  I'm not sure what the next step to address that is

**Comment by karthik** [comment]
Thanks for letting me know @cmaimone 
I fixed a few problems with the way they reference citations and sent in a pull-request. Once merged, Whedon will be able to generate PDFs again. In the meantime here's the paper I was able to compile locally with my fix. 

[nlr9oojjkffpxi0pif2v.pdf](https://github.com/openjournals/joss-reviews/files/4943009/nlr9oojjkffpxi0pif2v.pdf)

**Comment by cmaimone** [comment]
@karthik I'm not sure this submission meets the substantial scholarly effort criteria

> Age of software (is this a well-established software project) / length of commit history.
github history is just a few months

> Number of commits.
15

> Number of authors.
1

> Lines of code (LOC): These statistics are usually reported by Whedon in the pre-review issue thread.
919 lines of R code, under the recommended 1000

> Whether the software has already been cited in academic papers.
No evidence of this beyond the author's preprint https://arxiv.org/pdf/1907.04152.pdf

> Whether the software is sufficiently useful that it is likely to be cited by other researchers working in this domain.
The package does not appear to have sufficient documentation and examples to lead to widespread use that would bring about citations.  The package accompanies https://arxiv.org/pdf/1907.04152.pdf, but it does not go beyond serving as a record of the code and methods used for that paper.

**Comment by adamgdobrakowski** [comment]
@cmaimone Thank you for reviewing my package. I will try to solve all the opened issues. I would like also to answer to some of your doubts:

>  github history is just a few months
>  Number of commits.
>    15

The tools included in the package had been developing since 2018, but they were stored in a private repository due to medical data sensitivity and privacy. First experiments were performed on real medical data, and the package could be transformed into a public repository after a separation from the real data. Of course there are few commits because an initial commit was with a complete package.

>  Whether the software has already been cited in academic papers.
> No evidence of this beyond the author's preprint https://arxiv.org/pdf/1907.04152.pdf

My paper is accepted at the conference ISMIS 2020 https://ismis.ist.tugraz.at/accepted-papers/ and I will change the citation when it will be published.

> The package does not appear to have sufficient documentation and examples to lead to widespread use that would bring about citations.

I will develop a documentation and I could give more examples with a new bigger artificial dataset.

**Comment by timchurches** [comment]
I'm a bit confused as to what I am supposed to do at this point... I've looked at the 4 page manuscript, and I agree with @cmaimone that the project is insufficiently mature and insufficiently documented to warrant review as a software package at this stage. The manuscript as it stands is really more a research note, explaining how a known body of methods (word embedding etc) can be applied to a particular domain (medical free text), although it must e noted that there are dozens of such papers already. I suggest that the manuscript be rejected with an invitation to resubmit when the project is more mature and complete, or to submit elsewhere as a research note type of paper. I am presuming that the peer review process for JOSS is just that, a review process, rather than a mentoring process intended to help the manuscript author(s) develop their project to the point that it meets the criteria for JOSS consideration. If mentoring is intended, it might be done better through organisations such as rOpenSci, rather than via an extended manuscript peer review process.

**Comment by timchurches** [comment]
I should add that even as a research methodology or research note paper, the manuscript still needs a lot of work. Such a paper needs to assume the reader is unfamiliar with the methods used, and thus needs to explain, possibly in non-mathematical terms, what embedding is, how similarity between or clustering of embedding vectors can be used for tasks relevant to researchers working with free text records, what metrics might be used to evaluate this, and explanations that, for example, that tSNE is a way of visualising clusters in a reduce number of dimensions, and so on. The manuscript does none of those things at present. Nor does it give details of the software package or its design and architecture. Thus, unless JOSS reviews are intended to be a mentoring service, suggest rejection with fresh submission of a much expanded manuscript at a later date if the author wishes.

**Comment by timchurches** [comment]
Sorry, last post on this: I just read the paper referenced in the manuscript: https://arxiv.org/abs/1907.04152 That looks much more like the research note or research methodology type of paper I described above. If it has not been submitted elsewhere, that paper would be a much better basis for a submission to JOSS, if a section or two on the software package were added to it. But that needs to be a separate submission with the additional authors named in the pre-print, not a revision of the manuscript under consideration here.

**Comment by timchurches** [comment]
A final, more general point: I notice that the JOSS review questions does not include anything about ethics oversight. Obviously where a manuscript reports results from the software package in question which are obtained using data or information that needs to be under human research ethics committee (IRB) oversight, the details of the necessary clearances need to be provided in the manuscript. The preprint cited in the submitted manuscript describes the use of free text notes extracted from 100,000 patient records. In most jurisdictions, such use would require ethics review and approval, but none was mentioned. Just something to bear in mind when reviewing JOSS manuscripts that deal with software used for human and/or animal research, where examples of such research are being reported in the JOSS paper. I'm sure the authors of the preprint took all the required steps for ethical approval of their work in their jurisdiction, they just need to mention that in any paper submitted to JOSS for consideration.

**Comment by karthik** [comment]
@cmaimone and @timchurches , thank you for the review and your thoughts on the paper. I note both of you concurring that this is not substantive enough to count as a scholarly effort for JOSS and I also see the additional concerns raised by @timchurches

>  I suggest that the manuscript be rejected with an invitation to resubmit when the project is more mature and complete, or to submit elsewhere as a research note type of paper. 


> I am presuming that the peer review process for JOSS is just that, a review process, rather than a mentoring process intended to help the manuscript author(s) develop their project to the point that it meets the criteria for JOSS consideration. If mentoring is intended, it might be done better through organisations such as rOpenSci, rather than via an extended manuscript peer review process.

You presume correct. JOSS does not mentor papers into completion. Editors at rOpenSci will have to decide if this is a fit, but for JOSS we just make a decision based on what was submitted (with minor revisions).

>  I notice that the JOSS review questions do not include anything about ethics oversight. Obviously where a manuscript reports results from the software package in question which are obtained using data or information that needs to be under human research ethics committee(HREC aka IRB) oversight, the details of the necessary clearances need to be provided in the manuscript. 

Thank you. I'll raise this issue with the JOSS editorial board.


@arfon @kthyng Please see discussion above. My recommendation supports the view of the reviewers, that this be rejected from JOSS in the current form. The authors can submit a presubmission inquiry in the future to determine if the paper/software meets the criteria for acceptance to JOSS.

**Comment by kthyng** [comment]
@cmaimone and @timchurches, @karthik, @adamgdobrakowski: I will pause this submission as this is considered, thank you!

**Comment by karthik** [comment]
:wave: @adamgdobrakowski 

Thank you for submitting your software to JOSS. After considering the comments of the two reviewers and discussion with the EICs, I have decided to reject this submission in the current form. 

We are rejecting this submission because:

-  It currently does not meet our criteria for a substantial scholarly effort
- There isn't sufficient indication that your software is will be of interest to the broader research community
- There are unanswered questions about ethics oversight and missing IRB details.

If you are able to address these in a revision and demonstrate that it is a substantial scholarly effort, please submit a pre-submission inquiry and reference this review thread. We wish you the best.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
