### ISSUE TITLE
[PRE REVIEW]: sbi - a toolkit for simulation-based inference

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2486]
**Submitting author:** @janfb (<a href="http://orcid.org/0000-0003-4979-7092">Jan Boelts</a>)
**Repository:** <a href="https://github.com/mackelab/sbi" target ="_blank">https://github.com/mackelab/sbi</a>
**Version:** v0.10.0
**Editor:** @dfm
**Reviewers:** @EiffL, @cranmer
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @janfb. **Currently, there isn't an JOSS editor assigned** to your paper.

@janfb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2486 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (412.3 files/s, 63900.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          65           2061           2735           6544
Markdown                        10            162              0            465
Jupyter Notebook                 4              0           1124            150
YAML                             3             16             13            126
JSON                             2              0              0             98
JavaScript                       2             10              0             57
CSS                              1             11              7             47
SVG                              1              0              1             10
-------------------------------------------------------------------------------
SUM:                            88           2260           3880           7497
-------------------------------------------------------------------------------


Statistical information for the repository '2486' was gathered on 2020/07/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alvaro Tejero-Canter            96          7536           7451           12.48
Conor Durkan                     1         13290              0           11.07
David Greenberg                  1             2              2            0.00
Harry Fu Yu                      1            10              9            0.02
Jan                             12          1206           2821            3.35
Jan-Matthis                     12           993            867            1.55
Michael Deistler                81         11643           7351           15.82
dgreenberg                       1            13              9            0.02
jan-matthis                     21         15553          14266           24.84
janfb                           76          6820           5528           10.28
meteore                          8          8364          15833           20.15
michael                          6           306            192            0.41

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Conor Durkan                702            5.3          0.0                9.83
Harry Fu Yu                  10          100.0          0.2                0.00
Jan                          70            5.8          4.9                4.29
Jan-Matthis                2362          237.9          2.2                6.39
Michael Deistler           2939           25.2          2.0                8.51
janfb                      2669           39.1          1.7                8.73
meteore                    2458           29.4          2.0               13.75
michael                     197           64.4          0.2               10.66
```

**Comment by labarba** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02486/joss.02486/10.21105.joss.02486.pdf)

**Comment by labarba** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
@labarba: I'm happy to edit this submission!

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by janfb** [comment]
@dfm thanks for editing our submission!

**Comment by dfm** [comment]
@EiffL and @cranmer have kindly agreed to review this submission. I'll add them and we'll get the review started in a new thread. Thanks all!

**Comment by dfm** [comment]
@whedon assign @EiffL as reviewer

**Comment by whedon** [comment]
OK, @EiffL is now a reviewer

**Comment by dfm** [comment]
@whedon add @cranmer as reviewer

**Comment by whedon** [comment]
OK, @cranmer is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2505.
