### ISSUE TITLE
[PRE REVIEW]: PF: A C++ Library for Fast Particle Filtering

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2488]
**Submitting author:** @tbrown122387 (<a href="http://orcid.org/0000-0003-4972-6251">Taylor Brown</a>)
**Repository:** <a href="https://github.com/tbrown122387/pf" target ="_blank">https://github.com/tbrown122387/pf</a>
**Version:** v1.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tbrown122387. **Currently, there isn't an JOSS editor assigned** to your paper.

@tbrown122387 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.99 s (471.9 files/s, 79555.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           231           1497           1285          34160
C/C++ Header                    18           4526           3047          16726
TeX                             69           2241             65           8055
JavaScript                     130            134            114           3353
CSS                              4            331             80           1603
C++                              8            181            149            627
Markdown                         2            100              0            250
make                             2             93             56            157
CMake                            2              8              6             39
YAML                             2              1              1             19
-------------------------------------------------------------------------------
SUM:                           468           9112           4803          64989
-------------------------------------------------------------------------------


Statistical information for the repository '2488' was gathered on 2020/07/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Taylor                          95         45187          16285          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Taylor                    28902           64.0          5.1               11.46
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1080/10618600.2016.1172487 is OK
- 10.1007/978-1-4684-9393-1 is OK
- 10.1111/j.1467-9868.2009.00736.x is OK
- 10.1063/1.1699114 is OK
- 10.1111/1467-9868.00363 is OK
- 10.1214/aoms/1177699147 is OK
- 10.1109/5.18626 is OK
- 10.1049/ip-f-2.1993.0015 is OK
- 10.1109/TSP.2005.849185 is OK
- 10.3150/14-BEJ666 is OK
- 10.2139/ssrn.2386371 is OK

MISSING DOIs

- https://doi.org/10.1093/biomet/57.1.97 may be missing for title: Monte Carlo Sampling Methods Using Markov Chains and Their Applications
- https://doi.org/10.1109/9780470544334.ch9 may be missing for title: A New Approach to Linear Filtering and Prediction Problems
- https://doi.org/10.1080/01621459.1999.10474153 may be missing for title: Filtering via Simulation: Auxiliary Particle Filters

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02488/joss.02488/10.21105.joss.02488.pdf)

**Comment by labarba** [comment]
👋  @tbrown122387 — I'm going to send this back to you for some work, because the paper does not quite follow our expectations. Please read the section[What should my paper contain?](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) in our documentation. You should _start_ with a summary that is accessible for the non-specialist. This section is key for the Associate EiC on rotation (me, this week) to be able to identify the right handling editor. It's also helpful to readers!

The section on "Statement of Need" should explain to us why the world needs _this software_. Currently, you have text there about particle filters, but not about how the software fits in its context.

Moreover, this paper is _too long_ for JOSS (9 pages). Please go over the paper and remove material that belongs in the README or the software documentation.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tbrown122387 this is a friendly reminder that some points were raised :point_up: we'd like you to work on. Let us know if you have any questions.

**Comment by tbrown122387** [comment]
@labarba @Kevin-Mattheus-Moerman sorry for the delayed response, but yes, thank you very much for the timely and informative feedback. I plan on taking an axe to this puppy and making all of the required changes. I’m a little short on time at the moment, but y’all will hear from me shortly.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tbrown122387 thanks. I've paused this submission for now. We'll remove the paused label once we've heard back from you with those changes.

**Comment by danielskatz** [comment]
@tbrown122387  - I'm going to mark this as withdrawn, but please feel free to resubmit once you have made the changes discussed above.

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
