### ISSUE TITLE
[PRE REVIEW]: Kookaburra for radio-pulsar shapelet analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2489]
**Submitting author:** @GregoryAshton (<a href="http://orcid.org/0000-0001-7288-2231">Gregory Ashton</a>)
**Repository:** <a href="https://github.com/GregoryAshton/kookaburra" target ="_blank">https://github.com/GregoryAshton/kookaburra</a>
**Version:** 0.2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @GregoryAshton. **Currently, there isn't an JOSS editor assigned** to your paper.

@GregoryAshton if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (507.6 files/s, 55169.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          13            365            396           1090
TeX                              1             21              0            265
make                             1             29              6            181
Markdown                         4             42              0            177
reStructuredText                 5             62             51             81
YAML                             2              7              7             46
-------------------------------------------------------------------------------
SUM:                            26            526            460           1840
-------------------------------------------------------------------------------


Statistical information for the repository '2489' was gathered on 2020/07/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Gregory Ashton                  27          2477            626          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Gregory Ashton             1851           74.7          0.8               13.78
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.3847/1538-4365/ab06fc is OK
- 10.1046/j.1365-8711.2003.05901.x is OK
- 10.1093/mnras/stu2611 is OK
- 10.1093/mnras/stu1721 is OK
- 10.1093/mnras/stw3359 is OK
- 10.3847/0004-637X/820/1/64 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.1051/0004-6361/201322971 is OK
- 10.1038/217709a0 is OK
- 10.1038/218731a0 is OK
- 10.1038/216567a0 is OK

MISSING DOIs

- https://doi.org/10.1093/biomet/82.4.711 may be missing for title: Reversible jump Markov chain Monte Carlo computation and Bayesian model determination
- https://doi.org/10.1109/tit.2004.834752 may be missing for title: Information theory, inference and learning algorithms
- https://doi.org/10.1198/106186006x136976 may be missing for title: Validation of software for bayesian models using posterior quantiles
- https://doi.org/10.1109/mcse.2007.55 may be missing for title: Matplotlib: A 2D graphics environment

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02489/joss.02489/10.21105.joss.02489.pdf)

**Comment by labarba** [comment]
👋  @GregoryAshton — I'm going to send this back for a bit of work on the paper. Currently, it does not follow our guidance in providing a clear _Statement of Need_. See the section [What should my paper contain?](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) in our documentation. Tell us why the research world needs your software!

**Comment by labarba** [comment]
@whedon query scope

**Comment by arfon** [comment]
@GregoryAshton - thanks for your submission to JOSS. After consulting with the editorial team, we have concluded this submission is out of scope due to its small size and limited application.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by GregoryAshton** [comment]
Hi @arfon and @labarba, my apologies for a delayed response. I didn't see this thread until today. 

I'm disappointed to see the rejection, is there any opportunity to revise and resubmit? If possible, I'd like clarity on the reasoning of "small size and limited application". What does the size refer to? The size of the repository or the paper? If the former, this code is far more than just a wrapper - it adds substantive functionality well beyond the underlying codebases and is the result of some significant work. While right now it isn't used in the literature, this will soon change as it has application in radio-pulsar data analysis and beyond. 

I apologise for not making the clear statement of need, I thought I had done so to some extent in the introduction, but clearly this isn't up to the journal standard. Please let me know if you would consider a resubmission attempting to address these issues.

All the best,

Greg
