### ISSUE TITLE
[PRE REVIEW]: InteractiveFixedEffectModels.jl:  A Julia package to estimate linear models with interactive fixed effects

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#249]
**Submitting author:** @matthieugomez (<a href="http://orcid.org/0000-0003-1304-2720">Matthieu Gomez</a>)
**Repository:** <a href="https://github.com/matthieugomez/InteractiveFixedEffectModels.jl" target ="_blank">https://github.com/matthieugomez/InteractiveFixedEffectModels.jl</a>
**Version:** v0.1.1
**Editor:** @pjotrp
**Reviewer:** @sens

**Author instructions**

Thanks for submitting your paper to JOSS @matthieugomez. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@matthieugomez if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@whedon assign @sens as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sens

**Comment by pjotrp** [comment]
Dear @matthieugomez, I am your editor and Prof. Saunak Sen will review your paper. To help kick start the process, would you be so kind to help us by looking at the check boxes on, for example, https://github.com/openjournals/joss-reviews/issues/251 and see if you tick the important ones? Once you are happy we'll kick off full review. Thanks.

**Comment by sens** [comment]
Can you give me some review instructions?  It seems it is not blind,
right?

Saunak

On Mon, May 01, 2017 at 11:35:33AM -0700, Pjotr Prins wrote:
> @whedon assign @sens as reviewer
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Śaunak Sen ... http://www.senresearch.org
Prof and Chief of Biostatistics, Dept of Prev Med, UTHSC, Memphis, TN
Appointments: https://saunaksen.youcanbook.me

**Comment by pjotrp** [comment]
Wait Saunak, let Matthieu confirm his submission is up to scratch. Then you'll get instructions for review.

**Comment by pjotrp** [comment]
@matthieugomez ping!

**Comment by pjotrp** [comment]
@matthieugomez are you going ahead with this submission or should we ask you to retract it?

**Comment by pjotrp** [comment]
Hi @matthieugomez please be so kind to give a YES/NO/Won't do it. So we can proceed with your submission. Is there something wrong?

**Comment by pjotrp** [comment]
@arfon if the submitter does not respond I think we should close this issue.

**Comment by pjotrp** [comment]
@arfon I have E-mailed the author without getting a response. I suggest we close this issue. If the author comes back we can reopen.

**Comment by arfon** [comment]
> @arfon I have E-mailed the author without getting a response. I suggest we close this issue. If the author comes back we can reopen.

Agreed.
