### ISSUE TITLE
[PRE REVIEW]: pyOptSparse: A Python framework for large-scale constrained nonlinear optimization of sparse systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2490]
**Submitting author:** @nwu63 (<a href="http://orcid.org/0000-0001-8856-9661">Neil Wu</a>)
**Repository:** <a href="https://github.com/mdolab/pyoptsparse/" target ="_blank">https://github.com/mdolab/pyoptsparse/</a>
**Version:** v2.1.3
**Editor:** @poulson
**Reviewers:** @jgoldfar, @vissarion, @matbesancon
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @nwu63. **Currently, there isn't an JOSS editor assigned** to your paper.

@nwu63 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2490 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.68 s (407.6 files/s, 145543.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             51           5855           7238          27893
Python                          63           2534           3870           9251
Fortran 77                      33            414           4760           7143
C                               22            491            697           5411
C/C++ Header                    63           2532           9879           4797
SWIG                             3            295            525           2508
CSS                              3            115            105            792
reStructuredText                26            311            252            673
make                             1             24              5            124
JavaScript                       1             15             33            112
Fortran 90                       2             21            134            106
Markdown                         3             29              0            104
HTML                             4             10              0             97
YAML                             2              7             10             88
Bourne Shell                     1              0              0              8
-------------------------------------------------------------------------------
SUM:                           278          12653          27508          59107
-------------------------------------------------------------------------------


Statistical information for the repository '2490' was gathered on 2020/07/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrew Ning                      1         77398              0            3.28
Anil Yildirim                    1            16             16            0.00
Ben Brelje                       1             1              0            0.00
Benjamin Brelje                  1           102             31            0.01
Bret Naylor                      6         78738             39            3.34
Drayton Munster                  3          1454            463            0.08
Eirikur Jonsson                  3            51             21            0.00
Frederik Zahle                   1            17              6            0.00
Gaetan Kenway                    2           502            189            0.03
Graeme Kennedy                   2           420              6            0.02
John Jasa                       35        621099            503           26.35
Justin Gray                      6           142             86            0.01
Kenneth Moore                    6           528             26            0.02
Kenneth-T-Moore                  5           211              8            0.01
Neil Wu                         45          6781           7401            0.60
Nicolas                          1             7              5            0.00
Nicolas Bons                    14        293304            284           12.44
Ping He                          2             2              2            0.00
Rob Falck                       11         79088             73            3.36
S Ryan                           1            14              4            0.00
Sabet Seraj                      2            27              6            0.00
Stephen Ryan                     1         17156              0            0.73
Yicong Fu                        1             9              0            0.00
elee                             2         16531              0            0.70
frza                             4         77098            130            3.27
gjkennedy                        3            99            219            0.01
gkennedy                         8         50922            411            2.18
hschilling                       1            98              4            0.00
jjasa                            1         79070              0            3.35
johnjasa                        11           521            443            0.04
kenneth_moore                    1            69              0            0.00
kenway                         143        624144          18283           27.23
kmarsteller                      2             6              0            0.00
lambe                           37         99993            606            4.26
lvzhoujie                        2         16373              1            0.69
mader                           10        186942             46            7.93
nbons                            6            97             27            0.01
nischintu                        1           615              0            0.03
swryan                           1           144            134            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Anil Yildirim                 9           56.2         14.7                0.00
Benjamin Brelje             102          100.0          6.5               46.08
Bret Naylor                  15            0.0         25.1                6.67
Eirikur Jonsson               3            5.9          7.8               33.33
John Jasa                    19            0.0         32.0               26.32
Justin Gray                  23           16.2         17.8               30.43
Kenneth Moore               463           87.7         19.4               16.20
Neil Wu                    5409           79.8          2.2                5.58
Nicolas                       5           71.4          7.9                0.00
Ping He                       1           50.0         28.6                0.00
Rob Falck                     4            0.0          2.6               50.00
Sabet Seraj                  27          100.0          1.4               22.22
Yicong Fu                     6           66.7          2.4               50.00
eirikurj                     30          100.0          4.2               23.33
gkennedy                    257            0.5         15.5               10.12
hschilling                   96           98.0          1.2               11.46
jjasa                       938            1.2         34.8               13.97
johnjasa                    327           62.8          9.8               32.72
kenneth_moore                 4            5.8          6.0                0.00
kenway                    70264           11.3         32.5               27.23
kmarsteller                   4           66.7         24.7                0.00
nbons                      2214         2282.5         33.7               22.67
nischintu                   397           64.6         13.0               24.18
```

**Comment by labarba** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02490/joss.02490/10.21105.joss.02490.pdf)

**Comment by labarba** [comment]
👋  @nwu63 — I'm going to send this back for a bit of work on the paper. Currently, it does not follow our guidance in providing a clear _Statement of Need_. See the section [What should my paper contain?](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) in our documentation. Tell us why the research world needs your software!

**Comment by labarba** [comment]
@jedbrown — the author suggested you as handling editor... could you take a look?

**Comment by labarba** [comment]
@poulson — the author suggested you as handling editor... could you take a look?

**Comment by nwu63** [comment]
Hi @labarba, sorry about that I didn't realize it had to be a separate section. I've updated the paper and pushed it to the repo, please take a look if you have time. I would also be happy to suggest reviewers if needed.

@whedon generate pdf from branch paper

**Comment by labarba** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02490/joss.02490/10.21105.joss.02490.pdf)

**Comment by labarba** [comment]
@whedon invite @poulson as editor

**Comment by whedon** [comment]
@poulson has been invited to edit this submission.

**Comment by poulson** [comment]
@whedon set @poulson as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by poulson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by poulson** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
Hi Mathieu (@matbesancon) :wave: -- This submission on large-scale contrained nonlinear optimization of sparse systems seems like a great fit for your expertise in optimization and python. Would you be able to serve as one of the reviewers?

**Comment by poulson** [comment]
Hi Vissarion (@vissarion) :wave: -- Given your extensive work on optimization (including high-dimensional volume estimation) and your experience in python, it would be extremely helpful if you would serve as one of the reviewers of this submission on large-scale constrained nonlinear optimization. Would you have the time to do so?

**Comment by poulson** [comment]
Hi Jonathan (@jgoldfar) :wave: -- Given your expertise in fast computation for PDEs and optimal control, and that you listed python as your preferred language, you seem to be a great fit for reviewing this submission on large-scale constrained nonlinear optimization. Would you be willing to serve as a reviewer for it?

**Comment by vissarion** [comment]
Hi Jack (@poulson), I am interested to do the review. When is the deadline? I will be offline the most of the August.

**Comment by nwu63** [comment]
Hi @poulson, just wondering if the paper can be moved to the review phase, or if it's waiting for some action from me.

**Comment by poulson** [comment]
Hi @vissarion -- I will reach out to more potential reviewers. Ideally we can get three -- we currently have one more confirmed. If we don't find at least one more by the end of August I will circle back.

**Comment by poulson** [comment]
@whedon add @jgoldfar as reviewer

**Comment by whedon** [comment]
OK, @jgoldfar is now a reviewer

**Comment by poulson** [comment]
> Hi @poulson, just wondering if the paper can be moved to the review phase, or if it's waiting for some action from me.

This is on me. Thank you for your patience on this!

**Comment by poulson** [comment]
Hi Severin (@sevberg) :wave: -- Given your expertise in Python and optimization, you would seem to be a great candidate for reviewing this submission on large-scale nonlinear optimization (in Python).

[FWIW: It seems that your username is incorrectly listed in the JOSS reviewer spreadsheet as @dsryberg]

**Comment by poulson** [comment]
Hi David (@torressa) :wave: -- Given your expertise in Linear Programming and python, you seem like a great candidate for reviewing this submission on large-scale nonlinear optimization in Python.

Please let us know if you have the capacity and interest to review this software and paper.

**Comment by matbesancon** [comment]
hi, I would be available to review the paper and project but likely not before september

**Comment by poulson** [comment]
> hi, I would be available to review the paper and project but likely not before september

Thank you for the fast response, Mathieu. Both you and Vissarion (@vissarion) have the same constraint and would make a complete set of reviewers if added. I lean towards adding you both as reviewers and kicking off the review under the knowledge that the review won't start until September.

**Comment by poulson** [comment]
@whedon add @vissarion as reviewer

**Comment by whedon** [comment]
OK, @vissarion is now a reviewer

**Comment by poulson** [comment]
@whedon add @matbesancon as reviewer

**Comment by whedon** [comment]
OK, @matbesancon is now a reviewer

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2564.
