### ISSUE TITLE
[PRE REVIEW]: PyGRB: A pure python gamma-ray burst analysis package.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2491]
**Submitting author:** @JamesPaynter (<a href="http://orcid.org/0000-0002-9672-4008">James Paynter</a>)
**Repository:** <a href="https://github.com/JamesPaynter/PyGRB" target ="_blank">https://github.com/JamesPaynter/PyGRB</a>
**Version:** v1.0.1
**Editor:** @xuanxu
**Reviewers:** @zingale, @grburgess
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JamesPaynter. **Currently, there isn't an JOSS editor assigned** to your paper.

@JamesPaynter if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.15 s (425.4 files/s, 44534.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          39            739            853           3278
reStructuredText                17            395            420            339
TeX                              1             19              0            199
YAML                             2             21              0            104
Markdown                         1             16              0             52
DOS Batch                        1              8              1             27
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                            62           1202           1280           4009
-------------------------------------------------------------------------------


Statistical information for the repository '2491' was gathered on 2020/07/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
JamesPaynter                    34          5834            964          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
JamesPaynter               4870           83.5          0.1               10.66
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1086/176902 is OK
- 10.1086/430294 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-4365/ab06fc is OK
- 10.1093/mnras/staa278 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK
- 10.1063/1.1835238 is OK
- 10.1111/j.1365-2966.2007.12353.x is OK
- 10.1086/184740 is OK
- 10.1086/186399 is OK
- 10.1086/186344 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02491/joss.02491/10.21105.joss.02491.pdf)

**Comment by labarba** [comment]
👋  @JamesPaynter — I'm going to send this back for a bit of work on the paper. Currently, it does not follow our guidance in providing a clear _Statement of Need_. See the section [What should my paper contain?](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) in our documentation. Tell us why the research world needs your software!

**Comment by labarba** [comment]
@whedon invite @xuanxu as editor

**Comment by whedon** [comment]
@xuanxu has been invited to edit this submission.

**Comment by xuanxu** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by JamesPaynter** [comment]
Hi @labarba, 
How does whedon identify the statement of need?

I have the lines 
"""
`PyGRB` is a pure Python, open source pulse-fitting package which aims bring gamma-ray burst light-curve fitting and analysis into the 21st century.
"""
and 
"""
`PyGRB` makes visually appealing and scientifically instructive light-curves from the 4 broadband energy channel BATSE data.
The main feature of `PyGRB` is its ability to fit analytic light-curve models to data.
"""

**Comment by labarba** [comment]
Please add a section heading: "Statement of need," and address the question there.

**Comment by JamesPaynter** [comment]
I have updated the paper (I also fixed a small bug and updated the version to 1.0.1 )

**Comment by JamesPaynter** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02491/joss.02491/10.21105.joss.02491.pdf)

**Comment by JamesPaynter** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
I'm sorry @JamesPaynter, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by xuanxu** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by xuanxu** [comment]
👋 @fipanther & @zingale - would you be willing to review this submission for JOSS?
I think your knowledge of Python and Astrophysics makes both of you a great fit for this submission.

**Comment by zingale** [comment]
I can do this, but note that I am not an observer.

**Comment by xuanxu** [comment]
Thanks @zingale! I'll assign you now and wait to have a second reviewer before starting the review issue. Stay tuned!

**Comment by xuanxu** [comment]
@whedon add @zingale as reviewer

**Comment by whedon** [comment]
OK, @zingale is now a reviewer

**Comment by xuanxu** [comment]
:wave: @grburgess would you be willing to review this submission for JOSS?
I think your knowledge of Python and Astrophysics makes you a nice fit for this submission.

**Comment by grburgess** [comment]
i would be happy to!

**Comment by xuanxu** [comment]
@grburgess great, thanks! I'll add you as reviewer and start the review issue now.

**Comment by xuanxu** [comment]
@whedon add @grburgess as reviewer

**Comment by whedon** [comment]
OK, @grburgess is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2536.

**Comment by xuanxu** [comment]
@zingale, @grburgess: please head over to #2536 where the review will take place.
