### ISSUE TITLE
[PRE REVIEW]: CIMSA: Customizable Integrated Multiple Sequence Alignment Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2493]
**Submitting author:** @kuangmeng (<a href="http://orcid.org/0000-0001-9656-5652">Mengmeng Kuang</a>)
**Repository:** <a href="https://github.com/kuangmeng/CIMSA" target ="_blank">https://github.com/kuangmeng/CIMSA</a>
**Version:** v1.0
**Editor:** @will-rowe
**Reviewers:** @CFGrote, @xyzmjf
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kuangmeng. **Currently, there isn't an JOSS editor assigned** to your paper.

@kuangmeng if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.41 s (68.0 files/s, 20563.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              5            475            430           2787
C/C++ Header                    13            579            947           2716
Markdown                         2             51              0            131
Python                           2             32             10             96
TeX                              1             10              0             88
HTML                             1              0              1             53
JavaScript                       2              1              8             28
make                             1              5              0             12
Bourne Shell                     1              1              0             10
-------------------------------------------------------------------------------
SUM:                            28           1154           1396           5921
-------------------------------------------------------------------------------


Statistical information for the repository '2493' was gathered on 2020/07/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
kuangmeng                        7          8386            277          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mengmeng Kuang             8109          100.0          0.0               18.19
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02493/joss.02493/10.21105.joss.02493.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1371/journal.pcbi.0030123 may be missing for title: Recent evolutions of multiple sequence alignment algorithms
- https://doi.org/10.1093/bioinformatics/btl472 may be missing for title: Probalign: multiple sequence alignment using partition function posterior probabilities
- https://doi.org/10.1093/bioinformatics/btq338 may be missing for title: MSAProbs: multiple sequence alignment based on pair hidden Markov models and partition function posterior probabilities
- https://doi.org/10.1109/bibm.2018.8621220 may be missing for title: ProbPFP: a multiple sequence alignment algorithm combining partition function and hidden markov model with particle swarm optimization
- https://doi.org/10.1093/comjnl/16.1.30 may be missing for title: SLINK: an optimally efficient algorithm for the single-link cluster method
- https://doi.org/10.1093/comjnl/20.4.364 may be missing for title: An efficient algorithm for a complete link method

INVALID DOIs

- None
```

**Comment by labarba** [comment]
👋  @kuangmeng — I'm going to send this back for a bit of work on the paper. Currently, it does not follow our guidance in providing a clear _Statement of Need_. See the section [What should my paper contain?](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) in our documentation. Tell us why the research world needs your software!

Also, to be eligible for consideration in JOSS, your software must be under a standard public license, approved by the Open Source Initiative. See our [documentation](https://joss.readthedocs.io/en/latest/review_criteria.html#software-license).

**Comment by labarba** [comment]
@will-rowe — would you have a look at this submission and let me know if you might be able to handle it as editor?

**Comment by kuangmeng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02493/joss.02493/10.21105.joss.02493.pdf)

**Comment by kuangmeng** [comment]
The `DOI` issue, the `open source license` issue, and the `Statement of Need` section issue have been fixed. Thanks.

**Comment by kuangmeng** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by kuangmeng** [comment]
@whedon check references

**Comment by kuangmeng** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1101/gr.2821705 is OK
- 10.1016/j.sbi.2006.04.004 is OK
- 10.1371/journal.pcbi.0030123 is OK
- 10.1093/bioinformatics/btl472 is OK
- 10.1093/bioinformatics/btq338 is OK
- 10.1109/TCBB.2014.2316820 is OK
- 10.1109/bibm.2018.8621220 is OK
- 10.1093/comjnl/16.1.30 is OK
- 10.1093/comjnl/20.4.364 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.76 s (37.0 files/s, 11198.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              5            475            430           2787
C/C++ Header                    13            579            947           2716
Markdown                         2             51              0            131
TeX                              1             10              0             97
Python                           2             32             10             96
HTML                             1              0              1             53
JavaScript                       2              1              8             28
make                             1              5              0             12
Bourne Shell                     1              1              0             10
-------------------------------------------------------------------------------
SUM:                            28           1154           1396           5930
-------------------------------------------------------------------------------


Statistical information for the repository '2493' was gathered on 2020/07/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
kuangmeng                        7          8386            277          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mengmeng Kuang             8109          100.0          0.0               18.19
```

**Comment by kuangmeng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02493/joss.02493/10.21105.joss.02493.pdf)

**Comment by kuangmeng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02493/joss.02493/10.21105.joss.02493.pdf)

**Comment by will-rowe** [comment]
@labarba - I'm on leave for the week but happy to handle when I get back

**Comment by labarba** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Hi @kuangmeng 

Thanks for the submission! I've been reading through it this morning and have a couple of things I'd like before we put this out for review.

* I'm not an MSA algorithm researcher so am finding this a little hard to find a use case for. It would be great if you could provide a usage example, ideally for a real-world analysis problem. This will also help me find reviewers for your submission. This would be really beneficial at the top of the README.

* Please could you add some additional testing. I see that you have a test to make sure the compiled binary works with all available parameters, this is good! But I think we really need some unit testing - particularly where you have reimplemented MSA algorithms. It would be great if you could also hook this up to continuous integration (e.g. travis)

* I think the documentation needs a little work beyond what you have in the README. It would be really useful to have some more information on the various parameters, what the methods you have reimplemented are doing and how to access/interpret the results. Your figure from the paper would be useful here too. To save the README getting too crowded, you could add documentation via GitHub wiki or a service like readthedocs.

Sorry that these are quite significant points, but I really think they need doing before we can review this. Let me know if you need any further clarification or help.

**Comment by kuangmeng** [comment]
@will-rowe Thanks for your comments and I will revise the README and additional testing issues ASAP.

**Comment by kuangmeng** [comment]
Hi @will-rowe 

Thanks for your comments and I have revised the README file for your 1st and 3rd comments. As for 2nd comment, I will try my best to do it.

**Comment by kuangmeng** [comment]
Dear @will-rowe ,

Thank you for waiting so long. Since the calculation results of each step of my CIMSA are uncertain, I can't add normal unit tests. Therefore, in order to determine the correctness of each step, I add the `assert()` statement and print the intermediate running state. I hope this can help you understand my program better. Thanks.

**Comment by kuangmeng** [comment]
@labarba @will-rowe Please let me know what I should provide for further consideration. I really appreciate your comments and suggestions. Thanks.

**Comment by will-rowe** [comment]
Hi @kuangmeng - thanks for your update. My concern is that this still falls short of our reviewer [criteria](https://joss.readthedocs.io/en/latest/review_criteria.html?highlight=tests#tests):

```
No way for you, the reviewer, to objectively assess whether the software works
```

This might be my fault for not being specific enough. Could you include some sort of "truth set". For example, a set of sequences and the expected MSA? These expected MSAs could be generated using other tools (maybe clustal for instance?). A minimal example could be to have a test that takes an input set, produces an MSA using your software and then diffs this against a reference MSA.

[Here](https://github.com/HPCTUSofiaOrg/clustalw2/blob/master/test_clustal.sh) is an example I just found of another MSA aligner doing this. Personally, I'd prefer it done using a testing framework, and for fail/edge cases to be considered, but that is not a requirement for review (but might make your life easier when maintaining the software :))

**Comment by will-rowe** [comment]
Thanks @kuangmeng - I think this meets are criteria for review now. Let's find some reviewers and then start the process.

**Comment by will-rowe** [comment]
Hi @CFGrote and @VivekTodur - would you both be willing to review this submission please?

**Comment by kuangmeng** [comment]
> Thanks @kuangmeng - I think this meets are criteria for review now. Let's find some reviewers and then start the process.

Many thanks. @will-rowe

**Comment by CFGrote** [comment]
Thanks for the offer, I accept.

**Comment by will-rowe** [comment]
Thanks @CFGrote - that's brilliant. I'll track down one more reviewer and then we'll start

**Comment by will-rowe** [comment]
Hi @bblum9, @lmvasquezg and @emilydolson - would any of you be able to review this submission for JOSS please?

**Comment by xyzmjf** [comment]
Hi Will

Apologies for taking a few days to reply. I can review this manuscript.
What timeline are you expecting, and what format would you want the review
in.
As this is the first time I will have reviewed for you, I do have a few
'newbie' questions.

Mark

**Comment by bblum9** [comment]
I'm also available to review this submission.

**Comment by will-rowe** [comment]
Perfect - thanks @xyzmjf

Please find the full reviewer documentation [here](https://joss.readthedocs.io/en/latest/review_criteria.html).

We will start a new thread in a moment which will record the submission process and this one will be closed. You can use the new thread to track the review process, mark off your reviewer checklist and let us know your recommendation etc. As well as this, we suggest writing your reviewer comments and feedback as a Github issue on the submitting author's repository (https://github.com/kuangmeng/CIMSA).

I'll start the review thread in a moment and please feel free to ask any question there. We are pretty flexible on how long the review takes; usually it's best if it can be received within a few weeks but I appreciate that timelines are tricky for everyone at the moment.

**Comment by will-rowe** [comment]
@bblum9 - thank you for your quick response but we now have 2 reviewers. I really appreciate you getting back to me and I hope you will be available to review for us in the future

**Comment by will-rowe** [comment]
@whedon assign @CFGrote as reviewer

**Comment by whedon** [comment]
OK, @CFGrote is now a reviewer

**Comment by will-rowe** [comment]
@whedon add @xyzmjf as reviewer

**Comment by whedon** [comment]
OK, @xyzmjf is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2672.
