### ISSUE TITLE
[REVIEW]: bridge-sim: A Python library for concrete slab bridge simulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2496]
**Submitting author:** @barischrooneyj (<a href="http://orcid.org/0000-0002-8441-212X">Jeremy Barisch-Rooney</a>)
**Repository:** <a href="https://github.com/barischrooneyj/bridge-sim" target ="_blank">https://github.com/barischrooneyj/bridge-sim</a>
**Version:** v0.0.7
**Editor:** @diehlpk
**Reviewers:** @andybond13
**Archive:** Pending

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/65617b7c67695eb192635d01d0739ada/status.svg)](https://joss.theoj.org/papers/65617b7c67695eb192635d01d0739ada)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/65617b7c67695eb192635d01d0739ada"><img src="https://joss.theoj.org/papers/65617b7c67695eb192635d01d0739ada/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/65617b7c67695eb192635d01d0739ada/status.svg)](https://joss.theoj.org/papers/65617b7c67695eb192635d01d0739ada)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/barischrooneyj/bridge-sim" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@andybond13 & @manparvesh, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @diehlpk know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/barischrooneyj/bridge-sim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@barischrooneyj) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/barischrooneyj/bridge-sim">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@barischrooneyj) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @skreimeyer, @manparvesh it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/mcse.2011.66 may be missing for title: OpenSees: a framework for earthquake engineering simulation
- https://doi.org/10.1109/mcse.2007.55 may be missing for title: Matplotlib: A 2D graphics environment

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02496/joss.02496/10.21105.joss.02496.pdf)

**Comment by diehlpk** [comment]
@barischrooneyj

Following things:

1. Can you extend 1 TNO with the full name? Most people might not know what TNO means.
2. State of the field: Do the authors describe how this software compares to other commonly-used packages? I feel that this point is missing in the paper. Can you add more details there?

I leave the remaining check boxes to the reviewers :)

**Comment by skreimeyer** [comment]
This process is a lot more like doing my taxes than I expected. No thanks.

Best of luck.

**Comment by diehlpk** [comment]
@whedon remove @skreimeyer as reviewer

**Comment by whedon** [comment]
OK, @skreimeyer is no longer a reviewer

**Comment by diehlpk** [comment]
@barischrooneyj have you seen my remarks? Can you address them before the reviewers start?

**Comment by andybond13** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by andybond13** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by andybond13** [comment]
@whedon add @andybond13 as reviewer

**Comment by whedon** [comment]
I'm sorry @andybond13, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arfon** [comment]
@whedon re-invite @andybond13 as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@andybond13 please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by barischrooneyj** [comment]
> @barischrooneyj
> 
> Following things:
> 
> 1. Can you extend 1 TNO with the full name? Most people might not know what TNO means.
> 2. State of the field: Do the authors describe how this software compares to other commonly-used packages? I feel that this point is missing in the paper. Can you add more details there?
> 3. Add countries (full name no abbreviation) to the affiliations
> 
> I leave the remaining check boxes to the reviewers :)

@diehlpk @andybond13 I'm in the process of moving house/country, so I can get around to addressing your comments and I will also do another pass of the documentation, next week. I will let you know when that pass is done. Best, Jeremy

**Comment by diehlpk** [comment]
@barischrooneyj Good luck with the move.

**Comment by diehlpk** [comment]
@barischrooneyj Hope you finished your moving. Could you find some time to update the paper?

**Comment by andybond13** [comment]
Learning how to use docker...

FYI: As instructed in the documentation, "docker run -it barischrooneyj/bridge-sim:v0.0.8.5" returns error "docker: Error response from daemon: manifest for barischrooneyj/bridge-sim:v0.0.8.5 not found: manifest unknown: manifest unknown."

using "docker run -it barischrooneyj/bridge-sim:v0.0.8" seems to work.

**Comment by manparvesh** [comment]
hi @diehlpk sorry, please remove me from the reviewers list.

**Comment by andybond13** [comment]
Hi @diehlpk , I am getting through the review. Plan to complete this weekend.

**Comment by diehlpk** [comment]
> hi @diehlpk sorry, please remove me from the reviewers list.

Sure, could you please recommend someone else?

**Comment by diehlpk** [comment]
@whedon remove @manparvesh as reviewer

**Comment by whedon** [comment]
OK, @manparvesh is no longer a reviewer

**Comment by diehlpk** [comment]
Hi @CBenghi @mdelcambre @satish-annigeri @abhiramm7 would you be interested to review this paper?

**Comment by andybond13** [comment]
Hello @diehlpk , I have completed my review. I apologize for the delayed completion!

I am not comfortable accepting the submission at this point, primarily due to the lack of broad applicability. The submission implicitly contains many limiting assumptions which would prevent adoption of the submitted code outside of the author’s group, let alone to professional bridge engineers. Hence, my recommendation would be to suggest that the author make significant changes before publication.

I have prepared a detailed review (attached), which maps comments to the review checklist above.

[JOSS_review_sept13_2020.pdf](https://github.com/openjournals/joss-reviews/files/5215219/JOSS_review_sept13_2020.pdf)

**Comment by barischrooneyj** [comment]
@andybond13 Thank you for a very informative review! I will work through it, it might take 6-12 months since A I am not working on this project full time and B additional functionality will be added to bridge-sim. However it will get done. Thanks again :smile:

**Comment by andybond13** [comment]
@barischrooneyj @diehlpk 
No problem! The problem that this software is trying to address is challenging and has great relevance, and I commend Jeremy for attempting to tackle it. I would be willing to review the work again in the future, if desired by the editor and/or author.

**Comment by diehlpk** [comment]
Hi, @andybond13 thanks for the intense review. I agree that the paper/code is not ready for submission yet. 

I will pause the review for now and once @barischrooneyj finished the major revision, I will open it again. @barischrooneyj just ping me here once you have the revision done. In addition, please respond to all of the reviewer comments. 

 I am looking forward to your revision.

**Comment by diehlpk** [comment]
@barischrooneyj  How is the major revision going? Any plans to submit it within the next three months?

**Comment by CBenghi** [comment]
Hello, I'm already involved in a different review at the moment.
If you still need a reviewer once that one is completed I'd be happy to help, but I'd like to take up one at a time, if possible.

**Comment by diehlpk** [comment]
@barischrooneyj How is the major revision going? Any plans to submit it within the next three months?

**Comment by diehlpk** [comment]
@openjournals/joss-eics since we have not received any response, if the author wants to submit a major revision, could you please withdraw the paper? Thanks, Patrick

**Comment by arfon** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
