### ISSUE TITLE
[PRE REVIEW]: EFAtools: An R package with fast and flexible implementations of exploratory factor analysis tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2499]
**Submitting author:** @mdsteiner (<a href="http://orcid.org/0000-0002-8126-0757">Markus Steiner</a>)
**Repository:** <a href="https://github.com/mdsteiner/EFAtools" target ="_blank">https://github.com/mdsteiner/EFAtools</a>
**Version:** v0.1.1
**Editor:** @fboehm
**Reviewers:** @jacobsoj, @chainsawriot
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mdsteiner. **Currently, there isn't an JOSS editor assigned** to your paper.

@mdsteiner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.89 s (107.7 files/s, 13801.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               82           1887           2796           5648
C++                              6            163            491            487
Markdown                         4             70              0            269
TeX                              1             15              0            148
Rmd                              2            104            144             73
YAML                             1              1              1              2
-------------------------------------------------------------------------------
SUM:                            96           2240           3432           6627
-------------------------------------------------------------------------------


Statistical information for the repository '2499' was gathered on 2020/07/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Markus Steiner                   1             4              4            0.28
Silvia Grieder                   3            34             33            2.38
mdsteiner                       26          1939            799           97.33

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Markus Steiner                4          100.0          8.6                0.00
Silvia Grieder               21           61.8          1.8               57.14
mdsteiner                  1116           57.6          5.8               42.92
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1177/1073191119845051 is OK
- 10.1007/BF02289209 is OK
- 10.7275/jyj1-4868 is OK
- 10.1177/0095798418771807 is OK
- 10.7287/peerj.preprints.3188v1 is OK
- 10.1016/j.csda.2013.02.005 is OK
- 10.1037/met0000200 is OK
- 10.1037/met0000074 is OK
- 10.1037/a0025697 is OK
- 10.1080/00273171.2011.564527 is OK
- 10.18637/jss.v048.i02 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02499/joss.02499/10.21105.joss.02499.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@mdsteiner our system could not detect a license. Can you add a plain text `LICENSE` file to your repository? Adding it to the main repository folder is best (that way GitHub also easily discovers it and will render a clear license badge on your repo). The license needs to be an [OSI approved open source license](https://opensource.org/licenses).

**Comment by Kevin-Mattheus-Moerman** [comment]
@KristinaRiemer @fboehm @mikldk @csoneson could one of you handle this submission?

**Comment by mdsteiner** [comment]
thanks for the note! We have now added a `LICENSE` file to our repository.

As potential reviewers we think that maybe jacobsoj, navmayan, ihrke, or mmrabe (all from the linked list) might be suitable based on their descriptions on the domains/ topics they are comfortable to review.

**Comment by fboehm** [comment]
Yes, thank you, @Kevin-Mattheus-Moerman. I'm happy to handle this submission.

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@whedon assign @jacobsoj as reviewer

**Comment by whedon** [comment]
OK, @jacobsoj is now a reviewer

**Comment by fboehm** [comment]
@whedon add @chainsawriot as reviewer

**Comment by whedon** [comment]
OK, @chainsawriot is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2521.
