### ISSUE TITLE
[PRE REVIEW]: tacost: Testing and simulating the performance of acoustic tracking systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2501]
**Submitting author:** @thejasvibr (<a href="http://orcid.org/0000-0001-5360-4383">Beleyur Thejasvi</a>)
**Repository:** <a href="https://github.com/thejasvibr/tacost" target ="_blank">https://github.com/thejasvibr/tacost</a>
**Version:** v0.1.35
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @thejasvibr. **Currently, there isn't an JOSS editor assigned** to your paper.

@thejasvibr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2501 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.25 s (127.2 files/s, 84030.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1            615              4          15543
Python                          18            312            322            719
TeX                              1             29              0            213
Jupyter Notebook                 1              0           2760            196
reStructuredText                 3             76             28            129
Markdown                         2             33              0             90
DOS Batch                        1              8              1             26
YAML                             4              0              0             12
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            32           1077           3122          16937
-------------------------------------------------------------------------------


Statistical information for the repository '2501' was gathered on 2020/07/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
tbeleyur                        16          2391           1070           98.41
unknown                          1            44             12            1.59

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
tbeleyur                   1309           54.7          1.9                9.40
unknown                      44          100.0          0.0                4.55
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/s00265-017-2398-x is OK
- 10.1016/j.cub.2010.07.046 is OK
- 10.1111/1365-2435.13073 is OK
- 10.1371/journal.pcbi.1005412 is OK
- 10.1371/journal.pbio.1001745 is OK
- 10.1121/1.424536 is OK
- 10.5281/zenodo.3518761 is OK
- 10.1242/jeb.081398 is OK
- 10.1098/rspb.2008.1505 is OK
- 10.1371/journal.pone.0162069 is OK
- 10.1002/ece3.6216 is OK
- 10.1111/j.1365-2664.2011.01993.x is OK
- 10.1098/rspb.2003.2487 is OK

MISSING DOIs

- https://doi.org/10.20965/jrm.2017.p0213 may be missing for title: HARKBird: Exploring acoustic interactions in bird communities using a microphone array
- https://doi.org/10.1121/1.416105 may be missing for title: Acoustical flight path tracking of echolocating bats
- https://doi.org/10.1121/1.428329 may be missing for title: Sperm whale clicks: Directionality and source level revisited

INVALID DOIs

- 10.1109/ICASSP.2019.8683221. is INVALID
```

**Comment by thejasvibr** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by thejasvibr** [comment]
potential reviewers: krystophny, pharshalp, dbuscombe-usgs

**Comment by thejasvibr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02501/joss.02501/10.21105.joss.02501.pdf)

**Comment by thejasvibr** [comment]
@whedon article proof is okay

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kthyng** [comment]
Hi @thejasvibr. Thank you for your submission. However, while your software does indeed look useful research software, the JOSS editorial board has determined that it does not meet the bar of [_substantial scholarly effort_](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

If you continue to develop this work, we would be happy to reconsider it as a submission in the future.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
