### ISSUE TITLE
[PRE REVIEW]: 21cmFAST v3: A Python-integrated C code for generating 3D realizations of the cosmic 21cm signal.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2502]
**Submitting author:** @steven-murray (<a href="http://orcid.org/0000-0003-3059-3823">Steven Murray</a>)
**Repository:** <a href="https://github.com/21cmFAST/21cmFAST" target ="_blank">https://github.com/21cmFAST/21cmFAST</a>
**Version:** v3.0.0
**Editor:** @dfm
**Reviewers:** @sambit-giri, @sultanier
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @steven-murray. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @harpolea.

@steven-murray if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2502 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02502/joss.02502/10.21105.joss.02502.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.40 s (211.8 files/s, 74707.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                               13           2625           1281          10870
Python                          31           1651           2199           6043
reStructuredText                20            222            112            685
C/C++ Header                     6            210            237            468
Jupyter Notebook                 4              0           2185            385
YAML                             7             16             15            215
make                             1             24              5            125
INI                              1              5              0             30
TOML                             1              0              0             14
-------------------------------------------------------------------------------
SUM:                            84           4753           6034          18835
-------------------------------------------------------------------------------


Statistical information for the repository '2502' was gathered on 2020/07/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
BradGreig                      227         22960           9496           22.57
Catherine Watkinson              2          1611             22            1.14
Jaehong Park                     6           149             42            0.13
JulianBMunoz                     7           576            168            0.52
Steven Murray                  388         53454          50468           72.25
Yuxiang                          8           116             11            0.09
Yuxiang Qin                    103          3570           1186            3.31

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
BradGreig                 13098           57.0         15.2               25.92
Catherine Watkinson          10            0.6          8.6               10.00
Jaehong Park                 88           59.1          5.1               13.64
JulianBMunoz                317           55.0          9.4               10.41
Steven Murray             10065           18.8         10.4                9.84
Yuxiang Qin                2006           56.2          7.8               27.42
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@dfm @xuanxu @harpolea @eloisabentivegna @mbobra @pibion could one of you handle this submission? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
@Kevin-Mattheus-Moerman: yes - I'm happy to edit!

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by steven-murray** [comment]
Thanks @dfm! It looks like one of the figures is not rendering, and a couple of the references. I'll fix them up ASAP.

**Comment by steven-murray** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02502/joss.02502/10.21105.joss.02502.pdf)

**Comment by dfm** [comment]
@steven-murray: Quick update here: I'm still working on finding reviewers and I'll keep you posted. Thanks for your patience!

**Comment by steven-murray** [comment]
@dfm thanks for the update!

**Comment by dfm** [comment]
@sambit-giri has kindly agreed to act as a reviewer. Thanks!

Note that Sambit has previously co-authored with two authors of this submission (Grieg and Mesinger) as part of a larger collaboration, but we believe that this will not affect his ability to provide an impartial review so I don't think that this should present a conflict of interest. @steven-murray please let me know (here or via email) if you or any of your co-authors have any concerns!

**Comment by dfm** [comment]
@whedon assign @sambit-giri as reviewer

**Comment by whedon** [comment]
OK, @sambit-giri is now a reviewer

**Comment by steven-murray** [comment]
@dfm I know @sambit-giri but have never published with him. I am more than happy for him to review. Thanks!

**Comment by dfm** [comment]
@sultanier has agreed to act as the second reviewer. I'll add him and then get the main review started. It will be in a separate issue thread so we'll head over there once `@whedon` gives us the link.

Thanks all and let me know if any of you have questions as the review progresses!

**Comment by dfm** [comment]
@whedon add @sultanier as reviewer

**Comment by whedon** [comment]
OK, @sultanier is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2582.
