### ISSUE TITLE
[PRE REVIEW]: SeroTools: a Python package for Salmonella serotype data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2503]
**Submitting author:** @jdbaugher (<a href="http://orcid.org/0000-0003-2466-3047">Joseph D Baugher</a>)
**Repository:** <a href="https://github.com/CFSAN-Biostatistics/SeroTools" target ="_blank">https://github.com/CFSAN-Biostatistics/SeroTools</a>
**Version:** v0.2.0
**Editor:** @majensen
**Reviewers:** @amoeba, @Maghnuso
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jdbaugher. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @will-rowe.

@jdbaugher if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1038/s41598-020-61254-1 is OK
- 10.1128/genomeA.00215-15 is OK
- 10.3389/fmicb.2020.00549 is OK
- 10.3389/fmicb.2019.02554 is OK
- 10.1016/j.fm.2020.103452 is OK
- 10.1016/j.resmic.2009.10.002 is OK
- 10.3389/fmicb.2018.02993 is OK
- 10.1016/j.resmic.2014.07.004 is OK
- 10.1128/JCM.00008-15 is OK
- 10.1017/s0022172400034677 is OK
- 10.3389/fmicb.2019.01591 is OK
- 10.1007/978-1-4939-9000-9_17 is OK
- 10.1128/AEM.02265-19 is OK
- 10.1128/JCM.00190-19 is OK
- 10.1128/AEM.00165-19 is OK
- 10.3389/fmicb.2017.01044 is OK
- 10.1371/journal.pone.0147101 is OK
- 10.1128/JCM.00323-15 is OK
- 10.1128/AEM.01746-19 is OK

MISSING DOIs

- https://doi.org/10.1016/b978-0-12-387730-7.00020-6 may be missing for title: Methods in Microbiology.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02503/joss.02503/10.21105.joss.02503.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.29 s (105.2 files/s, 23551.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
RobotFramework                   1              0              0           2698
Python                           7            591            717           1476
reStructuredText                15            182             39            288
TeX                              1             25              0            236
DOS Batch                        1             29              1            212
make                             2             42              6            207
Markdown                         1             39              0            110
INI                              1              2              0             11
YAML                             1              4              3              9
CSS                              1              2              4              8
-------------------------------------------------------------------------------
SUM:                            31            916            770           5255
-------------------------------------------------------------------------------


Statistical information for the repository '2503' was gathered on 2020/07/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Baugher                          1          1921              0           46.11
Joseph Baugher                   5             9              9            0.43
Joseph D. Baugher, P             4          1545            682           53.46

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Baugher                    1259           65.5          0.0               28.20
Joseph Baugher                4           44.4          0.1               50.00
Joseph D. Baugher, P       1521           98.4          0.4                9.47
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@jdbaugher 

- [ ] Can you check that missing DOI :point_up: 

- [ ] Can you add a dedicated "Statement of need" section (see [our guidelines](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements))

**Comment by Kevin-Mattheus-Moerman** [comment]
@fboehm @marcosvital @majensen could one of you handle this submission? Can you also verify it is in scope and flag it for scope review if you feel it is too minor in terms of functionality? Thanks!

**Comment by fboehm** [comment]
@Kevin-Mattheus-Moerman - in terms of volume, it seems sufficient, with 1400 lines of Python. However, I'm a new editor, so I have less experience with determining scope. What other characteristics do you suggest we examine when assessing scope? 

I don't think that I'm familiar enough with existing software to say whether this submission offers new functionality for Python users.

**Comment by majensen** [comment]
@Kevin-Mattheus-Moerman I think this work is in scope. I expect there are few FOSS tools that do this particular job, which is an important one in food safety and molecular epidemiology. Because of this, I would bet that the user base within the specialty is significant (@jdbaugher - feel free to chime in here). This software also provides an important service, because it is free to use. Microbial typing analysis programs can be proprietary and too expensive for small labs.

**Comment by jdbaugher** [comment]
> @jdbaugher
> 
>     * [ ]  Can you check that missing DOI ☝️
> 
>     * [ ]  Can you add a dedicated "Statement of need" section (see [our guidelines](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements))

@Kevin-Mattheus-Moerman I have added the Statement of Need.

Regarding, the missing DOI, the reference in question is a book for which I have been unable to locate a DOI. The suggested DOI is for a different publication.

**Comment by majensen** [comment]
@Kevin-Mattheus-Moerman I'm happy to review this but I would give the right of first and second refusal to the new editors.

**Comment by jdbaugher** [comment]
> @Kevin-Mattheus-Moerman I think this work is in scope. I expect there are few FOSS tools that do this particular job, which is an important one in food safety and molecular epidemiology. Because of this, I would bet that the user base within the specialty is significant (@jdbaugher - feel free to chime in here). This software also provides an important service, because it is free to use. Microbial typing analysis programs can be proprietary and too expensive for small labs.

@Kevin-Mattheus-Moerman @majensen Characterization of Salmonella by serotyping is the standard methodology broadly used by public health and infectious disease communities, thus the potential user base would be substantial, including international public health agencies and research communities in academia and global food manufacturing. SeroTools provides unique functionality for query and comparison of serotyping data which is necessary for computationally efficient analyses as genomic databases continue to grow and computational predictions are replacing laboratory-based methods. To my knowledge there are currently no other software tools which support similar functionality.

**Comment by fboehm** [comment]
@Kevin-Mattheus-Moerman @majensen @marcosvital - I prefer to not be the editor for this submission, as I have several submissions in progress right now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
Hi @amoeba - would this [JOSS](https://joss.theoj.org) [submission](#2503) be of interest to you for review? thanks for considering - @majensen

**Comment by amoeba** [comment]
Hi @majensen, I can review this within six weeks from today.

**Comment by majensen** [comment]
@amoeba sold! Thanks!

**Comment by majensen** [comment]
@whedon add @amoeba as reviewer

**Comment by whedon** [comment]
OK, @amoeba is now a reviewer

**Comment by majensen** [comment]
I'm working via another channel on an additional reviewer - FYI

**Comment by majensen** [comment]
@Maghnuso welcome to Github and JOSS! I will assign you as a reviewer now.

**Comment by majensen** [comment]
@whedon add @Maghnuso as reviewer

**Comment by whedon** [comment]
OK, @Maghnuso is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2556.

**Comment by majensen** [comment]
@jdbaugher @amoeba @Maghnuso see you over at #2556 for the official review - thanks all
