### ISSUE TITLE
[PRE REVIEW]: RK-Opt: A package for the design of numerical ODE solvers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2504]
**Submitting author:** @ketch (<a href="http://orcid.org/0000-0002-1212-126X">David Ketcheson</a>)
**Repository:** <a href="https://github.com/ketch/RK-Opt" target ="_blank">https://github.com/ketch/RK-Opt</a>
**Version:** v1.0.0
**Editor:** @diehlpk
**Reviewers:** @gardner48, @debdeepbh
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ketch. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @VivianePons.

@ketch if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.24 s (336.7 files/s, 41920.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                          56            682           1387           4923
reStructuredText                13            355             32            586
Python                           6            228            316            467
CSS                              1             91             16            405
TeX                              2             41              0            293
Markdown                         2             38              0            180
make                             1             22              4            113
JSON                             1              0              0             29
-------------------------------------------------------------------------------
SUM:                            82           1457           1755           6996
-------------------------------------------------------------------------------


Statistical information for the repository '2504' was gathered on 2020/07/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
David Ketcheson                 13           171             42           19.14
Hendrik Ranocha                  2             8              8            1.44
Matteo Parsani                   2           883              1           79.42

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
David Ketcheson             158           92.4         64.8               10.76
Hendrik Ranocha               6           75.0          0.3                0.00
Matteo Parsani              847           95.9          0.0               23.85
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2140/camcos.2012.7.247 is OK
- 10.1090/S0025-5718-09-02209-1 is OK
- 10.1137/120885899 is OK
- 10.1007/s10915-013-9796-7 is OK
- 10.1007/s10915-017-0560-2 is OK
- 10.1007/s10915-016-0195-8 is OK
- 10.1007/s10915-016-0195-8 is OK
- 10.1007/s10915-016-0195-8 is OK
- 10.1063/1.4992751 is OK
- 10.1137/07070485X is OK
- 10.1016/j.apnum.2008.03.034 is OK
- 10.1016/j.jcp.2009.11.006 is OK
- 10.1137/100818674 is OK
- 10.1137/10080960X is OK
- 10.1090/mcom/3115 is OK
- 10.1007/s10915-018-0664-3 is OK
- 10.1016/j.jcp.2019.01.003 is OK
- 10.1016/j.jcp.2020.109499 is OK
- 10.1007/978-1-84800-155-8_7 is OK
- 10.1007/s10915-019-00916-3 is OK

MISSING DOIs

- https://doi.org/10.1016/0378-4754(87)90083-8 may be missing for title: Solving ordinary differential equations I: Nonstiff Problems

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02504/joss.02504/10.21105.joss.02504.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@ketch can you check that missing DOI? :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@VivianePons @meg-simula @xuanxu @diehlpk @drvinceknight @jedbrown could one of you handle this submission? Thanks!

**Comment by ketch** [comment]
> @ketch can you check that missing DOI? ☝️

Sure -- that reference is a book.  The suggested DOI refers to a review of the book, so it isn't correct.  As far as I know, the book doesn't have a DOI.

**Comment by diehlpk** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by diehlpk** [comment]
Hi, @lheagy @mancellin @arghdos @JaroslavHron would you be interested to review this paper?

**Comment by lheagy** [comment]
Thanks for thinking of me! I have a few other reviews on my plate at the moment so unfortunately can't take this on at the moment

**Comment by ChrisRackauckas** [comment]
Thanks for invitation, but I do not think I will be able to turn this around in an adequate time. Good luck to anyone else suddenly building an online course too 😱.

**Comment by diehlpk** [comment]
@ketch Can you recommend some potential reviewers?

**Comment by jedbrown** [comment]
@diehlpk Hong Zhang or Emil Constantinescu at Argonne, Mayya Tokman at UC Merced, Ray Spiteri at U Saskatchewan, Carol Woodward at LLNL.

**Comment by mancellin** [comment]
Thank you for the invitation. Unfortunately, I don't think I'll be able to make it either.

**Comment by diehlpk** [comment]
@whedon assign @gardner48 reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by diehlpk** [comment]
@whedon assign @gardner48 as reviewer

**Comment by whedon** [comment]
OK, @gardner48 is now a reviewer

**Comment by diehlpk** [comment]
@ketch Can you please add the countries no abbreviations to all the affiliations?

**Comment by diehlpk** [comment]
@whedon add @debdeepbh as reviewer

**Comment by whedon** [comment]
OK, @debdeepbh is now a reviewer

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2514.
