### ISSUE TITLE
[REVIEW]: TTLocVis: A Twitter Topic Location Visualization Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2507]
**Submitting author:** @xillig (<a href="http://orcid.org/0000-0003-2346-2841">Gillian Kant</a>)
**Repository:** <a href="https://github.com/xillig/TTLocVis" target ="_blank">https://github.com/xillig/TTLocVis</a>
**Version:** 1.0.4
**Editor:** @trallard
**Reviewer:** @sara-02 , @linuxscout, @aozorahime
**Archive:** <a href="https://doi.org/10.5281/zenodo.4133399" target="_blank">10.5281/zenodo.4133399</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/448cbcd790258531fd790d0225442c94/status.svg)](https://joss.theoj.org/papers/448cbcd790258531fd790d0225442c94)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/448cbcd790258531fd790d0225442c94"><img src="https://joss.theoj.org/papers/448cbcd790258531fd790d0225442c94/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/448cbcd790258531fd790d0225442c94/status.svg)](https://joss.theoj.org/papers/448cbcd790258531fd790d0225442c94)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/xillig/TTLocVis" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sara-02  & @linuxscout & @aozorahime, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @trallard know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xillig/TTLocVis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@xillig) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xillig/TTLocVis">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@xillig) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xillig/TTLocVis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@xillig) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sara-02 , @linuxscout, @aozorahime it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1145/2484028.2484166 may be missing for title: Improving LDA Topic Models for Microblogs via Tweet Pooling and Automatic Labeling

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02507/joss.02507/10.21105.joss.02507.pdf)

**Comment by trallard** [comment]
Thanks all for offering to review. You will find your reviewer's checklist at the top of this issue. 
If you encounter any issues please let me know and I can assist.

**Comment by sara-02** [comment]
Hey @xillig
You may want to check out these projects/papers that have previousy worked on twiiter data vizulization and include them under the literature review for your paper.
Also, you need to point our how your package compares to existing work, maybe this list can be a starting point.
- https://www.csc2.ncsu.edu/faculty/healey/tweet_viz/
- Q.  Kong,  R.  Ram,  and  M.-A.  Rizoiu,  “A  toolkit  for  analyzing  andvisualizing  online  users  via  reshare  cascade  modeling,”ArXiv,  vol.abs/2006.06167, 2020.
- S.  Malik,  A.  Smith,  T.  Hawes,  P.  Papadatos,  J.  Li,  C.  Dunne,  andB. Shneiderman, “Topicflow: Visualizing topic alignment of twitter dataover time,” inASONAM, 2013, p. 720–726.
-  Florence   Ying   Wang,   A.   Sallaberry,  K.   Klein,   M.   Takatsuka,   andM.  Roche,  “Senticompass:  Interactive  visualization  for  exploring  andcomparing  the  sentiments  of  time-varying  twitter  data,”  inPacificVis,2015, pp. 129–133.
- M.  Hu,  K.  Wongsuphasawat,  and  J.  Stasko,  “Visualizing  social  mediacontent with sententree,”IEEE Transactions on Visualization and Com-puter Graphics, vol. 23, no. 1, pp. 621–630, 2017

**Comment by xillig** [comment]
hi @sara-02 
Thanks a lot for your suggestions. We are doing the review process with JOSS for the first time. Should we just incorporate your comments and then push a new version of the paper? Or how does this usually work? Thank you!

**Comment by xillig** [comment]
Hi @trallard 
Thanks for initiating the review process, I noticed that the issue contains three review check-lists, but @linuxscout is not an assignee of the issue. Will he also review the paper?

**Comment by sara-02** [comment]
> hi @sara-02
> Thanks a lot for your suggestions. We are doing the review process with JOSS for the first time. Should we just incorporate your comments and then push a new version of the paper? Or how does this usually work? Thank you!

Hye @xillig there is no fixed process, you can keep incorporating the changes as they are suggested or wait for other reviewers to chime in as well. However, if we incorporate the changes on the go, then it will be easier for others when they start reviewing it, they will start from the improved version.

**Comment by aozorahime** [comment]
Hi @xillig I also agree with @sara-02 about referring some works regarding twitter data visualization and there's no mention about installation process and describe how this software compares to other commonly-used packages. You may read or look for some JOSS papers which has been published so you can revise the paper directly.

**Comment by xillig** [comment]
Hi @aozorahime 
Thanks for the feedback. We will include the suggestions asap.

**Comment by xillig** [comment]
Hi @sara-02 and @aozorahime,
we uploaded an updated version of our paper, embedding your suggestions.

**Comment by sara-02** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02507/joss.02507/10.21105.joss.02507.pdf)

**Comment by xillig** [comment]
Dear @sara-02, @aozorahime, @linuxscout and @trallard,
we hope that you are all doing well. Can we provide any further assistance regarding the open points? Please also consult the documentation website (https://ttlocvis.readthedocs.io/en/latest/) if you may have questions or write us at any time.

**Comment by aozorahime** [comment]
sure @xillig :+1:

**Comment by xillig** [comment]
Dear @trallard, @sara-02, @aozorahime,
We hope that you are all well and not too severely affected by the current Covid situation. For us a decision about our paper is quiet important in terms of funding applications. Given that the extended review timeline of six weeks is already past since a while, we would kindly like to ask you if you could give us an indication as to when we can expect a conclusion of the review? 

Thank you!
xillig

**Comment by aozorahime** [comment]
hi @xillig I am sorry I am totally forgot to check the remaining points. but I think its done. maybe we can ask the editor @trallard  to process this review

**Comment by sara-02** [comment]
Hey @xillig  I am almost done with my review as well, will add the final points in a day or two. Sorry this got delayed.

**Comment by xillig** [comment]
Dear @sara-02, dear @aozorahime,
Thank you very much for your quick answers! We looking forward to get your review @sara-02.
Thanks and all the best!

**Comment by sara-02** [comment]
@xillig rest of the features and documentation are well put, but where are the commands to run the test listed?
I see you have a test folder but how to operate on it?

**Comment by sara-02** [comment]
As we have to cover that under `Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?`

**Comment by sara-02** [comment]
Also, I feel we can better structure the content of the paper instead of putting everythhing under the summary heading.

**Comment by sara-02** [comment]
So, here is a suggested breakdown:
```
Summary: Para 1
About the package: para 2(In general...) to para 5 (Above this, the spatial distribution...)
Comparison with existing tools: Para 6 onwards 
```

**Comment by xillig** [comment]
Hi @sara-02,
you can find the guide for how to run the example files in the documentation under the following link: https://ttlocvis.readthedocs.io/en/latest/examples/ 
Please note that you can't use the TwitterStreamer without an Twitter Developer account, all other functions are usable with the example data. Please also note that the example data will not return any meaningful analytical results since it is for functional demonstration and tutorial purposes only. 

Regarding your suggested breakdown, we will review the paper in regards to your feedback asap.

Thank you and all the best!

**Comment by sara-02** [comment]
Hey, I have reviewed this documentation, my concern is regarding running unit tests.

**Comment by sara-02** [comment]
Is there a way we can test the modules with some dummy twitter data?

**Comment by xillig** [comment]
Hey, @sara-02,
Thanks for the clarification,
> 
> 
> As we have to cover that under `Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?`

There is no automated unit testing available, since our background is statistics and not computer science, so that we are not firm with unit testing. That's why we decided for the second option to provide manual testing steps as outlined in the "Usage and Example" guideline, to explain how all functions are used. 

> 
> 
> Hey, I have reviewed this documentation, my concern is regarding running unit tests.
> Is there a way we can test the modules with some dummy twitter data?

Using the example data provided (which can be found here: https://github.com/xillig/TTLocVis/tree/master/example_files), you can   run all the features of TTLocVis except for the TwitterStreamer class (Which was produced by the TwitterStreamer class). For example you can test the Cleaner class:

from TTLocVis.module import Cleaner
c = Cleaner(load_path=r'path-to-a-JSON-file-folder')
print(c.raw_data)
c.saving(r'path-to-where-the-cleaned-data-shall-be-saved')

where r'path-to-a-JSON-file-folder' should point to the example folder. 


I hope this answers your questions

**Comment by xillig** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02507/joss.02507/10.21105.joss.02507.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02507/joss.02507/10.21105.joss.02507.pdf) :page_facing_up: :point_left:

**Comment by xillig** [comment]
Hey @sara-02,

we updated the paper.

**Comment by sara-02** [comment]
@xillig and @trallard checks are complete from my side, and my concerns have been dually addressed.

**Comment by xillig** [comment]
Dear @trallard, @sara-02, @aozorahime,
 thank you very much for completing the review and for all the great comments. This really helped a lot to improve the paper and we really appreciate that you invested so much time despite of the COVID-19 situation.

 @trallard: What are the next steps in the publication process? 

On the JOSS Website we find the following instructions:
>
>
> Upon successful completion of the review, authors will make a tagged release of the software, and deposit a copy of the repository with a data-archiving service such as Zenodo or figshare, get a DOI for the archive, and update the review issue thread with the version number and DOI.

 Can we proceed with this? 

Thank you all very much!

**Comment by xillig** [comment]
Hi @tallard, 
now that @sara-02 and @aozorahime completed their reviews and helped us to really improve TTLocVis a lot, it would really great to make further progress with the review. How can we proceed? What are the next steps? Also @sara-02 and @aozorahime do you perhaps know what to do now?
  
Thank you all!

xillig

**Comment by sara-02** [comment]
Hey @xillig unfortunetly I am not aware of the next steps.

**Comment by xillig** [comment]
Hi @trallard,
we already created a tagged release on Zenodo. This is the DOI: https://zenodo.org/badge/latestdoi/258153686

Additionally, we would like to point out once more, that @linuxscout might be assigned as a Reviewer (he/she has a checklist above) but never has been a participant in this issue and probably never reviewed the project. Nevertheless, we do not think this is a problem since there are only two reviews nessesary to move forward, which are by now successfully completed by @sara-02 and @aozorahime. 

We hope this helps to move the case forward.
Thank you!

**Comment by linuxscout** [comment]
Hi @xillig,
I'm assigned as a Reviewer, but I accepted to review the paper if there are none to do this. When I saw that there are two reviewers, I don't make any action, I follow all the thread, but I think it's not necessary to interact.

If you need my review, I can do it, thanks. See you for other papers.

**Comment by xillig** [comment]
Hi @linuxscout,
thanks for your message. We agree that no further (third) review is necessary and your valueable work as a reviewer is more important for the numerous other submissions to JOSS!

Thus if @trallard agrees we would proceed with the publication process.

**Comment by trallard** [comment]
Hey all thanks for your patience and your time doing the reviews. I am going to move forward with the next steps.

@xillig can you please make sure that the software version is up to date and confirm it here?

**Comment by trallard** [comment]
@whedon set 10.5281/zenodo.4108270 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4108270" target="_blank">10.5281/zenodo.4108270</a> is the archive.

**Comment by trallard** [comment]
@whedon generate pdf

**Comment by trallard** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02507/joss.02507/10.21105.joss.02507.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02507/joss.02507/10.21105.joss.02507.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1145/2484028.2484166 may be a valid DOI for title: Improving LDA Topic Models for Microblogs via Tweet Pooling and Automatic Labeling
- 10.1016/j.future.2018.01.052 may be a valid DOI for title: From social networks to emergency operation centers: A semantic visualization approach
- 10.1007/978-3-319-31232-3_82 may be a valid DOI for title: TweeProfiles3: visualization of spatio-temporal patterns on Twitter

INVALID DOIs

- None
```

**Comment by trallard** [comment]
@xillig  there seem to be some DOIs missing, would you be able to check these, please? 

Also, I sent a PR with some edits <https://github.com/xillig/TTLocVis/pull/3>

**Comment by xillig** [comment]
@whedon set 10.5281/zenodo.4108270 as archive

**Comment by whedon** [comment]
I'm sorry @xillig, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by xillig** [comment]
Dear @trallard,
Thank you for all your efforts. We included the DOIs of the references and fixed authorship issue in zenodo by making a new release. We also merged your changes into master. We can also confirm that the software version is up to date: The version number is 1.0.4, with the same DOI as before: https://zenodo.org/badge/latestdoi/258153686

Thanks to everyone for their contributions.

All the best,
Gillian, Christoph and Benjamin

**Comment by trallard** [comment]
@whedon check references

**Comment by trallard** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2484028.2484166 is OK
- 10.1016/j.future.2018.01.052 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by trallard** [comment]
@whedon set 10.5281/zenodo.4115669 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4115669" target="_blank">10.5281/zenodo.4115669</a> is the archive.

**Comment by trallard** [comment]
@whedon set 1.0.4 as version

**Comment by whedon** [comment]
OK. 1.0.4 is the version.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02507/joss.02507/10.21105.joss.02507.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02507/joss.02507/10.21105.joss.02507.pdf) :page_facing_up: :point_left:

**Comment by trallard** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02507/joss.02507/10.21105.joss.02507.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02507/joss.02507/10.21105.joss.02507.pdf) :page_facing_up: :point_left:

**Comment by trallard** [comment]
@xillig everything seems in order now. I will go ahead and pass to our EiC for the final steps through publication.

@sara-02 ,  @aozorahime thanks for your time and effort as part of the review. Your contributions are massively appreciated. ✨

**Comment by trallard** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2484028.2484166 is OK
- 10.1016/j.future.2018.01.052 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1839

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1839, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by aozorahime** [comment]
I am so happy to be part of this. Thank you everyone. And good luck for @xillig  for the next publication journey 😁

**Comment by xillig** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @xillig, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by xillig** [comment]
Thank you everyone for their work!

@trallard, would you kindly accept the submission?

**Comment by trallard** [comment]
Hi @xillig I am afraid only our editors in chief can do this. They should have received a notification and will deal with this promptly

**Comment by kyleniemeyer** [comment]
Hi @xillig, I'm the EIC on duty this week, doing some final checks before publishing. Can 

- [ ] Please edit the Zenodo archive author list to match the paper—it looks like @trallard got included!
- [ ] Your article is missing an explicit [Statement of Need section](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), which we have begun requiring for articles. Can you please add? You may be able to use existing text in the paper.
- [ ] In the last paragraph of the "Comparison with existing tools" section, I think there is an extraneous comma before the citation.
- [ ] The Kong 2020 reference seems to be missing some details
- [ ] Are there DOIs available for the other references?

**Comment by xillig** [comment]
Hi @kyleniemeyer,

thank you very much for your feedback. Unfortunatly, for the two references that have no DOIs now, there are none available to your knowledge. Appart from that, we have incorporated all of your suggested points. Please let us know if we can do anything else or move forward. 

Thanks to everyone!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02507/joss.02507/10.21105.joss.02507.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02507/joss.02507/10.21105.joss.02507.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.4133399 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4133399" target="_blank">10.5281/zenodo.4133399</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2484028.2484166 is OK
- 10.1162/jmlr.2003.3.4-5.993 is OK
- 10.1145/2492517.2492639 is OK
- 10.1016/j.future.2018.01.052 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1866

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1866, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1320785306283614211) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1867
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02507](https://doi.org/10.21105/joss.02507)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @xillig on your article's publication in JOSS!

Many thanks to @sara-02 , @linuxscout, and @aozorahime for reviewing this submission, and @trallard for editing it.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02507/status.svg)](https://doi.org/10.21105/joss.02507)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02507">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02507/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02507/status.svg
   :target: https://doi.org/10.21105/joss.02507
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02507/status.svg)](https://doi.org/10.21105/joss.02507)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by xillig** [comment]
Thank you everyone for your awesome work! 

Best wishes,
Gillian, Christoph, Benjamin
