### ISSUE TITLE
[PRE REVIEW]: hankl: A lightweight Python implementation of the FFTLog algorithm for Cosmology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2508]
**Submitting author:** @minaskar (<a href="http://orcid.org/0000-0001-9489-4612">Minas Karamanis</a>)
**Repository:** <a href="https://github.com/minaskar/hankl" target ="_blank">https://github.com/minaskar/hankl</a>
**Version:** v1.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @minaskar. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@minaskar if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1046/j.1365-8711.2000.03071.x is OK

MISSING DOIs

- https://doi.org/10.1016/0021-9991(78)90107-9 may be missing for title: Numerical Fourier and Bessel transforms in logarithmic variables

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02508/joss.02508/10.21105.joss.02508.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.16 s (314.1 files/s, 128554.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      14           2200           2243           8331
SVG                              1              0              0           2671
CSS                              6            312             52           1180
HTML                             7            822             21            917
Python                           9            145            257            321
reStructuredText                 6            115             47            187
Markdown                         2             31              0             82
TeX                              1              3              0             41
DOS Batch                        1              8              1             26
YAML                             1              3              0             18
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            49           3643           2628          13783
-------------------------------------------------------------------------------


Statistical information for the repository '2508' was gathered on 2020/07/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Minas Karamanis                 46         13944            447          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Minas Karamanis           13497           96.8          0.0               17.02
```

**Comment by minaskar** [comment]
A few suggestions based on the list of reviewers that you mentioned are: ziotom78, HeloiseS, eschnett

**Comment by kthyng** [comment]
Hi @minaskar. Thank you for your submission. However, the JOSS editorial board has determined that it does not meet the bar of [_substantial scholarly effort_](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

If you continue to develop this work, we would be happy to reconsider it as a submission in the future.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by minaskar** [comment]
Hi @kthyng thank you for reviewing our work. Could you please elaborate exactly which requirement it does not meet?

According to the docs that you mentioned:

> Your software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or **makes addressing research challenges significantly better (e.g., faster, easier, simpler).**

hank is almost 500% faster than existing methods, significantly easier to use, and  trivially simple to configure. An analysis that would usually take a few hours to complete can be done in a matter of minutes using hankl. Furthermore, the user does not need to extrapolate the transformed function themselves since this is done automatically.

Thank you for your consideration.

Minas

**Comment by kthyng** [comment]
Hi @minaskar. A JOSS submission needs to be a substantial scholarly effort, as in, the equivalent effort of a traditionally publishable unit in research and/or academics. The link I posted gives guidelines, for example:

> Total lines of code (LOC). Submissions under 1000 LOC will usually be flagged, those under 300 LOC will be desk rejected.

Your submission has 321 lines of Python code, which is just above the desk reject level but still very small for a JOSS submission. Note that there are other great ways to publish your software; some are listed [here](https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages).
