### ISSUE TITLE
[REVIEW]: Grafoscopio: A moldable tool for literate computing and reproducible research

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#251]
**Submitting author:** @offray (<a href="http://orcid.org/0000-0002-4640-6984">Offray Vladimir Luna Cárdenas</a>)
**Repository:** <a href="http://mutabit.com/repos.fossil/grafoscopio/" target ="_blank">http://mutabit.com/repos.fossil/grafoscopio/</a>
**Version:** 1.3.8
**Editor:** @arfon
**Reviewer:** @SergeStinckwich
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1038147" target="_blank">10.5281/zenodo.1038147</a>

## Status

[![status](http://joss.theoj.org/papers/c92ed13fa746bc681081f9b31678841b/status.svg)](http://joss.theoj.org/papers/c92ed13fa746bc681081f9b31678841b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c92ed13fa746bc681081f9b31678841b"><img src="http://joss.theoj.org/papers/c92ed13fa746bc681081f9b31678841b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c92ed13fa746bc681081f9b31678841b/status.svg)](http://joss.theoj.org/papers/c92ed13fa746bc681081f9b31678841b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="http://mutabit.com/repos.fossil/grafoscopio/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="http://mutabit.com/repos.fossil/grafoscopio/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.3.8)?
- [x] **Authorship:** Has the submitting author (@offray) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @SergeStinckwich it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by SergeStinckwich** [comment]
@offray I can't install Grafoscopio at the moment. I'm using Pharo 5.0 with PharoLauncher. During the installation, there is a #DNU: OrderedCollection>>asSymbol

Can you add also a plain-text LICENSE file ? There is none at the moment.

**Comment by SergeStinckwich** [comment]
@arfon I find the paper on Grafoscopio repository. But there is no direct link from a review to the paper ?

**Comment by arfon** [comment]
> @arfon I find the paper on Grafoscopio repository. But there is no direct link from a review to the paper ?

We generally compile the paper at the end of the review. If you can find the `paper.md` file in the repository can you review it there?

**Comment by offray** [comment]
@SergeStinckwich 

I have solved the installation issue (software installation was ending, but the documentation installation was rising errors). Also, there is already a plain LICENSE text file already included in the repository at [1], but I have made it more explicit at the intro page [2] of the repository. 

[1] http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Docs/En/Licenses/grafoscopio-mit.md
[2] http://mutabit.com/repos.fossil/grafoscopio/

**Comment by SergeStinckwich** [comment]
Thank you @offray I was able to install Grafoscopio on my computer.

There is still some problems :
- part of the interface is in Spanish. For example, when I try Update / Dataviz
- after installing Dataviz, I was not able to do : ```OffshoreLeaksDB openIntroNotebook``` because apparently files are not at the correct place.
- Help > Manual (pdf) open no pdf document
- sometimes after using the keyboard and the UI in order to move in a notebook, I have the following error: ```MessageNotUnderstood: receiver of "selectedMorphList" is nil

**Comment by offray** [comment]
@SergeStinckwich 

Please update to the last development version from the Update docking bar menu or Monticello to see the issues solved. I plan to package it in a minor release soon, so the default installation includes all the fixes.

Some more detailed comments about your comment:

> part of the interface is in Spanish. For example, when I try Update / Dataviz

Fixed.

> after installing Dataviz, I was not able to do : `OffshoreLeaksDB openIntroNotebook` because apparently files are not at the correct place

I can't reproduce that bug. All documents are downloaded here. After updating Dataviz and documentation the bug still persists? Can you send me a message log in that case?

> Help > Manual (pdf) open no pdf document

Fixed. Now it relies on `WebBrowser openOn:` which makes it more crossplatform and removes unnecessary dependencies.

>  sometimes after using the keyboard and the UI in order to move in a notebook, I have the following error: ```MessageNotUnderstood: receiver of "selectedMorphList" is nil

Yes, this is a known bug reported in the manual (and asked in the Pharo mailing list). I have made this also visible in the readme and pointed to the full manual in the usage instructions.

**Comment by SergeStinckwich** [comment]
Thank you Offray for solving the issues.

Do you have some kind of API documentation as required by the documentation reviewing criteria ?

**Comment by SergeStinckwich** [comment]
I have update Dataviz and when I try ```OffshoreLeaksDB openIntroNotebook```, the files are not found (see picture below). Apparently the dataviz files are not at the correct place. They are located close to the image file.

![screen shot 2017-05-09 at 12 14 59](https://cloud.githubusercontent.com/assets/327334/25846241/60642376-34b1-11e7-9875-f4749b068d4f.png)

**Comment by offray** [comment]
Hi,

Well, is just the normal "API documentation" in the Pharo/Smalltalk way, 
as stated in the Readme: a command to browse the protocols inside the 
image.

 > Because Grafoscopio inhabits a full live coding environment, it 
follows the custom of making the API documentation available inside a 
dynamic environment, instead in some static web page. To open the 
Grafoscopio package inside the system browser, and see the messages 
organized by protocols execute:

1
2
3
4
5

	

|"Browser the notebook API" GrafoscopioNotebook browse. "Browse the 
document tree API" GrafoscopioNode browse|

I don't know if a static file API documentation would be appropriate... 
I think that is someway misses the point in a dynamic environment like 
Pharo, because, as I have learned, static API documentation gets easily 
obsolete. Let me know if you consider a static API file is mandatory and 
if you can point me a way to generate it from the image, or if inviting 
to "read the API" by browsing protocols in the image fits better the 
Pharo culture and just be pointed in the image.

Cheers,

Offray

**Comment by SergeStinckwich** [comment]
From me this is not mandatory, but the reviewing criteria ask about that.

I know Pharo is a live environment but I guess for people outside the community this will be better to have a static version of the API, without having to launch the tool. This will ease also the work of search engine like the Google one also. I know this is possible to generate an HTML file documentation from Pharo classes. Maybe ask the community about that.

There is a few classes without any class comments. Can you fix that ?

**Comment by offray** [comment]
Hi Serge,

It seems that something in the documentation dowloanding is failing. 
Could you please try to update Grafoscopio, Dataviz and Documentation 
from the "Update" dockbar menu (in that order) to see if the problem is 
fixed?

Thanks,

**Comment by offray** [comment]
Hi,


On 09/05/17 05:45, Serge Stinckwich wrote:
>
> From me this is not mandatory, but the reviewing criteria ask about that.
>
> I know Pharo is a live environment but I guess for people outside the 
> community this will be better to have a static version of the API, 
> without having to launch the tool. This will ease also the work of 
> search engine like the Google one also.
>

OK. I find so little documentation packaged like this in the Pharo 
projects and community (I mean as external static API documentation 
files) that feels really alien, and the community seems fine of not 
having static API docs indexed in search engines.

> I know this is possible to generate an HTML file documentation from 
> Pharo classes. Maybe ask the community about that.
>
> There is a few classes without any class comments. Can you fix that ?
>
I'll ask and fix the comments.

Thanks,

Offray

**Comment by SergeStinckwich** [comment]
Now when I try to update Documentation, I have the following error

![screen shot 2017-05-09 at 15 34 47](https://cloud.githubusercontent.com/assets/327334/25853460/1e5765ee-34cd-11e7-9387-eb3e9acfbecd.png)

**Comment by offray** [comment]
Fixed uncommented classes:

> Name: Grafoscopio-OffrayLuna.281
  Author: OffrayLuna
  Time: 26 May 2017, 10:25:17.580541 am
  UUID: e8cb7fae-d00c-0d00-bdc7-ae1f045b3609
  Ancestors: Grafoscopio-OffrayLuna.280
  Fixing uncommented classes for the JOSS paper.
  See details at:
  https://github.com/openjournals/joss-reviews/issues/251#issuecomment-300128786

For documentation installation issues, like the one reported about NeoJSON dependency not being installed properly, I'm waiting the upcoming Pharo 6 official release (which is my current Grafoscopio development platform) to test against it and update Grafoscopio Manual and Readme to Pharo 6.

**Comment by arfon** [comment]
@SergeStinckwich @offray - how are we getting on here?

**Comment by SergeStinckwich** [comment]
Waiting for @offray modifications.

**Comment by arfon** [comment]
> Waiting for @offray modifications.

:+1:

**Comment by arfon** [comment]
Friendly reminder @offray :grin:

**Comment by offray** [comment]
Hi Arfon,

Thanks for your reminder. I'm working on improvements following Serge
comments about improved installation and hopefully I will also deal with
exporting API documentation (now is included inside Pharo/Smalltalk as
usual). They should be packaged and ready to review at the beginning of
next week.

Cheers,

Offray

**Comment by offray** [comment]
@SergeStinckwich, classes have now class comments and documentation installation and updating is working, including the associated NeoJSON package prerequisites. I'm still [waiting for community support](http://forum.world.st/API-docs-as-HTML-tt4959416.html) on how to export the API as HTML. The package for that is unmaintained and even lacking of a `readme` file to start with (maybe because is so alien to community that kind of API documentation publishing). @arfon Could you give us some light here? Is API HTML publication mandatory even in environments where that is not the usual practice, like Pharo/Smalltalk ?

Thanks for your constructive comments and continuous interest.

**Comment by arfon** [comment]
> @arfon Could you give us some light here? Is API HTML publication mandatory even in environments where that is not the usual practice, like Pharo/Smalltalk ?

If you're following standard/best/expected practice for Pharo/Smalltalk communities then I think we're good here.

**Comment by arfon** [comment]
@SergeStinckwich - I think this is ready for you to take another look when you get a chance.

**Comment by SergeStinckwich** [comment]
There are still some methods and class comments missing, but the quality of the documentation is enough I guess.

**Comment by SergeStinckwich** [comment]
@arfon what is the meaning of "References: Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?" ?

**Comment by arfon** [comment]
> @arfon what is the meaning of "References: Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?" ?

It just means that if there's an entry in `paper.bib` it should ideally have a DOI for it. Not all references have a DOI but the vast majority of published papers do for example.

**Comment by SergeStinckwich** [comment]
@offray can you add DOI to the papers you cite as references ?

**Comment by offray** [comment]
@SergeStinckwich I have updated the ISBN for two book references in the [paper.bib][bib-file] file. Other few references there are blog post or drafts without a DOI. 

When I run ``SystemOrganization uncommentedClassesIn: 'Grafoscopio'`` I get an empty array. I can find any undocumented class in the Grafoscopio Package.

Thanks,

[bib-file]: http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Docs/En/Papers/JOSS/paper.bib

**Comment by SergeStinckwich** [comment]
ok great !

**Comment by arfon** [comment]
@SergeStinckwich @offray - how are we doing here? @SergeStinckwich are we good to accept?

**Comment by SergeStinckwich** [comment]
yes :-)

**Comment by arfon** [comment]
@offray - can you remind me how to download the sourcecode for this project? I can't seem to figure out how to download it from here http://smalltalkhub.com/#!/~Offray/Grafoscopio/

**Comment by offray** [comment]
Arfon, Thanks for testing and your interest.

SmalltalkHub is more for insiders who are kind of familiar with
installing stuff in Pharo. A more detailed procedure is this: first you
will need to download and launch Pharo from [1]. After that, open a
playground and execute the code in [2]. You can find detailed install
and use instruction in the Manual [3], or a general overview in the
documentation repository [4]

[1] http://pharo.org/
[2] http://smalltalkhub.com/#!/~Offray/Grafoscopio/
<http://smalltalkhub.com/#%21/%7EOffray/Grafoscopio/>
[3]
http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Docs/En/Books/Manual/manual.pdf
[4] http://mutabit.com/repos.fossil/grafoscopio/

**Comment by arfon** [comment]
@offray - to clarify, I just need the `paper.md` and `paper.bib` files to complete this submission (and acceptance into JOSS).

**Comment by arfon** [comment]
Friendly reminder on this @offray.

**Comment by offray** [comment]
Hi @arfon.

Its strange. I had answered by mail send on 04/10/17, but seems that the answer never came. Here it is again:

========

Here are the two files:
- http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Docs/En/Papers/JOSS/paper.md
- http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Docs/En/Papers/JOSS/paper.bib

Cheers,

========

**Comment by arfon** [comment]
Thanks @offray. Unfortunately I'm not able to get a 'clean' version of http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Docs/En/Papers/JOSS/paper.md as the website seems to be adding HTML tags to the content. Could you please email me a tarball or something similar of the complete repository to arfon.smith@gmail.com?

**Comment by SergeStinckwich** [comment]
Yes same problem here @offray I have a mix of markup with your website ...

**Comment by offray** [comment]
@arfon @SergeStinckwich  The Fossil default Markdown view as HTML is getting into the way. This links allow you to see the last versions of paper.md and paper.bib:

- md file: http://mutabit.com/repos.fossil/grafoscopio/raw/Docs/En/Papers/JOSS/paper.md?name=92f33ca0c58b055b66e7715e7c33c930896166f0 
- bib file: http://mutabit.com/repos.fossil/grafoscopio/finfo?name=Docs/En/Papers/JOSS/paper.bib

Let me know if you still need a copy of all the repository in a compressed file.

**Comment by arfon** [comment]
@offray - that should work ok. Also, could you share a direct link to the image in a paper (side-by-side.png)?

Finally, could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by offray** [comment]
@arfon  Done. The last version of `paper.md`, including the absolute path to the image is in [1]. The Zenodo DOI is https://doi.org/10.5281/zenodo.1038147, as published in [2]

[1] http://mutabit.com/repos.fossil/grafoscopio/raw/Docs/En/Papers/JOSS/paper.md?name=476551488ea47ba683c56db3df9667dcb97cd825 
[2] https://zenodo.org/record/1038147#.WfN04nXRZnI

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1038147 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1038147" target="_blank">10.5281/zenodo.1038147</a> is the archive.

**Comment by arfon** [comment]
@SergeStinckwich - many thanks for your review here ✨ 

@offray - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00251 ⚡️ 🚀 💥

**Comment by offray** [comment]
@arfon @SergeStinckwich thank you both for this!

**Comment by offray** [comment]
Upps... a Minor Issue. My family name should be just "Luna", or "Luna Cárdenas" (not "Cárdenas"). As usual in Latin American countries, your family name is composed from your father's family name ("Luna")  and your mother's family name ("Cárdenas").

**Comment by arfon** [comment]
> Upps... a Minor Issue. My family name should be just "Luna", or "Luna Cárdenas" (not "Cárdenas"). As usual in Latin American countries, your family name is composed from your father's family name ("Luna") and your mother's family name ("Cárdenas").

No problem. I've updated the paper and the website to "Luna Cárdenas".

**Comment by offray** [comment]
Thanks.
