### ISSUE TITLE
[PRE REVIEW]: Bacting: a next generation, command line version of Bioclipse

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2510]
**Submitting author:** @egonw (<a href="http://orcid.org/0000-0001-7542-0286">Egon Willighagen</a>)
**Repository:** <a href="https://github.com/egonw/bacting" target ="_blank">https://github.com/egonw/bacting</a>
**Version:** 0.0.11
**Editor:** @majensen
**Reviewers:** @Zethson, @arcuri82
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @egonw. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @trallard.

@egonw if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (209.5 files/s, 23737.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                            19            360            982           1969
Maven                           15             85              0            732
Markdown                         2             57              0             97
YAML                             1              4              0             11
Groovy                           1              3              0              6
-------------------------------------------------------------------------------
SUM:                            38            509            982           2815
-------------------------------------------------------------------------------


Statistical information for the repository '2510' was gathered on 2020/07/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Egon Willighagen                64          6474           3163          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Egon Willighagen           3311           51.1          7.5               29.66
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2510 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch devel/0.0.13

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch devel/0.0.13. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02510/joss.02510/10.21105.joss.02510.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@egonw thanks for this submission. I am reviewing the suitability of this submission for JOSS and will also look for editors to handle it. 
In the mean time can you please describe, for the record, the difference between the current submission and this paper to clarify this is not a duplicate publication: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-10-397

**Comment by Kevin-Mattheus-Moerman** [comment]
@trallard @majensen @will-rowe @csoneson is one of you able to handle this submission? Thanks!

**Comment by egonw** [comment]
Potential reviewers: zethson, reality (collaborators on a EU project, so probably not), 7omasz, arcuri82

**Comment by Kevin-Mattheus-Moerman** [comment]
@egonw thanks for those suggestion. Which ones exactly are collaborators?

**Comment by egonw** [comment]
> In the mean time can you please describe, for the record, the difference between the current submission and this paper to clarify this is not a duplicate publication: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-10-397

The Bioclipse 2 paper is still about the Eclipse-based version, not about the command line version and suffers from the limitations outlined in the "Statement of Need" section.

**Comment by egonw** [comment]
> @egonw thanks for those suggestions. Which ones exactly are collaborators?

reality, whom I work together with in the [NanoCommons](https://github.com/nanocommons) project on ontologies.

**Comment by Kevin-Mattheus-Moerman** [comment]
@galessiorob is this submission something you could handle?

**Comment by egonw** [comment]
I would also not mind having someone of the original Bioclipse team look at it. They have not contributed to this adaption of it, e.g. jonalv or goglepox as they know the ins and outs of the technology, but obviously have an academic CoI.

**Comment by majensen** [comment]
@Kevin-Mattheus-Moerman I can backstop for this submission, if others are unable.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by Kevin-Mattheus-Moerman** [comment]
@majensen note the various reviewers recommended :point_up: in a couple of comments.

**Comment by majensen** [comment]
@goglepox - Would you be willing to review [this package](#2520) for the [Journal of Open Source Software](https://joss.theoj.org)? Your Bioeclipse expertise would be extremely valuable. Please have a look at [these reviewer steps](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and let us know here whether you would have an interest. Thanks for your consideration --@majensen

**Comment by majensen** [comment]
@Zethson - would you be willing to share your expertise in a review of [this package](#2510) for the [Journal of Open Source Software](https://joss.theoj.org) ? It is meant to improve Bioeclipse build management and command line usability, among other things. Please have a look at these [reviewer steps](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and let us know here whether you would have an interest. 
Thanks for your consideration --@majensen

**Comment by egonw** [comment]
@majensen, can you please email me asap on my first.lastname @ gmail? thanks.

**Comment by Zethson** [comment]
Yes, I would do it. ETA 14 days is fine?  Saturday, 25 July 2020, 08:29PM +02:00 from Mark Jensen  notifications@github.com :

**Comment by majensen** [comment]
@Zethson that would be great. Thanks very much

**Comment by majensen** [comment]
@whedon add @Zethson as reviewer

**Comment by whedon** [comment]
OK, @Zethson is now a reviewer

**Comment by majensen** [comment]
All, will be getting additional review invites out over next couple days. Thanks for yr patience

**Comment by majensen** [comment]
@jonalv - Would you be willing to review [this work](#2510) for the [Journal of Open Source Software](https://joss.theoj.org)? Your expertise in Bioeclipse would be extremely valuable here. An overview of reviewing for the journal (performed openly on Github) is [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). I appreciate your consideration very much --@majensen

**Comment by jonalv** [comment]
Hi I can not get your link to work but from the title I see this is about
Bacting, since I know Egon Willighagen is behind a project with that name I
am hesitant as to whether I really am impartial. I have worked closely with
him, co-authoring a book with him and helped him move twice :)

// Jonathan

**Comment by majensen** [comment]
@jonalv  - I understand, having helped @egonw move might bias your review negatively  😄
For me, your expertise is very important since it deals very directly with the application, and you have not directly contributed code to Bacting. Since you have declared possible conflict, I can take that into account. 

@Kevin-Mattheus-Moerman - can you please comment here from the AIC point of view?

**Comment by danielskatz** [comment]
If the co-authoring has been recent (last 4 years), that's another conflict.  My impression is that we should find alternative reviewers unless there is no other choice, or if @jonalv does review, then have at least 2 other reviewers.

**Comment by majensen** [comment]
Ok @danielskatz .

Thanks for your consideration @jonalv - If you or @egonw can possibly recommend someone with Bioeclipse experience but without close collaboration, that would great. Difficult I'm sure.

**Comment by egonw** [comment]
@majensen, reviewers do not need Bioclipse experience. The build system is a regular Maven installation. Anyone with Maven experience can build, test, and use this adaption of Bioclipse.

Please see also my original list at https://github.com/openjournals/joss-reviews/issues/2510#issuecomment-663096346 (but plz exclude Luke).

**Comment by majensen** [comment]
Thanks @egonw - that makes sense.

**Comment by majensen** [comment]
@arcuri82, would you consider reviewing this work (https://github.com/openjournals/joss-reviews/issues/2510) for [the Journal of Open Source Software](https://joss.theo4j.org)? Your java expertise would be greatly appreciated. Guidelines for reviewing are [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). 
Thanks very much for considering! --@majensen

**Comment by arcuri82** [comment]
@majensen: Hi, yes, I can review it. Busy period (start of teaching semester)... so I do not think I ll have time to start the review before at least 2 weeks, but should be able to complete within the given 6 weeks

**Comment by majensen** [comment]
@arcuri82 thanks so much; that will be fine. Very much appreciated

**Comment by majensen** [comment]
@whedon add @arcuri82 as reviewer

**Comment by whedon** [comment]
OK, @arcuri82 is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2558.

**Comment by majensen** [comment]
@egonw @arcuri82 @Zethson we will perform the review over in #2558 - thanks!
