### ISSUE TITLE
[PRE REVIEW]: Off-resonance CorrecTion OPen soUrce Software (OCTOPUS)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2511]
**Submitting author:** @imr-framework (<a href="http://orcid.org/0000-0002-1141-2049">Marina Manso Jimeno</a>)
**Repository:** <a href="https://github.com/imr-framework/OCTOPUS" target ="_blank">https://github.com/imr-framework/OCTOPUS</a>
**Version:** 0.1.4
**Editor:** @jni
**Reviewers:** @puolival
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @imr-framework. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@imr-framework if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (375.8 files/s, 32308.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            352            748           1014
Markdown                         6             75              0            224
TeX                              1             14              0            199
reStructuredText                 6             42             58             39
DOS Batch                        1              8              1             26
INI                              1              2              0             15
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            33            497            814           1526
-------------------------------------------------------------------------------


Statistical information for the repository '2511' was gathered on 2020/07/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Marina Manso Jimeno             29          7691           5972           97.19
Mmj94                            1           395              0            2.81

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Marina Manso Jimeno        1898           24.7          0.8                9.48
Mmj94                       216           54.7          0.0                9.72
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2217/iim.10.33 is OK
- 10.1109/42.108599 is OK
- 10.1002/1522-2594(200102)45:2<269::AID-MRM1036>3.0.CO;2-5 is OK
- 10.1002/mrm.21599 is OK
- 10.1109/42.781014 is OK
- 10.1109/42.3926 is OK
- 10.1002/mrm.1910250210 is OK
- 10.1002/mrm.1910370523 is OK
- 10.1002/mrm.22428 is OK
- 10.1016/j.mri.2017.07.004 is OK
- 10.1016/j.neuroimage.2011.09.015 is OK
- 10.1109/TMI.2002.808360 is OK
- 10.1109/TSP.2005.853152 is OK
- 10.1016/j.mri.2018.03.008 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02511/joss.02511/10.21105.joss.02511.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
👋 @jni - would you be willing to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @jni as editor

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by jni** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jni

**Comment by jni** [comment]
@whedon assign @puolival as reviewer

**Comment by whedon** [comment]
OK, @puolival is now a reviewer

**Comment by jni** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2578.
