### ISSUE TITLE
[REVIEW]: RK-Opt: A package for the design of numerical ODE solvers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2514]
**Submitting author:** @ketch (<a href="http://orcid.org/0000-0002-1212-126X">David Ketcheson</a>)
**Repository:** <a href="https://github.com/ketch/RK-Opt" target ="_blank">https://github.com/ketch/RK-Opt</a>
**Version:** v1.0.3
**Editor:** @diehlpk
**Reviewers:** @gardner48, @debdeepbh, @emconsta
**Archive:** <a href="https://doi.org/10.5281/zenodo.4146740" target="_blank">10.5281/zenodo.4146740</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9cb393c408b6ee3b6686fdb63a98ce74/status.svg)](https://joss.theoj.org/papers/9cb393c408b6ee3b6686fdb63a98ce74)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9cb393c408b6ee3b6686fdb63a98ce74"><img src="https://joss.theoj.org/papers/9cb393c408b6ee3b6686fdb63a98ce74/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9cb393c408b6ee3b6686fdb63a98ce74/status.svg)](https://joss.theoj.org/papers/9cb393c408b6ee3b6686fdb63a98ce74)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ketch/RK-Opt" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gardner48 & @debdeepbh & @emconsta, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @diehlpk know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ketch/RK-Opt">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ketch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ketch/RK-Opt">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ketch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ketch/RK-Opt">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ketch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gardner48, @debdeepbh it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02514/joss.02514/10.21105.joss.02514.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2140/camcos.2012.7.247 is OK
- 10.1090/S0025-5718-09-02209-1 is OK
- 10.1137/120885899 is OK
- 10.1007/s10915-013-9796-7 is OK
- 10.1007/s10915-017-0560-2 is OK
- 10.1007/s10915-016-0195-8 is OK
- 10.1007/s10915-016-0195-8 is OK
- 10.1007/s10915-016-0195-8 is OK
- 10.1063/1.4992751 is OK
- 10.1137/07070485X is OK
- 10.1016/j.apnum.2008.03.034 is OK
- 10.1016/j.jcp.2009.11.006 is OK
- 10.1137/100818674 is OK
- 10.1137/10080960X is OK
- 10.1090/mcom/3115 is OK
- 10.1007/s10915-018-0664-3 is OK
- 10.1016/j.jcp.2019.01.003 is OK
- 10.1016/j.jcp.2020.109499 is OK
- 10.1007/978-1-84800-155-8_7 is OK
- 10.1007/s10915-019-00916-3 is OK

MISSING DOIs

- https://doi.org/10.1016/0378-4754(87)90083-8 may be missing for title: Solving ordinary differential equations I: Nonstiff Problems

INVALID DOIs

- None
```

**Comment by diehlpk** [comment]
@whedon add @emconsta as reviewer

**Comment by whedon** [comment]
OK, @emconsta is now a reviewer

**Comment by diehlpk** [comment]
Hi @emconsta @debdeepbh @gardner48 how is your review going? Please let me know if I can assist in any way.

**Comment by emconsta** [comment]
@ketch I am using a commercial Matlab license and do not have access to all toolboxes. In addition to required toolboxes, 
 I believe parpool is in 'Parallel Computing Toolbox'. I think that should be listed as a requirement or optional requirement since it's not critical.

**Comment by ketch** [comment]
@emconsta You're right; thanks for pointing that out.  I've added a note to the README in 67e0916.

**Comment by diehlpk** [comment]
Hi @emconsta @debdeepbh @gardner48 how is your review going? Please let me know if I can assist in any way.

**Comment by diehlpk** [comment]
Hi @emconsta @debdeepbh @gardner48 how is your review going? Please let me know if I can assist in any way.

**Comment by diehlpk** [comment]
Hi @emconsta @debdeepbh how is your review going? Please let me know if I can assist in any way.

**Comment by diehlpk** [comment]
@ketch I checked the references and please update 

1. Murray, L. M. (2013). Bayesian state-space modelling on high-performance hardware usingLibBi. (add the arxiv.org information)
2. Taylor, S. (1982). Financial returns modelled by the product of two stochastic processes, astudy of daily sugar prices 1961-79,1. (Add the journal)
3. Brown, T. R. (2020). Approximating posterior predictive distributions by averaging outputfrom many particle filters. (Add archiv.org information)

**Comment by diehlpk** [comment]
@ketch Have you seen that @gardner48 opened a new issue?

**Comment by diehlpk** [comment]
Hi @emconsta @debdeepbh @gardner48 could you please let me know when you anticipate to finish your review?

**Comment by gardner48** [comment]
@diehlpk Other than the issue I opened about running the examples I have finished my review.

**Comment by ketch** [comment]
> @ketch Have you seen that @gardner48 opened a new issue?

Thanks; I think it is resolved now, along with @debdeepbh's issue.

**Comment by diehlpk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02514/joss.02514/10.21105.joss.02514.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02514/joss.02514/10.21105.joss.02514.pdf) :page_facing_up: :point_left:

**Comment by diehlpk** [comment]
Since we quite close that the reviewers finished their review, I will do some editorial tasks on the paper, 

1. Affiliations: Please add the country 
1. Would it be possible to add the grant number for the AFOSR grant? Same for the DOE Computational Science Graduate Fellowship?
1. Some citations use abbreviations (minority) for the journal name and some use the full name. Could you make this consistent?

**Comment by ketch** [comment]
> 1. Affiliations: Please add the country

Done.

> 2. Would it be possible to add the grant number for the AFOSR grant? Same for the DOE Computational Science Graduate Fellowship?

There isn't a grant number for the CSGF.  I've added the AFOSR number.

> 3. Some citations use abbreviations (minority) for the journal name and some use the full name. Could you make this consistent?

Done.

> 4. For some references the capitalization seems to be strange, e.g. In Proceedings of the european congress on computational methods in applied sciences and engineering. Could you check these? Adding `{}` to the title or journal name will keep the capitalization.

Done; I think I caught them all.

**Comment by diehlpk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2514 with the following error: 

 Error reading bibliography ./paper.bib (line 80, column 9):
unexpected "T"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by diehlpk** [comment]
@ketch Could you please check why the paper does not compile?

**Comment by diehlpk** [comment]
Hi @emconsta @debdeepbh @gardner48  thanks for your review.

**Comment by ketch** [comment]
Sorry about that.  I've fixed it and checked that it compiles now.

**Comment by diehlpk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02514/joss.02514/10.21105.joss.02514.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02514/joss.02514/10.21105.joss.02514.pdf) :page_facing_up: :point_left:

**Comment by diehlpk** [comment]
@ketch 

- [ ] Please generate a new release including all the updates from the review 
- [ ] Please post the new release number here
- [ ] Please upload the release and obtain a DOI (Zenodo or FigShare). Note that the title and the authors have to match with the paper.
- [ ] Post the DOI here

**Comment by diehlpk** [comment]
@ketch I needed this information to accept the publication. Could you might provide it soonish?

**Comment by ketch** [comment]
@diehlpk I've tried to do what you asked.  The release version number is 1.0.1 and the DOI is 10.5281/zenodo.4138077.  I don't see any author information or any way to set the author information on Zenodo.

**Comment by ranocha** [comment]
I've submitted a PR to RK-Opt to fix that: https://github.com/ketch/RK-Opt/pull/60

**Comment by ketch** [comment]
Thanks, @ranocha .  I think everything is in order now.  Here is the corrected information:

Release: 1.0.2
DOI: 10.5281/zenodo.4138949

**Comment by diehlpk** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by diehlpk** [comment]
@whedon set v1.0.2 as version

**Comment by whedon** [comment]
OK. v1.0.2 is the version.

**Comment by diehlpk** [comment]
@ketch The title of the Zendo thingy has to match the paper's title. You can edit/update the current version and change the title or rearrange authors. Note that the order of authors has to match the paper as well.

**Comment by diehlpk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02514/joss.02514/10.21105.joss.02514.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02514/joss.02514/10.21105.joss.02514.pdf) :page_facing_up: :point_left:

**Comment by ranocha** [comment]
I've submitted a PR to make the title on Zenodo match the title of the paper: https://github.com/ketch/RK-Opt/pull/62.

The order of authors looks to me identical on Zenodo and the paper (David I. Ketcheson;  Matteo Parsani;  Zachary J. Grant;  Aron J. Ahmadia;  Hendrik Ranocha).

**Comment by diehlpk** [comment]
Ok, perfect. Once I have the new release and the DOI. I can accept the paper. If you like to avoid having a new release, you can log in to Zendo and change the title there.

**Comment by ketch** [comment]
I couldn't find a way to change the title on Zenodo.  Actually, it looks correct there already.  But in case it's needed, I made another release.

New release: 1.0.3
DOI: 10.5281/zenodo.4146740

**Comment by diehlpk** [comment]
@whedon set v1.0.3 as version

**Comment by whedon** [comment]
OK. v1.0.3 is the version.

**Comment by diehlpk** [comment]
@whedon set 10.5281/zenodo.4146740 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4146740" target="_blank">10.5281/zenodo.4146740</a> is the archive.

**Comment by diehlpk** [comment]
@ketch 

![image](https://user-images.githubusercontent.com/3922435/97459718-0fc70280-190a-11eb-8d8d-ed40d2136f10.png)

The title is still `ketch/RK-OPT` but should be the same title as in the paper.

**Comment by diehlpk** [comment]
@ketch 

![image](https://user-images.githubusercontent.com/3922435/97460802-17d37200-190b-11eb-95e8-26a5c2164371.png)

There is the edit button and you should be able to replace `ketch/RK-OPT` with the paper title there without doing a new release.

**Comment by ketch** [comment]
@diehlpk Thanks, but I can't see that.  Here is what I see:

![Screen Shot 2020-10-29 at 9 34 41 AM](https://user-images.githubusercontent.com/697763/97533899-22a10c00-19ca-11eb-833d-ebda6c233661.png)

Can you tell me how to get to the page with the "edit" and "New version" buttons?

**Comment by ketch** [comment]
Okay, I think I finally found it and fixed it:

![Screen Shot 2020-10-29 at 9 38 54 AM](https://user-images.githubusercontent.com/697763/97534193-a2c77180-19ca-11eb-92c1-c6addd210ea0.png)

Although on the other page I screenshotted above, it still shows exactly the same thing as before.

**Comment by diehlpk** [comment]
@arfon Do you have any idea what is going on? I do not know why the title is different in the two different views?

**Comment by diehlpk** [comment]
@ketch I see in your screenshot that you have one draft. Have you published your edit? You first have to save the edit and in addition you have to publish it. Could you please check if you have published it? Just some idea, since I saw the draft in the scrrenshot.

**Comment by ketch** [comment]
Thanks; apparently I clicked the wrong button previously.  Now it is published.

**Comment by diehlpk** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1882

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1882, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2140/camcos.2012.7.247 is OK
- 10.1090/S0025-5718-09-02209-1 is OK
- 10.1137/120885899 is OK
- 10.1007/s10915-013-9796-7 is OK
- 10.1007/s10915-017-0560-2 is OK
- 10.1007/s10915-016-0195-8 is OK
- 10.1007/s10915-016-0195-8 is OK
- 10.1007/s10915-016-0195-8 is OK
- 10.1063/1.4992751 is OK
- 10.1137/07070485X is OK
- 10.1016/j.apnum.2008.03.034 is OK
- 10.1016/j.jcp.2009.11.006 is OK
- 10.1137/100818674 is OK
- 10.1137/10080960X is OK
- 10.1090/mcom/3115 is OK
- 10.1007/s10915-018-0664-3 is OK
- 10.1016/j.jcp.2019.01.003 is OK
- 10.1016/j.jcp.2020.109499 is OK
- 10.1007/978-1-84800-155-8_7 is OK
- 10.1007/s10915-019-00916-3 is OK

MISSING DOIs

- 10.1007/978-3-030-39647-3_36 may be a valid DOI for title: DIRK Schemes with High Weak Stage Order
- 10.1016/0378-4754(87)90083-8 may be a valid DOI for title: Solving ordinary differential equations I: Nonstiff Problems

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1322256340908187648) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1885
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02514](https://doi.org/10.21105/joss.02514)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@gardner48, @debdeepbh, @emconsta - many thanks for your reviews here and to @diehlpk for editing this submission ✨ 

@ketch - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02514/status.svg)](https://doi.org/10.21105/joss.02514)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02514">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02514/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02514/status.svg
   :target: https://doi.org/10.21105/joss.02514
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02514/status.svg)](https://doi.org/10.21105/joss.02514)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by ketch** [comment]
Many thanks to everyone for your help in improving the software and getting this published.  Cheers!
