### ISSUE TITLE
[REVIEW]: NodePy: A package for the analysis of numerical ODE solvers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2515]
**Submitting author:** @ketch (<a href="http://orcid.org/0000-0002-1212-126X">David Ketcheson</a>)
**Repository:** <a href="https://github.com/ketch/nodepy" target ="_blank">https://github.com/ketch/nodepy</a>
**Version:** 1.0.1
**Editor:** @VivianePons
**Reviewers:** @fruzsinaagocs, @highlando
**Archive:** <a href="https://doi.org/10.5281/zenodo.4275158" target="_blank">10.5281/zenodo.4275158</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ad59e2373fbbd5d25cd39f22cda30773/status.svg)](https://joss.theoj.org/papers/ad59e2373fbbd5d25cd39f22cda30773)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ad59e2373fbbd5d25cd39f22cda30773"><img src="https://joss.theoj.org/papers/ad59e2373fbbd5d25cd39f22cda30773/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ad59e2373fbbd5d25cd39f22cda30773/status.svg)](https://joss.theoj.org/papers/ad59e2373fbbd5d25cd39f22cda30773)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ketch/nodepy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@fruzsinaagocs & @wingtorres, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @VivianePons know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ketch/nodepy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ketch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ketch/nodepy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ketch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @fruzsinaagocs, @wingtorres it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/07070485X is OK
- 10.1016/j.apnum.2008.03.034 is OK
- 10.1016/j.jcp.2009.11.006 is OK
- 10.1137/100818674 is OK
- 10.1137/10080960X is OK
- 10.1137/120884201 is OK
- 10.1137/130936245 is OK
- 10.2140/camcos.2014.9.175 is OK
- 10.1137/15M101717X is OK
- 10.1007/s10915-016-0331-5 is OK
- 10.1090/mcom/3115 is OK
- 10.1007/s10915-018-0664-3 is OK
- 10.1090/mcom/3296 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.rinam.2019.100004 is OK
- 10.1137/19M1263662 is OK
- 10.1002/fld.4773 is OK

MISSING DOIs

- https://doi.org/10.1016/0378-4754(87)90083-8 may be missing for title: Solving ordinary differential equations I: Nonstiff Problems

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02515/joss.02515/10.21105.joss.02515.pdf)

**Comment by VivianePons** [comment]
I am taking some time off, I will still be checking my emails and keep an eye on my current assigned submissions. I might just take a bit more time than usual to answer.

**Comment by VivianePons** [comment]
@whedon re-invite as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by VivianePons** [comment]
@whedon re-invite @fruzsinaagocs as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@fruzsinaagocs please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by fruzsinaagocs** [comment]
Hi all,

Thanks for writing this great package! Bringing together techniques from
classic numerical analysis works was much needed, and this certainly has the potential to be
widely used in research. I've ticked off most things on the reviewer checklist, I'll
organise the remaining points below.

### Python 3 compatibility and dependencies

* In the readthedocs [Dependencies](https://nodepy.readthedocs.io/en/latest/index.html#dependencies) section, it is stated that NodePy depends on (among others):
    * Python 2.7 (current, stable version: 3.8)
    * Sympy 0.7 (current, stable version: 1.6)
Python 2.7 is unsupported as of this year, and Sympy has deprecated some of the
functions used in the package since. Ideally, the package should support Python
3, but at least should make it very clear which version of the dependencies it
requires in the `README.md` and docs alike, and fetch the intended versions of
the dependencies. I can see that Travis CI is already testing in Python 3.5 (as
well as 2.7), which suggests that this work was planned/is in progress.
* There is a mismatch between what optional dependencies the package has:
  `README.md` lists cvxpy, the docs mention networkx. It should be clear which
  modules rely on these.
* Some example notebooks make use of scipy, this should be added as a dependency
  and fetched.

### Installation

`pip install` and installation from source were both quick and easy. Just some
minor points: 

* The docs [Quick Start
  Guide](https://nodepy.readthedocs.io/en/latest/quickstart.html#obtaining-nodepy)
  says that the pip version is often outdated and the package should be
  installed from source, whereas `README.md` suggets `pip install`. These should
  mathc, and ideally the pip version should be up to date. 
* The same guide suggests that the user updates the `PYTHONPATH` variable as
```bash
export PYTHONPATH=/user/home/python/
```
but this overwrites `PYTHONPATH`. I would change this to
```bash 
export PYTHONPATH=$PYTHONPATH:/user/home/python/
```
so that it is appended to instead.

### Documentation

* A link to the Useg Guide from the docs [Examples section](https://nodepy.readthedocs.io/en/latest/quickstart.html#examples) is broken. This would be a useful feature.
* An alternative docs website link from the docs [Documentation section](https://nodepy.readthedocs.io/en/latest/quickstart.html#nodepy-documentation) is also broken.
* There is a note about user guide being incomplete and not up-to-date [here in the docs](https://nodepy.readthedocs.io/en/latest/index.html). It's not clear which guide is being referred to.
* Throughout the docs, the rendering of LaTeX equations is broken, e.g. [here](https://nodepy.readthedocs.io/en/latest/rkm.html#runge-kutta-methods).
* In general, the `README.md` and docs should be more synchronised in their content.

### Examples

* scipy dependency should be added, as mentioned above.
* having worked though the examples, I submittted issues https://github.com/ketch/nodepy/issues/83,https://github.com/ketch/nodepy/issues/84, https://github.com/ketch/nodepy/issues/85, https://github.com/ketch/nodepy/issues/86 https://github.com/ketch/nodepy/issues/86 mainly to do with Python 3/Sympy 1.6 compatibility.
* It would be nice to run the example notebooks automatically, as mentioned
  already in https://github.com/ketch/nodepy/issues/87
* The example notebooks are really neat. They would be even better with some
  more comments and labelling of figure axes.

### Community guidelines

* Guidelines on how to seek support should be added.

### Testing

Testing's done via Travis continuous integration, the unit tests are found in
[`nodepy/unit_tests.py`](https://github.com/ketch/nodepy/blob/master/nodepy/unit_tests.py). Both in the comments and in the docs, it is mentioned that the unit tests are to be updated, which I support. An example of an incomplete test case is the `LinearMultistepTestCase`.

### Miscellaneous

* The [paper](https://github.com/openjournals/joss-papers/blob/joss.02515/joss.02515/10.21105.joss.02515.pdf) lists numerical methods the package has object-oriented representations for, one being dense output formulas. This would be incredibly useful, but I couldn't find anything about the topic in the docs, and the module reference includes some `TODO`s in the [relevant docstring](https://nodepy.readthedocs.io/en/latest/modules/runge_kutta_method.html#nodepy.runge_kutta_method.ContinuousRungeKuttaMethod). This should be updated, if such feature is planned.

**Comment by fruzsinaagocs** [comment]
These changes look great, @ketch. 

I have now ran the example notebooks, they run smoothly and have a good amount of detail. Running them automatically as tests is a neat idea.

Documenting a package with so much functionality is no small task, but with the existing examples and docs I trust that the few missing bits will soon be covered and I'm happy to tick this off. (As it happens, testing dense output from an arbitrary RK method is of particular interest to my research!)

I recommend the package for publication.

**Comment by VivianePons** [comment]
Thank you very much @fruzsinaagocs !

@wingtorres do you think you'll have time to work on this soon?

**Comment by ketch** [comment]
@fruzsinaagocs Thanks again for the detailed and thorough review.  If you let me know more specifically what you're hoping to test regarding dense output, I can probably add the needed functionality or documentation to the package.

**Comment by wingtorres** [comment]
@VivianePons sorry for the delay! I was out for a few weeks. I will have time to work on this next week

**Comment by fruzsinaagocs** [comment]
> @fruzsinaagocs Thanks again for the detailed and thorough review. If you let me know more specifically what you're hoping to test regarding dense output, I can probably add the needed functionality or documentation to the package.

I'm specifically looking for testing the efficiency of the continuous extension of Runge-Kutta formulas. To compare efficiencies of two formulas, [Shampine: Some practical Runge-Kutta formulas](https://doi.org/10.2307/2008219 ) offers a method in Section 3. "Interpolation", based on the truncation error coefficients of the formula, expressions for which Chapter 6 of [Hall, Watt: Modern numerical methods for ODEs](https://doi.org/10.1017/S0013091500026699) is cited. If `Nodepy` could compute this efficiency metric for an arbitrary continuous formula, that would be very helpful. 

Going one step further, if one could automatically compute the coefficients for a continuous extension of a given RK formula by solving the order conditions from e.g. [Horn: Fourth- and fifth-order, scaled Runge-Kutta algorithms for treating dense output](https://www.jstor.org/stable/2157271) and determine at which points one could get a 'free' or 'cheap' output of order p, it would make the construction of dense output formulas a lot easier!

Does any of the above sound like it could be added as a feature?

**Comment by VivianePons** [comment]
@wingtorres no problem! I just wanted to make sure we were still on track :)

**Comment by VivianePons** [comment]
Hi @wingtorres have you had time to look at it?

**Comment by VivianePons** [comment]
I have had no news of @wingtorres for more than a month, so I'll ask a new reviewer

**Comment by VivianePons** [comment]
@whedon invite @dalcinl as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by VivianePons** [comment]
@whedon add @dalcinl as reviewer

**Comment by whedon** [comment]
OK, @dalcinl is now a reviewer

**Comment by VivianePons** [comment]
@whedon remove @dalcinl as reviewer

**Comment by whedon** [comment]
OK, @dalcinl is no longer a reviewer

**Comment by VivianePons** [comment]
I had to remove Lisandro as reviewer due our [conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) I am looking for a replacement

**Comment by VivianePons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02515/joss.02515/10.21105.joss.02515.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02515/joss.02515/10.21105.joss.02515.pdf) :page_facing_up: :point_left:

**Comment by VivianePons** [comment]
@whedon add @highlando as reviewer

**Comment by whedon** [comment]
OK, @highlando is now a reviewer

**Comment by VivianePons** [comment]
HI @highlando did you have time to start your review? Remember that you can post comments as you go whenever you see room for improvement.

**Comment by highlando** [comment]
Alright. I can say that this looks like an advanced and useful piece of software. The formal requirements are all satisfied. I don't have any major issues. Only a few minor things:
- [ ] The link to documentation on http://numerics.kaust.edu.sa/nodepy is forwarded to *readthedocs*. Maybe have only one repo and one address for the documentation.
- [ ] Examples -- maybe one on how to apply these analyses for custom methods. (Although from the class descriptions it is very clear how this may work).
- [ ] The community support/contribution is very brief. Maybe add some more words.
- [ ] The paper does not refer to similar software or other software that might be helpful with these tasks. If there is none, the authors may just state this fact.

**Comment by ketch** [comment]
Thanks @highlando.

> Maybe have only one repo and one address for the documentation.

Good idea.  I've tried to get rid of all the old links, but left the redirect there in case there are some still floating around the internet.  The KAUST Numerics site is in a major transition at the moment, but when that is finished those links will be updated too.

> Examples -- maybe one on how to apply these analyses for custom methods. (Although from the class descriptions it is very clear how this may work).

Good idea; I've added this in the "Introduction to Nodepy" notebook in examples/.

> The community support/contribution is very brief. Maybe add some more words.

In my opinion, length itself is not a virtue.  But is there specific information that you think we should add?  And if so, are you referring to the README, the docs, or the paper?

> The paper does not refer to similar software or other software that might be helpful with these tasks. If there is none, the authors may just state this fact.

I've added a sentence to this effect at the beginning of the section.

**Comment by highlando** [comment]
Hi @ketch 

I'm OK with the extra link -- just a warning that this extra work when maintaining.

Thanks for the extra line in the *Introduction to Nodepy* notebook. Much appreciated.

As for the *support/contribution*. I was referring to the [documentation](https://nodepy.readthedocs.io/en/latest/about.html#contributing). Because of its brevity it is not so prominent. Maybe add a link to the github repo and also offer to open an issue in the issue tracker there. But I'm totally fine with its current state.

Thanks for the additional information that there is no similar software around.

I'm completely satisfied with the submission, @VivianePons

**Comment by ketch** [comment]
Thanks for calling my attention to that page in the docs; it was outdated in other ways, too.  I've expanded the contributing section with a couple of links for Github issues and PRs.

**Comment by VivianePons** [comment]
Hi @highlando the box "State of the field" is not checked in the issue description, if you are now satisfied, can you tick it?

**Comment by VivianePons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02515/joss.02515/10.21105.joss.02515.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02515/joss.02515/10.21105.joss.02515.pdf) :page_facing_up: :point_left:

**Comment by VivianePons** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/07070485X is OK
- 10.1016/j.apnum.2008.03.034 is OK
- 10.1016/j.jcp.2009.11.006 is OK
- 10.1137/100818674 is OK
- 10.1137/10080960X is OK
- 10.1137/120884201 is OK
- 10.1137/130936245 is OK
- 10.2140/camcos.2014.9.175 is OK
- 10.1137/15M101717X is OK
- 10.1007/s10915-016-0331-5 is OK
- 10.1090/mcom/3115 is OK
- 10.1007/s10915-018-0664-3 is OK
- 10.1090/mcom/3296 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.rinam.2019.100004 is OK
- 10.1137/19M1263662 is OK
- 10.1002/fld.4773 is OK
- 10.21105/joss.02514 is OK

MISSING DOIs

- 10.1016/0378-4754(87)90083-8 may be a valid DOI for title: Solving ordinary differential equations I: Nonstiff Problems

INVALID DOIs

- None
```

**Comment by VivianePons** [comment]
@whedon remove @wingtorres as reviewer

**Comment by whedon** [comment]
OK, @wingtorres is no longer a reviewer

**Comment by VivianePons** [comment]
Hi @ketch with two positive reviews, we can now move forward! Congratulations and thanks a lot to the reviewers.

Can you make an archive (on Zenodo, figshare, or other) and be careful to have the same metadata (name and authors) of the paper?

**Comment by ketch** [comment]
@VivianePons Thanks to you and the reviewers for all your hard work!  I've made a release on Zenodo and I think everything is in order.

**Comment by VivianePons** [comment]
Can you give me the doi?

**Comment by ketch** [comment]
Sorry!  Here it is:

10.5281/zenodo.4275158

**Comment by VivianePons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02515/joss.02515/10.21105.joss.02515.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02515/joss.02515/10.21105.joss.02515.pdf) :page_facing_up: :point_left:

**Comment by VivianePons** [comment]
@whedon set 10.5281/zenodo.4275158 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4275158" target="_blank">10.5281/zenodo.4275158</a> is the archive.

**Comment by VivianePons** [comment]
@whedon set 1.0.1 as version

**Comment by whedon** [comment]
OK. 1.0.1 is the version.

**Comment by VivianePons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02515/joss.02515/10.21105.joss.02515.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02515/joss.02515/10.21105.joss.02515.pdf) :page_facing_up: :point_left:

**Comment by VivianePons** [comment]
Congratulations @ketch ! I am moving your paper to acceptance, thank you for the work you provided by writing this software. Thank you to both reviewers @fruzsinaagocs and @highlando for your thorough comments and help with improving the software.

**Comment by VivianePons** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1920

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1920, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/07070485X is OK
- 10.1016/j.apnum.2008.03.034 is OK
- 10.1016/j.jcp.2009.11.006 is OK
- 10.1137/100818674 is OK
- 10.1137/10080960X is OK
- 10.1137/120884201 is OK
- 10.1137/130936245 is OK
- 10.2140/camcos.2014.9.175 is OK
- 10.1137/15M101717X is OK
- 10.1007/s10915-016-0331-5 is OK
- 10.1090/mcom/3115 is OK
- 10.1007/s10915-018-0664-3 is OK
- 10.1090/mcom/3296 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.rinam.2019.100004 is OK
- 10.1137/19M1263662 is OK
- 10.1002/fld.4773 is OK
- 10.21105/joss.02514 is OK

MISSING DOIs

- 10.1016/0378-4754(87)90083-8 may be a valid DOI for title: Solving ordinary differential equations I: Nonstiff Problems

INVALID DOIs

- None
```

**Comment by ketch** [comment]
Thank you @VivianePons, @fruzsinaagocs, @highlando!

**Comment by danielskatz** [comment]
Thanks - I'll start the final proofreading and processing later today.

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1328726863569678342) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1922
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02515](https://doi.org/10.21105/joss.02515)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @ketch (David Ketcheson) and co-authors!!

And thanks to @fruzsinaagocs & @highlando for reviewing, and @VivianePons for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02515/status.svg)](https://doi.org/10.21105/joss.02515)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02515">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02515/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02515/status.svg
   :target: https://doi.org/10.21105/joss.02515
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02515/status.svg)](https://doi.org/10.21105/joss.02515)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
