### ISSUE TITLE
[PRE REVIEW]: PyAutoFit`: A Classy Probabilistic Programming Language for Model Composition and Fitting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2516]
**Submitting author:** @Jammy2211 (<a href="http://orcid.org/0000-0002-8987-7401">James Nightingale</a>)
**Repository:** <a href="https://github.com/rhayes777/PyAutoFit" target ="_blank">https://github.com/rhayes777/PyAutoFit</a>
**Version:** v0.64.3
**Editor:** @dfm
**Reviewers:** @arm61, @eteq
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Jammy2211. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@Jammy2211 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.89 s (397.2 files/s, 49358.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         193           5849           7207          14821
Jupyter Notebook                67              0           4484           5918
JSON                            17              0              0           1779
INI                             46            146              0           1073
reStructuredText                19            592            607            667
TeX                              3              5              0            443
Markdown                         3             29              0             75
Dockerfile                       1              6              6             50
DOS Batch                        1              8              1             26
Bourne Shell                     1             14              3             24
make                             1              4              7              9
YAML                             1              4              2              8
-------------------------------------------------------------------------------
SUM:                           353           6657          12317          24893
-------------------------------------------------------------------------------


Statistical information for the repository '2516' was gathered on 2020/07/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
James Nightingale               20          1403            674            1.08
Richard                        329         15620          12516           14.60
Richard Hayes                  619         29043          18915           24.88
jammy2211                      406         64698          49907           59.45

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Richard                    8737           55.9          7.9                5.29
Richard Hayes               258            0.9          8.8               10.85
jammy2211                 19261           29.8          1.8                9.55
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00024 is OK
- 10.21105/joss.00433 is OK
- 10.1093/mnras/staa278 is OK
- 10.1086/670067 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1093/mnras/sts633 is OK
- 10.1093/mnras/stv1455 is OK
- 10.1093/mnras/sty1264 is OK
- 10.1093/mnras/stz2220 is OK
- 10.7717/peerj-cs.55 is OK
- 10.18637/jss.v076.i01 is OK
- 10.1051/0004-6361/201322971 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK

MISSING DOIs

- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy Array: A Structure for Efficient Numerical Computation

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02516/joss.02516/10.21105.joss.02516.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@Jammy2211 After investigating if this submission is suitable for JOSS I'll work on finding an editor to handle this submission. In the mean time perhaps you can work on those missing and invalid DOI's :point_up:. You can call `@whedon generate pdf` to update the paper and you can call `@whedon check references` to check those references.

**Comment by Kevin-Mattheus-Moerman** [comment]
@dfm you are handling a couple of submissions already but this does seem like your cup of tea :tea:. Would you be able to handle this one? 

Alternatively @mikldk @galessiorob @mjsottile can one of you handle this submission? Thanks.

**Comment by dfm** [comment]
@Kevin-Mattheus-Moerman: sure thing. I'm happy to edit!

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@arm61 has kindly agreed to review this submission.

I'll start the review once I've found a second reviewer.

**Comment by dfm** [comment]
@whedon assign @arm61 as reviewer

**Comment by whedon** [comment]
OK, @arm61 is now a reviewer

**Comment by dfm** [comment]
@eteq has also agree to review. Thanks Erik!

**Comment by dfm** [comment]
@whedon add @eteq as reviewer

**Comment by whedon** [comment]
OK, @eteq is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2550.

**Comment by dfm** [comment]
@arm61, @eteq, @Jammy2211: We can now head over to #2550 to get the review started. Let me know if any of you have questions as we proceed!
