### ISSUE TITLE
[PRE REVIEW]: gLBM: A GPU enabled Lattice Boltzmann Method Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2517]
**Submitting author:** @rclipp (<a href="http://orcid.org/0000-0001-6077-978X">Rachel Clipp</a>)
**Repository:** <a href="https://gitlab.kitware.com/LBM/lattice-boltzmann-solver" target ="_blank">https://gitlab.kitware.com/LBM/lattice-boltzmann-solver</a>
**Version:** v1.0.0
**Editor:** @eloisabentivegna
**Reviewers:** @ianhinder, @gouarin
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @rclipp. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@rclipp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2517 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2517 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2517 with the following error: 

 sh: 1: cd: can't cd to tmp/2517
/app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2517 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you check this error :point_up:. Is this not compiling because the folder the paper is in is called `joss` not `paper`?

The paper is currently here: 
https://gitlab.kitware.com/LBM/lattice-boltzmann-solver/-/tree/joss/joss

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by Kevin-Mattheus-Moerman** [comment]
@labarba do you have the bandwidth to handle this submission? It does seem like your cup of tea :tea: 

Alternatively @eloisabentivegna @harpolea can one of you edit this one? Thanks

**Comment by eloisabentivegna** [comment]
@whedon assign @eloisabentivegna as editor 

@Kevin-Mattheus-Moerman, sure!

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by arfon** [comment]
> @openjournals/dev can you check this error ☝️. Is this not compiling because the folder the paper is in is called joss not paper?

The issue is that Whedon (and git) can't clone a URL like this: `https://gitlab.kitware.com/LBM/lattice-boltzmann-solver/-/tree/joss/joss`

I've updated the URL for the repo to be `https://gitlab.kitware.com/LBM/lattice-boltzmann-solver`

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02517/joss.02517/10.21105.joss.02517.pdf)

**Comment by eloisabentivegna** [comment]
@whedon add @ianhinder as reviewer

**Comment by whedon** [comment]
OK, @ianhinder is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon add @gouarin as reviewer

**Comment by whedon** [comment]
OK, @gouarin is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2555.
