### ISSUE TITLE
[PRE REVIEW]: ectotemp: An R package for quantitative estimates of small ectotherm temperature regulation effectiveness

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2518]
**Submitting author:** @wouterbeukema (<a href="http://orcid.org/0000-0002-5839-7683">Wouter Beukema</a>)
**Repository:** <a href="https://github.com/wouterbeukema/ectotemp" target ="_blank">https://github.com/wouterbeukema/ectotemp</a>
**Version:** v0.2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @wouterbeukema. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @marcosvital.

@wouterbeukema if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.02 s (912.3 files/s, 57831.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         4             59              0            192
R                               10             15            346            186
TeX                              1             13              0            140
Rmd                              2             58             76             52
YAML                             1              1              1              2
-------------------------------------------------------------------------------
SUM:                            18            146            423            572
-------------------------------------------------------------------------------


Statistical information for the repository '2518' was gathered on 2020/07/25.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1890/04-1403 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.2307/2679832 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.2307/2963472 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1073/pnas.0709472105 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1111/ecog.04226 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.1086/285573 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1098/rspb.2008.1957 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1086/346135 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1098/rstb.2012.0005 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1086/409470 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1073/pnas.0808913106 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1086/422052 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02518/joss.02518/10.21105.joss.02518.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@wouterbeukema I will be reviewing this work for scope/suitability and will assign an editor to handle this submission if needed. 

In the mean time could you address those invalid DOI's by removing the `https://doi.org/` prefix as suggested? :point_up: 
You can regenerate the pdf here yourself by running: 
`@whedon generate pdf`

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by wouterbeukema** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02518/joss.02518/10.21105.joss.02518.pdf)

**Comment by wouterbeukema** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1890/04-1403 is OK
- 10.2307/2679832 is OK
- 10.2307/2963472 is OK
- 10.1073/pnas.0709472105 is OK
- 10.1111/ecog.04226 is OK
- 10.1086/285573 is OK
- 10.1098/rspb.2008.1957 is OK
- 10.1086/346135 is OK
- 10.1098/rstb.2012.0005 is OK
- 10.1086/409470 is OK
- 10.1073/pnas.0808913106 is OK
- 10.1086/422052 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by wouterbeukema** [comment]
Hi @Kevin-Mattheus-Moerman, thanks. I browsed through the list of potential reviewers and checked their work - I'd like to suggest KristinaRiemer.

**Comment by kthyng** [comment]
Hi @wouterbeukema. Thank you for your submission. However, the JOSS editorial board has determined that it does not meet the bar of [_substantial scholarly effort_](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).
If you continue to develop this work, we would be happy to reconsider it as a submission in the future.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
