### ISSUE TITLE
[PRE REVIEW]: The Dusty Evolved Star Kit (DESK): A Python package for fitting the Spectral Energy Distribution of Evolved Stars

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2519]
**Submitting author:** @s-goldman (<a href="http://orcid.org/0000-0002-8937-3844">Steve Goldman</a>)
**Repository:** <a href="https://github.com/s-goldman/Dusty-Evolved-Star-Kit" target ="_blank">https://github.com/s-goldman/Dusty-Evolved-Star-Kit</a>
**Version:** v1.7.0
**Editor:** @arfon
**Reviewers:** @Deech08, @TomGoffrey
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @s-goldman. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@s-goldman if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (699.7 files/s, 81691.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             9           1076              9           1642
Python                          28            410            902           1295
XML                              1              0              2            841
reStructuredText                16            214            185            325
TeX                              1              7              0             97
Markdown                         2             48              0             79
make                             2             24              6             78
YAML                             2              8              6             47
DOS Batch                        1              8              1             27
INI                              1              4              0             14
-------------------------------------------------------------------------------
SUM:                            63           1799           1111           4445
-------------------------------------------------------------------------------


Statistical information for the repository '2519' was gathered on 2020/07/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Pey Lian Lim                     1             1              0            0.00
Steve Goldman                  312         25450          22950          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Steve Goldman              2607           10.2          2.9               16.46
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1046/j.1365-8711.2001.04706.x is OK
- 10.1086/367818 is OK
- 10.1088/0004-637X/716/1/878 is OK
- 10.1051/0004-6361/201117033 is OK
- 10.1093/mnras/stw2708 is OK
- 10.1093/mnras/stz1255 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02519/joss.02519/10.21105.joss.02519.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@harpolea @xuanxu @mbobra @pibion Could one of you handle this submission? Thanks. This package appears to offer novel functionality but it does seem on the minor side. If you pick this up can you also judge if this is in scope (use `@whedon query scope` to trigger an editorial board level review if needed).

**Comment by xuanxu** [comment]
@Kevin-Mattheus-Moerman I can't take it, I don't have bandwidth right now

**Comment by arfon** [comment]
@s-goldman - does this submission accompany a paper in a AAS journal?

**Comment by s-goldman** [comment]
@arfon It does not. I will, however, discuss the package and do in-depth comparisons of models for the project/paper I will be working on for the bulk of next year.

**Comment by arfon** [comment]
@s-goldman - this submission is on the smaller-side of what we are allowing in JOSS these days and I note the following comment in your submission message to JOSS:

> The next iteration will develop a Bayesian-fitting approach, currently under development in the probabilities module that is not used in v1.7.0.

Could you say a little more about the timeline for developing this? I could imagine that the addition of this functionality would make this a more compelling submission here.

**Comment by s-goldman** [comment]
@arfon Yeah sure, I developed that Bayesian-fitting functionality, but I got stuck on what to give the user as the default priors given that they're not well constrained. I was hoping to constrain them over the next year (using data from PHAT) and present them with the Bayesian-fitting module with my next paper. 

I think that the current brute-force least-squares fitting method is the more adaptable for the average user, with a lower possibility of unrealistic results. That's at least the reason why I decided to leave it out for the time being. I suppose I could enable the package assuming flat priors, but that would have the same effect as the least-squares fit. 

My timeline "plan" was have a well-established package before JWST launch, when data (other than archival Spitzer data) will finally be available to use with the package.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@s-goldman - thanks for providing the additional context. Could you suggest a few people that might be able to give this package a good review? Please try to avoid tagging them by username, e.g. `@arfon` rather than @arfon. 

This spreadsheet of volunteers might be useful too: https://bit.ly/joss-reviewers

**Comment by s-goldman** [comment]
@arfon Given their background in stellar physics I would suggest `@TomGoffrey, @Deech08, or @zpace`.

**Comment by arfon** [comment]
@schristophe @TomGoffrey @Deech08 - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by Deech08** [comment]
This looks really interesting, but I am defending my thesis next week and don't have the time right away to put into this. If a timeline of me starting to review in 1.5-2 weeks from now is okay, then I can. Otherwise it may be best to look for someone else.

**Comment by arfon** [comment]
> This looks really interesting, but I am defending my thesis next week and don't have the time right away to put into this. If a timeline of me starting to review in 1.5-2 weeks from now is okay, then I can. Otherwise it may be best to look for someone else.

Absolutely! We generally ask for reviews to be complete within six weeks. If that sounds OK, I'll go ahead and add you as a reviewer (there will be two or more reviewers) and then check in with you a little later on.

>  I am defending my thesis next week 

Also, good luck!

**Comment by Deech08** [comment]
Great, thanks! In that case you can assign me to this!

**Comment by arfon** [comment]
@whedon add @Deech08 as reviewer

**Comment by whedon** [comment]
OK, @Deech08 is now a reviewer

**Comment by arfon** [comment]
> Great, thanks! In that case you can assign me to this!

Wonderful, thanks!

**Comment by schristophe** [comment]
Hello @arfon. I am afraid I will not be able to review this submission as I already have lots of things to prepare for early September. Sorry!

**Comment by TomGoffrey** [comment]
@arfon Sure happy to help out. I'm ~ a day from finishing another review then I can start on this.

I do have a couple of thoughts on the discussion above, but perhaps it's best I wait until the reviewing process formally starts?

**Comment by arfon** [comment]
> @arfon Sure happy to help out. I'm ~ a day from finishing another review then I can start on this.

:zap: thanks @TomGoffrey! I'll go ahead and set up the review now. Looking forward to your feedback during the review.

**Comment by arfon** [comment]
@whedon add @TomGoffrey as reviewer

**Comment by whedon** [comment]
OK, @TomGoffrey is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2554.

**Comment by arfon** [comment]
@Deech08, @TomGoffrey, @s-goldman - see you all over in #2554 where the actual review will take place.
