### ISSUE TITLE
[PRE REVIEW]: Lab::Measurement - measurement control with Perl

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#252]
**Submitting author:** @akhuettel (<a href="http://orcid.org/0000-0001-5794-5919">Andreas K. Hüttel</a>)
**Repository:** <a href="http://www.labmeasurement.de/" target ="_blank">http://www.labmeasurement.de/</a>
**Version:** 3.542
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @kippkitts

**Author instructions**

Thanks for submitting your paper to JOSS @akhuettel. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@akhuettel if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @Kevin-Mattheus-Moerman - the author suggested you as an editor 😁

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon @akhuettel Apologies for the late reply. I have some LabView experience but am not very familiar with Perl. I'll nevertheless attempt to be an editor for this submission but I need some help from the authors. 

@akhuettel

1. Can you please check if you meet all our requirements? http://joss.theoj.org/about e.g. on the license your site mentions: 

> COPYRIGHT AND LICENCE
 (c) 2010, 2011 Daniel Schröer, Andreas K. Hüttel, Daniela Taubert, and others.
     2012       Andreas K. Hüttel

Please use an OSI approved open source license (https://opensource.org/licenses). 

2. The link to the repository is actually a link to the project website. Should the actual repository link for your work be the CPAN link e.g. this link http://search.cpan.org/dist/Lab-Measurement/?

3. I will talk to makers and instrumentation people here at MIT to see if they can review. In the meantime it would be helpful if you can help suggest suitable reviewers as well.  

Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
I've just noticed that on this site http://search.cpan.org/dist/Lab-Measurement/ on CPAN you mention this license http://dev.perl.org/licenses/. That seems to be general Perl license which offers the option of several types of licenses. For your work can you pick a single OSI approved license and also refer to it appropriately on your website?

**Comment by akhuettel** [comment]
About the license... In the Perl ecosystem it's actually quite common to release software "under the same license as Perl itself", which is what we're doing. (The http://dev.perl.org/licenses/ link is autogenerated from that on CPAN.) The Perl license is dual-licensing under "GPL-1 or later" and "Artistic" (1), so whoever wants to use / reproduce / modify the software can chose from this list. At least GPL-2 and GPL-3 are both OSI-approved and applicable to our software, so I don't really see any problem there.

I've added both the text of GPL-2 and the Artistic license to our repository, see https://github.com/lab-measurement/lab-measurement/tree/master/Measurement

I'll also clarify that information on the homepage within the next minutes.

**Comment by akhuettel** [comment]
About the software repository. Well, there are technically three URLs. 

1) the project homepage, http://www.labmeasurement.de/
2) the page on CPAN where releases are uploaded and distributed, http://search.cpan.org/dist/Lab-Measurement/
3) the git repository on Github for software development, https://github.com/lab-measurement/lab-measurement

The "repository" is probably best given by 3). I'm just a bit wary to specify the Github address as anything permanent. First it defies the decentralized nature of Git, second it is not open-source and outside our control, and third we already did move from gitorious to github in the past and I can imagine similar moves in the future. That's why I chose our domain as contact point. Anyway pick your poison.

**Comment by akhuettel** [comment]
About reviewers... Well, I don't know anyone except us who uses Perl to measure, so I unfortunately can't really make immediate suggestions.

* There are some similar projects, but more limited in scope, in other programming languages, e.g. pyvisa (and the "normal" software to use in this type of application is of course Labview).
* For Perl, people with similar interests might be among the authors of the PDL (Perl Data Language) library, see https://github.com/PDLPorters/pdl 
* The types of devices that we're addressing can be found a lot in (electronical) physics measurements or electrical engineering, also in industry. If you're looking for someone who has the same measurement requirements, then you need someone from solid state physics who's not doing optics. In Physics at MIT that's probably the work groups of Pablo Jarillo-Herrero or Ray Ashoori (but these are not software experts, so I doubt a lot if that would make sense).

**Comment by akhuettel** [comment]
@Kevin-Mattheus-Moerman I might be able to better help if you give me an idea what you're e.g. looking for in a reviewer...

**Comment by akhuettel** [comment]
@Kevin-Mattheus-Moerman @arfon Any news?

**Comment by Kevin-Mattheus-Moerman** [comment]
@akhuettel @arfon Sorry for the delay! I have finally found a suitable reviewer!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @kippkitts as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kippkitts

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/299. Feel free to close this issue now!
