### ISSUE TITLE
[PRE REVIEW]: chorrrds: An R package for music chords extraction and analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2522]
**Submitting author:** @brunaw (<a href="http://orcid.org/0000-0001-8163-220X">Bruna Wundervald</a>)
**Repository:** <a href="https://github.com/r-music/chorrrds" target ="_blank">https://github.com/r-music/chorrrds</a>
**Version:**  0.1.9.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @brunaw. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @bmcfee.

@brunaw if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.18637/jss.v068.b03 is OK

MISSING DOIs

- https://doi.org/10.1561/9781601988072 may be missing for title: Music information retrieval: Recent developments and applications
- https://doi.org/10.25080/majora-7b98e3ed-003 may be missing for title: librosa: Audio and music signal analysis in python
- https://doi.org/10.1371/journal.pone.0144610 may be missing for title: pyaudioanalysis: An open-source python library for audio signal analysis
- https://doi.org/10.1007/978-3-7908-1709-6_20 may be missing for title: Symbolic data analysis: what is it?
- https://doi.org/10.1126/science.267.5199.843 may be missing for title: Gauging similarity with n-grams: Language-independent categorization of text

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02522/joss.02522/10.21105.joss.02522.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (237.6 files/s, 21456.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1             89              5            453
Markdown                         3             97              0            382
R                               13             85            247            317
TeX                              1             13              0             99
YAML                             2              2              1             16
-------------------------------------------------------------------------------
SUM:                            20            286            253           1267
-------------------------------------------------------------------------------


Statistical information for the repository '2522' was gathered on 2020/07/26.
No commited files with the specified extensions were found.
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by majensen** [comment]
@Kevin-Mattheus-Moerman I would edit this.

**Comment by danielskatz** [comment]
👋 @brunaw - after discussion between the JOSS editors, we've come to a consensus that your submission, while being research software, is not a sufficient enough contribution for JOSS - see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort.  We encourage you to consider JOSS at a later time if more effort and code goes into this software, or alternatively, consider publishing the software to Zenodo to get a DOI that users can cite.

Additionally, thanks to @majensen for volunteering to edit before this decision was made.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
