### ISSUE TITLE
[PRE REVIEW]: waspr: an R package for computing Wasserstein barycenters of subset posteriors

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2524]
**Submitting author:** @joliencremers (<a href="http://orcid.org/0000-0002-0037-1747">Jolien Cremers</a>)
**Repository:** <a href="https://github.com/joliencremers/waspr" target ="_blank">https://github.com/joliencremers/waspr</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @joliencremers. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @oliviaguest.

@joliencremers if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.07 s (364.7 files/s, 23415.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               12            133            240            289
Markdown                         4             41              0            201
C++                              3             65             58            156
TeX                              1             17              0             98
Rmd                              3             47            155             37
YAML                             1              1              1              2
-------------------------------------------------------------------------------
SUM:                            24            304            454            783
-------------------------------------------------------------------------------


Statistical information for the repository '2524' was gathered on 2020/07/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
joliencremers                    5           305             26          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
joliencremers               279           91.5          0.0               20.79
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.jmva.2019.104581 is OK
- 10.1080/17509653.2016.1142191 is OK
- 10.1016/j.jmaa.2017.02.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02524/joss.02524/10.21105.joss.02524.pdf)

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by joliencremers** [comment]
Suggested reviewers: 

MikeLydeamore

**Comment by danielskatz** [comment]
@joliencremers - after some editor discussion, we have decided that this submission is not a large enough contribution for JOSS to review it - see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort. We encourage you to consider JOSS at a later time if more effort and code goes into this software, or alternatively, consider publishing the software to Zenodo to get a DOI that users can cite.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
