### ISSUE TITLE
[PRE REVIEW]: matador: a Python library for analysing, curating and performing high-throughput density-functional theory calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2529]
**Submitting author:** @ml-evs (<a href="http://orcid.org/0000-0002-1182-9098">Matthew L Evans</a>)
**Repository:** <a href="https://github.com/ml-evs/matador" target ="_blank">https://github.com/ml-evs/matador</a>
**Version:** v0.9.6
**Editor:** @jgostick
**Reviewers:** @mkhorton
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ml-evs. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jgostick.

@ml-evs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2529 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2529 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=2.79 s (74.2 files/s, 16859.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         150           5750           5580          25541
reStructuredText                16            299            126            541
Jupyter Notebook                10              0           8356            483
YAML                            13             12              1            122
INI                              1              0              0             97
Markdown                         3              5              0             59
JSON                            11              0              0             11
make                             1              4              6             10
Bourne Shell                     2              0              0              8
-------------------------------------------------------------------------------
SUM:                           207           6070          14069          26872
-------------------------------------------------------------------------------


Statistical information for the repository '2529' was gathered on 2020/07/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Angela Harper                    9           595             52            0.34
JordD04                          6           270             60            0.17
Matthew Evans                 1930        104724          72055           92.73
charmedxi                        5           419            278            0.37
harpaf13                         3            44             38            0.04
matthew                          2             6              4            0.01
me388                          171          4187           2253            3.38
ml-evs                          78          3421           2236            2.97

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Angela Harper                75           12.6         18.6                5.33
JordD04                     196           72.6          5.2                3.57
Matthew Evans             35496           33.9         16.6                6.92
matthew                       2           33.3         49.2                0.00
```

**Comment by ml-evs** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02529/joss.02529/10.21105.joss.02529.pdf)

**Comment by kthyng** [comment]
Hi @jgostick! You were suggested as editor for this submission. Interested?

**Comment by kthyng** [comment]
@whedon invite @jgostick as editor

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by ml-evs** [comment]
Hi @kthyng and @jgostick! I'm just having a look through the potential reviewers list (great to see so many!) and I recognise several names in this field who would be able to do a good job (in no particular order):

@bjmorgan
@mkhorton
@mdoucet 
@lucydot
@bocklund

Thanks!

**Comment by ml-evs** [comment]
@whedon check references

**Comment by mkhorton** [comment]
I'd be happy to take this one, I know @ml-evs via another project as a disclosure

**Comment by jgostick** [comment]
@mkhorton are you offering to editor this one?  If so, go for it.

**Comment by mkhorton** [comment]
I was offering to review in response to @ml-evs potential reviewers list. I'd be happy to be editor, but I haven't previously taken any editorial role in JOSS

**Comment by jgostick** [comment]
OK!  I'll edit, and invite you to review.  

@whedon assign @jgostick as editor

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by jgostick** [comment]
@whedon add @mkhorton as reviewer

**Comment by whedon** [comment]
OK, @mkhorton is now a reviewer

**Comment by jgostick** [comment]
I'm still looking for a 2nd reviewer, but I will start this so that @mkhorton can get started.

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2563.

**Comment by mdoucet** [comment]
@jgostick I can be the second reviewer if you still need someone.
