### ISSUE TITLE
[PRE REVIEW]: xphyle: Extraordinarily simple file handling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#253]
**Submitting author:** @jdidion (<a href="http://orcid.org/0000-0002-8111-6261">John Didion</a>)
**Repository:** <a href="https://github.com/jdidion/xphyle" target ="_blank">https://github.com/jdidion/xphyle</a>
**Version:** 3.0.1
**Editor:** @pjotrp
**Reviewer:** @ctb

**Author instructions**

Thanks for submitting your paper to JOSS @jdidion. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jdidion if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @pjotrp - the submitting author suggested you as an editor 😁

**Comment by pjotrp** [comment]
Make my day. I am not known for being nice ;). OK, let's start looking for reviewers.

**Comment by pjotrp** [comment]
@peterjc can you suggest a reviewer? I think this is an interesting addition to python bioinformatics (and beyond)

**Comment by peterjc** [comment]
Hmm. Reviewing a Python library for efficient access to compressed files - I'd think someone doing IO heavy Python/C would be best. @ctb or @mr-c could you suggest someone?

**Comment by ctb** [comment]
I can review.

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@whedon assign @ctb as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ctb

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/255. Feel free to close this issue now!
