### ISSUE TITLE
[PRE REVIEW]: Social-Annotate: Browser extension to annotate and collect social media data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2530]
**Submitting author:** @onurvarol (<a href="http://orcid.org/0000-0002-3994-6106">Onur Varol</a>)
**Repository:** <a href="https://github.com/uluturki/social-annotate" target ="_blank">https://github.com/uluturki/social-annotate</a>
**Version:** v1.0.0
**Editor:** @lorenanicole
**Reviewers:** @davekinkead, @sara-02
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @onurvarol. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kakiac.

@onurvarol if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.18653/v1/p18-1022 may be missing for title: A stylometric inquiry into hyperpartisan and fake news
- https://doi.org/10.1002/hbe2.115 may be missing for title: Arming the public with artificial intelligence to counter social bots
- https://doi.org/10.1002/meet.14504701444 may be missing for title: HCI browser: A tool for studying web search behavior
- https://doi.org/10.1109/asonam.2016.7752207 may be missing for title: Stop clickbait: Detecting and preventing clickbaits in online news media
- https://doi.org/10.1109/tvcg.2019.2934266 may be missing for title: VASSL: A Visual Analytics Toolkit for Social Spambot Labeling
- https://doi.org/10.1371/journal.pone.0069958 may be missing for title: Comparing the quality of crowdsourced data contributed by expert and non-experts

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=2.37 s (48.0 files/s, 36483.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      39          10830          12986          51612
CSS                              8            108             95           7475
JSON                            41              2              0           1340
Sass                             3             86              0            551
Markdown                         9            196              0            380
HTML                             5             55              5            335
SVG                              1              0              0            288
TeX                              1             12              0            103
Ruby                             2             10              2             38
Bourne Shell                     3             20              8             29
Python                           1             12              0             24
YAML                             1              0              0              5
-------------------------------------------------------------------------------
SUM:                           114          11331          13096          62180
-------------------------------------------------------------------------------


Statistical information for the repository '2530' was gathered on 2020/07/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ovarol2005@gmail.com            26         75173            576           49.72
uluturki                        46         75636            971           50.28

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
ovarol2005@gmail.com      74456           99.0         12.2               17.36
uluturki                  74776           98.9         13.0               17.63
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02530/joss.02530/10.21105.joss.02530.pdf)

**Comment by kthyng** [comment]
Hi @usethedata! You've been suggested as the editor for this submission. Interested?

**Comment by kthyng** [comment]
@whedon invite @usethedata as editor

**Comment by whedon** [comment]
@usethedata has been invited to edit this submission.

**Comment by kthyng** [comment]
Sorry @usethedata — I got my tabs mixed up. Please ignore this invitation. I will go invite you on the proper tab!

**Comment by kthyng** [comment]
@lorenanicole! Are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @lorenanicole as editor

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by onurvarol** [comment]
Dear @kthyng thank you very much starting the process for review at JOSS. As you suggested we went through the list of reviewers and tried to identify potential reviewers with the relevant expertise and interest. You can see their usernames below.

felixhenninger, davekinkead, Andytwoods, mbod, adammichaelwood, tresoldi

Thank you very much and we are excited to experience JOSS review process.

**Comment by kthyng** [comment]
@lorenanicole Just a quick ping to check out this submission to see if you can take it on!

**Comment by danielskatz** [comment]
@whedon invite @lorenanicole as editor

a different type of ping

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by lorenanicole** [comment]
Sure! Let's go for it.

**Comment by lorenanicole** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @lorenanicole

**Comment by lorenanicole** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.52 s (220.3 files/s, 167381.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      39          10830          12986          51612
CSS                              8            108             95           7475
JSON                            41              2              0           1340
Sass                             3             86              0            551
Markdown                         9            196              0            380
HTML                             5             55              5            335
SVG                              1              0              0            288
TeX                              1             12              0            103
Ruby                             2             10              2             38
Bourne Shell                     3             20              8             29
Python                           1             12              0             24
YAML                             1              0              0              5
-------------------------------------------------------------------------------
SUM:                           114          11331          13096          62180
-------------------------------------------------------------------------------


Statistical information for the repository '2530' was gathered on 2020/08/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ovarol2005@gmail.com            26         75173            576           49.72
uluturki                        46         75636            971           50.28

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
ovarol2005@gmail.com      74456           99.0         12.2               17.36
uluturki                  74776           98.9         13.0               17.63
```

**Comment by lorenanicole** [comment]
@onurvarol wow what a collection of potential reviewers you have collected [here](https://bit.ly/joss-reviewers). As we need two, any you have particular recommendations on?

**Comment by onurvarol** [comment]
@lorenanicole, we want to have multiple options, incase they might not be available. Feel free to choose any two reviewers, they are all have interests and expertise that might match with the project.

**Comment by lorenanicole** [comment]
OK, that works @onurvarol !

**Comment by lorenanicole** [comment]
@nhejaz, your name was provided as a possible reviewer for this submission for JOSS. Would you be interested in reviewing?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by lorenanicole** [comment]
@rdrr1990, your name was provided as a possible reviewer for this submission for JOSS. Would you be interested in reviewing?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by nhejazi** [comment]
Unfortunately, I will not be able to provide a timely review at this time due to outstanding commitments and deadlines.

**Comment by onurvarol** [comment]
Dear @lorenanicole, @nhejazi was unavailable and @rdrr1990 haven't responded. How should we proceed?

**Comment by onurvarol** [comment]
Dear @lorenanicole it's been almost a month since we last attempted to assign a  reviewer for our submission. Can we make another attempt?

**Comment by lorenanicole** [comment]
@onurvarol let's pull in some more folks. Thank you!

**Comment by lorenanicole** [comment]
@emilydolson & @ajoer your names were provided as a possible reviewer for this submission for JOSS. Would you be interested in reviewing?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by lorenanicole** [comment]
@onurvarol if we find we are still casting too wide a net, it can be better for us to better microtarget individuals. We can timebox this for a shorter time window. I'll flag to circle back by end of week.

**Comment by lorenanicole** [comment]
> @emilydolson & @ajoer your names were provided as a possible reviewer for this submission for JOSS. Would you be interested in reviewing?
> 
> We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Hi. Just bumping this! Thanks!

**Comment by lorenanicole** [comment]
@onurvarol did you happen to have from your list of reviewers and explicit names to target? Since we have such a large list I wonder if we'd have better success by strategically reaching out to folks that you can shortlist for us.

**Comment by onurvarol** [comment]
@lorenanicole earlier I listed a larger list of potential reviewers but we only tried to reach out couple of them. Please help me invite from the list below, they are all have relevant experience and interest on this project.

felixhenninger, davekinkead, Andytwoods, mbod, adammichaelwood, tresoldi

**Comment by lorenanicole** [comment]
Thanks @onurvarol that sounds great!

**Comment by lorenanicole** [comment]
@adammichaelwood & @davekinkead would you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by adammichaelwood** [comment]
I do not have capacity for that at this time.

**Comment by davekinkead** [comment]
@lorenanicole happy to review this

**Comment by lorenanicole** [comment]
@felixhenninger, we're looking for one more editor for this JOSS submission! Would you be willing to review this?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by lorenanicole** [comment]
@whedon invite @davekinkead as editor

**Comment by whedon** [comment]
I'm sorry @lorenanicole, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by lorenanicole** [comment]
@whedon assign @davekinkead as reviewer

**Comment by whedon** [comment]
OK, @davekinkead is now a reviewer

**Comment by lorenanicole** [comment]
Great, @davekinkead! Once we have another reviewer confirmed, we'll open up a review issue for you!

**Comment by sara-02** [comment]
Hey @lorenanicole and @onurvarol I would be happy to review this package. I and my colleagures are actively working in the area of Twitter data collection and manual annotations, and would love to check out this package.
I just wrapped 2 of my pending reviews and have room for more.
Availablity: Fom 23rd Oct onwards. Let me know if it works for you guys.

**Comment by arfon** [comment]
:wave: @lorenanicole - I'm going to go ahead and add @sara-02 here as a reviewer and move this to review.

**Comment by arfon** [comment]
@whedon add @sara-02 as reviewer

**Comment by whedon** [comment]
OK, @sara-02 is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2780.

**Comment by arfon** [comment]
@davekinkead, @sara-02 - thank you both so much for agreeing to review this submission! @lorenanicole will be your editor over in #2780 - I'm just helping out here as one of the EiCs on rotation to move this forward.

See you over in #2780 where the actual review will take place.
