### ISSUE TITLE
[PRE REVIEW]: SALSA: A Python Package for Constructing Synthetic Quasar Absorption Line Catalogs from Astrophysical Hydrodynamic Simulations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2532]
**Submitting author:** @biboyd (<a href="http://orcid.org/0000-0002-5419-9751">Brendan Boyd</a>)
**Repository:** <a href="https://github.com/biboyd/SALSA" target ="_blank">https://github.com/biboyd/SALSA</a>
**Version:** v0.1.0
**Editor:** @danielskatz
**Reviewers:** @olebole, @zpace
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @biboyd. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @harpolea.

@biboyd if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.29 s (91.6 files/s, 14760.9 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           13            568            957           1314
reStructuredText                  5            159             79            346
Markdown                          2             27              0            176
TeX                               1              9              0            167
YAML                              4             15              8             83
Bourne Again Shell                1              5              3             14
Jupyter Notebook                  1              0            406             14
--------------------------------------------------------------------------------
SUM:                             27            783           1453           2114
--------------------------------------------------------------------------------


Statistical information for the repository '2532' was gathered on 2020/07/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Brendan Boyd                     4            25             17            0.05
Brendan Isaac Seaton             9            32             37            0.08
biboyd                          68         11753          14264           32.02
boydbre1                       301         29635          25484           67.84

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
biboyd                     2722           23.2          0.7               13.96
boydbre1                    117            0.4          1.8               21.37
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1146/annurev-astro-091916-055240 is OK
- 10.3847/1538-4357/aa7d04 is OK
- 10.3847/1538-4357/aa7e2d is OK
- 10.3847/1538-4357/aadd03 is OK
- 10.3847/1538-4357/aa87b4 is OK
- 10.1088/0004-637X/731/1/6 is OK
- 10.1088/0004-637X/791/1/64 is OK
- 10.3847/1538-4357/ab0654 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02532/joss.02532/10.21105.joss.02532.pdf)

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@xuanxu - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @xuanxu as editor

**Comment by whedon** [comment]
@xuanxu has been invited to edit this submission.

**Comment by xuanxu** [comment]
@danielskatz I can't take it, I don't have bandwidth right now.

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @biboyd - please add an explicit section title Statement of Need to the paper - see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

Once you have done this, please enter ```@whedon generate pdf``` as a new command here to regenerate the pdf.

**Comment by danielskatz** [comment]
Also, please suggest potential reviewers by mentioning them here in this thread (without tagging them with an @). [This list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list), or you may know of others in this field.  I will also check for reviewers through some other channels.

**Comment by danielskatz** [comment]
👋 @chummels & @brittonsmith - would one of you be willing to review this submission to JOSS?  I am aware you are acknowledged in the paper, but I also think this is likely not a COI. Let me know what you think.

If you're not familiar with JOSS's review style/guidelines, we are basically checklist driven and use GitHub, where reviewers, editors, and authors work openly and iteratively to ideally improve submissions to the point where they can be accepted.  See https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by biboyd** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02532/joss.02532/10.21105.joss.02532.pdf)

**Comment by biboyd** [comment]
A couple of names on the list that could be good reviewers might be eteq or olebole

**Comment by danielskatz** [comment]
👋 eteq & olebole - would one of you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
@biboyd - I also notice that a number of your references seem to be missing journals - which in our style, makes them incomplete.  Please add the journals or conferences for all references.

**Comment by danielskatz** [comment]
👋 @chummels & @brittonsmith - just checking with you again, and hoping that one of you will be willing to do this.

> 👋 @chummels & @brittonsmith - would one of you be willing to review this submission to JOSS? I am aware you are acknowledged in the paper, but I also think this is likely not a COI. Let me know what you think.
> 
> If you're not familiar with JOSS's review style/guidelines, we are basically checklist driven and use GitHub, where reviewers, editors, and authors work openly and iteratively to ideally improve submissions to the point where they can be accepted. See https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by danielskatz** [comment]
👋 eteq & olebole - just checking with you again, and hoping that one of you will be willing to do this.

> 👋 eteq & olebole - would one of you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
👋 @eteq & @olebole - would one of you be willing to review this JOSS submission?

**Comment by brittonsmith** [comment]
@danielskatz, sorry for the delay in getting back to you. I work quite closely with the authors and attend regular meetings with them. I'm not sure if that is too close, but I am really drowning this summer. I just can't spare the time. My apologies. I can think of a couple people who would do an excellent job at this: neutrinoceros and cphyc. I hope they can help.

**Comment by danielskatz** [comment]
👋  @neutrinoceros and @cphyc - would one of you be willing to review this submission to JOSS? If you're not familiar with JOSS's review style/guidelines, we are basically checklist driven and use GitHub, where reviewers, editors, and authors work openly and iteratively to ideally improve submissions to the point where they can be accepted. See https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by cphyc** [comment]
@danielskatz, I would be willing to review this submission but won't be able to do so until the beginning of September.

**Comment by danielskatz** [comment]
Thanks @cphyc - let's see if we can find 2 reviewers before then, but if not, I will take you up on your offer.

**Comment by neutrinoceros** [comment]
@danielskatz I don't think I'll have time for this in the foreseeable future unfortunately, but feel free to ping me again in a month if you're still looking, things might change !

**Comment by olebole** [comment]
I could do it next week. Would that be ok?

**Comment by danielskatz** [comment]
thanks @olebole  - I'll add you as a reviewer, but we won't start the review until I also find a second reviewer.

**Comment by danielskatz** [comment]
@whedon assign @olebole as reviewer

**Comment by whedon** [comment]
OK, @olebole is now a reviewer

**Comment by danielskatz** [comment]
👋 @namurphy - would you be willing to review this submission to JOSS? You were suggested by a colleague at CfA.

If you're not familiar with JOSS's review style/guidelines, we are basically checklist driven and use GitHub, where reviewers, editors, and authors work openly and iteratively to ideally improve submissions to the point where they can be accepted. See https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by danielskatz** [comment]
👍 @marcocamma - would you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
@biboyd - sorry this is taking longer than expected to find a second reviewer - I'm still working on it

**Comment by danielskatz** [comment]
👋 @namurphy & @marcocamma - I'm just checking with you again to see if one of you would be able to review this submission

**Comment by danielskatz** [comment]
👋 @cwchurchill-DrQSO, @gkacprzak, MTMurphy77 - would one of you be willing to review this submission to JOSS? You were suggested by a colleague at CfA.

If you're not familiar with JOSS's review style/guidelines, we are basically checklist driven and use GitHub, where reviewers, editors, and authors work openly and iteratively to ideally improve submissions to the point where they can be accepted. See https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by danielskatz** [comment]
👋 @zpace  - would you be willing to review this JOSS submission?

**Comment by gkacprzak** [comment]
HI Daniel,

I am sorry, I just don't have the time. With full lockdown in Australia, no daycare, and two full time jobs are making it impossible to do this at this time.
Sorry about that.

Thank you,
Glenn

-----------------------------------------------------------

A/Prof. Glenn G. Kacprzak

Centre for Astrophysics & Supercomputing
Swinburne University of Technology
H29, PO Box 218,
Hawthorn, Victoria 3122, Australia
http://astronomy.swin.edu.au/~gkacprzak
Phone: +61 (0)3 9214 5439
Fax: +61 (0)3 9214 8797
-----------------------------------------------------------

________________________________

**Comment by zpace** [comment]
Yes, I think I can commit to this.

**Comment by danielskatz** [comment]
Thanks @zpace  - I'll add you, and we'll start in a new review issue

**Comment by danielskatz** [comment]
@whedon add @zpace as reviewer

**Comment by whedon** [comment]
OK, @zpace is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2581.
