### ISSUE TITLE
[REVIEW]: OmniCV - A library for Omnidirectional Cameras

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2533]
**Submitting author:** @kaustubh-sadekar (<a href="http://orcid.org/0000-0001-8895-5319">kaustubh sadekar</a>)
**Repository:** <a href="https://github.com/kaustubh-sadekar/OmniCV-Lib" target ="_blank">https://github.com/kaustubh-sadekar/OmniCV-Lib</a>
**Version:** v1.0
**Editor:** @mjsottile
**Reviewer:** @nnadeau, @ionlights
**Archive:** Pending

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ae3115c7075a5d80ef4b441427b62117/status.svg)](https://joss.theoj.org/papers/ae3115c7075a5d80ef4b441427b62117)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ae3115c7075a5d80ef4b441427b62117"><img src="https://joss.theoj.org/papers/ae3115c7075a5d80ef4b441427b62117/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ae3115c7075a5d80ef4b441427b62117/status.svg)](https://joss.theoj.org/papers/ae3115c7075a5d80ef4b441427b62117)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kaustubh-sadekar/OmniCV-Lib" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nnadeau & @ionlights, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mjsottile know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kaustubh-sadekar/OmniCV-Lib">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@kaustubh-sadekar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kaustubh-sadekar/OmniCV-Lib">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@kaustubh-sadekar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nnadeau, @ionlights it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-0-387-31439-6_488 is OK
- 10.1145/3278471.3278479 is OK
- 10.1016/j.cviu.2006.06.003 is OK
- 10.1007/3-540-45053-X_29 is OK
- 10.1007/PL00013269 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- https://doi.org/10.1109/icra.2016.7487210 may be missing for title: Benefit of large field-of-view cameras for visual odometry
- https://doi.org/10.1007/978-3-030-20876-9_3 may be missing for title: CubemapSLAM: A Piecewise-Pinhole Monocular Fisheye SLAM System
- https://doi.org/10.1109/3dv.2018.00069 may be missing for title: The Double Sphere Camera Model
- https://doi.org/10.1109/icassp.2016.7471935 may be missing for title: A data set providing synthetic and real-world fisheye video sequences

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02533/joss.02533/10.21105.joss.02533.pdf)

**Comment by mjsottile** [comment]
@kaustubh-sadekar While the reviewers start to conduct their reviews, you should address the issues flagged above by the check references command regarding missing DOIs.

**Comment by kaustubh-sadekar** [comment]
> @kaustubh-sadekar While the reviewers start to conduct their reviews, you should address the issues flagged above by the check references command regarding missing DOIs.

@mjsottile Thank you very much. I have verified all the missing DOIs and have added them to the paper.bib file.

**Comment by kaustubh-sadekar** [comment]
@whedon generate pdf

**Comment by kaustubh-sadekar** [comment]
@whedon check references

**Comment by whedon** [comment]
PDF failed to compile for issue #2533 with the following error: 

 pandoc: getCurrentDirectory:getWorkingDirectory: does not exist (Current working directory no longer exists)
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-0-387-31439-6_488 is OK
- 10.1109/ICRA.2016.7487210 is OK
- 10.1145/3278471.3278479 is OK
- 10.1016/j.cviu.2006.06.003 is OK
- 10.1007/978-3-030-20876-9_3 is OK
- 10.1109/3DV.2018.00069 is OK
- 10.1007/3-540-45053-X_29 is OK
- 10.1007/PL00013269 is OK
- 10.1109/ICASSP.2016.7471935 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by nnadeau** [comment]
@mjsottile , thanks for checking in. I'm waiting for some progress on the linked PRs/issues before completing my review.

**Comment by mjsottile** [comment]
:wave: @ionlights - you had mentioned that you were busy until mid-August when we opened the review, so I assume you've been busy with your pre-existing commitment.  Does it look like you'll have capacity to handle the review in the not-too-distant future?  No pressure to rush - I'm just checking to make sure you're still interested and available.

**Comment by mjsottile** [comment]
👋 @kaustubh-sadekar I wanted to check to see if you were proceeding with the changes requested as part of the review.  I want to make sure the submission doesn’t go stale and get forgotten.

**Comment by kaustubh-sadekar** [comment]
Yes, definitely @mjsottile . I have made several changes based on valuable guidance and suggestions by @nnadeau and I am improving things further. I have also added comments on respective open issues to update about my progress. I am giving my best efforts to make all the suggested changes. Thank you very much for checking in.

**Comment by nnadeau** [comment]
@kaustubh-sadekar let me know when you're ready for another round of reviews 😀👍

**Comment by kaustubh-sadekar** [comment]
Sure. I am facing some errors with virtual environment setup and GitHub CI/CD. Its should be resolved soon.

**Comment by kaustubh-sadekar** [comment]
@nnadeau thank you very much for the reviews, they helped me a lot to learn about testing and deployment. I have completed all the modifications based on your reviews and suggestions. So yes :+1:  ... ready for the next round of reviews and looking forward to learning from them.

**Comment by mjsottile** [comment]
Hi @kaustubh-sadekar - I am in the process of seeking out a replacement reviewer for the second reviewer who has gone silent.  I am hoping to find a responsive second reviewer soon so that your review doesn't get stuck.

**Comment by nnadeau** [comment]
sounds good @kaustubh-sadekar . I'll try to schedule some time this weekend to finish my review :)

**Comment by kaustubh-sadekar** [comment]
> Hi @kaustubh-sadekar - I am in the process of seeking out a replacement reviewer for the second reviewer who has gone silent. I am hoping to find a responsive second reviewer soon so that your review doesn't get stuck.

Sure. No problem and thank you so much @mjsottile

**Comment by nnadeau** [comment]
@kaustubh-sadekar @mjsottile did another review pass. There are some fundamental issues to be addressed, primarily around the significance of the work. As outlined in https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/32 and https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/29, the code appears to mainly be conversion wrappers (e.g., `X to Y`). I'm not convinced that a researcher wouldn't just implement their own math/wrapper instead of pulling in an external dependency. Personally, from a software management point of view, I would need a very good value proposition of why this external project is necessary over just doing it myself. 

Moreover, if the library is live up to the statements in `paper/paper.md` (e.g., `Quick and easy to use API [...]`, `Detailed documentation [...]`, `[...] easily compatible and manageable for future updates`), then there are fundamental code quality updates that are also needed. Please review and address the many issues I've submitted to the repo (https://github.com/kaustubh-sadekar/OmniCV-Lib/issues?page=1&q=author%3Annadeau). I'm especially concerned about:

- https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/34
- https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/31
- https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/26
- https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/25
- https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/23
- https://github.com/kaustubh-sadekar/OmniCV-Lib/issues/18

**Comment by kaustubh-sadekar** [comment]
It is completely true that the researchers who are proficient in writing quick and efficient code would be able to write not just the functionalities provided in the OmniCV package but any other functionalities required in their research. They would hardly need to depend on any external library. But, writing even a small piece of code, even for such researchers would utilize some of their productive time. Also, considering a more general perspective which includes researchers with intermediate proficiency in writing fast and efficient code, this library contains several functionalities that would save a fair amount of development time helping them to focus on other aspects of their research and hence promote the research process. The functionalities are provided in the two widely used programming languages in robotics research (Python and C++) and even examples for ROS nodes are provided to fulfill the same objective.  Constant and sincere efforts have been made to improve the library respecting all the suggestions provided in the reviews. After following all the valuable suggestions provided in the review process, this library will definitely save a fair amount of development time as its final updated version would contain detailed documentation, a Make file to simplify the entry point (considering a more general perspective about the coding proficiency of a user), automated testing along with continuous integration and development workflow and code which follows all the standard coding practices. Sincere efforts will be further put in to improve the library, respecting all the suggestions provided in the review process.

**Comment by mjsottile** [comment]
Hello @kaustubh-sadekar,

Based on review feedback, my own examination of the submission, and a discussion with other editors, your submission unfortunately does not meet the threshold for acceptance into JOSS.  There are a number of rather significant issues related to software quality and the submission does not make a clear contribution to the research software community.  I hope that you take the feedback that the review process has provided and are able to refine your package.  You may consider resubmitting in the future if you feel you’ve made substantial improvements such that it would meet expectations for an acceptable JOSS publication.  

Thank you @nnadeau for your patient and detailed reviews - you went above and beyond in your feedback and I greatly appreciate it.

**Comment by mjsottile** [comment]
@whedon reject

**Comment by whedon** [comment]
I'm sorry @mjsottile, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
