### ISSUE TITLE
[PRE REVIEW]: Neuropsydia.py: A Python Module for Creating Experiments, Tasks and Questionnaires

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#254]
**Submitting author:** @DominiqueMakowski (<a href="http://orcid.org/0000-0001-5375-9967">Dominique Makowski</a>)
**Repository:** <a href="https://github.com/neuropsychology/Neuropsydia.py/" target ="_blank">https://github.com/neuropsychology/Neuropsydia.py/</a>
**Version:** 1.0.4
**Editor:** @arokem
**Reviewer:** @cMadan

**Author instructions**

Thanks for submitting your paper to JOSS @DominiqueMakowski. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@DominiqueMakowski if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arokem** [comment]
@cMadan : would you like to review this for JOSS?

**Comment by cMadan** [comment]
Sure, I can be a reviewer for this

**Comment by arokem** [comment]
@whedon assign @cMadan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @cMadan

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/259. Feel free to close this issue now!

**Comment by arokem** [comment]
Thanks @cMadan! 

Please head over to the aforementioned issue for the review itself. 

I will close this one.
