### ISSUE TITLE
[PRE REVIEW]: maxsmooth: Derivative Constrained Function Fitting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2540]
**Submitting author:** @htjb (<a href="http://orcid.org/0000-0002-4367-3550">Harry Bevins</a>)
**Repository:** <a href="https://github.com/htjb/maxsmooth" target ="_blank">https://github.com/htjb/maxsmooth</a>
**Version:** v1.1.0
**Editor:** @dfm
**Reviewers:** @smutch, @benjaminpope
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @htjb. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@htjb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (173.5 files/s, 24835.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          19            651            572           2644
reStructuredText                11            216            212            416
TeX                              1             16              0            196
Markdown                         1             28              0            107
YAML                             2              7              5             28
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            36            930            797           3426
-------------------------------------------------------------------------------


Statistical information for the repository '2540' was gathered on 2020/08/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
htjb                           129         47924          44057          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
htjb                       3867            8.1          1.5                3.00
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.physrep.2006.08.002 is OK
- 10.1016/j.physrep.2016.06.006 is OK
- 10.1088/0034-4885/75/8/086901 is OK
- 10.1086/146653 is OK
- 10.1086/106661 is OK
- 10.1093/mnras/stx2065 is OK
- 10.1007/s10686-018-9584-3 is OK
- 10.1093/mnras/sty1244 is OK
- 10.1142/S2251171719500041 is OK
- 10.3847/1538-4357/aa69bd is OK
- 10.3847/1538-4357/ab2879 is OK
- 10.1021/jp970984n is OK
- 10.1093/comjnl/7.4.308 is OK

MISSING DOIs

- https://doi.org/10.1109/iceaa.2019.8879199 may be missing for title: REACH: Radio Experiment for the Analysis of Cosmic Hydrogen

INVALID DOIs

- https://doi.org/10.1038/nature25792 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02540/joss.02540/10.21105.joss.02540.pdf)

**Comment by kthyng** [comment]
@dfm could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by kthyng** [comment]
@htjb Please add a Statement of Need to your paper.

**Comment by htjb** [comment]
Hi @kthyng, the first section in the paper after the summary is essentially a Statement of Need. I can make this more explicit if required or indeed change the title of the section?

**Comment by htjb** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02540/joss.02540/10.21105.joss.02540.pdf)

**Comment by htjb** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.physrep.2006.08.002 is OK
- 10.1016/j.physrep.2016.06.006 is OK
- 10.1088/0034-4885/75/8/086901 is OK
- 10.1086/146653 is OK
- 10.1086/106661 is OK
- 10.1093/mnras/stx2065 is OK
- 10.1109/ICEAA.2019.8879199 is OK
- 10.1007/s10686-018-9584-3 is OK
- 10.1093/mnras/sty1244 is OK
- 10.1142/S2251171719500041 is OK
- 10.1038/nature25792 is OK
- 10.3847/1538-4357/aa69bd is OK
- 10.3847/1538-4357/ab2879 is OK
- 10.1021/jp970984n is OK
- 10.1093/comjnl/7.4.308 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@htjb Thanks for the change, yes, we do indeed want the explicit heading name.

**Comment by htjb** [comment]
@kthyng Not a problem and thank you for highlighting this

**Comment by dfm** [comment]
@htjb: I noticed some overlap between this submission and the preprint at https://arxiv.org/abs/2007.14970. It looks like the preprint has been submitted to MNRAS - is that true? Can you tell us a bit more about the connection between these two submissions? Thanks!

**Comment by htjb** [comment]
@dfm There shouldn't be any direct overlap between the text in this draft and the preprint for MNRAS. Where I have used the same figure for this draft and the preprint I have referenced the preprint. We are intending to submit to MNRAS later this week after receiving some community feedback on the preprint. The MNRAS paper is intended to outline the algorithm for the 21-cm cosmology community and look in more detail at it's applications to 21-cm cosmology. We also wanted to submit to JOSS to get the code reviewed. I hope that is clear, let me know if there are any problems with this. Thanks.

**Comment by kthyng** [comment]
@dfm I'll assume you're taking this over, thanks.

**Comment by kthyng** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@kthyng: Sure thing - thanks!

**Comment by dfm** [comment]
@htjb: Just a quick update here. I'm still working on finding reviewers and I'll keep you posted as I do. Sorry for the delay and thanks for your patience!

**Comment by htjb** [comment]
@dfm No problem, thank you for the update!

**Comment by dfm** [comment]
@smutch and @benjaminpope have kindly agreed to review this submission - thanks Simon and Ben!

I'll add you both as reviewers and then get the review started. Let me know if any of you have any questions as things progress.

**Comment by dfm** [comment]
@whedon assign @smutch as reviewer

**Comment by whedon** [comment]
OK, @smutch is now a reviewer

**Comment by dfm** [comment]
@whedon add @benjaminpope as reviewer

**Comment by whedon** [comment]
OK, @benjaminpope is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2596.

**Comment by dfm** [comment]
@htjb, @smutch, @benjaminpope: We can head over to #2596 now for the main review where you'll find more instructions and the reviewer checklists. See you all there!
