### ISSUE TITLE
[PRE REVIEW]: ShinyJWAS: Shiny-based Application to Help Perform Whole-genome Bayesian Regression Analysis with JWAS package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2541]
**Submitting author:** @justinwang97 (<a href="http://orcid.org/0000-0002-1472-593X">Zigui Wang</a>)
**Repository:** <a href="https://github.com/QTL-rocks/ShinyJWAS.git" target ="_blank">https://github.com/QTL-rocks/ShinyJWAS.git</a>
**Version:** v0.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @justinwang97. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@justinwang97 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (324.4 files/s, 61888.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                4            391            130           1183
Markdown                         4             51              0            114
TeX                              1              2              0             33
JavaScript                       1              1              0              3
-------------------------------------------------------------------------------
SUM:                            10            445            130           1333
-------------------------------------------------------------------------------


Statistical information for the repository '2541' was gathered on 2020/08/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Zigui Wang                       1             4              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Zigui Wang                    4          100.0          0.0                0.00
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02541/joss.02541/10.21105.joss.02541.pdf)

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by justinwang97** [comment]
@whedon <https://github.com/whedon> commands

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by justinwang97** [comment]
@whedon <https://github.com/whedon> commands

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by justinwang97** [comment]
@whedon <https://github.com/whedon> generate pdf

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by justinwang97** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02541/joss.02541/10.21105.joss.02541.pdf)

**Comment by danielskatz** [comment]
@justinwang97 - you will probably find whedon much easier to work with via the github web interface, rather than via the email interface.

**Comment by justinwang97** [comment]
Hi:
I see, thanks for the clarification!

Best,
Zigui Wang

**Comment by justinwang97** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by kyleniemeyer** [comment]
Hello @justinwang97, the JOSS editorial board considered your submission, and we have decided that the software does not meet our requirement for substantial scholarly effort—see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort. (This is not a statement about the usefulness of your software.) We encourage you to consider publishing the software to Zenodo to get a DOI that users can cite.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
