### ISSUE TITLE
[PRE REVIEW]: GenGrab: A python toolkit for acquiring gene segments from genomes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2544]
**Submitting author:** @vikaszsi77 (<a href="http://orcid.org/0000-0002-0215-0120">Vikas Kumar</a>)
**Repository:** <a href="https://github.com/avvypaks/GenGrab" target ="_blank">https://github.com/avvypaks/GenGrab</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vikaszsi77. **Currently, there isn't an JOSS editor assigned** to your paper.

@vikaszsi77 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (111.1 files/s, 4909.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2             14              0             72
Python                           2             30              8             53
TeX                              1              5              0             39
-------------------------------------------------------------------------------
SUM:                             5             49              8            164
-------------------------------------------------------------------------------


Statistical information for the repository '2544' was gathered on 2020/08/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
avvypaks                         3           161             73           82.11
goirikdg                         6            27             24           17.89

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
avvypaks                     84           52.2          0.0                4.76
goirikdg                      7           25.9          0.0               28.57
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1093/jhered/ess052 may be missing for title: GenScalpel: an application for sequence retrieval and extraction from the GenBank flatfile
- https://doi.org/10.25080/majora-92bf1922-00a may be missing for title: Data structures for statistical computing in python
- https://doi.org/10.25080/majora-92bf1922-00a may be missing for title: Data structures for statistical computing in python

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02544/joss.02544/10.21105.joss.02544.pdf)

**Comment by danielskatz** [comment]
@vikaszsi77  - Unfortunately, this software is not packaged for reuse and is quite small.  It does not meet the JOSS [Substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
