### ISSUE TITLE
[PRE REVIEW]: DYCO: A Python package to dynamically detect and compensate for time lags in ecosystem time series

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2545]
**Submitting author:** @holukas (<a href="http://orcid.org/0000-0002-5569-0761">Lukas Hörtnagl</a>)
**Repository:** <a href="https://gitlab.ethz.ch/holukas/dyco-dynamic-lag-compensation" target ="_blank">https://gitlab.ethz.ch/holukas/dyco-dynamic-lag-compensation</a>
**Version:** v1.0.1
**Editor:** @KristinaRiemer
**Reviewers:** @mccabete, @r-barnes
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @holukas. **Currently, there isn't an JOSS editor assigned** to your paper.

@holukas if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2307/1941631 is OK
- 10.5194/amt-8-4197-2015 is OK
- 10.1016/S0022-1694(96)03194-0 is OK
- 10.1111/gcb.12518 is OK
- 10.1007/BF00128405 is OK
- 10.1515/intag-2017-0042 is OK
- 10.1111/gcb.14079 is OK
- 10.1007/978-94-007-2351-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (384.4 files/s, 65339.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            600           1028           1891
XML                             13              0              0           1021
TeX                              1              9              0            146
YAML                             1              1              0            115
Markdown                         2             53              0             65
-------------------------------------------------------------------------------
SUM:                            29            663           1028           3238
-------------------------------------------------------------------------------


Statistical information for the repository '2545' was gathered on 2020/08/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
holukas                         28         14151          11214          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
holukas                    3519           24.9          0.7               13.75
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02545/joss.02545/10.21105.joss.02545.pdf)

**Comment by danielskatz** [comment]
👋 @KristinaRiemer - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @KristinaRiemer as editor

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by KristinaRiemer** [comment]
@danielskatz yes I can.

**Comment by KristinaRiemer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @KristinaRiemer

**Comment by KristinaRiemer** [comment]
@whedon assign @mccabete as reviewer

**Comment by whedon** [comment]
OK, @mccabete is now a reviewer

**Comment by KristinaRiemer** [comment]
@camillescott @r-barnes @dirmeier would any of you be able to review this submission?

**Comment by dirmeier** [comment]
Hi @KristinaRiemer , I am sorry I don't have time right now. Cheers, Simon

**Comment by KristinaRiemer** [comment]
@camillescott @r-barnes @sgrieve @nmstreethran would any of y'all be able to review this submission for JOSS?

**Comment by r-barnes** [comment]
Sure.

**Comment by KristinaRiemer** [comment]
Excellent! Thanks @r-barnes.

**Comment by KristinaRiemer** [comment]
@whedon add @r-barnes as reviewer

**Comment by whedon** [comment]
OK, @r-barnes is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2575.

**Comment by KristinaRiemer** [comment]
@mccabete @r-barnes if you want to check out the issue linked to in the above comment, that is where the actual review will take place and let me know if you have questions!
