### ISSUE TITLE
[PRE REVIEW]: s4rdm3x: A Tool Suite to Explore Code to Architecture Mapping Techniques

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2546]
**Submitting author:** @tobias-dv-lnu (<a href="http://orcid.org/0000-0003-1154-5308">Tobias Olsson</a>)
**Repository:** <a href="https://github.com/tobias-dv-lnu/s4rdm3x" target ="_blank">https://github.com/tobias-dv-lnu/s4rdm3x</a>
**Version:** 1.2
**Editor:** @gkthiruvathukal
**Reviewers:** @kinow, @xirdneh
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tobias-dv-lnu. **Currently, there isn't an JOSS editor assigned** to your paper.

@tobias-dv-lnu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2546 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2546 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-3c447da9bd61/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-3c447da9bd61/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-3c447da9bd61/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
note that I've manually changed the submitted repo to the repo (it was a link down to the paper)

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02546/joss.02546/10.21105.joss.02546.pdf)

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.25 s (415.2 files/s, 115018.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           310              8           8901          85039
JavaScript                      14           3801           5604          16213
Java                           170           4596           2063          14542
CSS                              5             43            134           1446
Bourne Shell                     2             42             44            258
Markdown                         6             70              0            147
DOS Batch                        2             46              4            118
Gradle                           3             46             22            115
TeX                              1              8              0             90
YAML                             5             12              0             77
-------------------------------------------------------------------------------
SUM:                           518           8672          16772         118045
-------------------------------------------------------------------------------


Statistical information for the repository '2546' was gathered on 2020/08/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Tobias Olsson                  170        111717          53675           99.99
tobias-dv-lnu                    1            12             11            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Tobias Olsson             57861           51.8          6.5               17.50
tobias-dv-lnu                12          100.0          3.2               83.33
```

**Comment by danielskatz** [comment]
@gkthiruvathukal - would you be able to edit this submission? (If your plate is full with other reviews, that's fine too.)

**Comment by danielskatz** [comment]
@whedon invite @gkthiruvathukal as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by gkthiruvathukal** [comment]
@danielskatz Yes,  I can take this one on. This might be the last I can take on for a couple of weeks as I have to record a bunch of lectures for my upcoming classes this term.  I won't go into OOO mode as I plan to see all submissions through, but I am going to need to pause on new ones just for a short time.  By the way, I am assuming you meant to invite me as an editor, right?

**Comment by danielskatz** [comment]
Thanks, and yes, as editor - my fingers were moving independently of my brain :)

**Comment by danielskatz** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@tobias-dv-lnu I am ready to start review on this submission. If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by tobias-dv-lnu** [comment]
Great! I have no real suggestions but I went through the list from the bottom and compiled a list of reviewers that could be suitable (basically checking the preferred language to be Java, and some interest in software engineering).

Super short list:
bzz, chrisma

Short list:
kinow, shanamatthews, UTH-Tuan, bzz, chrisma, mado89, neurons, dghoshal-lbl, sonal-raj, jaynanavati, hainesr, arcuri82, xirdneh

**Comment by gkthiruvathukal** [comment]
@neurons and @sonal-raj, Are you willing to contribute a review for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@xirdneh and @kinow, Are you willing to contribute a review for this JOSS submission?

**Comment by xirdneh** [comment]
@gkthiruvathukal I'll take a quick look tomorrow see if it falls under my area of expertise.

**Comment by kinow** [comment]
I think a friend of mine was doing some bytecode analysis, but something much simpler than `s4rdm3x` (I think it was simply looking for patterns in the bytecode or in the abstract syntax tree). `s4rdm3x` looks interesting!

Would be happy to review this one @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
Thanks, @kinow! I will assign you now.

**Comment by gkthiruvathukal** [comment]
@whedon assign @kinow as reviewer

**Comment by whedon** [comment]
OK, @kinow is now a reviewer

**Comment by gkthiruvathukal** [comment]
@xirdneh Thanks! I hope you will say yes. It is not always important to be an "expert". Being knowledgeable will do. Let me know tomorrow if you can so I can start review.

**Comment by arfon** [comment]
:wave: @gkthiruvathukal - it looks like this submission is still waiting on you to find a second reviewer?

**Comment by gkthiruvathukal** [comment]
@arfon Yes, I'll get on it! Thanks for the gentle nudge.

**Comment by gkthiruvathukal** [comment]
@xirdneh  Can you let me know if you have decided whether you can participate as a reviewer for this submission?

**Comment by xirdneh** [comment]
@gkthiruvathukal Yes, I can review this.
IS it OK if I submit the review by next week?

**Comment by gkthiruvathukal** [comment]
@xirdneh Awesome. Yes, by next week is fine. But we are still in COVID-19 service mode, so we'll work with your schedule.  Thanks!!

**Comment by gkthiruvathukal** [comment]
@whedon add @xirdneh as reviewer

**Comment by whedon** [comment]
OK, @xirdneh is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2791.
