### ISSUE TITLE
[REVIEW]: PyAutoFit`: A Classy Probabilistic Programming Language for Model Composition and Fitting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2550]
**Submitting author:** @Jammy2211 (<a href="http://orcid.org/0000-0002-8987-7401">James Nightingale</a>)
**Repository:** <a href="https://github.com/rhayes777/PyAutoFit" target ="_blank">https://github.com/rhayes777/PyAutoFit</a>
**Version:** v0.72.2
**Editor:** @dfm
**Reviewers:** @arm61, @karllark
**Archive:** <a href="https://doi.org/10.5281/zenodo.4497861" target="_blank">10.5281/zenodo.4497861</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/72dd73121caeb8404e34d392331f907d/status.svg)](https://joss.theoj.org/papers/72dd73121caeb8404e34d392331f907d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/72dd73121caeb8404e34d392331f907d"><img src="https://joss.theoj.org/papers/72dd73121caeb8404e34d392331f907d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/72dd73121caeb8404e34d392331f907d/status.svg)](https://joss.theoj.org/papers/72dd73121caeb8404e34d392331f907d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/rhayes777/PyAutoFit" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arm61 & @eteq, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rhayes777/PyAutoFit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Jammy2211) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rhayes777/PyAutoFit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Jammy2211) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arm61, @eteq it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/joss.00024 is OK
- 10.21105/joss.00433 is OK
- 10.1093/mnras/staa278 is OK
- 10.1086/670067 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1093/mnras/sts633 is OK
- 10.1093/mnras/stv1455 is OK
- 10.1093/mnras/sty1264 is OK
- 10.1093/mnras/stz2220 is OK
- 10.7717/peerj-cs.55 is OK
- 10.18637/jss.v076.i01 is OK
- 10.1051/0004-6361/201322971 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK

MISSING DOIs

- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy Array: A Structure for Efficient Numerical Computation

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02550/joss.02550/10.21105.joss.02550.pdf)

**Comment by dfm** [comment]
@Jammy2211: Please address Kevin's comments from the pre-review (copied here): 

> Fixing those missing and invalid DOI's ☝️. You can call @whedon generate pdf to update the paper and you can call @whedon check references to check those references.
>
> Making your affiliations complete for the paper, i.e. include city and country (do not use acronyms for states and countries).

**Comment by dfm** [comment]
Just pinging @arm61 and @eteq to make sure that this is still on your radar. Let me know if you have any questions!

**Comment by arm61** [comment]
@dfm I was wondering are things like the "statement of need" (that is mentioned in the Documentation portion of this checklist) is expected to be in the code docs and the paper?

**Comment by arm61** [comment]
Once issues [127](https://github.com/rhayes777/PyAutoFit/issues/127) and [126](https://github.com/rhayes777/PyAutoFit/issues/126) are closed, @dfm has clarified my comments, and the referencing problems are solved I think I am happy. 

An only small point in the "state of the field" bit for the paper, is that it might be worth mentioning [`uravu`](uravu.readthedocs.io) which has similar functionality to PyAutoFit. This is not a hard issue because `uravu` is my own package and I don't wanna be an awful person.  However, I think that the similarity between the packages mean that it is worth a mention, however, I will leave that up to @Jammy2211.

**Comment by dfm** [comment]
@arm61: Thanks for the update! The statement of need should be in *both* the paper and the documentation. Let me know if you need more clarification.

**Comment by arm61** [comment]
Cheers @dfm. @Jammy2211 I think it is worth adding mention of the statement of need (covered well in the paper) to the homepage of the readthedocs.

**Comment by arm61** [comment]
Sorry that I have taken so long to complete this by the way. Life got in the way a bit!

**Comment by Jammy2211** [comment]
Great - I think I pretty much agree with all your suggestions and will get everything sorted this week :). You've definitely brought up a couple of aspects of the docs that need some polishing!

No problem on the length of time, I think everyone's stretched pretty thin at the moment and just trying to get everything done whenever its possible.

**Comment by Jammy2211** [comment]
I have responded to all suggestions :). Pretty much every single one improved the quality of the software and docs significantly, so thank you!

I have added uravu to the software list at the bottom, but not in the main body of text. uravu looks like a really cool project and shares a lot of similarity with PyAutoFit given how we both focus on emcee and dynesty. However, it doesn't take me as a probabilistic programming language (i.e. no model composition aspect), which is what the text's discussion is focused on (and is our main focus with PyAutoFit).

I think I have updated the references on the paper (I updated the .bib / .md files as necessary) but haven't been able to check to be 100% sure so let me know if there are still problems.

**Comment by Jammy2211** [comment]
Also, if you have any recommendations for logo designers please do let me know - its definitely one of the most important things we're missing. I have the artistic talents of a sponge :(.

**Comment by arm61** [comment]
100 % agree with your identification of `uravu` as not a PPL. 

Full ticks from me now! As for a logo designer, unfortunately I have always done my own (which speak volumes to my skill considering that they are usually text over a matplotlib figure...)

**Comment by dfm** [comment]
Hey @eteq, Can you give us an estimate of when you'll be able to get to this review? Thanks!

**Comment by dfm** [comment]
@Jammy2211: I wanted to send an update here. @eteq has also stopped responding to my emails so I'm in the process of finding a new second reviewer. Thanks for your patience!

**Comment by Jammy2211** [comment]
No problem! :)

**Comment by dfm** [comment]
@karllark has agreed to step in as the second reviewer. Thanks Karl! Let me know if you have any questions as we go. Whedon will add you to the review shortly.

**Comment by dfm** [comment]
@whedon add @karllark as reviewer.

**Comment by whedon** [comment]
OK, @karllark is now a reviewer

**Comment by dfm** [comment]
:wave: - @karllark any updates here? Let me know if you have any questions or if you run into any issues!

**Comment by karllark** [comment]
I will be able to carry out this review this week.  Apologies for the delay.  I plead JWST proposal deadline, holidays, and 2020.  ;-)

**Comment by Jammy2211** [comment]
No problem @karllark, JWST proposals have ruined the lives of many people around me in the past few weeks :P !

**Comment by karllark** [comment]
Once the (minor) issues https://github.com/rhayes777/PyAutoFit/issues/142 and https://github.com/rhayes777/PyAutoFit/issues/143 are closed, then I am happy and would recommend acceptance.

**Comment by dfm** [comment]
@Jammy2211: Happy new year! Do you have any updates on these remaining issues from @karllark? Let us know if you have questions or a timeline for when you're hoping to get to them. Thanks!

**Comment by Jammy2211** [comment]
Will get it done this week, shouldn't take long but putting the final touches on a release so will make sure its done with that!

Well post in here once its up.

**Comment by Jammy2211** [comment]
All done :)

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2550 with the following error:

**Comment by whedon** [comment]
PDF failed to compile for issue #2550 with the following error:

**Comment by dfm** [comment]
@Jammy2211: It looks like there's some issue with your paper which is causing the compiler to timeout (remotely and locally). I'll look into what's going on a bit more later today.

**Comment by dfm** [comment]
@whedon remove @eteq as reviewer

**Comment by whedon** [comment]
OK, @eteq is no longer a reviewer

**Comment by arfon** [comment]
@Jammy2211 @dfm - not sure what was going on here but there was something in the BibTeX entries causing compilation issues. I swapped them out here and the paper now seems to compile for me locally: https://github.com/rhayes777/PyAutoFit/pull/149

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02550/joss.02550/10.21105.joss.02550.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02550/joss.02550/10.21105.joss.02550.pdf) :page_facing_up: :point_left:

**Comment by Jammy2211** [comment]
Hopefully this is ok - I've added a third author to the paper who made a lot of contributions to the software in the past few months.

**Comment by dfm** [comment]
@Jammy2211 - Absolutely fine. Thanks for the update!

**Comment by dfm** [comment]
@Jammy2211: I've made a few more edits to the manuscript and opened a PR. Once you've taken a look at those and merged, here are the steps that we need to do before final processing:

1. Comment `@whedon generate pdf` on this issue to get the proofs of the manuscript. Read these over and double check that you're happy with it (especially things like author names and affiliations). It is difficult to make changes later.
2. Bump the version number of PyAutoFit and report the new version number back here.
3. Create an archived release (using Zenodo or similar) and report the DOI of that release back here. **Please note that the title and author list of this archive must EXACTLY match the paper.** (On Zenodo, you can edit the metadata after the release has been made if you're using an automated method.)

Thanks for your patience and let me know if you run into any issues!

**Comment by Jammy2211** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02550/joss.02550/10.21105.joss.02550.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02550/joss.02550/10.21105.joss.02550.pdf) :page_facing_up: :point_left:

**Comment by Jammy2211** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02550/joss.02550/10.21105.joss.02550.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02550/joss.02550/10.21105.joss.02550.pdf) :page_facing_up: :point_left:

**Comment by Jammy2211** [comment]
We will go with autofit v0.72.2.

I made a couple of changes to the manuscript, primarily typos and adding Binder links (and removing a couple of older links).

**Comment by Jammy2211** [comment]
The Zenodo will be sorted Wednesday, unfortunately only the repo owner can do that and my co developer isn't available until then!

**Comment by Jammy2211** [comment]
Here is the zenodo:

https://zenodo.org/record/4497861#.YBqqlOj7T-h

We've made sure the author list and title match, let me know if anything else looks like it needs editing.

**Comment by dfm** [comment]
@whedon set 10.5281/zenodo.4497861 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4497861" target="_blank">10.5281/zenodo.4497861</a> is the archive.

**Comment by dfm** [comment]
@whedon set v0.72.2 as version

**Comment by whedon** [comment]
OK. v0.72.2 is the version.

**Comment by dfm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2074

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2074, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.21105/joss.00024 is OK
- 10.21105/joss.00433 is OK
- 10.1093/mnras/staa278 is OK
- 10.1086/670067 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1093/mnras/sts633 is OK
- 10.1093/mnras/stv1455 is OK
- 10.1093/mnras/sty1264 is OK
- 10.1093/mnras/stz2220 is OK
- 10.7717/peerj-cs.55 is OK
- 10.18637/jss.v076.i01 is OK
- 10.1051/0004-6361/201322971 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK
- 10.21105/joss.02214 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@Jammy2211: This has now been handed off to the Editors-in-chief to handle the final processing. They might have some edits/recommendations before final acceptance, but we're just about there. Thanks for all of your work and patience!

@arm61, @karllark: Thank you both very much for your constructive reviews and contributions. I really appreciate it!!

**Comment by Jammy2211** [comment]
Awesome, thank you!

**Comment by kyleniemeyer** [comment]
Hi @Jammy2211, I am the EIC on duty this week doing some final checks before publishing.

I noticed that your paper does not have an explicit Statement of Need section, which is one of our [required paper elements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). This was caught by whedon at the very beginning of the submission process, but looks like it got missed more recently. (We are working on making this requirement more explicit in a few places, and ensuring the automated check happens at other steps in the process.)

Could you add this section? You can likely just repurpose some existing text in your paper. Thanks!

The only other editorial comments I have are minor: in the summary paragraph, could you add a comma after "e.g" in the parenthetical, and remove the redundant "etc."? There is another instance of an "e.g." missing its comma later in the Model Abstraction and Composition section. 

The paper looks great otherwise!

**Comment by Jammy2211** [comment]
Hi @kyleniemeyer,

I've added a statement of need, which invovled me rejigging a few sentenses and adding a couple :).

I've also sorted out the e.g. / etc issues.

Thanks!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02550/joss.02550/10.21105.joss.02550.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02550/joss.02550/10.21105.joss.02550.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1357755536255647744) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2076
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02550](https://doi.org/10.21105/joss.02550)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congratulations @Jammy2211 on your article's publication in JOSS!

Many thanks to @arm61 and @karllark for reviewing this, and @dfm for editing it.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02550/status.svg)](https://doi.org/10.21105/joss.02550)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02550">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02550/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02550/status.svg
   :target: https://doi.org/10.21105/joss.02550
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02550/status.svg)](https://doi.org/10.21105/joss.02550)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by JohannesBuchner** [comment]
Can the typo PyMulitNest->PyMultiNest still be fixed?

**Comment by kyleniemeyer** [comment]
@openjournals/dev The typo is in the Software Citation section of the paper, can that be fixed at this point?

**Comment by arfon** [comment]
Yep, we can regenerate the paper if the fix has been made.

**Comment by kyleniemeyer** [comment]
Hi @Jammy2211, could you fix the typo pointed out in the paper source?

**Comment by Jammy2211** [comment]
Pushed :)

**Comment by arfon** [comment]
OK, that should be fixed now.
