### ISSUE TITLE
[PRE REVIEW]: DARE Platform: a Developer-Friendly and Self-Optimising Workflows-as-a-Service Framework for e-Science on the Cloud

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2552]
**Submitting author:** @iaklampanos (<a href="http://orcid.org/0000-0003-0478-4300">Iraklis Klampanos</a>)
**Repository:** <a href="https://gitlab.com/project-dare/dare-platform" target ="_blank">https://gitlab.com/project-dare/dare-platform</a>
**Version:** 3.4
**Editor:** @danielskatz
**Reviewers:** @rafaelfsilva, @Himscipy
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @iaklampanos. **Currently, there isn't an JOSS editor assigned** to your paper.

@iaklampanos if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.20 s (1234.8 files/s, 68927.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                           106            210            491           2701
Markdown                        29            683              0           1913
JavaScript                       7            599            230           1705
CSS                              7            182            232           1450
HTML                            34            137            231            879
Dockerfile                      23            220             79            613
Bourne Shell                    28            105             98            459
TOML                             3             24              1            136
TeX                              1             13              0            130
JSON                             3              4              0            116
Python                           3             18              3             90
INI                              4             15              0             77
-------------------------------------------------------------------------------
SUM:                           248           2210           1365          10269
-------------------------------------------------------------------------------


Statistical information for the repository '2552' was gathered on 2020/08/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christian Page                   4           555            855           10.17
Christian Pagé                   4           300              0            2.16
Ian van der Neut                 3             9              6            0.11
Sissy                            2            29              0            0.21
sthemeli                        34          7398           4713           87.35

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ian van der Neut              8           88.9          0.7                0.00
Sissy                        12           41.4          0.0                8.33
sthemeli                   2625           35.5          5.6                8.95
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1177/1094342016649766 is OK
- 10.5281/zenodo.3361395 is OK
- 10.5281/zenodo.3697898 is OK

MISSING DOIs

- https://doi.org/10.1109/escience.2019.00079 may be missing for title: DARE: A Reflective Platform Designed to Enable Agile Data-Driven Research on the Cloud
- https://doi.org/10.1109/escience.2019.00042 may be missing for title: Comprehensible control for researchers and developers facing data challenges
- https://doi.org/10.1002/essoar.10500166.1 may be missing for title: Leveraging and Easing End Users’ Climate Data Access by Interfacing  Infrastructures
- https://doi.org/10.1109/escience.2019.00080 may be missing for title: Ease access to climate simulations for researchers: IS-ENES climate4impact
- https://doi.org/10.1109/escience.2019.00077 may be missing for title: Active provenance for Data-Intensive workflows: engaging users and developers
- https://doi.org/10.1109/escience.2019.00089 may be missing for title: Enabling Transparent Access to Heterogeneous Architectures for IS-ENES  Climate4Impact using the DARE Platform
- https://doi.org/10.1093/gigascience/giz095 may be missing for title: Sharing interoperable workflow provenance: A review of best practices and their  practical application in CWLProv

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02552/joss.02552/10.21105.joss.02552.pdf)

**Comment by danielskatz** [comment]
@iaklampanos - Can you explain what is the code that you are submitting?  I only see a very small amount of Python, and a bit more shell script, but I'm having difficulty understanding the structure of this repository.

In addition, we need an explicit statement of need section in the paper - see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

Finally, you might want to update the readme so that it says something about what the repository is for, how someone might use/test it, how someone could contribute to it, etc., not just what it contains.

**Comment by iaklampanos** [comment]
Dear Daniel,

Thanks for the quick response. 

This is the integrating repository for a number of open source components listed in the overall gitlab group (https://gitlab.com/project-dare <https://gitlab.com/project-dare>) and in the paper. The DARE platform has multiple facets but the emphasis here is on its WaaS functionality and the dynamic loading of execution contexts. In order to use this one would start at the dare-platform repository. We would be happy to mention this and provide links explicitly in the paper. 

Regarding the statement of need, I am not sure I understand what is needed. I would consider “Introduction” to be this? Perhaps I should change the section title?

Regarding readme.md, many of these questions are covered in the repository’s microsite https://project-dare.gitlab.io/dare-platform/ <https://project-dare.gitlab.io/dare-platform/> - we are currently linking relevant information in readme.md explicitly so that it’s more readily available.

Iraklis

**Comment by danielskatz** [comment]
Hi,

I'm still a bit confused, since https://gitlab.com/project-dare has absolutely no text or explanation, and is just a set of links to repositories. Maybe this is where https://project-dare.gitlab.io/dare-platform/ comes in?  But even in this, the closest I can find to a map for what software comprises Dare is https://project-dare.gitlab.io/dare-platform/features/ which mentions six components, and I am unsure how they relate to the more than six repositories in https://gitlab.com/project-dare

Regarding the README in https://gitlab.com/project-dare/dare-platform, I would expect to see things like:
- who might want to use the software
- how should someone contribute to the software
- how could someone install and test the software (this is mostly there, though the installation instructions are kind of like a recipe that doesn't say what you are making or start with ingredients, but just includes the steps to be performed.

I think the main concern I have here is that is seems like all of this is written for people who are already familiar with DARE, and someone (like me) who is not familiar with DARE very quickly gets lost.

For the JOSS review:

What software are you submitting for review? (please answer very specifically with the repository/ies that contains the software, and if needed, what parts of that repository/ies)

We do require a section in the paper called "Statement of Need" - this could be the introduction, or could follow it.  Again, please see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

We can leave the README discussion for the reviewers, but please take a look at https://joss.readthedocs.io/en/latest/review_checklist.html, which is the list of criteria reviewers will use.  I think the Documentation section in particular is going to lead to a number of discussions.

**Comment by iaklampanos** [comment]
Hello, thank you for your very helpful comments. We will try to address all of them and get back to you.

Iraklis

**Comment by danielskatz** [comment]
Thanks - I'll marked this as paused for now.  please mention @openjournals/jose-eics (rather than me) when you are ready to start again, as we rotate each week.

**Comment by iaklampanos** [comment]
Dear editors, @openjournals/jose-eics,

We have made the following updates: 

* The DARE group (https://gitlab.com/project-dare) now contains a short description pointing to the dare-platform repository as the integrating one and for more information
* ReadMe.md (https://gitlab.com/project-dare/dare-platform/-/blob/master/ReadMe.md) of the dare-platform repository has been significantly updated. It now includes info on 
	- who this is for
	- what it can do for its users
	- it clarifies this is a cloud-side solution
	- indicative use-cases from a technical perspective
	- pointers to more information 
	- ways for people to contribute and communicate with the DARE platform
	- updated the list of software components pointing to the corresponding repositories
* paper.md (https://gitlab.com/project-dare/dare-platform/-/blob/master/paper/paper.md)
	- now contains a "Statement of Need" section, instead of an Introduction
	- In the discussion of the approach we now refer to logical components and how they are being implemented in software - this is meant to work alongside the more dynamic ReadMe.md of the repository.

I am looking forward to receiving your feedback.

Many thanks in advance 
Iraklis

**Comment by iaklampanos** [comment]
Dear editors, @openjournals/jose-eics, @danielskatz 

I am writing this as a gentle reminder. I see this is still in pre-review and as @openjournals/jose-eics does not autocomplete I am wondering whether I've misspelt it. I would greatly appreciate your feedback. 

Many thanks in advance

**Comment by danielskatz** [comment]
Thanks - the correct address is @openjournals/joss-eics (JOSE is a different journal).  Sorry for my misleading typo.

Also FYI, we have a system of rotating AEiCs, and I am not on duty this week, nor was I last week.

This week's AEiC should be able to work on this.

**Comment by iaklampanos** [comment]
Thanks @danielskatz, I realise this, I included you as I wasn't sure who to contact.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02552/joss.02552/10.21105.joss.02552.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@trallard @csoneson @jedbrown @danielskatz could one of you handle this submission?

**Comment by danielskatz** [comment]
👋 @iaklampanos - do you have any progress to report?

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by iaklampanos** [comment]
Daniel, I apologise for the delay. 

After discussing with colleagues we believe It would make better sense for this submission to cover the complete platform.  To this end, I've rewritten parts of the paper to make clear what the software is, and I've added a couple of authors who have also contributed to the core software of the platform.

I am looking forward to receiving your feedback - many thanks

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02552/joss.02552/10.21105.joss.02552.pdf)

**Comment by danielskatz** [comment]
I'm suggesting some minor changes in https://gitlab.com/project-dare/dare-platform/-/merge_requests/5

Also, I don't know what "It delivers mappings to diverse computing infrastructures" means

**Comment by danielskatz** [comment]
overall, this looks much more clear.

**Comment by danielskatz** [comment]
Can you suggest any reviewers, either from the community (of course, who are not conflicted), or from [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).  

If so, please mention them here in this thread (without tagging them with an @).

**Comment by iaklampanos** [comment]
Thank you, I've merged your suggestions and changed "It delivers mappings to diverse computing infrastructures" to " It can translate higher-level workflows to diverse computing contexts, such as Apache Storm, MPI and plain shared-memory multi-core"

Re reviewers, I could suggest the following:

Katerina Doka, National Technical University of Athens, Greece - http://www.cslab.ece.ntua.gr/~doka/index.html

Álvaro López García, Advanced Computing and e-Science Group
Instituto de Física de Cantabria (IFCA) - CSIC - University of Cantabria, Spain - https://alvarolopez.github.io, https://ifca.unican.es/en-us/member?exp=48

Rafael Ferreira da Silva, University of Southern California, CA, USA -  https://rafaelsilva.com 

From the list of JOSS reviewers, possibly:
julianpistorius,
satybald, 
colbrydi,
Himscipy

**Comment by danielskatz** [comment]
👋  @rafaelfsilva - would you be willing to review this submission (short paper and software) for JOSS?  (See https://joss.readthedocs.io/en/latest/reviewer_guidelines.html for more on what this means)

**Comment by danielskatz** [comment]
👋 @julianpistorius & @satybald - would either of you be wiling to review this submission for JOSS?

**Comment by rafaelfsilva** [comment]
@danielskatz I will be happy to do this review. I will try to finalize it in the upcoming 2 weeks (most probably sooner).

**Comment by danielskatz** [comment]
Thanks @rafaelfsilva - I will assign you, but we will not start the review (in a new issue) once we get another reviewer as well.

**Comment by danielskatz** [comment]
@whedon assign @rafaelfsilva as reviewer

**Comment by whedon** [comment]
OK, @rafaelfsilva is now a reviewer

**Comment by danielskatz** [comment]
👋 @colbrydi & @Himscipy - would either of you be wiling to review this submission for JOSS?

**Comment by colbrydi** [comment]
> 👋 @colbrydi & @Himscipy - would either of you be wiling to review this submission for JOSS?

@danielskatz, thank you for asking.  Unfortunately I am currently overwhelmed with my coursework.  Please feel free to ask again in a couple of weeks but right now I need to pass.

**Comment by danielskatz** [comment]
👋 @julianpistorius & @satybald & @Himscipy - One more try to see if one of you would be wiling to review this submission for JOSS

**Comment by danielskatz** [comment]
👋 @alvarolopez - Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by Himscipy** [comment]
Hi @danielskatz,

I will be willing to review the submission, you can add me as a reviewer for the submission.

Thank you.

Himanshu

**Comment by danielskatz** [comment]
Thanks @Himscipy - I'll add you and we'll get started.

**Comment by danielskatz** [comment]
@whedon add @Himscipy as reviewer

**Comment by whedon** [comment]
OK, @Himscipy is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2664.
