### ISSUE TITLE
[PRE REVIEW]: LMAPper – Where Scanning Probe Microscopy and Molecular Visualisation Meet

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2553]
**Submitting author:** @perdigao1 (<a href="http://orcid.org/0000-0002-0534-1512">Luis Miguel Alves Perdigao</a>)
**Repository:** <a href="https://git.code.sf.net/p/spm-and-mol-viewer/git" target ="_blank"> https://git.code.sf.net/p/spm-and-mol-viewer/git</a>
**Version:** v52e
**Editor:** @usethedata
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @perdigao1. **Currently, there isn't an JOSS editor assigned** to your paper.

@perdigao1 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2553 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2553 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@perdigao1 - Where is the git repository containing the software and the paper?
You submitted https://lmaperdigao@git.code.sf.net/p/spm-and-mol-viewer/git but this just seems to be empty to me.  Is this perhaps a private repository?  I guess this is on sourceforge, which I don't think I've used in a long time, so I'm a little confused about how to find the source code in this case.

**Comment by perdigao1** [comment]
Hi Dr Katz,
Sorry for this confusion.
The software is being hosted in a sourceforce website. The versioning system is subversion.https://sourceforge.net/projects/spm-and-mol-viewer/
There is a way to download the whole code there.

The website also supports git, but I only put the article there. The link you probably received will not work in a browser, but if you do git clone, it should workhttps://sourceforge.net/p/spm-and-mol-viewer/git/ci/master/tree/

I also find this a bit strange, but I hope it is ok.
Thank you for checking the article
RegardsLuis Perdigao
    On Thursday, 6 August 2020, 14:14:50 BST, Daniel S. Katz <notifications@github.com> wrote:  
 
 


@perdigao1 - Where is the git repository containing the software and the paper?
You submitted https://lmaperdigao@git.code.sf.net/p/spm-and-mol-viewer/git but this just seems to be empty to me. Is this perhaps a private repository? I guess this is on sourceforge, which I don't think I've used in a long time, so I'm a little confused about how to find the source code in this case.

**Comment by danielskatz** [comment]
See https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements

> - Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository. Placing these items together with your software (rather than in a separate repository) is strongly encouraged.
> 
> In addition, the software associated with your submission must:
> 
> - Be stored in a repository that can be cloned without registration.
> - Be stored in a repository that is browsable online without registration.
> - Have an issue tracker that is readable without registration.
> - Permit individuals to create issues/file tickets against your repository.

I'm going to try putting https://sourceforge.net/p/spm-and-mol-viewer/git/ as the repository and see if whedon will be able to use this to build the paper.

When I look at https://sourceforge.net/projects/spm-and-mol-viewer/, I don't see any source code.  How will reviewers find and view the source code?

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2553 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2553 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @arfon - can you help here?

**Comment by arfon** [comment]
@whedon check repository

**Comment by arfon** [comment]
@perdigao1 - I don't think our bot (Whedon) can handle Git repository addresses with spaces in them e.g. `https://git.code.sf.net/p/spm-and-mol-viewer/git spm-and-mol-viewer-git`.

Is this something you are able to configure?

**Comment by perdigao1** [comment]
Hi,
Thank you for checking this.
The address you should to compile the paper use is the one that I provided when I submitted the paper (without the thing after the space). I tried it and it compiled
 https://git.code.sf.net/p/spm-and-mol-viewer/git

I hope this helps
RegardsLuis
   
 On Thursday, 6 August 2020, 17:10:20 BST, Arfon Smith <notifications@github.com> wrote:  
 
 


@perdigao1 - I don't think our bot (Whedon) can handle Git repository addresses with spaces in them e.g. https://git.code.sf.net/p/spm-and-mol-viewer/git spm-and-mol-viewer-git.

Is this something you are able to configure?

**Comment by perdigao1** [comment]
Hi Dr. Katz,
To check the code, just click the tab that says 'Code'.https://sourceforge.net/p/spm-and-mol-viewer/code/HEAD/tree/

I hope this helps
RegardsLuis

    On Thursday, 6 August 2020, 16:59:53 BST, Daniel S. Katz <notifications@github.com> wrote:  
 
 


See https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements

   
   - Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository. Placing these items together with your software (rather than in a separate repository) is strongly encouraged.

In addition, the software associated with your submission must:
   
   - Be stored in a repository that can be cloned without registration.
   - Be stored in a repository that is browsable online without registration.
   - Have an issue tracker that is readable without registration.
   - Permit individuals to create issues/file tickets against your repository.


I'm going to try putting https://sourceforge.net/p/spm-and-mol-viewer/git/ as the repository and see if whedon will be able to use this to build the paper.

When I look at LMAPper - The SPM and Mol Viewer, I don't see any source code. How will reviewers find and view the source code?


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
LMAPper - The SPM and Mol Viewer

Download LMAPper - The SPM and Mol Viewer for free. Where SPM images and molecular models meet. This application...
 |

 |

 |

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02553/joss.02553/10.21105.joss.02553.pdf)

**Comment by danielskatz** [comment]
Ok, the paper now builds!

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1126/science.1176210 is OK
- 10.1038/s41467-020-15898-2 is OK
- 10.1088/1367-2630/10/5/053012 is OK
- 10.1063/1.4793200 is OK
- 10.1021/jp060062x is OK
- 10.1039/C9CC08361H is OK
- 10.1039/C9SE01261C is OK
- 10.1021/jacs.9b09367 is OK
- 10.1186/1758-2946-4-17 is OK
- 10.1039/D0CE00213E is OK
- 10.2478/s11534-011-0096-2 is OK
- 10.1063/1.2432410 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by perdigao1** [comment]
Hi Dr. Katz,
Yes, the code is in Visual Basic. Probably not popular for open source, but works well.
RegardsLuis Perdigao
    On Thursday, 6 August 2020, 17:51:21 BST, Daniel S. Katz <notifications@github.com> wrote:  
 
 


I now agree that the code is available from the Code tab on https://sourceforge.net/p/spm-and-mol-viewer/code/HEAD/tree/

It looks like the code is in visual basic?

**Comment by danielskatz** [comment]
Ok - A last comment before we move forward is that the paper is probably too long.

As described in https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain:
> The paper should be between 250-1000 words.

> JOSS papers are only expected to contain a limited set of metadata (see example below), a Statement of Need, Summary, Acknowledgements, and References sections. You can look at an example accepted paper. Given this format, a “full length” paper is not permitted, and software documentation such as API (Application Programming Interface) functionality should not be in the paper and instead should be outlined in the software documentation.

**Comment by danielskatz** [comment]
👋 @usethedata - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @usethedata as editor

**Comment by whedon** [comment]
@usethedata has been invited to edit this submission.

**Comment by usethedata** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
@perdigao1 -- Do you have any suggestions for reviewers.  I've looked through the list of people who've volunteered to review for JOSS, and I can only find one with VB experience, and the domain is way out of field for them.  I'm asking around through my colleagues who do microscopy, but not getting much.  Almost all of the people I know who do work in this domain are Mac users.

**Comment by perdigao1** [comment]
Dear Dr. Wilson,
Thank you for your interest in the article I submitted. Sorry that you are having difficulty finding a suitable person to review my article.
I can perhaps provide some suggested names of people who can have a look at the software, in the field of molecular visualisation or scanning probe microscopy, but I am pretty sure they have not volunteered to review for JOSS, and I don't know if they use Windows, Mac or Linux.
Should I provide you their names and email addresses?
Thank you
RegardsLuis Perdigao
    On Tuesday, 11 August 2020, 22:18:56 BST, Bruce Wilson <notifications@github.com> wrote:  
 
 


@perdigao1 -- Do you have any suggestions for reviewers. I've looked through the list of people who've volunteered to review for JOSS, and I can only find one with VB experience, and the domain is way out of field for them. I'm asking around through my colleagues who do microscopy, but not getting much. Almost all of the people I know who do work in this domain are Mac users.

**Comment by usethedata** [comment]
@perdigao1 -- That would be helpful, particularly if you know anyone else working in VB.  I, and a few others, have used it in the distant (15+ years) past.  Easiest way to do that and protect privacy is if you send the info to my work email address -- wilsonbe@ornl.gov

**Comment by usethedata** [comment]
Suggestions received from author.  Inquiries sent.

**Comment by labarba** [comment]
👋 hi everybody!

It looks like @usethedata needs to find reviewers here still —times are tough, so we need to be patient, but I think this needs a circle back!

**Comment by usethedata** [comment]
My apologies to all.  I got slammed with end of fiscal year stuff and a significant reorganization at work.  I've attempted finding reviewers, but I have been completely unsuccessful.  To date, I've contacted well over a dozen potential reviewers, including the people @perdigao1 suggested and contacting people I know in the microscopy community across the DOE labs.  I have been completely unable to find anyone with a combination of recent (last decade) experience in Visual Basic and the science domain.  I discussed this with one of the Editors-in-chief, and I need to kick this back to @perdigao1 for suggestions of reviewers.

**Comment by perdigao1** [comment]
Hi Bruce,
Thank you for looking for referees. I suspect that the referees I suggested have either refused or did not respond to requests to review the article. Is this correct?
Perhaps one of the main problem with the article is that the code was written in Visual Basic. Although visual studio is nowadays free and powerful, I take that it is not a widely used language within the open source community.
I am not really sure what to do it here. I have been writing an alternative version of the same software in javascript, which runs in a browser. However it has significantly less functionality. Also I am not sure whether this version would be more 'submitable' for publication ?
I am aware that python language is more favoured in this journal however I am not a fan of it as I have tested it in the past and it lead me to conclude that it was not suitable for my applications.
I don't know who else could referee this article and software. The number of potential users is currently very narrow.
As such I am not really sure what to do regarding my submission. I will look for more potential reviewers.
Thank you
RegardsLuis Perdigao

    On Friday, 2 October 2020, 19:16:29 BST, Bruce Wilson <notifications@github.com> wrote:  
 
 


My apologies to all. I got slammed with end of fiscal year stuff and a significant reorganization at work. I've attempted finding reviewers, but I have been completely unsuccessful. To date, I've contacted well over a dozen potential reviewers, including the people @perdigao1 suggested and contacting people I know in the microscopy community across the DOE labs. I have been completely unable to find anyone with a combination of recent (last decade) experience in Visual Basic and the science domain. I discussed this with one of the Editors-in-chief, and I need to kick this back to @perdigao1 for suggestions of reviewers.

**Comment by usethedata** [comment]
You are correct that the issue is the software being in Visual Basic.  JOSS itself does not have any particular language preference.  However, the communities to which we are connected do seem to have some preferences.  I can say that there is a significant cadre of people working with JavaScript, so finding people with microscopy/imaging and JavaScript expertise is a much more tractable task.  As for submittable, there aren't hard and fast rules around how big things should be, but consider a typical journal article and ask yourself whether the amount of work involved and scope of the code is at the same order of magnitude as the effort involved in other types of scientific journal articles.  If so, then it's potentially publishable, even if it's not as feature-rich as what you've done.  

Yes, the referees you suggested either declined or did not respond (mostly the latter).  For those where I didn't get a response, I tried at least twice, and then looked through Internet searching to see if I could find alternate contact emails and tried those.

**Comment by usethedata** [comment]
Pausing pre-review until reviewers can be identified, which is waiting for further recommendations from the authors.

**Comment by arfon** [comment]
I've just posted on the [JOSS Twitter](https://twitter.com/JOSS_TheOJ/status/1348918665945747457) to see if we can find any potential reviewers suitable for this submission. 

@perdigao1 - as you will be aware, we've found it very challenging to find suitable reviewers for this submission. If we aren't able to find good candidates based on this latest attempt I think we will need to declare failure here sorry 😞 .

**Comment by jbytecode** [comment]
Hi folks,

just writing here for helping. 

@arfon this is not Visual Basic, but it is VB.NET, a new twit may increase the attentions.

I have just installed `svn` after many years,  I cloned the project, I tried the import the project in Microsoft Visual Studio 2019 for Mac (After nearly 15 years, it was fantastic to see VB code). This kind of project structure is not supported in Mono version. Well, VB.NET is no longer supported like VB by Microsoft. 

I suggest the authors to convert the project to `C#` and make it compilable using the new `dotnetsdk` which is available for Linux, Windows and Mac.

**Comment by arfon** [comment]
:wave: @perdigao1 - I'm afraid we're not going to be able to review this submission in JOSS due to the complete lack of available reviewers.

If you're still working on this submission and are looking to grow the user base and potentially find new contributors, I would encourage you to move to a more modern, supported programming language.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
