### ISSUE TITLE
[REVIEW]: Bacting: a next generation, command line version of Bioclipse

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2558]
**Submitting author:** @egonw (<a href="http://orcid.org/0000-0001-7542-0286">Egon Willighagen</a>)
**Repository:** <a href="https://github.com/egonw/bacting" target ="_blank">https://github.com/egonw/bacting</a>
**Version:** paper-v3
**Editor:** @majensen
**Reviewer:** @Zethson, @arcuri82
**Archive:** <a href="https://doi.org/10.5281/zenodo.4942022" target="_blank">10.5281/zenodo.4942022</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c306d8f50a6390d21b43633c99cbe4c3/status.svg)](https://joss.theoj.org/papers/c306d8f50a6390d21b43633c99cbe4c3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c306d8f50a6390d21b43633c99cbe4c3"><img src="https://joss.theoj.org/papers/c306d8f50a6390d21b43633c99cbe4c3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c306d8f50a6390d21b43633c99cbe4c3/status.svg)](https://joss.theoj.org/papers/c306d8f50a6390d21b43633c99cbe4c3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/egonw/bacting" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@Zethson & @arcuri82, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @majensen know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/egonw/bacting">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@egonw) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/egonw/bacting">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@egonw) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Zethson, @arcuri82 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2558 with the following error: 

 Can't find any papers to compile :-(

**Comment by majensen** [comment]
@whedon generate pdf from branch devel/0.0.13

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch devel/0.0.13. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02558/joss.02558/10.21105.joss.02558.pdf)

**Comment by Zethson** [comment]
Hi,

this is the first time that I am reviewing for JOSS, so feel free to tell me if I am doing something wrong.

1. I identified an issue with the installation instructions: https://github.com/egonw/bacting/issues/8 , which were promptly solved.
2. A question regarding the license: https://github.com/egonw/bacting/issues/9
3. Several issues regarding the community guidelines and documentation: https://github.com/egonw/bacting/issues/10

Additional questions that I have:
1. What do you, @egonw mean with missing progress monitoring? Missing progress bars for called functions?
2. How does Bioeclipse/Bacting compare to BioJava and BioPython?

The paper is well written and I am looking forward to your answers!
Great work.

Thank you!
Cheers

**Comment by majensen** [comment]
Looks good to me @Zethson - onward!

**Comment by egonw** [comment]
Regarding the license question, I also replied in the issue tracker, but here copy it here for convenience: There is a lot of code being reused, a good bit of which has not been written by me, but other Bioclipse developers. I cannot change the license. But I like the suggestion and will look into the (dis)advantages and discuss those with all original authors.

**Comment by majensen** [comment]
Hi @arcuri82 - just checking in. Have you had a chance to start looking at this work? 
Thanks.

**Comment by arcuri82** [comment]
Hi @majensen - unfortunately haven't had time to start yet :(  but hopefully should be able to start next week

**Comment by egonw** [comment]
@arcuri82, that sounds fine. I have not been able to work on the package this week anyway.

**Comment by arcuri82** [comment]
I made a first set of comments.
However, there is one thing I would like to get clarified. The program is written Java, but, its intended usage seems for Groovy. I do not know Groovy. And unfortunately I do not have the time to learn a new programming language just for doing a review. If all examples are going to be only in Groovy, I am not sure I can really try out this software, and give a proper review. But, asking examples/tutorials in Java for a program that is meant to be used mainly in Groovy would likely be unfair to the author.

**Comment by majensen** [comment]
@egonw can you comment regarding @arcuri82 's concern?

**Comment by egonw** [comment]
Yes, I can and will. Right now, I'm swamped in university year start and project mid terms reviews. I have some ideas, some take a bit more time to work out. Other things I have to try and see how they work out. I have created a project on GitHub to work out ideas the reviewers gave, towards the rebuttal/revision: https://github.com/egonw/bacting/projects/1?add_cards_query=is%3Aopen

I will report back here when making progress. @arcuri82 wrote "first set of comments" and I will also monitor things here if more feedback comes one.

**Comment by kthyng** [comment]
@egonw Totally understand the trouble with the start of the academic year! As the rotating associate editor in chief this week, I am going to pause this submission while we wait for your responses to start. This is for bookkeeping purposes and can be removed whenever you are ready to move forward. Thanks!

**Comment by majensen** [comment]
@egonw - how are things? Just checking in.

**Comment by majensen** [comment]
@egonw - checking in. How are things going?

**Comment by egonw** [comment]
> 2. A question regarding the license: [egonw/bacting#9](https://github.com/egonw/bacting/issues/9)

This one is still open. There are several past Bioclipse developers involved, one of them even passed away. I will not be able to resolve this quickly.

> 3. Several issues regarding the community guidelines and documentation: [egonw/bacting#10](https://github.com/egonw/bacting/issues/10)

@Zethson, I have isolated some subtasks of https://github.com/egonw/bacting/issues/10 which now have a reply (fixes mostly; see that issue). Thank you for your suggestions. 
 
> Additional questions that I have:
> 
> 1. What do you, @egonw mean with missing progress monitoring? Missing progress bars for called functions?

Indeed. Eclipse (and therefore Bioclipse) has a progress monitoring `View` (a GUI element) that allows you to see which processes are running in the background. For long running tasks, it would tell the user what they are waiting for. But since Bacting does not have a GUI, I have not ported this functionality yet. I have been thinking about this, but it depends a lot on how it is used. I cannot exclude I will include the progress monitoring in the future, but at this moment this does not have priority.

I'll update the manuscript to be more clear about this.

> 2. How does Bioeclipse/Bacting compare to BioJava and BioPython?

BioJava is a library that actually has been integrated into (the original) Bioclipse. This week I [started](https://github.com/egonw/bacting/issues/39) [porting](https://bioclipse.github.io/bioclipse.scripting/bio.html#the-biojava-manager) the functionality. Bioclipse exposes the functionality and makes it interoperable with other libraries by introducing implementation-neutral 'domain objects'.

**Comment by egonw** [comment]
> @egonw - checking in. How are things going?

@majensen, yes, sorry about this. i had to wait until the winter break to start working on the rebuttal. I think I indicated somewhere that I expect to "resubmit" (how does that work?) the manuscript before this Monday. I am tracking progress here: https://github.com/egonw/bacting/projects/1

**Comment by majensen** [comment]
@egonw Sounds good. Just start back up and I will remove the paused label. We can pick up where we left off.

**Comment by majensen** [comment]
@egonw - just checking in with you on your progress/timeline - thanks

**Comment by majensen** [comment]
@egonw - checking in - thanks

**Comment by egonw** [comment]
Sorry, I'm very close. Most is addressed, but need to check and write a rebuttal. But last three weeks were darn busy again :(

**Comment by egonw** [comment]
One of the last hurdles I wanted to take before the resubmission is using it in Python. There is also @arcuri82's question about Java. Since the manager is written in Java, you can simply use them directly in Java too. The dependencies which are resolved in Groovy with `@Grab` and in Python with `scyjava.config` (see the updated 0.17 README) can be defined in (for example) Maven. And creating a manager, like in the `cdk.fromSMILES("COC")` is done with the equivalent of:

```java
import net.bioclipse.managers.CDKManager;
CDKManager cdk = new CDKManager(".");
```

Of course, it needs the `main()` wrapping, which is why I prefer Groovy, that does not.

**Rebuttal**

First, thanks to the reviewers for their detailed review. It is my first JOSS submission and I really appreciate the thoroughness, beating the peer review we once established for the Chemistry Development Kit.

Since the issues got scattered over various comments in this issue and in the Bacting GitHub issue, I actually went through them and extracted several items for which I created issues: https://github.com/egonw/bacting/projects/1 You can find the detailed rebuttal there.

Roughly, code coverage added (70%), more detailed guidance on GitHub (like contributing.md), replied the questions about unclear things, or why something was done, added missing JavaDoc, and added a tracker for the porting of the Bioclipse API (see https://github.com/egonw/bacting/projects/2).

As said, I haven't been able to reproduce the compile issue, but solved the JavaDoc error in the report. That leaves two open questions, I believe:

1. the EPL version. contacting all authors of the original code is going to take some time. I suggest to decouple this from the paper.
2. the progress monitoring. This has not been ported from Bioclipse to Bacting at this moment. Eclipse has a nice progress user interface, but reproducing this on the command line is non-trivial. Maybe it will return at some point, but I do not foresee this in the near future.

@majensen, please consider this my point to continue the review process. I am sorry it took so long. I clearly underestimated to level of detail the reviewers would give to the work and generally fully agree with their comments. It greatly improved the project.

**Comment by egonw** [comment]
Hi @arcuri82, @Zethson, please let me know if I can answer any further questions. Your feedback has been really appreciated.

**Comment by arcuri82** [comment]
@egonw  Hi. I am currently on parental leave. unfortunately I have no time this week to look at your updates. but i ll try the week after

**Comment by Zethson** [comment]
@egonw It's great to see that you continued the work on this project.
I have no further requests or questions.

Thank you!

**Comment by arcuri82** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02558/joss.02558/10.21105.joss.02558.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02558/joss.02558/10.21105.joss.02558.pdf) :page_facing_up: :point_left:

**Comment by arcuri82** [comment]
@majensen I am fine by the changes made by @egonw . i do not have any further comment
@egonw  good work ;)

**Comment by egonw** [comment]
@majensen, I got an editorial question: for another journal we're piloting using CiTO annotations in reference lists, see https://www.biomedcentral.com/collections/cito If I can get this to work with the current template and JOSS compiler out of the box, would JOSS be okay with me adding some of them?

**Comment by majensen** [comment]
@egonw I will tag @arfon regarding the [above](https://github.com/openjournals/joss-reviews/issues/2558#issuecomment-852336355) proposal anyhow.

**Comment by majensen** [comment]
Just want to apologize for my tardiness on this - I will take a final look at the paper with an eye to proofreading; might have a suggestion or two via a PR. Really will try to get this accomplished this weekend
@egonw

**Comment by egonw** [comment]
Well, compared to how quickly I was able to reply to the reviewers, I will refrain from commenting on the "tardiness" :)

**Comment by majensen** [comment]
@whedon generate pdf from branch devel/cito

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch devel/cito. Reticulating splines etc...
```

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by majensen** [comment]
@egonw  - I have made some very minor suggestions to smooth out the English:
[10.21105.joss.02558-maj.pdf](https://github.com/openjournals/joss-reviews/files/6645339/10.21105.joss.02558-maj.pdf). While I'm not in the chem business, I can certainly appreciate the new life Bacting appears to be breathing into a useful and venerable toolkit.

Once you have made these changes, can you provide me with a Zenodo archive DOI of the repo here. This may need to be an ad hoc archive, as JOSS prefers the archive to have the precise title and author list as the paper it refers to. Thank you!

**Comment by egonw** [comment]
@majensen, I'm on it

**Comment by egonw** [comment]
@majensen, just to make sure... a new Zenodo archive, just for the paper, right? You do not mean to update the paper for the most recent Bacting release, right?

**Comment by egonw** [comment]
The Bacting version described in the article is 0.15, with DOI: https://doi.org/10.5281/zenodo.4400601

The DOI for the updated Bacting paper: to follow asap, awaiting PDF generation by Whedon...

**Comment by egonw** [comment]
ping @majensen, like this?

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02558/joss.02558/10.21105.joss.02558.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02558/joss.02558/10.21105.joss.02558.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02558/joss.02558/10.21105.joss.02558.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02558/joss.02558/10.21105.joss.02558.pdf) :page_facing_up: :point_left:

**Comment by majensen** [comment]
@egonw - for the archive, can you rename your latest to the paper title, viz. "Bacting: a next generation, command line version of Bioclipse" ? Then I can use that with the version "paper-V3", or you might call it 0.18.1, or what have you.

**Comment by egonw** [comment]
@majensen, I am confused. That's exactly what the title is in paper-v2 and the latest proof posted here by whedon...

**Comment by majensen** [comment]
Sorry, I'm not being clear @egonw  - so, JOSS likes the title _of the archive_ to match the title _of the paper_. Right now, the title of the archive at https://doi.org/10.5281/zenodo.4942022 is "egon/bacting: JOSS paper v3". 
So, in the Zenodo UI, where it says "title" in the Basic Information form (see screenshot below), one would put "Bacting: a next generation...".
Does this make sense?
<img width="699" alt="image" src="https://user-images.githubusercontent.com/82073/122844770-5ec60b80-d2d0-11eb-9903-2ba79e45d02c.png">

**Comment by egonw** [comment]
Done: https://zenodo.org/record/4942022

**Comment by majensen** [comment]
@whedon set archive as 10.5281/zenodo.4942022

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by majensen** [comment]
@whedon accept either order around the frigging conjunction

**Comment by whedon** [comment]
To recommend a paper to be accepted use `@whedon recommend-accept`

**Comment by majensen** [comment]
@whedon set 10.5281/zenodo.4942022 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4942022" target="_blank">10.5281/zenodo.4942022</a> is the archive.

**Comment by majensen** [comment]
@whedon set paper-v3 as version

**Comment by whedon** [comment]
OK. paper-v3 is the version.

**Comment by majensen** [comment]
@whedon recommend accept

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by majensen** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by majensen** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btn397 is OK
- 10.5281/zenodo.3950863 is OK
- 10.1186/1471-2105-8-59 is OK
- 10.1186/1471-2105-10-397 is OK
- 10.1186/s13321-017-0220-4 is OK
- 10.1021/ci100384d is OK
- 10.1186/1471-2105-11-5 is OK
- 10.1186/1758-2946-5-14 is OK
- 10.12688/f1000research.12342.1 is OK
- 10.1093/nar/gkx1064 is OK
- 10.6084/m9.figshare.6356027.v1 is OK
- 10.1007/978-3-319-70407-4_36 is OK
- 10.5281/ZENODO.3364510 is OK
- 10.5281/ZENODO.3855084 is OK
- 10.1016/j.csbj.2020.02.023 is OK
- 10.6084/M9.FIGSHARE.12458612 is OK
- 10.1186/s13326-015-0005-5 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2404

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2404, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hi @egonw, I'm doing some final checks before publishing. The Brenninkmeijer, Mayfield, Rijswijk, Slenter, Spjuth 2009, and Willighagen 2017 references look a bit strange - I think "et al." is included in the bibtex entry somehow. Can you correct those? All authors should be included in the bibtex entries, and then our LaTeX parser can handle truncating the list of authors automatically.

**Comment by egonw** [comment]
@kyleniemeyer, thank you for catching that. I had not expected Zotero to put et al. in their BibTeX output :( There was a second entry to which this applied and fixed that one too.

When looking at the final proof last night I noticed one sentence that changed in reply to a reviewer comment, but where something seems to have gone wrong. I am changing `This means that translation of IFile to String translations in the API do not exist in Bioclipse` to `This means that the IFile to String translations in the API do not exist in Bioclipse.`, see https://github.com/egonw/bacting/commit/ff7414cd3990639019e3a80d3e36feb0b95791bf

- [ ] make new proof and check changes
- [ ] make a new tag `paper-v4` for the article in the repo (for the `whedon set paper-v4 as version`)
- [ ] wait for the Zenodo deposit and look up the new DOI on Zenodo (for the `whedon set 10.5281/zenodo.494xxxx as archive)

**Comment by kyleniemeyer** [comment]
@egonw ah sorry for the confusion - I actually meant all *six* references that began with those first authors... 

You do not actually need to update the Zenodo deposit for paper-only changes—you can, if you want, but our focus is on archiving the version of the software that was reviewed, since JOSS archives the paper itself.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02558/joss.02558/10.21105.joss.02558.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02558/joss.02558/10.21105.joss.02558.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Actually it looks like all of the references with long author lists have this issue.

**Comment by egonw** [comment]
Yeah, indeed. I'm sorry about this. Hang on :)

**Comment by egonw** [comment]
Okay, took a bit of effort, but I exported all references in a different way from Zotero now (next time I'm just going to use `citation.js`)... I think it should be better now, but also note the following, which comes from the PDF generation process, I think:

![image](https://user-images.githubusercontent.com/26721/123047070-21ab6780-d3fd-11eb-8444-79dd08b07ccc.png)

**Comment by egonw** [comment]
> You do not actually need to update the Zenodo deposit for paper-only changes—you can, if you want, but our focus is on archiving the version of the software that was reviewed, since JOSS archives the paper itself.

Okay, that seems to me to contradict earlier instructions, but will do without now then. @kyleniemeyer, please do check the references one more time too.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02558/joss.02558/10.21105.joss.02558.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02558/joss.02558/10.21105.joss.02558.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@egonw Thanks for your work on that, it now looks good to me. Our paper template does truncate some very long author lists, but includes the final author.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
To recommend a paper to be accepted use `@whedon recommend-accept`

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1407732292903186437) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2408
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02558](https://doi.org/10.21105/joss.02558)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congratulations @egonw on your article's publication in JOSS!

Many thanks to  @Zethson and @arcuri82 for reviewing, and @majensen for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02558/status.svg)](https://doi.org/10.21105/joss.02558)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02558">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02558/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02558/status.svg
   :target: https://doi.org/10.21105/joss.02558
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02558/status.svg)](https://doi.org/10.21105/joss.02558)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by egonw** [comment]
> Congratulations @egonw on your article's publication in JOSS!
> 
> Many thanks to @Zethson and @arcuri82 for reviewing, and @majensen for editing.

Thanks everyone for landing this work!

**Comment by majensen** [comment]
@egonw - great work; @arcuri82 @Zethson really appreciate your help with this submission. We made it under the 1 year mark! Congrats all!
