### ISSUE TITLE
[PRE REVIEW]: zalpha: an R package for the identification of regions of the genome under selection

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2560]
**Submitting author:** @chorscroft (<a href="http://orcid.org/0000-0001-5679-5912">Clare Horscroft</a>)
**Repository:** <a href="https://github.com/chorscroft/zalpha" target ="_blank">https://github.com/chorscroft/zalpha</a>
**Version:** v0.2.0
**Editor:** @lpantano
**Reviewers:** @juanvillada 
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @chorscroft. **Currently, there isn't an JOSS editor assigned** to your paper.

@chorscroft if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2560 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2560 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02560/joss.02560/10.21105.joss.02560.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1534/genetics.115.185900 is OK
- 10.1038/ng1001-217 is OK
- 10.1534/genetics.103.025387 is OK
- 10.1146/annurev-genet-111212-133526 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (501.3 files/s, 86316.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               39           1364           1527           4463
Markdown                         5             60              0            158
TeX                              1              0              0             55
Rmd                              1            106            143             44
-------------------------------------------------------------------------------
SUM:                            46           1530           1670           4720
-------------------------------------------------------------------------------


Statistical information for the repository '2560' was gathered on 2020/08/09.
No commited files with the specified extensions were found.
```

**Comment by danielskatz** [comment]
👋 @lpantano - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @lpantano as editor

**Comment by whedon** [comment]
@lpantano has been invited to edit this submission.

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@lshep, @Kayla-Morrell, are you interested in reviewing this software? Some information if you are new to JOSS system: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks!

**Comment by lpantano** [comment]
@bernatgel, @naumenko-sa, would you be interested in reviewing this tool?

**Comment by bernatgel** [comment]
> @bernatgel, @naumenko-sa, would you be interested in reviewing this tool?

Hi @lpantano, I'm afraid I'll have to decline this. I don't have the expertise to evaluate this software. Thanks for the invitation.

**Comment by lshep** [comment]
Sorry I never responded.  I'm honestly overloaded with work and don't think I have the time to give it a fair review.

**Comment by lpantano** [comment]
@chorscroft, I am still trying to find reviewers, if you know of any, let me know. Thanks!

**Comment by lpantano** [comment]
Hey @acolum, @jean997,  would you like to review this tool?

**Comment by acolum** [comment]
Unfortunately, I'm not available to review this tool.

**Comment by jean997** [comment]
I'm sorry I'm not available either (plus selection isn't really my area of expertise). Looking at the list maybe shaunpwilkinson, giraola, juanvillada, stulacy, r-barnes, vbaliga, CFGrote,  or dwinter could be worth a try

**Comment by lpantano** [comment]
Hey @juanvillada, @vbaliga, would you like to review this tool?

**Comment by vbaliga** [comment]
I'm sorry to say the content goes beyond my area of expertise, so it's probably best that not I be a reviewer. Thanks for the offer, though

**Comment by juanvillada** [comment]
Hey @lpantano 

Yes, I would like to review this tool. Count me in 👍🏼

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by lpantano** [comment]
@whedon assign @juanvillada  as reviewer

**Comment by whedon** [comment]
OK, @juanvillada  is now a reviewer

**Comment by lpantano** [comment]
@dcgerard, would you like to review this tool? link to the guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by lpantano** [comment]
I will start this review, and continue to look for the second reviewer. This way @juanvillada can start working on this :)

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2638.

**Comment by lpantano** [comment]
Hey @alachins, @FerRacimo would you like to review this tool? link to the guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html
