### ISSUE TITLE
[PRE REVIEW]: Damona: a Singularity environment manager for reproducible analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2561]
**Submitting author:** @cokelaer (<a href="http://orcid.org/0000-0001-6286-1138">Thomas Cokelaer</a>)
**Repository:** <a href="https://github.com/cokelaer/damona" target ="_blank">https://github.com/cokelaer/damona</a>
**Version:** 0.4.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @cokelaer. **Currently, there isn't an JOSS editor assigned** to your paper.

@cokelaer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (441.6 files/s, 27909.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            240            336            673
reStructuredText                 7            205             32            363
Markdown                         1             59              0            191
make                             8             32              7            131
YAML                            13             15              7            118
TeX                              1             13              0            102
Bourne Shell                     1              0              0              4
-------------------------------------------------------------------------------
SUM:                            40            564            382           1582
-------------------------------------------------------------------------------


Statistical information for the repository '2561' was gathered on 2020/08/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Thomas Cokelaer                 31          1465            216          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Thomas Cokelaer            1249           85.3          0.0               24.42
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1371/journal.pone.0177459 is OK
- 10.1038/nrg.2016.49 is OK
- 10.21105/joss.00352 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.21105/joss.00352 is OK

MISSING DOIs

- https://doi.org/10.1093/bioinformatics/bts480 may be missing for title: Snakemake - a scalable bioinformatics workflow engine

INVALID DOIs

- https://doi.org/10.1101/162701 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02561/joss.02561/10.21105.joss.02561.pdf)

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@cokelaer - an OSI-approved license is required for JOSS to consider this submission - see https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements

**Comment by danielskatz** [comment]
Additionally, your paper needs to have a section entitled "Statement of Need" - see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

**Comment by danielskatz** [comment]
Finally, note that there is a DOI fix needed, and perhaps a missing DOI to be added

**Comment by cokelaer** [comment]
Dear Daniel, I've now uploaded a license file and created the DOI on zenodo (and updatedthe README of the repository itself). I have updated the paper to have a summary section and statement of need section, which should ease the reading and comply with JOSS requirements. I have not found instructions to include the DOI in the paper.md file itself. I noted the DOI and authors in the footnote of the online paper compilation tool are not correct but I believe this is not on my side. I hope that everything is settle foryou now; thanks

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02561/joss.02561/10.21105.joss.02561.pdf)

**Comment by danielskatz** [comment]
@cokelaer - you didn't need to create the DOI on zenodo - if there are changes in the software due to the review, a new version of the software will need to be archived.  By the missing DOI, I meant what was suggested in

> Reference check summary:
> 
> OK DOIs
> 
> - 10.1371/journal.pone.0177459 is OK
> - 10.1038/nrg.2016.49 is OK
> - 10.21105/joss.00352 is OK
> - 10.1038/s41592-018-0046-7 is OK
> - 10.21105/joss.00352 is OK
> 
> MISSING DOIs
> 
> - https://doi.org/10.1093/bioinformatics/bts480 may be missing for title: Snakemake - a scalable bioinformatics workflow engine
> 
> INVALID DOIs
> 
> - https://doi.org/10.1101/162701 is INVALID because of 'https://doi.org/' prefix

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1371/journal.pone.0177459 is OK
- 10.1038/nrg.2016.49 is OK
- 10.21105/joss.00352 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.21105/joss.00352 is OK

MISSING DOIs

- https://doi.org/10.1093/bioinformatics/bts480 may be missing for title: Snakemake - a scalable bioinformatics workflow engine

INVALID DOIs

- https://doi.org/10.1101/162701 is INVALID because of 'https://doi.org/' prefix
```

**Comment by danielskatz** [comment]
Note that you can issue the whedon commands to regenerate the pdf and check the references that I am doing.

**Comment by danielskatz** [comment]
Also, if you have items in your .bib file that are not being used as references, please remove them. This is a failing of whedon.

**Comment by cokelaer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1371/journal.pone.0177459 is OK
- 10.1038/nrg.2016.49 is OK
- 10.21105/joss.00352 is OK
- 10.1038/s41592-018-0046-7 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by cokelaer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02561/joss.02561/10.21105.joss.02561.pdf)

**Comment by cokelaer** [comment]
@danielskatz DOI corrected as well as bib file. PDF looks good to me; This at whedon is great by the way

**Comment by cokelaer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by cokelaer** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@KristinaRiemer
@VivianePons
@akeshavan
@arfon
@arokem
@bmcfee
@bstabler
@cMadan
@csoneson
@danielskatz
@dfm
@dhhagan
@diehlpk
@dpsanders
@drvinceknight
@eloisabentivegna
@fboehm
@galessiorob
@gkthiruvathukal
@harpolea
@hugoledoux
@jedbrown
@jgostick
@jni
@kakiac
@karthik
@katyhuff
@kbarnhart
@kthyng
@kyleniemeyer
@labarba
@leouieda
@lorenanicole
@lpantano
@majensen
@marcosvital
@mbobra
@meg-simula
@melissawm
@mikldk
@mjsottile
@oliviaguest
@pdebuyl
@pibion
@poulson
@richardjgowers
@sbenthall
@sjpfenninger
@terrytangyuan
@trallard
@usethedata
@will-rowe
@xuanxu
```

**Comment by cokelaer** [comment]
@danielskatz In the first part of the thread, I've been asked for suggesting potential reviewers. Here is aa short list: lorenanicole, jni, will-rowe,  drvinceknight

**Comment by danielskatz** [comment]
Unfortunately, these are editors, not reviewers.  We will find an editor.  You should suggest reviewers.   [This list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by cokelaer** [comment]
I believe those reviewers (non exhaustive list of users) should be relevant: 

fabianomenegidio, daissi, eteq, jeanmdavidson, smarkel

**Comment by cokelaer** [comment]
@danielskatz not sure how the review works. I have made some  changes to the paper (mostly in moving text in the correct summary/background/statement of need sections) and have now updated the repository accordingly. The latest version of the software (0.4.3)  has also been updated on pypi and the paper.md.

**Comment by kyleniemeyer** [comment]
Hello @cokelaer, thank you for your interest in JOSS.

The JOSS editorial board considered your submission, and we have decided that the software is too minor for JOSS to review—see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort for a description of what we consider substantial scholarly effort that warrants review/publication. (This is not a statement about the usefulness of your work.) We encourage you to consider JOSS at a later time if more effort and code goes into this software, or alternatively, consider publishing the software to Zenodo to get a DOI that users can cite.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
