### ISSUE TITLE
[REVIEW]: biorbd: A C++, Python and MATLAB library to analyze and simulate the human body biomechanics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2562]
**Submitting author:** @pariterre (<a href="http://orcid.org/0000-0002-5031-1048">Benjamin Michaud</a>)
**Repository:** <a href="https://github.com/pyomeca/biorbd" target ="_blank">https://github.com/pyomeca/biorbd</a>
**Version:** 1.3.2
**Editor:** @trallard
**Reviewer:** @trallard, @abhishektha
**Archive:** <a href="https://doi.org/10.5281/zenodo.4450303" target="_blank">10.5281/zenodo.4450303</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/52298f1fa05a60e6e312e1ee42806e82/status.svg)](https://joss.theoj.org/papers/52298f1fa05a60e6e312e1ee42806e82)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/52298f1fa05a60e6e312e1ee42806e82"><img src="https://joss.theoj.org/papers/52298f1fa05a60e6e312e1ee42806e82/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/52298f1fa05a60e6e312e1ee42806e82/status.svg)](https://joss.theoj.org/papers/52298f1fa05a60e6e312e1ee42806e82)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pyomeca/biorbd" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@trallard & @abhishektha, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @trallard know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pyomeca/biorbd">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pariterre) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pyomeca/biorbd">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pariterre) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @trallard, @abhishektha it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/S0021-9290(00)00155-X is OK
- 10.1007/s11044-017-9587-2 is OK
- 10.1016/j.simpat.2006.09.001 is OK
- 10.1007/978-3-540-36119-0_4 is OK
- 10.1109/ROBOT.2000.844153 is OK
- 10.1007/s10514-016-9574-0 is OK
- 10.1007/s00530-019-00633-9 is OK
- 10.1115/1.4029304 is OK
- 10.1016/j.jbiomech.2012.05.042 is OK
- 10.1016/j.jbiomech.2016.03.052 is OK
- 10.1007/s12206-018-1154-0 is OK
- 10.1145/1576246.1531386 is OK
- 10.1016/S0021-9290(03)00152-0 is OK
- 10.1080/00140139.2019.1571245 is OK
- 10.3389/fnbot.2019.00048 is OK
- 10.1371/journal.pcbi.1006223 is OK
- 10.1115/1.1531112 is OK
- 10.1016/j.jbiomech.2019.01.045 is OK
- 10.3389/fpsyg.2020.01159 is OK
- 10.1007/s10107-004-0559-y is OK

MISSING DOIs

- https://doi.org/10.1007/s12532-018-0139-4 may be missing for title: CasADi – A Software Framework for Nonlinear Optimization and Optimal Control
- https://doi.org/10.1080/10255842.2010.491958 may be missing for title: Estimation of the 3D Kinematics in Kayak Using an Extended Kalman Filter Algorithm: A Pilot Study
- https://doi.org/10.1201/9781315220352 may be missing for title: Robotics and Automation Handbook

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02562/joss.02562/10.21105.joss.02562.pdf)

**Comment by trallard** [comment]
/ooo from August 17 to September 2

**Comment by labarba** [comment]
hi 👋  – It looks like this review needs attention. @trallard, @abhishektha : can we have an update from you on your timeline to work on this? Thanks!

**Comment by abhishektha** [comment]
Hi 👋, sorry for the delay. Was planning on working on it this week!

**Comment by abhishektha** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02562/joss.02562/10.21105.joss.02562.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02562/joss.02562/10.21105.joss.02562.pdf) :page_facing_up: :point_left:

**Comment by abhishektha** [comment]
@trallard I can recommend biorbd for publication in JOSS. It is a very useful alternative to established programs like OpenSim for biomechanics analysis. biorbd easily calculates both forward and inverse kinematics and dynamics from given inputs using well-optimized C++ code. MATLAB and Python libraries allow for easy analysis in biorbd.

**Comment by trallard** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/S0021-9290(00)00155-X is OK
- 10.1007/s12532-018-0139-4 is OK
- 10.1007/s11044-017-9587-2 is OK
- 10.1016/j.simpat.2006.09.001 is OK
- 10.1016/j.gaitpost.2020.07.146 is OK
- 10.1007/978-3-540-36119-0_4 is OK
- 10.1109/ROBOT.2000.844153 is OK
- 10.1007/s10514-016-9574-0 is OK
- 10.1080/10255842.2010.491958 is OK
- 10.1007/s00530-019-00633-9 is OK
- 10.1115/1.4029304 is OK
- 10.1016/j.jbiomech.2012.05.042 is OK
- 10.1016/j.jbiomech.2016.03.052 is OK
- 10.1007/s12206-018-1154-0 is OK
- 10.1201/9781315220352 is OK
- 10.1145/1576246.1531386 is OK
- 10.1016/S0021-9290(03)00152-0 is OK
- 10.1080/00140139.2019.1571245 is OK
- 10.3389/fnbot.2019.00048 is OK
- 10.1371/journal.pcbi.1006223 is OK
- 10.1115/1.1531112 is OK
- 10.1016/j.jbiomech.2019.01.045 is OK
- 10.3389/fpsyg.2020.01159 is OK
- 10.1007/s10107-004-0559-y is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by trallard** [comment]
Thanks for your review and contribution to JOSS @abhishektha this is much appreciated

---
@pariterre your paper is needing an explicit [Statemen t of Need](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) section. 
I know this is pretty much covered in the Summary section, but we are now requesting for this to be a separate section for al JOSS papers

**Comment by pariterre** [comment]
@trallard 
Hi! Thanks for reviewing, that is really appreciated. There is a section called "The need for `biorbd`" Do you mean that I must add another one or just that the section's name should be "Statement of need"?

**Comment by pariterre** [comment]
@trallard 
up? :)

**Comment by arfon** [comment]
> Hi! Thanks for reviewing, that is really appreciated. There is a section called "The need for biorbd" Do you mean that I must add another one or just that the section's name should be "Statement of need"?

@pariterre - I would suggest renaming this section _Statement of need_. From our submission guidelines:

> A clear Statement of Need that illustrates the research purpose of the software.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02562/joss.02562/10.21105.joss.02562.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02562/joss.02562/10.21105.joss.02562.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@pariterre - could you take a look at the `@eigenweb` citation in your paper - I'm not sure it resolves to anything in your BibTeX file?

**Comment by arfon** [comment]
Also, can I just check the authorship list here? In your paper you say "A huge thanks to Ariane Dang for her patience and contribution to writing the tests for biorbd!". This author looks to be the `#2` [contributor to this package](https://github.com/pyomeca/biorbd/graphs/contributors) but doesn't look to be an author here. 

Could you say a little more about this please?

**Comment by pariterre** [comment]
Dear @arfon 

> @pariterre - could you take a look at the @eigenweb citation in your paper - I'm not sure it resolves to anything in your BibTeX file?

That is right, I don't know why though.. It is now fixed!

> Also, can I just check the authorship list here? In your paper you say "A huge thanks to Ariane Dang for her patience and contribution to writing the tests for biorbd!". This author looks to be the #2 contributor to this package but doesn't look to be an author here.
> 
> Could you say a little more about this please?

Ariane was a colleague of mine at the lab where I study (she now works elsewhere). She is an amazing person and I really like her very much. That said, she was mainly applying recipes that I was preparing for her (for instance, I was preparing a test, and she was copying it for all the relevant classes). I honestly have no problem adding her to the authorship, but I fell it would be kind of overkill.. As for her, when we discussed her position in the paper, she seemed totally fine with being only thanked. We can ping her if you want to confirm this information

**Comment by arfon** [comment]
> We can ping her if you want to confirm this information

Since you offer, for completeness I think we should do this. Thanks.

**Comment by pariterre** [comment]
@Dangzilla
I hope you are doing fine! We miss you at the lab :D

The reviewers for the paper on biorbd would like to confirm that you feel good about the fact that you are in the `acknowledgement` section instead of in the authors list. As you will see in earlier post, I told them that we basically worked together, and that most of the tests were written from a prepared recipe. 

Please fell free to answer entirely as you fell. So, if you fell that you should be part of the author list, please say so :)

**Comment by Dangzilla** [comment]
@pariterre I miss you guys as well!

Yes, no problem for the acknowledgement section. No need to be part of the author list :)

**Comment by arfon** [comment]
@pariterre - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

Also, please make a final check of the paper for any last possible updates (e.g., fixing typos).

I can then move forward with accepting the submission.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02562/joss.02562/10.21105.joss.02562.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02562/joss.02562/10.21105.joss.02562.pdf) :page_facing_up: :point_left:

**Comment by pariterre** [comment]
Hi @arfon 
I uploaded the 1.4.1 version (created after your last comment) of biorbd on Zenodo. The DOI is 10.5281/zenodo.4450303. I am not sure how I update this thread with the DOI though.. 
I made sure that the names and the paper title fit :)
Thanks!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4450303 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4450303" target="_blank">10.5281/zenodo.4450303</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2035

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2035, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/S0021-9290(00)00155-X is OK
- 10.1007/s12532-018-0139-4 is OK
- 10.1007/s11044-017-9587-2 is OK
- 10.1016/j.simpat.2006.09.001 is OK
- 10.1016/j.gaitpost.2020.07.146 is OK
- 10.1007/978-3-540-36119-0_4 is OK
- 10.1109/ROBOT.2000.844153 is OK
- 10.1007/s10514-016-9574-0 is OK
- 10.1080/10255842.2010.491958 is OK
- 10.1007/s00530-019-00633-9 is OK
- 10.1115/1.4029304 is OK
- 10.1016/j.jbiomech.2012.05.042 is OK
- 10.1016/j.jbiomech.2016.03.052 is OK
- 10.1007/s12206-018-1154-0 is OK
- 10.1201/9781315220352 is OK
- 10.1145/1576246.1531386 is OK
- 10.1016/S0021-9290(03)00152-0 is OK
- 10.1080/00140139.2019.1571245 is OK
- 10.3389/fnbot.2019.00048 is OK
- 10.1371/journal.pcbi.1006223 is OK
- 10.1115/1.1531112 is OK
- 10.1016/j.jbiomech.2019.01.045 is OK
- 10.3389/fpsyg.2020.01159 is OK
- 10.1007/s10107-004-0559-y is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@pariterre - I made a small number of formatting fixes in https://github.com/pyomeca/biorbd/pull/193

**Comment by pariterre** [comment]
@arfon 
It is now merged! Did I go too fast with the version on Zenodo?

**Comment by arfon** [comment]
> It is now merged! Did I go too fast with the version on Zenodo?

No, it's fine. We don't need these last fixes to the paper in the Zenodo archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2037

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2037, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1351601925393887232) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2038
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02562](https://doi.org/10.21105/joss.02562)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@trallard, @abhishektha - many thanks for your reviews here and to @trallard for editing this submission too! JOSS relies upon the volunteer efforts of folks like yourselves and we simply wouldn't be able to do this without you ✨ 

@pariterre your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02562/status.svg)](https://doi.org/10.21105/joss.02562)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02562">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02562/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02562/status.svg
   :target: https://doi.org/10.21105/joss.02562
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02562/status.svg)](https://doi.org/10.21105/joss.02562)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by pariterre** [comment]
Thanks everyone! :D
