### ISSUE TITLE
[PRE REVIEW]: RodiCS: a finite element solver of Kirchhoff rods under fluid flow and more

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2566]
**Submitting author:** @mou3adb (<a href="http://orcid.org/0000-0002-4908-4589">Mouad Boudina</a>)
**Repository:** <a href="https://github.com/lm2-poly/RodiCS" target ="_blank">https://github.com/lm2-poly/RodiCS</a>
**Version:** v1.0.0
**Editor:** @diehlpk
**Reviewers:** @ilyasst, @chennachaos
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mou3adb. **Currently, there isn't an JOSS editor assigned** to your paper.

@mou3adb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.57 s (54.1 files/s, 95120.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                             12              0              0          51888
Python                          16            613            385           1250
TeX                              1             18              0            226
Markdown                         2             46              0             91
-------------------------------------------------------------------------------
SUM:                            31            677            385          53455
-------------------------------------------------------------------------------


Statistical information for the repository '2566' was gathered on 2020/08/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
mou3adb                          1          2248              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
mou3adb                    2248          100.0          0.0               13.43
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.11588/ans.2015.100.20553 is OK
- 10.1145/2566630 is OK
- 10.1016/j.jfluidstructs.2003.12.004 is OK
- 10.1017/jfm.2017.910 is OK
- 10.1016/j.jfluidstructs.2015.12.009 is OK
- 10.1093/jxb/erz288 is OK
- 10.1146/annurev-fluid-122414-034606 is OK
- 10.1098/rstb.1998.0262 is OK
- 10.5281/zenodo.1287832 is OK
- 10.1016/j.jfluidstructs.2015.12.009 is OK
- 10.1016/j.jfluidstructs.2015.11.007 is OK
- 10.1017/S0022112009993673 is OK

MISSING DOIs

- https://doi.org/10.5860/choice.48-5112 may be missing for title: Elasticity and Geometry: From hair curls to the nonlinear response of shells
- https://doi.org/10.1146/annurev.fl.09.010177.002011 may be missing for title: Fluid mechanics of propulsion by cilia and flagella
- https://doi.org/10.1073/pnas.1409118111 may be missing for title: Coiling of elastic rods on rigid substrates

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02566/joss.02566/10.21105.joss.02566.pdf)

**Comment by kyleniemeyer** [comment]
Hi @diehlpk, the author suggested you to edit this submission. Do you have the bandwidth to take this one on?

**Comment by kyleniemeyer** [comment]
@whedon invite @diehlpk as editor

**Comment by whedon** [comment]
@diehlpk has been invited to edit this submission.

**Comment by diehlpk** [comment]
> Hi @diehlpk, the author suggested you to edit this submission. Do you have the bandwidth to take this one on?

@kyleniemeyer Yes, I can take it, but after that one I have six and can not handle more.

**Comment by diehlpk** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by diehlpk** [comment]
Hey @JaroslavHron @tupi @wkearn @dlagrava @adam-m-jcbs @mzamoraz @ctdegroot @mancellin @zbeekman would you be interested to review this paper?

**Comment by diehlpk** [comment]
> ```
> Reference check summary:
> 
> OK DOIs
> 
> - 10.11588/ans.2015.100.20553 is OK
> - 10.1145/2566630 is OK
> - 10.1016/j.jfluidstructs.2003.12.004 is OK
> - 10.1017/jfm.2017.910 is OK
> - 10.1016/j.jfluidstructs.2015.12.009 is OK
> - 10.1093/jxb/erz288 is OK
> - 10.1146/annurev-fluid-122414-034606 is OK
> - 10.1098/rstb.1998.0262 is OK
> - 10.5281/zenodo.1287832 is OK
> - 10.1016/j.jfluidstructs.2015.12.009 is OK
> - 10.1016/j.jfluidstructs.2015.11.007 is OK
> - 10.1017/S0022112009993673 is OK
> 
> MISSING DOIs
> 
> - https://doi.org/10.5860/choice.48-5112 may be missing for title: Elasticity and Geometry: From hair curls to the nonlinear response of shells
> - https://doi.org/10.1146/annurev.fl.09.010177.002011 may be missing for title: Fluid mechanics of propulsion by cilia and flagella
> - https://doi.org/10.1073/pnas.1409118111 may be missing for title: Coiling of elastic rods on rigid substrates
> 
> INVALID DOIs
> 
> - None
> ```

 @mou3adb Could you please check the missing DOIs and add them if they are missing?

**Comment by diehlpk** [comment]
@mou3adb Could you please add Montreal as city to both affiliations? Even it is mentioned in the school's name, we need the city as well.

**Comment by mou3adb** [comment]
Hi @diehlpk. I added the city, and fixed the DOIs, except for the book Elasticity and Geometry since it already has an ISBN.

**Comment by mou3adb** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02566/joss.02566/10.21105.joss.02566.pdf)

**Comment by diehlpk** [comment]
@whedon assign @ilyasst as reviewer

**Comment by whedon** [comment]
OK, @ilyasst is now a reviewer

**Comment by diehlpk** [comment]
@whedon add @chennachaos as reviewer

**Comment by whedon** [comment]
OK, @chennachaos is now a reviewer

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2577.
