### ISSUE TITLE
[PRE REVIEW]: AstroPaint: A Python Package for Painting Halo Catalogs into Celestial Maps

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2567]
**Submitting author:** @syasini (<a href="http://orcid.org/0000-0003-1978-6325">Siavash Yasini</a>)
**Repository:** <a href="https://github.com/syasini/AstroPaint" target ="_blank">https://github.com/syasini/AstroPaint</a>
**Version:** 0.1.1
**Editor:** @harpolea
**Reviewers:** @AshKelly, @zpace
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @syasini. **Currently, there isn't an JOSS editor assigned** to your paper.

@syasini if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1088/0004-637X/709/2/920 is OK
- 10.2172/1556957 is OK
- 10.3847/2041-8213/ab0bfe is OK
- 10.1093/mnras/stw2035 is OK
- 10.21105/joss.01298 is OK
- 10.1038/302315a0 is OK
- 10.1093/mnras/sty3226 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02567/joss.02567/10.21105.joss.02567.pdf)

**Comment by kyleniemeyer** [comment]
Hi @harpolea, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @harpolea as editor

**Comment by whedon** [comment]
@harpolea has been invited to edit this submission.

**Comment by syasini** [comment]
Thanks for initiating the review and edit process! Looking forward to your feedback.

**Comment by Kevin-Mattheus-Moerman** [comment]
@harpolea would you be able to handle this submission?

**Comment by zpace** [comment]
Sorry, I can't commit to this at the moment. Would love to review something in a couple weeks, though

**Comment by harpolea** [comment]
@zpace Thanks for your response! We typically ask that reviews are completed within 6 weeks – do you think that you'd be able to complete a review within that time frame?

**Comment by AshKelly** [comment]
Hi @harpolea  - I'm very happy to review this!

**Comment by harpolea** [comment]
@AshKelly Great, thanks!

**Comment by harpolea** [comment]
@whedon assign @AshKelly as reviewer

**Comment by whedon** [comment]
OK, @AshKelly is now a reviewer

**Comment by zpace** [comment]
@harpolea yes, after a little though, I think that's doable. I'd be happy to referee! :smile:

**Comment by harpolea** [comment]
@zspace thank you!

**Comment by harpolea** [comment]
@whedon add @zpace as reviewer

**Comment by whedon** [comment]
OK, @zpace is now a reviewer

**Comment by harpolea** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2608.

**Comment by syasini** [comment]
Thanks @AshKelly and @zpace for accepting to review our work. And thanks @harpolea for your help in organizing the review process. 

Looking forward to the future steps and all your feedback!
