### ISSUE TITLE
[PRE REVIEW]: dorado: A Python package for simulating passive particle transport in shallow-water flows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2568]
**Submitting author:** @elbeejay (<a href="http://orcid.org/0000-0002-1343-193X">Jayaram Hariharan</a>)
**Repository:** <a href="https://github.com/passaH2O/dorado" target ="_blank">https://github.com/passaH2O/dorado</a>
**Version:** v1.0.0
**Editor:** @kbarnhart
**Reviewers:** @dbuscombe-usgs, @gassmoeller
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @elbeejay. **Currently, there isn't an JOSS editor assigned** to your paper.

@elbeejay if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5194/gmd-11-1405-2018 is OK
- 10.1038/072342a0 is OK
- 10.5194/esurf-3-67-2015 is OK
- 10.5194/esurf-3-87-2015 is OK
- 10.1016/j.ocemod.2014.02.007 is OK
- 10.1525/bio.2009.59.6.8 is OK
- 10.1017/S0022112089002697 is OK
- 10.1002/2017WR021289 is OK
- 10.1029/2018GL079405 is OK
- 10.1016/j.marchem.2016.05.011 is OK
- 10.1016/j.ecss.2016.02.001 is OK
- 10.1016/j.jhydrol.2005.11.055 is OK
- 10.1029/2018WR023527 is OK
- 10.1029/2012GL053476 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @kbarnhart, can you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @kbarnhart as editor

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02568/joss.02568/10.21105.joss.02568.pdf)

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by elbeejay** [comment]
We think that reviewers from the fields of hydrology or geomorphology might best. I went through the list of reviewers to come up with the following list of potential reviewers (in no particular order):

Mankoff
dvalters
sgrieve
lheagy
krischer
Scivision
rmsare
amabdallah
nathanlyons
margauxmouchene
kmarkert
leouieda
kellykochanski
martibosch
tretherington
castelao
pytzcarraldo
Lachlangrose
dbuscombe-usgs
AtrCheema
Jessepisel
arthur-e
TomasBeuzen
arbennett
mdbartos
SWgeoscience
abhiramm7
pwernette
katmratliff
ldominguezruben
marda-science

**Comment by kbarnhart** [comment]
@kyleniemeyer I'd be happy to handle this. 

@elbeejay thanks for this submission and for the proposed reviewers. I'll start the process of requesting reviewers in the next 2-3 days. Between then and now I'll do my standard pre-review look through the submission and get you any associated feedback.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.14 s (468.8 files/s, 46746.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          27            727           1211           1964
reStructuredText                31            464            540            463
TeX                              1             20              0            208
YAML                             4             18              4            179
Jupyter Notebook                 1              0            689             69
Markdown                         2             25              0             68
make                             1             10              6             16
-------------------------------------------------------------------------------
SUM:                            67           1264           2450           2967
-------------------------------------------------------------------------------


Statistical information for the repository '2568' was gathered on 2020/08/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
J. Hariharan                     5             5              5            0.06
JayH                            66          6111           2409           52.12
Jayaram Hariharan                2          2266           2266           27.72
Kyle A Wright                    4            22             17            0.24
Wright                          26          1440            943           14.58
jay                              9           281            583            5.29

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
J. Hariharan               3030        60600.0          2.5               17.59
Jayaram Hariharan            52            2.3          0.4                1.92
Kyle A Wright                 6           27.3          2.5               16.67
Wright                      814           56.5          1.2               11.92
```

**Comment by kbarnhart** [comment]
@elbeejay I've now completed my pre-review checks and will begin looking for reviewers. I found one minor item that I think would be good to address before review begins: you have tests, but no instructions for how to run them. I would recommend indicating how a potential users would test their install somewhere on the readme and/or docs.

**Comment by kbarnhart** [comment]
:wave: @dbuscombe-usgs @gassmoeller @TomasBeuzen would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This submission is for "dorado: A Python package for simulating passive particle transport in shallow-water flows". I'm reaching out to you based on your expertise in fluid flow, particle methods, and/or python. 

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) before accepting the review invitation. 

If you have any questions about the JOSS review process, please do not hesitate to reach out to me by commenting on this issue or emailing me directly at krbarnhart@usgs.gov

**Comment by dbuscombe-usgs** [comment]
Yes, I can do it

**Comment by kbarnhart** [comment]
@whedon add @dbuscombe-usgs as reviewer

**Comment by whedon** [comment]
OK, @dbuscombe-usgs is now a reviewer

**Comment by gassmoeller** [comment]
@kbarnhart: I can review this as well.

**Comment by TomasBeuzen** [comment]
@kbarnhart: I can do this too.

**Comment by gassmoeller** [comment]
@TomasBeuzen: If you prefer to review, I am happy to step back, I am still involved in another review with JOSS at the moment.

**Comment by TomasBeuzen** [comment]
@gassmoeller - sure no preference, I'm happy with whatever @kbarnhart decides. FYI I'm more experienced with Python than hydrodynamics so my review will focus mostly on the code (style, usability, functionality, etc.) and clarity of the manuscript.

**Comment by kbarnhart** [comment]
Thanks all for the enthusiasm!! Given your expertise in particle methods in geodynamic models I'm inclined to include you as a reviewer. I'll now start the review with @dbuscombe-usgs and @gassmoeller as reviewers.  Thanks again!

**Comment by kbarnhart** [comment]
@whedon add @gassmoeller as reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2585.
