### ISSUE TITLE
[PRE REVIEW]: Thermoelasticity-based analysis: collection of python packages

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2569]
**Submitting author:** @LolloCappo (<a href="http://orcid.org/0000-0002-1333-9930">Lorenzo Capponi</a>)
**Repository:** <a href="https://github.com/LolloCappo/Thermoelasticity-based-analysis-collection-of-python-packages" target ="_blank">https://github.com/LolloCappo/Thermoelasticity-based-analysis-collection-of-python-packages</a>
**Version:** 1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @LolloCappo. **Currently, there isn't an JOSS editor assigned** to your paper.

@LolloCappo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (168.6 files/s, 15847.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            143            200            164
TeX                              1              0              0             70
Markdown                         2             14              0             67
-------------------------------------------------------------------------------
SUM:                             7            157            200            301
-------------------------------------------------------------------------------


Statistical information for the repository '2569' was gathered on 2020/08/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Lorenzo Capponi                  1           507              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Lorenzo Capponi             507          100.0          0.0                3.94
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.ijfatigue.2020.105661 is OK

MISSING DOIs

- https://doi.org/10.1109/i2mtc43012.2020.9128771 may be missing for title: Structural Characterization of Complex Lattice Parts by Means of Optical Non-Contact Measurements
- https://doi.org/10.1007/978-3-662-24691-7_39 may be missing for title: Über die specifische Wärme fester Körper, insbesondere der Metalle
- https://doi.org/10.1016/j.ymssp.2014.12.011 may be missing for title: Defect identification based on parameter estimation of histogram in ultrasonic IR thermography
- https://doi.org/10.1109/tim.2019.2959293 may be missing for title: Investigating additive manufactured lattice structures: a multi-instrument approach
- https://doi.org/10.1016/j.ijfatigue.2011.09.005 may be missing for title: Adopting lock-in infrared thermography technique for rapid determination of fatigue limit of aluminum alloy riveted component and affection to determined result caused by initial stress

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02569/joss.02569/10.21105.joss.02569.pdf)

**Comment by LolloCappo** [comment]
What should I do now?

**Comment by kyleniemeyer** [comment]
Hello @LolloCappo, thank you for your interest in JOSS. 

The JOSS editorial board has considered your submission, and found that it is too minor for JOSS to review—see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort for what we consider "substantial scholarly effort". (This is not a statement about the usefulness of your work.) We encourage you to consider JOSS at a later time if more effort and code goes into this software, or alternatively, consider publishing the software to Zenodo to get a DOI that users can cite.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
