### ISSUE TITLE
[REVIEW]: Varistran: Anscombe's variance stabilizing transformation for RNA-seq gene expression data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#257]
**Submitting author:** @pfh (<a href="http://orcid.org/0000-0002-3980-268X">Paul Harrison</a>)
**Repository:** <a href="https://github.com/MonashBioinformaticsPlatform/varistran" target ="_blank">https://github.com/MonashBioinformaticsPlatform/varistran</a>
**Version:** v1.0.1
**Editor:** @brainstorm
**Reviewer:** @roryk
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.846925" target="_blank">10.5281/zenodo.846925</a>

## Status

[![status](http://joss.theoj.org/papers/1a0896a899e8dd80d6284858dbfca4ba/status.svg)](http://joss.theoj.org/papers/1a0896a899e8dd80d6284858dbfca4ba)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/1a0896a899e8dd80d6284858dbfca4ba"><img src="http://joss.theoj.org/papers/1a0896a899e8dd80d6284858dbfca4ba/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/1a0896a899e8dd80d6284858dbfca4ba/status.svg)](http://joss.theoj.org/papers/1a0896a899e8dd80d6284858dbfca4ba)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/MonashBioinformaticsPlatform/varistran" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/MonashBioinformaticsPlatform/varistran">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.1)?
- [x] **Authorship:** Has the submitting author (@pfh) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @roryk it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @roryk - friendly reminder that this review is waiting for you 😄

**Comment by brainstorm** [comment]
@roryk If you need some guidance regarding the remaining checkboxes, let me know... I actually need some guidance on the editorial side, @arfon. Is there something special I should do when Rory finishes the review? First editing role :)

**Comment by arfon** [comment]
> @arfon. Is there something special I should do when Rory finishes the review? First editing role :)

@brainstorm - once @roryk has finished his review ping me here and I can finalize the submission.

**Comment by roryk** [comment]
It looks good to me-- I pinged them about the couple of checkboxes that are open, a couple references need to get linked to and a section about contributing and then it is all good.

**Comment by brainstorm** [comment]
Thanks a lot @roryk, seems that they might have addressed that in their latests commits a few days ago?:

https://github.com/MonashBioinformaticsPlatform/varistran/commits/master

**Comment by roryk** [comment]
Heya-- this look all set to me!

**Comment by brainstorm** [comment]
@arfon Clear to finalize/go then! Thanks much Rory! ;)

**Comment by arfon** [comment]
@pfh - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by pfh** [comment]
@arfon - Great! I've uploaded a tarball of the latest version to Zenodo, DOI is https://doi.org/10.5281/zenodo.846925

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.846925 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.846925" target="_blank">10.5281/zenodo.846925</a> is the archive.

**Comment by arfon** [comment]
@roryk - many thanks for your review here and to @brainstorm for editing this submission ✨ 

@pfh - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00257 ⚡️ 🚀 💥

**Comment by roryk** [comment]
Awesome!

**Comment by pfh** [comment]
Great to have this reviewed, published and citable. It's a component in quite a lot of the work we do. Thanks everyone.
