### ISSUE TITLE
[PRE REVIEW]: Minerva: a light-weight, narrative image browser for multiplexed tissue images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2570]
**Submitting author:** @thejohnhoffer (<a href="http://orcid.org/0000-0002-5877-4266">John Hoffer</a>)
**Repository:** <a href="https://github.com/labsyspharm/minerva-story" target ="_blank">https://github.com/labsyspharm/minerva-story</a>
**Version:** v1.0.0
**Editor:** @jni
**Reviewers:** @will-moore, @sofroniewn
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @thejohnhoffer. **Currently, there isn't an JOSS editor assigned** to your paper.

@thejohnhoffer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/j.cels.2016.03.008 is OK
- 10.1016/j.cell.2020.03.053 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.1158/2159-8290.CD-12-0095 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.54 s (523.6 files/s, 154492.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                     157          10259          11836          38023
CSS                              7           1299            103          10286
Sass                            88           1245           1029           5117
SVG                             10              2              2           1322
YAML                             2             40             12            591
HTML                             2             36              2            441
Markdown                         6            163              0            409
JSON                             6              1              0            405
TypeScript                       1             25             13            121
Python                           1             12              1             64
TeX                              1              6              0             49
-------------------------------------------------------------------------------
SUM:                           281          13088          12998          56828
-------------------------------------------------------------------------------


Statistical information for the repository '2570' was gathered on 2020/08/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
John Hoffer                     10        102676          42075          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
John Hoffer               60601           59.0          0.0               19.63
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02570/joss.02570/10.21105.joss.02570.pdf)

**Comment by kyleniemeyer** [comment]
Hi @jni, can you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @jni as editor

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hi @thejohnhoffer, thanks for your submission to JOSS. It looks like your article is missing one of the required elements: https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

**Comment by jni** [comment]
@whedon add me as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by jni** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jni

**Comment by will-moore** [comment]
@jni I'd be happy to review this.
Not reviewed for JOSS before, so might need some pointers...

**Comment by jni** [comment]
Awesome, thank you so much, @will-moore!

This is actually my second review as editor, but thankfully the JOSS process well documented, essentially:
- read the reviewer guidelines here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html
- read the review criteria: https://joss.readthedocs.io/en/latest/review_criteria.html
- work your way through the checklist, which will also appear in the review issue: https://joss.readthedocs.io/en/latest/review_checklist.html

All this will happen *after* I ask whedon to start the review (shortly), which will create a separate REVIEW issue, on which you'll be pinged.

Again, thank you! :tada:

**Comment by jni** [comment]
@whedon assign @will-moore as reviewer

**Comment by whedon** [comment]
OK, @will-moore is now a reviewer

**Comment by jni** [comment]
@whedon add @sofroniewn as reviewer

@sofroniewn, thanks for agreeing to review, and please see my [comment above](https://github.com/openjournals/joss-reviews/issues/2570#issuecomment-674845258) for a summary of the JOSS review process!

**Comment by whedon** [comment]
OK, @sofroniewn is now a reviewer

**Comment by jni** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2579.
