### ISSUE TITLE
[PRE REVIEW]: SLAM Toolbox: SLAM for the dynamic world

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2572]
**Submitting author:** @stevemacenski (<a href="http://orcid.org/0000-0003-1090-7733">Steven Macenski</a>)
**Repository:** <a href="https://github.com/SteveMacenski/slam_toolbox" target ="_blank">https://github.com/SteveMacenski/slam_toolbox</a>
**Version:** 2.3.0
**Editor:** @arfon
**Reviewers:** @mosteo, @carlosjoserg
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @stevemacenski. **Currently, there isn't an JOSS editor assigned** to your paper.

@stevemacenski if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2572 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.28 s (275.6 files/s, 86887.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                    26           1803           4746           7389
C++                             19           1100           1296           5199
CMake                           10            218            368           1083
YAML                             6             44             51            412
Markdown                         4            169              0            251
Python                           7             42             30            181
XML                              4             15             17            117
reStructuredText                 1              5              0             32
Dockerfile                       1              5              3             14
-------------------------------------------------------------------------------
SUM:                            78           3401           6511          14678
-------------------------------------------------------------------------------


Statistical information for the repository '2572' was gathered on 2020/08/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alexey Merzlyakov                1            42             14            0.07
Christen Lofland                 1             1              1            0.00
Jason Mercer                     1             3              3            0.01
Joe Dinius                       1             3              2            0.01
Jon Binney                       1           761           1737            3.02
Luc Bettaieb                     3           121              2            0.15
Michael Equi                     2             4              4            0.01
Michael Ferguson                 3             5              5            0.01
Steve Macenski                   6          2036           2159            5.07
Steven Macenski                 14         19085          15419           41.74
Tobias Fischer                   2            43              1            0.05
bhaskara                        17          1815             78            2.29
ivonaj                           3         13109              1           15.86
maxlein                          2            57             37            0.11
mgerdzhev                        2            13             17            0.04
michel                           1             6              0            0.01
stevemacenski                  172         15130          10947           31.55

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alexey Merzlyakov            42          100.0          2.7                0.00
Christen Lofland              1          100.0          0.2                0.00
Jason Mercer                  1           33.3         43.9                0.00
Joe Dinius                    1           33.3         10.7                0.00
Luc Bettaieb                  1            0.8         62.3                0.00
Michael Equi                  2           50.0          0.9                0.00
Steve Macenski            10156          498.8         12.5               20.55
Tobias Fischer               43          100.0          0.0                6.98
bhaskara                     44            2.4          0.0               31.82
ivonaj                    11441           87.3         19.9               34.52
maxlein                      52           91.2          8.3                0.00
michel                        2           33.3         11.6                0.00
```

**Comment by kyleniemeyer** [comment]
Hi @bstabler, this might be a little bit outside your wheelhouse, but could you edit it?

**Comment by kyleniemeyer** [comment]
@whedon invite @bstabler as editor

**Comment by whedon** [comment]
@bstabler has been invited to edit this submission.

**Comment by SteveMacenski** [comment]
> Can't find any papers to compile :-(

I'm not sure why it couldn't find the file, it built fine with the preview tool. Its on the `joss` branch. 

carlosjoseRG, mosteo, or traversaro could make good editors (all listing C++ and robotics)

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02572/joss.02572/10.21105.joss.02572.pdf)

**Comment by bstabler** [comment]
@kyleniemeyer - yes, I'm happy to edit it.  It looks like an interesting toolbox.

**Comment by kyleniemeyer** [comment]
@whedon assign @bstabler as editor

**Comment by whedon** [comment]
OK, the editor is @bstabler

**Comment by SteveMacenski** [comment]
Hi, just following back up here. Anything I can do to help most this forward?

**Comment by bstabler** [comment]
Hi @SteveMacenski - I finally read the paper.  I have a couple small comments on the paper while we look for reviewers:
  - there is a typo "proided"
  - an explicit Statement of Need section needs to be added
  - the Configuration section of the paper is not needed and should probably instead be in the online and/or package documentation

@carlosjoseRG, @mosteo, @muhaochen, @breznak, @jcarpent, or @traversaro - are you interested in reviewing this paper?

**Comment by SteveMacenski** [comment]
Hi,

Thanks for the review! 
- Typo fixed
- I'd be happy to. Should this be another section in the paper? I based my format on [this](https://joss.theoj.org/papers/10.21105/joss.01531) and [this](https://joss.theoj.org/papers/10.21105/joss.00456) paper in JOSS in the robotics space, which have that built into the summary. I can reiterate the statement of need in a separate section if that would be preferable. Let me know what you think. 
- That content is also available in the readme. I figured it would be good to add here as well, even if not required, to add some more context to the reader. I can remove it if you like, but I think it provides some useful context if this is their first introduction to the work in reading the paper.

**Comment by bstabler** [comment]
Yes, it should now be an explicit section of the paper, see https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain.  For the second item, I think it's too much detail for this high level introduction / summary.  Thanks.

**Comment by SteveMacenski** [comment]
Ok,

- Statement of need section added https://github.com/SteveMacenski/slam_toolbox/commit/efb33ec1afe4bfee7e26624a0c3f48ccfb8ec721
- Configuration section removed https://github.com/SteveMacenski/slam_toolbox/commit/ea6ee14bce12885024342ce598c8b15a375d50bb

**Comment by bstabler** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02572/joss.02572/10.21105.joss.02572.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02572/joss.02572/10.21105.joss.02572.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@SteveMacenski - apologies for the very slow progress here. I'll be taking over to help out Ben here.

:wave: @mosteo & @carlosjoseRG - would you be interested in reviewing this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The software under review is [_SLAM Toolbox: SLAM for the dynamic world_](https://github.com/SteveMacenski/slam_toolbox), the paper we'd ask you to review is available [here](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02572/joss.02572/10.21105.joss.02572.pdf).

**Comment by arfon** [comment]
@whedon add @mosteo as reviewer

**Comment by whedon** [comment]
OK, @mosteo is now a reviewer

**Comment by arfon** [comment]
@onlytailei @pifon2a @ojura - would you be interested in reviewing this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The software under review is [_SLAM Toolbox: SLAM for the dynamic world_](https://github.com/SteveMacenski/slam_toolbox), the paper we'd ask you to review is available [here](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02572/joss.02572/10.21105.joss.02572.pdf).

**Comment by carlosjoserg** [comment]
> @SteveMacenski - apologies for the very slow progress here. I'll be taking over to help out Ben here.
> 
>  @mosteo & @carlosjoserg - would you be interested in reviewing this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html
> 
> The software under review is [_SLAM Toolbox: SLAM for the dynamic world_](https://github.com/SteveMacenski/slam_toolbox), the paper we'd ask you to review is available [here](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02572/joss.02572/10.21105.joss.02572.pdf).

Sorry, I'm just seeing this thread now. I'm not a SLAM expert, I come more from the manipulation world. If you are interested in me reviewing the soft/paper, let me know.

**Comment by arfon** [comment]
Thanks for the response @carlosjoserg - we'd love to have your assistance here ✨. I'll go ahead and add you as a reviewer now and start the review process.

**Comment by arfon** [comment]
@whedon add @carlosjoserg as reviewer

**Comment by whedon** [comment]
OK, @carlosjoserg is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2783.

**Comment by arfon** [comment]
@mosteo, @carlosjoserg - please head over to #2783 where the actual review will take place!
