### ISSUE TITLE
[PRE REVIEW]: Dittodb: A Test Environment for Database Requests

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2573]
**Submitting author:** @pachamaltese (<a href="http://orcid.org/0000-0003-1017-7574">Mauricio Vargas</a>)
**Repository:** <a href="https://github.com/ropensci/dittodb" target ="_blank">https://github.com/ropensci/dittodb</a>
**Version:** 0.1.1.9001
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pachamaltese. **Currently, there isn't an JOSS editor assigned** to your paper.

@pachamaltese if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.20 s (429.2 files/s, 101017.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SQL                              4            148            143          12447
R                               48            397            943           2411
SVG                              1              0              0           1079
Markdown                        10            206              0            559
YAML                             6             69             14            336
JSON                             1              0              0            311
Rmd                              4            144            241            203
JavaScript                       1             28             40             98
Bourne Shell                     7             15             14             72
TeX                              1              4              0             38
C                                2             10              3             35
-------------------------------------------------------------------------------
SUM:                            85           1021           1398          17589
-------------------------------------------------------------------------------


Statistical information for the repository '2573' was gathered on 2020/08/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jonathan Keane                   9         12961            207           98.52
pachamaltese                     1           198              0            1.48

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jonathan Keane            12952           99.9          5.6                1.77
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.32614/rj-2011-002 may be missing for title: testthat: Get Started with Testing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02573/joss.02573/10.21105.joss.02573.pdf)

**Comment by kyleniemeyer** [comment]
Hello @pachamaltese, thank you for your interest in JOSS.

The JOSS editorial board considered your submission, and in our view the software is both too minor for JOSS to review, and not in our definition of research software—see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort and https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software for our standards. (This is not a statement about the usefulness of your work.) We encourage you to consider JOSS at a later time if the software changes substantially, or alternatively, consider publishing the software to Zenodo to get a DOI that users can cite.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
