### ISSUE TITLE
[PRE REVIEW]: Foolbox Native: Fast adversarial attacks to benchmark the robustness of machine learning models in PyTorch, TensorFlow, and JAX

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2574]
**Submitting author:** @jonasrauber (<a href="http://orcid.org/0000-0001-6795-9441">Jonas Rauber</a>)
**Repository:** <a href="https://github.com/bethgelab/foolbox" target ="_blank">https://github.com/bethgelab/foolbox</a>
**Version:** v3.1.0
**Editor:** @terrytangyuan
**Reviewers:** @GregaVrbancic, @ethanwharris
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jonasrauber. **Currently, there isn't an JOSS editor assigned** to your paper.

@jonasrauber if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by kyleniemeyer** [comment]
Hi @terrytangyuan, do you have the bandwidth to edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @terrytangyuan as editor

**Comment by whedon** [comment]
@terrytangyuan has been invited to edit this submission.

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/sp40000.2020.00045 may be missing for title: HopSkipJumpAttack: A query-efficient decision-based attack

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02574/joss.02574/10.21105.joss.02574.pdf)

**Comment by terrytangyuan** [comment]
Yes, I can edit this one.

**Comment by jonasrauber** [comment]
We had one small technical issue when creating the paper: the „joint senior authors“ footnote could only be added to one senior author. This seems to be a limitation of the Markdown to LaTeX conversion.
Any ideas how we can fix this?
How do you usually indicate joint first authors?

**Comment by terrytangyuan** [comment]
@jonasrauber if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Comment by kyleniemeyer** [comment]
@whedon assign @terrytangyuan as editor

**Comment by whedon** [comment]
OK, the editor is @terrytangyuan

**Comment by kyleniemeyer** [comment]
> We had one small technical issue when creating the paper: the „joint senior authors“ footnote could only be added to one senior author. This seems to be a limitation of the Markdown to LaTeX conversion.
> Any ideas how we can fix this?
> How do you usually indicate joint first authors?

@openjournals/dev any ideas about this author footnote issue?

**Comment by arfon** [comment]
> @openjournals/dev any ideas about this author footnote issue?

The way I recommend doing this is with a footnote next to the name of the first (or second) author stating that they are joint first authors e.g.:

```
authors:
  - name: First Author
    orcid: 0000-0003-0872-7098
    affiliation: "1, 2" 
  - name: Second Author^[Joint first author]
    affiliation: 2
```

**Comment by jonasrauber** [comment]
@terrytangyuan 

Here are some suggestions for potential reviewers from the list:

- ethanwharris
- rasbt
- willprice

And some more potential reviewers from the list:

- GregaVrbancic
- JesseLivezey
- nilesh-patil

It’s difficult to find someone from the specific field (adversarial robustness) on the list, so here is another suggestion, but he is not (yet) on the list:

- ttbrunner (Note: we are co-authors on a book chapter for a competition that we organized and in which ttbrunner participated; I don’t think it’s an actual COI, but it may be perceived as one)

**Comment by terrytangyuan** [comment]
👋 Hi @ethanwharris @rasbt @willprice @GregaVrbancic, if you would like to review for this submission, please let us know here! We need at least two reviewers.

**Comment by GregaVrbancic** [comment]
Hi @terrytangyuan, I am available to review this submission, but unfortunately, not before the end of next week. Sadly, I do not work in this specific field but I do most of my work training deep CNNs, so I think I would be able to adequately review this submission.

**Comment by terrytangyuan** [comment]
@whedon assign @GregaVrbancic as reviewer

**Comment by whedon** [comment]
OK, @GregaVrbancic is now a reviewer

**Comment by terrytangyuan** [comment]
Yes that would work. We still need another reviewer. Anyone else?

**Comment by ethanwharris** [comment]
Hi @terrytangyuan, I would be very happy to review this. I have limited experience with the specific area of adversarial robustness research but have done a good amount with deep learning and interpretability :smiley:

**Comment by terrytangyuan** [comment]
@whedon add @ethanwharris as reviewer

**Comment by whedon** [comment]
OK, @ethanwharris is now a reviewer

**Comment by terrytangyuan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2607.
