### ISSUE TITLE
[REVIEW]: ELECTRIC: Electric fields Leveraged from multipoleExpansion Calculations in Tinker Rapid Interface Code

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2576]
**Submitting author:** @valeriewelborn (<a href="http://orcid.org/0000-0003-0834-4441">Valerie Vaissier</a>)
**Repository:** <a href="https://github.com/WelbornGroup/ELECTRIC" target ="_blank">https://github.com/WelbornGroup/ELECTRIC</a>
**Version:** v1.0.0
**Editor:** @richardjgowers
**Reviewer:** @amandadumi, @govarguz
**Archive:** <a href="https://doi.org/10.5281/zenodo.4116258" target="_blank">10.5281/zenodo.4116258</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f311fd4ba2f3c1634ee26a6662898ea3/status.svg)](https://joss.theoj.org/papers/f311fd4ba2f3c1634ee26a6662898ea3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f311fd4ba2f3c1634ee26a6662898ea3"><img src="https://joss.theoj.org/papers/f311fd4ba2f3c1634ee26a6662898ea3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f311fd4ba2f3c1634ee26a6662898ea3/status.svg)](https://joss.theoj.org/papers/f311fd4ba2f3c1634ee26a6662898ea3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/WelbornGroup/ELECTRIC" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@amandadumi & @govarguz, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @richardjgowers know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/WelbornGroup/ELECTRIC">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@valeriewelborn) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/WelbornGroup/ELECTRIC">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@valeriewelborn) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @amandadumi, @govarguz it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1146/annurev-biophys-070317-033349 is OK
- 10.1021/ct4003702 is OK
- 10.1021/acs.jctc.8b00529 is OK
- 10.1021/acs.jctc.7b01169 is OK
- 10.1021/jacs.6b12265 is OK
- 10.1021/acscatal.7b03151 is OK
- 10.1038/s41929-018-0109-2 is OK
- 10.5281/zenodo.3659285 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02576/joss.02576/10.21105.joss.02576.pdf)

**Comment by richardjgowers** [comment]
Hi @amandadumi and @govarguz thanks for agreeing to review, we'll be doing that in this issue.  In general it works best if you raise issues against the ELECTRIC repository when you find issues.  Let me know if you run into any issues.

**Comment by govarguz** [comment]
Hi @whedon, the invitation link has expired. I think, I have accepted it but I changed recently of terminal. Do I need to accept the review invitation again?
Thanks for your attention, Horacio.

**Comment by valeriewelborn** [comment]
Hi @richardjgowers @amandadumi @govarguz, just checking on the status of this review as it's been a while. Have you had a chance to look at it? Thank you

**Comment by amandadumi** [comment]
Hello @valeriewelborn, thanks for your patience. I am nearly done! Just writing up some final comments which should be posted by tomorrow. I appreciate your patience.

**Comment by amandadumi** [comment]
Great work! This is a nice addition to the analysis tools for force fields, especially one that is open source and handles large data efficiently. I have submitted some issues for feedback according to specific section of the review WelbornGroup/ELECTRIC#17, WelbornGroup/ELECTRIC#18.

I have one general question about the Tinker modified for ELECTRIC. The ELECTRIC repository references this adapted Tinker: https://github.com/WelbornGroup/Tinker_ELECTRIC while in the pre-review (openjournals/joss-reviews/issues/2429) the authors mention https://github.com/MolSSI-MDI/Tinker/tree/mdi-efr as the adapted Tinker code. Which of these is correct? If it is the WelbornGroup version, since it is not a fork from the original Tinker repository, it is hard to tell what has changed. Could your provide some insight on where your contributions are? Once I understand which modified Tinker to use, I will provide feedback on the code.

In regards to the  Contribution and authorship point within the General Check category, the submitting author, @valeriewelborn  is not the main code contributor of ELECTRIC according to the git commit log. However, it seems to be that they are the PI leading this work so I do not see an issue with this in terms of publishing as this is very common dynamic. Though with the specific wording of this point, I wanted to ensure this will not bring about any issues for JOSS that I may be overlooking.  Is this acceptable for JOSS, @richardjgowers ?

**Comment by valeriewelborn** [comment]
Hi @amandadumi, thanks for the comments.  https://github.com/WelbornGroup/Tinker_ELECTRIC is a copy of https://github.com/MolSSI-MDI/Tinker/tree/mdi-efr so you can go directly to https://github.com/MolSSI-MDI/Tinker/tree/mdi-efr for review of the modified version of Tinker.

**Comment by valeriewelborn** [comment]
@govarguz, @richardjgowers  have you had a chance to look at the submission?

**Comment by govarguz** [comment]
Dear all, I am looking now to more details but may need a couple of days to
wrap up my comments. Best!

**Comment by govarguz** [comment]
@valeriewelborn I have submitted my review to your JOSS Ms. I have made 3 suggestions to the Ms. as seen in [here](https://github.com/WelbornGroup/ELECTRIC/issues/19). Those points may also clarify the concept of ELECTRIC and what is behind. Moreover, clearly show where the ELECTRIC contribution is (e.g. through a flowchart diagram). 
Another very minor comment for the Authors affiliation, do you normally use the name without an address? cc: @richardjgowers

**Comment by richardjgowers** [comment]
@valeriewelborn did you mean https://github.com/MolSSI-MDI/Tinker/commits/mdi-ef ?  In general it's useful to see the commits that are "on top" of the base TINKER.  E.g. if https://github.com/WelbornGroup/Tinker_ELECTRIC could have one commit which is the check in of the release of TINKER you built on and another commit (or more) showing the changes made for this work.  That way someone can quickly review how/why the dynamics are different (or are the same).

**Comment by richardjgowers** [comment]
@valeriewelborn also I think we'll need full addresses in the affiliations if possible, thanks

**Comment by valeriewelborn** [comment]
@richardjgowers The modifications to Tinker that enable the MDI interface used by ELECTRIC will be hosted by MolSSI at https://github.com/MolSSI-MDI/Tinker/commits/mdi-ef as part of the MolSSI MDI project. These are the Tinker changes that are part of this work. Further, we have added the MolSSI-MDI-enabled Tinker as a submodule of ELECTRIC, as suggested in issue WelbornGroup/ELECTRIC#17. WelbornGroup/Tinker_ELECTRIC has been deleted to avoid confusion.

**Comment by richardjgowers** [comment]
@govarguz can you check the changes that the authors have made and update your review please?

**Comment by amandadumi** [comment]
I wanted to add to this thread that https://github.com/WelbornGroup/ELECTRIC/issues/25 reviews the code within the ELECTRIC project. I plan on going through the mdi-ef code this evening. The simplification of mdi-ef being hosted by MolSSI is great, easier for users to open issues that pertain to the MDI changes specifically and hopefully easier for this authors to maintain as they work toward integrating this tool into the main Tinker project.

**Comment by govarguz** [comment]
@richardjgowers, ELECTRIC is ready for publication at JOSS

**Comment by amandadumi** [comment]
The ELECTRIC project and the MDI-enabled Tinker look great. The authors have addressed any concerns and I agree that ELECTRIC is ready for publication at JOSS!

**Comment by valeriewelborn** [comment]
Thank you @amandadumi and @govarguz for reviewing our paper. @richardjgowers, is there anything else you need from us?

**Comment by richardjgowers** [comment]
I need to go over this one last time this weekend then probably it’ll get
published :) thanks for your work on this!

**Comment by richardjgowers** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02576/joss.02576/10.21105.joss.02576.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02576/joss.02576/10.21105.joss.02576.pdf) :page_facing_up: :point_left:

**Comment by richardjgowers** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1146/annurev-biophys-070317-033349 is OK
- 10.1021/ct4003702 is OK
- 10.1021/acs.jctc.8b00529 is OK
- 10.1021/acs.jctc.7b01169 is OK
- 10.1021/jacs.6b12265 is OK
- 10.1021/acscatal.7b03151 is OK
- 10.1038/s41929-018-0109-2 is OK
- 10.5281/zenodo.3659285 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by richardjgowers** [comment]
@valeriewelborn all looking good,  Can you please add a quick paragraph just describing the usage procedure to make the paper complete?  This can just be a condensed version of the detailed description you've provided in the repo README.

**Comment by valeriewelborn** [comment]
Thanks @richardjgowers. I've just added a brief description of the usage procedure in the paper.

**Comment by richardjgowers** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02576/joss.02576/10.21105.joss.02576.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02576/joss.02576/10.21105.joss.02576.pdf) :page_facing_up: :point_left:

**Comment by richardjgowers** [comment]
@valeriewelborn ok all good to go, one last final step from your part:

At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by valeriewelborn** [comment]
Thank you @richardjgowers. The version tag is v1.0 and the DOI of the archived version is 10.5281/zenodo.4116258

**Comment by richardjgowers** [comment]
@whedon set 10.5281/zenodo.4116258 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4116258" target="_blank">10.5281/zenodo.4116258</a> is the archive.

**Comment by richardjgowers** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1146/annurev-biophys-070317-033349 is OK
- 10.1021/ct4003702 is OK
- 10.1021/acs.jctc.8b00529 is OK
- 10.1021/acs.jctc.7b01169 is OK
- 10.1021/jacs.6b12265 is OK
- 10.1021/acscatal.7b03151 is OK
- 10.1038/s41929-018-0109-2 is OK
- 10.5281/zenodo.3659285 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1845

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1845, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hi @valeriewelborn, I am the EIC on duty doing some final checks before publishing your article. There are some minor issues in the paper, could you address these?

- [ ] Most of the citations appear after the period in their sentences—could you move the citation commands to include them in the sentences?
- [ ] Could you put commas after "i.e." throughout? I noticed particularly in the third and fourth paragraphs.
- [ ] Your article is missing an explicit [Statement of Need section](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), which we have begun requiring for all articles. Could you please add this? It doesn't need to be too long, and you can likely use/reorganize some of what is already in your article.

**Comment by valeriewelborn** [comment]
Done @kyleniemeyer. Thanks

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02576/joss.02576/10.21105.joss.02576.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02576/joss.02576/10.21105.joss.02576.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@valeriewelborn sorry, one more thing: the references in the first paragraph need a space between them and the preceding words.

**Comment by valeriewelborn** [comment]
@kyleniemeyer, done!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02576/joss.02576/10.21105.joss.02576.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02576/joss.02576/10.21105.joss.02576.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1321126475618201601) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1871
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02576](https://doi.org/10.21105/joss.02576)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @valeriewelborn on your article's publication in JOSS!

Many thanks to @amandadumi and @govarguz for reviewing this, and @richardjgowers for editing it.
