### ISSUE TITLE
[REVIEW]: Noisyopt

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#258]
**Submitting author:** @andim (<a href="http://orcid.org/0000-0002-6643-7622">Andreas Mayer</a>)
**Repository:** <a href="https://github.com/andim/noisyopt" target ="_blank">https://github.com/andim/noisyopt</a>
**Version:** v0.2
**Editor:** @arokem
**Reviewer:** @nirum
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.580120" target="_blank">10.5281/zenodo.580120</a>

## Status

[![status](http://joss.theoj.org/papers/4d17c8d6e2cfe6505ca5ccdace5e123b/status.svg)](http://joss.theoj.org/papers/4d17c8d6e2cfe6505ca5ccdace5e123b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4d17c8d6e2cfe6505ca5ccdace5e123b"><img src="http://joss.theoj.org/papers/4d17c8d6e2cfe6505ca5ccdace5e123b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4d17c8d6e2cfe6505ca5ccdace5e123b/status.svg)](http://joss.theoj.org/papers/4d17c8d6e2cfe6505ca5ccdace5e123b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/andim/noisyopt" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/andim/noisyopt">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2)?
- [x] **Authorship:** Has the submitting author (@andim) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by nirum** [comment]
The author(s) have addressed all of my comments and closed the issues, which are linked below.

https://github.com/andim/noisyopt/issues/4

**Comment by nirum** [comment]
@arfon @arokem what's the next step here? It looks like @andim has already created a DOI for the package:

[![DOI](https://zenodo.org/badge/54976198.svg)](https://zenodo.org/badge/latestdoi/54976198)

**Comment by andim** [comment]
Just wanted to ping you again @arfon @arokem ! Let me know if any action is needed from my side at this point.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.580120 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.580120" target="_blank">10.5281/zenodo.580120</a> is the archive.

**Comment by arfon** [comment]
@nirum - many thanks for your review here and to @arokem for editing this one ✨ 

@andim - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00258 ⚡️:rocket: :boom:
