### ISSUE TITLE
[REVIEW]: emba: R package for analysis and visualization of biomarkers in boolean model ensembles

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2583]
**Submitting author:** @bblodfon (<a href="http://orcid.org/0000-0002-3609-8674">John Zobolas</a>)
**Repository:** <a href="https://github.com/bblodfon/emba" target ="_blank">https://github.com/bblodfon/emba</a>
**Version:** v0.1.7
**Editor:** @mikldk
**Reviewers:** @neerajdhanraj, @edifice1989
**Archive:** <a href="https://doi.org/10.5281/zenodo.4043085" target="_blank">10.5281/zenodo.4043085</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6f5ac7514e3bdeb27a3c137878b10fc5/status.svg)](https://joss.theoj.org/papers/6f5ac7514e3bdeb27a3c137878b10fc5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6f5ac7514e3bdeb27a3c137878b10fc5"><img src="https://joss.theoj.org/papers/6f5ac7514e3bdeb27a3c137878b10fc5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6f5ac7514e3bdeb27a3c137878b10fc5/status.svg)](https://joss.theoj.org/papers/6f5ac7514e3bdeb27a3c137878b10fc5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bblodfon/emba" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@neerajdhanraj & @edifice1989, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mikldk know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bblodfon/emba">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@bblodfon) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bblodfon/emba">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@bblodfon) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sahilseth, @edifice1989 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by mikldk** [comment]
@sahilseth, @edifice1989: Thanks for agreeing to review. Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If possible create issues (and cross-reference) in the submission's repository to avoid too specific discussions in this review thread. 

If you have any questions or concerns please let me know.

**Comment by whedon** [comment]
PDF failed to compile for issue #2583 with the following error:

**Comment by bblodfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02583/joss.02583/10.21105.joss.02583.pdf)

**Comment by mikldk** [comment]
@whedon add reviewer @edifice1989

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by mikldk** [comment]
@whedon add @edifice1989 as reviewer

**Comment by whedon** [comment]
OK, @edifice1989 is now a reviewer

**Comment by mikldk** [comment]
@edifice1989 Are you now able to edit your checklist?

**Comment by edifice1989** [comment]
yes, problem solved!

Thank you very much!

Ming

**Comment by edifice1989** [comment]
There is an issue when loading the 'emba' package. I opened a separate issue in  submission's [repository ](https://github.com/bblodfon/emba/issues/2#issue-687461142) please resolve it

**Comment by bblodfon** [comment]
Issue bblodfon/emba#2 is now resolved. Please use the development version of the package if you stumble upon this issue (install with `remotes::install_github("bblodfon/emba")`) and after the reviews are over I will have the newer version (`0.1.7`) with all relevant changes uploaded to CRAN.

**Comment by mikldk** [comment]
@sahilseth, @edifice1989: What is the status of your reviews? This is not to rush you, merely to give me an impression of the progress and time-frame.

**Comment by edifice1989** [comment]
@mikldk I have finished the review checklist, anything else I need to do?

**Comment by mikldk** [comment]
Thanks, @edifice1989. No, that's good for now. I just need to hear from @sahilseth.

**Comment by mikldk** [comment]
I have sent @sahilseth an email asking for status.

**Comment by bblodfon** [comment]
Hi @mikldk, any update from the reviewer?

**Comment by mikldk** [comment]
@Athanasiamo, @neerajdhanraj: Would one of you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by neerajdhanraj** [comment]
I would like to review it for JoSS.

Regards,

Neeraj

**Comment by mikldk** [comment]
@whedon remove @sahilseth as reviewer

**Comment by whedon** [comment]
OK, @sahilseth is no longer a reviewer

**Comment by mikldk** [comment]
@whedon add @neerajdhanraj as reviewer

**Comment by whedon** [comment]
OK, @neerajdhanraj is now a reviewer

**Comment by mikldk** [comment]
Thanks, @neerajdhanraj. I have changed the checklist etc. above to you. I hope you are able to use it now?

**Comment by neerajdhanraj** [comment]
Thank you so much. But, sorry to say, I am unable to find the manuscript related to the package. This is my first time to review this journal and on GitHub. Can you please let me know where I can see the manuscript?

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02583/joss.02583/10.21105.joss.02583.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02583/joss.02583/10.21105.joss.02583.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
There it is, @neerajdhanraj ^

**Comment by neerajdhanraj** [comment]
Dear @mikldk , 

I provided my reviews to this paper by ticking the respective boxes. Is it the completion of the review process from my side? Or is there any other procedure to proceed? 

Thank you.

**Comment by mikldk** [comment]
@neerajdhanraj No, that is it. Thank you.

**Comment by mikldk** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fgene.2016.00094 is OK
- 10.1038/ncb1497 is OK
- 10.1038/nbt.2284 is OK
- 10.1186/s12859-016-1287-z is OK
- 10.1158/0008-5472.CAN-17-0078 is OK
- 10.1371/journal.pcbi.1004426 is OK
- 10.1016/J.CELS.2018.10.013 is OK
- 10.1186/1752-0509-6-96 is OK
- 10.1093/bioinformatics/btw682 is OK
- 10.1038/nmeth.2016 is OK
- 10.1021/bi902202q is OK
- 10.1093/bioinformatics/btq124 is OK
- 10.3389/fphys.2018.01605 is OK
- 10.3389/fphys.2018.00646 is OK
- 10.3389/fphys.2018.00680 is OK
- 10.1093/bioinformatics/btv013 is OK
- 10.1007/978-3-319-67471-1_20 is OK
- 10.1016/j.molmed.2017.08.003 is OK
- 10.1093/bioinformatics/btx123 is OK
- 10.1186/1752-0509-6-133 is OK
- 10.1002/psp4.12225 is OK
- 10.1088/1478-3975/9/5/055001 is OK
- 10.1186/s12864-019-6413-7 is OK
- 10.1093/bioinformatics/btaa561 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mikldk** [comment]
@edifice1989, @neerajdhanraj:  Can you confirm that you have finished the review and recommend that this paper is now published?

@bblodfon :

* Please have a final read though of the paper, checking language etc.
* Have a final check of the proofs with `@whedon generate pdf`
* Please make a tagged release and archive (e.g. with [Zenodo](https://zenodo.org/)) as described [here](<https://joss.readthedocs.io/en/latest/submitting.html#the-review-process>), and report the version number and archive DOI in this thread. Please verify that the archive deposit has the correct metadata (title and author list), or edit these if that is not the case.

**Comment by edifice1989** [comment]
Yes. I confirm! I recommend that this paper is now published.

Best,
Ming

**Comment by neerajdhanraj** [comment]
Yes, it is confirmed from my side. I would like to recommend it for publication.

**Comment by bblodfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02583/joss.02583/10.21105.joss.02583.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02583/joss.02583/10.21105.joss.02583.pdf) :page_facing_up: :point_left:

**Comment by bblodfon** [comment]
Hi @mikldk,

- I read the paper one final time and made sure everything is proper
- I see that one of the reviewers is **mentioned twice** in the generated paper (as is here in the first post, I guess they are connected)
- Archived version number for the package is `v0.1.7` (see [respective release](https://github.com/bblodfon/emba/releases/tag/v0.1.7))
- Archived Zenodo DOI is `10.5281/zenodo.4043085` => [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4043085.svg)](https://doi.org/10.5281/zenodo.4043085)
- I made all appropriate edits in the Zenodo archived record

@edifice1989, @neerajdhanraj Thanks so much for reviewing my package!

**Comment by mikldk** [comment]
@whedon set 10.5281/zenodo.4043085 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4043085" target="_blank">10.5281/zenodo.4043085</a> is the archive.

**Comment by mikldk** [comment]
@whedon set v0.1.7 as version

**Comment by whedon** [comment]
OK. v0.1.7 is the version.

**Comment by mikldk** [comment]
@arfon Can you help with removing the double mention of @edifice1989 as reviewer? I am not sure how to handle that properly?

**Comment by arfon** [comment]
@whedon remove @edifice1989 as reviewer

**Comment by whedon** [comment]
OK, @edifice1989 is no longer a reviewer

**Comment by arfon** [comment]
@whedon add @edifice1989 as reviewer

**Comment by whedon** [comment]
OK, @edifice1989 is now a reviewer

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02583/joss.02583/10.21105.joss.02583.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02583/joss.02583/10.21105.joss.02583.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
OK, this looks fixed now in the PDF proofs?

**Comment by mikldk** [comment]
Thanks, @arfon . I was worried removing the reviewer would cause trouble. Cheers.

**Comment by mikldk** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fgene.2016.00094 is OK
- 10.1038/ncb1497 is OK
- 10.1038/nbt.2284 is OK
- 10.1186/s12859-016-1287-z is OK
- 10.1158/0008-5472.CAN-17-0078 is OK
- 10.1371/journal.pcbi.1004426 is OK
- 10.1016/J.CELS.2018.10.013 is OK
- 10.1186/1752-0509-6-96 is OK
- 10.1093/bioinformatics/btw682 is OK
- 10.1038/nmeth.2016 is OK
- 10.1021/bi902202q is OK
- 10.1093/bioinformatics/btq124 is OK
- 10.3389/fphys.2018.01605 is OK
- 10.3389/fphys.2018.00646 is OK
- 10.3389/fphys.2018.00680 is OK
- 10.1093/bioinformatics/btv013 is OK
- 10.1007/978-3-319-67471-1_20 is OK
- 10.1016/j.molmed.2017.08.003 is OK
- 10.1093/bioinformatics/btx123 is OK
- 10.1186/1752-0509-6-133 is OK
- 10.1002/psp4.12225 is OK
- 10.1088/1478-3975/9/5/055001 is OK
- 10.1186/s12864-019-6413-7 is OK
- 10.1093/bioinformatics/btaa561 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mikldk** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fgene.2016.00094 is OK
- 10.1038/ncb1497 is OK
- 10.1038/nbt.2284 is OK
- 10.1186/s12859-016-1287-z is OK
- 10.1158/0008-5472.CAN-17-0078 is OK
- 10.1371/journal.pcbi.1004426 is OK
- 10.1016/J.CELS.2018.10.013 is OK
- 10.1186/1752-0509-6-96 is OK
- 10.1093/bioinformatics/btw682 is OK
- 10.1038/nmeth.2016 is OK
- 10.1021/bi902202q is OK
- 10.1093/bioinformatics/btq124 is OK
- 10.3389/fphys.2018.01605 is OK
- 10.3389/fphys.2018.00646 is OK
- 10.3389/fphys.2018.00680 is OK
- 10.1093/bioinformatics/btv013 is OK
- 10.1007/978-3-319-67471-1_20 is OK
- 10.1016/j.molmed.2017.08.003 is OK
- 10.1093/bioinformatics/btx123 is OK
- 10.1186/1752-0509-6-133 is OK
- 10.1002/psp4.12225 is OK
- 10.1088/1478-3975/9/5/055001 is OK
- 10.1186/s12864-019-6413-7 is OK
- 10.1093/bioinformatics/btaa561 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1755

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1755, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by mikldk** [comment]
@neerajdhanraj, @edifice1989 Thank you very much for your effort in reviewing this paper!

**Comment by arfon** [comment]
@bblodfon - could you please merge this small PR before we accept the paper: https://github.com/bblodfon/emba/pull/3 ? This just tweaks the formatting of a couple of references for improved readability.

**Comment by mikldk** [comment]
Thanks for catching these, @arfon.

**Comment by bblodfon** [comment]
Hi @arfon, thanks for reading proof-reading my paper! I merged the PR. Though I think the **previous version** on the following sentence is better suited:
...suggest new therapeutic combination candidates, among others (Flobak at al. 2015). (**previous**)
...suggest new therapeutic combination candidates, among others Flobak et al. (2015). (**after the PR**) The way its written now allows for a more flexible interpretation I think, which is not what I intended. Is it ok with you to change it back to the previous version? What do you think @mikldk?

**Comment by arfon** [comment]
> The way its written now allows for a more flexible interpretation I think, which is not what I intended. Is it ok with you to change it back to the previous version?

That's fine. I think I mis-interpreted the logical flow of the sentence. Feel free to revert!

**Comment by bblodfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02583/joss.02583/10.21105.joss.02583.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02583/joss.02583/10.21105.joss.02583.pdf) :page_facing_up: :point_left:

**Comment by bblodfon** [comment]
Ok, everything seems in order now!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fgene.2016.00094 is OK
- 10.1038/ncb1497 is OK
- 10.1038/nbt.2284 is OK
- 10.1186/s12859-016-1287-z is OK
- 10.1158/0008-5472.CAN-17-0078 is OK
- 10.1371/journal.pcbi.1004426 is OK
- 10.1016/J.CELS.2018.10.013 is OK
- 10.1186/1752-0509-6-96 is OK
- 10.1093/bioinformatics/btw682 is OK
- 10.1038/nmeth.2016 is OK
- 10.1021/bi902202q is OK
- 10.1093/bioinformatics/btq124 is OK
- 10.3389/fphys.2018.01605 is OK
- 10.3389/fphys.2018.00646 is OK
- 10.3389/fphys.2018.00680 is OK
- 10.1093/bioinformatics/btv013 is OK
- 10.1007/978-3-319-67471-1_20 is OK
- 10.1016/j.molmed.2017.08.003 is OK
- 10.1093/bioinformatics/btx123 is OK
- 10.1186/1752-0509-6-133 is OK
- 10.1002/psp4.12225 is OK
- 10.1088/1478-3975/9/5/055001 is OK
- 10.1186/s12864-019-6413-7 is OK
- 10.1093/bioinformatics/btaa561 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1759

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1759, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1309830339351719936) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1760
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02583](https://doi.org/10.21105/joss.02583)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@neerajdhanraj, @edifice1989 - many thanks for your reviews here and to @mikldk for editing this submission ✨ 

@bblodfon - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02583/status.svg)](https://doi.org/10.21105/joss.02583)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02583">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02583/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02583/status.svg
   :target: https://doi.org/10.21105/joss.02583
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02583/status.svg)](https://doi.org/10.21105/joss.02583)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
