### ISSUE TITLE
[PRE REVIEW]: NO-DOUBT: A Decision Support Web Platformbased on AHP

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2586]
**Submitting author:** @gdede-hua (<a href="http://orcid.org/0000-0003-2947-7470">Georgia Dede</a>)
**Repository:** <a href="https://github.com/gdede-hua/decision-survey-platform" target ="_blank">https://github.com/gdede-hua/decision-survey-platform</a>
**Version:** v1.0
**Editor:** @sbenthall
**Reviewers:** @remram44, @alexssandrofc
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gdede-hua. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @sbenthall.

@gdede-hua if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.88 s (149.9 files/s, 58815.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
PHP                            264          12935          35731          56957
SQL                              1             67            102           1853
CSS                              5            259             47           1259
Markdown                         3            127              0            350
HTML                             1             42              1            316
JavaScript                       7             41            194            199
TeX                              1             42              0            161
-------------------------------------------------------------------------------
SUM:                           282          13513          36075          61095
-------------------------------------------------------------------------------


Statistical information for the repository '2586' was gathered on 2020/08/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dimitrios Alexandrak             1           434              0           17.67
gdede-hua                        1          2022              0           82.33

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dimitrios Alexandrak        434          100.0          0.0               44.70
gdede-hua                  2022          100.0          0.0               10.68
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02586/joss.02586/10.21105.joss.02586.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1007/s11066-010-9051-4 may be missing for title: Evaluation of technological and socio-economic issues affecting the deployment of home networks: Evidence from the ICT-OMEGA project
- https://doi.org/10.1016/s0377-2217(02)00227-8 may be missing for title: Decision-making with the AHP: Why is the principal eigenvector necessary
- https://doi.org/10.1016/j.dss.2005.11.005 may be missing for title: Investigating the effect of website quality on e-business success: An analytic hierarchy process (AHP) approach
- https://doi.org/10.1108/14635770610709031 may be missing for title: An AHP approach in benchmarking logistics performance of the postal industry
- https://doi.org/10.1016/j.ejor.2007.05.001 may be missing for title: The analytic hierarchy process in medical and health care decision making: A literature review
- https://doi.org/10.1016/j.ejor.2014.08.037 may be missing for title: Convergence properties and practical estimation of the probability of rank reversal in pairwise comparisons for multi-criteria decision making problems
- https://doi.org/10.1016/j.ejor.2016.01.059 may be missing for title: Theoretical estimation of the probability of weight rank reversal in pairwise comparisons

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by alexssandrofc** [comment]
Hi @sbenthall, I'm also available for the review, thanks!

**Comment by sbenthall** [comment]
@whedon assign @remram44 as reviewer

**Comment by whedon** [comment]
OK, @remram44 is now a reviewer

**Comment by sbenthall** [comment]
@whedon add @alexssandrofc as reviewer

**Comment by whedon** [comment]
OK, @alexssandrofc is now a reviewer

**Comment by sbenthall** [comment]
Thanks to both of you!

**Comment by sbenthall** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2605.
