### ISSUE TITLE
[PRE REVIEW]: PINE: An open source collaborative text annotation tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2587]
**Submitting author:** @brantapl (<a href="http://orcid.org/0000-0002-6174-4201">Brant Chee</a>)
**Repository:** <a href="https://github.com/jhuapl/PINE" target ="_blank">https://github.com/jhuapl/PINE</a>
**Version:** v1.0
**Editor:** @majensen
**Reviewers:** @bill-baumgartner, @bensonml
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @brantapl. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kakiac.

@brantapl if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2587 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.08 s (505.9 files/s, 103171.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           112           2739            263          30508
JSON                            20              0              0          15380
TeX                             10           3580            792          11272
JavaScript                      21           2452           2464          10236
Python                          70           1632           2247           6872
TypeScript                     133           1393            295           6520
CSS                             34            402             86           1656
YAML                            22             59             80           1320
Bourne Shell                    35            179             45            610
reStructuredText                66           3451           2814            394
Markdown                         8            139              0            330
Dockerfile                       7             99             43            250
Jupyter Notebook                 1              0            404             82
SVG                              1              0              0             59
make                             2             22             12             50
Mustache                         2             13              0             45
DOS Batch                        1              9              1             21
Sass                             1              6              0             13
-------------------------------------------------------------------------------
SUM:                           546          16175           9546          85618
-------------------------------------------------------------------------------


Statistical information for the repository '2587' was gathered on 2020/08/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Brant Chee                       1           862              0           21.27
Laura Glendenning                1          3099             78           78.39
brantapl                         5             9              5            0.35

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Brant Chee                 7925          919.4          0.0               13.15
Laura Glendenning         32170         1038.1          0.0               16.36
brantapl                      9          100.0          1.1              100.00
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02587/joss.02587/10.21105.joss.02587.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @kakiac! Are you up for editing another submission? You look like a good fit for this one!

**Comment by kthyng** [comment]
@whedon invite @kakiac as editor

**Comment by whedon** [comment]
@kakiac has been invited to edit this submission.

**Comment by majensen** [comment]
@kthyng I would be happy to edit if @kakiac is unable-

**Comment by danielskatz** [comment]
@majensen - done, thanks!

**Comment by danielskatz** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
@wdduncan - would you have time and interest to review [this work](#2587) for [JOSS](https://joss.theoj.org)? Consideration is much appreciated!

**Comment by majensen** [comment]
@yongqunh - this is @majensen, we have worked in the KPMP consortium together.
As a Topic Editor for [JOSS](https://joss.theoj.org), I am wondering - would you be willing to perform a software review on [this work](#2587) for the journal?
An overview of the review process is [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Please let me know here in this thread, or feel free to reach out to me at maj \-dot\- fortinbras \-at\- gmail \-dot\- com. 
Thanks for considering!

**Comment by wdduncan** [comment]
> @wdduncan - would you have time and interest to review [this work](#2587) for [JOSS](https://joss.theoj.org)? Consideration is much appreciated!

@majensen Sorry, I'm going to have to pass on this one. I have too many other reviews in the queue :(

**Comment by majensen** [comment]
No prob @wdduncan - thanks for reaponding

**Comment by majensen** [comment]
Hey @tvalerius - I'm a topic editor for the online [Journal of Open Source Software](https://joss.theoj.org), and I was thinking that [this work](#2587) would be right up your alley. Would you be willing to contribute your expertise on a review? 
All reviews are open and performed online here in GitHub. [Here is an overview of the process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). Please respond in this thread, or feel free to reach out to me at _maj \-dot\- fortinbras \-at\- gmail \-dot\- com_, or my NIH address.  

Really appreciate your consideration -- @majensen

**Comment by majensen** [comment]
@rvosa -- long time! I'm an editor now for the online journal [JOSS](https://joss.theoj.org). Would you be willing to review [this work](#2587)? All reviews are open and performed online here in GitHub. [Here is an overview](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) of the process. Please respond in this thread, or feel free to reach out to me at maj -dot- fortinbras -at- gmail -dot- com. I really appreciate your consideration --@majensen

**Comment by majensen** [comment]
@balhoff - can I trouble you again to consider a [JOSS](https://joss.theoj.org) review of [this work](#2487)? All my other ontology experts seem to be working hard on their ontologies and I haven't got a bite.... Appreciate your consideration! @majensen

**Comment by rvosa** [comment]
> @rvosa -- long time! I'm an editor now for the online journal [JOSS](https://joss.theoj.org). Would you be willing to review [this work](#2587)? All reviews are open and performed online here in GitHub. [Here is an overview](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) of the process. Please respond in this thread, or feel free to reach out to me at maj -dot- fortinbras -at- gmail -dot- com. I really appreciate your consideration --@majensen

Hi @majensen! Nice to hear from you. I'm sorry but I'll have to decline. Things are a bit hectic right now and this project also seems a bit outside of my expertise. Best, Rutger

**Comment by majensen** [comment]
Thanks for your consideration and quick response @rvosa - nice to hear a ping from you in any case!

**Comment by majensen** [comment]
Hey @sap218 -- would you have time and inclination to review [this work](#2587) for [JOSS](https://joss.theoj.org)? Would love to have your expertise on this. 
Thanks! --@majensen

**Comment by sap218** [comment]
@majensen Hi! Thank you for the invitation :-) I've had a look and I don't understand docker/sys admin enough to do a thorough review - really sorry. Best, Samantha.

**Comment by majensen** [comment]
@brantapl can you please provide me some suggestions for possible reviewers? Thanks.

**Comment by brantapl** [comment]
@majensen Thanks for all the help. Do you mean JOSS reviewers or outside of the community? Are their any requirements for reviewers?

**Comment by majensen** [comment]
@brantapl can be anyone who has some expertise in the field and is willing to do the software testing. Outside the JOSS community is fine, then we can being them in!

**Comment by balhoff** [comment]
@majensen sorry, I have to echo Rutger and Bill. :-( But I will email you some suggestions.

**Comment by majensen** [comment]
@callahantiff, @balhoff suggested that you would be a good reviewer for [JOSS](https://joss.theoj.org) on [this work](#2587). Would you be willing to provide your expertise? [Here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) is an overview of the reviewing process. 
Thanks for your consideration --@majensen

**Comment by callahantiff** [comment]
> @callahantiff, @balhoff suggested that you would be a good reviewer for [JOSS](https://joss.theoj.org) on [this work](#2587). Would you be willing to provide your expertise? [Here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) is an overview of the reviewing process.
> Thanks for your consideration --@majensen

Hi @majensen - Thanks for the invitation to review (thanks for recommending me @balhoff). I feel horrible to decline given that it looks like it's been hard to find reviewers, but I am also currently slammed (have 5 reviews due this week) ☹️ 

I do have a few other people in mind that I think would be very qualified to review this work: @bill-baumgartner, @jmbanda, @mboguslav, @KevinBretonnelCohen, or @jdkim.

Thank you again for the invitation, please keep me in mind for future papers!

**Comment by majensen** [comment]
Thanks @callahantiff for your response and suggestions! Any of those mentioned, can you ping back on this thread if you are willing to review?

**Comment by bill-baumgartner** [comment]
Hi @majensen - I'm willing to review this work. Please let me know next steps at your convenience. Thanks - Bill

**Comment by majensen** [comment]
@bill-baumgartner thanks very much! I will add you as a reviewer now (via our @whedon bot). Once I get a second vic...volunteer, then we will be able to start the review. That will come up as a new GitHub issue. I will shepherd everyone duly.

**Comment by majensen** [comment]
@whedon assign @bill-baumgartner as reviewer

**Comment by whedon** [comment]
OK, @bill-baumgartner is now a reviewer

**Comment by majensen** [comment]
Thanks to my colleague @bensonml who happens to be a NLP expert and a great programmer, we can do this thing!

**Comment by majensen** [comment]
@whedon add @bensonml as reviewer

**Comment by whedon** [comment]
OK, @bensonml is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2726.

**Comment by majensen** [comment]
All, the review has begun in #2726 - please join the conversation there. Thanks
