### ISSUE TITLE
[PRE REVIEW]: pyFBS: A Python package for Frequency Based Substructuring

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2588]
**Submitting author:** @tb93 (<a href="http://orcid.org/0000-0002-5587-5619">Tomaž Bregar</a>)
**Repository:** <a href="https://gitlab.com/pyFBS/pyFBS" target ="_blank">https://gitlab.com/pyFBS/pyFBS</a>
**Version:** 0.1.1
**Editor:** @kyleniemeyer
**Reviewers:** @ngoiz, @LolloCappo, @Gunnstein
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tb93. **Currently, there isn't an JOSS editor assigned** to your paper.

@tb93 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2588 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=2.09 s (35.3 files/s, 260214.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                21              0         536826           1980
Python                          14            820           1136           1683
reStructuredText                31            719            750            512
TeX                              1             14              0            112
Markdown                         1             20              0             80
HTML                             1              5              0             28
DOS Batch                        1              8              1             27
YAML                             2              9             17             25
CSS                              1              4              4             13
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                            74           1603         538740           4470
-------------------------------------------------------------------------------


Statistical information for the repository '2588' was gathered on 2020/08/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Locke-D-A                        3         10921          10287           23.56
Miha Kodrič                      3          1044           1044            2.32
Tomaž Bregar                    85         33669          32073           73.03
mihakodric                      12           495            412            1.01
tb93                             2            59             21            0.09

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Locke-D-A                     2            0.0          1.9                0.00
Tomaž Bregar               3448           10.2          3.1               13.98
mihakodric                  189           38.2          2.2                1.59
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev whedon cannot find the paper, which is here: https://gitlab.com/pyFBS/pyFBS/-/tree/master/joss, is this because they should move it out of that `joss` folder?

**Comment by tomazbregar** [comment]
I tested the paper compilation with [https://whedon.theoj.org/](url) and the PDF in fact compiles successfully ( 
[od30rut28esfdu4jhjeg.pdf](https://github.com/openjournals/joss-reviews/files/5107809/od30rut28esfdu4jhjeg.pdf)).

**Comment by tomazbregar** [comment]
@arfon - sorry for the large repository size, I forgot to clean the old datasets. The new updated repository contains only relevant data and its much smaller (< 100 Mb).

@labarba - I rewrote the Summary and added a section *Statement of need* to the paper (branch name *joss_paper*). Regarding the state of the field, as pointed out in the paper, there is currently no opensource package to support the use of dynamic substructuring methodologies. For the 3D display part, it is supported by numerous opensource packages but the specific routines needed in DS are not supported.

**Comment by arfon** [comment]
> @arfon - sorry for the large repository size, I forgot to clean the old datasets. The new updated repository contains only relevant data and its much smaller (< 100 Mb).

:+1: great!

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02588/joss.02588/10.21105.joss.02588.pdf)

**Comment by danielskatz** [comment]
In the statement of need section, I see a "dnamic" that should be "dynamic".  Also, can you add a little about of the kind of problems that can be solved with this software, and the kinds of researchers who need to solve them, remembering that the editors/reviewers/readers are a very diverse group in terms of their disciplinary expertise.

**Comment by danielskatz** [comment]
👋 @kyleniemeyer - would you be willing to take this as the editor?

**Comment by danielskatz** [comment]
@whedon invite @kyleniemeyer as editor

**Comment by whedon** [comment]
@kyleniemeyer has been invited to edit this submission.

**Comment by danielskatz** [comment]
👋 @bstabler - would you be able to edit this submission?  @kyleniemeyer thinks you are a better fit than him, but if not, he will edit it

**Comment by danielskatz** [comment]
@whedon invite @bstabler as editor

**Comment by whedon** [comment]
@bstabler has been invited to edit this submission.

**Comment by tomazbregar** [comment]
@danielskatz - Sorry for the grammatical error, I only had it corrected on the branch *joss_paper*, I have now moved the up-to-date version to *master* branch.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02588/joss.02588/10.21105.joss.02588.pdf)

**Comment by danielskatz** [comment]
@tomazbregar  - the paper still does not say what specific types of problems it can solve, as I wrote previously
> Also, can you add a little about of the kind of problems that can be solved with this software, and the kinds of researchers who need to solve them, remembering that the editors/reviewers/readers are a very diverse group in terms of their disciplinary expertise.

**Comment by tomazbregar** [comment]
@danielskatz -  My mistake, I forgot to include the explanation. The paper now contains a paragraph which briefly explains in which field the software is intended to be used (in *Statement of need* section).

**Comment by tomazbregar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02588/joss.02588/10.21105.joss.02588.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02588/joss.02588/10.21105.joss.02588.pdf) :page_facing_up: :point_left:

**Comment by bstabler** [comment]
@danielskatz - I just read the paper and I don't think it's a good fit for my expertise. 

@tomazbregar - I noticed a typo in the paper - "opensource" needs a space.

**Comment by tomazbregar** [comment]
@bstabler - Thank you for spotting the typo, I have corrected it in the paper.

**Comment by danielskatz** [comment]
Thanks - The currently on-duty AEiC will take over on the editor assignment

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hi @tomazbregar, I will now be starting to find reviewers for your submission. Do you have any reviewer suggestions?

**Comment by tomazbregar** [comment]
Hey @kyleniemeyer, unfortunately I don't know who would be the best fit for reviewer. If it helps, the person should have a background in structural dynamics.

**Comment by tomazbregar** [comment]
Dear @kyleniemeyer, perhaps potential reviewers could be ngoiz (norberto.goizueta13@imperial.ac.uk) and chennachaos (c.kadapa@swansea.ac.uk).

**Comment by arfon** [comment]
:wave: @kyleniemeyer - it looks like this submission is still waiting on you to identify reviewers?

**Comment by kyleniemeyer** [comment]
Hello @ngoiz and @chennachaos, would you be available to review this submission for JOSS, the Journal of Open Source Software?

**Comment by ngoiz** [comment]
Hi @kyleniemeyer, happy to help out and review this for JOSS!

**Comment by kyleniemeyer** [comment]
@whedon add @ngoiz as reviewer

**Comment by whedon** [comment]
OK, @ngoiz is now a reviewer

**Comment by chennachaos** [comment]
Hi @kyleniemeyer. Thank you for the invitation!
Although I work on the Finite Element Method, the application area covered in this library is outside the scope of my expertise. So, I don't think I am adequately qualified to review this submission.

**Comment by kyleniemeyer** [comment]
@chennachaos Understood, thanks!

**Comment by ahmedmahmoudi** [comment]
Dear @kyleniemeyer,
I went through the list and perhaps potential reviewers could be moorepants and jmbr (jmbr@superadditive.com).

**Comment by kyleniemeyer** [comment]
Hello @jmbr, would you be able to review this submission to JOSS, "pyFBS: A Python package for Frequency Based Substructuring", described in the [paper](https://github.com/openjournals/joss-papers/blob/joss.02588/joss.02588/10.21105.joss.02588.pdf) ?

**Comment by jmbr** [comment]
@kyleniemeyer I believe that this is not close to my fields of expertise.

**Comment by kyleniemeyer** [comment]
Hi @moorepants, if this JOSS submission looks up your alley, could you review it for us?

**Comment by arfon** [comment]
:wave: @domengorjup @jankoslavic @klemengit – would any of you be willing to review this submission for JOSS? 
We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review is [_pyFBS: A Python package for Frequency Based Substructuring_](https://gitlab.com/pyFBS/pyFBS) and our request of you would be to review the software and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02588/joss.02588/10.21105.joss.02588.pdf).

**Comment by jankoslavic** [comment]
Dear @arfon! Thank you for the invitation. pyFBS is a great package as far as I know it. Due to prior commitment, I am currently not able to commit to this additional task.  I ask you for understanding.

**Comment by tomazbregar** [comment]
Dear Arfon, thank you for continuing the review of our package and paper. @domengorjup, @jankoslavic and @klemengit are our collegues at the University of Ljubljana; therefore, we would propose two new reviewers: @LolloCappo and @Gunnstein. If off course, they would be willing to review the paper.

**Comment by kyleniemeyer** [comment]
Thanks @tomazbregar. 

@LolloCappo and @Gunnstein, are you willing and able to review this submission for JOSS? If you are unfamiliar with our journal, you can read more about performing our checklist-driven reviews here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Thanks!

**Comment by LolloCappo** [comment]
Dear @kyleniemeyer,
I am available for reviewing the submission.

**Comment by kyleniemeyer** [comment]
@whedon add @LolloCappo as reviewer

Thanks!

**Comment by whedon** [comment]
OK, @LolloCappo is now a reviewer

**Comment by Gunnstein** [comment]
Dear @kyleniemeyer ,

I can also review this submission.

Best regards,
Gunnstein

**Comment by kyleniemeyer** [comment]
@whedon add @Gunnstein as reviewer

**Comment by whedon** [comment]
OK, @Gunnstein is now a reviewer

**Comment by kyleniemeyer** [comment]
@ngoiz, @LolloCappo, @Gunnstein thank you all for agreeing to review this! I will now initiate the review issue and close this one. @tb93, thank you for your patience.

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3399.
