### ISSUE TITLE
[PRE REVIEW]: rFBP: Replicated Focusing Belief Propagation algorithm

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2589]
**Submitting author:** @Nico-Curti (<a href="http://orcid.org/0000-0001-5802-1195">Nico Curti</a>)
**Repository:** <a href="https://github.com/Nico-Curti/rFBP" target ="_blank">https://github.com/Nico-Curti/rFBP</a>
**Version:** v1.0.0
**Editor:** @arokem
**Reviewers:** @bblais, @justusschock
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Nico-Curti. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arokem.

@Nico-Curti if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2589 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2589/paper/paper.md): did not find expected alphabetic or numeric character while scanning an alias at line 16 column 19 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-0e09ec0a48e3/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you help trouble shoot this error :point_up:

**Comment by arokem** [comment]
Hi @Nico-Curti and co-authors: thank you for this submission. I have now read the article and looked through the software. The next steps are for me to offer some comments on this initial submission and for us to find appropriate reviewers. 

First, my comments on the article: 

1. The readership of JOSS is expected to be very broad, so you will need to provide a bit more context for the software. For example, the first sentence of the article really drops the reader off the deep end, where more general context would have been helpful. 

2. Since an important element in a JOSS paper is the potential research applications of the software, it would be good to flesh out the examples that you provided as bullet points. How was the software used in these applications? What kinds of research questions were answered? In general, as I understand it, since this is a re-implementation of an existing algorithm, what is the need that is addressed through this implementation of the algorithm?

Second: do you have particular suggestions for people who would be appropriate reviewers for your paper? If you include their GitHub handles here, please *do not* use the "@" sign before their name, so that I can take a look before tagging them into this issue.

**Comment by arokem** [comment]
👋 @justusschock : would you be willing to review this article for JOSS? This submissions seems like a good match for your expertise.

**Comment by arokem** [comment]
:wave: @georgiastuart : would you be willing to review this article for JOSS? It seems like a good match for your expertise.

**Comment by justusschock** [comment]
@arokem Sure!

**Comment by arokem** [comment]
@whedon assign @justusschock as reviewer

**Comment by whedon** [comment]
OK, @justusschock is now a reviewer

**Comment by arokem** [comment]
Thanks! Let's wait until I find one more person, before starting the review.

**Comment by Nico-Curti** [comment]
@arokem Thanks for your comments. We will provide an updated version of the paper with your suggestions in few days.
As for the second reviewer we would like to suggest professor [Brian Blais](https://github.com/bblais) since he is an expert in the field and a very competent Python programmer.

**Comment by arokem** [comment]
Hi @bblais -- would you be willing to review this software contribution to [The Journal of Open Source Software](https://joss.theoj.org/)? The reviews are conducted openly, through a GitHub issue. More instructions are available [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

**Comment by arokem** [comment]
:wave: @DanielLenz : would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
:wave: @zbeekman : would you be willing to review this article for JOSS?

**Comment by bblais** [comment]
> Hi @bblais -- would you be willing to review this software contribution to [The Journal of Open Source Software](https://joss.theoj.org/)? The reviews are conducted openly, through a GitHub issue. More instructions are available [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

Sure, I can review (didn't notice this invite the first time).  I see the editorial guide, but is there a guide for the process of submitting a review?  is it by individual issues or all at once?  is there a deadline or expected timeframe for review?  thanks!

**Comment by arokem** [comment]
@whedon assign @bblais as reviewer

**Comment by whedon** [comment]
OK, @bblais is now a reviewer

**Comment by arokem** [comment]
@whedon add @justusschock as reviewer

**Comment by whedon** [comment]
OK, @justusschock is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2663.

**Comment by arokem** [comment]
@bblais , @justusschock : please head over to #2663. There you will have a checklist with items to check off. As you go along, feel free to comment and make suggestions in that review issue, or to post issues on the software repository (might want to mention that the issue stems from the JOSS review). And please do let me know if you have any further questions.

**Comment by arokem** [comment]
@daniellenz, @zbeekman : sorry for the false alarm. Looks like we will not your service as reviewers this time around
