### ISSUE TITLE
[REVIEW]: Neuropsydia.py: A Python Module for Creating Experiments, Tasks and Questionnaires

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#259]
**Submitting author:** @DominiqueMakowski (<a href="http://orcid.org/0000-0001-5375-9967">Dominique Makowski</a>)
**Repository:** <a href="https://github.com/neuropsychology/Neuropsydia.py/" target ="_blank">https://github.com/neuropsychology/Neuropsydia.py/</a>
**Version:** 1.0.4
**Editor:** @arokem
**Reviewer:** @cMadan
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1048777" target="_blank">10.5281/zenodo.1048777</a>

## Status

[![status](http://joss.theoj.org/papers/e39d331f658d0501382853ff46bc9776/status.svg)](http://joss.theoj.org/papers/e39d331f658d0501382853ff46bc9776)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e39d331f658d0501382853ff46bc9776"><img src="http://joss.theoj.org/papers/e39d331f658d0501382853ff46bc9776/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e39d331f658d0501382853ff46bc9776/status.svg)](http://joss.theoj.org/papers/e39d331f658d0501382853ff46bc9776)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/neuropsychology/Neuropsydia.py/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/neuropsychology/Neuropsydia.py/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.4)?
- [x] **Authorship:** Has the submitting author (@DominiqueMakowski) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @cMadan it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cMadan** [comment]
@DominiqueMakowski - I just did a quick first pass at going through the JOSS reviewer questions, but not yet testing the functionality of the software itself. There are a few things I noticed that need to be addressed, and I will continue and test the code itself within a few days.

Version - You list the software as being version 1.0.4 in the repo, but haven't minted a 'release' in Github to go with this. If someone wanted to specifically run version 1.0.4 in the future, this wouldn't be possible. Also, JOSS will later require you to archive the accepted version of the software in an archival repository (such as Zenodo or figshare), but that isn't necessary yet.

Documentation - the API documentation link in the README is listed as http://neuropsydia.readthedocs.io/en/master/documentation.html, but this appears to only be a skeleton document. In the paper, the link is http://neuropsydia.readthedocs.io/en/latest/documentation.html, which does have content. These should both be linked to the same complete document.

References - DOIs are currently missing.

**Comment by arokem** [comment]
@DominiqueMakowski : have you had a chance to address the comments that @cMadan made?

**Comment by DominiqueMakowski** [comment]
@arokem I plan to address them by the end of the week. Sorry for the delay!

**Comment by DominiqueMakowski** [comment]
Dear @arokem, sorry for the long answer, and thanks a ***lot*** to @cMadan for his first comments.

**Version - You list the software as being version 1.0.4 in the repo, but haven't minted a 'release' in Github to go with this. If someone wanted to specifically run version 1.0.4 in the future, this wouldn't be possible. Also, JOSS will later require you to archive the accepted version of the software in an archival repository (such as Zenodo or figshare), but that isn't necessary yet.**

That has been done. We created a 1.0.4 release on github.

**Documentation - the API documentation link in the README is listed as http://neuropsydia.readthedocs.io/en/master/documentation.html, but this appears to only be a skeleton document. In the paper, the link is http://neuropsydia.readthedocs.io/en/latest/documentation.html, which does have content. These should both be linked to the same complete document.**

We replaced the wrong links with the correct one.

**References - DOIs are currently missing.**

This has been modified [here](https://github.com/neuropsychology/Neuropsydia.py/blob/master/paper/paper.bib) accordingly.

Again, thanks a lot and sorry for the delay.

**Comment by arokem** [comment]
@cMadan : any more thoughts here?

**Comment by cMadan** [comment]
@arokem - Sorry, I was traveling/on vacation. I will get back to this within the next few days.

**Comment by cMadan** [comment]
I tried the first example (go/no-go) and got a blank screen and no helpful errors--will follow-up with issues in their repo.

**Comment by arokem** [comment]
Thanks - ping me here when things are resolved, with pointers to the relevant issues. Thanks again!

**Comment by arokem** [comment]
Any progress here? @DominiqueMakowski / @cMadan? Have the issues previously identified been resolved?

**Comment by cMadan** [comment]
For some reason I can't get it to work on my Mac laptop, though someone else was able to get it to work on their Mac. Since I tried this last, I've moved to another uni (and generally been busy)... I will try the package on a Windows machine next week.

**Comment by cMadan** [comment]
@arokem I was able to test the package fine on a Windows 10 PC and it worked great. Also, as mentioned last time another person has had it work on a Mac, so we can leave that debugging for another time. The package does what's supposed to do, is well documented, and the paper seems to be in order. I recommend the submission be accepted at JOSS.

@DominiqueMakowski, sorry for the delay in testing it further!

**Comment by arokem** [comment]
Great! @DominiqueMakowski :  could you please create an archive (e.g., on zenodo) of the final version of the software and share the DOI here?

**Comment by DominiqueMakowski** [comment]
@cMadan Thanks a lot for all your suggestions and comments. 

@arokem , the DOI is the following: 10.5281/zenodo.1048777

[![DOI](https://zenodo.org/badge/70266940.svg)](https://zenodo.org/badge/latestdoi/70266940)

Thank you for your work!

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.1048777 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1048777" target="_blank">10.5281/zenodo.1048777</a> is the archive.

**Comment by arokem** [comment]
@arfon : I believe this paper can now be published.

**Comment by DominiqueMakowski** [comment]
@arokem Should I do something more?

**Comment by arokem** [comment]
No. I believe this is in @arfon's hands for the final call.

**Comment by arfon** [comment]
@cMadan - many thanks for your review here and to @arokem for editing this one ✨ 

@DominiqueMakowski - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00259 ⚡️ 🚀 💥

**Comment by DominiqueMakowski** [comment]
@cMadan @arokem @arfon Many thanks to the reviewers and editors!
