### ISSUE TITLE
[PRE REVIEW]: astrosource: automating optical astronomy measurement, calibration and analysis for variable stellar sources from provided photometry

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2591]
**Submitting author:** @mfitzasp (<a href="http://orcid.org/0000-0001-6554-1826">Michael Fitzgerald</a>)
**Repository:** <a href="https://github.com/zemogle/astrosource/" target ="_blank">https://github.com/zemogle/astrosource/</a>
**Version:** v1.4.0
**Editor:** @arfon
**Reviewers:** @bsipocz, @joshspeagle
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mfitzasp. **Currently, there isn't an JOSS editor assigned** to your paper.

@mfitzasp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by zemogle** [comment]
Hey @arfon! Ideas for reviewers are @bsipocz and @rzellem

The DOIs should be fixed now 👍

**Comment by zemogle** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1080/21672857.2017.1303264 is OK
- 10.1017/pasa.2014.30 is OK
- 10.1002/asna.201512254 is OK
- 10.3847/1538-3881/153/2/77 is OK
- 10.1088/1538-3873/ab7ee7 is OK
- 10.1017/pasa.2018.5 is OK
- 10.1088/0067-0049/219/1/12 is OK
- 10.1117/12.2314340 is OK
- 10.1086/673168 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1109/mcse.2011.37 is OK
- 10.1109/mcse.2007.55 is OK
- 10.3847/1538-3881/aafc33 is OK
- 10.21105/joss.00058 is OK
- 10.1051/0004-6361:20020802 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.32374/atom.2020.1.2 is INVALID
- 10.32374/atom.2020.1.4 is INVALID
- 10.32374/atom.2020.1.1 is INVALID
```

**Comment by zemogle** [comment]
Hmmm. Those are the DOIs referenced in ATOM. It looks like they don't resolve correctly.

**Comment by arfon** [comment]
:wave: @bsipocz & @rzellem - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by arfon** [comment]
> Hmmm. Those are the DOIs referenced in ATOM. It looks like they don't resolve correctly.

Indeed. I've enquired here: https://twitter.com/arfon/status/1298252048861814784

**Comment by rzellem** [comment]
Normally I'd be happy to review submissions, @arfon, but I'm refereeing another 3 journals at the moment. I recommend you reach out to @pearsonkyle

**Comment by arfon** [comment]
👍 thanks for the quick response @rzellem! :wave: @pearsonkyle - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by mfitzasp** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1080/21672857.2017.1303264 is OK
- 10.1017/pasa.2014.30 is OK
- 10.1002/asna.201512254 is OK
- 10.3847/1538-3881/153/2/77 is OK
- 10.1088/1538-3873/ab7ee7 is OK
- 10.1017/pasa.2018.5 is OK
- 10.1088/0067-0049/219/1/12 is OK
- 10.32374/atom.2020.1.2 is OK
- 10.32374/atom.2020.1.4 is OK
- 10.1117/12.2314340 is OK
- 10.1086/673168 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1109/mcse.2011.37 is OK
- 10.1109/mcse.2007.55 is OK
- 10.3847/1538-3881/aafc33 is OK
- 10.21105/joss.00058 is OK
- 10.32374/atom.2020.1.1 is OK
- 10.1051/0004-6361:20020802 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by bsipocz** [comment]
@arfon - what is the expected timeline? I'm fully occupied this week and next with AstroHackWeek, but would be happy to start with the review afterwards.

**Comment by arfon** [comment]
> @arfon - what is the expected timeline? I'm fully occupied this week and next with AstroHackWeek, but would be happy to start with the review afterwards.

Ideally sometime in the next ~4 weeks?

**Comment by arfon** [comment]
@bsipocz - I'm going to take your 👍 to [my comment](https://github.com/openjournals/joss-reviews/issues/2591#issuecomment-680683904) above as consent to add you as a reviewer. Please let me know if this isn't correct!

**Comment by arfon** [comment]
@whedon add @bsipocz as reviewer

**Comment by whedon** [comment]
OK, @bsipocz is now a reviewer

**Comment by arfon** [comment]
:wave: @joshspeagle @catherinezucker - would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by joshspeagle** [comment]
I’d be happy to sign up as a reviewer.

**Comment by arfon** [comment]
@whedon add @joshspeagle as reviewer

**Comment by whedon** [comment]
OK, @joshspeagle is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2641.

**Comment by arfon** [comment]
@bsipocz, @joshspeagle - many thanks for agreeing to review this submission. See you over in #2641 where the review will take place.
