### ISSUE TITLE
[PRE REVIEW]: SeismicMesh: Triangular meshing for seismology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2592]
**Submitting author:** @krober10nd (<a href="http://orcid.org/0000-0002-8470-0359">Keith Roberts</a>)
**Repository:** <a href="https://github.com/krober10nd/SeismicMesh" target ="_blank">https://github.com/krober10nd/SeismicMesh</a>
**Version:** v1.2
**Editor:** @meg-simula
**Reviewers:** @nschloe, @jorgensd
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @krober10nd. **Currently, there isn't an JOSS editor assigned** to your paper.

@krober10nd if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by meg-simula** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02592/joss.02592/10.21105.joss.02592.pdf)

**Comment by meg-simula** [comment]
@santisoler @nschloe would you be available to review this submission for JOSS? Please take a look at our reviewer guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html, and let us know. Your help would be much appreciated.

**Comment by meg-simula** [comment]
@whedon assign @nschloe as reviewer

**Comment by whedon** [comment]
OK, @nschloe is now a reviewer

**Comment by meg-simula** [comment]
@jorgensd would you be available to review this submission for JOSS? Please take a look at our reviewer guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html, and let us know. Your help would be much appreciated.

**Comment by jorgensd** [comment]
> @jorgensd would you be available to review this submission for JOSS? Please take a look at our reviewer guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html, and let us know. Your help would be much appreciated.

Im available.

**Comment by krober10nd** [comment]
hey @meg-simula Sorry to bother, but  has the review officially started yet?  Nico and I have been going back and forth for some time now.

**Comment by meg-simula** [comment]
@whedon add @jorgensd as reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2687.

**Comment by meg-simula** [comment]
@whedon add @jorgensd as reviewer

**Comment by whedon** [comment]
OK, @jorgensd is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by meg-simula** [comment]
@whedon start review

**Comment by meg-simula** [comment]
@arfon Could you have a look at this case? I asked whedon to add a reviewer, and then start the review, but the review was started before the second reviewer was added. I tried closing that review issue, and starting a new one with the two reviewers, but now it seems that whedon is not too keen to. Any advice?

**Comment by krober10nd** [comment]
Thanks @meg-simula  !

**Comment by krober10nd** [comment]
hey @arfon I realize you're probably incredibly busy, but I think this could be an easy fix to send this paper to the official review stage. Looks like there was just some buggy interaction with the whedon bot? I would appreciate your help here very much. Thanks1

**Comment by arfon** [comment]
> @arfon Could you have a look at this case? I asked whedon to add a reviewer, and then start the review, but the review was started before the second reviewer was added. I tried closing that review issue, and starting a new one with the two reviewers, but now it seems that whedon is not too keen to. Any advice?

There's no automated way to do this right now sorry. The 'fix' is to add the second reviewer on the actual review issue (#2687) and add a second checklist for them over there. I'll go ahead and do this for you now...
