### ISSUE TITLE
[PRE REVIEW]: biopeaks: a graphical user interface for feature extraction from heart- and breathing biosignals

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2593]
**Submitting author:** @JanCBrammer (<a href="http://orcid.org/0000-0002-7664-3753">Jan C. Brammer</a>)
**Repository:** <a href="https://github.com/JanCBrammer/biopeaks" target ="_blank">https://github.com/JanCBrammer/biopeaks</a>
**Version:** v1.4.0
**Editor:** @oliviaguest
**Reviewers:** @TomDonoghue, @sappelhoff, @jamesheathers
**Managing EiC:** Lorena A Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JanCBrammer. **Currently, there isn't an JOSS editor assigned** to your paper.

@JanCBrammer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by jni** [comment]
@labarba (👋!) sorry, unfortunately I don't have the bandwidth to take on one more paper right now... (But @JanCBrammer thanks for the reviewer suggestions! They will make the editor's job much easier!)

**Comment by JanCBrammer** [comment]
@jni, no worries, thanks for the quick response! @labarba, alternatively the following editors seem to fit the subject domain: oliviaguest, cMadan, arokem.

**Comment by labarba** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by labarba** [comment]
👋 @oliviaguest — can you take this extra submission to handle? I know you are already handling two others, but the other two suggested editors are listed in 'reduced mode' on our tracking. Tough times!

**Comment by oliviaguest** [comment]
I can do this, yes. 😄

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest  as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
@whedon add @TomDonoghue as reviewer

**Comment by whedon** [comment]
OK, @TomDonoghue is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @ sappelhoff as reviewer

**Comment by whedon** [comment]
OK, @ sappelhoff is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @sappelhoff as reviewer

**Comment by whedon** [comment]
OK, @sappelhoff is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @jamesheathers as reviewer

**Comment by whedon** [comment]
OK, @jamesheathers is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2621.

**Comment by oliviaguest** [comment]
Hi, @JanCBrammer, @TomDonoghue, @sappelhoff, @jamesheathers, please on over to #2621 to get the review started! 😊
