### ISSUE TITLE
[REVIEW]: textnets: A Python package for text analysis with networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2594]
**Submitting author:** @jboynyc (<a href="http://orcid.org/0000-0003-2118-4702">John Boy</a>)
**Repository:** <a href="https://github.com/jboynyc/textnets" target ="_blank">https://github.com/jboynyc/textnets</a>
**Version:** v0.4.10
**Editor:** @gkthiruvathukal
**Reviewer:** @sara-02, @tresoldi
**Archive:** <a href="https://doi.org/10.5281/zenodo.4028610" target="_blank">10.5281/zenodo.4028610</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/827fa29da12bd11fe1841f8135f5b840/status.svg)](https://joss.theoj.org/papers/827fa29da12bd11fe1841f8135f5b840)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/827fa29da12bd11fe1841f8135f5b840"><img src="https://joss.theoj.org/papers/827fa29da12bd11fe1841f8135f5b840/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/827fa29da12bd11fe1841f8135f5b840/status.svg)](https://joss.theoj.org/papers/827fa29da12bd11fe1841f8135f5b840)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jboynyc/textnets" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sara-02 & @tresoldi, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @gkthiruvathukal know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jboynyc/textnets">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jboynyc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jboynyc/textnets">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jboynyc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sara-02, @tresoldi it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2594 with the following error: 

 Can't find any papers to compile :-(

**Comment by jboynyc** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by tresoldi** [comment]
@jboynyc great library, thank you! I can see myself using it for at least one project I have in mind.

I've just filed an issue on the only real problem I saw. Some additional points/comments here:

- Given your audience, it might be valid to offer the library as a conda package as well
- I suggest putting

**Comment by jboynyc** [comment]
Thanks, @tresoldi! I will push a new version of the paper by the end of the week adding a more detailed statement of need to the background section and doing my best to fix figure placement. I'll let you know when I'm ready.

I also really like your idea of creating a Conda package. I've started looking into it.

**Comment by jboynyc** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02594/joss.02594/10.21105.joss.02594.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02594/joss.02594/10.21105.joss.02594.pdf) :page_facing_up: :point_left:

**Comment by tresoldi** [comment]
All my points were addressed, only issue https://github.com/jboynyc/textnets/issues/14 still pending.

**Comment by jboynyc** [comment]
Release [0.4.10](https://github.com/jboynyc/textnets/releases/tag/v0.4.10) closes jboynyc/textnets#14.

Many thanks @tresoldi for the helpful and encouraging review!

**Comment by tresoldi** [comment]
Great, @jboynyc , and thanks once more for this package.

@gkthiruvathukal No further requests from me, approved.

**Comment by jboynyc** [comment]
> Great, @jboynyc , and thanks once more for this package.

I'd love to hear about any projects you use it for, so please do ping me!

**Comment by jboynyc** [comment]
I made a minor update to the paper noting the ability to [install from conda-forge](https://anaconda.org/conda-forge/textnets).

@whedon generate pdf from branch joss

**Comment by jboynyc** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02594/joss.02594/10.21105.joss.02594.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02594/joss.02594/10.21105.joss.02594.pdf) :page_facing_up: :point_left:

**Comment by gkthiruvathukal** [comment]
@sara-02 and @tresoldi, it looks like we are mostly good to go on this submission. Can you let us know if there are any other issues and check all remaining boxes in your review checklist as appropriate?

Then we can move toward acceptance.

**Comment by tresoldi** [comment]
@gkthiruvathukal We can move towards acceptance, for me. All boxes checked. :smiley:

**Comment by sara-02** [comment]
@jboynyc I have a query regarding this point 
```
Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?
```
I could not find a command for the same, have added an issue here: https://github.com/jboynyc/textnets

Apart from this point, the rest of the checklist is complete from my side as well.

**Comment by sara-02** [comment]
The above query has been sorted.

**Comment by sara-02** [comment]
@gkthiruvathukal I have completed my checklist as well.
We are good to move forward.

**Comment by jboynyc** [comment]
Thanks for your careful review, @sara-02! :+1:

**Comment by gkthiruvathukal** [comment]
@tresoldi and @sara-02. Thanks for your help on this review! We appreciate all of the help from our reviewers during what remains a challenging time for the world.

@jboynyc Thanks for your work to address all input. Please do the following:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

**Comment by jboynyc** [comment]
- Latest tagged release is [0.4.10](https://github.com/jboynyc/textnets/releases/tag/v0.4.10)
- Zenodo DOI for that release is [10.5281/zenodo.4028610](https://doi.org/10.5281/zenodo.4028610)

**Comment by gkthiruvathukal** [comment]
@whedon set v0.4.10 as versino

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by gkthiruvathukal** [comment]
@whedon set v0.4.10 as version

**Comment by whedon** [comment]
OK. v0.4.10 is the version.

**Comment by gkthiruvathukal** [comment]
@whedon set 10.5281/zenodo.4028610 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4028610" target="_blank">10.5281/zenodo.4028610</a> is the archive.

**Comment by gkthiruvathukal** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2594 with the following error: 

 Can't find any papers to compile :-(

**Comment by gkthiruvathukal** [comment]
@whedon generate pdf from joss-submission

**Comment by whedon** [comment]
PDF failed to compile for issue #2594 with the following error: 

 Can't find any papers to compile :-(

**Comment by gkthiruvathukal** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02594/joss.02594/10.21105.joss.02594.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02594/joss.02594/10.21105.joss.02594.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@gkthiruvathukal - when the paper is a in branch, you need to accept it from the branch:

**Comment by danielskatz** [comment]
@whedon accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1812

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1812, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1146/annurev-soc-081715-074206 is OK
- 10.1073/pnas.1607151113 is OK
- 10.5281/zenodo.1469356 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.1126/sciadv.aaq1360 is OK
- 10.1111/jtsb.12086 is OK
- 10.21105/joss.00774 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @sara-02 - above you say that the unchecked item in your list is satisfied, so I am going to move the acceptance forward, but if you could check off the item itself, it will be slightly cleaner.

**Comment by danielskatz** [comment]
👋 @jboynyc - Some fixes are needed in the paper: https://github.com/jboynyc/textnets/pull/19 and https://github.com/jboynyc/textnets/pull/20

**Comment by sara-02** [comment]
> wave @sara-02 - above you say that the unchecked item in your list is satisfied, so I am going to move the acceptance forward, but if you could check off the item itself, it will be slightly cleaner.

Done

**Comment by jboynyc** [comment]
> wave @jboynyc - Some fixes are needed in the paper: [jboynyc/textnets#19](https://github.com/jboynyc/textnets/pull/19) and [jboynyc/textnets#20](https://github.com/jboynyc/textnets/pull/20)

Merged! Thanks for catching those.

**Comment by danielskatz** [comment]
@whedon accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1146/annurev-soc-081715-074206 is OK
- 10.1073/pnas.1607151113 is OK
- 10.5281/zenodo.1469356 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.3233/978-1-61499-649-1-87 is OK
- 10.1126/sciadv.aaq1360 is OK
- 10.1111/jtsb.12086 is OK
- 10.21105/joss.00774 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1815

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1815, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1316747954460471301) 👈 🐦🐦🐦

**Comment by danielskatz** [comment]
Congratulations to @jboynyc (John Boy)!!

And thanks to @sara-02 & @tresoldi for reviewing, and @gkthiruvathukal for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02594/status.svg)](https://doi.org/10.21105/joss.02594)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02594">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02594/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02594/status.svg
   :target: https://doi.org/10.21105/joss.02594
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02594/status.svg)](https://doi.org/10.21105/joss.02594)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by jboynyc** [comment]
Thanks to all involved!
