### ISSUE TITLE
[PRE REVIEW]: MewMew : Programming in Cats' Language

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2595]
**Submitting author:** @bauripalash (<a href="http://orcid.org/0000-0002-0498-628X">Palash Bauri</a>)
**Repository:** <a href="https://github.com/bauripalash/mewmew/" target ="_blank">https://github.com/bauripalash/mewmew/</a>
**Version:** v0.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @bauripalash. **Currently, there isn't an JOSS editor assigned** to your paper.

@bauripalash if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (222.4 files/s, 24705.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              1            155            341            336
Markdown                         3             54              0            152
Bourne Shell                     2             26              6             67
ANTLR Grammar                    1             24              0             61
YAML                             2              4              1             35
CMake                            1              7              0             31
make                             1              7              0             18
TeX                              1              0              0              8
-------------------------------------------------------------------------------
SUM:                            12            277            348            708
-------------------------------------------------------------------------------


Statistical information for the repository '2595' was gathered on 2020/08/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Johan-Mi                         3            48             23            6.92
Palash Bauri                     8           881             74           93.08

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Johan-Mi                     46           95.8          0.1                0.00
Palash Bauri                786           89.2          0.6               43.38
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02595/joss.02595/10.21105.joss.02595.pdf)

**Comment by arfon** [comment]
@bauripalash - thanks for your submission to JOSS. While this submission is very fun 😺, it's not in scope for JOSS sorry.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by bauripalash** [comment]
🤷‍♂️ Thank you 😔
