### ISSUE TITLE
[PRE REVIEW]: RCaller: A Java package for interfacing R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2600]
**Submitting author:** @jbytecode (<a href="http://orcid.org/0000-0002-9402-1982">Mehmet Hakan Satman</a>)
**Repository:** <a href="https://github.com/jbytecode/rcaller/" target ="_blank">https://github.com/jbytecode/rcaller/</a>
**Version:** v3.0
**Editor:** @mikldk
**Reviewers:** @xin-huang, @nthomasCUBE
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jbytecode. **Currently, there isn't an JOSS editor assigned** to your paper.

@jbytecode if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2600 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2600 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.9734/bjmcs/2014/10902 may be missing for title: RCaller: A software library for calling R from Java
- https://doi.org/10.1007/s00180-008-0132-x may be missing for title: How to talk to strangers: ways to leverage connectivity between R, Java and Objective C
- https://doi.org/10.1145/3328433.3328458 may be missing for title: Towards polyglot adapters for the graalvm

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev Can you help trouble shoot the above error? :point_up:

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02600/joss.02600/10.21105.joss.02600.pdf)

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.9734/bjmcs/2014/10902 is OK
- 10.1007/s00180-008-0132-x is OK
- 10.1145/3328433.3328458 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02600/joss.02600/10.21105.joss.02600.pdf)

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.47 s (243.0 files/s, 23787.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                            87           1462           1450           5601
TeX                              4            218             14            896
PHP                              8            142            271            377
R                                2             14              0            187
Maven                            1             11              0            166
Markdown                         5             55              0            163
INI                              3              0              0             13
XML                              2              0              0             13
YAML                             1              3              0              7
-------------------------------------------------------------------------------
SUM:                           113           1905           1735           7423
-------------------------------------------------------------------------------


Statistical information for the repository '2600' was gathered on 2020/08/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alexander Bondarev               4           139             81            0.38
Edinei Piovesan                  1            70              9            0.14
Kopilov Aleksandr                7           173             47            0.38
Luke Lai                         1             2              1            0.01
Manuel Muradas                   3            50              3            0.09
Mehmet Hakan Satman              2            27              1            0.05
Paul Curcean                    17          6618           6143           22.19
SKYLAKE-2016\celthan             2           104              4            0.19
hako                            11          1945           1420            5.85
jbytecode                       39          8914           6442           26.71
kstarosta                        2            34              9            0.07
mbatchkarov                      4          4598            240            8.41
mhsatman                        77         15356           4981           35.37
oem                              3            62              6            0.12
stevensotelo                     1            12              5            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alexander Bondarev          110           79.1         57.6                3.64
Edinei Piovesan              70          100.0         32.4               20.00
Kopilov Aleksandr           157           90.8          2.6               18.47
Manuel Muradas               43           86.0         45.6                6.98
Paul Curcean               1702           25.7         53.2                7.87
SKYLAKE-2016\celthan        104          100.0         44.4               45.19
jbytecode                  4124           46.3         63.8               19.88
kstarosta                    34          100.0         42.7               17.65
mbatchkarov                2161           47.0        105.0               23.79
stevensotelo                  8           66.7         65.0                0.00
```

**Comment by jbytecode** [comment]
since this repo is moved from old [code.google.com](https://code.google.com/archive/p/rcaller/source/default/commits), I am represented in above table by more than one nicknames, so 'hako', 'jbytecode','Mehmet Hakan Satman', and 'mhsatman' are both I am. fyi.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jbytecode 

Some notes on your paper: 
- [ ] Typo: `persfective` -> `perspective`

- [ ] We do not accept previously published scholarly works in JOSS. If major changes have been made, or if the focus on the paper is significantly different, exceptions can be made. Therefore, can you please clarify what the difference in focus/content/intent is for the current submission with respect to this paper: `Satman, M. H. (2014). RCaller: A software library for calling r from java.Journal of Advances in Mathematics and Computer Science, 2188–2196. doi:10.9734/bjmcs/2014/10902`. Likely you are looking to submit for the new developments from the past 6 years but please formally clarify the difference and list some of these developments please.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikldk @kakiac could one of you edit this submission?

**Comment by jbytecode** [comment]
@Kevin-Mattheus-Moerman Dear editor, new features such as support for DataFrames, R Start-up options, Java Scripting API (JSR 223), performance improvements, and minor API changes are not included in the paper you mentioned above. I will highlight the differences. Thanks.

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02600/joss.02600/10.21105.joss.02600.pdf)

**Comment by mikldk** [comment]
> @mikldk @kakiac could one of you edit this submission?

I am rather busy at the moment, so I prefer if @kakearney could handle this interesting submission. But if they cannot, I will be happy to.

**Comment by danielskatz** [comment]
@kakearney is not an editor?  Maybe you meant @kakiac ?

**Comment by danielskatz** [comment]
👋 @kakiac - can you edit this submission?

**Comment by danielskatz** [comment]
@mikldk  - I'm going to assign this to you, based on your semi-willingness and the fact that @kakiac also has another request right now.  Thanks!

**Comment by danielskatz** [comment]
@whedon assign @mikldk as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@jbytecode Can you please explain/clarify why the other (major) committers are not co-authors (maybe they declined?)?

**Comment by jbytecode** [comment]
@mikldk the most active contributer, Paul, is not interested in the project any more, so I didn't ask him to join. Should I offer them to participate?

**Comment by mikldk** [comment]
@jbytecode Yes, please ask all who contributed one way or another.

**Comment by jbytecode** [comment]
Dear editor @mikldk, I have just opened an issue in RCaller repo and I invited them to participate. fyi.

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02600/joss.02600/10.21105.joss.02600.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02600/joss.02600/10.21105.joss.02600.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02600/joss.02600/10.21105.joss.02600.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02600/joss.02600/10.21105.joss.02600.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
Dear editor @mikldk , after asking all contributors to join manuscript 11 days ago, one of the major contributor @Kopilov joined, other major contributor is no longer interested in the project and has no respond. The third major one and some of other minor contributors are happy being in the Acknowledgement section, some of them also have no response. Any actions needed?

**Comment by mikldk** [comment]
@jbytecode Thanks. Do you have any suggested reviewers?

**Comment by jbytecode** [comment]
No but if you don't have time, I can choose a few suitable reviewers from the list for you.

**Comment by jbytecode** [comment]
pragyansmita, nthomasCUBE, xin-huang, marcoapintoo, tylerwmarrs, marcoapintoo have both Java and R in their preferred programming language column.

**Comment by mikldk** [comment]
@marcoapintoo, @tylerwmarrs: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@nthomasCUBE, @xin-huang: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by xin-huang** [comment]
Hi @mikldk, I am happy to help

**Comment by nthomasCUBE** [comment]
Hi, me too

**Comment by mikldk** [comment]
@whedon add @xin-huang as reviewer

**Comment by whedon** [comment]
OK, @xin-huang is now a reviewer

**Comment by mikldk** [comment]
@whedon add @nthomasCUBE as reviewer

**Comment by whedon** [comment]
OK, @nthomasCUBE is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2722.
