### ISSUE TITLE
[PRE REVIEW]: PyAstroPol : A Python package for the instrumental polarization analysis of the astronomical optics.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2602]
**Submitting author:** @hemanthpruthvi (<a href="http://orcid.org/0000-0002-4892-6561">Hemanth Pruthvi</a>)
**Repository:** <a href="https://github.com/hemanthpruthvi/PyAstroPol" target ="_blank">https://github.com/hemanthpruthvi/PyAstroPol</a>
**Version:** v0.1.0
**Editor:** @pibion
**Reviewers:** @aquilesC, @caldarolamartin, @mwcraig
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @hemanthpruthvi. **Currently, there isn't an JOSS editor assigned** to your paper.

@hemanthpruthvi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.43 s (149.9 files/s, 54141.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       8           2166           2178           8618
HTML                             6            233              0           1605
Python                          10            161            686           1229
Jupyter Notebook                29              0           3739           1088
CSS                              4            323             42           1026
Markdown                         2             24              0            127
TeX                              1              8              0             64
reStructuredText                 3             27             42             29
DOS Batch                        1              8              1             27
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                            65           2954           6694          13823
-------------------------------------------------------------------------------


Statistical information for the repository '2602' was gathered on 2020/08/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Hemanth Pruthvi                 13         16878           1824           99.88
hemanthpruthvi                   1             3             19            0.12

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Hemanth Pruthvi           15035           89.1          0.1               16.99
hemanthpruthvi                3          100.0          0.0                0.00
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1086/599043 is OK
- 10.1117/12.2181397 is OK
- 10.1201/b19711 is OK
- 10.1117/1.JATIS.4.4.048002 is OK

MISSING DOIs

- https://doi.org/10.1117/12.2233176 may be missing for title: Polarization modeling and predictions for DKIST part 1: telescope and example instrument configurations

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02602/joss.02602/10.21105.joss.02602.pdf)

**Comment by hemanthpruthvi** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by hemanthpruthvi** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1086/599043 is OK
- 10.1117/12.2181397 is OK
- 10.1117/12.2233176 is OK
- 10.1201/b19711 is OK
- 10.1117/1.JATIS.4.4.048002 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by hemanthpruthvi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02602/joss.02602/10.21105.joss.02602.pdf)

**Comment by hemanthpruthvi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02602/joss.02602/10.21105.joss.02602.pdf)

**Comment by hemanthpruthvi** [comment]
Potential reviewers:
caldarolamartin
aquilesC

**Comment by hemanthpruthvi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02602/joss.02602/10.21105.joss.02602.pdf)

**Comment by kthyng** [comment]
Hi @pibion! Are you up for editing this submission?

**Comment by kthyng** [comment]
@whedon invite @pibion as editor

**Comment by whedon** [comment]
@pibion has been invited to edit this submission.

**Comment by pibion** [comment]
@kthyng I have a lot of experience with simulating beam polarization in accelerator systems, which maps weirdly well onto modeling optical systems.  But I've never applied that knowledge outside of beam modeling.

I'm comfortable being the editor, although I'd go for three reviewers rather than two.

How does that sound?  Totally understand if you'd rather have someone with telescope-specific experience here.

**Comment by kthyng** [comment]
Hi @pibion that works for me! Thank you!

**Comment by kthyng** [comment]
@whedon assign @pibion as editor

**Comment by whedon** [comment]
OK, the editor is @pibion

**Comment by pibion** [comment]
@hemanthpruthvi apologies for the slow start on my end!  I'll begin inviting reviewers; once three have accepted we'll get the review underway.

Also, thank you for providing reviewer suggestions!

**Comment by pibion** [comment]
:wave: @caldarolamartin & @aquilesC & @cavestruz, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by hemanthpruthvi** [comment]
@pibion It's all good

**Comment by aquilesC** [comment]
I can review the paper

**Comment by caldarolamartin** [comment]
I can also review the paper, if you are still interested.

Let me know.

Best,
Martin

-------------------------

Martín Caldarola

**Comment by pibion** [comment]
@whedon add @aquilesC as reviewer

**Comment by whedon** [comment]
OK, @aquilesC is now a reviewer

**Comment by pibion** [comment]
@whedon add @caldarolamartin as reviewer

**Comment by whedon** [comment]
OK, @caldarolamartin is now a reviewer

**Comment by pibion** [comment]
Excellent @caldarolamartin , @aquilesC , I've added you as reviewers!  We need one more reviewer for this paper and then I'll begin the review.  Once that happens, a new "review" issue will be opened and you'll both get a checklist in the issue.  The review process will involve everyone going through their review checklists.

**Comment by pibion** [comment]
:wave: @garrettj403, @cavestruz, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by garrettj403** [comment]
Hi @pibion , sorry I don't have the time right now. Looks like an interesting project though!

**Comment by pibion** [comment]
@garrettj403 I definitely understand 👍 

Thanks for letting us know!

**Comment by pibion** [comment]
@Teuben, @Deech08, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by Deech08** [comment]
@pibion - Apologies, but I don't think I can put in the time right now to handle this review.

**Comment by pibion** [comment]
@hemanthpruthvi apologies for the delay, it's taking a while to find a third reviewer!

I'm still working on it and hope to have someone identified by the end of this week.

**Comment by hemanthpruthvi** [comment]
@pibion I understand. Thank you very much for your efforts.

**Comment by pibion** [comment]
@whedon add @mwcraig as reviewer

**Comment by whedon** [comment]
OK, @mwcraig is now a reviewer

**Comment by pibion** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2693.
