### ISSUE TITLE
[PRE REVIEW]: Ripserer.jl: flexible and efficient persistent homology computation in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2603]
**Submitting author:** @mtsch (<a href="http://orcid.org/0000-0003-0734-2719">Matija Čufar</a>)
**Repository:** <a href="https://github.com/mtsch/Ripserer.jl" target ="_blank">https://github.com/mtsch/Ripserer.jl</a>
**Version:** v0.14.7
**Editor:** @VivianePons
**Reviewers:** @juliohm, @sauln
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mtsch. **Currently, there isn't an JOSS editor assigned** to your paper.

@mtsch if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.889971 is OK

MISSING DOIs

- https://doi.org/10.1007/978-3-319-64185-0_11 may be missing for title: Topological data analysis for image tampering detection
- https://doi.org/10.1038/ncomms15396 may be missing for title: Quantifying similarity of pore-geometry in nanoporous materials
- https://doi.org/10.1137/15m1031151 may be missing for title: Biological Aggregation Driven by Social and Environmental Factors: A Nonlocal Model and Its Degenerate Cahn–Hilliard Approximation
- https://doi.org/10.1145/3350755.3400244 may be missing for title: Towards Lockfree Persistent Homology
- https://doi.org/10.21105/joss.00925 may be missing for title: Ripser. py: A lean persistent homology library for python
- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing
- https://doi.org/10.1137/15m1020575 may be missing for title: JuMP: A modeling language for mathematical optimization

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02603/joss.02603/10.21105.joss.02603.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.67 s (95.5 files/s, 146842.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              4              1              1          91516
Julia                           42            951            363           4762
Markdown                         8            141              0            430
TeX                              1              0              0            129
YAML                             4              7              0             86
TOML                             3              4              0             61
make                             1              0              0              2
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            64           1104            364          96987
-------------------------------------------------------------------------------


Statistical information for the repository '2603' was gathered on 2020/08/26.
No commited files with the specified extensions were found.
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@mtsch can you work on the following: 

- [ ] Can you check/fix those missing/invalid DOI's :point_up:? You can call `@whedon check references` to check these here
- [ ] As recommended in [our guidelines](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) can you rework/add text to have a `Statement of Need` section in your paper? You can call `@whedon generate pdf` to update the paper pdf here

**Comment by Kevin-Mattheus-Moerman** [comment]
@VivianePons @xuanxu @drvinceknight could one of you handle this submission?

**Comment by VivianePons** [comment]
I can

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by mtsch** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-319-64185-0_11 is OK
- 10.1137/15M1031151 is OK
- 10.1038/ncomms15396 is OK
- 10.1145/3350755.3400244 is OK
- 10.4230/LIPIcs.SoCG.2016.71 is OK
- 10.21105/joss.00925 is OK
- 10.1137/141000671 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.5555/3122009.3122017 is INVALID
```

**Comment by mtsch** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-3-319-64185-0_11 is OK
- 10.1137/15M1031151 is OK
- 10.1038/ncomms15396 is OK
- 10.1145/3350755.3400244 is OK
- 10.4230/LIPIcs.SoCG.2016.71 is OK
- 10.21105/joss.00925 is OK
- 10.1137/141000671 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mtsch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02603/joss.02603/10.21105.joss.02603.pdf)

**Comment by mtsch** [comment]
Ok, I fixed the DOIs and added a statement of need.

**Comment by VivianePons** [comment]
@mtsch thank you for fixing the DOI

do you have any recommendations for potential reviewers? You can look at [our list of potential reviewers](https://bit.ly/joss-reviewers) but also suggest names outside the list

**Comment by mtsch** [comment]
I looked through the list and the intersection between topological data analysis and Julia appears to be empty.

Maybe @sauln might find this project interesting? Potentially @juliohm as well?

**Comment by VivianePons** [comment]
Indeed, I have just asked them, let's see!

**Comment by mtsch** [comment]
Thank you!

**Comment by VivianePons** [comment]
@whedon assign @juliohm as reviewer

**Comment by whedon** [comment]
OK, @juliohm is now a reviewer

**Comment by juliohm** [comment]
@VivianePons I remember JOSS had a check list on each submission. Is it still available? I remember the bot was responsible for creating this checklist. The review process already started?

**Comment by VivianePons** [comment]
The checklist appear on the review issue, we are still on the "pre review". I have just confirmed a second reviewer and am about to launch the review :)

**Comment by VivianePons** [comment]
@whedon add @sauln as reviewer

**Comment by whedon** [comment]
OK, @sauln is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2614.
