### ISSUE TITLE
[REVIEW]: OpenDrop: Open-source software for pendant drop tensiometry & contact angle measurements

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2604]
**Submitting author:** @jdber1 (<a href="http://orcid.org/0000-0002-0961-7782">Joe Berry</a>)
**Repository:** <a href="https://github.com/jdber1/opendrop" target ="_blank">https://github.com/jdber1/opendrop</a>
**Version:** v3.2.2
**Editor:** @kyleniemeyer
**Reviewers:** @rajeshrinet, @FelixKratz
**Archive:** <a href="https://doi.org/10.5281/zenodo.4555201" target="_blank">10.5281/zenodo.4555201</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/81c283e1b9af1d3d0db6b2da1d60855e/status.svg)](https://joss.theoj.org/papers/81c283e1b9af1d3d0db6b2da1d60855e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/81c283e1b9af1d3d0db6b2da1d60855e"><img src="https://joss.theoj.org/papers/81c283e1b9af1d3d0db6b2da1d60855e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/81c283e1b9af1d3d0db6b2da1d60855e/status.svg)](https://joss.theoj.org/papers/81c283e1b9af1d3d0db6b2da1d60855e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jdber1/opendrop" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@cryos & @rajeshrinet, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kyleniemeyer know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jdber1/opendrop">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jdber1) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jdber1/opendrop">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jdber1) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cryos, @rajeshrinet it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1103/physrevlett.100.024501 may be missing for title: Decompressing emulsion droplets favors coalescence
- https://doi.org/10.1103/revmodphys.69.865 may be missing for title: Nonlinear dynamics and breakup of free-surface flows
- https://doi.org/10.1163/156856192x00629 may be missing for title: Contact angle, wetting, and adhesion: a critical review
- https://doi.org/10.1016/j.jcis.2016.10.040 may be missing for title: Mapping coalescence of micron-sized drops and bubbles
- https://doi.org/10.1016/j.biosystemseng.2012.02.005 may be missing for title: Experimental method for the assessment of agricultural spray retention based on high-speed imaging of drop impact on a synthetic superhydrophobic surface
- https://doi.org/10.1039/c6sm00047a may be missing for title: Electrokinetics of isolated electrified drops
- https://doi.org/10.1039/c7ra05538b may be missing for title: A comparative analysis of antibacterial properties and in flammatory responses for the KR-12 peptide on titanium and PEGylated titanium surfaces
- https://doi.org/10.1038/srep21048 may be missing for title: Durable, superoleophobic polymer – nanoparticle composite surfaces with re-entrant geometry via solvent-induced phase transformation
- https://doi.org/10.1021/acsami.7b03094.s001 may be missing for title: Decreasing the Wettability of Cellulose Nanocrystal Surfaces Using Wrinkle-Based Alignment
- https://doi.org/10.1021/la102566c may be missing for title: Contact angles of liquid drops on super hydrophobic surfaces: understanding the role of flattening of drops by gravity

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02604/joss.02604/10.21105.joss.02604.pdf)

**Comment by kyleniemeyer** [comment]
👋 @jdber1 @cryos  @rajeshrinet

**Comment by kyleniemeyer** [comment]
@jdber1 while the reviewers begin looking at the software, there are a few issues with the paper you can take care of. It looks like your bib file has a number of references that are not cited in the paper, and then any references you do cite need DOIs

**Comment by cryos** [comment]
@kyleniemeyer it looks like I didn't accept the invitation in time, and it had expired when I started going through the instructions.

**Comment by jdber1** [comment]
> @jdber1 while the reviewers begin looking at the software, there are a few issues with the paper you can take care of. It looks like your bib file has a number of references that are not cited in the paper, and then any references you do cite need DOIs

@kyleniemeyer I have updated the bib file to include DOIs and also delete any un-cited references.

**Comment by jdber1** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02604/joss.02604/10.21105.joss.02604.pdf)

**Comment by rajeshrinet** [comment]
@ kyleniemeyer I have now gone through the paper and successfully installed the library from the GitHub repo. The paper is well-written and the sofware looks very good! Please can I request the authors to respond to my following comments such that I can complete my review checklist:

1. The **installation** works as indicated on the [docs](https://opendrop.readthedocs.io/en/latest/getting_started/index.html) but the command for launch needs update: `python3 -m opendrop`

2. **Example usage**: It would be useful to provide steps to run examples from sample frames on the repo. This can then also be used to test as described in 3 below.

3. **Testing:** The library does have a `tests` folder. But there does not seem to be an automated testing nor there is an explanation of manual steps for testing. 

4. **Community guidelines** needs to be added to the repo as indicate in this issue: https://github.com/jdber1/opendrop/issues/23

5. **State of the field**: The author should compare opendrop with existing similar software, if any.

**Comment by kyleniemeyer** [comment]
@whedon re-invite @cryos as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@cryos please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by kyleniemeyer** [comment]
@cryos sorry I missed your previous message—you should be able to accept the above invitation to review.

@jdber1 please work on addressing @rajeshrinet's comments

**Comment by jdber1** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02604/joss.02604/10.21105.joss.02604.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02604/joss.02604/10.21105.joss.02604.pdf) :page_facing_up: :point_left:

**Comment by jdber1** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02604/joss.02604/10.21105.joss.02604.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02604/joss.02604/10.21105.joss.02604.pdf) :page_facing_up: :point_left:

**Comment by jdber1** [comment]
@rajeshrinet Thank you for your feedback. Here are the changes we have made based on your list:

> 1. The **installation** works as indicated on the [docs](https://opendrop.readthedocs.io/en/latest/getting_started/index.html) but the command for launch needs update: `python3 -m opendrop`

The [docs](https://opendrop.readthedocs.io/en/latest/getting_started/index.html) has been updated to include the correct command.

> 2. **Example usage**: It would be useful to provide steps to run examples from sample frames on the repo. This can then also be used to test as described in 3 below.

I have included sample images for both surface tension and contact angle functionality in the [example_images](https://github.com/jdber1/opendrop/tree/master/example_images) folder. The steps involved have been outlined in the documentation, see here for [interfacial tension](https://opendrop.readthedocs.io/en/latest/usage/index.html#interfacial-tension), and here for [contact angle](https://opendrop.readthedocs.io/en/latest/usage/index.html#contact-angle). I have updated the readme to include information on this.

> 3. **Testing:** The library does have a `tests` folder. But there does not seem to be an automated testing nor there is an explanation of manual steps for testing.

Manual steps for testing with the example images are outlined in the [docs](https://opendrop.readthedocs.io/en/latest/getting_started/index.html) , as outlined in the response to 2.

> 4. **Community guidelines** needs to be added to the repo as indicate in this issue: [jdber1/opendrop#23](https://github.com/jdber1/opendrop/issues/23)

Community guidelines have been added to the repo.

> 5. **State of the field**: The author should compare opendrop with existing similar software, if any.

I have modified the paper to include two figures showing comparisons between OpenDrop and existing commercial software. I am still trying to get the captions and the figure references to show correctly.

**Comment by rajeshrinet** [comment]
@jdber1, thanks for your responses. @kyleniemeyer, I have now completed my checklists and I am happy to recommend this paper.

**Comment by jdber1** [comment]
@kyleniemeyer what is the status of the review currently? Do you require another reviewer?

**Comment by kyleniemeyer** [comment]
@cryos were you able to accept the review invitation? and either way, have you been able to make progress in your review?

**Comment by jdber1** [comment]
Hi @kyleniemeyer, do you need more reviewers to complete this review? Additionally, I am having trouble defining figure sizes and captions in the paper. Are there guidelines for this?

**Comment by jdber1** [comment]
> Hi @kyleniemeyer, do you need more reviewers to complete this review? Additionally, I am having trouble defining figure sizes and captions in the paper. Are there guidelines for this?

@kyleniemeyer just following up on this again

**Comment by jdber1** [comment]
Hi @kyleniemeyer what is the status of this submission? I submitted to JOSS over 9 months ago, and would really like to get this out as soon as possible.

**Comment by kyleniemeyer** [comment]
@jdber1 Sorry for the delay—I do understand your frustration, but please do understand that you submitted right at the beginning of a tough time. We do require two reviews, and due to the hardware requirement your submission is a bit more challenging. But, I have reached out again to the second reviewer.

Regarding figures and captions, [our docs](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) have some guidance on this, but I don't believe it is possible to control size/placement beyond placing the caption and figure commands:
```
Figures can be included like this:
![Caption for example figure.\label{fig:example}](figure.png)
and referenced from text using \autoref{fig:example}.
```

It does look like it's possible to vary the figure width, using (for example): 
```
![Caption for example figure.\label{fig:example}](figure.png){ width=20% }
```
and the `\newpage` command does work.

But, otherwise, placement is up to Pandoc and LaTeX.

**Comment by jdber1** [comment]
@kyleniemeyer no problems at all, I understand it has been a difficult year. Let me know if you need more reviewer suggestions for the second reviewer. Thanks for the help on the figures and captions, I will give it a try this week.

**Comment by kyleniemeyer** [comment]
@jdber1 I do think we might need to find a new, second reviewer. Do you have more recommendations?

**Comment by jdber1** [comment]
> @jdber1 I do think we might need to find a new, second reviewer. Do you have more recommendations?

Try Jonas Hegemann ([jhegemann](https://github.com/jhegemann)). I'll have a look for more if he is not able to review.

**Comment by kyleniemeyer** [comment]
@whedon remove @cryos as reviewer

**Comment by whedon** [comment]
OK, @cryos is no longer a reviewer

**Comment by kyleniemeyer** [comment]
Hello @jdber1, to keep you in the loop, I did find someone else who agreed to review a few weeks ago, and I just checked back in with them.

**Comment by jdber1** [comment]
> Hello @jdber1, to keep you in the loop, I did find someone else who agreed to review a few weeks ago, and I just checked back in with them.

@kyleniemeyer thanks for the update.

**Comment by kyleniemeyer** [comment]
@whedon add @FelixKratz as reviewer

**Comment by whedon** [comment]
OK, @FelixKratz is now a reviewer

**Comment by kyleniemeyer** [comment]
Hello @FelixKratz 👋 please accept the review invitation, which will allow you to check off items in your reviewer checklist above. Thank you for agreeing to review this!

**Comment by kyleniemeyer** [comment]
For transparency, @kierfeld and @FelixKratz will be reviewing together, via a joint checklist.

**Comment by FelixKratz** [comment]
We have gone through the paper and tested the application. The problems we pointed out in [Application will stop analysing images](https://github.com/jdber1/opendrop/issues/30) and [Saving Data to Disk not working](https://github.com/jdber1/opendrop/issues/28) where resolved very quickly. We have compared the results of the presented application with two other methods and find consistent predictions. We thus recommend the paper and the application.

**Comment by kyleniemeyer** [comment]
Thanks @FelixKratz for your quick review!

**Comment by kyleniemeyer** [comment]
OK @jdber1, with two reviewers now recommending acceptance, we can now proceed to publication! I will do some final checks on your paper, but in the meantime please archive the software repo (e.g., at Zenodo) and provide the DOI here. And, thanks for your patience with this review.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02604/joss.02604/10.21105.joss.02604.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02604/joss.02604/10.21105.joss.02604.pdf) :page_facing_up: :point_left:

**Comment by jdber1** [comment]
> I will do some final checks on your paper, but in the meantime please archive the software repo (e.g., at Zenodo) and provide the DOI here

Thanks very much @kyleniemeyer! I will archive the repo and report the DOI when I get a chance.

**Comment by jdber1** [comment]
> OK @jdber1, with two reviewers now recommending acceptance, we can now proceed to publication! I will do some final checks on your paper, but in the meantime please archive the software repo (e.g., at Zenodo) and provide the DOI here. And, thanks for your patience with this review.

Hi @kyleniemeyer I have archived the software repo - the DOI is 10.5281/zenodo.4555201

**Comment by jdber1** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2604 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (9a5ed3fef427451304bdbc1e/paper/paper.md): did not find expected '-' indicator while parsing a block collection at line 31 column 2 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by jdber1** [comment]
@whedon generate pdf

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.4555201 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4555201" target="_blank">10.5281/zenodo.4555201</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon set v3.2.2 as version

**Comment by whedon** [comment]
OK. v3.2.2 is the version.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jcis.2015.05.012 is OK
- 10.1021/acsami.7b03094 is OK
- 10.1038/srep21048 is OK
- 10.1039/C7RA05538B is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2108

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2108, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1364342587830722562) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2109
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02604](https://doi.org/10.21105/joss.02604)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @jdber1 on your article's publication in JOSS! And thank you for your patience here.

Many thanks to @rajeshrinet and @FelixKratz for reviewing this.

(It looks like the PDF has not yet built, but should show up momentarily.)

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02604/status.svg)](https://doi.org/10.21105/joss.02604)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02604">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02604/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02604/status.svg
   :target: https://doi.org/10.21105/joss.02604
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02604/status.svg)](https://doi.org/10.21105/joss.02604)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by jdber1** [comment]
> Congrats @jdber1 on your article's publication in JOSS! And thank you for your patience here.
> 
> Many thanks to @rajeshrinet and @FelixKratz for reviewing this.
> 
> (It looks like the PDF has not yet built, but should show up momentarily.)

@kyleniemeyer thanks very much for overseeing a difficult review in challenging times.
