### ISSUE TITLE
[REVIEW]: AstroPaint: A Python Package for Painting Halo Catalogs into Celestial Maps

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2608]
**Submitting author:** @syasini (<a href="http://orcid.org/0000-0003-1978-6325">Siavash Yasini</a>)
**Repository:** <a href="https://github.com/syasini/AstroPaint" target ="_blank">https://github.com/syasini/AstroPaint</a>
**Version:** 0.1.1
**Editor:** @harpolea
**Reviewer:** @AshKelly, @zpace
**Archive:** <a href="https://doi.org/10.5281/zenodo.4243176" target="_blank">10.5281/zenodo.4243176</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fb0e63372a0ada00083300ca5f2cba19/status.svg)](https://joss.theoj.org/papers/fb0e63372a0ada00083300ca5f2cba19)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fb0e63372a0ada00083300ca5f2cba19"><img src="https://joss.theoj.org/papers/fb0e63372a0ada00083300ca5f2cba19/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fb0e63372a0ada00083300ca5f2cba19/status.svg)](https://joss.theoj.org/papers/fb0e63372a0ada00083300ca5f2cba19)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/syasini/AstroPaint" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@AshKelly & @zpace, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @harpolea know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/syasini/AstroPaint">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@syasini) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/syasini/AstroPaint">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@syasini) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @AshKelly, @zpace it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1088/0004-637X/709/2/920 is OK
- 10.2172/1556957 is OK
- 10.3847/2041-8213/ab0bfe is OK
- 10.1093/mnras/stw2035 is OK
- 10.21105/joss.01298 is OK
- 10.1038/302315a0 is OK
- 10.1093/mnras/sty3226 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02608/joss.02608/10.21105.joss.02608.pdf)

**Comment by zpace** [comment]
After having reviewed this submission, I am happy to recommend it for acceptance into JOSS. The developers have responded to my handful of comments and suggestions to my satisfaction.

**Comment by syasini** [comment]
Thanks, @zpace. Your comments and feedback were incredibly helpful. We appreciate your assistance and guidance in creating the documentation and all the time you spent on reviewing our software in detail.

**Comment by AshKelly** [comment]
I would like to apologise for the delay in my review and thank you for your continued patience. I will complete my review before the end of the week!

**Comment by AshKelly** [comment]
I am happy to recommend this submission for acceptance into JOSS. The developers have responded positively to all of my comments and suggestions.

I would also like to add that I really like the library and the simplicity of the API. Notably, the abstraction into three main components `Catalog`, `Canvas` and `Painter`. I found that after just a short period experimenting with examples given in the docs, I was able to produce quite involved catalogues with relative ease. I anticipate this is a library I will use in the future. Great job!

I'd also like to thank @zpace as I benefited from the documentation that they helped produce. The RTD is a really great addition!

**Comment by syasini** [comment]
Thanks for your feedback @AshKelly! I sincerely appreciate your kind comment regarding the API. I'm glad you liked it and found it easy to use. 
We're grateful for your all help and really appreciate the time you took to review our work.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02608/joss.02608/10.21105.joss.02608.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02608/joss.02608/10.21105.joss.02608.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637X/709/2/920 is OK
- 10.2172/1556957 is OK
- 10.3847/2041-8213/ab0bfe is OK
- 10.1093/mnras/stw2035 is OK
- 10.21105/joss.01298 is OK
- 10.1038/302315a0 is OK
- 10.1093/mnras/sty3226 is OK

MISSING DOIs

- 10.1088/1475-7516/2020/10/012 may be a valid DOI for title: The Websky Extragalactic CMB Simulations

INVALID DOIs

- None
```

**Comment by arfon** [comment]
:wave: @syasini - I'm going to help out @harpolea to get this paper across the line and published.

**Comment by arfon** [comment]
@syasini - I made a tiny formatting fix in https://github.com/syasini/AstroPaint/pull/85. After merging (assuming you like the change), could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by syasini** [comment]
Thanks for your help @arfon. I just commented on issue #85. I sincerely appreciate your suggestion. 

After you submit the PR to `develop` I will go ahead with the new version release and submission to Zenodo and will report back here with the updates.

**Comment by arfon** [comment]
@syasini https://github.com/syasini/AstroPaint/pull/86

**Comment by syasini** [comment]
@arfon, I published a new release on (v1.0.0) on Zenodo. You can find it [here](https://zenodo.org/record/4243176#.X6I9qpNKjt1). Let me know if further actions are needed on my side. 

And thanks for resubmitting the PR to `develop`. I merged it earlier today :)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4243176 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4243176" target="_blank">10.5281/zenodo.4243176</a> is the archive.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637X/709/2/920 is OK
- 10.2172/1556957 is OK
- 10.3847/2041-8213/ab0bfe is OK
- 10.1093/mnras/stw2035 is OK
- 10.21105/joss.01298 is OK
- 10.1038/302315a0 is OK
- 10.1093/mnras/sty3226 is OK

MISSING DOIs

- 10.1088/1475-7516/2020/10/012 may be a valid DOI for title: The Websky Extragalactic CMB Simulations

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@syasini - did you check if `10.1088/1475-7516/2020/10/012` was a valid DOI for one of your references? If so, please add it to your BibTeX please.

**Comment by syasini** [comment]
Thanks for pointing that our @arfon. That's indeed the valid DOI for the reference. I just added it to the paper.bib file.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637X/709/2/920 is OK
- 10.1088/1475-7516/2020/10/012 is OK
- 10.2172/1556957 is OK
- 10.3847/2041-8213/ab0bfe is OK
- 10.1093/mnras/stw2035 is OK
- 10.21105/joss.01298 is OK
- 10.1038/302315a0 is OK
- 10.1093/mnras/sty3226 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637X/709/2/920 is OK
- 10.1088/1475-7516/2020/10/012 is OK
- 10.2172/1556957 is OK
- 10.3847/2041-8213/ab0bfe is OK
- 10.1093/mnras/stw2035 is OK
- 10.21105/joss.01298 is OK
- 10.1038/302315a0 is OK
- 10.1093/mnras/sty3226 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1894

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1894, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1324269112139329541) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1895
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02608](https://doi.org/10.21105/joss.02608)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@AshKelly, @zpace - many thanks for your reviews here and for @harpolea help editing ✨ 

@syasini - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02608/status.svg)](https://doi.org/10.21105/joss.02608)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02608">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02608/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02608/status.svg
   :target: https://doi.org/10.21105/joss.02608
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02608/status.svg)](https://doi.org/10.21105/joss.02608)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by syasini** [comment]
Thanks for the great news @arfon! This is very exciting. 

And many thanks again to @zpace and @AshKelly for their insightful feedback and their positive reviews and to @harpolea for editing. 

Publishing with JOSS was a great experience and we'll be looking forward to hopefully do it again in the future! 

Thank you all 🙏
