### ISSUE TITLE
[PRE REVIEW]: StatAid: a R package with a graphical user interface for data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2609]
**Submitting author:** @VincentAlcazer (<a href="http://orcid.org/0000-0003-1843-6286">Vincent Alcazer</a>)
**Repository:** <a href="https://github.com/VincentAlcazer/StatAid" target ="_blank">https://github.com/VincentAlcazer/StatAid</a>
**Version:** v1.0
**Editor:** @mikldk
**Reviewers:** @nistara, @adithirgis
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @VincentAlcazer. **Currently, there isn't an JOSS editor assigned** to your paper.

@VincentAlcazer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.37 s (123.4 files/s, 26453.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             5              0              0           4702
R                               32           1231            851           2762
Markdown                         5             70              0            135
TeX                              1              4              0             32
HTML                             1              0              0              9
YAML                             1              0              0              8
Rmd                              1             17             32              6
-------------------------------------------------------------------------------
SUM:                            46           1322            883           7654
-------------------------------------------------------------------------------


Statistical information for the repository '2609' was gathered on 2020/08/30.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v014.i09 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02609/joss.02609/10.21105.joss.02609.pdf)

**Comment by kthyng** [comment]
Hi @mikldk can you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@VincentAlcazer Thank you for this submission. Do you have any reviewers in mind (e.g. from [the list of people](https://bit.ly/joss-reviewers) mentioned above)?

The title of the paper has "a R package". This should be changed to "an R package" (or maybe even "An R package").

**Comment by VincentAlcazer** [comment]
@mikldk Thank you for your comment. Based on the list, I could suggest @adithirgis who seems to have an expertise in data analysis and Shiny apps, and @nistara who seems to be comfortable with health-related areas.

I am making the change for the title.

**Comment by VincentAlcazer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02609/joss.02609/10.21105.joss.02609.pdf)

**Comment by nistara** [comment]
I'd be happy to review this submission; it looks really interesting.

**Comment by mikldk** [comment]
@whedon assign @nistara as reviewer

**Comment by whedon** [comment]
OK, @nistara is now a reviewer

**Comment by mikldk** [comment]
@adithirgis: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by adithirgis** [comment]
Hi,

Thanks, I would be interested to review this. I will be able to start only
in a couple of days though. Is that ok?

Thanks!

**Comment by mikldk** [comment]
@adithirgis That's fine. Thank you.

**Comment by mikldk** [comment]
@whedon add @adithirgis as reviewer

**Comment by whedon** [comment]
OK, @adithirgis is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2630.
