### ISSUE TITLE
[PRE REVIEW]: CLOOPSy - Copernicus Land cOver crOwdsourcing Platform for Sentinel-based mapping

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#261]
**Submitting author:** @dandev89 (<a href="http://orcid.org/0000-0001-8600-7657">Daniele De Vecchi</a>)
**Repository:** <a href="https://bitbucket.org/cloopsy/android/" target ="_blank">https://bitbucket.org/cloopsy/android/</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @MWieland

**Author instructions**

Thanks for submitting your paper to JOSS @dandev89. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dandev89 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by dandev89** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by dandev89** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current JOSS editors:

```
@acabunoc
@arfon
@arokem
@biorelated
@brainstorm
@cMadan
@danielskatz
@jakevdp
@karthik
@katyhuff
@Kevin-Mattheus-Moerman
@kyleniemeyer
@labarba
@mgymrek
@pjotrp
@tracykteal
```

**Comment by dandev89** [comment]
@whedon assign @MWieland as reviewer

**Comment by whedon** [comment]
I'm sorry @dandev89, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by dandev89** [comment]
@whedon assign @MWieland as editor

**Comment by whedon** [comment]
I'm sorry @dandev89, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by dandev89** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @dandev89, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by dandev89** [comment]
@arfon  I'd suggest @MWieland as reviewer

**Comment by arfon** [comment]
> Sorry to bother you @arfon, but the editor is missing. I'd suggest @MWieland as reviewer

@dandev89 yep, it might take a week or so for one of the JOSS editors to volunteer to handle this submission. Thanks for recommending a reviewer - that will be very helpful.

**Comment by arfon** [comment]
👋 @MWieland - would you be willing to review this submission for JOSS?

**Comment by MWieland** [comment]
@arfon - Yes, I would be willing to review this submission for JOSS. Please instruct me on how to proceed further.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @MWieland as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @MWieland

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/291. Feel free to close this issue now!

**Comment by arfon** [comment]
@MWieland - please head over to #291 to carry out the review.
