### ISSUE TITLE
[PRE REVIEW]: Your: Your Unified Reader

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2610]
**Submitting author:** @KshitijAggarwal (<a href="http://orcid.org/0000-0002-2059-0525">Kshitij Aggarwal</a>)
**Repository:** <a href="https://github.com/thepetabyteproject/your" target ="_blank">https://github.com/thepetabyteproject/your</a>
**Version:** v0.5.1
**Editor:** @dfm
**Reviewers:** @pravirkr, @paulray
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @KshitijAggarwal. **Currently, there isn't an JOSS editor assigned** to your paper.

@KshitijAggarwal if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=3.18 s (17.0 files/s, 2935.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          38           1446           1087           3698
Jupyter Notebook                 4              0           2089            264
Markdown                         7             83              0            262
TeX                              1             19              0            235
YAML                             4             17             10            136
-------------------------------------------------------------------------------
SUM:                            54           1565           3186           4595
-------------------------------------------------------------------------------


Statistical information for the repository '2610' was gathered on 2020/08/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Devansh Agarwal                142          8674           6711           53.47
Kshitij Aggarwal               136          7639           3912           40.14
Reshma Anna Thomas               1             2              0            0.01
Reshma Thomas                    4           274            234            1.77
ReshmaAnnaThomas                 4            14             37            0.18
devanshkv                        4            31             18            0.17
jkania7                         13           215            281            1.72
josephwkania                    18           433             94            1.83
wcfiore                          2           185             21            0.72

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Devansh Agarwal            2898           33.4          3.4                6.25
Kshitij Aggarwal           3004           39.3          1.8                6.23
jkania7                     100           46.5          3.8                4.00
josephwkania                222           51.3          0.4               20.72
wcfiore                       7            3.8          0.3                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/mnras/staa1927 is OK
- 10.1111/j.1745-3933.2010.00882.x is OK
- 10.1109/MCSE.2007.55 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1071/AS04022 is OK
- 10.1145/2833157.2833162 is OK
- 10.1111/j.1365-2966.2012.20622.x is OK
- 10.1093/mnras/staa1856 is OK

MISSING DOIs

- 10.1109/mcse.2011.37 may be a valid DOI for title: The NumPy array: a structure for efficient numerical computation

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02610/joss.02610/10.21105.joss.02610.pdf)

**Comment by kthyng** [comment]
> Failed to discover a `Statement of need` section in paper

@KshitijAggarwal Please add in a statement of need

**Comment by kthyng** [comment]
@xuanxu, @harpolea, @dfm Could one of you take this on? You all have several submissions and I can't tell if one of you is more closely related. Thanks!

**Comment by KshitijAggarwal** [comment]
@kthyng Added statement of need, and fixed DOIs
 https://github.com/thepetabyteproject/your/commit/e36938e008689d9280267db2057d01b9cc226835, https://github.com/thepetabyteproject/your/commit/e70a4a19abc131e4bee66705a7f9d4341decd923

**Comment by KshitijAggarwal** [comment]
Suggestions for reviewers: hpparvi, olebole

**Comment by dfm** [comment]
@kthyng: Sorry - I missed this! I'm happy to edit this submission.

**Comment by dfm** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
:wave: @olebole: Are you available to review this one? (I know you just recently finished your previous review so no worries if this is too much!)

**Comment by dfm** [comment]
@pravirkr has agreed to act as a reviewer - thanks! Once we have a second, I'll get the review started.

**Comment by dfm** [comment]
@whedon assign @pravirkr as reviewer

**Comment by whedon** [comment]
OK, @pravirkr is now a reviewer

**Comment by olebole** [comment]
@dfm sorry, too busy in the moment. I'd look however forward next time!

**Comment by KshitijAggarwal** [comment]
@dfm Is any information required from my end on this?

**Comment by dfm** [comment]
Nope. Just working on finding a second reviewer. I'll let you know as soon as I do.

**Comment by dfm** [comment]
I'm still working on finding a second reviewer over here (perhaps because many people are starting their semester right now!). Thanks for your patience!

**Comment by dfm** [comment]
@paulray has agreed to act as the second reviewer. Thanks, Paul! I'll add him and then we'll get the review started in a new thread.

all: Let me know if you have any questions as we go. Thanks again for your patience!

**Comment by dfm** [comment]
@whedon add @paulray as reviewer

**Comment by whedon** [comment]
OK, @paulray is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2750.
