### ISSUE TITLE
[PRE REVIEW]: Psifr: Analysis and visualization of free recall data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2612]
**Submitting author:** @mortonne (<a href="http://orcid.org/0000-0002-2631-2710">Neal Morton</a>)
**Repository:** <a href="https://github.com/mortonne/psifr" target ="_blank">https://github.com/mortonne/psifr</a>
**Version:** v0.4.2
**Editor:** @cMadan
**Reviewers:** @samhforbes, @paxtonfitzpatrick
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mortonne. **Currently, there isn't an JOSS editor assigned** to your paper.

@mortonne if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (420.8 files/s, 36861.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          18            460            649           1231
reStructuredText                14            216            238            293
Markdown                         4             58              0            217
TeX                              1             10              0            182
JSON                             1             22              0            138
MATLAB                           3             22             77            129
YAML                             4             12             12            126
make                             1              4              7              9
Bourne Shell                     1              1              0              4
-------------------------------------------------------------------------------
SUM:                            47            805            983           2329
-------------------------------------------------------------------------------


Statistical information for the repository '2612' was gathered on 2020/08/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Neal Morton                    187          4703           2389          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Neal W Morton              2314          100.0          3.7                5.96
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1006/jmla.2001.2798 is OK
- 10.1037/a0014420 is OK
- 10.1037/a0022475 is OK
- 10.1016/j.jml.2015.10.002 is OK
- 10.1101/lm.041178.115 is OK
- 10.1016/j.neuroimage.2016.12.049 is OK
- 10.21105/joss.00424 is OK
- 10.5281/zenodo.3993412 is OK
- 10.5281/zenodo.3767070 is OK

MISSING DOIs

- 10.1037/h0045106 may be a valid DOI for title: The serial position effect of free recall
- 10.3758/bf03197276 may be a valid DOI for title: Associative retrieval processes in free recall

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02612/joss.02612/10.21105.joss.02612.pdf)

**Comment by kthyng** [comment]
Hi @jni! Are you interested and able to edit this submission? I think it is in your general expertise...

**Comment by kthyng** [comment]
@whedon invite @jni as editor

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by mortonne** [comment]
Here are some potential reviewers:
* cMadan
* janfreyberg
* snastase
* neuromusic
* JonathanReardon

**Comment by mortonne** [comment]
The article proof looks right.

**Comment by jni** [comment]
@kthyng I'm bandwidth-limited at the moment and currently editing two other manuscripts, so I won't be able to edit this one for now.

**Comment by kthyng** [comment]
@jni ok got it! I've marked you more appropriately on the AEIC table too to limit the pings you get.

**Comment by kthyng** [comment]
@cMadan would you be able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @cmadan as editor

**Comment by danielskatz** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by danielskatz** [comment]
👋 @cMadan - just a reminder... (and the notification last time may not have worked for some reason)

**Comment by cMadan** [comment]
@danielskatz, sure, am happy to edit this one. (The notification didn't come through last time.)

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@snastase @jeremymanning @samhforbes, would you be available and interested in reviewing this submission?

**Comment by jeremymanning** [comment]
@cMadan I’m super time-limited at the moment.  I could probably start taking a look sometime in October or November, so feel free to reach out then if you’re still having trouble finding reviewers.  But if you’re able to find someone who can turn this around faster I suggest going with them.  You might reach out to @andrewheusser and/or @paxtonfitzpatrick, who were both developers of our lab’s (related) [quail](cdl-quail.readthedocs.io) toolbox, also published in JOSS.

**Comment by samhforbes** [comment]
It's a little outside of my area @cMadan, but it looks interesting and I'm happy to have a look if you're happy to have me.

**Comment by cMadan** [comment]
@andrewheusser @paxtonfitzpatrick, if either of you are available, it would great to have you as a reviewer here!

@jeremymanning, thanks for that offer. I'll see if I can get someone that's more available but will ping you again in a few weeks if I still need another reviewer.

@samhforbes, great, thank you! If you find some of the demos need a bit more explaining to make sense to you, that will probably make the demo better in the end anyway! (For now though, wait until I start the actual review--which will be after finding a second reviewer.)

**Comment by cMadan** [comment]
@whedon add @samhforbes as reviewer

**Comment by whedon** [comment]
OK, @samhforbes is now a reviewer

**Comment by paxtonfitzpatrick** [comment]
@cMadan I'd be happy to review this 🙂

**Comment by cMadan** [comment]
@paxtonfitzpatrick, great, thank you!

@mortonne @samhforbes @paxtonfitzpatrick, I will go ahead and start the review now. Our friendly bot friend will be closing this issue and making a new one for us to do the actual review in, along with the instructions and checklists. Please comment there and tag me if you have any questions as things go along :).

**Comment by cMadan** [comment]
@whedon add @paxtonfitzpatrick as reviewer

**Comment by whedon** [comment]
OK, @paxtonfitzpatrick is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2669.
