### ISSUE TITLE
[PRE REVIEW]: Moran Pycess: a Python package to simulate Moran processes driven by game theory

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2613]
**Submitting author:** @AngryMaciek (<a href="http://orcid.org/0000-0003-1361-7301">Maciej Bak</a>)
**Repository:** <a href="https://github.com/AngryMaciek/angry-moran-simulator" target ="_blank">https://github.com/AngryMaciek/angry-moran-simulator</a>
**Version:** v1.0.0
**Editor:** @majensen
**Reviewers:** @xin-huang, @tkchafin
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @AngryMaciek. **Currently, there isn't an JOSS editor assigned** to your paper.

@AngryMaciek if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2613 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2613 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.17 s (131.2 files/s, 34496.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          10            303            486           2428
SVG                              1              0              0            778
Markdown                         7            148              0            451
Jupyter Notebook                 1              0            712            384
YAML                             3             12             29             55
-------------------------------------------------------------------------------
SUM:                            22            463           1227           4096
-------------------------------------------------------------------------------


Statistical information for the repository '2613' was gathered on 2020/08/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Maciej Bak                      79          4508           1291          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Maciek Bąk                 3217          100.0          0.2               15.11
```

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02613/joss.02613/10.21105.joss.02613.pdf)

**Comment by kthyng** [comment]
@majensen Are you able to and interested in taking this submission on? I see you already have a number of submissions you are handling, but it also looks like a good fit for you.

**Comment by kthyng** [comment]
@whedon invite @majensen as editor

**Comment by whedon** [comment]
@majensen has been invited to edit this submission.

**Comment by majensen** [comment]
@whedon add @majensen as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by majensen** [comment]
@whedon set @majensen as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by majensen** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
Thanks @kthyng - looks interesting. Moran models take me back to my misspent youth.

**Comment by majensen** [comment]
@AngryMaciek - thanks for this interesting submission. Do you happen to have any suggestions for reviewers? 
There is a [long list](https://bit.ly/joss-reviewers) of people who have agreed to review that you can consider. Much appreciated.

**Comment by majensen** [comment]
@spond - it has been a long time! Would you be willing to perform a software review of [this work](#2613) for the [Journal of Open Source Software](https://joss.theoj.org)? All reviews are performed openly and online in GitHub; an overview of the expectations are [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

It would be great to have your popgen expertise on this work. If you have any suggestions for others, that would be great too. Please reply in this issue thread. Thanks for your consideration -- @majensen

**Comment by majensen** [comment]
@RHagenson - reaching out to see if you would have time and interest in reviewing [this work](#2613) for [JOSS](https://joss.theoj.org). Thanks for your consideration!

**Comment by AngryMaciek** [comment]
@majensen Thanks for the editorial effort you put in.
I am not from the field of population biology (unlike the second author, who is the brain behind this operation) so unfortunately, I do not have any suggestions...
@rozmanowna - could you please take a look at the list of potential reviewers?

**Comment by rozmanowna** [comment]
Thank you @majensen! 
Based on the list, I would also suggest @xin-huang, @dwinter and @tkchafin for potential reviewers.

**Comment by xin-huang** [comment]
I am happy to review.

**Comment by tkchafin** [comment]
Also happy to review if needed - Tyler

**Comment by majensen** [comment]
@xin-huang and @tkchafin Thanks very much for stepping up -- I agree with @rozmanowna that you both would bring excellent experience to this review. Please refresh your memories regarding the [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). I will assign you as reviewers and then begin the review. The review proper will take place in a separate GitHub issue. 
Much apppreciated!

**Comment by majensen** [comment]
@spond, @rhagenson - we have found reviewers for this work. Thanks for your consideration.
--@majensen

**Comment by majensen** [comment]
@whedon assign @xin-huang as reviewer

**Comment by whedon** [comment]
OK, @xin-huang is now a reviewer

**Comment by majensen** [comment]
@whedon add @tkchafin as reviewer

**Comment by whedon** [comment]
OK, @tkchafin is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2643.

**Comment by majensen** [comment]
@xin-huang @tkchafin @AngryMaciek (and @rozmanowna ) , the review will proceed over in #2643 -- thanks!
