### ISSUE TITLE
[PRE REVIEW]: subMALDI: an open framework R package for processing irregularly-spaced mass spectrometry data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2617]
**Submitting author:** @wesleyburr (<a href="http://orcid.org/0000-0002-2058-1899">Wesley Burr</a>)
**Repository:** <a href="https://github.com/wesleyburr/subMaldi" target ="_blank">https://github.com/wesleyburr/subMaldi</a>
**Version:** v1.0.0
**Editor:** @pibion
**Reviewers:** @jspaezp, @sigven
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @wesleyburr. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @pibion.

@wesleyburr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (389.5 files/s, 81667.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               29           1203            587           4134
Rmd                              2            389            399            221
TeX                              1             12              0            122
Markdown                         2             14              0             47
-------------------------------------------------------------------------------
SUM:                            34           1618            986           4524
-------------------------------------------------------------------------------


Statistical information for the repository '2617' was gathered on 2020/08/31.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02617/joss.02617/10.21105.joss.02617.pdf)

**Comment by kthyng** [comment]
Hi @pibion, the author suggested you as a possible editor. Are you up for it?

**Comment by kthyng** [comment]
@whedon invite @pibion as editor

**Comment by whedon** [comment]
@pibion has been invited to edit this submission.

**Comment by wesleyburr** [comment]
Suggested reviewers are the overlap between R and mass spectrometry:
jpaezpae@purdue.edu
bbmisraccb@gmail.com
sigven@ifi.uio.no (not mass spec, but might be a good overlap)

**Comment by pibion** [comment]
@kthyng I'm not super experienced with R, but this is a topic I'm comfortable with.  I'll go ahead and accept.

**Comment by pibion** [comment]
@whedon assign @pibion as editor

**Comment by whedon** [comment]
OK, the editor is @pibion

**Comment by pibion** [comment]
@wesleyburr I've invited your suggested reviewers and I'll post in this space as they accept or decline.  

It's taking a little while longer than usual both to find reviewers and for them to review, but we'll try to keep the process moving along :)

**Comment by jspaezp** [comment]
I would love to review this paper, sign me up! (jpaezpae@purdue.edu here)

**Comment by wesleyburr** [comment]
> @wesleyburr I've invited your suggested reviewers and I'll post in this space as they accept or decline.
> 
> It's taking a little while longer than usual both to find reviewers and for them to review, but we'll try to keep the process moving along :)

No worries - I read the announcement about the delays. The fact that you folks are working as fast as you are in this "time of COVID" is remarkable, and we're thankful for any review at any pace folks can handle.

**Comment by pibion** [comment]
@whedon add @jspaezp as reviewer

**Comment by whedon** [comment]
OK, @jspaezp is now a reviewer

**Comment by pibion** [comment]
@jspaezp great, thank you!  Once we have two more reviewers I'll start the review and a new thread with reviewer instructions at the top will get opened up.

**Comment by pibion** [comment]
:wave: @yguitton & @biswapriyamisra, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by sigven** [comment]
@pibion Sorry for my late response to this one. I'll be happy to assist with the review process.

Sincerely,
Sigve

**Comment by pibion** [comment]
@whedon add @sigven as reviewer

**Comment by whedon** [comment]
OK, @sigven is now a reviewer

**Comment by pibion** [comment]
@sigven, that's great news, thank you! Once we have one more reviewer I'll start the review and a new thread with reviewer instructions at the top will get opened up.

**Comment by yguitton** [comment]
Hi,

 I'm not a MALDI expert, si i will wait for an other opportunity to review
an other paper.

Regards

**Comment by pibion** [comment]
@yguitton thanks for letting us know!

**Comment by pibion** [comment]
:wave: @florian-huber @biswapriyamisra, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by florian-huber** [comment]
Sorry for the delayed reply. I feel I don't know enough about R and R packages to really do the job well. I hope you can find another reviewer.

**Comment by pibion** [comment]
@wesleyburr apologies, it's taking some time to find a third reviewer.  I'm working on it, but in the meantime, how do you feel about two reviewers for this project?

I prefer having three reviewers, but our current reviewers have good expertise with this subject.  I'd be okay with moving ahead with only two in this case.  How do you feel?

**Comment by wesleyburr** [comment]
> @wesleyburr apologies, it's taking some time to find a third reviewer. I'm working on it, but in the meantime, how do you feel about two reviewers for this project?
> 
> I prefer having three reviewers, but our current reviewers have good expertise with this subject. I'd be okay with moving ahead with only two in this case. How do you feel?

I don't mind at all - 3 is certainly better for perspectives, but if the 2 reviewers who agreed are ok with it, I'm happy to work with them to make the process run as smoothly as we can!

**Comment by pibion** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2694.
