### ISSUE TITLE
[PRE REVIEW]: EMBERS: Experimental Measurement of BEam Responses with Satellites

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2618]
**Submitting author:** @amanchokshi (<a href="http://orcid.org/0000-0003-1130-6390">Aman Chokshi</a>)
**Repository:** <a href="https://github.com/amanchokshi/EMBERS" target ="_blank">https://github.com/amanchokshi/EMBERS</a>
**Version:** v0.7.0
**Editor:** @mbobra
**Reviewers:** @teuben, @hasantahir
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @amanchokshi. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @mbobra.

@amanchokshi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.50 s (204.2 files/s, 117180.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             8              0              0          42162
Python                          73           2911           2561           9842
CSS                              1             11              9            312
reStructuredText                12            297            462            289
Markdown                         1             20              0             64
YAML                             2              9              0             45
DOS Batch                        1              8              1             26
TeX                              1              1              0             23
HTML                             1              0              0             23
make                             1              4              7              9
INI                              1              1              0              4
SVG                              1              0              0              1
-------------------------------------------------------------------------------
SUM:                           103           3262           3040          52800
-------------------------------------------------------------------------------


Statistical information for the repository '2618' was gathered on 2020/08/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aman Chokshi                  1467         88580          73266          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aman Chokshi              15314           17.3          2.2                9.21
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/pasa.2018.30 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02618/joss.02618/10.21105.joss.02618.pdf)

**Comment by kthyng** [comment]
Hi @mbobra! The author suggested you as editor — are you up for it?

**Comment by kthyng** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by mbobra** [comment]
@kthyng Yes! 👍

**Comment by mbobra** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
@amanchokshi Thanks for your submission! Please give me a few days to find some reviewers.

**Comment by kthyng** [comment]
@amanchokshi it's always a good idea for the author of a submission to check out the list of reviewers given to make suggestions of your own too!

**Comment by mbobra** [comment]
@whedon add @teuben as reviewer

**Comment by whedon** [comment]
OK, @teuben is now a reviewer

**Comment by amanchokshi** [comment]
Hi @mbobra, @teuben and @kthyng! Thanks for doing this.
I'm not sure how many reviewers are required for the process, but I've gone through the list and have found a couple of people who may be suitable - astrom-tom and olebole.

**Comment by mbobra** [comment]
@whedon add @hasantahir as reviewer

**Comment by whedon** [comment]
OK, @hasantahir is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2629.
