### ISSUE TITLE
[PRE REVIEW]: SCALAR - A Platform for Real-time Machine Learning Competitions on Data Streams

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2619]
**Submitting author:** @nedRad88 (<a href="http://orcid.org/0000-0001-5056-6270">Nedeljko Radulovic</a>)
**Repository:** <a href="https://github.com/nedRad88/SCALAR" target ="_blank">https://github.com/nedRad88/SCALAR</a>
**Version:** v0.1
**Editor:** @galessiorob
**Reviewers:** @GregaVrbancic, @atanikan
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @nedRad88. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @galessiorob.

@nedRad88 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.70 s (281.2 files/s, 83274.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      86           5348           2345          23062
CSS                             24            839            129          14976
SVG                              2              0              0           2959
HTML                            42            804            255           2306
Python                          15            571            392           2174
Markdown                         6            160              0            750
JSON                             9              2              0            256
YAML                             3              8              1            158
Java                             2             26             24            111
TeX                              1             17              1             92
Maven                            1              3              0             65
R                                2              9             37             57
Protocol Buffers                 2             28              4             39
Dockerfile                       1              8             13             21
-------------------------------------------------------------------------------
SUM:                           196           7823           3201          47026
-------------------------------------------------------------------------------


Statistical information for the repository '2619' was gathered on 2020/08/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
dihiaboulegane                   4            37            140            0.25
nedRad88                       122         64355           6611           99.75

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
nedRad88                  34074           52.9          0.1                7.87
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2187671.2187677 is OK

MISSING DOIs

- 10.1109/bigdata47090.2019.9006357 may be a valid DOI for title: Real-Time Machine Learning Competition on Data Streams at the IEEE Big Data 2019

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02619/joss.02619/10.21105.joss.02619.pdf)

**Comment by kthyng** [comment]
Hi @galessiorob! The author suggested you as editor — are you interested?

**Comment by kthyng** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by galessiorob** [comment]
@whedon assign @galessiorob as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by galessiorob** [comment]
👋 Hi @nedRad88

I am in the process of assigning reviewers to this submission, but if you have any suggestions for reviewers please let me know.

In the meantime, it looks like you're only missing 1 DOIs, if you could nail that one down that would be great.

Many thanks!

Basic checks:

 - [ ] There’s a general description of the software
 - [ ] The software is within the scope as research software
 - [ ] OSI-approved license: GNU General Public License (GPL)

**Comment by nedRad88** [comment]
Hi,
The paper has been updated, the missing DOI has been added.

Thanks!

**Comment by galessiorob** [comment]
@whedon assign @GregaVrbancic as reviewer

**Comment by whedon** [comment]
OK, @GregaVrbancic is now a reviewer

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02619/joss.02619/10.21105.joss.02619.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02619/joss.02619/10.21105.joss.02619.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment]
@whedon add @atanikan as reviewer

**Comment by whedon** [comment]
OK, @atanikan is now a reviewer

**Comment by galessiorob** [comment]
@atanikan & @GregaVrbancic Thank you so much for being reviewers for this paper! 

I will close this issue and generate a new one that will contain individual checklists for you to work through. Please let me know if something is not clear or if you need help in any way. Looking forward to collaborating with you! 🎉

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2676.
