### ISSUE TITLE
[PRE REVIEW]: root_numpy: The interface between ROOT and NumPy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#262]
**Submitting author:** @ndawe (<a href="http://orcid.org/0000-0003-0202-3284">Edmund Dawe</a>)
**Repository:** <a href="https://github.com/scikit-hep/root_numpy" target ="_blank">https://github.com/scikit-hep/root_numpy</a>
**Version:** 4.7.2
**Editor:** @danielskatz
**Reviewer:** @wlav

**Author instructions**

Thanks for submitting your paper to JOSS @ndawe. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ndawe if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @jakevdp - are you able to handle this submission for us?

**Comment by arfon** [comment]
@openjournals/joss-editors - would anyone else be able to handle this submission for JOSS?

**Comment by danielskatz** [comment]
I can take it

**Comment by arfon** [comment]
> I can take it

👍 many thanks @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
I'm looking for reviewer volunteers now.  @betatim, @jpivarski, and @wlav have all been suggested.  Would one of you be willing to review this paper for JOSS?  (for more info about the journal and process, see http://joss.theoj.org/about, and particularly http://joss.theoj.org/about#reviewer_guidelines)

**Comment by wlav** [comment]
Sure can do, assuming that I pass the COI threshold.

**Comment by danielskatz** [comment]
@wlav 
Did you contribute to the code?
What other potential COIs should we be concerned with?

**Comment by wlav** [comment]
No, I did not contribute nor did I use the code. However, root_numpy uses PyROOT extensively, and I was the main developer of that. Thus, I very much like root_numpy to succeed.

**Comment by danielskatz** [comment]
I don't see any COIs then.

So I will take "Sure can do" as an accept :)
and start the review process - more notifications will follow

**Comment by danielskatz** [comment]
@whedon assign @wlav as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @wlav

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/307. Feel free to close this issue now!
