### ISSUE TITLE
[PRE REVIEW]: EnhancedVolcano: Publication-ready volcano plots with enhanced colouring and labeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2622]
**Submitting author:** @kevinblighe (<a href="http://orcid.org/0000-0002-6322-6571">Kevin Blighe</a>)
**Repository:** <a href="https://github.com/kevinblighe/EnhancedVolcano" target ="_blank">https://github.com/kevinblighe/EnhancedVolcano</a>
**Version:** v1.6.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kevinblighe. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dpsanders.

@kevinblighe if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (176.6 files/s, 75084.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         1            116              0            676
R                                3            101            263            634
Rmd                              1            161            217            377
TeX                              1              0              0              6
-------------------------------------------------------------------------------
SUM:                             6            378            480           1693
-------------------------------------------------------------------------------


Statistical information for the repository '2622' was gathered on 2020/08/31.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #2622 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
👋 @kevinblighe  - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort] criteria for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
