### ISSUE TITLE
[PRE REVIEW]: SLIX: A Python package for fully automated evaluation of Scattered Light Imaging measurements on brain tissue

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2623]
**Submitting author:** @Thyre (<a href="http://orcid.org/0000-0002-1219-0310">Jan André Reuter</a>)
**Repository:** <a href="https://github.com/3d-pli/SLIX" target ="_blank">https://github.com/3d-pli/SLIX</a>
**Version:** v1.1
**Editor:** @oliviaguest
**Reviewers:** @matteomancini, @rly
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Thyre. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arokem.

@Thyre if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.22 s (41.2 files/s, 7285.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5            196            415            750
Markdown                         2             53              0            129
YAML                             1              5              0             22
TeX                              1              2              0             21
-------------------------------------------------------------------------------
SUM:                             9            256            415            922
-------------------------------------------------------------------------------


Statistical information for the repository '2623' was gathered on 2020/08/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jan Andre Reuter                57          7045           4059           97.44
Jan André Reuter                 1           166              0            1.46
Miriam Menzel                    1            61             59            1.05
Reuter, Jan Andre                1             2              2            0.04
mmenzel                          1             1              1            0.02

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jan Andre Reuter            824           11.7          0.6               10.19
Miriam Menzel                52           85.2          0.0                0.00
mmenzel                       1          100.0          0.4                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevX.10.021002 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02623/joss.02623/10.21105.joss.02623.pdf)

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Thyre** [comment]
I'd like to list up some additional potential reviewers,
- alexrockhill
- agricolab
- Athanasiamo
- rly
- madvn
- peerherholz
- matteomancini
- snastase

**Comment by danielskatz** [comment]
@Thyre - as I look for an editor, who will then look for reviewers, I wanted to share a comment that we had during our scope discussion: "Looks like it should be added on PyPI and turned into a callable library (that could also offer a CLI)"  This is just input, not a requirement.

**Comment by danielskatz** [comment]
👋 @oliviaguest - I'm sorry to ask again so soon, but could you also take on this submission?

**Comment by danielskatz** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by oliviaguest** [comment]
@danielskatz can do!

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
@Thyre can you drop some names of people who might be able to review this, please?

**Comment by oliviaguest** [comment]
@whedon add @ alexrockhill as reviewer

**Comment by whedon** [comment]
OK, @ alexrockhill is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @alexrockhill as reviewer

**Comment by whedon** [comment]
OK, @alexrockhill is now a reviewer

**Comment by oliviaguest** [comment]
@whedon remove @ alexrockhill  as reviewer

**Comment by whedon** [comment]
OK, @ alexrockhill  is no longer a reviewer

**Comment by oliviaguest** [comment]
@whedon assign @matteomancini as reviewer

**Comment by whedon** [comment]
OK, @matteomancini is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @rly as reviewer

**Comment by whedon** [comment]
OK, @rly is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2675.
