### ISSUE TITLE
[REVIEW]: DiffCapAnalyzer: A Python Package for Quantitative Analysis of Total Differential Capacity Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2624]
**Submitting author:** @nicolet5 (<a href="http://orcid.org/0000-0003-3411-7373">Nicole  Thompson</a>)
**Repository:** <a href="https://github.com/nicolet5/DiffCapAnalyzer" target ="_blank">https://github.com/nicolet5/DiffCapAnalyzer</a>
**Version:** v0.1.1
**Editor:** @jgostick
**Reviewers:** @yangbai90, @WardLT
**Archive:** <a href="https://doi.org/10.5281/zenodo.4089118" target="_blank">10.5281/zenodo.4089118</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/543dd52dffe6a9551613a8533b25247a/status.svg)](https://joss.theoj.org/papers/543dd52dffe6a9551613a8533b25247a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/543dd52dffe6a9551613a8533b25247a"><img src="https://joss.theoj.org/papers/543dd52dffe6a9551613a8533b25247a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/543dd52dffe6a9551613a8533b25247a/status.svg)](https://joss.theoj.org/papers/543dd52dffe6a9551613a8533b25247a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nicolet5/DiffCapAnalyzer" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@yangbai90, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jgostick know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nicolet5/DiffCapAnalyzer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nicolet5) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nicolet5/DiffCapAnalyzer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nicolet5) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @yangbai90 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02624/joss.02624/10.21105.joss.02624.pdf)

**Comment by jgostick** [comment]
Hi @WardLT, you asked in the 'pre-review' thread how to get started.  I have added a checklist to the top of this issues under your name...you now just check off the boxes, and give the author(s) of the package any tips on how to improve their code for any of the boxes that are not 'check-worthy'.

**Comment by WardLT** [comment]
Thanks!

**Comment by jgostick** [comment]
@whedon add @WardLT

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by jgostick** [comment]
@whedon add @WardLT as reviewer

**Comment by whedon** [comment]
OK, @WardLT is now a reviewer

**Comment by whedon** [comment]
OK, @WardLT is now a reviewer

**Comment by jgostick** [comment]
@whedon assign @yangbai90 as reviewer

**Comment by whedon** [comment]
OK, @yangbai90 is now a reviewer

**Comment by jgostick** [comment]
@whedon add @WardLT as reviewer

**Comment by whedon** [comment]
OK, @WardLT is now a reviewer

**Comment by yangbai90** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jpowsour.2015.11.070 is OK
- 10.3389/fenrg.2016.00018 is OK
- 10.1016/j.jpowsour.2009.08.094 is OK
- 10.2172/911596 is OK
- 10.1016/j.jpowsour.2013.02.012 is OK
- 10.1016/j.energy.2019.04.070 is OK
- 10.3390/batteries5030059 is OK
- 10.1016/j.est.2020.101400 is OK
- 10.1016/j.jpowsour.2004.07.021 is OK
- 10.1063/1.1686503 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by nicolet5** [comment]
@yangbai90 Hi Yang, thank you for reviewing the package and for your comments! With regards to your questions:  

1. Yes the package has autotests. You can run all the tests using `./runTests` from the root directory, or by using pytest  (see the [Running Tests](https://github.com/nicolet5/DiffCapAnalyzer#running-tests) section of the README. Additionally, I have TravisCI set up, which runs the tests every time a commit is pushed. 

2. Thank you for pointing this out! I've updated the README with another section to describe how others can contribute: [Have Any Issues? Want to Contribute?](https://github.com/nicolet5/DiffCapAnalyzer#have-any-issues-want-to-contribute)

3. I've updated the paper's "Statement of Need" section to address this point. 

Let me know if there are any other issues I need to address! 

Best, 
Nicole

**Comment by yangbai90** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02624/joss.02624/10.21105.joss.02624.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02624/joss.02624/10.21105.joss.02624.pdf) :page_facing_up: :point_left:

**Comment by yangbai90** [comment]
@nicolet5 Hi Nicole, thanks for the update.
Now, on my side, I think the paper is ready to publish.
BR
Yang

**Comment by jgostick** [comment]
Hi  @WardLT are you still available to do this review?  The other reviewer has completed their review and the author has done some updates, so your review should be even more straight-forward.

**Comment by WardLT** [comment]
Excellent! I got back from vacation on Friday and will try to get this review out as I cope with my email backlog tomorrow!

**Comment by WardLT** [comment]
The software and paper look great to me!

I'm actually looking forward to being able to use this package in my own work. So, I'd like to express my personal appreciation to the authors for making this code available!

**Comment by jgostick** [comment]
Wow, @WardLT that is the highest praise there is!  It seems that all check boxes have been satisfied, so I will start the acceptance process soon.

**Comment by nicolet5** [comment]
Thank you everyone! @WardLT I am glad this will be useful to you and I look forward to seeing how you leverage it! 

@jgostick  thank you for the suggestion, I've edited the paper by replacing the last paragraph with a better concluding remark and I agree it reads better now!

**Comment by jgostick** [comment]
Hi @nicolet5 

Here is a checklist of things for you to do next:

- [ ] Double check authors and affiliations (including ORCIDs)
- [ ] Make a release of the software with the latest changes from the review and post the version number here. This is the version that will be used in the JOSS paper.
- [ ] Archive the release on Zenodo/figshare/etc and post the DOI here.
- [ ] Make sure that the title and author list (including ORCIDs) in the archive match those in the JOSS paper.

**Comment by nicolet5** [comment]
Thanks @jgostick 

I updated the paper with everyone's ORCIDs, made a release of the software `v1.0.1`, and archived the release on Zenodo with doi `10.5281/zenodo.4089118`. Let me know if there's anything else I need to do!

**Comment by jgostick** [comment]
@whedon set 10.5281/zenodo.4089118 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4089118" target="_blank">10.5281/zenodo.4089118</a> is the archive.

**Comment by jgostick** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02624/joss.02624/10.21105.joss.02624.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02624/joss.02624/10.21105.joss.02624.pdf) :page_facing_up: :point_left:

**Comment by jgostick** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jpowsour.2015.11.070 is OK
- 10.3389/fenrg.2016.00018 is OK
- 10.1016/j.jpowsour.2009.08.094 is OK
- 10.2172/911596 is OK
- 10.1016/j.jpowsour.2013.02.012 is OK
- 10.1016/j.energy.2019.04.070 is OK
- 10.3390/batteries5030059 is OK
- 10.1016/j.est.2020.101400 is OK
- 10.1016/j.jpowsour.2004.07.021 is OK
- 10.1063/1.1686503 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1817

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1817, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
👋 @nicolet5 - this basically looks ready to go, but I have some questions about cases in the references.  I feel like Gaussian and Lorentzian should be capitalized, for example.  And lifepo4 doesn't seem correct either.  Can you fix these, by protecting the capital letters with {}s in the bib file, along with anything else similar that I didn't catch?  Then we can proceed to accept this submission

**Comment by nicolet5** [comment]
@danielskatz Thank you for pointing that out, I've fixed those two references and checked the others for similar issues. They should all be good to go now!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by danielskatz** [comment]
@whedon accept

(trying again)

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jpowsour.2015.11.070 is OK
- 10.3389/fenrg.2016.00018 is OK
- 10.1016/j.jpowsour.2009.08.094 is OK
- 10.2172/911596 is OK
- 10.1016/j.jpowsour.2013.02.012 is OK
- 10.1016/j.energy.2019.04.070 is OK
- 10.3390/batteries5030059 is OK
- 10.1016/j.est.2020.101400 is OK
- 10.1016/j.jpowsour.2004.07.021 is OK
- 10.1063/1.1686503 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1824

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1824, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1317929192609251328) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1825
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02624](https://doi.org/10.21105/joss.02624)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @nicolet5 (Nicole Thompson) and co-authors!!

And thanks to @yangbai90 & @WardLT for reviewing, and @jgostick for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02624/status.svg)](https://doi.org/10.21105/joss.02624)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02624">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02624/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02624/status.svg
   :target: https://doi.org/10.21105/joss.02624
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02624/status.svg)](https://doi.org/10.21105/joss.02624)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
