### ISSUE TITLE
[PRE REVIEW]: nap: A molecular dynamics package with parameter-optimization programs for classical and machine-learning potentials

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2625]
**Submitting author:** @ryokbys (<a href="http://orcid.org/0000-0001-8244-5844">Ryo KOBAYASHI</a>)
**Repository:** <a href="https://github.com/ryokbys/nap" target ="_blank">https://github.com/ryokbys/nap</a>
**Version:** v0.9.2
**Editor:** @usethedata
**Reviewers:** @richardjgowers, @foeroyingur
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ryokbys. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jgostick.

@ryokbys if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1063/5.0015373 is OK
- 10.1063/1.5098061 is OK
- 10.1103/PhysRevMaterials.1.053604 is OK
- 10.1016/j.commatsci.2015.11.047 is OK
- 10.1088/0965-0393/23/7/074002 is OK
- 10.1103/PhysRevB.90.024101 is OK
- 10.1021/jp401225b is OK
- 10.1109/NABIC.2009.5393690 is OK
- 10.1103/PhysRevLett.98.146401 is OK
- 10.1088/0965-0393/15/3/008 is OK
- 10.1142/S0129183197000990 is OK
- 10.1006/jcph.1995.1039 is OK
- 10.1103/PhysRevB.37.6991 is OK
- 10.1103/PhysRevB.31.5262 is OK
- 10.1103/PhysRevB.29.6443 is OK
- 10.1080/01418618408244210 is OK
- 10.1103/PhysRev.34.57 is OK

MISSING DOIs

- 10.1093/oso/9780198803195.001.0001 may be a valid DOI for title: Computer Simulation of Liquids

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.44 s (278.2 files/s, 76715.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                      81           3829           7919          40465
Python                         130           3000           4416          17592
Fortran 77                      79           1736           4817          14574
Bourne Shell                    40            585            754           3957
reStructuredText                22           1231            311           2079
C/C++ Header                    23             42              0           1240
Ruby                             7             56             82            512
TeX                              1             18              2            385
Markdown                         9            109              0            311
XML                              2              0              0            174
make                             3             12              0             23
m4                               1              7              0             18
JSON                             1              0              0             13
HTML                             1              3              0             12
-------------------------------------------------------------------------------
SUM:                           400          10628          18301          81355
-------------------------------------------------------------------------------


Statistical information for the repository '2625' was gathered on 2020/09/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ryo KOBAYASH                     1            27             26            0.06
Ryo KOBAYASHI                  534         54144          27290           99.77
kobayashi                        1           131              0            0.16

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ryo KOBAYASHI             26843           49.6         40.4               10.11
kobayashi                   124           94.7         58.3               10.48
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02625/joss.02625/10.21105.joss.02625.pdf)

**Comment by kthyng** [comment]
Hi @jgostick could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @jgostick as editor

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by ryokbys** [comment]
I'd like to list up some potential reviewers,

- masrul
- govarguz
- srmnitc
- jeffhammond
- ml-evs
- mbkumar
- ChrisDowning
- utf

**Comment by jgostick** [comment]
I just accepted another one this morning, giving me three active submissions at the moment. Can I pass?

**Comment by kthyng** [comment]
@jgostick of course.

@usethedata Are you able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @usethedata as editor

**Comment by whedon** [comment]
@usethedata has been invited to edit this submission.

**Comment by usethedata** [comment]
Possible, but I'll be a bit slower than usual.  This is end of fiscal year time in the midst of a reorganization, so my work load is a bit crazy.

**Comment by danielskatz** [comment]
Thanks - that's fine

**Comment by danielskatz** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
Apologies to all, particularly @ryokbys for delays.  I got slammed with end of fiscal year stuff and a reorganization.  I'm on this and am working on finding reviewers.

**Comment by usethedata** [comment]
@whedon add @richardjgowers as reviewer

**Comment by whedon** [comment]
OK, @richardjgowers is now a reviewer

**Comment by usethedata** [comment]
@whedon add @foeroyingur as reviewer

**Comment by whedon** [comment]
OK, @foeroyingur is now a reviewer

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2768.
