### ISSUE TITLE
[PRE REVIEW]: hawen: time-harmonic wave modeling and inversion using hybridizable discontinuous Galerkin discretization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2626]
**Submitting author:** @flofaucher (<a href="http://orcid.org/0000-0003-4958-7511">Florian Faucher</a>)
**Repository:** <a href="https://gitlab.com/ffaucher/hawen" target ="_blank">https://gitlab.com/ffaucher/hawen</a>
**Version:** v0.1.2
**Editor:** @meg-simula
**Reviewers:** @chennachaos, @yangbai90
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @flofaucher. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jedbrown.

@flofaucher if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.72 s (400.0 files/s, 141844.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                     278          10052          29918          59981
Markdown                         4             78              0            503
C                                3            153            152            468
TeX                              1             52             16            361
make                             1              3             26             18
-------------------------------------------------------------------------------
SUM:                           287          10338          30112          61331
-------------------------------------------------------------------------------


Statistical information for the repository '2626' was gathered on 2020/09/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Florian Faucher                  2           773              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Florian Faucher             773          100.0          0.0               19.79
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/geo2019-0251.1 is OK
- 10.1093/gji/ggaa009 is OK
- 10.1051/m2an/2019009 is OK
- 10.1051/m2an/2019088 is OK
- 10.1016/j.jcp.2018.05.011 is OK
- 10.1137/15M1043856 is OK
- 10.1190/segam2016-13961828.1 is OK
- 10.1190/geo2019-0527.1 is OK
- 10.1137/S0036142901384162 is OK
- 10.1137/070706616 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1007/b98874 is OK
- 10.1190/1.3238367 is OK
- 10.1046/j.1365-246X.1998.00498.x is OK
- 10.1046/j.1365-246x.1999.00967.x is OK

MISSING DOIs

- 10.1190/geo2019-0251.1 may be a valid DOI for title: A priori estimates of attraction basins for velocity model reconstruction by time-harmonic Full Waveform Inversion and Data Space Reflectivity formulation
- 10.1142/7486 may be a valid DOI for title: Waves and rays in elastic continua

INVALID DOIs

- 10.1088/1361-6420 is INVALID
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02626/joss.02626/10.21105.joss.02626.pdf)

**Comment by kthyng** [comment]
Hi @meg-simula could you take on this submission?

**Comment by kthyng** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by meg-simula** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by meg-simula** [comment]
@flofaucher Thanks for your submission to JOSS. This looks exciting, but before I reach out to reviewers, would you take another look at the JOSS stipulations regarding paper scope (in particular length): 

https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

This paper looks substantially longer than 250-1000 words.

**Comment by flofaucher** [comment]
@meg-simula 
Thank you, I must apologize it is indeed much more... 
Regarding the modifications, should I simply update a new (shorter) version of the paper directly, 
or should I submit as a new paper in JOSS?
I thank you for your time.

**Comment by meg-simula** [comment]
Thanks - I suggest you update this submission with a revised version of the paper. Perhaps some of thematerial to be cut could be included in the documentation instead?

**Comment by flofaucher** [comment]
Ok, I have updated the repository with a new version which is less than 1000 words (excluding the bibliography).
Indeed, most of the details are already in the documentation. Yet I wanted to keep the pictures which, I hope, improve the readability.

**Comment by meg-simula** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02626/joss.02626/10.21105.joss.02626.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02626/joss.02626/10.21105.joss.02626.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/geo2019-0251.1 is OK
- 10.1093/gji/ggaa009 is OK
- 10.1051/m2an/2019009 is OK
- 10.1088/1361-6420/ab3507 is OK
- 10.1051/m2an/2019088 is OK
- 10.1016/j.jcp.2018.05.011 is OK
- 10.1137/15M1043856 is OK
- 10.1190/segam2016-13961828.1 is OK
- 10.1190/geo2019-0527.1 is OK
- 10.1137/S0036142901384162 is OK
- 10.1137/070706616 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1007/b98874 is OK
- 10.1190/1.3238367 is OK
- 10.1046/j.1365-246X.1998.00498.x is OK
- 10.1046/j.1365-246x.1999.00967.x is OK

MISSING DOIs

- 10.1016/j.cma.2020.113406 may be a valid DOI for title: Adjoint-state method for Hybridizable Discontinuous Galerkin discretization:  application to the inverse acoustic wave problem
- 10.1190/geo2019-0251.1 may be a valid DOI for title: A priori estimates of attraction basins for velocity model reconstruction by time-harmonic Full Waveform Inversion and Data Space Reflectivity formulation
- 10.1142/7486 may be a valid DOI for title: Waves and rays in elastic continua

INVALID DOIs

- None
```

**Comment by meg-simula** [comment]
Hi @mikaem @chennachaos @yangbai90 @capitalaslash, would two of you like to review this submission for JOSS? 

Feel free to take a look at our reviewer guidelines here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by chennachaos** [comment]
Hi @meg-simula. Thank you for the opportunity! I am happy to review this. :)

**Comment by meg-simula** [comment]
Great @chennachaos, thanks!

**Comment by meg-simula** [comment]
@whedon assign @chennachaos as reviewer

**Comment by whedon** [comment]
OK, @chennachaos is now a reviewer

**Comment by yangbai90** [comment]
Hi @meg-simula , I'm very happy to be the reviewer.

**Comment by meg-simula** [comment]
Great, thanks @yangbai90!

**Comment by meg-simula** [comment]
@whedon add @yangbai90 as reviewer

**Comment by whedon** [comment]
OK, @yangbai90 is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2699.
