### ISSUE TITLE
[PRE REVIEW]: Xgcm: A Python Package for Analyzing Data from General Circulation Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2628]
**Submitting author:** @rabernat (<a href="http://orcid.org/0000-0001-5999-4917">Ryan Abernathey</a>)
**Repository:** <a href="https://github.com/xgcm/xgcm" target ="_blank">https://github.com/xgcm/xgcm</a>
**Version:** v.0.3.0
**Editor:** @kthyng
**Reviewers:** @koldunovn, @vrx-
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @rabernat. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@rabernat if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.32 s (157.0 files/s, 48239.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          20           1199           2251           4531
SVG                              2             40              3           1372
Jupyter Notebook                 7              0           4038            517
reStructuredText                 8            207            218            410
DOS Batch                        1             29              1            212
Markdown                         2             34              0            166
make                             1             28              6            143
YAML                             9              8             10            142
TeX                              1              9              0             95
-------------------------------------------------------------------------------
SUM:                            51           1554           6527           7588
-------------------------------------------------------------------------------


Statistical information for the repository '2628' was gathered on 2020/09/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aurélien Ponte                   1            67              7            0.32
Christopher L.P. Wol             1             3              3            0.03
Deepak Cherian                   1           195             27            0.96
Julius Busecke                   9          3968           2095           26.32
Ryan Abernathey                 86         10985           4931           69.09
Timothy Smith                   22           425            315            3.21
Willi Rath                       1             3              3            0.03
stickler-ci                      2             6              2            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aurélien Ponte               67          100.0          4.1                4.48
Deepak Cherian              195          100.0          0.0                0.00
Julius Busecke             1280           32.3         17.1                8.91
Ryan Abernathey            4687           42.7         28.6               19.69
Timothy Smith               118           27.8         12.2               12.71
Willi Rath                    3          100.0          6.4               33.33
jbusecke                   1631          100.0         14.6                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1029/2019GL082692 is OK
- 10.1126/sciadv.aav5014 is OK
- 10.1029/2019MS001805 is OK
- 10.31223/osf.io/fqs7g is OK
- 10.5194/gmd-8-3071-2015 is OK

MISSING DOIs

- 10.5334/jors.148 may be a valid DOI for title: xarray: ND labeled arrays and datasets in Python
- 10.25080/majora-7b98e3ed-013 may be a valid DOI for title: Dask: Parallel computation with blocked algorithms and task scheduling

INVALID DOIs

- https://doi.org/10.1016/B978-0-12-460817-7.50009-4 is INVALID because of 'https://doi.org/' prefix
- <a class="libx-autolink" href="http://rd8hp6du2b.search.serialssolutions.com/?url_ver=Z39.88-2004&amp;rft_val_fmt=info:ofi/fmt:kev:mtx:journal&amp;__char_set=utf8&amp;rft_id=info:doi/10.21105/joss.01506&amp;rfr_id=info:sid/libx&amp;rft.genre=article">10.21105/joss.01506</a> is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02628/joss.02628/10.21105.joss.02628.pdf)

**Comment by kthyng** [comment]
Hi @rabernat! It's great to see `xgcm` here! I'll be your editor. 

Can you start by checking out the doi's noted above as possible problems, and then suggest reviewers either from your own network and/or from the [list of volunteers](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing). The best reviewers would be present or future users of xgcm who have not been involved with the development.

**Comment by kthyng** [comment]
@whedon add @kthyng as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kthyng** [comment]
@whedon assign @kthyng as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by rabernat** [comment]
Thanks @kthyng!

> Can you start by checking out the doi's noted above as possible problems

I have fixed the DOIs on the master branch.

> The best reviewers would be present or future users of xgcm who have not been involved with the development.

Based on your guidance and the spreadsheet, I would suggest

- @sadielbartholomew
- @edoddridge
- @koldunovn
- @wingtorres

Additional possible reviewers who are not on the JOSS list could be

- @vrx-
- @emmomp

**Comment by kthyng** [comment]
Sorry for the github pings everyone! (we list github handles without the "@" to not email people at this stage to limit noise for potential reviewers, but I forgot to say that)

I am going to narrow down @rabernat's list, especially to avoid people who are already actively reviewing for us!

@koldunovn and @vrx- would you be interested in reviewing this package? The review process is all on github and is focused on the code itself. We're asking for reviews within 5-6 weeks (longer than usual due to the on-going pandemic). You can find more information [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

@vrx- I know you have already used xgcm so I'm hoping you can go into depth in particular in your feedback. 
@koldunovn I hope that you haven't used xgcm before but do use ocean models since then you would be a good sample future user for such a package.

**Comment by rabernat** [comment]
> (we list github handles without the "@" to not email people at this stage to limit noise for potential reviewers, but I forgot to say that)

Makes sense. Sorry for my blunder!

**Comment by koldunovn** [comment]
Hello, everyone. Sure, I will do the review. Might not be very fast, but hope to manage in 5-6 weeks.

**Comment by vrx-** [comment]
Yes, I will do the review.

**Comment by kthyng** [comment]
Excellent! We can move forward with our two reviewers.

**Comment by kthyng** [comment]
@whedon assign @koldunovn as reviewer

**Comment by kthyng** [comment]
@whedon add @vrx- as reviewer

**Comment by whedon** [comment]
OK, @vrx- is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2631.

**Comment by kthyng** [comment]
@koldunovn and @vrx- the review itself will occur over in #2631.
