### ISSUE TITLE
[PRE REVIEW]: Windrose

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#263]
**Submitting author:** @scls19fr (<a href="http://orcid.org/0000-0001-9987-4338">Sébastien Celles</a>)
**Repository:** <a href="https://github.com/python-windrose/windrose/" target ="_blank">https://github.com/python-windrose/windrose/</a>
**Version:** 1.6
**Editor:** @arfon
**Reviewer:** @tacaswell

**Author instructions**

Thanks for submitting your paper to JOSS @scls19fr. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@scls19fr if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by scls19fr** [comment]
Given the fact that this library is written using Python language and deals with plotting @tacaswell @desilinguist are probably potential reviewers

**Comment by tacaswell** [comment]
:wave: I can review this.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @tacaswell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @tacaswell

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/268. Feel free to close this issue now!

**Comment by arfon** [comment]
@tacaswell - thanks for volunteering to review this and #267. Please don't feel like you need to do these in parallel!!
