### ISSUE TITLE
[PRE REVIEW]: DeepReg: a deep learning toolkit for medical image registration

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2633]
**Submitting author:** @mathpluscode (<a href="http://orcid.org/0000-0002-1184-7421">Yunguan Fu</a>)
**Repository:** <a href="https://github.com/DeepRegNet/DeepReg" target ="_blank">https://github.com/DeepRegNet/DeepReg</a>
**Version:** v0.1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @ethanwharris, @lbrea, @zhangfanmark
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mathpluscode. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arokem.

@mathpluscode if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.03 s (195.2 files/s, 20620.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          91           2047           3226           8415
Markdown                        38            934              0           2644
YAML                            35             33             37            833
Jupyter Notebook                 1              0            839            808
SVG                              6              0              0            367
reStructuredText                25            227            245            259
TeX                              1             26              0            222
DOS Batch                        1              8              1             26
TOML                             1              0              0             16
make                             1              4              7              9
INI                              1              0              0              4
-------------------------------------------------------------------------------
SUM:                           201           3279           4355          13603
-------------------------------------------------------------------------------


Statistical information for the repository '2633' was gathered on 2020/09/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adria                           30          2514           1582            5.80
MathPlusCode                     2             2              6            0.01
Nina Montana Brown              39          2257            639            4.10
Qianye Yang                     15           434             83            0.73
RemiDelaunay                    40          1982            501            3.52
Shaheer U Saeed                121          5066           1793            9.72
Yipeng Hu                       54          1997           1302            4.67
Yunguan Fu                     375         27021          20856           67.82
Zachary Baum                    15           732            297            1.46
ZheMin                          14           158             62            0.31
agrimw                           8           747             92            1.19
agrimwood                        1             2              2            0.01
ebonmati                        22           375             90            0.66

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adria                       926           36.8          1.1               12.85
MathPlusCode                  1           50.0          1.5                0.00
Nina Montana Brown         1198           53.1          1.9               16.36
Qianye Yang                 100           23.0          1.2               14.00
RemiDelaunay                770           38.8          1.3               10.39
Shaheer U Saeed            1327           26.2          1.5               20.65
Yipeng Hu                   858           43.0          0.8                8.86
Yunguan Fu                 7689           28.5          1.8               12.16
Zachary Baum                494           67.5          1.7               11.13
ZheMin                       73           46.2          1.4               10.96
agrimw                      237           31.7          1.2               13.50
ebonmati                     64           17.1          0.7               10.94
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02633/joss.02633/10.21105.joss.02633.pdf)

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.3835682 is OK
- 10.5281/zenodo.3715652 is OK

MISSING DOIs

- 10.1109/isbi.2018.8363756 may be a valid DOI for title: Label-driven weakly-supervised learning for multimodal deformable image registration
- 10.1016/j.media.2018.11.010 may be a valid DOI for title: A deep learning framework for unsupervised affine and deformable image registration
- 10.1109/tmi.2019.2897538 may be a valid DOI for title: VoxelMorph: a learning framework for deformable medical image registration
- 10.1016/j.media.2019.07.006 may be a valid DOI for title: Unsupervised learning of probabilistic diffeomorphic registration for images and surfaces
- 10.1016/j.cmpb.2018.01.025 may be a valid DOI for title: NiftyNet: a deep-learning platform for medical imaging
- 10.1109/cvpr.2016.90 may be a valid DOI for title: Deep residual learning for image recognition
- 10.1016/j.neuroimage.2007.07.007 may be a valid DOI for title: A fast diffeomorphic image registration algorithm
- 10.1016/j.neuroimage.2008.10.040 may be a valid DOI for title: Diffeomorphic demons: Efficient non-parametric image registration
- 10.1007/978-3-658-29267-6_53 may be a valid DOI for title: Deep Groupwise Registration of MRI Using Deforming Autoencoders
- 10.1109/42.796284 may be a valid DOI for title: Nonrigid registration using free-form deformations: application to breast MR images
- 10.1002/mp.12268 may be a valid DOI for title: REtroSpective Evaluation of Cerebral Tumors (RESECT): A clinical database of pre-operative MRI and intra-operative ultrasound in low-grade glioma surgeries

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @mathpluscode! Thanks for your submission. There are a few things to take care of before proceeding with the review: 

- Need a statement of need in the paper
- your paper is far too long. As stated in the [docs](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), it should be 250–1000 words.
- you can see the doi's listed above are missing; please fix this.

**Comment by kthyng** [comment]
@arokem Do you have bandwidth for handling a JOSS submission right now? We have you marked as "somewhat able" but I seem to remember maybe that is overstating it.

**Comment by kthyng** [comment]
@whedon invite @arokem as editor

**Comment by whedon** [comment]
@arokem has been invited to edit this submission.

**Comment by mathpluscode** [comment]
Hi @kthyng, thanks for the advice! We will fix this now ;)

**Comment by mathpluscode** [comment]
Hi @kthyng, for the reference, does every reference have to have a DOI? Is it ok if some references do not have DOI? Thx!

**Comment by mathpluscode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02633/joss.02633/10.21105.joss.02633.pdf)

**Comment by kthyng** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-030-32245-8_45 is OK
- 10.1016/j.media.2018.07.002 is OK
- 10.1109/ISBI.2018.8363756 is OK
- 10.1016/j.media.2018.11.010 is OK
- 10.1109/TMI.2019.2897538 is OK
- 10.1016/j.cmpb.2018.01.025 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1016/j.neuroimage.2008.10.040 is OK
- 10.1088/0031-9155/46/3/201 is OK
- 10.1007/s00138-020-01066-5 is OK
- 10.1088/1361-6560/ab843e is OK
- 10.1007/978-3-658-29267-6_53 is OK
- 10.1109/42.796284 is OK
- 10.5281/zenodo.3835682 is OK
- 10.1002/mp.12268 is OK
- 10.5281/zenodo.3715652 is OK

MISSING DOIs

- 10.1016/j.media.2019.07.006 may be a valid DOI for title: Unsupervised learning of probabilistic diffeomorphic registration for images and surfaces
- 10.1016/j.neuroimage.2007.07.007 may be a valid DOI for title: A fast diffeomorphic image registration algorithm

INVALID DOIs

- None
```

**Comment by mathpluscode** [comment]
@kthyng We are fixing these two DOI now.

**Comment by kthyng** [comment]
> For the reference, does every reference have to have a DOI? Is it ok if some references do not have DOI?

Any reference that has a doi needs to include it in your references. It looks like there are two more missing to consider above. If they are correct, they need to be included.

> * We've also changed the title from "DeepReg: a deep-learning toolkit for medical image registration" to "DeepReg: a deep learning toolkit for medical image registration", remove the hyphen between deep and learning. Hope it's fine.

I have updated this.

**Comment by mathpluscode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-030-32245-8_45 is OK
- 10.1016/j.media.2018.07.002 is OK
- 10.1109/ISBI.2018.8363756 is OK
- 10.1016/j.media.2018.11.010 is OK
- 10.1109/TMI.2019.2897538 is OK
- 10.1016/j.media.2019.07.006 is OK
- 10.1016/j.cmpb.2018.01.025 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1016/j.neuroimage.2007.07.007 is OK
- 10.1016/j.neuroimage.2008.10.040 is OK
- 10.1088/0031-9155/46/3/201 is OK
- 10.1007/s00138-020-01066-5 is OK
- 10.1088/1361-6560/ab843e is OK
- 10.1007/978-3-658-29267-6_53 is OK
- 10.1109/42.796284 is OK
- 10.5281/zenodo.3835682 is OK
- 10.1002/mp.12268 is OK
- 10.5281/zenodo.3715652 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mathpluscode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02633/joss.02633/10.21105.joss.02633.pdf)

**Comment by mathpluscode** [comment]
> > For the reference, does every reference have to have a DOI? Is it ok if some references do not have DOI?
> 
> Any reference that has a doi needs to include it in your references. It looks like there are two more missing to consider above. If they are correct, they need to be included.
> 
> > * We've also changed the title from "DeepReg: a deep-learning toolkit for medical image registration" to "DeepReg: a deep learning toolkit for medical image registration", remove the hyphen between deep and learning. Hope it's fine.
> 
> I have updated this.

Hi, @kthyng, we've fixed the DOIs.

**Comment by kthyng** [comment]
@arokem Totally understand! No worries!

**Comment by kthyng** [comment]
Hey @Kevin-Mattheus-Moerman! Could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
@Kevin-Mattheus-Moerman has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by mathpluscode** [comment]
Hi @kthyng @Kevin-Mattheus-Moerman,

Is there anything we need to do from author part? Or we just need to be patient and wait for the submission to be under review?

Thx!

**Comment by Kevin-Mattheus-Moerman** [comment]
@mathpluscode at this point I'm looking for reviewers for this submission and will invite some shortly. If you have any suitable reviewers in mind please suggest them here (remove the @ when you quote GitHub handles).

**Comment by mathpluscode** [comment]
> @mathpluscode at this point I'm looking for reviewers for this submission and will invite some shortly. If you have any suitable reviewers in mind please suggest them here (remove the @ when you quote GitHub handles).

@Kevin-Mattheus-Moerman I checked the reviewer lists and maybe we'd like to suggest ethanwharris, mamrehn, billchenxi.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mathpluscode thanks. I'll check those out. FYI they needn't be just from that list, I can also invite new reviewers

**Comment by mathpluscode** [comment]
> @mathpluscode thanks. I'll check those out. FYI they needn't be just from that list, I can also invite new reviewers

@Kevin-Mattheus-Moerman sure! We will ask around and recommend more if people are available. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@stefanklein @mstaring @thewtex @ljod @fedorov @ethanwharris @mamrehn @billchenxi as editor for the [Journal of Open Source Software (JOSS)](https://joss.theoj.org/) I'd like to invite you to review _"DeepReg: a deep learning toolkit for medical image registration"_. 

You can comment here to let me know if you are interested. Thanks! 

We have a smooth GitHub based [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) which focuses on [the software :computer: ](https://github.com/DeepRegNet/DeepReg) as well as [the very short paper :page_facing_up: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02633/joss.02633/10.21105.joss.02633.pdf). 

This here is a "pre-review issue". Once I've attracted sufficient reviewers I'll initiate a review issue where reviewers have a set of check-boxes to guide them through the review process.  

Check out [our documentation](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) to learn more about what it is like to review for JOSS, also here is an example review process for a different submission which you can look at: 
https://github.com/openjournals/joss-reviews/issues/2520

Thanks!

**Comment by ethanwharris** [comment]
Hi @Kevin-Mattheus-Moerman, I'd be happy to review this :smiley:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @ethanwharris as reviewer

**Comment by whedon** [comment]
OK, @ethanwharris is now a reviewer

**Comment by mstaring** [comment]
I am less into the code with this, but perhaps @hsokooti may be interested.

**Comment by stefanklein** [comment]
Hi, thanks for the invitation to review. I hadn't heard about this journal. The concept seems very interesting! Unfortunately I won't have time to do this review and thoroughly test the code. A postdoc from my group with experience in image registration and deep learning would be interested in doing the review, so please consider inviting her: @lbrea . Best regards, Stefan

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @stefanklein, that is fine. @lbrea would you be able to review this work? Let me know and I can add you, thanks!

**Comment by lbrea** [comment]
Yes, please feel free to add me for the review

Best,

Luisa

**Comment by fedorov** [comment]
Sorry for the delay in responding. I don't think I will be able to make time to do a proper review with everything else going on this Fall. I also don't have a student to delegate.

**Comment by ljod** [comment]
I cannot review either but my colleague Fan Zhang can review. @zhangfanmark

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @lbrea as reviewer

**Comment by whedon** [comment]
OK, @lbrea is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @zhangfanmark as reviewer

**Comment by whedon** [comment]
OK, @zhangfanmark is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2705.
