### ISSUE TITLE
[PRE REVIEW]: Empirical and non-parametric copula models with the `cort` R package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2634]
**Submitting author:** @lrnv (<a href="http://orcid.org/0000-0002-7508-999X">Oskar Laverny</a>)
**Repository:** <a href="https://github.com/lrnv/cort" target ="_blank">https://github.com/lrnv/cort</a>
**Version:** 0.3.1
**Editor:** @pdebuyl
**Reviewers:** @coatless, @agisga
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lrnv. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @csoneson.

@lrnv if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (734.7 files/s, 51936.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               27            375            603           1209
C++                             11             75             39            517
YAML                             5             37             34            184
Markdown                         7             69              0            159
Rmd                              4            185            202            144
TeX                              2             12              0            134
CSS                              1             17              0             80
HTML                             1              4              0             21
-------------------------------------------------------------------------------
SUM:                            58            774            878           2448
-------------------------------------------------------------------------------


Statistical information for the repository '2634' was gathered on 2020/09/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Oskar Laverny                   17           999            368          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Oskar Laverny               631           63.2          0.5                6.18
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/j.ejor.2015.06.028 may be a valid DOI for title: Convergence results for patchwork copulas
- 10.1080/03610926.2017.1285929 may be a valid DOI for title: Density estimation via the random forest method
- 10.1016/j.jmva.2016.07.003 may be a valid DOI for title: Evading the curse of dimensionality in nonparametric density estimation with simplified vine copulas

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02634/joss.02634/10.21105.joss.02634.pdf)

**Comment by kthyng** [comment]
Hi @lrnv, thanks for your submission. Upon looking through your paper, I see that it does not [have](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)

> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.

I cannot as a non-expert in your field understand enough to pass this onto a handling editor. Please make this change and ping back here when that is finished. While you are at it, please add the missing doi's listed above, too.

**Comment by lrnv** [comment]
I did correct the DOIs and rework the paper. Tell me if you think it's still not clear -- As the software solves a research-level problem, it's quite hard to describe to non-specialist, but i tried.

@whedon generate pdf

**Comment by lrnv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02634/joss.02634/10.21105.joss.02634.pdf)

**Comment by lrnv** [comment]
Forgot to push..

@whedon generate pdf

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02634/joss.02634/10.21105.joss.02634.pdf)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02634/joss.02634/10.21105.joss.02634.pdf)

**Comment by lrnv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02634/joss.02634/10.21105.joss.02634.pdf)

**Comment by lrnv** [comment]
@kthyng What do you think about this last version ? If this is still not enough, i'll rethink it dont hesitate to tell me. 

Thanks for taking care of that :)

**Comment by kthyng** [comment]
@lrnv I think that works, thanks.

**Comment by kthyng** [comment]
@pdebuyl Are you willing to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@coatless @emilyriederer @agisga would you review the paper "Empirical and non-parametric copula models with the `cort` R package" for the Journal of Open Source Software?

**Comment by agisga** [comment]
Hi @pdebuyl, I would be interested to review this paper but am not sure whether I can find sufficient amount of time for it in the next couple of weeks. What would be the review timeline (duration)?

**Comment by emilyriederer** [comment]
Hi @pdebuyl , I would love to help and this project looks very interesting. Unfortunately, I'd have to admit that it is far enough out of my domain that I worry I would add much of substance.

**Comment by pdebuyl** [comment]
@agisga the expected review time is currently of six weeks. It is usually a bit shorter (four weeks) but is extended until the working conditions improve in regard to the covid-19 pandemic. Let me know if that would work for you.

**Comment by pdebuyl** [comment]
@emilyriederer thank you for the quick reply! You may want to unsubscribe from this issue thread, else you will keep receiving emails while I look for other reviewers.

**Comment by coatless** [comment]
@pdebuyl more than happy to review the software! I'm excited to see an improvement in copula estimation within _R_.

**Comment by pdebuyl** [comment]
Thank you @coatless ! When the selection of a second reviewer is done, the review will start in a second github issue.

**Comment by pdebuyl** [comment]
@whedon assign @coatless as reviewer

**Comment by whedon** [comment]
OK, @coatless is now a reviewer

**Comment by agisga** [comment]
Hi @pdebuyl , thank you, with a review time of 6 weeks I am available to review this submission.

**Comment by pdebuyl** [comment]
Thank you @agisga !

**Comment by pdebuyl** [comment]
@whedon add @agisga as reviewer

**Comment by whedon** [comment]
OK, @agisga is now a reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2653.
