### ISSUE TITLE
[PRE REVIEW]: UVehavior: An Annotation Desktop-Tool for Behavioral Observation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2635]
**Submitting author:** @Manolomon (<a href="http://orcid.org/0000-0002-3398-2632">J. Manuel Pérez-Verdejo</a>)
**Repository:** <a href="https://github.com/Manolomon/uvehavior-desktop" target ="_blank">https://github.com/Manolomon/uvehavior-desktop</a>
**Version:** v1.0.0
**Editor:** @marcosvital
**Reviewers:** @SteveViss, @62442katieb
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Manolomon. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @cMadan.

@Manolomon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.12 s (1260.6 files/s, 54636.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TypeScript                      71            426            129           3009
HTML                            25              9              1            682
Sass                            23            145              3            678
JSON                            14              0              0            588
Markdown                         3             80              0            236
JavaScript                       5             11              6            100
TeX                              1              6              0             85
SQL                              1              7              0             79
SVG                              2              0              0             30
YAML                             1              2              0             16
-------------------------------------------------------------------------------
SUM:                           146            686            139           5503
-------------------------------------------------------------------------------


Statistical information for the repository '2635' was gathered on 2020/09/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Manolo Perez                     7           240             37          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Manolo Perez                203           84.6          0.7                2.96
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/S0140525X00018653 is OK
- 10.1038/s41567-018-0093-0 is OK
- 10.1080/09637486.2019.1580680 is OK
- 10.1007/978-3-319-12742-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02635/joss.02635/10.21105.joss.02635.pdf)

**Comment by kthyng** [comment]
@marcosvital are you interested in reviewing this submission?

**Comment by kthyng** [comment]
@whedon invite @marcosvital as editor

**Comment by whedon** [comment]
@marcosvital has been invited to edit this submission.

**Comment by marcosvital** [comment]
Yes, I can review this submission, @kthyng.

**Comment by marcosvital** [comment]
@whedon assign @marcosvital as editor

**Comment by whedon** [comment]
OK, the editor is @marcosvital

**Comment by marcosvital** [comment]
Hi, @Manolomon, I will be the editor of your submission.

Please take a look on your manuscript proof, generated above, and check if everything seems to be ok with it, as it will be the version used to start revision if nothing else changes. If you make any changes, you can use [call whedon to create a new proof ](https://joss.readthedocs.io/en/latest/whedon.html#author-commands)- or just ask me to do it.

At the same time, we can start looking for reviewers for you submission. We usually ask the authors for suggestions, so let me know if you have anyone in mind that could do this - you can paste the github profile of anyone you think that could do it (but please don't tag anyone yet).
You can also check [this list of people](https://bit.ly/joss-reviewers) that have agreed to review for JOSS, and see if any of them may be suitable to review this submission.

**Comment by marcosvital** [comment]
@Manolomon, you can also tag any of your co-authors here (and also on the issue that will be created on review starts), so they can follow the process.

**Comment by Manolomon** [comment]
Hi @marcosvital, thanks for the advice!

I took a look at the list and found that the following accounts could help as reviewers, according to their area of expertise and coding experience:

- felixhenninger
- SteveViss
- arose

Unfortunately, my coauthors don't have a github account, but they are following the process through this site. 

Thank you

**Comment by marcosvital** [comment]
Thank you for the suggestions, @Manolomon, I'll contact them.

In the meantime, you can work on a couple of suggestions, while we wait to hear from the potential reviewers:
* The paper should have a "statement of need" on a separate paragraph, with it's own header (this came to be a norm on all JOSS papers recently).
* The repository need to show "clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support" (this will be one point on [reviewers' checklist](https://joss.readthedocs.io/en/latest/review_checklist.html), and I didn't see information about this as I took a look at the repository).

**Comment by marcosvital** [comment]
Dear @felixhenninger, @SteveViss and @arose, would you be willing to review this submission for JOSS?

We carry out an open checklist-driven reviews here in GitHub issues, and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review issue, and once there are enough reviewers we will move on to a new issue where the review will take place. If you are not able to review, please let us know if you have recommendations for other reviewers that could help with this submission.

**Comment by SteveViss** [comment]
Hi @marcosvital, I can do the review for this submission. Let me know when we're ready to start.

**Comment by arose** [comment]
Hi, @marcosvital, I can NOT review this submission.

**Comment by Manolomon** [comment]
Hi, @marcosvital. I just updated the repository to meet the review criteria.
And thanks to @SteveViss and @arose for their answers.

**Comment by Manolomon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02635/joss.02635/10.21105.joss.02635.pdf)

**Comment by FelixHenninger** [comment]
Thanks everyone, and apologies for the late response, I'm glad you have this covered already! 👍

**Comment by marcosvital** [comment]
Thank you so much, @SteveViss, we will let you know when you are ready.

@arose, thank you for your prompt reply.

@FelixHenninger, we actually need two or three reviewers, so let us know if you are available, ok?

**Comment by marcosvital** [comment]
Hi @Manolomon, since we still got only one confirmed reviewer, I'll try to find and contact a few more, so hopefully we will be able to move on soon.

**Comment by marcosvital** [comment]
Dear @62442katieb, would you be willing to review this submission for JOSS?

We carry out an open checklist-driven reviews here in GitHub issues, and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is still a pre-review issue, and once there are enough reviewers we will move on to a new issue where the review will take place. If you are not able to review, please let us know if you have recommendations for other reviewers that could help with this submission.

**Comment by 62442katieb** [comment]
Hi @marcosvital! Sure, I'd be happy to review this submission.

**Comment by marcosvital** [comment]
Thank you, @62442katieb! We'll move to reviewing soon, with you and @SteveViss as reviewers; a new issue will be created for that.

**Comment by marcosvital** [comment]
@whedon assign @SteveViss as reviewer

**Comment by whedon** [comment]
OK, @SteveViss is now a reviewer

**Comment by marcosvital** [comment]
@whedon add @62442katieb as reviewer

**Comment by whedon** [comment]
OK, @62442katieb is now a reviewer

**Comment by marcosvital** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2692.
