### ISSUE TITLE
[PRE REVIEW]: epair: An R package for acquiring EPA data easily

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2636]
**Submitting author:** @GLOrozcoM (<a href="http://orcid.org/0000-0002-9011-409X">George Leonard Orozco-Mulfinger</a>)
**Repository:** <a href="https://github.com/GLOrozcoM/epair" target ="_blank">https://github.com/GLOrozcoM/epair</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @GLOrozcoM. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@GLOrozcoM if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (365.1 files/s, 42898.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         3            158              0            677
R                               12             81            471            475
TeX                              1              1              0             17
-------------------------------------------------------------------------------
SUM:                            16            240            471           1169
-------------------------------------------------------------------------------


Statistical information for the repository '2636' was gathered on 2020/09/02.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1007/s13253-019-00378-y may be a valid DOI for title: Distributions of Human Exposure to Ozone During Commuting Hours in Connecticut Using the Cellular Device Network

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02636/joss.02636/10.21105.joss.02636.pdf)

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
👋 @GLOrozcoM - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
