### ISSUE TITLE
[PRE REVIEW]: Seq2Pat: Sequence-to-Pattern Generation Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2639]
**Submitting author:** @skadio (<a href="http://orcid.org/0000-0002-4672-6830">Serdar Kadioglu</a>)
**Repository:** <a href="https://github.com/fidelity/seq2pat" target ="_blank">https://github.com/fidelity/seq2pat</a>
**Version:** v1.1.1
**Editor:** @galessiorob
**Reviewers:** @HaoZeke, @shreyasbapat
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @skadio. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @terrytangyuan.

@skadio if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.30 s (190.2 files/s, 117010.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      13           4197           4041          15600
SVG                              1              0              0           2671
HTML                            10           1249             10           1658
CSS                              6            312             54           1180
Python                           5            533            630           1087
C++                              4            155             28            890
Cython                           2             75             22            210
Markdown                         2             94              0            182
C/C++ Header                     5             45             19            143
TeX                              1              7              0             71
reStructuredText                 5             59             55             57
Jupyter Notebook                 1              0            245             49
DOS Batch                        1              8              1             26
make                             1              5              6             12
TOML                             1              0              0              2
-------------------------------------------------------------------------------
SUM:                            58           6739           5111          23838
-------------------------------------------------------------------------------


Statistical information for the repository '2639' was gathered on 2020/09/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Doruk Kilitcioglu                1          3272              0            5.62
Kadioglu, Serdar                 8         13616            191           23.70
Serdar Kadioglu                  2             4              1            0.01
Wang, Xin (V3A)                 10         25918          15252           70.67

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Doruk Kilitcioglu          3146           96.1          0.0               12.97
Serdar Kadioglu           13500       337500.0          4.2               17.45
Wang, Xin (V3A)           10722           41.4          2.9               17.09
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-319-42849-9 is OK

MISSING DOIs

- 10.1609/aaai.v33i01.33011495 may be a valid DOI for title: Constraint-Based Sequential Pattern Mining with Decision Diagrams
- 10.1609/aaai.v33i01.33011495 may be a valid DOI for title: Constraint-based Sequential Pattern Mining with Decsion Diagrams
- 10.1007/978-3-319-46227-1_20 may be a valid DOI for title: An efficient algorithm for mining frequent sequence with constraint programming

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02639/joss.02639/10.21105.joss.02639.pdf)

**Comment by terrytangyuan** [comment]
Thanks for suggesting me as the editor. Unfortunately I am not available to edit this at the moment.

**Comment by kthyng** [comment]
Hi @skadio, thank you for your submission. Please update your paper to meet the JOSS [submission](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) requirement of: 

> The paper should be between 250-1000 words.

**Comment by kthyng** [comment]
Hi @galessiorob! I can't tell if your expertise in data science overlaps with this submission. Are you interested in editing?

**Comment by kthyng** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by galessiorob** [comment]
Happy to edit!
@whedon assign @galessiorob as editor

**Comment by galessiorob** [comment]
@whedon assign @galessiorob as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by skadio** [comment]
Thank you @galessiorob!

**Comment by skadio** [comment]
CC: @takojunior @aminhn @dorukkilitcioglu

**Comment by galessiorob** [comment]
👋 Hi @skadio 

I am in the process of assigning reviewers to this submission, but if you have any suggestions for reviewers please let me know.

In the meantime, it looks like you're only missing 3 DOIs, if you could nail those down that would be great.

Many thanks!

Basic checks:

 - [ ] There’s a general description of the software
 - [ ] The software is within the scope as research software
 - [ ] OSI-approved license: GNU General Public License (GPL)

**Comment by galessiorob** [comment]
@whedon assign @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, @HaoZeke is now a reviewer

**Comment by skadio** [comment]
Thank you @galessiorob and thanks to our reviewer @HaoZeke! 

On the basic checks: 

- [ ] There’s a general description of the software 
--> Indeed, a general description is available for our reviewers. 

- [ ] The software is within the scope as research software
--> This library is an outcome of a research collaboration between CMU and Fidelity and will be presented at INFORMS 2020 as an invited talk in the Machine Learning & Optimization session. 

- [ ]  OSI-approved license: GNU General Public License (GPL)
--> It's licensed under GNU GPL 

@takojunior can you take a look at the missing DOIs and update the .bib file when you get a chance?

**Comment by takojunior** [comment]
Thank you @skadio, @galessiorob, @HaoZeke!

The missing DOIs have been resolved.

**Comment by galessiorob** [comment]
@whedon add @shreyasbapat as reviewer

**Comment by whedon** [comment]
OK, @shreyasbapat is now a reviewer

**Comment by galessiorob** [comment]
🎉 Thanks for volunteering to be reviewers @shreyasbapat and @HaoZeke!

I'll generate a "review issue" that will contain individual checklists to go through, feel free to get started at your earliest convenience, don't hesitate to ask if you need clarification or help - you can @mention me directly on the issue.

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2662.
