### ISSUE TITLE
[PRE REVIEW]: Mosquitto

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#264]
**Submitting author:** ralight (<a href="http://orcid.org/0000-0001-9218-7797">Roger A. Light</a>)
**Repository:** <a href="https://github.com/eclipse/mosquitto" target ="_blank">https://github.com/eclipse/mosquitto</a>
**Version:** v1.4.11
**Editor:** @arfon
**Reviewer:** @brainstorm

**Author instructions**

Thanks for submitting your paper to JOSS ralight. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

ralight if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by brainstorm** [comment]
This is a great piece of software, I've been using it together with The Things Network lately, happy to review its paper :)

@whedon assign @brainstorm as reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @brainstorm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @brainstorm

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/265. Feel free to close this issue now!

**Comment by arfon** [comment]
@brainstorm thanks for volunteering to review this. Please head over to #265 for the review.
