### ISSUE TITLE
[PRE REVIEW]: BrainGlobe Atlas API: a common interface for neuroanatomical atlases

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2640]
**Submitting author:** @adamltyson (<a href="http://orcid.org/0000-0003-3225-1130">Adam Luke Tyson</a>)
**Repository:** <a href="https://github.com/brainglobe/bg-atlasapi" target ="_blank">https://github.com/brainglobe/bg-atlasapi</a>
**Version:** 0.2.0
**Editor:** @oliviaguest
**Reviewers:** @typically, @vitay
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @adamltyson. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jni.

@adamltyson if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2640 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2640 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by adamltyson** [comment]
cc @FedeClaudi @vigji

**Comment by adamltyson** [comment]
Is the PDF failing to compile because I gave a link to the repository branch? I couldn't work out how to specify the branch (with the paper on) when submitting.

**Comment by vigji** [comment]
I guess so, but I have no solutions to offer there..

**Comment by kthyng** [comment]
Hi @adamltyson! Thank you for your submission. Is `https://github.com/brainglobe/bg-atlasapi/tree/joss` the url of the repository you want reviewed as your submission?

**Comment by kthyng** [comment]
Hi @oliviaguest, would you be up for editing this paper, once the repo/paper situation has been worked out?

**Comment by kthyng** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by adamltyson** [comment]
Hi @kthyng, the repository is `https://github.com/brainglobe/bg-atlasapi`. `https://github.com/brainglobe/bg-atlasapi/tree/joss` is the `joss` branch that is otherwise identical to the default, but with the paper. I wasn't sure how to submit the URL to reflect this.

**Comment by kthyng** [comment]
Hi @openjournals/dev! Do I have the power to change the URL in a submission in the database, rather than just editing it in the comment above? I think what needs to happen is for the repo url to change to "https://github.com/brainglobe/bg-atlasapi" with the JOSS paper then being accessible as a branch from there.

**Comment by oliviaguest** [comment]
@kthyng sure thing! 😊

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
@whedon add @typically as reviewer

**Comment by whedon** [comment]
OK, @typically is now a reviewer

**Comment by xuanxu** [comment]
> Do I have the power to change the URL in a submission in the database, rather than just editing it in the comment above? I think what needs to happen is for the repo url to change to "https://github.com/brainglobe/bg-atlasapi" with the JOSS paper then being accessible as a branch from there.

@kthyng (sorry for the delayed response) There is no database, Whedon gets the information from the issue body, so changing the URL there (in the **repository** entry) should make it work.

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2640 with the following error: 

 Can't find any papers to compile :-(

**Comment by oliviaguest** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02640/joss.02640/10.21105.joss.02640.pdf)

**Comment by kthyng** [comment]
> @kthyng (sorry for the delayed response) There is no database, Whedon gets the information from the issue body, so changing the URL there (in the **repository** entry) should make it work.

Ok thanks @xuanxu, that makes sense. @oliviaguest thanks for updating accordingly.

**Comment by oliviaguest** [comment]
@whedon add @vitay as reviewer

**Comment by whedon** [comment]
OK, @vitay is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2668.
