### ISSUE TITLE
[REVIEW]: astrosource: automating optical astronomy measurement, calibration and analysis for variable stellar sources from provided photometry

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2641]
**Submitting author:** @mfitzasp (<a href="http://orcid.org/0000-0001-6554-1826">Michael Fitzgerald</a>)
**Repository:** <a href="https://github.com/zemogle/astrosource/" target ="_blank">https://github.com/zemogle/astrosource/</a>
**Version:** v1.5.2
**Editor:** @arfon
**Reviewer:** @zackdraper, @joshspeagle
**Archive:** <a href="https://doi.org/10.6084/m9.figshare.14113667.v1" target="_blank">10.6084/m9.figshare.14113667.v1</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9332d9711581954baddd586202bbc92b/status.svg)](https://joss.theoj.org/papers/9332d9711581954baddd586202bbc92b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9332d9711581954baddd586202bbc92b"><img src="https://joss.theoj.org/papers/9332d9711581954baddd586202bbc92b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9332d9711581954baddd586202bbc92b/status.svg)](https://joss.theoj.org/papers/9332d9711581954baddd586202bbc92b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/zemogle/astrosource/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@zackdraper & @joshspeagle, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zemogle/astrosource/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mfitzasp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zemogle/astrosource/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mfitzasp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @bsipocz, @joshspeagle it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/21672857.2017.1303264 is OK
- 10.1017/pasa.2014.30 is OK
- 10.1002/asna.201512254 is OK
- 10.3847/1538-3881/153/2/77 is OK
- 10.1088/1538-3873/ab7ee7 is OK
- 10.1017/pasa.2018.5 is OK
- 10.1088/0067-0049/219/1/12 is OK
- 10.32374/atom.2020.1.2 is OK
- 10.32374/atom.2020.1.4 is OK
- 10.1117/12.2314340 is OK
- 10.1086/673168 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1109/mcse.2011.37 is OK
- 10.1109/mcse.2007.55 is OK
- 10.3847/1538-3881/aafc33 is OK
- 10.21105/joss.00058 is OK
- 10.32374/atom.2020.1.1 is OK
- 10.1051/0004-6361:20020802 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02641/joss.02641/10.21105.joss.02641.pdf)

**Comment by arfon** [comment]
@bsipocz, @joshspeagle 

This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/2641 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

**Comment by bsipocz** [comment]
@arfon - in this the place to ask paper related questions (rather than software related)?

E.g. authorship related questions should be discussed here, for example the explicit opt in from authors, or in an issue in the repo? (I would this here is better, but there may be a guideline saying otherwise that I missed). Also, I didn't see any discussion in the guidelines about authors for whom there is no trace of contribution in the software repo. Or should the commit history on be used to determined the lead author has made significant contribution to the software?

**Comment by danielskatz** [comment]
These discussions can happen here or in issues in the repo (tagged with this issue to create a link between them).

**Comment by bsipocz** [comment]
> ... active project direction and other forms of non-code contributions are. The authors themselves assume responsibility for deciding who should be credited with co-authorship, and co-authors must always agree to be listed... 

@mfitzasp - Since you and @zemoge interacted with the JOSS submission I take it as your agreement to be authors. I don't see any interactions in the repo with the other two authors though, have they been actively agreed to be listed?

Also, I wonder whether you considered adding the third person as author, who contributing to the package, especially early on helping with setting up the package skeleton, CI, etc. Unless they fully opted out, I would appreciate if they were at least mentioned in the acknowledgement.

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.19 s (158.9 files/s, 24758.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          18            584            376           2450
TeX                              1             25              0            278
Markdown                         2            114              0            191
reStructuredText                 3            101             21            170
Jupyter Notebook                 1              0            195             65
YAML                             2              3              2             40
DOS Batch                        1              8              1             26
make                             1              4              7              9
TOML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            30            839            602           3232
-------------------------------------------------------------------------------


Statistical information for the repository '2641' was gathered on 2020/09/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Edward Gomez                    97          8541           5484           76.81
Joe Singleton                    3          1799           1765           19.52
Michael Fitzgerald              30           501            169            3.67

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Edward Gomez               2913           34.1         10.0                7.83
Joe Singleton                69            3.8         14.0                1.45
Michael Fitzgerald          428           85.4          1.1                9.58
```

**Comment by zemogle** [comment]
That's a really good call. @joesingo would you like to be an author? You helped substantially with  the `tom_astrosource` aspect as well as setting up RTD and Travis.

The last 2 authors provided development input before I was involved, and before the code was in GitHub.

**Comment by zemogle** [comment]
I've added @joesingo to the author list @bsipocz

**Comment by arfon** [comment]
:wave: @bsipocz & @joshspeagle - just wanted to check in to see how you're getting along with your reviews here?

**Comment by bsipocz** [comment]
@arfon - I got a bit swamped and dropped the ball, will try to get back to it over the weekend.

**Comment by joshspeagle** [comment]
Same situation here — I’ve been absolutely swamped but will get to it this weekend. Apologies for the delay.

**Comment by joshspeagle** [comment]
This will unfortunately be delayed even further on my end. I've recently moved internationally and, due to technical issues and quarantine requirements, it's taking longer to get internet set up at our new place than we had expected. I'm hopeful that this will be resolved in the next few days.

Sorry about the extensive delays getting this referee report in.

**Comment by arfon** [comment]
👋 @bsipocz & @joshspeagle - any chance you could try and complete your reviews in the next week or so?

**Comment by joshspeagle** [comment]
My review will be done by tomorrow. Thanks in advance to everyone for their patience.

**Comment by joshspeagle** [comment]
Review is done! Comments below:
- Documentation is functional enough to meet JOSS requirements I *think*, but definitely not super thorough. Docs seem more like they were written more as a reference and less as a guide for new users. There's also limited examples of the internal Python API that the CLI runs off of (a stated feature of the package), although there's enough stuff online and in the codebase for someone to figure it out by poking around. Adding those in would be helpful but not required.
- Automatic tests are helpful, although figuring out the outputs is nontrivial even with the explanations. Additional explicit guidance working through an example would help enormously here.
- No issues with the paper other than the figure appears to be mislabeled in the submitted PDF (it's "??" for me).
- While not a requirement for acceptance, I would encourage the author(s) to try and add more examples and documentation to make the code easier to work through. In particular, I think it's especially important to have worked-through cases illustrating for users how exactly statements like this actually work in the code: "Solutions to avoid these issues have been easily incorporated into the `astrosource` code, but would likely be cumbersome to explain manually in any given observer guide."

As most of the above issues are recommendations and not requirements, I'm happy to recommend the submission be accepted.

**Comment by zemogle** [comment]
Thanks @joshspeagle Those are really constructive comments. The docs are an on-going effort but giving worked through examples are a good idea.

I've fixed up the figure references (and the missing captions).

**Comment by zemogle** [comment]
Any news on the status of this paper @arfon ?

**Comment by arfon** [comment]
Hi @zemogle - I emailed @bsipocz a few days ago to remind them about this review. I had meant to update this thread too when I did this (but forgot 🤦).

**Comment by arfon** [comment]
:wave: @zemogle - happy new year. I just sent a final reminder to @bsipocz. If I don't hear back from them this coming week then I'll go ahead and look for a new reviewer.

**Comment by arfon** [comment]
:wave: @gusbeane @zackdraper - would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The software under review here is [_astrosource: automating optical astronomy measurement, calibration and analysis for variable stellar sources from provided photometry_](https://github.com/zemogle/astrosource/) which already has one complete review and we're looking for a second reviewer to replace @bsipocz who unfortunately isn't able to complete their review at this time.

**Comment by gusbeane** [comment]
Hi @arfon - thanks for the ping. Unfortunately the topic of this code is way out of my ballpark, and I'm a bit oversubscribed this semester (lots of coursework!). In the future I'd be willing to help review other code.

Good luck!

**Comment by zackdraper** [comment]
Sure, I'll give it a go over the weekend.  Haven't done a JOSS review before but it looks straightforward.

**Comment by arfon** [comment]
@whedon re-invite @zackdraper as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@zackdraper please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
> Sure, I'll give it a go over the weekend. Haven't done a JOSS review before but it looks straightforward.

⚡ thank you so much @zackdraper! Please review [the instructions above](https://github.com/openjournals/joss-reviews/issues/2641#issuecomment-687649852), and work through the checklist at the top of the issue (you'll need to accept the repository invite above from Whedon before you can update the checklist).

Any questions, don't hesitate to ask!

**Comment by zackdraper** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02641/joss.02641/10.21105.joss.02641.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02641/joss.02641/10.21105.joss.02641.pdf) :page_facing_up: :point_left:

**Comment by zackdraper** [comment]
@zemogle Do you have a link to an example data set to use?  Trying to confirm functionality on real data. Tried getting public data off of LCO and got a few errors.  

The error for a missing keyword was caught, but I would suggest having documentation saying what fits header keywords are required for the input data.

I got another error resulting from a malformatted .fits file on "hdulist[2]" giving a Python KeyError.

**Comment by zemogle** [comment]
Hey @zackdraper 👋  Thanks for picking this up. Just picking a random data set, you could try this data set of [Tres 2b](https://archive.lco.global/?q=a&RLEVEL=91&PROPID=&INSTRUME=&OBJECT=&SITEID=&TELID=&FILTER=&OBSTYPE=&EXPTIME=&BLKUID=&REQNUM=1849306&basename=&start=2014-01-01&end=2021-07-31%2023%3A59&id=&public=true).

The coords of Tres 2b are `--ra 286.8083 --dec 49.3164` if you need them. I've just just tried `astrosource` with this dataset using the `--full` option and left it. All worked as expected.

I think the error you mentioned might have been from a fits file which doesn't have the photometry data in the fits extension.

Good catch on the documentation. As with all documentation it is a work in progress. I've never written documentation before, so any and all suggestions are helpful.

**Comment by zackdraper** [comment]
Hey @zemogle I ran it on the Tres2b data and got an error, looks like there needs to be more exception handling when intermediate steps don't return what is normally expected.

```
(py3) zackdraper@zackdraper-MacBookAir:~/JOSS$ astrosource --ra 286.8083 --dec 49.3164 --indir lcogtdata-20210211-10/ --full
💾 Inspecting input files
🌟 Identify comparison stars for photometry calculations
..........
⭐️ Find stable comparison stars for differential photometry
..................................................................................................................................................................................................💫.................................................................................................................................................................................................💫...............................................................................................................................................................................................
⭐️ Find comparison stars in catalogues for calibrated photometry
..........
Traceback (most recent call last):
  File "/home/zackdraper/anaconda2/envs/py3/bin/astrosource", line 11, in <module>
    sys.exit(main())
  File "/home/zackdraper/anaconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/zackdraper/anaconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/zackdraper/anaconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zackdraper/anaconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/zackdraper/anaconda2/envs/py3/lib/python3.6/site-packages/astrosource/main.py", line 90, in main
    ts.find_variables()
  File "/home/zackdraper/anaconda2/envs/py3/lib/python3.6/site-packages/astrosource/astrosource.py", line 69, in find_variables
    find_variable_stars(targets=self.targets, parentPath=self.paths['parent'])
  File "/home/zackdraper/anaconda2/envs/py3/lib/python3.6/site-packages/astrosource/analyse.py", line 175, in find_variable_stars
    plot_variability(outputVariableHolder, parentPath)
  File "/home/zackdraper/anaconda2/envs/py3/lib/python3.6/site-packages/astrosource/plots.py", line 74, in plot_variability
    outplotx = asarray(output)[:, 2]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

```

**Comment by zemogle** [comment]
Hmmm. This is puzzling. I just made a new environment and installed astrosource from `pypi`. Everything ran smoothly. I also did a checkout of `master` to see if there was an issue there, but it also ran smoothly. None of our other users have reported this problem either so I'm finding it a bit tricky to debug. 

Would you be able to make an [issue](https://github.com/zemogle/astrosource/issues)  so we keep this separate from the paper review ?

**Comment by zackdraper** [comment]
I have to verify the code actually works.  Do you have another data set of an actual variable star?  I think at the very least you would need to document an example dataset people can use. Obviously cant include it because the data would be too large, but some public data source is useful for this code to be tested with.  Also, the fits files require certain keywords to work, I think you need to document those requirements as well.  Imagine someone tries this on another observatory dataset and it happens to use non-standard fits headers. This would make it more useful for the amateur's you are trying to help with this software.

- Functionality: Have the functional claims of the software been confirmed?
- Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

I followed a fresh install as documented, but I'll try it on another computer just to be sure.  

I appreciate that this review process has gone on for a very long time for you and hope to get it finished soon.

**Comment by zemogle** [comment]
I think the docs should be clearer on this but `astrosource` doesn't do the photometric extraction, it just does the photometric analysis. It really only operates on FITS files which have a photometry table extension. So the inclusion of FITS format is just for data tables not images (see [Basic Usage](https://astrosource.readthedocs.io/en/latest/basic_usage.html#time-series-data) part of the docs). The exact columns needed are also detailed in that section.

Here is a small public dataset of variable star [RX Eri](https://cloud.lco.global/s/xS2ZLkLsDyJyagx). You'll need to use the following options with it because these are `.psx` format not `FITS Table`. 
```
--ra 72.43451
--dec -15.74109
--format psx
```

If that doesn't work, I suspect there is something about the versions of `NumPy` or `Matplotlib` which is causing the shenanigens. It would be really helpful if you could post an issue, so we can track the problem separately to the paper review. As I understand it the paper review should be higher level than code bugs. 

Thanks for bearing with us!

**Comment by zackdraper** [comment]
Ok, I'm satisfied that the code is functional now with that example.  But, I would strongly encourage you to include an actual example like the RX Eri data set somewhere in the documentation.  You have a few examples shown in the paper. Ideally, for open source software, I would think those examples should be readily available to all users to immitate and prepare thier own data. `astrosource --help` also needs better documentation on what the parameters are (for ease of usabaility, the parameters are doccumented suffeciently in the readme).  The exception handling issues can be chalked up to bugs to be fixed, but usable examples are really how others are going to take this open source code as a starting point to do thier own work, modify the code, etc.

**Comment by zackdraper** [comment]
@arfon My review is done now (I think). I'll recommend it's accepted.

**Comment by zemogle** [comment]
Thanks @zackdraper  and @joshspeagle for very constructive reviews. We'll find a way to include a useful dataset and add more complete examples to the docs 👍

**Comment by arfon** [comment]
@mfitzasp @zemogle - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by zemogle** [comment]
I've updated the code with the suggestions, published on PyPi and made a release which is on Figshare. Here is the [DOI](https://doi.org/10.6084/m9.figshare.14113667)

I think that's it! Let me know if need anything else for publication. This has been a really great experience! 👍

**Comment by arfon** [comment]
@whedon set 10.6084/m9.figshare.14113667.v1 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.14113667.v1" target="_blank">10.6084/m9.figshare.14113667.v1</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/21672857.2017.1303264 is OK
- 10.1017/pasa.2014.30 is OK
- 10.1002/asna.201512254 is OK
- 10.3847/1538-3881/153/2/77 is OK
- 10.1088/1538-3873/ab7ee7 is OK
- 10.1017/pasa.2018.5 is OK
- 10.1088/0067-0049/219/1/12 is OK
- 10.32374/atom.2020.1.2 is OK
- 10.32374/atom.2020.1.4 is OK
- 10.1117/12.2314340 is OK
- 10.1086/673168 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1109/mcse.2011.37 is OK
- 10.1109/mcse.2007.55 is OK
- 10.3847/1538-3881/aafc33 is OK
- 10.21105/joss.00058 is OK
- 10.32374/atom.2020.1.1 is OK
- 10.1051/0004-6361:20020802 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2113

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2113, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
Huh, I don't see figshare come through too often so I might be looking in the wrong place, but I am having trouble verifying that the title and author list match the JOSS submission. @zemogle can you point me to where this is, or update it on your end?

**Comment by kthyng** [comment]
@zemogle can you verify what version of your software should be associated with this review?

**Comment by zemogle** [comment]
@kthyng If you click the DOI link you should be able to see the title and authors list (Figshare shows a preview of the archive first, bizarrely). 

The version matching the paper is 1.5.2

**Comment by kthyng** [comment]
@zemogle Oh! I see it if I scroll farther down. Weird. Oh that looks good.

**Comment by kthyng** [comment]
@whedon set v1.5.2 as version

**Comment by whedon** [comment]
OK. v1.5.2 is the version.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1365403674219053057) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2116
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02641](https://doi.org/10.21105/joss.02641)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication to @mfitzasp! Many thanks to editor @arfon and reviewers @zackdraper and @joshspeagle for your time, hard work, and expertise!! 🎉 🎉

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02641/status.svg)](https://doi.org/10.21105/joss.02641)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02641">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02641/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02641/status.svg
   :target: https://doi.org/10.21105/joss.02641
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02641/status.svg)](https://doi.org/10.21105/joss.02641)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
