### ISSUE TITLE
[PRE REVIEW]: QGameTheory: A Quantum Game Theory Simulator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2642]
**Submitting author:** @indrag49 (<a href="http://orcid.org/0000-0002-7964-1307">Indranil Ghosh</a>)
**Repository:** <a href="https://github.com/indrag49/QGameTheory" target ="_blank">https://github.com/indrag49/QGameTheory</a>
**Version:** v0.1.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @indrag49. **Currently, there isn't an JOSS editor assigned** to your paper.

@indrag49 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (634.7 files/s, 42230.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               45            137           1447            842
Markdown                         2            118              0            527
TeX                              1             13              0            110
-------------------------------------------------------------------------------
SUM:                            48            268           1447           1479
-------------------------------------------------------------------------------


Statistical information for the repository '2642' was gathered on 2020/09/06.
No commited files with the specified extensions were found.
```

**Comment by danielskatz** [comment]
@whendon query scope

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02642/joss.02642/10.21105.joss.02642.pdf)

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by indrag49** [comment]
Hi, I am new to submitting to JOSS. Just to clarify, am I supposed to wait now? Or am I supposed to make changes to the paper.md as I see there is a "Failed to discover a Statement of need section in paper" message?

**Comment by danielskatz** [comment]
If you want to, you can add a Statement of Need section in the paper, than add a new comment here with ```@whedon generate pdf``` to regenerate the pdf.  However, note that because of the small amount of code in this submission, it also will go through a check of the editors to determine if meets the [Substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) bar in order to be reviewed, and you could also wait until that finishes, probably by the middle of the week.

**Comment by danielskatz** [comment]
👋 @indrag - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work. You might also consider [JOSE](https://jose.theoj.org) if this has more educational than research purposes.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
