### ISSUE TITLE
[REVIEW]: Moran Pycess: a Python package to simulate Moran processes driven by game theory

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2643]
**Submitting author:** @AngryMaciek (<a href="http://orcid.org/0000-0003-1361-7301">Maciej Bak</a>)
**Repository:** <a href="https://github.com/AngryMaciek/angry-moran-simulator" target ="_blank">https://github.com/AngryMaciek/angry-moran-simulator</a>
**Version:** 1.0.0
**Editor:** @majensen
**Reviewer:** @xin-huang, @tkchafin
**Archive:** <a href="https://doi.org/10.5281/zenodo.4114143" target="_blank">10.5281/zenodo.4114143</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3de15ca5cee0a1ae4304f85cfa70a8d9/status.svg)](https://joss.theoj.org/papers/3de15ca5cee0a1ae4304f85cfa70a8d9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3de15ca5cee0a1ae4304f85cfa70a8d9"><img src="https://joss.theoj.org/papers/3de15ca5cee0a1ae4304f85cfa70a8d9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3de15ca5cee0a1ae4304f85cfa70a8d9/status.svg)](https://joss.theoj.org/papers/3de15ca5cee0a1ae4304f85cfa70a8d9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/AngryMaciek/angry-moran-simulator" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@xin-huang & @tkchafin, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @majensen know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AngryMaciek/angry-moran-simulator">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@AngryMaciek) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/AngryMaciek/angry-moran-simulator">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@AngryMaciek) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @xin-huang, @tkchafin it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2643 with the following error: 

 Can't find any papers to compile :-(

**Comment by majensen** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02643/joss.02643/10.21105.joss.02643.pdf)

**Comment by xin-huang** [comment]
The authors implemented a python package to perform simulation with different evolutionary strategies under Moran process. This is an interesting simulator in population biology, because there are very few user-friendly simulators for evolutionary game currently. After testing this package and reading the paper, I have several concerns on the documentation and software paper. I have opened some issues (https://github.com/AngryMaciek/angry-moran-simulator/issues/5 and https://github.com/AngryMaciek/angry-moran-simulator/issues/6) in the repository. Because I do not have computers with MacOS and TravisCI cannot make python builds on MacOS. I cannot verify the installation and performance on MacOS.

**Comment by tkchafin** [comment]
The authors have provided a flexible and user-friendly software to generate simulations under several different scenarios from evolutionary game theory. I was able to verify functionality of the simulated processes and built-in plotting functions under MacOS, after minor changes to the documented installation instructions provided by the authors. After completing my review, I would recommend publication of this contribution in JOSS after completing several necessary revisions, which are aimed primarily at increasing clarity of the communications associated with this package (both software paper and documentation), and making installation/ plotting easier for the user. These are summarized below, and in greater detail as Issues on the software github page. 

Software paper: 
Major issues (per checklist) are currently: 1) The lack of a non-specialist summary statement; and 2) There are many inconsistencies in the writing that make me suggest the authors go back through more carefully to edit for clarity and language). For example, “EES” vs “ESS” is not consistent, and several other instances (i.e. “A population consists of individuals…” rather than “Population is created by individuals…”) where the quality of writing could be improved. These problems are listed in more detail over at issue #9(https://github.com/AngryMaciek/angry-moran-simulator/issues/9). 


Documentation/ Functionality: There are 2 major issues here that I think should be corrected prior to publication: 1) The installation was not initially successful (on MacOS) without first manually relaxing the version constraints specified in the .yml file. I suspect that these constraints are overly specific, which for me created conflicts when creating the environment in conda; and 2) Documentation for the plotting functions is insufficient. A third issue (which I consider minor) is that - per the checklist - the documentation should also contain a statement of need. These are also added as issues #7 (https://github.com/AngryMaciek/angry-moran-simulator/issues/7) and #8 (https://github.com/AngryMaciek/angry-moran-simulator/issues/8)

**Comment by majensen** [comment]
Wow @xin-huang and @tkchafin, you may have set some kind of record. Thanks very much.

**Comment by rozmanowna** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02643/joss.02643/10.21105.joss.02643.pdf)

**Comment by rozmanowna** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02643/joss.02643/10.21105.joss.02643.pdf)

**Comment by xin-huang** [comment]
Hi @majensen I have checked off all the items on the checklist. The authors already addressed my concerns. I have no further comments.

**Comment by majensen** [comment]
Thanks @xin-huang  - so @AngryMaciek I will look for https://github.com/AngryMaciek/angry-moran-simulator/issues/7 to be addressed and @tkchafin to then tick the final box on that review. I'll then proceed with editorial checks. Thanks all!

**Comment by AngryMaciek** [comment]
Dear @majensen ,
I believe we have addressed all of the suggestions raised by the reviewers :)

(CC @rozmanowna @tkchafin @xin-huang )

**Comment by majensen** [comment]
@whedon check references

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2643 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2643 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2643 with the following error: 

 Can't find any papers to compile :-(

**Comment by majensen** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by majensen** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2643 with the following error: 

 sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.02643.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/S0305004100033193 is OK
- 10.1017/CBO9780511806292 is OK
- 10.1016/j.jocs.2019.101067 is OK
- 10.5281/zenodo.3980654 is OK
- 10.1155/2007/18636 is OK
- 10.1038/nature07921 is OK
- 10.1137/15M1044825 is OK
- 10.1038/380240a0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by majensen** [comment]
@openjournals/dev - please see error in compilation at https://github.com/openjournals/joss-reviews/issues/2643#issuecomment-699695148 - I was able to use https://whedon.theoj.org successfully.

**Comment by majensen** [comment]
[Proof generated by whedon.theoj.org](https://github.com/openjournals/joss-reviews/files/5289179/sp4qyhqedxejp6q3hoho.pdf)

**Comment by arfon** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/S0305004100033193 is OK
- 10.1017/CBO9780511806292 is OK
- 10.1016/j.jocs.2019.101067 is OK
- 10.5281/zenodo.3980654 is OK
- 10.1155/2007/18636 is OK
- 10.1038/nature07921 is OK
- 10.1137/15M1044825 is OK
- 10.1038/380240a0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02643/joss.02643/10.21105.joss.02643.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02643/joss.02643/10.21105.joss.02643.pdf) :page_facing_up: :point_left:

**Comment by AngryMaciek** [comment]
Dear Editors,
Should we now make a `zenodo` submission ourselves, or... (?)

**Comment by majensen** [comment]
You can do that if you wish @AngryMaciek. I will have a pull request for you with a number of suggested changes. Apologies for the delay, thanks for your patience.

**Comment by AngryMaciek** [comment]
@majensen 
Then there is no need now, I will wait until I merge your suggestions.

**Comment by majensen** [comment]
will get to this by Thursday - thanks @AngryMaciek

**Comment by majensen** [comment]
@AngryMaciek please have a look at the suggestions in the PR (and assoc. comments).

I would also like to see an example run in the paper that exemplifies stochastic effects. One example might be to show that if an invading population is small enough, it can disappear frequently (i.e., among many replicate simulations) even if it uses an ESS. Probably (absolute guess) the fitness benefit has to exceed 1/N more or less to get a high probability of establishment. 
(This is also a test of the software - if a rare invader never disappears over multiple replicates, there is probably a code issue.)
thanks

**Comment by majensen** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02643/joss.02643/10.21105.joss.02643.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02643/joss.02643/10.21105.joss.02643.pdf) :page_facing_up: :point_left:

**Comment by AngryMaciek** [comment]
We have just included the most recent changes in the branch `paper` of the [repository](https://github.com/AngryMaciek/angry-moran-simulator).

**Comment by AngryMaciek** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02643/joss.02643/10.21105.joss.02643.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02643/joss.02643/10.21105.joss.02643.pdf) :page_facing_up: :point_left:

**Comment by majensen** [comment]
@AngryMaciek I think things look quite good. Can you now create your archive, making sure that the archive title and authors are the same as those on the paper? Once that's done, please provide the archive DOI in this thread. Then I will attempt the spell summoning the editors-in-chief. thanks!

**Comment by AngryMaciek** [comment]
@majensen 

We have merged branch `paper` to `master` and removed the former.
We have submitted the code to zenodo: https://doi.org/10.5281/zenodo.4114143

Good luck with the spellcasting!
(∩｀-´)⊃━☆ﾟ.*･｡ﾟ

**Comment by majensen** [comment]
@whedon set 10.5281/zenodo.4114143 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4114143" target="_blank">10.5281/zenodo.4114143</a> is the archive.

**Comment by majensen** [comment]
@whedon set 1.0.0 as version

**Comment by whedon** [comment]
OK. 1.0.0 is the version.

**Comment by majensen** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/S0305004100033193 is OK
- 10.1017/CBO9780511806292 is OK
- 10.1016/j.jocs.2019.101067 is OK
- 10.5281/zenodo.3980654 is OK
- 10.1155/2007/18636 is OK
- 10.1038/nature07921 is OK
- 10.1137/15M1044825 is OK
- 10.1038/380240a0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1836

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1836, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hi @AngryMaciek, I'm the EIC on duty this week doing some final checks. I only noticed one minor issue: a typo in "e.g" in the second paragraph. Could you fix with "e.g.,"? Thanks!

**Comment by AngryMaciek** [comment]
Hi @kyleniemeyer :)
Done in https://github.com/AngryMaciek/angry-moran-simulator/commit/431773d1872301f62dbdde76283988cf0fa8797e

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02643/joss.02643/10.21105.joss.02643.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02643/joss.02643/10.21105.joss.02643.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1320515913217617922) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1857
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02643](https://doi.org/10.21105/joss.02643)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @AngryMaciek on your article's publication in JOSS!

Many thanks to  @xin-huang and @tkchafin for reviewing this, and @majensen for editing it.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02643/status.svg)](https://doi.org/10.21105/joss.02643)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02643">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02643/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02643/status.svg
   :target: https://doi.org/10.21105/joss.02643
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02643/status.svg)](https://doi.org/10.21105/joss.02643)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by AngryMaciek** [comment]
Thank you very much @majensen @xin-huang @tkchafin for all your work and help!

**Comment by majensen** [comment]
@AngryMaciek congrats- It's a nice application and an interesting paper. Thanks for choosing JOSS!
