### ISSUE TITLE
[REVIEW]: BioGears: A C++ library for whole body physiology simulations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2645]
**Submitting author:** @ajbaird (<a href="http://orcid.org/0000-0002-4711-3016">Austin Baird</a>)
**Repository:** <a href="https://github.com/BioGearsEngine/core" target ="_blank">https://github.com/BioGearsEngine/core</a>
**Version:** v7.3.2
**Editor:** @meg-simula
**Reviewer:** @fcooper8472, @MiroK
**Archive:** <a href="https://doi.org/10.5281/zenodo.4304604" target="_blank">10.5281/zenodo.4304604</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5ecd8c3138fe9e272179549c49905635/status.svg)](https://joss.theoj.org/papers/5ecd8c3138fe9e272179549c49905635)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5ecd8c3138fe9e272179549c49905635"><img src="https://joss.theoj.org/papers/5ecd8c3138fe9e272179549c49905635/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5ecd8c3138fe9e272179549c49905635/status.svg)](https://joss.theoj.org/papers/5ecd8c3138fe9e272179549c49905635)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/BioGearsEngine/core" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@fcooper8472 & @MiroK, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @meg-simula know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/BioGearsEngine/core">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ajbaird) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/BioGearsEngine/core">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ajbaird) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @fcooper8472, @MiroK it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2645 with the following error: 

 Can't find any papers to compile :-(

**Comment by meg-simula** [comment]
@whedon generate pdf from branch f/abard-JOSSPaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch f/abard-JOSSPaper. Reticulating splines etc...
```

**Comment by meg-simula** [comment]
@whedon check references from branch f/abard-JOSSPaper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch f/abard-JOSSPaper
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2645 with the following error: 

 sh: 1: cd: can't cd to tmp/2645
/app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2645 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1089/end.2016.0613 may be a valid DOI for title: The CREST simulation development process: training the next generation
- 10.1002/psp4.12371 may be a valid DOI for title: Open source pharmacokinetic/pharmacodynamic framework: tutorial on the BioGears Engine
- 10.1117/12.2252510 may be a valid DOI for title: Physiology informed virtual surgical planning: a case study with a virtual airway surgical planner and BioGears
- 10.3389/fphys.2019.01321 may be a valid DOI for title: A Whole-Body Mathematical Model of Sepsis Progression and Treatment Designed in the BioGears Physiology Engine
- 10.1109/embc.2019.8857686 may be a valid DOI for title: A Full-Body Model of Burn Pathophysiology and Treatment Using the BioGears Engine

INVALID DOIs

- None
```

**Comment by meg-simula** [comment]
@ajbaird Could you look at the paper compilation issue reported by @whedon above at your earliest convenience?

**Comment by ajbaird** [comment]
sorry just noticed this, I can update DOIs today, Thanks!

**Comment by ajbaird** [comment]
Hi @meg-simula just pushed an update for the missing DOIs, not totally sure about the compilation error though? Seems to be not able to find the temp/ folder and the cd command is failing? Compiled ok before, maybe it needs to update with the new issue number once it got moved? I'm really not sure, sorry!

**Comment by meg-simula** [comment]
@whedon generate pdf from branch f/abard-JOSSPaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch f/abard-JOSSPaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
@whedon check references from branch f/abard-JOSSPaper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch f/abard-JOSSPaper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1089/end.2016.0613 is OK
- 10.1016/0022-2828(90)91460-o is OK
- 10.1007/s11517-008-0359-2 is OK
- 10.1002/psp4.12371 is OK
- 10.1117/12.2252510 is OK
- 10.3389/fphys.2019.01321 is OK
- 10.1109/EMBC.2019.8857686 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by meg-simula** [comment]
@ajbaird Ok, thanks! Compiles nicely now.

**Comment by ajbaird** [comment]
@meg-simula awesome, sorry about that issue!

**Comment by arfon** [comment]
:wave: @fcooper8472, @MiroK, @meg-simula - how are things going here? I see that @fcooper8472 & @MiroK haven't made much progress with your reviews yet?

**Comment by fcooper8472** [comment]
@arfon you're absolutely right - my apologies!  I'll get cracking on it this afternoon.

**Comment by MiroK** [comment]
Sorry for the delay. I'll get to it next week

**Comment by fcooper8472** [comment]
@arfon  I'm having problems configuring with CMake on Ubuntu 20.04.  I realise there aren't any specific instructions for 20.04, but the problematic dependency is identical to that on 18.04, so perhaps I'm missing something:

I'm following [these instructions](https://github.com/BioGearsEngine/core/wiki/Using-Ubuntu-package-system):

```
installing xsd

wget https://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd_4.0.0-1_amd64.deb
sudo dpkg -i xsd_4.0.0-1_amd64.deb
```

But get, when running CMake:

```
CMake Warning at cmake/cmake-common_logic.cmake:42 (message):
  The following packages CodeSynthesis were not found.For native compilations
  setting CMAKE_PREFIX_PATH can solve this problemFor cross complilation try
  expanding your CMAKE_FIND_ROOT_PATH
Call Stack (most recent call first):
  projects/biogears/CMakeLists.txt:34 (verify_package)
```

I see that ultimately the script that is responsible for finding XSD is

```
core/cmake/common/FindCodeSynthesis.cmake
```

but I can't see a mechanism to, for instance, explicitly identify paths to search in for XSD.  Any ideas?

**Comment by arfon** [comment]
> @arfon I'm having problems configuring with CMake on Ubuntu 20.04. I realise there aren't any specific instructions for 20.04, but the problematic dependency is identical to that on 18.04, so perhaps I'm missing something:

@ajbaird - I think this question is actually for you :-)

**Comment by fcooper8472** [comment]
> > @arfon I'm having problems configuring with CMake on Ubuntu 20.04. I realise there aren't any specific instructions for 20.04, but the problematic dependency is identical to that on 18.04, so perhaps I'm missing something:
> 
> @ajbaird - I think this question is actually for you :-)

Aha yes, my bad!

**Comment by ajbaird** [comment]
Hi @fcooper8472 @arfon ! So I think there are two solutions to the issue you are having, you can opt to use the xsd version provided in the apt-get package manager, I think its called xsdcxx (we haven't tested using this but I think it'll probably work, the brew version works on macOS). 

I feel like with our testing, we didn't need to configure cmake prefix paths to point to xsd on linux (when using the .deb package), but you could get the .bz2 file, unzip it and then add a line to the configuration step to set CMAKE_PREFIX_PATH=<path to xsd bin>

**Comment by fcooper8472** [comment]
Thanks @ajbaird, got it working by unzipping the bz2 package and specifying `CMAKE_PREFIX_PATH`.  I then get a warning:

```
-- Configuring Biogears
-- Could NOT find Boost: Found unsuitable version "1.71.0", but required is at least "1.73.0" (found /usr/include, )
```

but can't see how to specify the boost location AND the XSD location using `CMAKE_PREFIX_PATH`.

Without boost, though, it seems to have configured and compiled fine.

**Comment by ajbaird** [comment]
Ok, yeah there should just be a check for the version of boost and we rely on a few optional parameters from 1.73, so as long as it compiled ok, I believe you are good to go! We are updating the wiki for your 20.04 build to mention unzipping the bz2 package instead of relying on the .deb package! Thanks for the input.

**Comment by fcooper8472** [comment]
Apologies for the delay in completing my review. I have only one checkbox unticked:

- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?

Some general comments on the software/repository:

- The software appears to be well written, tested and documented: in my opinion, well above the threshold for publication in JOSS.
- In the README, under [Contributing](https://github.com/BioGearsEngine/core#contributing), there is a placeholder "Details will be filled in shortly", although enough information is provided that I was happy to check the related box in my review.
- The README contains a table indicating build status on a number of platforms, compilers and architectures. Are those badges "live"? Is the continuous integration hosted somewhere public? Could an interested third party see details of the processes that are behind this table?  There is certainly no requirement for the purpose of this review: I am simply curious as to whether those are just static images, and whether therefore the build is indeed succeeding everywhere.

Some general comments on the paper:

- There is one place with two references ("arterial system by using resistance and compliance elements (ref)(ref)") where the references could be combined.  I believe the syntax would be `[@Ref1; @Ref2]`
- The sentence "Full documentation and validation for every action available to the user is provided through our website link" looks very odd with the link & no punctuation at the end.

**Comment by ajbaird** [comment]
Hi @fcooper8472 we use build bot for our CI processes, we have developed it in house using those python libraries to build our cross platform tests, we don't' give access to others to view that splash screen but the badges are generated with buildbot, then uploaded to AWS so the badges are updated nightly. I can def change the general comments this week! 

Getting access to our IRC channel is the best way to contribute and we do have a very brief wiki article but I updating the contributing link is something that has been on our radar and needs updating.

**Comment by ajbaird** [comment]
oh just saw the top comment @fcooper8472, I can update some information there, should I do that now or after this process has concluded, then re-submit?

**Comment by fcooper8472** [comment]
@ajbaird  I think you can just update the paper and then get the bot to rebuild the paper as a new pdf.  Definitely don't need to re-submit I don't think.

**Comment by ajbaird** [comment]
@fcooper8472 ok great! I'll update now, might be able to wrap it up today. I'll post here when done.

**Comment by ajbaird** [comment]
@whedon generate pdf from branch f/abard-JOSSPaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch f/abard-JOSSPaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: :point_left:

**Comment by ajbaird** [comment]
ok @fcooper8472  just made some changes, I included the bulk of the text changes to address the unchecked box under the summery title. If you think it should have its own header, let me know, I thought it sort of fit there.

**Comment by ajbaird** [comment]
@whedon generate pdf from branch f/abard-JOSSPaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch f/abard-JOSSPaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: :point_left:

**Comment by fcooper8472** [comment]
@ajbaird That looks great, I'm happy to check the box now.

I'm finished with my review now; it all looks good from my perspective.

**Comment by meg-simula** [comment]
Thanks @fcooper8472 for the completed review and @ajbaird for the rapid handling of feedback.

**Comment by meg-simula** [comment]
@MiroK How are you progressing with this review? Do let me know if there is anything I can contribute with at this stage.

**Comment by ajbaird** [comment]
let me know if you need anything from me!

**Comment by MiroK** [comment]
@ajbaird I apologize for late response. From my point of view all looks/works nicely; I was able to install and run the code without issues on my Ubuntu 18.04. The only comments I have are regarding the article proof: 

- In the sentence on page 2. "compliance elements(Otto, 1899; Westerhof et al., 2009)" I guess there should be a space
- " The software architecture of BioGears is implemented in three layers of abstraction to encourage easy integration and provide a robust application programming interface (API), Figure 1". Should this be, "see Figure 1." or similar?

**Comment by ajbaird** [comment]
Hi @MiroK ! Thanks for the feedback, glad you were able to get it up and running! I'll address these two items today and build a new pdf.

**Comment by ajbaird** [comment]
@whedon generate pdf from branch f/abard-JOSSPaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch f/abard-JOSSPaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: :point_left:

**Comment by ajbaird** [comment]
Hi @MiroK got those edits in, feel free to download the proof above! 

Thanks for the edits!

**Comment by MiroK** [comment]
Thanks @ajbaird! @meg-simula I am done with the review

**Comment by ajbaird** [comment]
Hi @meg-simula let me know if there is anything else I can do! Thanks again for all the edits!

**Comment by meg-simula** [comment]
@ajbaird This reminder was perfect! 

@fcooper8472 @MiroK Could you confirm that you recommend this paper for acceptance at this point?

**Comment by fcooper8472** [comment]
@meg-simula yes, absolutely recommended.

**Comment by MiroK** [comment]
@meg-simula Yes from me too

**Comment by meg-simula** [comment]
Ok @ajbaird - I will follow-up on this later tonight or tomorrow - will get back in touch.

**Comment by meg-simula** [comment]
@whedon generate pdf

**Comment by meg-simula** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1089/end.2016.0613 is OK
- 10.1016/0022-2828(90)91460-o is OK
- 10.1007/s11517-008-0359-2 is OK
- 10.1002/psp4.12371 is OK
- 10.1117/12.2252510 is OK
- 10.3389/fphys.2019.01321 is OK
- 10.1109/EMBC.2019.8857686 is OK

MISSING DOIs

- 10.1016/j.pbiomolbio.2004.01.004 may be a valid DOI for title: CellML: its future, present and past

INVALID DOIs

- None
```

**Comment by meg-simula** [comment]
@ajbaird 

Please address the following minor points in the paper: 
- [ ] Add space before reference to (Otto...)
- [ ] This phrasing is unclear, please rephrase: "This work has extended the engine to support ..." 
- [ ] "New dugs" should probably be "New drugs" - please spell-check
- [ ] Missing punctuation after reference to Figure 1
- [ ] Should HowToFaciculation() be HowToFasciculation() ?  

After these points have been addressed, could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by ajbaird** [comment]
I will get to these today!

**Comment by ajbaird** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: :point_left:

**Comment by ajbaird** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: :point_left:

**Comment by ajbaird** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: :point_left:

**Comment by ajbaird** [comment]
Hi @meg-simula ! I think I got to all the edits you listed here with a few other minor things. 

- Software version is v7.3.2 https://github.com/BioGearsEngine/core/releases/tag/7.3.2
-  release is up on Zenodo, DOI is here 10.5281/zenodo.4304604, Author list and title should be the same as this paper. 

I think that is everything, let me know if I got to it, sorry if I missed something. 

Thanks! 

Austin

**Comment by meg-simula** [comment]
@whedon generate pdf

**Comment by meg-simula** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1089/end.2016.0613 is OK
- 10.1016/0022-2828(90)91460-o is OK
- 10.1007/s11517-008-0359-2 is OK
- 10.1002/psp4.12371 is OK
- 10.1117/12.2252510 is OK
- 10.3389/fphys.2019.01321 is OK
- 10.1109/EMBC.2019.8857686 is OK
- 10.1016/j.pbiomolbio.2004.01.004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02645/joss.02645/10.21105.joss.02645.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
@whedon set 10.5281/zenodo.4304604 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4304604" target="_blank">10.5281/zenodo.4304604</a> is the archive.

**Comment by meg-simula** [comment]
@whedon set v7.3.2 as version

**Comment by whedon** [comment]
OK. v7.3.2 is the version.

**Comment by meg-simula** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1089/end.2016.0613 is OK
- 10.1016/0022-2828(90)91460-o is OK
- 10.1007/s11517-008-0359-2 is OK
- 10.1002/psp4.12371 is OK
- 10.1117/12.2252510 is OK
- 10.3389/fphys.2019.01321 is OK
- 10.1109/EMBC.2019.8857686 is OK
- 10.1016/j.pbiomolbio.2004.01.004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1969

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1969, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1089/end.2016.0613 is OK
- 10.1016/0022-2828(90)91460-o is OK
- 10.1007/s11517-008-0359-2 is OK
- 10.1002/psp4.12371 is OK
- 10.1117/12.2252510 is OK
- 10.3389/fphys.2019.01321 is OK
- 10.1109/EMBC.2019.8857686 is OK
- 10.1016/j.pbiomolbio.2004.01.004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1981

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1981, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@ajbaird - could you please add a little more information to the affiliation string? For example, city and country name.

**Comment by ajbaird** [comment]
Hi @arfon ! Just added city state and country, let me know if you want a more detailed address. Thanks!

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1089/end.2016.0613 is OK
- 10.1016/0022-2828(90)91460-o is OK
- 10.1007/s11517-008-0359-2 is OK
- 10.1002/psp4.12371 is OK
- 10.1117/12.2252510 is OK
- 10.3389/fphys.2019.01321 is OK
- 10.1109/EMBC.2019.8857686 is OK
- 10.1016/j.pbiomolbio.2004.01.004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1984

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1984, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1338493033185226754) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1985
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02645](https://doi.org/10.21105/joss.02645)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@fcooper8472, @MiroK - many thanks for your reviews here and to @meg-simula for editing this submission. JOSS relies upon the volunteer efforts of folks like yourself - we simply couldn't do it without you ✨ 

@ajbaird - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02645/status.svg)](https://doi.org/10.21105/joss.02645)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02645">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02645/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02645/status.svg
   :target: https://doi.org/10.21105/joss.02645
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02645/status.svg)](https://doi.org/10.21105/joss.02645)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
