### ISSUE TITLE
[PRE REVIEW]: medrxivr: Accessing and searching medRxiv and bioRxiv preprint data in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2647]
**Submitting author:** @mcguinlu (<a href="http://orcid.org/0000-0001-8730-9761">Luke A McGuinness</a>)
**Repository:** <a href="https://github.com/ropensci/medrxivr" target ="_blank">https://github.com/ropensci/medrxivr</a>
**Version:** v0.0.3
**Editor:** @danielskatz
**Reviewers:** @danielskatz
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mcguinlu. **Currently, there isn't an JOSS editor assigned** to your paper.

@mcguinlu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.22541/au.158516578.89167184 is OK
- 10.1136/bmj.l2301 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.14 s (244.9 files/s, 15396.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               18            169            252            633
Markdown                         5             76              0            212
YAML                             6             45              9            167
Rmd                              4            173            274            100
TeX                              1              4              0             24
-------------------------------------------------------------------------------
SUM:                            34            467            535           1136
-------------------------------------------------------------------------------


Statistical information for the repository '2647' was gathered on 2020/09/08.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02647/joss.02647/10.21105.joss.02647.pdf)

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by mcguinlu** [comment]
This package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/380<https://github.com/ropensci/software-review/issues/380#issue-comment-box> @ropensci/editors
________________________________

**Comment by danielskatz** [comment]
Ok, thanks - that's important to know, as it changes the path forward

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as reviewer

**Comment by whedon** [comment]
OK, @danielskatz is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2651.
