### ISSUE TITLE
[PRE REVIEW]: dymos: A Python package for optimal control of multidisciplinary systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2648]
**Submitting author:** @robfalck (<a href="http://orcid.org/0000-0001-9864-4928">Rob Falck</a>)
**Repository:** <a href="https://github.com/OpenMDAO/dymos" target ="_blank">https://github.com/OpenMDAO/dymos</a>
**Version:** v0.16.0
**Editor:** @dpsanders
**Reviewers:** @goerz, @thowell
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @robfalck. **Currently, there isn't an JOSS editor assigned** to your paper.

@robfalck if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s00158-019-02211-z is OK
- 10.2514/3.21662 is OK
- 10.2514/6.2009-5989 is OK
- 10.2514/3.21224 is OK
- 10.2514/6.2020-3176 is OK
- 10.2514/6.2020-3141 is OK
- 10.2514/6.2017-4002 is OK
- 10.2514/6.2018-3738 is OK
- 10.2514/6.2019-4491 is OK
- 10.2514/6.2018-3884 is OK
- 10.1007/s00158-011-0666-3 is OK

MISSING DOIs

- 10.1007/s10107-004-0559-y may be a valid DOI for title: On the Implementation of an Interior-Point Filter Line-Search Algorithm for Large-Scale Nonlinear Programming

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=4.39 s (72.2 files/s, 12642.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         259          11505           5675          29774
SVG                              4             70              0           3428
Markdown                        48           1037              0           2816
TeX                              2             61              1            610
Bourne Shell                     1             39             16            238
YAML                             3             32             18            203
-------------------------------------------------------------------------------
SUM:                           317          12744           5710          37069
-------------------------------------------------------------------------------


Statistical information for the repository '2648' was gathered on 2020/09/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bret Naylor                      4           262            261            0.21
Eliot Aretskin-Harit             1           228            299            0.22
John T. Hwang                   46          5875           2217            3.32
Justin Gray                      6          1512            450            0.81
Keith Marsteller                 2          1679           1604            1.35
Kenneth Moore                    5          2700           1657            1.79
Rob Falck                      180        128296          90437           89.77
Ted Wright                      13          2909           1509            1.81
bbahiam                          1           727              1            0.30
kaushikponnapalli                6           947             61            0.41
swryan                           1            17              8            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Bret Naylor                  32           12.2         22.6                0.00
Eliot Aretskin-Harit        178           78.1         18.8                4.49
John T. Hwang                21            0.4         29.2                4.76
Justin Gray                 413           27.3         18.8                3.87
Keith Marsteller             66            3.9         24.7                0.00
Kenneth Moore              1892           70.1          8.8                5.39
Rob Falck                 40596           31.6         16.6                5.98
Ted Wright                 2644           90.9          4.9                7.68
bbahiam                     664           91.3          1.0                3.61
kaushikponnapalli           445           47.0          8.7                6.29
swryan                        3           17.6         22.0                0.00
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02648/joss.02648/10.21105.joss.02648.pdf)

**Comment by danielskatz** [comment]
👋 @robfalck - please add an explicit "Statement of need" section

**Comment by danielskatz** [comment]
👋 @meg-simula - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by meg-simula** [comment]
@danielskatz Thanks for the suggestion - but I would like to advance some with my on-going submission before taking another one on.

**Comment by danielskatz** [comment]
👋 @katyhuff - any chance you could help out JOSS and edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @katyhuff as editor

**Comment by whedon** [comment]
@katyhuff has been invited to edit this submission.

**Comment by katyhuff** [comment]
I could take this on, but I'm stretched a little thin at the moment and I think dpsanders might be a closer fit for this submission if he's available.

**Comment by danielskatz** [comment]
👋 @dpsanders - are you willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @dpsanders as editor

**Comment by whedon** [comment]
@dpsanders has been invited to edit this submission.

**Comment by dpsanders** [comment]
I have quite a lot on my plate but it is a good fit for me so yes.

**Comment by dpsanders** [comment]
@whedon assign @dpsanders as editor

**Comment by whedon** [comment]
OK, the editor is @dpsanders

**Comment by danielskatz** [comment]
thanks!

**Comment by robfalck** [comment]
> 👋 @robfalck - please add an explicit "Statement of need" section

I've added an explicit Statement of Need section.

**Comment by dpsanders** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02648/joss.02648/10.21105.joss.02648.pdf)

**Comment by dpsanders** [comment]
👋 @robfalck: Thanks for your submission to JOSS!

Reading through the paper I have a few initial comments:

- I don't feel that the paper is currently accessible to non-experts in the field. As an example, it's not clear how ODEs (which is never defined) are related to the rest of the story, and you seem to assume knowledge of OpenMDAO itself.

- It's not clear what is provided by OpenMDAO and what is new in Dymos.

- It's not clear what "phases" are.

- I would like to see a simple piece of example code and output in the paper.


In terms of the README in the repository:

- The code itself seems so verbose that it actually ends up being hard to read, even for a simple model. 
Also there seems to be code within strings.

**Comment by robfalck** [comment]
@dpsanders 

We've made some edits that hopefully will address your concerns here. 

I would like to know the intent of demonstrating it's use within the paper itself.  Developing dymos models and optimizing them is not easily demonstrated in a compact format.

I've included an example but I wonder if we should instead link to examples in the repo.  Including this example significantly increases the length of the paper.

**Comment by dpsanders** [comment]
@whedon generate pdf

**Comment by dpsanders** [comment]
👋 @robfalck: Thanks for the edits to the paper -- it's much clearer (and more inviting) now.
I'll proceed to look for reviewers.

Personally I like seeing the code a simple example in the paper and I don't see a particular reason for needing to keep the paper shorter but that is part of an ongoing editorial discussion.

**Comment by dpsanders** [comment]
@robfalck: Do you have any suggestions for reviewers?

**Comment by dpsanders** [comment]
👋 @bjack205 and @thowell: Would either of you be able to review this submission for JOSS?

**Comment by dpsanders** [comment]
👋 @moorepants and @goerz: Would you be able to review this submission for JOSS?

**Comment by moorepants** [comment]
@dpsanders Sorry, I can't. I'm still reviewing another JOSS paper.

**Comment by goerz** [comment]
I can, but I’m pretty busy this week. If next week is ok, then yes

**Comment by dpsanders** [comment]
Ok thanks @moorepants. 

Thanks @goerz, next week is great.

**Comment by dpsanders** [comment]
👋 @Jgoldfar: Would you be able to review this submission for JOSS?

**Comment by thowell** [comment]
@dpsanders happy to do a review sometime during the next two weeks if that works

**Comment by dpsanders** [comment]
@whedon add @goerz as reviewer

**Comment by whedon** [comment]
OK, @goerz is now a reviewer

**Comment by dpsanders** [comment]
@whedon add @thowell as reviewer

**Comment by whedon** [comment]
OK, @thowell is now a reviewer

**Comment by dpsanders** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2809.

**Comment by dpsanders** [comment]
Thanks @goerz and @thowell! Please head over to the review issue, and let me know if you have any difficulties.
