### ISSUE TITLE
[PRE REVIEW]: PyCS3: A Python toolbox for time-delay measurements in lensed quasars

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2649]
**Submitting author:** @martin-millon (<a href="http://orcid.org/0000-0001-7051-497X">Martin Millon</a>)
**Repository:** <a href="https://gitlab.com/cosmograil/PyCS3" target ="_blank">https://gitlab.com/cosmograil/PyCS3</a>
**Version:** v3.0.2
**Editor:** @arfon
**Reviewers:** @danhey, @coljac
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @martin-millon. **Currently, there isn't an JOSS editor assigned** to your paper.

@martin-millon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.79 s (154.8 files/s, 28553.4 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           82           3218           3742          10057
reStructuredText                 21            751            224            841
SVG                               4              0            145            761
TeX                               1             17              0            274
Jupyter Notebook                  3              0           1655            241
Markdown                          6            141              0            218
YAML                              1              9              8             69
Bourne Again Shell                2             18              6             51
Bourne Shell                      1             13              2             22
make                              1              4              6             10
--------------------------------------------------------------------------------
SUM:                            122           4171           5788          12544
--------------------------------------------------------------------------------


Statistical information for the repository '2649' was gathered on 2020/09/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vivien                           2             4              4            0.02
bastian-lengen-epfl              3          1836             47            5.38
martin-millon                  110         23910           8820           93.54
vbonvin                         10           360              8            1.05

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vivien                        4          100.0          5.2                0.00
bastian-lengen-epfl        1783           97.1          1.2                8.86
martin-millon             15181           63.5          4.7                8.74
vbonvin                     263           73.1          0.0               42.97
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/202037740 is OK
- 10.1051/0004-6361/201220123 is OK
- 10.1051/0004-6361/201526704 is OK
- 10.1093/mnras/stw3006 is OK
- 10.1051/0004-6361/201935921 is OK
- 10.1093/mnras/stz3094 is OK
- 10.1051/0004-6361/201220352 is OK
- 10.1051/0004-6361/201833287 is OK
- 10.1088/0004-637X/800/1/11 is OK
- 10.1093/mnras/stx483 is OK
- 10.1038/s42254-019-0137-0 is OK
- 10.1086/170951 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02649/joss.02649/10.21105.joss.02649.pdf)

**Comment by danielskatz** [comment]
👋 @martin-millon - Is this submission associated with a AAS paper submission?

**Comment by danielskatz** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by arfon** [comment]
@danielskatz - I can take this one.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @martin-millon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by martin-millon** [comment]
@danielskatz This submission is not associated with any particular AAS publication but we used this software for several of our papers published in Astronomy & Astrophysics. 

@arfon I think that the reviewer would need some knowledge in astronomy, cosmology and python. Based on your list, I would suggest as potential reviewer : cavestruz, Teuben, astrom-tom, coljac, danhey, aureliocarner, Deech08,htugcas, cmillion, KshitijAggarwal, samvaughan, christinahedges.

**Comment by arfon** [comment]
:wave: @coljac, @cavestruz, @danhey - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by danhey** [comment]
Hi @arfon, I am available to review.

**Comment by coljac** [comment]
@arfon - I could do this;  apologies to the authors, I may need more than a week before I can commence.

**Comment by arfon** [comment]
@whedon add @danhey as reviewer

**Comment by whedon** [comment]
OK, @danhey is now a reviewer

**Comment by arfon** [comment]
@whedon add @coljac as reviewer

**Comment by whedon** [comment]
OK, @coljac is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2654.

**Comment by arfon** [comment]
@danhey, @coljac - thanks for agreeing to review this submission - see you over in #2654 where the actual review will take place.
