### ISSUE TITLE
[PRE REVIEW]: pd-parser: A tool for Matching Photodiode Deflection Events to Time-Stamped Events

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2650]
**Submitting author:** @alexrockhill (<a href="http://orcid.org/0000-0003-3868-7453">Alexander Rockhill</a>)
**Repository:** <a href="https://github.com/alexrockhill/pd-parser" target ="_blank">https://github.com/alexrockhill/pd-parser</a>
**Version:** 0.1
**Editor:** @oliviaguest
**Reviewers:** @rougier, @rly
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @alexrockhill. **Currently, there isn't an JOSS editor assigned** to your paper.

@alexrockhill if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.08 s (120.8 files/s, 45416.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                             44           1233            409          14704
JavaScript                      17           3447           2895          11572
HTML                            29           1014             29           7532
RobotFramework                   3              0              0           1771
Python                          10            184            475           1312
reStructuredText                17            541            441            407
SVG                              1              0              0            288
TeX                              1              6              0            259
XML                              1             31              0            151
YAML                             2              9              4             91
make                             2             24              9             59
Markdown                         1             13              0             37
DOS Batch                        1              8              1             26
Jupyter Notebook                 2              0            276             12
-------------------------------------------------------------------------------
SUM:                           131           6510           4539          38221
-------------------------------------------------------------------------------


Statistical information for the repository '2650' was gathered on 2020/09/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex                            41         37869            729           98.29
Alex Rockhill                    3           508            164            1.71

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alex                      38275          101.1          0.6               16.36
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/sdata.2016.44 is OK
- 10.3389/fnins.2013.00267 is OK
- 10.1038/sdata.2018.110 is OK
- 10.1038/s41597-019-0104-8 is OK
- 10.1038/s41597-019-0105-7 is OK
- 10.21105/joss.01896 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02650/joss.02650/10.21105.joss.02650.pdf)

**Comment by danielskatz** [comment]
👋 @alexrockhill - please add something to the README that explains how this is research software.  What kinds of researchers need this software? (this is in the paper)

Also, note that some images in the README seem broken

**Comment by danielskatz** [comment]
👋 @oliviaguest - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by oliviaguest** [comment]
@danielskatz sure. 😊

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
@alexrockhill if you can drop some names for potential reviewers when you get a chance that would be super useful.

**Comment by oliviaguest** [comment]
@whedon add @rougier as reviewer

**Comment by whedon** [comment]
OK, @rougier is now a reviewer

**Comment by alexrockhill** [comment]
> @alexrockhill if you can drop some names for potential reviewers when you get a chance that would be super useful.

Maybe @TomDonoghue has time now that he's finished his PhD (congratulations by the way!) or @sappelhoff?

**Comment by sappelhoff** [comment]
According to the [JOSS conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) I'd have such a conflict for reviewing this piece, because I am working with Alex on [mne-bids](https://github.com/mne-tools/mne-bids/), which we published a paper on in 2019.

I think I could still make a relatively impartial judgment (this is up to @oliviaguest to decide) ... but if we can find another reviewer that'd be good as well.

**Comment by oliviaguest** [comment]
@sappelhoff Fine with me, yup.

**Comment by oliviaguest** [comment]
@whedon add @sappelhoff as reviewer

**Comment by whedon** [comment]
OK, @sappelhoff is now a reviewer

**Comment by danielskatz** [comment]
I think this is ok if we can argue that there aren't others who could review this, but if there are, I would prefer we avoid this conflict.

**Comment by oliviaguest** [comment]
@danielskatz I was going to add a 3rd reviewer, is that OK? Or do you prefer to just have 2 without the conflict?

**Comment by danielskatz** [comment]
My preference would be to avoid the appearance of conflicts unless we don't have a good alternative, which it sounds like we do, in this case.

**Comment by oliviaguest** [comment]
Gotcha, @danielskatz — and that makes sense!

**Comment by oliviaguest** [comment]
@whedon remove @sappelhoff as reviewer

**Comment by whedon** [comment]
OK, @sappelhoff is no longer a reviewer

**Comment by oliviaguest** [comment]
@sappelhoff I'm gonna email you about something else. ☺️

**Comment by alexrockhill** [comment]
More reviewer suggestions are @voytek or @TomDLT or @libertyh if they have the time :)

**Comment by libertyh** [comment]
Happy to do it, but I've never reviewed for JOSS before, so let me know if there are any general guidelines for how to do this and I'm happy to.

**Comment by alexrockhill** [comment]
The documentation for reviewing is here https://joss.readthedocs.io/en/latest/reviewer_guidelines.html :)

**Comment by libertyh** [comment]
One very minor potential conflict of interest is that Nicole Swann and I were on this paper together (https://www.nature.com/articles/s41597-019-0105-7), but this is a large list of authors (N=39) with a large number of iEEG contributors, and I have otherwise not worked with these authors directly. But just for transparency's sake I thought I'd mention, though it does rule out many iEEG/ECoG people if used in this way.

**Comment by danielskatz** [comment]
From the point of view of JOSS, this is not a conflict that should cause a problem

**Comment by oliviaguest** [comment]
@whedon add @sneakers-the-rat as reviewer

**Comment by whedon** [comment]
OK, @sneakers-the-rat is now a reviewer

**Comment by oliviaguest** [comment]
OK, cool! @libertyh do you want to review this given the above (no conflict from JOSS' perspective)?

**Comment by sneakers-the-rat** [comment]
re: COI, Alex and I are both at University of Oregon (though I believe in different departments), I've done some light troubleshooting of a server with him but haven't collaborated on any major work. I think I can be impartial but also know that doesn't quite work for COI.

let me know if that is ok for JOSS

**Comment by oliviaguest** [comment]
@danielskatz I think that's borderline but not a COI? Assuming I mean reading the documentation properly?

**Comment by danielskatz** [comment]
Well
> In addition, your recent (past year) association with the same organization of a submitter is a COI, for example, being employed at the same institution.

So this is a conflict for that reason.  Again, if we can find a reviewer without conflicts, that would be better.  If not, I think this is ok.

**Comment by oliviaguest** [comment]
Damn! This is so COI-y. OK, I'll try my best.

**Comment by oliviaguest** [comment]
@whedon remove @sneakers-the-rat as reviewer

**Comment by whedon** [comment]
OK, @sneakers-the-rat is no longer a reviewer

**Comment by oliviaguest** [comment]
@whedon add @rly as reviewer

**Comment by whedon** [comment]
OK, @rly is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2674.

**Comment by libertyh** [comment]
I can still review if you need me! Thanks!

**Comment by oliviaguest** [comment]
@whedon add @libertyh as reviewer

**Comment by whedon** [comment]
OK, @libertyh is now a reviewer

**Comment by oliviaguest** [comment]
@libertyh awesome — thanks!
