### ISSUE TITLE
[REVIEW]: medrxivr: Accessing and searching medRxiv and bioRxiv preprint data in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2651]
**Submitting author:** @mcguinlu (<a href="http://orcid.org/0000-0001-8730-9761">Luke A McGuinness</a>)
**Repository:** <a href="https://github.com/ropensci/medrxivr" target ="_blank">https://github.com/ropensci/medrxivr</a>
**Version:** v0.0.3
**Editor:** @danielskatz
**Reviewer:** @danielskatz
**Archive:** <a href="https://doi.org/10.5281/zenodo.3860023" target="_blank">10.5281/zenodo.3860023</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3d6184f7a2d4fc3a8ad4c0bfacc560af/status.svg)](https://joss.theoj.org/papers/3d6184f7a2d4fc3a8ad4c0bfacc560af)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3d6184f7a2d4fc3a8ad4c0bfacc560af"><img src="https://joss.theoj.org/papers/3d6184f7a2d4fc3a8ad4c0bfacc560af/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3d6184f7a2d4fc3a8ad4c0bfacc560af/status.svg)](https://joss.theoj.org/papers/3d6184f7a2d4fc3a8ad4c0bfacc560af)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/medrxivr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@danielskatz, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/medrxivr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mcguinlu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @danielskatz it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.22541/au.158516578.89167184 is OK
- 10.1136/bmj.l2301 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02651/joss.02651/10.21105.joss.02651.pdf)

**Comment by arfon** [comment]
:wave: @mcguinlu - thanks for your submission to JOSS. Unfortunately, even though this submission came via rOpenSci, this submission is out of scope for JOSS as we classify it a 'minor' submission ([API wrapper](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)). I've asked the rOpenSci folks to update their guidelines to make it a little clearer which rOpenSci packages might be considered out of scope here. 

/ cc @karthik

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by mcguinlu** [comment]
Hi @arfon,

Thanks for your comments on the package, though I'll admit I am a little surprised that the package is not considered in scope. 

While the package does interact with the API, this is mainly as a precusor to searching the medRxiv database using complex search strategies and then bulk exporting the results to a .BIB file for further processing/analysis as part of a systematic literaure review. This functionality (reproducible + transparent searching, bulk export of records) is something that is not offered by either the medRxiv website or its API, or by any other package/tool, but is regularly requested by the health librarian community:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I have pretty much given up on medRxiv, it search interface is useless &amp; unpredictable. I have many searches that I have rerun exactly the same week prior that have come back with inconsistent wacky results. No way should a search one week get 60 citations then 3000 next <a href="https://twitter.com/hashtag/medlibs?src=hash&amp;ref_src=twsrc%5Etfw">#medlibs</a></p>&mdash; Michelle Kraft (@krafty) <a href="https://twitter.com/krafty/status/1293973175244656641?ref_src=twsrc%5Etfw">August 13, 2020</a></blockquote>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">anyone have a method for bulk export from medRxiv? <a href="https://twitter.com/hashtag/systematicreviews?src=hash&amp;ref_src=twsrc%5Etfw">#systematicreviews</a> <a href="https://twitter.com/hashtag/rapidreviews?src=hash&amp;ref_src=twsrc%5Etfw">#rapidreviews</a> <a href="https://twitter.com/hashtag/ukmedlibs?src=hash&amp;ref_src=twsrc%5Etfw">#ukmedlibs</a> <a href="https://twitter.com/hashtag/medlibs?src=hash&amp;ref_src=twsrc%5Etfw">#medlibs</a> <a href="https://twitter.com/hashtag/thanks?src=hash&amp;ref_src=twsrc%5Etfw">#thanks</a></p>&mdash; (((MarshallDozier))) (@mafrado) <a href="https://twitter.com/mafrado/status/1244905414019428353?ref_src=twsrc%5Etfw">March 31, 2020</a></blockquote>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Re-amplifying this question. I&#39;m grappling with medRxiv this morning and having issues downloading. Any ideas <a href="https://twitter.com/hashtag/medlibs?src=hash&amp;ref_src=twsrc%5Etfw">#medlibs</a> people? <a href="https://t.co/pBB8j7hy8U">https://t.co/pBB8j7hy8U</a></p>&mdash; Jane Falconer (@falkie71) <a href="https://twitter.com/falkie71/status/1253614501733249024?ref_src=twsrc%5Etfw">April 24, 2020</a></blockquote>

In addition, the main functionality of the package was developed before the medRxiv API came online - previously `medrxivr` used webscraping to import the data (for example, see this [commit point from back in February](https://github.com/ropensci/medrxivr/blob/71046e6a2d847cb529d351295cedfacba18d6b6b)), which is why I think the designation as an "API wrapper" might not be accurate.

Finally, just to make you aware that the package has already been used in two published academic publications that I know of (see [here](https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30630-7/fulltext) and [here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0234765)) (COI: I am one of the co-authors on the second paper)

I fully respect your decision as EiC, but just wanted to make sure that the decision wasn't due to an error on my part, in that I may not have accurately described `medrxivr` in the paper I submitted.

Thanks for your continued consideration!

**Comment by mcguinlu** [comment]
Good morning @arfon (& @danielskatz, for reference ), and happy Monday!

As it's been a week, just flagging the above again in case it got lost in the mix - would be great to hear what you think, particularly re: comparison with `chirps`.

**Comment by danielskatz** [comment]
@mcguinlu asked me to reopen this so that he could further discuss it with @arfon and the JOSS team, so I am doing so

**Comment by mcguinlu** [comment]
Thanks @danielskatz!

Also just flagging this to @maelle, as I know she has done a lot of work recently on updating the rOpenSci dev guide, and I agree with @arfon's point above that it might be useful to have clear guidelines on the types of rOpenSci packages that are considered out of scope by JOSS included in the rOpenSci dev guide.

**Comment by karthik** [comment]
Thanks @mcguinlu. We have started a discussion to update the dev guide so it clearly reflects what might be out of scope for JOSS.

**Comment by danielskatz** [comment]
@mcguinlu  - we're going to process this in JOSS.

**Comment by danielskatz** [comment]
This package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/380

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02651/joss.02651/10.21105.joss.02651.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02651/joss.02651/10.21105.joss.02651.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.22541/au.158516578.89167184 is OK
- 10.1136/bmj.l2301 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@mcguinlu - can you merge https://github.com/ropensci/medrxivr/pull/12 or let me know what part of it you disagree with?

**Comment by danielskatz** [comment]
Also, is this code in zenodo or another archive?  If so, what is the DOI for it there?  In https://github.com/ropensci/software-review/issues/380#issuecomment-689011508 it looks like that item is checked off...

**Comment by mcguinlu** [comment]
Hi @danielskatz, 

I've merged the changes you made in ropensci/medrxivr#12 into the main branch now. And the code for this package is archived by Zenodo. The Zenodo DOI is [10.5281/zenodo.3860023](https://doi.org/10.5281/zenodo.3860023)

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.3860023 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3860023" target="_blank">10.5281/zenodo.3860023</a> is the archive.

**Comment by danielskatz** [comment]
In the zenodo archive, can you change the metadata so that the title and authors match those of the JOSS paper?

**Comment by mcguinlu** [comment]
Done - title and authors are now consistent between the JOSS paper and the Zenodo repo.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.22541/au.158516578.89167184 is OK
- 10.1136/bmj.l2301 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1788

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1788, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1314554610254839810) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1789
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02651](https://doi.org/10.21105/joss.02651)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations @mcguinlu!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02651/status.svg)](https://doi.org/10.21105/joss.02651)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02651">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02651/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02651/status.svg
   :target: https://doi.org/10.21105/joss.02651
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02651/status.svg)](https://doi.org/10.21105/joss.02651)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by mcguinlu** [comment]
Awesome - thanks to everyone involved! 🥳
