### ISSUE TITLE
[REVIEW]: PyCS3: A Python toolbox for time-delay measurements in lensed quasars

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2654]
**Submitting author:** @martin-millon (<a href="http://orcid.org/0000-0001-7051-497X">Martin Millon</a>)
**Repository:** <a href="https://gitlab.com/cosmograil/PyCS3" target ="_blank">https://gitlab.com/cosmograil/PyCS3</a>
**Version:** v3.0.2
**Editor:** @arfon
**Reviewer:** @danhey, @coljac
**Archive:** <a href="https://doi.org/10.5281/zenodo.4046260" target="_blank">10.5281/zenodo.4046260</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d6bb9e5f6314e0b2c3c1cc9a9e2d2a5f/status.svg)](https://joss.theoj.org/papers/d6bb9e5f6314e0b2c3c1cc9a9e2d2a5f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d6bb9e5f6314e0b2c3c1cc9a9e2d2a5f"><img src="https://joss.theoj.org/papers/d6bb9e5f6314e0b2c3c1cc9a9e2d2a5f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d6bb9e5f6314e0b2c3c1cc9a9e2d2a5f/status.svg)](https://joss.theoj.org/papers/d6bb9e5f6314e0b2c3c1cc9a9e2d2a5f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/cosmograil/PyCS3" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@danhey & @coljac, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/cosmograil/PyCS3">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@martin-millon) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/cosmograil/PyCS3">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@martin-millon) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @danhey, @coljac it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/202037740 is OK
- 10.1051/0004-6361/201220123 is OK
- 10.1051/0004-6361/201526704 is OK
- 10.1093/mnras/stw3006 is OK
- 10.1051/0004-6361/201935921 is OK
- 10.1093/mnras/stz3094 is OK
- 10.1051/0004-6361/201220352 is OK
- 10.1051/0004-6361/201833287 is OK
- 10.1088/0004-637X/800/1/11 is OK
- 10.1093/mnras/stx483 is OK
- 10.1038/s42254-019-0137-0 is OK
- 10.1086/170951 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02654/joss.02654/10.21105.joss.02654.pdf)

**Comment by arfon** [comment]
@danhey, @coljac - This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/2654 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02654/joss.02654/10.21105.joss.02654.pdf)

**Comment by danhey** [comment]
Hi all,

I find the code to be well written and nicely documented. Great work! I have installed it without issue, and ran most of the example code. 

My only issue appears to be running the the [code in Sec. 1.2](https://cosmograil.gitlab.io/PyCS3/tutorial/generalities.html#importing-pycs3). I am getting an attribute error which seems to be caused by misconfigured imports. I can get around this by replacing `import pycs3` with `import pycs3.gen.lc_func`. 

Otherwise, this is an excellent package and I recommend it for publication.

**Comment by martin-millon** [comment]
Thanks @danhey for checking our code and thanks for spotting this problem in the documentation. 
I have pushed a fix on the master branch.

**Comment by coljac** [comment]
Hi authors,

I have a question about the multiprocessing. There are several methods that take a number of cores as an argument, for example `pycs3.sim.run.multirun`. The docs say:


> **ncpu** – integer. Number of CPU tu use, if None I will use all available CPUs. Turn this to one if you use higher level of parallelisation

However, when I pass in a number > 0, I see this:

```
Multi-processing is not supported on this verison ! You can still use a higher level of parallelisation. I will run on a single core for the moment.
Starting the curve shifting on a single CPU, no multiprocessing...
```
However, the documentation doesn't seem to mention this.  Should the docs reflect that this feature isn't implemented, or did I miss something?

**Comment by coljac** [comment]
Hi authors,

Here's the rest of my review.

Firstly, this is an excellent software package, and it serves a genuine scientific need, as time delay cosmology is only going to increase in the future and will be key in confirming or resolving the H0 tension. Congratulations on a great piece of work! It was also a pleasure to review, as everything is in great shape.

**Regarding the paper**: I am satisfied with the paper and don't need to see any revisions. I would suggest fixing the citations so that the nested parentheses are removed - "(for instance, Wang 2010.)" This is a minor issue, as is the phrase "Since almost three decades" should probably be "for almost three decades". 

**Regarding the software**: I was able to successfully run the pytest tests in `/tests`. I'm familiar with using pytest; this process should probably be documented. On my system. the plots generated by the tests popped up in windows (many, many windows); perhaps setting the default backend to Agg would be more convenient here? (On the other hand, the documentation of the workflow in tdc_test seems adequate to get everything working.)

The notebooks were very good, all the examples ran for me (I had to install a latex package and dvipng; I don't think this was a deficiency on your end though).

Otherwise, the package is well documented and rich in features, meeting a genuine scientific need. Subject to a note on pytest, I am satisfied with this submission.

**Comment by martin-millon** [comment]
Thanks, @coljac and @danhey for your reviews and for helping us to improve this package. 

I have made the following changes : 
 - I have completely removed the multiprocessing computing at the level of the function pycs3.sim.applyopt(). This can be done at a higher level, i.e., at the level of the function pycs3.sim.multirun(). This is now better documented in the [tutorial](https://cosmograil.gitlab.io/PyCS3/tutorial/makehists.html#parallel-computing). I think this is the best solution as this improves (a bit) the performance and prevent some errors if the user is trying to parallelize the code at both levels at the same time. 
- As you suggested, I have changed the backend to Agg in the `\tests`. 
- I have added some [documentation](https://cosmograil.gitlab.io/PyCS3/installation.html) on how to run the tests.
- I have made the changes that you suggested in the paper

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02654/joss.02654/10.21105.joss.02654.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02654/joss.02654/10.21105.joss.02654.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
Thanks for the update @martin-millon. I found one small typo in your paper which I corrected in https://gitlab.com/cosmograil/PyCS3/-/merge_requests/5

@coljac - assuming that @martin-millon's response addresses your concerns about testing, could you please check off the final item in your checklist?

@martin-millon - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by martin-millon** [comment]
@arfon - I have put an archive on Zenodo. Here is the DOI:  http://doi.org/10.5281/zenodo.4046260

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4046260 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4046260" target="_blank">10.5281/zenodo.4046260</a> is the archive.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/202037740 is OK
- 10.1051/0004-6361/201220123 is OK
- 10.1051/0004-6361/201526704 is OK
- 10.1093/mnras/stw3006 is OK
- 10.1051/0004-6361/201935921 is OK
- 10.1093/mnras/stz3094 is OK
- 10.1051/0004-6361/201220352 is OK
- 10.1051/0004-6361/201833287 is OK
- 10.1088/0004-637X/800/1/11 is OK
- 10.1093/mnras/stx483 is OK
- 10.1038/s42254-019-0137-0 is OK
- 10.1086/170951 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/202037740 is OK
- 10.1051/0004-6361/201220123 is OK
- 10.1051/0004-6361/201526704 is OK
- 10.1093/mnras/stw3006 is OK
- 10.1051/0004-6361/201935921 is OK
- 10.1093/mnras/stz3094 is OK
- 10.1051/0004-6361/201220352 is OK
- 10.1051/0004-6361/201833287 is OK
- 10.1088/0004-637X/800/1/11 is OK
- 10.1093/mnras/stx483 is OK
- 10.1038/s42254-019-0137-0 is OK
- 10.1086/170951 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1746

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1746, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@martin-millon - please make a last check of the PDF proof in https://github.com/openjournals/joss-papers/pull/1746 (I'll do the same). 

I plan to loop back on this in the morning my time to process/accept this.

**Comment by martin-millon** [comment]
@arfon - I've been through the paper one more time and I don't have anything to change.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1309217686707228672) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1753
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02654](https://doi.org/10.21105/joss.02654)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@danhey, @coljac - many thanks for your reviews here ✨ 

@martin-millon - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02654/status.svg)](https://doi.org/10.21105/joss.02654)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02654">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02654/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02654/status.svg
   :target: https://doi.org/10.21105/joss.02654
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02654/status.svg)](https://doi.org/10.21105/joss.02654)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by martin-millon** [comment]
@arfon Is there a way with Whedon to get the .tex file from which the paper is generated? I would like to post it on the arXiv.

**Comment by arfon** [comment]
@martin-millon - not directly but you can hack it using [this script](https://github.com/mattpitkin/psrqpy/blob/master/paper/Makefile) from this issue: https://github.com/openjournals/joss/issues/132

**Comment by martin-millon** [comment]
Thanks  !
