### ISSUE TITLE
[PRE REVIEW]: StarBLAST: a scalable BLAST+ solution for the classroom

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2657]
**Submitting author:** @cosimichele (<a href="http://orcid.org/0000-0001-7609-1939">Michele Cosi</a>)
**Repository:** <a href="https://github.com/LyonsLab/StarBLAST/" target ="_blank">https://github.com/LyonsLab/StarBLAST/</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @cosimichele. **Currently, there isn't an JOSS editor assigned** to your paper.

@cosimichele if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (478.6 files/s, 36279.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         4            116              0            447
TeX                              1              9              0            127
reStructuredText                 6            180            288            122
Python                           2             29             33             71
DOS Batch                        1              8              1             26
CSS                              1              1              1             16
JavaScript                       3              1              0             14
make                             1              4              7              9
JSON                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            20            348            330            838
-------------------------------------------------------------------------------


Statistical information for the repository '2657' was gathered on 2020/09/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Michele Cosi CoGe                2            57             21           41.05
Sateesh Peri                     1           112              0           58.95

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michele Cosi                 57          100.0          0.0               52.63
Sateesh Peri                 91           81.2          0.0                3.30
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2657 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
👋 @CosiMichele - this submission is too small for JOSS to review - see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort

Additionally, the education aspect makes me think it might be better suited to [JOSE](https://jose.theoj.org) if it was larger.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
