### ISSUE TITLE
[PRE REVIEW]: Minimalist And Customizable Optimization Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2658]
**Submitting author:** @jbuisine (<a href="http://orcid.org/0000-0001-6071-744X">Jérôme BUISINE</a>)
**Repository:** <a href="https://github.com/jbuisine/macop" target ="_blank">https://github.com/jbuisine/macop</a>
**Version:** v1.0.0
**Editor:** @melissawm
**Reviewers:** @stsievert, @torressa
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jbuisine. **Currently, there isn't an JOSS editor assigned** to your paper.

@jbuisine if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.36 s (424.2 files/s, 105956.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            59           7168             58          10148
JavaScript                      11           2200           2239           8326
SVG                              1              0              0           2671
Python                          31            635            793           1114
CSS                              4            164             34            642
reStructuredText                39            681            563            265
Markdown                         3            104              0            178
TeX                              1             10              0            124
YAML                             2             10              4             51
make                             1              5              6             11
Bourne Shell                     1              3              2              8
-------------------------------------------------------------------------------
SUM:                           153          10980           3699          23538
-------------------------------------------------------------------------------


Statistical information for the repository '2658' was gathered on 2020/09/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jérôme BUISINE                  39         17309           2002          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jérôme BUISINE            15307           88.4          1.1               17.99
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/0-306-48056-5_11 is OK
- 10.1109/TEVC.2007.892759 is OK
- 10.1016/j.cor.2006.02.008 is OK
- 10.1109/TEVC.2013.2239648 is OK
- 10.1007/s00158-004-0465-1 is OK
- 10.1109/ICMLA.2007.35 is OK
- 10.3390/rs10071117 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02658/joss.02658/10.21105.joss.02658.pdf)

**Comment by danielskatz** [comment]
👋 @jbuisine - thanks for your submission.  The next step will be an internal discussion by JOSS editors about the scope, which will take about a week, then we will get back to you about the next steps

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jbuisine upon initial inspection our board has decided this work may be in scope for JOSS. I will no proceed find an editor to handle this work. We do feel the paper needs a lot of improvement so please do work with the editor to get it improved, likely prior to the formal review stage.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @melissawm as editor

**Comment by whedon** [comment]
@melissawm has been invited to edit this submission.

**Comment by jbuisine** [comment]
@Kevin-Mattheus-Moerman Thank you for your answer, I am of course available for any modification of the document in order to improve it.

**Comment by melissawm** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by melissawm** [comment]
Hello, @jbuisine ! Before we proceed into the review stage, I'd like to suggest a careful review of JOSS's [Submission Requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). More specifically, I would suggest a stronger statement of need and a description of where this software fits into the current landscape, as it's not clear what differentiates it from existing optimization/OR frameworks. Also, if this was created to solve a particular research problem, I would encourage it to be cited somewhere in the paper. Please let me know if you have any questions or comments!

**Comment by jbuisine** [comment]
Hello @melissawm, thank you for your advice, I will take it into account and modify the document in order to situate the package in the bibliography!

**Comment by jbuisine** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02658/joss.02658/10.21105.joss.02658.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02658/joss.02658/10.21105.joss.02658.pdf) :page_facing_up: :point_left:

**Comment by jbuisine** [comment]
Hello @melissawm, thanks to your advices, I generated a new version of the submited paper. I detailed the purpose and the need of this developed package during my thesis. 

Do not hesitate to tell me if something is not very clear or if something seems to be missing.

Thanks in advance.

**Comment by jbuisine** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02658/joss.02658/10.21105.joss.02658.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02658/joss.02658/10.21105.joss.02658.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
Hello, @jbuisine ! Thank you for the modifications. I noticed a number of typos, which I think might be corrected before the review stage - maybe going through an autocorrect feature. Another issue that I think might be worth noting is that the problem (or problems) being solved by the software are not explicitly mentioned in the software paper. From the context, I understand you are doing global optimization in an OR setting - is that correct? I think that is worth mentioning somewhere.

Finally: do you have any suggestions for potential reviewers from the list mentioned in the first comment on this issue? Thank you!

**Comment by jbuisine** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02658/joss.02658/10.21105.joss.02658.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02658/joss.02658/10.21105.joss.02658.pdf) :page_facing_up: :point_left:

**Comment by jbuisine** [comment]
Hello @melissawm,

Thank you again for your feedback. I have updated the paper accordingly, I hope this is more understandable.

That's right, the idea is to propose a generic tool allowing to refrain from some recurrent concepts when implementing operational search algorithms (solution evaluation, hierarchical management of algorithms, backups, algorithm reloading). As the tool is not specific, the user could implement his algorithm without having to overload or be limited when faced with the specificity of an implementation. It is a tool developed within the framework of the thesis which allowed me to implement some specific algorithms quickly and which I would like to share.

Concerning the suggestions of reviewers, I was thinking about : `stsievert`, `jakobbossek` and `rowanc1` (I do not quote them directly here to avoid unwanted spam).

Thanks.

**Comment by melissawm** [comment]
Thank you, @jbuisine, that is much clearer now. I'll proceed with the reviewer's invitations. If you have any further questions or comments, please let me know!

**Comment by melissawm** [comment]
:wave: Hello @stsievert, @rowanc1 would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html Let me know if you need any more information. Thank you!

**Comment by rowanc1** [comment]
Hi @melissawm, I don't have time at this point, sorry.

**Comment by stsievert** [comment]
@melissawm yes, I can review this.

**Comment by melissawm** [comment]
Thanks, @stsievert ! I'll add you as a reviewer but won't start the review right away as we're still missing another reviewer.

**Comment by melissawm** [comment]
@whedon assign @stsievert as reviewer

**Comment by whedon** [comment]
OK, @stsievert is now a reviewer

**Comment by melissawm** [comment]
Hello @torressa, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html Let me know if you need any more information. Thank you!

**Comment by torressa** [comment]
Hey @melissawm, definitely keen, a bit swamped at the minute, so may be two/three weeks.
If that's alright, then go ahead :)

**Comment by melissawm** [comment]
Thank you @torressa! If @jbuisine is ok with this timeframe, we can go ahead.

**Comment by jbuisine** [comment]
Hello, I agree, this is not a problem for me.

**Comment by melissawm** [comment]
Great! Then I'll add the second reviewer and open the review issue. This issue here will be closed, and all further communication and work will be done on the REVIEW issue.

**Comment by melissawm** [comment]
@whedon add @torressa as reviewer

**Comment by whedon** [comment]
OK, @torressa is now a reviewer

**Comment by melissawm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2812.
