### ISSUE TITLE
[PRE REVIEW]: c212: An R Package for the Detection of Safety Signals in Clinical Trials Using Body-Systems (System Organ Classes)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2659]
**Submitting author:** @rcarragh (<a href="http://orcid.org/0000-0002-0120-625X">Raymond Bernard Carragher</a>)
**Repository:** <a href="https://github.com/rcarragh/c212" target ="_blank">https://github.com/rcarragh/c212</a>
**Version:** 0.98
**Editor:** @csoneson
**Reviewers:** @rrrlw, @emilydolson
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @rcarragh. **Currently, there isn't an JOSS editor assigned** to your paper.

@rcarragh if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.44 s (310.9 files/s, 98576.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                              106           3030            870          17624
C++                             14           3345           1156          14529
C/C++ Header                    14            354             45           1661
XML                              1              0              1            310
TeX                              1             33              0            271
Markdown                         1             37              0            172
-------------------------------------------------------------------------------
SUM:                           137           6799           2072          34567
-------------------------------------------------------------------------------


Statistical information for the repository '2659' was gathered on 2020/09/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Raymond Carragher                2         21092              2          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Raymond Carragher         21090          100.0          0.0                5.69
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #2659 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Raymond Carragher, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon.rb:201:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon.rb:201:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon.rb:198:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon.rb:198:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon.rb:91:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1198/jasa.2010.tm09329 is OK
- 10.1002/sim.5310 is OK
- doi:10.1201/9781420011302.fmatt is OK
- 10.1111/j.0006-341X.2004.00186.x is OK
- 10.1080/10543406.2010.520181 is OK
- 10.1080/19466315.2017.1409134 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.5281/zenodo.3235282 is OK
- 10.1002/sim.8304 is OK
- 10.1002/sim.8495 is OK
- 10.1002/sim.8563 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.2307/2346101 is INVALID
- http://dx.doi.org/10.1016/j.jspi.2007.06.006 is INVALID because of 'https://doi.org/' prefix
```

**Comment by danielskatz** [comment]
@rcarragh - As you can see by comments in this issue from whedon, there are some problems to be fixed.  

In the repo, I see no license.  I also see no README.

In the paper, you need to change the multiple affiliation line to have commas between affiliations - see https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

You also have some extra metadata in the paper which may cause problems once the affiliations part is solved.

Finally, there are 2 DOI issues in the bib file.

Please make changes to the paper (and bib), then add ```@whedon generate pdf``` as a new comment here to regenerate the PDF.  Feel free to iterate.

I will mark this as paused for now.  Once you think you are ready to proceed, please tag @openjournals/joss-eics to let me (or the AEiC on duty) know.

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02659/joss.02659/10.21105.joss.02659.pdf)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02659/joss.02659/10.21105.joss.02659.pdf)

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02659/joss.02659/10.21105.joss.02659.pdf)

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02659/joss.02659/10.21105.joss.02659.pdf)

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02659/joss.02659/10.21105.joss.02659.pdf)

**Comment by rcarragh** [comment]
@openjournals/joss-eics

Apologies for the errors in the author affiliations section and any additional overhead caused.
(I couldn't see a full compiled version through the whedon web test interface before I submitted the paper, although I could generate a pdf wth pandoc.)

I've made the following changes:

1. I have fixed the affiliations section.
2. I have added a LICENSE file to the repository.
3. I have added a README file to the repository.
4. I have updated paper.bib to address the 2 DOI issues.
5. I have removed metadata from paper.md (csl, output, header-includes)

I have been able to generate a PDF as suggested and to me it looks ok, so hopefully this has addressed the issues reported.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.2517-6161.1995.tb02031.x is OK
- 10.1198/jasa.2010.tm09329 is OK
- 10.1002/sim.5310 is OK
- 10.1016/j.jspi.2007.06.006 is OK
- doi:10.1201/9781420011302.fmatt is OK
- 10.1111/j.0006-341X.2004.00186.x is OK
- 10.1080/10543406.2010.520181 is OK
- 10.1080/19466315.2017.1409134 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.5281/zenodo.3235282 is OK
- 10.1002/sim.8304 is OK
- 10.1002/sim.8495 is OK
- 10.1002/sim.8563 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @csoneson - would you be willing to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @rcarragh - I will handle this submission. Do you have any suggestions for suitable reviewers (e.g., from the spreadsheet linked in the first post above)?

Looking at your repository, it seems that you have different licenses indicated in the `DESCRIPTION` file and in the repository itself - could you please harmonize that? I also notice that your package doesn't seem to have any unit tests. We strongly suggest to have these; at the very least, there must be an objective way for the reviewers to verify the correct functionality of the package (see e.g. the review criteria [here](https://joss.readthedocs.io/en/latest/review_checklist.html)).

**Comment by rcarragh** [comment]
@csoneson - I will make these updates (licence and tests) and let you know when they are complete. 
Thanks

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02659/joss.02659/10.21105.joss.02659.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02659/joss.02659/10.21105.joss.02659.pdf) :page_facing_up: :point_left:

**Comment by rcarragh** [comment]
@csoneson - I have fixed the DESCRIPTION/LICENSE file issue and added a new directory to the repository called "test". 
This contains a README explaining the contents of the directory. 
The are tests for package functionality, covering all the main use cases and there are demonstration code files for the package in the 
subdirectory ./demo.

Starting from the bottom of the spreadsheet a couple of possible reviewers would be:

ChristopherLucas (R/C++/Bayesian statitics)
emilydolson (C++/R)

but someone with a statistics/R/C++ background should be suitable.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02659/joss.02659/10.21105.joss.02659.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02659/joss.02659/10.21105.joss.02659.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
👋 @emilydolson, @rowlandseymour, @stulacy, @rrrlw - would two of you be interested in reviewing this submission for JOSS? 

> c212: An R Package for the Detection of Safety Signals in Clinical Trials Using Body-Systems

**Comment by rrrlw** [comment]
I would only be able to superficially review the methodology. If a second reviewer would be willing to take that on, I’d be happy to review the software implementation.

**Comment by emilydolson** [comment]
I can review it, but I don't have any experience with clinical trial design, so I may not be the best choice (especially if the goal would be for me to focus on the methodology).

**Comment by csoneson** [comment]
Thanks @rrrlw and @emilydolson for your availability! Let me try to find a complementary third reviewer who would be more geared towards clinical trial methodology - I'll get back to you.

**Comment by rowlandseymour** [comment]
I'm in the same position as Emily. I'm happy to review it, but don't have any experience with clinical trials.

**Comment by csoneson** [comment]
👋 Just a quick update to say that I have contacted several possible reviewers on the more methodological side offline, hoping to have a positive response there.

**Comment by csoneson** [comment]
Hi again - turns out it's not so easy to find a reviewer with both clinical trial methodology expertise and free time :). I have some leads that are still open, and I will keep looking (we certainly want this aspect evaluated as well), but to avoid holding up the submission at this stage, I suggest that we start the review in the meanwhile - @rrrlw and @emilydolson, are you still available and willing to review the package (if so, @rowlandseymour, I hope we can come back to you for another submission in the future - thanks for volunteering!)

**Comment by rrrlw** [comment]
Sure, happy to help!

**Comment by emilydolson** [comment]
Me too!

**Comment by csoneson** [comment]
Brilliant, thanks both! I'll assign you and start the review issue.

**Comment by csoneson** [comment]
@whedon assign @rrrlw as reviewer

**Comment by whedon** [comment]
OK, @rrrlw is now a reviewer

**Comment by csoneson** [comment]
@whedon add @emilydolson as reviewer

**Comment by whedon** [comment]
OK, @emilydolson is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2706.
