### ISSUE TITLE
[PRE REVIEW]: Bézier

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#266]
**Submitting author:** @dhermes (<a href="http://orcid.org/0000-0001-7366-173X">Daniel Hermes</a>)
**Repository:** <a href="https://github.com/dhermes/bezier" target ="_blank">https://github.com/dhermes/bezier</a>
**Version:** 0.3.0
**Editor:** @arfon
**Reviewer:** @tacaswell

**Author instructions**

Thanks for submitting your paper to JOSS @dhermes. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dhermes if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by tacaswell** [comment]
:wave: I can volunteer to review this (sorry if I am out of order here).

**Comment by arfon** [comment]
> 👋 I can volunteer to review this (sorry if I am out of order here).

✨ thanks @tacaswell!

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @tacaswell as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @tacaswell

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/267. Feel free to close this issue now!

**Comment by arfon** [comment]
Thanks again @tacaswell - please head over to #267 for the actual review.
