### ISSUE TITLE
[PRE REVIEW]: Hardware-Control: Instrument Control and Automation Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2661]
**Submitting author:** @Grant-Giesbrecht (<a href="http://orcid.org/0000-0003-2885-4801">Grant Giesbrecht</a>)
**Repository:** <a href="https://bitbucket.org/berkeleylab/hardware-control/src/main/" target ="_blank">https://bitbucket.org/berkeleylab/hardware-control/src/main/</a>
**Version:** v1.0.0
**Editor:** @timtroendle
**Reviewers:** @aquilesC, @untzag, @garrettj403
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Grant-Giesbrecht. **Currently, there isn't an JOSS editor assigned** to your paper.

@Grant-Giesbrecht if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.89 s (206.5 files/s, 22070.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          78           2938           1973           9008
SVG                             39              7             10           3750
Markdown                         8            143              0            455
JSON                             9              2              0            411
reStructuredText                43            196            225            313
YAML                             2              0              0             37
DOS Batch                        1              8              1             26
TeX                              1              4              0             14
TOML                             1              5              3             11
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           183           3307           2219          14034
-------------------------------------------------------------------------------


Statistical information for the repository '2661' was gathered on 2020/09/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Arun Persaud                   170         31771          40152           41.19
Brian Mak                        6           128            100            0.13
Grant Giesbrecht               766         54705          34562           51.12
Grant-Giesbrecht                17           500            623            0.64
GrantGiesbrecht                  1            11              4            0.01
ROOTS teststand                 32           687            811            0.86
STS50-teststand-user            50           816            769            0.91
Schuyler Freeman                 1          1776              0            1.02
Timo Bauer                      57          3469           3092            3.76
Timo Bauer @STS50 Te             8           157            115            0.16
bmac3                            3           166            121            0.16
unknown                          5            55             33            0.05

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Arun Persaud               7284           22.9          2.1                8.06
Brian Mak                   112           87.5          0.6               10.71
Grant Giesbrecht           6209           11.3          4.8                9.50
Timo Bauer                  271            7.8          9.3               10.33
bmac3                        40           24.1          1.1                5.00
unknown                       3            5.5          9.1               33.33
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02661/joss.02661/10.21105.joss.02661.pdf)

**Comment by danielskatz** [comment]
👋 @Grant-Giesbrecht  - thanks for your submission.  Can you explain (and probably add to the paper) some examples of how this is (or will be) used in research, including what kinds of research?

**Comment by Grant-Giesbrecht** [comment]
We're using this software in two different projects run by our research group. One project, ROOTS, uses hardware-control to interface with data acquisition modules and power supplies for a neutron-based measurement of carbon content in soil. The other project uses hardware-control to automate instrumentation used to run our compact RF particle accelerator. As for what type of research our software can be used for, the really nice part about our software is that it's very general and can be used for any type of experimental research that relies upon instrumentation. This is because it solves the broad problem of instrument control. So although we are using it for particle physics experiments, it could just as easily be applied to other fields like engineering or other sciences.

**Comment by Grant-Giesbrecht** [comment]
I also added a brief description of these applications to the paper.

**Comment by danielskatz** [comment]
@whedon generate pdf

(@Grant-Giesbrecht - note that you can do this too if you make changes - whedon commands need to be at the start of a comment)

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02661/joss.02661/10.21105.joss.02661.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02661/joss.02661/10.21105.joss.02661.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @timtroendle - I wonder if this might be a good first submission for you to edit? Perhaps you can check with your onboarding buddy

**Comment by danielskatz** [comment]
@whedon invite @timtroendle as editor

**Comment by whedon** [comment]
@timtroendle has been invited to edit this submission.

**Comment by timtroendle** [comment]
Yes, can do.

**Comment by timtroendle** [comment]
@whedon assign @timtroendle as editor

**Comment by whedon** [comment]
OK, the editor is @timtroendle

**Comment by timtroendle** [comment]
@danielskatz @sjpfenninger The license file is deviating slightly from [BSD-3-Clause-LBNL](https://opensource.org/BSD-3-Clause-LBNL). Is this fine or does this require a fix? Also: is there an automatic way for me to check the license?

**Comment by sjpfenninger** [comment]
We _do_ require an OSI approved license so this must be fixed, i.e. there should be a LICENSE file that contains the exact text of the BSD-3-Clause-LBNL license. Not aware of any automatic way to check this but maybe @danielskatz can enlighten us :-)

**Comment by danielskatz** [comment]
There's no automatic way to check that I know.
And, yes, this does need to be fixed (though I don't see the difference immediately)

Also, please tag @openjournals/joss-eics in the future to get the on-duty AEiC (which is no longer me)

**Comment by timtroendle** [comment]
Thank you both!

@Grant-Giesbrecht could you please apply this tiny fix so that the license is in line with the [OSI version](https://opensource.org/BSD-3-Clause-LBNL)? This concerns the first line only, which should read like the following:

> Copyright (c) XXXX, The Regents of the University of California, through Lawrence Berkeley National Laboratory (subject to receipt of any required approvals from the U.S. Dept. of Energy). All rights reserved.

**Comment by Grant-Giesbrecht** [comment]
Good catch - fixed it!

**Comment by timtroendle** [comment]
Perfect. I will start looking for reviewers for your submission. If you can suggest anyone, please let me know @Grant-Giesbrecht .

**Comment by timtroendle** [comment]
:wave: @1313e & @bhajay, would any of you be willing to review this submission for JOSS?

**Comment by 1313e** [comment]
@timtroendle I have a feeling one can only truly review this package if they also have access to some of the physical instruments that it is programmed to interact with.
As I don't have these laying around, I feel like I am not the right person to review this.

**Comment by timtroendle** [comment]
Ok, I understand.

**Comment by timtroendle** [comment]
👋 @aquilesC, @untzag, @garrettj403, @ksunden, @sptennak, @caldarolamartin, would any of you be willing to review this submission for JOSS?

**Comment by aquilesC** [comment]
I can review it!

**Comment by timtroendle** [comment]
Thanks @aquilesC for the offer!

**Comment by timtroendle** [comment]
@whedon add @aquilesC as reviewer

**Comment by whedon** [comment]
OK, @aquilesC is now a reviewer

**Comment by untzag** [comment]
@timtroendle I can review this---it looks very relevant to what I'm interested in right now

**Comment by timtroendle** [comment]
That's great @untzag, thanks!

**Comment by timtroendle** [comment]
@whedon add @untzag as reviewer

**Comment by whedon** [comment]
OK, @untzag is now a reviewer

**Comment by garrettj403** [comment]
Hi @timtroendle I can review this project as well.

**Comment by timtroendle** [comment]
Thanks @garrettj403 , that's good to hear.

**Comment by timtroendle** [comment]
@whedon add @garrettj403 as reviewer

**Comment by whedon** [comment]
OK, @garrettj403 is now a reviewer

**Comment by timtroendle** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2688.

**Comment by timtroendle** [comment]
@bhajay, @ksunden, @sptennak, @caldarolamartin, thank you for considering to review this submission. I started the review with @aquilesC, @untzag, and @garrettj403 as reviewers.
