### ISSUE TITLE
[REVIEW]: Seq2Pat: Sequence-to-Pattern Generation Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2662]
**Submitting author:** @skadio (<a href="http://orcid.org/0000-0002-4672-6830">Serdar Kadioglu</a>)
**Repository:** <a href="https://github.com/fidelity/seq2pat" target ="_blank">https://github.com/fidelity/seq2pat</a>
**Version:** v1.1.1
**Editor:** @galessiorob
**Reviewers:** @HaoZeke, @shreyasbapat, @TimKam
**Archive:** Pending

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/00e34b91f8ffa673152104acb0d22ad3/status.svg)](https://joss.theoj.org/papers/00e34b91f8ffa673152104acb0d22ad3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/00e34b91f8ffa673152104acb0d22ad3"><img src="https://joss.theoj.org/papers/00e34b91f8ffa673152104acb0d22ad3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/00e34b91f8ffa673152104acb0d22ad3/status.svg)](https://joss.theoj.org/papers/00e34b91f8ffa673152104acb0d22ad3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fidelity/seq2pat" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@HaoZeke, @TimKam & @shreyasbapat, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @galessiorob know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fidelity/seq2pat">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@skadio) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fidelity/seq2pat">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@skadio) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fidelity/seq2pat">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@skadio) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @HaoZeke, @shreyasbapat it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1609/aaai.v33i01.33011495 is OK
- 10.1007/978-3-319-42849-9 is OK
- 10.1609/aaai.v33i01.33011495 is OK
- 10.1007/978-3-319-46227-1_20 is OK

MISSING DOIs

- 10.1287/ijoc.2019.0937 may be a valid DOI for title: Exact Multiple Sequence Alignment by Synchronized Decision Diagrams

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02662/joss.02662/10.21105.joss.02662.pdf)

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02662/joss.02662/10.21105.joss.02662.pdf)

**Comment by galessiorob** [comment]
@skadio the last and third to last cited reference need DOIs (not sure why whedon is not catching both of them), would you mind adding them, please? 🙏

**Comment by shreyasbapat** [comment]
> @skadio the last and third to last cited reference need DOIs (not sure why whedon is not catching both of them), would you mind adding them, please? 🙏

I will review as soon as this is done :D

**Comment by skadio** [comment]
Interesting. We had a PR yesterday to fix just that. @takojunior can you take another look at the whedon output above?

**Comment by takojunior** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1609/aaai.v33i01.33011495 is OK
- 10.1007/978-3-319-42849-9 is OK
- 10.1609/aaai.v33i01.33011495 is OK
- 10.1287/ijoc.2019.0937 is OK
- 10.1137/1.9780898719789 is OK
- 10.1007/978-3-319-46227-1_20 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by takojunior** [comment]
Hi @galessiorob, @shreyasbapat, @HaoZeke, @skadio 

The missing DOIs are updated. Thanks.

**Comment by shreyasbapat** [comment]
Thanks, I will now move forward with the review.

**Comment by galessiorob** [comment]
@whedon add @TimKam as reviewer

**Comment by whedon** [comment]
OK, @TimKam is now a reviewer

**Comment by skadio** [comment]
Thank you @TimKam for kindly agreeing to review our work!

**Comment by TimKam** [comment]
I have submitted my initial evaluation here: https://github.com/fidelity/seq2pat/issues/11.

Regarding the following evaluation result, I'd like to get the perspective of an editor (@galessiorob):
In essence, the library is a wrapper around research code that has been written for the corresponding [AAAI 2019 paper](https://aaai.org/ojs/index.php/AAAI/article/view/3962). The authors should be more clear about this fact. (The paper is prominently linked; for sure, the authors did not aim to disguise this fact.) This does not mean that the contribution is not valuable, but it certainly has implications on the _additional effort_ that was necessary to create the library.

Limitations: I don't have sufficient knowledge of sequence-to-pattern generation and multi-valued decision diagrams to judge aspects of the contribution that go beyond the software engineering perspective (I merely recognize some of the authors cited in the foundational AAAI '19 paper from "my" community).

**Comment by galessiorob** [comment]
Thanks for raising this question @TimKam! Based on our existing lineaments while brief, this submission is valid, as for the "extensibility/adaptability" for code that builds on existing work I _think_ this paper also passes but let me get an editor in chief's opinion.

**Comment by Kevin-Mattheus-Moerman** [comment]
@skadio thanks for your submission to JOSS. Several reviewers raised concerns in terms of this work potentially being out of scope. The handling editor, @galessiorob, consulted the JOSS editorial board who has now also reviewed and discussed this work in detail. Unfortunately the editorial board agreed that this work is out of scope for JOSS as it stands. In particular it is deemed too minor in terms of its functionality (see [our guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)). This conclusion does not mean the software is not useful or of a low quality, it merely means that in terms of required amount of scholarly content this work is out of scope for JOSS. 

I will reject this submission at this point. However, if you continue to develop and expand this work, we would be happy to reconsider it as a re-submission in the future. Alternatively you could archive a copy of this work on a service like ZENODO to obtain a DOI which users can cite.

Dr Kevin Moerman
_AEiC JOSS_

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by skadio** [comment]
@Kevin-Mattheus-Moerman @galessiorob 

I would like to thank you again for your time and service! I have read the guidelines as well as your response about the Scope and kindly disagree, especially when compared to other submissions that I have been part of. Leaving this aside, we already received an initial evaluation from @TimKam. Thank you very much @TimKam, we incorporated some of the input already and your pointers will help us improve over the current work. 

In return for the time of the JOSS reviewers here, I agreed to provide evaluations on a number of submissions and encourage our main co-authors here to do the same. 

This was our first submission to JOSS, thank you again for your feedback! 

Best,
Serdar
