### ISSUE TITLE
[REVIEW]: rFBP: Replicated Focusing Belief Propagation algorithm

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2663]
**Submitting author:** @Nico-Curti (<a href="http://orcid.org/0000-0001-5802-1195">Nico Curti</a>)
**Repository:** <a href="https://github.com/Nico-Curti/rFBP" target ="_blank">https://github.com/Nico-Curti/rFBP</a>
**Version:** v1.0.3
**Editor:** @arokem
**Reviewers:** @justusschock, @DanielLenz
**Archive:** <a href="https://doi.org/10.5281/zenodo.4106174" target="_blank">10.5281/zenodo.4106174</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/7643779111039dbc7776ff49d2a6b1b0/status.svg)](https://joss.theoj.org/papers/7643779111039dbc7776ff49d2a6b1b0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7643779111039dbc7776ff49d2a6b1b0"><img src="https://joss.theoj.org/papers/7643779111039dbc7776ff49d2a6b1b0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7643779111039dbc7776ff49d2a6b1b0/status.svg)](https://joss.theoj.org/papers/7643779111039dbc7776ff49d2a6b1b0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Nico-Curti/rFBP" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@DanielLenz & @justusschock, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arokem know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Nico-Curti/rFBP">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Nico-Curti) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Nico-Curti/rFBP">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Nico-Curti) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @bblais, @justusschock it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1073/pnas.1608103113 is OK
- 10.1073/pnas.0700324104 is OK
- 10.1103/physrevlett.96.030201 is OK
- 10.1103/physreve.93.052313 is OK
- 10.1016/S0893-6080(05)80010-3 is OK
- 10.1103/physreve.90.052813 is OK
- 10.1088/1742-5468/2016/02/023301 is OK
- 10.1142/S0217984995001868 is OK
- 10.1103/physrevlett.75.2432 is OK
- 10.1088/1742-5468/2015/08/p08008 is OK

MISSING DOIs

- 10.1051/jphys:0198900500200305700 may be a valid DOI for title: Storage capacity of memory networks with binary couplings

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02663/joss.02663/10.21105.joss.02663.pdf)

**Comment by arokem** [comment]
After a private exchange with @bblais we've ascertained that he has an apparent conflict-of-interest, due to a recent joint publication with one of the authors of this paper. That means that we will have to find another reviewer to replace him here. For now, I will edit the checklist at the top to indicate that @bblais is no longer a reviewer and unassign him. Thanks @bblais! I hope we find another opportunity to call on you to review for JOSS.

**Comment by arokem** [comment]
👋 @DanielLenz, @zbeekman : one of the reviewers for this paper is unable to do the review. Would either of you be willing to step in as a reviewer for this article? I think that you would either be a very good match given your expertise.

**Comment by arokem** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by arokem** [comment]
@whedon remove @bblais as reviewer

**Comment by whedon** [comment]
OK, @bblais is no longer a reviewer

**Comment by DanielLenz** [comment]
@arokem Sure, I'd be happy to review this submission.

**Comment by arokem** [comment]
@whedon add @DanielLenz as reviewer

**Comment by whedon** [comment]
OK, @DanielLenz is now a reviewer

**Comment by arokem** [comment]
Thank you for stepping up! I have edited the comment at the top of this issue so that you now have a checklist that you can use to check off review criteria. Please let me know if you have any questions.

**Comment by DanielLenz** [comment]
Will do! This week is a bit busy - I'll do my best, but it might take me a couple of days.

**Comment by arokem** [comment]
No problem. We generally hope to complete all items in the review within approximately six weeks.

**Comment by justusschock** [comment]
@arokem I finished my review. Overall I really like the submission. Regarding the checklist above:
* So far there is no API Documentation / Only some docstrings
* The license file must be changed from Markdown to plain text

If the above mentioned points are finished, I don't see any blockers from my side.

**Comment by arokem** [comment]
@justusschock : thanks for these comments. 

@Nico-Curti  : you can start addressing these issues in the meanwhile.

@DanielLenz : have you had a chance to take a look?

**Comment by Nico-Curti** [comment]
Hi @justusschock, thanks for your comments. We are working on your issues and we will provide an updated version of the project documentation as soon as possible.

**Comment by DanielLenz** [comment]
@arokem Will finish my review this weekend!

**Comment by arokem** [comment]
Super. Thanks for the update!

**Comment by DanielLenz** [comment]
Hey @arokem , I've finished my review and agree with @justusschock in that I really like the submission and think the software is well-written and follows many best practices, big thanks for @Nico-Curti .

There are a couple of points that we raised on the projects github issue tracker which should be taken care of first. All of these are fairly minor and shouldn't take long.

Regarding the paper itself, there are a couple of minor points that I'll list here. All of these refer to the [latest draft compiled by wheadon](https://github.com/openjournals/joss-papers/blob/joss.02663/joss.02663/10.21105.joss.02663.pdf)

- The hyperlinks in the pdf didn't work for me. Is this normal or am I the only one experiencing this?
- Remove the line that contains the bibliography file name
- Affiliations: Please use one line per affiliation
- Can we move the "Joint first author" footnote closer to the author list, perhaps right next to the affiliations?
- First paragraph:
  - ~fast~ quickly converging
- Second paragraph:
  - ... has already been widely used...
- Third paragraph:
  - ... ill-posed conditions can be tackled
  - i.e. a prior known...
  - (_perfect learning_, Baldassi et al. ....)
- Fourth paragraph:
  - `seems most promising` isn't particularly specific - perhaps `... spin-glass models have emerged as the most promising ones`?
- Fifth paragraph
  - I don't quite understand the first reference: Zecchina et al. (Baldassi et al., 2016a). Zecchina isn't listed in the bibliography either.

Thanks for working on this project over the years and for submitting to JOSS, I'm really looking forward to seeing it published!

Could you ping us here once these minor issues are addressed? Thank you!

**Comment by arokem** [comment]
Thanks @DanielLenz for these comments. 
 
@Nico-Curti : please let us know when you've had a chance to address everything.

**Comment by Nico-Curti** [comment]
Hi @DanielLenz 
We worked on your issues, trying to address all of your points.

> One point that I ran into, but didn't raise an issue about is the loading of the C++ library on Mac OS with clang to run the tests. You mention this in your travis config and I can confirm the issue, but I'm unsure how to address it.

We don't have a MacOS machine available in any sort and we aren't experts on this system. We have tried to solve the issue using the travis CI but unfortunately we haven't found any patch. If someone else have any suggestion please let us know.

> The hyperlinks in the pdf didn't work for me. Is this normal or am I the only one experiencing this?

The hyperlinks don't work on the online version of the paper as displayed by github. They seems to work fine if you download the pdf. 

> Remove the line that contains the bibliography file name

We have removed the duplicated lines from the paper as you have pointed out. Let us know if the issue persists.

> Affiliations: Please use one line per affiliation

We follow the guidelines on the JOSS website but the affiliations are still displayed on the same line. Maybe @arokem could suggest us how we can fix it.

> Can we move the "Joint first author" footnote closer to the author list, perhaps right next to the affiliations?

We noticed that other already published papers in JOSS has the footnote at the end of the page. Also in this case we can fix this issue but we need some help by @arokem 

About the typos that you have highlighted we have followed all your comments and fix the paper document.

**Comment by Nico-Curti** [comment]
Hi @arokem ,
With the latest commits we think we have answered all the issues raised by the reviewers.
We will wait for some feedback.

**Comment by DanielLenz** [comment]
Thanks for addressing all the issues @Nico-Curti ! I'll give another detailed look this weekend, but we should be good to go :)

**Comment by DanielLenz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02663/joss.02663/10.21105.joss.02663.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02663/joss.02663/10.21105.joss.02663.pdf) :page_facing_up: :point_left:

**Comment by zbeekman** [comment]
Sorry to have missed the boat on this one, looks interesting! Thanks for inviting me and I'll keep my eye out for the final publication!

**Comment by DanielLenz** [comment]
Hi @arokem , @Nico-Curti ,

I've taken another detailed look at the paper and the repo, and I'm happy to say that I recommend the publication at this point. 

There are some minor formatting issues that we discussed, perhaps @arokem can shed some light on this.

Thanks again for your submission and for including the feedback so quickly!

**Comment by arokem** [comment]
Thanks @DanielLenz! I will look into the formatting issues.

@justusschock : when you get a chance, could you please take a look and see whether the outstanding issues you had are addressed in the revision? In particular, I see that you have two check-boxes un-checked at this point. Are both of these points (license and documentation of functionality) addressed?

**Comment by justusschock** [comment]
@arokem, yes they have all been addressed. 
I would also recommend the publication at this point.

**Comment by Nico-Curti** [comment]
Hi @arokem,
I have solved both the issues.
Let me know if everything is ok now.

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02663/joss.02663/10.21105.joss.02663.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02663/joss.02663/10.21105.joss.02663.pdf) :page_facing_up: :point_left:

**Comment by arokem** [comment]
Thank you. Could you please make sure that the Krauth and Mézard reference has the same format as the other references? It currently has the word "In" before the name of the journal (not needed) and the word "Vol" explicitly mentioned. It should look like this:

Krauth, W., & Mézard, M. (1989). Storage capacity of memory networks with binary couplings. *Journal de Physique*, 50, 3057–3066. doi:10.1051/jphys: 0198900500200305700

**Comment by Nico-Curti** [comment]
Hi @arokem,
now it should work properly. 
Sorry for the inconvenience.

**Comment by arokem** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02663/joss.02663/10.21105.joss.02663.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02663/joss.02663/10.21105.joss.02663.pdf) :page_facing_up: :point_left:

**Comment by arokem** [comment]
Thanks! Looks good. At this point, could you please:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by Nico-Curti** [comment]
Hi @arokem.
We have just uploaded the latest version of the package as [v1.0.3](https://github.com/Nico-Curti/rFBP/releases/tag/v1.0.3). The corresponding Zenodo doi is [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4106175.svg)](https://doi.org/10.5281/zenodo.4106175).
Let me know if everything is ok now.

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.4106174 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4106174" target="_blank">10.5281/zenodo.4106174</a> is the archive.

**Comment by arokem** [comment]
@whedon set v1.0.3 as version

**Comment by whedon** [comment]
OK. v1.0.3 is the version.

**Comment by arokem** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1073/pnas.1608103113 is OK
- 10.1073/pnas.0700324104 is OK
- 10.1103/physrevlett.96.030201 is OK
- 10.1103/physreve.93.052313 is OK
- 10.1016/S0893-6080(05)80010-3 is OK
- 10.1051/jphys:0198900500200305700 is OK
- 10.1103/physreve.90.052813 is OK
- 10.1088/1742-5468/2016/02/023301 is OK
- 10.1142/S0217984995001868 is OK
- 10.1103/physrevlett.75.2432 is OK
- 10.1088/1742-5468/2015/08/p08008 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1828

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1828, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
Hi @Nico-Curti, I'm the EIC on duty this week, and doing some final checks before publishing your article. Can you fix a few small things?

- [ ] The paper is missing a Statement of Need section, which is a required element (as per [our docs](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)); not sure how this didn't come up before, since whedon looks for this at submission, but it might have been because of the original compilation problems.
- [ ] In the third paragraph, please put a comma after "i.e"
- [ ] On the second page, this is a bit confusing: "...despite it is a quite efficient implementation the Julia programming language stays on difficult and far from many users." Can you rewrite this bit?
- [ ] In the same paragraph, I see "... C++ library called Scorer for further details)", which seems to be missing the starting parenthesis.

**Comment by Nico-Curti** [comment]
Hi @kyleniemeyer, 
We have just uploaded a reviewed version of the paper following your suggestions.
Please let me know if there are other issues.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02663/joss.02663/10.21105.joss.02663.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02663/joss.02663/10.21105.joss.02663.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@Nico-Curti  Looks good, thanks!

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1073/pnas.1608103113 is OK
- 10.1073/pnas.0700324104 is OK
- 10.1103/physrevlett.96.030201 is OK
- 10.1103/physreve.93.052313 is OK
- 10.1016/S0893-6080(05)80010-3 is OK
- 10.1051/jphys:0198900500200305700 is OK
- 10.1103/physreve.90.052813 is OK
- 10.1088/1742-5468/2016/02/023301 is OK
- 10.1142/S0217984995001868 is OK
- 10.1103/physrevlett.75.2432 is OK
- 10.1088/1742-5468/2015/08/p08008 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1832

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1832, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1318608238808616969) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1833
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02663](https://doi.org/10.21105/joss.02663)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @Nico-Curti on your article's publication in JOSS!

Many thanks to @justusschock and @DanielLenz for reviewing this, and @arokem for editing it.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02663/status.svg)](https://doi.org/10.21105/joss.02663)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02663">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02663/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02663/status.svg
   :target: https://doi.org/10.21105/joss.02663
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02663/status.svg)](https://doi.org/10.21105/joss.02663)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
