### ISSUE TITLE
[REVIEW]: DARE Platform: a Developer-Friendly and Self-Optimising Workflows-as-a-Service Framework for e-Science on the Cloud

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2664]
**Submitting author:** @iaklampanos (<a href="http://orcid.org/0000-0003-0478-4300">Iraklis Klampanos</a>)
**Repository:** <a href="https://gitlab.com/project-dare/dare-platform" target ="_blank">https://gitlab.com/project-dare/dare-platform</a>
**Version:** v3.5
**Editor:** @danielskatz
**Reviewer:** @rafaelfsilva, @Himscipy
**Archive:** <a href="https://doi.org/10.5281/zenodo.4095463" target="_blank">10.5281/zenodo.4095463</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/83dd4a3b62de116a4e5fc17d871f18e7/status.svg)](https://joss.theoj.org/papers/83dd4a3b62de116a4e5fc17d871f18e7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/83dd4a3b62de116a4e5fc17d871f18e7"><img src="https://joss.theoj.org/papers/83dd4a3b62de116a4e5fc17d871f18e7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/83dd4a3b62de116a4e5fc17d871f18e7/status.svg)](https://joss.theoj.org/papers/83dd4a3b62de116a4e5fc17d871f18e7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/project-dare/dare-platform" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rafaelfsilva & @Himscipy, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/project-dare/dare-platform">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@iaklampanos) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/project-dare/dare-platform">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@iaklampanos) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rafaelfsilva, @Himscipy it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1177/1094342016649766 is OK
- 10.1109/eScience.2019.00079 is OK
- 10.6084/m9.figshare.3115156.v2 is OK
- 10.1109/eScience.2019.00042 is OK
- 10.5281/zenodo.3697898 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02664/joss.02664/10.21105.joss.02664.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02664/joss.02664/10.21105.joss.02664.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @rafaelfsilva & @Himscipy - thanks again for agreeing to review this submission. Please be sure to read the comments above, and let me know if you have any questions.  Basically, your job is to check the article proof and repository and check items off your checklist above.

If you see small problems that need to be discussed, feel free to discuss them here.  But if you can, create a new issue in the <a href="https://gitlab.com/project-dare/dare-platform" target="_blank">target repository</a> and link to this review thread in that issue to create corresponding breadcrumb trail here.

I look forward to seeing how this review goes!

**Comment by rafaelfsilva** [comment]
@iaklampanos, I was checking the review process guidelines for JOSS and one of the criteria is **Contribution and authorship**, which states that the person submitting the paper should have done major contributions to the software. Looking into the DARE repository, I observed that you have done contributions to the software, but mostly to the JOSS paper. I have also noticed that the second author of the paper (Chrysoula Themeli) did most of the software development (according to the repository list of contributions). Could you please elaborate more regarding contributions to the software? Thank you

**Comment by iaklampanos** [comment]
Hello @rafaelfsilva and thanks for agreeing to review our submission.

The DARE platform, main technical product of the H2020 DARE project, comprises multiple repositories and software owned by different entities (people and organisations), as mentioned in the paper. I have authored one of the components (the d4p-registry registry) and I am the technical coordinator of the project, responsible for the overall technical/software direction and for the delivery of the integrated dare-platform. Chrysoula Themeli is currently the main DARE developer in the Demokritos team. The other authors have contributed to core components of the platform (listed in the paper) as well as to their integration via software and otherwise.

**Comment by rafaelfsilva** [comment]
Thank you for the clarification @iaklampanos. I went through all other repositories mentioned in the README and could attest all contributions. As these components are part of the DARE platform, maybe they could be linked using [Git Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)?

**Comment by iaklampanos** [comment]
Thanks, this is certainly something we can discuss internally for a future release. However, as each of the components are meant to be deployed independently as containerised applications in a k8s cluster we haven't considered it so far.

**Comment by danielskatz** [comment]
That's certainly not needed for JOSS review, but it's an interesting idea to consider

**Comment by danielskatz** [comment]
👋 @rafaelfsilva @Himscipy - I'm just checking in to see how things are going...

**Comment by rafaelfsilva** [comment]
@iaklampanos, I am following the installation steps (in a local VM) provided at https://project-dare.gitlab.io/dare-platform/configuration/, but I am having issues installing Keycloak:
```.bash
dare@dare-VitualBox:~$ helm install keycloak -f keycloak-values.yaml --version 8.0.0 codecentric/keycloak 

Error: open keycloak-values.yaml: no such file or directory
```
**Any insights?**

Also, a small typo to fix in the installation instructions for the Rook Shared file system is to have the `git checkout release-0.8` after the `cd rook/cluster/examples/kubernetes/ceph` command.

**Comment by rafaelfsilva** [comment]
@iaklampanos, in the software paper, could you please add one additional section that provides a short overview of the state of the field?
- **State of the field:** Do the authors describe how this software compares to other commonly-used packages?

I noticed you have a very good description of the state of the field in the papers below, so it would only be a matter of summarizing them in the software paper. Thank you!
- https://doi.org/10.1109/eScience.2019.00079
- https://zenodo.org/record/3697898

**Comment by Himscipy** [comment]
👋  @danielskatz , I am on it...!! busy times at workplace.
@iaklampanos . The paper provides good source to know about the DARE platform and I agree with the @rafaelfsilva comment above that the addition of " State of the field" will further emphasis the gap which the DARE platform has filled.

**Comment by iaklampanos** [comment]
Thank you @rafaelfsilva and @Himscipy for your suggestions. We have addressed you comments re the deployment instructions and we have now provided a state of the field section which covers some related work.

**Comment by danielskatz** [comment]
@iaklampanos - if you make changes in the paper source, you then need to regenerate the pdf, as I will do in the next comment

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02664/joss.02664/10.21105.joss.02664.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02664/joss.02664/10.21105.joss.02664.pdf) :page_facing_up: :point_left:

**Comment by rafaelfsilva** [comment]
@iaklampanos Thank you for the updated installation instructions. I managed to install the platform on Ubuntu and test the main functionalities. The only thing that is missing is a reference to where I can find the `jupyterhub-config.yaml` file. Although this is not critical for testing the functionalities of the system, it would be good to completely test the [Toy Example](https://project-dare.gitlab.io/dare-platform/demo/), specifically the `mySplitMerge workflow.ipynb` notebook.

**Comment by iaklampanos** [comment]
Thank you @rafaelfsilva. Perhaps @sissythem can help with this.

**Comment by rafaelfsilva** [comment]
thank you @iaklampanos and @sissythem, I managed to test it.

@danielskatz I have completed my review.

**Comment by Himscipy** [comment]
@iaklampanos Thanks for the comprehensive documentation about the DARE platform I managed to test it functionality 
at least the use cases seamlessly.  I couldn't find any automated testing/ manual test which is need to verify the overall functionality.

**Review Requirements**
*Automated tests:* Are there automated tests or manual steps described so that the functionality of the software can be verified?

**Comment by iaklampanos** [comment]
Thanks @Himscipy. The platform comprises multiple largely independent components, which are listed in the paper. Each of these components will have some tests used by the respective development team. For instance dispel4py has its tests at https://gitlab.com/project-dare/dispel4py/-/tree/master/dispel4py/test, s-provflow has its tests at  https://gitlab.com/project-dare/s-ProvFlow/-/tree/master/provenance-api/src/test. 

Due to the fact that automated tests for the overall platform would depend on deployment and that we don't have a standard location that we deploy DARE, we run the above manually and not automatically. As referenced in the paper, for the overall platform we use the "mysplitmerge" demo (https://gitlab.com/project-dare/exec-api/-/tree/master/examples/mySplitMerge) as an integration test after all updates and deployment.

**Comment by Himscipy** [comment]
Hi @iaklampanos ,

Thank you for the details regarding the tests. I agree that due to individual and multiple independent components, setting the testing procedure might be a challenging  procedure. 
But a single script to test the coherence all the components  would further consolidate the overall framework robustness. As I user, I would first like to ensure that everything is correctly setup on the system and then customizing the code for the individual objective.

If not automated test, but a script to call a test for each component one at a time could do the job, and provide a functionality test.

**Comment by danielskatz** [comment]
@iaklampanos  - note that we are getting close to done with this review - there are just 2 more boxes for @Himscipy to check off.  If you can help with the testing one as in the comment above, we'll be a bit closer.

**Comment by sissythem** [comment]
@danielskatz @Himscipy We have added some tests in the individual APIs which also test their functionality. 
We have also added a ReadMe with instructions [here](https://gitlab.com/project-dare/dare-platform/-/tree/master/test_dare_components)

**Comment by danielskatz** [comment]
Great, thanks!

**Comment by iaklampanos** [comment]
Thank you @danielskatz and also @rafaelfsilva and @Himscipy for your very helpful comments. 

The gitlab tag is v3.5. 

We archived the software on zenodo - https://zenodo.org/record/4095463#.X4m04C8RoWo. 

The DOI assigned is 10.5281/zenodo.4095463

**Comment by danielskatz** [comment]
@whedon set v3.5 as version

**Comment by whedon** [comment]
OK. v3.5 is the version.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.4095463 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4095463" target="_blank">10.5281/zenodo.4095463</a> is the archive.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1177/1094342016649766 is OK
- 10.1109/eScience.2019.00079 is OK
- 10.6084/m9.figshare.3115156.v2 is OK
- 10.1109/eScience.2019.00042 is OK
- 10.5281/zenodo.3697898 is OK
- 10.1109/ACCESS.2020.2964386 is OK
- 10.21105/joss.01517 is OK
- 10.1016/j.future.2019.05.076 is OK
- 10.1016/j.future.2019.04.008 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1818

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1818, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
This looks almost ready - but I found a couple of small issues in the bib, addressed in https://gitlab.com/project-dare/dare-platform/-/merge_requests/7 - let me know when this is merged

**Comment by sissythem** [comment]
@danielskatz we have merged this update

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1177/1094342016649766 is OK
- 10.1109/eScience.2019.00079 is OK
- 10.6084/m9.figshare.3115156.v2 is OK
- 10.1109/eScience.2019.00042 is OK
- 10.5281/zenodo.3697898 is OK
- 10.1109/ACCESS.2020.2964386 is OK
- 10.21105/joss.01517 is OK
- 10.1016/j.future.2019.05.076 is OK
- 10.1016/j.future.2019.04.008 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1820

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1820, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1317487440903475201) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1821
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02664](https://doi.org/10.21105/joss.02664)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @iaklampanos (Iraklis Klampanos) and co-authors!!

And thanks to @rafaelfsilva & @Himscipy for reviewing!

**Comment by iaklampanos** [comment]
Thank you @danielskatz, your guidance both pre- and during the review has been extremely helpful and on-point! Also many thanks to both reviewers!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02664/status.svg)](https://doi.org/10.21105/joss.02664)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02664">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02664/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02664/status.svg
   :target: https://doi.org/10.21105/joss.02664
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02664/status.svg)](https://doi.org/10.21105/joss.02664)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
