### ISSUE TITLE
[PRE REVIEW]: Reorient: A Web tool for reorienting and cropping MRI data.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2665]
**Submitting author:** @katjaq (<a href="http://orcid.org/0000-0002-7237-0196">Katja Heuer</a>)
**Repository:** <a href="https://github.com/neuroanatomy/paper-reorient" target ="_blank">https://github.com/neuroanatomy/paper-reorient</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @katjaq. **Currently, there isn't an JOSS editor assigned** to your paper.

@katjaq if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.cortex.2019.04.011 is OK
- 10.1016/j.neuron.2018.08.039 is OK
- 10.5281/ZENODO.3402456 is OK
- 10.5281/ZENODO.3937147 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02665/joss.02665/10.21105.joss.02665.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02665/joss.02665/10.21105.joss.02665.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.01 s (325.9 files/s, 11190.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              1              3              0             46
Markdown                         2             11              0             43
-------------------------------------------------------------------------------
SUM:                             3             14              0             89
-------------------------------------------------------------------------------


Statistical information for the repository '2665' was gathered on 2020/09/11.
No commited files with the specified extensions were found.
```

**Comment by danielskatz** [comment]
@katjaq - I'm going to mark this as withdrawn.  Can you resubmit with the paper in the software repository?  Or in a branch, if you don't want it in master for some reason?

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.

**Comment by katjaq** [comment]
Hi @danielskatz !
Thank you very much. Sorry for my confusion on how this is supposed to work. 

I just submitted again – now from the good repo :D 
Very best
katja
