### ISSUE TITLE
[PRE REVIEW]: Multiscale Solar Water Heating

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2666]
**Submitting author:** @milicag (<a href="http://orcid.org/0000-0003-1640-3931">Milica Grahovac</a>)
**Repository:** <a href="https://github.com/LBNL-ETA/MSWH" target ="_blank">https://github.com/LBNL-ETA/MSWH</a>
**Version:** v1.0.0
**Editor:** @sjpfenninger
**Reviewers:** @brynpickering, @nmstreethran
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @milicag. **Currently, there isn't an JOSS editor assigned** to your paper.

@milicag if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2666 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2666 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2666 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@milicag - where in this repo is the JOSS paper?  We also require an OSI-approved license, normally a file called LICENSE

**Comment by milicag** [comment]
@danielskatz The paper is on a branch: https://github.com/LBNL-ETA/MSWH/tree/issue5_submit_to_joss. Let me know if you'd need it merged into the master and I can do that.

The license is in the l[egal.md](https://github.com/LBNL-ETA/MSWH/blob/issue5_submit_to_joss/legal.md) file.

**Comment by milicag** [comment]
@danielskatz The paper compiled fine in the test you provide.

**Comment by milicag** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02666/joss.02666/10.21105.joss.02666.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02666/joss.02666/10.21105.joss.02666.pdf) :page_facing_up: :point_left:

**Comment by milicag** [comment]
@danielskatz compiled, see above.

**Comment by danielskatz** [comment]
Which OSI-approved license is this?

**Comment by milicag** [comment]
BSD-3-Clause

**Comment by danielskatz** [comment]
This is modified from https://opensource.org/licenses/BSD-3-Clause which we don't allow.

Can you break this off into a LICENSE file that is just the BSD license, without any changes other than in the first line?

**Comment by milicag** [comment]
dalonsoa, brynpickering, kramea, nmstreethran, dsryberg are potential editors based on the topics.

**Comment by milicag** [comment]
So you need me to place the https://github.com/LBNL-ETA/MSWH/blob/issue5_submit_to_joss/legal.md#license-agreement into a separate file?

**Comment by milicag** [comment]
Can you tell me why the license must be in a separate file?

**Comment by milicag** [comment]
[Here is the license file as a separate file.](https://github.com/LBNL-ETA/MSWH/blob/master/LICENSE.md)

**Comment by danielskatz** [comment]
the problem is you are adding to the standard license, which we don't allow.  It also makes it harder to compare what you have with the standard license.

The open source community in general is good at dealing with standard files in standard locations, and this isn't standard.

**Comment by danielskatz** [comment]
> Here is the license file as a separate file.

Thanks - but you have modified the 3rd clause from the standard

**Comment by milicag** [comment]
Sure, no problem, I just like to understand. The modifications are how the license was granted by LBNL. What is not standard in the license? Thank you so much for any clarifications.

**Comment by milicag** [comment]
I just did a detailed read and the license has the same 3 clauses and provides the same ability to the users.

**Comment by danielskatz** [comment]
I'm sorry, now I realize that this is not a BSD 3-clause license but it is almost a Lawrence Berkeley National Labs BSD Variant License (BSD-3-Clause-LBNL) license: https://opensource.org/BSD-3-Clause-LBNL.

The only change that is needed is to remove the extra text at the start of the first line, so that this line starts with "Copyright".

**Comment by danielskatz** [comment]
BSD-3-Clause-LBNL is an OSI-approved license, so once you make this small change, it will be fine.

**Comment by milicag** [comment]
Great, I've pushed the fix as required.

**Comment by milicag** [comment]
Just as fyi, if you were to write a parser for the license, LBNL first writes the name of the software, so as was written in my initial version:
```
Multiscale Solar Water Heating (SWH) Copyright (c) 2019, 
```
I see how the https://opensource.org/BSD-3-Clause-LBNL switches the order, so I've aligned the license in the separate file with this one, so:
```
Copyright (c) 2019 Multiscale Solar Water Heating (MSWH)
```

**Comment by danielskatz** [comment]
I'm sorry to be picky about this, but can you change the first line from
> Copyright (c) 2019 Multiscale Solar Water Heating (MSWH), The Regents of the University of California, through Lawrence Berkeley National Laboratory (subject to receipt of any required approvals from the U.S. Dept. of Energy). All rights reserved.

to
> Copyright (c) 2019, The Regents of the University of California, through Lawrence Berkeley National Laboratory (subject to receipt of any required approvals from the U.S. Dept. of Energy). All rights reserved.

**Comment by milicag** [comment]
Sure! Just let me know what edits are needed.

**Comment by danielskatz** [comment]
Exactly what I wrote in the previous comment :)

**Comment by milicag** [comment]
It is changed as you instructed.

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.88 s (47.4 files/s, 285358.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       9           4455          20795          17937
Python                          47           2661           3658           6567
Jupyter Notebook                 6              0         474208           3261
HTML                            10            166            268           1247
Markdown                         5            105              0            247
TeX                              1             14              0            133
reStructuredText                 7             57             41            101
DOS Batch                        1              8              1             27
CSS                              2              5             13             26
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                            89           7475         498990          29556
-------------------------------------------------------------------------------


Statistical information for the repository '2666' was gathered on 2020/09/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Milica Grahovac                  1             3              1            0.01
milicag                         19         33221          25358           99.99

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Milica Grahovac               3          100.0          9.4               66.67
milicag                   56070          168.8          0.0               40.20
```

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/19401493.2013.765506 is OK
- 10.1016/j.apenergy.2017.07.093 is OK

MISSING DOIs

- 10.2172/1140094 may be a valid DOI for title: Laboratory Performance Evaluation of Residential Integrated Heat Pump Water Heaters

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@milicag - can you add the missing DOI?

**Comment by milicag** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "," (COMMA) [#<BibTeX::Bibliography data=[11]>, "@", #<BibTeX::Entry >, {:title=>["Laboratory Performance Evaluation of Residential Integrated Heat Pump Water Heaters"], :author=>["Sparn, B. and Hudon, K. and Christensen, D."], :abstractnote=>["This report discusses how a significant opportunity for energy savings is domestic hot water heating, where an emerging technology has recently arrived in the U.S. market: the residential integrated heat pump water heater. A laboratory evaluation is presented of the five integrated HPWHs available in the U.S. today."], :doi=>["10.2172/1025650"], :journal=>[""]}, ",", "number", "="]

**Comment by milicag** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/19401493.2013.765506 is OK
- 10.1016/j.apenergy.2017.07.093 is OK
- 10.2172/1025650 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @sjpfenninger - you were suggested to edit this by the submitters. Are you willing to do so?

**Comment by danielskatz** [comment]
@whedon invite @sjpfenninger as editor

**Comment by whedon** [comment]
@sjpfenninger has been invited to edit this submission.

**Comment by milicag** [comment]
Thanks @danielskatz for guidance.

**Comment by sjpfenninger** [comment]
@whedon assign @sjpfenninger as editor

**Comment by whedon** [comment]
OK, the editor is @sjpfenninger

**Comment by sjpfenninger** [comment]
@brynpickering, @dalonsoa would you be able to review this submission for JOSS?

**Comment by dalonsoa** [comment]
Hi all,  I'm sorry but I cannot do it this time. The topic is great, though! I'll keep an eye on the repo.

**Comment by sjpfenninger** [comment]
@whedon add @brynpickering as reviewer

**Comment by whedon** [comment]
OK, @brynpickering is now a reviewer

**Comment by sjpfenninger** [comment]
@dalonsoa, thanks and no worries!

**Comment by sjpfenninger** [comment]
@nmstreethran @sevberg Would either of you be able to review this submission to JOSS?

**Comment by nmstreethran** [comment]
@sjpfenninger Yes, I'm happy to review this submission!

**Comment by sjpfenninger** [comment]
@whedon add @nmstreethran as reviewer

**Comment by whedon** [comment]
OK, @nmstreethran is now a reviewer

**Comment by sjpfenninger** [comment]
Thanks @nmstreethran !

**Comment by sjpfenninger** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2695.

**Comment by sjpfenninger** [comment]
@brynpickering, @nmstreethran thanks for agreeing to review. Let's head over to #2695 for the actual review!
