### ISSUE TITLE
[PRE REVIEW]: Reorient: A Web tool for reorienting and cropping MRI data.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2667]
**Submitting author:** @katjaq (<a href="http://orcid.org/0000-0002-7237-0196">Katja Heuer</a>)
**Repository:** <a href="https://github.com/neuroanatomy/reorient" target ="_blank">https://github.com/neuroanatomy/reorient</a>
**Version:** v1.0.0
**Editor:** @oliviaguest
**Reviewers:** @sneakers-the-rat, @pauldmccarthy
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @katjaq. **Currently, there isn't an JOSS editor assigned** to your paper.

@katjaq if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.30 s (82.2 files/s, 63536.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      12           2372           4155          11325
SVG                              5              4              4            513
JSON                             2              0              0            488
HTML                             3             31             12            345
CSS                              1              1              0             46
YAML                             1              0              0             17
Markdown                         1             12              0              8
-------------------------------------------------------------------------------
SUM:                            25           2420           4171          12742
-------------------------------------------------------------------------------


Statistical information for the repository '2667' was gathered on 2020/09/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Roberto Toro                     4         17746             42           95.16
katja heuer                      4             8              7            0.08
katjaq                           3           215            204            2.24
r03ert0                          3           237            233            2.51

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Roberto Toro              17344           97.7          0.6               27.69
katja heuer                 143         1787.5          4.3                4.20
r03ert0                     233           98.3          0.4               45.49
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2667 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02667/joss.02667/10.21105.joss.02667.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02667/joss.02667/10.21105.joss.02667.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper-branch
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.cortex.2019.04.011 is OK
- 10.1016/j.neuron.2018.08.039 is OK
- 10.5281/ZENODO.3402456 is OK
- 10.5281/ZENODO.3937147 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @cMadan - Is there any chance you can take on one more submission to edit?

**Comment by danielskatz** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by cMadan** [comment]
@danielskatz, unfortunately, I'm at capacity right now.

**Comment by danielskatz** [comment]
👋 @oliviaguest - any chance you could take even one more submission to edit?

**Comment by danielskatz** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by oliviaguest** [comment]
@danielskatz There is a non-zero chance I can take this on. By which I mean, yes.

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
@katjaq when you get a moment can you drop some names for potential reviewers, please? 😊

**Comment by oliviaguest** [comment]
@whedon add @sneakers-the-rat as reviewer

**Comment by whedon** [comment]
OK, @sneakers-the-rat is now a reviewer

**Comment by katjaq** [comment]
Hello @oliviaguest ! Thank you so much for being editor for our paper.
As reviewers, we would like to suggest Anibal Solon (anibalsolon), Katie Bottenhorn (62442katieb), Felix Henninger (felixhenninger). Finally, Paul McCarthy (pauldmccarthy): he's the developer of FSLeyes, however, he's not in the reviewer pool for JOSS yet...

**Comment by oliviaguest** [comment]
@katjaq thanks. I tried to find contact info (like email) for Paul McCarthy (@pauldmccarthy) but can't so I'll tag the username you gave me.

**Comment by katjaq** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2667 with the following error: 

 Can't find any papers to compile :-(

**Comment by katjaq** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02667/joss.02667/10.21105.joss.02667.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02667/joss.02667/10.21105.joss.02667.pdf) :page_facing_up: :point_left:

**Comment by katjaq** [comment]
I have a question regarding the indication of corresponding authors: Is there a way to simply have an asterisk twice, for Roberto and me to indicate corresponding authors instead of star and cross?

I would like to just have 
Katja Heuer* and Roberto Toro*.

What it does though is 
Katja Heuer* and Roberto Toro†

The syntax I use is
Katja Heuer^[Corresponding author] and same later for Roberto Toro^[Corresponding author]. I am sorry I cannot figure it out :(

Thank you in case you can help. :)

(Or maybe in case of 2 authors both corresponding author you don't indicate a corresponding author at all? ) 👀  Happy to follow your advice 🙃

**Comment by r03ert0** [comment]
hello! Thank you @oliviaguest for your help!

**Comment by pauldmccarthy** [comment]
More than happy to review, will reply to your email @oliviaguest :)

**Comment by oliviaguest** [comment]
I'm hoping @danielskatz can give his opinion on the above (https://github.com/openjournals/joss-reviews/issues/2667#issuecomment-691519629), as I have no idea — sorry!

**Comment by oliviaguest** [comment]
@whedon add @pauldmccarthy as reviewer

**Comment by whedon** [comment]
OK, @pauldmccarthy is now a reviewer

**Comment by danielskatz** [comment]
I know we've had this issue before and @arfon provided an answer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2670.

**Comment by arfon** [comment]
> (Or maybe in case of 2 authors both corresponding author you don't indicate a corresponding author at all? ) 👀 Happy to follow your advice 🙃

I'm afraid our LaTeX template doesn't support denoting more than one author as a corresponding author so I'd suggest not using the footnotes like this for this case.

**Comment by katjaq** [comment]
> > (Or maybe in case of 2 authors both corresponding author you don't indicate a corresponding author at all? ) 👀 Happy to follow your advice 🙃
> 
> I'm afraid our LaTeX template doesn't support denoting more than one author as a corresponding author so I'd suggest not using the footnotes like this for this case.

Thank you for the quick reply, Arfon. 

@oliviaguest : I deleted the corresponding author part from the paper.md file (nothing in the paper changed)--> Do I ask the whedon bot here in this thread to recompile the paper, or over in the review thread? Or do you ask for recompilation as it is already under review? Thank you :)

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper-branch

@katjaq - anyone can ask Whedon to compile a paper whenever needed like this ☝️

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02667/joss.02667/10.21105.joss.02667.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02667/joss.02667/10.21105.joss.02667.pdf) :page_facing_up: :point_left:

**Comment by katjaq** [comment]
I just adapted one reference

@whedon generate pdf from branch joss-paper-branch

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02667/joss.02667/10.21105.joss.02667.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02667/joss.02667/10.21105.joss.02667.pdf) :page_facing_up: :point_left:
