### ISSUE TITLE
[REVIEW]: Psifr: Analysis and visualization of free recall data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2669]
**Submitting author:** @mortonne (<a href="http://orcid.org/0000-0002-2631-2710">Neal Morton</a>)
**Repository:** <a href="https://github.com/mortonne/psifr" target ="_blank">https://github.com/mortonne/psifr</a>
**Version:** v0.4.4
**Editor:** @cMadan
**Reviewer:** @samhforbes, @paxtonfitzpatrick
**Archive:** <a href="https://doi.org/10.5281/zenodo.4086188" target="_blank">10.5281/zenodo.4086188</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/712d4452e465229d61d0e281d3d6f299/status.svg)](https://joss.theoj.org/papers/712d4452e465229d61d0e281d3d6f299)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/712d4452e465229d61d0e281d3d6f299"><img src="https://joss.theoj.org/papers/712d4452e465229d61d0e281d3d6f299/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/712d4452e465229d61d0e281d3d6f299/status.svg)](https://joss.theoj.org/papers/712d4452e465229d61d0e281d3d6f299)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mortonne/psifr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@samhforbes & @paxtonfitzpatrick, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @cMadan know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mortonne/psifr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mortonne) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mortonne/psifr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mortonne) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @samhforbes, @paxtonfitzpatrick it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1006/jmla.2001.2798 is OK
- 10.1037/a0014420 is OK
- 10.1037/a0022475 is OK
- 10.1016/j.jml.2015.10.002 is OK
- 10.1101/lm.041178.115 is OK
- 10.1016/j.neuroimage.2016.12.049 is OK
- 10.21105/joss.00424 is OK
- 10.5281/zenodo.3993412 is OK
- 10.5281/zenodo.3767070 is OK

MISSING DOIs

- 10.1037/h0045106 may be a valid DOI for title: The serial position effect of free recall
- 10.3758/bf03197276 may be a valid DOI for title: Associative retrieval processes in free recall

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02669/joss.02669/10.21105.joss.02669.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02669/joss.02669/10.21105.joss.02669.pdf) :page_facing_up: :point_left:

**Comment by samhforbes** [comment]
Hi @mortonne - thanks for the opportunity to look at this package. Installation worked smoothly, and while I have no free recall data of my own to test it on, the sample data provided works well (thanks for that). I thought the paper was very clear on the differences between this package and other existing packages, so that was also great. A minor thought (purely optional) is that you could consider puting one of your custom plots in the paper, since it is one of the strengths of this package.
I'm enjoying it so far!

I have opened a couple of issues for you to look at:
https://github.com/mortonne/psifr/issues/1
https://github.com/mortonne/psifr/issues/2

**Comment by cMadan** [comment]
@samhforbes, thanks for your great work on the review so far! :)

**Comment by paxtonfitzpatrick** [comment]
Hey @mortonne, thanks for putting together a great toolkit!  I've finished looking everything over, and apart from a few fixes and tweaks in the issues I linked above, everything ran smoothly, looked pretty, and was well documented 🙂 
I agree with @samhforbes that a plot or two (particularly one of the raster plots, in my opinion) would make a great addition to the paper if you wanted!  But of course that's entirely up to you, and I think `psifr` is worthy of publication in JOSS with or without it.

I mentioned this in the issue itself, but I just wanted to note here as well that I don't think addressing the two items in mortonne/psifr#8 is necessary for an initial release, and both are likely outside the scope of a JOSS review (though I’ll defer to @cMadan on that since this is my first time not on the receiving end).  I simply enjoyed playing around with `psifr` and could certainly see myself using it, so I thought I'd post a couple quick suggestions I felt would be improvements.

Thanks again, and I'm signed off pending issues 1-7!

**Comment by cMadan** [comment]
@paxtonfitzpatrick, thank you for the thorough review! I've commented in https://github.com/mortonne/psifr/issues/8, but to briefly re-cap here--I agree this is a useful improvement but is not necessary for JOSS acceptance.

**Comment by mortonne** [comment]
@samhforbes @paxtonfitzpatrick, thanks very much for your thoughtful reviews, which had some great ideas for improvements. I believe I've addressed all of the issues you raised. Let me know if there is anything else I need to work on. Thanks again!

**Comment by samhforbes** [comment]
Hi @mortonne - great work with these issues - I'm really happy with how you have updated the docs, I think it will be good for the reader. The tests for plotting functions mentioned by @paxtonfitzpatrick are great, and the high test coverage is now really impressive. From my end I'm certainly satisfied. Well done, it's a great package, and I will be recommending it.

**Comment by paxtonfitzpatrick** [comment]
@mortonne thanks very much for addressing these issues—all your fixes look great to me!  I'm more than happy with the changes you've made, and am looking forward both to using `psifr` myself and seeing how the package grows in the future.

**Comment by cMadan** [comment]
@samhforbes @paxtonfitzpatrick, thank you both for your thorough and constructive comments!

@mortonne, I will now do some final checks within the next few days and then advise on the last steps. You're almost done!

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02669/joss.02669/10.21105.joss.02669.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02669/joss.02669/10.21105.joss.02669.pdf) :page_facing_up: :point_left:

**Comment by cMadan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1037/h0045106 is OK
- 10.3758/bf03197276 is OK
- 10.1006/jmla.2001.2798 is OK
- 10.1037/a0014420 is OK
- 10.1037/a0022475 is OK
- 10.1016/j.jml.2015.10.002 is OK
- 10.1101/lm.041178.115 is OK
- 10.1016/j.neuroimage.2016.12.049 is OK
- 10.21105/joss.00424 is OK
- 10.5281/zenodo.3993412 is OK
- 10.5281/zenodo.3767070 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by cMadan** [comment]
@mortonne, everything looks good to me!

To move forward with accepting your submission, there are a few last things to take care of:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

You may find this helpful: https://guides.github.com/activities/citable-code/

**Comment by mortonne** [comment]
* I've created a new tagged release: [v0.4.4](https://github.com/mortonne/psifr/releases/tag/v0.4.4).
* That tagged release has been archived in [Zenodo](https://zenodo.org/record/4086188); the archive has the correct metadata.
* Zenodo DOI: 10.5281/zenodo.4086188

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4086188" target="_blank">10.5281/zenodo.4086188</a> is the archive.

**Comment by whedon** [comment]
OK. v0.4.4 is the version.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02669/joss.02669/10.21105.joss.02669.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02669/joss.02669/10.21105.joss.02669.pdf) :page_facing_up: :point_left:

**Comment by cMadan** [comment]
@mortonne, can you proof your paper.md one last time. In particular, you should revise this line:
``The source code for `Psifr` has  been archived to Zenodo with the linked DOI: TBD.``

**Comment by mortonne** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02669/joss.02669/10.21105.joss.02669.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02669/joss.02669/10.21105.joss.02669.pdf) :page_facing_up: :point_left:

**Comment by mortonne** [comment]
I've added the Zenodo DOI and proofed the paper. The archive and JOSS DOI links give 404 errors, but I'm guessing that's normal at this stage. Everything else looks good.

**Comment by cMadan** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1037/h0045106 is OK
- 10.3758/bf03197276 is OK
- 10.1006/jmla.2001.2798 is OK
- 10.1037/a0014420 is OK
- 10.1037/a0022475 is OK
- 10.1016/j.jml.2015.10.002 is OK
- 10.1101/lm.041178.115 is OK
- 10.1016/j.neuroimage.2016.12.049 is OK
- 10.21105/joss.00424 is OK
- 10.5281/zenodo.3993412 is OK
- 10.5281/zenodo.3767070 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1809

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1809, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1316718254992355330) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1811
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02669](https://doi.org/10.21105/joss.02669)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations @mortonne (Neal Morton)!!

And thanks to editor @cMadan and reviewers @samhforbes & @paxtonfitzpatrick!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02669/status.svg)](https://doi.org/10.21105/joss.02669)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02669">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02669/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02669/status.svg
   :target: https://doi.org/10.21105/joss.02669
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02669/status.svg)](https://doi.org/10.21105/joss.02669)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
