### ISSUE TITLE
[REVIEW]: CIMSA: Customizable Integrated Multiple Sequence Alignment Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2672]
**Submitting author:** @kuangmeng (<a href="http://orcid.org/0000-0001-9656-5652">Mengmeng Kuang</a>)
**Repository:** <a href="https://github.com/kuangmeng/CIMSA" target ="_blank">https://github.com/kuangmeng/CIMSA</a>
**Version:** v1.0
**Editor:** @will-rowe
**Reviewer:** @CFGrote, @xyzmjf
**Archive:** Pending

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/850437e3e33f9eadca0222769b7673c3/status.svg)](https://joss.theoj.org/papers/850437e3e33f9eadca0222769b7673c3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/850437e3e33f9eadca0222769b7673c3"><img src="https://joss.theoj.org/papers/850437e3e33f9eadca0222769b7673c3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/850437e3e33f9eadca0222769b7673c3/status.svg)](https://joss.theoj.org/papers/850437e3e33f9eadca0222769b7673c3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kuangmeng/CIMSA" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@CFGrote & @xyzmjf, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @will-rowe know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kuangmeng/CIMSA">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@kuangmeng) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kuangmeng/CIMSA">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@kuangmeng) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @CFGrote, @xyzmjf it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/gr.2821705 is OK
- 10.1016/j.sbi.2006.04.004 is OK
- 10.1371/journal.pcbi.0030123 is OK
- 10.1093/bioinformatics/btl472 is OK
- 10.1093/bioinformatics/btq338 is OK
- 10.1109/TCBB.2014.2316820 is OK
- 10.1109/bibm.2018.8621220 is OK
- 10.1093/comjnl/16.1.30 is OK
- 10.1093/comjnl/20.4.364 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02672/joss.02672/10.21105.joss.02672.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02672/joss.02672/10.21105.joss.02672.pdf) :page_facing_up: :point_left:

**Comment by CFGrote** [comment]
Hi @will-rowe, I'm done with my review.  All comments are in https://github.com/kuangmeng/CIMSA/issues, 1-19. Overall recommendation is "Reject, major revisions in order."

**Comment by will-rowe** [comment]
Thank you very much for your detailed review @CFGrote - much appreciated.

@xyzmjf - please let us know how you are getting on with your review and if you need anything.

Cheers,

Will

**Comment by will-rowe** [comment]
Hi @xyzmjf - please could you let us know how your review is going?

**Comment by xyzmjf** [comment]
Hi Will. I have downloaded the code. I will be going over it this afternoon and this weekend. Updating the check list was a no go, as the invite has expired or been revoked. Mark

**Comment by xyzmjf** [comment]
Hi Will. I have seen enough now to come to a conclusion. The code and manuscript should be rejected in the current form. A lot of work on both would be needed to meet the standard expected for a peer reviewed publication. all of my comments can be found in the open issues. My main overall comments are here. https://github.com/kuangmeng/CIMSA/issues/19

**Comment by will-rowe** [comment]
Dear @kuangmeng,

Unfortunately, after very thorough and fair reviews from @xyzmjf and @CFGrote, I don't think we can accept your paper for publication at JOSS at this point in time.

Although I can see the utility of the package, in its current form it does not meet our requirements for publication. As stated by the reviews, documentation is severely lacking and veracity of software cannot be established.

I think the ability to benchmark and parameterise MSA algorithms is a very appealing and important research goal; although it  is an often under-appreciated and under-performed task. I do think the constructive reviews can be used to bring this submission up to a standard acceptable to JOSS. In particular, I think the paper and README need to document a clear need and use case for this work. With this in mind, I think we can consider this a reject with major revisions needed. If you address these comments and concerns, pease feel free to tag me in a new submission and we can re-assess.

Thank you for your submission to JOSS and thank you again to the reviewers.

**Comment by will-rowe** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
