### ISSUE TITLE
[REVIEW]: pd-parser: A tool for Matching Photodiode Deflection Events to Time-Stamped Events

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2674]
**Submitting author:** @alexrockhill (<a href="http://orcid.org/0000-0003-3868-7453">Alexander Rockhill</a>)
**Repository:** <a href="https://github.com/alexrockhill/pd-parser" target ="_blank">https://github.com/alexrockhill/pd-parser</a>
**Version:** v0.3
**Editor:** @oliviaguest
**Reviewers:** @rougier, @rly, @libertyh
**Archive:** <a href="https://doi.org/10.5281/zenodo.4122049" target="_blank">10.5281/zenodo.4122049</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5ca2ad9880e4606376bb8d69321e7aea/status.svg)](https://joss.theoj.org/papers/5ca2ad9880e4606376bb8d69321e7aea)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5ca2ad9880e4606376bb8d69321e7aea"><img src="https://joss.theoj.org/papers/5ca2ad9880e4606376bb8d69321e7aea/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5ca2ad9880e4606376bb8d69321e7aea/status.svg)](https://joss.theoj.org/papers/5ca2ad9880e4606376bb8d69321e7aea)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/alexrockhill/pd-parser" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rougier & @rly, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @oliviaguest know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/alexrockhill/pd-parser">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@alexrockhill) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/alexrockhill/pd-parser">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@alexrockhill) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/alexrockhill/pd-parser">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@alexrockhill) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rougier, @rly it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/sdata.2016.44 is OK
- 10.3389/fnins.2013.00267 is OK
- 10.1038/sdata.2018.110 is OK
- 10.1038/s41597-019-0104-8 is OK
- 10.1038/s41597-019-0105-7 is OK
- 10.21105/joss.01896 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02674/joss.02674/10.21105.joss.02674.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02674/joss.02674/10.21105.joss.02674.pdf) :page_facing_up: :point_left:

**Comment by oliviaguest** [comment]
Hey 👋 @rougier, @rly: this is where the review will take place. Please make sure to read the instructions above.

For any and all things worthy of discussion or comment, use this issue right here — so drop comments or questions for me, the author, etc., here. For any very code-specific things please feel free to start an issue on the repo of the code itself (if appropriate!) and link back to it from here. For an example of how this process plays out feel free to skim previous reviews, such as: #2285 and #2348. ☺️

**Comment by oliviaguest** [comment]
@whedon add @libertyh as reviewer

**Comment by whedon** [comment]
OK, @libertyh is now a reviewer

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02674/joss.02674/10.21105.joss.02674.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02674/joss.02674/10.21105.joss.02674.pdf) :page_facing_up: :point_left:

**Comment by oliviaguest** [comment]
Hey @rougier, @rly, @libertyh — when you get a chance can you give me an ETA for your reviews, please?

**Comment by rly** [comment]
@oliviaguest I'll have this done by October 8.

**Comment by rougier** [comment]
Same here, thanks for the reminder !

**Comment by libertyh** [comment]
I should be done by Oct 8 as well, thanks!

**Comment by oliviaguest** [comment]
@whedon remind @rly in 9 days

**Comment by whedon** [comment]
Reminder set for @rly in 9 days

**Comment by oliviaguest** [comment]
@whedon remind @libertyh in 9 days

**Comment by whedon** [comment]
Reminder set for @libertyh in 9 days

**Comment by oliviaguest** [comment]
@whedon remind @rougier in 9 days

**Comment by whedon** [comment]
Reminder set for @rougier in 9 days

**Comment by rougier** [comment]
@oliviaguest I'm jealous of whedon (I'm the reminder bot for ReScience...)

**Comment by oliviaguest** [comment]
@rougier it's so cute — see: https://joss.readthedocs.io/en/latest/whedon.html

**Comment by rougier** [comment]
@guest I can do all these command on ReScience (just replace whedon by rougier)...

@alexrockhill I'started testing your software and opened an issue on your repo. You already addressed one of my issue, could you have a look at the new one?

**Comment by oliviaguest** [comment]
@rougier can you link to any relevant issues here please, so we can all have them organised and accessible? 😊

**Comment by rougier** [comment]
Sure, here is is: https://github.com/alexrockhill/pd-parser/issues/1. And I realized my second post was not not posted.

**Comment by rly** [comment]
Hi @alexrockhill, I have reviewed your software and paper and created a few issues in your repo:
https://github.com/alexrockhill/pd-parser/issues/2
https://github.com/alexrockhill/pd-parser/issues/2
https://github.com/alexrockhill/pd-parser/issues/2

**Comment by rly** [comment]
Hi @alexrockhill, I have reviewed your software and paper. Overall, the software and paper look good. There were a few issues to address, as per the JOSS paper guidelines/rubric. I created a few issues in your repo:
https://github.com/alexrockhill/pd-parser/issues/2
https://github.com/alexrockhill/pd-parser/issues/3
https://github.com/alexrockhill/pd-parser/issues/4

Suggestions:
https://github.com/alexrockhill/pd-parser/issues/5

**Comment by rly** [comment]
@alexrockhill has addressed all of my concerns and, in my view, has met all of the review criteria. I would be happy to discuss this paper with the other reviewers when they are ready.

**Comment by rougier** [comment]
the two provided examples are now working properly on my machine. I think it would be nice to have these exampls tests alongside the pd_parser such that you can type `pd_parser.test()` to check everything's ok. And/or you could also have very simple unittests that would help you spotting discrepancies in the API. Apart from these minor points, I'm satisfied with the submission.

**Comment by alexrockhill** [comment]
> the two provided examples are now working properly on my machine. I think it would be nice to have these exampls tests alongside the pd_parser such that you can type `pd_parser.test()` to check everything's ok. And/or you could also have very simple unittests that would help you spotting discrepancies in the API. Apart from these minor points, I'm satisfied with the submission.

Good idea, I added unit tests for the examples to make sure they run with this commit 9086579ba5ca615bc9a2d9e03ede3c406c780073. They don't check whether they look right, the only way to do that is by eye, but you can run `pytest` and it will test everything including the examples now as described in the contributing guidelines.

**Comment by libertyh** [comment]
I've also started my review and left some comments about the README and the paper text so far. @oliviaguest I think I may need to be re-invited to the repo (sorry!!) in order to complete the checklist. Will link to my issues in a bit when complete!

**Comment by oliviaguest** [comment]
@whedon re-invite @libertyh as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@libertyh please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by oliviaguest** [comment]
No worries, @libertyh. With respect to your feedback please link to all issues you have opened here in this thread, so we can all easily take a look — ta!

**Comment by whedon** [comment]
:wave: @rougier, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @libertyh, please update us on how your review is going.

**Comment by rougier** [comment]
Good bot ! I forgot to check one box and I just remember I had a question about co-authors. They do not seem to have commited anything in the repo. @alexrockhill Could you explain their role ?

**Comment by alexrockhill** [comment]
> Good bot ! I forgot to check one box and I just remember I had a question about co-authors. They do not seem to have commited anything in the repo. @alexrockhill Could you explain their role ?

Dr. Raslan and Dr. Swann have active supervision, review and high-level direction of both the software package and the physical setup for data collection that is used in the example data and discussed in the paper.

**Comment by libertyh** [comment]
Hi everyone! Thanks @alexrockhill for starting to address my comments. I'm including the issues I opened here:

alexrockhill/pd-parser#6
alexrockhill/pd-parser#7
alexrockhill/pd-parser#8

Most of these have to do with clarifications to the usage of pd-parser so that it's as easy as possible for your end users to get started. I was able to get the code to work on my machine with the jupyter notebook examples. Happy to discuss when everyone is ready.

**Comment by alexrockhill** [comment]
Just pinging this thread to keep things moving forward.

**Comment by rly** [comment]
Everything looks good on my end. The new example mentioned in https://github.com/alexrockhill/pd-parser/issues/7 looks good too. @alexrockhill I would encourage you to git tag the new version and make a new release both on PyPI and on GitHub. 

Pending that, I think that the tool and paper are both suitable for publication on JOSS.

**Comment by libertyh** [comment]
Looks good to me too, I agree with @rly that following the new release this is acceptable for publication in JOSS.

**Comment by alexrockhill** [comment]
Ok, releasing 0.3 now

**Comment by alexrockhill** [comment]
@whedon set 0.3 as version

**Comment by whedon** [comment]
I'm sorry @alexrockhill, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by alexrockhill** [comment]
Oops, I guess @oliviaguest has to do that.

**Comment by alexrockhill** [comment]
Here's the DOI for the 0.3 release as well http://doi.org/10.5281/zenodo.4122049

**Comment by oliviaguest** [comment]
@whedon set v0.3 as version

**Comment by whedon** [comment]
OK. v0.3 is the version.

**Comment by oliviaguest** [comment]
@alexrockhill can you change the title of the zenodo repo to match the title of your paper, please? ☺️

**Comment by oliviaguest** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/sdata.2016.44 is OK
- 10.3389/fnins.2013.00267 is OK
- 10.1038/sdata.2018.110 is OK
- 10.1038/s41597-019-0104-8 is OK
- 10.1038/s41597-019-0105-7 is OK
- 10.21105/joss.01896 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@whedon set 10.5281/zenodo.4122049 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4122049" target="_blank">10.5281/zenodo.4122049</a> is the archive.

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/sdata.2016.44 is OK
- 10.3389/fnins.2013.00267 is OK
- 10.1038/sdata.2018.110 is OK
- 10.1038/s41597-019-0104-8 is OK
- 10.1038/s41597-019-0105-7 is OK
- 10.21105/joss.01896 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1851

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1851, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by alexrockhill** [comment]
> @alexrockhill can you change the title of the zenodo repo to match the title of your paper, please? ☺️
 
Fixed!

Yay thank you all for the review, it was a very positive and helpful experience!

**Comment by kyleniemeyer** [comment]
@alexrockhill Hi there, I am the EIC on duty this week doing some final checks before publishing. There are just a few things I noticed:

- Can you break up the text of your article into paragraphs? Right now it sort of looks like a wall of text in each section.
- Can you add your co-authors to the Zenodo archive? That author list should match the paper as well.

**Comment by alexrockhill** [comment]
Thanks for the copy editing, @kyleniemeyer, those suggested changes have been implemented!

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/sdata.2016.44 is OK
- 10.3389/fnins.2013.00267 is OK
- 10.1038/sdata.2018.110 is OK
- 10.1038/s41597-019-0104-8 is OK
- 10.1038/s41597-019-0105-7 is OK
- 10.21105/joss.01896 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1854

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1854, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@alexrockhill looks good, thanks!

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1320429822632431617) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1855
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02674](https://doi.org/10.21105/joss.02674)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @alexrockhill on your article's publication in JOSS!

Many thanks to @rougier, @rly, and @libertyh for reviewing this, and @oliviaguest for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02674/status.svg)](https://doi.org/10.21105/joss.02674)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02674">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02674/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02674/status.svg
   :target: https://doi.org/10.21105/joss.02674
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02674/status.svg)](https://doi.org/10.21105/joss.02674)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by oliviaguest** [comment]
@rougier, @rly, @libertyh thank you for all your hard work and congratulations to  @alexrockhill! 😊

**Comment by alexrockhill** [comment]
Thank you Nicolas, Ryan and Liberty for a super helpful review and Olivia for editing!! And Kyle for copy editing! 😊
