### ISSUE TITLE
[REVIEW]: SCALAR - A Platform for Real-time Machine Learning Competitions on Data Streams

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2676]
**Submitting author:** @nedRad88 (<a href="http://orcid.org/0000-0001-5056-6270">Nedeljko Radulovic</a>)
**Repository:** <a href="https://github.com/nedRad88/SCALAR" target ="_blank">https://github.com/nedRad88/SCALAR</a>
**Version:** v0.1
**Editor:** @galessiorob
**Reviewers:** @GregaVrbancic, @atanikan, @xiaohk
**Archive:** <a href="https://doi.org/10.5281/zenodo.4299807" target="_blank">10.5281/zenodo.4299807</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e7049c900cf5ab0754157be4a5668f11/status.svg)](https://joss.theoj.org/papers/e7049c900cf5ab0754157be4a5668f11)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e7049c900cf5ab0754157be4a5668f11"><img src="https://joss.theoj.org/papers/e7049c900cf5ab0754157be4a5668f11/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e7049c900cf5ab0754157be4a5668f11/status.svg)](https://joss.theoj.org/papers/e7049c900cf5ab0754157be4a5668f11)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nedRad88/SCALAR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@GregaVrbancic & @atanikan, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @galessiorob know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nedRad88/SCALAR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nedRad88) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nedRad88/SCALAR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nedRad88) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nedRad88/SCALAR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nedRad88) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @GregaVrbancic, @atanikan it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2187671.2187677 is OK
- 10.1109/BigData47090.2019.9006357 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by galessiorob** [comment]
@whedon add @xiaohk as reviewer

**Comment by whedon** [comment]
OK, @xiaohk is now a reviewer

**Comment by galessiorob** [comment]
👋 @GregaVrbancic , @xiaohk and @atanikan

Thank you all for reviewing for this paper! At the top, you'll find individual checklists to work trough, please let me know if something is not clear or if you need any help.

**Comment by galessiorob** [comment]
Checking in! @GregaVrbancic , @xiaohk and @atanikan please let me know if you need anything on my behalf to get started on the review, thanks!

**Comment by GregaVrbancic** [comment]
Hi @galessiorob and @nedRad88,
I have made some progress on this review. I have opened several issues on SCALAR repository, so @nedRad88, please take a look at them. Also, please clarify Dihia Boulegane's and Albert Bifet's contributions to the paper since it is not observable from commit history (which can happen sometimes). Additionally, based on the commit history, should @gradoslovar be included as an co-author?

**Comment by nedRad88** [comment]
Hi @GregaVrbancic,
Thanks for the remarks.
Regarding authorship, the repository was not established back then when the project was started, so that is why Albert and Dihia don't appear in the commit history. If you check the second commit (https://github.com/nedRad88/SCALAR/tree/944fe1ae3eda7e3b2d481f81618dfd71d38cfa92) you can see that the project existed before creating the repository. 
Regarding @gradoslovar, he is an external contributor, but yes we can add him as a co-author. Should I update the paper?
Thanks, I will come back to you soon to resolve all other the opened issues.

**Comment by galessiorob** [comment]
Thanks for getting started @GregaVrbancic!

@nedRad88 please add @gradoslovar as co-author or mention him as a contributor, thanks!

**Comment by xiaohk** [comment]
Hello @nedRad88. Very helpful and interesting work!

I have added some comments on the issues raised by @GregaVrbancic on SCALAR repo.

My main concern is that the installation instruction is not very easy to follow. It would be much easier for other users to set up their SCALAR if the instruction provides a list of _all exact commands_ that they needs to run in order to set it up.

Other minor comments:

- Either on the README page or on the [documentation](), I suggest adding some text to discuss the problem and motivation for this software. I found the text on [Big Data Challenge](https://bigmine.github.io/real-time-ML-competition/index.html) very helpful.
- It would be great to have some automated tests and community guidelines
- A typo on the README page: SCALAR `let's` users → `lets`

**Comment by nedRad88** [comment]
Hello @galessiorob , @xiaohk ,
Thanks for the comments. 
I have added @gradoslovar as a contributor.
Regarding other issues, we are working on them, I am posting updates on each issue, separately. 
We will provide the updated procedure to test the software soon and we are simplifying the installation procedure.

**Comment by galessiorob** [comment]
Hey @nedRad88 mind commenting on this issue which of the missing items have you added or fixed so the reviewers and I can go back and check? Eg. Tests, statement of purpose, etc.

Thanks!

**Comment by nedRad88** [comment]
Hey @galessiorob , sorry for the delay. We have updated the community guidelines and installation instructions. Documentation and improved instructions for tests are under way. I will be posting updates in issue's thread. Thanks!

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment]
@nedRad88 I added a few edit suggestions to the text on the `patch-1` branch, feel free to further edit them if you want.

Looking forward to taking this paper across the finish line!

**Comment by nedRad88** [comment]
Hi @galessiorob , thanks for the suggestions. I have merged them into master. I am finishing the test setup. I expect to have it done in a day or two. Thank you!

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment]
@nedRad88 the paper looks almost ready to ship, I found a missing space that I added [here.](https://github.com/nedRad88/SCALAR/pull/9)

@GregaVrbancic, @atanikan, @xiaohk could you go over all the added changes and check the missing items from your lists if you're satisfied with them?

Thank you all, we are almost there!

**Comment by GregaVrbancic** [comment]
@galessiorob looks good to me

**Comment by xiaohk** [comment]
@galessiorob Finished my review. It looks good!

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment]
@atanikan could you check off the missing items from your checklist at your earliest convenience, please? I think we're ready to close this issue out and publish but I'd like to have all reviews complete. Thanks!

**Comment by galessiorob** [comment]
@nedRad88 I added a few more edits on this [PR](https://github.com/nedRad88/SCALAR/pull/10), once those are reviewed and merged, and @atanikan completes their checklist we'll be good to go!

**Comment by atanikan** [comment]
@galessiorob I am done now. Thanks, @nedRad88 for easing installation. Everything looks good to me. Great job with the application.

**Comment by nedRad88** [comment]
Thank you all @galessiorob @GregaVrbancic @xiaohk @atanikan For suggestions, comments and reviews.
I closed all issues and merged the last changes.

**Comment by galessiorob** [comment]
Thanks so much, @atanikan! 🎉 

@nedRad88 The next thing we need from you is to deposit your software in Zenodo and post the DOI here. After that, we can set the final version, generate a final proof, and have an Editor in Chief do the publishing. 🚀

**Comment by nedRad88** [comment]
Hi @galessiorob , here is the DOI: 10.5281/zenodo.4299807

**Comment by galessiorob** [comment]
@nedRad88 is `Version v0.1` the last version?

**Comment by galessiorob** [comment]
@whedon check references

**Comment by nedRad88** [comment]
@galessiorob Yes, that is the last version.

**Comment by galessiorob** [comment]
@whedon set v0.1 as version

**Comment by whedon** [comment]
OK. v0.1 is the version.

**Comment by galessiorob** [comment]
@whedon check references

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2187671.2187677 is OK
- 10.1109/BigData47090.2019.9006357 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by galessiorob** [comment]
@whedon set 10.5281/zenodo.4299807 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4299807" target="_blank">10.5281/zenodo.4299807</a> is the archive.

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment]
@nedRad88 could you proofread this final version, please? 🙏

**Comment by nedRad88** [comment]
@galessiorob I did. I made couple of minor changes.

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02676/joss.02676/10.21105.joss.02676.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment]
@nedRad88 mind solving the merge conflicts and merging the last PRs? After that, we can submit the final version. Thanks!

**Comment by nedRad88** [comment]
@galessiorob Done!

**Comment by galessiorob** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1965

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1965, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2187671.2187677 is OK
- 10.1109/BigData47090.2019.9006357 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by galessiorob** [comment]
@GregaVrbancic, @atanikan, @xiaohk thank you all so much for lending your time and expertise for this paper!

@nedRad88 a Chief Editor will do the final deposit and after that, your paper will be published on JOSS. Congrats! 🎉

**Comment by kyleniemeyer** [comment]
Hello @nedRad88, I'm the editor-in-chief on duty, doing some final checks.

In the Zenodo archive, you have one more person listed as an author than is on the paper. Can you clarify this? Normally we expect/require that the author lists match.

**Comment by nedRad88** [comment]
Hi @kyleniemeyer, I edited the zenodo upload. The authors should match now, and the one that was different is now labeled as a contributor. Is that ok now?

**Comment by nedRad88** [comment]
Thanks a lot @galessiorob @GregaVrbancic @xiaohk @atanikan for everything! It was a pleasure!

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1335309080165052418) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1967
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02676](https://doi.org/10.21105/joss.02676)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @nedRad88 on your article's publication in JOSS!

Many thanks to @GregaVrbancic, @atanikan, and @xiaohk for reviewing this, and @galessiorob for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02676/status.svg)](https://doi.org/10.21105/joss.02676)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02676">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02676/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02676/status.svg
   :target: https://doi.org/10.21105/joss.02676
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02676/status.svg)](https://doi.org/10.21105/joss.02676)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
