### ISSUE TITLE
[PRE REVIEW]: Thermosteam: BioSTEAM's Premier Thermodynamic Engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2679]
**Submitting author:** @yoelcortes (<a href="http://orcid.org/0000-0003-1742-5059">Yoel Cortes-Pena</a>)
**Repository:** <a href="https://github.com/BioSTEAMDevelopmentGroup/thermosteam" target ="_blank">https://github.com/BioSTEAMDevelopmentGroup/thermosteam</a>
**Version:** 0.20.26
**Editor:** @kyleniemeyer
**Reviewers:** @decaluwe, @fwitte
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @yoelcortes. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kyleniemeyer.

@yoelcortes if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2679 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by kyleniemeyer** [comment]
Hey @openjournals/dev, I can see the paper in the `docs/paper` directory in the repo (https://github.com/BioSTEAMDevelopmentGroup/thermosteam/tree/master/docs/paper), any idea why whedon can't find it?

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=3.48 s (29.6 files/s, 16394.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             7            640              0          30104
Python                          81           2786           7106          11550
Jupyter Notebook                 4              0           4035            383
TeX                              1              8              0             83
Markdown                         1              9              0             72
YAML                             3              7              1             60
reStructuredText                 2             29             20             40
DOS Batch                        1              8              1             26
RobotFramework                   1              0              0             10
make                             1              4              7              9
INI                              1              0              0              8
-------------------------------------------------------------------------------
SUM:                           103           3491          11170          42345
-------------------------------------------------------------------------------


Statistical information for the repository '2679' was gathered on 2020/09/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Yalin Li                         4          1224            167            1.99
Yoel                            90         11999          22919           50.00
unknown                         12         32861            670           48.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Yalin Li                    150           12.3          3.6                4.00
Yoel                      21292          177.4          3.2                8.54
```

**Comment by kyleniemeyer** [comment]
Hi @yoelcortes, thanks for your submission to JOSS! We'll use this issue to identify reviewers and resolve any technical issues (like our friendly bot not being able to find the paper).

I will be serving as editor for this; I have a few potential reviewers in mind, but any suggestions you have are also welcome.

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hey @bryanwweber @decaluwe would one of you be interested in reviewing this for JOSS?

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02679/joss.02679/10.21105.joss.02679.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02679/joss.02679/10.21105.joss.02679.pdf) :page_facing_up: :point_left:

**Comment by yoelcortes** [comment]
@kyleniemeyer, thanks for picking this up as the editor. I think both potential reviewers are excellent choices. They both have some chemistry and engineering in their background. Let me know if there is anything I can help with. Thanks!

**Comment by decaluwe** [comment]
Happy to!

Steven

**Comment by kyleniemeyer** [comment]
Thanks @xuanxu for fixing the paper issue, and thanks @decaluwe!

**Comment by kyleniemeyer** [comment]
@whedon add @decaluwe as reviewer

**Comment by whedon** [comment]
OK, @decaluwe is now a reviewer

**Comment by arfon** [comment]
:wave: @kyleniemeyer - it looks like this submission is still waiting on you to find a second reviewer before moving forward?

**Comment by kyleniemeyer** [comment]
Hi @arosen93, would you be interested in reviewing this submission? Thanks!

**Comment by arosen93** [comment]
@kyleniemeyer -- thanks for reaching out. Seems like a cool package and normally would be up my alley to review, but unfortunately I don't have the time to provide a thorough review right now.

**Comment by kyleniemeyer** [comment]
Hi @fwitte, would you be interested in reviewing this submission for JOSS? Thank you!

**Comment by yoelcortes** [comment]
@kyleniemeyer, thanks for managing the requests to review. Would reaching out to another reviewer soon be a good idea? Thanks!

**Comment by fwitte** [comment]
Hi @kyleniemeyer,
the notification only arrived just now. I'll quickly check, if this fits my scope and give you a feedback as soon as possible.
Best regards

**Comment by fwitte** [comment]
Hi @kyleniemeyer,
I would be happy to review the paper.
Best

**Comment by kyleniemeyer** [comment]
@whedon add @fwitte as reviewer

Thanks @fwitte!

**Comment by whedon** [comment]
OK, @fwitte is now a reviewer

**Comment by kyleniemeyer** [comment]
OK, with two reviewers set, I will now start the review issue.

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2814.
