### ISSUE TITLE
[PRE REVIEW]: Mangal.jl and EcologicalNetworks.jl: Two complementary packages for analyzing ecological networks in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2680]
**Submitting author:** @FrancisBanville (<a href="http://orcid.org/0000-0001-9051-0597">Francis Banville</a>)
**Repository:** <a href="https://github.com/EcoJulia/EcologicalNetworks.jl" target ="_blank">https://github.com/EcoJulia/EcologicalNetworks.jl</a>
**Version:** v0.3.0
**Editor:** @KristinaRiemer
**Reviewers:** @kellykochanski, @arbennett
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @FrancisBanville. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@FrancisBanville if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.13 s (377.5 files/s, 16585.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           26            206             43            861
Markdown                        15            277              0            579
YAML                             5              9              0            103
TOML                             2              5              0             26
-------------------------------------------------------------------------------
SUM:                            48            497             43           1569
-------------------------------------------------------------------------------


Statistical information for the repository '2680' was gathered on 2020/09/17.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2680 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss-manuscript

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-manuscript. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02680/joss.02680/10.21105.joss.02680.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02680/joss.02680/10.21105.joss.02680.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @FrancisBanville, thanks for your submission to JOSS. We'll be using this issue to assign the editor and reviewers, and also get any technical/logistical issues out of the way.

**Comment by kyleniemeyer** [comment]
@FrancisBanville one issue with your submission is that usually we only review a single software package at a time, though with some exceptions, and I think that your grouping of these two packages together does make sense.

However, you have specified Mangal.jl as the "main" repository for the submission, and your paper is in this repo. Since Mangal.jl would not actually be in the scope of JOSS by itself (as an API wrapper), we would prefer for EcologicalNetworks.jl to be the "main" repository submitted. 

We can switch the software repo pointed to internally, but can you also move the paper to the EcologicalNetworks.jl repository? It is fine to live in a branch there, as it is currently in the Mangal.jl repo.

cc @arfon

**Comment by FrancisBanville** [comment]
Thank you @kyleniemeyer! The paper has been moved to the [EcologicalNetworks.jl repository](https://github.com/EcoJulia/EcologicalNetworks.jl/), in the branch `joss-article`.

**Comment by arfon** [comment]
Updated on our end too @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss-article

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-article. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02680/joss.02680/10.21105.joss.02680.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02680/joss.02680/10.21105.joss.02680.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@FrancisBanville @arfon looks good, thanks!

**Comment by kyleniemeyer** [comment]
Hi @KristinaRiemer, can you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @KristinaRiemer as editor

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by KristinaRiemer** [comment]
@kyleniemeyer I have no experience with Julia. Would it be sufficient to find two reviewers who do (and use this as a chance to introduce myself too)?

**Comment by kyleniemeyer** [comment]
@KristinaRiemer absolutely! As editor you don't really need to dive into the software itself—unless you want to!—as long as the reviewers have the appropriate expertise.

**Comment by KristinaRiemer** [comment]
I usually do poke around with the code a bit, to learn more about how other folks structure and document their software. I'll be editor for this.

**Comment by KristinaRiemer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @KristinaRiemer

**Comment by KristinaRiemer** [comment]
@arbennett @eviatarbach @kavir1698 @kellykochanski would any of you be able and willing to review this JOSS submission?

**Comment by kellykochanski** [comment]
@KristinaRiemer sure.

**Comment by eviatarbach** [comment]
Unfortunately I cannot commit to review this one. Thank you for the invitation!

**Comment by KristinaRiemer** [comment]
Awesome, thanks @kellykochanski! And no big deal @eviatarbach, thanks for getting back about it. 

This will still need a second reviewer, if @arbennett or @kavir1698 are able?

**Comment by KristinaRiemer** [comment]
@whedon assign @kellykochanski as reviewer

**Comment by whedon** [comment]
OK, @kellykochanski is now a reviewer

**Comment by arbennett** [comment]
Ah, sorry for the delay - I'd be happy to review this @KristinaRiemer!

**Comment by KristinaRiemer** [comment]
No problem at all @arbennett and thanks for being willing!

**Comment by KristinaRiemer** [comment]
@whedon add @arbennett as reviewer

**Comment by whedon** [comment]
OK, @arbennett is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2721.

**Comment by KristinaRiemer** [comment]
@kellykochanski @arbennett the actual review will happen in the issue linked to above. Let me know there if you have questions!
