### ISSUE TITLE
[PRE REVIEW]: AuthorRank: A Python package for to finding the most prestigious authors in a scientific collaboration network

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2681]
**Submitting author:** @vc1492a (<a href="http://orcid.org/0000-0002-5279-4143">Valentino Constantinou</a>)
**Repository:** <a href="https://github.com/adidier17/AuthorRank" target ="_blank">https://github.com/adidier17/AuthorRank</a>
**Version:** 0.1.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vc1492a. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @lorenanicole.

@vc1492a if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=3.89 s (7.7 files/s, 6827.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       3           3123            481          17428
JSON                             7              2              0           2808
Markdown                         4             84              0            418
Python                          10            172            248            356
TeX                              1              9              0            110
Jupyter Notebook                 2              0           1146            100
HTML                             1              5              2             21
CSS                              1              2              0             17
YAML                             1              4              4             15
-------------------------------------------------------------------------------
SUM:                            30           3401           1881          21273
-------------------------------------------------------------------------------


Statistical information for the repository '2681' was gathered on 2020/09/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Annie Didier                     2           148            147            1.31
adidier17                        3           101             10            0.49
vc1492a                         27         21922            211           97.95
vconstan                         4            53              5            0.26

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Annie Didier                  7            4.7          5.9               14.29
vc1492a                   21751           99.2          5.4                2.77
vconstan                     50           94.3          1.6               22.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ipm.2005.03.012 is OK
- 10.1007/bf03025416 is OK
- 10.1145/945721.945722 is OK
- 10.1109/TVCG.2011.185 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02681/joss.02681/10.21105.joss.02681.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02681/joss.02681/10.21105.joss.02681.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@whedon reject

:wave: @vc1492a, thanks for your submission to JOSS. After review by our editorial team, this submission has been flagged as out of scope as a minor utility.

**Comment by whedon** [comment]
Paper rejected.
