### ISSUE TITLE
[PRE REVIEW]: Bempp-cl: A fast Python based just-in-time compiling boundary element library.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2682]
**Submitting author:** @mscroggs (<a href="http://orcid.org/0000-0002-4658-2443">Matthew Scroggs</a>)
**Repository:** <a href="https://github.com/bempp/bempp-cl" target ="_blank">https://github.com/bempp/bempp-cl</a>
**Version:** v0.2.1
**Editor:** @meg-simula
**Reviewers:** @jamtrott, @ramisetti
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mscroggs. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @meg-simula.

@mscroggs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.parco.2011.09.001 is OK
- 10.1002/nme.2579 is OK
- 10.1109/TAP.1982.1142818 is OK
- 10.1007/BFb0064470 is OK
- 10.1007/BF01396415 is OK
- 10.1016/j.crma.2004.12.022 is OK
- 10.1016/j.camwa.2017.07.049 is OK
- 10.1145/2833157.2833162 is OK
- 10.1007/978-0-387-68805-3 is OK
- 10.1145/3368618 is OK
- 10.1145/2590830 is OK
- 10.1002/zamm.19850650104 is OK

MISSING DOIs

- 10.2307/3621632 may be a valid DOI for title: Strongly elliptic systems and boundary integral equations

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=2.63 s (64.2 files/s, 16759.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         106           5389           6320          21162
OpenCL                          24            713             54           3176
Lisp                            10            288              0           1853
C/C++ Header                     7            363             27           1232
Jupyter Notebook                 8              0           2260            543
TeX                              1             19              0            165
YAML                             5             13             12            162
Markdown                         3             36              0            119
Dockerfile                       1             24             27             89
JSON                             1              0              0             30
make                             1              4              6              9
reStructuredText                 1              3              3              4
INI                              1              1              0              2
-------------------------------------------------------------------------------
SUM:                           169           6853           8709          28546
-------------------------------------------------------------------------------


Statistical information for the repository '2682' was gathered on 2020/09/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Matthew Scroggs                 87         14639          13133           23.72
Timo Betcke                    252         61033          28175           76.19
paul                             1           101              0            0.09

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Matthew Scroggs            3363           23.0          2.0               11.86
Timo Betcke               31040           50.9          4.9               13.35
paul                         90           89.1          0.7               13.33
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02682/joss.02682/10.21105.joss.02682.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02682/joss.02682/10.21105.joss.02682.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @meg-simula, can you edit this submission?

@mscroggs we'll be using this issue to get things started, including finding reviewers—any suggestions you have are welcome.

**Comment by kyleniemeyer** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by meg-simula** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by meg-simula** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02682/joss.02682/10.21105.joss.02682.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02682/joss.02682/10.21105.joss.02682.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
@mscroggs Thanks for the submission, nice work! Before proceeding, could I ask you to take a look at the JOSS submission guidelines regarding paper length, and recommended structure: 

https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

**Comment by mscroggs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02682/joss.02682/10.21105.joss.02682.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02682/joss.02682/10.21105.joss.02682.pdf) :page_facing_up: :point_left:

**Comment by mscroggs** [comment]
@meg-simula Thanks, we've shortened and restructured it

**Comment by meg-simula** [comment]
@mscroggs Great, nicely done. Would you happen to have any suggestions for reviewers?

**Comment by mscroggs** [comment]
mikaem and sebastkm could be good fits for reviewers.

(We should avoid jorgensd, IgorBaratta, chrisrichardson and garth-wells as I'm currently working closely with them.)

**Comment by meg-simula** [comment]
@whedon assign @jamtrott as reviewer

**Comment by whedon** [comment]
OK, @jamtrott is now a reviewer

**Comment by meg-simula** [comment]
@mscroggs Just stopped by to apologies for the delay in getting this review started. Still looking for reviewers, but hopefully that will resolve soon.

**Comment by meg-simula** [comment]
@kparas @jonathanskilling @ramisetti @tjford Would either of you be available to review this paper for JOSS?

**Comment by ramisetti** [comment]
@meg-simula, Yes I am available to review this paper for JOSS

**Comment by meg-simula** [comment]
@ramisetti Great, thanks! Then we can get this review started!

**Comment by meg-simula** [comment]
@whedon add @ramisetti as reviewer

**Comment by whedon** [comment]
OK, @ramisetti is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2879.
