### ISSUE TITLE
[PRE REVIEW]: AOSAT: Adaptive Optics Simulation Analysis Tool(kit)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2686]
**Submitting author:** @mfeldt (<a href="http://orcid.org/0000-0002-4188-5242">Markus Feldt</a>)
**Repository:** <a href="https://github.com/mfeldt/AOSAT" target ="_blank">https://github.com/mfeldt/AOSAT</a>
**Version:** v1.0
**Editor:** @pibion
**Reviewers:** @mvandam, @frigaut
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mfeldt. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @pibion.

@mfeldt if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02686/joss.02686/10.21105.joss.02686.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02686/joss.02686/10.21105.joss.02686.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @pibion, the authors suggested you to edit this submission—it's a bit outside your primary area, but can you take it?

**Comment by kyleniemeyer** [comment]
@whedon invite @pibion as editor

**Comment by whedon** [comment]
@pibion has been invited to edit this submission.

**Comment by pibion** [comment]
@kyleniemeyer I'd love to edit this paper.  Telescopes are outside my area of instrumental expertise, so I'll be looking for three reviewers.  So if you know of any editors who have expertise in telescopes, feel free to boot me?

**Comment by pibion** [comment]
@whedon assign @pibion as editor

**Comment by whedon** [comment]
OK, the editor is @pibion

**Comment by kyleniemeyer** [comment]
@arfon might have suggestions on such reviewers?

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=40.15 s (2.0 files/s, 694.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       9           2201           2234           8335
HTML                            16           2276             48           4904
Python                          23            822           1423           1855
CSS                              4            328             50           1248
reStructuredText                21            461            463            565
Markdown                         2             47              0            173
TeX                              1             16              0            167
make                             2             35             13            165
DOS Batch                        1              8              1             26
YAML                             2              5             10             14
-------------------------------------------------------------------------------
SUM:                            81           6199           4242          17452
-------------------------------------------------------------------------------


Statistical information for the repository '2686' was gathered on 2020/09/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
BuildTools                      22           391            207            2.57
Horst Steuer                     2            31             31            0.27
Markus Feldt                    27         16968            463           75.04
Stefan Hippler                   1            16             10            0.11
mfeldt                          15          2643           2468           22.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
BuildTools                  290           74.2          3.1               10.00
Horst Steuer                 25           80.6          9.0               12.00
Markus Feldt              16545           97.5          8.4               16.26
Stefan Hippler               10           62.5          9.8               10.00
```

**Comment by arfon** [comment]
> @arfon might have suggestions on such reviewers?

I don't really sorry but this search came up with a good number of possible results: https://github.com/search?q=adaptive+optics

**Comment by pibion** [comment]
@arfon thanks, that helps!  I've also got a lead from a friend in telescope-astro.  I've got a bunch of emails out :)

**Comment by pibion** [comment]
@mfeldt apologies for the delay!  I'm still recruiting adaptive optics folks.  If you have any suggestions please let me know.  In the meantime I'll keep looking :)

**Comment by mfeldt** [comment]
Ideal reviewers for the AO part would of course be the authors of the simulation packages under analysis here... e.g. 
Francois Rigaut (frigaut),  Marcos van Dam (mvandam), or Rod Conan (rconan).

**Comment by pibion** [comment]
@frigaut, @mvandam, @rconan would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by mvandam** [comment]
I could possibly do it, but I am not sure what the review entails. I don't know much about JOSS! Is it a review of the paper describing the software or is it also a review of the software? Can I see the paper and the evaluation form (if any) before agreeing to review the submission? Thanks!

**Comment by frigaut** [comment]
Yes, I have to admit I am in the same category. I am very much in favour of open journals, and would love to help, but your message lack context and a personal touch. Who is sending this email?
Cheers
Francois

**Comment by pibion** [comment]
@mvandam , @frigaut this is Amy Roberts - I'm one of the editors of JOSS (https://joss.theoj.org/about).

The review is a review of both the software and the paper.  JOSS reviews are a bit different from traditional journal reviews in that once it's been decided that the paper is in scope, the purpose of the review is to work with the author to improve the code so that it meets the basic JOSS publication standards.

So the review will consist of going through the checklist (https://joss.readthedocs.io/en/latest/review_checklist.html) here on github.

Let me know if you have any more questions!  I'm also happy to find a time to chat if that'd help.

**Comment by mvandam** [comment]
OK, I am happy to give it a go!

**Comment by pibion** [comment]
@whedon add @mvandam as reviewer

**Comment by whedon** [comment]
OK, @mvandam is now a reviewer

**Comment by pibion** [comment]
@mvandam excellent, thanks!  There will be a bit of a wait - we need at least one more reviewer - and then I'll start the review.

At that point, I'll open a new issue and invite you (and all the other reviewers) to the issue.  "Doing the review" will consist of going through the checklist.  In some cases, checking off boxes will require some back-and-forth with the author.

**Comment by frigaut** [comment]
Alright, I am curious about this ne wkind of review (at least new for me), and I would be interested to give it a go too, to the extent of my abilities.
Count me in.
Francois

**Comment by pibion** [comment]
@whedon add @frigaut as reviewer

**Comment by whedon** [comment]
OK, @frigaut is now a reviewer

**Comment by pibion** [comment]
Woohoo!  We're ready to start the review!

**Comment by pibion** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2764.
