### ISSUE TITLE
[PRE REVIEW]: RefManageR: Import and Manage BibTeX and BibLaTeX References in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#269]
**Submitting author:** @mwmclean (<a href="http://orcid.org/0000-0002-7891-9645">Mathew McLean</a>)
**Repository:** <a href="https://github.com/mwmclean/RefManageR" target ="_blank">https://github.com/mwmclean/RefManageR</a>
**Version:** v0.13.4
**Editor:** @karthik
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @mwmclean. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mwmclean if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @noamross - would this package be suitable for rOpenSci?

**Comment by noamross** [comment]
Yes, this may be eligible for rOpenSci under our reproducibility and data access categories.  @mwmclean, if you are interested in joint submission, you may find more information [here](https://github.com/ropensci/onboarding#how-to-submit-your-package-for-review).

**Comment by karthik** [comment]
@arfon we are discussing this internally, will update thread shortly.

**Comment by karthik** [comment]
Have sent a request to @cboettig for a review. Will update thread soon.

**Comment by karthik** [comment]
@cboettig Please ignore this request. I see that @noamross has already pinged you at ropensci onboarding. Will place this issue into holding till the review is complete there. @noamross Please ping when that is done.

**Comment by mwmclean** [comment]
@noamross the DOI is 10.5281/zenodo.835547.

**Comment by noamross** [comment]
@arfon This package has been approved through ropensci onboarding and the review thread is here: https://github.com/ropensci/onboarding/issues/119

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/338. Feel free to close this issue now!
