### ISSUE TITLE
[REVIEW]: UVehavior: An Annotation Desktop-Tool for Behavioral Observation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2692]
**Submitting author:** @Manolomon (<a href="http://orcid.org/0000-0002-3398-2632">J. Manuel Pérez-Verdejo</a>)
**Repository:** https://github.com/Manolomon/uvehavior-desktop
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @marcosvital
**Reviewers:** @SteveViss, @62442katieb
**Archive:** Pending

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2bce0a4981246d244eb0fc25d49d6aec/status.svg)](https://joss.theoj.org/papers/2bce0a4981246d244eb0fc25d49d6aec)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2bce0a4981246d244eb0fc25d49d6aec"><img src="https://joss.theoj.org/papers/2bce0a4981246d244eb0fc25d49d6aec/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2bce0a4981246d244eb0fc25d49d6aec/status.svg)](https://joss.theoj.org/papers/2bce0a4981246d244eb0fc25d49d6aec)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Manolomon/uvehavior-desktop" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@SteveViss & @62442katieb, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @marcosvital know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Manolomon/uvehavior-desktop">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Manolomon) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Manolomon/uvehavior-desktop">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Manolomon) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @SteveViss, @62442katieb it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/S0140525X00018653 is OK
- 10.1038/s41567-018-0093-0 is OK
- 10.1080/09637486.2019.1580680 is OK
- 10.1007/978-3-319-12742-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02692/joss.02692/10.21105.joss.02692.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02692/joss.02692/10.21105.joss.02692.pdf) :page_facing_up: :point_left:

**Comment by marcosvital** [comment]
Dear @Manolomon: your manuscript will be reviewed in this issue, and you can reply any comments and suggestions that the reviewers might address right here.

**Comment by marcosvital** [comment]
@SteveViss and @62442katieb: thank you again for for accepting review this submission for JOSS.

Even if you are not starting the review right now, please accept the invite, as it has an expiration date (there is a link under Reviewer instructions & questions and you should also get an email notification). Furthermore, please check the instructions and checklists above, and let me know if you need any assistance.

You can also tag @Manolomon if you need to ask specific questions about the submission or to address any changes that might be necessary in the submitted paper or in the repository.

**Comment by marcosvital** [comment]
Hi, @SteveViss and @62442katieb. This is just a gentle reminder about this revision. As always, please let me know if you need any assistance, and don't hesitate to tag @Manolomon if you have any questions about the paper submitted.

**Comment by marcosvital** [comment]
Hi again, @SteveViss and @62442katieb! Hope everything is fine with both of you. Any news about this revision? Please don't hesitate to ask for assistance if you need, and also feel free to let me know if you are not able to review this submission anymore (it happens sometimes).

**Comment by 62442katieb** [comment]
Hi @marcosvital & @Manolomon! Apologies for the delay. I am able to finish up my review in the coming week, but have had some permissions issues installing the package on my university-issued laptop. Will follow up in the coming days. Thanks!

**Comment by 62442katieb** [comment]
In the mean time, I have a few small comments regarding the paper:
- In the *Summary*, the authors should consider switching mentioning ethology as "behavioral analysis" and "behavioral science" are broad, nonspecific terms, and specifying their scope would be helpful in introducing the tool. 
- The authors should provide a description how this task is currently performed, in addressing the "state of the field". From an outside perspective, do people usually use another software tool? Pen and paper? Excel spreadsheets? I think it might help, too, in showing the utility and value of their tool.

Regarding documentation:
- The authors should consider adding to the wiki homepage, as it is not immediately apparent to users how to find the information they're looking for, once they've been directed there from the README. Even just mentioning in the main body text the different pages (Home, Maintenance, Test, Usage) and a brief description would be really helpful to orient users.
- Additionally, the "Usage" page does not contain much usage on how to set up and perform an experiment, skipping from "tests and subject of interest must be added. Every element regarding experiment planning and management are displayed in the following view..." to "Once the behavioral observations have been recorded..." without much information about how one goes about adding subjects and texts or how to add recordings or bind keys to behaviors. I think users would be much more capable of making full use of this tool to improve their research if a few more details are added to the documentation.
- Installation instructions from building from source are good, but there's no information beyond links for installing from a disk image, .exe, or app image. A few instructions might be helpful here, too.

**Comment by Manolomon** [comment]
Hello @62442katieb, thank you for your comments. My coauthors and I are going to address them in the next commit and mention it here. Regarding the tool, feel free to ask for assistance if needed. Regards!

**Comment by marcosvital** [comment]
Hi, @Manolomon, I'm passing by to see how things are going with this first round of review. Let us know when you make any progress, ok?

@62442katieb and @SteveViss, feel free to keep raising other issues that you think that are needed while the authors are working with those - but of course, you can also wait for this first round to end if that feels better.

**Comment by marcosvital** [comment]
Hi, again! passing by to check if there is any progress on this review, since there is some time since the last activities here.

@Manolomon, please let us knows if you have any news, ok?

**Comment by marcosvital** [comment]
Hi, @Manolomon! Passing by again to check if there is any progress. Please, let me know if you have any problems, ok?

**Comment by Manolomon** [comment]
Hello, @marcosvital. First of all, I would like to apologize to everyone for the late response. I updated the corresponding changes to the paper a month ago and tested them on the preview page. However, I forgot to command wedon. I'm sorry for the misunderstanding and hope we can keep the review ongoing.
Sincerely 
Manuel

**Comment by Manolomon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02692/joss.02692/10.21105.joss.02692.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02692/joss.02692/10.21105.joss.02692.pdf) :page_facing_up: :point_left:

**Comment by marcosvital** [comment]
Hi, @Manolomon, good to hear from you! No problem, we can proceed if the reviewers are still available. 

@SteveViss and @62442katieb, we have a new version of the manuscript. Let me know if you can still proceed with the reviewing process, ok?

**Comment by marcosvital** [comment]
Hi, @SteveViss and @62442katieb! Any news on this revision? Let me know if you are facing any problems, ok?

**Comment by 62442katieb** [comment]
Hi @marcosvital , I've taken a look at the paper revision and am updating my comment accordingly:
> A few small comments regarding the paper:
> 
> * In the _Summary_, the authors should consider switching mentioning ethology as "behavioral analysis" and "behavioral science" are broad, nonspecific terms, and specifying their scope would be helpful in introducing the tool.

Addressed 👍 Thanks!
> * The authors should provide a description how this task is currently performed, in addressing the "state of the field". From an outside perspective, do people usually use another software tool? Pen and paper? Excel spreadsheets? I think it might help, too, in showing the utility and value of their tool.

Also addressed 👍 Thanks!
> 
> Regarding documentation:
> 
> * The authors should consider adding to the wiki homepage, as it is not immediately apparent to users how to find the information they're looking for, once they've been directed there from the README. Even just mentioning in the main body text the different pages (Home, Maintenance, Test, Usage) and a brief description would be really helpful to orient users.
> * Additionally, the "Usage" page does not contain much usage on how to set up and perform an experiment, skipping from "tests and subject of interest must be added. Every element regarding experiment planning and management are displayed in the following view..." to "Once the behavioral observations have been recorded..." without much information about how one goes about adding subjects and texts or how to add recordings or bind keys to behaviors. I think users would be much more capable of making full use of this tool to improve their research if a few more details are added to the documentation.
> * Installation instructions from building from source are good, but there's no information beyond links for installing from a disk image, .exe, or app image. A few instructions might be helpful here, too.

I took a look at commits and PRs to the UVehavior repository and haven't seen any changes to these files. Could you provide an update @Manolomon on any plans to update documentation?

**Comment by 62442katieb** [comment]
Additionally, in reviewing the paper, I noticed a few typos and grammatical issues:
- page 1, line 39: "**Is** by their belonging group that the individuals are subjected to a treatment...", should read, "**It is** by their..."
- page 2, line 41: "UVehavior allows the researcher to **keep** track of their subjects, and **distribute** them by groups, as well as **managing** the tests to be conducted." The verb tenses in this sentence are mixed, to retain parallel tenses, it should read, "UVehavior allows the researcher to **keep** track of their subjects, **distribute** them by groups, and **manage** the tests to be conducted." (minor additional edit of clunky conjunctions)

**Comment by Manolomon** [comment]
Hello @62442katieb, thanks for your review. I'm addressing the typos as soon as possible. Regarding the documentation, we are currently working on it as part of an upcoming update to the system. We hope to include most of those changes this week.

Thank you, and best regards

**Comment by marcosvital** [comment]
Hi, @Manolomon! I'm just passing by to check if you have any news on the revision. Let us know if you have any problems, ok?

**Comment by marcosvital** [comment]
Hello again, @Manolomon. Any news on you progress? Let us know if you are still working on this or if you are having any problems.

**Comment by Manolomon** [comment]
Hello again @marcosvital. I'm sorry this revision has taken so long. During the last months, I had been dealing with all my graduation-related processes and couldn't find the time to keep maintaining uvehavior. Now I and my colleagues have updated the repository and most importantly, generated full-length documentation on the [wiki site](https://github.com/Manolomon/uvehavior-desktop/wiki), as requested by @62442katieb.

I'm sorry again for all the late responses, but I'm now fully committed to the project and the revision.

**Comment by marcosvital** [comment]
Thank you for you update, @Manolomon! 

@SteveViss and @62442katieb, I know this review is taking a long time, so please let me know if you are still available to carry on with this, ok?

**Comment by 62442katieb** [comment]
Hi @marcosvital and @Manolomon ! I'm happy to continue reviewing, but have a conference and my defense in the next two weeks, so I probably won't get to it until the first week of July. Looking forward to sifting through the updated documentation!

**Comment by marcosvital** [comment]
OK, @62442katieb, thank you for letting us know!

**Comment by marcosvital** [comment]
Hi again, @Manolomon! Hope everything is fine with you. Let us know if you have made any advances that should let the reviewers continue with the process.

**Comment by heacosta** [comment]
Hello, the last suggestions that were asked were answered on June 12. Since then we have not received any new requests. Thank you in advance for reviewing the status of the review.

**Comment by marcosvital** [comment]
Thank you, @heacosta. I'll generate a new version of the manuscript.

Dear @SteveViss and @62442katieb, thank you for your patience and all the work you've done so far. I'm generating an updated proof and you can also check the updated documentation referred by @Manolomon above. Can you proceed with the reviewing process from there?

**Comment by marcosvital** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02692/joss.02692/10.21105.joss.02692.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02692/joss.02692/10.21105.joss.02692.pdf) :page_facing_up: :point_left:

**Comment by 62442katieb** [comment]
Hi @marcosvital, @Manolomon, & @heacosta ! Yes, I will review the updated proof and documentation this week. Thanks for pinging me!

**Comment by 62442katieb** [comment]
I just finished looking over the revised manuscript, documentation, and software. My comments are below:

Manuscript:
- line 12: "... we introduce UVehavior, **and** open-source tool..." I believe the bold "and" should be "an"
- line 75: "... whereas the horizontal one represents the _chronological order_..."; it would be more accurate to say that the horizontal axis represents time, as it presents elapsed seconds (which is important and valuable), instead of an ordinal scale of behavior occurrence

Documentation:
-  Overall very helpful! Thanks for taking the time to write all this out, it made using the tool much easier.
- Throughout the manuscript and in the GitHub README, the tool's name is written as "UVehavior", but in the documentation it is often "Uvehavior". The authors might want to edit this for consistency.
- There are a few typos in the documentation, the authors should consider proofreading and editing this text.

Software:
- Looks and works great, overall! Very nice tool.
- Authors might want to consider allowing users to resize the video viewer.

**Comment by Manolomon** [comment]
Hello @62442katieb, thank you very much for your review. We have implemented your suggested corrections in the manuscript, and looked for all minor typographical errors in our available documentation. We are glad that you found our tool nice and valuable.

**Comment by Manolomon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02692/joss.02692/10.21105.joss.02692.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02692/joss.02692/10.21105.joss.02692.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@SteveViss, @62442katieb – it looks like this submission might need you to take another look. Could you review the latest changes and update your checklists accordingly? Many thanks!

**Comment by marcosvital** [comment]
Hi again, @Manolomon. Did you get the chance to work on the documentation as pointed above?

@SteveViss, please let us know if you can continue.

**Comment by Manolomon** [comment]
Hello @marcosvital. Sorry for the late response, we are currently working on enhancing the available documentation for the software. It is our priority to fulfill all the remaining requirements and address all the observations so the review process can continue with no further delay. 
Best regards

**Comment by marcosvital** [comment]
Thnak you for the update, @Manolomon, and hope to hear from you soon.

**Comment by marcosvital** [comment]
Hello againd, @Manolomon. Any news concerning your submission?

**Comment by Manolomon** [comment]
Hello everyone.

Over the past year, my active participation in the development of the project entitled [Uvhevior](https://github.com/Manolomon/uvehavior-desktop) has been on hold and is not comparable to what it was at the time this submission started.
Unfortunately, this difference has escalated to a point that hinders the review from proceeding.
Due to this, my co-authors have come to the decision to **withdraw this submission** from being considered at the Journal of Open Source Software.

I sincerely apologize for all the inconvenience that this issue had caused, especially to the reviewers and the editorial team.

**Comment by marcosvital** [comment]
Thank you for leting us know, @Manolomon.

@SteveViss and @62442katieb, thank you so much for all the effort you put on reviewing this submission.

**Comment by marcosvital** [comment]
@openjournals/joss-eics the author requests a withdraw.

**Comment by kyleniemeyer** [comment]
@editorialbot withdraw

**Comment by kyleniemeyer** [comment]
Understood @Manolomon, thanks for letting us know. Thank you to @marcosvital, @SteveViss, and @62442katieb for your efforts.
