### ISSUE TITLE
[REVIEW]: subMALDI: an open framework R package for processing irregularly-spaced mass spectrometry data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2694]
**Submitting author:** @wesleyburr (<a href="http://orcid.org/0000-0002-2058-1899">Wesley Burr</a>)
**Repository:** <a href="https://github.com/wesleyburr/subMaldi" target ="_blank">https://github.com/wesleyburr/subMaldi</a>
**Version:** v1.0-5
**Editor:** @pibion
**Reviewers:** @jspaezp, @sigven, @tystan
**Archive:** <a href="https://doi.org/10.5281/zenodo.5498242" target="_blank">10.5281/zenodo.5498242</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c5362f45432a535c9a3642865702a3c2/status.svg)](https://joss.theoj.org/papers/c5362f45432a535c9a3642865702a3c2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c5362f45432a535c9a3642865702a3c2"><img src="https://joss.theoj.org/papers/c5362f45432a535c9a3642865702a3c2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c5362f45432a535c9a3642865702a3c2/status.svg)](https://joss.theoj.org/papers/c5362f45432a535c9a3642865702a3c2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/wesleyburr/subMaldi" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jspaezp & @sigven, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @pibion know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] Test that I can make edits
- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/wesleyburr/subMaldi">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@wesleyburr) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/wesleyburr/subMaldi">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@wesleyburr) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/wesleyburr/subMaldi">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@wesleyburr) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jspaezp, @sigven it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02694/joss.02694/10.21105.joss.02694.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02694/joss.02694/10.21105.joss.02694.pdf) :page_facing_up: :point_left:

**Comment by pibion** [comment]
@jspaezp, @sigven, could you confirm that you can check and uncheck the boxes at the top of this issue?

**Comment by sigven** [comment]
@pibion I am afraid I am not able to check any boxes, unsure as to why. I am logged in and have accepted the invitation.

**Comment by jspaezp** [comment]
@pibion I do seem to check the boxes in the issue

**Comment by pibion** [comment]
@whedon re-invite @sigven as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@sigven please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by pibion** [comment]
@sigven you'll need to accept the invitation at the link above.

**Comment by sigven** [comment]
@pibion Thanks! Checkboxes work finally now.

**Comment by pibion** [comment]
@sigven , @jspaezp , will you have time in the next few weeks to work on this review?  If you know when you'll have time I can set a reminder with whedon.

**Comment by jspaezp** [comment]
Hello @pibion, I referenced the issue I created in the host repository  a couple of weeks ago.
I also checked some of the boxes that I believe have been fully complied with the standards of the journal.

Let me know if anything additional is required and feel free to reach me to my email if I have not replied to an issue in 24h.

link to the issue:
https://github.com/wesleyburr/subMaldi/issues/5

**Comment by pibion** [comment]
@jspaezp excellent, thank you!  @wesleyburr let me know if you have any trouble finding the issue?

**Comment by pibion** [comment]
@sigven , will you have time in the next few weeks to work on this review? If you know when you'll have time I can set a reminder with whedon.

**Comment by wesleyburr** [comment]
> @jspaezp excellent, thank you! @wesleyburr let me know if you have any trouble finding the issue?

I did see this, just been swamped with the semester's work. Hoping to get started on @jspaezp's feedback this week.

**Comment by sigven** [comment]
@pibion Truly sorry for my delay with providing my review; I have been swamped with other obligations. Currently, I am struggling to see how I can provide my comments along with the review checklist, in the same manner as @jspaezp did? I have realized that I should creat an issue in [wesleyburr/subMadi](https://github.com/wesleyburr/subMaldi), but how do I technically refer to the checklist so that it also shows in the same issue (as @jspaezp has elegently accomplished)?

**Comment by pibion** [comment]
@sigven most people put their comments in this thread.  It's not as nice as what @jspaezp did but it does work!

I think I can provide some instructions for @jspaezp 's method, though, let me look into it :)

**Comment by pibion** [comment]
@sigven if you'd like to follow @jspaezp's style, you can open an issue over at https://github.com/wesleyburr/subMaldi and copy and paste the checklist into the message for your issue.

If you mention this issue (https://github.com/openjournals/joss-reviews/issues/2694) in your issue over at https://github.com/wesleyburr/subMaldi then it'll show up in our timeline over here.  This is what @jspaezp did near the top of his issue.

**Comment by wesleyburr** [comment]
@pibion - can you point me to JOSS policy on authorship changes? Specifically, we'd like to add an author, as we begin the work on the revisions. The maintainer status of this package is changing over to a new software author, and we'd like her to assist with the revisions as she will be the one maintaining the changes and adding to them into the future. 

Also, sincere apologies for the delay in beginning revisions - COVID is kicking our butts over here, and finding time to do science in this doom world has been hard.

**Comment by jspaezp** [comment]
@wesleyburr I dont't think there is a clear guideline on it ... I feel like it is OK to change them during the review process as long as the paper is modified and the final version contains information regarding what additions to the software/paper made that contribution authorship-worthy.

Especially since the reviewers (us...) have to check the following checkpoint before the paper is actually accepted. 

>>> Contribution and authorship: Has the submitting author (@wesleyburr) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

**Comment by wesleyburr** [comment]
Great, thanks. I'll make sure to make it clear where my contributions lie, personally - the first round of repo commits were all done by our lead author (and student supervisee), so all of my code writing and editing and such was funneled through her, and she integrated it into her personal repo, which eventually migrated to GitHub. Which isn't great for credit tracking! So for all the edits, we'll make sure that everyone contributes in their own way to the central repo so it's easy for you folks to tick your box.

**Comment by pibion** [comment]
@wesleyburr @sigven @jspaezp apologies for my long silence - I didn't realize how much time I needed off over the holidays.

I'm finally back online and wanted to check in to see what the current status of the paper is.  @wesleyburr are you currently working on responding to comments?

**Comment by wesleyburr** [comment]
Correct: we're working through the issues raised by the first review. Going to start tackling the second review this week.

**Comment by wesleyburr** [comment]
@pibion @sigven  - Hi, folks. We're working through the list of suggestions from @jspaezp, but I can't seem to find @sigven's review. Did it get recorded (and/or finished)? No shame whatsoever if it didn't: it's not like I've been responsive in this horrible time of COVID. But if we finish up the first round, we'd like to be able to keep going on the second round while we have momentum.

**Comment by wesleyburr** [comment]
@pibion: we're basically done the requests from @jspaezp - still expanding test coverage slightly as we have time, but otherwise the list of issues raised by his review have been corrected. Would appreciate an update on review #2 when you have time.

**Comment by pibion** [comment]
@jspaezp @wesleyburr just checking in - I'm currently looking for a second reviewer.  No luck yet but I've just sent out another round of emails.

**Comment by pibion** [comment]
@jspaezp @wesleyburr checking in again - the folks I invited in my last round of emails weren't able to review and I've sent out another round of invitations.

Sorry this is taking so long, I suspect people are a bit worn down right now.

**Comment by pibion** [comment]
@whedon add @tystan as reviewer

**Comment by whedon** [comment]
OK, @tystan is now a reviewer

**Comment by wesleyburr** [comment]
> OK, @tystan is now a reviewer

Hurrah! Thank you, @tystan: we appreciate your service greatly. Hopefully the already-revised package via @jspaezp's feedback will be easy/easier to review than our original.

**Comment by pibion** [comment]
@whedon re-invite @tystan as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@tystan please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by pibion** [comment]
@tystan could you accept the invite link and then confirm you can leave comments and edit the checklist at the top of this issue?

**Comment by tystan** [comment]
Hi @pibion, @whedon and @wesleyburr. Thanks for having me on board! I can confirm I can edit the checklist. I'm on leave until mid next week so I'll get back to this then.

**Comment by pibion** [comment]
@tystan thank you for confirming!

**Comment by wesleyburr** [comment]
@tystan - checking in, anything I can do to assist if you're at the stage of working through the review?

**Comment by jspaezp** [comment]
any update @tystan ?

**Comment by pibion** [comment]
@wesleyburr I've reached out to @tystan through email just in case they're not getting notifications.

**Comment by wesleyburr** [comment]
Great, thanks. I realized yesterday that we're coming up on the one-year anniversary! And it feels sad that after @jspaezp did such a great job, that we've been stuck for so long. Not blaming you at all - pandemics are hard!

**Comment by pibion** [comment]
@wesleyburr I know, right??  It was much easier to get things done at the beginning of the pandemic.  Now people are well and truly exhausted.  I'll start reaching out to additional potential reviewers next week depending on the response.

And thanks so much for your patience, this has been an incredibly long wait.

**Comment by tystan** [comment]
Hi all. Apologies for the radio silence. I will be starting this in earnest next week and feel free to pester me as much as you want until I finish it!

**Comment by pibion** [comment]
@tystan thanks for the update!

**Comment by tystan** [comment]
Hi @wesleyburr. Making my way through the reviewer checklist. I have found issues with the [sample workflow](https://wesleyburr.github.io/subMaldi/articles/subMALDI_workflow.html) and the [Processing with subMALDI vignette](https://wesleyburr.github.io/subMaldi/articles/subMALDIprocessing.html) that I have mentioned under "Functionality" of the review [here](https://github.com/wesleyburr/subMaldi/issues/22#issue-929174183). If these pages can be fixed up, I will be able to assess the package's functionality better. 

I couldn't add the screenshot I mentioned in the review note, so I am pasting it here to show you the resulting graph:
![graph-screenshot](https://user-images.githubusercontent.com/12855431/124116306-f9cb9c00-daad-11eb-8afb-1fe365464b31.png)

**Comment by wesleyburr** [comment]
@tystan - sorry for delay, caught me over the long weekend. The issue appears to be that the pkgdown-generated website didn't update with all our changes post-review by J. Paez. So the vignettes built into the **package** appear to be fine (we can't see what you see), but the **pkgdown** versions on the github.wesleyburr.com/subMaldi/ are referencing a year+ old code. I've re-generated the pkgdown, and uploaded it, and you should hopefully be not seeing the old code (which won't work, because we changed the syntax of the function calls a lot, to clean up some poor design). Let me know if this doesn't clear it up, or I'm misunderstanding something about your message, please. :)

(I've pinned a new release, 1.0-1, which has an updated .tar.gz if you'd like to install locally and then try things. The vignettes compile and run fine against this version, and the pkgdown is updated)

**Comment by tystan** [comment]
Great, thanks @wesleyburr. v1.0-1 installs and the online vignettes all work now (and I'm now using the in-package vignettes too, cheers for the heads up).

**Comment by wesleyburr** [comment]
@tystan - how's it going?

**Comment by tystan** [comment]
Hi @wesleyburr . I've got some leave and am away camping at the moment sorry but will be back next week. In the meantime, there are some things that are listed to be addressed in my reviewing notes [here](https://github.com/wesleyburr/subMaldi/issues/22#issue-929174183).

**Comment by wesleyburr** [comment]
Thanks, @tystan! Sophie and I will bang out your findings this week, along with the one outstanding thing from @jspaezp's review, and then hand it off to @pibion to setup final determination.

**Comment by wesleyburr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02694/joss.02694/10.21105.joss.02694.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02694/joss.02694/10.21105.joss.02694.pdf) :page_facing_up: :point_left:

**Comment by wesleyburr** [comment]
@tystan Can you check over this version now, please? I think we're pretty much done!

**Comment by tystan** [comment]
R CMD check was a success except for the error pasted below which is minor (is `subMALDI::select` being loaded in the `NAMESPACE` or it it legacy code?). 

No warnings when plotting in the vignette - now just prints a note to user (once in the `return()` statement and once to console using `cat()`?)

Have signed off and well done.

The only thing is the Gibb, S (2016) reference still has URL going off the side of the page

```
* checking examples ... ERROR
Running examples in 'subMALDI-Ex.R' failed
The error most likely occurred in:

> ### Name: rmveEmpty
> ### Title: Remove Empty Rows
> ### Aliases: rmveEmpty
> ### Keywords: manip methods
>
> ### ** Examples
>
>
> ## Load sample dataset "Mastre.rda"
> data("Master")
>
> ## Select only the spectra "Before1" and "Before2"
> ex <- select(Master, "full_mz", "Before1", "Before2")
Error in select(Master, "full_mz", "Before1", "Before2") :
  could not find function "select"
Execution halted
```

**Comment by wesleyburr** [comment]
Oh, I know what that error is - dplyr is only being loaded selectively now, to avoid the issue with signal::select and dplyr::select running into one another in the namespace. I'll fix that up, thanks for seeing it! I'm sure I ran the CMD check and had nothing.....

And I'll look at the URL and see if there's any way to fix it. Auto-formats are tricky.

Thanks, @tystan!

**Comment by wesleyburr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02694/joss.02694/10.21105.joss.02694.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02694/joss.02694/10.21105.joss.02694.pdf) :page_facing_up: :point_left:

**Comment by wesleyburr** [comment]
@pibion - I think we're done, at long last. Both issues with the reviews are finished, 20/20, and closed out. I've pushed a version (v1.0-4) which has all of the changes incorporated, and the final edited paper copy.

**Comment by pibion** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "-1105" (NAME) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:author=>["{Maux}, D. and {Enjalbal}, C. and {Martinez}, J. and {Aubagnac}, J.~L. and {Combarieu}, R."], :journal=>["J Am Mass Spectrom"], :month=>[:sep], :volume=>"12", :issue=>"10", :pages=>"1099"}]

**Comment by pibion** [comment]
@wesleyburr does the above error make sense to you?  @arfon the odd thing is this reference renders fine in the paper itself.

**Comment by pibion** [comment]
@wesleyburr ideally I'd like to see the `@whedon check references` command pass and then ask you to tag the version and archive it (through e.g. zenodo).  I'll need the archive DOI to recommend acceptance.

**Comment by wesleyburr** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "-1105" (NAME) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:author=>["Maux, D. and Enjalbal, C. and Martinez, J. and Aubagnac, J.~L. and Combarieu, R."], :journal=>["J Am Mass Spectrom"], :month=>[:sep], :volume=>"12", :issue=>"10", :pages=>"1099"}]

**Comment by wesleyburr** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "-1105" (NAME) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:author=>["Maux, D. and Enjalbal, C. and Martinez, J. and Aubagnac, J.~L. and Combarieu, R."], :journal=>["J Am Mass Spectrom"], :month=>[:sep], :volume=>"12", :issue=>"10", :pages=>"1099"}]

**Comment by wesleyburr** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "-1105" (NAME) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:author=>["{Maux}, D. and {Enjalbal}, C. and {Martinez}, J. and {Aubagnac}, J.~L. and {Combarieu}, R."], :journal=>["J Am Mass Spectrom"], :month=>[:sep], :volume=>"12", :issue=>"10", :pages=>"1099"}]

**Comment by wesleyburr** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "-1105" (NAME) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:author=>["{Maux}, D. and {Enjalbal}, C. and {Martinez}, J. and {Aubagnac}, J.~L. and {Combarieu}, R."], :title=>["{Static Secondary Ion MS to Monitor Solid-Phase Peptide Synthesis}"], :journal=>["J Am Mass Spectrom"], :year=>"2001", :month=>[:sep], :volume=>"12", :issue=>"10", :pages=>"1099"}]

**Comment by wesleyburr** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "-1521" (NAME) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:author=>["{Null}, A.~P. and {Hannis}, J.~C. and {Muddiman}, D.~C."], :title=>["{Genotying of Simple and Compound Short Tandem Repeat Loci Using Electrospray Ionization Fourier Transform Ion Cyclotron Resonance Mass Spectrometry}"], :journal=>["Anal Chem"], :year=>"2001", :month=>[:sep], :volume=>"73", :issue=>"18", :pages=>"4514"}]

**Comment by wesleyburr** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "-1521" (NAME) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:author=>["{Null}, A.~P. and {Hannis}, J.~C. and {Muddiman}, D.~C."], :title=>["{Genotying of Simple and Compound Short Tandem Repeat Loci Using Electrospray Ionization Fourier Transform Ion Cyclotron Resonance Mass Spectrometry}"], :journal=>["Anal Chem"], :year=>"2001", :month=>[:sep], :volume=>"73", :issue=>"18", :pages=>"4514"}]

**Comment by wesleyburr** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/ac0103928 is OK
- 10.1021/ac026213j is OK
- 10.1002/jms.396 is OK
- 10.1002/pmic.201300246 is OK
- 10.1186/1471-2105-8-101 is OK
- 10.1038/nbt.2377 is OK
- 10.1093/bioinformatics/btr645 is OK
- 10.1093/bioinformatics/bts447 is OK
- 10.1186/s12953-016-0107-8 is OK
- 10.1016/s1044-0305(01)00296-3 is OK

MISSING DOIs

- 10.1201/9780429200717-7 may be a valid DOI for title: Tidy data

INVALID DOIs

- https://doi.org/10.1016/j.forc.2020.100274 is INVALID because of 'https://doi.org/' prefix
```

**Comment by wesleyburr** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/ac0103928 is OK
- 10.1021/ac026213j is OK
- 10.1002/jms.396 is OK
- 10.1002/pmic.201300246 is OK
- 10.1186/1471-2105-8-101 is OK
- 10.1038/nbt.2377 is OK
- 10.1093/bioinformatics/btr645 is OK
- 10.1093/bioinformatics/bts447 is OK
- 10.1186/s12953-016-0107-8 is OK
- 10.1016/j.forc.2020.100274 is OK
- 10.18637/jss.v059.i10 is OK
- 10.1016/s1044-0305(01)00296-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by wesleyburr** [comment]
@pibion - so looks like it was a malformed field in one reference, not at all the one that was cited. Plus all of the page **ranges** weren't in {} or "", so were propagating issues. Fixed them all up.

**Comment by wesleyburr** [comment]
10.5281/zenodo.5498242 points to v1.0-5, which is the version with all of this fixed up.

**Comment by pibion** [comment]
@whedon set 10.5281/zenodo.5498242 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5498242" target="_blank">10.5281/zenodo.5498242</a> is the archive.

**Comment by pibion** [comment]
@whedon set v1.0-5 as version

**Comment by whedon** [comment]
OK. v1.0-5 is the version.

**Comment by pibion** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/ac0103928 is OK
- 10.1021/ac026213j is OK
- 10.1002/jms.396 is OK
- 10.1002/pmic.201300246 is OK
- 10.1186/1471-2105-8-101 is OK
- 10.1038/nbt.2377 is OK
- 10.1093/bioinformatics/btr645 is OK
- 10.1093/bioinformatics/bts447 is OK
- 10.1186/s12953-016-0107-8 is OK
- 10.1016/j.forc.2020.100274 is OK
- 10.18637/jss.v059.i10 is OK
- 10.1016/s1044-0305(01)00296-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2575

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2575, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1436229466775240707) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2577
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02694](https://doi.org/10.21105/joss.02694)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@jspaezp, @sigven, @tystan – many thanks for your reviews here and to @pibion for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@wesleyburr – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02694/status.svg)](https://doi.org/10.21105/joss.02694)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02694">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02694/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02694/status.svg
   :target: https://doi.org/10.21105/joss.02694
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02694/status.svg)](https://doi.org/10.21105/joss.02694)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
