### ISSUE TITLE
[REVIEW]: ObsPlus: A Pandas Centric ObsPy Expansion Pack

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2696]
**Submitting author:** @d-chambers (<a href="http://orcid.org/0000-0003-3656-6607">Derrick Chambers</a>)
**Repository:** <a href="https://github.com/niosh-mining/obsplus" target ="_blank">https://github.com/niosh-mining/obsplus</a>
**Version:** v0.1.0
**Editor:** @leouieda
**Reviewer:** @seisman, @ThomasLecocq
**Archive:** <a href="https://doi.org/10.5281/zenodo.4544008" target="_blank">10.5281/zenodo.4544008</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d1c82d31937fe0609963201c9d525430/status.svg)](https://joss.theoj.org/papers/d1c82d31937fe0609963201c9d525430)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d1c82d31937fe0609963201c9d525430"><img src="https://joss.theoj.org/papers/d1c82d31937fe0609963201c9d525430/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d1c82d31937fe0609963201c9d525430/status.svg)](https://joss.theoj.org/papers/d1c82d31937fe0609963201c9d525430)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/niosh-mining/obsplus" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@seisman & @ThomasLecocq, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @leouieda know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/niosh-mining/obsplus">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@d-chambers) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/niosh-mining/obsplus">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@d-chambers) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @seisman, @ThomasLecocq it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

-  10.25080/Majora-92bf1922-00a  is OK

MISSING DOIs

- 10.1088/1749-4699/8/1/014003 may be a valid DOI for title: ObsPy: A bridge for seismology into the scientific Python ecosystem

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02696/joss.02696/10.21105.joss.02696.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02696/joss.02696/10.21105.joss.02696.pdf) :page_facing_up: :point_left:

**Comment by leouieda** [comment]
👋 @d-chambers @seisman @ThomasLecocq  this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#2236` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 4 weeks. Please let me know if any of you require some more time. We can also use @whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me here (@leouieda) or email me privately if you have any questions/concerns.

**Comment by leouieda** [comment]
@d-chambers please have a look at the missing DOI report from Whedon above and add the missing DOIs to your BibTex file.

**Comment by d-chambers** [comment]
@leouieda my apologies, I missed this last request. I just added the correct DOI to the Bib Tex file.

**Comment by leouieda** [comment]
Hi @ThomasLecocq @seisman just checking in on the status of this review 🙂  Let me know if you have any questions or concerns.

**Comment by seisman** [comment]
Sorry for forgetting this paper. I'll review it in the following week.

**Comment by leouieda** [comment]
Thank you for the update @seisman 🙂

**Comment by leouieda** [comment]
👋🏼 Hi @seisman @ThomasLecocq just checking in to see how things are going with the reviews. It would be nice to get some progress on this soon but let me know if you require more time (we’re all living in strange times).

**Comment by seisman** [comment]
Hi @leouieda, sorry for the delay. I'm a little too busy with job interviews and preparing for AGU meeting recently. I may have more time in December.

**Comment by leouieda** [comment]
@seisman thanks for the update. I realize that the earlier than usual AGU deadlines are causing problems. Good luck on the job interviews and let me know when you have some more time.

@d-chambers apologies for the unusually long delays with this paper. I really appreciate your patience in these strange times we live in 😞

**Comment by d-chambers** [comment]
Hi @leouieda,

No worries, I understand the circumstances.

**Comment by leouieda** [comment]
Hi @seisman @ThomasLecocq are there any updates on this review?

**Comment by seisman** [comment]
I'll start to review the submission in the following week.

**Comment by arfon** [comment]
:wave: @ThomasLecocq @leouieda happy new year! Just checking in here on the status of this review?

**Comment by calum-chamberlain** [comment]
Sorry to pester,  but @leouieda are the any updates on this? I'm keen to have this out so that I can cite it for some upcoming papers for which ObsPlus had been very useful!

**Comment by ThomasLecocq** [comment]
It's all good for me

**Comment by d-chambers** [comment]
I would love to get this wrapped up soon. I addressed all of @seisman's comments thus far, but I am happy to make any additional improvements that might be required.

**Comment by seisman** [comment]
I reviewed the original v0.1.0 version. It's good for me.

**Comment by ThomasLecocq** [comment]
I can't check the boxes above, but I have no further remarks other than the citation for Pandas seem buggy in the latest rendered PDF. Other than that, it's good to go

**Comment by danielskatz** [comment]
@whedon re-invite @ThomasLecocq as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@thomaslecocq please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by danielskatz** [comment]
This should let you check the boxes

**Comment by ThomasLecocq** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2696 with the following error: 
```
 Error reading bibliography file paper.bib:
(line 7, column 9):
unexpected "Y"
expecting space, ",", white space or "}"
Looks like we failed to compile the PDF

```

**Comment by ThomasLecocq** [comment]
All 🟢 for me, just the missing Pandas citation in the PDF available above.

**Comment by d-chambers** [comment]
Ok the pdf now compiles and I think the citation looks correct.

@whedon generate pdf

**Comment by danielskatz** [comment]
@whedon generate pdf

(whedon commands need to be on the first line of a comment)

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02696/joss.02696/10.21105.joss.02696.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02696/joss.02696/10.21105.joss.02696.pdf) :page_facing_up: :point_left:

**Comment by ThomasLecocq** [comment]
All good now!

**Comment by kyleniemeyer** [comment]
Hi @d-chambers, I'm the AEIC on duty this week, and stepping in here to help get this past the finish line. It looks like the reviewers have both recommended this for acceptance.

Some final steps needed:
- [ ] Your article is missing a Statement of Need section, which is a [required element](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) of JOSS papers. You may be able to just move some existing text into that section.
- [ ] Once you've made that change, you can archive your software repository (e.g., on Zenodo) and provide the DOI here.

**Comment by d-chambers** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02696/joss.02696/10.21105.joss.02696.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02696/joss.02696/10.21105.joss.02696.pdf) :page_facing_up: :point_left:

**Comment by d-chambers** [comment]
Current-version DOI: http://doi.org/10.5281/zenodo.4544008

All-version DOI: http://doi.org/10.5281/zenodo.3228432

**Comment by d-chambers** [comment]
ok @kyleniemeyer, let me know if anything else is required. Also, thanks for your work on JOSS :smile:

**Comment by kyleniemeyer** [comment]
Thanks @d-chambers - can you clean up the author list on the current-version Zenodo record to match that of the paper?

**Comment by d-chambers** [comment]
Done. My apologies for not doing it originally, I am new to Zenodo.

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.4544008 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4544008" target="_blank">10.5281/zenodo.4544008</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

-  10.1088/1749-4699/8/1/014003  is OK
- 10.25080/Majora-92bf1922-00a is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2237

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2237, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@d-chambers sorry, looks like I missed something - the QuakeML is actually missing some key citation details, including a few authors, the volume (54) and number (1), and DOI: `10.4401/ag-4874`

Can you add these?

**Comment by d-chambers** [comment]
Ok, I have added the volume, number and DOI. 

The missing authors issues is interesting. The authors are included in the bib but don't show up in the PDF. Same issue for the ObsPy reference. I will dig into it more.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02696/joss.02696/10.21105.joss.02696.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02696/joss.02696/10.21105.joss.02696.pdf) :page_facing_up: :point_left:

**Comment by d-chambers** [comment]
Sorry haven't merged the changes to master yet, still trying to figure out why the middle authors aren't showing.

**Comment by kyleniemeyer** [comment]
Ah, I think the issue related to the commas in the `author` fields.

For the ObsPy reference, it should be `{Krischer, L. and Megies, T. and Barsch, R. and Beyreuther, M. and Lecocq, T. and Caudron, C. and Wassermann, J.}` (you want "and" rather than commas between the authors)

Also, you also do not need brackets around all the surnames, except in uncommon cases.

**Comment by kyleniemeyer** [comment]
and then `{Schorlemmer, D. and Euchner, F. and Kästli, P. and Saul, J.}` for QuakeML

**Comment by d-chambers** [comment]
@whedon generate pdf

Ok thanks, should be good now

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02696/joss.02696/10.21105.joss.02696.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02696/joss.02696/10.21105.joss.02696.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@d-chambers ah, one final issue: please remove the `https://doi.org/` from the QuakeML DOI, it should just include the DOI itself.

**Comment by d-chambers** [comment]
Done

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1749-4699/8/1/014003 is OK
- 10.3929/ethz-b-000034821 is OK
- 10.25080/Majora-92bf1922-00a is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2238

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2238, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1382831621691248641) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2239
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02696](https://doi.org/10.21105/joss.02696)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @d-chambers on your article's publication in JOSS! 

Many thanks to @seisman and @ThomasLecocq for reviewing this, and @leouieda for editing it.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02696/status.svg)](https://doi.org/10.21105/joss.02696)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02696">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02696/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02696/status.svg
   :target: https://doi.org/10.21105/joss.02696
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02696/status.svg)](https://doi.org/10.21105/joss.02696)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by d-chambers** [comment]
Thanks everyone. :tada:
