### ISSUE TITLE
[PRE REVIEW]: Predihood: an open-source tool for describing and predicting neighbourhoods' environment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2697]
**Submitting author:** @fduchatea (<a href="http://orcid.org/0000-0001-6803-917X">Fabien Duchateau</a>)
**Repository:** <a href="https://gitlab.liris.cnrs.fr/fduchate/predihood" target ="_blank">https://gitlab.liris.cnrs.fr/fduchate/predihood</a>
**Version:** 1.0
**Editor:** @galessiorob
**Reviewers:** @jdalzatec, @omshinde, @nuest, @martinfleis
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @fduchatea. **Currently, there isn't an JOSS editor assigned** to your paper.

@fduchatea if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2697 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1109/socialcom.2013.17 may be a valid DOI for title: Hoodsquare: Modeling and recommending neighborhoods in location-based social networks

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=3.32 s (652.4 files/s, 66999.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             7              0              0          60172
JavaScript                      28           9887          10791          38677
YAML                             4              0              0          25033
CSS                             28           5821            133          20740
SVG                           2001            224             28          18614
HTML                            25           1018              6           7925
Sass                            22           1439             35           7131
LESS                            21           1433             61           7082
Stylus                           3           1173              3           1903
Python                          19            377            591           1447
Markdown                         5            170              0            310
TeX                              1              2              0             20
-------------------------------------------------------------------------------
SUM:                          2164          21544          11648         189054
-------------------------------------------------------------------------------


Statistical information for the repository '2697' was gathered on 2020/09/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
DUCHATEAU FABIEN                 2             3              3            0.00
Duchateau Fabien                 7         48922             42           24.11
Nelly Barret                   121         21750          19104           20.12
nelly                            9         61758          51514           55.77

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Duchateau Fabien          48449           99.0          0.0               21.28
Nelly Barret              13321           61.2          4.1                5.93
```

**Comment by fduchatea** [comment]
Suggestions for potential reviewers: nuest, martinfleis, hugoledoux, molgor, nagelette, AndrewAnnex, omshinde,

**Comment by fduchatea** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02697/joss.02697/10.21105.joss.02697.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02697/joss.02697/10.21105.joss.02697.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@fduchatea - thanks for your submission. Could you clarify the research purpose of this software? I'm a little unclear reading your paper.

**Comment by fduchatea** [comment]
Hello @arfon and thank you. 
The motivation of the research is to characterize environment of neighbourhoods in a simple way (with a few attributes, such as type of buildings, type of landscape, location of the neighbourhood in the city, main social class, etc.). This is useful when people need to compare neighbourhoods (social sciences) or when searching an accomodation for instance.
However, in large countries, there are too many neighbourhoods (e.g., about 50,000 for France) and it is not possible to describe  environment for each of them. Thus we try to solve this issue using machine learning.
In our Predihood tool, it is possible:

- to change the dataset (in order to predict neighbourhood environments of other countries than France);
- to tune, test and evaluate existing classification algorithms (using a web interface);
- to define new classification algorithms and test them on our dataset.
 
Hope it clarifies. We can reformulate in the paper to make it more clear too.

**Comment by arfon** [comment]
Thanks @fduchatea.

> This is useful when people need to compare neighbourhoods (social sciences) or when searching an accomodation for instance.

Right. So the first of these sounds like a research question, the second is not. JOSS publishes _research_ software and so I'm trying to understand the research application of this tool.

Do you know if this tool has already been used for existing social science research?

**Comment by fduchatea** [comment]
Many social science researchers study the impact of neighbourhood environment with regards to a given criterion (eg, social conditions, health issues). But it is usually difficult to describe such environment, especially at large scale. Thus we propose Predihood as an initial solution (some environment variables, French neighbourhoods and existing prediction algorithms, all of them can be replaced/extended for different usages) to facilitate social science studies.
The tool can also be interested for machine learning researchers, as the prediction task seems difficult (our preliminary experiments achieve an accuracy between 33% to 65% depending on the variable), so they could develop more effective prediction algorithms.
 
This tool has been developed in the context of a research project, in collaboration with social science researchers.
Currently our tool has only been used in our project (but we released it a few weeks ago). Our objective was to study the impact of the neighbourhood environment when people moves in another city (eg, do they choose a similar environment? how their potential salary increase affect their choice of neighbourhood? etc.). Some preliminary results were published in the DATA conference (the 4th author is a researcher in social sciences):
Nelly Barret and Fabien Duchateau and Franck Favetta and Loïc Bonneval. _Predicting the Environment of a Neighborhood: a Use Case for France_, International Conference on Data Management Technologies and Applications (DATA), 2020. 
(citation has been updated in the JOSS paper since it was incomplete).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @bstabler as editor

**Comment by whedon** [comment]
@bstabler has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@bstabler :wave: could you handle this submission? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @bstabler as editor

**Comment by whedon** [comment]
@bstabler has been invited to edit this submission.

**Comment by danielskatz** [comment]
@galessiorob - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by galessiorob** [comment]
Sure thing! @danielskatz

**Comment by galessiorob** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02697/joss.02697/10.21105.joss.02697.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02697/joss.02697/10.21105.joss.02697.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1109/socialcom.2013.17 may be a valid DOI for title: Hoodsquare: Modeling and recommending neighborhoods in location-based social networks
- 10.5220/0009885702940301 may be a valid DOI for title: Predicting the Environment of a Neighborhood: a Use Case for France

INVALID DOIs

- None
```

**Comment by galessiorob** [comment]
👋 Hi @fduchatea 

I am in the process of assigning reviewers to this submission, in the meantime, it looks like there 2 missing DOIs, if you could add those down that would be great.

Many thanks!

Basic checks:

 - [ ] There’s a general description of the software
 - [ ] The software is within the scope as research software
 - [ ] OSI-approved license: GNU General Public License (GPL)

**Comment by fduchatea** [comment]
Hi @galessiorob,
Thank you for managing our submission.
Missing DOI have been added.

**Comment by fduchatea** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02697/joss.02697/10.21105.joss.02697.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02697/joss.02697/10.21105.joss.02697.pdf) :page_facing_up: :point_left:

**Comment by fduchatea** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02697/joss.02697/10.21105.joss.02697.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02697/joss.02697/10.21105.joss.02697.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment]
Thanks for adding those @fduchatea!

Could you please make sure that your repo [covers the submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements):

- Be stored in a repository that can be cloned without registration ✅ 
- Be stored in a repository that is browsable online without registration ✅ 
- Have an issue tracker that is readable without registration.
- Permit individuals to create issues/file tickets against your repository.

**Comment by galessiorob** [comment]
@whedon assign @martinfleis as reviewer

**Comment by whedon** [comment]
OK, @martinfleis is now a reviewer

**Comment by nuest** [comment]
@galessiorob Thanks for the ping via email - I'm happy to review this submission, though I can already second the concerns to clarify the research application (the first sentence makes it sound like individual citizens might want to use the tool).

Thank you for the opportunity to contribute to JOSS!

**Comment by galessiorob** [comment]
@whedon add @omshinde as reviewer

**Comment by whedon** [comment]
OK, @omshinde is now a reviewer

**Comment by galessiorob** [comment]
@fduchatea before I open a review issue for @nuest and @omshinde to start working on, could you please make sure to check off the following:

- [ ] Have an issue tracker that is readable without registration.
- [ ] Permit individuals to create issues/file tickets against your repository
- [ ] Expand and focus the software's research scope (see @nuest and my previous comments above)
- [ ] Expand the description of the software

Thanks! 🎉

**Comment by galessiorob** [comment]
@whedon assign @jdalzatec as reviewer

**Comment by whedon** [comment]
OK, @jdalzatec is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @omshinde as reviewer

**Comment by whedon** [comment]
OK, @omshinde is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @nuest as reviewer

**Comment by whedon** [comment]
OK, @nuest is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @martinfleis as reviewer

**Comment by whedon** [comment]
OK, @martinfleis is now a reviewer

**Comment by arfon** [comment]
:wave: @galessiorob - is this ready to go out for review? It looks like we have four reviewers assigned here :-)

**Comment by galessiorob** [comment]
I was waiting for @fduchatea to add [these details](https://github.com/openjournals/joss-reviews/issues/2697#issuecomment-714811843) but we can start the review and do it there.

**Comment by galessiorob** [comment]
Thanks for volunteering to review this paper @martinfleis, @nuest, @omshinde and @jdalzatec 🎉 

I'm going to open a fresh review issue that will contain individual checklists for each of you to work through, please let me know if you have any questions.

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2805.
