### ISSUE TITLE
[PRE REVIEW]: pytomoviewer.py: A simple tomography viewer with TIFF to RAW converter

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2698]
**Submitting author:** @victorsapucaia (<a href="http://orcid.org/0000-0002-5394-2603">Victor Wriedt Sapucaia</a>)
**Repository:** <a href="https://github.com/LCC-UFF/pytomoviewer" target ="_blank">https://github.com/LCC-UFF/pytomoviewer</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @victorsapucaia. **Currently, there isn't an JOSS editor assigned** to your paper.

@victorsapucaia if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (115.6 files/s, 13264.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         6            143              0            620
Python                           1             19             68            363
JSON                             5              0              0            150
TeX                              1             16              0            113
-------------------------------------------------------------------------------
SUM:                            13            178             68           1246
-------------------------------------------------------------------------------


Statistical information for the repository '2698' was gathered on 2020/09/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Victor                           1           450              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Victor                      450          100.0          0.0               13.33
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ISBI.2009.5193259 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.ijrmms.2018.04.020 is OK
- 10.1016/j.petrol.2020.107335 is OK
- 10.3390/fluids5010016 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1038/nmeth.2089 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02698/joss.02698/10.21105.joss.02698.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02698/joss.02698/10.21105.joss.02698.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

:wave: @victorsapucaia - thanks for your submission to JOSS. Given the size and scope of this package, I'm flagging it for editorial review for scope/fit in JOSS. This will likely take ~1 week before you hear back here.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by victorsapucaia** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@victorsapucaia thank you for this submission. We regret to inform you that after editorial review this work was found to be out of scope for JOSS. In particular this work was seen as too minor to warrant publication in JOSS (see our notes on [required amount of scholarly content](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)). This conclusion does not mean the software is of a poor quality or not useful, it merely means it is not in scope in its current form. 

We will now proceed to reject this submission. We do hope you will consider JOSS for future more extensive work or a re-submission of a significantly expanded version of this work. 

Note you may want to consider other venues to publish your work or enable citation. For instance archiving a release on ZENODO enables users to cite a DOI for your work. 

All the best, 

Kevin Moerman
_AEiC JOSS_

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
