### ISSUE TITLE
[REVIEW]: hawen: time-harmonic wave modeling and inversion using hybridizable discontinuous Galerkin discretization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2699]
**Submitting author:** @flofaucher (<a href="http://orcid.org/0000-0003-4958-7511">Florian Faucher</a>)
**Repository:** <a href="https://gitlab.com/ffaucher/hawen" target ="_blank">https://gitlab.com/ffaucher/hawen</a>
**Version:** 1.0.0
**Editor:** @meg-simula
**Reviewer:** @chennachaos, @yangbai90
**Archive:** <a href="https://doi.org/11353/10.1144094">11353/10.1144094</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/aaac99edf0ce2d26a3e22b69558b0b55/status.svg)](https://joss.theoj.org/papers/aaac99edf0ce2d26a3e22b69558b0b55)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/aaac99edf0ce2d26a3e22b69558b0b55"><img src="https://joss.theoj.org/papers/aaac99edf0ce2d26a3e22b69558b0b55/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/aaac99edf0ce2d26a3e22b69558b0b55/status.svg)](https://joss.theoj.org/papers/aaac99edf0ce2d26a3e22b69558b0b55)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/ffaucher/hawen" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@chennachaos & @yangbai90, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @meg-simula know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/ffaucher/hawen">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@flofaucher) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/ffaucher/hawen">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@flofaucher) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @chennachaos, @yangbai90 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02699/joss.02699/10.21105.joss.02699.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02699/joss.02699/10.21105.joss.02699.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
@yangbai90 @chennachaos Thanks again for agreeing to review. Checklists have been generated for each you above, ready for your review :-)

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/geo2019-0251.1 is OK
- 10.1093/gji/ggaa009 is OK
- 10.1051/m2an/2019009 is OK
- 10.1088/1361-6420/ab3507 is OK
- 10.1051/m2an/2019088 is OK
- 10.1016/j.jcp.2018.05.011 is OK
- 10.1137/15M1043856 is OK
- 10.1190/segam2016-13961828.1 is OK
- 10.1190/geo2019-0527.1 is OK
- 10.1137/S0036142901384162 is OK
- 10.1137/070706616 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1007/b98874 is OK
- 10.1190/1.3238367 is OK
- 10.1046/j.1365-246X.1998.00498.x is OK
- 10.1046/j.1365-246x.1999.00967.x is OK

MISSING DOIs

- 10.1016/j.cma.2020.113406 may be a valid DOI for title: Adjoint-state method for Hybridizable Discontinuous Galerkin discretization:  application to the inverse acoustic wave problem
- 10.1190/geo2019-0251.1 may be a valid DOI for title: A priori estimates of attraction basins for velocity model reconstruction by time-harmonic Full Waveform Inversion and Data Space Reflectivity formulation
- 10.1142/7486 may be a valid DOI for title: Waves and rays in elastic continua

INVALID DOIs

- None
```

**Comment by yangbai90** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by yangbai90** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.05 s (274.4 files/s, 97134.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                     278          10052          29918          59981
C                                3            153            152            468
TeX                              1             52             16            360
Markdown                         4             62              0            352
make                             1              3             26             18
-------------------------------------------------------------------------------
SUM:                           287          10322          30112          61179
-------------------------------------------------------------------------------


Statistical information for the repository 'cba03b43192a8c3431ac8a62' was
gathered on 2020/10/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Florian Faucher                  2           773              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Florian Faucher             773          100.0          0.0               19.79
```

**Comment by meg-simula** [comment]
@flofaucher @chennachaos @yangbai90 Just checking in to see how you are doing on this review? Do let me know if there is anything I can contribute with at this point.

**Comment by flofaucher** [comment]
@meg-simula Thanks, on my side, I guess I should wait for a formal reply before doing any modification is that correct? Or is there something I can/should start?

**Comment by meg-simula** [comment]
Correct,  we are awaiting feedback from the reviewers at this stage.

**Comment by chennachaos** [comment]
Hi. I have been busy with some personal stuff. I hope to complete the review in 2 to 3 weeks from today.

**Comment by yangbai90** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/geo2019-0251.1 is OK
- 10.1093/gji/ggaa009 is OK
- 10.1051/m2an/2019009 is OK
- 10.1088/1361-6420/ab3507 is OK
- 10.1051/m2an/2019088 is OK
- 10.1016/j.jcp.2018.05.011 is OK
- 10.1137/15M1043856 is OK
- 10.1190/segam2016-13961828.1 is OK
- 10.1190/geo2019-0527.1 is OK
- 10.1137/S0036142901384162 is OK
- 10.1137/070706616 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1007/b98874 is OK
- 10.1190/1.3238367 is OK
- 10.1046/j.1365-246X.1998.00498.x is OK
- 10.1046/j.1365-246x.1999.00967.x is OK

MISSING DOIs

- 10.1016/j.cma.2020.113406 may be a valid DOI for title: Adjoint-state method for Hybridizable Discontinuous Galerkin discretization:  application to the inverse acoustic wave problem
- 10.1190/geo2019-0251.1 may be a valid DOI for title: A priori estimates of attraction basins for velocity model reconstruction by time-harmonic Full Waveform Inversion and Data Space Reflectivity formulation
- 10.1142/7486 may be a valid DOI for title: Waves and rays in elastic continua

INVALID DOIs

- None
```

**Comment by yangbai90** [comment]
@flofaucher : Hi Florian, it seems some DOIs are still missing, if these references are completed, on my side, it's ready for publication.
BR
Yang

**Comment by flofaucher** [comment]
@whedon check references

**Comment by flofaucher** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/geo2019-0251.1 is OK
- 10.1093/gji/ggaa009 is OK
- 10.1051/m2an/2019009 is OK
- 10.1088/1361-6420/ab3507 is OK
- 10.1051/m2an/2019088 is OK
- 10.1016/j.jcp.2018.05.011 is OK
- 10.1137/15M1043856 is OK
- 10.1190/segam2016-13961828.1 is OK
- 10.1190/geo2019-0527.1 is OK
- 10.1016/j.cma.2020.113406 is OK
- 10.1137/S0036142901384162 is OK
- 10.1137/070706616 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1007/b98874 is OK
- 10.1190/1.3238367 is OK
- 10.1142/7486 is OK
- 10.1046/j.1365-246X.1998.00498.x is OK
- 10.1046/j.1365-246x.1999.00967.x is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1137/20M1336709 is INVALID
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/geo2019-0251.1 is OK
- 10.1093/gji/ggaa009 is OK
- 10.1051/m2an/2019009 is OK
- 10.1088/1361-6420/ab3507 is OK
- 10.1051/m2an/2019088 is OK
- 10.1016/j.jcp.2018.05.011 is OK
- 10.1137/15M1043856 is OK
- 10.1190/segam2016-13961828.1 is OK
- 10.1190/geo2019-0527.1 is OK
- 10.1016/j.cma.2020.113406 is OK
- 10.1137/S0036142901384162 is OK
- 10.1137/070706616 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1007/b98874 is OK
- 10.1190/1.3238367 is OK
- 10.1142/7486 is OK
- 10.1046/j.1365-246X.1998.00498.x is OK
- 10.1046/j.1365-246x.1999.00967.x is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1137/20M1336709 is INVALID
```

**Comment by flofaucher** [comment]
@whedon check references

**Comment by flofaucher** [comment]
@meg-simula  @yangbai90  Thank you, I have just updated the bibliography. There are two preprints that have been accepted that I listed as "to appear", I can update with the appropriate doi as soon as I got them.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/geo2019-0251.1 is OK
- 10.1093/gji/ggaa009 is OK
- 10.1051/m2an/2019009 is OK
- 10.1088/1361-6420/ab3507 is OK
- 10.1051/m2an/2019088 is OK
- 10.1016/j.jcp.2018.05.011 is OK
- 10.1137/15M1043856 is OK
- 10.1190/segam2016-13961828.1 is OK
- 10.1190/geo2019-0527.1 is OK
- 10.1016/j.cma.2020.113406 is OK
- 10.1137/S0036142901384162 is OK
- 10.1137/070706616 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1007/b98874 is OK
- 10.1190/1.3238367 is OK
- 10.1142/7486 is OK
- 10.1046/j.1365-246X.1998.00498.x is OK
- 10.1046/j.1365-246x.1999.00967.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by yangbai90** [comment]
@flofaucher : Great, now everything is ready. It can be published soon!

**Comment by chennachaos** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02699/joss.02699/10.21105.joss.02699.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02699/joss.02699/10.21105.joss.02699.pdf) :page_facing_up: :point_left:

**Comment by chennachaos** [comment]
Hi @flofaucher. Please update the bibliography section of the paper. Update the paper in CMAME with the volume and page numbers, and remove the references that are not yet online in any form.

**Comment by chennachaos** [comment]
Hi @flofaucher. I have the following comments on the **Documentation** section.

1) Automated tests are missing. I suggest adding two automated tests.
2) Include information about contributing to the software, reporting bugs and seeking support.
3) Add equations for the visco-acoustic and visco-elastic problems.
4) Add a section on HDG, explaining briefly what HDG is, followed by a list of references on HDG. This will be useful for users who are not familiar with HDG.
5) Briefly discuss the current limitations of the methodology and the software so the users are aware of them before using the software.
6) Change mpi to MPI in every place it occurs.
7) Tutorial page: change "waves peed" to "wave speed". It is understandable that some typos always escape our attention. I suggest running the documentation through a spell and grammar checker once to identify and correct any potential typos.

I will check the installation and functionality parts once the above-listed issues are addressed.

**Comment by flofaucher** [comment]
Hello @chennachaos 
Thanks for your comments. Just to clarify, the modifications you suggest are for the Documentation section in the website right? 
Or should I also update the JOOS preprint?  (for instance, the details on HDG and the equations were in the first version of the preprint that I had to shorten). 

Otherwise, I agree with all of your comments and I am going to update once I am sure it is the right place.
Many thanks,

**Comment by chennachaos** [comment]
Hi @flofaucher.
Yes. My first comment on references is for the JOSS paper only. Apart from the bibliography, the rest of the paper is fine. No need to add any equations to the paper.

All the modifications in my second comment are for the documentation section of the website. For the tests, you need to add the files to the repository, preferably as a separate folder. The steps to compile and run the tests should go into the installation part of the documentation (website).

**Comment by flofaucher** [comment]
Hi @chennachaos ,
 
I have updated the repository and website with the appropriate corrections, in particular,   
- Automated tests have been added in the repository, using the GitLab CI formalism and the dedicated folder for experiments. These automated tests can be checked in the GitLab pipelines now.   
- The documentation section has been updated with       
  - the equations for attenuation. Because there are many models, the main one is given and then, references are provided for more information.
  - information on the HDG discretization to illustrate the main specificities, and limitations at the beginning of the page.  
- Information regarding the installation is given on the dedicated page, with first a version to use the default Linux repositories, and then more details for custom installation.  
- Tutorial instructions for initial testings are detailed in the dedicated page as well.  
- The About section has been updated to indicate contact information.
- I have corrected several typos (including 'MPI') everywhere.

Please let me know if it clarifies your questions or if you suggest other modifications. 

Regarding the references in the Joss paper, I am waiting a bit as I expect to obtain the appropriate doi in the next few days. Nonetheless, I will modify it accordingly if I do not get them in time.

Many thanks,

**Comment by meg-simula** [comment]
@chennachaos @yangbai90 @flofaucher Just checking in - looks like there is good progress - thanks for all of your efforts!

**Comment by chennachaos** [comment]
Hi @flofaucher.
Thank you for your updates. All the updates are to a satisfactory level.

I have checked the installation as well. It went smoothly. I also tested the code with the acoustic benchmark example in the tutorial section. The simulation ran successfully. The library is impressive. I would certainly recommend it to anybody working on wave propagation problems. I have the following minor issues that need to be addressed before I make my final recommendation.
1.) For the contour plots in the tutorial section, add the color bar legend so that it will be easy for the user to compare the results.
2.) Finalise the paper with the latest available details for the refernces.

**Comment by flofaucher** [comment]
Hi @chennachaos,
Thank you for your comments and positive feedback.
I have done the changes: 
 - color bars have been added in all of the pictures oft the Tutorial section
 - I have updated the bibliography of the paper, in particular removing the ones that are not yet online. 
I cc @meg-simula, please let me know if there is anything I can do now.

**Comment by chennachaos** [comment]
Hi @meg-simula. 
@flofaucher has responded promptly and addressed all the concerns. I am happy with the current state of the library. I recommend **hawen** for publication in the JOSS.

Thank you for opportunity!

**Comment by meg-simula** [comment]
Great, thanks @chennachaos and @yangbai90 for your prompt and constructive reviews and @flofaucher for addressing all the concerns. I will give it a final readthrough and follow-up from here.

**Comment by meg-simula** [comment]
@whedon generate pdf

**Comment by meg-simula** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/geo2019-0251.1 is OK
- 10.1093/gji/ggaa009 is OK
- 10.1051/m2an/2019009 is OK
- 10.1088/1361-6420/ab3507 is OK
- 10.1051/m2an/2019088 is OK
- 10.1016/j.jcp.2018.05.011 is OK
- 10.1137/15M1043856 is OK
- 10.1190/segam2016-13961828.1 is OK
- 10.1190/geo2019-0527.1 is OK
- 10.1016/j.cma.2020.113406 is OK
- 10.1190/geo2020-0305.1 is OK
- 10.1137/20M1336709 is OK
- 10.1137/S0036142901384162 is OK
- 10.1137/070706616 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1007/b98874 is OK
- 10.1190/1.3238367 is OK
- 10.1142/7486 is OK
- 10.1046/j.1365-246X.1998.00498.x is OK
- 10.1046/j.1365-246x.1999.00967.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02699/joss.02699/10.21105.joss.02699.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02699/joss.02699/10.21105.joss.02699.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
@flofaucher Thanks for your patience here - this looks great! 

At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by flofaucher** [comment]
@meg-simula  Thank you, I am going to prepare the tagged version but I have a quick question before: 
Can it use the current version, or should it still be the one from last months 
(the current version does not have any added or removed functionality, only a few corrections to speedup operations).

**Comment by meg-simula** [comment]
Use the current version.

**Comment by flofaucher** [comment]
@meg-simula, I just created the tagged version and archived the version onto the repository phaidra (of Vienna University). It is available here: https://phaidra.univie.ac.at/o:1144094 and the handle doi is 11353/10.1144094
I am not sure if I have to indicate this information somewhere in an updated version of the paper now?
Thanks!

**Comment by meg-simula** [comment]
@whedon set 11353/10.1144094 as archive

**Comment by whedon** [comment]
11353/10.1144094 doesn't look like an archive DOI.

**Comment by meg-simula** [comment]
@flofaucher Great, thanks! Could you confirm that the version is v1?

**Comment by meg-simula** [comment]
@openjournals/jose-eics This paper is ready for your attention. 

Could you also advise on how to set the archive doi using whedon (cf. the above)? Aside from the archive and version setting, should be ready for whedon accept.

**Comment by flofaucher** [comment]
@meg-simula Yes the version is 1.0.0.
I can ask phaidra for support regarding the doi too if you need to.

**Comment by meg-simula** [comment]
@whedon set 1.0.0 as version

**Comment by kthyng** [comment]
@meg-simula @openjournals/dev I see that the DOI "11353/10.1144094" does link appropriately to what looks like a DOI with "doi.org/11353/10.1144094" so looks fine. How can we convince whedon of this, or skip over whedon to get it in the system appropriately?

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02699/joss.02699/10.21105.joss.02699.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02699/joss.02699/10.21105.joss.02699.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/geo2019-0251.1 is OK
- 10.1093/gji/ggaa009 is OK
- 10.1051/m2an/2019009 is OK
- 10.1088/1361-6420/ab3507 is OK
- 10.1051/m2an/2019088 is OK
- 10.1016/j.jcp.2018.05.011 is OK
- 10.1137/15M1043856 is OK
- 10.1190/segam2016-13961828.1 is OK
- 10.1190/geo2019-0527.1 is OK
- 10.1016/j.cma.2020.113406 is OK
- 10.1190/geo2020-0305.1 is OK
- 10.1137/20M1336709 is OK
- 10.1137/S0036142901384162 is OK
- 10.1137/070706616 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1007/b98874 is OK
- 10.1190/1.3238367 is OK
- 10.1142/7486 is OK
- 10.1046/j.1365-246X.1998.00498.x is OK
- 10.1046/j.1365-246x.1999.00967.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@flofaucher Ok your paper looks good! Let's wait to hear back about the DOI issue above. And it looks like your software version has been set.

**Comment by danielskatz** [comment]
👋 @openjournals/dev - please note that there's a DOI issue here to be solved by you...

The DOI for the archived software is https://doi.org/11353/10.1144094
but ```@whedon set 11353/10.1144094 as archive``` is not processed by whedon.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2045

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2045, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1190/geo2019-0251.1 is OK
- 10.1093/gji/ggaa009 is OK
- 10.1051/m2an/2019009 is OK
- 10.1088/1361-6420/ab3507 is OK
- 10.1051/m2an/2019088 is OK
- 10.1016/j.jcp.2018.05.011 is OK
- 10.1137/15M1043856 is OK
- 10.1190/segam2016-13961828.1 is OK
- 10.1190/geo2019-0527.1 is OK
- 10.1016/j.cma.2020.113406 is OK
- 10.1190/geo2020-0305.1 is OK
- 10.1137/20M1336709 is OK
- 10.1137/S0036142901384162 is OK
- 10.1137/070706616 is OK
- 10.1007/s10915-011-9501-7 is OK
- 10.1137/S0895479899358194 is OK
- 10.1016/j.parco.2005.07.004 is OK
- 10.1007/b98874 is OK
- 10.1190/1.3238367 is OK
- 10.1142/7486 is OK
- 10.1046/j.1365-246X.1998.00498.x is OK
- 10.1046/j.1365-246x.1999.00967.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1353388783824236546) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2046
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02699](https://doi.org/10.21105/joss.02699)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @flofaucher (Florian Faucher)!!

And thanks to @chennachaos and @yangbai90 for reviewing, and @meg-simula for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02699/status.svg)](https://doi.org/10.21105/joss.02699)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02699">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02699/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02699/status.svg
   :target: https://doi.org/10.21105/joss.02699
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02699/status.svg)](https://doi.org/10.21105/joss.02699)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
