### ISSUE TITLE
Submission: sourmash: a library for MinHash sketching of DNA

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#27]
**Submitting author:** @ctb (<a href="http://orcid.org/0000-0001-6001-2677">C. Titus Brown</a>)
**Repository:** <a href="https://github.com/dib-lab/sourmash/" target ="_blank">https://github.com/dib-lab/sourmash/</a>
**Version:** 1.0
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.153989" target="_blank">10.5281/zenodo.153989</a>

## Status

[![status](http://joss.theoj.org/papers/3d793c6e7db683bee7c03377a4a7f3c9/status.svg)](http://joss.theoj.org/papers/3d793c6e7db683bee7c03377a4a7f3c9)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3d793c6e7db683bee7c03377a4a7f3c9"><img src="http://joss.theoj.org/papers/3d793c6e7db683bee7c03377a4a7f3c9/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3d793c6e7db683bee7c03377a4a7f3c9/status.svg)](http://joss.theoj.org/papers/3d793c6e7db683bee7c03377a4a7f3c9)
```

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dib-lab/sourmash/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.9.2)?
- [x] **Archive:** Does the <a target="_blank" href="https://zenodo.org/badge/latestdoi/22555/dib-lab/sourmash">software archive</a> resolve?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00027.pdf](https://github.com/openjournals/joss-reviews/files/310599/10.21105.joss.00027.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by jkahn** [comment]
:hand: I am reviewing this submission.  I should have a review by end of week; likely sooner.

**Comment by ctb** [comment]
Hi @jkahn thx - note that I just updated master with a bug fix (and a test for the bug :) for a bug discovered yesterday.

**Comment by jkahn** [comment]
I am not a copyright lawyer, but I don't think the text given in the release is exactly what [the BSD 3-clause](https://opensource.org/licenses/BSD-3-Clause) would say. For one thing, the Regents of the U of C *and* the MSU are mentioned the `LICENSE` file, but only the RofUofC in the header.  (I understand that @ctb has probably moved from one to the other, looking at @dib-lab .

**Comment by jkahn** [comment]
updated the checklist so that there are unchecked boxes corresponding to the open questions.

**Comment by ctb** [comment]
Hi @jkahn Thanks for all your comments - many excellent improvements resulted. I think this is ready for review once again!

**Comment by ctb** [comment]
Note, the latest version is 0.9.4, https://github.com/dib-lab/sourmash/releases/tag/v0.9.4, and zenodo etc should be updated soon

**Comment by jkahn** [comment]
Pending these two concerns (both resolved by a little bit more attention to onboarding new developers), I'm satisfied that my concerns have been addressed and recommend the package re-mint and be accepted.

I want to address my one continuing gripe: I don't love that [the test code is mixed in (closed, wontfix)](https://github.com/dib-lab/sourmash/issues/19) among the shipped code (in a public-facing library, this could open an entirely new attack surface) but I don't think it's a release-blocking offense, especially in a research package.

**Comment by arfon** [comment]
> Pending these two concerns (both resolved by a little bit more attention to onboarding new developers), I'm satisfied that my concerns have been addressed and recommend the package re-mint and be accepted.

👍 thanks @jkahn. @ctb - please let me know when you've made these changes.

**Comment by ctb** [comment]
OK, I've made the changes and @luizirber has checked them twice :).

Am I correct in thinking that I should proceed by cutting a new release (v1.0) and then putting the zenodo link in here? That's it, yes? (Reading [author guidelines](http://joss.theoj.org/about#author_guidelines))

**Comment by arfon** [comment]
> Am I correct in thinking that I should proceed by cutting a new release (v1.0) and then putting the zenodo link in here? That's it, yes? (Reading author guidelines)

👍 yes please @ctb

**Comment by jkahn** [comment]
sgtm! congratulations!

**Comment by ctb** [comment]
[sourmash 1.0](https://github.com/dib-lab/sourmash/releases/tag/v1.0) now up! [![DOI](https://zenodo.org/badge/55858065.svg)](https://zenodo.org/badge/latestdoi/55858065)

**Comment by ctb** [comment]
thanks for all your hard work @jkahn!

**Comment by arfon** [comment]
Many thanks again for the review @jkahn!

@ctb your paper is now accepted in JOSS. Your DOI is http://dx.doi.org/10.21105/joss.00027 🎉 🚀 💥
