### ISSUE TITLE
[PRE REVIEW]: khmer release v2.1: software for biological sequence analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#270]
**Submitting author:** @standage (<a href="http://orcid.org/0000-0003-0342-8531">Daniel S. Standage</a>)
**Repository:** <a href="https://github.com/dib-lab/khmer" target ="_blank">https://github.com/dib-lab/khmer</a>
**Version:** v2.1
**Editor:** @biorelated
**Reviewer:** @sjackman 

**Author instructions**

Thanks for submitting your paper to JOSS @standage. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@standage if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @biorelated it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @biorelated - would you be willing to edit this submission for JOSS?

**Comment by standage** [comment]
Both @macmanes and @sjackman have been users of khmer (at some point, at least). It appears that neither has reviewed for JOSS before, but were they available they would be able to provide informed reviews for this submission.

**Comment by sjackman** [comment]
I can review khmer 2.1.

**Comment by biorelated** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by biorelated** [comment]
@whedon assign @sjackman  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sjackman

**Comment by biorelated** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/272. Feel free to close this issue now!
