### ISSUE TITLE
[PRE REVIEW]: EllipSect: A Python tool for surface brightness analysis for GALFIT

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2701]
**Submitting author:** @canorve (<a href="http://orcid.org/0000-0002-3721-8869">Christopher Anorve</a>)
**Repository:** <a href="https://github.com/canorve/EllipSect" target ="_blank">https://github.com/canorve/EllipSect</a>
**Version:**  v1.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @canorve. **Currently, there isn't an JOSS editor assigned** to your paper.

@canorve if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1086/340952 is OK
- 10.1093/mnras/226.4.747 is OK
- 10.1046/j.1365-8711.2002.05412.x is OK
- 10.1088/0004-6256/138/5/1417 is OK
- 10.1086/503539 is OK
- 10.1093/mnras/sts633 is OK
- 10.1111/j.1365-2966.2012.20619.x is OK
- 10.1111/j.1365-2966.2010.17426.x is OK

MISSING DOIs

- 10.1109/tac.1974.1100705 may be a valid DOI for title: A New Look at the Statistical Model Identification

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02701/joss.02701/10.21105.joss.02701.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02701/joss.02701/10.21105.joss.02701.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.13 s (29.9 files/s, 33399.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1           1255            368           2124
Markdown                         2            168              0            342
TeX                              1             13              0            200
-------------------------------------------------------------------------------
SUM:                             4           1436            368           2666
-------------------------------------------------------------------------------


Statistical information for the repository '2701' was gathered on 2020/09/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christopher Añorve             136         37114          33367          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Christopher Añorve         3747           10.1          5.6                9.79
```

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@canorve - many thanks for your submission to JOSS. Before proceeding to assign and editor I'm going to check with a few other editors on the scope of this submission. This will likely take a week so sit tight for now :-)

**Comment by Kevin-Mattheus-Moerman** [comment]
@canorve after a scope review by the editorial board it was decided that although this work looks useful and is research software, it is, in its current form, not in scope for JOSS. In particular the single functionality and single script implementation is not deemed acceptable for JOSS (some recommended aspects of this this work could perhaps instead be merged with astropy or photoutils). 

At this point we will proceed to reject this submission. We would welcome a re-submission if functionality is expanded, if the single script mode is avoided, and if automated tests are added. 

Note that you may want to explore other venues to publish this work or to enable users to cite this work. For instance archiving a release on ZENODO enables users to cite the archive DOI. 

All the best, 

Kevin Moerman
_AEiC JOSS_

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by canorve** [comment]
Dear Kevin,  

Thanks for your comments, 

Although you are right about the single script implementation, the software is **not** single functionality, and this is explained in the "Different modes" section as well as in the Github's page. The code's goal is to extract as much information as possible. However, I think I should have emphasized it in the paper. 


All the best,
