### ISSUE TITLE
[PRE REVIEW]: Geoserver-rest: A python package for geospatial data management in geoserver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2702]
**Submitting author:** @iamtekson (<a href="http://orcid.org/0000-0001-9275-5619">Tek Kshetri</a>)
**Repository:** <a href="https://github.com/gicait/geoserver-rest" target ="_blank">https://github.com/gicait/geoserver-rest</a>
**Version:** v1.1.3
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @iamtekson. **Currently, there isn't an JOSS editor assigned** to your paper.

@iamtekson if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (266.4 files/s, 33545.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           7            149            310            630
Scheme                           4              8              0            364
Markdown                         3             79              0            210
TeX                              1             16              0            123
-------------------------------------------------------------------------------
SUM:                            15            252            310           1327
-------------------------------------------------------------------------------


Statistical information for the repository '2702' was gathered on 2020/09/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
iamtekson                       30          2377           1288          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
iamtekson                  1089           45.8          0.2                6.52
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/3311790.3396647 is OK

MISSING DOIs

- 10.1007/springerreference_62098 may be a valid DOI for title: gdal

INVALID DOIs

- https://doi.org/10.1007/978-0-387-34905-3_15 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.25607/OBP-647 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02702/joss.02702/10.21105.joss.02702.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02702/joss.02702/10.21105.joss.02702.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@iamtekson - many thanks for your submission to JOSS. I'm flagging this submission as potentially out of scope for JOSS due to its size and that it looks like a small API wrapper (which are out of scope for us).

In the meantime, feel free to work on your BibTeX files which @whedon has some suggestions for above.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by iamtekson** [comment]
@arfon Thank you for the quick response. It is an open-source geospatial data management project. It can do all the fundamental requirement for geoserver data management. This project seems small in size but it has a wider scope for automation of web-GIS development. 

Yes, sure. I will correct the suggestions from @whedon.

According to @whedon report also, it has 1000+ LOC. I hope it meets the requirement of the paper submission. Please consider to publish it. Thank you in advance.

**Comment by arfon** [comment]
> According to @whedon report also, it has 1000+ LOC. I hope it meets the requirement of the paper submission. Please consider to publish it. Thank you in advance.

Just an FYI, the LOC count is mostly a guideline to help us identify submissions on the smaller side. Passing this threshold does not guarantee that a submission is in scope.

**Comment by iamtekson** [comment]
@arfon Thank you for taking the time to communicate with me. One more thing I just want to mention that, It is a rest API for geoserver but not just a wrapper. because the library supports the dynamic styling for raster as well as vector data. It can read the raster files and get the pixel values. Based on the raster pixel value, it can generate the style file (SLD) and for vector layer, We need to assign the column name and the column values based on which the style file can be generated. The library can be very useful for automation of the process mainly in GIS application development without geoserver GUI. I think the package is complete for the automation of geospatial data sharing and management. 

Thank you once again and please guide me for the publication.

**Comment by iamtekson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02702/joss.02702/10.21105.joss.02702.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02702/joss.02702/10.21105.joss.02702.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
Thanks for the extra information. The next step is for our editorial team to give their input on this submission and whether we believe it's in scope. This will likely take up to a week so there's no action required on your part now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@iamtekson thank you for this submission. We regret to inform you that after editorial review this work was found to be out of scope for JOSS. In particular this work was seen as too minor to warrant publication in JOSS (see our notes on [required amount of scholarly content](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)). This conclusion does not mean the software is of a poor quality or not useful, it merely means it is not in scope in its current form. 

We will now proceed to reject this submission. We do hope you will consider JOSS for future more extensive work or a re-submission of a significantly expanded version of this work. 

Note you may want to consider other venues to publish your work or enable citation. For instance archiving a release on ZENODO enables users to cite a DOI for your work. 

All the best, 

Kevin Moerman
_AEiC JOSS_

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
