### ISSUE TITLE
[REVIEW]: DeepReg: a deep learning toolkit for medical image registration

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2705]
**Submitting author:** @mathpluscode (<a href="http://orcid.org/0000-0002-1184-7421">Yunguan Fu</a>)
**Repository:** <a href="https://github.com/DeepRegNet/DeepReg" target ="_blank">https://github.com/DeepRegNet/DeepReg</a>
**Version:** v0.1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @ethanwharris, @lbrea, @zhangfanmark
**Archive:** <a href="https://doi.org/10.5281/zenodo.4210215" target="_blank">10.5281/zenodo.4210215</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/7e6de472bc82a70d7618e23f618960b3/status.svg)](https://joss.theoj.org/papers/7e6de472bc82a70d7618e23f618960b3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7e6de472bc82a70d7618e23f618960b3"><img src="https://joss.theoj.org/papers/7e6de472bc82a70d7618e23f618960b3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7e6de472bc82a70d7618e23f618960b3/status.svg)](https://joss.theoj.org/papers/7e6de472bc82a70d7618e23f618960b3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/DeepRegNet/DeepReg" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ethanwharris & @lbrea & @zhangfanmark, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/DeepRegNet/DeepReg">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mathpluscode) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/DeepRegNet/DeepReg">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mathpluscode) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/DeepRegNet/DeepReg">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mathpluscode) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ethanwharris, @lbrea, @zhangfanmark it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-030-32245-8_45 is OK
- 10.1016/j.media.2018.07.002 is OK
- 10.1109/ISBI.2018.8363756 is OK
- 10.1016/j.media.2018.11.010 is OK
- 10.1109/TMI.2019.2897538 is OK
- 10.1016/j.media.2019.07.006 is OK
- 10.1016/j.cmpb.2018.01.025 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1016/j.neuroimage.2007.07.007 is OK
- 10.1016/j.neuroimage.2008.10.040 is OK
- 10.1088/0031-9155/46/3/201 is OK
- 10.1007/s00138-020-01066-5 is OK
- 10.1088/1361-6560/ab843e is OK
- 10.1007/978-3-658-29267-6_53 is OK
- 10.1109/42.796284 is OK
- 10.5281/zenodo.3835682 is OK
- 10.1002/mp.12268 is OK
- 10.5281/zenodo.3715652 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02705/joss.02705/10.21105.joss.02705.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02705/joss.02705/10.21105.joss.02705.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@ethanwharris, @lbrea, @zhangfanmark, this is where the review takes place. There are instructions, and a set of checkboxes for each of you at the top of this issue which will guide you through the process. We would appreciate it if you could complete the review within about 2-3 weeks. Please let me know if you have any questions. 

Let the reviewing begin! :tada:

**Comment by Kevin-Mattheus-Moerman** [comment]
@lbrea, @zhangfanmark, could you please consider updating your GitHub profile with your full name, and preferably a link to a professional (e.g. university) profile, ORCID, or equivalent.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ethanwharris, @lbrea, @zhangfanmark, this is where the review takes place. I hope you are able to get started if you haven't already. Let me know if you have questions.

**Comment by mathpluscode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02705/joss.02705/10.21105.joss.02705.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02705/joss.02705/10.21105.joss.02705.pdf) :page_facing_up: :point_left:

**Comment by mathpluscode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-030-32245-8_45 is OK
- 10.1016/j.media.2018.07.002 is OK
- 10.1109/ISBI.2018.8363756 is OK
- 10.1016/j.media.2018.11.010 is OK
- 10.1109/TMI.2019.2897538 is OK
- 10.1016/j.media.2019.07.006 is OK
- 10.1016/j.cmpb.2018.01.025 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1016/j.neuroimage.2007.07.007 is OK
- 10.1016/j.neuroimage.2008.10.040 is OK
- 10.1088/0031-9155/46/3/201 is OK
- 10.1007/s00138-020-01066-5 is OK
- 10.1088/1361-6560/ab843e is OK
- 10.1007/978-3-658-29267-6_53 is OK
- 10.1109/42.796284 is OK
- 10.5281/zenodo.3835682 is OK
- 10.1002/mp.12268 is OK
- 10.5281/zenodo.3715652 is OK
- 10.1016/j.cmpb.2009.09.002 is OK
- 10.1109/CVPRW.2016.78 is OK

MISSING DOIs

- 10.1007/978-3-030-59716-0_24 may be a valid DOI for title: Longitudinal Image Registration with Temporal-order and Subject-specificity Discrimination
- 10.1007/978-3-030-59716-0_15 may be a valid DOI for title: MvMM-RegNet: A new image registration framework based on multivariate mixture model and neural network estimation

INVALID DOIs

- None
```

**Comment by mathpluscode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-030-32245-8_45 is OK
- 10.1016/j.media.2018.07.002 is OK
- 10.1109/ISBI.2018.8363756 is OK
- 10.1016/j.media.2018.11.010 is OK
- 10.1109/TMI.2019.2897538 is OK
- 10.1016/j.media.2019.07.006 is OK
- 10.1007/978-3-030-59716-0_24 is OK
- 10.1016/j.cmpb.2018.01.025 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1016/j.neuroimage.2007.07.007 is OK
- 10.1016/j.neuroimage.2008.10.040 is OK
- 10.1088/0031-9155/46/3/201 is OK
- 10.1007/s00138-020-01066-5 is OK
- 10.1088/1361-6560/ab843e is OK
- 10.1007/978-3-030-59716-0_15 is OK
- 10.1007/978-3-658-29267-6_53 is OK
- 10.1109/42.796284 is OK
- 10.5281/zenodo.3835682 is OK
- 10.1002/mp.12268 is OK
- 10.5281/zenodo.3715652 is OK
- 10.1016/j.cmpb.2009.09.002 is OK
- 10.1109/CVPRW.2016.78 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ethanwharris** [comment]
@Kevin-Mattheus-Moerman I have now finished my review. The authors have responded to my breif comments on the paper and the code base / documentation is in good shape (installation works and the demos run as expected etc.) so I recommend acceptance :smiley:

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for your help @ethanwharris !

**Comment by Kevin-Mattheus-Moerman** [comment]
@lbrea, @zhangfanmark thanks again for agreeing to review this work. Can you let me know if you have started and when you expect to complete this review? Let me know if you have questions.

**Comment by lbrea** [comment]
Hi, sorry for the late reply. I am now working now on the review, and I
expect to complete it by Monday 26 at the latest.

**Comment by zhangfanmark** [comment]
Sorry for the delay. I will perform the review and get it back early next week.

**Comment by zhangfanmark** [comment]
Above are my comments to DeepReg. Thanks.

**Comment by lbrea** [comment]
@Kevin-Mattheus-Moerman I've finished my review (see further comments above). The package looks great to me, and I would recommend acceptance.

**Comment by mathpluscode** [comment]
Hi @zhangfanmark @lbrea, thank you so much for your reviews. We've addressed all the mentioned issues and please feel free to try again ;)

**Comment by mathpluscode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02705/joss.02705/10.21105.joss.02705.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02705/joss.02705/10.21105.joss.02705.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@ethanwharris, @zhangfanmark looks like you've ticked all boxes above. Can you review the latest changes and/or confirm you are happy to recommend acceptance of this work?

**Comment by zhangfanmark** [comment]
Hi @Kevin-Mattheus-Moerman , the code and the paper look good to me. I recommend acceptance of the work. Thank you!

**Comment by ethanwharris** [comment]
Hi @Kevin-Mattheus-Moerman , all looks good to me, happy to recommend acceptance :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-030-32245-8_45 is OK
- 10.1016/j.media.2018.07.002 is OK
- 10.1109/ISBI.2018.8363756 is OK
- 10.1016/j.media.2018.11.010 is OK
- 10.1109/TMI.2019.2897538 is OK
- 10.1016/j.media.2019.07.006 is OK
- 10.1007/978-3-030-59716-0_24 is OK
- 10.1016/j.cmpb.2018.01.025 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1016/j.neuroimage.2007.07.007 is OK
- 10.1016/j.neuroimage.2008.10.040 is OK
- 10.1088/0031-9155/46/3/201 is OK
- 10.1007/s00138-020-01066-5 is OK
- 10.1088/1361-6560/ab843e is OK
- 10.1007/978-3-030-59716-0_15 is OK
- 10.1007/978-3-658-29267-6_53 is OK
- 10.1109/42.796284 is OK
- 10.5281/zenodo.3835682 is OK
- 10.1002/mp.12268 is OK
- 10.5281/zenodo.3715652 is OK
- 10.1016/j.cmpb.2009.09.002 is OK
- 10.1109/CVPRW.2016.78 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@mathpluscode this looks like it is ready to process for acceptance. At this point can you do the following: 

- [ ] Can you archive a copy of the reviewed software on Zenodo and report back here with the DOI? (some find this approach useful: https://guides.github.com/activities/citable-code/). 

- [ ] Please check that the Zenodo archive metadata like the **title**, **authors**, and **version** matches that of the paper. You may need to ammend/edit this information manually. 

- [ ] Can you confirm if `v0.1.0` is the most appropriate version tag for this work, or has the version moved on? 

Thanks

**Comment by mathpluscode** [comment]
> @mathpluscode this looks like it is ready to process for acceptance. At this point can you do the following:
> 
> * [ ]  Can you archive a copy of the reviewed software on Zenodo and report back here with the DOI? (some find this approach useful: https://guides.github.com/activities/citable-code/).
> * [ ]  Please check that the Zenodo archive metadata like the **title**, **authors**, and **version** matches that of the paper. You may need to ammend/edit this information manually.
> * [ ]  Can you confirm if `v0.1.0` is the most appropriate version tag for this work, or has the version moved on?
> 
> Thanks

Hi @Kevin-Mattheus-Moerman,
- Here is the archive of DeepReg `v0.1.0` [![DOI](https://zenodo.org/badge/269365590.svg)](https://zenodo.org/badge/latestdoi/269365590)
- Yes we've corrected the title, authors and version
- Yes we confirm `v0.1.0` is the correct version tag.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.4210215 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4210215" target="_blank">10.5281/zenodo.4210215</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-030-32245-8_45 is OK
- 10.1016/j.media.2018.07.002 is OK
- 10.1109/ISBI.2018.8363756 is OK
- 10.1016/j.media.2018.11.010 is OK
- 10.1109/TMI.2019.2897538 is OK
- 10.1016/j.media.2019.07.006 is OK
- 10.1007/978-3-030-59716-0_24 is OK
- 10.1016/j.cmpb.2018.01.025 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1016/j.neuroimage.2007.07.007 is OK
- 10.1016/j.neuroimage.2008.10.040 is OK
- 10.1088/0031-9155/46/3/201 is OK
- 10.1007/s00138-020-01066-5 is OK
- 10.1088/1361-6560/ab843e is OK
- 10.1007/978-3-030-59716-0_15 is OK
- 10.1007/978-3-658-29267-6_53 is OK
- 10.1109/42.796284 is OK
- 10.5281/zenodo.3835682 is OK
- 10.1002/mp.12268 is OK
- 10.5281/zenodo.3715652 is OK
- 10.1016/j.cmpb.2009.09.002 is OK
- 10.1109/CVPRW.2016.78 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1892

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1892, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1324102924801363971) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1893
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02705](https://doi.org/10.21105/joss.02705)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by mathpluscode** [comment]
Hi, @Kevin-Mattheus-Moerman @ethanwharris @zhangfanmark @lbrea, thank you a lot for the edit and review!

**Comment by YipengHu** [comment]
> Hi, @Kevin-Mattheus-Moerman @ethanwharris @zhangfanmark @lbrea, thank you a lot for the edit and review!

Great editorial service - will recommend to colleagues 👍

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02705/status.svg)](https://doi.org/10.21105/joss.02705)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02705">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02705/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02705/status.svg
   :target: https://doi.org/10.21105/joss.02705
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02705/status.svg)](https://doi.org/10.21105/joss.02705)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
