### ISSUE TITLE
[REVIEW]: c212: An R Package for the Detection of Safety Signals in Clinical Trials Using Body-Systems (System Organ Classes)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2706]
**Submitting author:** @rcarragh (<a href="http://orcid.org/0000-0002-0120-625X">Raymond Bernard Carragher</a>)
**Repository:** <a href="https://github.com/rcarragh/c212" target ="_blank">https://github.com/rcarragh/c212</a>
**Version:** 1.00
**Editor:** @csoneson
**Reviewers:** @rrrlw, @MelvinSMunsaka
**Archive:** <a href="https://doi.org/10.5281/zenodo.4304831" target="_blank">10.5281/zenodo.4304831</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4b7357f98bc7ac39777a7229ec30f108/status.svg)](https://joss.theoj.org/papers/4b7357f98bc7ac39777a7229ec30f108)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4b7357f98bc7ac39777a7229ec30f108"><img src="https://joss.theoj.org/papers/4b7357f98bc7ac39777a7229ec30f108/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4b7357f98bc7ac39777a7229ec30f108/status.svg)](https://joss.theoj.org/papers/4b7357f98bc7ac39777a7229ec30f108)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/rcarragh/c212" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rrrlw & @emilydolson, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rcarragh/c212">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rcarragh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rcarragh/c212">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@rcarragh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rcarragh/c212">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rcarragh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rrrlw, @emilydolson it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
Ok @rrrlw, @emilydolson - this is where the review will take place. Please find your respective checklists above together with some more instructions, and don't hesitate to ping me if you have any questions.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.2517-6161.1995.tb02031.x is OK
- 10.1198/jasa.2010.tm09329 is OK
- 10.1002/sim.5310 is OK
- 10.1016/j.jspi.2007.06.006 is OK
- doi:10.1201/9781420011302.fmatt is OK
- 10.1111/j.0006-341X.2004.00186.x is OK
- 10.1080/10543406.2010.520181 is OK
- 10.1080/19466315.2017.1409134 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.5281/zenodo.3235282 is OK
- 10.1002/sim.8304 is OK
- 10.1002/sim.8495 is OK
- 10.1002/sim.8563 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
And just a note to  myself that we're still looking to add a reviewer directed more towards the clinical trials methodology.

**Comment by rrrlw** [comment]
N.B. The paper has two authors and the GitHub repo has one contributor. Will trust submitting author's judgment and assume that both authors had substantial contributions and that the author list in the paper is appropriate (checking box in list above).

**Comment by rcarragh** [comment]
I have made some changes to address issues raised above: rcarragh/c212#1, rcarragh/c212#2. rcarragh/c212#3, rcarragh/c212#4.

**Comment by csoneson** [comment]
👋 @emilydolson - could you update us on how your review is progressing?

**Comment by csoneson** [comment]
ping @emilydolson

> 👋 @emilydolson - could you update us on how your review is progressing?

**Comment by rcarragh** [comment]
@rrrlw - I've added a comment in rcarragh/c212#6 to address your question about state of the field. 
I didn't close the issue so if you want to add anything further of course please do, but if you are happy with the response then we can close it.

**Comment by csoneson** [comment]
@whedon add @MelvinSMunsaka as reviewer

**Comment by whedon** [comment]
OK, @MelvinSMunsaka is now a reviewer

**Comment by csoneson** [comment]
Hi all - I'm happy to say that we now have a third reviewer - apologies for the delay and thanks a lot @MelvinSMunsaka for accepting!

Melvin - your checklist is in the first post above, and you can leave comments here and/or open issues in the software repository. Don't hesitate to ping me if you have any questions.

**Comment by rrrlw** [comment]
@csoneson I have checked off all the boxes in my review. All my questions and concerns were appropriately addressed by @rcarragh in c212's GitHub repo. I should point out that although I am not qualified to review the Functionality (2nd bullet within the Functionality section), I have checked the box with the expectation that @MelvinSMunsaka will be better suited to evaluate it.

Thank you for your help, @csoneson, and thank you, @rcarragh, for this useful contribution.

**Comment by csoneson** [comment]
Thank you for your review @rrrlw!

**Comment by csoneson** [comment]
👋 @MelvinSMunsaka - I just wanted to check in to see that you have everything you need for the review, and that the practical aspects of the review process is clear. Don't hesitate to ping me if you have any questions. Thanks!

**Comment by csoneson** [comment]
@MelvinSMunsaka - could you give us an update on the status of your review?

**Comment by MelvinSMunsaka** [comment]
I will provide my review over the weekend…had some COVID-19 issues as result of getting into contact with cousin who is asymptomatic. 

 

Also, I was taking a closer look at the package, trying out some example and also double checking how we implemented the c212 package here: (https://visual-analytics.shinyapps.io/index/ - see the AE Line Plot tab).  

 

Melvin

**Comment by csoneson** [comment]
@MelvinSMunsaka - hope things are well. Could you update us on the status of your review? Thanks!

**Comment by csoneson** [comment]
Ping @MelvinSMunsaka 

> @MelvinSMunsaka - hope things are well. Could you update us on the status of your review? Thanks!

**Comment by MelvinSMunsaka** [comment]
For some reason, I am not able to add my comments via Github even after I logged into my account. 

Here are my few comments:

•	The articles should explain more/correctly about MedDRA and the SOC/PT in the sentence “A number of methods, which use groupings of adverse events by body-system or System Organ Class” as this is key/central to the methods presented, especially some of the Bayesian approaches.

•	The reference “Fries, M., Kracht, K., & Li, J. (2016). Safety monitoring methodology in the premarketing setting. Proceedings of JSM, 2247–2269. Retrieved from https://ww2.amstat.org/MembersOnly/proceedings/2016/data/assets/pdf/389675.pdf” is incorrect. It should be “Fries, M., Kracht, K. K., Li, J., Munsaka, M. S., Sanchez-Kam, M., Singh, K. P., Wang, W., Whalen, E., Zhou. K. (2016). Safety Monitoring Methodology in the Premarketing Setting JSM 2016 Proceedings, Biopharmaceutical Section, 2247 - 2269.  https://ww2.amstat.org/MembersOnly/proceedings/2016/data/assets/pdf/389675.pdf”   

•	I stress tested with data sets with a large number of AEs and in some cases the computations crawled to a halt, especially where using the Bayesian method. May want to mention this in the paper since in clinical trial settings the number of AEs can be very large especially in certain therapeutic areas or integrated data settings. As an FYI, we have  implemented the package here: https://visual-analytics.shinyapps.io/index/ (see AE Line Plot tab) as part of the via the ASA Biopharm Safety WG ongoing work.


•	In terms of the checklist above, everything checks out except for the performance issues noted above. I will complete the checklist once I can get it to work. It seems it is greyed out even when I tried changing the “watch” options.

**Comment by MelvinSMunsaka** [comment]
@csoneson - have some questions about greyed out check boxes.

**Comment by csoneson** [comment]
Thanks @MelvinSMunsaka! I will re-invite you to this issue - you have to accept the invitation in order to be able to check the boxes. Let me know if it still doesn't work.

**Comment by csoneson** [comment]
@whedon re-invite @MelvinSMunsaka as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@melvinsmunsaka please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by rcarragh** [comment]
@MelvinSMunsaka - thank you for your comments. I will create issues in the c212 github repository for them and respond/make changes accordingly for you to review.

**Comment by rcarragh** [comment]
@MelvinSMunsaka - your comments can be seen at the issues: rcarragh/c212#7, rcarragh/c212#8, rcarragh/c212#9
I will respond and let you know when I've done so.

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by rcarragh** [comment]
@MelvinSMunsaka, @csoneson - I have put some responses into the issues I created for the comments (rcarragh/c212#7, rcarragh/c212#8, rcarragh/c212#9)

Briefly the following changes have been made to the paper:
1) I have added a couple of paragraphs in the Summary section explaining medical dictionaries and the motivation for the methods
2) I've fixed the reference author issue
3) I've added a section regarding performance and memory requirements in the Software Details and Availability section to give some guidance.

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
@MelvinSMunsaka - are you able to check the boxes in the checklist after the re-invitation?

**Comment by MelvinSMunsaka** [comment]
@csoneson Yes, I just provided my responses.

**Comment by csoneson** [comment]
Thanks @MelvinSMunsaka! It seems that you agreed with @rcarragh's changes and that the issues created in response to your comments have been closed, and all the boxes in the checklist are checked. Just to make sure I'm not missing anything, could you just confirm whether you are happy with the state of the submission now, or whether there are things that you would still like to see addressed before it should be accepted? Thanks!

**Comment by MelvinSMunsaka** [comment]
@csoneson I am confirming that I am happy with the state of the submission now. @rcarragh addressed all my comments. Unless there are comments from other reviewers, I would accept the submission.

**Comment by csoneson** [comment]
Perfect, thank you! 

I have not been able to reach @emilydolson (here or via email), but given the careful reviews from @rrrlw and @MelvinSMunsaka I am happy to move on with that. @rcarragh - I will take a quick look through the submission as well and get back to you shortly.

**Comment by csoneson** [comment]
@whedon remove @emilydolson as reviewer

**Comment by whedon** [comment]
OK, @emilydolson is no longer a reviewer

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.2517-6161.1995.tb02031.x is OK
- 10.1198/jasa.2010.tm09329 is OK
- 10.1002/sim.5310 is OK
- 10.1016/j.jspi.2007.06.006 is OK
- doi:10.1201/9781420011302.fmatt is OK
- 10.1111/j.0006-341X.2004.00186.x is OK
- 10.1080/10543406.2010.520181 is OK
- 10.1080/19466315.2017.1409134 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.5281/zenodo.3235282 is OK
- 10.1002/sim.8304 is OK
- 10.1002/sim.8495 is OK
- 10.1002/sim.8563 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
👋 @rcarragh - I've made a PR [here](https://github.com/rcarragh/c212/pull/10) with a couple of small fixes to the bibliography, could you please check and merge?

**Comment by csoneson** [comment]
The next steps will then be:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check that the Zenodo archive has the correct metadata: the title and author list should match those of the paper; you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

**Comment by rcarragh** [comment]
@csoneson I've checked and merged the changes, thanks.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.2517-6161.1995.tb02031.x is OK
- 10.1198/jasa.2010.tm09329 is OK
- 10.1002/sim.5310 is OK
- 10.1016/j.jspi.2007.06.006 is OK
- doi:10.1201/9781420011302.fmatt is OK
- 10.1111/j.0006-341X.2004.00186.x is OK
- 10.1080/10543406.2010.520181 is OK
- 10.1080/19466315.2017.1409134 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.5281/zenodo.3235282 is OK
- 10.1002/sim.8304 is OK
- 10.1002/sim.8495 is OK
- 10.1002/sim.8563 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by rcarragh** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02706/joss.02706/10.21105.joss.02706.pdf) :page_facing_up: :point_left:

**Comment by rcarragh** [comment]
@csoneson - I've done the following:

Tagged release of software in github: 1.00
I have archived the corresponding software on Zenodo
The title and author on Zenodo match the paper; Co-author does not have an ORCID.
Zenodo archive DOI: 10.5281/zenodo.4304831

I hope this is correct, thanks.

**Comment by csoneson** [comment]
Thanks @rcarragh - could you just remove the initial `rcarragh/c212` from the Zenodo record title, so that it matches the paper title? The rest looks good.

**Comment by csoneson** [comment]
@whedon set 1.00 as version

**Comment by whedon** [comment]
OK. 1.00 is the version.

**Comment by rcarragh** [comment]
Hi @csoneson, 
I've removed the initial rcarragh/c212 from the Zenodo record title
Thanks

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.4304831 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4304831" target="_blank">10.5281/zenodo.4304831</a> is the archive.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by csoneson** [comment]
Thanks @rcarragh - the associate editor-in-chief on rotation will take over from here and finalize the acceptance of your submission.

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1958

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1958, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.2517-6161.1995.tb02031.x is OK
- 10.1198/jasa.2010.tm09329 is OK
- 10.1002/sim.5310 is OK
- 10.1016/j.jspi.2007.06.006 is OK
- doi:10.1201/9781420011302.fmatt is OK
- 10.1111/j.0006-341X.2004.00186.x is OK
- 10.1080/10543406.2010.520181 is OK
- 10.1080/19466315.2017.1409134 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.1007/978-981-10-7826-2_11 is OK
- 10.5281/zenodo.3235282 is OK
- 10.1002/sim.8304 is OK
- 10.1002/sim.8495 is OK
- 10.1002/sim.8563 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by rcarragh** [comment]
I would like to says thanks to @csoneson for organising the review process, and thanks to the reviewers, @rrrlw and @MelvinSMunsaka, for their helpful and insightful comments.  Doubly so given the current difficult working conditions many are facing.

**Comment by rcarragh** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @rcarragh, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by rcarragh** [comment]
I checked the proof and crossref in openjournals/joss-papers#1958 and they look good from my point of view.

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1334932878317195264) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1962
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02706](https://doi.org/10.21105/joss.02706)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @rcarragh on your article's publication in JOSS!

Many thanks to  @rrrlw and @MelvinSMunsaka for reviewing this, and @csoneson for editing it.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02706/status.svg)](https://doi.org/10.21105/joss.02706)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02706">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02706/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02706/status.svg
   :target: https://doi.org/10.21105/joss.02706
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02706/status.svg)](https://doi.org/10.21105/joss.02706)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
