### ISSUE TITLE
[PRE REVIEW]: distFit: An R package to investigate goodness-of-fit with statistical distributions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2707]
**Submitting author:** @pbeagon (<a href="http://orcid.org/0000-0002-6555-7550">Paul Beagon</a>)
**Repository:** <a href="https://github.com/pbeagon/distFit" target ="_blank">https://github.com/pbeagon/distFit</a>
**Version:** v0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pbeagon. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @mikldk.

@pbeagon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2707 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (195.3 files/s, 18715.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1             67              9            297
Markdown                         4             58              0            197
R                                5             24            162            114
TeX                              1             13              0            113
-------------------------------------------------------------------------------
SUM:                            11            162            171            721
-------------------------------------------------------------------------------


Statistical information for the repository '2707' was gathered on 2020/09/29.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.enbuild.2020.110244 is OK
- 10.1080/00224065.1998.11979858 is OK

MISSING DOIs

- 10.1049/ip-c.1986.0048 may be a valid DOI for title: Statistical electricity demand modelling from consumer billing data
- 10.1016/j.apenergy.2014.08.093 may be a valid DOI for title: Characterizing probability density distributions for household electricity load profiles from high-resolution electricity use data
- 10.1016/j.renene.2016.10.041 may be a valid DOI for title: Two and three-parameter Weibull distribution in available wind power analysis

INVALID DOIs

- None
```

**Comment by pbeagon** [comment]
Hi 

I just added the DOIs as separate items in the paper.bib file

Thanks 

Paul

**Comment by pbeagon** [comment]
> Failed to discover a valid open source license.
Hi 

I added the licence file again, but this time I ticked "add to master branch" and it now appears as a file at
https://github.com/pbeagon/distFit

Paul

**Comment by pbeagon** [comment]
> PDF failed to compile for issue #2707 with the following error:
> 
> Can't find any papers to compile :-(

PDF failed to compile for issue #2707 with the following error: 

 Can't find any papers to compile :-(

_Originally posted by @whedon in https://github.com/openjournals/joss-reviews/issues/2707#issuecomment-700571970_

Hello 

I already mentioned it at submission, but I uploaded the paper in PDF version in addition to R markdown and the markdown generated by R using Pandocs v 2.10.1. My attempts with other markdown editors did not render properly, so I returned to R markdown. 

hope this helps 

Paul

**Comment by pbeagon** [comment]
>  @pbeagon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this list of people have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

Hi Kevin, 

I looked through the linked spreadsheet and found a few reviewers with R expertise (preferred or other language) and also know the energy domain:

elimillera  R and energy
jordanperr R (other language) Energy systems
kramea  R Energy

I noticed Modelica as a reviewer's language. Does JOSS publish Modelica energy models also?

Thanks 

Paul Beagon
Paul Beagon

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (145.3 files/s, 13952.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1             67              9            297
Markdown                         4             58              0            197
TeX                              1             13              0            115
R                                5             24            162            114
-------------------------------------------------------------------------------
SUM:                            11            162            171            723
-------------------------------------------------------------------------------


Statistical information for the repository '2707' was gathered on 2020/09/29.
No commited files with the specified extensions were found.
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@pbeagon 

> I noticed Modelica as a reviewer's language. Does JOSS publish Modelica energy models also?

I am not familiar with Modelica but judging from a quick look at https://www.modelica.org it appears to be an open source language which would be in scope for JOSS. I am not sure what "energy models" are though. You can always submit and we can review suitability. If the work is open source, has sufficient scholarly content (not too minor), has a significant research application, and we are able to find reviewers (e.g. often true if if the language and the application are sufficiently common/of interest), then yes it is likely publishable in JOSS.

**Comment by pbeagon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02707/joss.02707/10.21105.joss.02707.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02707/joss.02707/10.21105.joss.02707.pdf) :page_facing_up: :point_left:

**Comment by pbeagon** [comment]
> PDF failed to compile for issue #2707 with the following error:
> 
> Can't find any papers to compile :-(
Hi

Using info at https://github.com/rstudio/rticles, now JOSS PDF renders both on my PC and by whedon as above.

Looks much better now. Thanks

Paul

**Comment by Kevin-Mattheus-Moerman** [comment]
@pbeagon thanks for your submission. Unfortunately the editorial board has determined this work is not in scope for JOSS. In particular it is deemed too minor in terms of its functionality (see [our guidelines)](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This conclusion does not mean the software is not useful or of a low quality, it merely means that in terms of required amount of scholarly content this work is out of scope for JOSS.

I will reject this submission at this point. However, if you continue to develop and expand this work, we would be happy to reconsider it as a re-submission in the future. Alternatively you could archive a copy of this work on a service like ZENODO to obtain a DOI which users can cite (see also: https://guides.github.com/activities/citable-code/).

Dr Kevin Moerman
AEiC JOSS

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by pbeagon** [comment]
Hi Kevin 

While I do have ideas on how to develop the R library, my new research project lacks R coding. Thanks for the reference to Zenodo.org. I use it to create a linkable DOI, and formatted references to my university and PhD funders.

[https://doi.org/10.5281/zenodo.4060238]
distFit: An R package to investigate goodness-of-fit with normal and Weibull distributions

Regards

Paul Beagon
