### ISSUE TITLE
[PRE REVIEW]: polypy - Analysis Tools for Solid State Molecular Dynamics and Monte Carlo Trajectories

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2709]
**Submitting author:** @symmy596 (<a href="http://orcid.org/0000-0001-6059-497X">Adam Symington</a>)
**Repository:** <a href="https://github.com/symmy596/Polypy" target ="_blank">https://github.com/symmy596/Polypy</a>
**Version:** 0.8
**Editor:** @richardjgowers
**Reviewers:** @hmacdope, @lscalfi
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @symmy596. **Currently, there isn't an JOSS editor assigned** to your paper.

@symmy596 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2709 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2709 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/2515-7655/ab28b5 is OK
- 10.1098/rsta.2019.0026 is OK
- 10.1039/D0TA05343K is OK
- 10.1002/bbpc.198400007 is OK
- 10.1016/0022-3697(85)90172-6 is OK
- 10.1016/S0167-2738(02)00229-1 is OK
- 10.1063/1.117366 is OK
- 10.1149/1.1507597 is OK
- 10.1103/PhysRevB.58.13901 is OK
- 10.1080/08927022.2013.839871 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/S0263-7855(96)00043-4 is INVALID because of 'https://doi.org/' prefix
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
PDF failed to compile for issue #2709 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (452.7 files/s, 50613.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          16            347            614           1399
reStructuredText                17            344            337            262
Jupyter Notebook                 4              0           1403            184
TeX                              1             10              0            133
Markdown                         2             68              0            130
YAML                             4              6             12             45
DOS Batch                        1              8              1             27
make                             1              4              6             10
CSS                              1              2              0              9
Bourne Shell                     1              1              0              5
-------------------------------------------------------------------------------
SUM:                            48            790           2373           2204
-------------------------------------------------------------------------------


Statistical information for the repository '2709' was gathered on 2020/10/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adam Symington                  40          3171           3917           20.43
symmy596                       108         15443          12170           79.57

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adam Symington             2360           74.4          3.8               10.93
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see why this paper is not compiling?

**Comment by xuanxu** [comment]
> openjournals/dev can you see why this paper is not compiling?

whedon is having problems lately when compiling the pdf at the same time it is doing other checks. Retriyng when other task are finished should work.

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02709/joss.02709/10.21105.joss.02709.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02709/joss.02709/10.21105.joss.02709.pdf) :page_facing_up: :point_left:

**Comment by symmy596** [comment]
I have noticed that the figure has not rendered. I have updated the markdown.

**Comment by symmy596** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02709/joss.02709/10.21105.joss.02709.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02709/joss.02709/10.21105.joss.02709.pdf) :page_facing_up: :point_left:

**Comment by symmy596** [comment]
Potential Reviewers

- diegoenry
- matthiaslein

**Comment by symmy596** [comment]
Potential Reviewers

- dandavies99
- matthiaslein
- fdroessler
- utf
- hannahbrucemacdonald
- arm61

**Comment by Kevin-Mattheus-Moerman** [comment]
@symmy596 thanks for your submission. I've flagged this submission for additional review by our board, to check if it is in scope for JOSS. In particular it looks like it is close to being too minor (to me at first sight) in terms of functionality / the amount of scholarly work it contains. This internal review will take about a week. In the mean time if you could clearly and concisely outline the different types of functionality this work offers and how these are significant or novel contributions, and how they may differ in relation to other work, that may help us judge the scope of this work. Thanks.

**Comment by symmy596** [comment]
polypy was the analysis software used in three pieces of published work during my PhD (10.1088/2515-7655/ab28b5, 10.1098/rsta.2019.0026 and 10.1039/D0TA05343K). It is also being used in ongoing research and in remote learning at the University of Bath.

The DL_MONTE code is a new Monte Carlo simulation code produced by STFC in the UK. To the best of my knowledge, there are no open source, research software codes that are aimed at analysis of DL_MONTE simulations. So all DL_MONTE functionality present in polypy is unique in the community.

MDAnalysis is the most widely used molecular dynamics analysis code and some of the functionality in polypy is already present in mdanalysis. The MDAnalysis.analysis.lineardensity module calculates the charge density in different dimensions, although according to the documentation, is limited to orthorombic, fixed volume cells. Polypy is designed to handle all cell types and will work for simulations ensembles other than NPT. Furthermore, the calculation of the electric field and electrostatic potential is unique to polypy.

MDAnalysis and polypy are both capable of calculating mean squared displacements. polypy goes a step further by allowing the calculation of diffusion coefficients and conductivities within localised regions of a structure e.g a grain boundary or surface. This method was used in two papers to calculate the diffusion coefficients the grain boundary and bulk regions of a simulation cell (10.1088/2515-7655/ab28b5, 10.1098/rsta.2019.0026).

DL_ANALYSER is also available for the analysis of DL_POLY simulations, however is only available under license

**Comment by kthyng** [comment]
@whedon invite @richardjgowers as editor

**Comment by whedon** [comment]
@richardjgowers has been invited to edit this submission.

**Comment by kthyng** [comment]
@symmy596 Your submission a bit borderline, but let's proceed. I encourage you to take the opportunity of your future reviewers suggestions to improve your software where possible so that it can be used by others in the future.

**Comment by richardjgowers** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by richardjgowers** [comment]
@hannahbrucemacdonald @hmacdope are you free to review this?

**Comment by richardjgowers** [comment]
@symmy596 right off the bat, I think the paper is missing a section reviewing existing tools within the field

**Comment by hmacdope** [comment]
@richardjgowers happy to review.

**Comment by richardjgowers** [comment]
@whedon add @hmacdope as reviewer

**Comment by whedon** [comment]
OK, @hmacdope is now a reviewer

**Comment by symmy596** [comment]
@richardjgowers thank you and no problem. Would you like me to update the paper now or as part of the review?

**Comment by richardjgowers** [comment]
@lscalfi would you be available to review this?

**Comment by richardjgowers** [comment]
@symmy596 yeah you can edit the paper (& code) freely until it's published

**Comment by richardjgowers** [comment]
@fdroessler @jmborr would either of you be available to review this?

**Comment by fdroessler** [comment]
@richardjgowers I wont be able to review this time. My apologies

**Comment by lscalfi** [comment]
@richardjgowers Sorry I didn't see this until now, I can review this if it's not too late

**Comment by richardjgowers** [comment]
@lscalfi yes that would be great, thanks

**Comment by richardjgowers** [comment]
@whedon add @lscalfi as reviewer

**Comment by whedon** [comment]
OK, @lscalfi is now a reviewer

**Comment by richardjgowers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2824.

**Comment by jmborr** [comment]
> @fdroessler @jmborr would either of you be available to review this?

I can review this
