### ISSUE TITLE
[PRE REVIEW]: Kindel: indel-aware consensus for nucleotide sequence alignments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#271]
**Submitting author:** @bede (<a href="http://orcid.org/0000-0002-3480-3819">Bede Constantinides</a>)
**Repository:** <a href="https://github.com/bede/kindel" target ="_blank">https://github.com/bede/kindel</a>
**Version:** v0.2.0
**Editor:** @mgymrek
**Reviewer:** @genomematt

**Author instructions**

Thanks for submitting your paper to JOSS @bede. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bede if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @mgymrek it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @mgymrek - would you be willing to edit this submission for JOSS?

**Comment by bede** [comment]
Hi @genomematt, might you be willing to review this submission? Thank you.

**Comment by genomematt** [comment]
I am happy to review but probably won't get to it until late next week.

**Comment by bede** [comment]
Thanks @genomematt, that'd be great.

**Comment by arfon** [comment]
@whedon assign @genomematt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @genomematt

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/282. Feel free to close this issue now!

**Comment by arfon** [comment]
@genomematt @bede see you over in #282 for the actual paper review.
