### ISSUE TITLE
[PRE REVIEW]: ParaMonte: A high-performance serial/parallel Monte Carlo simulation library for C, C++, Fortran

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2710]
**Submitting author:** @shahmoradi (<a href="http://orcid.org/0000-0002-9720-8937">Amir Shahmoradi</a>)
**Repository:** <a href="https://github.com/cdslaborg/paramonte" target ="_blank">https://github.com/cdslaborg/paramonte</a>
**Version:** v1.2.0
**Editor:** @VivianePons
**Reviewers:** @milancurcic, @williamfgc
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @shahmoradi. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@shahmoradi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2710 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2710 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1088/0004-637x/766/2/111 may be a valid DOI for title: A Multivariate Fit Luminosity Function and World Model for Long Gamma-Ray Bursts
- 10.1093/mnras/stv714 may be a valid DOI for title: Short versus long gamma-ray bursts: a comprehensive study of energetics and prompt gamma-ray correlations
- 10.1007/s11222-006-9438-0 may be a valid DOI for title: DRAM: efficient adaptive MCMC
- 10.1093/bioinformatics/btp162 may be a valid DOI for title: GNU MCSim: Bayesian statistical inference for SBML-coded systems biology models
- 10.18637/jss.v035.i04 may be a valid DOI for title: PyMC: Bayesian stochastic modelling in Python

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@shahmoradi I think our system cannot see your paper (which appears to be at `https://github.com/cdslaborg/paramonte/tree/master/pubs/ParaMonte/kernel/JOSS2020`), can you move the files to your main folder or put them in a `paper` folder? 

@openjournals/dev can you confirm this is the issue here? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.19 s (370.9 files/s, 122918.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                     129           9675          16520          36343
MATLAB                         199           4322          16842          18907
Python                          41           3789           6733           6479
DOS Batch                       15            685            245           3464
Fortran 77                       1            117           6772           3226
Bourne Shell                    10            564            799           2902
CMake                           20            552           1747           2535
Markdown                        14            620              0           1664
HTML                             1             20             90            231
TeX                              1             17              0            186
C                                4             54            158            173
C/C++ Header                     5             21            151             62
C++                              2             19             36             53
Java                             1              8              7             23
-------------------------------------------------------------------------------
SUM:                           443          20463          50100          76248
-------------------------------------------------------------------------------


Statistical information for the repository '2710' was gathered on 2020/10/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Amir Shahmoradi                142         29997          18077           70.62
Joshua Osborne                   2            57             13            0.10
fagheri                          5         12868           7066           29.28

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Amir Shahmoradi            5593           18.6          1.8               36.96
fagheri                   12173           94.6          0.8               12.77
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@drvinceknight @diehlpk @melissawm @VivianePons @meg-simula @mjsottile could one of you handle this submission? Thanks!

**Comment by xuanxu** [comment]
> I think our system cannot see your paper (which appears to be at `https://github.com/cdslaborg/paramonte/tree/master/pubs/ParaMonte/kernel/JOSS2020`), can you move the files to your main folder or put them in a `paper` folder?

That should not be a problem, whedon can find the paper in any subfolder

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02710/joss.02710/10.21105.joss.02710.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02710/joss.02710/10.21105.joss.02710.pdf) :page_facing_up: :point_left:

**Comment by VivianePons** [comment]
I can take it

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by shahmoradi** [comment]
I apologize for arriving late at this issue. The suggestion of @Kevin-Mattheus-Moerman as the editor was accidental, though I believe @Kevin-Mattheus-Moerman is more than qualified to edit this submission. 

@Kevin-Mattheus-Moerman I believe the problem about the paper view is now resolved by whedon.

As for potential reviewers, I suggest the following:

=================================================

milancurcic  :  Research Scientist at the University of Florida, knowledgable on the topic and the languages used in the software. 
hpparvi
krystophny
fhorrobin
scivision
davidbeckingsale
williamfgc
anowacki
DougBurke
vwmaus
Teuben
mturiansky
rchg
CFGrote
eschnett

=================================================

@VivianePons If there is anything else that I may have missed, please let me know. 

Thank you,
Best regards

**Comment by Kevin-Mattheus-Moerman** [comment]
@shahmoradi thanks for your comments. Fortunately @VivianePons has volunteered to edit this submission and she will be much better suited than I am to edit this submission. You can address any further questions/communication for the review of this work to her.

**Comment by VivianePons** [comment]
@whedon add @milancurcic as reviewer

**Comment by whedon** [comment]
OK, @milancurcic is now a reviewer

**Comment by VivianePons** [comment]
@whedon add @williamfgc as reviewer

**Comment by whedon** [comment]
OK, @williamfgc is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2741.
