### ISSUE TITLE
[PRE REVIEW]: IndividualDisplacements.jl: a Julia package to simulate and study particle displacements within the climate system

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2713]
**Submitting author:** @gaelforget (<a href="http://orcid.org/0000-0002-4234-056X">Gael Forget</a>)
**Repository:** <a href="https://github.com/JuliaClimate/IndividualDisplacements.jl" target ="_blank">https://github.com/JuliaClimate/IndividualDisplacements.jl</a>
**Version:** v0.2.0
**Editor:** @kthyng
**Reviewers:** @milankl, @visr
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gaelforget. **Currently, there isn't an JOSS editor assigned** to your paper.

@gaelforget if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (453.0 files/s, 45135.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           22            561            422           2085
Markdown                         6             71              0            128
TOML                             3              2              0             60
YAML                             3              6              0             53
-------------------------------------------------------------------------------
SUM:                            34            640            422           2326
-------------------------------------------------------------------------------


Statistical information for the repository '2713' was gathered on 2020/10/01.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2713 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2713 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch josspaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch josspaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02713/joss.02713/10.21105.joss.02713.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02713/joss.02713/10.21105.joss.02713.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@gaelforget thanks for your submission. I've flagged this submission for additional review by our board to check if it is in scope for JOSS. In particular it looks like it is close to being too minor (to me at first sight) in terms of functionality / the amount of scholarly work it contains. This internal review will take about a week. In the mean time if you could clearly and concisely outline the different types of functionality this work offers and how these differ (or are novel) in relation to other work that may help us judge the scope of this work. Thanks.

**Comment by gaelforget** [comment]
Hi @Kevin-Mattheus-Moerman 

Thanks for taking this on and for your amazingly quick first assessment. I am especially grateful for such efficiency in light of the strain that COVID has been putting on all of us and the fact that joss is operating in reduced service mode in particular. 

Will get back to you with specifics asap after I re-read the journal docs another time in light of your comment -- I feel I may have overlooked something subtle in the language of the submission guidelines as I was under the impression that this submission would rather easily clear the bar for getting to the open review stage.

In any event, I look forward to additional feedback that you or any other editor may post here, will do my best to respond as rapidly as I can, and hope that I will get a chance to address possible concerns about e.g. functionality or scholarly work over the course of the review process if needed.

By the way, is it ok for me to ask follow up questions here if that's going to help me respond to your comment in more detail?

**Comment by Kevin-Mattheus-Moerman** [comment]
@gaelforget yes fire away, feel free to ask questions.

**Comment by gaelforget** [comment]
Hi @Kevin-Mattheus-Moerman 

A quick post to apologize for the delay in my response -- it's been a rather hectic week on on my end ...

If that's ok, let me start with 

> clearly and concisely outline the different types of functionality this work offers

and then turn to the scope and scholarly effort aspects later today and tomorrow

**Comment by gaelforget** [comment]
Below I outline the different types of functionality this work offers. 

The [three_dimensional_ocean notebook](https://juliaclimate.github.io/IndividualDisplacements.jl/dev/worldwide/three_dimensional_ocean/) and [the corresponding animation](https://youtu.be/twAAE_WUs_g) additionally provide a representative example of these functionalities put to action.

[W.I.P.]

**Comment by kthyng** [comment]
@gaelforget thanks for the extra information! We can move forward with this submission. I will be your editor since I do particle tracking too, though not with Julia. I will need particular help from you finding reviewers who can review this software in Julia. Please provide github handles or another way to reach people from either your own network (but not conflicting) or from the list [of volunteers](https://bit.ly/joss-reviewers). Do not use "@" when mentioning github handles here so we don't spam people unnecessarily.

**Comment by kthyng** [comment]
@whedon add me as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by gaelforget** [comment]
> @gaelforget thanks for the extra information! We can move forward with this submission. I will be your editor since I do particle tracking too, though not with Julia. I will need particular help from you finding reviewers who can review this software in Julia. Please provide github handles or another way to reach people from either your own network (but not conflicting) or from the list [of volunteers](https://bit.ly/joss-reviewers). Do not use "@" when mentioning github handles here so we don't spam people unnecessarily.

This is great news! Thanks @kthyng for taking on this submission as editor. 

I will work on reviewer suggestions asap and hope to get back to you later today on this. Thanks for your patience

**Comment by kthyng** [comment]
@gaelforget Can you add a short section to your paper also to compare your software with other particle tracking software? This will help give context.

**Comment by kthyng** [comment]
@gaelforget Still waiting to hear back from you about reviewer suggestions too.

**Comment by gaelforget** [comment]
> @gaelforget Still waiting to hear back from you about reviewer suggestions too.

Based on the list of volunteers (Preferred Language + Domain Expertise, mostly) and from my own network (incl. https://github.com/JuliaClimate) I may suggest:

- juliohm, felixcremer, visr, Alexander-Barth, natgeo-wong, milankl
- wkearn, Jgoldfar, eviatarbach (not in JuliaClimate)

Would this work?

ps. Others that came to mind but I felt may be too closely connected to me (`conflicting`?) include: ali-ramadhan and hdrake who are in my department at MIT; the CLIMA project which involves many close collaborators although not myself.

**Comment by kthyng** [comment]
Hi @visr and @milankl! Are you interested in reviewing this submission to the Journal for Open Source Software? The review is done openly through github and is checklist-driven. Acknowledging the global pandemic, we're asking for reviews in 5-6 weeks. You can get more information from our [docs](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) (though looks like they are offline at the moment). Please feel free to ask questions too.

I encourage you to [sign up](https://joss.theoj.org/reviewer-signup.html) as a JOSS reviewer if you'd like!

**Comment by milankl** [comment]
Thanks @kthyng for the invitiation, I'm happy to accept.

**Comment by kthyng** [comment]
@milankl Excellent! I'll add you now, though we will wait in this pre-review stage until we have two reviewers before beginning the actual review issue.

**Comment by kthyng** [comment]
@whedon assign @milankl as reviewer

**Comment by whedon** [comment]
OK, @milankl is now a reviewer

**Comment by visr** [comment]
I would also be happy to review.

**Comment by kthyng** [comment]
Thanks @visr! We'll proceed now.

**Comment by kthyng** [comment]
@whedon add @visr as reviewer

**Comment by whedon** [comment]
OK, @visr is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2813.
