### ISSUE TITLE
[PRE REVIEW]: ropenblas: Download, Compile and Link OpenBLAS Library with R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2715]
**Submitting author:** @prdm0 (<a href="http://orcid.org/0000-0003-1591-8300">Pedro Rafael Marinho</a>)
**Repository:** <a href="https://github.com/prdm0/ropenblas" target ="_blank">https://github.com/prdm0/ropenblas</a>
**Version:** v0.2.8
**Editor:** @timtroendle
**Reviewers:** @pratikvn, @sahilseth
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @prdm0. **Currently, there isn't an JOSS editor assigned** to your paper.

@prdm0 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (269.0 files/s, 56193.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            11            512            147           1606
R                                2            166            224            715
XML                              2              0              5            525
Markdown                         3            289              0            495
CSS                              3             99             48            428
JavaScript                       3             64             32            256
TeX                              2              4              0             98
Rmd                              1            105            184             39
SVG                              1              0              1             11
YAML                             1              1              0              5
-------------------------------------------------------------------------------
SUM:                            29           1240            641           4178
-------------------------------------------------------------------------------


Statistical information for the repository '2715' was gathered on 2020/10/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Pedro Rafael                     6        853454         853454           99.99
prdm0                            1           159              5            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
prdm0                       352          221.4          2.4                9.09
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@prdm0 thanks for your submission. This paper needs work. It lacks the concise sections we look for, e.g. Statement of need, and is too long. You can likely shorten it significantly by removing content that is already in the readme/documentation. 
Please review our guidelines on what the paper should contain: https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain. 
You can call `@whedon generate pdf` to update the paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
@prdm0 I've flagged this submission for additional scope review by our editorial board which will take about a week. The reason for this scope check is that this submission, to me, at first sight, appears rather minor in terms of functionality and amount of scholarly effort (see our [requirements related to substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)).

**Comment by prdm0** [comment]
Dear @Kevin-Mattheus-Moerman, this package has a lot of effort and has already been referred by important people in the R community. The project is followed by a programmer from the company RStudio and already has more than 6 thousand downloads. The aim of the package is to speed up the R for linear algebra operations. Everything is done within R without relying on GNU / Linux distribution repositories.

**Comment by prdm0** [comment]
@Kevin-Mattheus-Moerman The project allows recent versions of R to be installed on any GNU / Linux distribution, even if it does not have the latest version of the R language in the distribution repositories. It also allows us to switch between versions of R.

**Comment by prdm0** [comment]
@Kevin-Mattheus-Moerman  The project is very robust and allows to accelerate the R language through the link with the OpenBLAS library. The project is so useful that researchers like Norman Matloff, who wrote several R-language books, featured the project on his Twitter.

**Comment by prdm0** [comment]
> @prdm0 I've flagged this submission for additional scope review by our editorial board which will take about a week. The reason for this scope check is that this submission, to me, at first sight, appears rather minor in terms of functionality and amount of scholarly effort (see our [requirements related to substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)).

@Kevin-Mattheus-Moerman I would like you to be clear when you say that there is no academic effort in a far-fetched R code and that it brings functionalities that underpinned the linear algebra computation of R. Everything is done within R. The package allows you to switch between versions of R and between versions from the OpenBLAS library. In the last month there were more than 800 downloads for a total of more than 6 thousand downloads from the library. The project is followed by people from the field of data science and machine learning and was shared by people who wrote R books and who are highly respected by the community that maintains the language. I have several emails that prove the importance of this package.

This package has a lot to add to JOSS and will certainly bring citations to the Journal.

This package will help any researcher who wishes to perform computationally in algebraic computing, allowing the automatic linking of R to the OpenBLAS library.

Algebraic computations are currently carried out in the most varied research.

I will wait for an editorial board positioning.

**Comment by prdm0** [comment]
> Failed to discover a `Statement of need` section in paper



> Failed to discover a `Statement of need` section in paper

@whedon generate pdf

The "**Statement of Need**" section has been added.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@prdm0 thanks for your additional comments. I just want to add I am not implying this work is not useful or of a poor quality. For more on the term "effort" I used see our guidelines: https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort. You'll read there that submissions under 1000 lines of code (judging from the R code contained in this submission) are regularly subjected to additional scope review. I am sure this work will be properly reviewed by our editorial board which includes R specialists (which I am not). Thanks again for your clarifications. You will hear back shortly.

**Comment by prdm0** [comment]
> @prdm0 thanks for your additional comments. I just want to add I am not implying this work is not useful or of a poor quality. For more on the term "effort" I used see our guidelines: https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort. You'll read there that submissions under 1000 lines of code (judging from the R code contained in this submission) are regularly subjected to additional scope review. I am sure this work will be properly reviewed by our editorial board which includes R specialists (which I am not). Thanks again for your clarifications. You will hear back shortly.

Thank you very much for an answer @Kevin-Mattheus-Moerman. I am grateful for the clarifications.

**Comment by prdm0** [comment]
@ Kevin-Mattheus-Moerman, I have a question about one of @whedon  output:

```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```
 is this just a warning that there is no DOI yet? I can disregard it, okay?

Finally, should I wait for the review to reduce the material? What is the minimum number of pages?

Kind regards.

**Comment by prdm0** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: :point_left:

**Comment by prdm0** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: :point_left:

**Comment by prdm0** [comment]
Paper reduced from 13 to 9 pages.

@whedon generate pdf

**Comment by prdm0** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: :point_left:

**Comment by prdm0** [comment]
I significantly reduced the number of pages, from 13 to 9.

**Comment by prdm0** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
Just a heads up @prdm0 - this paper is still far too long. Most of the detailed documentation of the API should not be in the JOSS paper.

As a guideline, JOSS submissions should be ~1000 words (~4 pages max).

**Comment by Kevin-Mattheus-Moerman** [comment]
> @Kevin-Mattheus-Moerman, I have a question about one of @whedon output:
> 
> ```
> Reference check summary (note 'MISSING' DOIs are suggestions that need verification):
> 
> OK DOIs
> 
> - None
> 
> MISSING DOIs
> 
> - None
> 
> INVALID DOIs
> 
> - None
> ```
> 
> is this just a warning that there is no DOI yet? I can disregard it, okay?
> 
> Finally, should I wait for the review to reduce the material? What is the minimum number of pages?
> 
> Kind regards.

In relation to this :point_up_2: question. Our system checks if: 1) the references/citations you are using should have DOI's, and 2) if they do if the DOI's given are valid (they link to the correct paper) or not. It looks like you cite 3 "websites" or urls to software or other sites. These likely do not have DOI's so the system finds you currently have no DOI's (and therefore no invalid ones etc). So there is no problem there in principle. 

However, on a related note, and getting back to the paper content, it would be good to cite research utilizing this work and also perhaps similar/relevant works/research appearing in the literature. Once you add such references they will need appropriate DOI's in the .bib entries as well. Let me know if you have more questions. For more information check the "What should my paper contain?" section here: https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

**Comment by prdm0** [comment]
> > @Kevin-Mattheus-Moerman, I have a question about one of @whedon output:
> > ```
> > Reference check summary (note 'MISSING' DOIs are suggestions that need verification):
> > 
> > OK DOIs
> > 
> > - None
> > 
> > MISSING DOIs
> > 
> > - None
> > 
> > INVALID DOIs
> > 
> > - None
> > ```
> > 
> > 
> > is this just a warning that there is no DOI yet? I can disregard it, okay?
> > Finally, should I wait for the review to reduce the material? What is the minimum number of pages?
> > Kind regards.
> 
> In relation to this point_up_2 question. Our system checks if: 1) the references/citations you are using should have DOI's, and 2) if they do if the DOI's given are valid (they link to the correct paper) or not. It looks like you cite 3 "websites" or urls to software or other sites. These likely do not have DOI's so the system finds you currently have no DOI's (and therefore no invalid ones etc). So there is no problem there in principle.
> 
> However, on a related note, and getting back to the paper content, it would be good to cite research utilizing this work and also perhaps similar/relevant works/research appearing in the literature. Once you add such references they will need appropriate DOI's in the .bib entries as well. Let me know if you have more questions. For more information check the "What should my paper contain?" section here: https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

Thanks for the clarification. Understood.

**Comment by prdm0** [comment]
> Just a heads up @prdm0 - this paper is still far too long. Most of the detailed documentation of the API should not be in the JOSS paper.
> 
> As a guideline, JOSS submissions should be ~1000 words (~4 pages max).

Thank you. I will try to focus now on drastically reducing the paper.

**Comment by prdm0** [comment]
Drastic paper reduction from 13 to 4 pages.

**Comment by prdm0** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02715/joss.02715/10.21105.joss.02715.pdf) :page_facing_up: :point_left:

**Comment by prdm0** [comment]
Dear @Kevin-Mattheus-Moerman I reduced the paper from 13 to 4 pages, in order to fit with the Journal. Do I need to do anything else or should I wait?

**Comment by Kevin-Mattheus-Moerman** [comment]
@prdm0 at this point we will review the work for scope, which should take about a week. Thanks for your patience.

**Comment by prdm0** [comment]
> @prdm0 thanks for your additional comments. I just want to add I am not implying this work is not useful or of a poor quality. For more on the term "effort" I used see our guidelines: https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort. You'll read there that submissions under 1000 lines of code (judging from the R code contained in this submission) are regularly subjected to additional scope review. I am sure this work will be properly reviewed by our editorial board which includes R specialists (which I am not). Thanks again for your clarifications. You will hear back shortly.

Regarding codes with less than 1000 lines, I emphasize that my code has exactly 1103 lines. See the code [**here**](https://github.com/prdm0/ropenblas/blob/master/R/ropenblas.R#L1103). All lines with `#` are codes that generate the package documentation using [**roxygen2**](https://cran.r-project.org/web/packages/roxygen2/index.html).

**Comment by danielskatz** [comment]
@prdm0 - while this code is somewhat of a wrapper and it is relatively small, after some discussion, we have decided that because of its dynamic properties, it is not just a wrapper, and we will go ahead and review it.

**Comment by danielskatz** [comment]
👋 @timtroendle - Would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @timtroendle as editor

**Comment by whedon** [comment]
@timtroendle has been invited to edit this submission.

**Comment by prdm0** [comment]
> @prdm0 - while this code is somewhat of a wrapper and it is relatively small, after some discussion, we have decided that because of its dynamic properties, it is not just a wrapper, and we will go ahead and review it.

Dear @danielskatz , I'm happy to have my tools being evaluated at JOSS. Enabling distribution-independent GNU/Linux users to link R to optimized versions of BLAS is of great use. Thank you all for understanding the importance of the project.

Kind regards,
prdm0.

**Comment by timtroendle** [comment]
@openjournals/joss-eics Yes, I can edit this submission.

**Comment by danielskatz** [comment]
Thanks @timtroendle - when you are willing to edit, you can do what I'm going to do next, then get started (you can also replace your github name by me, as ```@whedon assign me as editor``` - you don't need to wait for the AEiC to assign you

**Comment by danielskatz** [comment]
@whedon assign @timtroendle as editor

**Comment by whedon** [comment]
OK, the editor is @timtroendle

**Comment by timtroendle** [comment]
👋 @wrathematics, @crew102, @matloff, would any of you be willing to review this submission for JOSS?

**Comment by prdm0** [comment]
> Hello @prdm0 ! I will start looking for reviewers for your submission. Please let me know if you want to suggest any reviewers yourself.

Dear @timtroendle , I liked your choices. Kind, regards.

**Comment by matloff** [comment]
Unfortunately, I have only a passing familiarity with OpenBLAS, simply as a user, and don't feel qualified to review papers on it.

Norm

**Comment by crew102** [comment]
I @timtroendle , I'm not familiar with OpenBLAS at all, so I'm probably not the best person to review this.

**Comment by timtroendle** [comment]
@matloff @crew102 Understood. Thanks for letting us know!

**Comment by timtroendle** [comment]
👋 @Jgoldfar, @pratikvn, would any of you be willing to review this submission for JOSS?

**Comment by pratikvn** [comment]
@timtroendle , yes, I would be available to review this submission.

**Comment by timtroendle** [comment]
Great @pratikvn , thanks a lot for the offer!

**Comment by timtroendle** [comment]
@whedon add @pratikvn as reviewer

**Comment by whedon** [comment]
OK, @pratikvn is now a reviewer

**Comment by sahilseth** [comment]
I have tried this pkg and can help review it, if needed - thanks

**Comment by timtroendle** [comment]
That's very helpful, thanks @sahilseth !

**Comment by timtroendle** [comment]
@whedon add @sahilseth as reviewer

**Comment by whedon** [comment]
OK, @sahilseth is now a reviewer

**Comment by timtroendle** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2769.

**Comment by jgoldfar** [comment]
Hello Tim; sorry for the delay. I would be happy to help, but will
probably not have time to complete the review well until December.
Best,
Jonathan Goldfarb

* Tim Tröndle <notifications@github.com> [2020-10-18 23:27:31 -0700]:

**Comment by timtroendle** [comment]
Hello Max, thanks for coming back! We started the review with two reviewers, but if there is still a need closer towards December, I may come back to you.
