### ISSUE TITLE
[PRE REVIEW]: REGENS: an open source Python package for simulating realistic autosomal genotypes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2716]
**Submitting author:** @greggj2016 (<a href="http://orcid.org/0000-0002-2619-3440">John Gregg</a>)
**Repository:** <a href="https://github.com/EpistasisLab/regens" target ="_blank">https://github.com/EpistasisLab/regens</a>
**Version:** v0.1.0
**Editor:** @fboehm
**Reviewers:** @raivivek, @dwinter
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @greggj2016. **Currently, there isn't an JOSS editor assigned** to your paper.

@greggj2016 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02716/joss.02716/10.21105.joss.02716.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02716/joss.02716/10.21105.joss.02716.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=10.49 s (5.8 files/s, 50407.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SQL                              1              0              0         500001
C                                1           1768           8513          15245
Python                           8            224            293            860
Bourne Shell                    32             70            204            654
Markdown                         7            106              0            417
R                               10             30              0            260
TeX                              1             16              0            112
Cython                           1              5              0             50
-------------------------------------------------------------------------------
SUM:                            61           2219           9010         517599
-------------------------------------------------------------------------------


Statistical information for the repository '2716' was gathered on 2020/10/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
John Gregg                       4         51848          51426           99.96
greggj2016                       1             0             41            0.04

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
John Gregg                52597          101.4          0.0               34.35
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@fboehm @mikldk @lpantano @will-rowe @majensen could one of you handle this submission? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
FYI :point_up: I closed an apparent duplicate submission. @greggj2016 can you confirm you submitted twice perhaps by mistake? I want to check if this was a hiccup in our system or not.

**Comment by greggj2016** [comment]
Yes, actually this is the first paper I submitted here. I wasn't sure how to submit my reformatted draft, so I had attempted to resubmit the reformatted draft and withdraw the previous submission. However, clicking the button to withdraw the previous submission did not seem to do anything after multiple attempts. I was then advised to wait for your response, so this is not a hiccup in your system (Unless you count the withdraw submission button not working. You might want to look at that.)

**Comment by Kevin-Mattheus-Moerman** [comment]
@greggj2016 Okay thanks for clarifying. In the future you can make changes to your paper on your repository and then call `@whedon generate pdf` (on its own, without any other text) here, to update the paper.

**Comment by greggj2016** [comment]
Yes, but what does that mean to "call @whedon generate pdf"?

**Comment by Kevin-Mattheus-Moerman** [comment]
Like this :point_down:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by greggj2016** [comment]
yes, but where do I input that? Is there a place where I can read more details?

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02716/joss.02716/10.21105.joss.02716.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02716/joss.02716/10.21105.joss.02716.pdf) :page_facing_up: :point_left:

**Comment by greggj2016** [comment]
@whedon generate pdf

**Comment by greggj2016** [comment]
Did your comment make that?

**Comment by Kevin-Mattheus-Moerman** [comment]
> yes, but where do I input that? Is there a place where I can read more details?

Right here. Like you just did :+1:

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02716/joss.02716/10.21105.joss.02716.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02716/joss.02716/10.21105.joss.02716.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
> Did your comment make that?

Yep, and yours did too

**Comment by greggj2016** [comment]
Got it thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
We will also use whedon like that to assign reviewers, start the review etc.

**Comment by greggj2016** [comment]
Is there a place i can read more about the full functionality of whedon, or do I not need to know anything else?

**Comment by Kevin-Mattheus-Moerman** [comment]
> Is there a place i can read more about the full functionality of whedon, or do I not need to know anything else?

See here: https://joss.readthedocs.io/en/latest/

Let me know if you have any more questions.

**Comment by fboehm** [comment]
Yes, @Kevin-Mattheus-Moerman - I can take this on as editor.

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by fboehm** [comment]
@whedon assign @raivivek as reviewer

**Comment by whedon** [comment]
OK, @raivivek is now a reviewer

**Comment by fboehm** [comment]
@whedon add @dwinter as reviewer

**Comment by whedon** [comment]
OK, @dwinter is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2743.
