### ISSUE TITLE
[PRE REVIEW]: PyQMRI: An accelerated Python based Quantitative MRI Python toolbox

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2718]
**Submitting author:** @maieroli2010 (<a href="http://orcid.org/0000-0002-7800-0022">Oliver Maier</a>)
**Repository:** <a href="https://github.com/IMTtugraz/PyQMRI" target ="_blank">https://github.com/IMTtugraz/PyQMRI</a>
**Version:** v0.3.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @grlee77,  @agahkarakuzu, @DARSakthi
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @maieroli2010. **Currently, there isn't an JOSS editor assigned** to your paper.

@maieroli2010 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2718 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2718 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2718 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2718 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch JOSS_pub

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS_pub. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2718 with the following error: 

 sh: 1: cd: can't cd to tmp/2718
/app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2718 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you help troubleshoot why this paper is not compiling? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch JOSS_pub

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS_pub. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02718/joss.02718/10.21105.joss.02718.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02718/joss.02718/10.21105.joss.02718.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
> @openjournals/dev can you help troubleshoot why this paper is not compiling? Thanks

I think I fixed it by changing the repository link to be the repo itself not the branch

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.55 s (98.9 files/s, 38614.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          30           1662           3655           8461
C                                8            679            356           5650
reStructuredText                 9            134             98            231
DOS Batch                        1              8              1             27
Dockerfile                       1              7              1             27
YAML                             2              8             11             26
make                             1              4              6             10
INI                              1              0              0             10
Bourne Shell                     1              0              0              8
-------------------------------------------------------------------------------
SUM:                            54           2502           4128          14450
-------------------------------------------------------------------------------


Statistical information for the repository '2718' was gathered on 2020/10/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Maier, Oliver                  341        257592         241085           89.13
Oliver                          62         30982           6909            6.77
Oliver Maier                   131         16345           6600            4.10

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Maier, Oliver             20463            7.9          7.4                4.81
```

**Comment by MaierOli2010** [comment]
I would suggest hanayik as potential reviewer given his knowledge in MRI and Image Analysis and sbacchio for his knowledge in HPC and Iterative Linear Solvers. vitorsr, ulvgard, and stsievert might be suitable too given their background in optimization and image processing.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @jni as editor

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by jni** [comment]
@Kevin-Mattheus-Moerman unfortunately I don't have the bandwidth right now, especially since I'm about to go on leave. I *will* however additionally recommend grlee77 as an additional potential reviewer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@grlee77, @JoshKarpel, @rljacobson, @mfroeling, @62442katieb, @agahkarakuzu, @mathieuboudreau, @spinicist, @imr-framework, @kerkelae , @DARSakthi, @ritagnunes

Would you be interested in reviewing this work for JOSS? 

_PyQMRI: An accelerated Python based Quantitative MRI Python toolbox_
**paper** :point_right: https://github.com/openjournals/joss-papers/blob/joss.02718/joss.02718/10.21105.joss.02718.pdf
**software** :point_right: https://github.com/IMTtugraz/PyQMRI

**Comment by JoshKarpel** [comment]
Unfortunately I don't have time at the moment. Thanks for asking!

**Comment by spinicist** [comment]
Looks very interesting but I don't have access to a suitable GPU at the moment!

**Comment by grlee77** [comment]
Sure, I am interested.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @grlee77 as reviewer

**Comment by whedon** [comment]
OK, @grlee77 is now a reviewer

**Comment by 62442katieb** [comment]
@Kevin-Mattheus-Moerman looks like an interesting toolbox, but I don't have access to a GPU at the moment

**Comment by agahkarakuzu** [comment]
@Kevin-Mattheus-Moerman I've arranged GPU access, happy to help out!

**Comment by mathieuboudreau** [comment]
Since @agahkarakuzu and I are from the same lab, I yield to him and decline for myself.

**Comment by DARSakthi** [comment]
I can try to arrange for GPU access. If another reviewer is needed

In general, and as an item of interest for the authors, GPUs are hard to
come by -- including solutions like Google Collab - based scripts, which
allows for free GPU access, could be valuable in expanding the user base.

Let me know if no one else steps up @Kevin-Mattheus-Moerman. Looks like an
interesting paper

Cheers

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add  @agahkarakuzu as reviewer

**Comment by whedon** [comment]
OK,  @agahkarakuzu is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@DARSakthi if you are still interested I'd like to add you as a third reviewer, let me know. Thanks!

**Comment by DARSakthi** [comment]
Sure, I'll do it

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @DARSakthi as reviewer

**Comment by whedon** [comment]
OK, @DARSakthi is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2727.
