### ISSUE TITLE
[PRE REVIEW]: pfsspy: A Python package for potential field source surface modelling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2719]
**Submitting author:** @dstansby (<a href="http://orcid.org/0000-0002-1365-1908">David Stansby</a>)
**Repository:** <a href="https://github.com/dstansby/pfsspy" target ="_blank">https://github.com/dstansby/pfsspy</a>
**Version:** 0.6.0
**Editor:** @mbobra
**Reviewers:** @mancellin, @sibirrer
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @dstansby. **Currently, there isn't an JOSS editor assigned** to your paper.

@dstansby if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2719 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2719 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-364ded062842/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02719/joss.02719/10.21105.joss.02719.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02719/joss.02719/10.21105.joss.02719.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.16 s (320.0 files/s, 52414.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          31           1025           2094           2767
SVG                              2              0              1           1502
reStructuredText                10             85             21            308
TeX                              2             52              5            295
make                             1             30              5            192
YAML                             4             13              4             71
DOS Batch                        1              8              1             26
Markdown                         1              3              0             10
-------------------------------------------------------------------------------
SUM:                            52           1216           2131           5171
-------------------------------------------------------------------------------


Statistical information for the repository '2719' was gathered on 2020/10/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
David Stansby                  344         10702           5138           94.26
Samuel Badman                   27           661            303            5.74

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
David Stansby              5676           53.0         13.8               18.16
Samuel Badman               210           31.8          3.3               20.95
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@mbobra @sjpfenninger @xuanxu @dfm could one of you handle this submission? Thanks

**Comment by arfon** [comment]
@whedon invite @mbobra as editor

@Kevin-Mattheus-Moerman - this looks like a really good fit for @mbobra I think?

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by mbobra** [comment]
@Kevin-Mattheus-Moerman @arfon I am happy to edit! I think I can be an objective editor, but I do want to mention that I've used PFSSPy and opened issues on the repo ([see here](https://github.com/dstansby/pfsspy/issues/211)). Is this okay? If so, I will assign myself as editor.

**Comment by arfon** [comment]
> @Kevin-Mattheus-Moerman @arfon I am happy to edit! I think I can be an objective editor, but I do want to mention that I've used PFSSPy and opened issues on the repo (see here). Is this okay? If so, I will assign myself as editor.

I think this is OK for you to go ahead and edit. Thanks for declaring this :-)

**Comment by mbobra** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
Thanks for your submission, @dstansby! 

I'll work on finding reviewers. If you have any suggestions (from the [reviewer spreadsheet](https://bit.ly/joss-reviewers) or otherwise), please let me know. You can suggest them without a mention, e.g. mbobra instead of @mbobra.

**Comment by dstansby** [comment]
Not sure what the best way to filter through the reviewer spreadsheet is, but from the bottom up the first handful of people with both python and astrophysics mentioned are: sibirrer, cxwx, JBorrow, cavestruz, sambit-giri, ashkelly

**Comment by mbobra** [comment]
@whedon assign @mancellin as reviewer

**Comment by whedon** [comment]
OK, @mancellin is now a reviewer

**Comment by mbobra** [comment]
@whedon add @sibirrer as reviewer

**Comment by whedon** [comment]
OK, @sibirrer is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2732.
