### ISSUE TITLE
[PRE REVIEW]: Thresholdmann: A Web tool for interactively creating adaptive thresholds to segment MRI data.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2720]
**Submitting author:** @katjaq (<a href="http://orcid.org/0000-0002-7237-0196">Katja Heuer</a>)
**Repository:** <a href="https://github.com/neuroanatomy/thresholdmann" target ="_blank">https://github.com/neuroanatomy/thresholdmann</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @katjaq. **Currently, there isn't an JOSS editor assigned** to your paper.

@katjaq if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (378.0 files/s, 102222.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       6            283            256           4546
JSON                             5              0              0            564
HTML                             2             36             12            320
SVG                              3              3              3            203
Markdown                         6             61              0            139
CSS                              1              2              0             45
YAML                             1              0              0             17
-------------------------------------------------------------------------------
SUM:                            24            385            271           5834
-------------------------------------------------------------------------------


Statistical information for the repository '455b6f4fbbe00278d81b8008' was
gathered on 2020/10/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Roberto Toro                     4          5113             96           95.02
katja heuer                      2             3              3            0.11
katjaq                           8            73             65            2.52
r03ert0                          1            70             59            2.35

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Roberto Toro               4907           96.0          1.0                5.18
katjaq                       62           84.9          2.7                1.61
r03ert0                      67           95.7          0.7                1.49
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2720 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02720/joss.02720/10.21105.joss.02720.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02720/joss.02720/10.21105.joss.02720.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@katjaq - thanks for your submission to JOSS. A couple of quick questions:

1. Could you explain the relationship between this submission and https://github.com/r03ert0/thresholdmann ? This looks to be a fork?
2. Could you point us to the JavaScript components that have been authored as part of this work? (e.g. `thresholdmann.js`)

**Comment by katjaq** [comment]
Hello @arfon . 
1. The neuroanatomy Github account is the account of the research group headed by @r03ert0 :) Sometimes we work in repositories in our own accounts, sometimes directly in the lab but when sharing the tools or final script workflows for papers for publication, we share from the @neuroanatomy group account which becomes the main repository for the tool.
2. Everything inside the Thresholdmann repository in @neuroanatomy with the exception of the rbf (radial basis functions) package which is an external module, has been authored as part of this work.

**Comment by arfon** [comment]
Got it. Thanks @katjaq.

This submission is on the smaller side of what we allow in JOSS so I'm going to ask for a scope review by the JOSS editorial team. This will take 7-10 days to happen, after which we can look for an editor and possible reviewers.

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@katjaq - also,  `joss-paper-branch` and `master` don't seem to be the same (i.e. there are additional JavaScript files in `master`). Could you clarify which branch you want reviewed?

**Comment by katjaq** [comment]
Thank you for your feedback @arfon .
I updated the joss-paper-branch where the actual paper files live, and now has the updated code as well. So the code is same in both branches, only the paper.md and bib files are an addition in the paper branch. The Web tool is being served to GitHub pages from master. (but now both branches are equal in terms of code so it doesn't matter).

**Comment by danielskatz** [comment]
👋 @katjaq - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by r03ert0** [comment]
Dear @danielskatz,
We understand your decision. We thought our software would fit the criteria because of its usefulness (criterion #6), as manual segmentation of inhomogeneous MRI data is a very frequent challenge for non-human MRI. Our tool has already been cited in one of our papers (criterion #5), and it will be soon cited in another one (from a primate neuroimaging consortium). Its main value and appeal, in our opinion, is on the UX more than the algorithm. The number of commits (criterion #2) in the present repo may be misleading because the tool was migrated from a previous repo into this one. In any case, it is true that the tool is not particularly old (criterion #1), and that it's only @katjaq and me who are currently developing it (criterion #3).

If in a future more functionalities were added (thus increasing the number of lines, commits, and probably the usability of the tool), would you consider a re-submission? Is there any particular sort of proof we could provide for the fulfilment of the admissibility criteria?

thank you!

**Comment by danielskatz** [comment]
> If in a future more functionalities were added (thus increasing the number of lines, commits, and probably the usability of the tool), would you consider a re-submission? 

yes, certainly.

> Is there any particular sort of proof we could provide for the fulfilment of the admissibility criteria?

Just to document how much effort has gone into the work, however you feel shows that best.
