### ISSUE TITLE
[REVIEW]: Mangal.jl and EcologicalNetworks.jl: Two complementary packages for analyzing ecological networks in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2721]
**Submitting author:** @FrancisBanville (<a href="http://orcid.org/0000-0001-9051-0597">Francis Banville</a>)
**Repository:** <a href="https://github.com/EcoJulia/EcologicalNetworks.jl" target ="_blank">https://github.com/EcoJulia/EcologicalNetworks.jl</a>
**Version:** v0.4.3
**Editor:** @KristinaRiemer
**Reviewer:** @kellykochanski, @arbennett
**Archive:** <a href="https://doi.org/10.5281/zenodo.4716483" target="_blank">10.5281/zenodo.4716483</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f17d9716739dafff35e3f5f6fefdd622/status.svg)](https://joss.theoj.org/papers/f17d9716739dafff35e3f5f6fefdd622)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f17d9716739dafff35e3f5f6fefdd622"><img src="https://joss.theoj.org/papers/f17d9716739dafff35e3f5f6fefdd622/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f17d9716739dafff35e3f5f6fefdd622/status.svg)](https://joss.theoj.org/papers/f17d9716739dafff35e3f5f6fefdd622)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/EcoJulia/EcologicalNetworks.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kellykochanski & @arbennett, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @KristinaRiemer know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/EcoJulia/EcologicalNetworks.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@FrancisBanville) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/EcoJulia/EcologicalNetworks.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@FrancisBanville) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kellykochanski, @arbennett it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2721 with the following error: 

 Can't find any papers to compile :-(

**Comment by arbennett** [comment]
@FrancisBanville - it seems there's no paper in this repository to review. Is the paper in the Mangal.jl repo?

**Comment by FrancisBanville** [comment]
@arbennett - The paper is in the branch `joss-article` of the `EcologicalNetworks.jl` repository.

Sorry for the confusion!

**Comment by kellykochanski** [comment]
@KristinaRiemer I can't edit the checklist (despite logging in and accepting the invitation, as suggested) - can you make sure I'm added?

**Comment by kellykochanski** [comment]
@whedon generate pdf from branch joss-article

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-article. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02721/joss.02721/10.21105.joss.02721.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02721/joss.02721/10.21105.joss.02721.pdf) :page_facing_up: :point_left:

**Comment by kellykochanski** [comment]
@KristinaRiemer  I still can't edit the checklist - either I'm missing something simple or it's a bug. I'm definitely logged in, I did accept the invitation (although if I click the link now, it's no longer available - says either the invitation was revoked or I'm in the wrong account?). I've tried both chrome and firefox.

**Comment by kellykochanski** [comment]
@FrancisBanville Thanks for submitting a well-written paper and test-covered code repository! I'm ready to approve you on many of the review criteria once I get the checklist working. However, I am also collecting a few questions and issues. These are raised on your repository as issues 166-168:

https://github.com/EcoJulia/EcologicalNetworks.jl/issues/166 - authorship
https://github.com/EcoJulia/EcologicalNetworks.jl/issues/167 - installation instructions
https://github.com/EcoJulia/EcologicalNetworks.jl/issues/168 - paper

**Comment by danielskatz** [comment]
Let's try again

**Comment by danielskatz** [comment]
@whedon re-invite @kellykochanski as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@kellykochanski please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by kellykochanski** [comment]
@danielskatz Thank you! It's working now.

**Comment by KristinaRiemer** [comment]
Just checking in with reviewers @kellykochanski & @arbennett to see how everything is going and if there is anything you need help with or is blocking your progress?

**Comment by FrancisBanville** [comment]
> @FrancisBanville Thanks for submitting a well-written paper and test-covered code repository! I'm ready to approve you on many of the review criteria once I get the checklist working [edit: now done]. However, I am also collecting a few questions and issues. These are raised on your repository as issues 166-168:
> 
> * [ ]  [EcoJulia/EcologicalNetworks.jl#166](https://github.com/EcoJulia/EcologicalNetworks.jl/issues/166) - contribution and authorship
> * [ ]  [EcoJulia/EcologicalNetworks.jl#167](https://github.com/EcoJulia/EcologicalNetworks.jl/issues/167) - installation instructions
> * [ ]  [EcoJulia/EcologicalNetworks.jl#168](https://github.com/EcoJulia/EcologicalNetworks.jl/issues/168) - software paper
> 
> I'm aiming to raise small issues, each relating to one or more specific JOSS review criteria, to streamline the editing and approval process.

Thank you for your helpful review @kellykochanski, and sorry for the late reply! 

We have made some changes to the manuscript (see branch [`joss-article-review1`](https://github.com/EcoJulia/EcologicalNetworks.jl/tree/joss-article-review1)) and commented on your issues. Please do not hesitate to contact us if you have any questions or if you need further detail!

**Comment by arbennett** [comment]
@KristinaRiemer - sorry for the slow review. I think my review is now complete.

@FrancisBanville - thanks for this submission. The paper is well written and covers all of the required bases (I just re-looked at it in the revised branch, and also really like the added diagram). Your example use cases are very nice and prove this is robust and mature software. The code quality, from my quick, shallow dive, is really good and I like how you've described your type system hierarchy, which definitely seems to be a boon for Julia. The documentation that you've written up is also quite clean and slick, and provides both technical as well as intuitive aspects of your software design. I only have two minor considerations that I would like to see addressed before accepting this for submission. They are:

- [ ] [ JOSS: EcoJulia link doesn't work. #170 ](https://github.com/EcoJulia/EcologicalNetworks.jl/issues/170)
- [ ] [ JOSS: Include code example in docs #171 ](https://github.com/EcoJulia/EcologicalNetworks.jl/issues/171)

I also was unclear on the contribution and authorship question brought up by @kellykochanski - perhaps @KristinaRiemer or @danielskatz could chime in on this? To me, the response in [#166](https://github.com/EcoJulia/EcologicalNetworks.jl/issues/166) seems reasonable and I'm happy with it.

**Comment by FrancisBanville** [comment]
Thanks for your review @arbennett!

We changed the defective link in the revised paper (branch `joss-article-review1`), and included a code example in the documentation of our package. We also recently changed the look of our conceptual figure to make it slightly more attractive.

**Comment by KristinaRiemer** [comment]
Hi @arbennett. With regards to the authorship question, one of the authors had previously been the only contributor to the code base, while the submitting author and the third additional author had not. Based on the comments in [#166](https://github.com/EcoJulia/EcologicalNetworks.jl/issues/166) from the authors, all of their contributions seem more than sufficient for authorship as we require at JOSS. Does that make sense? 

@kellykochanski it seems that the authors have addressed your feedback in [#167](https://github.com/EcoJulia/EcologicalNetworks.jl/issues/167) and [#168](https://github.com/EcoJulia/EcologicalNetworks.jl/issues/168), if you are able to follow up with those and continue your review? 

Please let me know if anyone has additional questions!

**Comment by arbennett** [comment]
@KristinaRiemer perfect, thanks! With that, I am happy to accept this paper!

**Comment by KristinaRiemer** [comment]
Hi all! Hopefully everyone had a good holiday season. It looks like @arbennett has finished his review of this software. For @kellykochanski's, there are a few items left on the checklist and also two issues (167 and 168) open in the software repo. Is there anything blocking your work or anything I can do to help move this forward?

**Comment by tpoisot** [comment]
Hi @KristinaRiemer @kellykochanski  - is there something we can do to help with the next steps?

**Comment by KristinaRiemer** [comment]
Thanks for following up @tpoisot. I pinged @kellykochanski via email to check in on the status of their review.

**Comment by KristinaRiemer** [comment]
Hi @kellykochanski, I'm not sure if I used an incorrect email address for you, just checking in on your review of this software?

**Comment by tpoisot** [comment]
Hi @KristinaRiemer - is there something we can do to help with the paper? Do you want suggestions for another reviewer?

**Comment by KristinaRiemer** [comment]
@tpoisot yes, I think at this point we should look for another reviewer. Hopefully @kellykochanski is doing alright! 

If you have suggestions of reviewers with sufficient expertise that adhere to the [JOSS conflict of interest](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) guidelines, that would be great! I will also check for reviewers from our JOSS list.

**Comment by tpoisot** [comment]
@KristinaRiemer all the people I would think of from the top of my head have COI - but I can think about it some more.

That being said, my understanding is that @kellykochanski opened a number of issues on the repo as part of their review, 

EcoJulia/EcologicalNetworks.jl#166 - contribution and authorship
EcoJulia/EcologicalNetworks.jl#167 - installation instructions
EcoJulia/EcologicalNetworks.jl#168 - software paper

and that @FrancisBanville addressed these comments with modifications. Could you confirm that the responses are satisfactory, and given that we've had another review with all comments resolved, can you make an editorial decision based on this?

**Comment by KristinaRiemer** [comment]
Hi @FrancisBanville & @tpoisot. Thank you for your patience, some folks are reaching out to see if they can get in contact with @kellykochanski.

**Comment by tpoisot** [comment]
Hi @KristinaRiemer - just checking-in, have you got any news? We'd like to use this paper as evidence that we are making progress on these tools for a grant, and as the submission deadline is soon, it would really help to have a decision, or comments to address in order to get closer to one.

**Comment by KristinaRiemer** [comment]
Hi @tpoisot. Thanks for being patient with this! We still have not been able to get in touch with @kellykochanski. So at this point, I'm going to finish out her review for her and we'll try to to wrap this up quickly, hopefully by the end of this week. Does that sound okay?

**Comment by tpoisot** [comment]
Perfect! Thanks a lot!!!

**Comment by KristinaRiemer** [comment]
Okay, I finished up the review started by @kellykochanski and everything looks good! I especially like the diagram of the package workflow in the paper. Are you leaving the paper in the `joss-article-review1` branch? 

Otherwise, will say this paper is accepted. We'll have a few more steps to go through, including a last review of the paper itself and getting a DOI.

**Comment by KristinaRiemer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2721 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by KristinaRiemer** [comment]
@whedon generate pdf from branch joss-article-review1

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-article-review1. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02721/joss.02721/10.21105.joss.02721.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02721/joss.02721/10.21105.joss.02721.pdf) :page_facing_up: :point_left:

**Comment by FrancisBanville** [comment]
Great, thank you @KristinaRiemer!

**Comment by KristinaRiemer** [comment]
I'm not sure why that's not working, do I need to specify the branch there too @kyleniemeyer?

**Comment by KristinaRiemer** [comment]
@whedon check references from branch joss-article-review1

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-article-review1
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevE.76.066102 is OK
- 10.1073/pnas.1633576100 is OK
- 10.5281/ZENODO.889971 is OK
- 10.1111/brv.12433 is OK
- 10.1046/j.1461-0248.2002.00354.x is OK
- 10.1073/pnas.192407699 is OK
- 10.1111/2041-210X.12458 is OK
- 10.1111/j.1461-0248.2005.00868.x is OK
- 10.1146/annurev-ecolsys-012220-120819 is OK
- 10.1111/2041-210X.12005 is OK
- 10.1016/j.patter.2020.100079 is OK
- 10.1073/pnas.0601602103 is OK
- 10.1111/ecog.04310 is OK
- 10.1111/2041-210X.12468 is OK
- 10.7717/peerj.251 is OK
- 10.1038/ncomms2422 is OK
- 10.1111/jbi.12015 is OK

MISSING DOIs

- 10.1111/j.1365-2656.2010.01688.x may be a valid DOI for title: Nestedness versus Modularity in Ecological Networks: Two Sides of the Same Coin?

INVALID DOIs

- None
```

**Comment by KristinaRiemer** [comment]
Everything in the paper looks good except a couple of the references. Could you edit the Lightgraph reference so that the other contributors doesn't look like an author? And I think the DOI for the "Nestedness versus modularity in ecological networks: two sides of the same coin?" should be changed to https://doi.org/10.1111/j.1365-2656.2010.01688.x, so it doesn't show up as missing?

**Comment by FrancisBanville** [comment]
Thanks for pointing that out @KristinaRiemer! I fixed these two references.

**Comment by KristinaRiemer** [comment]
@whedon generate pdf from branch joss-article-review1

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-article-review1. Reticulating splines etc...
```

**Comment by KristinaRiemer** [comment]
@whedon check references from branch joss-article-review1

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-article-review1
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02721/joss.02721/10.21105.joss.02721.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02721/joss.02721/10.21105.joss.02721.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevE.76.066102 is OK
- 10.1073/pnas.1633576100 is OK
- 10.5281/ZENODO.889971 is OK
- 10.1111/brv.12433 is OK
- 10.1046/j.1461-0248.2002.00354.x is OK
- 10.1073/pnas.192407699 is OK
- 10.1111/2041-210X.12458 is OK
- 10.1111/j.1461-0248.2005.00868.x is OK
- 10.1111/j.1365-2656.2010.01688.x is OK
- 10.1146/annurev-ecolsys-012220-120819 is OK
- 10.1111/2041-210X.12005 is OK
- 10.1016/j.patter.2020.100079 is OK
- 10.1073/pnas.0601602103 is OK
- 10.1111/ecog.04310 is OK
- 10.1111/2041-210X.12468 is OK
- 10.7717/peerj.251 is OK
- 10.1038/ncomms2422 is OK
- 10.1111/jbi.12015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by KristinaRiemer** [comment]
That looks great, thanks for doing that!

The next steps are to: 1) generate a new tagged release on GitHub and 2) archive the code (on Zenodo, figshare, institutional repository, etc.) to generate a DOI. If you can post the tag version and a link to the DOI here when you're done please.

**Comment by FrancisBanville** [comment]
Hello @KristinaRiemer,

**Comment by FrancisBanville** [comment]
Hello @KristinaRiemer,

**Comment by FrancisBanville** [comment]
Hello @KristinaRiemer,
The tagged versions are [v0.4.3 for EcologicalNetworks.jl ](https://github.com/EcoJulia/EcologicalNetworks.jl/releases/tag/v0.4.3) and [v0.3.1 for Mangal.jl](https://github.com/EcoJulia/Mangal.jl/releases/tag/v0.3.1).
We archived our repositories and the code to reproduce our paper on Zenodo [at this link](https://zenodo.org/record/4716483#.YIb5mJBKiM9).

Please let me know if everything is okay.
Thank you!

**Comment by KristinaRiemer** [comment]
Great, I'll use the EcologicalNetworks version here. Could you change the Zenodo title to match the software paper title?

**Comment by KristinaRiemer** [comment]
@whedon set v0.4.3 as version

**Comment by whedon** [comment]
OK. v0.4.3 is the version.

**Comment by tpoisot** [comment]
Hi @KristinaRiemer - is there a thing we need to do at this point?

**Comment by KristinaRiemer** [comment]
Oh, sorry, I didn't see that the Zenodo title was changed! Thanks for doing that @FrancisBanville.

**Comment by KristinaRiemer** [comment]
@whedon set 10.5281/zenodo.4716483 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4716483" target="_blank">10.5281/zenodo.4716483</a> is the archive.

**Comment by KristinaRiemer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2721 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by KristinaRiemer** [comment]
@whedon accept from branch joss-article-review1

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevE.76.066102 is OK
- 10.1073/pnas.1633576100 is OK
- 10.5281/ZENODO.889971 is OK
- 10.1111/brv.12433 is OK
- 10.1046/j.1461-0248.2002.00354.x is OK
- 10.1073/pnas.192407699 is OK
- 10.1111/2041-210X.12458 is OK
- 10.1111/j.1461-0248.2005.00868.x is OK
- 10.1111/j.1365-2656.2010.01688.x is OK
- 10.1146/annurev-ecolsys-012220-120819 is OK
- 10.1111/2041-210X.12005 is OK
- 10.1016/j.patter.2020.100079 is OK
- 10.1073/pnas.0601602103 is OK
- 10.1111/ecog.04310 is OK
- 10.1111/2041-210X.12468 is OK
- 10.7717/peerj.251 is OK
- 10.1038/ncomms2422 is OK
- 10.1111/jbi.12015 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2279

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2279, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss-article-review1 
```

**Comment by tpoisot** [comment]
Proofs are :+1:

**Comment by KristinaRiemer** [comment]
For the last step, an EiC will do the final approval, and then it will be published!

**Comment by kthyng** [comment]
looks good!

**Comment by kthyng** [comment]
@whedon accept deposit=true from branch joss-article-review1

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1389945882959917057) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2280
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02721](https://doi.org/10.21105/joss.02721)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @FrancisBanville! Many thanks to editor @KristinaRiemer and reviewers @kellykochanski and @arbennett for your time, hard work, and expertise!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02721/status.svg)](https://doi.org/10.21105/joss.02721)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02721">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02721/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02721/status.svg
   :target: https://doi.org/10.21105/joss.02721
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02721/status.svg)](https://doi.org/10.21105/joss.02721)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by FrancisBanville** [comment]
Great, thank you so much @kthyng, @KristinaRiemer, @kellykochanski, and @arbennett for your time and useful comments! 🎉
