### ISSUE TITLE
[REVIEW]: RCaller: A Java package for interfacing R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2722]
**Submitting author:** @jbytecode (<a href="http://orcid.org/0000-0002-9402-1982">Mehmet Hakan Satman</a>)
**Repository:** <a href="https://github.com/jbytecode/rcaller/" target ="_blank">https://github.com/jbytecode/rcaller/</a>
**Version:** v3.0.3
**Editor:** @mikldk
**Reviewer:** @xin-huang, @nthomasCUBE
**Archive:** <a href="https://doi.org/10.5281/zenodo.4189769" target="_blank">10.5281/zenodo.4189769</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/de28eed555632371f4dcbe82efce5075/status.svg)](https://joss.theoj.org/papers/de28eed555632371f4dcbe82efce5075)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/de28eed555632371f4dcbe82efce5075"><img src="https://joss.theoj.org/papers/de28eed555632371f4dcbe82efce5075/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/de28eed555632371f4dcbe82efce5075/status.svg)](https://joss.theoj.org/papers/de28eed555632371f4dcbe82efce5075)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jbytecode/rcaller/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@xin-huang & @nthomasCUBE, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mikldk know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jbytecode/rcaller/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jbytecode) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jbytecode/rcaller/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jbytecode) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @xin-huang, @nthomasCUBE it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.9734/bjmcs/2014/10902 is OK
- 10.1007/s00180-008-0132-x is OK
- 10.1145/3328433.3328458 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@xin-huang, @nthomasCUBE: Thanks for agreeing to review. Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If possible create issues (and cross-reference) in the submission's repository to avoid too specific discussions in this review thread. 

If you have any questions or concerns please let me know.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@xin-huang, @nthomasCUBE: I'm just checking in to hear if everything is progressing or is there is anything you need help to?

**Comment by xin-huang** [comment]
Hi @mikldk, I am preparing for a conference on 26th. I will finish the review after that.

**Comment by nthomasCUBE** [comment]
Hi @mikldk I will try to continue and finish by end of next week

**Comment by nthomasCUBE** [comment]
added new issue for updating example in the manuscript
https://github.com/jbytecode/rcaller/issues/43#issuecomment-710939070

**Comment by nthomasCUBE** [comment]
i am done with reviewing: seems all use cases worked in Eclipse, great tool

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
> i am done with reviewing: seems all use cases worked in Eclipse, great tool

Dear reviewer @nthomasCUBE , I corrected the example as you mentioned in the issue and the compiled manuscript is above. Thank you for your comment.

**Comment by nthomasCUBE** [comment]
> > i am done with reviewing: seems all use cases worked in Eclipse, great tool
> 
> Dear reviewer @nthomasCUBE , I corrected the example as you mentioned in the issue and the compiled manuscript is above. Thank you for your comment.

many thanks!

**Comment by mikldk** [comment]
@xin-huang: What is the status with your review?

**Comment by xin-huang** [comment]
Hi @mikldk I just finished my presentation. I will complete the review by the end of the week. Thanks!

**Comment by xin-huang** [comment]
The authors implemented an interesting tool for Java programmers to use R codes inside Java, which may be helpful for Java programmers to use tremendous statistical tools in R. However, I feel the authors could improve their documentation and software paper and make them more user-friendly. I have open two issues (https://github.com/jbytecode/rcaller/issues/54 and https://github.com/jbytecode/rcaller/issues/55) in the repo. I hope the authors could address my concerns.
Besides, although the authors did not mention performance in the software paper, they discussed this issue in [the manual](https://raw.githubusercontent.com/jbytecode/rcaller/master/doc/rcaller3/rcaller3.pdf). Therefore, I suggest the authors release their codes for the benchmark, so that users can verify the performance issue more easily.

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
Dear reviewer @xin-huang ,

I think I have completed all the changes you suggested. I also made explanations for each of your suggestions in the issues.

Regards.

**Comment by xin-huang** [comment]
Hi @mikldk 
The authors have addressed my concerns. I have no further comments.

**Comment by mikldk** [comment]
@jbytecode :

* Please remove "3.0" from title of the paper
* Please have a final read though of the paper, checking language etc.
* Have a final check of the proofs with `@whedon generate pdf`
* Please make a tagged release and archive (e.g. with [Zenodo](https://zenodo.org/)) as described [here](<https://joss.readthedocs.io/en/latest/submitting.html#the-review-process>), and report the version number and archive DOI in this thread. Please verify that the archive deposit has the correct metadata (title and author list), or edit these if that is not the case.

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
Dear editor @mikldk ,

1. The term 3.0 was removed from the title.

2 - 3. The compiled pdf seems to be okay.

3. The tagged revision is 3.0.3 and the DOI is [https://zenodo.org/badge/doi/10.5281/zenodo.4189769.svg](https://zenodo.org/badge/doi/10.5281/zenodo.4189769.svg)

The fetched metadata seems okay.

**Comment by mikldk** [comment]
@whedon set 10.5281/zenodo.4189769 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4189769" target="_blank">10.5281/zenodo.4189769</a> is the archive.

**Comment by mikldk** [comment]
@whedon set v3.0.3 as version

**Comment by whedon** [comment]
OK. v3.0.3 is the version.

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.9734/bjmcs/2014/10902 is OK
- 10.1007/s00180-008-0132-x is OK
- 10.1145/3328433.3328458 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mikldk** [comment]
@jbytecode: The metadata at Zenodo is not okay. The title nor the authors match those of the paper. Please check thoroughly. Please also carefully read the paper and verify that everything is in order and confirm.

**Comment by jbytecode** [comment]
Dear editor @mikldk 

- I corrected the authors list and the title in [Zenodo](https://zenodo.org/record/4189769#.X6EYO1MzY_V).

- I made a small correction in the summary, have you got any suggestions for me to correct anything else? It is okay to me.

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.9734/bjmcs/2014/10902 is OK
- 10.1007/s00180-008-0132-x is OK
- 10.1145/3328433.3328458 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1891

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1891, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@jbytecode I'm helping to process the last steps for this paper. It looks like the paper needs a bit of work to improve language. Can you please consider the points below. 

@mikldk could you also help review the paper, since R/Java are not my expertise I want to make sure I did not misunderstood anything. 

- [ ] Please add (city and) country information to all affiliations

- [ ] Please review this sentence: "Addition to the previous revisions, RCaller 3.0 implements the scripting API of Java in which the R function calls and data transfers are performed in a standard way as in the way of calling other scripting languages in Java.", it does not read well and the "Addition" part seems incorrect. Consider rephrasing to (if I understood it correctly): "Unlike previous RCaller versions, RCaller 3.0 implements the scripting API of Java, ensuring R function calls and data transfers are performed in a standard way, as is usual for other scripting languages in Java."

- [ ] Check this sentence (use in instead of on): "Nowadays, the interest ~~on~~ in statistical computation and data analysis increased the popularity of some programming languages such as R, Python, and Julia.", also it sounds a bit awkward, would this be better: "Nowadays, increased interest in statistical computation and data analysis has enhanced the popularity of some programming languages such as R, Python, and Julia."

- [ ] Please rephrase this sentence: " On the other side, many main frame languages are adopted for more specific tasks in server-side or the general-purpose use in several platforms."

- [ ] Check this sentence "These huge collection of computation tools are not directly accessible...", it looks like it should probably read "This huge collection of computation tools is not directly accessible..."

- [ ] Rephrase this sentence (perhaps it needs commas): "Previous works showed that the performance of the library is suitable for more cases and studies with moderate data sets can be handled in reasonable times"

- [ ] Consider rephrasing "After being introduced in paper....  are implemented besides ", to something like "Following its first publication.... have been implemented, as well as,... "

- [ ] Suggestion: "matured" -> "mature"

- [ ] Add comma/rephrase: "...and function optimization besides other research tools" -> "...and function optimization, as well as other research tools". Also, if you were to say: "R has many well-tested and mature packages, [including] for...", then you could leave "as well as other research tools" out which sounds less vague. 

- [ ] Suggestion "....that R serves... " -> "....that R provides... "

- [ ] "free microservice solution" -> "a free microservice solution".

**Comment by jbytecode** [comment]
Dear editor @Kevin-Mattheus-Moerman 

Thank you very much for your effort on correcting language although you are not obliged to. I made the corrections as suggested above. However, in (2) It is not "unlike" but a "new feature" so other kind of calling schemes are still correct. I changed it to 

`In addition to previous RCaller versions, RCaller 3.0 implements the scripting API of Java, ensuring R function calls and data transfers are performed in a standard way, as is usual for other scripting languages in Java.`

Regards.

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@jbytecode I ticked some of the boxes. Some points still remaining. @mikldk can you check some of these sentences and perhaps shed light on how best to rephrase them?

**Comment by jbytecode** [comment]
Dear editor @Kevin-Mattheus-Moerman ,

Sorry to take your precious time for language corrections. Here is my effort to correct unchecked suggestions:

@whedon generate pdf

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@Kevin-Mattheus-Moerman, thanks for catching these. Below you will find my comments to the unchecked boxes:

- [ ] Please rephrase this sentence: " On the other side, many main frame languages are adopted for more specific tasks in server-side or the general-purpose use in several platforms."
  - Change *main frame* to *mainframe* (?) and rephrasing to improve understanding; maybe include the term *domain-specific language*

- [x] Check this sentence "These huge collection of computation tools are not directly accessible...", it looks like it should probably read "This huge collection of computation tools is not directly accessible..."
  - Already fixed from what I can see.

- [x] Add comma/rephrase: "...and function optimization besides other research tools" -> "...and function optimization, as well as other research tools". Also, if you were to say: "R has many well-tested and mature packages, [including] for...", then you could leave "as well as other research tools" out which sounds less vague. 
  - Already fixed from what I can see.

**Comment by jbytecode** [comment]
Dear editor @mikldk,

The term domain-specific is a little bit a 'constricted concept', like SQL, however I corrected main frame to mainframe

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02722/joss.02722/10.21105.joss.02722.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1326119009583067137) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1903
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02722](https://doi.org/10.21105/joss.02722)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by jbytecode** [comment]
I would like to thank everyone who contributed to the editorial process. It was a great experience to have an article published on JOSS. 

All the best.

@Kevin-Mattheus-Moerman @mikldk @xin-huang @nthomasCUBE @Kopilov

**Comment by arfon** [comment]
@xin-huang, @nthomasCUBE - many thanks for your reviews here and to @mikldk for editing this submission ✨ 

 @jbytecode - your paper is now accepted and published in JOSS :zap::rocket::boom:
