### ISSUE TITLE
[PRE REVIEW]: rdataretriever: An R package for downloading, cleaning, and installing publicly available datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2724]
**Submitting author:** @henrykironde (<a href="http://orcid.org/0000-0001-7105-5808">henry senyondo</a>)
**Repository:** <a href="https://github.com/ropensci/rdataretriever" target ="_blank">https://github.com/ropensci/rdataretriever</a>
**Version:** v3.0.0
**Editor:** @fboehm
**Reviewers:** @rmhogervorst, @jsgalan
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @henrykironde. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @bstabler.

@henrykironde if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.15 s (117.0 files/s, 12900.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                7             87            423            692
Markdown                         5            165              0            424
YAML                             3             16             17             76
Dockerfile                       1             12             11             36
TeX                              1              1              0             16
Bourne Shell                     1              2              1              5
-------------------------------------------------------------------------------
SUM:                            18            283            452           1249
-------------------------------------------------------------------------------


Statistical information for the repository 'd543acce22dadce4df534719' was
gathered on 2020/10/06.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1371/journal.pone.0065848 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02724/joss.02724/10.21105.joss.02724.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02724/joss.02724/10.21105.joss.02724.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by kthyng** [comment]
Hi @henrykironde! Thank you for your submission. I have flagged your submission as possibly out of scope due to its small size. Please see details on "substantial scholarly effort": https://joss.readthedocs.io/en/latest/review_criteria.html#substantial-scholarly-effort. The editorial board will consider your submission to make the decision together in the next week or two. If there is any additional information you'd like to provide, please feel free to do so in this pre-review issue.

**Comment by ethanwhite** [comment]
Thanks for the update @kthyng. FYI we did submit a pre-submission inquiry about a month ago:
https://github.com/openjournals/joss/issues/796

**Comment by kthyng** [comment]
@ethanwhite Thank you for including that information! We'll use it as part of our decision-making.

**Comment by danielskatz** [comment]
@henrykironde & @ethanwhite - Has this software gone through rOpenSci review?

**Comment by henrykironde** [comment]
It is under rOpenSci, so I believe it was reviewed during the early versions before I became the maintainer. `https://github.com/ropensci/rdataretriever`

**Comment by ethanwhite** [comment]
@danielskatz - the project's involvement in rOpenSci predates the creation of the rOpenSci review process so it has not formally been through there review process.

**Comment by danielskatz** [comment]
👋 @fboehm - are you willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@henrykironde - would you be willing to write a vignette for the R package? I'm interested in seeing the package used in practice to access an interesting data set. How do I, as a user, know which data sets are available? Maybe a vignette could list the currently available data sets and demonstrate something interesting with one or two data sets. Thank you!

**Comment by henrykironde** [comment]
Yes we are going to create the vignette

**Comment by fboehm** [comment]
Thanks, @henrykironde ! When you've had a chance to create the vignette, please let me know. We can then find reviewers for your submission. If you have questions or concerns, please let me know. I'm here to assist you. Thanks again!

**Comment by henrykironde** [comment]
@fboehm the vignettes are in.

**Comment by fboehm** [comment]
Thanks so much, @henrykironde ! I'll now search for reviewers. Once I find them, we can begin the official review.

**Comment by fboehm** [comment]
@whedon add @rmhogervorst as reviewer

**Comment by whedon** [comment]
OK, @rmhogervorst is now a reviewer

**Comment by fboehm** [comment]
@whedon add @jsgalan as reviewer

**Comment by whedon** [comment]
OK, @jsgalan is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2800.
