### ISSUE TITLE
[PRE REVIEW]: GIMS: Graphical Interface for Materials Simulations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2725]
**Submitting author:** @kokookster (<a href="http://orcid.org/0000-0003-1066-6909">Sebastian Kokott</a>)
**Repository:** <a href="https://gitlab.com/gims-developers/gims" target ="_blank">https://gitlab.com/gims-developers/gims</a>
**Version:** 1.0.0
**Editor:** @jgostick
**Reviewers:** @marshallmcdonnell, @arose, @marshallmcdonnell
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kokookster. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jgostick.

@kokookster if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.19 s (213.9 files/s, 42462.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                            114             47              0          31232
JavaScript                      59           2528           3339           8414
CSS                              2            304            113           1012
Python                          13            198            124            716
SVG                              5              5              5            708
reStructuredText                18            300             37            601
Markdown                         3            104              0            280
TeX                              1              8              0             82
HTML                             2             18              2             59
JSON                            31              0              0             57
YAML                             1              5              1             52
DOS Batch                        1              8              1             26
Bourne Shell                     2              3              1             17
make                             2              6              7             13
-------------------------------------------------------------------------------
SUM:                           254           3534           3630          43269
-------------------------------------------------------------------------------


Statistical information for the repository '2d54480f1e6de1a3c4d67036' was
gathered on 2020/10/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Iker Hurtado                   277        155463         100334           89.85
Sebastian Kokott               118          8123          20765           10.15

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Iker Hurtado              11130            7.2          9.7               27.54
Sebastian Kokott           4189           51.6          3.9               15.49
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/j.cpc.2009.06.022 may be a valid DOI for title: Ab initio molecular simulations with numeric atom-centered orbitals
- 10.1088/0953-8984/26/36/363202 may be a valid DOI for title: Exciting: a full-potential all-electron package implementing density-functional theory and many-body perturbation theory
- 10.1016/j.commatsci.2010.05.010 may be a valid DOI for title: High-throughput electronic band structure calculations: Challenges and tools
- 10.1007/978-1-4842-2677-3_5 may be a valid DOI for title: pytest

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02725/joss.02725/10.21105.joss.02725.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02725/joss.02725/10.21105.joss.02725.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @Kokookster! Thank you for your submission! 

I would like to better understand what part of your repository is specifically your software vs. dependencies. For example, could you give a short overview of what of the 8000 lines of Javascript are written by you and your co-authors?

**Comment by Kokookster** [comment]
Hi @kthyng ,

Only the files in the `client/libs` folder (currently only `OrthographicTrackballControls.js`) is _not_ written by any of the project authors. The names of the authors are included in the lib-files.

All other javascript lines are the original work of the project authors. (Hopefully) all files carry the author name in the file header.

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by kthyng** [comment]
Thank you for the information @Kokookster! 

And thanks to @jgostick for volunteering as editor.

**Comment by jgostick** [comment]
@arose, you are listed as a potential volunteer reviewer for JOSS, and your subject area not only includes MD, but "molecular graphics" as well.  Please let me know by adding to this issue thread whether you're able to review this contribution.

**Comment by jgostick** [comment]
@marshallmcdonnell, you are listed in our database of potential volunteers for JOSS, though it seems you've not had the privilege of doing one yet.  Your expertise in MD and web applications is highly relevant to this submission.  Please let me know by adding a comment to this issue whether you're able to review this contributions.

**Comment by marshallmcdonnell** [comment]
@jgostick I'd be very happy to review this contribution! Upon a cursory look, I am very interested in the submission!

**Comment by jgostick** [comment]
@whedon assign @marshallmcdonnell as reviewer

**Comment by whedon** [comment]
OK, @marshallmcdonnell is now a reviewer

**Comment by jgostick** [comment]
Thanks @marshallmcdonnell I'll start the reviewer soon once I find a second reviewer, then  you can click the 'check boxes', but in the meantime feel free to start evaluating it!

**Comment by Kokookster** [comment]
Hi @jgostick, @marshallmcdonnell,
Looking forward to going through this review process guided by you!

**Comment by arose** [comment]
@jgostick happy to review this

**Comment by jgostick** [comment]
Super!  Let the fun begin.

**Comment by jgostick** [comment]
@whedon add @arose as reviewer

**Comment by whedon** [comment]
OK, @arose is now a reviewer

**Comment by jgostick** [comment]
@whedon add @marshallmcdonnell as reviewer

**Comment by whedon** [comment]
OK, @marshallmcdonnell is now a reviewer

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2767.
