### ISSUE TITLE
[PRE REVIEW]: (py)oscode: fast solutions of oscillatory ODEs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2729]
**Submitting author:** @fruzsinaagocs (<a href="http://orcid.org/0000-0002-1763-5884">Fruzsina Julia Agocs</a>)
**Repository:** <a href="https://github.com/fruzsinaagocs/oscode" target ="_blank">https://github.com/fruzsinaagocs/oscode</a>
**Version:** v1.0.0
**Editor:** @melissawm
**Reviewers:** @jakryd, @dlfivefifty
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @fruzsinaagocs. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kyleniemeyer.

@fruzsinaagocs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by kthyng** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevResearch.2.013030 is OK
- 10.1103/PhysRevD.101.043517 is OK
- 10.1103/PhysRevD.100.123517 is OK
- 10.1103/PhysRevD.102.023507 is OK
- 10.1137/0718030 is OK
- 10.1017/S0962492900002750 is OK
- 10.1137/1.9781611975123 is OK
- 10.1007/bf03322583 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.acha.2016.05.002 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.46 s (207.6 files/s, 94585.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   278          13853          21772          80558
SVG                              1              0              0            715
Jupyter Notebook                 3              0          18238            568
Python                           8            126            200            428
reStructuredText                 5            256            202            363
C++                              2             35            140            236
TeX                              1             12              0            148
Markdown                         1             16              0            102
Dockerfile                       1              6              5             28
YAML                             2              5             12             24
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                           303          14313          40575          83179
-------------------------------------------------------------------------------


Statistical information for the repository '186d6b688622ba7eb8005bb3' was
gathered on 2020/10/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Fruzsina Agocs                   9           309             80            0.11
agocsfruzsina                    5          1800            351            0.62
fruzsinaagocs                   49        231063         115393           99.27

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Fruzsina Agocs              215           69.6          1.9               50.23
fruzsinaagocs            117133           50.7          0.5               19.32
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.49 s (202.9 files/s, 92454.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   278          13853          21772          80558
SVG                              1              0              0            715
Jupyter Notebook                 3              0          18238            568
Python                           8            126            200            428
reStructuredText                 5            256            202            363
C++                              2             35            140            236
TeX                              1             12              0            148
Markdown                         1             16              0            102
Dockerfile                       1              6              5             28
YAML                             2              5             12             24
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                           303          14313          40575          83179
-------------------------------------------------------------------------------


Statistical information for the repository 'cfa0d911633dbc0de39b8fa9' was
gathered on 2020/10/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Fruzsina Agocs                   9           309             80            0.11
agocsfruzsina                    5          1800            351            0.62
fruzsinaagocs                   49        231063         115393           99.27

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Fruzsina Agocs              215           69.6          1.9               50.23
fruzsinaagocs            117133           50.7          0.5               19.32
```

**Comment by fruzsinaagocs** [comment]
Hi @kthyng  :wave: 
The invalid DOI whedon discovered has been corrected.
I think the following people could potentially be reviewers:
- lgarrison
- danfortunato

From the volunteer list:
- harpolea
- danehkar
- fhorrobin
- rgmyr
- bhajay
- solanpaa
- ziotom78
- corentin-dev
- jakryd

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02729/joss.02729/10.21105.joss.02729.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02729/joss.02729/10.21105.joss.02729.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@melissawm Could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @melissawm as editor

**Comment by whedon** [comment]
@melissawm has been invited to edit this submission.

**Comment by melissawm** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by melissawm** [comment]
:wave: @danehkar, @fhorrobin, @rgmyr would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by melissawm** [comment]
Hello @bhajay, @solanpaa would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by melissawm** [comment]
Hello, @corentin-dev, @jakryd would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Let me know if you have need any more information. Thanks!

**Comment by melissawm** [comment]
Hello @fruzsinaagocs, seems like we're having some trouble finding reviewers. I'll try and ping them again via email, to see if we have better luck. In the meantime, if you have any other suggestions please let me know. Thanks!

**Comment by jakryd** [comment]
Hello, I'm happy to review this submission.

**Comment by fruzsinaagocs** [comment]
Having gone through the volunteer list again, and I think the following people could be suitable reviewers:
- jgoldfar
- dawbarton
- adam-m-jcbs
- mstimberg

I've also emailed someone not on the volunteer list to ask for a review, I'm waiting for his response.

**Comment by melissawm** [comment]
Thank you, @jakryd! I'll add you as a reviewer but I won't start the review process just yet because we need another reviewer to start. As soon as that happens we'll move to the review issue.

**Comment by melissawm** [comment]
@whedon assign @jakryd as reviewer

**Comment by whedon** [comment]
OK, @jakryd is now a reviewer

**Comment by melissawm** [comment]
Hello @jgoldfar! Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Let me know if you need any more information. Thanks!

**Comment by fruzsinaagocs** [comment]
I just had an email reply from dlfivefifty saying he’d be happy to review. @melissawm  can I tag him?

**Comment by melissawm** [comment]
Sure, please do! Thank you! As soon as he comments here I'll assign him as a reviewer.

**Comment by fruzsinaagocs** [comment]
Thank you @dlfivefifty for agreeing to review this, looking forward to hearing your comments.

**Comment by dlfivefifty** [comment]
👍

**Comment by melissawm** [comment]
Hello, @dlfivefifty ! Thank you for agreeing to review this software paper for JOSS! I'll assign you as reviewer, and whedon (our bot) will close this issue and open a new [REVIEW] issue. We'll meet there for the remainder of the process.

**Comment by melissawm** [comment]
@whedon add @dlfivefifty as reviewer

**Comment by whedon** [comment]
OK, @dlfivefifty is now a reviewer

**Comment by melissawm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2830.
