### ISSUE TITLE
[PRE REVIEW]: BioPandas: Working with molecular structures in pandas DataFrames

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#273]
**Submitting author:** @rasbt (<a href="http://orcid.org/0000-0001-6989-4493">Sebastian Raschka</a>)
**Repository:** <a href="https://github.com/rasbt/biopandas" target ="_blank">https://github.com/rasbt/biopandas</a>
**Version:** v2.1.0
**Editor:** @pjotrp
**Reviewer:** @krother

**Author instructions**

Thanks for submitting your paper to JOSS @rasbt. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rasbt if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @pjotrp - would you be willing to edit this submission?

**Comment by rasbt** [comment]
> @rasbt if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, this list of people have already agreed to review for JOSS and may be suitable for this submission.

Looking at the list, I think @krother @genomematt and @ctb are good candidates! Anyone of you interested and open to review the biopandas package?

**Comment by krother** [comment]
me me me!!!

**Comment by krother** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by krother** [comment]
@whedon assign @krother as reviewer

**Comment by whedon** [comment]
I'm sorry @krother, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by krother** [comment]
I want to review this paper

**Comment by rasbt** [comment]
Wow, that was quick! Thanks @krother I really appreciate it :)

**Comment by arfon** [comment]
@whedon assign @krother as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @krother

**Comment by arfon** [comment]
@krother - let's wait until @pjotrp is able to edit this submission before getting started.

**Comment by pjotrp** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/279. Feel free to close this issue now!
