### ISSUE TITLE
[PRE REVIEW]: CoPro: a data-driven model for conflict risk projections

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2730]
**Submitting author:** @JannisHoch (<a href="http://orcid.org/0000-0003-3570-6436">Jannis Hoch</a>)
**Repository:** <a href="https://github.com/JannisHoch/copro" target ="_blank">https://github.com/JannisHoch/copro</a>
**Version:** v0.0.5
**Editor:** @sbenthall
**Reviewers:** @soodoku, @sbenthall
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JannisHoch. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @lorenanicole.

@JannisHoch if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by kthyng** [comment]
@whedon check repository

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02730/joss.02730/10.21105.joss.02730.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02730/joss.02730/10.21105.joss.02730.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.31 s (220.2 files/s, 54302.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              2           1997              7           8196
Python                          20            675            770           1060
reStructuredText                30            194            225            203
Markdown                         3             39              0            124
Jupyter Notebook                 3              0           3185            104
TeX                              1              6              0             72
YAML                             3             11             13             42
DOS Batch                        1              8              1             27
INI                              1              3              3             20
make                             1              4              7             10
JSON                             1              0              0              4
XML                              1              0              0              2
Bourne Shell                     2              0              0              2
-------------------------------------------------------------------------------
SUM:                            69           2937           4211           9866
-------------------------------------------------------------------------------


Statistical information for the repository '51e75d075b85361a693154a1' was
gathered on 2020/10/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ChippChapp                      10           592            251            8.03
Hoch                            20           891            139            9.82
Jannis                         117          4898           3721           82.13
Jannis Hoch                      2             2              0            0.02

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Hoch                        385           43.2          4.4               27.01
Jannis                     2120           43.3          0.9                9.53
```

**Comment by kthyng** [comment]
@lorenanicole could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @lorenanicole as editor

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by lorenanicole** [comment]
I've got two papers in flight. So I'm going to pass for now.

**Comment by kthyng** [comment]
@sbenthall can you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by sbenthall** [comment]
Oh, yeah, I can edit this!

**Comment by sbenthall** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @sbenthall

**Comment by sbenthall** [comment]
@Zac-HD would you be able to review this article?

**Comment by sbenthall** [comment]
@martibosch would you be able to review this article?

**Comment by martibosch** [comment]
Hello @sbenthall,

after going through the README, documentation and example notebooks, I am not sure that the library falls within my expertise (besides my "general" knowledge of the underlying machine learning and GIS involved). Nonetheless, if you do not find other JOSS reviewers that are better suited to the task, I will do my best to review this.

Cheers,
Martí

**Comment by Zac-HD** [comment]
@sbenthall - I'd be happy to do a generic code review, but don't feel I know the domain well enough to review the paper.

**Comment by sbenthall** [comment]
Ok, I will keep reaching out to see if there's somebody more confident with the research substance. Thanks @martibosch and @Zac-HD

**Comment by sbenthall** [comment]
@platipodium would you be able to review this article?

**Comment by sbenthall** [comment]
@akbaritabar Would you be able to review this article?

**Comment by platipodium** [comment]
> @platipodium would you be able to review this article?

I am not an expert in conflict or risk modeling, nor machine learning, so I'd like to deflect this to a more knowledgeable reviewer.   May I suggest marcel.nonnenmacher@hzg.de for machine learning and roland.comier@hzg.de for risk assessment.

On thing I noticed: From the existing ReadtheDocs and ReadMe and associated paper, it is still unclear to me, what the software is good for.  An example output/visualization in the JOSS paper and/or documentation would be helpful to find reviewers, and users.

**Comment by sbenthall** [comment]
Thank you, @platipodium

**Comment by sbenthall** [comment]
@chainsawriot would you be able to review this article?

**Comment by akbaritabar** [comment]
> @akbaritabar Would you be able to review this article?

Thanks for asking dear @sbenthall, I am sorry, but I won't be available.

**Comment by chainsawriot** [comment]
@sbenthall 

Thank you so much for your invitation. I can give it a try, although I am not an expert in Python. If I can get this running, the documentation should have done a good job.

**Comment by sbenthall** [comment]
Ok @chainsawriot Thanks for your reply! I will keep searching for a second reviewer. In the meantime, I wonder if you could check to see if you can feel confident about your review. If so, I'll assign you officially to review. If not, please let me know so I can keep looking.

**Comment by sbenthall** [comment]
@nniiicc Would you be able to review this submission?

**Comment by sbenthall** [comment]
@soodoku would you be able to review this submission?

**Comment by JannisHoch** [comment]
@sbenthall 
thanks for not giving up the search for reviewers!
Not sure whom to contact, but I drafted an updated release of the code. It contains a few minor changes to the code and the JOSS manuscript is not affected by it.

Link to it: https://github.com/JannisHoch/copro/releases/tag/v0.0.6b.

Many thanks and kind regards, Jannis

**Comment by sbenthall** [comment]
Thank you @soodoku ! I will assign you as a reviewer.

**Comment by sbenthall** [comment]
@whedon assign @soodoku as reviewer

**Comment by whedon** [comment]
OK, @soodoku is now a reviewer

**Comment by sbenthall** [comment]
@JannisHoch I believe that updates to the software are encouraged. It's possible that the review will motivate further updates.

This package is actually very much in line with my own research.

@kthyng is it possible for editors to also be reviewers on a piece, or is that a conflict of interest?

**Comment by nniiicc** [comment]
> @nniiicc Would you be able to review this submission?

@sbenthall - sorry I have too many reviews on my plate right now. Agree that it looks promising though.

**Comment by kthyng** [comment]
> @kthyng is it possible for editors to also be reviewers on a piece, or is that a conflict of interest?

Yes that can happen though usually it is done because a reviewer dropped out or similar. If you're really interested in the package, I think it's fine for you to review if you'd like to.

**Comment by soodoku** [comment]
so @kthyng, need some help. there used to be a checklist that i got to tick off. i can't see it here. have the procedures changed?

**Comment by kthyng** [comment]
@soodoku No you’re correct about the checklist. However this is still the pre review not the review issue. @sbenthall will start the actual review issue probably once two reviewers have been secured.

**Comment by soodoku** [comment]
Thanks! Anything for me to do for now?

**Comment by kthyng** [comment]
@soodoku Probably best to just wait for the review issue to start. Thanks!

**Comment by sbenthall** [comment]
@whedon add @sbenthall as reviewer

**Comment by whedon** [comment]
OK, @sbenthall is now a reviewer

**Comment by sbenthall** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2855.
