### ISSUE TITLE
[REVIEW]: GRLC - the Git Repository Linked data api Constructor

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2731]
**Submitting author:** @c-martinez (<a href="http://orcid.org/0000-0001-5565-7577">Carlos Martinez-Ortiz</a>)
**Repository:** <a href="https://github.com/CLARIAH/grlc" target ="_blank">https://github.com/CLARIAH/grlc</a>
**Version:** v1.3.7
**Editor:** @arfon
**Reviewer:** @essepuntato, @alexdma
**Archive:** <a href="https://doi.org/10.5281/zenodo.5644276" target="_blank">10.5281/zenodo.5644276</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/437074e2d77df8c6cbf3bc4e407b3b17/status.svg)](https://joss.theoj.org/papers/437074e2d77df8c6cbf3bc4e407b3b17)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/437074e2d77df8c6cbf3bc4e407b3b17"><img src="https://joss.theoj.org/papers/437074e2d77df8c6cbf3bc4e407b3b17/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/437074e2d77df8c6cbf3bc4e407b3b17/status.svg)](https://joss.theoj.org/papers/437074e2d77df8c6cbf3bc4e407b3b17)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/CLARIAH/grlc" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@essepuntato & @alexdma, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lorenanicole know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CLARIAH/grlc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@c-martinez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CLARIAH/grlc">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@c-martinez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @essepuntato, @alexdma it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18174/505685 is OK

MISSING DOIs

- 10.1007/978-3-030-30796-7_28 may be a valid DOI for title: Easy Web API Development with SPARQL Transformer
- 10.1007/978-3-319-47602-5_48 may be a valid DOI for title: grlc Makes GitHub Taste Like Linked Data APIs
- 10.1007/978-3-319-70407-4_27 may be a valid DOI for title: SPARQL2Git: Transparent SPARQL and Linked Data API Curation via Git
- 10.1007/978-3-319-68204-4_30 may be a valid DOI for title: Automatic Query-Centric API for Routine Access to Linked Data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02731/joss.02731/10.21105.joss.02731.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02731/joss.02731/10.21105.joss.02731.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @essepuntato, @alexdma - happy new year! From the looks of things, neither of you have made any progress on your reviews here. Do you think you might be able to complete your initial review in the next two weeks?

**Comment by alexdma** [comment]
My apologies @arfon - it is certainly no justification that I have moved to a new job and country in the meantime.

I'm trying to work through it but I can't seem to be able to tick any of the checkboxes on my list (code of conduct etc.) - how do I do that? The issue does not seem to be editable.

**Comment by arfon** [comment]
@whedon re-invite @alexdma as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@alexdma please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
> I'm trying to work through it but I can't seem to be able to tick any of the checkboxes on my list (code of conduct etc.) - how do I do that? The issue does not seem to be editable.

Thanks for the update @alexdma. Please accept the invite from @whedon above and then you should be able to update the checklist.

**Comment by alexdma** [comment]
Hi - Does the Softyware paper section of the review checklist refer to the article as found here: https://github.com/openjournals/joss-papers/blob/joss.02731/joss.02731/10.21105.joss.02731.pdf ?

Thanks

**Comment by arfon** [comment]
Yes, that's correct @alexdma

**Comment by alexdma** [comment]
Thank you @arfon - if I have any recommendation regarding that paper, should the issue be filed with the GRLC code repository or somewhere else?

**Comment by arfon** [comment]
@alexdma - please open issues on the associated repository (https://github.com/CLARIAH/grlc) and mention this issue when doing so (https://github.com/openjournals/joss-reviews/issues/2731), that way they will be cross-linked.

**Comment by arfon** [comment]
:wave: @essepuntato - just checking in here - do you need any assistance with your review?

**Comment by lorenanicole** [comment]
@essepuntato just bumping the below to see if you needed anything additional: 

https://github.com/openjournals/joss-reviews/issues/2731#issuecomment-774939456

**Comment by essepuntato** [comment]
Hi @arfon and @lorenanicole,

I really apologies for my silence - strangely, all your messages went to my SPAM folder and I did not notice them until now. Of course, this is not a justification, since I am tremendously late with the review that, honestly, I totally forgot about it. Thus, please accept my sincere apologies for it.

Back to the topic: I won't be able to address it this week due to prior commitments, but you can expect the review by the end of the next week. Apologies again and have a nice day :-)

**Comment by lorenanicole** [comment]
No worries, thank you @essepuntato for the update! Just ping us back on this channel in a week to let us know if you need anything (e.g. more time).

**Comment by arfon** [comment]
:wave: @essepuntato – just checking in here. Do you think you might be able to provide your review in the next couple of weeks?

**Comment by c-martinez** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02731/joss.02731/10.21105.joss.02731.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02731/joss.02731/10.21105.joss.02731.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
I just emailed @essepuntato directly to see when they might be able to complete their review by.

**Comment by essepuntato** [comment]
Hi @arfon, 

Apologies again, and thanks for writing directly to me to remind the review - as before, all the GitHub messages went to the SPAM folder. I've completed my review, and wrote an issue to the authors of the tool with some comments about how to improve some aspects (mainly the accompanying paper).

Have a nice day :-)

**Comment by arfon** [comment]
> Apologies again, and thanks for writing directly to me to remind the review - as before, all the GitHub messages went to the SPAM folder. I've completed my review, and wrote an issue to the authors of the tool with some comments about how to improve some aspects (mainly the accompanying paper).

Wonderful, thank you so much @essepuntato!

**Comment by arfon** [comment]
@c-martinez – how are you getting along here? Have you had a chance to incorporate the feedback from our reviewers?

**Comment by c-martinez** [comment]
Hi @arfon -- we are working on it, but still have a couple of points to address. I think we should be done in the next couple of weeks.

**Comment by arfon** [comment]
@whedon assign me as editor

Unfortunately @lorenanicole is no longer able to edit this submission so I'll be taking over from here.

**Comment by c-martinez** [comment]
Hi @arfon -- it took a bit longer than expected, but we've now addressed the last of @essepuntato 's comments in https://github.com/CLARIAH/grlc/issues/356. Thanks for all the useful feedback!

**Comment by arfon** [comment]
Got it. Thanks @c-martinez. It looks like there are still a couple of issues open on your repo related to the review (e.g., https://github.com/CLARIAH/grlc/issues/311 and https://github.com/CLARIAH/grlc/issues/327). Could you share what your intent here is?

:wave: @essepuntato, @alexdma – could you take a look at the changes that @c-martinez has made and see if you are able to update the remaining checkboxes for the review?

**Comment by alexdma** [comment]
I have updated the reviewer checklist following core issues now solved. Everything checks. Thanks to the authors for all the work done to onboard the advice!

**Comment by arfon** [comment]
@c-martinez – At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by c-martinez** [comment]
Great, thanks @arfon !

I've just made a [release in Zenodo](https://zenodo.org/record/5644276)

I hope everything is as expected?

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.5644276 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5644276" target="_blank">10.5281/zenodo.5644276</a> is the archive.

**Comment by arfon** [comment]
@whedon set v1.3.7 as version

**Comment by whedon** [comment]
OK. v1.3.7 is the version.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18174/505685 is OK
- 10.1016/j.websem.2016.03.003 is OK

MISSING DOIs

- 10.1007/978-3-030-30796-7_28 may be a valid DOI for title: Easy Web API Development with SPARQL Transformer
- 10.1007/978-3-319-47602-5_48 may be a valid DOI for title: grlc Makes GitHub Taste Like Linked Data APIs
- 10.1007/978-3-319-70407-4_27 may be a valid DOI for title: SPARQL2Git: Transparent SPARQL and Linked Data API Curation via Git
- 10.1007/978-3-319-68204-4_30 may be a valid DOI for title: Automatic Query-Centric API for Routine Access to Linked Data

INVALID DOIs

- https://doi.org/10.1016/j.websem.2021.100655 is INVALID because of 'https://doi.org/' prefix
```

**Comment by arfon** [comment]
@c-martinez - could you please check if those DOIs recommended by Whedon are correct, and if so, add them to your BibTeX file? Also, this one `https://doi.org/10.1016/j.websem.2021.100655` should be written as `10.1016/j.websem.2021.100655` in your BibTeX file please.

**Comment by c-martinez** [comment]
Sure no problem -- is a new release necessary after fixing those?

**Comment by arfon** [comment]
> Sure no problem -- is a new release necessary after fixing those?

No, we can just stick with the same release number and Zenodo archive.

**Comment by arfon** [comment]
@whedon check references

**Comment by arfon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2728

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2728, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1456378680863830018) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2729
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02731](https://doi.org/10.21105/joss.02731)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@essepuntato, @alexdma – many thanks for your reviews here and to @lorenanicole for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@c-martinez – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02731/status.svg)](https://doi.org/10.21105/joss.02731)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02731">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02731/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02731/status.svg
   :target: https://doi.org/10.21105/joss.02731
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02731/status.svg)](https://doi.org/10.21105/joss.02731)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
