### ISSUE TITLE
[REVIEW]: pfsspy: A Python package for potential field source surface modelling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2732]
**Submitting author:** @dstansby (<a href="http://orcid.org/0000-0002-1365-1908">David Stansby</a>)
**Repository:** <a href="https://github.com/dstansby/pfsspy" target ="_blank">https://github.com/dstansby/pfsspy</a>
**Version:** v0.6.3
**Editor:** @mbobra
**Reviewer:** @mancellin, @sibirrer
**Archive:** <a href="https://doi.org/10.5281/zenodo.4118975" target="_blank">10.5281/zenodo.4118975</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/795ebd577bda16e2891c446a3ebb5424/status.svg)](https://joss.theoj.org/papers/795ebd577bda16e2891c446a3ebb5424)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/795ebd577bda16e2891c446a3ebb5424"><img src="https://joss.theoj.org/papers/795ebd577bda16e2891c446a3ebb5424/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/795ebd577bda16e2891c446a3ebb5424/status.svg)](https://joss.theoj.org/papers/795ebd577bda16e2891c446a3ebb5424)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dstansby/pfsspy/tree/joss-paper" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mancellin & @sibirrer, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dstansby/pfsspy/tree/joss-paper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dstansby) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dstansby/pfsspy/tree/joss-paper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dstansby) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mancellin, @sibirrer it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2732 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - d767e2c6b691b6c3aa4357b1 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:66:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:53:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by mbobra** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2732 with the following error: 

 sh: 1: cd: can't cd to cf7fcbd881a9f5f14b0840c0
/app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - cf7fcbd881a9f5f14b0840c0 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:66:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:53:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by mbobra** [comment]
@openjournals/joss-eics Why isn't the pdf compiling properly from branch joss-paper? (It worked correctly in the pre-review).

**Comment by mbobra** [comment]
👋 @mancellin @sibirrer Thank you so much for agreeing to review this submission! Whedon generated your reviewer checklists above. If you'd like more information on any of these items, please reference the [review critera](https://joss.readthedocs.io/en/latest/review_criteria.html). Also, we encourage open communication between the reviewers, submitting author, and editor. So please feel free to ask questions here on this review thread. I'm happy to help!

Also, I am not sure why Whedon is not generating the paper correctly. I'll fix this, but you can use [this pdf](https://github.com/openjournals/joss-papers/blob/joss.02719/joss.02719/10.21105.joss.02719.pdf) in the meantime.

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2732 with the following error: 

 sh: 1: cd: can't cd to 896ed2be1863fee2c7d9c43a
/app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - 896ed2be1863fee2c7d9c43a (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:66:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:53:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2732 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - d7bd0a9a20c9afab265a5e7d (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:66:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:53:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02732/joss.02732/10.21105.joss.02732.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02732/joss.02732/10.21105.joss.02732.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
Apologies for the noise here. This should be fixed now.

**Comment by sibirrer** [comment]
@dstansby very nice software package. I very much like the presentation of the documentation and the user examples. I don't see from my side any roadblocks from publishing pfsspy in JOSS after minor revisions indicated in my opened issues.

I opened three issues:
https://github.com/dstansby/pfsspy/issues/239
https://github.com/dstansby/pfsspy/issues/240
https://github.com/dstansby/pfsspy/issues/241
one concerning the documentation, one about the contribution guidelines and one about code formatting.
Let me know if you have questions about these issues and happy to engage in a discussion.

The installation works and the few examples I tried worked out.

There is one reference in the paper pdf that does not work. And I found a type ("Given an 2D map...")
I am not an expert in solar physics and therefore do not want to judge the scientific applicability. Given that this code has been used in several publications with noticeable use, this is prove enough.

Testing is at a good stage. There are some definitions not being tested and it might be not too much work to add suitable test functions for those as well.

In the documentation you state (wisely): "pfsspy is a very new package, so elements of the API are liable to change with the first few releases." Can you be more specific of which features are susceptible to changes or do you consider the API being stable now? Or what kind of design and feature changes the user might expect in the near future? I very much like the changelog description with the changes that are not backwards compatible in the latest version.

**Comment by dstansby** [comment]
Thanks for taking the time to review it, and thanks for the helpful review!

> I opened three issues:
> [dstansby/pfsspy#239](https://github.com/dstansby/pfsspy/issues/239)
> [dstansby/pfsspy#240](https://github.com/dstansby/pfsspy/issues/240)
> [dstansby/pfsspy#241](https://github.com/dstansby/pfsspy/issues/241)
> one concerning the documentation, one about the contribution guidelines and one about code formatting.
> Let me know if you have questions about these issues and happy to engage in a discussion.

I think I have addressed each of these issues; see the comments I have left on the individual issues. I'll leave you to close or comment on them as you see fit. Am happy to do a minor release of pfsspy with these changes as a condition of acceptance, but I will wait for reviewer two to comment in case there's some more changes to be made.

> There is one reference in the paper pdf that does not work. And I found a type ("Given an 2D map...")

Thanks, the typo and reference has been fixed in the latest version of the paper source.

> In the documentation you state (wisely): "pfsspy is a very new package, so elements of the API are liable to change with the first few releases." Can you be more specific of which features are susceptible to changes or do you consider the API being stable now? Or what kind of design and feature changes the user might expect in the near future? I very much like the changelog description with the changes that are not backwards compatible in the latest version.

Technically I'm reserving the right for everything to be subject to change; in practice now `pfsspy` is maturing only minor changes are now made. I intend for the current version (0.6) to be the last unstable version, and for the next major release (1.0) to be the first release where no API is subsequently broken.

I think that's all - any more queries or questions let me know!

**Comment by sibirrer** [comment]
Thanks @dstansby ! These changes address my comments. I am waiting for the other reviewers comments before signing off myself.

**Comment by mancellin** [comment]
This is a very good work. The package is easy to install, the documentation is fine, and the code examples work as expected.

I agree with @sibirrer's comments. I also reported two more minor issues (dstansby/pfsspy#250, dstansby/pfsspy#254) and made some optional suggestions (dstansby/pfsspy#252, dstansby/pfsspy#253) in the issue tracker of the package.

The paper can be recommended for publication as soon as a fixed version of the package is released.

**Comment by dstansby** [comment]
Thanks both for your super helpful reviews. I have just released a new minor version with the recommended fixes: https://pypi.org/project/pfsspy/0.6.2/. Let me know if there is anything else I need to do, or if I have missed anything.

**Comment by mbobra** [comment]
Thank you both for your thorough and speedy reviews, @sibirrer and @mancellin! I really appreciate it it. 

Nice work and congratulations, @dstansby!

**Comment by dstansby** [comment]
Thanks! Version 0.6.3 includes the paper source: https://github.com/dstansby/pfsspy/releases/tag/0.6.3 / https://pypi.org/project/pfsspy/0.6.3/

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02732/joss.02732/10.21105.joss.02732.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02732/joss.02732/10.21105.joss.02732.pdf) :page_facing_up: :point_left:

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BF00145734 is OK
- 10.1007/BF00146478 is OK
- 10.3847/1538-4365/ab4da7 is OK
- 10.1051/0004-6361/202038319 is OK
- 10.1051/0004-6361/201936449 is OK
- 10.1007/s11207-020-01622-2 is OK
- 10.1038/s41586-019-1818-7 is OK
- 10.3847/1538-4357/ab4f7a is OK
- 10.21105/joss.01832 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1023/A:1005038224881 is OK
- 10.1086/309265 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.4118975 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4118975" target="_blank">10.5281/zenodo.4118975</a> is the archive.

**Comment by mbobra** [comment]
@whedon set v0.6.3 as version

**Comment by whedon** [comment]
OK. v0.6.3 is the version.

**Comment by mbobra** [comment]
@openjournals/joss-eics This paper is ready for final processing 🎉🎉🎉

**Comment by kyleniemeyer** [comment]
Looks good to me!

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BF00145734 is OK
- 10.1007/BF00146478 is OK
- 10.3847/1538-4365/ab4da7 is OK
- 10.1051/0004-6361/202038319 is OK
- 10.1051/0004-6361/201936449 is OK
- 10.1007/s11207-020-01622-2 is OK
- 10.1038/s41586-019-1818-7 is OK
- 10.3847/1538-4357/ab4f7a is OK
- 10.21105/joss.01832 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1023/A:1005038224881 is OK
- 10.1086/309265 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1843

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1843, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1319469111148150785) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1844
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02732](https://doi.org/10.21105/joss.02732)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @dstansby on your article's publication in JOSS!

Many thanks to @mancellin and @sibirrer for reviewing this, and @mbobra for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02732/status.svg)](https://doi.org/10.21105/joss.02732)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02732">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02732/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02732/status.svg
   :target: https://doi.org/10.21105/joss.02732
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02732/status.svg)](https://doi.org/10.21105/joss.02732)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
