### ISSUE TITLE
[PRE REVIEW]: pyhf: pure-Python implementation of HistFactory statistical models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2734]
**Submitting author:** @matthewfeickert (<a href="http://orcid.org/0000-0003-4124-7862">Matthew Feickert</a>)
**Repository:** <a href="https://github.com/scikit-hep/pyhf" target ="_blank">https://github.com/scikit-hep/pyhf</a>
**Version:** v0.5.2
**Editor:** @eloisabentivegna
**Reviewers:** @suchitakulkarni, @bradkav
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @matthewfeickert. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @eloisabentivegna.

@matthewfeickert if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2734 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.46 s (173.2 files/s, 33330.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         109           3334           3611          13247
Jupyter Notebook                25              0          20188           2243
JSON                            38              4              0           1292
reStructuredText                16            476            609            763
YAML                            14             53             29            581
TeX                              8             41              9            486
XML                             27            194            243            308
DTD                              2             40             74            206
make                             1             30              6            194
Markdown                         8             95              0            148
TOML                             1              4              1             58
Dockerfile                       2              4              4             52
Bourne Shell                     2             11              7             48
-------------------------------------------------------------------------------
SUM:                           253           4286          24781          19626
-------------------------------------------------------------------------------


Statistical information for the repository '1ad9a8dbcabed3fa39dd9a08' was
gathered on 2020/10/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Giordon Stark                  117         13959           5323           32.63
GitHub Action                   11            16             16            0.05
Kanishk Kalra                    3           118             45            0.28
Lukas                           94         10569           3485           23.78
Lukas Heinrich                   3            15             15            0.05
Matthew Feickert               133         13393          10061           39.69
Nikolai Hartmann                 3           113             10            0.21
Ruggero Turra                    1             2              2            0.01
Tadej Novak                      1             1              1            0.00
alexander-held                   2            15              0            0.03
lukasheinrich                   57          1454            477            3.27

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Giordon Stark              9470           67.8         12.4                5.28
GitHub Action                 1            6.2          1.0                0.00
Kanishk Kalra               102           86.4          6.2                0.98
Lukas                      6452           61.0         14.5                8.62
Matthew Feickert           4087           30.5         15.9                6.14
Nikolai Hartmann             93           82.3         13.2               11.83
alexander-held               15          100.0          1.6                0.00
```

**Comment by kthyng** [comment]
@whedon generate pdf from branch docs/add-JOSS-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch docs/add-JOSS-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02734/joss.02734/10.21105.joss.02734.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02734/joss.02734/10.21105.joss.02734.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @matthewfeickert! Thanks for your submission. One quick edit that will have to happen at some point: the references in your paper have () around them because they have been put in as [@reference] instead of @reference. Sometimes the () are justified of course but I see some in your paper that should be inline instead of parenthetical.

**Comment by kthyng** [comment]
@eloisabentivegna Can you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @eloisabentivegna as editor

**Comment by whedon** [comment]
@eloisabentivegna has been invited to edit this submission.

**Comment by matthewfeickert** [comment]
> Sometimes the () are justified of course but I see some in your paper that should be inline instead of parenthetical.

Done. :+1:

**Comment by matthewfeickert** [comment]
> > Sometimes the () are justified of course but I see some in your paper that should be inline instead of parenthetical.
> 
> Done.

@whedon generate pdf from branch docs/add-JOSS-paper

**Comment by matthewfeickert** [comment]
@whedon generate pdf from branch docs/add-JOSS-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch docs/add-JOSS-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02734/joss.02734/10.21105.joss.02734.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02734/joss.02734/10.21105.joss.02734.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by matthewfeickert** [comment]
FWIW, as I'm used to seeing citations stylized as just the reference number in the bibliography

![example_screenshot](https://user-images.githubusercontent.com/5142394/95603677-3933f300-0a1c-11eb-84d1-f0aacb7039c8.png)

so if anything looks strange with the current switch to all inline references `@reference` then please let me know and I'll be happy to fix them.

**Comment by eloisabentivegna** [comment]
@whedon assign @eloisabentivegna as editor

> @eloisabentivegna Can you edit this submission?

Sure thing!

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by eloisabentivegna** [comment]
Dear @betatim, would you be available to review this submission?

**Comment by matthewfeickert** [comment]
> Dear @betatim, would you be available to review this submission?

Hi Tim! :)  :wave: 

I don't think there's any conflict of interest, but I'll just note here to be transparent that @betatim knows the authors quite well.

**Comment by eloisabentivegna** [comment]
> I don't think there's any conflict of interest, but I'll just note here to be transparent that @betatim knows the authors quite well.

Thanks for letting me know, @matthewfeickert. @betatim, if you are available to review, could you first check out the conflict-of-interest policy (https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy)?

**Comment by matthewfeickert** [comment]
We just released [`v0.5.3`](https://github.com/scikit-hep/pyhf/releases/tag/v0.5.3) so I rebased the paper branch and corrected the Zenodo version number.

@whedon generate pdf from branch docs/add-JOSS-paper

**Comment by matthewfeickert** [comment]
@whedon generate pdf from branch docs/add-JOSS-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch docs/add-JOSS-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02734/joss.02734/10.21105.joss.02734.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02734/joss.02734/10.21105.joss.02734.pdf) :page_facing_up: :point_left:

**Comment by matthewfeickert** [comment]
Just wanted to give a gentle ping here to see if there was any further thoughts on having @betatim review the paper given @eloisabentivegna's request.

**Comment by eloisabentivegna** [comment]
@bradkav, @suchitakulkarni, @vyasr, are you available to review this submission?

**Comment by vyasr** [comment]
Hi there, normally I'd be happy to help, but I have my PhD defense coming up in less than a month so unfortunately I don't have the bandwidth for this at the moment. Come December if you're still short a reviewer, feel free to ping me again!

**Comment by suchitakulkarni** [comment]
Hi, I will be happy to do this. Please provide me with the instructions and timeline of what is expected out of me.

**Comment by eloisabentivegna** [comment]
> Hi there, normally I'd be happy to help, but I have my PhD defense coming up in less than a month so unfortunately I don't have the bandwidth for this at the moment. Come December if you're still short a reviewer, feel free to ping me again!

Dear @vyasr, thanks for letting us know. Best of luck on your defense!

**Comment by eloisabentivegna** [comment]
> Hi, I will be happy to do this. Please provide me with the instructions and timeline of what is expected out of me.

Suchita, thanks for agreeing to help! As you might have gathered if you've looked around this repository a little, a JOSS review is centred upon downloading and installing the software, and inspecting the repository and submitted paper for key elements. You can find much more details at https://joss.readthedocs.io/en/latest/reviewer_guidelines.html, but I am also happy to elaborate.

Since this is much more interactive than traditional reviews, we encourage you to start as soon as possible. We would expect things to wrap up within six weeks, at the latest.

**Comment by bradkav** [comment]
> @bradkav, @suchitakulkarni, @vyasr, are you available to review this submission?

Sorry for the slow reply. I see that Suchita has already accepted, but if you still need another reviewer, I'd be happy to do it. Let me know :)

**Comment by eloisabentivegna** [comment]
> Sorry for the slow reply. I see that Suchita has already accepted, but if you still need another reviewer, I'd be happy to do it. Let me know :)

Thanks, @bradkav! Definitely still in time. :)

**Comment by eloisabentivegna** [comment]
@whedon add @suchitakulkarni as reviewer

**Comment by whedon** [comment]
OK, @suchitakulkarni is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon add @bradkav as reviewer

**Comment by whedon** [comment]
OK, @bradkav is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2823.
