### ISSUE TITLE
[PRE REVIEW]: ELDAM: A Python software for Life Cycle Inventory data management

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2735]
**Submitting author:** @GustaveCoste (<a href="http://orcid.org/0000-0001-5867-0507">Gustave Coste</a>)
**Repository:** <a href="https://framagit.org/GustaveCoste/eldam" target ="_blank">https://framagit.org/GustaveCoste/eldam</a>
**Version:** V1.0
**Editor:** @sjpfenninger
**Reviewers:** @konstantinstadler, @romainsacchi
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @GustaveCoste. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @sjpfenninger.

@GustaveCoste if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.82 s (53.8 files/s, 7627.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          50           1980           1943           5067
Qt                              10              0              0           3047
SVG                             10              8              6            877
reStructuredText                24            252            199            457
DOS Batch                        2              8              1             30
make                             1              4              6             10
INI                              1              0              0              2
-------------------------------------------------------------------------------
SUM:                            98           2252           2155           9490
-------------------------------------------------------------------------------


Statistical information for the repository '9562c73e5278aa16bc004d02' was
gathered on 2020/10/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Gustave Coste                  496         28421          19431          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Gustave Coste              8990           31.6         20.0               11.43
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2735 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02735/joss.02735/10.21105.joss.02735.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02735/joss.02735/10.21105.joss.02735.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@sjpfenninger would you be willing to edit this? I see you have 4 currently, but one is about to be wrapped up so I thought it might be ok.

**Comment by kthyng** [comment]
@whedon invite @sjpfenninger as editor

**Comment by whedon** [comment]
@sjpfenninger has been invited to edit this submission.

**Comment by sjpfenninger** [comment]
@whedon assign @sjpfenninger as editor

**Comment by whedon** [comment]
OK, the editor is @sjpfenninger

**Comment by sjpfenninger** [comment]
@konstantinstadler 👋 Would you be willing to review this submission to JOSS?

**Comment by sjpfenninger** [comment]
@GustaveCoste Thanks for your submission! It looks like there are two broken references in the PDF (and a typo next to one of them: "inteface"). Can you fix those?

**Comment by konstantinstadler** [comment]
> @konstantinstadler wave Would you be willing to review this submission to JOSS?

Hi, happy to do the review, but can only do that next week.

**Comment by GustaveCoste** [comment]
Hi, thank you for initiating the review process. I tried to fix the broken references without success. The strange thing is that I can't see the difference with [the example](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).

Here is the figure: 
    `![Review procedure.\label{fig:review}](review.png)`

And the reference to it:
`... helps to improve the LCIs quality (\autoref{fig:review}).`

Should the figure be inserted before the reference?

**Comment by sara-02** [comment]
Hey folks, I am available to review more packages, and while this tool is not right up my alley(I work with Python but not software workflow tools), if you need more reviewers for this I am available to help 23rd Oct onwards :)

**Comment by sjpfenninger** [comment]
@konstantinstadler Looks like it's next week anyway now, so I'll take you up on the offer. Thanks!

**Comment by sjpfenninger** [comment]
Thanks @sara-02, let me see if we find somebody with expertise in the area.

**Comment by sjpfenninger** [comment]
@romainsacchi Would you be able to review this submission to JOSS?

**Comment by sjpfenninger** [comment]
@whedon add @konstantinstadler as reviewer

**Comment by whedon** [comment]
OK, @konstantinstadler is now a reviewer

**Comment by sjpfenninger** [comment]
@GustaveCoste Hmm, I'm unsure what's happening there. @openjournals/dev Any idea why following the figure referencing approach from [the example](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) does not work [in this case](https://framagit.org/GustaveCoste/eldam/-/blob/joss/paper.md)?

**Comment by arfon** [comment]
> @GustaveCoste Hmm, I'm unsure what's happening there. @openjournals/dev Any idea why following the figure referencing approach from the example does not work in this case?

No idea at all sorry. I've been debugging this for the last hour and can't get it to work (I'm currently trying to figure out if this has _ever_ worked 😕). For now, I suggest simply cross-linking manually by just writing out the figure name in the text (e.g. _Figure 1_ shows...).

**Comment by arfon** [comment]
Actually, turns out this is a whitespace issue. If you give your figures some whitespace, e.g., change L65 onward to look like this:

```
`ELDAM` has been used in various research projects [@Gentil:2020], helping to improve and characterize LCI data quality. Its review procedure has proven very helpful for auditing the LCIs produced by LCA beginners such as interns.

![Review procedure.\label{fig:review}](review.png)

![ELDAM's GUI.\label{fig:gui}](gui.png)
```

you should find it works.

**Comment by romainsacchi** [comment]
Yes, I can do that.

**Comment by romainsacchi** [comment]
@sjpfenninger yes, I can do that.

**Comment by GustaveCoste** [comment]
@arfon Thank you it fixed the problem.

**Comment by sjpfenninger** [comment]
@whedon add @romainsacchi as reviewer

**Comment by whedon** [comment]
OK, @romainsacchi is now a reviewer

**Comment by sjpfenninger** [comment]
Thanks @romainsacchi !

**Comment by sjpfenninger** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2765.

**Comment by sjpfenninger** [comment]
@konstantinstadler , @romainsacchi  thanks for agreeing to review. Let's head over to #2765 for the actual review!
