### ISSUE TITLE
[PRE REVIEW]: hectorui: A web-based interactive scenario builder and visualization application for the Hector climate model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2736]
**Submitting author:** @evanoffPNNL (<a href="http://orcid.org/0000-0002-8858-2783">Jason Evanoff</a>)
**Repository:** <a href="https://github.com/JGCRI/hectorui/" target ="_blank">https://github.com/JGCRI/hectorui/</a>
**Version:** 1.1.0
**Editor:** @kthyng
**Reviewers:** @marvinjonathcn, @tscheypidi
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @evanoffPNNL. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @danielskatz.

@evanoffPNNL if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.00 s (67.1 files/s, 14256.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            24           1097            289           3118
INI                             12            703           1281           2596
R                               11            437            677           1715
CSS                              4            173             60            749
Markdown                         4            127              0            567
JavaScript                       4             65             33            264
TeX                              1              0              0             93
YAML                             4             12              0             58
SVG                              2              0              1             46
Rmd                              1             23             58              1
-------------------------------------------------------------------------------
SUM:                            67           2637           2399           9207
-------------------------------------------------------------------------------


Statistical information for the repository 'bf1174da4bea7e5858394c46' was
gathered on 2020/10/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
crvernon                         1           352              0           97.24
evanoffPNNL                      1            10              0            2.76

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
crvernon                    352          100.0          0.0                9.09
evanoffPNNL                  10          100.0          0.0               10.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5194/gmd-8-939-2015 is OK
- 10.5194/bg-13-4329-2016 is OK

MISSING DOIs

- 10.1371/journal.pone.0223542 may be a valid DOI for title: Joint emulation of Earth System Model temperature-precipitation realizations with internal variability and space-time and cross-variable correlation: fldgen v2. 0 software description
- 10.1016/j.techfore.2006.05.026 may be a valid DOI for title: Scenarios of long-term socio-economic and environmental development under climate stabilization
- 10.5547/issn0195-6574-ej-volsi2006-nosi3-17 may be a valid DOI for title: Multi-gas mitigation analysis on stabilization scenarios using AIM global model
- 10.1007/s10584-011-0151-4 may be a valid DOI for title: RCP4. 5: a pathway for stabilization of radiative forcing by 2100
- 10.1007/s10584-011-0152-3 may be a valid DOI for title: RCP2. 6: exploring the possibility to keep global mean temperature increase below 2 C

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02736/joss.02736/10.21105.joss.02736.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02736/joss.02736/10.21105.joss.02736.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@evanoffPNNL Thank you for your submission! I will be your editor. Please add a "Statement of Need" to your paper to start. Also, can you recommend reviewers for this submission? You can recommend from your network or from [this list](https://bit.ly/joss-reviewers) of volunteers (as long as not conflicting). If you are providing github handles, please do not use "@" so that they are not prematurely notified with excessive email.

**Comment by evanoffPNNL** [comment]
@kthyng Thanks for your quick turn around on getting the review process started! The statement of need was an oversight that has been fixed in the latest release today. I am also listing a number of reviewers that seemed appropriate from my perspective in no particular order. Please let me know if there's anything else needed. 

jhollist, nuest , khaors,  garretrc, marvinjonathcn,  mikejohnson51, arbennett

**Comment by crvernon** [comment]
@kthyng @evanoffPNNL The latest release is:  https://github.com/JGCRI/hectorui/releases/tag/v1.1.1 and the accompanying DOI from Zenodo link is:   http://doi.org/10.5281/zenodo.4075376

Thanks!

**Comment by kthyng** [comment]
Hi @crvernon! We'll need that information at the end of the review process to make sure everything is up to date at that point, and there should be an up to date zenodo archive at that time too.

**Comment by kthyng** [comment]
I'll get back to this next week to get the review going.

**Comment by crvernon** [comment]
Thanks @kthyng ! Let us know if you need anything else.  Have a great day!

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02736/joss.02736/10.21105.joss.02736.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02736/joss.02736/10.21105.joss.02736.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5194/gmd-8-939-2015 is OK
- 10.5194/bg-13-4329-2016 is OK

MISSING DOIs

- 10.1371/journal.pone.0223542 may be a valid DOI for title: Joint emulation of Earth System Model temperature-precipitation realizations with internal variability and space-time and cross-variable correlation: fldgen v2. 0 software description
- 10.1016/j.techfore.2006.05.026 may be a valid DOI for title: Scenarios of long-term socio-economic and environmental development under climate stabilization
- 10.5547/issn0195-6574-ej-volsi2006-nosi3-17 may be a valid DOI for title: Multi-gas mitigation analysis on stabilization scenarios using AIM global model
- 10.1007/s10584-011-0151-4 may be a valid DOI for title: RCP4. 5: a pathway for stabilization of radiative forcing by 2100
- 10.1007/s10584-011-0152-3 may be a valid DOI for title: RCP2. 6: exploring the possibility to keep global mean temperature increase below 2 C

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@evanoffPNNL and @crvernon — please modify your bib file to include the missing DOIs listed above.

@evanoffPNNL thanks for the long list of reviewer ideas! I'll invite people now.

**Comment by kthyng** [comment]
@mikejohnson51 and @nuest — are you interested in reviewing this submission to JOSS? Reviews for JOSS are open on github and are checklist-driven. As you find items to bring up in the review process, you open issues to the software repository itself, link to the review issue, and explain the comment. We're asking for reviews within 5-6 weeks, a long timeline due to the pandemic. You can find more information about the reviewing process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#

**Comment by evanoffPNNL** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5194/gmd-8-939-2015 is OK
- 10.5194/bg-13-4329-2016 is OK
- 10.1007/s10584-011-0149-y is OK
- 10.5547/ISSN0195-6574-EJ-VolSI2006-NoSI3-17 is OK
- 10.1007/s10584-011-0152-3 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1371/journal.pone.0223542 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.5194/gmd-12-677-2019 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.techfore.2006.05.026 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/s10584-011-0151-4 is INVALID because of 'https://doi.org/' prefix
```

**Comment by evanoffPNNL** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5194/gmd-8-939-2015 is OK
- 10.5194/bg-13-4329-2016 is OK
- 10.1371/journal.pone.0223542 is OK
- 10.5194/gmd-12-677-2019 is OK
- 10.1016/j.techfore.2006.05.026 is OK
- 10.1007/s10584-011-0149-y is OK
- 10.5547/ISSN0195-6574-EJ-VolSI2006-NoSI3-17 is OK
- 10.1007/s10584-011-0151-4 is OK
- 10.1007/s10584-011-0152-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by evanoffPNNL** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02736/joss.02736/10.21105.joss.02736.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02736/joss.02736/10.21105.joss.02736.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Ok thanks @evanoffPNNL. We'll wait a few more days to see if we hear back from potential reviewers before trying others.

**Comment by kthyng** [comment]
@marvinjonathcn: are you interested in reviewing this submission to JOSS? Reviews for JOSS are open on github and are checklist-driven. As you find items to bring up in the review process, you open issues to the software repository itself, link to the review issue, and explain the comment. We're asking for reviews within 5-6 weeks, a long timeline due to the pandemic. You can find more information about the reviewing process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#

**Comment by nuest** [comment]
@kthyng Sorry, I am just about to start another JOSS review and wouldn't be able to get to this even within the extended timeline.

@tscheypidi are you a JOSS reviewer yet?

**Comment by marvinjonathcn** [comment]
Hello @kthyng , I would like to be a reviewer for this publication.

**Comment by kthyng** [comment]
@marvinjonathcn - excellent! I will add you now. We need to find another reviewer before continue on in the review process, so hold tight for now.

**Comment by kthyng** [comment]
@whedon assign @marvinjonathcn as reviewer

**Comment by whedon** [comment]
OK, @marvinjonathcn is now a reviewer

**Comment by kthyng** [comment]
@nuest of course, totally understand, thanks for getting back to me.

**Comment by kthyng** [comment]
@tscheypidi [Here](https://joss.theoj.org/reviewer-signup.html) is the link to sign up as a JOSS reviewer generally if you'd like. Are you interested in being a reviewer on this submission?

**Comment by tscheypidi** [comment]
@kthyng @nuest Thanks for the invitation. I haven't reviewed for JOSS yet, but I am happy to help.

**Comment by kthyng** [comment]
Ok thanks @tscheypidi, looks like you are a good fit.

**Comment by kthyng** [comment]
@whedon add @tscheypidi as reviewer

**Comment by whedon** [comment]
OK, @tscheypidi is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2782.
