### ISSUE TITLE
[PRE REVIEW]: pystiche: A Framework for Neural Style Transfer

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2737]
**Submitting author:** @pmeier (<a href="http://orcid.org/0000-0002-5184-1622">Philip Meier</a>)
**Repository:** <a href="https://github.com/pmeier/pystiche" target ="_blank">https://github.com/pmeier/pystiche</a>
**Version:** v0.6.1
**Editor:** @kthyng
**Reviewers:** @kthyng
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pmeier. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@pmeier if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=2.63 s (67.6 files/s, 6937.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         132           3801           1756          10566
YAML                            10             99             41            394
reStructuredText                27            276            481            358
INI                              3             25              9            153
TeX                              2             16              1            106
TOML                             1              9              6             60
Markdown                         1             12              0             57
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           178           4250           2302          11729
-------------------------------------------------------------------------------


Statistical information for the repository '48f970e7cb203db4a573b3e3' was
gathered on 2020/10/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Philip Meier                   309         66560          51574           98.93
jbueltemeier                     1          1174              1            0.98
sourcery-ai[bot]                 1            31             67            0.08

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Philip Meier              16110           24.2          3.8                4.63
sourcery-ai[bot]             13           41.9          3.7                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/CVPR.2016.265 is OK
- 10.1109/CVPR.2016.272 is OK
- 10.1109/CVPR.2017.397 is OK
- 10.1145/3092919.3092920 is OK
- 10.1007/978-3-319-46475-6_43 is OK
- 10.1007/978-3-030-01234-2_49 is OK
- 10.1109/TVCG.2019.2921336 is OK

MISSING DOIs

- 10.1109/cvpr.2015.7299155 may be a valid DOI for title: Understanding Deep Image Representations by Inverting Them
- 10.1007/springerreference_62539 may be a valid DOI for title: Non-Photorealistic Rendering

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02737/joss.02737/10.21105.joss.02737.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02737/joss.02737/10.21105.joss.02737.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @pmeier! Thank you for your submission. Can you add a statement of need to your paper?

**Comment by kthyng** [comment]
@pmeier Also I've read through your paper several times but I'm having a hard time figuring out a few categories of where this software fits in order to match it up with our editors. You suggested arfon as editor when you submitted but that doesn't seem like a good match to me. We don't have someone who does image processing in particular, but some who do machine learning in particular domains. Does this work fit into a particular domain?

**Comment by pmeier** [comment]
Hey @kthyng 

> Also I've read through your paper several times but I'm having a hard time figuring out a few categories of where this software fits in order to match it up with our editors. You suggested arfon as editor when you submitted but that doesn't seem like a good match to me.

`pystiche` was already reviewed in pyOpenSci/software-review#25 in a previous step. The editor @NickleDave ["tasked" me](https://github.com/pyOpenSci/software-review/issues/25#issuecomment-705646440) to submit to JOSS. In the same comment he tagged @arfon, hence my suggestion.

> We don't have someone who does image processing in particular, but some who do machine learning in particular domains. Does this work fit into a particular domain?

Yes, machine learning plays a big role in the project. Looking through your [list of editors](https://joss.theoj.org/about#editorial_board) I think Juan Nunez-Iglesias (jni) would also be a good fit since he is listed for Python and image processing.

**Comment by kthyng** [comment]
@pmeier Ah! I am sorry I missed your note with the original submission. In that case, your submission doesn't need a separate review so I can just process this for you.

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02737/joss.02737/10.21105.joss.02737.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02737/joss.02737/10.21105.joss.02737.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Ok so @pmeier let me know when you have added a statement of need and I think we can proceed through the much shortened process since this came from pyopensci.

**Comment by pmeier** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by pmeier** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/CVPR.2016.265 is OK
- 10.1109/CVPR.2015.7299155 is OK
- 10.1109/CVPR.2016.272 is OK
- 10.1109/CVPR.2017.397 is OK
- 10.1145/3092919.3092920 is OK
- 10.1007/978-3-319-46475-6_43 is OK
- 10.1007/978-3-030-01234-2_49 is OK
- 10.1109/TVCG.2019.2921336 is OK

MISSING DOIs

- 10.1007/springerreference_62539 may be a valid DOI for title: Non-Photorealistic Rendering

INVALID DOIs

- None
```

**Comment by pmeier** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02737/joss.02737/10.21105.joss.02737.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02737/joss.02737/10.21105.joss.02737.pdf) :page_facing_up: :point_left:

**Comment by pmeier** [comment]
@kthyng I've added a "Statement of Need" section to the paper. 

@whedon [keeps suggesting a DOI](https://github.com/openjournals/joss-reviews/issues/2737#issuecomment-709186591) (`10.1007/springerreference_62539`) for one of the references that does [**not** resolve correctly](https://doi.org/10.1007/springerreference_62539). I couldn't find a DOI for that source manually. Is that a problem?

**Comment by kthyng** [comment]
@pmeier I agree that the DOI does not appear to be correct, so we just need to remember to ignore that warning. I will continue processing your submission.

**Comment by kthyng** [comment]
I want to be clear to link to the [pyOpenSci review](https://github.com/pyOpenSci/software-review/issues/25) already completed.

**Comment by kthyng** [comment]
@whedon assign @kthyng as reviewer

**Comment by whedon** [comment]
OK, @kthyng is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2761.
