### ISSUE TITLE
[PRE REVIEW]: mcbette: model comparison using babette

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2738]
**Submitting author:** @richelbilderbeek (<a href="http://orcid.org/0000-0003-1107-7049">Richel Bilderbeek</a>)
**Repository:** <a href="https://github.com/ropensci/mcbette" target ="_blank">https://github.com/ropensci/mcbette</a>
**Version:** v1.8.3
**Editor:** @kthyng
**Reviewers:** @kthyng
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @richelbilderbeek. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @marcosvital.

@richelbilderbeek if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (507.4 files/s, 39138.2 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
R                                34            221            635           1336
HTML                              1             33              2            449
Markdown                         10            211              0            437
JSON                              1              0              0            318
YAML                              2             26             30            100
Rmd                               2             76            170             74
TeX                               1              6              0             61
Bourne Again Shell                4              6             21             30
--------------------------------------------------------------------------------
SUM:                             55            579            858           2805
--------------------------------------------------------------------------------


Statistical information for the repository '746639d6a8241269327f8b70' was
gathered on 2020/10/09.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1111/2041-210X.13032 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1371/journal.pcbi.1006650 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1093/molbev/msi103 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1098/rstb.1994.0068 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1093/sysbio/syy050 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #2738 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/openjournals/jose-reviews/issues/2738: 404 - Not Found // See: https://docs.github.com/rest/reference/issues#get-an-issue (Octokit::NotFound)
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /app/vendor/bundle/ruby/2.4.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	from /app/vendor/bundle/ruby/2.4.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/connection.rb:156:in `request'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/connection.rb:19:in `get'
	from /app/vendor/bundle/ruby/2.4.0/gems/octokit-4.8.0/lib/octokit/client/issues.rb:114:in `issue'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/review.rb:21:in `issue_body'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:44:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02738/joss.02738/10.21105.joss.02738.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02738/joss.02738/10.21105.joss.02738.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @richelbilderbeek! Thanks for your submission. Your submission is missing a few items or needs editing:

* open source license
* DOI's are missing from references (see list above)
* Your paper needs a high level non-technical short introduction to orient a reader who might be interested in using your software to decide whether it is relevant or not.
* you should be able to resize your giant logo in the paper too

**Comment by kthyng** [comment]
@marcosvital Could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @marcosvital as editor

**Comment by whedon** [comment]
@marcosvital has been invited to edit this submission.

**Comment by richelbilderbeek** [comment]
This package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/360, @ropensci/editors

**Comment by kthyng** [comment]
> This package has been reviewed by rOpenSci: [ropensci/software-review#360](https://github.com/ropensci/software-review/issues/360), @ropensci/editors

@richelbilderbeek ah! I didn't realize that. I will process this submission then.

@marcosvital Please disregard the invitation above.

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02738/joss.02738/10.21105.joss.02738.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02738/joss.02738/10.21105.joss.02738.pdf) :page_facing_up: :point_left:

**Comment by richelbilderbeek** [comment]
Hi @kthyng, I have processed your feedback:

> open source license

Upon your request, I have added the LICENSE file.

> DOI's are missing from references (see list above)

Fixed the DOIs indited by [this](https://github.com/openjournals/joss-reviews/issues/2738#issuecomment-706222339) @whelan commit.

> Your paper needs a high level non-technical short introduction to orient a reader who might be interested in using your software to decide whether it is relevant or not.

AFAICS the Introduction serves that purpose:

>``mcbette`` is an R package to do model comparison between
a set of evolutionary models on a DNA alignment, which allows
to select that model that is closest to the process that underlied
the DNA alignment and species tree.

I assume the rOpenSci reviewers agree. If you disagree, let me know and I will make it less technical :+1:

> you should be able to resize your giant logo in the paper too

Done!

If there is something more you need, let me know and I will be happy to help :+1:

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02738/joss.02738/10.21105.joss.02738.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02738/joss.02738/10.21105.joss.02738.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon assign @kthyng as reviewer

**Comment by whedon** [comment]
OK, @kthyng is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2762.
