### ISSUE TITLE
[PRE REVIEW]: pfem4ec.jl: Pixel-based Finite Element Method for computing effective electrical conductivity of heterogeneous materials

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2739]
**Submitting author:** @victorsapucaia (<a href="http://orcid.org/0000-0002-5394-2603">Victor Wriedt Sapucaia</a>)
**Repository:** <a href="https://github.com/LCC-UFF/pfem4ec" target ="_blank">https://github.com/LCC-UFF/pfem4ec</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @victorsapucaia. **Currently, there isn't an JOSS editor assigned** to your paper.

@victorsapucaia if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.polymertesting.2019.106218 is OK
- 10.1016/j.commatsci.2013.09.006 is OK
- 10.1002/cnm.1630020205 is OK
- 10.1098/rspa.1979.0160 is OK
- 10.1038/d41586-019-02310-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (228.4 files/s, 25632.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                            1             43             60            434
Jupyter Notebook                 1              0            501            356
JSON                            12              0              0            276
Markdown                         4            121              0            267
TeX                              1             11              0             63
-------------------------------------------------------------------------------
SUM:                            19            175            561           1396
-------------------------------------------------------------------------------


Statistical information for the repository '619ed4db2b515c2e6ce71904' was
gathered on 2020/10/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02739/joss.02739/10.21105.joss.02739.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02739/joss.02739/10.21105.joss.02739.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
👋 @victorsapucaia - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject
