### ISSUE TITLE
[PRE REVIEW]: OpenSpace: An open-source astrovisualization framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#274]
**Submitting author:** @alexanderbock (<a href="http://orcid.org/0000-0002-2849-6146">Alexander Bock</a>)
**Repository:** <a href="https://github.com/OpenSpace/OpenSpace" target ="_blank">https://github.com/OpenSpace/OpenSpace</a>
**Version:** v0.8.0
**Editor:** @danielskatz
**Reviewer:** @MatthewTurk

**Author instructions**

Thanks for submitting your paper to JOSS @alexanderbock. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@alexanderbock if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @danielskatz - the submitting author suggested you as an editor. What do you think?

**Comment by danielskatz** [comment]
ok

**Comment by danielskatz** [comment]
@MatthewTurk - would you be willing to review this?  Or if not, can you suggest other potential reviewers?

**Comment by MatthewTurk** [comment]
Yes, I'd be happy to.

**Comment by danielskatz** [comment]
great, thanks

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by danielskatz** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by danielskatz** [comment]
@whedon assign @MatthewTurk as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @MatthewTurk

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/281. Feel free to close this issue now!
