### ISSUE TITLE
[PRE REVIEW]: ezc3d: An easy C3D file I/O cross-platform solution for C++, Python and MATLAB

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2740]
**Submitting author:** @pariterre (<a href="http://orcid.org/0000-0002-5031-1048">Benjamin Michaud</a>)
**Repository:** <a href="https://github.com/pyomeca/ezc3d" target ="_blank">https://github.com/pyomeca/ezc3d</a>
**Version:** Release_1.3.7
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @melund, @BKillen05
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pariterre. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@pariterre if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-0-12-816713-7.00008-8 is OK
- 10.1371/journal.pcbi.1006223 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.19 s (415.0 files/s, 105195.7 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code
---------------------------------------------------------------------------------------
C++                                     27           1069            563           7504
SWIG                                     3            312            537           2692
C/C++ Header                            21            485           2204           1077
Python                                   5            174             79            953
SVG                                      2              2              2            593
CMake                                   11            117            175            554
Markdown                                 3            130              0            489
MATLAB                                   5             56             35            296
YAML                                     1              7             11             93
TeX                                      1              7              0             60
Windows Module Definition                1              0              0              1
---------------------------------------------------------------------------------------
SUM:                                    80           2359           3606          14312
---------------------------------------------------------------------------------------


Statistical information for the repository '6a0a1285504861a038ab5229' was
gathered on 2020/10/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Allison Clouthier                1             0              3            0.01
Christopher Dembia               1             7              3            0.02
Marcos Alfredo Núñez             8           205             10            0.51
Morten Enemark Lund              1             4              2            0.01
Pariterre                      322         26581          13248           94.26
pariterre                       15          1382            811            5.19

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Christopher Dembia            7          100.0          5.9                0.00
Marcos Alfredo Núñez        167           81.5         11.3                4.19
Pariterre                 13934           52.4         13.7               20.35
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02740/joss.02740/10.21105.joss.02740.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02740/joss.02740/10.21105.joss.02740.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@luizirber welcome to JOSS! Would you be able to edit this submission? Can't tell if this is close to your expertise at all.

**Comment by kthyng** [comment]
@whedon invite @luizirber as editor

**Comment by whedon** [comment]
@luizirber has been invited to edit this submission.

**Comment by luizirber** [comment]
> @luizirber welcome to JOSS! Would you be able to edit this submission? Can't tell if this is close to your expertise at all.

It isn't my expertise, but I'm willing to try =]

**Comment by Kevin-Mattheus-Moerman** [comment]
@kthyng I can take this or help support @luizirber with it

**Comment by kthyng** [comment]
Thanks @Kevin-Mattheus-Moerman. @luizirber up to you!

**Comment by danielskatz** [comment]
@whedon assign @luizirber as editor

**Comment by whedon** [comment]
OK, the editor is @luizirber

**Comment by arfon** [comment]
:wave: @luizirber - how are you getting on finding reviewers here?

**Comment by arfon** [comment]
@pariterre - could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by pariterre** [comment]
Hi @arfon !
Thanks for the update :)
I would suggest @ixjlyons and @melund (I am not sure for @melund though since he contributed once to the code, I can't remember on what exactly though!)

Do you need more? :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02740/joss.02740/10.21105.joss.02740.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02740/joss.02740/10.21105.joss.02740.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@modenaxe @BKillen05 @melund @ixjlyons would you be interested in reviewing this work for [JOSS](https://joss.theoj.org/)? 
The review focuses on [the software](https://github.com/pyomeca/ezc3d) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.02740/joss.02740/10.21105.joss.02740.pdf). 
For more information have a look at our [review guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by melund** [comment]
Yes. I would like to help review :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @melund as reviewer

**Comment by whedon** [comment]
OK, @melund is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@melund @pariterre says you made what sounds like a minor contribution to this project in the past. Can you confirm you do not have a conflict of interest reviewing this work? Thanks.

**Comment by ixjlyons** [comment]
Sorry, now's not a great time for me personally so I'll have to decline reviewing this one.

**Comment by Kevin-Mattheus-Moerman** [comment]
@modenaxe @BKillen05 would you be able to help with this review?

**Comment by modenaxe** [comment]
Hi @Kevin-Mattheus-Moerman, apologies for the late reply! Not the best period for reviewing unfortunately...I doubt I could do this before January... @BKillen05 what is your situation?

**Comment by melund** [comment]
> @melund @pariterre says you made what sounds like a minor contribution to this project in the past. Can you confirm you do not have a conflict of interest reviewing this work? Thanks.

Yes. I can confirm that I don't have any conflicts of interests :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@modenaxe If you are able to help in January that is fine too. I expect any reviewer will tell me "dude the holidays are coming", so I we can certainly wait if you are still interested.

**Comment by BKillen05** [comment]
HI Kevin, Sorry for the radio silence I was finalising a fellowship application and let most of my mails lapse.  I am in the same boat as Luca at this point where I can likely find more time in January CheersBryce  Bryce A Killen, BExSc Hons PhDPostdoctoral Research FellowHuman Movement Biomechanics Research GroupKU Leuven, Leuven, BelgiumTwitter: @bryce_killen From: Kevin Mattheus MoermanSent: dinsdag 1 december 2020 12:34To: openjournals/joss-reviewsCc: BKillen05; MentionSubject: Re: [openjournals/joss-reviews] [PRE REVIEW]: ezc3d: An easy C3D file I/O cross-platform solution for C++, Python and MATLAB (#2740) @modenaxe If you are able to help in January that is fine too. I expect any reviewer will tell me "dude the holidays are coming", so I we can certainly wait if you are still interested.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Kevin-Mattheus-Moerman** [comment]
@BKillen05 @modenaxe since December/January is a holiday season for many we've seen this type of response from many editors/reviewers invited. This is fine and fully understandable and we can be flexible regarding timing to work with your constraints. 

Would you be okay with being assigned as reviewers for now and to pick this up whenever you are "back in the office"? No worries if you'd rather not. 
Thanks.

**Comment by BKillen05** [comment]
Hi Kevin, That is fine for me CheersBryce  Bryce A Killen, BExSc Hons PhDPostdoctoral Research FellowHuman Movement Biomechanics Research GroupKU Leuven, Leuven, BelgiumTwitter: @bryce_killen From: Kevin Mattheus MoermanSent: zaterdag 12 december 2020 10:34To: openjournals/joss-reviewsCc: BKillen05; MentionSubject: Re: [openjournals/joss-reviews] [PRE REVIEW]: ezc3d: An easy C3D file I/O cross-platform solution for C++, Python and MATLAB (#2740) @BKillen05 @modenaxe since December/January is a holiday season for many we've seen this type of response from many editors/reviewers invited. This is fine and fully understandable and we can be flexible regarding timing to work with your constraints.Would you be okay with being assigned as reviewers for now and to pick this up whenever you are "back in the office"? No worries if you'd rather not.Thanks.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @BKillen05 as reviewer

**Comment by whedon** [comment]
OK, @BKillen05 is now a reviewer

**Comment by modenaxe** [comment]
@Kevin-Mattheus-Moerman probably this is ok for me as well but can I confirm when I am back in early January?

**Comment by Kevin-Mattheus-Moerman** [comment]
@modenaxe okay sounds good. Enjoy the holiday period and talk to you next year.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2911.
