### ISSUE TITLE
[PRE REVIEW]: BinMat: an R package and Shiny application for processing binary data obtained from genetic fragment analysis methods

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2742]
**Submitting author:** @CJMvS (<a href="http://orcid.org/0000-0002-4219-446X">Clarke van Steenderen</a>)
**Repository:** <a href="https://github.com/CJMvS/BinMat_JOSS" target ="_blank">https://github.com/CJMvS/BinMat_JOSS</a>
**Version:** v0.1.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @CJMvS. **Currently, there isn't an JOSS editor assigned** to your paper.

@CJMvS if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.41 s (59.0 files/s, 10897.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             1              0              0           1279
HTML                             1             33              2            716
R                               16            298            327            635
TeX                              1             38              0            366
Markdown                         3            148              0            325
Rmd                              2             88            158             21
-------------------------------------------------------------------------------
SUM:                            24            605            487           3342
-------------------------------------------------------------------------------


Statistical information for the repository '7996e803680d5bae5cf46acb' was
gathered on 2020/10/12.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2742 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (a8c3174891a74b887edc939e/Paper/paper.md): could not find expected ':' while scanning a simple key at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @CJMvS - your paper.md is not formatted correctly - see https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography for what is needed.  If you make changes, please add a new comment here with ```@whedon generate pdf``` to check to see if it compiles.  You can also use ```@whedon check references``` to see if references have correct DOIs (as far as whedon can guess).

**Comment by danielskatz** [comment]
Also, due to the small size of your code, the editors will discuss the scope of the paper to see if we will review it.  We should make a decision by the end of next week

**Comment by danielskatz** [comment]
@whedon scope query

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by CJMvS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2742 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (00934c39f12d19325df18b5e/Paper/paper.md): did not find expected key while parsing a block mapping at line 16 column 4 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by CJMvS** [comment]
@whedon generate pdf

**Comment by CJMvS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: :point_left:

**Comment by CJMvS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: :point_left:

**Comment by CJMvS** [comment]
@whedon check references

**Comment by CJMvS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: :point_left:

**Comment by CJMvS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: :point_left:

**Comment by CJMvS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: :point_left:

**Comment by CJMvS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: :point_left:

**Comment by CJMvS** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by CJMvS** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (453.9 files/s, 83094.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             1              0              0           1279
HTML                             1             33              2            716
R                               16            298            327            635
TeX                              1             38              0            367
Markdown                         3            112              0            189
Rmd                              1             71            123             21
-------------------------------------------------------------------------------
SUM:                            23            552            452           3207
-------------------------------------------------------------------------------


Statistical information for the repository 'e54b789413047443089f1c6b' was
gathered on 2020/10/12.
No commited files with the specified extensions were found.
```

**Comment by CJMvS** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/j.biocontrol.2020.104426 may be a valid DOI for title: Addressing the red flags in cochineal identification: the use of molecular techniques to identify cochineal insects that are used as biological control agents for invasive alien cacti
- 10.1111/j.1442-9993.1993.tb00438.x may be a valid DOI for title: Non-parametric multivariate analyses of changes in community structure
- 10.1007/978-1-61779-870-2_10 may be a valid DOI for title: Automated scoring of AFLPs using RawGeno v 2.0, a free R CRAN library
- 10.1111/j.1365-294x.2004.02346.x may be a valid DOI for title: How to track and assess genotyping errors in population genetics studies
- 10.1080/10635150802044037 may be a valid DOI for title: Optimizing automated AFLP scoring parameters to improve phylogenetic resolution
- 10.1111/1755-0998.12559 may be a valid DOI for title: stratag: An R package for manipulating, summarizing and analysing population genetic data
- 10.1093/bioinformatics/btg412 may be a valid DOI for title: APE: analyses of phylogenetics and evolution in R language
- 10.1093/bioinformatics/btq706 may be a valid DOI for title: Phangorn: Phylogenetic analysis in R
- 10.1111/1365-2745.12869 may be a valid DOI for title: Intracontinental plant invader shows matching genetic and chemical profiles and might benefit from high defence variation within populations
- 10.1186/s12864-019-6073-7 may be a valid DOI for title: GENAVi: a shiny web application for gene expression normalization, analysis and visualization
- 10.1093/jis/1.1.8 may be a valid DOI for title: Individual and population variation in invertebrates revealed by Inter-simple Sequence Repeats (ISSRs)
- 10.1007/978-1-4615-5419-6_2 may be a valid DOI for title: Contributions of PCR-based methods to plant systematics and evolutionary biology
- 10.1016/0003-2697(91)90120-i may be a valid DOI for title: Fast and sensitive silver staining of DNA in polyacrylamide gels
- 10.1017/s0007485309990435 may be a valid DOI for title: Population genetic structure of economically important Tortricidae (Lepidoptera) in South Africa: a comparative analysis
- 10.1111/j.1462-2920.2004.00685.x may be a valid DOI for title: Assessing terminal restriction fragment length polymorphism suitability for the description of bacterial community structure and dynamics in hydrocarbon-polluted marine environments
- 10.1111/j.1574-6941.2008.00493.x may be a valid DOI for title: Evaluation of terminal-restriction fragment length polymorphism analysis in contrasting marine environments
- 10.1002/0470013192.bsa612 may be a valid DOI for title: Shepard diagram
- 10.1093/bioinformatics/14.1.68 may be a valid DOI for title: SplitsTree: analyzing and visualizing evolutionary data

INVALID DOIs

- None
```

**Comment by CJMvS** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value ".1111/mec.12844" (NAME) [#<BibTeX::Bibliography data=[3]>, "@", #<BibTeX::Entry >, {:title=>["{Phylogeography of \\textit{Heliconius cydno} and its closest relatives: disentangling their origin and diversification}"], :author=>["Arias, Carlos F and Salazar, Camilo and Rosales, Claudia and Kronforst, Marcus R and Linares, Mauricio and Bermingham, Eldredge and McMillan, W Owen"], :journal=>["Molecular Ecology"], :volume=>["23"], :number=>["16"], :pages=>["4137--4152"], :year=>["2014"], :doi=>"10"}]

**Comment by CJMvS** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.biocontrol.2020.104426 is OK
- 10.1111/j.1442-9993.1993.tb00438.x is OK
- 10.1111/mec.12844 is OK
- 10.1016/j.biocontrol.2011.05.008 is OK
- 10.1016/j.biocontrol.2017.08.015 is OK
- 10.1007/978-1-61779-870-2_10 is OK
- 10.1111/j.1365-294X.2004.02346.x is OK
- 10.1038/nrg1707 is OK
- 10.1080/10635150802044037 is OK
- 10.1111/1755-0998.12559 is OK
- 10.1093/bioinformatics/btg412 is OK
- 10.1093/bioinformatics/btq706 is OK
- 10.5169/seals-268384 is OK
- 10.1111/1365-2745.12869 is OK
- 10.1186/s12864-019-6073-7 is OK
- 10.1016/S0167-7012(00)00153-6 is OK
- 10.1626/pps.12.88 is OK
- 10.1017/S0007485309990435 is OK
- 10.1111/j.1462-2920.2004.00685.x is OK
- 10.1111/j.1574-6941.2008.00493.x is OK
- 10.1371/journal.pone.0184259 is OK
- 10.1002/9781118445112.stat06268.pub2 is OK
- 10.1093/bioinformatics/14.1.68 is OK

MISSING DOIs

- 10.1093/jis/1.1.8 may be a valid DOI for title: Individual and population variation in invertebrates revealed by Inter-simple Sequence Repeats (ISSRs)
- 10.1007/978-1-4615-5419-6_2 may be a valid DOI for title: Contributions of PCR-based methods to plant systematics and evolutionary biology
- 10.1016/0003-2697(91)90120-i may be a valid DOI for title: Fast and sensitive silver staining of DNA in polyacrylamide gels

INVALID DOIs

- 10.1128/AEM.67.10.4863–4873.2001 is INVALID
```

**Comment by CJMvS** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.biocontrol.2020.104426 is OK
- 10.1111/j.1442-9993.1993.tb00438.x is OK
- 10.1111/mec.12844 is OK
- 10.1016/j.biocontrol.2011.05.008 is OK
- 10.1016/j.biocontrol.2017.08.015 is OK
- 10.1007/978-1-61779-870-2_10 is OK
- 10.1111/j.1365-294X.2004.02346.x is OK
- 10.1038/nrg1707 is OK
- 10.1080/10635150802044037 is OK
- 10.1111/1755-0998.12559 is OK
- 10.1093/bioinformatics/btg412 is OK
- 10.1093/bioinformatics/btq706 is OK
- 10.5169/seals-268384 is OK
- 10.1111/1365-2745.12869 is OK
- 10.1186/s12864-019-6073-7 is OK
- 10.1093/jis/1.1.8 is OK
- 10.1007/978-1-4615-5419-6_2 is OK
- 10.1016/S0167-7012(00)00153-6 is OK
- 10.1016/0003-2697(91)90120-i is OK
- 10.1626/pps.12.88 is OK
- 10.1017/S0007485309990435 is OK
- 10.1111/j.1462-2920.2004.00685.x is OK
- 10.1111/j.1574-6941.2008.00493.x is OK
- 10.1371/journal.pone.0184259 is OK
- 10.1002/9781118445112.stat06268.pub2 is OK
- 10.1093/bioinformatics/14.1.68 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1128/AEM.67.10.4863–4873.2001 is INVALID
```

**Comment by CJMvS** [comment]
Thank you for the update @danielskatz. 
I managed to successfully compile the .md file.

**Comment by CJMvS** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02742/joss.02742/10.21105.joss.02742.pdf) :page_facing_up: :point_left:

**Comment by CJMvS** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.biocontrol.2020.104426 is OK
- 10.1111/j.1442-9993.1993.tb00438.x is OK
- 10.1111/mec.12844 is OK
- 10.1016/j.biocontrol.2011.05.008 is OK
- 10.1016/j.biocontrol.2017.08.015 is OK
- 10.1007/978-1-61779-870-2_10 is OK
- 10.1111/j.1365-294X.2004.02346.x is OK
- 10.1038/nrg1707 is OK
- 10.1080/10635150802044037 is OK
- 10.1111/1755-0998.12559 is OK
- 10.1093/bioinformatics/btg412 is OK
- 10.1093/bioinformatics/btq706 is OK
- 10.5169/seals-268384 is OK
- 10.1111/1365-2745.12869 is OK
- 10.1186/s12864-019-6073-7 is OK
- 10.1093/jis/1.1.8 is OK
- 10.1007/978-1-4615-5419-6_2 is OK
- 10.1016/S0167-7012(00)00153-6 is OK
- 10.1016/0003-2697(91)90120-i is OK
- 10.1626/pps.12.88 is OK
- 10.1017/S0007485309990435 is OK
- 10.1111/j.1462-2920.2004.00685.x is OK
- 10.1111/j.1574-6941.2008.00493.x is OK
- 10.1371/journal.pone.0184259 is OK
- 10.1002/9781118445112.stat06268.pub2 is OK
- 10.1093/bioinformatics/14.1.68 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@CJMvS Unfortunately, the JOSS editors have decided that this submission does not meet the substantial scholarly effort criterion for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
