### ISSUE TITLE
[PRE REVIEW]: kalepy: a python package for kernel density estimation and sampling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2746]
**Submitting author:** @lzkelley (<a href="http://orcid.org/0000-0002-6625-6450">Luke Zoltan Kelley</a>)
**Repository:** <a href="https://github.com/lzkelley/kalepy" target ="_blank">https://github.com/lzkelley/kalepy</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewers:** @williamjameshandley, @kexinrong
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lzkelley. **Currently, there isn't an JOSS editor assigned** to your paper.

@lzkelley if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.29 s (131.2 files/s, 55175.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          15           1521           1197           4177
Jupyter Notebook                10              0           5910           2011
Markdown                         5            165              0            547
TeX                              1             33              0            249
DOS Batch                        1              8              1             26
YAML                             1              4              4             23
reStructuredText                 1             22             16             17
Bourne Shell                     3              3             10             14
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                            38           1760           7144           7073
-------------------------------------------------------------------------------


Statistical information for the repository '422f05301b783c16c59f6d94' was
gathered on 2020/10/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
lzkelley                       221         14718           7825          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
lzkelley                   6895           46.8          9.8                9.78
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/1114019 is OK
- 10.1214/aoms/1177704472 is OK
- 10.1214/aoms/1177728190 is OK
- 10.1093/biomet/66.3.605 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/zenodo.592845 is OK
- 10.5281/zenodo.2392268 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.53 is OK
- 10.1093/mnras/staa2361 is OK
- 10.3847/2041-8213/abb1bf is OK
- 10.21105/joss.00024 is OK

MISSING DOIs

- 10.1093/imamat/20.3.335 may be a valid DOI for title: A review of some non-parametric methods of density estimation
- 10.1093/biomet/65.1.1 may be a valid DOI for title: Choosing the window width when estimating a density
- 10.1109/mcse.2007.55 may be a valid DOI for title: Matplotlib: A 2D graphics environment

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02746/joss.02746/10.21105.joss.02746.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02746/joss.02746/10.21105.joss.02746.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @arfon - are you able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @arfon as editor

**Comment by whedon** [comment]
@arfon has been invited to edit this submission.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @lzkelley, thanks for your submission to JOSS! A few questions to get us started here:

- Is this submission associated with a [AAS publication](https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing)?
- Could you please take a look at the DOI suggestions from Whedon [above](https://github.com/openjournals/joss-reviews/issues/2746#issuecomment-707890824) and if they are correct, add them to your BibTeX file?
- Do you have any suggestions for people who might be able to give this submission a good review?

**Comment by arfon** [comment]
:wave: @pmelchior - would you be willing to review this submission for JOSS? 

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The software (_kalepy: a python package for kernel density estimation and sampling_) is [here](https://github.com/lzkelley/kalepy) and the short paper [here](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02746/joss.02746/10.21105.joss.02746.pdf).

**Comment by pmelchior** [comment]
Sorry, swamped right now.

**Comment by arfon** [comment]
> Sorry, swamped right now.

NP, thanks for the quick response.

**Comment by lzkelley** [comment]
Hi @arfon sorry for the slow reply, and thanks for handling my submission!

> 👋 @lzkelley, thanks for your submission to JOSS! A few questions to get us started here:
> 
> * Is this submission associated with a [AAS publication](https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing)?
No, not in particular.
> * Could you please take a look at the DOI suggestions from Whedon [above](https://github.com/openjournals/joss-reviews/issues/2746#issuecomment-707890824) and if they are correct, add them to your BibTeX file?
Two of them were correct and have been added (in the `dev` branch).
> * Do you have any suggestions for people who might be able to give this submission a good review?
Unfortunately I don't.  I only know a few people who have worked on open-source projects and I don't think they'd be particularly well suited for this in particular.

**Comment by arfon** [comment]
:wave: @kexinrong @williamjameshandley - would you be willing to review this submission for JOSS? 

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The software (_kalepy: a python package for kernel density estimation and sampling_) is [here](https://github.com/lzkelley/kalepy) and the short paper [here](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02746/joss.02746/10.21105.joss.02746.pdf).

**Comment by williamjameshandley** [comment]
Happy to help out with this, should have time next week to start the review.

**Comment by kexinrong** [comment]
Also happy to help out and will start reviewing next week!

**Comment by arfon** [comment]
Wonderful, thanks so much @williamjameshandley and @kexinrong! I'll set up the review issue now.

**Comment by arfon** [comment]
@whedon add @williamjameshandley as reviewer

**Comment by whedon** [comment]
OK, @williamjameshandley is now a reviewer

**Comment by arfon** [comment]
@whedon add @kexinrong as reviewer

**Comment by whedon** [comment]
OK, @kexinrong is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2784.

**Comment by arfon** [comment]
@williamjameshandley, @kexinrong - see you over in #2784 where the actual review will take place.
