### ISSUE TITLE
[PRE REVIEW]: Terrain Shading: a module for analytical terrain visualisation in QGIS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2747]
**Submitting author:** @zoran-cuckovic (<a href="http://orcid.org/0000-0001-7626-4086">Zoran Čučković</a>)
**Repository:** <a href="https://github.com/zoran-cuckovic/QGIS-terrain-shading" target ="_blank">https://github.com/zoran-cuckovic/QGIS-terrain-shading</a>
**Version:** 0.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS zoran-cuckovic. **Currently, there isn't an JOSS editor assigned** to your paper.

zoran-cuckovic if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (376.2 files/s, 37810.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            585            700           1038
make                             2             62             53            244
QML                              4              0              0            176
Markdown                         3             57              0            134
DOS Batch                        1             21              1            133
Bourne Shell                     3             14             11             71
TeX                              1              7              0             66
XML                              1              0              0             13
Qt Linguist                      1              0              0             11
reStructuredText                 1              6              6              8
-------------------------------------------------------------------------------
SUM:                            34            752            771           1894
-------------------------------------------------------------------------------


Statistical information for the repository '354e41a2773ac2704b7d8e7c' was
gathered on 2020/10/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Zoran Čučković                  24          3156            858           98.55
zoran-cuckovic                   2            42             17            1.45

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Zoran Čučković             2323           73.6          6.1               18.25
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2747 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.geomorph.2012.12.015 is OK
- 10.5194/gmd-8-1991-2015 is OK
- 10.3390/rs3020398 is OK

MISSING DOIs

- 10.1109/proc.1981.11918 may be a valid DOI for title: Hill Shading and the Reflectance Map

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@zoran-cuckovic - your paper.md is misformatted - it needs to follow https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography (affiliations is a section with keyed entries). Please make changes, and also potentially add the DOI that whedon thinks is missing (if it's right), then use new comments with ```@whedon generate pdf``` to check the compilation of the paper, and ```@whedon check references``` to check the references again.

**Comment by danielskatz** [comment]
Additionally, because of the relatively small size of your code, the editors will discuss the scope to make sure it meets our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion before we start a review - this will likely take until the middle of next week.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by danielskatz** [comment]
@whedon generate pdf

checking to see if there have been any changes in the paper

**Comment by whedon** [comment]
PDF failed to compile for issue #2747 with the following error: 

 Error reading bibliography ./paper.bib (line 26, column 14):
unexpected "{"
expecting space or "="
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
It appears that there have been changes, but the author didn't check them here, so we've now passed one problem, but are stuck on another.  As mentioned previously
> use new comments with ```@whedon generate pdf``` to check the compilation of the paper, and ```@whedon check references``` to check the references again.

**Comment by zoran-cuckovic** [comment]
Hello, 
Yes, I've tidied up the bibliography file, it seemed to parse well... I'm checking it again.

**Comment by danielskatz** [comment]
Please use the whedon commands here when ready

**Comment by zoran-cuckovic** [comment]
It works now, there was a typo.

**Comment by danielskatz** [comment]
Please use the whedon commands **here** so that we can see the current version

**Comment by zoran-cuckovic** [comment]
Ok, let me try the bot

@whedon generate pdf

**Comment by danielskatz** [comment]
commands to whedon have to be at the top of a new comment

**Comment by zoran-cuckovic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02747/joss.02747/10.21105.joss.02747.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02747/joss.02747/10.21105.joss.02747.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@zoran-cuckovic - thanks for submitting to JOSS. After an initial review, it looks like this submission could do with a substantial amount of work before it could be considered for review in JOSS. 

In particular:
- It looks like this software isn't structured in a very user-friendly way. Could you take a look at the [Python packaging guidelines](https://packaging.python.org)
- It's not immediately clear how to run the tests for this project - please take a look at [this guide](https://docs.python-guide.org/writing/tests/).
- The paper doesn't clearly articulate the research challenge this software is addressing.

Given the amount of work likely necessary, I'm going to go ahead and reject the submission at this stage but we'd welcome a resubmission in the future if you're able to address the feedback above.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
