### ISSUE TITLE
[REVIEW]: POMDPStressTesting.jl: Adaptive Stress Testing for Black-Box Systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2749]
**Submitting author:** @mossr (<a href="http://orcid.org/0000-0003-2403-454X">Robert Moss</a>)
**Repository:** <a href="https://github.com/sisl/POMDPStressTesting.jl" target ="_blank">https://github.com/sisl/POMDPStressTesting.jl</a>
**Version:** v0.5.0
**Editor:** @sbenthall
**Reviewer:** @jarvist, @sambitdash
**Archive:** <a href="https://doi.org/10.5281/zenodo.4663471" target="_blank">10.5281/zenodo.4663471</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/04dc39ea89e90938727d789a2e402b0b/status.svg)](https://joss.theoj.org/papers/04dc39ea89e90938727d789a2e402b0b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/04dc39ea89e90938727d789a2e402b0b"><img src="https://joss.theoj.org/papers/04dc39ea89e90938727d789a2e402b0b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/04dc39ea89e90938727d789a2e402b0b/status.svg)](https://joss.theoj.org/papers/04dc39ea89e90938727d789a2e402b0b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/sisl/POMDPStressTesting.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jarvist & @sambitdash, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @sbenthall know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sisl/POMDPStressTesting.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mossr) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/sisl/POMDPStressTesting.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mossr) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jarvist, @sambitdash it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02749/joss.02749/10.21105.joss.02749.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02749/joss.02749/10.21105.joss.02749.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1007/978-3-319-97301-2_5 is OK
- 10.1109/DASC.2015.7311450 is OK
- 10.1109/IVS.2018.8500400 is OK
- 10.1007/978-3-540-75538-8_7 is OK
- 10.1023/A:1010091220143 is OK
- 10.1007/978-3-642-19835-9_21 is OK
- 10.1007/978-3-642-14295-6_17 is OK
- 10.1109/TCAD.2018.2858463 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by sbenthall** [comment]
Hello @jarvist and @sambitdash . This is a gentle reminder to please review this article.

**Comment by jarvist** [comment]
I just finished lecturing today, so I should be able to do this during the later half of this week.

**Comment by sambitdash** [comment]
Will review the paper this week and the software early next week. Thanks for the reminder @sbenthall.

**Comment by sambitdash** [comment]
Software paper reviewed and looks reasonable.

**Comment by sambitdash** [comment]
On the software documentation, a lot is lacking. It's not very clear what is the system all about. Why should someone use the library? It assumes prior knowledge but that cannot be expected of a software. If there is a prereq to be read before working on the library then that should be explained. There is a sample PDF file given to try the example, but generally a lot is not clear to me from the level of documentation given. Most likely I may not use the package if I just read the documentation unless I look into the algorithms and try a meaningful search on them to understand. 

It's completely a subordinate system to POMDPs.jl. So explanation of the system may be needed. Why a graybox or a blackbox interface needs to be explained as well. Once, the documentation is organized this will be a great addition to the Julia ecosystem.

**Comment by sbenthall** [comment]
Thank you @sambitdash 

@mossr I recommend you begin working to address the issues raised by this review.

**Comment by mossr** [comment]
Hey @sambitdash and @sbenthall, thank you both for your input! I agree, documentation should be centralized. I've already started to write formal documentation and will have a completed version up this afternoon.

**Comment by mossr** [comment]
@sambitdash I've pushed comprehensive documentation that addresses the concerns you raised and checks all the necessary boxes above. 

https://sisl.github.io/POMDPStressTesting.jl/dev/

Thank you again for the constructive input! Let me know if you have any more questions or would like additional clarifications.

**Comment by jarvist** [comment]
> @sambitdash I've pushed comprehensive documentation that addresses the concerns you raised and checks all the necessary boxes above.

This is much better! 
I think it could be improved still further though - it's probably worth expanding the POMDPS acronym, and explaining how this technique is used; and also defining what a 'black-box' system is in this context; and for that matter what counts as 'failure'. 

Can the Walk1D example be simplified any further? It's a bit confusing that the first thing the notebook starts talking about is how the problem is set up as a 'Gray box'.

**Comment by mossr** [comment]
@jarvist I agree with your comments—thank you for these. I've since added a paragraph describing the POMDP acronym and why we use it, and added a section on the definition of "failure" and the "distance" metric, all under the "Home" section here: 
- **Home**: https://sisl.github.io/POMDPStressTesting.jl/dev/

Note that I already have two sections describing the "black-box" and "gray-box" definitions, again under "Home".

The Walk1D example *is* the simplest example we could come up with, but I've since included references back to the gray-box/black-box sections in the documentation that help describe these components. Also, I'd refer you to the "Example" section of the documentation which helps define the Walk1D problem definitions (i.e. the system/environment/failure/distance), which I also included in the notebook to centralize that information.
- **Example**: https://sisl.github.io/POMDPStressTesting.jl/dev/example/
- **Notebook**: https://nbviewer.jupyter.org/github/sisl/POMDPStressTesting.jl/blob/master/notebooks/Walk1D.ipynb

**Comment by jarvist** [comment]
Dear @mossr , that's great! It's extremely clear now, and I think would answer all the questions that arose when I first read through it. The lay-person definition followed by an example is very easy to follow. I'm certainly happy with this documentation now. 

Apologies for the sluggishness of doing my review, I'll install the software, check the repo & read the paper as soon as I can fit it in.

**Comment by mossr** [comment]
Thank you @jarvist and @sambitdash. I'm applying to PhD programs at the end of this month, so if there's anything I can do to help expedite this review please let me know and I'd be happy to address them.

**Comment by sbenthall** [comment]
@jarvist have you been able to make any progress towards your review?

**Comment by mossr** [comment]
Hi @sbenthall, just checking on the status of this review.

**Comment by jarvist** [comment]
Ah yes, sorry - I'll get on this ASAP.

**Comment by jarvist** [comment]
@mossr are the fairly heavy GUI requirements of the package (Seaborn, Pyplot I presume) necessary? They are currently causing a failure for me at the 'Precompiling POMDPStressTesting' just after using, I think due to some automatic Python compile failing on the backend. Generally these requirements can make the code fragile for installation, and be quite limiting in some HPC environments (e.g. when no X is installed). 

Is plotting like this integral to the package, or could it be provided separately / via Plot recipes? (https://docs.juliaplots.org/latest/recipes/)

**Comment by mossr** [comment]
@jarvist you're absolutely right—the plotting should be separate and is not vital to the core package. I'll work on something right now to bypass the plotting unless you already load in those packaged. Hang tight.

**Comment by mossr** [comment]
@jarvist I relaxed the PyPlot/Seaborn plotting dependencies using Requires.jl (and subsequently updated the example Jupyter notebook and documentation to reflect this design choice). This is tagged in a new release v0.4.4 (master).

Thank you for the heads up—I agree that the dependency on Python for plotting would be an unnecessary (and unfortunate) bottleneck for many applications of this package.

**Comment by sbenthall** [comment]
@sambitdash @jarvist How is this looking to you now?

**Comment by sambitdash** [comment]
@sbenthall, I will complete the review by next weekend. Sorry for the delay from my side but due to the overheads earlier identified by @jarvist, it was not easy setting up the test environment. Now that the bottlenecks are removed, I should be able to complete the review. Thanks @mossr for making sure all the changes suggested are taken care of now.

**Comment by mossr** [comment]
@sbenthall I just made it _even easier_ for you to test the entire package, avoiding the plotting. So when you do start testing, pull the latest v0.4.5 (on master) and this will make your life much easier :)

Thanks again for getting around to this. Let me know if you run into any hiccups.

**Comment by sbenthall** [comment]
@sambitdash This is a gentle nudge reminding you about this review :)

**Comment by sambitdash** [comment]
@sbenthall reviewed the documentation. Need to install and test the software.

**Comment by sambitdash** [comment]
Bugs in the repo related to the missing docstrings. https://github.com/sisl/POMDPStressTesting.jl/issues/7

**Comment by mossr** [comment]
@sambitdash fixed with https://github.com/sisl/POMDPStressTesting.jl/commit/2f23550c65148d48d70d853f3bc055f13064979c

**Comment by jarvist** [comment]
Documentation & JOSS paper are now very nicely written ^:)

**Comment by jarvist** [comment]
Apologies @sambitdash  - I think I accidentally ticked off some of your bits of the review, I tried to undo this, but I may now have unticked items you had confirmed for!

**Comment by jarvist** [comment]
`PyPlot` is a hidden requirement for the tests to run, it appears to get called in `Walk2D`. This causes the tests to error out when halfway complete, on a new installation on Julia 1.6.0-rc2.

**Comment by mossr** [comment]
@jarvist great catch! That `PyPlot` code is unused anyhow, so I've just removed it from the `Walk2D` test (updated on master).

**Comment by jarvist** [comment]
I edited it out by hand, and then the tests ran to completion. 

I'm finished with my review now - it looks like a well put together & described package! 🎉

**Comment by mossr** [comment]
Wonderful to hear! Thank you for taking the time to review this!

**Comment by sambitdash** [comment]
> Apologies @sambitdash - I think I accidentally ticked off some of your bits of the review, I tried to undo this, but I may now have unticked items you had confirmed for!

Fixed my comments. No worries.

**Comment by jarvist** [comment]
@sbenthall I think we should be good to go ^_^

**Comment by sambitdash** [comment]
@sbenthall I ticked all the items related to the software as well. So we should be good to go.

**Comment by sbenthall** [comment]
Awesome! With both reviewers recommending publication, we can proceed with the finalizing steps.

**Comment by sbenthall** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02749/joss.02749/10.21105.joss.02749.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02749/joss.02749/10.21105.joss.02749.pdf) :page_facing_up: :point_left:

**Comment by sbenthall** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1007/978-3-319-97301-2_5 is OK
- 10.1109/DASC.2015.7311450 is OK
- 10.1109/IVS.2018.8500400 is OK
- 10.1007/978-3-540-75538-8_7 is OK
- 10.1023/A:1010091220143 is OK
- 10.1007/978-3-642-19835-9_21 is OK
- 10.1007/978-3-642-14295-6_17 is OK
- 10.1109/TCAD.2018.2858463 is OK

MISSING DOIs

- 10.1109/dasc50938.2020.9256730 may be a valid DOI for title: Adaptive Stress Testing of Trajectory Predictions in Flight Management Systems

INVALID DOIs

- None
```

**Comment by sbenthall** [comment]
@mossr  Can you please address the missing DOI identified by Whedon?

**Comment by mossr** [comment]
@sbenthall addressed and pushed. Should be all set.

**Comment by sbenthall** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02749/joss.02749/10.21105.joss.02749.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02749/joss.02749/10.21105.joss.02749.pdf) :page_facing_up: :point_left:

**Comment by sbenthall** [comment]
OK. This looks great.

@mossr couldyou please:

- make a tagged release
- archive it so that it has a DOI
- report the version number and archive DOI in the review thread.

**Comment by mossr** [comment]
@sbenthall I've tagged and released a new version v0.5.0. How would you recommend archiving it and producing a DOI?

**Comment by sbenthall** [comment]
I recommend uploading the software bundle to Zenodo.
It should provide a DOI.
https://zenodo.org/

**Comment by mossr** [comment]
Thank you, @sbenthall.

- Tagged release of [v0.5.0](https://github.com/sisl/POMDPStressTesting.jl/releases/tag/v0.5.0)
- Archived with a DOI of [10.5281/zenodo.4663471](https://zenodo.org/record/4663471)

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by sbenthall** [comment]
@whedon set 10.5281/zenodo.4663471 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4663471" target="_blank">10.5281/zenodo.4663471</a> is the archive.

**Comment by sbenthall** [comment]
@whedon set v0.5.0 as version

**Comment by whedon** [comment]
OK. v0.5.0 is the version.

**Comment by sbenthall** [comment]
Fantastic. Thanks @mossr

**Comment by sbenthall** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1007/978-3-319-97301-2_5 is OK
- 10.1109/DASC.2015.7311450 is OK
- 10.1109/DASC50938.2020.9256730 is OK
- 10.1109/IVS.2018.8500400 is OK
- 10.1007/978-3-540-75538-8_7 is OK
- 10.1023/A:1010091220143 is OK
- 10.1007/978-3-642-19835-9_21 is OK
- 10.1007/978-3-642-14295-6_17 is OK
- 10.1109/TCAD.2018.2858463 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2207

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2207, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by sbenthall** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @sbenthall, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by danielskatz** [comment]
I'll do this later today, after a proof-read...

**Comment by danielskatz** [comment]
@mossr  - there are a few small changes in https://github.com/sisl/POMDPStressTesting.jl/pull/8 - if you can merge these, I'll go ahead and finish the acceptance and publishing

**Comment by mossr** [comment]
@danielskatz all set!

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2212

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2212, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1007/978-3-319-97301-2_5 is OK
- 10.1109/DASC.2015.7311450 is OK
- 10.1109/DASC50938.2020.9256730 is OK
- 10.1109/IVS.2018.8500400 is OK
- 10.1007/978-3-540-75538-8_7 is OK
- 10.1023/A:1010091220143 is OK
- 10.1007/978-3-642-19835-9_21 is OK
- 10.1007/978-3-642-14295-6_17 is OK
- 10.1109/TCAD.2018.2858463 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1380210907268194306) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2213
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02749](https://doi.org/10.21105/joss.02749)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by mossr** [comment]
Thank you all for your time during this review!

**Comment by danielskatz** [comment]
Congratulations to @mossr (Robert Moss)!!

And thanks to @jarvist and @sambitdash for reviewing and @sbenthall for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02749/status.svg)](https://doi.org/10.21105/joss.02749)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02749">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02749/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02749/status.svg
   :target: https://doi.org/10.21105/joss.02749
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02749/status.svg)](https://doi.org/10.21105/joss.02749)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
