### ISSUE TITLE
[PRE REVIEW]: kerasR: R Interface to the Keras Deep Learning Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#275]
**Submitting author:** @statsmaths (<a href="http://orcid.org/0000-0003-0576-0669">Taylor Arnold</a>)
**Repository:** <a href="https://github.com/statsmaths/kerasR" target ="_blank">https://github.com/statsmaths/kerasR</a>
**Version:** 0.6.1
**Editor:** @karthik
**Reviewer:** @kaneplusplus

**Author instructions**

Thanks for submitting your paper to JOSS @statsmaths. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@statsmaths if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @karthik - would you be willing to edit this submission?

**Comment by karthik** [comment]
@arfon sure

**Comment by karthik** [comment]
@statsmaths While I seek reviewers, are there any folks you are able to suggest?

**Comment by statsmaths** [comment]
Here are a few people who would be good reviewers but were not involved with the package itself: Mike Kane (@kaneplusplus), Akitaka Matsuo (@amatsuo), Adam Obeng (@adamobeng).

**Comment by karthik** [comment]
@statsmaths Thanks for those suggestions. Quick update that I'm trying to get this sorted out asap.

**Comment by karthik** [comment]
@whedon assign @kaneplusplus as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kaneplusplus

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/296. Feel free to close this issue now!

**Comment by karthik** [comment]
@kaneplusplus Thanks very much for agreeing to review this submission 🙏. I'm going to close this issue since we have now assigned you. Please continue your review at #296 and let me know if you have any questions or run into issues.

**Comment by kaneplusplus** [comment]
@karthik Got it. Thanks for the update.
