### ISSUE TITLE
[REVIEW]: Your: Your Unified Reader

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2750]
**Submitting author:** @KshitijAggarwal (<a href="http://orcid.org/0000-0002-2059-0525">Kshitij Aggarwal</a>)
**Repository:** <a href="https://github.com/thepetabyteproject/your" target ="_blank">https://github.com/thepetabyteproject/your</a>
**Version:** 0.6.0
**Editor:** @dfm
**Reviewer:** @pravirkr, @paulray
**Archive:** <a href="https://doi.org/10.5281/zenodo.4269947" target="_blank">10.5281/zenodo.4269947</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/798844ebd352f563de28bb75515da674/status.svg)](https://joss.theoj.org/papers/798844ebd352f563de28bb75515da674)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/798844ebd352f563de28bb75515da674"><img src="https://joss.theoj.org/papers/798844ebd352f563de28bb75515da674/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/798844ebd352f563de28bb75515da674/status.svg)](https://joss.theoj.org/papers/798844ebd352f563de28bb75515da674)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/thepetabyteproject/your" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@pravirkr & @paulray, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/thepetabyteproject/your">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@KshitijAggarwal) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/thepetabyteproject/your">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@KshitijAggarwal) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @pravirkr, @paulray it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/mnras/staa1927 is OK
- 10.1111/j.1745-3933.2010.00882.x is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1109/mcse.2011.37 is OK
- 10.1071/AS04022 is OK
- 10.1145/2833157.2833162 is OK
- 10.1111/j.1365-2966.2012.20622.x is OK
- 10.1093/mnras/staa1856 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02750/joss.02750/10.21105.joss.02750.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02750/joss.02750/10.21105.joss.02750.pdf) :page_facing_up: :point_left:

**Comment by pravirkr** [comment]
The software package `your` is well-organized with a nice interface. The documentation is very detailed with lots of good examples. This package is going to be very useful for the FRB/radio transients science. 

I have opened the following issues within the main repository:
- thepetabyteproject/your#46
- thepetabyteproject/your#47
- thepetabyteproject/your#48
- thepetabyteproject/your#49

Most of these are very minor issues. Apologies for nitpicking (reviewing for the first time).

**Comment by KshitijAggarwal** [comment]
@pravirkr, thanks for the issues. We have addressed those from our end, feel free to take a look and close them.

**Comment by paulray** [comment]
I'm supposed to answer this question: "Does the full list of paper authors seem appropriate and complete?"
I don't know how to judge that, other than from git commits. Is there a statement of the various author contributions somewhere? I didn't see it in the paper.

**Comment by KshitijAggarwal** [comment]
Hi @paulray, I can answer that here:
@KshitijAggarwal  @devanshkv: equal contribution in terms of code, ideas, discussion, structure and documentation
@scottransom: original author of [psrfits](https://github.com/scottransom/presto/blob/master/python/presto/psrfits.py), which was modified for `your`
@demorest: original author of [pysigproc](https://github.com/demorest/pysigproc/blob/master/pysigproc.py), which was modified for `your`
@ReshmaAnnaThomas and @wcfiore: wrote + contributed to `filwriter.py`
@josephwkania: worked on RFI mitigation functions, `your_viewer`
@xiggystardust, Duncan Lorimer, Maura McLaughlin, @nategarver-daniels: contributed through discussions and structure 
@rwharton: original author of [fitswriter](https://github.com/rwharton/fil2psrfits), which was then modified for `your`

**Comment by paulray** [comment]
Thanks, that is extremely helpful!

**Comment by paulray** [comment]
Regarding my review, I want to disclose the following potential COIs. 

- Scott Ransom and I are longtime collaborators. We are co-Is on several funded guest observer proposals and work closely together on the open source PINT project and many aspects of Fermi and pulsar science.
- Paul Demorest is a collaborator of mine on several projects.
- Maura McLaughlin is a close collaborator on Fermi pulsar searches and some other projects.
- All of the above people as well as Kshitij Aggarwal, Sarah Burke-Spolaor, Dunc Lorimer, Nate Garver-Daniels, and William Fiore are (or were) members of the NANOGrav collaboration that I am a full member of. We all collaborate and co-author many papers together.

I just now realized that the submitting author is a NANOGrav member.  I don't think that is a serious conflict since I wasn't even aware of it. According to the statement above, my other potential COIs generally have a largely advisory role in this project or have prior code that was subsumed into this project.  

I don't think these potential COIs affect my ability to make an impartial review, so I propose that they be waived.

**Comment by dfm** [comment]
@paulray: Thanks for bringing these up! I agree that these potential conflicts seem ok to be waived.

@KshitijAggarwal: do you or co-authors don't have any concerns about this? Please feel free to let me know here or offline via email if you'd prefer. Thanks!

**Comment by KshitijAggarwal** [comment]
@dfm @paulray: We don't have any concerns regarding this.

**Comment by paulray** [comment]
I enjoyed reviewing the paper and the code and trying it out on same data I had. I found it well explained, easy to install and the documentation was very clear. Nice work!

**Comment by KshitijAggarwal** [comment]
@pravirkr @dfm, we are submitting an NSF proposal for a project (the petabyte project) which is going to rely on this library. The NSF proposal is due pretty soon. I also noticed that only a few checklist items are left in the review. So I wanted to ask if it would be possible to complete this review in the next day or so? This way we can properly cite it in our proposal, and also upload it to arxiv. 
If not, is it okay if we upload the paper to arxiv before the review process is complete?

**Comment by dfm** [comment]
You're welcome to post the pre-print to ArXiv, but sometimes ArXiv doesn't accept JOSS papers so no guarantees that it will work!

@pravirkr: you definitely shouldn't feel pressured to finish your review faster than planned!

**Comment by pravirkr** [comment]
@dfm: Thanks. I was waiting for the resolution of the above issues.
@KshitijAggarwal: Thanks for addressing the issues. Looks good now! The only thing left to do IMO is to release the updated version (0.5.9, I guess).

I also recommend acceptance of this work.

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02750/joss.02750/10.21105.joss.02750.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02750/joss.02750/10.21105.joss.02750.pdf) :page_facing_up: :point_left:

**Comment by dfm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/mnras/staa1927 is OK
- 10.1111/j.1745-3933.2010.00882.x is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1109/mcse.2011.37 is OK
- 10.1071/AS04022 is OK
- 10.1145/2833157.2833162 is OK
- 10.1111/j.1365-2966.2012.20622.x is OK
- 10.1093/mnras/staa1856 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@pravirkr, @paulray: Thanks for your reviews!!

@KshitijAggarwal: I'm going to go through the paper and do some final checks. Then I'll give you a few instructions to prepare for final review. This will include minting a new release so no need to do that yet!

**Comment by KshitijAggarwal** [comment]
@pravirkr,  @paulray:  thanks for the reviews and useful comments! 

@dfm: Thanks and that sounds good!

**Comment by dfm** [comment]
@KshitijAggarwal: I've just submitted a small pull request with some formatting changes. After you take a look at that, here are the steps to run:

1. Comment `@whedon generate pdf` on this thread and carefully read through the manuscript to make sure that you're happy with it because it can be hard to update later. You should especially double check author names and affiliations.
2. Update the version number on the software and create an archive of that release (using Zenodo or similar) and report the archive DOI and new version number to this thread. **NOTE: The title and author list in the archive metadata must exactly match this manuscript** (you can generally update the metadata even after the archive has been made).

Let me know if you have any issues or questions!

**Comment by KshitijAggarwal** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02750/joss.02750/10.21105.joss.02750.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02750/joss.02750/10.21105.joss.02750.pdf) :page_facing_up: :point_left:

**Comment by KshitijAggarwal** [comment]
@dfm, here is the DOI of the archive: 10.5281/zenodo.4269947, and the new version number is 0.6.0

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4269947.svg)](https://doi.org/10.5281/zenodo.4269947)

I have edited the title and author list in the archive to be exactly the same as that in this manuscript.

**Comment by dfm** [comment]
@whedon set 10.5281/zenodo.4269947 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4269947" target="_blank">10.5281/zenodo.4269947</a> is the archive.

**Comment by dfm** [comment]
@whedon set 0.6.0 as version

**Comment by whedon** [comment]
OK. 0.6.0 is the version.

**Comment by dfm** [comment]
@KshitijAggarwal: I found a few more remaining formatting issues with the manuscript. Take a look at that PR and then we should be good to go!

**Comment by devanshkv** [comment]
@dfm merged!

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02750/joss.02750/10.21105.joss.02750.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02750/joss.02750/10.21105.joss.02750.pdf) :page_facing_up: :point_left:

**Comment by dfm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/mnras/staa1927 is OK
- 10.1111/j.1745-3933.2010.00882.x is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1071/AS04022 is OK
- 10.1145/2833157.2833162 is OK
- 10.1111/j.1365-2966.2012.20622.x is OK
- 10.1093/mnras/staa1856 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/mnras/staa1927 is OK
- 10.1111/j.1745-3933.2010.00882.x is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1071/AS04022 is OK
- 10.1145/2833157.2833162 is OK
- 10.1111/j.1365-2966.2012.20622.x is OK
- 10.1093/mnras/staa1856 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1907

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1907, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by dfm** [comment]
An editor-in-chief will take a final look at this submission and then we should be good to go.

Thanks again @pravirkr and @paulray for your reviews!!

**Comment by devanshkv** [comment]
Thanks, @dfm, @pravirkr, and @paulray.

**Comment by KshitijAggarwal** [comment]
Thanks a lot, @dfm, @pravirkr, and @paulray!!

**Comment by josephwkania** [comment]
Thanks @dfm, @pravirkr, @paulray! 😊

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1328044580009369600) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1912
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02750](https://doi.org/10.21105/joss.02750)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @KshitijAggarwal! Many thanks to editor @dfm and reviewers @pravirkr and @paulray for your time and expertise!! 🎉

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02750/status.svg)](https://doi.org/10.21105/joss.02750)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02750">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02750/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02750/status.svg
   :target: https://doi.org/10.21105/joss.02750
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02750/status.svg)](https://doi.org/10.21105/joss.02750)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by KshitijAggarwal** [comment]
Thanks a lot, everyone!!! :) :)
