### ISSUE TITLE
[PRE REVIEW]: HexWatershed

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2751]
**Submitting author:** @changliao1025 (<a href="http://orcid.org/0000-0002-7348-8858">Chang Liao</a>)
**Repository:** <a href="https://github.com/pnnl/hexwatershed" target ="_blank">https://github.com/pnnl/hexwatershed</a>
**Version:** Version 1.0
**Editor:** @kbarnhart
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @changliao1025. **Currently, there isn't an JOSS editor assigned** to your paper.

@changliao1025 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=3.87 s (9.8 files/s, 58178.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                             11              0              0         218965
C++                             10            476            716           3087
C/C++ Header                     9            157            185            411
INI                              1              1              0            381
make                             1            144             79            278
CMake                            2             22              7            116
Markdown                         1             36              0             69
JSON                             1              0              0             60
Bourne Shell                     2              0              0             10
-------------------------------------------------------------------------------
SUM:                            38            836            987         223377
-------------------------------------------------------------------------------


Statistical information for the repository 'e081ee93cc6d538862d8f9fa' was
gathered on 2020/10/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Chang Liao                      11          4176           1221           50.28
changliao1025                   16          3068           2268           49.72

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chang Liao                 5022          120.3         12.7               17.96
changliao1025                10            0.3         25.2                0.00
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #2751 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@changliao1025 - where is your paper?

See https://joss.readthedocs.io/en/latest/submitting.html#typical-paper-submission-flow and specifically https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by danielskatz** [comment]
It looks like it might be in the README?  But the README should be the README, and the paper should be in a different file, usually paper.md along with any needed references in a .bib file

**Comment by danielskatz** [comment]
I also notice that there is no open source license in the repo  - this is another part of https://joss.readthedocs.io/en/latest/submitting.html#typical-paper-submission-flow

**Comment by danielskatz** [comment]
I'm going to mark this as paused for now - please ping us here when fixes are made

**Comment by changliao1025** [comment]
Hi, @danielskatz, I have made edits to the repository as you suggested. Please let me know your further suggestions.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2751 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (340cee360f20054ecb6766fd/paper.md): could not find expected ':' while scanning a simple key at line 28 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@changliao1025  - The paper does not compile - please check the format of the paper against the example, and then use ```@whedon generate pdf``` - and repeat until it looks right to you.

**Comment by danielskatz** [comment]
@whedon check references

**Comment by danielskatz** [comment]
@whedon check references

**Comment by danielskatz** [comment]
👋 @openjournals/dev - Why doesn't the reference check work here?

**Comment by changliao1025** [comment]
Sure, I will test with the bot first and then get back.

**Comment by changliao1025** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2751 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (27048a8315bbcd2e5886ca83/paper.md): could not find expected ':' while scanning a simple key at line 28 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by changliao1025** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: :point_left:

**Comment by changliao1025** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: :point_left:

**Comment by changliao1025** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: :point_left:

**Comment by changliao1025** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: :point_left:

**Comment by changliao1025** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: :point_left:

**Comment by changliao1025** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: :point_left:

**Comment by changliao1025** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02751/joss.02751/10.21105.joss.02751.pdf) :page_facing_up: :point_left:

**Comment by changliao1025** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1002/hyp.3360050107 may be a valid DOI for title: On the extraction of channel networks from digital elevation data
- 10.1109/mcise.2002.1032427 may be a valid DOI for title: Climate modeling with spherical geodesic grids
- 10.3133/tm6d1 may be a valid DOI for title: GSFLOW, Coupled Ground-Water and Surface-Water Flow Model Based on the Integration of the Precipitation-Runoff Modeling System (PRMS) and the Modular Ground-Water Flow Model (MODFLOW-2005)
- 10.3133/sir20095233 may be a valid DOI for title: Evaluation of catchment delineation methods for the medium-resolution national hydrography dataset
- 10.1175/2009mwr2917.1 may be a valid DOI for title: Voronoi, Delaunay, and block-structured mesh refinement for solution of the shallow-water equations on the sphere
- 10.1016/j.cageo.2013.04.024 may be a valid DOI for title: Priority-flood: An optimal depression-filling and watershed-labeling algorithm for digital elevation models
- 10.5194/isprs-archives-xlii-4-687-2018 may be a valid DOI for title: The comparison of drainage network extraction between square and hexagonal grid-based dem
- 10.3138/cart.54.1.2018-0022 may be a valid DOI for title: Central Place Indexing: Hierarchical Linear Indexing Systems for Mixed-Aperture Hexagonal Discrete Global Grid Systems

INVALID DOIs

- https://doi.org/10.1016/j.envsoft.2020.104702 is INVALID because of 'https://doi.org/' prefix
```

**Comment by changliao1025** [comment]
@danielskatz , I have fixed the bug in the files and both paper.md and references were compiled successfully.

**Comment by danielskatz** [comment]
👋 @kbarnhart - given your volunteering in the editorial discussion, I'm going to go ahead and assign this to you - let me know if that's a problem.

**Comment by danielskatz** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
Sounds good @danielskatz thanks!

**Comment by kbarnhart** [comment]
@changliao1025 the first step in the JOSS submission/review process is that the topical editor (me) looks though the submission as an initial check. I have a couple of questions:

- Is there a place where documentation and example usage of HexWatershed are provided
- Is there a place where instructions for testing that HexWatershed has been installed correctly?

**Comment by kbarnhart** [comment]
@changliao1025 after discussion with the JOSS editorial board I have decided to reject this submission for the following reasons:

1. Violation of [JOSS ethics guidelines](https://joss.theoj.org/about#ethics). Specifically that the submitted paper is almost entirely composed of text previously published in Liao et al. (2020). 

     Liao, C., Tesfa, T., Duan, Z., & Leung, L. R. (2020). Watershed delineation on a hexagonal mesh grid. Environmental Modelling & Software, 104702. https://doi.org/10.1016/j.envsoft.2020.104702

2. Missing major elements:
    a. No documentation
    b. No examples of use
    c. No instructions for testing

If you have any questions or clarifications about this decision, please let me know here and I will do my best to further explain.

**Comment by kbarnhart** [comment]
@openjournals/joss-eics I've recommended that this submission be rejected.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by changliao1025** [comment]
> @changliao1025 after discussion with the JOSS editorial board I have decided to reject this submission for the following reasons:
> 
> 1. Violation of [JOSS ethics guidelines](https://joss.theoj.org/about#ethics). Specifically that the submitted paper is almost entirely composed of text previously published in Liao et al. (2020).
>    Liao, C., Tesfa, T., Duan, Z., & Leung, L. R. (2020). Watershed delineation on a hexagonal mesh grid. Environmental Modelling & Software, 104702. https://doi.org/10.1016/j.envsoft.2020.104702
> 2. Missing major elements:
>    a. No documentation
>    b. No examples of use
>    c. No instructions for testing
> 
> If you have any questions or clarifications about this decision, please let me know here and I will do my best to further explain.

A user guide will be added to the repository shortly. We collected some user feedback to make sure all the necessary information are presented in the user guide.
This submission is mainly focusing on the technical part of the model instead of the scientific implication, that is why lots of text are the same or similar to our other publication, which does not provide details of the software.

**Comment by kbarnhart** [comment]
@changliao1025 thanks for the comment. As indicated above, this submission has been rejected. 

I'd recommend that you take a close look at the [JOSS submission requirements](https://joss.readthedocs.io/en/latest/submitting.html?#submission-requirements) and the [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html). As the review criteria state, the JOSS review process has reviewers comment on the documentation (typically both API and some sort of narrative documentation are expected). 

If you think you can revise your submission to meet the requirements, including revising the paper so that its text is distinct from the text of the prior publication, then consider re-submitting to JOSS. At that time the submission would be re-considered as a new submission. 

If you have questions or clarifications about re-submission,  I'd recommend you make a pre-submission inquiry ([as described here](https://joss.theoj.org/about#submitting)). Feel free to tag me there. 

If you have further questions or clarifications about why I decided to reject the submission, please feel free to voice those on this thread and I'll do my best to answer.

**Comment by changliao1025** [comment]
Thanks for the suggestions, I will revise the repository following the instructions and then re-submit.
