### ISSUE TITLE
[PRE REVIEW]: TDAsweep: A Novel Dimensionality Reduction Method for Image Classification Tasks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2753]
**Submitting author:** @matloff (<a href="http://orcid.org/0000-0001-9179-6785">Norman Matloff</a>)
**Repository:** <a href="https://github.com/matloff/tdaImage" target ="_blank">https://github.com/matloff/tdaImage</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @matloff. **Currently, there isn't an JOSS editor assigned** to your paper.

@matloff if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (549.8 files/s, 52464.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               15            165            333            591
Markdown                         3            140              0            448
TeX                              1             19              0            117
-------------------------------------------------------------------------------
SUM:                            19            324            333           1156
-------------------------------------------------------------------------------


Statistical information for the repository 'ed820fc4b709f4b362446564' was
gathered on 2020/10/15.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02753/joss.02753/10.21105.joss.02753.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02753/joss.02753/10.21105.joss.02753.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1146/annurev-statistics-031017-100045 is OK
- 10.1371/journal.pone.0217413 is OK
- 10.1007/978-3-642-04438-0_7 is OK
- 10.1109/51.473275 is OK
- 10.1038/srep27988 is OK
- 10.1109/ijcnn.2017.7966217 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @matloff - note that we require an OSI-approved open source license, usually in the form of a LICENSE file in the repo.

Additionally, given the relatively small size of the software, the editors will now discuss if this meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. 

We should have a decision in about a week.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by matloff** [comment]
The license is shown as GPL (>= 2) in the DESCRIPTION FILE.

i would suggest Gunnar Carlsson <gunnar@ayasdi.com>  of the Stanford Dept.
of Mathematics as a reviewer.

Norm

**Comment by kyleniemeyer** [comment]
@matloff Unfortunately, the JOSS editors have decided that this submission does not meet the substantial scholarly effort criterion for review by JOSS; while useful, it is quite small. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
