### ISSUE TITLE
[PRE REVIEW]: The Pulsar Signal Simulator: A Python package for simulating radio signal data from pulsars

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2754]
**Submitting author:** @Hazboun6 (<a href="http://orcid.org/0000-0003-2742-3321">Jeffrey Hazboun</a>)
**Repository:** <a href="https://github.com/PsrSigSim/PsrSigSim" target ="_blank">https://github.com/PsrSigSim/PsrSigSim</a>
**Version:** v1.0.0
**Editor:** @mbobra
**Reviewers:** @JBorrow, @arjunsavel
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Hazboun6. **Currently, there isn't an JOSS editor assigned** to your paper.

@Hazboun6 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.40 s (194.3 files/s, 33744.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          39            922           1978           3091
reStructuredText                21            803           1055            773
Jupyter Notebook                 8              0           3131            593
TeX                              1             11              0            260
DOS Batch                        1             29              1            212
make                             2             47              6            211
JSON                             1              0              0             86
Markdown                         1             10              0             77
INI                              1              4              3             29
YAML                             2              8             15             15
-------------------------------------------------------------------------------
SUM:                            77           1834           6189           5347
-------------------------------------------------------------------------------


Statistical information for the repository '3600b8b07b091c9db5f713db' was
gathered on 2020/10/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Amelia Henkel                    1            61             10            0.20
Brent Shapiro-Albert            71          3380            303           10.58
Cassidy Wagner                   4           230             31            0.75
Hazboun6                        84          2187           3635           16.73
Jacob Hesse                     16           317             60            1.08
Jeff Hazboun                     6           202             16            0.63
Jeffrey Hazboun                101          4139           2179           18.15
Joe Romano                       2             7              4            0.03
Min Young                        9           390            133            1.50
Paul T. Baker                   50          9498           7958           50.15
paulthebaker                     5            36             30            0.19

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Amelia Henkel                 8           13.1         38.6               25.00
Brent Shapiro-Albert       3085           91.3          6.5               18.22
Cassidy Wagner                2            0.9         38.6                0.00
Hazboun6                   1325           60.6         15.3               12.15
Jacob Hesse                   9            2.8         29.0               22.22
Jeffrey Hazboun             203            4.9         41.4                9.85
Joe Romano                    3           42.9         34.8                0.00
Paul T. Baker              1356           14.3         27.2               22.57
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/217709a0 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1007/s00159-019-0115-7 is OK
- 10.1093/nsr/nwx126 is OK
- 10.1086/181708 is OK
- 10.1086/159690 is OK
- 10.5281/zenodo.3756164 is OK
- 10.1017/pasa.2020.19 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02754/joss.02754/10.21105.joss.02754.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02754/joss.02754/10.21105.joss.02754.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
Note: This is associated with a AAS submission

**Comment by danielskatz** [comment]
👋 @mbobra - would you be willing to edit this submission? You were suggested by the authors.

**Comment by danielskatz** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by mbobra** [comment]
@whedon assign @mbobra as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by Hazboun6** [comment]
Thanks @danielskatz for getting things started and @mbobra for agreeing to be our editor! 
I have two suggestions of reviewers from your list:  garrettj403, arjunsavel

And here is one suggestion not on your list: aparthas3112

Wondering if @paulthebaker or @bshapiroalbert have other suggestions?

**Comment by mbobra** [comment]
Thanks for your suggestions, @Hazboun6 -- I really appreciate it. I will get started on finding you some reviewers!

**Comment by bshapiroalbert** [comment]
I will echo @Hazboun6 in thanking both @danielskatz and @mbobra! I do not have any other suggestions for reviewers right now, but I agree with @Hazboun6 's suggestions.

**Comment by mbobra** [comment]
@whedon assign @JBorrow as reviewer

**Comment by whedon** [comment]
OK, @JBorrow is now a reviewer

**Comment by mbobra** [comment]
@whedon add @arjunsavel as reviewer

**Comment by whedon** [comment]
OK, @arjunsavel is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2757.
