### ISSUE TITLE
[PRE REVIEW]: ambrosia: An R package for calculating and analyzing food demand and in accordance with the Edmonds et al. food demand model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2755]
**Submitting author:** @kanishkan91 (<a href="http://orcid.org/0000-0001-8483-6216">Kanishka Narayan</a>)
**Repository:** <a href="https://github.com/JGCRI/ambrosia" target ="_blank">https://github.com/JGCRI/ambrosia</a>
**Version:** v1.3.0
**Editor:** @dhhagan
**Reviewers:** @tscheypidi, @sahilseth
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kanishkan91. **Currently, there isn't an JOSS editor assigned** to your paper.

@kanishkan91 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.13 s (236.3 files/s, 34334.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               18            463           1236           1844
Markdown                         6            121              0            256
TeX                              1              0              0            132
YAML                             3             12              0             52
C++                              1             10              4             48
make                             1             13             15             24
Rmd                              1             57            217              1
-------------------------------------------------------------------------------
SUM:                            31            676           1472           2357
-------------------------------------------------------------------------------


Statistical information for the repository '943705e042b7d6ef5f251972' was
gathered on 2020/10/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kanishka Narayan                 1            62             62            9.93
Robert Link                     16           492            156           51.88
crvernon                         2            65            412           38.19

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Robert Link                  62           12.6         20.2                6.45
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02755/joss.02755/10.21105.joss.02755.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02755/joss.02755/10.21105.joss.02755.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1142/s2010007817500129 may be a valid DOI for title: A global food demand model for the assessment of complex human-earth systems
- 10.5334/jors.266 may be a valid DOI for title: Moirai Version 3: A Data Processing System to Generate Recent Historical Land Inputs for Global Modeling Applications at Various Scales
- 10.5194/gmd-8-939-2015 may be a valid DOI for title: A simple object-oriented and open-source model for scientific and policy analyses of the global climate system – Hector v1.0
- 10.5334/jors.181 may be a valid DOI for title: Xanthos–a global hydrologic model
- 10.1201/9780203735268 may be a valid DOI for title:  Transformation and Weighting in Regression
- 10.1093/biomet/57.1.97 may be a valid DOI for title:  Monte Carlo sampling methods using Markov chains and their applications
- 10.1093/comjnl/12.1.94 may be a valid DOI for title: A new method of solving nonlinear simultaneous equations
- 10.2307/1269576 may be a valid DOI for title: Finding groups in data: an introduction to cluster analysis
- 10.4249/scholarpedia.2928 may be a valid DOI for title: Nelder-mead algorithm

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@kanishkan91 - thanks for your submission.

In my opinion, the paper is too long.  I suggest moving some of the example content into the software documentation, perhaps in a tutorial on usage.

I also suggest that most of the information just before the acknowledgements could either be a few lines of text, rather than a page of bullets, or again, moved into the repository/documentation/README.

Finally, note that whedon has found what it thinks might be some missing DOIs. If these are correct, please add them to your bib file.

Use ```@whedon generate pdf``` and ```@whedon check references``` after you make changes to check the results - each command needs to be the first (or only) thing in a new comment.

**Comment by danielskatz** [comment]
Also, you probably need to protect some letters in the bib with {} to make/keep them upper case, such as FAIR in one reference.

**Comment by danielskatz** [comment]
👋 @dhhagan - would you be willing to edit this?  I know it's a bit out of your area, but I'm also trying to balance assignments/work

**Comment by danielskatz** [comment]
@whedon invite @dhhagan as editor

**Comment by whedon** [comment]
@dhhagan has been invited to edit this submission.

**Comment by kanishkan91** [comment]
@danielskatz Thanks much for the comments! we will work on cutting down the length of the paper as you suggest.

By the way, these examples are documented on a user tutorial here on the repository - https://jgcri.github.io/ambrosia/articles/ambrosia_vignette.html

This is also referenced in the README.md . The user tutorial in addition to other documentation can also be accessed here-   
https://jgcri.github.io/ambrosia/

Do let us know what you think. Thanks again!

**Comment by danielskatz** [comment]
Thanks - any further discussion probably should wait for the editor (and the reviewers).

**Comment by sahilseth** [comment]
I can help review, if needed - thanks

**Comment by kanishkan91** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1142/s2010007817500129 is OK
- 10.5334/jors.266 is OK
- 10.5194/gmd-8-939-2015 is OK
- 10.5334/jors.181 is OK
- 10.1201/9780203735268 is OK
- 10.1093/biomet/57.1.97 is OK
- 10.1093/comjnl/12.1.94 is OK
- 10.2307/1269576 is OK
- 10.4249/scholarpedia.2928 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kanishkan91** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02755/joss.02755/10.21105.joss.02755.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02755/joss.02755/10.21105.joss.02755.pdf) :page_facing_up: :point_left:

**Comment by kanishkan91** [comment]
Hi all,

As suggested, we have cut down the paper length and shifted some text to the documentation and the user tutorial. We have also fixed and checked the DOI's and addressed other comments. Do let us know if you need anything else from our side. Thanks!

**Comment by kanishkan91** [comment]
@danielskatz We addressed the initial review comments (paper length, invalid DOIs). Do let us know if you have any updates on editors/reviewers or if you need anything else from our side. Thanks!

**Comment by kanishkan91** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02755/joss.02755/10.21105.joss.02755.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02755/joss.02755/10.21105.joss.02755.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon assign @dhhagan as editor

**Comment by whedon** [comment]
OK, the editor is @dhhagan

**Comment by arfon** [comment]
:wave: @dhhagan - further to @danielskatz's [request from ~10 days ago](https://github.com/openjournals/joss-reviews/issues/2755#issuecomment-710026146) I've gone ahead and assigned you here.

**Comment by kanishkan91** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by dhhagan** [comment]
Hey @arfon sorry about that - having a hard time sorting through GitHub notifications. Will get right on this.

**Comment by dhhagan** [comment]
👋 @sahilseth @jsta @masalmon would you be willing to review this manuscript?

**Comment by arfon** [comment]
@dhhagan (not that you could possibly know this) but @jsta has asked to be removed from the reviewer list so you'll need to look a little further afield.

**Comment by dhhagan** [comment]
👋 @maelle Would you available and interested in reviewing this manuscript?

**Comment by maelle** [comment]
Hello @dhhagan ! Sorry, no, I don't have time at the moment.

**Comment by dhhagan** [comment]
👋  Hey there @pboesu @cbrueffer @nhejazi @ethanwhite are any of you available to review this manuscript?

**Comment by pboesu** [comment]
I'm afraid I do not have capacity for this at the moment.

**Comment by cbrueffer** [comment]
Same here, too many other obligations at the moment, sorry.

**Comment by nhejazi** [comment]
I am currently committed to several other ongoing reviews and cannot take on another at the moment.

**Comment by crvernon** [comment]
@dhhagan We just had @tscheypidi conduct a review on a different submission.  They did a thorough and efficient job and may be an option for this review if you see fit.  Thanks!

**Comment by dhhagan** [comment]
👋  @tscheypidi Are you able and interested in reviewing this paper?

**Comment by tscheypidi** [comment]
@dhhagan Yes, I can do it.

**Comment by dhhagan** [comment]
@whedon add @tscheypidi as reviewer

**Comment by whedon** [comment]
OK, @tscheypidi is now a reviewer

**Comment by crvernon** [comment]
@dhhagan Here are two more reviewers that seem to be very responsive and efficient for this type of paper that you can try contacting to review if you see fit:  @mmrabe or @DominiqueMakowski

**Comment by sahilseth** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by dhhagan** [comment]
👋  @mmrabe @DominiqueMakowski are either of you able and interested to review this paper?

**Comment by DominiqueMakowski** [comment]
Hi @dhhagan thanks for considering me, unfortunately it is not a good time for me and, as much as I like the name of this package, it's a little outside my scope. Good luck!

**Comment by mmrabe** [comment]
Hi all! Thanks for considering me, @dhhagan. Unfortunately, I won't be able to return a review in the next couple of weeks (probably until early January). But it seems that @sahilseth and @tscheypidi have already agreed to review already?

**Comment by dhhagan** [comment]
@whedon add @sahilseth as reviewer

**Comment by whedon** [comment]
OK, @sahilseth is now a reviewer

**Comment by dhhagan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2890.
