### ISSUE TITLE
[REVIEW]: The Pulsar Signal Simulator: A Python package for simulating radio signal data from pulsars

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2757]
**Submitting author:** @Hazboun6 (<a href="http://orcid.org/0000-0003-2742-3321">Jeffrey Hazboun</a>)
**Repository:** <a href="https://github.com/PsrSigSim/PsrSigSim" target ="_blank">https://github.com/PsrSigSim/PsrSigSim</a>
**Version:** v1.0.1
**Editor:** @mbobra
**Reviewer:** @JBorrow, @arjunsavel
**Archive:** <a href="https://doi.org/10.5281/zenodo.4521235" target="_blank">10.5281/zenodo.4521235</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6f2caac6394c899d461075963b5d7e45/status.svg)](https://joss.theoj.org/papers/6f2caac6394c899d461075963b5d7e45)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6f2caac6394c899d461075963b5d7e45"><img src="https://joss.theoj.org/papers/6f2caac6394c899d461075963b5d7e45/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6f2caac6394c899d461075963b5d7e45/status.svg)](https://joss.theoj.org/papers/6f2caac6394c899d461075963b5d7e45)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/PsrSigSim/PsrSigSim" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@JBorrow & @arjunsavel, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PsrSigSim/PsrSigSim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Hazboun6) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PsrSigSim/PsrSigSim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@Hazboun6) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @JBorrow, @arjunsavel it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/217709a0 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1007/s00159-019-0115-7 is OK
- 10.1093/nsr/nwx126 is OK
- 10.1086/181708 is OK
- 10.1086/159690 is OK
- 10.5281/zenodo.3756164 is OK
- 10.1017/pasa.2020.19 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02757/joss.02757/10.21105.joss.02757.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02757/joss.02757/10.21105.joss.02757.pdf) :page_facing_up: :point_left:

**Comment by mbobra** [comment]
👋 @JBorrow @arjunsavel Thank you so much for agreeing to review this submission! You'll see your reviewer checklists above. Please feel free to ask questions here on this review thread.

Please note that this article is in collaboration with AAS publishing (the submitting authors submitted a companion paper to *The Astrophysical Journal*). As part of this collaboration, AAS publishing makes a small donation to the running costs of JOSS. Please take a look at the blog posts [about the AAS-JOSS collaboration](https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing) and [JOSS' financial model](https://joss.theoj.org/about#costs). Please let me know if you have any issues with this.

**Comment by JBorrow** [comment]
The authors have presented a new package for the simulation and modelling of pulsar observations. It has a clean object-oriented interface, and exceptionally detailed narrative documentation and tutorial content. I found the interface particularly intuitive, and it was great (as somebody who is a 'pure' simulator) to play around with the different telescopes. I can see clearly both the scientific as well as educational benefit of such a package. As somebody not directly within the field of radio astronomy, I cannot comment on the scientific merit of the package or its results, but I will leave this to those reviewing the ApJ paper.

I have opened the following issues within the main repository:

+ https://github.com/PsrSigSim/PsrSigSim/issues/156
+ https://github.com/PsrSigSim/PsrSigSim/issues/157
+ https://github.com/PsrSigSim/PsrSigSim/issues/158
+ https://github.com/PsrSigSim/PsrSigSim/issues/159
+ https://github.com/PsrSigSim/PsrSigSim/issues/160

with various concerns. Most of these are minor and should be a relatively quick fix (e.g. typos, adding a section to the paper looking at other software packages in the field). My one major concern, though, is the large amount of warnings produced when running the examples and tests. In particular, when running the test suite, I saw over 1000 warnings of various types (Runtime warnings from taking negative square roots and deprecation warnings). I would like to have these resolved before being confident in accepting this package, particularly as they are so numerous.

**Comment by arjunsavel** [comment]
I've  completed my review:

With PsrSigSim, the authors have provided a well-documented and well-organized package for simulating pulsar observations. I don't specialize in radio astronomy, but to the extent of my knowledge, I believe it to be of scientific merit.

Of the issues that I have opened in PsrSigSim repository, the below are relevant for acceptance. Many are related to grammar and consistency.
- https://github.com/PsrSigSim/PsrSigSim/issues/164
- https://github.com/PsrSigSim/PsrSigSim/issues/163
- https://github.com/PsrSigSim/PsrSigSim/issues/162
- https://github.com/PsrSigSim/PsrSigSim/issues/161

For https://github.com/PsrSigSim/PsrSigSim/issues/164, a full implementation of a user-input random seed would not be necessary for acceptance; however, I would recommend briefly addressing effects of randomness on the documentation plots.

I reproduced the errors (and fixes) on installation/testing that @JBorrow reported above (running Python 3.7.6).

I also wanted to touch base about the authorship list — I noticed that a few people are listed in the paper but not in AUTHORS.RST (Nathan Garver-Daniels, Maura A. McLaughlin).

Overall, the package looks great to me, and I'll be signed off pending the resolution of the above issues! Looking forward to the companion ApJ paper.

**Comment by Hazboun6** [comment]
Thank you @JBorrow and @arjunsavel for your speedy reviews! We're looking over the Issues you both posted now and we'll let you know when we've been able to attend to them. Hopefully we'll be able to make most changes this week.

**Comment by Hazboun6** [comment]
@mbobra One point that @JBorrow made in [Issue 160](https://github.com/PsrSigSim/PsrSigSim/issues/160) was about a reference to the AAS paper to which this work is linked. Is there a JOSS standard for how you'd like us to refer to that paper? I'm imagining it will probably take longer to appear/publish. Would you like it as `.bib` entry. Currently it is written as `[Shapiro-Albert,2020`, but I just realized that if I was followng the AAS style it should be `[Shapiro-Albert, In Prep]`, which is probably what led to some confusion.

**Comment by mbobra** [comment]
@Hazboun6 Good question. You don't need to cite the AAS paper. The DOI for the AAS paper will appear the JOSS paper automatically (see examples [here](https://joss.theoj.org/papers/10.21105/joss.01889) and [here](https://joss.theoj.org/papers/10.21105/joss.02125); look at the left margin).

There is some documentation about the AAS publishing process process [here](https://joss.readthedocs.io/en/latest/editing.html#handling-of-papers-published-together-with-aas-publishing). Here is the order of operations:

1. The JOSS reviewers agree that the software package PsrSigSim passes review.
2. Your paper is accepted by JOSS. However, we don't publish it yet. We pause the publication of the review pending the DOI from ApJ. Practically speaking, pausing the review means I add a label to this review thread that says "paused" and we leave this issue open.
3. Your paper is accepted into ApJ. We the publish the JOSS paper and automatically include the ApJ DOI, which automatically closes this issue.

**Comment by mbobra** [comment]
👋 @Hazboun6 How is it going with the issues?

**Comment by Hazboun6** [comment]
Hi @mbobra ! Thanks for checking in. We are making good progress. I think we're probably ~75% of the way through the issues. We also got the referee report from the AAS paper back and that also involved a few changes to the [code,](https://github.com/PsrSigSim/PsrSigSim/issues/175) so we've been working to add that functionality in as well. 

I can update the referees with which Issues have been completed within a week, and I think we'll only have a few things left at that point.

**Comment by mbobra** [comment]
👋 @Hazboun6 Checking in again -- how is it going? Do you need any help?

**Comment by Hazboun6** [comment]
@mbobra I keep holding back on answering you thinking that I will be done with all of the changes we'd like to make. We are _almost_ done on our end. I spent a good amount of time on the docs today and I have been closing the various Issues in our GitHub repo. I don't think we need any help at this point but I appreciate the offer. Is there a hard deadline for these responses?

**Comment by mbobra** [comment]
@Hazboun6 Nope, no hard deadline. I wanted to check in to make sure everything is okay. Please take all the time you need.

If you need a lot of time, that is totally fine -- but I in that case, I would pause the submission. All this does is notify the Editors in Chief that this submission will take a bit longer. Practically, all I do is put another label on this issue that says "Paused." In any case -- if we're looking at 4 weeks or less, no worries. If you think you'll need more time, I'll add the paused button (which we can unpause at any time).

**Comment by Hazboun6** [comment]
@mbobra  we have completed the changes to the code suggested by @JBorrow and @arjunsavel. 

We branched the code and just merged all of the changes in this [PR](https://github.com/PsrSigSim/PsrSigSim/pull/187). 

Thank you for your patience in how long this took us to do!

**Comment by JBorrow** [comment]
Happy to take another look at things soon if you think there are no other changes to be made @Hazboun6

**Comment by Hazboun6** [comment]
@JBorrow please standby. I just realized that the docs did not build on `readthedocs`. The were of course building locally. How embarrassing... My work day starts in an hour and I'll fix ASAP. Sorry

**Comment by Hazboun6** [comment]
@JBorrow and @arjunsavel We are now ready for you both to have another look!

**Comment by arjunsavel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02757/joss.02757/10.21105.joss.02757.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02757/joss.02757/10.21105.joss.02757.pdf) :page_facing_up: :point_left:

**Comment by arjunsavel** [comment]
Hi @Hazboun6 — I've completed my second pass, and I only have a few more minor comments:

- https://github.com/PsrSigSim/PsrSigSim/issues/189
- https://github.com/PsrSigSim/PsrSigSim/issues/190

Other than these, things look great!

**Comment by Hazboun6** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02757/joss.02757/10.21105.joss.02757.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02757/joss.02757/10.21105.joss.02757.pdf) :page_facing_up: :point_left:

**Comment by Hazboun6** [comment]
@arjunsavel Thanks for the second look at the paper and docs! I've merged changes based on your suggestions and regenerated the pdf above. Also looks like the semicolon fixed the multiple citations.

**Comment by JBorrow** [comment]
Happy that all of my comments have been addressed. Thanks again to the authors.

**Comment by mbobra** [comment]
Thank you both so very much for your thorough reviews, @arjunsavel and @JBorrow! Your volunteer time keeps JOSS running and the JOSS team appreciates it very much ☀️

**Comment by mbobra** [comment]
@Hazboun6 Could you please cut a new release of PsrSigSim and [deposit it in Zenodo](https://guides.github.com/activities/citable-code/)? Please make sure that the author list on the Zenodo deposit matches the author list on the paper. Then I can move forward with accepting the paper.

**Comment by Hazboun6** [comment]
@mbobra I just tagged a release and deposited in [Zenodo](https://zenodo.org/record/4521235). Should be all set. Thanks to everyone for helping make our code better!

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02757/joss.02757/10.21105.joss.02757.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02757/joss.02757/10.21105.joss.02757.pdf) :page_facing_up: :point_left:

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/217709a0 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1007/s00159-019-0115-7 is OK
- 10.1093/nsr/nwx126 is OK
- 10.1086/181708 is OK
- 10.1086/159690 is OK
- 10.5281/zenodo.3756164 is OK
- 10.1017/pasa.2020.19 is OK
- 10.1071/AS04022 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Hazboun6** [comment]
@mbobra do you need any info about the ApJ paper? It has been excepted and the proofs were returned yesterday, but hasn't been published yet.

**Comment by mbobra** [comment]
@Hazboun6 Yes! I was just about to message you with that. Please ask AAS to give you the DOI for the paper (I think they should have already generated that) and then put it in the paper.md YAML header [like this](https://joss.readthedocs.io/en/latest/editing.html#handling-of-papers-published-together-with-aas-publishing). Please let me know when that's done and I can wrap up here.

**Comment by mbobra** [comment]
@openjournals/joss-eics - this paper is ready to publish once we have the AAS DOI.

/ cc @crawfordsm

**Comment by Hazboun6** [comment]
@mbobra we finally heard back from ApJ! The DOI is now part of the paper.

**Comment by Hazboun6** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02757/joss.02757/10.21105.joss.02757.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02757/joss.02757/10.21105.joss.02757.pdf) :page_facing_up: :point_left:

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.4521235 as doi

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.4521235 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4521235" target="_blank">10.5281/zenodo.4521235</a> is the archive.

**Comment by mbobra** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by mbobra** [comment]
@Hazboun6 Congrats!!! All we have to do now is wait for the ApJ paper to be published. Then we can publish this one (which takes just a few minutes). Can you keep us up to date about when the ApJ paper is published?

@openjournals/joss-eics This paper, which is a AAS companion paper, is ready to publish.

**Comment by arfon** [comment]
@Hazboun6 - can you tell me the title of your AAS paper?

**Comment by Hazboun6** [comment]
@arfon Yep! It is "A Study in Frequency-dependent Effects on Precision Pulsar Timing Parameters with the Pulsar Signal Simulator"

**Comment by arfon** [comment]
:+1: thanks. And do you by any chance know the AAS submission ID? (I'm assuming you don't know the DOI yet)

**Comment by Hazboun6** [comment]
The DOI is `10.3847/1538-4357/abdc29` The alphanumeric past the last slash is the AAS submission ID as well. And I've put the DOI into the `paper.md` in the appropriate spot.

**Comment by arfon** [comment]
> @Hazboun6 Congrats!!! All we have to do now is wait for the ApJ paper to be published. Then we can publish this one (which takes just a few minutes). Can you keep us up to date about when the ApJ paper is published?

@mbobra - as I think we have the AAS DOI now, we can go ahead and accept and publish here too.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/217709a0 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1007/s00159-019-0115-7 is OK
- 10.1093/nsr/nwx126 is OK
- 10.1086/181708 is OK
- 10.1086/159690 is OK
- 10.5281/zenodo.3756164 is OK
- 10.1017/pasa.2020.19 is OK
- 10.1071/AS04022 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2086

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2086, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1360878655367503873) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2087
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02757](https://doi.org/10.21105/joss.02757)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@JBorrow, @arjunsavel - many thanks for your reviews here and to @mbobra for editing this submission ✨. JOSS relies upon the volunteer efforts of folks like yourselves and we simply wouldn't be able to do this without you!

@Hazboun6 - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02757/status.svg)](https://doi.org/10.21105/joss.02757)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02757">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02757/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02757/status.svg
   :target: https://doi.org/10.21105/joss.02757
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02757/status.svg)](https://doi.org/10.21105/joss.02757)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
