### ISSUE TITLE
[PRE REVIEW]: Virgo: A Versatile Spectrometer for Radio Astronomy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2758]
**Submitting author:** @0xCoto (<a href="http://orcid.org/0000-0001-6928-6877">Apostolos Spanakis-Misirlis</a>)
**Repository:** <a href="https://github.com/0xCoto/Virgo" target ="_blank">https://github.com/0xCoto/Virgo</a>
**Version:** 2.0.3
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @0xCoto. **Currently, there isn't an JOSS editor assigned** to your paper.

@0xCoto if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (122.4 files/s, 19128.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            114             79            526
Markdown                         2             58              0            229
TeX                              1              4              0             84
-------------------------------------------------------------------------------
SUM:                             7            176             79            839
-------------------------------------------------------------------------------


Statistical information for the repository '7be56a6adeeb03cf9703f988' was
gathered on 2020/10/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
0xCoto                          41          2446           1727          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
0xCoto                      719           29.4          0.8                9.32
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1142/9446 is OK

MISSING DOIs

- 10.1016/b978-0-12-804547-3.00007-3 may be a valid DOI for title: Multirate Digital Signal Processing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02758/joss.02758/10.21105.joss.02758.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02758/joss.02758/10.21105.joss.02758.pdf) :page_facing_up: :point_left:

**Comment by 0xCoto** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
I'm sorry @0xCoto, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by 0xCoto** [comment]
I consider the following reviewers to be a good fit for my paper: `garrettj403`, `arjunsavel`, `sibirrer`.

Also, regarding the warning:
```
MISSING DOIs

 - 10.1016/b978-0-12-804547-3.00007-3 may be a valid DOI for title: Multirate Digital Signal Processing
```
The book does not have a DOI, so I assume this 'warning' should be dismissed.

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@0xCoto - thanks for your submission to JOSS. I've flagged this for a scope review by the editorial team as it's very small and so may be out of scope for us.

**Comment by kyleniemeyer** [comment]
@0xCoto Unfortunately, the JOSS editors have decided that this submission does not meet the substantial scholarly effort criterion for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by 0xCoto** [comment]
@kyleniemeyer - Thank you very much for taking the time to evaluate the work.

Could you please further elaborate on why the submission does not meet the substantial scholarly effort criterion? If the problem is the fact that the code has <1000 LOC, would you consider a resubmission with the implementation of additional features that would lead to this standard being fulfilled?

Lastly, I would like to comment on this:

> Whether the software is sufficiently useful that it is likely to be cited by your peer group.

The software definitely has the potential of being cited in academic work, particularly in undergraduate and graduate student theses. Given I know an undergraduate's thesis (currently in the works) is heavily dependent on `Virgo`, how could I address such citation potential in order to help encourage the consideration of the software for review (according to JOSS, `Some factors that may be considered by editors and reviewers when judging effort include...`)?

**Comment by kyleniemeyer** [comment]
@0xCoto the view from the editorial board was that the package was too small, and also somewhat minor in terms of utility. If you extended the functionality by adding more features, we would reconsider a new submission at a later point.
