### ISSUE TITLE
[PRE REVIEW]: climpred: Verification of weather and climate forecasts

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2759]
**Submitting author:** @bradyrx (<a href="http://orcid.org/0000-0002-2309-8245">Riley Brady</a>)
**Repository:** <a href="https://www.github.com/pangeo-data/climpred" target ="_blank">https://www.github.com/pangeo-data/climpred</a>
**Version:** v2.1.1
**Editor:** @dhhagan
**Reviewers:** @neerajdhanraj, @darothen
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @bradyrx. **Currently, there isn't an JOSS editor assigned** to your paper.

@bradyrx if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.34 s (611.8 files/s, 104205.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          56           2196           4104           8712
reStructuredText               109            902            730           1731
Jupyter Notebook                18              0          14564           1039
TeX                              1             30              0            348
YAML                            12             17             18            329
Markdown                         6             45              0            225
JSON                             2             22              0            174
DOS Batch                        1              8              1             26
Bourne Shell                     1              4              0             10
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           207           3228          19424          12603
-------------------------------------------------------------------------------


Statistical information for the repository 'feb745cbe8940dbfcfc14144' was
gathered on 2020/10/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
AS                              20          1668           1336            3.98
Aaron Spring                   134         19313           9302           37.92
Andrew                           3           720            620            1.78
Andrew Huang                     3           153             26            0.24
Kathy Pegion                     3           207             42            0.33
Riley Brady                     50          8753           6906           20.75
Riley X. Brady                 252         13520          11501           33.16
aaronspring                      5           692            146            1.11
ahuang11                         8           228            105            0.44
bradyrx                         17           198             25            0.30

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
AS                          359           21.5         16.0                8.64
Aaron Spring               7789           40.3          6.8                9.95
Andrew                      278           38.6         16.1               17.63
Andrew Huang                  7            4.6         17.1               28.57
Kathy Pegion                 41           19.8          9.2               19.51
Riley Brady                6533           74.6          6.7                7.79
ahuang11                      5            2.2         16.8                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10/f89qdf is OK
- 10/ggtpks is OK
- 10/gd7hfq is OK
- 10/f782pf is OK
- 10/gbpwpt is OK
- 10/f4jjvf is OK
- 10/dp65gs is OK
- 10/f5w2xr is OK
- 10/gdqdmw is OK
- 10/gfxr7x is OK
- 10/gf4wzh is OK
- 10/f7r9st is OK
- 10/gf48c9 is OK
- 10/gdsnf8 is OK
- 10/gg9ss8 is OK
- 10/gc9wzk is OK
- 10/dpsjbp is OK
- 10/ggvcqv is OK
- 10/ggkt9s is OK
- 10/gfz6s5 is OK
- 10/gdb424 is OK
- 10/ggtbv2 is OK
- 10/gddfcs is OK

MISSING DOIs

- 10.1201/9780203734636-38 may be a valid DOI for title: Deterministic nonperiodic flow

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02759/joss.02759/10.21105.joss.02759.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02759/joss.02759/10.21105.joss.02759.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @jedbrown - any chance you can take on this submission as editor?

**Comment by danielskatz** [comment]
@whedon invite @jedbrown as editor

**Comment by arfon** [comment]
@whedon invite @jedbrown as editor

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by bradyrx** [comment]
A great reviewer would be Chris Kadow (ckadow), but he might be too busy to review here.

Based on the list of approved reviewers:
* Eviatar Bach (eviatarbach)
* Ryan Abernathy (rabernat)
* Kelly Kochanski (kellykochanski)
* Neeraj Bokde (neerajdhanraj)
* Damien Irving (DamienIrving)
* Sarat Sreepathi (sarats)
* Ali Ramadhan (ali-ramadhan)
* Nikolay Koldunov (koldunovn)
* Andrew Bennett (arbennett)
* Philipp Sommer (Chilipp)

**Comment by jedbrown** [comment]
@danielskatz This looks cool, but I'm conflicted (lead author is also at CU Boulder).

**Comment by danielskatz** [comment]
Sorry I missed that - I assume @openjournals/jose-eics will make a different editor invitation

**Comment by bradyrx** [comment]
> @danielskatz This looks cool, but I'm conflicted (lead author is also at CU Boulder).
> 
> PS: as is Kelly (in reviewer list above)

Hi Jed! Bummer I didn't meet you during my time here -- glad to see a fellow Buff here. Kelly is a good friend of mine, although we haven't collaborated directly. I crossed her name out above to avoid CU Boulder bias. Thanks!

**Comment by kyleniemeyer** [comment]
@danielskatz I think you meant openjournals/joss-eics... 😄 

@dhhagan could you instead edit this submission? Thanks!

**Comment by kyleniemeyer** [comment]
@whedon invite @dhhagan as editor

**Comment by whedon** [comment]
@dhhagan has been invited to edit this submission.

**Comment by dhhagan** [comment]
@kyleniemeyer Yup.

**Comment by dhhagan** [comment]
@whedon assign @dhhagan as editor

**Comment by whedon** [comment]
OK, the editor is @dhhagan

**Comment by dhhagan** [comment]
👋  @darothen @eviatarbach @sarats @neerajdhanraj: would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow [these](https://joss.readthedocs.io/en/latest/review_criteria.html) guidelines.

**Comment by neerajdhanraj** [comment]
Yeah, I would like to review this submission.

**Comment by dhhagan** [comment]
@whedon add @neerajdhanraj as reviewer

**Comment by whedon** [comment]
OK, @neerajdhanraj is now a reviewer

**Comment by neerajdhanraj** [comment]
Can someone please tell me where to provide the comments on the manuscript?

**Comment by dhhagan** [comment]
Hi @neerajdhanraj After I identify another reviewer, I will officially start the review which will take place in a new issue on GitHub. There will be checkboxes you can check off as the review progresses and you will comment either directly in that issue or on the software's original repository. An example of what that process looks like can be found [here](https://github.com/openjournals/joss-reviews/issues/1075). I hope to have the reviewer list locked down within the next few days.

**Comment by neerajdhanraj** [comment]
Great, I got your point.

**Comment by eviatarbach** [comment]
Thank you for considering me as a reviewer! While I would love to review this submission, I would unfortunately not be able to do it until December. So if that is okay with @bradyrx I would be happy to do it, but you may want a speedier review.

**Comment by bradyrx** [comment]
I think we'd prefer a speedier reviewer if possible, but if that's difficult to arrange we would be fine with December!

**Comment by darothen** [comment]
@dhhagan I would be happy to serve as a reviewer if you still need one.

**Comment by dhhagan** [comment]
@darothen Great! I'll add you as a reviewer.

**Comment by dhhagan** [comment]
@whedon add @darothen as a reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by dhhagan** [comment]
@whedon add @darothen as reviewer

**Comment by whedon** [comment]
OK, @darothen is now a reviewer

**Comment by dhhagan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2781.
