### ISSUE TITLE
[PRE REVIEW]: Moltres: finite element based simulation of molten salt reactors

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#276]
**Submitting author:** @lindsayad (<a href="http://orcid.org/0000-0002-6988-2123">Alexander Lindsay</a>)
**Repository:** <a href="https://github.com/arfc/moltres" target ="_blank">https://github.com/arfc/moltres</a>
**Version:** v0.1.0
**Editor:** @kyleniemeyer
**Reviewer:** @scopatz

**Author instructions**

Thanks for submitting your paper to JOSS @lindsayad. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lindsayad if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @kyleniemeyer - the submitting author suggested you as an editor. What do you think?

**Comment by kyleniemeyer** [comment]
@arfon sure, I can take this one.

@lindsayad to start, can you recommend a potential reviewer or two? My preference is to get one set of eyes familiar with the topic/domain, and another more general reviewer.

**Comment by lindsayad** [comment]
Ok I'm thinking initial suggestions...@friedmud and @scopatz

**Comment by kyleniemeyer** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by kyleniemeyer** [comment]
Hi @friedmud & @scopatz, would either (or both!) of you be willing to review this submission to JOSS?

From the JOSS reviewer pool, @tacaswell are you able/willing to review this?

**Comment by scopatz** [comment]
Hi @kyleniemeyer @whedon @arfon - definitely willing, but what is the timeline / deadline for the review? I am traveling a lot this summer.

**Comment by kyleniemeyer** [comment]
@scopatz: great! If you can commit to reviewing within the next few weeks, that would be great.

**Comment by scopatz** [comment]
Yep yep, I'll try to get to it next week!

**Comment by scopatz** [comment]
It would be helpful if this link were somewhere in the original post: http://joss.theoj.org/about#reviewer_guidelines

**Comment by scopatz** [comment]
Also, it would be helpful if @lindsayad could provide links to the PDF of the paper and the API documentation.  Also also, is there a standard form or format for the review? It just seems like we are "encouraged to open issues against the repository." So it is not clear what a review truly entails. A little more formalism for the reviewer would be very helpful to me.

**Comment by kyleniemeyer** [comment]
Hi @scopatz, the main review format is based on the items given at the top, with the checkboxes. You can check off items if you feel they are satisfied—otherwise bring up comments here or issues in the source repo if something is not satisfied.

**Comment by kyleniemeyer** [comment]
d'oh, I didn't start the actual review! My fault.

**Comment by kyleniemeyer** [comment]
@whedon set reviewer as @scopatz

**Comment by kyleniemeyer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by kyleniemeyer** [comment]
@whedon assign @scopatz as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @scopatz

**Comment by kyleniemeyer** [comment]
@whedon start review magicword=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/298. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
@scopatz the aforementioned review checklist will be in #298, so let's move the conversation over there.

**Comment by lindsayad** [comment]
@scopatz The link to the "paper", which is really just a summary, is [here](https://github.com/arfc/moltres/blob/devel/paper/paper.pdf). Doxygen pages are [here](https://arfc.github.io/moltres/)

**Comment by scopatz** [comment]
Thanks @lindsayad!

**Comment by friedmud** [comment]
I'm a bit late to the party (been traveling) but I would be willing to do a
review as well.  Please advise if my review is needed at this point.

**Comment by kyleniemeyer** [comment]
@friedmud absolutely! the actual review is taking place in #298, your contributions over there are welcome.
