### ISSUE TITLE
[PRE REVIEW]: simstudy: Illuminating research methods through data generation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2760]
**Submitting author:** @assignUser (<a href="http://orcid.org/0000-0002-7281-3989">Jacob Wujciak-Jens</a>)
**Repository:** <a href="https://github.com/kgoldfeld/simstudy/" target ="_blank">https://github.com/kgoldfeld/simstudy/</a>
**Version:** v0.2.1
**Editor:** @mikldk
**Reviewers:** @gagolews, @brunaw
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @assignUser. **Currently, there isn't an JOSS editor assigned** to your paper.

@assignUser if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.12 s (533.5 files/s, 99010.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               33           1123           2970           4263
Rmd                             11            570            550           1016
YAML                            10             86              3            488
Markdown                         7            121              0            357
C++                              2             36              8            101
-------------------------------------------------------------------------------
SUM:                            63           1936           3531           6225
-------------------------------------------------------------------------------


Statistical information for the repository '154f9557d81823d24e0f4982' was
gathered on 2020/10/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
James Joseph Balamut             2            10             26            4.24
Keith Goldfeld                  24           487            326           95.76

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
James Joseph Balamut          9           90.0         27.5                0.00
Keith Goldfeld              136           27.9          2.8                5.88
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2760 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02760/joss.02760/10.21105.joss.02760.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02760/joss.02760/10.21105.joss.02760.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss-submission

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-submission
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v037.i03 is OK
- 10.1016/j.jbusvent.2019.02.001 is OK
- 10.20982/tqmp.16.4.p248 is OK
- 10.1007/s40273-020-00946-y is OK
- 10.1080/00031305.1991.10475828 is OK
- 10.1111/dmcn.14552 is OK
- 10.18637/jss.v069.i04 is OK
- 10.31234/osf.io/59uaq is OK
- 10.1002/sim.8452 is OK
- 10.1097/MLR.0000000000001063 is OK
- 10.1080/03610918.2012.718841 is OK
- 10.1101/215889 is OK
- 10.1007/s10463-020-00761-4 is OK
- 10.1186/s13063-019-3364-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @mikldk - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invited @mikldk as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by assignUser** [comment]
Thank you for considering our submission and the quick start of the process!

Potential reviewers from the provided list with no active reviews, R/C++ and relevant topics, sorted bottom to top:
j-andrews7
gagolews
brunaw
tbrown122387
pedro-teles-fonseca

**Comment by mikldk** [comment]
@brunaw, @gagolews: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by gagolews** [comment]
@mikldk I'm willing to write a review.

**Comment by brunaw** [comment]
@mikldk Yes, I would be happy to

**Comment by mikldk** [comment]
@whedon add @gagolews as reviewer

**Comment by whedon** [comment]
OK, @gagolews is now a reviewer

**Comment by mikldk** [comment]
@whedon add @brunaw as reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2763.
