### ISSUE TITLE
[REVIEW]: pystiche: A Framework for Neural Style Transfer

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2761]
**Submitting author:** @pmeier (<a href="http://orcid.org/0000-0002-5184-1622">Philip Meier</a>)
**Repository:** <a href="https://github.com/pmeier/pystiche" target ="_blank">https://github.com/pmeier/pystiche</a>
**Version:** v0.6.2
**Editor:** @kthyng
**Reviewer:** @kthyng
**Archive:** <a href="https://doi.org/10.5281/zenodo.4107044" target="_blank">10.5281/zenodo.4107044</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f1c301e128bcadc0a137ed5f74c98276/status.svg)](https://joss.theoj.org/papers/f1c301e128bcadc0a137ed5f74c98276)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f1c301e128bcadc0a137ed5f74c98276"><img src="https://joss.theoj.org/papers/f1c301e128bcadc0a137ed5f74c98276/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f1c301e128bcadc0a137ed5f74c98276/status.svg)](https://joss.theoj.org/papers/f1c301e128bcadc0a137ed5f74c98276)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pmeier/pystiche" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kthyng, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pmeier/pystiche">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pmeier) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kthyng it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/CVPR.2016.265 is OK
- 10.1109/CVPR.2015.7299155 is OK
- 10.1109/CVPR.2016.272 is OK
- 10.1109/CVPR.2017.397 is OK
- 10.1145/3092919.3092920 is OK
- 10.1007/978-3-319-46475-6_43 is OK
- 10.1007/978-3-030-01234-2_49 is OK
- 10.1109/TVCG.2019.2921336 is OK

MISSING DOIs

- 10.1007/springerreference_62539 may be a valid DOI for title: Non-Photorealistic Rendering

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02761/joss.02761/10.21105.joss.02761.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02761/joss.02761/10.21105.joss.02761.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Reference completed [pyOpenSci review](https://github.com/pyOpenSci/software-review/issues/25).

**Comment by kthyng** [comment]
@pmeier Can you paste in the zenodo doi for the software archive? I can't find it.

**Comment by pmeier** [comment]
@kthyng Here you go: [10.5281/zenodo.3965784](https://doi.org/10.5281/zenodo.3965784).

**Comment by kthyng** [comment]
@pmeier Thanks! At JOSS we ask for the title and author list in the metadata for the zenodo archive to exactly match your JOSS paper, though it isn't required. Could you do this?

**Comment by pmeier** [comment]
Will try. The Zenodo archive is generated automatically through a webhook after a GitHub release. I'm not sure if I'm allowed to modify the meta data.

**Comment by pmeier** [comment]
@kthyng I've just released [`v0.6.2`](https://github.com/pmeier/pystiche/releases/tag/v0.6.2) which fixes the metadata.

**Comment by kthyng** [comment]
@whedon set v0.6.2 as version

**Comment by whedon** [comment]
OK. v0.6.2 is the version.

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.4107044 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4107044" target="_blank">10.5281/zenodo.4107044</a> is the archive.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/CVPR.2016.265 is OK
- 10.1109/CVPR.2015.7299155 is OK
- 10.1109/CVPR.2016.272 is OK
- 10.1109/CVPR.2017.397 is OK
- 10.1145/3092919.3092920 is OK
- 10.1007/978-3-319-46475-6_43 is OK
- 10.1007/978-3-030-01234-2_49 is OK
- 10.1109/TVCG.2019.2921336 is OK

MISSING DOIs

- 10.1007/springerreference_62539 may be a valid DOI for title: Non-Photorealistic Rendering

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1829

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1829, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1318293878701772805) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1830
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02761](https://doi.org/10.21105/joss.02761)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
@pmeier congrats on your publication with JOSS! I'll close this issue once the doi resolves.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02761/status.svg)](https://doi.org/10.21105/joss.02761)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02761">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02761/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02761/status.svg
   :target: https://doi.org/10.21105/joss.02761
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02761/status.svg)](https://doi.org/10.21105/joss.02761)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
