### ISSUE TITLE
[REVIEW]: simstudy: Illuminating research methods through data generation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2763]
**Submitting author:** @assignUser (<a href="http://orcid.org/0000-0002-7281-3989">Jacob Wujciak-Jens</a>)
**Repository:** <a href="https://github.com/kgoldfeld/simstudy/" target ="_blank">https://github.com/kgoldfeld/simstudy/</a>
**Version:** v0.2.2
**Editor:** @mikldk
**Reviewer:** @gagolews, @brunaw
**Archive:** <a href="https://doi.org/10.5281/zenodo.4134675" target="_blank">10.5281/zenodo.4134675</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/640fd4333948933b2817343e86df3424/status.svg)](https://joss.theoj.org/papers/640fd4333948933b2817343e86df3424)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/640fd4333948933b2817343e86df3424"><img src="https://joss.theoj.org/papers/640fd4333948933b2817343e86df3424/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/640fd4333948933b2817343e86df3424/status.svg)](https://joss.theoj.org/papers/640fd4333948933b2817343e86df3424)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kgoldfeld/simstudy/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gagolews & @brunaw, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mikldk know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kgoldfeld/simstudy/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@assignUser) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kgoldfeld/simstudy/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@assignUser) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gagolews, @brunaw it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by mikldk** [comment]
@gagolews, @brunaw: Thanks for agreeing to review. Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If possible create issues (and cross-reference) in the submission's repository to avoid too specific discussions in this review thread. 

If you have any questions or concerns please let me know.

**Comment by whedon** [comment]
PDF failed to compile for issue #2763 with the following error: 

 Can't find any papers to compile :-(

**Comment by mikldk** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@whedon check references from branch joss-submission

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-submission
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v037.i03 is OK
- 10.1016/j.jbusvent.2019.02.001 is OK
- 10.20982/tqmp.16.4.p248 is OK
- 10.1007/s40273-020-00946-y is OK
- 10.1080/00031305.1991.10475828 is OK
- 10.1111/dmcn.14552 is OK
- 10.18637/jss.v069.i04 is OK
- 10.31234/osf.io/59uaq is OK
- 10.1002/sim.8452 is OK
- 10.1097/MLR.0000000000001063 is OK
- 10.1080/03610918.2012.718841 is OK
- 10.1101/215889 is OK
- 10.1007/s10463-020-00761-4 is OK
- 10.1186/s13063-019-3364-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mikldk** [comment]
@gagolews, @brunaw: Thanks for agreeing to review. Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If possible create issues (and cross-reference) in the submission's repository to avoid too specific discussions in this review thread. 

If you have any questions or concerns please let me know.

**Comment by brunaw** [comment]
I  personally appreciate the creation of this package, since I have had to come up with my own data simulation procedures several times, for many different contexts. I think this package should be accepted because it will help lots of researchers with the same issues. Comments and suggestions about the code & content/documentation of the package are below. 

## Package content/documentation

- Add latex to the README for clarity 
- There are a few grammatical errors in the vignettes that could be improved, I suggest using Grammarly for a text review. 

- I don't think the description for the `formula` and `variance` arguments is clear yet. For instance, what does it mean to say that `formula = 10`? Likewise, what is the `variance` argument related to? I think a good way of solving this would be a concrete, written-up example with a Normal distribution, showing that the`variance` argument is the variance of the Normal distribution you're simulating from, and what does the `formula` argument represent in that. 

- It might be useful to use a simulation seed (`set.seed()`) throughout the vignettes, so people will know that their code is working as it should be when replicating it. For some vignettes, only running the code leads to quite different results from what is seen in the package website (since it's all random). 

- I think it would be nice to have your references listed in the vignettes. For example, simulating correlated (multivariate data) is not a trivial thing, since we don't have as much theory available for multivariate distributions beyond the Normal case. I had to go check the reference you cite in the JOSS paper for the binary case, since I hadn't come across that method before. Other users might be interested in knowing exactly what is going on in the code, especially if they need to explain that later (in a paper, for example).    

- You state the existence of the Contributor Code of Conduct, but actual Contributor guidelines are not provided, or how to report a problem. I think it would be good to write a few lines in the README addressing that. 



## Package code
- The package installs locally (with a cloned repository and CRAN) but it wouldn't install from GitHub, the following URL was not found: 
> https://api.github.com/repos/kgoldfeld/simstudy/tarball/master 

- The package builds okay after installing the packages used in the vignettes
- Tests are provided and also run correctly
- I haven't found any other issues with the code itself

**Comment by assignUser** [comment]
@brunaw Thank you for your review and your positive recommendation! I will try to address each point you have brought up
 
* Could you elaborate in what way you would like latex to be added to the README?
* We will review the texts.
* The meaning of each parameter for all available distributions is explained in the package help under [`?distributions`](https://kgoldfeld.github.io/simstudy/reference/distributions.html) and in the overview [vignette](https://kgoldfeld.github.io/simstudy/articles/simstudy.html). Is this in line with what you had in mind?
* I agree on the seed, which is already the case in some vignettes, we will work on consistency there. Or are there reasons not to @kgoldfeld?
* It makes sense to add the reference(s) to the documentation.
* CoC and Contributor Guidlines are in `.github/CODE_OF_CONDUCT.md` and  `.github/CONTRIBUTING.md` respectively so they should be picked up by github for new users, furthermore  they are also prominently linked in the [pkgdown site](https://kgoldfeld.github.io/simstudy/). Maybe we could add a note to the README about contributions/error reports @kgoldfeld?
* How are you installing from github? There seems to be a mention of the `master` branch which we renamed to `main`. I tested `devtools::install_github("kgoldfeld/simstudy")` and that works as intended. I just noticed & fixed that the codemeta (generated with `codemetar`) was referring to the the master branch for news as well.

**Comment by brunaw** [comment]
@assignUser Thank you for the quick reply, and I apologize if some of my comments weren't clear. 

- For example, you have log(\mu)  in the text that could be shown as <a href="https://www.codecogs.com/eqnedit.php?latex=log(\mu)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?log(\mu)" title="log(\mu)" /></a>. This can be quite tricky (https://stackoverflow.com/questions/35498525/latex-rendering-in-readme-md-on-github) to do and not necessarily pretty, but I think it could be useful for you (it's only a suggestion though)
- Okay, thank you
- Yes, exactly, I thought that even with the explanation it wasn't clear for the general user. People who do simulation frequently might get it when reading it, but it would be helpful if the argument definitions were explained in a bit more detail.  
- Okay, thank you
- Okay, thank you
-  Okay, I might have missed it on the pkgdown website, sorry about that! Maybe just link it to the README as well 
-  I wish I could come up with a more helpful explanation for you, but I couldn't wrap my head around it either. I just run `devtools::install_github("kgoldfeld/simstudy")` and get the error. I thought it was an internet connection problem but I tried it on a different network (just now) and the same error happens. The code doesn't suggest anything about it either, so I don't know what causes it.

**Comment by assignUser** [comment]
@brunaw 
Latex: Ah I see. As the symbols are rendered correctly on the pkgdown page and any workarounds for github might interfere with that I think we will keep it as is (sadly, I would like it to be rendered too, maybe github will add it at some point).

Arguments: I feel that with all of the vignettes and targeted documentation we have this covered as a specific example for `normal` would not cover all use cases, unlike the distributions. Please let me know if this is still a sticking point for you.

Install: I just found the solution for this issue. This is a recently solved problem where devtools/remotes was assuming the default branch to be "master" which was fixed by https://github.com/r-lib/remotes/pull/510 but is not on cran yet: https://remotes.r-lib.org/news/index.html 
You should be able to install by setting `devtools::install_github("kgoldfeld/simstudy", ref = "HEAD")`

**Comment by assignUser** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2763 with the following error: 

 Can't find any papers to compile :-(

**Comment by assignUser** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: :point_left:

**Comment by kgoldfeld** [comment]
@brunaw 
I was able to fix the LaTex issue without affecting the pkgdown site. Thanks for that suggestion - it looks much better - it always bothered me.

As for the grammar of the vignettes - were there any that were particularly egregious? I will certainly go through all of them - as you see there are quite a few - but it would help if you found that particular ones need special attention.

**Comment by kgoldfeld** [comment]
@brunaw 
I was able to go through the vignettes - there were some really bad typos throughout. Thanks so much for taking the time to catch all that. I have added seeds as well throughout where there were none. Thanks again.

**Comment by gagolews** [comment]
The package may be useful to some researchers and students,
in cases where generation of data following some typical models
is required. 
Overall, it is quite well written and well documented.
The package's API can be considered user friendly.
Yet, of course, more exotic scenarios will require its users to 
implement the missing functionality by hand anyway (and learn how
to implement the models included in `simstudy` anyway).
I recommended the paper be accepted provided that the authors
address what follows.


# Paper — remarks:

1. Neither in the title nor in the summary the reader is informed that it is an **R** package

2. Mention it's availability on CRAN, add link to CRAN entry, and info on how to install the package

3. The package is documented quite well (vignettes),
the link to https://kgoldfeld.github.io/simstudy/articles/simstudy.html should
therefore be emphasised in the main text,
as in *"for more details on the package, use cases, etc. (...), see (...)"*.
Also, add this information to the README file.

4. `$log(\mu)$` → `$\log(\mu)$`


# Vignettes — remarks:

1. https://kgoldfeld.github.io/simstudy/articles/simstudy.html

    a. `$log(\mu)$` → `$\log(\mu)$`

    b. "please refer to other package vignettes" – you mean other vignettes
    included in this very package?

    c. "One option is to to use"

    d. "has the following fields: varname, formula, variance, dist, and link" —
    consider using `varname`, `formula` (code)

    e. e.g., in `defData(def, varname = "female", dist = "binary",
    formula = "-2 + age * 0.1", link = "logit")` — I guess a more R-way
    (which is a matter of taste) would be to specify
    `formula = -2+age*0.1`, i.e., as an R expression, see `?deparse`
    and `?substitute`. The same with `varname` and `dist`.
    See base R functions `transform()` and `subset()` for inspiration.

    f. `$uniform$` → `uniform`

    g. `$uniforminteger$` → `uniforminteger`


2. https://kgoldfeld.github.io/simstudy/articles/correlated.html

    a. side note: copulas (copulae) are nice tools for modelling
    of dependencies between random variables

**Comment by gagolews** [comment]
@brunaw re: simulating correlated data - see https://en.wikipedia.org/wiki/Copula_(probability_theory) and https://cran.r-project.org/web/packages/copula/index.html

**Comment by kgoldfeld** [comment]
@gagolews Thanks for your feedback - will make the editing changes. I agree with you regarding 1e - we may make that change in a future iteration, though there are some "formulas" where there is no standard R formulation. The following (clearly nonsensical) snippet shows three distributions where the standard formulas don't really apply:

```r
library(simstudy)

d <- defData(varname = "x", formula = "0;1", dist = "uniform")
d <- defData(d, varname ="y", formula = "-2+x;-1 + 0.5*x", 
             dist = "categorical", link = "logit")
d <- defData(d, varname = "z", formula = "x|0.5 + y|0.5", dist = "mixture")

set.seed(5)
genData(10, d)
#>     id         x y         z
#>  1:  1 0.2002145 3 0.2002145
#>  2:  2 0.6852186 3 3.0000000
#>  3:  3 0.9168758 3 0.9168758
#>  4:  4 0.2843995 2 0.2843995
#>  5:  5 0.1046501 2 0.1046501
#>  6:  6 0.7010575 1 0.7010575
#>  7:  7 0.5279600 3 0.5279600
#>  8:  8 0.8079352 3 0.8079352
#>  9:  9 0.9565001 3 3.0000000
#> 10: 10 0.1104530 1 1.0000000
```

With respect to 2a, I agree that copulas are useful in generating correlated data. Indeed, that is what we are doing in `simstudy` to generated correlated data (for all distributions other than the normal distribution).

**Comment by gagolews** [comment]
Yeah, but this way you end up inventing a totally new syntax, like a "language within a language", making the API more difficult to learn (and these skills are "not transferable" to other package, as I understand the package aims at less advanced users?)

Actually `x|0.5 + y|0.5` is a valid R expression although it means `x|(0.5+y)|0.5` and some users might read it exactly like this?
How about simply `0.5*x + 0.5*y` for mixtures? By the way in `lm.formula()` we also use the `I(...)` function to transform the variables

`"0;1"` → `c(0,1)` ?
`"-2+x;-1 + 0.5*x"` → `c(...)?

I reckon these are/were all pretty difficult API design questions. If I were you, I'd opt for maximum compatibility with other R functions, especially those from base R, `stats`, etc. But that's my 99 cents, it's a matter of taste.

**Comment by kgoldfeld** [comment]
I agree - and it was definitely something I struggled with.  There are some things I wish I had done differently, like naming `formula` and `variance` rather than something like `param1` and `param2`. We may move to that at some point, and could think about the specification as well.

As for who is using it, I think it is a mix of experienced and less experienced folks. I think the experienced folks appreciate the ease with which you can generate complex study designs without a ton of coding.

I am hesitant to make major changes without some serious thought, because there have been 30K+ downloads, which probably means a few hundred or so serious users. I don't want to mess them up. But I hear what you are saying.

**Comment by kgoldfeld** [comment]
I made all the editing changes to the  vignette - my collaborator will fix the paper issues tomorrow at some point.

**Comment by assignUser** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: :point_left:

**Comment by assignUser** [comment]
@gagolews Thank you for your review, positive recommendation  and valuable insights. I have opened an issue regarding 1.e kgoldfeld/simstudy/issues/75 to keep track of it when we are considering breaking changes. 

I have made the changes to the paper and readme.

**Comment by brunaw** [comment]
@assignUser and @kgoldfeld  Thank you for your answers. The package correctly installs from GitHub now, and as for the grammar, I didn't mean anything specific but a few typos here and there that could be fixed (which you already did). In these cases, I always use Grammarly because I'm sure I'll miss something.  My other issue was mostly regarding this line of code

```
def <- defData(varname = "age", dist = "normal", formula = 10, 
               variance = 2)
genData(5, def)
```

where you're simulating from a N(10, 2) distribution. When I read the documentation I think I missed the part where you say that the formula argument represents the mean of the distribution, so this was actually my mistake, sorry about that! No need to correct anything there. 

@gagolews Copulas are the most popular way of simulating from correlated data, but they're also limited because they depend on assumptions about the underlying multivariate distribution and about the marginal distributions. For Binomial cases,  for instance, this is not very well defined in the literature as for a Normal distribution (e.g. https://brunaw.com/slides/conferences/EMR2019_poster.pdf).  As a result, you have a set of possible methods to simulate from non-Gaussian correlated data, but most times they present issues such as not allowing full flexibility of the covariance matrix. That's why this is not a trivial thing to do deal with, and why I suggested some references are given in the vignettes.

**Comment by assignUser** [comment]
@brunaw Thanks again :) If you are satisfied with the new "Contributing & Support"  section of the readme pointing to CONTRIBUTING.md could you check your last box? :)

**Comment by brunaw** [comment]
@assignUser Done!

**Comment by assignUser** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by assignUser** [comment]
@mikldk Everything should be in order or do we need to do something else to proceed?

**Comment by kgoldfeld** [comment]
@assignUser @brunaw I just updated the correlation vignette to include the two links that Bruna recommended.

Thanks again for all the comments and suggestions.

**Comment by mikldk** [comment]
@gagolews, @brunaw:  Can you confirm that you have finished the review and recommend that this paper is now published?

@assignUser:

* Please have a final read though of the paper, checking language etc.
* Have a final check of the proofs with `@whedon generate pdf`
* Please make a tagged release and archive (e.g. with [Zenodo](https://zenodo.org/)) as described [here](<https://joss.readthedocs.io/en/latest/submitting.html#the-review-process>), and report the version number and archive DOI in this thread. Please verify that the archive deposit has the correct metadata (title and author list), or edit these if that is not the case.

**Comment by brunaw** [comment]
@mikldk Yes

**Comment by assignUser** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: :point_left:

**Comment by assignUser** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: :point_left:

**Comment by assignUser** [comment]
@mikldk @kgoldfeld The tagged release is https://github.com/kgoldfeld/simstudy/releases/tag/v0.2.2 archived on Zenodo with the DOI: https://doi.org/10.5281/zenodo.4134675 
meta data should be correct.

**Comment by assignUser** [comment]
@whedon generate pdf

**Comment by assignUser** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v037.i03 is OK
- 10.1016/j.jbusvent.2019.02.001 is OK
- 10.20982/tqmp.16.4.p248 is OK
- 10.1007/s40273-020-00946-y is OK
- 10.1080/00031305.1991.10475828 is OK
- 10.1111/dmcn.14552 is OK
- 10.18637/jss.v069.i04 is OK
- 10.31234/osf.io/59uaq is OK
- 10.1002/sim.8452 is OK
- 10.1097/MLR.0000000000001063 is OK
- 10.1080/03610918.2012.718841 is OK
- 10.1101/215889 is OK
- 10.1007/s10463-020-00761-4 is OK
- 10.1186/s13063-019-3364-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by gagolews** [comment]
@mikldk I now recommend the paper be accepted for publication.

**Comment by mikldk** [comment]
@whedon set 10.5281/zenodo.4134675 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4134675" target="_blank">10.5281/zenodo.4134675</a> is the archive.

**Comment by mikldk** [comment]
@whedon set v0.2.2 as version

**Comment by whedon** [comment]
OK. v0.2.2 is the version.

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02763/joss.02763/10.21105.joss.02763.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@gagolews, @brunaw Thank you very much for your effort in reviewing this paper!

**Comment by mikldk** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1870

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1870, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v037.i03 is OK
- 10.1016/j.jbusvent.2019.02.001 is OK
- 10.20982/tqmp.16.4.p248 is OK
- 10.1007/s40273-020-00946-y is OK
- 10.1080/00031305.1991.10475828 is OK
- 10.1111/dmcn.14552 is OK
- 10.18637/jss.v069.i04 is OK
- 10.31234/osf.io/59uaq is OK
- 10.1002/sim.8452 is OK
- 10.1097/MLR.0000000000001063 is OK
- 10.1080/03610918.2012.718841 is OK
- 10.1101/215889 is OK
- 10.1007/s10463-020-00761-4 is OK
- 10.1186/s13063-019-3364-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1321197821224124416) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1874
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02763](https://doi.org/10.21105/joss.02763)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@gagolews, @brunaw - many thanks for your reviews here and to @mikldk for editing this submission ✨ 

@assignUser - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02763/status.svg)](https://doi.org/10.21105/joss.02763)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02763">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02763/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02763/status.svg
   :target: https://doi.org/10.21105/joss.02763
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02763/status.svg)](https://doi.org/10.21105/joss.02763)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
