### ISSUE TITLE
[PRE REVIEW]: AmgXWrapper: An interface between PETSc and the NVIDIA AmgX library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#277]
**Submitting author:** @piyueh (<a href="http://orcid.org/0000-0001-6330-2709">Pi-Yueh Chuang</a>)
**Repository:** <a href="https://github.com/barbagroup/AmgXWrapper" target ="_blank">https://github.com/barbagroup/AmgXWrapper</a>
**Version:** v1.0
**Editor:** @danielskatz
**Reviewer:** @jedbrown

**Author instructions**

Thanks for submitting your paper to JOSS @piyueh. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@piyueh if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @danielskatz it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @danielskatz - the submitting author suggested you as an editor. What do you think?

**Comment by danielskatz** [comment]
ok

**Comment by danielskatz** [comment]
@wrathematics - would you be willing to review this submission?

**Comment by labarba** [comment]
As explained in the README, this code enables PETSc-based application software to use the NVIDIA AmgX library, bestowing multi-GPU powers. Needless to say, testing the code will require both PETSc and AmgX, both big libraries. 

Right now, you need to be a registered CUDA developer to download AmgX for free—but NVIDIA folks told me they have decided to open-source it. Great news! The bad news is that it's not been released yet. For now, you need a trial license.

**Comment by labarba** [comment]
On the list of registered reviewers, I found only one who lists GPU computing among their interests: @arghdos.

**Comment by danielskatz** [comment]
@labarba - Do you have other reviewers you might suggest outside the list of JOSS volunteers?

**Comment by labarba** [comment]
I wonder if @jedbrown might give reviewing for JOSS a go.

**Comment by jedbrown** [comment]
What's the timeline?

**Comment by danielskatz** [comment]
how about 2 weeks?

**Comment by labarba** [comment]
@jedbrown : (In case it hasn't show up in your feeds yet…) JOSS reviews involve downloading and installing the software, and inspecting the repository for key elements. 
http://joss.theoj.org/about#reviewer_guidelines

Editors and reviewers post comments on the GitHub issue tracker, and authors are expected to respond to the comments and improve their submission until acceptance (or withdraw, if they feel unable to satisfy the review).

**Comment by jedbrown** [comment]
Thanks. I can review but can't promise I'll be able to put time into it until after the PETSc meeting (June 14-16), which I'm organizing.

**Comment by danielskatz** [comment]
That's fine in term of timing - I'll start the review and notify you about it.

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by danielskatz** [comment]
@whedon assign @jedbrown as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jedbrown

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/280. Feel free to close this issue now!
