### ISSUE TITLE
[PRE REVIEW]: ZiopcPy: A Python Package for the Zero-Inflated Ordered Probit Models Without and With Correlated Errors

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2770]
**Submitting author:** @Nicolas-Schmidt (<a href="http://orcid.org/0000-0001-5083-5792">Nicolás Schmidt</a>)
**Repository:** <a href="https://github.com/hknd23/ziopcpy" target ="_blank">https://github.com/hknd23/ziopcpy</a>
**Version:** 0.1.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Nicolas-Schmidt. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @lorenanicole.

@Nicolas-Schmidt if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.25 s (215.5 files/s, 79980.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      10           2222           2267           8430
HTML                            12            218              0           2781
CSS                              4            220             53            849
Python                           5             99            281            678
Markdown                         3            161              2            434
reStructuredText                 8            234            339            162
TeX                              1             13              0             76
XML                              6              0              0             47
DOS Batch                        1              8              1             26
YAML                             2              9             17             23
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            53           3188           2967          13515
-------------------------------------------------------------------------------


Statistical information for the repository '1a4bad7c67dd838247b977ef' was
gathered on 2020/10/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nguyen Huynh                     9             7              9            0.09
Sergio Bejar                     1             1              1            0.01
hknd23                          66         15955           1975           99.90

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Nguyen Huynh              13976       199657.1          1.2               16.90
Sergio Bejar                  1          100.0          0.9                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1162/ajhe_a_00026 may be a valid DOI for title: Inflated responses in measures of self-assessed health
- 10.1016/j.jeconom.2007.01.002 may be a valid DOI for title: A zero-inflated ordered probit model, with an application to modelling tobacco consumption
- 10.3386/w8419 may be a valid DOI for title: What do self-reported, objective, measures of health measure?
- 10.2307/2998213 may be a valid DOI for title: Between dispute and war: The effect of joint democracy on interstate conflict escalation
- 10.2139/ssrn.3187203 may be a valid DOI for title: Estimation of Nested and Zero-Inflated Ordered Probit Models

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02770/joss.02770/10.21105.joss.02770.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02770/joss.02770/10.21105.joss.02770.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hi @Nicolas-Schmidt, thanks for your interest in JOSS. Your package is on the small side, so the editorial board is going to take a look and decide whether it is in scope for us.

**Comment by Nicolas-Schmidt** [comment]
Dear @kyleniemeyer,  thank you very much for your message.  Please let us know if there is any additional information on the scope and/or context of our package/paper that we can provide to help the board make a decision.

In case you decide to send the paper for review, we would like to suggest @lorenanicole as editor and andrewheiss, cmaimone, soodoku, and rdrr1990 as potential reviewers.

**Comment by arfon** [comment]
@whedon reject 

@Nicolas-Schmidt - many thanks for your submission to JOSS. After consulting with the editorial team, we have concluded that this submission is out of scope for JOSS due to [its limited size and scope](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by whedon** [comment]
Paper rejected.
