### ISSUE TITLE
[PRE REVIEW]: gospl: Global Scalable Paleo Landscape Evolution

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2771]
**Submitting author:** @tristan-salles (<a href="http://orcid.org/0000-0001-6095-7689">Tristan Salles</a>)
**Repository:** <a href="https://github.com/Geodels/gospl/" target ="_blank">https://github.com/Geodels/gospl/</a>
**Version:** v0.2.0
**Editor:** @kbarnhart
**Reviewers:** @johnjarmitage, @cmshobe
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tristan-salles. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kbarnhart.

@tristan-salles if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.85 s (58.4 files/s, 12377.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          35           1854           1369           6178
reStructuredText                26           1021           1190            878
Fortran 90                       1            151            110            756
Jupyter Notebook                 7              0           6433            740
YAML                            14             96             36            600
SVG                              8              4              5            400
CSS                              2             50             11            245
TeX                              1             25              0            204
Markdown                         5             89              0            183
Dockerfile                       2             30             18             82
Bourne Shell                     5             17             15             52
TOML                             1              0              0             15
make                             1              4              5             10
-------------------------------------------------------------------------------
SUM:                           108           3341           9192          10343
-------------------------------------------------------------------------------


Statistical information for the repository '9ff880d8fe383e68b1b8d524' was
gathered on 2020/10/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Tristan                         14          3506            222           13.66
Tristan Salles                 195         15047           8510           86.34

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Tristan Salles             9821           65.3          2.7                8.38
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02771/joss.02771/10.21105.joss.02771.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02771/joss.02771/10.21105.joss.02771.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.sedgeo.2018.06.007 is OK
- 10.2110/jsr.2016.56 is OK
- 10.1002/2013WR014326 is OK
- 10.1016/j.cageo.2013.04.024 is OK
- 10.1016/j.epsl.2019.115728 is OK
- 10.5194/gmd-12-4165-2019 is OK
- 10.1016/j.earscirev.2015.10.013 is OK
- 10.1016/j.geomorph.2015.04.007 is OK
- 10.1371/journal.pone.0195557 is OK
- 10.1016/j.margeo.2011.02.014 is OK

MISSING DOIs

- 10.1046/j.1365-2117.1997.00030.x may be a valid DOI for title: Modelling landscape evolution on geological time scales: a new method based on irregular spatial discretization
- 10.1007/978-1-4615-0575-4_12 may be a valid DOI for title: The Channel-Hillslope Integrated Landscape Development Model (CHILD)
- 10.5194/esurf-5-21-2017 may be a valid DOI for title: Creative computing with Landlab: an open-source toolkit for building, coupling, and exploring two-dimensional numerical models of Earth-surface dynamics
- 10.1016/j.geomorph.2012.10.008 may be a valid DOI for title: A very efficient O(n), implicit and parallel method to solve the stream power equation governing fluvial incision and landscape evolution
- 10.2110/pec.99.62.0197 may be a valid DOI for title: Concepts and applications of a 3D multiple lithology, diffusive model in stratigraphic modeling.
- 10.21105/joss.00964 may be a valid DOI for title: eSCAPE: parallel global-scale landscape evolution model
- 10.1029/2010jf001935 may be a valid DOI for title: Field calibration of sediment flux dependent river incision
- 10.1063/1.4823180 may be a valid DOI for title: Software for Portable Scientific Data Management

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon invite @jedbrown as editor

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hey @jedbrown, can you take this submission on?

**Comment by arfon** [comment]
@whedon invite @kbarnhart as editor

:wave: @kbarnhart - would you be able to take this submission?

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by tristan-salles** [comment]
Thanks @kbarnhart !

**Comment by kbarnhart** [comment]
@tristan-salles let me know if you have any thoughts on suitable reviewers for gospl. Please mention them with a space between the @ and their handle (so you would refer to me as "@ kbarnhart"). 

I have some thoughts on suitable reviewers but am interested in your input.

**Comment by tristan-salles** [comment]
Hi @kbarnhart, here are some suitable reviewers: 
+ @ sgrieve, 
+ @ BCampforts,
+ @ SiccarPoint, 
+ @ benbovy, or
+ @ johnjarmitage

**Comment by kbarnhart** [comment]
:wave: @cmshobe, @SiccarPoint, @johnjarmitage, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. 

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by SiccarPoint** [comment]
I'm afraid I can't right now. I'm utterly overwhelmed with teaching stuff...

**Comment by johnjarmitage** [comment]
OK @kbarnhart, I'll take a look at the code and summary paper.

**Comment by cmshobe** [comment]
Sure thing @kbarnhart, I can do it.

**Comment by kbarnhart** [comment]
@whedon add @johnjarmitage as reviewer

**Comment by whedon** [comment]
OK, @johnjarmitage is now a reviewer

**Comment by kbarnhart** [comment]
@whedon add @cmshobe as reviewer

**Comment by whedon** [comment]
OK, @cmshobe is now a reviewer

**Comment by kbarnhart** [comment]
@johnjarmitage and @cmshobe thanks for agreeing to review. @SiccarPoint - no worries, good luck with the teaching responsibilities. 

I'm now going to start the review on a new issue.

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2804.
