### ISSUE TITLE
[PRE REVIEW]: AtomNeb: Python Package for Atomic Data of Ionized Nebulae

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2772]
**Submitting author:** @danehkar (<a href="http://orcid.org/0000-0003-4552-5997">Ashkbiz Danehkar</a>)
**Repository:** <a href="https://github.com/atomneb/AtomNeb-py" target ="_blank">https://github.com/atomneb/AtomNeb-py</a>
**Version:** v0.2.3
**Editor:** @arfon
**Reviewers:** @arfon
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @danehkar. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@danehkar if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (431.9 files/s, 58383.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            718           1670           2024
TeX                              1             51              0            685
reStructuredText                 8            234             53            405
Markdown                        12             82              0            131
YAML                             4             19              0             87
DOS Batch                        2              8              1             28
make                             1              4              7              9
Bourne Shell                     1              0              0              2
-------------------------------------------------------------------------------
SUM:                            46           1116           1731           3371
-------------------------------------------------------------------------------


Statistical information for the repository '1d8998fa7731814da9c88c95' was
gathered on 2020/10/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ashkbiz Danehkar                15          6461           2049          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ashkbiz Danehkar           4412           68.3          0.9               15.41
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1086/498148 is OK
- 10.1051/0004-6361/200911712 is OK
- 10.3847/1538-4365/ab05cf is OK
- 10.1088/0004-637X/744/2/99 is OK
- 10.1051/0004-6361/201323152 is OK
- 10.1051/aas:2000139 is OK
- 10.1086/191479 is OK
- 10.1093/mnras/272.2.369 is OK
- 10.1051/aas:1998319 is OK
- 10.1093/mnras/272.1.41 is OK
- 10.1111/j.1745-3933.2012.01300.x is OK
- 10.1093/mnrasl/slt049 is OK
- 10.1051/0004-6361/201116511 is OK
- 10.1051/0004-6361/201116511e is OK
- 10.1093/mnras/stx1189 is OK
- 10.1093/mnras/stt1116 is OK
- 10.1093/mnras/stu203 is OK
- 10.5281/zenodo.47794 is OK
- 10.3847/0004-6256/151/2/38 is OK
- 10.1017/pasa.2018.1 is OK
- 10.21105/joss.00899 is OK
- 10.21105/joss.00898 is OK
- 10.1086/316190 is OK
- 10.1086/319184 is OK
- 10.1046/j.1365-8711.2003.06371.x is OK
- 10.1111/j.1365-2966.2005.09381.x is OK
- 10.1086/524378 is OK
- 10.1051/0004-6361:20010923 is OK
- 10.1051/0004-6361/201015362 is OK
- 10.1111/j.1365-2966.2012.20863.x is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.0.25080/majora-92bf1922-00a is INVALID
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02772/joss.02772/10.21105.joss.02772.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02772/joss.02772/10.21105.joss.02772.pdf) :page_facing_up: :point_left:

**Comment by danehkar** [comment]
Invalid DOI was fixed.

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by danehkar** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02772/joss.02772/10.21105.joss.02772.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02772/joss.02772/10.21105.joss.02772.pdf) :page_facing_up: :point_left:

**Comment by danehkar** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1086/498148 is OK
- 10.1051/0004-6361/200911712 is OK
- 10.3847/1538-4365/ab05cf is OK
- 10.1088/0004-637X/744/2/99 is OK
- 10.1051/0004-6361/201323152 is OK
- 10.1051/aas:2000139 is OK
- 10.1086/191479 is OK
- 10.1093/mnras/272.2.369 is OK
- 10.1051/aas:1998319 is OK
- 10.1093/mnras/272.1.41 is OK
- 10.1111/j.1745-3933.2012.01300.x is OK
- 10.1093/mnrasl/slt049 is OK
- 10.1051/0004-6361/201116511 is OK
- 10.1051/0004-6361/201116511e is OK
- 10.1093/mnras/stx1189 is OK
- 10.1093/mnras/stt1116 is OK
- 10.1093/mnras/stu203 is OK
- 10.5281/zenodo.47794 is OK
- 10.3847/0004-6256/151/2/38 is OK
- 10.1017/pasa.2018.1 is OK
- 10.21105/joss.00899 is OK
- 10.21105/joss.00898 is OK
- 10.1086/316190 is OK
- 10.1086/319184 is OK
- 10.1046/j.1365-8711.2003.06371.x is OK
- 10.1111/j.1365-2966.2005.09381.x is OK
- 10.1086/524378 is OK
- 10.1051/0004-6361:20010923 is OK
- 10.1051/0004-6361/201015362 is OK
- 10.1111/j.1365-2966.2012.20863.x is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.25080/Majora-92bf1922-00a is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danehkar** [comment]
I think @arfon may be busy. Hi @xuanxu @dfm Are you willing to serve as an editor for this program also?

**Comment by arfon** [comment]
@danehkar - please sit tight for a little, I'll have a response for you today.

**Comment by arfon** [comment]
Hi @danehkar, many thanks for your submission to JOSS.

After discussing with the JOSS editorial team, we've determined that https://github.com/atomneb/AtomNeb-py is out of scope for JOSS as it is a direct port of your earlier package (https://github.com/atomneb/AtomNeb-idl) and therefore does not reach our threshold for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

While we can't support a pulication in JOSS related to this work, we would allow an update (addendum) to [your paper](https://joss.theoj.org/papers/10.21105/joss.00898) on `AtomNeb-idl` noting that there is now a Python port of this package.

Please let me know if this is of interest to you and if so, I'll be happy to work with you on an update to your earlier article.

**Comment by danehkar** [comment]
I am fine with Addendum.

Please include that its dependent Python packages are different than its IDL version:

`AtomNeb` uses the FITS handling routines of the Python package `Astropy` [@Astropy:2013; @Astropy:2018] to retrieve the atomic data from its FITS files. It also requires the Python packages `NumPy` [@Walt:2011; @Harris:2020] and `pandas` [@McKinney:2010; @McKinney:2011; @McKinney:2017]. Its latest version can be installed directly from its repository on the GitHub sing ``python setup.py install``, and the stable version from the Python Package Index (PyPi) via ``pip install atomneb`` or alternatively from the Conda Python package manager via ``conda install -c conda-forge atomneb``. The online documentation, tutorials and examples are provided on the GitHub platform (https://github.com/atomneb/AtomNeb-py) and the Read the Docs documentation host (https://atomneb-py.readthedocs.io/).

@ARTICLE{Astropy:2013,
       author = {{Astropy Collaboration} and {Robitaille}, T. P. and
         {Tollerud}, E. J. and {Greenfield}, P. and {Droettboom}, M. and
         {Bray}, Erik and {Aldcroft}, Tom and {Davis}, Matt and
         {Ginsburg}, Adam and {Price-Whelan}, Adrian M. and
         {Kerzendorf}, Wolfgang E. and {Conley}, Alexander and {Crighton}, Neil and
         {Barbary}, Kyle and {Muna}, Demitri and {Ferguson}, Henry and
         {Grollier}, Fr{\'e}d{\'e}ric and {Parikh}, Madhura M. and
         {Nair}, Prasanth H. and {Unther}, Hans M. and {Deil}, Christoph and
         {Woillez}, Julien and {Conseil}, Simon and {Kramer}, Roban and
         {Turner}, James E.~H. and {Singer}, Leo and {Fox}, Ryan and
         {Weaver}, Benjamin A. and {Zabalza}, Victor and {Edwards}, Zachary I. and
         {Azalee Bostroem}, K. and {Burke}, D.~J. and {Casey}, Andrew R. and
         {Crawford}, Steven M. and {Dencheva}, Nadia and {Ely}, Justin and
         {Jenness}, Tim and {Labrie}, Kathleen and {Lim}, Pey Lian and
         {Pierfederici}, Francesco and {Pontzen}, Andrew and {Ptak}, Andy and
         {Refsdal}, Brian and {Servillat}, Mathieu and {Streicher}, Ole},
        title = "{Astropy: A community Python package for astronomy}",
      journal = {Astronomy and Astrophysics},
         year = 2013,
       volume = {558},
          eid = {A33},
        pages = {A33},
          doi = {10.1051/0004-6361/201322068},
archivePrefix = {arXiv},
       eprint = {1307.6212},
 primaryClass = {astro-ph.IM},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2013A&A...558A..33A},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@ARTICLE{Astropy:2018,
       author = {{Astropy Collaboration} and {Price-Whelan}, A.~M. and
         {Sip{\H{o}}cz}, B.~M. and {G{\"u}nther}, H.~M. and {Lim}, P.~L. and
         {Crawford}, S.~M. and {Conseil}, S. and {Shupe}, D.~L. and
         {Craig}, M.~W. and {Dencheva}, N. and {Ginsburg}, A. and {Vand
        erPlas}, J.~T. and {Bradley}, L.~D. and {P{\'e}rez-Su{\'a}rez}, D. and
         {de Val-Borro}, M. and {Aldcroft}, T.~L. and {Cruz}, K.~L. and
         {Robitaille}, T.~P. and {Tollerud}, E.~J. and {Ardelean}, C. and
         {Babej}, T. and {Bach}, Y.~P. and {Bachetti}, M. and {Bakanov}, A.~V. and
         {Bamford}, S.~P. and {Barentsen}, G. and {Barmby}, P. and
         {Baumbach}, A. and {Berry}, K.~L. and {Biscani}, F. and {Boquien}, M. and
         {Bostroem}, K.~A. and {Bouma}, L.~G. and {Brammer}, G.~B. and
         {Bray}, E.~M. and {Breytenbach}, H. and {Buddelmeijer}, H. and
         {Burke}, D.~J. and {Calderone}, G. and {Cano Rodr{\'\i}guez}, J.~L. and
         {Cara}, M. and {Cardoso}, J.~V.~M. and {Cheedella}, S. and {Copin}, Y. and
         {Corrales}, L. and {Crichton}, D. and {D'Avella}, D. and {Deil}, C. and
         {Depagne}, {\'E}. and {Dietrich}, J.~P. and {Donath}, A. and
         {Droettboom}, M. and {Earl}, N. and {Erben}, T. and {Fabbro}, S. and
         {Ferreira}, L.~A. and {Finethy}, T. and {Fox}, R.~T. and
         {Garrison}, L.~H. and {Gibbons}, S.~L.~J. and {Goldstein}, D.~A. and
         {Gommers}, R. and {Greco}, J.~P. and {Greenfield}, P. and
         {Groener}, A.~M. and {Grollier}, F. and {Hagen}, A. and {Hirst}, P. and
         {Homeier}, D. and {Horton}, A.~J. and {Hosseinzadeh}, G. and {Hu}, L. and
         {Hunkeler}, J.~S. and {Ivezi{\'c}}, {\v{Z}}. and {Jain}, A. and
         {Jenness}, T. and {Kanarek}, G. and {Kendrew}, S. and {Kern}, N.~S. and
         {Kerzendorf}, W.~E. and {Khvalko}, A. and {King}, J. and {Kirkby}, D. and
         {Kulkarni}, A.~M. and {Kumar}, A. and {Lee}, A. and {Lenz}, D. and
         {Littlefair}, S.~P. and {Ma}, Z. and {Macleod}, D.~M. and
         {Mastropietro}, M. and {McCully}, C. and {Montagnac}, S. and
         {Morris}, B.~M. and {Mueller}, M. and {Mumford}, S.~J. and {Muna}, D. and
         {Murphy}, N.~A. and {Nelson}, S. and {Nguyen}, G.~H. and
         {Ninan}, J.~P. and {N{\"o}the}, M. and {Ogaz}, S. and {Oh}, S. and
         {Parejko}, J.~K. and {Parley}, N. and {Pascual}, S. and {Patil}, R. and
         {Patil}, A.~A. and {Plunkett}, A.~L. and {Prochaska}, J.~X. and
         {Rastogi}, T. and {Reddy Janga}, V. and {Sabater}, J. and
         {Sakurikar}, P. and {Seifert}, M. and {Sherbert}, L.~E. and
         {Sherwood-Taylor}, H. and {Shih}, A.~Y. and {Sick}, J. and
         {Silbiger}, M.~T. and {Singanamalla}, S. and {Singer}, L.~P. and
         {Sladen}, P.~H. and {Sooley}, K.~A. and {Sornarajah}, S. and
         {Streicher}, O. and {Teuben}, P. and {Thomas}, S.~W. and
         {Tremblay}, G.~R. and {Turner}, J.~E.~H. and {Terr{\'o}n}, V. and
         {van Kerkwijk}, M.~H. and {de la Vega}, A. and {Watkins}, L.~L. and
         {Weaver}, B.~A. and {Whitmore}, J.~B. and {Woillez}, J. and
         {Zabalza}, V. and {Astropy Contributors}},
        title = "{The Astropy Project: Building an Open-science Project and Status of the v2.0 Core Package}",
      journal = {The Astronomical Journal},
         year = 2018,
        month = sep,
       volume = {156},
       number = {3},
          eid = {123},
        pages = {123},
          doi = {10.3847/1538-3881/aabc4f},
archivePrefix = {arXiv},
       eprint = {1801.02634},
 primaryClass = {astro-ph.IM},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2018AJ....156..123A},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@ARTICLE{Walt:2011,
       author = {{van der Walt}, S. and {Colbert}, S. C. and
         {Varoquaux}, G.},
        title = "{The NumPy Array: A Structure for Efficient Numerical Computation}",
      journal = {Computing in Science and Engineering},
     keywords = {Computer Science - Mathematical Software},
         year = 2011,
       volume = {13},
       number = {2},
        pages = {22-30},
          doi = {10.1109/MCSE.2011.37},
archivePrefix = {arXiv},
       eprint = {1102.1523},
 primaryClass = {cs.MS},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2011CSE....13b..22V},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@ARTICLE{Harris:2020,
       author = {{Harris}, Charles R. and {Jarrod Millman}, K. and
         {van der Walt}, S. J. and {Gommers}, R. and
         {Virtanen}, Pauli and {Cournapeau}, David and {Wieser}, Eric and
         {Taylor}, Julian and {Berg}, Sebastian and {Smith}, Nathaniel J. and
         {Kern}, Robert and {Picus}, Matti and {Hoyer}, Stephan and
         {van Kerkwijk}, Marten H. and {Brett}, Matthew and {Haldane}, Allan and
         {Fern{\'a}ndez del R{\'\i}o}, Jaime and {Wiebe}, Mark and
         {Peterson}, Pearu and {G{\'e}rard-Marchant}, Pierre and
         {Sheppard}, Kevin and {Reddy}, Tyler and {Weckesser}, Warren and
         {Abbasi}, Hameer and {Gohlke}, Christoph and {Oliphant}, Travis E.},
        title = "{Array Programming with NumPy}",
      journal = {Nature},
         year = 2020,
       volume = {585},
        pages = {357},
          doi = {10.1038/s41586-020-2649-2},
archivePrefix = {arXiv},
       eprint = {2006.10256},
 primaryClass = {cs.MS},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2020arXiv200610256H},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@InProceedings{McKinney:2010,
  Title                    = {{Data Structures for Statistical Computing in Python}},
  Author                   = {{McKinney}, W.},
  Year                     = {2010},
  Series                   = {Proceedings of the 9th Python in Science Conference (SciPy)},
  volume                   = {445},
  pages                    = {51-56},
  doi                      = {10.25080/Majora-92bf1922-00a},
}

@InProceedings{McKinney:2011,
  Title                    = {{pandas: a Foundational Python Library for Data Analysis and Statistics}},
  Author                   = {{McKinney}, W.},
  Year                     = {2011},
  Series                   = {Python for High Performance and Scientific Computing},
  volume                   = {14},
  number                   = {9},
}

@Book{McKinney:2017,
  Title                    = {{Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython, 2nd Edition}},
  Author                   = {{McKinney}, W.},
  isbn                     = {9781491957639},
  lccn                     = {2018302150},
  Year                     = {2017},
  Publisher                = {O'Reilly Media}
}

**Comment by danehkar** [comment]
> After discussing with the JOSS editorial team, we've determined that https://github.com/atomneb/AtomNeb-py is out of scope for JOSS as it is a direct port of your earlier package (https://github.com/atomneb/AtomNeb-idl) and therefore does not reach our threshold for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).
> 
> While we can't support a pulication in JOSS related to this work, we would allow an update (addendum) to [your paper](https://joss.theoj.org/papers/10.21105/joss.00898) on `AtomNeb-idl` noting that there is now a Python port of this package.
> 

@arfon, actually,  i think that a direct port is not a correct description. There is a possibility to port IDL into Python. However, the new python package is not a port of IDL version, it is purely a new implementation in Python language and translation of IDL version into Python code. You can see the Python codes here:

https://github.com/atomneb/AtomNeb-py/blob/master/atomneb/atomneb.py

Atomic data is stored in the **structure** in IDL version, while atomic data is stored using the **dictionary** and **pandas**python  library in Python. IDL version uses the IDL **Astronomy User's Library** (https://idlastro.gsfc.nasa.gov/homepage.html), while the Python version uses **AstroPy** (https://www.astropy.org/). 

I think that the correct phrase is a Python implementation (not a Python port) of this package.

**Comment by danehkar** [comment]
@arfon I am happy to update the published paper and mention its Python implementation. Can we also revise the title of my published paper? For example, to "AtomNeb: IDL/Python Package for Atomic Data of Ionized Nebulae"

**Comment by arfon** [comment]
Similar to my [comment](https://github.com/openjournals/joss-reviews/issues/2773#issuecomment-718161693) on `pyEQUIB`, we can't modify the original paper but we can make sure the new package is mentioned in the addendum title, e.g.:

`AtomNebpy, an addendum to AtomNeb: IDL Library for Atomic Data of Ionized Nebulae` 

(or something like that)

**Comment by danehkar** [comment]
> Similar to my [comment](https://github.com/openjournals/joss-reviews/issues/2773#issuecomment-718161693) on `pyEQUIB`, we can't modify the original paper but we can make sure the new package is mentioned in the addendum title, e.g.:
> 
> `AtomNebpy, an addendum to AtomNeb: IDL Library for Atomic Data of Ionized Nebulae`
> 
> (or something like that)

The name of python package is still atomneb:
https://pypi.org/project/atomneb/
https://pypi.org/project/atomneb/

so it is better to be `AtomNeb Python Package, an addendum to AtomNeb: IDL Library for Atomic Data of Ionized Nebulae`

**Comment by danehkar** [comment]
> Similar to my [comment](https://github.com/openjournals/joss-reviews/issues/2773#issuecomment-718161693) on `pyEQUIB`, we can't modify the original paper but we can make sure the new package is mentioned in the addendum title, e.g.:
> 
> `AtomNebpy, an addendum to AtomNeb: IDL Library for Atomic Data of Ionized Nebulae`
> 
> (or something like that)

@arfon The name of python package is still atomneb:
https://pypi.org/project/atomneb/
https://pypi.org/project/atomneb/

so it is better to be `AtomNeb Python Package, an addendum to AtomNeb: IDL Library for Atomic Data of Ionized Nebulae`

**Comment by arfon** [comment]
Sounds good to me @danehkar. I've stubbed out a basic addendum format [here](https://gist.githubusercontent.com/arfon/17449e908eaa77112a8027e91d7116a0/raw/ff72f34f4971b388acd56f0f8f90e736ed2eb0f5/paper.md). Could you update the `paper.md` in the https://github.com/atomneb/AtomNeb-py repository with a paragraph describing the Python package?

Also, please do something similar over in https://github.com/openjournals/joss-reviews/issues/2773 for that package too.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @arfon as reviewer

**Comment by whedon** [comment]
OK, @arfon is now a reviewer

**Comment by arfon** [comment]
@whedon start review

@danehkar - I'm going to move this forward to 'review' even though it will only be you and I working on the addendum together (no additional external review).

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2797.

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02772/joss.02772/10.21105.joss.02772.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02772/joss.02772/10.21105.joss.02772.pdf) :page_facing_up: :point_left:

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02772/joss.02772/10.21105.joss.02772.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02772/joss.02772/10.21105.joss.02772.pdf) :page_facing_up: :point_left:

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02772/joss.02772/10.21105.joss.02772.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02772/joss.02772/10.21105.joss.02772.pdf) :page_facing_up: :point_left:
