### ISSUE TITLE
[PRE REVIEW]: pyEQUIB: Python Package for Plasma Diagnostics and Abundance Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2773]
**Submitting author:** @danehkar (<a href="http://orcid.org/0000-0003-4552-5997">Ashkbiz Danehkar</a>)
**Repository:** <a href="https://github.com/equib/pyEQUIB" target ="_blank">https://github.com/equib/pyEQUIB</a>
**Version:** v0.3.3
**Editor:** @arfon
**Reviewers:** @arfon
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @danehkar. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@danehkar if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (345.3 files/s, 77188.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          14            807           2435           2986
reStructuredText                 8            486             53           1315
TeX                              1             23              0            309
Markdown                         8             51              0             95
YAML                             4             18              0             82
DOS Batch                        2              8              1             28
make                             1              4              7              9
Bourne Shell                     1              0              0              2
-------------------------------------------------------------------------------
SUM:                            39           1397           2496           4826
-------------------------------------------------------------------------------


Statistical information for the repository '4ccb2a688adf28405c8aef7c' was
gathered on 2020/10/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ashkbiz Danehkar                73         13132           6904          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ashkbiz Danehkar           6228           47.4          0.4               19.78
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/mnras/stt1116 is OK
- 10.1093/mnras/stu203 is OK
- 10.5281/zenodo.47794 is OK
- 10.3847/0004-6256/151/2/38 is OK
- 10.1017/pasa.2018.1 is OK
- 10.21105/joss.00899 is OK
- 10.21105/joss.00898 is OK
- 10.1046/j.1365-8711.2003.06371.x is OK
- 10.1111/j.1365-2966.2005.09381.x is OK
- 10.1111/j.1365-2966.2012.20863.x is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02773/joss.02773/10.21105.joss.02773.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02773/joss.02773/10.21105.joss.02773.pdf) :page_facing_up: :point_left:

**Comment by danehkar** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02773/joss.02773/10.21105.joss.02773.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02773/joss.02773/10.21105.joss.02773.pdf) :page_facing_up: :point_left:

**Comment by danehkar** [comment]
I think @arfon might be busy. Hello @xuanxu @dfm Are either of you willing to serve as an editor for this code?

**Comment by arfon** [comment]
@danehkar - please sit tight for a little, I'll have a response for you today.

**Comment by arfon** [comment]
Hi @danehkar, many thanks for your submission to JOSS.

After discussing with the JOSS editorial team, we've determined that https://github.com/equib/pyEQUIB is out of scope for JOSS as it is a direct port of your earlier package (https://github.com/equib/proEQUIB) and therefore does not reach our threshold for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

While we can't support a pulication in JOSS related to this work, we would allow an update (addendum) to [your paper](https://joss.theoj.org/papers/10.21105/joss.00899) on `proEQUIB` noting that there is now a Python port of this package.

Please let me know if this is of interest to you and if so, I'll be happy to work with you on an update to your earlier article.

**Comment by danehkar** [comment]
I am fine with Addendum. 

Please include that its dependent Python packages are different than its IDL version: 

The package implementation requires the Python packages `NumPy` [@Walt:2011; @Harris:2020], `SciPy` [@Virtanen:2020], and `AtomNeb`. The latest version of this package can be installed directly from its repository on the GitHub using ``python setup.py install``, and its stable version from the Python Package Index (PyPi) via ``pip install pyequib`` or alternatively from the Anaconda Python package distributor via ``conda install -c conda-forge pyequib``. The online documentation, tutorials and examples are available on its GitHub page (https://equib.github.io/pyEQUIB/) and its Read the Docs documentation page (https://pyequib.readthedocs.io/).

@ARTICLE{Harris:2020,
       author = {{Harris}, C. R. and {Jarrod Millman}, K. and
         {van der Walt}, S. J. and {Gommers}, R. and
         {Virtanen}, P. and {Cournapeau}, D. and {Wieser}, E. and
         {Taylor}, Julian and {Berg}, Sebastian and {Smith}, Nathaniel J. and
         {Kern}, Robert and {Picus}, Matti and {Hoyer}, Stephan and
         {van Kerkwijk}, Marten H. and {Brett}, Matthew and {Haldane}, Allan and
         {Fern{\'a}ndez del R{\'\i}o}, Jaime and {Wiebe}, Mark and
         {Peterson}, Pearu and {G{\'e}rard-Marchant}, Pierre and
         {Sheppard}, Kevin and {Reddy}, Tyler and {Weckesser}, Warren and
         {Abbasi}, Hameer and {Gohlke}, Christoph and {Oliphant}, Travis E.},
        title = "{Array Programming with NumPy}",
      journal = {Nature},
         year = 2020,
       volume = {585},
        pages = {357},
          doi = {10.1038/s41586-020-2649-2},
archivePrefix = {arXiv},
       eprint = {2006.10256},
 primaryClass = {cs.MS},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2020arXiv200610256H},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@ARTICLE{Virtanen:2020,
       author = {{Virtanen}, P. and {Gommers}, R. and {Oliphant}, T. E. and
         {Haberland}, M. and {Reddy}, Tyler and {Cournapeau}, David and
         {Burovski}, Evgeni and {Peterson}, Pearu and {Weckesser}, Warren and
         {Bright}, Jonathan and {van der Walt}, St{\'e}fan J. and
         {Brett}, Matthew and {Wilson}, Joshua and {Millman}, K. Jarrod and
         {Mayorov}, Nikolay and {Nelson}, Andrew R.~J. and {Jones}, Eric and
         {Kern}, Robert and {Larson}, Eric and {Carey}, C.~J. and
         {Polat}, {\.I}lhan and {Feng}, Yu and {Moore}, Eric W. and {Vand
        erPlas}, Jake and {Laxalde}, Denis and {Perktold}, Josef and
         {Cimrman}, Robert and {Henriksen}, Ian and {Quintero}, E.~A. and
         {Harris}, Charles R. and {Archibald}, Anne M. and
         {Ribeiro}, Ant{\^o}nio H. and {Pedregosa}, Fabian and
         {van Mulbregt}, Paul and {SciPy 1. 0 Contributors}},
        title = "{SciPy 1.0: fundamental algorithms for scientific computing in Python}",
      journal = {Nature Methods},
         year = 2020,
        month = feb,
       volume = {17},
        pages = {261-272},
          doi = {10.1038/s41592-019-0686-2},
archivePrefix = {arXiv},
       eprint = {1907.10121},
 primaryClass = {cs.MS},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2020NatMe..17..261V},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@ARTICLE{Walt:2011,
       author = {{van der Walt}, S. and {Colbert}, S. C. and
         {Varoquaux}, G.},
        title = "{The NumPy Array: A Structure for Efficient Numerical Computation}",
      journal = {Computing in Science and Engineering},
         year = 2011,
       volume = {13},
       number = {2},
        pages = {22-30},
          doi = {10.1109/MCSE.2011.37},
archivePrefix = {arXiv},
       eprint = {1102.1523},
 primaryClass = {cs.MS},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2011CSE....13b..22V},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

**Comment by danehkar** [comment]
> After discussing with the JOSS editorial team, we've determined that https://github.com/equib/pyEQUIB is out of scope for JOSS as it is a direct port of your earlier package (https://github.com/equib/proEQUIB) and therefore does not reach our threshold for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

@arfon, actually, a direct port is not a correct description. There is a possibility to port IDL into Python. However, the new python package is not a port of IDL version, it is purely a new implementation in Python language and translation of IDL version into Python code. You can see the Python codes here:

https://github.com/equib/pyEQUIB/blob/master/pyequib/pyequib.py

IDL verison depends on the IDL Astronomy User's Library (https://idlastro.gsfc.nasa.gov/homepage.html), while the Python version depends on AstroPy (https://www.astropy.org/). Atomic data is stored in the structure in IDL version, while atomic data is stored using disctionary and pandas library in Python. Interpolation in Python is done using some functions from SciPy. 

> While we can't support a pulication in JOSS related to this work, we would allow an update (addendum) to your paper on proEQUIB noting that there is now a Python port of this package.

I think that the correct phrase is a Python implementation (not a Python port).of this package.

**Comment by danehkar** [comment]
@arfon For porting IDL package into Python, we should use [idlwrap](https://pypi.org/project/idlwrap/), https://r4lv.github.io/idlwrap/Porting%20IDL%20to%20Python.html, which is not the case her. Here we have a translation and partly implementation of this package purely in the Python language without the use of IDL language . I do not use any library such as [idlwrap](https://pypi.org/project/idlwrap/) to port IDL codes into Python. I rewrote and translated all functions purely into Python, and this package do not depend on its IDL version.

**Comment by danehkar** [comment]
@arfon I am happy to update the paper and mention its Python implementation. Can we also revise the title of my published paper? For example, to "proEQUIB/pyEQUIB: IDL/Python Package for Plasma Diagnostics and Abundance Analysis"

**Comment by arfon** [comment]
> @arfon I am happy to update the published paper and mention its Python implementation. Can we also revise the title of my published paper? For example, to "proEQUIB/pyEQUIB: IDL/Python Package for Plasma Diagnostics and Abundance Analysis"

I don't think we can modify the old paper sorry - this is considered [bad practice](https://www.stm-assoc.org/2017_09_05_STM_Guide_Preserving_the_Record_of_Science_5_September_2017.pdf). The addendum would be a separate (very short) note describing pyEQUIB. The addendum will be a citable object in itself (i.e. will have its own DOI) and we'll make sure it links back to the proEQUIB paper.

We could try and include `pyEQUIB` in the title of the addendum perhaps e.g.:

`pyEQUIB, an addendum to proEQUIB: IDL Library for Plasma Diagnostics and Abundance Analysis`

Or something like that?

**Comment by danehkar** [comment]
> I don't think we can modify the old paper sorry - this is considered [bad practice](https://www.stm-assoc.org/2017_09_05_STM_Guide_Preserving_the_Record_of_Science_5_September_2017.pdf). The addendum would be a separate (very short) note describing pyEQUIB. The addendum will be a citable object in itself (i.e. will have its own DOI) and we'll make sure it links back to the proEQUIB paper.

You probably need to include the following text in addendum: 

The Python package `pyEQUIB` requires the Python packages `NumPy` [@Walt:2011; @Harris:2020], `SciPy` [@Virtanen:2020], and `AtomNeb`. The latest version of this package can be installed directly from its repository on the GitHub using ``python setup.py install``, and its stable version from the Python Package Index (PyPi) via ``pip install pyequib`` or alternatively from the Anaconda Python package distributor via ``conda install -c conda-forge pyequib``. The online documentation, tutorials and examples are available on its GitHub page (https://equib.github.io/pyEQUIB/) and its Read the Docs documentation page (https://pyequib.readthedocs.io/).

@ARTICLE{Harris:2020,
       author = {{Harris}, C. R. and {Jarrod Millman}, K. and
         {van der Walt}, S. J. and {Gommers}, R. and
         {Virtanen}, P. and {Cournapeau}, D. and {Wieser}, E. and
         {Taylor}, Julian and {Berg}, Sebastian and {Smith}, Nathaniel J. and
         {Kern}, Robert and {Picus}, Matti and {Hoyer}, Stephan and
         {van Kerkwijk}, Marten H. and {Brett}, Matthew and {Haldane}, Allan and
         {Fern{\'a}ndez del R{\'\i}o}, Jaime and {Wiebe}, Mark and
         {Peterson}, Pearu and {G{\'e}rard-Marchant}, Pierre and
         {Sheppard}, Kevin and {Reddy}, Tyler and {Weckesser}, Warren and
         {Abbasi}, Hameer and {Gohlke}, Christoph and {Oliphant}, Travis E.},
        title = "{Array Programming with NumPy}",
      journal = {Nature},
         year = 2020,
       volume = {585},
        pages = {357},
          doi = {10.1038/s41586-020-2649-2},
archivePrefix = {arXiv},
       eprint = {2006.10256},
 primaryClass = {cs.MS},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2020arXiv200610256H},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@ARTICLE{Virtanen:2020,
       author = {{Virtanen}, P. and {Gommers}, R. and {Oliphant}, T. E. and
         {Haberland}, M. and {Reddy}, Tyler and {Cournapeau}, David and
         {Burovski}, Evgeni and {Peterson}, Pearu and {Weckesser}, Warren and
         {Bright}, Jonathan and {van der Walt}, St{\'e}fan J. and
         {Brett}, Matthew and {Wilson}, Joshua and {Millman}, K. Jarrod and
         {Mayorov}, Nikolay and {Nelson}, Andrew R.~J. and {Jones}, Eric and
         {Kern}, Robert and {Larson}, Eric and {Carey}, C.~J. and
         {Polat}, {\.I}lhan and {Feng}, Yu and {Moore}, Eric W. and {Vand
        erPlas}, Jake and {Laxalde}, Denis and {Perktold}, Josef and
         {Cimrman}, Robert and {Henriksen}, Ian and {Quintero}, E.~A. and
         {Harris}, Charles R. and {Archibald}, Anne M. and
         {Ribeiro}, Ant{\^o}nio H. and {Pedregosa}, Fabian and
         {van Mulbregt}, Paul and {SciPy 1. 0 Contributors}},
        title = "{SciPy 1.0: fundamental algorithms for scientific computing in Python}",
      journal = {Nature Methods},
         year = 2020,
        month = feb,
       volume = {17},
        pages = {261-272},
          doi = {10.1038/s41592-019-0686-2},
archivePrefix = {arXiv},
       eprint = {1907.10121},
 primaryClass = {cs.MS},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2020NatMe..17..261V},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

@ARTICLE{Walt:2011,
       author = {{van der Walt}, S. and {Colbert}, S. C. and
         {Varoquaux}, G.},
        title = "{The NumPy Array: A Structure for Efficient Numerical Computation}",
      journal = {Computing in Science and Engineering},
         year = 2011,
       volume = {13},
       number = {2},
        pages = {22-30},
          doi = {10.1109/MCSE.2011.37},
archivePrefix = {arXiv},
       eprint = {1102.1523},
 primaryClass = {cs.MS},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2011CSE....13b..22V},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

**Comment by danehkar** [comment]
> We could try and include `pyEQUIB` in the title of the addendum perhaps e.g.:
> 
> `pyEQUIB, an addendum to proEQUIB: IDL Library for Plasma Diagnostics and Abundance Analysis`
> 
> Or something like that?

@arfon it is OK.

**Comment by danehkar** [comment]
@arfon 

It is better to be `pyEQUIB Python Package, an addendum to AtomNeb: IDL Library for Atomic Data of Ionized Nebulae`

**Comment by danehkar** [comment]
@arfon 

It is better to be `pyEQUIB Python Package, an addendum to proEQUIB: IDL Library for Plasma Diagnostics and Abundance Analysis`

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @arfon as reviewer

**Comment by whedon** [comment]
OK, @arfon is now a reviewer

**Comment by arfon** [comment]
@whedon start review

@danehkar - I'm going to move this forward to 'review' even though it will only be you and I working on the addendum together (no additional external review).

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2798.

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02773/joss.02773/10.21105.joss.02773.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02773/joss.02773/10.21105.joss.02773.pdf) :page_facing_up: :point_left:
