### ISSUE TITLE
[PRE REVIEW]: CalValWaves: A Python package for wave reanalysis calibration with satellite altimeter data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2774]
**Submitting author:** @javitausia (<a href="http://orcid.org/0000-0002-2299-2915">Javier Tausia Hoyal</a>)
**Repository:** <a href="https://github.com/javitausia/CalValWaves" target ="_blank">https://github.com/javitausia/CalValWaves</a>
**Version:** v.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @javitausia. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@javitausia if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ocemod.2018.09.001 is OK
- 10.1175/JTECH-D-11-00008.1 is OK
- 10.21105/joss.02083 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2774 with the following error: 

 pandoc: /images/calibration-satellite.png: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.33 s (33.2 files/s, 51375.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1           2001              2          13222
Python                           5             91            130            638
Markdown                         2             55              0            122
Jupyter Notebook                 1              0            662             44
TeX                              1              2              0             30
YAML                             1              0              0             18
-------------------------------------------------------------------------------
SUM:                            11           2149            794          14074
-------------------------------------------------------------------------------


Statistical information for the repository '34cb50207cbdc1460ddbea87' was
gathered on 2020/10/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Javier Tausia hoyal              2            51             32           13.41
Javier Tausía                   16           242            294           86.59

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Javier Tausia hoyal         859         1684.3          1.3                7.68
```

**Comment by javitausia** [comment]
Here there are some reviewers I think could be potential:

callumrollo, marda-science and dbuscombe-usgs, evaristor, rabernat,
dspelaez, DamienIrving, bradyrx, wingtorres, koldunovn, castelao,
ali-ramadhan...

as they are related with python, machine learning and oceanography!!

Regards ;)

**Comment by kyleniemeyer** [comment]
@whedon query scope

Hi @javitausia, thanks for your submission. Due to the relatively small size of your software package, the editorial board is going to evaluate whether this is in scope for JOSS.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@javitausia - thanks for your submission to JOSS. After consulting with the editorial team, this submission was deemed too small to be considered in JOSS (see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
