### ISSUE TITLE
[PRE REVIEW]: The nnlib2 library and nnlib2Rcpp R package for implementing neural networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2775]
**Submitting author:** @VNNikolaidis (<a href="http://orcid.org/0000-0003-1471-8788">Vasilis Nikolaidis</a>)
**Repository:** <a href="https://github.com/VNNikolaidis/nnlib2Rcpp" target ="_blank">https://github.com/VNNikolaidis/nnlib2Rcpp</a>
**Version:** v0.1.5
**Editor:** @kakiac
**Reviewers:** @schnorr
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @VNNikolaidis. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@VNNikolaidis if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (461.1 files/s, 86273.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             18           1039            748           3039
C/C++ Header                    20            712            549           2058
Markdown                         4             48              0            104
TeX                              1             12              0             95
R                                2              3              2             10
-------------------------------------------------------------------------------
SUM:                            45           1814           1299           5306
-------------------------------------------------------------------------------


Statistical information for the repository 'a301ac4f575ec42bb16f5e81' was
gathered on 2020/10/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vasilis N. Nikolaidi             1          8145              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vasilis N. Nikolaidi       8145          100.0          0.0               16.22
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1163/1574-9347_bnp_e612900 may be a valid DOI for title: Keras
- 10.1016/0893-6080(90)90030-o may be a valid DOI for title: Artificial Neural Systems: Foundations, Paradigms, Applications, and Implementations
- 10.1504/gber.2013.050667 may be a valid DOI for title: ANS-based Preprocessing of Company Performance Indicators

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02775/joss.02775/10.21105.joss.02775.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02775/joss.02775/10.21105.joss.02775.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @VNNikolaidis, I'm a bit confused about your repository—it is named "joss", when you should really be submitting the repository for one of the packages (probably the main R package). Is that what the repository contains, and it is just not called "nnlib2Rcpp" for some reason?

**Comment by VNNikolaidis** [comment]
Dear Kyle, thank you for your comment. You are right, I misinterpreted the instructions in Submission Requirements (this is my first submission on JOSS). They state "Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software (although they may be in a short-lived branch which is never merged with the default)".

Instead, I created a new repository which is a copy of the actual repository, and added the paper there.

The actual repository (containing the main R package as you correctly mentioned, and also the C++ library it uses) is in https://github.com/VNNikolaidis/nnlib2Rcpp

Since I could easily add the paper there (as a branch this time), and resubmit it, maybe that is a good way to correct the issue.


________________________________

**Comment by kyleniemeyer** [comment]
@VNNikolaidis got it—yes, it would be great if you can add the paper to the actual repository (on a branch is fine). We can update the repository URL here, you do not need to resubmit. @openjournals/dev can you help with this?

**Comment by VNNikolaidis** [comment]
That's great, I will add the paper to the actual repository (or a branch) soon and get back to you. I would do it now, but I worry not to mess with the delicate R package structure as it is known to be strict, so I need to investigate this a little just to be sure.
Thank you again!

________________________________

**Comment by kyleniemeyer** [comment]
@VNNikolaidis ok, sounds good. I will pause this until then.

**Comment by VNNikolaidis** [comment]
Not a long pause I am afraid. To avoid adding a directory that R-build may complain about<https://blog.r-hub.io/2020/05/20/rbuildignore/>, I followed the easy solution and created a branch (JOSS) with the paper content (no other changes). It can be found in https://github.com/VNNikolaidis/nnlib2Rcpp/tree/JOSS
I also removed the copy (joss repository) as it is no longer needed and may confuse someone.
Please let me know if this is ok. Thanks again!

________________________________

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from-branch=JOSS

**Comment by whedon** [comment]
PDF failed to compile for issue #2775 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02775/joss.02775/10.21105.joss.02775.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02775/joss.02775/10.21105.joss.02775.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@karthik would you be able to edit this one instead?

**Comment by kyleniemeyer** [comment]
@whedon invite @bmcfee as editor

Hey @bmcfee, could you edit this submission?

**Comment by whedon** [comment]
@bmcfee has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@karthik @bmcfee @terrytangyuan @arokem can one of you handle this submission? Thanks

**Comment by arokem** [comment]
Sorry. I can only handle one submission at a time for now and already have one ongoing.

**Comment by terrytangyuan** [comment]
I am not able to handle additional ones at this time either.

**Comment by karthik** [comment]
Same as the above two.

**Comment by Kevin-Mattheus-Moerman** [comment]
Okay. Thanks @karthik @arokem @xuanxu that is fine. I'll check with @bmcfee if they are able to help.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @bmcfee as editor

**Comment by whedon** [comment]
@bmcfee has been invited to edit this submission.

**Comment by kakiac** [comment]
👋  @kyleniemeyer I have some capacity and could take this up, feel free to assign me as editor :)

**Comment by arfon** [comment]
@whedon assign @kakiac as editor

**Comment by whedon** [comment]
OK, the editor is @kakiac

**Comment by arfon** [comment]
💖 thanks @kakiac!

**Comment by kakiac** [comment]
👋  @VNNikolaidis many thanks for your submission! From a quick inspection of this submission I can see that it meets our [submission criteria](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) - and shows great potential of doing Deep Learning and NNs for R geeks! 🤓 

It is however shorter than our JOSS typical papers, so whilst I am looking for reviewers, can I please ask you to look at some of the published papers here https://joss.theoj.org/papers/published to get inspiration on how to augment/expand your paper? Thank you 👍

**Comment by kakiac** [comment]
:wave: @gagolews, @brunaw, @schnorr would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by gagolews** [comment]
@kakiac Apologies, my review queue is quite bloated atm. Unless you're fine with a referee report returned in 3+ weeks.

**Comment by VNNikolaidis** [comment]
Dear @kakiac<https://github.com/kakiac> I thank you for your interest, feedback and advice.
It is indeed a tool for geeks, I hope there may be some out there who might be interested to use it for experimentation, or -even better- contribute to improve it.
I fully understand your comment about the length of the paper and I agree, when compared to current papers published, it is shorter. I actually tried to be brief, for three reasons:
(a) to closely follow the sample paper (Gala),
(b) to comply with the guidelines mentioning that it should “not focus on new research results”, and that “a full-length paper is not permitted, and software documentation such as API functionality should not be in the paper”.
(c) I personally prefer reading short papers.
I can think of material that could be added, but I wonder if would break (b) above and/or make the paper too long.
Let me investigate this a little. As I am unfamiliar with the process, should material be added to the paper do I simply go ahead and do them on the repository (even now)?
Thank you and best regards,
V.Nikolaidis
________________________________

**Comment by brunaw** [comment]
Hi @kakiac, I'm in the same situation as @gagolews, my next few weeks are quite busy. I prefer not to review this time, apologies for that!

**Comment by schnorr** [comment]
Hi @kakiac. Thanks for the invitation. I've just checked the PDF generated by dear @whedon  and it is 2-page long. I could do a review of the code and the 2-page manuscript until de end of November. If that is okay for you, let's go ahead.

**Comment by kakiac** [comment]
@brunaw no problem at all, many thanks for letting us know.

**Comment by kakiac** [comment]
@schnorr apologies, I seem to have missed your window - I have added you as a reviewer in case you are still able to review. If not, let me know :)

**Comment by kakiac** [comment]
@whedon assign @schnorr as reviewer

**Comment by whedon** [comment]
OK, @schnorr is now a reviewer

**Comment by kakiac** [comment]
@gagolews, no worries, I will try to find an alternative reviewer. Let me know if your availability has changed in the meantime, though!

**Comment by kakiac** [comment]
@VNNikolaidis re your question:

> As I am unfamiliar with the process, should material be added to the paper do I simply go ahead and do them on the repository (even now)?

Yes please! Here at JOSS we actually encourage you to continuously improve the paper throughout the reviewing process. Editors and reviewers, we all tend to engage the authors freely in a conversation aimed at improving the paper.

**Comment by kakiac** [comment]
re your comments here: https://github.com/openjournals/joss-reviews/issues/2775#issuecomment-724629047, I fully agree with your points. It's not about length per se - but the paper needs to help both the specialist and the non-specialist reader:

- understand the high-level functionality and purpose of the software 
- understand the research purpose of the software
- place the current software in context, by reading about other software addressing related needs
- read about (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.

If you could do some initial thinking around it, and make any modifications, and we (the reviewers and I) might make some suggestions on areas for improvement 👍 

Thanks in advance,

**Comment by kakiac** [comment]
:wave @agisga @billchenxi @MohmedSoudy @paragkulkarni11 would any of you be available to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by kakiac** [comment]
@schnorr I will initiate the review issue, where you can go and make a start on your review, whilst I look for the second reviewer :) Many thanks again,

**Comment by kakiac** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2876.
