### ISSUE TITLE
[PRE REVIEW]: PRDA: An R pakcage for Prospective and Retrospective Design Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2776]
**Submitting author:** @ClaudioZandonella (<a href="http://orcid.org/0000-0001-7721-6318">Claudio Zandonella Callegher</a>)
**Repository:** <a href="https://github.com/ClaudioZandonella/PRDA" target ="_blank">https://github.com/ClaudioZandonella/PRDA</a>
**Version:** v1.0.0.900
**Editor:** @cMadan
**Reviewers:** @DominiqueMakowski, @mmrabe
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ClaudioZandonella. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @cMadan.

@ClaudioZandonella if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (371.3 files/s, 43185.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               22            614            867           1357
Markdown                         5            122              0            371
TeX                              2             20              0            228
C++                              3             32             31            155
Rmd                              5            233            377            124
YAML                             3             27             12             82
-------------------------------------------------------------------------------
SUM:                            40           1048           1287           2317
-------------------------------------------------------------------------------


Statistical information for the repository 'a5b9f3b36de00d75aea0da63' was
gathered on 2020/10/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Claudio Zandonella              22           825            607          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Claudio Zandonella          218           26.4          1.9               14.22
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fpsyg.2019.02893 is OK
- 10.31234/osf.io/q9f86 is OK
- 10.1177/1745691614551642 is OK
- 10.7326/0003-4819-121-3-199408010-00008 is OK
- 10.2527/jas.2006-449 is OK
- 10.1111/bmsp.12132 is OK
- 10.1136/bmj.325.7375.1304 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02776/joss.02776/10.21105.joss.02776.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02776/joss.02776/10.21105.joss.02776.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @cMadan, I realize that R is outside your primary experience, but this seems to be up your alley. Could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by cMadan** [comment]
@kyleniemeyer, sure, I can take this one.

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@ClaudioZandonella, do you have any suggestions for reviewers? (See initial comment in this issue.)

**Comment by ClaudioZandonella** [comment]
@cMadan, thanks for accepting being the editor.
I list below possible reviewers:
 - mmrabe
 - lindemann09
 - jacobsoj

Let me know if more names are needed. 
Thanks!

**Comment by cMadan** [comment]
@ClaudioZandonella, before inviting reviewers I did an initial pass of the repository to see check if I noticed anything missing, and I don't see clear community guidelines.

You can see the reviewer checklist here (https://joss.readthedocs.io/en/latest/review_checklist.html), this is the exact same list that reviewers would need to evaluate your submission on. Please take a look and make sure that you think all of these are reasonably addressed in your submission.

Let me know after you've revised accordingly and I'll move forward with the review process.

**Comment by ClaudioZandonella** [comment]
@cMadan, thanks! I just added a Contributor Code of Conduct link.

I checked all the other points. Probably the only other missing information is a clear statement about contribution and authorship. The other authors gave fundamental contributions to the package development in the theoretical aspects, design phase, and paper writing. However, I coded the most part so considering git commits it seems that I did most of the work although all the authors contributed in fundamental aspects.

I would like to not add verbose information in the read me about contribution and authorship. Instead, I could discuss it with the reviewers if required.

**Comment by cMadan** [comment]
@mmrabe @terrytangyuan @ejolly @DominiqueMakowski, would you be available and interested in reviewing this submission?

**Comment by arfon** [comment]
@cMadan - just a heads up that @terrytangyuan is actually a JOSS editor these days and so probably shouldn't be asked to review for us too 😁

**Comment by DominiqueMakowski** [comment]
@cMadan yes I can review it ☺️

**Comment by ejolly** [comment]
@cMadan Unfortunately I don't do much R work these days so I don't think I'd be a good reviewer. I actually requested an edit to the languages I'm listed for on a [different review](https://github.com/openjournals/joss-reviews/issues/2471#issuecomment-701711404) just to make sure I'm not a bottleneck for R package submissions in the future. Maybe that didn't get updated?

**Comment by cMadan** [comment]
@DominiqueMakowski, great, thanks! I'll start the review after I find a second reviewer. 

@ejolly, no worries, I'll get that sorted. 

@terrytangyuan @arfon, makes sense, thanks for pointing that out!

**Comment by cMadan** [comment]
@whedon add @DominiqueMakowski as reviewer

**Comment by whedon** [comment]
OK, @DominiqueMakowski is now a reviewer

**Comment by cMadan** [comment]
@lindemann09 @trettenbrein @nhejazi @prdm0, would you be available and interested in reviewing this submission?

**Comment by mmrabe** [comment]
Hi, @ClaudioZandonella and @cMadan . 👋 Sorry for the late reply. Thanks for considering me. I'm available and would be happy to review this package.

**Comment by trettenbrein** [comment]
Hi @cMadan,

Thanks for your request. I see that you already have two positive responses, but in case you still need someone else I'd be happy to review the package.

**Comment by cMadan** [comment]
@mmrabe - thanks for agreeing, I'll add you as a reviewer and start the review process now.

@trettenbrein - that's great to hear! I'll definitely keep you in mind when another relevant submission comes in.

**Comment by cMadan** [comment]
@whedon add @mmrabe as reviewer

**Comment by whedon** [comment]
OK, @mmrabe is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2810.

**Comment by lindemann09** [comment]
> @cMadan Sorry, I'm currently too busy with other reviews and not available.  Thanks for considering me. I'm happy to help out next time.
