### ISSUE TITLE
[PRE REVIEW]: MiTfAT: A Python-based scikit-learn-friendly fMRI Analysis Tool, Made in Tuebingen.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2778]
**Submitting author:** @vahid-sb (<a href="http://orcid.org/0000-0001-6544-7960">Vahid S. Bokharaie</a>)
**Repository:** <a href="https://github.com/vahid-sb/MiTfAT" target ="_blank">https://github.com/vahid-sb/MiTfAT</a>
**Version:** v0.1.7
**Editor:** @arokem
**Reviewers:** @JonathanReardon, @emdupre
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vahid-sb. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arokem.

@vahid-sb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (177.2 files/s, 31494.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            504           1023           1870
reStructuredText                 1             39              7             54
Markdown                         1             21              0             36
YAML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            20            564           1030           1961
-------------------------------------------------------------------------------


Statistical information for the repository 'ae544ff2e67d943433bc2cd6' was
gathered on 2020/10/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vahid Bokharaie                  7          4095            698          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vahid Bokharaie            3397           83.0          0.0               14.84
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2778 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (90e95d3ba1bee68e7ed07805/paper.md): could not find expected ':' while scanning a simple key at line 23 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Hi @vahid-sb, it looks like the header of your paper may not be valid—please take a look at the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). It may just be missing the `---` line to close the YAML header section.

Also, your reference(s) should be contained in a .bib file, rather than hardcoded in the paper.

**Comment by kyleniemeyer** [comment]
@arokem could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @arokem as editor

**Comment by whedon** [comment]
@arokem has been invited to edit this submission.

**Comment by vahid-sb** [comment]
> Hi @vahid-sb, it looks like the header of your paper may not be valid—please take a look at the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). It may just be missing the `---` line to close the YAML header section.
> 
> Also, your reference(s) should be contained in a .bib file, rather than hardcoded in the paper.

HI @kyleniemeyer, both issues are resolved now. Thanks for drawing my attention to them. Seems I deleted '---' after the header. Didn't know it is part of .md file commands. Also, reference is now read from a bib file.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02778/joss.02778/10.21105.joss.02778.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02778/joss.02778/10.21105.joss.02778.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@vahid-sb thanks, looks good now. I'll wait on @arokem to (hopefully) take over soon and identify reviewers.

**Comment by arokem** [comment]
Yeah. I can take this one.

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
👋 @snastase : Would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
👋 @JonathanReardon : Would you be willing to review this article for JOSS?

**Comment by JonathanReardon** [comment]
Hi @arokem, I'm happy to review this -- looks like a nice project. When would you want it completed by?

**Comment by arokem** [comment]
@vahid-sb : while we are waiting for reviewers to come on-board, a few comments from me: 

- There are several other software libraries that do things that are closely related to what MiTfAT does. For example, [nilearn](https://nilearn.github.io/). I think that you will need to add a section to your paper describing previous similar work and describing the relationship between the present library and this previous work.
- The word "Neuroscience" (first line) should not be capitalized. 
- "belts and whistles" should be "bells and whistles". I should also add that I don't understand exactly what this sentence means. It seems to suggest that MiTfAT is somehow simpler to use than other software, but provides little evidence to support this assertion. I would rethink how you would like to say this in a manner that emphasizes design choices made by different libraries, rather than posing this as an assertion. 
- Though novelty per-se is not a requirement, the text does imply that MiTfAT implements novel methods. What are these analysis methods?
- The word "accomponied" should be spelled "accompanied".

**Comment by arokem** [comment]
@JonathanReardon : thanks for your quick response here! We usually aim to finish all parts of the review within six weeks, so if you think that you could turn around comments in two-three weeks, that would be ideal.

**Comment by arokem** [comment]
@whedon add @JonathanReardon as reviewer

**Comment by whedon** [comment]
OK, @JonathanReardon is now a reviewer

**Comment by JonathanReardon** [comment]
> @JonathanReardon : thanks for your quick response here! We usually aim to finish all parts of the review within six weeks, so if you think that you could turn around comments in two-three weeks, that would be ideal.

Yes, absolutely fine! thanks

**Comment by vahid-sb** [comment]
> @vahid-sb : while we are waiting for reviewers to come on-board, a few comments from me:
> 
>     * There are several other software libraries that do things that are closely related to what MiTfAT does. For example, [nilearn](https://nilearn.github.io/). I think that you will need to add a section to your paper describing previous similar work and describing the relationship between the present library and this previous work.
> 
>     * The word "Neuroscience" (first line) should not be capitalized.
> 
>     * "belts and whistles" should be "bells and whistles". I should also add that I don't understand exactly what this sentence means. It seems to suggest that MiTfAT is somehow simpler to use than other software, but provides little evidence to support this assertion. I would rethink how you would like to say this in a manner that emphasizes design choices made by different libraries, rather than posing this as an assertion.
> 
>     * Though novelty per-se is not a requirement, the text does imply that MiTfAT implements novel methods. What are these analysis methods?
> 
>     * The word "accomponied" should be spelled "accompanied".

Thanks, @arokem, and thanks @JonathanReardon for agreeing to review. 
@arokem I have updated the paper correcting the typos you kindly reminded me of. About Nilearn, I am aware of that and it is one of the requirements for mitfat, although I have used it merely for IO operations. But mitfat treats the data in a more comprehensive manner, not simply as separate NumPy arrays that might or might not be related. I have defined a class for fMRI data which is the cornerstone of the code. I added a short description of that to the paper. And about novelty, it is true that what I was looking for, I could find in the common fMRI analysis packages, but that does not mean the methods themselves are new. Simply smart applications of undergraduate mathematics, that's how I would characterize them. For example, the detrending method discussed in Chapter 8 of the manual.

**Comment by JonathanReardon** [comment]
Apologies if this is a mistake my end, but has the review process started yet? it's not showing as started my end. Also, am I the only person reviewing? Thanks.

**Comment by arokem** [comment]
Thanks for checking. The review process has not started yet. I still need to find one more reviewer but I have been somewhat distracted in the last week or so.

**Comment by JonathanReardon** [comment]
> Thanks for checking. The review process has not started yet. I still need to find one more reviewer but I have been somewhat distracted in the last week or so.

No problem at all, just wanted to be sure.

**Comment by emdupre** [comment]
Yes, I'd be happy to review ! Let me know what I can do at this point to help in that process.

**Comment by arokem** [comment]
@whedon add @emdupre as reviewer

**Comment by whedon** [comment]
OK, @emdupre is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2827.
