### ISSUE TITLE
[PRE REVIEW]: opty: Software For Trajectory Optimization and Parameter Identification Using Direct Collocation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#278]
**Submitting author:** @moorepants (<a href="http://orcid.org/0000-0002-8698-6143">Jason K. Moore</a>)
**Repository:** <a href="https://github.com/csu-hmc/opty" target ="_blank">https://github.com/csu-hmc/opty</a>
**Version:** v0.2.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @cybanical

**Author instructions**

Thanks for submitting your paper to JOSS @moorepants. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@moorepants if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @Kevin-Mattheus-Moerman it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @Kevin-Mattheus-Moerman - the submitting author suggested you as an editor. Whaddya think?

**Comment by Kevin-Mattheus-Moerman** [comment]
@jakevdp Do you want to review this? If yes, great I can remain editor. If not, could you be editor and/or help find a reviewer?

**Comment by moorepants** [comment]
Here are some potential reviewer sources:

Main contributors to:
- Casadi: https://github.com/casadi/casadi/graphs/contributors
- Opensim: https://github.com/opensim-org/opensim-core/graphs/contributors
- BTK: https://github.com/Biomechanical-ToolKit/BTKCore/graphs/contributors
- Simbody: https://github.com/simbody/simbody/graphs/contributors
- Drake: https://github.com/RobotLocomotion/drake/graphs/contributors
- psopt: https://github.com/PSOPT/psopt/graphs/contributors
- acado: https://github.com/acado/acado/graphs/contributors

**Comment by moorepants** [comment]
I'm pinging my co-author @tvdbogert so that he is subscribed to this thread.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @cybanical as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @cybanical

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/300. Feel free to close this issue now!
