### ISSUE TITLE
[REVIEW]: Social-Annotate: Browser extension to annotate and collect social media data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2780]
**Submitting author:** @onurvarol (<a href="http://orcid.org/0000-0002-3994-6106">Onur Varol</a>)
**Repository:** <a href="https://github.com/uluturki/social-annotate" target ="_blank">https://github.com/uluturki/social-annotate</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @davekinkead, @sara-02
**Archive:** Pending

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b99e61f7f362321315c6fc9feba1efde/status.svg)](https://joss.theoj.org/papers/b99e61f7f362321315c6fc9feba1efde)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b99e61f7f362321315c6fc9feba1efde"><img src="https://joss.theoj.org/papers/b99e61f7f362321315c6fc9feba1efde/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b99e61f7f362321315c6fc9feba1efde/status.svg)](https://joss.theoj.org/papers/b99e61f7f362321315c6fc9feba1efde)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/uluturki/social-annotate" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@davekinkead & @sara-02, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lorenanicole know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/uluturki/social-annotate">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@onurvarol) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/uluturki/social-annotate">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@onurvarol) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @davekinkead, @sara-02 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Reminder set for @davekinkead in 1 week

**Comment by whedon** [comment]
Reminder set for @sara-02 in 1 week

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.18653/v1/p18-1022 may be a valid DOI for title: A stylometric inquiry into hyperpartisan and fake news
- 10.1002/hbe2.115 may be a valid DOI for title: Arming the public with artificial intelligence to counter social bots
- 10.1002/meet.14504701444 may be a valid DOI for title: HCI browser: A tool for studying web search behavior
- 10.1109/asonam.2016.7752207 may be a valid DOI for title: Stop clickbait: Detecting and preventing clickbaits in online news media
- 10.1109/tvcg.2019.2934266 may be a valid DOI for title: VASSL: A Visual Analytics Toolkit for Social Spambot Labeling
- 10.1371/journal.pone.0069958 may be a valid DOI for title: Comparing the quality of crowdsourced data contributed by expert and non-experts

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02780/joss.02780/10.21105.joss.02780.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02780/joss.02780/10.21105.joss.02780.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@davekinkead, @sara-02 - This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/2780 so that a link is created to this thread (and @lorenanicole can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by davekinkead** [comment]
Hi @arfon I've completed a first pass and added issues on the software's issue page https://github.com/uluturki/social-annotate/issues.

If the author(s) could let me know when they have  addressed or clarified these, that would be 🥳 ... I'll have another look then.

**Comment by sara-02** [comment]
@davekinkead I guess we need an issue for documentation as well, covering the points ` t**he core functionality of the software documented to a satisfactory level (e.g., API method documentation)? and Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems)**`. If you have not already covered them in the existing issues I can add one.
 I see I docs folder but I do not think it is connected to a site like readthe docs or something @onurvarol  am I missing something w.r.t doc?

**Comment by davekinkead** [comment]
Agree @sara-02

**Comment by sara-02** [comment]
Added: https://github.com/uluturki/social-annotate/issues/25

**Comment by whedon** [comment]
:wave: @davekinkead, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @sara-02, please update us on how your review is going.

**Comment by sara-02** [comment]
Hey, @onurvarol  any updated on the process w.r.t issues we posted?

**Comment by onurvarol** [comment]
Thank you @sara-02 for checking. @uluturki and I working on revisions and improving the documentation and the paper to address all the requests.

**Comment by arfon** [comment]
:wave: just checking in here. How are you getting on with your updates and revisions @onurvarol?

**Comment by onurvarol** [comment]
Thank you @arfon for the reminder. @uluturki recently started a new job and I have been building my lab as a PI, so it was a busy couple of months. This summer one of my students will take the lead, we hope to wrap it up quickly.

**Comment by arfon** [comment]
Thanks @onurvarol. Any news on possible updates?

**Comment by onurvarol** [comment]
Hi @arfon, our new member working on the changes and we will submit the revisions in a month. Thank you for your patience and following this up.

**Comment by danielskatz** [comment]
👋 @onurvarol - Can you provide an update on this?

**Comment by arfon** [comment]
@lorenanicole – this submission has now been under review for over a year. I propose that if there isn't a major revision by the authors in the next two weeks, we proceed to reject this submission.

**Comment by arfon** [comment]
@whedon assign me as editor

Unfortunately @lorenanicole is no longer able to edit this submission so I'll be taking over from here.

**Comment by arfon** [comment]
@whedon remind me in two weeks

**Comment by arfon** [comment]
@whedon reject

This submission is being rejected due to inactivity on the part of the author. @davekinkead, @sara-02, @lorenanicole  – many thanks for your efforts here. Sorry this one didn't work out.

**Comment by whedon** [comment]
Paper rejected.
