### ISSUE TITLE
[REVIEW]: hectorui: A web-based interactive scenario builder and visualization application for the Hector climate model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2782]
**Submitting author:** @evanoffPNNL (<a href="http://orcid.org/0000-0002-8858-2783">Jason Evanoff</a>)
**Repository:** <a href="https://github.com/JGCRI/hectorui/" target ="_blank">https://github.com/JGCRI/hectorui/</a>
**Version:** v1.1.6
**Editor:** @kthyng
**Reviewer:** @marvinjonathcn, @tscheypidi
**Archive:** <a href="https://doi.org/10.5281/zenodo.4317756" target="_blank">10.5281/zenodo.4317756</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/41f3715537e7e5af5ecedcb9c123c8c4/status.svg)](https://joss.theoj.org/papers/41f3715537e7e5af5ecedcb9c123c8c4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/41f3715537e7e5af5ecedcb9c123c8c4"><img src="https://joss.theoj.org/papers/41f3715537e7e5af5ecedcb9c123c8c4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/41f3715537e7e5af5ecedcb9c123c8c4/status.svg)](https://joss.theoj.org/papers/41f3715537e7e5af5ecedcb9c123c8c4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JGCRI/hectorui/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@marvinjonathcn & @tscheypidi, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JGCRI/hectorui/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@evanoffPNNL) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JGCRI/hectorui/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@evanoffPNNL) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @marvinjonathcn, @tscheypidi it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5194/gmd-8-939-2015 is OK
- 10.5194/bg-13-4329-2016 is OK
- 10.1371/journal.pone.0223542 is OK
- 10.5194/gmd-12-677-2019 is OK
- 10.1016/j.techfore.2006.05.026 is OK
- 10.1007/s10584-011-0149-y is OK
- 10.5547/ISSN0195-6574-EJ-VolSI2006-NoSI3-17 is OK
- 10.1007/s10584-011-0151-4 is OK
- 10.1007/s10584-011-0152-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02782/joss.02782/10.21105.joss.02782.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02782/joss.02782/10.21105.joss.02782.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@marvinjonathcn, @tscheypidi: this is where the actual review takes places. Please look through [reviewer docs](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) to see how the review process works, and look through the checklist above too. As issues arise in the review process, open an issue per comment in the submission repo on github and link back to this issue. Don't hesitate to ask if you have any questions about how it all works especially since it is a little unusual!

**Comment by tscheypidi** [comment]
@evanoffPNNL, I am just checking the list of authors and did not find all mentioned authors in the commit history of hectorui. Could you please clarify how Stephanie Waldhoff, Abigail Snyder and Corinne Hartin contributed to the Software?

**Comment by whedon** [comment]
:wave: @tscheypidi, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @marvinjonathcn, please update us on how your review is going.

**Comment by tscheypidi** [comment]
I am currently waiting for installation instructions (https://github.com/JGCRI/hectorui/issues/19) which are required in order to check installation and functionality of the software. 

All other parts have been checked and will get ticked off as soon as the corresponding issues have been resolved (https://github.com/JGCRI/hectorui/issues/20, https://github.com/JGCRI/hectorui/issues/22 and https://github.com/JGCRI/hectorui/issues/23). 

https://github.com/JGCRI/hectorui/issues/21 is somehow independent as it is a suggestion but no requirement to complete the review process.

**Comment by evanoffPNNL** [comment]
@tscheypidi Hey Jan, thanks for your prompt review. I believe we have addressed all of your concerns in the latest release, 1.1.4.

**Comment by crvernon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02782/joss.02782/10.21105.joss.02782.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02782/joss.02782/10.21105.joss.02782.pdf) :page_facing_up: :point_left:

**Comment by crvernon** [comment]
@tscheypidi thanks for the thorough review!  It has been very helpful.

**Comment by tscheypidi** [comment]
@crvernon @evanoffPNNL you have developed a nice and useful tool here. Thanks for taking the effort to make your work so accessible to others.

**Comment by tscheypidi** [comment]
@kthyng I finished my review and recommend the paper to be accepted for publication. All my concerns have been adressed and resolved by the authors.

**Comment by kthyng** [comment]
@tscheypidi Thanks for your review!

**Comment by kthyng** [comment]
Hi @marvinjonathcn! Just a friendly ping here to remind you about this review. When might you be able to work on this? Thanks!

**Comment by marvinjonathcn** [comment]
Hi @kthyng this weekend I finish the review. I was a bit busy, excuse me.

**Comment by marvinjonathcn** [comment]
I'm done with the review. The application is easy to understand and use, it will be very useful for the community.

**Comment by evanoffPNNL** [comment]
Thanks @marvinjonathcn ! In regards to your other issue, would putting some text and a link in the readme file/github page be sufficient?

**Comment by crvernon** [comment]
@kthyng ... @evanoffPNNL and I have addressed all reviewer comments and all changes are currently represented in the new release v1.1.5 (GitHub: https://github.com/JGCRI/hectorui/releases/tag/v1.1.5 ; Zenodo:  https://zenodo.org/record/4302333#.X8fCSKpKhUM).  Please let us know if further information is needed.  

We have found this review to be very helpful and it has strengthened this package!  Thanks to @tscheypidi and @marvinjonathcn for all of their comments and suggestions!

**Comment by kthyng** [comment]
Excellent! Looks like we can work on wrapping things up now.

**Comment by kthyng** [comment]
@whedon set v1.1.5 as version

**Comment by whedon** [comment]
OK. v1.1.5 is the version.

**Comment by kthyng** [comment]
@crvernon, @evanoffPNNL Can you update the metadata for your Zenodo archive so that the title and author list exactly match your JOSS paper?

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02782/joss.02782/10.21105.joss.02782.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02782/joss.02782/10.21105.joss.02782.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@crvernon, @evanoffPNNL Your paper looks good, though please go through your references in detail and fix anything that looks off. For example, one reference has "r" (uncapitalized), and the final reference maybe should have different formatting for 2 deg C? There may be more such items. To preserve capitalization from the bib file, you can put {} around a single letter, word, or more.

**Comment by crvernon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02782/joss.02782/10.21105.joss.02782.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02782/joss.02782/10.21105.joss.02782.pdf) :page_facing_up: :point_left:

**Comment by crvernon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02782/joss.02782/10.21105.joss.02782.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02782/joss.02782/10.21105.joss.02782.pdf) :page_facing_up: :point_left:

**Comment by crvernon** [comment]
@kthyng I updated the references to be formatted correctly.  Thank you for catching that!  The person who originally linked the `hectorui` repository with Zenodo is no longer with our organization.  This keeps me from being able to edit the metadata of the Zenodo record to update the citation as you requested.  I have contacted Zenodo to see if they can terminate the existing connection so that I may activate the `hectorui` repo on my Zenodo account.  I will let you know when I hear back and have this resolved.  Thanks!

**Comment by kthyng** [comment]
@crvernon Ok paper looks good including references, and I'll wait to hear back on the Zenodo metadata. Thanks!

**Comment by crvernon** [comment]
Alright @kthyng we have the Zenodo issue worked out. The newest release will is v1.1.6 which has been minted at the following with an updated reference:

Jason Evanoff, Chris R. Vernon, Stephanie Waldhoff, Abigail Snyder, & Corinne Hartin. (2020, December 11). JGCRI/hectorui: v1.1.6 JOSS publication (Version v1.1.6). Zenodo. http://doi.org/10.5281/zenodo.4317756

Thanks for everything!

**Comment by kthyng** [comment]
@crvernon Good, though can you make the title "hectorui: A web-based interactive scenario builder and visualization application for the Hector climate model"?

**Comment by crvernon** [comment]
No problem. Just updated it. Thanks!


Jason Evanoff, Chris R. Vernon, Stephanie Waldhoff, Abigail Snyder, & Corinne Hartin. (2020, December 11). hectorui: A web-based interactive scenario builder and visualization application for the Hector climate model (Version v1.1.6). Zenodo. http://doi.org/10.5281/zenodo.4317756

**Comment by kthyng** [comment]
Ok this looks great!

**Comment by kthyng** [comment]
@whedon set v1.1.6 as version

**Comment by whedon** [comment]
OK. v1.1.6 is the version.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4317756" target="_blank">10.5281/zenodo.4317756</a> is the archive.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5194/gmd-8-939-2015 is OK
- 10.5194/bg-13-4329-2016 is OK
- 10.1371/journal.pone.0223542 is OK
- 10.5194/gmd-12-677-2019 is OK
- 10.1016/j.techfore.2006.05.026 is OK
- 10.1007/s10584-011-0149-y is OK
- 10.5547/ISSN0195-6574-EJ-VolSI2006-NoSI3-17 is OK
- 10.1007/s10584-011-0151-4 is OK
- 10.1007/s10584-011-0152-3 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1975

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1975, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1337486269706887171) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1976
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02782](https://doi.org/10.21105/joss.02782)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats to @evanoffPNNL and @crvernon on your new publication! Many thanks to reviewers @marvinjonathcn and @tscheypidi for your time and expertise. 🎉 🎉

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02782/status.svg)](https://doi.org/10.21105/joss.02782)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02782">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02782/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02782/status.svg
   :target: https://doi.org/10.21105/joss.02782
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02782/status.svg)](https://doi.org/10.21105/joss.02782)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by crvernon** [comment]
Thanks so much @kthyng !!!
