### ISSUE TITLE
[REVIEW]: SLAM Toolbox: SLAM for the dynamic world

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2783]
**Submitting author:** @stevemacenski (<a href="http://orcid.org/0000-0003-1090-7733">Steven Macenski</a>)
**Repository:** <a href="https://github.com/SteveMacenski/slam_toolbox" target ="_blank">https://github.com/SteveMacenski/slam_toolbox</a>
**Version:** 2.3.0
**Editor:** @arfon
**Reviewer:** @mosteo, @carlosjoserg
**Archive:** <a href="https://doi.org/10.5281/zenodo.4749721" target="_blank">10.5281/zenodo.4749721</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/92f7096f8cdf263c22dbcff980b785b2/status.svg)](https://joss.theoj.org/papers/92f7096f8cdf263c22dbcff980b785b2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/92f7096f8cdf263c22dbcff980b785b2"><img src="https://joss.theoj.org/papers/92f7096f8cdf263c22dbcff980b785b2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/92f7096f8cdf263c22dbcff980b785b2/status.svg)](https://joss.theoj.org/papers/92f7096f8cdf263c22dbcff980b785b2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/SteveMacenski/slam_toolbox" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mosteo & @carlosjoserg, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SteveMacenski/slam_toolbox">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@stevemacenski) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SteveMacenski/slam_toolbox">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@stevemacenski) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mosteo, @carlosjoserg it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2783 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by arfon** [comment]
@mosteo, @carlosjoserg - This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/2783  so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be _completed_ within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02783/joss.02783/10.21105.joss.02783.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02783/joss.02783/10.21105.joss.02783.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @carlosjoserg, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @mosteo, please update us on how your review is going.

**Comment by SteveMacenski** [comment]
Hi, just wanted to touch base on this - any progress?

**Comment by arfon** [comment]
:wave: @mosteo, @carlosjoserg - just checking in here to see how you're both getting on with your reviews?

**Comment by carlosjoserg** [comment]
Hi all, appologies for the delay, also got other reviews from IEEE that took me some time too... I hope within a week to finish this one. Best,

**Comment by mosteo** [comment]
Hi @arfon, for some reason I was not getting notifications from here. I'm going to review my settings to fix this for the future.

**Comment by mosteo** [comment]
Opened a PR with proofreading fixes: SteveMacenski/slam_toolbox#317

**Comment by mosteo** [comment]
Installation verified by installing the `ros-foxy-slam-toolbox` package.

**Comment by arfon** [comment]
:wave: @mosteo, @carlosjoserg - happy new year. Just checking in on your reviews here? It looks like @SteveMacenski responded to the questions you asked in https://github.com/SteveMacenski/slam_toolbox/issues/318 and https://github.com/SteveMacenski/slam_toolbox/issues/320 ?

**Comment by mosteo** [comment]
I'm back on track, sorry for the delay. @arfon, in regard to the verification of the functionality/performance, this is intended to be verified by the reviewers? Or would evidence of usage by third parties be enough?

**Comment by SteveMacenski** [comment]
A few examples from people that aren't me and I've had no contact with (googled and found for reference) if that helps
- https://www.youtube.com/watch?v=ftfMsA-UykQ / https://www.notion.so/Tutorial-SLAM-toolbox-aac021ec21d24f898ce230c19def3b7b
- https://www.youtube.com/watch?v=s16269kol5M
- https://www.youtube.com/watch?v=Cgcl3LcFnEs
- http://www.robotandchisel.com/2020/08/19/slam-in-ros2/ (though note I do know Mike but I didn't ask/inform him on this)
- https://msadowski.github.io/hands-on-with-slam_toolbox/
- https://blog.pal-robotics.com/aris-wiki-ros-tutorials-on-slam/

**Comment by arfon** [comment]
> I'm back on track, sorry for the delay. @arfon, in regard to the verification of the functionality/performance, this is intended to be verified by the reviewers? Or would evidence of usage by third parties be enough?

We would definitely prefer both reviewers to verify the functionality claims (performance is sometimes more challenging for folks).

**Comment by mosteo** [comment]
Understood. Then, I'm going to throw a ball to @SteveMacenski : I don't currently have access to my labs robots due to covid. Also, I'm exclusively using ROS2 these days. This brings me back to the issue of beginner tutorials. If I go to https://navigation.ros.org/tutorials/docs/navigation2_with_slam.html, I read:

> we will use the turtlebot3. If you have another robot, replace with suitable instructions

I would really like to see there, instead of "replace with suitable", something like "use this previous tutorial to set up a simulated robot" or similar. Related to my earlier comment that people not current with ROS2 may hit a bump there if interested in a "quick" test.

**Comment by SteveMacenski** [comment]
Ok, makes sense - do you have a ROS2 bag file you can run it over? I'd be happy to share with you a ROS(1) bag file I have for the purposes of review and a set of instructions to reproduce, but unfortunately I don't have any ROS2 bag files (as you're aware until exceptionally recently, ROS2 bag has been very flaky). ROS 1 would be easier to see everything since that's what this article was written on but lets see what we can work out in ROS2. 

---

Another option is as you've found in the tutorial, if you're OK installing Nav2 to run our canonical [getting started demo](https://navigation.ros.org/getting_started/index.html) then one of the parameters I have conveniently provided is [`slam`](https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/bringup/launch/tb3_simulation_launch.py#L35). So 

```
ros2 launch nav2_bringup tb3_simulation_launch.py slam:=true
```

will get you what you need. It will launch a TB3 in a sandbox world that you can initialize the pose with the rviz "Pose2D" tool and then request navigation goals with "goal pose" tool. You'll see the map update as you move.The SLAM specific tutorial is meant to be more abstract and separate out the navigation from the simulation from the SLAM since that tutorial is written with "bring your own robot" in mind - in which case using our one-stop-shop launch file `tb3_simulation_launch.py` isn't appropriate. 

>  we will use the turtlebot3. If you have another robot, replace with suitable instructions

Is to mean your own robot state publisher, hardware / simulation interface, and any other robot-specific needs. It's hard to fully articulate the broad range of things that a particular company / robot might require, so we keep it abstract. It could be as little as the robot state publisher with URDF and drivers, but frequently its alot more.

**Comment by SteveMacenski** [comment]
Any update? Anyhow else I can help?

**Comment by mosteo** [comment]
I'm on it, but I can't give you a definite date ATM.

**Comment by mosteo** [comment]
I am finished, sorry for the delay. A couple of observations:

In the SLAM tutorial at https://navigation.ros.org/tutorials/docs/navigation2_with_slam.html, the command at step 1:

` ros2 launch nav2_bringup nav2_navigation_launch.py` should be 
`ros2 launch nav2_bringup navigation_launch.py`

At step 4 with the shortcut, the last `True` is given in lowercase and should be in uppercase: `ros2 launch nav2_bringup tb3_simulation_launch.py slam:=true`.

I could not load the plugin for RViz mentioned in the readme in RViz2. Is this ROS1 only? Is it not bundled with Foxy packages? Am I missing something? If not the latter, this should be clarified in the readme.

**Comment by mosteo** [comment]
> They are bundled and should work, can you explain what you mean by didn't load?

Yes, the navigation panel does show. What I'm missing there is the options about map manipulation mentioned in the README, i.e. the panel shown at the end of section https://github.com/SteveMacenski/slam_toolbox#rviz-plugin. I had tried the `Add Panels -> Add New Panel`, where the same Nav2 panel exists, but nothing else about slam.

Now, I've found that there's a config file `foxy/share/slam_toolbox/config/slam_toolbox_default.rviz`, but that says (in an error dialog):

![image](https://user-images.githubusercontent.com/264377/110607248-4d2a7f00-818b-11eb-9038-245d592b3652.png)

Afterwards there are other errors in the panels and rviz quickly dies.

**Comment by SteveMacenski** [comment]
The map manipulation tools are only available in ROS1 due to the incomplete port of interactive markers in ROS2 (this document is talking about ROS1) You can enter interactive mode and see the interactive markers but unfortunately the "dragging" of them to reposition them for manipulation is still unavailable. 

That's not an excuse for the rviz config issue, I've removed the slam toolbox rviz config, all it was was the default config file with the SLAM Toolbox plugin pre-loaded. However, rviz2 has renamed a bunch of the namespaces in its port after this was ported. I removed the file to remove this confusion (and any further issues with rviz changes impacting the repo since really it was just preloading a simple panel).

**Comment by mosteo** [comment]
Thanks, @SteveMacenski. I'm not that worried about some things being only available for ROS1 (I known the migration to ROS2 is not being trivial), but about the confusion a newcomer may experience.

**Comment by SteveMacenski** [comment]
Totally fair - I removed that config file from `ros2` branch and very shortly `foxy` too. Let me know if there's anything more I can do to help!

**Comment by SteveMacenski** [comment]
@mosteo anything else that I can resolve / clarify / assist with to get your check on "Example usage" (I believe the last item on your list to complete the review)?

**Comment by mosteo** [comment]
I'm sorry, I thought I had checked it after you provided the `slam:=True` bit.

**Comment by SteveMacenski** [comment]
@carlosjoserg anything I can do to help you in your review?

**Comment by carlosjoserg** [comment]
@arfon my list is fully checked.

Thanks, it's been an interesting review.

**Comment by SteveMacenski** [comment]
@arfon thanks! The newest releases contain all of the change requested and patched as part of the review. I just verified by looking back at all of the review comments/threads and cross referencing change requested with commits in those releases:
- ROS2 2.4.0 https://github.com/SteveMacenski/slam_toolbox/releases/tag/2.4.0
- ROS(1) 1.5.5 https://github.com/SteveMacenski/slam_toolbox/releases/tag/1.5.5

Zenodo archive link (named with the same name and with both authors): https://doi.org/10.5281/zenodo.4749721

10.5281/zenodo.4749721

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4749721" target="_blank">10.5281/zenodo.4749721</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2300

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2300, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by arfon** [comment]
@SteveMacenski - a couple of final things:

- Did you check the DOI suggestions from Whedon above? If any of them are correct, please update your BibTeX to include them.
- I made a small change to your paper in https://github.com/SteveMacenski/slam_toolbox/pull/392 to make it read a little more clearly (I think).

**Comment by SteveMacenski** [comment]
Hi,

- [Googling the DOIs](https://www.google.com/search?channel=fs&client=ubuntu&q=10.1109%2Firos45743.2020.9341207) all gave me the papers that are also matching the titles. I'm not exactly sure what the issue is there, but they seem to all be valid from my checking
- Merged

**Comment by arfon** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1177/1729881420910530 is OK
- 10.1016/j.procs.2015.12.336 is OK
- 10.1109/IROS.2010.5649043 is OK
- 10.1177/0278364906065387 is OK
- 10.1109/ROBOT.2006.1641929 is OK

MISSING DOIs

- 10.1109/iros45743.2020.9341207 may be a valid DOI for title: The Marathon 2: A Navigation System
- 10.36288/roscon2019-900903 may be a valid DOI for title: On Use of SLAM Toolbox
- 10.1109/icra.2016.7487258 may be a valid DOI for title: Real-Time Loop Closure in 2D LIDAR SLAM
- 10.1109/tro.2006.889486 may be a valid DOI for title: Improved Techniques for Grid Mapping With Rao-Blackwellized Particle Filters
- 10.1109/ssrr.2011.6106777 may be a valid DOI for title: A flexible and scalable SLAM system with full 3D motion estimation

INVALID DOIs

- None
```

**Comment by arfon** [comment]
> Googling the DOIs all gave me the papers that are also matching the titles. I'm not exactly sure what the issue is there, but they seem to all be valid from my checking

Great! Then please update your `paper.bib` to include them. For example, for `The Marathon 2: A Navigation System`, if the suggested DOI from Whedon is correct then you need to add `doi=10.1109/iros45743.2020.9341207` to [this part](https://github.com/SteveMacenski/slam_toolbox/blob/joss/paper.bib#L48-L54) of your BibTeX file (we need you to do this for all of the potential missing DOIs please).

**Comment by SteveMacenski** [comment]
https://github.com/SteveMacenski/slam_toolbox/commit/7a333e5321030c8d3187c82d8fc0563fe400ae6b Done!

**Comment by arfon** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1177/1729881420910530 is OK
- 10.1016/j.procs.2015.12.336 is OK
- 10.1109/IROS.2010.5649043 is OK
- 10.1109/iros45743.2020.9341207 is OK
- 10.36288/roscon2019-900903 is OK
- 10.1109/icra.2016.7487258 is OK
- 10.1177/0278364906065387 is OK
- 10.1109/ROBOT.2006.1641929 is OK
- 10.1109/tro.2006.889486 is OK
- 10.1109/ssrr.2011.6106777 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1177/1729881420910530 is OK
- 10.1016/j.procs.2015.12.336 is OK
- 10.1109/IROS.2010.5649043 is OK
- 10.1109/iros45743.2020.9341207 is OK
- 10.36288/roscon2019-900903 is OK
- 10.1109/icra.2016.7487258 is OK
- 10.1177/0278364906065387 is OK
- 10.1109/ROBOT.2006.1641929 is OK
- 10.1109/tro.2006.889486 is OK
- 10.1109/ssrr.2011.6106777 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2306

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2306, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by arfon** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1392920888581009408) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2307
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02783](https://doi.org/10.21105/joss.02783)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@mosteo, @carlosjoserg - many thanks for your reviews here! JOSS relies upon volunteer effort from folks like you and we simply wouldn't be able to do this without you! ✨ 

@SteveMacenski - your paper is now accepted and published in JOSS ⚡:rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02783/status.svg)](https://doi.org/10.21105/joss.02783)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02783">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02783/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02783/status.svg
   :target: https://doi.org/10.21105/joss.02783
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02783/status.svg)](https://doi.org/10.21105/joss.02783)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by SteveMacenski** [comment]
Amazing, thank you! I've added myself a bit ago as a reviewer for ROS/robotics papers, feel free to call on me if you have something in robotics/ROS!
