### ISSUE TITLE
[REVIEW]: kalepy: a python package for kernel density estimation and sampling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2784]
**Submitting author:** @lzkelley (<a href="http://orcid.org/0000-0002-6625-6450">Luke Zoltan Kelley</a>)
**Repository:** <a href="https://github.com/lzkelley/kalepy" target ="_blank">https://github.com/lzkelley/kalepy</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @williamjameshandley, @kexinrong
**Archive:** <a href="https://doi.org/10.5281/zenodo.4456130" target="_blank">10.5281/zenodo.4456130</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e381b6d56a759d6f365977b0254fdbae/status.svg)](https://joss.theoj.org/papers/e381b6d56a759d6f365977b0254fdbae)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e381b6d56a759d6f365977b0254fdbae"><img src="https://joss.theoj.org/papers/e381b6d56a759d6f365977b0254fdbae/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e381b6d56a759d6f365977b0254fdbae/status.svg)](https://joss.theoj.org/papers/e381b6d56a759d6f365977b0254fdbae)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/lzkelley/kalepy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@williamjameshandley & @kexinrong, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lzkelley/kalepy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@lzkelley) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lzkelley/kalepy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@lzkelley) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @williamjameshandley, @kexinrong it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02784/joss.02784/10.21105.joss.02784.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02784/joss.02784/10.21105.joss.02784.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/1114019 is OK
- 10.1214/aoms/1177704472 is OK
- 10.1214/aoms/1177728190 is OK
- 10.1093/biomet/66.3.605 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/zenodo.592845 is OK
- 10.5281/zenodo.2392268 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.53 is OK
- 10.1093/mnras/staa2361 is OK
- 10.3847/2041-8213/abb1bf is OK
- 10.21105/joss.00024 is OK

MISSING DOIs

- 10.1093/imamat/20.3.335 may be a valid DOI for title: A review of some non-parametric methods of density estimation
- 10.1093/biomet/65.1.1 may be a valid DOI for title: Choosing the window width when estimating a density
- 10.1109/mcse.2007.55 may be a valid DOI for title: Matplotlib: A 2D graphics environment

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@williamjameshandley, @kexinrong - this is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/2784 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be _completed_ within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by whedon** [comment]
:wave: @kexinrong, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @williamjameshandley, please update us on how your review is going.

**Comment by kexinrong** [comment]
@lzkelley Nice package and visualizations! I will collect feedback on the repository here as I go through the review:

**Documentation**
- [ ] Could you compile the package documentation and add a link in the README? 
- [ ] The README has a few incomplete sections. 
- [ ] Since resampling is one of the main use cases, I will suggest exposing more parameters in the example usage. For example, for resample(), how do you specific size and weights? For KDE, what are the options for bandwidth. 
- [ ] In the example "Plotting Smooth Distributions", the comment about 'points' is slightly confusing. Can you specify the granularity at which the PDF is evaluated? 
- [ ] Missing guidelines for contribution and support.

**Comment by lzkelley** [comment]
Thanks for the comments @kexinrong, these are all really helpful suggestions.  Could you clarify on your first point: "compile the package documentation" --- do you mean something in the 'readthedocs' style?

**Comment by kexinrong** [comment]
@lzkelley Yes that's what I meant. I personally find that it is helpful to have readthedoc style API documentation, compared to inline documentation.

**Comment by arfon** [comment]
FYI I just sent a reminder to @williamjameshandley.

**Comment by williamjameshandley** [comment]
This is a very high-quality JOSS submission, with the code in an already very polished state, and a paper that is appropriate in content and length. The testing and CI are good, the installation smooth (both from PyPi and from source), and the examples in the README.md all work and clearly demonstrate the utility of the code. This is a package that I will likely incorporate into  [one of my own](https://github.com/williamjameshandley/anesthetic) as an optional dependency alternative to scipy KDE. Please could you raise kalepy integration as an issue on that repo to remind me.

I agree with @kexinrong that given all the work that has been put into the excellent numpy docstrings this should be continuously integrated readthedocs host using e.g. sphinx.

The paper itself has a couple of minor typos (Guassian -> Gaussian, Fig.Figure 1 -> Figure 1).

I think there are still a few missing README sections at the bottom, that need to be filled out. To fulfil community guidelines, I recommend going to the relevant [insights tab](https://github.com/lzkelley/kalepy/community) and following the examples there.

The only thing I think is missing from this is a discussion/comparison with what I would consider the present state-of-the-art in kernel density estimation in astronomy [GetDist](https://arxiv.org/pdf/1910.13970.pdf). kalepy includes resampling (which if possible in GetDist is not obvious to me how to do), but GetDist has a more sophisticated boundary correction system.

@arfon, I can't tick off my sections (I've been doing them locally for now). Could you re-send the invitation?

**Comment by arfon** [comment]
@whedon re-invite @williamjameshandley as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@williamjameshandley please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
> @arfon, I can't tick off my sections (I've been doing them locally for now). Could you re-send the invitation?

@williamjameshandley - you should be good to go once you've accepted the invite at the link above.

**Comment by lzkelley** [comment]
Dear @kexinrong and @williamjameshandley, thank you both so much for your helpful comments!  I have just pushed a new version 'v0.5' to master which includes the recommended updates.  The changes are noted in the [CHANGES.md file](https://github.com/lzkelley/kalepy/blob/master/CHANGES.md#v05---20201230), and also here:

- [kalepy.readthedocs.io](kalepy.readthedocs.io) now includes fully compiled documentation from docstrings, in addition to usage instructions and numerous examples.  These are primarily included on the [API](https://kalepy.readthedocs.io/en/latest/api.html) page, which now also includes examples on resampling (and its features) and plotting.
- The API to the plotting submodule has been completely restructured for a far-simpler API.  The plotting functionality is also highlighted more prominently (and clearly) in the [readthedocs plotting examples](https://kalepy.readthedocs.io/en/latest/api.html#plotting-distributions).
- I have fixed the typos in the JOSS paper, and discussed the `GetDist` package in particular.  I believe the most important difference is that `GetDist` is a **plotting package** that uses KDEs (very nicely), while `kalepy` is a **KDE package** that includes plotting routines.  In addition to the added functionality of resampling, I wasn't able to find any user-interface to the KDE functionality in `GetDist` *per se*, outside of plotting routines.
- In both the README and readthedocs index, I have included information about both contributions and attributions.  For the time being, I have not added any codes of conduct, bug-report templates, etc as I don't expect these to be necessary for the scale of community contributions that I expect on this relatively-small package.

**Comment by arfon** [comment]
:zap: thanks for the update @lzkelley.

@kexinrong and @williamjameshandley happy new year 🎉! When you are able to, please check in on the latest changes made by @lzkelley and update your checklists as appropriate.

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02784/joss.02784/10.21105.joss.02784.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02784/joss.02784/10.21105.joss.02784.pdf) :page_facing_up: :point_left:

**Comment by williamjameshandley** [comment]
This is very nearly there in my book. At the moment, the readthedocs website doesn't seem to be extracting the docstrings. For an example of what I mean, have a look [here](https://anesthetic.readthedocs.io/en/latest/anesthetic.html), and how this is automated [here](https://github.com/williamjameshandley/anesthetic). There still aren't any clear community guidelines for contributions (other than a small subsection). I recommend following the advice [here](https://github.com/lzkelley/kalepy/community).

**Comment by lzkelley** [comment]
Apologies @williamjameshandley, there was a readthedocs build error that I didn't notice.  The docs seem to be building properly now.  The [full docstring documentation is here](https://kalepy.readthedocs.io/en/latest/kalepy.html).  I have expanded the contribution information in the [README](https://github.com/lzkelley/kalepy#development--contributions), the [DEVELOPMENT.rst](https://github.com/lzkelley/kalepy/blob/master/DEVELOPMENT.rst) file, and in the [readthedocs index](https://kalepy.readthedocs.io/en/latest/#development-contributions).

**Comment by kexinrong** [comment]
Hi Luke, thanks for the changes. The updated documentation and guideline look good to me. 

For the JOSS paper, I have one suggestion regarding discussions on related packages: it seems that `scipy.stats.gaussian_kde` does have a build-in [resample](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.resample.html) function. Could you update the writing to reflect this?

**Comment by williamjameshandley** [comment]
Subject to the change suggested by @kexinrong above I'm happy to approve this for publication now

**Comment by lzkelley** [comment]
@kexinrong thanks for pointing that out!  I clarified (and cleaned up) the discussion about other packages.  New version is pushed to master.

@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

@lzkelley - messages to Whedon have to be on the first line of a comment ☝️

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02784/joss.02784/10.21105.joss.02784.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02784/joss.02784/10.21105.joss.02784.pdf) :page_facing_up: :point_left:

**Comment by lzkelley** [comment]
> @whedon generate pdf
> 
> @lzkelley - messages to Whedon have to be on the first line of a comment ☝️

Woops, thanks @arfon !

**Comment by arfon** [comment]
@williamjameshandley, @kexinrong - thanks for your excellent reviews here and to @lzkelley for the responsive feedback. I think we're ready to move forward to accepting this submission.

@lzkelley - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

Finally, please give the paper a final proof read (I will do this too) to look for any last issues there.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02784/joss.02784/10.21105.joss.02784.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02784/joss.02784/10.21105.joss.02784.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@lzkelley - I made a collection of small fixes to the paper in https://github.com/lzkelley/kalepy/pull/1

**Comment by lzkelley** [comment]
Thanks for the corrections @arfon, I've created the release v1.0.0 and associated [zenodo DOI: 10.5281/zenodo.4456130
](https://zenodo.org/record/4456130).  I fixed another typo, and couple of grammatical issues in the draft.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4456130 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4456130" target="_blank">10.5281/zenodo.4456130</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2040

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2040, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/1114019 is OK
- 10.1093/imamat/20.3.335 is OK
- 10.1214/aoms/1177704472 is OK
- 10.1214/aoms/1177728190 is OK
- 10.1093/biomet/66.3.605 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.5281/zenodo.592845 is OK
- 10.5281/zenodo.2392268 is OK
- 10.1109/mcse.2007.55 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.53 is OK
- 10.1093/mnras/staa2361 is OK
- 10.3847/2041-8213/abb1bf is OK
- 10.21105/joss.00024 is OK

MISSING DOIs

- 10.1093/biomet/65.1.1 may be a valid DOI for title: Choosing the window width when estimating a density

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1352535545654738946) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2041
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02784](https://doi.org/10.21105/joss.02784)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@williamjameshandley, @kexinrong - many thanks for your reviews here. JOSS relies upon the volunteer efforts of people like you - we simply wouldn't be able to do this without you! ✨ 

@lzkelley - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02784/status.svg)](https://doi.org/10.21105/joss.02784)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02784">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02784/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02784/status.svg
   :target: https://doi.org/10.21105/joss.02784
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02784/status.svg)](https://doi.org/10.21105/joss.02784)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by lzkelley** [comment]
@williamjameshandley @kexinrong @arfon thank you all for all of your time and extremely useful help in getting this together!
