### ISSUE TITLE
[PRE REVIEW]: Atmospheric Rossby waves identification and tracking with a raytracing numerical model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2786]
**Submitting author:** @salvatirehbein (<a href="http://orcid.org/0000-0002-8714-7931">Amanda Rehbein</a>)
**Repository:** <a href="https://github.com/salvatirehbein/raytracing" target ="_blank">https://github.com/salvatirehbein/raytracing</a>
**Version:** 0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @salvatirehbein. **Currently, there isn't an JOSS editor assigned** to your paper.

@salvatirehbein if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.02 s (758.9 files/s, 92250.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         4            177              0            745
R                               10             94            344            551
TeX                              1              0              0            120
Rmd                              1             26             46             52
YAML                             2              6              0             27
-------------------------------------------------------------------------------
SUM:                            18            303            390           1495
-------------------------------------------------------------------------------


Statistical information for the repository 'f6b0a7da472f37d06d6e5cbd' was
gathered on 2020/10/27.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2786 with the following error: 

 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.318 ....br}{\nolinkurl{amanda.rehbein@usp.br}}}}

Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.32614/RJ-2018-009 is OK

MISSING DOIs

- 10.1175/1520-0469(1995)052<3661:rwpatp>2.0.co;2 may be a valid DOI for title: Rossby wave propagation and teleconnection patterns in the austral winter
- 10.1002/qj.49712354007 may be a valid DOI for title: Stationary Rossby-wave propagation in a baroclinic atmosphere
- 10.1175/1520-0469(1993)050<1661:rwpoar>2.0.co;2 may be a valid DOI for title: Rossby wave propagation on a realistic longitudinally varying flow
- 10.1175/1520-0469(1981)038<1179:tslroa>2.0.co;2 may be a valid DOI for title: The steady linear response of a spherical atmosphere to thermal and orographic forcing
- 10.1175/1520-0493(1992)120<1169:gtitms>2.0.co;2 may be a valid DOI for title: Global teleconnections in the 250-mb streamfunction field during the Northern Hemisphere winter
- 10.1016/0377-0265(83)90013-1 may be a valid DOI for title: Rossby wave propagation in a barotropic atmosphere

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@salvatirehbein - many thanks for your submission to JOSS. This submission will need to go through an additional review by the JOSS editorial team due to its very small size - this will likely take a week or so.

**Comment by arfon** [comment]
:wave: @salvatirehbein - thanks again for your submission to JOSS. After consulting with the JOSS editorial team, your submission has been deemed out of scope for JOSS due to it's [limited size and scope](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by salvatirehbein** [comment]
Dear @arfon

Thank you so much for your efforts in reviewing this paper.

I was wondering to tell you that the tool we created and described in this paper started being made in February of this year. Many, many efforts were made for making it fast, easy, and simple for studying and understanding our climate system. Therefore, this tool is very important for our group of studies (www.grec.iag.usp.br) and is currently in use in two papers that will be submitted by December.  Therefore, it is very important to make this tool available and citable. Besides that, the lines of code of our R package are 989, which seems suitable. So, I was wondering if there is any chance of reconsideration for this paper?

**Comment by arfon** [comment]
Hi @salvatirehbein - I'm afraid our decision on scope is final here but there are some alternatives for citing the package which we have written about here: https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages
