### ISSUE TITLE
[PRE REVIEW]: secuTrialR: Seamless interaction with clinical trial databases in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2787]
**Submitting author:** @PatrickRWright (<a href="http://orcid.org/0000-0002-1153-0846">Patrick R. Wright</a>)
**Repository:** <a href="https://github.com/SwissClinicalTrialOrganisation/secuTrialR" target ="_blank">https://github.com/SwissClinicalTrialOrganisation/secuTrialR</a>
**Version:** 1.0.6
**Editor:** @csoneson
**Reviewers:** @pacoramon, @sachsmc
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @PatrickRWright. **Currently, there isn't an JOSS editor assigned** to your paper.

@PatrickRWright if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.15 s (755.2 files/s, 120807.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            33           1698            405           6655
R                               57            633           1671           3704
Markdown                         9            213              0            719
CSS                              3             99             48            428
JavaScript                       3             64             32            256
YAML                             5             54              8            201
Rmd                              2            284            747            199
TeX                              1             11              0             95
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                           114           3056           2912          12268
-------------------------------------------------------------------------------


Statistical information for the repository 'ac4efdf28ec3ae1b798b6dec' was
gathered on 2020/10/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Patrick R. Wright                1           159              5           45.30
aghaynes                         1           198              0           54.70

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Patrick R. Wright           159          100.0          0.0               10.06
aghaynes                    193           97.5          0.0                8.29
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9781107256644 is OK
- 10.1186/1745-6215-11-79 is OK
- 10.1038/d41586-020-00758-2 is OK
- 10.21105/joss.01686 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02787/joss.02787/10.21105.joss.02787.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02787/joss.02787/10.21105.joss.02787.pdf) :page_facing_up: :point_left:

**Comment by PatrickRWright** [comment]
Suggestions for reviewers:
masalmon, Tgerke, acolum, pacoramon, Jminnier, sachsmc, rrrlw

Really anyone in [the list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) which a background in R and medicine/health/epidemiology.

**Comment by PatrickRWright** [comment]
Hey, @aghaynes and @markomi this is the thread for the secuTrialR submission to JOSS.

**Comment by arfon** [comment]
@whedon invite @csoneson as editor

:wave: @csoneson - would you be able to handle this submission for JOSS?

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@whedon add @csoneson as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @PatrickRWright - I will handle your submission, and start by inviting suitable reviewers. In the meanwhile, could you please add a 'Statement of Need' section to your paper (see e.g. [here](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain))? Also, during a quick read-through I noticed that there was one place in the manuscript where `CDMS` was misspelled as `CMDS`.

**Comment by PatrickRWright** [comment]
Hi @csoneson - Thank you, its appreciated. I have added the 'Statement of Need' and corrected the typo you pointed out.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02787/joss.02787/10.21105.joss.02787.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02787/joss.02787/10.21105.joss.02787.pdf) :page_facing_up: :point_left:

**Comment by pacoramon** [comment]
Dear @csoneson, I would be interested although being my first time reviewing for JOSS (and in this format), I am concerned I will need a bit of help to manage. 
Would that be 'ok'?  Could you guide me to any documentation or guideline from JOSS I have to be aware off?

**Comment by csoneson** [comment]
Thank you @pacoramon - that's not a problem at all. JOSS guidelines for reviewers are available [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). 

Briefly, the process is as follows: I will assign you as a reviewer in this thread, but the 'actual' review will start only once we have one additional reviewer. At that time, I will open the REVIEW GitHub issue, in which you will find a personal checklist with the aspects that we ask our reviewers to evaluate (the checklist is also available in the documentation linked above). You check off the items that you are satisfied with, and for the others, provide comments to the authors either in the REVIEW issue itself, or by opening separate issues in the software repository itself. If you have questions at any time, feel free to ping me.

**Comment by pacoramon** [comment]
Thank you @csoneson for your kind explanation. Count me in, then. I will review the JOSS guidelines while another reviewer is enlisted. 
Best!

**Comment by csoneson** [comment]
@whedon assign @pacoramon as reviewer

**Comment by whedon** [comment]
OK, @pacoramon is now a reviewer

**Comment by jminnier** [comment]
Apologies, I'm unable to review at this time since I'm preparing to go on leave pretty soon and have my hands full until then. Good luck!

**Comment by csoneson** [comment]
@jminnier no worries, thanks for letting us know!

**Comment by PatrickRWright** [comment]
Thank you @pacoramon

**Comment by csoneson** [comment]
👋 @tgerke, @sachsmc - would one of you be willing to review this submission for JOSS? 

> secuTrialR: Seamless interaction with clinical trial databases in R

**Comment by sachsmc** [comment]
@csoneson Sure, I'm happy to review it.

**Comment by csoneson** [comment]
@sachsmc excellent, thanks!

**Comment by csoneson** [comment]
@whedon add @sachsmc as reviewer

**Comment by whedon** [comment]
OK, @sachsmc is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2816.
