### ISSUE TITLE
[PRE REVIEW]: Pyinterpolate: Spatial Interpolation in Python for point measurements and aggregated datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2788]
**Submitting author:** @szymon-datalions (<a href="http://orcid.org/0000-0003-3525-2104">Szymon Moliński</a>)
**Repository:** <a href="https://github.com/szymon-datalions/pyinterpolate" target ="_blank">https://github.com/szymon-datalions/pyinterpolate</a>
**Version:** v0.2.0
**Editor:** @hugoledoux
**Reviewers:** @chrisbrunsdon
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @szymon-datalions. **Currently, there isn't an JOSS editor assigned** to your paper.

@szymon-datalions if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.23 s (421.7 files/s, 124014.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       9           2289           2314           8440
HTML                            19           1321              0           4146
Python                          49           1205           1166           2433
CSS                              4            328             50           1261
Jupyter Notebook                 6              0           2921            420
Markdown                         5            117              0            219
reStructuredText                 2             32             33             34
DOS Batch                        1              8              1             26
YAML                             2              5             10             23
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            98           5309           6502          17011
-------------------------------------------------------------------------------


Statistical information for the repository '097a509f94f858cb0374e910' was
gathered on 2020/10/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Szymon                           2             2              1            0.01
TobiaszWojnar                    1            14             20            0.10
szymon-datalions                93         26250           8404           99.89

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
TobiaszWojnar                13           92.9          1.3                0.00
szymon-datalions          17834           67.9          0.7               15.61
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2788 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02788/joss.02788/10.21105.joss.02788.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02788/joss.02788/10.21105.joss.02788.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @hugoledoux as editor

:wave: @hugoledoux - would you feel comfortable taking on another submission right now?

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by hugoledoux** [comment]
sure!

**Comment by arfon** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by hugoledoux** [comment]
@whedon assign @kenohori as reviewer

**Comment by whedon** [comment]
OK, @kenohori is now a reviewer

**Comment by hugoledoux** [comment]
@whedon assign @chrisbrunsdon as reviewer

**Comment by whedon** [comment]
OK, @chrisbrunsdon is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2869.
