### ISSUE TITLE
[PRE REVIEW]: PyAutoLens: Open-Source Strong Gravitational Lensing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2789]
**Submitting author:** @Jammy2211 (<a href="http://orcid.org/0000-0002-8987-7401">James Nightingale</a>)
**Repository:** <a href="https://github.com/Jammy2211/PyAutoLens" target ="_blank">https://github.com/Jammy2211/PyAutoLens</a>
**Version:** 1.7.8
**Editor:** @xuanxu
**Reviewers:** @aureliocarnero, @zonca
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Jammy2211. **Currently, there isn't an JOSS editor assigned** to your paper.

@Jammy2211 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.02 s (349.6 files/s, 62193.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         239           8079           7478          22710
JSON                            29              0              0           8527
Jupyter Notebook                30              0           4896           6425
TeX                              3             25              0           1075
reStructuredText                25            729            875            936
INI                             21            120              0            853
Markdown                         4             52              0            264
DOS Batch                        1              8              1             26
Bourne Shell                     1             14              1             25
make                             1              4              7              9
YAML                             1              4              2              8
-------------------------------------------------------------------------------
SUM:                           355           9035          13260          40858
-------------------------------------------------------------------------------


Statistical information for the repository '4ffdf1ee10792ce326b99c55' was
gathered on 2020/10/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
James Nightingale               75          9641           8457            0.10
Jammy2211                     9590       5397504        4320697           51.57
Nan Li                           9           279              0            0.00
Richard                       1045         46333          40057            0.46
Richard Hayes                40235       4060350        3995003           42.75
amyetherington                  19         22046          15834            0.20
ashkelly                         2            23             54            0.00
jammy2211                     1197        453824         475011            4.93

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jammy2211                 37411            0.7          6.3                9.02
Richard Hayes               813            0.0         12.0                3.81
amyetherington               77            0.3         17.5               20.78
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02789/joss.02789/10.21105.joss.02789.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02789/joss.02789/10.21105.joss.02789.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @Jammy2211 - is this submission associated with a paper in a AAS publication?

**Comment by Jammy2211** [comment]
It is not.

**Comment by arfon** [comment]
@whedon invite @xuanxu as editor

:wave: @xuanxu - could you edit this submission for us?

**Comment by whedon** [comment]
@xuanxu has been invited to edit this submission.

**Comment by xuanxu** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
@Jammy2211 A quick comment before I look for reviewers: I got some errors cloning the repo, because the .git directory is big (~260Mb), so I had to install the [LFS extension](https://git-lfs.github.com/) for git to be able to work with it. I'd recommend adding a note in the _Cloning/forking_ section of the Installation guide, and/or trying to reduce the size of the repo objects in the git history if possible.

**Comment by Jammy2211** [comment]
Thanks. I literally added the LFS stuff last night, having not used it before. Sounds like it is cumbersome so I will remove it entirely and switch the files to some sort of a URL download or separate GIt repo :).

**Comment by Jammy2211** [comment]
We're also aware of an issue where the imports in the `transdimensional` and `slam` runners in the autolens_workspace will give import errors, which require setting your PYTHONPATH to fix.

We did a big refactor before submitting (probably not the best idea...) changing how we handle paths / configs / output and are still having a few teething issues, but the goal is to make it so users don't have to set environment variables to run every!

**Comment by xuanxu** [comment]
@HeloiseS / @aureliocarnero: would you be willing to review this paper? I think your knowledge of Astrophysics and Python makes both of you a great fit for this submission.

**Comment by aureliocarnero** [comment]
Dear @xuanxu I'm willing to review it, so count on me. 
Thank you!
Aurelio

**Comment by xuanxu** [comment]
@zonca would you be willing to review this paper? I think your knowledge of Cosmology and Python makes you a great fit for this submission.

**Comment by zonca** [comment]
yes, I can

**Comment by xuanxu** [comment]
@whedon add aureliocarnero as reviewer

**Comment by whedon** [comment]
OK, aureliocarnero is now a reviewer

**Comment by xuanxu** [comment]
@whedon add @zonca as reviewer

**Comment by whedon** [comment]
OK, @zonca is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2825.

**Comment by xuanxu** [comment]
@aureliocarnero, @zonca thank you both. Please head over to #2825 where the review will take place.
