### ISSUE TITLE
[REVIEW]: s4rdm3x: A Tool Suite to Explore Code to Architecture Mapping Techniques

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2791]
**Submitting author:** @tobias-dv-lnu (<a href="http://orcid.org/0000-0003-1154-5308">Tobias Olsson</a>)
**Repository:** <a href="https://github.com/tobias-dv-lnu/s4rdm3x" target ="_blank">https://github.com/tobias-dv-lnu/s4rdm3x</a>
**Version:** v1.3
**Editor:** @gkthiruvathukal
**Reviewer:** @kinow, @xirdneh
**Archive:** <a href="https://doi.org/10.5281/zenodo.4475664" target="_blank">10.5281/zenodo.4475664</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f4301adc3e9121a10354c355d91b5c1f/status.svg)](https://joss.theoj.org/papers/f4301adc3e9121a10354c355d91b5c1f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f4301adc3e9121a10354c355d91b5c1f"><img src="https://joss.theoj.org/papers/f4301adc3e9121a10354c355d91b5c1f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f4301adc3e9121a10354c355d91b5c1f/status.svg)](https://joss.theoj.org/papers/f4301adc3e9121a10354c355d91b5c1f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/tobias-dv-lnu/s4rdm3x/tree/master/JOSS-paper" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kinow & @xirdneh, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @gkthiruvathukal know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/tobias-dv-lnu/s4rdm3x/tree/master/JOSS-paper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tobias-dv-lnu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/tobias-dv-lnu/s4rdm3x/tree/master/JOSS-paper">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@tobias-dv-lnu) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kinow, @xirdneh it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2791 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - 241d63aa7177374e42894fdd (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:66:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:53:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kinow** [comment]
@gkthiruvathukal hi, do you have karma to re-generate the article? I think the bot failed to do so, and I think I need it to complete the review checklist items for the paper. Please.

Thank you!

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02791/joss.02791/10.21105.joss.02791.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02791/joss.02791/10.21105.joss.02791.pdf) :page_facing_up: :point_left:

**Comment by kinow** [comment]
Thanks!

**Comment by gkthiruvathukal** [comment]
@gkthiruvathukal Sorry I didn't get to your request as fast as @arfon, @kinow. Looks like we're good now.

**Comment by whedon** [comment]
:wave: @kinow, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @xirdneh, please update us on how your review is going.

**Comment by kinow** [comment]
My review is complete @gkthiruvathukal :heavy_check_mark: 

Even managed to test `s4rdm3x` with Apache Commons Imaging. I was going to use Apache Commons Lang, but I am currently working on Imaging. I didn't add all the relationships between packages, and the tool correctly highlighted the failed clusterings.

![image](https://user-images.githubusercontent.com/304786/98224880-e61c7400-1fb8-11eb-83f5-c84cbbd89cec.png)

Didn't get fully familiar with the rest of the interface and metrics, but looks really useful for developers inspecting code bases, and getting familiar with new architectures.

I used IntelliJ's diagram builder to remind me of some of the relationships, but in the past I used Stan4J that would be a good tool to help users to create `sysmdl` files.

<details><summary>commons-imaging.sysmdl</summary>
# name
Apache Commons Imaging

# jar
commons-imaging-1.0-alpha2.jar

# root-packages
org/apache/commons/imaging/

# metrics file
#commons-imaging-file-metrics.csv

# modules
base
color
common
bmp
dcx
gif
icns
ico
jpeg
pcx
png
pnm
psd
rgbe
tiff
wbmp
xbm
xpm
icc
internal
palette

# mapping
# <high_level_module> <regular_expression>
base org.apache.commons.imaging.color.[^.]*
color org.apache.commons.imaging.color.*
common org.apache.commons.imaging.common.*
bmp org.apache.commons.imaging.formats.bmp.*
dcx org.apache.commons.imaging.formats.dcx.*
gif org.apache.commons.imaging.formats.gif.*
icns org.apache.commons.imaging.formats.icns.*
ico org.apache.commons.imaging.formats.ico.*
jpeg org.apache.commons.imaging.formats.jpeg.*
pcx org.apache.commons.imaging.formats.pcx.*
png org.apache.commons.imaging.formats.png.*
pnm org.apache.commons.imaging.formats.pnm.*
psd org.apache.commons.imaging.formats.psd.*
rgbe org.apache.commons.imaging.formats.rgbe.*
tiff org.apache.commons.imaging.formats.tiff.*
wbmp org.apache.commons.imaging.formats.wbmp.*
xbm org.apache.commons.imaging.formats.xbm.*
xpm org.apache.commons.imaging.formats.xpm.*
icc org.apache.commons.imaging.formats.icc.*
internal org.apache.commons.imaging.formats.internal.*
palette org.apache.commons.imaging.formats.palette.*

# relations
# <source_module> <target_module>

base icc
base common
common base
common internal
icc common
jpeg common
palette base
palette internal
color internal

</details>

**Comment by tobias-dv-lnu** [comment]
Awesome! Do you consider the sysmdl for commons imaging to be "correct"? If so would can I include it in the repo as an available system (always on the lookout for more data :) )

**Comment by kinow** [comment]
> Awesome! @kinow: Do you consider the sysmdl for commons imaging to be "correct"? If so would can I include it in the repo as an available system (always on the lookout for more data :) )

Not yet, but I will open a draft pull request. We can discuss how to improve it. I didn't understand how to use all the options and settings, and for the `experiment.xml` I simply used the same one from JebRef modifying the system loaded.

I've created a draft PR: https://github.com/tobias-dv-lnu/s4rdm3x/pull/14

**Comment by xirdneh** [comment]
Having some trouble testing a couple of things on the paper. I think it has to do with my local setup, I am currently tweaking some thing and will try to finish this over the weekend.
Sorry for the delay.

**Comment by tobias-dv-lnu** [comment]
@xirdneh: just let me know if I can help :)

**Comment by gkthiruvathukal** [comment]
@xirdneh Just checking on how things are coming along with your review. I'm definitely not trying to rush you but would like to see if we are getting closer.

@kinow Am I correct in interpreting your review as being complete and ready to recommend acceptance, or are their still issues requiring attention?

**Comment by kinow** [comment]
All good @gkthiruvathukal , review complete, article looking good, software built and tested locally. No other issues pending for me. Thanks!

**Comment by xirdneh** [comment]
@gkthiruvathukal I was able to test the code locally. Everything seems good.
I am not able to edit the checklist. Should I just be able to edit the issue description?

**Comment by arfon** [comment]
@whedon re-invite @xirdneh as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@xirdneh please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
@xirdneh - please accept the repository invite above, this should then allow you to edit the checklist.

**Comment by tobias-dv-lnu** [comment]
@xirdneh please let me know if there is anything I can do to help you with the review :)

**Comment by gkthiruvathukal** [comment]
Thanks for the nudge on this @tobias-dv-lnu.

@xirdneh Can you let us know your timeframe for completing your review? It looks like @kinow has done a fairly thorough review. I would like to move forward with acceptance as soon as we have your input. Thanks!

**Comment by xirdneh** [comment]
Hi, sorry about this.

I will finish the review by tomorrow afternoon.

I already have everything written down just needed the invitation.

**Comment by xirdneh** [comment]
@whedon re-invite @xirdneh as reviewer

**Comment by whedon** [comment]
I'm sorry @xirdneh, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by xirdneh** [comment]
@gkthiruvathukal Sorry, could you send the invitation again?
Seems like I didn't click it last time, I thought i did.

**Comment by gkthiruvathukal** [comment]
@whedon re-invite @xirdneh as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@xirdneh please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by gkthiruvathukal** [comment]
@xirdneh I hope that works!

**Comment by tobias-dv-lnu** [comment]
@xirdneh: Thanks, it seems to have worked! :)

**Comment by gkthiruvathukal** [comment]
@tobias-dv-lnu We are close! I will follow up with a final checklist as soon as I get a response to the following.

@xirdneh  Can you please confirm for us that you have no further issues to raise regarding this submission? I would like to move toward acceptance and give final instructions.

**Comment by xirdneh** [comment]
@gkthiruvathukal 
Yes, the submission is complete.

**Comment by gkthiruvathukal** [comment]
Thanks, @xirdneh 

@tobias-dv-lnu Ok, I am ready now! Please do the following:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

**Comment by tobias-dv-lnu** [comment]
- [x] Make a tagged release of your software, and list the version tag of the archived version here.
release version tag: v1.3_archive
URL: https://github.com/tobias-dv-lnu/s4rdm3x/tree/v1.3_archive
- [x] Archive the reviewed software in Zenodo
- [x]  Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [x] List the Zenodo DOI of the archived version here.
DOI: 10.5281/zenodo.4475664
URL: https://zenodo.org/record/4475664#.YBKnmjpKguU

**Comment by kyleniemeyer** [comment]
Thanks @tobias-dv-lnu @gkthiruvathukal, it looks like this is ready for acceptance so I can take it from here.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02791/joss.02791/10.21105.joss.02791.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02791/joss.02791/10.21105.joss.02791.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.4475664 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4475664" target="_blank">10.5281/zenodo.4475664</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon set v1.3 as version

**Comment by whedon** [comment]
OK. v1.3 is the version.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2077

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2077, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/3241403.3241456 is OK

MISSING DOIs

- 10.1016/j.infsof.2006.10.015 may be a valid DOI for title: Automated clustering to support the reflexion method
- 10.1109/wcre.2010.26 may be a valid DOI for title: Improving automated mapping in reflexion models using information retrieval techniques
- 10.1145/3344948.3344984 may be a valid DOI for title: Semi-automatic mapping of source code using naive Bayes
- 10.1145/3344948.3344997 may be a valid DOI for title: An exploration and experiment tool suite for code to architecture mapping techniques
- 10.1007/s11219-018-9404-z may be a valid DOI for title: Exploring the suitability of source code metrics for indicating architectural inconsistencies
- 10.1109/wcre.2012.35 may be a valid DOI for title: On the evolutionary nature of architectural violations

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@tobias-dv-lnu, it looks like DOIs may be available but missing for a number of your references. Can you please check these, and add if appropriate? I will then be able to accept the submission. Thanks!

**Comment by gkthiruvathukal** [comment]
Thanks, @kyleniemeyer for helping to bring this to closure! :)

**Comment by tobias-dv-lnu** [comment]
@kyleniemeyer Thanks! Just added the missing DOIs in the paper.bib file (whedon had made the correct guesses on the DOIs), everything should be ok now I hope :)

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.infsof.2006.10.015 is OK
- 10.1109/WCRE.2010.26 is OK
- 10.1145/3344948.3344984 is OK
- 10.1145/3344948.3344997 is OK
- 10.1145/3241403.3241456 is OK
- 10.1007/s11219-018-9404-z is OK
- 10.1109/wcre.2012.35 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.infsof.2006.10.015 is OK
- 10.1109/WCRE.2010.26 is OK
- 10.1145/3344948.3344984 is OK
- 10.1145/3344948.3344997 is OK
- 10.1145/3241403.3241456 is OK
- 10.1007/s11219-018-9404-z is OK
- 10.1109/wcre.2012.35 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2078

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2078, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1358329383006597121) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2081
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02791](https://doi.org/10.21105/joss.02791)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@kinow, @xirdneh - many thanks for your reviews here and to @gkthiruvathukal for editing this submission. JOSS relies upon the volunteer efforts of folks like yourselves and we simply wouldn't be able to do this without you! ✨ 

@tobias-dv-lnu - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02791/status.svg)](https://doi.org/10.21105/joss.02791)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02791">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02791/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02791/status.svg
   :target: https://doi.org/10.21105/joss.02791
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02791/status.svg)](https://doi.org/10.21105/joss.02791)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by tobias-dv-lnu** [comment]
@kinow, @xirdneh, @gkthiruvathukal, @arfon : Thank you all for making this happen!

**Comment by kinow** [comment]
Thank you for writing the article and having patience with the review process @tobias-dv-lnu . And thanks to all involved too :bouquet: !
