### ISSUE TITLE
[PRE REVIEW]: Cellocity: A Python package for analysis of confluent cell layer dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2792]
**Submitting author:** @oftatkofta (<a href="http://orcid.org/0000-0002-8945-2665">Jens Eriksson</a>)
**Repository:** <a href="https://github.com/Oftatkofta/cellocity" target ="_blank">https://github.com/Oftatkofta/cellocity</a>
**Version:** 1.0.0
**Editor:** @jni
**Reviewers:** @rfezzani, @aplyer
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @oftatkofta. **Currently, there isn't an JOSS editor assigned** to your paper.

@oftatkofta if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (283.9 files/s, 42095.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            761            858           1241
TeX                              2             28              2            300
reStructuredText                 6            207            115            266
Markdown                         5             31              0             81
YAML                             2             10             12             35
DOS Batch                        1              8              1             26
make                             2              4              7             11
-------------------------------------------------------------------------------
SUM:                            27           1049            995           1960
-------------------------------------------------------------------------------


Statistical information for the repository '65f3e251fddc6365d8bae5a1' was
gathered on 2020/10/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jens Eriksson                  136          8740           5878           99.73
Mikael E. Sellin                 1            18             20            0.26
jrijn                            1             1              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jens Eriksson              2842           32.5          4.7               11.44
Mikael E. Sellin             17           94.4          1.9               11.76
jrijn                         1          100.0          1.3                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41467-018-05578-7 is OK
- 10.1038/nmat4848 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/TIM.2010.2047149 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.bpj.2016.02.032 is OK
- 10.1016/j.tibtech.2018.12.001 is OK
- 10.1146/annurev.biophys.35.040405.102114 is OK
- 10.5281/zenodo.3930343 is OK

MISSING DOIs

- 10.1007/3-540-45103-x_50 may be a valid DOI for title: Two-Frame Motion Estimation Based on Polynomial Expansion

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02792/joss.02792/10.21105.joss.02792.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02792/joss.02792/10.21105.joss.02792.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @lpantano as editor

:wave: @lpantano - would you be able to take on this submission for us?

**Comment by whedon** [comment]
@lpantano has been invited to edit this submission.

**Comment by lpantano** [comment]
Hi Arfon, the papers seems interesting, but I don’t know about microscopy :( I don’t think I can handle well this edit.

**Comment by arfon** [comment]
@whedon invite @jni as editor

:wave: @jni - would you feel comfortable taking on a third paper?

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by jni** [comment]
@whedon assign me as editor

I have fairly low bandwidth this month but this is definitely in my wheelhouse! We just yesterday finished adding some PIV datasets to skimage! :joy: @Oftatkofta thanks for this work, apologies if I move a bit slow but I'll try to get reviewers lined up ASAP and get the process started!

**Comment by whedon** [comment]
OK, the editor is @jni

**Comment by jni** [comment]
@whedon assign @rfezzani as reviewer

**Comment by whedon** [comment]
OK, @rfezzani is now a reviewer

**Comment by jni** [comment]
@whedon add @aplyer as reviewer

**Comment by whedon** [comment]
OK, @aplyer is now a reviewer

**Comment by jni** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2818.
