### ISSUE TITLE
[PRE REVIEW]: BVPy: A Python package based on FEniCS and Gmsh for solving boundary value problems in cell and tissue mechanics.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2793]
**Submitting author:** @oalii (<a href="http://orcid.org/0000-0001-7671-7225">Olivier Ali</a>)
**Repository:** <a href="https://gitlab.inria.fr/mosaic/bvpy" target ="_blank">https://gitlab.inria.fr/mosaic/bvpy</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @IgorBaratta, @chennachaos, @finsberg
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @oalii. **Currently, there isn't an JOSS editor assigned** to your paper.

@oalii if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.19 s (445.2 files/s, 73502.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          52           1587           3096           3458
Jupyter Notebook                 9              0           3472            443
DOS Batch                        1             29              3            212
Markdown                         2            110              0            198
reStructuredText                 9            206            170            174
YAML                             3             16             10            173
make                             1             29              8            143
JSON                             3              0              0            130
TeX                              1              8              0            118
Dockerfile                       1             14              8             39
CSS                              1              0              0              9
Bourne Shell                     1              2              0              4
-------------------------------------------------------------------------------
SUM:                            84           2001           6767           5101
-------------------------------------------------------------------------------


Statistical information for the repository 'cc5650abca4dd4ceef557bd6' was
gathered on 2020/10/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Florian                        229         20229          15304           70.44
GACON Florian                    4           228              2            0.46
Olivier Ali                    138         11490           3192           29.10

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Florian                    4524           22.4          1.0               16.53
Olivier Ali                3617           31.5          1.0                9.43
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2793 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (890fd4099fd333577252941f/paper/paper.md): found character that cannot start any token while scanning for the next token at line 4 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@oalii - there are a number of issues with your `paper.md`. I've attempted to address them in: https://gist.githubusercontent.com/arfon/fe64794a79cbe9d0004b8ede620df49f/raw/4752f38cb5db08998161c43fda197b64929c81b9/paper.md

**Comment by arfon** [comment]
@whedon invite @Kevin-Mattheus-Moerman as editor

:wave: @Kevin-Mattheus-Moerman - I realise you already have a number of papers on your plate but would you be able to take this one too?

**Comment by whedon** [comment]
@Kevin-Mattheus-Moerman has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by oalii** [comment]
Hello @arfon, thanks for your editing of the `paper.md`. https://gist.githubusercontent.com/arfon/fe64794a79cbe9d0004b8ede620df49f/raw/4752f38cb5db08998161c43fda197b64929c81b9/paper.md

Since this is my first submission to JOSS I don't know how it works: Do I need to do anything with these modifications (update and push the file on our gitlab repo ?).

**Comment by arfon** [comment]
Hi @oalii. Yes, please update your paper and test is compiles with either the Whedon paper preview service (http://whedon.theoj.org) or here by issuing the command `@whedon generate pdf`.

The entire JOSS editorial process happens in the GitHub review issues and so it's essential that the paper can be compiled by Whedon here.

**Comment by oalii** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02793/joss.02793/10.21105.joss.02793.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02793/joss.02793/10.21105.joss.02793.pdf) :page_facing_up: :point_left:

**Comment by oalii** [comment]
@arfon, 
ok I updated `paper.md` with your modifications, the pdf is properly generated and all our tests pass. Again a stupid *newbie* question : I pushed the modify in the develop branch, should I merge it in the master or should I wait the end of the review process before pushing everything on the master ?

**Comment by arfon** [comment]
👍. There are no stupid questions here, these are all good ones :-)

Whedon can compile from the default (`master` in your case) or a named branch so it's up to you. Some authors never merge the JOSS paper into their default branch (preferring to keep it on a named branch for the entire process).

**Comment by oalii** [comment]
Thanks @arfon ,  
So maybe the best in our case would be to switch on the `develop` branch for the reviewing process and merge at the end in the `master` once all the improvements generated by the review will be made ? 
In that case, how can I specify to Whedon that the default branch to check is the `develop` one ?

**Comment by arfon** [comment]
Yes, that sounds good. We can ask Whedon to build from a custom branch with e.g.:

`@whedon generate pdf from branch develop`

**Comment by oalii** [comment]
@whedon generate pdf from branch develop

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch develop. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02793/joss.02793/10.21105.joss.02793.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02793/joss.02793/10.21105.joss.02793.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@oalii I will be looking for suitable reviewers for this submission. If you have any suggested reviewers in mind please list them here (remove `@` from github handles for now).

**Comment by Kevin-Mattheus-Moerman** [comment]
@chrisrichardson, @garth-wells, @IgorBaratta, @trallard, @meg-simula, @pefarrell, @SteveMaas1978, @sebastkm would you be interested in reviewing this submission for JOSS?

**Comment by IgorBaratta** [comment]
Hi @Kevin-Mattheus-Moerman ,
I'm happy to review this one!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @IgorBaratta as reviewer

**Comment by whedon** [comment]
OK, @IgorBaratta is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@oalii are you able to suggest any reviewers at this points? Thanks

**Comment by oalii** [comment]
Hi @Kevin-Mattheus-Moerman ,

Thanks for accepting to edit this manuscript.
I quickly checked online and came up with some suggestions:
@finsberg authored an FEniCS-based, biophysical-related paper in JOSS last year.
@jessdtate, @dlagrava, @jhill1, @chennachaos and @JaroslavHron already reviewed some FEniCS-based pieces for JOSS in the past, maybe they could fit ?

**Comment by oalii** [comment]
Hi @finsberg ,

Thanks for your help !

**Comment by chennachaos** [comment]
I am happy to help to review this submission.

**Comment by dlagrava** [comment]
@oalii it looks like you have already two reviewers. Good luck!

**Comment by oalii** [comment]
Thanks @chennachaos for jumping in !
And thanks also to @dlagrava for answering as well.
Let's wait for @Kevin-Mattheus-Moerman's ruling, I think he is the one in charge here :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @chennachaos as reviewer

**Comment by whedon** [comment]
OK, @chennachaos is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @finsberg as reviewer

**Comment by whedon** [comment]
OK, @finsberg is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2831.

**Comment by Kevin-Mattheus-Moerman** [comment]
@dlagrava we've started the review over at #2831. If you are able to/interested in helping as well I can add you as a reviewer there. Let me know. Thanks either way.
