### ISSUE TITLE
[PRE REVIEW]: effectsize: Estimation and Interpretation of Effect Size Indices and Standardized Parameters

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2794]
**Submitting author:** @mattansb (<a href="http://orcid.org/0000-0002-4287-4801">Mattan S. Ben-Shachar</a>)
**Repository:** <a href="https://github.com/easystats/effectsize" target ="_blank">https://github.com/easystats/effectsize</a>
**Version:** 0.4.0.001
**Editor:** @mikldk
**Reviewers:** @trashbirdecology, @jkarreth
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mattansb. **Currently, there isn't an JOSS editor assigned** to your paper.

@mattansb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.14 s (610.7 files/s, 91608.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               67           1350           2637           4361
XML                              1              0             42           1484
Rmd                              8            694            938            441
Markdown                         8            165              0            420
TeX                              1             90              0            329
YAML                             3             33              5            212
-------------------------------------------------------------------------------
SUM:                            88           2332           3622           7247
-------------------------------------------------------------------------------


Statistical information for the repository '9b72d65fe2d9b84e65ec607b' was
gathered on 2020/10/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel                           2            60            502           55.42
Dominique Makowski               1           198              0           19.53
mattansb                         2           249              5           25.05

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2794 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02794/joss.02794/10.21105.joss.02794.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02794/joss.02794/10.21105.joss.02794.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@mattansb - thanks for your submission to JOSS. Could you please suggest an alternative title for your paper without the innuendo?

**Comment by mattansb** [comment]
@arfon An alternative title would be "effectsize: Estimation and Interpretation of Effect Size Indices and Standardized Parameters".
Would that be acceptable?

For reviewers, we would like to suggest Guy Prochilo (gprochilo), Tristan Mahr (tjmahr) or Matt Craddock (craddm).

Thanks!

**Comment by mattansb** [comment]
@arfon I've changed the title.

**Comment by mattansb** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02794/joss.02794/10.21105.joss.02794.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02794/joss.02794/10.21105.joss.02794.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @mikldk as editor

:wave: @mikldk - would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@whedon check refereces from branch paper

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by mikldk** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1037/1082-989X.9.2.164 is OK
- 10.1002/9780470743386.ch7 is OK
- 10.1136/bmj.f7450 is OK
- 10.1037/1082-989X.8.4.434 is OK
- 10.21105/joss.02445 is OK
- 10.5281/zenodo.2074621 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mikldk** [comment]
@trashbirdecology, @tbrown122387: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by tbrown122387** [comment]
@mikldk sorry I’m really busy at the moment

**Comment by mikldk** [comment]
@kellieotto: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by trashbirdecology** [comment]
I can review this, but only because the logo is so amazing.

**Comment by kellieotto** [comment]
@mikldk I don't have the bandwidth to do a review right now - sorry!

**Comment by mikldk** [comment]
@mdogucu: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mdogucu** [comment]
I unfortunately cannot commit to do a review now.

**Comment by mikldk** [comment]
@pboesu, @jkarreth: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by jkarreth** [comment]
@mikldk yes, I'll be happy to review this - but would need to take advantage of the extended JOSS time frame, so I'd get my review in by mid-December (and will try for earlier of course)

**Comment by pboesu** [comment]
@mikldk Unfortunately I do not have capacity for this review at the moment.

**Comment by mikldk** [comment]
@whedon add @trashbirdecology as reviewer

**Comment by whedon** [comment]
OK, @trashbirdecology is now a reviewer

**Comment by mikldk** [comment]
@whedon add @jkarreth as reviewer

**Comment by whedon** [comment]
OK, @jkarreth is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2815.
