### ISSUE TITLE
[PRE REVIEW]: aiapy: A Python Package for Analyzing Solar EUV Image Data from AIA

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2795]
**Submitting author:** @wtbarnes (<a href="http://orcid.org/0000-0001-9642-6089">Will Barnes</a>)
**Repository:** <a href="https://gitlab.com/LMSAL_HUB/aia_hub/aiapy" target ="_blank">https://gitlab.com/LMSAL_HUB/aia_hub/aiapy</a>
**Version:** v0.3.0
**Editor:** @arfon
**Reviewers:** @hayesla, @samaloney
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @wtbarnes. **Currently, there isn't an JOSS editor assigned** to your paper.

@wtbarnes if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.14 s (542.1 files/s, 31819.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          38            521           1293           1640
reStructuredText                27            146             98            318
YAML                             5             16             30             99
Markdown                         1             18              0             55
INI                              1             10              0             55
TOML                             1             10              0             38
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            75            733           1429           2240
-------------------------------------------------------------------------------


Statistical information for the repository 'caa2b3fe2d4dcb9e45a5138a' was
gathered on 2020/10/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Albert Y. Shih                   1            81              0            0.49
David Stansby                    1            61              5            0.40
Georgios Chintzoglou             2           418             99            3.16
Mark Cheung                      7           705             23            4.44
Nicholas Padmanabhan             8           822            439            7.70
Nina Shirman                     1           559              0            3.41
Paul Wright                      2            77              9            0.52
Stuart Mumford                   2           164           1383            9.44
Will Barnes                     47          6959           4467           69.73
mbobra                           1            74             41            0.70

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Albert Y. Shih               69           85.2          5.8               17.39
David Stansby                61          100.0          0.0                3.28
Georgios Chintzoglou        134           32.1          5.1               14.93
Mark Cheung                  22            3.1          4.9               45.45
Nina Shirman                 46            8.2         12.2                6.52
Paul Wright                  63           81.8          1.0               11.11
Stuart Mumford              157           95.7          6.2               30.57
Will Barnes                2850           41.0          8.5               18.77
mbobra                       52           70.3          6.4               82.69
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2795 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02795/joss.02795/10.21105.joss.02795.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02795/joss.02795/10.21105.joss.02795.pdf) :page_facing_up: :point_left:

**Comment by wtbarnes** [comment]
Possible suggested reviewers:

Laura Hayes: hayesla
Shane Maloney: samaloney
Matt Craig: mwcraig
Shreyas Bapat: shreyasbapat

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @hayesla and @samaloney - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The software (_aiapy: A Python Package for Analyzing Solar EUV Image Data from AIA_) we'd be asking you to review is here: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy and the associated short paper is [here](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02795/joss.02795/10.21105.joss.02795.pdf).

**Comment by hayesla** [comment]
Hey @arfon - yes I'm happy to review this submission to JOSS

**Comment by arfon** [comment]
Great, thanks @hayesla. I'll add you here now but won't actually open the review thread (a separate issue) until I've identified a second reviewer.

**Comment by arfon** [comment]
@whedon add @hayesla as reviewer

**Comment by whedon** [comment]
OK, @hayesla is now a reviewer

**Comment by samaloney** [comment]
Hi @arfon I'm also happy to review this JOSS submission

**Comment by arfon** [comment]
@whedon add @samaloney as reviewer

**Comment by whedon** [comment]
OK, @samaloney is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2801.

**Comment by arfon** [comment]
@hayesla, @samaloney, @wtbarnes  - see you over in #2801 where the actual review will take place.
