### ISSUE TITLE
[PRE REVIEW]: SHED: Streaming Heterogeneous Event Data Tracking with Provenance

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2796]
**Submitting author:** @CJ-Wright (<a href="http://orcid.org/0000-0003-2522-7028">Christopher Wright</a>)
**Repository:** <a href="https://github.com/xpdAcq/SHED" target ="_blank">https://github.com/xpdAcq/SHED</a>
**Version:** 0.7.5
**Editor:** @arfon
**Reviewers:** @remram44
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @CJ-Wright. **Currently, there isn't an JOSS editor assigned** to your paper.

@CJ-Wright if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.25 s (155.0 files/s, 40447.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          25            771            827           3276
reStructuredText                 4            212             28            330
DOS Batch                        1             34              2            239
make                             1             32              5            204
YAML                             4             11              7            154
Jupyter Notebook                 2              0           3928             79
Markdown                         1              4              0             30
INI                              1              0              0              2
-------------------------------------------------------------------------------
SUM:                            39           1064           4797           4314
-------------------------------------------------------------------------------


Statistical information for the repository 'd17b581e02b97473bd3e7513' was
gathered on 2020/10/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christopher J. Wrigh           100          2633           1171            5.59
Julien L                         6            63             12            0.11
Julien Lhermitte                13            94             35            0.19
XPD Operator                     2            27              6            0.05
christopher                    388         33568          30272           93.73
st3107                          11           107            122            0.34

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Julien Lhermitte              4            4.3         35.8               25.00
christopher                4775           14.2         21.9                8.67
st3107                       95           88.8          1.0                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2796 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02796/joss.02796/10.21105.joss.02796.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02796/joss.02796/10.21105.joss.02796.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @katyhuff as editor

:wave: @katyhuff - would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@katyhuff has been invited to edit this submission.

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
@whedon check references

**Comment by katyhuff** [comment]
* @remram44 : Remi Rampin, are you able to and interested in taking on this review for JOSS?
* This submission is in need of expertise in reproducibility tooling as well as familiarity with the systems and languages involved (primarily python).
* Title: SHED: Streaming Heterogeneous Event Data Tracking with Provenance
* Summary: The SHED package provides a python based software framework for real time analysis of streaming data with provenance. It is highly flexible, allowing analysis pipelines to be built for any variety of experimental data that is arriving in a time series. It allows straightforward serialization of the pipeline, and the analysis results, for storage in databases with provenance information that allows analyses later to be pulled from the databases, adapted if desired, and rerun.
* Article Proof: https://raw.githubusercontent.com/openjournals/joss-papers/joss.02796/joss.02796/10.21105.joss.02796.pdf
* Submitting author: @CJ-Wright (Christopher Wright)
* Repository: https://github.com/xpdAcq/SHED
* Version: 0.7.5

**Comment by katyhuff** [comment]
* @eteq : Erik Tollerud, are you able to and interested in taking on this review for JOSS?
* This submission is in need of expertise in reproducibility tooling as well as familiarity with the systems and languages involved (primarily python).
* Title: SHED: Streaming Heterogeneous Event Data Tracking with Provenance
* Summary: The SHED package provides a python based software framework for real time analysis of streaming data with provenance. It is highly flexible, allowing analysis pipelines to be built for any variety of experimental data that is arriving in a time series. It allows straightforward serialization of the pipeline, and the analysis results, for storage in databases with provenance information that allows analyses later to be pulled from the databases, adapted if desired, and rerun.
* Article Proof: https://raw.githubusercontent.com/openjournals/joss-papers/joss.02796/joss.02796/10.21105.joss.02796.pdf
* Submitting author: @CJ-Wright (Christopher Wright)
* Repository: https://github.com/xpdAcq/SHED
* Version: 0.7.5

**Comment by katyhuff** [comment]
* @dvanic : Darya Vanichkina, are you able to and interested in taking on this review for JOSS?
* This submission is in need of expertise in reproducibility tooling as well as familiarity with the systems and languages involved (primarily python).
* Title: SHED: Streaming Heterogeneous Event Data Tracking with Provenance
* Summary: The SHED package provides a python based software framework for real time analysis of streaming data with provenance. It is highly flexible, allowing analysis pipelines to be built for any variety of experimental data that is arriving in a time series. It allows straightforward serialization of the pipeline, and the analysis results, for storage in databases with provenance information that allows analyses later to be pulled from the databases, adapted if desired, and rerun.
* Article Proof: https://raw.githubusercontent.com/openjournals/joss-papers/joss.02796/joss.02796/10.21105.joss.02796.pdf
* Submitting author: @CJ-Wright (Christopher Wright)
* Repository: https://github.com/xpdAcq/SHED
* Version: 0.7.5

**Comment by katyhuff** [comment]
@whedon check references

**Comment by remram44** [comment]
@katyhuff I can do a review

**Comment by arfon** [comment]
:wave: @katyhuff - happy new year! It looks like this submission is still waiting to go out for review (and to identify a second reviewer)

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@CJ-Wright - I'm sorry it has taken so very long to move this paper forward. Unfortunately, @katyhuff was unable to edit this submission for us and so I shall take it over from here.

**Comment by arfon** [comment]
👋 @remram44 - are you still willing to provide a review for this submission?

**Comment by arfon** [comment]
:wave: @julianpistorius @mbdemoraes – would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review is [_SHED: Streaming Heterogeneous Event Data Tracking with Provenance_](https://github.com/xpdAcq/SHED).

**Comment by remram44** [comment]
I can review, \#2605 is dormant

**Comment by arfon** [comment]
@remram44 - many thanks! I'll go ahead and add you as a reviewer and start the review. @CJ-Wright - As and when we find a second reviewer I'll add them too.

**Comment by arfon** [comment]
@whedon add @remram44 as reviewer

**Comment by whedon** [comment]
OK, @remram44 is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3119.
