### ISSUE TITLE
[REVIEW]: pyEQUIB: Python Package for Plasma Diagnostics and Abundance Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2798]
**Submitting author:** @danehkar (<a href="http://orcid.org/0000-0003-4552-5997">Ashkbiz Danehkar</a>)
**Repository:** <a href="https://github.com/equib/pyEQUIB" target ="_blank">https://github.com/equib/pyEQUIB</a>
**Version:** v0.3.3
**Editor:** @arfon
**Reviewer:** @arfon
**Archive:** <a href="https://doi.org/10.5281/zenodo.4287576" target="_blank">10.5281/zenodo.4287576</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/cdfb70639009bf589cfa683f6b7e23af/status.svg)](https://joss.theoj.org/papers/cdfb70639009bf589cfa683f6b7e23af)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cdfb70639009bf589cfa683f6b7e23af"><img src="https://joss.theoj.org/papers/cdfb70639009bf589cfa683f6b7e23af/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cdfb70639009bf589cfa683f6b7e23af/status.svg)](https://joss.theoj.org/papers/cdfb70639009bf589cfa683f6b7e23af)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/equib/pyEQUIB" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arfon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/equib/pyEQUIB">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@danehkar) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/mnras/stt1116 is OK
- 10.1093/mnras/stu203 is OK
- 10.5281/zenodo.47794 is OK
- 10.3847/0004-6256/151/2/38 is OK
- 10.1017/pasa.2018.1 is OK
- 10.21105/joss.00899 is OK
- 10.21105/joss.00898 is OK
- 10.1046/j.1365-8711.2003.06371.x is OK
- 10.1111/j.1365-2966.2005.09381.x is OK
- 10.1111/j.1365-2966.2012.20863.x is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02798/joss.02798/10.21105.joss.02798.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02798/joss.02798/10.21105.joss.02798.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@danehkar - please adapt your `paper.md` to follow the same format as I described over here: https://github.com/openjournals/joss-reviews/issues/2772#issuecomment-718227083

Once you've done that, I can work on getting the addendum published.

**Comment by danehkar** [comment]
@arfon Thank you. I will adapt my `paper.m` accordingly soon. I will let you know when it is ready.

**Comment by whedon** [comment]
:wave: @arfon, please update us on how your review is going.

**Comment by arfon** [comment]
:wave: @danehkar - just checking in here. Any progress reworking your paper?

**Comment by danehkar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02798/joss.02798/10.21105.joss.02798.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02798/joss.02798/10.21105.joss.02798.pdf) :page_facing_up: :point_left:

**Comment by danehkar** [comment]
>  @danehkar - just checking in here. Any progress reworking your paper?

@arfon I updated the paper accordingly.

**Comment by arfon** [comment]
Thanks @danehkar - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by danehkar** [comment]
@arfon I made a new release (v0.3.3) in its GitHub repository ([https://github.com/equib/pyEQUIB](https://github.com/equib/pyEQUIB)) and also an archive of the software in Zenodo service:

doi:[10.5281/zenodo.4287576](https://doi.org/10.5281/zenodo.4287576)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4287576 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4287576" target="_blank">10.5281/zenodo.4287576</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00899 is OK
- 10.21105/joss.00898 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1934

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1934, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@danehkar - this is now published.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02798/status.svg)](https://doi.org/10.21105/joss.02798)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02798">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02798/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02798/status.svg
   :target: https://doi.org/10.21105/joss.02798
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02798/status.svg)](https://doi.org/10.21105/joss.02798)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
