### ISSUE TITLE
[PRE REVIEW]: EUKulele: Taxonomic annotation of the unsung eukaryotic microbes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2799]
**Submitting author:** @akrinos (<a href="http://orcid.org/0000-0001-9767-8392">Arianna Krinos</a>)
**Repository:** <a href="https://github.com/AlexanderLabWHOI/EUKulele" target ="_blank">https://github.com/AlexanderLabWHOI/EUKulele</a>
**Version:** v1.0.0
**Editor:** @will-rowe
**Reviewers:** @johanneswerner, @jcmcnch
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @akrinos. **Currently, there isn't an JOSS editor assigned** to your paper.

@akrinos if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.05 s (170.3 files/s, 33278.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      14           2289           2323           8446
Python                          31            554            372           3218
SVG                              1              0              0           2671
HTML                            17           1340             41           2146
TeX                              2             96              0            934
PO File                         11            315            557            830
CSS                              5            185             37            731
reStructuredText                21            320            335            575
Jupyter Notebook                 4              0           4049            573
JSON                            25              0              0            537
YAML                            21             24             40            430
Bourne Shell                    11             56             57            183
Markdown                         6             75              0            173
INI                              3             20             41            141
DOS Batch                        2              8              1             28
make                             1              4              7              9
R                                1              1              0              4
RobotFramework                   2              0              0              3
-------------------------------------------------------------------------------
SUM:                           178           5287           7860          21632
-------------------------------------------------------------------------------


Statistical information for the repository 'f7c61fa612658e0eabd4b291' was
gathered on 2020/10/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ARIANNA KRINOS                   3            51            513            1.71
Arianna Krinos                   4            73              8            0.25
Harriet Alexander                4           188             25            0.64
akrinos                        146         24807           7359           97.40

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
ARIANNA KRINOS               17           33.3          2.7               23.53
akrinos                   17197           69.3          2.7               15.58
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02799/joss.02799/10.21105.joss.02799.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02799/joss.02799/10.21105.joss.02799.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @will-rowe as editor

:wave: @will-rowe - the submitting author suggested you as the handling editor, do you have capacity to take this on right now?

**Comment by whedon** [comment]
@will-rowe has been invited to edit this submission.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.7287/peerj.preprints.27295v1 is OK
- 10.1038/s41564-018-0176-9 is OK
- 10.1038/s41467-017-02342-1 is OK
- 10.1101/2020.06.30.180687 is OK
- 10.5281/zenodo.1476236 is OK
- 10.1051/0004-6361/201629272 is OK
- 10.1051/0004-6361/201322068 is OK

MISSING DOIs

- 10.1142/s0219720012500151 may be a valid DOI for title: Metagenomic taxonomic classification using extreme learning machines
- 10.1038/ncomms11257 may be a valid DOI for title: Fast and sensitive taxonomic classification for metagenomics with Kaiju
- 10.1111/1755-0998.13147 may be a valid DOI for title: A metagenomic assessment of microbial eukaryotic diversity in the global ocean
- 10.1038/ismej.2015.30 may be a valid DOI for title: Metatranscriptomic census of active protists in soils
- 10.1038/nrmicro.2016.160 may be a valid DOI for title: Probing the evolution, ecology and physiology of marine protists using transcriptomics
- 10.1093/database/baaa051 may be a valid DOI for title: SAGER: a database of Symbiodiniaceae and Algal Genomic Resource
- 10.1111/jpy.12529 may be a valid DOI for title: Robust Dinoflagellata phylogeny inferred from public transcriptome databases
- 10.1093/database/baaa051 may be a valid DOI for title: SAGER: a database of Symbiodiniaceae and Algal Genomic Resource
- 10.1016/j.tim.2018.10.009 may be a valid DOI for title: Are we overestimating protistan diversity in nature?
- 10.1093/nar/gks1160 may be a valid DOI for title: The Protist Ribosomal Reference database (PR2): a catalog of unicellular eukaryote small sub-unit rRNA sequences with curated taxonomy
- 10.1016/j.tree.2014.03.006 may be a valid DOI for title: The others: our biased perspective of eukaryotic genomes
- 10.1371/journal.pbio.2005849 may be a valid DOI for title: EukRef: Phylogenetic curation of ribosomal RNA to enhance understanding of eukaryotic diversity and distribution
- 10.1093/gigascience/giy158 may be a valid DOI for title: Re-assembly, quality evaluation, and annotation of 678 microbial eukaryotic reference transcriptomes
- 10.1007/978-3-319-61510-3_4 may be a valid DOI for title: Functional analysis in metagenomics using MEGAN 6
- 10.1007/978-1-4939-3369-3_13 may be a valid DOI for title: MG-RAST, a metagenomics service for analysis of microbial community structure and function
- 10.1016/j.gpb.2015.08.003 may be a valid DOI for title: The Tara Oceans project: new opportunities and greater challenges ahead
- 10.1038/sdata.2017.203 may be a valid DOI for title: The reconstruction of 2,631 draft metagenome-assembled genomes from the global oceans
- 10.1093/bioinformatics/btw445 may be a valid DOI for title: SWORD—a highly efficient protein database search
- 10.1038/nmeth.3176 may be a valid DOI for title: Fast and sensitive protein alignment using DIAMOND
- 10.1101/2020.06.30.180687 may be a valid DOI for title: EukProt: a database of genome-scale predicted proteins across the diversity of eukaryotic life
- 10.1371/journal.pone.0016342 may be a valid DOI for title: How and why DNA barcodes underestimate the diversity of microbial eukaryotes
- 10.1038/ncomms12860 may be a valid DOI for title: Adaptive radiation by waves of gene transfer leads to fine-scale resource partitioning in marine microbes
- 10.1111/gcb.12983 may be a valid DOI for title: Bridging the gap between omics and earth system science to better understand how environmental change impacts marine microbes
- 10.1098/rstb.2015.0331 may be a valid DOI for title: Censusing marine eukaryotic diversity in the twenty-first century
- 10.1007/978-3-030-38281-0_12 may be a valid DOI for title: Eukaryotic Pangenomes
- 10.1038/nature12221 may be a valid DOI for title: Pan genome of the phytoplankton Emiliania underpins its global distribution
- 10.1128/aem.01541-09 may be a valid DOI for title: Introducing mothur: open-source, platform-independent, community-supported software for describing and comparing microbial communities

INVALID DOIs

- None
```

**Comment by akrinos** [comment]
Suggested reviewers:
- johanneswerner
- juanvillada
- jcmcnch
- csoneson
- edgraham
- frederic-mahe

**Comment by will-rowe** [comment]
Hi. I'm just on annual leave this week but can take this on Monday

**Comment by arfon** [comment]
> Hi. I'm just on annual leave this week but can take this on Monday

:zap: thanks @will-rowe! I'll go ahead and assign you this now.

**Comment by arfon** [comment]
@whedon assign @will-rowe as editor

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Thanks for your reviewer suggestions @akrinos. Let's ping some and see if they can take this on.

**Comment by will-rowe** [comment]
Hi @johanneswerner and @jcmcnch. Would either of you be willing to review this submission to JOSS?

**Comment by johanneswerner** [comment]
Hi @will-rowe, I am interested in reviewing the submission.

**Comment by will-rowe** [comment]
@whedon assign @johanneswerner as reviewer

**Comment by whedon** [comment]
OK, @johanneswerner is now a reviewer

**Comment by will-rowe** [comment]
Brill - thanks @johanneswerner! Hang tight while we find a second reviewer and then we will start the review thread

**Comment by jcmcnch** [comment]
Hi @will-rowe, I would be willing to review Arianna's tool, but in the interests of full disclosure her PhD advisor Harriet is a friend of mine from grad school. Don't know if that presents a conflict of interest from your perspective as an editor. Also FYI I'm also more of a biologist/oceanographer type, so may not offer as useful feedback wrt software design as a true full-blooded bioinformatician (though I am trying to learn this sort of thing myself and am familiar with python). I could be probably most useful simulating the naive user trying to install/use the software and as a skeptical eye towards how well the annotation works. Finally, before I commit fully, is there a timeline that you require? I'm a little busy these days but think I could find time in the coming ~3 weeks to get to this.

**Comment by will-rowe** [comment]
Hi @jcmcnch - thanks for getting back to me. I don't think this presents a [conflict of interest](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy).

I think your background makes you a great potential reviewer for JOSS - have a look at the [reviewer criteria](https://joss.readthedocs.io/en/latest/review_criteria.html) and see if you think you can assess these points. Usually you don't need to be a bioinformatician/developer to complete a review for us. If you want, I can always help with points you don't feel confident with.

That timeline is fine for me - within a month would be great.

If all this is okay with you and you still want to review for us, please write back and we can start the reviews.

**Comment by jcmcnch** [comment]
@will-rowe OK sounds good, I'm in!

**Comment by will-rowe** [comment]
Great! Thanks @jcmcnch.

I'll start the review thread, which you all will get tagged in. Anyone questions, let me know.

**Comment by will-rowe** [comment]
@whedon add @jcmcnch as reviewer

**Comment by whedon** [comment]
OK, @jcmcnch is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2817.
