### ISSUE TITLE
[REVIEW]: aiapy: A Python Package for Analyzing Solar EUV Image Data from AIA

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2801]
**Submitting author:** @wtbarnes (<a href="http://orcid.org/0000-0001-9642-6089">Will Barnes</a>)
**Repository:** <a href="https://gitlab.com/LMSAL_HUB/aia_hub/aiapy" target ="_blank">https://gitlab.com/LMSAL_HUB/aia_hub/aiapy</a>
**Version:** v0.3.0
**Editor:** @arfon
**Reviewer:** @hayesla, @samaloney
**Archive:** <a href="https://doi.org/10.5281/zenodo.4274931" target="_blank">10.5281/zenodo.4274931</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9bfcd1677e43046a5136766863419a04/status.svg)](https://joss.theoj.org/papers/9bfcd1677e43046a5136766863419a04)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9bfcd1677e43046a5136766863419a04"><img src="https://joss.theoj.org/papers/9bfcd1677e43046a5136766863419a04/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9bfcd1677e43046a5136766863419a04/status.svg)](https://joss.theoj.org/papers/9bfcd1677e43046a5136766863419a04)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/LMSAL_HUB/aia_hub/aiapy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@hayesla & @samaloney, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/LMSAL_HUB/aia_hub/aiapy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@wtbarnes) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/LMSAL_HUB/aia_hub/aiapy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@wtbarnes) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @hayesla, @samaloney it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2801 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02801/joss.02801/10.21105.joss.02801.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02801/joss.02801/10.21105.joss.02801.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@hayesla, @samaloney - this is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/2801 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be _completed_ within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by whedon** [comment]
:wave: @hayesla, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @samaloney, please update us on how your review is going.

**Comment by hayesla** [comment]
> 👋 @hayesla, please update us on how your review is going.

almost done!

**Comment by samaloney** [comment]
> 👋 @samaloney, please update us on how your review is going.

still working on it

**Comment by hayesla** [comment]
@arfon @wtbarnes sorry for the delay! 

I'm now done with my review and recommend it to be published 🌞 

Just some minor comments, that have been raised on the gitlab repo:

 * https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/issues/86 - Bug with respike
 * https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/issues/87 - Potential user error 
 * https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/issues/88 - Minor doc addition

I also have two small questions: 

* Just on a side note, and maybe I'm missing something - the calculation of the psf with `aiapy.psf.psf` takes a good bit of time, but shouldn't really change much - I wonder if it would be quicker to load it in from somewhere rather than calculate everytime?

* is it worth adding a note in the `COMMENT` or `HISTORY` header keyword what has been applied to the data (i.e. register/update_pointing) and the date of such operation? May be worth it for files saved again. But I'm sure this has been thought about - just curious. I see its done for respike but not the other calibration functions.

**Comment by wtbarnes** [comment]
Thanks for your review @hayesla! Just to respond to your questions:

* That's correct. The problem is that these aren't stored anywhere (e.g. JSOC, VSO, etc.). `aiapy.psf.deconvolve` has the `psf` kwarg which allows a user to pass in a precomputed PSF rather than doing it on the fly each time. The suggested workflow would be to calculate the PSF for each channel once with `aiapy.psf.psf` and then store these (e.g. as FITS) somewhere and load them into memory when they are needed. 
* That is a very fair point. https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/issues/56 has been open for a while to deal with this, but we've not come to a consensus as far as how to systematically update the `HISTORY` keyword.

As far as the open issues go, I've just closed 88 with a PR and have added comments to the other two. Do these issues and questions need to be adequately addressed prior to publication?

**Comment by hayesla** [comment]
Thanks for clarification @wtbarnes!

No these aren't blocking issues for publication in my opinion - just suggestions from my review.

**Comment by arfon** [comment]
:wave: @samaloney - can I just check that you're happy with this submission _as-is_ and recommend publication in JOSS?

**Comment by samaloney** [comment]
Sorry @arfon I was just checking a few things, I'm more than happy to recommend for publication.

@wtbarnes Great work on a very useful and well documented package.

**Comment by arfon** [comment]
@whedon check references

**Comment by arfon** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02801/joss.02801/10.21105.joss.02801.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02801/joss.02801/10.21105.joss.02801.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@wtbarnes - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by wtbarnes** [comment]
@arfon I've just created a v0.3.1 release for the package: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/releases/v0.3.1 as well as an associated Zenodo record for this release: https://zenodo.org/record/4274931. This release includes several fixes suggest by @hayesla as part of her review.

The Zenodo DOI is: 10.5281/zenodo.4274931

@hayesla @samaloney Thanks very much for reviewing the package and the paper!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4274931 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4274931" target="_blank">10.5281/zenodo.4274931</a> is the archive.

**Comment by arfon** [comment]
@whedon accept from branch joss-paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2801 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.5/lib/bibtex/bibliography.rb:50:in `read': No such file or directory @ rb_sysopen - 9511e0a11d5128c0be0847f5/joss/["paper.bib"] (Errno::ENOENT)
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.5/lib/bibtex/bibliography.rb:50:in `open'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.5/lib/bibtex/utilities.rb:25:in `open'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/bibtex_parser.rb:38:in `generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/compilers.rb:246:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:100:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:88:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@wtbarnes - please update the line referencing your figure:

```
bibliography: [paper.bib] -> bibliography: paper.bib
```

**Comment by wtbarnes** [comment]
Sorry about that. Just updated.

**Comment by arfon** [comment]
@whedon accept from branch joss-paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s11207-011-9776-8 is OK
- 10.1007/s11207-011-9841-3 is OK
- 10.1007/s11207-011-9804-8 is OK
- 10.1007/s11207-011-9842-2 is OK
- 10.1007/s11207-009-9487-6 is OK
- 10.3847/1538-4357/ab4f7a is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.21105/joss.01614 is OK
- 10.1007/s11207-020-01622-2 is OK
- 10.1023/A:1005038224881 is OK
- 10.1051/aas:1997368 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1915

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1915, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss-paper 
```

**Comment by arfon** [comment]
@whedon accept deposit=true from branch joss-paper

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1328300431232086016) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1916
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02801](https://doi.org/10.21105/joss.02801)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@hayesla, @samaloney - many thanks for your reviews here, JOSS simply wouldn't work without the efforts of volunteers like yourselves ✨ 

@wtbarnes - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02801/status.svg)](https://doi.org/10.21105/joss.02801)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02801">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02801/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02801/status.svg
   :target: https://doi.org/10.21105/joss.02801
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02801/status.svg)](https://doi.org/10.21105/joss.02801)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
