### ISSUE TITLE
[PRE REVIEW]: netrd: A library for network reconstruction and graph distances

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2802]
**Submitting author:** @sdmccabe (<a href="http://orcid.org/0000-0002-7180-145X">Stefan McCabe</a>)
**Repository:** <a href="https://github.com/netsiphd/netrd" target ="_blank">https://github.com/netsiphd/netrd</a>
**Version:** v0.2.2
**Editor:** @arfon
**Reviewers:** @adi3, @sonal-raj
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sdmccabe. **Currently, there isn't an JOSS editor assigned** to your paper.

@sdmccabe if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.24 s (361.7 files/s, 43271.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          67           2148           3568           3061
TeX                              1             44              0            420
Markdown                         3            118              0            334
Jupyter Notebook                 1              0            265            116
reStructuredText                12             85            136            104
YAML                             2             10              6             58
DOS Batch                        1              8              1             26
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                            88           2417           3982           4128
-------------------------------------------------------------------------------


Statistical information for the repository 'b65e6776667ac0e82ee3bc57' was
gathered on 2020/10/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex Gates                       1             3              0            0.01
Alexander Gates                  1           132              0            0.61
Andy Mellor                      9           289             35            1.51
Anton Tsitsulin                  1            90              0            0.42
Brennan Klein                   27          1675            411            9.70
Carolina Mattsson                8           296             97            1.83
Chia-Hung Yang                   3           129            253            1.78
David Saffo                      4            97              1            0.46
Guillaume St-Onge               17           826            109            4.35
Harry Hartle                     8           334              8            1.59
Jessica                          2            63              1            0.30
Leo Torres                       2            17              6            0.11
Matteo Chinazzi                  2           255              0            1.19
Ryan J. Gallagher                3           102              3            0.49
Stefan McCabe                   32          1430            562            9.26
Tim LaRock                      31           506            144            3.02
charlesmurphy1                  10           387             42            2.00
chiahungyang                    20          1209            175            6.44
leotrs                          28          3106           1762           22.64
rer                              2            60              6            0.31
sdmccabe@github.com             96          4124           2758           32.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alex Gates                  106         3533.3         21.4               23.58
Andy Mellor                 253           87.5         16.5               10.28
Anton Tsitsulin              74           82.2         18.6                9.46
Brennan Klein               946           56.5         20.1               10.78
Carolina Mattsson            62           20.9         20.2                8.06
Chia-Hung Yang              126           97.7          9.6               18.25
David Saffo                  53           54.6         21.3                9.43
Guillaume St-Onge           517           62.6         20.8               12.77
Harry Hartle                231           69.2         21.1               12.12
Jessica                      43           68.3         20.3                6.98
Matteo Chinazzi             183           71.8         21.3                3.28
Ryan J. Gallagher            63           61.8         21.3               17.46
Stefan McCabe              1176           82.2          8.9               10.20
Tim LaRock                  237           46.8         20.9               16.03
charlesmurphy1              156           40.3         21.3                6.41
chiahungyang                612           50.6         21.0               12.42
leotrs                     2283           73.5         17.7                7.23
rer                          30           50.0         21.4                6.67
sdmccabe@github.com        1626           39.4         18.8                6.70
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02802/joss.02802/10.21105.joss.02802.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02802/joss.02802/10.21105.joss.02802.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1140/epjb/e2004-00110-5 is OK
- 10.1080/00107510903084036 is OK
- 10.1093/acprof:oso/9780199206650.001.0001 is OK
- 10.1177/0094306116681814 is OK
- 10.1145/3154524 is OK
- 10.1063/1.5025050 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1126/science.1227079 is OK
- 10.1214/09-AOAS303 is OK
- 10.1103/PhysRevE.99.023311 is OK
- 10.1073/pnas.1718154115 is OK
- 10.1093/biostatistics/kxm045 is OK
- 10.1017/S0962492904000236 is OK
- 10.1103/PhysRevLett.110.210601 is OK
- 10.1209/0295-5075/87/48007 is OK
- 10.1103/PhysRevE.90.062129 is OK
- 10.2139/ssrn.433840 is OK
- 10.1371/journal.pcbi.1002653 is OK
- 10.1103/PhysRevLett.123.128301 is OK
- 10.1155/2018/3132940 is OK
- 10.5169/seals-266450 is OK
- 10.1016/S0016-0032(23)90506-5 is OK
- 10.1109/DSAA.2015.7344816 is OK
- 10.1214/18-AOAS1176 is OK
- 10.1016/j.physleta.2010.12.038 is OK
- 10.1007/s41109-019-0156-x is OK
- 10.1103/PhysRevX.6.041062 is OK
- 10.1103/PhysRevE.98.012319 is OK
- 10.1109/GlobalSIP.2013.6736904 is OK
- 10.1016/j.dam.2017.10.007 is OK
- 10.1145/3219819.3219991 is OK
- 10.3233/978-1-60750-692-8-227 is OK
- 10.1103/PhysRevE.66.046109 is OK
- 10.1007/s41109-019-0147-y is OK
- 10.1103/PhysRevE.99.052309 is OK
- 10.1038/ncomms13928 is OK
- 10.1145/2824443 is OK
- 10.3389/frobt.2014.00011 is OK
- 10.1126/sciadv.aau4996 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1098/rspa.2019.0744 is INVALID
```

**Comment by arfon** [comment]
:wave: @sdmccabe, thanks for your submission to JOSS. Could you please make sure you have a section named _Statement of need_ near the top of your paper with a description of the software designed for a generalist audience?

**Comment by arfon** [comment]
> 👋 @sdmccabe, thanks for your submission to JOSS. Could you please make sure you have a section named Statement of need near the top of your paper with a description of the software designed for a generalist audience?

Edit: Ignore me. I see the title of your first section. The paper is good as-is.

**Comment by arfon** [comment]
@whedon invite @bmcfee as editor

:wave: @bmcfee - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@bmcfee has been invited to edit this submission.

**Comment by bmcfee** [comment]
@arfon sure; I can get started on it tomorrow.

**Comment by arfon** [comment]
⚡️ thanks @bmcfee! I'll go ahead and assign you now.

**Comment by arfon** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
OK, the editor is @bmcfee

**Comment by adi3** [comment]
@bmcfee I'll be happy to review this if you'd like

**Comment by kthyng** [comment]
@bmcfee Are you able to work on this submission? Thanks!

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @adi3 - are you still available to review this submission?

**Comment by arfon** [comment]
@gabrielspadon @sonal-raj @Shathra @sudarshansudarshan - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission is _netrd: A library for network reconstruction and graph distances_, and the software is primarily written in Python https://github.com/netsiphd/netrd

**Comment by adi3** [comment]
@arfon yes, I can review this one

**Comment by arfon** [comment]
@whedon add @adi3 as reviewer

**Comment by whedon** [comment]
OK, @adi3 is now a reviewer

**Comment by arfon** [comment]
> @arfon yes, I can review this one

⚡ thanks @adi3. I'll wait another few days to find a second reviewer before moving this to the full review if that's OK with you?

**Comment by sonal-raj** [comment]
@arfon, I can review this.

**Comment by arfon** [comment]
@whedon add @sonal-raj as reviewer

**Comment by whedon** [comment]
OK, @sonal-raj is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2990.

**Comment by arfon** [comment]
@adi3, @sonal-raj - many thanks for agreeing to review here! See you over in #2990 where the actual review will take place.
