### ISSUE TITLE
[PRE REVIEW]: PUPILS pipeline: A flexible Matlab toolbox for eyetracking and pupillometry data processing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2803]
**Submitting author:** @heliaib (<a href="http://orcid.org/0000-0002-2899-1673">Helia Relaño-Iborra</a>)
**Repository:** <a href="https://gitlab.gbar.dtu.dk/heliaib/PUPILS-preprocessing-pipeline" target ="_blank">https://gitlab.gbar.dtu.dk/heliaib/PUPILS-preprocessing-pipeline</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @heliaib. **Currently, there isn't an JOSS editor assigned** to your paper.

@heliaib if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.02 s (494.9 files/s, 47168.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                           7            203             75            379
TeX                              1             16              0            151
Markdown                         2             51              0             78
-------------------------------------------------------------------------------
SUM:                            10            270             75            608
-------------------------------------------------------------------------------


Statistical information for the repository 'bfad286782dadcbb9e3dd26d' was
gathered on 2020/10/30.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02803/joss.02803/10.21105.joss.02803.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02803/joss.02803/10.21105.joss.02803.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.1469-8986.1982.tb02540.x is OK
- 10.3758/BF03210302 is OK
- 10.3758/s13428-017-1008-1 is OK
- 10.3758/s13428-017-1007-2 is OK
- 10.3758/BF03195486 is OK
- 10.1177/2331216518800869 is OK

MISSING DOIs

- 10.1126/science.154.3756.1583 may be a valid DOI for title: Pupil Diameter and Load on Memory
- 10.1126/science.143.3611.1190 may be a valid DOI for title: Pupil Size in Relation to Mental Activity during Simple Problem-Solving

INVALID DOIs

- http://dx.doi.org/10.1037/h0032456 is INVALID because of 'https://doi.org/' prefix
```

**Comment by heliaib** [comment]
RE: Potential reviewers. Based on the list of potential reviewers provided I see the following matches: mwanvliet, Suresh-lab, acolum, wspr, cMcdan.

Other possibilities (slightly more removed topic-wise): fernandoandreotti, sdelantsheer, wahls, CELavecchia, josphhardinee

**Comment by arfon** [comment]
@whedon query scope

:wave: @heliaib - thanks for your submission to JOSS. I've flagged this for review by our editorial team as this submission is very small and may be judged to not meet our [substantial scholarly effort threshold](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by heliaib** [comment]
@arfon  yes, I thought that might be the case - thanks for flagging it!

**Comment by heliaib** [comment]
Fixed DOIs 

@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@whedon check references

**Comment by arfon** [comment]
> Fixed DOIs

> @whedon check references

> @whedon generate pdf

@heliaib - these commands currently have to be issued in a separate comment on the thread (or at the start of a comment).

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02803/joss.02803/10.21105.joss.02803.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02803/joss.02803/10.21105.joss.02803.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.1469-8986.1982.tb02540.x is OK
- 10.1126/science.143.3611.1190 is OK
- 10.3758/BF03210302 is OK
- 10.1037/h0032456 is OK
- 10.3758/s13428-017-1008-1 is OK
- 10.3758/s13428-017-1007-2 is OK
- 10.3758/BF03195486 is OK
- 10.1177/2331216518800869 is OK

MISSING DOIs

- 10.1126/science.143.3611.1190 may be a valid DOI for title: Pupil Size in Relation to Mental Activity during Simple Problem-Solving

INVALID DOIs

- None
```

**Comment by arfon** [comment]
:wave: @heliaib, thanks for your submission to JOSS. After consulting with the editorial team, your submission has been deemed [too small to be considered for review here](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
