### ISSUE TITLE
[PRE REVIEW]: spaghetti: spatial network analysis in PySAL

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2806]
**Submitting author:** @jGaboardi (<a href="http://orcid.org/0000-0002-4776-6826">James Gaboardi</a>)
**Repository:** <a href="https://github.com/pysal/spaghetti" target ="_blank">https://github.com/pysal/spaghetti</a>
**Version:** v1.5.3
**Editor:** @usethedata
**Reviewers:** @martibosch
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jGaboardi. **Currently, there isn't an JOSS editor assigned** to your paper.

@jGaboardi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.54 s (102.7 files/s, 67303.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            30           2129             30          24974
CSS                             41           1223            391          14648
SVG                              4              0              0          14102
JavaScript                      17           3482           2908          11727
Jupyter Notebook                14              0          15845           3240
Python                           9           1144           2410           2185
Markdown                         8            227              0           1151
TeX                              2             58              4            745
YAML                            18              5             51            375
reStructuredText                13            131            175             99
DOS Batch                        1              8              1             27
make                             1              7              6             19
-------------------------------------------------------------------------------
SUM:                           158           8414          21821          73292
-------------------------------------------------------------------------------


Statistical information for the repository '0bded99297ebd6a7f8e1b697' was
gathered on 2020/10/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
David Folch                      5            91             32            0.05
James Gaboardi                 738        113961          89808           88.29
Jay                             43          5374           6985            5.36
Phil Stephens                    1             0              2            0.00
Philip Stephens                  2           112            193            0.13
Serge                            3          1885           1858            1.62
Serge Rey                       59          5823           4096            4.30
Sergio Rey                       2            47             75            0.05
Stefanie Lumnitz                 1             0            231            0.10
ljw                              1            66              4            0.03
ljwolf                           6            22             81            0.04
rahul799                         2             9             10            0.01
sjsrey                           1            18              2            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
James Gaboardi            23846           20.9         14.2               16.04
Serge Rey                     7            0.1         26.3               28.57
ljwolf                        3           13.6         17.9                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02806/joss.02806/10.21105.joss.02806.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02806/joss.02806/10.21105.joss.02806.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/ijgi4020815 is OK
- 10.1111/gean.12211 is OK
- 10.5281/zenodo.1343650 is OK
- 10.1111/j.0016-7363.2005.00674.x is OK
- 10.1002/9781119967101 is OK
- 10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.5281/zenodo.3379659 is OK
- 10.5281/zenodo.3669853 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.5281/zenodo.1472807 is OK
- 10.1007/s11067-018-9427-9 is OK

MISSING DOIs

- 10.1007/978-3-642-03647-7_11 may be a valid DOI for title: PySAL: A Python Library of Spatial Analytical Methods

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon invite @usethedata as editor

:wave: @usethedata - are you available to take on an additional paper currently? `@bstabler` would be the obvious editor to take this paper but he's currently unable to edit for JOSS.

**Comment by whedon** [comment]
@usethedata has been invited to edit this submission.

**Comment by jGaboardi** [comment]
@arfon, Lorena Mesa or Leonardo Uieda may be nice fits for editor if @usethedata is not available.

**Comment by jGaboardi** [comment]
**Potentional Reviewers**
* anitagraser
* ResidentMario
* HTenkanen
* hobu
* gboeing

**Comment by usethedata** [comment]
I've got capacity to handle this and have no conflicts of interest with any of the authors.

**Comment by usethedata** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
@jGaboardi Thanks for the suggestions of reviewers.

**Comment by usethedata** [comment]
Update.   Decline and no response on my first request.  Sending some additional reviewer requests.  Some do this through tagging on the issue, but I prefer, when possible, to do so by email based on my perspectives around privacy.

**Comment by jGaboardi** [comment]
> Update. Decline and no response on my first request. Sending some additional reviewer requests. Some do this through tagging on the issue, but I prefer, when possible, to do so by email based on my perspectives around privacy.

Thanks for the update. Let me know if there is anything I can do.

**Comment by usethedata** [comment]
@jGaboardi Thanks.  Nothing in particular at this time.  I have your list and a few others that have volunteered.  Unlike some other papers I've done, I don't think finding reviewers will be a huge problem.  Declines and no response aren't that unusual, and lots of people are in very challenging situations from time to time.  

one more decline.  Additional request sent out this morning.

**Comment by usethedata** [comment]
@whedon assign @martibosch as reviewer

**Comment by whedon** [comment]
OK, @martibosch is now a reviewer

**Comment by usethedata** [comment]
Still looking for the second reviewer, but I have one, so I'm opening the review issue and will add the second reviewer when I get an accept.

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2826.
