### ISSUE TITLE
[PRE REVIEW]: Palette diagram: A Python package for visualization of collective categorical data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2808]
**Submitting author:** @tatsuro-kawamoto (<a href="http://orcid.org/0000-0002-9898-839X">Tatsuro Kawamoto</a>)
**Repository:** <a href="https://github.com/palette-diagram/palette-diagram" target ="_blank">https://github.com/palette-diagram/palette-diagram</a>
**Version:** v1.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tatsuro-kawamoto. **Currently, there isn't an JOSS editor assigned** to your paper.

@tatsuro-kawamoto if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (127.2 files/s, 14700.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           3             70             17            237
Markdown                         2             63              0            161
TeX                              1             12              0             70
Jupyter Notebook                 1              0            171              8
-------------------------------------------------------------------------------
SUM:                             7            145            188            476
-------------------------------------------------------------------------------


Statistical information for the repository '5518c2426b40e49cdff36f14' was
gathered on 2020/11/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Chihiro Noguchi                  1           324              0           85.26
Tatsuro Kawamoto                 1            28             28           14.74

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chihiro Noguchi             296           91.4          0.0                5.74
Tatsuro Kawamoto             28          100.0          0.0                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1126/science.290.5500.2319 is OK
- 10.1126/science.290.5500.2323 is OK

MISSING DOIs

- 10.1109/tvcg.2008.166 may be a valid DOI for title: Stacked graphs–geometry & aesthetics

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2808 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:204:in `block in parse_authors': Author (Chihiro Noguchi) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@tatsuro-kawamoto - many thanks for your submission to JOSS. Unfortunately at ~240 lines of Python, this submission is too small to be published in JOSS: https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
