### ISSUE TITLE
[REVIEW]: OpenSpace: An open-source astrovisualization framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#281]
**Submitting author:** @alexanderbock (<a href="http://orcid.org/0000-0002-2849-6146">Alexander Bock</a>)
**Repository:** <a href="https://github.com/OpenSpace/OpenSpace" target ="_blank">https://github.com/OpenSpace/OpenSpace</a>
**Version:** v0.8.0
**Editor:** @danielskatz
**Reviewer:** @MatthewTurk
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.835206" target="_blank">10.5281/zenodo.835206</a>

## Status

[![status](http://joss.theoj.org/papers/4843fc43db46dff18152e3f55a533b8d/status.svg)](http://joss.theoj.org/papers/4843fc43db46dff18152e3f55a533b8d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4843fc43db46dff18152e3f55a533b8d"><img src="http://joss.theoj.org/papers/4843fc43db46dff18152e3f55a533b8d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4843fc43db46dff18152e3f55a533b8d/status.svg)](http://joss.theoj.org/papers/4843fc43db46dff18152e3f55a533b8d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/OpenSpace/OpenSpace" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/OpenSpace/OpenSpace">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.8.0)?
- [x] **Authorship:** Has the submitting author (@alexanderbock) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @MatthewTurk it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@MatthewTurk - this is ready for you to review.  You should review the reviewer instructions on http://joss.theoj.org/about. Let me know if you have any problems.

**Comment by danielskatz** [comment]
Hi @MatthewTurk - any news on this review?

**Comment by danielskatz** [comment]
Hi @MatthewTurk - any news on this review?

**Comment by danielskatz** [comment]
Hi @MatthewTurk - any news on this review?

**Comment by alexanderbock** [comment]
I think it's my turn...   any news? :)

**Comment by MatthewTurk** [comment]
Hi, sorry -- had a :baby: and that didn't go quite as smoothly as hoped, and am reviewing this today.

**Comment by alexanderbock** [comment]
Congratulations on the 🍼

**Comment by MatthewTurk** [comment]
@danielskatz Review done, ready to go!

**Comment by danielskatz** [comment]
Hi @arfon - it looks like we are ready (for you) to do the final steps to accept this!

**Comment by danielskatz** [comment]
thanks @MatthewTurk!

**Comment by arfon** [comment]
Hi @alexanderbock, before I can accept this submission could you please reformat your `paper.md` file. A couple of issues:

1. The `affiliations` need pulling out into a separate block in the YAML header (see [this example](https://raw.githubusercontent.com/arfon/fidgit/master/paper/paper.md))
2. None of the references in your bibtex are mentioned directly in the paper so by default they won't be included by pandoc when compiling the paper. Could you please make sure you're actually citing them (see how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by danielskatz** [comment]
Hi @alexanderbock - just a reminder that we are waiting for you on this...

**Comment by alexanderbock** [comment]
Sorry for the delay;  there was another deadline ongoing.

@arfon   I changed the `paper.md` accordingly.  I thought that I had seen in one of the instructions that inline affiliations were okay as well.

I have two affiliation tags next to my name in there, is specifying the attribute multiple times allowed or is there a different syntax for this?

**Comment by arfon** [comment]
@alexanderbock - you nearly had it right. I fixed things up in https://github.com/OpenSpace/OpenSpace/pull/373

Once you've merged https://github.com/OpenSpace/OpenSpace/pull/373 could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by alexanderbock** [comment]
@arfon  The pullrequest is merged, thanks for the fix.  If have uploaded the software at Zenodo: http://doi.org/10.5281/zenodo.835206   (https://zenodo.org/record/835206)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.835206 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.835206" target="_blank">10.5281/zenodo.835206</a> is the archive.

**Comment by arfon** [comment]
@MatthewTurk many thanks for your review here and @danielskatz for editing this submission ✨ 

@alexanderbock - your submission is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00281 :zap: 🚀 💥

**Comment by alexanderbock** [comment]
Thank you all very much!
