### ISSUE TITLE
[REVIEW]: PRDA: An R pakcage for Prospective and Retrospective Design Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2810]
**Submitting author:** @ClaudioZandonella (<a href="http://orcid.org/0000-0001-7721-6318">Claudio Zandonella Callegher</a>)
**Repository:** <a href="https://github.com/ClaudioZandonella/PRDA" target ="_blank">https://github.com/ClaudioZandonella/PRDA</a>
**Version:**  v1.0.0
**Editor:** @cMadan
**Reviewer:** @DominiqueMakowski, @mmrabe
**Archive:** <a href="https://doi.org/10.5281/zenodo.4533739" target="_blank">10.5281/zenodo.4533739</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/24d4c5907f813e8a56e1426e2d26b77c/status.svg)](https://joss.theoj.org/papers/24d4c5907f813e8a56e1426e2d26b77c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/24d4c5907f813e8a56e1426e2d26b77c"><img src="https://joss.theoj.org/papers/24d4c5907f813e8a56e1426e2d26b77c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/24d4c5907f813e8a56e1426e2d26b77c/status.svg)](https://joss.theoj.org/papers/24d4c5907f813e8a56e1426e2d26b77c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ClaudioZandonella/PRDA" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@DominiqueMakowski & @mmrabe, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @cMadan know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ClaudioZandonella/PRDA">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ClaudioZandonella) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ClaudioZandonella/PRDA">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ClaudioZandonella) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @DominiqueMakowski, @mmrabe it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fpsyg.2019.02893 is OK
- 10.31234/osf.io/q9f86 is OK
- 10.1177/1745691614551642 is OK
- 10.7326/0003-4819-121-3-199408010-00008 is OK
- 10.2527/jas.2006-449 is OK
- 10.1111/bmsp.12132 is OK
- 10.1136/bmj.325.7375.1304 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02810/joss.02810/10.21105.joss.02810.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02810/joss.02810/10.21105.joss.02810.pdf) :page_facing_up: :point_left:

**Comment by DominiqueMakowski** [comment]
PRDA is an R package aiming at facilitating the implementation of design analysis, a recent framework extending traditional power analysis.

The package is very well documented, with a thorough yet accessible introduction to the conceptual framework.

Regarding its API, it is also very accessible, well-documented with good examples and clear (helped by the low number of functions).
The paper is well-written, clear and to the point. 
Overall, it's a really good and useful piece of software that will improve the accessibility of design analysis.

I only have some minor comments that I made directly on the software's repo (see above ☝️) :relaxed:

**Comment by mmrabe** [comment]
The submitted paper describes the R package PRDA, which can be used for retrospective and prospective design analysis. It has significant advantages over prior R packages, such as an option for prospective design analysis and using standardized effect sizes, which are more common than unstandardized effect sizes in some scientific disciplines.

The paper, documentation, and examples are thoughtfully crafted and very straightforward. As a whole, they could possibly make the rather complex issue of power/design analysis more graspable and easy to address for researchers without advanced skills in statistical programming.

@DominiqueMakowski has already thoroughly evaluated the paper/package with an exemplary speed 😲 and made a number of suggestions, all of which I support. I made three additional minor suggestions (see above 👆). Once these have been addressed, I can fully recommend the paper for publication in JOSS.

**Comment by ClaudioZandonella** [comment]
@DominiqueMakowski and @mmrabe thanks for your very rapid reviews and thanks for your encouraging opinions!

I had a quick look at the issues and all your suggestions are very useful. Most of them will require small changes so at the weekend I will have the time to fix everything. Thanks!

**Comment by cMadan** [comment]
@DominiqueMakowski @mmrabe, thanks for the prompt and thorough reviews. I really appreciate the time and effort you are putting in to review this submission!

**Comment by cMadan** [comment]
@ClaudioZandonella, how are the revisions coming along?

**Comment by ClaudioZandonella** [comment]
Dear @cMadan I have integrated all the useful suggestions and comments by @mmrabe and @DominiqueMakowski.

The only missing issue is ClaudioZandonella/PRDA#2 regarding the upload of the package to CRAN. I have re-submitted the package to CRAN after they required a few changes to abide by their policy. In a few days, everything should be ok and I will be able to ultimate the revision.

**Comment by ClaudioZandonella** [comment]
Dear @cMadan, I have reviewed all the issues and updated the [paper/paper.md](https://github.com/ClaudioZandonella/PRDA/blob/master/paper/paper.md) file. 

Thanks, @mmrabe and @DominiqueMakowski  I really appreciate your comments and suggestions. They helped me to improve the overall quality of the package.

**Comment by mmrabe** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2810 with the following error: 

 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.327 ...nolinkurl{claudiozandonella@gmail.com}}}}

Looks like we failed to compile the PDF

**Comment by ClaudioZandonella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02810/joss.02810/10.21105.joss.02810.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02810/joss.02810/10.21105.joss.02810.pdf) :page_facing_up: :point_left:

**Comment by cMadan** [comment]
@ClaudioZandonella, I need to do some final checks, but we're almost done! (So the review is with me now.)

**Comment by ClaudioZandonella** [comment]
Dear @cMadan I just want to be sure that everything is fine with the review or if there is something I can do to help

**Comment by cMadan** [comment]
@ClaudioZandonella, apologies for the delay. It's been a busy time for me with exam marking/other responsibilities, but I'll try and get this wrapped up over the next few days.

**Comment by ClaudioZandonella** [comment]
@cMadan perfect thanks! I was just worried there might be some problems. Absolutely no rush, I know that unfortunately, these are difficult and busy times and indeed, thanks for the time you have already dedicated to our work.

**Comment by cMadan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fpsyg.2019.02893 is OK
- 10.31234/osf.io/q9f86 is OK
- 10.1177/1745691614551642 is OK
- 10.7326/0003-4819-121-3-199408010-00008 is OK
- 10.2527/jas.2006-449 is OK
- 10.1111/bmsp.12132 is OK
- 10.1136/bmj.325.7375.1304 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02810/joss.02810/10.21105.joss.02810.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02810/joss.02810/10.21105.joss.02810.pdf) :page_facing_up: :point_left:

**Comment by cMadan** [comment]
@ClaudioZandonella, everything looks good to me!

To move forward with accepting your submission, there are a few last things to take care of:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

**Comment by ClaudioZandonella** [comment]
Dear @cMadan, thanks for your work.

Here the last required information:

- tag version v1.0.0 [https://github.com/ClaudioZandonella/PRDA/releases/tag/v1.0.0](https://github.com/ClaudioZandonella/PRDA/releases/tag/v1.0.0)
- Zenodo DOI [http://doi.org/10.5281/zenodo.4533739](http://doi.org/10.5281/zenodo.4533739)

Let me know if there is something else I can do.
Thanks!

**Comment by arfon** [comment]
@whedon set  v1.0.0 as version

**Comment by whedon** [comment]
OK.  v1.0.0 is the version.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4533739 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4533739" target="_blank">10.5281/zenodo.4533739</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fpsyg.2019.02893 is OK
- 10.31234/osf.io/q9f86 is OK
- 10.1177/1745691614551642 is OK
- 10.7326/0003-4819-121-3-199408010-00008 is OK
- 10.2527/jas.2006-449 is OK
- 10.1111/bmsp.12132 is OK
- 10.1136/bmj.325.7375.1304 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2101

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2101, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@cMadan - I'm currently trying to move a bunch of submissions that are very close to finished through the last steps. I believe this is one of these so will proceed the accept and publish now.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1363459128048431104) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2103
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02810](https://doi.org/10.21105/joss.02810)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@DominiqueMakowski, @mmrabe - many thanks for your reviews here and to @cMadan for editing this submission. JOSS relies upon the volunteer efforts of people like you, and we simply wouldn't be able to do it without you! ✨ 

@ClaudioZandonella - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02810/status.svg)](https://doi.org/10.21105/joss.02810)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02810">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02810/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02810/status.svg
   :target: https://doi.org/10.21105/joss.02810
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02810/status.svg)](https://doi.org/10.21105/joss.02810)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
