### ISSUE TITLE
[PRE REVIEW]: c-lasso: a Python package for constrained sparse regression and classification

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2811]
**Submitting author:** @Leo-Simpson (<a href="http://orcid.org/0000-0003-0717-5244">Leo Simpson</a>)
**Repository:** <a href="https://github.com/Leo-Simpson/c-lasso" target ="_blank">https://github.com/Leo-Simpson/c-lasso</a>
**Version:** v1.0
**Editor:** @mjsottile
**Reviewers:** @jbytecode, @glemaitre
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Leo-Simpson. **Currently, there isn't an JOSS editor assigned** to your paper.

@Leo-Simpson if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/biomet/71.2.323 is OK
- 10.1101/2020.09.01.277632 is OK
- 10.1007/s10957-018-1430-2 is OK
- 10.1007/s11228-011-0191-y is OK
- 10.1214/19-EJS1662 is OK
- 10.1007/s12561-020-09283-2 is OK
- 10.1080/10618600.2018.1473777 is OK
- 10.1080/01621459.2019.1609970 is OK
- 10.1162/NECO_a_00434 is OK
- 10.1093/biomet/asu031 is OK
- 10.1111/j.1467-9868.2010.00740.x is OK
- 10.1214/009053606000001370 is OK
- 10.1214/16-AOAS928 is OK

MISSING DOIs

- 10.1007/bf02985802 may be a valid DOI for title: The Elements of Statistical Learning: Data Mining, Inference, and Prediction

INVALID DOIs

- https://doi.org/10.1016/j.csda.2020.106958 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=8.15 s (5.3 files/s, 12124.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             3           6745              6          41729
SQL                              1              0              0          37299
Python                          19            893            820           3443
Markdown                         6            499              3           1113
Jupyter Notebook                 3              0           5152            520
TeX                              1             21              1            209
R                                3             35             32             76
reStructuredText                 5             52             64             37
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            43           8257           6086          84461
-------------------------------------------------------------------------------


Statistical information for the repository '74dbc8b66f808cbec11046e3' was
gathered on 2020/11/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Leo-Simpson                    166         19112          13956          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Leo-Simpson                5156           27.0          2.4                7.06
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02811/joss.02811/10.21105.joss.02811.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02811/joss.02811/10.21105.joss.02811.pdf) :page_facing_up: :point_left:

**Comment by Leo-Simpson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Leo-Simpson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02811/joss.02811/10.21105.joss.02811.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02811/joss.02811/10.21105.joss.02811.pdf) :page_facing_up: :point_left:

**Comment by Leo-Simpson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/biomet/71.2.323 is OK
- 10.1101/2020.09.01.277632 is OK
- 10.1007/s10957-018-1430-2 is OK
- 10.1007/s11228-011-0191-y is OK
- 10.1214/19-EJS1662 is OK
- 10.1007/s12561-020-09283-2 is OK
- 10.1080/10618600.2018.1473777 is OK
- 10.1080/01621459.2019.1609970 is OK
- 10.1007/bf02985802 is OK
- 10.1016/j.csda.2020.106958 is OK
- 10.1162/NECO_a_00434 is OK
- 10.1093/biomet/asu031 is OK
- 10.1111/j.1467-9868.2010.00740.x is OK
- 10.1214/009053606000001370 is OK
- 10.1214/16-AOAS928 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@pdebuyl @melissawm @drvinceknight could one of you edit this submission?

**Comment by pdebuyl** [comment]
@Kevin-Mattheus-Moerman I just picked pysensors. If nobody takes this next week I can do it as well.

**Comment by arfon** [comment]
@Kevin-Mattheus-Moerman - let's give this one to @mjsottile who is available to edit again.

**Comment by arfon** [comment]
@whedon assign @mjsottile as editor

:wave: @mjsottile - can you take this one for us?

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mjsottile** [comment]
Sounds good.  @Leo-Simpson : please let me know if you have any suggested reviewers for your submission.  Otherwise I will start to identify a few people to ask.

**Comment by Leo-Simpson** [comment]
Thank you @mjsottile . I don't have specific suggestion for reviewers, but for example I saw that jbytecode have computational statistics and optimization on his domain area so I think it could fit.

**Comment by mjsottile** [comment]
:wave: Hello @jbytecode, @zhampel, @nhejazi : Would you be interested in providing a review for this submission to JOSS?  I have identified you based on your areas of knowledge as listed in our potential reviewer spreadsheet.  Please let me know if you are interested and available.  Thank you!

**Comment by zhampel** [comment]
@mjsottile I will be out of office for the next two weeks and can not take on the review at the moment. Cheers

**Comment by jbytecode** [comment]
Dear editor @mjsottile ,  I gladly accept reviewing this paper, thank you.

**Comment by nhejazi** [comment]
Thanks, @mjsottile -- unfortunately, I am already committed to several other ongoing reviews and do not have the bandwidth to accept another at the moment.

**Comment by mjsottile** [comment]
@whedon add @jbytecode as reviewer

**Comment by whedon** [comment]
OK, @jbytecode is now a reviewer

**Comment by mjsottile** [comment]
:wave: @oesteban, @tupi, @glemaitre : Would you be interested in providing a review for this submission to JOSS? I have identified you based on your areas of knowledge as listed in our potential reviewer spreadsheet. Please let me know if you are interested and available. Thank you!

**Comment by glemaitre** [comment]
@mjsottile I can help with the review.

**Comment by mjsottile** [comment]
@whedon add @glemaitre as reviewer

**Comment by whedon** [comment]
OK, @glemaitre is now a reviewer

**Comment by mjsottile** [comment]
Thanks @glemaitre and @jbytecode for agreeing to help - it looks like we're good to start the review.  Please let me know if you have any questions over in the review thread.

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2844.

**Comment by Leo-Simpson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02811/joss.02811/10.21105.joss.02811.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02811/joss.02811/10.21105.joss.02811.pdf) :page_facing_up: :point_left:

**Comment by Leo-Simpson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02811/joss.02811/10.21105.joss.02811.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02811/joss.02811/10.21105.joss.02811.pdf) :page_facing_up: :point_left:

**Comment by Leo-Simpson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02811/joss.02811/10.21105.joss.02811.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02811/joss.02811/10.21105.joss.02811.pdf) :page_facing_up: :point_left:
