### ISSUE TITLE
[REVIEW]: secuTrialR: Seamless interaction with clinical trial databases in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2816]
**Submitting author:** @PatrickRWright (<a href="http://orcid.org/0000-0002-1153-0846">Patrick R. Wright</a>)
**Repository:** <a href="https://github.com/SwissClinicalTrialOrganisation/secuTrialR" target ="_blank">https://github.com/SwissClinicalTrialOrganisation/secuTrialR</a>
**Version:** 1.0.6
**Editor:** @csoneson
**Reviewer:** @pacoramon, @sachsmc
**Archive:** <a href="https://doi.org/10.5281/zenodo.4280767" target="_blank">10.5281/zenodo.4280767</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/42515acce06c46e43dbb236e00682dcf/status.svg)](https://joss.theoj.org/papers/42515acce06c46e43dbb236e00682dcf)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/42515acce06c46e43dbb236e00682dcf"><img src="https://joss.theoj.org/papers/42515acce06c46e43dbb236e00682dcf/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/42515acce06c46e43dbb236e00682dcf/status.svg)](https://joss.theoj.org/papers/42515acce06c46e43dbb236e00682dcf)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/SwissClinicalTrialOrganisation/secuTrialR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@pacoramon & @sachsmc, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SwissClinicalTrialOrganisation/secuTrialR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@PatrickRWright) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SwissClinicalTrialOrganisation/secuTrialR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@PatrickRWright) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @pacoramon, @sachsmc it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9781107256644 is OK
- 10.1186/1745-6215-11-79 is OK
- 10.1038/d41586-020-00758-2 is OK
- 10.21105/joss.01686 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
@pacoramon, @sachsmc - thanks for agreeing to review this submissions. This is where the review happens. You can find some instructions above, as well as your individual checklists. Don't hesitate to ping me if you have any questions (I will also be checking in regularly).

**Comment by PatrickRWright** [comment]
Thank you for taking this on from my side too :thumbsup:

**Comment by sachsmc** [comment]
Hi @PatrickRWright , 

I noted a few small issues with the documentation and the software paper in issues 225 and 226 on your repo: 

https://github.com/SwissClinicalTrialOrganisation/secuTrialR/issues/225
https://github.com/SwissClinicalTrialOrganisation/secuTrialR/issues/226

Otherwise the package looks and works great!

Best wishes,

Michael

**Comment by PatrickRWright** [comment]
Thank you @sachsmc for the taking the time and your comments. I'll try and get on to them asap.

**Comment by PatrickRWright** [comment]
Note to myself: Add the reviewers and editor to the acknowledgements.

**Comment by whedon** [comment]
:wave: @sachsmc, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @pacoramon, please update us on how your review is going.

**Comment by PatrickRWright** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: :point_left:

**Comment by PatrickRWright** [comment]
@csoneson we have addressed all points brought up by @sachsmc

**Comment by PatrickRWright** [comment]
@pacoramon can you tell us your legal name so we can adjust it in the acknowledgements?

**Comment by csoneson** [comment]
> We are, however, not sure how to solve the issue with one of the links in the references moving out of the page. Any idea?

Good question. I'm not sure why that link is not wrapped like the others. Perhaps someone from the @openjournals/dev team has an idea.

**Comment by sachsmc** [comment]
@csoneson  One way to solve it requires modifying the latex template (not sure how onerous that would be). If you add the code 

    \usepackage[hyphens]{url}

to the header before the hyperref package is loaded, it will break the url at hyphens. By default, it will only break at slashes. 

https://tex.stackexchange.com/questions/175399/line-breaking-of-urls-at

**Comment by pacoramon** [comment]
>  @pacoramon, please update us on how your review is going.
I am progressing, although not very fast. Sorry! 

> @pacoramon can you tell us your legal name so we can adjust it in the acknowledgements?
My legal name is Francisco Estupiñán-Romero. Thanks for the acknowledgement although I am not going very fast with my review just now. I will try to catch up.

**Comment by PatrickRWright** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: :point_left:

**Comment by PatrickRWright** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: :point_left:

**Comment by PatrickRWright** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: :point_left:

**Comment by xuanxu** [comment]
> We are, however, not sure how to solve the issue with one of the links in the references moving out of the page. Any idea?
 

A quick fix would be to use the shorter-form url for the same article: 
https://www.spiegel.de/wissenschaft/a-13bd06d7-22a1-4b3d-af23-ff43e5e8abd6

**Comment by PatrickRWright** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: :point_left:

**Comment by sachsmc** [comment]
I've completed my review. Thanks @PatrickRWright for addressing my comments

**Comment by pacoramon** [comment]
I've also finished mine. Thanks, @PatrickRWright for the work done, and @csoneson for inviting me to review.  
I feel I have not contributed much, but this review process has been swift, and all just worked out right away or was already done accordingly to guidelines, so congrats!

**Comment by csoneson** [comment]
@sachsmc, @pacoramon - thanks a lot for your reviews!

@PatrickRWright - I will give a quick look at the submission too and come back to you with the next steps shortly.

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9781107256644 is OK
- 10.1186/1745-6215-11-79 is OK
- 10.1038/d41586-020-00758-2 is OK
- 10.21105/joss.01686 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.jbi.2019.103208 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.jbi.2008.08.010 is INVALID because of 'https://doi.org/' prefix
```

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: :point_left:

**Comment by PatrickRWright** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9781107256644 is OK
- 10.1186/1745-6215-11-79 is OK
- 10.1038/d41586-020-00758-2 is OK
- 10.21105/joss.01686 is OK
- 10.1016/j.jbi.2019.103208 is OK
- 10.1016/j.jbi.2008.08.010 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by PatrickRWright** [comment]
@csoneson the dois should be fixed.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02816/joss.02816/10.21105.joss.02816.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
Thanks @PatrickRWright, looks good. I had a look through the submission, and I just noted one other thing: I think there is at least one place where `secuTrialdata` should be in fixed-width font, could you double-check this? 

The next steps are as follows:
- [ ] Make a tagged release of the current state of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service
- [ ] Check that the archival deposit has the correct metadata. This includes the title (should match the paper title) and author list (should match the paper author list). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

**Comment by PatrickRWright** [comment]
Thank you @csoneson 
Ther version tag would be: 1.0.6
Zenodo link: https://zenodo.org/record/4278979#.X7TdUq4o-EL
DOI: seems to be the one I entered for this publication. i.e. 10.21105/joss.02816

**Comment by csoneson** [comment]
Ah, I see. The Zenodo archive should have its own DOI, something like `10.5281/zenodo.XXXXXX` (i.e., not the one of the JOSS paper).

**Comment by PatrickRWright** [comment]
Hm... I'm a bit confused now. since the DOI tooltip for zenodo said:
```
Optional. Did your publisher already assign a DOI to your upload? If not, leave
the field empty and we will register a new DOI for you. A DOI allows others to
easily and unambiguously cite your upload. Please note that it is NOT possible
to edit a Zenodo DOI once it has been registered by us, while it is always
possible to edit a custom DOI.
```
For me this indicated to use a preexisting DOI (i.e. JOSS) if available. I tried to remove the JOSS DOI now, but saving on zenodo doesn't actually remove it. Any suggestions?

**Comment by danielskatz** [comment]
Zenodo will issue its own DOI for the deposit (which you will see once it is published "Cite as" on the lower right).  In addition, you can put other DOIs into the page where you submit to zenodo, such as references and links. These DOIs are stored in the metadata of the published article under the published DOI.

When you manually upload to Zenodo, there's a place for a DOI, which says "Optional. Did your publisher already assign a DOI to your upload? If not, leave the field empty and we will register a new DOI for you. A DOI allows others to easily and unambiguously cite your upload. Please note that it is NOT possible to edit a Zenodo DOI once it has been registered by us, while it is always possible to edit a custom DOI."  In the case of JOSS, we do not assign a DOI to the software upload, so you should leave this empty.  We will assign a DOI to the paper, which will refer to the DOI of the software upload (which is why we need you to tell us what it at this stage of the acceptance process).

**Comment by csoneson** [comment]
Thanks @danielskatz for the more extensive explanation.

@PatrickRWright - I think you may need to email Zenodo to resolve this and replace the JOSS DOI with a Zenodo-assigned one.

**Comment by PatrickRWright** [comment]
@csoneson I have gotten in touch with Zenodo and hope they can resolve this.

Thank you for the guidance.

**Comment by PatrickRWright** [comment]
@csoneson Zenodo suggested to reupload the package leaving the DOI field empty. They will then delete the old submission.

I have done this: https://zenodo.org/record/4280767#.X7Zbqa4o_MU
DOI: http://doi.org/10.5281/zenodo.4280767
Version: 1.0.6

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.4280767 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4280767" target="_blank">10.5281/zenodo.4280767</a> is the archive.

**Comment by csoneson** [comment]
@whedon set 1.0.6 as version

**Comment by whedon** [comment]
OK. 1.0.6 is the version.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by csoneson** [comment]
Thanks @PatrickRWright - the associate editor in chief on rotation will take over from here.

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1928

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1928, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9781107256644 is OK
- 10.1186/1745-6215-11-79 is OK
- 10.1038/d41586-020-00758-2 is OK
- 10.21105/joss.01686 is OK
- 10.1016/j.jbi.2019.103208 is OK
- 10.1016/j.jbi.2008.08.010 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by PatrickRWright** [comment]
Thank you a lot @csoneson this has been such a great process.

@aghaynes @markomi looks like its accepted. Thanks to both of you too for all your efforts in the project :rocket:

**Comment by PatrickRWright** [comment]
Should I run this `@whedon accept deposit=true` or is the something the associate editor needs to do?

Also I saw that the XML omits the middle names. i.e. `Alan Haynes` should be `Alan G. Haynes` and `Patrick Wright` should be `Patrick R. Wright`. Is that possible?

**Comment by danielskatz** [comment]
I'll take over from here, with a final proofreading and then the acceptance.  I'll also look at the name issue in the XML - thanks for catching it as a potential issue.

**Comment by danielskatz** [comment]
Please merge the changes in https://github.com/SwissClinicalTrialOrganisation/secuTrialR/pull/229 or let me know what you don't agree with.

**Comment by PatrickRWright** [comment]
It is merged.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1929

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1929, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/CBO9781107256644 is OK
- 10.1186/1745-6215-11-79 is OK
- 10.1038/d41586-020-00758-2 is OK
- 10.21105/joss.01686 is OK
- 10.1016/j.jbi.2019.103208 is OK
- 10.1016/j.jbi.2008.08.010 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@PatrickRWright - It turns out that Crossref only wants the given name (e.g. Alan). We omit the middle initial deliberately. But since we add the ORCID, the authors should still be uniquely identified.

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1329820163005411331) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1930
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02816](https://doi.org/10.21105/joss.02816)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @PatrickRWright (Patrick R. Wright) and co-authors!!

And thanks to @pacoramon & @sachsmc for reviewing and @csoneson for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02816/status.svg)](https://doi.org/10.21105/joss.02816)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02816">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02816/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02816/status.svg
   :target: https://doi.org/10.21105/joss.02816
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02816/status.svg)](https://doi.org/10.21105/joss.02816)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
