### ISSUE TITLE
[REVIEW]: Cellocity: A Python package for analysis of confluent cell layer dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2818]
**Submitting author:** @oftatkofta (<a href="http://orcid.org/0000-0002-8945-2665">Jens Eriksson</a>)
**Repository:** <a href="https://github.com/Oftatkofta/cellocity" target ="_blank">https://github.com/Oftatkofta/cellocity</a>
**Version:** v1.0.1
**Editor:** @jni
**Reviewer:** @rfezzani, @aplyer
**Archive:** <a href="https://doi.org/10.5281/zenodo.4475442" target="_blank">10.5281/zenodo.4475442</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/eb4e6d1a3b23dfcecf27e51c3405e7f4/status.svg)](https://joss.theoj.org/papers/eb4e6d1a3b23dfcecf27e51c3405e7f4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/eb4e6d1a3b23dfcecf27e51c3405e7f4"><img src="https://joss.theoj.org/papers/eb4e6d1a3b23dfcecf27e51c3405e7f4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/eb4e6d1a3b23dfcecf27e51c3405e7f4/status.svg)](https://joss.theoj.org/papers/eb4e6d1a3b23dfcecf27e51c3405e7f4)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Oftatkofta/cellocity" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@rfezzani & @aplyer, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jni know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Oftatkofta/cellocity">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@oftatkofta) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Oftatkofta/cellocity">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@oftatkofta) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @rfezzani, @aplyer it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41467-018-05578-7 is OK
- 10.1038/nmat4848 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/TIM.2010.2047149 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.bpj.2016.02.032 is OK
- 10.1016/j.tibtech.2018.12.001 is OK
- 10.1146/annurev.biophys.35.040405.102114 is OK
- 10.5281/zenodo.3930343 is OK

MISSING DOIs

- 10.1007/3-540-45103-x_50 may be a valid DOI for title: Two-Frame Motion Estimation Based on Polynomial Expansion

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02818/joss.02818/10.21105.joss.02818.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02818/joss.02818/10.21105.joss.02818.pdf) :page_facing_up: :point_left:

**Comment by jni** [comment]
@rfezzani @aplyer :wave: over here! :blush: Thank you for agreeing to review this paper/software! Please read the review issue description above in detail, and feel free ask me here any questions you might have about the process.

**Comment by whedon** [comment]
:wave: @aplyer, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @rfezzani, please update us on how your review is going.

**Comment by jni** [comment]
That seemed a bit blunt! :sweat_smile: @aplyer @rfezzani JOSS is testing a new "reminder" feature on reviews, please don't take it as too aggressive — it is just a kind ping to ensure things don't stall for months. :pray:

**Comment by rfezzani** [comment]
:smile: don't mind @jni, **whedon** is simply a conscientious bot :wink:

**Comment by jni** [comment]
@rfezzani @aplyer It's been a very busy month for me and I've neglected my editorial duties. 😬 Probably a busy month for you also but I just wanted to make a small ping to surface this again to your attention. 😊

**Comment by rfezzani** [comment]
You are absolutely right, I am so much busy these last few days, sorry :pray:. I will try to complete my review by the end of next week :wink:

**Comment by rfezzani** [comment]
Hi @jni, sorry again for my late answer.

`Cellocity` submission meets all JOSS requirements in terms of license, functionalities, documentation, and validation. I recommend  acceptance.

**Comment by jni** [comment]
Thank you so much @rfezzani! @aplyer, apologies if you are busy — it is a busy time! — could you please let us know if you agree with @rfezzani's assessment? I see that most but not all of your checklist is ticked, so thank you for all the work you've done so far, and I look forward to wrapping this up! 😊

**Comment by Oftatkofta** [comment]
Hello @jni! I am a bit curious if it is possible to continue the review process by maybe inviting another reviewer? It seems like @aplyer has gone AWOL.

**Comment by jni** [comment]
A great suggestion! Thanks for the ping @Oftatkofta and happy new year. I'll start looking.

**Comment by jni** [comment]
@Oftatkofta after some fruitless pursuit of alternate reviewers, @rfezzani finally helped me to track down @aplyer, who had been busier than usual but was able to finish the review — and has also recommended acceptance! 🎉 There's going to be some final checks now, and if all goes well your paper will be out in the next few hours/days!

**Comment by jni** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02818/joss.02818/10.21105.joss.02818.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02818/joss.02818/10.21105.joss.02818.pdf) :page_facing_up: :point_left:

**Comment by jni** [comment]
@whedon check references

**Comment by jni** [comment]
> MISSING DOIs
> 
> - 10.1007/3-540-45103-x_50 may be a valid DOI for title: Two-Frame Motion Estimation Based on Polynomial Expansion

@Oftatkofta could you please add that DOI to that reference? Whedon appears to be accurate here. =)

Once that's added, could you please also make a new tagged release and Zenodo archive, and report back here the version number and the Zenodo DOI?

**Comment by Oftatkofta** [comment]
I'm on it!

**Comment by Oftatkofta** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02818/joss.02818/10.21105.joss.02818.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02818/joss.02818/10.21105.joss.02818.pdf) :page_facing_up: :point_left:

**Comment by Oftatkofta** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41467-018-05578-7 is OK
- 10.1038/nmat4848 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/TIM.2010.2047149 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.bpj.2016.02.032 is OK
- 10.1016/j.tibtech.2018.12.001 is OK
- 10.1146/annurev.biophys.35.040405.102114 is OK
- 10.1007/3-540-45103-x_50 is OK
- 10.5281/zenodo.3930343 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Oftatkofta** [comment]
@jni The new release has version 1.0.1, is submitted to Zendo and given the DOI 10.5281/zenodo.4475442 whedon seems satisfied with the DOI added to the reference. 

On a personal note I would like thank you, the reviewers, and JOSS for a modern and smooth submission & review process.

**Comment by MikaelSellin** [comment]
Thanks @jni and the reviewers also from my side for your efforts and the transparent review process.

**Comment by jni** [comment]
@whedon set 10.5281/zenodo.4475442 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4475442" target="_blank">10.5281/zenodo.4475442</a> is the archive.

**Comment by jni** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by jni** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2056

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2056, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
I've suggested some minor changes in https://github.com/Oftatkofta/cellocity/pull/21 - please merge this or let me know what you disagree with

**Comment by Oftatkofta** [comment]
@danielskatz Thanks for the proof read, I have merged the edits.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2058

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2058, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41467-018-05578-7 is OK
- 10.1038/nmat4848 is OK
- 10.1109/MCSE.2011.37 is OK
- 10.1109/TIM.2010.2047149 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.bpj.2016.02.032 is OK
- 10.1016/j.tibtech.2018.12.001 is OK
- 10.1146/annurev.biophys.35.040405.102114 is OK
- 10.1007/3-540-45103-x_50 is OK
- 10.5281/zenodo.3930343 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1354790436813070338) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2059
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02818](https://doi.org/10.21105/joss.02818)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @Oftatkofta (Jens Eriksson) and co-authors!!

And thanks to @rfezzani and @aplyer for reviewing, and @jni for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02818/status.svg)](https://doi.org/10.21105/joss.02818)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02818">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02818/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02818/status.svg
   :target: https://doi.org/10.21105/joss.02818
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02818/status.svg)](https://doi.org/10.21105/joss.02818)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
