### ISSUE TITLE
[PRE REVIEW]: AltaiPony - Flare science in Kepler, K2 and TESS light curves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2819]
**Submitting author:** @ekaterinailin (<a href="http://orcid.org/0000-0002-6299-7542">Ekaterina Ilin</a>)
**Repository:** <a href="https://github.com/ekaterinailin/AltaiPony" target ="_blank">https://github.com/ekaterinailin/AltaiPony</a>
**Version:** v1.0
**Editor:** @dfm
**Reviewers:** @afeinstein20, @mrtommyb
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ekaterinailin. **Currently, there isn't an JOSS editor assigned** to your paper.

@ekaterinailin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2819 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.39 s (120.0 files/s, 28166.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          22           1308           2293           3272
reStructuredText                12            211            107            233
Jupyter Notebook                 7              0           3224            225
JavaScript                       2              7             16             50
DOS Batch                        1              8              1             26
Markdown                         1              5              0             11
make                             1              4              6              9
YAML                             1              4              0              9
-------------------------------------------------------------------------------
SUM:                            47           1547           5647           3835
-------------------------------------------------------------------------------


Statistical information for the repository 'e99e6ffc642acf443c5fb1de' was
gathered on 2020/11/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ekaterina Ilin                 118          7155           2898           60.54
Geert Barentsen                  1             5              5            0.06
ekaterina                       28           874            336            7.29
ekaterinailin                   64          3716           1594           31.98
gully                            1            14              9            0.14

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ekaterina Ilin             1187           16.6         24.1               13.65
Geert Barentsen               2           40.0         24.7                0.00
ekaterinailin              5755          154.9          7.6               13.68
gully                         2           14.3         24.8                0.00
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch josspaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch josspaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02819/joss.02819/10.21105.joss.02819.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02819/joss.02819/10.21105.joss.02819.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@ekaterinailin thanks for this submission. I'll be helping to find a handling editor. 

I the mean time, can you clarify if this submission is associated with an AAS paper?

**Comment by Kevin-Mattheus-Moerman** [comment]
@dfm @harpolea @arfon @xuanxu could one of you handle this submission?

**Comment by dfm** [comment]
Sure - I'm happy to edit this one!

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by ekaterinailin** [comment]
> @ekaterinailin thanks for this submission. I'll be helping to find a handling editor.
> 
> In the mean time, can you clarify if this submission is associated with an AAS paper?

No, it is not associated with an AAS paper.

Working up from the bottom of the reviewers list for suggestions: dflemin3, christinahedges

**Comment by dfm** [comment]
@afeinstein20 has agreed to review. Thanks Adina! We'll get things started once we have a second reviewer.

**Comment by dfm** [comment]
@whedon assign @afeinstein20 as reviewer

**Comment by whedon** [comment]
OK, @afeinstein20 is now a reviewer

**Comment by dfm** [comment]
And we have a second reviewer: @mrtommyb. Thanks Tom!

I'll add @mrtommyb as a reviewer then get the main review thread started.

All: please let me know if you have any questions as the review progresses - I'm here to help!

**Comment by dfm** [comment]
@whedon add @mrtommyb as reviewer

**Comment by whedon** [comment]
OK, @mrtommyb is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2845.
