### ISSUE TITLE
[REVIEW]: Kindel: indel-aware consensus for nucleotide sequence alignments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#282]
**Submitting author:** @bede (<a href="http://orcid.org/0000-0002-3480-3819">Bede Constantinides</a>)
**Repository:** <a href="https://github.com/bede/kindel" target ="_blank">https://github.com/bede/kindel</a>
**Version:** v0.2.0
**Editor:** @mgymrek
**Reviewer:** @genomematt
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.826723" target="_blank">10.5281/zenodo.826723</a>

## Status

[![status](http://joss.theoj.org/papers/117efd1fc35bb2011311f73d3fa0b545/status.svg)](http://joss.theoj.org/papers/117efd1fc35bb2011311f73d3fa0b545)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/117efd1fc35bb2011311f73d3fa0b545"><img src="http://joss.theoj.org/papers/117efd1fc35bb2011311f73d3fa0b545/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/117efd1fc35bb2011311f73d3fa0b545/status.svg)](http://joss.theoj.org/papers/117efd1fc35bb2011311f73d3fa0b545)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bede/kindel" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bede/kindel">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.0)?
- [x] **Authorship:** Has the submitting author (@bede) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @genomematt it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by genomematt** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by genomematt** [comment]
Looks quite good.  Only issues are:
The lack of a clear example usage.  I would recommend something that shows some input and output.  (Probably easiest to do by just working through an analysis in an ipynb)

The paper is quite sparse.  It definitely needs to cite ococo like the main page does.  A simplified diagram example of input and output would help a lot, especially for someone slightly off field.

There are guidelines for reporting bugs and support, but no guidelines for contributing.   See other JOSS articles for examples.

**Comment by bede** [comment]
Thanks for your comments Matt. I'll reply again once I've incorporated the following:
- Example usage (Jupyter notebook or otherwise)
- Additional detail to the paper, perhaps including a diagrammatic explanation of usage
- Contribution guidelines

**Comment by bede** [comment]
I've done the following:
- Created an example usage notebook
- Added detail to the paper, including two diagrams
- Reviewed a handful of accepted JOSS papers, and added a contribution section to the README

Are you happy with the changes @genomematt ?

**Comment by genomematt** [comment]
This now ticks all the boxes.  I think we are ready to accept @mgymrek

**Comment by gymreklab** [comment]
This looks great to me. @arfon I think this is ready to go.

**Comment by arfon** [comment]
@bede - Could you move the references you currently have in the `paper.md` file into a `paper.bib` file and cite them directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by bede** [comment]
@arfon Thanks! Now sorted.

I'd seen a lot of JOSS submissions using hardcoded citations and just followed suit. This is much cleaner.

**Comment by bede** [comment]
@arfon Also, is it possible to revise the text on this page? http://joss.theoj.org/papers/117efd1fc35bb2011311f73d3fa0b545

**Comment by arfon** [comment]
> @arfon Also, is it possible to revise the text on this page? 

This will be replaced by your paper content once we've accepted the paper.

Thanks for making the edits to `paper.md`, take a look at the compiled PDF here [10.21105.joss.00282.pdf](https://github.com/openjournals/joss-reviews/files/1129066/10.21105.joss.00282.pdf)

I'm wondering if you should remove the sections (`Core functionality` etc) and just replace these with slightly longer captions? The flow of the document in Pandoc is pretty weird. Smaller figures might help too.

**Comment by bede** [comment]
@arfon Thanks for your comments. I (think I) now understand how Rmd citations and figure captions work. Things should look better next time you compile.

**Comment by arfon** [comment]
> @arfon Thanks for your comments. I (think I) now understand how Rmd citations and figure captions work. Things should look better next time you compile.

That's looking good. Thanks. At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by bede** [comment]
Thanks – here it is: https://doi.org/10.5281/zenodo.826723

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.826723 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.826723" target="_blank">10.5281/zenodo.826723</a> is the archive.

**Comment by arfon** [comment]
@genomematt - many thanks for your review here and to @mgymrek for editing this submission ✨ 

@bede - your paper is now accepted into JOSS. Your DOI is http://dx.doi.org/10.21105/joss.00282 ⚡️ 🚀 💥

**Comment by bede** [comment]
Arfon, Matt and Melissa, thank you all for your time.
