### ISSUE TITLE
[PRE REVIEW]: h5fortran: object-oriented polymorphic Fortran interface for HDF5 file IO

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2820]
**Submitting author:** @scivision (<a href="http://orcid.org/0000-0002-1637-6526">Michael Hirsch</a>)
**Repository:** <a href="https://github.com/geospace-code/h5fortran" target ="_blank">https://github.com/geospace-code/h5fortran</a>
**Version:** v3.4.1
**Editor:** @pdebuyl
**Reviewers:** @milancurcic, @bast
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @scivision. **Currently, there isn't an JOSS editor assigned** to your paper.

@scivision if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.15 s (617.8 files/s, 52228.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                      40           1143            764           2091
CMake                           18            260            179           1522
Markdown                         8            247              0            524
Python                           4             66             40            204
YAML                             8             52             41            156
NAnt script                      4             23              0            100
TeX                              1              9              0             81
JSON                             1              0              0             35
C++                              1             10              0             17
C                                1             10              0             17
INI                              1              0              0              6
TOML                             1              0              0              5
C/C++ Header                     2              2              0              4
-------------------------------------------------------------------------------
SUM:                            90           1822           1024           4762
-------------------------------------------------------------------------------


Statistical information for the repository '96b842ed2d9c4deaa5f1c4c0' was
gathered on 2020/11/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Michael Hirsch                  24           611            557           72.59
Michael Hirsch, Ph.D             9           365             76           27.41

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael Hirsch              343           56.1          4.2                7.87
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.3733569 is OK
- 10.5281/zenodo.3718418 is OK
- 10.5281/zenodo.3731716 is OK
- 10.1029/2018GL081569 is OK
- 10.1145/1966895.1966900 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02820/joss.02820/10.21105.joss.02820.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02820/joss.02820/10.21105.joss.02820.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @scivision! Thanks for your submission. The editorial board is a bit borderline about your submission as to whether it is in scope as research software and is more than a thin wrapper, though everyone thinks it is clearly very useful. However, enough people support it as in scope to move forward with review. So, let's proceed!

**Comment by kthyng** [comment]
@melissawm and @pdebuyl would either of you like to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @melissawm as editor

**Comment by whedon** [comment]
@melissawm has been invited to edit this submission.

**Comment by kthyng** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@milancurcic @bast can you review the article "h5fortran: object-oriented polymorphic Fortran interface for HDF5 file IO" for JOSS?

**Comment by milancurcic** [comment]
I'm in.

**Comment by bast** [comment]
Yes I would love to. Thanks!

**Comment by pdebuyl** [comment]
That was fast :-) Thank you both.

**Comment by pdebuyl** [comment]
@whedon assign @milancurcic as reviewer

**Comment by whedon** [comment]
OK, @milancurcic is now a reviewer

**Comment by pdebuyl** [comment]
@whedon add @bast as reviewer

**Comment by whedon** [comment]
OK, @bast is now a reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2842.
