### ISSUE TITLE
[PRE REVIEW]: PyCTRSA: A Python package for cross-temporal representational similarity analysis-based E/MEG decoding

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2821]
**Submitting author:** @ZitongLu1996 (<a href="http://orcid.org/0000-0002-7953-6742">Zitong Lu</a>)
**Repository:** <a href="https://github.com/ZitongLu1996/PyCTRSA" target ="_blank">https://github.com/ZitongLu1996/PyCTRSA</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ZitongLu1996. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @cMadan.

@ZitongLu1996 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (220.8 files/s, 26294.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          32            488            699            925
XML                              6              0              0            693
Jupyter Notebook                 5              0           1832            649
Markdown                         2             43              0             80
TeX                              1              9              0             60
-------------------------------------------------------------------------------
SUM:                            46            540           2531           2407
-------------------------------------------------------------------------------


Statistical information for the repository 'b34f7b707725234cca14a31e' was
gathered on 2020/11/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ZitongLu1996                     2          3992              5          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
ZitongLu1996               3987           99.9          0.0                9.83
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2020.03.25.008086 is OK

MISSING DOIs

- 10.1016/j.tics.2006.07.005 may be a valid DOI for title: Beyond Mind-Reading: Multi-Voxel Pattern Analysis of fMRI Data
- 10.3389/neuro.06.004.2008 may be a valid DOI for title: Representational Similarity Analysis – Connecting the Branches of Systems Neuroscience
- 10.1109/mcse.2011.37 may be a valid DOI for title: The NumPy array: a structure for efficient numerical computation
- 10.1109/mcse.2007.55 may be a valid DOI for title: Matplotlib: A 2D Graphics Environment
- 10.1523/jneurosci.2860-17.2017 may be a valid DOI for title: Dissociable Decoding of Spatial Attention and Working Memory from EEG Oscillations and Sustained Potentials

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02821/joss.02821/10.21105.joss.02821.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02821/joss.02821/10.21105.joss.02821.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ZitongLu1996 I have flagged this submission for scope review by our editorial board (standard for submissions in the order of 1000 lines of code). This review will take about a week.

**Comment by kthyng** [comment]
Hi @ZitongLu1996. Thank you for your JOSS submission. Unfortunately, the editorial board has determined that it is too narrow in scope for JOSS to review it - see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort. We encourage you to consider JOSS at a later time if more effort and code goes into this software, or alternatively, consider publishing the software to Zenodo to get a DOI that users can cite.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
