### ISSUE TITLE
[PRE REVIEW]: PySPOD: A Python package for Spectral Proper Orthogonal Decomposition (SPOD)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2822]
**Submitting author:** @mengaldo (<a href="http://orcid.org/0000-0002-0157-5477">Gianmarco Mengaldo</a>)
**Repository:** <a href="https://github.com/mengaldo/PySPOD" target ="_blank">https://github.com/mengaldo/PySPOD</a>
**Version:** v0.3
**Editor:** @eloisabentivegna
**Reviewers:** @albertonogueira, @joao-l-s-almeida, @jdmoorman
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mengaldo. **Currently, there isn't an JOSS editor assigned** to your paper.

@mengaldo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.89 s (80.0 files/s, 39100.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      14           2289           2323           8445
HTML                            12           1734             44           4575
Python                          24            814           1301           3353
SVG                              1              0              0           2671
CSS                              5            183             43            722
Jupyter Notebook                 7              0           4829            564
Markdown                         2             82              0            255
reStructuredText                 2             94             68            176
YAML                             2             11             10             55
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            71           5219           8626          20851
-------------------------------------------------------------------------------


Statistical information for the repository '0a6b9a2db80e74d4f97642a7' was
gathered on 2020/11/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Gianmarco Mengaldo              69         26810           7800           98.58
mengaldo                         1             7            492            1.42

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Gianmarco Mengaldo        18525           69.1          0.1               16.97
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2822 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch papers/JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch papers/JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02822/joss.02822/10.21105.joss.02822.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02822/joss.02822/10.21105.joss.02822.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@harpolea @eloisabentivegna @VivianePons could one of you handle this submission? Thanks!

**Comment by eloisabentivegna** [comment]
I can!

**Comment by eloisabentivegna** [comment]
@whedon assign @eloisabentivegna as editor

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by eloisabentivegna** [comment]
@jdmoorman, would you be available to review this submission?

**Comment by mengaldo** [comment]
Dear Eloisa, I have no particular suggestions for reviewers. Please, let me know if you need any additional information to proceed with the review. Best, Gianmarco

**Comment by eloisabentivegna** [comment]
> Dear Eloisa, I have no particular suggestions for reviewers. Please, let me know if you need any additional information to proceed with the review. Best, Gianmarco

Thanks, @mengaldo! One reviewer has agreed to work on this submission, but we will need at least another one. Please bear with me for a little longer. Thanks!

**Comment by eloisabentivegna** [comment]
@whedon add @albertonogueira as reviewer

**Comment by whedon** [comment]
OK, @albertonogueira is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon add @joao-l-s-almeida as reviewer

**Comment by whedon** [comment]
OK, @joao-l-s-almeida is now a reviewer

**Comment by mengaldo** [comment]
@eloisabentivegna Thank you!

**Comment by jdmoorman** [comment]
> @jdmoorman, would you be available to review this submission?

I am available if you need another reviewer

**Comment by eloisabentivegna** [comment]
> I am available if you need another reviewer

Thanks, @jdmoorman! I will add you as well.

**Comment by eloisabentivegna** [comment]
@whedon add @jdmoorman as reviewer

**Comment by whedon** [comment]
OK, @jdmoorman is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2862.

**Comment by albertonogueira** [comment]
@Joao-L-S-Almeida and @albertonogueira are testing PySPOD in NASA's GMAO dataset to check the library capabilities. We started filling in the checklist review.

**Comment by eloisabentivegna** [comment]
@albertonogueira, @Joao-L-S-Almeida, the review will now continue on issue #2862. Could you leave your comments there?
