### ISSUE TITLE
[REVIEW]: spaghetti: spatial network analysis in PySAL

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2826]
**Submitting author:** @jGaboardi (<a href="http://orcid.org/0000-0002-4776-6826">James Gaboardi</a>)
**Repository:** <a href="https://github.com/pysal/spaghetti" target ="_blank">https://github.com/pysal/spaghetti</a>
**Version:** v1.5.8
**Editor:** @usethedata
**Reviewers:** @martibosch, @usethedata
**Archive:** <a href="https://doi.org/10.5281/zenodo.4898079" target="_blank">10.5281/zenodo.4898079</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/52b8d0c81bbf311465b45bfc26379e74/status.svg)](https://joss.theoj.org/papers/52b8d0c81bbf311465b45bfc26379e74)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/52b8d0c81bbf311465b45bfc26379e74"><img src="https://joss.theoj.org/papers/52b8d0c81bbf311465b45bfc26379e74/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/52b8d0c81bbf311465b45bfc26379e74/status.svg)](https://joss.theoj.org/papers/52b8d0c81bbf311465b45bfc26379e74)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pysal/spaghetti" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@martibosch, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @usethedata know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pysal/spaghetti">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jGaboardi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pysal/spaghetti">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jGaboardi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @martibosch it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/ijgi4020815 is OK
- 10.1111/gean.12211 is OK
- 10.5281/zenodo.1343650 is OK
- 10.1111/j.0016-7363.2005.00674.x is OK
- 10.1002/9781119967101 is OK
- 10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.5281/zenodo.3379659 is OK
- 10.5281/zenodo.3669853 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.5281/zenodo.1472807 is OK
- 10.1007/s11067-018-9427-9 is OK

MISSING DOIs

- 10.1007/978-3-642-03647-7_11 may be a valid DOI for title: PySAL: A Python Library of Spatial Analytical Methods

INVALID DOIs

- None
```

**Comment by usethedata** [comment]
Still working on getting the second reviewer.  @martibosch -- you're free to go ahead with your review.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: :point_left:

**Comment by usethedata** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: :point_left:

**Comment by jGaboardi** [comment]
@usethedata
* I am wondering if this is still on track or if there is anything I can do to assist?
* I am planning on doing a New Year release. Do I need to update anything here in the review once I do that?

**Comment by martibosch** [comment]
Hello all,

I am sorry for the delay in reviewing this submission. I am at the end of my thesis and this ended up buried in a pile of "TODOs". If this works for everybody, will review the submission by the end of this week. Or should I wait for the amendments that @jGaboardi is planning to include? How do we proceed regarding that, @usethedata?

Best,
Martí

**Comment by jGaboardi** [comment]
> Or should I wait for the amendments that @jGaboardi is planning to include?

The release is a scheduled one to coincide with the biannual PySAL federation release. It will not include any change to the actual code-base, just admin/maintenance adjustments for testing, docs, etc. I will get that out today, which will be `v1.5.4`.

**Comment by martibosch** [comment]
This would be all from my side. Looking forward to hear back from the authors. Let me clear out again that my intention is not to question the criteria of the authors (since they probably know better than me why they have made such choices), but rather ensure that the raised issues have been considered.

Best,
Martí

**Comment by jGaboardi** [comment]
Thanks for the thorough review, @martibosch. We will go through the issue you raised and respond ASAP.

@slumnitz @sjsrey

**Comment by usethedata** [comment]
@martibosch -- Thanks.
@jGaboardi -- My apologies for being missing in action on this.  The last several weeks have been a bit challenging.  I'll set the version on the software for the paper as one of the last things in the review process, so there aren't issues there.  I'll work on the second reviewer shortly.

**Comment by usethedata** [comment]
@jGaboardi I've had a couple more declines on reviewers.  As it turns out, however, I'm stepping away from being a JOSS Topic editor and returning to just being a reviewer.  Ping me here when you've addressed, as you feel appropriate, the items @martibosch has listed, and I'll do the second review.

**Comment by usethedata** [comment]
@whedon add @usethedata as reviewer

**Comment by whedon** [comment]
OK, @usethedata is now a reviewer

**Comment by arfon** [comment]
:wave: folks, I just wanted to check in to see how things are coming along here?

**Comment by usethedata** [comment]
The issues raised by the first review appear to still be open.  When they're addressed, either as done or won't do, then I can go through my review.

**Comment by jGaboardi** [comment]
@arfon & @usethedata 

Sorry for long delay. Have had several personal issues come up over the past 2 months. @slumnitz and I have started back with the responses to the first review and I hope to get that completed within the next 2 weeks.

**Comment by usethedata** [comment]
Got it.  Personal issues can have an outsized effect these days.  Very much understood and I hope things have returned to a good state for you.

**Comment by jGaboardi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: :point_left:

**Comment by jGaboardi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: :point_left:

**Comment by jGaboardi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: :point_left:

**Comment by jGaboardi** [comment]
@martibosch @usethedata @arfon We have wrapped up our responses to the issues raised by @martibosch, and implemented changes in the `spaghetti` package itself and in the manuscript text. I was unsure about leaving the issues opened by @martibosch as they are or closing them, so I left them open.

On another topic, I was unable to figure out how to reduce figure sizes elegantly in MarkDown, but I think both figures in the manuscript need to be smaller (pending your review & decision).

@slumnitz @sjsrey

**Comment by jGaboardi** [comment]
@whedon generate pdf (cleaning up references and citations)

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
> On another topic, I was unable to figure out how to reduce figure sizes elegantly in MarkDown, but I think both figures in the manuscript need to be smaller (pending your review & decision).

@jGaboardi – Figure sizes can be customized by adding an optional second parameter: 

```
![Caption for example figure.](figure.png){ width=20% }
```

**Comment by jGaboardi** [comment]
> > On another topic, I was unable to figure out how to reduce figure sizes elegantly in MarkDown, but I think both figures in the manuscript need to be smaller (pending your review & decision).
> 
> @jGaboardi – Figure sizes can be customized by adding an optional second parameter:
> 
> ```
> ![Caption for example figure.](figure.png){ width=20% }
> ```

@arfon Thanks for this. Not sure how I missed it.

**Comment by jGaboardi** [comment]
@whedon generate pdf (reducing figure size by 50%)

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: :point_left:

**Comment by jGaboardi** [comment]
@whedon generate pdf (cleaning up references and citations [2])

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: :point_left:

**Comment by jGaboardi** [comment]
I'll go ahead and close the issues that @martibosch opened as we are "done" with them. If I am jumping the gun here, I'm happy to reopen.

[#574](https://github.com/pysal/spaghetti/issues/574), [#575](https://github.com/pysal/spaghetti/issues/575), [#576](https://github.com/pysal/spaghetti/issues/576), [#577](https://github.com/pysal/spaghetti/issues/577), [#578](https://github.com/pysal/spaghetti/issues/578), [#580](https://github.com/pysal/spaghetti/issues/580), [#581](https://github.com/pysal/spaghetti/issues/581), [#582](https://github.com/pysal/spaghetti/issues/582), [#583](https://github.com/pysal/spaghetti/issues/583)

**Comment by arfon** [comment]
@martibosch, @usethedata - could you come and take another look at this submission and see if the author's updates are satisfactory to you?

**Comment by usethedata** [comment]
I've completed my review and am satisfied.

**Comment by martibosch** [comment]
Hello all. First of all my apologies for my delay - these last month with the end of my thesis have been quite busy.

all my comments have been addressed and I would just like to suggest a final iteration to make the current statement of need as synthetic as possible - to that end, I have reopened [#575](https://github.com/pysal/spaghetti/issues/575). After this, I believe the manuscript can go to publication.

Best,
Martí

**Comment by arfon** [comment]
Thanks @martibosch - could you also update your review checklist based on your latest review?

**Comment by martibosch** [comment]
done! (sorry I forgot)

**Comment by jGaboardi** [comment]
@martibosch @usethedata @arfon I believe that all concerns have now been addressed in this review.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@jGaboardi – At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by jGaboardi** [comment]
@arfon I have cut a fresh release and Zenodo archive with the following info. Let me know if I did this correctly.
| title | spaghetti: spatial network analysis in PySAL |
|  --- | --- |
| version | 1.5.8 |
| release | https://github.com/pysal/spaghetti/releases/tag/v1.5.8 |
|  doi | https://zenodo.org/record/4898079 |

@slumnitz @sjsrey looks like things are wrapping up here!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4898079 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4898079" target="_blank">10.5281/zenodo.4898079</a> is the archive.

**Comment by arfon** [comment]
@whedon set v1.5.8 as version

**Comment by whedon** [comment]
OK. v1.5.8 is the version.

**Comment by arfon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/ijgi4020815 is OK
- 10.1111/gean.12211 is OK
- 10.5281/zenodo.1343650 is OK
- 10.1111/j.0016-7363.2005.00674.x is OK
- 10.1002/9781119967101 is OK
- 10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.5281/zenodo.3379659 is OK
- 10.5281/zenodo.4569086 is OK
- 10.5281/zenodo.4572994 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.5281/zenodo.1472807 is OK
- 10.1007/s11067-018-9427-9 is OK
- 10.1002/9780470549094.ch5 is OK
- 10.21105/joss.01882 is OK
- 10.5281/zenodo.3265190 is OK

MISSING DOIs

- 10.1007/978-3-642-03647-7_11 may be a valid DOI for title: PySAL: A Python Library of Spatial Analytical Methods

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2357

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2357, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@jGaboardi – please merge this PR which makes a small number of formatting fixes and removes a duplicate sentence https://github.com/pysal/spaghetti/pull/626.

**Comment by jGaboardi** [comment]
@arfon pysal/spaghetti#626 is now merged.

**Comment by jGaboardi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02826/joss.02826/10.21105.joss.02826.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/ijgi4020815 is OK
- 10.1111/gean.12211 is OK
- 10.5281/zenodo.1343650 is OK
- 10.1111/j.0016-7363.2005.00674.x is OK
- 10.1002/9781119967101 is OK
- 10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.5281/zenodo.3379659 is OK
- 10.5281/zenodo.4569086 is OK
- 10.5281/zenodo.4572994 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.5281/zenodo.1472807 is OK
- 10.1007/s11067-018-9427-9 is OK
- 10.1002/9780470549094.ch5 is OK
- 10.21105/joss.01882 is OK
- 10.5281/zenodo.3265190 is OK

MISSING DOIs

- 10.1007/978-3-642-03647-7_11 may be a valid DOI for title: PySAL: A Python Library of Spatial Analytical Methods

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2358

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2358, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1400700298956521472) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2359
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02826](https://doi.org/10.21105/joss.02826)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@martibosch, @usethedata – many thanks for your reviews here and to @usethedata for editing too! JOSS relies upon the volunteer efforts of people like you and we simply wouldn't be able to do this without you ✨ 

On a personal note, thanks to @usethedata who is stepping down from the JOSS editorial team. Thanks Bruce for all of your help making JOSS the success it is 💖 

@jGaboardi – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02826/status.svg)](https://doi.org/10.21105/joss.02826)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02826">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02826/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02826/status.svg
   :target: https://doi.org/10.21105/joss.02826
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02826/status.svg)](https://doi.org/10.21105/joss.02826)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
