### ISSUE TITLE
[REVIEW]: Omniscape.jl: Software to predict omni-directional landscape connectivity

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2829]
**Submitting author:** @vlandau (<a href="http://orcid.org/0000-0001-9290-9438">Vincent Landau</a>)
**Repository:** <a href="https://github.com/Circuitscape/Omniscape.jl" target ="_blank">https://github.com/Circuitscape/Omniscape.jl</a>
**Version:** v0.4.4
**Editor:** @melissawm
**Reviewer:** @juliohm, @tpoisot
**Archive:** <a href="https://doi.org/10.5281/zenodo.4466323" target="_blank">10.5281/zenodo.4466323</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/735ea484dee8a0ab28f10183aa420d77/status.svg)](https://joss.theoj.org/papers/735ea484dee8a0ab28f10183aa420d77)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/735ea484dee8a0ab28f10183aa420d77"><img src="https://joss.theoj.org/papers/735ea484dee8a0ab28f10183aa420d77/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/735ea484dee8a0ab28f10183aa420d77/status.svg)](https://joss.theoj.org/papers/735ea484dee8a0ab28f10183aa420d77)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Circuitscape/Omniscape.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@juliohm & @tpoisot, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @melissawm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Circuitscape/Omniscape.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@vlandau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Circuitscape/Omniscape.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@vlandau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @juliohm, @tpoisot it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.0014-3820.2006.tb00500.x is OK
- 10.1137/141000671 is OK
- 10.1890/07-1861.1 is OK
- 10.1111/cobi.13230 is OK
- 10.21105/jcon.00058 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
👋🏼 @vlandau @juliohm @tpoisot this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#2829` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@melissawm) if you have any questions/concerns.

**Comment by vlandau** [comment]
@melissawm I slightly adjusted the title immediately after submitting a while back -- will that be reflected if/when the submission is accepted and published? Just wanted to double check. Thanks!

**Comment by melissawm** [comment]
Yes, the paper should be published under the new title, but I might need to check this upon acceptance. Can you please remind me to do that, just in case? :) Thanks!

**Comment by vlandau** [comment]
Yes, will do. Thanks! :slightly_smiling_face:

**Comment by juliohm** [comment]
@vlandau can you please provide an example in the documentation that can be run easily? The example provided depends on  a file that is not available. Also, can you plot the output of this example in the documentation? Ideally this example should come as one of the first things in your docs before you even start explaining the algorithm.

Also, can you please add a statement of need explaining why this functionality is important, and how other packages from other languages may provide similar functionality?

**Comment by tpoisot** [comment]
I concur with @juliohm  - it would be good to have a fully runnable example, and the results shown in the paper.

**Comment by tpoisot** [comment]
@melissawm I can't edit the comment at the top (probably because I am not assigned)

**Comment by vlandau** [comment]
@juliohm yes definitely! I tried to get at the importance of the functionality of the package in the second paragraph in the motivation section -- I explain the value of the Omniscape algorithm, how it differs from the similar package "Circuitscape.jl", and that until now there was not a software package implementing it. Should I just shift that to its own "Statement of Need" section?

**Comment by juliohm** [comment]
I think I'm missing the context here. Someone coming for the first time in
the subject will wonder why ominiscape ? What problems it addresses? You
need to show the potential users what it is about and how the features are
used in practical applications.

**Comment by vlandau** [comment]
@juliohm okay thanks, I'll elaborate on that a bit.

**Comment by vlandau** [comment]
@juliohm I gave it a shot in the latest commit, thanks!

**Comment by vlandau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: :point_left:

**Comment by vlandau** [comment]
Working on adding a workable example next.

**Comment by vlandau** [comment]
@juliohm @tpoisot please see the new [Examples section](https://docs.circuitscape.org/Omniscape.jl/latest/examples/#Examples) in the docs. Following the example set by other Julia packages' documentation, I created a dedicated section for examples and linked to it in both the table of contents and the User Guide.

**Comment by melissawm** [comment]
@whedon re-invite @tpoisot as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@tpoisot please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by melissawm** [comment]
@tpoisot please accept the invitation and let me know if that solves the issue. Thanks!

**Comment by juliohm** [comment]
@vlandau the example section you linked could be improved. Imagine that you are explaining this subject to someone that never heard of connectivity maps before. You need to plot the input images, display the entries of the resistance table, and how they can be interpreted, and finally display the result of the `run_omniscape` function, ideally without using a file, but instead the method with arguments. The easier you make the life of the reader, the more they will appreciate your work. Can you refactor the example like that?

**Comment by vlandau** [comment]
@juliohm thanks for the feedback -- I can add those details, and good idea to use the alternative method instead of the INI file -- then the only thing that needs to be downloaded is the land cover data. I'll post back here when I have made a second pass.

**Comment by vlandau** [comment]
Hi @juliohm and @tpoisot -- I've updated the example in the documentation to be much more thorough. I have not included it in the paper yet since I'm at (or over) the soft 1000 word limit for JOSS papers and the docs are linked in the paper, but happy to add it if you two prefer that. [Here](https://docs.circuitscape.org/Omniscape.jl/latest/examples/#Forest-connectivity-in-central-Maryland) is the expanded example. Thanks!

**Comment by juliohm** [comment]
I still miss the input image and the intermediate results of the example.
Are you aware that Documenter.jl allows you to run code directly? You don't
need to include code snippets and copy paste results. Just add the actual
script section by section and the results will be shown. Check the
GeoStats.jl docs for examples. In particular the Basic Worfklow section.

**Comment by vlandau** [comment]
@juliohm Yeah I was aware of that but had been trying to avoid that since the example takes a while to run on Travis workers. I totally missed the request to see a plot of the input landcover data! Sorry about that. I'm not sure what you mean about intermediate results, though?

**Comment by juliohm** [comment]
By intermediate results I mean the input image and any intermediate output
produced. If the example takes a long time to run you probably need to
reduce the image? This is supposed to be a small toy example to give users
an idea of what is happening. It doesn't need to be an actual real world
application with a large image. Makes sense?

**Comment by vlandau** [comment]
Okay -- I'll reduce the image size, and will have Documenter.jl run the code directly and have it show all of the REPL outputs. I'll let you know when it's done. Thanks!

**Comment by vlandau** [comment]
@juliohm do you prefer `@repl` blocks or `@example` blocks? I see you use the former in GeoStats.jl docs.

**Comment by juliohm** [comment]
I think @example blocks are fine. As soon as the message is clear it
doesn't matter really.

**Comment by vlandau** [comment]
@juliohm @tpoisot [here]() is the latest iteration of the example. @juliohm, I ended up needing to add the plots as figures (saved in the docs directory before hand) because I was running into various issues when trying to plot them dynamically (figures being too small, Documenter hanging at the plot steps, etc). Hopefully this is getting closer! :slightly_smiling_face:

**Comment by juliohm** [comment]
Awesome @vlandau , much better! I could finally understand the expected output :ok_hand: 

I will proceed with the review now.

**Comment by juliohm** [comment]
Regarding the Documenter hanging at the plot steps, perhaps you are experiencing the same issue as I am with the latest stable release of Plots.jl? https://github.com/JuliaPlots/Plots.jl/issues/3164 Comment there if you can reproduce the issue. Otherwise just ignore this comment.

**Comment by juliohm** [comment]
![image](https://user-images.githubusercontent.com/3345261/101531088-888d9580-3971-11eb-8160-c80b620ce41e.png)

You claim 3 different outputs in the section above. Can you please show this functionality in the example as well? Would it be easy to produce the two other optional outputs?

**Comment by juliohm** [comment]
Before I continue with the review of the paper, please consider addressing the two issues raised in previous comments about the package documentation:

1. A clear statement of need must be present in the very beginning of the documentation. Your documentation is currently starting with the description of an algorithm without any motivation or description of the problem being solved. Add a simple sentence like "In environmental sciences, ecology, etc, it is often important to discover or quantify connectivity of forests. This task has various challenges and this package is a possible solution to this." Then, after you state the problem you are addressing, you can jump to the example. I don't think that describing the algorithm is the first thing an end user wants. Keep in mind that the audience of a documentation is mostly interested in knowing if the package has a set of features that solves their problem. Only a few people will devote time to reading the algorithm explanation and an even smaller fraction of people will try to read the papers you cited.

2. Make sure that the example covers the full functionality of the package. Your example is must improved compared to previous versions but it still doesn't show the optional outputs described in the docs. I'd try to extend the example to show these outputs and comment on how they can be used in practice.

**Comment by vlandau** [comment]
> Would it be easy to produce the two other optional outputs?

Yes definitely! I can work on that this week. I'll also add a statement of need to the landing page of the docs. Additional examples may be included in the future, so if it is okay I'll leave the examples in a dedicated section and provide a link to that section immediately following the statement of need.

**Comment by juliohm** [comment]
That is fine. Make sure that the links are emphasized and that the
algorithm explanation is a bonus for the curious reader. This will improve
the user/reader experience.

Em ter., 8 de dez. de 2020 às 16:48, Vincent Landau <
notifications@github.com> escreveu:

**Comment by vlandau** [comment]
Will do. Thanks all this feedback so far. It has been super helpful so far and is making for MUCH better docs.

**Comment by vlandau** [comment]
@juliohm @tpoisot finally got to updating the docs to reflect the comments above!

**Comment by juliohm** [comment]
Very nice! The documentation is now targeting the right audience! Like how you explained succinctly the work in the first paragraph of the docs, still providing reference and links to other sections for more details. That is it 💯 

Continuing with the review...

**Comment by juliohm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: :point_left:

**Comment by juliohm** [comment]
Review comments for paper:

![image](https://user-images.githubusercontent.com/3345261/102064459-146e4a00-3dd6-11eb-9436-444044825ac2.png)

![image](https://user-images.githubusercontent.com/3345261/102064595-42ec2500-3dd6-11eb-8817-55dc474656ed.png)

The comma in `"cores, "` should probably go outside the double quotes?

Overall, I am missing references to alternative approaches to the connectivity map problem, and missing how the circuit-theoretic approach fits into a broader category of methods. If you could maybe cite different packages from other languages doing something similar, that would already help. Are there Python, R, ... packages for connectivity maps?

**Comment by vlandau** [comment]
@juliohm [commas go inside quotes](https://style.mla.org/punctuation-and-quotation-marks/). There are no "standard" software packages that I know of. I think people likely just use their favorite graph packages or GIS plugins to compute least cost paths or corridors. I'll add one or two additional references and a sentence about least cost paths so the reader at least knows where to look!

**Comment by vlandau** [comment]
@juliohm I've added a mention of the other predominant modeling approach (least-cost paths) as well as a citation.

**Comment by vlandau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: :point_left:

**Comment by juliohm** [comment]
Thank you @vlandau ! My review is concluded 🎉 

Really nice work and contribution to the Julia ecosystem 💯 👌🏽

Cheers,
-Julio

**Comment by vlandau** [comment]
Thank you so much @juliohm, for the thorough review and helpful comments!

**Comment by tpoisot** [comment]
I can't seem to edit the comment at the top - that being said, I have used Omniscape extensively, and there is no doubt that it is production-ready, efficient, and user-friendly. If anything, the current paper is selling the software short a little bit. Omniscape can be deployed on HPC to really benefit from the built-in multi-threading, and the variety of input/output formats is really important to mention.

I would also show one map with a full Omniscape result, to see a quick illustration of what the different components of the output are.

**Comment by melissawm** [comment]
@tpoisot let's try this once more. If even after accepting the invitation you can't edit, we might be looking at a bug in whedon or some other issue we might need to investigate.

**Comment by melissawm** [comment]
@whedon re-invite @tpoisot as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@tpoisot please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by melissawm** [comment]
Hello, folks! @tpoisot I can see you were able to check some of the boxes - hope the invitation worked! Let me know if there's anything else you need help with. Thanks!

**Comment by tpoisot** [comment]
@melissawm / @vlandau - yep, all works - my comments on the (really good) paper are here:

> If anything, the current paper is selling the software short a little bit. Omniscape can be deployed on HPC to really benefit from the built-in multi-threading, and the variety of input/output formats is really important to mention.
> 
> I would also show one map with a full Omniscape result, to see a quick illustration of what the different components of the output are.

**Comment by vlandau** [comment]
Thanks @tpoisot! I will work on addressing those comments now.

**Comment by vlandau** [comment]
@tpoisot just added a figure with example outputs. Good call! I also added a sentence about multithreading to the summary, and mentioned that ASCII and GeoTIFF raster formats are supported for reading and writing. 

@melissawm I think it might make sense prior to finalizing the review to tag a new patch release of Omniscape.jl so a snapshot of the documentation can be preserved. Would it be possible to update the version after I tag that release?

**Comment by vlandau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: :point_left:

**Comment by tpoisot** [comment]
That's an **accept** for me.

**Comment by melissawm** [comment]
Thank you both @tpoisot and @juliohm for you thorough and thoughtful reviews! 

> @melissawm I think it might make sense prior to finalizing the review to tag a new patch release of Omniscape.jl so a snapshot of the documentation can be preserved. Would it be possible to update the version after I tag that release?

If I understand the question correctly, yes you can update the version number with whedon and choose the correct version to tag as the Zenodo/archive corresponding to the JOSS paper. Please see if [the JOSS/whedon documentation](https://joss.readthedocs.io/en/latest/whedon.html#changing-the-software-version) answers your question.

**Comment by vlandau** [comment]
@whedon set v0.4.4 as version

**Comment by whedon** [comment]
I'm sorry @vlandau, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by vlandau** [comment]
@melissawm looks like I don't have the permissions to update. But v0.4.4 is tagged and docs for it are [here](https://docs.circuitscape.org/Omniscape.jl/v0.4.4), so it's all set.

**Comment by melissawm** [comment]
@whedon set v0.4.4 as version

**Comment by whedon** [comment]
OK. v0.4.4 is the version.

**Comment by melissawm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.0014-3820.2006.tb00500.x is OK
- 10.1137/141000671 is OK
- 10.1890/07-1861.1 is OK
- 10.1111/cobi.13230 is OK
- 10.21105/jcon.00058 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by melissawm** [comment]
@vlandau, A few final comments:
- In the reference Anantharaman et al, 2020, the publication venue listed in the paper is "Proceedings of the JuliaCon Conferences", which is different from the DOI (JuliaCon Proceedings). Can you check which is the correct one?
- For the reference Bunn et al, 2000, can you confirm that [this is the right DOI](https://doi.org/10.1006/jema.2000.0373)? In that case, can you add it to the reference?
- For the McRae et al, 2016 reference, it seems to me that [this is the right DOI](https://www.researchgate.net/publication/304842896_Conserving_Nature%27s_Stage_Mapping_Omnidirectional_Connectivity_for_Resilient_Terrestrial_Landscapes_in_the_Pacific_Northwest?channel=doi&linkId=577c4e4608aec3b743367195&showFulltext=true) - can you confirm and add it to the reference if that's the case?

After this, I ask that you re-read the paper and make sure all is good so we can proceed with publishing. Thanks!

**Comment by vlandau** [comment]
@melissawm I've added those DOIs, thanks! I have reviewed the paper and all looks good to me! 

For Anantharaman et al, I am checking with the folks from Julia. It looks like the citation shown on that page has "JuliaCon Proceedings" but the bibtex snippet that they provide on the same page uses "Proceedings of the JuliaCon Conferences." I will post back here once I find out which to use.

**Comment by vlandau** [comment]
@melissawm Okay, they said to go with JuliaCon Proceedings. Thanks for flagging that! I just fixed the reference in the paper.bib file.

**Comment by vlandau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02829/joss.02829/10.21105.joss.02829.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
At this point could you:
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository) with the correct version 
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission. Thanks!

**Comment by vlandau** [comment]
Alright, it should all be [here](https://doi.org/10.5281/zenodo.4466323). The DOI is 10.5281/zenodo.4466323

Thank you!

**Comment by melissawm** [comment]
Thank you, @vlandau ! Just checking - there is a small typo on the summary for Zenodo:

> Omniscape.jl implements **to** Omniscape omnidirectional habitat connectivity modeling algorithm (McRae et al. 2016) in the Julia programming language.

Also you mention References but there is only one paper listed - is this intentional?

**Comment by vlandau** [comment]
@melissawm thanks I'll fix that typo! That was the only paper I cited so it was the only one listed in references.

**Comment by melissawm** [comment]
@whedon set 10.5281/zenodo.4466323 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4466323" target="_blank">10.5281/zenodo.4466323</a> is the archive.

**Comment by melissawm** [comment]
Hello @openjournals/joss-eics , I believe this is ready for publishing. 

Thanks again @vlandau, @juliohm and @tpoisot !

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.0014-3820.2006.tb00500.x is OK
- 10.1006/jema.2000.0373 is OK
- 10.1137/141000671 is OK
- 10.1890/07-1861.1 is OK
- 10.1111/cobi.13230 is OK
- 10.21105/jcon.00058 is OK
- 10.13140/RG.2.1.4158.6166 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2062

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2062, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1355206577918242817) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2063
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02829](https://doi.org/10.21105/joss.02829)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @vlandau (Vincent Landau) and co-authors!!

And thanks to @juliohm @tpoisot for reviewing, and @melissawm for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02829/status.svg)](https://doi.org/10.21105/joss.02829)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02829">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02829/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02829/status.svg
   :target: https://doi.org/10.21105/joss.02829
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02829/status.svg)](https://doi.org/10.21105/joss.02829)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
