### ISSUE TITLE
[PRE REVIEW]: yotover: An R package to support analysis and reproduce results from An Advanced Guide to Trade Policy Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2832]
**Submitting author:** @pachamaltese (<a href="http://orcid.org/0000-0003-1017-7574">Mauricio Vargas</a>)
**Repository:** <a href="https://github.com/pachamaltese/yotover" target ="_blank">https://github.com/pachamaltese/yotover</a>
**Version:** v0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pachamaltese. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @oliviaguest.

@pachamaltese if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.24 s (215.0 files/s, 32866.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             5            214              5           2998
CSS                              9             16             51            849
R                               12            163            169            779
JavaScript                      12            107            107            707
XML                              1              0              2            441
JSON                             2              0              0            414
Markdown                         2             96              0            321
TeX                              3             20              0            162
YAML                             4             27              0             99
Rmd                              1             11             37              0
-------------------------------------------------------------------------------
SUM:                            51            654            371           6770
-------------------------------------------------------------------------------


Statistical information for the repository '2179c389c3159802545ba032' was
gathered on 2020/11/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Mauricio Vargas                  5          1810            889          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mauricio Vargas             921           50.9          0.6               11.62
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2832 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
@pachamaltese This submission will be discussed by the editorial board and we should be able to get back to you in a week or two.

**Comment by kthyng** [comment]
@pachamaltese Also your paper is not being found by our bot Whedon because the suffix is .Rmd but it needs to be .md.

**Comment by kthyng** [comment]
Hi @pachamaltese. Thank you for your submission, but we've determined that it isn't within our scope. We publish software in direct support of research. It's a great idea to archive scripts to support this book, but JOSS isn't the venue for doing so. One suggestion is to get a Zenodo archive to preserve and distribute this software.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
