### ISSUE TITLE
[PRE REVIEW]: UQit: A Python package for uncertainty quantification (UQ) in computational fluid dynamics (CFD)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2833]
**Submitting author:** @salrm8 (<a href="http://orcid.org/0000-0002-9610-9910">Saleh Rezaeiravesh</a>)
**Repository:** <a href="https://github.com/KTH-Nek5000/UQit" target ="_blank">https://github.com/KTH-Nek5000/UQit</a>
**Version:** v1.0.2
**Editor:** @drvinceknight
**Reviewers:** @jayten, @ctdegroot
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @salrm8. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kyleniemeyer.

@salrm8 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.22 s (202.7 files/s, 45183.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          24            266           1739           2892
Jupyter Notebook                 5              0           3192            880
reStructuredText                10            220            167            323
Markdown                         3             42              0            144
TeX                              1             11              0            102
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            45            551           5106           4376
-------------------------------------------------------------------------------


Statistical information for the repository 'd38d75959b8a09f5b3ef4c8c' was
gathered on 2020/11/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Saleh                          230         27550          21794          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Saleh                      4897           17.8          2.6               17.54
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2833 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Saleh Rezaeiravesh, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-8db9f43069bd/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-1-4757-3799-8 is OK
- 10.1007/978-3-319-12385-1 is OK
- 10.2307/j.ctv7h0skv is OK

MISSING DOIs

- 10.21236/ada460654 may be a valid DOI for title: The Wiener–Askey Polynomial Chaos for Stochastic Differential Equations

INVALID DOIs

- https://doi.org/10.1016/S0378-4754(00)00270-6 is INVALID because of 'https://doi.org/' prefix
- arXiv:2007.07071 is INVALID
```

**Comment by kthyng** [comment]
Hi @salrm8! Can you look through and address the DOI problems above and look through the errors with building your paper to try to fix them?

**Comment by kthyng** [comment]
@drvinceknight do you have bandwidth to take on this submission?

**Comment by kthyng** [comment]
@whedon invite @drvinceknight as editor

**Comment by whedon** [comment]
@drvinceknight has been invited to edit this submission.

**Comment by salrm8** [comment]
> Hi @salrm8! Can you look through and address the DOI problems above and look through the errors with building your paper to try to fix them?

Hi @kthyng! I fixed the issues with the DOIs and affiliations index quoting. 
Thank you

**Comment by danielskatz** [comment]
👋 @drvinceknight - note that you have been requested to edit this submission...

**Comment by danielskatz** [comment]
@whedon invite @drvinceknight as editor

**Comment by whedon** [comment]
@drvinceknight has been invited to edit this submission.

**Comment by drvinceknight** [comment]
Sorry for missing the first notification!

**Comment by drvinceknight** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by drvinceknight** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02833/joss.02833/10.21105.joss.02833.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02833/joss.02833/10.21105.joss.02833.pdf) :page_facing_up: :point_left:

**Comment by drvinceknight** [comment]
@whedon check references

**Comment by drvinceknight** [comment]
@salrm8 do you have any suggestions for reviewer? Looking through the list of potential reviewers: https://bit.ly/joss-reviewers a number jump out as having experience with both Python and fluid dynamics. No trouble at all if you don't have any suggestions :)

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-1-4757-3799-8 is OK
- 10.1007/978-3-319-12385-1 is OK
- 10.1137/S1064827501387826 is OK
- 10.2307/j.ctv7h0skv is OK
- 10.1016/S0378-4754(00)00270-6 is OK
- 10.1142/p878 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by salrm8** [comment]
> @salrm8 do you have any suggestions for reviewer? Looking through the list of potential reviewers: https://bit.ly/joss-reviewers a number jump out as having experience with both Python and fluid dynamics. No trouble at all if you don't have any suggestions :)

Thanks you. I just did a quick search and came up with this list: prmiles, georgiastuart, ctdegroot, jayten
They have experience with UQ, Python and CFD.

**Comment by drvinceknight** [comment]
Thank you, I'll start there.

**Comment by drvinceknight** [comment]
Hello @jayten and @ctdegroot, would you be able to review this paper for JOSS entitled: "UQit: A Python package for uncertainty quantification (UQ) in computational fluid dynamics". Given your stated expertise in fluid dynamics and Python I think you'll find it interesting :)

If either of you have any questions about reviewing for JOSS or anything else let me know. There is also very helpful documentation here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#.

**Comment by jayten** [comment]
@drvinceknight, I can help with the review process of this paper. You can assign me as a reviewer.

**Comment by drvinceknight** [comment]
Thanks @jayten :+1:

**Comment by drvinceknight** [comment]
@whedon assign @jayten as reviewer

**Comment by whedon** [comment]
OK, @jayten is now a reviewer

**Comment by ctdegroot** [comment]
Yep, I am interested in this. Might take me a couple weeks to get to it as I'm wrapping up another JOSS review.

**Comment by drvinceknight** [comment]
That's fine @ctdegroot, thank you very much!

**Comment by drvinceknight** [comment]
@whedon add @ctdegroot as reviewer

**Comment by whedon** [comment]
OK, @ctdegroot is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2871.
