### ISSUE TITLE
[PRE REVIEW]: deeplenstronomy: A dataset simulation package for strong gravitational lensing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2834]
**Submitting author:** @rmorgan10 (<a href="http://orcid.org/0000-0002-7016-5471">Robert Morgan</a>)
**Repository:** <a href="https://github.com/deepskies/deeplenstronomy" target ="_blank">https://github.com/deepskies/deeplenstronomy</a>
**Version:** v0.0.1.0
**Editor:** @pdebuyl
**Reviewers:** @shreyasbapat, @jiwoncpark
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @rmorgan10. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @harpolea.

@rmorgan10 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2834 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (4f9319a0577a52cb76197b48/paper.md): mapping values are not allowed in this context at line 9 column 52 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.48 s (198.9 files/s, 50289.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          39           1217           1496           3684
Jupyter Notebook                19              0          12323           1731
YAML                            19            121             27           1602
Markdown                         5            178              0            788
TeX                              1             15              0            369
DOS Batch                        1             29              1            212
make                             2             39              6            188
reStructuredText                 9             75             17            130
INI                              1              3              0             24
-------------------------------------------------------------------------------
SUM:                            96           1677          13870           8728
-------------------------------------------------------------------------------


Statistical information for the repository '3a1fc19720c38e628fb51236' was
gathered on 2020/11/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Brian Nord                      28          2767            491           22.96
Jason Poh                       10           521            192            5.03
Joao Caldeira                   13           183            307            3.45
Robert Morgan                   94          5551           1443           49.29
joshualin24                      7           194             90            2.00
sibirrer                        38          1080           1370           17.27

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Brian Nord                 1976           71.4          8.5               19.33
Jason Poh                   132           25.3         15.6                3.79
Joao Caldeira               106           57.9         15.5               11.32
Robert Morgan              3949           71.1          4.5               12.18
joshualin24                  55           28.4         15.6               16.36
sibirrer                    182           16.9         15.9                5.49
```

**Comment by kthyng** [comment]
@pdebuyl Are you able to take on this submission?

**Comment by kthyng** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by kthyng** [comment]
@rmorgan10 not sure about the error in your paper... can you compare your line 9 with the [paper requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) and see if something is amiss?

**Comment by rmorgan10** [comment]
It looks like lines 8-9 are
```
authors:
  - name: Robert Morgan^[Corresponding author email: robert.morgan@wisc.edu]
```
Though I believe I followed the same syntax as the paper requirements:
```
authors:
  - name: Adrian M. Price-Whelan^[Custom footnotes for e.g. denoting who the corresponding author is can be included like this.]
```

I'm not quite sure what the problem is either.

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by rmorgan10** [comment]
I have a feeling the compile issue is the ':' character in the footnote, or perhaps that the footnote text needs to be enclosed in single quotes. I will test this as soon as I can, but at present the online compile service seems to be down.

**Comment by arfon** [comment]
> I have a feeling the compile issue is the ':' character in the footnote, or perhaps that the footnote text needs to be enclosed in single quotes. I will test this as soon as I can, but at present the online compile service seems to be down.

This should be fixed again now.


@rmorgan10 - is this JOSS submission associated with a paper in AAS publishing?

**Comment by pdebuyl** [comment]
@rmorgan10 the AAS question should be answered before I proceed. BTW, as you have an ORCID record the email could be considered superfluous, which would solve the compilation issue :-)

**Comment by rmorgan10** [comment]
@arfon this JOSS submission is not associated with a paper in a AAS journal.

@pdebuyl , @kthyng the compilation issue has been fixed and everything looks good!

**Comment by rmorgan10** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02834/joss.02834/10.21105.joss.02834.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02834/joss.02834/10.21105.joss.02834.pdf) :page_facing_up: :point_left:

**Comment by pdebuyl** [comment]
@fipanther @shreyasbapat can you review the article "deeplenstronomy: A dataset simulation package for strong gravitational lensing" for JOSS ?

**Comment by shreyasbapat** [comment]
Sure! I'll be glad to!

**Comment by shreyasbapat** [comment]
At the same time, @rmorgan10 do you think this can be brought in the family of @einsteinpy ?

**Comment by shreyasbapat** [comment]
@kakirastern See this package! 
@rmorgan10 we always planned to do something similar in @einsteinpy ! Great work!

**Comment by rmorgan10** [comment]
`deeplenstronomy` doesn't perform any gravitational lensing calculations itself, it's a wrapper that focuses on generating and organizing data for deep learning using the package [`lenstronomy`](https://github.com/sibirrer/lenstronomy) (which is the main gravitational lensing workhorse). 

After a quick glance at the @einsteinpy family, to me it doesn't feel like `deeplenstronomy` fits in, but I'd be happy to discuss it more with you if you think it does!

**Comment by pdebuyl** [comment]
Thank you @shreyasbapat for accepting :-)

**Comment by kakirastern** [comment]
Nice

**Comment by kakirastern** [comment]
> @fipanther @shreyasbapat can you review the article "deeplenstronomy: A dataset simulation package for strong gravitational lensing" for JOSS ?

Can I help as well?

**Comment by pdebuyl** [comment]
@kakirastern I pick reviewers from this list first and try to balance the reviewers' backgrounds. The best way forward, in any case, is to volunteer to review for JOSS here: https://joss.theoj.org/reviewer-signup.html Then you can be picked for a future submission.

**Comment by kakirastern** [comment]
Sure @pdebuyl, let me volunteer for JOSS now. Thanks for the heads up!

**Comment by pdebuyl** [comment]
@jiwoncpark can you review the article "deeplenstronomy: A dataset simulation package for strong gravitational lensing" for JOSS?

**Comment by jiwoncpark** [comment]
@pdebuyl Sure, happy to.

**Comment by pdebuyl** [comment]
Thank you @jiwoncpark !

**Comment by pdebuyl** [comment]
@whedon assign @shreyasbapat as reviewer

**Comment by whedon** [comment]
OK, @shreyasbapat is now a reviewer

**Comment by pdebuyl** [comment]
@whedon add @jiwoncpark as reviewer

**Comment by whedon** [comment]
OK, @jiwoncpark is now a reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2854.
