### ISSUE TITLE
[PRE REVIEW]: ADI.jl: A Julia Package for High-Contrast Imaging

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2835]
**Submitting author:** @mileslucas (<a href="http://orcid.org/0000-0001-6341-310X">Miles Lucas</a>)
**Repository:** <a href="https://github.com/JuliaHCI/ADI.jl" target ="_blank">https://github.com/JuliaHCI/ADI.jl</a>
**Version:** 0.5.2
**Editor:** @dfm
**Reviewers:** @giordano, @semaphoreP
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mileslucas. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@mileslucas if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.25 s (186.3 files/s, 15168.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           23            349            248           1266
TOML                             6            180              1            875
Markdown                        13            150              0            333
TeX                              1             14              2            226
YAML                             3              4              0             97
-------------------------------------------------------------------------------
SUM:                            46            697            251           2797
-------------------------------------------------------------------------------


Statistical information for the repository 'b916fe10f0b382abbfe1920d' was
gathered on 2020/11/11.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1538-3873/128/968/102001 is OK
- 10.1126/science.1102929 is OK
- 10.1086/500401 is OK
- 10.1088/2041-8205/755/2/L28 is OK
- 10.3847/1538-4357/aaa1f2 is OK
- 10.1137/141000671 is OK
- 10.1051/0004-6361/201834136 is OK
- 10.1109/TPDS.2018.2872064 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02835/joss.02835/10.21105.joss.02835.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02835/joss.02835/10.21105.joss.02835.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@xuanxu Are you interested and able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @xuanxu as editor

**Comment by whedon** [comment]
@xuanxu has been invited to edit this submission.

**Comment by xuanxu** [comment]
@kthyng Sorry, currently I am not able to handle another submission.

**Comment by arfon** [comment]
:wave: @mileslucas - is this submission associated with a paper in a AAS journal?

**Comment by mileslucas** [comment]
Not that I believe. We have some related forward modeling work that will be published but it's not closely related enough to be a joint publication in my opinion.

**Comment by kthyng** [comment]
@jni are you able to take on another submission?

**Comment by kthyng** [comment]
@whedon invite @jni as editor

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by kthyng** [comment]
@whedon add @dfm as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kthyng** [comment]
@jni nevermind! @dfm volunteered.

**Comment by kthyng** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@giordano has agreed to act as our first reviewer - thanks Mosè!

@giordano has disclosed that he and @mileslucas co-mentored a Google Summer of Code project, but he feels that he can provide an impartial review despite this potential conflict of interest. I agree that this potential conflict is minor and believe that the benefit of having Mosè as a reviewer outweighs the apparent conflict of interest. _Therefore, unless @mileslucas has any other concerns, I propose that we declare and waive this conflict_. Miles: please let me know here or via email if you have any questions or concerns!

**Comment by mileslucas** [comment]
Thanks Dan (and Mosè)- I have no issues with Mosè reviewing, either, so I'm happy to waive the conflict.

@dfm unrelated to this, a concern about the manuscript is that I currently have a markdown table in it; I'm not sure if that's allowed or not. In its current state the table definitely needs edited to be shown better and I understand pandoc has options for rendering it. However, I understand if the table is a no-go and I can punt it out into my package docs, instead.

**Comment by dfm** [comment]
@mileslucas: Sounds good - thanks! For the table, there should be no problem including one, but I agree that it's worth tweaking the formatting. You can use the preview service here to test the compiled version of the manuscript: http://whedon.theoj.org

**Comment by dfm** [comment]
@whedon add @giordano as reviewer

**Comment by whedon** [comment]
OK, @giordano is now a reviewer

**Comment by mileslucas** [comment]
@dfm if I understand correctly, to tweak the table formatting I would need to change some of the options that pandoc uses when it compiles the pdf. Do I have access to those options in my markdown/bib/meta files?

**Comment by dfm** [comment]
Ah! No, I meant that the best approach would be to change the table to fit. I bet that renaming the "pre-processing" column would get you most of the way there. For simplicity, the pandoc options are set in stone!

**Comment by dfm** [comment]
@semaphoreP has agreed to act as our second reviewer - thanks Jason! We'll get the review started momentarily.

@giordano, @semaphoreP, and @mileslucas: Let me know if you have any questions as we go!

**Comment by dfm** [comment]
@whedon add @semaphoreP as reviewer

**Comment by whedon** [comment]
OK, @semaphoreP is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2843.
