### ISSUE TITLE
[PRE REVIEW]: ivadomed: A Medical Imaging Deep Learning Toolbox

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2836]
**Submitting author:** @charleygros (<a href="http://orcid.org/0000-0003-4318-0024">Charley Gros</a>)
**Repository:** <a href="https://github.com/ivadomed/ivadomed" target ="_blank">https://github.com/ivadomed/ivadomed</a>
**Version:** 2.5.0
**Editor:** @cMadan
**Reviewers:** @NMontanaBrown, @justusschock, @lbugnon
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @charleygros. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arokem.

@charleygros if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.62 s (191.8 files/s, 32063.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          65           2884           3510           9196
JSON                            13              2              0           1076
reStructuredText                18            563            273           1068
TeX                              1             29              0            283
Markdown                         6            127              0            273
Bourne Shell                     8             75            131            220
YAML                             4             15             14             84
DOS Batch                        1              8              1             26
make                             1              5              7             13
CSS                              1              0              1              4
RobotFramework                   1              0              0              2
-------------------------------------------------------------------------------
SUM:                           119           3708           3937          12245
-------------------------------------------------------------------------------


Statistical information for the repository '1a28f68744d0d8badfad9ab2' was
gathered on 2020/11/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alexandru Jora                   7            12             29            0.06
AnBucquet                       83          2553           1221            5.66
BUCQUET Anthime                  3            11              2            0.02
Christian S. Perone              8           527             20            0.82
Julien Cohen-Adad               40           745            310            1.58
Lucas Rouhier                   33           144            139            0.42
Nick                             2            11             23            0.05
Olivier                         25           121            127            0.37
Olivier Vincent                 35           339            148            0.73
Valentine-LL                     7            15             18            0.05
ValentineLL                     27           521            218            1.11
andreanne-lemay                563         10581           6911           26.24
bsauty                           1             1              1            0.00
charleygros                   1415         21212          12583           50.69
lrouhier                       132          4060           2131            9.29
olivier                         62           948            617            2.35
olix86                          16           318             57            0.56

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alexandru Jora                8           66.7          4.4                0.00
AnBucquet                   771           30.2          9.9               10.89
Christian S. Perone          90           17.1         11.1                2.22
Julien Cohen-Adad           488           65.5          7.9               35.86
Nick                         10           90.9          6.8              100.00
Olivier                     278          229.8          7.7               10.79
Olivier Vincent               2            0.6         12.4                0.00
Valentine-LL                  7           46.7         15.3               28.57
ValentineLL                 206           39.5         16.6                8.25
andreanne-lemay            4359           41.2          4.9                7.18
charleygros                6344           29.9          6.1               12.97
lrouhier                   2765           68.1          2.2                9.69
olix86                      262           82.4          2.9                9.16
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2836 with the following error: 

 ORCID looks malformed
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (XX) for Lucas Rouhier (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.nicl.2018.03.029 is OK
- 10.1016/j.neuroimage.2018.09.081 is OK
- 10.14245/ns.1938396.198 is OK
- 10.1038/sdata.2016.44 is OK
- 10.1016/j.neucom.2019.01.103 is OK
- 10.1109/CVPR.2016.90 is OK

MISSING DOIs

- 10.1109/iccv.2019.00707 may be a valid DOI for title: Adaptive Wing Loss for Robust Face Alignment via Heatmap Regression
- 10.1007/978-3-030-00928-1_74 may be a valid DOI for title: Exploring Uncertainty Measures in Deep Networks for Multiple Sclerosis Lesion Detection and Segmentation
- 10.1007/978-3-319-46723-8_54 may be a valid DOI for title: Hemis: Hetero-modal image segmentation
- 10.1109/iccvw.2017.9 may be a valid DOI for title: Count-ception: Counting by Fully Convolutional Redundant Counting
- 10.1016/j.neuroimage.2018.11.042 may be a valid DOI for title: QuickNAT: A Fully Convolutional Network for Quick and Accurate Segmentation of Neuroanatomy
- 10.1109/3dv.2016.79 may be a valid DOI for title: V-net: Fully convolutional neural networks for volumetric medical image segmentation
- 10.1007/978-3-030-00931-1_70 may be a valid DOI for title: 3D segmentation with exponential logarithmic loss for highly unbalanced object sizes

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@cMadan  are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by cMadan** [comment]
@kthyng, sure, I can take this one.

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@charleygros, do you have any suggestions for reviewers? (See initial comment in this issue.)

It would also be great if you can add DOIs for articles that are currently missing them in the bib. See some suggestions earlier in this issue (but please double check!).

**Comment by charleygros** [comment]
Many thanks @cMadan for accepting to be the editor for this submission!

Sorry for the delayed reply.

> @charleygros, do you have any suggestions for reviewers? (See initial comment in this issue.)

Suggestions for reviewers from the provided list:
- rlizzo
- NMontanaBrown
- Bsingstad
- justusschock
- lbugnon
- esadr
- fernandoandreotti

> It would also be great if you can add DOIs for articles that are currently missing them in the bib. See some suggestions earlier in this issue (but please double check!).

Sure, I'm happy do this ASAP and will keep you posted.

**Comment by charleygros** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2836 with the following error: 

 Error reading bibliography file paper.bib:
(line 107, column 10):
unexpected ","
expecting white space
Looks like we failed to compile the PDF

**Comment by charleygros** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2836 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.-02aca882a10b72c1/78fb38f212fa49029aff24c669a39648d9b4e68b.vs': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 404: N
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA not enough bytes
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.-02aca882a10b72
c1/78fb38f212fa49029aff24c669a39648d9b4e68b.vs (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.398 ...b38f212fa49029aff24c669a39648d9b4e68b.vs}

Looks like we failed to compile the PDF

**Comment by charleygros** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02836/joss.02836/10.21105.joss.02836.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02836/joss.02836/10.21105.joss.02836.pdf) :page_facing_up: :point_left:

**Comment by cMadan** [comment]
@whedon check references

**Comment by cMadan** [comment]
@openjournals/joss-eics, any idea why whedon's not responding here?

**Comment by danielskatz** [comment]
@whedon check references

**Comment by danielskatz** [comment]
(I always try twice before deciding there's a problem)

**Comment by arfon** [comment]
@whedon check references

**Comment by arfon** [comment]
It looks like the Crossref API is timing out. I managed to get this to run locally (the DOIs are fine):

```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/iccv.2019.00707 is OK
- 10.1016/j.nicl.2018.03.029 is OK
- 10.1016/j.neuroimage.2018.09.081 is OK
- 10.14245/ns.1938396.198 is OK
- 10.1038/sdata.2016.44 is OK
- 10.1016/j.media.2019.101557 is OK
- 10.1016/j.neucom.2019.01.103 is OK
- 10.1007/978-3-319-46723-8_54 is OK
- 10.1109/iccvw.2017.9 is OK
- 10.1109/CVPR.2016.90 is OK
- 10.1016/j.neuroimage.2018.11.042 is OK
- 10.1109/3dv.2016.79 is OK
- 10.1007/978-3-030-00931-1_70 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by cMadan** [comment]
@NMontanaBrown @justusschock @lbugnon, would you be available and interested in reviewing this submission?

**Comment by NMontanaBrown** [comment]
> @NMontanaBrown @justusschock @lbugnon, would you be available and interested in reviewing this submission?

I'd be keen to! 😄

**Comment by justusschock** [comment]
I would also be available for a review

**Comment by lbugnon** [comment]
> @NMontanaBrown @justusschock @lbugnon, would you be available and interested in reviewing this submission?

Ok!

**Comment by cMadan** [comment]
Great, happy to have you all as reviewers here!

**Comment by cMadan** [comment]
@whedon add @NMontanaBrown as reviewer

**Comment by whedon** [comment]
OK, @NMontanaBrown is now a reviewer

**Comment by cMadan** [comment]
@whedon add @justusschock as reviewer

**Comment by whedon** [comment]
OK, @justusschock is now a reviewer

**Comment by cMadan** [comment]
@whedon add @lbugnon as reviewer

**Comment by whedon** [comment]
OK, @lbugnon is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2868.
