### ISSUE TITLE
[PRE REVIEW]: censo2017: 2017 Chilean Census Easy Access Database

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2837]
**Submitting author:** @pachamaltese (<a href="http://orcid.org/0000-0003-1017-7574">Mauricio Vargas</a>)
**Repository:** <a href="https://github.com/pachamaltese/censo2017/" target ="_blank">https://github.com/pachamaltese/censo2017/</a>
**Version:** v0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pachamaltese. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @oliviaguest.

@pachamaltese if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.22 s (215.2 files/s, 38889.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              0              2           2508
HTML                            17            745            198           2361
R                               12            160            140            905
CSS                              3             99             48            428
JSON                             1              0              0            319
JavaScript                       4             65             35            267
Markdown                         4             45              0             83
YAML                             2             17              0             58
TeX                              1              6              0             55
Rmd                              1             19             49             50
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            48           1156            473           7045
-------------------------------------------------------------------------------


Statistical information for the repository '87dc0b42e1edc212084c60ba' was
gathered on 2020/11/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Mauricio Vargas                  2           367              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mauricio Vargas             367          100.0          0.0                9.54
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.21105/joss.01483 may be a valid DOI for title: citesdb: An R package to support analysis of CITES Trade Database shipment-level data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02837/joss.02837/10.21105.joss.02837.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02837/joss.02837/10.21105.joss.02837.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
@pachamaltese Since the size of this submission looks borderline, the greater editorial board will have a look to make it is in scope. This will take 1-2 weeks.

**Comment by pachamaltese** [comment]
@kthyng Hi. Thanks a lot. No worries, this is very similar to citesdb but adapted to our Latin-American reality.

**Comment by danielskatz** [comment]
👋 @pachamaltese - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by pachamaltese** [comment]
Dear @danielskatz 

I have to disagree. I have created R packages that only matter to 10 individuals or so and are considered scholarly important, while this is, by far, the most significant contribution I have written in a long time.

Comparing my previous JOSS articles gravity and economiccomplexity, those won't have the same number of users or won't be used by as many sociologists and economists as censo2017 has been used even when it wasn't on CRAN.

This work is an adaptation of citesdb, an R package that has a JOSS article.  After this rejection I don't think I shall send my works to JOSS ever again and/or I'll limit all my efforts to LaTeX equations while leaving data access out of my projects.

Best,

**Comment by arfon** [comment]
Hi @pachamaltese - thanks for the followup comment here. I wanted to give a little more context about our decision here...

Back in July this year, we adopted a [new standard for JOSS](https://blog.joss.theoj.org/2020/07/minimum-publishable-unit) submissions. The big change with this new policy was that future submissions would need to meet a minimum level of effort to be published in JOSS. If you haven't already, I encourage you to read this post as it explains in detail our thinking here and why we made this decision.

While I absolutely recognize the value and potential impact of the work you've submitted here, I believe our decision here about level of effort is correct. 

Finally, please note that there are submissions that JOSS has reviewed and published that would no longer be in scope for us. This includes `citesdb` which would be rejected these days because of the same reason.
