### ISSUE TITLE
[PRE REVIEW]: fctSPM: Factorial ANOVA and post-hoc tests for Statistical Parametric Mapping in MATLAB

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2839]
**Submitting author:** @tramarobin (<a href="http://orcid.org/0000-0001-6807-0505">Robin Trama</a>)
**Repository:** <a href="https://github.com/tramarobin/fctSPM" target ="_blank">https://github.com/tramarobin/fctSPM</a>
**Version:** 1.4
**Editor:** @cMadan
**Reviewers:** @0todd0000, @nicholst
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tramarobin. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @csoneson.

@tramarobin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jbiomech.2010.03.008 is OK
- 10.1016/j.jbiomech.2010.03.008 is OK
- 10.1109/TBME.2020.3035838 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1002/hbm.460020402 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.60 s (989.1 files/s, 41876.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                         591           6048           3866          14981
Markdown                         3             59              0            198
TeX                              1              5              0             34
-------------------------------------------------------------------------------
SUM:                           595           6112           3866          15213
-------------------------------------------------------------------------------


Statistical information for the repository '2c1b233853851da820e7464a' was
gathered on 2020/11/13.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02839/joss.02839/10.21105.joss.02839.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02839/joss.02839/10.21105.joss.02839.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@tramarobin Can you address the DOI note above?

**Comment by kthyng** [comment]
@csoneson Can you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by tramarobin** [comment]
The DOI issue was corrected. Trama RobinPhD student De : Kristen ThyngEnvoyé le :samedi 14 novembre 2020 20:08À : openjournals/joss-reviewsCc : tramarobin; MentionObjet :Re: [openjournals/joss-reviews] [PRE REVIEW]: fctSPM: Factorial ANOVA and post-hoc tests for Statistical Parametric Mapping in MATLAB (#2839) @tramarobin Can you address the DOI note above?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by csoneson** [comment]
@kthyng - this is a bit outside of my expertise, I'm afraid. I wonder if one of the more MATLAB/neuroimaging-oriented editors would be more suitable (if available).

**Comment by kthyng** [comment]
@csoneson no problem!

@cMadan Are you interested in editing this one?

**Comment by kthyng** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@tramarobin, it looks like the references aren't working here. Are you still working on this, or do you need help debugging it?

**Comment by tramarobin** [comment]
@cMadan yes it seems I can use some help. 
I think I correctly modified the DOI issue, and I did not receive other issue with references. 

For what I read, I attached my bibliography in the article by writing "bibliography: paper.bib", and I called my reference that is listed in the paper.bib file as  '[@myreference]' 

It is the first time I am using bibtext format for references, am I missing something ?

**Comment by cMadan** [comment]
@tramarobin, I think there are probably a few things that need fixing. Let's fix the ones I noticed and see if there are any more that still remail.

(1) https://raw.githubusercontent.com/tramarobin/fctSPM/master/Article%40JOSS/paper.md

Please remove the single quotes around the square brackets for each reference. It might be useful to take another look at the example: https://joss.readthedocs.io/en/latest/submitting.html

I think you used the examples at the very bottom and followed them too literally, look instead at the references in the Statement of Need section.

(2) https://github.com/tramarobin/fctSPM/blob/master/Article%40JOSS/paper.bib

You need `and` between authors, not just at the end. If you have initials after the last name you need a comma, e.g., `{Nicols, T E and Holmes, A P}`. See the first bib example in https://joss.readthedocs.io/en/latest/submitting.html, which shows a paper with three authors.

Your last reference is missing the volume and page numbers.

**Comment by tramarobin** [comment]
@cMadan, thank you for your help. I took the examples too litterally indeed.

I previewed the paper at https://whedon.theoj.org/ and I think it is ok now (last time the website wasn't working and I could not check the paper once compiled)

For the last reference, the paper was only accepted recently and there is no volume and page number yet. On the jounal website, the BibText citation has an empty volume number and '{1-1}' for page numbers. I added these fileds to the reference, I hope it is ok.

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02839/joss.02839/10.21105.joss.02839.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02839/joss.02839/10.21105.joss.02839.pdf) :page_facing_up: :point_left:

**Comment by cMadan** [comment]
@tramarobin, thanks for fixing those errors. I would remove the `1-1` page range for the recently accepted paper since this isn't the actual publication information and is just a placeholder.

Now that some of the initial issues are resolved, it would be good to revise the text a bit. Your current Statement of need section doesn't really explain the 'need' that this software is designed to fulfil. I also found that the section of the software itself could use some proof reading. For instance the sentence beginning with "Numerous figures are also created, ..." is a bit awkward. The late sentence about "Many parameters also exist..." would benefit from more details on what these parameters are. I would suggest you ask a colleague not involved in the project to look over the text and ask them where they found it too unclear. These are intended to be short papers, but they also need to explain what the software does, so that an interested reader might follow up and try using the software.

Here are a few examples I felt that should be relatable, to help you get a better idea of what the paper should be like:
https://joss.theoj.org/papers/10.21105/joss.02670
https://joss.theoj.org/papers/10.21105/joss.02166
https://joss.theoj.org/papers/10.21105/joss.02668

**Comment by tramarobin** [comment]
@cMadan, thank you for your helpful feedbacks. We have modified the article as recommended and some colleagues not involved in the project helped us to clarify some points.
The new version has been updated on the GitHub repository.

**Comment by cMadan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02839/joss.02839/10.21105.joss.02839.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02839/joss.02839/10.21105.joss.02839.pdf) :page_facing_up: :point_left:

**Comment by cMadan** [comment]
@tramarobin, the text is much improved--well done!

As a minor comment, I'd suggest against jet as the default colormap. (For some background, see https://onlinelibrary.wiley.com/doi/full/10.1111/ejn.14430.)

Can you look through the list of JOSS reviewers (linked in the first comment in this issue) and suggest some who may be suitable?

**Comment by tramarobin** [comment]
@cMadan, thank you for the link to your paper. I had never considered the luminance or the sequential or diverging characteristics of a color scale. 

I included the cbrewer funtion in the package as it allows to chose between more colormaps.  (Charles (2020). cbrewer : colorbrewer schemes for Matlab (https://www.mathworks.com/matlabcentral/fileexchange/34087-cbrewer-colorbrewer-schemes-for-matlab), MATLAB Central File Exchange. Retrieved December 11, 2020.) 

Two optional inputs are now available to define colormaps for mean maps and map of differences independantly. 
* `colorMap` is the colormap used for means, standard deviations, ANOVA and effect sizes plots. Default is cbrewer('Reds').
* `colorMapDiff` is the colormap used for differences, relative differences and post-hoc spm plots. Default is cbrewer('RdBu').

Consequently, jet is not the default colormap anymore. 
I modified the readme.md file to reflect these changes, and created a new release of the function  (v1.4.1) 


Maybe @EtienneCmb ?

**Comment by EtienneCmb** [comment]
Hi all !

Agree with @cMadan , I wouldn't use jet neither. There's a recent Nature Comm paper about it, also comparing several colormaps : https://www.nature.com/articles/s41467-020-19160-7

**Comment by cMadan** [comment]
@EtienneCmb, would you be interested/available to review this submission?

@tramarobin, can you suggest anyone else? We normally have two reviewers for each submission.

**Comment by tramarobin** [comment]
@cMadan, oh yes sorry I can suggest @katschueler

**Comment by tramarobin** [comment]
@cMadan, Hi ! Hope your doing well 
As I am not familiar with this kind of review, should I suggest other reviewers as we have no answers from the previouly suggested ones ?

**Comment by tramarobin** [comment]
@cMadan & @kthyng,  is there something I can do as I don't have any answers ?

**Comment by kthyng** [comment]
Hi @tramarobin! Do you mean with respect to reviewers to suggest? We do ask submitting authors to look through the [list](https://bit.ly/joss-reviewers) of volunteers to find matches for your submission since you know your code best, and then list them here without using "@" so they aren't preemptively pinged. I see you've found 2. Can you find a handful more? You may also know people from your own science community and network who may be good reviewers, as long as they aren't conflicted with you. @cMadan will then request reviewers from your suggestions and/or others. 

Please let me know if you have other questions.

**Comment by tramarobin** [comment]
@kthyng, thanks for your answer, i didn't get the nuance of "without @"  

@cMadan, I suggest EtienneCmb, katschueler, daviddewhurst, marcoapintoo
Outside the list, I can suggest 0todd0000 who create the statistical analysis which is employed in my function.

**Comment by cMadan** [comment]
@EtienneCmb @daviddewhurst @0todd0000, would you be available and interested in reviewing this submission?

**Comment by EtienneCmb** [comment]
Hi @cMadan, sorry for the delay, unfortunately I'm already in the middle of multiple reviews.

**Comment by cMadan** [comment]
@EtienneCmb, no problem, thanks for letting me know!

**Comment by tramarobin** [comment]
@cMadan, do you want me to suggest other potential reviewers ?

**Comment by 0todd0000** [comment]
Apologies for my delayed reply, I saw the invitation a while ago but then lost it, so thank you for the reminder.  I'd be happy to review.  I don't see instructions for reviewers in this discussion, but please let me know if I've missed something.

**Comment by cMadan** [comment]
@0todd0000, that would be great, thank you! The detailed instructions, and review itself haven't started yet. Ideally we'd have two reviewers before we begin. 

@typically, would you be interested and available to review this? I think it is related to some of your current work and may even be useful to use there.

**Comment by cMadan** [comment]
@whedon add @0todd0000 as reviewer

**Comment by whedon** [comment]
OK, @0todd0000 is now a reviewer

**Comment by tramarobin** [comment]
@cMadan, as typically does not seem to answer, I can suggest nicholst. He is working in Matlab about Statistical non Parametric Mapping (SnPM), which is the approach chosen in my function to analyse two-dimensional data.

**Comment by cMadan** [comment]
@nicholst, would you be interested/available to review this submission?

@tramarobin, sorry we haven't been able to start the review yet. Hopefully we'll be able to soon!

**Comment by nicholst** [comment]
Sure @cMadan ... first time reviewing for JOSS... is there a reviewer's guide?

**Comment by tramarobin** [comment]
@cMadan, no problem I know it is sometimes difficult to find reviewers. 

@nicholst, thank you for accepting to review this paper. I think @cMadan will give you instructions soon as there are now two reviewers.

**Comment by cMadan** [comment]
@nicholst, thank you, that's great!

The reviewer guide is here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. When the review is started (moments from now), you'll have a checklist of what you're supposed to assess in the work--a bit different than with other journals since we're reviewing software, but same spirit of giving feedback and making sure it meets set expectations. That link has some related pages linked on the far-left that provide further guidance. Of course, I'm happy to answer questions as you do the review and there will be another reviewer as well. It's a relatively interactive and transparent process, so not in discrete rounds/etc as with most journals.

**Comment by cMadan** [comment]
@whedon add @nicholst as reviewer

**Comment by whedon** [comment]
OK, @nicholst is now a reviewer

**Comment by cMadan** [comment]
@0todd0000, it's been awhile, but hopefully you are still able to review this as well. I am going to start the review now, but do let me know if your availability has changed. You may also want to see the reviewer guidance I just commented above.

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3159.
