### ISSUE TITLE
[PRE REVIEW]: SimpleSDMLayers.jl and GBIF.jl: A Framework for Species Distribution Modeling in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2841]
**Submitting author:** @gabrieldansereau (<a href="http://orcid.org/0000-0002-2212-3584">Gabriel Dansereau</a>)
**Repository:** <a href="https://github.com/EcoJulia/SimpleSDMLayers.jl" target ="_blank">https://github.com/EcoJulia/SimpleSDMLayers.jl</a>
**Version:** v0.3.1
**Editor:** @KristinaRiemer
**Reviewers:** @dglmoore, @marcjwilliams1
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gabrieldansereau. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@gabrieldansereau if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.07 s (754.6 files/s, 40692.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           31            291             47           1347
Markdown                        14            203              0            725
YAML                             4              6              0             97
TeX                              1             10              0             92
TOML                             3              4              0             36
-------------------------------------------------------------------------------
SUM:                            53            514             47           2297
-------------------------------------------------------------------------------


Statistical information for the repository 'ea81b267fe9e8c09420417a6' was
gathered on 2020/11/13.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02841/joss.02841/10.21105.joss.02841.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02841/joss.02841/10.21105.joss.02841.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @KristinaRiemer! Can you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @KristinaRiemer as editor

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by KristinaRiemer** [comment]
@kthyng yes, I can be editor for this, thanks!

**Comment by KristinaRiemer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @KristinaRiemer

**Comment by KristinaRiemer** [comment]
@dglmoore @marcjwilliams1 @eviatarbach would you be able and willing to review this JOSS submission?

**Comment by eviatarbach** [comment]
Sorry, I am not able to review this submission.

**Comment by dglmoore** [comment]
@KristinaRiemer I would be happy to review this submission.

**Comment by marcjwilliams1** [comment]
I'm also happy to review.

**Comment by KristinaRiemer** [comment]
Thanks for getting back about it @eviatarbach, and thanks to @dglmoore & @marcjwilliams1 for being able to review this!

**Comment by KristinaRiemer** [comment]
@whedon assign @dglmoore as reviewer

**Comment by whedon** [comment]
OK, @dglmoore is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon add @marcjwilliams1 as reviewer

**Comment by KristinaRiemer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2872.

**Comment by KristinaRiemer** [comment]
@dglmoore @marcjwilliams1 the actual review will happen in the new issue linked to above. Feel free to ask me any questions over there, and to start your review at any time! Thanks again.
