### ISSUE TITLE
[REVIEW]: ADI.jl: A Julia Package for High-Contrast Imaging

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2843]
**Submitting author:** @mileslucas (<a href="http://orcid.org/0000-0001-6341-310X">Miles Lucas</a>)
**Repository:** <a href="https://github.com/JuliaHCI/ADI.jl" target ="_blank">https://github.com/JuliaHCI/ADI.jl</a>
**Version:** v0.5.3
**Editor:** @dfm
**Reviewer:** @giordano, @semaphoreP
**Archive:** <a href="https://doi.org/10.5281/zenodo.4323554" target="_blank">10.5281/zenodo.4323554</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/32605be405e024fcbd15cd81dfdf9985/status.svg)](https://joss.theoj.org/papers/32605be405e024fcbd15cd81dfdf9985)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/32605be405e024fcbd15cd81dfdf9985"><img src="https://joss.theoj.org/papers/32605be405e024fcbd15cd81dfdf9985/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/32605be405e024fcbd15cd81dfdf9985/status.svg)](https://joss.theoj.org/papers/32605be405e024fcbd15cd81dfdf9985)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JuliaHCI/ADI.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@giordano & @semaphoreP, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JuliaHCI/ADI.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mileslucas) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JuliaHCI/ADI.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mileslucas) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @giordano, @semaphoreP it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1538-3873/128/968/102001 is OK
- 10.1126/science.1102929 is OK
- 10.1086/500401 is OK
- 10.1088/2041-8205/755/2/L28 is OK
- 10.3847/1538-4357/aaa1f2 is OK
- 10.1137/141000671 is OK
- 10.1051/0004-6361/201834136 is OK
- 10.1109/TPDS.2018.2872064 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02843/joss.02843/10.21105.joss.02843.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02843/joss.02843/10.21105.joss.02843.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @semaphoreP, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @giordano, please update us on how your review is going.

**Comment by mileslucas** [comment]
@whedon preview

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by mileslucas** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02843/joss.02843/10.21105.joss.02843.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02843/joss.02843/10.21105.joss.02843.pdf) :page_facing_up: :point_left:

**Comment by semaphoreP** [comment]
Just finished the checklist. I am done reviewing I believe. Let me know if there's anything else.

**Comment by dfm** [comment]
@semaphoreP: Yes it looks like you're all set. Thank you very much for your review!!

**Comment by giordano** [comment]
I also just finished the checklist.  I'd like to mention that I had left some comments in `ADI.jl` bug tracker:

* https://github.com/JuliaHCI/ADI.jl/issues/26 about subtyping of a data structure
* https://github.com/JuliaHCI/ADI.jl/issues/27 about an error experienced while going through examples in the documentation
* https://github.com/JuliaHCI/ADI.jl/issues/30 more general suggestions about the documentation
* https://github.com/JuliaHCI/ADI.jl/issues/32 and https://github.com/JuliaHCI/ADI.jl/issues/34 reporting errors while running benchmarks

All reported issues have been resolved already.  I also opened a couple of pull requests with trivial changes:

* https://github.com/JuliaHCI/ADI.jl/pull/29 to fix a typo in documentation
* https://github.com/JuliaHCI/ADI.jl/pull/31 to make it possible to load the Julia environment for benchmarks

**Comment by mileslucas** [comment]
I'll mention, too, I have the working changes on the master branch ready to release, which will change the version to `0.5.3` (rather than the `0.5.2` when I initiated the submission).

**Comment by dfm** [comment]
@giordano and @semaphoreP: Thanks for reviews! I really appreciate your time and your constructive suggestions.

@mileslucas: There are two things for you to do before we do the final processing:

1. I submitted a PR with some small edits to the manuscript. Take a look at that, merge it, and double check the manuscript to see if there are any other edits that you want to make. Then, comment `@whedon generate pdf` on this thread and double check the proofs. In particular, check that the author names and affiliations are correct. This is harder to change later!
2. Release `v0.5.3` and create an archive for the version using Zenodo or similar. **Note: the title and author list on that archive must _exactly_ match the manuscript**. Report the DOI of that archive to this thread.

Thanks all!!

**Comment by mileslucas** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02843/joss.02843/10.21105.joss.02843.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02843/joss.02843/10.21105.joss.02843.pdf) :page_facing_up: :point_left:

**Comment by mileslucas** [comment]
@dfm All released and updated, the Zenodo link is https://zenodo.org/deposit/4323554 with the doi `10.5281/zenodo.4323554`

**Comment by dfm** [comment]
@mileslucas: Please update the metadata on the Zenodo archive to match the manuscript ([as requested above](https://github.com/openjournals/joss-reviews/issues/2843#issuecomment-745409496) in bold text :D). The title should be `ADI.jl: A Julia Package for High-Contrast Imaging` and the author list should be you and Michael Bottom. You don't need to make a new archive - you should be able to edit the metadata for the existing archive.

**Comment by mileslucas** [comment]
@dfm I don't know what to say: every time I edit the DOI it says it has the correct information.
![Screen Shot 2020-12-16 at 2 33 01 PM](https://user-images.githubusercontent.com/14099459/102403259-9a8fb980-3fab-11eb-87d8-363643c1c4a8.png)

Saving doesn't change anything and when I publish I get a server error

**Comment by dfm** [comment]
@mileslucas: Bizarre! It looks like you used some sort of GitHub actions workflow to publish your release? Perhaps it has something to do with that. Can you try uploading a new snapshot of the code with the right metadata to Zenodo directly? Thanks!

**Comment by mileslucas** [comment]
Yeah, I'm using the zenodo feature that automatically updates with each github release. I sent a support request to zenodo to see if that can be resolved before I upload a new version. I'll ping here when I've got it figured out.

**Comment by dfm** [comment]
Ok thanks! Ping me when you have it sorted and I'll take it from there.

**Comment by mileslucas** [comment]
I was told to ~turn it off and back on again~ discard the changes and re-submit and it seems to have worked-
https://zenodo.org/record/4323554

**Comment by mileslucas** [comment]
@dfm

**Comment by dfm** [comment]
@mileslucas: Excellent - Looks good now!

**Comment by dfm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1538-3873/128/968/102001 is OK
- 10.1126/science.1102929 is OK
- 10.1086/500401 is OK
- 10.1088/2041-8205/755/2/L28 is OK
- 10.3847/1538-4357/aaa1f2 is OK
- 10.1137/141000671 is OK
- 10.1051/0004-6361/201834136 is OK
- 10.1109/TPDS.2018.2872064 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@whedon set 10.5281/zenodo.4323554 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4323554" target="_blank">10.5281/zenodo.4323554</a> is the archive.

**Comment by dfm** [comment]
@whedon set v0.5.3 as version

**Comment by whedon** [comment]
OK. v0.5.3 is the version.

**Comment by dfm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1538-3873/128/968/102001 is OK
- 10.1126/science.1102929 is OK
- 10.1086/500401 is OK
- 10.1088/2041-8205/755/2/L28 is OK
- 10.3847/1538-4357/aaa1f2 is OK
- 10.1137/141000671 is OK
- 10.1051/0004-6361/201834136 is OK
- 10.1109/TPDS.2018.2872064 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1992

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1992, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by dfm** [comment]
@mileslucas: I've handed this off to the Editors-in-Chief to handle the final processing. They might have some last edits for the manuscript and once that's been sorted we'll have this published!

@giordano, @semaphoreP: Thanks for your reviews!! I really appreciate the time that you've put in and for your constructive recommendations for the code. Thanks again!!

**Comment by kthyng** [comment]
Everything looks to be in order! @mileslucas the summary in your paper is excellent! This is uncommon. 

We can proceed.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1339685450181697538) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1993
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02843](https://doi.org/10.21105/joss.02843)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @mileslucas! Thanks to editor @dfm and reviewers @giordano and @semaphoreP for your time and expertise!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02843/status.svg)](https://doi.org/10.21105/joss.02843)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02843">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02843/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02843/status.svg
   :target: https://doi.org/10.21105/joss.02843
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02843/status.svg)](https://doi.org/10.21105/joss.02843)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
