### ISSUE TITLE
[REVIEW]: AltaiPony - Flare science in Kepler, K2 and TESS light curves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2845]
**Submitting author:** @ekaterinailin (<a href="http://orcid.org/0000-0002-6299-7542">Ekaterina Ilin</a>)
**Repository:** <a href="https://github.com/ekaterinailin/AltaiPony" target ="_blank">https://github.com/ekaterinailin/AltaiPony</a>
**Version:** v2.0.1
**Editor:** @dfm
**Reviewer:** @afeinstein20, @mrtommyb
**Archive:** <a href="https://doi.org/10.5281/zenodo.4095339" target="_blank">10.5281/zenodo.4095339</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/344b45dac8496725be33ccf1cd902dc2/status.svg)](https://joss.theoj.org/papers/344b45dac8496725be33ccf1cd902dc2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/344b45dac8496725be33ccf1cd902dc2"><img src="https://joss.theoj.org/papers/344b45dac8496725be33ccf1cd902dc2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/344b45dac8496725be33ccf1cd902dc2/status.svg)](https://joss.theoj.org/papers/344b45dac8496725be33ccf1cd902dc2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ekaterinailin/AltaiPony" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@afeinstein20 & @mrtommyb, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ekaterinailin/AltaiPony">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ekaterinailin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ekaterinailin/AltaiPony">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ekaterinailin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @afeinstein20, @mrtommyb it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2845 with the following error: 

 Can't find any papers to compile :-(

**Comment by dfm** [comment]
@whedon generate pdf from branch josspaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch josspaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02845/joss.02845/10.21105.joss.02845.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02845/joss.02845/10.21105.joss.02845.pdf) :page_facing_up: :point_left:

**Comment by mrtommyb** [comment]
Hi @ekaterinailin I'm starting my review and working my way down the checklist. I'm at the item on Contribution and authorship. I have a question here. 
I notice that the software Appaloosa is described as this software’s predecessor and it looks like some of the code in this package is lifted from Appaloosa. I was wondering if you could explain a little about your authorship choices for this paper given the heritage of some of the code included.

**Comment by ekaterinailin** [comment]
Hi @mrtommyb ! First of all, thank you for volunteering as a reviewer. 

My reasoning on authorship was: I made what I thought was a default choice based on the Github history of the project. From Appaloosa, I ended up using and adapting three functions (the aflare model, and the flare search functions in the residual light curve). AltaiPony was written from scratch, and did not grow out of Appaloosa directly, so maybe _predecessor_ is not the right term to use in a technical sense, uncertain here. In the end, I decided to cite Jim's code in the paper, as I did with K2SC and lightkurve, from which I integrated functions and classes in a similar manner. 

Is there a consideration that I am missing here?

**Comment by whedon** [comment]
:wave: @afeinstein20, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @mrtommyb, please update us on how your review is going.

**Comment by afeinstein20** [comment]
Hi @ekaterinailin ! Thanks for writing AltaiPony and what a fantastic logo! The software was easy to install and run, with few to minor errors. I've recorded some of those below as well as some changes I think would make the functionality and the documentation better/easier for users!

**Installation**:
I had no trouble installing and using the software following both installation methods. However, I did receive the following errors that I wanted to note. And there are some dependencies I found were missing later one.
1. Through PyPI, I receive the following error: `FileNotFoundError: [Errno 2] No such file or directory: '//anaconda3/lib/python3.7/site-packages/K2SC-1.0-py3.7.egg'`
2. Through Github clone, I receive the following error: `error: scipy 1.4.1 is installed but scipy!=1.4.0,!=1.4.1,>=0.19.0 is required by {'lightkurve'}`
3. I ran into trouble with the progressbar on my personal machine! I assume this is a version error because it runs okay in a Google Colab notebook. Error: `TypeError: __init__() got an unexpected keyword argument 'max_value'`
4. I went to run the FFD functionality and was missing the `emcee` and `corner` dependencies. 

**Functionality**
1. It's unclear to me what the flare detection criteria are and if there's any way for me to change them. Are there any criteria I really shouldn't change? It looks like those criteria are stored in `find_flares_in_cont_obs_period` but there's no documentation for this function.
2. The injection-recovery tools and associated plots are super useful! It would be great to have a way to save these output figures, maybe through a keyword or by returning the figure instead of just plotting.
3. When I ran `simple_ffd.ed_and_freq()` from the documentation, it returned only 5 data points? I copied most of the lines from the demo notebooks in your documentation, so this is kind of weird! 

**Documentation**
1. Could use a bit more description in the opening about paragraph, since there's way more to this software than just "finding flares" (e.g. light curve downloading, detrending, flare fitting, injection-recovery tests, etc.)
2. Example usage could use some figures! As I was walking through the tutorials, it would have been nice to compare what my light curve looked like compared to what the docs expected.

**Software Paper**
The paper is overall clear and well written. It provides a good outline as to why the software is necessary and what it accomplishes compared to other flare detection methods. I believe the paper would benefit from a bit more description about details of flare detection and fitting: What is detected as a flare and not a flare? What are the default settings for flare detection? How the software handle the ramp ups at the end of TESS orbits? What is defined as a the start and stop time of a flare? Adding little details like this would be useful!

**Comment by ekaterinailin** [comment]
Hi @afeinstein20 ! Thanks a ton for the detailed review, these are all very helpful comments, and I am looking forward to addressing them to improve the software. I have a few busy weeks ahead of me, but I hope to get my hands on the code before the end of this year.

**Comment by ekaterinailin** [comment]
Hello again,

I finally got my hands on the code again, so here are my (proto-)solutions to @afeinstein20 's review:

- **Installation**
    - I had no [...] later on.
        - Through PyPI, I receive the following error: FileNotFoundError: [Errno 2] No such file or directory: '//anaconda3/lib/python3.7/site-packages/K2SC-1.0-py3.7.egg'
            - Not sure about that one because I am not familiar with the anaconda + python3.7 combo. The released version runs on python3.6. It would be awesome if you could open an issue on that for the next release (which will  probably be on python3.7, and K2SC is still going through some updates.
        - Through Github clone, I receive the following error: error: scipy 1.4.1 is installed but scipy!=1.4.0,!=1.4.1,>=0.19.0 is required by {'lightkurve'}
            - Hm. I updated a few dependencies now, maybe this solves the problem. At least there were no restrictions on scipy being the 1.4.1. version in requirements.txt or setup.py. I added the requirement to use scipy>1.5 in hope of improvement.
        - I ran into trouble with the progressbar on my personal machine! I 
assume this is a version error because it runs okay in a Google Colab 
notebook. Error: TypeError: __init__() got an unexpected keyword argument 'max_value'
            - Had this problem before, but was not sure where it came from.. It's perhaps to do with the default version fetched, I hope my attempts to solve the problem in [this issue](https://github.com/ekaterinailin/AltaiPony/issues/55) will help.
        - I went to run the FFD functionality and was missing the emcee and corner dependencies.
            - Ah, thanks! Added them to setup.py.
- **Functionality** 
    - It's unclear to me what the flare detection criteria are and if there's any way for me to change them. Are there any criteria I really shouldn't change? It looks like those criteria are stored in find_flares_in_cont_obs_period but there's no documentation for this function.
        - I added some more docs [here](https://altaipony.readthedocs.io/en/latest/tutorials/altai.html) to explain everything. Short answer: you can change everything now, but the default is a good heuristic in general, a bit generous perhaps.
    - The injection-recovery tools and associated plots are super useful! It would be great to have a way to save these output figures, maybe through a keyword or by returning the figure instead of just plotting.
        - Good idea! `FlareLightCurve.plot_ed_ratio_heatmap()` and `FlareLightCurve.plot_recovery_probability_heatmap()`  now both return a matplotlib figure. Updated the `Visualize_Injection_Recovery.ipynb` accordingly.
    - When I ran simple_ffd.ed_and_freq() from the documentation, it returned only 5 data points? I copied most of the lines from the demo notebooks in your documentation, so this is kind of  weird!
        - You mean [here](https://altaipony.readthedocs.io/en/latest/tutorials/ffds.html)? If your flc.flares table is short, this can totally be the case. But if you used the setup in ``Beginner_Flare_Frequency_Distributions_and_Power_Laws.ipynb`` this should not happen, because the toy example generates 200 events. I re-ran the notebook, and it looked fine. It would be cool, if you could open an issue with the script you used that failed to reproduce the example.
- **Documentation** 
    - Could use a bit more description in the opening about paragraph, since there's way more to this software than just "finding flares" (e.g. light curve downloading, detrending, flare fitting, injection-recovery tests, etc.)
        - New description in the about section, and more details in [Getting Started](https://altaipony.readthedocs.io/en/latest/install.html#getting-started) added!
    - Example usage could use some figures! As I was walking through the tutorials, it would have been nice to compare what my light curve looked like compared to what the docs expected.
        - Added light curves and an illustrative table to Finding Data, [Finding Flares](https://altaipony.readthedocs.io/en/latest/tutorials/altai.html)
        - Added heatmaps and an illustrative table to [Injection Recovery](https://altaipony.readthedocs.io/en/latest/tutorials/lcio.html).
- **Software Paper**
    - The paper [...] would benefit from a bit more description about details of flare detection and fitting: 
        - I think these are questions that users will regularly have, and since I expect them to go to the documentation for this, I opened a [FAQ section](https://altaipony.readthedocs.io/en/latest/faq.html) in the docs that addresses them in some detail. I only added a few words to the paper to make the definition of flare candidates more clear.
        - What is detected as a flare and not a flare?
            - I added a section to the [Finding Flares](https://altaipony.readthedocs.io/en/latest/tutorials/altai.html#defining-flare-candidates) tutorial that goes into detail here, and I link to it in the FAQs. 
        - What are the default settings for flare detection?
            - Also answered in [Finding Flares](https://altaipony.readthedocs.io/en/latest/tutorials/altai.html#defining-flare-candidates), answers linked in FAQs. 
        - How the software handle the ramp ups at the end of TESS orbits?
            - It doesn't unless your de-trending algorithm is tailored to do it. I added instructions on how to pass a custom de-trending function to `FlareLightCurve.find_flares() 
        - What is defined as a the start and stop time of a flare?
            - Answered this in the FAQs, and added an example on how to mask flares based on flare start and stop indices. 

Let me know if I understood your remarks correctly! Happy new year :smiley_cat:

**Comment by dfm** [comment]
I'm pinging @mrtommyb to keep this on his radar as we roll into the new year.

**Comment by dfm** [comment]
:wave: @afeinstein20 and @mrtommyb: I wanted to check in with you both to see how your reviews are going. Let me know if you have any questions or issues. Thanks for your work on this so far!!

**Comment by afeinstein20** [comment]
Hi @ekaterinailin ! Thanks for addressing all of the points! I'm very happy with the updates 😄  The additional docs and FAQ section are super useful. I just have 2 additional comments/issues:
     
 * Good idea! `FlareLightCurve.plot_ed_ratio_heatmap()` and `FlareLightCurve.plot_recovery_probability_heatmap()`  now both return a matplotlib figure. Updated the `Visualize_Injection_Recovery.ipynb` accordingly.
- I'm glad you agreed this would be useful! Unfortunately, now I'm running into some issues the way the values are being binned. I've been running everything in this [Google Colab](https://colab.research.google.com/drive/1xmPHhHI4mpGcq01wlS1n6u07gtmpDt4V?usp=sharing) notebook. I think if you open it, the error messages should appear as well?

_* You mean [here](https://altaipony.readthedocs.io/en/latest/tutorials/ffds.html)? ... example._
- Yup this was totally the issue! I thought in your docs you were computing the FFD for TIC 29780677. But I know realize it was for GJ 1243, although I'm still getting fewer points still. This is probably because I've set `iterations=50` for the `flc.sample_flare_recovery()` just for time's sake. Does that sound right to you?

I've gone ahead and checked all of the boxes on my review list, since you've covered everything on my end! Hopefully these 2 minor things listed above are easily fixed!

**Comment by mrtommyb** [comment]
Sorry that it took me a while to get back to this. I reinstalled the package, and I installed from the github repo. A few things to note
* it would be useful if altaipony.__version__ returned a version number. 
* I followed the getting started notebook and the from_mast function doesn't work for me. 
```python
TypeError: __init__() got an unexpected keyword argument '_required_columns'
```
I think the issue is that altaipony is incompatible with lightkurve version 2.x. I think that this should probably be fixed before this is accepted. 

* I was trying to work out if I could download the data and then import that data into a FlareLightCurve object but I could not work out how to do that. This meant that I could not test the additional functionality.
* I didn't see any information on how to contribute to the project.

**Comment by ekaterinailin** [comment]
You're right, @mrtommyb , the new version of lightkurve is incompatible with AltaiPony, and it slipped me. I did two things to fix this:

1. restricted allowed lightkurve versions (2.x seems incompatible with K2SC light curves, but I'd like to keep that functionality because people still work on those data. The new version also breaks **a lot more** than just `from_mast`, so I think this will not be fixed before major refactoring happens in AltaiPony 2.0.)
2. set up a weekly CI build to notice such failures promptly.

**Comment by ekaterinailin** [comment]
As for the other requests:

- `altaipony.__version__` now returns the version
- added a "Contribute to AltaiPony" paragraph on the front page in the docs and in the repo README

**Comment by ekaterinailin** [comment]
@afeinstein20 Thanks for the comments!

>  Unfortunately, now I'm running into some issues the way the values are being binned. I've been running everything in this Google Colab notebook. I think if you open it, the error messages should appear as well?

Yes, I can see the error message, and I could indeed reproduce your heatmap error! The pansdas version 1.1.5 is the culprit and I actually fixed that in the requirements back in December (see the [log](https://github.com/ekaterinailin/AltaiPony/commits/master/requirements.txt)), but it was not included in the 1.0.0. version. It should now work with a fresh installation of version 1.0.1 :)

@mrtommyb This should also fix the pip installation problems with lightkurve for the moment.

> Yup this was totally the issue! I thought in your docs you were computing the FFD for TIC 29780677. But I know realize it was for GJ 1243, although I'm still getting fewer points still. This is probably because I've set iterations=50 for the flc.sample_flare_recovery() just for time's sake. Does that sound right to you?

Looking into your Google Colab notebook your results look correct. 16 +/- 2 or so flares is what you'd find in that GJ 1243 light curve. Nothing to do with sample_flare_recovery and the 50 iterations, though. The synthetic flares are stored in `flc.fake_flares`.

**Comment by mrtommyb** [comment]
Thanks for your response @ekaterinailin. I think that the tight integration with Lightkurve means that not having the software compatible with Lightkurve 2 means that the software is not entirely functional. I think that it's important to be able to use the current release of Lightkurve, without pinning the installation to an old and unmaintained version of Lightkurve.

**Comment by dfm** [comment]
Thanks @mrtommyb!

@ekaterinailin: I agree with Tom that lightkurve compatibility is pretty crucial since it's a major dependency, but also a common element in the workflow of many of your users. I think that it would be worth taking the time to look carefully into what it would take to support lightkurve 2+. Even better, how painful would it be to support both? If it's really infeasible, one option would be to add a prominent version disclaimer to the README and docs, and open an issue describing the steps that would be needed so that folks could contribute.

**Comment by ekaterinailin** [comment]
@mrtommyb @dfm Agreed! I have a few deadlines coming up, but I hope that  - if feasible - I can make lightkurve2+ compatibility happen in early April. If that works out I also shall see if I can make the software work for both old and new lightkurve :+1:

**Comment by ekaterinailin** [comment]
Hi @dfm, I finally got back to it. Not quite early April - but now AltaiPony 2.0. is available, test and notebooks seem to run with lightkurve2.0 :)

**Comment by dfm** [comment]
@ekaterinailin: Great to hear!

@mrtommyb: Are you be available to revisit your checklist now that we have compatibility with lightkurve 2?

**Comment by mrtommyb** [comment]
Hi @ekaterinailin, I've still working on a the examples, but one very quick thing is that in the Readme you have GitHub and email listed in several places that look like links but they don't link to anywhere.

**Comment by ekaterinailin** [comment]
> Hi @ekaterinailin, I've still working on a the examples, but one very quick thing is that in the Readme you have GitHub and email listed in several places that look like links but they don't link to anywhere.

You're right, thanks! Fixed both links :)

**Comment by mrtommyb** [comment]
Sorry this took me forever to get finished. I'm very happy with the changes made.

**Comment by ekaterinailin** [comment]
Thank you @mrtommyb ! I'll look into the warnings - can you recall what numpy version you were working with when you got the warnings?

**Comment by dfm** [comment]
Thanks @mrtommyb!

@ekaterinailin: Give me a day or two to do a final pass through the paper, etc. and then I'll have a few last administrative tasks before publication. Thanks for your patience!!

**Comment by dfm** [comment]
@ekaterinailin: I've opened a tiny pull request with an update for the references. Can you take a look at that and once you've merged, please take the following steps:

- Comment `@whedon generate pdf from branch josspaper` on this thread and read through the manuscript to make sure that you're happy with it (it's hard to make changes later!), especially check that your name and affiliation are correct.
- Increment the version number of the software and report that version number back here.
- Create an archived release of that version of the software (using Zenodo or something similar). **Please make sure that the metadata (title and author list) exactly match the paper.** Then report the DOI of the release back to this thread.

Let me know if you have questions or run into any issues!

**Comment by ekaterinailin** [comment]
@whedon generate pdf from branch josspaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch josspaper. Reticulating splines etc...
```

**Comment by ekaterinailin** [comment]
Thank you for updating and checking the references, @dfm ! I read through the paper - looks complete and correct to me.

The newest version of AltaiPony is now 2.0.1., and the corresponding DOI is [10.5281/zenodo.4095339](https://zenodo.org/record/5040830#.YNsVujqxUn4)

**Comment by dfm** [comment]
@whedon check references from branch josspaper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch josspaper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/202039198 is OK
- 10.1051/0004-6361/201834400 is OK
- 10.1093/mnras/stw706 is OK
- 10.1086/670067 is OK
- 10.3847/0004-637X/829/1/23 is OK
- 10.1088/0004-637X/797/2/122 is OK
- 10.1093/mnras/staa2021 is OK
- 10.1111/j.1365-2966.2009.14577.x is OK
- 10.1086/421261 is OK
- 10.1088/2041-8205/713/2/L79 is OK
- 10.1086/676406 is OK
- 10.1117/1.JATIS.1.1.014003 is OK
- 10.21105/joss.02347 is OK

MISSING DOIs

- 10.3847/1538-4365/abe70e may be a valid DOI for title: Allesfitter: Flexible Star and Exoplanet Inference From Photometry and Radial Velocity

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@whedon set 10.5281/zenodo.4095339 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4095339" target="_blank">10.5281/zenodo.4095339</a> is the archive.

**Comment by dfm** [comment]
@whedon set v2.0.1 as version

**Comment by whedon** [comment]
OK. v2.0.1 is the version.

**Comment by dfm** [comment]
@ekaterinailin: Thanks!! I opened one last PR with a reference update - sorry about that! Once you merge that, we're good to go.

**Comment by dfm** [comment]
@whedon generate pdf from branch josspaper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch josspaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02845/joss.02845/10.21105.joss.02845.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02845/joss.02845/10.21105.joss.02845.pdf) :page_facing_up: :point_left:

**Comment by dfm** [comment]
@whedon recommend-accept from branch josspaper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/202039198 is OK
- 10.1051/0004-6361/201834400 is OK
- 10.1093/mnras/stw706 is OK
- 10.1086/670067 is OK
- 10.3847/0004-637X/829/1/23 is OK
- 10.1088/0004-637X/797/2/122 is OK
- 10.1093/mnras/staa2021 is OK
- 10.1111/j.1365-2966.2009.14577.x is OK
- 10.1086/421261 is OK
- 10.1088/2041-8205/713/2/L79 is OK
- 10.3847/1538-4365/abe70e is OK
- 10.1086/676406 is OK
- 10.1117/1.JATIS.1.1.014003 is OK
- 10.21105/joss.02347 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dfm** [comment]
🎉  @ekaterinailin: This has now been passed to the Editors-in-Chief who will do a final pass (they might have some last edits) and then press the publish button. Thanks for this submission and all of your work through this process.

@afeinstein20, @mrtommyb: Thank you for your constructive reviews. I really appreciate all the work you put in here!!

**Comment by ekaterinailin** [comment]
Thank you all for getting AltaiPony through the review process, your work and your patience, @dfm @mrtommyb @afeinstein20 :raised_hands: I am very happy with the result :)

**Comment by arfon** [comment]
@whedon accept deposit=true from branch josspaper

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1410188648608415755) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2424
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02845](https://doi.org/10.21105/joss.02845)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@afeinstein20, @mrtommyb – many thanks for your reviews here and to @dfm for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@ekaterinailin – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02845/status.svg)](https://doi.org/10.21105/joss.02845)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02845">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02845/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02845/status.svg
   :target: https://doi.org/10.21105/joss.02845
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02845/status.svg)](https://doi.org/10.21105/joss.02845)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by ekaterinailin** [comment]
> @ekaterinailin – your paper is now accepted and published in JOSS 

Thanks for wrapping it up so quickly, @arfon !
