### ISSUE TITLE
[PRE REVIEW]: Parent-map: analysis of parental contributions to evolved or engineered protein or DNA sequences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2846]
**Submitting author:** @damienmarsic (<a href="http://orcid.org/0000-0003-0847-8095">Damien Marsic</a>)
**Repository:** <a href="https://github.com/damienmarsic/Parent-map" target ="_blank">https://github.com/damienmarsic/Parent-map</a>
**Version:** 1.1.0
**Editor:** @csoneson
**Reviewers:** @xie186, @j-andrews7
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @damienmarsic. **Currently, there isn't an JOSS editor assigned** to your paper.

@damienmarsic if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ymthe.2017.09.006 is OK
- 10.1016/j.omtm.2019.10.007 is OK
- 10.1038/nbt.3440 is OK
- 10.1073/pnas.0813365106 is OK
- 10.1038/mt.2014.139 is OK
- 10.1016/j.ymthe.2017.09.021 is OK
- 10.1038/gt.2016.62 is OK
- 10.1038/nbt.1599 is OK
- 10.1038/mt.2010.234 is OK
- 10.1016/j.neuron.2016.09.021 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.1021/acssynbio.8b00373 is OK
- 10.1128/JVI.00254-08 is OK
- 10.1126/scitranslmed.3005708 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.21 s (135.0 files/s, 85339.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       9           2289           2314           8441
CSS                              4            324             50           1240
Python                           2             60             52           1180
HTML                             5            327              0           1143
reStructuredText                 4            156              8            350
TeX                              1             14              0            242
Markdown                         2             26              0             56
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            29           3208           2432          12687
-------------------------------------------------------------------------------


Statistical information for the repository '0bf81d5fd748a888a17aff65' was
gathered on 2020/11/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Damien Marsic                    7          2313           1163           20.68
Damien Marsic(Porton             5         13258             72           79.32

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Damien Marsic              1080           46.7          0.1                1.57
Damien Marsic(Porton      13256          100.0          0.2               17.74
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02846/joss.02846/10.21105.joss.02846.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02846/joss.02846/10.21105.joss.02846.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @luizirber - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @luizirber as editor

**Comment by whedon** [comment]
@luizirber has been invited to edit this submission.

**Comment by damienmarsic** [comment]
Hi,

Suggested reviewers

AngryMaciek
xie186
BjornFJohansson
j-andrews7
aponsero
j-andrews7
sigven
AhmedArslan
Datakid
Tijeco

Best regards,

Damien

	




From: whedon
Sent: Thursday, November 19, 2020 01:26
To: openjournals/joss-reviews
Cc: Damien Marsic; Mention
Subject: [openjournals/joss-reviews] [PRE REVIEW]: Parent-map: analysis ofparental contributions to evolved or engineered protein or DNA sequences(#2846)

Submitting author: @damienmarsic (Damien Marsic)
Repository: https://github.com/damienmarsic/Parent-map
Version: 1.1.0
Editor: Pending
Reviewer: Pending
Managing EiC: Daniel S. Katz
⚠️ JOSS reduced service mode ⚠️
Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in our blog post.
Author instructions
Thanks for submitting your paper to JOSS @damienmarsic. Currently, there isn't an JOSS editor assigned to your paper.
@damienmarsic if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this list of people have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
Editor instructions
The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:
@whedon commands

**Comment by arfon** [comment]
:wave: @csoneson - would you be willing to edit this submission for JOSS?

**Comment by csoneson** [comment]
Sure, I can take this one.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @xie186, @BjornFJohansson, @j-andrews7 - would two of you be interested in reviewing this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues, following these [guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html).

> Parent-map: analysis of parental contributions to evolved or engineered protein or DNA sequences

**Comment by xie186** [comment]
@csoneson I'm interested in reviewing this submission. Thanks for the invitation.

**Comment by j-andrews7** [comment]
@csoneson I'm also happy to review this.

**Comment by csoneson** [comment]
Oh wow, that was fast :) thanks both! I will start the review tomorrow.

**Comment by csoneson** [comment]
@whedon assign @xie186 as reviewer

**Comment by whedon** [comment]
OK, @xie186 is now a reviewer

**Comment by csoneson** [comment]
@whedon add @j-andrews7 as reviewer

**Comment by whedon** [comment]
OK, @j-andrews7 is now a reviewer

**Comment by csoneson** [comment]
Just for completeness: @BjornFJohansson - I think we're all set on the reviewer side for this submission, but I hope we can get back to you for another submission in the future. Thanks for volunteering to review for JOSS!

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2864.
