### ISSUE TITLE
[PRE REVIEW]: Chromanomer: A Javascript Library enabling Universally Accessible Color Selection through Intutive Naming Conventions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2847]
**Submitting author:** @arvindcheenu (<a href="http://orcid.org/0000-0002-3409-6077">Arvind Srinivasan</a>)
**Repository:** <a href="https://github.com/arvindcheenu/Chromanomer" target ="_blank">https://github.com/arvindcheenu/Chromanomer</a>
**Version:** 1.0.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @arvindcheenu. **Currently, there isn't an JOSS editor assigned** to your paper.

@arvindcheenu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "url" (NAME) [#<BibTeX::Bibliography data=[4]>, "@", #<BibTeX::Entry >, {:title=>["ntc js (Name that Color JavaScript) - Chirag Mehta : chir.ag"]}]

**Comment by whedon** [comment]
PDF failed to compile for issue #2847 with the following error: 

 Error reading bibliography file paper.bib:
(line 29, column 3):
unexpected "u"
expecting space, ",", white space or "}"
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.12 s (276.7 files/s, 206809.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Sass                             5              3              1          22222
JavaScript                      13              1             14            795
Markdown                         9            249              0            728
JSON                             3              0              0            374
TeX                              1              0              0            133
CSS                              1             48              0             99
YAML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            33            301             15          24352
-------------------------------------------------------------------------------


Statistical information for the repository 'a040dffd8ddf40ef0b5cad7a' was
gathered on 2020/11/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Arvind                          21           924            448          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Arvind Srinivasan           810          100.0          0.0                1.73
```

**Comment by danielskatz** [comment]
Hi @arvindcheenu
You need a comma at the end of line 28 of your .bib file.  Feel free to try to generate the PDF and check the references again with the following comments, which each need to be on the first line of a new comment:
* ```@whedon generate pdf```
* ```@whedon check references```

Additionally, the next step in our process will be a discussion of the editors about scope and contribution, which is automatic for anything with this amount of code - we'll get back to you next week.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
Also, can you explain how this is research software? What fields/areas of research need to use this software?

**Comment by arvindcheenu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2847 with the following error: 

 Error reading bibliography file paper.bib:
(line 20, column 1):
unexpected "y"
expecting space, ",", white space or "}"
Looks like we failed to compile the PDF

**Comment by arvindcheenu** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "year" (NAME) [#<BibTeX::Bibliography data=[2]>, "@", #<BibTeX::Entry >, {:title=>["Color Name & Hue – Colblindor"], :url=>["https://www.color-blindness.com/color-name-hue/"], :author=>["Flueck, Daniel"]}]

**Comment by arvindcheenu** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "abstractNote" (NAME) [#<BibTeX::Bibliography data=[14]>, "@", #<BibTeX::Entry >, {:url=>["https://www.hsluv.org/"], :title=>["HSLuv"]}]

**Comment by arvindcheenu** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "abstractNote" (NAME) [#<BibTeX::Bibliography data=[14]>, "@", #<BibTeX::Entry >, {:url=>["https://www.hsluv.org/"], :title=>["HSLuv"]}]

**Comment by arvindcheenu** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCG.1982.1674223 is OK
- 10.1111/j.1467-8659.2008.01203.x is OK

MISSING DOIs

- 10.2307/2798490 may be a valid DOI for title: Basic color terms: Their universality and evolution
- 10.1002/col.5080060303 may be a valid DOI for title: NCS—Natural Color System: a Swedish standard for color notation
- 10.1002/col.22355 may be a valid DOI for title: Describing natural colors with Munsell and NCS color systems
- 10.1109/83.597279 may be a valid DOI for title: A study of efficiency and accuracy in the transformation from RGB to CIELAB color space
- 10.1002/9781118653128.ch10 may be a valid DOI for title: Color appearance models

INVALID DOIs

- None
```

**Comment by arvindcheenu** [comment]
@whedon check references

**Comment by arvindcheenu** [comment]
@whedon check references
@whedon generate pdf

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2307/2798490 is OK
- 10.1002/col.5080060303 is OK
- 10.1109/MCG.1982.1674223 is OK
- 10.1002/col.22355 is OK
- 10.1109/83.597279 is OK
- 10.1111/j.1467-8659.2008.01203.x is OK
- 10.1002/9781118653128.ch10 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arvindcheenu** [comment]
@whedon  commands

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arvindcheenu** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2307/2798490 is OK
- 10.1002/col.5080060303 is OK
- 10.1109/MCG.1982.1674223 is OK
- 10.1002/col.22355 is OK
- 10.1109/83.597279 is OK
- 10.1111/j.1467-8659.2008.01203.x is OK
- 10.1002/9781118653128.ch10 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arvindcheenu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02847/joss.02847/10.21105.joss.02847.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02847/joss.02847/10.21105.joss.02847.pdf) :page_facing_up: :point_left:

**Comment by arvindcheenu** [comment]
@whedon generate pdf

Added dates for a couple bibliography. Rectified labelling of referenced figure.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02847/joss.02847/10.21105.joss.02847.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02847/joss.02847/10.21105.joss.02847.pdf) :page_facing_up: :point_left:

**Comment by arvindcheenu** [comment]
> Also, can you explain how this is research software? What fields/areas of research need to use this software?

@danielskatz Thanks a lot for your valuable inputs. I have successfully generated the PDF after making the necessary changes based on it. 

Regarding the scope of this software, please see below:

## Brief Summary on Scope and Need
### Who might use this software for research purposes?
* Data Visualisation Specialists
* UX Research Specialists 
### You might need this software if...
* You are **visually impaired Data Visualisation Specialist** (varying degrees of blindness or color-blindness)
* You are a Data Visualisation Specialist in need an intuitive way of **describing color palettes for visualisation**
* You are a UX Research Specialist trying to **maximise the accessibility** of your data visualisation software

## Extended Description on Scope and Need

Quoting from my paper's **Statement of Need**:

The *Chromanomer* Javascript Library attempts to address these shortcomings by implementing a better color naming system that names a broader gamut of colors than any existing open-source solution while maintaining a shallow learning curve. By adopting an object-based modeling approach, this library is built with accessibility, customisability and internationalization in mind. Through the use of CSS preprocessors like Sass, the generation of colors is automated, thus enabling ease of use. *Chromanomer*'s concise API is functional and chainable by design. Ranging from Color conversions and Lookups to Palette Generation and Transformations for Color Blindness, *Chromanomer* offers a consummate collection of methods for the most pressing use-cases. Furthermore, *Chromanomer* also provides a colorful commandline interface visually representing colors as named swatches.  

*Chromanomer* is a software designed with the needs of Data Visualisation Specialists and UX Researchers in mind. Notably, Graphic Designers and Data Visualisation Specialists can incorporate colors into their designs with confidence and ease irrespective of their varying degrees of visual disability. API Implementation for Palette Generation and Greedy Selection are deliberately minimal and extensible by design to ensure its ease of use. UX Researchers, on the other hand, are now offered additional context that helps them arrive at substantial insights into the design process of visually impaired users, if this tool can be incorporated in a product offering that is being tested. In brief, the ultimate goal of *Chromanomer* is to **make access to color universal.**

**Comment by arfon** [comment]
@whedon reject 

@arvindcheenu - many thanks for the additional context here. While this does seem like useful software for _Data Visualisation Specialists_ and _UX Research Specialists_, we still consider this submission out of scope and not within our scope definition for [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) which is.

**Comment by whedon** [comment]
Paper rejected.
