### ISSUE TITLE
[PRE REVIEW]: EBSCOHost XML Parser Excel macro

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#285]
**Submitting author:** @profwhy (<a href="http://orcid.org/0000-0002-5144-968X">Yana Weinstein</a>)
**Repository:** <a href="https://github.com/profwhy/cite-managers" target ="_blank">https://github.com/profwhy/cite-managers</a>
**Version:** V1.0
**Editor:** @cmadan
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @profwhy. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@profwhy if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cMadan** [comment]
@whedon set @cmadan as editor

**Comment by cMadan** [comment]
@whedon assign @cmadan as editor

**Comment by whedon** [comment]
OK, the editor is @cmadan

**Comment by cMadan** [comment]
Hi @profwhy, I took a quick look at your submission and have a few suggestions before we start the actual review.
- Can you include an example XML input file, and an example output file (preferably saved in an 'open' format like CSV) so a user can test your software with a known input/output
- More documentation of how it works is necessary
- Preferably include a snippet of example output in the README.md
- The paper.md should more clearly describe the purpose of the software, you may want to look over JOSS' Reviewer Guidelines (http://joss.theoj.org/about#reviewer_guidelines)
- You don't need to reference the Github repo itself in the paper.md

That said, I need to confirm with other editors (@arfon?) that this submission qualifies as 'open source' since the Excel macro file itself (xlsm) is a propriety binary file

**Comment by arfon** [comment]
> That said, I need to confirm with other editors (@arfon?) that this submission qualifies as 'open source' since the Excel macro file itself (xlsm) is a propriety binary file

I'm learning towards saying this isn't acceptable as there's no open source _code_ here (I realize that Excel doesn't really make this an option): https://opensource.org/faq#non-distribution

What do @openjournals/joss-editors think?

**Comment by labarba** [comment]
It looks like this is a utility to extract bibliographic information from a proprietary database (EBSCOHost) into an Excel spreadsheet. First, I agree that this is not "open-source code." Second, even if this was, say, a Python script, it still would not be research software. I would categorize this application as information or library services. 

We need to stay the course with JOSS as a venue for *research software*, meaning a code package that is an instrument for generating research data, for virtual experiments leading to new scientific findings.

**Comment by arfon** [comment]
> I would categorize this application as information or library services.

Yes, me too. I didn't have an instinctive response though that this package isn't a valid use-case though. My reason being that I've been thinking that the following (from JOSS submission criteria):

> Your software should have a research application

..._could_ include software that's part of the research cycle, that is, software that is tailored to the needs of a research audience. That might include the definitions you've written here @labarba but could also include packages that help a researcher do their work (e.g. [BioPandas](http://joss.theoj.org/papers/d611893a9442b7dd421e2a1622a3da18)) that we just accepted last week.

We should probably take this discussion to a dedicated thread but regardless I suspect that the binary-nature of this submission @profwhy means that this isn't compatible with JOSS I'm afraid.

**Comment by cMadan** [comment]
Thanks for your thoughts on this, @arfon and @labarba.

@profwhy - Unfortunately it looks like your submission doesn't fit the criteria for publication at JOSS. I do think it's a useful tool though, and I hope you nonetheless improve the documentation so that others can more easily benefit from it.
