### ISSUE TITLE
[PRE REVIEW]: circleclust: A spatiotemporal clustering algorithm for personal location data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2851]
**Submitting author:** @wolfeclw (<a href="http://orcid.org/0000-0002-5882-1149">Christopher Wolfe</a>)
**Repository:** <a href="https://github.com/wolfeclw/circleclust" target ="_blank">https://github.com/wolfeclw/circleclust</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @wolfeclw. **Currently, there isn't an JOSS editor assigned** to your paper.

@wolfeclw if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (705.2 files/s, 82496.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            18            839            228           1919
R                               20            240            321            987
XML                              1              0              2            441
CSS                              3             99             48            428
JavaScript                       3             64             32            256
Markdown                         4             55              0            122
TeX                              2              9              0             92
SVG                              1              0              1             11
YAML                             1              1              0              5
-------------------------------------------------------------------------------
SUM:                            53           1307            632           4261
-------------------------------------------------------------------------------


Statistical information for the repository '955a6ed5eaedf7be0762ba39' was
gathered on 2020/11/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Chris Wolfe                      1           352              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chris Wolfe                 352          100.0          0.0                9.09
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1039/b903841h is OK
- 10.1186/1476-069X-13-33 is OK
- 10.2196/mhealth.5771 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02851/joss.02851/10.21105.joss.02851.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02851/joss.02851/10.21105.joss.02851.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@wolfeclw - due to the relatively small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  We should get back to you sometime next week.  Also, I notice your journal titles in the references are in ALLCAPS, which isn't JOSS's style. If you want to fix this, you can, then use the following command (as the first line of a new comment) to regenerate the PDF.
* ```@whedon generate pdf```

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by wolfeclw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02851/joss.02851/10.21105.joss.02851.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02851/joss.02851/10.21105.joss.02851.pdf) :page_facing_up: :point_left:

**Comment by wolfeclw** [comment]
@danielskatz Thank you for the opportunity to publish with JOSS.  As you review my submission, please consider my previous package [`pufpR`](https://github.com/wolfeclw/pufpR/graphs/traffic) as you evaluate whether `circleclust` meets the requirements for substantial scholarly effort.  

A considerable amount of the codebase in `pufpR` has been implemented in `circleclust`.  While there are similarities in the packages, the functions included in `pufpR` are specific to the Enmont Personal Ultrafine Particle (PUFP) sensor.  I created the `circleclust` package to convert the functions and clustering algorithm in `pufpR` into a more generalizable form.  `circleclust` functions can be applied across output data from other GPS sensors.

**Comment by kthyng** [comment]
Hi @wolfeclw and thanks for your submission. Unfortunately, the editorial board did decide that this submission is a bit too thin to pass our [scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) bar. 

I don't quite understand your comment above, but if you mean that the `pufpR` package should also be reviewed with `circleclust`, it's possible that would be a different situation. If you want to pursue that case, you should resubmit with that clearly explained in your paper and the submission. As it is, in addition to the small size, there was also concern that this submission does not have enough functionality to justify publication, and doesn't appear to acknowledge a larger package in the field that may do similar work (https://github.com/anitagraser/movingpandas).

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
