### ISSUE TITLE
[PRE REVIEW]: SpeedDate.jl

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2852]
**Submitting author:** @BenJWard (<a href="http://orcid.org/0000-0001-6337-5238">Ben J. Ward</a>)
**Repository:** <a href="https://github.com/vanOosterhoutLab/SpeedDate.jl" target ="_blank">https://github.com/vanOosterhoutLab/SpeedDate.jl</a>
**Version:** v0.3.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @BenJWard. **Currently, there isn't an JOSS editor assigned** to your paper.

@BenJWard if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (603.1 files/s, 28821.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                            7             72             28            349
Markdown                         5             67              0            181
YAML                             4              8              1            100
TeX                              1              5              0             63
TOML                             2              5              0             29
-------------------------------------------------------------------------------
SUM:                            19            157             29            722
-------------------------------------------------------------------------------


Statistical information for the repository '0adbbde5d0c1a189fb892025' was
gathered on 2020/11/20.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02852/joss.02852/10.21105.joss.02852.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02852/joss.02852/10.21105.joss.02852.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1111/1755-0998.12469 may be a valid DOI for title: HYBRIDCHECK: software for the rapid detection, visualization and dating of recombinant regions in genome sequence data
- 10.1038/s41564-019-0377-x may be a valid DOI for title: Evolutionary genomics of anthroponosis in Cryptosporidium
- 10.1038/s41467-019-08809-7 may be a valid DOI for title: Hybridization is a recurrent evolutionary stimulus in wild yeast speciation

INVALID DOIs

- https://doi.org/10.1111/mec.13213 is INVALID because of 'https://doi.org/' prefix
```

**Comment by danielskatz** [comment]
@BenJWard - due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  We should get back to you sometime next week.  If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.
* ```@whedon generate pdf```
* ```@whedon check references```

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@whedon reject

@BenJWard - many thanks for your submission to JOSS. The JOSS editorial team has concluded that this submission is out of scope as it does not meet our guidelines for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by whedon** [comment]
Paper rejected.
