### ISSUE TITLE
[PRE REVIEW]: 3dfier: automatic reconstruction of 3D city models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2853]
**Submitting author:** @hugoledoux (<a href="http://orcid.org/0000-0002-1251-8654">Hugo Ledoux</a>)
**Repository:** <a href="https://github.com/tudelft3d/3dfier" target ="_blank">https://github.com/tudelft3d/3dfier</a>
**Version:** v1.3.0
**Editor:** @arfon
**Reviewers:** @GANys, @chenkianwee
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @hugoledoux. **Currently, there isn't an JOSS editor assigned** to your paper.

@hugoledoux if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.72 s (242.9 files/s, 61188.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                    16           2533           4876           8500
CSS                             10           1473             65           7842
C++                             14            592            749           5848
SVG                              3              0              0           3479
YAML                            36            151             58           2216
Markdown                        26            511              0           1529
JavaScript                       7            317            535            920
HTML                            36            176             55            867
XML                              4              4              0            298
Python                           4             31             15            189
Bourne Shell                     8             28             25            108
TeX                              1             18              0             68
Dockerfile                       2             12              4             63
JSON                             4              8              0             57
CMake                            2             24             13             51
DOS Batch                        3              2              0             32
-------------------------------------------------------------------------------
SUM:                           176           5880           6395          32067
-------------------------------------------------------------------------------


Statistical information for the repository 'e2ba67312e06f295b225cbf1' was
gathered on 2020/11/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Clemens Rudert                   1            12              5            0.02
Hugo Ledoux                    354         27473          22716           60.05
Ivan Paden                       7           359            128            0.58
Ravi Peters                      6            25              7            0.04
Tom Commandeur                 397         18494          13534           38.32
Ylannl                          16           504            225            0.87
tcommandeur                      1             2              4            0.01
tjfcommandeur                    2            78             14            0.11

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Clemens Rudert               11           91.7         12.5                0.00
Hugo Ledoux               17437           63.5         36.2               36.84
Ivan Paden                  266           74.1          0.5                4.51
Tom Commandeur             7148           38.7         28.2               14.03
Ylannl                      243           48.2         34.3                5.35
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.buildenv.2014.04.013 is OK
- 10.1080/13658810701739039 is OK
- 10.4236/jep.2013.47081  is OK
- j.compenvurbsys.2011.02.001 is OK
- 10.14358/PERS.79.2.147 is OK
- 10.1186/s40965-019-0064-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02853/joss.02853/10.21105.joss.02853.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02853/joss.02853/10.21105.joss.02853.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @bstabler - you've been requested as the editor for this submission - can you take it on?

**Comment by danielskatz** [comment]
@whedon invite @bstabler as editor

**Comment by whedon** [comment]
@bstabler has been invited to edit this submission.

**Comment by hugoledoux** [comment]
potential reviewers:

  1. clausnagel
  1. ganys
  1. chenkianwee
  1. https://3dom.fbk.eu/people/profile/eozdemir (not sure on github though)
  1. https://research.utwente.nl/en/persons/sander-oude-elberink (not sure on github though)

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @clausnagel @chenkianwee @ganys - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission we'd be asking you to review is `3dfier: automatic reconstruction of 3D city models`. 

- The software package is here: https://github.com/tudelft3d/3dfier
- The short paper here: [joss.02853/10.21105.joss.02853.pdf](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02853/joss.02853/10.21105.joss.02853.pdf)

**Comment by GANys** [comment]
@arfon, I certainly agree.

Is there any deadline?

**Comment by arfon** [comment]
@GANys - excellent, thanks! We generally aim to have JOSS reviews complete within six weeks, but given their iterative nature, it's often most effective if you can start your review in the first couple of weeks (to give initial feedback to the authors).

Does that sound OK?

**Comment by GANys** [comment]
It seems more than feasible.

**Comment by arfon** [comment]
@whedona add @GANys as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon add @GANys as reviewer

**Comment by whedon** [comment]
OK, @GANys is now a reviewer

**Comment by arfon** [comment]
> It seems more than feasible.

Great, thanks! I won't open the actual review until we've identified a second reviewer but hopefully this won't take too long.

**Comment by chenkianwee** [comment]
Hi I agree to review the paper.

**Comment by arfon** [comment]
@whedon add @chenkianwee as reviewer

**Comment by whedon** [comment]
OK, @chenkianwee is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2866.

**Comment by arfon** [comment]
@GANys, @chenkianwee - many thanks for agreeing to review this submission! See you over in #2866 where the actual review will take place.
