### ISSUE TITLE
[PRE REVIEW]: Isoreader: An R package to read stable isotope data files for reproducible research

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2856]
**Submitting author:** @sebkopf (<a href="http://orcid.org/0000-0002-2044-0201">Sebastian Kopf</a>)
**Repository:** <a href="https://github.com/isoverse/isoreader" target ="_blank">https://github.com/isoverse/isoreader</a>
**Version:** v1.2.7
**Editor:** @mikldk
**Reviewers:** @kdorheim
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sebkopf. **Currently, there isn't an JOSS editor assigned** to your paper.

@sebkopf if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/gbi.12312 is OK
- 10.1111/gbi.12386 is OK
- 10.1144/SP507-2020-85 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1002/lom3.10300 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (600.3 files/s, 144124.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               46           1836           2763           8471
Rmd                              7            326            631            456
YAML                             4             42              6            275
Markdown                         4             55              0            193
TeX                              1              3              0             50
make                             1              6              3             10
-------------------------------------------------------------------------------
SUM:                            63           2268           3403           9455
-------------------------------------------------------------------------------


Statistical information for the repository '518b215f4e2146e9bdf4fa07' was
gathered on 2020/11/21.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02856/joss.02856/10.21105.joss.02856.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02856/joss.02856/10.21105.joss.02856.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @karthik - would you be willing to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @karthik as editor

**Comment by whedon** [comment]
@karthik has been invited to edit this submission.

**Comment by karthik** [comment]
Unfortunately I don't have bandwidth for a new submission till January

**Comment by danielskatz** [comment]
👋 @mikldk - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@sebkopf Thank you for your submission. I have a few questions and comments:

1) Please remove the `https://doi.org/` prefix in [paper.bib#L22](https://github.com/isoverse/isoreader/blob/master/paper.bib#L22)
2) Please include countries where appropriate in the paper (currently only the Netherlands is mentioned, the US is not)
3) Please confirm the paper's authors; when I look at the repo's [insights](https://github.com/isoverse/isoreader/graphs/contributors) I (almost) only see you as a developer (also refer to [JOSS's authorship docs](https://joss.readthedocs.io/en/latest/submitting.html#authorship))
4) Do you have any suggestions for reviewers (find the list above)?

**Comment by sebkopf** [comment]
@mikldk thank you very much for agreeing to be the editor for this submission
 
> Please remove the https://doi.org/ prefix in paper.bib#L22
> Please include countries where appropriate in the paper (currently only the Netherlands is mentioned, the US is not)

DOI issue and missing country in affiliations addressed in commit https://github.com/isoverse/isoreader/commit/524330bcdc8573ec796641c8751273545f02fdb7


> Please confirm the paper's authors; when I look at the repo's insights I (almost) only see you as a developer (also refer to JOSS's authorship docs)

I confirm that the paper's authors are correct. You are right that I did almost all of the actual coding but the biggest challenges for this R package were analyzing and testing different vendor file formats to catch data files that caused trouble and figure out exactly what information was stored where in binary data files. The two co-authors contributed enormously to these aspects of the project, which I consider to merit co-authorship if that's okay with JOSS policy.

> Do you have any suggestions for reviewers (find the list above)?

It seems there are not many reviewers (yet) in the field of geochemistry, I tried to find a few other potential reviewers who work on data access, ecology or reproducible research in R. Hopefully one of the following will be willing to review this submission.

 - jhollist
 - r-barnes
 - ethanwhite
 - kdorheim
 - dvanic

Thank you

**Comment by mikldk** [comment]
@sebkopf :

Thanks. 

- [ ] Please also add countries in the Acknowledgements section.

**Comment by mikldk** [comment]
@jhollist, @kdorheim: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by kdorheim** [comment]
@mikldk thanks for thinking of me, I can review this submission to JOSS. Should the review be included in this issue or a separate issue? Also is there an expected due date for this review? Thanks!

**Comment by jhollist** [comment]
@mikldk I am going to have to pass on this one.  I am full up until about mid/late January.  If you are still looking then, please ping me again.  Sorry!

**Comment by mikldk** [comment]
> @mikldk thanks for thinking of me, I can review this submission to JOSS. 
Thanks!

> Should the review be included in this issue or a separate issue? 
It's up to you. I normally recommend specific comments as issues in the repository (linked to the review issue once created), and general comments/question in the review issue (once created).

> Also is there an expected due date for this review? Thanks!
No, but we normally try to get thinks done within weeks if possible - but if it's not, that's okay, too!

**Comment by mikldk** [comment]
@ethanwhite, @dvanic: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by dvanic** [comment]
@mikldk  Sorry, I'm swamped with childcare + work at the moment, so cannot commit the time to review at this stage - sorry!

**Comment by mikldk** [comment]
@ethanwhite, @r-barnes: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by kdorheim** [comment]
> > @mikldk thanks for thinking of me, I can review this submission to JOSS.
> 
> Thanks!
> 
> > Should the review be included in this issue or a separate issue?
> 
> It's up to you. I normally recommend specific comments as issues in the repository (linked to the review issue once created), and general comments/question in the review issue (once created).
> 
> > Also is there an expected due date for this review? Thanks!
> 
> No, but we normally try to get thinks done within weeks if possible - but if it's not, that's okay, too!

okay yes I would like to accept

**Comment by sebkopf** [comment]
> @sebkopf :
> 
> Thanks.
> 
> * [ ]  Please also add countries in the Acknowledgements section.

Country information added to Acknowledgements https://github.com/isoverse/isoreader/commit/9dae60c6277be1b2eb727111513d6c0ceface3ea. Thank you very much @kdorheim for reviewing our work.

**Comment by mikldk** [comment]
@whedon add @kdorheim as reviewer

**Comment by whedon** [comment]
OK, @kdorheim is now a reviewer

**Comment by kdorheim** [comment]
@mikldk I am excited to review this project but and am also heading into a busy time of the year. I hate to be a bother but I would like the opportunity to start working on the review as soon as possible, could you please open the REVIEW issue so that I may be able to start working on the checklist/tagging issues. I'd really appreciate it, many thanks.

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2878.

**Comment by mikldk** [comment]
> @mikldk I am excited to review this project but and am also heading into a busy time of the year. I hate to be a bother but I would like the opportunity to start working on the review as soon as possible, could you please open the REVIEW issue so that I may be able to start working on the checklist/tagging issues. I'd really appreciate it, many thanks.

Normally we try to not start review until we have found both reviewers, but in this case I'll make an exception because it is taking some time to find a second reviewer :).

**Comment by r-barnes** [comment]
@mikldk: I've been a little slow with my reviews lately, but I could probably find time. The fact that this is already on CRAN means that it's passed a series of peer-reviews already with respect to various aspects of code quality, so a priori I don't expect too much difficulty.

**Comment by mikldk** [comment]
> @mikldk: I've been a little slow with my reviews lately, but I could probably find time. The fact that this is already on CRAN means that it's passed a series of peer-reviews already with respect to various aspects of code quality, so a priori I don't expect too much difficulty.

Thanks, @r-barnes , that sounds really good. Thanks. I'll add you as reviewer in the review issue.

**Comment by ethanwhite** [comment]
Sorry for being slow on this (just starting to dig out as the semester comes to an end). Looks like you have this one covered, but definitely keep me in mind for next time.
