### ISSUE TITLE
[PRE REVIEW]: nf-gwas-pipeline: A Nextflow Genome-Wide Association Study Pipeline

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2857]
**Submitting author:** @ZeyuanSong (<a href="http://orcid.org/0000-0002-7352-4177">Zeyuan Song</a>)
**Repository:** <a href="https://github.com/montilab/nf-gwas-pipeline" target ="_blank">https://github.com/montilab/nf-gwas-pipeline</a>
**Version:** v1.0.0
**Editor:** @lpantano
**Reviewers:** @preetida
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ZeyuanSong. **Currently, there isn't an JOSS editor assigned** to your paper.

@ZeyuanSong if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.07 s (395.9 files/s, 38486.2 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
R                                20            207             73            849
Bourne Again Shell                1             40             39            387
Markdown                          2            117              0            352
Rmd                               3             94            287            109
Dockerfile                        1             15              5             87
TeX                               1              7              0             73
Python                            1             13              0             65
--------------------------------------------------------------------------------
SUM:                             29            493            404           1922
--------------------------------------------------------------------------------


Statistical information for the repository '3a388e5062a57187c950c60d' was
gathered on 2020/11/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ZeyuanSong                       1            42              0           53.85
anfederico                       1            36              0           46.15

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
ZeyuanSong                   42          100.0          0.0                0.00
anfederico                   36          100.0          0.0                2.78
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2857 with the following error: 

 Error reading bibliography file paper.bib:
(line 7, column 15):
unexpected "("
expecting white space, "#", "," or "}"
Looks like we failed to compile the PDF

**Comment by ZeyuanSong** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02857/joss.02857/10.21105.joss.02857.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02857/joss.02857/10.21105.joss.02857.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@ZeyuanSong – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by lpantano** [comment]
Just a comment, the stats of whedon is missing the *nf files that are the main code in this kind of pipelines (nextflow).

**Comment by arfon** [comment]
@lpantano would you be able to edit this submission?

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
I am working on getting reviewers, but at this time it is a little hard. @ZeyuanSong , do you have some suggestions for reviewers?

**Comment by ZeyuanSong** [comment]
Yes, we would like to suggest possible reviewers:
Dr. Riccardo Bellazzi – University of Pavia, Italy – email: riccardo.bellazzi@unipv.it
Dr. Alberto Riva – University of Florida – ariva@ufl.edu,
Dr. Aldi Kraja – University of Mississippi – akraja@umc.edu,
Dr. Han Chen – The University of Texas Health Science Center at Houston – Han.Chen.2@uth.tmc.edu
@lpantano Thank you!

**Comment by lpantano** [comment]
@whedon assign @preetida as reviewer

**Comment by whedon** [comment]
OK, @preetida is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2957.

**Comment by lpantano** [comment]
I will start this so @preetida can start meanwhile I find the other reviewer. Thanks!

**Comment by preetida** [comment]
Hello, 
Thank you for submitting your software. I had a chance to test the pipeline. 
Docker set up works fine, and example works as demonstrated. 
However, for running the pipeline on an HPC that does not support docker, following the instruction, running tools gives error for missing dependency. 
For e.g. below 
```
module load R/3.6.1
module load vcftools
 module load bcftools
module load annovar
module load pandoc
module load plink
nextflow gwas.nf -c gwas.config
Error executing process > 'vcf_to_gds (chr_2)'

Caused by:
  Process `vcf_to_gds (chr_2)` terminated with an error exit status (1)

Command executed:

  02_vcf_to_gds.R chr_2_qc2.vcf.gz chr_2.gds chr_2_vcf_to_gds.log

Command exit status:
  1

Command output:
  [1] "Tue Feb  2 12:09:36 2021"

Command error:
  Error in library(SeqArray) : there is no package called ‘SeqArray’
  Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
  Execution halted

Work dir:
  /home/pjb40/homework/Nextflow/nf-gwas-pipeline/work/d2/c0e24eb2fdda9079d9772828ee8444

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
WARN: Killing pending tasks (7)
```

**Comment by anfederico** [comment]
Hello, co-author here. For HPC's without Docker, an alternative route is to use Singularity. One can convert from the Docker image directly (assuming Singularity is available and setup to pull from Docker). 

```
singularity pull docker://montilab/gwas
```

```
nextflow gwas.nf -c gwas.config -with-singularity [singularity image file]
```

**Comment by lpantano** [comment]
@anfederico, thanks for helping with this. @preetida try to see if this works. Meanwhile, @anfederico it would be good to have a complete list of dependencies for cases where tools needs to be installed (maybe a conda env file helps to deal with this? or list all the dependencies.), thanks!.
