### ISSUE TITLE
[PRE REVIEW]: Launcher: A simple tool for executing high throughput computing workloads

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#286]
**Submitting author:** @lwilson (<a href="http://orcid.org/0000-0002-0686-3152">Lucas Wilson</a>)
**Repository:** <a href="https://github.com/TACC/launcher" target ="_blank">https://github.com/TACC/launcher</a>
**Version:** v3.1
**Editor:** @danielskatz
**Reviewer:** @kc9qey

**Author instructions**

Thanks for submitting your paper to JOSS @lwilson. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lwilson if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@kc9qey - would you be willing to review this submission for JOSS?

**Comment by kc9qey** [comment]
Yeah, only because I can :

===============================================================================
                          --- Stampede 2 is coming
---
     --- Stampede 1 will start phased decommissioning in January 2017
---
          --- The KNLs are now available <> Start migrating today
---
            https://portal.tacc.utexas.edu/user-news/-/news/101909

            https://portal.tacc.utexas.edu/user-guides/stampede#knl

===============================================================================
login3.stampede(1)$ id
uid=456924(tg456924) gid=80228(G-80228)
groups=80228(G-80228),80871(G-80871),80898(G-80898),81815(G-81815),802826(G-802826),803434(G-803434),803442(G-803442),803452(G-803452),803673(G-803673),815561(G-815561),816467(G-816467),816890(G-816890),818338(G-818338)
login3.stampede(2)$

**Comment by danielskatz** [comment]
@whedon assign @kc9qey as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kc9qey

**Comment by danielskatz** [comment]
@whedon commands
tell me about how I phrase the "secret" banana again?

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by danielskatz** [comment]
@whedon start review
but what about the banana?

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas
I can't figure out how anyone benefits from this bananas thingee

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/289. Feel free to close this issue now!
