### ISSUE TITLE
[PRE REVIEW]: sntools: Event generator for supernova burst neutrinos

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2860]
**Submitting author:** @JostMigenda (<a href="http://orcid.org/0000-0002-5350-8049">Jost Migenda</a>)
**Repository:** <a href="https://github.com/JostMigenda/sntools/" target ="_blank">https://github.com/JostMigenda/sntools/</a>
**Version:** v0.7
**Editor:** @xuanxu
**Reviewers:** @bradkav, @benjaminrose
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JostMigenda. **Currently, there isn't an JOSS editor assigned** to your paper.

@JostMigenda if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (420.7 files/s, 47075.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          36            751            906           1788
TeX                              2            144             17            850
Markdown                         2             25              0             69
YAML                             1              4              4             30
-------------------------------------------------------------------------------
SUM:                            41            924            927           2737
-------------------------------------------------------------------------------


Statistical information for the repository '6dc85ca9702d46dffd1e94d4' was
gathered on 2020/11/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex Himmel                      1           166              0            1.13
Jost Migenda                   171          7205           4676           80.65
Liz Kneale                      10          1275            275           10.52
Tom Dealtry                      6            83             51            0.91
Yan-Jie Schnellbach              4            52              4            0.38
ekneale                         10           453            491            6.41

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jost Migenda               3397           47.1         14.7               15.81
Yan-Jie Schnellbach          48           92.3          0.9                4.17
```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
PDF failed to compile for issue #2860 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02860/joss.02860/10.21105.joss.02860.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02860/joss.02860/10.21105.joss.02860.pdf) :page_facing_up: :point_left:

**Comment by JostMigenda** [comment]
I can think of a few potential reviewers, but most of them are co-authors on [this recent paper](https://arxiv.org/abs/2011.00035), which I have also contributed to; so they may be excluded by the JOSS [Conflict of Interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy).
Looking at [the list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822), I think bradkav and kostunin would be good candidates; perhaps also arjunsavel, olebole or benjaminrose.

**Comment by arfon** [comment]
/ cc @augustfly for visibility.

**Comment by arfon** [comment]
@whedon invite @xuanxu as editor

:wave: @xuanxu - would you be able to take this paper?

**Comment by whedon** [comment]
@xuanxu has been invited to edit this submission.

**Comment by xuanxu** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
@bradkav would you be willing to review this paper? You have been suggested by the author and your knowledge of Astroparticle Physics and Python makes you a great fit fot the submission.

**Comment by xuanxu** [comment]
@HeloiseS would you be willing to review this paper? I think your interest in SuperNovae and knowledge of Python makes you a great fit for this submission.

**Comment by JostMigenda** [comment]
Quick note: @HeloiseS and I were PhD students in the same department until 1.5 years ago and still interact socially (but have never collaborated on a paper or similar). I think that’s not covered by the [CoI policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) (which requires at least 1 year since being at the same institution, and does not limit Twitter interactions), but I still wanted to mention it in the interest of transparency.

That said, I agree Héloïse would be a great fit for this topic and I am certain that she will be able to judge it impartially, so I’d be happy to have her as a reviewer.

**Comment by bradkav** [comment]
@xuanxu I'm very happy to review this paper. Sign me up!

**Comment by xuanxu** [comment]
@whedon assign @bradkav as reviewer

**Comment by whedon** [comment]
OK, @bradkav is now a reviewer

**Comment by xuanxu** [comment]
@bradkav great, thanks! I'll start the review issue once I have the second reviewer. Stay tuned!

**Comment by xuanxu** [comment]
@benjaminrose would you be willing to review this paper? I think your interest in SuperNovae and knowledge of Python makes you a great fit for this submission.

**Comment by benjaminrose** [comment]
@xuanxu, yes, I can review this project. I am currently reviewing another JOSS paper, so I can't get to this one for about a week. 

I wanted to note that the repo was started by Chris Walker (a co-worker of mine) but it appears that he was only the author of this initial commit and not apart of the project. If I am mistaken, @JostMigenda, can you correct me?

**Comment by xuanxu** [comment]
@benjaminrose great, thanks! 

>  I can't get to this one for about a week.

No problem!

> the repo was started by Chris Walter (a co-worker of mine) 

He's not in the [paper](https://github.com/openjournals/joss-papers/blob/joss.02860/joss.02860/10.21105.joss.02860.pdf)'s authors list and can't be found as [contributor to the code](https://github.com/openjournals/joss-reviews/issues/2860#issuecomment-732756040), so currently I don't see any COI. 
Anyway, let's wait for confirmation of his (not) involvement from @JostMigenda

**Comment by JostMigenda** [comment]
I confirm that Chris Walter was not involved.

(The reason he appears in the commit history is because we originally started out with [a pre-existing script from a different repo](https://github.com/WCSim/WCSim/commits/develop/sample-root-scripts/MakeKin.py), so I included the git history of that file. Chris just happened to start that different repo; as far as I can reconstruct, his [commit in sntools](https://github.com/JostMigenda/sntools/commit/5800c46ec8e75b3a438f4cb153b460c83946e345) corresponds to [this commit in the original repo](https://github.com/WCSim/WCSim/commit/24c724cd2cef2cfc6e525ec159f2b812f5f1a6fd).)

**Comment by benjaminrose** [comment]
Sounds great. That is what I was seeing as well.

**Comment by xuanxu** [comment]
@whedon add @benjaminrose as reviewer

**Comment by whedon** [comment]
OK, @benjaminrose is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2877.
