### ISSUE TITLE
[PRE REVIEW]: fuelcell: A Python package and graphical user interface for electrochemical data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2861]
**Submitting author:** @samaygarg (<a href="http://orcid.org/0000-0002-9872-6429">Samay Garg</a>)
**Repository:** <a href="https://github.com/samaygarg/fuelcell" target ="_blank">https://github.com/samaygarg/fuelcell</a>
**Version:** v0.3.1
**Editor:** @jgostick
**Reviewers:** @jlopata21, @shimpalee
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @samaygarg. **Currently, there isn't an JOSS editor assigned** to your paper.

@samaygarg if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2861 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (58d18b130a895693f16bd711/paper/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 16 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.28 s (210.4 files/s, 97621.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      15           2222           2276           8435
Python                           8            501           1211           3607
SVG                              1              0              0           2671
HTML                            12           1472             36           2355
CSS                              7            365             66           1379
Markdown                         3             37              0             86
reStructuredText                 9             30             21             50
TeX                              1              4              0             34
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            58           4643           3618          18652
-------------------------------------------------------------------------------


Statistical information for the repository '4b34792a73a8575677fe2fb9' was
gathered on 2020/11/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aditya Limaye                    1             1              1            0.01
Samay Garg                      25         23021           4769           99.99

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aditya Limaye                 1          100.0          2.4                0.00
Samay Garg                18251           79.3          2.6               15.14
```

**Comment by arfon** [comment]
@samaygarg - this PR should fix your paper compilation issues: https://github.com/samaygarg/fuelcell/pull/4

**Comment by arfon** [comment]
@whedon invite @jgostick as editor

:wave: @jgostick - would you be able to edit this submission for us?

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by jgostick** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02861/joss.02861/10.21105.joss.02861.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02861/joss.02861/10.21105.joss.02861.pdf) :page_facing_up: :point_left:

**Comment by jgostick** [comment]
sorry for the delay here...still looking for reviewers.  Probably will spill over into the new year.

**Comment by jgostick** [comment]
@whedon add @jlopata21 as reviewer

**Comment by whedon** [comment]
OK, @jlopata21 is now a reviewer

**Comment by jgostick** [comment]
@whedon add @shimpalee as reviewer

**Comment by whedon** [comment]
OK, @shimpalee is now a reviewer

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2940.
