### ISSUE TITLE
[REVIEW]: Parent-map: analysis of parental contributions to evolved or engineered protein or DNA sequences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2864]
**Submitting author:** @damienmarsic (<a href="http://orcid.org/0000-0003-0847-8095">Damien Marsic</a>)
**Repository:** <a href="https://github.com/damienmarsic/Parent-map" target ="_blank">https://github.com/damienmarsic/Parent-map</a>
**Version:** 1.1.2
**Editor:** @csoneson
**Reviewer:** @xie186, @j-andrews7
**Archive:** <a href="https://doi.org/10.5281/zenodo.4459006" target="_blank">10.5281/zenodo.4459006</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1db59f6daa32b52df72f612bf1020b60/status.svg)](https://joss.theoj.org/papers/1db59f6daa32b52df72f612bf1020b60)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1db59f6daa32b52df72f612bf1020b60"><img src="https://joss.theoj.org/papers/1db59f6daa32b52df72f612bf1020b60/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1db59f6daa32b52df72f612bf1020b60/status.svg)](https://joss.theoj.org/papers/1db59f6daa32b52df72f612bf1020b60)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/damienmarsic/Parent-map" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@xie186 & @j-andrews7, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/damienmarsic/Parent-map">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@damienmarsic) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/damienmarsic/Parent-map">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@damienmarsic) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @xie186, @j-andrews7 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ymthe.2017.09.006 is OK
- 10.1016/j.omtm.2019.10.007 is OK
- 10.1038/nbt.3440 is OK
- 10.1073/pnas.0813365106 is OK
- 10.1038/mt.2014.139 is OK
- 10.1016/j.ymthe.2017.09.021 is OK
- 10.1038/gt.2016.62 is OK
- 10.1038/nbt.1599 is OK
- 10.1038/mt.2010.234 is OK
- 10.1016/j.neuron.2016.09.021 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.1021/acssynbio.8b00373 is OK
- 10.1128/JVI.00254-08 is OK
- 10.1126/scitranslmed.3005708 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02864/joss.02864/10.21105.joss.02864.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02864/joss.02864/10.21105.joss.02864.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
@xie186, @j-andrews7 - This is the review thread for this submission. All of our communications will happen here from now on.

Please have a look at the "Reviewer instructions & questions" in the first comment above, which also contains your respective checklists. As you go over the submission, please check any items that you feel have been satisfied, and provide some comments or guidance for the author concerning the remaining ones. We aim for the review process to be fully completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

Feel free to ping me (@csoneson) if you have any questions. Thanks again for accepting to review this submission!

**Comment by j-andrews7** [comment]
In general, this is a really nifty tool, and I expect it will get a solid amount of play for its simplicity, ease of use, and straight-forward output - really an ideal fit for JOSS. **parent-map** is well-documented - the input and output formats are easy to understand and thoroughly explained on the associated [readthedocs](https://parent-map.readthedocs.io/en/latest/index.html) site, as are all arguments. Installation is simple via `conda` or `pip` - there's even a basic Windows-only GUI.

The tool functions as described and is highly performant, completing its task nearly instantly. I quadrupled the input size and didn't notice a difference, so I presume it likely scales adequately as well. Multiple example inputs from several published studies are provided in the repo. The examples are well-documented and automated tests were added [during the review process](https://github.com/damienmarsic/Parent-map/issues/2). Output from the GUI and CLI are identical, as expected.

The software repo is in good shape and contribution guidelines and issue templates are present. A google support forum is also available. 

The paper is generally well-written and easy to follow. **My last request** is to organize the sections in the paper. Right now, the only sections are the Summary and Statement of Need, so having Implementation and/or Usage sections in addition would be helpful. Otherwise, this is good to go from me.

**Comment by csoneson** [comment]
Thanks a lot @j-andrews7 for this thorough review!

**Comment by damienmarsic** [comment]
Indeed, thanks for this very efficient review and all your advice and suggestions to improve my submission. I really appreciate.

**Comment by whedon** [comment]
:wave: @xie186, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @j-andrews7, please update us on how your review is going.

**Comment by csoneson** [comment]
@j-andrews7 - feel free to ignore Whedon's nudge above :) 

@xie186 - just wanted to check in to make sure that you have everything you need for your review, and whether you have any questions (on the process or otherwise).

**Comment by csoneson** [comment]
👋 @xie186 - could you give us an update on how your review is progressing? Thanks!

**Comment by csoneson** [comment]
ping @xie186 

> 👋 @xie186 - could you give us an update on how your review is progressing? Thanks!

**Comment by xie186** [comment]
> ping @xie186
> 
> > 👋 @xie186 - could you give us an update on how your review is progressing? Thanks!

@csoneson Just let you know that I'll submit the comment over the weekend. Sorry for the delay in response.

**Comment by xie186** [comment]
This is really a neat tool to analyze parental contributions to evolved or engineered protein or DNA sequences. 

The documentation is very detailed. Example data is provided for easy testing. 

Parent-map can be installed using either `conda` or `pip` which is fantastic given the fact the easy installation is important. 
Only problem is that error below was given after successfully run 'pip install parent-map':  
```
ModuleNotFoundError: No module named 'gooey'
```
My testing system is ubuntu 16.04. 

GUI mode is a great advantage of `parent-map`. GUI mode makes more users to be able to use the tool. 

I suggest you to use `github issue` to replace the `Discussion list` hosted using `google group`. I don't see any advantage of using 'google group' here. 

The manuscript is well written. One suggestion to give an example to represent the accuracy of `parent-map`.

**Comment by csoneson** [comment]
👋 Happy New Year! 
@j-andrews7, @xie186 - thanks a lot for your reviews.  
@damienmarsic - could you take a look at the few outstanding points above and let us know when the submission is ready for a reassessment by the reviewers?
Thanks!

**Comment by damienmarsic** [comment]
Hi everyone, and best wishes for the new year!
Sorry for the dealy, I was actally waiting for instructions on what to do next. Following the reviewers comments, I made the following changes in the repository:
- paper.md has now sections "Methods" and "Implementation" in addition to "Statement of need"
- The google group discussion list was removed rom README.md and replaced with a link to the repository's GitHub Issues
- Both README.md and the readthedocs documentations were updated with a warning to manually install possible missing modules such as gooey when installing with pip.
Sorry I am not sure to understand last comment by @xie186. In my mind, the accuracy is already demonstrated in the Examples section of the documentation.
Thanks all for your efforts!

**Comment by j-andrews7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02864/joss.02864/10.21105.joss.02864.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02864/joss.02864/10.21105.joss.02864.pdf) :page_facing_up: :point_left:

**Comment by j-andrews7** [comment]
This looks good to me and I have no further comments other than good job and thanks for the quick edits. Personally, I feel the accuracy is adequately addressed through the examples, and given the sparsity of other options and journal guidelines, that a true benchmarking study is beyond the scope of the journal.

**Comment by csoneson** [comment]
Thanks @j-andrews7!

**Comment by csoneson** [comment]
@xie186 - could you clarify the last point in your review above?

**Comment by xie186** [comment]
@damienmarsic Regarding the last comment, what I meant was to include the example(s) of the document in the manuscript. Otherwise the user won't have this information while read the MS.

**Comment by damienmarsic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02864/joss.02864/10.21105.joss.02864.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02864/joss.02864/10.21105.joss.02864.pdf) :page_facing_up: :point_left:

**Comment by damienmarsic** [comment]
@xie186 Thanks for this clarification.
I added detailed information at the end of the manuscript, showing that parent-map correctly identifies all the features from the sample variants.

**Comment by xie186** [comment]
@damienmarsic Thank you!

**Comment by csoneson** [comment]
Thanks @xie186 and @damienmarsic! 
@xie186 - could you confirm whether your comments have been adequately addressed and you're happy with the current state of the submission (and if so, please tick the last boxes in the checklist above), or whether there are outstanding issues?

**Comment by csoneson** [comment]
ping @xie186 
> @xie186 - could you confirm whether your comments have been adequately addressed and you're happy with the current state of the submission (and if so, please tick the last boxes in the checklist above), or whether there are outstanding issues?

**Comment by xie186** [comment]
I confirmed that my comments were addressed adequately. I also ticked the last boxes in the checklist above.

**Comment by csoneson** [comment]
Thanks @xie186! 
@damienmarsic - I will take a quick look at the submission as well, and get back to you shortly with the next steps forward.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02864/joss.02864/10.21105.joss.02864.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02864/joss.02864/10.21105.joss.02864.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ymthe.2017.09.006 is OK
- 10.1016/j.omtm.2019.10.007 is OK
- 10.1038/nbt.3440 is OK
- 10.1073/pnas.0813365106 is OK
- 10.1038/mt.2014.139 is OK
- 10.1016/j.ymthe.2017.09.021 is OK
- 10.1038/gt.2016.62 is OK
- 10.1038/nbt.1599 is OK
- 10.1038/mt.2010.234 is OK
- 10.1016/j.neuron.2016.09.021 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.1021/acssynbio.8b00373 is OK
- 10.1128/JVI.00254-08 is OK
- 10.1126/scitranslmed.3005708 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@damienmarsic - this looks all good. The next steps are as follows: 

- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the software in Zenodo or a similar service
- [ ] Check that the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (should match that of the paper). You may also add the author's ORCID.
- [ ] Please list the DOI of the archived version here.

I will then move forward with accepting the submission.

**Comment by damienmarsic** [comment]
Here is the Zenodo link:
https://zenodo.org/record/4459006#.YAvKedlFaV4
Version: 1.1.2
DOI: 10.5281/zenodo.4459006

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.4459006 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4459006" target="_blank">10.5281/zenodo.4459006</a> is the archive.

**Comment by csoneson** [comment]
@whedon set 1.1.2 as version

**Comment by whedon** [comment]
OK. 1.1.2 is the version.

**Comment by csoneson** [comment]
Great, thanks! I'll hand over to the associate editor-in-chief on rotation for the last steps.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ymthe.2017.09.006 is OK
- 10.1016/j.omtm.2019.10.007 is OK
- 10.1038/nbt.3440 is OK
- 10.1073/pnas.0813365106 is OK
- 10.1038/mt.2014.139 is OK
- 10.1016/j.ymthe.2017.09.021 is OK
- 10.1038/gt.2016.62 is OK
- 10.1038/nbt.1599 is OK
- 10.1038/mt.2010.234 is OK
- 10.1016/j.neuron.2016.09.021 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.1021/acssynbio.8b00373 is OK
- 10.1128/JVI.00254-08 is OK
- 10.1126/scitranslmed.3005708 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2043

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2043, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
This looks good - it's great to get a paper that doesn't need any copy-editing changes

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1353104798178971648) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2044
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02864](https://doi.org/10.21105/joss.02864)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @damienmarsic (Damien Marsic)!!

And thanks to @xie186 and @j-andrews7 for reviewing, and @csoneson for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02864/status.svg)](https://doi.org/10.21105/joss.02864)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02864">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02864/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02864/status.svg
   :target: https://doi.org/10.21105/joss.02864
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02864/status.svg)](https://doi.org/10.21105/joss.02864)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by damienmarsic** [comment]
Thanks everyone !
