### ISSUE TITLE
[PRE REVIEW]: pygamma-agreement: Gamma measure for inter/intra-annotator agreement in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2865]
**Submitting author:** @hadware (<a href="http://orcid.org/0000-0002-8511-1644">Hadrien Titeux</a>)
**Repository:** <a href="https://github.com/bootphon/pygamma-agreement/" target ="_blank">https://github.com/bootphon/pygamma-agreement/</a>
**Version:** 0.1.4
**Editor:** @arfon
**Reviewers:** @faroit
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @hadware. **Currently, there isn't an JOSS editor assigned** to your paper.

@hadware if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (149.3 files/s, 21071.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          14            438            565           1558
reStructuredText                 5            178            163            207
TeX                              1              5              0            138
Markdown                         2             59              0            114
YAML                             3             10              7             38
Jupyter Notebook                 1              0            279             32
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            27            694           1021           2096
-------------------------------------------------------------------------------


Statistical information for the repository '70ded2a00bb9627f60897adc' was
gathered on 2020/11/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Rachine                         45          2187            298           22.60
hadware                         56          4592           3921           77.40

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Rachid Riad                 421          100.0         11.5               30.17
hadware                    2140           46.6          2.0               10.47
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02865/joss.02865/10.21105.joss.02865.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02865/joss.02865/10.21105.joss.02865.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1162/COLI_a_00227 is OK
- 10.1162/COLI_a_00296 is OK
- 10.1177/014272370002006006 is OK
- 10.1145/2833157.2833162 is OK
- 10.1109/ICASSP40776.2020.9052974 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon invite @bmcfee as editor

:wave: @bmcfee - the submitting authors suggested you as the handling editor for this submission and it looks to be a pretty good fit. Would you be willing to handle this submission?

**Comment by whedon** [comment]
@bmcfee has been invited to edit this submission.

**Comment by hadware** [comment]
Hello! Thanks for reviewing our work.

We'd like to suggest two additional reviewers that could be suitable for this submission and have a good knowledge of the field: https://github.com/jjatria and https://github.com/faroit

**Comment by arfon** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
OK, the editor is @bmcfee

**Comment by kthyng** [comment]
@bmcfee Are you available to work on this submission?

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @hadware - apologies for taking so long to get this moving. I'll be editing this paper going forward.

**Comment by arfon** [comment]
:wave: @jjatria & @faroit - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration is _pygamma-agreement: Gamma measure for inter/intra-annotator agreement in Python_, with the Python-based software here: https://github.com/bootphon/pygamma-agreement/

Many thanks!

**Comment by hadware** [comment]
:wave: @arfon , thanks for stepping in as editor for our paper! No troubles for the delay, we (me and @rachine) understand that you must be working under a fair amount of constraints. We'll also be staying tuned for any questions or suggestions from you. If any of the suggested reviewers isn't available, we can also suggest others.

**Comment by faroit** [comment]
@arfon I'm happy to review this contribution. I will have the bandwidth to do it rather soon. Thanks for considering me, the package sounds really interesting and useful!

**Comment by arfon** [comment]
@whedon add @faroit as reviewer

**Comment by whedon** [comment]
OK, @faroit is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2989.

**Comment by arfon** [comment]
@faroit @hadware - I'll go ahead and start the review now and keep looking for a second reviewer in the meantime. See you over in #2989 for the actual review.

**Comment by jjatria** [comment]
@arfon I'm not sure I'll have the time to review this. I'd love to help, but I don't know if I can commit, which means it's probably better for me to decline.

Do let me know if you have trouble finding someone else to do it, and I'll try to make some time. :bow:

**Comment by arfon** [comment]
:wave: @apiad @pzelasko @ajoer - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration is _pygamma-agreement: Gamma measure for inter/intra-annotator agreement in Python_, with the Python-based software here: https://github.com/bootphon/pygamma-agreement/

Many thanks!

**Comment by pzelasko** [comment]
I'm sorry, but I have too many commitments at this time.

**Comment by apiad** [comment]
I'd be more than happy to help review it! What is the deadline?

**Comment by arfon** [comment]
> I'd be more than happy to help review it! What is the deadline?

We aim to have reviews completed in ~6 weeks. As JOSS reviews are generally iterative in nature, we encourage reviewers to provide initial feedback sooner than this though in case any clarifications are necessary.

Does this sound OK?

**Comment by apiad** [comment]
> > I'd be more than happy to help review it! What is the deadline?
> 
> We aim to have reviews completed in ~6 weeks. As JOSS reviews are generally iterative in nature, we encourage reviewers to provide initial feedback sooner than this though in case any clarifications are necessary.
> 
> Does this sound OK?

Absolutely. I'll do my best to have some initial feedback in the next couple of weeks at most.

**Comment by arfon** [comment]
@whedon add @apiad as reviewer

**Comment by whedon** [comment]
OK, @apiad is now a reviewer
