### ISSUE TITLE
[REVIEW]: 3dfier: automatic reconstruction of 3D city models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2866]
**Submitting author:** @hugoledoux (<a href="http://orcid.org/0000-0002-1251-8654">Hugo Ledoux</a>)
**Repository:** <a href="https://github.com/tudelft3d/3dfier" target ="_blank">https://github.com/tudelft3d/3dfier</a>
**Version:** v1.3.1
**Editor:** @arfon
**Reviewer:** @GANys, @chenkianwee
**Archive:** <a href="https://doi.org/10.5281/zenodo.4461324" target="_blank">10.5281/zenodo.4461324</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/53cc45eaa9fbdc70f02e042bd433da87/status.svg)](https://joss.theoj.org/papers/53cc45eaa9fbdc70f02e042bd433da87)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/53cc45eaa9fbdc70f02e042bd433da87"><img src="https://joss.theoj.org/papers/53cc45eaa9fbdc70f02e042bd433da87/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/53cc45eaa9fbdc70f02e042bd433da87/status.svg)](https://joss.theoj.org/papers/53cc45eaa9fbdc70f02e042bd433da87)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/tudelft3d/3dfier" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@GANys & @chenkianwee, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/tudelft3d/3dfier">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@hugoledoux) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/tudelft3d/3dfier">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@hugoledoux) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @GANys, @chenkianwee it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.buildenv.2014.04.013 is OK
- 10.1080/13658810701739039 is OK
- 10.4236/jep.2013.47081  is OK
- j.compenvurbsys.2011.02.001 is OK
- 10.14358/PERS.79.2.147 is OK
- 10.1186/s40965-019-0064-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02866/joss.02866/10.21105.joss.02866.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02866/joss.02866/10.21105.joss.02866.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@GANys, @chenkianwee - This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions &amp; questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/2866 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by hugoledoux** [comment]
@arfon the Fig1 in my paper is very small, which is weird because the original .png is rather large (1500px X 346px). I couldn't find a way to make it use the width of the page. Possible?

**Comment by arfon** [comment]
@hugoledoux - I think you can force a specific size, e.g. `![](file.jpg){ width=50% }`. Can you try experimenting with syntax like that?

**Comment by GANys** [comment]
Just a question about the following point :

_Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)_

Authors claim that "A simple model can be created even using a laptop with less RAM and slower CPU.". My tests confirm the statement but does it correspond to the performance check box requirements? Or should it be a normative benchmark?

**Comment by whedon** [comment]
:wave: @chenkianwee, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @GANys, please update us on how your review is going.

**Comment by GANys** [comment]
I have finished testing 3Dfier and reading the software paper. I hava some comments. Here is my point-by-point list of comments in regard of the review checklist :

Community Guidelines: besides the common GitHub community standards and tools, I don't see any framework or guidelines for people to contribute.
State of the field: 3Dfier is kind of unique. I don't see any package or solution that provide such an output. Some FME Workbench could for instance perform something comparable but this is completely out of the Open Source community.

Besides the performance related question, I don't have any remaining comment on the checklist.

But, about the paper, I have quick remarks: 

- A point is lacking at the end of the sentence _[...] different software_. at the end of the Summary.
- _The resulting surface aims at being error-free._ This sentence does not do justice to the actual outputs of the programme. The main advantage of 3Dfier is that output objects are discrete. "Resulting surface" might means that the output is a common mesh. The result goes far away from it, in a good manner I mean.
- This point is somehow related to the second, but it does not seem obvious that 2D input information should not be contiguous. Hence, the result will not be contiguous in this case but 3Dfier still propose a solution.
It is important to make this clear, all the more so because that the explanation of the "stitch" processing looks to work vertically form Figure 2. Moreover, Figure 2 does not leave a choice on the continuity of the 2D dataset.

Finally, 3Dfier is a state of the art software that improves the creation and thus the usability of consistent 3D City Models. It is used in research since several years and continues to improve.

@hugoledoux Here is an up.

**Comment by arfon** [comment]
> Authors claim that "A simple model can be created even using a laptop with less RAM and slower CPU.". My tests confirm the statement but does it correspond to the performance check box requirements? Or should it be a normative benchmark?

Apologies for missing this earlier @GANys. I think you can check this off based on your test here.

**Comment by arfon** [comment]
:wave: @chenkianwee - just checking in here to see how you're getting along here?

**Comment by chenkianwee** [comment]
Sorry for the delay, been busy, will work on the review today

**Comment by chenkianwee** [comment]
I have issue installing the binary version of 3dfier on my windows machine. This is the error I am getting. Am I suppose to install something before running the windows.zip file?
![image](https://user-images.githubusercontent.com/13062600/101960300-22a14800-3bd5-11eb-8ce3-cb372b5777c1.png)

**Comment by chenkianwee** [comment]
I got it fix adter downloading necessary Visual studio packages

**Comment by chenkianwee** [comment]
I have followed the example here (http://tudelft3d.github.io/3dfier/first_run.html). I successfully generated the 3D geometry. However, the mesh that was generated are overlapping as shown in the image below. The terrain and side of the buildings have overlapping surfaces, which is not as described in the paper.
![image](https://user-images.githubusercontent.com/13062600/101996402-0cac8980-3ca0-11eb-91bf-3a20b29e5336.png)

**Comment by chenkianwee** [comment]
3Dfier is a useful piece of software, especially in the built environment field, where the creation of 3D data is essential for running certain analyses and simulations (e.g. solar, airflow simulation). I see it as a much-needed software that can extend existing 2D GIS tools to generate 3D data for the built environment field. 

Community Guidelines: I do not see any guideline or framework for contributing to the project. However, I feel the software is well-managed and there is sufficient documentation for interested parties to extend the software. Considering the software is a standalone cmd tool. It could potentially be a useful module where it could be easily included in other projects for 3Dfying 2D GIS data. So rather than be extended, I think this software is useful for other projects that require 3D generation functionality. 
  
State of the field: There is no mention of the state of the field, there are existing commercial tools that offer similar functionality such as FME and ArcGIS software. They are definitely not in the realm of open-source, but I think it will be useful to mention tools of similar functionality regardless of whether they are proprietary or open-source.  

There are still some minor issues with the software, e.g. with the installations and the overlapping surfaces shown in my previous comments. I hope the authors are able to fix those. Once addressed, I recommend the publication of the paper.

**Comment by hugoledoux** [comment]
Thanks for comments @GANys, sorry for delay in responding.

> Community Guidelines: besides the common GitHub community standards and tools, I don't see any framework or guidelines for people to contribute.

You are right, I forgot to add this! Will do so very soon.

> State of the field: 3Dfier is kind of unique. I don't see any package or solution that provide such an output. Some FME Workbench could for instance perform something comparable but this is completely out of the Open Source community.

If you see comments below from @chenkianwee he says FME and others could do the same. I somewhat disagree but it's a good point to mention. In short, you can extruse buildings and other other features/objects, but the stitching part that aims obtaining topologically clean data is not possible.

I'll add 1-2 sentence in the paper.

**Comment by hugoledoux** [comment]
> I got it fix adter downloading necessary Visual studio packages

Should this be added in the installation tutorial though? Maybe we had this all along and never noticed?

**Comment by hugoledoux** [comment]
> I have followed the example here (http://tudelft3d.github.io/3dfier/first_run.html). I successfully generated the 3D geometry. However, the mesh that was generated are overlapping as shown in the image below. The terrain and side of the buildings have overlapping surfaces, which is not as described in the paper.
> ![image](https://user-images.githubusercontent.com/13062600/101996402-0cac8980-3ca0-11eb-91bf-3a20b29e5336.png)

Is this in the dataset given in the folder `example_data/*`? If yes, where is it? And more importantly, it's possible that there's a gap there between the terrain and the building, I would be very surprise they overlap?

**Comment by hugoledoux** [comment]
> Community Guidelines: I do not see any guideline or framework for contributing to the project. However, I feel the software is well-managed and there is sufficient documentation for interested parties to extend the software. Considering the software is a standalone cmd tool. It could potentially be a useful module where it could be easily included in other projects for 3Dfying 2D GIS data. So rather than be extended, I think this software is useful for other projects that require 3D generation functionality.
> 

I would agree with this, extending it is somewhat cumbersome, but it's possible. Would you say it would be better if I rephrased the paper as such?

> State of the field: There is no mention of the state of the field, there are existing commercial tools that offer similar functionality such as FME and ArcGIS software. They are definitely not in the realm of open-source, but I think it will be useful to mention tools of similar functionality regardless of whether they are proprietary or open-source.

https://github.com/tudelft3d/3dfier/commit/e351e5a20bff6349368a6ea0591890558173eb3f

> 
> There are still some minor issues with the software, e.g. with the installations and the overlapping surfaces shown in my previous comments. I hope the authors are able to fix those. Once addressed, I recommend the publication of the paper.

Thanks. Overlap == we aim at avoiding those, and I'd like to know the location then I'll check. We don't guarantee clean 3D output, only if you have clean 2D then can you get sensible 3D output. Garbage in? Garbage out...

**Comment by chenkianwee** [comment]
> 
> 
> > I have followed the example here (http://tudelft3d.github.io/3dfier/first_run.html). I successfully generated the 3D geometry. However, the mesh that was generated are overlapping as shown in the image below. The terrain and side of the buildings have overlapping surfaces, which is not as described in the paper.
> > ![image](https://user-images.githubusercontent.com/13062600/101996402-0cac8980-3ca0-11eb-91bf-3a20b29e5336.png)
> 
> Is this in the dataset given in the folder `example_data/*`? If yes, where is it? And more importantly, it's possible that there's a gap there between the terrain and the building, I would be very surprise they overlap?

Yes, this is from the example dataset. There is no overlap in the original dataset, but I think what is happening is that the terrain is inheriting some of the elevations from the building when the terrain meets the buildings. I have uploaded my data here if it is useful for you to see what is wrong?
[example_data.zip](https://github.com/openjournals/joss-reviews/files/5697217/example_data.zip)

**Comment by chenkianwee** [comment]
> 
> 
> > I got it fix adter downloading necessary Visual studio packages
> 
> Should this be added in the installation tutorial though? Maybe we had this all along and never noticed?

There is documentation for some other missing visual studio files. Its a different visual studio file. But I notice you have already updated your installation instruction here https://tudelft3d.github.io/3dfier/installation.html

**Comment by chenkianwee** [comment]
> > State of the field: 3Dfier is kind of unique. I don't see any package or solution that provide such an output. Some FME Workbench could for instance perform something comparable but this is completely out of the Open Source community.
> 
> If you see comments below from @chenkianwee he says FME and others could do the same. I somewhat disagree but it's a good point to mention. In short, you can extruse buildings and other other features/objects, but the stitching part that aims obtaining topologically clean data is not possible.
> 
> I'll add 1-2 sentence in the paper
> **update**: done [tudelft3d/3dfier@e351e5a](https://github.com/tudelft3d/3dfier/commit/e351e5a20bff6349368a6ea0591890558173eb3f)

I agree with Hugo that the stitching part is more complex and there might not be an existing function to do that. I overlooked that part when giving the comment about the state of the art. I think it will be beneficial to the paper if maybe you can mention the current state of the art with extrusion etc.

**Comment by hugoledoux** [comment]
> Yes, this is from the example dataset.

I'm trying to replicate your issue @chenkianwee , with my macOS, if I compile the master branch, I get this, which is also what the output we get and put in the repository:
![IMAGE 2020-12-17 15:41:16](https://user-images.githubusercontent.com/1546518/102501954-4d304c80-407e-11eb-8569-54b0bbed1b08.jpg)

Now if I look at your .yml file, it's not the same at the one currently in the repo (https://github.com/tudelft3d/3dfier/blob/master/example_data/testarea_config.yml), you removed many parameters that make the spikes appear (I think). Could you run with Windows (compiled by yourself or you used our binary?) with that .yml config file and check if the weird spikes are gone?

**Comment by chenkianwee** [comment]
Sorry for the late reply. @hugoledoux I tried with the new yml file and it worked. It seems like I have downloaded an outdated example file here (https://github.com/tudelft3d/3dfier/releases/tag/example_data).  Its on the Github documentation page. 
![image](https://user-images.githubusercontent.com/13062600/102935072-6288ea80-4473-11eb-9682-1f4d9c334afe.png). Will be good to update the information to avoid confusion. Thanks.

**Comment by hugoledoux** [comment]
hmmm, I wasn't aware of that old-and-weird release. I have just deleted it, since I can imagine it could cause confusion! 

The proper and up-to-date `.yml` file is the one in the master branch in the `example_data` folder.

**Comment by hugoledoux** [comment]
@arfon I think that most/all comments have been processed, can you let us know what's next?

**Comment by arfon** [comment]
@chenkianwee - I notice there are still a few checkboxes un-checked in your review. Can you confirm that these issues have now been addressed?

**Comment by chenkianwee** [comment]
sorry for the delay, I have just checked the list. The authors have responded to all of my comments and make the necessary changes.

**Comment by arfon** [comment]
@hugoledoux - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

Finally, please make sure you give the paper a final read for any last formatting issues (I will do the same).

I can then move forward with accepting the submission.

**Comment by hugoledoux** [comment]
@whedon generate pdf

**Comment by hugoledoux** [comment]
@arfon seems the service to build pdf (and check DOIs) is down, tried elsewhere too nothing works

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02866/joss.02866/10.21105.joss.02866.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02866/joss.02866/10.21105.joss.02866.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
> @arfon seems the service to build pdf (and check DOIs) is down, tried elsewhere too nothing works

Whedon was being a little sloooooow this morning. Should be fine now.

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.buildenv.2014.04.013 is OK
- 10.1080/13658810701739039 is OK
- 10.4236/jep.2013.47081  is OK
- j.compenvurbsys.2011.02.001 is OK
- 10.14358/PERS.79.2.147 is OK
- 10.1186/s40965-019-0064-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by hugoledoux** [comment]
@arfon what you asked for:

  - DOI: http://dx.doi.org/10.5281/zenodo.4461324
  - it's for v1.3.1

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4461324 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4461324" target="_blank">10.5281/zenodo.4461324</a> is the archive.

**Comment by arfon** [comment]
@whedon set v1.3.1 as version

**Comment by whedon** [comment]
OK. v1.3.1 is the version.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.buildenv.2014.04.013 is OK
- 10.1080/13658810701739039 is OK
- 10.4236/jep.2013.47081  is OK
- j.compenvurbsys.2011.02.001 is OK
- 10.14358/PERS.79.2.147 is OK
- 10.1186/s40965-019-0064-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2866 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/bibtex_parser.rb:82:in `doi_citation': undefined method `encode' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/bibtex_parser.rb:64:in `make_citation'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/bibtex_parser.rb:50:in `block in generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.6/lib/bibtex/bibliography.rb:149:in `each'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.6/lib/bibtex/bibliography.rb:149:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/bibtex_parser.rb:43:in `generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/compilers.rb:248:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:100:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:88:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@hugoledoux - can you merge this PR? There's an issue with one of your DOIs: https://github.com/tudelft3d/3dfier/pull/124

**Comment by hugoledoux** [comment]
done.

I should re-issue/update v1.3.1 now, right?

**Comment by arfon** [comment]
> I should re-issue/update v1.3.1 now, right?

No, we don't need an update for something as small as this.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.buildenv.2014.04.013 is OK
- 10.1080/13658810701739039 is OK
- 10.4236/jep.2013.47081  is OK
- 10.1016/j.compenvurbsys.2011.02.001 is OK
- 10.14358/PERS.79.2.147 is OK
- 10.1186/s40965-019-0064-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2050

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2050, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
One more small set of changes @hugoledoux: https://github.com/tudelft3d/3dfier/pull/125

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.buildenv.2014.04.013 is OK
- 10.1080/13658810701739039 is OK
- 10.4236/jep.2013.47081  is OK
- 10.1016/j.compenvurbsys.2011.02.001 is OK
- 10.14358/PERS.79.2.147 is OK
- 10.1186/s40965-019-0064-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2051

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2051, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1354024550682533890) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2052
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02866](https://doi.org/10.21105/joss.02866)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@GANys, @chenkianwee - many thanks for your reviews here. JOSS relies upon the volunteer efforts of folks like yourself and we simply wouldn't be able to do this without you! :sparkles:

@hugoledoux - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02866/status.svg)](https://doi.org/10.21105/joss.02866)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02866">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02866/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02866/status.svg
   :target: https://doi.org/10.21105/joss.02866
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02866/status.svg)](https://doi.org/10.21105/joss.02866)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
