### ISSUE TITLE
[PRE REVIEW]: ClimDown: Climate Downscaling in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#287]
**Submitting author:** @jameshiebert (<a href="http://orcid.org/0000-0002-4171-9586">James Hiebert</a>)
**Repository:** <a href="https://github.com/pacificclimate/ClimDown" target ="_blank">https://github.com/pacificclimate/ClimDown</a>
**Version:** 1.0.3
**Editor:** @karthik
**Reviewer:** @mdsumner

**Author instructions**

Thanks for submitting your paper to JOSS @jameshiebert. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jameshiebert if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@arfon @karthik Is this another candidate for going through review via rOpenSci?

**Comment by karthik** [comment]
@kyleniemeyer Let me discuss with the editors and get back to you.

**Comment by karthik** [comment]
@kyleniemeyer Unfortunately this is not a fit for ropensci. So this should proceed as is with JOSS>

**Comment by kyleniemeyer** [comment]
@karthik ok, perhaps one of the R-focused @openjournals/joss-editors can take it them 😋

**Comment by karthik** [comment]
ok, I'm happy to take this on.

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
@whedon assign @mdsumner as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @mdsumner

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/360. Feel free to close this issue now!
