### ISSUE TITLE
[PRE REVIEW]: bcdata: An R package for searching & retrieving data from the B.C. Data Catalogue

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2870]
**Submitting author:** @boshek (<a href="http://orcid.org/0000-0002-9270-7884">Samuel Albers</a>)
**Repository:** <a href="https://github.com/bcgov/bcdata" target ="_blank">https://github.com/bcgov/bcdata</a>
**Version:** 0.2.1
**Editor:** @arfon
**Reviewers:** @tweed1e, @MilesMcBain
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @boshek. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@boshek if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.73 s (89.6 files/s, 87654.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              2              0              0          56933
R                               47            681           1461           2368
Markdown                         6            108              0            394
YAML                             6             33              3            248
Rmd                              4            262           1063             10
-------------------------------------------------------------------------------
SUM:                            65           1084           2527          59953
-------------------------------------------------------------------------------


Statistical information for the repository '3bb60aff067a889fb310112c' was
gathered on 2020/11/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andy Teucher                     4           453              7           50.77
stephhazlitt                     1             0            446           49.23

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2870 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02870/joss.02870/10.21105.joss.02870.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02870/joss.02870/10.21105.joss.02870.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@boshek - as [per our submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), could you please make sure your paper has a section headed 'Statement of need' describing the research need and purpose of this software for a non-specialist audience?

**Comment by boshek** [comment]
sorry about that @arfon. Added now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2870 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02870/joss.02870/10.21105.joss.02870.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02870/joss.02870/10.21105.joss.02870.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @boshek - could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02870/joss.02870/10.21105.joss.02870.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02870/joss.02870/10.21105.joss.02870.pdf) :page_facing_up: :point_left:

**Comment by boshek** [comment]
@arfon here is a list from the pool of reviewers. I have _not_ ranked these at all. Let me know if you'd like to trim down this list. 

Bryce Mecum: https://github.com/amoeba
Adam Sparks: https://github.com/adamhsparks/
Jesse Tweedle: https://github.com/tweed1e
Jeff Hollister: https://github.com/jhollist
Noam Ross: https://github.com/noamross
Maelle Salmon: https://github.com/maelle
Miles McBain: https://github.com/MilesMcBain/

**Comment by arfon** [comment]
:wave: @MilesMcBain & @tweed1e - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission to be reviewed here is _bcdata: An R package for searching & retrieving data from the B.C. Data Catalogue_.

- The software: https://github.com/bcgov/bcdata
- The paper: [10.21105.joss.02870.pdf](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02870/joss.02870/10.21105.joss.02870.pdf)

**Comment by tweed1e** [comment]
In! 👍

**Comment by MilesMcBain** [comment]
Happy to do it 😁

**Comment by arfon** [comment]
@whedon add @tweed1e as reviewer

**Comment by whedon** [comment]
OK, @tweed1e is now a reviewer

**Comment by arfon** [comment]
@whedon add @MilesMcBain as reviewer

**Comment by whedon** [comment]
OK, @MilesMcBain is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2927.

**Comment by arfon** [comment]
@tweed1e, @MilesMcBain - thanks for the quick responses here! See you over in #2927 for the actual review.
