### ISSUE TITLE
[REVIEW]: UQit: A Python package for uncertainty quantification (UQ) in computational fluid dynamics (CFD)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2871]
**Submitting author:** @salrm8 (<a href="http://orcid.org/0000-0002-9610-9910">Saleh Rezaeiravesh</a>)
**Repository:** <a href="https://github.com/KTH-Nek5000/UQit" target ="_blank">https://github.com/KTH-Nek5000/UQit</a>
**Version:** v1.0.2
**Editor:** @drvinceknight
**Reviewer:** @jayten, @ctdegroot
**Archive:** <a href="https://doi.org/10.5281/zenodo.4704355" target="_blank">10.5281/zenodo.4704355</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/07314f813b47f2779237ef753df89f3d/status.svg)](https://joss.theoj.org/papers/07314f813b47f2779237ef753df89f3d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/07314f813b47f2779237ef753df89f3d"><img src="https://joss.theoj.org/papers/07314f813b47f2779237ef753df89f3d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/07314f813b47f2779237ef753df89f3d/status.svg)](https://joss.theoj.org/papers/07314f813b47f2779237ef753df89f3d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/KTH-Nek5000/UQit" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jayten & @ctdegroot, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @drvinceknight know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/KTH-Nek5000/UQit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@salrm8) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/KTH-Nek5000/UQit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@salrm8) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jayten, @ctdegroot it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02871/joss.02871/10.21105.joss.02871.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02871/joss.02871/10.21105.joss.02871.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-1-4757-3799-8 is OK
- 10.1007/978-3-319-12385-1 is OK
- 10.1137/S1064827501387826 is OK
- 10.2307/j.ctv7h0skv is OK
- 10.1016/S0378-4754(00)00270-6 is OK
- 10.1142/p878 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @jayten, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @ctdegroot, please update us on how your review is going.

**Comment by jayten** [comment]
### Overview
The submitted software is well-written and acceptable for publication in JOSS.


### Regarding authors
The actual name of the contributor "saleh8" is not clear. If he/she is not the already existing author, consider adding his/her name to the list of authors or in the acknowledgment, accordingly. 

### Documentation
It will be better for people like me who do not use "conda" to have an already existing Documentation website or a PDF file. Already existing HTML files can be easily hosted on GitHub using [Github pages](https://pages.github.com/).

### Community guidelines
Since the authors plan to add a few more features in the future release, consider adding a simple contriubting.txt file to guide people interested in helping you with that work. 

### Test

- Is it possible to automate the tests? 

- **Error encountered while running tests**:

1. When I am trying to run 2d and 3d PCE tests, it am getting the following error:
```
Traceback (most recent call last):
  File "pce_tests.py", line 301, in <module>
    pce_2d_test()
  File "pce_tests.py", line 153, in pce_2d_test
    pce_=pce(fVal=fVal,xi=xiGrid,pceDict=pceDict,nQList=nQ)
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/pce.py", line 92, in __init__
    self.cnstrct()
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/pce.py", line 343, in cnstrct
    self.cnstrct_pd()
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/pce.py", line 446, in cnstrct_pd
    self.cnstrct_nonGQTP_pd()
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/pce.py", line 595, in cnstrct_nonGQTP_pd
    fCoef=linAlg.myLinearRegress(A,self.fVal) 
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/linAlg.py", line 53, in myLinearRegress
    f=linearSysSolver(A,R,1)
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/linAlg.py", line 46, in linearSysSolver
    object_value = prob.solve(verbose=True,max_iter=max_iter_)
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 752, in _solve
    solution = solving_chain.solve_via_data(
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 325, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/ecos_conif.py", line 137, in solve_via_data
    solution = ecos.solve(data[s.C], data[s.G], data[s.H],
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/ecos/ecos.py", line 62, in solve
    return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, A.data, A.indices, A.indptr, b, **kwargs)
TypeError: 'max_iter' is an invalid keyword argument for this function
```

2. Figures expected by the test for Lagrange interpolation are missing. The following error was issued:
`FileNotFoundError: [Errno 2] No such file or directory: '../testFigs/lag1d4.png'`

**Comment by drvinceknight** [comment]
Thank you for your review @jayten, @salrm8 if you could respond/modify as appropriate :+1:

**Comment by salrm8** [comment]
@jayten Thank you for your constructive comments. I certainly apply them and let you know.

**Comment by salrm8** [comment]
@drvinceknight and @jayten: Thank you again for the comments. Small modifications in the codes and documentation are applied and pushed to the repo. 
The summary of the actions/answers are as follows:

1. salrm8 and saleh8 are the IDs of the first author in the JOSS paper. 
2. A GitHub page is created to host the documentation: https://kth-nek5000.github.io/UQit/
3. File "CONTRIBUTING.md" is created to facilitate contributions. 
4. Run-time error 1: The 2d and 3d PCE tests should run now. The issue was that the setting "maxiter" in the linear solver in linAlg.py was set based on the default solver OSQP. Now different linear solvers required by [cxypy](https://www.cvxpy.org/tutorial/advanced/index.html?highlight=installed_solvers) can be used. 
5. Run-time error 2: Figure '../testFigs/lag1d4.png' was an output of the test. Now, saving the figure has been removed from the test. 
6. The only remaining comment is about automating the tests. Since running each test generates a set of plots, we thought it might be unnecessary to automate them. Also, the tests have also been used in the notebooks in the documentation. 

I hope these could answer the comments.

**Comment by jayten** [comment]
@salrm8, 
I have gone through the changes, and all of them work except for the run-time-error with the "pce_tests.py" file. I am still getting the "max_iter" keyword error even after pulling the latest changes made by you. 
```
Traceback (most recent call last):
  File "pce_tests.py", line 301, in <module>
    pce_2d_test()
  File "pce_tests.py", line 153, in pce_2d_test
    pce_=pce(fVal=fVal,xi=xiGrid,pceDict=pceDict,nQList=nQ)
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/pce.py", line 92, in __init__
    self.cnstrct()
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/pce.py", line 343, in cnstrct
    self.cnstrct_pd()
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/pce.py", line 446, in cnstrct_pd
    self.cnstrct_nonGQTP_pd()
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/pce.py", line 595, in cnstrct_nonGQTP_pd
    fCoef=linAlg.myLinearRegress(A,self.fVal) 
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/linAlg.py", line 53, in myLinearRegress
    f=linearSysSolver(A,R,1)
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/linAlg.py", line 46, in linearSysSolver
    object_value = prob.solve(verbose=True,max_iter=max_iter_)
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 752, in _solve
    solution = solving_chain.solve_via_data(
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 325, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/ecos_conif.py", line 137, in solve_via_data
    solution = ecos.solve(data[s.C], data[s.G], data[s.H],
  File "/home/jatinder/anaconda3/lib/python3.8/site-packages/ecos/ecos.py", line 62, in solve
    return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, A.data, A.indices, A.indptr, b, **kwargs)
TypeError: 'max_iter' is an invalid keyword argument for this function

```

**Comment by salrm8** [comment]
@jayten Has UQit been re-installed? It seems the previous version is still being used. One can simply replace "/home/jatinder/anaconda3/lib/python3.8/site-packages/UQit/linAlg.py" by the linAlg.py from the repo. 

After this test, I will upload a new version of UQit on PyPI. 
Thank you,

**Comment by jayten** [comment]
@salrm8 
You are correct. I did not update the installed version of UQit. I am not getting any error now.

**Comment by salrm8** [comment]
@jayten Great, thank you! I will push the revised version to PyPI.

**Comment by drvinceknight** [comment]
Hi both I will be offline from today for about 2 weeks.

**Comment by salrm8** [comment]
Dear @drvinceknight, 
Kindly, I wonder if there is any further comment which I need to take care of. Thank you!

**Comment by drvinceknight** [comment]
Hi @ctdegroot, this is a polite nudge in case this had dropped off your horizon, let us know when you've been able to take a look at this paper :)

**Comment by salrm8** [comment]
Hi @drvinceknight, I wonder if there has been any update. Thank you!

**Comment by drvinceknight** [comment]
@ctdegroot another polite nudge, do you think you'll be able to get to reviewing this?

@salrm8 if we don't hear back soon I'll aim to get another reviewer.

**Comment by ctdegroot** [comment]
Thanks for the nudge and apologies for the delay. I will prioritize this.

**Comment by salrm8** [comment]
@drvinceknight Hello. Sorry for reminding again, but I wonder if it could be possible to invite another reviewer to review the work?

**Comment by ctdegroot** [comment]
@drvinceknight I am working on this... sorry I didn't tick the boxes as I worked

**Comment by ctdegroot** [comment]
@salrm8 
This is a bit of an awkward statement in the paper: "It is important to note that uncertainty is different from error, which is defined as the deviation of a realization from a reference true value." While it is true that uncertainty is different than error, I think your definition of error is too limiting. For example, one may attempt to quantify discretization error while having no "true" value. Perhaps you may consider a definition where error is any recognizable error not due to lack of knowledge/information (https://www.grc.nasa.gov/www/wind/valid/tutorial/glossary.html#error). Otherwise I am satisfied with the conent of the paper.

**Comment by ctdegroot** [comment]
@salrm8 I was unable to find instructions on how to run the tests or how to run examples. Please let me know how to do this? Ideally this should be on the main README page. Once these two items are handled, I am satisfied with my review.

**Comment by salrm8** [comment]
> @salrm8
> This is a bit of an awkward statement in the paper: "It is important to note that uncertainty is different from error, which is defined as the deviation of a realization from a reference true value." While it is true that uncertainty is different than error, I think your definition of error is too limiting. For example, one may attempt to quantify discretization error while having no "true" value. Perhaps you may consider a definition where error is any recognizable error not due to lack of knowledge/information (https://www.grc.nasa.gov/www/wind/valid/tutorial/glossary.html#error). Otherwise I am satisfied with the conent of the paper.

Thank you @ctdegroot for the comment. I understand the point of view, however, we are discussing the uncertainty in a QoI which is the outcome of a simulation, for instance. To emphasize this, we have modified the sentence  "It is important to note that uncertainty is different ..." as "It is important to note that **for a QoI**, uncertainty is different ...". 

There are also a few ways to define error and uncertainty, for instance in AIAA Guide and UQ literature. But these definitions are not contradictory. Among other things, what is needed to be clearly specified is whether error/uncertainty in the modeling/codes or a QoI is addressed. 

In the discretization error example by the reviewer,  if we use modified equation approach in finite-difference method for instance, then the solution around which the expansion is made can be considered as a reference truth. If instead we mean a posteriori error in QoIs, then we need to compare the numerical solution to continuous solution or experimental data: again we have a reference value. 
However, there are cases where the combination of errors can lead to behaviors which could not be a-priori predicted or even be against what is expected. A good example is the scale-resolving simulation of turbulent flows and influence of the  numerical parameters at resolutions coarser than DNS. In this cases, the evolvement of errors may lead to uncertainties.

**Comment by salrm8** [comment]
> @salrm8 I was unable to find instructions on how to run the tests or how to run examples. Please let me know how to do this? Ideally this should be on the main README page. Once these two items are handled, I am satisfied with my review.

Thank you @ctdegroot. We have added a short guide in README on how to run a test: 

### How to run a test:
The tests associated to different UQ techniques are provided in `./tests/`.
Most of the tests have also been used in the notebooks and documentation.
For instance, to run a test from `pce_tests.py` in `./tests/`, do the following:

`python3 -c 'import pce_tests as X;X.pce_1d_test()'`

**Comment by salrm8** [comment]
Hi @ctdegroot, I wonder if the above answers are satisfactory. Thank you!

**Comment by ctdegroot** [comment]
@salrm8 I accept your explanation of the reference value. However, I think it should not say "reference true value", but just "reference value". This would be more consistent with your own explanation with regards to a posteriori error estimations. Yes, it is a reference value as you explained, but I can't see how the word "true" applies in this case.

With regards to the change in the readme, explaining how to run a test, I am pleased.

**Comment by salrm8** [comment]
@ctdegroot Thank you for your comment. What was meant in the text by "reference true data" is for instance, a reference DNS or experimental data for the quantities of interest obtained by minimizing the error and uncertainties from all possible sources. But we never get rid of the error and uncertainties completely. Still, the reported QoIs can be considered the most accurate values for describing the physics and hence be used for evaluation of other simulations/experiments.  
In fact, from theoretical point of view, we have "true unobserved" values which can be estimated by numerical simulations and experiments.

**Comment by ctdegroot** [comment]
I don’t even think “reference true value” is even proper grammar. I would like this changed.

**Comment by ctdegroot** [comment]
I would accept “reference (true) value” as an alternative.

**Comment by salrm8** [comment]
It has been changed to "reference (true) value".

**Comment by ctdegroot** [comment]
@drvinceknight I have nothing more to add.

**Comment by salrm8** [comment]
Hi @drvinceknight, is there any other thing I need to do? Thank you!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02871/joss.02871/10.21105.joss.02871.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02871/joss.02871/10.21105.joss.02871.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @salrm8, I am the AEIC on duty this week, and it looks like this submission is essentially ready to be accepted. I noticed some small issues with citation formatting, and fixed them in https://github.com/KTH-Nek5000/UQit/pull/3. Can you merge this PR?

Once you've done that, you can archive your software repository (e.g., on Zenodo) and let us know the DOI here.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02871/joss.02871/10.21105.joss.02871.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02871/joss.02871/10.21105.joss.02871.pdf) :page_facing_up: :point_left:

**Comment by salrm8** [comment]
@kyleniemeyer Thank you! I will archive the repo and let you know.

**Comment by salrm8** [comment]
@kyleniemeyer Hi! Here is the DOI from Zenodo:

https://zenodo.org/badge/306281730.svg

**Comment by kyleniemeyer** [comment]
@salrm8 ah, thanks - could you clean up the author list on the Zenodo archive to match the paper?

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.4704355 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4704355" target="_blank">10.5281/zenodo.4704355</a> is the archive.

**Comment by salrm8** [comment]
> @salrm8 ah, thanks - could you clean up the author list on the Zenodo archive to match the paper?

@kyleniemeyer Done! Thank you.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2249

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2249, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1384561995538702340) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2250
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02871](https://doi.org/10.21105/joss.02871)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @salrm8 on your article's publication in JOSS!

Many thanks to  @jayten and @ctdegroot for reviewing this submission, and @drvinceknight for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02871/status.svg)](https://doi.org/10.21105/joss.02871)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02871">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02871/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02871/status.svg
   :target: https://doi.org/10.21105/joss.02871
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02871/status.svg)](https://doi.org/10.21105/joss.02871)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by salrm8** [comment]
> Congrats @salrm8 on your article's publication in JOSS!
> 
> Many thanks to @jayten and @ctdegroot for reviewing this submission, and @drvinceknight for editing.

Thank you @kyleniemeyer , @drvinceknight , @jayten, and @ctdegroot!
