### ISSUE TITLE
[REVIEW]: SimpleSDMLayers.jl and GBIF.jl: A Framework for Species Distribution Modeling in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2872]
**Submitting author:** @gabrieldansereau (<a href="http://orcid.org/0000-0002-2212-3584">Gabriel Dansereau</a>)
**Repository:** <a href="https://github.com/EcoJulia/SimpleSDMLayers.jl" target ="_blank">https://github.com/EcoJulia/SimpleSDMLayers.jl</a>
**Version:** v0.3.4
**Editor:** @KristinaRiemer
**Reviewer:** @dglmoore, @marcjwilliams1
**Archive:** <a href="https://doi.org/10.5281/zenodo.4472905" target="_blank">10.5281/zenodo.4472905</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/7f4f28130ba9b2515909d00f82d25865/status.svg)](https://joss.theoj.org/papers/7f4f28130ba9b2515909d00f82d25865)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7f4f28130ba9b2515909d00f82d25865"><img src="https://joss.theoj.org/papers/7f4f28130ba9b2515909d00f82d25865/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7f4f28130ba9b2515909d00f82d25865/status.svg)](https://joss.theoj.org/papers/7f4f28130ba9b2515909d00f82d25865)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/EcoJulia/SimpleSDMLayers.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dglmoore & @marcjwilliams1, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @KristinaRiemer know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/EcoJulia/SimpleSDMLayers.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@gabrieldansereau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/EcoJulia/SimpleSDMLayers.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@gabrieldansereau) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dglmoore, @marcjwilliams1 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02872/joss.02872/10.21105.joss.02872.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02872/joss.02872/10.21105.joss.02872.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @dglmoore, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @marcjwilliams1, please update us on how your review is going.

**Comment by marcjwilliams1** [comment]
Overall I think the package and article are excellent and they more than satisfy all the requirements for JOSS. The documentation and API is clear and easy to use and it is great to see high coverage testing (>80%) of the functionality. A few small comments below:
1. The CI is currently failing on master,I can see previous versions have been passing so have no concerns that these are important issues.
2. Although far from an expert on computational ecology I can see how this package would make some types of modeling easier through integration with other packages as mentioned in the article, are there examples of this in the wider EcoJulia ecosystem? I think it would be nice to mention if so.

**Comment by KristinaRiemer** [comment]
@marcjwilliams1 thank you for your review and your thoughtful questions/comments, hopefully @gabrieldansereau will have a chance to respond soon. 

@dglmoore, I just noticed that you were not added as an assignee to this issue, I'm going to try to fix that now.

**Comment by KristinaRiemer** [comment]
@whedon re-invite @dglmoore as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@dglmoore please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by dglmoore** [comment]
@KristinaRiemer thank you for re-inviting me. I'll take care of the review today.

**Comment by dglmoore** [comment]
The article and documentation are great. The package has some really nice features that should make many common tasks painless. Performance was good and the code quality looks high.

The only concern at the moment is the failing unit tests, but I suspect that's a simple enough issue to resolve. With this possible exception, all of the JOSS requirements are met or exceeded in my opinion.

**Comment by gabrieldansereau** [comment]
@marcjwilliams1 @dglmoore Thank you for your helpful reviews and sorry for the delay.

I fixed the tests in EcoJulia/SimpleSDMLayers.jl#44 and released a new version of the package. As expected by the reviewers, it was a simple fix, a problem with the download URL for one of the supported datasets, which seems to have changed. All other functionalities should work properly.

@marcjwilliams1's comment on integration with other EcoJulia packages is very relevant, however, we do not have such an example of wider integration yet. For now, EcoJulia has a few combinations of packages working together, such as SimpleSDMLayers.jl and GBIF.jl (in review here), or Mangal.jl and EcologicalNetworks.jl (also in review at JOSS). Wider integration between more packages is a long term goal of EcoJulia, but we are not quite there yet. We will for sure include some examples in the package's documentation once we do.

**Comment by tpoisot** [comment]
Hi @KristinaRiemer @gabrieldansereau - is there something we can do to help with the next step?

**Comment by KristinaRiemer** [comment]
Thanks for checking in @tpoisot. It looks like @gabrieldansereau has addressed all of the reviewer comments, so we just need final confirmation from @marcjwilliams1 and @dglmoore that they are satisfied with this submission.

**Comment by marcjwilliams1** [comment]
All good with me, can confirm I'm satisfied with this submission.

**Comment by dglmoore** [comment]
I am satisfied with the submission.

**Comment by KristinaRiemer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02872/joss.02872/10.21105.joss.02872.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02872/joss.02872/10.21105.joss.02872.pdf) :page_facing_up: :point_left:

**Comment by KristinaRiemer** [comment]
Thanks for the confirmations, @marcjwilliams1 & @dglmoore! 

@gabrieldansereau I went through the article proof to check for reference formatting, typos, etc., and found a few things to improve: 

- line 53: remove "an"
- lines 129-131: change verbs to clip, coarsen, and perform
- Chamberlain et al., 2020 should have rgbif in title lower case
- add links to software references, e.g., [the suggested citation for rgbif](https://cran.r-project.org/web/packages/rgbif/citation.html) includes link to CRAN page

You should also read through the PDF and make sure you're happy with it, let me know when you've made those updates and are done.

**Comment by gabrieldansereau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02872/joss.02872/10.21105.joss.02872.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02872/joss.02872/10.21105.joss.02872.pdf) :page_facing_up: :point_left:

**Comment by gabrieldansereau** [comment]
@KristinaRiemer Thank you for pointing these out.

I made the changes you requested, along with a few minor ones while re-reading. @tpoisot and I are now happy with the PDF.

**Comment by KristinaRiemer** [comment]
@whedon check references

**Comment by KristinaRiemer** [comment]
Great, thank you for doing that @gabrieldansereau. The next steps are to: 1) create a new tagged release on GitHub and 2) archive the code (on Zenodo, figshare, institutional repository, etc.) to generate a DOI. If you can post a link to the DOI here when you're done please.

**Comment by gabrieldansereau** [comment]
@KristinaRiemer I've released a new version (v0.3.4). The DOI for the [Zenodo archive](https://zenodo.org/record/4464943) is `10.5281/zenodo.4464943`.

**Comment by KristinaRiemer** [comment]
It looks like there's an additional author for the Zenodo archive, should that person be included as an author for the JOSS publication?

**Comment by gabrieldansereau** [comment]
@KristinaRiemer No, although he is an important contributor to the EcoJulia organization, he was not involved in this submission to JOSS and his contribution to this specific package was very minor. 

I believe he was listed automatically on Zenodo for 2 minor commits in 2019 (one small syntax and one default parameter change).

**Comment by KristinaRiemer** [comment]
@whedon set 10.5281/zenodo.4464943 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4464943" target="_blank">10.5281/zenodo.4464943</a> is the archive.

**Comment by KristinaRiemer** [comment]
@whedon set v0.3.4 as version

**Comment by whedon** [comment]
OK. v0.3.4 is the version.

**Comment by KristinaRiemer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2872 with the following error: 

 [WARNING] Missing character: There is no ⋮ (U+22EE) in font [lmmono10-regular]:!
[WARNING] Missing character: There is no ⋱ (U+22F1) in font [lmmono10-regular]:!
/app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.6/lib/bibtex/bibliography.rb:50:in `read': No such file or directory @ rb_sysopen - 72810ef458cb6ab33ef3e4fd/joss/["paper.bib"] (Errno::ENOENT)
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.6/lib/bibtex/bibliography.rb:50:in `open'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.6/lib/bibtex/utilities.rb:25:in `open'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/bibtex_parser.rb:38:in `generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/compilers.rb:248:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:100:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:88:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by gabrieldansereau** [comment]
@KristinaRiemer I believe this is because of the `⋮` and `⋱` symbols on line 161 of the markdown file. I just realized they are not in the PDF either (line 86 of that file).

I'll try removing them as they are not really needed.

**Comment by gabrieldansereau** [comment]
Just removed on `master` in [this commit](https://github.com/EcoJulia/SimpleSDMLayers.jl/commit/5cc32ca5241c77a1681ddd07273c75c5dc5fe903).

Do I need to release a new version too?

**Comment by KristinaRiemer** [comment]
I'm not sure, I haven't dealt with this sort of issue before. @kthyng would you be able to help with this?

**Comment by danielskatz** [comment]
@KristinaRiemer - feel free to ask @openjournals/joss-eics about things like this, so that you get whichever one of us is currently on-duty (me, this week).

No, a new release is not needed for small changes in the paper.  Just run the accept again...

**Comment by KristinaRiemer** [comment]
Ah, okay. Thanks @danielskatz!

**Comment by KristinaRiemer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2872 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.6/lib/bibtex/bibliography.rb:50:in `read': No such file or directory @ rb_sysopen - b42433e841a9ec14519387a7/joss/["paper.bib"] (Errno::ENOENT)
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.6/lib/bibtex/bibliography.rb:50:in `open'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.6/lib/bibtex/utilities.rb:25:in `open'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/bibtex_parser.rb:38:in `generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/compilers.rb:248:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:100:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:88:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by gabrieldansereau** [comment]
Could the error happen because I had `bibliography: [paper.bib]` instead of `bibliography: paper.bib` in the markdown header? I made the change [here](https://github.com/EcoJulia/SimpleSDMLayers.jl/commit/789e8134de5c2a90ffba8d0a1343d7045fba48ee), maybe we should try again? (It still works with the JOSS preview service)

**Comment by arfon** [comment]
`bibliography: paper.bib` should fix the paper compilation issue here.

**Comment by gabrieldansereau** [comment]
@KristinaRiemer The header should be fixed now. Anything else I need to do?

**Comment by KristinaRiemer** [comment]
@gabrieldansereau let's see if that worked!

**Comment by KristinaRiemer** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1126/sciadv.aat4858 is OK
- 10.1137/141000671 is OK
- 10.1111/ddi.12144 is OK
- 10.1002/ecs2.2567 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2053

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2053, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by KristinaRiemer** [comment]
It worked! Now one of the EiCs will take care of the last bit.

**Comment by gabrieldansereau** [comment]
Awesome, thank you very much!

**Comment by danielskatz** [comment]
@gabrieldansereau - the zenodo archive has a different title and authors than the paper. Usually, these should be the same. Can you change the zenodo metadata or explain why these are different?

**Comment by danielskatz** [comment]
You can (and I think should) change the zenodo metadata to match the paper - you don't have to keep the automatically compiled metadata.

**Comment by tpoisot** [comment]
@danielskatz - I think the contributions to the code and paper can be kept different, and I would not be comfortable changing the metadata on zenodo.

**Comment by danielskatz** [comment]
I've also suggesting changing some cases in the paper text: https://github.com/EcoJulia/SimpleSDMLayers.jl/pull/46

**Comment by tpoisot** [comment]
the casing changes have been merged

**Comment by danielskatz** [comment]
> I would not be comfortable changing the metadata on zenodo.

Why not? This is a normal thing that is done by JOSS authors. We really would like you to change the title, at least, as the automatically generated title is not very descriptive, though maybe leaving the authors as it is makes sense in this case.

**Comment by tpoisot** [comment]
I'm sorry can you clarify which title? The paper is in the repo of _one_ package, but describes _two_ packages. Changing the title of the zenodo repo would make the _package_ title less descriptive.

**Comment by danielskatz** [comment]
The paper title is: SimpleSDMLayers.jl and GBIF.jl: A Framework for Species Distribution Modeling in Julia
We normally expect that for a JOSS paper there is an archive that contains a snapshot of the software that was reviewed, and the title of that archive entry matches the title of paper.

In the paper draft, I see a link to a zenodo archive title with the title: EcoJulia/SimpleSDMLayers.jl: v0.3.4
Normally, this would be an archive for all the software that was reviewed.
Is there also a second zenodo archive for GBIF?

If so, I think perhaps we want a single archive that contains both, which in this case will have to created manually, since JOSS does not have a way to link to two archives.

And maybe @arfon will have some additional thoughts on this

**Comment by tpoisot** [comment]
The dual archive would not work with Julia packaging system, which requires the packages be kept in separate repos. There is, of course, a second zenodo archive for GBIF.jl - https://zenodo.org/record/4293898#.YBGAZtZyYew - making a single archive for the two of them would lead to duplication of content and ensure that the joint archive is not kept up to date, and it's not me being obtuse, I just don't see the benefits for users.

I'd also like to add that GBIF.jl is not *necessary* for for SimpleSDMLayers.jl to function (and that wen installed, only the version of it compatible with SimpleSDMLayers.jl will be available.

**Comment by tpoisot** [comment]
(as a side note a re-tagged version of the package is on its way with a changed title)

**Comment by danielskatz** [comment]
In a JOSS paper, there is a single link that should point to an archive of all the reviewed software.
(This archive is a permanent record of the reviewed software, not a live version.)

In this case, the link does not - it only points to part of the reviewed software. To me, this is a problem.
But it's easy to fix, by creating an archive (in zenodo, figshare, etc.) that contains both packages - again, this is for the scholarly records associated with this paper, not for people who want to use the software, who would go to the github repos.  And yes, this has to be done manually in this case, because it's not something the zenodo-github linkage supports.

**Comment by danielskatz** [comment]
> ensure that the joint archive is not kept up to date, and it's not me being obtuse, I just don't see the benefits for users.

This doesn't need to be kept up to date, and it's not for users.  It's for the scholarly record associated with this paper, and is a one-time need for the paper.

**Comment by tpoisot** [comment]
Is it better than linking both DOIs? I can do a one-time archive with both. if this is a _requirement_ from the editorial board, althought I don't see the point. Just tell me which title you think it should have and I will get it done.

**Comment by danielskatz** [comment]
Linking both DOIs would be better in some ways, but the JOSS paper template doesn't support it.  There is a requirement to link to the reviewed software, and I think because of the JOSS template, we need a single archive that contains it.

**Comment by tpoisot** [comment]
Here is an archive with the two zips of both packages: `10.5281/zenodo.4472905 `

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.4472905 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4472905" target="_blank">10.5281/zenodo.4472905</a> is the archive.

**Comment by danielskatz** [comment]
hmmm - that doesn't resolve for me right now.  Can you also share the direct URL for me to check?

**Comment by gabrieldansereau** [comment]
https://zenodo.org/record/4472905

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2054

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2054, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2872 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/JuliaCon/proceedings-review/issues/2872: 404 - Not Found // See: https://docs.github.com/rest/reference/issues#get-an-issue (Octokit::NotFound)
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	from /app/vendor/bundle/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/connection.rb:156:in `request'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/connection.rb:19:in `get'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/client/issues.rb:114:in `issue'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/review.rb:21:in `issue_body'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:74:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1354456684375244804) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2055
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02872](https://doi.org/10.21105/joss.02872)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by KristinaRiemer** [comment]
Looks like whedon was a little slow, does [this](https://github.com/openjournals/joss-reviews/issues/2872#issuecomment-768377632) need to be dealt with?

**Comment by danielskatz** [comment]
@openjournals/dev  - please notice [this transient problem](https://github.com/openjournals/joss-reviews/issues/2872#issuecomment-768377632) which I worked around by just re-running the comment

**Comment by danielskatz** [comment]
Congratulations to @gabrieldansereau and @tpoisot!!

And thanks to @dglmoore and @marcjwilliams1 for reviewing, and @KristinaRiemer for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02872/status.svg)](https://doi.org/10.21105/joss.02872)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02872">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02872/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02872/status.svg
   :target: https://doi.org/10.21105/joss.02872
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02872/status.svg)](https://doi.org/10.21105/joss.02872)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by gabrieldansereau** [comment]
Thank you very much @danielskatz @KristinaRiemer @dglmoore @marcjwilliams1!

**Comment by arfon** [comment]
> Linking both DOIs would be better in some ways, but the JOSS paper template doesn't support it. There is a requirement to link to the reviewed software, and I think because of the JOSS template, we need a single archive that contains it.

:wave: folks - just popping in here to say that currently this is the only way for JOSS to handle submissions like this. I would like us to be able to link to multiple software archives (and repositories) but the current model for JOSS is one review per software repository.

**Comment by KristinaRiemer** [comment]
Thanks everyone!
