### ISSUE TITLE
[PRE REVIEW]: Pre-trained Deep-Learning Models That Enable Computational Developmental Biology Research and Education

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2873]
**Submitting author:** @balicea (<a href="http://orcid.org/0000-0003-3869-3175">Bradly Alicea</a>)
**Repository:** <a href="https://github.com/DevoLearn/Education/" target ="_blank">https://github.com/DevoLearn/Education/</a>
**Version:** 0.2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @balicea. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kakiac.

@balicea if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.01 s (373.5 files/s, 15462.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              1              0              0             86
Markdown                         4             43              0             78
-------------------------------------------------------------------------------
SUM:                             5             43              0            164
-------------------------------------------------------------------------------


Statistical information for the repository '98962524f30969a324a604e0' was
gathered on 2020/11/30.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #2873 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon reject 

:wave: @balicea - assuming this submission is associated with this project https://github.com/DevoLearn/devolearn, please resubmit with your paper _in that repository_ (a non-default branch is fine). Also, as [per our submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html), please rename your paper to `paper.md`

**Comment by whedon** [comment]
Paper rejected.
