### ISSUE TITLE
[PRE REVIEW]: nettskjemar - An R-package for API connection to the University of Oslo's Nettskjema survey tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2874]
**Submitting author:** @athanasiamo (<a href="http://orcid.org/0000-0002-5756-0223">Athanasia M. Mowinckel</a>)
**Repository:** <a href="https://github.com/LCBC-UiO/nettskjemar" target ="_blank">https://github.com/LCBC-UiO/nettskjemar</a>
**Version:** 0.1.03
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @athanasiamo. **Currently, there isn't an JOSS editor assigned** to your paper.

@athanasiamo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (355.5 files/s, 23415.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               23            214            457            726
XML                              1              0              2            441
Markdown                         5             44              0            149
YAML                             4             19              7            123
SVG                              1              1              1            107
TeX                              2              3              0             89
Rmd                              3             51            105             30
-------------------------------------------------------------------------------
SUM:                            39            332            572           1665
-------------------------------------------------------------------------------


Statistical information for the repository '048805eee385e13d6e875ae9' was
gathered on 2020/11/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Athanasia Monika Mow             2           200            200          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02874/joss.02874/10.21105.joss.02874.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02874/joss.02874/10.21105.joss.02874.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5040/9781782258674 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon query scope

@Athanasiamo – due to the small size of this code and the software application, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@whedon reject 

@Athanasiamo - Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by whedon** [comment]
Paper rejected.

**Comment by Athanasiamo** [comment]
Thank you for considering the submission, and for providing alternative possibilities.
