### ISSUE TITLE
[PRE REVIEW]: Archeofrag: an R package for refitting and stratigraphic analysis in archaeology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2875]
**Submitting author:** @sebastien-plutniak (<a href="http://orcid.org/0000-0002-6674-3806">Sébastien Plutniak</a>)
**Repository:** <a href="https://github.com/sebastien-plutniak/archeofrag" target ="_blank">https://github.com/sebastien-plutniak/archeofrag</a>
**Version:** v0.6.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sebastien-plutniak. **Currently, there isn't an JOSS editor assigned** to your paper.

@sebastien-plutniak if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (419.0 files/s, 43396.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               14             95             56            553
Markdown                         2            167              0            380
Rmd                              2            229            375            155
TeX                              1             16              0             92
YAML                             2              5              3             49
-------------------------------------------------------------------------------
SUM:                            21            512            434           1229
-------------------------------------------------------------------------------


Statistical information for the repository '5210deddc12eb32bb7416a0f' was
gathered on 2020/11/30.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02875/joss.02875/10.21105.joss.02875.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02875/joss.02875/10.21105.joss.02875.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4271900 is OK
- 10.21105/joss.01821 is OK
- 10.18637/jss.v093.c01 is OK
- 10.18129/B9.bioc.RBGL is OK
- 10.1016/j.quaint.2015.11.080 is OK

MISSING DOIs

- 10.7551/mitpress/10909.003.0005 may be a valid DOI for title: The Big Puzzle

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon query scope

@sebastien-plutniak  – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@whedon reject 

@sebastien-plutniak - Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by whedon** [comment]
Paper rejected.

**Comment by sebastien-plutniak** [comment]
@arfon Thank you for this feedback. May I ask you more about the criteria to determine the “minor utility” category? (should the submission be relevant for more than a specific discipline? in this case archaeology). More information would help me to consider resubmitting (or not) this paper/package. Thank you.

**Comment by arfon** [comment]
Apologies, I should have stated "substantial scholarly effort" as the reason here. You can read more about this here: https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort

**Comment by sebastien-plutniak** [comment]
Thank you for this. In this case, I was aware of the “substantial scholarly effort” when reading the requirements for submission. Sorry for reacting to the rejection decision, but this package (and its forthcoming companion paper) are the results of an ongoing development since 2014, including four conference presentations and advice from several supporting colleagues… so actually much more than “three months of work for an individual”. 
Generally speaking, do you authorize and consider re-submission? (If this package will finally meet more  “substantial scholarly effort” criterias in the future). Thanks, Sébastien

**Comment by arfon** [comment]
> Generally speaking, do you authorize and consider re-submission? (If this package will finally meet more “substantial scholarly effort” criterias in the future). Thanks, Sébastien

Yes, resubmissions are welcome if/when further investments are made into this package.
