### ISSUE TITLE
[REVIEW]: Isoreader: An R package to read stable isotope data files for reproducible research

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2878]
**Submitting author:** @sebkopf (<a href="http://orcid.org/0000-0002-2044-0201">Sebastian Kopf</a>)
**Repository:** <a href="https://github.com/isoverse/isoreader" target ="_blank">https://github.com/isoverse/isoreader</a>
**Version:** v1.3.0
**Editor:** @mikldk
**Reviewers:** @kdorheim, @r-barnes
**Archive:** <a href="https://doi.org/10.5281/zenodo.4724083" target="_blank">10.5281/zenodo.4724083</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/558d2ff8cdc1098df31b718555f4181d/status.svg)](https://joss.theoj.org/papers/558d2ff8cdc1098df31b718555f4181d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/558d2ff8cdc1098df31b718555f4181d"><img src="https://joss.theoj.org/papers/558d2ff8cdc1098df31b718555f4181d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/558d2ff8cdc1098df31b718555f4181d/status.svg)](https://joss.theoj.org/papers/558d2ff8cdc1098df31b718555f4181d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/isoverse/isoreader" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kdorheim and @r-barnes, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mikldk know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/isoverse/isoreader">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@sebkopf) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/isoverse/isoreader">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@sebkopf) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kdorheim it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/gbi.12312 is OK
- 10.1002/lom3.10300 is OK
- 10.1111/gbi.12386 is OK
- 10.1144/SP507-2020-85 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02878/joss.02878/10.21105.joss.02878.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02878/joss.02878/10.21105.joss.02878.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@kdorheim: Thanks for agreeing to review. Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If possible create issues (and cross-reference) in the submission's repository to avoid too specific discussions in this review thread. 

If you have any questions or concerns please let me know.

**Comment by kdorheim** [comment]
@sebkopf, `isoreader` is well written, well documented, and fulfills an important need in supporting reproducible open-source science. As indicated by the manuscripts that have cited this package it has already been useful to the community. The paper clearly describes the need for this package and is well written for a general audience (as a non-specialist I really appreciated that), however, it seems like the authors could have referenced citations for some of the information in the summary (i.e. the comments about availability and variability of isotopes). This being said if these generally known facts in the community, then no citations are needed. I've opened some issues on the `isoreader` repo related to the [JOSS](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) guidelines, which I believe are relatively minor fixes.

**Comment by mikldk** [comment]
@whedon add @r-barnes as reviewer

**Comment by whedon** [comment]
OK, @r-barnes is now a reviewer

**Comment by mikldk** [comment]
@r-barnes: Thanks for agreeing to review. Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. If possible create issues (and cross-reference) in the submission's repository to avoid too specific discussions in this review thread.

If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@kdorheim, @r-barnes, would you mind giving a brief status of your progress?

**Comment by kdorheim** [comment]
Hi @mikldk, I've gone through the checklist, opened issues when relevant/marked others as complete. 

> JOSS plain text license files isoverse/isoreader#141
 Open
JOSS Contribution and authorship isoverse/isoreader#142
 Open
JOSS Installation instructions isoverse/isoreader#143
 Open
JOSS Automated tests isoverse/isoreader#144
 Open
JOSS Example usage isoverse/isoreader#145

**Comment by sebkopf** [comment]
thank you @kdorheim! pull request for the changes to address the raised issues is here: https://github.com/isoverse/isoreader/pull/148

**Comment by whedon** [comment]
:wave: @kdorheim, please update us on how your review is going.

**Comment by mikldk** [comment]
@kdorheim, @r-barnes, would you mind giving a brief status of your progress?

**Comment by kdorheim** [comment]
@whedon I've been working with @sebkopf on resolving the only remaining open issue I opened as part of my review.

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by mikldk** [comment]
@r-barnes, would you mind giving a brief status of your progress?

**Comment by mikldk** [comment]
@r-barnes, would you mind giving a brief status of your progress?

**Comment by r-barnes** [comment]
Apologies; I'll put this review at the top of my todo list for tomorrow.

**Comment by mikldk** [comment]
> Apologies; I'll put this review at the top of my todo list for tomorrow.

Thanks, @r-barnes . Can you give any indication of the expected time frame for your review?

**Comment by kdorheim** [comment]
@mikldk, @sebkopf has done an excellent job addressing all of the issues I opened related to this package. 👍

**Comment by mikldk** [comment]
Thanks, @kdorheim and @sebkopf .

@r-barnes, would you mind giving a brief status of your progress?

**Comment by r-barnes** [comment]
For whatever reason, I'm unable to see the `LICENSE` file. However, CRAN can be a bear to work with and I see the license info in the `DESCRIPTION` file that CRAN uses, so I feel myself satisfied.

**Comment by r-barnes** [comment]
Sorry I'm so behind on this!

I've just finished looking through the repo. In general, things look pretty good. I've opened a few issues, as above. I reiterate the main points below:

1. Installation did not complete for me. It looks like some dependencies are not on CRAN and I didn't immediately see instructions for overcoming this.
2. This isn't my field, so I don't have appropriate input data available, but it looks highly plausible that the software does what is claimed. In particular, the impressively thorough [documentation](https://isoreader.isoverse.org/reference/) and the presence of unit tests are good evidence. However, the authors do claim the software will read a number of file types, but only have tests for a subset of these. From a testing perspective alone, it would be good to fill this gap. In this case, it's also important for evaluating functionality (at least for me).
3. Example usage. If I click around I can find a lot of complex examples. I think the README itself would be facilitated by having an extremely simple example to get the reader started (similar to what I do [here](https://github.com/r-barnes/dggridR), perhaps). I feel like a simple example helps sell viewers on the idea of looking in depth.

I think once these are taken care of, this should be good to go.

**Comment by mikldk** [comment]
Thanks for the progress, @r-barnes . @sebkopf , please update us here when you have addressed the comments/issues put forward by @r-barnes .

**Comment by sebkopf** [comment]
Thank you @r-barnes for going through this. A few quick questions for clarification

> For whatever reason, I'm unable to see the LICENSE file. However, CRAN can be a bear to work with and I see the license info in the DESCRIPTION file that CRAN uses, so I feel myself satisfied.

Thank you for checking. The `LICENSE` is in the Joss branch at https://github.com/isoverse/isoreader/tree/joss, waiting for all edits from the review process to merge.

> 1. Installation did not complete for me. It looks like some dependencies are not on CRAN and I didn't immediately see instructions for overcoming this.

Could you copy which dependencies it is having trouble with? I'm testing on Windows, Linux and Mac OS with GitHub actions but could not find issues with dependencies except for the unreleased R development version (4.1) where `devtools` is not yet available. I suspect it might be `digest` which has in the past sometimes been a problem on windows (instructions for reinstall in the readme) or the bioconductor dependency `rhdf5` if `BiocManager` is not pulled correctly from CRAN. We can definitely add some troubleshooting guidelines for these if they are what is causing the problem.

> 2. This isn't my field, so I don't have appropriate input data available, but it looks highly plausible that the software does what is claimed. In particular, the impressively thorough documentation and the presence of unit tests are good evidence. However, the authors do claim the software will read a number of file types, but only have tests for a subset of these. From a testing perspective alone, it would be good to fill this gap. In this case, it's also important for evaluating functionality (at least for me).

The unit tests for the different file types (continuous flow, dual inlet and scan data) are in different test files to keep them easier to maintain with several example files included for all supported data types (for exactly the reason you mentioned, important to ensure functionality across the board): 
 - https://github.com/isoverse/isoreader/blob/master/tests/testthat/test-continuous-flow.R for testing .iarc, .dxf, .cf files
 - https://github.com/isoverse/isoreader/blob/master/tests/testthat/test-dual-inlet.R for testing .did, .caf, .txt files
 - https://github.com/isoverse/isoreader/blob/master/tests/testthat/test-scan.R for testing .scn files
 - https://github.com/isoverse/isoreader/blob/master/tests/testthat/test-export.R for testing export and re-import of .cf.rds, .did.rds and .scn.rds 
 
Note that not all of the example files are included on CRAN because of the limits on package file size but are always tested as part of the GitHub continuous integration. Also, some file extensions have more test files than others because we found more variability in the format (despite identical extension). Would you recommend additional tests or are these sufficient?

> 3. Example usage. If I click around I can find a lot of complex examples. I think the README itself would be facilitated by having an extremely simple example to get the reader started (similar to what I do here, perhaps). I feel like a simple example helps sell viewers on the idea of looking in depth.

We originally had this in the README but it got too cluttered so decided to put it into a `Quick Start` vignette, which is at https://isoreader.isoverse.org/articles/quick_start.html and covers some very basic code usage for the package. Would you suggest including this in the README as well or would it suffice to make a clear `How to get started` section in the readme that links to this vignette? (I realize we completely forgot to link this in the readme!)

Thank you very much for your time!

**Comment by sebkopf** [comment]
Hi @r-barnes, just a quick note that the README updates (and all other JOSS review related updates) are now merged into master and reflected at https://isoreader.isoverse.org/ (including clear links to the vignettes and a snippet of example code). Let me know if you have any other questions regarding the testing details mentioned above or if this all sounds good for moving towards publication.

Thank you very much.

**Comment by sebkopf** [comment]
@mikldk and @r-barnes : I think all issues raised by @r-barnes have now been addressed. Please let us know if you still see anything missing. Thank you very much for all your work on reviewing this. Best regards.

**Comment by mikldk** [comment]
@r-barnes still needs to check a few boxes. Can you give a status update?

**Comment by mikldk** [comment]
@r-barnes still needs to check a few boxes. Can you give a status update?

**Comment by mikldk** [comment]
@r-barnes still needs to check a few boxes. Can you give a status update?

**Comment by r-barnes** [comment]
Sorry for going MIA. I've noticed github's notification system has improved, so hopefully I can make better use of that in the future. I'll take another look and see if we can get this wrapped up.

**Comment by mikldk** [comment]
r-barnes, can you please give a brief status of your review? This is not to rush you, merely to give me an impression of the progress and time-frame.

**Comment by mikldk** [comment]
@r-barnes, can you please give a brief status of your review? This is not to rush you, merely to give me an impression of the progress and time-frame.

**Comment by mikldk** [comment]
@r-barnes, can you please give a brief status of your review? This is not to rush you, merely to give me an impression of the progress and time-frame.

**Comment by sebkopf** [comment]
Hi @mikldk and @r-barnes - could you give me an update when you get the chance? It has been ~2 months since we addressed the last concerns and I was wondering if there is anything more that we need to do to get this published. I appreciate your time and effort on this publication very much. Best regards

**Comment by mikldk** [comment]
@sebkopf I understand your request for an update - this slipped through my filter, sorry. 

@r-barnes Please finalise your review as soon as possible.

**Comment by r-barnes** [comment]
I hope to have time this weekend or late Friday night :-(

**Comment by r-barnes** [comment]
After working through the software again and reviewing responses to prior comments, I think this is good to go and put my Reviewer's Mark of Approval™ on it. My apologies again for being so late on this.

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02878/joss.02878/10.21105.joss.02878.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02878/joss.02878/10.21105.joss.02878.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@sebkopf:

* Please have a final read though of the paper, checking language etc.
* Have a final check of the proofs with `@whedon generate pdf`
* In general, be sure that all versions are correct and that the repo is in the state that should be published.
* Please make a tagged release and archive (e.g. with [Zenodo](https://zenodo.org/)) as described [here](<https://joss.readthedocs.io/en/latest/submitting.html#the-review-process>), and report the version number and archive DOI in this thread. Please verify that the archive deposit has the correct metadata (title and author list), or edit these if that is not the case.

**Comment by mikldk** [comment]
@sebkopf, can you please give a brief status of the bullets above?

**Comment by sebkopf** [comment]
Hi @mikldk . Got zenodo finally figured out:

The release version is 1.3.0 and the archive DOI is 10.5281/zenodo.4724083:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4724083.svg)](https://doi.org/10.5281/zenodo.4724083)

@whedon generate pdf

**Comment by sebkopf** [comment]
> 👉📄 [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02878/joss.02878/10.21105.joss.02878.pdf) 📄 [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02878/joss.02878/10.21105.joss.02878.pdf) 📄 👈

@mikldk This all looks great, happy to approve this proof. Is there anything else you need me to do? As mentioned above, zenodo DOI is [10.5281/zenodo.4724083](https://zenodo.org/badge/latestdoi/90583005)

**Comment by mikldk** [comment]
@whedon set v1.3.0 as version

**Comment by whedon** [comment]
OK. v1.3.0 is the version.

**Comment by mikldk** [comment]
@whedon set 10.5281/zenodo.4724083 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4724083" target="_blank">10.5281/zenodo.4724083</a> is the archive.

**Comment by mikldk** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/gbi.12312 is OK
- 10.1002/lom3.10300 is OK
- 10.1111/gbi.12386 is OK
- 10.1144/SP507-2020-85 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2266

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2266, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by sebkopf** [comment]
looks great to me, is there something else I need to do @mikldk ? Thanks for helping navigate this process for the first time.

**Comment by Kevin-Mattheus-Moerman** [comment]
@sebkopf I've also proofread the paper and I think all looks good. I will now proceed to accept this submission in JOSS. Congratulations!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1388395498554511360) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2269
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02878](https://doi.org/10.21105/joss.02878)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by Kevin-Mattheus-Moerman** [comment]
Once again congratulations @sebkopf on this accepted paper. 

Thanks @mikldk for editing this work, and thanks @kdorheim, @r-barnes for your review efforts!!!!!!!!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02878/status.svg)](https://doi.org/10.21105/joss.02878)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02878">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02878/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02878/status.svg
   :target: https://doi.org/10.21105/joss.02878
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02878/status.svg)](https://doi.org/10.21105/joss.02878)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
