### ISSUE TITLE
[REVIEW]: A Repository to Simulate the Spread of COVID-19 in any Population with a Known Age-Structure, Made in Tübingen.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2880]
**Submitting author:** @vahid-sb (<a href="http://orcid.org/0000-0001-6544-7960">Vahid S. Bokharaie</a>)
**Repository:** <a href="https://github.com/vahid-sb/MiTepid_sim" target ="_blank">https://github.com/vahid-sb/MiTepid_sim</a>
**Version:** v0.0.5
**Editor:** @majensen
**Reviewer:** @AngryMaciek, @adi3
**Archive:** Pending

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2a0d7b5f8730b915ab938ed4f9dc149a/status.svg)](https://joss.theoj.org/papers/2a0d7b5f8730b915ab938ed4f9dc149a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2a0d7b5f8730b915ab938ed4f9dc149a"><img src="https://joss.theoj.org/papers/2a0d7b5f8730b915ab938ed4f9dc149a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2a0d7b5f8730b915ab938ed4f9dc149a/status.svg)](https://joss.theoj.org/papers/2a0d7b5f8730b915ab938ed4f9dc149a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/vahid-sb/MiTepid_sim" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@AngryMaciek & @adi3, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @majensen know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/vahid-sb/MiTepid_sim">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@vahid-sb) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/vahid-sb/MiTepid_sim">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@vahid-sb) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @AngryMaciek, @adi3 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2020.10.16.20213835 is OK
- 10.1101/2020.04.10.20060681 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02880/joss.02880/10.21105.joss.02880.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02880/joss.02880/10.21105.joss.02880.pdf) :page_facing_up: :point_left:

**Comment by adi3** [comment]
@vahid-sb can you please create a /paper subdirectory in your repo, and put the .bib, .md and .png files in it?

**Comment by vahid-sb** [comment]
@adi3, done!

**Comment by adi3** [comment]
@vahid-sb thank you. As I go through the review checklist, I'll be requesting you to make several changes to your repository. This is to bring the repo and paper in line with JOSS standards. Most of them will be tiny, so please bear with me.

In the Installation section of your readme, you state "Or you can install it directly from the repository." Please provide the commands (starting from git clone...) in the readme for the user to the do this install from source.

**Comment by vahid-sb** [comment]
Dear @adi3, I removed that sentence altogether since it has nothing to do with Mitepid_sim in particular and I do not want to turn the documentation into a resource for teaching the basics of python. And I am happy to make any changes that make the repo better and would be grateful for any such suggestion from you or anybody else, but I'd be also grateful if you'd be kind enough to tell me all such tiny changes in one batch rather than one by one.

**Comment by adi3** [comment]
@vahid-sb Thank you for making the change. I'm afraid it is not possible for me to give you all the required changes in one batch. The process of reviewing is iterative and as I go through the checklist, some things are interrelated so we have to approach them in discrete steps. We are not aiming for an easy publication process here, but a high standard one.

Now, going through your paper, I see a major revision necessary. Your Summary section needs to be "a clear description of the high-level functionality and purpose of the software". Instead, your current Summary provides a background of the field and the problem. Of course, some background information is necessary to include, in order to set up the context. So perhaps you can remove the explanation of what SEIR/SIS models are. I see that a bunch of the content you need for the Summary section can be extracted from your current Statement of Need section, in particular, the places where you describe what the software does.

I hope this gives you some direction. Please let me know if I clarify anything further.

Lastly, what exactly is "Made in Tuebingen"? The way it is used in your sentences currently does not make sense to me.

**Comment by whedon** [comment]
:wave: @AngryMaciek, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @adi3, please update us on how your review is going.

**Comment by vahid-sb** [comment]
Dear @AngryMaciek and @adi3, I have seen your constructive comments, and I plan to make the necessary changes but I am busy with ongoing commitments and deadlines and very unlikely that I can come back to you in December. I am not sure if there is a time limit for the review process. My plan is to address the raised issues in the first half of January. Dear @majensen, please advise if this is fine with you and the editorial board.

**Comment by adi3** [comment]
@majensen suggest pausing the review till @vahid-sb is ready with his changes.

**Comment by majensen** [comment]
@adi3 thanks for the suggestion. Right now, I think we can leave the review open-  @vahid-sb, this is of course common for all of us especially at the year end. I appreciate your setting the expectations; a January timeframe is great.

(I sort of reserve pauses when an author has to drop the work for an indeterminate period. The problem with the "paused" flag is that it causes me to exclude the paper from my already tiny attention span!)

**Comment by vahid-sb** [comment]
@majensen @adi3 @AngryMaciek Thanks again to you all. I'd come back to you as soon as I can, as I said my plan is the first half of January.

**Comment by majensen** [comment]
@vahid-sb checking in - how are thing going?

**Comment by vahid-sb** [comment]
@majensen, haven't managed to find time to do all the changes I plan to do. It is on my mind, only a matter of finding enough time. I will come back to you and reviewers as soon as my responses are ready and changes done. Thanks for your patience.

**Comment by majensen** [comment]
@vahid-sb thanks for checking in - no problem

**Comment by majensen** [comment]
@vahid-sb any progress? Maybe we should take @adi3 's  suggestion and pause this review? Let us know.

**Comment by vahid-sb** [comment]
Dear @majensen, to be realistic, it is very unlikely that I can make the required changes in Feb or Mar. So, if this case being open is causing issues, maybe we can pause it and I'd get back to you when I can. The changes I plan to make are major, hence I should find time to focus on them properly, which unfortunately seems to be not possible these days.

**Comment by majensen** [comment]
Thanks @vahid-sb - we will put the review on pause and we can pick it back up when you can.

**Comment by majensen** [comment]
Hi @vahid-sb - I just wanted to check in and see if you want to restart this review. Hope everything is going well.

**Comment by vahid-sb** [comment]
Hi @majensen, thanks for your message and I hope life is treating you well. I used this library to do a study whose results I have already published. The paper itself took a lot of mental energy, in particular since I had to do it all alone. And although afterwards, I tried to force myself into editing this library, I couldn't find the required mental energy. And given what is going on in my professional life right now, I find it very unlikely that I can do the required editing for this library any time soon. Hence, I think it is better to withdraw this submission. I thank you and the reviewers for your time and comments. And please let me know what should I do to formally withdraw the review request.

**Comment by majensen** [comment]
Thanks for your response, @vahid-sb. I've been there. I appreciate your submission and the contributions of @AngryMaciek and @adi3. Feel free to resubmit the paper if and when you are ready to do so; recommend me as editor.

**Comment by majensen** [comment]
@whedon withdraw

**Comment by whedon** [comment]
I'm sorry @majensen, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by majensen** [comment]
@openjournals/jose-eics - @vahid-sb has requested that this submission be withdrawn. Thanks for your attention to this.

**Comment by labarba** [comment]
@openjournals/joss-editors

**Comment by kthyng** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
