### ISSUE TITLE
[PRE REVIEW]: EMD: Empirical Mode Decomposition and Hilbert-Huang Spectral Analyses in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2881]
**Submitting author:** @ajquinn (<a href="http://orcid.org/0000-0003-2267-9897">Andrew Quinn</a>)
**Repository:** <a href="https://gitlab.com/emd-dev/emd" target ="_blank">https://gitlab.com/emd-dev/emd</a>
**Version:** v0.3.2
**Editor:** @dpsanders
**Reviewers:** @JanCBrammer, @EtienneCmb, @neurofractal
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ajquinn. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arokem.

@ajquinn if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1098/rspa.1998.0193 is OK
- 10.1109/icassp.2005.1416051 is OK
- 10.1142/s1793536909000096 is OK
- 10.1142/s1793536909000047 is OK
- 10.1098/rsta.2015.0206 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2881 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Anna Nobre, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (402.3 files/s, 81312.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          27           1681           3098           3009
Markdown                         4             82              0            284
reStructuredText                 5             78             45            132
YAML                             5              5              2             84
Jupyter Notebook                10              0           2570             75
TeX                              1              5              0             66
HTML                             2              5              0             41
make                             1             12              4             32
CSS                              1              3              0              7
-------------------------------------------------------------------------------
SUM:                            56           1871           5719           3730
-------------------------------------------------------------------------------


Statistical information for the repository 'e953d74a1167bf90067bb8c3' was
gathered on 2020/12/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrew Quinn                   265         12683           4930           97.37
Andrew Quinn BDNU                6            26             10            0.20
AndrewQuinn                      3           361             34            2.18
Mark Hymers                      3            25             11            0.20
ajquinn                          3             6              2            0.04

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrew Quinn               7778           61.3          9.7               23.40
Mark Hymers                   9           36.0         10.8                0.00
ajquinn                       1           16.7         32.4                0.00
```

**Comment by kyleniemeyer** [comment]
Hi @dpsanders, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @dpsanders as editor

**Comment by whedon** [comment]
@dpsanders has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hi @AJQuinn, thanks for your interest in JOSS. We start out by finding an editor and reviewers in this pre-review issue.

It looks like your paper has an issue in one of the author affiliations, for Anna Christina Nobre. Could you replace `affiliation: 1,3` with `affiliation: "1, 3"`? Thanks!

**Comment by dpsanders** [comment]
@kyleniemeyer Yes, sure.

**Comment by dpsanders** [comment]
@whedon assign @dpsanders as editor

**Comment by whedon** [comment]
OK, the editor is @dpsanders

**Comment by AJQuinn** [comment]
Hello - Thank you all for your time with our paper. I'll take a look at the reviewer list and make some suggestions. I've also fixed the affiliation issue in a branch and will try to recompile.

Please let me know if there is anything else I can do

**Comment by AJQuinn** [comment]
@whedon generate pdf from branch 33-joss-revisions

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 33-joss-revisions. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02881/joss.02881/10.21105.joss.02881.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02881/joss.02881/10.21105.joss.02881.pdf) :page_facing_up: :point_left:

**Comment by AJQuinn** [comment]
Hello again - some reviewer suggestions from the list in case it is helpful, happy to take a closer look through the list if needeed.

sappelhoff
alexrockhill
john-s-butler-dit
JanCBrammer  

Cheers

**Comment by dpsanders** [comment]
👋  @AJQuinn: Thanks for your submission to JOSS, and apologies for the delay.

In general the submission looks good!

Here's a couple of initial remark:
- The JOSS paper is missing a "Statement of Need" section, which is a [JOSS requirement](https://joss.readthedocs.io/en/latest/submitting.html).

- On a related note: You refer to other packages that implement EMD, but it is not clear how your package differs from them or why a new package is needed. 

Could you please clarify the above points in the paper? Thanks!

**Comment by dpsanders** [comment]
👋 Hi @john-s-butler-dit and @jancbrammer: Would you be available to review this submission for JOSS? Thanks!

**Comment by JanCBrammer** [comment]
@dpsanders, sure! I expect to be able to review the repository next week (calendar week 1).

**Comment by AJQuinn** [comment]
Hello - thanks all for your time with our paper!

@dpsanders - thanks for the first comments. I've made some changes in a branch and will recompile the paper below. I've reworked the summary to make the statement of need section more explicit (I'd intended the summary to cover the SofN but didn't realise it needed a separate section..) and added some specifics on how our package goes beyond others in the field. 

Please let me know if I can add anything else.

Cheers

**Comment by AJQuinn** [comment]
@whedon generate pdf from branch 33-joss-revisions

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 33-joss-revisions. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02881/joss.02881/10.21105.joss.02881.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02881/joss.02881/10.21105.joss.02881.pdf) :page_facing_up: :point_left:

**Comment by AJQuinn** [comment]
Hello, I've taken another look through the list of potential reviewers in case it is useful. The following people looks like they have relevant experience:
neurofractal
EtienneCmb
saran-nns

I hope this is helpful - please let me know if I should do anything else with this or in the manuscript itself. Thanks for your time with our paper!

Cheers

**Comment by dpsanders** [comment]
Thanks @AJQuinn and apologies for the delay.

**Comment by dpsanders** [comment]
👋 @neurofractal and @EtienneCmb: Would you be able to review this submission for JOSS? Thanks!

**Comment by EtienneCmb** [comment]
Hi @dpsanders, yes I'm able to review this submission. It's going to be my first review for JOSS. I already know this package and I'm considering using it on my data so I would be happy to help

**Comment by neurofractal** [comment]
Hey @dpsanders. Happy to review this - looks interesting. Are there any guidelines for how to review for JOSS?

**Comment by dpsanders** [comment]
@whedon add @JanCBrammer as reviewer

**Comment by whedon** [comment]
OK, @JanCBrammer is now a reviewer

**Comment by dpsanders** [comment]
@whedon add @EtienneCmb as reviewer

**Comment by whedon** [comment]
OK, @EtienneCmb is now a reviewer

**Comment by dpsanders** [comment]
@whedon add @neurofractal as reviewer

**Comment by whedon** [comment]
OK, @neurofractal is now a reviewer

**Comment by dpsanders** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2977.

**Comment by dpsanders** [comment]
👋 @JanCBrammer, @EtienneCmb and @neurofractal: Thank you very much for agreeing to review this submission.

Please follow your personalised checklist in the review issue that has just been opened. 

The JOSS submission guidelines are [here](https://joss.readthedocs.io/en/latest/submitting.html), and the reviewer guidelines are [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

Please let me know if you have any queries during the process. Thanks again!
