### ISSUE TITLE
[PRE REVIEW]: Magicwand: A platform to provide high-quality, reliable, and reproducible data sets for low-and-slow DDoS attacks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2882]
**Submitting author:** @ctodd26labs (<a href="http://orcid.org/0000-0003-1453-265X">Christopher Todd</a>)
**Repository:** <a href="https://github.com/twosixlabs/magicwand-datatool" target ="_blank">https://github.com/twosixlabs/magicwand-datatool</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @nidhog
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ctodd26labs. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @usethedata.

@ctodd26labs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (595.1 files/s, 47960.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          47            944           2339           2185
Markdown                        15            626              0           1468
YAML                            12             11              2            182
JSON                            21              1              0             79
TeX                              1              7              0             70
make                             1             23             23             36
Bourne Shell                     1             12              0             24
TOML                             1              1              1             21
INI                              1              0              0              4
-------------------------------------------------------------------------------
SUM:                           100           1625           2365           4069
-------------------------------------------------------------------------------


Statistical information for the repository 'cac81696238fa51e1358e4d6' was
gathered on 2020/12/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Banjo                            1             1              1            0.04
Christopher.H.Todd               1          5427              0           99.96

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Banjo                         2          200.0          0.0                0.00
Christopher.H.Todd         5426          100.0          0.0               13.53
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02882/joss.02882/10.21105.joss.02882.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02882/joss.02882/10.21105.joss.02882.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @usethedata, the authors suggested you as editor for this submission. Interested in editing this one?

**Comment by kyleniemeyer** [comment]
@whedon invite @usethedata as editor

**Comment by whedon** [comment]
@usethedata has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@usethedata can you handle this submission?

**Comment by usethedata** [comment]
Sorry. This week blew up on me with the American Geophysical Union meeting and a family member ER trip.  It will be the weekend before I can start on this.

**Comment by usethedata** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by ctodd26labs** [comment]
Hello everyone, happy holidays.

I figured that people are probably busy and taking off, but I wanted to check to see if there has been any movement on this request or if there is anything necessary on our end.

Thank you and have a good day.

**Comment by ctodd26labs** [comment]
Hello everyone

Wanted to follow up again with everyone. Is there anything we need to help move this along at this point? 

Again, thank you for all f your help on this.

**Comment by usethedata** [comment]
@kyleniemeyer -- Per the discussion with the editors in chief, I believe the intent was to assign someone else to edit this paper, given the challenges in my world.

@ctodd26labs -- My apologies for the lack of action here.  For a variety of personal and job-related reasons, I've not had the bandwidth to work on JOSS things and am stepping away from being a topic editor.

**Comment by ctodd26labs** [comment]
@usethedata thank you for your help on this and the update. Also, good luck with everything you are dealing with.

@kyleniemeyer please let me know if there is anything I can do to help with the process.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@ctodd26labs - apologies for the delay here in getting this submission moving. 

Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission? (Please list their GitHub handles without a `@` when listing them here so as avoid accidentally pinging a bunch of people).

**Comment by ctodd26labs** [comment]
Hello @arfon thanks for responding. I took a look through the reviewers file you sent, here are 5 I think fit the bill.

Possible Reviewers:
    - fabianomenegidio
    - kellieotto
    - dvysardana
    - Suman-d
    - nidhog

I tried to find people who have
    - Python
    - Docker
    - data science/data engineering

Thanks for your help; please let me know if there is anything more needed from me. I can always respond here or hop on a call to talk through anything if there are questions.

Have a great day.

**Comment by arfon** [comment]
👋 @nidhog @fabianomenegidio @dvysardana - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration is a Python package: [_Magicwand: A platform to provide high-quality, reliable, and reproducible data sets for low-and-slow DDoS attacks_](https://github.com/twosixlabs/magicwand-datatool).

**Comment by ctodd26labs** [comment]
Hello,

Wanted to follow-up to see if there has been any movement with this?

Thank you in advance and have a good day.

**Comment by fabianomenegidio** [comment]
Sorry. I'm away assisting in the assembly of the genome of the
Brazilian strain of SARS-CoV-2.

I will not be able to revise the article.


Em qua, 3 de fev de 2021 13:40, Christopher H. Todd <
notifications@github.com> escreveu:

**Comment by arfon** [comment]
> Wanted to follow-up to see if there has been any movement with this?

@ctodd26labs not yet sorry. I'm still on the hunt for reviewers.

**Comment by arfon** [comment]
:wave: @ajoer & @Suman-d would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration is a Python package: [_Magicwand: A platform to provide high-quality, reliable, and reproducible data sets for low-and-slow DDoS attacks_](https://github.com/twosixlabs/magicwand-datatool).

**Comment by nidhog** [comment]
@arfon sorry for taking too long to respond (side effect of not having notifications 😅 🙏 ) 
would happily review it at some time within the next 3 weeks to be realistic, if this scope is ok let me know 😉 👌

**Comment by arfon** [comment]
That's great, thank you @nidhog! I'll go ahead and add you to the review now - sometime in the next 3 weeks would be great!

**Comment by arfon** [comment]
@whedon add @nidhog as reviewer

**Comment by whedon** [comment]
OK, @nidhog is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3032.

**Comment by arfon** [comment]
@nidhog - please head over to #3032 where the actual review will take place. @ctodd26labs - I'm going to keep looking for a second reviewer while @nidhog gets started.

**Comment by arfon** [comment]
:wave: @satybald and @ajoer - would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration is a Python package: [_Magicwand: A platform to provide high-quality, reliable, and reproducible data sets for low-and-slow DDoS attacks_](https://github.com/twosixlabs/magicwand-datatool).

**Comment by ctodd26labs** [comment]
Hello @arfon, 

I got the update today from this thread and I have not seen any updates on https://github.com/openjournals/joss-reviews/issues/3032 in ~16 days. Is there anything needed from me or are we choosing a new reviewer for the paper?

I appreciate you keeping an eye on it and updating the ticket.

**Comment by arfon** [comment]
> I got the update today from this thread and I have not seen any updates on #3032 in ~16 days. Is there anything needed from me or are we choosing a new reviewer for the paper?

Let's sit tight for now. My comment earlier today was to try and find a second reviewer to go along with the one we already have (JOSS has a minimum of two reviewers per submission)
