### ISSUE TITLE
[PRE REVIEW]: LinRegOutliers: A Julia package for detecting outliers in linear regression

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2884]
**Submitting author:** @jbytecode (<a href="http://orcid.org/0000-0002-9402-1982">Mehmet Hakan Satman</a>)
**Repository:** <a href="https://github.com/jbytecode/LinRegOutliers" target ="_blank">https://github.com/jbytecode/LinRegOutliers</a>
**Version:** v0.8.3
**Editor:** @mikldk
**Reviewers:** @salleuska, @rMassimiliano
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jbytecode. **Currently, there isn't an JOSS editor assigned** to your paper.

@jbytecode if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (706.6 files/s, 107454.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           37            992            335           4715
TOML                             4            224              2           1003
Markdown                        11            171              0            534
TeX                              1             83              0            379
YAML                             3              8              1             69
-------------------------------------------------------------------------------
SUM:                            56           1478            338           6700
-------------------------------------------------------------------------------


Statistical information for the repository '3f7eb2db9813fc214ef3f8be' was
gathered on 2020/12/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
jbytecode                        3           552           1104          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by kyleniemeyer** [comment]
Hi @mikldk, are you able to edit this submission for us?

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02884/joss.02884/10.21105.joss.02884.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02884/joss.02884/10.21105.joss.02884.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/01621459.1993.10476407 is OK
- 10.1080/01621459.1994.10476872 is OK
- 10.1080/03610929708831988 is OK
- 10.1016/s0167-9473(98)00021-8 is OK
- 10.1080/02664760500163599 is OK
- 10.1080/01966324.2006.10737673 is OK
- 10.1109/ACC.2009.5160229 is OK
- 10.1080/01621459.1984.10477105 is OK
- 10.1007/978-3-642-58250-9_27 is OK
- 10.1080/00401706.1999.10485670 is OK
- 10.14419/ijasp.v3i1.4439 is OK
- 10.1007/s11590-020-01565-4 is OK
- 10.2307/1268249 is OK
- 10.1080/03610918.2011.598989 is OK

MISSING DOIs

- 10.1137/141000671 may be a valid DOI for title: Julia: A fresh approach to numerical computing

INVALID DOIs

- https://doi.org/10.1016/B978-0-08-051581-6.50070-2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.2307/2531498 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1111/j.2517-6161.1992.tb01449.x is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1111/j.2517-6161.1994.tb01988.x is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1111/j.2517-6161.1995.tb02051.x is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0167-9473(99)00101-2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0167-9473(02)00291-8 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0167-9473(99)00029-8 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/wics.19 is INVALID because of 'https://doi.org/' prefix
- 10.5539/ijsp.v2n3p101 is INVALID
```

**Comment by kyleniemeyer** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hello @jbytecode, thanks for your interest in JOSS. We will use this pre-review issue to identify an editor and reviewers. While doing that, could you fix those issues related to DOIs in the paper? I think you just need to remove `https://doi.org/` at the beginning and just include the DOI itself in the `.bib` file.

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "author" (NAME) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:title=>["Julia: A fresh approach to numerical computing"], :doi=>["10.1137/141000671"]}]

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-0-08-051581-6.50070-2 is OK
- 10.1137/141000671 is OK
- 10.2307/2531498 is OK
- 10.1111/j.2517-6161.1992.tb01449.x is OK
- 10.1080/01621459.1993.10476407 is OK
- 10.1080/01621459.1994.10476872 is OK
- 10.1111/j.2517-6161.1994.tb01988.x is OK
- 10.1111/j.2517-6161.1995.tb02051.x is OK
- 10.1080/03610929708831988 is OK
- 10.1016/s0167-9473(98)00021-8 is OK
- 10.1016/S0167-9473(99)00101-2 is OK
- 10.1016/S0167-9473(02)00291-8 is OK
- 10.1080/02664760500163599 is OK
- 10.1080/01966324.2006.10737673 is OK
- 10.1109/ACC.2009.5160229 is OK
- 10.1016/S0167-9473(99)00029-8 is OK
- 10.1080/01621459.1984.10477105 is OK
- 10.1007/978-3-642-58250-9_27 is OK
- 10.1002/wics.19 is OK
- 10.1080/00401706.1999.10485670 is OK
- 10.5539/ijsp.v2n3p101 is OK
- 10.14419/ijasp.v3i1.4439 is OK
- 10.1007/s11590-020-01565-4 is OK
- 10.2307/1268249 is OK
- 10.1080/03610918.2011.598989 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
Dear editor @kyleniemeyer , it seems now it is okay. Thank you.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@jbytecode Do you have any reviewer suggestions?

**Comment by jbytecode** [comment]
Dear editor @mikldk ,

There is not a referee that I can specifically recommend in the list but rMassimiliano, salleuska, OmarShehata, gagolews, brunaw, degleris1, and, daviddewhurst have keywords Julia and Statistics in their preferred language and interest sections. They are listed on the bottom of the list.

**Comment by mikldk** [comment]
@salleuska, @rMassimiliano: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by salleuska** [comment]
Hi @mikldk sorry for the late reply, I missed the github notification. Sure I'll be happy to review this submission.

**Comment by rMassimiliano** [comment]
Hi @mikldk, I would also be happy to review the submission!

**Comment by mikldk** [comment]
That's great, @salleuska and @rMassimiliano - thanks.

**Comment by mikldk** [comment]
@whedon add @salleuska as reviewer

**Comment by whedon** [comment]
OK, @salleuska is now a reviewer

**Comment by mikldk** [comment]
@whedon add @rMassimiliano as reviewer

**Comment by whedon** [comment]
OK, @rMassimiliano is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2892.
