### ISSUE TITLE
[PRE REVIEW]: Easy3D: a lightweight, easy-to-use, and efficient C++ library for processing and rendering 3D data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2885]
**Submitting author:** @LiangliangNan (<a href="http://orcid.org/0000-0002-5629-9975">Liangliang Nan</a>)
**Repository:** <a href="https://github.com/LiangliangNan/Easy3D" target ="_blank">https://github.com/LiangliangNan/Easy3D</a>
**Version:** v2.4.1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @adi3, @vissarion,  @bhajay
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @LiangliangNan. **Currently, there isn't an JOSS editor assigned** to your paper.

@LiangliangNan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2885 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=4.12 s (362.5 files/s, 150740.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   814          41395          61319         196228
C++                            356          25349          28630         161025
C                               47           8117           7130          61128
Qt                              20              0              0           6891
GLSL                           108           1494           1206           6251
CMake                           91            965            587           3331
Objective-C                      5            697            337           2901
Markdown                        17            567              0           1749
m4                              13            106             50            911
HTML                             1            122             20            489
Bourne Shell                     8             81            205            309
make                             4            100            174            280
XML                              3              9              1            230
YAML                             3             20             23            172
Starlark                         1             15             75            112
CSS                              1             11             12             92
Bazel                            1              1              0              9
-------------------------------------------------------------------------------
SUM:                          1493          79049          99769         442108
-------------------------------------------------------------------------------


Statistical information for the repository '7682a458b988d34bd252d1e9' was
gathered on 2020/12/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Chunmei                          5            49             27            0.00
Daniel Feist                     1             3              3            0.00
Kelvin                           1             7              1            0.00
Liangliang Nan                1190       1066911         525202           99.77
LiangliangNan                   12          1554           1543            0.19
liangliang                      16           302            259            0.04
liangliang.nan                   1             1              0            0.00
tonghao.yuan                     1             1              0            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chunmei                       1            2.0          9.6                0.00
Daniel Feist                  2           66.7         13.6                0.00
Liangliang Nan           541418           50.7         10.1               18.03
tonghao.yuan                  1          100.0          7.7                0.00
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
Hi @jni, would you be interested in editing this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @jni as editor

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02885/joss.02885/10.21105.joss.02885.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02885/joss.02885/10.21105.joss.02885.pdf) :page_facing_up: :point_left:

**Comment by jni** [comment]
Hello @kyleniemeyer! Unfortunately I have very limited bandwidth before Christmas, and am struggling to keep up with the reviews I have currently assigned, so I must decline.

**Comment by kyleniemeyer** [comment]
@jni understood, that's ok

**Comment by kyleniemeyer** [comment]
Hi @leouieda, could you edit this one?

**Comment by kyleniemeyer** [comment]
@whedon invite @leouieda as editor

**Comment by whedon** [comment]
@leouieda has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer I can take this one

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@hugoledoux would you be interested in reviewing this work?

**Comment by hugoledoux** [comment]
I would yes, but major conflict of interest here: Liangliang's desk is 4m from mine (in normal times!).

**Comment by Kevin-Mattheus-Moerman** [comment]
@hugoledoux ah right. Okay thanks for letting me know. Can you and @LiangliangNan help suggest any reviewers?

**Comment by Kevin-Mattheus-Moerman** [comment]
@avaxman @sgsellan @mlivesu @ataber would you be interested in reviewing this work for [JOSS](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) focuses on [the software](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02885/joss.02885/10.21105.joss.02885.pdf). If you are interested you can comment here. Thanks! 

Note, this is a so-called "Pre-review issue" where reviewers/editors are assigned. Once I've attracted sufficient reviewers I'll trigger a "Review issue" where the review will take place.

**Comment by mlivesu** [comment]
@Kevin-Mattheus-Moerman, sorry but this is a period of many deadlines for me. I cannot take this one.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mlivesu that is fine. We are getting this type of response from nearly all reviewers at this time. Completely understandable if course. I'd like to point out though that we can be really flexible and if you think you can join/pick this up in January for instance that is fine. So if you are interested in principle, but too busy now, I could add you now if you like and we can wait and be flexible to receive your review. Thanks either way.

**Comment by mlivesu** [comment]
I'll be completely swamped until the end of January/beginning of February, then it'll be time for some well deserved rest :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@avaxman @sgsellan @ataber are you able to help review this submission  for [JOSS](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) focuses on [the software](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02885/joss.02885/10.21105.joss.02885.pdf). If you are interested you can comment here. Thanks! 

Note, this is a so-called "Pre-review issue" where reviewers/editors are assigned. Once I've attracted sufficient reviewers I'll trigger a "Review issue" where the review will take place.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mlivesu thanks, that is okay. I take it your schedule still does not allow you to help with this work but if you change your mind let us know.  Best wishes for 2021.

**Comment by Kevin-Mattheus-Moerman** [comment]
@avaxman @sgsellan @ataber are you able to help review this submission  for [JOSS](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) focuses on [the software](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02885/joss.02885/10.21105.joss.02885.pdf). If you are interested you can comment here. Thanks! 

Note, this is a so-called "Pre-review issue" where reviewers/editors are assigned. Once I've attracted sufficient reviewers I'll trigger a "Review issue" where the review will take place.

**Comment by Kevin-Mattheus-Moerman** [comment]
@hugoledoux @LiangliangNan it has been challenging to find reviewers here. Can you help suggest some reviewers? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@mlivesu thanks for your responses earlier. Here is one last attempt from me to try to recruit you as a reviewer. We are still looking for reviewers and I can add that we can be extremely flexible regarding review time to give you the time you need. Given this, would you reconsider? If you cant that is understandable of course.

**Comment by bhajay** [comment]
@Kevin-Mattheus-Moerman : Are you still looking for a reviewer?

**Comment by LiangliangNan** [comment]
> @hugoledoux @LiangliangNan it has been challenging to find reviewers here. Can you help suggest some reviewers? Thanks

Maybe "clemaitre58",  "nnadeau", "jizecn", "RealPolitiX", "jcarpent", "amitkumarj441" from the [existing reviewer list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822). Just found their domains are similar to mine.

**Comment by Kevin-Mattheus-Moerman** [comment]
> @Kevin-Mattheus-Moerman : Are you still looking for a reviewer?

@bhajay yes. Are you interested in helping?

**Comment by bhajay** [comment]
@Kevin-Mattheus-Moerman 

> > @Kevin-Mattheus-Moerman : Are you still looking for a reviewer?
> 
> @bhajay yes. Are you interested in helping?

@Kevin-Mattheus-Moerman : Yes, surely.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @bhajay as reviewer

**Comment by whedon** [comment]
OK, @bhajay is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@gpeyre, @jizecn, @RealPolitiX, @jcarpent, @jni, @SimonDanisch, @bryevdv, @jsignell, @afabri, @janetournois, @MoniqueTeillaud, are you able to help review this submission  for [JOSS](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) focuses on [the software](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02885/joss.02885/10.21105.joss.02885.pdf). If you are interested you can comment here. Thanks! 

Note, given the global COVID19 pandemic we can be very flexible in terms of review times.

Note, this is a so-called "Pre-review issue" where reviewers/editors are assigned. Once I've attracted sufficient reviewers I'll trigger a "Review issue" where the review will take place.

**Comment by adi3** [comment]
@Kevin-Mattheus-Moerman feel free to put me down as a reviewer if you can't find another. This topic is up my alley.

**Comment by MoniqueTeillaud** [comment]
Dear [ https://github.com/Kevin-Mattheus-Moerman | @Kevin-Mattheus-Moerman ] 

Just a short email to decline your invitation, as the submission does not fall in my precise area of research. 

It could help to ask some other CGAL developers 
[ https://github.com/CGAL/ | https://www.cgal.org/people.html ] [ https://github.com/CGAL/ ] 
[ https://github.com/CGAL/ | https://github.com/CGAL/ ] 
[ https://www.cgal.org/people.html ] 
Best regards, 
-- 
Monique Teillaud 
https://members.loria.fr/Monique.Teillaud/ 
INRIA Nancy - Grand Est, LORIA 
Institut National de Recherche en Informatique et Automatique

**Comment by RealPolitiX** [comment]
Dear [ https://github.com/Kevin-Mattheus-Moerman | @Kevin-Mattheus-Moerman
],

Thanks for the invitation, I'm unfortunately not working explicitly in this
area, so I decline the invitation.

Cheers

R. Patrick Xian

**Comment by Kevin-Mattheus-Moerman** [comment]
@vissarion would you be able to help as reviewer here?

**Comment by vissarion** [comment]
> @vissarion would you be able to help as reviewer here?

@Kevin-Mattheus-Moerman thanks for asking. This is not exactly my area of expertise but it is close. Moreover, I have some load in both editing and reviewing for joss right now. However, I will be happy to review it if a more relevant to the topic reviewer will not show up.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ranahanocka are you able to help review this submission  for [JOSS](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) focuses on [the software](https://github.com/LiangliangNan/Easy3D) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02885/joss.02885/10.21105.joss.02885.pdf). If you are interested you can comment here. Thanks! 

Note, given the global COVID19 pandemic we can be very flexible in terms of review times.

Note, this is a so-called "Pre-review issue" where reviewers/editors are assigned. Once I've attracted sufficient reviewers I'll trigger a "Review issue" where the review will take place.

**Comment by Kevin-Mattheus-Moerman** [comment]
@keenancrane @nmwsharp @ranahanocka @dcoeurjo @MarkGillespie @ctlee @rohan-sawhney are you able to help review this submission  for [JOSS](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) focuses on [the software](https://github.com/LiangliangNan/Easy3D) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02885/joss.02885/10.21105.joss.02885.pdf). If you are interested you can comment here. Thanks! 

Note, given the global COVID19 pandemic **we can be very flexible in terms of review times**.

Note, this is a so-called "Pre-review issue" where reviewers/editors are assigned. Once I've attracted sufficient reviewers I'll trigger a "Review issue" where the review will take place.

**Comment by adi3** [comment]
@Kevin-Mattheus-Moerman Did you see my message up above offering to review this?

**Comment by Kevin-Mattheus-Moerman** [comment]
@adi3, sorry that slipped through the net. Thanks,  that is great, I'll add you as a reviewer since you are interested. I will hopefully recruit two more reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @adi3 as reviewer

**Comment by whedon** [comment]
OK, @adi3 is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@vissarion I'm having some difficulty finding reviewers. Would you be okay with being added for this one?

**Comment by Kevin-Mattheus-Moerman** [comment]
@keenancrane @nmwsharp @ranahanocka @dcoeurjo @MarkGillespie @ctlee @rohan-sawhney are you able to help review this submission  for [JOSS](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) focuses on [the software](https://github.com/LiangliangNan/Easy3D) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02885/joss.02885/10.21105.joss.02885.pdf). If you are interested you can comment here. Thanks! 

Note, given the global COVID19 pandemic **we can be very flexible in terms of review times**.

Note, this is a so-called "Pre-review issue" where reviewers/editors are assigned. Once I've attracted sufficient reviewers I'll trigger a "Review issue" where the review will take place.

**Comment by vissarion** [comment]
> @vissarion I'm having some difficulty finding reviewers. Would you be okay with being added for this one?

Sure, happy to help. Most probably I should find time in the next month.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @vissarion as reviewer

**Comment by whedon** [comment]
OK, @vissarion is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add  @bhajay as reviewer

**Comment by whedon** [comment]
OK,  @bhajay is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3255.
