### ISSUE TITLE
[PRE REVIEW]: mikropml: User-Friendly R Package for Supervised Machine Learning Pipelines

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2886]
**Submitting author:** @pschloss (<a href="http://orcid.org/0000-0002-6935-4275">Patrick D Schloss</a>)
**Repository:** <a href="https://github.com/SchlossLab/mikropml" target ="_blank">https://github.com/SchlossLab/mikropml</a>
**Version:** v0.0.1
**Editor:** @arfon
**Reviewers:** @JonnyTran, @FedericoComoglio
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pschloss. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @karthik.

@pschloss if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.37 s (432.9 files/s, 106655.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            98           4620           1233          25613
R                               31            236           1161           2912
Markdown                         8            131              0            465
TeX                              1             40              0            454
CSS                              4             99             49            431
JavaScript                       6             69             42            301
Rmd                              6            343            995            299
YAML                             6             25              0            258
XML                              1              0              0            123
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                           162           5563           3481          30867
-------------------------------------------------------------------------------


Statistical information for the repository 'f7b754863a0ef03daf075ca5' was
gathered on 2020/12/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kelly Sovacool                   6           893              0           85.62
github-actions[bot]              7           150              0           14.38

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kelly Sovacool              541           60.6          0.4               11.28
github-actions[bot]          75           50.0          1.4               20.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02886/joss.02886/10.21105.joss.02886.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02886/joss.02886/10.21105.joss.02886.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02886/joss.02886/10.21105.joss.02886.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02886/joss.02886/10.21105.joss.02886.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @csoneson, would you be interested in editing this one?

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1023/A:1010933404324 is OK
- 10.1038/s41591-020-1101-3 is OK
- 10.18637/jss.v033.i01 is OK
- 10.1093/bioinformatics/btv153 is OK
- 10.1128/mBio.01680-20 is OK
- 10.18637/jss.v011.i09 is OK
- 10.1093/bioinformatics/bts480 is OK
- 10.18637/jss.v028.i05 is OK
- 10.1101/2020.07.06.20147306 is OK
- 10.1371/journal.pcbi.1004977 is OK
- 10.1016/S2589-7500(19)30112-8 is OK
- 10.1093/jamia/ocaa139 is OK
- 10.1038/s41563-018-0241-z is OK
- 10.1128/mBio.00434-20 is OK
- 10.1007/978-3-319-24277-4 is OK
- 10.32614/RJ-2011-002 is OK
- 10.21105/joss.01686 is OK
- 10.1038/s41591-019-0548-6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by kakiac** [comment]
@kyleniemeyer I have some capacity and would be happy to be assigned as the editor for this submission 😄

**Comment by kakiac** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kakiac

**Comment by kyleniemeyer** [comment]
@kakiac sure! Never a problem when someone volunteers to edit!

**Comment by arfon** [comment]
:wave: @kakiac - happy new year! Just a friendly reminder that this submission is still waiting for reviewers to be assigned.

**Comment by arfon** [comment]
@pschloss - could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by pschloss** [comment]
@skummerf 
@Tgerke
@paulgovan
@steffilazerte
@noamross
@darokun
@ja-thomas
@hope-data-science

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@pschloss - apologies for the delay here. As @kakiac is less available to edit than expected, I'll take over from here.

**Comment by arfon** [comment]
:wave: @JonnyTran @FedericoComoglio @JDRomano2 – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission we'd ask you to review here is [_mikropml: User-Friendly R Package for Supervised Machine Learning Pipelines_](https://github.com/SchlossLab/mikropml)

**Comment by JonnyTran** [comment]
Hi @arfon yes I'd gladly review this package.

**Comment by arfon** [comment]
@whedon add @JonnyTran as reviewer

**Comment by whedon** [comment]
OK, @JonnyTran is now a reviewer

**Comment by arfon** [comment]
Great, thanks @JonnyTran! I'll wait a few more days to find a second reviewer before opening up the main review issue.

**Comment by FedericoComoglio** [comment]
Hi @arfon, I will be happy to help. This would be my first review for JOSS - I will make sure to read the guidelines in the meantime.

**Comment by arfon** [comment]
@whedon add @FedericoComoglio as reviewer

**Comment by whedon** [comment]
OK, @FedericoComoglio is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3073.

**Comment by arfon** [comment]
@JonnyTran, @FedericoComoglio - thanks for agreeing to review this submission! See you over in #3073 where the actual review will take place.
