### ISSUE TITLE
[PRE REVIEW]: Learning Simulator: A simulation software for animal and human learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2887]
**Submitting author:** @markusrobertjonsson (<a href="http://orcid.org/0000-0003-1242-3599">Markus Jonsson</a>)
**Repository:** <a href="https://github.com/learningsimulator/learningsimulator" target ="_blank">https://github.com/learningsimulator/learningsimulator</a>
**Version:** 1.0.0
**Editor:** @oliviaguest
**Reviewers:** @themkar, @CatarauCorina, @jkbye
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @markusrobertjonsson. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @cMadan.

@markusrobertjonsson if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.42 s (48.0 files/s, 17706.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          53           3128           6685           9959
JavaScript                      10           2311           2347           8544
HTML                            43            405              0           7346
CSS                              3            234             44            917
Markdown                         2             76              0            325
TeX                              1             34              7            285
Lisp                             1              3             24             46
YAML                             1              5              4             43
DOS Batch                        1              8              1             27
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                           116           6208           9118          27502
-------------------------------------------------------------------------------


Statistical information for the repository 'b5946d9ad4cf0366c3cb1982' was
gathered on 2020/12/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Markus Jonsson                 103         53210          17911           99.94
drghirlanda                      3            35              9            0.06

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Markus Jonsson            33031           62.1          9.0               11.37
Stefano Ghirlanda            21          100.0         17.9                4.76
```

**Comment by kyleniemeyer** [comment]
Hi @oliviaguest, can you edit this submission?

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02887/joss.02887/10.21105.joss.02887.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02887/joss.02887/10.21105.joss.02887.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- 10.1098/rsos.160734 may be a valid DOI for title: The power of associative learning and the ontogeny of optimal behaviour
- 10.1111/j.1751-0813.2010.00653.x may be a valid DOI for title: Carrots and sticks: Principles of animal training
- 10.1016/s0899-9007(98)00192-0 may be a valid DOI for title: Taste aversion learning: A contemporary perspective
- 10.4324/9780203803509 may be a valid DOI for title: Clinical applications of learning theory
- 10.1109/tsmcc.2012.2218595 may be a valid DOI for title: A survey of actor-critic reinforcement learning: Standard and natural policy gradients
- 10.1101/446906 may be a valid DOI for title: Social learning through associative processes: A computational theory
- 10.1098/rsos.180778 may be a valid DOI for title: What can associative learning do for planning?
- 10.1098/rsos.161011 may be a valid DOI for title: Memory for stimulus sequences: A divide between humans and other animals?
- 10.3758/brm.40.2.442 may be a valid DOI for title: HMS: A MATLAB simulator of the Harris model of associative learning
- 10.3758/lb.38.1.1 may be a valid DOI for title: An attention-modulated associative network
- 10.1016/j.cmpb.2012.02.004 may be a valid DOI for title: A Java simulator of Rescorla and Wagner’s prediction error model and configural cue extensions
- 10.3758/brm.41.1.29 may be a valid DOI for title: ALTSim: A MATLAB simulator for current associative learning theories
- 10.3758/brm.40.2.435 may be a valid DOI for title: Rapid-REM: A MATLAB simulator of the replaced-elements model
- 10.1109/adprl.2009.4927542 may be a valid DOI for title: A theoretical and empirical analysis of Expected Sarsa
- 10.1016/s0019-9958(77)90354-0 may be a valid DOI for title: An adaptive optimal controller for discrete-time Markov environments
- 10.3758/s13423-020-01749-0 may be a valid DOI for title: A-learning: A new formulation of associative learning theory

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
@markusrobertjonsson can you address the missing DOIs and when you get some time drop some names for reviewers, please? 😊

**Comment by oliviaguest** [comment]
@whedon add @themkar as reviewer

**Comment by whedon** [comment]
OK, @themkar is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @CatarauCorina as reviewer

**Comment by whedon** [comment]
OK, @CatarauCorina is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @jkbye as reviewer

**Comment by whedon** [comment]
OK, @jkbye is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2891.
