### ISSUE TITLE
[PRE REVIEW]: Tyssue, en Epithelium simulation library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2888]
**Submitting author:** @glyg (<a href="http://orcid.org/0000-0002-5444-5246">Guillaume Gay</a>)
**Repository:** <a href="https://github.com/damcb/tyssue" target ="_blank">https://github.com/damcb/tyssue</a>
**Version:** v0.8.0
**Editor:** @pdebuyl
**Reviewers:** @fcooper8472, @SergeDmi
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @glyg. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @pdebuyl.

@glyg if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41467-019-10720-0 is OK
- 10.1101/704932 is OK
- 10.1038/s41467-018-06497-3 is OK
- 10.1242/dev.146761 is OK
- 10.1098/rstb.2015.0520 is OK
- 10.1038/nphys3471 is OK
- 10.1038/nature14152 is OK
- 10.1007/s10237-015-0724-7 is OK
- 10.1007/s10237-012-0430-7 is OK
- 10.1016/J.CUB.2010.06.075 is OK
- 10.1016/J.CUB.2007.11.049 is OK
- 10.1016/S0021-9290(02)00006-4 is OK

MISSING DOIs

- 10.1242/prelights.16742 may be a valid DOI for title: Mechanical control of morphogenesis robustness

INVALID DOIs

- https://doi.org/10.1016/S0074-7696(08)62339-6 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/0022-5193(78)90315-6 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.65 s (336.0 files/s, 90043.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             21             19             21          34334
Python                         127           3302           3033          11078
TeX                              2            218              0           3340
Markdown                         6            267              0            503
JSON                            18              1              0            392
reStructuredText                31            320            527            338
CMake                            4             56            184            226
make                             2             35              6            197
C++                              2             36             10            128
YAML                             4             12              2             76
Bourne Shell                     1              5              0             14
INI                              1              0              0              4
-------------------------------------------------------------------------------
SUM:                           219           4271           3783          50630
-------------------------------------------------------------------------------


Statistical information for the repository '3a5dd3b96214f400298ce323' was
gathered on 2020/12/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bertrand Caré                   12          1088             90            1.55
George C                         2           259              6            0.35
Guillaume Gay                  464         33828          20693           71.62
Hadrien Mary                     5            87             86            0.23
Sophie THEIS                   109         12092           7879           26.24
btbest                           1             2              1            0.00
felixquinton                     1             7              1            0.01
kc lee                           1             2              0            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Bertrand Caré                 1            0.1         50.5                0.00
George C                    256           98.8          9.9                7.03
Guillaume Gay             14309           42.3         27.9                6.63
Hadrien Mary                 21           24.1         65.4                0.00
Sophie THEIS               2996           24.8         19.2                7.04
felixquinton                  4           57.1         20.2                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02888/joss.02888/10.21105.joss.02888.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02888/joss.02888/10.21105.joss.02888.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @pdebuyl, can you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by glyg** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by glyg** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2020.01.06.896266 is OK
- 10.1038/s41467-019-10720-0 is OK
- 10.1101/704932 is OK
- 10.1038/s41467-018-06497-3 is OK
- 10.1242/dev.146761 is OK
- 10.1098/rstb.2015.0520 is OK
- 10.1038/nphys3471 is OK
- 10.1038/nature14152 is OK
- 10.1007/s10237-015-0724-7 is OK
- 10.1007/s10237-012-0430-7 is OK
- 10.1016/J.CUB.2010.06.075 is OK
- 10.1016/J.CUB.2007.11.049 is OK
- 10.1016/S0021-9290(02)00006-4 is OK
- 10.1016/S0074-7696(08)62339-6 is OK
- 10.1016/0022-5193(78)90315-6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by glyg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02888/joss.02888/10.21105.joss.02888.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02888/joss.02888/10.21105.joss.02888.pdf) :page_facing_up: :point_left:

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@smsaladi can you review the article "Tyssue, en Epithelium simulation library" for JOSS?

**Comment by smsaladi** [comment]
@pdebuyl Thanks for thinking of me, but it's not a great time for me right now (wouldn't be able to respond within the next month). Hope I can help in the future though...

**Comment by pdebuyl** [comment]
Thank you @smsaladi for your prompt reply! You remain in the list of reviewers, no worry.

**Comment by pdebuyl** [comment]
PS @smsaladi you might want to unsubscribe to this github issue else you will keep on receiving notifications.

**Comment by pdebuyl** [comment]
Hi @glyg I am still looking for reviewers. Our pool of volunteers has few matches for the topic here, I will expand the search.

You can suggest reviewers as well, I will then consider including one from that list.

**Comment by pdebuyl** [comment]
@shriyaamittal can you review the article "Tyssue, en Epithelium simulation library" for the Journal of Open Source Software?

**Comment by glyg** [comment]
Hi @pdebuyl , thank you,

If you talk about reviewers outside of the volunteers, I can think of Guillaume Salbreux or people in the teams of Lisa Manning, Alexander Fletcher or Frank Jüllicher

**Comment by pdebuyl** [comment]
@Paijmans can you review the article "Tyssue, en Epithelium simulation library" for the Journal of Open Source Software?

**Comment by shriyaamittal** [comment]
Sorry, I have no competence in cell biology to review this work.

**Comment by pdebuyl** [comment]
Thank you for the reply @shriyaamittal . You might want to unsubscribe to this github issue else you will keep on receiving notifications.

**Comment by pdebuyl** [comment]
@salbreux can you review the article "Tyssue, en Epithelium simulation library" for the Journal of Open Source Software? (please check our COI policy https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy ).

**Comment by glyg** [comment]
Hi @pdebuyl happy new year!

 I'm tagging @sophietheis here so she can follow the process 
Best

Guillaume

**Comment by pdebuyl** [comment]
Happy new year @glyg :-)

I have proceeded with email invitations, I'll let you know of course when there is an update. Sorry that this is taking so long.

**Comment by glyg** [comment]
No worries, there's no rush

**Comment by pdebuyl** [comment]
@whedon assign @fcooper8472 as reviewer

**Comment by whedon** [comment]
OK, @fcooper8472 is now a reviewer

**Comment by pdebuyl** [comment]
@whedon add @SergeDmi as reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2973.
