### ISSUE TITLE
[PRE REVIEW]: SymbiotaR2: An R Package for Accessing Symbiota2 Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2889]
**Submitting author:** @akoontz11 (<a href="http://orcid.org/0000-0002-6103-5894">Austin Koontz</a>)
**Repository:** <a href="https://github.com/ropensci/SymbiotaR2" target ="_blank">https://github.com/ropensci/SymbiotaR2</a>
**Version:** v1.0.0
**Editor:** @kyleniemeyer
**Reviewers:** @kyleniemeyer
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @akoontz11. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @karthik.

@akoontz11 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (1362.8 files/s, 149692.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                           105              3              0          12896
R                               32            214            560           1560
Markdown                         6             79              0            313
JSON                             1              0              0            145
TeX                              1              1              0             18
Rmd                              1             34            214              0
-------------------------------------------------------------------------------
SUM:                           146            331            774          14932
-------------------------------------------------------------------------------


Statistical information for the repository '59bf3123198f0dbd6dba32c5' was
gathered on 2020/12/05.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3897/BDJ.2.e1114 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02889/joss.02889/10.21105.joss.02889.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02889/joss.02889/10.21105.joss.02889.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @akoontz11, thanks for your interest in JOSS. The editorial board is going to review your software to see if it falls within our scope—in particular, while useful, this looks like an API client rather than [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software).

I did note that this comes from rOpenSci; if deemed to be within the scope of JOSS, the review/publication will be fast-tracked, but not all rOpenSci-approved packages are automatically within the scope of JOSS.

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by akoontz11** [comment]
Hi @kyleniemeyer, thanks for your message and providing information on this submission. This software has completed [review by rOpenSci](https://github.com/ropensci/software-review/issues/373), but I wanted to reach out and just ask about the status of this review. If there's anything I could do to help move the process along, please let me know.

**Comment by kyleniemeyer** [comment]
Thanks @akoontz11 - this was judged to be within scope, so we will proceed!

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as reviewer

**Comment by whedon** [comment]
OK, @kyleniemeyer is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2917.
