### ISSUE TITLE
[REVIEW]: Learning Simulator: A simulation software for animal and human learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2891]
**Submitting author:** @markusrobertjonsson (<a href="http://orcid.org/0000-0003-1242-3599">Markus Jonsson</a>)
**Repository:** <a href="https://github.com/learningsimulator/learningsimulator" target ="_blank">https://github.com/learningsimulator/learningsimulator</a>
**Version:** v1.0.1
**Editor:** @oliviaguest
**Reviewers:** @themkar, @CatarauCorina
**Archive:** <a href="https://doi.org/10.5281/zenodo.4544535" target="_blank">10.5281/zenodo.4544535</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3987c9eb5e1e31414be3f320eed9303f/status.svg)](https://joss.theoj.org/papers/3987c9eb5e1e31414be3f320eed9303f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3987c9eb5e1e31414be3f320eed9303f"><img src="https://joss.theoj.org/papers/3987c9eb5e1e31414be3f320eed9303f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3987c9eb5e1e31414be3f320eed9303f/status.svg)](https://joss.theoj.org/papers/3987c9eb5e1e31414be3f320eed9303f)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/learningsimulator/learningsimulator" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@themkar & @CatarauCorina & @jkbye, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @oliviaguest know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/learningsimulator/learningsimulator">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@markusrobertjonsson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/learningsimulator/learningsimulator">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@markusrobertjonsson) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @themkar, @CatarauCorina, @jkbye it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02891/joss.02891/10.21105.joss.02891.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02891/joss.02891/10.21105.joss.02891.pdf) :page_facing_up: :point_left:

**Comment by oliviaguest** [comment]
Hi all! 👋 Thank you so much — @themkar, @CatarauCorina, and @jkbye — for accepting to review this. Please read the instructions above. Any questions, feedback on the paper, etc., please post here. Any very code-specific questions, suggestions, etc., please use the issues in the code repo and link to them from this thread so we can all keep track of them. 🌸

For an example of how this process plays out feel free to skim previous reviews, such as: #2285 and #2348. ☺️

**Comment by oliviaguest** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- 10.1098/rsos.160734 may be a valid DOI for title: The power of associative learning and the ontogeny of optimal behaviour
- 10.1111/j.1751-0813.2010.00653.x may be a valid DOI for title: Carrots and sticks: Principles of animal training
- 10.1016/s0899-9007(98)00192-0 may be a valid DOI for title: Taste aversion learning: A contemporary perspective
- 10.4324/9780203803509 may be a valid DOI for title: Clinical applications of learning theory
- 10.1109/tsmcc.2012.2218595 may be a valid DOI for title: A survey of actor-critic reinforcement learning: Standard and natural policy gradients
- 10.1101/446906 may be a valid DOI for title: Social learning through associative processes: A computational theory
- 10.1098/rsos.180778 may be a valid DOI for title: What can associative learning do for planning?
- 10.1098/rsos.161011 may be a valid DOI for title: Memory for stimulus sequences: A divide between humans and other animals?
- 10.3758/brm.40.2.442 may be a valid DOI for title: HMS: A MATLAB simulator of the Harris model of associative learning
- 10.3758/lb.38.1.1 may be a valid DOI for title: An attention-modulated associative network
- 10.1016/j.cmpb.2012.02.004 may be a valid DOI for title: A Java simulator of Rescorla and Wagner’s prediction error model and configural cue extensions
- 10.3758/brm.41.1.29 may be a valid DOI for title: ALTSim: A MATLAB simulator for current associative learning theories
- 10.3758/brm.40.2.435 may be a valid DOI for title: Rapid-REM: A MATLAB simulator of the replaced-elements model
- 10.1109/adprl.2009.4927542 may be a valid DOI for title: A theoretical and empirical analysis of Expected Sarsa
- 10.1016/s0019-9958(77)90354-0 may be a valid DOI for title: An adaptive optimal controller for discrete-time Markov environments
- 10.3758/s13423-020-01749-0 may be a valid DOI for title: A-learning: A new formulation of associative learning theory

INVALID DOIs

- None
```

**Comment by markusrobertjonsson** [comment]
@oliviaguest missing DOIs addressed. If you need it, additional reviewer suggestions are satpreetsingh and seba-1511.

**Comment by oliviaguest** [comment]
@whedon check references

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02891/joss.02891/10.21105.joss.02891.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02891/joss.02891/10.21105.joss.02891.pdf) :page_facing_up: :point_left:

**Comment by oliviaguest** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.1098/rsos.160734 is OK
- 10.1111/j.1751-0813.2010.00653.x is OK
- 10.1016/s0899-9007(98)00192-0 is OK
- 10.4324/9780203803509 is OK
- 10.1109/tsmcc.2012.2218595 is OK
- 10.1101/446906 is OK
- 10.1098/rsos.180778 is OK
- 10.1098/rsos.161011 is OK
- 10.3758/brm.40.2.442 is OK
- 10.3758/lb.38.1.1 is OK
- 10.1016/j.cmpb.2012.02.004 is OK
- 10.3758/brm.41.1.29 is OK
- 10.3758/brm.40.2.435 is OK
- 10.1109/adprl.2009.4927542 is OK
- 10.1016/s0019-9958(77)90354-0 is OK
- 10.3758/s13423-020-01749-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@markusrobertjonsson great! 😊

**Comment by oliviaguest** [comment]
@themkar, @CatarauCorina, and @jkbye — can you please post a rough ETA for your reviews, please?

**Comment by whedon** [comment]
:wave: @jkbye, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @themkar, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @CatarauCorina, please update us on how your review is going.

**Comment by CatarauCorina** [comment]
> @themkar, @CatarauCorina, and @jkbye — can you please post a rough ETA for your reviews, please?

Hi @oliviaguest  by the end of this week for me, I was away, sorry for the late reply.

**Comment by jkbye** [comment]
Hello @oliviaguest thank you for your patience. I have been dealing with a family issue but will finish the review by next week.

**Comment by themkar** [comment]
Hello @oliviaguest, Happy new year. I shall be able to have this by 31st Jan. Hope this is ok.

**Comment by oliviaguest** [comment]
Great! Thanks @themkar, @CatarauCorina, and @jkbye! Just need an ETA for now, so this is all perfect! Hope you are all well. 🌼

**Comment by oliviaguest** [comment]
@whedon remind @themkar in a month

**Comment by whedon** [comment]
I don't recognize this description of time 'a' 'month
'.

**Comment by oliviaguest** [comment]
@whedon remind @themkar in 1 month

**Comment by whedon** [comment]
Reminder set for @themkar in 1 month

**Comment by oliviaguest** [comment]
@whedon remind @CatarauCorina in 1 week

**Comment by whedon** [comment]
Reminder set for @CatarauCorina in 1 week

**Comment by oliviaguest** [comment]
@whedon remind @jkbye in 2 weeks

**Comment by whedon** [comment]
Reminder set for @jkbye in 2 weeks

**Comment by whedon** [comment]
:wave: @CatarauCorina, please update us on how your review is going.

**Comment by CatarauCorina** [comment]
Hi @oliviaguest , I am about to finish my review, but I have 2 questions:
1. Any errors that I have encounter should I add them under the functionality observations?
2. Is the software paper the one found on readthedocs ?https://learningsimulator.readthedocs.io/en/latest/background.html
As I can't seem to find it anywhere else.

Thank you for your help!

**Comment by CatarauCorina** [comment]
### Functionality
✅ Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
      OK: A list of dependencies to install  found in requirements.txt

✅ Functionality: Have the functional claims of the software been confirmed?

- Yes, but whenever I press simulate and plot I am getting an additional window not shown in the documentation called “Plot and Export Progress”. This number of this windows increases with each simulation such that in the below image I have ran 3 simulations and therefore apart from my plot window is these 3 extra windows. Unsure weather this has to be addressed

![image](https://user-images.githubusercontent.com/8167831/104338873-a6659180-54ff-11eb-8304-3adb64955cec.png)

- - “ A stimulus is specified as a comma-separated list of stimulus elements, optionally with the intensity in brackets after the stimulus element name, for example e1,e2, or e1[0.3],e2,e3[0.9]” . However when modifying the default script to add intensity to the stimulus elements I get an error. Should the intensity be added in a different place ? And if so I think it's unclear in the documentation

![image](https://user-images.githubusercontent.com/8167831/104338938-bb422500-54ff-11eb-8d3a-f878bc7007a0.png)

Here is the head of the input file 
n_subjects        = 10
mechanism         = sr
behaviors         = response, no_response
stimulus_elements = stimulus[0.9],background,reward[0.3]
start_v           = -1
alpha_v           = 0.1
u                 = reward:10, default:0

-  “ n_subjects = n where n is a scalar expression evaluating to a positive integer”.  When running **python lesim.py gui** and adding a value to n_subjects < 5 it fails, when running it in script mode it performs ok.

### Documentation

✅ A statement of need  Do the authors clearly state what problems the software is designed to solve and who the target audience is?

- Yes, however it does not state the intended audience, I would add who the user persona is, in order to understand the background necessary to use it properly 

✅ Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

- Yes, there is one example script for stimulus-response mechanism, though considering the complexity of the language a few more would be useful , for example one for every mechanism.

✅ Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?
	- Yes, but I couldn't find how to run all of them at once, and some seemed to fail as I ran them one by one

**Comment by markusrobertjonsson** [comment]
@oliviaguest I can respond to issues and questions raised by the reviewers as they come in, without having to wait for a final assessment, right? And I can make commits to source code and docs to address them, if needed?

**Comment by oliviaguest** [comment]
@markusrobertjonsson absolutely, yes!

**Comment by whedon** [comment]
:wave: @jkbye, please update us on how your review is going.

**Comment by markusrobertjonsson** [comment]
@CatarauCorina Thanks for reviewing! Below are my comments to the issues you raised.
- Regarding the Plot/Export Progress: We have noticed a few window-related problems on Mac. This seems to be yet another one. The Progress dialog box just displays the progress bar and does not affect the functionality. I have now disabled it on Mac, and made an issue to look into this. To help with the debugging: Which OSX version are you using?
- Regarding the problem with intensities: Stimulus intensities should not be specified in the parameter `stimulus_elements`, but in a `@phase`-block where it specifies the intensity of the stimulus element that is presented to the subject. The parameter `stimulus_elements` just declares the names of the elements. I have clarified the documentation.
- Regarding the problem with `n_subjects`<5: As this does not seem to be a general problem, feel free to either send me the script where the error occured, and/or submit an issue.
- Regarding the intended audience: In the README-file as well as in the Summary section on https://github.com/learningsimulator, it says "It is primarily intended for computational and behavioral biologists, ethologists, and psychologists, and it can also be useful to students and teachers in these fields." Let me know if you think this should be stated elsewhere as well.
- Regarding example usage: Since changing the mechanism merely involves setting the value of the property `mechanism` (to `ga`, `sr`, `es`, `ql`, `ac`, or `rw`) while keeping the rest of the script intact, the complexity of the scripting language will not be showcased this way. Instead we refer to the script database on the project's website https://www.learningsimulator.org/script-database. I have added a reference to the database in the doc section "A Small Usage Example".
- Regarding automated tests: There are automated tests (that are run by GitHub Actions), and the build-badge "Learning Simulator" shows whether or not they are passing. In a Python environment with `pytest` or `unittest` installed, the test suite can be run with `python -m pytest` (as in `workflow.yml`) or `python -m unittest`. To run an individual test file (for example `test_beta.py` that tests the script parameter `beta`), use `python -m pytest tests/test_beta.py` or `python -m unittest tests/test_beta.py`. (As far as I can see, the JOSS docs criteria for tests only says "An automated test suite hooked up to an external service such as Travis-CI or similar", not that there has to be instructions on how to manually execute the automated test suite.)

**Comment by CatarauCorina** [comment]
@markusrobertjonsson , thank you for your response ! 

1. 10.14.5 is the version I have
2. Thank you for adding that to the documentation, is clear now , I have tested and it is working fine.
3. Ok, it's not a urgent issue, as I was saying in script mode is working fine, plus if I'm not mistaken usually in this type of experiments larger number of subjects are used.
4. That's fine - I might have missed it. Sorry !
5. That's perfect as the script database has 3 types of mechanisms, so that's great. Thanks!
6.  You are correct, I didn't see there was a CI pipeline in place, I saw it now under actions and had a look at the stages of the build pipeline and you are correct they are running fine in that environment so it is surely something to do with my machine, which is not a requirement.

Thank you for clarifying my issues, I appreciate it. Good luck with your review further !

**Comment by oliviaguest** [comment]
@markusrobertjonsson feel free to make edits (as needed) before the other reviewers take a look.

**Comment by markusrobertjonsson** [comment]
@oliviaguest I have no additional edits to make at this point. I am looking forward to addressing possible further issues in the continued review process.

**Comment by whedon** [comment]
:wave: @themkar, please update us on how your review is going.

**Comment by themkar** [comment]
My apologies for the delay, I shall be able to complete it later this week.

**Comment by oliviaguest** [comment]
@themkar thank you for the update! 🎉

**Comment by oliviaguest** [comment]
@whedon re-invite @themkar as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@themkar please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by themkar** [comment]
Hi @oliviaguest, I have finished my review and I am appending my comments (minor points) below.
Many thanks.

**comment #1**
_Functionality: Have the functional claims of the software been confirmed?_

I have experimented with LeSIm using the GUI and the Computer Lab document and the three example scripts. I think it achieves the simplicity to which the authors refer to in the statement in need. 
The software offers good functionality for producing plots.

The GUI produced this warning in the chaining web, which can be explained better.

![image](https://github.com/themkar/myimages/raw/main/lesim.png)

It would be good to have text processing functionalities under edit- copy, paste, find (or with keyboard shortcuts). Not sure if it is my system, but only undo and redo were available.


**comment #2**
_Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution._

Yes. Tried installation on Win, MacOS, Linux Mint. It might be worth including the possibility in which python is called with python3 (no alias).

**comment #3**
_Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems)._
Yes. would be good if a sample script folder was incorporated in the GUI.

**comment #4**
 _Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?_
Yes. And I especially liked the availability of a tutorial.

**Comment by oliviaguest** [comment]
@themkar I don't know if you want/need to try again with the image you tried to attach as I cannot see it..?

**Comment by markusrobertjonsson** [comment]
@themkar Thank you for reviewing! Below are my responses to your comments.

**comment #1**
The warning is a deprecated-syntax-warning. I have edited the script to use the updated syntax, so that the warning does not appear in that script anymore.

Additional text-processing functionalities are planned (see e.g. https://github.com/markusrobertjonsson/learningsimulator/issues/6), but since it is possible for the user to use his/her favourite editor and run scripts from a command line, we have not prioritized this.

**comment #2**
I have added python3 (and pip3) to the installation instructions.

**comment #3**
The addition of sample scripts (in a "Script Library") is a very good idea and is indeed planned for the future (https://github.com/markusrobertjonsson/learningsimulator/issues/26).

**comment #4**
Great!

**Comment by oliviaguest** [comment]
@markusrobertjonsson I think, if no other edits are obvious to you, we can continue with this without @jkbye (unless @jkbye you have time to take look within the next few days?), as I think he is very busy and might not have the time to check this out (totally understandable given pandemic).

**Comment by themkar** [comment]
> @themkar I don't know if you want/need to try again with the image you tried to attach as I cannot see it..?

@oliviaguest is it visible now?

thanks @markusrobertjonsson for addressing my comments. Looking forward to using this software!

**Comment by oliviaguest** [comment]
@themkar yes, thank you! 🌼

**Comment by markusrobertjonsson** [comment]
@oliviaguest I have no other edits to make at this point. I very much appreciate the reviewer's comments.

**Comment by oliviaguest** [comment]
@whedon compile pdf

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02891/joss.02891/10.21105.joss.02891.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02891/joss.02891/10.21105.joss.02891.pdf) :page_facing_up: :point_left:

**Comment by oliviaguest** [comment]
@whedon remove @jkbye as reviewer

**Comment by whedon** [comment]
OK, @jkbye is no longer a reviewer

**Comment by oliviaguest** [comment]
@markusrobertjonsson can you please create an archive for the software (on Zenodo, figshare, etc.) and post the DOI here? 😊

**Comment by oliviaguest** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.1098/rsos.160734 is OK
- 10.1111/j.1751-0813.2010.00653.x is OK
- 10.1016/s0899-9007(98)00192-0 is OK
- 10.4324/9780203803509 is OK
- 10.1109/tsmcc.2012.2218595 is OK
- 10.1101/446906 is OK
- 10.1098/rsos.180778 is OK
- 10.1098/rsos.161011 is OK
- 10.3758/brm.40.2.442 is OK
- 10.3758/lb.38.1.1 is OK
- 10.1016/j.cmpb.2012.02.004 is OK
- 10.3758/brm.41.1.29 is OK
- 10.3758/brm.40.2.435 is OK
- 10.1109/adprl.2009.4927542 is OK
- 10.1016/s0019-9958(77)90354-0 is OK
- 10.3758/s13423-020-01749-0 is OK

MISSING DOIs

- 10.1007/978-0-387-44956-2_12 may be a valid DOI for title: A mathematical model for simple learning

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@markusrobertjonsson and fix the DOIs (you can run the same command as me to check them). ☺️

**Comment by markusrobertjonsson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.1098/rsos.160734 is OK
- 10.1111/j.1751-0813.2010.00653.x is OK
- 10.1016/s0899-9007(98)00192-0 is OK
- 10.4324/9780203803509 is OK
- 10.1109/tsmcc.2012.2218595 is OK
- 10.1101/446906 is OK
- 10.1098/rsos.180778 is OK
- 10.1098/rsos.161011 is OK
- 10.3758/brm.40.2.442 is OK
- 10.3758/lb.38.1.1 is OK
- 10.1016/j.cmpb.2012.02.004 is OK
- 10.3758/brm.41.1.29 is OK
- 10.3758/brm.40.2.435 is OK
- 10.1037/h0054388 is OK
- 10.1109/adprl.2009.4927542 is OK
- 10.1016/s0019-9958(77)90354-0 is OK
- 10.3758/s13423-020-01749-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by markusrobertjonsson** [comment]
@oliviaguest I added the repo to Zenodo. The DOI is 10.5281/zenodo.4544535.

**Comment by oliviaguest** [comment]
@whedon check repository

**Comment by oliviaguest** [comment]
@whedon set 10.5281/zenodo.4544535 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4544535" target="_blank">10.5281/zenodo.4544535</a> is the archive.

**Comment by oliviaguest** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.08 s (107.8 files/s, 39777.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          54           3189           6778          10109
JavaScript                      10           2311           2347           8544
HTML                            43            405              0           7350
CSS                              3            234             44            917
Markdown                         2             76              0            326
TeX                              1             34              7            302
Lisp                             1              3             24             46
YAML                             1              5              4             43
DOS Batch                        1              8              1             27
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                           117           6269           9211          27674
-------------------------------------------------------------------------------


Statistical information for the repository '3b7733eeeba18e148f188832' was
gathered on 2021/02/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Learning Simulator -             1             1              1            0.00
Markus Jonsson                 111         53557          17954           99.94
drghirlanda                      3            35              9            0.06

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Learning Simulator -          1          100.0          1.0                0.00
Markus Jonsson            33334           62.2         10.7               11.29
Stefano Ghirlanda            21          100.0         20.1                4.76
```

**Comment by oliviaguest** [comment]
@markusrobertjonsson can you change the title on zenodo to match the title of your JOSS submission please?

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2106

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2106, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by oliviaguest** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.1098/rsos.160734 is OK
- 10.1111/j.1751-0813.2010.00653.x is OK
- 10.1016/s0899-9007(98)00192-0 is OK
- 10.4324/9780203803509 is OK
- 10.1109/tsmcc.2012.2218595 is OK
- 10.1101/446906 is OK
- 10.1098/rsos.180778 is OK
- 10.1098/rsos.161011 is OK
- 10.3758/brm.40.2.442 is OK
- 10.3758/lb.38.1.1 is OK
- 10.1016/j.cmpb.2012.02.004 is OK
- 10.3758/brm.41.1.29 is OK
- 10.3758/brm.40.2.435 is OK
- 10.1037/h0054388 is OK
- 10.1109/adprl.2009.4927542 is OK
- 10.1016/s0019-9958(77)90354-0 is OK
- 10.3758/s13423-020-01749-0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02891/joss.02891/10.21105.joss.02891.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02891/joss.02891/10.21105.joss.02891.pdf) :page_facing_up: :point_left:

**Comment by markusrobertjonsson** [comment]
@oliviaguest The title on Zenodo is now changed to match the JOSS submission.

**Comment by kthyng** [comment]
Hi @markusrobertjonsson! I'll be helping to finalize your publication. Can you also update the metadata on your Zenodo archive so that the author list matches your JOSS paper?

**Comment by kthyng** [comment]
@markusrobertjonsson Your paper looks great and everything will be in order once I hear back from you about the author list. Thanks!

**Comment by markusrobertjonsson** [comment]
@kthyng Thanks. The author list on Zenodo is now correct.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1364603745397477377) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2110
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02891](https://doi.org/10.21105/joss.02891)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congratulations to @markusrobertjonsson on your new publication! Many thanks to editor @oliviaguest and to reviewers @themkar and @CatarauCorina — this literally couldn't occur without you! 🎉 

(will wait to close this issue until the doi resolves)

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02891/status.svg)](https://doi.org/10.21105/joss.02891)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02891">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02891/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02891/status.svg
   :target: https://doi.org/10.21105/joss.02891
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02891/status.svg)](https://doi.org/10.21105/joss.02891)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
