### ISSUE TITLE
[PRE REVIEW]: pyHomogeneity: A python package for homogeneity test of time series data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2893]
**Submitting author:** @mmhs013 (<a href="http://orcid.org/0000-0002-5361-0633">Md. Manjurul Hussain</a>)
**Repository:** <a href="https://github.com/mmhs013/pyHomogeneity" target ="_blank">https://github.com/mmhs013/pyHomogeneity</a>
**Version:** v1.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mmhs013. **Currently, there isn't an JOSS editor assigned** to your paper.

@mmhs013 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/joc.3370060607 is OK
- 10.1016/0022-1694(82)90066-X is OK
- 10.1016/0022-1694(84)90032-5 is OK
- 10.2307/2346729 is OK
- 10.13140/RG.2.1.4431.3688 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (131.0 files/s, 37054.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           6            469           1091           1266
Markdown                         4            141              0            300
TeX                              1              0              0             52
Jupyter Notebook                 1              0            310             32
YAML                             1              0              1             15
-------------------------------------------------------------------------------
SUM:                            13            610           1402           1665
-------------------------------------------------------------------------------


Statistical information for the repository 'a399b358f9d5c8e569b6c25a' was
gathered on 2020/12/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Md. Manjurul Hussain             1            21             20            1.23
Md. Manjurul Hussain            10          3052            227           98.77

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Md. Manjurul Hussain       2826        13457.1          0.3               14.33
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02893/joss.02893/10.21105.joss.02893.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02893/joss.02893/10.21105.joss.02893.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@mmhs013 since this submission features around 1000 lines of code (and the core functionality seems to be about 300 lines https://github.com/mmhs013/pyHomogeneity/blob/master/pyhomogeneity/pyhomogeneity.py), I have flagged this submission for an additional scope check by the editorial board. In particular out board will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mmhs013 in the meantime you could work to add the required `Statement of need` section to the paper (https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).  If you'd like to update the paper you can call the following in a comment here: 

`@whedon generate pdf`

**Comment by mmhs013** [comment]
@Kevin-Mattheus-Moerman, thanks for your consideration. `Statement of need` already covered in the `Summary` section. So I think it is not needed any more.

**Comment by arfon** [comment]
@mmhs013 - Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
