### ISSUE TITLE
[PRE REVIEW]: WI Fast Stats: a collection of web apps for the visualization and analysis   of WI Fast Plants data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2894]
**Submitting author:** @crsl4 (<a href="http://orcid.org/0000-0002-9789-8915">Claudia Solis-Lemus</a>)
**Repository:** <a href="https://github.com/crsl4/fast-stats" target ="_blank">https://github.com/crsl4/fast-stats</a>
**Version:** v2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @crsl4. **Currently, there isn't an JOSS editor assigned** to your paper.

@crsl4 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.72 s (50.0 files/s, 24638.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              6            884            112           6968
R                                4            419            508           2124
JavaScript                      12            474            490           2052
HTML                             3            242            286           1371
SVG                              1              0              0            504
Markdown                         6            151              0            399
Rmd                              2            130            218            353
TeX                              1              3              0             34
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            36           2304           1618          13823
-------------------------------------------------------------------------------


Statistical information for the repository '7ca4f591dae57427d20a040c' was
gathered on 2020/12/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Yizhou Liu                       1          3016              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Yizhou Liu                 3016          100.0          0.0               16.31
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2894 with the following error: 

 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.292 ....edu}{\nolinkurl{solislemus@wisc.edu}})}}

Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1126/science.232.4756.1385 may be a valid DOI for title: Rapid-cycling populations of Brassica

INVALID DOIs

- https://doi.org/10.1002/lol2.10165 is INVALID because of 'https://doi.org/' prefix
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@crsl4 thanks for this submission. I have flagged this submission for additional scope review by our editorial board. In particular it may be deemed out of scope as it appears to mainly offer educational functionality (in the form of a web app) rather than scientific research functionality. The additional review will take about a week.

**Comment by crsl4** [comment]
Thanks Kevin! While it is true that the web app is aligned to the Fast Plants educational units, the software is used as a research tool for students designing and implementing their own plant experiments. Perhaps it is still out of scope, but we wait to hear what the additional review says. Thanks!

**Comment by arfon** [comment]
Hi @crsl4, many thanks for your submission. After consulting with the JOSS editorial team, we've concluded this submission is out of scope for JOSS. We believe this may be a better fit for the Journal of Open Source Education (http://jose.theoj.org).

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by crsl4** [comment]
I know that this issue is closed and I fully accept the rejection decision, but I submitted the manuscript to Journal of Open Source Education (http://jose.theoj.org) a month ago as you suggested and the review process has not even been started. I have emailed the editor without response either. So, I wonder if you know of other similar journals were I could submit this work. Any help is appreciated!

**Comment by arfon** [comment]
> I know that this issue is closed and I fully accept the rejection decision, but I submitted the manuscript to Journal of Open Source Education (http://jose.theoj.org) a month ago as you suggested and the review process has not even been started. I have emailed the editor without response either. So, I wonder if you know of other similar journals were I could submit this work. Any help is appreciated!

☝️ @openjournals/jose-eics .

**Comment by labarba** [comment]
Noted. Thanks. Submissions arriving in December (end of semester, holidays, volunteer labor) are handled as best we can.

**Comment by crsl4** [comment]
Thank you Lorena! I completely understand the delay in the review process. I was mostly worried that the page stated that review had not even started, so I was worried there was another reason for the delay. I appreciate your help!
