### ISSUE TITLE
[PRE REVIEW]: Moead-framework : a modular MOEA/D python framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2895]
**Submitting author:** @geoffreyp (<a href="http://orcid.org/0000-0002-5049-5991">Geoffrey Pruvost</a>)
**Repository:** <a href="https://github.com/moead-framework/framework" target ="_blank">https://github.com/moead-framework/framework</a>
**Version:** 0.5.7.1
**Editor:** @melissawm
**Reviewers:** @sjvrijn, @chkoar
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @geoffreyp. **Currently, there isn't an JOSS editor assigned** to your paper.

@geoffreyp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TEVC.2008.925798 is OK
- 10.1109/TEVC.2007.892759 is OK
- 10.1109/CEC.2009.4982949 is OK
- 10.1145/3377930.3390149 is OK
- 10.1007/978-3-030-43680-3_9 is OK
- 10.18637/jss.v092.i06 is OK
- 10.1109/ACCESS.2020.2990567 is OK
- 10.21105/joss.02338 is OK
- 10.1145/2739482.2768462 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (593.2 files/s, 30383.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          49            549            236           1648
Markdown                         2             50              0            124
TeX                              1             10              0            110
YAML                             3             14              9             67
-------------------------------------------------------------------------------
SUM:                            55            623            245           1949
-------------------------------------------------------------------------------


Statistical information for the repository '0642baeb5b9ddc8ee0fd9878' was
gathered on 2020/12/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Geoffrey Pruvost                60          2461            661          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Geoffrey Pruvost           2433           98.9          4.0                5.88
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02895/joss.02895/10.21105.joss.02895.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02895/joss.02895/10.21105.joss.02895.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@geoffreyp given that this submission is on the small side (in therms of number of lines of code). I have flagged this submission for an additional scope check by the editorial board. In particular our board will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by kthyng** [comment]
Hi @geoffreyp, your paper is missing a section titled "Statement of Need." It also should start with a high level scientific summary that a scientific person not in your area would understand.

**Comment by kthyng** [comment]
@melissawm are you able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @melissawm as editor

**Comment by whedon** [comment]
@melissawm has been invited to edit this submission.

**Comment by geoffreyp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02895/joss.02895/10.21105.joss.02895.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02895/joss.02895/10.21105.joss.02895.pdf) :page_facing_up: :point_left:

**Comment by geoffreyp** [comment]
Hello @kthyng, thank you for your feedback. The paper is updated with the "Statement of Need" section.

**Comment by melissawm** [comment]
Yes, I can edit this submission. Thanks @kthyng !

**Comment by melissawm** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by melissawm** [comment]
Hello @geoffreyp ! Do you have any suggestions for reviewers from the [JOSS reviewer list](https://bit.ly/joss-reviewers)?

**Comment by geoffreyp** [comment]
Hello @melissawm, this is a list of reviewers I could find in my domain/topic:
sjvrijn, jmadera, jbytecode, petroniocandido, chkoar, andim

**Comment by melissawm** [comment]
Thank you, @geoffreyp , and really sorry for the delay in responding.

**Comment by melissawm** [comment]
Hello, @sjvrijn @jmadera! Would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by sjvrijn** [comment]
Hi @melissawm, looks relevant to me indeed, I can review

**Comment by melissawm** [comment]
@whedon assign @sjvrijn as reviewer

**Comment by whedon** [comment]
OK, @sjvrijn is now a reviewer

**Comment by melissawm** [comment]
Hello, @petroniocandido! Would you be willing/available to review this submission for JOSS?

**Comment by melissawm** [comment]
Hello, @chkoar! Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by chkoar** [comment]
Hey @melissawm, I'd be happy to help.

**Comment by melissawm** [comment]
@whedon add @chkoar as reviewer

**Comment by whedon** [comment]
OK, @chkoar is now a reviewer

**Comment by melissawm** [comment]
Thank you both, and@geoffreyp! Now that we have two reviewers, we can open the REVIEW issue - this PRE-REVIEW issue will be closed automatically, and we'll continue the work there.

**Comment by melissawm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2974.
