### ISSUE TITLE
[PRE REVIEW]: lidar: A Python package for terrain and hydrological analysis using digital elevation models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2896]
**Submitting author:** @giswqs (<a href="http://orcid.org/0000-0001-5437-4073">Qiusheng Wu</a>)
**Repository:** <a href="https://github.com/giswqs/lidar" target ="_blank">https://github.com/giswqs/lidar</a>
**Version:** 0.5.1
**Editor:** @kbarnhart
**Reviewers:** @laijingtao, @cheginit, @amanaster2
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @giswqs. **Currently, there isn't an JOSS editor assigned** to your paper.

@giswqs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.cageo.2005.11.002 is OK
- 10.1016/j.geomorph.2016.05.006 is OK
- 10.1007/s13157-015-0731-6 is OK
- 10.1080/13658816.2015.1038719 is OK
- 10.1111/1752-1688.12689 is OK
- 10.1080/13658810500433453 is OK
- 10.1080/13658816.2014.975715 is OK
- 10.1002/hyp.10648 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (420.1 files/s, 40023.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          13            288            259            986
reStructuredText                11            205            176            236
TeX                              1              7              0            124
Jupyter Notebook                 2              0            790             97
YAML                             4              9             20             96
make                             2             24              6             78
Markdown                         2             17              0             51
DOS Batch                        1              8              1             27
INI                              1              5              0             15
-------------------------------------------------------------------------------
SUM:                            37            563           1252           1710
-------------------------------------------------------------------------------


Statistical information for the repository '0c0f307b066ea03f6ad8c52b' was
gathered on 2020/12/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Qiusheng Wu                     59          2766           1233          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Qiusheng Wu                1533           55.4         12.1               17.16
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02896/joss.02896/10.21105.joss.02896.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02896/joss.02896/10.21105.joss.02896.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@giswqs since this submission is on the small side (in therms of number of lines of code). I have flagged this submission for an additional scope check by the editorial board. In particular our board will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by giswqs** [comment]
@Kevin-Mattheus-Moerman No problem. Thank you for the consideration.

**Comment by giswqs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02896/joss.02896/10.21105.joss.02896.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02896/joss.02896/10.21105.joss.02896.pdf) :page_facing_up: :point_left:

**Comment by giswqs** [comment]
@Kevin-Mattheus-Moerman Just let you know that I have added more functionality to the package and expanded the source code by a few more hundreds of lines. You can rerun the statistics if needed. Thanks.

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.19 s (234.1 files/s, 29466.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          20            605            570           2370
reStructuredText                11            205            176            236
TeX                              1              7              0            124
Jupyter Notebook                 2              0            790             97
YAML                             4              9             20             96
make                             2             24              6             78
Markdown                         2             17              0             52
DOS Batch                        1              8              1             27
INI                              1              5              0             15
-------------------------------------------------------------------------------
SUM:                            44            880           1563           3095
-------------------------------------------------------------------------------


Statistical information for the repository '8015707b8d245e5870642f86' was
gathered on 2020/12/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Qiusheng Wu                     60          4778           1233          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Qiusheng Wu                3545           74.2          5.3               14.22
```

**Comment by kthyng** [comment]
@kbarnhart are you willing to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @kbarnhart as editor

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by kbarnhart** [comment]
@kthyng I can handle this starting in early Jan. 

@giswqs thanks for the submission. It still has the query-scope label, which means we are still determining whether the submission fits the scope of JOSS. I may follow up with some questions/clarifications on this point in early January. Please let me know if you have questions.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by giswqs** [comment]
@kbarnhart No problem. Thank you for the consideration.

**Comment by kyleniemeyer** [comment]
@kbarnhart @giswqs the editorial board voted to consider this one in scope, so please proceed! I'm removing the `scope-query` label.

**Comment by kbarnhart** [comment]
@giswqs I'm now back in the office and will start actively handling this submission. 

A couple of clarifying questions.

1. Is there a place where API-level documentation is provided? I've looked through the readthedocs page and can't seem to find this. I would expect that all public facing functions/classes would have detailed documentation describing the format of all inputs and outputs. 
2. Could you comment on the similarities/difference between the core package and the arcpy toolbox. E.g., is 
lidar/toolbox/scripts/4_Slicing.py intended as the arcpy equivalent of lidar/slicing.py?
3. It appears that the tests in lidar/tests are empty. Could you comment on how the contents of the package is tested?

A final comment: There are a number of dependencies (matplotlib, scipy, numpy, richDEM, skimage) that are used and not cited in the submitted paper.

**Comment by giswqs** [comment]
@kbarnhart Thank you for handling the submission. I have revised the repo according to your comments. Thanks. 

- Added docstrings to all functions and classes ([link](https://lidar.readthedocs.io/en/latest/lidar.html#submodules))
- Added tests ([link](https://github.com/giswqs/lidar/blob/master/tests/test_lidar.py)) and GitHub actions ([link](https://github.com/giswqs/lidar/runs/1651187012?check_suite_focus=true))
- Cited dependencies ([link](https://github.com/giswqs/lidar/blob/master/paper/paper.md#acknowledgments))

The [lidar/toolbox/scripts/1_Extract_Sink.py](https://github.com/giswqs/lidar/blob/master/lidar/toolbox/scripts/1_Extract_Sink.py) and [lidar/toolbox/scripts/4_Slicing.py](https://github.com/giswqs/lidar/blob/master/lidar/toolbox/scripts/4_Slicing.py) are intended as the arcpy equivalent of [lidar/filling.py](https://github.com/giswqs/lidar/blob/master/lidar/filling.py) and [lidar/slicing.py](https://github.com/giswqs/lidar/blob/master/lidar/slicing.py), respectively. The other five scripts (i.e., 2_Delineate_Catchment.py, 3_Flow_Path.py, 5_Catchment_Hierarchy.py, 6_Simulate Inundation.py, 7_Play_Animation.py) are for the arcpy toolbox only as they rely on some arcpy functions, which are not available outside arcpy.

**Comment by giswqs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02896/joss.02896/10.21105.joss.02896.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02896/joss.02896/10.21105.joss.02896.pdf) :page_facing_up: :point_left:

**Comment by kbarnhart** [comment]
@giswqs thanks for that update. Could you please recommend reviewers for this submission. A list of people who have volunteered to review for JOSS is listed above. Of course, don't feel constrained to that list. 

In addition, is the Arc Spatial Analyst extension is the only Arc extension required to use the toolbox? I skimmed for `arcpy.CheckOutExtension` and only saw "Spatial". I want to make sure to find reviewers who have access to the correct Arc licenses.

**Comment by giswqs** [comment]
@kbarnhart Here are some potential reviewers from that list with expertise in GIS and Python. And yes, the toolbox only requires the Spatial Analyst extension. Thanks. 

- sgrieve
- Scivision
- juliohm
- sjsrey
- mikejohnson51
- nagellette
- Narayana-Rao

**Comment by kbarnhart** [comment]
@giswqs thanks for confirming the Arc license requirements and recommending reviewers.

**Comment by kbarnhart** [comment]
:wave: @sgrieve @laijingtao @mikejohnson51 @r-barnes would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This submission includes an ArcGIS toolbox, as well as a python package that implements similar functionality. Thus, it is important that at least one (ideally all) reviewers have access to the proprietary environment ArcGIS and the Spatial Analyst extension. For reference, [here is a link](https://joss.readthedocs.io/en/latest/review_criteria.html#what-about-submissions-that-rely-upon-proprietary-languages-development-environments) to the JOSS documentation statement regarding submissions which include proprietary languages/environments. 

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers are found, I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by laijingtao** [comment]
@kbarnhart Hi Katy, I'm happy to review this submission. Looks like an interesting work. I don't have access to ArcGIS right now so I'll focus on the Python implementation. Hope that's okay.

**Comment by kbarnhart** [comment]
@laijingtao thank you for your willingness to review and for letting me know about your Arc access. Focusing on the python implementation would be great and I'll make sure at least one other reviewer has access to Arc. I'll add you as a reviewer now, but won't make the JOSS review issue (which will have checkboxes to guide you through the review) until I've found another reviewer.

**Comment by kbarnhart** [comment]
@whedon add @laijingtao as reviewer

**Comment by whedon** [comment]
OK, @laijingtao is now a reviewer

**Comment by kbarnhart** [comment]
:wave: @sgrieve @mikejohnson51 @r-barnes would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission is "lidar: A Python package for terrain and hydrological analysis using digital elevation models".

This submission includes an ArcGIS toolbox, as well as a python package that implements similar functionality. Thus, it is important that at least one (ideally all) reviewers have access to the proprietary environment ArcGIS and the Spatial Analyst extension. For reference, [here is a link](https://joss.readthedocs.io/en/latest/review_criteria.html#what-about-submissions-that-rely-upon-proprietary-languages-development-environments) to the JOSS documentation statement regarding submissions which include proprietary languages/environments. 

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers are found, I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by mikejohnson51** [comment]
@kbarnhart I have very little experience with python and no access to ArcGIS, if you are unable to find others I would be willing to do my best!

**Comment by sgrieve** [comment]
@kbarnhart Afraid I don't have any spare capacity to review at the moment, and due to the pandemic I don't have access to an ArcGIS licence. London is supposed to come out of lockdown by mid Feb, so give me a shout then if you have not found anyone else and I might be able to take a look.

**Comment by kbarnhart** [comment]
@mikejohnson51 and @sgrieve thanks for the info and updates. I'll keep looking for a second reviewer who has access to Arc.

**Comment by kbarnhart** [comment]
:wave: @cheginit @juliohm @Hedrick-ARS would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission is "lidar: A Python package for terrain and hydrological analysis using digital elevation models".

This submission includes an ArcGIS toolbox, as well as a python package that implements similar functionality. Thus, it is important that at least one (ideally all) reviewers have access to the proprietary environment ArcGIS and the Spatial Analyst extension. For reference, [here is a link](https://joss.readthedocs.io/en/latest/review_criteria.html#what-about-submissions-that-rely-upon-proprietary-languages-development-environments) to the JOSS documentation statement regarding submissions which include proprietary languages/environments. 

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers are found, I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by juliohm** [comment]
Dear all, unfortunately I can't review the submission. I don't have access
to the proprietary software and haven't used Python in a while.

Thank you,
-Júlio

**Comment by cheginit** [comment]
@kbarnhart I am a Python developer but don't have access to ArcGIS. So I can review the non-ArcGIS parts of the submission. Please, let me know if that works.

**Comment by r-barnes** [comment]
I could take a look, but I don't have access to ArcGIS.

**Comment by kbarnhart** [comment]
@juliohm - thanks for the response

@cheginit and @r-barnes thanks for your willingness to review. Via email discussions, I think that I've now found a third reviewer with access to Arc, but am still confirming with them. 

Thus only one you is needed as a reviewer. I'll add @cheginit as a reviewer because @r-barnes has done a review for me somewhat recently (thank you!) and then start the review issue once I can confirm the final reviewer.

**Comment by kbarnhart** [comment]
@whedon add @cheginit as reviewer

**Comment by whedon** [comment]
OK, @cheginit is now a reviewer

**Comment by kbarnhart** [comment]
@amanaster2 has confirmed that she is willing to review and has access to Arc so I will now add her and start the review.

**Comment by kbarnhart** [comment]
@whedon add @amanaster2 as reviewer

**Comment by whedon** [comment]
OK, @amanaster2 is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2965.

**Comment by r-barnes** [comment]
@kbarnhart : I appreciate your choice of the alternate reviewer here. I should be more free to look at things again in a month or so. I hope your 2021 is off to a good start!

**Comment by kbarnhart** [comment]
Thanks @r-barnes, same to you!
