### ISSUE TITLE
[PRE REVIEW]: NLMech: Implementation of finite difference/meshfreediscretization of nonlocal fracture models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2898]
**Submitting author:** @diehlpk (<a href="http://orcid.org/0000-0003-3922-8419">Patrick Diehl</a>)
**Repository:** <a href="https://github.com/nonlocalmodels/NLMech" target ="_blank">https://github.com/nonlocalmodels/NLMech</a>
**Version:** v0.1.0-rc1
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @vijaysm, @chennachaos
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @diehlpk. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@diehlpk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2898 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.43 s (479.5 files/s, 81268.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             56           2858           2882          11612
C/C++ Header                    74           2279           7950           4521
YAML                            27             16            253            950
CMake                           24            121            198            299
Markdown                        11            114              0            186
XML                              5              0              0            147
GLSL                             1              0              0             47
Bourne Shell                     4             24             30             37
MATLAB                           1              6              7             24
Dockerfile                       1              5              4              4
-------------------------------------------------------------------------------
SUM:                           204           5423          11324          17827
-------------------------------------------------------------------------------


Statistical information for the repository 'dc9d8d1a0d42903081acad72' was
gathered on 2020/12/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Patrick                         47          4404           2861            0.53
Patrick Diehl                   25          8705         638851           46.99
Prashant K. Jha                 46         18323           9250            2.00
Prashant Kumar Jha              56        675356          20302           50.48

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Patrick                    2212           50.2          5.9               22.92
Patrick Diehl              5090           58.5         10.2               36.70
Prashant K. Jha           10779           58.8         10.5               32.80
Prashant Kumar Jha        14021            2.1         19.3               35.18
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02898/joss.02898/10.21105.joss.02898.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02898/joss.02898/10.21105.joss.02898.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@ilyasst, @ctdegroot @chennachaos @tjhei, @vijaysm, @likask would you be interested in reviewing this work for JOSS? It features nonlocal fracture models and finite difference/meshfree methods. 

FYI we can be flexible the coming month regarding timing (since it is a holiday season for many), so if you are able to accept this invitation but start review at a later time, or take quite a bit more time than usual, that is fine too. Thanks!

I realize I've invited some of you for multiple submissions. We are really thankful for your review efforts. Please do let me know if you feel you are receiving too many invites from us.

**Comment by vijaysm** [comment]
@Kevin-Mattheus-Moerman I am available for review.

**Comment by ilyasst** [comment]
I am interested in the subject of this publication and can review it in the following weeks. However, I'd like to check with you @Kevin-Mattheus-Moerman that there is no conflict of interest here as I know @diehlpk quite well. We have worked together in the past (same lab for some time) and are currently collaborating on some projects.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @vijaysm as reviewer

**Comment by whedon** [comment]
OK, @vijaysm is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
> I am interested in the subject of this publication and can review it in the following weeks. However, I'd like to check with you @Kevin-Mattheus-Moerman that there is no conflict of interest here as I know @diehlpk quite well. We have worked together in the past (same lab for some time) and are currently collaborating on some projects.

@ilyasst thanks for letting us know. We would unfortunately classify that as a conflict of interest so I will look for alternative reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ctdegroot @chennachaos @tjhei, @likask would you be interested in reviewing this work for JOSS? It features nonlocal fracture models and finite difference/meshfree methods.

FYI we can be flexible the coming month regarding timing (since it is a holiday season for many), so if you are able to accept this invitation but start review at a later time, or take quite a bit more time than usual, that is fine too. Thanks!

I realize I've invited some of you for multiple submissions. We are really thankful for your review efforts. Please do let me know if you feel you are receiving too many invites from us.

**Comment by chennachaos** [comment]
Hi @Kevin-Mattheus-Moerman. Thanks for the invitation!
I am occupied with other assignments in the next couple of months. I will not be able to carry out the review at least until the beginning of February. If that's fine with you, then you can add me as a reviewer for this one.

**Comment by Kevin-Mattheus-Moerman** [comment]
Great @chennachaos. I'll add you for now and I'll look for more reviewers too. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @chennachaos as reviewer

**Comment by whedon** [comment]
OK, @chennachaos is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@diehlpk do you have any suggestions for reviewers at this point?

**Comment by diehlpk** [comment]
@Kevin-Mattheus-Moerman  Maybe: mlparks or djlittl or johntfoster or jamitch-snl could be some potential reviewers.

**Comment by tjhei** [comment]
> @tjhei would you be interested in reviewing this work for JOSS?

The next 2-3 months are quite inconvenient for me. Sorry.

**Comment by diehlpk** [comment]
@Kevin-Mattheus-Moerman One more potential reviewer: jritta

**Comment by Kevin-Mattheus-Moerman** [comment]
@ctdegroot, @likask, @jritta would you be interested in reviewing this work for [JOSS](https://joss.theoj.org)? It features nonlocal fracture models and finite difference/meshfree methods.

The review focuses on [the software](https://github.com/nonlocalmodels/NLMech) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02898/joss.02898/10.21105.joss.02898.pdf). 

This is a pre-review issue in which we find and assign editors/reviewers. Once sufficient reviewers are recruited a dedicated review issue is opened. 

Let me know if you are interested. Thanks, and best wishes for 2021!

**Comment by diehlpk** [comment]
@Kevin-Mattheus-Moerman Maybe Prakash, Naveen or Ross, Stewart could be some potential reviewers. However, I could not find them easily on GitHub.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ctdegroot, @likask, @jritta would you be interested in reviewing this work for [JOSS](https://joss.theoj.org)? It features nonlocal fracture models and finite difference/meshfree methods.

The review focuses on [the software](https://github.com/nonlocalmodels/NLMech) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.02898/joss.02898/10.21105.joss.02898.pdf). 

This is a pre-review issue in which we find and assign editors/reviewers. Once sufficient reviewers are recruited a dedicated review issue is opened. 

Let me know if you are interested. Thanks, and best wishes for 2021!

**Comment by diehlpk** [comment]
@Kevin-Mattheus-Moerman Should I recommend more reviewers?

**Comment by ctdegroot** [comment]
Normally I would say yes, but I have another JOSS review in progress at this time, so I can't commit to finishing this in a timely manner. Best of luck!

**Comment by diehlpk** [comment]
@Kevin-Mattheus-Moerman Should I recommend more reviewers?

**Comment by Kevin-Mattheus-Moerman** [comment]
@ctdegroot no worries. This review will be ongoing for a bit. If you'd like me to add you now but provide you with more time that works for us too. I'll start the review now but let me know if you could help with extra time provided. Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3020.

**Comment by Kevin-Mattheus-Moerman** [comment]
@diehlpk Apologies for the delay encountered. We'll start review now.

**Comment by diehlpk** [comment]
@Kevin-Mattheus-Moerman No worries, thank you.
