### ISSUE TITLE
[PRE REVIEW]: vICC: Varying Intraclass Correlation Coefficients in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2902]
**Submitting author:** @donaldRwilliams (<a href="http://orcid.org/0000-0001-6735-8785">Donald Williams </a>)
**Repository:** <a href="https://github.com/donaldRwilliams/vICC" target ="_blank">https://github.com/donaldRwilliams/vICC</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @donaldRwilliams. **Currently, there isn't an JOSS editor assigned** to your paper.

@donaldRwilliams if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (102.5 files/s, 14313.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               12            247            473            919
Markdown                         2            106              0            303
TeX                              1              5              0             63
YAML                             1              4              0              9
Rmd                              1             59            180              6
-------------------------------------------------------------------------------
SUM:                            17            421            653           1300
-------------------------------------------------------------------------------


Statistical information for the repository '56d9880353a4586fbeb6d288' was
gathered on 2020/12/11.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3758/s13428-015-0623-y is OK
- 10.1214/09-BA403 is OK

MISSING DOIs

- 10.3758/s13428-017-0935-1 may be a valid DOI for title: The reliability paradox: Why robust cognitive tasks do not produce reliable individual differences
- 10.31234/osf.io/hpq7w may be a valid DOI for title: Putting the Individual into Reliability: Bayesian Testing of Homogeneous Within-Person Variance in Hierarchical Models
- 10.31234/osf.io/2ux7t may be a valid DOI for title: A Fine-Tooth Comb for Measurement Reliability: Predicting True Score and Error Variance in Hierarchical Models

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02902/joss.02902/10.21105.joss.02902.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02902/joss.02902/10.21105.joss.02902.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@donaldRwilliams thanks for this submission. Since the core functionality appears to be under 1000 lines of code I have flagged this submission for an additional scope check by the editorial board. In particular our board will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. This is standard for submissions of this size. We should get back to you within about a week.

**Comment by Kevin-Mattheus-Moerman** [comment]
@donaldRwilliams we have not detected an [OSI approved license](https://opensource.org/licenses) for this work, which is a requirement. Please add one. It is recommended to have this in a plain text file e.g. as a LICENSE file (which will also help GitHub pick up on it so it renders a license badge on your repo).

**Comment by donaldRwilliams** [comment]
> @donaldRwilliams thanks for this submission. Since the core functionality appears to be under 1000 lines of code I have flagged this submission for an additional scope check by the editorial board. In particular our board will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. This is standard for submissions of this size. We should get back to you within about a week.

@Kevin-Mattheus-Moerman 

I see the concern about the number of lines of code. However, I would like to note that the methodology is novel and there is a paper of over 8,000 words about to be accepted into the methods journal Behavioral Research Methods. Hence, this underlying idea behind the method, the 8000 words paper, and the software, I think, is a substantial contribution.

Here is the pre-print: https://psyarxiv.com/hpq7w/

**Comment by donaldRwilliams** [comment]
> @donaldRwilliams we have not detected an [OSI approved license](https://opensource.org/licenses) for this work, which is a requirement. Please add one. It is recommended to have this in a plain text file e.g. as a LICENSE file (which will also help GitHub pick up on it so it renders a license badge on your repo).

I have added the license.

**Comment by donaldRwilliams** [comment]
> ```
> Reference check summary (note 'MISSING' DOIs are suggestions that need verification):
> 
> OK DOIs
> 
> - 10.3758/s13428-015-0623-y is OK
> - 10.1214/09-BA403 is OK
> 
> MISSING DOIs
> 
> - 10.3758/s13428-017-0935-1 may be a valid DOI for title: The reliability paradox: Why robust cognitive tasks do not produce reliable individual differences
> - 10.31234/osf.io/hpq7w may be a valid DOI for title: Putting the Individual into Reliability: Bayesian Testing of Homogeneous Within-Person Variance in Hierarchical Models
> - 10.31234/osf.io/2ux7t may be a valid DOI for title: A Fine-Tooth Comb for Measurement Reliability: Predicting True Score and Error Variance in Hierarchical Models
> 
> INVALID DOIs
> 
> - None
> ```

I have added the DOIs

**Comment by donaldRwilliams** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02902/joss.02902/10.21105.joss.02902.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02902/joss.02902/10.21105.joss.02902.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @donaldRwilliams. Thank you for your submission. However, the JOSS editorial board has determined that it does not meet the bar of [_substantial scholarly effort_](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort), especially as it looks to be mostly a wrapper.

If you continue to develop this work, we would be happy to reconsider it as a submission in the future. One possible alternative to JOSS is to follow GitHub's guide on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by donaldRwilliams** [comment]
@kthyng 

Thank you for this quick decision. However, I am a bit confused by the decision. The package is not a wrapper, not at all. The package in fact contains custom models for novel methodology that we recently introduced to the quantitative psychological literature.

The paper introducing the methodology is to be published in the journal Behavior Research Methods.  This is the software implementation for those methods, which are already being used by other researchers.

**Comment by kthyng** [comment]
@donaldRwilliams When a submission is labeled with query-scope, we have a process behind the scenes where members of the editorial board inspect the submission and vote on it going to review or not. The AEiC on rotation manually inspects and decides to add the query-scope label (or not), and then it goes to the board for further manual checks of the scope. We require at least two additional board members to concur on a desk rejection (as is typical at other journals).

In addition to the possibility of a submission being a wrapper, one proxy that we have developed to represent substantial scholarly effort is the amount of time spent developing a project, with 3 months or less of development time taken as a trigger for further inspection by the board. This repository is borderline for lines of code, but the development time implies a lack of scholarly effort that we are looking for in JOSS submissions.

We are mindful that JOSS gives a "publication credit" for the software, and continue to be regarded as a valid and equal counterpart to traditional journals, for which reason we are constantly discussing our criteria and refining our process. Like editors at other journals, we have to draw a line somewhere for what we consider a "minimum publishable unit." Note that your overall work with your other paper and research is probably a substantial scholarly effort, however, that doesn't mean the software component on its own is.

Please consider whether this software can be made part of a larger package providing additional functionality, and which would make for a submission that passes that bar, or alternatively, consider getting a DOI for this software via, e.g., Zenodo.

**Comment by donaldRwilliams** [comment]
@kthyng 
Thanks for the quick response.

Note that perhaps the software itself does not warrant publication in JOSS, but programming the models in the first place certainly took many months of scholarly effort ironing out kinks, making sure they work right, etc.. And if the commit history is being used to track the scholarly time, note that lots of the code was written in stand-alone files for the non-software paper and was a matter of placing that code into the package. This is why it was done so quickly, if looking at the commit history.

"Please consider whether this software can be made part of a larger package providing additional functionality"

There is no software in any language that implements these models.
