### ISSUE TITLE
[PRE REVIEW]: ForestAtRisk: A Python package for modelling and forecasting deforestation in the tropics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2903]
**Submitting author:** @ghislainv (<a href="http://orcid.org/0000-0002-1685-4997">Ghislain Vieilledent</a>)
**Repository:** <a href="https://github.com/ghislainv/forestatrisk" target ="_blank">https://github.com/ghislainv/forestatrisk</a>
**Version:** v0.2
**Editor:** @kbarnhart
**Reviewers:** @molgor, @ethanwhite
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ghislainv. **Currently, there isn't an JOSS editor assigned** to your paper.

@ghislainv if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.00 s (133.6 files/s, 48544.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            45           3075              0          14817
JavaScript                       9           2289           2314           8440
Python                          38           1138           2170           3149
TeX                              3            129             59           1771
CSS                              4            328             49           1271
C                                2            161            267           1068
reStructuredText                17            245            188            691
Jupyter Notebook                 3              0           3062            521
SVG                              2              0              0            472
Bourne Shell                     3             80            123            233
YAML                             3             34             27            165
XML                              1              0              0            162
Markdown                         1             24              0             80
JSON                             1              0              0             23
C/C++ Header                     1              2              9             13
make                             1              5              7             12
-------------------------------------------------------------------------------
SUM:                           134           7510           8275          32888
-------------------------------------------------------------------------------


Statistical information for the repository '057d315986e3cb629a7ed120' was
gathered on 2020/12/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ghislain Vieilledent           309         28607           7599           99.97
ghislainv                        1            12              0            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ghislain Vieilledent      21020           73.5          5.7               19.76
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02903/joss.02903/10.21105.joss.02903.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02903/joss.02903/10.21105.joss.02903.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-319-60801-3_36 is OK
- 10.1016/S0304-3800(02)00059-5 is OK
- 10.1111/j.1461-0248.2004.00702.x is OK
- 10.1126/science.aam5962 is OK
- 10.1101/2020.09.17.295774 is OK
- 10.1016/j.envsoft.2013.09.010 is OK
- 10.5281/zenodo.3553579 is OK
- 10.1201/b10905-5 is OK
- 10.1007/s10980-009-9355-7 is OK

MISSING DOIs

- 10.1007/bf00116466 may be a valid DOI for title: Bayesian image restoration, with two applications in spatial statistics
- 10.1126/science.293.5530.657 may be a valid DOI for title: Ecological forecasts: An emerging imperative

INVALID DOIs

- https://doi.org/10.1016/j.foreco.2015.06.014 is INVALID because of 'https://doi.org/' prefix
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@ghislainv thanks for this submission. I will be helping to find a handling editor for this submission. In the mean time can you please have a look at the above :point_up: DOI checks? If you want to update your paper simply call:
`@whedon generate pdf` in a comment here.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jni @leouieda @kbarnhart could one of you handle this submission? Thanks

**Comment by jni** [comment]
@Kevin-Mattheus-Moerman, I'm about to go on leave for a month, so I'm just trying to wrap up the papers I have in flight right now. If no one has picked this up by mid-January I'm happy to step in then.

**Comment by ghislainv** [comment]
@Kevin-Mattheus-Moerman, thank you for handling my submission. I have corrected the DOIs (see ghislainv/forestatrisk@e82b240635446b65b3f598c30302760efbeac752) and will generate a new pdf will `whedon`.

**Comment by ghislainv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02903/joss.02903/10.21105.joss.02903.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02903/joss.02903/10.21105.joss.02903.pdf) :page_facing_up: :point_left:

**Comment by kbarnhart** [comment]
@Kevin-Mattheus-Moerman I could take this on in January (swamped for the next week, then OOO with no email for almost two).

**Comment by Kevin-Mattheus-Moerman** [comment]
@kbarnhart that is fine. If it is okay I'll assign you for now and you can just list yourself as OOO here

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
@Kevin-Mattheus-Moerman sounds good. Thanks. 

@ghislainv I'll handle this submission starting in early January.

**Comment by ghislainv** [comment]
@kbarnhart, that's perfectly fine with me. Thanks for considering my manuscript/software.

**Comment by ghislainv** [comment]
Correcting typos in paper's summary: @whedon generate pdf

**Comment by ghislainv** [comment]
Correcting typos in paper's summary.

**Comment by ghislainv** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02903/joss.02903/10.21105.joss.02903.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02903/joss.02903/10.21105.joss.02903.pdf) :page_facing_up: :point_left:

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by kbarnhart** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.1007/bf00116466 is OK
- 10.1007/978-3-319-60801-3_36 is OK
- 10.1016/S0304-3800(02)00059-5 is OK
- 10.1111/j.1461-0248.2004.00702.x is OK
- 10.1038/nature10425 is OK
- 10.1126/science.aam5962 is OK
- 10.1126/science.293.5530.657 is OK
- 10.1016/j.foreco.2015.06.014 is OK
- 10.1101/2020.09.17.295774 is OK
- 10.1111/j.1755-263X.2008.00027.x is OK
- 10.1016/j.envsoft.2013.09.010 is OK
- 10.1038/nature04389 is OK
- 10.5281/zenodo.3553579 is OK
- 10.1201/b10905-5 is OK
- 10.1007/s10980-009-9355-7 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02903/joss.02903/10.21105.joss.02903.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02903/joss.02903/10.21105.joss.02903.pdf) :page_facing_up: :point_left:

**Comment by kbarnhart** [comment]
@ghislainv  Thanks for your submission. I'll now start actively handling it. 

If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

In addition, here are a few minor comments that I would recommend addressing before review begins. 
- [ ] As part of the review process, reviewers will need to assess whether it is possible to test the software to verify it has been installed/compiled correctly. I would recommend adding instructions describing how a user might do do this. 
- [ ] Reviewers will also assess community guidelines regarding the following tasks: 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support. I would recommend adding statements for community guidelines to the repo. 

If you have any questions about the JOSS review process, or clarifications about the above comments please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by ghislainv** [comment]
@kbarnhart Thanks for handling the submission. I am out of office until Monday 11th of January. I will address your two minor comments as soon as possible next week. Regarding the potential reviewers, I would suggest: molgor, kmarkert, leouieda, martinfleis, and bradyrx.

**Comment by kbarnhart** [comment]
:wave: @molgor, @kmarkert, @martinfleis, and @bradyrx, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by martinfleis** [comment]
@kbarnhart the scope seems to be quite distant from what I normally do. I am not entirely comfortable reviewing this. Sorry.

**Comment by kbarnhart** [comment]
@martinfleis thank you for your prompt response.

**Comment by bradyrx** [comment]
@kbarnhart, this looks like a really cool package. However, I just defended my PhD and got started up last week in a new position at a company. I'll be plenty swamped with onboarding and getting spun up with the team for awhile. I'll have to evaluate after a few months there if I have time to still review at JOSS, but will update you all once I know better there. Best of luck, @ghislainv!

**Comment by ghislainv** [comment]
@bradyrx, thanks and good luck with your new position!

@kbarnhart, in response to your first comments, I have included two new sections: "Installation testing" and "Contributing" in the README file of the project. Also, as potential reviewers, I would add @ ecodiv, and @ NikosAlexandris. They are not in the [list of people](https://bit.ly/joss-reviewers) who have already agreed to review for JOSS.

**Comment by kbarnhart** [comment]
@bradyrx congratulations on defending and thanks for the update. 

@ghislainv thanks for the additional reviewer recommendations.

**Comment by kbarnhart** [comment]
:wave: @molgor, @kmarkert, @ethanwhite @ecodiv would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission is "ForestAtRisk: A Python package for modelling and forecasting deforestation in the tropics".

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by molgor** [comment]
Hi Kathy,I can do it. It would be my first time to review in the JOSS, so I might bug you with some questions. Best,JuanEl 14/01/2021, a las 13:33, Katy Barnhart <notifications@github.com> escribió:👋 @molgor, @KMarkert, @ethanwhite @ecodiv would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.htmlThe submission is "ForestAtRisk: A Python package for modelling and forecasting deforestation in the tropics".This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").If you are interested in reviewing, I would recommend looking over the journal's conflict of interest policy before the review process starts.If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kbarnhart** [comment]
@molgor thanks so much for your willingness to review (and apologies for the delay in my response). Of course you can ask me any questions about the process. 

I will now add you as a reviewer. I'll start the official review issue once I find one to two more reviewers.

**Comment by kbarnhart** [comment]
@whedon add @molgor as reviewer

**Comment by whedon** [comment]
OK, @molgor is now a reviewer

**Comment by kbarnhart** [comment]
:wave: @kmarkert, @ethanwhite @ecodiv would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission is "ForestAtRisk: A Python package for modelling and forecasting deforestation in the tropics".

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by molgor** [comment]
Hi Katy,

It’s no problem.

Best,

Juan

**Comment by ethanwhite** [comment]
@kbarnhart - Yes, I'd be happy to review this. Thanks for having the longer 6 week timeline right now. Makes it easier to say yes in the midst of everything.

**Comment by kbarnhart** [comment]
@ethanwhite thanks for being willing to review! I'll add you as a reviewer and then start the official review issue.

**Comment by kbarnhart** [comment]
@whedon add @ethanwhite as reviewer

**Comment by whedon** [comment]
OK, @ethanwhite is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2975.
