### ISSUE TITLE
[PRE REVIEW]: Correlation: An Analyzing Tool for Liquids and for Amorphous Solids

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2904]
**Submitting author:** @Isurwars (<a href="http://orcid.org/0000-0002-4359-2742">Isaías Rodríguez</a>)
**Repository:** <a href="https://github.com/Isurwars/Correlation/" target ="_blank">https://github.com/Isurwars/Correlation/</a>
**Version:** v1.0.0
**Editor:** @jgostick
**Reviewers:** @awvwgk
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Isurwars. **Currently, there isn't an JOSS editor assigned** to your paper.

@Isurwars if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (372.1 files/s, 62374.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              5            249            312           1169
TeX                              1             21              0            260
XML                              1              0              0            157
Markdown                         2             80              0            152
C/C++ Header                     4             14             45            102
YAML                             2              7              8             48
make                             1             16              0             42
-------------------------------------------------------------------------------
SUM:                            16            387            365           1930
-------------------------------------------------------------------------------


Statistical information for the repository '9adbc48bbb28efdb6a43631a' was
gathered on 2020/12/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Isurwars                        20          2156            265          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Isurwars                   1891           87.7          2.1               19.09
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02904/joss.02904/10.21105.joss.02904.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02904/joss.02904/10.21105.joss.02904.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevB.100.024422 is OK
- 10.1002/chem.200800987 is OK
- 10.3390/ma4040716 is OK
- 10.1016/j.physb.2015.07.027 is OK
- 10.1039/tf9373300027 is OK
- 10.1088/0305-4608/12/11/001 is OK
- 10.1098/rspa.1964.0147 is OK
- 10.3390/ecm-2-B001 is OK
- 10.1371/journal.pone.0147645 is OK

MISSING DOIs

- 10.1016/0025-5416(82)90073-8 may be a valid DOI for title: The structure of non-crystalline materials: liquids and amorphous solids
- 10.1063/1.2914122 may be a valid DOI for title: Models of disorder: the theoretical physics of homogeneously disordered systems

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@Isurwars thanks for this submission. Since the core functionality appears to be close to a 1000 lines of code I have flagged this submission for an additional scope check by the editorial board. In particular our board will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. This is standard for submissions of this size. We should get back to you within about a week.

**Comment by kthyng** [comment]
@jgostick are you able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @jgostick as editor

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by arfon** [comment]
:wave: @jgostick - just a friendly reminder to respond here when you get a chance.

**Comment by jgostick** [comment]
hmmm, I must've missed the invite.

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by jgostick** [comment]
I'm still searching for reviewers. Sorry for the delay.

**Comment by jgostick** [comment]
@whedon assign @awvwgk as reviewer

**Comment by whedon** [comment]
OK, @awvwgk is now a reviewer

**Comment by awvwgk** [comment]
I already briefly checked the project and reported issues while checking for the robustness of the user interface (see https://github.com/Isurwars/Correlation/issues/1 and https://github.com/Isurwars/Correlation/issues/2).

**Comment by jgostick** [comment]
I guess I will start the review, then I'll just add the second reviewer if/when I find someone

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2976.
