### ISSUE TITLE
[PRE REVIEW]: FixedPointAcceleration: A Julia package for accelerating convergence of fixed point problems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2905]
**Submitting author:** @s-baumann (<a href="http://orcid.org/0000-0002-9657-0969">Stuart Baumann</a>)
**Repository:** <a href="https://github.com/s-baumann/FixedPointAcceleration.jl" target ="_blank">https://github.com/s-baumann/FixedPointAcceleration.jl</a>
**Version:** v0.3.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @s-baumann. **Currently, there isn't an JOSS editor assigned** to your paper.

@s-baumann if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (806.8 files/s, 65374.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           16             54            112            925
Markdown                        10            206              0            686
TeX                              2             40              0            272
TOML                             3             55              1            216
YAML                             1              5              2             19
-------------------------------------------------------------------------------
SUM:                            32            360            115           2118
-------------------------------------------------------------------------------


Statistical information for the repository '9a82f8cd2bf805f82ba25d06' was
gathered on 2020/12/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Stuart Baumann                   2            25             25          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2905 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Stuart Baumann, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-54ca145bf448/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.32614/RJ-2019-037 is OK

MISSING DOIs

- 10.2172/1240289 may be a valid DOI for title: Anderson acceleration for fixed-point iterations
- 10.1145/321296.321305 may be a valid DOI for title: Iterative procedures for nonlinear integral equations
- 10.1137/0713060 may be a valid DOI for title: A Polynomial Extrapolation Method for Finding Limits and Antilimits of Vector Sequences
- 10.1090/s0025-5718-1962-0145647-x may be a valid DOI for title: Acceleration techniques for iterated vector and matrix problems

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@s-baumann thanks for this submission. Since the core functionality appears to be ~1000 lines of code I have flagged this submission for an additional scope check by the editorial board. In particular our board will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. This is standard for submissions of this size. We should get back to you within about a week.

**Comment by kthyng** [comment]
Hi @s-baumann, thank you for submission. Unfortunately, our editorial board has decided that while this package is interesting and looks useful, it is not a large enough contribution for JOSS to review it - see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort. If you continue to develop this work, we would be happy to reconsider it as a submission in the future, or alternatively, consider publishing the software to Zenodo to get a DOI that users can cite.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
