### ISSUE TITLE
[REVIEW]: Augur: a bioinformatics toolkit for phylogenetic analyses of human pathogens

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2906]
**Submitting author:** @huddlej (<a href="http://orcid.org/0000-0002-4250-2063">John Huddleston</a>)
**Repository:** <a href="https://github.com/nextstrain/augur/" target ="_blank">https://github.com/nextstrain/augur/</a>
**Version:** 10.2.0
**Editor:** @majensen
**Reviewer:** @dcnickle, @Maghnuso
**Archive:** <a href="https://doi.org/10.5281/zenodo.4421955" target="_blank">10.5281/zenodo.4421955</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6bc9f6bf0d5722b9b9710315a1807548/status.svg)](https://joss.theoj.org/papers/6bc9f6bf0d5722b9b9710315a1807548)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6bc9f6bf0d5722b9b9710315a1807548"><img src="https://joss.theoj.org/papers/6bc9f6bf0d5722b9b9710315a1807548/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6bc9f6bf0d5722b9b9710315a1807548/status.svg)](https://joss.theoj.org/papers/6bc9f6bf0d5722b9b9710315a1807548)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nextstrain/augur/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dcnickle & @Maghnuso, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @majensen know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nextstrain/augur/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@huddlej) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nextstrain/augur/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@huddlej) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dcnickle, @Maghnuso it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.20944/preprints202008.0220.v1 is OK
- 10.2807/1560-7917.ES.2020.25.32.2001410 is OK
- 10.1186/s13059-015-0726-x is OK
- 10.1371/journal.pone.0009490 is OK
- 10.1093/bioinformatics/btu033 is OK
- 10.1038/s41591-020-0935-z is OK
- 10.1126/science.abc0523 is OK
- 10.1093/bioinformatics/bty407 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1093/bioinformatics/btr509 is OK
- 10.1093/nar/gkf436 is OK
- 10.1093/molbev/msu300 is OK
- 10.1093/ve/vex042 is OK

MISSING DOIs

- 10.1093/bioinformatics/btv381 may be a valid DOI for title: nextflu: real-time tracking of seasonal influenza virus evolution in humans.
- 10.1093/bioinformatics/bts480 may be a valid DOI for title: Snakemake—a scalable bioinformatics workflow engine

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02906/joss.02906/10.21105.joss.02906.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02906/joss.02906/10.21105.joss.02906.pdf) :page_facing_up: :point_left:

**Comment by DavidNickle** [comment]
**Conflict of interest:** I confirm that I have read the JOSS conflict of interest policy and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.
Code of Conduct

**Repository:** The source code for this software is available at the repository url

**License:** The repository containa a plain-text LICENSE file with the contents of an OSI approved software license.

**Contribution and authorship:** The submitting author made major contributions to the software and the full list of paper authors seem appropriate and complete.

**Functionality:** The software is functional and important adding very important knowledge to the public domain

**Installation:** The installation procedure follows the documentation clearly.  I performed all the task in the Zika_Tuotrial

**Functionality:** I confirmed the functional claims of the on the tutorial data as well as some of my own.

**Performance:** No claims here but it is pretty quick!

**A statement of need:** The authors have a clear audience in mine and the paper and the software should be readably available to that audience.

**Installation instructions:** I ran into an error that clearly was my own (may conda app and phython3 where out of date)! Updated and everything worked including all of the dependencies which are all clearly stated.

**Example usage:** I went through the zika_tutorial and all the functionality worked.  I found this to be fantastic exercise and I will be using Nexstrain in my workflows going forward.

**Automated tests:** YES — tests are available 
Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support. **YES**

**Software paper:** **YES**

Summary: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided? **YES**

**A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is? **YES**

**State of the field:** Do the authors describe how this software compares to other commonly-used packages? YES
Quality of writing: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)? YES
References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax? **YES**

Lastly, I would like to state that is a piece of scientific coding that is very useful especially to field of phylogenetic and epidemiology. It drives towards the mantra of repeatable results with code that is highly documented and user friendly to the data scientist. The author's have done an exceptional work at sticking to this theme.

**Comment by Maghnuso** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02906/joss.02906/10.21105.joss.02906.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02906/joss.02906/10.21105.joss.02906.pdf) :page_facing_up: :point_left:

**Comment by Maghnuso** [comment]
Hi @majensen, I can't complete the checklist, I believe that I am logged in and that I had accepted the invitation, but perhaps I need to be invited again?

**Comment by majensen** [comment]
That's bizarre @Maghnuso - I see you are officially in the review so I doubt it that's the problem. Maybe trying closing and opening the browser?

**Comment by Maghnuso** [comment]
no luck @majensen! I see that the pre-review was closed immediately after my checklist in the timeline, could that be blocking me?

**Comment by Maghnuso** [comment]
@whedon reference check summary

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by Maghnuso** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Maghnuso** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.20944/preprints202008.0220.v1 is OK
- 10.2807/1560-7917.ES.2020.25.32.2001410 is OK
- 10.1186/s13059-015-0726-x is OK
- 10.1371/journal.pone.0009490 is OK
- 10.1093/bioinformatics/btu033 is OK
- 10.1038/s41591-020-0935-z is OK
- 10.1126/science.abc0523 is OK
- 10.1093/bioinformatics/bty407 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1093/bioinformatics/btr509 is OK
- 10.1093/nar/gkf436 is OK
- 10.1093/molbev/msu300 is OK
- 10.1093/ve/vex042 is OK

MISSING DOIs

- 10.1093/bioinformatics/btv381 may be a valid DOI for title: nextflu: real-time tracking of seasonal influenza virus evolution in humans.
- 10.1093/bioinformatics/bts480 may be a valid DOI for title: Snakemake—a scalable bioinformatics workflow engine

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon re-invite @Maghnuso as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@maghnuso please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by Maghnuso** [comment]
> That's bizarre @Maghnuso - I see you are officially in the review so I doubt it that's the problem. Maybe trying closing and opening the browser?
If it's helpful @majensen, when I try to accept the invitation again, I get the following message "Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account."

**Comment by Maghnuso** [comment]
Thanks @majensen @danielskatz,  it's working for me now!

**Comment by Maghnuso** [comment]
Hi @majensen, all items on my checklist are now completed, so I am happy to accept the paper! Augur was very easy to install, execute and evaluate. The Zika tutorial was fantastic and the paper was well-written and concise. As @DavidNickle stated, this will be a very useful computational tool for epidemiologists going forward that can be more efficiently curated, as the demands of pathogen surveillance increase.

**Comment by majensen** [comment]
@huddlej looks like a home run. I will be doing an editorial check of the paper itself, and this may generate a minor PR with suggestions. 

Can you review @DavidNickle 's issues with needing to update his tools, and maybe add a helpful hint in this regard to the install instructions?

thanks

**Comment by huddlej** [comment]
Thank you, @majensen, for the great news and thank you @DavidNickle and @Maghnuso for the reviews!

@DavidNickle, do you recall the general error you got during the installation process and how you updated your conda and Python 3 versions? We can use the steps you took to update our documentation as @majensen suggests. For example, did you end up needing to update conda itself like so?

```bash
conda update conda
```

Also, just to doublecheck, did you use [the Local Installation guide for Nextstrain](https://docs.nextstrain.org/en/latest/guides/install/local-installation.html#install-augur-auspice-with-conda) or [the Augur-specific installation guide](https://docs.nextstrain.org/en/latest/guides/install/augur_install.html)?

**Comment by DavidNickle** [comment]
I had to do "conda update conda" and then make sure I had py3 was updated too.  I installed both ways, that is to say Nexstrain and Augur specific install.  I ran the Zika tutorial through the Nextstrain install.  All in all it really was not a big issue.  You guys are doing great work and I think this really helps people with reproducible code and analyses.

**Comment by huddlej** [comment]
Thank you for clarifying, @DavidNickle! I've updated both the [Nextstrain installation docs](https://github.com/nextstrain/docs.nextstrain.org/commit/178a0829179848def908d9a8699cad359528ce8e) and [Augur installation docs](https://github.com/nextstrain/augur/pull/655/commits/97cee791938b32ff6a29307b7c0809d995c9e34a) to reflect this issue.

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by majensen** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.20944/preprints202008.0220.v1 is OK
- 10.2807/1560-7917.ES.2020.25.32.2001410 is OK
- 10.1186/s13059-015-0726-x is OK
- 10.1371/journal.pone.0009490 is OK
- 10.1093/bioinformatics/btu033 is OK
- 10.1038/s41591-020-0935-z is OK
- 10.1126/science.abc0523 is OK
- 10.1093/bioinformatics/bty407 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1093/bioinformatics/btr509 is OK
- 10.1093/nar/gkf436 is OK
- 10.1093/molbev/msu300 is OK
- 10.1093/ve/vex042 is OK

MISSING DOIs

- 10.1093/bioinformatics/btv381 may be a valid DOI for title: nextflu: real-time tracking of seasonal influenza virus evolution in humans.
- 10.1093/bioinformatics/bts480 may be a valid DOI for title: Snakemake—a scalable bioinformatics workflow engine

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02906/joss.02906/10.21105.joss.02906.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02906/joss.02906/10.21105.joss.02906.pdf) :page_facing_up: :point_left:

**Comment by majensen** [comment]
@huddlej can you have a look at the "Missing DOIs" in the above (https://github.com/openjournals/joss-reviews/issues/2906#issuecomment-753240297) and see if they are appropriate to incorporate into your bib references? Thanks

**Comment by majensen** [comment]
@huddlej I would like you to consider adding the following committers (not @'ed so they don't get pinged) explicitly to the author list, and then remove the "Augur Contributors" author and make a general acknowledgement in the paper instead.

- kairstenfay
- elebow
- joverlee521
- willingc
- barneypotter24
and possibly
- lmoncla
- sidneymbell
- saikirankv

My rationale is that these folks (many of whom committed more lines or more times that one of your current authors) appear to have contributed:
1. Functionality for new diseases
2. Significant documentation
3. Updates to the use of python and its ecosystem that make the application less homebrew and more pro.

Please consider giving this credit where it is due. Certainly some of that work was free (or let's say, paid forward!). Up to you and your team - I won't dig in my heels.

thanks for your consideration

**Comment by huddlej** [comment]
@majensen The missing DOIs were both correct and helpful. I've added these to the bibliography.

I'll check with the rest of the team about the authorship changes. We weren't sure how to best choose a threshold for authorship and I think folks will be open to these changes. We would also want to consider [danielsoneg](https://github.com/nextstrain/augur/search?q=danielsoneg&type=commits) and groutr in this list, if we go this route.

**Comment by majensen** [comment]
(Maybe for those folks who are/were not directly part of the Hutch or Bioz,  you could give them a direct acknowledgement if they contributed significantly. Hey tell Thomas that both David and I worked for Jim Mullins about a century ago.)

**Comment by huddlej** [comment]
@majensen, we've decided that the best way to acknowledge all contributors without adding unwanted responsibilities to people outside of our team was to add Nextstrain team members as authors and name all other contributors specifically in the acknowledgements.

To this end, we added three authors from the Nextstrain team and added 25 contributors to the acknowledgements. Since we were able to explicitly acknowledge everyone who has contributed code to this project, we removed the "Augur Contributors" item from the author list. All of these changes are now reflected in `master` of our augur repository.

Thank you for asking us to reconsider our authorship and acknowledgements approach here. This has changed my perspective a bit on how to evaluate contributions to a project.

**Comment by majensen** [comment]
@whedon generate pdf

**Comment by majensen** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.20944/preprints202008.0220.v1 is OK
- 10.2807/1560-7917.ES.2020.25.32.2001410 is OK
- 10.1186/s13059-015-0726-x is OK
- 10.1371/journal.pone.0009490 is OK
- 10.1093/bioinformatics/btu033 is OK
- 10.1038/s41591-020-0935-z is OK
- 10.1126/science.abc0523 is OK
- 10.1093/bioinformatics/btv381 is OK
- 10.1093/bioinformatics/bty407 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1093/bioinformatics/btr509 is OK
- 10.1093/nar/gkf436 is OK
- 10.1093/molbev/msu300 is OK
- 10.1093/bioinformatics/bts480 is OK
- 10.1093/ve/vex042 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02906/joss.02906/10.21105.joss.02906.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02906/joss.02906/10.21105.joss.02906.pdf) :page_facing_up: :point_left:

**Comment by majensen** [comment]
@huddlej Thanks very much for your thoughtful consideration; I'm certainly pleased with the team's decision.

Now, the paper looks great. I have no edits, except for the attached patch, which should fix the Alm reference so that it is not whacked by BibTeX. 

Before I perform the incantation to summon the Associate Ed-in-Chief, can I have you create an open archive of your repo on Zenodo, Figshare, or similar (see https://github.com/openjournals/joss-reviews/issues/1839#issuecomment-560048729 for a tutorial if needed). Then report the resulting DOI back here in the thread. JOSS strongly prefers that the authors and the title of the archive match those of the paper. 

Thanks!

[bibpatch.dif.txt](https://github.com/openjournals/joss-reviews/files/5773769/bibpatch.dif.txt)

**Comment by huddlej** [comment]
Thank you for the citation patch, @majensen! I've applied that and generated [a DOI for Augur from Zenodo](https://doi.org/10.5281/zenodo.4421955):

10.5281/zenodo.4421955

**Comment by majensen** [comment]
@whedon set 10.5281/zenodo.4421955 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4421955" target="_blank">10.5281/zenodo.4421955</a> is the archive.

**Comment by majensen** [comment]
@whedon set 10.2.0 as version

**Comment by whedon** [comment]
OK. 10.2.0 is the version.

**Comment by majensen** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.20944/preprints202008.0220.v1 is OK
- 10.2807/1560-7917.ES.2020.25.32.2001410 is OK
- 10.1186/s13059-015-0726-x is OK
- 10.1371/journal.pone.0009490 is OK
- 10.1093/bioinformatics/btu033 is OK
- 10.1038/s41591-020-0935-z is OK
- 10.1126/science.abc0523 is OK
- 10.1093/bioinformatics/btv381 is OK
- 10.1093/bioinformatics/bty407 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1093/bioinformatics/btr509 is OK
- 10.1093/nar/gkf436 is OK
- 10.1093/molbev/msu300 is OK
- 10.1093/bioinformatics/bts480 is OK
- 10.1093/ve/vex042 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2015

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2015, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1347188133012660224) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2017
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02906](https://doi.org/10.21105/joss.02906)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@dcnickle, @Maghnuso - many thanks for your reviews here and to @majensen for editing this submission. JOSS relies upon the volunteer efforts of folks like yourselves, and we simply couldn't do this without you! ✨ 

@huddlej - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02906/status.svg)](https://doi.org/10.21105/joss.02906)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02906">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02906/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02906/status.svg
   :target: https://doi.org/10.21105/joss.02906
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02906/status.svg)](https://doi.org/10.21105/joss.02906)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by majensen** [comment]
@huddlej thanks very much for choosing JOSS for this very nice work. Keep on with the outstanding efforts you and your colleagues are making; it is making a difference in the real world.
