### ISSUE TITLE
[PRE REVIEW]: zipcodeR: An all-in-one toolkit of functions & data for working with U.S. ZIP codes in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2907]
**Submitting author:** @gavinrozzi (<a href="http://orcid.org/0000-0002-9969-8175">Gavin Rozzi</a>)
**Repository:** <a href="https://github.com/gavinrozzi/zipcodeR" target ="_blank">https://github.com/gavinrozzi/zipcodeR</a>
**Version:** v0.2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gavinrozzi. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kakiac.

@gavinrozzi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.53 s (102.8 files/s, 26153.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            26           1316            350           9606
Markdown                         8            162              0            648
CSS                              4             99             49            431
JavaScript                       5             69             40            291
R                                4             20            220            187
TeX                              1              0              0             46
YAML                             4              6              8             39
Rmd                              1             40             79             16
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            54           1712            747          11275
-------------------------------------------------------------------------------


Statistical information for the repository 'bfb187f648311d6215c83a50' was
gathered on 2020/12/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Gavin Rozzi                      2           400              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Gavin Rozzi                 400          100.0          0.0               10.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02907/joss.02907/10.21105.joss.02907.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02907/joss.02907/10.21105.joss.02907.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @gavinrozzi. Thank you for your submission. However, while your software does indeed look like useful research software, it does not meet the bar of [_substantial scholarly effort_](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

If you continue to develop this work, we would be happy to reconsider it as a submission in the future.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by gavinrozzi** [comment]
Hello @kthyng. I have reviewed the criteria for "substantial scholarly effort" prior to making this submission and feel that this criteria has been met with my submission. 

Could you please elaborate as to why you feel this does not currently meet that criteria? Given that this package has already been cited in multiple scholarly outputs since its introduction and fills a void in the R ecosystem I feel that it meets this criteria. Nevertheless I appreciate your feedback. Thanks!

**Comment by kthyng** [comment]
@gavinrozzi Sure, the primary item on [the list](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) that triggered this rejection is the lines of code in your submission. The cloc analysis printed above shows the lines of R code to be less than 200. We are mindful that JOSS gives a "publication credit" for the software, and continue to be regarded as a valid and equal counterpart to traditional journals, for which reason we are constantly discussing our criteria and refining our process. Like editors at other journals, we have to draw a line somewhere for what we consider a "minimum publishable unit." 

Please consider whether this software can be made part of a larger package providing additional functionality, and which would make for a submission that passes that bar.
