### ISSUE TITLE
[PRE REVIEW]: How scientifically popular is a species?

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2909]
**Submitting author:** @jessicatytam (<a href="http://orcid.org/0000-0003-3655-1974">Jessica Tam</a>)
**Repository:** <a href="https://github.com/jessicatytam/specieshindex" target ="_blank">https://github.com/jessicatytam/specieshindex</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jessicatytam. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @karthik.

@jessicatytam if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (361.3 files/s, 74179.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rmd                              2            185            334            778
R                                8             58            379            524
TeX                              2             23              0            376
Markdown                         2             67              0            236
YAML                             1             22              1             97
-------------------------------------------------------------------------------
SUM:                            15            355            714           2011
-------------------------------------------------------------------------------


Statistical information for the repository '648cb6098b19f10f4ca11159' was
gathered on 2020/12/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
jessicatytam                     2            19             19          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1073/pnas.0507655102 is OK
- 10.1111/tbed.12221 is OK
- 10.1111/mam.12066 is OK
- 10.1007/s11192-015-1798-9 is OK
- 10.1007/s11192-007-1859-9 is OK
- 10.1371/journal.pone.0131004 is OK
- 10.1111/mam.12038 is OK
- 10.1038/s41598-017-09084-6 is OK
- 10.1139/facets-2016-0011 is OK
- 10.1017/S1367943004001799 is OK
- 10.1371/journal.pone.0189577 is OK
- 10.1016/S0169-5347(01)02381-3 is OK

MISSING DOIs

- 10.1007/s11192-006-0147-4 may be a valid DOI for title: A Hirsch-type index for journals
- 10.1007/s11192-006-0146-5 may be a valid DOI for title: An extension of the Hirsch index: Indexing scientific topics and compounds
- 10.1038/s41467-018-07916-1 may be a valid DOI for title: Recognizing the quiet extinction of invertebrates
- 10.1111/acv.12586 may be a valid DOI for title: Drivers of taxonomic bias in conservation research: a global analysis of terrestrial mammals

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02909/joss.02909/10.21105.joss.02909.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02909/joss.02909/10.21105.joss.02909.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @jessicatytam, and thanks for your submission. Since the number of lines of code of your submission is on the low end (below 1000), I have flagged it for editorial review to decide whether it is in scope or not. You should hear back from someone here next week about it.

**Comment by danielskatz** [comment]
👋 @jessicatytam - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
