### ISSUE TITLE
[REVIEW]: CLOOPSy - Copernicus Land cOver crOwdsourcing Platform for Sentinel-based mapping

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#291]
**Submitting author:** @dandev89 (<a href="http://orcid.org/0000-0001-8600-7657">Daniele De Vecchi</a>)
**Repository:** <a href="https://bitbucket.org/cloopsy/android/" target ="_blank">https://bitbucket.org/cloopsy/android/</a>
**Version:** v1.0
**Editor:** @arfon
**Reviewer:** @MWieland
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.825709" target="_blank">10.5281/zenodo.825709</a>

## Status

[![status](http://joss.theoj.org/papers/0fc1fdfe97d953313df00d88468a170a/status.svg)](http://joss.theoj.org/papers/0fc1fdfe97d953313df00d88468a170a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0fc1fdfe97d953313df00d88468a170a"><img src="http://joss.theoj.org/papers/0fc1fdfe97d953313df00d88468a170a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0fc1fdfe97d953313df00d88468a170a/status.svg)](http://joss.theoj.org/papers/0fc1fdfe97d953313df00d88468a170a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://bitbucket.org/cloopsy/android/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/cloopsy/android/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@dandev89) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @MWieland it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @MWieland - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by arfon** [comment]
Friendly reminder on this review @MWieland 😁

**Comment by MWieland** [comment]
The software complies with the journal standards and I suggest its publication in JOSS. My only suggestions are to add more functional documentation to the repository itself. I assume that the authors intended to provide more documentation through their external software website (https://cloopsy.unipv.it), which they reference in the repository. Unfortunately, at the time of this review the website was not accessible.

**Comment by dandev89** [comment]
Thanks @MWieland. I confirm that the server is down at the moment and we are working to recover it. Anyway, I'll follow your suggestion to include more documentation within the repository.

**Comment by dandev89** [comment]
The server is up and running now. I've also added a functionality document to the repository describing the data flow and the APIs.

**Comment by MWieland** [comment]
Thanks for the updates @dandev89. The website works now and the functionality document is very useful.

**Comment by arfon** [comment]
@dandev89 - it doesn't look like there is a `paper.bib` file present with your paper. Do you not have any references you'd like to include with this submission?

**Comment by dandev89** [comment]
Thanks @arfon, I included the references in the bib file and cited them within the md file.

**Comment by arfon** [comment]
> Thanks @arfon, I included the references in the bib file and cited them within the md file.

👍 - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by dandev89** [comment]
Zenodo DOI: https://doi.org/10.5281/zenodo.825709

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.825709 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.825709" target="_blank">10.5281/zenodo.825709</a> is the archive.

**Comment by arfon** [comment]
@MWieland - many thanks for your review here ✨ 

@dandev89 - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00291 ⚡️ 🚀 💥
