### ISSUE TITLE
[REVIEW]: ezc3d: An easy C3D file I/O cross-platform solution for C++, Python and MATLAB

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2911]
**Submitting author:** @pariterre (<a href="http://orcid.org/0000-0002-5031-1048">Benjamin Michaud</a>)
**Repository:** <a href="https://github.com/pyomeca/ezc3d" target ="_blank">https://github.com/pyomeca/ezc3d</a>
**Version:** Release_1.4.2
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @melund, @BKillen05, @modenaxe
**Archive:** <a href="https://doi.org/10.5281/zenodo.4553333" target="_blank">10.5281/zenodo.4553333</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e67556c5eeb8cdb68a2257e62d2f22bb/status.svg)](https://joss.theoj.org/papers/e67556c5eeb8cdb68a2257e62d2f22bb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e67556c5eeb8cdb68a2257e62d2f22bb"><img src="https://joss.theoj.org/papers/e67556c5eeb8cdb68a2257e62d2f22bb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e67556c5eeb8cdb68a2257e62d2f22bb/status.svg)](https://joss.theoj.org/papers/e67556c5eeb8cdb68a2257e62d2f22bb)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pyomeca/ezc3d" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@melund & @BKillen05, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pyomeca/ezc3d">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pariterre) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pyomeca/ezc3d">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pariterre) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pyomeca/ezc3d">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pariterre) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @melund, @BKillen05 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-0-12-816713-7.00008-8 is OK
- 10.1371/journal.pcbi.1006223 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02911/joss.02911/10.21105.joss.02911.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02911/joss.02911/10.21105.joss.02911.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @BKillen05, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @melund, please update us on how your review is going.

**Comment by melund** [comment]
@Kevin-Mattheus-Moerman I missed the invitation for the review so it managed to expire: 

![image](https://user-images.githubusercontent.com/1038978/103519789-6efb4300-4e76-11eb-8abc-a5e83828e24a.png)

Can you issue a new one, so I can update my progress. Sorry about the delay.

**Comment by melund** [comment]
Thanks a lot @Kevin-Mattheus-Moerman. But I still can't edit the checklist. And clicking the invitation link now gives me this:

![image](https://user-images.githubusercontent.com/1038978/103616397-acbaa300-4f2c-11eb-913b-62e99106b4ba.png)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon re-invite @melund as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@melund please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by Kevin-Mattheus-Moerman** [comment]
@melund can you access it now? Thanks

**Comment by melund** [comment]
@Kevin-Mattheus-Moerman . Now it works :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@modenaxe we are just getting started. Would you like to join this review party? :pray:

**Comment by Kevin-Mattheus-Moerman** [comment]
@BKillen05 I hope you are well, and best wishes for 2021. Can you remind us when you are able to work on this? Thanks again for your help!

**Comment by modenaxe** [comment]
@Kevin-Mattheus-Moerman count me in. It might take longer than usual though. Also I will comment confidently only on the MATLAB and Python part. I forgot C++ 😅

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @modenaxe as reviewer

**Comment by whedon** [comment]
OK, @modenaxe is now a reviewer

**Comment by BKillen05** [comment]
> @BKillen05 I hope you are well, and best wishes for 2021. Can you remind us when you are able to work on this? Thanks again for your help!

@Kevin-Mattheus-Moerman I am reading the text now - we are preparing for examination period here so even more hectic than usual. Best wishs for 2021 to you also

**Comment by melund** [comment]
@Kevin-Mattheus-Moerman, I have finished my review and I am happy to accept the paper. The paper and the project fulfill all requirements for a JOSS publication. 

The ezc3d is a valuable contribution which is already used in many projects. I believe it will receive many citations in the future. 
I haven’t been able to assess the functionality of the C++ API but I have used the Python interface extensively which is just wrapper on the C++ API. Similarly I haven’t been able to try the Matlab API, but the documentation seems solid. 

I have also contributed a few bug reports and fixes to the project prior to this review which were all handle well. I believe ezc3d is a best practice example of an open source project. Good work @pariterre

**Comment by BKillen05** [comment]
@Kevin-Mattheus-Moerman Sorry for the delay in this review. 
I have now read the paper and documentation and completed some testing for functionality etc.

I am extremely impressed by the quality of the submisison - both the software - descriptions - and documentation is extremely thorough. I am therefore more than happy to accept the paper and project in its current form. Similar to @melund  I have only tested the Python interface to date - if required I can try to carve out some time to try and do further testing on the MATLAB side.

I was previously able to edit the "checklist" but for some reason cannot do so now - I may need a new invitation ?

**Comment by modenaxe** [comment]
@BKillen05 I can test the MATLAB wrapper when I review the paper. @Kevin-Mattheus-Moerman apologies for the delay with this review...

**Comment by modenaxe** [comment]
@pariterre I have a good number of comments. Some are issues, some other would be probably easier to highlight/fix with a pull request. @Kevin-Mattheus-Moerman am I allowed to do that during a review process?

**Comment by modenaxe** [comment]
@pariterre, the project is overall very nice and it will be incredibly useful, I really like it!

**Comment by modenaxe** [comment]
@Kevin-Mattheus-Moerman on second thought, no worries, I will put everything in the project Issues.

**Comment by modenaxe** [comment]
hi @pariterre, I have [posted some questions](https://github.com/pyomeca/ezc3d/issues) under the `[JOSS review]` header.

**Comment by pariterre** [comment]
@modenaxe 
I have answered all the comments in the issues, feel free to close those you are satisfied with. Thanks for your review!

**Comment by modenaxe** [comment]
@pariterre there are a couple more [here](https://github.com/pyomeca/ezc3d/issues/177) I added them to an existing Issue.

**Comment by modenaxe** [comment]
@Kevin-Mattheus-Moerman I am happy with both the paper and the repository (as mentioned above I checked carefully the MATLAB interface). The submission is high quality, and really solves a constant issue in biomechanics (efficiently importing gait lab data for processing)!

Thank you @pariterre, this was a great JOSS contribution to review, great fun exchanging some data structuring dilemmas as well! :smile::laughing:

**Comment by pariterre** [comment]
@modenaxe  It is a impossible to solve dilemma hahaha!
Thanks for the careful and highly useful review :)

**Comment by modenaxe** [comment]
@pariterre indeed, I was dealing with something similar yesterday and thinking: "shall I go XYZ this time"? 🤣  
No worries, it's been a pleasure discovering such a nice package, congratulations again 👏 👏

**Comment by Kevin-Mattheus-Moerman** [comment]
@BKillen05 how are you getting on. No pressure but can you remind us when you could pick this up again? Thanks!

**Comment by modenaxe** [comment]
@Kevin-Mattheus-Moerman I think Bryce said he's ok with accepting but had issue with the tick boxes

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon re-invite @BKillen05 as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@bkillen05 please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by Kevin-Mattheus-Moerman** [comment]
@BKillen05 apologies I missed that box ticking issue. I think it should be working if you accept this invite again :point_up:

**Comment by BKillen05** [comment]
@Kevin-Mattheus-Moerman Thank you - all should be sorted

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @BKillen05!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02911/joss.02911/10.21105.joss.02911.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02911/joss.02911/10.21105.joss.02911.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@pariterre I will now process this work for acceptance in JOSS. 

Below are some very minor point on the paper, and some instructions for next steps:

- [ ] This sentence does not read well: `This has forced scientists to develop ad hoc solutions for each project which require to write file I/O codes for each software format files.` would the following be better?  `This has forced scientists to develop ad hoc solutions for each project which requires writing file I/O codes for each software file format.`
- [ ] Could you consider rephrasing the line `Introducing the open-source ezc3d library which provides.....`, perhaps something like these alternatives: `This work introduces....` or `Here the .... is introduced...` or `To address these issues the open source ezc3d library is introduced here....`
- [ ] I suggest replacing `open-source` by `open source`
- [ ] I suggest removal of `in-house`, since I take it all the software here is custom made as part of the open source project, it seems odd to refer to `in-house` here unless I am misunderstanding
- [ ] Instead of `dependencies-free` consider using `dependency-free`
- [ ] Since it is used once please spell out `OS` as `operational systems`
- [ ] This paper is about to be processed for acceptance, as such I recommend the authors thoroughly review it once more themselves (especially ensure the author names and acknowledgements are accurate). 

- [ ] Once you have completed the above, please archive a copy of the software on [Zenodo](https://zenodo.org/) (Some users find [these steps](https://guides.github.com/activities/citable-code/) useful), and please report back here with the archive DOI. 
- [ ] Ensure that the Zenodo archive metadata matches that of the paper. I.e. verify that the title and author list matches (the title might be automatically created from the repository). You may need to manually edit this information.

**Comment by melund** [comment]
I think `OS` should be `operating systems` and not `operational systems`

**Comment by Kevin-Mattheus-Moerman** [comment]
> I think `OS` should be `operating systems` and not `operational systems`

Thanks @melund I fixed it up there :point_up:

**Comment by pariterre** [comment]
Hi @kellykochanski  and everyone! Many thanks again for the process! 

I have completed all the tick boxes of your comment (but cannot actually tick them). 
Here is the DOI: 10.5281/zenodo.4548917

Have a nice day!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.4548917 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4548917" target="_blank">10.5281/zenodo.4548917</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
whedon generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02911/joss.02911/10.21105.joss.02911.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02911/joss.02911/10.21105.joss.02911.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@pariterre thanks for making those changes. I've ticked those boxes. One more point remains which I forgot to add to that list: 

- [ ] Recently we changed [our criteria](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) to require that papers have a `Statement of need` section. Can you add such a heading in the paper and collect/formulate/move text there with a description that illustrates the research purpose of the software? I think most of this is written already so perhaps you can just collect existing text largely and put it under this heading. (note you can see examples on our website too e.g. https://joss.theoj.org/papers/10.21105/joss.02757).

**Comment by pariterre** [comment]
@Kevin-Mattheus-Moerman 

I added the `Statement of need` in https://github.com/pyomeca/ezc3d/pull/188 !
Here is the DOI for the release with the Statement of need
10.5281/zenodo.4553333

Thanks :)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02911/joss.02911/10.21105.joss.02911.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02911/joss.02911/10.21105.joss.02911.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set 10.5281/zenodo.4553333 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4553333" target="_blank">10.5281/zenodo.4553333</a> is the archive.

**Comment by Kevin-Mattheus-Moerman** [comment]
@pariterre can you confirm what the most recent version tag is for this software? Are we still at 'Release_1.3.7', or has it moved on?

**Comment by pariterre** [comment]
Hum... I don't know where I am supposed to inform this, but the version that corresponds to the latest DOI is 1.4.2

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set Release_1.4.2 as version

**Comment by whedon** [comment]
OK. Release_1.4.2 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@pariterre we are all set now. I'll now recommend accept

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/B978-0-12-816713-7.00008-8 is OK
- 10.1371/journal.pcbi.1006223 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2095

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2095, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1363456998126329862) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2100
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02911](https://doi.org/10.21105/joss.02911)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@melund, @BKillen05, @modenaxe - many thanks for your reviews here and to @Kevin-Mattheus-Moerman for editing this submission. JOSS relies upon the volunteer efforts of people like you and we simply wouldn't be able to do this without you! ✨ 

@pariterre - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02911/status.svg)](https://doi.org/10.21105/joss.02911)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02911">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02911/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02911/status.svg
   :target: https://doi.org/10.21105/joss.02911
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02911/status.svg)](https://doi.org/10.21105/joss.02911)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by pariterre** [comment]
Thanks guys! That was a pleasure :)
