### ISSUE TITLE
[PRE REVIEW]: Visualization of Multi-Dimensional Data - The data-slicer Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2914]
**Submitting author:** @kuadrat (<a href="http://orcid.org/0000-0001-5523-6924">Kevin Kramer</a>)
**Repository:** <a href="https://github.com/kuadrat/data_slicer" target ="_blank">https://github.com/kuadrat/data_slicer</a>
**Version:** 0.0.9
**Editor:** @timtroendle
**Reviewers:** @sabinomaggi  @Chilipp
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kuadrat. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @pibion.

@kuadrat if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (170.4 files/s, 28039.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          19            783           1783           2440
reStructuredText                11            154             93            318
TeX                              1             26              0            311
Markdown                         2             32              0            177
SVG                              1              1              1            170
DOS Batch                        1              8              1             26
YAML                             2              3              4             25
CSS                              1              7             16             18
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            39           1018           1905           3494
-------------------------------------------------------------------------------


Statistical information for the repository '6c62bcbeabe7e4674cc0f0c2' was
gathered on 2020/12/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kevin Kramer                    74          5985            979          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kevin Kramer               5006           83.6          9.3               19.12
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2914 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-a0b7af7c4770/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-a0b7af7c4770/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-a0b7af7c4770/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-a0b7af7c4770/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-a0b7af7c4770/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-a0b7af7c4770/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/nphys3172 is OK
- 10.1088/1361-648x/ab757a is OK
- 10.1107/S2052252519012612 is OK
- 10.1107/S2059798316012304 is OK
- 10.1088/0957-0233/25/5/055604 is OK
- 10.1016/j.mri.2012.05.001 is OK
- 10.1016/j.softx.2020.100472 is OK
- 10.1016/j.softx.2020.100600 is OK
- 10.1063/1.4943208 is OK
- 10.1103/RevModPhys.79.353 is OK
- 10.1103/PhysRev.126.941 is OK
- 10.1103/PhysRevLett.110.087004 is OK
- 10.1103/PhysRevB.46.11830 is OK
- 10.1103/PhysRev.119.980 is OK
- 10.1038/s41586-019-1319-8 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.ultramic.2019.112815 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/xrs.3141 is INVALID because of 'https://doi.org/' prefix
```

**Comment by kuadrat** [comment]
> 
> @kuadrat if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
> 

Just judging from that list (starting at the bottom), the following people might be well suited as reviewers:
sabinomaggi
jodemaey
kgoebber
Generally people with a background in data heavy natural sciences should be suitable.
A background in condensed matter physcics (x-ray/neutron/synchrotron science) may help understand where we are coming from, but should not be necessary.

Kind regards

**Comment by kthyng** [comment]
Hi @mbobra! Would you be up for editing this submission?

**Comment by kthyng** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by kthyng** [comment]
@kuadrat - thanks! Those submissions will be very helpful. First we'll find a suitable handling editor, and that person will move forward with finding with reviewers.

**Comment by kthyng** [comment]
Ack sorry @mbobra

**Comment by kthyng** [comment]
@timtroendle are you up for editing this submission?

**Comment by kthyng** [comment]
@whedon invite @timtroendle as editor

**Comment by whedon** [comment]
@timtroendle has been invited to edit this submission.

**Comment by jgostick** [comment]
This needs a 'scope query'.  It's very light, despite having 2k lines of python.  It a jazzed up jupyter notebook for looking at 3d data from different directions.  If it does more than this, it's not documented on the website.

**Comment by timtroendle** [comment]
@kthyng Could do, but will be ooo for two weeks.

**Comment by kthyng** [comment]
Ok let's do this. We'll scope query based on @jgostick's comment, and I will also add @timtroendle as the handling editor for when back from being out of office. If the submission passes the scope query, we'll have our editor in place. 

@kuadrat It's possible you'll hear back about the scope query next week, but it may be after the holidays at this point. Thanks for your patience.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
@whedon assign @timtroendle as editor

**Comment by kthyng** [comment]
Sorry for all the notes. Actually I will wait to add @timtroendle as editor for book keeping reasons in the system. Thanks everyone!

**Comment by kthyng** [comment]
@whedon remove @timtroendle as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kthyng** [comment]
@openjournals/dev sorry for the trouble, but can I remove the editor I added?

**Comment by kuadrat** [comment]
> Ok let's do this. We'll scope query based on @jgostick's comment, and I will also add @timtroendle as the handling editor for when back from being out of office. If the submission passes the scope query, we'll have our editor in place.
> 
> @kuadrat It's possible you'll hear back about the scope query next week, but it may be after the holidays at this point. Thanks for your patience.

Alright thanks! I'm in no rush and didn't expect the process to go particularly fast during this time of the year anyways, so no worries at all.
It sounds like there is no action required on my behalf with regards to this 'scope query'?

**Comment by kthyng** [comment]
Yes @kuadrat that's correct, nothing to do on your part currently.

**Comment by danielskatz** [comment]
@whedon unassign @timtroendle as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon assign @timtroendle as editor

**Comment by whedon** [comment]
OK, the editor is @timtroendle

**Comment by arfon** [comment]
OK, I've re-assigned @timtroendle as the editor here as this submission has passed the scope review check.

**Comment by timtroendle** [comment]
Hi @kuadrat , I will start looking for reviewers for your submission. If you have any additional suggestions please let me know.

**Comment by timtroendle** [comment]
👋 @sabinomaggi, @jodemaey, @kgoebber would any of you be willing to review this submission for JOSS?

**Comment by sabinomaggi** [comment]
Seems very interesting. I can review the paper but not earlier than 3-4 weeks. Am I supposed to test the package to check how it works?

**Comment by timtroendle** [comment]
Thanks @sabinomaggi , that's great to hear. We are currently in [Reduced service mode](https://blog.joss.theoj.org/2020/05/reopening-joss), which means that reviews may take up to six weeks. Of course, we are encouraging reviewers to start the review as soon as possible. 

Regarding your question: the review includes a functionality check as well. You may want to have a quick look at our [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html).

**Comment by jodemaey** [comment]
Hi @timtroendle ,

Sorry, but I feel uncomfortable reviewing GUIs so I prefer to pass on this one. I hope you will find the right person to complete the review.

Best Regards,

Jonathan.

**Comment by timtroendle** [comment]
@jodemaey, I understand. Thanks for letting me know.

**Comment by timtroendle** [comment]
👋 @Chilipp, @krischer, would any of you be willing to review this submission for JOSS?

**Comment by Chilipp** [comment]
hey @timtroendle! yes, I will be able to review this submission until the end of January

**Comment by timtroendle** [comment]
That's great to hear, thanks @Chilipp!

**Comment by krischer** [comment]
Hi @timtroendle 

This looks exciting but I currently don't have the capacity to review it. Thanks for considering me.

**Comment by timtroendle** [comment]
Thanks for letting us know, @krischer.

**Comment by timtroendle** [comment]
@whedon assign @sabinomaggi  @Chilipp as reviewer

**Comment by whedon** [comment]
OK, @sabinomaggi  @Chilipp is now a reviewer

**Comment by timtroendle** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2969.

**Comment by sabinomaggi** [comment]
@whedon commands

**Comment by sabinomaggi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2914 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by sabinomaggi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02914/joss.02914/10.21105.joss.02914.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02914/joss.02914/10.21105.joss.02914.pdf) :page_facing_up: :point_left:
