### ISSUE TITLE
[PRE REVIEW]: coder: An R package for code-based item classification and categorization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2915]
**Submitting author:** @eribul (<a href="http://orcid.org/0000-0002-9973-456X">Erik Bülow</a>)
**Repository:** <a href="https://github.com/ropensci/coder" target ="_blank">https://github.com/ropensci/coder</a>
**Version:** v0.13.1
**Editor:** @kthyng
**Reviewers:** @kthyng
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @eribul. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @karthik.

@eribul if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.25 s (239.1 files/s, 88297.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              4           1195              0          16129
R                               41            407           1107           1582
Markdown                         3             76              0            292
Rmd                              6            338            493            188
JSON                             1              0              0            178
YAML                             4             25              2            135
HTML                             1              0              0              8
-------------------------------------------------------------------------------
SUM:                            60           2041           1602          18512
-------------------------------------------------------------------------------


Statistical information for the repository '6f7b220a27abe4cdfc6b2f2f' was
gathered on 2020/12/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Erik Bulow                       1             5              7            0.85
Erik Bülow                      2            90            586           47.94
Erik Bülow                       8           610            112           51.21

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/17453674.2018.1492507 is OK
- 10.1080/17453674.2017.1341243 is OK
- 10.1302/0301-620X.101B1.BJJ-2018-0894.R1 is OK
- 10.1097/CORR.0000000000001210 is OK
- 10.1016/0021-9681(87)90171-8 is OK
- 10.1002/jor.23711 is OK
- 10.1080/17453674.2018.1475179 is OK
- 10.21105/joss.00648 is OK
- 10.1080/17453674.2019.1690339 is OK
- 10.1016/J.INJURY.2018.12.022 is OK
- 10.1186/s12891-018-2321-2 is OK
- 10.1136/bmjopen-2017-021122 is OK
- 10.1097/01.mlr.0000182534.19832.83 is OK
- 10.1056/NEJMsb1609216 is OK
- 10.1097/01.MLR.0000064641.84967.B7 is OK
- 10.1097/CORR.0000000000000679 is OK

MISSING DOIs

- 10.1097/00005650-199801000-00004 may be a valid DOI for title: Comorbidity Measures for Use with Administrative Data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02915/joss.02915/10.21105.joss.02915.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02915/joss.02915/10.21105.joss.02915.pdf) :page_facing_up: :point_left:

**Comment by eribul** [comment]
This package has been reviewed by rOpenSci: https://github.com/ropensci/software-review/issues/381, @ropensci/editors

**Comment by kthyng** [comment]
HI @eribul! I see that this has already been reviewed with rOpenSci. Because of that, I can take the submission through the whole JOSS process.

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@whedon assign me as reviewer

**Comment by whedon** [comment]
OK, me is now a reviewer

**Comment by kthyng** [comment]
ok fine.

**Comment by kthyng** [comment]
@whedon remove me as reviewer

**Comment by whedon** [comment]
OK, me is no longer a reviewer

**Comment by kthyng** [comment]
@whedon assign @kthyng as reviewer

**Comment by whedon** [comment]
OK, @kthyng is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2916.
