### ISSUE TITLE
[REVIEW]: coder: An R package for code-based item classification and categorization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2916]
**Submitting author:** @eribul (<a href="http://orcid.org/0000-0002-9973-456X">Erik Bülow</a>)
**Repository:** <a href="https://github.com/ropensci/coder" target ="_blank">https://github.com/ropensci/coder</a>
**Version:** v0.13.2
**Editor:** @kthyng
**Reviewer:** @kthyng
**Archive:** <a href="https://doi.org/10.5281/zenodo.4329526" target="_blank">10.5281/zenodo.4329526</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/49d52b062aa289d7b990b1a0a678d109/status.svg)](https://joss.theoj.org/papers/49d52b062aa289d7b990b1a0a678d109)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/49d52b062aa289d7b990b1a0a678d109"><img src="https://joss.theoj.org/papers/49d52b062aa289d7b990b1a0a678d109/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/49d52b062aa289d7b990b1a0a678d109/status.svg)](https://joss.theoj.org/papers/49d52b062aa289d7b990b1a0a678d109)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/coder" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kthyng, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/coder">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@eribul) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kthyng it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/17453674.2018.1492507 is OK
- 10.1080/17453674.2017.1341243 is OK
- 10.1302/0301-620X.101B1.BJJ-2018-0894.R1 is OK
- 10.1097/CORR.0000000000001210 is OK
- 10.1016/0021-9681(87)90171-8 is OK
- 10.1002/jor.23711 is OK
- 10.1080/17453674.2018.1475179 is OK
- 10.21105/joss.00648 is OK
- 10.1080/17453674.2019.1690339 is OK
- 10.1016/J.INJURY.2018.12.022 is OK
- 10.1186/s12891-018-2321-2 is OK
- 10.1136/bmjopen-2017-021122 is OK
- 10.1097/01.mlr.0000182534.19832.83 is OK
- 10.1056/NEJMsb1609216 is OK
- 10.1097/01.MLR.0000064641.84967.B7 is OK
- 10.1097/CORR.0000000000000679 is OK

MISSING DOIs

- 10.1097/00005650-199801000-00004 may be a valid DOI for title: Comorbidity Measures for Use with Administrative Data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02916/joss.02916/10.21105.joss.02916.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02916/joss.02916/10.21105.joss.02916.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
This submission was previously reviewed with rOpenSci: https://github.com/ropensci/software-review/issues/381

**Comment by kthyng** [comment]
@eribul: we do require a section in your paper that has the title "Statement of Need". Can you rename an existing section if appropriate or add a section addressing this requirement?

**Comment by kthyng** [comment]
@eribul Looking through your paper, it looks good but the references need a bit of attention. For example:

* Gasparini has "r" lower case (you can force capitalization with {} around one or more characters)
* Jawad et al seems to have a typo in the title
* the author list for Quan et al has lower case letters for initials
* Pratt et al has "rx-risk", not sure if any of that should be capitalized.

Could you go through the references in detail and make sure everything is correct?

**Comment by kthyng** [comment]
@eribul Also can you archive your repo with a place like Zenodo and report the doi back here? Be sure to edit the metadata of the archive so that the title and author list exactly match that of your JOSS paper.

**Comment by eribul** [comment]
Dear @kthyng thank you very much for very rapid response and nice feedback!
I have now included a section called "Statement of Need" (changed one of the old headings).
I have changed the references according to your suggestions.
I also found some additional typos in the references, which are also fixed.
I have a repo at Zenodo: http://doi.org/10.5281/zenodo.4329526 with the same title and author as for the paper.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02916/joss.02916/10.21105.joss.02916.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02916/joss.02916/10.21105.joss.02916.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@eribul Excellent, things looks good but I did notice one more thing with your paper. Could you capitalize the appropriate items in your second affiliation? It currently looks a bit informal.

What software version would you like associated with your submission?

**Comment by eribul** [comment]
@kthyng thanks! Capitalization has now been performed :-) The current version is v0.13.2

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02916/joss.02916/10.21105.joss.02916.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02916/joss.02916/10.21105.joss.02916.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@eribul Excellent! We're all set now then. I will finish with the publication.

**Comment by kthyng** [comment]
@whedon set v0.13.2 as version

**Comment by whedon** [comment]
OK. v0.13.2 is the version.

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.4329526 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4329526" target="_blank">10.5281/zenodo.4329526</a> is the archive.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/17453674.2018.1492507 is OK
- 10.1080/17453674.2017.1341243 is OK
- 10.1302/0301-620X.101B1.BJJ-2018-0894.R1 is OK
- 10.1097/CORR.0000000000001210 is OK
- 10.1016/0021-9681(87)90171-8 is OK
- 10.1002/jor.23711 is OK
- 10.1080/17453674.2018.1475179 is OK
- 10.21105/joss.00648 is OK
- 10.1080/17453674.2019.1690339 is OK
- 10.1016/J.INJURY.2018.12.022 is OK
- 10.1186/s12891-018-2321-2 is OK
- 10.1136/bmjopen-2017-021122 is OK
- 10.1097/01.mlr.0000182534.19832.83 is OK
- 10.1056/NEJMsb1609216 is OK
- 10.1097/01.MLR.0000064641.84967.B7 is OK
- 10.1097/CORR.0000000000000679 is OK

MISSING DOIs

- 10.1097/00005650-199801000-00004 may be a valid DOI for title: Comorbidity Measures for Use with Administrative Data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1994

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1994, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@eribul Ah, I missed the missing DOI note before. Can you update your references with that missing DOI too?

**Comment by eribul** [comment]
@kthyng No problem! I have updated it now!

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02916/joss.02916/10.21105.joss.02916.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02916/joss.02916/10.21105.joss.02916.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/17453674.2018.1492507 is OK
- 10.1080/17453674.2017.1341243 is OK
- 10.1302/0301-620X.101B1.BJJ-2018-0894.R1 is OK
- 10.1097/CORR.0000000000001210 is OK
- 10.1016/0021-9681(87)90171-8 is OK
- 10.1002/jor.23711 is OK
- 10.1080/17453674.2018.1475179 is OK
- 10.1097/00005650-199801000-00004 is OK
- 10.21105/joss.00648 is OK
- 10.1080/17453674.2019.1690339 is OK
- 10.1016/J.INJURY.2018.12.022 is OK
- 10.1186/s12891-018-2321-2 is OK
- 10.1136/bmjopen-2017-021122 is OK
- 10.1097/01.mlr.0000182534.19832.83 is OK
- 10.1056/NEJMsb1609216 is OK
- 10.1097/01.MLR.0000064641.84967.B7 is OK
- 10.1097/CORR.0000000000000679 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1995

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1995, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1340005093073104905) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1996
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02916](https://doi.org/10.21105/joss.02916)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your JOSS publication @eribul!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02916/status.svg)](https://doi.org/10.21105/joss.02916)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02916">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02916/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02916/status.svg
   :target: https://doi.org/10.21105/joss.02916
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02916/status.svg)](https://doi.org/10.21105/joss.02916)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
