### ISSUE TITLE
[PRE REVIEW]: NiaAML: AutoML framework based on stochastic population-based nature-inspired algorithms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2918]
**Submitting author:** @lukapecnik (<a href="http://orcid.org/0000-0002-3897-9774">Luka Pečnik</a>)
**Repository:** <a href="https://github.com/lukapecnik/NiaAML" target ="_blank">https://github.com/lukapecnik/NiaAML</a>
**Version:** 1.1.0
**Editor:** @arfon
**Reviewers:** @adi3, @sara-02
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lukapecnik. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @galessiorob.

@lukapecnik if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-981-15-2133-1_13 is OK
- 10.21105/joss.00613 is OK
- 10.1109/IJCNN.2015.7280767 is OK
- 10.1007/978-3-030-05318-5 is OK

MISSING DOIs

- 10.1007/978-3-030-05318-5_8 may be a valid DOI for title: TPOT: A tree-based pipeline optimization tool for automating machine learning

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.96 s (147.2 files/s, 8092.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         104           1170           1595           2831
reStructuredText                17            323            129            715
Markdown                         9            256              0            496
YAML                             5             11              3             66
TeX                              1              5              0             63
DOS Batch                        2              8              1             27
TOML                             1              3              0             27
make                             1              4              7              9
Bourne Shell                     1              0              0              4
-------------------------------------------------------------------------------
SUM:                           141           1780           1735           4238
-------------------------------------------------------------------------------


Statistical information for the repository 'c312f2aab150833b37e2797e' was
gathered on 2020/12/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Luka Pečnik                     73          7539           2383           93.23
firefly-cpp                      3           130             31            1.51
luka.pecnik                      2           185             85            2.54
lukapecnik                       3           265             24            2.72

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Luka Pečnik                5454           72.3          0.7                8.78
firefly-cpp                  57           43.8          1.0               12.28
luka.pecnik                  85           45.9          1.0               11.76
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02918/joss.02918/10.21105.joss.02918.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02918/joss.02918/10.21105.joss.02918.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @galessiorob! Are you able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by adi3** [comment]
I'd be keen to review this one.

**Comment by danielskatz** [comment]
Thanks @adi3 - once there is an editor assigned, they will decide on reviewers, and likely accept your offer

**Comment by arfon** [comment]
:wave: @galessiorob - happy new year! Just a friendly reminder you have an invite to edit here that we'd appreciate your response to 😄.

**Comment by sara-02** [comment]
Hello @arfon I too would like to review this package.

**Comment by arfon** [comment]
> Hello @arfon I too would like to review this package.

:zap: thanks @sara-02! Given we've got two offers of reviewers here I'm going to take on this submission and get it started.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon add @adi3 as reviewer

**Comment by whedon** [comment]
OK, @adi3 is now a reviewer

**Comment by arfon** [comment]
@whedon add @sara-02 as reviewer

**Comment by whedon** [comment]
OK, @sara-02 is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2949.

**Comment by arfon** [comment]
@adi3, @sara-02 - many thanks for agreeing to review this submission. See you over in #2949 where the actual review will take place.
