### ISSUE TITLE
[PRE REVIEW]: Pychron: Automated Data Collection and Reduction for Noble Gas and Ar/Ar Geochronology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2919]
**Submitting author:** @jirhiker (<a href="http://orcid.org/0000-0003-4727-7472">Jake Ross</a>)
**Repository:** <a href="https://github.com/NMGRL/pychron" target ="_blank">https://github.com/NMGRL/pychron</a>
**Version:** v20.1
**Editor:** @richardjgowers
**Reviewers:** @bovee, @pvermees
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jirhiker. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@jirhiker if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2919 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
Hi @jirhiker and thanks for resubmitting. Did you include the JOSS paper in this repo? That is required for us to be able to review. Please add it in.

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=29.68 s (76.3 files/s, 11626.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                        2060          55822          79272         171720
Fortran 77                      13            611            722           8551
C                                2            820           2477           7068
Fortran 90                       8            348            572           4949
reStructuredText               127           1599           3356           3099
YAML                            19             37             31           1484
Markdown                        12            199              0            784
Bourne Shell                     6             82             45            321
Arduino Sketch                   7            130            113            287
make                             1             24              5            124
C++                              1             39              2            122
MATLAB                           1             19             12             54
Cython                           2             11             23             41
C/C++ Header                     1             14              1             37
INI                              1             12              0             37
Mako                             1              7              0             15
DOS Batch                        1              1              0              3
HTML                             1              0              0              1
CSS                              1              0              8              0
-------------------------------------------------------------------------------
SUM:                          2265          59775          86639         198697
-------------------------------------------------------------------------------


Statistical information for the repository 'cef5d0e84a196491d83fac13' was
gathered on 2020/12/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
AGES-NGX                         6           143             59            0.02
Argon                           18           784            370            0.11
ArgonServer                      1            19             14            0.00
Bryan Wathen                     1            28              6            0.00
GSFC-MNGRL                       1            85              2            0.01
Jake Ross                     3780        318612         245710           53.35
Jan                              6           143             79            0.02
Stephen                          3           219              4            0.02
Stephen E Cox                   69           605            401            0.10
ael-ng                           3            29             24            0.01
ages-ngx-admin                  13           776            379            0.11
angl_laser                       2            84             49            0.01
argonlab2                       61          1283            761            0.19
argonlab5                        6           104             64            0.02
argus1ms                       106          2592           1548            0.39
felix                          170          8806           4757            1.28
jake                             1             2              2            0.00
jake ross                       93          1950            952            0.27
jan                              2            37             13            0.00
jirhiker                      1849        350877          96180           42.26
jross                            3             8             34            0.00
mcintosh                        33           428            231            0.06
nmgrluser                      158          5211           3405            0.81
obama                           60          2883           1913            0.45
raregas                         14           458            197            0.06
sidneyhemming                    1             5              2            0.00
stephen-e-cox                   44          1667            723            0.23
usgshelix                        1            25             23            0.00
uv                              30          1318            757            0.20
wiscar                           2            17              7            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
AGES-NGX                     83           58.0         34.8                0.00
ArgonServer                   2           10.5         55.8                0.00
Bryan Wathen                 10           35.7         31.4                0.00
GSFC-MNGRL                    2            2.4         10.2                0.00
Jake Ross                311255           97.7         34.2               23.63
Stephen E Cox               741          122.5         23.0               15.38
ael-ng                        7           24.1          1.2                0.00
ages-ngx-admin              473           61.0         32.5                7.19
angl_laser                   82           97.6         10.1                6.10
argonlab2                   220           17.1         12.0               10.45
argonlab5                    33           31.7         37.6               12.12
felix                      4149           47.1         37.5               19.26
mcintosh                    108           25.2         50.3                8.33
nmgrluser                  2371           45.5         28.7               11.30
raregas                     322           70.3         10.1                9.01
sidneyhemming                 1           20.0         31.0                0.00
usgshelix                    13           52.0         27.7               23.08
uv                           18            1.4         82.9               27.78
wiscar                       17          100.0         27.2                0.00
```

**Comment by kthyng** [comment]
@richardjgowers are you able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @richardjgowers as editor

**Comment by whedon** [comment]
@richardjgowers has been invited to edit this submission.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch manuscript

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch manuscript. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2919 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@whedon check references from branch manuscript

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch manuscript
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @jirhiker - your paper doesn't compile due to blank orcid lines - for authors without orcids, just remove the orcid line in the metadata.  Then use the command I did above to try to generate the PDF again

**Comment by jirhiker** [comment]
@whedon generate pdf from branch manuscript

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch manuscript. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02919/joss.02919/10.21105.joss.02919.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02919/joss.02919/10.21105.joss.02919.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @richardjgowers - happy new year! Just a friendly reminder you have an invite to edit here that we'd appreciate your response to 😄.

**Comment by richardjgowers** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by richardjgowers** [comment]
@sgrieve @bovee this is a little outside of your respective areas but would either of you be free to review this submission?

**Comment by richardjgowers** [comment]
@jirhiker if you can think of someone suitable to review this then I'm open to suggestions too!

**Comment by jirhiker** [comment]
@noahmclean @pvermees are both researchers in my field that are also involved with software

**Comment by sgrieve** [comment]
Afraid I don't have any spare capacity to review at the moment.

**Comment by bovee** [comment]
Sorry, I've been a bit behind on my notifications. I also have limited bandwidth right now, but I can review on a slower timescale (i.e. weeks) if you can't find other reviewers.

**Comment by pvermees** [comment]
I am confused. Have I been formally invited to review this paper, or have I simply been added to the GitHub page as an observer? I must confess that I am not very familiar with JOSS. Is it common for this journal to publish 2-page papers? Does such a short paper even require peer review? From [https://github.com/openjournals/joss](https://github.com/openjournals/joss) it appears that the review process is a formality. Would it suffice if I confirm that Pychron is a top notch piece of software? @jirhiker certainly deserves to get a DOI for his work!

**Comment by danielskatz** [comment]
👋 @pvermees - @jirhiker suggested you as a potential reviewer (which he should have done without the `@` so that you wouldn't have been notified). The next step is for the editor (@richardjgowers in this case) to invite you (and/or others).

Re: JOSS review criteria, see https://joss.readthedocs.io/en/latest/review_criteria.html.  In brief, the review is of the software as much as or more than the short paper.  The process is most definitely not 'a formality', except in the case of software that has previously been carefully reviewed by rOpenSci.

**Comment by pvermees** [comment]
@danielskatz Thanks for the clarification. I would be happy to provide a review, but I won't be able to do so until three weeks from now when I get a short break from teaching.

**Comment by richardjgowers** [comment]
@pvermees would you have time to do the review? Thanks

**Comment by pvermees** [comment]
Yes I can try to find some time. Note that I am not a practitioner of
40Ar/39Ar geochronology so I won't be able to install the software on a
mass spectrometer. So all that I will be able to test is the data
processing side of Pychron.

I assume that I will receive detailed instructions on how to conduct the
review?

P

**Comment by arfon** [comment]
I'm going to step in here and help @richardjgowers move this submission forward. 

Thanks @pvermees and @bovee for agreeing to review. If you're able to provide your initial review in 4-6 weeks that would be very acceptable. I'll go ahead now and set you up as reviewers and open the main review issue where you'll be given detailed instructions on how to proceed.

**Comment by arfon** [comment]
@whedon add @bovee as reviewer

**Comment by whedon** [comment]
OK, @bovee is now a reviewer

**Comment by arfon** [comment]
@whedon add @pvermees as reviewer

**Comment by whedon** [comment]
OK, @pvermees is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3386.

**Comment by arfon** [comment]
@bovee, @pvermees – see you over in #3386 where the actual review will take place.

**Comment by richardjgowers** [comment]
@noahmclean would you be free to help get this reviewed?

**Comment by richardjgowers** [comment]
@arosen93 @bbucior would either of you be able to review this or suggest someone that might be more suitable?

**Comment by arosen93** [comment]
@richardjgowers -- sorry, I'm a bit short on time and this is outside my area of expertise. Unfortunately, no recommendations from me on this topic.

**Comment by bbucior** [comment]
@richardjgowers -- sorry, I'm in a similar boat as Andrew. The only lead that comes to mind is the team over at https://github.com/numat since they've written some other data collection software.
