### ISSUE TITLE
[PRE REVIEW]: cuIBM: A GPU-based immersed boundary method code

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#292]
**Submitting author:** @mesnardo (<a href="http://orcid.org/0000-0001-5335-7853">Olivier Mesnard</a>)
**Repository:** <a href="https://github.com/barbagroup/cuIBM" target ="_blank">https://github.com/barbagroup/cuIBM</a>
**Version:** v0.1
**Editor:** @kyleniemeyer
**Reviewer:** @arghdos

**Author instructions**

Thanks for submitting your paper to JOSS @mesnardo. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mesnardo if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
Hi @mesnardo, thanks for submitting cuIBM to JOSS!

(For full disclosure, I've encountered cuIBM before; one of my students forked it and developed his own methods using that. However, I haven't contributed to cuIBM itself.)

Where possible, I like to find two reviewers: one close to the domain, and another perhaps coming from a bit further away.

@boyceg @namupatel and/or @arghdos, would you be willing to review this submission to JOSS? @mesnardo, any other suggestions you have would also be appreciated.

**Comment by mesnardo** [comment]
Hi @kyleniemeyer , thank you for being the editor for this paper.

I just release version 0.1.1 of cuIBM that includes a small bug-fix: downgrading the external library yaml-cpp from version 0.5.3 to 0.5.1.
(yaml-cpp is bundled into cuIBM, in the `external` folder.)
With version 0.5.3, yaml-cpp throws an error when a key parameter is not present in the YAML configuration file, whereas the expected behavior is to use the default value for the parameter.

So, the reviewers should be using the `master` branch of cuIBM or the release 0.1.1.

**Comment by arghdos** [comment]
@kyleniemeyer I'm willing to review this

**Comment by kyleniemeyer** [comment]
Awesome, thanks @arghdos! Dan Magee (@osumageed) has also agreed to serve as a second reviewer.

@whedon set reviewer as @arghdos

**Comment by kyleniemeyer** [comment]
@whedon assign @arghdos as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arghdos

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/301. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
OK @arghdos @osumageed and any others following, we'll move over to #301 for the actual review.
