### ISSUE TITLE
[PRE REVIEW]: VAST: The Void Analysis Software Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2920]
**Submitting author:** @kadglass (<a href="http://orcid.org/0000-0002-9540-546X">Kelly Douglass</a>)
**Repository:** <a href="https://github.com/DESI-UR/VAST" target ="_blank">https://github.com/DESI-UR/VAST</a>
**Version:** v1.0.0-alpha
**Editor:** @dfm
**Reviewers:** @changhoonhahn, @lavaux
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kadglass. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @pibion.

@kadglass if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.02 s (55.9 files/s, 22924.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          38           5326           5221           5192
Cython                          10           2490           1904           2439
Markdown                         6            152              0            454
TeX                              1              9              0             89
YAML                             1             13              6             66
INI                              1              2              0             21
-------------------------------------------------------------------------------
SUM:                            57           7992           7131           8261
-------------------------------------------------------------------------------


Statistical information for the repository '4fe3d438318c23e3be437b94' was
gathered on 2020/12/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dylan Veyrat                    38          4187            806            4.32
KELLY DOUGLASS                   1             8              4            0.01
Kelly                           85          6998           5589           10.89
Kelly Douglass                   1             7              7            0.01
Micahaela Guzzetti              39          2867            751            3.13
Michaela Guzzetti                1           182             63            0.21
Segev BenZvi                    83         31285          33410           55.96
Stephen W. O'Neill J            70         18762           9546           24.48
kadglass                         5            86           1059            0.99

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dylan Veyrat               2979           71.1          6.4               10.14
Micahaela Guzzetti          139            4.8         28.9                5.76
Michaela Guzzetti            22           12.1         29.6                0.00
Segev BenZvi               1804            5.8          1.6               44.29
Stephen W. O'Neill J       9073           48.4         10.4               12.61
kadglass                   1723         2003.5         16.5               20.26
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0067-0049/182/2/543 is OK
- 10.1086/304973 is OK
- 10.1111/j.1365-2966.2008.13180.x is OK

MISSING DOIs

- 10.1109/mcse.2010.118 may be a valid DOI for title: Cython: The Best of Both Worlds
- 10.1086/338340 may be a valid DOI for title: Voids in the point source catalogue survey and the updated zwicky catalog

INVALID DOIs

- https://doi.org/10.1038/s41592-019-0686-2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02920/joss.02920/10.21105.joss.02920.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02920/joss.02920/10.21105.joss.02920.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @kadglass and thanks for your submission. It looks to me like your submission is in scope for JOSS, but light on some of our packaging requirements, like clear documentation for how to use each of the two subpackages. The readme's are a start, and I see references to example scripts, but it is likely that under review these would need to be expanded. The reviewers will use your software and therefore need to be able to understand how to use it, and with as little effort as possible since we are asking them to spend their time reviewing your software.

In the meantime, I will work on recruiting a handling editor, however, I don't expect there to be much movement on reviews until the new year.

**Comment by kthyng** [comment]
@pibion are you able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @pibion as editor

**Comment by whedon** [comment]
@pibion has been invited to edit this submission.

**Comment by arfon** [comment]
:wave: @pibion - happy new year! Just a friendly reminder you have an invite to edit here that we'd appreciate your response to 😄.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @pibion as editor

**Comment by whedon** [comment]
@pibion has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jni would you be able to help edit this submission?

**Comment by kthyng** [comment]
@dfm would you be able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
Sure - I'm happy to edit!

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by kthyng** [comment]
thanks @dfm!!

**Comment by dfm** [comment]
@kadglass Following up on @kthyng's comment above (https://github.com/openjournals/joss-reviews/issues/2920#issuecomment-748178437): this package still needs substantial work on the documentation, packaging, and testing to bring it up to the standards expected for JOSS (see the [JOSS docs](https://joss.readthedocs.io/en/latest/review_criteria.html) for more info). Can you give us a timeline for when you expect to be able to get to this? Thanks!

**Comment by kadglass** [comment]
@dfm Absolutely!  We have looked at the JOSS docs, and we thought that we had checked all of the boxes.  Could you give us more detail on what you would like to see?  Thank you!

**Comment by dfm** [comment]
@kadglass: The main issues are _documentation_ and _testing_.

1. *Documentation*: As far as I can tell (and as noted by @kthyng) there seems to be no documentation beyond the two readmes in the subpackages. The argument could perhaps be made that this nearly reaches the bare minimum required to check the "Installation instructions" and "Example usage" boxes, but I don't find it to be sufficient. For example, there should be more discussion of what the examples are trying to convey. The "Functionality documentation" component is not satisfied. For a Python package, we would expect documentation generated using something like Sphinx, and we would expect these docs to include installation instructions, tutorials, and (at least automatically generated) API documentation.
2. *Testing*: While, again, there is an extremely limited test (it appears to just check compilation and that the package imports) this is not sufficient to satisfy the testing requirements of a JOSS submission.

Then other components are such as "Community guidelines" and "Functionality/Performance" are also not fully satisfied, but these are less of a major issue at this stage (but they should be addressed eventually!).

If I've missed something in the repo, please point me to it. Otherwise, please take your time adding these components and I'd be happy to answer questions as you go!

**Comment by kadglass** [comment]
Great, thank you @dfm!  This will probably take us a couple of weeks to put together, so I will let you know when we are ready for you to take a look.

**Comment by dfm** [comment]
@kadglass: Sounds good. I'm going to add the `paused` label. Ping me when you're ready!

**Comment by arfon** [comment]
@whedon remind @arfon in two weeks

@kadglass – how are you getting on here? Given this submission has been paused for quite some time now (> 6 months) if we don't hear back from you that your ready to move forward in the next couple of weeks we will close this submission and encourage a future re-submission when you are ready.

**Comment by whedon** [comment]
Sorry, I can't set reminders on PRE-REVIEW issues.

**Comment by kadglass** [comment]
@arfon - Thank you for checking in!  We are wrapping up the requests made, and should have things ready by the end of this week.  I will update here when we are ready to move forward.

**Comment by kadglass** [comment]
@arfon @dfm We have finished the documentation, which is available at https://vast.readthedocs.io/en/latest/ (the link is also included in the description of the repo).  We are still working on the testing; hopefully it will be complete by the end of the day tomorrow, but I will update here again when that is complete.

**Comment by kadglass** [comment]
@arfon @dfm We have finished implementing the testing for the repository.  Please take a look and let us know of any additional issues that need to be addressed.  Thank you!

**Comment by dfm** [comment]
@kadglass: I'm really sorry that I missed your ping here! Thanks for your patience and all your work here. The docs and tests are looking great. I'm going to remove the `paused` label and start working on recruiting reviewers.

**Comment by dfm** [comment]
@whedon add @changhoonhahn as reviewer

Thanks Chang for agreeing to review!

@kadglass: Thanks for your patience! As soon as I have a second reviewer lined up we'll get the main review going.

**Comment by whedon** [comment]
OK, @changhoonhahn is now a reviewer

**Comment by dfm** [comment]
@whedon add @lavaux as reviewer

Thanks Guilhem for agreeing to review!

I'm going to start up the main review in a new thread. I know that both @changhoonhahn and @lavaux are not available to start the review right away, but I'll keep checking in to make sure that we get when they are ready. Thanks all for agreeing to participate!

**Comment by whedon** [comment]
OK, @lavaux is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4033.
