### ISSUE TITLE
[PRE REVIEW]: fastPLI: A Fiber Architecture Simulation Toolbox for 3D-PLI

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2923]
**Submitting author:** @fmatuschke (<a href="http://orcid.org/0000-0001-6435-5351">Felix Matuschke</a>)
**Repository:** <a href="https://github.com/3d-pli/fastpli" target ="_blank">https://github.com/3d-pli/fastpli</a>
**Version:** v1.0.0
**Editor:** @oliviaguest
**Reviewers:** @vigji
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @fmatuschke. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jni.

@fmatuschke if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.73 s (145.9 files/s, 48652.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              4              2              2          21804
Python                          52           1510           1485           3965
C++                             15            692            202           2978
C/C++ Header                    19            304             69           1451
Markdown                         3             87              0            228
CMake                            5             40             36            207
make                             2             38             11            154
YAML                             2              4              3            122
TeX                              1              7              0             85
Bourne Shell                     1              9             25             40
reStructuredText                 3             18             86             11
-------------------------------------------------------------------------------
SUM:                           107           2711           1919          31045
-------------------------------------------------------------------------------


Statistical information for the repository 'b6c7bd5f86a67c1b4732f215' was
gathered on 2020/12/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
fmatuschke                     623         27035          14390          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
fmatuschke                12656           46.8         12.3                6.68
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fninf.2011.00034 is OK
- 10.3233/APC190017 is OK
- 10.3389/fnana.2018.00075 is OK
- 10.1016/j.neuroimage.2015.02.020 is OK
- 10.1098/rsif.2015.0734 is OK
- 10.1145/2833157.2833162 is OK

MISSING DOIs

- 10.17815/jlsrf-2-121 may be a valid DOI for title: JURECA: General-purpose supercomputer at Jülich Supercomputing Centre

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02923/joss.02923/10.21105.joss.02923.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02923/joss.02923/10.21105.joss.02923.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@oliviaguest are you up for editing this submission?

**Comment by kthyng** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by kthyng** [comment]
@fmatuschke in the meantime, please see the notes above about a missing DOI and statement of need.

**Comment by fmatuschke** [comment]
Hello, I fixed the reference and added the statement of need.

**Comment by oliviaguest** [comment]
@kthyng is it OK with everybody if I take this over after the holidays?

**Comment by danielskatz** [comment]
Just to clean up our AEiC action list, I'm going to assign it to you now, but with the expectation that nothing will happen this week - thanks!

**Comment by danielskatz** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
Hey @fmatuschke 👋  — when you get a chance can you list some [user]names of potential reviewers, please? 😊

**Comment by fmatuschke** [comment]
Hi @oliviaguest, I'm so sorry I missed this. Apparently the holidays were necessary.
I looked through the document and found the following potential reviewers: vigji(luigi.petrucco@gmail.com), caldarolamartin(m.caldarola@tudelft.nl), spinicist(tobias.wood@kcl.ac.uk), AmirHoseinHadian(amir.h.hadian@gmail.com) and neurofractal(rob.seymour@ucl.ac.uk)

**Comment by oliviaguest** [comment]
@whedon invite @vigji as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by oliviaguest** [comment]
@whedon add @vigji as reviewer

**Comment by whedon** [comment]
OK, @vigji is now a reviewer

**Comment by vigji** [comment]
Hi @fmatuschke! I have an important deadline in 10 days time and I will be able to look carefully at the code only after that has been met. 
Moreover I have to warn you in advance that looking very broadly at the package I got the impression it has been developed with Linux in mind (just following the installation instructions gave my macOS compiler some trouble). I can still test it on a Windows, but I would not set up an Ubuntu machine just for the review. If you think you would prefer not to support other OSs because the code would generally run on clusters that use Linux that is obviously fine (it should be specified in the readme), but I could not take up the review. If you're ok with supporting me trying it out on other machines, happy to give it a try, and I will continue the conversation in issues!

**Comment by fmatuschke** [comment]
Hi @vigji. Thanks for pointing out your deadline. That is absolutely not a problem. After all, I know the daily work of a scientist all too well.
The current version is indeed for Linux only. I have added a note in the README. For your information, there are plans to support macOS as well. However, due to the current situation, I don't have access to a macOS system to test everything. On Windows, I test it regularly within the WSL. If you are willing to test it, I would be happy about it. But I can certainly understand the inconvenience.
As a self-taught programmer, I have a lot to learn in this regard as well.

**Comment by vigji** [comment]
Ok, if you regularly work within WSL I can give that a try! And keep testing things on macOS, if that can help. Will come back to this after the 29th.

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02923/joss.02923/10.21105.joss.02923.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02923/joss.02923/10.21105.joss.02923.pdf) :page_facing_up: :point_left:

**Comment by vigji** [comment]
For the sake of keeping this conversation updated, I started the review through issues in the considered repo, as to my understanding that is the way of proceeding right? My plan would be to report here after the points there have been addressed

**Comment by fmatuschke** [comment]
@vigji I am sorry. I was not notified about the issues on the GitHub repository. I will start on them ASAP.  They are all valid points.

**Comment by oliviaguest** [comment]
Also... @fmatuschke could you give me a few more suggestions for reviewers when you get a chance? I have tried a lot of people but many seem to be too busy right now (which is understandable of course).

**Comment by fmatuschke** [comment]
@oliviaguest of course. I have looked at the list again. I found the following possible reviewers:

glyg - guillaume@damcb.com
dxm447 - mukherjeed@ornl.gov
pr4deepr - pradeep.rajasekhar@gmail.com
BjornFJohansson - bjorn_johansson@bio.uminho.pt
JackTyson - jack@mirrorpark.net
tpeulen - thomas-otavio.peulen@ucsf.edu
RealPolitiX - xrpatrick@gmail.com
peerherholz - herholz.peer@gmail.com
ryEllison - ryan.dean.ellison@gmail.com
dr-xenia - Xkobeleva@gmail.com
wmvanvliet - marijn.vanvliet@aalto.fi
martlj - martin.jones@crick.ac.uk
mwegrzyn - martin.wegrzyn@uni-bielefeld.de

Please let me know if you need more help.

**Comment by oliviaguest** [comment]
@vigji we're still in the pre-review. However, if you have already started, I'll go ahead and start the review and then invite any other reviewers from there. When I start the review, please link to any new issues in the software from the review issue, so I and others can keep track of them, please.

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3042.

**Comment by oliviaguest** [comment]
@fmatuschke and @vigji please move to #3042 and take a look at all the relevant information there! 😊

**Comment by glyg** [comment]
Hi all, hi @oliviaguest I think I can take on the review, should I go directly to the other opened issue?

**Comment by oliviaguest** [comment]
Oh, fantastic! And yes, please read: https://github.com/openjournals/joss-reviews/issues/3042#issuecomment-779338987
