### ISSUE TITLE
[PRE REVIEW]: Autosubmit GUI: A Javascript-based Graphical User Interface to Monitor Experiments Workflow Execution

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2924]
**Submitting author:** @wuruchi (<a href="http://orcid.org/0000-0003-0842-0459">Wilmer Uruchi Ticona</a>)
**Repository:** <a href="https://earth.bsc.es/gitlab/wuruchi/autosubmitreact" target ="_blank">https://earth.bsc.es/gitlab/wuruchi/autosubmitreact</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @djmitche
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @wuruchi. **Currently, there isn't an JOSS editor assigned** to your paper.

@wuruchi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/HPCSim.2016.7568429 is OK
- 10.5194/gmd-10-19-2017 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02924/joss.02924/10.21105.joss.02924.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02924/joss.02924/10.21105.joss.02924.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by danielskatz** [comment]
👋 @openjournals/dev - any thought on why 👆 doesn't work?

**Comment by danielskatz** [comment]
👋 @wuruchi - I'm unsure if this fits JOSS, so the editors will now discuss if it meets JOSS's scope for review, specifically to make sure that we consider it research software (and also possible to check the size/scholarly effort of the software). This normally would take about a week, but might take longer due to the holidays.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=199.57 s (130.4 files/s, 17373.8 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code
---------------------------------------------------------------------------------------
JavaScript                           18443         332909         352433        1848572
JSON                                  2832            296              0         369561
Markdown                              2179          88917              4         220358
HTML                                   312          18648            405          64383
TypeScript                            1768           8268          44195          53475
CSS                                    104           1297           2642          20501
C/C++ Header                            42           1342            431           7073
C++                                     22           1292           1096           5645
D                                       20              0              0           5567
YAML                                   213            244            176           4207
XML                                      3            233             11           2011
CoffeeScript                            28            611             54           1649
LESS                                    13            272            745           1630
make                                    20            277            384            988
Bourne Shell                             8            194            132            936
Python                                   4             83            177            798
SVG                                      8             14              5            681
diff                                     1              3             13            588
Windows Module Definition                5             83              0            451
PHP                                      1             33             52             70
JSON5                                    1              0              0             55
TeX                                      1              7              0             46
Bourne Again Shell                       2             11              1             43
TOML                                     1              2              0             39
EJS                                      1              0              0              9
Lisp                                     1              0              0              6
DOS Batch                                1              0              0              2
---------------------------------------------------------------------------------------
SUM:                                 26034         455036         402956        2609344
---------------------------------------------------------------------------------------


Statistical information for the repository '662038724d77940241bd1d35' was
gathered on 2020/12/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Wilmer Uruchi Ticona            59       2258199         102129           61.43
bleudchanel                     68       1098792         375195           38.36
wuruchi                         14          6658           1550            0.21

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
bleudchanel             1084604           98.7          2.1               11.96
wuruchi                 1965759        29524.8          1.8               16.13
```

**Comment by danielskatz** [comment]
@openjournals/dev - never mind my request above - check repository just took a really long time...

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=391.01 s (66.6 files/s, 8867.6 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code
---------------------------------------------------------------------------------------
JavaScript                           18443         332909         353806        1847199
JSON                                  2832            296              0         369561
Markdown                              2179          88917              4         220358
HTML                                   312          18648            405          64383
TypeScript                            1768           8268          44195          53475
CSS                                    104           1297           2642          20501
C/C++ Header                            42           1342            431           7073
C++                                     22           1292           1096           5645
D                                       20              0              0           5567
YAML                                   213            244            176           4207
XML                                      3            233             11           2011
CoffeeScript                            28            611             54           1649
LESS                                    13            272            745           1630
make                                    20            277            384            988
Bourne Shell                             8            194            132            936
Python                                   4             83            177            798
SVG                                      8             14              5            681
diff                                     1              3             13            588
Windows Module Definition                5             83              0            451
PHP                                      1             33             52             70
JSON5                                    1              0              0             55
TeX                                      1              7              0             46
Bourne Again Shell                       2             11              1             43
TOML                                     1              2              0             39
EJS                                      1              0              0              9
Lisp                                     1              0              0              6
DOS Batch                                1              0              0              2
---------------------------------------------------------------------------------------
SUM:                                 26034         455036         404329        2607971
---------------------------------------------------------------------------------------


Statistical information for the repository 'ab1e9a7db33ea546df362da7' was
gathered on 2020/12/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Wilmer Uruchi Ticona            59       2258199         102129           61.43
bleudchanel                     68       1098792         375195           38.36
wuruchi                         14          6658           1550            0.21

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
bleudchanel             1084604           98.7          2.1               11.96
wuruchi                 1965759        29524.8          1.8               16.13
```

**Comment by wuruchi** [comment]
> 👋 @wuruchi - I'm unsure if this fits JOSS, so the editors will now discuss if it meets JOSS's scope for review, specifically to make sure that we consider it research software (and also possible to check the [size/scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) of the software). This normally would take about a week, but might take longer due to the holidays.

Hello @danielskatz. We will be waiting for the editors' answer and we are open to any request. 

As a side note, the users `bleudchanel` and `wuruchi` are both my users. Author `bleudchanel` was introduced when I switched to working from home and forgot to update my git user.

Thank you for your time.

**Comment by arfon** [comment]
> @openjournals/dev - never mind my request above - check repository just took a really long time...

Yeah, I think this is because clones from that server are really slooooooooow.

**Comment by wuruchi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02924/joss.02924/10.21105.joss.02924.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02924/joss.02924/10.21105.joss.02924.pdf) :page_facing_up: :point_left:

**Comment by wuruchi** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by wuruchi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02924/joss.02924/10.21105.joss.02924.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02924/joss.02924/10.21105.joss.02924.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @wuruchi! The editorial board has decided that this submission is in scope, so we can proceed. Next step is to find a handling editor for your submission.

**Comment by kthyng** [comment]
@lorenanicole I know I pinged you on another submission to edit recently, but also wondering if you can take this one on.

**Comment by kthyng** [comment]
@whedon invite @lorenanicole  as editor

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by wuruchi** [comment]
Hello @kthyng 



> Hi @wuruchi! The editorial board has decided that this submission is in scope, so we can proceed. Next step is to find a handling editor for your submission.

Hello @kthyng. That is great news!

**Comment by kyleniemeyer** [comment]
Hello @lorenanicole, just pinging you again on this edit request. Thanks!

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @wuruchi - apologies it has taken so long to assign an editor here. Many of our JOSS editors are extremely busy right now.

Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by wuruchi** [comment]
Hello @arfon 

No worries.

I think any of these reviewers could be a good choice: 

* @desilinguist 
* @pragyansmita
* @djmitche 
* @fil
* @pgadige
* @aokad
* @vc1492a

**Comment by arfon** [comment]
:wave: @ygrange @daissi @wjakethompson @vijaysm - would any of your be willing to review this submission for JOSS?

The submission under review is [_Autosubmit GUI: A Javascript-based Graphical User Interface to Monitor Experiments Workflow Execution_](https://earth.bsc.es/gitlab/wuruchi/autosubmitreact). 

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by wjakethompson** [comment]
I have no Javascript experience, so I'm not sure that I'd be a good fit for this one given that I have no idea what I'd be looking for :smile:.

**Comment by desilinguist** [comment]
Same here. I can't really review JS code.

**Comment by daissi** [comment]
Sorry, I don't have free time currently and no experience with Javascript.

**Comment by ygrange** [comment]
Same point on JS code as the others. I can, and am totally happy to,  look at it functionality-wise and look at things like testing etc.

**Comment by djmitche** [comment]
Not to throw myself under a bus that others seem to be successfully avoiding, but .. I know a bit of React and a lot of JS and can take a look.

**Comment by vijaysm** [comment]
Unfortunately I don't have enough experience with JavaScript and can't do
justice to review the submission. But the tool description does sound
interesting and can offer some comments if I get the time to play with it.
Best.

**Comment by arfon** [comment]
@djmitche - thanks so much! I'll go ahead and assign you now and start the review ✨

**Comment by arfon** [comment]
@whedona add @djmitche as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon add @djmitche as reviewer

**Comment by whedon** [comment]
OK, @djmitche is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3049.

**Comment by arfon** [comment]
@RuneBlaze @ikayz - would either of your be willing to review this submission for JOSS?

The submission under review is [_Autosubmit GUI: A Javascript-based Graphical User Interface to Monitor Experiments Workflow Execution_](https://earth.bsc.es/gitlab/wuruchi/autosubmitreact). 

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by ikayz** [comment]
@arfon The issue has been closed does it still need a review?

**Comment by arfon** [comment]
@ikayz - we're still looking for a second reviewer if you're able to help out!

**Comment by ikayz** [comment]
@arfon sure thing though I don't think I'm part of the repo.

**Comment by arfon** [comment]
Ah OK. I've added you to the review over in https://github.com/openjournals/joss-reviews/issues/3049. Thanks again @ikayz!
