### ISSUE TITLE
[PRE REVIEW]: Python-based Algorithm for Convective Cell Identification and Tracking using DWR Reflectivity Images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2925]
**Submitting author:** @niranjanstudy06 (<a href="http://orcid.org/0000-0002-0625-236X">Niranjan Akella</a>)
**Repository:** <a href="https://github.com/niranjanstudy06/Python-based-Algorithm-for-Convective-Cell-Identification-and-Tracking-using-DWR-Reflectivity-Images.git" target ="_blank">https://github.com/niranjanstudy06/Python-based-Algorithm-for-Convective-Cell-Identification-and-Tracking-using-DWR-Reflectivity-Images.git</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @niranjanstudy06. **Currently, there isn't an JOSS editor assigned** to your paper.

@niranjanstudy06 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (69.8 files/s, 30103.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                 3              0           1076           1228
Python                           3            441            527            732
TeX                              1             18              0            200
Markdown                         2             12              0             77
INI                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            10            471           1603           2240
-------------------------------------------------------------------------------


Statistical information for the repository 'd308aa88044501b7d0223e0a' was
gathered on 2020/12/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
niranjanstudy06                  1          1700              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
niranjanstudy06            1700          100.0          0.0               28.94
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TGRS.2012.2227762 is OK
- 10.2151/jmsj1965.60.1_396 is OK
- 10.1127/0941-2948/2009/359 is OK
- 10.5194/angeo-31-1155-2013 is OK
- 10.1002/2014GL061823 is OK
- doi.org/10.1029/2012GL051242 is OK
- 10.1007/s00703-008-0290-y is OK

MISSING DOIs

- 10.3390/rs12020337 may be a valid DOI for title: Backward Adaptive Brightness Temperature Threshold Technique (BAB3T): A Methodology to Determine Extreme Convective Initiation Regions Using Satellite Infrared Imagery
- 10.1080/02564602.2019.1593890 may be a valid DOI for title: New insights into the convective system characteristics over the Indian summer monsoon region using space based passive and active remote sensing techniques
- 10.1029/jd092id08p09591 may be a valid DOI for title: Mesoscale convective complexes in the Americas

INVALID DOIs

- https://doi.org/10.1175/1520-0450(1992)031<0443:ATACOA>2.0.CO;2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1175/1520-0493(1988)116<0685:MCCOTU>2.0.CO;2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1175/1520-0450(2001)040<1683:ASMTIS>2.0.CO;2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1175/1520-0469(1996)053<1380:MVODCI>2.0.CO;2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/BF01277501 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0022-1694(00)00352-8 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1029/2008GM000838 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1175/MWR-D-19-0070.1 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1175/1520-0493(1987)115<0505:SOCOWM>2.0.CO;2 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @niranjanstudy06 - given the relatively small size of this software, the editors will now discuss if it meets JOSS's scope for review, specifically [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) 
While we are doing this, if you want to make any changes to the references or the paper based on the fact that whedon found a number of missing DOIs and misformed DOIs in your bib file, and the fact that no references were actually embedded in the paper, feel free to do so, then use the commands
* @whedon generate pdf
* @whedon check references

(one at a time, at the start of a new comment) to regenerate the PDF and recheck the references.  See the example paper for how to cite references in the body of the text - https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by niranjanstudy06** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1175/1520-0450(1992)031<0443:ATACOA>2.0.CO;2 is OK
- 10.1175/1520-0493(1988)116<0685:MCCOTU>2.0.CO;2 is OK
- 10.3390/rs12020337 is OK
- 10.1175/1520-0450(2001)040<1683:ASMTIS>2.0.CO;2 is OK
- 10.1175/1520-0469(1996)053<1380:MVODCI>2.0.CO;2 is OK
- 10.1109/TGRS.2012.2227762 is OK
- 10.1007/BF01277501 is OK
- 10.2151/jmsj1965.60.1_396 is OK
- 10.1127/0941-2948/2009/359 is OK
- 10.1016/S0022-1694(00)00352-8 is OK
- 10.1029/2008GM000838 is OK
- 10.1175/MWR-D-19-0070.1 is OK
- 10.5194/angeo-31-1155-2013 is OK
- 10.1002/2014GL061823 is OK
- 10.1175/1520-0493(1987)115<0505:SOCOWM>2.0.CO;2 is OK
- 10.1029/2012GL051242 is OK
- 10.1007/s00703-008-0290-y is OK

MISSING DOIs

- 10.1029/jd092id08p09591 may be a valid DOI for title: Mesoscale convective complexes in the Americas

INVALID DOIs

- 10.1080/02564602.2019.1593890. is INVALID
```

**Comment by niranjanstudy06** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1175/1520-0450(1992)031<0443:ATACOA>2.0.CO;2 is OK
- 10.1175/1520-0493(1988)116<0685:MCCOTU>2.0.CO;2 is OK
- 10.3390/rs12020337 is OK
- 10.1175/1520-0450(2001)040<1683:ASMTIS>2.0.CO;2 is OK
- 10.1175/1520-0469(1996)053<1380:MVODCI>2.0.CO;2 is OK
- 10.1109/TGRS.2012.2227762 is OK
- 10.1007/BF01277501 is OK
- 10.2151/jmsj1965.60.1_396 is OK
- 10.1127/0941-2948/2009/359 is OK
- 10.1016/S0022-1694(00)00352-8 is OK
- 10.1029/2008GM000838 is OK
- 10.1175/MWR-D-19-0070.1 is OK
- 10.5194/angeo-31-1155-2013 is OK
- 10.1002/2014GL061823 is OK
- 10.1175/1520-0493(1987)115<0505:SOCOWM>2.0.CO;2 is OK
- 10.1029/2012GL051242 is OK
- 10.1007/s00703-008-0290-y is OK

MISSING DOIs

- 10.1029/jd092id08p09591 may be a valid DOI for title: Mesoscale convective complexes in the Americas

INVALID DOIs

- 10.1080/02564602.2019.1593890. is INVALID
```

**Comment by niranjanstudy06** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1175/1520-0450(1992)031<0443:ATACOA>2.0.CO;2 is OK
- 10.1175/1520-0493(1988)116<0685:MCCOTU>2.0.CO;2 is OK
- 10.3390/rs12020337 is OK
- 10.1175/1520-0450(2001)040<1683:ASMTIS>2.0.CO;2 is OK
- 10.1175/1520-0469(1996)053<1380:MVODCI>2.0.CO;2 is OK
- 10.1109/TGRS.2012.2227762 is OK
- 10.1007/BF01277501 is OK
- 10.2151/jmsj1965.60.1_396 is OK
- 10.1127/0941-2948/2009/359 is OK
- 10.1016/S0022-1694(00)00352-8 is OK
- 10.1029/2008GM000838 is OK
- 10.1175/MWR-D-19-0070.1 is OK
- 10.5194/angeo-31-1155-2013 is OK
- 10.1080/02564602.2019.1593890 is OK
- 10.1002/2014GL061823 is OK
- 10.1029/JD092iD08p09591 is OK
- 10.1175/1520-0493(1987)115<0505:SOCOWM>2.0.CO;2 is OK
- 10.1029/2012GL051242 is OK
- 10.1007/s00703-008-0290-y is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by niranjanstudy06** [comment]
@whedon generate pdf

**Comment by niranjanstudy06** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: :point_left:

**Comment by niranjanstudy06** [comment]
@whedon query scope

**Comment by whedon** [comment]
I'm sorry @niranjanstudy06, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by niranjanstudy06** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (136.5 files/s, 59432.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                 3              0           1076           1228
Python                           3            441            527            732
TeX                              1             20              0            197
Markdown                         2             33              0             98
INI                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            10            494           1603           2258
-------------------------------------------------------------------------------


Statistical information for the repository 'dffd2e27d3000bb7c8c0826f' was
gathered on 2020/12/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
niranjanstudy06                  1          1700              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
niranjanstudy06            1700          100.0          0.0               28.94
```

**Comment by niranjanstudy06** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: :point_left:

**Comment by niranjanstudy06** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: :point_left:

**Comment by niranjanstudy06** [comment]
@danielskatz, Thank you very much for your guidance, Sir. I have incorporated the necessary changes in my "paper.md" and "paper.bib" files as suggested by you.

**Comment by niranjanstudy06** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: :point_left:

**Comment by niranjanstudy06** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@niranjanstudy06 - sorry, but the idea is not to manually add the references in the References section of the paper, but to add tags to the references from the bib file within the body of the paper, which will automatically cause the references to be added to the references section (and linked from the earlier sections) when the PDF is built - again, I point you to https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

For example, see specifically, `[@astropy]` in the paper as a place where the astropy paper should be cited, and see that `astropy` is one of the labels in the bib file, for the astropy paper.

**Comment by niranjanstudy06** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: :point_left:

**Comment by niranjanstudy06** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: :point_left:

**Comment by niranjanstudy06** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02925/joss.02925/10.21105.joss.02925.pdf) :page_facing_up: :point_left:

**Comment by niranjanstudy06** [comment]
@danielskatz - Yeah, sorry now I got it. Thank you.

**Comment by Kevin-Mattheus-Moerman** [comment]
@niranjanstudy06 you mentioned _"A research paper on this topic has been submitted to the Journal of Atmospheric and Solar-Terrestrial Physics which is currently under review."_. Have you posted a pre-print of that paper anywhere? If so, could you share the link in this thread? If not you could consider it as that journal allows you to do this. Posting that pre-print is not required but would be helpful to us. Either way, could you please explain the difference in content/focus between that paper and this JOSS submission? This would help us determine if that paper doubles on the communicated scholarship or if the focus is sufficiently different. Thanks

**Comment by niranjanstudy06** [comment]
@Kevin-Mattheus-Moerman In the currently submitted JOSS paper, the main focus is entirely on the structural development of the algorithm and its working. The paper submitted to "The Journal of Atmospheric and Solar-Terrestrial Physics" explains about the proposed Python-based algorithm and its comparison with other algorithms in detail with the working examples as an overview of the proposed algorithm. Hence, the submission to "The Journal of Atmospheric and Solar-Terrestrial Physics" is entirely different from the current JOSS submission, which was re-written to explain the working mechanism and the structural integrity of the developed algorithm.

**Comment by arfon** [comment]
@niranjanstudy06 - many thanks for your submission to JOSS. After review by our editorial team, this submission has been deemed out of scope for JOSS and not meeting the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

Additionally, based on a cursory review of this software, it seems like this code could do with substantial effort to improve the packaging (see https://packaging.python.org/tutorials/packaging-projects/ for example).

While a submission to JOSS is not possible, one possible alternative is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
