### ISSUE TITLE
[PRE REVIEW]: GeometricIntegrators.jl: Geometric Numerical Integration in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2926]
**Submitting author:** @michakraus (<a href="http://orcid.org/0000-0001-7637-3979">Michael Kraus</a>)
**Repository:** <a href="https://github.com/JuliaGNI/GeometricIntegrators.jl" target ="_blank">https://github.com/JuliaGNI/GeometricIntegrators.jl</a>
**Version:** v0.7.0
**Editor:** @VivianePons
**Reviewers:** @ChrisRackauckas, @ranocha
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @michakraus. **Currently, there isn't an JOSS editor assigned** to your paper.

@michakraus if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.64 s (397.8 files/s, 88816.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                          207           6814           2109          24052
Markdown                        27            233              0            984
Jupyter Notebook                11              0          22205            410
TeX                              1             21              0            127
YAML                             4              4              0            109
TOML                             3              4              0             61
Bourne Shell                     2              2              0             11
make                             1              6              0             11
-------------------------------------------------------------------------------
SUM:                           256           7084          24314          25765
-------------------------------------------------------------------------------


Statistical information for the repository 'a602babbfa015f9d04f89619' was
gathered on 2020/12/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2926 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02926/joss.02926/10.21105.joss.02926.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02926/joss.02926/10.21105.joss.02926.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/3-540-30666-8 is OK
- 10.1017/CBO9780511614118 is OK
- 10.1137/141000671 is OK
- 10.5334/jors.151 is OK
- 10.1093/imanum/draa022 is OK

MISSING DOIs

- 10.1201/b21563 may be a valid DOI for title: A Concise Introduction to Geometric Numerical Integration

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @michakraus - you might want to check and see if the DOI suggested by whedon is correct, and if so, add it.

**Comment by danielskatz** [comment]
👋 @VivianePons - would you be willing to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @VivianePons as editor

**Comment by whedon** [comment]
@VivianePons has been invited to edit this submission.

**Comment by VivianePons** [comment]
I can but I forgot to set my ooo: I won't be available before Jan 4

**Comment by danielskatz** [comment]
Thanks - I'm going to go ahead and assign it you, and also recognize that nothing will happen until after Jan 4

**Comment by danielskatz** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by VivianePons** [comment]
Hi @michakraus could you check the missing DOI suggested by whedon?

Also, could you look at our [potential reviewer list](https://bit.ly/joss-reviewers) and maybe suggest reviewers (without tagging them with an @).? You can also suggest names outside of the list, just be aware of our [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy)

**Comment by michakraus** [comment]
> Hi @michakraus could you check the missing DOI suggested by whedon?

Thanks, I added the DOI.

> Also, could you look at our [potential reviewer list](https://bit.ly/joss-reviewers) and maybe suggest reviewers (without tagging them with an @).? You can also suggest names outside of the list, just be aware of our [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy)

Potential reviewers from the list are ChrisRackauckas, Datseris and ranocha.

**Comment by VivianePons** [comment]
@whedon assign @ChrisRackauckas as reviewer

**Comment by whedon** [comment]
OK, @ChrisRackauckas is now a reviewer

**Comment by VivianePons** [comment]
@whedon add @ranocha as reviewer

**Comment by whedon** [comment]
OK, @ranocha is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2954.
