### ISSUE TITLE
[REVIEW]: bcdata: An R package for searching & retrieving data from the B.C. Data Catalogue

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2927]
**Submitting author:** @boshek (<a href="http://orcid.org/0000-0002-9270-7884">Samuel Albers</a>)
**Repository:** <a href="https://github.com/bcgov/bcdata" target ="_blank">https://github.com/bcgov/bcdata</a>
**Version:** 0.2.1
**Editor:** @arfon
**Reviewer:** @tweed1e, @MilesMcBain
**Archive:** <a href="https://doi.org/10.5281/zenodo.4737824" target="_blank">10.5281/zenodo.4737824</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5f72a500b49b303cf497fa6ad434af43/status.svg)](https://joss.theoj.org/papers/5f72a500b49b303cf497fa6ad434af43)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5f72a500b49b303cf497fa6ad434af43"><img src="https://joss.theoj.org/papers/5f72a500b49b303cf497fa6ad434af43/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5f72a500b49b303cf497fa6ad434af43/status.svg)](https://joss.theoj.org/papers/5f72a500b49b303cf497fa6ad434af43)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bcgov/bcdata" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@tweed1e & @MilesMcBain, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bcgov/bcdata">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@boshek) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bcgov/bcdata">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@boshek) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tweed1e, @MilesMcBain it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2927 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02927/joss.02927/10.21105.joss.02927.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02927/joss.02927/10.21105.joss.02927.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@tweed1e, @MilesMcBain - This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/2927 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

Our bot Whedon will send an automated reminder in a couple of weeks to see how you're getting along.

**Comment by tweed1e** [comment]
> I confirm that I have read the JOSS conflict of interest (COI) policy and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

A potential COI is that I work for the Canadian federal government and this package was developed by the BC provincial government. But I've never worked with the authors of the pkg. @arfon can you waive that COI?

**Comment by arfon** [comment]
> A potential COI is that I work for the Canadian federal government and this package was developed by the BC provincial government. But I've never worked with the authors of the pkg. @arfon can you waive that COI?

Yes, this is fine. Thanks for disclosing this - please proceed.

**Comment by MilesMcBain** [comment]
Sorry @arfon I can't check boxes in the lists, probably because the collaborator invite expired?

**Comment by arfon** [comment]
@whedon re-invite @MilesMcBain as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@milesmcbain please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
> Sorry @arfon I can't check boxes in the lists, probably because the collaborator invite expired?

Yes, I think so. Please try the invite link again as I've now re-invited you.

**Comment by whedon** [comment]
:wave: @tweed1e, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @MilesMcBain, please update us on how your review is going.

**Comment by MilesMcBain** [comment]
Hi @whedon and @afron Things are progressing smoothly so far. I'm part-way through verifying the functionality. I don't anticipate this software generating major issues or requiring extra time based on what I have seen so far. :+1:

**Comment by tweed1e** [comment]
@whedon pretty slow, but I hope to make progress soon.

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by MilesMcBain** [comment]
I've finished my first pass review. 

This is a really great package, potentially best in class. 

The `dbplyr` backend for the `WFS` API is a genuinely novel development for these types of packages, and I hope it is copied by other similar packages. 

I also appreciate from an end user's perspective the attention to detail in the print methods, messages, errors, and warnings. It's quite chatty in a reassuring way, and I think it lowers the level of R experience required for good results significantly.

The documentation is high quality, especially the three vignettes, which do a good job of unveiling features without overwhelming.

There are a few issues to resolve but all fairly minor. Congratulations to the authors!

Current blockers to acceptance are:
* https://github.com/bcgov/bcdata/issues/244
* https://github.com/bcgov/bcdata/issues/246
* https://github.com/bcgov/bcdata/issues/245
* https://github.com/bcgov/bcdata/issues/242

And I would strongly recommend taking some action to rectify usability feedback item 5 (UF5):
* https://github.com/bcgov/bcdata/issues/243

**Comment by boshek** [comment]
Thank you @MilesMcBain! Your kind words are very much appreciated and your extensive feedback even more so. You've done us and the package such a service. Looking forward to digging into your feedback.

**Comment by boshek** [comment]
@tweed1e - should we consider your review finished now? We are looking to triage and plan how we are going to address the review.

**Comment by tweed1e** [comment]
Yes, sorry for the delay, consider it finished. I still have final
(positive) thoughts to write down but they shouldn’t make extra work for
you or conflict with the other reviewer’s comments.

**Comment by ateucher** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by ateucher** [comment]
@whedon commands

**Comment by whedon** [comment]
PDF failed to compile for issue #2927 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: tlsv1 alert internal error (OpenSSL::SSL::SSLError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:996:in `connect'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/compilers.rb:106:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/compilers.rb:13:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:59:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by ateucher** [comment]
@whendon commands

**Comment by ateucher** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by ateucher** [comment]
@whedon @arfon we have now finished addressing the reviewer's comments:

@MilesMcBain's review identified several blockers to acceptance:

 - bcgov/bcdata#244: Addressed by bcgov/bcdata#266
 - bcgov/bcdata#246: Addressed by bcgov/bcdata#261
 - bcgov/bcdata#245: Addressed by bcgov/bcdata#263
 - bcgov/bcdata#242: Addressed by bcgov/bcdata#266

He also had one issue which he strongly recommended we address in terms of user-experience:

- bcgov/bcdata#243: Addressed by bcgov/bcdata#258

@MilesMcBain also had several other [excellent suggestions](https://github.com/bcgov/bcdata/issues/239) that would make the package better and more consistent for users, and we did address all of those that were possible:

- UF1: bcgov/bcdata#240, Closed by bcgov/bcdata#264
- UF2: bcgov/bcdata#241, Closed by bcgov/bcdata#259
- UF3: bcgov/bcdata#265, Closed by bcgov/bcdata#267
- UF4: Unfixable, See this [comment](https://github.com/bcgov/bcdata#239#issuecomment-762187642)

@tweed1e had [one blocker to acceptance](https://github.com/bcgov/bcdata/issues/248), which was addressed by bcgov/bcdata#263

Overall the review process was excellent and has made the package, and the paper, much better. Thank you very much to both reviewers!

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arfon** [comment]
@ateucher - many thanks for the detailed response.

@tweed1e, @MilesMcBain - please could you come and take another look at this submission and see if these updates address your feedback? If they do, please update your checklists accordingly, if not, please let us know why.

**Comment by MilesMcBain** [comment]
Hi @afron, all boxes now checked from my perspective. :+1:

**Comment by arfon** [comment]
@boshek - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by boshek** [comment]
Thanks @arfon 

Here is the Zenodo badge: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4737824.svg)](https://doi.org/10.5281/zenodo.4737824)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4737824 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4737824" target="_blank">10.5281/zenodo.4737824</a> is the archive.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2927 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02927/joss.02927/10.21105.joss.02927.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02927/joss.02927/10.21105.joss.02927.pdf) :page_facing_up: :point_left:

**Comment by ateucher** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02927/joss.02927/10.21105.joss.02927.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02927/joss.02927/10.21105.joss.02927.pdf) :page_facing_up: :point_left:

**Comment by boshek** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02927/joss.02927/10.21105.joss.02927.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02927/joss.02927/10.21105.joss.02927.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01686 is OK
- 10.32614/RJ-2018-009 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1390943947397152769) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2289
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02927](https://doi.org/10.21105/joss.02927)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@tweed1e, @MilesMcBain - many thanks for your reviews here! JOSS relies upon the volunteer efforts of people like you and we simply wouldn't be able to do this without you ✨ 

@boshek - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02927/status.svg)](https://doi.org/10.21105/joss.02927)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02927">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02927/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02927/status.svg
   :target: https://doi.org/10.21105/joss.02927
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02927/status.svg)](https://doi.org/10.21105/joss.02927)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
