### ISSUE TITLE
[PRE REVIEW]: GOFIG: A Tool for Gene Ontology Enrichment Analysis and Visualization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2928]
**Submitting author:** @adidevara (<a href="http://orcid.org/0000-0002-7014-3029">Aditya Devarakonda</a>)
**Repository:** <a href="https://github.com/adidevara/GOFIG" target ="_blank">https://github.com/adidevara/GOFIG</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @adidevara. **Currently, there isn't an JOSS editor assigned** to your paper.

@adidevara if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (173.3 files/s, 33311.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                1             80             44            629
Markdown                         4            150              0            208
TeX                              1              2              0             40
-------------------------------------------------------------------------------
SUM:                             6            232             44            877
-------------------------------------------------------------------------------


Statistical information for the repository '55e15b15bf85d7c7870df911' was
gathered on 2020/12/26.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18129/B9.bioc.org.Hs.eg.db is OK
- 10.1093/nar/gkv007 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02928/joss.02928/10.21105.joss.02928.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02928/joss.02928/10.21105.joss.02928.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @adidevara - I'm unsure if this fits JOSS, so the editors will now discuss if it meets JOSS's scope for review, specifically to make sure that we consider it research software (and also possible to check the [size/scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) of the software). This normally would take about a week, but might take longer due to the holidays.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@adidevara - many thanks for your submission to JOSS. A review by our editorial team has concluded that this submission is out of scope for JOSS due to it's [limited size/scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
