### ISSUE TITLE
[REVIEW]: Web-based text anonymization with Node.js: Introducing NETANOS (Named entity-based Text Anonymization for Open Science)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#293]
**Submitting author:** @ben-aaron188 (<a href="http://orcid.org/0000-0003-1658-9086">Bennett Kleinberg</a>)
**Repository:** <a href="https://github.com/ben-aaron188/netanos" target ="_blank">https://github.com/ben-aaron188/netanos</a>
**Version:** v1.1.5
**Editor:** @acabunoc
**Reviewer:** @RichardLitt
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.817892" target="_blank">10.5281/zenodo.817892</a>

## Status

[![status](http://joss.theoj.org/papers/cd40892f7ea198aded1bc90ba33c6655/status.svg)](http://joss.theoj.org/papers/cd40892f7ea198aded1bc90ba33c6655)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/cd40892f7ea198aded1bc90ba33c6655"><img src="http://joss.theoj.org/papers/cd40892f7ea198aded1bc90ba33c6655/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/cd40892f7ea198aded1bc90ba33c6655/status.svg)](http://joss.theoj.org/papers/cd40892f7ea198aded1bc90ba33c6655)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ben-aaron188/netanos" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ben-aaron188/netanos">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1.0)?
- [x] **Authorship:** Has the submitting author (@ben-aaron188) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @RichardLitt it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by RichardLitt** [comment]
Version: The GitHub release does not match, and the npm release is now ahead of the release for this review (as it is 1.1.3, instead of 1.1.0). I don't know how to best suggest moving forward; perhaps committing and tagging a GitHub release as 1.1.3, and then updating this submission here?

**Comment by RichardLitt** [comment]
Opened issues for Version and References. Otherwise, this is all good. Note: not sure what to do about versions. See above.

**Comment by RichardLitt** [comment]
Note: I am happy with the changes I suggested in https://github.com/openjournals/joss-reviews/issues/283. These have now been fixed.

**Comment by ben-aaron188** [comment]
@RichardLitt Thanks for pointing that versioning issue out. We've tried to address this as follows:

1. Latest version is in the GitHub repo
2. Latest version is in the npm release with v1.1.4
3. On the GitHub repo, we created a release tag to the master branch with v1.1.4 and refer to the npm link in the release description

Does this sound like an option? We would need to change the version for the JOSS submission then though.

**Comment by RichardLitt** [comment]
Sounds good to me! Changing the version in the JOSS submission also seems like a smart move. @arfon that's the last thing that needs to be done, and then I consider this to be worthy of accepting as is.

**Comment by RichardLitt** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by RichardLitt** [comment]
@arfon Looks like we need to have an 'Update version' command, and an 'accept paper' command.

**Comment by arfon** [comment]
> @arfon Looks like we need to have an 'Update version' command, and an 'accept paper' command.

👍 yep, that's next on my todo list.

**Comment by arfon** [comment]
@ben-aaron188 - Could you move the references you currently have in the `paper.md` file into a `paper.bib` file and cite them directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

I've also made a small fix to your paper meta data here: https://github.com/ben-aaron188/netanos/pull/7

After fixing these two items up, could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by ben-aaron188** [comment]
@arfon The references are updated and the pull request is merged. To avoid any versioning inaccuracies with npm, we’ve updated the npm release with these changes (which unfortunately implied that we needed to provide a new version in the `package.json`).
If possible, could you update the JOSS version to `v1.1.5`?

We’ve linked the `v1.1.5` tree in the master branch to Zenodo. Here’s the DOI 10.5281/zenodo.817892

The bagde is here (already included at the top of the readme):
[![DOI](https://zenodo.org/badge/86087510.svg)](https://zenodo.org/badge/latestdoi/86087510)

**Comment by RichardLitt** [comment]
Small note: thanks @ben-aaron188 for being so receptive to changes and fixes!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.817892 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.817892" target="_blank">10.5281/zenodo.817892</a> is the archive.

**Comment by arfon** [comment]
@RichardLitt many thanks for your review here ✨ 

@ben-aaron188 - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00293 ⚡️:rocket: :boom:

**Comment by ben-aaron188** [comment]
@RichardLitt Thanks for your helpful review and for taking the time with this tool! Much appreciated. 

@arfon What a fantastic, smooth review process this is. I will recommend your journal to colleagues eager to put their open source research software out there! I think this kind of open reviewing will be the future of academic peer reviewing soon!

**Comment by arfon** [comment]
> @arfon What a fantastic, smooth review process this is. I will recommend your journal to colleagues eager to put their open source research software out there! I think this kind of open reviewing will be the future of academic peer reviewing soon!

💖 Thanks!
