### ISSUE TITLE
[PRE REVIEW]: IndeterminateBeam: A Python package for solving 1D indeterminate beams

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2930]
**Submitting author:** @jessebonanno (<a href="http://orcid.org/0000-0002-4996-6813">Jesse Bonanno</a>)
**Repository:** <a href="https://github.com/JesseBonanno/IndeterminateBeam" target ="_blank">https://github.com/JesseBonanno/IndeterminateBeam</a>
**Version:** v1.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jessebonanno. **Currently, there isn't an JOSS editor assigned** to your paper.

@jessebonanno if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (222.0 files/s, 28392.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            340            658            795
Markdown                         3             80              0            200
reStructuredText                 6            129             83            147
TeX                              2             14              2            138
Jupyter Notebook                 3              0            548            122
DOS Batch                        1              8              1             26
JSON                             1              0              0             14
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            26            575           1299           1451
-------------------------------------------------------------------------------


Statistical information for the repository 'b8d37468bdbf7eff7cfdfc9d' was
gathered on 2020/12/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
JesseBonanno                    31         37978          36185          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
JesseBonanno               1793            4.7          0.2               10.43
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/jose.00065 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2930 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @jessebonanno - I'm unsure if this fits JOSS, so the editors will now discuss if it meets JOSS's scope for review, specifically to make sure that we consider it research software (and also possible to check the [size/scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) of the software). This normally would take about a week, but might take longer due to the holidays.

Also, I notice that your paper does not compile due to an error in the affiliations, specifically that you didn't list one for you.  Please add an affiliation, following the example in [our sample](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography), and then add a comment here starting with ```@whedon generate pdf``` to regenerate the PDF.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by JesseBonanno** [comment]
Hi @danielskatz - I agree that it appeared to be fairly weak when considering the scope. I mainly have submitted this with consideration that it was a significant improvement to a [previous published article](https://jose.theoj.org/papers/10.21105/jose.00065) (in fact that is how I found out about JOSS). 

Okay, I didn't get the affiliation error when I used the [Whedon paper preview service](https://whedon.theoj.org/preview?id=068ec2a59412dbb21e39353c). Just letting you know in case this is something you would like to flag on your end.

I don't actually have any affiliations and have done this independently to help with creating higher order structural engineering python projects. I will add a blank affiliations section and hopefully that effectively resolves the issue, and is also okay by the JOSS criteria.

**Comment by JesseBonanno** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2930 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:213:in `parse_affiliations': undefined method `each' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:199:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by JesseBonanno** [comment]
@danielskatz - I am going to add a dummy affiliation in named "None" as suggested in this [issue thread](https://github.com/openjournals/joss/issues/406).

**Comment by JesseBonanno** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02930/joss.02930/10.21105.joss.02930.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02930/joss.02930/10.21105.joss.02930.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@JesseBonanno - many thanks for your submission to JOSS. After a review by our editorial team, this submission has been determined as out of scope for JOSS.

> I agree that it appeared to be fairly weak when considering the scope. I mainly have submitted this with consideration that it was a significant improvement to a [previous published article](https://jose.theoj.org/papers/10.21105/jose.00065) (in fact that is how I found out about JOSS). 

Please note, your earlier comment (and link) was to a [_JOSE_ ](http://jose.theoj.org) paper, and we believe this submission may be better suited for that journal too.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by JesseBonanno** [comment]
@arfon My mistake, thank you for pointing it out!
