### ISSUE TITLE
[PRE REVIEW]: registr 2.0: Incomplete Curve Registration for Exponential Family Functional Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2931]
**Submitting author:** @bauer-alex (<a href="http://orcid.org/0000-0003-3495-5131">Alexander Bauer</a>)
**Repository:** <a href="https://github.com/julia-wrobel/registr" target ="_blank">https://github.com/julia-wrobel/registr</a>
**Version:** 2.0.0
**Editor:** @mbobra
**Reviewers:** @munkm, @qpmnguyen
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @bauer-alex. **Currently, there isn't an JOSS editor assigned** to your paper.

@bauer-alex if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (434.0 files/s, 61269.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               30            500           1144           2050
HTML                             2             76              4           1241
Markdown                         5             96              0            318
Rmd                              3            286            568            278
TeX                              3             20              0            149
C++                              4             14             46            106
YAML                             1              5              1             11
Bourne Shell                     1              0              0              5
-------------------------------------------------------------------------------
SUM:                            49            997           1763           4158
-------------------------------------------------------------------------------


Statistical information for the repository 'c5f12879b4a716a79fdbb3cd' was
gathered on 2020/12/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Julia Wrobel                     5           187             21          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Julia Wrobel                153           81.8          0.4               28.76
julia-wrobel                 13          100.0          3.5               15.38
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v040.i08 is OK
- 10.1002/sta4.109 is OK

MISSING DOIs

- 10.1016/j.csda.2016.07.010 may be a valid DOI for title: A note on modeling sparse exponential-family functional response curves
- 10.1016/j.csda.2013.02.005 may be a valid DOI for title: RcppArmadillo: Accelerating R with high-performance C++ linear algebra
- 10.21105/joss.00557 may be a valid DOI for title: register: Registration for Exponential Family Functional Data
- 10.1007/978-3-319-55846-2_35 may be a valid DOI for title: Registration for exponential family functional data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02931/joss.02931/10.21105.joss.02931.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02931/joss.02931/10.21105.joss.02931.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @bauer-alex - note that whedon thinks some of your references might be missing DOIs - if it is correct, please add them, then use the commands
* ```@whedon generate PDF```
* ```@whedon check references```
(each at the start of a new comment) to check again and regenerate the PDF

**Comment by danielskatz** [comment]
Note that this is a new version of https://doi.org/10.21105/joss.00557 (from about 3 years ago), and should be checked to make sure it has enough new content for JOSS to re-review it

**Comment by danielskatz** [comment]
👋 @galessiorob - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by danielskatz** [comment]
Sorry, @galessiorob - I see you also have another request - please ignore this one

**Comment by danielskatz** [comment]
👋 @mbobra - would you be willing to edit this submission for JOSS? (and I know that you are out through 4 Jan, so I'm not expecting an immediate response)

**Comment by danielskatz** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by bauer-alex** [comment]
@whedon generate PDF

**Comment by bauer-alex** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.csda.2016.07.010 is OK
- 10.21105/joss.00557 is OK
- 10.1111/biom.12963 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02931/joss.02931/10.21105.joss.02931.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02931/joss.02931/10.21105.joss.02931.pdf) :page_facing_up: :point_left:

**Comment by bauer-alex** [comment]
All missing doi's are now included. Thanks for the hint!

**Comment by mbobra** [comment]
@danielskatz Sorry for the late reply, I don't know why the ooo bot messages don't show up 😕

**Comment by mbobra** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
@bauer-alex Thanks for your submission! Please give me a few days to find some reviewers and then we'll start the review.

**Comment by bauer-alex** [comment]
@whedon generate PDF

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02931/joss.02931/10.21105.joss.02931.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02931/joss.02931/10.21105.joss.02931.pdf) :page_facing_up: :point_left:

**Comment by bauer-alex** [comment]
@whedon generate PDF

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02931/joss.02931/10.21105.joss.02931.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02931/joss.02931/10.21105.joss.02931.pdf) :page_facing_up: :point_left:

**Comment by bauer-alex** [comment]
I made one more slight edit in the paper. The above generated pdf contains the most current version.

**Comment by mbobra** [comment]
@whedon assign @munkm as reviewer

**Comment by whedon** [comment]
OK, @munkm is now a reviewer

**Comment by mbobra** [comment]
Apologies @bauer-alex -- I am having trouble soliciting reviewers. I'm still working on it. Hopefully we'll kick the review off next week.

**Comment by mbobra** [comment]
@whedon add @qpmnguyen as reviewer

**Comment by whedon** [comment]
OK, @qpmnguyen is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2964.

**Comment by mbobra** [comment]
@bauer-alex @munkm @qpmnguyen See you over in #2964 where we'll do the review.
