### ISSUE TITLE
[PRE REVIEW]: sboxgates: A program for finding low gate count implementations of S-boxes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2932]
**Submitting author:** @dansarie (<a href="http://orcid.org/0000-0001-9246-0263">Marcus Dansarie</a>)
**Repository:** <a href="https://github.com/dansarie/sboxgates" target ="_blank">https://github.com/dansarie/sboxgates</a>
**Version:** v1.1.0
**Editor:** @VivianePons
**Reviewers:** @gradvohl, @gcdeshpande
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @dansarie. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @VivianePons.

@dansarie if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.65 s (23.1 files/s, 5965.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                5            245            220           2305
SVG                              1              0             68            335
C/C++ Header                     5             77            132            149
Markdown                         1             33              0            126
XSD                              1             17             13             63
YAML                             1              5              0             50
CMake                            1              7             16             14
-------------------------------------------------------------------------------
SUM:                            15            384            449           3042
-------------------------------------------------------------------------------


Statistical information for the repository 'f02402affcb18c24ee627f61' was
gathered on 2021/01/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aram                             1            40             21            0.28
Marcus                           9           784            531            6.05
Marcus Dansarie                 99         11697           8662           93.67

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aram                          9           22.5         20.0                0.00
Marcus Dansarie            3119           26.7         19.9               14.62
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2932 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02932/joss.02932/10.21105.joss.02932.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02932/joss.02932/10.21105.joss.02932.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @VivianePons as editor

:wave: @VivianePons - happy new year! Would you be willing to edit this submission for JOSS? It's not clear if this submission needs a scope check by the editorial team first so please let me know if you think we should review for scope.

**Comment by whedon** [comment]
@VivianePons has been invited to edit this submission.

**Comment by VivianePons** [comment]
Sure!

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by VivianePons** [comment]
@arfon I read the paper and it looks quite convincing for being on scope. What made you hesitate?

**Comment by VivianePons** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BFb0052352 is OK
- 10.1007/11545262_32 is OK
- 10.1007/3-540-45848-4_57 is OK
- 10.3233/SAT190099 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by VivianePons** [comment]
Hi @dansarie thank you very much for submitting your paper.

Could you look at our [potential reviewer list](https://bit.ly/joss-reviewers) and maybe suggest reviewers (without tagging them with an @).? You can also suggest names outside of the list, just be aware of our [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy)

**Comment by dansarie** [comment]
Hi @VivianePons!

Here are some suggested reviewers from the list: vissarion, Brnikat, gcdeshpande. skadio also appears to be a good fit for the topic area, but does not have C listed as a preferred/other programming language.

**Comment by arfon** [comment]
> @arfon I read the paper and it looks quite convincing for being on scope. What made you hesitate?

Oh nothing really. Just that ~2000 LOC (in C) might be considered on the smaller-side of things for us. Happy to proceed if you think this is 👍

**Comment by VivianePons** [comment]
@whedon set @gradvohl as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by VivianePons** [comment]
@whedon assign @gradvohl as reviewer

**Comment by whedon** [comment]
OK, @gradvohl is now a reviewer

**Comment by gradvohl** [comment]
# Review itens for JOSS paper #2932
**Paper title**: sboxgates: A program for finding low gate count implementations of S-boxes

## Review criteria
* A list of the authors of the software: :heavy_check_mark:
* Author affiliations: :heavy_check_mark:
* A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience: :heavy_check_mark:
* A clear statement of need that illustrates the purpose of the software: :heavy_check_mark:
* Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it: :heavy_check_mark:
* A list of key references including a link to the software archive:  :heavy_check_mark:

## Review items
* Software license: :thumbsup: (good - GPL v3) 

* Documentation: 
    * A statement of need: :thumbsup: (good) 
    * Installation instructions: :wave: (sort of -- Please see the following Compilation section) 
    * Example usage: :wave: (sort of) 
    * API documentation: :thumbsup: (good -- Please see the following Documentation section) 
    * Community guidelines: :thumbsup: (good)
    * Functionality: :wave: (sort of -- Please see the following Compilation section). 
    * Tests: :thumbsdown: (bad)

* Software paper
    * Authors: :heavy_check_mark:
    * A statement of need: :heavy_check_mark:
    * References: :heavy_check_mark:

## Reviewer comments
The following comments refer to items I considered  that could be improved a little more, although they currently met the requirements for JOSS submission.

### Documentation in source code
The author comments on some functions in the .h files, while other comments are in .c files. Also, most of the comments describe the functions at a high level only. It would be interesting to say what the parameters are and what they are needed for.

**Suggestion**: Uniform where you will write the comments and, if possible, use a standard for documentation of functions, parameters, and returns (such as [Doxygen](https://www.doxygen.nl)).

### Compilation
- When I tried to build the software with `cmake` it required the CMake 3.10 or higher. 

- **Suggestion**: Inform the user what are the required versions (especially CMake).

- When I tried to `cmake ..`, it raised the following error:
`-- Could NOT find MPI_C (missing: MPI_mpich_LIBRARY MPI_opa_LIBRARY MPI_mpl_LIBRARY MPI_C_WORKS)`

- **Suggestion**: Inform the user what are the main environment variables must be set. Besides, I suspect that `mpich-devel` is also a dependency.

### Questions:
When running with mpirun, may the user specify the number of processes and `hostfile` with processes location (for instance, `mpirun -np 4 --hostfile file ...`? If so, the author should clarify this in the instructions for running the software.
 
 ### Other suggestions: 
1. Please consider to add the author's name and contact info in the `README.md`.
2. In `paper.md`, the author states that CUDA is a "programming language for GPUs". However, CUDA is an Application Programming Interface (API) or a library, if you prefer.
 
## Conclusion
Analyzing all the aspects mentioned earlier, I rank the paper as **minor revisions** needed. I would like to ask the author to provide the corrections, especially in the compilation issues, for another round of installation and tests.

**Comment by VivianePons** [comment]
@whedon add @gcdeshpande as reviewer

**Comment by whedon** [comment]
OK, @gcdeshpande is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2946.
