### ISSUE TITLE
[PRE REVIEW]: SAR tools: A QGIS plugin for generating SAR descriptors

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2933]
**Submitting author:** @Narayana-Rao (<a href="http://orcid.org/0000-0002-6496-7283">NR Bhogapurapu</a>)
**Repository:** <a href="https://github.com/Narayana-Rao/SAR-tools" target ="_blank">https://github.com/Narayana-Rao/SAR-tools</a>
**Version:** v0.6
**Editor:** @hugoledoux
**Reviewers:** @liberostelios, @HenrikJanPersson
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Narayana-Rao. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @usethedata.

@Narayana-Rao if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.87 s (45.0 files/s, 14050.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      14           2200           2243           8329
SVG                              1              0              0           2671
Python                          17            812            584           2169
HTML                            17           1827             45           1872
CSS                              6            349             49           1139
Qt                               1             13              0            788
make                             2             62             61            251
DOS Batch                        2             23              1            140
Markdown                         2             29              0             97
reStructuredText                15             76             57             97
TeX                              1              8              0             84
Bourne Shell                     3             14             11             71
YAML                             2              5             23             33
Qt Linguist                      1              0              0             11
-------------------------------------------------------------------------------
SUM:                            84           5418           3074          17752
-------------------------------------------------------------------------------


Statistical information for the repository '7144b2a49de5fa09b7121090' was
gathered on 2021/01/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dipankar Mandal                  6            84             19            0.50
Narayana Rao Bhogapu             1             2              2            0.02
Narayana-Rao                    29         18278           2011           98.38
Subhadip Dey                     8           116            111            1.10

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dipankar Mandal              64           76.2          1.0               29.69
Narayana Rao Bhogapu          2          100.0          1.0                0.00
Narayana-Rao              16199           88.6          0.3               16.64
Subhadip Dey                 72           62.1          1.6                2.78
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TGRS.2009.2014944 is OK

MISSING DOIs

- 10.1016/j.rse.2020.111954 may be a valid DOI for title: Dual polarimetric radar vegetation index for crop growth monitoring using sentinel-1 SAR data
- 10.1109/tgrs.2020.2976661 may be a valid DOI for title: A Radar Vegetation Index for Crop Monitoring Using Compact Polarimetric SAR Data
- 10.36227/techrxiv.11482434 may be a valid DOI for title: Target Characterization and Scattering Power Decomposition for Full and Compact Polarimetric SAR Data
- 10.1109/lgrs.2019.2907703 may be a valid DOI for title: A generalized volume scattering model-based vegetation index from polarimetric SAR data
- 10.1109/tgrs.2018.2848285 may be a valid DOI for title: Polarimetric Radar Vegetation Index for Biomass Estimation in Desert Fringe Ecosystems
- 10.1016/0030-4018(77)90292-9 may be a valid DOI for title: Degree of polarization and the principal idempotents of the coherency matrix

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2933 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:204:in `block in parse_authors': Author (Subhadip Dey) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@Narayana-Rao - please note you have a typo in your paper - affiliations is mis-spelt for the following authors:

```
  - name: Subhadip Dey
    orcid: 0000-0002-4979-0192
    affliation: 1
  - name: Dipankar Mandal
    orcid: 0000-0001-8407-7125
    affliation: 1
  - name: Avik Bhattacharya
    orcid: 0000-0001-6720-6108
    affliation: 1
  - name: Y. S. Rao
    affliation: 1
```

Your paper is also missing the required 'Statement of need' section.

Also, if you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by arfon** [comment]
@whedon invite @usethedata as editor.

:wave: @usethedata happy new year! Would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@usethedata has been invited to edit this submission.

**Comment by Narayana-Rao** [comment]
@arfon Thank you for your time. I have updated the .md file.

@whedon generate pdf
@whedon check references

**Comment by Narayana-Rao** [comment]
@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02933/joss.02933/10.21105.joss.02933.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02933/joss.02933/10.21105.joss.02933.pdf) :page_facing_up: :point_left:

**Comment by Narayana-Rao** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TGRS.2009.2014944 is OK

MISSING DOIs

- 10.1016/j.rse.2020.111954 may be a valid DOI for title: Dual polarimetric radar vegetation index for crop growth monitoring using sentinel-1 SAR data
- 10.1109/tgrs.2020.2976661 may be a valid DOI for title: A Radar Vegetation Index for Crop Monitoring Using Compact Polarimetric SAR Data
- 10.36227/techrxiv.11482434 may be a valid DOI for title: Target Characterization and Scattering Power Decomposition for Full and Compact Polarimetric SAR Data
- 10.1109/lgrs.2019.2907703 may be a valid DOI for title: A generalized volume scattering model-based vegetation index from polarimetric SAR data
- 10.1109/tgrs.2018.2848285 may be a valid DOI for title: Polarimetric Radar Vegetation Index for Biomass Estimation in Desert Fringe Ecosystems
- 10.1016/0030-4018(77)90292-9 may be a valid DOI for title: Degree of polarization and the principal idempotents of the coherency matrix

INVALID DOIs

- None
```

**Comment by Narayana-Rao** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.rse.2020.111954 is OK
- 10.1016/j.jag.2020.102052 is OK
- 10.1109/tgrs.2020.2976661 is OK
- 10.1016/j.isprsjprs.2020.09.010 is OK
- 10.1109/lgrs.2019.2907703 is OK
- 10.1109/tgrs.2018.2848285 is OK
- 10.1109/TGRS.2009.2014944 is OK
- 10.1016/0030-4018(77)90292-9 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.5589/m12-043 is INVALID
```

**Comment by Narayana-Rao** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.rse.2020.111954 is OK
- 10.1016/j.jag.2020.102052 is OK
- 10.1109/tgrs.2020.2976661 is OK
- 10.1016/j.isprsjprs.2020.09.010 is OK
- 10.1109/lgrs.2019.2907703 is OK
- 10.1109/tgrs.2018.2848285 is OK
- 10.1109/TGRS.2009.2014944 is OK
- 10.1016/0030-4018(77)90292-9 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by hugoledoux** [comment]
> 👋 @usethedata happy new year! Would you be willing to edit this submission for JOSS?

if @usethedata cannot, I could do this. I teach with QGIS and I know some people in the SAR community

**Comment by arfon** [comment]
⚡ let's do it. Thanks @hugoledoux!

**Comment by arfon** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by hugoledoux** [comment]
@whedon add @liberostelios as reviewer

**Comment by whedon** [comment]
OK, @liberostelios is now a reviewer

**Comment by hugoledoux** [comment]
@whedon add @HenrikJanPersson as reviewer

**Comment by whedon** [comment]
OK, @HenrikJanPersson is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2970.
