### ISSUE TITLE
[PRE REVIEW]: minimo: a linked data and metadata storage system for small labs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2934]
**Submitting author:** @borchardt (<a href="http://orcid.org/0000-0001-9033-6365">Jackson Borchardt</a>)
**Repository:** <a href="https://github.com/focolab/minimo.git" target ="_blank">https://github.com/focolab/minimo.git</a>
**Version:** v1.0.0
**Editor:** @majensen
**Reviewers:** @junjun-zhang, @bensonml
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @borchardt. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @majensen.

@borchardt if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.20 s (173.3 files/s, 20367.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             2              0              0            955
EJS                             18            383             27            920
JavaScript                       8            153            217            597
CSS                              2             66              5            317
Markdown                         1             57              0            115
SVG                              1              0              0             79
YAML                             1              6              3             76
Dockerfile                       1              5              7              7
-------------------------------------------------------------------------------
SUM:                            34            670            259           3066
-------------------------------------------------------------------------------


Statistical information for the repository '58c704a91ce685d5a3f461ac' was
gathered on 2021/01/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jackson Borchardt                6           250             75           29.10
borchardt                        1           792              0           70.90

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jackson Borchardt           967          386.8          1.2               23.47
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2934 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02934/joss.02934/10.21105.joss.02934.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02934/joss.02934/10.21105.joss.02934.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon query scope

@Borchardt – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Borchardt** [comment]
Thanks! Please let me know if there's anything I can provide to help!

**Comment by majensen** [comment]
I would be pleased to review this work (pending scope check)

**Comment by Borchardt** [comment]
Thanks, majensen!

With regard to the scope check, we wanted to add a couple of notes that might provide helpful context:

Of the 3066 lines of of code reported by whedon, the 955 JSON lines (Node package information), 115 markdown lines (readme content), and 79 SVG lines (our logo) might not be considered "real" code. This still leaves 1,917 lines of core application code -- JavaScript, CSS, Dockerfile, etc.

We also wanted to note that the repo we have shared here represents a public port of work originally completed in a longer-lived private repo. That work encompassed more than a few months, and it included significant code contributions by @RaymondDunn, who is listed as an author on the paper (but whose presence is not visible in the public repo).

Thanks again; looking forward to hearing back!

**Comment by Kevin-Mattheus-Moerman** [comment]
@Borchardt this submission has passed scope review and I will now assign an editor to handle this submission

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
Hi @balhoff - could I persuade you to review [this database work](#2934) for JOSS? Appreciate your consideration!

**Comment by majensen** [comment]
Thanks @Junjun-Zhang for agreeing to review!

**Comment by majensen** [comment]
@whedon assign @junjun-zhang as reviewer

**Comment by whedon** [comment]
OK, @junjun-zhang is now a reviewer

**Comment by balhoff** [comment]
@majensen apologies, I'm not able to do it right now. Keep me in consideration for future submissions though.

**Comment by majensen** [comment]
Thanks @balhoff will do

**Comment by majensen** [comment]
@bensonml - since the other review seems indefinitely paused, would you be willing to take [this database work](#2934) on as a reviewer? Thanks for considering!

**Comment by bensonml** [comment]
@majensen sure!

**Comment by majensen** [comment]
@whedon add @bensonml as reviewer

**Comment by whedon** [comment]
OK, @bensonml is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2979.
