### ISSUE TITLE
[PRE REVIEW]: Thing Directory: Simple and lightweight registry of IoT device metadata

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2935]
**Submitting author:** @farshidtz (<a href="http://orcid.org/0000-0002-5415-9899">Farshid Tavakolizadeh</a>)
**Repository:** <a href="https://github.com/linksmart/thing-directory" target ="_blank">https://github.com/linksmart/thing-directory</a>
**Version:** v1.0.0-beta.20
**Editor:** @gkthiruvathukal
**Reviewers:** @yadudoc, @sarathsp06
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @farshidtz. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @gkthiruvathukal.

@farshidtz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=10.88 s (80.3 files/s, 24611.2 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Go                              762          26210          23733         206358
Markdown                         30           1053              0           3335
Assembly                         43            449            812           2203
JSON                              3              0              0           1122
YAML                             25             87             23            952
Bourne Shell                      2             70            325            548
HTML                              2             29              0            120
TeX                               1              0              0             84
Bourne Again Shell                2             12              6             72
make                              1             11              0             33
C                                 1              8              7             24
Dockerfile                        1             10              2             22
--------------------------------------------------------------------------------
SUM:                            873          27939          24908         214873
--------------------------------------------------------------------------------


Statistical information for the repository '40d55f56475fe2279ca05b1c' was
gathered on 2021/01/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Farshid Tavakolizade             3           116             77          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Farshid Tavakolizade         39           33.6          0.0               17.95
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/CCNC.2019.8651786 is OK

MISSING DOIs

- 10.1145/2991561.2991570 may be a valid DOI for title: A Categorization of Discovery Technologies for the Internet of Things

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02935/joss.02935/10.21105.joss.02935.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02935/joss.02935/10.21105.joss.02935.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@gkthiruvathukal - would you be willing to edit this submission for JOSS? Also, if you believe this needs a scope check by the JOSS editorial team then we can do that first.

Note, there's a lot of code in `vendor`, removing that and re-running `cloc` gives the following:

```
cloc thing-directory/
      33 text files.
      33 unique files.                              
       8 files ignored.

github.com/AlDanial/cloc v 1.86  T=0.04 s (607.8 files/s, 134638.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                              17            585            355           2738
JSON                             2              0              0           1086
YAML                             3             46             17            712
TeX                              1              0              0             84
Markdown                         2             25              0             77
Dockerfile                       1             10              2             22
-------------------------------------------------------------------------------
SUM:                            26            666            374           4719
-------------------------------------------------------------------------------
```

**Comment by farshidtz** [comment]
@arfon - Thanks for the stats. The historical commit information, by author also seems wrong when compared with [contributors on Github](https://github.com/linksmart/thing-directory/graphs/contributors) (the second author is @dschowta).

I have added the missing DOI 10.1145/2991561.2991570 for title: A Categorization of Discovery Technologies for the Internet of Things. 
@whedon generate pdf

**Comment by gkthiruvathukal** [comment]
@arfon I think this is within scope and my areas of expertise, so please assign me as editor.

**Comment by danielskatz** [comment]
HI @gkthiruvathukal  - It's likely just as easy to write `@whedon assign me as editor` :)

**Comment by gkthiruvathukal** [comment]
Thanks, @danielskatz. I'll do it!

**Comment by gkthiruvathukal** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
I will get review started soon. Happy new year!

**Comment by gkthiruvathukal** [comment]
@farshidtz  Thank you for your patience as I work to get review started. Can you please take a look at the list of people under author instructions and suggest (without using the @ symbol) 3-4 reviewers?

**Comment by farshidtz** [comment]
> @farshidtz Thank you for your patience as I work to get review started. Can you please take a look at the list of people under author instructions and suggest (without using the @ symbol) 3-4 reviewers?

No worries. Thanks for starting the review.
Based on the domains and expertise, we suggest the following: natpt, manojrege, FreddieV4, bzz

**Comment by gkthiruvathukal** [comment]
@FreddieV4 and @natpt, would you be willing to contribute a review for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@manojrege, would you be willing to contribute a review for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@bzz, would you be willing to contribute a review for this JOSS submission.

@farshidtz Hmm, we're having trouble lining up reviewers. I hope you can suggest a few more possibilities.

**Comment by farshidtz** [comment]
@gkthiruvathukal Sad to see that no one is willing to review. We recommend: sarathsp06, yadudoc, suyashkumar

**Comment by gkthiruvathukal** [comment]
@farshidtz Don't worry, we will get the review processing going. Let me try from your suggestions!

**Comment by gkthiruvathukal** [comment]
sarathsp06, would you be willing to contribute a review for this JOSS submission? I need two reviewers to proceed.

**Comment by gkthiruvathukal** [comment]
@yadudoc, would you be willing to contribute a review for this JOSS submission? I need two reviewers to proceed.

**Comment by sarathsp06** [comment]
I shall review this , earliest by EoD today

**Comment by yadudoc** [comment]
@gkthiruvathukal, I can review this, but the earliest I can look at this would be this weekend. Does that work?

**Comment by gkthiruvathukal** [comment]
@yadudoc In the COVID-19 era, I don't rush our reviewers. I'll work with your schedule. Please do try to keep me informed if you think it will take more than a couple of weeks! (I usually gently nudge people after that amount of time.)

@sarathsp06 Thank you for your response! I'll work with your schedule, per my comment to @yadudoc here.

**Comment by gkthiruvathukal** [comment]
@whedon assign @yadudoc as reviewer

**Comment by whedon** [comment]
OK, @yadudoc is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon add @sarathsp06 as reviewer

**Comment by whedon** [comment]
OK, @sarathsp06 is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3075.
