### ISSUE TITLE
[PRE REVIEW]: MOLE: Mimetic Operators Library Enhanced

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2936]
**Submitting author:** @jcorbino (<a href="http://orcid.org/0000-0002-2638-9216">Johnny Corbino</a>)
**Repository:** <a href="https://github.com/jcorbino/mole" target ="_blank">https://github.com/jcorbino/mole</a>
**Version:** v3.0.0
**Editor:** @jedbrown
**Reviewers:** @ketch, @jshipton
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jcorbino. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jedbrown.

@jcorbino if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.78 s (316.3 files/s, 20874.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           109            385            518           7371
MATLAB                          81            581            633           2173
CSS                              4            320             80           1558
JavaScript                      31             83            112            974
C++                              6             84             79            577
PHP                              1             14             26            289
Markdown                         4             58              0            136
C/C++ Header                     7             37             17            104
TeX                              1              2              0             30
make                             2             22             15             30
ProGuard                         1              8              5             25
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                           248           1595           1489          13285
-------------------------------------------------------------------------------


Statistical information for the repository '09d44b2b933c5f1d4a46eeff' was
gathered on 2021/01/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Johnny                           1            57              0            1.42
Johnny Corbino Delga            32          2996            974           98.58

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Johnny Corbino Delga       2079           69.4         22.7                9.96
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.cam.2019.06.042 is OK
- 10.1137/S0895479801398025 is OK
- 10.21105/joss.00026 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02936/joss.02936/10.21105.joss.02936.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02936/joss.02936/10.21105.joss.02936.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @jedbrown as editor

:wave: @jedbrown - the submitting editor suggested you as the handling editor. Would you be willing to take on this submission?

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by jedbrown** [comment]
@whedon set @jedbrown as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jedbrown** [comment]
Hi, @jcorbino. :wave:  At first glance, I'm curious if the documentation is rendered somewhere and how one goes about testing the software. The documentation looks to be a mix of PDF files of unknown origin and some generated Doxygen docs that have been committed to the repository. It's quite easy these days to use an action to build a GitHub Pages site containing rendered documentation. And there should be source files for all content so it can be edited -- I see the Users Manual only describes the MATLAB interface and has outdated citations.

Are there external research users of the software? If so, what do they look like?

The C++ code size is small enough that we tend to ask questions: https://joss.readthedocs.io/en/latest/submitting.html?highlight=maintainable#substantial-scholarly-effort
I see the MATLAB is about 2000 lines, but it's unclear to me how the capabilities compare. Much of the question here is whether the software is something that the research community builds upon, or whether it's more of a reproducibility pack for your 2020 paper that readers of the paper might copy and modify for their use.

> JOSS requires that software should be feature-complete (i.e. no half-baked solutions) and designed for maintainable extension (not one-off modifications of existing tools).

Could you please update the repository to address these issues or ask questions here in this issue?

**Comment by jcorbino** [comment]
Hi @jedbrown, thank you for your feedback. This is basically what we have (documentation-wise):

**#1** _mole/doc_C++_  is our Doxygen generated documentation for the C++ version of the library
**#2** _mole/doc_MATLAB_ is the API documentation for MOLE's MATLAB version (generated through m2html)
**#3** _mole/MOLE User's Manual (MATLAB version).pdf_ is a short document that explains the resolution of a common problem using MOLE (yes, as you mentioned, only the MATLAB version)
**#4** There are a couple of extra PDFs that just talk about why we use staggered grids etc.
**#5** There are two examples folders (one for each flavor)

It is important to mention that the MATLAB version of our library is ahead of the C++ version, that is, there are certain functions (e.g. curvilinear operators) that so far have only been implemented for MATLAB.

So far I'm the sole contributor of the library (I mention this just to clarify on one of the rules of JOSS regarding the minimum of 3 months work for individual repos).

The library is backed by a peer-reviewed paper published (as you clearly mentioned), in addition, a couple of articles have been published from students in our lab that have used MOLE for their research [(](https://www.sciencedirect.com/science/article/pii/S0045793020303169?via%3Dihub)  and [)](https://ojs.lib.uwo.ca/index.php/mase/article/view/10874) there are other articles but I don't see the point in mentioning them.

Regarding the "_feature-complete, half-baked solutions_" I'm a bit puzzled, as a developer, I do not see how the current state of the library does not fulfill such requirement. The library allows to solve steady-state and time-dependent problems using mimetic methods in 1, 2 and 3 spatial dimensions. The reproducibility of our paper is just a subset of the set of applications.

Yes, there are internal and external users of the library, most of them graduate students. Most of them are Computer Scientists, Mathematicians, and Physicists.

Regarding the GitHub Page, so far I just have [](https://jcorbino.github.io/mole/) as the "page". I know it would be ideal to embed all or part of the documentation into that page but right now that is not a priority.

**Comment by jcorbino** [comment]
@jedbrown "User's manual" has been updated. Thanks for pointing that out!

Regarding having a more detailed GitHub page (so the different elements of documentation can be accessed from an index.md), currently I'm getting myself familiar with the creation process (I think it is a good addition), but as I mentioned in my previous comment, this has low priority.

**Comment by rouson** [comment]
@jedbrown  I just gave @jcorbino several tips to help get the MOLE repository in shape to meet the JOSS review criteria.  I also suggested that the JOSS paper.md write-up be revised so that it cites the research literature in which the submitted code has been used.  Hopefully this will demonstrate the substantial scholarly contributions of the code.

**Comment by jedbrown** [comment]
Many thanks, @rouson! I hope you're well, and I look forward to moving forward to review once it's ready.

**Comment by jcorbino** [comment]
Thanks @rouson for your feedback. @jedbrown , I've updated the following:

- *doc_MATLAB* (generated documentation about the MATLAB implementation of MOLE)
- *README.md* (added some extra details to make installation process clear)
- Updated references

**Comment by jcorbino** [comment]
@whedon withdraw

**Comment by whedon** [comment]
I'm sorry @jcorbino, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by jedbrown** [comment]
Hi, sorry I've been unresponsive (sick kids, no childcare, too many meeting collisions *waves hands furiously*). Please let us know how you'd like to proceed (retract, possible resubmit, start looking for reviewers).

**Comment by jcorbino** [comment]
Hi @jedbrown , I totally understand, I'm in a similar situation, kids + COVID restrictions make the system nonlinear. **I would like to proceed with the manuscript in this journal**, but I don't know exactly how to do it.  For reviewing I think that david.ketcheson@kaust.edu.sa (David Ketcheson) and damian@sourceryinstitute.org (Damian Rouson) are appropriate (based on their area of expertise).  @arfon , is there any way to tell the system to reverse the withdrawal action?  Thanks!

**Comment by rouson** [comment]
@jedbrown count me in if you'd like to add me as a reviewer.

**Comment by arfon** [comment]
> Hi @jedbrown , I totally understand, I'm in a similar situation, kids + COVID restrictions make the system nonlinear. I would like to proceed with the manuscript in this journal, but I don't know exactly how to do it. For reviewing I think that david.ketcheson@kaust.edu.sa (David Ketcheson) and damian@sourceryinstitute.org (Damian Rouson) are appropriate (based on their area of expertise). @arfon , is there any way to tell the system to reverse the withdrawal action? Thanks!

:+1: we're OK here. Whedon hasn't taken any action so we can proceed as-is.

**Comment by jcorbino** [comment]
- Updated the Doxyfile
- Removed generated files (doc_C++ folder)
- Left in place 'doc_MATLAB' folder since this is generated through a non-standard tool
- Expanded a little bit the README file
- Installation looks straight forward
- All files pertinent to JOSS are located in JOSS/
- Created a .github/workflow so paper.pdf gets generated as an artifact on every push

Currently working on catching up the C++ implementation...

**Comment by jcorbino** [comment]
Hi @jedbrown, @arfon ,

Any update on this?  I think the reviewers have not been assigned...

Kind regards,

**Comment by jcorbino** [comment]
@whedon assign @Kevin-Mattheus-Moerman  as editor

**Comment by whedon** [comment]
I'm sorry @jcorbino, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by jedbrown** [comment]
Sorry about the big lag on my end. I should be able to be responsive going forward.

@ketch Would you be available to review this submission?

@rouson I'd love if you'd be up for reviewing as well; you've already done a bit of work here. I've sent other invites, so please don't feel obligated.

**Comment by ketch** [comment]
I'm interested in this and would normally be happy to review it.  However, right now I have some other commitments that will keep me from doing so until probably the first or second week of August.  If that timeline is okay, then you can assign me.

**Comment by jedbrown** [comment]
Thanks @ketch. I'm fine with your August timeline. Please let us know if anything comes up that would cause further delays.

**Comment by jedbrown** [comment]
@whedon add @ketch as reviewer

**Comment by whedon** [comment]
OK, @ketch is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @jshipton as reviewer

**Comment by whedon** [comment]
OK, @jshipton is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by jedbrown** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@jedbrown Whedon is failing here as it looks like the author may have withdrawn the submission on the JOSS site.

@jcorbino - can you confirm you're still interested in pursuing this publication in JOSS?

**Comment by danielskatz** [comment]
I see from the author
>@whedon withdraw

and then 

> Hi @jedbrown , I totally understand, I'm in a similar situation, kids + COVID restrictions make the system nonlinear. **I would like to proceed with the manuscript in this journal**, but I don't know exactly how to do it. For reviewing I think that [david.ketcheson@kaust.edu.sa](mailto:david.ketcheson@kaust.edu.sa) (David Ketcheson) and [damian@sourceryinstitute.org](mailto:damian@sourceryinstitute.org) (Damian Rouson) are appropriate (based on their area of expertise). @arfon , is there any way to tell the system to reverse the withdrawal action? Thanks!

**Comment by danielskatz** [comment]
So it seems like this should go forward, but that perhaps there is (was) an issue with how whedon handled the author's request to withdraw, which it should have ignored, or maybe something else went wrong along the way

**Comment by jcorbino** [comment]
Hi @arfon ,

Yes, I'm still interested in pursing this publication in JOSS. And as @danielskatz pointed out, at some point in time I tried to withdraw the article but it kind of ended up in limbo. If there's anything I can do to fix this, please let me know.

**Comment by jedbrown** [comment]
Thanks. Whedon reported that the request was invalid (needs editor or AEiC) so I'd hope its internal state was not impacted. @arfon Is there a prod that can be done so Whedon can proceed or do we need to start over in some form?

**Comment by danielskatz** [comment]
I'm fairly sure this can't be fixed via a whedon command, and my guess is that @openjournals/dev can fix it rather than us having to start it over

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3380.

**Comment by arfon** [comment]
> OK, I've started the review over in #3380.

OK, looks like we're moving again :-)
