### ISSUE TITLE
[PRE REVIEW]: RivGraph: Automatic extraction and analysis of river and delta channel network topology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2937]
**Submitting author:** @jonschwenk (<a href="http://orcid.org/0000-0001-5803-9686">Jon Schwenk</a>)
**Repository:** <a href="https://github.com/jonschwenk/RivGraph" target ="_blank">https://github.com/jonschwenk/RivGraph</a>
**Version:** v0.3
**Editor:** @kbarnhart
**Reviewers:** @eriknes, @leotrs
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jonschwenk. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kbarnhart.

@jonschwenk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.72 s (45.9 files/s, 25848.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            32           6553             96          19623
JavaScript                      14           2144           2130           8154
Python                          36           3199           5851           7695
JSON                             9              0              0           7069
SVG                              1              0              0           2671
reStructuredText                16            660            548            636
CSS                              4            161             32            634
YAML                             4             14             11            196
TeX                              1             11              0            148
Markdown                         2             53              0            125
Jupyter Notebook                 3              0           1772            119
XML                              2              0              0             21
make                             1             10              5             17
-------------------------------------------------------------------------------
SUM:                           125          12805          10445          47108
-------------------------------------------------------------------------------


Statistical information for the repository '2a217ec18a5662e7c2a24612' was
gathered on 2021/01/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
JayH                            17          1391            124            2.72
Jon Schwenk                    104         25960          10788           65.98
jay                             39          5446            961           11.50
jonschwenk                      12         10804            225           19.80

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
JayH                       3763          270.5          5.3               21.02
Jon Schwenk               25417           97.9          1.7               15.41
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/2014WR016604 is OK
- 10.1002/2014WR016577 is OK
- 10.1073/pnas.1708404114 is OK
- 10.5194/esurf-8-87-2020 is OK
- 10.1029/2020WR027199 is OK
- 10.1029/2019GL086710 is OK
- 10.1029/2019WR026867 is OK
- 10.1002/esp.3482 is OK
- 10.3390/ijgi9110658 is OK
- 10.1029/2019JF005206 is OK

MISSING DOIs

- 10.1002/essoar.10502024.1 may be a valid DOI for title: The Braiding Index 2.0: eBI

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02937/joss.02937/10.21105.joss.02937.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02937/joss.02937/10.21105.joss.02937.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @kthyng @leouieda - would one of you be willing to handle this submission for JOSS? @kbarnhart is the suggested editor but is already handing four submissions right now 😬.

**Comment by kbarnhart** [comment]
@arfon its not an issue for me to take this as a 5th paper right now (one of the five is currently under revisions, and I'm going start handling the other three today as I'm now back from vacation). Not an issue to also handle this.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
@jonschwenk thanks for this submission. At this point I've looked through the repository and have determined that I can move forward to looking for reviewers.  If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this [list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

In addition there are a few minor items I would recommend attending to before the formal review issue begins:
- [ ] add the identified missing DOI 
- [ ] address the date format of Tejedor et al., 2019 (line 46)
- [ ] add references for dependency software where citations exists.

**Comment by kbarnhart** [comment]
@jonschwenk thanks for pointing me to the test instructions. That is sufficient. I had managed to miss that. 🤦 

Regarding citations. One of the review criteria in the checklist that reviewers will use states 

> **References**: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?

Thus I recommend adding citations to the paper to reference software used to construct RivGraph. 

Let me know if that doesn't address your question. 

Also, please let me know if you have recommendations for reviewers. I have some thoughts on suitable reviewers for this, but it is always helpful to get input from authors.

**Comment by jonschwenk** [comment]
Ok, I didn't see a way to organically work the dependency refs into the paper so I just added a new section for that.

Here are some possible reviewers:
Erik Nesvold - https://github.com/eriknes
Charlie Marshak (author of "competing" package Orinoco) - https://scienceandtechnology.jpl.nasa.gov/charlie-marshak
Allison Pfeiffer or Jon Czuba

From JOSS list (Python preferred, 'network' or 'geomorphology' in interests):
RafalKucharskiPK/
jkbren
leotrs
nicgaspar
marda-science and dbuscombe-usgs

Hope that helps!

**Comment by kbarnhart** [comment]
:wave: @cmarshak @eriknes @pfeiffea @dbuscombe-usgs @leotrs would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission is "RivGraph: Automatic extraction and analysis of river and delta channel network topology" and I'm reaching out to you based on your experience in network analysis, river/delta geomorphology, and/or python. 

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by eriknes** [comment]
Sure, I can do that.

Thanks, Erik

**Comment by dbuscombe-usgs** [comment]
Sorry, can't do it this time - v. busy month. But keep me in mind for similar papers in the future

**Comment by leotrs** [comment]
Yes I can do it.

**Comment by pfeiffea** [comment]
This month is a hectic one for me. @kbarnhart if you can't find a third reviewer in the coming week or so, ping me again and I'll see if I can clear the space for it!

**Comment by kbarnhart** [comment]
@leotrs and @eriknes thanks for your willingness to review. I'll now add you as reviewers and start the review.

@cmarshak if you are interested in reviewing I can add you after I start the review. 

@dbuscombe-usgs and @pfeiffea thanks for the prompt replies.

**Comment by kbarnhart** [comment]
@whedon add @eriknes as reviewer

**Comment by whedon** [comment]
OK, @eriknes is now a reviewer

**Comment by kbarnhart** [comment]
@whedon add @leotrs as reviewer

**Comment by whedon** [comment]
OK, @leotrs is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2952.
