### ISSUE TITLE
[PRE REVIEW]: libCEED: Fast algebra for high-order element-based discretizations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2938]
**Submitting author:** @jedbrown (<a href="http://orcid.org/0000-0002-9945-0639">Jed Brown</a>)
**Repository:** <a href="https://github.com/CEED/libCEED" target ="_blank">https://github.com/CEED/libCEED</a>
**Version:** v0.8.0
**Editor:** @diehlpk
**Reviewers:** @thelfer, @FreddieWitherden, @pbauman
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jedbrown. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @meg-simula.

@jedbrown if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=4.30 s (152.7 files/s, 27558.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                              201           5050           8602          28864
C/C++ Header                   135           2334           5426          11013
C++                             51           1333           1642           9432
SVG                              8              0              0           7616
Fortran 90                      66           1050            717           5488
Python                          30           1546           1880           4453
Julia                           26            673            167           3883
CUDA                            19            191            404           2528
reStructuredText                38            959            916           1894
Rust                             7            182           2567           1349
Markdown                        26            325              0           1100
make                            11            197            260            777
Bourne Shell                     7            143            167            742
Jupyter Notebook                 7              0           1427            435
YAML                            15             54             20            391
TeX                              2             11              0            130
TOML                             5              9              2             58
Pascal                           1             12              0             44
Groovy                           1              2              0             38
INI                              1              3              0             35
-------------------------------------------------------------------------------
SUM:                           657          14074          24197          80270
-------------------------------------------------------------------------------


Statistical information for the repository '1ea2032f6a1ebe30ede373f9' was
gathered on 2021/01/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ahmad Abdelfattah                1           593             68            0.34
David Medina                     6          7570           2703            5.31
James Wright                    14           262            141            0.21
Jean-Sylvain Camier             85          6849           4781            6.01
Jed Brown                      228         10834           6704            9.06
Jeremy L. Thompson             588         68679          28080           50.01
Kenneth E. Jansen                1           195             41            0.12
Leila Ghaffari                  57          3969           2479            3.33
Natalie Beams                   40         14036           4207            9.43
Oana Marin                       3          1703             78            0.92
Sander Arens                     1            35             45            0.04
Stan Tomov                      18          1832           1438            1.69
Steven Roberts                   4            51             27            0.04
Thilina Rathnayake              43          1243            587            0.95
Tzanio Kolev                    15           720            536            0.65
Valeria Barra                  118          8025           2769            5.58
Veselin Dobrev                  24          1662            170            0.95
Will Pazner                      7            60             27            0.04
Yohann Dudouit                  34          8424           1855            5.31

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ahmad Abdelfattah          4389          740.1          7.5               15.65
David Medina               7509           99.2          4.3               13.30
James Wright                118           45.0         12.4                5.08
Jean-Sylvain Camier         149            2.2         34.0               33.56
Jed Brown                  4533           41.8         17.0               12.51
Jeremy L. Thompson        42709           62.2         12.7               28.87
Kenneth E. Jansen           146           74.9         14.3               28.08
Leila Ghaffari             1412           35.6          8.9               23.58
Natalie Beams              8692           61.9          4.0               18.47
Sander Arens                 29           82.9         13.4                0.00
Stan Tomov                  351           19.2         17.3               28.77
Steven Roberts               14           27.5         29.3                0.00
Thilina Rathnayake          476           38.3         35.0               50.00
Tzanio Kolev                487           67.6         34.1               53.39
Valeria Barra              5882           73.3         11.3               25.54
Veselin Dobrev              520           31.3         35.6                8.27
Will Pazner                  60          100.0          3.5               10.00
Yohann Dudouit             4197           49.8         18.7               12.65
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2938 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by arfon** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10915-010-9396-8 is OK
- 10.5281/zenodo.2641316 is OK
- 10.5281/zenodo.3860804 is OK
- 10.1177/1094342020915762 is OK
- 10.1137/141000671 is OK
- 10.5281/zenodo.4302737 is OK
- 10.25080/Majora-342d178e-00c is OK
- 10.11578/dc.20171025.1248 is OK
- 10.1016/j.camwa.2020.06.009 is OK
- 10.1145/2833157.2833162 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1002/fld.1650170103 is OK
- 10.1007/s00366-006-0049-3 is OK
- 10.1515/jnma-2020-0043 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/0021-9991(80)90005-4 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02938/joss.02938/10.21105.joss.02938.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02938/joss.02938/10.21105.joss.02938.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @meg-simula @diehlpk happy new year! Would one of you be willing to handle this submission from our very own @jedbrown 😄?

@jedbrown - note the minor issue with one of your DOIs here.

**Comment by meg-simula** [comment]
Happy New Year! I feel a bit biased here ... - but can step in if @diehlpk is not available.

**Comment by diehlpk** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by diehlpk** [comment]
@arfon and @meg-simula Happy New Year! Sure, I can handle this one here.

**Comment by diehlpk** [comment]
@jedbrown Could you please recommend some potential reviewers? 

`As a reviewer, COIs are your present or previous association with any authors of a submission: recent (past four years) collaborators in funded research or work that is published; and lifetime for the family members, business partners, and thesis student/advisor or mentor. In addition, your recent (past year) association with the same organization of a submitter is a COI, for example, being employed at the same institution.`

**Comment by jedbrown** [comment]
:wave: Happy new year! I've fixed the DOI issue. For reviewers, I would consider

* Direct domain expertise
  * https://github.com/pbauman - libMesh and multiphysics solvers, now at AMD
  * https://github.com/FreddieWitherden - PyFR (similar to high-order DG), Python-based optimization and GPU offloading
  * https://github.com/lukeolson - algebraic multigrid, finite elements, and GPUs, Python
* Volunteered to review and have relevant expertise, but have not yet reviewed for JOSS (or not recently)
  * https://github.com/munkm - meshing, visualization, nuclear engineering apps, Python and Rust
  * https://github.com/fhorrobin - astrophysics, CFD, relevant languages
  * https://github.com/thelfer - solid mechanics

**Comment by diehlpk** [comment]
Hey, @pbauman, @FreddieWitherden, @lukeolson, @munkm, @fhorrobin, and @thelfer would you willing to review this paper?

**Comment by thelfer** [comment]
@diehlpk I am interested. What is the deadline ?

**Comment by diehlpk** [comment]
> @diehlpk I am interested. What is the deadline ?

@thelfer within the next two month would be great.

**Comment by thelfer** [comment]
@diehlpk Perfect. So I take the review. We are currently making tests with MFEM and libCEED in my lab.  I already sent the paper to interested colleagues who will also make feedbacks on the paper (I'll centralize everything to simplify the review).

**Comment by diehlpk** [comment]
@whedon assign @thelfer as reviewer

**Comment by whedon** [comment]
OK, @thelfer is now a reviewer

**Comment by FreddieWitherden** [comment]
> Hey, @pbauman, @FreddieWitherden, @lukeolson, @munkm, @fhorrobin, and @thelfer would you are willing to review this paper?

I am happy to review, too, if you're short.

**Comment by pbauman** [comment]
> I am happy to review, too, if you're short.

Same.

**Comment by diehlpk** [comment]
@whedon add @FreddieWitherden as reviewer

**Comment by whedon** [comment]
OK, @FreddieWitherden is now a reviewer

**Comment by diehlpk** [comment]
@whedon add @pbauman as reviewer

**Comment by whedon** [comment]
OK, @pbauman is now a reviewer

**Comment by diehlpk** [comment]
Thanks, @FreddieWitherden and @pbauman for doing the review.

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2945.

**Comment by lukeolson** [comment]
@diehlpk Do you need any more?  Happy to do one if you still need additional reviewers.

**Comment by diehlpk** [comment]
@lukeolson Thanks, however, I already have three reviewers and I am good for this paper.

**Comment by danielskatz** [comment]
@lukeolson - did you try to volunteer since the name was so close to "[CEESD](http://ceesd.illinois.edu)"?
