### ISSUE TITLE
[REVIEW]: Text-Fabric: Text representation for text with stand-off annotations and linguistic features

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#294]
**Submitting author:** @dirkroorda (<a href="http://orcid.org/0000-0002-2680-8724">Dirk Roorda</a>)
**Repository:** <a href="https://github.com/ETCBC/text-fabric" target ="_blank">https://github.com/ETCBC/text-fabric</a>
**Version:** v2.3.6
**Editor:** @acabunoc
**Reviewer:** @47rooks
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/24d593e78c794f4c2c4641bbb69e0136/status.svg)](http://joss.theoj.org/papers/24d593e78c794f4c2c4641bbb69e0136)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/24d593e78c794f4c2c4641bbb69e0136"><img src="http://joss.theoj.org/papers/24d593e78c794f4c2c4641bbb69e0136/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/24d593e78c794f4c2c4641bbb69e0136/status.svg)](http://joss.theoj.org/papers/24d593e78c794f4c2c4641bbb69e0136)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ETCBC/text-fabric" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ETCBC/text-fabric">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v2.3.6)?
- [x] **Authorship:** Has the submitting author (@dirkroorda) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @47rooks it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@47rooks - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let @acabunoc or myself know.

**Comment by 47rooks** [comment]
@arfon The license is Unlicense (http://unlicense.org) which is not listed on the OSI page you list but I would expect it to qualify at least from an intent standpoint. Is this ok ? Also the Github version has shifted from 2.3.6 to 2.3.7 in the time between submission and now I guess.

Regarding installation I would only mention that Python 3.6 is required at a minimum rather than just 3.
I don't see any community guidelines as such. Obviously, pinging the author via github or raising issues would work. There are no contributor guidelines per se.

Other than those minor nits it is in compliance with your guidelines.

**Comment by arfon** [comment]
> @arfon The license is Unlicense (http://unlicense.org) which is not listed on the OSI page you list but I would expect it to qualify at least from an intent standpoint. Is this ok ? Also the Github version has shifted from 2.3.6 to 2.3.7 in the time between submission and now I guess.

Actually this isn't acceptable to JOSS (see a similar recent thread [here](https://github.com/openjournals/joss/issues/248)). Probably the easiest option would be to dual-license the repository with an [OSI approved](https://opensource.org/licenses/alphabetical) license. @dirkroorda - would this be possible?

**Comment by dirkroorda** [comment]
I like to stick to the Unlicense. I find it the best expression of my intent. This piece of software is like the pond in front of my house: not part of the world of copyright. It is also simple. A dual-license is an unnecessary complication. I've seen discussions why the Unlicense is not good enough, but I have not been persuaded.
If this means that this repo cannot be reviewed for the JOSS, so be it.
Sorry for wasting your time in that case.

**Comment by arfon** [comment]
> If this means that this repo cannot be reviewed for the JOSS, so be it.

I'm afraid it does. No hard feelings 😄.

@47rooks - I'm going to withdraw the paper on @dirkroorda's behalf on the JOSS site. Many thanks for your review.
