### ISSUE TITLE
[PRE REVIEW]: RI5C: A Visual Blockchain Navigator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2941]
**Submitting author:** @ebarojas (<a href="http://orcid.org/0000-0003-4182-1537">Everardo J Barojas-Méndez</a>)
**Repository:** <a href="https://github.com/ebarojas/RI5C/" target ="_blank">https://github.com/ebarojas/RI5C/</a>
**Version:** v0.9
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ebarojas. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @galessiorob.

@ebarojas if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.87 s (23.1 files/s, 945.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           8             82            110            259
Markdown                         2             58              0            112
HTML                             1              5              4             93
Bourne Shell                     2              7             11             42
TeX                              1              3              0             26
JavaScript                       6              0              1              6
-------------------------------------------------------------------------------
SUM:                            20            155            126            538
-------------------------------------------------------------------------------


Statistical information for the repository 'ef99129b3d5c548bbaabf350' was
gathered on 2021/01/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Everardo J Barojas M            52           720            261          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Everardo J Barojas M        459           63.8          2.9               18.08
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.2139/ssrn.3440802 may be a valid DOI for title: Bitcoin: A Peer-to-Peer Electronic Cash System

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02941/joss.02941/10.21105.joss.02941.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02941/joss.02941/10.21105.joss.02941.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @ebarojas  - thanks for your submission to JOSS. I'm the EiC on rotation for JOSS this week and am trying to understand the [scale/scope of this submission](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). Can you confirm that the Python code in [this directory](https://github.com/ebarojas/RI5C/tree/master/ri5c) forms the bulk of the source code for this project (aside from the plotting libraries etc.)?

**Comment by ebarojas** [comment]
Hi @arfon - I can confirm that the Python code in that directory forms the bulk of the source code. There is some server and dev-ops data in the root dir, but the relevant contributions are in the ```/ri5c``` sub-directory.

**Comment by ebarojas** [comment]
As far as potential reviewers go, my suggestions would be:
- ohmaddi
- jkbren
- dinacmistry [mismatch on area, but interesting]
- jankatins
- ati-ozgur
- jkbren
- skradha26

**Comment by ebarojas** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by arfon** [comment]
> Hi @arfon - I can confirm that the Python code in that directory forms the bulk of the source code. There is some server and dev-ops data in the root dir, like you say the relevant contributions are in the /ri5c sub-directory.

OK, thanks for confirming. I'm afraid this means that this submission is out of scope for JOSS due to our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion. You can read more about the motivations for this decision in our [blog post](https://blog.joss.theoj.org/2020/07/minimum-publishable-unit).

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by ebarojas** [comment]
@arfon thanks for the quick response:  in this case, was this decision made on the number of lines of code?

According to the criteria you cited, it would be flagged if less than 1,000 lines of code and desk-rejected if less than 300. By my count I'm roughly at 450. Please provide a bit more depth so I can resubmit once criteria are met.

**Comment by arfon** [comment]
Yes, the LOC was the primary decision point here. I used [this report](https://github.com/openjournals/joss-reviews/issues/2941#issuecomment-754448483) to make my decision, which reports ~250 lines of Python.

**Comment by ebarojas** [comment]
There is relevant code in [this](https://github.com/ebarojas/RI5C/blob/master/ri5c/show_graph.html) file, esp. after line 40, which that report counts as HTML but is js inside a <script> tag.

**Comment by ebarojas** [comment]
@arfon I understand the need for triage, but it is incorrect to gauge the LOC only with the Python files, RI5C is a full functioning scientific app and JS is just as important.

Should I re-submit in order to at least be reviewed by your editorial team?

**Comment by arfon** [comment]
Hi @ebarojas, even with the additional JavaScript included, this submission is still very small for JOSS and by my (and other EiC) assessment still falls well below our threshold for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by ebarojas** [comment]
@arfon Equivalent reports to [this](https://github.com/openjournals/joss-reviews/issues/2941#issuecomment-754448483) seem to not be present/deleted on accepted submissions - if LOC criteria gets you desk rejected like that, without even minor feedback or recommendation on where to improve, I would make that a wee bit more clear in your submission guidelines.
