### ISSUE TITLE
[PRE REVIEW]: Kinetic.jl: A lightweight finite volume toolbox in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2942]
**Submitting author:** @vavrines (<a href="http://orcid.org/0000-0001-9127-9497">Tianbai Xiao</a>)
**Repository:** <a href="https://github.com/vavrines/Kinetic.jl" target ="_blank">https://github.com/vavrines/Kinetic.jl</a>
**Version:** v0.7.0
**Editor:** @diehlpk
**Reviewers:** @KristofferC, @rdeits
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vavrines. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@vavrines if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (322.1 files/s, 40919.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TOML                             5            512              2           2405
Julia                           12            153            235            820
Markdown                        15             66              0            324
YAML                             4              5              7            116
TeX                              1              0              0             55
-------------------------------------------------------------------------------
SUM:                            37            736            244           3720
-------------------------------------------------------------------------------


Statistical information for the repository '7c6b994d8ff9880733838cee' was
gathered on 2021/01/06.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1137/141000671 may be a valid DOI for title: Julia: A fresh approach to numerical computing

INVALID DOIs

- https://doi.org/10.5281/zenodo.4025432 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02942/joss.02942/10.21105.joss.02942.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02942/joss.02942/10.21105.joss.02942.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope 

@vavrines thanks for your submission to JOSS – due to the relatively small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by vavrines** [comment]
> @whedon query scope
> 
> @vavrines thanks for your submission to JOSS – due to the relatively small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.
> 
> @whedon generate pdf
> @whedon check references

Thanks for the prompt support! 
Maybe I should mention it here. The package is a combination that reexports [KitBase](https://github.com/vavrines/KitBase.jl), [KitML](https://github.com/vavrines/KitML.jl) and [KitFort](https://github.com/vavrines/KitFort.jl), and the total size of codes should be fine : )

**Comment by vavrines** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02942/joss.02942/10.21105.joss.02942.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02942/joss.02942/10.21105.joss.02942.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
> Maybe I should mention it here. The package is a combination that reexports KitBase, KitML and KitFort, and the total size of codes should be fine : )

@vavrines - I'm not sure I follow sorry. Are you saying that this package is actually four different codebases combined, or that KitBase, KitML, and KitFort are _dependencies_ of this one?

If so, JOSS' scholarly effort criterion is applied to the package under review (Kinetic.jl) in this case, not the dependent projects. From my assessment (with the caveat that I'm not a Julia user), this submission looks to be ~800 lines of Julia code. Please correct me if I'm missing something here.

**Comment by vavrines** [comment]
> > Maybe I should mention it here. The package is a combination that reexports KitBase, KitML and KitFort, and the total size of codes should be fine : )
> 
> @vavrines - I'm not sure I follow sorry. Are you saying that this package is actually four different codebases combined, or that KitBase, KitML, and KitFort are _dependencies_ of this one?
> 
> If so, JOSS' scholarly effort criterion is applied to the package under review (Kinetic.jl) in this case, not the dependent projects. From my assessment (with the caveat that I'm not a Julia user), this submission looks to be ~800 lines of Julia code. Please correct me if I'm missing something here.

@arfon Thanks for the clarification.
Yes they're the codebases. The structs and methods have been imported into this main package so there's no need to review these sub repositories.
It's a common strategy in Julia to reduce precompilation time, e.g. [DIfferentialEquations.jl](https://github.com/SciML/DifferentialEquations.jl) and [Yao.jl](https://github.com/QuantumBFS/Yao.jl)

**Comment by dpsanders** [comment]
The sub repositories are an integral part of the Julia package and should definitely be reviewed.

**Comment by Kevin-Mattheus-Moerman** [comment]
@vavrines can you clarify what the entire codebase is that should be considered/reviewed here? The package Kinetic.jl appears too minor on its own. If the core functionality provided requires KitBase, KitML and KitFort (and perhaps kineticpy), all of which you wrote to accompany Kinetic (if I understand this correctly), then these should perhaps all be reviewed altogether and seen as a single submission, can you confirm?

**Comment by vavrines** [comment]
> @vavrines can you clarify what the entire codebase is that should be considered/reviewed here? The package Kinetic.jl appears too minor on its own. If the core functionality provided requires KitBase, KitML and KitFort (and perhaps kineticpy), all of which you wrote to accompany Kinetic (if I understand this correctly), then these should perhaps all be reviewed altogether and seen as a single submission, can you confirm?

Hi Keven, thanks for the reply.
Yes I can herby confirm the core functionality is provided together with KitBase, KitML and KitFort, and they serve as a single submission.

Best, Tianbai

**Comment by jedbrown** [comment]
If the capability has rough parity with Clawpack, then there's no question about it being within scope. I can't tell if that's the case -- the examples are surely much less developed and documented. From briefly browsing the docs, I don't see where to look for boundary conditions, the extent of its multi-dimensional capability, time integrators, etc. What is supported? How fast is it compared to mature implementations (e.g., Clawpack or OpenFOAM)? The paper's statement of need should explain the capabilities and why you might opt for this package versus others.

Finally, I think drawing attention to the text input format is counter-productive. One of the advantages of Julia is programmatically creating model configurations and differentiating output with respect to arbitrary inputs. The text format seems to steer away from such things.

**Comment by vavrines** [comment]
I huess the editors may be discussing this article. To avoid possible misunderstandings, I'll write a brief reply here and sorry for any interruptions.

I agree Clawpack is a much more matured software. The main difference are listed here:

- Clawpack is coded in Fortran and Python, while Kinetic.jl is using Julia and avoids two-language problem
- It pays considerable attention to the Boltzmann equation, which is missing in Clawpack or OpenFOAM
- It is closely coupled with scientific machine learning

I believe the text input makes sense. During the runtime, the texts are going to generate variables directly, which relies on the meta-programming property of Julia. Different types of text input (txt, toml, cfg, etc.) are supported, and it provides a convenient way to modify settings without changing source codes. It is worth mentioning that there is an equivalent way to do configuration in Julia scripts without text input. I omitted it in the paper to avoid redundancy.

The documentation isn't perfect at present and is being organized continuously.

**Comment by kthyng** [comment]
@vavrines Can I verify that this submission covers Kinetic.jl and KitBase, KitML and KitFort? Also, have these other packages been published on or are in the process of being published on?

We seem to be narrowing in on what exactly is in this submission and that the packages together are in scope. However, there is still concern about the maturity of the project at this point. The paper is incomplete with no statement of need and a reference to a figure that is not present (?) along with other errors. Also, given that as part of the JOSS review, two reviewers will go through the package(s) in detail as well as all of the documentation, these items should be as perfect as possible now as opposed to some point in the future. Tests and other [requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) should also be fully functional before the review starts.

Would you like to pause this submission to improve the documentation and paper before proceeding? This would mean you think you could improve it enough in, say, a few weeks, to be able to proceed with the review. Alternatively, you could withdraw and resubmit at a later time when you have had a chance to make these improvements.

**Comment by vavrines** [comment]
> @vavrines Can I verify that this submission covers Kinetic.jl and KitBase, KitML and KitFort? Also, have these other packages been published on or are in the process of being published on?
> 
> We seem to be narrowing in on what exactly is in this submission and that the packages together are in scope. However, there is still concern about the maturity of the project at this point. The paper is incomplete with no statement of need and a reference to a figure that is not present (?) along with other errors. Also, given that as part of the JOSS review, two reviewers will go through the package(s) in detail as well as all of the documentation, these items should be as perfect as possible now as opposed to some point in the future. Tests and other [requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) should also be fully functional before the review starts.
> 
> Would you like to pause this submission to improve the documentation and paper before proceeding? This would mean you think you could improve it enough in, say, a few weeks, to be able to proceed with the review. Alternatively, you could withdraw and resubmit at a later time when you have had a chance to make these improvements.

Dear @kthyng 
Thank you very much for the reply. I can confirm this submission covers Kinetic.jl, KitBase.jl, KitML.jl and KitFort.jl. All these packages have neber been published on or are in process of being published on any other journal.

And thanks for the comments on the paper. I don't agree with part of the arguments. The statement of need is obviously provided in the summary of paper. The figure is tightly connected to the text above, and I can add a caption of it if necessary (not sure about this point in JOSS). The tests and other requiements work well.

I think the current maturity of the documentation and of the whole package meets the readership of JOSS. However, if it comes to an official decision from editors that the paper submission has to be paused, I would respect it and apply myself to the improvement.

Best,
Tianbai

**Comment by kthyng** [comment]
> The statement of need is obviously provided in the summary of paper. 

We require a section entitled "Statement of Need." @jedbrown gave suggestions for additions above.

> The figure is tightly connected to the text above, and I can add a caption of it if necessary (not sure about this point in JOSS). 

The paper seems to imply the presence of a figure but I do not see one. Am I missing something? I see it now in the github representation of the paper but not in the whedon compiled version. Yes you can and should include a caption. The information you need to implement these items should be [here](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). 

> The tests and other requiements work well.

At a minimum, you can see @jedbrown's comments about the state of the documentation, but this came up in the editorial discussion outside of this issue as well. 

The low coverage of tests were brought up as well. Can you elaborate on what is tested for at present?

The items that I am bringing up now are from the editorial board discussion and are also the items that reviewers would need to bring up immediately upon starting their reviews so we try to catch things like this before the review process starts when possible to reduce the time reviewers need to spend. I will pause this paper for now as you work through the items.

**Comment by kthyng** [comment]
Ah, I forgot to include above that the paper needs proof reading too. There are a number of grammatical errors at present.

**Comment by vavrines** [comment]
@kthyng 
Thanks again for the kind explanation.

I figured out that JOSS seems not accepting html syntax so that all the figures in (https://github.com/vavrines/Kinetic.jl/blob/master/paper/paper.md) are missing. Is there a recommended way to adjust the attributes of a picture in JOSS?

I'll work on improving the paper. When it's ready, how should I contact the editor and restart the review process?

Best, Tianbai

**Comment by kthyng** [comment]
@vavrines can you use the example given in the docs that is like this: `![Caption for example figure.](figure.png){ width=20% }`

In addition to the paper, please work on the docs and tests.

When you are ready, you can ping @openjournals/joss-eics  to start your submission back up.

**Comment by vavrines** [comment]
With the revise of the paper, docs and tests, I would like to reboot the review process.

The major changes include:
- The paper is rewritten. A statement of need section is added. The figure format is adjusted. The proof reading is made.
- The tests are expanded and the coverage increases.
- The documentation is reorganized.

@openjournals/joss-eics 
@arfon 
@kthyng 
@Kevin-Mattheus-Moerman 
Could you please help continue the review?

**Comment by vavrines** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02942/joss.02942/10.21105.joss.02942.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02942/joss.02942/10.21105.joss.02942.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@jedbrown Would you be able to have a look at the changes in this repo? Would you be willing to edit the submission, too?

**Comment by kthyng** [comment]
@whedon invite @jedbrown as editor

**Comment by whedon** [comment]
@jedbrown has been invited to edit this submission.

**Comment by jedbrown** [comment]
Sorry, I'm swamped and will need to decline new editing for a few weeks. Perhaps @harpolea would be available.

**Comment by kthyng** [comment]
@diehlpk Would you be able to edit this?

**Comment by kthyng** [comment]
@whedon invite @diehlpk as editor

**Comment by whedon** [comment]
@diehlpk has been invited to edit this submission.

**Comment by diehlpk** [comment]
@kthyng I can manage the topic but have no experience with the Julia language and would need to reply on the reviewer's judgment.

**Comment by diehlpk** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by diehlpk** [comment]
Hey  @vavrines could you please recommend some potential reviewers?

**Comment by vavrines** [comment]
@diehlpk Thanks for the quick handling.
For the potential reviewers, I suggest:
- Christopher Rackauckas (ChrisRackauckas)
- Robin Deits (rdeits)
- David P. Sanders (dpsanders)
- Kristoffer Carlsson (KristofferC)

**Comment by diehlpk** [comment]
Hey @ChrisRackauckas, @rdeits, @dpsanders, and @KristofferC would you be interested to review this paper?

**Comment by rdeits** [comment]
Sure, I can help out. I've done lots of scientific paper reviews in grad school, but never anything as software-focused as this, so I'm not totally sure what's expected. Do you have any info about what you're expecting from a JOSS reviewer?

**Comment by diehlpk** [comment]
@rdeits Please have a look at our guidelines 

https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Please let me know if you like to have more details?

**Comment by rdeits** [comment]
Oh, yeah, that's exactly what I was looking for. Thanks! What is the review timeline?

**Comment by KristofferC** [comment]
@diehlpk Hello, yes I can help review this paper.

**Comment by diehlpk** [comment]
> Oh, yeah, that's exactly what I was looking for. Thanks! What is the review timeline?

@rdeits everything within the next two months would be great

**Comment by diehlpk** [comment]
@whedon assign @KristofferC as reviewer

**Comment by whedon** [comment]
OK, @KristofferC is now a reviewer

**Comment by diehlpk** [comment]
@rdeits Does the proposed time lime works for you?

**Comment by rdeits** [comment]
Yes, that works for me

**Comment by diehlpk** [comment]
@whedon add @rdeits as reviewer

**Comment by whedon** [comment]
OK, @rdeits is now a reviewer

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3060.

**Comment by diehlpk** [comment]
Hey @ChrisRackauckas and @dpsanders would you be interested to review this paper?

**Comment by diehlpk** [comment]
Hey @Adrianzo @ahwillia @vchuravy @dhhagan @jarvist would you be interested to review this paper?

**Comment by ahwillia** [comment]
I can't, too many deadlines over the next 6 weeks, then a planned vacation.

**Comment by vavrines** [comment]
@diehlpk 
Thanks very much for the continuous support.
If you want I could also recommend some potential reviewers who are working on similar topics on github.

**Comment by jarvist** [comment]
> Hey @Adrianzo @ahwillia @vchuravy @dhhagan @jarvist would you be interested to review this paper?

I'm on parental leave until May 17th, but can then review this. 
We have some partial reviews already? The history ^^^^ was a bit long to skim through!

**Comment by diehlpk** [comment]
> @diehlpk 
> Thanks very much for the continuous support.
> If you want I could also recommend some potential reviewers who are working on similar topics on github.

Yes, please go ahead.

**Comment by diehlpk** [comment]
> > Hey @Adrianzo @ahwillia @vchuravy @dhhagan @jarvist would you be interested to review this paper?
> 
> I'm on parental leave until May 17th, but can then review this. 
> We have some partial reviews already? The history ^^^^ was a bit long to skim through!

Cool, I will assign you as the second reviewer. I have one reviewer already.

**Comment by diehlpk** [comment]
@whedon add @jarvist as reviewer

**Comment by whedon** [comment]
OK, @jarvist is now a reviewer

**Comment by vavrines** [comment]
Hi @fverdugo @sloede 
Would you be interested and have time review this paper?

**Comment by dhhagan** [comment]
@diehlpk I'm a bit busy with editing right now to take on any reviews, unfortunately. Sorry!

**Comment by fverdugo** [comment]
Hi! thanks for the review invitation @vavrines. I am currently reviewer in another JOSS paper and have no extra time to be involved in a second one unfortunately.

**Comment by sloede** [comment]
I have never reviewed at JOSS, how does it compare to a regular paper review in terms of effort? Also, what is the expected time frime? I am intrigued, but quite busy this and next week...

**Comment by vavrines** [comment]
@sloede Thanks for the interest : )
It's depends on a number of factors and hard to make a fair comparison. From my point of view on the checklist given by JOSS, it's easier to review here.
cc @diehlpk I remember the expected time frime you mentioned is 2 months. Given the long delay of the review process, I'm not sure if it stays the same in this round.

**Comment by sloede** [comment]
@vavrines I am sorry, but I have to decline. I wouldn't be able to do it within an appropriate time frame :-/
