### ISSUE TITLE
[PRE REVIEW]: Open Source Infrastructure Risk Analytics (osira)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2943]
**Submitting author:** @edwardoughton (<a href="http://orcid.org/0000-0002-2766-008X">Edward J. Oughton</a>)
**Repository:** <a href="https://github.com/edwardoughton/osira" target ="_blank">https://github.com/edwardoughton/osira</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @edwardoughton. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @danielskatz.

@edwardoughton if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (199.4 files/s, 19248.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            344            209            661
Markdown                         2             67              0            170
reStructuredText                 3             88             24            148
TeX                              1              7              0            120
DOS Batch                        1              8              1             26
YAML                             2              5              5             21
make                             1              4              7              9
INI                              1              3              0              4
-------------------------------------------------------------------------------
SUM:                            20            526            246           1159
-------------------------------------------------------------------------------


Statistical information for the repository 'd3218caf51c6230ee0375fc0' was
gathered on 2021/01/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ej550                           25          2211            997          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
ej550                      1214           54.9          0.0                8.32
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/jfr3.12288 is OK
- 10.1680/jcien.16.00018 is OK
- 10.1108/DPRG-02-2018-0004 is OK
- 10.1093/acrefore/9780199389407.013.315 is OK
- 10.1111/risa.13291 is OK
- 10.1193/013015EQS015M is OK
- 10.1007/s10669-018-9707-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02943/joss.02943/10.21105.joss.02943.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02943/joss.02943/10.21105.joss.02943.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope 

@edwardoughton thanks for your submission to JOSS – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by edwardoughton** [comment]
> @whedon query scope
> 
> @edwardoughton thanks for your submission to JOSS – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

Dear @arfon, okay, I haven't run into this with previous JOSS publications, so didn't know this was an issue. I have tried to be succinct in the codebase for brevity, with most of the work carried out as preprocessing (scripts/preprocessing.py). Best wishes, Ed

**Comment by arfon** [comment]
> Dear @arfon, okay, I haven't run into this with previous JOSS publications, so didn't know this was an issue. I have tried to be succinct in the codebase for brevity, with most of the work carried out as preprocessing (scripts/preprocessing.py). Best wishes, Ed

Thanks for the point. FYI, we introduced this new scope criterion last July: https://blog.joss.theoj.org/2020/07/minimum-publishable-unit

**Comment by edwardoughton** [comment]
Hi @arfon, thanks, I had a decent look over these requirements and also evaluated the other submissions you've flagged with this. I think the key point is that the software package reflects the research developed and published in the papers listed as citations on the repo, so there's many years' of work that's gone into figuring out how to do the processing. I have tried to keep things brief in the repo, but if you need more content that's fine, I can resubmit it with more functionality and documentation.  Best wishes, Ed

**Comment by kthyng** [comment]
Hi @edwardoughton and thanks for your submission. The editorial board did end up deciding that this submission is too small to pass our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) bar. We do encourage your resubmission after some substantial additional functionality to the software in which case we would reevaluate the package at that time.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
