### ISSUE TITLE
[PRE REVIEW]: CliquePercolation: An R Package for conducting and visualizing results of the clique percolation network community detection algorithm

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2944]
**Submitting author:** @LangeJens (<a href="http://orcid.org/0000-0002-5375-3247">Jens Lange</a>)
**Repository:** <a href="https://github.com/LangeJens/CliquePercolation" target ="_blank">https://github.com/LangeJens/CliquePercolation</a>
**Version:** 0.3.0
**Editor:** @karthik
**Reviewers:** @donaldRwilliams, @AlexChristensen
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @LangeJens. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @cMadan.

@LangeJens if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (96.9 files/s, 25952.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                7             95            913            734
XML                              1              0              8            612
TeX                              2             22              0            218
Rmd                              1            174            267            190
Markdown                         2             92              0            156
-------------------------------------------------------------------------------
SUM:                            13            383           1188           1910
-------------------------------------------------------------------------------


Statistical information for the repository '92c70fc71e6ebdf55f32271e' was
gathered on 2021/01/06.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02944/joss.02944/10.21105.joss.02944.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02944/joss.02944/10.21105.joss.02944.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btl039 is OK
- 10.1038/nphys2188 is OK
- 10.1086/386272 is OK
- 10.18637/jss.v048.i04 is OK
- 10.1088/1367-2630/9/6/180 is OK
- 10.1016/j.physrep.2009.11.002 is OK
- 10.1038/nature03607 is OK

MISSING DOIs

- 10.31219/osf.io/muvc3 may be a valid DOI for title: Emotions as Overlapping Causal Networks of Emotion Components: Implications and Methodological Approaches

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon query scope 

@LangeJens  thanks for your submission to JOSS – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

```
@whedon generate pdf
@whedon check references
```

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @LangeJens! We are wrapping up our scope query for your submission. One suggestion that came up a couple of times is whether this software could be integrated into a larger R package? Is there one that would be a logical choice for this? The idea is that smaller software would be used much more often potentially in a larger package that can cover more functions.

**Comment by LangeJens** [comment]
Hi @kthyng! Thank you very much for getting in touch. I am very thankful that you take the time to carefully consider my submission. Regarding your question: I did not yet program another R package of a broader scope into which CliquePercolation could be intergrated. Moreover, I am not collarborating with someone who developed a package into which CliquePercolation could be merged. Even though I wish to extend the package in the future with another popular method for identifying mixed communities, I cannot predict when (or even whether) this is going to happen.
Nevertheless, I want to emphasize that the clique percolation algorithm is popular and frequently used in practice. As a rough indication, the original paper introducing the classic algorithm was cited more than 5,000 times. Furthermore, the CliquePercolation package is downloaded 400 to 500 times each month, speaking to its popularity despite the fact that it is - admittedly - specialized and small compared to other R packages.

**Comment by kthyng** [comment]
@LangeJens Ok, thanks for your thorough response. Let us proceed with the review then. We see that the package is on the small side for JOSS, but we have also seen that it appears to fill a software need.

**Comment by kthyng** [comment]
@LangeJens Could you go through the editor list and suggest a handful more potential editors?

Also, please follow up on @arfon's comment about DOI's above.

**Comment by kthyng** [comment]
Oops, sorry everyone for the ping. @karthik are you interested in editing this submission?

> The missing doi for one paper was intentional. The manuscript was just accepted for publication and does not have an official doi as of yet. The doi whedon identified belongs to a preprint we uploaded on the Open Science Framework. As this doi will not be the final doi, I thought it would be better not to add it to the manuscript. However, if you prefer the preprint doi over not having a doi, I am happy to add it.

Let's wait for now and it can be addressed at the end of the review process, in case it has an official DOI at that time and this can all be ignored for now.

**Comment by kthyng** [comment]
@whedon invite @karthik as editor

**Comment by whedon** [comment]
@karthik has been invited to edit this submission.

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
👋 @LangeJens
I'll start to look for reviewers. Do you have suggestions for any independent reviewers that might be able to evaluate your submission? thanks.

**Comment by LangeJens** [comment]
@karthik 
Hi! Thanks for getting the process started. Here are two persons who I think could serve as reviewers: Payton Jones (payton_jones@g.harvard.edu; github: paytonjjones) and Giulio Costantini (giulio.costantini@unimib.it; github: GiulioCostantini).

**Comment by karthik** [comment]
👋 @paytonjjones 
Would you be able to review this submission?

**Comment by karthik** [comment]
👋 @GiulioCostantini 
Would you be able to review this submission?

**Comment by paytonjjones** [comment]
Unfortunately, I don't think I would be able to review this in a reasonable
time frame. Sacha Epskamp (sacha.epskamp@gmail.com) or Donald Williams (
drwwilliams@ucdavis.edu) might be good alternate reviewers.

**Comment by GiulioCostantini** [comment]
Hi all,
Unfortunately the same the same is true for me. I would suggest also Jonas
Haslbeck (jonashaslbeck@gmail.com) as another alternative reviewer,
All the best
Giulio

Giulio Costantini, PhD
Assistant professor
Psychology Department
University of Milano-Bicocca
P.zza dell'Ateneo Nuovo, 1 (U6) - room 3127
20126 Milan (MI)
Phone ++39 02.6448.3839


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno mer 3 feb 2021 alle ore 22:13 Payton J. Jones <
notifications@github.com> ha scritto:

**Comment by LangeJens** [comment]
I want to mention, that I know Sacha Epskamp and Jonas Haslbeck from my time in Amsterdam. I worked in another department at the same university and we met in group as well as personal meetings. I do not necessarily believe that they would have a conflict of interest, but I wanted to disclose this in case it is relevant.

**Comment by karthik** [comment]
Thanks for that disclosure @LangeJens 
I believe this is totally fine.

@SachaEpskamp 👋 Would you be able to review this submission for us?

**Comment by donaldRwilliams** [comment]
@karthik 
I can review the submission (I received an email earlier).

**Comment by SachaEpskamp** [comment]
I am afraid I won't be able to do the review now, sorry.

**Comment by karthik** [comment]
@whedon add @donaldRwilliams as reviewer

**Comment by whedon** [comment]
OK, @donaldRwilliams is now a reviewer

**Comment by karthik** [comment]
No worries, Sacha. Thanks for letting us know.

**Comment by LangeJens** [comment]
Just to be sure, is the review process currently ongoing or do you wait for me to recommend more reviewers?

**Comment by paytonjjones** [comment]
I was expecting you to move on to other reviewers - I'm not reviewing the
manuscript!

**Comment by donaldRwilliams** [comment]
> Just to be sure, is the review process currently ongoing or do you wait for me to recommend more reviewers?

@LangeJens I am a reviewer. Getting to it this week :-)

**Comment by donaldRwilliams** [comment]
@karthik I noted the software has under 1,000 lines of R code, yet it was not flagged according to the guidelines, in addition to having 25 commits.

I am happy to review anyhow, but want to be sure it is worth my time given the length of code and submit history. Thanks !

**Comment by donaldRwilliams** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02944/joss.02944/10.21105.joss.02944.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02944/joss.02944/10.21105.joss.02944.pdf) :page_facing_up: :point_left:

**Comment by karthik** [comment]
Hi @donaldRwilliams Thanks for the note. I'll look into it and get back to you. I'm still trying to locate the second reviewer before starting the review process.

**Comment by karthik** [comment]
> Just to be sure, is the review process currently ongoing or do you wait for me to recommend more reviewers?

Still waiting on a second reviewer. I'm open to suggestions if you have more people in mind.

**Comment by donaldRwilliams** [comment]
> Hi @donaldRwilliams Thanks for the note. I'll look into it and get back to you. I'm still trying to locate the second reviewer before starting the review process.

@karthik Sounds good. So I am not supposed to start my review ?

**Comment by LangeJens** [comment]
@donaldRwilliams @karthik The editorial office already decided that despite the fewer lines of code, the submission can go into review. I still see it in the history of this thread here but potentially you two don't because you have been invited later. Kristen Thyng decided it.
Regarding reviewers, Claudia Van Borkulo (cvborkulo) or Hudson Golino (hfgolino) may also fit.

**Comment by karthik** [comment]
Thanks. I'll update the thread when I hear back from these reviewers.

**Comment by karthik** [comment]
@LangeJens  FYI I am still seeking reviewers. I've had about 4 declines and I am pursuing more leads.

**Comment by LangeJens** [comment]
Thanks for getting in touch! If it is of any help, you could also ask Julian Burger or Riet Van Bork from the University of Amsterdam. I know that they also contribute to R packages although they do not seem to have github pages themselves.

**Comment by karthik** [comment]
I've reached out to Julian and will follow up with Riet Van Bork if he doesn’t respond.

**Comment by karthik** [comment]
@LangeJens Still no bites on the second reviewer. Julian and Riet both declined. I'll keep looking but also welcome more suggestions.

**Comment by AlexChristensen** [comment]
@karthik,

I accepted the review

**Comment by karthik** [comment]
@whedon add @AlexChristensen as reviewer

**Comment by whedon** [comment]
OK, @AlexChristensen is now a reviewer

**Comment by karthik** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3210.
