### ISSUE TITLE
[REVIEW]: sboxgates: A program for finding low gate count implementations of S-boxes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2946]
**Submitting author:** @dansarie (<a href="http://orcid.org/0000-0001-9246-0263">Marcus Dansarie</a>)
**Repository:** <a href="https://github.com/dansarie/sboxgates" target ="_blank">https://github.com/dansarie/sboxgates</a>
**Version:** v2.0.0
**Editor:** @VivianePons
**Reviewers:** @gradvohl, @HeshamAlsaadi
**Archive:** <a href="https://doi.org/10.5281/zenodo.4954685" target="_blank">10.5281/zenodo.4954685</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/66d05c0a21c5b63b2bc31b030cac9510/status.svg)](https://joss.theoj.org/papers/66d05c0a21c5b63b2bc31b030cac9510)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/66d05c0a21c5b63b2bc31b030cac9510"><img src="https://joss.theoj.org/papers/66d05c0a21c5b63b2bc31b030cac9510/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/66d05c0a21c5b63b2bc31b030cac9510/status.svg)](https://joss.theoj.org/papers/66d05c0a21c5b63b2bc31b030cac9510)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dansarie/sboxgates" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gradvohl & @gcdeshpande & @5998, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @VivianePons know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dansarie/sboxgates">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dansarie) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dansarie/sboxgates">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dansarie) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gradvohl, @gcdeshpande it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2946 with the following error: 

 Can't find any papers to compile :-(

**Comment by VivianePons** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: :point_left:

**Comment by VivianePons** [comment]
Hi, we now have two reviewers and we move the discussion here.

@gradvohl has already made some comments [over here, in the pre-review issue](https://github.com/openjournals/joss-reviews/issues/2932#issuecomment-756133402)  . @dansarie can you have a look?

Thank you very much to @gradvohl and  @gcdeshpande let me know if you have issues or questions

**Comment by dansarie** [comment]
@VivianePons I looked over @gradvohl's comments and updated the repo. Responses below.

> * Tests: :-1:  (bad)

This did not come with any clarification. Testing is done by Travis CI automatically on each commit. I've updated the readme to make this clearer.

> ### Documentation in source code
> 
> The author comments on some functions in the .h files, while other comments are in .c files. Also, most of the comments describe the functions at a high level only. It would be interesting to say what the parameters are and what they are needed for.
> 
> **Suggestion**: Uniform where you will write the comments and, if possible, use a standard for documentation of functions, parameters, and returns (such as [Doxygen](https://www.doxygen.nl)).

All documentation of functions has been moved to header files and all parameters should now be documented.

> * When I tried to build the software with `cmake` it required the CMake 3.10 or higher.
> 
> * **Suggestion**: Inform the user what are the required versions (especially CMake).

After testing, the required CMake version has been lowered to 3.9. The readme has been updated with information about the lowest required version.

> * When I tried to `cmake ..`, it raised the following error:
>   `-- Could NOT find MPI_C (missing: MPI_mpich_LIBRARY MPI_opa_LIBRARY MPI_mpl_LIBRARY MPI_C_WORKS)`
> 
> * **Suggestion**: Inform the user what are the main environment variables must be set. Besides, I suspect that `mpich-devel` is also a dependency.

Installation of the `libmpich-dev` package is documented in the build section of the readme. CMake uses the script that is installed with the MPI implementation to search for MPI, so setting any environment variables shouldn't be required.

> ### Questions:
> 
> When running with mpirun, may the user specify the number of processes and `hostfile` with processes location (for instance, `mpirun -np 4 --hostfile file ...`? If so, the author should clarify this in the instructions for running the software.

Yes. I have updated the readme with guidance on how to specify the number of processes and a reference to the MPI documentation.

>  1. Please consider to add the author's name and contact info in the `README.md`.

The readme has been updated with my name and a link to my Github profile.

>  2. In `paper.md`, the author states that CUDA is a "programming language for GPUs". However, CUDA is an Application Programming Interface (API) or a library, if you prefer.

I have changed this to "a parallel computing platform for Nvidia GPUs" in the paper.

**Comment by dansarie** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: :point_left:

**Comment by gradvohl** [comment]
# Review itens for JOSS paper #2946
**Paper title**: sboxgates: A program for finding low gate count implementations of S-boxes
**Review round two**

## Review criteria
* A list of the authors of the software: :heavy_check_mark:
* Author affiliations: :heavy_check_mark:
* A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience: :heavy_check_mark:
* A clear statement of need that illustrates the purpose of the software: :heavy_check_mark:
* Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it: :heavy_check_mark:
* A list of key references including a link to the software archive:  :heavy_check_mark:

## Review items
* Software license: :thumbsup: (good - GPL v3) 

* Documentation: 
    * A statement of need: :thumbsup: (good) 
    * Installation instructions: :thumbsup: (good) 
    * Example usage: :thumbsup: (good) 
    * API documentation: :thumbsup: (good)
    * Community guidelines: :thumbsup: (good)
    * Functionality: :thumbsup: (good) 
    * Tests: :thumbsup: (good -- *It means that the software passed in my own tests, not the automatic ones*)

* Software paper
    * Authors: :heavy_check_mark:
    * A statement of need: :heavy_check_mark:
    * References: :heavy_check_mark:

## Reviewer comments
The author addressed all comments from Round 1. Therefore, I am satisfied with the software and with the documentation. 
However, when I tried to run, it took much time to process the examples the author proposed. I know that the software addresses a complex computational problem. Still, I suggest that the author includes a section warning the users that the program may take high processing time to produce a result.
I ran the software on an AWS instance (t2.xlarge) with Ubuntu 20.04.

 
## Conclusion
Analyzing all the aspects mentioned earlier, I consider the paper **ready for publication**.

**Comment by VivianePons** [comment]
Thank you very much @gradvohl for such an effective review. You have left the "Performance" box unchecked is it just a mistake? Can you check?

Thanks

**Comment by gradvohl** [comment]
> 
> 
> Thank you very much @gradvohl for such an effective review. You have left the "Performance" box unchecked is it just a mistake? Can you check?
> 
> Thanks

Sorry. It is ok now.
Best.

**Comment by whedon** [comment]
:wave: @gcdeshpande, please update us on how your review is going.

**Comment by gcdeshpande** [comment]
@whedon I am setting up the system. I was facing the issue with my system. Will try to complete by first week of February.

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by VivianePons** [comment]
Hi, just checking in to see how we are doing over here (as a real person this time, not a robot!)

@gcdeshpande did you manage to solve the issue with your system? By the way, if the issues are related to this software, please update the author on what they are. Especially if you're having trouble solving it as this might be useful for future users.

**Comment by VivianePons** [comment]
Hi @gcdeshpande I wondered if you could give us an update on the review? Or even a timeframe on when you believe you'll be able to get to it

**Comment by dansarie** [comment]
@VivianePons We haven't heard anything from the reviewer for three months now. I understand that there are many legitimate reasons for this, but is there something we can do to move this along?

**Comment by VivianePons** [comment]
@dansarie Definetly, sorry I was myself very busy and didn't take the time to move things forward. I will contact new reviewers soon.

Thank you for your patience

**Comment by dansarie** [comment]
@VivianePons Thank you!

**Comment by VivianePons** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: :point_left:

**Comment by VivianePons** [comment]
@whedon add @5998 as reviewer

**Comment by 5998** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: :point_left:

**Comment by 5998** [comment]
@whedon list editors

**Comment by 5998** [comment]
@whedon check references

**Comment by 5998** [comment]
@whedon check references

**Comment by whedon** [comment]
PDF failed to compile for issue #2946 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by heshamalsaadi** [comment]
@whedon accept

**Comment by whedon** [comment]
I'm sorry @heshamalsaadi, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by 5998** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2946 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by HeshamAlsaadi** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: :point_left:

**Comment by VivianePons** [comment]
@whedon remove @5998 as reviewer

**Comment by whedon** [comment]
OK, @5998 is no longer a reviewer

**Comment by VivianePons** [comment]
@whedon add @HeshamAlsaadi as reviewer

**Comment by whedon** [comment]
OK, @HeshamAlsaadi is now a reviewer

**Comment by HeshamAlsaadi** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: :point_left:

**Comment by VivianePons** [comment]
@whedon re-invite @HeshamAlsaadi as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@heshamalsaadi please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by HeshamAlsaadi** [comment]
**I want to add the following comments:**
The references need to be built automatically from the .bib file (which will be added to the .pdf). Please follow this guideline here for implementation https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography; this will allow the citation to be very helpful and compiled correctly for a reference check.

**Comment by dansarie** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BFb0052352 is OK
- 10.1007/11545262_32 is OK
- 10.1007/3-540-45848-4_57 is OK
- 10.3233/SAT190099 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dansarie** [comment]
@HeshamAlsaadi The references in the .bib file look ok to me and the reference check seems to be working.

**Comment by VivianePons** [comment]
Hi @HeshamAlsaadi I see that you have checked all the boxes. Can I conclude that you are happy with the software and move on to publication?

Thank you

**Comment by HeshamAlsaadi** [comment]
> Hi @HeshamAlsaadi I see that you have checked all the boxes. Can I conclude that you are happy with the software and move on to publication?
> 
> Thank you

Definitely yes

**Comment by VivianePons** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02946/joss.02946/10.21105.joss.02946.pdf) :page_facing_up: :point_left:

**Comment by VivianePons** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BFb0052352 is OK
- 10.1007/11545262_32 is OK
- 10.1007/3-540-45848-4_57 is OK
- 10.3233/SAT190099 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by VivianePons** [comment]
@whedon remove @gcdeshpande as reviewer

**Comment by whedon** [comment]
OK, @gcdeshpande is no longer a reviewer

**Comment by VivianePons** [comment]
Hi @dansarie thank you for your patience, we can move toward acceptance! 

Can you make a new tagged release of the software (if needed) an archive it (on Zenodo, figshare, or other)? Please be careful to use the same metadata than the paper (title and authors). Send me the doi when you are done!

**Comment by dansarie** [comment]
@VivianePons done!

The tagged release (v2.0.0) is available at [https://github.com/dansarie/sboxgates/releases/tag/v2.0.0](https://github.com/dansarie/sboxgates/releases/tag/v2.0.0).
Version 2.0.0 has been archived at Zenodo with [doi:10.5281/zenodo.4954685](https://doi.org/10.5281/zenodo.4954685). (The latest version is always available through [doi:10.5281/zenodo.891020](https://doi.org/10.5281/zenodo.891020).)

**Comment by VivianePons** [comment]
Can you update the title on Zenodo so that it is the same as the paper?

**Comment by dansarie** [comment]
@VivianePons Ok! It should be fixed now.

**Comment by VivianePons** [comment]
@whedon set 10.5281/zenodo.4954685 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4954685" target="_blank">10.5281/zenodo.4954685</a> is the archive.

**Comment by VivianePons** [comment]
@whedon set v2.0.0 as version

**Comment by VivianePons** [comment]
Thank you! We ow have everything to accept the paper into JOSS. Thanks a lot to @dansarie for the contribution and thank you @gradvohl and @HeshamAlsaadi for the reviews :)

**Comment by VivianePons** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2946 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by VivianePons** [comment]
@whedon recommend-accept from branch paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2946 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by VivianePons** [comment]
@whedon recommend-accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BFb0052352 is OK
- 10.1007/11545262_32 is OK
- 10.1007/3-540-45848-4_57 is OK
- 10.3233/SAT190099 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2393

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2393, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1405148536346398723) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2394
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02946](https://doi.org/10.21105/joss.02946)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @dansarie (Marcus Dansarie)!!

And thanks to @gradvohl and @HeshamAlsaadi for reviewing, and @VivianePons for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02946/status.svg)](https://doi.org/10.21105/joss.02946)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02946">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02946/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02946/status.svg
   :target: https://doi.org/10.21105/joss.02946
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02946/status.svg)](https://doi.org/10.21105/joss.02946)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
