### ISSUE TITLE
[PRE REVIEW]: Coral: a parallel spectral solver for fluid dynamics and partial differential equations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2947]
**Submitting author:** @benmql (<a href="http://orcid.org/0000-0001-6283-0382">BENJAMIN MIQUEL</a>)
**Repository:** <a href="https://github.com/BenMql/coral" target ="_blank">https://github.com/BenMql/coral</a>
**Version:** v1.0.1
**Editor:** @eloisabentivegna
**Reviewers:** @robertsawko, @rhaas80
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @benmql. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @eloisabentivegna.

@benmql if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1017/jfm.2020.485 is OK

MISSING DOIs

- 10.1103/physrevfluids.4.121501 may be a valid DOI for title: Convection driven by internal heat sources and sinks: Heat transport beyond the mixing-length or “ultimate” scaling regime

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.57 s (232.0 files/s, 27731.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                      50           1164           1279           9193
Python                          59            709            278           2331
Bourne Shell                    14             94             96            308
make                             3             25              7            102
C                                1             14              0             56
Markdown                         2             17              0             38
TeX                              1              5              0             28
YAML                             2              2              4             28
-------------------------------------------------------------------------------
SUM:                           132           2030           1664          12084
-------------------------------------------------------------------------------


Statistical information for the repository '023953a7bc1ed534e1cee3f6' was
gathered on 2021/01/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
benmql                           2          3626              5          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
benmql                     3621           99.9          0.0                7.18
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02947/joss.02947/10.21105.joss.02947.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02947/joss.02947/10.21105.joss.02947.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by eloisabentivegna** [comment]
@whedon add @robertsawko as reviewer

**Comment by whedon** [comment]
OK, @robertsawko is now a reviewer

**Comment by BenMql** [comment]
@eloisabentivegna Thank you for accepting to handle the submission as an editor.

As suggested, I include below a few suggestions for referees (selected in the list of JOSS referees):
- mikaem
- harpolea
- p-costa
In addition to existing referees, the following scientists would be suitable for reviewing:
- Dr. Adrian Barker (U. Leeds), https://eps.leeds.ac.uk/maths/staff/4006/dr-adrian-j-barker
- Dr. Celine Guervilly (U. Newcastle), https://www.ncl.ac.uk/maths-physics/staff/profile/celineguervilly.html#background
- Dr. Thomas Gastine (CNRS-IPGP), http://www.ipgp.fr/~gastine/
- Dr. Benjamin Favier (Aix-Marseille U., CNRS), https://sites.google.com/site/bfavierhome/home?authuser=0

Thank you! --BM

**Comment by eloisabentivegna** [comment]
@whedon add @rhaas80 as reviewer

**Comment by whedon** [comment]
OK, @rhaas80 is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2978.
