### ISSUE TITLE
[REVIEW]: NiaAML: AutoML framework based on stochastic population-based nature-inspired algorithms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2949]
**Submitting author:** @lukapecnik (<a href="http://orcid.org/0000-0002-3897-9774">Luka Pečnik</a>)
**Repository:** <a href="https://github.com/lukapecnik/NiaAML" target ="_blank">https://github.com/lukapecnik/NiaAML</a>
**Version:** 1.1.0
**Editor:** @arfon
**Reviewer:** @adi3, @sara-02
**Archive:** <a href="https://doi.org/10.5281/zenodo.4782445" target="_blank">10.5281/zenodo.4782445</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/273ea8b67562eab528ec57c0458449cb/status.svg)](https://joss.theoj.org/papers/273ea8b67562eab528ec57c0458449cb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/273ea8b67562eab528ec57c0458449cb"><img src="https://joss.theoj.org/papers/273ea8b67562eab528ec57c0458449cb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/273ea8b67562eab528ec57c0458449cb/status.svg)](https://joss.theoj.org/papers/273ea8b67562eab528ec57c0458449cb)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/lukapecnik/NiaAML" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@adi3 & @sara-02, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lukapecnik/NiaAML">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@lukapecnik) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lukapecnik/NiaAML">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@lukapecnik) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @adi3, @sara-02 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-981-15-2133-1_13 is OK
- 10.21105/joss.00613 is OK
- 10.1109/IJCNN.2015.7280767 is OK
- 10.1007/978-3-030-05318-5 is OK

MISSING DOIs

- 10.1007/978-3-030-05318-5_8 may be a valid DOI for title: TPOT: A tree-based pipeline optimization tool for automating machine learning

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02949/joss.02949/10.21105.joss.02949.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02949/joss.02949/10.21105.joss.02949.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@adi3, @sara-02 - This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/2949 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by adi3** [comment]
@lukapecnik thank you for your submission to JOSS. Your paper is a great start, but can do with a few modifications. Here are a few recommendations:

1. The summary section gets a little repetitive. For instance:
- "The framework incorporates stochastic population-based nature-inspired algorithms to search for the best classification pipeline"
- "NiaAML is slightly different, regarding the search for a perfect pipeline with the use of stochastic population-based nature-inspired algorithms"
- "In conclusion, NiaAML is an AutoML framework based on stochastic population-based nature-inspired algorithms."

Please edit the summary to avoid such repetitions.

2. The first paragraph of your Summary should to belong to the Statement of Need section.

3. I would like to see some content, if only a couple of lines, on what this "nature-inspired algorithm" is. How is it nature-inspired and why is that a good approach? It seems like that is the critical scholarly effort here, and without any explanation around this concept, there is nothing that clearly distinguishes NiaAML from other AutoML libraries.

**Comment by lukapecnik** [comment]
The authors would like to thank the Reviewer @adi3  sincerely for the
time spent on reading and commenting on the paper.

The given remarks are very thorough, and extremely helpful to overcome
the shortcomings and ambiguities in our paper.

In what follows, a point-by-point reply to the Reviewer’s remarks,
comments and suggestions is given.

--------------------------------------------------------------------

1. Repetitive sentences are now omitted from the manuscript.

2. As per your request, the first paragraph in the Summary Section has
been moved to the Statement of Need Section.

3. Good point! We have added a few lines of nature-inspired algorithms`
description. Moreover, we have also added some
literature about nature-inspired algorithms where the readers can gain
more information about these concepts.
Arguments that distinguish NiaAML from the other similar solutions in a
little bit more detail have now been added to
our paper.

**Comment by adi3** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02949/joss.02949/10.21105.joss.02949.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02949/joss.02949/10.21105.joss.02949.pdf) :page_facing_up: :point_left:

**Comment by adi3** [comment]
@lukapecnik Thanks for the changes. I will be making some editorial changes myself to the draft and issuing a pull request. Please review it and merge it into your master branch. These edits will mostly be to correct syntactic usage or word choices. The aim is to keep the article crisp and to the point. It is faster for me to make these changes and issue a pull request instead of leading you through them. Let me know if you have any questions. Once you have merged the pull request, please notify me here so we can proceed.

**Comment by lukapecnik** [comment]
@adi3 Thank you for the pull request. I have reviewed and merged it.

**Comment by adi3** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02949/joss.02949/10.21105.joss.02949.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02949/joss.02949/10.21105.joss.02949.pdf) :page_facing_up: :point_left:

**Comment by adi3** [comment]
@lukapecnik Thank you. While I go through the remainder of the checklist, can you please figure out why one of your references is showing up as having a missing DOI?

```
MISSING DOIs

- 10.1007/978-3-030-05318-5_8 may be a valid DOI for title: TPOT: A tree-based pipeline optimization tool for automating machine learning
```

**Comment by lukapecnik** [comment]
@adi3 We have added the missing DOI after the submission. I think this should be fixed now.

**Comment by adi3** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-981-15-2133-1_13 is OK
- 10.21105/joss.00613 is OK
- 10.1109/IJCNN.2015.7280767 is OK
- 10.1007/978-3-030-05318-5_8 is OK
- 10.1007/978-3-030-05318-5 is OK
- 10.1002/9780470512517 is OK
- 10.1016/b978-0-12-416743-8.00017-8 is OK
- 10.1016/j.dib.2020.105792 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @adi3, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @sara-02, please update us on how your review is going.

**Comment by adi3** [comment]
I'll make further progress on my checklist this week.

**Comment by adi3** [comment]
@lukapecnik I'm reviewing your installation instructions.

- I recommend you specify supported OS that your software has been tested on and is confirmed to work. For instance, I was able to do pip installation just fine on Ubuntu, but ran into hurdles installing it on RHEL.
- The conda installation is failing at my end. I'm opening an issue on your repo so you can debug and look into it.

Please let me know when these two points have been fixed and I'll proceed. Thanks!

**Comment by lukapecnik** [comment]
@adi3 Thank you. 

- We have specified the OS we have tested the NiaAML package on.
- Good point, we have switched pip to pip3 as you suggested.
- Thank you for pointing out the `conda` failure. We surely will fix this option in the near future, but the investigation may take some time as after a few days we still have not found the reason why it is not working. That is why we decided to temporarily disable the installation using `conda` so the process of reviewing the package may proceed for now if you agree.

Thank you.

**Comment by lukapecnik** [comment]
Hello @adi3 and @sara-02, I hope you are both doing well. How are things going forward with this review? Is there anything we can do so far to improve this framework and make it more suitable for publishing the paper in JOSS?

We are looking forward to hearing from you.
Thank you in advance.

**Comment by adi3** [comment]
Hi @lukapecnik - I could not find any automated tests in your repo. Can you add some for the key functionalities, or if you already have them, document them in the readme?

**Comment by lukapecnik** [comment]
Hi @adi3, the tests are available [here](https://github.com/lukapecnik/NiaAML/tree/master/niaaml/tests), and the instructions on how to run them are available in the `CONTRIBUTING.md`. They are also automated using the TravisCI platform (see `.travis.yml`). Test coverage is also available as a badge on top of the root `README.md` or via the Coveralls platform.

Do you think the instructions should be moved from the `CONTRIBUTING.md` to the root `README.md`?

Best regards

**Comment by adi3** [comment]
I think leaving them in `CONTRIBUTING.md` is fine. Thanks for pointing them out to me. I'll run them and get back to you with feedback.

**Comment by adi3** [comment]
@lukapecnik in your examples folder, can you please changes all occurrences of `python` to `python3`? This at least has to be the case in `run_all.sh` and `run_all.bat` files. Please do a search on other files as well. Since you are documenting the installation with `python3`, your examples should assume to run in that environment as well.

**Comment by adi3** [comment]
@lukapecnik Can you please move the `Support` section from `CONTRIBUTING.md` to the main `README.md`? Also, please add a section for `Issues` in `README.md` and copy here the text you have under `Reporting Bugs` in `CONTRIBUTING.md`. Thanks! This is coming together pretty well.

**Comment by lukapecnik** [comment]
Hi @adi3, thank you very much for your effort and quick response! I think I've improved the NiaAML repository now according to your great suggestions.

Best regards

**Comment by adi3** [comment]
@lukapecnik thank you for making the changes. My checklist is complete and I will recommend this for publication. Good job!

@arfon I have completed my review against the JOSS checklist, and this submission meets our standard for publication.

**Comment by arfon** [comment]
> @lukapecnik thank you for making the changes. My checklist is complete and I will recommend this for publication. Good job!

🙌 thanks so much @adi3! @sara-02 any updates on the progress you are making with yours?

**Comment by lukapecnik** [comment]
@adi3 great news! Thank you very much for your review and for making the NiaAML project better.

Best regards

**Comment by lukapecnik** [comment]
Hello @arfon and @sara-02, we were wondering whether there has been some status update about this pending review. What are the next steps towards publishing? The authors of the NiaAML would be very happy if we can improve NiaAML with some further guidance and finish publishing in the following days. Thank you.

**Comment by lukapecnik** [comment]
Hello @arfon and @sara-02! I hope you are well. We were wondering whether this review is going to be completed shortly. The authors would really like to use the JOSS paper as the base for further research in this research area.

We are looking forward to hearing from you soon.

Best regards

**Comment by arfon** [comment]
Hi @lukapecnik, apologies this is taking a little longer than we might have hoped here. I've just followed up with @sara-02 to see when they might be able to complete their review by.

**Comment by lukapecnik** [comment]
Hi @arfon, thank you for responding. Has there been any response from @sara-02? Thank you.

**Comment by lukapecnik** [comment]
Hi @arfon, I hope you're well. I am wondering whether the review is going to be complete soon? It's been a month since the last update and we'd really like to know the current status.

Best regards

**Comment by arfon** [comment]
Hi @lukapecnik - you have exactly the same information as me at this point sorry. I'd like to give a little more time to @sara-02 before seeking out a second reviewer.

**Comment by sara-02** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02949/joss.02949/10.21105.joss.02949.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02949/joss.02949/10.21105.joss.02949.pdf) :page_facing_up: :point_left:

**Comment by sara-02** [comment]
Hey @lukapecnik I was trying to run the[ following example](https://github.com/lukapecnik/NiaAML#example-of-usage) post installing `niaaml` and `Niapy` but when I copy pasted the example code to a python file and ran it, I am getting this error:
```
Traceback (most recent call last):
  File "niml.py", line 1, in <module>
    from niaaml import PipelineOptimizer, Pipeline
  File "/home/sarah/.local/lib/python3.8/site-packages/niaaml/__init__.py", line 3, in <module>
    from niaaml import preprocessing
  File "/home/sarah/.local/lib/python3.8/site-packages/niaaml/preprocessing/__init__.py", line 2, in <module>
    from niaaml.preprocessing import feature_selection
  File "/home/sarah/.local/lib/python3.8/site-packages/niaaml/preprocessing/feature_selection/__init__.py", line 3, in <module>
    from niaaml.preprocessing.feature_selection.jDEFSTH import jDEFSTH
  File "/home/sarah/.local/lib/python3.8/site-packages/niaaml/preprocessing/feature_selection/jDEFSTH.py", line 2, in <module>
    from NiaPy.algorithms.modified import SelfAdaptiveDifferentialEvolution
ModuleNotFoundError: No module named 'NiaPy'
```

**Comment by lukapecnik** [comment]
Hi @sara-02! Thank you for issue report. It seems that there's been a bit of an API change for the `niapy` package in the meantime. I created a new release of the `niaaml` (version 1.1.2) that should fix this problem. Please update the `niaaml` package and then the example should run smoothly.

Best regards

**Comment by sara-02** [comment]
@arfon @lukapecnik Sorry for the delay from my side, I have completed the review now.

**Comment by lukapecnik** [comment]
@sara-02 great news! Thank you very much for your effort and reported issue. You helped with making our software better. I wish you all the best 🎉 🙌

@arfon is there anything else that needs to be done from our side now? Thank you

**Comment by arfon** [comment]
@lukapecnik – At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by lukapecnik** [comment]
Hello @arfon! I've archived the project using Zenodo. The DOI is `10.5281/zenodo.4782445` and the link to the archive is [https://zenodo.org/record/4782445#.YKqPs6gzaUl](url). I hope this is what you had in mind with updating this thread, otherwise please let me know.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4782445 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4782445" target="_blank">10.5281/zenodo.4782445</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-981-15-2133-1_13 is OK
- 10.21105/joss.00613 is OK
- 10.1109/IJCNN.2015.7280767 is OK
- 10.1007/978-3-030-05318-5_8 is OK
- 10.1007/978-3-030-05318-5 is OK
- 10.1002/9780470512517 is OK
- 10.1016/b978-0-12-416743-8.00017-8 is OK
- 10.1016/j.dib.2020.105792 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2335

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2335, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1396558912795652102) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2336
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02949](https://doi.org/10.21105/joss.02949)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@adi3, @sara-02 – many thanks for your reviews here! JOSS relies upon the volunteer efforts of folks like you, and we simply wouldn't be able to do this without you ✨ 

@lukapecnik – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02949/status.svg)](https://doi.org/10.21105/joss.02949)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02949">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02949/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02949/status.svg
   :target: https://doi.org/10.21105/joss.02949
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02949/status.svg)](https://doi.org/10.21105/joss.02949)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by lukapecnik** [comment]
@arfon thank you very much! 🎉 

@adi3 and @sara-02 I thank you again in the name of both authors for your reviews and making our project better.

Best regards
