### ISSUE TITLE
[REVIEW]: biotmle: Targeted Learning for Biomarker Discovery

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#295]
**Submitting author:** @nhejazi (<a href="http://orcid.org/0000-0002-7127-2789">Nima Hejazi</a>)
**Repository:** <a href="https://github.com/nhejazi/biotmle" target ="_blank">https://github.com/nhejazi/biotmle</a>
**Version:** v0.1.0
**Editor:** @karthik
**Reviewer:** @NelleV
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.834849" target="_blank">10.5281/zenodo.834849</a>

## Status

[![status](http://joss.theoj.org/papers/02be843d9bab1b598187bfbb08ce3949/status.svg)](http://joss.theoj.org/papers/02be843d9bab1b598187bfbb08ce3949)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/02be843d9bab1b598187bfbb08ce3949"><img src="http://joss.theoj.org/papers/02be843d9bab1b598187bfbb08ce3949/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/02be843d9bab1b598187bfbb08ce3949/status.svg)](http://joss.theoj.org/papers/02be843d9bab1b598187bfbb08ce3949)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/nhejazi/biotmle" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/nhejazi/biotmle">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (nhejazi) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @NelleV it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by nhejazi** [comment]
To the reviewer (@NelleV) -- please make sure to evaluate only the `develop` branch of this project, as it contains several important changes that have not yet been moved to `master` (this is because `master` is currently in line with the version of this package currently available on Bioconductor). Thanks!

**Comment by NelleV** [comment]
I'll keep this in mind.

**Comment by nhejazi** [comment]
Best to consult the `master` branch now. `develop` now contains some functionality that is statistically questionable and still needs to be thought about.

**Comment by NelleV** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by NelleV** [comment]
Hi @nhejazi 

I've done a first pass at reviewing the paper (sorry it took so long), and I have a few comments:

- The version number specified in the ticket is wrong, though I don't see where it is specified. The bioconductor version and the github one do match.
- The contribution guidelines are missing. It'd be nice to have a small section in the readme to help new contributors.

There are still a couple of things I need to look at, but I'll get back to you soon.

**Comment by nhejazi** [comment]
Hi @NelleV ---

Thanks much for taking the time to go through our `biotmle` package. I've gone ahead and made the suggested changes as of 1d40f60. In regard to package versioning, I've put the current version (1.1.2) of the GitHub package in the `codemeta.json` file, as the current status of the package reflects changes that will be present in the [development version on Bioconductor](https://bioconductor.org/packages/devel/bioc/html/biotmle.html), which will become the stable release when Bioconductor 3.6 becomes the standard in the Fall.

**Comment by karthik** [comment]
👋 @NelleV  I know you're just back from SciPy and are catching up, but once you are caught up, can you please let me know if you're ready to sign off? 🙏

**Comment by NelleV** [comment]
LGTM!

**Comment by karthik** [comment]
Awesome! Thanks @NelleV! We appreciate your time to review this submission. 🙏

@nhejazi Can you please archive this submission on Zenodo and update the thread with the DOI so I can move forward with the acceptance?

**Comment by nhejazi** [comment]
Thanks very much for taking the time to review this package @NelleV! 🙏
@karthik -- thanks very much for your help throughout the review process!

I've archived v1.1.2 of the package and generated a DOI via Zenodo: DOI: 10.5281/zenodo.834849. Please let me know if there's anything more on my end.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.834849 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.834849" target="_blank">10.5281/zenodo.834849</a> is the archive.

**Comment by arfon** [comment]
@nhejazi - it looks like there are two paper files (`paper.md` and `paper.Rmd`). The later looks to be more closely aligned with our expected format. Could you confirm that the `paper.Rmd` should be the file we should be looking at here? If so, please delete the `paper.md` file.

**Comment by nhejazi** [comment]
Confirming that `paper.Rmd` is the appropriate (reproducible) file to be using here. `paper.md` and (now) unnecessary supporting files have been removed as of the latest commit on `master`.

**Comment by arfon** [comment]
OK thanks @nhejazi. Can you clarify why this is `.Rmd` and not `.md` - our submission tooling is heavily automated and expects to find a file named `paper.md` not `paper.Rmd` 😁

**Comment by nhejazi** [comment]
Oh, based on a different JOSS submission that I was involved in, the reviewer asked for an `.Rmd` to ensure reproducibility of results. That submission ended up getting stalled on our end, but I went ahead with applying the suggestion to this submission. I should be able to pretty easily convert it to `.md` if you'd like.

**Comment by arfon** [comment]
>  I should be able to pretty easily convert it to `.md` if you'd like.

👍 Yes please.

**Comment by nhejazi** [comment]
Done! `.Rmd` -> `.md`, and everything looks close enough to what I had intended.

**Comment by arfon** [comment]
@NelleV - many thanks for your review here and to @karthik for editing this one ✨ 

@nhejazi - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00295 ⚡️ 🚀 💥

**Comment by nhejazi** [comment]
Awesome!

Thanks again @NelleV, @karthik, @arfon!
