### ISSUE TITLE
[PRE REVIEW]: OpenRepGrid.ic: A software for Interpretive Clustering

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2951]
**Submitting author:** @markheckmann (<a href="http://orcid.org/0000-0002-0736-7417">Mark Heckmann</a>)
**Repository:** <a href="https://github.com/markheckmann/OpenRepGrid.ic" target ="_blank">https://github.com/markheckmann/OpenRepGrid.ic</a>
**Version:** v0.5.0
**Editor:** @gkthiruvathukal
**Reviewers:** @aj2duncan, @brunaw
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @markheckmann. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @cMadan.

@markheckmann if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.35 s (55.0 files/s, 10034.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               10            366            327           1661
HTML                             1              3              0            553
Markdown                         3             83              0            143
Rmd                              2             73            136             56
YAML                             3             17              8             41
-------------------------------------------------------------------------------
SUM:                            19            542            471           2454
-------------------------------------------------------------------------------


Statistical information for the repository '8398fb12f12ebb25912d9246' was
gathered on 2021/01/11.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2951 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02951/joss.02951/10.21105.joss.02951.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02951/joss.02951/10.21105.joss.02951.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@markheckmann I've flagged this submission for additional scope review by our editorial board. In particular we will review if it is considered to have [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This is standard for submissions of this size (the core functionality appears to be captured by around 1661 lines of code).  This review will take about a week. 

In the mean time, can you please review our documentation on [what the paper should contain](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), in particular the "Statement of need" section is missing. You can update the paper here by calling: `@whedon generate pdf`. Thanks.

**Comment by kthyng** [comment]
Hi @markheckmann — the editorial board has determined that this submission is in scope, so we can proceed.

Please follow up on @Kevin-Mattheus-Moerman's comment above to add a Statement of Need section.

Also, add a sentence or two to the start of your paper so that a non-expert in your field can be oriented to where your software fits.

**Comment by kthyng** [comment]
@markheckmann As someone who isn't in your field (and referring to my previous comment about your paper needing to help orient nonexperts to your topic area), I can't tell who is an appropriate editor for this submission, given that cMadan isn't able to take an another submission right now. Can you look through the editor list and suggest another editor or two?

**Comment by markheckmann** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02951/joss.02951/10.21105.joss.02951.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02951/joss.02951/10.21105.joss.02951.pdf) :page_facing_up: :point_left:

**Comment by markheckmann** [comment]
@kthyng We added a 'Statement of need' section and modified the introduction to make it more accessible for non-experts.
We suggest one of the following editors who have a background in social science: alexhanna, kakiac, leeper, lorenanicole
Thanks!

**Comment by kthyng** [comment]
@kakiac are you available to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @kakiac as editor

**Comment by whedon** [comment]
@kakiac has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hello @kakiac, just a gentle ping on this editorial request.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @kakiac as editor

**Comment by whedon** [comment]
@kakiac has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@kakiac would you be able to help with this submission?

**Comment by kthyng** [comment]
Hi @lorenanicole could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @lorenanicole as editor

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by lorenanicole** [comment]
@kthyng I have another few papers on my roster and don't want to overextend myself.

**Comment by kthyng** [comment]
Hi @markheckmann and thanks for your submission! We currently have low editor availability in this area, so I am going to add the "waitlist" label until we are able to assign this submission to an editor. Thanks for your patience.

**Comment by danielskatz** [comment]
👋 @cMadan - are you able to take this on by any chance?

**Comment by danielskatz** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by cMadan** [comment]
Apologies, I can't handle another submission at this time.

**Comment by kyleniemeyer** [comment]
@whedon invite @gkthiruvathukal as editor

Hi @gkthiruvathukal, I realize you just wrapped up a submission, but we are trying to trim the backlog... can you edit this submission?

**Comment by whedon** [comment]
@gkthiruvathukal has been invited to edit this submission.

**Comment by gkthiruvathukal** [comment]
Hi @kyleniemeyer. Yes, I can edit it.

**Comment by kyleniemeyer** [comment]
@whedon assign @gkthiruvathukal as editor

Thank you!

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@markheckmann if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by markheckmann** [comment]
@gkthiruvathukal Thanks for the info! Based on the information on the list, I would suggest on of the following four persons: adithirgis, elimillera, aj2duncan, brunaw 
Thanks and best wishes, Mark

**Comment by gkthiruvathukal** [comment]
@aj2duncan, are you willing to contribute a review for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@brunaw, are you willing to contribute a review for this JOSS submission?

**Comment by aj2duncan** [comment]
Hi @gkthiruvathukal,

This looks really interesting and thank you very much for the offer but I'm not going to be able to contribute for a couple of weeks. If you're happy to wait, I'll gladly look at it then but otherwise I'll have to pass. 

Thanks,

Andrew

**Comment by markheckmann** [comment]
@aj2duncan Dear Andrew, thanks for your offer. We are happy to wait for a couple of weeks. We would be very glad if you were willing to do it then. Thanks, Mark

**Comment by gkthiruvathukal** [comment]
@aj2duncan I hope I can interpret your response as a yes. Both the author, @markheckmann, and I are willing to work with your timeframe.  We're still very much in a COVID-19 world, so we will wait for your review. Thank you for your willingness to participate in this important process.

**Comment by gkthiruvathukal** [comment]
@whedon assign @aj2duncan as reviewer

**Comment by whedon** [comment]
OK, @aj2duncan is now a reviewer

**Comment by gkthiruvathukal** [comment]
We'll start review once I get the second reviewer, again with the understanding that this will take some time.

**Comment by brunaw** [comment]
@gkthiruvathukal thanks for the invite. I am in the same situation as @aj2duncan, I am happy to review but it might take me a few days to start, would that be okay?

**Comment by gkthiruvathukal** [comment]
@brunaw Yes, it's absolutely ok! I will work with your schedule. I will just nudge both of you in a couple of weeks to see how things are going. Ok?

I'll add you and start review! Thanks so much for being willing to help.

**Comment by gkthiruvathukal** [comment]
@whedon add @brunaw as reviewer

**Comment by whedon** [comment]
OK, @brunaw is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3292.
