### ISSUE TITLE
[PRE REVIEW]: splithalf: robust estimates of split half reliability

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2953]
**Submitting author:** @sdparsons (<a href="http://orcid.org/0000-0002-7048-4093">Sam Parsons</a>)
**Repository:** <a href="https://github.com/sdparsons/splithalf/" target ="_blank">https://github.com/sdparsons/splithalf/</a>
**Version:** 0.7.2
**Editor:** @oliviaguest
**Reviewers:** @jpsnijder, @Nathaniel-Haines, @rMassimiliano
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sdparsons. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @cMadan.

@sdparsons if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (305.4 files/s, 56721.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                8            354            280           1366
Markdown                         4            203              0            598
TeX                              2             18              0            294
Rmd                              2            176            210            131
C++                              2             11              4             25
YAML                             1              1              4             18
C                                1              4              4             14
-------------------------------------------------------------------------------
SUM:                            20            767            502           2446
-------------------------------------------------------------------------------


Statistical information for the repository '40d99799f8f83c82ddbec214' was
gathered on 2021/01/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Sam Parsons                      2            80             10           86.54
sdparsons                        1             3             11           13.46

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
sdparsons                    62         2066.7          0.4               12.90
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02953/joss.02953/10.21105.joss.02953.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02953/joss.02953/10.21105.joss.02953.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.12688/wellcomeopenres.15191.1 is OK
- 10.31234/osf.io/y6tcz is OK
- 10.2307/1412159 is OK
- 10.3758/s13428-017-0935-1 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1177/2515245919879695 is INVALID because of 'https://doi.org/' prefix
```

**Comment by sdparsons** [comment]
I have corrected the DOI issue in the .bib file and checked the generated pdf.

**Comment by sdparsons** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02953/joss.02953/10.21105.joss.02953.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02953/joss.02953/10.21105.joss.02953.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@sdparsons I've flagged this submission for additional scope review by our editorial board. In particular we will review if it is considered to have [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This is standard for submissions of this size (the core functionality appears to be captured by around 1366 lines of code).  This review will take about a week.

**Comment by sdparsons** [comment]
@Kevin-Mattheus-Moerman thank you for the update. If there is anything I can do to support the process, or any information I can provide (e.g. other's use of the software), I am more than happy to help.

**Comment by kthyng** [comment]
@sdparsons Ok we can proceed with this review.

**Comment by kthyng** [comment]
@oliviaguest would you be up for editing this submission?

**Comment by kthyng** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
@kthyng sure, no problem.

@sdparsons can you drop some names of potential reviewers, please?

**Comment by sdparsons** [comment]
@oliviaguest happy to. Is it ok to post them here as well as email addresses, or better to message separately?

**Comment by kthyng** [comment]
@oliviaguest Thank you!!

**Comment by oliviaguest** [comment]
@sdparsons here is fine (thank you!) as long as you don't tag their username on GitHub with an @.

**Comment by sdparsons** [comment]
Great! I've gathered the details for five potential reviewers and also noted relevant expertise. I hope this helps, and I can think of more people if needed too.

James Bartlett (bartle16@uni.coventry.ac.uk) – has used the package before (I’m not sure if this constitutes a COI for JOSS – though I will note that we have worked together on a separate project before also) and also done work with task reliability. 
Shelly Cooper (shelly.cooper@wustl.edu) – has worked on task reliability and implementing splithalf-reliability estimation procedures
Jean-Paul Snijder (jean-paul.snijder@cgu.edu) – has worked on reliability issues and used similar methods as implemented in the package
Donald Williams (drrwilliams@ucdavis.edu) - Recently published in JOSS and has a good record in psychometrics
Julia Haaf (j.m.haaf@uva.nl) strong psychometrician and R expertise

**Comment by oliviaguest** [comment]
@sdparsons fabulous! Ta!

**Comment by oliviaguest** [comment]
@whedon add @jpsnijder as reviewer

**Comment by whedon** [comment]
OK, @jpsnijder is now a reviewer

**Comment by oliviaguest** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02953/joss.02953/10.21105.joss.02953.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02953/joss.02953/10.21105.joss.02953.pdf) :page_facing_up: :point_left:

**Comment by oliviaguest** [comment]
@whedon add @Nathaniel-Haines as reviewer

**Comment by whedon** [comment]
OK, @Nathaniel-Haines is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @rMassimiliano as reviewer

**Comment by whedon** [comment]
OK, @rMassimiliano is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3041.

**Comment by oliviaguest** [comment]
Hi All! @sdparsons, @jpsnijder, @Nathaniel-Haines, @rMassimiliano please head on over to #3041! 🥳
