### ISSUE TITLE
[PRE REVIEW]: Drug Ontology Parsing Engine (DOPE): An R Package for Querying of a Comprehensive Ontology of Substances of Abuse

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2955]
**Submitting author:** @labouz (<a href="http://orcid.org/0000-0002-6616-0950">Layla Bouzoubaa</a>)
**Repository:** <a href="https://github.com/CTN-0094/DOPE" target ="_blank">https://github.com/CTN-0094/DOPE</a>
**Version:** v1.0.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @labouz. **Currently, there isn't an JOSS editor assigned** to your paper.

@labouz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.24 s (244.7 files/s, 32455.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            23           1016            258           3613
Rmd                              8            258            422            562
CSS                              3             99             48            428
R                               14             79            192            317
JavaScript                       4             65             35            267
Markdown                         4             41              0             84
YAML                             2              3              0             25
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            59           1561            956           5307
-------------------------------------------------------------------------------


Statistical information for the repository '370517ec2fcb3ee52c63f87b' was
gathered on 2021/01/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Layla Bouzoubaa                  3           884            442          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Layla Bouzoubaa             442           50.0          0.0               11.31
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2955 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02955/joss.02955/10.21105.joss.02955.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02955/joss.02955/10.21105.joss.02955.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@labouz I've flagged this submission for additional scope review by our editorial board. In particular we will review if it is considered to have [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This is standard for submissions of this size.  This review will take about a week.

**Comment by labouz** [comment]
@Kevin-Mattheus-Moerman Thank you. In the form I suggested en editor on the submission form but just in case, I'm looking at elimillera or kanekalla or nanhung or praveenkumarpgiindia

**Comment by RaymondBalise** [comment]
@Kevin-Mattheus-Moerman. Thank you for the update Kevin.  Because we developed this in a private repo, we were/are concerned about the "effort" criteria.  If it matters, we can share some of the history of the repos which went into this.  They have around 100 commits, over many months, made by the full team of 4 PhDs and 3 MS level statisticians/programmers.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @labouz @RaymondBalise for the additional clarification. The "scholarly effort" mostly relates to the functionality contained within the code. Our editorial board will review this and make a judgement on this. They will review the repository and the paper but if you want to expand here on the functionality the code covers you are welcome to do so.

**Comment by RaymondBalise** [comment]
@Kevin-Mattheus-Moerman Sounds good.  Thank you for the note.

**Comment by kthyng** [comment]
Hi @labouz and @RaymondBalise and thanks for your submission. Unfortunately the editorial board did decide that this submission does not meet our bar for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). In this case, it wasn't the time frame in your commit history but the ultimate size of the functionality. As an alternative to JOSS, you might consider publishing the software to Zenodo to get a DOI that users can cite.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
