### ISSUE TITLE
[PRE REVIEW]: tinselR – An RShiny Application for Annotating Outbreak Trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2956]
**Submitting author:** @jennahamlin (<a href="http://orcid.org/0000-0001-7037-134X">Jennafer Hamlin</a>)
**Repository:** <a href="https://github.com/jennahamlin/tinselR.git" target ="_blank">https://github.com/jennahamlin/tinselR.git</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jennahamlin. **Currently, there isn't an JOSS editor assigned** to your paper.

@jennahamlin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.85 s (66.9 files/s, 4215.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               38            319           1218           1527
Markdown                         7             60              0            165
YAML                             2             11             14             51
Rmd                              1             41            163             16
SVG                              8              0              0              8
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            57            431           1395           1768
-------------------------------------------------------------------------------


Statistical information for the repository '57420f32f371e9a3fbe2ebb9' was
gathered on 2021/01/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
jennahamlin                      2          3460           3460          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2956 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch manuscript

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch manuscript. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02956/joss.02956/10.21105.joss.02956.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02956/joss.02956/10.21105.joss.02956.pdf) :page_facing_up: :point_left:

**Comment by jennahamlin** [comment]
Hello -

Here are my suggestions for potential reviewers:

**Those familiar with R shiny**
* aj2duncan
* adithirgis
* elimillera
* brunaw


**Those familiar with R and phylogenetics**

* giraola
* shaunpwilkinson
* gavinmdouglas
* iimog
* *vbaliga
* rachelss
* Gab0
* tkchafin
* richelbilderbeek

**Comment by jennahamlin** [comment]
@whedon generate pdf from branch manuscript

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch manuscript. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02956/joss.02956/10.21105.joss.02956.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02956/joss.02956/10.21105.joss.02956.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@jennahamlin thanks for updating the paper. Just to let you know, I have flagged this submission for additional scope review by our editorial board which is standard for submissions of this size. In particular we will review if it contains ["substantial scholarly effort"](https://joss.readthedocs.io/en/latest/review_criteria.html#substantial-scholarly-effort) given that the core functionality is ~1527 lines of code. The second reason I triggered the scope review relates to as our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements), in particular whether this work has a clear/substantial research application. This submission, to me, at first sight, appears to be a visualization package which perhaps does not in itself influence research outcomes. Perhaps you could comment on how this software is directly important to research and clarify this. You can do this here and also distill it in a dedicated "Statement of need" section in the paper. After reading this section it should be clear that this work is significant enough to research outcomes that one would feel the need to cite this library when used in research (this is what typically distinguishes a "utility tool", typically not cited, from research software, which is cited). Let me know if you have any questions. You'll hear back from us in about a week.

**Comment by jennahamlin** [comment]
@Kevin-Mattheus-Moerman Thank you for letting me know. My goal is to update and include the 'Statement of Need' both here and in the manuscript by Wednesday of this week.

**Comment by jennahamlin** [comment]
@Kevin-Mattheus-Moerman - We are still crafting the statement of need. Apologies for not having it available by yesterday but know that we are working on this. Once available, I will post it here.

**Comment by jennahamlin** [comment]
Below I provide the statement of need and update the manuscript to also include the statement. 

**Statement of Need**

Public health genomic surveillance is a young and rapidly evolving field that exists at the intersection of genomics and epidemiology. Phylogenetic trees showing ​bacterial isolates' relatedness with annotated epidemiologic data are critical for identifying potential outbreaks. Neither the genetic nor the epidemiological data alone are sufficient, and no other type of analysis can replace it. In addition to the routine use of this software for outbreak investigation, ​it will play a critical role in establishing new genetic subtyping schemes. The applied research to develop new typing schemes for identifying isolates belonging to outbreak clusters remains reliant upon the manual review of many trees containing large numbers of isolates from well described historical outbreak. For many organisms, no a priori genomic relatedness threshold exists, and the examination of trees is the only way to establish a hypothesis for validation. Tinselr is both a visualization tool and an analysis package, and its user-friendly interface is uniquely suited to the needs of public health genomic surveillance.

**Comment by jennahamlin** [comment]
@whedon generate pdf from branch manuscript

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch manuscript. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02956/joss.02956/10.21105.joss.02956.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02956/joss.02956/10.21105.joss.02956.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@jennahamlin  - thanks for your submission. Your changes make it clear that there is a research software component, but unfortunately, the editors have decided that the research software aspect of it is too small for us to review. A large portion of the code is in-app documentation and layout specification.

Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

Or if this is expanded to include additional functionality and scope, please feel free to resubmit it to JOSS (and link to this issue at that time).

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
