### ISSUE TITLE
[PRE REVIEW]: The targets R package: a dynamic Make-like function-oriented pipeline toolkit for reproducibility and high-performance computing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2958]
**Submitting author:** @wlandau (<a href="http://orcid.org/0000-0003-1878-3253">William Landau</a>)
**Repository:** <a href="https://github.com/ropensci/targets" target ="_blank">https://github.com/ropensci/targets</a>
**Version:** 0.0.1
**Editor:** @arfon
**Reviewers:** @arfon
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @wlandau. **Currently, there isn't an JOSS editor assigned** to your paper.

@wlandau if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.29 s (247.0 files/s, 20229.3 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
R                               295           1572           2447          19638
SVG                               2              0              0            764
JSON                              1              0              0            511
Markdown                         12            127              0            424
YAML                              4             32              0            249
TeX                               1             14              0            108
Rmd                               2             54             90              9
Bourne Again Shell                1              0              5              4
--------------------------------------------------------------------------------
SUM:                            318           1799           2542          21707
--------------------------------------------------------------------------------


Statistical information for the repository '01655ea691b9a529f338d1ff' was
gathered on 2021/01/15.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02958/joss.02958/10.21105.joss.02958.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02958/joss.02958/10.21105.joss.02958.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00550 is OK
- 10.21105/joss.01686 is OK
- 10.1093/bioinformatics/btz284 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, @arfon is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2959.

**Comment by arfon** [comment]
Moving this through a fast-track review as this was reviewed in https://github.com/ropensci/software-review/issues/401
