### ISSUE TITLE
[REVIEW]: kerasR: R Interface to the Keras Deep Learning Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#296]
**Submitting author:** @statsmaths (<a href="http://orcid.org/0000-0003-0576-0669">Taylor Arnold</a>)
**Repository:** <a href="https://github.com/statsmaths/kerasR" target ="_blank">https://github.com/statsmaths/kerasR</a>
**Version:** 0.6.1
**Editor:** @karthik
**Reviewer:** @kaneplusplus
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.814996" target="_blank">10.5281/zenodo.814996</a>

## Status

[![status](http://joss.theoj.org/papers/c83b6694f1192e920aa86912bd08919c/status.svg)](http://joss.theoj.org/papers/c83b6694f1192e920aa86912bd08919c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c83b6694f1192e920aa86912bd08919c"><img src="http://joss.theoj.org/papers/c83b6694f1192e920aa86912bd08919c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c83b6694f1192e920aa86912bd08919c/status.svg)](http://joss.theoj.org/papers/c83b6694f1192e920aa86912bd08919c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/statsmaths/kerasR" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/statsmaths/kerasR">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.6.1)?
- [x] **Authorship:** Has the submitting author (@statsmaths) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kaneplusplus it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by kaneplusplus** [comment]
This is a package I have begun using when applying deep learning models. This interface mirrors Python's making it very easy to transition between the two languages. Constructing a model, fitting it, and predicting is easy. The examples in the documentation were helpful and I liked that the vignette includes references for other deep learning resources.

The package should be accepted. While going through the code and documentation, I came up with the following three suggestions.

- (suggestion) The installation assumes that keras is installed and configured for python. Is it worth pointing to installation instructions or adding the `pip install` commands that can be used to set this up? This would include installing `pydot` for visualization. 
- (suggestion) There is code output in [the vignette](https://github.com/statsmaths/kerasR/blob/master/vignettes/introduction.Rmd) that simply reads `output`. Should this be removed?
- (suggestion) The code coverage is slightly low. Will this be increased in the coming weeks?

**Comment by statsmaths** [comment]
@kaneplusplus Thank you very much for reviewing this submission and your very helpful feedback. I just pushed version 0.7.0 to GitHub, which I believe implements your three suggestions. Namely:

- The package now gives an explicit warning message whenever any keras-related function is called if the keras package is not available. Details instructions for using pip to install the requirements are now given. I've also made it so that there is an explicit printing of the python path being used by reticulate.
- I removed the erroneous `output` line in the vignette and README file.
- Due to an oversight on my part, many of the test files were not pushed to the repository. These are now online. Because CRAN does not have the Python keras module, and some of the tests take a while to run, there are `skip_on_cran()` calls in the testing suite, so you need to set the `export NOT_CRAN='true'` if you want to run these locally. The current coverage is now at 76%.

Please let me know if you have any further questions or suggestions.

**Comment by kaneplusplus** [comment]
This is great. I have no other issues or suggestions.

**Comment by karthik** [comment]
@kaneplusplus Thank you very much for the review. We really appreciate it.

@statsmaths Could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by statsmaths** [comment]
@karthik Thanks. I archived the current version of the software to Zenodo with this DOI: 10.5281/zenodo.814996

**Comment by karthik** [comment]
@whedon set 10.5281/zenodo.814996 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.814996" target="_blank">10.5281/zenodo.814996</a> is the archive.

**Comment by arfon** [comment]
@kaneplusplus many thanks for your review here and to @karthik for editing this one :sparkles:

@statsmaths - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00296 :zap: 🚀:boom:
