### ISSUE TITLE
[PRE REVIEW]: ADratio: Probabilistic classification of sex-linked scaffolds from pileup data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2960]
**Submitting author:** @tkchafin (<a href="http://orcid.org/0000-0001-8687-5905">Tyler Chafin</a>)
**Repository:** <a href="https://github.com/tkchafin/ADratio" target ="_blank">https://github.com/tkchafin/ADratio</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tkchafin. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @fboehm.

@tkchafin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.22 s (27.6 files/s, 6913.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           3             78            213            567
Markdown                         2            108              0            359
TeX                              1              0              0            177
-------------------------------------------------------------------------------
SUM:                             6            186            213           1103
-------------------------------------------------------------------------------


Statistical information for the repository '51b478a3bc9d943a72502fb0' was
gathered on 2021/01/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Tyler Chafin                    20           997            139          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Tyler Chafin                858           86.1          0.3               13.75
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/aps3.1247 is OK
- 10.1111/jpy.13088 is OK
- 10.1111/mec.14540 is OK
- 10.1111/mec.14562 is OK
- 10.1111/1755-0998.12237 is OK
- 10.1093/gbe/evw172 is OK
- 10.1093/gbe/evv103 is OK
- 10.1186/1471-2164-14-273 is OK
- 10.1186/1471-2164-13-183 is OK
- 10.1371/journal.pbio.1002078 is OK
- 10.1093/bioinformatics/btq033 is OK
- 10.1093/bioinformatics/btp352 is OK
- 10.1093/bioinformatics/btp324 is OK
- 10.1093/bioinformatics/btu170 is OK

MISSING DOIs

- 10.1007/s10994-005-4258-6 may be a valid DOI for title: Not so naive Bayes: Aggregating one‐dependence estimators

INVALID DOIs

- 10.1016/j.tig.2017.01.008Get is INVALID
- 110.1186/s12864-018-4945-x is INVALID
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02960/joss.02960/10.21105.joss.02960.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02960/joss.02960/10.21105.joss.02960.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope 

@tkchafin – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by tkchafin** [comment]
@whedon generate pdf

**Comment by tkchafin** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02960/joss.02960/10.21105.joss.02960.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02960/joss.02960/10.21105.joss.02960.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @tkchafin and thanks for your submission. Unfortunately, the editorial board determined that it is too small to pass our bar for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). If you continue development, you could submit this work again in the future for consideration. Alternatively, there are other pathways to get a DOI for your software that you could [consider](https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages).

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
