### ISSUE TITLE
[PRE REVIEW]: GNSS2CHORDS: A new tool for connecting UNAVCO Real-Time GNSS Data Services to CHORDS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2961]
**Submitting author:** @joshj55 (<a href="http://orcid.org/0000-0002-6078-4287">Joshua Jones</a>)
**Repository:** <a href="https://github.com/joshj55/GNSS2CHORDS" target ="_blank">https://github.com/joshj55/GNSS2CHORDS</a>
**Version:** v2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @joshj55. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kbarnhart.

@joshj55 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.27 s (26.3 files/s, 3339.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           3             87            111            459
Markdown                         2             30              0            110
TeX                              1             10              0             71
JSON                             1              0              0             11
-------------------------------------------------------------------------------
SUM:                             7            127            111            651
-------------------------------------------------------------------------------


Statistical information for the repository 'e6b0be54a0ea718745e39301' was
gathered on 2021/01/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
joshj55                          3           661              4          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
joshj55                     657           99.4          0.0               12.33
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02961/joss.02961/10.21105.joss.02961.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02961/joss.02961/10.21105.joss.02961.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@joshj55 – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- doi.org/10.5065/d6p849bm is OK

MISSING DOIs

- 10.1109/igarss.2017.8128006 may be a valid DOI for title: Integration of real-time weather radar data and Internet of Things with cloud-hosted real-time data services for the geosciences (CHORDS)
- 10.1785/0220190269 may be a valid DOI for title: Evaluation of Earthquake Magnitude Estimation and Event Detection Thresholds for Real-Time GNSS Networks: Examples from Recent Events Captured by the Network of the Americas

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @joshj55 and thanks for your submission. Unfortunately, the editorial board has determined that while your software looks useful, it also seems to be more in a beta version rather than ready for publication. Additionally, it is too small in its current form to pass our bar for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
