### ISSUE TITLE
[REVIEW]: registr 2.0: Incomplete Curve Registration for Exponential Family Functional Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2964]
**Submitting author:** @bauer-alex (<a href="http://orcid.org/0000-0003-3495-5131">Alexander Bauer</a>)
**Repository:** <a href="https://github.com/julia-wrobel/registr" target ="_blank">https://github.com/julia-wrobel/registr</a>
**Version:** v2.1.0
**Editor:** @mbobra
**Reviewers:** @qpmnguyen, @g4brielvs
**Archive:** <a href="https://doi.org/10.5281/zenodo.4734283" target="_blank">10.5281/zenodo.4734283</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/097327a2d4737bed50e2d39e206881cd/status.svg)](https://joss.theoj.org/papers/097327a2d4737bed50e2d39e206881cd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/097327a2d4737bed50e2d39e206881cd"><img src="https://joss.theoj.org/papers/097327a2d4737bed50e2d39e206881cd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/097327a2d4737bed50e2d39e206881cd/status.svg)](https://joss.theoj.org/papers/097327a2d4737bed50e2d39e206881cd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/julia-wrobel/registr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@g4brielvs & @qpmnguyen, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/julia-wrobel/registr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@bauer-alex) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/julia-wrobel/registr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@bauer-alex) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @munkm, @qpmnguyen it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.csda.2016.07.010 is OK
- 10.21105/joss.00557 is OK
- 10.1111/biom.12963 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: :point_left:

**Comment by mbobra** [comment]
👋  @munkm @qpmnguyen Thank you so much for agreeing to review this submission! 

Here's what you need:
* Here is the software repository: https://github.com/julia-wrobel/registr
* The paper describing the software is linked in Whedon's comment above ⬆️ 
* Here is a detailed description of the review criteria: https://joss.readthedocs.io/en/latest/review_criteria.html#review-items 

Please check off the tick boxes as you go through your review. This is an open review process, and we encourage communication between the reviewers, the submitting author, and the editor (myself). Please feel free to ask me any questions if you have them!

**Comment by bauer-alex** [comment]
I made a minor update of the paper, so I'm updating the pdf.

**Comment by bauer-alex** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @munkm, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @qpmnguyen, please update us on how your review is going.

**Comment by bauer-alex** [comment]
@munkm @qpmnguyen @mbobra Any update on the review?
Don't want to stress you guys. Just want to make sure that our submission isn't overlooked.

**Comment by mbobra** [comment]
Thanks for the ping, @bauer-alex! I reached out to both reviewers via e-mail. We at JOSS do give reviewers six weeks to complete their review (JOSS is operating on a reduced service mode), so the reviewers still have some time.

**Comment by bauer-alex** [comment]
@mbobra Any update on the review?
Side note: I'll generate the pdf again since we made another minor change to a formula.

**Comment by bauer-alex** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: :point_left:

**Comment by bauer-alex** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: :point_left:

**Comment by munkm** [comment]
Hi @bauer-alex! I'm reviewing this and I've set aside time over the next week to review it. Thanks for your patience!!!!

**Comment by qpmnguyen** [comment]
Hi hi! I am planning to get your review back @bauer-alex at the end of this week. Sorry for taking so long!

**Comment by bauer-alex** [comment]
All good. Thanks for the quick response!

**Comment by qpmnguyen** [comment]
Thank you very much everyone for your patience. @mbobra I have gone through the checklist and found the submission to have fulfilled all the listed requirements. I recommend acceptance for publication in JOSS. I have also filed an issue with some minor comments [here](https://github.com/julia-wrobel/registr/issues/38)

**Comment by mbobra** [comment]
Thank you, @qpmnguyen! I really appreciate your time and effort ☀️

**Comment by bauer-alex** [comment]
@whedon generate pdf

**Comment by bauer-alex** [comment]
@whedon generate pdf

**Comment by bauer-alex** [comment]
@mbobra @qpmnguyen Thanks for the valuable feedback. I now addressed all questions / final recommendations of @qpmnguyen, see [here](https://github.com/julia-wrobel/registr/issues/38). The newly generated pdf in the last comment contains the newest version of the paper.

**Comment by mbobra** [comment]
👋 @munkm Let me know if you need any help reviewing (or, if you're swamped, I'm totally happy to find another reviewer -- it is okay!). The submitting author has been waiting patiently since January 15.

**Comment by mbobra** [comment]
@whedon remove @munkm as reviewer

**Comment by whedon** [comment]
OK, @munkm is no longer a reviewer

**Comment by mbobra** [comment]
@whedon add @ g4brielvs as reviewer

**Comment by whedon** [comment]
OK, @ g4brielvs is now a reviewer

**Comment by mbobra** [comment]
@whedon add @g4brielvs as reviewer

**Comment by whedon** [comment]
OK, @g4brielvs is now a reviewer

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: :point_left:

**Comment by mbobra** [comment]
👋  @g4brielvs Thank you so much for agreeing to review this submission! 

Here's what you need:
* Here is the software repository: https://github.com/julia-wrobel/registr
* The paper describing the software is linked in Whedon's comment above ⬆️ 
* Here is a detailed description of the review criteria: https://joss.readthedocs.io/en/latest/review_criteria.html#review-items 

Please check off the tick boxes (above, in the first comment on this thread) as you go through your review. This is an open review process, and we encourage communication between the reviewers, the submitting author, and the editor (myself). Please feel free to ask me any questions if you have them!

**Comment by mbobra** [comment]
👋 @g4brielvs How is the review going? Do you need any help or do you have any questions? Please let me know -- I'm happy to help!

**Comment by g4brielvs** [comment]
@whedon generate pdf

**Comment by g4brielvs** [comment]
Thank you very much for your patience. @mbobra I have gone through the checklist and found the submission to have fulfilled all the listed requirements.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02964/joss.02964/10.21105.joss.02964.pdf) :page_facing_up: :point_left:

**Comment by mbobra** [comment]
Thank you, @g4brielvs! I really appreciate your time and effort.

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.csda.2016.07.010 is OK
- 10.21105/joss.00557 is OK
- 10.1111/biom.12963 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
👋 @bauer-alex We're almost there! Could you please cut a new release and [deposit it in Zenodo](https://guides.github.com/activities/citable-code/)? Please make sure that the author list on the Zenodo deposit matches the author list on the paper. Then I can move forward with accepting the paper!

**Comment by bauer-alex** [comment]
@mbobra Great! The Zenodo entry for the newest release can be found [here](https://zenodo.org/record/4734283).

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.4734283 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4734283" target="_blank">10.5281/zenodo.4734283</a> is the archive.

**Comment by mbobra** [comment]
@whedon set v2.1.0 as version

**Comment by whedon** [comment]
OK. v2.1.0 is the version.

**Comment by mbobra** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.csda.2016.07.010 is OK
- 10.21105/joss.00557 is OK
- 10.1111/biom.12963 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2281

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2281, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by mbobra** [comment]
@bauer-alex You finally made it! Thank you for your extraordinary patience -- I know you waited nearly half a year. I am sorry it took so long but I hope you're happy with the final result ☀️

**Comment by bauer-alex** [comment]
Nice! Happy that everything's done now.
@mbobra @qpmnguyen @g4brielvs Thanks again for all your efforts! :)

**Comment by kthyng** [comment]
Hi @bauer-alex, I'll be taking over from here! Can you change the title of your Zenodo archive so the title matches your JOSS paper? This isn't required, but it is a preference to be consistent.

**Comment by kthyng** [comment]
This is ready for publication once I hear back on that.

**Comment by bauer-alex** [comment]
@kthyng The title of our Zenodo archive is now updated.

**Comment by kthyng** [comment]
Looks good! Thank you!

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1390409508472692737) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2282
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02964](https://doi.org/10.21105/joss.02964)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @bauer-alex! Many thanks to editor @mbobra and reviewers @qpmnguyen and @g4brielvs for your time, hard work, and expertise!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02964/status.svg)](https://doi.org/10.21105/joss.02964)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02964">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02964/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02964/status.svg
   :target: https://doi.org/10.21105/joss.02964
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02964/status.svg)](https://doi.org/10.21105/joss.02964)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
