### ISSUE TITLE
[REVIEW]: lidar: A Python package for delineating nested surface depressions from digital elevation data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2965]
**Submitting author:** @giswqs (<a href="http://orcid.org/0000-0001-5437-4073">Qiusheng Wu</a>)
**Repository:** <a href="https://github.com/giswqs/lidar" target ="_blank">https://github.com/giswqs/lidar</a>
**Version:** 0.6.1
**Editor:** @kbarnhart
**Reviewers:** @laijingtao, @cheginit, @amanaster2
**Archive:** <a href="https://doi.org/10.5281/zenodo.4571011" target="_blank">10.5281/zenodo.4571011</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/005bf3e6f47840e74e71678d8e88facc/status.svg)](https://joss.theoj.org/papers/005bf3e6f47840e74e71678d8e88facc)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/005bf3e6f47840e74e71678d8e88facc"><img src="https://joss.theoj.org/papers/005bf3e6f47840e74e71678d8e88facc/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/005bf3e6f47840e74e71678d8e88facc/status.svg)](https://joss.theoj.org/papers/005bf3e6f47840e74e71678d8e88facc)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/giswqs/lidar" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@laijingtao & @cheginit & @amanaster2, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kbarnhart know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/giswqs/lidar">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@giswqs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/giswqs/lidar">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@giswqs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] ~~**Performance:** If there are any performance claims of the software, have they been confirmed?~~ (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/giswqs/lidar">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@giswqs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @laijingtao, @cheginit, @amanaster2 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.cageo.2005.11.002 is OK
- 10.1016/j.geomorph.2016.05.006 is OK
- 10.1007/s13157-015-0731-6 is OK
- 10.1080/13658816.2015.1038719 is OK
- 10.1111/1752-1688.12689 is OK
- 10.1080/13658810500433453 is OK
- 10.1080/13658816.2014.975715 is OK
- 10.1002/hyp.10648 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.7717/peerj.453 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.7287/peerj.preprints.27099v1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02965/joss.02965/10.21105.joss.02965.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02965/joss.02965/10.21105.joss.02965.pdf) :page_facing_up: :point_left:

**Comment by kbarnhart** [comment]
It looks like I accidentally unassigned the reviewers so I'm going to re-add them with whedon.

**Comment by kbarnhart** [comment]
@whedon add @laijingtao as reviewer

**Comment by whedon** [comment]
OK, @laijingtao is now a reviewer

**Comment by kbarnhart** [comment]
@whedon add @cheginit as reviewer

**Comment by whedon** [comment]
OK, @cheginit is now a reviewer

**Comment by kbarnhart** [comment]
@whedon add @amanaster2 as reviewer

**Comment by whedon** [comment]
OK, @amanaster2 is now a reviewer

**Comment by laijingtao** [comment]
Hi Katy @kbarnhart, it seems that I can't click the checkbox and my names is not listed as one of the assignees. Also, I clicked the link for accepting invitation but it said that it could find the invitation. This is my first time reviewing for joss. Could you help me figure out what could be wrong?

**Comment by kbarnhart** [comment]
@whedon re-invite @laijingtao as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@laijingtao please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by kbarnhart** [comment]
@laijingtao it should work after you click the above link. If it doesn't let me know.

**Comment by whedon** [comment]
:wave: @laijingtao, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @amanaster2, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @cheginit, please update us on how your review is going.

**Comment by kbarnhart** [comment]
@laijingtao, @amanaster2, @cheginit, we have an automatic reminder two weeks into the review. Feel free to provide an update if you have one.

**Comment by laijingtao** [comment]
I've finished my review for this repository. This package meets all the review criteria and is suitable for publication. My only suggestion is the documentation of the core methods could be improved by adding detailed description and example inputs/outputs. Other parts of the documentation are all great.

**Comment by cheginit** [comment]
I've been reviewing your submission and here are my comments so far:

1. The article reads well and states the package capabilities clearly. However, you wrote on line 6:

> lidar is a Python package for terrain and hydrological analysis using digital elevation models (DEMs).

Then on line 18 said:

> The lidar Python package implements the level-set method and makes it possible for delineating the nested hierarchy of surface depressions as well as elevated terrain features.

The first part makes the scope of applicability of the package very broad, terrain and hydrological analysis, and then second part says that the package mainly implements level-set method for delineating depressions. So I think you need to make the scope of applicability more clear in the summary part similar to the "Statement of Need" section where you correctly state that the package does some terrain analysis which can be used with other hydrology analysis tools.

2. Regarding the tests, I ran `coverage` and here is the result:

```bash
$ coverage run --source lidar -m unittest discover tests/
$ coverage report -m
Name                 Stmts   Miss  Cover   Missing
--------------------------------------------------
lidar/__init__.py        9      0   100%
lidar/cli.py             9      3    67%   11-13
lidar/example.py        29     29     0%   1-48
lidar/filling.py       151     12    92%   119, 274, 356-376
lidar/filtering.py      85     36    58%   54-56, 84-86, 114-116, 125-175
lidar/gui.py            62     50    19%   15-165, 169, 173, 177
lidar/lidar.py           1      1     0%   3
lidar/mounts.py         55     20    64%   54, 72, 102-133
lidar/slicing.py       375     49    87%   211-216, 262-287, 320, 363, 494-497, 598, 600, 705-722
--------------------------------------------------
TOTAL                  776    200    74%
```

Though not necessary, my suggestion is to add a coverage badge and try to increase the coverage percentage to around 90% at least.

3. I am not sure about the journal's policies regarding code quality, @kbarnhart, but, in my opinion, the code needs some polishing. Some files have `if-main` as well as commented out lines of code which shouldn't be in the published version of a code. If these kind of things matter, I can provide a more detailed list of things that needs to be addressed.
4. Regarding the documentation, I think the usage section is lacking. The `lidar` section is essentially a duplicate of all the other sections. The history section is empty as well.

**Comment by kbarnhart** [comment]
@cheginit thanks for these thoughtful comments. @giswqs when you respond to them, please paste them into an in-repo issue and comment there. Include a link to this repo by including the text openjournals/joss-reviews/issues/2965. This keeps only the top-level discussion on this thread, and more detailed discussion on in-repo issue threads and links those issues with this one. 

I broadly agree with @cheginit 's comments and will expand a bit on items 2 and 3. If further clarification from me is useful on any of these issues, just tag me here or in the in-repo issue. 

2. My only addition regarding tests is to emphasize the distinction between tests of interface (e.g., if the right format input is provided, can it run without errors) and tests that verify the algorithms are behaving as expecting). My experience is that it is not too hard to create 100% code coverage that is just a test of the interface but much harder to reach a lower coverage level with algorithm verification. Both types of tests are important and having tests that verify the algorithms are implemented correctly are critical.
 
3. JOSS doesn't have any explicit statements about code quality. However, we do expect 

    > In addition, JOSS requires that software should be feature-complete (i.e. no half-baked solutions) and designed for maintainable extension (not one-off modifications of existing tools). “Minor utility” packages, including “thin” API clients, and single-function packages are not acceptable.

    To that end, a user shouldn't be expected to modify the source code in order to use it to its full level of functionality. E.g., modifying the `if-main` block to use a different parameter value or input file. I don't think `if-main` blocks are inherently problematic, but if they exist, a user shouldn't need to edit the code in order to use them. And they should be documented.

**Comment by giswqs** [comment]
@kbarnhart @cheginit @laijingtao Thank you all for your very helpful comments. I have opened an [issue](https://github.com/giswqs/lidar/issues/10) on the lidar repo. I will keep you posted on this thread once I resolve all the comments. Thanks.

**Comment by kbarnhart** [comment]
@giswqs thanks for the update and for linking it to this issue 🎉 . If you have questions for me at any point in this process, please don't hesitate to ask.

**Comment by amanaster2** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2965 with the following error:

**Comment by giswqs** [comment]
Not sure why it fails to compile. I just tested it using [https://whedon.theoj.org](https://whedon.theoj.org) and it complied just fine.

**Comment by giswqs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02965/joss.02965/10.21105.joss.02965.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02965/joss.02965/10.21105.joss.02965.pdf) :page_facing_up: :point_left:

**Comment by giswqs** [comment]
I have re-built the documentation using mkdocs. Here is the new link (https://lidar.gishub.org). I am still updating the content. The [lidar.reathedocs.io](https://lidar.readthedocs.io/) is no longer being updated. Thanks.

**Comment by cheginit** [comment]
@giswqs Thanks for taking the time and addressing the issues that I raised. @kbarnhart, in my opinion, the package meets all the criteria.

@giswqs As a side note, I would suggest you to take a look at [pre-commit](https://pre-commit.com/). It's a fantastic tool that can help with checking the quality of your code. It can automate many of the tasks, here's an example config file that I use for my package: https://github.com/cheginit/hydrodata/blob/master/.pre-commit-config.yaml

**Comment by giswqs** [comment]
@cheginit Many thanks for your recommendation of [pre-commit](https://pre-commit.com/). It seems a very useful tool. I will start using it in my projects.

**Comment by kbarnhart** [comment]
@laijingtao and @cheginit thanks much for your thoughtful reviews and thanks to @giswqs for addressing their issues so expediently, this often makes the effort of subsequent reviewers much more straightforward. 

@amanaster2 thank you for being the reviewer with the Arc license. As you are able, feel free to update me on the progress of the review here.

**Comment by amanaster2** [comment]
@kbarnhart Will do! I've really only scratched the surface so far. Apologies for the delay... Planning to dig into this further this weekend 😄

**Comment by kbarnhart** [comment]
@amanaster2 no worries. We are only 4 weeks into the preferred 6 week window. Thanks again for contributing a review, and for testing the ArcGIS components of this submission.

**Comment by giswqs** [comment]
@amanaster2 I will make a video tutorial for using the ArcGIS toolbox. Hopefully, it will make your review much easier. Thanks.

**Comment by amanaster2** [comment]
@kbarnhart Absolutely---happy to do it!

@giswqs That will be excellent. Thank you!

**Comment by giswqs** [comment]
@amanaster2 I just posted the first video tutorial for using the ArcGIS toolbox. More to come. 

https://lidar.gishub.org/get-started/#arcgis-toolbox

**Comment by giswqs** [comment]
@amanaster2 I just posted another video tutorial for using the toolbox with ArcGIS Pro. Hope it will make it easier for you to test the toolbox. Let me know if you have any questions. Thanks. 

https://lidar.gishub.org/get-started/#arcgis-toolbox

**Comment by amanaster2** [comment]
Hello @kbarnhart, @giswqs:

I've finished my review. Overall, this is a great piece of software, and I really enjoyed learning how to use it.
I have a few comments/suggestions:

1.  **Documentation**: The installation instructions could use clarification. Please see my comment on this [issue](https://github.com/giswqs/lidar/issues/10) for more details.
2. **Documentation**: Suggest providing information about the ArcGIS toolbox in the [lidar repository](https://github.com/giswqs/lidar). I wouldn't have known there was an ArcGIS toolbox at first glance had @kbarnhart not told me. The tutorials you provided were excellent, and the toolbox works great!
3.  **Paper**: A little more information regarding the state of the field would be ideal. Are there other software packages that are comparable?
4. **Paper**:  Update the paper such that the readthedocs isn't listed under Help Documentation and instead list the [gishub](https://lidar.gishub.org/) page.

Please let me know if you have any questions about any of my comments.
Otherwise, this software meets all review criteria, and I would be happy to see it published!

**Comment by giswqs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02965/joss.02965/10.21105.joss.02965.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02965/joss.02965/10.21105.joss.02965.pdf) :page_facing_up: :point_left:

**Comment by giswqs** [comment]
@amanaster2 Thank you very much for taking the time to review the software and providing feedback. I have updated the repo according to your comments. Thanks. 

1. Improved the installation instructions. See https://lidar.gishub.org/installation
2. Added the ArcGIS toolbox info. See https://lidar.gishub.org/get-started/#arcgis-toolbox
3. Added a `State of the field` section to the paper. See the [article proof.](https://github.com/openjournals/joss-papers/blob/joss.02965/joss.02965/10.21105.joss.02965.pdf) 
4. Updated the `Help Documentation` of the paper. See the [article proof.](https://github.com/openjournals/joss-papers/blob/joss.02965/joss.02965/10.21105.joss.02965.pdf) 

@kbarnhart Please note that I changed the paper title to **lidar: A Python package for delineating nested surface depressions from digital elevation data** based on cheginit's comments.

**Comment by kbarnhart** [comment]
@giswqs thanks for making changes in response to all of the reviewer's comments. 

@laijingtao @cheginit @amanaster2 - if @giswqs has addressed all of your concerns and you think that this submission is ready to be accepted, could you please indicate so here. If not, please let me know what else needs to be addressed. 

@giswqs , after all reviewer's have recommended the submission be accepted, there are a couple of steps I complete (e.g., copyediting) before we move to the final steps of the JOSS process.

**Comment by cheginit** [comment]
@kbarnhart All my concerns have been addressed.

**Comment by amanaster2** [comment]
@kbarnhart All of my concerns have been addressed. This submission is ready to be accepted! 

Thank you for your work, @giswqs.

**Comment by laijingtao** [comment]
@kbarnhart All my concerns have been addressed

**Comment by kbarnhart** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.cageo.2005.11.002 is OK
- 10.1016/j.geomorph.2016.05.006 is OK
- 10.1007/s13157-015-0731-6 is OK
- 10.1080/13658816.2015.1038719 is OK
- 10.1111/1752-1688.12689 is OK
- 10.1080/13658810500433453 is OK
- 10.1080/13658816.2014.975715 is OK
- 10.1002/hyp.10648 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.7717/peerj.453 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.7287/peerj.preprints.27099v1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02965/joss.02965/10.21105.joss.02965.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02965/joss.02965/10.21105.joss.02965.pdf) :page_facing_up: :point_left:

**Comment by kbarnhart** [comment]
@giswqs please fix the .bib file so John B Lindsay and J B Lindsay are not disambiguated. This occurs when the author names are different. If you make all of them "Lindsay, J B" it should fix it. 

Once you have made that fix and verified that it builds correctly as a PDF, please do the following:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by giswqs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02965/joss.02965/10.21105.joss.02965.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02965/joss.02965/10.21105.joss.02965.pdf) :page_facing_up: :point_left:

**Comment by giswqs** [comment]
@kbarnhart I have fixed the paper.bib file. See the [article proof](https://github.com/openjournals/joss-papers/blob/joss.02965/joss.02965/10.21105.joss.02965.pdf). Thanks. 

- Tagged version: [v0.6.1](https://github.com/giswqs/lidar/releases/tag/v0.6.1)
- Zenodo link: https://doi.org/10.5281/zenodo.4571011
- DOI: 10.5281/zenodo.4571011

**Comment by kbarnhart** [comment]
@whedon set 0.6.1 as version

**Comment by whedon** [comment]
OK. 0.6.1 is the version.

**Comment by kbarnhart** [comment]
@whedon set 10.5281/zenodo.4571011 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4571011" target="_blank">10.5281/zenodo.4571011</a> is the archive.

**Comment by kbarnhart** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.cageo.2005.11.002 is OK
- 10.1016/j.geomorph.2016.05.006 is OK
- 10.1007/s13157-015-0731-6 is OK
- 10.1080/13658816.2015.1038719 is OK
- 10.1111/1752-1688.12689 is OK
- 10.1080/13658810500433453 is OK
- 10.1080/13658816.2014.975715 is OK
- 10.1002/hyp.10648 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.7717/peerj.453 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.7287/peerj.preprints.27099v1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kbarnhart** [comment]
@giswqs I've now recommended that this submission be accepted and published. One of the JOSS EiC's @openjournals/joss-eics will manage final publication steps. 

Thanks to @laijingtao @cheginit and @amanaster2 for contributing reviews.

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2128

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2128, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1366846791564603392) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2129
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02965](https://doi.org/10.21105/joss.02965)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to  @giswqs (Qiusheng Wu)!!

And thanks to @laijingtao, @cheginit, and @amanaster2 for reviewing, and @kbarnhart for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02965/status.svg)](https://doi.org/10.21105/joss.02965)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02965">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02965/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02965/status.svg
   :target: https://doi.org/10.21105/joss.02965
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02965/status.svg)](https://doi.org/10.21105/joss.02965)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by giswqs** [comment]
@kbarnhart Thank you very much for handling my submission. Much appreciated. 

@laijingtao @cheginit and @amanaster2 Thank you all for your constructive comments that greatly improved the package.
