### ISSUE TITLE
[PRE REVIEW]: Agentpy: A package for agent-based modeling in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2966]
**Submitting author:** @JoelForamitti (<a href="http://orcid.org/0000-0002-4828-7288">Joël Foramitti</a>)
**Repository:** <a href="https://github.com/JoelForamitti/agentpy" target ="_blank">https://github.com/JoelForamitti/agentpy</a>
**Version:** v0.0.6
**Editor:** @sbenthall
**Reviewers:** @jamesdamillington, @martibosch 
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JoelForamitti. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @sbenthall.

@JoelForamitti if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (255.8 files/s, 314934.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          26            780            897           2048
reStructuredText                15            159            113            380
Jupyter Notebook                 5              0          60268            331
Markdown                         2             24              0             84
TeX                              1              8              1             70
DOS Batch                        1              8              1             26
YAML                             2              0              0             25
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            53            983          61287           2973
-------------------------------------------------------------------------------


Statistical information for the repository 'fac91b9f95c172a839cb6807' was
gathered on 2021/01/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Joël Foramitti                  43          8545           4850          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Joël Foramitti             3725           43.6          1.0                9.69
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1177/0963721419834547 is OK
- 10.3389/fevo.2018.00237 is OK

MISSING DOIs

- 10.1038/460685a may be a valid DOI for title: The economy needs agent-based modelling
- 10.1057/jos.2009.28 may be a valid DOI for title: Managing business complexity: discovering strategic solutions with agent-based modeling and simulation

INVALID DOIs

- https://doi.org/10.1002/wcc.647 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/wics.1356 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cosrev.2017.03.001 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02966/joss.02966/10.21105.joss.02966.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02966/joss.02966/10.21105.joss.02966.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@sbenthall @KristinaRiemer could one of you edit this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @KristinaRiemer as editor

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by KristinaRiemer** [comment]
@Kevin-Mattheus-Moerman I'm not going to be able to edit this submission, sorry.

**Comment by kthyng** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by sbenthall** [comment]
Yes, I can edit this one :)

**Comment by danielskatz** [comment]
@sbenthall  - you can ```@whedon assign me as editor``` whenever you are invited and agree, though I'll do it for you this time

**Comment by danielskatz** [comment]
@whedon assign @sbenthall as editor

**Comment by whedon** [comment]
OK, the editor is @sbenthall

**Comment by sbenthall** [comment]
@jamesdamillington would you be able to review this work?

**Comment by sbenthall** [comment]
@fdroessler would you be able to review this work?

**Comment by jamesdamillington** [comment]
@sbenthall yes, happy to review this

**Comment by sbenthall** [comment]
@whedon assign @jamesdamillington as reviewer

**Comment by whedon** [comment]
OK, @jamesdamillington is now a reviewer

**Comment by sbenthall** [comment]
@martibosch would you be able to review this work?

**Comment by martibosch** [comment]
Hello @sbenthall, sure, I'd be pleased to review this submission. Best,
Martí

**Comment by sbenthall** [comment]
Thank you!

**Comment by sbenthall** [comment]
@whedon add @martibosch  as reviewer

**Comment by whedon** [comment]
OK, @martibosch  is now a reviewer

**Comment by sbenthall** [comment]
Let's start this review!

**Comment by sbenthall** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3065.
