### ISSUE TITLE
[PRE REVIEW]: Recan: R-based tool for detection of recombination in viral genomes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2967]
**Submitting author:**  @vasily-pavelko (<a href="http://orcid.org/0000-0001-8142-1621">Vasily Pavelko</a>)
**Repository:** <a href="https://github.com/vasily-pavelko/recan" target ="_blank">https://github.com/vasily-pavelko/recan</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS  @vasily-pavelko. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @csoneson.

 @vasily-pavelko if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.02014 is OK
- 10.1016/j.meegid.2020.104212 is OK
- 10.18129/B9.bioc.seqcombo is OK
- 10.1093/bioinformatics/bth500 is OK
- 10.1128/JVI.73.1.152-160.1999 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (426.1 files/s, 38649.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         3             47              0            198
R                                3             23             93            176
TeX                              1             10              0             88
-------------------------------------------------------------------------------
SUM:                             7             80             93            462
-------------------------------------------------------------------------------


Statistical information for the repository 'a0cd818930c6b49d16d42a93' was
gathered on 2021/01/17.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02967/joss.02967/10.21105.joss.02967.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02967/joss.02967/10.21105.joss.02967.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @vasily-pavelko - thanks for your submission to JOSS. Can you confirm that this folder contains the primary source code for this submission? https://github.com/vasily-pavelko/recan/tree/master/R

I ask as last July we introduced a scope check for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) which this submission looks to not be meeting.

**Comment by vasily-pavelko** [comment]
> 👋 @vasily-pavelko - thanks for your submission to JOSS. Can you confirm that this folder contains the primary source code for this submission? https://github.com/vasily-pavelko/recan/tree/master/R

Yes, that is true. This folder is the main sourse of code in my package.

> I ask as last July we introduced a scope check for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) which this submission looks to not be meeting.
I checked these rules before  the submision
1.  My software was writen from the 8th of September till the 15th of January for 3 months and has 30 commits.
2.  There are more than 300 LOC (321 LOC according to GitHubGloc).
3.  Alex Sprygin https://orcid.org/0000-0001-5982-3675 will highly likely use my package in his future research.
Please, review my paper.

**Comment by kthyng** [comment]
Hi @vasily-pavelko and thanks for your submission. Unfortunately it has been determined by the editorial board to be too small in scope to pass our bar for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). Please note that there are [other pathways](https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages) for getting a DOI to cite for your software package if that is of interest.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
