### ISSUE TITLE
[REVIEW]: Riroriro: Simulating gravitational waves and calculating SNRs in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2968]
**Submitting author:** @wvanzeist (<a href="http://orcid.org/0000-0002-4231-656X">Wouter van Zeist</a>)
**Repository:** <a href="https://github.com/wvanzeist/riroriro" target ="_blank">https://github.com/wvanzeist/riroriro</a>
**Version:** v1.0.0
**Editor:** @dfm
**Reviewer:** @GregoryAshton, @katiebreivik
**Archive:** <a href="https://doi.org/10.5281/zenodo.4588070" target="_blank">10.5281/zenodo.4588070</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/22ee68e9828487b9d7b0036b195b99ad/status.svg)](https://joss.theoj.org/papers/22ee68e9828487b9d7b0036b195b99ad)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/22ee68e9828487b9d7b0036b195b99ad"><img src="https://joss.theoj.org/papers/22ee68e9828487b9d7b0036b195b99ad/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/22ee68e9828487b9d7b0036b195b99ad/status.svg)](https://joss.theoj.org/papers/22ee68e9828487b9d7b0036b195b99ad)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/wvanzeist/riroriro" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@GregoryAshton & @katiebreivik, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dfm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/wvanzeist/riroriro">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@wvanzeist) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/wvanzeist/riroriro">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@wvanzeist) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @GregoryAshton, @katiebreivik it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1361-6404/aaf81e is OK
- 10.1103/PhysRevD.95.024038 is OK
- 10.1093/mnras/sty908 is OK
- 10.1103/PhysRevD.85.122006 is OK
- 10.1103/PhysRevD.52.605 is OK
- 10.1103/PhysRevD.67.024016 is OK
- 10.1088/0264-9381/24/19/S31 is OK
- 10.1103/PhysRevD.59.084006 is OK
- 10.1103/PhysRevD.65.044001 is OK
- 10.1103/PhysRevD.65.124012 is OK
- 10.1103/PhysRevX.4.031006 is OK
- 10.1017/pasa.2017.51 is OK
- 10.1093/mnras/sty1353 is OK
- 10.21105/joss.01987 is OK
- 10.1103/PhysRevLett.116.061102 is OK
- 10.3847/1538-4365/ab06fc is OK
- 10.1088/1538-3873/aaef0b is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: :point_left:

**Comment by GregoryAshton** [comment]
@dfm I'm unable to tick the boxes above (I am logged in, and I accepted the request a few days back - now the link gives a "Sorry, we couldn't find that repository invitation")

**Comment by dfm** [comment]
@GregoryAshton: Sorry about that - I'll send you a new invitation!

**Comment by dfm** [comment]
@whedon re-invite @GregoryAshton as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@gregoryashton please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by whedon** [comment]
:wave: @GregoryAshton, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @katiebreivik, please update us on how your review is going.

**Comment by dfm** [comment]
@GregoryAshton, @katiebreivik: Note that the messages from @whedon are automated, and I am following along with issues that you have already opened. No need for more details here. Let me know if you have any questions as the reviews proceed!

**Comment by wvanzeist** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: :point_left:

**Comment by wvanzeist** [comment]
I have responded to every issue that has been raised in the repository; is there anything else that is keeping the review from proceeding?

**Comment by katiebreivik** [comment]
Hi @wvanzeist -- apologies on my part!! I am reading through the new proof this evening since I've been swamped for the past week.

**Comment by katiebreivik** [comment]
I am happy to recommend for publishing -- all boxes checked!

**Comment by wvanzeist** [comment]
@GregoryAshton Have you seen my response to the issue you raised in the Riroriro directory?

**Comment by GregoryAshton** [comment]
All boxes checked. Happy to recommend for publication.

**Comment by dfm** [comment]
Awesome - thanks @GregoryAshton and @katiebreivik for your reviews!

@wvanzeist: Now that the reviewers have signed off I'm going to do a pass of editing and then I'll have a few more steps for you in the next couple of days.

**Comment by dfm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: :point_left:

**Comment by dfm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1361-6404/aaf81e is OK
- 10.1103/PhysRevD.95.024038 is OK
- 10.1093/mnras/sty908 is OK
- 10.1103/PhysRevD.85.122006 is OK
- 10.1017/pasa.2017.51 is OK
- 10.1093/mnras/sty1353 is OK
- 10.21105/joss.01987 is OK
- 10.1103/PhysRevLett.116.061102 is OK
- 10.7935/GT1W-FZ16 is OK
- 10.1103/PhysRevD.102.044055 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@wvanzeist: I've opened a tiny pull request with some minor edits to the paper. Can you take a look at that and once you've merged, please take the following steps:

1. Comment `@whedon generate pdf` on this thread and read through the manuscript to make sure that you're happy with it (it's hard to make changes later!), especially author names and affiliations.
2. Increment the version number of the software and report that version number back here.
3. Create an archived release of that version of the software (using Zenodo or something similar). **Please make sure that the metadata (title and author list) exactly match the paper.** Then report the DOI of the release back to this thread.

Let me know if you have questions or run into any issues!

**Comment by wvanzeist** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: :point_left:

**Comment by wvanzeist** [comment]
@dfm Would you know of a way to prevent the PDF from breaking the word "Riroriro" weirdly without a line-break hyphen at line 62?

**Comment by wvanzeist** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: :point_left:

**Comment by wvanzeist** [comment]
In order to deal with the weird line break at line 62, I decided to just rearrange the sentence so that the word with the special formatting wasn't at the end of the line. It's fixed now.

**Comment by wvanzeist** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02968/joss.02968/10.21105.joss.02968.pdf) :page_facing_up: :point_left:

**Comment by wvanzeist** [comment]
> @wvanzeist: I've opened a tiny pull request with some minor edits to the paper. Can you take a look at that and once you've merged, please take the following steps:
> 
> 1. Comment `@whedon generate pdf` on this thread and read through the manuscript to make sure that you're happy with it (it's hard to make changes later!), especially author names and affiliations.
> 2. Increment the version number of the software and report that version number back here.
> 3. Create an archived release of that version of the software (using Zenodo or something similar). **Please make sure that the metadata (title and author list) exactly match the paper.** Then report the DOI of the release back to this thread.
> 
> Let me know if you have questions or run into any issues!

I have completed each of these steps, is there anything else I need to do now?

**Comment by dfm** [comment]
@wvanzeist: whoops! I hadn't seen the DOI and version number in the previous comment - sorry! I think you're all set. I'll pass this off to the Editors in Chief who might have some final edits before final processing.

@GregoryAshton, @katiebreivik: thanks again for your reviews!!

**Comment by dfm** [comment]
@whedon set 10.5281/zenodo.4588070 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4588070" target="_blank">10.5281/zenodo.4588070</a> is the archive.

**Comment by dfm** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by dfm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1361-6404/aaf81e is OK
- 10.1103/PhysRevD.95.024038 is OK
- 10.1093/mnras/sty908 is OK
- 10.1103/PhysRevD.85.122006 is OK
- 10.1017/pasa.2017.51 is OK
- 10.1093/mnras/sty1353 is OK
- 10.21105/joss.01987 is OK
- 10.1103/PhysRevLett.116.061102 is OK
- 10.7935/GT1W-FZ16 is OK
- 10.1103/PhysRevD.102.044055 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1369795096259002369) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2140
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02968](https://doi.org/10.21105/joss.02968)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congratulations @wvanzeist on your article's publication in JOSS!

Many thanks to  @GregoryAshton and @katiebreivik for reviewing this, and @dfm for editing it.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02968/status.svg)](https://doi.org/10.21105/joss.02968)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02968">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02968/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02968/status.svg
   :target: https://doi.org/10.21105/joss.02968
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02968/status.svg)](https://doi.org/10.21105/joss.02968)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by wvanzeist** [comment]
Great thanks for all the reviewers and editors! 

@kyleniemeyer When I go to the theoj.org page for this article, the place where the PDF is supposed to be appears empty, and clicking "download paper" gives "file not found". Might there be a bug of some sort, or is it just taking some time for the website to update?

**Comment by kyleniemeyer** [comment]
@wvanzeist yeah, sometimes I have found that caches / different DNS resolvers (or something) take a bit for the PDF to propagate and become available. It loads fine for me, so I would just give it some time on your end.

**Comment by wvanzeist** [comment]
Thanks! Now it loads correctly for me, too.
