### ISSUE TITLE
[PRE REVIEW]: ACEInhibPKPD: An open-source MATLAB app for a pharmacokinetic/pharmacodynamic model of ACE inhibition

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#297]
**Submitting author:** @ashleefv (<a href="http://orcid.org/0000-0001-9059-5703">Ashlee N. Ford Versypt</a>)
**Repository:** <a href="https://github.com/ashleefv/ACEInhibPKPD" target ="_blank">https://github.com/ashleefv/ACEInhibPKPD</a>
**Version:** v1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @sdelandtsheer

**Author instructions**

Thanks for submitting your paper to JOSS @ashleefv. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ashleefv if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @labarba - the submitting authors suggested you as a potential editor.

**Comment by labarba** [comment]
It's quite removed from any expertise of mine. I have no idea how to even begin finding a reviewer for this. (Not to mention it's a GUI app for MATLAB.)

**Comment by ashleefv** [comment]
The science has already been peer-reviewed and published this spring:
http://www.sciencedirect.com/science/article/pii/S009813541730145X. The
code also includes stand alone .m files that can be viewed in any editor.

Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State
University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences
Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu
Ford Versypt Lab Website <https://sites.google.com/site/ashleefordversypt/>

**Comment by Kevin-Mattheus-Moerman** [comment]
Not my field either but myself and @cMadan are MATLAB experts so perhaps we can have a look here too.

**Comment by Kevin-Mattheus-Moerman** [comment]
The [readme.md](https://github.com/ashleefv/ACEInhibPKPD/blob/master/README.md) and [paper.md](https://github.com/ashleefv/ACEInhibPKPD/blob/master/paper.md) emphasize "This software is intended to be used by engineering educators working with college freshmen or high school students and by systems biology researchers investigating pharmaceuticals to modulate the renin-angiotensin system.". Can you elaborate on the scientific research applications a bit more in the paper?
Also, there is a small typo in the paper "...describe and solve the the dynamics of...".

**Comment by ashleefv** [comment]
I updated both the readme.md and paper.md with additional statements about
the scientific applications. Is further clarification needed?

Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State
University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences
Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu
Ford Versypt Lab Website <https://sites.google.com/site/ashleefordversypt/>

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for making the changes. I'll review these and let you know. Although I am happy implementing/reviewing MATLAB code this is not my field of study. Can you recommend any reviewers (e.g. researchers that would be interested in your work but were not involved in its creation)?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon @labarba I can take this as editor

**Comment by ashleefv** [comment]
potential reviewers:

   - Fulden Buyukozturk
   https://www.linkedin.com/in/fulden-buyukozturk-b4384910/
   - Gilbert Koch https://www.ukbb.ch/en/personal/personen/koch-gilbert.php


Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State
University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences
Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu
Ford Versypt Lab Website <https://sites.google.com/site/ashleefordversypt/>

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@dpastoor, @ronkeizer, @billdenney, @PavelBal + @TheiBa (or a colleague at Open Systems Pharmacology team) would you willing to review this JOSS submission? 

Here is the [JOSS](http://joss.theoj.org/) website
Here is the repository for this project: https://github.com/ashleefv/ACEInhibPKPD 
Reviewing JOSS submissions generally does not take a lot of time and is largely focused on the claims and functionality of the software. See here for [reviewer instructions](http://joss.theoj.org/about#reviewer_guidelines)

Let me know if you have any questions.

**Comment by dpastoor** [comment]
@Kevin-Mattheus-Moerman Thanks for your interest. First, I would like to commend @ashleefv for putting her research in the open. This is a fantastic first step, however the core functionality is written in matlab, which is not FOSS. Looking at the guidelines, this does not seem to directly violate the journal requirements, however as I do not have a copy of matlab I will not be able to review.

I will encourage @ashleefv to consider using a fully open source implementation, such as using R shiny for the GUI + https://github.com/metrumresearchgroup/mrgsolve for the PKPD solver or something along those lines, at which point I would be happy to review

**Comment by Kevin-Mattheus-Moerman** [comment]
@dpastoor thanks for your fast reply. I understand your points. We do not exclude works in principle that require proprietor hardware or software (e.g. a runtime like MATLAB). As long as it adheres to the OSI definitions of open source. 
If we were able to set-up a free to use MATLAB environment (have to enquire), would you consider reviewing this work?

**Comment by Kevin-Mattheus-Moerman** [comment]
@ashleefv can you briefly inquire if translation to something like [octave](https://www.gnu.org/software/octave/) is easy to achieve? Translation is NOT a requirement but it would be good to state here if you believe it to be achievable in principle.

**Comment by dpastoor** [comment]
@Kevin-Mattheus-Moerman I have 2 problems reviewing this (I probably _could_ get ahold of matlab myself).

First and foremost, as I a have not written any matlab, I would not feel comfortable evaluating the implementation, which I believe is an important part of any scientific review. I can handle R, python, go, or javascript implementations, if at some point it is translated to any of those languages.

Second, I appreciate that matlab is extremely prevalent in engineering, and certain components, such as a GUI, were previously much more labor intensive to implement in FOSS languages. However, in this day and age, it is not an unreasonable task. To me, the thing that excites me seeing this journal is the ability to provide a "reviewed" piece of software that anyone, anywhere, can immediately pull and start using. To that end, I would be willing to 'donate' my time to support such software efforts, however in tandem with the first point above I cannot justify the bandwidth needed for a "closed" matlab implementation to take the time to properly review.  Again, not to take anything from @ashleefv 's willingness to at least put the code in the open, which I think is *amazing*.

If @ashleefv is willing to do a translation, I would be happy to assist in both the translation and/or review.

**Comment by ashleefv** [comment]
I looked into octave. Unfortunately, even for the code that doesnt need the
GUI, octave cannot handle the .mat files used for storing data and
variables for various cases.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ashleefv thanks for your reply. I understand.

**Comment by Kevin-Mattheus-Moerman** [comment]
@dpastoor Thanks for your detailed reply. I understand your points. We would be happy to have you as reviewer on other projects. And here is a list of currently open reviews:
https://github.com/openjournals/joss-reviews/issues/

**Comment by Kevin-Mattheus-Moerman** [comment]
:wave: @tpfau @sdelandtsheer would you willing to review this JOSS submission? 

Here is the [JOSS](http://joss.theoj.org/) website
Here is the repository for this project: https://github.com/ashleefv/ACEInhibPKPD 
Reviewing JOSS submissions generally does not take a lot of time and is largely focused on the claims and functionality of the software. See here for [reviewer instructions](http://joss.theoj.org/about#reviewer_guidelines)

Let me know if you have any questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tpfau @sdelandtsheer would you willing to review this JOSS submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@ashleefv you suggested reviewers but I have not find them on GitHub. Can you suggest reviewers by posting GitHub handles here?

**Comment by ashleefv** [comment]
They may not be on Github. If needed because of no reviewers, I can
withdraw this submission.

Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State
University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences
Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu
Ford Versypt Lab Website <https://sites.google.com/site/ashleefordversypt/>

**Comment by danielskatz** [comment]
Or you can provide email addresses, and they can be asked to join GitHub to do the review.

**Comment by ashleefv** [comment]
gilbert.koch@ukbb.ch

@fulden_b on twitter

Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State
University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences
Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu
Ford Versypt Lab Website <https://sites.google.com/site/ashleefordversypt/>

**Comment by Kevin-Mattheus-Moerman** [comment]
I've invited @fulden_b via twitter https://twitter.com/KMMoerman/status/891756250589007874

**Comment by Kevin-Mattheus-Moerman** [comment]
and I've just e-mailed Gilbert Koch, thanks @ashleefv

**Comment by sdelandtsheer** [comment]
Hi, sorry for the delayed answer. I just read the reviewers guidelines. I can review that software, happy to do it.

**Comment by Kevin-Mattheus-Moerman** [comment]
Awesome! Thanks @sdelandtsheer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @sdelandtsheer as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sdelandtsheer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/340. Feel free to close this issue now!

**Comment by Kevin-Mattheus-Moerman** [comment]
Ok @ashleefv @sdelandtsheer review will happen here #340
