### ISSUE TITLE
[REVIEW]: Moead-framework : a modular MOEA/D python framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2974]
**Submitting author:** @geoffreyp (<a href="http://orcid.org/0000-0002-5049-5991">Geoffrey Pruvost</a>)
**Repository:** https://github.com/moead-framework/framework
**Branch with paper.md** (empty if default branch): 
**Version:** 1.0
**Editor:** @melissawm
**Reviewers:** @sjvrijn, @chkoar
**Archive:** 10.5281/zenodo.7152178

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a81ea21d0358e013000b0b3b926bd4ba/status.svg)](https://joss.theoj.org/papers/a81ea21d0358e013000b0b3b926bd4ba)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a81ea21d0358e013000b0b3b926bd4ba"><img src="https://joss.theoj.org/papers/a81ea21d0358e013000b0b3b926bd4ba/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a81ea21d0358e013000b0b3b926bd4ba/status.svg)](https://joss.theoj.org/papers/a81ea21d0358e013000b0b3b926bd4ba)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/moead-framework/framework" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@sjvrijn & @chkoar, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @melissawm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/moead-framework/framework">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@geoffreyp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/moead-framework/framework">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@geoffreyp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @sjvrijn, @chkoar it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TEVC.2008.925798 is OK
- 10.1109/TEVC.2007.892759 is OK
- 10.1109/CEC.2009.4982949 is OK
- 10.1145/3377930.3390149 is OK
- 10.1007/978-3-030-43680-3_9 is OK
- 10.18637/jss.v092.i06 is OK
- 10.1109/ACCESS.2020.2990567 is OK
- 10.21105/joss.02338 is OK
- 10.1145/2739482.2768462 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02974/joss.02974/10.21105.joss.02974.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02974/joss.02974/10.21105.joss.02974.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
👋🏼 @geoffreyp @sjvrijn @chkoar this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#2974` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@melissawm) if you have any questions/concerns.

**Comment by melissawm** [comment]
Hello, folks! @chkoar @sjvrijn @geoffreyp I see some progress in the checkboxes, let me know if there's anything I can help you with. Thanks!

**Comment by melissawm** [comment]
Hello, folks! @chkoar @sjvrijn @geoffreyp I see some progress in the checkboxes, let me know if there's anything I can help you with. Thanks!

**Comment by whedon** [comment]
:wave: @sjvrijn, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @chkoar, please update us on how your review is going.

**Comment by chkoar** [comment]
Hey @melissawm, I hope that by Monday I will have completed the review.

**Comment by chkoar** [comment]
Hey @melissawm, I created a couple of issues in the software repo. 
I'll wait the authors response in order to continue my review report.

**Comment by geoffreyp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02974/joss.02974/10.21105.joss.02974.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02974/joss.02974/10.21105.joss.02974.pdf) :page_facing_up: :point_left:

**Comment by geoffreyp** [comment]
Hello @chkoar and @sjvrijn,
I answered your issues and push the new release(0.5.8) of the framework with your comments and tips, thank you!

I move the documentation in the same repository, the new URL is: https://moead-framework.github.io/framework/

**Comment by chkoar** [comment]
@geoffreyp please try to address the raised issues atomically. Unrelated changes might slow down the review process. Thanks.

**Comment by sjvrijn** [comment]
Hi @geoffreyp and @melissawm, sorry for the delay on my part until now. I'm continueing my review and will have some comments tomorrow.

**Comment by geoffreyp** [comment]
Hi, I don't know if you received a notification, but I answered directly in your issues: https://github.com/moead-framework/framework/issues

**Comment by sjvrijn** [comment]
Hi @geoffreyp, are you explicitly waiting for our confirmation on whether issues were sufficiently addressed?

If so, maybe a tip/suggestion for next time: create a separate PR corresponding to each issue. That gives a clear location and interface to view and discuss the changes.

**Comment by geoffreyp** [comment]
Hello @sjvrijn, my message was just to inform you that you can continue the review because the previous issues have been resolved. I have seen your new issues, I will deal with them as soon as possible.

Thanks for the tip, I will use separate PR now instead of writing the issue number in the commit

**Comment by chkoar** [comment]
Great. During the weekend I will review the changes.

**Comment by melissawm** [comment]
Hello, @geoffreyp , @chkoar and @sjvrijn ! I'm just checking if you need anything from me. I see the issues being filed in the main repo so I assume the review is going well, let me know if there's anything I can do to help. Cheers!

**Comment by chkoar** [comment]
Hey @melissawm! @geoffreyp has worked on issues raised by us and I suppose that he needs our feedback in order to move forward. After the bank holidays of the orthodox easter I will try to provide the feedback that he needs.

**Comment by melissawm** [comment]
Hello, folks! @chkoar @geoffreyp and @sjvrijn Just checking in - anything I can help you with?

**Comment by geoffreyp** [comment]
Hello @melissawm, 
to summarize, there are still 5 issues to be reviewed by @chkoar and none for @sjvrijn.
Two of these issues are open questions that I answered a few months ago, 3 PR are created for the 3 other issues.

**Comment by melissawm** [comment]
Thanks for the update! Please ping me if you need anything :)

**Comment by chkoar** [comment]
> @geoffreyp to summarize, there are still 5 issues to be reviewed by @chkoar and none for @sjvrijn.
Two of these issues are open questions that I answered a few months ago, 3 PR are created for the 3 other issues

I think that My review can be submitted regardless of these issues.

**Comment by chkoar** [comment]
@melissawm till now, I have opened an issue in the software repo for each concern I had. Although there were not a direct match with the checklist. I have left some of the checks unchecked. Since some of them cannot be addressed by the author (e.g. General Checks), do you want me to paste here my report so we will be all aligned?

**Comment by melissawm** [comment]
@chkoar - if you feel like more work is necessary before you check the items, I think you can continue working with the author to get there. It is useful to give updates here just so I know there are not pending issues waiting for either the author or reviewer to respond for too long. If things are moving forward, then that's fine with me!

**Comment by sjvrijn** [comment]
Hi @melissawm, apologies for the recent lack of response & progress. I hope to complete my review later today by raising all remaining issues I see for me to complete the checklist.

One question regarding the software paper though: Besides just multi-objective optimization software, other frameworks also exist for single-objective optimization such as [DEAP](https://deap.readthedocs.io/), and a framework for CMA-ES, similarly modular to this project, I worked on ([ModEA](https://github.com/sjvrijn/ModEA)). Are these structurally relevant enough to include in the paper, or is it enough for the paper to focus on multi-objective optimization only?

**Comment by geoffreyp** [comment]
Hello @melissawm @sjvrijn @chkoar, 
I have completed the requested changes. Do you think that the review can be finished before August? It's just to know if I can include this work in my thesis before sending it :)

**Comment by chkoar** [comment]
Hey @geoffreyp, I will open three issues so you can address them in order to move forward the review.

**Comment by sjvrijn** [comment]
Hi @geoffreyp,
I can check 'functionality documentation' once moead-framework/framework#55 has been approved by @chkoar and merged.

For 'state of the field' I'm waiting for a resolution my question about other frameworks from May 27th: either adding a paragraph on them in your paper, or a confirmation from @melissawm that they are out-of-scope for this submission.

**Comment by melissawm** [comment]
Thanks all for the update!

I do think it would be useful to address the "State of the Field" question by @sjvrijn - can you clarify @geoffreyp ? Thanks!

**Comment by chkoar** [comment]
@melissawm hey! As I [said earlier](https://github.com/openjournals/joss-reviews/issues/2974#issuecomment-869566182) I will open some issues in the software repo, so the review will move forward. However, some checks cannot be addressed from @geoffreyp. For instance the General Checks that I haven't ticked yet. Could you please see my comments and validate that they can be ticked without any concern?

# General checks

***Contribution and authorship: Has the submitting author (@geoffreyp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?***

The submitting author [seems](https://github.com/openjournals/joss-reviews/issues/2895#issuecomment-741149229) to be the solely contributor to this package. However, the paper states two other authors. The problem here is that I cannot see and validate their contribution to this package. I can see their names in a cited papers, though.

**Substantial scholarly effort: Does this submission meet the scope eligibility described in the JOSS guidelines**

JOSS requires that the published software should represent substantial scholarly effort. Thus, it lists some [factors](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) that should be considered.

At the [date](https://github.com/openjournals/joss-reviews/issues/2895#issuecomment-741149229) **of the submission** the submitted project had 60 commits, 1 author and almost 1.5k lines of Python code (549 blank and 236 comments)

Although, the submitted software seems that it have been used in two publications of the submitted author.

**Comment by geoffreyp** [comment]
Hello @sjvrijn, you can see my answer in the PR https://github.com/moead-framework/framework/pull/68.


> Hey @geoffreyp, I will open three issues so you can address them in order to move forward the review.

Hello @chkoar, thank you, so I will wait for the new issues ! 

Concerning the **Contribution and authorship**, Bilel and Arnaud are my supervisors, and they contributed to the framework in its design and in the writing of the paper, even if it is true that they do not appear in the contributors on GitHub

**Comment by chkoar** [comment]
Hey @geoffreyp,

I have opened moead-framework/framework#69, moead-framework/framework#69 and moead-framework/framework#70. These are my objections regarding my unticked items in my report.

@melissawm I suppose that @geoffreyp's [answer](https://github.com/openjournals/joss-reviews/issues/2974#issuecomment-870455114) is adequate in order to tick the [General Checks](https://github.com/openjournals/joss-reviews/issues/2974#issuecomment-869782530), right?

cc @sjvrijn

**Comment by melissawm** [comment]
> _**Contribution and authorship: Has the submitting author (@geoffreyp) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?**_
> 
> The submitting author [seems](https://github.com/openjournals/joss-reviews/issues/2895#issuecomment-741149229) to be the solely contributor to this package. However, the paper states two other authors. The problem here is that I cannot see and validate their contribution to this package. I can see their names in the cited papers, though.

From the JOSS Documentation [here](https://joss.readthedocs.io/en/latest/submitting.html#authorship) and [here](https://joss.readthedocs.io/en/latest/review_criteria.html#authorship) 

*Purely financial (such as being named on an award) and organizational (such as general supervision of a research group) contributions are not considered sufficient for co-authorship of JOSS submissions, **but active project direction and other forms of non-code contributions are. The authors themselves assume responsibility for deciding who should be credited with co-authorship, and co-authors must always agree to be listed.** In addition, co-authors agree to be accountable for all aspects of the work, and to notify JOSS if any retraction or correction of mistakes are needed after publication.*

It is reasonable to expect that the co-authors are then aware and agree to be listed here.

As far as Substantial Scholarly Effort, I don't see an objection. (although of course Reviewers are free to disagree :)

**Comment by geoffreyp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02974/joss.02974/10.21105.joss.02974.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02974/joss.02974/10.21105.joss.02974.pdf) :page_facing_up: :point_left:

**Comment by geoffreyp** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02974/joss.02974/10.21105.joss.02974.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02974/joss.02974/10.21105.joss.02974.pdf) :page_facing_up: :point_left:

**Comment by chkoar** [comment]
> As far as Substantial Scholarly Effort, I don't see an objection. (although of course Reviewers are free to disagree :)

OK. Checked.

**Comment by melissawm** [comment]
Hello, folks. I know there has been some movement on the repo, but I wanted to check what is still left to do for this review to be finalized. Is there anything I might be able to help you with? Thanks!

@chkoar @geoffreyp

**Comment by kyleniemeyer** [comment]
Hi @geoffreyp, I just wanted to check in on the status of your work.

**Comment by geoffreyp** [comment]
Hello @kyleniemeyer, I am waiting for the feedback from @chkoar (or from @sjvrijn if he has more time than @chkoar) ? 
We still have 2 issues to close : 
- https://github.com/moead-framework/framework/issues/71
- https://github.com/moead-framework/framework/issues/70

**Comment by melissawm** [comment]
Hello folks, any updates on this? Thanks!

**Comment by geoffreyp** [comment]
Hello @melissawm,
Not really, we still have 2 issues to close : 
- https://github.com/moead-framework/framework/issues/71
- https://github.com/moead-framework/framework/issues/70

**Comment by chkoar** [comment]
@melissawm almost there

**Comment by melissawm** [comment]
Gentle ping on this one!

**Comment by melissawm** [comment]
Hello folks - is there anything we can do to move this to the finish line? Thanks!

**Comment by geoffreyp** [comment]
Hello @melissawm, we only have one more issue to close : https://github.com/moead-framework/framework/issues/71 
@chkoar

**Comment by melissawm** [comment]
Sorry to be bumping this again - do we have any updates on this submission? Thanks

**Comment by chkoar** [comment]
Hey @melissawm, I think yes. I believe that we are almost there. Please read [this](https://github.com/moead-framework/framework/issues/71) for further info.

**Comment by geoffreyp** [comment]
Hello, sorry for the delay. I have just added the new tests to the review branch

**Comment by arfon** [comment]
Hi folks, just checking in again here. @chkoar @geoffreyp – it looks like you're finessing tests in https://github.com/moead-framework/framework/issues/71 ? Having reviewed that thread I would recommend moving forward with an accept/publish at this point @melissawm.

**Comment by melissawm** [comment]
@sjvrijn @chkoar are you happy with us moving to accept and publish this paper at this point?

**Comment by sjvrijn** [comment]
@melissawm Yep, looks good to me!

**Comment by chkoar** [comment]
> @sjvrijn @chkoar are you happy with us moving to accept and publish this paper at this point?

Yeap

**Comment by melissawm** [comment]
Folks - I am really sorry for the delay, entirely due to personal issues on my part. 

@chkoar I see you still have the "Automated tests" checklist item unchecked, but I am assuming we can move forward based on your answer above. 

At this point I will generate a new proof and ask @geoffreyp to review and make sure everything is alright.

**Comment by melissawm** [comment]
@editorialbot generate pdf

**Comment by melissawm** [comment]
@editorialbot check references

**Comment by geoffreyp** [comment]
@editorialbot generate pdf

**Comment by melissawm** [comment]
@editorialbot set 10.5281/zenodo.7152178 as archive

**Comment by melissawm** [comment]
@editorialbot set 1.0 as version

**Comment by melissawm** [comment]
@editorialbot recommend-accept

**Comment by arfon** [comment]
@geoffreyp – I found a couple of minor typos in your paper here: https://github.com/moead-framework/framework/pull/79

**Comment by arfon** [comment]
@editorialbot recommend-accept

**Comment by geoffreyp** [comment]
Thanks @arfon, it is fixed

**Comment by arfon** [comment]
@editorialbot accept

**Comment by arfon** [comment]
@sjvrijn, @chkoar – many thanks for your reviews here and to @melissawm for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@geoffreyp – your paper is now accepted and published in JOSS :zap::rocket::boom:
