### ISSUE TITLE
[REVIEW]: EMD: Empirical Mode Decomposition and Hilbert-Huang Spectral Analyses in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2977]
**Submitting author:** @ajquinn (<a href="http://orcid.org/0000-0003-2267-9897">Andrew Quinn</a>)
**Repository:** <a href="https://gitlab.com/emd-dev/emd" target ="_blank">https://gitlab.com/emd-dev/emd</a>
**Version:** 0.4.0
**Editor:** @dpsanders
**Reviewer:** @JanCBrammer, @EtienneCmb, @neurofractal
**Archive:** <a href="https://doi.org/10.5281/zenodo.4647949" target="_blank">10.5281/zenodo.4647949</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/02ba7be4eea16a18976d264ac5443dbd/status.svg)](https://joss.theoj.org/papers/02ba7be4eea16a18976d264ac5443dbd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/02ba7be4eea16a18976d264ac5443dbd"><img src="https://joss.theoj.org/papers/02ba7be4eea16a18976d264ac5443dbd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/02ba7be4eea16a18976d264ac5443dbd/status.svg)](https://joss.theoj.org/papers/02ba7be4eea16a18976d264ac5443dbd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/emd-dev/emd" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@JanCBrammer & @EtienneCmb & @neurofractal, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @dpsanders know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/emd-dev/emd">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ajquinn) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/emd-dev/emd">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ajquinn) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/emd-dev/emd">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ajquinn) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @JanCBrammer, @EtienneCmb, @neurofractal it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2977 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Anna Nobre, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1098/rspa.1998.0193 is OK
- 10.1109/icassp.2005.1416051 is OK
- 10.1142/s1793536909000096 is OK
- 10.1142/s1793536909000047 is OK
- 10.1098/rsta.2015.0206 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by AJQuinn** [comment]
Hello - thanks all for your time!

I have the latest version of the paper in a branch for the moment, I think this is causing the whedon error above...

@whedon generate pdf from branch 33-joss-revisions

**Comment by AJQuinn** [comment]
@whedon generate pdf from branch 33-joss-revisions

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 33-joss-revisions. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: :point_left:

**Comment by EtienneCmb** [comment]
Hi @AJQuinn,

Some minor comments about the draft : 
- Caption figure 2 : "cycle-maximum"
- Caption figure 3 : "an an" amplitude
- Caption figure 4 : a suggestion, you could add some details about which frequencies composed the simulated signal. This would then be easier for the reader to retrieve the informations especially for the holospectrum. In addition, I would increase the fontsize of x/y labels and titles

Small question : is the holospectrum related to phase-amplitude coupling and comodulogram plot?

**Comment by EtienneCmb** [comment]
You could also add one sentence to the manuscript to highlight that some computations can be accelerated though multi-processing. This is a nice feature that doesn't seems to be present over all other EMD packages

**Comment by JanCBrammer** [comment]
@whedon re-invite @JanCBrammer as reviewer

**Comment by whedon** [comment]
I'm sorry @JanCBrammer, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by JanCBrammer** [comment]
> 
> 
> I'm sorry @JanCBrammer, I'm afraid I can't do that. That's something only editors are allowed to do.

@dpsanders, could you re-invite me (invitation has expired)?

**Comment by danielskatz** [comment]
@whedon re-invite @JanCBrammer as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@jancbrammer please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by AJQuinn** [comment]
Hi all, I've made some paper changes based on @EtienneCmb suggestions above. Please let me know if these are ok and if there are any more!

We followed up the point about phase-amplitude coupling elsewhere in the end but just in case others are interested... the Holospectrum quantifies any amplitude modulations present in an oscillatory signal but does not formally relate these to the phase of a low frequency signal. The methods measure complementary things but you would still need a phase x frequency plot or comodulogram alongside the holospectrum for a complete PAC measure (there is an example of this at the end of the Holospectrum tutorial)

Cheers,
Andrew

**Comment by AJQuinn** [comment]
@whedon generate pdf from branch 33-joss-revisions

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 33-joss-revisions. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @EtienneCmb, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @JanCBrammer, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @neurofractal, please update us on how your review is going.

**Comment by dpsanders** [comment]
Sorry about the automatic reminders; please let us know here if you have comments. Detailed technical questions, comments etc. are best done as an issue on the software repository with a link to this issue. Thanks!

**Comment by JanCBrammer** [comment]
@AJQuinn, I suggested a few small manuscript edits over at #AJQuinn/emd-mirror/pull/1. I enjoyed reading the paper. Helpful figures! Will dive into the package and docs in the coming days.

**Comment by JanCBrammer** [comment]
Below is a list of observations from my review (in progress). I labeled those points that ideally should be addressed before publication with *TODO*. Everything else are merely suggestions or remarks. I'll let you know once I've concluded the review.

### General
* beautiful tutorials that can be conveniently run in Binder environment.
* adding some high-level plotting functions to `plotting.py` might be nice, since currently it seems that the user needs to generate some plots (e.g., HHT plots) from scratch?
* code in [README examples](https://gitlab.com/emd-dev/emd/-/tree/master) is not compliant with [PEP8](https://www.python.org/dev/peps/pep-0008/)

### Paper
- [ ] *TODO*: some [edits](https://github.com/AJQuinn/emd-mirror/pull/1)
- [ ] *TODO*: dead link to `contribution guidelines`

### Documentation
- [ ] *TODO*: target audience is not explicitly mentioned (although this is sufficiently clear from context imo)
* maybe use the term `API` instead of [reference](https://emd.readthedocs.io/en/latest/reference.html#)? The latter made me expect to find a way to cite the package.
* contributor instructions could be a bit more explicit, e.g., infos on how to install editable version, run tests, guidelines on scope, code style etc..
* [`from conda` section](https://emd.readthedocs.io/en/latest/install.html#from-conda) in installation instructions pertains to `pip`-installing `emg` into a conda environment, not from a conda channel (e.g., `conda-forge`)

**Comment by JanCBrammer** [comment]
I concluded my review and would be happy to see @AJQuinn's paper on the `emd` package published in JOSS. The paper is well written and the package is of high quality (excellent documentation, automated tests and package management, good coding practices). I explored `emd` using time series containing cardiac physiology ([inter-beat-intervals](https://en.wikipedia.org/wiki/Interbeat_interval)) and found the core functionality (computing IMF and HHT) working to my satisfaction. Once @AJQuinn has addressed the _TODO_ items in my earlier post, I'm happy to sign off on my review.

**Comment by EtienneCmb** [comment]
Same here, I tested `emd` on the examples such as on neural data and everything worked as expected. Overall, I also agree that the examples written in a tutorial fashion are really clear. 

From my side, all lights are green for publishing in JOSS as soon as @AJQuinn has addressed my few comments about the examples.

**Comment by neurofractal** [comment]
Hi all.. Should be able to look at this over the next week or so. Excited to try some EMD on MEG data.

**Comment by AJQuinn** [comment]
Thank you all - very interesting and useful suggestions in the reviews. I'll make those changes during the week and make a note here when they're done.

Cheers

**Comment by AJQuinn** [comment]
Hi all - changes based on comments from @EtienneCmb are summarised here: https://gitlab.com/emd-dev/emd/-/issues/42#note_513753774 . I'm working on changes from @JanCBrammer next - will upate early next week.

Cheers

**Comment by AJQuinn** [comment]
Hi again - changes based on @JanCBrammer's comments are on this branch: https://gitlab.com/emd-dev/emd/-/merge_requests/53 - thanks for the suggestions! Please let me know if there is anything else I have missed or can do.

There is now also an updated manuscript based on all the changes so far here: https://gitlab.com/emd-dev/emd/-/merge_requests/38

Thanks all!

**Comment by AJQuinn** [comment]
@whedon generate pdf from branch 33-joss-revisions

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 33-joss-revisions. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: :point_left:

**Comment by JanCBrammer** [comment]
Thanks, @AJQuinn! I've been browsing through the changes at https://gitlab.com/emd-dev/emd/-/merge_requests/53 and I'm absolutely happy with the way you addressed my comments. I think you've put together an amazing, high quality piece of software and I can't wait to find an excuse to use it :grin:

**Comment by AJQuinn** [comment]
Thanks @JanCBrammer - that's great to hear. I'm glad you liked the package. I'll merge that branch in the next day or so!

**Comment by EtienneCmb** [comment]
Hi @AJQuinn, I looked at the changes you made, especially the tutorial about how to use EMD to retrieve the PAC. I have to say that it is a fantastic tutorial, very clear and the figures clearly explain your point. Like all of the other examples, the progression in the difficulty is very pleasant to read.

About the rest of your commits, I believe you addressed all of my points, even minor ones like the html representation.

Thank you for this nice piece of software, I learned a lot about EMD through the examples, I'll definitely use it in my data analysis to dig into my time-series.

**Comment by AJQuinn** [comment]
Thank you @EtienneCmb, very help full comments.

The changes from both reviews are now merged into the main package on gitlab.com and the updates to the website are live. Thanks for all your time!

Cheers

**Comment by AJQuinn** [comment]
Hi @neurofractal - thanks for the comments. I've included the changes in the branches attached to this issue: https://gitlab.com/emd-dev/emd/-/issues/47

I'll recompile the paper with changes here as well - let me know if there is anything I've missed or anything else I can do!

Cheers

**Comment by AJQuinn** [comment]
@whedon generate pdf from branch 33-joss-revisions

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 33-joss-revisions. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: :point_left:

**Comment by dpsanders** [comment]
👋  @EtienneCmb and @JanCBrammer: Are you happy with the current version and finished with your reviews? Thanks!

**Comment by dpsanders** [comment]
@neurofractal: Could you please fill in the checkboxes at the top of this review? Thanks!

**Comment by neurofractal** [comment]
@dpsanders all done. Finished with my review!

**Comment by JanCBrammer** [comment]
> Are you happy with the current version and finished with your reviews? Thanks!

@dpsanders, yes and yes 👍 Except for a tiny edit in the current proof: I believe on line 55 the `(?)` after `obtain` can be removed?

**Comment by EtienneCmb** [comment]
>  @EtienneCmb and @JanCBrammer: Are you happy with the current version and finished with your reviews? Thanks!

yes I finished with my review and I'm happy with the current version :+1:

**Comment by AJQuinn** [comment]
@whedon generate pdf from branch 33-joss-revisions

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 33-joss-revisions. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: :point_left:

**Comment by AJQuinn** [comment]
Hi @dpsanders - is there anything else outstanding for this review? 

Sorry to ask... just wondering about timings. I'm close to needing the next release and would like to get all the JOSS changes in a single increment if possible. I'll wait if there are only minor changes needed but if there is something bigger required I'll plan for two releases. Thank you for your time

**Comment by dpsanders** [comment]
Apologies for the delay.

I submitted a couple of PRs with minor edits. 
I am also checking if the other software packages you link top need to be listed in the References section.
Apart from that LGTM!

**Comment by AJQuinn** [comment]
Thank you for the edits @dpsanders - those changes are now merged into the JOSS draft branch.

I think several of the other toolboxes have websites but I couldn't find anything more formally citable (eg with a DOI) so left it with the link in the draft. I'm happy to double check this and inlcude the most stable-looking links in the reference section?

**Comment by AJQuinn** [comment]
@whedon generate pdf from branch 33-joss-revisions

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 33-joss-revisions. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: :point_left:

**Comment by dpsanders** [comment]
Yes please include links in the references section.

Then when you are ready please make a release and archive it, e.g. at zenodo.org.
Then report the release number and archive link here. Thanks!

**Comment by AJQuinn** [comment]
@whedon generate pdf from branch 33-joss-revisions

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 33-joss-revisions. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: :point_left:

**Comment by AJQuinn** [comment]
Hi @dpsanders -  I've pushed v0.4.0 with all the changes from the review. This is now the stable version on PyPI (https://pypi.org/project/emd/).

I've archived a tarball of 0.4.0 on Zenodo under the same license as the main code release
https://zenodo.org/record/4647949
https://doi.org/10.5281/zenodo.4647949

I think that is all in order... please let me know if I should do anything else or have missed something out.

Thanks for your help

**Comment by dpsanders** [comment]
@whedon set 0.4.0 as version

**Comment by whedon** [comment]
OK. 0.4.0 is the version.

**Comment by dpsanders** [comment]
@whedon set https://doi.org/10.5281/zenodo.4647949 as archive

**Comment by dpsanders** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1098/rspa.1998.0193 is OK
- 10.1109/icassp.2005.1416051 is OK
- 10.1142/s1793536909000096 is OK
- 10.1142/s1793536909000047 is OK
- 10.1098/rsta.2015.0206 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2977 with the following error:

**Comment by dpsanders** [comment]
@whedon generate pdf from branch 33-joss-revisions

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 33-joss-revisions. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02977/joss.02977/10.21105.joss.02977.pdf) :page_facing_up: :point_left:

**Comment by dpsanders** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1098/rspa.1998.0193 is OK
- 10.1109/icassp.2005.1416051 is OK
- 10.1142/s1793536909000096 is OK
- 10.1142/s1793536909000047 is OK
- 10.1098/rsta.2015.0206 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2169

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2169, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
everything looks good!!

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1377282294117978115) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2171
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02977](https://doi.org/10.21105/joss.02977)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @AJQuinn! Thanks to editor @dpsanders and reviewers @JanCBrammer, @EtienneCmb, and @neurofractal for your time, hard work, and expertise!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02977/status.svg)](https://doi.org/10.21105/joss.02977)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02977">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02977/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02977/status.svg
   :target: https://doi.org/10.21105/joss.02977
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02977/status.svg)](https://doi.org/10.21105/joss.02977)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by dpsanders** [comment]
Congratulations @AJQuinn! Many thanks to @JanCBrammer, @EtienneCmb and @neurofractal for your detailed and helpful reviews, and to @kthyng for help with the process.
