### ISSUE TITLE
[REVIEW]: minimo: a linked data and metadata storage system for small labs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2979]
**Submitting author:** @borchardt (<a href="http://orcid.org/0000-0001-9033-6365">Jackson Borchardt</a>)
**Repository:** <a href="https://github.com/focolab/minimo.git" target ="_blank">https://github.com/focolab/minimo.git</a>
**Version:** 44b306957691505bc4f95cdb0721c7e1b03a9e7d
**Editor:** @majensen
**Reviewers:** @junjun-zhang, @bensonml, @junjun-zhang
**Archive:** <a href="https://doi.org/10.5281/zenodo.4678098" target="_blank">10.5281/zenodo.4678098</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e7d0a8ee7c5182907d4ee7d78887c459/status.svg)](https://joss.theoj.org/papers/e7d0a8ee7c5182907d4ee7d78887c459)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e7d0a8ee7c5182907d4ee7d78887c459"><img src="https://joss.theoj.org/papers/e7d0a8ee7c5182907d4ee7d78887c459/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e7d0a8ee7c5182907d4ee7d78887c459/status.svg)](https://joss.theoj.org/papers/e7d0a8ee7c5182907d4ee7d78887c459)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/focolab/minimo.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@junjun-zhang & @bensonml, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @majensen know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/focolab/minimo.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@borchardt) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/focolab/minimo.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@borchardt) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @junjun-zhang, @bensonml it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2979 with the following error: 

 Can't find any papers to compile :-(

**Comment by majensen** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02979/joss.02979/10.21105.joss.02979.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02979/joss.02979/10.21105.joss.02979.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @junjun-zhang, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @bensonml, please update us on how your review is going.

**Comment by bensonml** [comment]
Status update: Currently reading paper, and going through test install

--
Mark Benson, PhD (NIH/NCI) [C]
9605 Medical Center Dr., Suite 390 Office #02
Rockville, MD 20850
Mobile: 240-672-1400
mark.benson@nih.gov<mailto:mark.benson@nih.gov>

**Comment by majensen** [comment]
@whedon add @junjun-zhang as reviewer

**Comment by whedon** [comment]
OK, @junjun-zhang is now a reviewer

**Comment by majensen** [comment]
@whedon re-invite @junjun-zhang as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@junjun-zhang please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by majensen** [comment]
@whedon re-invite @junjun-zhang as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@junjun-zhang please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by majensen** [comment]
@bensonml @junjun-zhang making progress?

**Comment by junjun-zhang** [comment]
@majensen, have been trying it out, will post comments in coming days

**Comment by bensonml** [comment]
Thanks for the reminder – I’ll finish up in the next day or two

-Mark

**Comment by bensonml** [comment]
I recommend the paper for publication

1. Software looks good - and it's great to see it being currently used by the lab.
2. installation and options worked well 
3. documentation is pretty good
4. it would be nice to see some tests - even if they are smoke tests
5. look forward to seeing future releases, and mentioned updates

**Comment by Borchardt** [comment]
Thanks for the feedback, bensonml! I agree with you on the need for automated testing. As a quick first step, I've added an Actions workflow which builds the app, connects to its reverse proxy container, and validates landing page content.

Adding deeper functional tests is on my backlog, and I'll update here as I make headway.

**Comment by junjun-zhang** [comment]
`minimo` certainly has the potential to address the need of a system that helps researchers to organize and track their data together with associated metadata.

Installation and getting the app up and running was straightforward, thanks to the nice documentation.

My comments are more on useability from a user’s perspective:

1. The term `form` in the `MANAGE FORMS` is a bit confusing. It seems more like a field, not a web form that consists of multiple fields.
2. If the above understanding is correct, is there any plan to add support for defining metadata `form` with multiple `fields`? That would be very helpful as I expect many labs may have different types of experimental results, different experiments can then use different metadata forms.
3. It’s not quite clear what `Number of experiments` means, if the data were generated from multiple experiments, wouldn’t it be more advisable to upload them individually for fine-grained linking between data and metadata?
4. Related to the above point, it would be nice to provide some examples of real world data and metadata that can be tried out by the users. This should give a user better ideas how she might use `minimo` to manage her own data/metadata.
5. Number of experiments set to `0` seems not allowed, why not remove `0` in the dropdown list?
6. It seems like overwriting an existing folder/file is permitted, should there be a warning before proceeding? It would be good to get confirmation from the user to prevent potential mistakes.
7. It would be good to get confirmation from the user before deleting a metadata form which has been used by many metadata entries since this operation is irreversable and possibley affects large number of entries.
8. Since there is no pagination for listing metadata entries, practically speaking, it would be difficult for the UI to scale up to over hundreds of items. Would it be possible to support listing metadata entries in a table with pagination?
9. Directly exposing MinIO UI via iframe is a quick way to allow users to access data objects managed by MinIO. However, this also comes with some drawbacks. For example, a user may bypass the normal data manipulation route to delete data files without the metadata portion being updated resulting in discrepancies. Also, a user may accidentally overwrite existing data objects without leaving any trace.
10. It would be ideal that the metadata listing table mentioned in point 8 also provides users with access to data files, eg, displaying folder structure of an uploaded entry, offering download links etc, maybe in a popup modal. This way there is no need to expose MinIO UI directly and avoid possible caveats.
11. When a metadata entry is updated using `link existing data with a new metadata entry`, the previous metadata entry still shows up as any others, could this be confusing? If it’s desirable to keep revision history, it would be nice to collapse the two metadata entries with the latest shown by default.
12. I once tried to set up a user with a password, but later forgot the password. It seems there is no password reset functionality, I ended up locking myself out, had to create a new deployment.

**Comment by Borchardt** [comment]
Thanks for your feedback, junjun-zhang. Comments/responses below:

1. Good point; agree. Will be fixed by solution to point 2.
2. We think that this is a good suggestion. I've created [an issue in the tracker](https://github.com/focolab/minimo/issues/32) for this work.
3. We agree that the text here probably needs to change, but we're still discussing what alternative might make the most sense. I've created [an issue in the tracker](https://github.com/focolab/minimo/issues/33) to track this work.
4. We think this sounds like a reasonable update for the docs. I've created [an issue in the tracker](https://github.com/focolab/minimo/issues/34) for this work.
5. Good point, and related to [existing issue #13](https://github.com/focolab/minimo/issues/13) in our issue tracker. I've updated that issue to include removing 0 from the dropdown.
6. Overwrites are currently permitted, we'd prefer that it weren't. I've created [an issue in the tracker](https://github.com/focolab/minimo/issues/35) for disabling them.
7. I don't know that this is a high priority, but I do think that it's a sensible idea. I've created [an issue for the associated work](https://github.com/focolab/minimo/issues/36)
8. Agreed. We have [an existing issue in our tracker](https://github.com/focolab/minimo/issues/10) for this.
9. For the time being (until point 10 is resolved), exposing the MinIO browser is necessary in order to provide the ability for downloads of raw data folders. Some of the reviewer's concerns here may be mitigated once work is completed for point 6, but we are open to moving away from exposing the MinIO browser whenever we no longer have a functional need to do so.
10. Agreed. I've created [an issue to track associated work](https://github.com/focolab/minimo/issues/37).
11. Our point of view here is that maintaining an "inseparable link" between data and metadata means that old (even incorrect) metadata should not be deleted nor hidden. We believe that timestamping of metadata entries provides sufficient versioning, at least for the time being.
12. We appreciate this feedback. I think that it should be possible for anyone with root access to the host machine to wipe the users database without nuking the entire installation; I've created [an issue for adding instructions for doing so](https://github.com/focolab/minimo/issues/38) in our tracker.

**Comment by Borchardt** [comment]
(As an aside: I'm unfamiliar with this review process! If I'm not meant to be responding to these comments, or if there's anything else that I *should* be doing, please let me know, and I will adjust accordingly.)

**Comment by majensen** [comment]
@Borchardt this is awesome, please carry on!

**Comment by majensen** [comment]
I think we're very close now - I will do my final check (proofreading, editorial) this weekend if all goes well. Thanks to all-

**Comment by majensen** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by majensen** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02979/joss.02979/10.21105.joss.02979.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02979/joss.02979/10.21105.joss.02979.pdf) :page_facing_up: :point_left:

**Comment by majensen** [comment]
@Borchardt the paper text looks fine. Can you add examples of the sizes of data objects that you use with minimo now (after "supports very large files")?

I'd like to see some more work towards the usability issues identified by @junjun-zhang. The following tickets are open from your response to Junjun above:

https://github.com/focolab/minimo/issues/32
https://github.com/focolab/minimo/issues/33
https://github.com/focolab/minimo/issues/34
https://github.com/focolab/minimo/issues/35
https://github.com/focolab/minimo/issues/36
https://github.com/focolab/minimo/issues/37
https://github.com/focolab/minimo/issues/38

From these, I think 32, 35, 36, and 38 would be highest priority. What do you think, could you implement these or a subset?
thanks

**Comment by Borchardt** [comment]
@majensen Thanks for your work!

Work for https://github.com/focolab/minimo/issues/38 was actually merged a couple of weeks ago, but I apparently forgot to link and close the issue. I've done so now.

Of the remaining three you highlighted, I think focolab/minimo#35 is probably the highest priority. I'm beginning work for that issue now, and I will aim to have a PR for it in the next couple of days. From there, I'll transition to 32 and then 36. Our lab would prefer that we not block publication for those last two issues, but I will aim to have them completed within the next week regardless.

How does all of that sound?

**Comment by junjun-zhang** [comment]
Sounds like a good plan!

**Comment by Borchardt** [comment]
@majensen quick update: https://github.com/focolab/minimo/issues/35 has been completed, and I've updated the paper per your request.

**Comment by Borchardt** [comment]
@majensen another update: https://github.com/focolab/minimo/issues/32 now also closed!

**Comment by majensen** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02979/joss.02979/10.21105.joss.02979.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02979/joss.02979/10.21105.joss.02979.pdf) :page_facing_up: :point_left:

**Comment by majensen** [comment]
Ok @Borchardt, last thing we need from you is an open archive of the code submitted to Zenodo or similar. There is a little Zenodo tutorial at [this link](https://github.com/openjournals/joss-reviews/issues/1839#issuecomment-560048729). JOSS prefers that the archive title match the paper title, and the archive authors match the paper authors.
Once you have this, can you report the version number and the archive DOI back here? Thanks!

**Comment by Borchardt** [comment]
Awesome! I'll get on this as soon as I've merged the outstanding PR for https://github.com/focolab/minimo/issues/36.

Just double checking: there's no need for me to merge code changes from mainline into our (now outdated) joss branch, correct?

**Comment by majensen** [comment]
Correct

**Comment by Borchardt** [comment]
Okay, done! Thanks for the tutorial link; very helpful! 

DOI: 10.5281/zenodo.4678098
Version number: 44b306957691505bc4f95cdb0721c7e1b03a9e7d

**Comment by majensen** [comment]
@whedon set 10.5281/zenodo.4678098 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4678098" target="_blank">10.5281/zenodo.4678098</a> is the archive.

**Comment by majensen** [comment]
@whedon set 44b306957691505bc4f95cdb0721c7e1b03a9e7d as version

**Comment by whedon** [comment]
OK. 44b306957691505bc4f95cdb0721c7e1b03a9e7d is the version.

**Comment by majensen** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2979 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by majensen** [comment]
@whedon accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2220

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2220, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1381412867145138177) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2221
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02979](https://doi.org/10.21105/joss.02979)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @Borchardt on your article's publication in JOSS!

Many thanks to @bensonml and @junjun-zhang for reviewing this, and @majensen for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02979/status.svg)](https://doi.org/10.21105/joss.02979)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02979">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02979/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02979/status.svg
   :target: https://doi.org/10.21105/joss.02979
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02979/status.svg)](https://doi.org/10.21105/joss.02979)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by majensen** [comment]
@Borchardt congrats! Really appreciate all your work to make this code great. @junjun-zhang, @bensonml  -- as always , thanks

**Comment by Borchardt** [comment]
Thanks for the congratulations, and a huge thanks back to you and our reviewers! Very much appreciate everybody's help in making this happen!
