### ISSUE TITLE
[REVIEW]: Moltres: finite element based simulation of molten salt reactors

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#298]
**Submitting author:** @lindsayad (<a href="http://orcid.org/0000-0002-6988-2123">Alexander Lindsay</a>)
**Repository:** <a href="https://github.com/arfc/moltres" target ="_blank">https://github.com/arfc/moltres</a>
**Version:** v0.1.0
**Editor:** @kyleniemeyer
**Reviewer:** @scopatz
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1137726" target="_blank">10.5281/zenodo.1137726</a>

## Status

[![status](http://joss.theoj.org/papers/463afc20e9cabc04befdf870d44e645e/status.svg)](http://joss.theoj.org/papers/463afc20e9cabc04befdf870d44e645e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/463afc20e9cabc04befdf870d44e645e"><img src="http://joss.theoj.org/papers/463afc20e9cabc04befdf870d44e645e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/463afc20e9cabc04befdf870d44e645e/status.svg)](http://joss.theoj.org/papers/463afc20e9cabc04befdf870d44e645e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/arfc/moltres" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/arfc/moltres">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@lindsayad) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @scopatz it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by scopatz** [comment]
For reference, the link to the "paper", which is really just a summary, is [here](https://github.com/arfc/moltres/blob/devel/paper/paper.pdf). Doxygen pages are [here](https://arfc.github.io/moltres/)

**Comment by scopatz** [comment]
Hi @lindsayad, there doesn't seem to be a conda package for moose. Can you confirm and/or create one? That would be the easiest way for me to verify the installation procedures. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer over at https://github.com/openjournals/joss-reviews/issues/276#issuecomment-310480159 @friedmud volunteered to review as well. Can you use another reviewer?

**Comment by lindsayad** [comment]
I would certainly be appreciated if @friedmud could review. As the creator of MOOSE and a developer of his own MOOSE applications, I think he could give some very helpful feedback...

**Comment by lindsayad** [comment]
@scopatz I will look into/get started on a conda package

**Comment by kyleniemeyer** [comment]
Hi @friedmud, your additional review is absolutely welcome. I believe @scopatz is taking care of checking the boxes above, but it would be great if you also go through each item and ensure you agree that they are satisfied (otherwise mention it here).

**Comment by lindsayad** [comment]
@scopatz So Moltres sits on top of MOOSE which does not do releases nor does it itself have a conda package. I could include MOOSE as a submodule of Moltres. However, MOOSE relies on a lot of dependencies like MPI and PetSc and needs environment variables like MPI_HOME and PETSC_DIR. Current MOOSE installation relies on providing a redistributable package which contains dependencies like MPI and PetSc and then automatically loads module files that modify things like `C_INCLUDE_PATH`, `CPLUS_INCLUDE_PATH`, `MPI_HOME`, `PETSC_DIR`, etc., creating the proper environment for building libmesh, MOOSE, and MOOSE applications. I've spent some time this afternoon with `conda build` and I believe I could eventually re-create the proper environment, but I think it might be kind of a pain.

**Comment by lindsayad** [comment]
@scopatz If it's of interest, and maybe of use for build questions, you can see an example of our automated build and test process [here](https://www.moosebuild.org/job/97233/)

**Comment by scopatz** [comment]
Hi @lindsayad can you please provide a VM or a docker container or something with all of the dependencies.  I know that it is kind of a pain to get all of the dependencies. I don't do moose development, and so I am looking for a way to evaluate Moltres without having to drill down the whole stack myself. Anything you can provide will be most useful.

**Comment by lindsayad** [comment]
Ok, the image is about 5.5 GB, but you can get an image with all the MOOSE dependencies installed as well as an already built moltres if it's needed for any reason. You can get it by running
```
docker pull lindsayad/moltres
```

**Comment by katyhuff** [comment]
@scopatz , just wanted to check in about whether the docker image has worked for you -- it should get you to running the tests in no time. Thanks so much for being willing to review!

**Comment by scopatz** [comment]
Hi @lindsayad - I am now seeing this:

```
scopatz@artemis ~ $ docker pull lindsayad/moltres
Using default tag: latest
Error response from daemon: repository lindsayad/moltres not found: does not exist or no pull access
```

Please advise.

**Comment by lindsayad** [comment]
I gave you bad information. Instead do:
```bash
docker pull lindsayad/moose
```
and then once you're in an interactive terminal:
```
su - moose-user
```

**Comment by lindsayad** [comment]
You should then be able to 
```
cd ~/projects/moltres
./run_tests -j8
```

**Comment by scopatz** [comment]
> References: Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

The Moose reference does not list a DOI

**Comment by scopatz** [comment]
> Have the functional claims of the software been confirmed?

How do I actually run the example? This is not presented anywhere in the documentation.

> Have any performance claims of the software been confirmed?

likewise can you please give an example of how to run with parallelism

**Comment by scopatz** [comment]
> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

Similarly, there is no full walkthrough of inputs to results that I could find. The [example input](http://arfc.github.io/software/moltres/wiki/input_example/) page isn't enough for me to run the problem and there are no results to verify against

**Comment by scopatz** [comment]
> Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?

Most of the API lacks any form of in-line documentation that is translated to doxygen. 

Also, the API docs are not clearly labeled as such on the website. Instead, it says that the, "Doxygen pages are here." This requires that the user have a priori knowledge that doxygen is a tool for producing documentation

**Comment by scopatz** [comment]
Hi @lindsayad, sorry it took me so long to get to the review!  Please let me know if/when you have a chance to get to the issues I have brought up above. Thanks!

**Comment by lindsayad** [comment]
@scopatz Are you looking for existing simulation results or experimental results to compare against?

**Comment by scopatz** [comment]
@lindsayad - I am looking for an input file that contains physical variables that I can adjust and then see its physical effect on some output quantity.

**Comment by kyleniemeyer** [comment]
To avoid any potential (or the appearance of) conflict of interest, I'd like to find a second reviewer for this submission—not necessarily someone in the domain, but mainly someone quite familiar with C++. @jochym @dvalters @pragyansmita @hugoledoux would any of you be interested in providing a second review?

(@scopatz you are doing fine, keep doing your thing 😄)

**Comment by dvalters** [comment]
@kyleniemeyer I can give it a second review if domain-specific knowledge is not required.

**Comment by kyleniemeyer** [comment]
@dvalters excellent, thanks! Even though @scopatz checked off items in the checklist, please check whether all items are satisfied from your perspective.

**Comment by lindsayad** [comment]
@scopatz I've updated our [home wiki page](http://arfc.github.io/software/moltres/) so that API docs are clearly labeled as such, instead of "Doxygen page". I've also added a significant amount of content to our [example](http://arfc.github.io/software/moltres/wiki/input_example/) which describes how to actually run the example, where you can compare to some example output, and what some variables are that you can tune and what you might expect their effect to be. I'll be working on our API documentation next.

**Comment by lindsayad** [comment]
Oops, realized I haven't updated the docker container yet. I'll do that and then report back

**Comment by scopatz** [comment]
Thanks for continuing to work on this @lindsayad! I look forward to trying the new example

**Comment by lindsayad** [comment]
Docker container finally updated. Access through:
```
docker pull lindsayad/moose:0.2.0
```

**Comment by kyleniemeyer** [comment]
Hi @scopatz, any luck trying the new example?

**Comment by katyhuff** [comment]
Ping.

**Comment by kyleniemeyer** [comment]
@katyhuff pong!

**Comment by kyleniemeyer** [comment]
Hi @scopatz, did you have a chance to complete/continue your review?

**Comment by scopatz** [comment]
Alright, sorry for the delay. I think that this is good to go, from my perspective.  Thanks for fixing this up @lindsayad!

**Comment by dvalters** [comment]
I am nearly finished with the 2nd review - apologies for delay, will complete today - don't foresee any problems though, agree with @scopatz's review.

**Comment by kyleniemeyer** [comment]
@dvalters no worries, thanks! Just let me know when you are finished.

**Comment by dvalters** [comment]
@kyleniemeyer Sorry - all done now! I am happy it meets all the requirements and agree with @scopatz's review. A well put together piece of software 🙂

**Comment by kyleniemeyer** [comment]
thanks @dvalters!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
Hi @lindsayad @katyhuff, my only remaining comment is that the article is a bit short, and is missing some of the aspects we normally look for (http://joss.theoj.org/about#author_guidelines)

It's only about 100 words right now (we expect more like 250–1000), and the only citations are to the software itself (which isn't really necessary/appropriate, since the article and software are already associated) and then the MOOSE software. However, are there MOOSE-related publications that could be cited that describe the theory behind it? Are there articles that have used Moltres that you can cite, or those that describe the theory better?

The article could also better describe example uses/applications.

There are a number of good examples, but one I recommend you take a look at is PyGBe-LSPR (http://joss.theoj.org/papers/10.21105/joss.00306).

**Comment by lindsayad** [comment]
Hi Kyle, I should be able to get to this next week. Thanks!

**Comment by lindsayad** [comment]
@kyleniemeyer I've fleshed out our article a bit more, so hoping it's ready to go!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00298/joss.00298/10.21105.joss.00298.pdf
```

**Comment by kyleniemeyer** [comment]
Hi @lindsayad, it looks like the `kophazi_development_2009` reference is missing the DOI, and the `moltres` reference also seems incomplete. (If the latter is accepted, perhaps update the year to 2018?)

**Comment by lindsayad** [comment]
What do you mean by incomplete? I can't provide a volume or issue number since it hasn't been published yet. I've updated the year (since it will be published in 2018 -> good catch!). Should I just not have that reference?

**Comment by lindsayad** [comment]
Kophazi reference has been updated with DOI

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00298/joss.00298/10.21105.joss.00298.pdf
```

**Comment by kyleniemeyer** [comment]
Hi @lindsayad, ok, got it, I didn't realize at first that the `moltres` reference was something submitted.

If it hasn't yet been accepted in the journal, it's probably not appropriate to include the journal name. Instead, perhaps replace the journal name with "in review"? Also, is there a preprint link you could share? If so, it might be good to change the reference type to `misc` and add that link in the `howpublished` field.

**Comment by lindsayad** [comment]
It has been accepted. I just finished reviewing the proofs. But not published yet. Hmm good thought on the preprint. We didn't submit to arxiv but probably should anyways. Would you prefer that to the accepted but not yet published reference?

**Comment by kyleniemeyer** [comment]
@lindsayad Ah, ok. Since it's been accepted, then it's fine to include the journal name. It's up to you if you want to submit to arXiv, but if you do, then you could add the link (once it's available).

I'm fine to accept this now, but it's up to you (and @katyhuff) if you want to add an arXiv link, or even wait for the DOI to become available.

**Comment by lindsayad** [comment]
I'm ready to be done but I'll let @katyhuff sign off first

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/eb1a2ea1-7c1f-4a92-abdb-e89cdc52edfd-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)

**Comment by arfon** [comment]
@lindsayad - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by lindsayad** [comment]
Yes, the DOI should be 10.5281/zenodo.887941

**Comment by lindsayad** [comment]
Ok, our article was actually published this morning, so if it's not too
late, I've updated our bibliography with its DOI and publication
information.

**Comment by katyhuff** [comment]
@lindsay , you'll need to update the zenodo.

**Comment by lindsayad** [comment]
Updated DOI for the moltres repo: 10.5281/zenodo.1137726

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1137726 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1137726" target="_blank">10.5281/zenodo.1137726</a> is the archive.

**Comment by arfon** [comment]
@scopatz - many thanks for your review here and to @kyleniemeyer for editing this one ✨ 

@lindsayad - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00298 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00298/status.svg)](https://doi.org/10.21105/joss.00298)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00298/status.svg)](https://doi.org/10.21105/joss.00298)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html

**Comment by kyleniemeyer** [comment]
hey @lindsayad @arfon looks like the DOI in that new reference got messed up—it looks like "https://doi.org/https://doi.org/10.1016/j.anucene.2017.12.025"

**Comment by arfon** [comment]
@kyleniemeyer @lindsayad - this PR fixes the issue. The paper template expects 'bare' DOIs, i.e. without the full URL: https://github.com/arfc/moltres/pull/61

**Comment by arfon** [comment]
I've updated the paper based on https://github.com/arfc/moltres/pull/61. It might take a while before it looks fixed on the JOSS site as the papers are served from a content distribution network (CDN).
