### ISSUE TITLE
[PRE REVIEW]: KALMUS: tools for color analysis of films

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2980]
**Submitting author:** @yc015 (<a href="http://orcid.org/0000-0002-4018-6095">Yida Chen</a>)
**Repository:** <a href="https://github.com/KALMUS-Color-Toolkit/KALMUS" target ="_blank">https://github.com/KALMUS-Color-Toolkit/KALMUS</a>
**Version:** v.1.3.5
**Editor:** @gkthiruvathukal
**Reviewers:** @thomakra, @elektrobohemian
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @yc015. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @gkthiruvathukal.

@yc015 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02980/joss.02980/10.21105.joss.02980.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02980/joss.02980/10.21105.joss.02980.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=39.63 s (0.7 files/s, 134.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          25            851           1491           2633
Markdown                         2             67              0            155
TeX                              1             22              0            125
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            29            940           1491           2914
-------------------------------------------------------------------------------


Statistical information for the repository 'f889ccc089eeda69fb87e97c' was
gathered on 2021/01/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Yida Chen                       21          7499           2524          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Yida Chen                  4975           66.3          2.2               15.80
```

**Comment by kthyng** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by kthyng** [comment]
(@gkthiruvathukal having already agreed elsewhere!)

**Comment by gkthiruvathukal** [comment]
@yc015 Can you please look through the list of reviewers and suggest 3-4 IDs? (without the @ symbol, please)

**Comment by yc015** [comment]
@gkthiruvathukal Hello Prof. Thiruvathukal! My suggested reviewers are Editor Arfon Smith (arfon), Juan Nunez-Iglesias (jni), and Lorena Mesa (lorenanicole). The reviewers' GitHub IDs are in the parentheses. 

Thank you so much for checking these!

**Comment by gkthiruvathukal** [comment]
@yc015, thanks for the nice greeting! Can I ask you to add a couple more who are not on the editorial board or EICs?  I'm only asking that because our board in general is facing heavy workload now. (I personally am interested in this topic, since it has a nice overlap with Digital Humanities, one of my areas of interest.

**Comment by yc015** [comment]
@gkthiruvathukal That's very understandable, and thank you for your interest in our topic! The additional reviewers that I would suggest are stsievert, tuelwer, Atif-Anwer, and thomakra. They are not on the editorial board or EICs. Thanks again!

**Comment by gkthiruvathukal** [comment]
@stsievert and @thomakra, are you willing to contribute a review for this JOSS submission?

@yc015 Many apologies for the delay in following up on your suggestions!

**Comment by stsievert** [comment]
Thanks for the request! I'm afraid I'll have to decline this review – my bandwidth is unfortunately limited.

I have briefly glanced at the code. I would recommend reviewing the JOSS reviewer guidelines and improving the documentation.

**Comment by gkthiruvathukal** [comment]
@stsievert I know the feeling about limited bandwidth. You've already done such a nice job of giving feedback. I occasionally have to explain this to reviewers: *Any* feedback is helpful to help improve a submission, and we work with your schedule to complete your review. COVID-19 has put all of us under major strain, so what's the hurry? Given that you offered comments, I do sense some interest. It would be great to have you on board!

I'm interpreting your response as "not available" but I am happy with slow progress vs. no progress. 👍🏾  Please follow up to let me know. I'll respect your final answer.

**Comment by stsievert** [comment]
I think "not available" is accurate – I'm not seeing how I'll be able to find the time required.

**Comment by gkthiruvathukal** [comment]
Thanks, @stsievert! Appreciate your initial input.

@yc015 I still don't have any reviewers, but I see the documentation issue reported by @stsievert as a blocker here. Can you please work to address this right away? And please suggest other reviewers from our reviewer list.

**Comment by yc015** [comment]
@gkthiruvathukal Thank you! Yes, I will work on improving the API documentation and other items. I will notice you when these have been done. @stsievert Thank you so much for your comments!

**Comment by thomakra** [comment]
Hei George,

Sorry for the late reply. I also have very limited time these days, but
since you say you are happy with slow progress I can try to have a look
over the coming few weeks.

-Thomas-

**Comment by gkthiruvathukal** [comment]
@thomakra Great, I will assign you and see if I can get a second reviewer. So it might take a little while to get things going anyway.

**Comment by gkthiruvathukal** [comment]
@whedon assign @thomakra as reviewer

**Comment by whedon** [comment]
OK, @thomakra is now a reviewer

**Comment by gkthiruvathukal** [comment]
@yc015 Can you please suggest a few more possible reviewers from our reviewer list? Thanks!

**Comment by yc015** [comment]
@gkthiruvathukal  Sorry for being so late in giving out my suggestions. I would suggest dr-xenia, hanayik, macrocosme, and adamltyson as potential reviewers for our submission. @thomakra Thank you so much for your time reviewing our work! Also, thank stsievert again for his great comment, I have improved the documentation and software repo in general over the past two weeks.

**Comment by gkthiruvathukal** [comment]
@dr-xenia Are you willing to contribute a review for this JOSS submission?

**Comment by yc015** [comment]
@gkthiruvathukal Hello! Just in case that dr-xenia also has a tight schedule, I would suggest elektrobohemian and macrocosme for reviewing our submission. Thank you!

**Comment by gkthiruvathukal** [comment]
@yc015 Thank you. Even things got insanely busy over there. Apologies for the delay in following up.

@elektrobohemian or @macrocosme, just wondering whether either of you can help review this JOSS submission? I think I have asked macrocosme recently but perhaps your workload has eased up a bit now!

Please let me know so I can get review started.

**Comment by elektrobohemian** [comment]
I could step in if the don't start a new shutdown in Germany after Easter holidays. But I will not be done before the end of April as the semester starts next week...

**Comment by macrocosme** [comment]
Thank you for the suggestion @gkthiruvathukal. While it seems like an interesting project, I unfortunately have no time available for this task at the moment.

**Comment by gkthiruvathukal** [comment]
@elektrobohemian  I'm more than happy to work with your schedule/timeframe. We continue to operate in a scenario where we have to assume everything takes longer with COVID-19. I read about the situation in Germany. If I can interpret your response as a "yes", I would like to assign you wait for your review.

**Comment by yc015** [comment]
@gkthiruvathukal  Good Afternoon! I just wonder if there are more suggestions needed from me, or we are still awaiting the responses from invited reviewers.

**Comment by gkthiruvathukal** [comment]
@yc015 I'm going to assume @elektrobohemian will be able to do the review. Just keep in mind, we will be working at slower speed in general. I was waiting for the response but am going to assume that the review may not be completed until May (may ... May!)

Starting review now.

**Comment by gkthiruvathukal** [comment]
@whedon add @elektrobohemian as reviewer

**Comment by whedon** [comment]
OK, @elektrobohemian is now a reviewer

**Comment by gkthiruvathukal** [comment]
@elektrobohemian I'm assuming you are willing as long as we give you enough time. We'll work with your schedule!

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3156.
