### ISSUE TITLE
[PRE REVIEW]: CLAIRE: Constrained Large Deformation Diffeomorphic Image Registration on Parallel Computing Architectures

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2981]
**Submitting author:** @andreasmang (<a href="http://orcid.org/0000-0003-4605-3290">Andreas Mang</a>)
**Repository:** <a href="https://github.com/andreasmang/claire" target ="_blank">https://github.com/andreasmang/claire</a>
**Version:** v0.07
**Editor:** @mjsottile
**Reviewers:** @tjasaki, @NMontanaBrown
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @andreasmang. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jedbrown.

@andreasmang if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.22 s (111.2 files/s, 44206.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             44           8821           6972          27289
C/C++ Header                    48           1464           1122           3491
Bourne Shell                    14            330            317           1504
CMake                           14            165            418            989
Markdown                         9            180              0            407
TeX                              1             33              4            235
make                             3             40              7            180
Python                           1             17              7             60
YAML                             2              0              0              5
-------------------------------------------------------------------------------
SUM:                           136          11050           8847          34160
-------------------------------------------------------------------------------


Statistical information for the repository '7476d2e411db803dcb6cc62e' was
gathered on 2021/01/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Amir Gholami                     1             1              0            0.00
Andreas Mang                   588         94954          44608           91.03
James Herring                    5           765             91            0.56
MalteBrunn                       2           228           6005            4.07
Naveen Himthani                 21          4087           1328            3.53
brunnme                          1             6              0            0.00
naveenaero                       4          1241              6            0.81

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Amir Gholami                  1          100.0         33.8                0.00
Andreas Mang              46628           49.1         38.5               22.07
James Herring               702           91.8         20.0               16.10
MalteBrunn                  234          102.6         16.0                2.14
Naveen Himthani              13            0.3         14.5               15.38
naveenaero                 1673          134.8          9.6                6.81
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02981/joss.02981/10.21105.joss.02981.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02981/joss.02981/10.21105.joss.02981.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@poulson would you be able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @poulson as editor

**Comment by whedon** [comment]
@poulson has been invited to edit this submission.

**Comment by kthyng** [comment]
@andreasmang please look through your paper as it is shown above and correct the references. Many have parentheses when they should not.

**Comment by danielskatz** [comment]
@whedon invite @poulson as editor

just another ping to @poulson on this...

**Comment by whedon** [comment]
@poulson has been invited to edit this submission.

**Comment by jedbrown** [comment]
I can take this if Jack is conflicted (though I can't promise to be fast -- I'm pretty swamped).

@andreasmang I don't see any automated tests and the docs seem hard to navigate (though I'm not the target audience) to understand how to prepare data, assess quality, and contribute. Please consider adding GitHub Actions or other automated tests, as well as [recommended community docs](https://github.com/andreasmang/claire/community).

**Comment by danielskatz** [comment]
Thanks for volunteering @jedbrown - let's see what @poulson says

**Comment by danielskatz** [comment]
@jedbrown - if you are still willing to edit, can you assign yourself, or let me know and I will do so

**Comment by andreasmang** [comment]
> @andreasmang please look through your paper as it is shown above and correct the references. Many have parentheses when they should not.

@kthying Sorry for the late response. I was assuming I get notified by email once there is any action required. I have fixed the references in the CLAIRE repo.

**Comment by andreasmang** [comment]
> I can take this if Jack is conflicted (though I can't promise to be fast -- I'm pretty swamped).
> 
> @andreasmang I don't see any automated tests and the docs seem hard to navigate (though I'm not the target audience) to understand how to prepare data, assess quality, and contribute. Please consider adding GitHub Actions or other automated tests, as well as [recommended community docs](https://github.com/andreasmang/claire/community).

@jedbrown Thanks for your recommendation. I will look into your suggestions and update the documentation. I'll ping you once I believe we have addressed everything you have brought to my attention...

**Comment by kthyng** [comment]
> @kthying Sorry for the late response. I was assuming I get notified by email once there is any action required. I have fixed the references in the CLAIRE repo.

You'll just be getting github pings, so I'd recommend changing your github email notifications so that you are emailed when you are pinged here.

**Comment by andreasmang** [comment]
> > @kthying Sorry for the late response. I was assuming I get notified by email once there is any action required. I have fixed the references in the CLAIRE repo.
> 
> You'll just be getting github pings, so I'd recommend changing your github email notifications so that you are emailed when you are pinged here.

@kthyng Thanks for pointing this out. The problem was that notifications went to the address of my old affiliation (which is no longer active). No I should be good to go...

**Comment by kyleniemeyer** [comment]
Hi @jedbrown, could you edit this?

**Comment by jedbrown** [comment]
I'd love to, but I'm just ridiculously overcommitted. Today was like a parody of two-parent work-from-home with sick kids and my experience of the past 11 months is that it won't get better in the near future so I'm afraid I have to decline at this time. If nobody else is available, I can reassess in a month or two.

**Comment by kyleniemeyer** [comment]
@jedbrown understood, no problem.

@jni could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @jni as editor

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02981/joss.02981/10.21105.joss.02981.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02981/joss.02981/10.21105.joss.02981.pdf) :page_facing_up: :point_left:

**Comment by jni** [comment]
@kyleniemeyer I'm sorry, I too am a little too overwhelmed this month. 🙏

**Comment by arfon** [comment]
@whedon invite @mjsottile as editor

:wave: @mjsottile - any chance you could take this submission for us too?

**Comment by whedon** [comment]
@mjsottile has been invited to edit this submission.

**Comment by mjsottile** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mjsottile** [comment]
@whedon assign @tjasaki as reviewer

**Comment by whedon** [comment]
OK, @tjasaki is now a reviewer

**Comment by mjsottile** [comment]
:wave: @NMontanaBrown Would you be interested in providing a review for this JOSS submission?  It appears to be in the vicinity of your areas of expertise.

**Comment by NMontanaBrown** [comment]
Hi @mjsottile, indeed it is. I can provide a review.

**Comment by mjsottile** [comment]
@whedon add @NMontanaBrown as reviewer

**Comment by whedon** [comment]
OK, @NMontanaBrown is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3038.
