### ISSUE TITLE
[PRE REVIEW]: contagion: A Python package for node immunization and stochastic epidemic simulation on networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2982]
**Submitting author:** @lucasmccabe (<a href="http://orcid.org/0000-0001-7822-028X">Lucas McCabe</a>)
**Repository:** <a href="https://github.com/lucasmccabe/contagion.git" target ="_blank">https://github.com/lucasmccabe/contagion.git</a>
**Version:** v1.3.3
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lucasmccabe. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @pdebuyl.

@lucasmccabe if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (306.8 files/s, 23652.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            216            586            738
Markdown                         3             78              0            223
reStructuredText                21            238            219            128
TeX                              1              3              0             38
DOS Batch                        1              8              1             26
YAML                             2              3              0             19
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            33            550            813           1181
-------------------------------------------------------------------------------


Statistical information for the repository '5f6fa79f0a7c7a2a75506675' was
gathered on 2021/01/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Lucas                           28          1944            404          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Lucas                      1540           79.2          1.0               10.91
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02982/joss.02982/10.21105.joss.02982.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02982/joss.02982/10.21105.joss.02982.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.3993314 is OK

MISSING DOIs

- 10.1016/j.epidem.2019.03.002 may be a valid DOI for title: Efficient vaccination strategies for epidemic control using network information
- 10.1371/journal.pone.0083489 may be a valid DOI for title: An efficient immunization strategy for community networks
- 10.1007/s13278-014-0213-5 may be a valid DOI for title: Influence of vaccination strategies and topology on the herd immunity of complex networks

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @lucasmccabe! I have triggered an editorial board check on your submission because the size is borderline for being in scope. This should take a week or two. Thanks.

**Comment by danielskatz** [comment]
👋 @lucasmccabe - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

Also, one editor commented that some of the algorithms and science did not appear have proper citations.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by lucasmccabe** [comment]
Understood. Thank you for your time and consideration.
