### ISSUE TITLE
[PRE REVIEW]: UltraNest - a robust, general purpose Bayesian inference engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2983]
**Submitting author:** @JohannesBuchner (<a href="http://orcid.org/0000-0003-0426-6634">Johannes Buchner</a>)
**Repository:** <a href="https://github.com/JohannesBuchner/UltraNest/" target ="_blank">https://github.com/JohannesBuchner/UltraNest/</a>
**Version:** 3.2.0
**Editor:** @fboehm
**Reviewers:** @mattpitkin, @ziatdinovmax
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JohannesBuchner. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@JohannesBuchner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=5.06 s (33.6 files/s, 5346.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          57           2476           3271          10644
JavaScript                      15            311            187           2143
JSON                            53              0              0           1015
Jupyter Notebook                10              0           3097            866
reStructuredText                12            376            189            771
Cython                           1            173            303            491
SVG                              1              0              0            148
make                             7             57              7            142
HTML                             3              0              3             84
YAML                             2             14              1             36
C++                              1              7              0             35
INI                              1              8              3             31
C                                1              6              6             29
DOS Batch                        1              8              1             27
Fortran 90                       1              4              6             23
Julia                            1              5              0             17
R                                1              7              2             17
Markdown                         2              7              0             15
-------------------------------------------------------------------------------
SUM:                           170           3459           7076          16534
-------------------------------------------------------------------------------


Statistical information for the repository 'ab0178b80b8ea6dbf348dfc7' was
gathered on 2021/01/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Johannes Buchner               297         31260          12007          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Johannes Buchner          19115           61.1         14.6               10.39
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2983 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@whedon generate pdf from joss-paper

**Comment by kthyng** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2983 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02983/joss.02983/10.21105.joss.02983.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02983/joss.02983/10.21105.joss.02983.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@fboehm would this fall under your statistical background?

**Comment by kthyng** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by kthyng** [comment]
@JohannesBuchner Your paper is too long. Please check out our [paper requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) and trim yours down where possible.

**Comment by fboehm** [comment]
Yes, @kthyng, this looks like a good fit for me. I'm excited to edit it!

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by mattpitkin** [comment]
@fboehm I'm happy to review this.

**Comment by fboehm** [comment]
Thank you, @mattpitkin !

**Comment by fboehm** [comment]
@whedon assign @mattpitkin as reviewer

**Comment by whedon** [comment]
OK, @mattpitkin is now a reviewer

**Comment by fboehm** [comment]
@mattpitkin - I'm still finding a second reviewer. Once I do that, we can officially start the review. Thanks again!

**Comment by JohannesBuchner** [comment]
Thanks @kthyng. The updated text should be now 994 words.

@whedon generate pdf

**Comment by fboehm** [comment]
@jordigh - would you be willing to review this submission for the Journal of Open Source Software?

**Comment by 1313e** [comment]
@fboehm If needed, I would be willing to review this submission.

**Comment by fboehm** [comment]
@whedon add @ziatdinovmax as reviewer

**Comment by whedon** [comment]
OK, @ziatdinovmax is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3001.
