### ISSUE TITLE
[PRE REVIEW]: Bayesian X-ray Analysis (BXA) v4.0

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2984]
**Submitting author:** @JohannesBuchner (<a href="http://orcid.org/0000-0003-0426-6634">Johannes Buchner</a>)
**Repository:** <a href="https://github.com/JohannesBuchner/BXA" target ="_blank">https://github.com/JohannesBuchner/BXA</a>
**Version:** v4.0.2
**Editor:** @jgostick
**Reviewers:** @cescalara, @grburgessas, @cescalara
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JohannesBuchner. **Currently, there isn't an JOSS editor assigned** to your paper.

@JohannesBuchner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2984 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=8.34 s (10.7 files/s, 47060.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                            12              0              0         383161
Python                          42           1052           1203           5275
reStructuredText                23            480            224            798
YAML                             2             13             18            208
make                             2             27              6             88
Bourne Shell                     6             24             13             56
XML                              1              9              0             20
Dockerfile                       1             11              1             14
-------------------------------------------------------------------------------
SUM:                            89           1616           1465         389620
-------------------------------------------------------------------------------


Statistical information for the repository '4ad1fad8b4c7dc2af0714b89' was
gathered on 2021/01/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Brian Refsdal                    8          3223            305           13.24
Johannes Buchner               143         16817           6303           86.75
Liu Teng                         1             1              1            0.01
ruizca                           1             1              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Brian Refsdal                 5            0.2        121.2               20.00
Johannes Buchner           7525           44.7         42.4               10.71
Liu Teng                      1          100.0          2.7                0.00
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02984/joss.02984/10.21105.joss.02984.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02984/joss.02984/10.21105.joss.02984.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201322971 is OK
- 10.1111/j.1365-2966.2009.14548.x is OK
- 10.1117/12.447161 is OK
- 10.1063/1.1835238 is OK
- 10.1086/339856 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @jgostick - would you be able to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @jgostick as editor

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by jgostick** [comment]
A have sent review invitations to several people and got no reply, so am send out a new batch of invites.  Sorry for the delay.  Suggested reviewers would be welcome.

**Comment by JohannesBuchner** [comment]
Here are some highly qualified people who know X-rays and statistics and software packaging, but I don't know if they can donate time to be reviewers: @dhuppenkothen @cescalara @giacomov @grburgess and perhaps [stingray contributors](https://github.com/StingraySoftware/stingray/blob/main/CREDITS.rst).

**Comment by jgostick** [comment]
@whedon add @cescalara as reviewer

**Comment by whedon** [comment]
OK, @cescalara is now a reviewer

**Comment by jgostick** [comment]
@whedon add @grburgessas reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by jgostick** [comment]
@whedon add @grburgessas as reviewer

**Comment by whedon** [comment]
OK, @grburgessas is now a reviewer

**Comment by jgostick** [comment]
@whedon add @cescalara as reviewer

**Comment by whedon** [comment]
OK, @cescalara is now a reviewer

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3045.
