### ISSUE TITLE
[PRE REVIEW]: Nanoq: fast quality control for nanopore reads

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2985]
**Submitting author:** @esteinig (<a href="http://orcid.org/0000-0001-5399-5353">Eike J. Steinig</a>)
**Repository:** <a href="https://github.com/esteinig/nanoq" target ="_blank">https://github.com/esteinig/nanoq</a>
**Version:** v0.2.1
**Editor:** @luizirber
**Reviewers:** @natir, @bovee
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @esteinig. **Currently, there isn't an JOSS editor assigned** to your paper.

@esteinig if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (62.6 files/s, 12516.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rust                             1            286             68            912
Markdown                         2            105              0            263
TeX                              1              5              0            151
Python                           1             19              0             50
Bourne Shell                     2             21             14             48
YAML                             1              7              1             23
TOML                             1              1              0             22
Dockerfile                       1              1              0              2
-------------------------------------------------------------------------------
SUM:                            10            445             83           1471
-------------------------------------------------------------------------------


Statistical information for the repository '7fe1ce2336d1411bae980a5b' was
gathered on 2021/01/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
esteinig                        22           109             40          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
esteinig                     69           63.3          0.0                1.45
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btv573 is OK
- 10.1016/S1473-3099(20)30562-4 is OK
- 10.1093/bioinformatics/bty149 is OK
- 10.1038/nbt.4060 is OK
- 10.1093/gigascience/giz043 is OK
- 10.1093/bioinformatics/bty654 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02985/joss.02985/10.21105.joss.02985.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02985/joss.02985/10.21105.joss.02985.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@esteinig - given the relatively small size of this submission, the editors will now discuss if it meet the JOSS [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review. You should hear back about the next steps in 1-2 weeks.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
We'll go ahead with the review

**Comment by danielskatz** [comment]
@whedon assign @luizirber as editor

thanks @luizirber !!

**Comment by whedon** [comment]
OK, the editor is @luizirber

**Comment by esteinig** [comment]
Thanks @danielskatz for going ahead with review and @luizirber for editing. I'm not too familiar with the reviewers, but suppose anyone with `Rust` and bioinformatics background might be helpful?

* holtgrewe
* will-rowe
* lskatz
* natir
* k3yavi
* Gab0
* kblin
* martinmodrak
* bovee
* HadrienG

**Comment by luizirber** [comment]
Thanks for the reviewers suggestions, @esteinig!

I'll start by pinging @bovee (as author of needletail) and @natir (since I know he has experimented with nanopore data before). Are you two willing to review `nanoq`?

**Comment by esteinig** [comment]
Thanks for that, please let me know if there is anything that can be improved / optimised. It was our first foray into Rust, and the processing speed of the libaries is exceptional, even without much optimisation. 

NB: Mean error function for read scores is costly at each iteration, but couldn't think of any faster way to implement it.

**Comment by natir** [comment]
Hello everyone, thanks @luizirber to suggest me as reviewer. I accept review this paper.

**Comment by luizirber** [comment]
@whedon assign @natir as reviewer

**Comment by whedon** [comment]
OK, @natir is now a reviewer

**Comment by bovee** [comment]
Hi, also happy to review!

**Comment by luizirber** [comment]
@whedon add @bovee as reviewer

**Comment by whedon** [comment]
OK, @bovee is now a reviewer

**Comment by luizirber** [comment]
Great, let's get this party started!

**Comment by luizirber** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2991.
