### ISSUE TITLE
[PRE REVIEW]: covid19.analytics: An R Package to Obtain, Analyze and Visualize Data from the 2019 Corona Virus Disease Pandemic

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2986]
**Submitting author:** @mponce0 (<a href="http://orcid.org/0000-0001-5850-7240">Marcelo Ponce</a>)
**Repository:** <a href="https://github.com/mponce0/covid19.analytics/" target ="_blank">https://github.com/mponce0/covid19.analytics/</a>
**Version:** v2.0
**Editor:** @fboehm
**Reviewers:** @LogIN-, @JDRomano2
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mponce0. **Currently, there isn't an JOSS editor assigned** to your paper.

@mponce0 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by mponce0** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2986 with the following error: 

 Can't find any papers to compile :-(

**Comment by mponce0** [comment]
@whedon generate pdf from branch literature

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch literature. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02986/joss.02986/10.21105.joss.02986.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02986/joss.02986/10.21105.joss.02986.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch literature

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch literature
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/S1473-3099(20)30120-1 is OK
- 10.1093/nar/gkx1095 is OK
- 10.1145/3332186.3332195 is OK
- 10.1038/d41586-020-01541-z is OK
- 10.1038/s41591-020-0820-9 is OK
- 10.1038/s41579-020-0394-z is OK
- 10.1038/d41586-020-01449-8 is OK
- 10.1038/s41586-020-2012-7 is OK
- 10.1038/s41564-020-0771-4 is OK
- 10.1038/d41586-020-01403-8 is OK
- 10.1038/s41577-020-0348-8 is OK
- 10.1038/s41586-020-2521-4 is OK
- 10.1038/s41591-020-0968-3 is OK
- 10.1038/s41577-020-0319-0 is OK
- 10.1038/d41586-020-01394-6 is OK
- 10.1038/s41562-020-0911-0 is OK
- 10.1038/d41586-020-01520-4 is OK
- 10.1038/s42256-020-0184-3 is OK
- 10.1038/s42256-020-0185-2 is OK
- 10.1126/scitranslmed.abc1126 is OK
- 10.1063/5.0008834 is OK
- 10.1038/d41586-020-01685-y is OK
- 10.1038/d41586-020-01003-6 is OK
- 10.1038/s41562-020-0898-6 is OK
- 10.1038/d41586-020-01695-w is OK
- 10.1038/s41597-020-0524-5 is OK
- 10.1038/s41577-020-0323-4 is OK
- 10.1038/s41596-020-0358-9 is OK
- 10.1371/journal.pone.0236307 is OK

MISSING DOIs

- 10.1002/wics.1212 may be a valid DOI for title: The Comprehensive R Archive Network
- 10.1201/9780429447273 may be a valid DOI for title: Interactive Web-Based Data Visualization with R, plotly, and shiny
- 10.7287/peerj.preprints.3179v2 may be a valid DOI for title: rentrez: an R package for the NCBI eUtils API
- 10.1093/bioinformatics/bty633 may be a valid DOI for title: ape 5.0: an environment for modern phylogenetics and evolutionary analyses in R
- 10.32388/uq8dyz may be a valid DOI for title: National Center for Biotechnology Information
- 10.1073/pnas.2009033117 may be a valid DOI for title: Timing social distancing to avert unmanageable COVID-19 hospital surges

INVALID DOIs

- https://doi.org/10.1016/j.amc.2014.03.030 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cell.2020.06.043 is INVALID because of 'https://doi.org/' prefix
```

**Comment by arfon** [comment]
Cloc output from local machine:

```
arfon@mawr ~ $ cloc covid19.analytics/
      70 text files.
      64 unique files.                              
      40 files ignored.

github.com/AlDanial/cloc v 1.86  T=0.54 s (57.1 files/s, 22835.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               21           1186           2098           3738
HTML                             5            438              0           3429
Markdown                         1            295              0           1099
YAML                             2             19             21             24
Bourne Shell                     1              8              6             18
Rmd                              1              3             14              4
-------------------------------------------------------------------------------
SUM:                            31           1949           2139           8312
-------------------------------------------------------------------------------
```

**Comment by danielskatz** [comment]
👋  @mponce0 - if you can remove the entries in the .bib file that are not actually being used, that will help reduce the potential problems that check references found.

**Comment by danielskatz** [comment]
👋 @fboehm - you were suggested as the editor - are you able to take this on?

**Comment by danielskatz** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by fboehm** [comment]
I'd be delighted :)

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by mponce0** [comment]
@whedon generate pdf from branch literature
@whedon check references from branch literature

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch literature. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02986/joss.02986/10.21105.joss.02986.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02986/joss.02986/10.21105.joss.02986.pdf) :page_facing_up: :point_left:

**Comment by mponce0** [comment]
@whedon check references from branch literature

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch literature
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1201/9780429447273 is OK
- 10.7287/peerj.preprints.3179v2 is OK
- 10.1093/bioinformatics/bty633 is OK
- 10.1016/S1473-3099(20)30120-1 is OK
- 10.1093/nar/gkx1095 is OK
- 10.1145/3332186.3332195 is OK
- 10.1016/j.amc.2014.03.030 is OK
- 10.1038/d41586-020-01541-z is OK
- 10.1038/s41591-020-0820-9 is OK
- 10.1038/s41579-020-0394-z is OK
- 10.1038/d41586-020-01449-8 is OK
- 10.1038/s41586-020-2012-7 is OK
- 10.1038/s41564-020-0771-4 is OK
- 10.1038/d41586-020-01403-8 is OK
- 10.1038/s41577-020-0348-8 is OK
- 10.1038/s41586-020-2521-4 is OK
- 10.1038/s41591-020-0968-3 is OK
- 10.1038/s41577-020-0319-0 is OK
- 10.1038/d41586-020-01394-6 is OK
- 10.1038/s41562-020-0911-0 is OK
- 10.1038/d41586-020-01520-4 is OK
- 10.1038/s42256-020-0184-3 is OK
- 10.1038/s42256-020-0185-2 is OK
- 10.1126/scitranslmed.abc1126 is OK
- 10.1063/5.0008834 is OK
- 10.1038/d41586-020-01685-y is OK
- 10.1038/d41586-020-01003-6 is OK
- 10.1038/s41562-020-0898-6 is OK
- 10.1073/pnas.2009033117 is OK
- 10.1038/d41586-020-01695-w is OK
- 10.1038/s41597-020-0524-5 is OK
- 10.1038/s41577-020-0323-4 is OK
- 10.1038/s41596-020-0358-9 is OK
- 10.1016/j.cell.2020.06.043 is OK
- 10.1371/journal.pone.0236307 is OK

MISSING DOIs

- 10.32388/uq8dyz may be a valid DOI for title: National Center for Biotechnology Information

INVALID DOIs

- 0.1002/wics.1212 is INVALID
```

**Comment by mponce0** [comment]
@whedon check references from branch literature

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch literature
```

**Comment by mponce0** [comment]
@whedon generate pdf from branch literature

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch literature. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/nar/gkx1095 is OK
- 10.1038/s42256-020-0184-3 is OK
- 10.1038/s42256-020-0185-2 is OK
- 10.1038/d41586-020-01695-w is OK
- 10.1038/s41597-020-0524-5 is OK

MISSING DOIs

- None

INVALID DOIs

- 0.1002/wics.1212 is INVALID
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02986/joss.02986/10.21105.joss.02986.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02986/joss.02986/10.21105.joss.02986.pdf) :page_facing_up: :point_left:

**Comment by mponce0** [comment]
@whedon check references from branch literature

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch literature
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/wics.1212 is OK
- 10.1093/nar/gkx1095 is OK
- 10.1038/s42256-020-0184-3 is OK
- 10.1038/s42256-020-0185-2 is OK
- 10.1038/d41586-020-01695-w is OK
- 10.1038/s41597-020-0524-5 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mponce0** [comment]
> 👋 @mponce0 - if you can remove the entries in the .bib file that are not actually being used, that will help reduce the potential problems that check references found.

@danielskatz Thanks! I fixed all the issues with the DOIs and removed unused items from the .bib file

**Comment by fboehm** [comment]
@whedon assign @LogIN- as reviewer

**Comment by whedon** [comment]
OK, @LogIN- is now a reviewer

**Comment by fboehm** [comment]
@whedon add @JDRomano2 as reviewer

**Comment by whedon** [comment]
OK, @JDRomano2 is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2995.
