### ISSUE TITLE
[PRE REVIEW]: Virgo: A Versatile Spectrometer for Radio Astronomy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2987]
**Submitting author:** @0xCoto (<a href="http://orcid.org/0000-0001-6928-6877">Apostolos Spanakis-Misirlis</a>)
**Repository:** <a href="https://github.com/0xCoto/Virgo" target ="_blank">https://github.com/0xCoto/Virgo</a>
**Version:** v3.6.0
**Editor:** @xuanxu
**Reviewers:** @astrom-tom , @ygrange
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @0xCoto. **Currently, there isn't an JOSS editor assigned** to your paper.

@0xCoto if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1142/9446 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1051/0004-6361:20041864 is OK
- 10.1051/0004-6361/201015362 is OK

MISSING DOIs

- 10.1016/b978-0-12-804547-3.00007-3 may be a valid DOI for title: Multirate Digital Signal Processing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.80 s (13.7 files/s, 9540.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              0              0           5511
Python                           5            277            171           1047
Markdown                         2             93              0            347
TeX                              1              8              0            189
YAML                             1              5              2             24
-------------------------------------------------------------------------------
SUM:                            11            383            173           7118
-------------------------------------------------------------------------------


Statistical information for the repository '6de461491c1fcad43c0b025e' was
gathered on 2021/01/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
0xCoto                          88          2230            735          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
0xCoto                     1495           67.0          2.7               10.70
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02987/joss.02987/10.21105.joss.02987.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02987/joss.02987/10.21105.joss.02987.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
The previous version of this paper (which was not reviewed as being too small) is https://github.com/openjournals/joss-reviews/issues/2758

**Comment by danielskatz** [comment]
@0xCoto - thanks for this submission - as it's still on the borderline in terms of effort, the editors will discuss it and get back to sometime next week about next steps

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@whedon invite @xuanxu as editor

:wave: @xuanxu - would you be able to edit this submission?

**Comment by whedon** [comment]
@xuanxu has been invited to edit this submission.

**Comment by xuanxu** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
@ygrange, @astrom-tom would you be willing to review this paper? I think your knowledge of Astrophysics and Python makes both of you a great fit for this submission.

**Comment by ygrange** [comment]
Looks cool (I don't really have a radio telescope at hand to test it against though). But I'd be happy to have a look at it :)

**Comment by 0xCoto** [comment]
@ygrange - Thank you very much for agreeing to review the paper. As it is understandably unlikely that a reviewer would have access to appropriate hardware, we have included an example observation file obtained with Virgo on the repository, for software testing and verification purposes: https://github.com/0xCoto/Virgo/tree/master/joss_example

**Comment by xuanxu** [comment]
@whedon assign @ygrange as reviewer

**Comment by whedon** [comment]
OK, @ygrange is now a reviewer

**Comment by xuanxu** [comment]
@ygrange great, thanks! I'll start the review issue once we have the second reviewer. Stay tuned!

**Comment by xuanxu** [comment]
@garrettj403 would you be willing to review this paper? I think your knowledge of Radioastronomy and Python makes you a good fit for this submission.

**Comment by astrom-tom** [comment]
Hi all!
Sorry I am on holidays (for two weeks more). If there is not an emergency to review the paper I can get to it when I am back. If this is more pressing please do not hesitate to pick someone else.
Cheers,

**Comment by xuanxu** [comment]
@astrom-tom Thanks! Starting the review in a couple of weeks is ok, I'll assign you as reviewer now, open the review issue and I'll set a reminder for you.

**Comment by xuanxu** [comment]
@whedon assign @astrom-tom  as reviewer

**Comment by whedon** [comment]
OK, @astrom-tom  is now a reviewer

**Comment by xuanxu** [comment]
@whedon add @ygrange as reviewer

**Comment by whedon** [comment]
OK, @ygrange is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3067.
