### ISSUE TITLE
[PRE REVIEW]: lineartestr: An R package for testing the linear specification of a model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2988]
**Submitting author:** @FedericoGarza (<a href="http://orcid.org/0000-0001-7015-8186">Federico Garza Ramírez</a>)
**Repository:** <a href="https://github.com/FedericoGarza/lineartestr" target ="_blank">https://github.com/FedericoGarza/lineartestr</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @FedericoGarza. **Currently, there isn't an JOSS editor assigned** to your paper.

@FedericoGarza if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (217.8 files/s, 21612.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                6             93            176            263
Markdown                         3             97              0            252
TeX                              1             11              0            135
YAML                             2             14              0             85
Rmd                              1             53             64             47
-------------------------------------------------------------------------------
SUM:                            13            268            240            782
-------------------------------------------------------------------------------


Statistical information for the repository '57e1aa4ec907814c7c4e99c1' was
gathered on 2021/01/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Fede                             2           198            198          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/07474938.2019.1687116 is OK
- 10.1214/aos/1176349025 is OK

MISSING DOIs

- 10.32614/rj-2013-031 may be a valid DOI for title: lfe: Linear Group Fixed Effects
- 10.1111/j.2517-6161.1969.tb00796.x may be a valid DOI for title: Tests for Specification Errors in Classical Linear Least-Squares Regression Analysis

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02988/joss.02988/10.21105.joss.02988.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02988/joss.02988/10.21105.joss.02988.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@@FedericoGarza - unfortunately, this software is too small for us to consider - it does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work. Or if you add a lot more functionality to the package, feel free to resubmit to JOSS, and link to the issue.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
