### ISSUE TITLE
[REVIEW]: Lab::Measurement - measurement control with Perl

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#299]
**Submitting author:** @akhuettel (<a href="http://orcid.org/0000-0001-5794-5919">Andreas K. Hüttel</a>)
**Repository:** <a href="http://www.labmeasurement.de/" target ="_blank">http://www.labmeasurement.de/</a>
**Version:** 3.542
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @kippkitts
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/df7931bc709f8176aa761256f69520b2/status.svg)](http://joss.theoj.org/papers/df7931bc709f8176aa761256f69520b2)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/df7931bc709f8176aa761256f69520b2"><img src="http://joss.theoj.org/papers/df7931bc709f8176aa761256f69520b2/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/df7931bc709f8176aa761256f69520b2/status.svg)](http://joss.theoj.org/papers/df7931bc709f8176aa761256f69520b2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="http://www.labmeasurement.de/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@kippkitts, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="http://www.labmeasurement.de/">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (3.542)?
- [x] **Authorship:** Has the submitting author (@akhuettel) made major contributions to the software?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kippkitts it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@akhuettel @kippkitts Let the reviewing begin. Let me know if I can help.

**Comment by akhuettel** [comment]
Please ping me if there's anything I can do to help.

There have been a few bugfixes since 3.542 (the most critical one probably the Gnuplot handling on Windows). Otherwise the main changes since that version are cleanup of obsolete files, initial support for Zurich Instruments devices, and a replacement of the build system with Dist::Zilla (the conversion of the documentation is still work in progress).

**Comment by Kevin-Mattheus-Moerman** [comment]
:wave: @kippkitts how are you getting on?

**Comment by Kevin-Mattheus-Moerman** [comment]
@kippkitts Let me know if I can help.

**Comment by Kevin-Mattheus-Moerman** [comment]
@akhuettel apologies for the delay so far. I've emailed @kippkitts to inquire about when he can finalize this review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by akhuettel** [comment]
We released a new version in the meantime, with support for additional equipment and additional backends. The detailed release notes / a blog post will be written in the near future and posted on the homepage.
http://search.cpan.org/~akhuettel/Lab-Measurement-3.600/

**Comment by Kevin-Mattheus-Moerman** [comment]
Great. @kippkitts can you please finalize your review and look at the latest version?

**Comment by Kevin-Mattheus-Moerman** [comment]
@kippkitts are you able to start the review process? If not let me know so I can find a different reviewer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@kippkitts can you give an indication as to when you will start the review process here? Alternatively can you recommend another reviewer?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #299 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:75:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon, do the authors need to change the repo to this link: https://github.com/lab-measurement/Lab-Measurement and put the paper.md and paper.bib in a paper folder?

**Comment by Kevin-Mattheus-Moerman** [comment]
​:hand: @geggo @hgrecco @MatthieuDartiailh @mikef5410 are you interested in this software and are you able to assist with review this submission for [JOSS](http://joss.theoj.org/about) (an academic journal for open source software).
The review process (see the [review quidelines](http://joss.theoj.org/about#reviewer_guidelines)) largely focuses on the software, but also on [a short paper](https://github.com/lab-measurement/Lab-Measurement/blob/master/paper.md), a PDF of the paper will be available shortly.
The GitHub repo is here: https://github.com/lab-measurement/Lab-Measurement

I'm calling for your help as it has been difficult to find available reviewers for this submission. If you feel part of this submission is beyond your scope/expertise it is okay if you can review only part of this submission or part of the functionality. 

Thanks!

**Comment by geggo** [comment]
Sorry, I have zero experience with Perl, but forwarded your message to a colleague with expertise in Perl / instrument control.

Gregor

**Comment by MatthieuDartiailh** [comment]
@Kevin-Mattheus-Moerman, I am sorry but I must decline. I am in principle interested in software assisted measurement, but I have no experience in PERL and I have no time to run the tests involved in the review process. I will let you know should I find time to perform part of the review (documentation) but I can make no promise.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @geggo that is really helpful. Let me know if they have questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for your response @MatthieuDartiailh I understand. It seems there are very few people that do PERL with instrumentation/measurement.

**Comment by Kevin-Mattheus-Moerman** [comment]
@geggo any news from your colleague? We would really appreciate help to review this work.

**Comment by Kevin-Mattheus-Moerman** [comment]
@akhuettel unfortunately I have not been able to track down a reviewer yet for this submission. The original reviewer has disappeared off the radar it seems. Has anything changed on your end? Do you have any reviewers you can suggest? We can either close this issue for now, or leave it open while we continue our search for reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #299 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/lib/whedon/processor.rb:49:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-8307502c3aee/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@akhuettel I've had contact with the reviewer @kippkitts we may be able to pick up review but can you confirm you are still interested in pursuing to publish your work in JOSS? Should we review a newer version of your work?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon, do the authors need to change the repo to this link: https://github.com/lab-measurement/Lab-Measurement and put the paper.md and paper.bib in a paper folder?

**Comment by arfon** [comment]
> @arfon, do the authors need to change the repo to this link: https://github.com/lab-measurement/Lab-Measurement and put the paper.md and paper.bib in a paper folder?

That would certainly fix the @whedon issue here yes.

**Comment by geggo** [comment]
I apologise for the late answer: some time I forwarded the review invitation to a colleague with some experience in this field, and urged him again. But he abandoned using Perl already a couple of yeas ago, and has  no equipment with GPIB interface available for testing. Sorry, can't help with reviewing.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon this submission looks like it has gone stale. The reviewer has gone of the radar. I pinged the authors to see if we need to revive the review process (it has been a great challenge to find suitable reviewers) but if we do not hear from the authors I feel we can assume we can withdraw this submission. Could you e-mail the authors a reminder? Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@geggo thanks for letting us know.

**Comment by arfon** [comment]
> @arfon this submission looks like it has gone stale. The reviewer has gone of the radar. I pinged the authors to see if we need to revive the review process (it has been a great challenge to find suitable reviewers) but if we do not hear from the authors I feel we can assume we can withdraw this submission. Could you e-mail the authors a reminder? Thanks.

OK, I've emailed the authors

**Comment by akhuettel** [comment]
@arfon  @Kevin-Mattheus-Moerman  I'm sorry for the delay. As already stated in the e-mail we'd like to withdraw the submission. To be honest, I don't see this going anywhere.

**Comment by arfon** [comment]
@Kevin-Mattheus-Moerman - thanks for all of your help here. Sorry this didn't work out @akhuettel.
