### ISSUE TITLE
[REVIEW]: netrd: A library for network reconstruction and graph distances

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2990]
**Submitting author:** @sdmccabe (<a href="http://orcid.org/0000-0002-7180-145X">Stefan McCabe</a>)
**Repository:** <a href="https://github.com/netsiphd/netrd" target ="_blank">https://github.com/netsiphd/netrd</a>
**Version:** v0.3
**Editor:** @arfon
**Reviewer:** @adi3, @sonal-raj
**Archive:** <a href="https://doi.org/10.5281/zenodo.4885375" target="_blank">10.5281/zenodo.4885375</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/685871d0cbb8d64e48d2445bcac6f920/status.svg)](https://joss.theoj.org/papers/685871d0cbb8d64e48d2445bcac6f920)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/685871d0cbb8d64e48d2445bcac6f920"><img src="https://joss.theoj.org/papers/685871d0cbb8d64e48d2445bcac6f920/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/685871d0cbb8d64e48d2445bcac6f920/status.svg)](https://joss.theoj.org/papers/685871d0cbb8d64e48d2445bcac6f920)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/netsiphd/netrd" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@adi3 & @sonal-raj, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/netsiphd/netrd">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@sdmccabe) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/netsiphd/netrd">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@sdmccabe) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @adi3, @sonal-raj it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by arfon** [comment]
@adi3, @sonal-raj - This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/2990 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1140/epjb/e2004-00110-5 is OK
- 10.1080/00107510903084036 is OK
- 10.1093/acprof:oso/9780199206650.001.0001 is OK
- 10.1177/0094306116681814 is OK
- 10.1145/3154524 is OK
- 10.1063/1.5025050 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1126/science.1227079 is OK
- 10.1214/09-AOAS303 is OK
- 10.1103/PhysRevE.99.023311 is OK
- 10.1073/pnas.1718154115 is OK
- 10.1093/biostatistics/kxm045 is OK
- 10.1017/S0962492904000236 is OK
- 10.1103/PhysRevLett.110.210601 is OK
- 10.1209/0295-5075/87/48007 is OK
- 10.1103/PhysRevE.90.062129 is OK
- 10.2139/ssrn.433840 is OK
- 10.1371/journal.pcbi.1002653 is OK
- 10.1103/PhysRevLett.123.128301 is OK
- 10.1155/2018/3132940 is OK
- 10.5169/seals-266450 is OK
- 10.1016/S0016-0032(23)90506-5 is OK
- 10.1109/DSAA.2015.7344816 is OK
- 10.1214/18-AOAS1176 is OK
- 10.1016/j.physleta.2010.12.038 is OK
- 10.1007/s41109-019-0156-x is OK
- 10.1103/PhysRevX.6.041062 is OK
- 10.1103/PhysRevE.98.012319 is OK
- 10.1109/GlobalSIP.2013.6736904 is OK
- 10.1016/j.dam.2017.10.007 is OK
- 10.1145/3219819.3219991 is OK
- 10.3233/978-1-60750-692-8-227 is OK
- 10.1103/PhysRevE.66.046109 is OK
- 10.1007/s41109-019-0147-y is OK
- 10.1103/PhysRevE.99.052309 is OK
- 10.1038/ncomms13928 is OK
- 10.1145/2824443 is OK
- 10.1098/rspa.2019.0744 is OK
- 10.3389/frobt.2014.00011 is OK
- 10.1126/sciadv.aau4996 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02990/joss.02990/10.21105.joss.02990.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02990/joss.02990/10.21105.joss.02990.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @adi3, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @sonal-raj, please update us on how your review is going.

**Comment by sonal-raj** [comment]
@arfon I have reviewed the netrd library along with the supporting paper & documentation and it looks good to me. The checklist has been updated accordingly.

**Comment by adi3** [comment]
@sdmccabe in the Usage section of your `README.md`, it seems you are using pseudo-code in the three snippets. Can you please change them to full code examples starting with `import netrd`. Looks like this will be quite straightforward for you as you only need to copy the snippets from [Tutorial](https://netrd.readthedocs.io/en/latest/tutorial.html) documentation.

**Comment by adi3** [comment]
@sdmccabe Thanks for the changes. A couple of things minor things in the examples:

- I could not find `time_series_data.txt` and `ground_truth.txt` in your repository. Please state in the documentation where the user can retrieve those files from.
- An alternate approach can be that you have an `/examples` directory which has the 3 python scripts together with the data, and the user simply needs to execute these scripts.
- Let's get rid of the `>>>` in the examples. No need to explicitly state them.

Also, could you please tag me on a comment here once you make any changes? That way I get the notification to proceed. Thanks!

**Comment by sdmccabe** [comment]
@adi3 how is this? https://github.com/netsiphd/netrd/pull/322

**Comment by adi3** [comment]
@sdmccabe starting to look great! Where are the `time_series_data.txt` and `ground_truth.txt` files? Intuitively, I'd imagine they would be in your `/data` folder, but couldn't find them here.

**Comment by sdmccabe** [comment]
They are hypothetical files. I'm not really inclined to make real files for the purposes of illustration; in their place I could also generate simulated data with the correct structure (as in the distances example).

**Comment by adi3** [comment]
@sdmccabe we need some sort of starter files so that users can see your examples running out of the box. Please add files with some dummy / simulated data to achieve this, and link them in your README. Thanks!

**Comment by sdmccabe** [comment]
I think that simulated data would be sufficient to show this, as in the graph distances example. We have more detailed examples in the tutorial and included notebook; simulated data in the README would be sufficient to show the required types of input data.

**Comment by adi3** [comment]
@sdmccabe cool, let me know once you're ready with the data. Also, please go ahead and merge your pull request so I can simply check the master README.

**Comment by sdmccabe** [comment]
@adi3 it's merged.

**Comment by adi3** [comment]
@sdmccabe Your second example runs fine. No success with the first and third though.

- For the first example, the commands run fine but the object `G` does not print anything.
- For the third example, the `simulate` method throws an error:
```
>>> synthetic_TS = dynamics_model.simulate(ground_truth)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adi/.local/lib/python3.8/site-packages/netrd/utilities/graph.py", line 136, in wrapper
    return func(*args, **kwargs)
TypeError: simulate() missing 1 required positional argument: 'L'
```

**Comment by sdmccabe** [comment]
@adi3 the first example returns a NetworkX graph, which does not have a particularly expressive string representation. But you can do something like `print(nx.info(G))` to inspect further. 

The third example will be fixed in https://github.com/netsiphd/netrd/pull/323.

**Comment by sdmccabe** [comment]
Hi @adi3 just checking in on this. The README updates ended up getting merged.

**Comment by sdmccabe** [comment]
Just wanted to check in on this review @adi3.

**Comment by adi3** [comment]
@sdmccabe I'm juggling with a few things right now so I'll move forward with my review in a couple of weeks. Sorry for the delay!

**Comment by adi3** [comment]
@sdmccabe Thanks for your patience. I went through your paper and the content of it looks quite good. However, it needs to be restructured and condensed a little.

1. Please have two separate sections title `Summary` and `Statement of Need`. Most of the content you present in other sections is either (a) not within the scope of a JOSS publication and should be removed (like the entire `Related software packages` discussion), or (b) can be included in the `Summary` or `Statement of Need` sections. Your `Acknowledgements` section can of course remain as it is.

2. I also would recommend you to cut down on your citations. You have a couple of very lengthy citation blocks, and a paper this short does not warrant 45 citations. I understand that your tool combines a lot of techniques together, so in this case, either cite one or two meta-analysis papers on the topic, or cite only the most important papers.

**Comment by jkbren** [comment]
@adi3 no problem, we’re happy that this is progressing, and thanks for the comments.

Is it okay if we give a little pushback on each of them? Structurally, we based much of this off of [another recent JOSS paper about Network Science](https://joss.theoj.org/papers/10.21105/joss.01731), and we were aiming for a paper that was a mix between that style and what’s required in the [JOSS readthedocs](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).

- Note 1: Separating the `Summary` from `Statement of Need`: back in October 2020 @arfon made a [similar comment and then amended to say that the paper looked good as-is](https://github.com/openjournals/joss-reviews/issues/2802#issuecomment-719443085). We would be fine separating the two sections, but reading through it we really feel that the Statement of Need is so deeply tied to the Network Science background, that it’s better suited where it is.

- Note 2: Removing the `Related Software Packages` section: we’re happy to do this, but again, we based this off of another JOSS paper that is similar in topic area. Also, in the reviewer checklist there’s a box that says “State of the field: Do the authors describe how this software compares to other commonly-used packages?” and we felt that the section addressed that.

- Note 3: Cutting down on references: Is there a limit we should be aiming for? We're happy to cut down on the references but the motivation doesn't seem very clear - we are implementing a number of methods, all of which are equally deserving of attribution. Given that JOSS is an online journal with no page limits, it seems harmless to include all of them.

We really do appreciate these comments, hoping @arfon can help us figure out how to bring the article in line with JOSS standards.

**Comment by arfon** [comment]
Thanks for the thoughtful feedback @adi3 and your response @jkbren. Here are my thoughts:

> - Note 1: Separating the Summary from Statement of Need: back in October 2020 @arfon made a similar comment and then amended to say that the paper looked good as-is. We would be fine separating the two sections, but reading through it we really feel that the Statement of Need is so deeply tied to the Network Science background, that it’s better suited where it is.

I don't have very strong feeling about this except to say that the two seconds following the first, _Network reconstruction from time series data_ and _Comparing networks using graph distances_  read a little like extended versions of the statement of need so I think there may be some merit in trying to refactor the content a little under a separate _Statement of need section_ that describes the core functionality of the package.

> - Note 2: Removing the Related Software Packages section: we’re happy to do this, but again, we based this off of another JOSS paper that is similar in topic area. Also, in the reviewer checklist there’s a box that says “State of the field: Do the authors describe how this software compares to other commonly-used packages?” and we felt that the section addressed that.

I think this I content is fine.

> - Note 3: Cutting down on references: Is there a limit we should be aiming for? We're happy to cut down on the references but the motivation doesn't seem very clear - we are implementing a number of methods, all of which are equally deserving of attribution. Given that JOSS is an online journal with no page limits, it seems harmless to include all of them.

This is also fine as-is. I generally favour liberal citation of the literature (unless it's excessive self-citation 😄).

**Comment by adi3** [comment]
@jkbren if you could please work on Note 1 as per @arfon's comments and generate a new PDF, we can move forward with the review. Thank you both!

**Comment by jkbren** [comment]
@adi3 all set! You can see where the changes took place here https://github.com/netsiphd/netrd/pull/325/files?file-filters%5B%5D=.md

**Comment by jkbren** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02990/joss.02990/10.21105.joss.02990.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02990/joss.02990/10.21105.joss.02990.pdf) :page_facing_up: :point_left:

**Comment by adi3** [comment]
@jkbren Where can users go, or who can they contact, for support? Can you add a line on this in your README.md or CONTRIBUTING.md?

**Comment by arfon** [comment]
@jkbren @sdmccabe – thanks for your updates to the paper. This is looking good!

At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by sdmccabe** [comment]
@arfon does this look right? https://doi.org/10.5281/zenodo.4885375

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4885375 as version

**Comment by whedon** [comment]
OK. 10.5281/zenodo.4885375 is the version.

**Comment by arfon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4885375 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4885375" target="_blank">10.5281/zenodo.4885375</a> is the archive.

**Comment by arfon** [comment]
@whedon set v0.3 as version

**Comment by whedon** [comment]
OK. v0.3 is the version.

**Comment by arfon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1140/epjb/e2004-00110-5 is OK
- 10.1080/00107510903084036 is OK
- 10.1093/acprof:oso/9780199206650.001.0001 is OK
- 10.1177/0094306116681814 is OK
- 10.1145/3154524 is OK
- 10.1063/1.5025050 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1126/science.1227079 is OK
- 10.1214/09-AOAS303 is OK
- 10.1103/PhysRevE.99.023311 is OK
- 10.1073/pnas.1718154115 is OK
- 10.1093/biostatistics/kxm045 is OK
- 10.1017/S0962492904000236 is OK
- 10.1103/PhysRevLett.110.210601 is OK
- 10.1209/0295-5075/87/48007 is OK
- 10.1103/PhysRevE.90.062129 is OK
- 10.2139/ssrn.433840 is OK
- 10.1371/journal.pcbi.1002653 is OK
- 10.1103/PhysRevLett.123.128301 is OK
- 10.1155/2018/3132940 is OK
- 10.5169/seals-266450 is OK
- 10.1016/S0016-0032(23)90506-5 is OK
- 10.1109/DSAA.2015.7344816 is OK
- 10.1214/18-AOAS1176 is OK
- 10.1016/j.physleta.2010.12.038 is OK
- 10.1007/s41109-019-0156-x is OK
- 10.1103/PhysRevX.6.041062 is OK
- 10.1103/PhysRevE.98.012319 is OK
- 10.1109/GlobalSIP.2013.6736904 is OK
- 10.1016/j.dam.2017.10.007 is OK
- 10.1145/3219819.3219991 is OK
- 10.3233/978-1-60750-692-8-227 is OK
- 10.1103/PhysRevE.66.046109 is OK
- 10.1007/s41109-019-0147-y is OK
- 10.1103/PhysRevE.99.052309 is OK
- 10.1038/ncomms13928 is OK
- 10.1145/2824443 is OK
- 10.1098/rspa.2019.0744 is OK
- 10.3389/frobt.2014.00011 is OK
- 10.1126/sciadv.aau4996 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2352

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2352, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1399652049856389120) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2354
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02990](https://doi.org/10.21105/joss.02990)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@adi3, @sonal-raj – many thanks for your reviews here! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@sdmccabe – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02990/status.svg)](https://doi.org/10.21105/joss.02990)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02990">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02990/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02990/status.svg
   :target: https://doi.org/10.21105/joss.02990
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02990/status.svg)](https://doi.org/10.21105/joss.02990)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
