### ISSUE TITLE
[REVIEW]: Nanoq: fast quality control for nanopore reads

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2991]
**Submitting author:** @esteinig (<a href="http://orcid.org/0000-0001-5399-5353">Eike J. Steinig</a>)
**Repository:** <a href="https://github.com/esteinig/nanoq" target ="_blank">https://github.com/esteinig/nanoq</a>
**Version:** v0.8.3
**Editor:** @luizirber
**Reviewer:** @natir, @bovee
**Archive:** <a href="https://doi.org/10.5281/zenodo.5816183" target="_blank">10.5281/zenodo.5816183</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5a1570cde4b9fc494db27f6088affef3/status.svg)](https://joss.theoj.org/papers/5a1570cde4b9fc494db27f6088affef3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5a1570cde4b9fc494db27f6088affef3"><img src="https://joss.theoj.org/papers/5a1570cde4b9fc494db27f6088affef3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5a1570cde4b9fc494db27f6088affef3/status.svg)](https://joss.theoj.org/papers/5a1570cde4b9fc494db27f6088affef3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/esteinig/nanoq" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@natir & @bovee, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @luizirber know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/esteinig/nanoq">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@esteinig) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/esteinig/nanoq">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@esteinig) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @natir, @bovee it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btv573 is OK
- 10.1016/S1473-3099(20)30562-4 is OK
- 10.1093/bioinformatics/bty149 is OK
- 10.1038/nbt.4060 is OK
- 10.1093/gigascience/giz043 is OK
- 10.1093/bioinformatics/bty654 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02991/joss.02991/10.21105.joss.02991.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02991/joss.02991/10.21105.joss.02991.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:wave: @natir, please update us on how your review is going.

**Comment by whedon** [comment]
:wave: @bovee, please update us on how your review is going.

**Comment by esteinig** [comment]
@natir @bovee still working on the improvements, apologies for the delay

**Comment by luizirber** [comment]
We are in the middle of a pandemic, so whedon's comment might sound a bit demanding, but the intentions are good, just so we know how the review is going =]

@esteinig do you mind [opening a PR](https://github.com/esteinig/nanoq/compare/joss?expand=1) with the `joss` branch, so we have better visibility on the changes you're making to address Roderick and Pierre's comments? You don't need to merge the PR yet, but it is nicer to see changes than having to find the branch in the nanoq repo.

**Comment by esteinig** [comment]
@luizirber thanks a ton, really appreciate the patience! I am back on this from tomorrow, so will make the PR request and finalize all the bits and pieces (not sure if you want to see my messy commit history but all good). Thanks everyone!

**Comment by esteinig** [comment]
@luizirber my sincere apologies for the delays. I'm in the process of submitting my PhD thesis and it's a bit hectic. I hope this is not an issue. I would very much like to include the (excellent) points raised by the reviewers and include documentation and other improvements.

**Comment by luizirber** [comment]
@esteinig I don't see any problems in delaying a bit, thesis work is hard. Good luck!

Just checking with @openjournals/joss-eics if there is any specific whedon command or tag to be added to show that this submission is paused, or just leave as-is.

**Comment by arfon** [comment]
> Just checking with @openjournals/joss-eics if there is any specific whedon command or tag to be added to show that this submission is paused, or just leave as-is.

We just add the `paused` label in situations like this. I'll add it now...

**Comment by arfon** [comment]
:wave: folks, just checking in here. @esteinig - did you manage to submit your thesis yet?

**Comment by arfon** [comment]
:wave: @esteinig – any updates here?

**Comment by natir** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02991/joss.02991/10.21105.joss.02991.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02991/joss.02991/10.21105.joss.02991.pdf) :page_facing_up: :point_left:

**Comment by luizirber** [comment]
Removing the `paused` label, let's get this going again? =]

**Comment by natir** [comment]
it's seems

**Comment by esteinig** [comment]
thank you so much for your patience! thesis finally submitted, it was a bit of a grind :hot_face: tried my best to address the issues and re-wrote most of the code and the paper. thanks for the great suggestions around implementation @natir and @bovee

**Comment by esteinig** [comment]
there was a couple of slight changes to the paper, added `rust-bio-tools` in the introduction

@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02991/joss.02991/10.21105.joss.02991.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02991/joss.02991/10.21105.joss.02991.pdf) :page_facing_up: :point_left:

**Comment by esteinig** [comment]
* fixed a bug affecting the `seqtk` benchmark (done on uncompressed instead of compressed file)
* added a `seqkit stats` benchmark as it has a 'fast' mode
* added  benchmark data to tables
* removed duplicate figure captions
* updated plots and benchmark text

**Comment by esteinig** [comment]
* updated citations in paper

**Comment by bovee** [comment]
Sorry for the delay! I checked through the remaining issues and the paper and software look great.

**Comment by luizirber** [comment]
@whedon generate pdf

**Comment by luizirber** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btv573 is OK
- 10.1371/journal.pone.0163962 is OK
- 10.1016/S1473-3099(20)30562-4 is OK
- 10.1093/bioinformatics/bty149 is OK
- 10.1038/nbt.4060 is OK
- 10.1093/gigascience/giz043 is OK
- 10.1093/bioinformatics/bty654 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02991/joss.02991/10.21105.joss.02991.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02991/joss.02991/10.21105.joss.02991.pdf) :page_facing_up: :point_left:

**Comment by luizirber** [comment]
@esteinig can you tag a new `nanoq` release (potentially after linking zenodo and github, so new tags get Zenodo DOIs) to serve as the archival version and report the version number and archive DOI here? It is all that is needed to finish this review (so close!)

**Comment by esteinig** [comment]
@luizirber yep totally, apologies for the delay (and thanks for the ping)

* Release: `0.8.3`
* Zenodo: `10.5281/zenodo.5720098 `

**Comment by luizirber** [comment]
@whedon set 10.5281/zenodo.5720098 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5720098" target="_blank">10.5281/zenodo.5720098</a> is the archive.

**Comment by luizirber** [comment]
@whedon set v0.8.3 as version

**Comment by whedon** [comment]
OK. v0.8.3 is the version.

**Comment by luizirber** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btv573 is OK
- 10.1371/journal.pone.0163962 is OK
- 10.1016/S1473-3099(20)30562-4 is OK
- 10.1093/bioinformatics/bty149 is OK
- 10.1038/nbt.4060 is OK
- 10.1093/gigascience/giz043 is OK
- 10.1093/bioinformatics/bty654 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2766

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2766, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by esteinig** [comment]
Wohooo, looking good! :partying_face: Thanks so much for your patience and feedback, really appreciated this process.

**Comment by Kevin-Mattheus-Moerman** [comment]
@luizirber thanks for editing this work. Some points need to be addressed here which you can keep in mind for the future so you fix these before recommending acceptance. In particular the archived version meta-data (title, author lists, etc) should match that of the paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
@esteinig I have reviewed your paper and the archived data and have the following issues that need your attention: 

- [ ] Edit the ZENODO archive such that the meta-data matches the paper. 
- The title should be: `Nanoq: ultra-fast quality control for nanopore reads`. 
- The author lists should match the paper
- You may also add ORCID profiles to the authors on ZENODO 

- [ ] Check throughout for potentially missing "Oxford comma's" E.g. perhaps here? `Nanoq offers nanopore-specific quality scores, read filtering options[,] and output compression.`
- [ ] Check `...they may not immediately applicable...`, looks like that should be `...they may not be immediately applicable...`?
- [ ] Check `...and summary statistics on the even...`. It may be because this is not my domain of expertise but this sentence does not make sense to me. It is mainly the "on the even" part that throws me off. Consider rephrasing. 
- [ ] If it is easy to recreate figures 1 and 2 I suggest/recommend (not required) to render them with a larger font size and to export them with a higher resolution.

**Comment by Kevin-Mattheus-Moerman** [comment]
@esteinig could you give an update on work on this :point_up:. Let us know if you have any questions.

**Comment by esteinig** [comment]
@Kevin-Mattheus-Moerman thanks so much for the final suggestions, will upload the new version over the weekend! (apologies for the delay)

**Comment by arfon** [comment]
@esteinig – just checking if you've managed to make these changes yet?

**Comment by esteinig** [comment]
@arfon yes thanks so much for your patience, the end of last year was a bit hectic for us. please see the new version pushed:

* Zenodo data updated
* oxford commas added throughout manuscript
* spelling checked and fixed

**Comment by danielskatz** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btv573 is OK
- 10.1371/journal.pone.0163962 is OK
- 10.1016/S1473-3099(20)30562-4 is OK
- 10.1093/bioinformatics/bty149 is OK
- 10.1038/nbt.4060 is OK
- 10.1093/gigascience/giz043 is OK
- 10.1093/bioinformatics/bty654 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.5816183 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5816183" target="_blank">10.5281/zenodo.5816183</a> is the archive.

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2870

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2870, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1479845274449330178) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2871
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.02991](https://doi.org/10.21105/joss.02991)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @esteinig (Eike J. Steinig) and co-author!!

And thanks to @natir and @bovee for reviewing, and @luizirber for editing!
We couldn't do this without you!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02991/status.svg)](https://doi.org/10.21105/joss.02991)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02991">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02991/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02991/status.svg
   :target: https://doi.org/10.21105/joss.02991
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02991/status.svg)](https://doi.org/10.21105/joss.02991)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
