### ISSUE TITLE
[REVIEW]: RBF: An R package to compute a robust backfitting estimator for additive models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2992]
**Submitting author:** @alemermartinez (<a href="http://orcid.org/0000-0002-1893-2039">Alejandra Martínez</a>)
**Repository:** <a href="https://github.com/msalibian/RBF" target ="_blank">https://github.com/msalibian/RBF</a>
**Version:** v2.1.0
**Editor:** @mikldk
**Reviewer:** @mcavs, @mmrabe
**Archive:** <a href="https://doi.org/10.5281/zenodo.4637759" target="_blank">10.5281/zenodo.4637759</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/abeafeccafd9ec620180af2aba4379cb/status.svg)](https://joss.theoj.org/papers/abeafeccafd9ec620180af2aba4379cb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/abeafeccafd9ec620180af2aba4379cb"><img src="https://joss.theoj.org/papers/abeafeccafd9ec620180af2aba4379cb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/abeafeccafd9ec620180af2aba4379cb/status.svg)](https://joss.theoj.org/papers/abeafeccafd9ec620180af2aba4379cb)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/msalibian/RBF" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mcavs & @mmrabe, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mikldk know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/msalibian/RBF">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@alemermartinez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/msalibian/RBF">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@alemermartinez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mcavs, @mmrabe it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2992 with the following error: 

 Can't find any papers to compile :-(

**Comment by mikldk** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/10485252.2017.1369077 is OK
- 10.1016/0047-259X(89)90023-7 is OK
- 10.2307/2287576 is OK
- 10.1201/9780203753781-6 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mikldk** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@mcavs, @mmrabe: Thanks for agreeing to review. Please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If possible create issues (and cross-reference) in the submission's repository to avoid too specific discussions in this review thread. 

If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@mcavs, @mmrabe, can you please give a brief status of your reviews? This is not to rush you, merely to give me an impression of the progress and time-frame.

**Comment by mmrabe** [comment]
Hi @mikldk, I have completed general checks and some functionality checks. I should be able to return a complete review within a week from now (i.e., by Feb 10) if that's okay?

**Comment by mikldk** [comment]
@mmrabe Thanks, that's fine -- thanks for checking in.

**Comment by mcavs** [comment]
Hi @mmrabe, I have completed review. 

I think the manuscript is well-written and easy to read. It would be good to explain the other options of the type argument in the backf.rob function. Also, a short text about their superiority against each other could be added. The fact that the manuscript was illustrated through an example makes me worry about whether the findings are generalizable. I think it is ready for the publication, if this situation can be clarified.

**Comment by mmrabe** [comment]
The `RBF` package is an R package for robust backfitting (Boente et al., 2017). Overall, the package works well and the authors provide a good justification and explanation in the paper. I think the paper needs some revisions (esp. with regard to citations/bibliography). Also, for usability the `print` and `summary` methods in the package may need some work but I'm not sure if that should be the scope of this review or may be attended to later on as the package develops. I have added and linked issues to the package repository.

I found your example in the paper very helpful. I'm not a statistician, so I can't confirm whether the algorithm performs exactly what it's supposed to and @mcavs also pointed out that a single example may not be enough to judge that. It may be useful to add at least one more example as a vignette in the package. If you decide to do so, you should of course also consider adding the current example as a vignette. Once the examples are added as vignettes, it may also be worthwhile to only summarize the key findings (e.g., compare the model fits using figures or some statistic) and to refer to the vignettes for more details.

I think this submission is certainly a suitable candidate for publication in JOSS once the open issues have been addressed.

**Comment by whedon** [comment]
:wave: @mmrabe, please update us on how your review is going.

**Comment by alemermartinez** [comment]
Thanks the reviewers for their constructive comments. If that is okay, we will start to incorporate the suggestions.

Kind regards,

Alejandra

________________________________
De: whedon <notifications@github.com>
Enviado: jueves, 11 de febrero de 2021 06:24
Para: openjournals/joss-reviews <joss-reviews@noreply.github.com>
Cc: Alejandra Martinez <ale_m_martinez@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [openjournals/joss-reviews] [REVIEW]: RBF: An R package to compute a robust backfitting estimator for additive models (#2992)


👋 @mmrabe<https://github.com/mmrabe>, please update us on how your review is going.

**Comment by mikldk** [comment]
@alemermartinez Please do. Please check in again within a week's time if possible.

**Comment by alemermartinez** [comment]
Dear Mikkel and reviewers,

Once again, thank you very much for your constructive comments and suggestions, and also for Mikkel's help with our submission process.

Our revised manuscript and software incorporates all your recommended changes. Specifically: we fixed the references and typos, included community guidelines (lines 115-121), added information on other arguments of the main function (lines 78-91), and incorporated a comment (lines 49-56) about other evidence of the favourable behaviour of our proposal (e.g. a simulated study reported in Boente et al. 2017).
With respect to the software, we have changed the 'summary' and 'print' methods as suggested. We have also started writing a package vignette as suggested by one of the referees, where we plan to include another illustrative example.

Kind regards,

Alejandra

________________________________
De: Mikkel Meyer Andersen <notifications@github.com>
Enviado: martes, 16 de febrero de 2021 10:15
Para: openjournals/joss-reviews <joss-reviews@noreply.github.com>
Cc: Alejandra Martinez <ale_m_martinez@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [openjournals/joss-reviews] [REVIEW]: RBF: An R package to compute a robust backfitting estimator for additive models (#2992)


@alemermartinez<https://github.com/alemermartinez> Please do. Please check in again within a week's time if possible.

**Comment by mikldk** [comment]
Thanks, @alemermartinez . Please let us know when the vignette has finished so that the reviewers can look at all the changes simultaneously.

**Comment by mmrabe** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@alemermartinez, can you please give a brief status? This is not to rush you, merely to give me an impression of the progress and time-frame.

**Comment by alemermartinez** [comment]
Dear Mikkel,
We have just finished the vignette, which can be found in the "doc" folder of the main branch of the repository. I believe our revision is now complete.
Kind regards,
Alejandra

________________________________
De: Mikkel Meyer Andersen <notifications@github.com>
Enviado: jueves, 4 de marzo de 2021 18:41
Para: openjournals/joss-reviews <joss-reviews@noreply.github.com>
Cc: Alejandra Martinez <ale_m_martinez@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [openjournals/joss-reviews] [REVIEW]: RBF: An R package to compute a robust backfitting estimator for additive models (#2992)


@alemermartinez<https://github.com/alemermartinez>, can you please give a brief status? This is not to rush you, merely to give me an impression of the progress and time-frame.

**Comment by mmrabe** [comment]
@alemermartinez , the typical location for vignettes is `vignettes/`. The contents of `docs/` will not be visible to the user of the final package.

**Comment by alemermartinez** [comment]
Thank you, Maximilian. We didn't know that. I copied Examples.html and Examples.R to "vignettes".

Kind regards,

Alejandra

________________________________
De: Maximilian M. Rabe <notifications@github.com>
Enviado: viernes, 5 de marzo de 2021 03:07
Para: openjournals/joss-reviews <joss-reviews@noreply.github.com>
Cc: Alejandra Martinez <ale_m_martinez@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [openjournals/joss-reviews] [REVIEW]: RBF: An R package to compute a robust backfitting estimator for additive models (#2992)


@alemermartinez<https://github.com/alemermartinez> , the typical location for vignettes is vignettes/. The contents of docs/ will not be visible to the user of the final package.

**Comment by msalibian** [comment]
@mmrabe @alemermartinez perhaps the easiest way to access the vignette before the package is updated on CRAN would be to install it from the repository with
```
devtools::install_github('msalibian/RBF', build_vignettes=TRUE)
```
and then open it with
```
vignette('Examples', package='RBF')
```

**Comment by mikldk** [comment]
@alemermartinez Please also read <https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-package-vignettes> and <https://r-pkgs.org/vignettes.html>. Normally, `.R` and `.html` files are not in the `vignette` directory. Use e.g. `devtools::build_vignettes()` for handling vignettes (see [here](https://devtools.r-lib.org/reference/build_vignettes.html)).

**Comment by msalibian** [comment]
@mikldk We've rolled back the repository to its original state when we finished the vignette. Only the source code for the vignette (and figures which are not generated by the R Markdown file) are in the `vignettes` folder, and we removed the `doc` folder from the repository. The package passes all the usual CRAN checks, and builds (including the vignette) without any issues. 

Since the HTML of the vignette and the corresponding .R file are only created (and stored in the `inst/doc` folder) when one builds the source tar ball of the package to upload to CRAN, and thus are not be immediately available to the referees from the GitHub repository, we originally decided to leave the `doc` folder and its contents (as created by `devtools::build_vignettes()`) in the repository to save the referees' some time. We then probably misread @mmrabe comment as suggesting @alemermartinez to move those files to the `vignettes` folder instead. We were aware that the `doc` folder will not be included in the package, and that the `vignettes` folder should only include the source for the vignette--we just thought we would save the referees some time.

Please let us know if you (or the referees) would like us to make the HTML version of the vignette available directly to you or them, and how. We can either temporarily restore the `doc` folder (from `devtools::build_vignettes()`) in the repository, as we had it before, or attach the HTML file to a comment here, or some other way.

**Comment by mikldk** [comment]
@msalibian You can also try the `[pkgdown](https://pkgdown.r-lib.org/)` package which generates a webpage with the man pages and vignettes. It can be published via GitHub Pages (see the `README`).

**Comment by msalibian** [comment]
@mikldk Done. Please find it at [https://msalibian.github.io/RBF/articles/Examples.html](https://msalibian.github.io/RBF/articles/Examples.html). Note that at this point we are only planning to use that site to help with the revision of the paper.

**Comment by mikldk** [comment]
@mmrabe: You have one unchecked box. Is this still correct?

**Comment by mmrabe** [comment]
@mikldk Sorry, I missed that one. @msalibian & @alemermartinez, thanks for providing the additional example!

**Comment by mikldk** [comment]
@mcavs, @mmrabe:  Can you confirm that you have finished the review and recommend that this paper is now published?

@alemermartinez :

* Please have a final read though of the paper, checking language etc.
* Have a final check of the proofs with `@whedon generate pdf`
* In general be sure that all versions are correct and that the repo is in the state that should be published.
* Please make a tagged release and archive (e.g. with [Zenodo](https://zenodo.org/)) as described [here](<https://joss.readthedocs.io/en/latest/submitting.html#the-review-process>), and report the version number and archive DOI in this thread. Please verify that the archive deposit has the correct metadata (title and author list), or edit these if that is not the case.

**Comment by mmrabe** [comment]
Yes, all issues have been resolved. I can now recommend this paper for publication in JOSS.

**Comment by mcavs** [comment]
@mikldk I confirm that it can publish in JOSS!

**Comment by msalibian** [comment]
@mikldk @mmrabe @mcavs Thank you all for your work and constructive revision process!

**Comment by msalibian** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2992 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: :point_left:

**Comment by msalibian** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: :point_left:

**Comment by alemermartinez** [comment]
Thank you very much, @mikldk<https://github.com/mikldk> @mmrabe<https://github.com/mmrabe> @mcavs<https://github.com/mcavs>

Kind regards,

Alejandra



-------- Mensaje original --------
De: Matias Salibian Barrera ***@***.***>
Fecha: 24/3/21 13:01 (GMT-03:00)
A: openjournals/joss-reviews ***@***.***>
CC: Alejandra Martinez ***@***.***>, Mention ***@***.***>
Asunto: Re: [openjournals/joss-reviews] [REVIEW]: RBF: An R package to compute a robust backfitting estimator for additive models (#2992)


@mikldk<https://github.com/mikldk> @mmrabe<https://github.com/mmrabe> @mcavs<https://github.com/mcavs> Thank you all for your work and constructive revision process!

**Comment by msalibian** [comment]
@mikldk The release is v2.1.0 and the DOI is [10.5281/zenodo.4637759](https://doi.org/10.5281/zenodo.4637759).

**Comment by mikldk** [comment]
@whedon set 10.5281/zenodo.4637759 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4637759" target="_blank">10.5281/zenodo.4637759</a> is the archive.

**Comment by mikldk** [comment]
@whedon set v2.1.0 as version

**Comment by whedon** [comment]
OK. v2.1.0 is the version.

**Comment by mikldk** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@msalibian @alemermartinez Please make the title at Zenodo the same as the paper's ("RBF: An R package to compute a robust backfitting estimator for additive models").

**Comment by msalibian** [comment]
@mikldk Done.

**Comment by mikldk** [comment]
@msalibian At Zenodo your name is "Matias Salibian Barrera" and in the paper it is "Matias Salibian-Barrera". Please make consistent.

**Comment by msalibian** [comment]
@mikldk My apologies! They are now consistent (both as it appeared in the paper).

**Comment by mikldk** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: :point_left:

**Comment by mikldk** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2992 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/10485252.2017.1369077 is OK
- 10.1016/0047-259X(89)90023-7 is OK
- 10.1201/9781351072304 is OK
- 10.2307/2287576 is OK
- 10.1201/9780203753781-6 is OK
- 10.1002/9781119214656 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2185

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2185, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by danielskatz** [comment]
👋 @mikldk - this is the command that was needed. Can you confirm that this is ready to go, from your point of view? If so, I'll do a final proof read...

**Comment by mikldk** [comment]
@danielskatz Thanks; it was a mistake; I wasn't entirely ready. Sorry.

@alemermartinez @msalibian:

1. Maybe add citation to RBF in "Statement of Need" (similar to that in the Summary; Boente et al.(2017)?)
2. Background: "Note that if [...]" for all g_j ?
3. Background: Distribution (variance? constant?) of error term (at least required for it being a standard linear regression model)?
4. Background: min formula: sigma not defined; you mention it as "residual scale", but not clear how/what it should be for the optimisation?
5. Illustration: `degree = 1 and type='Tukey'`; add spaces around second `=`. Similarly later `type='Huber'`.

**Comment by msalibian** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02992/joss.02992/10.21105.joss.02992.pdf) :page_facing_up: :point_left:

**Comment by msalibian** [comment]
@mikldk Thank you for catching these omissions. We've fixed them. For comments (3) and (4), we now explicitly include the residual scale parameter in our model in equation (1), and we also mention that \sigma is estimated using a preliminary estimator (the MAD of the residuals from a local median fit). The distribution family of the errors in equation (1) may remain unspecified, but we mention that it is assumed to be symmetric around zero.

**Comment by mikldk** [comment]
@whedon accept deposit=true from branch joss

**Comment by mikldk** [comment]
@whedon accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/10485252.2017.1369077 is OK
- 10.1016/0047-259X(89)90023-7 is OK
- 10.1201/9781351072304 is OK
- 10.2307/2287576 is OK
- 10.1201/9780203753781-6 is OK
- 10.1002/9781119214656 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2204

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2204, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by danielskatz** [comment]
Please let @openjournals/joss know when you are happy with this, and I will go ahead and do the final proofreading and then processing

**Comment by mikldk** [comment]
@danielskatz Just tagging the authors @alemermartinez @msalibian for the proofreading.

**Comment by danielskatz** [comment]
I've found a few small things that shoud be changed, as indicated in https://github.com/msalibian/RBF/pull/6

**Comment by msalibian** [comment]
@danielskatz Done

**Comment by danielskatz** [comment]
Done as in "I've merged those changes" or "I'm happy with the text and you can proceed to publication" or both or something else?

**Comment by msalibian** [comment]
@danielskatz Both: merged the changes and I'm happy to go ahead with the current text. Thanks.

**Comment by danielskatz** [comment]
Are you speaking for @alemermartinez  as well?

**Comment by alemermartinez** [comment]
Yes, he is. Thank you, Daniel, for this new read of the text.

Kind regards,

Alejandra


-------- Mensaje original --------
De: "Daniel S. Katz" ***@***.***>
Fecha: 7/4/21 17:57 (GMT-03:00)
A: openjournals/joss-reviews ***@***.***>
CC: Alejandra Martinez ***@***.***>, Mention ***@***.***>
Asunto: Re: [openjournals/joss-reviews] [REVIEW]: RBF: An R package to compute a robust backfitting estimator for additive models (#2992)


Are you speaking for @alemermartinez<https://github.com/alemermartinez> as well?

**Comment by danielskatz** [comment]
@whedon accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/10485252.2017.1369077 is OK
- 10.1016/0047-259X(89)90023-7 is OK
- 10.1201/9781351072304 is OK
- 10.2307/2287576 is OK
- 10.1201/9780203753781-6 is OK
- 10.1002/9781119214656 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2205

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2205, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1379909831428075522) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2206
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02992](https://doi.org/10.21105/joss.02992)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @alemermartinez (Alejandra Martínez) & @msalibian!!

And thanks to @mcavs and @mmrabe for reviewing, and @mikldk for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02992/status.svg)](https://doi.org/10.21105/joss.02992)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02992">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02992/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02992/status.svg
   :target: https://doi.org/10.21105/joss.02992
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02992/status.svg)](https://doi.org/10.21105/joss.02992)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
