### ISSUE TITLE
[PRE REVIEW]: BACPHLIP: Predicting bacteriophage lifestyle from conserved protein domains

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2993]
**Submitting author:** @adamhockenberry (<a href="http://orcid.org/0000-0001-9476-0104">Adam Hockenberry</a>)
**Repository:** <a href="https://github.com/adamhockenberry/bacphlip" target ="_blank">https://github.com/adamhockenberry/bacphlip</a>
**Version:** v0.9.6
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @adamhockenberry. **Currently, there isn't an JOSS editor assigned** to your paper.

@adamhockenberry if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (100.4 files/s, 13194.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              1             37              0            534
Python                           5             76            116            424
Markdown                         2             45              0            175
YAML                             2              2              4             24
INI                              1              0              0              9
-------------------------------------------------------------------------------
SUM:                            11            160            120           1166
-------------------------------------------------------------------------------


Statistical information for the repository '3933e0c3591ad624b3095700' was
gathered on 2021/01/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adam Hockenberry                36           788            339          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adam Hockenberry            616           78.2          1.9                8.12
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02993/joss.02993/10.21105.joss.02993.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02993/joss.02993/10.21105.joss.02993.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201629272 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.1101/2020.04.14.041137 is OK
- 10.1093/bioinformatics/bts014 is OK
- 10.1038/nmicrobiol.2017.112 is OK
- 10.7554/eLife.06416 is OK
- 10.1038/nature13459 is OK
- 10.7554/eLife.08490 is OK
- 10.1101/709758 is OK
- 10.7554/eLife.51971 is OK
- 10.7554/eLife.49081 is OK
- 10.1126/science.1261498 is OK
- 10.1038/nrmicro.2016.177 is OK
- 10.1038/s41591-019-0437-z is OK
- 10.1128/mSystems.00756-19 is OK
- 10.1016/j.cell.2017.10.045 is OK
- 10.1038/s41564-018-0312-6 is OK
- 10.1038/s41564-018-0190-y is OK
- 10.1128/mSphere.00359-16 is OK
- 10.1038/ismej.2016.47 is OK
- 10.1038/s41467-018-07641-9 is OK
- 10.1371/journal.pcbi.1002195 is OK
- 10.1093/nar/gkz991 is OK
- 10.1093/molbev/mss279 is OK
- 10.1016/j.cell.2019.03.040 is OK
- 10.1038/nature19094 is OK
- 10.1016/j.crci.2010.06.007 is OK
- 10.1038/s41579-019-0311-5 is OK
- 10.7554/eLife.51599 is OK
- 10.1101/2020.07.11.198606 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@adamhockenberry - due to the small size of this submission, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. You should hear back in about a week.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by adamhockenberry** [comment]
@danielskatz Many thanks! Two quick notes, if it's helpful. 

As for the text of the paper, I purposefully kept it quite limited but have a several page ".pdf" included in the repository ("paper/BACPHLIP_supplement.pdf") that is meant for better describing the scholarly research aims, model development, and validation. Was unsure of whether this was necessary/appropriate/best practice. 

Also, I have a separate repository (https://github.com/adamhockenberry/bacphlip-model-dev) that contains much more about how the model was created and trained, while this "bacphlip" repository under-review is meant to be the as-streamlined-as-possible end-user version. Thanks for all your help!

**Comment by danielskatz** [comment]
The main issue is going to be the quite small size of the codebase. It's about 500 lines of Python, and we typically desk-reject anything under 300 lines, and have editor discussion of anything under or near 1000...

**Comment by clauswilke** [comment]
Hello @danielskatz, @clauswilke here, the other author of the paper. I'd like to emphasize that this is a Software 2.0 project where much of the program logic is encoded in the trained model, so simply counting lines of code is misleading. There's about a megabyte of binary data encoding program logic here:
https://github.com/adamhockenberry/bacphlip/blob/master/bacphlip/data/rf_best.joblib

And, as @adamhockenberry stated, we have a separate public repository that contains all the code required to generate this model: https://github.com/adamhockenberry/bacphlip-model-dev
We could have put everything into one repo but we felt that that would only confuse endusers who will generally not have to worry about retraining the model.

**Comment by arfon** [comment]
Hi @adamhockenberry and @clauswilke. Apologies for the delay in providing a response here, this submission prompted some discussions amongst the editorial team. The upshot of these discussions is that we will not be sending this submission out for review.

Ultimately this decision has been made because the _software contribution_ is considered too small to be reviewed by JOSS. 

_Software 2.0 projects_ as you describe @clauswilke are an interesting development but many/most of our [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#review-items) can't really be applied to trained models. We are **not saying** that this is not a useful contribution to the field, rather, we don't feel like JOSS is the right venue to review this submission. We realize this currently isn't clear in our submission guidelines and are updating our docs accordingly: https://github.com/openjournals/joss/pull/871

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
