### ISSUE TITLE
[PRE REVIEW]: PyFstat: a Python package for continuous gravitational-wave data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2994]
**Submitting author:** @dbkeitel (<a href="http://orcid.org/0000-0002-2824-626X">David Keitel</a>)
**Repository:** <a href="https://github.com/PyFstat/PyFstat/" target ="_blank">https://github.com/PyFstat/PyFstat/</a>
**Version:** v1.11.1
**Editor:** @danielskatz
**Reviewers:** @khanx169, @RobertRosca
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @dbkeitel. **Currently, there isn't an JOSS editor assigned** to your paper.

@dbkeitel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.27 s (265.2 files/s, 73563.4 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           41           2066           4227          12221
Markdown                          2             93              0            498
YAML                              6             25             23            159
CUDA                              2             38             66            142
reStructuredText                 14             52             67            104
JSON                              1              0              0             40
DOS Batch                         1              8              1             26
Bourne Shell                      2              6             14             20
Bourne Again Shell                1              6              4             18
Dockerfile                        1              4              7             14
make                              1              5              7             13
--------------------------------------------------------------------------------
SUM:                             72           2303           4416          13255
--------------------------------------------------------------------------------


Statistical information for the repository 'a8658face0a8c6503406fcd4' was
gathered on 2021/01/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
David Keitel                   348         15016           6978           36.50
Gregory Ashton                 285         13432           8478           36.36
Reinhard Prix                   10          4217           2311           10.83
Rodrigo Tenorio                 15          1279            546            3.03
Rodrigo-Tenorio                142          2406           1779            6.95
gregory.ashton                 111          3086            723            6.32

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
David Keitel              10614           70.7          6.0                9.31
Gregory Ashton             2832           21.1         40.5                4.38
Reinhard Prix              2359           55.9         18.9                0.42
Rodrigo Tenorio             215           16.8          5.8                0.47
Rodrigo-Tenorio            2494          103.7          3.4                6.98
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2994 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2994 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `initialize': No such file or directory @ rb_sysopen - af475834051feb14868d9a04/joss-paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:66:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.7935/GT1W-FZ16 is OK
- 10.1103/PhysRevD.58.063001 is OK
- 10.1007/978-3-540-76965-1_24 is OK
- 10.1016/j.parco.2011.09.001 is OK
- 10.1103/PhysRevD.89.064023 is OK
- 10.1088/0264-9381/32/2/024001 is OK
- 10.1088/0264-9381/32/7/074001 is OK
- 10.1093/mnras/stv2422 is OK
- 10.1142/S021773231730035X is OK
- 10.1103/PhysRevD.97.103020 is OK
- 10.1103/PhysRevD.98.063011 is OK
- 10.1088/1361-6382/aade34 is OK
- 10.3390/universe5110217 is OK
- 10.1103/PhysRevLett.124.191102 is OK
- 10.1093/mnras/staa3624 is OK
- 10.1016/j.softx.2020.100634 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2994 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `initialize': No such file or directory @ rb_sysopen - d08b089bfd93fdba0f8da8b4/joss-paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:66:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
👋 @openjournals/dev  - can you help with this compilation error?  I don't see anything in the error message that I can use to diagnose the problem

**Comment by arfon** [comment]
I think the presence of a `paper.tex` file is confusing Whedon: https://github.com/PyFstat/PyFstat/blob/joss/joss-paper/paper.tex

I would suggest removing this and trying again.

**Comment by danielskatz** [comment]
👋 @dbkeitel  - can you remove paper.tex from the repo, and then try the compilation, by putting ```@whedon generate pdf from branch joss``` in a new comment here?  I'm going to mark this as paused for the minute

**Comment by dbkeitel** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02994/joss.02994/10.21105.joss.02994.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02994/joss.02994/10.21105.joss.02994.pdf) :page_facing_up: :point_left:

**Comment by dbkeitel** [comment]
Thanks  @danielskatz @arfon that has fixed it! And thanks for getting thing started, too.

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@dbkeitel - do you have any suggestions for potential reviewers? Please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by danielskatz** [comment]
👋 @khanx169, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html  (You were suggested by @eliu23)

**Comment by danielskatz** [comment]
👋 @svigeland - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by dbkeitel** [comment]
If those first wo people you asked aren't available, cmbiwer would be a great choice (GW analyst with experience developing similar packages, but no direct contact with this project).

Some more likely-looking people (with python & astro listed as language/field) going up from the bottom of the table would be e.g.: RobertRosca arjunsavel sibirrer JBorrow cavestruz .

**Comment by danielskatz** [comment]
👋 @cmbiwer - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by khanx169** [comment]
> 👋 @khanx169, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html (You were suggested by @eliu23)

@danielskatz yes I'd be happy to review.

**Comment by danielskatz** [comment]
@khanx169 - thanks.  I'll assign you now, but we won't actually start the review until we get at least one more reviewer as well

**Comment by danielskatz** [comment]
@whedon assign @khanx169 as reviewer

**Comment by whedon** [comment]
OK, @khanx169 is now a reviewer

**Comment by svigeland** [comment]
> 👋 @svigeland - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Apologies, but I'm unable to review now.

**Comment by danielskatz** [comment]
👋 @RobertRosca - would you be willing to review this submission for JOSS?

**Comment by RobertRosca** [comment]
Hey, sure I'd be happy to review! I can read through the guidelines and get started Monday.

**Comment by danielskatz** [comment]
Thanks - I'll assign you and we'll start the review in a new issue

**Comment by danielskatz** [comment]
@whedon add @RobertRosca as reviewer

**Comment by whedon** [comment]
OK, @RobertRosca is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3000.
