### ISSUE TITLE
[PRE REVIEW]: GeophysicalFlows.jl: Solvers for geophysical fluid dynamics problems in periodic domains on CPUs & GPUs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2996]
**Submitting author:** @navidcy (<a href="http://orcid.org/0000-0002-8149-4094">Navid C. Constantinou</a>)
**Repository:** <a href="https://github.com/FourierFlows/GeophysicalFlows.jl" target ="_blank">https://github.com/FourierFlows/GeophysicalFlows.jl</a>
**Version:** v0.11.3
**Editor:** @pdebuyl
**Reviewers:** @ranocha, @eviatarbach
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @navidcy. **Currently, there isn't an JOSS editor assigned** to your paper.

@navidcy if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.48 s (97.9 files/s, 18287.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           25           1721            498           4898
Markdown                        13            419              0           1047
YAML                             6             17              8            115
TOML                             3              6              0             53
-------------------------------------------------------------------------------
SUM:                            47           2163            506           6113
-------------------------------------------------------------------------------


Statistical information for the repository '0dbbb2628f154e88c486304b' was
gathered on 2021/01/30.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2996 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2996 with the following error: 

 Can't find any papers to compile :-(

**Comment by navidcy** [comment]
@whedon generate pdf from branch JOSS-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-paper. Reticulating splines etc...
```

**Comment by navidcy** [comment]
potential reviewers: rabernat, francispoulin, datseris, kburns, cesar-rocha

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02996/joss.02996/10.21105.joss.02996.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02996/joss.02996/10.21105.joss.02996.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch JOSS-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch JOSS-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4460734 is OK
- 10.5670/oceanog.2016.66 is OK
- 10.1103/PhysRevResearch.2.023068 is OK
- 10.5281/zenodo.3551326 is OK
- 10.5802/smai-jcm.63 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @leouieda - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @leouieda as editor

**Comment by whedon** [comment]
@leouieda has been invited to edit this submission.

**Comment by navidcy** [comment]
extended list of potential reviewers:
rabernat, francispoulin, datseris, kburns,
cesar-rocha, gasagna, johnfgibson,

**Comment by navidcy** [comment]
@whedon generate pdf from branch JOSS-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02996/joss.02996/10.21105.joss.02996.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02996/joss.02996/10.21105.joss.02996.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @leouieda, just wanted to ping you on this edit request

**Comment by pdebuyl** [comment]
@kyleniemeyer I can edit this

**Comment by kyleniemeyer** [comment]
Thanks @pdebuyl!

**Comment by kyleniemeyer** [comment]
@whedon assign @pdebuyl as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@whedon assign @ranocha as reviewer

**Comment by whedon** [comment]
OK, @ranocha is now a reviewer

**Comment by pdebuyl** [comment]
Hi @navidcy , I am still looking for a second reviewer. Your can suggest a reviewer (with no [conflict of interest](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy)) which I may consider if my current search is not fruitful.

**Comment by pdebuyl** [comment]
Sorry, hit the close button by accident.

**Comment by navidcy** [comment]
dpsanders, briochemc, ChrisRackauckas

If I think of more I’ll add them.

**Comment by navidcy** [comment]
@pdebuyl I'm not sure if dkarrasch would be considered having COI because he has contributed to the repository (see https://github.com/FourierFlows/GeophysicalFlows.jl/commit/a4d42fe90a920e9ab90d6d705afe61c18e553422).

**Comment by pdebuyl** [comment]
Hello @navidcy I have contacted other potential reviewers for the time being, so this should not be an issue. If I have to extend my search, I will consider the question.

**Comment by pdebuyl** [comment]
@whedon add @eviatarbach as reviewer

**Comment by whedon** [comment]
OK, @eviatarbach is now a reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3053.
