### ISSUE TITLE
[PRE REVIEW]: Generating fragment density plots in R/Bioconductor with VplotR

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2998]
**Submitting author:** @js2264 (<a href="http://orcid.org/0000-0002-4295-0624">Jacques Serizay</a>)
**Repository:** <a href="https://github.com/js2264/VplotR/" target ="_blank">https://github.com/js2264/VplotR/</a>
**Version:** v1.1.0
**Editor:** @csoneson
**Reviewers:** @henrykironde, @fgeier
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @js2264. **Currently, there isn't an JOSS editor assigned** to your paper.

@js2264 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (172.4 files/s, 31324.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               13            104            913           1792
Rmd                              1             48            119            123
YAML                             2              4              0             87
Markdown                         2             17              0             63
-------------------------------------------------------------------------------
SUM:                            18            173           1032           2065
-------------------------------------------------------------------------------


Statistical information for the repository '0cbc2f81fe41265a1bee6cc8' was
gathered on 2021/01/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
js2264                           2           352            352          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #2998 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@js2264 - I see a mention of a license in your readme, but I don't see a license file in the repository

**Comment by danielskatz** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02998/joss.02998/10.21105.joss.02998.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02998/joss.02998/10.21105.joss.02998.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch JOSS

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch JOSS
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/nmeth.2688 is OK
- 10.1186/gb-2010-11-12-r119 is OK
- 10.1101/gr.265934.120 is OK
- 10.1073/pnas.1110731108 is OK
- 10.1101/gr.192294.115 is OK
- 10.1093/nar/gkx1126 is OK
- 10.1093/bioinformatics/btw024 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @csoneson - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by js2264** [comment]
> @js2264 - I see a mention of a license in your readme, but I don't see a license file in the repository

Thanks for spotting it. Not sure why it was absent, but should be fixed now (both in JOSS and master branch)!

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @js2264 - just to say that I'm currently in the process of identifying suitable reviewers for this submission, and I have reached out to a few candidates offline. If you have suggestions, feel free to mention them here (without tagging them with an `@`).

**Comment by henrykironde** [comment]
@csoneson, feel free to tag me as a reviewer in case you don't hear from folks.

**Comment by csoneson** [comment]
Thanks @henrykironde for volunteering!

**Comment by csoneson** [comment]
@whedon assign @henrykironde as reviewer

**Comment by whedon** [comment]
OK, @henrykironde is now a reviewer

**Comment by csoneson** [comment]
@whedon add @fgeier as reviewer

**Comment by whedon** [comment]
OK, @fgeier is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3009.
