### ISSUE TITLE
[PRE REVIEW]: TAT.py: Tropospheric Analysis Tools in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2999]
**Submitting author:** @marcozennaro (<a href="http://orcid.org/0000-0002-0578-0830">Marco Zennaro</a>)
**Repository:** <a href="https://github.com/marcozennaro/tropo_paper" target ="_blank">https://github.com/marcozennaro/tropo_paper</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @marcozennaro. **Currently, there isn't an JOSS editor assigned** to your paper.

@marcozennaro if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (9.6 files/s, 1733.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         1             51              0            233
TeX                              1              9              0             69
-------------------------------------------------------------------------------
SUM:                             2             60              0            302
-------------------------------------------------------------------------------


Statistical information for the repository '3e73799cd713e42e1636832b' was
gathered on 2021/01/30.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1109/tap.2015.2418788 may be a valid DOI for title: Channel model for the surface ducts: large-scale path-loss, delay spread, and AOA
- 10.1007/978-3-319-61949-1_31 may be a valid DOI for title: Radio link planning made easy with a telegram bot

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02999/joss.02999/10.21105.joss.02999.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02999/joss.02999/10.21105.joss.02999.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@marcozennaro - this repository seems to only contain a paper.  For JOSS, we expect the submitted repository to contain the software to be reviewed, plus the paper.  See https://joss.readthedocs.io/en/latest/submitting.html

> Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software (although they may be in a short-lived branch which is never merged with the default).

**Comment by marcozennaro** [comment]
@danielskatz thanks! I hope I have solved all the issues. The software + paper are now here: 
https://github.com/STI-ICTP/TropPOLoRaTools
Is there a way to provide a new github repository?
Thanks! Marco

**Comment by arfon** [comment]
@whedon reject
