### ISSUE TITLE
[REVIEW]: opty: Software For Trajectory Optimization and Parameter Estimation Using Direct Collocation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#300]
**Submitting author:** @moorepants (<a href="http://orcid.org/0000-0002-8698-6143">Jason K. Moore</a>)
**Repository:** <a href="https://github.com/csu-hmc/opty" target ="_blank">https://github.com/csu-hmc/opty</a>
**Version:** v0.2.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @stavness
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1162870" target="_blank">10.5281/zenodo.1162870</a>

## Status

[![status](http://joss.theoj.org/papers/62e456da8057ac4e92e012bcf815d32e/status.svg)](http://joss.theoj.org/papers/62e456da8057ac4e92e012bcf815d32e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/62e456da8057ac4e92e012bcf815d32e"><img src="http://joss.theoj.org/papers/62e456da8057ac4e92e012bcf815d32e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/62e456da8057ac4e92e012bcf815d32e/status.svg)](http://joss.theoj.org/papers/62e456da8057ac4e92e012bcf815d32e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/csu-hmc/opty" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@cybanical, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/csu-hmc/opty">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.0)?
- [x] **Authorship:** Has the submitting author (@moorepants) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @cybanical it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants @tvdbogert this is where the review process happens

**Comment by Kevin-Mattheus-Moerman** [comment]
@chrisdembia our formal system currently handles a single reviewer but would you be able to act as a second reviewer on this?

**Comment by Kevin-Mattheus-Moerman** [comment]
@chrisdembia has also agreed to review.

**Comment by moorepants** [comment]
It is worth nothing that Chris is a co-author of mine (at least in the last few years) and we are good friends. I'm not sure of JOSS rules, but in other journals this would likely be a conflict of interest. FYI.

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants thank you for pointing this out. I will arrange another reviewer.

**Comment by moorepants** [comment]
Just checking in on this. It's been well over a month since I submitted.

**Comment by Kevin-Mattheus-Moerman** [comment]
:wave: @cybanical how are you getting on? Have you started the review process?

**Comment by Kevin-Mattheus-Moerman** [comment]
@demotu @siboles @stavness @melund @jslee02 I am looking for an additional reviewer for [this submission](https://github.com/csu-hmc/opty). Would you be interested in reviewing this for [JOSS](http://joss.theoj.org/)? The review guidelines are [here](http://joss.theoj.org/about#reviewer_guidelines).

**Comment by stavness** [comment]
Hi Kevin,

I'd be happy to help -- I like the idea of JOSS. I'm on vacation for the
next 3 weeks though, so I wouldn't be able to get it done until ~mid
August. Let me know if that's ok for your timeline.

Ian

**Comment by Kevin-Mattheus-Moerman** [comment]
Hey @stavness. Mid-August is fine. By then we'll hopefully have some comments from the first reviewer also. Enjoy your vacation.

**Comment by cybanical** [comment]
I've got a design review this week. Then I can take some time to getting the toolchain up and running.

**Comment by jslee02** [comment]
I'm currently in the middle of moving to a different city so my timeline would be similar to @stavness for settling down at the new place. If it's fine and still needs an additional reviewer, then I'd be happy to participate. Just let me know what you think.

**Comment by melund** [comment]
Hi @Kevin-Mattheus-Moerman. Sorry for slow reply. I am also on holiday at the moment. I see you got your second reviewer, but I don't mind helping out some other time if it is biomechanics related. Funny, I had just watched Kyles presentation on Scipy when I got this notification. JOSS is a much needed initiative.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jslee02 @melund Thanks for getting back to me. It looks like most reviewers have vacation etc. so the mid-august time-line is fine. If this submission is of interest to  you, and you have time, I would greatly appreciate if you could also help to review this submission. Our formal system handles 1 "official reviewer". But you can review by leaving comments here (i.e. based on the tick-marks at the top of this issue and http://joss.theoj.org/about#reviewer_guidelines).

**Comment by demotu** [comment]
Hi @Kevin-Mattheus-Moerman <https://github.com/kevin-mattheus-moerman>

Here is @demotu <https://github.com/demotu>. I also can review the
submission. This work interests to me so even if there are enough potential
reviewers, I will look at it.

-
Marcos Duarte
http://demotu.org/

**Comment by Kevin-Mattheus-Moerman** [comment]
Excellent. Looking forward to seeing your comments.

**Comment by cybanical** [comment]
@moorepants Is this only working on a 32-bit install? I just did a fresh anaconda py3.6 install and got this error: 
```
PackageNotFoundError: Package missing in current win-64 channels:
  - opty

```
Also, windows anaconda Anaconda is not aware of ipopt, cyipopt. 
It looks like i need to install ipopt separately. This requires cygwin or mingw.

Perhaps there could be a bit more clarity/handholding on windows based installation?

**Comment by moorepants** [comment]
@cybanical Thanks, but i do not support Windows at the moment. You can manually install ipopt and then cyipopt and it should work but I do not have the resources to get it working on windows. I suggest using a linux VM or docker image and using the install instructions in the readme.

**Comment by cybanical** [comment]
@moorepants In that case it might make sense to explicitly state that windows is not supported, rather than give partial instructions for a windows installation - it'd save some headache.

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants can you more clearly state if Windows is actively supported?
@cybanical will you still be able to review this submission? If needed I can provide you with a Linux environment for testing this software.

**Comment by Kevin-Mattheus-Moerman** [comment]
@stavness @jslee02 @melund @demotu we are getting close to mid-august :smile: I hope those who had a vacation had a good one. If you are still able, would you be willing to help review this submission? Thanks!

**Comment by moorepants** [comment]
I'm pretty sure that the software will work fine on Windows but have never tested it myself. The user would need to manually install all of the dependencies as per their Windows specific instructions. IPOPT, NumPy, SciPy, etc are not necessarily trivial to compile on Windows but one likely can find binaries. I'm happy to do bug fixes wrt to Windows but do not plan on developing installation instructions for all of the dependencies in the opty documentation, as this can be found in the respective packages' docs. I'm happy to make this clearer in the README.

**Comment by demotu** [comment]
I am reviewing this submission; it will be done by the weekend.

@demotu <https://github.com/demotu>

-
Marcos Duarte
http://demotu.org/

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @demotu you can leave review comments here. Alternatively you can open issues on [the repository for this submission](https://github.com/csu-hmc/opty) and refer to the issues here.

**Comment by stavness** [comment]
I installed the software and ran the examples. Everything went smoothly on
ubuntu. Will read the paper this week.

**Comment by Kevin-Mattheus-Moerman** [comment]
@stavness Great, thanks Ian! Let me know if you have any comments on the other aspects, such as documentation (see tickmarks at the top of this issue).

**Comment by demotu** [comment]
I tested optpy <https://github.com/csu-hmc/opty> in a Linux machine (Ubuntu
64 bits with a conda installation of Python 3.6).
The examples ran fine, with the exception of the inverted_pendulum.py; I
opened an issue on its repo.
The software and the paper comply with all the JOSS guidelines (
http://joss.theoj.org/about#reviewer_guidelines).
The paper (a summary with a few lines) is in markdown format, not in PDF as
described in the JOSS guidelines, but this is not a problem.
My congratulations to the authors for the development of optpy.

I recommend optpy <https://github.com/csu-hmc/opty> for publication in JOSS.

regards,

-
Marcos Duarte
http://demotu.org/

**Comment by stavness** [comment]
Sorry is there also a paper, or just the git repo?

**Comment by stavness** [comment]
Thanks for the clarification Kevin. Please find my review below.

The paper is missing a number of required components according to the JOSS
guidelines:

* A summary describing the high-level functionality and purpose of the
software for a diverse, non-specialist audience
— current summary is written in highly technical language, I suggest a lay
introduction followed by a more detailed technical description of the
software that includes equations to clarify what types of problems are
applicable for the software
— [optional] a full theory guide would be very beneficial for introducing
the basic concepts of direct colocation. Although this type of information
can be found in textbooks / papers (e.g. the Betts paper cited), but it can
be very helpful to include it within the software paper, as the software
authors typically have their own interpretation of the theory, and the
equations can be better matched to the software implementation. For
example, both FEBio and Simbody have excellent theory guides, which are
arguably one of the main contributions of those works.

* A clear statement of need that illustrates the purpose of the software
- Motivation should be expanded, why is this software useful, what targeted
applications?

* A list of key references including a link to the software archive
- References are not rendered in the paper.md file
- No link to software archive
- Other than Betts2010, the other citations appear to be just for
dependencies. The paper should include citations to other software for
direct colocation, and a comparison of feature sets, etc.


* Mentions (if applicable) of any ongoing research projects using the
software or recent scholarly publications enabled by it
- Needs to be added


Software license:
- acceptable
-
Documentation:
- acceptable

API documentation
- acceptable

Tests
- acceptable — uses Travis-CI

Community guidelines
- Missing, should include:
There should be clear guidelines for third-parties wishing to:
Contribute to the software
Report issues or problems with the software
Seek support
Examples


Functionality
- Installation and examples worked

**Comment by moorepants** [comment]
@stavness Thank you for the helpful review. We will work on addressing these items. They all seem reasonable, except for less-than-clear scope of a theory guide. I agree that the Simbody (have only read that one) guide is a top notch contribution, but that kind of guide seems to be an outlier. I've only seen that kind of detail in the most exceptional packages and it would take a large amount of time to create something similar. I'd rather cite textbooks/articles for this information and simply explain our implementation wrt to those. For example, I think the IPOPT software has a minimal explanation of the theory and cites the relevant literature, which I'd be more keen to replicate.

**Comment by stavness** [comment]
Yes I intended that as an optional suggestion. Definitely not required for
this publication. And the IPOPT approach would be fine too.

Congratulations on a nice piece of software!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @stavness as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stavness

**Comment by Kevin-Mattheus-Moerman** [comment]
@stavness I've spoken with @cybanical who was the primary reviewer here. He does not currently have time to continue this review so I kindly ask if you could take over. Essentially you should now be able to formally tick the boxes at the top of this review issue.

**Comment by stavness** [comment]
ok I've accepted the invitation

**Comment by jslee02** [comment]
Sorry for the late response. Below is my review based on the template. There is only one missing component according to the JOSS guidelines.

## Reviewer questions

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository**: Is the source code for this software available at the repository url?
- [x] **License**: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?
  - **comment**: The license is not being detected by Github. It would be nice to adjust `LICENSE.txt` so as to be displayed on the repository overview. (see: https://github.com/blog/2252-license-now-displayed-on-repository-overview)
- [x] **Version**: Does the release version given match the GitHub release (v0.2.0)?
- [x] **Authorship**: Has the submitting author (@moorepants) made major contributions to the software?

### Functionality

- [x] **Installation**: Does installation proceed as outlined in the documentation?
- [x] **Functionality**: Have the functional claims of the software been confirmed?
- [x] **Performance**: Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need**: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions**: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage**: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation**: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests**: Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines**: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
  - **comment**: Missing. It would be great to have one. There is a useful instruction on the de facto standard way to add a contribution guideline: https://help.github.com/articles/setting-guidelines-for-repository-contributors/.

### Software paper

- [x] **Authors**: Does the paper.md file include a list of authors with their affiliations?
- [x] **A statement of need**: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References**: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
  - **comment**: Nitpick: According to the [author guidelines of JOSS](http://joss.theoj.org/about#author_guidelines), it seems `paper.bib` is the recommended name for the file. Is there a reason that `joss.bib` was used instead?

### Minor comments

- The link at the top of the repository is http://hmc.csuohio.edu that I believe that it refers to the associated lab's website rather than the software's website. At first, I thought this is because the software website is missing but later found the link to it in `README.md` that is http://opty.readthedocs.io/. It would be great to put the link to the software website at the top of the repository, which is meant to be used so, and move the link to the lab website to somewhere else.
- All the examples worked except `examples/inverted_pendulum` printing:
```
$ python pendulum.py
Traceback (most recent call last):
  File "pendulum.py", line 48, in <module>
    import simulate
  File "/Users/jeongseoklee/dev/opty/examples/inverted_pendulum/simulate.py", line 10, in <module>
    from pydy.codegen.code import generate_ode_function
ModuleNotFoundError: No module named 'pydy.codegen.code'
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @stavness as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @stavness

**Comment by Kevin-Mattheus-Moerman** [comment]
@stavness sorry I assigned you again since I did you see you assigned at the top here.

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants were you able to address @stavness comments?

@stavness Are you able to tick some of the boxes at the top of this issue? 

@jslee02 thanks for your review! @moorepants can you address these comments as well?

**Comment by moorepants** [comment]
I am planning to address the comments. I have been bogged down with hosting a conference and then prepping two new courses. Things should calm down soon. Thanks for the reminder.

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants great. Thanks for the update.

**Comment by moorepants** [comment]
A couple of questions:

- What is the recommended way to put tables in the paper.md file?
- How do we check that the bibliography renders correctly?

**Comment by arfon** [comment]
@moorepants - the command we run is here: https://github.com/openjournals/whedon/blob/master/lib/whedon/processor.rb#L173

> How do we check that the bibliography renders correctly?

Looks like there's a small issue with your bibliography:

```
pandoc-citeproc: reference Watcher2006 not found
```

> What is the recommended way to put tables in the paper.md file?

I'm not sure sorry but the current table looks a bit wonky: [10.21105.joss.00300.pdf](https://github.com/openjournals/joss-reviews/files/1420197/10.21105.joss.00300.pdf)

Do any of the @openjournals/joss-editors know how to fix this?

**Comment by moorepants** [comment]
I wasn't sure if there was a spec for making tables in markdown so I made an restructuredtext table and just wrapped in in markdown literal ticks for the time being. I knew it would render as is.

Is there a simple way to run that command on my computer? I'm not familiar with Ruby.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon obviously we could use [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables ), [HTML](https://www.w3schools.com/html/html_tables.asp), or [LATEX](https://en.wikibooks.org/wiki/LaTeX/Tables) tables. But I'm not sure how the process of creating the PDF handles these. Does normal Markdown table stuff work? 

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | Nice |
| col 2 is      | centered      |   Fits well |
| zebra stripes | are neat      |    3.14159265359 |

**Comment by moorepants** [comment]
So Github flavored markdown has the table support that you sow above: https://help.github.com/articles/organizing-information-with-tables/, but this isn't in all markdown flavors. It isn't clear to me in the ruby code which flavor of markdown is being used. Pandoc can process a number of them apparently.

**Comment by arfon** [comment]
> Is there a simple way to run that command on my computer? I'm not familiar with Ruby.

```
      `cd #{paper_directory} && pandoc \
      -V repository="#{repository_address}" \
      -V archive_doi="#{archive_doi}" \
      -V paper_url="#{paper_url}" \
      -V formatted_doi="#{formatted_doi}" \
      -V review_issue_url="#{review_issue_url}" \
      -V graphics="true" \
      -V issue="#{paper_issue}" \
      -V volume="#{paper_volume}" \
      -V page="#{review_issue_id}" \
      -V joss_logo_path="#{Dir.pwd}/resources/joss-logo.png" \
      -V year="#{paper_year}" \
      -V formatted_doi="#{formatted_doi}" \
      -V citation_author="#{citation_author}" \
      -V paper_title="#{paper_title}" \
      -S -o #{filename_doi}.pdf -V geometry:margin=1in \
      --latex-engine=xelatex \
      --filter pandoc-citeproc #{File.basename(paper_path)} \
      --template #{latex_template_path}
```

The command above is just passing a bunch of variables in but it's a normal(ish) pandoc command so if you have pandoc installed locally you should be able to do something like:

```
pandoc  -S -o paper.pdf --latex-engine=xelatex --filter pandoc-citeproc paper.md --template latex.template 
```
...where the `latex.template` is [this file](https://github.com/openjournals/whedon/blob/master/resources/latex.template). I'm also happy to try compiling the document a few times with you if you want to debug this here. In the future we plan to give @whedon the ability to compile the PDF on demand for you.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00300/10.21105.joss.00300.pdf
```

**Comment by moorepants** [comment]
That's cool! FYI, still working on the review. I have a few more issues to close, just don't have time at the moment. Maybe I can finish over our Thanksgiving break.

**Comment by Kevin-Mattheus-Moerman** [comment]
Cool eh :smile: btw,  in your paper one reference shows ???, it is @Watcher2006 should that be @Watcher2006?

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants thanks for the update. Let me know when we can resume review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants any updates to present? It would be good to keep going here.

**Comment by Kevin-Mattheus-Moerman** [comment]
@stavness Are you able to start ticking some of the boxes at the top of this review issue?

**Comment by stavness** [comment]
I'm waiting for the revised version, and then I'll look at that time.

**Comment by moorepants** [comment]
I apologize, my revision stalled due to other priorities. This is near the top of my task list, so I except to finalize this month.

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants great. Thanks for the update.

**Comment by moorepants** [comment]
We have made all of the changes requested by the reviewers. You can see an issue for each reviewer comment here:

https://github.com/csu-hmc/opty/issues?q=is%3Aissue+is%3Aclosed+label%3Ajoss

And pull requests that close all of these issues here:

https://github.com/csu-hmc/opty/pulls?q=is%3Apr+is%3Aclosed+label%3Ajoss

I have not made a new release of opty yet, so testing from the master branch is required. I would prefer to make the release after the review is done so that I can incorporate all of the changes into the release.

The documentation reflects the master branch:

https://github.com/csu-hmc/opty/pulls?q=is%3Apr+is%3Aclosed+label%3Ajoss

Thanks for your patience.

cc @tvdbogert

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00300/joss.00300/10.21105.joss.00300.pdf
```

**Comment by moorepants** [comment]
Editors, I switched to an HTML table in the markdown file since HTML can be put into markdown files but the PDF does not render the table correctly. Any suggestions on getting a table in the paper?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon any suggestions for @moorepants?

**Comment by arfon** [comment]
Not really sorry. @karthik - your Markdown-fu exceeds that of most - any ideas here?

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants @arfon I tested the local paper build myself.  I was able to get it to create markdown based tables without any issues. What was your issue? Do you perhaps have a table syntax error somewhere? 

I did notice that your particular table will spill beyond the margins using pandoc (for both HTML and markdown).  [Here is a link](https://pandoc.org/MANUAL.html#pandocs-markdown) to how to create tables in pandoc markdown. HTML is not listed there and I could not get that to work. 

Is it an idea to render a picture of the table in the right layout and to render the image in markdown instead instead? I suppose the references would not show up.... sigh... this is difficult!

**Comment by arfon** [comment]
I wonder if we could put the table on its own page and hack the LaTeX template to make this happen. Some ideas here: https://stackoverflow.com/questions/25849814/rstudio-rmarkdown-both-portrait-and-landscape-layout-in-a-single-pdf

**Comment by karthik** [comment]
@arfon I don't have a good solution unfortunately. :(

**Comment by moorepants** [comment]
Is it possible to use the markdown "grid-tables" extension? I already have the table typed up like that. If not I can try converting the first table option on the pandoc markdown documentation.

**Comment by arfon** [comment]
> Is it possible to use the markdown "grid-tables" extension? I already have the table typed up like that. If not I can try converting the first table option on the pandoc markdown documentation.

Sure thing. Let's give that a go. Are those commits in `master`?

**Comment by moorepants** [comment]
No, I will need to reformat the table. Will work on it.

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00300/joss.00300/10.21105.joss.00300.pdf
```

**Comment by moorepants** [comment]
I have updated the `paper.md` file to make use of the footnotes and grid-tables extensions listed here:

https://pandoc.org/MANUAL.html

**Comment by moorepants** [comment]
It is close now. Is it possible to choose a smaller font for the table? This is possible in LaTeX.

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00300/joss.00300/10.21105.joss.00300.pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
Sorry I'm not sure how to change the font locally. @arfon @karthik any ideas?

**Comment by moorepants** [comment]
I just found this: https://pandoc.org/MANUAL.html#extension-raw_tex

It may be easier to just write the document in LaTeX using this extension. I'll give it a try too. I haven't been able to figure out how to manipulate the font size of the table using markdown.

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00300/joss.00300/10.21105.joss.00300.pdf
```

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00300/joss.00300/10.21105.joss.00300.pdf
```

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00300/joss.00300/10.21105.joss.00300.pdf
```

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00300/joss.00300/10.21105.joss.00300.pdf
```

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00300/joss.00300/10.21105.joss.00300.pdf
```

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00300/joss.00300/10.21105.joss.00300.pdf
```

**Comment by moorepants** [comment]
The table fits now. It isn't perfect but it is too difficult to try to fine tune it via markdown and limited control of the LaTeX source. We can go with this.

**Comment by arfon** [comment]
OK thanks @moorepants. @Kevin-Mattheus-Moerman - is this submission good to accept now? The checklist at the top of the review isn't filled but it sounds like we might be done based on other comments in the thread.

**Comment by stavness** [comment]
Looks great!. I went through the checklist and checked all the boxes.

**Comment by Kevin-Mattheus-Moerman** [comment]
Awesome! Thanks for the review @stavness 🚀  🎉

**Comment by Kevin-Mattheus-Moerman** [comment]
@moorepants can you provide a DOI of the reviewed software (e.g. through Zenodo)? Then @arfon can proceed to formally accept this submission.

**Comment by moorepants** [comment]
I will package a new release of the software, push to PyPi, conda, and then Zenodo for archival purposes. Note that the version number will go up.

Do we not need to get @jslee02 @cybanical and @demotu's final approval? I addressed comments from all of them in the new version.

**Comment by moorepants** [comment]
I've pushed version 1.0.0 to Zenodo:

DOI: 10.5281/zenodo.1162870

https://zenodo.org/record/1162870

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1162870 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1162870" target="_blank">10.5281/zenodo.1162870</a> is the archive.

**Comment by arfon** [comment]
@stavness @demotu - many thanks for your reviews here and to @Kevin-Mattheus-Moerman for editing this submission ✨ 

@moorepants - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00300 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00300/status.svg)](https://doi.org/10.21105/joss.00300)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00300/status.svg)](https://doi.org/10.21105/joss.00300)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html

**Comment by moorepants** [comment]
Thanks everyone. I appreciate the time and effort spent on reviewing this.
