### ISSUE TITLE
[PRE REVIEW]: kuibit: Analyzing Einstein Toolkit simulations with Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3003]
**Submitting author:** @sbozzolo (<a href="http://orcid.org/0000-0003-3696-6408">Gabriele Bozzola</a>)
**Repository:** <a href="https://github.com/Sbozzolo/kuibit/" target ="_blank">https://github.com/Sbozzolo/kuibit/</a>
**Version:** 1.0.0
**Editor:** @eloisabentivegna
**Reviewers:** @yurlungur, @eloisabentivegna
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sbozzolo. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @eloisabentivegna.

@sbozzolo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3003 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.59 s (147.0 files/s, 41166.3 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           37           4079           6928           8231
reStructuredText                 27            572            418           1394
Jupyter Notebook                  6              0           1518            274
Markdown                          3             58              0            185
Bourne Again Shell                6             30             54             93
INI                               3              3              0             79
YAML                              1             13              3             65
TOML                              2             13              3             50
make                              1              4              7              9
--------------------------------------------------------------------------------
SUM:                             86           4772           8931          10380
--------------------------------------------------------------------------------


Statistical information for the repository '941450f6df4d37bc2caaa99a' was
gathered on 2021/02/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Gabriele Bozzola               187         26885           7645           99.99
deepsource-autofix[b             1             0              2            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Gabriele Bozzola          19238           71.6          3.4               19.22
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from joss-paper

**Comment by whedon** [comment]
PDF failed to compile for issue #3003 with the following error: 

 Can't find any papers to compile :-(

**Comment by Sbozzolo** [comment]
I never entered the branch where the paper is (did I miss that?), so I guess that's the problem. The paper is in the `joss-paper` branch and compiles successfully.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss-paper

(whoops, my command was incorrect)

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03003/joss.03003/10.21105.joss.03003.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03003/joss.03003/10.21105.joss.03003.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @eloisabentivegna, the author suggested you to edit this submission—I also see that you contributed to the Einstein Toolkit itself, so this seems like a great fit!

**Comment by kyleniemeyer** [comment]
@whedon invite @eloisabentivegna as editor

**Comment by whedon** [comment]
@eloisabentivegna has been invited to edit this submission.

**Comment by Sbozzolo** [comment]
Hi @kyleniemeyer.

Thank you for pre-editing my submission. 

I pushed a commit addressing your comment. Please let me know if there's a better way to do this.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03003/joss.03003/10.21105.joss.03003.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03003/joss.03003/10.21105.joss.03003.pdf) :page_facing_up: :point_left:

**Comment by eloisabentivegna** [comment]
> Hi @eloisabentivegna, the author suggested you to edit this submission—I also see that you contributed to the Einstein Toolkit itself, so this seems like a great fit!

Indeed @kyleniemeyer, this is right up my alley. 🙂

**Comment by eloisabentivegna** [comment]
@whedon assign @eloisabentivegna as editor

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by Sbozzolo** [comment]
Is there any update on this submission?

Thanks

**Comment by eloisabentivegna** [comment]
Hi @Sbozzolo, I am currently looking for reviewers. Feel free to suggest good candidates, if you know of any!

**Comment by Sbozzolo** [comment]
I think that maintainers of the Einstein Toolkit could be a good fit. Other than that, I don't have any suggestion.

Thanks again

**Comment by eloisabentivegna** [comment]
@whedon add @yurlungur as reviewer

**Comment by whedon** [comment]
OK, @yurlungur is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon add @eloisabentivegna as reviewer

**Comment by whedon** [comment]
OK, @eloisabentivegna is now a reviewer

**Comment by eloisabentivegna** [comment]
@Sbozzolo, finding reviewers is taking longer than expected. I have added myself as a reviewer and will start the actual review issue now, but will continue looking for a third reviewer in the meantime.

**Comment by eloisabentivegna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3099.

**Comment by Sbozzolo** [comment]
Thank you very much, @eloisabentivegna. I really appreciate it.
