### ISSUE TITLE
[PRE REVIEW]: gmr: Gaussian Mixture Regression

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3004]
**Submitting author:** @AlexanderFabisch (<a href="http://orcid.org/0000-0003-2824-7956">Alexander Fabisch</a>)
**Repository:** <a href="https://github.com/AlexanderFabisch/gmr" target ="_blank">https://github.com/AlexanderFabisch/gmr</a>
**Version:** 1.4
**Editor:** @mikldk
**Reviewers:** @vs74, @inakleinbottle
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @AlexanderFabisch. **Currently, there isn't an JOSS editor assigned** to your paper.

@AlexanderFabisch if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (396.2 files/s, 52093.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          19            539            677           1522
Markdown                         1             23              0            128
TeX                              1              5              0             61
reStructuredText                 1             57             45             51
SVG                              1              0              0             34
YAML                             1              0              0             14
-------------------------------------------------------------------------------
SUM:                            24            624            722           1810
-------------------------------------------------------------------------------


Statistical information for the repository 'e9b0a6c4140f716fa8fd041a' was
gathered on 2021/02/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alexander Fabisch              106          3381            642           99.48
Joao Felipe Santos               2            10             11            0.52

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alexander Fabisch          2730           80.7         36.9                5.60
Joao Felipe Santos            8           80.0         69.1                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TSMCB.2006.886952 is OK
- 10.1016/j.neunet.2015.05.005 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03004/joss.03004/10.21105.joss.03004.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03004/joss.03004/10.21105.joss.03004.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @terrytangyuan, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @terrytangyuan as editor

**Comment by whedon** [comment]
@terrytangyuan has been invited to edit this submission.

**Comment by terrytangyuan** [comment]
Sorry I am a little overloaded at the moment and it would be great if you could find others to edit.

**Comment by kyleniemeyer** [comment]
@terrytangyuan that's alright, will do.

@mikldk, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@AlexanderFabisch - thanks for this submission. 

Can you please maybe comment on how your contribution relates to the `mclust` package in `R`, see e.g. <https://mclust-org.github.io/mclust/> where also a few publications are mentioned, including Fraley C. and Raftery A. E. (2002) *Model-based clustering, discriminant analysis and density estimation*, Journal of the American Statistical Association, 97/458, pp. 611-631.

Do you have any suggestions for reviewers?

**Comment by AlexanderFabisch** [comment]
Hi @mikldk,

if I didn't miss anything, mclust focuses on clustering and density estimation, while gmr focuses on multimodal regression. mclust is an R package and gmr is a Python package.

I am sorry, I don't have any suggestion for a reviewer, requirements would be knowledge about Python and machine learning or something similar.

**Comment by mikldk** [comment]
@oesteban, @benjamin-lee: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@oesteban, @benjamin-lee: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@juliensiebert, @acguidoum: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by Benjamin-Lee** [comment]
I'm always happy to help with JOSS reviews but this is out of my area. Sorry I can't help!

**Comment by mikldk** [comment]
@vs74, @inakleinbottle: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by vs74** [comment]
Hey @mikldk, thanks for tagging me. I would be glad to review this submission.

**Comment by inakleinbottle** [comment]
@mikldk I'd be happy to review the submission.

**Comment by mikldk** [comment]
@whedon assign @vs74 as reviewer

**Comment by whedon** [comment]
OK, @vs74 is now a reviewer

**Comment by mikldk** [comment]
@whedon add @inakleinbottle as reviewer

**Comment by whedon** [comment]
OK, @inakleinbottle is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3054.
