### ISSUE TITLE
[PRE REVIEW]: gaussplotR: Fit, Predict and Plot 2D Gaussians in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3005]
**Submitting author:** @vbaliga (<a href="http://orcid.org/0000-0002-9367-8974">Vikram B. Baliga</a>)
**Repository:** <a href="https://github.com/vbaliga/gaussplotR" target ="_blank">https://github.com/vbaliga/gaussplotR</a>
**Version:** v0.2.3
**Editor:** @KristinaRiemer
**Reviewers:** @cddesja, @brunaw
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vbaliga. **Currently, there isn't an JOSS editor assigned** to your paper.

@vbaliga if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1152/jn.1994.71.6.2517 is OK
- 10.1523/JNEUROSCI.23-13-05650.2003 is OK
- 10.1152/jn.00921.2005 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (585.4 files/s, 110460.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            21           1068            260           4534
R                               19            363            768           2192
Markdown                         7            187              0            780
CSS                              3             99             48            428
JavaScript                       3             64             32            256
JSON                             1              0              0            180
Rmd                              4            166            417            159
YAML                             4             27              2            137
TeX                              1              2              0             43
XML                              1              0              0             42
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            65           1976           1528           8762
-------------------------------------------------------------------------------


Statistical information for the repository '58b69e12553444d149bce8bf' was
gathered on 2021/02/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vikram Baliga                    1           352              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vikram Baliga               352          100.0          0.0                9.09
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03005/joss.03005/10.21105.joss.03005.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03005/joss.03005/10.21105.joss.03005.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hello @vbaliga, this pre-review issue is where we find an editor, reviewers, and also resolve any obvious issues.

Your paper is currently missing an explicit Statement of Need section that illustrates the research purpose of the software, which is one of our [required paper elements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Can you please add this?

**Comment by kyleniemeyer** [comment]
Hi @KristinaRiemer, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @KristinaRiemer as editor

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by vbaliga** [comment]
Hi @kyleniemeyer , thanks for your feedback. I have just updated the paper to make the Statement of Need more clear by making it its own section. This change was made in https://github.com/vbaliga/gaussplotR/commit/e4ef931e1726213b776b6c1112d66173165c9f12

Please let me know if there's anything else you'd like me to address. And thanks for getting this submission into the queue for consideration!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03005/joss.03005/10.21105.joss.03005.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03005/joss.03005/10.21105.joss.03005.pdf) :page_facing_up: :point_left:

**Comment by KristinaRiemer** [comment]
@kyleniemeyer I can edit this submission.

**Comment by KristinaRiemer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @KristinaRiemer

**Comment by KristinaRiemer** [comment]
@becarioprecario @emilyriederer @cddesja would any of you be able and willing to review this JOSS submission?

**Comment by becarioprecario** [comment]
Thanks for the invitation, but I am not available for making reviews at the moment.

El 8 feb 2021, a las 20:41, Kristina Riemer <notifications@github.com<mailto:notifications@github.com>> escribió:



@becarioprecario<https://github.com/becarioprecario> @emilyriederer<https://github.com/emilyriederer> @cddesja<https://github.com/cddesja> would any of you be able and willing to review this JOSS submission?

**Comment by emilyriederer** [comment]
I'm so sorry. Similarly, I'd really like to but I'm afraid I'm a bit overextended right now and probably shouldn't take on something else. Looks like a neat package!

**Comment by cddesja** [comment]
Sure, I can do this.

**Comment by KristinaRiemer** [comment]
Thank you for following up @becarioprecario and @emilyriederer, and thanks @cddesja for offering to be a reviewer! 

I'm still looking for a second reviewer for this JOSS submission then. Would @brunaw, @daviddewhurst, or @rchew be able and willing to review?

**Comment by brunaw** [comment]
@KristinaRiemer Certainly, let me know when I can start reviewing

**Comment by KristinaRiemer** [comment]
Great, thanks so much @brunaw!

**Comment by KristinaRiemer** [comment]
@whedon assign @cddesja as reviewer

**Comment by whedon** [comment]
OK, @cddesja is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon add @brunaw as reviewer

**Comment by whedon** [comment]
OK, @brunaw is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3074.

**Comment by KristinaRiemer** [comment]
Hi @cddesja and @brunaw, the actual review will happen in the issue linked to above. If you go over there, you'll see a checklist that you can use to guide your review, and you should feel free to create relevant issues in the project's GitHub repo. Let me know over there if you have any questions or concerns!
