### ISSUE TITLE
[PRE REVIEW]: Simulating instrumental systematics of Cosmic Microwave Background experiments with s4cmb

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3006]
**Submitting author:** @JulienPeloton (<a href="http://orcid.org/0000-0002-8560-4449">Julien Peloton</a>)
**Repository:** <a href="https://github.com/JulienPeloton/s4cmb" target ="_blank">https://github.com/JulienPeloton/s4cmb</a>
**Version:** 1.0
**Editor:** @mbobra
**Reviewers:** @Christovis, @changhoonhahn
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JulienPeloton. **Currently, there isn't an JOSS editor assigned** to your paper.

@JulienPeloton if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3006 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.26 s (188.6 files/s, 60275.6 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           30           2056           5625           6719
Fortran 90                        4             88            140            265
reStructuredText                  4             82             11            216
Bourne Again Shell                5             51             61            166
YAML                              3             12              0            101
make                              1              4              1             29
Dockerfile                        1              8              4             12
Bourne Shell                      1              1              6              6
--------------------------------------------------------------------------------
SUM:                             49           2302           5848           7514
--------------------------------------------------------------------------------


Statistical information for the repository 'dbf7ce0f3e1550f2d4d36242' was
gathered on 2021/02/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Joy Didier                       1           315              0            0.90
Julien                          32          3277           1912           14.81
Mark Mirmelstein                 6            63             25            0.25
Reijo Keskitalo                  2            33             27            0.17
gfabbian                        20           632            254            2.53
mark                             3           180             48            0.65
peloton                        251         20124           8157           80.69

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Joy Didier                  315          100.0         38.2               37.78
Julien                     3247           99.1          1.7               16.01
Mark Mirmelstein             32           50.8         23.5                9.38
Reijo Keskitalo               9           27.3         38.4               11.11
gfabbian                    357           56.5          8.5                7.00
mark                         76           42.2          1.4               11.84
peloton                   10364           51.5         40.6               12.07
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch 56/joss/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 56/joss/paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3006 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch issues/56/joss/paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch issues/56/joss/paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3006 with the following error: 

 Can't find any papers to compile :-(

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch issues/56/joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch issues/56/joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03006/joss.03006/10.21105.joss.03006.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03006/joss.03006/10.21105.joss.03006.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Whew, sorry @JulienPeloton, I could not seem to get the branch correct there... can you confirm that is the correct paper location?

We use this pre-review issue to assign the editor and reviewers, and resolve any obvious issues.

**Comment by kyleniemeyer** [comment]
Hi @mbobra, can you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by JulienPeloton** [comment]
Hi @kyleniemeyer, @mbobra 

I confirm this is the correct paper location. The paper lives in 
- repo: https://github.com/JulienPeloton/s4cmb
- branch `issues/56/joss`
- folder: `paper/`

Note that it compiled correctly from the Whedon paper preview service ([link](https://whedon.theoj.org/)). Shall I move the files under the root of the repo instead of `paper/` to ease the review process?

**Comment by kyleniemeyer** [comment]
@JulienPeloton no need, whedon finds the paper easily enough—I just wanted to check that the branch was correct.

**Comment by mbobra** [comment]
@kyleniemeyer Yes, no problem!

**Comment by mbobra** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by Christovis** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
I'm sorry @Christovis, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by mbobra** [comment]
Thanks for agreeing to review, @Christovis! I really appreciate it.

**Comment by mbobra** [comment]
@whedon assign @Christovis as reviewer

**Comment by whedon** [comment]
OK, @Christovis is now a reviewer

**Comment by mbobra** [comment]
@whedon add @changhoonhahn as reviewer

**Comment by whedon** [comment]
OK, @changhoonhahn is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3022.

**Comment by mbobra** [comment]
👋 @Christovis @changhoonhahn See you over in #3022 where the actual review will take place!
