### ISSUE TITLE
[PRE REVIEW]: IGRINS RV: A Python Package for Precision Radial Velocities with Near-Infrared Spectra

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3007]
**Submitting author:** @shihyuntang (<a href="http://orcid.org/0000-0003-4247-1401">Shih-Yun Tang</a>)
**Repository:** <a href="https://github.com/shihyuntang/igrins_rv" target ="_blank">https://github.com/shihyuntang/igrins_rv</a>
**Version:** v0.9.6-beta.1
**Editor:** @dfm
**Reviewers:** @jmbrewer, @gully
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @shihyuntang. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@shihyuntang if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.14 s (51.8 files/s, 18441.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          38           2448           2559           8997
TeX                              2            504              6           5077
Cython                           1            105            164            274
reStructuredText                11            103             86            211
Markdown                         3             43              0            172
make                             1             30              6            156
Bourne Shell                     2             10              1             36
YAML                             1              0              0             19
-------------------------------------------------------------------------------
SUM:                            59           3243           2822          14942
-------------------------------------------------------------------------------


Statistical information for the repository '999a0ec7787d69cfc56179c2' was
gathered on 2021/02/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
astahl7                        716         48676          42331           41.05
sytang                        1870         72430          58255           58.95

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
astahl7                    4568            9.4          2.6               12.28
sytang                     9436           13.0          5.7               13.09
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03007/joss.03007/10.21105.joss.03007.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03007/joss.03007/10.21105.joss.03007.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637X/721/2/1861 is OK
- 10.1111/j.1365-2966.2011.19960.x is OK
- 10.1093/mnras/stw706 is OK
- 10.1086/672273 is OK
- 10.1051/0004-6361/201834917 is OK
- 10.1051/0004-6361/201629749 is OK
- 10.1051/0004-6361/201935979 is OK
- 10.3847/0004-637X/816/2/69 is OK
- 10.1086/301443 is OK
- 10.1063/1.3274199 is OK
- 10.3847/1538-3881/aa9ed7 is OK
- 10.1088/0067-0049/187/1/149 is OK
- 10.3847/1538-3881/aacb21 is OK
- 10.1038/nature05525 is OK
- 10.3847/1538-3881/aaf477 is OK
- 10.1051/0004-6361/201425481 is OK
- 10.1088/0004-637X/774/1/53 is OK
- 10.1086/428639 is OK
- 10.2458/azu_uapress_9780816531240-ch029 is OK
- 10.1051/0004-6361/201629922 is OK
- 10.3847/0004-637X/829/2/114 is OK
- 10.1086/524706 is OK
- 10.1007/BF00699735 is OK
- 10.1086/156357 is OK
- 10.1051/0004-6361/201629882 is OK
- 10.1126/science.1185402 is OK
- 10.1051/0004-6361:200500201 is OK
- 10.1051/0004-6361/201323266 is OK
- 10.1051/0004-6361/201833675 is OK
- 10.1051/0004-6361:20066021 is OK
- 10.1051/0004-6361/201525741 is OK
- 10.1038/nature11161 is OK
- 10.1086/133755 is OK
- 10.1086/310444 is OK
- 10.1086/504701 is OK
- 10.3847/1538-3881/aa66ca is OK
- 10.1051/0004-6361/201730831 is OK
- 10.3847/1538-3881/153/2/81 is OK
- 10.1086/590227 is OK
- 10.1016/j.jqsrt.2004.05.058 is OK
- 10.1088/0004-6256/147/4/82 is OK
- 10.3847/1538-3881/aacead is OK
- 10.1093/mnras/stw149 is OK
- 10.1088/0004-637X/735/2/78 is OK
- 10.1088/0004-637X/761/2/164 is OK
- 10.1109/18.57199 is OK
- 10.1038/nature18293 is OK
- 10.3847/1538-4357/aafe09 is OK
- 10.3847/2041-8213/ab4c99 is OK
- 10.1146/annurev-astro-081817-051853 is OK
- 10.1117/12.459907 is OK
- 10.1051/0004-6361:200810355 is OK
- 10.1038/nature18305 is OK
- 10.1093/mnras/stw2904 is OK
- 10.1088/0004-637X/796/2/132 is OK
- 10.1086/305670 is OK
- 10.1051/0004-6361:200809460 is OK
- 10.1051/eas/1041035 is OK
- 10.1051/0004-6361/201219981 is OK
- 10.1038/nature14501 is OK
- 10.1086/379137 is OK
- 10.3847/0004-637X/818/1/34 is OK
- 10.1051/0004-6361:20066929 is OK
- 10.5281/zenodo.1998447 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.3847/1538-4357/aa74ca is OK
- 10.1051/0004-6361/201014005 is OK
- 10.1086/428383 is OK
- 10.3847/2041-8213/ab276d is OK
- 10.1088/0004-6256/150/5/150 is OK
- 10.1088/2041-8205/714/2/L222 is OK
- 10.1086/118137 is OK
- 10.3847/0004-637X/820/2/89 is OK
- 10.3847/1538-3881/aa80eb is OK
- 10.1088/1538-3873/aaaaa8 is OK
- 10.3847/1538-4357/aaae09 is OK
- 10.3847/1538-4357/aaca2e is OK
- 10.1093/mnras/stt2108 is OK
- 10.1111/j.1365-2966.2011.19915.x is OK
- 10.1093/mnras/sty290 is OK
- 10.1016/j.jqsrt.2017.06.038 is OK
- 10.3847/1538-4357/aad0a0 is OK
- 10.1086/319956 is OK
- 10.1086/378365 is OK
- 10.1086/499928 is OK
- 10.1117/12.158684 is OK
- 10.1088/0004-6256/148/3/53 is OK
- 10.3847/1538-3881/ab5d3a is OK
- 10.1093/mnras/stz1230 is OK
- 10.1093/mnras/staa315 is OK
- 10.1086/307954 is OK
- 10.1093/mnras/sty328 is OK
- 10.2458/azu_uapress_9780816531240-ch028 is OK
- 10.1086/508233 is OK
- 10.1088/0004-6256/140/6/2025 is OK
- 10.1086/383340 is OK
- 10.1088/0004-637X/808/1/23 is OK
- 10.1117/12.317217 is OK
- 10.1086/676406 is OK
- 10.3847/0004-637X/825/2/98 is OK
- 10.3847/1538-4357/aae317 is OK
- 10.1051/0004-6361:200810596 is OK
- 10.1086/526415 is OK
- 10.1051/0004-6361/201219058 is OK
- 10.1088/0004-637X/767/2/112 is OK
- 10.1093/mnras/sty626 is OK
- 10.1088/0004-637X/795/1/65 is OK
- 10.1086/519017 is OK
- 10.3847/0004-637X/826/2/206 is OK
- 10.1051/0004-6361:20041864 is OK
- 10.1088/2041-8205/741/1/L2 is OK
- 10.3847/1538-3881/ab6e66 is OK
- 10.3847/2041-8213/ab59d9 is OK
- 10.3847/2041-8213/aa861f is OK
- 10.1051/0004-6361/201322428 is OK
- 10.1117/12.2055075 is OK
- 10.3847/2515-5172/aac887 is OK
- 10.1088/0004-637X/786/2/132 is OK
- 10.1093/mnras/sty2108 is OK
- 10.1016/j.icarus.2008.02.017 is OK
- 10.1051/0004-6361/201731340 is OK
- 10.1051/0004-6361:20065014 is OK
- 10.1051/0004-6361/200913347 is OK
- 10.5281/zenodo.845059 is OK
- 10.3847/1538-4357/aa6fb3 is OK
- 10.1088/0004-6256/145/4/102 is OK
- 10.1051/0004-6361/200811577 is OK
- 10.1088/0004-637X/717/2/1291 is OK
- 10.1088/0004-637X/780/1/61 is OK
- 10.3847/1538-3881/aaa841 is OK
- 10.1051/0004-6361/201834491 is OK
- 10.1111/j.1365-2966.2010.18193.x is OK
- 10.1093/mnras/stx1558 is OK
- 10.3847/2041-8213/834/2/L17 is OK
- 10.3847/1538-4357/ab6605 is OK
- 10.1088/0004-637X/758/1/31 is OK
- 10.1117/12.2232780 is OK
- 10.1117/12.2312345 is OK
- 10.1117/12.926102 is OK
- 10.1086/345520 is OK
- 10.1086/512759 is OK
- 10.3847/0004-6256/152/3/61 is OK
- 10.3847/1538-3881/aa9791 is OK
- 10.1086/316516 is OK
- 10.1086/505343 is OK
- 10.1038/378355a0 is OK
- 10.1143/PTP.64.544 is OK
- 10.1051/0004-6361/201118457 is OK
- 10.1086/590948 is OK
- 10.1126/science.279.5347.69 is OK
- 10.1088/0004-637X/693/1/23 is OK
- 10.1093/mnras/sty2267 is OK
- 10.1007/978-3-319-55333-7_139 is OK
- 10.1126/science.aat5348 is OK
- 10.1088/2041-8205/743/1/L16 is OK
- 10.3847/0004-6256/152/3/75 is OK
- 10.3847/2041-8213/aaada9 is OK
- 10.3847/1538-4357/ab2f7f is OK
- 10.1111/j.1365-2966.2012.21481.x is OK
- 10.1088/0004-637X/775/2/105 is OK
- 10.3847/0004-637X/816/1/34 is OK
- 10.3847/1538-4357/aa890a is OK
- 10.1146/annurev-earth-053018-060246 is OK
- 10.1007/s11214-018-0472-y is OK
- 10.1117/12.2056431 is OK
- 10.1088/0004-637X/746/2/154 is OK
- 10.1093/mnras/stw1300 is OK
- 10.1088/0004-637X/799/1/27 is OK
- 10.1088/0004-637X/805/1/75 is OK
- 10.1038/s41586-020-2400-z is OK
- 10.1006/icar.1996.0190 is OK
- 10.1086/593201 is OK
- 10.1086/341174 is OK
- 10.1088/0004-637X/787/1/27 is OK
- 10.1086/428899 is OK
- 10.1093/mnras/stu2060 is OK
- 10.1126/science.274.5289.954 is OK
- 10.1093/mnrasl/slu011 is OK
- 10.1117/12.2232064 is OK
- 10.3847/1538-3881/aab605 is OK
- 10.1051/0004-6361/201322175 is OK
- 10.1093/mnras/stv207 is OK
- 10.1088/2041-8205/753/1/L25 is OK
- 10.1086/505967 is OK
- 10.1051/0004-6361/201526416 is OK
- 10.1016/j.jqsrt.2004.10.008 is OK
- 10.1088/0004-6256/145/6/162 is OK
- 10.1093/mnras/stw2297 is OK
- 10.1088/0031-8949/90/5/054005 is OK
- 10.1051/0004-6361/201527042 is OK
- 10.1051/0004-6361/201833694 is OK
- 10.1086/521346 is OK
- 10.1051/0004-6361:200810174 is OK
- 10.1051/0004-6361/200913782 is OK
- 10.1086/508980 is OK
- 10.3847/1538-4357/aa78f1 is OK
- 10.1086/498708 is OK
- 10.1051/0004-6361/201526599 is OK
- 10.1038/s41586-018-0067-5 is OK
- 10.3847/1538-3881/aa5eb9 is OK
- 10.3847/1538-4357/833/2/175 is OK
- 10.3847/2041-8213/aa8d70 is OK
- 10.3847/1538-4357/aa774a is OK
- 10.1086/674012 is OK
- 10.1051/0004-6361/200913913 is OK
- 10.1007/978-3-319-55333-7_2 is OK
- 10.1086/346193 is OK
- 10.1088/1538-3873/128/965/075002 is OK
- 10.1086/678764 is OK
- 10.3847/1538-3881/aac894 is OK
- 10.1088/0004-6256/142/2/60 is OK
- 10.1088/0004-637X/755/1/42 is OK
- 10.1093/mnras/sty1783 is OK
- 10.1038/nature01448 is OK
- 10.1086/383347 is OK
- 10.1086/587036 is OK
- 10.1117/12.176725 is OK
- 10.1088/0004-637X/723/1/954 is OK
- 10.3847/1538-4357/aa8868 is OK
- 10.1006/icar.1996.5647 is OK
- 10.1146/annurev-astro-081710-102548 is OK
- 10.1086/430523 is OK
- 10.1088/0004-637X/735/2/109 is OK
- 10.1093/mnras/stx009 is OK
- 10.1117/12.856864 is OK
- 10.3847/1538-4357/aa98df is OK

MISSING DOIs

- 10.1093/comjnl/8.1.42 may be a valid DOI for title: A new method of constrained optimization and a comparison with other methods
- 10.1016/j.jcp.2015.10.035 may be a valid DOI for title: High-order wavelet reconstruction/differentiation filters and Gibbs phenomena
- 10.3847/1538-3881/aad230 may be a valid DOI for title: An update to the EVEREST K2 pipeline: Short cadence, saturated stars, and Kepler-like photometry down to Kp = 15
- 10.3847/2041-8213/ab9530 may be a valid DOI for title: Irradiated ocean planets bridge super-Earth and sub-Neptune populations

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @shihyuntang, we use this pre-review issue to identify an editor and reviewers, and also fix any obvious issues.

Your paper is currently missing a Statement of Need section that clearly illustrates the research purpose of the software, which is one of [our required paper elements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Can you please add this?

Also, our bot identified some potential missing DOIs; however, these may be for references in your `.bib` file but not actually included in the paper. Please confirm that all your references do have DOIs if available.

**Comment by kyleniemeyer** [comment]
Hi @dfm, could you edit this submission for us?

I want to point out (for potential reviewers) that this submission is connected to an article submitted to the AAS Astronomical Journal. As part of JOSS's collaboration with AAS, they make a small donation to the running costs of JOSS.

AAS publishing, and that as part of this collaboration, AAS publishing makes a small donation to the running costs of JOSS.

Some related links:
- Blog post describing the collaboration: https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing
- Summary of JOSS financial model: https://joss.theoj.org/about#costs

**Comment by kyleniemeyer** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
I'm happy to edit! I'll start recruiting reviewers shortly.

**Comment by dfm** [comment]
@whedon assign @dfm as editor

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by shihyuntang** [comment]
Dear @kyleniemeyer and @dfm,

Thank you both. 
For
> Hi @shihyuntang, we use this pre-review issue to identify an editor and reviewers, and also fix any obvious issues.
> 
> Your paper is currently missing a Statement of Need section that clearly illustrates the research purpose of the software, which is one of [our required paper elements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Can you please add this?
> 
> Also, our bot identified some potential missing DOIs; however, these may be for references in your `.bib` file but not actually included in the paper. Please confirm that all your references do have DOIs if available.

we had removed all the unused references in the `.bib` file, and also updated the paper with a new section, the Statement of Need.


Please check again.
@whedon generate pdf
Thank you.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03007/joss.03007/10.21105.joss.03007.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03007/joss.03007/10.21105.joss.03007.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637X/761/2/164 is OK
- 10.1088/0004-6256/148/3/53 is OK
- 10.5281/zenodo.845059 is OK
- 10.1117/12.2232780 is OK
- 10.1117/12.2312345 is OK
- 10.1117/12.2056431 is OK
- 10.1117/12.856864 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dfm** [comment]
@shihyuntang: I just wanted to let you know that I'm still working on recruiting reviewers and I'll add them here as soon as I have it sorted. Thanks for your patience!

**Comment by shihyuntang** [comment]
Dear @dfm Thank you for your notification. We understand that. We also used this time to import our wiki page. Now there is a dedicate "Demo with Example Data" to work user through the entire process with the example data.
However, we fix some small bugs as well during the process. 
Should I just make a new release like v0.9.6-beta.2 (submitted verse was v0.9.6-beta.1) or I need to make a new submission?
Thank you.

**Comment by dfm** [comment]
No need to make a new submission - we will expect the version number to be updated at least once throughout this process.

**Comment by shihyuntang** [comment]
@dfm Ok, Please let the reviewers know to review "v0.9.6-beta.3", instead of the submitted version "beta.1".
Thank you!

**Comment by dfm** [comment]
@whedon assign @jmbrewer as reviewer

@jmbrewer has agreed to review this submission - thanks John! Once I've lined up a second reviewer, I'll get the main review started. Please don't don't hesitate to ask questions if you have them as the review progresses. Thanks all!

**Comment by whedon** [comment]
OK, @jmbrewer is now a reviewer

**Comment by dfm** [comment]
@whedon add @gully as reviewer

Gully has agreed to be the second reviewer. Thank you! I'll get the review started in a separate issue thread and we'll get started over there. Please let me know if any of you have questions as we proceed.

**Comment by whedon** [comment]
OK, @gully is now a reviewer

**Comment by dfm** [comment]
@whedon start review
