### ISSUE TITLE
[PRE REVIEW]: libecpint: A C++ library for the eﬀicient evaluation of integrals over effective core potentials

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3008]
**Submitting author:** @robashaw (<a href="http://orcid.org/0000-0002-9977-0835">Robert A. Shaw</a>)
**Repository:** <a href="https://github.com/robashaw/libecpint" target ="_blank">https://github.com/robashaw/libecpint</a>
**Version:** v1.0.4
**Editor:** @poulson
**Reviewers:** @felipeZ, @lorenzo-rovigatti
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @robashaw. **Currently, there isn't an JOSS editor assigned** to your paper.

@robashaw if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3008 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.83 s (853.2 files/s, 86656.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                             72              0              0          31587
C++                             37           1106           1000           7140
reStructuredText               541           8438          13726           4342
XSD                              3            111             10           1175
C/C++ Header                    15            274           1091            934
Python                           4            111             98            410
CMake                           32             68             26            385
YAML                             3              8              8            102
Markdown                         1             21              0             38
Bourne Shell                     1              3              0             30
DOS Batch                        1              8              1             27
XSLT                             1              0              5             10
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                           712          10152          15971          46190
-------------------------------------------------------------------------------


Statistical information for the repository 'd169aa1d831559f0cd79f5dd' was
gathered on 2021/02/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jens                             1             8             19            0.04
Peter Bygrave                    1            23             10            0.05
Robert Shaw                     38         38052          25918           97.02
Thomas Dresselhaus               2           283            250            0.81
pk                               1             2              0            0.00
robashaw                         2            75              3            0.12
thomas-dresselhaus               2           720            572            1.96

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jens                          8          100.0          0.0                0.00
Peter Bygrave                 9           39.1          1.3                0.00
Robert Shaw               11620           30.5          1.5               19.06
Thomas Dresselhaus          212           74.9          1.5                5.66
thomas-dresselhaus          322           44.7          2.0                1.55
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03008/joss.03008/10.21105.joss.03008.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03008/joss.03008/10.21105.joss.03008.pdf) :page_facing_up: :point_left:

**Comment by robashaw** [comment]
> @robashaw if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

Possible reviewers taken from the list, based on being comfortable with C++ and having expertise in computational chemistry/electronic structure: 

lorenzo-rovigatti
felipeZ
nicorenaud
awgwvk
smutao
xwang862

**Comment by kyleniemeyer** [comment]
Thanks @robashaw. We will use this pre-review issue to assign the editor and reviewers.

@meg-simula, can you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by meg-simula** [comment]
@kyleniemeyer I'm essentially OOO until March 1 2021. If still relevant, I can handle this after that.

**Comment by kyleniemeyer** [comment]
@meg-simula ah, I didn't realize, that's alright.

**Comment by kyleniemeyer** [comment]
Hi @poulson, do you have bandwidth to edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @poulson as editor

**Comment by whedon** [comment]
@poulson has been invited to edit this submission.

**Comment by poulson** [comment]
@whedon assign poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
Hi Lorenzo (@lorenzo-rovigatti) :wave:.

In addition to you being recommended by Robert Shaw (@robashaw) as an expert reviewer for this submission, your C++/Python project BaggieAnalysis also seems to be quite relevant (https://github.com/lorenzo-rovigatti/baggianalysis).

Please let me know if you would be willing and able to review this submission on "libecpint: A C++ library for the eﬀicient evaluation of integrals over effective core potentials".

**Comment by poulson** [comment]
Hi Felipe (@felipeZ) :wave:.

In addition to your work on the C++ VOCTA-XTP library (https://github.com/votca/xtp/commits?author=felipeZ), you have been recommended as an expert by Robert Shaw (@robashaw).

Please let me know if you would be willing and able to review this submission on "libecpint: A C++ library for the eﬀicient evaluation of integrals over effective core potentials".

**Comment by poulson** [comment]
Hi Nicolas (@nicorenaud) :wave:,

While I don't see any C++ projects on your GitHub profile, you have been recommended as an expert reviewer by Robert Shaw (@robashaw) for this submission, entitled "libecpint: A C++ library for the eﬀicient evaluation of integrals over effective core potentials".

Please let me know if you would be willing to accept this invitation to review this C++ computational physics submission.

**Comment by felipeZ** [comment]
Hi Jack(@poulson) and Robert (@robashaw),
I am very happy to help with the review!

**Comment by lorenzo-rovigatti** [comment]
Hi Jack(@poulson) and Robert (@robashaw),

I'll be happy to help! It'll be my first review so bare with me though :-)

**Comment by poulson** [comment]
@whedon add @felipeZ as reviewer

**Comment by whedon** [comment]
OK, @felipeZ is now a reviewer

**Comment by poulson** [comment]
@whedon add @lorenzo-rovigatti as reviewer

**Comment by whedon** [comment]
OK, @lorenzo-rovigatti is now a reviewer

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3039.
