### ISSUE TITLE
[PRE REVIEW]: kallisto: A command-line interface to simplify 2 computational modelling and the generation of atomic features.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3011]
**Submitting author:** @f3rmion (<a href="http://orcid.org/0000-0002-3985-595X">Eike Caldeweyher</a>)
**Repository:** <a href="https://github.com/AstraZeneca/kallisto" target ="_blank">https://github.com/AstraZeneca/kallisto</a>
**Version:** v1.0.1
**Editor:** @richardjgowers
**Reviewers:** @rmeli, @Sulstice
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @f3rmion. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @richardjgowers.

@f3rmion if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.36 s (93.3 files/s, 38844.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          23            697            713          12058
Markdown                         3             79              0            202
SVG                              1              0              0            162
TeX                              1             12              0            105
YAML                             4              1              7             67
TOML                             1              7              0             42
INI                              1              1              0              4
-------------------------------------------------------------------------------
SUM:                            34            797            720          12640
-------------------------------------------------------------------------------


Statistical information for the repository '8cb25928bf0a918016770623' was
gathered on 2021/02/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Eike Caldeweyher                 9         13994            526          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Eike Caldeweyher          13468           96.2          0.0                4.75
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03011/joss.03011/10.21105.joss.03011.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03011/joss.03011/10.21105.joss.03011.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/c2014-0-00286-9 may be a valid DOI for title: Understanding the basics of QSAR for applications in pharmaceutical sciences and risk assessment
- 10.2174/156802610791111506 may be a valid DOI for title: QSAR in the pharmaceutical research setting: QSAR models for broad, large problems
- 10.2174/138620706776055539 may be a valid DOI for title: Computational methods in developing quantitative structure-activity relationships (QSAR): a review
- 10.1103/revmodphys.71.1253 may be a valid DOI for title: Nobel Lecture: Electronic structure of matter—wave functions and density functionals
- 10.1002/chin.200605293 may be a valid DOI for title: Single-reference ab initio methods for the calculation of excited states of large molecules
- 10.1063/1.478522 may be a valid DOI for title: Toward reliable density functional methods without adjustable parameters: The PBE0 model
- 10.1039/b508541a may be a valid DOI for title: Balanced basis sets of split valence, triple zeta valence and quadruple zeta valence quality for H to Rn: Design and assessment of accuracy
- 10.1007/bf00549096 may be a valid DOI for title: Bonded-atom fragments for describing molecular charge densities

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @f3rmion, we will use this pre-review issue to identify the editor and reviewers, and resolve any obvious issues.

It looks like the references in your paper did not compile properly; I think the issue is the tics surrounding the cite keys, which are not needed. Also, while you are fixing that, please pull the citations into the preceding sentence, rather than after the period.

**Comment by kyleniemeyer** [comment]
@richardjgowers can you edit this submission? This looks right up your alley.

**Comment by kyleniemeyer** [comment]
@whedon invite @richardjgowers as editor

**Comment by whedon** [comment]
@richardjgowers has been invited to edit this submission.

**Comment by f3rmion** [comment]
> preceding sentence

Hi @kyleniemeyer, I fixed the references. 
According to the Whedon preview, the references seems to be correct now.

**Comment by richardjgowers** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by f3rmion** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03011/joss.03011/10.21105.joss.03011.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03011/joss.03011/10.21105.joss.03011.pdf) :page_facing_up: :point_left:

**Comment by richardjgowers** [comment]
Hi @f3rmion I'm in the process of getting reviewers for this. One thing I noticed is you've missed that rdkit has had as extended Heuckel method available since 2019 (https://rdkit.blogspot.com/2019/06/doing-extended-hueckel-calculations.html)  Obviously not the best level of theory but worth a mention.

**Comment by f3rmion** [comment]
> Hi @f3rmion I'm in the process of getting reviewers for this. One thing I noticed is you've missed that rdkit has had as extended Heuckel method available since 2019 (https://rdkit.blogspot.com/2019/06/doing-extended-hueckel-calculations.html) Obviously not the best level of theory but worth a mention.

Thanks! I added a note and a reference, accordingly.

**Comment by f3rmion** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03011/joss.03011/10.21105.joss.03011.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03011/joss.03011/10.21105.joss.03011.pdf) :page_facing_up: :point_left:

**Comment by richardjgowers** [comment]
Hello @rmeli @thesketh @sulstice .  Would any/all of you be available to review this? Thanks

**Comment by RMeli** [comment]
@richardjgowers Yes, I'd be happy to review.

**Comment by Sulstice** [comment]
@richardjgowers Yep, I would be down to review!

**Comment by f3rmion** [comment]
@richardjgowers are two reviewers enough?

**Comment by richardjgowers** [comment]
@whedon add @rmeli as reviewer

**Comment by whedon** [comment]
OK, @rmeli is now a reviewer

**Comment by richardjgowers** [comment]
@whedon add @Sulstice as reviewer

**Comment by whedon** [comment]
OK, @Sulstice is now a reviewer

**Comment by richardjgowers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3050.

**Comment by richardjgowers** [comment]
@f3rmion yeah I was waiting on another person to get back to me, but we can proceed with 2
