### ISSUE TITLE
[PRE REVIEW]: ThermoPlotter: Streamlined Analysis of Thermoelectric Properties

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3012]
**Submitting author:** @kbspooner (<a href="http://orcid.org/0000-0002-4078-3148">Kieran B. Spooner</a>)
**Repository:** <a href="https://github.com/SMTG-UCL/ThermoPlotter/" target ="_blank">https://github.com/SMTG-UCL/ThermoPlotter/</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kbspooner. **Currently, there isn't an JOSS editor assigned** to your paper.

@kbspooner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3012 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.44 s (100.3 files/s, 134598.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                             8           2744             26          86041
JSON                             1              0              0          45781
JavaScript                      15           4277           4132          15247
HTML                            30           4979             87          12426
Python                          54           2408           3386           6235
SVG                              1              0              0           2671
CSS                              6            328             53           1256
reStructuredText                23            233            239            515
Markdown                         2             10              0             33
DOS Batch                        1              8              1             26
Bourne Shell                     2              4              0             16
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           144          14995           7931         170256
-------------------------------------------------------------------------------


Statistical information for the repository 'a48b84e6ca4070d417ec37e9' was
gathered on 2021/02/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel Davies                    1             1              1            0.00
Kieran B Spooner                64         29741           5453           74.92
Kieran B. Spooner                7            11             29            0.09
Kieran Spooner                   1            32             11            0.09
Maud Einhorn                    10         11204            427           24.76
Warda Rahim                      4            54             13            0.14

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dan Davies                    1          100.0          0.1                0.00
Kieran B Spooner          24124           81.1          2.0               12.09
Kieran Spooner               31           96.9          1.0                3.23
Maud Einhorn              10903           97.3          0.2               16.74
Warda Rahim                  31           57.4          0.0                0.00
```

**Comment by kyleniemeyer** [comment]
Hello @kbspooner, thanks for your interest in JOSS. Since your submission looks to be focused on visualization, I'm flagging it for a discussion among the editorial board for whether it fits in our scope as [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software). This isn't a comment on the effort or usefulness of your software, and it certainly satisfies our size/scholarly effort requirements.

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03012/joss.03012/10.21105.joss.03012.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03012/joss.03012/10.21105.joss.03012.pdf) :page_facing_up: :point_left:

**Comment by kbspooner** [comment]
Hi @kyleniemeyer, thanks for looking at our code.
I just want to point out that ThermoPlotter performs a fair amount of complex data post-processing and analysis (e.g. `tp.load`, `tp.calculate` and `tp.plot.phonons`) and can run external analysis tools on the fly (e.g. `tp.data.run`). For most users, the end goal of using this package will be effective visualisation of multidimensional data sets, so we have focussed more on that aspect. If you think we should re-focus the manuscript to highlight more clearly on the other capabilities of ThermoPlotter, then we would be happy to implement changes.

**Comment by kbspooner** [comment]
oh and our suggested reviewers are lucydot and mkhorton

**Comment by kthyng** [comment]
@kbspooner Thanks for your submission to JOSS. Unfortunately, the editorial board has found that it is not in scope for JOSS as mainly parsing and plotting files. While, as you pointed out, there is some analysis, it looks too light for our [guidelines](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software). This is not a commentary on how useful your software is, but how it falls in relation to JOSS scope guidelines. You may consider publishing your software another way; we have some suggestions [here](https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages).

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
