### ISSUE TITLE
[PRE REVIEW]: ARDL: An R package for the analysis of level relationships

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3013]
**Submitting author:** @Natsiopoulos (<a href="http://orcid.org/0000-0003-1180-2984">Kleanthis Natsiopoulos</a>)
**Repository:** <a href="https://github.com/Natsiopoulos/ARDL" target ="_blank">https://github.com/Natsiopoulos/ARDL</a>
**Version:** v0.1.1
**Editor:** @sbenthall
**Reviewers:** @ha0ye, @jacobsoj
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Natsiopoulos. **Currently, there isn't an JOSS editor assigned** to your paper.

@Natsiopoulos if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (413.8 files/s, 81191.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               14            177           1313           1561
Markdown                         4            144              0            503
Rmd                              1             53             83             48
TeX                              1              3              0             39
-------------------------------------------------------------------------------
SUM:                            20            377           1396           2151
-------------------------------------------------------------------------------


Statistical information for the repository '64831c22fa581fb86da03c82' was
gathered on 2021/02/05.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/jae.616 is OK

MISSING DOIs

- 10.1371/journal.pone.0228812 may be a valid DOI for title: dLagM: An R package for distributed lag models and ARDL bounds testing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03013/joss.03013/10.21105.joss.03013.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03013/joss.03013/10.21105.joss.03013.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hello @Natsiopoulos, thanks for your interest in JOSS. We use this pre-review issue to identify an editor and reviewers, and also resolve any obvious issues.

Your repository is currently missing an open-source license file; I see in the DESCRIPTION file that you use the GPL-3 license, so please add this to the repo at the top level.

Also, your paper needs a Statement of Need section, which is a [required element](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) of the paper.

**Comment by kyleniemeyer** [comment]
Hi @sbenthall, could you edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by Natsiopoulos** [comment]
Hello @kyleniemeyer, thank you for accepting our submission.

On behalf of my coauthor, I have made the following changes.
- Added the license file.
- Added the Statement of Need section. The relative information was already there but as part of the summary.
- Added a reference about a recent publication that uses the software.

Thank you

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03013/joss.03013/10.21105.joss.03013.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03013/joss.03013/10.21105.joss.03013.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (342.1 files/s, 67369.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               14            177           1313           1561
Markdown                         4            145              0            504
TeX                              1              4              0             50
Rmd                              1             53             83             48
-------------------------------------------------------------------------------
SUM:                            20            379           1396           2163
-------------------------------------------------------------------------------


Statistical information for the repository 'a4205f86284f5fe007d02bd5' was
gathered on 2021/02/08.
No commited files with the specified extensions were found.
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@sbenthall could you help with this submission?

**Comment by kthyng** [comment]
Hi @Natsiopoulos and thanks for your submission! We currently have low editor availability in this area, so I am going to add the "waitlist" label until we are able to assign this submission to an editor. Thanks for your patience.

**Comment by Natsiopoulos** [comment]
Hello @kyleniemeyer, @Kevin-Mattheus-Moerman, @kthyng,
Thank you for helping with our submission. 

Since this work is part of my PhD, and it's been over a month from the first submission, me and my coauthor and supervisor, we are wondering if you have an estimation about when the process is going to start?
Could another editor be invited since sbenthall has not responded yet? 

Thank you for your help

**Comment by kyleniemeyer** [comment]
Hello @Natsiopoulos, thanks for your patience. Unfortunately, many in our editorial board are still at reduced capacity right now, but submissions have not really slowed.

I will be looking for an alternative editor, but it may take a bit longer still as we work through the backlog.

**Comment by kyleniemeyer** [comment]
@whedon invite @kakiac as editor

Hi @kakiac, could you edit this?

**Comment by whedon** [comment]
@kakiac has been invited to edit this submission.

**Comment by kthyng** [comment]
Hi @Natsiopoulos! You are second on our waiting list for your submission's discipline. We have a handful of editors who could potentially handle it, but they are all occupied currently.

**Comment by danielskatz** [comment]
👋 @sbenthall - Are you able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by sbenthall** [comment]
Sure, I'll be the editor for this.

**Comment by sbenthall** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @sbenthall

**Comment by sbenthall** [comment]
@mcavs would you be able to review this submission?

**Comment by sbenthall** [comment]
@pedro-teles-fonseca would you be able to review this submission?

**Comment by mcavs** [comment]
I am sorry that I don't have enough time for this now @sbenthall

**Comment by Natsiopoulos** [comment]
Hello @sbenthall,
Thank you for being the editor of our submission.
Searching through the reviewers list, we found some potential reviewers with relevant domain areas. 
These are:
soodoku, tweed1e, ha0ye and taqtiqa-mark
Also, alexpghayes seems to have an interest in reviewing the interface and documentation which we consider a big advantage of our package.
Thank you

**Comment by sbenthall** [comment]
Thank you @Natsiopoulos that's very helpful!

@taqtiqa-mark would you be willing to review this package?

@ha0ye would you be willing to review this package?

**Comment by sbenthall** [comment]
@Natsiopoulos are you suggesting that @alexpghayes be asked to review the package for JOSS? In any case, of course you may take additional input from others and @alexpghayes is welcome to use the review issue to provide additional feedback. We will need to keep the official review process focused on the two formally chosen reviewers.

**Comment by alexpghayes** [comment]
I can't review at the moment, but the package looks interesting! Good luck!

**Comment by sbenthall** [comment]
That works great, @ha0ye Thank you!

@whedon assign @ha0ye as reviewer

**Comment by sbenthall** [comment]
@tweed1e would you be able to review this package?

**Comment by sbenthall** [comment]
@whedon assign @ha0ye as reviewer

**Comment by whedon** [comment]
OK, @ha0ye is now a reviewer

**Comment by sbenthall** [comment]
@soodoku would you be able to review this package?

**Comment by taqtiqa-mark** [comment]
@sbenthall unfortunately I can't take one another commitment right now. Apologies for the delay in responding to your request.

**Comment by ha0ye** [comment]
> @sbenthall - I can commit to a review by end of May, if that works for the general timeline of things.

Ok, lost track of time, but will start tomorrow, and target next week to submit my review.

**Comment by soodoku** [comment]
hi @sbenthall: too many other commitments for now so i must decline.

**Comment by sbenthall** [comment]
@ha0ye Thank you! We are a little backed up in the process because we need to find a second reviewer. But if you do your review soon, you can submit it once the second reviewer is found.

Do you have the review checklist available?

**Comment by sbenthall** [comment]
@Darthpathos would you be able to review this package?

**Comment by ha0ye** [comment]
> @ha0ye Thank you! We are a little backed up in the process because we need to find a second reviewer. But if you do your review soon, you can submit it once the second reviewer is found.
> 
> Do you have the review checklist available?

Yep, I've reviewed for JOSS before, as well as used the rOpenSci checklist in a separate setting.

**Comment by Darthpathos** [comment]
> @Darthpathos would you be able to review this package?

Hi @sbenthall - Unfortunately I don't anything about economics (I'm in healthcare).  Please let me know if you have any packages needing review for clinical trials, medical research, etc. :)

**Comment by sbenthall** [comment]
@feddelegrand7 Would you be able to review this package?

**Comment by feddelegrand7** [comment]
Hello @sbenthall. Thank you for asking, unfortunately I don't have the "time series" background and  necessary skills to review the package.

**Comment by sbenthall** [comment]
@daviddewhurst would you be able to review this package?

**Comment by sbenthall** [comment]
@jacobsoj would you be able to review this package?

**Comment by sbenthall** [comment]
@road2stat would you be able to review this package?

**Comment by sbenthall** [comment]
@trallard would you be able to review this package?

**Comment by jacobsoj** [comment]
Hi Sebastian,
Sorry for the delay. The email got filtered to a package that I don't often check. I can review this package if you still need me to.
Jill

Jill A. Jacobson, Ph.D. Office Phone  613-533-2847
Associate Professor, Social-Personality Program
Lab Phone 613-533-6000 x75417
Queen's University      FAX  613-533-2499
Department of Psychology        Email  ***@***.***
Kingston, ON  K7L 3N6
CANADA

http://www.queensu.ca/psychology/People/Faculty/Jill-Jacobson



________________________________

**Comment by sbenthall** [comment]
@jacobsoj  Thank you! I will assign you as a reviewer and start the review process.

**Comment by sbenthall** [comment]
@whedon add @jacobsoj as reviewer

**Comment by whedon** [comment]
OK, @jacobsoj is now a reviewer

**Comment by sbenthall** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3496.
