### ISSUE TITLE
[PRE REVIEW]: TAT.py: Tropospheric Analysis Tools in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3014]
**Submitting author:** @marcozennaro (<a href="http://orcid.org/0000-0002-0578-0830">Marco Zennaro</a>)
**Repository:** <a href="https://github.com/STI-ICTP/TropPOLoRaTools" target ="_blank">https://github.com/STI-ICTP/TropPOLoRaTools</a>
**Version:** 1.0
**Editor:** @gkthiruvathukal
**Reviewers:** @wtbarnes, @gorlapraveen
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @marcozennaro. **Currently, there isn't an JOSS editor assigned** to your paper.

@marcozennaro if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.43 s (35.3 files/s, 15518.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           8            525           1123           2180
Jupyter Notebook                 1              0            829           1321
Markdown                         2             53              0            240
HTML                             3             83              0            174
TeX                              1              8              0             67
-------------------------------------------------------------------------------
SUM:                            15            669           1952           3982
-------------------------------------------------------------------------------


Statistical information for the repository '0a265b210aceaea48f7a0a01' was
gathered on 2021/02/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
marcorainone                     1          3828              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
marcorainone               3828          100.0          0.0               28.94
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TAP.2015.2418788 is OK
- 10.1007/978-3-319-61949-1_31 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1145/3410670.3410856 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03014/joss.03014/10.21105.joss.03014.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03014/joss.03014/10.21105.joss.03014.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @marcozennaro, thanks for your interest in JOSS. We use this pre-review issue to assign the editor and reviewers, and also address any obvious issues.

First, your software repository is missing a valid open-source license. Please select a license, and add it.

Also, in your paper, I see some section/subsection references that do not appear to be compiling correctly—please take a look.

**Comment by kyleniemeyer** [comment]
Hi @gkthiruvathukal, I realize you already have a few submissions on your plate right now, but could you edit this for us?

**Comment by kyleniemeyer** [comment]
@whedon invite @gkthiruvathukal as editor

**Comment by whedon** [comment]
@gkthiruvathukal has been invited to edit this submission.

**Comment by gkthiruvathukal** [comment]
@kyleniemeyer I'll be happy to edit. Yes, I'm overwhelmed right now, but it has nothing to do with JOSS. I can handle it and will see it though the process.

**Comment by gkthiruvathukal** [comment]
@marcozennaro, once you have addressed @kyleniemeyer's points above, can you please suggest some reviewers from the list atop this issue thread? Thanks!

**Comment by kyleniemeyer** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by marcozennaro** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03014/joss.03014/10.21105.joss.03014.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03014/joss.03014/10.21105.joss.03014.pdf) :page_facing_up: :point_left:

**Comment by marcozennaro** [comment]
thanks @gkthiruvathukal ! I have addressed the issues. I think @wtbarnes would be a perfect reviewer for the paper

**Comment by marcozennaro** [comment]
Hi @wtbarnes, please let me know if the PDF is fine / if I need to address any issues. Thanks!

**Comment by gkthiruvathukal** [comment]
@marcozennaro Thanks. We need 2 reviewers to proceed with review. I will start by checking on wtbarnes' availability.

**Comment by gkthiruvathukal** [comment]
@wtbarnes Are you willing to contribute a review for this JOSS subimssion?

**Comment by wtbarnes** [comment]
@marcozennaro @gkthiruvathukal yes I can review this submission for JOSS!

**Comment by gkthiruvathukal** [comment]
Thanks so much @wtbarnes! Will assign you now and hope we can get one more reviewer shortly!

**Comment by gkthiruvathukal** [comment]
@whedon assign @wtbarnes as reviewer

**Comment by whedon** [comment]
OK, @wtbarnes is now a reviewer

**Comment by gkthiruvathukal** [comment]
@marcozennaro Can you please suggest a couple of additional reviewers? I need two to proceed with review.

**Comment by marcozennaro** [comment]
I would suggest http://people.sabanciuniv.edu/onat/ and http://www.grc.upv.es/calafate/

**Comment by gkthiruvathukal** [comment]
@marcozennaro  Can you suggest people who are in the list of JOSS reviewers (similar to wtbarnes)?

**Comment by marcozennaro** [comment]
@gkthiruvathukal: it would be great to ask @gorlapraveen and @garrettj403 Thanks!

**Comment by gkthiruvathukal** [comment]
@gorlapraveen, are you willing to contribute a review for this JOSS submission? I need a second reviewer in order to proceed.

**Comment by gorlapraveen** [comment]
@gkthiruvathukal , I would be happy to review!

**Comment by gkthiruvathukal** [comment]
So grateful, @gorlapraveen. I will add you and we can get the review started!

**Comment by gkthiruvathukal** [comment]
@whedon add @gorlapraveen as reviewer

**Comment by whedon** [comment]
OK, @gorlapraveen is now a reviewer

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3062.
