### ISSUE TITLE
[PRE REVIEW]: Groupyr: Sparse Group Lasso in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3016]
**Submitting author:** @richford (<a href="http://orcid.org/0000-0001-9276-9084">Adam Richie-Halford</a>)
**Repository:** <a href="https://github.com/richford/groupyr" target ="_blank">https://github.com/richford/groupyr</a>
**Version:** v0.2.0
**Editor:** @galessiorob
**Reviewers:** @janfreyberg, @JonathanReardon, @rougier
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @richford. **Currently, there isn't an JOSS editor assigned** to your paper.

@richford if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.46 s (115.7 files/s, 14504.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          18            842           1620           2230
Markdown                         7            129              0            523
reStructuredText                10            104             86            209
make                             2             38             12            175
YAML                             7             22             15            157
SVG                              2              0              0            132
TeX                              1              8              0             88
Bourne Shell                     2             16             19             62
JavaScript                       1              3             10             50
JSON                             1              0              0             46
TOML                             1              3              2             27
CSS                              1              3              0             13
-------------------------------------------------------------------------------
SUM:                            53           1168           1764           3712
-------------------------------------------------------------------------------


Statistical information for the repository 'c09b3f1657be4e558429b66b' was
gathered on 2021/02/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adam Richie-Halford             54          5860           1110           99.93
Ariel Rokem                      2             5              0            0.07

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adam Richie-Halford        4751           81.1          0.6                8.84
Ariel Rokem                   4           80.0          1.6               25.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.1283339 is OK
- 10.1101/2019.12.19.882928 is OK
- 10.5281/zenodo.4014775 is OK

MISSING DOIs

- 10.1007/978-3-642-15883-4_27 may be a valid DOI for title: Solving structured sparsity regularization with proximal methods

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03016/joss.03016/10.21105.joss.03016.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03016/joss.03016/10.21105.joss.03016.pdf) :page_facing_up: :point_left:

**Comment by richford** [comment]
At-mentioning co-authors here: @arokem, @mnarayan, @nrs02004, @jyeatman

Here is a non-exhaustive list of potential reviewers from the JOSS reviewers google sheet (coauthors, please feel free to add more in this thread):
- rougier
- sealhuang
- nirum
- effigies
- vsoch
- janfreyberg
- ionlights
- djsaunde
- JonathanReardon
- EtienneCmb
- ryEllison
- anibalsolon
- syoh
- clinssen
- emdupre
- saran-nns

**Comment by richford** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.1283339 is OK
- 10.1101/2019.12.19.882928 is OK
- 10.5281/zenodo.4014775 is OK

MISSING DOIs

- 10.1007/978-3-642-15883-4_27 may be a valid DOI for title: Solving structured sparsity regularization with proximal methods

INVALID DOIs

- https://doi.org/10.1007/978-3-642-15883-4_27 is INVALID because of 'https://doi.org/' prefix
```

**Comment by kyleniemeyer** [comment]
Thanks @richford. Looks like there may still be some DOI issues to work out.

We will use this pre-review issue to find an editor and reviewers.

**Comment by richford** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-642-15883-4_27 is OK
- 10.5281/zenodo.1283339 is OK
- 10.1101/2019.12.19.882928 is OK
- 10.5281/zenodo.4014775 is OK

MISSING DOIs

- 10.1007/978-3-642-15883-4_27 may be a valid DOI for title: Solving structured sparsity regularization with proximal methods

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @galessiorob, could you edit this submission? There are some reviewer suggestions above 👆

**Comment by kyleniemeyer** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by galessiorob** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by galessiorob** [comment]
Hi @richford 

Thanks for posting your suggested reviewers, I'll email them and add them as reviewers when they accept. In the meantime feel free to resolve the missing DOI.

**Comment by richford** [comment]
Hi @galessiorob, thanks! I'm a bit confused about the missing DOI. The single missing DOI is also listed in the "OK DOIs" list.

**Comment by richford** [comment]
@whedon check references

**Comment by galessiorob** [comment]
@richford you're right 🤔 

@danielskatz do you think [this](https://github.com/openjournals/joss-reviews/issues/3016#issuecomment-775539130) can be a whedon bug?

**Comment by danielskatz** [comment]
I wouldn't call this a bug.

In the .bib file, I see
> @inproceedings{mosci2010solving,
  title        = {Solving structured sparsity regularization with proximal methods},
  author       = {Mosci, Sofia and Rosasco, Lorenzo and Santoro, Matteo and Verri, Alessandro and Villa, Silvia},
  booktitle    = {Joint European conference on machine learning and knowledge discovery in databases},
  pages        = {418--433},
  year         = {2010},
  organization = {Springer}
}
> 
> @inproceedings{mosci2010solving,
  author    = {Mosci, Sofia and Rosasco, Lorenzo and Santoro, Matteo and Verri, Alessandro and Villa, Silvia},
  editor    = {Balc{\'a}zar, Jos{\'e} Luis and Bonchi, Francesco and Gionis, Aristides and Sebag, Mich{\`e}le},
  title     = {{Solving Structured Sparsity Regularization with Proximal Methods}},
  booktitle = {{Machine Learning and Knowledge Discovery in Databases}},
  year      = {2010},
  publisher = {Springer Berlin Heidelberg},
  address   = {Berlin, Heidelberg},
  pages     = {418--433},
  isbn      = {978-3-642-15883-4},
  doi       = {10.1007/978-3-642-15883-4_27}
}

Both of these entries have the same title.  whedon saw the title of the first one, which doesn't have a DOI listed, looked it up, and found the DOI for the second one, which has the same title and appears to be the same work, or perhaps a different version of the same work (same title, same authors, same year).  And they have the same bibtex key.  Which one is correct and is intended to be cited in the paper?  The other should probably be deleted from the .bib file.

**Comment by richford** [comment]
Thanks @danielskatz! 🤦🏻 @arokem fixed this in richford/groupyr#38

**Comment by galessiorob** [comment]
@whedon assign @rougier as reviewer

**Comment by whedon** [comment]
OK, @rougier is now a reviewer

**Comment by galessiorob** [comment]
@whedon assign @janfreyberg as reviewer

**Comment by whedon** [comment]
OK, @janfreyberg is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @JonathanReardon as reviewer

**Comment by whedon** [comment]
OK, @JonathanReardon is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @rougier as reviewer

**Comment by whedon** [comment]
OK, @rougier is now a reviewer

**Comment by galessiorob** [comment]
🎉 Thanks for volunteering to be reviewers @rougier @JonathanReardon and @janfreyberg!

I'll generate a "review issue" that will contain individual checklists to go through, feel free to get started at your earliest convenience, don't hesitate to ask if you need clarification or help - you can @mention me directly on the issue.

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3024.
