### ISSUE TITLE
[PRE REVIEW]: Logodetect: One-shot detection of logos in image and video data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3017]
**Submitting author:** @maxpumperla (<a href="http://orcid.org/0000-0002-7801-4184">Max Pumperla</a>)
**Repository:** <a href="https://github.com/Heldenkombinat/Logodetect" target ="_blank">https://github.com/Heldenkombinat/Logodetect</a>
**Version:** v0.1
**Editor:** @arokem
**Reviewers:** nsaunier, abhishekbajpayee
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @maxpumperla. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kakiac.

@maxpumperla if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (400.2 files/s, 56359.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          34            652            551           2558
Jupyter Notebook                 8              0           3278            652
JSON                             6              0              0            414
Markdown                         4            100              0            326
TeX                              1              7              0             67
YAML                             4              5              0             34
Bourne Shell                     3             14              7             32
Dockerfile                       1              8              0             13
INI                              1              3              0             11
-------------------------------------------------------------------------------
SUM:                            62            789           3836           4107
-------------------------------------------------------------------------------


Statistical information for the repository 'a5c44b549154345fd72197ad' was
gathered on 2021/02/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jorge                           37          1181            823           23.60
Jorge Davila-Chacon              2           459              5            5.46
Max Pumperla                    52          4481           1542           70.93

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jorge Davila-Chacon          24            5.2          6.4                4.17
Max Pumperla               3727           83.2          3.4                9.82
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/CVPR.2016.90 is OK

MISSING DOIs

- 10.1109/tpami.2016.2577031 may be a valid DOI for title: Faster R-CNN: Towards Real-Time Object Detection with Region Proposal Networks

INVALID DOIs

- https://doi.org/10.1016/j.patcog.2019.106965 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03017/joss.03017/10.21105.joss.03017.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03017/joss.03017/10.21105.joss.03017.pdf) :page_facing_up: :point_left:

**Comment by maxpumperla** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03017/joss.03017/10.21105.joss.03017.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03017/joss.03017/10.21105.joss.03017.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @arokem as editor

:wave: @arokem - I realize you're looking to keep your editorial load light right now but given that your other paper is close to wrapping up, would you be willing to take this one on as your next?

**Comment by whedon** [comment]
@arokem has been invited to edit this submission.

**Comment by arokem** [comment]
Yeah. I can take this on.

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
Hello @maxpumperla. Thank you for this submission. Could you please say a little bit about the anticipated research uses of this software? I am not sure that this falls within our [definition of research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software)

**Comment by arokem** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by maxpumperla** [comment]
Hi @arokem, thanks for taking a first look. We read through your documentation, of course, and were fairly sure that making object detection and recognition more accessible is `solve[ing] complex modeling problems in a scientific context (engineering, ML)`, especially when comparing to other submissions (e.g. LOC and scope).
 
Specifically, it not easy to get your hands on one-shot detectors and even researchers will have to design them mostly from scratch. @jorgedch and I are currently looking into

- adding more architectures to logodetect for comparison
- extending the problem from logos to other objects, within the same framework
- apply the techniques to concrete problems to see how they fare against established methods (e.g. in banner ads on TV, which doesn't have such sophisticated methods).

The first adds more convenience, the second is "proper" ML research, and the last point is applied science. Now, I can't speak for the community as a whole and what can be anticipated, but the point of OSS for me is that you share first and see if it gets adopted later. Right now I don't see any frameworks allowing you to run and build on top of one-shot detection, and logodetect fills that gap.

**Comment by arokem** [comment]
OK. Based on your response and the scope check, we have determined that this is within scope for the journal. I will proceed to find reviewers for this. @maxpumperla : if you have suggestions for reviewers (look [here](https://bit.ly/joss-reviewers)), please send their GitHub user names here (but please do not include the @ sign before their name, so that they are not unnecessarily alerted).

**Comment by jorgedch** [comment]
Great, thank you for the update. We found the following reviewers to have a
relevant background:
lee-seon-woo, nsaunier, jizecn, abuccts, alexssandrofc
All the best, Jorge

**Comment by arokem** [comment]
👋  @lee-seon-woo : would you be willing to review this paper for JOSS?

**Comment by arokem** [comment]
👋 @jizecn: would you be willing to review this paper for JOSS? Thanks!

**Comment by arokem** [comment]
👋 @abuccts would you be willing to review this paper for JOSS? Thanks!

**Comment by arokem** [comment]
👋 @nsaunier : would you be willing to review this paper for JOSS? Thanks!

**Comment by arokem** [comment]
:wave: @abhishekbajpayee: would you be willing to review this paper for JOSS? Thanks!

**Comment by arokem** [comment]
👋 @neuroimaginador : would you be willing to review this paper for JOSS? Thanks!

**Comment by nsaunier** [comment]
> wave @nsaunier : would you be willing to review this paper for JOSS? Thanks!

Yes. Is that the correct way to accept and how should I submit the review? Sorry, I am a beginner here.

**Comment by arokem** [comment]
@nsaunier: yes - thank you for accepting! As soon as I find one more reviewer, I will start the review issue, where you will find your reviewer check list to work from. In the meanwhile, please stand by.

**Comment by arokem** [comment]
👋 @jmadera : would you be willing to review this article for JOSS? Thanks!

**Comment by arokem** [comment]
👋 @rewbenio : would you be willing to review this article for JOSS? Thanks!

**Comment by abhishekbajpayee** [comment]
@arokem I don't have time until early April. If this can wait until April 10th or so, I can review.

**Comment by arokem** [comment]
@abhishekbajpayee : That's fine. I'll assign you to this and start the review process.

**Comment by arokem** [comment]
@whedon assign nsaunier as reviewer

**Comment by whedon** [comment]
OK, nsaunier is now a reviewer

**Comment by arokem** [comment]
@whedon add abhishekbajpayee as reviewer

**Comment by whedon** [comment]
OK, abhishekbajpayee is now a reviewer

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3124.

**Comment by arokem** [comment]
Alright - @nsaunier and @abhishekbajpayee : thank you both for taking this on. Please head over to #3124 for your reviewer checklists.
