### ISSUE TITLE
[PRE REVIEW]: PXO (Poly-XTAL Operations): Free MATLAB codebase to generate and analyse complex 2D grain structures

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3018]
**Submitting author:** @SunilAnandatheertha (<a href="http://orcid.org/0000-0001-6535-8191">sunil anandatheertha</a>)
**Repository:** <a href="https://github.com/SunilAnandatheertha/PXO" target ="_blank">https://github.com/SunilAnandatheertha/PXO</a>
**Version:** V10.0.3
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @yangbai90, @ksyang2013, @littlelazy6
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @SunilAnandatheertha. **Currently, there isn't an JOSS editor assigned** to your paper.

@SunilAnandatheertha if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.41 s (524.4 files/s, 47162.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                         205           1247           3459          14127
Markdown                         7             65              0            184
XML                              1              1              0            146
TeX                              1              7              0             89
YAML                             1              1              1             10
-------------------------------------------------------------------------------
SUM:                           215           1321           3460          14556
-------------------------------------------------------------------------------


Statistical information for the repository 'ed90a5f57c18b2664e8bb2d0' was
gathered on 2021/02/08.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/S0081-1947(08)60603-7 is OK
- 10.1016/0001-6160(84)90151-2 is OK
- 10.1016/0036-9748(89)90525-5 is OK
- 10.1016/0001-6160(84)90089-0 is OK
- 10.2355/isijinternational.38.913 is OK
- 10.1016/0956-7151(90)90177-I is OK
- 10.1016/j.actamat.2009.10.058 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03018/joss.03018/10.21105.joss.03018.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03018/joss.03018/10.21105.joss.03018.pdf) :page_facing_up: :point_left:

**Comment by SunilAnandatheertha** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by SunilAnandatheertha** [comment]
@Kevin-Mattheus-Moerman Could I please request you to please use the latest version from https://github.com/SunilAnandatheertha/PXO/releases/tag/V10.0.3. Thank you.

**Comment by Kevin-Mattheus-Moerman** [comment]
We usually do not review a particular tagged version since the review often triggers (e.g. minor) changes in the software. Once the review is complete we do create a tagged release which is then associated with the paper. I'll update the version tag here (which may be upgraded again time) but perhaps we can keep the repository the same, since I take it your main branch is still the one reviewers should focus on.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set V10.0.3 as version

**Comment by whedon** [comment]
OK. V10.0.3 is the version.

**Comment by Kevin-Mattheus-Moerman** [comment]
I will start looking for reviewers in the coming week. We are operating at a slower pace then usual. In the mean time it would be helpful if you could recommend reviewers at this time (see also our current list of reviewers mentioned above). You can mention their github user names without the `@` so you do not tag them yet. Thanks.

**Comment by SunilAnandatheertha** [comment]
Hi. Thank you for the message. Please find the below list of reviwer's usernames:
(1) ketch
(2) abigailsnyder
(3) mturiansky
(4) yangbai90
(5) na

Thanks

**Comment by SunilAnandatheertha** [comment]
Hi. I hope the reviewer list was ok. Could i please request an update. Thanks.

**Comment by SunilAnandatheertha** [comment]
Hello. Could I please request for an update.

**Comment by Kevin-Mattheus-Moerman** [comment]
@SunilAnandatheertha apologies for the delay in processing your submission. JOSS is experiencing delays since both editors and reviewers are experiencing additional time constraints and difficulties due to the COVID19 pandemic. 
I am picking this up now and will hopefully have found and assigned reviewers this. Thanks for your patience.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ralfHielscher, @frankNiessen, @millerta, @ketch, @mturiansky, @yangbai90, would you be interested in reviewing this submission  for [JOSS](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) focuses on [the software](https://github.com/SunilAnandatheertha/PXO) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.03018/joss.03018/10.21105.joss.03018.pdf). If you are interested you can comment here. Thanks! 

Note, given the global COVID19 pandemic we can be very flexible in terms of review times.

Note, this is a so-called "Pre-review issue" where reviewers/editors are assigned. Once I've attracted sufficient reviewers I'll trigger a "Review issue" where the review will take place.

**Comment by SunilAnandatheertha** [comment]
Hi Kevin, thank you for the update.

**Comment by mturiansky** [comment]
I am already reviewing another paper for JOSS at the moment, so I must decline for that reason.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ksyang2013, @jan-janssen, @jic198, @hitliaomq, @DavidMercier, @czambaldi , @ralfHielscher, @frankNiessen, @millerta, @ketch, @yangbai90, would you be interested in reviewing this submission  for [JOSS](https://joss.theoj.org/)? The [review process](https://joss.readthedocs.io/en/latest/submitting.html#the-review-process) focuses on [the software](https://github.com/SunilAnandatheertha/PXO) and this [short paper](https://github.com/openjournals/joss-papers/blob/joss.03018/joss.03018/10.21105.joss.03018.pdf). If you are interested you can comment here. Thanks! 

Note, given the global COVID19 pandemic we can be very flexible in terms of review times. 

Note, this is a so-called "Pre-review issue" where reviewers/editors are assigned. Once I've attracted sufficient reviewers I'll trigger a "Review issue" where the review will take place.

**Comment by jan-janssen** [comment]
@Kevin-Mattheus-Moerman Thank you for the invitation - I would prefer to focus on reviewing python packages as I only have very limited experience with MATLAB.

**Comment by hitliaomq** [comment]
Dear Kevin,


Thank you for your invitation.


But I have no time recently, I must focus on my Ph.D thesis. In the future (after september), I'm glad to review papers or codes.


Thank you again.


Best,
Mingqing


On 4/16/2021 16:11，Kevin Mattheus ***@***.***> wrote：

@ksyang2013, @jan-janssen, @jic198, @hitliaomq, @DavidMercier, @czambaldi , @ralfHielscher, @frankNiessen, @millerta, @ketch, @yangbai90, would you be interested in reviewing this submission for JOSS? The review process focuses on the software and this short paper. If you are interested you can comment here. Thanks!

Note, given the global COVID19 pandemic we can be very flexible in terms of review times.

Note, this is a so-called "Pre-review issue" where reviewers/editors are assigned. Once I've attracted sufficient reviewers I'll trigger a "Review issue" where the review will take place.

**Comment by ksyang2013** [comment]
Dear Kevin,

I am willing to review this codebase. Thanks!

Best,
Kesong  


--------------------------------------
Kesong YANG, Ph.D.

Associate Professor,
Department of NanoEngineering, 
Program of Materials Science and Engineering,
Center for Memory and Recording Research (CMRR),
University of California San Diego
9500 Gilman Drive, Mail Code 0448
La Jolla, CA 92093-0448, USA
 
Office: SME 244H
Tel: (858) 534-2514
E-mail: ***@***.***    
http://materials.ucsd.edu <http://materials.ucsd.edu/>

**Comment by yangbai90** [comment]
@Kevin-Mattheus-Moerman 
Dear Kevin, I'm willing to review this package. Thanks!

BR
Yang

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @yangbai90 as reviewer

**Comment by whedon** [comment]
OK, @yangbai90 is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @ksyang2013 as reviewer

**Comment by whedon** [comment]
OK, @ksyang2013 is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @littlelazy6 as reviewer

**Comment by whedon** [comment]
OK, @littlelazy6 is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@littlelazy6 (a PhD student at NUIG working on grain structures with Dr Noel Harrison) who expressed an interest to review this has also been added as a reviewer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3190.
