### ISSUE TITLE
[PRE REVIEW]: Precise calculations on hypercomplex numbers in C++

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3019]
**Submitting author:** @AngryMaciek (<a href="http://orcid.org/0000-0003-1361-7301">Maciej Bak</a>)
**Repository:** <a href="https://github.com/AngryMaciek/hypercomplex" target ="_blank">https://github.com/AngryMaciek/hypercomplex</a>
**Version:** v1.0.0
**Editor:** @melissawm
**Reviewers:** @dvberkel, @bonh
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @AngryMaciek. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @melissawm.

@AngryMaciek if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (226.9 files/s, 200596.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     2           3233           1408          14285
C++                              4             89             66           1249
YAML                             6             66              0            243
Markdown                         8             71              0            233
XML                              1              2              4             98
TeX                              1              7              0             72
make                             1             17             31             35
HTML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            24           3485           1509          16221
-------------------------------------------------------------------------------


Statistical information for the repository '678546932cdbf418842f3943' was
gathered on 2021/02/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Maciej Bak                     205         40007          21364           94.88
Maciek Bąk                       6          2501            814            5.12

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Maciej Bak                20330           50.8          3.2                7.27
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03019/joss.03019/10.21105.joss.03019.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03019/joss.03019/10.21105.joss.03019.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1007/978-3-7643-7791-5_2 may be a valid DOI for title: Quaternions
- 10.1007/978-1-4419-7719-9_6 may be a valid DOI for title: Boost C++ libraries

INVALID DOIs

- None
```

**Comment by melissawm** [comment]
@whedon assign @melissawm as editor

**Comment by whedon** [comment]
OK, the editor is @melissawm

**Comment by AngryMaciek** [comment]
Dear @melissawm,

Thank you for accepting the editor's position here.

I do not have anyone specific for the reviewers in my mind but I would suggest one mathematician to double-check the algebra and one C++ expert to double-check the template programming and code structure.

Kind Regards,
Maciek

**Comment by melissawm** [comment]
Hello, @AngryMaciek! Before we start, I'd like to suggest some minor changes to the paper:

- It would be nice to add the name of your software package in the title of your paper, and remove "The following repository.." As much as this is about a software repository, people reading your software paper may need a bit more context :)
- For the references [Hořeňovský,  M. (2018)], [The Boost Organization (1999)] and [van Heesch (2013)], it might be interesting to cite a specific version number.
- For other github repositories, I'm not sure how the "publishing date" was chosen. Can you clarify that? For example, for the [fed36 (2015)] reference, there appear to be changes in 2016. In cases where there's no release or version tag in the repository, it might be useful to either cite a specific commit or add to the citation the date where the last access was made. See, for example, [this document on citation principles for software](https://www.force11.org/software-citation-principles ).

Meanwhile I'll get started on finding reviewers. Thanks!

**Comment by AngryMaciek** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03019/joss.03019/10.21105.joss.03019.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03019/joss.03019/10.21105.joss.03019.pdf) :page_facing_up: :point_left:

**Comment by AngryMaciek** [comment]
Dear @melissawm,

* OK, changes included.
* OK, I have specified the most recent stable versions and adjuted the 'year' field respectively.
* I am generally following the example: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography These other three github repositories do not tag versions and the parsing engine for the paper does not support pointing to specific commits therefore I have modified the 'year' field for them to be 'last accessed' field. I believe that previously I have chosen the initial year of the project start, which does not make much sense as for a reference... It looks much better now, thanks!

**Comment by melissawm** [comment]
Thanks, @AngryMaciek ! I'll start looking for reviewers from our spreadsheet, and once we've found at least two, we can start the review.

**Comment by melissawm** [comment]
Hi @jordigh @kpeeters, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by AngryMaciek** [comment]
@melissawm 
Maybe we should ask around more people?

From the list I selected: StewMH, diehlpk, iljah, katyhuff, nnadeau, rrrlw, ctdegroot, dvberkel, vissarion, danehkar, inakleinbottle, Nheyer, bonh, cpgr, mstimberg

**Comment by kpeeters** [comment]
Sorry all, I can't do it this time unfortunately, too many other commitments.

**Comment by melissawm** [comment]
Hi @StewMH @diehlpk , would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by StewMH** [comment]
Hi,

Unfortunately I don't have much time at the moment.

Thanks,
Stewart

**Comment by melissawm** [comment]
Hello, @dvberkel! Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by diehlpk** [comment]
@melissawm I am the editor for too many papers and have no time to review any paper at this stage.

**Comment by melissawm** [comment]
Hello, @danehkar! Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by dvberkel** [comment]
@melissawm I am willing to review this submission for JOSS

**Comment by melissawm** [comment]
Thank you, @dvberkel ! I'll add you as a reviewer and we'll try and get at least another reviewer before we start the Review issue.

**Comment by melissawm** [comment]
@whedon assign @dvberkel as reviewer

**Comment by whedon** [comment]
OK, @dvberkel is now a reviewer

**Comment by dvberkel** [comment]
Hi @melissawm,

Just for the record. I am still waiting for the official review-process to start. Or did I miss a notification?

**Comment by melissawm** [comment]
@dvberkel yes, we are still looking for a second reviewer. I'll try contacting a few other people.

**Comment by melissawm** [comment]
Hello, @bonh! Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by bonh** [comment]
@melissawm will do, thanks!

**Comment by melissawm** [comment]
Thank you, @bonh ! 

Looks like we have two reviewers, so I will proceed - this issue will be closed and you will all be tagged in the REVIEW issue. I'll give you further instructions in a bit.

**Comment by melissawm** [comment]
@whedon add @bonh as reviewer

**Comment by whedon** [comment]
OK, @bonh is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3096.
