### ISSUE TITLE
[PRE REVIEW]: origami - Cross-validation Framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#302]
**Submitting author:** @jeremyrcoyle (<a href="http://orcid.org/0000-0002-9874-6649">Jeremy Coyle</a>)
**Repository:** <a href="https://github.com/jeremyrcoyle/origami" target ="_blank">https://github.com/jeremyrcoyle/origami</a>
**Version:** v0.8
**Editor:** @karthik
**Reviewer:** @wrathematics

**Author instructions**

Thanks for submitting your paper to JOSS @jeremyrcoyle. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jeremyrcoyle if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by karthik** [comment]
@jeremyrcoyle Thanks for the submission. Please hang on while I do some preliminary checks and find reviewers.

**Comment by karthik** [comment]
Apologies for the delay @jeremyrcoyle. Still waiting on reviewers (two that I've asked have declined). I was also on my summer vacation for the past 10 days. Checking with a couple of people now. Will update when I know more.

**Comment by karthik** [comment]
@wrathematics Would you be able to review this submission?

**Comment by nhejazi** [comment]
Just wanted to bump this since it's now been ~1 month since @wrathematics was prompted

**Comment by karthik** [comment]
Thanks @nhejazi 
Seeking other reviewers now.

**Comment by karthik** [comment]
While I look for reviewers for this paper (which has been challenging) @nhejazi do you or @jeremyrcoyle have any suggestions for people we should approach?

**Comment by nhejazi** [comment]
Thanks very much for your efforts @karthik! No one in particular comes to mind - is there a list of JOSS reviewers we might be able to consult?

_Perhaps worth mentioning_ - this particular package provides a very general framework for easily implementing a variety of cross-validation schemes, making no domain expertise necessary to evaluate it. Really, its purpose is to make implementing cross-validation in a computationally efficient manner less of a headache. For now, we support some common CV schemes, and have the goal of adding more over time. Because of its generality, the important thing (in our eyes) in terms of reviewing the package is expertise in R and a working knowledge of cross-validation. I only mention the above in case it makes finding reviewers easier - hope this helps.

**Comment by karthik** [comment]
@arfon I am unable to find a reviewer for this. Would another editor be willing to take this over?

cc @leeper

**Comment by nhejazi** [comment]
@karthik Thanks for your efforts in searching for a reviewer for this package. Please let us know if there's anything we can do to help with the process once @leeper or another editor takes over.

**Comment by wrathematics** [comment]
Hey, I'm really sorry I never responded. I never got an email for the mention for some reason. I can review this next week if you're still looking for reviewers.

**Comment by arfon** [comment]
> Hey, I'm really sorry I never responded. I never got an email for the mention for some reason. I can review this next week if you're still looking for reviewers.

No problem at all. If you're available that would be great! @karthik - are you OK to handle this if @wrathematics takes on the review?

**Comment by arfon** [comment]
@whedon assign @wrathematics as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @wrathematics

**Comment by nhejazi** [comment]
@wrathematics - thanks in advance for the review!

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/512. Feel free to close this issue now!

**Comment by arfon** [comment]
@wrathematics - when you're ready, please head over to #512 for the actual review.
