### ISSUE TITLE
[PRE REVIEW]: cgmquantify: Python and R packages for comprehensive analysis of interstitial glucose and glycemic variability from continuous glucose monitor data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3023]
**Submitting author:** @brinnaebent (<a href="http://orcid.org/0000-0002-7039-0177">Brinnae Bent</a>)
**Repository:** <a href="https://github.com/DigitalBiomarkerDiscoveryPipeline/cgmquantify" target ="_blank">https://github.com/DigitalBiomarkerDiscoveryPipeline/cgmquantify</a>
**Version:** v0.0.5
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @brinnaebent. **Currently, there isn't an JOSS editor assigned** to your paper.

@brinnaebent if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (336.1 files/s, 20272.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           3            104            263            288
Markdown                         8             82              0            260
R                               16             57            193            234
TeX                              1             25              0            136
Jupyter Notebook                 1              0            149             24
reStructuredText                 1              0              0              3
Rmd                              1             10             41              1
-------------------------------------------------------------------------------
SUM:                            31            278            646            946
-------------------------------------------------------------------------------


Statistical information for the repository '8c47aceb337b3c399801c942' was
gathered on 2021/02/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
brinnaebent                      9           680             24          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
brinnaebent                 655           96.3          0.8               10.23
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3023 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (f03e5abcc9a5d0b487ca9edc/Paper/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
:wave: @brinnaebent - thanks for your submission, also thank you for drawing our attention to the fact that this is a [resubmission](https://github.com/openjournals/joss-reviews/issues/2112).

To directly address [your comment]( https://github.com/openjournals/joss-reviews/issues/2112#issuecomment-593607497) in the earlier submission:

> Good afternoon `@labarba`. Thank you for your comments. Can you elaborate on this being in the 'minor utility' category? Diabetes and prediabetes affect 1/3 of the US population, there are over 700k diabetes publications indexed in PubMed, and yet there is not a standard package with metrics summarizing glucose and glucose variability in the most utilized programming language, Python. The metrics provided in this package include clinically validated metrics across multiple studies in addition to novel metrics that give a more complete picture of glucose health. Could you provide more information into why this is considered 'minor utility'? Thank you very much.

Unfortunately at ~500 lines of code this submission still falls foul of our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion. While this software may be a useful contribution to an important area of research, the _software contribution effort_ here is considered too low to be published in JOSS.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
