### ISSUE TITLE
[REVIEW]: Groupyr: Sparse Group Lasso in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3024]
**Submitting author:** @richford (<a href="http://orcid.org/0000-0001-9276-9084">Adam Richie-Halford</a>)
**Repository:** <a href="https://github.com/richford/groupyr" target ="_blank">https://github.com/richford/groupyr</a>
**Version:** v0.2.2
**Editor:** @galessiorob
**Reviewer:** @janfreyberg, @JonathanReardon, @rougier
**Archive:** <a href="https://doi.org/10.5281/zenodo.4559599" target="_blank">10.5281/zenodo.4559599</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1235928957b5dfe59f159a568bd64950/status.svg)](https://joss.theoj.org/papers/1235928957b5dfe59f159a568bd64950)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1235928957b5dfe59f159a568bd64950"><img src="https://joss.theoj.org/papers/1235928957b5dfe59f159a568bd64950/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1235928957b5dfe59f159a568bd64950/status.svg)](https://joss.theoj.org/papers/1235928957b5dfe59f159a568bd64950)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/richford/groupyr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@janfreyberg & @JonathanReardon & @rougier, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @galessiorob know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/richford/groupyr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@richford) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/richford/groupyr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@richford) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/richford/groupyr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@richford) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @janfreyberg, @JonathanReardon, @rougier it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.26 s (200.7 files/s, 25174.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          18            842           1620           2230
Markdown                         7            129              0            523
reStructuredText                10            104             86            209
make                             2             38             12            175
YAML                             7             22             15            157
SVG                              2              0              0            132
TeX                              1              8              0             92
Bourne Shell                     2             16             19             62
JavaScript                       1              3             10             50
JSON                             1              0              0             46
TOML                             1              3              2             27
CSS                              1              3              0             13
-------------------------------------------------------------------------------
SUM:                            53           1168           1764           3716
-------------------------------------------------------------------------------


Statistical information for the repository 'a698189cf93dc39741d3213a' was
gathered on 2021/02/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adam Richie-Halford             54          5860           1110           99.93
Ariel Rokem                      2             5              0            0.07

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adam Richie-Halford        4751           81.1          0.6                8.84
Ariel Rokem                   4           80.0          1.6               25.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-642-15883-4_27 is OK
- 10.5281/zenodo.1283339 is OK
- 10.1101/2019.12.19.882928 is OK
- 10.5281/zenodo.4014775 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03024/joss.03024/10.21105.joss.03024.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03024/joss.03024/10.21105.joss.03024.pdf) :page_facing_up: :point_left:

**Comment by janfreyberg** [comment]
@richford can you please add citations & references for the group_lasso and Lightning packages in the paper? Thanks!

**Comment by richford** [comment]
@janfreyberg, sure thing. I added that in the above referenced PR. Thanks!

**Comment by janfreyberg** [comment]
Great, thanks :)

@whedon generate pdf

**Comment by janfreyberg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03024/joss.03024/10.21105.joss.03024.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03024/joss.03024/10.21105.joss.03024.pdf) :page_facing_up: :point_left:

**Comment by janfreyberg** [comment]
@galessiorob review completed, paper looks good to publish!

**Comment by JonathanReardon** [comment]
Just finished my review, all looks great to me. No issues my end - good to publish!

**Comment by rougier** [comment]
I've just read the paper and installed the software. I've a few questions concerning the submission:

- There are five authors in the paper, could you tell us their respective role in the software?
- I did not  find the way to run the unittests. Would it be possible to have a simple `groupyrr.test()` that run tests?
- When you write "we found that our implementation .... was faster", maybe you can give some precision (2x 10x 100x ?) and possibly how to test it.
- For the references, I think some DOI are missing.
- For the reference on group-lasso, maybe you can retrieve the swid from software heritage such as to have a long term id on the resource.

**Comment by richford** [comment]
Hi @rougier, thanks for your review. I'll address all but one of you points now and come back for the remaining one (about the performance comparison with group-lasso) in a few days:

> - There are five authors in the paper, could you tell us their respective role in the software?

Sure thing, in [this PR](https://github.com/richford/groupyr/pull/42), I added an author contribution statement to the paper, which categorizes author contribution according to the [CRediT taxonomy](http://dx.doi.org/10.1087/20150211).

> - I did not find the way to run the unittests. Would it be possible to have a simple groupyrr.test() that run tests?

Good question! Provided you have installed a development version of `groupyr` using
```
python -m pip install -e .[dev]
```
you can run unit tests and check for code style using
```
make lint
make test
```
We mention this in [this section of the contributing guidelines](https://github.com/richford/groupyr/blob/main/.github/CONTRIBUTING.md#making-a-change) (specifically , but your comment was very helpful because it made me realize that the provided `Makefile` is not well documented. To resolve this, I added a `help` target to the `Makefile` in [this recent PR](https://github.com/richford/groupyr/pull/43). Now, a user can simple type `make` or `make help` to see the available options and discover the `make test` command.

> - For the references, I think some DOI are missing.

You are correct. Thanks! I have added missing DOIs in [the same PR that added the author contribution statement](https://github.com/richford/groupyr/pull/42).

> - For the reference on group-lasso, maybe you can retrieve the swid from software heritage such as to have a long term id on the resource.

Thanks for the tip. I updated the `group-lasso` citation to use the biblatex `softwareversion` entry and then put the swhid in the version number. That change is also in [PR 42](https://github.com/richford/groupyr/pull/42)

**Comment by rougier** [comment]
Thanks for your answers. For the speed comparison, I'm not asking to a full-proof comparison but just some number to give the reader an idea of the speedup (x1.1 is technically faster but 5x might be worth to explore further your software). If you have a script, it's all the better bit not mandatory at all.

By the way, I forgot to ask to list dependencies in the documenation. Not mandatory but it might help user.

Apart from that, I'm satisfied with the submission.

**Comment by richford** [comment]
Hi @rougier, I addressed the speed comparison in [PR 44](https://github.com/richford/groupyr/pull/44), where I changed the comparison sentence to
> However, we found that our implementation in *groupyr*, which relies on the
*copt* optimization library, was between two and ten times faster
for the problem sizes that we encounter in our research (see the
repository's examples directory for a performance comparison).

And added an example script to the examples directory that generates a chart showing the speedup for various problem sizes.

**Comment by richford** [comment]
@rougier, I also added a list of dependencies to the installation documentation in [PR 45](https://github.com/richford/groupyr/pull/45). Hope that resolves all of your concerns. Thanks!

**Comment by rougier** [comment]
@richford Thanks.
@galessiorob I'm happy with the modifications.

**Comment by richford** [comment]
Thanks to all of the reviewers: @rougier, @JonathanReardon, and @janfreyberg.

@galessiorob, it looks like all of the reviewers have completed their reviews. Anticipating the next steps, I have cut a new version of *groupyr* and created a new archive DOI. Here's the new information:

new version: 0.2.1
new DOI: [10.5281/zenodo.4554452](https://zenodo.org/record/4554452)

If you need any other information, please don't hesitate to reach out.

**Comment by galessiorob** [comment]
Thank you @rougier @JonathanReardon and @janfreyberg for the quick turnaround. 

@richford thank you for being so efficient and proactive! I'll take a final pass at it and ping the editor to get this published ASAP.

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03024/joss.03024/10.21105.joss.03024.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03024/joss.03024/10.21105.joss.03024.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment]
@whedon set v0.2.1 as version

**Comment by whedon** [comment]
OK. v0.2.1 is the version.

**Comment by galessiorob** [comment]
@whedon set 10.5281/zenodo.4554452 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4554452" target="_blank">10.5281/zenodo.4554452</a> is the archive.

**Comment by galessiorob** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03024/joss.03024/10.21105.joss.03024.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03024/joss.03024/10.21105.joss.03024.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment]
@richford could you proofread this final version, please? 🙏

Once you greenlight it we can accept it and publish it 🎉

**Comment by richford** [comment]
Hi @galessiorob, I just read through the final version and it looks good to me :rocket:

Thanks for everyone's hard work on this!

**Comment by galessiorob** [comment]
@richford great, thanks so much, and congrats!

 @rougier @JonathanReardon and @janfreyberg this has been the fastest review I have ever had! Thank you all so very much ⚡

**Comment by galessiorob** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2107

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2107, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.2517-6161.1996.tb02080.x is OK
- 10.1080/10618600.2012.681250 is OK
- 10.1111/j.1467-9868.2005.00532.x is OK
- 10.1007/978-3-642-15883-4_27 is OK
- 10.5281/zenodo.1283339 is OK
- 10.1101/2019.12.19.882928 is OK
- 10.5281/zenodo.4014775 is OK
- 10.5281/zenodo.200504 is OK
- 10.1087/20150211 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.5555/1953048.2078195 is INVALID
```

**Comment by galessiorob** [comment]
@richford mind solving that last DOI, please?

**Comment by richford** [comment]
Sure thing. Sorry about that. I scraped the DOI [from the url](https://dl.acm.org/doi/10.5555/1953048.2078195) for the JMLR paper, but I guess that doesn't work. I see that later papers from the same sklearn authors reference their earlier paper and do not include a DOI at all. So I elected to simply remove the DOI for the sklearn reference. I just pushed that change to the `main` branch.

@galessiorob, do you want me to cut a new version because of this change? The underlying software did not change, only the `paper.bib` file that is in the repo.

**Comment by galessiorob** [comment]
>@galessiorob, do you want me to cut a new version because of this change? The underlying software did not change, only the paper.bib file that is in the repo.

@richford thanks for the explanation, makes sense. Yes, let's get a new version 👍

**Comment by richford** [comment]
@galessiorob, Thanks! The new version is `v0.2.2` and the new DOI is [10.5281/zenodo.4559599](https://zenodo.org/record/4559599)

**Comment by kthyng** [comment]
@whedon set v0.2.2 as version

**Comment by whedon** [comment]
OK. v0.2.2 is the version.

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.4559599 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4559599" target="_blank">10.5281/zenodo.4559599</a> is the archive.

**Comment by kthyng** [comment]
@richford I just found one typo, you can find it in this [PR](https://github.com/richford/groupyr/pull/52).

**Comment by kthyng** [comment]
After that we are ready to finalize this publication!

**Comment by richford** [comment]
@kthyng, thanks for catching that! I just merged your PR.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1364626592530628609) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2111
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.03024](https://doi.org/10.21105/joss.03024)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @richford!! Many thanks to editor @galessiorob and to reviewers @janfreyberg, @JonathanReardon, and @rougier — we couldn't do this without your hard work, time, and expertise!

(I'll close this issue once the doi resolves)

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03024/status.svg)](https://doi.org/10.21105/joss.03024)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03024">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03024/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03024/status.svg
   :target: https://doi.org/10.21105/joss.03024
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03024/status.svg)](https://doi.org/10.21105/joss.03024)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
