### ISSUE TITLE
[PRE REVIEW]: fishgrowbot: Fish growth curves through back-calculation of otoliths rings in a Bayesian framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3025]
**Submitting author:** @nschiett (<a href="http://orcid.org/0000-0002-1925-3484">Nina Schiettekatte</a>)
**Repository:** <a href="https://github.com/nschiett/fishgrowbot" target ="_blank">https://github.com/nschiett/fishgrowbot</a>
**Version:** v0.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @nschiett. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@nschiett if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41597-020-00711-y is OK
- 10.1111/1365-2435.13618 is OK
- 10.1139/cjfas-57-6-1291 is OK
- 10.1007/978-1-4020-5775-5_6 is OK
- 10.1002/fee.2088 is OK
- 10.1126/science.1059199 is OK
- 10.1111/j.1095-8649.2001.tb00127.x is OK
- 10.1016/j.fishres.2006.07.002 is OK
- 10.3168/jds.S0022-0302(63)89186-9 is OK
- 10.18637/jss.v076.i01 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (164.4 files/s, 23678.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     3              6             69           1795
XML                              1              0              2            441
Markdown                         3             57              0            204
R                                7              6            184            199
YAML                             5             34              5            156
TeX                              1              0              0            139
Rmd                              3             75            220             67
C++                              3             20              4             62
-------------------------------------------------------------------------------
SUM:                            26            198            484           3063
-------------------------------------------------------------------------------


Statistical information for the repository '78fbb1bf92958481e38208a5' was
gathered on 2021/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Diego Barneche                   2            30            395            6.12
nschiett                         8          4420           2099           93.88

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
nschiett                   1956           44.3          0.0                3.94
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3025 with the following error: 

 pandoc: /media/nschiettekatte/DATA/phd/fishgrowbot/paper/output/paper_files/figure-latex/plot1a-1.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon query scope

Thanks for your submission to JOSS @nschiett – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@nschiett - Thanks for your submission to JOSS. After a review, the editors have determined that this submission does not meet our criterion for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) and so is out of scope for JOSS.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by nschiett** [comment]
@arfon thanks for the review. Would it be possible to specify which aspect of the package doesn't meet the criterion? Is it something we could work on for a revision? 
I would really appreciate your feedback.

**Comment by arfon** [comment]
@nschiett - mostly this was due to the software contribution being considered too small here. Our interpretation of this package is that there is some R [here](https://github.com/nschiett/fishgrowbot/tree/master/R) and some Stan-generated source code in C/C++. 

As we outline in our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort), small submissions like these may be considered out of scope for JOSS.
