### ISSUE TITLE
[PRE REVIEW]: starry_process: Interpretable Gaussian processes for stellar light curves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3026]
**Submitting author:** @rodluger (<a href="http://orcid.org/0000-0002-0296-3826">Rodrigo Luger</a>)
**Repository:** <a href="https://github.com/rodluger/starry_process" target ="_blank">https://github.com/rodluger/starry_process</a>
**Version:** v0.9.6
**Editor:** @arfon
**Reviewers:** @nespinoza, @j-faria
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @rodluger. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@rodluger if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3847/1538-3881/ab4fee is OK
- 10.1109/TPAMI.2015.2448083 is OK
- 10.1093/mnras/stx2109 is OK
- 10.3847/1538-4357/aade45 is OK
- 10.3847/1538-4357/abae5d is OK
- 10.1146/annurev-statistics-030718-105212 is OK
- 10.12942/lrsp-2005-8 is OK
- 10.1126/science.1185402 is OK
- 10.1111/j.1365-2966.2009.14679.x is OK
- 10.3847/1538-4357/ab3924 is OK
- 10.1093/mnras/stt1191 is OK
- 10.1088/0004-637X/806/2/212 is OK
- 10.1016/0370-2693(87)91197-X is OK
- 10.1111/j.1365-2966.2009.14548.x is OK
- 10.3847/1538-3881/aa9332 is OK
- 10.3847/1538-4357/836/2/200 is OK
- 10.3847/1538-4357/aaeb9b is OK
- 10.1086/316882 is OK
- 10.1093/mnras/stu1320 is OK
- 10.1093/mnras/stt304 is OK
- 10.1051/0004-6361/201629505 is OK
- 10.1093/mnras/stt1435 is OK
- 10.1051/0004-6361/201117270 is OK
- 10.3847/0004-6256/152/4/100 is OK
- 10.3847/1538-4357/aa9c43 is OK
- 10.1038/s41550-017-0129 is OK
- 10.3847/1538-3881/aae8e5 is OK
- 10.1088/0004-637X/801/1/3 is OK
- 10.3847/1538-4357/aa8555 is OK
- 10.3847/1538-4357/aab6a5 is OK
- 10.3847/1538-4357/ab79a0 is OK
- 10.21105/joss.02103 is OK
- 10.1080/10618600.2017.1302882 is OK
- 10.3847/1538-4357/aaa08c is OK
- 10.1093/mnras/stv1428 is OK
- 10.1117/1.JATIS.1.1.014003 is OK
- 10.3847/1538-4357/aa8ef7 is OK
- 10.1086/141361 is OK
- 10.1088/0034-4885/69/3/R02 is OK
- 10.1093/mnras/staa278 is OK
- 10.1063/1.1835238 is OK
- 10.1214/06-BA127 is OK
- 10.1086/165647 is OK
- 10.1007/978-1-4614-3508-2_5 is OK
- 10.1038/nature09319 is OK

MISSING DOIs

- 10.1080/01621459.2017.1285773 may be a valid DOI for title: Variational Inference: A Review for Statisticians
- 10.1162/neco_a_01127 may be a valid DOI for title: Adaptive Gaussian process approximation for Bayesian inference with expensive likelihood functions

INVALID DOIs

- https://doi.org/10.1016/0010-4655(89)90107-0 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03026/joss.03026/10.21105.joss.03026.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03026/joss.03026/10.21105.joss.03026.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=7.81 s (202.8 files/s, 41055.0 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
C/C++ Header                    532          23772          32795         127515
C++                             733           8403           5536          43116
Fortran 77                       51             17          13727          24137
CMake                            85           1470           1480           6782
Python                           85           1337           1849           6479
C                                21            796           2076           3792
CUDA                             14            681            173           2732
SVG                               1              0              0           2671
Markdown                          4            500              0           1642
TeX                               1             86              0            898
Jupyter Notebook                  5              0           2353            587
HTML                              6             45              6            426
Bourne Shell                      9            113             40            380
YAML                              8             46              1            326
PO File                           4            120            154            322
CSS                               5             60             21            217
JavaScript                        3             27             54            210
XML                               1             15             10            210
JSON                              1              0              0             81
Bourne Again Shell                4             18             21             77
reStructuredText                  4             31             42             44
DTD                               1              1              0             30
make                              3             12             11             23
TOML                              1              1              0             19
Dockerfile                        1              6              0             13
INI                               1              0              0              8
--------------------------------------------------------------------------------
SUM:                           1584          37557          60349         222737
--------------------------------------------------------------------------------


Statistical information for the repository '5aa39b17ea6fc0e9c978a870' was
gathered on 2021/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dan F-M                         10           312            198            0.16
Rodrigo Luger                  319        285787          28225           99.84

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dan F-M                     294           94.2          0.4                1.70
Rodrigo Luger            257382           90.1          5.4               16.39
```

**Comment by arfon** [comment]
@whedon assign me as editor

:wave: @rodluger, thanks for your submission to JOSS. Could you suggest a few names for people who might be able to give this software a good review? Either real names or GitHub handles is fine.

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by rodluger** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03026/joss.03026/10.21105.joss.03026.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03026/joss.03026/10.21105.joss.03026.pdf) :page_facing_up: :point_left:

**Comment by rodluger** [comment]
@arfon As reviewers I'd suggest Néstor Espinoza (nespinoza), Brett Morris (bmorris3), or James Davenport (jradavenport).

**Comment by arfon** [comment]
:+1: thanks @rodluger. I suspect these folks might be pretty busy but let's try 🤞 

:wave: @nespinoza @bmorris3 @jradavenport - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by nespinoza** [comment]
Hi @arfon, @rodluger --- would love to review this submission, but I can't promise a speedy review. If a review by March 12 works, would be happy to take this.

**Comment by rodluger** [comment]
@nespinoza @arfon No worries.  March 12 works for me. Thanks!

**Comment by arfon** [comment]
@whedon add @nespinoza as reviewer

**Comment by whedon** [comment]
OK, @nespinoza is now a reviewer

**Comment by arfon** [comment]
Thanks @nespinoza! @rodluger - I'll leave this in the pre-review state for a little longer while we try and find a second reviewer.

**Comment by arfon** [comment]
@gully @j-faria - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The software under review is [_starry_process: Interpretable Gaussian processes for stellar light curves_](https://github.com/rodluger/starry_process).

**Comment by bmorris3** [comment]
Hi all, I'm oversubscribed for the next month or two – if you have any trouble finding a second reviewer let me know but it might take me a bit to get around to it.

**Comment by gully** [comment]
I could probably do this review if no one else agrees to.  Given that Néstor can do it by March 12, I could match that date.  However, regarding conflict-of-interest, co-author Christina Hedges and I were co-workers from 2017-2020 and are co-authors on at least one research note and one or more large-author-list publications.

**Comment by j-faria** [comment]
Hi @arfon, @rodluger 
I'd be happy to do the review but can't make it before March 10. 
Can try to match Néstor's date or have it ready for the following week for sure.

**Comment by arfon** [comment]
:zap: thanks @j-faria! I'd love to have you as a reviewer here and the timeframe you suggest sounds great! As we now have two reviewers, I'll go ahead and set up the main review issue.

**Comment by arfon** [comment]
@whedon add @j-faria as reviewer

**Comment by whedon** [comment]
OK, @j-faria is now a reviewer

**Comment by arfon** [comment]
@nespinoza, @j-faria. One thing I forgot to mention when inviting you both to review is that this JOSS submission/paper is a joint publication with AAS Journals, i.e. this JOSS paper will be published together with another paper in one of the AAS journals. As part of this collaboration, AAS publishing makes a small donation to the running costs of JOSS. 

If this is unacceptable to you, please let me know and I can look for alternative reviewers.

Some related links:

- Blog post describing the collaboration: https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing
- Summary of JOSS financial model: https://joss.theoj.org/about#costs

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3071.

**Comment by arfon** [comment]
@nespinoza, @j-faria - see you over in #3071 where the actual review will take place.
