### ISSUE TITLE
[PRE REVIEW]: PyArmadillo: an alternative approach to linear algebra in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3028]
**Submitting author:** @jason-rumengan (<a href="http://orcid.org/0000-0003-1839-5138">Jason Rumengan</a>)
**Repository:** <a href="https://gitlab.com/jason-rumengan/pyarma" target ="_blank">https://gitlab.com/jason-rumengan/pyarma</a>
**Version:** v0.500.0
**Editor:** @mjsottile
**Reviewers:** @JaroslavHron, @uellue
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jason-rumengan. **Currently, there isn't an JOSS editor assigned** to your paper.

@jason-rumengan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/1.9780898719604 is OK
- 10.1016/j.csda.2013.02.005 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1007/978-3-319-32452-4 is OK
- 10.21105/joss.00026 is OK
- 10.1007/978-3-319-96418-8_50 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03028/joss.03028/10.21105.joss.03028.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03028/joss.03028/10.21105.joss.03028.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=20.97 s (62.6 files/s, 16744.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   783          56263          20980         147037
HTML                             4           1466           1065          31626
C++                            287           7995           6951          29992
Python                         133           7204           5234          17253
reStructuredText                32           2578           2846           4413
CMake                           32            738            764           2812
YAML                            16            245            172           1034
Markdown                         9            334              0            926
SVG                              2              0              0            854
TeX                              1             19              0            120
XML                              1              0              0             69
Bourne Shell                     4             21             20             64
INI                              1              0              0             19
CSS                              1              0              0             11
make                             1             10              6             11
TOML                             3              1              0              9
MATLAB                           1              4              3              4
PowerShell                       1              3              5              4
-------------------------------------------------------------------------------
SUM:                          1312          76881          38046         236258
-------------------------------------------------------------------------------


Statistical information for the repository 'f9987d8da1fbab58540bb6cf' was
gathered on 2021/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jason Rumengan                   3            91             54            0.01
Terry Zhuo                      74        221763          11413            8.58
conrad                           2            46             53            0.00
jason-rumengan                 447       1384413        1096872           91.30
terryyz                          2          1097             73            0.04
terryzhuo110                     1           191           1556            0.06

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Terry Zhuo                  196            0.1          1.0               43.37
conrad                        1            2.2          0.3                0.00
jason-rumengan           298735           21.6          1.0               11.04
```

**Comment by arfon** [comment]
@whedon invite @mjsottile as editor

:wave: @mjsottile - would you be able to edit this submission for us?

**Comment by whedon** [comment]
@mjsottile has been invited to edit this submission.

**Comment by mjsottile** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mjsottile** [comment]
:wave: @jason-rumengan If you have any suggestions for people to review your submission, please let me know.  I will be searching for potential reviewers over the next few days.

**Comment by jason-rumengan** [comment]
Thank you, @mjsottile. I suggest Sébastien Marcel (https://www.idiap.ch/~marcel/professional/Welcome.html) as a reviewer.

**Comment by conradsnicta** [comment]
@mjsottile Thank you for volunteering to be an editor on this submission.  If there is anything that we can do to clarify or provide further information, please let us know.  (I'm one of the co-authors).

**Comment by mjsottile** [comment]
Sorry - I'm running a bit behind due to power + internet outages from weather in the Pacific Northwest in the last week.  I'll be soliciting reviewers shortly.

**Comment by mjsottile** [comment]
:wave: @JaroslavHron, @vyasr, @sivaramambikasaran Would you be interested in reviewing this submission for JOSS?  I believe you would be a fit for this work based on your areas of interest listed in our list of potential reviewers.

**Comment by JaroslavHron** [comment]
Hi, yes I can review this submission.

**Comment by sivaramambikasaran** [comment]
> 👋 @JaroslavHron, @vyasr, @sivaramambikasaran Would you be interested in reviewing this submission for JOSS? I believe you would be a fit for this work based on your areas of interest listed in our list of potential reviewers.

Nope. Tied with other work.

**Comment by mjsottile** [comment]
@whedon assign @JaroslavHron as reviewer

**Comment by whedon** [comment]
OK, @JaroslavHron is now a reviewer

**Comment by mjsottile** [comment]
:wave: @uellue, @ulvgard Would you be interested in reviewing this submission for JOSS?  I am looking for one additional reviewer.  I believe you would be a fit for this work based on your areas of interest listed in our list of potential reviewers.

**Comment by uellue** [comment]
@mjsottile it would be my pleasure!

**Comment by ulvgard** [comment]
Nice to see you filled the spot. Thanks for the consideration!

**Comment by vyasr** [comment]
> 👋 @JaroslavHron, @vyasr, @sivaramambikasaran Would you be interested in reviewing this submission for JOSS? I believe you would be a fit for this work based on your areas of interest listed in our list of potential reviewers.

Hi sorry for the slow response. I can't right now, I'm starting a new job next week.

**Comment by mjsottile** [comment]
@whedon add @uellue as reviewer

**Comment by whedon** [comment]
OK, @uellue is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3051.
