### ISSUE TITLE
[PRE REVIEW]: PyOncoPrint: A python package to plot OncoPrints

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3029]
**Submitting author:** @pjb7687 (<a href="http://orcid.org/0000-0002-9064-4912">Jeongbin Park</a>)
**Repository:** <a href="https://github.com/pjb7687/pyoncoprint" target ="_blank">https://github.com/pjb7687/pyoncoprint</a>
**Version:** v0.2.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pjb7687. **Currently, there isn't an JOSS editor assigned** to your paper.

@pjb7687 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (114.2 files/s, 16544.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             36             10            367
Jupyter Notebook                 1              0            188             96
Markdown                         1              8              0             51
TeX                              1              0              1             46
reStructuredText                 1             16             16             34
-------------------------------------------------------------------------------
SUM:                             6             60            215            594
-------------------------------------------------------------------------------


Statistical information for the repository 'bdfb4a080ebf9abf8c4e9598' was
gathered on 2021/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jeongbin Park                   11           789            376          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jeongbin Park               413           52.3          0.0                2.42
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03029/joss.03029/10.21105.joss.03029.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03029/joss.03029/10.21105.joss.03029.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1126/scisignal.2004088 may be a valid DOI for title: Integrative analysis of complex cancer genomics and clinical profiles using the cBioPortal
- 10.1093/bioinformatics/btw313 may be a valid DOI for title: Complex heatmaps reveal patterns and correlations in multidimensional genomic data
- 10.1109/mcse.2007.55 may be a valid DOI for title: Matplotlib: A 2D graphics environment

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon query scope 

@pjb7687 – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by pjb7687** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03029/joss.03029/10.21105.joss.03029.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03029/joss.03029/10.21105.joss.03029.pdf) :page_facing_up: :point_left:

**Comment by pjb7687** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1158/2159-8290.cd-12-0095 is OK
- 10.1126/scisignal.2004088 is OK
- 10.1093/bioinformatics/btw313 is OK
- 10.1109/mcse.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by pjb7687** [comment]
I have updated the DOIs. Thank you so much!

**Comment by pjb7687** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03029/joss.03029/10.21105.joss.03029.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03029/joss.03029/10.21105.joss.03029.pdf) :page_facing_up: :point_left:

**Comment by pjb7687** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03029/joss.03029/10.21105.joss.03029.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03029/joss.03029/10.21105.joss.03029.pdf) :page_facing_up: :point_left:

**Comment by pjb7687** [comment]
I also did some minor corrections regarding BibTeX citations too. Thanks for reviewing the paper.

**Comment by arfon** [comment]
@pjb7687 - Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
