### ISSUE TITLE
[PRE REVIEW]: PyGBe-LSPR: Python and GPU Boundary-integral solver for electrostatics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#303]
**Submitting author:** @ncclementi (<a href="http://orcid.org/0000-0002-0575-5520">Natalia C. Clementi</a>)
**Repository:** <a href="https://github.com/barbagroup/pygbe" target ="_blank">https://github.com/barbagroup/pygbe</a>
**Version:** 0.3
**Editor:** @katyhuff
**Reviewer:** @nicoguaro

**Author instructions**

Thanks for submitting your paper to JOSS @ncclementi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ncclementi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @katyhuff it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by katyhuff** [comment]
Thanks for submitting, @ncclementi !
 @jordigh or @nicoguaro , would either of you be interested in reviewing this paper?

**Comment by nicoguaro** [comment]
@katyhuff, I think I can do it.

**Comment by katyhuff** [comment]
Excellent. Thanks @nicoguaro .

**Comment by katyhuff** [comment]
@whedon assign @nicoguaro as reviewer.

**Comment by whedon** [comment]
OK, the reviewer is @nicoguaro

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/306. Feel free to close this issue now!

**Comment by katyhuff** [comment]
@nicoguaro and @ncclementi , please head over to #306 for the actual review.

**Comment by katyhuff** [comment]
@whedon assign @kyleniemeyer as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kyleniemeyer
