### ISSUE TITLE
[PRE REVIEW]: `presize`: An R-package for precision-based sample size calculation in clinical research

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3030]
**Submitting author:** @aghaynes (<a href="http://orcid.org/0000-0003-1374-081X">Alan G Haynes</a>)
**Repository:** <a href="https://github.com/CTU-Bern/presize" target ="_blank">https://github.com/CTU-Bern/presize</a>
**Version:** 0.1.3
**Editor:** @majensen
**Reviewers:** @amoeba, @TomKellyGenetics
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @aghaynes. **Currently, there isn't an JOSS editor assigned** to your paper.

@aghaynes if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (667.0 files/s, 102628.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            22           1109            281           3442
R                               34            604           1028           3149
CSS                              3             99             48            428
Markdown                         4            107              0            309
JavaScript                       3             64             32            256
YAML                             6             56             11            208
TeX                              1             17              0            165
Rmd                              1             34             70             11
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            75           2090           1471           7979
-------------------------------------------------------------------------------


Statistical information for the repository '39bbc3d0451dc65e46bf0a81' was
gathered on 2021/02/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
aghaynes                         2           357              5          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
aghaynes                    352           98.6          0.0                9.09
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2307/2685779 is OK
- 10.1198/000313002317572736 is OK
- 10.1016/S0140-6736(86)90837-8 is OK
- 10.1136/bmj.b3985 is OK
- 10.1002/sim.1108 is OK
- 10.1214/ss/1009213286 is OK
- 10.1007/BF02294183 is OK
- 10.1177/0962280211415469 is OK
- 10.1148/radiology.143.1.7063747 is OK
- 10.2307/2530610 is OK
- 10.2307/2531551 is OK
- 10.1002/sim.4780040211 is OK
- 10.1002/(sici)1097-0258(19980430)17:8<873::aid-sim779>3.0.co;2-i is OK
- 10.1016/j.jclinepi.2011.10.019  is OK
- 10.1097/EDE.0000000000000876 is OK
- 10.1016/S0140-6736(10)60484-9 is OK
- 10.1016/0895-4356(91)90128-v is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3030 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@aghaynes - our document production pipeline expects a `date` field in the YAML header, could you please add one?

Also, it looks like we couldn't find a license for this repository. Please make sure there is one present.

**Comment by aghaynes** [comment]
Thanks for the feedback @arfon. I've added those things. I also noticed that the version on github is actually 0.2.0 rather than 0.1.3 which is on CRAN. 

On a different point, Whedon seems to think that I've only made 2 commits... that is not even remotely correct... I've committed many more times...

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3030 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you help trouble shoot this error?

**Comment by xuanxu** [comment]
In the paper metadata the `orcid` field for Odile Stalder is empty. There are two options to fix the error, adding a value or removing the orcid field for that author.

**Comment by aghaynes** [comment]
thanks both

**Comment by aghaynes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03030/joss.03030/10.21105.joss.03030.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03030/joss.03030/10.21105.joss.03030.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @majensen would you be able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @majensen as editor

**Comment by whedon** [comment]
@majensen has been invited to edit this submission.

**Comment by majensen** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by kthyng** [comment]
thank you @majensen!!!

**Comment by majensen** [comment]
@seandavi - would you be willing to review [this work](#3030) for [JOSS](https://joss.theoj.org)? If not, would you be able to recommend an expert from your group or elsewhere? I really appreciate  your consideration - @majensen

**Comment by majensen** [comment]
@aghaynes if you have suggestions for reviewers, please let me know. Much appreciated-

**Comment by majensen** [comment]
Hey @amoeba, do you have time and inclination to review [this work](#3030) for [JOSS](https://joss.theoj.org)? Would be awesome.

**Comment by aghaynes** [comment]
@majensen sorry for the delay... The only people that come to my mind might be biased (people I know or have collaborated with). If you're fine with that then I could nominate certainly one person...

**Comment by majensen** [comment]
@aghaynes sure

**Comment by aghaynes** [comment]
@majensen then perhaps @PatrickRWright would be able and willing?

**Comment by cimentadaj** [comment]
@majensen I can't at the moment. Thanks!

**Comment by majensen** [comment]
Thanks @cimentadaj - appreciate your consideration!

**Comment by majensen** [comment]
@PatrickRWright - any chance you would be willing to review [this work](#3030) for [JOSS](https://joss.theoj.org)? Please have a look at [these reviewing guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) for some additional info. Thanks for considering-

**Comment by amoeba** [comment]
Hi @majensen, I do have time and could have a review in on or before March 21 if that works.

**Comment by majensen** [comment]
Thanks @amoeba that would be perfect

**Comment by majensen** [comment]
@whedon assign @amoeba as reviewer

**Comment by whedon** [comment]
OK, @amoeba is now a reviewer

**Comment by PatrickRWright** [comment]
Hi @majensen thanks for considering me but I'm swamped right now.

**Comment by majensen** [comment]
@TomKellyGenetics - would you have time to review [this work](#3030) for [JOSS](https:://joss.theoj.org)? Much appreciated! --@majensen

**Comment by TomKellyGenetics** [comment]
Hi @majensen, I can do it but I'm attending an online conference next week so it'll need to be the following week. I hope that's okay.  🙇‍♂️

**Comment by majensen** [comment]
@TomKellyGenetics that would be great-- very much appreciated!

**Comment by majensen** [comment]
@whedon add @TomKellyGenetics as reviewer

**Comment by whedon** [comment]
OK, @TomKellyGenetics is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3118.
