### ISSUE TITLE
[PRE REVIEW]:  toqito -- Theory of quantum information toolkit: A Python package for studying quantum information

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3033]
**Submitting author:** @vprusso (<a href="http://orcid.org/0000-0002-8952-8981">Vincent Russo</a>)
**Repository:** <a href="https://github.com/vprusso/toqito" target ="_blank">https://github.com/vprusso/toqito</a>
**Version:** 0.0.7
**Editor:** @poulson
**Reviewers:** @rurz, @jameshclrk, @marwahaha
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vprusso. **Currently, there isn't an JOSS editor assigned** to your paper.

@vprusso if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.48 s (882.9 files/s, 53405.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         269           4067           7141           7042
TeX                              8            481            125           1710
reStructuredText               124            865           1365           1108
SVG                              8              1              1            949
Markdown                         6            139              0            374
TOML                             1              6              0             57
YAML                             4              3              1             37
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           422           5574           8641          11312
-------------------------------------------------------------------------------


Statistical information for the repository 'e28ad1d9e28350899ae0caed' was
gathered on 2021/02/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Sanketh Menda                    1             1              1            0.00
Vincent Russo                  330         52598          34796           97.93
georgios-ts                      5           254             10            0.30
sebgrijalva                      3           143              9            0.17
vprusso                         11           784            644            1.60

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vincent Russo               446            0.8          6.2                6.95
georgios-ts                 237           93.3          0.5                7.59
sebgrijalva                 128           89.5          0.5                6.25
vprusso                   17439         2224.4          7.8                7.82
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03033/joss.03033/10.21105.joss.03033.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03033/joss.03033/10.21105.joss.03033.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.22331/q-2019-03-11-129 may be a valid DOI for title: Strawberry fields: A software platform for photonic quantum computing
- 10.22331/q-2018-01-31-49 may be a valid DOI for title: ProjectQ: an open source software framework for quantum computing

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@vprusso - please update your paper to include a section named `Statement of need` with a description that illustrates the research purpose of the software. Also, I'm not sure if those DOI recommendations from Whedon are correct but if they are, please add them `doi` fields to your BibTeX.

**Comment by vprusso** [comment]
Hi Afron,

Thanks again for your quick response.

I've gone ahead and added in a "Statement of Need" section along with the
"doi" information in the BibTeX file for the entries that do possess a
valid doi.

If there is anything else I need to add, please let me know, and thanks
again.

Vincent

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03033/joss.03033/10.21105.joss.03033.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03033/joss.03033/10.21105.joss.03033.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.5281/zenodo.44637 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cpc.2012.11.019 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.22331/q-2019-03-11-129 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.22331/q-2018-01-31-49 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1371/journal.pone.0208073 is INVALID because of 'https://doi.org/' prefix
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@vprusso see :point_up:, can you remove the `https://doi.org/` prefix to fix these references?

**Comment by Kevin-Mattheus-Moerman** [comment]
@jedbrown @poulson @gkthiruvathukal could one of you handle this submission? Thanks

**Comment by vprusso** [comment]
Fixed the `https://doi.org/` prefix in the references.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03033/joss.03033/10.21105.joss.03033.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03033/joss.03033/10.21105.joss.03033.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.44637 is OK
- 10.1016/j.cpc.2012.11.019 is OK
- 10.22331/q-2019-03-11-129 is OK
- 10.22331/q-2018-01-31-49 is OK
- 10.1371/journal.pone.0208073 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @poulson as editor

**Comment by whedon** [comment]
@poulson has been invited to edit this submission.

**Comment by poulson** [comment]
Hi @Kevin-Mattheus-Moerman -- I am pretty comfortable with the convex optimization and linear algebra they are making use of but am pretty far from an expert on quantum information theory. I should be able to handle finding reviewers who are though.

**Comment by poulson** [comment]
@whedon set @poulson as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by poulson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by poulson** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
Hi Vincent (@vprusso) :wave:.

Thank you for this submission and, before I reach out to find a set of reviewers, are there any experts in both quantum information theory (and, ideally, python) that you would recommend?

**Comment by vprusso** [comment]
Hi Jack,

Thanks for getting back to me. Sure, I can suggest a few individuals who
are quantum information theorists who have also contributed to various
Python projects that I think would be great candidates (assuming they are
available, of course):

Sarah Kaiser: https://github.com/crazy4pi314
Josh Combes: https://github.com/joshcombes
Ryan LaRose: https://github.com/rmlarose
Nathan Shammah: https://github.com/nathanshammah
Andrea Mari: https://github.com/andreamari

Let me know what you think, and thanks again.

Vincent

**Comment by gkthiruvathukal** [comment]
@vprusso I was probably not clear on this request. Are they currently on the JOSS list of reviewers? (See link at the very top of this issue thread). It would be ideal if you can select from that list. I am working to clarify how new reviewers can be added to the system.

**Comment by vprusso** [comment]
Ah, my apologies. Sorry about that. Here are some JOSS reviewers who I
think would be well-suited for the submission:

jameshclrk
goerz
nmoran
ycchen1989
TejasAvinashShetty
WhiteSymmetry
marwahaha
rurz

Let me know if I can provide anything further, and thanks again.

**Comment by poulson** [comment]
Thank you, Vincent (@vprusso)! And I apologize for not being clearer initially.

**Comment by vprusso** [comment]
No worries at all Jack (@poulson)! Please do let me know if I can provide any further information at this time, and thanks again.

**Comment by poulson** [comment]
Hi James (@jameshclrk) -- you were recommended by Vincent Russo (@vprusso) as an expert on quantum information theory that would be appropriate for reviewing their submission of a python toolkit in that area.

Would you be willing to serve as one of the reviewers of this submission?

**Comment by poulson** [comment]
Hi Alejandra (@rurz) -- your colleague Vincent Russo (@vprusso) has recommended you as an expert on quantum information theory that would be an ideal reviewer for their python package in said area.

Please let me know if you would be willing to serve as a reviewer for this Journal of Open Source Software submission.

**Comment by rurz** [comment]
@poulson Thanks for considering me as a potential reviewer. Sure, I accept the task.

(I little typo, my name is Alejandro)

**Comment by poulson** [comment]
My apologies for the typo, Alejandro, I assure you it is what I meant to type (I pulled it from your GitHub page). 

And thank you for accepting!

**Comment by poulson** [comment]
@whedon add @rurz as reviewer

**Comment by whedon** [comment]
OK, @rurz is now a reviewer

**Comment by poulson** [comment]
Hi Kunal (@marwahaha) :wave:.

Your colleague, Vincent Russo (@vprusso) suggested you as an expert that would be an ideal reviewer for their submission of an open source package for quantum information theory.

Would you be willing to serve as a reviewer for this submission?

**Comment by marwahaha** [comment]
Sure thing. By the way, it will be my first review for JOSS.

**Comment by jameshclrk** [comment]
> Hi James (@jameshclrk) -- you were recommended by Vincent Russo (@vprusso) as an expert on quantum information theory that would be appropriate for reviewing their submission of a python toolkit in that area.
> 
> Would you be willing to serve as one of the reviewers of this submission?

Sorry for the delay in replaying - email notifications weren't working. If you're still looking for a reviewer, I'm happy to help.

**Comment by poulson** [comment]
Thanks James (@jameshclrk) and Kunal (@marwahaha) -- that makes three and we can start the review.

Thank you both for your time!

**Comment by poulson** [comment]
@whedon add @jameshclrk as reviewer

**Comment by whedon** [comment]
OK, @jameshclrk is now a reviewer

**Comment by poulson** [comment]
@whedon add @marwahaha as reviewer

**Comment by whedon** [comment]
OK, @marwahaha is now a reviewer

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3082.
