### ISSUE TITLE
[PRE REVIEW]: bleiglas: An R package for interpolation and visualisation of spatiotemporal data with 3D tessellation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3034]
**Submitting author:** @nevrome (<a href="http://orcid.org/0000-0003-3448-5715">Clemens Schmid</a>)
**Repository:** <a href="https://github.com/nevrome/bleiglas" target ="_blank">https://github.com/nevrome/bleiglas</a>
**Version:** v0.1.2
**Editor:** @vissarion
**Reviewers:** @corybrunson , @fabian-s
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @nevrome. **Currently, there isn't an JOSS editor assigned** to your paper.

@nevrome if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.24 s (127.3 files/s, 12680.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               19            200            297            975
Markdown                         2             90              0            449
Rmd                              2            111            209            178
JSON                             1              0              0            172
C++                              3             30             30            155
TeX                              1              0              0            121
C                                1              5              5             20
YAML                             1              0              2             19
C/C++ Header                     1              4              2             14
-------------------------------------------------------------------------------
SUM:                            31            440            545           2103
-------------------------------------------------------------------------------


Statistical information for the repository 'f1dd26ffd5d2dfc6f2bc423c' was
gathered on 2021/02/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Clemens Schmid                  11           591            326          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Clemens Schmid              265           44.8          0.8               13.96
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1063/1.3215722 is OK
- 10.1038/s41598-020-58834-6 is OK
- 10.1016/j.compenvurbsys.2019.101357 is OK
- 10.1093/mnras/staa1379 is OK
- 10.1007/978-3-319-29538-1 is OK
- 10.7287/peerj.preprints.3188v1 is OK
- 10.32614/RJ-2018-009 is OK
- 10.1177/1059712319860842 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03034/joss.03034/10.21105.joss.03034.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03034/joss.03034/10.21105.joss.03034.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@nevrome - because of the relatively small size of this package I'm going to flag it for editorial review.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
@nevrome The editorial board decided this is in scope.

@vissarion would you be up for editing this submission?

**Comment by kthyng** [comment]
@whedon invite @vissarion as editor

**Comment by whedon** [comment]
@vissarion has been invited to edit this submission.

**Comment by vissarion** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @vissarion

**Comment by vissarion** [comment]
:wave: @corybrunson & @amritagos, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by corybrunson** [comment]
@vissarion i would be glad to and will be able to complete my initial review within 3 weeks.

**Comment by vissarion** [comment]
Thanks @corybrunson for your quick reply.

**Comment by vissarion** [comment]
@whedon assign @corybrunson  as reviewer

**Comment by whedon** [comment]
OK, @corybrunson  is now a reviewer

**Comment by vissarion** [comment]
@robertmartin8 thank you for fixing the issues in the paper. It is now ready for review.

**Comment by vissarion** [comment]
:wave: @GISerDaishaoqing, @becarioprecario, @fpl, @fabian-s, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by amritagos** [comment]
@vissarion I am so sorry for the late reply. I'm really busy with some deadlines and will not be able to review.

**Comment by fabian-s** [comment]
@vissarion I'll do it :smiley_cat:

**Comment by vissarion** [comment]
@amritagos no problem at all! 
@fabian-s thanks for the quick reply!

**Comment by vissarion** [comment]
@whedon add @fabian-s as reviewer

**Comment by whedon** [comment]
OK, @fabian-s is now a reviewer

**Comment by vissarion** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3092.

**Comment by becarioprecario** [comment]
Hi,

Thanks but I am not available at the moment.

Best,

Virgilio

El 8 mar 2021, a las 9:35, Vissarion Fisikopoulos <notifications@github.com<mailto:notifications@github.com>> escribió:



👋 @GISerDaiShaoqing<https://github.com/GISerDaiShaoqing>, @becarioprecario<https://github.com/becarioprecario>, @fpl<https://github.com/fpl>, @fabian-s<https://github.com/fabian-s>, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by GISerDaiShaoqing** [comment]
Hi,

Sorry to reply to you late. Thanks for the invitation. If necessary now, I also could be a reviewer.

Best,

Shaoqing Dai
