### ISSUE TITLE
[PRE REVIEW]: Metatheory.jl: Fast and Elegant Algebraic Computation in Julia with Extensible Equality Saturation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3035]
**Submitting author:** @0x0f0f0f (<a href="http://orcid.org/0000-0002-8122-9469">Alessandro Cheli</a>)
**Repository:** <a href="https://github.com/0x0f0f0f/Metatheory.jl" target ="_blank">https://github.com/0x0f0f0f/Metatheory.jl</a>
**Version:** v0.1.0
**Editor:** @dpsanders
**Reviewers:** @mwillsey, @jpfairbanks, philzook58
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ 0x0f0f0f. **Currently, there isn't an JOSS editor assigned** to your paper.

@ 0x0f0f0f if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (260.9 files/s, 16697.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           30            384            217           1492
Markdown                         5             80              0            218
TeX                              2             13              0            105
YAML                             2              0             46             46
TOML                             1              4              0             16
SVG                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            41            481            263           1880
-------------------------------------------------------------------------------


Statistical information for the repository '27309fc1673a25ff79893396' was
gathered on 2021/02/12.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03035/joss.03035/10.21105.joss.03035.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03035/joss.03035/10.21105.joss.03035.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1145/3434304 may be a valid DOI for title: egg: fast and extensible equality saturation
- 10.1137/141000671 may be a valid DOI for title: Julia: A fresh approach to numerical computing
- 10.1145/2813885.2737959 may be a valid DOI for title: Automatically improving accuracy for floating point expressions
- 10.1145/322186.322198 may be a valid DOI for title: Fast decision procedures based on congruence closure

INVALID DOIs

- None
```

**Comment by 0x0f0f0f** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03035/joss.03035/10.21105.joss.03035.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03035/joss.03035/10.21105.joss.03035.pdf) :page_facing_up: :point_left:

**Comment by 0x0f0f0f** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by 0x0f0f0f** [comment]
Fixing DOIs. Anyways, here is a non-exhaustive list of potential reviewers:

- dpsanders
- ChrisRackauckas
- vchuravy
- dmbates
- ahwillia
- ninjin
- ayushpatnaikgit
- dglmoore
- avik-pal
- pitsianis 
- henrik227

**Comment by 0x0f0f0f** [comment]
@whedon generate pdf

**Comment by 0x0f0f0f** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03035/joss.03035/10.21105.joss.03035.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03035/joss.03035/10.21105.joss.03035.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/3434304 is OK
- 10.1137/141000671 is OK
- 10.1145/2813885.2737959 is OK
- 10.1145/2737924.2737959 is OK
- 10.1145/322186.322198 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by 0x0f0f0f** [comment]
Is there anything else I should do for pre-review?

**Comment by 0x0f0f0f** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.19 s (279.9 files/s, 16130.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           40            472            235           1776
Markdown                         8             96              0            269
TeX                              2             21              0            157
YAML                             1              0              0             57
TOML                             2              4              1             21
SVG                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            54            593            236           2283
-------------------------------------------------------------------------------


Statistical information for the repository 'd3d77bdb203b2dec77ed30fa' was
gathered on 2021/02/16.
No commited files with the specified extensions were found.
```

**Comment by 0x0f0f0f** [comment]
I don't understand why whedon does not list any commit. I have pushed 90 so far.

**Comment by Kevin-Mattheus-Moerman** [comment]
> I don't understand why whedon does not list any commit. I have pushed 90 so far.

@0x0f0f0f I believe this feature (for whedon to scan the repository) is relatively new and might not yet be 100% accurate. I'll ping @openjournals/dev to see if they can check this out.

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkthiruvathukal @mjsottile @dpsanders could one of you handle this submission?

**Comment by arfon** [comment]
> @0x0f0f0f I believe this feature (for whedon to scan the repository) is relatively new and might not yet be 100% accurate. I'll ping @openjournals/dev to see if they can check this out.

Not sure what is going on here sorry. We simply run `gitinspector` (https://github.com/openjournals/whedon-api/blob/master/workers.rb#L379) so perhaps it is struggling with this repository for some reason.

**Comment by 0x0f0f0f** [comment]
I have updated Package version to `v0.1.1`.

**Comment by dpsanders** [comment]
@Kevin-Mattheus-Moerman: I can handle this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @dpsanders as editor

**Comment by whedon** [comment]
OK, the editor is @dpsanders

**Comment by 0x0f0f0f** [comment]
@whedon set v0.1.1 as version

**Comment by whedon** [comment]
I'm sorry @0x0f0f0f, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by 0x0f0f0f** [comment]
whoops!

**Comment by 0x0f0f0f** [comment]
Extending the list of potential reviewers from the Google sheets file.

- dpsanders
- ChrisRackauckas
- vchuravy
- dmbates
- ahwillia
- ninjin
- ayushpatnaikgit
- dglmoore
- avik-pal
- pitsianis 
- henrik227 (interested in symbolic computation)
- moorepants (interested in symbolic computation)

**Comment by dpsanders** [comment]
👋 @philzook58 and @jpfairbanks: Would you be willing and able to review this submission for JOSS? Thanks!

**Comment by dpsanders** [comment]
@whedon add @mwillsey as reviewer

**Comment by whedon** [comment]
OK, @mwillsey is now a reviewer

**Comment by dpsanders** [comment]
@whedon add @jpfairbanks as reviewer

**Comment by whedon** [comment]
OK, @jpfairbanks is now a reviewer

**Comment by dpsanders** [comment]
@whedon add philzook58 as reviewer

**Comment by whedon** [comment]
OK, philzook58 is now a reviewer

**Comment by dpsanders** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3078.
