### ISSUE TITLE
[PRE REVIEW]: osmdata

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#304]
**Submitting author:** @mpadge (<a href="http://orcid.org/0000-0003-2172-5265">Mark Padgham</a>)
**Repository:** <a href="https://github.com/ropensci/osmdata" target ="_blank">https://github.com/ropensci/osmdata</a>
**Version:** v0.0.2
**Editor:** @karthik
**Reviewer:** @karthik

**Author instructions**

Thanks for submitting your paper to JOSS @mpadge. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mpadge if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@openjournals/ropensci - could you link the associated rOpenSci onboarding issue here please?

**Comment by karthik** [comment]
Accepting without additional review: https://github.com/ropensci/onboarding/issues/103

**Comment by karthik** [comment]
@mpadge Please update the thread with the Zenodo/figshare DOI so we can move forward with this.

**Comment by mpadge** [comment]
[https://doi.org/10.5281/zenodo.803231](https://doi.org/10.5281/zenodo.803231)

**Comment by arfon** [comment]
@whedon assign @karthik as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @karthik

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/305. Feel free to close this issue now!
