### ISSUE TITLE
[PRE REVIEW]: SkyPy: A package for modelling the Universe

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3043]
**Submitting author:** @rrjbca (<a href="http://orcid.org/0000-0003-1291-1023">Richard Rollins</a>)
**Repository:** <a href="https://github.com/skypyproject/skypy" target ="_blank">https://github.com/skypyproject/skypy</a>
**Version:** v0.4
**Editor:** @arfon
**Reviewers:** @cescalara, @rmorgan10
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @rrjbca. **Currently, there isn't an JOSS editor assigned** to your paper.

@rrjbca if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.22 s (414.9 files/s, 32567.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          46           1029           1740           1999
reStructuredText                17            333            225            469
SVG                              1              0              0            333
YAML                            16              9              0            238
DOS Batch                        1             21              1            150
Markdown                         5             55              0            148
JSON                             1              0              0            121
make                             1             22              5            108
INI                              1             16              0             99
CSS                              1              3              0             12
TOML                             1              2              0              5
-------------------------------------------------------------------------------
SUM:                            91           1490           1971           3682
-------------------------------------------------------------------------------


Statistical information for the repository 'b711181b2c9c25c809bcd996' was
gathered on 2021/02/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adam Amara                       2          1497              0            6.49
Andrew R. Williamson             1             4              0            0.02
Andy Lundgren                    1            55              5            0.26
Brian Nord                       1             4              0            0.02
Ian Harrison                     8           710             84            3.44
Ian Harry                        4           246            126            1.61
JonathanDHarris                  2            72              1            0.32
Juan Pablo Cordero               3           364             19            1.66
Lucia F. de la Bella             1           126              0            0.55
Lucia-Fonseca                   15          1667            242            8.28
Nicolas Tessore                 70          4915           4762           41.96
Richard R                       43          3126            929           17.58
Sarah Bridle                     2            13             11            0.10
Simon Birrer                     1             0              1            0.00
nstarman                         1             3              0            0.01
philipp128                       9          1111            148            5.46
skypybot                         7             2           2819           12.23

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adam Amara                  277           18.5          0.0               44.40
Andy Lundgren                32           58.2         10.1               18.75
Ian Harrison                241           33.9          0.9               11.20
JonathanDHarris               3            4.2          3.0                0.00
Lucia-Fonseca               465           27.9          7.9               19.78
Nicolas Tessore            2191           44.6          4.7               11.82
Richard R                  1237           39.6          2.7               17.70
Sarah Bridle                 11           84.6          0.9               18.18
nstarman                      3          100.0          3.8               33.33
philipp128                  307           27.6          8.5                6.84
skypybot                      1           50.0          1.2                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3043 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3043 with the following error: 

 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.292 ....uk}{\nolinkurl{adam.amara@port.ac.uk}}}}

Looks like we failed to compile the PDF

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you help trouble shoot this error :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@dpsanders @dfm could one of you edit this submission? I know you are both handling quite a few submissions already so let me know if you cannot. Alternatively @terrytangyuan since this relates to machine learning do you think you can help?

**Comment by arfon** [comment]
> @openjournals/dev can you help trouble shoot this error ☝️

I think the `@` in the emails in the authors need escaping, e.g.:

```
authors:
  - name: Adam Amara^[adam.amara\@port.ac.uk]
    orcid: 0000-0003-3481-3491
    affiliation: 1
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@rrjbca can you implement these changes and call `@whedon generate pdf from branch joss-paper` here to update the paper?

**Comment by rrjbca** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03043/joss.03043/10.21105.joss.03043.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03043/joss.03043/10.21105.joss.03043.pdf) :page_facing_up: :point_left:

**Comment by terrytangyuan** [comment]
> @dpsanders @dfm could one of you edit this submission? I know you are both handling quite a few submissions already so let me know if you cannot. Alternatively @terrytangyuan since this relates to machine learning do you think you can help?

Sorry I probably don't have bandwidth to help at this point.

**Comment by Kevin-Mattheus-Moerman** [comment]
@dpsanders @dfm could one of you edit this submission? I think you have a lot on your plates already so no worries if you can't. Thanks!

**Comment by arfon** [comment]
If @dpsanders or @dfm can't take it I can.

**Comment by dpsanders** [comment]
I don't think I can take any more on right now, thanks.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@rrjbca - thanks for your submission to JOSS? Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission? (Please avoid @mentioning them here).

Also, if there are other people in the community who you think might be able to give this package a good review, please let me know.

**Comment by rrjbca** [comment]
@arfon thank you for considering our submission! We would suggest the following reviewers: cescalara, rmorgan10, jborrow, ejhigson, astrom-tom, coljac, aureliocarnero, adrn, steven-murray, mgckind.

**Comment by arfon** [comment]
:wave: @cescalara @rmorgan10 @adrn - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration is [_SkyPy: A package for modelling the Universe_](https://github.com/skypyproject/skypy)

**Comment by cescalara** [comment]
Hi, I'd be happy to review.

**Comment by arfon** [comment]
@rrjbca - does this submission accompany a paper in a AAS journal?

**Comment by arfon** [comment]
@whedon add @cescalara as reviewer

**Comment by whedon** [comment]
OK, @cescalara is now a reviewer

**Comment by arfon** [comment]
> Hi, I'd be happy to review.

:zap: thanks! I'll wait until a second reviewer has been identified before opening the main review issue. Hopefully this won't take too long 😄

**Comment by rmorgan10** [comment]
I'd be happy to review as well. I'm currently away from my computer so I won't be able to start my review until next week, but I'll certianly be able to get it done within the usual JOSS timeframe

**Comment by rrjbca** [comment]
> @rrjbca - does this submission accompany a paper in a AAS journal?

@arfon No this is a stand-alone submission

**Comment by arfon** [comment]
@whedon add @rmorgan10 as reviewer

**Comment by whedon** [comment]
OK, @rmorgan10 is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3056.

**Comment by arfon** [comment]
@cescalara, @rmorgan10 - thanks for agreeing to review this submission. See you over in #3056 where the main review will take place.
