### ISSUE TITLE
[PRE REVIEW]: HOODESolver.jl: A Julia package for highly oscillatory problems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3044]
**Submitting author:** @pnavaro (<a href="http://orcid.org/0000-0002-7372-3221">Pierre Navaro</a>)
**Repository:** <a href="https://github.com/ymocquar/HOODESolver.jl" target ="_blank">https://github.com/ymocquar/HOODESolver.jl</a>
**Version:** v0.2.3
**Editor:** @vissarion
**Reviewers:** @ranocha, @HaoZeke
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pnavaro. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dpsanders.

@pnavaro if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.66 s (89.8 files/s, 83205.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           40            308            282          51677
Markdown                         9            194              0            494
YAML                             4              7              1            110
TeX                              2              1              0             61
TOML                             3              4              0             37
Jupyter Notebook                 1              0           1485             36
-------------------------------------------------------------------------------
SUM:                            59            514           1768          52415
-------------------------------------------------------------------------------


Statistical information for the repository '34c9d2edb6cc8ed08ae267e3' was
gathered on 2021/02/17.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3044 with the following error: 

 Can't find any papers to compile :-(

**Comment by pnavaro** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by pnavaro** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03044/joss.03044/10.21105.joss.03044.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03044/joss.03044/10.21105.joss.03044.pdf) :page_facing_up: :point_left:

**Comment by pnavaro** [comment]
According to the list, Hendrik Ranocha ranocha is a potential reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@mjsottile @diehlpk @melissawm could one of you edit this submission? Thanks

**Comment by diehlpk** [comment]
@Kevin-Mattheus-Moerman I could do it, however, I would prefer if someone else can do it since I have plenty of submiisions right now.

**Comment by mjsottile** [comment]
@Kevin-Mattheus-Moerman I'm at my capacity for the moment, so I can't take a new paper right now.

**Comment by Kevin-Mattheus-Moerman** [comment]
@vissarion @arfon would this be a nice first submission to handle?

**Comment by arfon** [comment]
@whedon invite @vissarion as editor

**Comment by whedon** [comment]
@vissarion has been invited to edit this submission.

**Comment by vissarion** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @vissarion

**Comment by vissarion** [comment]
@pnavaro the submission is in scope, I am searching for potential reviewers

**Comment by vissarion** [comment]
@dawbarton @ranocha Would you be willing to contribute a review for this JOSS submission?

**Comment by ranocha** [comment]
@vissarion I can review the submission but I will probably not have enough time for it in the immediate future (next weeks), but probably around end of March or beginning of April.

**Comment by vissarion** [comment]
@ranocha according to current difficult circumstances, "end of March or beginning of April" sounds OK for me. Thanks for accepting!

**Comment by vissarion** [comment]
@whedon assign @ranocha as reviewer

**Comment by whedon** [comment]
OK, @ranocha is now a reviewer

**Comment by dawbarton** [comment]
Apologies I'm snowed under with teaching duties at the moment and I'm not going to have time to look at this in the near future

**Comment by vissarion** [comment]
@dawbarton no problem, thanks for the reply.

**Comment by vissarion** [comment]
:wave: @ysimillides, @HaoZeke, @yangbai90, @raghurama123, @Datseris, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by vissarion** [comment]
@HaoZeke thanks for replying  in a flash.

**Comment by vissarion** [comment]
@whedon add @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, @HaoZeke is now a reviewer

**Comment by vissarion** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3077.
