### ISSUE TITLE
[PRE REVIEW]: imodels: a python package for fitting interpretable models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3046]
**Submitting author:** @csinva (<a href="http://orcid.org/0000-0003-0318-2340">Chandan Singh</a>)
**Repository:** <a href="https://github.com/csinva/imodels" target ="_blank">https://github.com/csinva/imodels</a>
**Version:** v0.2.7
**Editor:** @vissarion
**Reviewers:** @jungtaekkim, @yxoos 
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @csinva. **Currently, there isn't an JOSS editor assigned** to your paper.

@csinva if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.62 s (173.1 files/s, 46561.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            41           2021              0          18218
Python                          48           1059           1221           4045
CSS                              1             40             21            347
Markdown                         7             88              0            284
Jupyter Notebook                 5              0           1323            231
TeX                              1              9              0             87
YAML                             2              5              2             29
Bourne Shell                     2              0              1             17
TOML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                           108           3222           2568          23259
-------------------------------------------------------------------------------


Statistical information for the repository '7885deb3e66e86d35ba27917' was
gathered on 2021/02/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Avi A                            1             1              0            0.01
Chandan Singh                   73          8266           2387           74.80
Keyan Nasseri                   48          2007           1581           25.19

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chandan Singh              4965           60.1          2.5                8.64
Keyan Nasseri              1360           67.8          1.8                9.26
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03046/joss.03046/10.21105.joss.03046.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03046/joss.03046/10.21105.joss.03046.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1007/s10994-015-5528-6 may be a valid DOI for title: Supersparse linear integer models for optimized medical scoring systems
- 10.1214/15-aoas848 may be a valid DOI for title: Interpretable classifiers using rules and bayesian analysis: Building a better stroke prediction model
- 10.1201/9780367816377-16 may be a valid DOI for title: Interpretable machine learning
- 10.1214/07-aoas148 may be a valid DOI for title: Predictive learning via rule ensembles

INVALID DOIs

- None
```

**Comment by csinva** [comment]
Just added all the missing DOIs!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03046/joss.03046/10.21105.joss.03046.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03046/joss.03046/10.21105.joss.03046.pdf) :page_facing_up: :point_left:

**Comment by csinva** [comment]
Anyone with experience in interpretable machine learning and python would make a great reviewer! Looking at the list of  volunteer reviewers, I think the following people would make wonderful reviewers (starting from the bottom of the volunteer reviewer list):

hbaniecki, xiaohk, expectopatronum

**Comment by kthyng** [comment]
Hi @galessiorob are you up for editing this submission?

**Comment by kthyng** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by galessiorob** [comment]
@kthyng I'm spread out a bit thin at the moment, apologies for the delayed response.

**Comment by danielskatz** [comment]
👋 @cMadan - are you able to edit this perhaps?

**Comment by danielskatz** [comment]
@whedon invite @cMadan as editor

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by cMadan** [comment]
I don't think I can take on another review at this time, sorry!

**Comment by kyleniemeyer** [comment]
Hi @csinva, it looks like editor availability in this area is a bit low at the moment (many of our editors are at reduced capacity at the moment), so I'm going to put this in the waitlist for now.

**Comment by kyleniemeyer** [comment]
@whedon invite @vissarion as editor

Hi @vissarion, could you edit this one?

**Comment by whedon** [comment]
@vissarion has been invited to edit this submission.

**Comment by vissarion** [comment]
@whedon assign @vissarion  as editor

**Comment by whedon** [comment]
OK, the editor is @vissarion

**Comment by vissarion** [comment]
:wave: @RohitRathore1, @yxoos, @jungtaekkim, @juliensiebert, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by jungtaekkim** [comment]
I am willing to review this submission.

**Comment by yxoos** [comment]
I am open to review as well.

**Comment by vissarion** [comment]
@whedon assign @jungtaekkim as reviewer

**Comment by whedon** [comment]
OK, @jungtaekkim is now a reviewer

**Comment by vissarion** [comment]
@whedon add @yxoos  as reviewer

**Comment by whedon** [comment]
OK, @yxoos  is now a reviewer

**Comment by vissarion** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3192.
