### ISSUE TITLE
[PRE REVIEW]: WhaleMap: a tool to collate and display whale survey results in near real-time

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3047]
**Submitting author:** @hansenjohnson (<a href="http://orcid.org/0000-0002-3086-6759">Hansen Johnson</a>)
**Repository:** <a href="https://github.com/hansenjohnson/WhaleMap" target ="_blank">https://github.com/hansenjohnson/WhaleMap</a>
**Version:** v1.0.0
**Editor:** @KristinaRiemer
**Reviewers:** @pjbouchet, @mcsiple
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @hansenjohnson. **Currently, there isn't an JOSS editor assigned** to your paper.

@hansenjohnson if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.29 s (401.5 files/s, 49296.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               99           3379           3328           5961
make                             1             97            105            446
Bourne Shell                    12             84             93            240
Markdown                         3             76              0            229
Rmd                              1             71             89            144
TeX                              1              1              0             22
-------------------------------------------------------------------------------
SUM:                           117           3708           3615           7042
-------------------------------------------------------------------------------


Statistical information for the repository '6ef6b0d3ad106134a17acf8a' was
gathered on 2021/02/20.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1121/10.0001811 is OK
- 10.1111/csp2.267 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03047/joss.03047/10.21105.joss.03047.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03047/joss.03047/10.21105.joss.03047.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@hansenjohnson thanks for this submission. Our system detected the paper currently lacks a `Statement of need` section [which is required](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). Can you add such a section to you paper? It should illustrate the research purpose of the software.

**Comment by Kevin-Mattheus-Moerman** [comment]
Notes for handling editor, this work seems to relate to these papers: 
https://github.com/openjournals/joss-reviews/issues/1825
https://github.com/openjournals/joss-reviews/issues/2097
https://github.com/openjournals/joss-reviews/issues/2172

**Comment by Kevin-Mattheus-Moerman** [comment]
@KristinaRiemer @karthik @marcosvital @jni could one of you handle this submission? Note there are some related papers :point_up: which might help to find reviewers too.

**Comment by hansenjohnson** [comment]
Thank you @Kevin-Mattheus-Moerman! I made some very slight changes to explicitly include a `Statement of need` section. Sorry for omitting that in the first place!

**Comment by hansenjohnson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by hansenjohnson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03047/joss.03047/10.21105.joss.03047.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03047/joss.03047/10.21105.joss.03047.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@KristinaRiemer @karthik @marcosvital @jni @kthyng could one of you handle this submission? Note these are some related papers which might help to find reviewers too:
https://github.com/openjournals/joss-reviews/issues/1825
https://github.com/openjournals/joss-reviews/issues/2097
https://github.com/openjournals/joss-reviews/issues/2172

**Comment by kthyng** [comment]
Hi @hansenjohnson and thanks for your submission. It looks like a really interesting project! I am going to ping the editorial board to make sure that it is in scope before we move forward. This isn't a statement on how awesome your project is, but just to check for fit. This will take 1-2 weeks and someone will get back to you. Thanks for your patience.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by hansenjohnson** [comment]
Thank you @kthyng! I recognize this is a bit of an odd submission and think a scope query is a great place to start. I look forward to hearing from the team. Much appreciated!

**Comment by danielskatz** [comment]
This submission has been determined to be in-scope

**Comment by danielskatz** [comment]
👋 @KristinaRiemer - you were suggested as the editor for this submission.  Are you able to take it on?

**Comment by danielskatz** [comment]
@whedon invite @KristinaRiemer as editor

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by KristinaRiemer** [comment]
Hi, yes, I'm able to take care of this submission. (I had accidentally turned off GitHub notifications for this repo 🤦‍♀️)

**Comment by KristinaRiemer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @KristinaRiemer

**Comment by KristinaRiemer** [comment]
@whedon assign @pjbouchet as reviewer

**Comment by whedon** [comment]
OK, @pjbouchet is now a reviewer

**Comment by whedon** [comment]
OK, @mcsiple is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3094.

**Comment by KristinaRiemer** [comment]
Thanks to @pjbouchet and @mcsiple for agreeing to review this submission! The review will happen in the GitHub issue linked to above. Feel free to ask me questions there! Use the checklist as a guide for your review, and file issues in the submission repo to suggest improvements.
