### ISSUE TITLE
[PRE REVIEW]: IDCeMPy: Python Package for Inflated Discrete Choice Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3048]
**Submitting author:** @hknd23 (<a href="http://orcid.org/0000-0002-6234-7232">Nguyen Huynh</a>)
**Repository:** <a href="https://github.com/hknd23/idcempy" target ="_blank">https://github.com/hknd23/idcempy</a>
**Version:** 0.0.1
**Editor:** @galessiorob
**Reviewers:** @cmaimone, @jungtaekkim
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @hknd23. **Currently, there isn't an JOSS editor assigned** to your paper.

@hknd23 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (141.1 files/s, 16950.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            211            453           1582
Markdown                         2            113              0            378
TeX                              1             21              0            158
reStructuredText                 5            238            282            144
XML                             10              0              0             91
YAML                             3             15             42             61
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            32            610            785           2449
-------------------------------------------------------------------------------


Statistical information for the repository 'd17248db734bee286597d116' was
gathered on 2021/02/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nguyen Huynh                     1            11             11            0.07
bebejar                          4           165            165            1.03
hknd23                          59         16989          14743           98.90

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Sergio Bejar                146          100.0          0.2                0.00
hknd23                     2100           12.4          0.4                5.67
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1162/ajhe_a_00026 is OK
- 10.1016/j.jeconom.2007.01.002 is OK
- 10.3386/w8419 is OK
- 10.2307/2998213 is OK
- 10.2139/ssrn.3187203 is OK
- 10.1017/psrm.2015.42 is OK
- 10.1093/pan/mps020 is OK
- 10.1111/j.1540-5907.2009.00399.x is OK
- 10.1111/obes.12366 is OK
- 10.1177/1536867X19874246 is OK
- 10.1016/j.amar.2018.04.003 is OK
- 10.4324/9781315623351-27 is OK
- 10.1177/1065912907305684 is OK
- 10.1093/poq/nfn032 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03048/joss.03048/10.21105.joss.03048.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03048/joss.03048/10.21105.joss.03048.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @hknd23 and thanks for your submission! We currently have low editor availability in this area, so I am going to add the "waitlist" label until we are able to assign this submission to an editor. Thanks for your patience.

**Comment by Sergio-Bejar** [comment]
Hi @kthyng, thanks for keeping us in the loop!  We have no problem waiting until our submission is assigned to an editor.   Thanks to you and other members of the editorial board for your hard work.

**Comment by danielskatz** [comment]
👋 @galessiorob - Would you be willing to edit this submission?  It might be a little out of your area, but it's been waiting a while, and I hope you can take it on...

**Comment by danielskatz** [comment]
@whedon invite @galessiorob as editor

**Comment by whedon** [comment]
@galessiorob has been invited to edit this submission.

**Comment by galessiorob** [comment]
Happy to edit this paper @danielskatz, thanks for the invite!

👋 Hi @Sergio-Bejar 

I am in the process of assigning reviewers to this submission, if you have any suggestions please let me know and feel free to @ mention them here.

Basic checks to go over before we formally start the review:

 - [ ] There’s a general description of the software
           Needs expanding
 - [ ] The software is within the scope as research software
           Potentially to be expanded to denote research application and use cases
 - [ ] OSI-approved license: GNU General Public License (GPL)

**Comment by danielskatz** [comment]
Thanks @galessiorob - as we might have discussed before, once you agree to edit, you can assign yourself with the same command that I will use, though I will do it this time

**Comment by danielskatz** [comment]
@whedon assign @galessiorob as editor

**Comment by whedon** [comment]
OK, the editor is @galessiorob

**Comment by Sergio-Bejar** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03048/joss.03048/10.21105.joss.03048.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03048/joss.03048/10.21105.joss.03048.pdf) :page_facing_up: :point_left:

**Comment by Sergio-Bejar** [comment]
👋 Hi @galessiorob, 

Thanks for agreeing to edit our submission, and for providing us with suggestions to improve the quality of our manuscript! 
We have addressed all your requests.  Specifically, (i) we expanded the general description of the software in both the Statement of Need and Package Architecture sections (see pages 2 & 3); (ii) expanded the description of the package's application and use cases in both the Summary, Package Architecture, and Application sections; and (iii) added the GNU General Public License (GPL) statement in both the paper and GitHub repo.   

I went ahead and created a PDF file of the updated manuscript.  I hope this is ok with you.  

We'd like to suggest the following people (GitHub user names) as potential reviewers:
- alexhanna
- ohmaddi
- cmaimone
- chainsawriot

Thanks again for your time and effort editing our submission.  Please let us know if there's any other information we should provide to start the formal review.

**Comment by galessiorob** [comment]
Thanks for being so proactive @Sergio-Bejar 👏

I'll start adding the reviewers once they agree to the assignment.

**Comment by Sergio-Bejar** [comment]
Thanks for the update, @galessiorob!   If you need additional names, please let us know.

**Comment by galessiorob** [comment]
@whedon assign @cmaimone as reviewer

**Comment by whedon** [comment]
OK, @cmaimone is now a reviewer

**Comment by galessiorob** [comment]
@whedon add @jungtaekkim as a reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by galessiorob** [comment]
@whedon add @jungtaekkim as reviewer

**Comment by whedon** [comment]
OK, @jungtaekkim is now a reviewer

**Comment by galessiorob** [comment]
🎉 Thanks for volunteering to be reviewers @cmaimone and @jungtaekkim!

I'll generate a "review issue" that will contain individual checklists to go through, feel free to get started at your earliest convenience, don't hesitate to ask if you need clarification or help - you can @mention me directly on the issue.

**Comment by galessiorob** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3322.
