### ISSUE TITLE
[REVIEW]: Autosubmit GUI: A Javascript-based Graphical User Interface to Monitor Experiments Workflow Execution

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3049]
**Submitting author:** @wuruchi (<a href="http://orcid.org/0000-0003-0842-0459">Wilmer Uruchi Ticona</a>)
**Repository:** <a href="https://earth.bsc.es/gitlab/wuruchi/autosubmitreact" target ="_blank">https://earth.bsc.es/gitlab/wuruchi/autosubmitreact</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @djmitche, @ikayz
**Archive:** <a href="https://doi.org/10.6084/m9.figshare.14230052.v1" target="_blank">10.6084/m9.figshare.14230052.v1</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a8ac17f6c02fdf76098ac97ed3e09b22/status.svg)](https://joss.theoj.org/papers/a8ac17f6c02fdf76098ac97ed3e09b22)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a8ac17f6c02fdf76098ac97ed3e09b22"><img src="https://joss.theoj.org/papers/a8ac17f6c02fdf76098ac97ed3e09b22/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a8ac17f6c02fdf76098ac97ed3e09b22/status.svg)](https://joss.theoj.org/papers/a8ac17f6c02fdf76098ac97ed3e09b22)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://earth.bsc.es/gitlab/wuruchi/autosubmitreact" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@djmitche, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://earth.bsc.es/gitlab/wuruchi/autosubmitreact">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@wuruchi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://earth.bsc.es/gitlab/wuruchi/autosubmitreact">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@wuruchi) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @djmitche it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by arfon** [comment]
@djmitche - This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention https://github.com/openjournals/joss-reviews/issues/3049 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/HPCSim.2016.7568429 is OK
- 10.5194/gmd-10-19-2017 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03049/joss.03049/10.21105.joss.03049.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03049/joss.03049/10.21105.joss.03049.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=234.27 s (111.1 files/s, 14807.6 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code
---------------------------------------------------------------------------------------
JavaScript                           18446         332936         353174        1848739
JSON                                  2833            296              0         370196
Markdown                              2179          88917              4         220358
HTML                                   312          18648            405          64383
TypeScript                            1768           8268          44195          53475
CSS                                    104           1297           2642          20501
C/C++ Header                            42           1342            431           7073
C++                                     22           1292           1096           5645
D                                       20              0              0           5567
YAML                                   213            244            176           4207
XML                                      3            233             11           2011
CoffeeScript                            28            611             54           1649
LESS                                    13            272            745           1630
make                                    20            277            384            988
Bourne Shell                             8            194            132            936
Python                                   4             83            177            798
SVG                                      8             14              5            681
diff                                     1              3             13            588
Windows Module Definition                5             83              0            451
PHP                                      1             33             52             70
JSON5                                    1              0              0             55
TeX                                      1              7              0             46
Bourne Again Shell                       2             11              1             43
TOML                                     1              2              0             39
EJS                                      1              0              0              9
Lisp                                     1              0              0              6
DOS Batch                                1              0              0              2
---------------------------------------------------------------------------------------
SUM:                                 26038         455063         403697        2610146
---------------------------------------------------------------------------------------


Statistical information for the repository 'a0cb992e191e8a4c34575aa3' was
gathered on 2021/02/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Wilmer Uruchi Ticona            59       2258199         102129           61.41
bleudchanel                     68       1098792         375195           38.35
wuruchi                         24          7716           1673            0.24

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
bleudchanel             1084557           98.7          4.0               11.96
wuruchi                 1966741        25489.1          2.0               16.12
```

**Comment by arfon** [comment]
@whedon add @ikayz as reviewer

**Comment by whedon** [comment]
OK, @ikayz is now a reviewer

**Comment by arfon** [comment]
@whedon re-invite @ikayz as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@ikayz please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by arfon** [comment]
@ikayz - many thanks for agreeing to review this submission! I've added a checklist for you above. Please take a look at the [message I posted](https://github.com/openjournals/joss-reviews/issues/3049#issuecomment-782621514) earlier in the thread on what to do next.

Any questions, please ask!

**Comment by ikayz** [comment]
@arfon thanks I'll check them out and ask questions

**Comment by wuruchi** [comment]
Hello @arfon @djmitche @ikayz 

We are very happy to have progressed into this stage of the process, and we are glad to be working with you. 

As a note: 

From the author's analysis: Wilmer Uruchi Ticona, bleudchanel, and wuruchi are all my usernames. I guess some of them got mixed in when I switched to working from home around March/April of 2020.

**Comment by ikayz** [comment]
I'm glad to assist in anyway. I was wondering if all those user names are different people 😅

**Comment by djmitche** [comment]
I meant to get to this over the weekend, but I will find time during this week to do so.  Sorry!

**Comment by djmitche** [comment]
I'm midway through review, but have a few comments, none of them major.

First, the tests fail for me:
```
 FAIL  src/components/context/utils.test.js
  ● 1604334422 is converted to [2/11]17:27:02

    expect(received).toBe(expected) // Object.is equality

    Expected: "[2/11] 17:27:02"
    Received: "[2/11] 11:27:02"

      2 |
      3 | test('1604334422 is converted to [2/11]17:27:02', () => {
    > 4 |   expect(timeStampToDate(1604334422)).toBe("[2/11] 17:27:02");
        |                                       ^
      5 | });
      6 |
      7 | test('1600 seconds to delta 00:26:40', () => {

      at Object.<anonymous> (src/components/context/utils.test.js:4:39)

Summary of all failing tests
 FAIL  src/components/context/utils.test.js
  ● 1604334422 is converted to [2/11]17:27:02

    expect(received).toBe(expected) // Object.is equality

    Expected: "[2/11] 17:27:02"
    Received: "[2/11] 11:27:02"

      2 |
      3 | test('1604334422 is converted to [2/11]17:27:02', () => {
    > 4 |   expect(timeStampToDate(1604334422)).toBe("[2/11] 17:27:02");
        |                                       ^
      5 | });
      6 |
      7 | test('1600 seconds to delta 00:26:40', () => {

      at Object.<anonymous> (src/components/context/utils.test.js:4:39)
```
I suspect this is because I'm not in the CET timezone!

Second, the paper is mostly fine but I found the sentence about Javascript starting on line 70 ("This programming language has..") to be needlessly opinionated -- my reaction was "if you hate JS so much why did you do this project?"  The paper would still be complete without the sentence.

Finally, a point of clarification for myself: is autosubmit, and with it this application, something which might be installed by other HPC groups, or is it specific to BSC?  AIUI that doesn't affect eligibility for the paper, but is relevant in judging the usefulness of the documentation.

Thanks!

**Comment by djmitche** [comment]
Actually, I'd like some confirmation/guidance on the last point, @arfon.

**Comment by wuruchi** [comment]
Hello @djmitche 

Thanks for the feedback. 

> I suspect this is because I'm not in the CET timezone

Looks like we forgot to test against other timezones. Working on it.

> Second, the paper is mostly fine but I found the sentence about Javascript starting on line 70 ("This programming language has..") to be needlessly opinionated 

You are correct. I guess we tried to convey some of the controversy surrounding Javascript in a way that emphasizes that despite that controversy, we still think it is a good choice. That sentence will be reworded.

>is autosubmit, and with it this application, something which might be installed by other HPC groups, or is it specific to BSC?

Autosubmit can be installed by other HPC groups but would require some configuration to address any particular setting in the new environment. Autosubmit GUI consumes an API whose data is generated by Autosubmit at BSC, but another workflow manager can (in theory) generate similar information an Autosubmit GUI can be adapted to consume that information. The main objective is that Autosubmit GUI can be used as a template or starting point for other HPC groups that need a visual monitoring tool for their workflow managers, or if they decide to use Autosubmit.

**Comment by wuruchi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03049/joss.03049/10.21105.joss.03049.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03049/joss.03049/10.21105.joss.03049.pdf) :page_facing_up: :point_left:

**Comment by wuruchi** [comment]
Hello @djmitche 

I have pushed the changes I mentioned in my previous response.

**Comment by djmitche** [comment]
> Autosubmit can be installed by other HPC groups but would require some configuration to address any particular setting in the new environment. Autosubmit GUI consumes an API whose data is generated by Autosubmit at BSC, but another workflow manager can (in theory) generate similar information and Autosubmit GUI can be adapted to consume that information. The main objective is that Autosubmit GUI can be used as a template or starting point for other HPC groups that need a visual monitoring tool for their workflow managers, or if they decide to use Autosubmit.

This does clarify the situation. I see parts of the above paragraph in the paper and README, so I think this was a failure on my part to comprehend what had already been made clear.  Thanks!

The changes look good, and the tests now pass :)

**Comment by djmitche** [comment]
> 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I'm still struggling with this a little bit.  The README addresses the first two, and (3) isn't an issue since groups outside BSC wouldn't use this software.  The JOSS guidelines are silent on this issue, so I'll check the box.

**Comment by ikayz** [comment]
@wuruchi I'll get to it this weekend. Had a busy couple of weeks.

**Comment by djmitche** [comment]
My review is complete (and I don't mean to rush you @ikayz!).  I had a look through the source and this seems like a solid, well-factored React app.  Anyone familiar with React dev could jump into this quickly and solve a bug or add a feature.  Nice work!

**Comment by ikayz** [comment]
@wuruchi so I've done I think half of the review. Some feedback, the node_modules folder causes an issue on Windows-based machines (Tried it on two machines, same result). I noticed they were not ignored in the gitiginore file. I had to delete the directory and reinstall the dependencies by running `npm install`. The tests are failing to run due to canvas.node

![image](https://user-images.githubusercontent.com/31007212/110255629-6372e800-7f9d-11eb-8a62-ac53a0e36e74.png)

Jest failed to run until I installed it as a dev dependency. This might be a Windows-related error. These are my finds so far.

**Comment by djmitche** [comment]
Yikes, how did I miss that?  `node_modules` definitely should not be in version control!  Note, too, that `yarn` sees to be the de-facto replacement for `npm`.  Assuming `node_modules` is in the repo due to some bug with `npm`, switching to `yarn` is probably the fix.

**Comment by wuruchi** [comment]
Hello @ikayz @djmitche 

>I'm still struggling with this a little bit. The README addresses the first two, and (3) isn't an issue since groups outside BSC wouldn't use this software. The JOSS guidelines are silent on this issue, so I'll check the box.

We can say that at BSC we are open to collaboration, and any team willing to seek support to adapt/modify/improve this application can contact us. I added a line about it at the end of the README.

>node_modules definitely should not be in version control! Note, too, that yarn sees to be the de-facto replacement for npm. 

I guess we included it at some point in the repository because we were not really sure about our dependencies. I have deleted the node_modules folder and included the necessary installation instructions on the README.

>I had a look through the source and this seems like a solid, well-factored React app. Anyone familiar with React dev could jump into this quickly and solve a bug or add a feature. Nice work!

Thank you!

>Some feedback, the node_modules folder causes an issue on Windows-based machines (Tried it on two machines, same result). I noticed they were not ignored in the gitiginore file. I had to delete the directory and reinstall the dependencies by running npm install.

Thanks for your time @ikayz. I have deleted the node_modules folder from the repository and made sure that the install process runs without issues. I have tested it (from a fresh clone) on an OSX machine and also on a Windows machine without issue. I used git bash on the windows machine. Please test it again, it should work fine now.

**Comment by wuruchi** [comment]
Hello @ikayz 

I wonder if there is anything else you need to continue with the review process.

Best regards.

**Comment by ikayz** [comment]
@wuruchi sorry I was caught up with something, I finished the review and tried the app with the implemented changes. It works, all the tests pass and I've checked everything the checklist mentioned. It's a well-written React app, good job. My test machine is a Windows 10 build and here by do confirm the app works.
![image](https://user-images.githubusercontent.com/31007212/111481950-1f6da900-873c-11eb-958e-062bd4eeaddc.png)

**Comment by wuruchi** [comment]
> @wuruchi sorry I was caught up with something, I finished the review and tried the app with the implemented changes. It works, all the tests pass and I've checked everything the checklist mentioned. It's a well-written React app, good job. My test machine is a Windows 10 build and here by do confirm the app works.

Hello @ikayz 

Thank you for your time and the compliments!

I guess it is now my turn to make a tagged release and upload it to get a DOI. I have taken these steps and as a result we have:

Autosubmit GUI uploaded as autosubmitreact-v1.0.0 (v1.0.0 is the current version).

The DOI is [https://doi.org/10.6084/m9.figshare.14230052.v1](https://doi.org/10.6084/m9.figshare.14230052.v1)

Is it Ok @arfon?

**Comment by ikayz** [comment]
It was an honour and a previlege to review it.

**Comment by arfon** [comment]
@whedon set 10.6084/m9.figshare.14230052.v1 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.6084/m9.figshare.14230052.v1" target="_blank">10.6084/m9.figshare.14230052.v1</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/HPCSim.2016.7568429 is OK
- 10.5194/gmd-10-19-2017 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2152

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2152, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by wuruchi** [comment]
Looks good to me.

@whedon accept deposit=true

**Comment by danielskatz** [comment]
@wuruchi - you can't do this - just the AEiC on duty can

**Comment by wuruchi** [comment]
@danielskatz Oh, sorry about it. 😬

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1372800041228722179) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2154
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.03049](https://doi.org/10.21105/joss.03049)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@djmitche, @ikayz - many thanks for your reviews here. JOSS relies upon the volunteer efforts of people l like you and we simply wouldn't be able to do this without you ✨ 

@wuruchi - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03049/status.svg)](https://doi.org/10.21105/joss.03049)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03049">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03049/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03049/status.svg
   :target: https://doi.org/10.21105/joss.03049
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03049/status.svg)](https://doi.org/10.21105/joss.03049)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by ikayz** [comment]
@arfon thanks to you for the opportunity and always happy to contribute to Open Source. Looking forward to future opportunities like these.
