### ISSUE TITLE
[PRE REVIEW]: TUM Open Infra Platform: an open source package for simultaneous viewing and analysis of digital models in the civil engineering domain

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3057]
**Submitting author:** @pjanck (<a href="http://orcid.org/0000-0003-0387-3440">Štefan Jaud</a>)
**Repository:** <a href="https://github.com/tumcms/Open-Infra-Platform" target ="_blank">https://github.com/tumcms/Open-Infra-Platform</a>
**Version:** [still a moving target]
**Editor:** @hugoledoux
**Reviewers:** @aothms, @CBenghi
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pjanck. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @hugoledoux.

@pjanck if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3057 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (889e735991ee1b12e583c41f/Documentation/joss/paper.md): did not find expected comment or line break while scanning a block scalar at line 6 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=21.88 s (72.4 files/s, 31524.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Expect                          20          18217              0         147227
C++                            528          34546          46141         125050
C/C++ Header                   465          21243          26775          96620
XSD                            105            113           1271          53205
C                               24           2796            664          17791
Qt                              32              0              0          10427
XML                             35             57             14          10223
Bourne Shell                     9            943           1628           9143
Qt Linguist                      3              0              0           8663
WiX source                       2           3392             30           7278
m4                              17           1141             71           7018
SVG                             33             30             30           6275
Python                          37           1997           2307           6137
MSBuild script                  18              0             14           3316
CMake                          105            792           1881           2312
HLSL                            15            536            279           1620
XSLT                             4            153             81           1582
yacc                             1            323             24           1290
Markdown                        18            449              0            996
HTML                             2             94            219            731
DOS Batch                       32             69             63            666
Java                             1            138            293            634
TeX                              4            116              1            478
make                            16            111             47            447
C#                              10             97             43            411
lex                              1             31             23            250
Qt Project                      32             90             16            234
ProGuard                         8             31             30             57
QML                              2             10              4             57
MATLAB                           1              5             13             24
JSON                             1              0              0             21
INI                              2              0              0              9
IDL                              1              0              0              1
-------------------------------------------------------------------------------
SUM:                          1584          87520          81962         520193
-------------------------------------------------------------------------------


Statistical information for the repository 'a90719215262fa405ffff895' was
gathered on 2021/02/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ana Sanchez                      1             4              0            0.00
Cara Coetzee                    45         75224          95039            4.76
Elvira Khromykh                 11           198            134            0.01
Fabian Schöttl                   7           919            274            0.03
Frédéric Gillioz                 2          2456            523            0.08
Hecht                            1             1              1            0.00
Helge Hecht                    310        367863        1759623           59.50
Jonas Schlenger                 43          1158            285            0.04
Julian Amann                    62       1165069           3021           32.67
Lena Fuchs                      28          4031           2585            0.19
Lucas Duckerschein               2           112             66            0.00
Markus Böckle                   12           460            710            0.03
Mauplatteau                     41          1449            777            0.06
Mauricio Platteau                1           389              0            0.01
Max Werner                       3           100             16            0.00
Rebecca Schill                  31         15013           2536            0.49
Samuils Rulovs                 209          9669           4825            0.41
SamuilsRulovs                    7            10             14            0.00
Stefan Jaud                    429         25919           9279            0.98
Stefan Markic                   77          3003           1489            0.13
ccoetzee                        65          8184           3132            0.32
christophKaiser                 49           882            658            0.04
hechth                          63          4620           4167            0.25

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ana Sanchez                   4          100.0         16.0                0.00
Cara Coetzee               7568           10.1         19.6               19.24
Elvira Khromykh              71           35.9          1.0               56.34
Fabian Schöttl              704           76.6         40.4               18.89
Frédéric Gillioz           1731           70.5         43.3               18.72
Hecht                         1          100.0         10.3                0.00
Helge Hecht               74038           20.1         27.9               29.57
Jonas Schlenger             876           75.6          1.5               26.26
Julian Amann             275581           23.7          0.3               18.39
Lena Fuchs                  922           22.9         31.4               37.85
Markus Böckle                76           16.5         20.5               10.53
Mauricio Platteau          1211          311.3          5.0               24.61
Rebecca Schill              144            1.0         17.6               65.28
Samuils Rulovs             6507           67.3          3.8               32.80
Stefan Jaud               23452           90.5          2.6               22.70
ccoetzee                   5517           67.4          5.3               58.02
christophKaiser             519           58.8          7.1               30.06
```

**Comment by kthyng** [comment]
@hugoledoux would you be able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @hugoledoux as editor

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by kthyng** [comment]
@pjanck Please take a look through the compilation errors above and see if you can address them.

**Comment by pjanck** [comment]
Hi @kthyng: I believe that whedon needs to compile the `joss_submission` branch. The version of the paper in the current main branch is not according to the specifications.

**Comment by pjanck** [comment]
@whedon generate pdf from branch joss_submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03057/joss.03057/10.21105.joss.03057.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03057/joss.03057/10.21105.joss.03057.pdf) :page_facing_up: :point_left:

**Comment by hugoledoux** [comment]
> @hugoledoux would you be able to edit this submission?

yes sure, on it.

**Comment by pjanck** [comment]
@whedon generate pdf from branch joss_submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03057/joss.03057/10.21105.joss.03057.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03057/joss.03057/10.21105.joss.03057.pdf) :page_facing_up: :point_left:

**Comment by hugoledoux** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by hugoledoux** [comment]
whedon assign @aothms as reviewer

**Comment by hugoledoux** [comment]
@whedon add @aothms as reviewer

**Comment by whedon** [comment]
OK, @aothms is now a reviewer

**Comment by hugoledoux** [comment]
@whedon add @CBenghi as reviewer

**Comment by whedon** [comment]
OK, @CBenghi is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3061.

**Comment by kthyng** [comment]
whoa @hugoledoux this was lightning fast! I'm impressed!!

**Comment by hugoledoux** [comment]
yeah I have a colleague who is perfect for this and he replied instantly, and my other request was answered within 1h too. 

This compensates for all the other times where I had to wait days (weeks?) for reviewers...
