### ISSUE TITLE
[PRE REVIEW]: Application to perform circular profiles of stack of radiographs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3059]
**Submitting author:** @jeanbilheux (<a href="http://orcid.org/0000-0003-2172-6487">Jean Bilheux</a>)
**Repository:** <a href="https://github.com/neutronimaging/circular_profiler" target ="_blank">https://github.com/neutronimaging/circular_profiler</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jeanbilheux. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @melissawm.

@jeanbilheux if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.40 s (64.8 files/s, 12159.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          16            510            181           1851
Qt                               1              0              0           1433
Markdown                         3             41              0            123
YAML                             2              7              1            112
CSS                              1             21             10             96
TeX                              1              4              0             45
Bourne Shell                     1              5              5             24
Jupyter Notebook                 1              0            397             13
-------------------------------------------------------------------------------
SUM:                            26            588            594           3697
-------------------------------------------------------------------------------


Statistical information for the repository '88c64fa51e3ee404266e2394' was
gathered on 2021/02/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
JeanBilheux                      4          2544              2          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
JeanBilheux                2542           99.9          0.0                5.35
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2011.37 is OK
- 10.21105/joss.00815 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- 10.25080/majora-92bf1922-00a may be a valid DOI for title:  Data Structures for Statistical Computing in Python 

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03059/joss.03059/10.21105.joss.03059.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03059/joss.03059/10.21105.joss.03059.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@JeanBilheux  Thank you for your submission. Please take a look through our [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html) and [submission criteria](https://joss.readthedocs.io/en/latest/submitting.html). I'm having a hard time telling if your submission is appropriate for JOSS because many of the necessary submission and elements reviewers will check for are missing. 

Do you have any questions? I suspect that withdrawing this submission and resubmitting after you've had a chance to modify your software would be the best path forward.

**Comment by arfon** [comment]
@whedon reject

Rejecting this due to lack of activity.

**Comment by whedon** [comment]
Paper rejected.

**Comment by bidochon** [comment]
I did reject that paper and submitted another one https://github.com/openjournals/joss-reviews/issues/3183
