### ISSUE TITLE
[PRE REVIEW]: StatSailr: Reproducible and Easy Statistics Environment with StatSailr Script

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3063]
**Submitting author:** @niceume (<a href="http://orcid.org/0000-0001-7015-621X">Toshihiro Umehara</a>)
**Repository:** <a href="https://github.com/niceume/statsailr/" target ="_blank">https://github.com/niceume/statsailr/</a>
**Version:** v0.7.2
**Editor:** @fboehm
**Reviewers:** @g4brielvs, @Nachootal
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @niceume. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @mjsottile.

@niceume if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (191.2 files/s, 21153.1 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Ruby                             26            413             99           2490
Markdown                          2             99              0            204
YAML                              1              0              0              6
Bourne Again Shell                1              2              1              5
--------------------------------------------------------------------------------
SUM:                             30            514            100           2705
--------------------------------------------------------------------------------


Statistical information for the repository '17e7aad7110264d58cef2725' was
gathered on 2021/02/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
niceume                         15          3265            448          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
niceume                    2817           86.3          0.2                2.95
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3063 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@whedon generate pdf from branch joss_submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3063 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/JuliaCon/proceedings-review/issues/3063: 404 - Not Found // See: https://docs.github.com/rest/reference/issues#get-an-issue (Octokit::NotFound)
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /app/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	from /app/vendor/bundle/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/connection.rb:156:in `request'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/connection.rb:19:in `get'
	from /app/vendor/bundle/ruby/2.6.0/gems/octokit-4.8.0/lib/octokit/client/issues.rb:114:in `issue'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/review.rb:21:in `issue_body'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:44:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by kthyng** [comment]
@arfon Did something get messed up in here? I see a "juliacon" in the error dump above.

**Comment by kthyng** [comment]
@whedon generate pdf from branch joss_submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03063/joss.03063/10.21105.joss.03063.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03063/joss.03063/10.21105.joss.03063.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @niceume and thanks for your submission! I want to be sure about the fit of your package within the scope of JOSS, so I am going to ping the editorial board to take a look with the scope query label. Someone will get back to you after this in a week or two.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by niceume** [comment]
@kthyng  Thank you very much for consideration!

**Comment by arfon** [comment]
> @arfon Did something get messed up in here? I see a "juliacon" in the error dump above.

Lemme dig into this. I think there's some kind of issue on the Whedon bot server side.

**Comment by arfon** [comment]
@niceume - this looks like a useful Ruby library. After a quick inspection of the code, it looks like there aren't any automated tests or testing procedures here to verify the functionality of the software? The JOSS review [includes specific criteria for verifying the testing approach](https://joss.readthedocs.io/en/latest/review_criteria.html#tests) - could you explain how you would expect a reviewer to test your software?

**Comment by niceume** [comment]
@arfon Thank you for having a look at my Ruby program. This gem installs CLI programs called sailr and sailrREPL. Actually, how to test is not mentioned, but I would like reviewers to run examples described in README. 

This gem requires some setups to run. If Docker is allowed, please have a look at the bottom of this page. https://statsailr.io/install/install.html
Also, how it works can be seen here. https://statsailr.io/demo/demo.html

**Comment by danielskatz** [comment]
@niceume - you need to have some instructions about testing in your documentation, even if the testing is manual.

**Comment by danielskatz** [comment]
This has passed the scope review, but I'm going to mark it as paused until the testing part is done. @niceume - please let us know when this is, and we will resume the process

**Comment by niceume** [comment]
@danielskatz - I am sorry for being late. I needed to take time for my family. Testing part is now added, and it can be done with docker.

**Comment by kyleniemeyer** [comment]
@whedon invite @lorenanicole as editor

Hi @lorenanicole, could you edit this one?

**Comment by whedon** [comment]
@lorenanicole has been invited to edit this submission.

**Comment by arfon** [comment]
I'm pretty sure @lorenanicole is currently unable to take on an additional paper so I'm going to make this submission as waitlisted for now.

@niceume - it may be a little while before an editor is assigned to your paper sorry. We have a backlog of submissions right now I'm afraid.

**Comment by niceume** [comment]
@arfon @lorenanicole - I understand. I will wait until you have time to review. Thank you.

**Comment by niceume** [comment]
@arfon - Assigned editor seems to be busy now. Can I ask another editor for reviewing? This Ruby program converts StatSailr script into R's internal expression and executes it. I see the reviewer list, and I would like to ask lutzhamel to review it.

**Comment by arfon** [comment]
> I'm pretty sure `@lorenanicole` is currently unable to take on an additional paper so I'm going to make this submission as waitlisted for now.

@niceume - as per my comment two weeks ago, your submission is currently waitlisted (there is no editor assigned currently to handle it). Once an editor is assigned, they will then start the process of identifying reviewers.

JOSS is very busy right now. Thanks for your patience.

**Comment by danielskatz** [comment]
@fboehm - is there any chance you could take this on as well?  It's related, but Ruby.  It would be useful for the same editor to handle both if possible

**Comment by danielskatz** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by fboehm** [comment]
Yes, I am happy to take this on, too, @danielskatz.

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by fboehm** [comment]
@whedon assign @g4brielvs as reviewer

**Comment by whedon** [comment]
OK, @g4brielvs is now a reviewer

**Comment by fboehm** [comment]
@g4brielvs - I'm still seeking a second reviewer. Once we find one, we can begin the official review.

**Comment by fboehm** [comment]
@whedon add @Nachootal as reviewer

**Comment by whedon** [comment]
OK, @Nachootal is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3170.
