### ISSUE TITLE
[PRE REVIEW]: MUQ: The MIT Uncertainty Quantification Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3070]
**Submitting author:** @mparno (<a href="http://orcid.org/0000-0002-9419-2693">Matthew Parno</a>)
**Repository:** <a href="https://bitbucket.org/mituq/muq2.git" target ="_blank">https://bitbucket.org/mituq/muq2.git</a>
**Version:** v0.3.2
**Editor:** @pdebuyl
**Reviewers:** @martinmodrak
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mparno. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jedbrown.

@mparno if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.14 s (465.2 files/s, 80289.4 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
C/C++ Header                    366          12654          19594          49204
C++                             353          11682           6172          37366
Python                           76           2494           1609           7464
CMake                           108           1206            813           4382
reStructuredText                 32           2450           2778           4153
SVG                               3              0              0           1186
D                                 1              0              0            961
Jupyter Notebook                  8              0           2901            807
YAML                             23             41             30            557
TeX                               3             45              0            304
Markdown                          8             73              0            277
XML                               1              5              7            170
Dockerfile                        4             28             14             91
Bourne Shell                      3             32             19             69
HTML                              1              3             16             46
INI                               1              0              0             19
CSS                               1              0              0             11
TOML                              2              0              0              6
Bourne Again Shell                1              0              0              2
--------------------------------------------------------------------------------
SUM:                            995          30713          33953         107075
--------------------------------------------------------------------------------


Statistical information for the repository 'edbdfb78894a540a3be120d8' was
gathered on 2021/02/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alexandra Datz                   3            77             20            0.03
Andrew                          85         13805           8030            7.40
Andrew Davis                   108         19392           8923            9.59
Andy Davis                      15          1536            430            0.67
Arnold Song                     15          1984           2350            1.47
Brendan West                    15          1699            165            0.63
Devin O'Connor                  13           963            254            0.41
Hodgdon, Taylor S ER             8           828             97            0.31
Josephine Westermann             5           179             84            0.09
Ki-Tae Kim                       2             8              2            0.00
Linus Seelinger                116         26050          17873           14.88
Matt                            25          3778            568            1.47
Matt Parno                      11          2169            443            0.89
Matthew Parno                  383         97268          32459           43.96
Max Liu                          1             1              0            0.00
andyddavis                       1            53              6            0.02
cassielumbrazo                   3            92             42            0.05
davisad                         66         49707           3611           18.07
vagrant                          1           156              0            0.05

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alexandra Datz               69           89.6          4.3                0.00
Andrew                     6323           45.8         45.0               24.92
Andrew Davis               8626           44.5         36.4               17.12
Arnold Song                1003           50.6         31.6               34.20
Brendan West                370           21.8         35.5               51.62
Devin O'Connor              628           65.2         33.6                7.32
Hodgdon, Taylor S ER        533           64.4         32.6                1.13
Josephine Westermann        179          100.0          3.4               29.61
Ki-Tae Kim                    8          100.0          8.2                0.00
Linus Seelinger            6133           23.5         18.0               10.19
Matt Parno                  293           13.5         47.6               14.33
Matthew Parno             75037           77.1         30.3               16.52
Max Liu                       1          100.0         18.7                0.00
andyddavis                   53          100.0         11.1               16.98
cassielumbrazo               63           68.5         42.4               22.22
davisad                   48920           98.4         49.7               23.33
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/130915005 is OK
- 10.1137/19M126966X is OK
- 10.1287/opre.1070.0496 is OK

MISSING DOIs

- 10.1016/j.jcp.2015.10.008 may be a valid DOI for title: Dimension-independent likelihood-informed MCMC
- 10.1214/13-sts421 may be a valid DOI for title: MCMC methods for functions: modifying old algorithms to make them faster
- 10.1615/int.j.uncertaintyquantification.2019027384 may be a valid DOI for title: Embedded model error representation for Bayesian model calibration
- 10.1137/140964023 may be a valid DOI for title: Randomize-then-optimize: A method for sampling from posterior distributions in nonlinear inverse problems
- 10.1137/120890715 may be a valid DOI for title: Adaptive Smolyak pseudospectral approximations
- 10.1137/16m1084080 may be a valid DOI for title: Parallel local approximation MCMC for expensive models
- 10.1137/17m1134640 may be a valid DOI for title: Transport map accelerated Markov chain Monte Carlo

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03070/joss.03070/10.21105.joss.03070.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03070/joss.03070/10.21105.joss.03070.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @mparno and thanks for your submission. One thing I notice in your paper: can you update the affiliations to include all the normal information like institution, city, country.

**Comment by mparno** [comment]
> Hi @mparno and thanks for your submission. One thing I notice in your paper: can you update the affiliations to include all the normal information like institution, city, country.

Will do!

**Comment by mparno** [comment]
@kthyng The affiliations have been updated in the `master` branch of our repo.  Do I need to make the changes anywhere else?   Thanks for your help!

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03070/joss.03070/10.21105.joss.03070.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03070/joss.03070/10.21105.joss.03070.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @pdebuyl! Would you be up for editing this submission?

**Comment by kthyng** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@georgiastuart would you review the article "MUQ: The MIT Uncertainty Quantification Library" for the Journal of Open Source Software ?

**Comment by pdebuyl** [comment]
Hi @georgiastuart thanks for your prompt reply :-)

We have a conflict of interest policy here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy . It does not seem that your case applies though, thank you for the notice.

**Comment by georgiastuart** [comment]
Great! Yes, I have not collaborated with the authors or anything like that.

**Comment by pdebuyl** [comment]
@martinmodrak would you review the article "MUQ: The MIT Uncertainty Quantification Library" for the Journal of Open Source Software ?

**Comment by martinmodrak** [comment]
Wow, this looks like a huge piece of software, additionally, parts of it are very much not my expertise (polynomial chaos) and my experience with Python is very limited. I however don't doubt this is useful. So if it is OK for me to review only part of the software (MCMC and the Bayesian "stuff", with focus on the C++ interface), then I think I could have a review in few weeks. I unfortunately don't have neither the expertise nor time available for a review of the software as a whole.

**Comment by pdebuyl** [comment]
Thank you for the quick reply @martinmodrak :-)

Indeed, the codebase is large. You can focus on the C++ part. @georgiastuart you listed Python in the "preferred programming languages", so that we could split the focus on the two APIs for both of you. There are examples in both languages.

If necessary I'll request a third reviewer but I propose to start the review already.

**Comment by pdebuyl** [comment]
@whedon add @martinmodrak as reviewer

**Comment by whedon** [comment]
OK, @martinmodrak is now a reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3076.
