### ISSUE TITLE
[PRE REVIEW]: FitBenchmarking: an open source Python package comparing data fitting software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3080]
**Submitting author:** @tyronerees (<a href="http://orcid.org/0000-0003-0476-2259">Tyrone Rees</a>)
**Repository:** <a href="https://github.com/fitbenchmarking/fitbenchmarking" target ="_blank">https://github.com/fitbenchmarking/fitbenchmarking</a>
**Version:** v 0.1.0
**Editor:** @dhhagan
**Reviewers:** @johnsamuelwrites, @djmitche
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tyronerees. **Currently, there isn't an JOSS editor assigned** to your paper.

@tyronerees if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10589-014-9687-3 is OK
- 10.5281/zenodo.3930098 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.11 s (85.9 files/s, 11910.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          86           2248           4211           6920
CSS                              4             25             42           4831
SVG                              1              0              0           2671
reStructuredText                43            820            428           1463
HTML                             8              2              0            383
Markdown                        10             55              0            154
Bourne Shell                    10             48             39            148
YAML                             2             12              0            147
JSON                             7              0              0             87
TeX                              1             10              0             74
Dockerfile                       2             36             25             73
INI                              3             22              0             50
DOS Batch                        1              8              1             27
make                             1              4              6             10
XML                              1              0              0              6
JavaScript                       1              0              0              1
-------------------------------------------------------------------------------
SUM:                           181           3290           4752          17045
-------------------------------------------------------------------------------


Statistical information for the repository '3240b89e0a5a8446fce78b9d' was
gathered on 2021/03/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Anders Markvardsen              56          1732           8905            5.39
Anders-Markvardsen              34           496           1120            0.82
Andrew Lister                  252          9592          48899           29.65
Andrew McCluskey                10           297            468            0.39
AndrewLister-STFC                2             2              2            0.00
Anthony Lim                     19           723            339            0.54
Anton Piccardo-Selg              2             6              3            0.00
Atom Anuchitanukul              15             2             28            0.02
AtomAnu                        121         50466           2162           26.68
Federico Montesino P            24          1895            616            1.27
Karl Palmen                      1           434             14            0.23
Michael Wathen                 469         17191          13207           15.41
Patrick                         81          2755           1845            2.33
Patrick Odagiu                 200         15356          10962           13.34
Pete Peterson                    1             2              2            0.00
Roman Tolchenov                  3             3              3            0.00
Ross Whitfield                   1            26             12            0.02
Simon Fernandes                 32           222            136            0.18
TOFarmer                         7           143             99            0.12
Tom Perkins                      1             1              1            0.00
Tyrone Rees                    117          1504            558            1.05
bb511                           68          3284           1743            2.55

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Anders-Markvardsen          143           28.8         11.9               17.48
Andrew Lister              4293           44.8         13.7               15.16
Andrew McCluskey              9            3.0         15.2                0.00
Anthony Lim                   2            0.3         42.9                0.00
Anton Piccardo-Selg           1           16.7         48.5                0.00
AtomAnu                      55            0.1         19.4                7.27
Michael Wathen             7786           45.3          8.3               14.10
Patrick                       2            0.1         30.9              100.00
Patrick Odagiu               81            0.5         30.6               20.99
Ross Whitfield                1            3.8         48.4                0.00
TOFarmer                     38           26.6         15.2                7.89
Tyrone Rees                 885           58.8          9.3               13.90
bb511                        84            2.6         26.2               11.90
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03080/joss.03080/10.21105.joss.03080.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03080/joss.03080/10.21105.joss.03080.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @dhhagan - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @dhhagan as editor

**Comment by whedon** [comment]
@dhhagan has been invited to edit this submission.

**Comment by dhhagan** [comment]
@danielskatz yup. Will do.

**Comment by dhhagan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by dhhagan** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by dhhagan** [comment]
Hi there @tyronerees - It appears that there are a few items missing from the [review items](https://joss.readthedocs.io/en/latest/review_criteria.html#review-items) list that JOSS requires/recommends. Specifically, I don't see any installation instructions, API documentation, example usage, community guidelines, or automated tests. It is possible that I am just not seeing them, in which case, please point me in their direction! It would also be helpful to list those resources directly in the Readme file which is the first thing users often look at. 

Please let me know if you have any questions.

**Comment by tyronerees** [comment]
Hi @dhhagan -- thanks for handling this submission.  

**installation instructions** are at https://fitbenchmarking.readthedocs.io/en/latest/users/install_instructions/index.html
**API documentation, example usage**  Users interact with FitBenchmarking via a CLI, not API.  Basic details of how it is run are found at https://fitbenchmarking.readthedocs.io/en/latest/users/running.html (with the options being fully explored in the rest of the Users section https://fitbenchmarking.readthedocs.io/en/latest/users/index.html)
**community guidelines** are at https://fitbenchmarking.readthedocs.io/en/latest/contributors/guidelines.html
**automated tests** are run via GitHub Actions, https://github.com/fitbenchmarking/fitbenchmarking/actions, and the tests are documented at https://fitbenchmarking.readthedocs.io/en/latest/users/tests.html 

I'll open an issue to point to these from the README.  Please let me know if you need any further information.

**Comment by danielskatz** [comment]
@dhhagan - can you explain why you started a scope query?  I was expecting you to assign yourself as editor.

**Comment by dhhagan** [comment]
@whedon assign @dhhagan as editor

**Comment by whedon** [comment]
OK, the editor is @dhhagan

**Comment by danielskatz** [comment]
I'm going to remove the scope query - let me know if you think this is needed

**Comment by dhhagan** [comment]
Hi @tyronerees thanks for pointing those out. When those are merged into the main readme, please let me know and I'll go ahead and proceed to find reviewers.

**Comment by tyronerees** [comment]
Hi @dhhagan -- the readme is now updated to include links to the relevant sections.

**Comment by dhhagan** [comment]
:wave:  @ziotom78, @diehlpk, @AmirHoseinHadian, & @johnsamualwrites, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by ziotom78** [comment]
Hi @dhhagan, thanks for having contacted me. Unfortunately I am going to be really busy in the next few weeks, and I am probably not going to have enough time to do the review.

**Comment by diehlpk** [comment]
@dhhagan thanks for asking, however, I can not do any review since I am editing several papers.

**Comment by dhhagan** [comment]
@ziotom78 and @diehlpk thanks for the quick response. I'm going to re-tag @johnsamuelwrites who I believe I misspelled previously...

**Comment by johnsamuelwrites** [comment]
@dhhagan Thanks for the invitation. I will be able to review this.

**Comment by dhhagan** [comment]
@johnsamuelwrites great!

**Comment by dhhagan** [comment]
@whedon add @johnsamuelwrites as reviewer

**Comment by whedon** [comment]
OK, @johnsamuelwrites is now a reviewer

**Comment by dhhagan** [comment]
👋 @djmitche, @trallard, @Chilipp would one of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by djmitche** [comment]
I'm willing.

**Comment by Chilipp** [comment]
My apologies but I won't be available

**Comment by dhhagan** [comment]
Hi @djmitche thanks so much. I'll add you and get the review started.

**Comment by dhhagan** [comment]
@whedon add @djmitche as reviewer

**Comment by whedon** [comment]
OK, @djmitche is now a reviewer

**Comment by dhhagan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3127.

**Comment by dhhagan** [comment]
@djmitche and @johnsamuelwrites Thank you for agreeing to review. The new review issue can be found in the comment above. I will now go ahead and close this pre-review issue. Please reach out to me with any questions.
