### ISSUE TITLE
[PRE REVIEW]: dataquieR: assessment of data quality in epidemiological research

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3081]
**Submitting author:** @struckma
**Repository:** <a href="https://gitlab.com/libreumg/dataquier.git" target ="_blank">https://gitlab.com/libreumg/dataquier.git</a>
**Version:** v1.0.5
**Editor:** @csoneson
**Reviewers:** @tgerke, @borishejblum
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @struckma. **Currently, there isn't an JOSS editor assigned** to your paper.

@struckma if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.34 s (164.8 files/s, 56599.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             24              0              0          55206
R                              184           1431           3685          14462
Rmd                              7            129            245            439
Markdown                         3             46              0            177
CSS                              1              1              0             37
YAML                             2              5              1             30
-------------------------------------------------------------------------------
SUM:                           221           1612           3931          70351
-------------------------------------------------------------------------------


Statistical information for the repository '3a439d5a0200839a5a893663' was
gathered on 2021/03/02.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3081 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03081/joss.03081/10.21105.joss.03081.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03081/joss.03081/10.21105.joss.03081.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch JOSS

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch JOSS
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- doi: 10.3205/mibe000202 is OK
- doi: 10.3205/mibe000203 is OK
- 10.21203/rs.3.rs-119457/v1 is OK
- 10.18637/jss.v067.i01 is OK
- 10.1038/sdata.2018.118 is OK

MISSING DOIs

- 10.1007/s10654-019-00500-x may be a valid DOI for title: Guidelines and recommendations for ensuring Good Epidemiological Practice (GEP): a guideline developed by the German Society for Epidemiology
- 10.1146/annurev-statistics-060116-054114 may be a valid DOI for title: The evolution of data quality: Understanding the transdisciplinary origins of data quality concepts and approaches
- 10.14301/llcs.v6i2.312 may be a valid DOI for title: The impact of attrition and non-response in birth cohort studies: a need to incorporate missingness strategies
- 10.18637/jss.v090.i06 may be a valid DOI for title: dataMaid: Your Assistant for Documenting Supervised Data Quality Screening in R
- 10.21105/joss.01509 may be a valid DOI for title: SmartEDA: An R Package for Automated Exploratory Data Analysis
- 10.32614/rj-2019-033 may be a valid DOI for title: The Landscape of R Packages for Automated Exploratory Data Analysis
- 10.13063/egems.1280 may be a valid DOI for title: A Data Quality Assessment Guideline for Electronic Health Record Data Reuse
- 10.18637/jss.v040.i03 may be a valid DOI for title: Dates and Times Made Easy with lubridate
- 10.18637/jss.v032.i03 may be a valid DOI for title: An Object-Oriented Framework for Robust Multivariate Analysis
- 10.5334/dsj-2015-002 may be a valid DOI for title: The challenges of data quality and data quality assessment in the big data era

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@openjournals/dev - I can't identify the submitter here, so I'm not sure how to proceed.

**Comment by xuanxu** [comment]
@danielskatz: Following the submitted ORCID info it looks like the submitter is Adrian Richter, ([Adrian_HGW in GitLab](https://gitlab.com/Adrian_HGW)), but I guess he needs to have a GitHub account too to participate here.

**Comment by danielskatz** [comment]
I've submitted https://gitlab.com/libreumg/dataquier/-/issues/3 to try to identify someone as the contact of this submission

**Comment by danielskatz** [comment]
I'm going to mark this as paused until this is resolved.

**Comment by struckma** [comment]
> I've submitted https://gitlab.com/libreumg/dataquier/-/issues/3 to try to identify someone as the contact of this submission

Dear @danielskatz, dear others,

you can use my github-account (@struckma) as contact for this issue.

Thank you.

**Comment by danielskatz** [comment]
@struckma - please go ahead and fix the references that whedon mentioned above, but note that whedon isn't always correct, so please confirm these before adding them. Once that is done, you can enter `@whedon check references from branch JOSS` as the first line of a new comment to run the check again.

**Comment by danielskatz** [comment]
Also, I notice in the paper that some things in the references aren't cased correctly.  You can use {}s around text to set and preserve the case (usually upper) during the processing.

**Comment by danielskatz** [comment]
👋 @csoneson - you were suggested as the editor - can you do this?

**Comment by danielskatz** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @struckma - I will handle your submission and start by looking for suitable reviewers. If you have any suggestions (e.g., from the list mentioned in the first comment above), please mention them here (without tagging them with `@`).

**Comment by struckma** [comment]
Dear Charlotte, 

thank you for being the editor. Indeed, we have some reviewer suggestions:

Darthpathos; masalmon; Tgerke

Thank you

**Comment by struckma** [comment]
Dear Charlotte, 

we’ve addressed all issues regarding the problems with DOIs in the references (see https://github.com/openjournals/joss-reviews/issues/3081#issuecomment-789889598). We also went through the references carefully and addressed the casing (see https://github.com/openjournals/joss-reviews/issues/3081#issuecomment-789892631).

**Comment by struckma** [comment]
@whedon check references from branch JOSS

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch JOSS
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v067.i01 is OK
- 10.5334/dsj-2015-002 is OK
- 10.18637/jss.v040.i03 is OK
- 10.13063/2327-9214.1244 is OK
- 10.1146/annurev-statistics-060116-054114 is OK
- 10.18637/jss.v090.i06 is OK
- 10.21105/joss.01509 is OK
- doi: 10.3205/mibe000202 is OK
- 10.21203/rs.3.rs-119457/v1 is OK
- 10.18637/jss.v032.i03 is OK
- 10.18637/jss.v021.i12 is OK
- 10.1038/sdata.2018.118 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03081/joss.03081/10.21105.joss.03081.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03081/joss.03081/10.21105.joss.03081.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
👋 @tgerke, @maelle - would you be interested in reviewing this submission for JOSS? 

> dataquieR: assessment of data quality in epidemiological research

**Comment by tgerke** [comment]
Sure, this looks interesting!

**Comment by csoneson** [comment]
Brilliant, thanks @tgerke! Once we have one more reviewer I will open the review issue.

**Comment by csoneson** [comment]
@borishejblum - would you be interested in reviewing this submission for JOSS? 

> dataquieR: assessment of data quality in epidemiological research

**Comment by borishejblum** [comment]
Hi @csoneson, yes I'd be happy to act as a reviewer for this submission.

**Comment by csoneson** [comment]
Great, thanks a lot @borishejblum!

**Comment by csoneson** [comment]
@whedon assign @tgerke as reviewer

**Comment by whedon** [comment]
OK, @tgerke is now a reviewer

**Comment by csoneson** [comment]
@whedon add @borishejblum as reviewer

**Comment by whedon** [comment]
OK, @borishejblum is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3093.
