### ISSUE TITLE
[PRE REVIEW]: R-Opitools – An Opinion Analytical Tool for Big Social Media Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3083]
**Submitting author:** @MAnalytics (<a href="http://orcid.org/0000-0002-9006-4934">Monsuru Adepeju</a>)
**Repository:** <a href="https://github.com/MAnalytics/opitools" target ="_blank">https://github.com/MAnalytics/opitools</a>
**Version:** v1.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @MAnalytics. **Currently, there isn't an JOSS editor assigned** to your paper.

@MAnalytics if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (225.8 files/s, 31706.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               15            289            717            747
HTML                             1             41              2            685
Markdown                         4             58              0            115
TeX                              2             15              0             95
Rmd                              1            130            249             86
-------------------------------------------------------------------------------
SUM:                            23            533            968           1728
-------------------------------------------------------------------------------


Statistical information for the repository 'd5cffa81b8dfe17c05ca89e4' was
gathered on 2021/03/03.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3083 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:154:in `block in check_orcids': undefined method `has_key?' for ["name", "Monsuru Adepeju"]:Array (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.3389/frobt.2018.00138 may be a valid DOI for title: Opinion mining from social media short texts: Does collective intelligence beat deep learning?
- 10.21105/joss.00764 may be a valid DOI for title: Sentiment Analysis of Twitter Data (saotd)
- 10.31235/osf.io/c32qh may be a valid DOI for title: An Analytical Framework for Measuring Inequality in the Public Opinions on Policing – Assessing the impacts of COVID-19 Pandemic using Twitter Data.

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@MAnalytics - the fact that this has been submitted to CRAN is a plus, not a problem.  However, there appear to be some missing DOIs in your references, and the paper does not build correctly.  Please fix the DOIs (if the suggestions are correct), and fix the paper (using the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)), and then make new comments here starting with `@whedon check references` to check the references or `@whedon generate pdf` to regenerate the paper.

**Comment by danielskatz** [comment]
Also, because of the relatively small size of the code, I'm going to mark it for the editors to discuss before we start a review process, in particular to decide if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
It should take about a week or a little more until you hear back about the scope.

**Comment by MAnalytics** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/frobt.2018.00138 is OK
- 10.21105/joss.00764 is OK
- 10.31235/osf.io/c32qh is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by MAnalytics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3083 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:154:in `block in check_orcids': undefined method `has_key?' for ["name", "Monsuru Adepeju"]:Array (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by MAnalytics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03083/joss.03083/10.21105.joss.03083.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03083/joss.03083/10.21105.joss.03083.pdf) :page_facing_up: :point_left:

**Comment by MAnalytics** [comment]
@danielskatz Thanks for the efforts.

1. References check now okay.
2. Pdf now compiles successfully.

**Comment by MAnalytics** [comment]
> Also, because of the relatively small size of the code, I'm going to mark it for the editors to discuss before we start a review process, in particular to decide if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.

Thank you for bringing up this issue. If I may address the factors that needed to be considered when judging a substantial effort (according to JOSS):

1. Age of software (is this a well-established software project) / length of commit history.

**Response:** This package includes several months of method development, under a different Github repository name: https://github.com/MAnalytics/Sentiment-analysis. However, a new repository https://github.com/MAnalytics/opitools is created after deciding the appropriate name for the package. 

2. Number of commits.
**Response:** Please see the above.

3. Number of authors.
**Response:** I developed the codes.

4. Total lines of code (LOC). Submissions under 1000 LOC will usually be flagged, those under 300 LOC will be desk rejected.
**Response:** Total number of lines in .R files only: 1,124 

5. Whether the software has already been cited in academic papers.

**Response:**: Yes. The associated article to the package (methodology) has now been accepted for publication in the Journal of Geographical Information System (to go online by the mid of this month). The pre-print of the article can be found here: https://osf.io/preprints/socarxiv/c32qh/ . 

6. Whether the software is sufficiently useful that it is likely to be cited by your peer group.

**Response:** Please, see the statement of need of the JOSS submission (also see the Introduction of the article: https://osf.io/preprints/socarxiv/c32qh/ )

I hope that I have been able to address the [substantial scholarly effort] concern appropriately.

Thanks,
MA.

**Comment by MAnalytics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03083/joss.03083/10.21105.joss.03083.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03083/joss.03083/10.21105.joss.03083.pdf) :page_facing_up: :point_left:

**Comment by MAnalytics** [comment]
@danielskatz The package is now available on CRAN! Please, check here: https://cran.r-project.org/web/packages/opitools/index.html (vignette title to be corrected shortly).

**Comment by MAnalytics** [comment]
@danielskatz @arfon It's been two weeks sir! Just checking to see what the outcome of the scope query is.

Btw. Please, check out the newly published article: https://www.scirp.org/journal/paperinformation.aspx?paperid=107836   which describes the methodologies behind the R package in detail; and also contains the proper citation of the R package. I hope that the editors will also put this into consideration in their decision.

**Comment by MAnalytics** [comment]
generate pdf

**Comment by MAnalytics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03083/joss.03083/10.21105.joss.03083.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03083/joss.03083/10.21105.joss.03083.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by MAnalytics** [comment]
Dear @kthyng ,

Thank you very much for the feedback, and I thank the editors for taking the time to assess the package. I will love to re-submit the package but I would like you to help clarify a part of your comments. Specifically this: 

"...so that the research part of the code was separate from the implementation code.". 

My question is, which one is favoured by the journal, the 'research part' or the 'implementation code'? Or any further clarification of this comment will be very helpful to me.

Thanks,
Monsuru.

**Comment by kthyng** [comment]
Hi @MAnalytics. I think the idea behind the comment is that specific code for your very particular research question might not be as generally useful to other people who might be interested in using your package, so the more the code is modularized or written so that people with different specific questions can also use your package, the more likely it is to be used. Hope that helps.

**Comment by MAnalytics** [comment]
> Hi @MAnalytics. I think the idea behind the comment is that specific code for your very particular research question might not be as generally useful to other people who might be interested in using your package, so the more the code is modularized or written so that people with different specific questions can also use your package, the more likely it is to be used. Hope that helps.

Hi @kthyng. Thanks so much for the clarification. That is very helpful! 

But if I re-submit the package, do I need to mention this issue, or everything will be re-considered afresh? Thanks.

**Comment by kthyng** [comment]
@MAnalytics Yes it would be best to connect back to this issue for context. Thanks.

**Comment by MAnalytics** [comment]
> @MAnalytics Yes it would be best to connect back to this issue for context. Thanks.

@kthyng Ok. Thank you very much.
