### ISSUE TITLE
[PRE REVIEW]: ppdiag: Diagnostic Tools for Temporal Point Processes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3085]
**Submitting author:** @OwenWard (<a href="http://orcid.org/0000-0002-9678-3542">Owen G. Ward</a>)
**Repository:** <a href="https://github.com/OwenWard/ppdiag" target ="_blank">https://github.com/OwenWard/ppdiag</a>
**Version:** v0.1.0
**Editor:** @mikldk
**Reviewers:** @alexpghayes, @wjakethompson
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @OwenWard. **Currently, there isn't an JOSS editor assigned** to your paper.

@OwenWard if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (529.7 files/s, 69515.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            48           2312            642           7235
R                               54            272            924           2407
CSS                              3             99             48            428
Rmd                              3            194            323            336
JavaScript                       5             65             37            277
Markdown                         3             58              0            222
YAML                             5             32              2            155
XML                              1              0              0             63
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                           123           3032           1977          11134
-------------------------------------------------------------------------------


Statistical information for the repository 'd0695cfab74a977ddfcf683f' was
gathered on 2021/03/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Owen Ward                        3           415              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Owen Ward                   415          100.0          0.0               10.36
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3085 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03085/joss.03085/10.21105.joss.03085.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03085/joss.03085/10.21105.joss.03085.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1162/08997660252741149 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @mikldk - you were suggested as the editor - are you able to take on one more submission?

**Comment by danielskatz** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@author - thank you for the submission.

1. I created issues at OwenWard/ppdiag#52 and OwenWard/ppdiag#53.
2. I see not all authors contributed with commits to the Github repo. Please confirm that the author list is accurate.
3. Do you have any suggestions for reviewers ([here](https://bit.ly/joss-reviewers) is a list of potential reviewers)?

**Comment by OwenWard** [comment]
@mikldk thanks for agreeing to be the editor, appreciate it!

1. Thanks for pointing these out. I'll fix them shortly.
2. The author list is accurate. All authors contributed, either before this project became a github repo or in substantial non code contributions.
3. Some names from that list that might be suitable are alexpghayes, trashbirdecology and  wjakethompson

**Comment by mikldk** [comment]
@alexpghayes, @trashbirdecology: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by alexpghayes** [comment]
I'm happy to review, although I'm pretty overwhelmed for the next week or so.

**Comment by mikldk** [comment]
@trashbirdecology: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@whedon assign @alexpghayes as reviewer

**Comment by whedon** [comment]
OK, @alexpghayes is now a reviewer

**Comment by mikldk** [comment]
@wjakethompson: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by trashbirdecology** [comment]
Sorry for the delay, @mikldk, but this is a little too out of my expertise. I would recommend reaching out to @natbprice who has yet to review.

**Comment by mikldk** [comment]
@trashbirdecology Thanks. I'll wait on @wjakethompson's reply before reaching out.

**Comment by wjakethompson** [comment]
Happy to review this one!

**Comment by mikldk** [comment]
@whedon add @wjakethompson as reviewer

**Comment by whedon** [comment]
OK, @wjakethompson is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3133.
