### ISSUE TITLE
[PRE REVIEW]: epipack: An infectious disease modeling package for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3086]
**Submitting author:** @benmaier (<a href="http://orcid.org/0000-0001-7414-8823">Benjamin F. Maier</a>)
**Repository:** <a href="https://github.com/benmaier/epipack" target ="_blank">https://github.com/benmaier/epipack</a>
**Version:** v0.1.1
**Editor:** @fboehm
**Reviewers:** @chrisvoncsefalvay, @esteinig
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @benmaier. **Currently, there isn't an JOSS editor assigned** to your paper.

@benmaier if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.32 s (59.6 files/s, 10657.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          85           3433           3717           8790
reStructuredText                34           1396           1934           1571
Markdown                         6            223              0            663
TeX                              1             18              0            246
make                             2             48              6            238
DOS Batch                        1             34              2            227
Jupyter Notebook                 2              0           2035             83
JSON                             3              0              0             10
Bourne Shell                     2              1              0              5
INI                              1              0              0              5
CSS                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                           138           5153           7694          11841
-------------------------------------------------------------------------------


Statistical information for the repository '99525284b8947d0d4d4fcb70' was
gathered on 2021/03/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ben F. Maier                    12           473             96            2.12
Benjamin Maier                 130         20924           5343           97.88

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ben F. Maier              15940         3370.0          5.7                7.67
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BF02464423 is OK
- 10.1021/j100540a008 is OK
- 10.1186/1471-2334-11-37 is OK
- 10.18637/jss.v084.i08 is OK
- 10.6084/m9.figshare.1164194 is OK
- 10.21105/joss.01731 is OK
- 10.1016/j.physrep.2020.07.005 is OK
- 10.1016/j.cpc.2019.02.008 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.18452/20950 is OK
- 10.1016/j.jtbi.2011.07.015 is OK
- 10.21105/joss.00565 is OK
- 10.1007/978-3-319-50806-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03086/joss.03086/10.21105.joss.03086.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03086/joss.03086/10.21105.joss.03086.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @fboehm - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@danielskatz - yes, I'm happy to take this one :)

**Comment by benmaier** [comment]
Thank you so much for the swift response, @danielskatz and @fboehm!

May I kindly suggest the following people as potential reviewers:

* Guillaume St-Onge
* Jean-Gabriel Young
* Antoine Allard
* Christian Vestergaard
* Joel C. Miller

**Comment by fboehm** [comment]
@benmaier - We greatly appreciate the suggested reviewers. Do you happen to have email addresses and github handles for them? If so, would you please email me - frederick.boehm@gmail.com - with the contact info for the suggested reviewers? Thanks again!!

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by fboehm** [comment]
@whedon add @chrisvoncsefalvay as reviewer

**Comment by whedon** [comment]
OK, @chrisvoncsefalvay is now a reviewer

**Comment by esteinig** [comment]
Happy to review this @fboehm

**Comment by fboehm** [comment]
@whedon add @esteinig as reviewer

**Comment by whedon** [comment]
OK, @esteinig is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3097.
