### ISSUE TITLE
[PRE REVIEW]: IFermi: A python library for Fermi surface generation and analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3087]
**Submitting author:** @utf (<a href="http://orcid.org/0000-0002-4486-3321">Alex Ganose</a>)
**Repository:** <a href="https://github.com/fermisurfaces/IFermi" target ="_blank">https://github.com/fermisurfaces/IFermi</a>
**Version:** v.0.2.1
**Editor:** @danielskatz
**Reviewers:** @arosen93, @lucydot
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @utf. **Currently, there isn't an JOSS editor assigned** to your paper.

@utf if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.48 s (27.7 files/s, 182121.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              0          40230
Python                          17            915           1283           2844
reStructuredText                 9            225            221            343
SVG                              6              0              6            277
Markdown                         2             56              0            150
YAML                             3             26              0            101
Jupyter Notebook                 1              0         222685             79
CSS                              1              1              2              6
HTML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            41           1223         224197          44033
-------------------------------------------------------------------------------


Statistical information for the repository '8effa3af958294274f00d21f' was
gathered on 2021/03/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex Ganose                    153          8395          18247           39.43
Amy                              3          1035            438            2.18
Amy Jade Searle                  8         25777            771           39.29
Amy Searle                      15           852            399            1.85
Katherine Inzani                 1             1              0            0.00
Matthew Horton                   8           106              9            0.17
ajsearle97                      10           136          11403           17.08

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alex Ganose                4770           56.8          2.2                9.20
Amy                           5            0.5         18.3                0.00
Amy Jade Searle              97            0.4         15.8                9.28
Amy Searle                  105           12.3          0.2                7.62
Matthew Horton               60           56.6          5.7               20.00
ajsearle97                    5            3.7          8.8                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3087 with the following error: 

 Can't find any papers to compile :-(

**Comment by utf** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3087 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Amy Searle, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by utf** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03087/joss.03087/10.21105.joss.03087.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03087/joss.03087/10.21105.joss.03087.pdf) :page_facing_up: :point_left:

**Comment by utf** [comment]
Suggested reviewers:

lucydot
arosen93

**Comment by danielskatz** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/10867651.2003.10487582 is OK
- 10.1088/0031-8949/91/5/053009 is OK
- 10.1088/0370-1328/80/2/316 is OK
- 10.1103/PhysRevResearch.3.013069 is OK
- 10.1103/PhysRevApplied.14.024064 is OK
- 10.1016/j.cpc.2019.107080 is OK
- 10.1016/j.cpc.2019.01.017 is OK
- 10.1016/j.cpc.2018.05.010 is OK
- 10.1088/0953-8984/14/11/301 is OK
- 10.1088/1361-648X/ab4007 is OK
- 10.1109/MCSE.2011.35 is OK
- 10.7717/peerj.453 is OK

MISSING DOIs

- 10.1016/j.commatsci.2012.10.028 may be a valid DOI for title: Python Materials Genomics (pymatgen): A robust, open-source Python library for materials analysis
- 10.1016/s1093-3263(99)00028-5 may be a valid DOI for title: XCrySDen—a new program for displaying crystalline structures and electron densities
- 10.1109/mcse.2007.55 may be a valid DOI for title: Matplotlib: A 2D graphics environment

INVALID DOIs

- None
```

**Comment by utf** [comment]
@whedon check references from branch paper

@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/10867651.2003.10487582 is OK
- 10.1016/j.commatsci.2012.10.028 is OK
- 10.1016/s1093-3263(99)00028-5 is OK
- 10.1109/mcse.2007.55 is OK
- 10.1088/0031-8949/91/5/053009 is OK
- 10.1088/0370-1328/80/2/316 is OK
- 10.1103/PhysRevResearch.3.013069 is OK
- 10.1103/PhysRevApplied.14.024064 is OK
- 10.1016/j.cpc.2019.107080 is OK
- 10.1016/j.cpc.2019.01.017 is OK
- 10.1016/j.cpc.2018.05.010 is OK
- 10.1088/0953-8984/14/11/301 is OK
- 10.1088/1361-648X/ab4007 is OK
- 10.1109/MCSE.2011.35 is OK
- 10.7717/peerj.453 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by utf** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03087/joss.03087/10.21105.joss.03087.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03087/joss.03087/10.21105.joss.03087.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@utf - I'll be working with you on this submission.  A few more potential reviewer suggestions would be welcome, too.

**Comment by danielskatz** [comment]
👋 @lucydot & @arosen93 - Would you be willing to review this submission for JOSS?

**Comment by utf** [comment]
@danielskatz - great! A few more potential reviewers are:

- dandavies99
- bocklund
- Evan1415
- raghurama123
-

**Comment by arosen93** [comment]
@danielskatz, I would be happy to review this submission for JOSS. For full disclosure, while I have significant experience with electronic structure calculations, I have personally not generated Fermi surfaces before (although have been interested in doing so!). In this regard, I would be providing a review from the perspective of a new user interested in generating/analyzing Fermi surfaces for the first time. If this is not preferred, don't hesitate to let me know.

**Comment by danielskatz** [comment]
Thanks @arosen93 - that's fine. I'll add you as a reviewer, and see if we can find another reviewer with more Fermi surface experience before we start the review

**Comment by danielskatz** [comment]
@whedon assign @arosen93 as reviewer

**Comment by whedon** [comment]
OK, @arosen93 is now a reviewer

**Comment by lucydot** [comment]
Hi @danielskatz I'm happy to review. I'm in the same situation as the other reviewer - I haven't generated Fermi surfaces before. Though I know enough textbook physics about Fermi surfaces that I think I should be able to give it an educated whirl.

**Comment by danielskatz** [comment]
Thanks @lucydot - given what you say, let's go ahead and see how it goes.  If we find problems in the review, we can bring in someone else at that point

**Comment by danielskatz** [comment]
@whedon add @lucydot as reviewer

**Comment by whedon** [comment]
OK, @lucydot is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3089.
