### ISSUE TITLE
[REVIEW]: IFermi: A python library for Fermi surface generation and analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3089]
**Submitting author:** @utf (<a href="http://orcid.org/0000-0002-4486-3321">Alex Ganose</a>)
**Repository:** <a href="https://github.com/fermisurfaces/IFermi" target ="_blank">https://github.com/fermisurfaces/IFermi</a>
**Version:**  v0.2.3
**Editor:** @danielskatz
**Reviewer:** @arosen93, @lucydot
**Archive:** <a href="https://doi.org/10.5281/zenodo.4609270" target="_blank">10.5281/zenodo.4609270</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/59fa1c336b832a772f30b85bfbc2efdc/status.svg)](https://joss.theoj.org/papers/59fa1c336b832a772f30b85bfbc2efdc)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/59fa1c336b832a772f30b85bfbc2efdc"><img src="https://joss.theoj.org/papers/59fa1c336b832a772f30b85bfbc2efdc/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/59fa1c336b832a772f30b85bfbc2efdc/status.svg)](https://joss.theoj.org/papers/59fa1c336b832a772f30b85bfbc2efdc)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fermisurfaces/IFermi" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arosen93 & @lucydot, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fermisurfaces/IFermi">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@utf) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fermisurfaces/IFermi">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@utf) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arosen93, @lucydot it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.67 s (61.2 files/s, 402029.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              0          40230
Python                          17            915           1283           2844
reStructuredText                 9            225            221            343
SVG                              6              0              6            277
Markdown                         2             56              0            150
YAML                             3             26              0            106
Jupyter Notebook                 1              0         222685             79
CSS                              1              1              2              6
HTML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            41           1223         224197          44038
-------------------------------------------------------------------------------


Statistical information for the repository 'f4e3be367a80be13694bfb85' was
gathered on 2021/03/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex Ganose                    153          8395          18247           39.43
Amy                              3          1035            438            2.18
Amy Jade Searle                  8         25777            771           39.29
Amy Searle                      15           852            399            1.85
Katherine Inzani                 1             1              0            0.00
Matthew Horton                   8           106              9            0.17
ajsearle97                      10           136          11403           17.08

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alex Ganose                4770           56.8          2.2                9.20
Amy                           5            0.5         18.3                0.00
Amy Jade Searle              97            0.4         15.8                9.28
Amy Searle                  105           12.3          0.2                7.62
Matthew Horton               60           56.6          5.7               20.00
ajsearle97                    5            3.7          8.8                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3089 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@arosen93 and @lucydot - Thanks for agreeing to review this submission.
This is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

Please read the first couple of comments in this issue carefully, so that you can accept the invitation from JOSS and be able to check items, and so that you don't get overwhelmed with notifications from other activities in JOSS.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention openjournals/joss-reviews#3040 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@danielskatz) if you have any questions/concerns.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03089/joss.03089/10.21105.joss.03089.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03089/joss.03089/10.21105.joss.03089.pdf) :page_facing_up: :point_left:

**Comment by arosen93** [comment]
Fantastic. I plan to start my review towards the latter half of next week. Looking forward to learning about IFermi!

**Comment by arosen93** [comment]
@utf: I just read through the paper. It is clearly written, has a nice introduction to the importance of Fermi surfaces, discusses prior software in this area, and makes it clear where IFermi fits within the existing software ecosystem. As such, I have no major suggestions for changes to the text.

I only have a couple very trivial comments on the paper, unrelated to the software or science underlying the work.
- In the Summary: "IFermi is Python library..." --> "IFermi is a Python library..."
- The "author" for the Plotly citation got a bit truncated (Plotly Technologies Inc. --> Inc., P.T.).

**Comment by utf** [comment]
Thanks for catching those errors @arosen93. I've updated the manuscript accordingly.

@whedon generate pdf from branch paper

**Comment by utf** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by arosen93** [comment]
I have concluded my review of IFermi. In short, IFermi is an excellent software package that I believe should be published in JOSS.

Overall, I am incredibly pleased with the detailed documentation, easy-to-follow tutorials, and accessible code layout. I believe that this will become the de facto tool for generating and analyzing Fermi surfaces for VASP users (and hopefully users of other codes once these features are added). I raised a few minor issues on the GitHub page, mainly with regards to the documentation, that have all been addressed to my satisfaction.

With regards to the accompanying paper, it clearly explains the purpose of IFermi. For comparison's sake, I tried out what I feel to be one of the closest packages to IFermi, PyProcar, to compare the two codes. Like IFermi, PyProcar has its own features for visualizing Fermi surface and allows for surface coloring based on properties. While there are many similarities, I came away from this exercise feeling that IFermi is still an important contribution to the field. As the authors aptly note in the accompanying manuscript, it is quite easy to analyze and modify the Fermi surfaces once generated with IFermi (since it's stored as a very convenient Python object). This was a clear advantage to me. The claim of novelty regarding the dimensionality determination is also accurate to the best of my knowledge. All in all, I agree with the statement of need and advertised features of IFermi.

Thank you for the opportunity to review IFermi. I am happy to recommend its acceptance in JOSS.

**Comment by lucydot** [comment]
@danielskatz I'm in the process of working through the tutorials for my own dataset - I'll report back later today. All good so far!

**Comment by lucydot** [comment]
@danielskatz @utf 

I finished reviewing iFermi today. I ran through the tutorial using my own dataset, so that I could compare it to the corresponding bandstructure that I have generated elsewhere. The iFermi output is consistent with what I'd expect looking at my 2D slice through reciprocal space.

To re-iterate what Andrew has already said, iFermi has easy to follow, comprehensive documentation. The CLI is intuitive to use, and installation is straight forward. There are similarities with existing packages, but these are highlighted in the JOSS paper, and the flexibility of iFermi distinguishes itself from what is already out there.

Last week I raised some minor issues regarding documentation, testing and installation. All of these have been addressed are now closed.

I'm happy to recommend iFermi for publication with JOSS. Thanks @utf @ajsearle97 for the code I'm looking forward to using it for future research

**Comment by danielskatz** [comment]
Thanks @lucydot!

**Comment by danielskatz** [comment]
@utf - since both reviewers are happy, have checked off all items, and all the issues raised are closed, I think we're ready to proceed in the acceptance process.  At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

**Comment by utf** [comment]
Hi @danielskatz

The archived version is v0.2.3
The zenodo doi is [10.5281/zenodo.4609270](https://zenodo.org/record/4609271)

I can confirm that I have checked the zenodo metadata.

Thanks you @lucydot and @arosen93 for the swift reviews. The package is definitely improved after your comments.

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.4609270 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4609270" target="_blank">10.5281/zenodo.4609270</a> is the archive.

**Comment by danielskatz** [comment]
@whedon set  v0.2.3 as version

**Comment by whedon** [comment]
OK.  v0.2.3 is the version.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03089/joss.03089/10.21105.joss.03089.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03089/joss.03089/10.21105.joss.03089.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@utf - this looks good, except for one minor issue that I've proposed a change for in https://github.com/fermisurfaces/IFermi/pull/24

**Comment by utf** [comment]
Thanks @danielskatz. I've merged your PR.

**Comment by utf** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03089/joss.03089/10.21105.joss.03089.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03089/joss.03089/10.21105.joss.03089.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon accept from branch paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/10867651.2003.10487582 is OK
- 10.1016/j.commatsci.2012.10.028 is OK
- 10.1016/s1093-3263(99)00028-5 is OK
- 10.1109/mcse.2007.55 is OK
- 10.1088/0031-8949/91/5/053009 is OK
- 10.1088/0370-1328/80/2/316 is OK
- 10.1103/PhysRevResearch.3.013069 is OK
- 10.1103/PhysRevApplied.14.024064 is OK
- 10.1016/j.cpc.2019.107080 is OK
- 10.1016/j.cpc.2019.01.017 is OK
- 10.1016/j.cpc.2018.05.010 is OK
- 10.1088/0953-8984/14/11/301 is OK
- 10.1088/1361-648X/ab4007 is OK
- 10.1109/MCSE.2011.35 is OK
- 10.7717/peerj.453 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2150

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2150, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch paper 
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true from branch paper

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1371993667435692035) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2151
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.03089](https://doi.org/10.21105/joss.03089)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @utf (Alex Ganose) and co-authors!!

And thanks to @arosen93 and @lucydot for a very quick and easy review process!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03089/status.svg)](https://doi.org/10.21105/joss.03089)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03089">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03089/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03089/status.svg
   :target: https://doi.org/10.21105/joss.03089
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03089/status.svg)](https://doi.org/10.21105/joss.03089)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by utf** [comment]
Thank you everyone!

**Comment by utf** [comment]
Hi @danielskatz, the paper pdf isn't loading on https://joss.theoj.org/papers/10.21105/joss.03089

Just checking if this is usual and I need to wait a little bit?

**Comment by arosen93** [comment]
For what it's worth, it loads just fine for me. Maybe it's related to an ad-blocker or something similar?

**Comment by utf** [comment]
Strange, on Safari nothing loads but on Chrome I see:

<img width="1792" alt="Screenshot 2021-03-16 at 18 51 51" src="https://user-images.githubusercontent.com/1330638/111402627-c133be00-8688-11eb-895d-08916fd9081c.png">

I will see if this has fixed itself by tomorrow.

**Comment by arosen93** [comment]
Very odd! Well, here's a sneak peak I guess! Works fine for me on Chrome and Edge even though you get the 404. Hopefully @danielskatz can provide some insight.

![image](https://user-images.githubusercontent.com/8674072/111402743-c2b9b200-8699-11eb-9244-d096b78b81ee.png)

**Comment by danielskatz** [comment]
It worked for me on Safari - a check of it is the last thing I do before closing an issue.  It's likely a caching problem somewhere - If you are on a wifi network, you could try on a phone network or something like that, or just wait a bit.
