### ISSUE TITLE
[PRE REVIEW]: BigArrayList: A Java API which Allows Programmers to Transparently Use Disk Space as Additional 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#309]
**Submitting author:** @dselent (<a href="http://orcid.org/0000-0003-2322-6734">Douglas Selent</a>)
**Repository:** <a href="https://github.com/dselent/BigArrayList" target ="_blank">https://github.com/dselent/BigArrayList</a>
**Version:** 1.3
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @dselent. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@dselent if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave @dselent. Many thanks for your submission.

It's not immediately clear to me that this project meets our [JOSS submission criteria](http://joss.theoj.org/about#author_guidelines). Could you outline the research application of this work?

**Comment by dselent** [comment]
Sure,
The original research application was for merging school lunch data into an existing large .csv file on student data from the ASSISTments online tutoring system.  The file contents are too large to fit in memory and there are a lack of good tools that easily operate on files that large.  The library I developed made it easy to create a simple program to do the required tasks.  I provide the specific concrete example of its original research application, however I developed the library for more generic use.

**Comment by labarba** [comment]
@dselent : I looked at the `paper.md` file in the repo and it's just not a good-enough description of the software and the way that it addresses a research need. 

We (the JOSS editors) plan to extend the author guidelines to be more clear about the requirements, and to be more firm with enforcing them. Paper length is an issue: we need to see a clear statement of need within the research enterprise, and expect that is not possible in under 250 words (the guide will likely give a range of 250 to 1000 words maximum).

In its current form, the submission looks like a generic tool. You will need to expand on why this is useful in research.

**Comment by dselent** [comment]
@labarba : I updated the paper using < 1000 words.  I added more background for the research applications and how it is an improvement on existing solutions.  I also added some details on what the library is and how it works internally.

**Comment by arfon** [comment]
Hi @dselent, many thanks for update your paper. After review the editorial board has determined that your submission does not meet our [submission requirements](http://joss.theoj.org/about#submission_requirements). In particular, this submission falls under the 'Minor utility package' category.

Apologies for any time wasted here. Over the last few weeks we've been tightening up the language surrounding our submission requirements to help authors understand the scope of JOSS and your submission was held up while we made these changes.
