### ISSUE TITLE
[PRE REVIEW]: `modglm`: An R package for testing, interpreting, and displaying interactions   in generalized linear models of discrete data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3090]
**Submitting author:** @connorjmccabe (<a href="http://orcid.org/0000-0003-1868-8459">Connor McCabe</a>)
**Repository:** <a href="https://github.com/connorjmccabe/modglm" target ="_blank">https://github.com/connorjmccabe/modglm</a>
**Version:** 0.0.0.9000
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @connorjmccabe. **Currently, there isn't an JOSS editor assigned** to your paper.

@connorjmccabe if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (150.4 files/s, 23285.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                6            182            387            513
Markdown                         2             53              0            104
-------------------------------------------------------------------------------
SUM:                             8            235            387            617
-------------------------------------------------------------------------------


Statistical information for the repository 'ecda680e7a502e86deddce34' was
gathered on 2021/03/05.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3090 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch JOSS-MS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-MS. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3090 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: authors, affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
@whedon check references from branch JOSS-MS

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch JOSS-MS
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/00273171.2020.1868966 is OK
- 10.1016/S0165-1765(03)00032-6 is OK
- 10.15195/v6.a4 is OK
- 10.1177/2515245917746792 is OK
- 10.2307/2669316 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1177/1536867X1201200209 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.3102/10769986031004437 is INVALID because of 'https://doi.org/' prefix
```

**Comment by danielskatz** [comment]
@connorjmccabe - I think the header should be
```
author:
 - name: Connor J. McCabe^[Corresponding Author]
   orcid: 0000-0003-1868-8459
   affiliation: 1
 - name: Max A. Halvorson
   orcid: 0000-0002-3113-2458
   affiliation: 2
 - name: Kevin M. King
   orcid: 0000-0001-8358-9946
   affiliation: 2
 - name: Xiaolin Cao
   affiliation: 2
 - name: Dale S. Kim
   orcid: 0000-0002-5365-3748
   affiliation: 3
affiliations:
 - name: University of California, San Diego
   index: 1
 - name: University of Washington
   index: 2
 - name: University of California, Los Angeles
   index: 3
```

**Comment by danielskatz** [comment]
Can you try this, and use the command I did (`@whedon generate pdf from branch JOSS-MS` as the first line in a new comment) to regenerate the PDF?

Also, two of the DOIs in the .bib file need to have the `http://doi.org/` DOI prefix removed.  You can use `@whedon check references from branch JOSS-MS` to check that this is fixed

**Comment by connorjmccabe** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by connorjmccabe** [comment]
@whedon generate pdf from branch JOSS-MS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-MS. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3090 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: authors (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by connorjmccabe** [comment]
@whedon check references from branch JOSS-MS

**Comment by danielskatz** [comment]
You also need to remove the blank line after the title in the header

**Comment by connorjmccabe** [comment]
Hi @danielskatz,

I appreciate these suggestions! I've re-tried with the header you suggested and I'm still getting compliation errors on this. Any other suggestions on what I might try? I've done some trial-and-error and I can get a compiled version with one author and no `^[Corresponding Author]` bit it seems.

Thanks,

Connor

**Comment by danielskatz** [comment]
@whedon generate pdf from branch JOSS-MS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-MS. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3090 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: authors (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment]
the `author:` line in the header should be `authors:` (add an s)

**Comment by danielskatz** [comment]
@whedon check references from branch JOSS-MS

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch JOSS-MS
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/00273171.2020.1868966 is OK
- 10.1016/S0165-1765(03)00032-6 is OK
- 10.15195/v6.a4 is OK
- 10.1177/1536867X1201200209 is OK
- 10.1177/2515245917746792 is OK
- 10.3102/10769986031004437 is OK
- 10.2307/2669316 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by connorjmccabe** [comment]
@whedon generate pdf

**Comment by connorjmccabe** [comment]
@whedon generate pdf from branch JOSS-MS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-MS. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3090 with the following error: 

 Can't find any papers to compile :-(

**Comment by connorjmccabe** [comment]
@whedon check references from branch JOSS-MS

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch JOSS-MS
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03090/joss.03090/10.21105.joss.03090.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03090/joss.03090/10.21105.joss.03090.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/00273171.2020.1868966 is OK
- 10.1016/S0165-1765(03)00032-6 is OK
- 10.15195/v6.a4 is OK
- 10.1177/1536867X1201200209 is OK
- 10.1177/2515245917746792 is OK
- 10.3102/10769986031004437 is OK
- 10.2307/2669316 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by connorjmccabe** [comment]
@danielskatz I believe that did the trick. I really appreciate your help on this!

**Comment by danielskatz** [comment]
@connorjmccabe - note that JOSS requires an explicit "Statement of Need" section - please add such a section, perhaps containing some of the existing text.  This would ideally explain some disciplines in which this software would be used.

**Comment by connorjmccabe** [comment]
@whedon generate pdf from branch JOSS-MS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-MS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03090/joss.03090/10.21105.joss.03090.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03090/joss.03090/10.21105.joss.03090.pdf) :page_facing_up: :point_left:

**Comment by connorjmccabe** [comment]
@danielskatz Thanks for noting this. I have just made this change.

**Comment by kyleniemeyer** [comment]
Hi @connorjmccabe, thanks for your interest in JOSS, and work on the paper. Due to the relatively small size (under 1000 source lines of code) of your submission, the editorial board is going to review this and determine whether it should continue on to review.

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
Thanks for your submission to JOSS @connorjmccabe. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it fails to meet our [substantial scholarly effort criterion](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
