### ISSUE TITLE
[REVIEW]: epipack: An infectious disease modeling package for Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3097]
**Submitting author:** @benmaier (<a href="http://orcid.org/0000-0001-7414-8823">Benjamin F. Maier</a>)
**Repository:** <a href="https://github.com/benmaier/epipack" target ="_blank">https://github.com/benmaier/epipack</a>
**Version:** v0.1.2
**Editor:** @fboehm
**Reviewer:** @chrisvoncsefalvay, @esteinig
**Archive:** <a href="https://doi.org/10.5281/zenodo.4655616" target="_blank">10.5281/zenodo.4655616</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8e27f9956723872f916ea1bf23fc5dcb/status.svg)](https://joss.theoj.org/papers/8e27f9956723872f916ea1bf23fc5dcb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8e27f9956723872f916ea1bf23fc5dcb"><img src="https://joss.theoj.org/papers/8e27f9956723872f916ea1bf23fc5dcb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8e27f9956723872f916ea1bf23fc5dcb/status.svg)](https://joss.theoj.org/papers/8e27f9956723872f916ea1bf23fc5dcb)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/benmaier/epipack" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@chrisvoncsefalvay & @esteinig, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @fboehm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/benmaier/epipack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@benmaier) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/benmaier/epipack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@benmaier) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @chrisvoncsefalvay, @esteinig it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BF02464423 is OK
- 10.1021/j100540a008 is OK
- 10.1186/1471-2334-11-37 is OK
- 10.18637/jss.v084.i08 is OK
- 10.6084/m9.figshare.1164194 is OK
- 10.21105/joss.01731 is OK
- 10.1016/j.physrep.2020.07.005 is OK
- 10.1016/j.cpc.2019.02.008 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.18452/20950 is OK
- 10.1016/j.jtbi.2011.07.015 is OK
- 10.21105/joss.00565 is OK
- 10.1007/978-3-319-50806-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.67 s (51.7 files/s, 9249.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          85           3433           3717           8790
reStructuredText                34           1396           1934           1571
Markdown                         6            223              0            663
TeX                              1             18              0            246
make                             2             48              6            238
DOS Batch                        1             34              2            227
Jupyter Notebook                 2              0           2035             83
JSON                             3              0              0             10
Bourne Shell                     2              1              0              5
INI                              1              0              0              5
CSS                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                           138           5153           7694          11841
-------------------------------------------------------------------------------


Statistical information for the repository '893be85df9210d56380ab9e0' was
gathered on 2021/03/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ben F. Maier                    12           473             96            2.12
Benjamin Maier                 130         20924           5343           97.88

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ben F. Maier              15940         3370.0          5.7                7.67
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: :point_left:

**Comment by fboehm** [comment]
Thank you, @esteinig and @chrisvoncsefalvay , for agreeing to review this submission. You can see above your checklists for the review process. Please reach out to me when questions come up.

**Comment by chrisvoncsefalvay** [comment]
The paper does not contain a 'statement of need' section. However, it is my view that the substance of this requirement (pasted below for reference) is addressed adequately in para.s 1 through 3. With that in mind, I would consider requirement 1 of the Documentation section to be met.

> The authors should clearly state what problems the software is designed to solve and who the target audience is.

**Comment by esteinig** [comment]
> The authors should clearly state what problems the software is designed to solve and who the target audience is.

Agreed, it is well addressed in the paragraphs

**Comment by fboehm** [comment]
@esteinig and @chrisvoncsefalvay - how are your reviews going? It looks like you both haven't yet checked the "installation" and "functionality" boxes. Are there issues that the authors should address?

**Comment by chrisvoncsefalvay** [comment]
@fboehm I have just completed my review. I've left the installation and functionality boxes last, as I wanted to give a thorough opinion. I have managed to install and test functionalities with success on a Mac OS Big Sur system. I am happy to check off the relevant box based on that, although I would note that the author himself states they have tested it on a Mac OS system – there may be issues on, say, Windows systems that would not have shown up in the course of my testing.

Overall, it has been a pleasure to review what is a well-written, concise yet thorough paper supporting a very useful package that answers a clear need, and does so in a way that bundles often disparate techniques for the analysis of epidemic networks into a single cohesive package.

**Comment by fboehm** [comment]
@esteinig - how is the review going? Please let us know if there are issues that the authors should address. Thanks again!

**Comment by esteinig** [comment]
Hi my apologies for the delay, finishing my thesis at the moment. I am very pleased with the package and the code base, it's already gotten some attention within our lab. I had opportunity to test it on Linux systems but can't make an assessment on other OS. 

The paper is well written, and concise. My only recommendation would be to introduce some better structure with headlines in the paper, but that's all :)

**Comment by fboehm** [comment]
Thank you, @esteinig! Can you be more specific about the suggestion for headlines in the paper? Can you recommend specific places in paper.md where headlines might be placed? 

Thanks again!

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: :point_left:

**Comment by benmaier** [comment]
Dear @fboehm, @chrisvoncsefalvay, and @esteinig, thank you so much for this lightning-fast editing and reviewing work. This has probably been the smoothest reviewing experience I've ever had! I greatly appreciated all your positive comments about the work I submitted.

Regarding adding more headlines, I started working on the manuscript again to incorporate your point, @esteinig, but noticed that I do like the flow of the text as it is. I fear adding more subsections would make this already very short paper even more fragmented. When I wrote it, I had these two successful submissions in mind: 

1. https://raw.githubusercontent.com/adrn/gala/f6bb2532afeed3c0b0feea3037bf71a3f42b2a12/paper/paper.md
2. https://github.com/benmaier/netwulf/blob/master/paper/paper.md

where the only subsection was "Summary", as well. I would therefore prefer to keep the text as it is. Of course, this is an editorial decision, ultimately!

(Also, @esteinig, all the best for your thesis!)

**Comment by fboehm** [comment]
@benmaier - I think that your solution is reasonable.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BF02464423 is OK
- 10.1021/j100540a008 is OK
- 10.1186/1471-2334-11-37 is OK
- 10.18637/jss.v084.i08 is OK
- 10.6084/m9.figshare.1164194 is OK
- 10.21105/joss.01731 is OK
- 10.1016/j.physrep.2020.07.005 is OK
- 10.1016/j.cpc.2019.02.008 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.18452/20950 is OK
- 10.1016/j.jtbi.2011.07.015 is OK
- 10.21105/joss.00565 is OK
- 10.1007/978-3-319-50806-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: :point_left:

**Comment by fboehm** [comment]
line 22, please italicize i.e. and place a comma after the second period. "i.e., "

**Comment by fboehm** [comment]
@benmaier - please fix the typos that I mentioned immediately above in three comments.

**Comment by benmaier** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: :point_left:

**Comment by benmaier** [comment]
done!

**Comment by fboehm** [comment]
Great! We now need you, @benmaier to make a new release and to archive the package on zenodo. Please report in this thread the new release's version number and the archive's doi.

**Comment by benmaier** [comment]
* version: v0.1.2 
* zenodo: [10.5281/zenodo.4655616](https://doi.org/10.5281/zenodo.4655616)

**Comment by fboehm** [comment]
@whedon set 0.1.2 as version

**Comment by whedon** [comment]
OK. 0.1.2 is the version.

**Comment by fboehm** [comment]
@whedon set 10.5281/zenodo.4655616 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4655616" target="_blank">10.5281/zenodo.4655616</a> is the archive.

**Comment by fboehm** [comment]
@whedon set v0.1.2 as version

**Comment by whedon** [comment]
OK. v0.1.2 is the version.

**Comment by fboehm** [comment]
I've now downloaded the pdf and verified that all dois in the references section direct to the correct resources.

**Comment by fboehm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BF02464423 is OK
- 10.1021/j100540a008 is OK
- 10.1186/1471-2334-11-37 is OK
- 10.18637/jss.v084.i08 is OK
- 10.6084/m9.figshare.1164194 is OK
- 10.21105/joss.01731 is OK
- 10.1016/j.physrep.2020.07.005 is OK
- 10.1016/j.cpc.2019.02.008 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.18452/20950 is OK
- 10.1016/j.jtbi.2011.07.015 is OK
- 10.21105/joss.00565 is OK
- 10.1007/978-3-319-50806-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2175

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2175, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@benmaier Things look like they are mostly ready to go! One comment on your paper. For lists of inline parenthetical references, use this sort of format: [@ref1; @ref2] so that they should up together in one set of parentheses. More info: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by benmaier** [comment]
Ah, thank you and many apologies for not staying in syntax! Do you want me to fix this and resubmit?

**Comment by fboehm** [comment]
@benmaier - please fix the formatting issues and post a comment in this thread once the fixes have been made.

**Comment by benmaier** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: :point_left:

**Comment by benmaier** [comment]
ok, @fboehm, fixed!

**Comment by fboehm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03097/joss.03097/10.21105.joss.03097.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/BF02464423 is OK
- 10.1021/j100540a008 is OK
- 10.1186/1471-2334-11-37 is OK
- 10.18637/jss.v084.i08 is OK
- 10.6084/m9.figshare.1164194 is OK
- 10.21105/joss.01731 is OK
- 10.1016/j.physrep.2020.07.005 is OK
- 10.1016/j.cpc.2019.02.008 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.18452/20950 is OK
- 10.1016/j.jtbi.2011.07.015 is OK
- 10.21105/joss.00565 is OK
- 10.1007/978-3-319-50806-1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2182

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2182, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1379053318849314824) 👈 🐦🐦🐦

**Comment by danielskatz** [comment]
Congratulations to  @benmaier (Benjamin F. Maier)!!

And thanks to @chrisvoncsefalvay, @esteinig for reviewing, and @fboehm for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03097/status.svg)](https://doi.org/10.21105/joss.03097)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03097">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03097/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03097/status.svg
   :target: https://doi.org/10.21105/joss.03097
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03097/status.svg)](https://doi.org/10.21105/joss.03097)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
