### ISSUE TITLE
[PRE REVIEW]: dms2dfe: Comprehensive Workflow for Analysis of Deep Mutational Scanning Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#310]
**Submitting author:** @rraadd88 (<a href="http://orcid.org/0000-0002-6421-2067">Rohan Dandage</a>)
**Repository:** <a href="https://github.com/kc-lab/dms2dfe" target ="_blank">https://github.com/kc-lab/dms2dfe</a>
**Version:** v1.0.6
**Editor:** @tracykteal
**Reviewer:** @afrubin

**Author instructions**

Thanks for submitting your paper to JOSS @rraadd88. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rraadd88 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @tracykteal it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by tracykteal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
👋 @tracykteal - the submitting author suggested you as an editor for this submission.

**Comment by tracykteal** [comment]
Thanks for your submission @rraadd88 and sorry for the delay. I've confirmed that this submission has

- [X]  An OSI approved license
- [X] A description of the software and its research applications
- [X] Is in scope for this journal

So, I'm currently looking for a reviewer.

**Comment by tracykteal** [comment]
@whedon assign @tracykteal as editor

**Comment by whedon** [comment]
OK, the editor is @tracykteal

**Comment by tracykteal** [comment]
@krother @genomematt @ctb @rmflight @luizirber @konrad @cbrueffer would you be able to review?

**Comment by krother** [comment]
Sorry, I don't understand what the submission is about.. probably because I am unfamiliar with the method presented. I have to decline this one.

**Comment by genomematt** [comment]
@afrubin @daniaki Interested in reviewing this?

**Comment by afrubin** [comment]
@tracykteal This is my field and I'm happy to review the manuscript. Thanks, @genomematt

**Comment by arfon** [comment]
@whedon assign @afrubin as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @afrubin

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/362. Feel free to close this issue now!
