### ISSUE TITLE
[PRE REVIEW]: ExaFMM: a high-performance fast multipole method library with C++ and Python interfaces

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3100]
**Submitting author:** @tingyu66 (<a href="http://orcid.org/0000-0003-2520-0511">Tingyu Wang</a>)
**Repository:** <a href="https://github.com/exafmm/exafmm-t" target ="_blank">https://github.com/exafmm/exafmm-t</a>
**Version:** v0.1.1
**Editor:** @poulson
**Reviewers:** @berenger-eu, @pitsianis
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tingyu66. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @poulson.

@tingyu66 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/IPDPS.2008.4536319 is OK
- 10.1016/j.jcp.2011.12.024 is OK
- 10.1109/5992.814662 is OK
- 10.1016/j.jcp.2003.11.021 is OK
- 10.1002/nme.2972 is OK
- 10.1016/B978-0-12-384988-5.00009-7 is OK
- 10.6084/m9.figshare.92166.v1 is OK
- 10.1177/1094342011429952 is OK
- 10.1260/1748-3018.7.3.301 is OK
- 10.4208/cicp.020215.150515sw is OK
- 10.1145/2588768.2576787 is OK
- 10.1145/2590830 is OK
- 10.21105/joss.02444 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/0021-9991 is INVALID
- 10.21105/joss.02879 is INVALID
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.78 s (50.0 files/s, 36790.1 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Bourne Shell                     10           5185           6020          31749
m4                               21           1108            103          10913
C/C++ Header                     20            284            631           5223
C++                              14            239            236           1325
TeX                               1             18              0            235
Markdown                          5             30              0            218
CMake                             2             49             89            209
Python                            2             67            123            130
reStructuredText                  5             70             71             98
make                              4             25             11             91
Jupyter Notebook                  3              0            760             79
YAML                              1              1              0             37
Bourne Again Shell                1              1              0              2
--------------------------------------------------------------------------------
SUM:                             89           7077           8044          50309
--------------------------------------------------------------------------------


Statistical information for the repository 'd71e82d77755946c09e9b4b3' was
gathered on 2021/03/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Rio Yokota                      29         51608           1937           22.44
Tingyu Wang                    490         67516         108103           73.61
bloodysin                       67          4335           5075            3.94

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Rio Yokota                 1131            2.2          9.5                0.18
Tingyu Wang                6926           10.3         16.6               14.09
bloodysin                   201            4.6         27.4                4.98
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03100/joss.03100/10.21105.joss.03100.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03100/joss.03100/10.21105.joss.03100.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @poulson as editor

Hi @poulson, could you edit this submission for us?

**Comment by whedon** [comment]
@poulson has been invited to edit this submission.

**Comment by poulson** [comment]
@whedon set @poulson as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by poulson** [comment]
@whedon assign @poulson as editor

**Comment by whedon** [comment]
OK, the editor is @poulson

**Comment by poulson** [comment]
Hi Tingyu (@tingyu66) :wave: .

Please let me know if there are any reviewers from the following list
    https://bit.ly/joss-reviewers
which you feel would be especially suited for providing feedback on your submission. It's possible to have someone not on this list review, but it is much preferred if they have already signed up for JOSS.

**Comment by labarba** [comment]
Possible reviewers:

- sivaramambikasaran is the first author of [HODLRlib](https://joss.theoj.org/papers/10.21105/joss.01167) in JOSS (H-matrices, a related method)
- pitsianis is the first author of [SG-t-SNE-Π](https://joss.theoj.org/papers/10.21105/joss.01577) in JOSS, and also a co-author of the [parallel AFMPB code](https://doi.org/10.1016/j.cpc.2014.12.022), targeting the same problem setting we have done with the code in our recent [arXiv preprint](https://arxiv.org/abs/2103.01048)
- the author or the other reviewers of [TBFMM](https://joss.theoj.org/papers/10.21105/joss.02444) in JOSS, another fast multipole method software

**Comment by poulson** [comment]
Hi Berenger (@berenger-eu) :wave:.

Given your authorship of the TBFMM JOSS paper, please let me know if you would be willing to serve as a reviewer on this submission on a high-performance C++/Python FMM implementation.

**Comment by poulson** [comment]
Hi Siva (@sivaramambikasaran) :wave:,

Given your expertise in FMM and its algebraic analogues, please let me know if you would be willing to serve as a reviewer for this submission on a high-performance C++/Python FMM implementation.

**Comment by berenger-eu** [comment]
Hi Jack,
Yes I agree, thanks to let me participate.
Bérenger

**Comment by poulson** [comment]
Thank you Bérenger!

**Comment by poulson** [comment]
@whedon add @berenger-eu as reviewer

**Comment by whedon** [comment]
OK, @berenger-eu is now a reviewer

**Comment by poulson** [comment]
Hi Nicos (@pitsianis) :wave: -- I hate to ask for you to review yet another paper, but would you be willing to serve as a reviewer on this C++/Python submission on high-performance Fast Multipole Methods?

**Comment by berenger-eu** [comment]
@poulson If I am correct, some checkboxes should be on the first post, right? Should I do something to make them appearing? Maybe it will be automatically done after all the reviewers will be selected(?) Thanks.

**Comment by poulson** [comment]
Yes, we need at least two reviewers -- and ideally three -- before starting the review.

**Comment by pitsianis** [comment]
I will do it

**Comment by poulson** [comment]
Thank you Nikos!

**Comment by poulson** [comment]
@whedon add @pitsianis as reviewer

**Comment by whedon** [comment]
OK, @pitsianis is now a reviewer

**Comment by poulson** [comment]
Hi Siva (@sivaramambikasaran) :wave: -- I wanted to circle back to see if you might have time to serve as a reviewer for this submission on high-performance FMM. We have two reviewers, but three is always preferred and I believe you would provide helpful feedback.

**Comment by poulson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3145.

**Comment by pitsianis** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03100/joss.03100/10.21105.joss.03100.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03100/joss.03100/10.21105.joss.03100.pdf) :page_facing_up: :point_left:

**Comment by pitsianis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03100/joss.03100/10.21105.joss.03100.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03100/joss.03100/10.21105.joss.03100.pdf) :page_facing_up: :point_left:
