### ISSUE TITLE
[PRE REVIEW]: RustBCA: A High-Performance, Binary-Collision-Approximation Code for Ion-Material Interactions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3101]
**Submitting author:** @drobnyjt (<a href="http://orcid.org/0000-0002-9733-6058">Jon Drobny</a>)
**Repository:** <a href="https://github.com/lcpp-org/RustBCA" target ="_blank">https://github.com/lcpp-org/RustBCA</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @HaoZeke, @joglekara
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @drobnyjt. **Currently, there isn't an JOSS editor assigned** to your paper.

@drobnyjt if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (251.2 files/s, 56872.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rust                            13            713            367           3826
Python                           5            443            352           1670
TOML                            14             41              0            709
TeX                              1             14              0            429
Markdown                         6            103              0            337
YAML                             1              5              0             46
-------------------------------------------------------------------------------
SUM:                            40           1319            719           7017
-------------------------------------------------------------------------------


Statistical information for the repository '03b25ea39e0ee9d9d378b1d7' was
gathered on 2021/03/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jon Drobny                      65         15592          13660           97.34
Ryan M. L. McFadden              1            30             29            0.20
Stephen                         12           374            100            1.58
Stephen-Armstrong                1           254              0            0.85
zerostarm                        1             8              4            0.04

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jon Drobny                 1903           12.2          4.3                2.15
Ryan M. L. McFadden          30          100.0          3.8                0.00
Stephen                     330           88.2          1.1                5.76
Stephen-Armstrong           199           78.3          1.4               13.57
zerostarm                     3           37.5          1.4               33.33
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1367-2630/aa56eb is OK
- 10.1088/0022-3727/47/39/394003 is OK
- 10.1063/1.1776318 is OK
- 10.1080/00337578408215770 is OK
- 10.1103/PhysRevB.9.5008 is OK
- 10.1016/0029-554X(76)90806-5 is OK
- 10.1016/0029-554x(80)90440-1 is OK
- 10.1016/0022-3115(79)90397-0 is OK
- 10.1016/0022-3115(80)90189-0 is OK
- 10.1007/BF00614759 is OK
- 10.1080/10420159408219787 is OK
- 10.1016/0029-554X(82)90575-4 is OK
- 10.1016/j.jnucmat.2017.07.037 is OK
- 10.1080/10420159408219767 is OK
- 10.1016/0010-4655(88)90148-8 is OK
- 10.1016/0168-583X(92)95298-6 is OK
- 10.1016/0168-583X(84)90271-4 is OK
- 10.1063/1.327954 is OK
- 10.1080/00337578308218604 is OK
- 10.1080/00337578408222489 is OK
- 10.1016/j.nimb.2010.02.091 is OK
- 10.1006/adnd.1996.0005 is OK
- 10.1134/S1027451019030339 is OK
- 10.1016/j.apsusc.2018.01.039 is OK
- 10.1016/j.apsusc.2014.03.152 is OK
- 10.1088/1402-4896/ab4c29 is OK
- 10.1063/1.1776318 is OK
- 10.1016/0168-583X(87)90004-8 is OK

MISSING DOIs

- 10.1007/978-3-642-73513-4 may be a valid DOI for title: Computer Simulation of Ion-Solid Interactions

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03101/joss.03101/10.21105.joss.03101.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03101/joss.03101/10.21105.joss.03101.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @luizirber as editor

:wave: @luizirber - I realize this it out of your field, but I wondered if you might want to take it on as I know you like Rust 😬

**Comment by whedon** [comment]
@luizirber has been invited to edit this submission.

**Comment by luizirber** [comment]
@whedon assign @luizirber as editor

**Comment by whedon** [comment]
OK, the editor is @luizirber

**Comment by arfon** [comment]
:wave: @luizirber - are you still able to handle this submission? If so, the next step is to identify some reviewers :-)

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@drobnyjt - apologies for the very slow movement on this submission. It looks like @luizirber is unable to edit this paper for us so I'll take it on from here.

Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by drobnyjt** [comment]
@arfon Sure, no problem. From that list, I would recommend:

1. joglekara for kinetic plasma physics modeling experience
2. HaoZeke for experience with Rust and Molecular Dynamics (closely related to the BCA)
3. amritagos for experience with Rust and Molecular Dynamics

**Comment by arfon** [comment]
:wave: @HaoZeke @joglekara @amritagos – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission we'd be asking you to review here is [_RustBCA: A High-Performance, Binary-Collision-Approximation Code for Ion-Material Interactions_](https://github.com/lcpp-org/RustBCA).

**Comment by HaoZeke** [comment]
Hi @arfon, Sure I'd be happy to review this, looks very interesting.

**Comment by arfon** [comment]
@whedon add @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, @HaoZeke is now a reviewer

**Comment by arfon** [comment]
:zap: thanks @HaoZeke! I'd like to wait a few more days before opening up the main review issue to try and find a second reviewer if that's OK? For now, please sit tight!

**Comment by joglekara** [comment]
hey @arfon , happy to review this. Thanks for tagging me in.

**Comment by arfon** [comment]
@whedon add @joglekara as reviewer

**Comment by whedon** [comment]
OK, @joglekara is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3298.

**Comment by arfon** [comment]
@HaoZeke, @joglekara - thanks so much for agreeing to review this submission! See you over in #3298 where the actual review will take place.
