### ISSUE TITLE
[PRE REVIEW]: Semi-Automatic Classification Plugin: A Python tool for the download and processing of remote sensing images in QGIS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3102]
**Submitting author:** @semiautomaticgit (<a href="http://orcid.org/0000-0001-7283-116X">Luca Congedo</a>)
**Repository:** <a href="https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin" target ="_blank">https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin</a>
**Version:** 7.8.0
**Editor:** @kthyng
**Reviewers:** @bstabler, @joferkington
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @semiautomaticgit. **Currently, there isn't an JOSS editor assigned** to your paper.

@semiautomaticgit if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3102 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.69 s (79.6 files/s, 65991.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          76           2050           7564          72235
SVG                            120            120            120          39983
Qt Linguist                      4              0              0          27642
Qt                               5              0              0          26955
XML                              5              0              0            503
Markdown                         2             71              0            117
make                             1             27             56             58
HTML                             1              0              0             13
-------------------------------------------------------------------------------
SUM:                           214           2268           7740         167506
-------------------------------------------------------------------------------


Statistical information for the repository '82eb72abd604c256e3109ed8' was
gathered on 2021/03/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Donovan Cameron                  1             3              0            0.00
Karthikeyan Singarav             1             8              9            0.00
Sayantan Majumdar                1             8              8            0.00
luca                            34         61551           7853            2.80
semiautomaticgit               139        909900        1503183           97.20

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Karthikeyan Singarav          7           87.5          3.0                0.00
luca                       6187           10.1         73.7               18.57
semiautomaticgit          75660            8.3         15.6                5.62
```

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03102/joss.03102/10.21105.joss.03102.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03102/joss.03102/10.21105.joss.03102.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @bstabler as editor

:wave: @bstabler - would you be able to edit this paper for JOSS?

**Comment by whedon** [comment]
@bstabler has been invited to edit this submission.

**Comment by semiautomaticgit** [comment]
> @whedon generate pdf from branch paper

Thank you very much @arfon !

**Comment by Kevin-Mattheus-Moerman** [comment]
@bstabler :wave: can you help edit this submission?

**Comment by bstabler** [comment]
I don't have time to edit, but I'm happy to review

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by kthyng** [comment]
@bstabler you still interested in reviewing?

**Comment by kthyng** [comment]
@joferkington Are you interested in reviewing this submission for JOSS? The reviews are done all through github following checklists and opening issues in the software repo. We ask for reviews to be finished in 4-6 weeks but it tends to be an iterative process so it would be best to start the process earlier in that window. You can get more information here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by bstabler** [comment]
@kthyng - yes!

**Comment by kthyng** [comment]
@whedon assign @bstabler as reviewer

**Comment by whedon** [comment]
OK, @bstabler is now a reviewer

**Comment by kthyng** [comment]
(just pinged joferkington by email)

**Comment by joferkington** [comment]
@kthyng - Sorry for not noticing this earlier! I'd be happy to review and should have time in the next week.

**Comment by kthyng** [comment]
Thanks @joferkington!

**Comment by kthyng** [comment]
@whedon add @joferkington as reviewer

**Comment by whedon** [comment]
OK, @joferkington is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3172.

**Comment by kthyng** [comment]
@bstabler and @joferkington, please head on over to #3172  for the actual review issue, and let me know if you have any questions. Thanks!
