### ISSUE TITLE
[PRE REVIEW]: TE-dependent analysis of multi-echo fMRI with *tedana*

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3103]
**Submitting author:** @tsalo (<a href="http://orcid.org/0000-0001-9813-3167">Taylor Salo</a>)
**Repository:** <a href="https://github.com/ME-ICA/tedana" target ="_blank">https://github.com/ME-ICA/tedana</a>
**Version:** 0.0.9
**Editor:** @oliviaguest
**Reviewers:** @martinagvilas, @stebo85
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tsalo. **Currently, there isn't an JOSS editor assigned** to your paper.

@tsalo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.48 s (195.0 files/s, 34218.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          50           1593           3538           5052
reStructuredText                19            700            646           1747
Jupyter Notebook                 2              0           1127            571
Markdown                         7            171              0            523
YAML                             7             24             20            342
JSON                             1              0              0            117
Bourne Shell                     2             25             62             64
HTML                             2              5              1             57
make                             2             13              6             34
DOS Batch                        1              8              1             27
CSS                              1              3              3             14
-------------------------------------------------------------------------------
SUM:                            94           2542           5404           8548
-------------------------------------------------------------------------------


Statistical information for the repository '4af636ce7f1bbede560a820c' was
gathered on 2021/03/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Benoît Béranger                  1             3              1            0.01
Cesar Caballero Gaud             1             8              2            0.02
Chris Markiewicz                 2             8              2            0.02
Daniel Handwerker                5           397            115            1.26
Dylan                            2           115              5            0.30
Elizabeth DuPre                 89          8895           4694           33.44
Eneko Uruñuela                   2           860             32            2.20
Frode Aannevik                  14           463            482            2.33
Joshua Teves                    18           503            447            2.34
Logan                           43           256             59            0.78
Logan Dowdle                    13           525            128            1.61
Ross Markello                   28          2575           1645           10.38
Stefano Moia                     2            29             26            0.14
Taylor Salo                    230         10245           7617           43.96
TomMaullin                       1             9             38            0.12
Zaki A                           7            43             42            0.21
monicayao                       11           357             11            0.91

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Benoît Béranger               2           66.7         16.8                0.00
Cesar Caballero Gaud          8          100.0         12.8               87.50
Chris Markiewicz              7           87.5         16.4               28.57
Dylan                        10            8.7         38.8               20.00
Elizabeth DuPre            3893           43.8         24.7               15.59
Eneko Uruñuela              814           94.7         13.7               10.32
Frode Aannevik              182           39.3         28.3                9.89
Joshua Teves                382           75.9         15.3               12.57
Logan                       127           49.6         19.9               11.02
Ross Markello               205            8.0         33.1               13.17
Stefano Moia                  5           17.2         15.2                0.00
Taylor Salo                4241           41.4         18.9                8.72
TomMaullin                    1           11.1         33.0                0.00
Zaki A                       43          100.0          0.8                0.00
monicayao                   263           73.7         18.0               15.59
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3103 with the following error: 

 Can't find any papers to compile :-(

**Comment by tsalo** [comment]
The manuscript is located at https://github.com/ME-ICA/tedana/blob/joss/paper/paper.md. Is there a way to make it easier for the bot to locate it?

**Comment by emdupre** [comment]
Let's try :

 @whedon generate pdf from branch joss

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by arfon** [comment]
@emdupre - thanks. Whedon is a little fussy and expects the command as the first string in a comment...

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03103/joss.03103/10.21105.joss.03103.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03103/joss.03103/10.21105.joss.03103.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @jni as editor

:wave: @jni - would you be able to edit this paper for JOSS?

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by arfon** [comment]
@whedon invite @cMadan as editor

:wave: @cMadan - would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by jni** [comment]
@arfon I only have bandwidth for one more concurrent submission (really -1, but I'll stretch a bit! 😅), so I'll decline this one. 🙏

**Comment by tsalo** [comment]
Here are a list of 15 potential reviewers we felt would be well-suited for this manuscript:

- Athanasiamo
- JonathanReardon
- SRSteinkamp
- TomDonoghue
- a3sha2
- arokem
- grlee77
- hanayik
- lukassnoek
- martinagvilas
- mwegrzyn
- puolival
- sappelhoff
- sealhuang
- spinicist

**Comment by cMadan** [comment]
I don't think I can take on another review at this time, sorry!

**Comment by arfon** [comment]
@tsalo - it looks like the editors best-placed to handle this submission are a little busy right now. I'm going to mark this as 'waitlisted' and we'll assign an editor just as soon as one becomes available. Thanks in advance for your patience!

**Comment by danielskatz** [comment]
👋 @oliviaguest - Is this a submission you might be able to edit?

**Comment by danielskatz** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by oliviaguest** [comment]
I can but not in any immediate way — is it OK to take it on but "pause" it for a few weeks? 😊

**Comment by danielskatz** [comment]
Yes, that's fine - I'll assign it to you, and when you are ready to start, please remove the 'waitlisted' label and go ahead

**Comment by danielskatz** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by tsalo** [comment]
We just want to check in on this and see if there's anything needed from us to move this forward.

**Comment by oliviaguest** [comment]
@tsalo thank you for checking, short answer: no. Longer answer: I am swamped with work, other duties as editor, etc., but will reach out to reviewers starting (hopefully) next week, Monday. Thus removing the waitlist tag. But I promise you I have neither forgotten, nor absconded my duties more generally here. ☺️

**Comment by tsalo** [comment]
Thank you @oliviaguest! We're happy to wait. We're just glad to have a better understanding of the timeline.

**Comment by oliviaguest** [comment]
@whedon add @martinagvilas as reviewer

**Comment by whedon** [comment]
OK, @martinagvilas is now a reviewer

**Comment by arfon** [comment]
:wave: @oliviaguest, I wonder if `jsheunis`, `szorowi1, or `SRSteinkamp` might be able to act as a second reviewer here?

**Comment by oliviaguest** [comment]
@arfon I'll try them! Thanks!

**Comment by oliviaguest** [comment]
Ah, @arfon... spoke too soon!

`jsheunis`` unfortunately cannot review this because they are an author on the paper. Made the same mistake months ago when I asked them, ha! In the case of ``szorowi1``, they don't reply to my emails... 😅

**Comment by emdupre** [comment]
For additional reviewers, I might also suggest :

robbisg
htwangtw
richford
Remi-Gau
matteomancini
dr-xenia
mih
snastase

**Comment by oliviaguest** [comment]
@whedon add @stebo85 as reviewer

**Comment by whedon** [comment]
OK, @stebo85 is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3669.

**Comment by oliviaguest** [comment]
👋 @martinagvilas, @stebo85 please go to #3669 to start the process of reviewing this paper! 😊
