### ISSUE TITLE
[PRE REVIEW]: Fear Learning and Anxiety Response (FLARe): Open-source software for remote human fear conditioning experiments.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3105]
**Submitting author:** @McGregor14 (<a href="http://orcid.org/0000-0003-0024-7049">Thomas McGregor</a>)
**Repository:** <a href="https://github.com/flare-kcl/flare-app" target ="_blank">https://github.com/flare-kcl/flare-app</a>
**Version:** v1.0.0
**Editor:** @oliviaguest
**Reviewers:** @peircej, @KirstensGitHub, @EleonoraVagnoni
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @McGregor14. **Currently, there isn't an JOSS editor assigned** to your paper.

@McGregor14 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/j.actpsy.2007.11.007 may be a valid DOI for title: The relevance of recent developments in classical conditioning to understanding the etiology and maintenance of anxiety disorders
- 10.31234/osf.io/r9qtj may be a valid DOI for title: Validating the use of a smartphone app for remote administration of a fear conditioning paradigm
- 10.1101/2020.12.18.423504 may be a valid DOI for title: Evidence for distinct genetic and environmental influences on fear acquisition and extinction

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3105 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Gerome Breen, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@McGregor14 - this PR should fix your paper https://github.com/flare-kcl/flare-app/pull/110

**Comment by arfon** [comment]
@whedon invite @oliviaguest as editor

:wave: @oliviaguest - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest as reviewer

**Comment by whedon** [comment]
You need to assign an editor first.

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
👋  Hi @McGregor14, would be so kind as to share some names from the reviewers list (without the @) to help me a little? Ta! ☺️

**Comment by McGregor14** [comment]
Hello @oliviaguest 👋

For the app, I can see olade014 has React Native in their list of languages. Though I can't see anyone else, kellerb has listed React and is also comfortable reviewing social sciences. Other people with React in their list of languages include marwahaha and jdalzatec.

For the portal, pgadige is the only person I can see with Django in their list of languages. However, since Django is based on Python, the following people with an interest in psychology may be appropriate: Andytwoods, snastase, JonathanReardon, peircej, and kirstensgithub

Thanks for joining as editor. Let me know if you need any extra info on the project or software.

**Comment by McGregor14** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03105/joss.03105/10.21105.joss.03105.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03105/joss.03105/10.21105.joss.03105.pdf) :page_facing_up: :point_left:

**Comment by NathHorrigan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03105/joss.03105/10.21105.joss.03105.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03105/joss.03105/10.21105.joss.03105.pdf) :page_facing_up: :point_left:

**Comment by oliviaguest** [comment]
@McGregor14 thank you for all the above! 🌼

**Comment by oliviaguest** [comment]
@McGregor14 I changed the title because I realised this (the new one) is what it should be, right?

**Comment by McGregor14** [comment]
@oliviaguest Yep! Thank you very much. I think the line numbers snuck in there somehow!

**Comment by oliviaguest** [comment]
@whedon add @peircej as reviewer

**Comment by whedon** [comment]
OK, @peircej is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @Andytwoods as reviewer

**Comment by whedon** [comment]
OK, @Andytwoods is now a reviewer

**Comment by andytwoods** [comment]
I am sorry but I do not feel comfortable reviewing this work. React and Docker are core technologies used here, both of which I have no experience with. I just cannot review this article in any sensible amount of time -- it takes days to get familiar with new tech stacks. And please note that there is an interplay between the different technologies that is also burdensome. It' not just the case that I can install the Django app and review that. There's seems to be a React frontend to the Django app that I would have to set up (with which I have no experience), which requires a set of technologies (e.g. live transpiling from ES6) I cannot become familiar with quickly.
With best wishes, Andy.

**Comment by oliviaguest** [comment]
Ah, apologies. I think I misunderstood you @andytwoods, and I shall remove you. Thanks for the feedback!

**Comment by oliviaguest** [comment]
@whedon remove @andytwoods as reviewer

**Comment by whedon** [comment]
OK, @andytwoods is no longer a reviewer

**Comment by oliviaguest** [comment]
@whedon add @KirstensGitHub as reviewer

**Comment by whedon** [comment]
OK, @KirstensGitHub is now a reviewer

**Comment by oliviaguest** [comment]
@McGregor14 sorry for the delay here — give me a few days to check with another potential reviewer, as I think they need to create a GitHub account. 😅  And then we can get this going. 🥳

**Comment by McGregor14** [comment]
@oliviaguest no problem! Thanks for the update.

**Comment by oliviaguest** [comment]
@whedon add @EleonoraVagnoni as reviewer

**Comment by whedon** [comment]
OK, @EleonoraVagnoni is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3270.
