### ISSUE TITLE
[PRE REVIEW]: BIDSonym - a BIDSapp for the pseudo-anonymization of neuroimaging datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3106]
**Submitting author:** @peerherholz (<a href="http://orcid.org/0000-0002-9840-6257">Peer Herholz</a>)
**Repository:** <a href="https://github.com/PeerHerholz/BIDSonym/" target ="_blank">https://github.com/PeerHerholz/BIDSonym/</a>
**Version:** v0.0.4
**Editor:** @oliviaguest
**Reviewers:** @deep-introspection, @chrisgorgo, @neuromusic
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @peerherholz. **Currently, there isn't an JOSS editor assigned** to your paper.

@peerherholz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (295.1 files/s, 47003.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            617           1352           1843
reStructuredText                17            285            164            594
TeX                              2             31              0            450
Dockerfile                       1             25              8            211
Bourne Shell                     1              6              7             92
Markdown                         3             30              0             82
YAML                             2              3              4             33
DOS Batch                        1              8              1             27
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                            37           1009           1542           3342
-------------------------------------------------------------------------------


Statistical information for the repository '97165b8a3059e64c054c30f8' was
gathered on 2021/03/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Peer Herholz                    16           981             43            8.59
PeerHerholz                     67          6880           4006           91.34
rxqx                             1             4              4            0.07

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
PeerHerholz                3812           55.4         16.5               13.93
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3106 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@PeerHerholz - please remove the line with the missing `orcid` for your author entry. Also, the editors in your area are a little overloaded right now so I'm going to put your submission into the backlog.

**Comment by PeerHerholz** [comment]
Hi @arfon,

thx for the pointer and update. 
Sorry for the obvious error...I compiled it locally via the `docker image` and also the `web version`, but overlooked my missing `orcid` both times. I updated the `paper.md` and added my `orcid`. 
Re editors: of course, I understand, thx for letting me know.

Cheers, Peer

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3106 with the following error: 

 pandoc: Bidsonym.bib: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
> pandoc: Bidsonym.bib: openBinaryFile: does not exist (No such file or directory)

@PeerHerholz - Pandoc is case sensitive for filenames your BibTeX file has a different case from how you're referencing it in the `paper.md`.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3106 with the following error: 

 pandoc: BidSonym.bib: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
@PeerHerholz - this is waiting for your fix as described by @arfon above - https://github.com/openjournals/joss-reviews/issues/3106#issuecomment-799210422

**Comment by PeerHerholz** [comment]
Hi @danielskatz, 

thanks for the ping, I'm sorry for the delay. 
I addressed the issue and based on the compiled preview I tested, things should work now. 

Thanks again. 

Cheers, Peer

**Comment by danielskatz** [comment]
Thanks - the commands to whedon are generally usable by anyone, such as the following

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03106/joss.03106/10.21105.joss.03106.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03106/joss.03106/10.21105.joss.03106.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@PeerHerholz - now back to the waitlist...

**Comment by PeerHerholz** [comment]
Hi @danielskatz,

ok, thanks for the notice, I wasn't sure if I should go ahead and try again.
I'll do that going forward.

Thanks again.

Cheers, Peer

**Comment by oliviaguest** [comment]
I am happy to edit this, if it's not been assigned yet and at that stage. 😊

**Comment by danielskatz** [comment]
@whedon assign @oliviaguest as editor

Thanks!!

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
@whedon add @deep-introspection as reviewer

**Comment by whedon** [comment]
OK, @deep-introspection is now a reviewer

**Comment by PeerHerholz** [comment]
Thanks so much @oliviaguest!

**Comment by oliviaguest** [comment]
@whedon add @chrisgorgo as reviewer

**Comment by whedon** [comment]
OK, @chrisgorgo is now a reviewer

**Comment by oliviaguest** [comment]
@whedon add @neuromusic as reviewer

**Comment by whedon** [comment]
OK, @neuromusic is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3169.
