### ISSUE TITLE
[PRE REVIEW]: FielDHub: An R Shiny Package for Design of Experiments in Life Sciences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3107]
**Submitting author:** @DidierMurilloF (<a href="http://orcid.org/0000-0003-3685-4959">Didier Murillo Florez</a>)
**Repository:** <a href="https://github.com/DidierMurilloF/FielDHub" target ="_blank">https://github.com/DidierMurilloF/FielDHub</a>
**Version:** 0.1.0
**Editor:** @csoneson
**Reviewers:** @Prof-ThiagoOliveira, @dlebauer
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @DidierMurilloF. **Currently, there isn't an JOSS editor assigned** to your paper.

@DidierMurilloF if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.31 s (423.4 files/s, 88849.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            30           1365            357          10651
R                               81           1779           1824           9880
CSS                              5            148             70            642
JavaScript                       3             64             32            256
Markdown                         5             71              0            181
TeX                              1              5              0             52
YAML                             4              4              3             43
SVG                              1              0              1             11
Rmd                              1             12             31              6
-------------------------------------------------------------------------------
SUM:                           131           3448           2318          21722
-------------------------------------------------------------------------------


Statistical information for the repository '94bad9ed849a59e518e6d04d' was
gathered on 2021/03/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
DidierMurillo                    1           352              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
DidierMurillo               352          100.0          0.0                9.09
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1198/108571106X154443 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1111/j.1467-842X.2011.00642.x is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03107/joss.03107/10.21105.joss.03107.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03107/joss.03107/10.21105.joss.03107.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @csoneson as editor

:wave: @csoneson - would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋 @DidierMurilloF - thanks for submitting to JOSS. I will handle your submission, and start by finding a couple of suitable reviewers. If you have any suggestions (e.g., from the list linked in the first post above), please mention them here (without tagging them with `@`). 

I noticed that your paper is currently missing a 'Statement of Need' section (see [here](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)). Could you please add that (I think you can break out a part of the 'Summary' section)? Also, please fix the invalid DOI mentioned by Whedon above (remove the `https://doi.org/` prefix). Thanks!

**Comment by DidierMurilloF** [comment]
@csoneson<https://github.com/csoneson> thank you for accepting to be the editor. I added the 'Statement of Need' section and fixed the problem with DOI. From the list of reviewers and I would like to suggest to ThiagoOliveira and dlebauer.

Thank you for your time and consideration!

Best regards,

Didier Murillo.
________________________________

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03107/joss.03107/10.21105.joss.03107.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03107/joss.03107/10.21105.joss.03107.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/j.1467-842X.2011.00642.x is OK
- 10.1198/108571106X154443 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
👋 @Prof-ThiagoOliveira, @dlebauer - would you be interested in reviewing this submission for JOSS? 

> FielDHub: An R Shiny Package for Design of Experiments in Life Sciences

**Comment by Prof-ThiagoOliveira** [comment]
Dear Madam/Sir,

Yes, I would appreciate to review this paper.

Best regards,
Dr. Thiago de Paula Oliveira
Blog: https://prof-thiagooliveira.netlify.com/
​
Researcher in Statistics
The Roslin Institute
University of Edinburgh
________________________________

**Comment by csoneson** [comment]
@Prof-ThiagoOliveira - great, thanks! Once we have secured one more reviewer I will start the actual review issue (where you will find the checklist to fill etc).

**Comment by dlebauer** [comment]
Hi Charlotte - yes I am interested in reviewing this submission

**Comment by csoneson** [comment]
Brilliant, thanks both for your quick replies! I will now open the review issue and further communication will happen over there.

**Comment by csoneson** [comment]
@whedon assign @Prof-ThiagoOliveira as reviewer

**Comment by whedon** [comment]
OK, @Prof-ThiagoOliveira is now a reviewer

**Comment by csoneson** [comment]
@whedon add @dlebauer as reviewer

**Comment by whedon** [comment]
OK, @dlebauer is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3122.
