### ISSUE TITLE
[PRE REVIEW]: ngsxfem: Add-on to NGSolve for geometrically unfitted finite element discretizations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3108]
**Submitting author:** @schruste (<a href="http://orcid.org/0000-0003-0170-8468">Christoph Lehrenfeld</a>)
**Repository:** <a href="https://github.com/ngsxfem/ngsxfem" target ="_blank">https://github.com/ngsxfem/ngsxfem</a>
**Version:** v2.0
**Editor:** @meg-simula
**Reviewers:** @mscroggs, @mikaem, @mikaem
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @schruste. **Currently, there isn't an JOSS editor assigned** to your paper.

@schruste if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.37 s (376.4 files/s, 72926.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             38           1931           1057           9911
Python                          47           1795           2075           4859
C/C++ Header                    32            671            297           2821
CMake                           12             87              9            361
TeX                              1             39              1            343
Markdown                         4            102              0            302
YAML                             3             14              0            213
Bourne Shell                     1              5              6             14
Dockerfile                       1              7              2             11
-------------------------------------------------------------------------------
SUM:                           139           4651           3447          18835
-------------------------------------------------------------------------------


Statistical information for the repository 'b4303fae6e6e369ecc1ee0e8' was
gathered on 2021/03/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christoph Lehrenfeld           974         53534          58645           60.14
Christoph Winterstei             2           339             24            0.19
Christopher Lackner              2             7              7            0.01
Fabian Heimann                 466         14595           6387           11.25
Henry Maximilian von            64          2461           1586            2.17
Henry v. Wahl                   97          3712           1354            2.72
Henry von Wahl                   4           153              1            0.08
Janosch Preuß                  100          6502           2186            4.66
Matthias Hochsteger              6           193            157            0.19
Philip Lederer                   5           636             13            0.35
Thomas Ludescher                17          3637            341            2.13
Tobias Jawecki                   1             3              3            0.00
Yimin Lou                        6           209             13            0.12
henryvonwahl                     2           333              0            0.18
hvonwah                          1             6              4            0.01
lehrenfeld                       1            93             32            0.07
mw                               2            77              1            0.04
root                             1           316             79            0.21
schruste@pummelzacke           190         22159           6078           15.14
tobias                           7           634             20            0.35
yimin.lou                        1             1              1            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Christoph Lehrenfeld      14000           26.2         37.5                7.59
Christopher Lackner           6           85.7         38.1                0.00
Fabian Heimann             4211           28.9         27.0                9.45
Henry Maximilian von       2960          120.3          7.0               14.86
Matthias Hochsteger          23           11.9         29.0               39.13
Thomas Ludescher            872           24.0         24.7               16.51
henryvonwahl                270           81.1         15.6                5.93
janosch.preuss              623          100.0         45.9               11.08
lehrenfeld                 2376         2554.8         38.2               12.92
root                         76           24.1         52.5                2.63
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03108/joss.03108/10.21105.joss.03108.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03108/joss.03108/10.21105.joss.03108.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1063/5.0037971 is OK
- 10.5281/zenodo.3989604 is OK
- 10.5281/zenodo.3647571 is OK
- 10.1051/m2an/2020044 is OK
- 10.1016/j.camwa.2019.08.003 is OK
- 10.1002/pamm.201610003 is OK
- 10.1016/j.cma.2015.12.005 is OK
- 10.1007/978-3-319-71431-8_3 is OK
- 10.1093/imanum/drx041 is OK
- 10.1007/978-3-319-96415-7_16 is OK
- 10.1051/m2an/2018068 is OK
- 10.1515/jnma-2017-0109 is OK
- 10.18154/RWTH-2020-07305 is OK
- 10.1137/16m1102203 is OK
- 10.1007/s00211-016-0801-6 is OK
- 10.11588/ans.2015.100.20553 is OK
- 10.1007/978-3-642-28589-9_7 is OK
- 10.11588/ans.2016.100.26526 is OK

MISSING DOIs

- 10.1093/imanum/drz062 may be a valid DOI for title: Trace Finite Element Methods for Surface Vector-Laplace Equations
- 10.7712/100016.1820.4573 may be a valid DOI for title: Removing the stabilization parameter in fitted and unfitted symmetric Nitsche formulations

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon invite @meg-simula as editor

:wave: @meg-simula - are you able to take on an additional paper at this time?

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by schruste** [comment]
As for the potential reviewers:
Perfect matches, but both not on the list, would be santiagobadia and chr-engwer. 
From the list the following persons seem to qualify as potential reviewers as well (in that order):
- jaroslavhron,
- mscroggs, 
- mikaem,
- capitalaslash

**Comment by Kevin-Mattheus-Moerman** [comment]
@meg-simula can you help edit this submission? It is okay if you need more time before you can commit to editing this, we can set the submission to `waitlisted` until you are available.

**Comment by kthyng** [comment]
Hi @schruste  and thanks for your submission! Our relevant editors for your submission are booked up already so I am adding you to our waitlist. You'll be taken on as availability opens up. Sorry for the wait and thanks for your patience.

**Comment by meg-simula** [comment]
Yes, I can take this on now.

**Comment by meg-simula** [comment]
@whedon assign meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by meg-simula** [comment]
@whedon generate pdf

**Comment by meg-simula** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03108/joss.03108/10.21105.joss.03108.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03108/joss.03108/10.21105.joss.03108.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
@schruste Thanks for the submission and your patience so far. This looks ready for review. I'm reaching out to reviewers and will get back to you shortly.

**Comment by meg-simula** [comment]
@whedon assign @mscroggs as reviewer

**Comment by whedon** [comment]
OK, @mscroggs is now a reviewer

**Comment by meg-simula** [comment]
@whedon add @mikaem as reviewer

**Comment by whedon** [comment]
OK, @mikaem is now a reviewer

**Comment by meg-simula** [comment]
@whedon add @mikaem as reviewer

**Comment by whedon** [comment]
OK, @mikaem is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3237.
