### ISSUE TITLE
[PRE REVIEW]: Qlunc: Quantification of lidar uncertainty

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3109]
**Submitting author:** @PacoCosta (<a href="http://orcid.org/0000-0003-1318-9677">F. Costa García</a>)
**Repository:** <a href="https://github.com/SWE-UniStuttgart/Qlunc" target ="_blank">https://github.com/SWE-UniStuttgart/Qlunc</a>
**Version:** v091
**Editor:** @danielskatz
**Reviewers:** @adi3, @PierreGuilbertF
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @PacoCosta. **Currently, there isn't an JOSS editor assigned** to your paper.

@PacoCosta if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (465.3 files/s, 72821.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          13            279            389            798
YAML                             7            140            124            435
Jupyter Notebook                 2              0           1391            315
Markdown                         5             76              0            275
TeX                              1             15              0            145
-------------------------------------------------------------------------------
SUM:                            28            510           1904           1968
-------------------------------------------------------------------------------


Statistical information for the repository 'bb469883edfadb42f2e43848' was
gathered on 2021/03/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Costa                           62          4017           4223           36.07
Francisco Costa                 73          2645           4024           29.19
PacoCosta                       67          5033           2903           34.74

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Costa                       387            9.6          4.7                9.04
Francisco Costa            1100           41.6          1.3               14.82
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3109 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (76e2c6ee44bc4f69fca0403f/Docs/JOSS_202102/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 10 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@PacoCosta - this PR should fix your paper compilation https://github.com/SWE-UniStuttgart/Qlunc/pull/105

**Comment by arfon** [comment]
Also, the editors for this area are a little busy right now so I'm going to mark this submission as 'waitlisted'. When an editor becomes available, we'll assign them.

**Comment by PacoCosta** [comment]
Dear Arfon,

Thanks for your comments.
Do you know how many time will take the complete process before publishing?
Thanks for your time and effort.

BR,
Paco

**Comment by arfon** [comment]
> Do you know how many time will take the complete process before publishing?

I don't sorry. JOSS reviews usually take up to two months (but sometimes more), but this is once an editor has been assigned. I would hope you will have an editor assigned in the next few weeks.

**Comment by PacoCosta** [comment]
Ok, thanks 👍

**Comment by adi3** [comment]
@arfon feel free to put me down as a reviewer. I have good experience in working with robotic sensors, and especially lidars.

**Comment by danielskatz** [comment]
👋 @sjpfenninger - are you available to edit again?

**Comment by danielskatz** [comment]
@whedon invite @sjpfenninger as editor

**Comment by whedon** [comment]
@sjpfenninger has been invited to edit this submission.

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @adi3 - thanks for volunteering - I'll assign you as a reviewer, but we won't start the review until we find another reviewer as well

**Comment by danielskatz** [comment]
@whedon assign @adi3 as reviewer

**Comment by whedon** [comment]
OK, @adi3 is now a reviewer

**Comment by danielskatz** [comment]
@PacoCosta - we have a few things we need to do now
1. Get the paper to compile - I'll check and see if you have made changes. You can also do this, by using the command `@whedon check references` to check the references, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.
2. Add an explicit "Statement of Need" section
3. suggest some additional reviewers - if you have any suggestions then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03109/joss.03109/10.21105.joss.03109.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03109/joss.03109/10.21105.joss.03109.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references

**Comment by danielskatz** [comment]
Ok, the paper compiles, but there is no "Statement of Need" section - you could probably just retitle the Motivation section to address this.

**Comment by danielskatz** [comment]
Please remove the prefix from the reference noted above ☝️ 

Also, one of your references (line 117 of the PDF) seems to be to this paper itself, which doesn't really make sense.

**Comment by PacoCosta** [comment]
1. Add Statement of Need section: :heavy_check_mark:
2. Remove prefix from invalid DOI's: :heavy_check_mark:
3. Suggest additional reviewer --> Scivision : :heavy_check_mark:
4. Reference to Qlunc version 0.91V: I am referencing the last release of Qlunc in Zenodo not to the paper itself. Do you think it doesn't have sense? If so, I will just remove it.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03109/joss.03109/10.21105.joss.03109.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03109/joss.03109/10.21105.joss.03109.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.3414197 is OK
- 10.5281/zenodo.4432136 is OK
- 10.5281/zenodo.3580749 is OK
- 10.5281/zenodo.3823878 is OK
- 10.5281/zenodo.1212538 is OK
- 10.1175/1520-0450(1968)007<0105:TDOKPO>2.0.CO;2 is OK
- 10.3390/rs10030406 is OK
- 10.13140/RG.2.1.1658.2005 is OK
- 10.3390/rs9060561 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
Re the reference, I see "Costa, F. (2021). Qlunc: A Python framework for quantification of lidar uncertainty. In Journal of Open Source Software (Version 0.91)." This seems to be a reference to this paper in JOSS, not the software in Zenodo.  But in either case, since the software will be published as part of the paper, why would the paper either cite itself or an element of it?

**Comment by danielskatz** [comment]
👋 @Scivision, @dsryberg - would one of you be willing to review this submission to JOSS?

**Comment by PacoCosta** [comment]
@danielskatz  - Definitely...

4. Remove reference to Qlunc: ✔️

**Comment by danielskatz** [comment]
@PacoCosta - when you make changes, please regenerate the PDF...  To do this, use the command `@whedon generate pdf` Whedon commands need to be the first entry in a new comment.

**Comment by PacoCosta** [comment]
@whedon generate pdf

Understood

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03109/joss.03109/10.21105.joss.03109.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03109/joss.03109/10.21105.joss.03109.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @NickLaurenson, @PierreGuilbertF, @bastienjacquet - would one of you be willing to review this JOSS submission (short paper and software)?  We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by danielskatz** [comment]
@PierreGuilbertF - thanks!  I'll add you, and we'll start the review

**Comment by danielskatz** [comment]
@whedon add @PierreGuilbertF as reviewer

**Comment by whedon** [comment]
OK, @PierreGuilbertF is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3211.
