### ISSUE TITLE
[PRE REVIEW]: Hytool: an open source matlab toolbox for the interpretation of hydraulic tests using analytical solutions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#311]
**Submitting author:** @philipperenard (<a href="http://orcid.org/0000-0003-4504-435X">Philippe Renard</a>)
**Repository:** <a href="https://github.com/UniNE-CHYN/hytool" target ="_blank">https://github.com/UniNE-CHYN/hytool</a>
**Version:** 2.05
**Editor:** @kyleniemeyer
**Reviewer:** @pboesu

**Author instructions**

Thanks for submitting your paper to JOSS @philipperenard. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@philipperenard if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by kyleniemeyer** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by kyleniemeyer** [comment]
Hi @philipperenard, thanks for your submission. Do you have a suggested reviewer or two from your domain?

For existing JOSS reviewers, @nicoguaro & @pboesu, would either of you be interested to review this?

**Comment by nicoguaro** [comment]
@kyleniemeyer, I don't have access to MATLAB right now, and the repository does not specify which version is required. Can it be ran in Octave?

**Comment by kyleniemeyer** [comment]
Hi @philipperenard, is your software Octave-compatible?

**Comment by philipperenard** [comment]
I do not expect that the code is fully compatible with octave. Currently it runs on R2017a and requires the Statistics toolbox.

**Comment by nicoguaro** [comment]
@kyleniemeyer, @philipperenard I don't that I have access to such a recent version of MATLAB. Not sure about the statistics toolbox, though.

**Comment by kyleniemeyer** [comment]
@nicoguaro ok, thanks. @philipperenard we may need your help in finding an appropriate reviewer, who also has access to Matlab+necessary toolbox(es).

@pboesu, are you able to review this submission?

**Comment by philipperenard** [comment]
@kyleniemeyer. Ok. Did you receive the list of potential reviewers? I send it in response to your message 2 days ago, but I did it directly from my email and I am unsure if you got it. In this list, I suggested three names, I am pretty sure that the second one has access to matlab. Here is again the same name plus a new one and a repetition of the first.

Martin H. Trauth: http://www.geo.uni-potsdam.de/mitarbeiterdetails/show/108/Martin+H._Trauth.html - I am sure that he uses matlab. He wrote a book on Matlab for earth sciences

Alan D. Chave: http://www.whoi.edu/science/AOPE/people/achave/Site/Blank.html - He just published a book on statistics for the earth sciences using matlab. 

Alex Cheng: http://home.olemiss.edu/~acheng/  - I am not sure if he has or uses matlab, but he knows very well the well testing domain. He wrote a mathematica toolbox on that topic some years ago.

Let me know if this is sufficient or if you need more help.

**Comment by kyleniemeyer** [comment]
@philipperenard ah no, I did not get any list. I will reach out to these three, thanks.

**Comment by pboesu** [comment]
@kyleniemeyer I am in principle happy to review this. However, two possible constraints:
1)  I'm about to do a fair amount of traveling, so realistically I will not be able to work on this review until the second half of August. If that should be a problem, I am happy to ceed to someone else.

2) My institution's licensed only for MATLAB R2014b (including the statistical toolbox). I managed to follow the installation instructions for this toolbox, and found the "Getting started" example, but am getting errors when executing parts of it (see here: https://gist.github.com/pboesu/460e5a9a046ca56ab199d838a2e6600a) . It would be great if @philipperenard could confirm whether R2017a is a hard requirement.

**Comment by kyleniemeyer** [comment]
Thanks for responding @pboesu! If we can't find someone else, then that timeline would be acceptable.

@philipperenard yes, please confirm if this is a hard requirement—and if so, one preliminary review suggestion might be to see if this requirement could be lessened, as it would enable more (potential) reuse.

**Comment by philipperenard** [comment]
Hi @kyleniemeyer, in principle, it should work with an older version. It was working with all previous versions since 2001. 

@pboesu: I have seen the error message that you get and I do not have yet enough information to reproduce the problem and analyze its origin. My first guess is that the data file is not imported properly. It could be a problem of file encoding between different OS and not a problem related to the version of matlab. Which OS are you using ? 

To try to reproduce the bug, I have started to download the release R2014b and will check if I obtain the same issue as you. 

But, please note that I am in holiday and traveling, I'll do my best to answer rapidly. But the internet connection is slow, and takes for ever to download matlab and do the tests...

**Comment by philipperenard** [comment]
I confirm that the ths_dmo example works (as well as war_dmo, thc_dmo, grf_dmo or blt_dmo) on R2014b on Windows 10.

**Comment by kyleniemeyer** [comment]
Hi @pboesu, just wanted to ping you on this review.

**Comment by pboesu** [comment]
Hi @kyleniemeyer sorry for the delay, I wasn't clear whether you were actively trying to recruit another reviewer, and then Irma blew through my life. I will try to get to this next week.

**Comment by kyleniemeyer** [comment]
@pboesu no worries/rush! Just wanted to check in. Hope things down there are going ok...

**Comment by kyleniemeyer** [comment]
Hi @pboesu are you still able to review this? If not, no worries, I will find a new reviewer.

**Comment by pboesu** [comment]
I am so sorry about the delay on this, this somehow slipped through the cracks on my end. I will start on the review today and should be able to finish it this weekend.

Can you please trigger whedon to open the review issue @kyleniemeyer ?

**Comment by arfon** [comment]
@whedon set @pboesu as reviewer

**Comment by arfon** [comment]
@whedon assign @pboesu as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pboesu

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/441. Feel free to close this issue now!

**Comment by arfon** [comment]
@pboesu - I've started the review for you over in #441

**Comment by kyleniemeyer** [comment]
@pboesu thanks!
