### ISSUE TITLE
[PRE REVIEW]: INCHEM-Py: An open source Python box model for indoor air chemistry

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3110]
**Submitting author:** @DrDaveShaw (<a href="http://orcid.org/0000-0001-5542-0334">David Shaw</a>)
**Repository:** <a href="https://github.com/DrDaveShaw/INCHEM-Py" target ="_blank">https://github.com/DrDaveShaw/INCHEM-Py</a>
**Version:** v1.0
**Editor:** @dhhagan
**Reviewers:** @goldmanm, @khinsen
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @DrDaveShaw. **Currently, there isn't an JOSS editor assigned** to your paper.

@DrDaveShaw if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (108.0 files/s, 78102.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          13            476           1122          10933
TeX                              1              2              0            186
SVG                              1              0              0            158
Markdown                         2             40              0             78
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            18            519           1126          11373
-------------------------------------------------------------------------------


Statistical information for the repository 'b9e14daa9c962586d8ac78c8' was
gathered on 2021/03/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
DrDaveShaw                      31         13665           1134          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
DrDaveShaw                12531           91.7          0.1                2.78
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/acs.est.5b02241 is OK
- 10.1021/es301350x is OK
- 10.1016/S1352-2310(96)00105-7 is OK
- 10.1016/j.atmosenv.2013.09.042 is OK
- 10.1016/j.atmosenv.2020.117784 is OK
- 10.1111/ina.12402 is OK
- 10.1111/ina.12394 is OK
- 10.1039/c9em00140a is OK
- 10.1016/j.atmosenv.2013.08.034 is OK
- 10.1111/ina.12381 is OK
- 10.1111/ina.12702 is OK
- 10.1145/2833157.2833162 is OK
- 10.1016/j.atmosenv.2006.09.038 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03110/joss.03110/10.21105.joss.03110.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03110/joss.03110/10.21105.joss.03110.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @dhhagan as editor

👋 @dhhagan - would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@dhhagan has been invited to edit this submission.

**Comment by dhhagan** [comment]
@arfon I can indeed.

**Comment by dhhagan** [comment]
@whedon assign @dhhagan as editor

**Comment by whedon** [comment]
OK, the editor is @dhhagan

**Comment by dhhagan** [comment]
Hi @DrDaveShaw - thank you so much for your submission to JOSS and I apologize for taking so long to get to this. Before I go ahead and find reviewers, I had a few questions/comments/suggestions:

1. It may be worth going through the README and fixing some of the typos
2. You are missing a few required parts of the paper such as the **statement of need* - it might be a good idea to look over a couple of recently published papers [here][1] to get an idea of what that looks like


Last, I was wondering if you could comment on how you envision this software to meet the "designed for maintainable extension" requirement found in the [**Substantial Scholarly Effort**][2] section of the JOSS submission criteria. It doesn't appear that any releases have been made or there is any versioning being tracked. Normally for a python submission, I would look for a python package that can be easily versioned, installed, etc, though that is **not** a strict requirement. I would like to understand how you plan on ensuring this is possible. 

I look forward to evaluating the rest of this great work! Please feel free to ping me here with any comments or questions.


[1]: https://joss.theoj.org/papers/published
[2]: https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort

**Comment by DrDaveShaw** [comment]
Hi @dhhagan 

Thank you very much for agreeing to be the Editor for our submission and for taking the time to look it over and provide these questions/comments/suggestions. 

1. I have read over the README and I have fixed the typos. I'm sorry they made it through to submission!
2. I have extracted the _statement of need_ into a section and completed additions to the paper in line with the recently published papers linked in your reply. 

Prior to these edits I have released a version (v1.0) of the software. Not releasing a version prior to review was an oversight that I can only ascribe to my lack of experience with the process. As the software is further developed we will continue to release versions following semantic versioning guidelines and with major releases being accompanied by appropriate publications. Hopefully this is sufficient to meet the requirement for "designed for maintainable extension".

Thank you again for taking the time for these comments and I look forward to the review process.

**Comment by DrDaveShaw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03110/joss.03110/10.21105.joss.03110.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03110/joss.03110/10.21105.joss.03110.pdf) :page_facing_up: :point_left:

**Comment by dhhagan** [comment]
@DrDaveShaw No worries! I'll look to find some reviewers now and hope to have them set within the week.

**Comment by dhhagan** [comment]
@whedon add @goldmanm as reviewer

**Comment by whedon** [comment]
OK, @goldmanm is now a reviewer

**Comment by dhhagan** [comment]
👋  Hey @annahodshire would you be interested in reviewing this paper?

**Comment by annahodshire** [comment]
@dhhagan my apologies for the slow response, I unfortunately do not have time at the moment due to prep for a panel review that's taking more time than expected... please keep me in mind in the future!

**Comment by dhhagan** [comment]
No worries, @annahodshire - thanks for considering!

**Comment by dhhagan** [comment]
:wave: Hey @khinsen, @vahtras, @chasemc, @dvalters - would one of you be available and interested in reviewing this manuscript and software?

**Comment by khinsen** [comment]
@dhhagan I can review this, but might take up to three weeks to complete it due to other commitments.

**Comment by dhhagan** [comment]
Hey @khinsen that shouldn't be an issue. Thanks so much.

**Comment by dhhagan** [comment]
@whedon add @khinsen as reviewer

**Comment by whedon** [comment]
OK, @khinsen is now a reviewer

**Comment by dhhagan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3224.
