### ISSUE TITLE
[PRE REVIEW]: statsExpressions: R Package for Tidy Dataframes and Expressions with Statistical Details

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3111]
**Submitting author:** @IndrajeetPatil (<a href="http://orcid.org/0000-0003-1995-6531">Indrajeet Patil</a>)
**Repository:** <a href="https://github.com/IndrajeetPatil/statsExpressions" target ="_blank">https://github.com/IndrajeetPatil/statsExpressions</a>
**Version:** 1.0.0
**Editor:** @mikldk
**Reviewers:** @humanfactors, @tomfaulkenberry
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @IndrajeetPatil. **Currently, there isn't an JOSS editor assigned** to your paper.

@IndrajeetPatil if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.19 s (379.5 files/s, 62590.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               34            658           1405           4388
Markdown                        10            466              0           1603
Rmd                              4            322            700            609
XML                              1              0              2            441
YAML                            11             83              7            422
JSON                             1              0              0            399
TeX                              1             27              0            144
CSS                              1              5              0             20
SVG                              8              0              0              8
-------------------------------------------------------------------------------
SUM:                            71           1561           2114           8034
-------------------------------------------------------------------------------


Statistical information for the repository 'edad175370fc19625aa0965d' was
gathered on 2021/03/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Indrajeet Patil                 18           704            704          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.02815 is OK
- 10.21105/joss.02445 is OK
- 10.5281/zenodo.3952174 is OK
- 10.21105/joss.01412 is OK
- 10.21105/joss.02306 is OK
- 10.5281/zenodo.2074621 is OK
- 10.21105/joss.01541 is OK
- 10.21105/joss.01686 is OK

MISSING DOIs

- 10.3758/s13428-019-01246-w may be a valid DOI for title: Robust Statistical Methods in R Using the WRS2 Package
- 10.31234/osf.io/yqxfr may be a valid DOI for title: The JASP guidelines for conducting and reporting a Bayesian analysis
- 10.32614/rj-2016-001 may be a valid DOI for title: metaplus: An R Package for the Analysis of Robust Meta-Analysis and Meta-Regression

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3111 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Indrajeet Patil, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@IndrajeetPatil - this PR should fix your paper compilation https://github.com/IndrajeetPatil/statsExpressions/pull/81

**Comment by arfon** [comment]
@whedon invite @karthik as editor

👋 @karthik - would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@karthik has been invited to edit this submission.

**Comment by IndrajeetPatil** [comment]
Potential reviewers:
- RMHogervorst
- cimentadaj
- njtierney
- humanfactors

Will suggest a few more if none of them can review the submission.

**Comment by karthik** [comment]
@arfon Currently don't have bandwidth to edit this but let me know if you can't find anyone else to take over.

**Comment by IndrajeetPatil** [comment]
@arfon Are we allowed to make suggestions about possible editors as well? If yes, I can suggest the following people:

- mikldk
- sbenthall

Will suggest a few more if none of them can edit the submission.

**Comment by IndrajeetPatil** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03111/joss.03111/10.21105.joss.03111.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03111/joss.03111/10.21105.joss.03111.pdf) :page_facing_up: :point_left:

**Comment by IndrajeetPatil** [comment]
Hi everyone, any update on the submission?

I have suggested both possible editors and reviewers. 
Please let me know if I can do anything else on my end to expedite the process. :)

**Comment by arfon** [comment]
@IndrajeetPatil - apologies for the slow progress here. As our existing editors are a little overloaded I'm going to mark this submission as `waitlisted` for now. As and when an editor becomes available, we'll go ahead and assign one.

**Comment by IndrajeetPatil** [comment]
Can this submission be reconsidered for review? 

Two of my other submissions (both `R` packages) at _JOSS_ were submitted after this submission and are already under review. So I am guessing someone might be available now to edit this submission?

**Comment by arfon** [comment]
> Two of my other submissions (both `R` packages) at JOSS were submitted after this submission and are already under review. So I am guessing someone might be available now to edit this submission?

Not necessarily so. Please be patient.

**Comment by arfon** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@IndrajeetPatil Thanks for your submission. Can you briefly describe how this package differs e.g. from [`broom`](https://github.com/tidymodels/broom)?

**Comment by IndrajeetPatil** [comment]
`statsExpressions` has wildly different goals than `broom`.

- `broom`: convert regression and other modeling **objects** to dataframes 
- `statsExpressions`: provide consistent syntax to run different tests and extract dataframes and expressions

So `statsExpressions` doesn't work with objects, but rather provides functions to carry out different types of analyses.

<img width="705" alt="Screenshot 2021-04-23 at 12 52 37" src="https://user-images.githubusercontent.com/11330453/115861265-e4dde700-a432-11eb-8013-08ce8f1010ae.png">

Additionally, it is more opinionated than `broom`. For example, `broom` won't add any other information than present in underlying objects (e.g., it doesn't add effect sizes and their confidence intervals), while `statsExpressions` does.

``` r
broom::tidy(t.test(mtcars$wt, mu = 3))
#> # A tibble: 1 x 8
#>   estimate statistic p.value parameter conf.low conf.high method     alternative
#>      <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl> <chr>      <chr>      
#> 1     3.22      1.26   0.218        31     2.86      3.57 One Sampl… two.sided

(df <- statsExpressions::one_sample_test(mtcars, wt, test.value = 3))
#> # A tibble: 1 x 11
#>      mu statistic df.error p.value method estimate conf.level conf.low conf.high
#>   <dbl>     <dbl>    <dbl>   <dbl> <chr>     <dbl>      <dbl>    <dbl>     <dbl>
#> 1     3      1.26       31   0.218 One S…    0.217       0.95   -0.129     0.566
#> # … with 2 more variables: effectsize <chr>, expression <list>
```

Additionally, `statsExpressions` provides dataframes containing expressions with statistical details. `broom` does no such thing.

```r
library(ggplot2)

ggplot(mtcars, aes(wt)) + geom_histogram()  + 
  labs(subtitle = df$expression[[1]])
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/ahSKR48.png)

<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Oh, forgot to say, thanks for accepting to edit this submission :)

**Comment by mikldk** [comment]
@IndrajeetPatil Thanks. I think it would be appropriate if `broom` was briefly mentioned in the paper and how this package differs from it.

A minor question from your example just given:

``` r
broom::tidy(t.test(mtcars$wt, mu = 3))
#> # A tibble: 1 x 8
#>   estimate statistic p.value parameter conf.low conf.high method     alternative
#>      <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl> <chr>      <chr>      
#> 1     3.22      1.26   0.218        31     2.86      3.57 One Sampl… two.sided

(df <- statsExpressions::one_sample_test(mtcars, wt, test.value = 3))
#> # A tibble: 1 x 11
#>      mu statistic df.error p.value method estimate conf.level conf.low conf.high
#>   <dbl>     <dbl>    <dbl>   <dbl> <chr>     <dbl>      <dbl>    <dbl>     <dbl>
#> 1     3      1.26       31   0.218 One S…    0.217       0.95   -0.129     0.566
#> # … with 2 more variables: effectsize <chr>, expression <list>
```

Wouldn't you expect that `one_sample_test()`'s `conf.low` / `conf.high` were centered around `mu` and not 0 (like `t.test()`)?

**Comment by IndrajeetPatil** [comment]
> I think it would be appropriate if broom was briefly mentioned in the paper and how this package differs from it.

Sure, I can do that.

> Wouldn't you expect that one_sample_test()'s conf.low / conf.high were centered around mu and not 0 (like t.test())?

The estimate is actually for Hedge's _g_, which you couldn't see since not all columns of the dataframe were printed.

``` r
options(tibble.width = Inf)
(df <- statsExpressions::one_sample_test(mtcars, wt, test.value = 3))
#> # A tibble: 1 x 11
#>      mu statistic df.error p.value method            estimate conf.level
#>   <dbl>     <dbl>    <dbl>   <dbl> <chr>                <dbl>      <dbl>
#> 1     3      1.26       31   0.218 One Sample t-test    0.217       0.95
#>   conf.low conf.high effectsize expression
#>      <dbl>     <dbl> <chr>      <list>    
#> 1   -0.129     0.566 Hedges' g  <language>
```

<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mikldk** [comment]
> The estimate is actually for Hedge's _g_, which you couldn't see since not all columns of the dataframe were printed.

Okay. Is it possible to also get `\hat{mu}` and confidence interval for `mu` similar to what `t.test()` outputs?

**Comment by IndrajeetPatil** [comment]
>  Is it possible to also get \hat{mu} and confidence interval for mu similar to what t.test() outputs?

Currently, no. The user can either get Hedge's _g_ or Cohen's _d_ for this test. If you want, I can add to the feature request list.

Usually, across different `type` arguments, there will just be one type of estimate available.

``` r
library(statsExpressions)
options(tibble.width = Inf)

one_sample_test(mtcars, wt, test.value = 3, type = "parametric")
#> # A tibble: 1 x 11
#>      mu statistic df.error p.value method            estimate conf.level
#>   <dbl>     <dbl>    <dbl>   <dbl> <chr>                <dbl>      <dbl>
#> 1     3      1.26       31   0.218 One Sample t-test    0.217       0.95
#>   conf.low conf.high effectsize expression
#>      <dbl>     <dbl> <chr>      <list>    
#> 1   -0.129     0.566 Hedges' g  <language>

one_sample_test(mtcars, wt, test.value = 3, type = "nonparametric")
#> # A tibble: 1 x 9
#>   statistic p.value method                    estimate conf.level conf.low
#>       <dbl>   <dbl> <chr>                        <dbl>      <dbl>    <dbl>
#> 1      5.77   0.308 Wilcoxon signed rank test    0.208       0.95   -0.249
#>   conf.high effectsize        expression
#>       <dbl> <chr>             <list>    
#> 1     0.578 r (rank biserial) <language>

one_sample_test(mtcars, wt, test.value = 3, type = "robust")
#> # A tibble: 1 x 9
#>   statistic p.value method                                 estimate conf.low
#>       <dbl>   <dbl> <chr>                                     <dbl>    <dbl>
#> 1      1.18    0.24 Bootstrap-t method for one-sample test     3.20     2.81
#>   conf.high conf.level effectsize   expression
#>       <dbl>      <dbl> <chr>        <list>    
#> 1      3.58       0.95 Trimmed mean <language>

one_sample_test(mtcars, wt, test.value = 3, type = "bayesian")
#> # A tibble: 2 x 13
#>   term       estimate conf.level conf.low conf.high    pd rope.percentage
#>   <chr>         <dbl>      <dbl>    <dbl>     <dbl> <dbl>           <dbl>
#> 1 Difference   -0.192       0.95   -0.534     0.173 0.859           0.274
#> 2 Cohens_d      3.19        0.95    2.29      4.06  1               0    
#>   prior.distribution prior.location prior.scale  bf10 method          expression
#>   <chr>                       <dbl>       <dbl> <dbl> <chr>           <list>    
#> 1 cauchy                          0       0.707 0.387 Bayesian t-test <language>
#> 2 cauchy                          0       0.707 0.387 Bayesian t-test <language>
```

<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mikldk** [comment]
> Potential reviewers:
> 
>     * RMHogervorst
> 
>     * cimentadaj
> 
>     * martinju
> 
>     * humanfactors
> 
> 

Can you please suggest a list where none have obvious conflicts of interest (I see that `cimentadaj` like you is at Max Planck Institute)?

**Comment by mikldk** [comment]
@RMHogervors, @martinju: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by IndrajeetPatil** [comment]
I think you meant @RMHogervorst?

**Comment by mikldk** [comment]
Indeed.

**Comment by martinju** [comment]
@mikldk Thanks for the suggestion, but I don't have time for at least a couple of weeks.

**Comment by mikldk** [comment]
@Prof-ThiagoOliveira: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by IndrajeetPatil** [comment]
@mikldk Here are a few other reviewer suggestions:
- Ohmaddi
- russellpierce
- mariacuellar
- tomfaulkenberry
- cimentadaj

**Comment by Prof-ThiagoOliveira** [comment]
Dear Mikkel,

I am afraid I have to reject review this paper because I don't have enough time to review it accordingly this and next month. I am happy to receive more invitations in a couple of months.

best regards,

Thiago
________________________________

**Comment by mikldk** [comment]
@Ohmaddi: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by IndrajeetPatil** [comment]
@mikldk Maybe we can invite a few others and check their availability? Let me know if I should suggest more reviewers.

**Comment by mikldk** [comment]
@mariacuellar @russellpierce @tomfaulkenberry @cimentadaj @humanfactors Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by humanfactors** [comment]
Happy to accept this review. Thanks for the information.

**Comment by mikldk** [comment]
@whedon add @humanfactors as reviewer

**Comment by whedon** [comment]
OK, @humanfactors is now a reviewer

**Comment by mikldk** [comment]
Thanks, @humanfactors . (We still need one more.)

**Comment by humanfactors** [comment]
@mikldk I would like to flag a potential perceived conflict of interest (i.e., to "avoid the appearance of conflicts of interest" as per JOSS policy). Both @IndrajeetPatil and I are members of the [easystats](https://easystats.github.io/blog/portfolio/) contributor list and we both were CRAN co-authors on the `bayestestR` package (https://cran.r-project.org/web/packages/bayestestR/index.html).

If this is perceived as a possible COI, I would request this COI is waived on the basis that:
- Indrajeet Patil and I have never co-authored a published manuscript, and do not have any prior or current collaborations related to publications. Nor do I see there to be any financial or academic benefits to me from this work that would prevent me from giving an impartial assessment of the work. 
- We are not personally or professionally antiquated 
- This project does not directly add to the easystats ecosystem

I place this here to be as thorough as possible and ensure I conform to policies.

**Comment by mikldk** [comment]
@humanfactors Thanks for flagging this. I agree that this is not a COI based on the description above.

**Comment by tomfaulkenberry** [comment]
@mikldk I'll be happy to review this.  Thanks!

**Comment by mikldk** [comment]
@whedon add @tomfaulkenberry as reviewer

**Comment by whedon** [comment]
OK, @tomfaulkenberry is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3236.
