### ISSUE TITLE
[PRE REVIEW]: `bwsample`: Processing Best-Worst Scaling data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3112]
**Submitting author:** @ulf1 (<a href="http://orcid.org/0000-0002-0440-4868">Ulf Hamster</a>)
**Repository:** <a href="https://github.com/satzbeleg/bwsample" target ="_blank">https://github.com/satzbeleg/bwsample</a>
**Version:** 0.6.0
**Editor:** @mikldk
**Reviewers:** @ejhigson, @jakryd
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ulf1. **Currently, there isn't an JOSS editor assigned** to your paper.

@ulf1 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (390.5 files/s, 58606.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          19            432            757           1348
Markdown                         3             85              0            230
Jupyter Notebook                 3              0           1377            108
TeX                              1              7              0             94
YAML                             3              5              0             42
JSON                             1              0              0             18
-------------------------------------------------------------------------------
SUM:                            30            529           2134           1840
-------------------------------------------------------------------------------


Statistical information for the repository '4057eae9665580b1e86a204f' was
gathered on 2021/03/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
UH                              58          3475            938          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
UH                         2537           73.0          0.4                7.45
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1177/074391569201100202 is OK
- 10.1016/S0377-2217(02)00227-8 is OK
- 10.1214/aos/1079120141 is OK
- 10.31219/osf.io/qkxej is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03112/joss.03112/10.21105.joss.03112.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03112/joss.03112/10.21105.joss.03112.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
Thanks for your submission to JOSS @ulf1. Unfortunately all of our editors in this area are very busy right now so I've added this paper to the waitlist.

**Comment by ulf1** [comment]
Hello @arfon I moved the repository into a new organisation but couldn't change URL anymore. The new location is https://github.com/satzbeleg/bwsample 
Is there a way to change the path?

**Comment by arfon** [comment]
> Is there a way to change the path?

Yep, I've gone ahead and done that for you.

**Comment by danielskatz** [comment]
👋 @mikldk - Would you be able to edit this submission?  It might be a little outside of your core area, but it's been waiting a while, and I think you might be able to handle it.

**Comment by danielskatz** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@ulf1 - thank you for the submission.

Do you have any suggestions for reviewers ([here](https://bit.ly/joss-reviewers) is a list of potential reviewers)?

**Comment by ulf1** [comment]
Hello @mikldk 
maybe rasbt, desilinguist, ahurriyetoglu, betatim, yxoos, or apiad

**Comment by mikldk** [comment]
@rasbt, @desilinguist: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by desilinguist** [comment]
If this can wait until first week of June, I can probably do it.

**Comment by rasbt** [comment]
Sorry, I currently have a large backlog of reviews (JOSE, ICCV, and upcoming NeurIPS) in the next weeks/months and shouldn't add more to my plate right now. I am happy to check back mid-July though in case an additional reviewer is needed

**Comment by mikldk** [comment]
@ahurriyetoglu, @betatim: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by mikldk** [comment]
@yxoos, @apiad: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by apiad** [comment]
I'm glad to review, but in the next couple of weeks I'm gonna be busy, so I'll do it slowly if that's OK.

**Comment by mikldk** [comment]
@stsievert, @ejhigson: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by ejhigson** [comment]
I'm happy to review this!

**Comment by mikldk** [comment]
@whedon assign @ejhigson as reviewer

**Comment by whedon** [comment]
OK, @ejhigson is now a reviewer

**Comment by stsievert** [comment]
My apologies @mikldk, but I'll have to decline. I don't have the bandwidth right now.

**Comment by mikldk** [comment]
@GregoryAshton: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by GregoryAshton** [comment]
Hi @mikldk, I'm not able to commit to reviews at the moment due to other commitments. I'll be available in a month or so. Apologies.

**Comment by mikldk** [comment]
@jakryd: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by jakryd** [comment]
Hello @mikldk, I would be happy to.

**Comment by mikldk** [comment]
@whedon add @jakryd as reviewer

**Comment by whedon** [comment]
OK, @jakryd is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3324.
