### ISSUE TITLE
[PRE REVIEW]: Analysis of Prehistoric Iconography with the R package iconr

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3113]
**Submitting author:** @zoometh (<a href="http://orcid.org/0000-0002-1112-6122">Huet Thomas</a>)
**Repository:** <a href="https://github.com/zoometh/iconr" target ="_blank">https://github.com/zoometh/iconr</a>
**Version:** v0.1.0
**Editor:** @hugoledoux
**Reviewers:** @fbiljecki, @benmarwick
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @zoometh. **Currently, there isn't an JOSS editor assigned** to your paper.

@zoometh if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.60 s (131.0 files/s, 27166.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            27           1332            286           8832
Rmd                              9            605            994            833
R                               15             58            262            796
CSS                              4            153             53            641
Markdown                         5            175              0            321
JavaScript                       5             64             34            274
XML                              5              0              0            182
TeX                              3             13              0            118
YAML                             4             19              9            111
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            78           2419           1639          12119
-------------------------------------------------------------------------------


Statistical information for the repository '9bd6114fb887d97b9bb50f54' was
gathered on 2021/03/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Shennan                          4           436              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Shennan                     436          100.0          0.0                9.63
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.11588/propylaeumdok.00000512 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03113/joss.03113/10.21105.joss.03113.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03113/joss.03113/10.21105.joss.03113.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@zoometh – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by zoometh** [comment]
@arfon Yes, [iconr](https://cran.r-project.org/web/packages/iconr/index.html) package LOC can < 1000, but the theoretical background is innovative and voluntarily parsimonious because the package should be at the root of different implementations. Best,

**Comment by kthyng** [comment]
Hi @zoometh! The editorial board has determined that your submission is in scope.

We will have to ask for your patience, though, as we have a backlog of submissions and our relevant editors are already overbooked with submissions. I will add the waitlist label now.

**Comment by danielskatz** [comment]
👋 @hugoledoux - are you able to take on another submission to edit at this point?

**Comment by danielskatz** [comment]
@whedon invite @hugoledoux as editor

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by hugoledoux** [comment]
@whedon assign @hugoledoux as reviewer

**Comment by whedon** [comment]
You need to assign an editor first.

**Comment by hugoledoux** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by whedon** [comment]
OK, @fbiljecki is now a reviewer

**Comment by hugoledoux** [comment]
@whedon add @benmarwick as reviewer

**Comment by whedon** [comment]
OK, @benmarwick is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3191.
