### ISSUE TITLE
[PRE REVIEW]: GORILLA: Guiding-center ORbit Integration with Local Linearization Approach

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3116]
**Submitting author:** @micheder (<a href="http://orcid.org/0000-0002-1392-1664">Michael Eder</a>)
**Repository:** <a href="https://github.com/itpplasma/GORILLA" target ="_blank">https://github.com/itpplasma/GORILLA</a>
**Version:** v1.0
**Editor:** @dpsanders
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @micheder. **Currently, there isn't an JOSS editor assigned** to your paper.

@micheder if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1063/5.0022117 is OK
- 10.5281/zenodo.4593661 is OK
- 10.1017/S002237780000060X is OK
- 10.1063/1.863080 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.71 s (97.2 files/s, 43009.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                      43           1136           9297          14626
TeX                              4            218            115           1600
MATLAB                          12            524           1049           1256
Markdown                         3             77              0            276
Python                           4             64             60             90
make                             1              8              0             64
YAML                             2              8              9             51
-------------------------------------------------------------------------------
SUM:                            69           2035          10530          17963
-------------------------------------------------------------------------------


Statistical information for the repository '5938276bc84ad2974e5caee3' was
gathered on 2021/03/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Michael Eder                     2           215              1          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael Eder                214           99.5          0.0               15.89
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03116/joss.03116/10.21105.joss.03116.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03116/joss.03116/10.21105.joss.03116.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@micheder - many thanks for your review here. Unfortunately the editor best-placed to edit this submission is currently very busy so I'm going to add this to the backlog of 'waitlisted' submissions. Hopefully this won't be too long.

**Comment by micheder** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by micheder** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by micheder** [comment]
We would kindly like to suggest the following potential reviewers:
* sigvaldm
* Christovis
* ketch
* vickysharma0812
* robashaw

**Comment by kthyng** [comment]
@dpsanders could you take on this submission?

**Comment by kthyng** [comment]
@whedon invite @dpsanders as editor

**Comment by whedon** [comment]
@dpsanders has been invited to edit this submission.

**Comment by dpsanders** [comment]
Yes I can take it.

**Comment by dpsanders** [comment]
@whedon assign @dpsanders as editor

**Comment by whedon** [comment]
OK, the editor is @dpsanders

**Comment by micheder** [comment]
@dpsanders May we politely ask, if we can support the editorial process?

**Comment by micheder** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03116/joss.03116/10.21105.joss.03116.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03116/joss.03116/10.21105.joss.03116.pdf) :page_facing_up: :point_left:

**Comment by dpsanders** [comment]
👋 @micheder: Apologies for the delay.

Could you please add a section in the paper comparing your software to the other available software packages that solve the same problem?

**Comment by dpsanders** [comment]
@micheder: I don't see any information about automated tests to make sure the code is running correctly.

**Comment by dpsanders** [comment]
@micheder: I also don't see narrative documentation explaining the use of the package.

**Comment by dpsanders** [comment]
@micheder: Is the MATLAB code runnable in Octave? If not, it would be great to make sure that it can be used in a totally open-source environment, and/or replicate the MATLAB examples in Python.

Providing automated installation scripts in addition to the manual instructions would also be very useful.

**Comment by micheder** [comment]
> 👋 @micheder: Any update here?

Unfortunately, I was very busy with another project in these days. You can expect changes in the upcoming weeks.
I will comment here, when all your suggestions are implemented.

**Comment by arfon** [comment]
@whedon remind @arfon in two weeks

@micheder - any update here? If this submission isn't ready for review in the next couple of weeks I propose rejecting at this point and encouraging a future re-submission when ready.

**Comment by whedon** [comment]
Sorry, I can't set reminders on PRE-REVIEW issues.

**Comment by micheder** [comment]
We would like to apologize for the unexpected delay.
Unfortunately, separate ongoing projects and the summer holidays have caused this delay.
However, we would still like to implement the suggestions.
We expect to be able to finish the implementations in October.

Please, decide whether it is better to keep the submission open or reject at this point and we re-submit in October.

We are sorry for the caused inconvenience.

**Comment by arfon** [comment]
>  Please, decide whether it is better to keep the submission open or reject at this point and we re-submit in October.

No problem, thanks for the update. I think we'll proceed with the rejection now but would welcome a resubmission later once this feedback has been addressed.

On resubmission, please mention that this is a resubmission in the submission form. Thanks!

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
