### ISSUE TITLE
[PRE REVIEW]: arrgh: a Go interface to the OpenCPU R server system

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#312]
**Submitting author:** @kortschak (<a href="http://orcid.org/0000-0001-8295-2301">Robert Daniel Kortschak</a>)
**Repository:** <a href="https://github.com/kortschak/arrgh" target ="_blank">https://github.com/kortschak/arrgh</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @brentp

**Author instructions**

Thanks for submitting your paper to JOSS @kortschak. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

kortschak if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @acabunoc - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](http://joss.theoj.org/about#paper_structure) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by kortschak** [comment]
I am confused, the paper clearly states that the package is intended to be used for interfacing with R, which is primarily a research software. The paper also explains why this would be useful, in that Go is a good language for performing scientific analyses for many reasons, but that R provides a much richer statistical analysis support base and so use the two together is a benefit:

>Go is a simple statically typed compiled language that provides many benefits for scientific computing. However, Go currently lacks the rich statistical analysis tools available in R. So an interface between R and Go would allow building analytical tools utilising the simplicity and high performance of Go and the statistical analysis tools available within R.

**Comment by kortschak** [comment]
To give an explicit use case (hypothetical), if a person wanted to perform a genomics analysis using Go and the [bíogo ncbi package](http://joss.theoj.org/papers/10.21105/joss.00234) (interestingly built around the same server/client model as the arrgh package) requiring some statistical analysis, it may be necessary to use R. The arrgh package would facilitate this analysis. The need for statistical analysis to support research seemed so obvious to me that I did not include any text to justify it; should I?

**Comment by pjotrp** [comment]
@kortschak it will be good to give an example of use in research context. @arfon I can be the editor.

**Comment by kortschak** [comment]
I am teaching at the moment and this will take some time to put together, but it does honestly strike me as very odd. These are two languages that are used for scientific research, with different strengths that can, if interfaced, strengthen each other.

**Comment by arfon** [comment]
> I am teaching at the moment and this will take some time to put together, but it does honestly strike me as very odd. These are two languages that are used for scientific research, with different strengths that can, if interfaced, strengthen each other.

Hi @kortschak. We've been discussing this submission as an editorial board and the primary concern we have is that this submission falls into the 'utility package' category (http://joss.theoj.org/about#submission_requirements). We definitely understand the potential value of connecting these two languages, we're simply looking for an illustration of this for the reader. Better yet, if you have used this in some of your own ongoing research then cite that too.

**Comment by pjotrp** [comment]
@kortschak Dan, take a look at the RPy2 paper. https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-S12-S11

**Comment by kortschak** [comment]
@pjotrp I'm not sure what I should take from that. The two approaches are very different, reflecting the differences in the underpinning philosophies of python and Go, and also reflects the differences in approaches to performance optimisation seen in the two languages; the package use example of edger in figure 3 would be an anti-pattern in Go because of the heavy inter-process communication purely for the purpose of retaining the data in the python space. It is also difficult for me to distinguish the packages there from what @arfon describes here as a 'utility package'. The RPy2 packages do things that in my work would be done purely in R, and serve only to wrap that in a different syntax.

I will write up an example of a graph structure analysis where the graph statistics are generated in Go using packages in the gonum graph suite and the statistical analysis and plotting is done using arrgh to interface to R. If this plan is satisfactory, then I can move ahead, otherwise I am at a loss with how to move this forward, and would continue to be confused given other paper that have been moved onto review/published here recently that IMO sit squarely in the same space.

**Comment by arfon** [comment]
> I will write up an example of a graph structure analysis where the graph statistics are generated in Go using packages in the gonum graph suite and the statistical analysis and plotting is done using arrgh to interface to R. If this plan is satisfactory, then I can move ahead, otherwise I am at a loss with how to move this forward, and would continue to be confused given other papers that have been moved onto review/published here recently that IMO sit squarely in the same space.

Thanks @kortschak. I realize there many be some apparent inconsistencies in editorial policy - this is because we've recently updated our submission guidelines (see https://github.com/openjournals/joss/pull/307).

**Comment by pjotrp** [comment]
Hey Dan. We are all volunteers. Please appreciate that. All good intentions. I am with you that we should push forward. The idea of a GO graph is very good.

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@kortschak ping me when you are ready and I'll look for a reviewer. Since you have published with JOSS before I trust you to be ready at some point.

**Comment by kortschak** [comment]
Thanks for the patience @pjotrp, I will let you know when I have the worked up examples as a PR.

**Comment by kortschak** [comment]
@pjotrp *ping*

I have a [PR adding a more fleshed out example usage](https://github.com/kortschak/arrgh/pull/8).

**Comment by pjotrp** [comment]
Thanks. I'll start asking around for a reviewer.

**Comment by pjotrp** [comment]
@brentp would you mind reviewing this submission? Or suggest someone who would be interested in using R from Go?

**Comment by brentp** [comment]
yes, I can review.

**Comment by pjotrp** [comment]
@whedon assign @brentp as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @brentp

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/517. Feel free to close this issue now!
