### ISSUE TITLE
[PRE REVIEW]: Surfaxe: Systematic surface calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3123]
**Submitting author:** @brlec (<a href="http://orcid.org/0000-0003-1485-1888">Katarina Brlec</a>)
**Repository:** <a href="https://github.com/SMTG-UCL/surfaxe" target ="_blank">https://github.com/SMTG-UCL/surfaxe</a>
**Version:** v1.1
**Editor:** @danielskatz
**Reviewers:** @pzarabadip, @eihernan
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @brlec. **Currently, there isn't an JOSS editor assigned** to your paper.

@brlec if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/cpe.3505 is OK
- 10.1016/j.commatsci.2012.10.028 is OK
- 10.1088/1361-648X/aa680e is OK
- 10.21105/joss.01944 is OK
- 10.1016/j.commatsci.2020.110086 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=17.79 s (3.9 files/s, 67356.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              8              0              0        1191898
Python                          27            629            936           2272
JSON                             3              0              0            360
reStructuredText                10             74            106            147
Markdown                         2             72              0            145
YAML                            13              4              0            117
Jupyter Notebook                 4              0           1436            102
TeX                              1              3              0             78
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            70            794           2486        1195154
-------------------------------------------------------------------------------


Statistical information for the repository '1e7849f55932cf376e4878e7' was
gathered on 2021/03/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dan Davies                       3            93              2            0.91
Daniel Davies                   29           200             96            2.83
Sean Kavanagh                    1             1              1            0.02
brlec                          104          6685           3376           96.24

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dan Davies                  214          230.1          4.1               16.36
brlec                      3623           54.2          2.9                7.09
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03123/joss.03123/10.21105.joss.03123.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03123/joss.03123/10.21105.joss.03123.pdf) :page_facing_up: :point_left:

**Comment by brlec** [comment]
Hi, our suggested reviewers are arosen and pzarabadip

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @pibion as editor

**Comment by whedon** [comment]
@pibion has been invited to edit this submission.

**Comment by pibion** [comment]
@Kevin-Mattheus-Moerman I'd be happy to take this but wanted to caution that I'm a little slow right now as I've got several papers whose reviewers have gone quiet and it's been unusually time-consuming to find new folks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@pibion that is fine. We now tag submissions as "waitlisted" if we feel the editors need time before they can commit fully to the submission. I can do two things, so let me know if you prefer A or B, option A) I could assign you here as editor and add the waitlisted label which you can remove once you have time to take this up, or B) I could not assign you yet and keep this waitlisted for when you are ready to be assigned (that way it doesn't show up on your list yet and may prevent that feeling of pressure).

**Comment by Kevin-Mattheus-Moerman** [comment]
@pibion I'll set this as waitlisted for now and look forward to having you help with this submission once you have the time to take it on.

**Comment by danielskatz** [comment]
@pibion - I'll go ahead and take this one

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @arosen & @pzarabadip - would one or both of you be willing to review this submission for JOSS?

**Comment by pzarabadip** [comment]
Hi @danielskatz I'd be happy to review this submission.

**Comment by danielskatz** [comment]
Thanks very much @pzarabadip  - I'll add you as a reviewer, but we won't actually start the review until we get at least one more reviewer as well

**Comment by danielskatz** [comment]
@whedon assign @pzarabadip as reviewer

**Comment by whedon** [comment]
OK, @pzarabadip is now a reviewer

**Comment by danielskatz** [comment]
👋 @eihernan - thanks for agreeing to review this submission.  I'll add you, and we'll start the review.

**Comment by danielskatz** [comment]
@whedon add @eihernan as reviewer

**Comment by whedon** [comment]
OK, @eihernan is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3171.
