### ISSUE TITLE
[PRE REVIEW]: HyRiver: Hydroclimate Data Retriever

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3128]
**Submitting author:** @cheginit (<a href="http://orcid.org/0000-0002-5430-6000">Taher Chegini</a>)
**Repository:** <a href="https://github.com/cheginit/HyRiver" target ="_blank">https://github.com/cheginit/HyRiver</a>
**Version:** v0.10.x
**Editor:** @kthyng
**Reviewers:** @evanleeturner, @raoulcollenteur
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @cheginit. **Currently, there isn't an JOSS editor assigned** to your paper.

@cheginit if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3334/ORNLDAAC/1840 is OK
- 10.3133/fs20193051 is OK
- 10.3133/fs20203033 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (213.7 files/s, 30670.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          11            234            380            652
reStructuredText                12            229            212            557
Jupyter Notebook                 9              0           2997            494
YAML                             7             23             16            219
SVG                              1              0              0            162
Markdown                         1             10              0            113
make                             2             17              9             70
DOS Batch                        1              8              1             26
TeX                              1              2              0             26
-------------------------------------------------------------------------------
SUM:                            45            523           3615           2319
-------------------------------------------------------------------------------


Statistical information for the repository '61baca6992fd3d7af918d51c' was
gathered on 2021/03/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
cheginit                         6         18137          16871          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
cheginit                   1266            7.0          0.0               29.38
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03128/joss.03128/10.21105.joss.03128.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03128/joss.03128/10.21105.joss.03128.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @kthyng as editor

**Comment by whedon** [comment]
@kthyng has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@kthyng note this submission is for a "stack" of six python projects (the above repository data and lines of code estimates etc are therefore only for the collection repository).

**Comment by cheginit** [comment]
I went through the list of reviewers and found the interests of these users relevant to this package:
Ziqi-Li, raoulcollenteur, mdbartos, arbennett, and kmarkert

**Comment by cheginit** [comment]
@kthyng, as @Kevin-Mattheus-Moerman mentioned the above lines of code is only for the collection repo, here's a summary of lines of code (only the main files) for each package using `cloc`:
```bash
❯ for f in $(ls -d1 py*/py*/);do echo $f && cloc $f; done
py3dep/py3dep/
       6 text files.
       4 unique files.                              
       2 files ignored.

github.com/AlDanial/cloc v 1.89  T=0.01 s (318.3 files/s, 38752.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4             75            149            263
-------------------------------------------------------------------------------
SUM:                             4             75            149            263
-------------------------------------------------------------------------------
pydaymet/pydaymet/
       7 text files.
       5 unique files.                              
       2 files ignored.

github.com/AlDanial/cloc v 1.89  T=0.02 s (249.6 files/s, 91717.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5            287            508           1042
-------------------------------------------------------------------------------
SUM:                             5            287            508           1042
-------------------------------------------------------------------------------
pygeohydro/pygeohydro/
      12 text files.
       8 unique files.                              
       4 files ignored.

github.com/AlDanial/cloc v 1.89  T=0.02 s (427.6 files/s, 74192.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           8            242            281            865
-------------------------------------------------------------------------------
SUM:                             8            242            281            865
-------------------------------------------------------------------------------
pygeoogc/pygeoogc/
      13 text files.
      10 unique files.                              
       3 files ignored.

github.com/AlDanial/cloc v 1.89  T=0.03 s (338.9 files/s, 114360.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            531            962           1853
YAML                             1              3              0             25
-------------------------------------------------------------------------------
SUM:                            10            534            962           1878
-------------------------------------------------------------------------------
pygeoutils/pygeoutils/
       7 text files.
       7 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.89  T=0.02 s (362.5 files/s, 87359.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           7            281            369           1037
-------------------------------------------------------------------------------
SUM:                             7            281            369           1037
-------------------------------------------------------------------------------
pynhd/pynhd/
      10 text files.
       6 unique files.                              
       4 files ignored.

github.com/AlDanial/cloc v 1.89  T=0.02 s (314.6 files/s, 82000.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           6            252            481            831
-------------------------------------------------------------------------------
SUM:                             6            252            481            831
-------------------------------------------------------------------------------
```

And here's the combined summary:
```bash
❯ for f in $(ls -d1 py*/py*/);do cloc --out $(basename $f).txt $f; done
❯ cloc --sum-reports --out=hyriver.txt *.txt
❯ cat hyriver.txt.lang
github.com/AlDanial/cloc v 1.89
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          39           1668           2750           5891
YAML                             1              3              0             25
-------------------------------------------------------------------------------
SUM:                            40           1671           2750           5916
-------------------------------------------------------------------------------
```

Please let me know if more info is needed.

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
@cheginit sorry for my delay! I'll be handling your submission as editor. I'll pick this up next week.

**Comment by cheginit** [comment]
@kthyng no problem, thank you. Looking forward to it!

**Comment by kthyng** [comment]
@evanleeturner I hope things are going well with you! Are you interested in reviewing this submission to JOSS? As a reminder, you can read about the process [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and we are asking for reviews to be finished within about 4-6 weeks but since it is often an iterative process, you would want to start sooner than that. Thanks for your consideration.

**Comment by kthyng** [comment]
Hi @kmarkert are you interested in reviewing this submission for the Journal of Open Source Software? You can read about the process [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and we are asking for reviews to be finished within about 4-6 weeks but since it is often an iterative process, you would want to start sooner than that. Thanks for your consideration.

**Comment by kthyng** [comment]
(pinged both potential reviewers by email)

**Comment by evanleeturner** [comment]
I have agreed to review this submission!  -evan

**Comment by kthyng** [comment]
@whedon assign @evanleeturner as reviewer

**Comment by whedon** [comment]
OK, @evanleeturner is now a reviewer

**Comment by kthyng** [comment]
Hi @raoulcollenteur! Are you interested in reviewing this submission for the Journal of Open Source Software? You can read about the process [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and we are asking for reviews to be finished within about 4-6 weeks but since it is often an iterative process, you would want to start sooner than that. Thanks for your consideration.

**Comment by raoulcollenteur** [comment]
Happy to help, agree to review!

**Comment by kthyng** [comment]
@raoulcollenteur awesome! Ok I'll get things rolling then.

**Comment by kthyng** [comment]
@whedon add @raoulcollenteur as reviewer

**Comment by whedon** [comment]
OK, @raoulcollenteur is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3175.

**Comment by kthyng** [comment]
@evanleeturner and @raoulcollenteur please head over to #3175 for the actual review issue, and let me know if you have any questions!
