### ISSUE TITLE
[PRE REVIEW]: Synch: A framework for concurrent data-structures and benchmarks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3129]
**Submitting author:** @nkallima (<a href="http://orcid.org/0000-0002-0331-1475">Nikolaos D. Kallimanis</a>)
**Repository:** <a href="https://github.com/nkallima/sim-universal-construction" target ="_blank">https://github.com/nkallima/sim-universal-construction</a>
**Version:** v2.3.1
**Editor:** @danielskatz
**Reviewers:** @hkaiser, @jarrah42
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @nkallima. **Currently, there isn't an JOSS editor assigned** to your paper.

@nkallima if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.18 s (625.0 files/s, 43313.5 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
C                                60            777             58           4435
C/C++ Header                     39            283             75           1155
Bourne Shell                      4             45             24            366
Markdown                          6            129              0            347
YAML                              3              6              1            149
Bourne Again Shell                1              4              3             19
make                              1              7              0             18
--------------------------------------------------------------------------------
SUM:                            114           1251            161           6489
--------------------------------------------------------------------------------


Statistical information for the repository 'd0cd11ca31397ce695145a7a' was
gathered on 2021/03/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nick Kallimanis                 23           636            462            2.24
Nikolaos D. Kalliman            61          2295           1666            8.08
Nikolaos Kallimanis              3          5629           9803           31.48
Spyridon N. Agathos              3            27            170            0.40
nkallima                        25         10594           8774           39.51
nkallima@gmail.com               7          8751            218           18.29

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Nick Kallimanis              16            2.5          5.5                0.00
Nikolaos D. Kalliman       2077           90.5          3.5                2.79
Spyridon N. Agathos          89          329.6          4.2                1.12
nkallima                   4510           42.6         38.0                1.57
nkallima@gmail.com           91            1.0         99.6                5.49
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3129 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03129/joss.03129/10.21105.joss.03129.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03129/joss.03129/10.21105.joss.03129.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @danielskatz  as editor

**Comment by whedon** [comment]
@danielskatz has been invited to edit this submission.

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @nkallima - I'll be your editor.

1. Can you suggest any potential reviewers by mentioning them here in this thread (without tagging them with an @)? [This list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
2. Also, can you help me understand the authorship? It looks like you are the only author, but I see multiple contributors in the  repository.

**Comment by nkallima** [comment]
@danielskatz – Thank you for handling the paper.
I checked the list of the reviewers and judging from the domains/topic areas, a list of potential reviewers could be the following:
-	Kanirudh
-	Jpenuchot
-	jarrah42
-	cedricchevalier19

Most of the content on this repository is an extension of my research on concurrent data-structures/algorithms and performance evaluation performed in the last decade. Recently, my colleague Spiros Agathos used the software extensively and gently contributed a few patches/fixes. Moreover, Eftychia Datsika (edatsika) improved the logo of the repository. I acknowledge Spiros and Eftychia in the Acknowledgment section of the paper.

**Comment by danielskatz** [comment]
👋 @Kanirudh - would you be able to review this submission for JOSS?

**Comment by danielskatz** [comment]
👋 @Jpenuchot - would you be able to review this submission for JOSS?

**Comment by danielskatz** [comment]
👋 @hkaiser - Would you be willing to review this submission for JOSS?  We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by hkaiser** [comment]
> 👋 @hkaiser - Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

I can try reviewing the paper.

**Comment by danielskatz** [comment]
Thanks - I'll add you in the system, but the review won't start until we get one more reviewer as well

**Comment by danielskatz** [comment]
@whedon assign @hkaiser as reviewer

**Comment by whedon** [comment]
OK, @hkaiser is now a reviewer

**Comment by danielskatz** [comment]
👋 @jarrah42 - would you be able to review this submission for JOSS?

**Comment by danielskatz** [comment]
👋 @cedricchevalier19 - would you be able to review this submission for JOSS?

**Comment by danielskatz** [comment]
👋 @mkaguilera - Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews of the software and paper here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by danielskatz** [comment]
👋 @icalciu - Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews of the software and paper here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by danielskatz** [comment]
👋 @jamesreinders - Would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews of the software and paper here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by jarrah42** [comment]
@danielskatz yes I can look at this.

**Comment by danielskatz** [comment]
Great - thanks for agreeing to another one @jarrah42 !  I'll add you and start the review

**Comment by danielskatz** [comment]
@whedon add @jarrah42 as reviewere

**Comment by whedon** [comment]
OK, @jarrah42 is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3143.
