### ISSUE TITLE
[PRE REVIEW]: PlateReaderDataAnalyzer: a SAAS service to compute growth rates based on plate reader collected data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#313]
**Submitting author:** @uriba (<a href="http://orcid.org/0000-0002-3097-9681">Uri Barenholz</a>)
**Repository:** <a href="https://github.com/uriba/PlateReaderDataAnalyzer" target ="_blank">https://github.com/uriba/PlateReaderDataAnalyzer</a>
**Version:** v0.0.1
**Editor:** @arfon
**Reviewer:** @pboesu

**Author instructions**

Thanks for submitting your paper to JOSS @uriba. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@uriba if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by uriba** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by uriba** [comment]
Potential reviewers from the list are jsta and pboesu
Other potential reviewer is Avi Flamholz (
https://www.linkedin.com/in/avi-flamholz-32841b2/)

**Comment by arfon** [comment]
👋 @pboesu - would you be willing to review this submission for JOSS?

**Comment by pboesu** [comment]
I am willing to review this contribution.

**Comment by arfon** [comment]
> I am willing to review this contribution.

Wonderful, many thanks!

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @pboesu as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pboesu

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/381. Feel free to close this issue now!

**Comment by arfon** [comment]
@pboesu @uriba - see you both over in #381 for the actual review.
