### ISSUE TITLE
[PRE REVIEW]: Ceiba: A web service to handle scientific simulation data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3130]
**Submitting author:** @felipeZ (<a href="http://orcid.org/0000-0001-8286-677X">felipe zapata ruiz</a>)
**Repository:** <a href="https://github.com/nlesc-nano/ceiba" target ="_blank">https://github.com/nlesc-nano/ceiba</a>
**Version:** v1.0.0
**Editor:** @majensen
**Reviewers:** @junjun-zhang, @dimitridarras
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @felipeZ. **Currently, there isn't an JOSS editor assigned** to your paper.

@felipeZ if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (378.8 files/s, 23603.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          18            358            412            771
GraphQL                          2             11              0            269
reStructuredText                12             99             29            252
Markdown                         2             59              0            219
TeX                              1             21              0            195
YAML                             7             36              9            168
JSON                             1              0              0             43
DOS Batch                        1              8              1             27
Bourne Shell                     2              4              0             13
make                             1              4              6             10
Dockerfile                       1              7              0              9
CSS                              1              2              3              8
-------------------------------------------------------------------------------
SUM:                            49            609            460           1984
-------------------------------------------------------------------------------


Statistical information for the repository 'a4fa9abd7d9c007264e15c76' was
gathered on 2021/03/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
felipez                         96          2503            962          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
felipez                    1541           61.6          3.6               15.57
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3130 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (78c0a0709d59255d5d01c42a/paper/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 13 column 12 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@felipeZ thank you for this submission. I have just flagged this work for additional scope review by our editorial board. This is typical for works presenting with <1000 lines of code. We will review if this work conforms to our  ["substantial scholarly effort" requirements](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). The scope review should take about a week.

**Comment by felipeZ** [comment]
@Kevin-Mattheus-Moerman thanks for letting me know. Please note that the repository from which I submitted the paper only contains the web service back-end, the client code is hosted in another repository called [Ceiba-CLI](https://github.com/nlesc-nano/ceiba-cli). Both the back-end and the client are part of the web service presented in the publication.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3130 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (661f38b24c9dad2bf1895989/paper/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 13 column 12 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by kthyng** [comment]
@felipeZ I think the paper is not generating because of the tab highlighted in red here: https://github.com/nlesc-nano/ceiba/blob/main/paper/paper.md. PLease fix that.

The editorial board has decided this is in scope, when reviewed together with the CLI package.

**Comment by kthyng** [comment]
@majensen Would you be able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @majensen as editor

**Comment by whedon** [comment]
@majensen has been invited to edit this submission.

**Comment by felipeZ** [comment]
@kthyng thanks for let me know! I am changing it now

**Comment by felipeZ** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03130/joss.03130/10.21105.joss.03130.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03130/joss.03130/10.21105.joss.03130.pdf) :page_facing_up: :point_left:

**Comment by majensen** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
Looks like an interesting approach, happy to handle this

**Comment by majensen** [comment]
@junjun-zhang would you have time to review [this work](#3130) for JOSS? No pressure- I know you just recently helped us out.

**Comment by junjun-zhang** [comment]
@majensen yes, happy to review it

**Comment by majensen** [comment]
@whedon assign @junjun-zhang as reviewer

**Comment by whedon** [comment]
OK, @junjun-zhang is now a reviewer

**Comment by majensen** [comment]
Hi @vsoch -- would you have time and inclination to review [this work](#3130) for [JOSS](https://joss.theoj.org)? Your expertise and experience would be very much appreciated! 
Thanks for considering --@majensen

**Comment by vsoch** [comment]
hey @majensen ! I'm in a new job for a few months, so I'd need to check if this is okay with my supervisor. I think likely I'd need to do it on my own time on a weekend, so please reach out to other potential reviewers and don't wait for me if you want to get it started sooner than later.

**Comment by majensen** [comment]
Thanks @vsoch, will do. Really appreciate your consideration!

**Comment by majensen** [comment]
All, will be inviting other reviewers in next day or so, thanks for your patience!

**Comment by majensen** [comment]
All, @dimitridarras has graciously agreed to review this work. Will assign him and then move to the full review.

**Comment by majensen** [comment]
@whedon add @dimitridarras as reviewer

**Comment by whedon** [comment]
OK, @dimitridarras is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3197.
