### ISSUE TITLE
[PRE REVIEW]: Assessment, Testing and Comparison of Statistical Models using R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3132]
**Submitting author:** @strengejacke (<a href="http://orcid.org/0000-0002-8895-3206">Daniel Lüdecke</a>)
**Repository:** <a href="https://github.com/easystats/performance" target ="_blank">https://github.com/easystats/performance</a>
**Version:** 0.7.1
**Editor:** @mikldk
**Reviewers:** @martinju, @gjo11
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @strengejacke. **Currently, there isn't an JOSS editor assigned** to your paper.

@strengejacke if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.18 s (757.3 files/s, 95434.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                              119           2293           3626           6563
XML                              1              0             42           1484
Markdown                         6            504              0           1137
YAML                             3             37              2            229
TeX                              1             29              0            194
Rmd                              3            156            308            156
-------------------------------------------------------------------------------
SUM:                           133           3019           3978           9763
-------------------------------------------------------------------------------


Statistical information for the repository 'cbb13969c6b0b471c1971947' was
gathered on 2021/03/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel                           4           176            376           73.40
Dominique Makowski               1           200              0           26.60

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03132/joss.03132/10.21105.joss.03132.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03132/joss.03132/10.21105.joss.03132.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01541 is OK
- 10.21105/joss.01412 is OK
- 10.5281/zenodo.3952153 is OK
- 10.5281/zenodo.3952214 is OK
- 10.1111/2041-210X.12225 is OK
- 10.21105/joss.02445 is OK
- 10.21105/joss.02306 is OK
- 10.1098/rsif.2017.0213 is OK
- 10.2307/1912557 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by strengejacke** [comment]
I would suggest following reviewers:
rmhogervorst, cimentadaj, russellpierce, rchew, apwheele (in no particular order)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @mikldk as editor

**Comment by whedon** [comment]
@mikldk has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mikldk I realize you are handling several submissions already. If this is in your domain but you do not have time at the moment I can set this to "waitlisted" and wait for you to be available if you like.

**Comment by Kevin-Mattheus-Moerman** [comment]
@strengejacke thanks for your submission. I wanted to make a recommendation with regards to your paper title. It is more usual for JOSS paper titles to hint at the name of the package in the title, e.g. perhaps you can consider something like: `Performance:  an R Package for Assessment, Testing and Comparison of Statistical Models`.

**Comment by mikldk** [comment]
> @mikldk I realize you are handling several submissions already. If this is in your domain but you do not have time at the moment I can set this to "waitlisted" and wait for you to be available if you like.

Yes, it would be fine to assign me and set this to "waitlisted", thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @mikldk as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by Kevin-Mattheus-Moerman** [comment]
@strengejacke this submission is now set as `waitlisted`, which means that although we've found a handling editor our editors are too busy at the moment to work on this submission. Your submission will be dealt with as soon as the handling editor becomes available.

**Comment by strengejacke** [comment]
Great, thanks! I'll revise the paper title as suggested.

**Comment by mikldk** [comment]
@martinju, @sachsmc: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by martinju** [comment]
@mikldk Hi, I would be happy to review this paper.

**Comment by sachsmc** [comment]
@mikldk I don't have the time to do it at the moment, but I can recommend one of my students to review this submission. I will help guide them through the process, so if that is OK with you please assign @gjo11 as a reviewer.

**Comment by mikldk** [comment]
@whedon assign @martinju as reviewer

**Comment by whedon** [comment]
OK, @martinju is now a reviewer

**Comment by mikldk** [comment]
@whedon add @gjo11 as reviewer

**Comment by whedon** [comment]
OK, @gjo11 is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3139.
