### ISSUE TITLE
[PRE REVIEW]: PyMut: A rotamer based mutation library implemented in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3134]
**Submitting author:** @gerdos (<a href="http://orcid.org/0000-0001-6218-5192">Erdős Gábor</a>)
**Repository:** <a href="https://github.com/gerdos/pyMUT" target ="_blank">https://github.com/gerdos/pyMUT</a>
**Version:** 1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gerdos. **Currently, there isn't an JOSS editor assigned** to your paper.

@gerdos if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (47.4 files/s, 10518.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             55             62            634
Markdown                         1             22              0             71
TeX                              1              3              0             40
-------------------------------------------------------------------------------
SUM:                             4             80             62            745
-------------------------------------------------------------------------------


Statistical information for the repository '991b75d21f72a307e20b21bc' was
gathered on 2021/03/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Erdos Gabor                      4           905            155           97.70
gerdos                           2            11             14            2.30

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
gerdos                      751         6827.3          0.3                4.79
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3134 with the following error: 

 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (000-0001-6218-5192) for Erdős Gábor^[Corresponding author] (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/j.str.2011.03.019 may be a valid DOI for title: A smoothed backbone-dependent rotamer library for proteins derived from adaptive kernel density estimates and regressions

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@gerdos thanks for this submission. I've flagged this submission for additional scope review by our editorial board. This is default for submission of this size (see our ["substantial scholarly effort" requirements](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)) and should take about a week to complete. Thanks for your patience.

**Comment by Kevin-Mattheus-Moerman** [comment]
Note to editorial board, it looks like this is the core code contribution which appears to be about ~350 lines of code followed by mostly hardcoded (e.g. angle) definitions: 
https://github.com/gerdos/pyMUT/blob/master/pymut.py

@gerdos if you disagree with this finding :point_up: or want to elaborate on the extent of scholarly work contained in your submission please do let us know. Thanks. 

@gerdos a side note, I noticed `RESIDUE_STRUCTUES` in the code which perhaps should read `RESIDUE_STRUCTURES`?

**Comment by gerdos** [comment]
Dear @Kevin-Mattheus-Moerman!

Thanks a lot for reviewing my work! Indeed, the length of the code does not reach the suggested 1000 lines, but reaches the minimum in the submission rules. I usually try to code in a more compact manner while keeping my code in line with the current standards. I also though a lot about the aforementioned hardcoded angles, to supply them in a data file, however at the end, I put all the things inside the code that were calculated by me, and only supplied external data in separated file, like the rotamer library itself.

I hope the shortage of the code will not hider the possibility of the publication. 

Thanks you for the notice as well, it is indeed a typo, I will correct it now!

Earlier yesterday I was also contacted by the good people behind Biopython, and they offered me to intergrate PyMut inside Biopython. I hope this will not cause problems with JOSS! 

Thanks a lot, again!

**Comment by kthyng** [comment]
Hi @gerdos and thanks for your submission. Unfortunately the editorial board has determined that your submission does not pass the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) bar. It sounds excellent to join with Biopython, and perhaps the larger combined package could even be submitted to JOSS sometime.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
