### ISSUE TITLE
[PRE REVIEW]: Ngesh: a Python library for synthetic phylogenetic data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3135]
**Submitting author:** @tresoldi (<a href="http://orcid.org/0000-0002-2863-1467">Tiago Tresoldi</a>)
**Repository:** <a href="https://github.com/tresoldi/ngesh" target ="_blank">https://github.com/tresoldi/ngesh</a>
**Version:** v0.5
**Editor:** @majensen
**Reviewers:** @DavidNickle, @rvosa
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tresoldi. **Currently, there isn't an JOSS editor assigned** to your paper.

@tresoldi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.54 s (57.3 files/s, 9324.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              6             16           1084
Python                          10            318            703            974
Markdown                         6            172              0            736
reStructuredText                 5            157            294            353
TeX                              1             11              0            112
YAML                             3              8              4             49
JSON                             1              0              0             23
make                             1              4              7              9
Bourne Shell                     2              1              0              5
-------------------------------------------------------------------------------
SUM:                            31            677           1024           3345
-------------------------------------------------------------------------------


Statistical information for the repository 'd53fb5cb39d986d0bba6b3e4' was
gathered on 2021/03/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
NicolaDM                         1           183              1            2.90
Tiago Tresoldi                  90          3986           2173           97.10

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
NicolaDM                    122           66.7          1.9               48.36
Tiago Tresoldi             1873           47.0          8.3               23.01
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1126/science.283.5406.1310 is OK
- 10.1093/sysbio/syr029 is OK
- 10.1093/molbev/msw046 is OK

MISSING DOIs

- 10.2307/1909876 may be a valid DOI for title: The elements of stochastic processes with applications to the natural sciences
- 10.1093/bioinformatics/btu181 may be a valid DOI for title: geiger v2.0: an expanded suite of methods for fitting macroevolutionary models to phylogenetic trees
- 10.1093/bioinformatics/bty633 may be a valid DOI for title: ape 5.0: an environment for modern phylogenetics and evolutionary analyses in R
- 10.1371/journal.pone.0180908 may be a valid DOI for title: BEASTling: A software tool for linguistic phylogenetics using BEAST 2

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03135/joss.03135/10.21105.joss.03135.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03135/joss.03135/10.21105.joss.03135.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tresoldi thanks for this submission. I've flagged this submission for additional scope review by our editorial board. This is default for submissions of this size (see our ["substantial scholarly effort" requirements](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)) and should take about a week to complete. Thanks for your patience.

**Comment by tresoldi** [comment]
@Kevin-Mattheus-Moerman thank you!

**Comment by danielskatz** [comment]
@tresoldi - the scope review has completed, and we've decided this is in scope for review, so we'll now move to finding an editor

**Comment by danielskatz** [comment]
👋 @fboehm - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by fboehm** [comment]
Thanks for the invitation, @danielskatz. I feel like I should decline this opportunity, as I'm still finding reviewers for two other submissions.

**Comment by danielskatz** [comment]
@majensen - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @majensen as editor

**Comment by whedon** [comment]
@majensen has been invited to edit this submission.

**Comment by majensen** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
@DavidNickle - would you have some time to review [this interesting work on phylogenetic simulation](#3135) for [JOSS](https://joss.theoj.org)?

**Comment by DavidNickle** [comment]
Hi Mark,

I would be happy to but the current link does not work.

Thanks,

David

**Comment by DavidNickle** [comment]
I found the link :)

**Comment by majensen** [comment]
You are an awesome guy @DavidNickle

**Comment by majensen** [comment]
@whedon assign @DavidNickle as reviewer

**Comment by whedon** [comment]
OK, @DavidNickle is now a reviewer

**Comment by majensen** [comment]
@rvosa would you be up for reviewing [this phylogenetic simulation library](#3135) for [JOSS](https://joss.theoj.org)? A guide for JOSS reviews are [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

It would be great to have you weigh in! Hope things are great for you --@majensen

**Comment by rvosa** [comment]
Hey Mark! Sure, I'll be happy to do that. Thanks for the guide but this isn't even my first JOSS rodeo ;-)

Hope things are good with you too!

**Comment by DavidNickle** [comment]
**Conflict of interest:** I confirm that I have read the JOSS conflict of interest policy and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.
**Code of Conduct**

**Repository:** The source code for this software is available at the repository url **YES**

**License:** The repository contain a plain-text LICENSE file with the contents of an OSI approved software license. **YES**

**Contribution and authorship:** The submitting author made major contributions to the software and the full list of paper authors seem appropriate and complete. **YES**

**Functionality:** The software is functional and important adding very important knowledge to the public domain. **YES**

**Installation:** The installation procedure follows the documentation clearly.  I performed many of the examples in the How To Use section of the manuscript.  All worked as advertised

**Functionality:** I confirmed the functional claims of the software as well as some of my own.

**Performance:** It is pretty quick!

**A statement of need:** The authors have a clear audience in they have mind and the paper and the software should be readably available to that audience. It is potentially most useful for developing nulls in the evolution of languages

**Installation instructions:** I installed through PIP without any issues

**Example usage:** I went through the How To Use section. Everything worked. 

**Automated tests:** YES — tests are available 

**Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support. **YES**

**Software paper:**

**Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided? **YES**

**A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is? **YES**

**State of the field:** Do the authors describe how this software compares to other commonly-used packages? YES
Quality of writing: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)? YES
References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax? **YES**

@majensen I think this paper should be accepted. It is a nice piece of software that can be useful for those that are interested in the evolutionary of languages. It even allows for recombination (words passing from one language into another — can you use the word **pajama** or **pyjama**).

**Comment by majensen** [comment]
@DavidNickle thanks for the review, you can reenter it when we start the official review-- coming soon!

**Comment by majensen** [comment]
@rvosa you as usual are "the man"!

**Comment by majensen** [comment]
@whedon add @rvosa as reviewer

**Comment by whedon** [comment]
OK, @rvosa is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3173.

**Comment by majensen** [comment]
@tresoldi @DavidNickle @rvosa please join the review now open over at #3173 - thanks!
