### ISSUE TITLE
[PRE REVIEW]: Colette: A networking program to build research connections

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3136]
**Submitting author:** @gacphillips (<a href="http://orcid.org/0000-0002-2347-2321">Genevieve A. C. Phillips</a>)
**Repository:** <a href="https://github.com/dehorsley/colette/" target ="_blank">https://github.com/dehorsley/colette/</a>
**Version:** v0.1.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gacphillips. **Currently, there isn't an JOSS editor assigned** to your paper.

@gacphillips if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (48.3 files/s, 4721.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2            102             83            292
YAML                             1              2              0             36
Markdown                         1             12              0             30
TOML                             1              4              0             19
INI                              1              0              0              7
-------------------------------------------------------------------------------
SUM:                             6            120             83            384
-------------------------------------------------------------------------------


Statistical information for the repository 'afef59308012426991716a66' was
gathered on 2021/03/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
David Horsley                   28           931            454           77.59
Genevieve Phillips               1           316             84           22.41

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
David Horsley               465           49.9          2.4               11.18
Genevieve Phillips           12            3.8          2.4               16.67
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3136 with the following error: 

 Can't find any papers to compile :-(

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03136/joss.03136/10.21105.joss.03136.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03136/joss.03136/10.21105.joss.03136.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
This work was rejected over at: https://github.com/openjournals/joss-reviews/issues/3126#issuecomment-804360438

This re-submission corrects the repository link but does not alter the conclusion from the  editorial board, i.e. this submission is to minor given our criteria, and furthermore does not classify as scientific research software. 

We will once again reject this submission. Please consider JOSS for future works of a more substantial nature and with a clear scientific research application. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
