### ISSUE TITLE
[PRE REVIEW]: eemont: A Python package that extends Google Earth Engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3137]
**Submitting author:** @davemlz (<a href="http://orcid.org/0000-0002-9010-3286">David Montero Loaiza</a>)
**Repository:** <a href="https://github.com/davemlz/eemont" target ="_blank">https://github.com/davemlz/eemont</a>
**Version:** v0.1.9
**Editor:** @kbarnhart
**Reviewers:** @giswqs, @elbeejay, @patrickcgray
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @davemlz. **Currently, there isn't an JOSS editor assigned** to your paper.

@davemlz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.rse.2017.06.031 is OK
- 10.21105/joss.02272 is OK
- 10.21105/joss.02305 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.00 s (129.7 files/s, 50893.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            52           6326            156          15547
JavaScript                      13           2289           2320           8445
SVG                              1              0              0           2671
Python                          17            516           1453           1866
CSS                              6            328             53           1250
reStructuredText                21            747           1038            692
Jupyter Notebook                14              0           4682            380
Markdown                         1             20              0             67
TeX                              1              3              0             37
DOS Batch                        1              8              1             26
Rmd                              1             23             40             16
make                             1              4              7              9
INI                              1              1              0              5
-------------------------------------------------------------------------------
SUM:                           130          10265           9750          31011
-------------------------------------------------------------------------------


Statistical information for the repository '471a9702fe9e086fb22d7598' was
gathered on 2021/03/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
U-dmlmont-PC\dmlmont            87         31211          10487          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
U-dmlmont-PC\dmlmont      20724           66.4          2.2               13.26
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03137/joss.03137/10.21105.joss.03137.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03137/joss.03137/10.21105.joss.03137.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @kbarnhart as editor

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by kbarnhart** [comment]
@Kevin-Mattheus-Moerman I can take this one. I'm a bit overloaded so I won't be able to start actively handling it until the end of this week.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
@davemlz I'll now start actively handling this submission, beginning by looking for reviewers. I have some thoughts on suitable reviewers but would also be interested in people you think would be appropriate for this submission. 

Please indicate here people you think are appropriate (without tagging them with an @). [This list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list). Do not feel limited to this list. 

In addition, based on looking through the package, it looks like you've created a nice set of tutorials, but instructions for using them are not provided. I'd recommend adding some text to the readme/documentation that points a user to the tutorials.

**Comment by davemlz** [comment]
Hi @kbarnhart, @whedon, thank you so much for this!

I went through the list and have these people as a suggestion: omshinde, patrickcgray, jhollist.

Thanks for the recommendation of the instructions to use the tutorials, I will add them to the documentation so that people can use them.

**Comment by kbarnhart** [comment]
:wave:  @patrickcgray @giswqs @elbeejay  would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission is "eemont: A Python package that extends Google Earth Engine" and I'm contacting you based on your experience with python and remote sensing. 

This is a pre-review issue which is used to find reviewers. Once 2-3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks. If you are not able to review and have someone to recommend, please mention them here (when mentioning, please place a space after the @ of a github handle, for example, you would refer to me as "@ kbarnhart").

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) before the review process starts.

If you have any questions about the JOSS review process, please do not hesitate to reach out to me on this issue or at krbarnhart@usgs.gov

**Comment by giswqs** [comment]
@kbarnhart I would be happy to review it. Thanks for the invite.

**Comment by elbeejay** [comment]
@kbarnhart I'm happy to review this with the caveat that I don't know how to use R (yet), so I won't be able to test the `rgee` R-compatibility of this package.

**Comment by patrickcgray** [comment]
I'm also happy to help review this!

**Comment by kbarnhart** [comment]
@giswqs, @elbeejay, and @patrickcgray thanks for your enthusiasm to review this. 

@giswqs and/or @patrickcgray would either of you be able to review the `rgee` portion of the package ([described here](https://eemont.readthedocs.io/en/0.1.9/guide/eemontR.html)).

Once I confirm that someone is able to review the R portion I'll add you all as reviewers and start the main review issue.

**Comment by giswqs** [comment]
@kbarnhart Yes, I can review the rgee portion of the package.

**Comment by kbarnhart** [comment]
Thanks @giswqs !

**Comment by kbarnhart** [comment]
@whedon add @giswqs as reviewer

**Comment by whedon** [comment]
OK, @giswqs is now a reviewer

**Comment by kbarnhart** [comment]
@whedon add @elbeejay as reviewer

**Comment by whedon** [comment]
OK, @elbeejay is now a reviewer

**Comment by kbarnhart** [comment]
@whedon add @patrickcgray as reviewer

**Comment by whedon** [comment]
OK, @patrickcgray is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review
