### ISSUE TITLE
[REVIEW]: USAboundaries: Historical and Contemporary Boundaries of the United States of America

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#314]
**Submitting author:** @lmullen (<a href="http://orcid.org/0000-0001-5103-6917">Lincoln Mullen</a>)
**Repository:** <a href="https://github.com/ropensci/USAboundaries" target ="_blank">https://github.com/ropensci/USAboundaries</a>
**Version:** v0.3.0
**Editor:** @karthik
**Reviewer:** @AndySouth
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.825218" target="_blank">10.5281/zenodo.825218</a>

## Status

[![status](http://joss.theoj.org/papers/3458a33133aa6c069ab4dd8df0b5f3b5/status.svg)](http://joss.theoj.org/papers/3458a33133aa6c069ab4dd8df0b5f3b5)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3458a33133aa6c069ab4dd8df0b5f3b5"><img src="http://joss.theoj.org/papers/3458a33133aa6c069ab4dd8df0b5f3b5/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3458a33133aa6c069ab4dd8df0b5f3b5/status.svg)](http://joss.theoj.org/papers/3458a33133aa6c069ab4dd8df0b5f3b5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/USAboundaries" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@karthik, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @karthik know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/USAboundaries">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.3.0)?
- [x] **Authorship:** Has the submitting author (@lmullen) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@lmullen - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by arfon** [comment]
@openjournals/ropensci - could you link to the rOpenSci onboarding thread?

**Comment by noamross** [comment]
This package was developed under rOpenSci but has not been peer-reviewed through rOpenSci onboarding. (We plan to make it easier to distinguish between the two with some new badging and metadata soon).

**Comment by lmullen** [comment]
@arfon I've tagged everything 0.3.0 and create a GitHub release. Here is the Zenodo DOI.

DOI: 10.5281/zenodo.825218

**Comment by arfon** [comment]
> This package was developed under rOpenSci but has not been peer-reviewed through rOpenSci onboarding. (We plan to make it easier to distinguish between the two with some new badging and metadata soon).

Ah OK. @karthik - looks like we need a reviewer for thus submission then...

**Comment by karthik** [comment]
Got it, assigning one now.

**Comment by karthik** [comment]
I've reached out to @AndySouth for a review request.

**Comment by AndySouth** [comment]
Thanks @karthik, happy to do this. I'm travelling for a week will get to it after then. On quick inspection I couldn't find reviewers instructions, e.g. turnaround time, can you point me to ?

**Comment by karthik** [comment]
Thanks @AndySouth. Guidelines are here: http://joss.theoj.org/about#reviewer_guidelines
If you are able to accept and complete the review within two weeks after you're back, I would really appreciate it. Please let me know if that's ok and I'll start off the review process (which will close this issue and create a new one with a checklist for you to work through).

**Comment by AndySouth** [comment]
Great, thanks @karthik I'll do it.

On 27 Jul 2017 19:52, "Karthik Ram" <notifications@github.com> wrote:

Thanks @AndySouth <https://github.com/andysouth>. Guidelines are here:
http://joss.theoj.org/about#reviewer_guidelines
If you are able to accept and complete the review within two weeks after
you're back, I would really appreciate it. Please let me know if that's ok
and I'll start off the review process (which will close this issue and
create a new one with a checklist for you to work through).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/314#issuecomment-318517999>,
or mute the thread

**Comment by karthik** [comment]
@whedon assign @AndySouth as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @AndySouth

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by karthik** [comment]
@AndySouth Please work through the checklist at the top of this issue when you are ready and let me know if you have any questions or run into problems. Thanks again for your help!

**Comment by AndySouth** [comment]
@lmullen @karthik 

I've worked through the checklist and submitted some issues to the project repo.

I think this is a super-useful package, should I write a summary paragraph here too ?

[#](https://github.com/ropensci/USAboundaries/issues/41)
[#](https://github.com/ropensci/USAboundaries/issues/40)
[#](https://github.com/ropensci/USAboundaries/issues/39)
[#](https://github.com/ropensci/USAboundaries/issues/38)
[#](https://github.com/ropensci/USAboundaries/issues/37)
[#](https://github.com/ropensci/USAboundaries/issues/36)
[#](https://github.com/ropensci/USAboundaries/issues/35)

**Comment by karthik** [comment]
Thanks @AndySouth! We really appreciate the detailed review. No summary necessary here since you've linked to the issues (tip for next time, mentioning `joss-reviews/314` in the issues you open will automatically link them here with the title). I will wait for @lmullen to respond to these comments (push an update or respond with a reason) and once these are addressed, I'll ping you for another really quick check before proceeding with the acceptance.

Thanks again for sharing your time and expertise, Andy!

**Comment by lmullen** [comment]
Thanks for the review, @AndySouth. I will go over these issues as soon as I can and get back to you both with a summary response and changes to the package/paper.

**Comment by karthik** [comment]
Hi @lmullen just a quick ping to check in. Please update us once you get a chance.

**Comment by lmullen** [comment]
Hi @karthik. My apologies for the delay, especially since @AndySouth was generous to get the peer review done quickly. I have to launch a project at the middle of next week and then I will work on the issues raised by the peer review.

**Comment by karthik** [comment]
No worries.  Thanks @lmullen!

**Comment by arfon** [comment]
👋@lmullen - just a reminder to review @AndySouth's feedback sometime soon.

**Comment by lmullen** [comment]
@AndySouth Thanks for your thorough review, which I very much appreciate. Please accept my sincere apologies for the undue delay in implementing the requested changes.

I have gone through the issues that were opened on the USAboundaries issue and addressed them all. In all but one case I made the change that was requested. Those issues should have links to the commits and any other discussion so I won't belabor the point here.

I did also revise `paper.md` to elaborate on some points as requested to show a concrete example of a research project.

@karthik Please do let me know if you would like any further changes.

**Comment by karthik** [comment]
Thanks @lmullen I'll take a look shortly and follow up with next steps.

**Comment by AndySouth** [comment]
Good work on addressing the issues @lmullen , best wishes for the next steps.

**Comment by lmullen** [comment]
@AndySouth Thanks very much for the review. It has made the package stronger in a number of ways, not least the consistency of using all sf objects. Much appreciated!

**Comment by karthik** [comment]
Thanks very much for your time and expertise, @AndySouth 🙏
@lmullen I'm happy with the changes and the explanation for the one exception. Please archive your software on Zenodo and post a DOI here. I will proceed with accepting your submission.

Thank you!

**Comment by lmullen** [comment]
@karthik Here is the link to the Zenodo archive for v0.3.0 (the version reviewed): https://zenodo.org/record/825218

It's linked in `paper.md` but I'm happy to change the way it is listed if there is a standard way to do so for JOSS.

**Comment by lmullen** [comment]
This is the DOI to Zenodo. https://doi.org/10.5281/zenodo.825218

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.825218 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.825218" target="_blank">10.5281/zenodo.825218</a> is the archive.

**Comment by arfon** [comment]
@AndySouth - many thanks for your review here and to @karthik for editing this submission ✨ 

@lmullen - Your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00314 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00314/status.svg)](https://doi.org/10.21105/joss.00314)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00314/status.svg)](https://doi.org/10.21105/joss.00314)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by lmullen** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by lmullen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #314 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0     81      0 --:--:-- --:--:-- --:--:--    81
Error reading bibliography ./paper.bib (line 21, column 3):
unexpected "h"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by lmullen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by lmullen** [comment]
@arfon Thanks for the chance to fix minor errors in the PDF. I think that I've got everything fixed now. Could you regenerate the PDF please?

**Comment by arfon** [comment]
> @arfon Thanks for the chance to fix minor errors in the PDF. I think that I've got everything fixed now. Could you regenerate the PDF please?

Sure thing. I've updated the paper based on what's in `master` on https://github.com/ropensci/USAboundaries
