### ISSUE TITLE
[PRE REVIEW]: fastgwr: A python-based command-line interface for fast and parallel fitting of Geographically Weighted Regression models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3140]
**Submitting author:** @Ziqi-Li (<a href="http://orcid.org/0000-0002-6345-4347">Ziqi Li</a>)
**Repository:** <a href="https://github.com/Ziqi-Li/FastGWR" target ="_blank">https://github.com/Ziqi-Li/FastGWR</a>
**Version:** v0.2.9
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Ziqi-Li. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@Ziqi-Li if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03140/joss.03140/10.21105.joss.03140.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03140/joss.03140/10.21105.joss.03140.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1080/13658816.2018.1521523 may be a valid DOI for title: Fast Geographically Weighted Regression (FastGWR): a scalable algorithm to investigate spatial process heterogeneity in millions of observations
- 10.31219/osf.io/cpbt3 may be a valid DOI for title: Computational improvements to multi-scale geographically weighted regression
- 10.1016/j.jpdc.2007.09.005 may be a valid DOI for title: MPI for Python: Performance improvements and MPI-2 extensions
- 10.3390/ijgi9110653 may be a valid DOI for title: A CUDA-Based Parallel Geographically Weighted Regression for Large-Scale Geographic Data
- 10.1016/j.cageo.2021.104723 may be a valid DOI for title: Parallel computing for Fast Spatiotemporal Weighted Regression
- 10.2139/ssrn.3706851 may be a valid DOI for title: Guns and homicides: a multiscale geographically weighted instrumental variables approach
- 10.1016/j.neucom.2020.02.058 may be a valid DOI for title: RNN-GWR: A geographically weighted regression approach for frequently updated data
- 10.17341/gazimmfd.757131 may be a valid DOI for title: FastGTWR: Hızlı coğrafi ve zamansal ağırlıklı regresyon yaklaşımı
- 10.31219/osf.io/bphw9 may be a valid DOI for title: mgwr: A Python implementation of multiscale geographically weighted regression for investigating process spatial heterogeneity and scale
- 10.18637/jss.v063.i17 may be a valid DOI for title: GWmodel: an R package for exploring spatial heterogeneity using geographically weighted models
- 10.1016/j.envsoft.2010.06.011 may be a valid DOI for title: Investigating spatial non-stationary and scale-dependent relationships between urban surface temperature and environmental factors using geographically weighted regression
- 10.1177/0894439307298925 may be a valid DOI for title: Using geographically weighted regression to explore local crime patterns
- 10.1093/icesjms/fsp224 may be a valid DOI for title: Exploring spatial non-stationarity of fisheries survey data using geographically weighted regression (GWR): an example from the Northwest Atlantic
- 10.3390/ijerph8072798 may be a valid DOI for title: Using geographically weighted regression (GWR) to explore spatial varying relationships of immature mosquitoes and human densities with the incidence of dengue
- 10.1007/978-3-540-30218-6_19 may be a valid DOI for title: Open MPI: Goals, concept, and design of a next generation MPI implementation
- 10.1109/mcse.2011.37 may be a valid DOI for title: The NumPy array: a structure for efficient numerical computation

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @ziqi-li and thanks for your submission! Due to the relatively small size of the package, I am going to ping the editorial board to get input and see if we collectively consider it to be in scope. This process will take 1-2 weeks. Thanks for your patience.

**Comment by Ziqi-Li** [comment]
@kthyng Thanks for letting me know, and look forward to hearing positive from you and the board! Even though small in size, the package contains the core code and algorithms published in two peer-reviewed articles.

**Comment by danielskatz** [comment]
👋 @Ziqi-Li - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by Ziqi-Li** [comment]
@danielskatz Thanks for letting me know. May I clarify with you which criterion that this package fails to meet? I suspect it is due to the limited LOC, if that is the case, I wonder if I could add more functionalities so that this could be re-considered by JOSS.

**Comment by danielskatz** [comment]
The LoC is probably the primary issue.  Yes, we would welcome a resubmission of a more substantial package.

**Comment by Ziqi-Li** [comment]
@danielskatz That makes sense, thank you for the updated information!
