### ISSUE TITLE
[PRE REVIEW]: Visualizations with statistical details: The 'ggstatsplot' approach

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3141]
**Submitting author:** @IndrajeetPatil (<a href="http://orcid.org/0000-0003-1995-6531">Indrajeet Patil</a>)
**Repository:** <a href="https://github.com/IndrajeetPatil/ggstatsplot" target ="_blank">https://github.com/IndrajeetPatil/ggstatsplot</a>
**Version:** 0.7.1
**Editor:** @csoneson
**Reviewers:** @njtierney, @kevinrue
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @IndrajeetPatil. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @csoneson.

@IndrajeetPatil if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by IndrajeetPatil** [comment]
@whedon generate pdf

**Comment by kthyng** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.21 s (210.0 files/s, 88722.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            69           4650            881          33854
JavaScript                      28           5168           5438          18920
SVG                             26              0              1           7721
R                               60           1035           2679           6091
Markdown                        23           1124              0           5625
Rmd                             22           2080           4400           5082
XML                              2              0              2            609
CSS                              7            108             58            474
YAML                            12             82             19            446
JSON                             2              1              0            381
TeX                              3             30              0            335
-------------------------------------------------------------------------------
SUM:                           254          14278          13478          79538
-------------------------------------------------------------------------------


Statistical information for the repository 'e3a349548944b834366cf7e3' was
gathered on 2021/03/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Indrajeet Patil                 48         54347          15043           99.42
IndrajeetPatil                   5           305             99            0.58

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Indrajeet Patil           39510           72.7          8.9               18.52
```

**Comment by kthyng** [comment]
@csoneson I see you're just finishing up a different submission... are you able to take on this new one?

**Comment by kthyng** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by IndrajeetPatil** [comment]
Thanks!

Potential reviewers:

- RMHogervorst
- cimentadaj
- njtierney
- humanfactors

**Comment by csoneson** [comment]
👋 @RMHogervorst, @njtierney - would you be interested in reviewing this submission for JOSS? 

> Visualizations with statistical details: The 'ggstatsplot' approach

**Comment by csoneson** [comment]
@IndrajeetPatil - I noticed that a couple of the references cited in your paper are listed as published by JOSS (Ludecke et al, 2021; Patil et al, 2021), but the DOIs go to a preprint server. Could you please correct these references?

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3758/s13428-015-0664-2 is OK
- 10.3389/fpsyg.2015.01100 is OK
- 10.21105/joss.01686 is OK
- 10.31234/osf.io/ntbvy is OK
- 10.21105/joss.02815 is OK
- 10.21105/joss.02445 is OK
- 10.21105/joss.01541 is OK
- 10.31234/osf.io/vtq8f is OK
- 10.21105/joss.01412 is OK
- 10.3758/s13423-020-01798-5 is OK
- 10.21105/joss.02306 is OK

MISSING DOIs

- 10.1016/0003-2697(86)90183-1 may be a valid DOI for title: The Elements of Graphing Data

INVALID DOIs

- None
```

**Comment by IndrajeetPatil** [comment]
@csoneson Sorry about that. I have [fixed](https://github.com/IndrajeetPatil/ggstatsplot/commit/94db4de38370734819a893107ea8864f132ca13d) the references.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03141/joss.03141/10.21105.joss.03141.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03141/joss.03141/10.21105.joss.03141.pdf) :page_facing_up: :point_left:

**Comment by IndrajeetPatil** [comment]
Do you know how can I avoid the duplicated affiliation index (two instances of `1`) here?

<img width="363" alt="Screenshot 2021-04-05 at 09 58 16" src="https://user-images.githubusercontent.com/11330453/113551822-925c9800-95f5-11eb-9eca-6725e3cfc281.png">

**Comment by csoneson** [comment]
Good question - perhaps @openjournals/dev can help (don't know if it's because the .md is generated from the .Rmd)?

**Comment by xuanxu** [comment]
> Do you know how can I avoid the duplicated affiliation index (two instances of `1`) here?

The format of the affiliations section in the metadata is incorrect, should be something like:
```yaml
affiliations:
 - name: Center for Humans and Machines, Max Planck Institute for Human Development, Berlin, Germany
   index: 1
```

**Comment by IndrajeetPatil** [comment]
Thanks, @xuanxu! 

@whedon generate pdf

**Comment by IndrajeetPatil** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03141/joss.03141/10.21105.joss.03141.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03141/joss.03141/10.21105.joss.03141.pdf) :page_facing_up: :point_left:

**Comment by IndrajeetPatil** [comment]
@xuanxu I changed my `.md` file according to your suggestion (https://raw.githubusercontent.com/IndrajeetPatil/ggstatsplot/master/paper/paper.md), but the second `1` has now moved to the end of the affiliation

<img width="461" alt="Screenshot 2021-04-05 at 13 01 58" src="https://user-images.githubusercontent.com/11330453/113567576-28e98300-960f-11eb-906d-bd2113f41c12.png">

**Comment by xuanxu** [comment]
@IndrajeetPatil You have a dash before the index, so you are creating two affiliation entries.

Current:
```yaml
affiliations:
  - name: Center for Humans and Machines, Max Planck Institute for Human Development, Berlin, Germany
  - index: 1
```

Correct:
```yaml
affiliations:
  - name: Center for Humans and Machines, Max Planck Institute for Human Development, Berlin, Germany
    index: 1
```

**Comment by IndrajeetPatil** [comment]
Oops 🙈 

Thanks, will fix it.

**Comment by IndrajeetPatil** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03141/joss.03141/10.21105.joss.03141.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03141/joss.03141/10.21105.joss.03141.pdf) :page_facing_up: :point_left:

**Comment by njtierney** [comment]
Hi there!

I'd be happy to review this package. When is the due date?

**Comment by csoneson** [comment]
Thanks @njtierney! We don't impose a fixed due date (and we're a bit more flexible right now given the challenges brought by the pandemic), but we encourage reviewers to post comments as they go through the submission (no need to collect them all in one big review), and to have an initial assessment for the authors to work on within two weeks from the start of the review.

**Comment by csoneson** [comment]
@njtierney - I will add you as a reviewer now (and you can of course start looking at the submission), but the actual review will start once we have recruited one more reviewer. At that point I'll open the review issue, where you will find your review checklist etc.

**Comment by csoneson** [comment]
@whedon assign @njtierney as reviewer

**Comment by whedon** [comment]
OK, @njtierney is now a reviewer

**Comment by csoneson** [comment]
@whedon add @kevinrue as reviewer

**Comment by csoneson** [comment]
@njtierney, @kevinrue - thanks for accepting to review this submission! I'll start the review issue now, and we'll move the discussion over there.

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3167.
