### ISSUE TITLE
[PRE REVIEW]: tfaip - a Generic and Powerful Research Framework for Deep Learning based on Tensorflow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3142]
**Submitting author:** @chwick (<a href="http://orcid.org/0000-0003-3958-6240">Christoph Wick</a>)
**Repository:** <a href="https://github.com/Planet-AI-GmbH/tfaip" target ="_blank">https://github.com/Planet-AI-GmbH/tfaip</a>
**Version:** v1.1.0
**Editor:** @arfon
**Reviewers:** @levimcclenny, @Het-Shah
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @chwick. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @terrytangyuan.

@chwick if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.45 s (450.7 files/s, 36856.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         166           2221           4451           7679
reStructuredText                24            463            380            706
Markdown                         7             98              0            358
TeX                              1              6              0             94
YAML                             3             14             13             64
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           203           2814           4852           8936
-------------------------------------------------------------------------------


Statistical information for the repository '6d8c827aca5ac03382709ba2' was
gathered on 2021/03/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
C. Wick                         31         28028          12885           99.94
jochen                           3            20              3            0.06

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
C. Wick                   15160           54.1          1.3               30.27
```

**Comment by kthyng** [comment]
Hi @chwick and thanks for your submission. We have a backlog of submissions right now and will need to add you to a waitlist as we wait for editors to process through some submissions. I'll add the waitlist tag and we hope to get to this submission soon. Thanks for your patience.

**Comment by ChWick** [comment]
Hi @kthyng, thanks for this information! We hope that our paper will be scheduled soon and appreciate the efforts of all editors that make this journal possible!

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @rmorgan10 @vs74 @levimcclenny - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission we'd be asking you to review is [_tfaip - a Generic and Powerful Research Framework for Deep Learning based on Tensorflow_](https://github.com/Planet-AI-GmbH/tfaip).

**Comment by rmorgan10** [comment]
Hi @arfon thanks for reaching out. I mainly work with `PyTorch`, and don't feel I have enough experience with `tensorflow` to provide a thorough review of `tfaip`.

**Comment by levimcclenny** [comment]
@arfon I can do it. Whats the timeline?

**Comment by levimcclenny** [comment]
@whedon assign me as reviewer

**Comment by whedon** [comment]
I'm sorry @levimcclenny, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arfon** [comment]
> @arfon I can do it. Whats the timeline?

Great, thanks so much @levimcclenny! Ideally we'd like initial feedback to the author in a couple of weeks, and then for the review process to have completed with ~6 weeks.

I'll go ahead and add you as a reviewer now, but will hold off opening up the main review issue (with the checklist for you to work through) until I've identified a second reviewer (hopefully later this week).

**Comment by arfon** [comment]
@whedon add @levimcclenny as reviewer

**Comment by whedon** [comment]
OK, @levimcclenny is now a reviewer

**Comment by arfon** [comment]
@ankur-gupta & @Het-Shah - would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission we'd be asking you to review is [_tfaip - a Generic and Powerful Research Framework for Deep Learning based on Tensorflow_](https://github.com/Planet-AI-GmbH/tfaip).

**Comment by arfon** [comment]
@ChWick - apologies it's taking a while to find a second reviewer here. Any chance you could suggest a few additional reviewer names?

**Comment by Het-Shah** [comment]
@arfon I am extremely sorry, I missed the previous message. I would love to provide a review for this submission. Can you kindly let me know a rough timeline for my review? 

Thank you and sorry once again!

**Comment by arfon** [comment]
Thanks @Het-Shah! Ideally we'd want the review to be complete in ~4-6 weeks, but ideally with some initial feedback to the authors before then. In all likelihood, we can work with whatever timescale you're able to commit to :smile:

I'll go ahead and add you to the review thread now to get things moving.

**Comment by whedon** [comment]
OK, @Het-Shah is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3297.
