### ISSUE TITLE
[PRE REVIEW]: PySDM v1: particle-based cloud modelling package for warm-rain microphysics and aqueous chemistry

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3144]
**Submitting author:** @piotrbartman (<a href="http://orcid.org/0000-0003-0265-6428">Piotr Bartman</a>)
**Repository:** <a href="https://github.com/atmos-cloud-sim-uj/PySDM.git" target ="_blank">https://github.com/atmos-cloud-sim-uj/PySDM.git</a>
**Version:** v1
**Editor:** @dhhagan
**Reviewers:** @jwuttke, @darothen
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @piotrbartman. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @pdebuyl.

@piotrbartman if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.72 s (304.0 files/s, 17875.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         210           2022           1194           7257
SVG                              1              0             19           1402
Jupyter Notebook                 3              0            207            336
Markdown                         1             33              0            270
YAML                             4             20              5            113
-------------------------------------------------------------------------------
SUM:                           219           2075           1425           9378
-------------------------------------------------------------------------------


Statistical information for the repository '540d532768b39be7feea8047' was
gathered on 2021/04/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Anna Jaruga                      1             3              1            0.01
Bartosz Piasecki                 1            42             23            0.09
Michael                         18           443            170            0.81
Michaeldz36                     37          2661           2424            6.76
Piotr Bartman                   10            14             19            0.04
Sylwester Arabas               391         11156           7135           24.30
piotrbartman                    61          2072           2853            6.54
prbartman                      438         26379          19740           61.27
tehAgitto                        4            84             51            0.18

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Bartosz Piasecki             30           71.4          4.5                0.00
Michael                     345           77.9         14.3                8.41
Sylwester Arabas           3856           34.6          3.3                4.67
prbartman                  6227           23.6          8.9                7.98
tehAgitto                    43           51.2          3.9                2.33
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3144 with the following error: 

 Can't find any papers to compile :-(

**Comment by kthyng** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3144 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by kthyng** [comment]
@piotrbartman can you address the error in your paper here?

**Comment by kthyng** [comment]
@dhhagan Is this close enough in your wheelhouse to take on?

**Comment by kthyng** [comment]
@whedon invite @dhhagan as editor

**Comment by whedon** [comment]
@dhhagan has been invited to edit this submission.

**Comment by dhhagan** [comment]
@kthyng This is absolutely right in my wheelhouse - will add myself as editor.

**Comment by dhhagan** [comment]
@whedon assign @dhhagan as editor

**Comment by whedon** [comment]
OK, the editor is @dhhagan

**Comment by slayoo** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03144/joss.03144/10.21105.joss.03144.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03144/joss.03144/10.21105.joss.03144.pdf) :page_facing_up: :point_left:

**Comment by dhhagan** [comment]
Looks great - I'll find some reviewers over the next week or so (hopefully).

**Comment by dhhagan** [comment]
Hey @darothen - any chance you have some time for a review?

**Comment by dhhagan** [comment]
:wave: Hey @sgrieve, @lheagy, @andreas-h, @jwuttke - would any of you be available and interested in reviewing this manuscript and software?

**Comment by jwuttke** [comment]
Where are the review instructions?

**Comment by slayoo** [comment]
> Where are the review instructions?

https://joss.readthedocs.io/en/latest/reviewer_guidelines.html
https://joss.readthedocs.io/en/latest/review_criteria.html
https://joss.readthedocs.io/en/latest/review_checklist.html

Thanks,
Sylwester

**Comment by jwuttke** [comment]
OK, let me give it a try. How to get to the checklist?

**Comment by dhhagan** [comment]
Hey @jwuttke - once I find two reviewers, I will add them as reviewers in this issue, and a new review issue will be created that has the checklist for each reviewer. Would you like to review? If so, I will add you as one of the reviewers.

**Comment by jwuttke** [comment]
yes, I'm available.

**Comment by dhhagan** [comment]
@whedon add @jwuttke as reviewer

**Comment by whedon** [comment]
OK, @jwuttke is now a reviewer

**Comment by darothen** [comment]
Just saw this @slayoo and @dhhagan (buried in my notifications). I can offer a quick review.

**Comment by dhhagan** [comment]
@darothen Awesome. I'll add you and we can kick off this review!

**Comment by dhhagan** [comment]
@whedon add @darothen as reviewer.

**Comment by whedon** [comment]
OK, @darothen is now a reviewer

**Comment by dhhagan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3219.

**Comment by darothen** [comment]
Thanks @dhhagan; will knock this out ASAP.
