### ISSUE TITLE
[PRE REVIEW]: Sapsan: Framework for Supernovae Turbulence Modeling with Machine Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3146]
**Submitting author:** @pikarpov-lanl (<a href="http://orcid.org/0000-0003-4311-8490">Platon I. Karpov</a>)
**Repository:** <a href="https://github.com/pikarpov-LANL/Sapsan" target ="_blank">https://github.com/pikarpov-LANL/Sapsan</a>
**Version:** v0.2.5
**Editor:** @dfm
**Reviewers:** @kburns, @milescranmer
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @pikarpov-lanl. **Currently, there isn't an JOSS editor assigned** to your paper.

@pikarpov-lanl if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3146 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.95 s (74.5 files/s, 8286.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          57           1268           1307           4174
Markdown                         4             78              0            204
Jupyter Notebook                 3              0            492            166
YAML                             5             12              3            161
Dockerfile                       1              5              3             11
make                             1              2              3              5
-------------------------------------------------------------------------------
SUM:                            71           1365           1808           4721
-------------------------------------------------------------------------------


Statistical information for the repository '9e6f9cbac95d3e62f12cc685' was
gathered on 2021/04/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
IceKhan13                        1            43              6            0.21
Iskandar Sitdikov               22          3330            396           16.31
Platon I Karpov                 16          3825           2270           26.68
Platon Karpov                   16          1544           1217           12.09
pikarpov                        57          6688           3522           44.70

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
IceKhan13                     6           14.0         16.5                0.00
Iskandar Sitdikov          1493           44.8         12.3                7.97
Platon I Karpov            2814           73.6          4.7               12.08
Platon Karpov              2436          157.8          4.7                6.65
```

**Comment by danielskatz** [comment]
👋 @mbobra - are you able to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by danielskatz** [comment]
@pikarpov-LANL - Given the comment in your README: "currently Sapsan is in alpha, but we are actively working on it and introduce new feature on a daily basis" and given that JOSS is looking for papers that are complete, I suggest this submission be withdrawn until it is more stable and more mature.  Does this seem ok to you?  If so, I will mark it as withdrawn.

**Comment by pikarpov-LANL** [comment]
Hi Daniel,


This is an outdated note, left behind before I had any physics-informed methods, analytical tools, and wiki. As it stands, Sapsan is full-featured and ready for general use as outlined in the paper. I have removed that note from README.


Thank you for bringing it to my attention!


Plato

________________________________
From: Daniel S. Katz ***@***.***>
Sent: Monday, April 5, 2021 5:52:19 PM
To: openjournals/joss-reviews
Cc: Karpov, Platon; Mention
Subject: [EXTERNAL] Re: [openjournals/joss-reviews] [PRE REVIEW]: Sapsan: Framework for Supernovae Turbulence Modeling with Machine Learning (#3146)


@pikarpov-LANL<https://github.com/pikarpov-LANL> - Given the comment in your README: "currently Sapsan is in alpha, but we are actively working on it and introduce new feature on a daily basis" and given that JOSS is looking for papers that are complete, I suggest this submission be withdrawn until it is more stable and more mature. Does this seem ok to you? If so, I will mark it as withdrawn.

**Comment by danielskatz** [comment]
👋 @dfm - are you able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
@whedon assign me as editor

Yes - I'm happy to edit.

@pikarpov-LANL: I'll do a first pass and then start looking for reviewers in the next few days. I'll keep you posted as this progresses and if I have any questions. You should also feel free to ask me any questions as we go.

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by pikarpov-LANL** [comment]
@dfm great, thank you!

**Comment by dfm** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3146 with the following error: 

 ORCID looks malformed
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (to-fill) for Platon I. Karpov (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by dfm** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by dfm** [comment]
@whedon check repository from branch joss

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevE.93.031301 is OK
- 10.1103/PhysRevFluids.3.074602 is OK
- 10.1103/RevModPhys.91.045002 is OK
- 10.1080/14685240802376389 is OK
- 10.1038/nature12128 is OK
- 10.1126/science.359.6377.725 is OK

MISSING DOIs

- 10.1109/tkde.2017.2720168 may be a valid DOI for title: Theory-guided Data Science: A New Paradigm for Scientific Discovery from Data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.44 s (161.5 files/s, 17950.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          57           1268           1307           4174
Markdown                         4             77              0            203
Jupyter Notebook                 3              0            492            166
YAML                             5             12              3            161
Dockerfile                       1              5              3             11
make                             1              2              3              5
-------------------------------------------------------------------------------
SUM:                            71           1364           1808           4720
-------------------------------------------------------------------------------


Statistical information for the repository '14fee00b678c84b921e8e16e' was
gathered on 2021/04/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
IceKhan13                        1            43              6            0.21
Iskandar Sitdikov               22          3330            396           16.31
Platon I Karpov                 16          3825           2270           26.68
Platon Karpov                   16          1544           1217           12.09
pikarpov                        57          6688           3522           44.70

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
IceKhan13                     6           14.0         16.5                0.00
Iskandar Sitdikov          1493           44.8         12.3                7.97
Platon I Karpov            2814           73.6          4.7               12.08
Platon Karpov              2436          157.8          4.7                6.65
```

**Comment by dfm** [comment]
@pikarpov-LANL: Can you make these small changes:

1. Fix the ORCID in the manuscript
2. Add the [suggested DOI](https://github.com/openjournals/joss-reviews/issues/3146#issuecomment-815724155): `10.1109/tkde.2017.2720168`
3. Add an [explicit "Statement of need" section](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) to the paper

**Comment by pikarpov-LANL** [comment]
@dfm 

1. Done
2. Done
3. I think that my Introduction served as a Statement of Need, hence I renamed it to the latter. However, if you think it is too lengthy, I will be happy to edit it down. Let me know.

**Comment by dfm** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03146/joss.03146/10.21105.joss.03146.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03146/joss.03146/10.21105.joss.03146.pdf) :page_facing_up: :point_left:

**Comment by dfm** [comment]
@whedon assign @kburns as reviewer

@kburns will be one of our reviewers - thanks Keaton! Once I have confirmation on a second reviewer, I'll get the main review started.

**Comment by whedon** [comment]
OK, @kburns is now a reviewer

**Comment by dfm** [comment]
@pikarpov-LANL: would you like me to switch this review to your @pikarpov account altogether or would you rather the submission still be associated with @pikarpov-LANL? Sorry I didn't get back to you about this sooner!

**Comment by pikarpov-LANL** [comment]
@dfm please keep the submission under @pikarpov-lanl, for the lab's record. However, I will reply faster @pikarpov, since I get notifications straight to my personal email, hence my phone. I cannot do the same with the lab's account.

**Comment by dfm** [comment]
@whedon add @milescranmer as reviewer

Thanks Miles for agreeing to be our second reviewer! I'll get the review started shortly in a new thread, so we can all head over there for the rest of the process. Please don't hesitate to ask if you have any questions as the review progresses.

**Comment by whedon** [comment]
OK, @milescranmer is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3199.
