### ISSUE TITLE
[PRE REVIEW]: ERFit: Entropic Regression Fit Matlab Package, for Data-Driven System Identification of Underlying Dynamic Equations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3147]
**Submitting author:** @almomaa (<a href="http://orcid.org/0000-0001-9362-7459">Abd AlRahman AlMomani</a>)
**Repository:** <a href="https://github.com/almomaa/ERFit-Package" target ="_blank">https://github.com/almomaa/ERFit-Package</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @almomaa. **Currently, there isn't an JOSS editor assigned** to your paper.

@almomaa if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.18 s (123.3 files/s, 8560.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                          19            234            392            533
TeX                              1             30              0            227
Markdown                         2             29              0             82
-------------------------------------------------------------------------------
SUM:                            22            293            392            842
-------------------------------------------------------------------------------


Statistical information for the repository '76ebea59e92e712334b01b5c' was
gathered on 2021/04/05.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/00207178908953472 is OK
- 10.1073/pnas.1517384113 is OK
- 10.1103/PhysRevLett.106.154101 is OK
- 10.1007/BF02546499 is OK

MISSING DOIs

- 10.1063/1.5133386 may be a valid DOI for title: How entropic regression beats the outliers problem in nonlinear system identification
- 10.1016/j.physd.2013.07.001 may be a valid DOI for title: Causation entropy identifies indirect influences, dominance of neighbors and anticipatory couplings
- 10.3390/e16063416 may be a valid DOI for title: Identifying the coupling structure in complex systems through the optimal causation entropy principle
- 10.2307/2529430 may be a valid DOI for title: Best linear unbiased estimation and prediction under a selection model
- 10.1103/physreve.77.026214 may be a valid DOI for title: Inferring the directionality of coupling with conditional mutual information
- 10.1016/j.physd.2006.12.006 may be a valid DOI for title: Modeling and Nonlinear Parameter Estimation with Kronecker product Representation for Coupled Oscillators and Spatiotemporal Systems.
- 10.1080/00207170701701031 may be a valid DOI for title: An extended orthogonal forward regression algorithm for system identification using entropy
- 10.1103/physreve.92.010902 may be a valid DOI for title: Predicting chaotic time series with a partial model
- 10.1137/16m1086637 may be a valid DOI for title: Exact Recovery of Chaotic Systems from Highly Corrupted Data

INVALID DOIs

- https://doi.org/10.1016/j.sigpro.2011.02.013 is INVALID because of 'https://doi.org/' prefix
- http://dx.doi.org/10.1016/j.physrep.2016.06.004 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03147/joss.03147/10.21105.joss.03147.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03147/joss.03147/10.21105.joss.03147.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @almomaa - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect.  Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF.  Whedon commands need to the be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hello @almomaa, the JOSS editorial board has reviewed your submission, and found that it falls outside our scope at this time, due to the relatively small size of the software package and narrow functionality. Editors also pointed out that the package could use some cleaning up and better organization following open-source best practices.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
