### ISSUE TITLE
[PRE REVIEW]: datasailr - An R Package for Row by Row Data Processing, Using DataSailr Script

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3149]
**Submitting author:** @niceume (<a href="http://orcid.org/0000-0001-7015-621X">Toshihiro Umehara</a>)
**Repository:** <a href="https://github.com/niceume/datasailr" target ="_blank">https://github.com/niceume/datasailr</a>
**Version:** 0.8.7
**Editor:** @fboehm
**Reviewers:** @DrMattG and @crvernon
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @niceume. **Currently, there isn't an JOSS editor assigned** to your paper.

@niceume if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.37 s (51.8 files/s, 8388.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              2            193            110           1385
Markdown                         2            224              0            516
R                                8             45             14            237
m4                               1             26              0            192
Bourne Shell                     5             25             19             75
C/C++ Header                     1              4              1             11
-------------------------------------------------------------------------------
SUM:                            19            517            144           2416
-------------------------------------------------------------------------------


Statistical information for the repository 'f15aec5b9e3876cac4df3016' was
gathered on 2021/04/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
niceume                         31          1857            153          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
niceume                    1704           91.8          1.9                6.51
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3149 with the following error: 

 Can't find any papers to compile :-(

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss_submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03149/joss.03149/10.21105.joss.03149.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03149/joss.03149/10.21105.joss.03149.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss_submission

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss_submission
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @fboehm - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by fboehm** [comment]
Thank you, @danielskatz - I'm happy to edit this submission.

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by fboehm** [comment]
@whedon assign @DrMattG and @crvernon as reviewers

**Comment by whedon** [comment]
OK, @DrMattG and @crvernon is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3166.
