### ISSUE TITLE
[PRE REVIEW]: genomepy: download genomes the easy way

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#315]
**Submitting author:** @simonvh (<a href="http://orcid.org/0000-0002-0411-3219">SJ van Heeringen</a>)
**Repository:** <a href="http://github.com/simonvh/genomepy" target ="_blank">http://github.com/simonvh/genomepy</a>
**Version:** 0.3.1
**Editor:** @pjotrp
**Reviewer:** @kblin

**Author instructions**

Thanks for submitting your paper to JOSS @simonvh. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@simonvh if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by pjotrp** [comment]
Hi @simonvh,

Thank your for your submission and thank you for the interesting software. 

Before I start looking for a reviewer can you fill out the paper a bit more?
https://github.com/simonvh/genomepy/blob/master/paper/paper.md

It should be descriptive of the software and give a bit of context. Citations should go in a bib file similar to
http://joss.theoj.org/papers/10.21105/joss.00025. The sources for this are here:
https://github.com/genenetwork/genenetwork2/tree/master/doc/joss/2016

Giving it a nice presentation will help popularize your project and get citations.

**Comment by simonvh** [comment]
Thanks @pjotrp. I have updated the submission.

**Comment by pjotrp** [comment]
OK, looking good. @peterjc can you suggest a biopython contributor as a reviewer for genomepy?

**Comment by peterjc** [comment]
He may decline as the author of a "rival" tool https://github.com/kblin/ncbi-genome-download (or the editors might consider this a conflict of interest), but I think that knowledge would let Kai Blin give a very well informed review.

**Comment by pjotrp** [comment]
Thanks @peterjc! @kblin can you take a look at this?

**Comment by kblin** [comment]
What's the timeline on this? I have a number of other pending reviews, and it looks like reviewing this needs a decent internet connection, so not something I can do while traveling.

At a first glance, I don't think I have a big conflict of interest, the focus of genomepy really seems to be more focused on interacting with the UCSC genomes and higher eukaryotes, whereas ncbi-genome-download is pretty much about what it says on the label, with a feature set more focused on the metadata available from NCBI.

**Comment by simonvh** [comment]
From my side at least there is no big rush. I'm leaving for a few weeks of holiday this Friday (pretty much off the grid). That means I won't have much time for a response before half of August anyway. In addition, I do agree, I also don't see any real conflict of interest.

**Comment by pjotrp** [comment]
Thanks @kblin. @simonvh, to expedite the review process can you check whether your submission matches our check list? See https://github.com/openjournals/joss-reviews/issues/307 for an example. That would be helpful, thanks!

**Comment by simonvh** [comment]
Thanks @pjotrp, I went through the checklist and added a few missing bits of information. I think it should be OK, looking forward to @kblin's input.

**Comment by pjotrp** [comment]
Excellent, let's proceed. I should see @kblin this week.

**Comment by pjotrp** [comment]
@whedon assign @kblin as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kblin

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/320. Feel free to close this issue now!
