### ISSUE TITLE
[PRE REVIEW]: fitgrid: A Python package for multi-channel event-related time series regression modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3150]
**Submitting author:** @turbach (<a href="http://orcid.org/0000-0001-7993-142X">Thomas P. Urbach</a>)
**Repository:** <a href="https://github.com/kutaslab/fitgrid" target ="_blank">https://github.com/kutaslab/fitgrid</a>
**Version:** v0.5.0
**Editor:** @meg-simula
**Reviewers:** @AJQuinn, @sappelhoff
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @turbach. **Currently, there isn't an JOSS editor assigned** to your paper.

@turbach if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.79 s (99.9 files/s, 14464.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          41           1614           2443           4319
reStructuredText                28            314            271            601
YAML                             5             43            100            440
Markdown                         3             35              0             76
Jupyter Notebook                 1              0           1082             59
make                             1              8              8             21
-------------------------------------------------------------------------------
SUM:                            79           2014           3904           5516
-------------------------------------------------------------------------------


Statistical information for the repository 'a03dceb00e4209685b3b6b24' was
gathered on 2021/04/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrey Portnoy                 191          5222           5139           30.16
Lauren                          10           438             82            1.51
Tom Urbach                     119         15705           7771           68.33

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrey Portnoy             2405           46.1         28.4                6.99
Tom Urbach                 5971           38.0          8.8               24.10
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3150 with the following error: 

 Can't find any papers to compile :-(

**Comment by turbach** [comment]
https://github.com/kutaslab/fitgrid/tree/joss-paper

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03150/joss.03150/10.21105.joss.03150.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03150/joss.03150/10.21105.joss.03150.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @turbach - thanks for your submission.  Due to a lack of suitable and available editors, I'm going to put this on our waitlist for now

**Comment by turbach** [comment]
@danielskatz Got it thanks. 

As editors become available perhaps cMadan, oliviaguest, arokem

Some candiate reviewers: a3sha2, SRSteinkamp, neurofractal, ajquinn, Emma-k-ward, sappelhoff, GerJuli, szorowi1

**Comment by danielskatz** [comment]
👋 @meg-simula - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by meg-simula** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by meg-simula** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by meg-simula** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03150/joss.03150/10.21105.joss.03150.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03150/joss.03150/10.21105.joss.03150.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
@turbach Thanks for the submission (and the patience so far)! This looks ready for review. I'll reach out to reviewers and then get back to you shortly to get the review started.

**Comment by meg-simula** [comment]
@SRSteinkamp, @neurofractal, @ajquinn, @sappelhoff: You have been suggested as reviewers - would you be available and willing to review this package for JOSS? Your assistance and expertise would be much appreciated.

**Comment by AJQuinn** [comment]
Hello - yes, I'm happy to review this. Looks very interesting!

**Comment by meg-simula** [comment]
@AJQuinn Excellent, I'll assign you.

**Comment by meg-simula** [comment]
@whedon assign @AJQuinn as reviewer

**Comment by whedon** [comment]
OK, @AJQuinn is now a reviewer

**Comment by sappelhoff** [comment]
Unfortunately my earliest availability for this would be May 22nd. Please ping me if no available reviewer has been found until then, and I'll gladly help out!

**Comment by SRSteinkamp** [comment]
I am so sorry for the late reply, I haven't looked into my Github notifications for ages (and didn't know that the Review requests would come in this way). 

I find the package quite interesting, but unfortunately do not have any resources for reviewing in the next couple of weeks.

**Comment by meg-simula** [comment]
@sappelhoff would you still be available from May 22nd and onwards? Your review would be much appreciated.

**Comment by sappelhoff** [comment]
Yes, I'll be available for review :+1:

**Comment by meg-simula** [comment]
Excellent!

**Comment by meg-simula** [comment]
@whedon add @sappelhoff as reviewer

**Comment by whedon** [comment]
OK, @sappelhoff is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3293.
