### ISSUE TITLE
[PRE REVIEW]: ML2Pvae: An R package for high-dimensional Item Response Theory parameter estimation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3151]
**Submitting author:** @converseg (<a href="http://orcid.org/0000-0001-8764-9950">Geoffrey Converse</a>)
**Repository:** <a href="https://github.com/converseg/ML2Pvae" target ="_blank">https://github.com/converseg/ML2Pvae</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @converseg. **Currently, there isn't an JOSS editor assigned** to your paper.

@converseg if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (298.8 files/s, 14320.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               22             42            220            587
Markdown                         3             53              0            195
Rmd                              1             26             50             62
TeX                              1              9              0             50
-------------------------------------------------------------------------------
SUM:                            27            130            270            894
-------------------------------------------------------------------------------


Statistical information for the repository '5abf19f3e7a2a9c094b78371' was
gathered on 2021/04/05.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v048.i06 is OK

MISSING DOIs

- 10.1109/ijcnn.2019.8852333 may be a valid DOI for title: Interpretable Variational Autoencoders for Cognitive Models
- 10.31234/osf.io/tm2av may be a valid DOI for title: A Deep Learning Algorithm for High-Dimensional Exploratory Item Factor Analysis

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03151/joss.03151/10.21105.joss.03151.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03151/joss.03151/10.21105.joss.03151.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @converseg - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command @whedon check references to check again, and the command @whedon generate pdf when the references are right to make a new PDF. Whedon commands need to the be the first entry in a new comment.

**Comment by kyleniemeyer** [comment]
Hello @converseg, thanks for your interest in JOSS. Unfortunately, after a review by the editorial board, we found that your software is not in scope for JOSS, due to its small size.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
