### ISSUE TITLE
[PRE REVIEW]: mobilityIndexR: an R package to calculate transition matrices and mobility indices from numeric data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3152]
**Submitting author:** @bcmullins (<a href="http://orcid.org/0000-0002-8436-0091">Brett Mullins</a>)
**Repository:** <a href="https://github.com/bcmullins/mobilityIndexR" target ="_blank">https://github.com/bcmullins/mobilityIndexR</a>
**Version:** v0.2.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @bcmullins. **Currently, there isn't an JOSS editor assigned** to your paper.

@bcmullins if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (179.0 files/s, 20135.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               12             52            217            657
HTML                             1             90              5            463
Markdown                         4             77              0            396
TeX                              1              9              0             64
Rmd                              2             87            129             61
YAML                             1             15              7             33
-------------------------------------------------------------------------------
SUM:                            21            330            358           1674
-------------------------------------------------------------------------------


Statistical information for the repository '1fac49902ff035baec276730' was
gathered on 2021/04/05.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.23889/ijpds.v4i3.1184 may be a valid DOI for title: Using Linked Administrative Data to Measure Earnings Mobility of Public Assistance Recipients during the Great Recession
- 10.1093/oso/9780198815501.003.0015 may be a valid DOI for title: Income mobility

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03152/joss.03152/10.21105.joss.03152.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03152/joss.03152/10.21105.joss.03152.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @bcmullins - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to the be the first entry in a new comment.

**Comment by kyleniemeyer** [comment]
Hello @bcmullins, thanks for your interest in JOSS. The editorial board has reviewed your submission, and unfortunately found that your submission is too small to meet our requirement for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). If you extend your package, we might consider it again in the future.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
