### ISSUE TITLE
[REVIEW]: TRUNAJOD: A text complexity library to enhance natural language processing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3153]
**Submitting author:** @dpalmasan (<a href="http://orcid.org/0000-0003-1540-7164">Diego Palma</a>)
**Repository:** <a href="https://github.com/dpalmasan/TRUNAJOD2.0" target ="_blank">https://github.com/dpalmasan/TRUNAJOD2.0</a>
**Version:** v0.1.2
**Editor:** @danielskatz
**Reviewer:** @mbdemoraes, @apiad
**Archive:** <a href="https://doi.org/10.5281/zenodo.4707403" target="_blank">10.5281/zenodo.4707403</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/92d7b9ed329d0b30cfad311c045fb1d5/status.svg)](https://joss.theoj.org/papers/92d7b9ed329d0b30cfad311c045fb1d5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/92d7b9ed329d0b30cfad311c045fb1d5"><img src="https://joss.theoj.org/papers/92d7b9ed329d0b30cfad311c045fb1d5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/92d7b9ed329d0b30cfad311c045fb1d5/status.svg)](https://joss.theoj.org/papers/92d7b9ed329d0b30cfad311c045fb1d5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dpalmasan/TRUNAJOD2.0" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mbdemoraes & @apiad, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dpalmasan/TRUNAJOD2.0">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dpalmasan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dpalmasan/TRUNAJOD2.0">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dpalmasan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mbdemoraes, @apiad it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.47 s (39.4 files/s, 8339.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          26            596           1160           9646
Markdown                         3             82              0            270
TeX                              7             14              0            171
YAML                             4              5             10             73
reStructuredText                13             46             56             57
DOS Batch                        1              8              1             26
TOML                             1              1              0             22
INI                              2              2              0             21
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            58            758           1234          10295
-------------------------------------------------------------------------------


Statistical information for the repository '76f6d2c6eb33101c71282a2e' was
gathered on 2021/04/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bruce Lee                        2           189             30            0.57
Diego                            3          8579           8385           44.14
Diego Palma Sánchez              1           805              0            2.09
dpalma                           1           774              0            2.01
dpalmasan                       35         14568           5098           51.18

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Bruce Lee                   153           81.0          0.2               14.38
Diego                      8576          100.0          0.1                0.02
dpalmasan                  2673           18.3         14.7               13.92
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1080/01638539809545029 may be a valid DOI for title: The measurement of textual coherence with latent semantic analysis
- 10.1080/00220973.1994.9943835 may be a valid DOI for title: Computer grading of student prose, using modern concepts and software
- 10.3758/s13428-015-0684-y may be a valid DOI for title: Spanish norms for affective and lexico-semantic variables for 1,400 words

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03153/joss.03153/10.21105.joss.03153.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03153/joss.03153/10.21105.joss.03153.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @mbdemoraes and @apiad - Thanks for agreeing to review this submission.
This is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

Please read the first couple of comments in this issue carefully, so that you can accept the invitation from JOSS and be able to check items, and so that you don't get overwhelmed with notifications from other activities in JOSS.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#3153` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@danielskatz) if you have any questions/concerns.

**Comment by danielskatz** [comment]
👋 @dpalmasan, can you work on the possibly missing DOIs that whedon suggests, noting that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to the be the first entry in a new comment.

**Comment by dpalmasan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03153/joss.03153/10.21105.joss.03153.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03153/joss.03153/10.21105.joss.03153.pdf) :page_facing_up: :point_left:

**Comment by dpalmasan** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/01638539809545029 is OK
- 10.1080/00220973.1994.9943835 is OK
- 10.3758/s13428-015-0684-y is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by dpalmasan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03153/joss.03153/10.21105.joss.03153.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03153/joss.03153/10.21105.joss.03153.pdf) :page_facing_up: :point_left:

**Comment by mbdemoraes** [comment]
@dpalmasan great job so far! I believe these should be the last issues:

- https://github.com/dpalmasan/TRUNAJOD2.0/issues/50
- https://github.com/dpalmasan/TRUNAJOD2.0/issues/51

**Comment by dpalmasan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03153/joss.03153/10.21105.joss.03153.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03153/joss.03153/10.21105.joss.03153.pdf) :page_facing_up: :point_left:

**Comment by mbdemoraes** [comment]
@danielskatz My review has been completed.

**Comment by danielskatz** [comment]
@mbdemoraes - just to confirm, you are now satisfied that this work can be published?

**Comment by danielskatz** [comment]
👋 @apiad - there's no hurry, but how are things coming for you?

**Comment by mbdemoraes** [comment]
@danielskatz Sure! I'm ready to approve it.

**Comment by apiad** [comment]
> 👋 @apiad - there's no hurry, but how are things coming for you?

I'm pretty confident I'll get it done during the weekend. The work seems pretty solid. I just have to download and check the functional claims but other than that I'm quite convinced it's gonna be a smooth review.

**Comment by apiad** [comment]
Sorry, clicked a button by accident...

**Comment by apiad** [comment]
@dpalmasan I just checked all the functional claims and documentation. I opened a (hopefully easy) issue to improve the contribution guidelines just a little bit. 

I'm now reviewing the paper itself, and I have some suggestions. I'll finish reviewing it and open a single issue with all of them. Most of them are gonna are optional suggestions that I think can improve the quality of the writing, nothing too complex, mostly rewriting some long sentences and clarifying some points. I hope these suggestions help! 

Great work, BTW. I already said it elsewhere but as a Spanish-speaker NLP researcher, I'm very happy to see this kind of high-quality work in our native language.

**Comment by apiad** [comment]
@danielskatz what's in your opinion the best UX for a writing/grammar review? Should I open an issue and just say "where you say ... in line X" or is there a better way to use the Github UI, maybe opening a PR with suggested changes, etc.?

What I would ideally prefer is to go over `paper.md` and just add comments on specific lines, so the PR workflow seems perfect for this, but to open a PR I have to propose some changes and *then* add comments on the PR. Is there a better/suggested way? Thanks in advance.

**Comment by danielskatz** [comment]
@apiad - feel free to do whichever seems best to you. As an Associate Editor in Chief, I do a lot of proofreading, and generally use PRs, but that's just me

**Comment by apiad** [comment]
Hey @dpalmasan, just submitted a small PR with what I think could be minor fixes to the paper. Please forgive me for taking the freedom to directly suggest text changes, but I think is easier/faster than listing them here. Let me know if you wish to review anything, and of course, as the author, you have the final word on your paper. Hope my suggestions help a bit :smile:!

**Comment by dpalmasan** [comment]
No worries! It was actually a great idea. I already took the suggestions into account and updated some missing bits (the ones that were tagged as `<NAME>`. Thanks for the detailed review!

**Comment by apiad** [comment]
Awesome! Perfect then, @danielskatz this officially completes my review.

I'm extremely satisfied with the work and I sincerely think it's a great addition to the NLP community. Thanks, @dpalmasan again for your quick responses, and please extend my congratulations to your colleagues on such solid work.

**Comment by danielskatz** [comment]
👋 @dpalmasan - I've suggested a bunch of small changes to the paper and bib in https://github.com/dpalmasan/TRUNAJOD2.0/pull/57

**Comment by danielskatz** [comment]
The next step is for you to:
 - [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by dpalmasan** [comment]
Hello @danielskatz, I already merged your changes, thanks! Here are the items of the checklist:

- Tagged release with the reviewed software `v.0.1.2`: https://github.com/dpalmasan/TRUNAJOD2.0/releases/tag/v0.1.2
- Zenodo software archival: https://zenodo.org/record/4707403#.YIAa5RNKh70
- Metadata title and authors match the `paper.md`
- The archived version DOI: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4707403.svg)](https://doi.org/10.5281/zenodo.4707403)

Please let me know if further changes are needed

**Comment by danielskatz** [comment]
@whedon set 10.5281/zenodo.4707403 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4707403" target="_blank">10.5281/zenodo.4707403</a> is the archive.

**Comment by danielskatz** [comment]
@whedon set v0.1.2 as version

**Comment by whedon** [comment]
OK. v0.1.2 is the version.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2255

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2255, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon check references

**Comment by danielskatz** [comment]
👋 @openjournals/dev - Can you see why ☝️ doesn't seem to be returning, and wasn't completed as part of the `accept` process?

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/01638539809545029 is OK
- 10.1080/00220973.1994.9943835 is OK
- 10.3758/s13428-015-0684-y is OK
- 10.3758/s13428-018-1142-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1384862337627209728) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2256
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03153](https://doi.org/10.21105/joss.03153)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @dpalmasan (Diego Palma) and co-authors on your publication!!

And thanks to @mbdemoraes and @apiad for reviewing!

As the editor, this was a very quick and smooth process that worked well as everyone was quite collaborative and responsive - thank again to all of you!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03153/status.svg)](https://doi.org/10.21105/joss.03153)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03153">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03153/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03153/status.svg
   :target: https://doi.org/10.21105/joss.03153
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03153/status.svg)](https://doi.org/10.21105/joss.03153)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
