### ISSUE TITLE
[PRE REVIEW]: nrCascadeSim - A simulation tool for nuclear recoil cascades resulting from neutron capture

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3154]
**Submitting author:** @gerudo7 (<a href="http://orcid.org/0000-0001-5406-8367">Kitty Harris</a>)
**Repository:** <a href="https://github.com/villano-lab/nrCascadeSim" target ="_blank">https://github.com/villano-lab/nrCascadeSim</a>
**Version:** 1.0.1
**Editor:** @mbobra
**Reviewers:** @kelseymh, @matthewfeickert
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gerudo7. **Currently, there isn't an JOSS editor assigned** to your paper.

@gerudo7 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.55 s (102.8 files/s, 19220.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                               13            711            970           2536
SVG                              1              0             21           2247
C++                             11            252            251            929
Python                           6            144            236            501
C/C++ Header                    10            154            308            484
Markdown                         5             69              0            236
make                             2             22              8             69
HTML                             1             12              1             67
Jupyter Notebook                 1              0            129             65
TeX                              1              7              1             65
Bourne Shell                     2             11              3             55
YAML                             3              2              4             54
CSS                              1              6              0             31
-------------------------------------------------------------------------------
SUM:                            57           1390           1932           7339
-------------------------------------------------------------------------------


Statistical information for the repository '00fb6e311bf45304e2e7b2b1' was
gathered on 2021/04/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Anthony Villano                  2          6962              1           78.07
Kitty                            2           881           1075           21.93

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Anthony Villano            5886           84.5          0.0               26.95
Kitty                       881          100.0          1.1               25.99
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevD.91.083509 is OK

MISSING DOIs

- 10.1515/iupac.70.0026 may be a valid DOI for title: Isotopic Compositions of the Elements 1997
- 10.1103/physrevc.43.1086 may be a valid DOI for title: Radiative strength functions of germanium from thermal neutron capture

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03154/joss.03154/10.21105.joss.03154.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03154/joss.03154/10.21105.joss.03154.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @gerudo7 - On possibly missing DOIs that whedon suggests, note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to the be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @mbobra - Would you be able to edit this submission too?

**Comment by danielskatz** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by pibion** [comment]
@mbobra if you'd like any help finding reviewers I'm happy to help out!

**Comment by mbobra** [comment]
@whedon assign me as editor

**Comment by mbobra** [comment]
@pibion Thank you! I appreciate it. If you have any suggested reviewers, please let me know here (you can give me the Github handle without @ mentioning them, e.g. mbobra instead of @mbobra).

**Comment by gerudo7** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1515/iupac.70.0026 is OK
- 10.1103/PhysRevD.91.083509 is OK
- 10.1103/physrevc.43.1086 is OK
- 10.1103/PhysRevC.46.972 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by gerudo7** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03154/joss.03154/10.21105.joss.03154.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03154/joss.03154/10.21105.joss.03154.pdf) :page_facing_up: :point_left:

**Comment by villaa** [comment]
@mbobra I am a co-author of this paper alongside @gerudo7 who submitted the paper. The paper doesn't show up in my JOSS profile but it does in @gerudo7 . Is there a way to make it show up in mine too as a convenience?

**Comment by gerudo7** [comment]
@mbobra Hi! We have a couple of reviewer suggestions who are not on the list. The first is kelseymh. We don't know the second person's github username. Since this is publicly visible we didn't want to give their contact information without asking first - what's the best way to indicate who they are?

Regarding the list, we looked for people who were comfortable with physics - preferably particle physics - and C++. We identified mathtewfeickert and db87.

**Comment by villaa** [comment]
@mbobra another possible reviewer is a collaborator of mine on a different project, github handle: tsaab. He is familiar with coding in C and the physics behind our code submission, but has not worked on this project with us.

**Comment by mbobra** [comment]
> @mbobra I am a co-author of this paper alongside @gerudo7 who submitted the paper. The paper doesn't show up in my JOSS profile but it does in @gerudo7 . Is there a way to make it show up in mine too as a convenience?

I don't think so, I'm sorry! Our system attaches the paper to the submitting author. @openjournals/joss-eics Can you please confirm?

**Comment by mbobra** [comment]
@whedon assign @kelseymh as reviewer

**Comment by whedon** [comment]
OK, @kelseymh is now a reviewer

**Comment by arfon** [comment]
> I don't think so, I'm sorry! Our system attaches the paper to the submitting author. @openjournals/joss-eics Can you please confirm?

Yeah, I'm afraid the paper can only be associated with a single author in our submission system.

**Comment by mbobra** [comment]
@whedon add @matthewfeickert as reviewer

**Comment by whedon** [comment]
OK, @matthewfeickert is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3174.

**Comment by mbobra** [comment]
👋 @kelseymh @matthewfeickert @gerudo7 See you over in #3174 where we'll do the review!
