### ISSUE TITLE
[PRE REVIEW]: gm: R Package for Creating Music

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3155]
**Submitting author:** @flujoo (<a href="http://orcid.org/0000-0002-2841-9570">Renfei Mao</a>)
**Repository:** <a href="https://github.com/flujoo/gm" target ="_blank">https://github.com/flujoo/gm</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @flujoo. **Currently, there isn't an JOSS editor assigned** to your paper.

@flujoo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.30 s (250.5 files/s, 58824.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            33           1559            453           4845
R                               22           1790           1574           4806
CSS                              3             99             48            428
JavaScript                       4             64             34            266
Markdown                         5            100              0            244
Rmd                              2            292            439            190
TeX                              1              6              0             61
XML                              1              0              0             51
YAML                             2              3              0             15
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            74           3913           2549          10917
-------------------------------------------------------------------------------


Statistical information for the repository '0bdaa3e117838827bde84390' was
gathered on 2021/04/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
flujoo                           1           364              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
flujoo                      364          100.0          0.0                9.34
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1126/scitranslmed.aaf5027 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03155/joss.03155/10.21105.joss.03155.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03155/joss.03155/10.21105.joss.03155.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@flujoo - The editors will now discuss if this submission is in scope for JOSS review - you should hear back in a week or so

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by flujoo** [comment]
potential reviewer: brunaw

**Comment by flujoo** [comment]
@danielskatz May I ask why my submission being in scope is in question? If it is for the [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) requirement, I think my paper is similar to the published JOSS paper [An easy-to-use p5.js 3D object picker for visual artists](https://joss.theoj.org/papers/10.21105/joss.00475). The works in these two papers seem only about art creation, and they don't directly solve scientific problems, but they provide tools or languages for art-related researches such as that in this published JOSS paper [Opycleid: A Python package for transformational music theory](https://joss.theoj.org/papers/10.21105/joss.00981) to better describe or frame research questions.

**Comment by danielskatz** [comment]
@flujoo - Thanks for your explanation, which the editors will consider when discussing the submission.  Also, be aware that JOSS requirements have changed over time, and there are certainly submissions from a few years that we would no longer consider in scope.

**Comment by flujoo** [comment]
@danielskatz I understand that. Thanks for your clarification.

**Comment by kyleniemeyer** [comment]
Hello @flujoo, thanks for your interest in JOSS. The editorial board has considered your submission, and unfortunately we found that it falls outside our current scope of [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software). We do realize that our scope has narrowed somewhat over time as the journal has matured. We suggest that you consider [alternate venues](https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages) for reviewing and publishing software packages.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by flujoo** [comment]
Thank you all all the same.
