### ISSUE TITLE
[PRE REVIEW]: FURY: advanced scientific visualization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3158]
**Submitting author:** @garyfallidis (<a href="http://orcid.org/0000-0002-3991-2774">Eleftherios Garyfallidis</a>)
**Repository:** <a href="https://github.com/fury-gl/fury" target ="_blank">https://github.com/fury-gl/fury</a>
**Version:** master
**Editor:** @danielskatz
**Reviewers:** @chrishavlin, @rougier, @phamvanvung
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @garyfallidis. **Currently, there isn't an JOSS editor assigned** to your paper.

@garyfallidis if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.60 s (377.8 files/s, 70342.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         102           6513          10182          17043
reStructuredText                69           1140            672           2179
CSS                              3             22              5           1649
JSON                            16              1              0            576
GLSL                            11            158             78            370
Markdown                         7            120              0            270
YAML                             4             22             26            235
TeX                              1             27              0            223
HTML                             2              8             20            204
DOS Batch                        2             16              1            131
Bourne Shell                     3             18             17            101
PowerShell                       3             15             19             85
JavaScript                       2             12              1             68
make                             1              7              6             25
INI                              1              0              0              5
-------------------------------------------------------------------------------
SUM:                           227           8079          11027          23164
-------------------------------------------------------------------------------


Statistical information for the repository '5ea989ace3f52d17358dcb7b' was
gathered on 2021/04/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adam                             1             1              0            0.00
Alexandre Gauvin                 2            38             20            0.07
Aman Soni                        1             1              1            0.00
Ariel Rokem                     48           519            725            1.43
Bago Amirbekian                 11           198            201            0.46
Bishakh Ghosh                    3            52             26            0.09
ChenCheng0630                    7           202             62            0.30
Christopher Nguyen               2            23              3            0.03
David Reagan                    22           593            259            0.98
Devanshu Modi                    1            16             16            0.04
Eleftherios Garyfall           457         13588           8296           25.22
Enes Albay                       5            28             11            0.04
Etienne St-Onge                 12           638            393            1.19
Filipi Nascimento Si             6           289             37            0.38
Gauvin Alexandre                 1             3              0            0.00
Gottipati Gautam                 2             6              6            0.01
Gregory R. Lee                   5            34             21            0.06
Guillaume Favelier               4           160             13            0.20
Ian Nimmo-Smith                  1             2              0            0.00
Javier Guaje                    12          1773           1229            3.46
Jiri Borovec                     2             6             23            0.03
Jon Haitz Legarreta              6            34             35            0.08
Karan                           49          2496            404            3.34
Kesshi Jordan                   11           420            205            0.72
Kevin Sitek                     10            34             15            0.06
Lenix Lobo                      47          1027            536            1.80
Liam Donohue                     4           313             10            0.37
Marc-Alexandre Côté             56          5087           3081            9.41
Marssis                          2            14             14            0.03
Matthew Brett                   17           223            588            0.93
Melina Raglin                   52          1291            263            1.79
Naman Bansal                    14            62             17            0.09
Nasim Anousheh                  20           554            282            0.96
Omar Ocegueda                   10           964            186            1.33
Pietro Astolfi                   1             1              1            0.00
Prashil                         26           379            246            0.72
Ranveer Aggarwal                72          3515            747            4.91
Sajag Swami                      2            19             10            0.03
Samuel St-Jean                   1            12             14            0.03
Sanjay Marreddi                  9           359            131            0.56
Saransh Jain                    16           420            105            0.60
Scott Trinkle                    2             2              4            0.01
Serge Koudoro                  428         16194           7157           26.91
Shahnawaz Ahmed                  4            11              7            0.02
Shreyas Bhujbal                 16           149             52            0.23
Soham Biswas                   172          5126           2056            8.28
Stefan van der Walt              5           263            162            0.49
Tingyi Wanyan                    5           128            128            0.29
Tushar                          15           328             55            0.44
Vivek Choudhary                 22           693            193            1.02
Yaroslav Halchenko               1             3              2            0.01
ganimtron-10                     1             1              1            0.00
ibrahimAnis                     11           318            122            0.51
theaverageguy                    3             3              3            0.01
wasserth                         1             1              1            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alexandre Gauvin             28           73.7         65.6                0.00
Aman Soni                     1          100.0          0.0                0.00
Ariel Rokem                   5            1.0         53.9                0.00
ChenCheng0630               159           78.7         10.9               17.61
David Reagan                246           41.5         27.3               16.26
Devanshu Modi                16          100.0         10.3                0.00
Eleftherios Garyfall       3852           28.3         42.8                7.66
Enes Albay                   17           60.7         32.5               11.76
Etienne St-Onge             265           41.5         48.3                7.92
Filipi Nascimento Si        247           85.5         11.3               17.00
Gottipati Gautam              6          100.0         11.4              100.00
Gregory R. Lee                1            2.9         60.3                0.00
Guillaume Favelier           72           45.0         19.7                1.39
Javier Guaje               2029          114.4          8.7               10.05
Jiri Borovec                  1           16.7         34.6              100.00
Jon Haitz Legarreta          33           97.1         16.6                0.00
Karan                      1593           63.8         31.7               13.43
Kesshi Jordan               177           42.1         47.1               10.73
Kevin Sitek                   6           17.6         22.8               16.67
Lenix Lobo                  393           38.3          9.1               12.21
Liam Donohue                233           74.4         10.8                3.00
Marc-Alexandre Côté        3042           59.8         35.1               10.49
Marssis                      14          100.0         15.2                0.00
Melina Raglin               926           71.7          7.4               18.90
Naman Bansal                 47           75.8          9.8                6.38
Nasim Anousheh              270           48.7          8.8               24.07
Pietro Astolfi                1          100.0          5.4                0.00
Prashil                     111           29.3         24.2                2.70
Ranveer Aggarwal           1039           29.6         47.6               14.05
Sajag Swami                 507         2668.4         -0.7               18.34
Sanjay Marreddi             227           63.2          3.1               24.23
Saransh Jain                280           66.7         11.5               24.64
Serge Koudoro             13072           80.7         21.4               12.85
Shreyas Bhujbal              98           65.8         10.9                3.06
Soham Biswas               3237           63.1          6.8               12.64
Tushar                      288           87.8          3.5               10.76
Vivek Choudhary             302           43.6         10.8               11.59
ganimtron-10                  1          100.0          0.1                0.00
haran2001                    16          100.0         -0.7                0.00
ibrahimAnis                 168           52.8         10.4               10.71
wasserth                      1          100.0         32.0                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03158/joss.03158/10.21105.joss.03158.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03158/joss.03158/10.21105.joss.03158.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201629272 is OK
- 10.1051/0004-6361/201322068 is OK

MISSING DOIs

- 10.25080/majora-92bf1922-00a may be a valid DOI for title: Data structures for statistical computing in python
- 10.1109/mcse.2007.55 may be a valid DOI for title: Matplotlib: A 2D graphics environment
- 10.25080/majora-7b98e3ed-00e may be a valid DOI for title: VisPy: harnessing the GPU for fast, high-level visualization
- 10.1109/mcse.2011.35 may be a valid DOI for title: Mayavi: 3D visualization of scientific data
- 10.3389/fninf.2014.00008 may be a valid DOI for title: Dipy, a library for the analysis of diffusion MRI data
- 10.1515/nano.0034.00034 may be a valid DOI for title: nanoHUB. org: cloud-based services for nanoscale modeling, simulation, and education
- 10.1109/nmdc.2011.6155316 may be a valid DOI for title: Network for computational nanotechnology-a strategic plan for global knowledge transfer in research and education

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @Garyfallidis - thanks for your submission.  The editors will now discuss if it meets the [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to the be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Garyfallidis** [comment]
Thank you @danielskatz

**Comment by skoudoro** [comment]
@whedon check references

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.25080/majora-92bf1922-00a is OK
- 10.1109/mcse.2007.55 is OK
- 10.25080/majora-7b98e3ed-00e is OK
- 10.1109/mcse.2011.35 is OK
- 10.3389/fninf.2014.00008 is OK
- 10.1051/0004-6361/201629272 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.1515/ntrev-2012-0043 is OK
- 10.1109/nmdc.2011.6155316 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Garyfallidis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03158/joss.03158/10.21105.joss.03158.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03158/joss.03158/10.21105.joss.03158.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @Garyfallidis, the JOSS editorial board reviewed your submission and found that it is within our scope. However, due to a lack of suitable and available editors, I'm going to put this on our waitlist for now. We will assign this to an editor as soon as one becomes available.

**Comment by Garyfallidis** [comment]
Thank you @kyleniemeyer

**Comment by Garyfallidis** [comment]
Perhaps @jni could be a potential editor for this ?

**Comment by jni** [comment]
Thanks for the ping @Garyfallidis! It's indeed right up my alley but I'm currently editing two other manuscripts and don't have the bandwidth for another. Happy to pick it up once my queue is clear, or perhaps another editor will have availability...

**Comment by Garyfallidis** [comment]
Sounds good @jni.

**Comment by arfon** [comment]
@whedon invite @leouieda as editor

:wave: @leouieda - would you be able to handle this submission for us?

**Comment by whedon** [comment]
@leouieda has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@leouieda - would you be able to handle this submission for us?

**Comment by danielskatz** [comment]
👋 @leouieda - just a ping...

**Comment by danielskatz** [comment]
@whedon assign me as editor

I'll take this to get it off the waiting list...

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @Garyfallidis - Can you suggest some potential reviewers by mentioning them here in this thread (without tagging them with an @).

[This list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by danielskatz** [comment]
👋 @matthewturk - Would you (or someone in your group/lab) be willing to review this for JOSS?  As I think you know, we carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by danielskatz** [comment]
👋 @chrishavlin - I hear you might be willing to review this submission?

**Comment by chrishavlin** [comment]
Yes! I won't be able to start reviewing until the week of June 1,but assuming that is OK, I'm happy to review this submission.

**Comment by danielskatz** [comment]
Thanks @chrishavlin!
I'll assign you now, and when I find another reviewer, start the review, but with the understanding that you won't start until the week of June 1.

**Comment by danielskatz** [comment]
@whedon assign @chrishavlin as reviewer

**Comment by whedon** [comment]
OK, @chrishavlin is now a reviewer

**Comment by Garyfallidis** [comment]
Much appreciated @chrishavlin ! And thank you @danielskatz for pushing this forward. :+1:

**Comment by danielskatz** [comment]
@Garyfallidis - note that I'm also looking for reviewer suggestions from you, as requested in https://github.com/openjournals/joss-reviews/issues/3158#issuecomment-845342011

**Comment by Garyfallidis** [comment]
Sure, will get back to you asap.

**Comment by chrishavlin** [comment]
@danielskatz should the review checklist be automatically added or do I add that? Or does that show up when this is switched from Pre Review to Review?

**Comment by danielskatz** [comment]
It's automatically generated in the review issue.  You can start working if you have time, and just keep some local notes that you can put there once we find another reviewer and start the review

**Comment by chrishavlin** [comment]
Ok, got it! Thanks!

**Comment by danielskatz** [comment]
👋 @Garyfallidis - any reviewer suggestions from you, as requested in https://github.com/openjournals/joss-reviews/issues/3158#issuecomment-845342011 ?  I would like to start this review soon

**Comment by danielskatz** [comment]
👋 @hankchilds, @ARSanderson, @BradWhitlock - would one of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by Garyfallidis** [comment]
Thank you @danielskatz. I hope we will hear soon from @hankchilds, @ARSanderson and @BradWhitlock. Otherwise, @jankatins, @zfurnas, @a-slide and @tuchandra seem relevant.

**Comment by danielskatz** [comment]
👋 @jankatins, @alexanderfurnas, @a-slide, @tuchandra - Would one of you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
👋  @hankchilds, @ARSanderson, @BradWhitlock, @jankatins, @alexanderfurnas, @a-slide, @tuchandra - re-ping...

I'm looking for one additional reviewer to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by danielskatz** [comment]
I'm continuing to look for a second reviewer, now via https://twitter.com/danielskatz/status/1405600484442923014?s=20

**Comment by rougier** [comment]
I can probably review starting next week.

**Comment by phamvanvung** [comment]
I can also review starting Friday next week onward.

**Comment by danielskatz** [comment]
Great, thanks to both of you - I'm going to add you both, and start the review, but you don't need to start immediately

**Comment by danielskatz** [comment]
@whedon add @rougier as reviewer

**Comment by whedon** [comment]
OK, @rougier is now a reviewer

**Comment by danielskatz** [comment]
@whedon add @phamvanvung as reviewer

**Comment by whedon** [comment]
OK, @phamvanvung is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3384.
