### ISSUE TITLE
[PRE REVIEW]: microViz: an R package for microbiome data visualization and statistics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3160]
**Submitting author:** @david-barnett (<a href="http://orcid.org/0000-0003-1961-7206">David Barnett</a>)
**Repository:** <a href="https://github.com/david-barnett/microViz" target ="_blank">https://github.com/david-barnett/microViz</a>
**Version:** 0.7.0
**Editor:** @lpantano
**Reviewers:** @marypiper
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @david-barnett. **Currently, there isn't an JOSS editor assigned** to your paper.

@david-barnett if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.48 s (222.5 files/s, 35831.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               76            541           3294           4491
SVG                              1              0              0           2852
Markdown                        14            531              0           2547
JSON                             5             25              0           1669
Rmd                              4            154            279            343
YAML                             5             35              6            199
TeX                              1             11              0             94
-------------------------------------------------------------------------------
SUM:                           106           1297           3579          12195
-------------------------------------------------------------------------------


Statistical information for the repository '87d93a79de3668c2f2dacbc2' was
gathered on 2021/04/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
David Barnett                    4           496            496          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03160/joss.03160/10.21105.joss.03160.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03160/joss.03160/10.21105.joss.03160.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01686 is OK
- 10.1371/journal.pcbi.1005404 is OK
- 10.1214/19-AOAS1283 is OK

MISSING DOIs

- 10.1371/journal.pone.0061217 may be a valid DOI for title: phyloseq: An R package for reproducible interactive analysis and graphics of microbiome census data

INVALID DOIs

- https://doi.org/10.1111/2041-210X.12628 is INVALID because of 'https://doi.org/' prefix
```

**Comment by danielskatz** [comment]
👋 @lpantano - are you able to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @lpantano as editor

**Comment by whedon** [comment]
@lpantano has been invited to edit this submission.

**Comment by danielskatz** [comment]
👋 @david-barnett - You could work on the possibly missing DOI that whedon suggests, but note that this may be incorrect, and remove the prefix from the other. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to the be the first entry in a new comment.

**Comment by david-barnett** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01686 is OK
- 10.1371/journal.pcbi.1005404 is OK
- 10.1371/journal.pone.0061217 is OK
- 10.1111/2041-210X.12628 is OK
- 10.1214/19-AOAS1283 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by david-barnett** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03160/joss.03160/10.21105.joss.03160.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03160/joss.03160/10.21105.joss.03160.pdf) :page_facing_up: :point_left:

**Comment by david-barnett** [comment]
Regarding potential reviewers, perhaps:
kelly-sovacool (from the joss_reviewers spreadsheet) 
+ joey711 / mikemc / antagomir ?

**Comment by lpantano** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by lpantano** [comment]
@mikemc, would you be interested in reviewing this tool? Thanks!

**Comment by mikemc** [comment]
@lpantano I am unable to accept review requests right now, sorry! I can try to come up with some suggestions if that helps

**Comment by lpantano** [comment]
@whedon assign @marypiper as reviewer

**Comment by whedon** [comment]
OK, @marypiper is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3201.
