### ISSUE TITLE
[PRE REVIEW]: Eir: A Python Package for Epidemic Simulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3161]
**Submitting author:** @mjacob1002 (<a href="http://orcid.org/0000-0001-5513-432X">Mathew Jacob</a>)
**Repository:** <a href="https://github.com/mjacob1002/Eir" target ="_blank">https://github.com/mjacob1002/Eir</a>
**Version:** v 0.1.20
**Editor:** @will-rowe
**Reviewers:** @DARSakthi, @joeweaver
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mjacob1002. **Currently, there isn't an JOSS editor assigned** to your paper.

@mjacob1002 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.49 s (387.6 files/s, 38460.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         148           3076           5693           8983
Markdown                        30            308              0            535
XML                             10              0              0            182
TeX                              1              5              0             64
JSON                             1              0              0              5
-------------------------------------------------------------------------------
SUM:                           190           3389           5693           9769
-------------------------------------------------------------------------------


Statistical information for the repository '337a3f6245cfddf95eb6ec62' was
gathered on 2021/04/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Eva Xueyao Guo                   1           114              0            0.35
Mathew Jacob                   246         24977           7339           99.65

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mathew Jacob              17752           71.1          0.3               11.04
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1098/rspa.1927.0118 is OK
- 10.1016/j.physa.2006.08.050 is OK
- 10.1016/j.idm.2017.03.001 is OK
- 10.21105/joss.01731 is OK
- 10.18637/jss.v084.i08 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03161/joss.03161/10.21105.joss.03161.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03161/joss.03161/10.21105.joss.03161.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@will-rowe - would you be able to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @will-rowe as editor

**Comment by whedon** [comment]
@will-rowe has been invited to edit this submission.

**Comment by will-rowe** [comment]
Hi @smjenness - would you be willing to review this submission to JOSS?

**Comment by will-rowe** [comment]
Hi @joelmiller - would you be able to review this?

**Comment by joelmiller** [comment]
Unfortunately I am too busy right now to take on any new reviewing tasks.

**Comment by will-rowe** [comment]
No worries @joelmiller - thanks for your reply.

**Comment by will-rowe** [comment]
Hi @aineniamh - are you able to review this please? Or do you have any suggestions for other reviewers?

**Comment by smjenness** [comment]
The "manuscript" (really just an extended abstract) appears fine. I am not able to review the software itself, as I don't work in Python.

**Comment by aineniamh** [comment]
Hey @will-rowe, I'm really sorry but I'm the same as Joel right now. I can't commit to any new reviewing tasks- trying to fit thesis writing around the current pandemic workload too.

**Comment by kyleniemeyer** [comment]
@whedon assign @will-rowe as editor

(whoops, realized we didn't formally assign this)

**Comment by whedon** [comment]
OK, the editor is @will-rowe

**Comment by will-rowe** [comment]
Thanks both - I'll keep trying. Good luck with the write up @aineniamh!

**Comment by will-rowe** [comment]
Hi @acolum - would you be able to review this for us?

**Comment by will-rowe** [comment]
Hi @giskid - would you be able to review this JOSS submission?

**Comment by acolum** [comment]
Hi Will,

Thank you for contacting me, but I have too many other commitments at the
moment to review this submission.

Best,
Alyssa

**Comment by will-rowe** [comment]
Hi @seabbs, @gakhov, @DARSakthi - would any of you please be able to review this JOSS submission?

**Comment by GISKid** [comment]
This loooks really important. I do not have capacity at this time.

**Comment by DARSakthi** [comment]
I could take a look at it -- but I am a bit busy heading into the end of term and preparing for summer. Its a short paper, so maybe the delay won't be appreciable. I'll leave it up to you @will-rowe 

Dalton Sakthivadivel
Biomedical Engineering
Renaissance School of Medicine

**Comment by will-rowe** [comment]
Hi @DARSakthi - thank you! I'd be happy to accept your offer if you can manage it within the next month or so?

**Comment by DARSakthi** [comment]
A month sounds doable

**Comment by will-rowe** [comment]
@whedon assign @DARSakthi as reviewer

**Comment by whedon** [comment]
OK, @DARSakthi is now a reviewer

**Comment by will-rowe** [comment]
Thanks @DARSakthi  - we will find one more reviewer and then start the review thread. I'll keep you posted

**Comment by DARSakthi** [comment]
Cheers

**Comment by will-rowe** [comment]
Hi @emilydolson, @chrisvoncsefalvay, @joeweaver - would any of you be able to review this submission to JOSS?

**Comment by joeweaver** [comment]
Hi Will,

I'd be a first time reviewer for JOSS, so thanks for having a review
checklist publicly available so I know what I'd be responsible for
evaluating. I'd be happy to review and would almost certainly have time
within the next two weeks to do so (likely much sooner, but cannot
guarantee).

I can say, based on a cursory look at the git repo, I'd have some issues
with the minimal documentation.

--Joe

**Comment by mjacob1002** [comment]
Hi @joeweaver,

Thanks for the feedback! Just to clarify for myself: should I move the docstrings in the files python files themselves to the "docs" folder or add more to the docstrings themselves?

Best,
Mathew

**Comment by will-rowe** [comment]
Thanks very much @joeweaver - we'll assign you and then kick off the review thread.

**Comment by will-rowe** [comment]
@whedon add @joeweaver as reviewer

**Comment by whedon** [comment]
OK, @joeweaver is now a reviewer

**Comment by will-rowe** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3247.

**Comment by joeweaver** [comment]
The docstrings look ok. Probably no need to move all the variable
explanations over (no need to put the whole API into the paper, which I
gather is counter to JOSS), but maybe do so for the example in the README
file.  The goal (at least from the perspective of a reviewer coming from
outside epidemiology) is to provide just a touch more context.

**Comment by emilydolson** [comment]
I'd be happy to review this paper! Looks like a cool package!
