### ISSUE TITLE
[PRE REVIEW]: Merly.jl: Web Framework in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3162]
**Submitting author:** @neomatrixcode (<a href="http://orcid.org/0000-0002-4056-1895">JOSUE ACEVEDO MALDONADO</a>)
**Repository:** <a href="https://github.com/neomatrixcode/Merly.jl" target ="_blank">https://github.com/neomatrixcode/Merly.jl</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @neomatrixcode. **Currently, there isn't an JOSS editor assigned** to your paper.

@neomatrixcode if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3162 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03162/joss.03162/10.21105.joss.03162.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03162/joss.03162/10.21105.joss.03162.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2872427.2883029 is OK
- 10.1145/1060745.1060746 is OK
- 10.1145/872757.872793 is OK
- 10.1145/3053600.3053653 is OK

MISSING DOIs

- 10.1137/141000671 may be a valid DOI for title: Julia: A Fresh Approach to Numerical Computing
- 10.1016/0001-8708(90)90053-p may be a valid DOI for title: Lambda-Calculus, Combinators and Functional Programming

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @neomatrixcode - thanks for your submission.  The editors will now discuss if it meets the [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by neomatrixcode** [comment]
@danielskatz thank you very much for your help.

**Comment by kyleniemeyer** [comment]
Hello @neomatrixcode, thanks for your interest in JOSS. The editorial board has reviewed your submission, and unfortunately finds that it is not in scope for review by JOSS, due to not being considered research software by [our definition](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software).

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
