### ISSUE TITLE
[PRE REVIEW]: FIRESONG: A python package to simulate populations of extragalactic neutrino sources

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3163]
**Submitting author:** @ChrisCFTung (<a href="http://orcid.org/0000-0001-6920-7841">Chun Fai Tung</a>)
**Repository:** <a href="https://github.com/icecube/FIRESONG" target ="_blank">https://github.com/icecube/FIRESONG</a>
**Version:** v1.6
**Editor:** @eloisabentivegna
**Reviewers:** @JostMigenda, @rafaelab
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ChrisCFTung. **Currently, there isn't an JOSS editor assigned** to your paper.

@ChrisCFTung if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (199.2 files/s, 70115.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             8            729              0           6714
Python                          16            499            956           1375
Markdown                         4             54              0            277
TeX                              1             18              0            239
YAML                             2              2              4             42
-------------------------------------------------------------------------------
SUM:                            31           1302            960           8647
-------------------------------------------------------------------------------


Statistical information for the repository 'b8d1884225cafe2ebcc8d539' was
gathered on 2021/04/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex Pizzuto                    27          1283            317           13.81
ChrisCFTung                      3           113             32            1.25
Chun Fai Tung                   58          1111            267           11.89
Ignacio Taboada                 73          1681           2002           31.79
Konstancja Satalecka             3           210             11            1.91
Michael Larson                   6            42             26            0.59
René Reimann                    71          2876           1615           38.76

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alex Pizzuto               1131           88.2          1.1               12.29
ChrisCFTung                 112           99.1          1.9               13.39
Chun Fai Tung               227           20.4         34.1               14.54
Ignacio Taboada              86            5.1         22.7               12.79
Michael J Larson             35          100.0          1.0                5.71
René Reimann               1239           43.1         36.6               10.01
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03163/joss.03163/10.21105.joss.03163.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03163/joss.03163/10.21105.joss.03163.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3847/1538-4357/abcaa4 is OK
- 10.1103/PhysRevLett.124.051103 is OK
- 10.1140/epjc/s10052-019-6680-0 is OK
- 10.1126/science.aat1378 is OK
- 10.1126/science.aat2890 is OK
- 10.3847/1538-4357/835/1/45 is OK
- 10.1088/2041-8205/805/1/L5 is OK
- 10.1103/PhysRevD.94.103006 is OK
- 10.1088/1742-6596/632/1/012039 is OK

MISSING DOIs

- 10.22323/1.358.1004 may be a valid DOI for title: Characterization of the Astrophysical Diffuse Neutrino Flux with IceCube High-Energy Starting Events
- 10.22323/1.358.1017 may be a valid DOI for title: Measurement of the diffuse astrophysical muon-neutrino spectrum with ten years of IceCube data
- 10.22323/1.358.1015 may be a valid DOI for title: First Double Cascade Tau Neutrino Candidates in IceCube and a New Measurement of the Flavor Composition
- 10.22323/1.301.0663 may be a valid DOI for title: Constrains on the extragalactic origin of IceCube’s neutrinos using HAWC
- 10.22323/1.358.1017 may be a valid DOI for title: Measurement of the diffuse astrophysical muon-neutrino spectrum with ten years of IceCube data

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @ChrisCFTung - thanks for your submission. Due to a lack of suitable and available editors, I'm going to put this on our waitlist for now.

**Comment by danielskatz** [comment]
In the meantime, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by kyleniemeyer** [comment]
@whedon invite @eloisabentivegna as editor

Hi @eloisabentivegna, can you edit this? We are trying to work through our backlog of submissions.

**Comment by whedon** [comment]
@eloisabentivegna has been invited to edit this submission.

**Comment by eloisabentivegna** [comment]
@kyleniemeyer, certainly!

**Comment by eloisabentivegna** [comment]
@whedon  assign @eloisabentivegna as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by eloisabentivegna** [comment]
@whedon assign @eloisabentivegna as editor

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by eloisabentivegna** [comment]
@JostMigenda, @apizzuto, would you be able to review this submission?

**Comment by JostMigenda** [comment]
I’m happy to review this, yes!
It looks like @apizzuto is a co-author on this paper, though, and therefore can’t be a reviewer.

**Comment by apizzuto** [comment]
Thanks @JostMigenda for offering to review!
Jost is correct that I can't because I'm one of the authors of this work, but I look forward to working with you both during review!

**Comment by eloisabentivegna** [comment]
Thanks, @JostMigenda! And thanks to both for clarifying.

**Comment by eloisabentivegna** [comment]
@rafaelab, would you be available to review this submission?

**Comment by rafaelab** [comment]
> @rafaelab, would you be available to review this submission?

I'd be happy to do it.

**Comment by eloisabentivegna** [comment]
Thanks, @rafaelab!

**Comment by eloisabentivegna** [comment]
@whedon add @JostMigenda as reviewer

**Comment by whedon** [comment]
OK, @JostMigenda is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon add @rafaelab as reviewer

**Comment by whedon** [comment]
OK, @rafaelab is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3194.
