### ISSUE TITLE
[PRE REVIEW]: yaml2sbml: Human-readable and -writable specification of ODE models and their conversion to SBML

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3164]
**Submitting author:** @jvanhoefer (<a href="http://orcid.org/0000-0002-3451-1701">Jakob Vanhoefer</a>)
**Repository:** <a href="https://github.com/yaml2sbml-dev/yaml2sbml" target ="_blank">https://github.com/yaml2sbml-dev/yaml2sbml</a>
**Version:** v0.2.2
**Editor:** @kellyrowland
**Reviewers:** @SirSharpest, @marouenbg
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jvanhoefer. **Currently, there isn't an JOSS editor assigned** to your paper.

@jvanhoefer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (636.1 files/s, 69930.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            588            808           1297
YAML                            20            424             10           1167
SVG                              3              0              0            467
reStructuredText                11            191            106            262
Markdown                         4             51              0            209
Jupyter Notebook                 6              0           1240            182
XML                              1              0              0            179
INI                              1              9              0             76
DOS Batch                        1              8              1             26
Bourne Shell                     2             11              8             25
make                             1              5              7              9
-------------------------------------------------------------------------------
SUM:                            67           1287           2180           3899
-------------------------------------------------------------------------------


Statistical information for the repository 'ca1ed860e3c58582d84d3165' was
gathered on 2021/04/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dilan Pathirana                  2           113              4            1.92
Jakob Vanhoefer                 97          3592           1389           81.79
Yannik Schälte                   5            64             90            2.53
dilpath                          3            10             16            0.43
martamatos                       9           698             77           12.73
yannikschaelte                   1            27             10            0.61

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dilan Pathirana             104           92.0          1.9               14.42
Jakob Vanhoefer            2196           61.1          4.0               11.52
Yannik Schälte               51           79.7          1.3               39.22
dilpath                       2           20.0          1.7              100.00
martamatos                  331           47.4          1.2               18.73
yannikschaelte                9           33.3         11.5                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3164 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@jvanhoefer - where is your paper?  I don't see a paper.md (and paper.bib) in the repo, or in a branch.

**Comment by jvanhoefer** [comment]
Oh, I apologize, it is in this repository 

https://github.com/yaml2sbml-dev/paper

(I gave the link to the toolbox and not to the paper...)

**Comment by jvanhoefer** [comment]
Regarding possible reviewers: There has been previously an article on a python based software on SBML at this journal. This paper was reviewed by marouenbg and SirSharpest.

Further from your list, I could imagine, that e.g. artgoldberg and dawbarton are a good fit.

**Comment by danielskatz** [comment]
For JOSS, we need the paper and the software to be in the same repository, though if you need, the paper can be in a branch that doesn't gets merged. For most submissions, it's just in a paper or joss directory in the software repo.

**Comment by jvanhoefer** [comment]
Thank you for the info, that wasn't clear to me. The paper is now in

https://github.com/yaml2sbml-dev/yaml2sbml/tree/JOSS_review/doc/JOSS_paper

(i.e. in folder `doc/JOSS_paper` of the `JOSS_review` branch.)

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch JOSS_review

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS_review. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03164/joss.03164/10.21105.joss.03164.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03164/joss.03164/10.21105.joss.03164.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hey @openjournals/dev, do we need to do something to point at the correct repository? It should be https://github.com/yaml2sbml-dev/yaml2sbml

**Comment by arfon** [comment]
@whedon invite @kellyrowland as editor

:wave: @kellyrowland - would you be willing to edit this submission for us?

**Comment by whedon** [comment]
@kellyrowland has been invited to edit this submission.

**Comment by kellyrowland** [comment]
Hi @arfon , I'll take this on.

**Comment by kellyrowland** [comment]
@whedon assign @kellyrowland as editor

**Comment by whedon** [comment]
OK, the editor is @kellyrowland

**Comment by kellyrowland** [comment]
Hello @marouenbg and @SirSharpest - would you be willing and available to review this submission for JOSS?

**Comment by SirSharpest** [comment]
Hi @kellyrowland, I'd be happy to review.

**Comment by kellyrowland** [comment]
Great, thanks very much!

**Comment by kellyrowland** [comment]
@whedon add @SirSharpest as reviewer

**Comment by whedon** [comment]
OK, @SirSharpest is now a reviewer

**Comment by marouenbg** [comment]
Hi @kellyrowland , yes count me in! Hi @SirSharpest great to see you again !

**Comment by kellyrowland** [comment]
Great, thanks!

**Comment by kellyrowland** [comment]
@whedon add @marouenbg as reviewer

**Comment by whedon** [comment]
OK, @marouenbg is now a reviewer

**Comment by kellyrowland** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3215.
