### ISSUE TITLE
[PRE REVIEW]: popsynth: A generic astrophysical population synthesis framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3165]
**Submitting author:** @grburgess (<a href="http://orcid.org/0000-0003-3345-9515">J. Michael Burgess</a>)
**Repository:** <a href="https://github.com/grburgess/popsynth" target ="_blank">https://github.com/grburgess/popsynth</a>
**Version:** v1.0.1
**Editor:** @xuanxu
**Reviewers:** @HeloiseS, @warrickball
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @grburgess. **Currently, there isn't an JOSS editor assigned** to your paper.

@grburgess if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.32 s (364.8 files/s, 75150.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          55           2825           2191           5225
CSS                             36             31             77           2590
Markdown                         8            448              0            910
YAML                             7             34             23            209
Jupyter Notebook                 1              0           9347            107
TeX                              1              5              0             52
reStructuredText                 6             40             83             28
JavaScript                       1              1              8             26
HTML                             2              0             25             20
Lisp                             1              1              2              2
-------------------------------------------------------------------------------
SUM:                           118           3385          11756           9169
-------------------------------------------------------------------------------


Statistical information for the repository '4adc8e63d1fb1564eb90e78e' was
gathered on 2021/04/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Francesca Capel                  8           395            212            2.21
J. Michael Burgess             198          8182           3644           43.02
grburgess                      226         10324           4730           54.77

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Francesca Capel             285           72.2          1.2                6.67
J. Michael Burgess          452            5.5          2.6                0.00
grburgess                  9539           92.4         12.6               11.16
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/physrevd.100.103523 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03165/joss.03165/10.21105.joss.03165.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03165/joss.03165/10.21105.joss.03165.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @xuanxu - are you able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @xuanxu as editor

**Comment by whedon** [comment]
@xuanxu has been invited to edit this submission.

**Comment by xuanxu** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
👋 @warrickball would you be willing to review this paper? I think your expertise on stellar astrophysics makes you a good fit for this submission.

**Comment by xuanxu** [comment]
:wave: @aureliocarnero: would you be willing to review this paper? I think your knowledge of Astrophysics and Python makes  you a great fit for this submission.

**Comment by warrickball** [comment]
Hi @xuanxu ! I've just had a look at the paper and a cursory look at the repo and it isn't obviously my area of expertise. While the package can be used to synthesize populations of stars, the framework is quite generic, so the code doesn't appear to involve any stellar astrophysics.

I'm not sure who the other potential reviewers are but I'd recommend someone who is better versed in the statistics of astronomical surveys.

If you have trouble finding another reviewer, do ask again, but I disclaim that I'll be approaching with limited knowledge of the science case at hand.

**Comment by xuanxu** [comment]
Understood, thanks @warrickball

**Comment by aureliocarnero** [comment]
Dear @xuanxu unfortunately I need to decline the invitation, it is not the right moment for me, Im very busy. Apologies, and hope I can be more useful next time.
Cheers
Aurelio

**Comment by grburgess** [comment]
perhaps Fipanther could be a good choice? @xuanxu

**Comment by xuanxu** [comment]
@grburgess indeed, thanks. BTW, I'm sorry for the delay starting the review, the potential reviewers I've contacted by email have also declined due by work load. Let's keep trying.

**Comment by xuanxu** [comment]
:wave: @Fipanther would you be willing to review this paper? The author has identified you as a good fit for this submission.

**Comment by grburgess** [comment]
@xuanxu all is good.

**Comment by xuanxu** [comment]
:wave: @ceb8 would you be willing to review this paper? I think your expertise on stellar astrophysics makes you a great fit for this submission.

**Comment by grburgess** [comment]
@xuanxu They have not signed up for JOSS reviews, but farr and ilyamandel both have vast expertise in generic populations.

**Comment by ilyamandel** [comment]
Alas, I can't help. :(
I just started as an editor at ApJ earlier this year, so I am fairly busy with that at the moment.    
I can recommend Jeff Andrews or Heloise Stevance.

**Comment by xuanxu** [comment]
@ilyamandel Thanks, I've queried both of them via email 🤞

**Comment by xuanxu** [comment]
@whedon assign @HeloiseS as reviewer

**Comment by whedon** [comment]
OK, @HeloiseS is now a reviewer

**Comment by xuanxu** [comment]
@whedon add @warrickball as reviewer

**Comment by whedon** [comment]
OK, @warrickball is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3257.
