### ISSUE TITLE
[PRE REVIEW]: mcMST: A Toolbox for the Multi-Criteria Minimum Spanning Tree Problem

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#317]
**Submitting author:** @jakobbossek (<a href="http://orcid.org/0000-0002-4121-4668">Jakob Bossek</a>)
**Repository:** <a href="https://github.com/jakobbossek/mcMST" target ="_blank">https://github.com/jakobbossek/mcMST</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @gvegayon

**Author instructions**

Thanks for submitting your paper to JOSS @jakobbossek. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jakobbossek if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](http://joss.theoj.org/about#paper_structure) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by jakobbossek** [comment]
@arfon Thanks for having a first look at my submission!

> Could you confirm here that there is a research application for this software (and explain what that  
> application is)? The section 'what should my paper contain' has some guidance for the sort of
> content we're looking to be present in the paper.md.

The software is beneficial for researchers who work in the field of evolutionary multi-objecitve optimization of combinatorial (graph) problems and the multi-criteria spanning tree problem (mcMST) in particular. An example: Most recently we used the software to develop a new mutation operator for an evolutionary multi-objective algorithm for the mcMST based on insights gained from the empirical analysis of Pareto-optimal solutions of mcMST problems. This work was submitted to the multi-criteria decision making track of the [IEEE SSCI2017](http://www.ele.uri.edu/ieee-ssci2017/) and is currently under review.

**Comment by arfon** [comment]
OK thanks @jakobbossek. 

> An example: Most recently we used the software to develop a new mutation operator for an evolutionary multi-objective algorithm for the mcMST based on insights gained from the empirical analysis of Pareto-optimal solutions of mcMST problems. This work was submitted to the multi-criteria decision making track of the IEEE SSCI2017 and is currently under review.

If you haven't already, it might be worth adding something about this to the `paper.md`.

We just need to find an editor and reviewer for this submission now before we can proceed with the main review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@ArdiaD @lmarti @berndbischl @jakob-r @aklxao2 @luca-scr @gvegayon would you be interested in reviewing this submission for [JOSS](http://joss.theoj.org/)? If you choose to accept this invitation we'll open a review issue where the actual review will take place. [Review](http://joss.theoj.org/about#reviewer_guidelines) is often fast and focuses on the software, its claims, and the documentation. Thanks! :rocket:

**Comment by gvegayon** [comment]
Hi Kevin,

I'm in. Thanks for inviting me.

Best,

George G. Vega Yon (from mobile)
+1 626 381 8171
http://cana.usc.edu/vegayon

On Aug 21, 2017 07:46, "Kevin Mattheus Moerman" <notifications@github.com>
wrote:

@ArdiaD <https://github.com/ardiad> @lmarti <https://github.com/lmarti>
@berndbischl <https://github.com/berndbischl> @jakob-r
<https://github.com/jakob-r> @aklxao2 <https://github.com/aklxao2> @luca-scr
<https://github.com/luca-scr> @gvegayon <https://github.com/gvegayon> would
you be interested in reviewing this submission for JOSS
<http://joss.theoj.org/>? If you choose to accept this invitation we'll
open a review issue where the actual review will take place. Review
<http://joss.theoj.org/about#reviewer_guidelines> is often fast and focuses
on the software, its claims, and the documentation. Thanks! 🚀

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/317#issuecomment-323762213>,
or mute the thread

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @gvegayon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @gvegayon

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/374. Feel free to close this issue now!
