### ISSUE TITLE
[PRE REVIEW]: pypbomb: A Python package with tools for the design of detonation tubes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3176]
**Submitting author:** @cartemic (<a href="http://orcid.org/0000-0002-5559-936X">Mick Carter</a>)
**Repository:** <a href="https://github.com/cartemic/pypbomb/" target ="_blank">https://github.com/cartemic/pypbomb/</a>
**Version:** v1.1.0
**Editor:** @kyleniemeyer
**Reviewers:** @mefuller, @wenkailiang
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @cartemic. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kyleniemeyer.

@cartemic if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (195.0 files/s, 40443.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            664           1211           3345
Jupyter Notebook                 1              0            787            364
TeX                              1             24              0            197
YAML                             3             12             21             90
reStructuredText                11             60             68             70
Markdown                         3             23              0             59
DOS Batch                        1              8              1             26
make                             1              4              7              9
CSS                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            34            795           2095           4163
-------------------------------------------------------------------------------


Statistical information for the repository '6346d37a2cfc47858c2f98e8' was
gathered on 2021/04/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Carter                          35          3513           1531           11.38
Mick Carter                    140         21285          17979           88.62

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mick Carter                5220           24.5         11.5                7.95
```

**Comment by kyleniemeyer** [comment]
Hey @cartemic, nice to see this submission! I will go ahead and assign myself to edit this one.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03176/joss.03176/10.21105.joss.03176.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03176/joss.03176/10.21105.joss.03176.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1115/1.3089497 is OK
- 10.1016/j.pecs.2007.11.002 is OK
- 10.5281/zenodo.1174508 is OK
- 10.2514/1.43659 is OK
- 10.1017/S0022112007005046 is OK
- 10.1007/s00348-017-2420-0 is OK
- 10.2514/6.2015-1350 is OK
- 10.1016/j.combustflame.2010.04.011 is OK
- 10.1016/j.proci.2010.07.071 is OK
- 10.2514/6.2016-1198 is OK
- 10.1016/j.combustflame.2014.11.026 is OK

MISSING DOIs

- 10.1016/0141-6359(79)90149-1 may be a valid DOI for title: Machinery’s Handbook

INVALID DOIs

- None
```

**Comment by cartemic** [comment]
I'm excited to be submitting it! Thanks for taking the time to review this!

**Comment by arfon** [comment]
@cartemic – to help get this moving could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by cartemic** [comment]
@arfon I filtered the list down by python and combustion, which (aside from kyleniemeyer, who is already editing) leaves arghdos, and mefuller. Expanding the filter to include thermodynamics, it looks like bocklund, arosen93, yes, fwitte, and mwerwee may also be good fits. All of them show 0 active reviews at the moment. Please let me know if there is anything more I can do to help!

**Comment by kyleniemeyer** [comment]
Thanks @cartemic! I let this one lag, but I'll get some review requests out shortly.

**Comment by kyleniemeyer** [comment]
Hello @mefuller @arosen93, would you be willing to review this submission for JOSS?

**Comment by arosen93** [comment]
@kyleniemeyer This one looks a bit outside my expertise, so I'll have to pass. I'm better suited for quantum chemistry and computational materials science.

**Comment by mefuller** [comment]
@kyleniemeyer this should be in my wheelhouse, so I'll agree to review it.

**Comment by kyleniemeyer** [comment]
Thanks @mefuller, and understood @arosen93.

**Comment by kyleniemeyer** [comment]
@whedon add @mefuller as reviewer

I still need to find a second reviewer, after which I'll start the actual review issue.

**Comment by whedon** [comment]
OK, @mefuller is now a reviewer

**Comment by kyleniemeyer** [comment]
Hi @fwitte, could you review this submission for JOSS?

**Comment by fwitte** [comment]
Hi @kyleniemeyer,
I'll need to pass as this is unfortunately not my expertise.
Best regards, have a nice day
Francesco

**Comment by mefuller** [comment]
@kyleniemeyer Is there anythign actionable as yet for me as a reviewer?

**Comment by kyleniemeyer** [comment]
@mefuller you can certainly begin looking at the software, based on our [reviewer guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html), but I need to identify a second reviewer before I start the actual review issue

**Comment by danielskatz** [comment]
@kyleniemeyer - what's going on with this submission?

**Comment by kyleniemeyer** [comment]
Ah, shoot, lost track of this. Sorry about that @cartemic and @mefuller. I still need to find a second reviewer.

**Comment by kyleniemeyer** [comment]
Hello @mwerwee, are you able to review this submission for JOSS? It focuses on the design and analysis of detonation tubes.

**Comment by cartemic** [comment]
Hi @kyleniemeyer, is there anything I should be doing to help keep the ball rolling on this? Thanks!

**Comment by kyleniemeyer** [comment]
@cartemic ah sorry about that, this fell off my radar screen after struggling to find a second reviewer. I will make one or two more requests, and if I can't find someone else, I'll do the second review myself.

**Comment by zadehsey** [comment]
@kyleniemeyer appreciate your invitation. As I find the manuscript outside the area of knowledgeability, I am afraid that I will not be able to provide constructive feedback on the work. Please consider me for future nanoscale transport related work.

**Comment by cartemic** [comment]
@kyleniemeyer no worries, I understand that you're very busy. Thanks for continuing the search, and for offering to review if needed!

**Comment by jiweiqi** [comment]
hi @kyleniemeyer , thanks for your invitation! Detonation is out of my expertise. I would recommend @wenkailiang.

**Comment by wenkailiang** [comment]
@kyleniemeyer @jiweiqi Sure. I can review this work. Thanks.

**Comment by kyleniemeyer** [comment]
@whedon add @wenkailiang as reviewer

**Comment by whedon** [comment]
OK, @wenkailiang is now a reviewer

**Comment by kyleniemeyer** [comment]
Thanks for the quick responses!

@wenkailiang @mefuller @cartemic I am going to start the review issue now, see you over there

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/4143.
