### ISSUE TITLE
[PRE REVIEW]: morse: an R-package in support of Environmental Risk Assessment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3177]
**Submitting author:** @sandrinecharles (<a href="http://orcid.org/0000-0003-4604-0166">Sandrine CHARLES</a>)
**Repository:** <a href="https://github.com/pveber/morse" target ="_blank">https://github.com/pveber/morse</a>
**Version:** 3.3.1
**Editor:** @KristinaRiemer
**Reviewers:** @BrandonEdwards, @puruckertom
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sandrinecharles. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@sandrinecharles if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (245.9 files/s, 36241.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Lua                              2             32             68            255
Markdown                         2             57              0            220
TeX                              1              9              0             96
-------------------------------------------------------------------------------
SUM:                             5             98             68            571
-------------------------------------------------------------------------------


Statistical information for the repository 'ba90c03f9d5b76567bf6507a' was
gathered on 2021/04/17.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03177/joss.03177/10.21105.joss.03177.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03177/joss.03177/10.21105.joss.03177.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s11356-017-9809-4 is OK
- 10.1021/acs.est.7b05464 is OK
- 10.2903/j.efsa.2018.5377 is OK
- 10.1002/ieam.4061 is OK

MISSING DOIs

- 10.1007/s10646-012-0917-0 may be a valid DOI for title: Toxicokinetic-toxicodynamic modelling of survival of Gammarus pulex in multiple pulse exposures to propiconazole: model assumptions, calibration data requirements and predictive power

INVALID DOIs

- http://dx.doi.org/10.1101/356469 is INVALID because of 'https://doi.org/' prefix
```

**Comment by kyleniemeyer** [comment]
Hi @sandrinecharles, thanks for your submission to JOSS. So, it looks like the repository you submitted points to one for the paper, rather than the software itself. The typical approach we expect is for the paper to be included in the software repository itself, and then we just have a single repo (for the submitted software package).

Can you move your paper to the repository for the software itself, and let us know when you have done that? Thanks!

**Comment by kyleniemeyer** [comment]
@whedon invite @KristinaRiemer as editor

Hi Kristina, this one looks right up your alley—I realize you already have a few other submissions at various stages right now, but wanted to see if you could take this on.

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by KristinaRiemer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @KristinaRiemer

**Comment by sandrinecharles** [comment]
> **Submitting author:** @sandrinecharles ([Sandrine CHARLES](http://orcid.org/0000-0003-4604-0166))
> **Repository:** https://github.com/sandrinecharles/morse_paper
> **Version:** 3.3.1
> **Editor:** @KristinaRiemer
> **Reviewer:** Pending
> **Managing EiC:** Kyle Niemeyer
> 
> **⚠️ JOSS reduced service mode ⚠️**
> 
> Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).
> 
> **Author instructions**
> 
> Thanks for submitting your paper to JOSS @sandrinecharles. **Currently, there isn't an JOSS editor assigned** to your paper.
> 
> The author's suggestion for the handling editor is @KristinaRiemer.
> 
> @sandrinecharles if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
> 
> **Editor instructions**
> 
> The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:
> 
> ```
> @whedon commands
> ```

Dear colleague,
As reviewers I may suggest the following ones:
Andre GERGS, andre.gergs@bayer.com
Alessio IPPOLITO, Alessio.IPPOLITO@efsa.europa.eu
Arnaud CHAUMOT, arnaud.chaumot@inrae.fr

Else, within your own list, those persons could maybe be interested in reviewing our manuscript:
@BrandonEdwards
@ghislainv
@Volkerschmid
@BrandonEdwards

Best regards,
Sandrine Charles

**Comment by sandrinecharles** [comment]
> ```
> Software report (experimental):
> 
> github.com/AlDanial/cloc v 1.88  T=0.02 s (245.9 files/s, 36241.3 lines/s)
> -------------------------------------------------------------------------------
> Language                     files          blank        comment           code
> -------------------------------------------------------------------------------
> Lua                              2             32             68            255
> Markdown                         2             57              0            220
> TeX                              1              9              0             96
> -------------------------------------------------------------------------------
> SUM:                             5             98             68            571
> -------------------------------------------------------------------------------
> 
> 
> Statistical information for the repository 'ba90c03f9d5b76567bf6507a' was
> gathered on 2021/04/17.
> No commited files with the specified extensions were found.
> ```

@whedons could you detail what is expected from my side as actions regarding this post?

**Comment by sandrinecharles** [comment]
> ```
> Reference check summary (note 'MISSING' DOIs are suggestions that need verification):
> 
> OK DOIs
> 
> - 10.1007/s11356-017-9809-4 is OK
> - 10.1021/acs.est.7b05464 is OK
> - 10.2903/j.efsa.2018.5377 is OK
> - 10.1002/ieam.4061 is OK
> 
> MISSING DOIs
> 
> - 10.1007/s10646-012-0917-0 may be a valid DOI for title: Toxicokinetic-toxicodynamic modelling of survival of Gammarus pulex in multiple pulse exposures to propiconazole: model assumptions, calibration data requirements and predictive power
> 
> INVALID DOIs
> 
> - http://dx.doi.org/10.1101/356469 is INVALID because of 'https://doi.org/' prefix
> ```

File paper.bib has been corrected. Thanks for your vigilance.

**Comment by sandrinecharles** [comment]
> Hi @sandrinecharles, thanks for your submission to JOSS. So, it looks like the repository you submitted points to one for the paper, rather than the software itself. The typical approach we expect is for the paper to be included in the software repository itself, and then we just have a single repo (for the submitted software package).
> 
> Can you move your paper to the repository for the software itself, and let us know when you have done that? Thanks!

Dear Kyle, I moved the 'paper' folder to the Github repository of the R-package directly as requested:
https://github.com/pveber/morse/tree/master/paper

**Comment by sandrinecharles** [comment]
> @whedon invite @KristinaRiemer as editor
> 
> Hi Kristina, this one looks right up your alley—I realize you already have a few other submissions at various stages right now, but wanted to see if you could take this on.

Dear Kristina, that would be much appreciated getting your feedback on our manuscript.

**Comment by sandrinecharles** [comment]
> Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.
> 
> **⚠️ JOSS reduced service mode ⚠️**
> 
> Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).
> 
> For a list of things I can do to help you, just type:
> 
> ```
> @whedon commands
> ```
> 
> For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:
> 
> ```
> @whedon generate pdf
> ```

@whedon generate pdf

**Comment by KristinaRiemer** [comment]
@sandrinecharles thanks for moving the paper into the code repo! You don't need to do anything with the software report, it's automatically generated to give us an idea of how many lines of code in which languages there are.

**Comment by KristinaRiemer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03177/joss.03177/10.21105.joss.03177.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03177/joss.03177/10.21105.joss.03177.pdf) :page_facing_up: :point_left:

**Comment by KristinaRiemer** [comment]
Thanks for the suggestion for reviewers @sandrinecharles, I'm reaching out via email to those whose GitHub handles I couldn't find. Otherwise, @BrandonEdwards @puruckertom would you be interested and able to review this JOSS submission?

**Comment by BrandonEdwards** [comment]
> Thanks for the suggestion for reviewers @sandrinecharles, I'm reaching out via email to those whose GitHub handles I couldn't find. Otherwise, @BrandonEdwards @puruckertom would you be interested and able to review this JOSS submission?

Certainly interested, and certainly able to!

**Comment by puruckertom** [comment]
Certainly!

**Comment by KristinaRiemer** [comment]
Great, thanks for the fast responses @BrandonEdwards and @puruckertom!

**Comment by KristinaRiemer** [comment]
@whedon assign @BrandonEdwards as reviewer

**Comment by whedon** [comment]
OK, @BrandonEdwards is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon add @puruckertom as reviewer

**Comment by whedon** [comment]
OK, @puruckertom is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3200.

**Comment by KristinaRiemer** [comment]
@BrandonEdwards and @puruckertom, the review itself will happen in the issue linked to above. Let me know if you have questions over there. And thanks again!

**Comment by sandrinecharles** [comment]
> > Thanks for the suggestion for reviewers @sandrinecharles, I'm reaching out via email to those whose GitHub handles I couldn't find. Otherwise, @BrandonEdwards @puruckertom would you be interested and able to review this JOSS submission?
> 
> Certainly interested, and certainly able to!

Thank you very much!

**Comment by sandrinecharles** [comment]
> Certainly!

Thank you very much!
