### ISSUE TITLE
[PRE REVIEW]: The Babelizer: language interoperability for model coupling in the geosciences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3179]
**Submitting author:** @mcflugen (<a href="http://orcid.org/0000-0002-5864-6459">ERIC HUTTON</a>)
**Repository:** <a href="https://github.com/csdms/babelizer/" target ="_blank">https://github.com/csdms/babelizer/</a>
**Version:** v1.0.0
**Editor:** @kthyng
**Reviewers:** @PythonCHB, @lheagy
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mcflugen. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@mcflugen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (699.5 files/s, 57815.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          22            389            209           1491
Cython                           3            230             22            820
reStructuredText                22            494            412            637
Fortran 90                       1            138            149            531
YAML                            16             71             20            406
TOML                             7             25              1            183
make                             4             53             13            165
C/C++ Header                     1             13              4             61
DOS Batch                        1              8              1             26
JSON                             1              0              0             26
HTML                             2              1              0             13
-------------------------------------------------------------------------------
SUM:                            80           1422            831           4359
-------------------------------------------------------------------------------


Statistical information for the repository 'bfdf6bc1944913ae651aadf3' was
gathered on 2021/04/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Eric Hutton                     14          2700           4145           62.67
Mark Piper                      18           362             30            3.59
mcflugen                        22          3483            203           33.75

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Eric Hutton                1742           64.5          6.7                6.43
Mark Piper                  283           78.2          5.2               20.49
mcflugen                    142            4.1         21.4                4.93
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3179 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
@whedon invite @kthyng as editor

Hey @kthyng, this looks up your alley—are you able to take another submission on as editor?

**Comment by whedon** [comment]
@kthyng has been invited to edit this submission.

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03179/joss.03179/10.21105.joss.03179.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03179/joss.03179/10.21105.joss.03179.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@mcflugen, @kyleniemeyer I'm not sure I have any relevant expertise for this. Geosciences, yes, but that looks like the application but not the guts of this project? @mcflugen who would you recommend to review this submission (from your network or [this list](https://bit.ly/joss-reviewers)? What type of skills are you looking for?

**Comment by mcflugen** [comment]
@kthyng We'll have a look at the list of potential reviewers and get back to you. In terms of skills, I think it would be good to find someone familiar with python (and cython) as well as at least one of the other languages we're working with (i.e. Fortran, C, C++).

**Comment by mcflugen** [comment]
@kthyng After going through your list, here are some that looked as if they could serve as reviewers. Some of these people we know, some we don't:
- camillescott
- cheginit
- dbuscombe-usgs
- lheagy
- ngoldbaum
- PythonCHB
- rowanc1

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @rowanc1 and @camillescott — would you be interested in reviewing this submission for JOSS? We're asking for people to start their reviews in the next few weeks in hopes the whole iterative process would be finished in 4-6 weeks. You can learn more about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Thanks for your consideration!

**Comment by kthyng** [comment]
@dbuscombe-usgs and @ngoldbaum: would you be interested in reviewing this submission for JOSS? We're asking for people to start their reviews in the next few weeks in hopes the whole iterative process would be finished in 4-6 weeks. You can learn more about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Thanks for your consideration!

**Comment by dbuscombe-usgs** [comment]
I'm sorry, I don't think I have the time this time - very busy month coming up. But would be happy to consider similar articles in the future

**Comment by kthyng** [comment]
Thanks for letting me know @dbuscombe-usgs! Totally understand.

**Comment by kthyng** [comment]
@PythonCHB Are you available to review this JOSS submission? We're asking for people to start their reviews in the next few weeks in hopes the whole iterative process would be finished in 4-6 weeks. As a reminder, you can learn more about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Thanks for your consideration!

**Comment by PythonCHB** [comment]
@kthyng: Yes, I should be able to do it.

-CHB

**Comment by kthyng** [comment]
Thanks @PythonCHB! I need to find a second reviewer and then we can move forward to the review step.

**Comment by kthyng** [comment]
@whedon assign @PythonCHB as reviewer

**Comment by whedon** [comment]
OK, @PythonCHB is now a reviewer

**Comment by kthyng** [comment]
@lheagy are you missing some JOSS from your life? If so, maybe you'd want to review this submission?

**Comment by lheagy** [comment]
Best reviewer invite @kthyng 😄 ! I would be happy to be a reviewer here.

**Comment by kthyng** [comment]
haha, excellent! Thanks @lheagy and glad to have you around a JOSS issue once again.

**Comment by kthyng** [comment]
@whedon add @lheagy as reviewer

**Comment by whedon** [comment]
OK, @lheagy is now a reviewer

**Comment by kthyng** [comment]
Ok we can get this review process started now!

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3344.
