### ISSUE TITLE
[PRE REVIEW]: Nimbus: a Ruby gem to implement Random Forest algorithms in a genomic selection context

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#318]
**Submitting author:** @xuanxu (<a href="http://orcid.org/0000-0001-7699-3983">Juanjo Bazán</a>)
**Repository:** <a href="https://github.com/xuanxu/nimbus" target ="_blank">https://github.com/xuanxu/nimbus</a>
**Version:** 2.3.0
**Editor:** @pjotrp
**Reviewer:** @fstrozzi

**Author instructions**

Thanks for submitting your paper to JOSS @xuanxu. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@xuanxu if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current JOSS editors:

```
@acabunoc
@arfon
@arokem
@biorelated
@brainstorm
@cMadan
@danielskatz
@jakevdp
@karthik
@katyhuff
@Kevin-Mattheus-Moerman
@kyleniemeyer
@labarba
@lheagy
@mgymrek
@pjotrp
@tracykteal
```

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by arfon** [comment]
@xuanxu - we're a little light on folks with Ruby experience and genomics. Do you have any suggestions for potential reviewers for this submission?

**Comment by xuanxu** [comment]
@arfon I think the review should be easy to someone with working knowledge of Ruby. The "genomics" part of the software refers to the values of the expected input data, but there's no need to be a genomics expert to test the software. After reading the lists of editors & reviewers I think you or @amoeba are good options. But if you prefer I can ask a colleague for help.

**Comment by arfon** [comment]
@pjotrp - do you know anyone who might be a good reviewer here?

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@fstrozzi would you like to review this interesting submission?

**Comment by fstrozzi** [comment]
Sure I'd be glad to. I'll need few days though, to have a bit of time to look at it.

**Comment by pjotrp** [comment]
No problem. Thanks @fstrozzi.

**Comment by pjotrp** [comment]
@whedon assign @fstrozzi as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @fstrozzi

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/351. Feel free to close this issue now!
