### ISSUE TITLE
[PRE REVIEW]: pyHMT2D: Python-based two-dimensional hydraulic modeling tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3180]
**Submitting author:** @psu-efd (<a href="http://orcid.org/0000-0002-8296-7076">Xiaofeng Liu</a>)
**Repository:** <a href="https://github.com/psu-efd/pyHMT2D" target ="_blank">https://github.com/psu-efd/pyHMT2D</a>
**Version:** v1.0.1
**Editor:** @kthyng
**Reviewers:** @jmp75, @mdbartos
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @psu-efd. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kbarnhart.

@psu-efd if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.38 s (235.6 files/s, 37675.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          53           3127           3375           4551
JSON                             9              0              0            861
SVG                              1              1              1            797
reStructuredText                16            260             95            524
TeX                              1             24              0            169
Bourne Shell                     1             32             10            141
Markdown                         4             61              0            135
YAML                             1              1              4             18
make                             1              4              8             10
HTML                             1              5              0              9
INI                              1              0              0              9
-------------------------------------------------------------------------------
SUM:                            89           3515           3493           7224
-------------------------------------------------------------------------------


Statistical information for the repository '0576abaa6a93461d154608b2' was
gathered on 2021/04/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
psuliuxf                        44         14218           2984          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
psuliuxf                  11234           79.0          0.7               17.04
```

**Comment by kyleniemeyer** [comment]
@whedon invite @kbarnhart as editor

Hi @kbarnhart, I know you have a few other submissions right now, but wanted to see if you could take this on. If you don't have availability right now, we can waitlist it.

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by kbarnhart** [comment]
@kyleniemeyer no availability now :( sorry. 

Also, sorry for the delay in response. I must have not enabled the ooo bot correctly (am back now)

**Comment by psu-efd** [comment]
Hi, 
Thanks for picking up this paper. I totally understand the unavailability of editors. Please choose another editor for this paper. 

For suggested reviewers, I had a look at the list and searched with keywords "hydrology", "hydraulics", and "earth system". The following is a list of potential reviewers:

cheginit, mdbartos, zgxn, JannisHoch, jmp75, AtrCheema, marda-science , dbuscombe-usgs

Thanks again.

**Comment by Kevin-Mattheus-Moerman** [comment]
@kbarnhart if you feel you are in principle a suitable editor would you mind if we waitlisted this for now and that we assign this to you once you are available?

**Comment by kbarnhart** [comment]
@Kevin-Mattheus-Moerman I would be a suitable editor, but it might be best if this could get on at least one other editor's queue. Given what I know the next few months will look like for me I'd like to drop down to handling two papers at a time (currently have three, one nearing the end --- I think --- and two part way along). So it might be a bit before I could get this off the waitlist.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see why the paper wont compile here?

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by psu-efd** [comment]
Thanks, @kthyng for picking up this paper. 

I saw there is a message about the paper not compiling. Please let me know if I can be of any help to resolve the issue.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by kthyng** [comment]
@openjournals/dev The paper here never seems to have any error nor any follow up from whedon, despite repeated calls to generate the pdf over time.

**Comment by kthyng** [comment]
@psu-efd Thanks for the reviewer ideas!

@jmp75 and @AtrCheema — would you be interested in reviewing this submission for the Journal for Open Source Software? We would ask you to start the review in the next few weeks to be finished in 4-6 weeks, anticipated some potential back and forth of iteration with the author.  It's all done through github — you can learn more about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by jmp75** [comment]
@kthyng  I am interested. This will be my first JOSS review but I'll try to do a suitable job.

**Comment by kthyng** [comment]
@jmp75 Excellent! I'll add you as a reviewer, but we'll wait to start the review until we have secured a second reviewer. Thanks.

**Comment by kthyng** [comment]
@whedon assign @jmp75 as reviewer

**Comment by whedon** [comment]
OK, @jmp75 is now a reviewer

**Comment by kthyng** [comment]
Hi @mdbartos! Would you be interested in reviewing this submission for the Journal for Open Source Software? We would ask you to start the review in the next few weeks to be finished in 4-6 weeks, anticipated some potential back and forth of iteration with the author. It's all done through github — you can learn more about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
> @openjournals/dev The paper here never seems to have any error nor any follow up from whedon, despite repeated calls to generate the pdf over time.

@kthyng – I'm not exactly sure what's going on here but compiling the paper is blowing up the memory usage of Whedon and the process is being killed.

Historically this has been due to large figures but the PNGs here don't look too big. I'll need to dig into this further.

For now though, here's the paper compiled locally: [10.21105.joss.03180.pdf](https://github.com/openjournals/joss-reviews/files/6577596/10.21105.joss.03180.pdf)

**Comment by mdbartos** [comment]
> Hi @mdbartos! Would you be interested in reviewing this submission for the Journal for Open Source Software? We would ask you to start the review in the next few weeks to be finished in 4-6 weeks, anticipated some potential back and forth of iteration with the author. It's all done through github — you can learn more about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Sure, happy to help. I've had a paper reviewed before in JOSS and I'm a big fan of the process.

**Comment by kthyng** [comment]
@mdbartos Excellent! I'll add you and we can start the process.

**Comment by kthyng** [comment]
@whedon add @mdbartos as reviewer

**Comment by whedon** [comment]
OK, @mdbartos is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3332.
