### ISSUE TITLE
[PRE REVIEW]: autumn: A Python library for dynamic modelling of captured CO~2~ cost potential curves

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3182]
**Submitting author:** @Eugenio2192 (<a href="http://orcid.org/0000-0003-2508-3976">Eugenio Salvador Arellano Ruiz</a>)
**Repository:** <a href="https://gitlab.com/dlr-ve/autumn/" target ="_blank">https://gitlab.com/dlr-ve/autumn/</a>
**Version:** 0.1.0
**Editor:** @timtroendle
**Reviewers:** @potterzot, @igarizio
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Eugenio2192. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @timtroendle.

@Eugenio2192 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.19 s (321.8 files/s, 43469.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          21            794           1502           2859
YAML                             7             22              9           1015
JSON                            10             10              0            359
reStructuredText                14            161            147            215
Markdown                         2             57              0            170
Jupyter Notebook                 2              0            569            150
TeX                              1             11              0            109
DOS Batch                        1              8              1             26
HTML                             1              1              0             24
make                             1              4              7              9
XML                              1              0              0              1
-------------------------------------------------------------------------------
SUM:                            61           1068           2235           4937
-------------------------------------------------------------------------------


Statistical information for the repository '757bebed405de121aa733b4c' was
gathered on 2021/04/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Arellano Ruiz                    1             1              1            0.02
Arellano Ruiz, Eugen            22          4152           2818           62.52
Eugenio                          1          3497              0           31.37
Eugenio Arellano                11           340            187            4.73
Eugenio Salvador Are             4            62             37            0.89
ve-py@dlr.de                     2            41             13            0.48

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Arellano Ruiz                 1          100.0          0.3                0.00
Arellano Ruiz, Eugen       3736           90.0          1.3                7.90
DLR                          40          100.0          0.2                5.00
Eugenio Arellano              3            0.9          0.7                0.00
Eugenio2192                1375          100.0          0.1                6.40
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1039/C7EE02342A is OK
- 10.1007/s11356-016-6810-2 is OK
- 10.1016/j.esr.2018.11.004 is OK
- 10.1038/s41467-020-20015-4 is OK
- 10.1016/j.energy.2018.10.114 is OK
- 10.1016/j.energy.2018.06.222 is OK
- 10.18419/opus-2015 is OK
- 10.1016/j.epsr.2020.106690 is OK
- 10.1021/acs.est.5b03474 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon invite @timtroendle as editor

Hi @timtroendle, can you take this submission on?

**Comment by whedon** [comment]
@timtroendle has been invited to edit this submission.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03182/joss.03182/10.21105.joss.03182.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03182/joss.03182/10.21105.joss.03182.pdf) :page_facing_up: :point_left:

**Comment by timtroendle** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @timtroendle

**Comment by timtroendle** [comment]
Hello @Eugenio2192, I will start looking for reviewers for your submission. If you have any suggestions, please let me know.

**Comment by timtroendle** [comment]
:wave: @igarizio, @potterzot & @milicag, would any of you be willing to review this submission for JOSS?

**Comment by Eugenio2192** [comment]
> 
> 
> Hello @Eugenio2192, I will start looking for reviewers for your submission. If you have any suggestions, please let me know.
Hello @timtroendle  I am looking foward to this review process let me know if  you need anything from me I extend this to the potential reviewers. 
I currently don't have any suggestion but I let you know if someone shows up.

**Comment by potterzot** [comment]
@timtroendle thank you for the request to review. I'd be happy to do so but the earliest I would be able to respond would be the first week of May.

**Comment by timtroendle** [comment]
@potterzot thank you for your reply. We are currently still working in a "reduced service mode" in which we ask reviewers to respond within 6 week at the latest. So a response of you in the beginning of May would be fine.

**Comment by igarizio** [comment]
👋 @timtroendle thank you for suggesting me for the review. I would be more than happy to participate (if you are looking for more than one reviewer).

**Comment by timtroendle** [comment]
Absolutely, thank you for letting me know @igarizio .

**Comment by milicag** [comment]
I am glad the other reviewers already volunteered and happy to skip due to other reviewer commitments I am involved with right now. This looks like a great topic and I wish you a great reviewing session.

**Comment by timtroendle** [comment]
That's fine, @milicag. Thank you for letting us know. 

@Eugenio2192, @potterzot, @igarizio, with two reviewers assigned we can start the review process right away. Thanks all for your quick replies.

**Comment by timtroendle** [comment]
@whedon assign @potterzot as reviewer

**Comment by whedon** [comment]
OK, @potterzot is now a reviewer

**Comment by timtroendle** [comment]
@whedon add @igarizio as reviewer

**Comment by whedon** [comment]
OK, @igarizio is now a reviewer

**Comment by timtroendle** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3203.
