### ISSUE TITLE
[PRE REVIEW]: Circular profile of a ring over a stack of images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3183]
**Submitting author:** @jeanbilheux (<a href="http://orcid.org/0000-0003-2172-6487">Jean Bilheux</a>)
**Repository:** <a href="https://github.com/neutronimaging/circular_profiler" target ="_blank">https://github.com/neutronimaging/circular_profiler</a>
**Version:** v1.0.0
**Editor:** @jgostick
**Reviewers:** @prasantapal, @michaelberks
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jeanbilheux. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jni.

@jeanbilheux if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (197.9 files/s, 37136.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          16            510            181           1851
Qt                               1              0              0           1433
Markdown                         3             37              0            126
YAML                             2              7              1            112
CSS                              1             21             10             96
TeX                              1              4              0             45
Bourne Shell                     1              5              5             24
Jupyter Notebook                 1              0            397             13
-------------------------------------------------------------------------------
SUM:                            26            584            594           3700
-------------------------------------------------------------------------------


Statistical information for the repository 'ee5821c1e27752752caf8114' was
gathered on 2021/04/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
JeanBilheux                      4          2544              2          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jean Bilheux               2542          100.0          0.0                5.35
```

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/MCSE.2011.37 is OK
- 10.21105/joss.00815 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- 10.25080/majora-92bf1922-00a may be a valid DOI for title:  Data Structures for Statistical Computing in Python 

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03183/joss.03183/10.21105.joss.03183.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03183/joss.03183/10.21105.joss.03183.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @JeanBilheux, thanks for your interest in JOSS. The editors will now discuss if it meets the [research software criterion](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) for review by JOSS. You should hear back in a week or so.

**Comment by kthyng** [comment]
Hi @JeanBilheux! The editorial board has decided that this submission is in scope for us, though the argument for this being research software should be improved in your paper, as part of the review process. So, I have removed the "query-scope" label. Unfortunately, we have a backlog of submissions currently in this area with overburdened editors so I will add you to the backlog with the "waitlist" label. Thanks for your patience.

**Comment by JeanBilheux** [comment]
Thanks @kthyng , I will improve the paper.md document and explain in more detail why this library is so important for the type of research we do.

**Comment by danielskatz** [comment]
@JeanBilheux  - have you updated the paper?  When you have done so, please use the command `@whedon generate pdf` to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by bidochon** [comment]
So sorry Daniel. I was waiting on some feedback on your side and thanks to you, I just realized the ball was in my side. I'm gonna work on this first thing today. thanks

**Comment by JeanBilheux** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03183/joss.03183/10.21105.joss.03183.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03183/joss.03183/10.21105.joss.03183.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @jgostick - Would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @jgostick as editor

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by jgostick** [comment]
@whedon add @prasantapal as reviewer

**Comment by whedon** [comment]
OK, @prasantapal is now a reviewer

**Comment by jgostick** [comment]
@prasantapal, I need to find a second reviewer then I'll start the official review process, at which point further instructions will follow.

**Comment by prasantapal** [comment]
Will wait for that. Thanks!

**Comment by jgostick** [comment]
@whedon add @michaelberks as reviewer

**Comment by whedon** [comment]
OK, @michaelberks is now a reviewer

**Comment by jgostick** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3426.
