### ISSUE TITLE
[PRE REVIEW]: PERFORM: A Python package for developing reduced-order models for reacting fluid flows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3184]
**Submitting author:** @cwentland0 (<a href="http://orcid.org/0000-0002-8500-569X">Christopher Wentland</a>)
**Repository:** <a href="https://github.com/cwentland0/perform" target ="_blank">https://github.com/cwentland0/perform</a>
**Version:** v0.1
**Editor:** @kyleniemeyer
**Reviewers:** @clemaitre58, @Himscipy
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @cwentland0. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jedbrown.

@cwentland0 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.44 s (183.2 files/s, 18877.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          49           1383           1168           3808
reStructuredText                23            529            696            571
Markdown                         5             43              0             55
Bourne Shell                     2             14              8             46
make                             1              4              6             10
TeX                              1              0              0              7
-------------------------------------------------------------------------------
SUM:                            81           1973           1878           4497
-------------------------------------------------------------------------------


Statistical information for the repository 'fb8371d87a8713aa26198609' was
gathered on 2021/04/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ashish S Nair                   14          2181            996            7.30
chris                          130         22631          17703           92.70

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
chris                      6359           28.1          1.4               14.29
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3184 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hi @cwentland0, thanks for your interest in JOSS! This actually looks up my alley, so I'm going to serve as editor. We'll use this pre-review issue to find and assign reviewers, which I'll be doing in the coming week.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03184/joss.03184/10.21105.joss.03184.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03184/joss.03184/10.21105.joss.03184.pdf) :page_facing_up: :point_left:

**Comment by cwentland0** [comment]
@kyleniemeyer Sounds great! Thanks for taking this up, I appreciate it.

**Comment by arfon** [comment]
@cwentland0 – could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by cwentland0** [comment]
Hi @arfon, here are a few names:
clemaitre58
szkafander
tupi
Himscipy
highlando
bonh

These reviewers indicated Python as a preferred programming language, and made some reference to computational fluid dynamics and machine learning/data-driven methods in their preferred domains/topics. If figure that combo might fit best.

**Comment by kyleniemeyer** [comment]
Thanks @cwentland0! Sorry for letting this one lag. I'll be sending out some review requests shortly.

**Comment by kyleniemeyer** [comment]
Hi @clemaitre58 and @tupi, would you be willing to review this submission for JOSS?

**Comment by clemaitre58** [comment]
ok

**Comment by kyleniemeyer** [comment]
@whedon add @clemaitre58 as reviewer

Thanks @clemaitre58! Once we find a second reviewer, I will initiate the actual review issue. In the meantime, you can see our reviewer guidelines here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by whedon** [comment]
OK, @clemaitre58 is now a reviewer

**Comment by kyleniemeyer** [comment]
Hello @Himscipy, would you be willing to review this submission for JOSS? If you haven't reviewed for us before, we follow a checklist-based approach in the open here on GitHub: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by Himscipy** [comment]
Hi @kyleniemeyer, 
Thanks for the review invite.
The work fit well with my background and I can surely review it.

**Comment by kyleniemeyer** [comment]
@whedon add @Himscipy as reviewer

Great, thank you!

**Comment by whedon** [comment]
OK, @Himscipy is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3428.
