### ISSUE TITLE
[PRE REVIEW]: plutus: An R package to calculate electricity investments and stranded assets from the Global Change Analysis Model (GCAM)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3185]
**Submitting author:** @mengqi-z (<a href="http://orcid.org/0000-0001-5385-2758">Mengqi Zhao</a>)
**Repository:** <a href="https://github.com/JGCRI/plutus.git" target ="_blank">https://github.com/JGCRI/plutus.git</a>
**Version:** v0.1.0
**Editor:** @kellyrowland
**Reviewers:** @kramea, @neerajdhanraj
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @mengqi-z. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@mengqi-z if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.31 s (193.9 files/s, 51148.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              8              0           5379
HTML                            32           1616            456           4971
R                                9            245            382           1334
CSS                              3             99             48            428
JavaScript                       4             65             35            267
YAML                             6             25              0            156
Rmd                              2            118            231            107
Markdown                         2             34              0             76
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            61           2210           1153          12729
-------------------------------------------------------------------------------


Statistical information for the repository '4b126f4bcc483594d45fd284' was
gathered on 2021/04/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
mengqi-z                         3           427             45          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
mengqi-z                    382           89.5          0.0                9.95
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3185 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
Hello @mengqi-z, thanks for your interest in JOSS. Can you specify which branch has the JOSS paper? I see both `joss-paper-branch_plp` and `joss-paper-branch`.

**Comment by kyleniemeyer** [comment]
@whedon invite @kellyrowland as editor

Hi Kelly! I realize this submission is a bit outside your wheelhouse, but could you edit this? The author has provided some suggested reviewers already: `tscheypidi` and `jhollist`

**Comment by whedon** [comment]
@kellyrowland has been invited to edit this submission.

**Comment by mengqi-z** [comment]
> Hello @mengqi-z, thanks for your interest in JOSS. Can you specify which branch has the JOSS paper? I see both `joss-paper-branch_plp` and `joss-paper-branch`.

Hi @kyleniemeyer, the latest paper is located in `joss-paper-branch`. Thanks!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03185/joss.03185/10.21105.joss.03185.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03185/joss.03185/10.21105.joss.03185.pdf) :page_facing_up: :point_left:

**Comment by kellyrowland** [comment]
Hi @kyleniemeyer , happy to take this on.

**Comment by kellyrowland** [comment]
@whedon assign @kellyrowland as editor

**Comment by whedon** [comment]
OK, the editor is @kellyrowland

**Comment by kellyrowland** [comment]
Hello @tscheypidi and @jhollist - would you be willing and available to review this submission for JOSS?

**Comment by jhollist** [comment]
Thanks for the invite.  Unfortunately, I am going to have to pass right now.  Schedule is busy and getting busier!  Sorry!

**Comment by kellyrowland** [comment]
@jhollist Understood, thanks for the quick reply!

**Comment by tscheypidi** [comment]
I also have to decline this time due to other commitments. Sorry for that.

**Comment by kellyrowland** [comment]
@tscheypidi No problem, thanks for your reply!

**Comment by kellyrowland** [comment]
Hello @neerajdhanraj @jordanperr @kramea -

Would any of you be interested in and able to take on reviewing this JOSS submission?

**Comment by kramea** [comment]
Sure, I would be interested to review this.

**Comment by neerajdhanraj** [comment]
Dear Kelly,

I would like to review this article.

Best regards,
Neeraj

**Comment by kellyrowland** [comment]
Thank you both!

**Comment by kellyrowland** [comment]
@whedon add @kramea as reviewer

**Comment by whedon** [comment]
OK, @kramea is now a reviewer

**Comment by kellyrowland** [comment]
@whedon add @neerajdhanraj as reviewer

**Comment by whedon** [comment]
OK, @neerajdhanraj is now a reviewer

**Comment by kellyrowland** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3212.
