### ISSUE TITLE
[PRE REVIEW]: diyepw: A Python package for Do-It-Yourself EnergyPlus 1 weather file generation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3187]
**Submitting author:** @amandadsmith (<a href="http://orcid.org/0000-0003-2990-2190">Amanda D. Smith</a>)
**Repository:** <a href="https://github.com/IMMM-SFA/diyepw/" target ="_blank">https://github.com/IMMM-SFA/diyepw/</a>
**Version:** 1.0.4
**Editor:** @timtroendle
**Reviewers:** @samuelduchesne, @ritwikagarwal
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @amandadsmith. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@amandadsmith if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3187 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (501.3 files/s, 38492.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          20            314            594           1114
reStructuredText                 3             65             45            122
Markdown                         6             23              0            119
DOS Batch                        1              8              1             26
make                             1              4              7              9
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            32            414            647           1396
-------------------------------------------------------------------------------


Statistical information for the repository 'b05ed781d84db01e89e4c2b8' was
gathered on 2021/04/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Amanda Smith                     7           738              8            2.06
Benjamin Stürmer               157          4175           3004           19.85
travis                           8         14157          14091           78.09

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Benjamin Stürmer           1944           46.6          3.7               15.33
travis                       78            0.6          1.1               34.62
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03187/joss.03187/10.21105.joss.03187.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03187/joss.03187/10.21105.joss.03187.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @amandadsmith, thanks for your interest in JOSS. Unfortunately, we have a bit of a backlog, and due to a lack of suitable and available editors, I'm going to put this on our waitlist for now. We will assign this to an editor as soon as one becomes available.

**Comment by amandadsmith** [comment]
Thank you for the status update @kyleniemeyer

**Comment by timtroendle** [comment]
@openjournals/joss-eics I could take on this submission as editor.

**Comment by danielskatz** [comment]
@whedon assign @timtroendle as editor

**Comment by whedon** [comment]
OK, the editor is @timtroendle

**Comment by timtroendle** [comment]
:wave: @samuelduchesne & @ralphevins, would any of you be willing to review this submission for JOSS?

**Comment by samuelduchesne** [comment]
Hi @timtroendle, I would be happy to review this!

**Comment by amandadsmith** [comment]
Hi @timtroendle, thanks! The following JOSS reviewers also look like they may fit the bill: sarats, jtmiclat, ritwikagarwal, willu47

**Comment by timtroendle** [comment]
👋 @sarats & @jtmiclat, would any of you be willing to review this submission for JOSS?

**Comment by timtroendle** [comment]
👋 @ritwikagarwal & @willu47, would any of you be willing to review this submission for JOSS?

**Comment by ritwikagarwal** [comment]
Would be happy to pick up!
Thanks

**Comment by timtroendle** [comment]
That's great, @ritwikagarwal. Thanks for letting us know. We can now start the review with the two of you, @ritwikagarwal and @samuelduchesne .

**Comment by timtroendle** [comment]
@whedon add @samuelduchesne as reviewer

**Comment by whedon** [comment]
OK, @samuelduchesne is now a reviewer

**Comment by timtroendle** [comment]
@whedon add @ritwikagarwal as reviewer

**Comment by timtroendle** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3313.
