### ISSUE TITLE
[PRE REVIEW]: The stantargets R package: a workflow framework for efficient reproducible Stan-powered Bayesian data analysis pipelines

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3188]
**Submitting author:** @wlandau (<a href="http://orcid.org/0000-0003-1878-3253">William Landau</a>)
**Repository:** <a href="https://github.com/ropensci/stantargets" target ="_blank">https://github.com/ropensci/stantargets</a>
**Version:** 0.0.0.9003
**Editor:** @kyleniemeyer
**Reviewers:** @kyleniemeyer
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @wlandau. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @fboehm.

@wlandau if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (648.0 files/s, 106375.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               54             90           1434           8226
SVG                              2              0              0            810
Rmd                              3            126            210            520
Markdown                        10             91              0            352
JSON                             1              0              0            307
YAML                             5             41             64            255
TeX                              2             11              0            104
-------------------------------------------------------------------------------
SUM:                            77            359           1708          10574
-------------------------------------------------------------------------------


Statistical information for the repository '51d291204645089537680253' was
gathered on 2021/04/17.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.02959 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03188/joss.03188/10.21105.joss.03188.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03188/joss.03188/10.21105.joss.03188.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @wlandau, since this submission was already reviewed and accepted by rOpenSci, the review at JOSS will be fast-tracked.

rOpenSci review issue: https://github.com/ropensci/software-review/issues/430

**Comment by kyleniemeyer** [comment]
@wlandau however, it does look like your paper is missing the required statement of need section, one of the [required elements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) of JOSS papers. Can you add this, then we will proceed?

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by wlandau** [comment]
Thanks @kyleniemeyer, https://github.com/ropensci/stantargets/commit/bd5e306d05c60274b45eb584e83ef76ea3158716 adds a statement of need section.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as reviewer

**Comment by whedon** [comment]
OK, @kyleniemeyer is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review
