### ISSUE TITLE
[PRE REVIEW]: JPP : Java-Parallel-Pipeline

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3189]
**Submitting author:** @rsegretain (<a href="http://orcid.org/0000-0003-3044-9792">Rémi Segretain</a>)
**Repository:** <a href="https://gitlab.com/rsegretain/jpp" target ="_blank">https://gitlab.com/rsegretain/jpp</a>
**Version:** V1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @rsegretain. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @gkthiruvathukal.

@rsegretain if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (248.7 files/s, 38954.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              3            135           1647
Java                            10            182            684            529
Markdown                         7            126              0            287
YAML                             2              2              2             50
TeX                              1              1              0             28
HTML                             1              2              0              8
Ant                              1             13             55              5
-------------------------------------------------------------------------------
SUM:                            24            329            876           2554
-------------------------------------------------------------------------------


Statistical information for the repository '8b75c31c2aea194c99d91bce' was
gathered on 2021/04/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Rémi                            54          2420           1024           99.91
Rémi Segretain                   1             1              2            0.09

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Rémi                       1395           57.6          1.2               51.90
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2020.10.02.323949 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hi @rsegretain, thanks for your interest in JOSS. Because of the relatively small size of the codebase, the JOSS editorial board is going to review your submission to see if it meets our requirement for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). You should hear back within a week or so.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03189/joss.03189/10.21105.joss.03189.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03189/joss.03189/10.21105.joss.03189.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it fails to meet our threshold for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
