### ISSUE TITLE
[PRE REVIEW]: geneXplainR: An R interface for the geneXplain platform

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#319]
**Submitting author:** @pstegma (<a href="http://orcid.org/0000-0002-1881-8746">Philip Stegmaier</a>)
**Repository:** <a href="https://github.com/genexplain/geneXplainR" target ="_blank">https://github.com/genexplain/geneXplainR</a>
**Version:** 0.4
**Editor:** @mgymrek
**Reviewer:** @selbouhaddani 

**Author instructions**

Thanks for submitting your paper to JOSS @pstegma. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@pstegma if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @mgymrek it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @mgymrek - the submitting author suggested you as a potential editor.

**Comment by mgymrek** [comment]
@pstegma thanks for the submission. I have taken a look at the paper.md. Could you clarify what types of analyses can be done with this platform? The paper currently mentions "a broad range of bioinformatic and systems biology applications" and "upstream anslysis", but it is not clear exactly what types of analyses are being targeted. e.g. analysis of sequencing data? gene ontology analysis? Some examples in the paper will be helpful to readers to determine whether the tool is relevant to them, and will also help me find an appropriate reviewer.

**Comment by pstegma** [comment]
Dear @mgymrek ,
thank you for taking a look at our paper and for your suggestions. I have added information about covered methods. As we are part of a few consortia, can I be of any help to find a reviewer?

**Comment by gymreklab** [comment]
Hi @pstegma sorry for the delay in response. It would be great if you could suggest a couple potential reviewers.

**Comment by mgymrek** [comment]
@konrad @cmungall @mcourtot @slowkow would any of you be willing to review this submission?

**Comment by pstegma** [comment]
Dear @gymreklab ,
I may suggest Ivo Ugrina (https://github.com/iugrina) and Said el Bouhaddani (https://github.com/selbouhaddani) as potential reviewers.

**Comment by gymreklab** [comment]
@iugrina @selbouhaddani - I believe you have the background to review this submission by @pstegma (https://github.com/genexplain/geneXplainR). Are you interested in reviewing this submission for JOSS? For more background on the review process, see: http://joss.theoj.org/about#reviewer_guidelines

**Comment by selbouhaddani** [comment]
@gymreklab Yes, I would be willing to review this submission

**Comment by slowkow** [comment]
@gymreklab Yes, I would be willing to review. Could I please ask for instructions?

**Comment by mgymrek** [comment]
@whedon assign @selbouhaddani  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @selbouhaddani

**Comment by mgymrek** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/412. Feel free to close this issue now!

**Comment by mgymrek** [comment]
Thanks @selbouhaddani for agreeing to review. The review issue has been started, feel free to ask any questions about the review process there.

**Comment by mgymrek** [comment]
@slowkow thanks, it looks like we're actually set for now. I'll keep you in mind for future submissions!
