### ISSUE TITLE
[PRE REVIEW]: MCALF: Multi-Component Atmospheric Line Fitting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3195]
**Submitting author:** @ConorMacBride (<a href="http://orcid.org/0000-0002-9901-8723">Conor MacBride</a>)
**Repository:** <a href="https://github.com/ConorMacBride/mcalf" target ="_blank">https://github.com/ConorMacBride/mcalf</a>
**Version:** v0.2.0
**Editor:** @mbobra
**Reviewers:** @mgalloy, @Goobley
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ConorMacBride. **Currently, there isn't an JOSS editor assigned** to your paper.

@ConorMacBride if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637x/795/1/9 is OK
- 10.1098/rsta.2020.0216 is OK
- 10.1098/rsta.2020.0171 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.44 s (176.6 files/s, 21465.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          39           1452           2530           3122
reStructuredText                17            191            119            488
YAML                             7             25             31            185
Jupyter Notebook                 3              0            721            167
JSON                             2              1              0             86
INI                              1              3              0             41
Markdown                         1             13              0             39
TeX                              1              3              0             39
DOS Batch                        1              8              1             26
IDL                              1              7              8             17
make                             1              4              7              9
C                                2              2              0              8
TOML                             1              1              0              7
-------------------------------------------------------------------------------
SUM:                            77           1710           3417           4234
-------------------------------------------------------------------------------


Statistical information for the repository '8215206438df162a10d0a9f4' was
gathered on 2021/04/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Conor MacBride                 117          9542           2428          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Conor MacBride             7114           74.6          1.9               14.04
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03195/joss.03195/10.21105.joss.03195.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03195/joss.03195/10.21105.joss.03195.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @ConorMacBride - thanks for your submission to JOSS. can you tell me if this paper is associated with one in a AAS journal?

**Comment by ConorMacBride** [comment]
> :wave: @ConorMacBride - thanks for your submission to JOSS. can you tell me if this paper is associated with one in a AAS journal?

It is not.

**Comment by arfon** [comment]
@whedon invite @mbobra as editor

:wave: @mbobra - would you be willing to edit this submission for us?

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by mbobra** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
@ConorMacBride Thanks for your submission! If you have any suggestions for reviewers, please let me know here (you can give me the Github handle without @ mentioning them, e.g. mbobra instead of @mbobra).

**Comment by ConorMacBride** [comment]
Hi @mbobra, thank you for agreeing to be editor. From the JOSS spreadsheet, the following people (in the order they are listed) have Python as a preferred language and are in the solar physics area: mgalloy, Cadair, hayesla, aasensio, samaloney, dstansby. I have no particular preference. You may know others who would be most suited and available. Thanks!

**Comment by mbobra** [comment]
@whedon assign @mgalloy as reviewer

**Comment by whedon** [comment]
OK, @mgalloy is now a reviewer

**Comment by mbobra** [comment]
@ConorMacBride I'm still working on finding a second reviewer!

**Comment by mbobra** [comment]
@whedon add @Goobley as reviewer

**Comment by whedon** [comment]
OK, @Goobley is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3265.

**Comment by mbobra** [comment]
@mgalloy @Goobley See you over in #3265!
