### ISSUE TITLE
[PRE REVIEW]: S(ound)lab: A teaching-oriented Python package for designing and running psychoacoustic experiments.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3196]
**Submitting author:** @DrMarc (<a href="http://orcid.org/0000-0002-2023-1207">Marc Schönwiesner</a>)
**Repository:** <a href="https://github.com/DrMarc/slab" target ="_blank">https://github.com/DrMarc/slab</a>
**Version:** v0.9.0
**Editor:** @arfon
**Reviewers:** @hadware, @sneakers-the-rat
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @DrMarc. **Currently, there isn't an JOSS editor assigned** to your paper.

@DrMarc if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.38 s (91.5 files/s, 18396.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            356           1632           3217
reStructuredText                 8            256            227            765
Markdown                         3             77              0            309
YAML                             4             10              3             66
TeX                              1              6              0             61
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            35            717           1870           4453
-------------------------------------------------------------------------------


Statistical information for the repository 'ce773a7734b7746975f1af0b' was
gathered on 2021/04/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Marc                             2             0             18            0.09
Marc Schoenwiesner             203          9251           5402           72.40
Ole Bialas                      14          3515           2052           27.51

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Marc Schoenwiesner         2493           26.9         14.9                3.97
Ole Bialas                 2712           77.2          1.7               12.02
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3196 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3758/s13428-018-01193-y is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- 10.25080/majora-7b98e3ed-003 may be a valid DOI for title: librosa: Audio and music signal analysis in python

INVALID DOIs

- None
```

**Comment by arfon** [comment]
:wave: @DrMarc - thanks for your submission to JOSS. A few housekeeping issues here related to your paper:

- Please either add an ORCID for `Ole Bialas` or remove the blank entry for them.
- Please check the suggested DOI above from @whedon, and if it looks correct, then please update your BibTeX file with the corresponding DOI.

Also, could you confirm the main purpose of this software? From my initial read of your paper, this sounds like it's primary purpose is as a teaching tool, which is not in scope for JOSS (but is in scope for our sister journal JOSE, [_Journal of Open Source Education_](http://jose.theoj.org)).

**Comment by DrMarc** [comment]
Hi,
thanks for your comment. The package is aimed at designing and running actual experiments and is used in that capacity in our lab (several papers using it are forthcoming). Since we have many Master and Bachelor students, we also wanted something that will allow them to go from zero Python experience to actual research within the typical 6-months timespan of a thesis. This turned out to be very useful in our lab and resulted in a productivity boost, which is why we discuss it prominently in the paper. If you think it's overdone or sounds out of scope, we can tone that aspect down.
Cheers,
Marc

**Comment by DrMarc** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3758/s13428-018-01193-y is OK
- 10.25080/majora-7b98e3ed-003 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by DrMarc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03196/joss.03196/10.21105.joss.03196.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03196/joss.03196/10.21105.joss.03196.pdf) :page_facing_up: :point_left:

**Comment by DrMarc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03196/joss.03196/10.21105.joss.03196.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03196/joss.03196/10.21105.joss.03196.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon are you happy with the above :point_up: comments on the applications of this work? Let me know if you want me to pick this up.

**Comment by arfon** [comment]
> @arfon are you happy with the above ☝️ comments on the applications of this work?

:+1: yep, this sounds reasonable to me. I'm also happy to take this submission on.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@DrMarc - could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by DrMarc** [comment]
Hi @arfon ,
Many thanks, glad to hear it. Below are the reviewers from the list that have listed relevant expertise in audio signal processing and/or psychophysics related to sound or speech stimuli:
peircej, jonathan.peirce@nottingham.ac.uk
trettenbrein, trettenbrein@cbs.mpg.de
JonathanReardon, jonathanjreardon@gmail.com
sneakers-the-rat, jlsaunders987@gmail.com
faroit, mail@faroit.com
hadware, hadrien.titeux@ens.fr

Cheers,
Marc

**Comment by arfon** [comment]
👋 @sneakers-the-rat @hadware @peircej - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is [_S(ound)lab: A teaching-oriented Python package for designing and running psychoacoustic experiments_](https://github.com/DrMarc/slab).

**Comment by hadware** [comment]
Definitely! This looks like a very interesting package to review.

**Comment by arfon** [comment]
Great, thanks @hadware! I'll add you to the review now but won't actually kick off the review process properly until I've identified a second reviewer.

**Comment by arfon** [comment]
@whedon add @hadware as reviewer

**Comment by whedon** [comment]
OK, @hadware is now a reviewer

**Comment by sneakers-the-rat** [comment]
sorry just saw this, sure would be happy to review :)

**Comment by arfon** [comment]
@whedon add @sneakers-the-rat as reviewer

**Comment by whedon** [comment]
OK, @sneakers-the-rat is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3284.

**Comment by arfon** [comment]
@hadware, @sneakers-the-rat - many thanks for agreeing to review this submission. See you over in #3284 where the actual review will take place!
