### ISSUE TITLE
[REVIEW]: genomepy: download genomes the easy way

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#320]
**Submitting author:** @simonvh (<a href="http://orcid.org/0000-0002-0411-3219">SJ van Heeringen</a>)
**Repository:** <a href="http://github.com/simonvh/genomepy" target ="_blank">http://github.com/simonvh/genomepy</a>
**Version:** 0.3.1
**Editor:** @pjotrp
**Reviewer:** @kblin
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.831969" target="_blank">10.5281/zenodo.831969</a>

## Status

[![status](http://joss.theoj.org/papers/df434a15edd00c8c2f4076668575d1cd/status.svg)](http://joss.theoj.org/papers/df434a15edd00c8c2f4076668575d1cd)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/df434a15edd00c8c2f4076668575d1cd"><img src="http://joss.theoj.org/papers/df434a15edd00c8c2f4076668575d1cd/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/df434a15edd00c8c2f4076668575d1cd/status.svg)](http://joss.theoj.org/papers/df434a15edd00c8c2f4076668575d1cd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="http://github.com/simonvh/genomepy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@kblin, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="http://github.com/simonvh/genomepy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.3.1)?
- [x] **Authorship:** Has the submitting author (@simonvh) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @kblin it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by pjotrp** [comment]
@kblin ping

**Comment by kblin** [comment]
Looks good to me. Apart from the example in the README, I did not see documentation on using the API functions, but this is mainly a command line tool, and the CLI is documented nicely.

**Comment by pjotrp** [comment]
Thanks @kblin! Great we have a submission with a focus on reproducible research! 

@arfon we are ready to accept this submission.

**Comment by arfon** [comment]
> @arfon we are ready to accept this submission.

Great! @simonvh could you please merge this PR https://github.com/simonvh/genomepy/pull/18 which fixes up the paper metadata. 

Then, could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by arfon** [comment]
Friendly reminder @simonvh

**Comment by simonvh** [comment]
Sorry @arfon, holidays without computer so it took a while. PR is now merged, thanks! The Zenodo DOI of this version is [10.5281/zenodo.831969](https://doi.org/10.5281/zenodo.831969).

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.831969 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.831969" target="_blank">10.5281/zenodo.831969</a> is the archive.

**Comment by arfon** [comment]
@kblin - many thanks for your review here and to @pjotrp for editing this submission ✨ 

@simonvh - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00320 ⚡️ 🚀 💥
