### ISSUE TITLE
[PRE REVIEW]: atlite: A Lightweight Python Package for Calculating Renewable Power Potentials and Time Series

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3204]
**Submitting author:** @fabianhofmann (<a href="http://orcid.org/0000-0002-6604-5450">Fabian Hofmann</a>)
**Repository:** <a href="https://github.com/PyPSA/atlite" target ="_blank">https://github.com/PyPSA/atlite</a>
**Version:** v0.2.2
**Editor:** @timtroendle
**Reviewers:** @kanderso-nrel, @crvernon
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @fabianhofmann. **Currently, there isn't an JOSS editor assigned** to your paper.

@fabianhofmann if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.72 s (104.2 files/s, 20057.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          27           1167           1516           2832
Jupyter Notebook                 7              0           6579            434
reStructuredText                11            236            190            399
DOS Batch                        1             55              3            359
YAML                            24             57            181            241
Markdown                         3             20              0             70
CSS                              1             14              6             54
make                             1              7             10              9
-------------------------------------------------------------------------------
SUM:                            75           1556           8485           4398
-------------------------------------------------------------------------------


Statistical information for the repository '3f257b608bd5fbfe09283b70' was
gathered on 2021/04/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bryn Pickering                   1             6              1            0.06
David Schlachtberger             6            86             32            0.93
Fabian                           7            62             29            0.72
Fabian Neumann                   1             9              3            0.09
FabianHofmann                    9          1032             89            8.86
Jonas Hoersch                   65          2738            954           29.18
Jonas Hörsch                    76          4258           2289           51.74
Leon                             1             7              2            0.07
Markus Schlott                  11           347             68            3.28
Tom Brown                       17           321             34            2.81
euronion                        14           215             64            2.20
fabianhofmann                    1             2              2            0.03
hailiangliu89                    2             2              2            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
David Schlachtberger         55           64.0         49.9               23.64
Fabian                       60           96.8          5.3               25.00
Fabian Neumann                1           11.1          4.9                0.00
Jonas Hoersch               775           28.3         31.8                8.00
Jonas Hörsch               3363           79.0          9.8               13.98
Leon                          1           14.3         22.2                0.00
Markus Schlott               64           18.4         51.9                4.69
Tom Brown                    83           25.9         46.2               15.66
euronion                    101           47.0         24.0               11.88
fabianhofmann              1012        50600.0          1.5                7.81
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #3204 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-review-fneum

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-review-fneum. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03204/joss.03204/10.21105.joss.03204.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03204/joss.03204/10.21105.joss.03204.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @FabianHofmann - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by FabianHofmann** [comment]
Thank you @arfon!

Just for you information, the paper.md is in the branch `joss` (not `joss-review-fneum`) in the paper directory (I did not now how to trigger the robot exactly)

**Comment by FabianHofmann** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03204/joss.03204/10.21105.joss.03204.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03204/joss.03204/10.21105.joss.03204.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon assign @timtroendle as editor

**Comment by whedon** [comment]
OK, the editor is @timtroendle

**Comment by timtroendle** [comment]
I am happy to serve as an editor for this submission.

For transparency: I co-authored [a publication (published in January 2018)](https://doi.org/10.1016/j.esr.2017.12.002) together with one of the authors of `atlite`. The publication had 23 authors in total and the amount of direct collaboration between the two of us was little.

**Comment by timtroendle** [comment]
@FabianHofmann, I am looking forward to working with you on this submission! I will start looking for reviewers now. If you have any suggestions, please let us know.

**Comment by FabianHofmann** [comment]
@timtroendle great, thank you for taking care of this! From the list of reviewers, I'd think that both Kevin Anderson and Will Holmgren would suit well. Also GIS related reviewers could fit...

**Comment by danielskatz** [comment]
@whedon assign @timtroendle as editor

thanks @timtroendle - you can also do this yourself when you want :)

**Comment by whedon** [comment]
OK, the editor is @timtroendle

**Comment by martibosch** [comment]
Hello @timtroendle, thank you for your invitation, but I am afraid that I will have to decline it as I already have a lot of work to do and I will thus be me very busy the following months. Additionally, I do not have much experience with the subject so I am sure that other reviewers will be better suited for this submission.

Best,
Martí

**Comment by timtroendle** [comment]
That's fine of course, @martibosch . Thanks for letting us know.

**Comment by timtroendle** [comment]
👋 @sgrieve, would you be willing to review this submission for JOSS?

**Comment by timtroendle** [comment]
👋 @kanderso-nrel, would you be willing to review this submission for JOSS?

**Comment by kanderso-nrel** [comment]
Hi @timtroendle, sure I can review this.

**Comment by timtroendle** [comment]
@whedon add @kanderso-nrel as reviewer

**Comment by whedon** [comment]
OK, @kanderso-nrel is now a reviewer

**Comment by wholmgren** [comment]
Sorry for the slow response here. I need to pass this time but happy to review in the future. `atlite` looks like an interesting package!

**Comment by timtroendle** [comment]
Thanks for letting us know, @wholmgren !

**Comment by timtroendle** [comment]
👋 @hertzsprung, @crvernon would any of you be willing to review this submission for JOSS?

**Comment by crvernon** [comment]
Hello @timtroendle I'll be happy to do this review!

**Comment by timtroendle** [comment]
That's great @crvernon . Happy to have you on board. Thanks again @crvernon and @kanderso-nrel for accepting to review this submission. We'll start the review with the two of you. @sgrieve and @hertzsprung, if any of you is still interested in joining the review at a later point, please let me know.

**Comment by timtroendle** [comment]
@whedon add @crvernon as reviewer

**Comment by whedon** [comment]
OK, @crvernon is now a reviewer

**Comment by timtroendle** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3294.
