### ISSUE TITLE
[PRE REVIEW]: rmcorrShiny: A web application for repeated measures correlation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3205]
**Submitting author:** @lmarusich (<a href="http://orcid.org/0000-0002-3524-6110">Laura Marusich</a>)
**Repository:** <a href="https://github.com/lmarusich/rmcorrShiny" target ="_blank">https://github.com/lmarusich/rmcorrShiny</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lmarusich. **Currently, there isn't an JOSS editor assigned** to your paper.

@lmarusich if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (516.3 files/s, 104534.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              0             19           2640
R                               21            360            239           1896
JSON                             6             30              0            863
Markdown                         3            139              0            613
TeX                              1             16              0            167
HTML                             1              8              5             46
Rmd                              1             15             25              6
-------------------------------------------------------------------------------
SUM:                            35            568            288           6231
-------------------------------------------------------------------------------


Statistical information for the repository '726b54f3fc818faa04dc2ab7' was
gathered on 2021/04/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03205/joss.03205/10.21105.joss.03205.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03205/joss.03205/10.21105.joss.03205.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fpsyg.2020.609647 is OK
- 10.1186/1471-2202-11-5 is OK
- 10.1093/cercor/bhi044 is OK
- 10.1038/nn.3648 is OK
- 10.3389/fpsyg.2017.00456 is OK
- 10.21105/joss.01026 is OK
- 10.1136/bmj.310.6977.446 is OK
- 10.1136/bmj.310.6980.633 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lmarusich** [comment]
Suggested reviewers from the provided list: smasongarrison,  matherion, humanfactors, katschueler

**Comment by arfon** [comment]
@whedon query scope

:wave: @lmarusich – due to the relatively small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@lmarusich - many thanks for your submission to JOSS. Unfortunately packages such as this that provide a limited GUI wrapper around another tool are generally classified as out of scope for us.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
