### ISSUE TITLE
[PRE REVIEW]: JPhyloRef: a tool for testing and resolving phyloreferences

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3206]
**Submitting author:** @gaurav (<a href="http://orcid.org/0000-0003-0587-0454">Gaurav Vaidya</a>)
**Repository:** <a href="https://github.com/phyloref/jphyloref" target ="_blank">https://github.com/phyloref/jphyloref</a>
**Version:** v1.0.0
**Editor:** @kellyrowland
**Reviewers:** @iimog, @7omasz
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gaurav. **Currently, there isn't an JOSS editor assigned** to your paper.

@gaurav if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.25 s (121.0 files/s, 18555.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                            15            412            734           2081
XML                              2              0              0            356
Maven                            1             29             30            270
Markdown                         5             51              0            221
TeX                              1              9              4            184
JSON                             3              0              0            167
YAML                             1              4              3             20
Bourne Shell                     2              5              9             13
-------------------------------------------------------------------------------
SUM:                            30            510            780           3312
-------------------------------------------------------------------------------


Statistical information for the repository 'f31b6309815627c2764ae17f' was
gathered on 2021/04/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Gaurav Vaidya                  144          4466           1994           85.31
Hilmar Lapp                      2             2              2            0.05
gaurav                          17           909            199           14.63

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Gaurav Vaidya              3227           72.3         26.3               22.75
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.32942/osf.io/57yjs is OK
- 10.1146/annurev.es.23.110192.002313 is OK
- 10.1007/BF00129972 is OK
- 10.2307/2992353 is OK
- 10.1007/s10817-013-9296-3 is OK
- 10.1080/10635150701656378 is OK
- 10.3233/SW-2011-0025 is OK
- 10.5281/zenodo.4697965 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03206/joss.03206/10.21105.joss.03206.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03206/joss.03206/10.21105.joss.03206.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@gaurav - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by gaurav** [comment]
Thanks so much for the update, Arfon!

**Comment by arfon** [comment]
@whedon invite @kellyrowland as editor

:wave: @kellyrowland – I realize this is a little out of your wheelhouse but would you be willing to edit this submission for us?

**Comment by whedon** [comment]
@kellyrowland has been invited to edit this submission.

**Comment by kellyrowland** [comment]
Sure thing, happy to step in.

**Comment by kellyrowland** [comment]
@whedon add @kellyrowland as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kellyrowland** [comment]
@whedon assign @kellyrowland as editor

**Comment by whedon** [comment]
OK, the editor is @kellyrowland

**Comment by kellyrowland** [comment]
Hi, @gaurav - if you have any suggestions for potential reviewers, please mention them here in this thread (without tagging them with an @).

**Comment by kellyrowland** [comment]
Hi @iimog and @7omasz - would you be available and willing to review this paper for JOSS?

**Comment by iimog** [comment]
I'd be willing to review this paper for JOSS. I can start working on the review next week.

**Comment by kellyrowland** [comment]
Great, thank you!

**Comment by kellyrowland** [comment]
@whedon add @iimog as reviewer

**Comment by whedon** [comment]
OK, @iimog is now a reviewer

**Comment by 7omasz** [comment]
Hi @kellyrowland, happy to help, but may need a couple weeks to complete.

**Comment by kellyrowland** [comment]
@gaurav - is that review timeframe okay for you? I'm okay with it if you are.

**Comment by gaurav** [comment]
That's fine by us! So sorry for the delay in replying -- I've been out on vacation. I'm back now, so I should be able to reply sooner in the future. Thanks so much, everybody!

**Comment by kellyrowland** [comment]
Thanks! Glad to hear that you weren't replying on your vacation. 🙂

**Comment by kellyrowland** [comment]
@whedon add @7omasz as reviewer

**Comment by whedon** [comment]
OK, @7omasz is now a reviewer

**Comment by kellyrowland** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3374.
