### ISSUE TITLE
[PRE REVIEW]: geocmeans: An R package for spatial fuzzy c-means

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3207]
**Submitting author:** @JeremyGelb (<a href="http://orcid.org/0000-0002-7114-2714">Jeremy Gelb</a>)
**Repository:** <a href="https://github.com/JeremyGelb/geocmeans" target ="_blank">https://github.com/JeremyGelb/geocmeans</a>
**Version:** v0.1.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JeremyGelb. **Currently, there isn't an JOSS editor assigned** to your paper.

@JeremyGelb if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (266.2 files/s, 52384.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                8            172           1043            945
Markdown                         5            149              0            358
Rmd                              2            159            251            210
YAML                             1             14              6             87
TeX                              1              6              0             71
JSON                             1              3              0             68
-------------------------------------------------------------------------------
SUM:                            18            503           1300           1739
-------------------------------------------------------------------------------


Statistical information for the repository '2795e48c3d7e1b0b2e1f08dd' was
gathered on 2021/04/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.4000/cybergeo.36414 is OK
- 10.1016/j.patcog.2006.07.011 is OK
- 10.1016/j.dsp.2012.09.016 is OK
- 10.1007/s00180-018-0791-1 is OK
- 10.1080/13658810600665111 is OK
- 10.1111/j.1538-4632.2006.00689.x is OK

MISSING DOIs

- 10.2307/622300 may be a valid DOI for title: A geographical solution to scale and aggregation problems in region-building, partitioning and spatial modelling

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03207/joss.03207/10.21105.joss.03207.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03207/joss.03207/10.21105.joss.03207.pdf) :page_facing_up: :point_left:

**Comment by JeremyGelb** [comment]
adding the missing DOI as suggest by whedon
@whedon generate pdf

**Comment by JeremyGelb** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03207/joss.03207/10.21105.joss.03207.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03207/joss.03207/10.21105.joss.03207.pdf) :page_facing_up: :point_left:

**Comment by JeremyGelb** [comment]
Here is a first selection of potential reviewers from the provided list: jpiburn, ssujit, yongzesong, crvernon

**Comment by arfon** [comment]
:wave: @JeremyGelb – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.4000/cybergeo.36414 is OK
- 10.1016/j.patcog.2006.07.011 is OK
- 10.1016/j.dsp.2012.09.016 is OK
- 10.1007/s00180-018-0791-1 is OK
- 10.2307/622300 is OK
- 10.1080/13658810600665111 is OK
- 10.1111/j.1538-4632.2006.00689.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by JeremyGelb** [comment]
I understand, feel free to contact me if you have any question

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
