### ISSUE TITLE
[PRE REVIEW]: experDesign: helping performing experiments on batches

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3214]
**Submitting author:** @llrs (<a href="http://orcid.org/0000-0001-9747-2570">Lluís Revilla Sancho</a>)
**Repository:** <a href="https://github.com/llrs/experDesign" target ="_blank">https://github.com/llrs/experDesign</a>
**Version:** 0.1.0
**Editor:** @lpantano
**Reviewers:** @abartlett004, @stemangiola
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @llrs. **Currently, there isn't an JOSS editor assigned** to your paper.

@llrs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (619.4 files/s, 31502.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               36            146            420            813
Markdown                         6            108              0            368
YAML                             5             39             10            175
JSON                             1              0              0            154
Rmd                              2             83            173             54
-------------------------------------------------------------------------------
SUM:                            50            376            603           1564
-------------------------------------------------------------------------------


Statistical information for the repository 'a33266dfbe72aa7f598b47bf' was
gathered on 2021/04/23.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3214 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by llrs** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03214/joss.03214/10.21105.joss.03214.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03214/joss.03214/10.21105.joss.03214.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@llrs – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by llrs** [comment]
Hi @arfon, I know JOSS is in reduced service mode and I am not in any hurry, but do you have any update on the scope of the article? Many thanks for providing these resource to the developers and looking forward to its success.

**Comment by danielskatz** [comment]
@llrs - we've decided we will review this, though there is some chance the reviewers will still comment on scope/size of the work

**Comment by danielskatz** [comment]
👋 @mbobra - Would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by llrs** [comment]
Many thanks, looking forward to the reviewers comments.

**Comment by mbobra** [comment]
👋 @danielskatz Thanks for the invite. I don't know how to program in R, so I don't think I could do this one justice. But please feel free to throw another submission (in Python) my way!

**Comment by danielskatz** [comment]
Ok, thanks - this is something that is hard to remember and our editor bios - I'm going to add Python to your editor categories...

**Comment by danielskatz** [comment]
👋 @lpantano - would this be something you would consider editing?

**Comment by danielskatz** [comment]
@whedon invite @lpantano as editor

**Comment by whedon** [comment]
@lpantano has been invited to edit this submission.

**Comment by lpantano** [comment]
@whedon add me as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by lpantano** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by lpantano** [comment]
@whedon assign @lpantano as reviewer

**Comment by whedon** [comment]
You need to assign an editor first.

**Comment by lpantano** [comment]
@whedon assign @username as editor

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by danielskatz** [comment]
Thanks!

FYI `@whedon assign me as editor` would have also worked

**Comment by lpantano** [comment]
thanks, sorry, clearly Friday is not my day to do this kind of tasks...

**Comment by lpantano** [comment]
@whedon assign @abartlett004 as reviewer

**Comment by whedon** [comment]
OK, @abartlett004 is now a reviewer

**Comment by lpantano** [comment]
@nagoue,@nhejazi are you interested on reviewing this tool? Thanks!

**Comment by nhejazi** [comment]
@lpantano Thanks for pinging me for this review -- it looks like an interesting package and paper; however, I will not be able to provide a timely review at present, due to a confluence of external deadlines. Happy to help out again in the future.

**Comment by lpantano** [comment]
@tleonardi,@waldeyr, would you be interested on reviewing this tool? thanks!

**Comment by tleonardi** [comment]
Hi @lpantano, thanks for considering me but unfortunately I really don't have time to provide a timely review at the moment.  I can suggest @ocroci as a potential reviewer. Happy to help reviewing other submissions in the future!

**Comment by lpantano** [comment]
Hi @stemangiola, would you be interested on reviewing this R tool? thanks!

**Comment by stemangiola** [comment]
Hello @lpantano, sure I will review.

**Comment by lpantano** [comment]
@whedon add @stemangiola as reviewer

**Comment by whedon** [comment]
OK, @stemangiola is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3358.
