### ISSUE TITLE
[PRE REVIEW]: Beiwe: A data collection platform for high-throughput digital phenotyping

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3216]
**Submitting author:** @jponnela (<a href="http://orcid.org/0000-0001-6613-8668">Jukka-Pekka Onnela</a>)
**Repository:** <a href="https://github.com/onnela-lab/beiwe-backend" target ="_blank">https://github.com/onnela-lab/beiwe-backend</a>
**Version:** 2.0.1
**Editor:** @fboehm
**Reviewers:** @Tam-Pham, @erik-whiting
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jponnela. **Currently, there isn't an JOSS editor assigned** to your paper.

@jponnela if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.75 s (122.9 files/s, 26539.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      96           4836           6738          27059
Python                         174           3368           3273          13951
CSS                             11             98            221           8153
HTML                            39            360             57           3287
YAML                             2             11             33            383
SVG                              1              0              0            288
Bourne Shell                     4             70             70            262
Markdown                         4             43              0            170
TeX                              1             14              0            137
JSON                             6              0              0             83
-------------------------------------------------------------------------------
SUM:                           338           8800          10392          53773
-------------------------------------------------------------------------------


Statistical information for the repository '3a26cb9af39a39d93b55f5d4' was
gathered on 2021/04/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aaron Klein                    161          7752           4993            9.38
Ali Abdullah                     3            29              7            0.03
Alvin Siu                       41          1433            734            1.59
Caleb                           78          2853           1762            3.40
Caleb-Dixon                      3           331              9            0.25
Chris McCarthy                   9           290             98            0.29
Daniel Norton                    6             9              9            0.01
Dor Samet                      142         16833            494           12.75
Eli Jones                     1384         39004          25507           47.48
Erinn Looney-Triggs              8            77             17            0.07
Jake Klingensmith                3            13             12            0.02
Josh Zagorsky                    6            41             56            0.07
Keary Griffin                   17           147             38            0.14
Kevin Fan                        7           263             48            0.23
Leila                            1            10              5            0.01
Leila Minowada                  11          1071            509            1.16
Sean Esterkin                   35          1135            288            1.05
Teh Beebles                      1             1              1            0.00
kfan                            18           236            116            0.26
kfantastic                      24         10750            257            8.10
leila                            9           809            388            0.88
tjaeni01                        59          1609            626            1.64
zagorsky                       211         13426           1772           11.19

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Aaron Klein                1310           16.9         42.8                8.63
Ali Abdullah                  9           31.0         35.2                0.00
Alvin Siu                   907           63.3         42.6               18.96
Caleb                      1046           36.7          5.8                8.80
Caleb-Dixon                 277           83.7          6.5                6.50
Chris McCarthy                3            1.0         81.3                0.00
Daniel Norton                 1           11.1         14.5                0.00
Dor Samet                 16259           96.6         79.5               22.92
Eli Jones                 15693           40.2         24.0               14.50
Erinn Looney-Triggs          74           96.1         21.3                4.05
Jake Klingensmith             8           61.5         21.8                0.00
Josh Zagorsky                14           34.1          2.2               35.71
Keary Griffin                42           28.6         60.0                2.38
Kevin Fan                    12            4.6         48.1                0.00
Sean Esterkin               509           44.8         34.1                5.11
kfantastic                10371           96.5         79.7               16.58
leila                       949          117.3         21.7               12.96
tjaeni01                    693           43.1         13.0                9.09
zagorsky                  11048           82.3         68.0                8.08
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03216/joss.03216/10.21105.joss.03216.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03216/joss.03216/10.21105.joss.03216.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1097/phm.0000000000001506 may be a valid DOI for title: Digital Phenotyping to Quantify Psychosocial Well-Being Trajectories After Spinal Cord Injury
- 10.1001/jamasurg.2019.4702 may be a valid DOI for title: Using smartphones to capture novel recovery metrics after cancer surgery
- 10.1002/acn3.770 may be a valid DOI for title: Design and results of a smartphone-based digital phenotyping study to quantify ALS progression
- 10.1016/j.wneu.2019.01.297 may be a valid DOI for title: Digital phenotyping in patients with spine disease: a novel approach to quantifying mobility and quality of life
- 10.1038/s41746-018-0022-8 may be a valid DOI for title: Characterizing the clinical relevance of digital phenotyping data quality with applications to a cohort with schizophrenia
- 10.1200/cci.17.00149 may be a valid DOI for title: The HOPE pilot study: harnessing patient-reported outcomes and biometric data to enhance cancer care
- 10.1038/s41386-018-0030-z may be a valid DOI for title: Relapse prediction in schizophrenia through digital phenotyping: a pilot study
- 10.1038/s41537-017-0038-0 may be a valid DOI for title: A comparison of passive and active estimates of sleep in a cohort with schizophrenia
- 10.1038/npp.2016.7 may be a valid DOI for title: Harnessing smartphone-based digital phenotyping to enhance behavioral and mental health
- 10.2196/mental.5165 may be a valid DOI for title: New tools for new research in psychiatry: a scalable and customizable platform to empower data driven smartphone research

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@jponnela - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

In the meantime, if you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by jponnela** [comment]
@whedon generate pdf

**Comment by jponnela** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03216/joss.03216/10.21105.joss.03216.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03216/joss.03216/10.21105.joss.03216.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1177/2167702621993857 is OK
- 10.1002/mus.27110 is OK
- 10.1097/phm.0000000000001506 is OK
- 10.1097/SLA.0000000000004487 is OK
- 10.1245/s10434-020-09004-5 is OK
- 10.1001/jamasurg.2019.4702 is OK
- 10.1002/acn3.770 is OK
- 10.1016/j.wneu.2019.01.297 is OK
- 10.1038/s41746-018-0022-8 is OK
- 10.1200/cci.17.00149 is OK
- 10.1038/s41386-018-0030-z is OK
- 10.1038/s41537-017-0038-0 is OK
- 10.1038/npp.2016.7 is OK
- 10.2196/mental.5165 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
@whedon invite @csoneson as editor

@csoneson can you edit this submission?

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@kyleniemeyer - I'm afraid that this is pretty far from what I have experience with, especially in terms of the implementation framework...I think an editor with closer experience would do a better job here.

**Comment by kthyng** [comment]
@fboehm Are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by fboehm** [comment]
@kthyng - yes, I'm happy to edit this submission. Thanks!

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@jponnela - do you have any suggestions for reviewers? They can be people from the list of JOSS reviewers, but I'm also happy to invite reviewers who haven't reviewed for JOSS yet. Ideally, the reviewers will have considerable expertise in your area of research.

**Comment by fboehm** [comment]
@jponnela - Do you have any suggestions for reviewers? Once we find two reviewers, the review can begin. 

Thanks again!

**Comment by fboehm** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by fboehm** [comment]
@vasudev-sharma and @Tam-Pham - would you be willing to review this submission to JOSS?

**Comment by fboehm** [comment]
@erik-whiting - would you be willing to review this submission to JOSS?

**Comment by vasudev-sharma** [comment]
@fboehm thanks for asking for the reivew. However, this submission doesn't fall under my areas of expertise.

**Comment by fboehm** [comment]
@vasudev-sharma - Thanks for the prompt and thoughtful reply. I hope that we can work together on a future submission.

**Comment by erik-whiting** [comment]
@fboehm I can review the software aspects of this submission, but I'm not qualified to comment on the science. Also, it will probably take me a few weeks to do a thorough review. If that's acceptable to you then yes, I'll review the submission.

**Comment by Tam-Pham** [comment]
@fboehm thank you for reaching out. I would be happy to review this submission.

**Comment by fboehm** [comment]
Thank you, @Tam-Pham ! I'll add you as a reviewer. 

And thank you, @erik-whiting! I would very much appreciate your review of the software. And yes, it's ok to spend a few weeks on the review. We would like to complete it by the end of July, but there is some flexibility around that date.

**Comment by fboehm** [comment]
@whedon assign @Tam-Pham as reviewer

**Comment by whedon** [comment]
OK, @Tam-Pham is now a reviewer

**Comment by fboehm** [comment]
@whedon add @erik-whiting as reviewer

**Comment by whedon** [comment]
OK, @erik-whiting is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3417.
