### ISSUE TITLE
[PRE REVIEW]: Omnizart: A General Toolbox for Automatic Music Transcription

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3218]
**Submitting author:** @BreezeWhite (<a href="http://orcid.org/0000-0003-2362-6340">Yu Te Wu</a>)
**Repository:** <a href="https://github.com/Music-and-Culture-Technology-Lab/omnizart" target ="_blank">https://github.com/Music-and-Culture-Technology-Lab/omnizart</a>
**Version:** v0.4.1
**Editor:** @faroit
**Reviewers:** @hagenw, @keunwoochoi
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @BreezeWhite. **Currently, there isn't an JOSS editor assigned** to your paper.

@BreezeWhite if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.70 s (253.8 files/s, 58247.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                            25             32             14          23994
Python                         111           2516           2926           8702
reStructuredText                23            358            333            418
Markdown                         5            152              0            381
TeX                              2             30              0            253
Bourne Shell                     4             48             30            166
TOML                             1              7              0             59
make                             2             23             17             56
DOS Batch                        1              8              1             26
JSON                             1              0              0             26
CSS                              1              5              0             18
Dockerfile                       1              6              1             16
-------------------------------------------------------------------------------
SUM:                           177           3185           3322          34115
-------------------------------------------------------------------------------


Statistical information for the repository '211eb75fa58cfcf47032ec6a' was
gathered on 2021/04/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
BreezeWhite                    240         19252           5632           88.53
Derek-Wu                         3             5              5            0.04
Yin-Jyun Luo                     4            79             74            0.54
unknown                         18           438            229            2.37
yjluo                           19          1582            812            8.52

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
BreezeWhite               13241           68.8          3.1                6.18
Yin-Jyun Luo                 60           75.9          2.2               15.00
unknown                     378           86.3          0.1                2.91
yjluo                       465           29.4          2.7                4.73
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03218/joss.03218/10.21105.joss.03218.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03218/joss.03218/10.21105.joss.03218.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1109/taslp.2020.3030482 may be a valid DOI for title: Multi-Instrument Automatic Music Transcription With Self-Attention-Based Instance Segmentation
- 10.1007/978-3-030-01234-2_49 may be a valid DOI for title: Encoder-Decoder with Atrous Separable Convolution for Semantic Image Segmentation
- 10.1109/taslp.2015.2442411 may be a valid DOI for title: Combining Spectral and Temporal Representations for Multipitch Estimation of Polyphonic Music
- 10.1109/icassp.2018.8462079 may be a valid DOI for title: Automatic Music Transcription Leveraging Generalized Cepstral Features and Deep Learning
- 10.1109/icassp.2018.8462420 may be a valid DOI for title: Vocal Melody Extraction Using Patch-Based CNN
- 10.1109/access.2019.2960566 may be a valid DOI for title: Shakedrop regularization for deep residual learning
- 10.1109/tpami.2018.2858821 may be a valid DOI for title: Virtual adversarial training: a regularization method for supervised and semi-supervised learning
- 10.1109/tasl.2009.2026503 may be a valid DOI for title: On the improvement of singing voice separation for monaural recordings using the MIR-1K dataset
- 10.1109/icassp.2018.8461686 may be a valid DOI for title: Invariances and Data Augmentation for Supervised Music Transcription
- 10.25080/majora-7b98e3ed-003 may be a valid DOI for title: librosa: Audio and music signal analysis in python

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@BreezeWhite thanks for this submission. Our editors in this domain are currently not able to take on this submission. I have therefore added the "waitlisted" label, which means one of our editors will pick up this work once they become available. Thanks for your patience. 

In the mean time please consider these comments: 

- [ ] Please rename/rephrase the purpose section to be the required `Statement of need` section. 
- [ ] Consider more clearly describing the direct scientific research application in the statement of need section
- [ ] We recommend that you shorten the paper where possible, as  [our guidelines](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) state "between 250-1000 words".

**Comment by Kevin-Mattheus-Moerman** [comment]
Perhaps @bmcfee or @terrytangyuan could take this submission once they are available.

**Comment by BreezeWhite** [comment]
@Kevin-Mattheus-Moerman Thank you for your mention! And also thanks for the quick advice on our submission.

We are currently modifying the content according to your suggestion. As for the third point, the word count we see on the editor shows there are total 1000 words, just fit in the upper limit. Would that still be a problem? If so, we will try continue to shorten the paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
@BreezeWhite if you are at the 1000 word limit that could be fine. As long as you are not repeating content from the documentation. Thanks. 
FYI you can update the paper whenever you like here by calling: `@whedon generate pdf`

**Comment by arfon** [comment]
@whedon invite @faroit as editor

:wave: @faroit - this looks like it could be perfect for you as a first paper?

**Comment by whedon** [comment]
@faroit has been invited to edit this submission.

**Comment by faroit** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @faroit

**Comment by faroit** [comment]
👋  Hi @BreezeWhite, thanks for your submission to JOSS! I will be serving as the editor for this. We'll use this issue to identify reviewers and resolve technical issues. 

As this toolbox implements a bunch of transcription models, it would be great to have reviewers with domain knowledge who also have experience with frameworks used in the MIR community... I have a few potential reviewers in mind:

- __@ superbock__: author of [madmom](https://github.com/CPJKU/madmom) 
- __@ adarob:__ [magenta](https://github.com/magenta/magenta) core dev
- __@ keunwoochoi:__ author of [DrummerNet](https://github.com/keunwoochoi/DrummerNet)

@BreezeWhite, I am also interested in your input on potential reviewers, so any suggestions you have are also welcome. 
For this, please check the JOSS [COI policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) and only mention them with a space between the @ and their handle (so you would refer to me as "@ faroit").

**Comment by faroit** [comment]
@BreezeWhite while we find potential reviewers, can you please address https://github.com/openjournals/joss-reviews/issues/3218#issuecomment-828230199 and add the missing DOIs as indicated by the [reference check summary](https://github.com/openjournals/joss-reviews/issues/3218#issuecomment-826046133)?

**Comment by BreezeWhite** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03218/joss.03218/10.21105.joss.03218.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03218/joss.03218/10.21105.joss.03218.pdf) :page_facing_up: :point_left:

**Comment by BreezeWhite** [comment]
Hi @faroit, thank you for the suggestions. 

For the DOI issue, I've just updated the missing DOIs in the `paper.bib`, you could check if there are still missing things.
And for the reviewers, I would like to mention @ bmfcc for joining the review process. And also thank you for mentioning the above members that would be a huge help for reviewing the paper.

**Comment by BreezeWhite** [comment]
@whedon check references

**Comment by BreezeWhite** [comment]
@whedon set v0.4.1 as version

**Comment by whedon** [comment]
I'm sorry @BreezeWhite, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/taslp.2020.3030482 is OK
- 10.1007/978-3-030-01234-2_49 is OK
- 10.1109/taslp.2015.2442411 is OK
- 10.1109/icassp.2018.8462079 is OK
- 10.1109/icassp.2018.8462420 is OK
- 10.1109/access.2019.2960566 is OK
- 10.1109/tpami.2018.2858821 is OK
- 10.1109/tasl.2009.2026503 is OK
- 10.1109/icassp.2018.8461686 is OK
- 10.25080/majora-7b98e3ed-003 is OK

MISSING DOIs

- 10.1109/icassp39728.2021.9414409 may be a valid DOI for title: Improving automatic drum transcription using large-scale audio-to-midi aligned data

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon set v0.4.1 as version

**Comment by whedon** [comment]
OK. v0.4.1 is the version.

**Comment by faroit** [comment]
@BreezeWhite 

> And for the reviewers, I would like to mention **@ bmfcc** for joining the review process. And also thank you for mentioning the above members that would be a huge help for reviewing the paper.

by @ bmfcc ... were you referring to @ bmcfee ? In that case, I'm afraid that he is to busy and is not available for a review as he also serves as an topic editor at JOSS.

**Comment by faroit** [comment]
@superbock @keunwoochoi @adarob - would any of you be willing to review this submission for JOSS? The JOSS review process takes place on GitHub and focuses on the software and a short paper. We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The software under review is [_Omnizart: A General Toolbox for Automatic Music Transcription_](https://github.com/Music-and-Culture-Technology-Lab/omnizart).

This issue is a "pre-review" issue in which reviewers are assigned. Once sufficient reviewers are recruited we will open a dedicated review issue where the review will take place.

**Comment by superbock** [comment]
@faroit, thanks for considering me! Unfortunately, I am too busy to properly review the paper before the end of the summer (which I guess is too late).

**Comment by keunwoochoi** [comment]
Hi @faroit, thanks for this! I can do it.

**Comment by hagenw** [comment]
Thanks for asking, but I guess you have enough reviewers now?

**Comment by faroit** [comment]
@hagenw for now, only @keunwoochoi accepted the invitation. I would be very happy if you could review the submission :-)

**Comment by faroit** [comment]
@whedon assign @keunwoochoi as reviewer

**Comment by whedon** [comment]
OK, @keunwoochoi is now a reviewer

**Comment by hagenw** [comment]
OK, great, I would then also agree to review.

**Comment by faroit** [comment]
@whedon assign @hagenw as reviewer

**Comment by whedon** [comment]
OK, @hagenw is now a reviewer

**Comment by faroit** [comment]
@whedon add @keunwoochoi as reviewer

**Comment by whedon** [comment]
OK, @keunwoochoi is now a reviewer

**Comment by faroit** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by faroit** [comment]
@whedon check references

**Comment by faroit** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.25 s (749.9 files/s, 226021.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                            27             32             14          29650
Python                         111           2555           2981           8816
JavaScript                       3           1604           1860           6244
reStructuredText                25            432            344            587
HTML                             5             55              0            429
Markdown                         5            169              0            414
TeX                              2             30              0            264
CSS                              2             56              1            241
Bourne Shell                     4             48             30            166
TOML                             1              7              0             59
make                             2             23             17             56
DOS Batch                        1              8              1             26
JSON                             1              0              0             26
Dockerfile                       1              6              1             16
-------------------------------------------------------------------------------
SUM:                           190           5025           5249          46994
-------------------------------------------------------------------------------


Statistical information for the repository '96f09a86d6e166b2ae8f8361' was
gathered on 2021/06/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
BreezeWhite                    267         19646           5818           66.32
Derek-Wu                         3             5              5            0.03
Yin-Jyun Luo                     4            79             74            0.40
unknown                         19         10147            230           27.02
yjluo                           19          1582            812            6.23

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
BreezeWhite               13450           68.5          6.3                6.22
Yin-Jyun Luo                 60           75.9          5.8               15.00
unknown                   10085           99.4          3.1               18.55
yjlolo                      465          100.0          6.4                4.73
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/taslp.2020.3030482 is OK
- 10.1007/978-3-030-01234-2_49 is OK
- 10.1109/taslp.2015.2442411 is OK
- 10.1109/icassp39728.2021.9414409 is OK
- 10.1109/icassp.2018.8462079 is OK
- 10.1109/icassp.2018.8462420 is OK
- 10.1109/access.2019.2960566 is OK
- 10.1109/tpami.2018.2858821 is OK
- 10.1109/tasl.2009.2026503 is OK
- 10.1109/icassp.2018.8461686 is OK
- 10.25080/majora-7b98e3ed-003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by faroit** [comment]
@Kevin-Mattheus-Moerman Is there anything left in the comments you made in https://github.com/openjournals/joss-reviews/issues/3218#issuecomment-828230199 that should be addressed by @BreezeWhite before we proceed with the review process?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03218/joss.03218/10.21105.joss.03218.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03218/joss.03218/10.21105.joss.03218.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@faroit thanks for letting me check this before moving on. Yes I ticked those boxes. 

I have one more minor comment/recommendation below. 

I recommend that the following sentence is rephrased: 
`We believe the release of Omnizart can accelerate the advance of AMT research and contribute to the MIR community.`. 

I have 2 issues with this sentence. 

1. I would avoid statements like "We" or "I" in these papers. Furthermore, the statement `We believe..`, makes it feel like "only a belief", i.e. that there isn't necessarily clear/good evidence to support it. Could the authors rephrase the sentence, if they have confidence in their claims, such that it sounds more firmly grounded in evidence? 
2. The statement `..contribute to the MIR community.` sounds vague, it is unclear what it contributes. Perhaps rephrase. 

I'm not saying the following is the best possible sentence (give this some thought and formulate something yourself) but the following would be an example to avoid the above issues (perhaps summarize something in place of those dots): 
`Omnizart is an important tool for the MIR community, since it can accelerate and advance AMT research by.....` 

@faroit I'll leave you to follow up with this if that is okay, and if you agree.

**Comment by BreezeWhite** [comment]
Hi @Kevin-Mattheus-Moerman, thank you for the advises. I have rephrased the sentences as you have pointed out. Please see if there are still needs to modify the content.

**Comment by faroit** [comment]
> Hi @Kevin-Mattheus-Moerman, thank you for the advises. I have rephrased the sentences as you have pointed out. Please see if there are still needs to modify the content.

@Kevin-Mattheus-Moerman thanks for your suggestions, @BreezeWhite has addressed your comment.

**Comment by faroit** [comment]
@whedon generate pdf

**Comment by faroit** [comment]
@whedon check repository

**Comment by faroit** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.30 s (642.3 files/s, 193576.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                            27             32             14          29650
Python                         111           2555           2981           8816
JavaScript                       3           1604           1860           6244
reStructuredText                25            432            344            587
HTML                             5             55              0            429
Markdown                         5            168              0            412
TeX                              2             30              0            264
CSS                              2             56              1            241
Bourne Shell                     4             48             30            166
TOML                             1              7              0             59
make                             2             23             17             56
DOS Batch                        1              8              1             26
JSON                             1              0              0             26
Dockerfile                       1              6              1             16
-------------------------------------------------------------------------------
SUM:                           190           5024           5249          46992
-------------------------------------------------------------------------------


Statistical information for the repository '933c1889d4372121d8c583e0' was
gathered on 2021/06/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
BreezeWhite                    267         19646           5818           66.32
Derek-Wu                         3             5              5            0.03
Yin-Jyun Luo                     4            79             74            0.40
unknown                         19         10147            230           27.02
yjluo                           19          1582            812            6.23

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
BreezeWhite               13450           68.5          6.3                6.22
Yin-Jyun Luo                 60           75.9          5.8               15.00
unknown                   10085           99.4          3.1               18.55
yjluo                       465           29.4          6.4                4.73
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03218/joss.03218/10.21105.joss.03218.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03218/joss.03218/10.21105.joss.03218.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/taslp.2020.3030482 is OK
- 10.1007/978-3-030-01234-2_49 is OK
- 10.1109/taslp.2015.2442411 is OK
- 10.1109/icassp39728.2021.9414409 is OK
- 10.1109/icassp.2018.8462079 is OK
- 10.1109/icassp.2018.8462420 is OK
- 10.1109/access.2019.2960566 is OK
- 10.1109/tpami.2018.2858821 is OK
- 10.1109/tasl.2009.2026503 is OK
- 10.1109/icassp.2018.8461686 is OK
- 10.25080/majora-7b98e3ed-003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by faroit** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3391.
