### ISSUE TITLE
[PRE REVIEW]: BayesianNetwork: Interactive Bayesian Network Modeling and Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#322]
**Submitting author:** @paulgovan (<a href="http://orcid.org/0000-0002-1821-8492">Paul Govan</a>)
**Repository:** <a href="https://github.com/paulgovan/BayesianNetwork" target ="_blank">https://github.com/paulgovan/BayesianNetwork</a>
**Version:** v0.1.3
**Editor:** @katyhuff
**Reviewer:** @rgiordan

**Author instructions**

Thanks for submitting your paper to JOSS @paulgovan. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@paulgovan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by paulgovan** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by paulgovan** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by paulgovan** [comment]
@whedon set 10.5281/zenodo.822808 as archive

**Comment by whedon** [comment]
I'm sorry @paulgovan, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by paulgovan** [comment]
Perhaps @janschulz or @cdcrabtree

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
@janschulz @cdcrabtree @wrathematics -- I believe you have the background to review this submission -- are any of you interested in reviewing this submission for JOSS?

**Comment by janschulz** [comment]
I've no clue about bayesian models, so if that's not a problem I can do the review.

**Comment by katyhuff** [comment]
I see. Thanks letting me know. I'd like for someone with bayesian
experience to handle this review if possible. @cdcrabtree or @wrathematics,
do either of you have experience with bayesian models?

**Comment by katyhuff** [comment]
@cdcrabtree : Would you be willing to review this submission for JOSS?

**Comment by katyhuff** [comment]
@wrathematics : Would you be willing to review this submission for JOSS?

**Comment by cdcrabtree** [comment]
@katyhuff Sorry about the late reply. After looking over the package, I don't think that I have the background knowledge necessary to be a good reviewer here.

**Comment by katyhuff** [comment]
Just as a quick update on this, please rest assured @paulgovan, I'm emailing for available reviewers.

**Comment by paulgovan** [comment]
Perhaps @robohyun66 based on experience in R and machine learning.

**Comment by katyhuff** [comment]
@paulgovan , Please don't think I've given up. I'm having a terrible time getting folks to agree to review this. Many have cited that it is beyond their comfort zone in machine learning. Thank you for your patience. I am continuing to contact folks.

**Comment by paulgovan** [comment]
@katyhuff thanks for the update.

**Comment by katyhuff** [comment]
@whedon set @rgiordan as reviewer

**Comment by katyhuff** [comment]
@whedon assign @rgiordan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rgiordan

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by katyhuff** [comment]
Hi @paulgovan , I found a willing reviewer! @rgiordan has some near term conflicts, but has kindly promised a review by Oct. 20th at the latest. This will happen over in #425.
