### ISSUE TITLE
[PRE REVIEW]: SEED: Software for the Extraction of Equations from Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3222]
**Submitting author:** @definitely-kyle (<a href="http://orcid.org/0000-0002-2274-4815">Kyle Kean</a>)
**Repository:** <a href="https://github.com/Statistical-Learning-4-System-Id/SEED-3.0" target ="_blank">https://github.com/Statistical-Learning-4-System-Id/SEED-3.0</a>
**Version:** 3.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @definitely-kyle. **Currently, there isn't an JOSS editor assigned** to your paper.

@definitely-kyle if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.02104 is OK
- 10.1073/pnas.1517384113 is OK
- 10.1021/j150111a004 is OK
- 10.1175/1520-0469(1963)020<0130:DNF>2.0.CO;2 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.ifacol.2016.10.249 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.50 s (14.0 files/s, 3192.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            253            134            932
Markdown                         2             69              0            131
TeX                              1              5              0             69
-------------------------------------------------------------------------------
SUM:                             7            327            134           1132
-------------------------------------------------------------------------------


Statistical information for the repository 'f39c16db2163a83cb547166b' was
gathered on 2021/04/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kyle Kean                        5          1030            995           50.11
definitely-kyle                 25          1650            366           49.89

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kyle Kean                   757           73.5          4.5               11.62
definitely-kyle             562           34.1          3.5                8.19
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03222/joss.03222/10.21105.joss.03222.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03222/joss.03222/10.21105.joss.03222.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by Kevin-Mattheus-Moerman** [comment]
@definitely-kyle thanks for this submission. I've flagged this submission for additional scope review by our editorial board. This is standard for submissions of this size. We should get back with a verdict within a week or so.

**Comment by arfon** [comment]
@definitely-kyle - many thanks for your submission to JOSS. Unfortunately packages such as this that provide a limited GUI wrapper around another tool are generally classified as out of scope for us.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
