### ISSUE TITLE
[PRE REVIEW]: Reiz: Structural Source Code Search at Scale

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3223]
**Submitting author:** @isidentical (<a href="http://orcid.org/0000-0002-5081-5529">Batuhan Taskaya</a>)
**Repository:** <a href="https://github.com/reizio/reiz.io" target ="_blank">https://github.com/reizio/reiz.io</a>
**Version:** v1.0.0
**Editor:** @mjsottile
**Reviewers:** @lutzhamel, @yuhc
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @isidentical. **Currently, there isn't an JOSS editor assigned** to your paper.

@isidentical if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.60 s (181.3 files/s, 13366.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          80           1345            173           4086
Markdown                         8            214              0            919
JSON                             4              0              0            901
YAML                             7             13              2            130
TeX                              1              9              0             81
Bourne Shell                     4             14             13             43
DOS Batch                        1              8              1             26
Dockerfile                       2              8              0             17
TOML                             1              2              0             12
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           109           1617            196           6224
-------------------------------------------------------------------------------


Statistical information for the repository '3ed7936f4adedbc8e7388cc4' was
gathered on 2021/04/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Batuhan Taskaya                175         11684           6080          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Batuhan Taskaya            5604           48.0          2.9                3.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03223/joss.03223/10.21105.joss.03223.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03223/joss.03223/10.21105.joss.03223.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.scico.2012.04.008 is OK
- 10.5281/zenodo.4657163 is OK
- 10.1007/s10664-017-9514-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@isidentical thanks for this submission. I have a couple of questions about this submission which I hope you can help with. 
[JOSS requires](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) software to have an obvious research application. Currently, from reading the paper and the statement of need, I get the impression this work presents a very valuable and useful tool for source code searching, however, I fail to understand if their is a clear and direct application to scientific research. Can you help clarify this? Perhaps you can update the statement of need section in the paper to include a clearer description of the scientific research applications. In essence the description should straight away convince a reader that one would definitively cite this work when using it for research because it is clearly important to research or the research outcomes. 

If you make changes to the paper you can update the pdf here by calling `@whedon generate pdf`.

**Comment by isidentical** [comment]
> Currently, from reading the paper and the statement of need, I get the impression this work presents a very valuable and useful tool for source code searching, however, I fail to understand if their is a clear and direct application to scientific research. Can you help clarify this?

Hey @Kevin-Mattheus-Moerman! Thanks for the response and the question. In this research, we share the findings and a practical implementation of a source code search engine that actually process the information regarding syntactical structs in a scalable way. I believe that the major scientific value comes from the new DSL that we introduce, and the query compiler for it.

I've updated the second parapraph of the state of the need describing it's scientific value.

**Comment by isidentical** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03223/joss.03223/10.21105.joss.03223.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03223/joss.03223/10.21105.joss.03223.pdf) :page_facing_up: :point_left:

**Comment by isidentical** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03223/joss.03223/10.21105.joss.03223.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03223/joss.03223/10.21105.joss.03223.pdf) :page_facing_up: :point_left:

**Comment by isidentical** [comment]
@Kevin-Mattheus-Moerman what is the process of recommending reviewers? I've gone through the list and found people whose intersection is PLT / Python / Developer Tooling though I don't know whether I should contact them first or write here.

**Comment by danielskatz** [comment]
@isidentical - sorry for the delay here - the next step is finding a editor for this submission, who will work to find reviewers.  If you have suggestions for reviewers, please put their github usernames here (without the `@` so that they are not tagged)

**Comment by danielskatz** [comment]
👋 @mjsottile - Is there any chance you can take on another submission to edit?

**Comment by danielskatz** [comment]
@whedon invite @mjsottile as editor

**Comment by whedon** [comment]
@mjsottile has been invited to edit this submission.

**Comment by mjsottile** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mjsottile** [comment]
@isidentical If you have suggestions for reviewers please let me know - I will start gathering reviewers in the coming week to start the review.

**Comment by isidentical** [comment]
Without any order on suggestions: lutzhamel, henrik227, yuhc

**Comment by mjsottile** [comment]
:wave: @lutzhamel, @yuhc.  Would you be interested in reviewing this submission to JOSS?  If you haven’t done a JOSS review before, we perform the reviews on github and the process is much lighter weight than a traditional paper review.  The review criteria that we ask reviewers to use as a guide are here (a helpful checklist is provided on the review issue for reference once the review starts): https://joss.readthedocs.io/en/latest/review_criteria.html

Let me know if you’re interested.  Thanks!

**Comment by lutzhamel** [comment]
Hi Matthew:

I'd be more than happy to review this submission. Two quick questions:
what is the typical time frame for a JOSS review?  Does the length of the
submitted paper matter? In other words, is there a minimum or maximum
number of pages that should be considered?

Thanks,
Lutz

**Comment by yuhc** [comment]
Hi @mjsottile, I'd love to. Besides Lutz's questions, is there an deadline for the review and any example of how the review should be organized/posted?

**Comment by mjsottile** [comment]
Excellent - thanks for the positive responses.  In response to your questions:

- Timeframe is generally shorter than a classical journal paper, usually on the order of 1-2 months.  We used to go faster, but in the last year things have slowed down.
- The papers are usually short, anywhere from 3-6 pages usually.  Longer sometimes happens, but it’s generally discouraged unless absolutely necessary.  The review checklist has specific things to look for in the write up.
- The review organization is all based on github issue threads.  When I initiate the review later today, you’ll see a new issue will be created for the review itself.  At the top of the issue each reviewer will have a checklist to work through.  If a submission satisfied all things in the checklist and there are no issues for the author to address, a reviewer can just check off the items and post a note stating that they’re happy with the submission.  If there are issues, usually reviewers post them in the review thread and/or open issues on the project itself (e.g., if there are missing files, issues with the build, bugs noticed, etc…).  Typically we ask that reviewers just make note of the project issue in a comment on the review thread so we’re aware of them.  We don’t expect reviewers to write up a review like you’d see for a normal paper - the checklist and comments in the review thread are sufficient.

If you want to see some example reviews, just pick a paper that was published from the list (https://joss.theoj.org/papers/published) and you can see the papers themselves for a sense of scale/scope, and see the review threads that correspond to each paper.  Some are super short if the paper and package have no issues from the start, while others can get longer if there are more things too address before it’s publishable.

**Comment by mjsottile** [comment]
@whedon assign @lutzhamel as reviewer

**Comment by whedon** [comment]
OK, @lutzhamel is now a reviewer

**Comment by mjsottile** [comment]
@whedon add @yuhc as reviewer

**Comment by whedon** [comment]
OK, @yuhc is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3296.
