### ISSUE TITLE
[PRE REVIEW]: Blinkr: Computer Vision Based Blink Reminder

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3225]
**Submitting author:** @AdritRao (<a href="http://orcid.org/0000-0002-0780-033X">Adrit Rao</a>)
**Repository:** <a href="https://github.com/AdritRao/Blinkr" target ="_blank">https://github.com/AdritRao/Blinkr</a>
**Version:** Python 3.7
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @AdritRao. **Currently, there isn't an JOSS editor assigned** to your paper.

@AdritRao if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (43.2 files/s, 3196.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2             53              0            130
Python                           1             19              9             75
TeX                              1              2              0              8
-------------------------------------------------------------------------------
SUM:                             4             74              9            213
-------------------------------------------------------------------------------


Statistical information for the repository 'ec63c26fc03e7195595308e3' was
gathered on 2021/04/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adrit Rao                        2           106              3          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adrit Rao                   103           97.2          0.0                8.74
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #3225 with the following error: 
```
 Error reading bibliography file paper.bib:
(line 10, column 13):
unexpected "c"
expecting space or ","
Looks like we failed to compile the PDF

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@AdritRao thanks for this submission. 

Unfortunately this submission is not acceptable for JOSS. In particular it is not inline with our `substantial scholarly effort` requirements. [JOSS requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) state that `Submissions under 1000 LOC will usually be flagged, those under 300 LOC will be desk rejected.`

I will therefore proceed to reject this submission at this point. 

We hope you will consider JOSS for future submission which are more substantial in nature (or for expanded versions of the current work).

**Comment by whedon** [comment]
Paper rejected.
