### ISSUE TITLE
[PRE REVIEW]: Makie.jl: Flexible high-performance data visualization for Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3226]
**Submitting author:** @jkrumbiegel (<a href="http://orcid.org/0000-0002-8409-5590">Julius Krumbiegel</a>)
**Repository:** <a href="https://github.com/JuliaPlots/AbstractPlotting.jl" target ="_blank">https://github.com/JuliaPlots/AbstractPlotting.jl</a>
**Version:** v.0.17.4
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @fverdugo, @gaelforget
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jkrumbiegel. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@jkrumbiegel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by whedon** [comment]
PDF failed to compile for issue #3226 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@jkrumbiegel 

Our system cannot find the paper. Where can we find it? The repository for this submission is listed as: https://github.com/JuliaPlots/AbstractPlotting.jl is that correct or should it be https://github.com/JuliaPlots/Makie.jl ? 

Thanks

**Comment by jkrumbiegel** [comment]
The paper is in the `joss-paper` branch in `AbstractPlotting.jl` https://github.com/JuliaPlots/AbstractPlotting.jl/tree/joss-paper

I can also move it to `Makie.jl` if you prefer, but AbstractPlotting is actually the main repository for the Makie ecosystem, due to historical reasons. It could be that we move everything from `AbstractPlotting.jl` to `Makie.jl` in the future as part of a restructuring effort.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03226/joss.03226/10.21105.joss.03226.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03226/joss.03226/10.21105.joss.03226.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @fverdugo as reviewer

**Comment by whedon** [comment]
OK, @fverdugo is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @gaelforget as reviewer

**Comment by whedon** [comment]
OK, @gaelforget is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@cormullion would you be interested in helping with this review?

**Comment by cormullion** [comment]
Nice paper. I can see little that could be improved or needs comment - I would however rephrase the sentence at lines 21-24, which looks like it's missing something:

> To effectively understand and communicate results, different disciplines ranging from [... ? ...] publication-quality static vector graphics, through animated movies , to interactive data exploration tools, require flexible and powerful plotting software.

I won't be able to say anything about the software.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @logankilpatrick

as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @logankilpatrick as reviewer

**Comment by whedon** [comment]
OK, @logankilpatrick is now a reviewer

**Comment by jkrumbiegel** [comment]
@Kevin-Mattheus-Moerman I'm not sure if it makes a difference, but @logankilpatrick has contributed to Makie before. It's only a couple of commits I think, but maybe that is still a conflict.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jkrumbiegel apologies for the delay in getting back to you. Thanks for raising that, since he is not a co-author in this case it sounds like it could be okay. @logankilpatrick can you comment on this too?

**Comment by Kevin-Mattheus-Moerman** [comment]
After a discussion with the editorial board we decided that contribution does constitute a conflict of interest. We will therefore proceed to remove @logankilpatrick as a reviewer. 

@logankilpatrick thanks for offering to help. We'd love your help reviewing other packages for JOSS in the future if you are available.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon remove @logankilpatrick as reviewer

**Comment by whedon** [comment]
OK, @logankilpatrick is no longer a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@jkrumbiegel @gaelforget @fverdugo I will now initiate the review process.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3349.
