### ISSUE TITLE
[PRE REVIEW]: MiniSom, a minimalistic and Numpy based implementation of the Self Organizing Maps

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3227]
**Submitting author:** @JustGlowing (<a href="http://orcid.org/0000-0002-3939-2801">Giuseppe Vettigli</a>)
**Repository:** <a href="https://github.com/JustGlowing/minisom/" target ="_blank">https://github.com/JustGlowing/minisom/</a>
**Version:** 2.2.9
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JustGlowing. **Currently, there isn't an JOSS editor assigned** to your paper.

@JustGlowing if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (160.0 files/s, 241242.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                16              0          30470           1290
Python                           2            137            197            451
Markdown                         2             45              0            340
TeX                              1             16              0            148
HTML                             1             34              0             51
-------------------------------------------------------------------------------
SUM:                            22            232          30667           2280
-------------------------------------------------------------------------------


Statistical information for the repository '9f88b0eeaab390dbee3cdd5e' was
gathered on 2021/04/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adit Chawdhary                   2             3              3            0.23
Austin T                         1             3             12            0.57
Flavio Giobergia                 3            16              8            0.90
Giuseppe Vettigli                1             4              4            0.30
JustGlowing                     19           288            142           16.20
Mateusz Choinski                 1            22             11            1.24
Matt Poegel                      1             1              1            0.08
Peppe                            4           126            126            9.50
Phan Hai Phong                   3             5              5            0.38
Sumera Priyadarsini              1             1              1            0.08
Tómas Árni Jónasson              1            20              6            0.98
Velibor Zeli                     1             1              1            0.08
Wei Zhang                        5            59             51            4.14
christos.sourmpis                2             7             10            0.64
giu                             11           323             37           13.56
jay                              4            65             16            3.05
justglowing                     70           773            503           48.08

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adit Chawdhary                2           66.7          9.1                0.00
Austin T                      2           66.7         20.3                0.00
Flavio Giobergia             13           81.2          6.1               15.38
Giuseppe Vettigli             1           25.0         65.3              100.00
JustGlowing                 531          184.4         23.2                7.16
Mateusz Choinski             17           77.3         31.4                0.00
Matt Poegel                   1          100.0         58.4                0.00
Sumera Priyadarsini           1          100.0         11.5                0.00
Tómas Árni Jónasson           9           45.0         74.4               11.11
Wei Zhang                    22           37.3         16.4                9.09
christos.sourmpis             3           42.9         22.9                0.00
giu                          42           13.0          0.0               16.67
justglowing                 141           18.2         60.4               12.06
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03227/joss.03227/10.21105.joss.03227.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03227/joss.03227/10.21105.joss.03227.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@JustGlowing I've flagged this submission for editorial scope review. This is typical for submissions of this size. This scope review should take about a week.

**Comment by JustGlowing** [comment]
Thanks @Kevin-Mattheus-Moerman !

**Comment by arfon** [comment]
@JustGlowing - thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by JustGlowing** [comment]
Hi @arfon thanks for getting back to me. Could you be a little more specific? The link posted reports a list of scholarly efforts, which ones my submission doesn't meet?
