### ISSUE TITLE
[PRE REVIEW]: KVFinder-web: a web-based application for detecting and characterizing cavities in biomolecules

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3228]
**Submitting author:** @zgcarvalho (<a href="http://orcid.org/0000-0003-1041-0209">José Geraldo de Carvalho Pereira</a>)
**Repository:** <a href="https://github.com/LBC-LNBio/PyMOL-KVFinder-web-Tools" target ="_blank">https://github.com/LBC-LNBio/PyMOL-KVFinder-web-Tools</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @zgcarvalho. **Currently, there isn't an JOSS editor assigned** to your paper.

@zgcarvalho if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (94.7 files/s, 52867.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Qt                               1              1              0           2124
Python                           1            531            950           1548
Markdown                         6            105              0            237
TeX                              1              5              0             60
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            10            643            954           3987
-------------------------------------------------------------------------------


Statistical information for the repository 'c5342fb8f7a1f5cc621ddbbd' was
gathered on 2021/04/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
jvsguerra                        7          3243            214          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
jvsguerra                  3029           93.4          0.0               18.62
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1186/1471-2105-15-197 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.softx.2020.100606 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/jmr.984 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1111/cgf.13158 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03228/joss.03228/10.21105.joss.03228.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03228/joss.03228/10.21105.joss.03228.pdf) :page_facing_up: :point_left:

**Comment by jvsguerra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03228/joss.03228/10.21105.joss.03228.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03228/joss.03228/10.21105.joss.03228.pdf) :page_facing_up: :point_left:

**Comment by zgcarvalho** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you advise on how to edit the title which contains `detectingand` but should read `detecting and`? Thanks

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @richardjgowers as editor

**Comment by whedon** [comment]
@richardjgowers has been invited to edit this submission.

**Comment by richardjgowers** [comment]
@Kevin-Mattheus-Moerman this is a plugin for PyMOL.  PyMOL isn't free software (but is widely used freely under academic licenses), so I'm not going to be able to review this.  I'm not sure what the JOSS policy on free plugins for non-free software is.

**Comment by zgcarvalho** [comment]
Dear @richardjgowers and @Kevin-Mattheus-Moerman,  

 

PyMOL is a molecular visualization software originally created by Warren Lyford DeLano as an open source software. According to the original author, by 2009, almost a quarter of all published images of 3D protein structures in the scientific literature were made using PyMOL. However, when Dr. DeLano prematurely passed away ([https://www.nature.com/articles/nsmb1209-1202](https://www.nature.com/articles/nsmb1209-1202)), PyMOL was acquired by Schrondinger, Inc on the condition that it would remain available as an open source software (See January 8, 2010 announcement on [https://pymol.org/news.html?](https://pymol.org/news.html?); [https://en.wikipedia.org/wiki/PyMOL](https://en.wikipedia.org/wiki/PyMOL); [https://pymol.org/2/#opensource](https://pymol.org/2/#opensource)).  

 

According to Schrodinger’s open source PyMOL repository, PyMOL is licensed under BSD-like license ([https://github.com/schrodinger/pymol-open-source#license](https://github.com/schrodinger/pymol-open-source#license)). Consequently, in addition to commercial and academic licenses, open source versions of PyMOL are available in the repositories of the main Linux distributions ([https://pymol.org/index.php/Linux_Install](https://pymol.org/index.php/Linux_Install)). Additionally, this open source version can also be installed on Windows ([https://pymolwiki.org/index.php/Windows_Install](https://pymolwiki.org/index.php/Windows_Install)) and macOS ([https://pymolwiki.org/index.php/MAC_Install](https://pymolwiki.org/index.php/MAC_Install)), or independently of the OS using Anaconda. Thus, PyMOL remains one of the most used protein structure viewers. 

 

Although we developed user friendly PyMOL plugins for KVFinder-web, as well as parKVFinder, both softwares are open source initiatives and can be used independently of its PyMOL plugins. Perhaps in the future, plugins of other less used molecular visualization softwares could be developed for KVFinder-web service. Of note, KVFinder-web users through the open source PyMOL can take full advantage of the web service plugin, similarly to the ones using commercial/academic/non-profit licenses. 

 

Kind regards,

**Comment by kyleniemeyer** [comment]
Hello @zgcarvalho, thanks for your interest in JOSS and the explanation above.

Regardless of the question about the open-source nature (or otherwise) of PyMOL, the editorial board is going to review your submission to see whether it is in scope for JOSS at all. It appears that your submission is a web-based wrapper for a different software package, ParKVFinder, which was [previously published about in SoftwareX](https://www.sciencedirect.com/science/article/pii/S2352711020303198?via%3Dihub). 

ParKVFinder would itself certainly be in scope for JOSS as standalone research software, but I am not sure that KVFinder-web meets [our requirements](https://joss.readthedocs.io/en/latest/submitting.html#submitting-a-paper-to-joss). We will get back to you once the editorial board has had a chance to discuss.

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @zgcarvalho. Unfortunately the editorial board has determined this submission to be out of scope. The functionality of the tool is too narrow and a fair amount of the code is for UI logic. Overall, the amount of functionality contributed by this package is too small at the moment. We are willing to reconsider the package in the future if the scope is expanded. Thank you.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
