### ISSUE TITLE
[PRE REVIEW]: HARDy: Handling Arbitrary Recognition of Data in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3229]
**Submitting author:** @MariaPoliti (<a href="http://orcid.org/0000-0002-5815-3371">Maria Politi</a>)
**Repository:** <a href="https://github.com/EISy-as-Py/hardy" target ="_blank">https://github.com/EISy-as-Py/hardy</a>
**Version:** v1.0
**Editor:** @gkthiruvathukal
**Reviewers:** @andrewtarzia, @alberto-battistel
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @MariaPoliti. **Currently, there isn't an JOSS editor assigned** to your paper.

@MariaPoliti if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (406.6 files/s, 79897.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          30            846           1884           2657
Markdown                        10            185              0            559
YAML                            11            112            134            482
Jupyter Notebook                 4              0           5756            133
reStructuredText                 9             81             90            118
TeX                              1              7              0             68
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            67           1243           7872           4052
-------------------------------------------------------------------------------


Statistical information for the repository 'ac846e0a300aec2640405689' was
gathered on 2021/04/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Abdul Moeez                      1            51             62            0.14
David Hurt                      55          3545           1093            5.76
Maria Politi                    89         19618           4301           29.72
MariaPoliti                      7           222            425            0.80
Moeez                            2             2              2            0.00
amoeezuw                       132         26151          25008           63.57

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Abdul Moeez                  20           39.2         11.3               20.00
David Hurt                  970           27.4         11.0               15.77
Maria Politi               2725           13.9         10.0                7.08
amoeezuw                   1677            6.4          8.3               13.18
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03229/joss.03229/10.21105.joss.03229.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03229/joss.03229/10.21105.joss.03229.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1021/acs.chemmater.9b03043.s001 may be a valid DOI for title: Enabling catalyst discovery through machine learning and high-throughput experimentation
- 10.1109/dsaa.2015.7344858 may be a valid DOI for title: Deep feature synthesis: Towards automating data science endeavors
- 10.1107/s1600576720000552 may be a valid DOI for title: Classifying and analyzing small‐angle scattering data using weighted k nearest neighbors machine learning techniques

INVALID DOIs

- None
```

**Comment by MariaPoliti** [comment]
tacaswell
rmsare
yxoos

**Comment by MariaPoliti** [comment]
@whedon generate pdf

**Comment by MariaPoliti** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03229/joss.03229/10.21105.joss.03229.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03229/joss.03229/10.21105.joss.03229.pdf) :page_facing_up: :point_left:

**Comment by MariaPoliti** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/acs.chemmater.9b03043.s001 is OK
- 10.1002/aenm.201900555 is OK
- 10.1109/dsaa.2015.7344858 is OK
- 10.24963/ijcai.2017/352 is OK
- 10.1107/s1600576720000552 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@gkthiruvathukal @arokem @terrytangyuan this seems like your cup of tea to potentially handle as editor but I see you all have a lot on your plate at the moment. I'll add the `waitlisted` label for now until one of you becomes available.

**Comment by Kevin-Mattheus-Moerman** [comment]
@MariaPoliti as you can see I've added the `waitlisted` label as none of our editors, which appear most suitable for this submission, are currently available. Thanks for your patience.

**Comment by gkthiruvathukal** [comment]
@Kevin-Mattheus-Moerman I think I can take this one! It looks interesting!  I will go ahead and assign myself.

**Comment by gkthiruvathukal** [comment]
@whedon assign @gkthiruvathukal as editor

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
@MariaPoliti Can you please take a look at the list of people who can review for JOSS and suggest 2-4 of them?  This will greatly help me to get the review process started.

**Comment by MariaPoliti** [comment]
@gkthiruvathukal <https://github.com/gkthiruvathukal>,

Thank you so much for volunteering to be the editor for our submission.
Here is a list of reviewer who we think could be a good fit:

- yxoos,
- rmsare
- tacaswell

I am happy to provide other names if needed.
Best,
Maria & Moeez

**Comment by gkthiruvathukal** [comment]
@MariaPoliti  Thank you. I will get on this shortly!

**Comment by gkthiruvathukal** [comment]
@tacaswell, are you willing to contribute a review for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@rmsare, are you willing to contribute a review for this JOSS submission?

**Comment by tacaswell** [comment]
I will not have any time until June.

**Comment by rmsare** [comment]
Thanks for asking, George. I'm not able to review at this time.

**Comment by gkthiruvathukal** [comment]
@tacaswell That works for my timeframe. We're still in reduced service mode here. I will work with your schedule and try to keep it as low-stress as possible. Same for you, @rmsare, if you are willing to work on June/July timeframe.

Thanks for responding.

**Comment by gkthiruvathukal** [comment]
@tacaswell  Just following up. It's hard to believe we are approaching end of June, so I hope this works well with your availability. Are you available to help with this review?

**Comment by gkthiruvathukal** [comment]
@yxoos Would you be willing to contribute a review for this JOSS submission? I need two reviewers, so I am hoping you and @tacaswell can help me out!

**Comment by yxoos** [comment]
Sorry, I am so busy with work, cannot do it.
______________________
Amir Hassanzadeh

Ph.D. Candidate
Chester F. Carlson Center for Imaging Science
Rochester Institute of Technology, NY, 14623, USA
Email:     ***@***.***
Tel:         585-771-0680

**Comment by MariaPoliti** [comment]
@gkthiruvathukal In case you need additional reviewers, I have identified a few others:

* andrewtarzia
* magedhelmy1
* michaelberks
* alberto-battistel

I hope this helps!

**Comment by gkthiruvathukal** [comment]
@MariaPoliti Thank you! I will try others now.

**Comment by gkthiruvathukal** [comment]
@andrewtarzia Would you be willing to contribute a review for this JOSS submission? I need two reviewers, so I hope you can help us here.

**Comment by gkthiruvathukal** [comment]
@michaelberks Would you be willing to contribute a review for this JOSS submission? I need two reviewers, so I hope you can help us here.

**Comment by andrewtarzia** [comment]
@gkthiruvathukal I would be keen to review, but as this would be my first time and I am about to travel, I would not expect to have this done before September. Is this ok?

Andrew

**Comment by andrewtarzia** [comment]
Started to review this. Lacks usage introduction. If there is a compiled documentation, it is not accessible.

Added an issue for the example notebook not working: https://github.com/EISy-as-Py/hardy/issues/6

Interested in training timing: https://github.com/EISy-as-Py/hardy/issues/7

**Comment by gkthiruvathukal** [comment]
@whedon assign @andrewtarzia as reviewer

**Comment by alberto-battistel** [comment]
@gkthiruvathukal Yes, I am willing to help review this submission. It is not exactly my topic but I will do my best!

**Comment by gkthiruvathukal** [comment]
@whedon add @alberto-battistel as reviewer

**Comment by whedon** [comment]
OK, @alberto-battistel is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3829.
