### ISSUE TITLE
[PRE REVIEW]: Orangetool: Control Functions For Single-Board Computers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#323]
**Submitting author:** @sepandhaghighi (<a href="http://orcid.org/0000-0001-9450-2375">Sepand Haghighi</a>)
**Repository:** <a href="https://github.com/Moduland/Orangetool" target ="_blank">https://github.com/Moduland/Orangetool</a>
**Version:** v0.24
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @sepandhaghighi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sepandhaghighi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
Hello @sepandhaghighi, taking a look at your software and the paper, I'm afraid I don't quite see the research use for this software. JOSS only publishes articles about software with an explicit research application. 

In addition, your article does not conform to our standards, as it only includes a single (incomplete) sentence. JOSS articles need to include a statement of purpose, a short summary describing the functionality, and include references (where necessary).

**Comment by sepandhaghighi** [comment]
Hi @kyleniemeyer ;-) Orangetool is an easy to use linux based lib. This tool mostly use in IOT research and electronic programs that consist of single board computers.
But if you mean this software should directly analysis or generate some data about a research  , this software is not like this, it is a tool.

About article paper and references : 

- I added  reference in paper.bib file.
- In one line this software is "Orangetool: Control Functions For Single-Board Computers" and each of these functions mentioned in paper.md.

Best Regards
Sepand Haghighi

**Comment by labarba** [comment]
This is not research software.

This submission is not in-scope for JOSS.

**Comment by kyleniemeyer** [comment]
@sepandhaghighi To be within scope of JOSS, the *primary* purpose of the tool should be for scholarly research—meaning, is this something that would be used in the methodology of a research study / article?

General software tools that do not specifically support research are not in scope, and unfortunately it appears your submission falls in this category. This isn't a judgement on the quality or usefulness of your software, but JOSS can only consider submissions in its specific scope.

**Comment by sepandhaghighi** [comment]
@kyleniemeyer yeah with this definition Orangetool is not in-scope for JOSS. 
But I think this rule filter a large range of software's that work in high-level embedded system research!!
These tools really are not general and also directly-research!!

Best Regards
Sepand Haghighi

**Comment by kyleniemeyer** [comment]
@sepandhaghighi I appreciate your feedback, but JOSS does need a scope, otherwise it dilutes the purpose of the journal.

@arfon could you remove this submission?

**Comment by arfon** [comment]
> @arfon could you remove this submission?

Done.
