### ISSUE TITLE
[PRE REVIEW]: libfmp: A Python Package for Fundamentals of Music Processing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3230]
**Submitting author:** @fzalkow (<a href="http://orcid.org/0000-0003-1383-4541">Frank Zalkow</a>)
**Repository:** <a href="https://github.com/meinardmueller/libfmp" target ="_blank">https://github.com/meinardmueller/libfmp</a>
**Version:** v1.1.2
**Editor:** @arfon
**Reviewers:** @brunaw, @expectopatronum
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @fzalkow. **Currently, there isn't an JOSS editor assigned** to your paper.

@fzalkow if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.46 s (327.5 files/s, 127150.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            59           8851            174          21365
JavaScript                      14           2404           2467           9203
Python                          55           1876           3644           4629
SVG                              1              0              0           2671
CSS                              4            181             33            726
reStructuredText                13             47            181             66
DOS Batch                        1              8              1             26
Markdown                         2             18              0             22
make                             1              4              7              9
YAML                             1              0              2              6
-------------------------------------------------------------------------------
SUM:                           151          13389           6509          38723
-------------------------------------------------------------------------------


Statistical information for the repository 'ba3bd2eaf07f7e4cc3760e81' was
gathered on 2021/04/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Frank Zalkow                     4         16340           1813           65.16
Meinard Müller                   3          9700              4           34.84

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Frank Zalkow              16337          100.0          0.1               15.63
Meinard Müller             7886           81.3          0.1               10.22
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3230 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@fzalkow unfortunately none of our editors in this domain are currently available to handle this submission. As such I've add the `waitlisted` label. Once an appropriate editor becomes available we will assign them and resume the review of this submission.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@brunaw @expectopatronum – would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by brunaw** [comment]
@arfon yes, happy to review this new submission, the only issue is that I might only be able to start the review next week, would that be acceptable?

**Comment by arfon** [comment]
@whedon add @brunaw as reviewer

> @arfon yes, happy to review this new submission, the only issue is that I might only be able to start the review next week, would that be acceptable?

Absolutely, this is great! I'm hoping to have a second reviewer identified by then too (the actual review will take place in a second issue here on GitHub).

**Comment by whedon** [comment]
OK, @brunaw is now a reviewer

**Comment by expectopatronum** [comment]
Also happy to review! And I will also be able to start next week :)

**Comment by arfon** [comment]
@whedon add @expectopatronum as reviewer

> Also happy to review! And I will also be able to start next week :)

:zap: thanks so much @expectopatronum!

**Comment by whedon** [comment]
OK, @expectopatronum is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3326.

**Comment by arfon** [comment]
@brunaw, @expectopatronum – many thanks for agreeing to review here, see you over in #3326 where the actual review will take place.
