### ISSUE TITLE
[PRE REVIEW]: funsies: A minimalist, distributed and dynamic workflow engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3231]
**Submitting author:** @clavigne (<a href="http://orcid.org/0000-0003-2778-1866">Cyrille Lavigne</a>)
**Repository:** <a href="https://github.com/aspuru-guzik-group/funsies" target ="_blank">https://github.com/aspuru-guzik-group/funsies</a>
**Version:** v0.7.0
**Editor:** @diehlpk
**Reviewers:** @camillescott, @gflofst
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @clavigne. **Currently, there isn't an JOSS editor assigned** to your paper.

@clavigne if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (514.0 files/s, 103559.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            10            639              0           6867
Python                          57           1304           1324           4879
Markdown                         6             75              0            380
TeX                              1             27              0            294
YAML                             1              0              0             40
INI                              2              3              0             29
Bourne Shell                     1             11             23             14
Mako                             1              0              0              8
-------------------------------------------------------------------------------
SUM:                            79           2059           1347          12511
-------------------------------------------------------------------------------


Statistical information for the repository 'cbb507920ec4c86c92184295' was
gathered on 2021/04/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Cyrille Lavigne                317         23835          14394          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Cyrille Lavigne            7316           30.7          2.2               12.40
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03231/joss.03231/10.21105.joss.03231.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03231/joss.03231/10.21105.joss.03231.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1063/5.0006002 is OK
- 10.1063/5.0004835 is OK
- 10.1063/5.0007045 is OK
- 10.1063/5.0004997 is OK
- 10.1063/5.0005188 is OK
- 10.1063/1.5144261 is OK
- 10.1016/j.matt.2021.02.017 is OK
- 10.1145/1330017.1330019 is OK
- 10.1093/bioinformatics/bts480 is OK
- 10.12688/f1000research.29032.2 is OK
- 10.1145/2807591.2807623 is OK
- 10.1007/10968987_3 is OK
- 10.1007/978-3-319-63688-7_19 is OK

MISSING DOIs

- 10.26434/chemrxiv.13008500.v1 may be a valid DOI for title: Automatic discovery of chemical reactions using imposed activation
- 10.21276/ijre.2018.5.5.4 may be a valid DOI for title: MapReduce: Simplified Data Processing on Large Clusters

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite  @diehlpk as editor

**Comment by diehlpk** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by diehlpk** [comment]
@Kevin-Mattheus-Moerman Sure, I can take this paper.

**Comment by diehlpk** [comment]
@clavigne Could you please name some potential reviewers?

**Comment by diehlpk** [comment]
Hey @daissi @wjakethompson @vijaysm @gflofst @camillescott would you be interested to review this paper?

**Comment by camillescott** [comment]
Sure, this is in my wheelhouse.

**Comment by vijaysm** [comment]
If the others are busy, sure I can review it. I just have some deadlines near term, but can start in 2-3 weeks or so, if that works.

**Comment by diehlpk** [comment]
@whedon assign @camillescott as reviewer

**Comment by whedon** [comment]
OK, @camillescott is now a reviewer

**Comment by diehlpk** [comment]
@vijaysm I will wait for a few more days and if I could not find one additional reviewer, I will add you.

**Comment by clavigne** [comment]
sorry for the delay, Ive had a very busy week. 

I'd recommend [Johannes Koester](https://github.com/johanneskoester) or someone from his group, [Paolo Di Tommaso](https://github.com/pditommaso) and [Hilary J. Oliver](https://github.com/hjoliver). They are all working on similar codes (inspirations of sort). 

Thank you!

**Comment by whedon** [comment]
OK, @gflofst is now a reviewer

**Comment by diehlpk** [comment]
@wheon start review

**Comment by diehlpk** [comment]
> @vijaysm I will wait for a few more days and if I could not find one additional reviewer, I will add you.

@vijaysm Can you still review the paper? One reviewer disappeared and I could need some help here.

**Comment by vijaysm** [comment]
@diehlpk I'm swamped until end of next week with a conference. But can review this after. Let me know if that timeline would work.

**Comment by diehlpk** [comment]
> @diehlpk I'm swamped until end of next week with a conference. But can review this after. Let me know if that timeline would work.

Sure, that will work.

**Comment by diehlpk** [comment]
@whedon add @vijaysm as reviewer

**Comment by whedon** [comment]
OK, @vijaysm is now a reviewer

**Comment by clavigne** [comment]
@diehlpk Any news on this? Thanks.

**Comment by diehlpk** [comment]
@clavigne Not really @camillescott never responded, and I asked @vijaysm to replace her. We need to wait for his review to proceed.

**Comment by diehlpk** [comment]
@whedon remove @camillescott as reviewer

**Comment by whedon** [comment]
OK, @camillescott is no longer a reviewer

**Comment by diehlpk** [comment]
@vijaysm How is your review going?

**Comment by vijaysm** [comment]
Thanks for the reminder. I'll start the review this Friday and should be able to complete it within a week.
