### ISSUE TITLE
[PRE REVIEW]: RapidHRV: An Open-Source Toolbox for Extracting Heart Rate and Heart Rate Variability

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3233]
**Submitting author:** @peterakirk (<a href="http://orcid.org/0000-0003-0786-3039">Peter Kirk</a>)
**Repository:** <a href="https://github.com/peterakirk/rapidhrv" target ="_blank">https://github.com/peterakirk/rapidhrv</a>
**Version:** v0.1.5
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @peterakirk. **Currently, there isn't an JOSS editor assigned** to your paper.

@peterakirk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (288.2 files/s, 36221.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            100            102            345
TeX                              1             22              0            244
Markdown                         3             88              0            224
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                             9            210            102            819
-------------------------------------------------------------------------------


Statistical information for the repository 'bb757cf56b609d105c6c0144' was
gathered on 2021/04/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Peter Kirk                       3           829            287           85.00
peterakirk                       7           101             96           15.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Peter Kirk                  479           57.8          0.0               10.02
peterakirk                   68           67.3          0.4                2.94
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.neuroimage.2019.116072 is OK
- 10.2478/folmed-2018-0012 is OK
- 10.1109/ICNF.2017.7985971 is OK
- 10.3389/fmed.2020.597774 is OK
- 10.1016/j.trf.2019.09.015 is OK
- 10.1098/rstb.2019.0271 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1093/europace/eus341 is OK
- 10.1017/S003329171600060X is OK
- 10.1109/MCSE.2007.55 is OK
- 10.31234/osf.io/3ewgz is OK
- 10.3390/s19143079 is OK
- 10.5281/zenodo.4669042 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03233/joss.03233/10.21105.joss.03233.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03233/joss.03233/10.21105.joss.03233.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@peterakirk I've flagged this submission for editorial scope review. This is [typical for submissions of this size](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This scope review should take about a week.

**Comment by peterakirk** [comment]
> **Submitting author:** @peterakirk ([Peter Kirk](http://orcid.org/0000-0003-0786-3039))
> **Repository:** https://github.com/peterakirk/rapidhrv
> **Version:** v0.1.5
> **Editor:** Pending
> **Reviewer:** Pending
> **Managing EiC:** Kevin M. Moerman
> 
> **warning JOSS reduced service mode warning**
> 
> Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).
> 
> **Author instructions**
> 
> Thanks for submitting your paper to JOSS @peterakirk. **Currently, there isn't an JOSS editor assigned** to your paper.
> 
> @peterakirk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
> 
> **Editor instructions**
> 
> The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:
> 
> ```
> @whedon commands
> ```

Hi @Kevin-Mattheus-Moerman,

Thank you for processing the submission. We can suggest four potential reviewers:

Mohamed Elgendi (moe.elgendi@gmail.com): Expert in computer engineering, signal processing, cardiac arrhythmias, and developer of PPGSynth, the MATLAB toolbox used for the simulation of photoplethysmography cardiac data in our validation tests.

Daniel Quintana (daniel.quintana@psykologi.uio.no): Expert in psychiatry and heart rate variability. Open science advocate.

Torben Noto (TorbenNoto2024@u.northwestern.edu): Expert in psychophysiological monitoring and developer of BreathMetrics, a signal processing toolbox dedicated to peak detection in respiration.

Micah Allen (micah@aias.au.dk): Expert in brain-body interactions and developer of Systole, a software for the analysis of heart rate variability in pulse oximetry data.

Best,
Pete

**Comment by kthyng** [comment]
Hi @peterakirk and thank you for your submission. Unfortunately the editorial board has determined that it is too small in scope to pass our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) bar. If your software expands in size or is combined with another package, we would be happy to reconsider it in the future. Alternatively, there are a few [other ideas](https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages) for publishing your software to get a citation for people when using your software. Thank you.

**Comment by whedon** [comment]
Paper rejected.
