### ISSUE TITLE
[PRE REVIEW]: cvCovEst: Cross-validated covariance matrix estimator selection and evaluation in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3235]
**Submitting author:** @PhilBoileau (<a href="http://orcid.org/0000-0002-4850-2507">Philippe Boileau</a>)
**Repository:** <a href="https://github.com/PhilBoileau/cvCovEst" target ="_blank">https://github.com/PhilBoileau/cvCovEst</a>
**Version:** 3.5.0
**Editor:** @fboehm
**Reviewers:** @Marie-PerrotDockes, @yunanwu123
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @PhilBoileau. **Currently, there isn't an JOSS editor assigned** to your paper.

@PhilBoileau if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.39 s (241.3 files/s, 52991.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            50           2410            639           8732
R                               23            506           1726           4041
Markdown                         5            176              0            528
TeX                              2             40              0            478
CSS                              3             99             48            428
JavaScript                       4             64             34            266
Rmd                              2            118            289            102
YAML                             4             12              1             87
make                             1              8              0             17
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            95           3433           2738          14690
-------------------------------------------------------------------------------


Statistical information for the repository 'afa909e16e5f02693a7c8ef7' was
gathered on 2021/05/03.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03235/joss.03235/10.21105.joss.03235.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03235/joss.03235/10.21105.joss.03235.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/ectj.12061 is OK
- 10.21105/joss.00512 is OK
- 10.1214/08-AOS600 is OK
- 10.1214/009053607000000758 is OK
- 10.1214/09-AOS752 is OK
- 10.1093/jjfinec/nbaa007 is OK
- 10.2202/1544-6115.1175 is OK
- 10.1198/016214501753382273 is OK
- 10.1198/jasa.2009.0101 is OK
- 10.1214/17-AOS1588 is OK
- 10.1038/nn.4216 is OK

MISSING DOIs

- 10.1016/j.stamet.2005.02.003 may be a valid DOI for title: Asymptotics of Cross-Validated Risk Estimation in Estimator Selection and Performance Assessment
- 10.1016/j.stamet.2005.02.003 may be a valid DOI for title: Asymptotics of cross-validated risk estimation in estimator selection and performance assessment
- 10.1524/stnd.2006.24.3.351 may be a valid DOI for title: Oracle inequalities for multi-fold cross validation
- 10.1214/19-aos1921 may be a valid DOI for title: Analytical nonlinear shrinkage of large-dimensional covariance matrices
- 10.2139/ssrn.1977673 may be a valid DOI for title: Large covariance estimation by thresholding principal orthogonal complements

INVALID DOIs

- https://doi.org/10.1016/S0047-259X(03)00096-4 is INVALID because of 'https://doi.org/' prefix
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@PhilBoileau thanks for this submission. Can you work on checking/fixing those missing/invalid DOI's? :point_up: 
If you make changes to the paper you can update it here by calling:
`@whedon generate pdf`

**Comment by fboehm** [comment]
@whedon assign @fboehm as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@PhilBoileau - Do you have any suggestions for reviewers? These can be people who have reviewed for JOSS in the past or any scholars in your area. If you would leave their names and github usernames in the comment thread, I'll then reach out to them.

**Comment by PhilBoileau** [comment]
Will do, @Kevin-Mattheus-Moerman!

Thanks, @fboehm. I've looked for authors of relatively recent packages in our area. The following people may be interested in reviewing our submission:

+ Anestis Touloumis (email: A.Touloumis at brighton.ac.uk, GitHub: AnestisTouloumis)
+ Drew Schmidt (email: wrathematics at gmail.com, GitHub: wrathematics)
+ Marie Perrot-Dockès (email: marie.perrocks at gmail.com)

**Comment by fboehm** [comment]
:wave: @wrathematics & @AnestisTouloumis, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by PhilBoileau** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03235/joss.03235/10.21105.joss.03235.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03235/joss.03235/10.21105.joss.03235.pdf) :page_facing_up: :point_left:

**Comment by AnestisTouloumis** [comment]
> 👋 @wrathematics & @AnestisTouloumis, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Thank you for considering me as a reviewer for this paper. Although I am very interested in the topic of the paper, my current workload does not allow me to commit to review this article on time. Apologies for any inconvenience caused. 
Best Wishes,
Anestis

**Comment by fboehm** [comment]
No problem, @AnestisTouloumis - we appreciate the reply. Maybe we can work together on a future submission.

Thanks again!

**Comment by fboehm** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by fboehm** [comment]
:wave: @tianxzhu - would you be willing to review this submission for JOSS?

**Comment by fboehm** [comment]
:wave: @mdogucu - would you be willing to review this submission for JOSS?

**Comment by mdogucu** [comment]
I, unfortunately, would not be able to review at this point.

**Comment by fboehm** [comment]
No problem, @mdogucu . We appreciate the reply.

**Comment by fboehm** [comment]
@whedon assign @Marie-PerrotDockes as reviewer

**Comment by whedon** [comment]
OK, @Marie-PerrotDockes is now a reviewer
