### ISSUE TITLE
[PRE REVIEW]: radioactivedecay: A Python package for radioactive decay calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3239]
**Submitting author:** @alexmalins (<a href="http://orcid.org/0000-0003-1922-4496">Alex Malins</a>)
**Repository:** <a href="https://github.com/alexmalins/radioactivedecay/" target ="_blank">https://github.com/alexmalins/radioactivedecay/</a>
**Version:** v0.3.2
**Editor:** @kellyrowland
**Reviewers:** @bjodah, @munkm
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @alexmalins. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @katyhuff.

@alexmalins if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3239 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (182.5 files/s, 60988.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          14            606           1215           2037
Jupyter Notebook                 6              0           6277           1038
Markdown                         5            132              0            419
reStructuredText                11            219            335            367
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            38            969           7835           3896
-------------------------------------------------------------------------------


Statistical information for the repository 'd3e5236ac758525d7f5615ef' was
gathered on 2021/05/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex Malins                     40          6015           2165          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alex Malins                3859           64.2          4.4                8.50
```

**Comment by kthyng** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03239/joss.03239/10.21105.joss.03239.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03239/joss.03239/10.21105.joss.03239.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@kellyrowland would you be able to take this submission on?

**Comment by kthyng** [comment]
@whedon invite @kellyrowland as editor

**Comment by whedon** [comment]
@kellyrowland has been invited to edit this submission.

**Comment by kellyrowland** [comment]
Sure thing!

@whedon assign @kellyrowland as editor

**Comment by kellyrowland** [comment]
@alexmalins do you have any recommended reviewers for this paper?

**Comment by kellyrowland** [comment]
@whedon assign @kellyrowland as editor

**Comment by whedon** [comment]
OK, the editor is @kellyrowland

**Comment by alexmalins** [comment]
Thanks @kellyrowland & @kthyng /

I suggest Anthony Scopatz (@scopatz) & Björn Dahlgren (@bjodah) as potential reviewers.

**Comment by kellyrowland** [comment]
Great, thanks!

**Comment by kellyrowland** [comment]
@whedon add @bjodah as reviewer

**Comment by whedon** [comment]
OK, @bjodah is now a reviewer

**Comment by kellyrowland** [comment]
Hi @munkm 👋 - would you be available and willing to review this paper for JOSS? ⚛️

**Comment by munkm** [comment]
Hi! Yes, I would be available to review but not until after mid-June if that's all right!

**Comment by kellyrowland** [comment]
Thanks! That works for me if that's okay with you, @alexmalins.

**Comment by alexmalins** [comment]
That's fine with me! Thank you all for your consideration.

**Comment by kellyrowland** [comment]
Great, thanks!

**Comment by kellyrowland** [comment]
@whedon add @munkm as reviewer

**Comment by kellyrowland** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3318.

**Comment by bjodah** [comment]
@kellyrowland sorry, I might have been a bit hasty in accepting the role as reviewer here. I'm afraid I'm swamped now and for quite a while. Sorry @alexmalins (I glanced over your package it looks really nice)!

**Comment by kellyrowland** [comment]
No problem @bjodah , thanks for the heads up! I will unassign your reviewer status over in #3318 .

**Comment by alexmalins** [comment]
@bjodah No problem! Thanks again for your consideration.
