### ISSUE TITLE
[PRE REVIEW]: rtimicropem: an R package supporting the analysis of RTI MicroPEM output files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#324]
**Submitting author:** @maelle (<a href="http://orcid.org/0000-0002-2815-0399">Maëlle Salmon</a>)
**Repository:** <a href="https://github.com/ropensci/rtimicropem" target ="_blank">https://github.com/ropensci/rtimicropem</a>
**Version:** v1.3
**Editor:** @arfon
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @maelle. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@maelle if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by maelle** [comment]
Link to rOpenSci review of `rtimicropem` https://github.com/ropensci/onboarding/issues/126

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/333. Feel free to close this issue now!
