### ISSUE TITLE
[PRE REVIEW]: AuDoLab: Automatic document labelling and classfication for extremely unbalanced data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3240]
**Submitting author:** @ArneTillmann (<a href="http://orcid.org/0000-0002-2761-4518">Arne Matthias Tillmann</a>)
**Repository:** <a href="https://github.com/ArneTillmann/AuDoLab" target ="_blank">https://github.com/ArneTillmann/AuDoLab</a>
**Version:** v0.1.15
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ArneTillmann. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @trallard.

@ArneTillmann if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3240 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Christoph Weisser, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (281.8 files/s, 16740.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          14            200            444            520
reStructuredText                16            121             68            215
HTML                             2             15              0            134
TeX                              1             14              0            114
PowerShell                       1             49            245            104
make                             2             24              6             75
DOS Batch                        3             23              2             65
Markdown                         1             15              0             58
INI                              1              4              3             17
YAML                             2              1              2             16
-------------------------------------------------------------------------------
SUM:                            43            466            770           1318
-------------------------------------------------------------------------------


Statistical information for the repository 'a82fa803f12a3424b81334aa' was
gathered on 2021/05/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
AFThielmann                     13           444            295           11.44
Anton Thielmann                  2             1              1            0.03
ArneTillmann                   132          3391           2324           88.49
tkneib                           1             1              1            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
AFThielmann                 146           32.9          0.4               13.70
ArneTillmann               1018           30.0          0.5               19.74
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1162/jmlr.2003.3.4-5.993 is OK
- 10.1080/02664763.2021.1919063 is OK
- 10.1162/089976601750264965 is OK
- 10.3115/v1/W14-3110 is OK
- 10.1162/15324430260185574 is OK
- 10.21105/joss.02507 is OK
- 10.17875/gup2020-1338 is OK
- 10.13140/2.1.2393.1847 is OK
- 10.17875/gup2020-1338 is OK

MISSING DOIs

- 10.5260/cca.199178 may be a valid DOI for title: IEEE Xplore Digital Library

INVALID DOIs

- 10.5555/1953048.2078195 is INVALID
```

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @ArneTillmann and thanks for your submission. I triggered a scope query of your submission in which the editorial board will vote as to whether this submission is in scope or not. I did this because of the small size of the submission — this doesn't automatically mean that it won't be reviewed, but that is what we will vote to decide. This will take 1-2 weeks. Thanks.

**Comment by ArneTillmann** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03240/joss.03240/10.21105.joss.03240.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03240/joss.03240/10.21105.joss.03240.pdf) :page_facing_up: :point_left:

**Comment by ArneTillmann** [comment]
Hi @kthyng thank you very much for your quick feedback! Please note that the size of the python code might appear relatively small, however we tried to write the code as efficient as possible and hence the length might seem quite short. In particular, the abstract scraping uses a new approach that is written in Java Script and requires only little python code. We believe that our package is quite innovative and would welcome a full review very much.
Thank you! We are looking forward to hear from you.

**Comment by danielskatz** [comment]
👋 @ArneTillmann - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by ArneTillmann** [comment]
Dear @danielskatz and @kthyng, 
thank you for you feedback. 
The version of the package that we submitted is a relativly early version. We would now extend the package substantially and resubmit to JOSS at a later stage, if this is possible and sensible?

**Comment by danielskatz** [comment]
yes
