### ISSUE TITLE
[PRE REVIEW]: ImSwitch: Generalizing microscope control in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3241]
**Submitting author:** @kasasxav (<a href="http://orcid.org/0000-0002-9583-9022">Xavier Casas Moreno</a>)
**Repository:** <a href="https://github.com/kasasxav/ImSwitch" target ="_blank">https://github.com/kasasxav/ImSwitch</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @MakerTobey, @uellue, @beniroquai, @untzag
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kasasxav. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jni.

@kasasxav if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.65 s (304.4 files/s, 32944.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         184           3613           4636          11711
JSON                             2              0              0            487
reStructuredText                 9            271             89            451
TeX                              1              2              0            131
Markdown                         2             27              0             73
YAML                             1              6              2             39
-------------------------------------------------------------------------------
SUM:                           199           3919           4727          12892
-------------------------------------------------------------------------------


Statistical information for the repository '48e379ccc23a90cc93a49fda' was
gathered on 2021/05/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andreas   Bodén                  8           835            304            1.53
Testalab                         2             2              2            0.01
jonatanalvelid                  42          7797           3312           14.88
stafak                         218         29240          18074           63.39
xaviercm94                     110         10847           4224           20.19

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andreas   Bodén              68            8.1         12.6               16.18
Jonatan Alvelid            2045          100.0          3.4               14.03
jonatanalvelid              420            5.4          0.8               15.24
stafak                    14734           50.4          2.2               14.14
xaviercm94                 2694           24.8          7.6               61.95
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03241/joss.03241/10.21105.joss.03241.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03241/joss.03241/10.21105.joss.03241.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @kasasxav and thanks for your submission. We have a backlog of submission right now and our editors are overburdened, so I have added this submission to the waitlist. Thank you for your patience.

**Comment by MakerTobey** [comment]
This looks like a very exciting tool. I'm neither a classical microscopy person nor a great Python programmer, but this software looks very professional to me. It does not only (at least at brief view) look like it has all the main features of a professional Nikon etc. platform, but it also has very exciting and advances hardware control interfaces to control lasers, fast photon detector modules, spatial light modulators and other units that are needed for advances microscopy (confocal, super resolution, scanning, etc.). I will definitely keep this in mind for my own future projects. Also: Thank you for using Phython, which is FOSS and in my eyes the best scientific platform to interface with custom hardware. I have not tried to execute the software (yet).

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @MakerTobey as reviewer

**Comment by whedon** [comment]
OK, @MakerTobey is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@beniroquai @nicost @henrypinkard @untzag @nanthony21 @uellue would you be interested in reviewing this work for [the Journal of Open Source Software (JOSS)](https://joss.theoj.org/about): _ImSwitch: Generalizing microscope control in Python_

The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) focuses on [the software](https://github.com/kasasxav/ImSwitch) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.03241/joss.03241/10.21105.joss.03241.pdf). 

If you are interested in helping you can comment here. This here is a pre-review issue. The review process takes place in a review issue which I'll initiate when sufficient reviewers are recruited. Here is an example of a completed review issue: https://github.com/openjournals/joss-reviews/issues/2006, where you can see we have a streamlined GitHub based review process featuring a set of tick-boxes to guide the reviewers through the process. 

Let me know if you have any questions. 

Thanks!

**Comment by uellue** [comment]
@Kevin-Mattheus-Moerman it would be my pleasure to review the software and paper!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @uellue as reviewer

**Comment by whedon** [comment]
OK, @uellue is now a reviewer

**Comment by beniroquai** [comment]
Thanks for inviting me. I'm curious to go through this review process as I have never heard about it before. The software seems very nice! If possible I would also like to give it a try. No problem if one reviewer is already enough! :-)

**Comment by untzag** [comment]
@Kevin-Mattheus-Moerman I'd be happy to review if desired

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @beniroquai as reviewer

**Comment by whedon** [comment]
OK, @beniroquai is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @untzag as reviewer

**Comment by whedon** [comment]
OK, @untzag is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3394.
