### ISSUE TITLE
[PRE REVIEW]: **raddo**: A Python Package for RADOLAN Weather Radar Data Provision

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3242]
**Submitting author:** @RaT0M (<a href="http://orcid.org/0000-0001-5322-4540">Thomas Ramsauer</a>)
**Repository:** <a href="https://github.com/RaT0M/raddo" target ="_blank">https://github.com/RaT0M/raddo</a>
**Version:** 0.6.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @RaT0M. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@RaT0M if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (194.5 files/s, 22984.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           8            287            300           1167
reStructuredText                 8            159             94            274
Markdown                         3            106              0            272
TeX                              1             12              0            172
make                             1             31              6            156
Bourne Shell                     3              9             21             46
YAML                             1              1             12             28
INI                              1              2              0             21
Dockerfile                       1              4              3              8
-------------------------------------------------------------------------------
SUM:                            27            611            436           2144
-------------------------------------------------------------------------------


Statistical information for the repository 'fae81e90e671f5b98e7fc95d' was
gathered on 2021/05/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Thomas Ramsauer                 68          2348            590          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Thomas Ramsauer            1754           74.7          6.5               13.91
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03242/joss.03242/10.21105.joss.03242.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03242/joss.03242/10.21105.joss.03242.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @RaT0M and thanks for your submission. I have triggered a scope query due to the relatively small size of your submission. The editorial board will take a look at it and decide if it is in scope. This process should take 1-2 weeks. Thanks for your patience!

**Comment by kyleniemeyer** [comment]
Hello @RaT0M, thanks for your patience. The JOSS editorial board has reviewed your submission, and found that it does not meet our [substantial scholarly effort criterion](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
