### ISSUE TITLE
[PRE REVIEW]: ConTEXT Explorer: a web-based text analysis tool for exploring and visualizing concepts across time

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3244]
**Submitting author:** @alicia-ziying-yang (<a href="http://orcid.org/0000-0001-7705-3280">Ziying Yang</a>)
**Repository:** <a href="https://github.com/alicia-ziying-yang/conTEXT-explorer" target ="_blank">https://github.com/alicia-ziying-yang/conTEXT-explorer</a>
**Version:** v1.0
**Editor:** @faroit
**Reviewers:** @sara-02, @baileythegreen
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @alicia-ziying-yang. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kakiac.

@alicia-ziying-yang if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (58.2 files/s, 35454.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            453             90           2588
CSS                              3            441            189           2047
Markdown                         2             64              0            108
TeX                              1             14              0             96
-------------------------------------------------------------------------------
SUM:                            10            972            279           4839
-------------------------------------------------------------------------------


Statistical information for the repository '48aa86579650046d44771ce3' was
gathered on 2021/05/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ziying Alicia Yang               1             2              2            0.13
alicia-ziying-yang               5          3157             26           99.87

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
alicia-ziying-yang         3131           99.2          0.0                2.91
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03244/joss.03244/10.21105.joss.03244.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03244/joss.03244/10.21105.joss.03244.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.1212303 is OK
- 10.1561/1500000019 is OK

MISSING DOIs

- 10.1007/978-1-4471-2099-5_30 may be a valid DOI for title: The Effect of Adding Relevance Information in a Relevance Feedback Environment

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @alicia-ziying-yang and thanks for your submission! I've added the "waitlisted" label because the editors in your area are currently overburdened and we have a backlog of submissions. Thank you for your patience.

**Comment by sara-02** [comment]
Hey @kthyng @alicia-ziying-yang I would be happy to review this when it gets off the waitlist. :)

**Comment by kthyng** [comment]
@sara-02 That's awesome! Thank you for your offer! Whoever takes this submission on as editor will see these notes and may reach out to you.

**Comment by arfon** [comment]
@whedon invite @faroit as editor

:wave: @faroit – how about this as a second paper to edit? Given your expertise in web technologies it feels like it could be a good fit?

**Comment by whedon** [comment]
@faroit has been invited to edit this submission.

**Comment by faroit** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @faroit

**Comment by faroit** [comment]
👋  Hi @alicia-ziying-yang, thanks for your submission to JOSS! I will be serving as the editor for this. We'll use this issue to identify reviewers and resolve technical issues. Since @sara-02 has already volunteered (👏) for review we are looking for only one additional reviewer. Based on the list of people that have agreed to review for JOSS I found the following three potential reviewers to be a good fit:  

- @ baileythegreen
- @ jaeyk
- @ cmaimone

@alicia-ziying-yang, I am also interested in your input on these reviewers, so any suggestions you have are also welcome, especially w.r.t. the JOSS [COI policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy). Please only mention potential reviewers with a space between the @ and their handle (so you would refer to me as "@ faroit").

**Comment by alicia-ziying-yang** [comment]
Hi @faroit, thanks for asking:D
I am glad if @ baileythegreen could be the reviewer. 
Cheers

**Comment by faroit** [comment]
@sara-02 @baileythegreen - would you be willing to review this submission?

**Comment by baileythegreen** [comment]
Hi @faroit, yes, I'd be happy to review it.

**Comment by sara-02** [comment]
@faroit Happy to help.

**Comment by faroit** [comment]
@whedon assign @sara-02 as reviewer

**Comment by whedon** [comment]
OK, @sara-02 is now a reviewer

**Comment by faroit** [comment]
@whedon add @baileythegreen as reviewer

**Comment by whedon** [comment]
OK, @baileythegreen is now a reviewer

**Comment by faroit** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.1212303 is OK
- 10.1561/1500000019 is OK

MISSING DOIs

- 10.1007/978-1-4471-2099-5_30 may be a valid DOI for title: The Effect of Adding Relevance Information in a Relevance Feedback Environment

INVALID DOIs

- None
```

**Comment by faroit** [comment]
@alicia-ziying-yang can you please fix the missing DOI before we can start the review process?

**Comment by alicia-ziying-yang** [comment]
Hi, I have fixed the suggested DOI. Please check again.

**Comment by faroit** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.1212303 is OK
- 10.1561/1500000019 is OK

MISSING DOIs

- 10.1007/978-1-4471-2099-5_30 may be a valid DOI for title: The Effect of Adding Relevance Information in a Relevance Feedback Environment

INVALID DOIs

- None
```

**Comment by alicia-ziying-yang** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.1212303 is OK
- 10.1561/1500000019 is OK
- 10.1007/978-1-4471-2099-5_30 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by faroit** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03244/joss.03244/10.21105.joss.03244.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03244/joss.03244/10.21105.joss.03244.pdf) :page_facing_up: :point_left:

**Comment by faroit** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (231.5 files/s, 141012.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            453             90           2588
CSS                              3            441            189           2047
Markdown                         2             64              0            109
TeX                              1             14              0             97
-------------------------------------------------------------------------------
SUM:                            10            972            279           4841
-------------------------------------------------------------------------------


Statistical information for the repository 'b1fc57a82b1e665f8cab75f3' was
gathered on 2021/06/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ziying Alicia Yang               1             2              2            0.13
alicia-ziying-yang               5          3157             26           99.87

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
alicia-ziying-yang         3131           99.2          0.0                2.91
```

**Comment by faroit** [comment]
@alicia-ziying-yang

> Hi, I have fixed the suggested DOI. Please check again.

thanks, looks good. 

Can you also modify the markdown section headers so that they match the [JOSS template](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)? E.g. `# 2. Statement of Need` -> `# Statement of need`... etc.

**Comment by alicia-ziying-yang** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (237.6 files/s, 144730.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            453             90           2588
CSS                              3            441            189           2047
Markdown                         2             64              0            109
TeX                              1             14              0             97
-------------------------------------------------------------------------------
SUM:                            10            972            279           4841
-------------------------------------------------------------------------------


Statistical information for the repository 'dfb92ea82c69c579d46faaa6' was
gathered on 2021/06/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ziying Alicia Yang               1             2              2            0.13
alicia-ziying-yang               5          3157             26           99.87

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
alicia-ziying-yang         3131           99.2          0.0                2.91
```

**Comment by alicia-ziying-yang** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (236.9 files/s, 144315.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            453             90           2588
CSS                              3            441            189           2047
Markdown                         2             64              0            109
TeX                              1             14              0             97
-------------------------------------------------------------------------------
SUM:                            10            972            279           4841
-------------------------------------------------------------------------------


Statistical information for the repository '9051a52ddd02c536e62c8ec5' was
gathered on 2021/06/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ziying Alicia Yang               1             2              2            0.13
alicia-ziying-yang               5          3157             26           99.87

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
alicia-ziying-yang         3131           99.2          0.0                2.91
```

**Comment by alicia-ziying-yang** [comment]
> @alicia-ziying-yang
> 
> > Hi, I have fixed the suggested DOI. Please check again.
> 
> thanks, looks good.
> 
> Can you also modify the markdown section headers so that they match the [JOSS template](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)? E.g. `# 2. Statement of Need` -> `# Statement of need`... etc.

fixed.

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (189.2 files/s, 115265.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            453             90           2588
CSS                              3            441            189           2047
Markdown                         2             64              0            109
TeX                              1             14              0             97
-------------------------------------------------------------------------------
SUM:                            10            972            279           4841
-------------------------------------------------------------------------------


Statistical information for the repository '1915b23812b3badd5e6cac88' was
gathered on 2021/06/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ziying Alicia Yang               1             2              2            0.13
alicia-ziying-yang               5          3157             26           99.87

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
alicia-ziying-yang         3131           99.2          0.0                2.91
```

**Comment by faroit** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03244/joss.03244/10.21105.joss.03244.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03244/joss.03244/10.21105.joss.03244.pdf) :page_facing_up: :point_left:

**Comment by faroit** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3347.
