### ISSUE TITLE
[PRE REVIEW]: Lerche: Generating data file processors in Julia from EBNF grammars

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3245]
**Submitting author:** @jamesrhester (<a href="http://orcid.org/0000-0002-2004-8672">James Hester</a>)
**Repository:** <a href="https://github.com/jamesrhester/Lerche.jl" target ="_blank">https://github.com/jamesrhester/Lerche.jl</a>
**Version:** 0.4.3
**Editor:** @sbenthall
**Reviewers:** @ziotom78, @eschnett
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jamesrhester. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @pibion.

@jamesrhester if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.31 s (107.9 files/s, 21353.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           23            832            563           4365
Markdown                         4            168              0            477
YAML                             2              2              6             65
TOML                             4             12              1             40
-------------------------------------------------------------------------------
SUM:                            33           1014            570           4947
-------------------------------------------------------------------------------


Statistical information for the repository 'bfd6b133fcbb716c10044481' was
gathered on 2021/05/04.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3245 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon generate pdf from joss_paper

**Comment by whedon** [comment]
PDF failed to compile for issue #3245 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by jamesrhester** [comment]
Can confirm that https://whedon.theoj.org/ compiles the paper from this repository if `joss_paper` is provided as the branch. Perhaps the version number causes a problem?

**Comment by kthyng** [comment]
@whedon generate pdf from joss_paper

**Comment by whedon** [comment]
PDF failed to compile for issue #3245 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@openjournals/dev The JOSS paper is located by itself at branch `joss_paper`, but I can't compile it from there. Any ideas?

**Comment by kthyng** [comment]
Hi @jamesrhester and thanks for your submission. I have added this to our backlog of submissions due to the relevant editors being overburdened at the moment. Thank you for your patience.

**Comment by arfon** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by arfon** [comment]
> @openjournals/dev The JOSS paper is located by itself at branch joss_paper, but I can't compile it from there. Any ideas?

@kthyng - looks like you didn't quite have the syntax of the command correct :-)

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03245/joss.03245/10.21105.joss.03245.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03245/joss.03245/10.21105.joss.03245.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
> @kthyng - looks like you didn't quite have the syntax of the command correct :-)

Gah! I think I have these errors all over today. Thanks.

**Comment by kthyng** [comment]
@sbenthall could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by sbenthall** [comment]
Yes, I can edit this one. Sign me up!

**Comment by danielskatz** [comment]
Hi @sbenthall  - the best option at this point is for you to sign yourself up, by doing what I am going to do below

**Comment by danielskatz** [comment]
@whedon assign @sbenthall as editor

you can do this yourself, or you can also do `@whedon assign me as editor`

**Comment by whedon** [comment]
OK, the editor is @sbenthall

**Comment by sbenthall** [comment]
@ziotom78 @gcdeshpande would you be able to review this work?

**Comment by ziotom78** [comment]
Hi @sbenthall, I would love to do it!

**Comment by sbenthall** [comment]
@whedon assign @ziotom78 as reviewer

**Comment by whedon** [comment]
OK, @ziotom78 is now a reviewer

**Comment by sbenthall** [comment]
Thank you @ziotom78 !

**Comment by sbenthall** [comment]
@r-barnes would you be able to review this work?

**Comment by sbenthall** [comment]
@trallard would you be able to review this package?

**Comment by sbenthall** [comment]
@eschnett would you be able to review this package?

**Comment by eschnett** [comment]
@sbenthall I am.

**Comment by sbenthall** [comment]
Thank you @eschnett

**Comment by sbenthall** [comment]
@whedon add @eschnett as reviewer

**Comment by sbenthall** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3497.
