### ISSUE TITLE
[PRE REVIEW]: Computer-Aided Generation of N-shift RWS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3246]
**Submitting author:** @benjaminbolling (<a href="http://orcid.org/0000-0002-6650-5365">Benjamin Edward Bolling</a>)
**Repository:** <a href="https://github.com/benjaminbolling/RSW" target ="_blank">https://github.com/benjaminbolling/RSW</a>
**Version:** v.1.0.0
**Editor:** @majensen
**Reviewers:** @magedhelmy1, @ShantanuDash
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @benjaminbolling. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @majensen.

@benjaminbolling if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (110.1 files/s, 24990.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5             56            124           1806
Markdown                         3             71              0            182
TeX                              1              2              0             21
YAML                             1              0              0              8
-------------------------------------------------------------------------------
SUM:                            10            129            124           2017
-------------------------------------------------------------------------------


Statistical information for the repository '2867211bb21b5e6d87ca9d72' was
gathered on 2021/05/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
benjaminbolling                 32          4373           2387          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
benjaminbolling            1986           45.4          3.6                6.24
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/s0166-218x(01)00258-x may be a valid DOI for title: Efficient generation of rotating workforce schedules
- 10.1201/9781584889304-33 may be a valid DOI for title: Python Language Reference

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by majensen** [comment]
@kthyng I am happy to handle this submission when you are ready.

**Comment by kthyng** [comment]
woohoo! Thanks @majensen!

**Comment by kthyng** [comment]
@whedon assign @majensen as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by benjaminbolling** [comment]
@majensen Thank you!

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3246 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Benjamin Bolling, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3246 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Benjamin Bolling, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3246 with the following error: 
```
 Error reading bibliography file docs/paper.bib:
(line 8, column 3):
unexpected "d"
expecting space, ",", white space or "}"
Looks like we failed to compile the PDF

```

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by benjaminbolling** [comment]
Hi all, sorry for the spamming...

**Comment by benjaminbolling** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03246/joss.03246/10.21105.joss.03246.pdf) :page_facing_up: :point_left:

**Comment by majensen** [comment]
@benjaminbolling sorry I'm dragging my feet here - lots of personal activity going on. I'm thinking about reviewers, but if you have any suggestions please let me know - thanks!

**Comment by majensen** [comment]
@benjaminbolling again apologies - I will get on this this weekend. Many competing priorities this last month or so.

**Comment by benjaminbolling** [comment]
@majensen thank you, and no worries and no rush - take your time. I understand there can be many things that compete priority-wise.

**Comment by majensen** [comment]
@amoeba would you have time/interest in review [this submission](#3246) for JOSS? Appreciate the consideration as always.

**Comment by amoeba** [comment]
Hi @majensen, I'm sorry but I can't review this at the moment.

**Comment by benjaminbolling** [comment]
@majensen thank you for looking for a reviewer, and thanks anyways @amoeba. I will sit down this evening as well to look for a possible reviewer for the package.

**Comment by majensen** [comment]
@sap218 would you be willing to review [this work](#3246) for JOSS? I would appreciate your expertise here.
Thanks for the consideration! --@majensen

**Comment by benjaminbolling** [comment]
My initial suggestions after looking through the editorial board would be one of following:
- @melissawm (applied mathematician and an editor for Python scripts)
- @lorenanicole (data engineer and data scientist, a champion of FATE and an editor for Python scripts)
- @jbytecode (Author of three books on R programming and genetic algorithms, and developer and maintainer of many open source projects in several languages including R, Julia, Python, and Java)

**Comment by danielskatz** [comment]
@benjaminbolling  - please don't suggest editors as reviewers; they already have enough work 😄 

As noted in the first comment in this issue, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

And also, as mentioned in that comment, please suggest people without tagging them with an @

**Comment by benjaminbolling** [comment]
Oho, I'm so sorry editors! Somehow I missed this list... thank you @danielskatz !

**Comment by benjaminbolling** [comment]
My updated list of suggestions, starting from the bottom of the list:
- @magedhelmy1
- @shantanudash
- @jGaboardi
- @FranciscoReveriano

**Comment by majensen** [comment]
@magedhelmy1, @ShantuDash - are you both willing to review [this work](#3246) for [JOSS](https://joss.theoj.org)? Thanks for your consideration1

**Comment by ShantanuDash** [comment]
@majensen  I am willing to review this. Do you have any particular guidelines for reviewing? And I am new to reviewing on GitHub workflow.

**Comment by magedhelmy1** [comment]
> @magedhelmy1, @shantudash - are you both willing to review [this work](#3246) for [JOSS](https://joss.theoj.org)? Thanks for your consideration1

Yes, I am willing to review. Similiar to ShatanuDash, please share the reviewer guidelines :)

**Comment by majensen** [comment]
@magedhelmy1 @ShantanuDash Thanks very much for the interest. Please have a look at the process here https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and here https://joss.readthedocs.io/en/latest/review_criteria.html - if you have any questions just ask here. If you change your mind, that is ok!

**Comment by majensen** [comment]
@whedon assign @magedhelmy1 as reviewer

**Comment by whedon** [comment]
OK, @magedhelmy1 is now a reviewer

**Comment by majensen** [comment]
@whedon add @ShantanuDash as reviewer

**Comment by whedon** [comment]
OK, @ShantanuDash is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3431.

**Comment by majensen** [comment]
@benjaminbolling @magedhelmy1 @ShantanuDash - please join the discussion in the official review issue at #3431. Don't hesitate to ask any questions you may have about the process; really appreciate your participation.
