### ISSUE TITLE
[REVIEW]: OpenOmics: A bioinformatics API to integrate multi-omics datasets and interface with public databases

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3249]
**Submitting author:** @JonnyTran (<a href="http://orcid.org/0000-0002-2575-9633">Nhat Tran</a>)
**Repository:** <a href="https://github.com/BioMeCIS-Lab/OpenOmics" target ="_blank">https://github.com/BioMeCIS-Lab/OpenOmics</a>
**Version:** v0.8.8
**Editor:** @arfon
**Reviewer:** @arfon
**Archive:** <a href="https://doi.org/10.5281/zenodo.4731011" target="_blank">10.5281/zenodo.4731011</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/aca43e3c2989a803b514faef72dd3294/status.svg)](https://joss.theoj.org/papers/aca43e3c2989a803b514faef72dd3294)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/aca43e3c2989a803b514faef72dd3294"><img src="https://joss.theoj.org/papers/aca43e3c2989a803b514faef72dd3294/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/aca43e3c2989a803b514faef72dd3294/status.svg)](https://joss.theoj.org/papers/aca43e3c2989a803b514faef72dd3294)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/BioMeCIS-Lab/OpenOmics" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@arfon, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/BioMeCIS-Lab/OpenOmics">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@JonnyTran) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by arfon** [comment]
Fast-tracking this submission because it has already been reviewed in https://github.com/pyOpenSci/software-review/issues/31#issuecomment-832451199

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.86 s (156.7 files/s, 13359.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          38           1044           1782           3615
Markdown                        21            292              0           1284
CSS                              5            197             87            982
TeX                              1             59              0            478
reStructuredText                61            426            704            127
YAML                             2             12             16             87
make                             2             24              6             78
XML                              2              0              0             71
DOS Batch                        1              8              1             27
TOML                             1              6              0             14
-------------------------------------------------------------------------------
SUM:                           134           2068           2596           6763
-------------------------------------------------------------------------------


Statistical information for the repository '36d4405885fdd6e8f1615832' was
gathered on 2021/05/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jonny Tran                     930         16307          11528           34.34
JonnyTran                      457         27907          24256           64.35
Nhat Tran                        2           110             82            0.24
deepsource-autofix[b            12           624            252            1.08

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jonny Tran                 3618           22.2         10.5               11.08
JonnyTran                  2335            8.4          7.7               14.26
deepsource-autofix[b        488           78.2          2.3                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03249/joss.03249/10.21105.joss.03249.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03249/joss.03249/10.21105.joss.03249.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/nar/gky1079 is OK

MISSING DOIs

- 10.1093/nar/gkaa554 may be a valid DOI for title: The Galaxy platform for accessible, reproducible and collaborative biomedical analyses: 2020 update
- 10.1093/bioinformatics/btz133 may be a valid DOI for title: Anduril 2: upgraded large-scale data integration framework
- 10.1074/mcp.m115.052381 may be a valid DOI for title: Integration of metabolomics and transcriptomics reveals major metabolic pathways and potential biomarker involved in prostate cancer
- 10.1371/journal.pcbi.1005752 may be a valid DOI for title: mixOmics: An R package for ‘omics feature selection and multiple data integration
- 10.1186/gm186 may be a valid DOI for title: Large-scale data integration framework provides a comprehensive view on glioblastoma multiforme
- 10.1093/nar/gkw377 may be a valid DOI for title: Enrichr: a comprehensive gene set enrichment analysis web server 2016 update
- 10.1038/nrg3606 may be a valid DOI for title: Long non-coding RNAs: new players in cell differentiation and development
- 10.1093/nar/gkr1175 may be a valid DOI for title: NONCODE v3. 0: integrative annotation of long noncoding RNAs
- 10.1093/nar/gks915 may be a valid DOI for title: LNCipedia: a database for annotated human lncRNA transcript sequences and structures
- 10.1101/gr.132159.111 may be a valid DOI for title: The GENCODE v7 catalog of human long noncoding RNAs: analysis of their gene structure, evolution, and expression
- 10.1093/nar/gku1173 may be a valid DOI for title: LncRNA2Target: a database for differentially expressed genes after lncRNA knockdown or overexpression
- 10.1093/nar/gky1051 may be a valid DOI for title: LncRNA2Target v2. 0: a comprehensive database for target genes of lncRNAs in human and mouse
- 10.1093/database/bav083 may be a valid DOI for title: LncReg: a reference resource for lncRNA-associated regulatory networks
- 10.1093/nar/gkq1138 may be a valid DOI for title: lncRNAdb: a reference database for long noncoding RNAs
- 10.1093/nar/gkw943 may be a valid DOI for title: DisGeNET: a comprehensive platform integrating information on human disease-associated genes and variants
- 10.1093/nar/gks1099 may be a valid DOI for title: LncRNADisease: a database for long-non-coding RNA-associated diseases
- 10.1093/nar/gkj112 may be a valid DOI for title: miRBase: microRNA sequences, targets and gene nomenclature
- 10.1093/nar/gkt1057 may be a valid DOI for title: NPInter v2. 0: an updated database of ncRNA interactions
- 10.1093/database/bav083 may be a valid DOI for title: LncReg: a reference resource for lncRNA-associated regulatory networks
- 10.1093/database/bat034 may be a valid DOI for title: lncRNome: a comprehensive knowledgebase of human long noncoding RNAs
- 10.1093/nar/gkj147 may be a valid DOI for title: The HUGO gene nomenclature database, 2006 updates
- 10.1017/cbo9780511546198.190 may be a valid DOI for title: Scale-free networks in cell biology
- 10.1093/nar/gkv1270 may be a valid DOI for title: DIANA-LncBase v2: indexing microRNA targets on non-coding transcripts
- 10.1093/nar/gkw1102 may be a valid DOI for title: The BioGRID interaction database: 2017 update
- 10.1093/nar/gkt1248 may be a valid DOI for title: starBase v2. 0: decoding miRNA-ceRNA, miRNA-ncRNA and protein–RNA interaction networks from large-scale CLIP-Seq data
- 10.1371/journal.pcbi.1005752 may be a valid DOI for title: mixOmics: An R package for ‘omics feature selection and multiple data integration

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@JonnyTran - while I check your paper over, please fix the DOIs in your references (noting that Whedon's suggestions are not always right).

**Comment by JonnyTran** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03249/joss.03249/10.21105.joss.03249.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03249/joss.03249/10.21105.joss.03249.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4731011 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4731011" target="_blank">10.5281/zenodo.4731011</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3249 with the following error: 
```
 [WARNING] Citeproc: citation wolf2018scanpy not found
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/bibtex_parser.rb:82:in `doi_citation': undefined method `encode' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/bibtex_parser.rb:64:in `make_citation'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/bibtex_parser.rb:50:in `block in generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.6/lib/bibtex/bibliography.rb:149:in `each'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-5.1.6/lib/bibtex/bibliography.rb:149:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/bibtex_parser.rb:43:in `generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/compilers.rb:248:in `crossref_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/compilers.rb:21:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:100:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:88:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/nar/gkaa554 is OK
- 10.3389/fonc.2020.00804 is OK
- 10.1093/bioinformatics/btz133 is OK
- 10.1371/journal.pcbi.1005752 is OK
- 10.1186/gm186 is OK
- 10.1093/nar/gkw377 is OK
- 10.1038/nrg3606 is OK
- 10.1093/nar/gkr1175 is OK
- 10.1093/nar/gks915 is OK
- 10.1101/gr.132159.111 is OK
- 10.1093/nar/gku1173 is OK
- 10.1093/nar/gky1051 is OK
- 10.1093/database/bav083 is OK
- 10.1093/nar/gkq1138 is OK
- 10.1093/nar/gks1099 is OK
- 10.1093/nar/gkj112 is OK
- 10.1093/nar/gkt1057 is OK
- 10.1093/database/bav083 is OK
- 10.1093/database/bat034 is OK
- 10.1093/nar/gkj147 is OK
- 10.1017/cbo9780511546198.190 is OK
- 10.1093/nar/gkv1270 is OK
- 10.1093/nar/gkw1102 is OK
- 10.1093/nar/gky1079 is OK
- 10.1093/nar/gkt1248 is OK
- 10.1371/journal.pcbi.1005752 is OK

MISSING DOIs

- 10.1074/mcp.m115.052381 may be a valid DOI for title: Integration of metabolomics and transcriptomics reveals major metabolic pathways and potential biomarker involved in prostate cancer

INVALID DOIs

- .1093/nar/gkw943 is INVALID
```

**Comment by arfon** [comment]
@JonnyTran - looks like your BibTeX file doesn't have a `wolf2018scanpy` entry. Could you take a look?

**Comment by JonnyTran** [comment]
Oops, I've missed those DOIs. I've just fixed them.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/nar/gkaa554 is OK
- 10.1186/s13059-017-1382-0 is OK
- 10.3389/fonc.2020.00804 is OK
- 10.1093/bioinformatics/btz133 is OK
- 10.1074/mcp.M115.052381 is OK
- 10.1371/journal.pcbi.1005752 is OK
- 10.1038/nbt.3134 is OK
- 10.1093/bib/bbx080 is OK
- 10.1186/gm186 is OK
- 10.1093/nar/gkw377 is OK
- 10.1038/nrg3606 is OK
- 10.1093/nar/gkr1175 is OK
- 10.1093/nar/gks915 is OK
- 10.1101/gr.132159.111 is OK
- 10.1093/nar/gku1173 is OK
- 10.1093/nar/gky1051 is OK
- 10.1093/database/bav083 is OK
- 10.1093/nar/gkq1138 is OK
- 10.1093/nar/gkw943 is OK
- 10.1093/nar/gks1099 is OK
- 10.1093/nar/gkj112 is OK
- 10.1093/nar/gkt1057 is OK
- 10.1093/database/bav083 is OK
- 10.1093/database/bat034 is OK
- 10.1093/nar/gkj147 is OK
- 10.1017/cbo9780511546198.190 is OK
- 10.1093/nar/gkv1270 is OK
- 10.1093/nar/gkw1102 is OK
- 10.1093/nar/gky1079 is OK
- 10.1093/nar/gkt1248 is OK
- 10.1371/journal.pcbi.1005752 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@JonnyTran - please merge this PR which makes a number of small formatting fixes to your paper: https://github.com/BioMeCIS-Lab/OpenOmics/pull/164

Also, please be sure to cite Dask and Pandas in your paper. You can find information on how to cite them here:

- https://docs.dask.org/en/latest/cite.html
- https://pandas.pydata.org/about/citing.html

**Comment by JonnyTran** [comment]
Hi Arfon, I've just added pandas and dask citations. 

I opted for the bibtex with author names,
> @InProceedings{ matthew_rocklin-proc-scipy-2015,
  author    = { Matthew Rocklin },
  title     = { Dask: Parallel Computation with Blocked algorithms and Task Scheduling },
  booktitle = { Proceedings of the 14th Python in Science Conference },
  pages     = { 130 - 136 },
  year      = { 2015 },
  editor    = { Kathryn Huff and James Bergstra }
}

rather than team authors,
> @Manual{,
  title = {Dask: Library for dynamic task scheduling},
  author = {{Dask Development Team}},
  year = {2016},
  url = {https://dask.org},
}

because Whedon will pick up the last name as (Team, 2016) citation.

Thanks for checking this over. I hope I didn't miss anything else.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/nar/gkaa554 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.25080/Majora-7b98e3ed-013 is OK
- 10.1186/s13059-017-1382-0 is OK
- 10.3389/fonc.2020.00804 is OK
- 10.1093/bioinformatics/btz133 is OK
- 10.1074/mcp.M115.052381 is OK
- 10.1371/journal.pcbi.1005752 is OK
- 10.1038/nbt.3134 is OK
- 10.1093/bib/bbx080 is OK
- 10.1186/gm186 is OK
- 10.1093/nar/gkw377 is OK
- 10.1038/nrg3606 is OK
- 10.1093/nar/gkr1175 is OK
- 10.1093/nar/gks915 is OK
- 10.1101/gr.132159.111 is OK
- 10.1093/nar/gku1173 is OK
- 10.1093/nar/gky1051 is OK
- 10.1093/database/bav083 is OK
- 10.1093/nar/gkq1138 is OK
- 10.1093/nar/gkw943 is OK
- 10.1093/nar/gks1099 is OK
- 10.1093/nar/gkj112 is OK
- 10.1093/nar/gkt1057 is OK
- 10.1093/database/bav083 is OK
- 10.1093/database/bat034 is OK
- 10.1093/nar/gkj147 is OK
- 10.1017/cbo9780511546198.190 is OK
- 10.1093/nar/gkv1270 is OK
- 10.1093/nar/gkw1102 is OK
- 10.1093/nar/gky1079 is OK
- 10.1093/nar/gkt1248 is OK
- 10.1371/journal.pcbi.1005752 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2290

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2290, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1391380065078874117) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2291
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03249](https://doi.org/10.21105/joss.03249)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@JonnyTran - thanks for your submission to JOSS. Your paper is now accepted and published :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03249/status.svg)](https://doi.org/10.21105/joss.03249)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03249">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03249/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03249/status.svg
   :target: https://doi.org/10.21105/joss.03249
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03249/status.svg)](https://doi.org/10.21105/joss.03249)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
