### ISSUE TITLE
[PRE REVIEW]: pyrgg: Python Random Graph Generator

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#325]
**Submitting author:** @sepandhaghighi (<a href="http://orcid.org/0000-0001-9450-2375">Sepand Haghighi</a>)
**Repository:** <a href="https://github.com/sepandhaghighi/pyrgg" target ="_blank">https://github.com/sepandhaghighi/pyrgg</a>
**Version:** v0.1
**Editor:** @danielskatz
**Reviewer:** @hausen

**Author instructions**

Thanks for submitting your paper to JOSS @sepandhaghighi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sepandhaghighi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@hausen, would you be willing to review this submission?

**Comment by hausen** [comment]
Sure!

2017-07-21 14:22 GMT-04:00 Daniel S. Katz <notifications@github.com>:

**Comment by danielskatz** [comment]
@whedon assign @hausen as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @hausen

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/331. Feel free to close this issue now!
