### ISSUE TITLE
[PRE REVIEW]: lenstronomy II: A gravitational lensing software ecosystem

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3252]
**Submitting author:** @sibirrer (<a href="http://orcid.org/0000-0003-3195-5507">Simon Birrer</a>)
**Repository:** <a href="https://github.com/sibirrer/lenstronomy" target ="_blank">https://github.com/sibirrer/lenstronomy</a>
**Version:** v1.8.1
**Editor:** @danielskatz
**Reviewers:** @smsharma, @coljac
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @sibirrer. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@sibirrer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=6.95 s (102.4 files/s, 24937.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           231           8777              0          82405
Python                         415          10161          16077          38117
JavaScript                      10           2229           2248           8871
reStructuredText                42            758            952           1076
CSS                              4            199             42            766
make                             2             39              6            189
Markdown                         1             39              0             89
XML                              1             10              0             53
INI                              1              4              0             36
YAML                             3              8             22             35
Ruby                             1              0              0              2
-------------------------------------------------------------------------------
SUM:                           711          22224          19347         131639
-------------------------------------------------------------------------------


Statistical information for the repository '6a33dcf34c8a30d80f685cea' was
gathered on 2021/05/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Anowar Jaman Shajib            124          5701           3132            3.21
Aymeric Galan                  220         11415           6456            6.50
AymericG                         1            57              1            0.02
Daniel Gilman                  183         10082           7874            6.53
Ewoud                            2            13             18            0.01
Ewoud Wempe                     20           481            133            0.22
Giulia Pagano                   11          1016             83            0.40
Jelle Aalbers                   17           927             69            0.36
Luca Teodori                    26          1778           1140            1.06
Lyne VdV                         4           172              6            0.06
LyneVdV                          7           455             69            0.19
Madi Ueland                     15           738             91            0.30
Nicolas Tessore                  2           357              3            0.13
Robert Morgan                    4           173              5            0.06
Sebastian Wagner-Car             3            32             30            0.02
Simon Birrer                   557         81553          40247           44.32
ajshajib                         1            41             12            0.02
dangilman                       24          3242           1297            1.65
jiwoncpark                      11           109            101            0.08
lilan                           11           256             45            0.11
martin-millon                   16            50            571            0.23
sibirrer                       858         58297          36466           34.49

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Anowar Jaman Shajib        2767           48.5         20.6                8.89
Aymeric Galan              3299           28.9         15.9                8.88
Daniel Gilman              3792           37.6         13.6                6.94
Ewoud                         9           69.2          7.0               11.11
Ewoud Wempe                 354           73.6          2.1                5.93
Giulia Pagano               927           91.2         10.1               19.42
Jelle Aalbers               858           92.6          6.4                4.78
Luca Teodori                643           36.2          3.9               10.73
Lyne VdV                    144           83.7          8.4                6.94
LyneVdV                     369           81.1          4.4               10.03
Madi Ueland                 648           87.8          8.9                9.72
Nicolas Tessore             289           81.0         11.6               16.26
Robert Morgan               168           97.1          7.7                9.52
Sebastian Wagner-Car         29           90.6          2.0                3.45
Simon Birrer              19918           24.4         37.4               12.04
jiwoncpark                   78           71.6         14.4                6.41
lilan                       203           79.3         22.6                7.88
martin-millon                 9           18.0         15.7                0.00
sibirrer                  43209           74.1         18.9               10.05
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3252 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon generate pdf from JOSS_paper

**Comment by whedon** [comment]
PDF failed to compile for issue #3252 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
Hi @eloisabentivegna would you be able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @eloisabentivegna as editor

**Comment by whedon** [comment]
@eloisabentivegna has been invited to edit this submission.

**Comment by sibirrer** [comment]
Hi JOSS editors!

The paper is in the branch JOSS_paper (I somehow could not indicate this on the submission form/was rejected as not a clone-able project). I may have mis-clicked on the suggested editor form. I am happy with any editor.

For reviewers, when reading from bottom to top of the file, I can identify two lensing experts: 
coljac
smsharma

and in addition those people with coding and astronomy expertise I noted (incomplete list): changhoonhahn
RobertRosca
Teuben
olebole
danhey
cmillion
KshitijAggarwal
yymao
HeloiseS

Let me know if you have questions and thank you very much for handling our submission!
Simon, in the name of the authors

**Comment by kthyng** [comment]
@whedon generate pdf from branch JOSS_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03252/joss.03252/10.21105.joss.03252.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03252/joss.03252/10.21105.joss.03252.pdf) :page_facing_up: :point_left:

**Comment by sibirrer** [comment]
@whedon generate pdf from branch JOSS_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03252/joss.03252/10.21105.joss.03252.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03252/joss.03252/10.21105.joss.03252.pdf) :page_facing_up: :point_left:

**Comment by sibirrer** [comment]
I just made minor changes to the manuscript and this version is ready to go for review

**Comment by eloisabentivegna** [comment]
> Hi @eloisabentivegna would you be able to edit this submission?

@kthyng, I don't have capacity for this one, sorry!

**Comment by sibirrer** [comment]
Hi @kthyng : Would you like me to suggest another editor for this submission?

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @coljac, @smsharma - I'm looking for two reviewers for this JOSS submission.  Are either or ideally both of you willing to review this?

**Comment by smsharma** [comment]
Hi @danielskatz, I would be happy to.

**Comment by danielskatz** [comment]
Great, thanks - I'll add you in the system, but we won't actually start the review until we get one more reviewer as well.

**Comment by danielskatz** [comment]
@whedon assign @smsharma as reviewer

**Comment by whedon** [comment]
OK, @smsharma is now a reviewer

**Comment by coljac** [comment]
@danielskatz Yep I can do it.

**Comment by danielskatz** [comment]
Great!  I'll add you, and we can start the review

**Comment by danielskatz** [comment]
@whedon add @coljac as reviewer

**Comment by whedon** [comment]
OK, @coljac is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3283.
