### ISSUE TITLE
[PRE REVIEW]: Human-Learn

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3253]
**Submitting author:** @koaning (<a href="http://orcid.org/0000-0003-0845-4528">Vincent Warmerdam</a>)
**Repository:** <a href="https://github.com/koaning/human-learn/" target ="_blank">https://github.com/koaning/human-learn/</a>
**Version:** 0.3.0
**Editor:** @jbytecode
**Reviewers:** @desilinguist, @ahurriyetoglu
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @koaning. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arfon.

@koaning if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.27 s (262.8 files/s, 49471.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       2            356            214           1963
Python                          32            406            562           1315
Markdown                        18            391              0            993
Jupyter Notebook                 6              0           6223            209
CSS                              2             75            129            181
YAML                             4              8              2            131
HTML                             2             40              0             85
TeX                              1              3              0             36
make                             1             10              0             31
JSON                             3              0              0              3
-------------------------------------------------------------------------------
SUM:                            71           1289           7130           4947
-------------------------------------------------------------------------------


Statistical information for the repository '3116cdc464ea8afc13c633a6' was
gathered on 2021/05/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kay Hoogland                     1            37              0            0.12
Vincent                          1         11998              0           39.24
koaning                          1            20              4            0.08
vincent d warmerdam             22          5641          12876           60.56

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kay Hoogland                 37          100.0          6.8                5.41
vincent d warmerdam        4779           84.7          3.0                7.70
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3253 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kthyng** [comment]
Hi @koaning and thanks for your submission. Unfortunately we have a backlog of submissions in this area with overburdened editors, so I have added your submission to a waitlist. Thank you for your patience.

**Comment by koaning** [comment]
No rush. 

One question though, this is a package that I maintain personally which means that I don't have a `affiliations` entry. Should I just put in my name here?

**Comment by kyleniemeyer** [comment]
@koaning I think you still may need the affiliations field, even if you leave it empty

cc @openjournals/dev just checking, is that correct?

**Comment by danielskatz** [comment]
you can't leave it empty, so you need to put in one that says "independent researcher" or "self" etc...

**Comment by arfon** [comment]
> you can't leave it empty, so you need to put in one that says "independent researcher" or "self" etc...

Correct.

**Comment by koaning** [comment]
Good to know! Just made the small change.

**Comment by koaning** [comment]
Still strange that the compiler did not complain about it.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03253/joss.03253/10.21105.joss.03253.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03253/joss.03253/10.21105.joss.03253.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
I'm sorry @jbytecode, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by jbytecode** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jbytecode

**Comment by jbytecode** [comment]
Hi @koaning,

Thank you for the submission. Now it is time to assign some reviewers for the submission. Could you please take a look through https://bit.ly/joss-reviewers to suggest some potential reviewers?

**Comment by jbytecode** [comment]
@koaning I notice that you're the only author on the paper but it looks like there have been some other contributors to the codebase. Could you please clarify?

**Comment by koaning** [comment]
There are three contributors outside of myself. 

One contributor fixed a typo: 
https://github.com/koaning/human-learn/commit/deace163a8e2f381392c08119ecad6944f48c1d8

Another one contributed a one-liner so that the license would be included in the source distribution:
https://github.com/koaning/human-learn/commit/188d16775393edcafcf77d91b4f2491f79a3e3d5

Finally, there's one contributor who added a dataset to the repository. That's a welcome PR, but it's very much a utility function that doesn't touch the internals of the package. 
https://github.com/koaning/human-learn/commits?author=kayhoogland

I don't mind mentioning these contributors on the paper, but since none of the other contributions touched the internal components (what the package is really about) it didn't occur to me to mention them in the paper directly.

**Comment by koaning** [comment]
After glancing at the reviewer list I think the following reviewers might be good. I'm basing this purely on the preferred programming language and the listed topics/domains. 

- @desilinguist
- @jankatins
- @ahurriyetoglu
- @kellieotto
- @aokad

**Comment by desilinguist** [comment]
I'd be happy to review this but I can't do it until mid-July unfortunately.

**Comment by jbytecode** [comment]
@jankatins hi! I am pinging you just because you are registered as an expert on Python and visualizing on the JOSS reviewer list. Would you willing to assist in reviewing this submission?

**Comment by jbytecode** [comment]
> I'd be happy to review this but I can't do it until mid-July unfortunately.

@desilinguist thank you! The reviewing process will start whenever we assign a second viewer. Meanwhile, you can have a look at the reviewing guide in https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by jbytecode** [comment]
@whedon assign @desilinguist as reviewer

**Comment by whedon** [comment]
OK, @desilinguist is now a reviewer

**Comment by jbytecode** [comment]
@koaning while we are seeking a proper reviewer team, please consider following items:

- The paper does not compare the software with the previous one(s). In JOSS, this kind of discussion is generally handled in a `State of the field` section. 
- It is not usual for an article not to have a reference list. I think, when you add comparisons in State of the field section, you will use some citations.

**Comment by jbytecode** [comment]
@ahurriyetoglu I am sorry if I disturbed you. I am just pinging you to ask if you would be willing to assist in reviewing this submission for JOSS (Journal of open source software).

**Comment by jbytecode** [comment]
Hi @kellieotto, would you be willing to assist in reviewing this submission for JOSS?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "Human-Learn". You can find more information at the top of this Github issue.

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
Hi @aokad, would you be willing to assist in reviewing this submission for JOSS?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "Human-Learn". You can find more information at the top of this Github issue.

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by kellieotto** [comment]
Hi @jbytecode @koaning, I don't currently have bandwidth to review this.

**Comment by jbytecode** [comment]
@whedon add @ahurriyetoglu as reviewer

**Comment by whedon** [comment]
OK, @ahurriyetoglu is now a reviewer

**Comment by jbytecode** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3448.
