### ISSUE TITLE
[PRE REVIEW]: DataLad: distributed system for joint management of code, data, and their relationship

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3254]
**Submitting author:** @yarikoptic (<a href="http://orcid.org/0000-0003-3456-2493">Yaroslav Halchenko</a>)
**Repository:** <a href="https://github.com/datalad/datalad" target ="_blank">https://github.com/datalad/datalad</a>
**Version:** 0.14.3
**Editor:** @arokem
**Reviewers:** @szorowi1, @jkanche
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @yarikoptic. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arokem.

@yarikoptic if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3254 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.98 s (141.5 files/s, 41132.9 lines/s)
-----------------------------------------------------------------------------------
Language                         files          blank        comment           code
-----------------------------------------------------------------------------------
Python                             330          14272          28216          62740
reStructuredText                    18           1451            460           4920
Markdown                             6            992              0           3622
YAML                                13             99            239           2257
Bourne Shell                        25            230             83            937
Bourne Again Shell                  18            202            301            922
JSON                                 2             19              0            253
make                                 2             45             13            190
Windows Resource File                1              9              0             53
INI                                  1              6              0             42
Logos                                1             13             25             20
DOS Batch                            3              0              9             13
PowerShell                           1              1              2              5
TOML                                 1              0              1              2
-----------------------------------------------------------------------------------
SUM:                               422          17339          29349          75976
-----------------------------------------------------------------------------------


Statistical information for the repository '9963524159fe2dc358726412' was
gathered on 2021/05/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adina Wagner                   101           992            384            0.25
Alejandro de la Vega             5             7              7            0.00
Alex Waite                       2            12             13            0.00
Andy Connolly                    7            44             30            0.01
Benjamin Poldrack             1525         57087          25544           14.85
Christian Mönch                  9           271             43            0.06
Christopher J. Marki             4           169             46            0.04
Dave MacFarlane                 35           490            126            0.11
Debanjum Singh Solan           168         42529           4831            8.51
Gergana Alteva                 158          2903           1470            0.79
Horea Christian                  1             2              0            0.00
Jason Gors                      52           998            461            0.26
John T. Wodder II               26           726            848            0.28
Kusti Skytén                     2             2              0            0.00
Kyle Meyer                    1594         36680          15014            9.29
Matt Cieslak                     2             6              3            0.00
Matteo Visconti dOC              2            20              2            0.00
Michael Hanke                 3669        103152         133292           42.49
Nell Hardcastle                  1             1              1            0.00
Neuroimaging Communi             2            39             46            0.02
Nolan Nichols                    8            36             10            0.01
Robin Schneider                  1             2              2            0.00
Soichi Hayashi                   1             1              1            0.00
Taylor Olson                     7            55             30            0.02
Vanessa Sochat                   3            14              6            0.00
Yarchael                         2            12             10            0.00
Yaroslav Halchenko            3125         91283          36752           23.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adina Wagner                533           53.7         14.7                8.44
Alex Waite                    4           33.3         44.4               25.00
Andy Connolly                31           70.5         11.9                3.23
Benjamin Poldrack         11710           20.5         33.7               22.67
Christian Mönch             236           87.1          6.9               13.98
Christopher J. Marki        122           72.2         23.7               14.75
Dave MacFarlane             309           63.1         33.7               18.45
Debanjum Singh Solan        404            0.9         57.3               15.35
Gergana Alteva              131            4.5         57.3               15.27
Jason Gors                  269           27.0         68.7               12.64
John T. Wodder II            57            7.9          7.1                7.02
Kyle Meyer                17849           48.7         20.9               14.95
Matt Cieslak                  3           50.0          2.3              100.00
Matteo Visconti dOC           5           25.0         41.1                0.00
Michael Hanke             40833           39.6         28.7               17.88
Neuroimaging Communi         14           35.9          0.0                0.00
Nolan Nichols                16           44.4          9.3                6.25
Robin Schneider               2          100.0          1.7                0.00
Soichi Hayashi                1          100.0         17.4                0.00
Taylor Olson                  7           12.7         39.2               28.57
Yarchael                      4           33.3         32.0                0.00
Yaroslav Halchenko        32238           35.3         43.6               19.29
vsoch                         5          100.0         31.6                0.00
```

**Comment by yarikoptic** [comment]
@whedon generate pdf from paper-joss

**Comment by whedon** [comment]
PDF failed to compile for issue #3254 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by yarikoptic** [comment]
@whedon generate pdf from branch paper-joss

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03254/joss.03254/10.21105.joss.03254.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03254/joss.03254/10.21105.joss.03254.pdf) :page_facing_up: :point_left:

**Comment by yarikoptic** [comment]
Just to help to get the ball rolling -- potential reviewers (from the given list) which might be interested: aaronpeikert, peterakirk, williamfgc, csadorf, szorowi1

**Comment by arokem** [comment]
@kthyng : I can take this one, unless you have another plan for it. Feel free to assign me.

**Comment by mih** [comment]
Thx @arokem !

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
👋 @csadorf : would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
👋 @szorowi1: would you be willing to review this article for JOSS?

**Comment by csadorf** [comment]
> 👋 @csadorf : would you be willing to review this article for JOSS?

Yes, I would be happy to! the only hitch is that I will be on vacation from May 13th until May 28th. What is the expected timeline?

**Comment by arokem** [comment]
@csadorf : Ideally, we'd like to finish this in a few weeks. Do you think that you will have time for a first round of review before you head out on your vacation?

**Comment by arokem** [comment]
:wave: @pibion : would you be willing to review this article for JOSS?

**Comment by arokem** [comment]
:wave: @jkanche: would you be willing to review this article for JOSS?

**Comment by csadorf** [comment]
> @csadorf : Ideally, we'd like to finish this in a few weeks. Do you think that you will have time for a first round of review before you head out on your vacation?

@arokem Since this would be my first review for JOSS I am afraid that I might not be able to without comprising due diligence. So unfortunately I have to decline this time. Please feel free to reach out to me again in case that you would still like my input on this particular submission after my return or for similar submissions in the future.

**Comment by arokem** [comment]
@whedon assign @jkanchee as reviewer

**Comment by whedon** [comment]
OK, @jkanchee is now a reviewer

**Comment by arokem** [comment]
@whedon add @szorowi1 as reviewer

**Comment by whedon** [comment]
OK, @szorowi1 is now a reviewer

**Comment by arokem** [comment]
@whedon commands

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3262.

**Comment by arokem** [comment]
OK, @jkanche and @szorowi1 : with that typo now fixed (sorry about that!), I think that you can head over to #3262 for the review.
