### ISSUE TITLE
[PRE REVIEW]: exoplanet: Gradient-based probabilistic inference forexoplanet data & other astronomical time series

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3256]
**Submitting author:** @dfm (<a href="http://orcid.org/0000-0002-9328-5652">Daniel Foreman-Mackey</a>)
**Repository:** <a href="https://github.com/exoplanet-dev/exoplanet" target ="_blank">https://github.com/exoplanet-dev/exoplanet</a>
**Version:** v0.5.0
**Editor:** @arfon
**Reviewers:** @grburgess, @benjaminpope
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @dfm. **Currently, there isn't an JOSS editor assigned** to your paper.

@dfm if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.39 s (168.8 files/s, 22716.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          39           1170           1566           3968
TeX                              1             42              0            633
Markdown                         6             67              0            368
reStructuredText                 6            190             93            301
YAML                             9             33              0            272
CSS                              1             16              0             78
make                             1              8              5             30
TOML                             1              2              0             28
INI                              1              0              0              8
HTML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            66           1528           1664           5692
-------------------------------------------------------------------------------


Statistical information for the repository 'eda8ab67fa51b87a14d98be8' was
gathered on 2021/05/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adrian Price-Whelan              5            33             18            0.01
Arjun Savel                     18           220             24            0.03
Christina Hedges                 5            91             82            0.02
Dan F-M                        560        165043         316130           58.16
Dan Foreman-Mackey              36          3538         176542           21.77
Eric Agol                        1             1              1            0.00
Ian Czekala                      5           115             23            0.02
Luke Bouma                       1            13              9            0.00
Rodrigo Luger                   10        164894            273           19.96
Timothy D Brandt                 1           254              0            0.03
Tom Barclay                      1             1              1            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adrian Price-Whelan           1            3.0         12.4                0.00
Arjun Savel                  52           23.6          5.2                5.77
Christina Hedges             38           41.8          2.1                7.89
Dan F-M                     135            0.1          8.5               74.07
Dan Foreman-Mackey         6173          174.5         18.2               11.45
Eric Agol                     1          100.0          0.2              100.00
Ian Czekala                  70           60.9         23.8               14.29
Luke Bouma                   13          100.0         10.0                0.00
Rodrigo Luger               221            0.1         19.7                9.95
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03256/joss.03256/10.21105.joss.03256.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03256/joss.03256/10.21105.joss.03256.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.1998447 is OK
- 10.5281/zenodo.4695331 is OK
- 10.7717/peerj-cs.55 is OK
- 10.21105/joss.01143 is OK
- 10.1093/mnras/stt1435 is OK
- 10.1093/mnrasl/slt075 is OK
- 10.3847/1538-3881/aaf22f is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.3847/1538-3881/aae8e5 is OK
- 10.3847/1538-3881/ab4fee is OK
- 10.3847/1538-3881/aa9332 is OK
- 10.3847/2515-5172/aaaf6c is OK
- 10.1051/0004-6361/201118085 is OK
- 10.1093/mnras/stz2870 is OK
- 10.1086/669497 is OK
- 10.1093/mnras/stz2688 is OK
- 10.1086/683602 is OK
- 10.1088/1538-3873/aaaaa8 is OK
- 10.3847/1538-3881/ab6663 is OK
- 10.1051/0004-6361/201628579 is OK
- 10.1093/mnras/sty2472 is OK
- 10.1093/mnras/stv894 is OK
- 10.1093/mnras/stz3251 is OK
- 10.3847/1538-4357/abc686 is OK
- 10.3847/1538-3881/abbc16 is OK
- 10.18637/jss.v076.i01 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.3847/1538-3881/aba4b2 is OK
- 10.1038/s41586-020-2400-z is OK
- 10.1093/mnras/stx138 is OK

MISSING DOIs

- 10.3847/1538-4365/abe70e may be a valid DOI for title: Allesfitter: Flexible Star and Exoplanet Inference From Photometry and Radial Velocity
- 10.3847/1538-4357/abebe3 may be a valid DOI for title: A coplanar circumbinary protoplanetary disk in the TWA 3 triple M dwarf system

INVALID DOIs

- None
```

**Comment by dfm** [comment]
Potential reviewers from the list include `nespinoza`, `benjaminpope`, `jbrande`, `grburgess`, and `hpparvi`.

**Comment by Kevin-Mattheus-Moerman** [comment]
@xuanxu would you be able to edit this submission? If you need time to wrap up the other submissions you are handling first I can waitlist this for now. Also @arfon you were suggested as editor I believe. However since you have a lot on your plate I take it you cannot take this on too?

**Comment by arfon** [comment]
@whedon assign me as editor

:+1: I can take this.

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave:  @benjaminpope and @grburgess - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is [_exoplanet: Gradient-based probabilistic inference forexoplanet data & other astronomical time series_](https://github.com/exoplanet-dev/exoplanet).

**Comment by grburgess** [comment]
@arfon I can review. Cheers.

**Comment by arfon** [comment]
@whedon assign @grburgess as reviewer

**Comment by whedon** [comment]
OK, @grburgess is now a reviewer

**Comment by arfon** [comment]
@grburgess - thanks so much! I would like to wait until I've found a second reviewer here before moving this to the full review issue (with checklists etc.), so please sit tight for a little while.

**Comment by arfon** [comment]
:wave: @jbrande @nespinoza - would either of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is [_exoplanet: Gradient-based probabilistic inference forexoplanet data & other astronomical time series_](https://github.com/exoplanet-dev/exoplanet).

**Comment by benjaminpope** [comment]
Sorry I just saw this - I for some reason didn't get a notification to my email. I'd be happy to.

**Comment by arfon** [comment]
⚡ thanks @benjaminpope!

**Comment by arfon** [comment]
@whedon add @benjaminpope as reviewer

**Comment by whedon** [comment]
OK, @benjaminpope is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3285.

**Comment by arfon** [comment]
@grburgess, @benjaminpope - many thanks for agreeing to review this submission for JOSS. See you over in #3285 where the actual review will take place.
