### ISSUE TITLE
[PRE REVIEW]: dataaimsr: An R Client for the Australian Institute of Marine Science Data Platform API which provides easy access to AIMS Data Platform

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3258]
**Submitting author:** @dbarneche (<a href="http://orcid.org/0000-0002-4568-2362">Diego Barneche</a>)
**Repository:** <a href="https://github.com/ropensci/dataaimsr" target ="_blank">https://github.com/ropensci/dataaimsr</a>
**Version:** v1.0.3
**Editor:** @kthyng
**Reviewers:** @kthyng
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @dbarneche. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @karthik.

@dbarneche if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.49 s (46.9 files/s, 135743.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                            23              4              0         197713
R                               28             52            640            948
Markdown                         5            142              0            578
TeX                              2             51             30            451
XML                              1              0              2            441
YAML                             6             46             10            206
Rmd                              5            265            948             48
-------------------------------------------------------------------------------
SUM:                            70            560           1630         200385
-------------------------------------------------------------------------------


Statistical information for the repository 'd898f47365b04ad92549d98d' was
gathered on 2021/05/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jeffrey Sheehan                  5            32             32          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by kthyng** [comment]
Already reviewed at [rOpenSci](https://github.com/ropensci/software-review/issues/428).

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.mio.2014.09.001 is OK
- 10.21014/acta_imeko.v5i1.213 is OK
- 10.32614/RJ-2018-009 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03258/joss.03258/10.21105.joss.03258.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03258/joss.03258/10.21105.joss.03258.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @dbarneche! I'll start processing your submission next week. It should go pretty quickly since it's already reviewed! Please do note that you'll need a section of your paper with the name "Statement of Need" to meet our paper requirements.

**Comment by dbarneche** [comment]
Hi @kthyng ! Thank you very much for acting as Editor.
Also thanks for flagging the structural issue. We currently have a section named [`Background and Statement of need`](https://github.com/ropensci/dataaimsr/blob/master/paper/paper.md#background-and-statement-of-need), should I rename it to `Statement of need` only?
Have a good weekend.

**Comment by kthyng** [comment]
@dbarneche Yes, please rename it. I see your paper is pretty long — this is almost to the length where I would require it to be shorter but we try not to be too heavy handed about it. If some of it is repeat from the docs, you could cut it from the paper. But, if you feel like it is how you'd like it to be, you can leave it.

**Comment by kthyng** [comment]
@whedon assign me as reviewer

**Comment by whedon** [comment]
OK, me is now a reviewer

**Comment by kthyng** [comment]
@whedon remove me as reviewer

**Comment by whedon** [comment]
OK, me is no longer a reviewer

**Comment by kthyng** [comment]
@whedon assign @kthyng as reviewer

**Comment by whedon** [comment]
OK, @kthyng is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3282.
