### ISSUE TITLE
[PRE REVIEW]: gamut: A Geospatial Analysis of Multisector Urban Teleconnections

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3259]
**Submitting author:** @KristianNelson (<a href="http://orcid.org/0000-0002-6745-167X">Kristian Nelson</a>)
**Repository:** <a href="https://github.com/IMMM-SFA/gamut" target ="_blank">https://github.com/IMMM-SFA/gamut</a>
**Version:** v0.1.0
**Editor:** @KristinaRiemer
**Reviewers:** @fsanchez-trigueros
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @KristianNelson. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @csoneson.

@KristianNelson if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (166.1 files/s, 21553.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               15            354            415           1188
Markdown                         2             50              0            264
TeX                              1             30              0            234
Rmd                              2             46             85             96
YAML                             2             17              0             75
-------------------------------------------------------------------------------
SUM:                            22            497            500           1857
-------------------------------------------------------------------------------


Statistical information for the repository 'ca132d1b10ab25704d308b81' was
gathered on 2021/05/06.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03259/joss.03259/10.21105.joss.03259.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03259/joss.03259/10.21105.joss.03259.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.envsoft.2015.11.007 is OK
- 10.32614/RJ-2018-009 is OK

MISSING DOIs

- 10.32614/rj-2011-002 may be a valid DOI for title: testthat: Get Started with Testing
- 10.1201/9781315373461-1 may be a valid DOI for title: knitr: A Comprehensive Tool for Reproducible Research in R
- 10.1201/9781315373461-1 may be a valid DOI for title: knitr: A Comprehensive Tool for Reproducible Research in R

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @KristianNelson and thanks for your submission! I am going to tag this to query the scope, meaning that the editorial board will be pinged to make sure this is in scope for JOSS, the main question being the size since this is relatively small. This should take 1-2 weeks. Thank you for your patience.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
@KristianNelson The JOSS editorial board reviewed your submission and found that it does meet our standards to proceed to review—unfortunately, we have low editor availability in this area right now, and so I have to put this on a waitlist until an appropriate editor becomes available.

**Comment by KristianNelson** [comment]
@kyleniemeyer Sounds great! Thank you so much.

**Comment by kthyng** [comment]
@KristinaRiemer could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @KristinaRiemer as editor

**Comment by whedon** [comment]
@KristinaRiemer has been invited to edit this submission.

**Comment by KristinaRiemer** [comment]
I can take on this submission.

**Comment by KristinaRiemer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @KristinaRiemer

**Comment by KristinaRiemer** [comment]
@whedon assign @jsta as reviewer

**Comment by KristinaRiemer** [comment]
@whedon add @fsanchez-trigueros as reviewer

**Comment by whedon** [comment]
OK, @fsanchez-trigueros is now a reviewer

**Comment by KristinaRiemer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3383.

**Comment by KristinaRiemer** [comment]
Hi @jsta and @fsanchez-trigueros, thank you again for agreeing to review this JOSS submission! The review will happen in the GitHub issue linked to in the above comment, so go over there and check out the guidelines for reviewing and the checklist. Feel free to create issues for the submission author @KristianNelson in the software repo and comment in the review issue. And let me know if you have questions or need anything over there!

**Comment by KristinaRiemer** [comment]
@kthyn I'm not sure what happened here, but it doesn't look like @jsta was included as a reviewer in the review issue? I think I assigned the reviewers correctly?

**Comment by danielskatz** [comment]
For some reason, @whedon didn't respond to that request. We can fix it in the review issue, which I'll go ahead and do

**Comment by danielskatz** [comment]
ok, it's now fixed - let @openjournals/joss-eics know (in the review issue) if there is any further issue
