### ISSUE TITLE
[PRE REVIEW]: Visually comparing climate model output with observations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#326]
**Submitting author:** @mvhulten (<a href="http://orcid.org/0000-0002-3045-4949">Marco van Hulten</a>)
**Repository:** <a href="https://savannah.nongnu.org/projects/complot/" target ="_blank">https://savannah.nongnu.org/projects/complot/</a>
**Version:** 0.1
**Editor:** @lheagy
**Reviewer:** @AnsleyManke

**Author instructions**

Thanks for submitting your paper to JOSS @mvhulten. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mvhulten if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@lheagy might this be a suitable submission for you to take on?

**Comment by lheagy** [comment]
@kyleniemeyer: I have never worked with Ferret, the language they are scripting in, however, I do think I can help find some suitable reviewers for this.

**Comment by kyleniemeyer** [comment]
@lheagy sounds good! I'll go ahead and give it to you then (though in the future feel free to assign yourself).

@whedon assign @lheagy as editor

**Comment by kyleniemeyer** [comment]
Hmm, not sure why that didn't work...

**Comment by kyleniemeyer** [comment]
@whedon assign @lheagy as editor

**Comment by whedon** [comment]
OK, the editor is @lheagy

**Comment by lheagy** [comment]
Thank you for your submission @mvhulten. 

Before we start looking for reviewers, could you please include a paper.md in the repository? This should include an description of the software, provide some context and a statement of need (eg. http://joss.theoj.org/papers/b3adbbf7df62f4e427f19e99e70163f5).  

Additionally, the site https://savannah.nongnu.org/projects/complot/ is a bit challenging to navigate. Would it be possible to also include links to the paper.md and source code in the description of the package? 

Please let me know if you have any questions!

**Comment by mvhulten** [comment]
Thank you for accepting my paper for review!
I will respond more extensively later on, but I will quickly respond to @lheagy.

I tried to make a README.md that could be used as the paper.  Maybe it is better to create a separate paper.md?  Otherwise, I could symlink README.md to paper.md.

The repository is here: http://hg.savannah.nongnu.org/hgweb/complot/
Is it sufficient to add this to the paper.md?  I was thinking about creating a decent website (served on the same location).

**Comment by lheagy** [comment]
Thanks @mvhulten, if you could please add a paper.md, that would make it more clear for both myself and the reviewers. Any references can be included as a bibtex file (paper.bib). For an example, see: https://github.com/arfon/fidgit/tree/master/paper 

Upgrading the website would help elevate the usability of the project. Is this something you would like to do prior to engaging with reviewers? It would be a great opportunity to get feedback on a new website. This is not required, so please let me know what you would like to do!

**Comment by kyleniemeyer** [comment]
@mvhulten to add to what  @lheagy said, JOSS *requires* an article, including references. Please see the [author guidelines](http://joss.theoj.org/about#author_guidelines) for a description of what is required in this. 

The article does not serve the same purpose as a README, but should be a 250–1000 word high-level description of the software, including a statement of need and description of the software functionality. For example, see http://dx.doi.org/10.21105/joss.00301 and https://doi.org/10.21105/joss.00031 for good examples.

**Comment by mvhulten** [comment]
I am preparing the paper according to the guidelines.

I am not sure in what time frame I will have a proper website for *ComPlot*, so probably it is better to start the review without it (when I reply here with the info that I included a paper.md).

**Comment by mvhulten** [comment]
I have added a `paper.md`.  As far as I am concerned, you may start with the review.

In the meanwhile I did think of several people who are qualified to do the review:

 - Anne Mouchet <anne.mouchet AT lsce.ipsl.fr>
 - Patrick Brockmann <patrick.brockmann AT lsce.ipsl.fr>
 - Ansley Manke <ansley.b.manke AT noaa.gov>

My colleagues at LSCE are heavy users of Ferret.
Ferret is developed at NOAA.  Ansley is one of its main developers.

**Comment by lheagy** [comment]
Thanks @mvhulten. Of the reviewers that you have suggested, are they at arms length of the project, particularly those who are at the same institution as you? (eg. they are not currently contributors or currently providing you with feedback on ComPlot).

I do have a couple more requests prior to sending it for review: 

- It is not necessarily obvious how to navigate from the main website to the location of the paper.md. Could you please add a link from the main page to where we can view the source code at:   http://hg.savannah.nongnu.org/hgweb/complot/file/cbda29db682d. (At a minimum, instructions on how to navigate to the source-code should be stated in the main description of the package). Alternatively, if you would be open to putting the code up on github, it is widely used and the navigation is familiar for many. 
![image](https://user-images.githubusercontent.com/6361812/28601803-f4a8e71a-71ec-11e7-8240-4ca7e3005d9a.png)

- One comment regarding scope: the downloading instructions in the `# Availability` section are more suited for a README than the article. If you would still like to include a statement pointing readers to instructions for downloading the software, I would recommend putting it at the end of the article similar to what is done in: http://joss.theoj.org/papers/10.21105/joss.00031.

- I did not see the `paper.bib` in the repository. Could you please ensure it is included in the repository. 

Thanks and please let me know if I can clarify any of these comments.

**Comment by mvhulten** [comment]
Thanks @lheagy.

LSCE is my previous institute.  I did discuss with Patrick technical details, but not really about the package structure.  The same is true for Ansley.  Anne was just interested and did not provide any input to the package.  Right now I am at the University of Bergen.  In any case, they are not currently contributors or currently providing you with feedback on ComPlot.

I added the link to the source code on the project page.

I moved the availability section and added `paper.bib` (thanks for noticing!).

**Comment by mvhulten** [comment]
To be a bit more clear: nobody of my suggested reviewers had direct input into ComPlot.  Patrick and Ansley helped me, as many more people, with technical Ferret issues.

Savannah was a conscious choice.  Moreover, it might be a good idea to try to keep JOSS hosting service (and version control system) agnostic.  I am hoping this will work out.

**Comment by lheagy** [comment]
Thanks @mvhulten! I will start reaching out to reviewers

**Comment by lheagy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by lheagy** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by lheagy** [comment]
@mvhulten: sorry for the delayed update. Here is a quick overview on where we are at with reviewers. 

I have heard back from Ansley and she is willing to review. I sent a follow up email asking her to sign up for github so we can get the ball rolling and got a vacation responder from her, so I will follow up again first thing next week. 

Anne has declined to review and I am still waiting to hear back from Patrick. Feel free to also reach out to Patrick to ask if he is willing to review. I sent one follow up email to him and will also try again next week. If we don't hear back from him, we can start asking reviewers from the JOSS list.

**Comment by mvhulten** [comment]
Thank you @lheagy for the status update.

I approached another couple of people for review, but received no positive response so far.  Please, go ahead with the JOSS list.

**Comment by lheagy** [comment]
@jsta, @pboesu have either of you worked with Ferret? Would you be willing to review this submission?

**Comment by lheagy** [comment]
Thanks @AnsleyManke for volunteering to review. Ideally, we will find at least one more reviewer to help out as well.

**Comment by lheagy** [comment]
@whedon assign @AnsleyManke as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @AnsleyManke

**Comment by lheagy** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by lheagy** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/368. Feel free to close this issue now!

**Comment by pboesu** [comment]
@lheagy While I have a background in biological oceanography, I unfortunately I don't have any experience with Ferret and only limited experience with python, so I'd be hesitant to review this contribution, unless you think a review of a "naive user" would be of use.

**Comment by lheagy** [comment]
Thanks @pboesu, no problem. @AnsleyManke is a involved with the Ferret project and has agreed to review, so I think we are in good shape.
