### ISSUE TITLE
[PRE REVIEW]: flux-data-qaqc: A Python Package for Energy Balance Closure and Post-Processing of Eddy Flux Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3261]
**Submitting author:** @JohnVolk (<a href="http://orcid.org/0000-0001-9994-1545">John Volk</a>)
**Repository:** <a href="https://github.com/Open-ET/flux-data-qaqc" target ="_blank">https://github.com/Open-ET/flux-data-qaqc</a>
**Version:** 0.1.5
**Editor:** @pdebuyl
**Reviewers:** @ashwinvis, @dgketchum
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @JohnVolk. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@JohnVolk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=3.05 s (20.7 files/s, 5871.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           7            590           1635           2868
reStructuredText                10            688            709           1700
HTML                            31           1020              0           1596
INI                              5             39              0            489
Jupyter Notebook                 2              0           5892            227
TeX                              1             14              0            158
Markdown                         1             20              0             73
JavaScript                       2              9             18             60
DOS Batch                        1              8              1             26
CSS                              1              1              1             19
YAML                             1              0              0             15
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                            63           2393           8262           7240
-------------------------------------------------------------------------------


Statistical information for the repository '68b7eeb6f3dfc321563248d4' was
gathered on 2021/05/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christian Dunkerly              11          1195            468           13.21
David Ketchum                    1             1              1            0.02
John Volk                      104          7684           3238           86.77

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Christian Dunkerly           40            3.3         23.7               22.50
David Ketchum                 1          100.0          5.6                0.00
John Volk                  5139           66.9         18.5               11.31
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5194/bg-15-5015-2018 is OK
- 10.1061/9780784408056 is OK
- 10.1175/1520-0477(2001)082<2415:FANTTS>2.3.CO;2 is OK
- 10.5281/zenodo.3831489 is OK
- 10.1038/s41597-020-0534-3 is OK

MISSING DOIs

- 10.2307/1941631 may be a valid DOI for title: Measuring biosphere-atmosphere exchanges of biologically related gases with micrometeorological methods

INVALID DOIs

- https://doi.org/10.1016/j.agrformet.2011.12.002 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1890/06-0922.1 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/joc.3413 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0168-1923(02)00109-0 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.agrformet.2012.11.004 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03261/joss.03261/10.21105.joss.03261.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03261/joss.03261/10.21105.joss.03261.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @JohnVolk and thanks for your submission. Unfortunately we have a backlog of submissions in this area and our editors are currently overburdened, so I am adding you to the waitlist. Thank you for your patience!

**Comment by JohnVolk** [comment]
Hi @kthyng thank you, actually my suggested reviewer was supposed to be "usethedata" but I think when I refreshed the page perhaps it defaulted back to "Kevin-Mattheus-Moerman".  After reviewing the list here are other potential reviewers based on their domains: 

kramea, tacaswell, desilinguist, Mankoff, amoeba, krother, sgrieve, Chilipp, molgor, josephhardinee, dhhagan, wholmgren, ethan-nelson, rchg, simonom, rabernat, znicholls, kgoebber, ashwinvis, apalarcon

Hope that helps!

**Comment by kthyng** [comment]
Hi @JohnVolk. The list of reviewers will be helpful once this is picked up by an editor, thanks!

**Comment by kthyng** [comment]
@pdebuyl could you take on this submission?

**Comment by kthyng** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
Hi @JohnVolk I will start looking for reviewers next week. Thank you for providing recommendations.

**Comment by JohnVolk** [comment]
Thank you!

**Comment by pdebuyl** [comment]
@ashwinvis @rabernat would you review the article "flux-data-qaqc: A Python Package for Energy Balance Closure and Post-Processing of Eddy Flux Data" for the Journal of Open Source Software ?

**Comment by ashwinvis** [comment]
@pdebuyl I am willing to review this, but since I am on vacation, realistically the earliest I can complete review would be the end of August.

**Comment by pdebuyl** [comment]
@ashwinvis thank you for the reply. Many of our reviewers have timing issues since a year so I'll take your offer!

**Comment by rabernat** [comment]
I am in the same boat. I just left for a vacation. I'm very sorry but I have to decline.

**Comment by pdebuyl** [comment]
Hi @rabernat thank you for replying! Consider unsubscribing from this issue to avoid receiving further notifications.

**Comment by pdebuyl** [comment]
@dgketchum would you review the article "flux-data-qaqc: A Python Package for Energy Balance Closure and Post-Processing of Eddy Flux Data" for the Journal of Open Source Software ?

**Comment by dgketchum** [comment]
@pdebuyl Yes I will.

**Comment by pdebuyl** [comment]
Thank you @dgketchum !

**Comment by JohnVolk** [comment]
Thank you all!

**Comment by pdebuyl** [comment]
@whedon set @ashwinvis as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by pdebuyl** [comment]
@whedon assign @ashwinvis as reviewer

**Comment by whedon** [comment]
OK, @ashwinvis is now a reviewer

**Comment by pdebuyl** [comment]
@whedon add @dgketchum as reviewer

**Comment by whedon** [comment]
OK, @dgketchum is now a reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3418.
