### ISSUE TITLE
[PRE REVIEW]: demographicx: A Python package for estimating gender and ethnicity using deep learning transformers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3263]
**Submitting author:** @daniel-acuna (<a href="http://orcid.org/0000-0002-7765-1595">Daniel E. Acuna</a>)
**Repository:** <a href="https://github.com/sciosci/demographicx" target ="_blank">https://github.com/sciosci/demographicx</a>
**Version:** 0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @daniel-acuna. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @arokem.

@daniel-acuna if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (30.9 files/s, 1400.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2             35              0            104
Python                           4             19              0             73
TeX                              1             15              4             67
-------------------------------------------------------------------------------
SUM:                             7             69              4            244
-------------------------------------------------------------------------------


Statistical information for the repository '4d935abc62743a737b8ea263' was
gathered on 2021/05/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel Acuna                     1            62             33           45.67
LiamLiang                        3            79             16           45.67
jim                              4             9              9            8.65

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel Acuna                 62          100.0          0.0                0.00
LiamLiang                    26           32.9          0.1                0.00
jim                           4           44.4          0.0                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.13012/B2IDB-9087546_V1 is OK

MISSING DOIs

- 10.31219/osf.io/ybfk6 may be a valid DOI for title: Some considerations for studying gender, mentorship, and scientific impact: commentary on AlShebli, Makovi, and Rahwan (2020)
- 10.1145/1557019.1557032 may be a valid DOI for title: Name-ethnicity classification from open sources
- 10.1126/science.1196783 may be a valid DOI for title: Race, ethnicity, and NIH research awards
- 10.1038/504211a may be a valid DOI for title: Bibliometrics: Global gender disparities in science

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03263/joss.03263/10.21105.joss.03263.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03263/joss.03263/10.21105.joss.03263.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @daniel-acuna and thanks for your submission. Unfortunately, it is too small to be in scope for JOSS. Please read through our guidelines for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). Though the number of lines of code is not a perfect metric by which to judge software, we have decided that <300 lines of code is too few to consider. You are welcome to resubmit in the future with a larger software package.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
