### ISSUE TITLE
[PRE REVIEW]: PyOMA: A Python module for Operational Modal Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3264]
**Submitting author:** @dagghe (<a href="http://orcid.org/0000-0002-3830-2835">Dag</a>)
**Repository:** <a href="https://github.com/dagghe/PyOMA" target ="_blank">https://github.com/dagghe/PyOMA</a>
**Version:** v.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @dagghe. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@dagghe if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (52.8 files/s, 16761.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            442            647           1151
Markdown                         4            213              0            503
SVG                              2              0              2            366
TeX                              1             18              0            152
-------------------------------------------------------------------------------
SUM:                            11            673            649           2172
-------------------------------------------------------------------------------


Statistical information for the repository 'fc54b8dc3fe499aa5f02ea71' was
gathered on 2021/05/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
dag                              4           161              8           17.70
dagghe                           4           393            167           58.64
lollix91                         5           142             84           23.66

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
dag                        2193         1362.1          0.1               17.15
lollix91                     47           33.1          3.0               36.17
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1088/0964-1726/10/3/303 may be a valid DOI for title: Modal identification of output-only systems using frequency domain decomposition
- 10.1006/mssp.1999.1249 may be a valid DOI for title: Reference-based stochastic subspace identification for output-only modal analysis
- 10.1007/978-1-4939-0767-0 may be a valid DOI for title: Operational modal analysis of civil engineering structures
- 10.1016/j.ymssp.2009.10.024 may be a valid DOI for title: A frequency–spatial domain decomposition (FSDD) method for operational modal analysis
- 10.1016/j.conbuildmat.2020.121069 may be a valid DOI for title: Two-years static and dynamic monitoring of the santa maria di collemaggio basilica
- 10.1080/15583058.2020.1836531 may be a valid DOI for title: Assessment of seismic retrofitting interventions of a masonry palace using operational modal analysis
- 10.1080/15732479.2020.1731559 may be a valid DOI for title: Assessment of structural interventions using Bayesian updating and subspace-based fault detection methods: The case study of S. Maria di Collemaggio basilica, L’Aquila, Italy
- 10.1080/15732479.2020.1819343 may be a valid DOI for title: Bayesian estimate of the elastic modulus of concrete box girders from dynamic identification: A statistical framework for the A24 motorway in Italy
- 10.3390/app10124289 may be a valid DOI for title: Identification and model update of the dynamic properties of the san silvestro belfry in l’aquila and estimation of bell’s dynamic actions
- 10.1080/15583058.2020.1802533 may be a valid DOI for title: The recorded seismic response of the Santa Maria di Collemaggio basilica to low-intensity earthquakes
- 10.1016/j.conbuildmat.2020.120146 may be a valid DOI for title: Dynamic identification and model updating of full-scale concrete box girders based on the experimental torsional response
- 10.1016/j.engstruct.2020.110619 may be a valid DOI for title: Time-domain identification of the elastic modulus of simply supported box girders under moving loads: Method and full-scale validation
- 10.3390/buildings11030120 may be a valid DOI for title: Operational Modal Analysis, Model Update and Fragility Curves Estimation, through Truncated Incremental Dynamic Analysis, of a Masonry Belfry

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03264/joss.03264/10.21105.joss.03264.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03264/joss.03264/10.21105.joss.03264.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @dagghe and thanks for your submission! I have applied the "query-scope" label which pings our editorial board to make sure that this submission is in scope. I did this because it's on the small size. This process should take 1-2 weeks. Thanks for your patience!

**Comment by arfon** [comment]
:wave: @dagghe - thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
