### ISSUE TITLE
[REVIEW]: MCALF: Multi-Component Atmospheric Line Fitting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3265]
**Submitting author:** @ConorMacBride (<a href="http://orcid.org/0000-0002-9901-8723">Conor MacBride</a>)
**Repository:** <a href="https://github.com/ConorMacBride/mcalf" target ="_blank">https://github.com/ConorMacBride/mcalf</a>
**Version:** v0.2.1
**Editor:** @mbobra
**Reviewer:** @mgalloy, @Goobley
**Archive:** <a href="https://doi.org/10.5281/zenodo.4767888" target="_blank">10.5281/zenodo.4767888</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5ce964a3bf717a8961a688c25ba0edf1/status.svg)](https://joss.theoj.org/papers/5ce964a3bf717a8961a688c25ba0edf1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5ce964a3bf717a8961a688c25ba0edf1"><img src="https://joss.theoj.org/papers/5ce964a3bf717a8961a688c25ba0edf1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5ce964a3bf717a8961a688c25ba0edf1/status.svg)](https://joss.theoj.org/papers/5ce964a3bf717a8961a688c25ba0edf1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ConorMacBride/mcalf" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mgalloy & @Goobley, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mbobra know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ConorMacBride/mcalf">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ConorMacBride) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ConorMacBride/mcalf">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ConorMacBride) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mgalloy, @Goobley it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637x/795/1/9 is OK
- 10.1098/rsta.2020.0216 is OK
- 10.1098/rsta.2020.0171 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.33 s (230.9 files/s, 28064.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          39           1452           2530           3122
reStructuredText                17            191            119            488
YAML                             7             25             31            185
Jupyter Notebook                 3              0            721            167
JSON                             2              1              0             86
INI                              1              3              0             41
Markdown                         1             13              0             39
TeX                              1              3              0             39
DOS Batch                        1              8              1             26
IDL                              1              7              8             17
make                             1              4              7              9
C                                2              2              0              8
TOML                             1              1              0              7
-------------------------------------------------------------------------------
SUM:                            77           1710           3417           4234
-------------------------------------------------------------------------------


Statistical information for the repository 'd465bd3f5c3275a54ef68dd5' was
gathered on 2021/05/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Conor MacBride                 117          9542           2428          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Conor MacBride             7114           74.6          1.9               14.04
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03265/joss.03265/10.21105.joss.03265.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03265/joss.03265/10.21105.joss.03265.pdf) :page_facing_up: :point_left:

**Comment by Goobley** [comment]
I am quite happy with this software, the level of documentation is excellent (and automated tests are included); the code appears to work well and do "what it says on the tin".

My primary comment has been opened as an issue on the repository (ConorMacBride/mcalf#29): 
 - It isn't possible to simply run the examples expecting real data, providing a small amount of this, so that the software can easily be tested on real data (with noise etc), would be very welcomed. Currently I can play with the software using generated profiles, but I can't see if there are difficulties with real data. This would also easily allow testing the parallelisation.

Other points:
- "State of the field", I am not aware of any other packages that propose a toolkit/framework like approach to this problem, or even of automated classification _prior_ to fitting. If this is indeed novel, I would like to see a passing reference to this, explaining why no other software is mentioned with respect to these tasks. 
In terms of classification of spectra, Panos et al (doi: 10.3847/1538-4357/aac779) were (to my knowledge) the first to perform autmated spectral classification using machine learning, and whilst k-means was used instead of an MLP, this seems worth mentioning as clustering onto labelled representative profiles could also be used for the classification step.

Overall, I am happy with this work, and would just like to see these minor points addressed.

**Comment by mgalloy** [comment]
I would also like to see some data available so that the example notebooks can be executed as is, i.e., the notebook could download the example data from a website if needed. This would make the example notebooks much more useful for new users and demonstrate their capabilities without having to find appropriate data.

**Comment by ConorMacBride** [comment]
Thank you @mgalloy and @Goobley for reviewing, and for doing so quickly. Much appreciated.

@Goobley, I've replied in your issue about including example data — I'll check the licence compatibility and include (or link to) a file with some real data. Since the v0.2.0 release, I've added one more example which is in the "latest" documentation (https://mcalf.macbride.me/en/latest/gallery/models/plot_ibis8542model.html), although it is running with randomly generated data.

Regarding "state of field", we are not aware of other similar packages either. I'll update the paper to highlight that it is a novel method. I'll also have a look at Panos et al. (and similar) and include this. I'll provide an update here when I do that.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637x/795/1/9 is OK
- 10.1098/rsta.2020.0216 is OK
- 10.1098/rsta.2020.0171 is OK
- 10.3847/1538-4357/aac779 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ConorMacBride** [comment]
Hi @mgalloy and @Goobley, I've now added real IBIS data to the repository and updated `LabellingTutorial.ipynb` so it runs as-is with this data. Instead of updating the now mostly redundant `FittingIBIS.ipynb`, I've created a new (more user friendly) gallery example (https://mcalf.macbride.me/en/latest/gallery/models/plot_ibis8542data.html) which covers most of what `FittingIBIS.ipynb` did. This gallery example can also be downloaded and run as-is. I've left a comment in issue https://github.com/ConorMacBride/mcalf/issues/29 with more details. Let me know if you're happy with how I implemented your requests, or if you'd like anything changed. Thanks!

**Comment by mgalloy** [comment]
I really like the new gallery example at https://mcalf.macbride.me/en/latest/gallery/models/plot_ibis8542data.html.

**Comment by mgalloy** [comment]
One last thing for me: you mention in the paper the ability to parallelize the code. I don't see anything built into you code to do this (or am I missing it?).

**Comment by ConorMacBride** [comment]
Hi @mgalloy, the `IBIS8542Model.fit` method (https://mcalf.macbride.me/en/latest/api/mcalf.models.IBIS8542Model.html#mcalf.models.IBIS8542Model.fit) has an `n_pools` parameter that distributes the list of spectra to fit between a number of parallel processing pools. By default, the spectra are fitted on a single process.

**Comment by mgalloy** [comment]
OK, I played around with that a bit and the scaling does look very good. I have checked off all the items on my checklist. My review is complete.

**Comment by Goobley** [comment]
I'm happy with all of this now!

**Comment by ConorMacBride** [comment]
Thanks @mgalloy and @Goobley for your valuable feedback on this software, helping to improve its quality. The issue (https://github.com/ConorMacBride/mcalf/issues/29) has now been resolved and closed, and it looks like both checklists are now complete @mbobra.

**Comment by mbobra** [comment]
@ConorMacBride Thanks! Could you please cut a new release of MCALF and [deposit it in Zenodo](https://guides.github.com/activities/citable-code/)? Please make sure that the author list and title on the Zenodo deposit matches the author list and title on the JOSS paper. Then I can move forward with accepting the paper.

**Comment by ConorMacBride** [comment]
Hi @mbobra, excellent! I've now created a new release ([MCALF v0.2.1](https://github.com/ConorMacBride/mcalf/releases/tag/v0.2.1)) and a new version in Zenodo ([10.5281/zenodo.4767888](http://doi.org/10.5281/zenodo.4767888)). Thanks!

**Comment by mbobra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03265/joss.03265/10.21105.joss.03265.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03265/joss.03265/10.21105.joss.03265.pdf) :page_facing_up: :point_left:

**Comment by mbobra** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637x/795/1/9 is OK
- 10.1098/rsta.2020.0216 is OK
- 10.1098/rsta.2020.0171 is OK
- 10.3847/1538-4357/aac779 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mbobra** [comment]
@whedon set 10.5281/zenodo.4767888 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4767888" target="_blank">10.5281/zenodo.4767888</a> is the archive.

**Comment by mbobra** [comment]
@whedon set v0.2.1 as version

**Comment by whedon** [comment]
OK. v0.2.1 is the version.

**Comment by mbobra** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0004-637x/795/1/9 is OK
- 10.1098/rsta.2020.0216 is OK
- 10.1098/rsta.2020.0171 is OK
- 10.3847/1538-4357/aac779 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2313

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2313, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by mbobra** [comment]
@openjournals/joss-eics This paper is ready for final processing.

@ConorMacBride Thank you for your submission!

@mgalloy @Goobley Thank you both so very much for your thorough and speedy reviews! Your volunteer time keeps JOSS running and I really appreciate it! ☀️

**Comment by kyleniemeyer** [comment]
@ConorMacBride Hi there, I'm the AEIC on duty this week doing some final checks before publishing.

I only noticed a very minor issue: in the Panos et al. reference, it looks like some of the words in the title need to be wrapped with `{}` to preserve capitalization. Could you fix that and let me know?

**Comment by ConorMacBride** [comment]
Hi @kyleniemeyer, I'll fix that now. Should I also preserve the all-caps title in Felipe et al. (https://doi.org/10.1088/0004-637x/795/1/9)?

**Comment by kyleniemeyer** [comment]
@ConorMacBride no, only words that should actually be capitalized in a regular sentence, I think.

**Comment by ConorMacBride** [comment]
Thanks @kyleniemeyer. I've now merged a PR (https://github.com/ConorMacBride/mcalf/pull/35) which keeps the `Mg` capitalised and sets the `ii` to small caps.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03265/joss.03265/10.21105.joss.03265.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03265/joss.03265/10.21105.joss.03265.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1394400639220846594) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2315
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03265](https://doi.org/10.21105/joss.03265)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congrats @ConorMacBride on your article's publication in JOSS!

Many thanks to @mgalloy and @Goobley for reviewing this, and @mbobra for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03265/status.svg)](https://doi.org/10.21105/joss.03265)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03265">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03265/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03265/status.svg
   :target: https://doi.org/10.21105/joss.03265
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03265/status.svg)](https://doi.org/10.21105/joss.03265)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by ConorMacBride** [comment]
Thank you @mgalloy, @Goobley, @mbobra, and @kyleniemeyer for your work on this submission, and for all of your useful feedback. Much appreciated! 🎉
