### ISSUE TITLE
[PRE REVIEW]: JMcDM: A Julia package for multiple-criteria decision-making tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3266]
**Submitting author:** @jbytecode (<a href="http://orcid.org/0000-0002-9402-1982">Mehmet Hakan Satman</a>)
**Repository:** <a href="https://github.com/jbytecode/JMcDM" target ="_blank">https://github.com/jbytecode/JMcDM</a>
**Version:** v0.1.8
**Editor:** @drvinceknight
**Reviewers:** @brunaw, @sylvaticus
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @jbytecode. **Currently, there isn't an JOSS editor assigned** to your paper.

@jbytecode if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (697.1 files/s, 114970.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           30           1379            167           4300
TOML                             4            134              2            548
Markdown                         8            128              0            385
TeX                              1             42              0            354
Lisp                             3            133              0            295
YAML                             2              1              0             49
-------------------------------------------------------------------------------
SUM:                            48           1817            169           5931
-------------------------------------------------------------------------------


Statistical information for the repository 'caa711664c3d0895a2a03db9' was
gathered on 2021/05/09.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/4235.996017 is OK
- 10.1016/j.softx.2019.02.004 is OK
- 10.1109/ieem.2009.5373124 is OK
- 10.1002/9780470400531.eorms0970 is OK
- 10.1016/s2212-5671(14)00342-6 is OK
- 10.1007/978-3-319-06647-9 is OK
- 10.1137/141000671 is OK
- 10.1007/978-3-642-48318-9_3 is OK
- 10.1111/1467-8667.00269 is OK
- 10.1016/0022-2496(77)90033-5 is OK
- 10.1016/s0167-6911(82)80025-x is OK
- 10.1016/0167-9236(89)90037-7 is OK
- 10.1287/opre.2.2.172 is OK
- 10.5755/j01.eee.122.6.1810 is OK
- 10.15388/informatica.2015.57 is OK
- 10.1016/j.eswa.2014.11.057 is OK
- 10.1016/j.cie.2019.106231 is OK
- 10.1108/md-05-2017-0458 is OK
- 10.1016/0305-0548(94)00059-h is OK
- 10.1002/j.1538-7305.1948.tb01338.x is OK
- 10.1016/0377-2217(78)90138-8 is OK

MISSING DOIs

- 10.1051/ro/196802v100571 may be a valid DOI for title: Classement et choix en présence de points de vue multiples

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03266/joss.03266/10.21105.joss.03266.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03266/joss.03266/10.21105.joss.03266.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@jbytecode - thanks for your submission to JOSS. We're currently working through a backlog of submissions so I'm marking yours as _waitlisted_ for now. We'll assign an editor to handle your paper as and when a suitable editor becomes available. Thanks for your patience!

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/4235.996017 is OK
- 10.1016/j.softx.2019.02.004 is OK
- 10.1109/ieem.2009.5373124 is OK
- 10.1002/9780470400531.eorms0970 is OK
- 10.1016/s2212-5671(14)00342-6 is OK
- 10.1007/978-3-319-06647-9 is OK
- 10.1137/141000671 is OK
- 10.1007/978-3-642-48318-9_3 is OK
- 10.1051/ro/196802v100571 is OK
- 10.1111/1467-8667.00269 is OK
- 10.1016/0022-2496(77)90033-5 is OK
- 10.1016/s0167-6911(82)80025-x is OK
- 10.1016/0167-9236(89)90037-7 is OK
- 10.1287/opre.2.2.172 is OK
- 10.5755/j01.eee.122.6.1810 is OK
- 10.15388/informatica.2015.57 is OK
- 10.1016/j.eswa.2014.11.057 is OK
- 10.1016/j.cie.2019.106231 is OK
- 10.1108/md-05-2017-0458 is OK
- 10.1016/0305-0548(94)00059-h is OK
- 10.1002/j.1538-7305.1948.tb01338.x is OK
- 10.1016/0377-2217(78)90138-8 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03266/joss.03266/10.21105.joss.03266.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03266/joss.03266/10.21105.joss.03266.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @drvinceknight as editor

Hi @drvinceknight, could you edit this? I *think* this seems somewhat close to your areas.

**Comment by whedon** [comment]
@drvinceknight has been invited to edit this submission.

**Comment by jbytecode** [comment]
@kyleniemeyer The invited editor's notifications may be turned off.

**Comment by drvinceknight** [comment]
> @kyleniemeyer The invited editor's notifications may be turned off.

Not quite turned off but overflowing 😆 Apologies for my delay on this, I'll happily take it on.

**Comment by drvinceknight** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
@jbytecode thanks again for the submission and my apologies for the delay, if you have not already done so, could you  take a look through https://bit.ly/joss-reviewers to suggest some potential reviewers.

**Comment by jbytecode** [comment]
Dear editor @drvinceknight 

I am listing some potential reviewers (from bottom of the list) with their research areas. Julia is in their preferred or other language list.

bonh: numerical mathematics
AvianaGlobal: statistics and economics
degleris1: optimization and statistics
brunaw: statistics
sylvaticus: social sciences
salleuska: statistics and optimization
mvaldes: optimization and numerical methods
ayushpatnaikgit: statistics
jbcaillau: optimization
justinsgray: numerical optimization

**Comment by drvinceknight** [comment]
That's very helpful, thank you.

**Comment by drvinceknight** [comment]
@bonh @AvianaGlobal @degleris1 @brunaw I'm pinging you to ask if you would be able to assist with reviewing this submissions to JOSS (The Journal of Open Source Software). 

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "JMcDM: A Julia package for multiple-criteria decision-making tools". You can find more information at the top of this Github issue.

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by bonh** [comment]
Hi @drvinceknight! I would very much like to review this submission. However, I feel obligated to bring to your attention, that in April I reviewed another JOSS submission during which I asked for an editorial scope check. Afterwards the editor and I decided to remove myself from the review process due to insufficient knowledge in the specific field of that submission. Unfortunately, the submission is still flagged for editorial review - so it is not done yet and I feel uncomfortable to start another review while that one still lingers around. My point is, that I might not have the heart to ask for another scope check (or some other editorial stuff) during the review of this submission even if I feel it might be needed - after all we all do this on the side and I greatly appreciate the work of the editors! I hope you get what I mean.

**Comment by brunaw** [comment]
@drvinceknight  happy to review if I'm allowed to start in about 7-10 days

**Comment by drvinceknight** [comment]
> @drvinceknight happy to review if I'm allowed to start in about 7-10 days

Thank you. Starting then is no problem at all.

**Comment by drvinceknight** [comment]
@whedon assign @brunaw as reviewer

**Comment by whedon** [comment]
OK, @brunaw is now a reviewer

**Comment by drvinceknight** [comment]
> Hi @drvinceknight! I would very much like to review this submission. However, I feel obligated to bring to your attention, that in April I reviewed another JOSS submission during which I asked for an editorial scope check. Afterwards the editor and I decided to remove myself from the review process due to insufficient knowledge in the specific field of that submission. Unfortunately, the submission is still flagged for editorial review - so it is not done yet and I feel uncomfortable to start another review while that one still lingers around. My point is, that I might not have the heart to ask for another scope check (or some other editorial stuff) during the review of this submission even if I feel it might be needed - after all we all do this on the side and I greatly appreciate the work of the editors! I hope you get what I mean.

Thank you @bonh for responding. No problem if you cannot review this submission. 

If you can let me know what the other review is I'll chase up to try and make sure it's not a problem for you.

**Comment by jbytecode** [comment]
@whedon generate pdf

sorry for bothering. I have made a small change for typo.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03266/joss.03266/10.21105.joss.03266.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03266/joss.03266/10.21105.joss.03266.pdf) :page_facing_up: :point_left:

**Comment by drvinceknight** [comment]
@sylvaticus @salleuska @mvaldes @ayushpatnaikgit I'm pinging you to ask if you would be able to assist with reviewing this submissions to JOSS (The Journal of Open Source Software).

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "JMcDM: A Julia package for multiple-criteria decision-making tools". You can find more information at the top of this Github issue.

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by sylvaticus** [comment]
Hello, I could do it, but I am confident only with a small subset of the methods implemented in the package.

**Comment by drvinceknight** [comment]
Thank you @sylvaticus, once you have completed what you can if I feel a further review is needed I can find one.

I'll go ahead and start the review now.

**Comment by drvinceknight** [comment]
@whedon add @sylvaticus as reviewer

**Comment by whedon** [comment]
OK, @sylvaticus is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3430.

**Comment by drvinceknight** [comment]
The review will now be taking place on #3430, there are various things documented there but if I can answer any questions please let me know.

**Comment by salleuska** [comment]
Hi @drvinceknight sorry for the late reply, I have been offline a few days. I think I'll have to pass on this, as I am not much confident with the methods!
