### ISSUE TITLE
[PRE REVIEW]: A C++17 Thread Pool for High-Performance Scientific Computing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3267]
**Submitting author:** @bshoshany (<a href="http://orcid.org/0000-0003-2222-127X">Barak Shoshany</a>)
**Repository:** <a href="https://github.com/bshoshany/thread-pool" target ="_blank">https://github.com/bshoshany/thread-pool</a>
**Version:** v1.5
**Editor:** @gkthiruvathukal
**Reviewers:** @zeroset, @cedricchevalier19
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @bshoshany. **Currently, there isn't an JOSS editor assigned** to your paper.

@bshoshany if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (24.1 files/s, 15248.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         1            161              0            605
C/C++ Header                     1             51            210            238
-------------------------------------------------------------------------------
SUM:                             2            212            210            843
-------------------------------------------------------------------------------


Statistical information for the repository 'f328173d849604b53668f58c' was
gathered on 2021/05/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Barak Shoshany                   6           583             84          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Barak Shoshany              499           85.6          0.0               42.08
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3267 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon query scope

@bshoshany - thanks for your submission to JOSS. As discussed in the earlier scope discussion in https://github.com/openjournals/joss/issues/918, this is a rather small submission for us so we will send this through our internal scope review.

This may take a couple of weeks to complete so thanks for your patience!

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03267/joss.03267/10.21105.joss.03267.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03267/joss.03267/10.21105.joss.03267.pdf) :page_facing_up: :point_left:

**Comment by bshoshany** [comment]
Thanks @arfon. Please let me know if there's anything you need from me at any point.

**Comment by arfon** [comment]
> Thanks @arfon. Please let me know if there's anything you need from me at any point.

Nope, sit tight for now please :-)

**Comment by jgostick** [comment]
Regarding the scope query, this was preemptively discussed [here](https://github.com/openjournals/joss/issues/918)

**Comment by danielskatz** [comment]
Right - thanks for pointing this out - I missed this one coming in

**Comment by danielskatz** [comment]
I'll remove the scope query label, since we already discussed it, and assign it (reluctantly) to @gkthiruvathukal, who volunteered in that earlier discussion

**Comment by danielskatz** [comment]
@whedon assign @gkthiruvathukal as editor

Thanks @gkthiruvathukal !!

**Comment by whedon** [comment]
OK, the editor is @gkthiruvathukal

**Comment by gkthiruvathukal** [comment]
My pleasure, @danielskatz! I know, I have my hands full, but the good news is that my semester is fully done so I can catch up.

**Comment by gkthiruvathukal** [comment]
@bshoshany Can you please suggest some potential reviewers from the list shared at the top of this issue thread?

**Comment by bshoshany** [comment]
@gkthiruvathukal Here are some potential reviewers who listed C++ as a preferred language and parallel programming as a topic they are comfortable reviewing:
* cedricchevalier19
* davidbeckingsale
* fcdimitr
* jpenuchot
* leonardojaneis
* pitsianis 
* RcSepp
* zeroset

**Comment by gkthiruvathukal** [comment]
@zeroset Are you willing to contribute a review for this JOSS submission?

**Comment by gkthiruvathukal** [comment]
@cedricchevalier19 Are you willing to contribute a review for this JOSS submission?

**Comment by zeroset** [comment]
Yes I am happy to review.

**Comment by gkthiruvathukal** [comment]
@whedon assign @zeroset as reviewer

**Comment by whedon** [comment]
OK, @zeroset is now a reviewer

**Comment by cedricchevalier19** [comment]
> @cedricchevalier19 Are you willing to contribute a review for this JOSS submission?

I will be happy to contribute too, if  necessary.

**Comment by gkthiruvathukal** [comment]
@whedon add @cedricchevalier19 as reviewer

**Comment by whedon** [comment]
OK, @cedricchevalier19 is now a reviewer

**Comment by gkthiruvathukal** [comment]
Thanks to both @zeroset and @cedricchevalier19 for responding so quickly. 
Starting review now!

**Comment by gkthiruvathukal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3291.
