### ISSUE TITLE
[PRE REVIEW]: neworder: a dynamic microsimulation framework for python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3268]
**Submitting author:** @virgesmith (<a href="http://orcid.org/0000-0002-9951-6642">Andrew Smith</a>)
**Repository:** <a href="https://github.com/virgesmith/neworder" target ="_blank">https://github.com/virgesmith/neworder</a>
**Version:** 0.3.0
**Editor:** @danielskatz
**Reviewers:** @platipodium, @tresoldi
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @virgesmith. **Currently, there isn't an JOSS editor assigned** to your paper.

@virgesmith if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-319-44663-9 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1002/nav.3800260304 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (612.4 files/s, 54176.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          67           1137           1324           3114
C++                             13            451            306           1819
Markdown                        27            979              2           1463
C/C++ Header                    14            262            142            632
YAML                             6             63             58            361
TeX                              1              9              0             86
HTML                             1             16              0             75
Bourne Shell                     7             25             16             45
XML                              2              0              0             40
TOML                             1              2              0             13
JavaScript                       1              0              0             12
Dockerfile                       1              8              3             11
-------------------------------------------------------------------------------
SUM:                           141           2952           1851           7671
-------------------------------------------------------------------------------


Statistical information for the repository '24bcd29d0d70216787ecb4c0' was
gathered on 2021/05/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrew Smith                    18          1265            760            4.04
virgesmith                     514         27857          20207           95.96

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
virgesmith                 8167           29.3         13.4               18.27
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3268 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by arfon** [comment]
@virgesmith - please fix your `paper.md` by adding a `date` field as @whedon suggests.

Also, I'm going to mark this submission as _waitlisted_ for now as we have a backlog of submissions which we're working through in the order that they were submitted.

**Comment by virgesmith** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03268/joss.03268/10.21105.joss.03268.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03268/joss.03268/10.21105.joss.03268.pdf) :page_facing_up: :point_left:

**Comment by virgesmith** [comment]
Some reviewer suggestions: zeroset, platipodium, tresoldi

**Comment by kthyng** [comment]
@virgesmith I can't quite tell what your submission is about in order to suggest an editor (to me, the words describing the work are generic and could be from many different fields). Do you have more editor suggestions? Also I see you describe the work as in pre-release — this can be a sign that the work is not ready to be published by JOSS. When do you plan to release version 1.0?

**Comment by virgesmith** [comment]
@kthyng it is rather generic, I'm afraid - the techniques* are commonly applied in social sciences, e.g. geography, demography, epidemiology, I've personally used it for demographic modelling and more recently criminology. But it can be applied to any application where modelling the evolution and interactions of individual entities is required. 

Re: editors I tried to pick social-scientists with C++ and python skills, but this combination is relatively rare so don't really have any other suggestions, sorry 

Regarding "pre-release" I should remove this now. It is a stable, tested, packaged and documented product. That is not to say that I have no plans to extend it. At the risk of complicating my response to your first question I intend to enhance its agent-based modelling capabilities in the medium term - there does seem to be a "gap in the market" for python-based ABM tools.

&ast; the terms microsimulation, agent-based modelling, individual-based modelling overlap hugely and are often used interchangably

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @virgesmith - if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by virgesmith** [comment]
Some reviewer suggestions: zeroset, platipodium, tresoldi

Also not sure why it's tagged python, shell, tex? C++, python would be more appropriate

**Comment by danielskatz** [comment]
I think that's just what code was found in the repo - don't worry about it

**Comment by danielskatz** [comment]
👋 @zeroset, @platipodium, @tresoldi - Would a couple of you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by platipodium** [comment]
I am happy to take on this review if you think I satisfy the definition of "social-scientists with C++ and python skills"

**Comment by danielskatz** [comment]
Thanks - Let's try and see how it works out.  I'll add you, but we won't start the review until we also find a second reviewer.

**Comment by platipodium** [comment]
> At the risk of complicating my response to your first question I intend to enhance its agent-based modelling capabilities in the medium term - there does seem to be a "gap in the market" for python-based ABM tools.

I certainly agree, there definitely is a gap in the market for python-based ABM tools.

**Comment by danielskatz** [comment]
@whedon assign @platipodium as reviewer

**Comment by whedon** [comment]
OK, @platipodium is now a reviewer

**Comment by platipodium** [comment]
> INVALID DOIs
> 
> - https://doi.org/10.1002/nav.3800260304 is INVALID because of 'https://doi.org/' prefix

Hey @whedon, I guess you forgot to update your doi rules, as the reference with https://doi.org/ is now the recommended way to cite DOis

**Comment by platipodium** [comment]
@arfon How can I update my reviewer profile in  this [list of people ](https://bit.ly/joss-reviewers) ?

**Comment by danielskatz** [comment]
> > INVALID DOIs
> > 
> > * https://doi.org/10.1002/nav.3800260304 is INVALID because of 'https://doi.org/' prefix
> 
> Hey @whedon, I guess you forgot to update your doi rules, as the reference with https://doi.org/ is now the recommended way to cite DOis

But this isn't how bibtex works - leave off the prefix in the bibtex entry, and it will be added back in the pandoc/tex processing

**Comment by zeroset** [comment]
> wave @zeroset, @platipodium, @tresoldi - Would a couple of you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Hi @danielskatz, unfortunately i already have another ongoing review and too less time. Sorry.

**Comment by danielskatz** [comment]
👋 @virgesmith - while we wait to hear back from tresoldi, do you have any other suggestions for people to try?  They don't have to be from our list, and they don't have be people on GitHub (though it's much easier if they are)

**Comment by tresoldi** [comment]
@danielskatz I have checked the code and the draft. The library seems robust and useful (I will probably consider it for a project we are just beginning to plan!) and I would be happy to take this review.

Note, however, that an ABM tool lies a bit too much outside my domains of expertise (historical linguistics and evolutionary studies in general, especially phylogenetics). While I am confident I can can review it as research software (usability, documentation, etc., Python & C++ code), we could probably find people better suited to judge its novelty, the state of the field, references, etc.

**Comment by platipodium** [comment]
@tresoldi 

> Note, however, that an ABM tool lies a bit too much outside my domains of expertise (historical linguistics and evolutionary studies in general, especially phylogenetics). While I am confident I can can review it as research software (usability, documentation, etc., Python & C++ code), we could probably find people better suited to judge its novelty, the state of the field, references, etc.

I am proficient in ABM modeling and applications, so we should make a good complementary reviewer team!

**Comment by tresoldi** [comment]
@platipodium perfect! If @danielskatz agrees, I see no reason not to proceed. :)

**Comment by danielskatz** [comment]
great, thanks - let's get started

**Comment by danielskatz** [comment]
@whedon add @tresoldi as reviewer

**Comment by whedon** [comment]
OK, @tresoldi is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3351.
