### ISSUE TITLE
[PRE REVIEW]: pySYD: Automated measurements of global asteroseismic parameters

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3269]
**Submitting author:** @ashleychontos (<a href="http://orcid.org/0000-0003-1125-2564">Ashley Chontos</a>)
**Repository:** <a href="https://github.com/ashleychontos/pySYD" target ="_blank">https://github.com/ashleychontos/pySYD</a>
**Version:** v0.7.5
**Editor:** @mbobra
**Reviewers:** @danhey, @benjaminpope
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @ashleychontos. **Currently, there isn't an JOSS editor assigned** to your paper.

@ashleychontos if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (438.4 files/s, 57527.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          10            416            890           1706
TeX                              1             21              0            402
reStructuredText                13            191            165            299
Markdown                         3             30              0            116
YAML                             3              0              0             34
DOS Batch                        1              8              1             26
make                             1              4              6              9
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            33            670           1062           2598
-------------------------------------------------------------------------------


Statistical information for the repository '1cd7785e0463e33f45a179b0' was
gathered on 2021/05/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ashley Chontos                 124         20822          19004           94.35
Maryum Sayeed                    9           275            105            0.90
Pavadol Yamsiri                  1          1233            261            3.54
danxhuber                        9           344            165            1.21

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ashley Chontos             3012           14.5          0.2               10.29
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/RevModPhys.93.015001 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1038/nature12419 is OK
- 10.1088/0067-0049/210/1/1 is OK
- 10.1051/0004-6361/201424181 is OK
- 10.1111/j.1365-2966.2009.16030.x is OK
- 10.1051/0004-6361/201015185 is OK
- 10.1088/0004-637X/743/2/143 is OK
- 10.1051/0004-6361/200913266 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1051/0004-6361/200912944 is OK
- 10.3847/1538-3881/abcd39 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.3847/1538-4365/aa97df is OK
- 10.1111/j.1365-2966.2011.18968.x is OK
- 10.1093/mnrasl/sly123 is OK

MISSING DOIs

- 10.1017/cbo9781139333696.004 may be a valid DOI for title: Solar-like oscillations: An observational perspective
- 10.1553/cia160s74 may be a valid DOI for title: Automated extraction of oscillation parameters for Kepler observations of solar-type stars

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03269/joss.03269/10.21105.joss.03269.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03269/joss.03269/10.21105.joss.03269.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @ashleychontos, thanks for your submission to JOSS. We have a reasonable number of submissions in our backlog right now so I'm going to mark this submission as _waitlisted_ until an editor with appropriate experience has time to take on this.

One thing you might want to work on while we're waiting to send this out for review is that I couldn't see any tests covering the functionality of the software. I would strongly encourage you to add a test suite for your package - this will almost certainly be flagged by any reviewers during the review process (https://joss.readthedocs.io/en/latest/review_criteria.html#tests)

**Comment by ashleychontos** [comment]
@arfon hello and thank your quick response with comments and suggestions! 

Re: the test suite: 
I have thought about adding a separate test feature (i.e. one that does not depend on input data, science, etc.), as it would also be helpful for folks interested in developing the software. We do have an example star (with output) available in the [documentation](https://pysyd.readthedocs.io/en/latest/quickstart.html#summary). We have additional examples [here](https://pysyd.readthedocs.io/en/latest/examples.html), including detailed descriptions about the output figures as well as how to interpret them. In your experience(s), do you think this would suffice or should we consider other options? Thank you again!

**Comment by arfon** [comment]
> We have additional examples here, including detailed descriptions about the output figures as well as how to interpret them. In your experience(s), do you think this would suffice or should we consider other options? 

I think these are helpful, but if I were reviewing this submission, I'd be looking for a way to verify the functionality of the files in [this directory](https://github.com/ashleychontos/pySYD/tree/master/pysyd). As we describe in https://joss.readthedocs.io/en/latest/review_criteria.html#tests, there are multiple ways to do this, and example inputs/outputs is the _minimum_ we allow but I would [encourage you to go further](https://docs.python-guide.org/writing/tests/) :-)

**Comment by arfon** [comment]
@whedon invite @mbobra as editor

:wave: @mbobra – I realize this is a little out-of-field for you but would you be willing to edit this submission for us?

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by mbobra** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
@ashleychontos Thanks for your submission! If you have any suggestions for reviewers, please let me know here (you can give me the Github handle without @ mentioning them, e.g. mbobra instead of @mbobra).

**Comment by ashleychontos** [comment]
> @ashleychontos Thanks for your submission! If you have any suggestions for reviewers, please let me know here (you can give me the Github handle without @ mentioning them, e.g. mbobra instead of @mbobra).

Thank you for accepting your role as editor in order to assist with our submission! Below are my suggestions for reviewers:

-warrickball
-danhey
-benjaminpope
-jessie-dotson
-christinahedges

Please let me know if you need anything else!

**Comment by mbobra** [comment]
Thanks @ashleychontos! Give me a week-ish to assign reviewers to this submission.

**Comment by mbobra** [comment]
@whedon assign @danhey as reviewer

**Comment by whedon** [comment]
OK, @danhey is now a reviewer

**Comment by mbobra** [comment]
@whedon add @benjaminpope as reviewer

**Comment by whedon** [comment]
OK, @benjaminpope is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3331.

**Comment by mbobra** [comment]
@danhey @benjaminpope See you over in #3331!
