### ISSUE TITLE
[PRE REVIEW]: UglyMol: a WebGL macromolecular viewer focused on the electron density

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#327]
**Submitting author:** @wojdyr (<a href="http://orcid.org/0000-0003-3980-4092">Marcin Wojdyr</a>)
**Repository:** <a href="https://github.com/uglymol/uglymol" target ="_blank">https://github.com/uglymol/uglymol</a>
**Version:** v0.5.7
**Editor:** @arokem
**Reviewer:** @luizirber

**Author instructions**

Thanks for submitting your paper to JOSS @wojdyr. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@wojdyr if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arokem** [comment]
:hand: I can edit this one. 

@wojdyr : do you have suggestions for reviewers? I haven't done crystallography in about 15 years, and don't know anyone in that field any more.

**Comment by wojdyr** [comment]
Thanks for looking into it.
I'm afraid I don't have suggestions for reviewers (people who come to my mind would have a conflict of interest).
But I think that a biochemist or a bioinformatician familiar with 3d structures could also be a good reviewer.

**Comment by arokem** [comment]
Hey @luizirber : would you be willing to review this paper for JOSS?

**Comment by wojdyr** [comment]
@arokem sure, I'll extend it. But are you sure about the recommendations? ATM the [author guidelines](http://joss.theoj.org/about#author_guidelines) show a 60-word example summary as the only hint about the required paper length.

**Comment by arokem** [comment]
This is undergoing change at the moment (if you want to see the discussion, it's going on over here: https://github.com/openjournals/joss/issues/294). We're working to use a better example. For the time being, take a look at https://github.com/cMadan/prism/blob/master/paper/paper.md

**Comment by wojdyr** [comment]
I added a paragraph about scientific context.
And one sentence about another use of the software that I've just learnt about.

Let me know if you have other suggestions. I may reply with a delay -- I'm on holidays this week.

**Comment by arokem** [comment]
Thank you. OK - let's see if we can get a reviewer for this while you are on holidays...

**Comment by arokem** [comment]
@luizirber: Have you had a chance to take a look at this? I realize it's summer, and people are traveling and on vacation, so might be disconnected...

**Comment by luizirber** [comment]
@arokem: I am traveling indeed, just saw this issue. I can review it, but I will try to bring some people to help with the scientific discussion (since I don't know anything about crystallography 😅 )

**Comment by cMadan** [comment]
@whedon assign @arokem as editor

**Comment by whedon** [comment]
OK, the editor is @arokem

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by arokem** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by arokem** [comment]
Something is broken... 

@luizirber : feel free to start taking a look at the code. Hopefully @whedon will come back to its senses, and there will be a review issue for you to follow up on.

**Comment by arokem** [comment]
@whedon assign @luizirber as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @luizirber

**Comment by arokem** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/350. Feel free to close this issue now!

**Comment by arokem** [comment]
OK - turns out I was broken. Closing in favor of #350 for the review.

**Comment by arfon** [comment]
> OK - turns out I was broken. Closing in favor of #350 for the review.

Whedon should also give smarter errors :-\

**Comment by arokem** [comment]
Now raised as an issue here: https://github.com/openjournals/joss/issues/306
