### ISSUE TITLE
[PRE REVIEW]: academictwitteR: an R Package to Access the Twitter Academic Research Product Track V2 API Endpoint

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3271]
**Submitting author:** @cjbarrie (<a href="http://orcid.org/0000-0002-9156-990X">Christopher Barrie</a>)
**Repository:** <a href="https://github.com/cjbarrie/academictwitteR" target ="_blank">https://github.com/cjbarrie/academictwitteR</a>
**Version:** v0.1.0
**Editor:** @danielskatz
**Reviewers:** @medewitt, @JosiahParry
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @cjbarrie. **Currently, there isn't an JOSS editor assigned** to your paper.

@cjbarrie if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.2528481 is OK
- 10.5281/zenodo.4714637 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by cjbarrie** [comment]
Hey! Thanks so much for the quick response. Any of @josiahparry, @Medewitt, @zhanglipku or @natematias?

**Comment by danielskatz** [comment]
> without tagging them with an @ ...

**Comment by JosiahParry** [comment]
Hi @danielskatz I'd love to. What is the timeline we're looking at for this?

**Comment by danielskatz** [comment]
We try for a couple of weeks, but a bit longer is ok.  Reviews are somewhat iterative as well, so if there are any issues you find, it's great for you to point them out then rather than waiting to have a complete review.  Is this ok?  If so, I will add you as a reviewer, but the review won't start until I get another reviewer as well, and open a new issue for the review itself.

**Comment by medewitt** [comment]
Happy to review as well.

**Comment by whedon** [comment]
OK, @medewitt is now a reviewer

**Comment by JosiahParry** [comment]
A few weeks is okay for me! :)

**Comment by danielskatz** [comment]
great, thanks! - I'll start the review and send you another note over there

**Comment by danielskatz** [comment]
@whedon add @JosiahParry as reviewer

**Comment by whedon** [comment]
OK, @JosiahParry is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3272.

**Comment by zhanglipku** [comment]
sorry for responding late, but would be happy to review if needed!

**Comment by danielskatz** [comment]
@zhanglipku - thanks for offering, but the review has started with other reviewers, so no need at this point...
