### ISSUE TITLE
[PRE REVIEW]: PyEI: A Python package for ecological inference

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3275]
**Submitting author:** @karink520 (<a href="http://orcid.org/0000-0003-1312-6473">Karin Knudson</a>)
**Repository:** <a href="https://github.com/mggg/ecological-inference" target ="_blank">https://github.com/mggg/ecological-inference</a>
**Version:** v0.1.0
**Editor:** @drvinceknight
**Reviewers:** @matt-graham, @pmyteh
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6915a867f5b1185488f1d4a8e856e2f3/status.svg)](https://joss.theoj.org/papers/6915a867f5b1185488f1d4a8e856e2f3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6915a867f5b1185488f1d4a8e856e2f3"><img src="https://joss.theoj.org/papers/6915a867f5b1185488f1d4a8e856e2f3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6915a867f5b1185488f1d4a8e856e2f3/status.svg)](https://joss.theoj.org/papers/6915a867f5b1185488f1d4a8e856e2f3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @karink520. **Currently, there isn't an JOSS editor assigned** to your paper.

@karink520 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.55 s (45.1 files/s, 32987.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            459            943           1969
Jupyter Notebook                 6              0          14086            451
TeX                              1             19              0            134
Markdown                         2             53              0            116
YAML                             1              4              2             25
Bourne Shell                     3             11              0             21
-------------------------------------------------------------------------------
SUM:                            25            546          15031           2716
-------------------------------------------------------------------------------


Statistical information for the repository '5f0fd33ee7eae01dd16d7348' was
gathered on 2021/05/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Amy Becker                       2            49             17            0.88
Colin Carroll                   13           358            252            8.12
Gabe Schoenbach                 30           693            269           12.81
JN                               1            17             10            0.36
Karin Knudson                   96          3957           1369           70.94
Matthew Sun                     16           357            149            6.74
karink520                        6             7              4            0.15

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Amy Becker                   28           57.1          1.6                3.57
Colin Carroll               200           55.9          3.8                9.00
Gabe Schoenbach             495           71.4          1.8                4.04
JN                           11           64.7          0.3                0.00
Karin Knudson              2407           60.8          4.5                8.31
Matthew Sun                 230           64.4          8.7                9.13
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01143 is OK

MISSING DOIs

- 10.2307/2088121 may be a valid DOI for title: Ecological regressions and behavior of individuals.
- 10.3886/icpsr01132.v1 may be a valid DOI for title: A solution to the ecological inference problem: Reconstructing individual behavior from aggregate data
- 10.1093/acprof:oso/9780198515326.003.0001 may be a valid DOI for title: Spatial epidemiology: methods and applications.
- 10.1201/b10905-6 may be a valid DOI for title: MCMC using Hamiltonian dynamics

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03275/joss.03275/10.21105.joss.03275.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03275/joss.03275/10.21105.joss.03275.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@karink520 - while we find an editor, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @drvinceknight - Would you be able to edit this submission? I think you will find it interesting...

**Comment by danielskatz** [comment]
@whedon invite @drvinceknight as editor

**Comment by whedon** [comment]
@drvinceknight has been invited to edit this submission.

**Comment by karink520** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "title" (NAME) [#<BibTeX::Bibliography data=[15]>, "@", #<BibTeX::Entry >, {:doi=>["10.1201/b10905-7"]}]

**Comment by karink520** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2307/2088121 is OK
- 10.21105/joss.01143 is OK
- 10.1093/acprof:oso/9780198515326.001.0001 is OK
- 10.1201/b10905-7 is OK

MISSING DOIs

- 10.3886/icpsr01132.v1 may be a valid DOI for title: A solution to the ecological inference problem: Reconstructing individual behavior from aggregate data

INVALID DOIs

- None
```

**Comment by karink520** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03275/joss.03275/10.21105.joss.03275.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03275/joss.03275/10.21105.joss.03275.pdf) :page_facing_up: :point_left:

**Comment by karink520** [comment]
Thanks, @danielskatz! I updated the DOIs. There is one that is still listed as missing. It looks to me like the suggestion is a DOI for data that accompanies the book, but that there is no DOI for the book itself, so I will leave that as is if that works.

**Comment by danielskatz** [comment]
thanks @karink520

**Comment by karink520** [comment]
Hi @danielskatz. I know it's a busy time for folks. Just double checking that there's nothing in particular that I should be doing in the meantime.

**Comment by danielskatz** [comment]
I'll pass this to @openjournals/joss-eics for the person who's on duty this week

**Comment by kyleniemeyer** [comment]
@karink520 unfortunately we have low editor availability in this area right now, so I have to put your submission on our waitlist. We will assign an editor once someone in this area becomes available.

**Comment by Kevin-Mattheus-Moerman** [comment]
@drvinceknight are you able to handle this submission at this point?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite  @drvinceknight as editor

**Comment by danielskatz** [comment]
@whedon invite @drvinceknight as editor

resending, as it doesn't appear that whedon succeeded in this email

**Comment by whedon** [comment]
@drvinceknight has been invited to edit this submission.

**Comment by drvinceknight** [comment]
Apologies for my delay on this and thank you @danielskatz for the nudge.

**Comment by drvinceknight** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by drvinceknight** [comment]
@karink520 thanks again for the submission and my apologies for the delay, if you have not already done so, could you  take a look through https://bit.ly/joss-reviewers to suggest some potential reviewers.

**Comment by karink520** [comment]
@drvinceknight Thank you! Apologies for being slow to reply this week - I have been out of office. Some possible reviewers from the list would be: eigenfoo, ejhigson, pmyteh, SuperKam91, matt-graham

**Comment by drvinceknight** [comment]
That's very helpful @karink520. Thanks :) :+1:

**Comment by drvinceknight** [comment]
@eigenfoo @ejhigson @pmyteh @SuperKam91 and  @matt-graham I'm pinging you to ask if you would be able to assist with reviewing this submissions to JOSS (The Journal of Open Source Software).

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "PyEI: A Python package for ecological inference". You can find more information at the top of this Github issue.

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by matt-graham** [comment]
@drvinceknight: I would be very happy to review the submission.

**Comment by ejhigson** [comment]
I'm sorry I'm afraid I don't have the time to review this at the moment!

**Comment by drvinceknight** [comment]
No problem at all @ejhigson, thank you for getting back to me.

**Comment by drvinceknight** [comment]
> @drvinceknight: I would be very happy to review the submission.

Great @matt-graham :+1: Thanks.

**Comment by drvinceknight** [comment]
@whedon assign @matt-graham as reviewer

**Comment by whedon** [comment]
OK, @matt-graham is now a reviewer

**Comment by pmyteh** [comment]
I am very happy to review.

**Comment by drvinceknight** [comment]
Fantastic, thank you @pmyteh

**Comment by drvinceknight** [comment]
@whedon add @pmyteh as reviewer

**Comment by whedon** [comment]
OK, @pmyteh is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3397.

**Comment by drvinceknight** [comment]
@matt-graham and @pmyteh the review will now be taking place on #3397, there are details there with next steps but please ping me if I can answer any questions you might have.

Thank you both again for agreeing to review.

**Comment by SuperKam91** [comment]
Sorry @drvinceknight but I'm currently a bit snowed-under with work so wouldn't be able to process a review in the near-term

**Comment by drvinceknight** [comment]
No problem @SuperKam91, thank you for getting back to me.
