### ISSUE TITLE
[PRE REVIEW]: InteractionR: An R Package for Full Reporting of Effect Modification and Interaction Analyses

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3276]
**Submitting author:** @epi-zen (<a href="http://orcid.org/0000-0002-9687-7864">Babatunde Yusuf Alli</a>)
**Repository:** <a href="https://github.com/epi-zen/interactionR" target ="_blank">https://github.com/epi-zen/interactionR</a>
**Version:** v0.1.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4d7ebeb18f7dd7c834f3a169cab5b490/status.svg)](https://joss.theoj.org/papers/4d7ebeb18f7dd7c834f3a169cab5b490)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4d7ebeb18f7dd7c834f3a169cab5b490"><img src="https://joss.theoj.org/papers/4d7ebeb18f7dd7c834f3a169cab5b490/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4d7ebeb18f7dd7c834f3a169cab5b490/status.svg)](https://joss.theoj.org/papers/4d7ebeb18f7dd7c834f3a169cab5b490)
```

**Author instructions**

Thanks for submitting your paper to JOSS @epi-zen. **Currently, there isn't an JOSS editor assigned** to your paper.

@epi-zen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (167.7 files/s, 23253.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               12            219            391            956
Markdown                         5            195              0            763
TeX                              1             11              0            100
Rmd                              1             53             64             16
YAML                             1              0              0              5
-------------------------------------------------------------------------------
SUM:                            20            478            455           1840
-------------------------------------------------------------------------------


Statistical information for the repository '283b965a652e34c1b74d8e47' was
gathered on 2021/05/13.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1093/ije/dyr218 may be a valid DOI for title: Recommendations for presenting analyses of effect modification and interaction
- 10.1097/00001648-199209000-00012 may be a valid DOI for title: Confidence Interval Estimation of Interaction
- 10.1093/aje/kwn104 may be a valid DOI for title: On the estimation of additive interaction by use of the four-by-two table and beyond
- 10.1093/aje/kwn411 may be a valid DOI for title: Estimation of the relative excess risk due to interaction and associated confidence bounds
- 10.1093/infdis/jiaa135 may be a valid DOI for title: HIV Modifies the Effect of Tobacco Smoking on Oral Human Papillomavirus Infection

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03276/joss.03276/10.21105.joss.03276.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03276/joss.03276/10.21105.joss.03276.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @epi-zen - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by epi-zen** [comment]
Thanks, @danielskatz. 

I found that two of the criteria for the substantial scholarly effort that you linked to are:

- Whether the software has already been cited in academic papers.

- Whether the software is sufficiently useful that it is likely to be cited by your peer group

On that note, one reason I decided to submit it for consideration for publication was that other researchers are actually using the package and I wasn't getting recognition nor citation for the work yet. Indeed, one of the users caught a bug in the package (see attached anonymized email) which I fixed and this led to the current patched version (0.1.2) on CRAN.  I felt submitting it to JOSS will give it the wider reach, exposure, and recognition the work deserves. Hope this helps with the editorial review. 

In the meantime, I will fix the DOI issues identified by @whedon.  

[Email Correspondence with user.pdf](https://github.com/openjournals/joss-reviews/files/6473468/Email.Correspondence.with.user.pdf)

**Comment by epi-zen** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1097/EDE.0b013e31818f6651 is OK
- 10.1093/oxfordjournals.aje.a113015 is OK
- 10.1093/ije/dyr218 is OK
- 10.1097/00001648-199209000-00012 is OK
- 10.1097/00001648-199605000-00012 is OK
- 10.1093/aje/kwn104 is OK
- 10.1093/aje/kwn411 is OK
- 10.1007/s10654-005-7835-x is OK
- 10.1097/ede.0000000000000752 is OK
- 10.1093/infdis/jiaa135 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by epi-zen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03276/joss.03276/10.21105.joss.03276.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03276/joss.03276/10.21105.joss.03276.pdf) :page_facing_up: :point_left:

**Comment by epi-zen** [comment]
@danielskatz  DOIs are now fixed. Thanks

**Comment by kthyng** [comment]
Hi @epi-zen. Unfortunately the editorial board has determined that this submission is not in scope in terms of [substantial scholarly contribution](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort), though of course that not a statement on how useful the package is. The number of lines of code is relatively small, and the package offers a relatively minor utility. We do have a few suggestions on other ways to make your code available and get a DOI for citations here: https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
