### ISSUE TITLE
[PRE REVIEW]: udocker: a user oriented tool for unprivileged Linux containers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3277]
**Submitting author:** @jorge-lip (<a href="http://orcid.org/0000-0002-9142-2596">Jorge Gomes</a>)
**Repository:** <a href="https://github.com/indigo-dc/udocker" target ="_blank">https://github.com/indigo-dc/udocker</a>
**Version:** v1.1.7
**Editor:** @danielskatz
**Reviewers:** @vsoch, @mviereck
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c14d991a006947bb45804eead0e830d0/status.svg)](https://joss.theoj.org/papers/c14d991a006947bb45804eead0e830d0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c14d991a006947bb45804eead0e830d0"><img src="https://joss.theoj.org/papers/c14d991a006947bb45804eead0e830d0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c14d991a006947bb45804eead0e830d0/status.svg)](https://joss.theoj.org/papers/c14d991a006947bb45804eead0e830d0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jorge-lip. **Currently, there isn't an JOSS editor assigned** to your paper.

@jorge-lip if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.57 s (8.2 files/s, 9978.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5           1785           2970          13262
Bourne Shell                     2            653            500           3569
Markdown                         8            455              0           1746
TeX                              1             54              0            568
YAML                             4              5              0             55
INI                              1              8              0             32
-------------------------------------------------------------------------------
SUM:                            21           2960           3470          19232
-------------------------------------------------------------------------------


Statistical information for the repository 'aa88112e96afb642b00d0fae' was
gathered on 2021/05/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Francesco Bruni                  1             7              0            0.01
Frankie Robertson                1             1              1            0.00
Gregory Boddin                   2             4              2            0.01
Jonathan Passerat-Pa             1             3              0            0.01
Luís Alves                      20          1500            259            3.66
Manabu ISHII                     1             2              1            0.01
Michael R. Crusoe                2             7              4            0.02
Pau Ruiz Safont                  1             1              1            0.00
Romain Reuillon                  1             3              0            0.01
jorge                            1          2725            882            7.50
mariojmdavid                    38          7279           6615           28.90
udocker support                206         21354           7419           59.86

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Francesco Bruni               3           42.9         35.1                0.00
Gregory Boddin                1           25.0         29.6                0.00
Jorge Gomes                 960          100.0         49.6                8.02
Luís Alves                  485           32.3         40.6                2.06
Manabu ISHII                  1           50.0         34.7                0.00
Michael R. Crusoe             6           85.7         31.1                0.00
Pau Ruiz Safont               1          100.0         35.3              100.00
Romain Reuillon               1           33.3         38.8                0.00
mariojmdavid               5728           78.7         14.6               26.96
udocker support           10831           50.7         29.8                7.25
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.6084/m9.figshare.3115156.v2 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.1007/s10723-018-9453-3 is OK
- epjc/s10052-019-7382-3 is OK
- 10.1093/gigascience/giz022 is OK
- 10.1186/s13321-020-0408-x is OK
- 10.1109/ACCESS.2020.2964386 is OK
- 10.1093/gigascience/giz014 is OK
- 10.3204/PUBDB-2018-00782/B8 is OK
- 10.1093/nar/gkaa1125 is OK
- 10.1051/epjconf/202024503002 is OK
- 10.1007/s10723-021-09543-5 is OK
- 10.3390/app11041438 is OK
- 10.1051/epjconf/202024507032 is OK
- 10.1371/journal.pone.0177459 is OK

MISSING DOIs

- 10.1016/j.cpc.2018.05.021 may be a valid DOI for title: Enabling rootless Linux Containers in multi-user environments: the udocker tool
- 10.1016/j.future.2013.05.003 may be a valid DOI for title: OpenMOLE, a workflow engine specifically tailored for the distributed exploration of simulation models
- 10.1007/978-3-030-22750-0_80 may be a valid DOI for title: OPENCoastS: An Open-Access App for Sharing Coastal Prediction Information for Management and Recreation
- 10.1007/978-3-030-34356-9_36 may be a valid DOI for title: Benchmarking Deep Learning Infrastructures by Means of TensorFlow and Containers
- 10.1186/s13321-020-0408-x may be a valid DOI for title: Towards reproducible computational drug discovery
- 10.5194/egusphere-egu21-8418 may be a valid DOI for title: An online service for analysing ozone trends within EOSC-synergy
- 10.1088/1742-6596/898/8/082039 may be a valid DOI for title: OCCAM: a flexible, multi-purpose and extendable HPC cluster
- 10.1016/j.procs.2017.05.065 may be a valid DOI for title: Combining grid computing and docker containers for the study and parametrization of CT image reconstruction methods
- 10.1016/j.procs.2016.05.362 may be a valid DOI for title: Running simultaneous kepler sessions for the parallelization of parametric scans and optimization studies applied to complex workflows

INVALID DOIs

- https://doi.org/10.1016/j.cpc.2018.05.021 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.future.2018.01.022 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.envsoft.2019.104585 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.jpdc.2019.08.002 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3277 with the following error: 
```
 ORCID looks malformed
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (7514-1C96-A542) for Jorge Gomes^[corresponding author] (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
👋 @jorge-lip - The first two ORCIDs in your paper.md are too short. They are likely missing the initial set of four digits.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file.

Then use the command `@whedon check references` to check the references again, and the command `@whedon generate pdf` to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by jorge-lip** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.cpc.2018.05.021 is OK
- 10.6084/m9.figshare.3115156.v2 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.1016/j.future.2013.05.003 is OK
- 10.1016/j.future.2018.01.022 is OK
- 10.1007/s10723-018-9453-3 is OK
- 10.1140/epjc/s10052-019-7382-3 is OK
- 10.1093/gigascience/giz022 is OK
- 10.1186/s13321-020-0408-x is OK
- 10.1109/ACCESS.2020.2964386 is OK
- 10.1093/gigascience/giz014 is OK
- 10.1016/j.envsoft.2019.104585 is OK
- 10.1016/j.future.2013.05.003 is OK
- 10.1016/j.jpdc.2019.08.002 is OK
- 10.3204/PUBDB-2018-00782/B8 is OK
- 10.1007/978-3-030-34356-9_36 is OK
- 10.1093/nar/gkaa1125 is OK
- 10.1051/epjconf/202024503002 is OK
- 10.1186/s13321-020-0408-x is OK
- 10.1007/s10723-021-09543-5 is OK
- 10.3390/app11041438 is OK
- 10.1051/epjconf/202024507032 is OK
- 10.5194/egusphere-egu21-8418 is OK
- 10.1088/1742-6596/898/8/082039 is OK
- 10.1016/j.procs.2017.05.065 is OK
- 10.1016/j.procs.2016.05.362 is OK
- 10.1371/journal.pone.0177459 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jorge-lip** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03277/joss.03277/10.21105.joss.03277.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03277/joss.03277/10.21105.joss.03277.pdf) :page_facing_up: :point_left:

**Comment by jorge-lip** [comment]
@whedon generate pdf

**Comment by jorge-lip** [comment]
@whedon check references

**Comment by jorge-lip** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03277/joss.03277/10.21105.joss.03277.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03277/joss.03277/10.21105.joss.03277.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.cpc.2018.05.021 is OK
- 10.6084/m9.figshare.3115156.v2 is OK
- 10.1038/s41592-018-0046-7 is OK
- 10.1016/j.future.2013.05.003 is OK
- 10.1016/j.future.2018.01.022 is OK
- 10.1007/s10723-018-9453-3 is OK
- 10.1140/epjc/s10052-019-7382-3 is OK
- 10.1093/gigascience/giz022 is OK
- 10.1186/s13321-020-0408-x is OK
- 10.1109/ACCESS.2020.2964386 is OK
- 10.1093/gigascience/giz014 is OK
- 10.1016/j.envsoft.2019.104585 is OK
- 10.1016/j.future.2013.05.003 is OK
- 10.1016/j.jpdc.2019.08.002 is OK
- 10.3204/PUBDB-2018-00782/B8 is OK
- 10.1007/978-3-030-34356-9_36 is OK
- 10.1093/nar/gkaa1125 is OK
- 10.1051/epjconf/202024503002 is OK
- 10.1186/s13321-020-0408-x is OK
- 10.1007/s10723-021-09543-5 is OK
- 10.3390/app11041438 is OK
- 10.1051/epjconf/202024507032 is OK
- 10.5194/egusphere-egu21-8418 is OK
- 10.1088/1742-6596/898/8/082039 is OK
- 10.1016/j.procs.2017.05.065 is OK
- 10.1016/j.procs.2016.05.362 is OK
- 10.1371/journal.pone.0177459 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jorge-lip** [comment]
check references

**Comment by jorge-lip** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03277/joss.03277/10.21105.joss.03277.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03277/joss.03277/10.21105.joss.03277.pdf) :page_facing_up: :point_left:

**Comment by jorge-lip** [comment]
I suggest The following reviewers:
kapsakcj
raivivek
koldunovn

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @vsoch - Would you be interested in reviewing this for JOSS?

**Comment by danielskatz** [comment]
👋 @kapsakcj - Would you be interested in reviewing this for JOSS?

**Comment by vsoch** [comment]
huh, udocker has been around for a bit, I thought it was already published? https://www.sciencedirect.com/science/article/pii/S0010465518302042

**Comment by danielskatz** [comment]
👋 @jorge-lip - can you address @vsoch's point?  How is this JOSS submission different than the previous publication she points to?

**Comment by jorge-lip** [comment]
The mentioned publication was focused on version 1.1.0 and 1.1.1 for Python 2 since then udocker evolved a lot. Has more capabilities and was much rewritten for Python 3. Currently the latest Python 3 candidate release is 2.7.1. The initial paper introduced udocker but was also about benchmarking three scientific applications and providing performance comparisons for them with several containerization tools. This paper is only about udocker and also provides consolidated references for further scientific applications of udocker.

**Comment by danielskatz** [comment]
Thanks - that sounds good to me.

**Comment by danielskatz** [comment]
@vsoch - are you willing to review this?

**Comment by vsoch** [comment]
yes! I love containers and would love to give udocker another spin. I also hugely support that JoSS reviews "non traditional" scientific software papers - this is about containers and environments, and this is on par with my recent submission https://github.com/openjournals/joss-reviews/issues/3217. Sign me up! I can try to make some time in the next few weeks.

**Comment by danielskatz** [comment]
Thanks!  I'll add you, but as you probably know, we won't actually start the review until we also get another reviewer in

**Comment by danielskatz** [comment]
@whedon assign @vsoch as reviewer

**Comment by whedon** [comment]
OK, @vsoch is now a reviewer

**Comment by danielskatz** [comment]
👋 @mviereck - Would you be willing to review this submission to JOSS?

**Comment by kapsakcj** [comment]
Hi all, thanks for the invitation to review but I have to decline as I don't think I'll be able to review in a timely manner. I recently started a new job and will be moving very soon so things are a bit hectic.

If you all are not able to find another reviewer in say...a month's time? please ping me again and I may be able to dedicate some time to this. 

I too love containers and am interested in this topic, but I'd hate to be the reason why a review drags on for weeks & months.

I will ping some colleagues to see if they are interested.

**Comment by danielskatz** [comment]
Thanks - suggestions on your interested colleagues would be great!

**Comment by danielskatz** [comment]
👋 @laramaktub - Would you be willing to review this submission for JOSS?  We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by mviereck** [comment]
Thank you for the invitation, I am interested to review.
I am currently looking at udocker, run some first tests and have a look at the paper.

I am a bit unsure yet if I can fulfill the requirements (lack of English language skills to understand everything well). Though, I have some experience with containers. Maybe I should just do the review and point out when/where I am unsure in single check points.

**Comment by danielskatz** [comment]
That would be fine - please let me know when you decide if you want to do this, and if so, I will assign you and start the review

**Comment by vsoch** [comment]
@mviereck I'll be around in the review issue and can help with that - just ask when you want to discuss something or just want clarification on a point.

**Comment by danielskatz** [comment]
@mviereck - I realize I may have read your comment incorrectly.  I'm going to assume now that "I am interested to review" means you want to review this, and I'll go ahead and add you and get things started - thanks!!

**Comment by danielskatz** [comment]
@whedon add @mviereck as reviewer

**Comment by whedon** [comment]
OK, @mviereck is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3295.
