### ISSUE TITLE
[PRE REVIEW]: covidregionaldata: Subnational data for COVID-19 epidemiology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3278]
**Submitting author:** @joseph-palmer (<a href="http://orcid.org/0000-0002-5593-9352">Joseph Palmer</a>)
**Repository:** <a href="https://github.com/epiforecasts/covidregionaldata" target ="_blank">https://github.com/epiforecasts/covidregionaldata</a>
**Version:** 0.9.1
**Editor:** @csoneson
**Reviewers:** @mponce0, @federicomarini
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/dd6f7acdae3b7136a3ac373ce9a0655c/status.svg)](https://joss.theoj.org/papers/dd6f7acdae3b7136a3ac373ce9a0655c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/dd6f7acdae3b7136a3ac373ce9a0655c"><img src="https://joss.theoj.org/papers/dd6f7acdae3b7136a3ac373ce9a0655c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/dd6f7acdae3b7136a3ac373ce9a0655c/status.svg)](https://joss.theoj.org/papers/dd6f7acdae3b7136a3ac373ce9a0655c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @joseph-palmer. **Currently, there isn't an JOSS editor assigned** to your paper.

@joseph-palmer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.70 s (152.1 files/s, 12847.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               60            364           1948           3896
YAML                            27            218             10           1167
Markdown                         6            161              0            498
TeX                              1             19              0            228
Rmd                              4            138            222            146
SVG                              8              0              0              8
Dockerfile                       1              3              6              4
-------------------------------------------------------------------------------
SUM:                           107            903           2186           5947
-------------------------------------------------------------------------------


Statistical information for the repository '0f00582d10f6f9ccfed55582' was
gathered on 2021/05/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Hamish Gibbs                     1           159              5           22.97
seabbs                           2           198            352           77.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.12688/wellcomeopenres.16006.2 is OK
- 10.5281/zenodo.3957539 is OK
- 10.21105/joss.02376 is OK
- 10.1126/science.abg3055 is OK
- 10.1016/S1473-3099(20)30120-1 is OK
- 10.12688/wellcomeopenres.15842.3 is OK
- 10.21105/joss.02376 is OK
- 10.1038/s41562-021-01079-8 is OK
- 10.1080/13876988.2021.1873703 is OK
- 10.1101/2020.10.18.20214585 is OK
- 10.21105/joss.01686 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03278/joss.03278/10.21105.joss.03278.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03278/joss.03278/10.21105.joss.03278.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @csoneson - Is there any chance you would be able to take on another editing task?  You were suggested by the submitter here.

**Comment by danielskatz** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋🏻 @joseph-palmer  - I will handle your submission, and start by finding reviewers. If you have any suggestions (e.g., from the spreadsheet linked in the first post above), please feel free to provide them here.

**Comment by csoneson** [comment]
👋🏻 @mponce0, @eguidotti - would you be interested in reviewing this submission for JOSS? 

> covidregionaldata: Subnational data for COVID-19 epidemiology

**Comment by eguidotti** [comment]
@csoneson Thanks but I think to be in conflict of interest with this work as I've implemented and published something very similar. I will not review according to your policies. 

> The definition of a conflict of Interest in peer review is a circumstance that makes you “unable to make an impartial scientific judgment or evaluation.” (PNAS Conflict of Interest Policy). JOSS is concerned with avoiding any actual conflicts of interest, and being sufficiently transparent that we avoid the appearance of conflicts of interest as well.

**Comment by mponce0** [comment]
@csoneson I'm in a similar situation as @eguidotti, as I have also authored an R package for accessing covid19 data. Having said that and IFF you and JOSS are OK with this, meaning that you consider that there is no conflict of interest, I'll be OK to review the submission.

> @csoneson Thanks but I think to be in conflict of interest with this work as I've implemented and published something very similar. I will not review according to your policies.
> 
> > The definition of a conflict of Interest in peer review is a circumstance that makes you “unable to make an impartial scientific judgment or evaluation.” (PNAS Conflict of Interest Policy). JOSS is concerned with avoiding any actual conflicts of interest, and being sufficiently transparent that we avoid the appearance of conflicts of interest as well.

**Comment by csoneson** [comment]
Thanks both! @mponce0 - we discussed it and we think that it is not a problem (assuming of course that you think you can make a "fair" assessment of the submission).

**Comment by mponce0** [comment]
> Thanks both! @mponce0 - we discussed it and we think that it is not a problem (assuming of course that you think you can make a "fair" assessment of the submission).

@csoneson Thanks! I will certainly try my best!

**Comment by csoneson** [comment]
Brilliant, thanks a lot!

**Comment by csoneson** [comment]
@whedon assign @mponce0 as reviewer

**Comment by whedon** [comment]
OK, @mponce0 is now a reviewer

**Comment by csoneson** [comment]
@whedon add @federicomarini as reviewer

**Comment by whedon** [comment]
OK, @federicomarini is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3290.
