### ISSUE TITLE
[PRE REVIEW]: The Region Growing Plugin (RegionGrow)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3279]
**Submitting author:** @gro5-AberUni (<a href="http://orcid.org/0000-0002-5054-1548">Gregory Oakes</a>)
**Repository:** <a href="https://github.com/gro5-AberUni/RegionGrow" target ="_blank">https://github.com/gro5-AberUni/RegionGrow</a>
**Version:** V4.1
**Editor:** @hugoledoux
**Reviewers:** @jorgegil, @Geogoeroe
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1a627488ff2314c58c19dce3b77d97e8/status.svg)](https://joss.theoj.org/papers/1a627488ff2314c58c19dce3b77d97e8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1a627488ff2314c58c19dce3b77d97e8"><img src="https://joss.theoj.org/papers/1a627488ff2314c58c19dce3b77d97e8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1a627488ff2314c58c19dce3b77d97e8/status.svg)](https://joss.theoj.org/papers/1a627488ff2314c58c19dce3b77d97e8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @gro5-AberUni. **Currently, there isn't an JOSS editor assigned** to your paper.

@gro5-AberUni if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.9790/2834-0122445 may be a valid DOI for title: Color image segmentation for medical images using L* a* b* color space
- 10.1109/icamechs.2014.6911663 may be a valid DOI for title: Image segmentation algorithm for disease detection of wheat leaves
- 10.1007/978-3-030-05318-5_8 may be a valid DOI for title: TPOT: A tree-based pipeline optimization tool for automating machine learning

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=6.54 s (5.0 files/s, 13637.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          14            739            519          85775
Qt                               1              0              0           1105
make                             2             62             61            251
Markdown                         4             63              0            190
DOS Batch                        1             21              1            133
TeX                              2              6              0            104
Bourne Shell                     3             14             11             71
HTML                             1              2              0             40
XML                              2              2              0             29
QML                              1              0              0             26
Qt Linguist                      1              0              0             11
reStructuredText                 1              6              6              8
-------------------------------------------------------------------------------
SUM:                            33            915            598          87743
-------------------------------------------------------------------------------


Statistical information for the repository '634a29ef3e11fad41ec32c68' was
gathered on 2021/05/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
gro5-AberUni                    24         39656           6400          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
gro5-AberUni              87033          219.5          5.1                0.39
```

**Comment by danielskatz** [comment]
👋 @hugoledoux - Is there any chance you can take on another submission to edit?  You were suggested by the authors...

**Comment by danielskatz** [comment]
@whedon invite @hugoledoux as editor

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by hugoledoux** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by whedon** [comment]
OK, @jorgegil is now a reviewer

**Comment by gro5-AberUni** [comment]
@hugoledoux Thank you for including the newer citation, I will update the paper to reflect that. 

The main difference between the plugin we present here and the Semi Automatic Classification Plugin is that the region growing tool in the Semi Automatic Classification plugin is integrated within the wider toolbox with the expectation that digitised regions are used for image classification within the plugin itself. We present a more general tool for digitising features through region growing where the resultant features are used in other workflows. We also found that the Semi automatic classification plugin can be quite difficult to use, particularly for non-experts who do not frequently use GIS software so we aimed to create a tool with an easy to use UI.

**Comment by hugoledoux** [comment]
@whedon add @Geogoeroe as reviewer

**Comment by whedon** [comment]
OK, @Geogoeroe is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3346.
