### ISSUE TITLE
[PRE REVIEW]: NSDRP: A Near-Infrared Data Reduction and Numerical Analysis Pipeline

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#328]
**Submitting author:** @Astrodude11 (<a href="http://orcid.org/0000-0002-3634-1187">Andrew Colson</a>)
**Repository:** <a href="https://github.com/Astrodude11/NIRSPEC-Data-Reduction-Pipeline/tree/master" target ="_blank">https://github.com/Astrodude11/NIRSPEC-Data-Reduction-Pipeline/tree/master</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @Astrodude11. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Astrodude11 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @Astrodude11 - thanks for your submission to JOSS. Is there a reason you're submitting your fork of this repository for review and not the parent (https://github.com/Keck-DataReductionPipelines/NIRSPEC-Data-Reduction-Pipeline)?

**Comment by Astrodude11** [comment]
@arfon - Yes, I'm glad you asked. I created the fork so I could change the README file to satisfy the instructions per JOSS. Since users download the parent I want the users to see the full and original README.

**Comment by arfon** [comment]
> @arfon - Yes, I'm glad you asked. I created the fork so I could change the README file to satisfy the instructions per JOSS. Since users download the parent I want the users to see the full and original README.

@Astrodude11 - JOSS doesn't place any requirements on what the README should contain, we need you to have a `paper.md` file that has the paper contents and an associated bibtex file. See the two files in this example: https://github.com/arfon/fidgit/tree/master/paper . I would suggest adding the files (`paper.md` and `paper.bib`) to the original repository (https://github.com/Keck-DataReductionPipelines/NIRSPEC-Data-Reduction-Pipeline) and I can then update the repository address associated with the submission.

Also, could you please expand a little on the `paper.md` file once you've created it? We (the JOSS editors) are in the process of adding more guidance for authors, including a better indication of expected paper length. Currently it's hard to get a picture of the functionality of the software, and also include a statement of need, in less than 250 words. Would you be able to put a little more detail in your submission please?

**Comment by Astrodude11** [comment]
@arfon - Ah, okay. I took READMD.md as mistake for paper.md. I'll correct this, add paper.bib, and supplement the description to the original repo soon.

**Comment by arfon** [comment]
> @arfon - Ah, okay. I took READMD.md as mistake for paper.md. I'll correct this, add paper.bib, and supplement the description to the original repo soon.

Thanks. Please let me know when you've done this.

**Comment by arfon** [comment]
Friendly reminder @Astrodude11

**Comment by arfon** [comment]
*bump* friendly reminder @Astrodude11

**Comment by arfon** [comment]
@Astrodude11 - if I don't hear back from you in the next two weeks I'll be forced to reject your submission.

**Comment by arfon** [comment]
This submission is rejected due to the author going AWOL.
