### ISSUE TITLE
[PRE REVIEW]: ddop: A python package for data-driven operations management

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3280]
**Submitting author:** @AndreasPhilippi (<a href="http://orcid.org/0000-0002-6508-9128">Andreas Philippi</a>)
**Repository:** <a href="https://github.com/opimwue/ddop" target ="_blank">https://github.com/opimwue/ddop</a>
**Version:** v0.6.5
**Editor:** @arfon
**Reviewers:** @kramea, @g4brielvs
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0de119f95840b69fcea94309c18058e4/status.svg)](https://joss.theoj.org/papers/0de119f95840b69fcea94309c18058e4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0de119f95840b69fcea94309c18058e4"><img src="https://joss.theoj.org/papers/0de119f95840b69fcea94309c18058e4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0de119f95840b69fcea94309c18058e4/status.svg)](https://joss.theoj.org/papers/0de119f95840b69fcea94309c18058e4)
```

**Author instructions**

Thanks for submitting your paper to JOSS @AndreasPhilippi. **Currently, there isn't an JOSS editor assigned** to your paper.

@AndreasPhilippi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.95 s (90.6 files/s, 36178.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      14           2289           2323           8445
HTML                            21           2766             63           6919
SVG                              1              0              0           2671
Python                          17            403           1255            967
Jupyter Notebook                 2              0           3561            935
CSS                              4            181             33            715
reStructuredText                21            230            206            219
TeX                              1              3              0             36
DOS Batch                        1             11              1             32
Markdown                         1             12              0             32
make                             1              4              7             10
YAML                             2              2              0              8
-------------------------------------------------------------------------------
SUM:                            86           5901           7449          20989
-------------------------------------------------------------------------------


Statistical information for the repository '67b9c1253487e9a552663bb2' was
gathered on 2021/05/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
AndreasPhilippi                 74       1316537        1300891          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
AndreasPhilippi           15682            1.2          9.2               15.76
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.2139/ssrn.2559116 may be a valid DOI for title: The big data newsvendor: Practical insights from machine learning
- 10.1080/24725854.2019.1632502 may be a valid DOI for title: Applying deep learning to the newsvendor problem

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03280/joss.03280/10.21105.joss.03280.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03280/joss.03280/10.21105.joss.03280.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@AndreasPhilippi - Operations Management is two words in English - please change this in your paper.  In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
Also, because the code size is a little on the small side, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by AndreasPhilippi** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "doi" (NAME) [#<BibTeX::Bibliography data=[2]>, "@", #<BibTeX::Entry >, {:title=>["From predictive to prescriptive analytics"], :author=>["Bertsimas, Dimitris and Kallus, Nathan"], :journal=>["Management Science"], :volume=>["66"], :number=>["3"], :pages=>["1025--1044"], :year=>["2020"], :publisher=>["INFORMS"]}]

**Comment by AndreasPhilippi** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1287/opre.2018.1757 is OK
- 10.1287/mnsc.2018.3253 is OK
- 10.1080/24725854.2019.1632502 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by AndreasPhilippi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03280/joss.03280/10.21105.joss.03280.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03280/joss.03280/10.21105.joss.03280.pdf) :page_facing_up: :point_left:

**Comment by AndreasPhilippi** [comment]
> Also, because the code size is a little on the small side, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. You should hear back in a week or so.

@danielskatz - Do you have any news for us regarding the query scope?

**Comment by AndreasPhilippi** [comment]
@danielskatz - As reviewer we suggest rlucas7, g4brielvs, or kramea

**Comment by danielskatz** [comment]
@AndreasPhilippi - I'm sorry for the delay, but this discussion has not been as brief as most other editor discussions - I'm pinging the AEiC currently on duty about this: @openjournals/joss-eics to help move it forward to a decision

**Comment by danielskatz** [comment]
👋 @AndreasPhilippi - note that we are awaiting your answer.

**Comment by AndreasPhilippi** [comment]
@kthyng @danielskatz - The goal of ddop is to allow previously developed data-driven approaches (from the field of operations management) to be efficiently applied on different datasets. 
Let me give you an example: In recent years, many algorithms have been proposed to solve the newsvendor problem based on historical data (including past demand observations as well as additional features such as weather forecasts or calendar data.). Now ddop integrates a wide range of these algorithms making it possible to apply and evaluate them on different datasets with only a few lines of code. So ddop is basically the same as machine learning libraries like scikit-learn. It' s just much smaller and instead of ML algorithms, it provides data-driven decision algorithms from the field of operations management.

However, we will update the paper with the "statement of need section" as soon as possible.

**Comment by danielskatz** [comment]
Thanks - adding some of these specific examples will be helpful

**Comment by AndreasPhilippi** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1287/opre.2018.1757 is OK
- 10.1287/mnsc.2018.3253 is OK
- 10.1080/24725854.2019.1632502 is OK
- 10.3390/info11020108 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by AndreasPhilippi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03280/joss.03280/10.21105.joss.03280.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03280/joss.03280/10.21105.joss.03280.pdf) :page_facing_up: :point_left:

**Comment by AndreasPhilippi** [comment]
@kthyng We have updated the paper and hope that the statement of needs is clear. Let me now if there are still uncertainties.

**Comment by kyleniemeyer** [comment]
Hi @AndreasPhilippi, the JOSS editorial board has reviewed your submission and found that it is within our scope, so we will move forward with review. 

However, due to low editor availability, this will enter our waitlist as we work through the backlog of submissions. Thanks for your patience!

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@AndreasPhilippi – could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by AndreasPhilippi** [comment]
> @danielskatz - As reviewer we suggest rlucas7, g4brielvs, or kramea

@arfon We have already suggested three editions that we think are good candidates. Are they not available or do we need to suggest more?

**Comment by arfon** [comment]
:wave: @rlucas7, @g4brielvs, @kramea – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration here is [_ddop: A python package for data-driven operations management_](https://github.com/opimwue/ddop)

**Comment by kramea** [comment]
Sure, I can review that.

**Comment by arfon** [comment]
@whedon add @kramea as reviewer

**Comment by whedon** [comment]
OK, @kramea is now a reviewer

**Comment by g4brielvs** [comment]
@arfon Sorry for missing this opportunity to review. My name hadn't been tagged and I didn't receive the notification. I'd be more than happy to contribute, if appropriate.

**Comment by arfon** [comment]
> @arfon Sorry for missing (20 days ago) this opportunity to review. My name hadn't been tagged and I didn't receive the notification. I'd be more than happy to contribute, if appropriate.

Definitely not to late! I'll add you now, and thanks!

**Comment by arfon** [comment]
@whedon add @g4brielvs as reviewer

**Comment by whedon** [comment]
OK, @g4brielvs is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3429.

**Comment by arfon** [comment]
@kramea, @g4brielvs, @AndreasPhilippi – see you over in #3429 where the actual review will take place.
