### ISSUE TITLE
[PRE REVIEW]: ICSSgen and ICSScsv: Python programs for 2D-ICSS calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3281]
**Submitting author:** @wongzit (<a href="http://orcid.org/0000-0002-9996-586X">Zhe Wang</a>)
**Repository:** <a href="https://github.com/wongzit/ICSSgen-ICSScsv" target ="_blank">https://github.com/wongzit/ICSSgen-ICSScsv</a>
**Version:** v2.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/10069fce6beb1d944822ec29354b25c3/status.svg)](https://joss.theoj.org/papers/10069fce6beb1d944822ec29354b25c3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/10069fce6beb1d944822ec29354b25c3"><img src="https://joss.theoj.org/papers/10069fce6beb1d944822ec29354b25c3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/10069fce6beb1d944822ec29354b25c3/status.svg)](https://joss.theoj.org/papers/10069fce6beb1d944822ec29354b25c3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @wongzit. **Currently, there isn't an JOSS editor assigned** to your paper.

@wongzit if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (33.1 files/s, 5512.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           2             68             39            402
Markdown                         1             34              0             98
TeX                              1              2              0             24
-------------------------------------------------------------------------------
SUM:                             4            104             39            524
-------------------------------------------------------------------------------


Statistical information for the repository '2e002f4330429d646db560a9' was
gathered on 2021/05/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Zhe Wang                         1           509              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Zhe Wang                    509          100.0          0.0                7.66
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "-1898" (NAME) ["@", #<BibTeX::Entry >, {:author=>["{Klod}, S. and {Kleinpeter}, E."], :title=>["{Ab initio calculation of the anisotropy effect of multiple bonds and the ring current effect of arenes--application in conformational and configurational analysis}"], :journal=>["J. Chem. Soc., Perkin Trans. 2"], :year=>"2001", :pages=>"1893"}]

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03281/joss.03281/10.21105.joss.03281.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03281/joss.03281/10.21105.joss.03281.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @wongzit - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

In addition, you could work on the bibtex problems. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hello @wongzit, thanks for your patience. The JOSS editorial board reviewed your submission, and unfortunately found that it does not meet our [substantial scholarly effort criterion](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
