### ISSUE TITLE
[REVIEW]: dataaimsr: An R Client for the Australian Institute of Marine Science Data Platform API which provides easy access to AIMS Data Platform

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3282]
**Submitting author:** @dbarneche (<a href="http://orcid.org/0000-0002-4568-2362">Diego Barneche</a>)
**Repository:** <a href="https://github.com/ropensci/dataaimsr" target ="_blank">https://github.com/ropensci/dataaimsr</a>
**Version:** v1.0.3
**Editor:** @kthyng
**Reviewer:** @kthyng
**Archive:** <a href="https://doi.org/10.5281/zenodo.4782786" target="_blank">10.5281/zenodo.4782786</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/7980fff63a54453a4e637f185764336d/status.svg)](https://joss.theoj.org/papers/7980fff63a54453a4e637f185764336d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7980fff63a54453a4e637f185764336d"><img src="https://joss.theoj.org/papers/7980fff63a54453a4e637f185764336d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7980fff63a54453a4e637f185764336d/status.svg)](https://joss.theoj.org/papers/7980fff63a54453a4e637f185764336d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/dataaimsr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kthyng, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/dataaimsr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dbarneche) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kthyng it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.46 s (48.1 files/s, 139061.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                            23              4              0         197713
R                               28             52            640            948
Markdown                         5            142              0            578
TeX                              2             51             30            451
XML                              1              0              2            441
YAML                             6             46             10            206
Rmd                              5            265            948             48
-------------------------------------------------------------------------------
SUM:                            70            560           1630         200385
-------------------------------------------------------------------------------


Statistical information for the repository '9785a65a0b274e047955c3fb' was
gathered on 2021/05/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jeffrey Sheehan                  5            32             32          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.mio.2014.09.001 is OK
- 10.21014/acta_imeko.v5i1.213 is OK
- 10.32614/RJ-2018-009 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03282/joss.03282/10.21105.joss.03282.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03282/joss.03282/10.21105.joss.03282.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03282/joss.03282/10.21105.joss.03282.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03282/joss.03282/10.21105.joss.03282.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @dbarneche — here we are in the review issue now, but please do look at the comments I left in the pre-review issue (I should have made them here).

**Comment by kthyng** [comment]
@openjournals/dev I think I lost my permission to edit the checkboxes above midway through checking them. They were turning blue for me and I could edit and now they are gray and I cannot edit them.

**Comment by kthyng** [comment]
@dbarneche Do you already have a zenodo repo? If so, please provide the DOI here. If not, please go ahead and make one. The title and author list in the archive should exactly match that of your JOSS paper.

**Comment by dbarneche** [comment]
Hi @kthyng,

Thanks very much for advancing this, and apologies for the delayed response. I have addressed the comments mention in the [pre-review issue](https://github.com/openjournals/joss-reviews/issues/3258). Particularly, I renamed the first section to "Statement of Need" and shortened some bits of the paper as advised. There is still a bit of repetition with the package documentation/vignettes, but I thought those were best as is for the sake of transparency---let me know if you'd like me to shrink the size further.

I have also created a Zenodo repo for the package, please see it here:
https://zenodo.org/record/4782786#.YKsgIpMzbUI

DOI is: 10.5281/zenodo.4782786.svg

Please do not hesitate to let me know if there's anything else needed from my end. Thanks again. Best wishes

**Comment by arfon** [comment]
> @openjournals/dev I think I lost my permission to edit the checkboxes above midway through checking them. They were turning blue for me and I could edit and now they are gray and I cannot edit them.

Weird... Can you try again now please?

**Comment by kthyng** [comment]
@arfon Worked, thanks!

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03282/joss.03282/10.21105.joss.03282.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03282/joss.03282/10.21105.joss.03282.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@dbarneche Great! Can you update the title of your Zenodo archive to exactly match your JOSS paper?

Also, the figure references in your JOSS paper seem to have gotten off. Can you take a look at them in the proof above? You don't need to update the Zenodo archive for paper changes (unless you want to).

**Comment by dbarneche** [comment]
Hi @kthyng , apologies for the mix up with the Zenodo title, that has been fixed.

I'm not quite sure how to fix the figure references/captions issue. Would you mind guiding me through a fix?

Locally, I'm running [this code](https://github.com/ropensci/dataaimsr/blob/master/paper/render.R) to generate the pdf (it is a bit of a hack), and the fig references/captions render fine, e.g.:

![Screen Shot 2021-05-27 at 9 35 12 am](https://user-images.githubusercontent.com/3580907/119752035-d7eb6200-bece-11eb-92bc-e4788fbefc66.png)
![Screen Shot 2021-05-27 at 9 35 23 am](https://user-images.githubusercontent.com/3580907/119752051-dde14300-bece-11eb-91f7-847d0f4949e7.png)
![Screen Shot 2021-05-27 at 9 35 57 am](https://user-images.githubusercontent.com/3580907/119752104-f2254000-bece-11eb-9b18-6dc71ed2383c.png)
![Screen Shot 2021-05-27 at 9 36 08 am](https://user-images.githubusercontent.com/3580907/119752119-f94c4e00-bece-11eb-85c3-1f17aa711298.png)
 
Thanks for your help!

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03282/joss.03282/10.21105.joss.03282.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03282/joss.03282/10.21105.joss.03282.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@dbarneche There is a note about paper compilation here: https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles We have a system that will do that for you, and you can test it out, too. Examples of figures and captions are here: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography Does this help?

**Comment by dbarneche** [comment]
Thanks @kthyng ! It has been [fixed](https://github.com/ropensci/dataaimsr/commit/b7daff1254a6f7741b7117e2e2115d331494b37a).
I checked the online compilation tools and it should be working now.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03282/joss.03282/10.21105.joss.03282.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03282/joss.03282/10.21105.joss.03282.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.4782786 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4782786" target="_blank">10.5281/zenodo.4782786</a> is the archive.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
To recommend a paper to be accepted use `@whedon recommend-accept`

**Comment by kthyng** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.mio.2014.09.001 is OK
- 10.21014/acta_imeko.v5i1.213 is OK
- 10.32614/RJ-2018-009 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2360

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2360, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1400931415173349379) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2361
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03282](https://doi.org/10.21105/joss.03282)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new paper @dbarneche!!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03282/status.svg)](https://doi.org/10.21105/joss.03282)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03282">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03282/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03282/status.svg
   :target: https://doi.org/10.21105/joss.03282
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03282/status.svg)](https://doi.org/10.21105/joss.03282)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by dbarneche** [comment]
Thanks very much @kthyng for your assessment and guidance, much appreciated.
All the best,
Diego
