### ISSUE TITLE
[PRE REVIEW]: ATARRI: A TESS Archive RR Lyrae Classifier

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3286]
**Submitting author:** @kennethcarrell (<a href="http://orcid.org/0000-0002-6307-992X">Kenneth Carrell</a>)
**Repository:** <a href="https://github.com/kennethcarrell/ATARRI" target ="_blank">https://github.com/kennethcarrell/ATARRI</a>
**Version:** v1.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/7a7ec2930dbd73e8ddaa7171031552d4/status.svg)](https://joss.theoj.org/papers/7a7ec2930dbd73e8ddaa7171031552d4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7a7ec2930dbd73e8ddaa7171031552d4"><img src="https://joss.theoj.org/papers/7a7ec2930dbd73e8ddaa7171031552d4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7a7ec2930dbd73e8ddaa7171031552d4/status.svg)](https://joss.theoj.org/papers/7a7ec2930dbd73e8ddaa7171031552d4)
```

**Author instructions**

Thanks for submitting your paper to JOSS @kennethcarrell. **Currently, there isn't an JOSS editor assigned** to your paper.

@kennethcarrell if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (304.4 files/s, 34765.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5            106            179            674
Markdown                         2             15              0             88
TeX                              1              2              0             43
reStructuredText                 2              5              0             30
-------------------------------------------------------------------------------
SUM:                            10            128            179            835
-------------------------------------------------------------------------------


Statistical information for the repository 'deb49d2a2e90032eed3b0b30' was
gathered on 2021/05/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kenneth Carrell                 12          1155            196          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kenneth Carrell             959           83.0          0.2               18.56
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1117/1.JATIS.1.1.014003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03286/joss.03286/10.21105.joss.03286.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03286/joss.03286/10.21105.joss.03286.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
Note from author: This is a companion paper to an article submitted to The Astrophysical Journal Letters

**Comment by danielskatz** [comment]
👋 @kennethcarrell - Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kyleniemeyer** [comment]
Hello @kennethcarrell, thanks for your patience. The JOSS editorial board has reviewed your submission, and unfortunately found that it does not meet our [substantial scholarly effort criterion](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
