### ISSUE TITLE
[PRE REVIEW]: pyREX: Workflow-Orientated Python Package for Replica Exchange Molecular Dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3287]
**Submitting author:** @ArtVoro (<a href="http://orcid.org/0000-0002-5804-5151">Arthur Voronin</a>)
**Repository:** <a href="https://github.com/KIT-MBS/pyREX" target ="_blank">https://github.com/KIT-MBS/pyREX</a>
**Version:** 1.0
**Editor:** @jgostick
**Reviewers:** @janash, @rosecers
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/957b0672d03306d75cc12fada3a6b6da/status.svg)](https://joss.theoj.org/papers/957b0672d03306d75cc12fada3a6b6da)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/957b0672d03306d75cc12fada3a6b6da"><img src="https://joss.theoj.org/papers/957b0672d03306d75cc12fada3a6b6da/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/957b0672d03306d75cc12fada3a6b6da/status.svg)](https://joss.theoj.org/papers/957b0672d03306d75cc12fada3a6b6da)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ArtVoro. **Currently, there isn't an JOSS editor assigned** to your paper.

@ArtVoro if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.72 s (80.4 files/s, 82868.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       9           2404           2458           9198
HTML                             8            555              0           6834
Python                          19           1723           4295           5160
CSS                              4            328             50           1267
Jupyter Notebook                 8              0          24643            350
Markdown                         2             37              0            123
TeX                              1             11              0            111
reStructuredText                 5             39             67             49
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            58           5109          31521          23127
-------------------------------------------------------------------------------


Statistical information for the repository '21fc6015a32262df071ebe91' was
gathered on 2021/05/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Arthur                          19         16916           1748           58.43
Arthur Voronin                  60         11489           1787           41.57

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Arthur                    25238          149.2          1.4               15.23
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.2654393 is OK

MISSING DOIs

- 10.1002/jcc.20291 may be a valid DOI for title: GROMACS: fast, flexible, and free
- 10.2210/pdb5upw/pdb may be a valid DOI for title: CryoEM structure refinement by integrating NMR chemical shifts with molecular dynamics simulations
- 10.25080/majora-629e541a-00e may be a valid DOI for title: MDAnalysis: a Python package for the rapid analysis of molecular dynamics simulations
- 10.1002/jcc.21787 may be a valid DOI for title: MDAnalysis: a toolkit for the analysis of molecular dynamics simulations
- 10.1093/bioinformatics/btx789 may be a valid DOI for title: NGLview–interactive molecular graphics for Jupyter notebooks
- 10.1371/journal.pone.0242072 may be a valid DOI for title: Including residual contact information into replica-exchange MD simulations significantly enriches native-like conformations

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03287/joss.03287/10.21105.joss.03287.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03287/joss.03287/10.21105.joss.03287.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@artvoro - if you have time, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @jgostick - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @jgostick as editor

**Comment by whedon** [comment]
@jgostick has been invited to edit this submission.

**Comment by jgostick** [comment]
arg, I keep getting these molecular dynamics packages to review though it's really not my area.  I have been relying on the list of volunteer editors, but I must be close to exhausting that list by now.  I will edit this one, but would appreciate if @ArtVoro could suggest some suitable reviewers?

**Comment by jgostick** [comment]
@whedon assign @jgostick as editor

**Comment by whedon** [comment]
OK, the editor is @jgostick

**Comment by jgostick** [comment]
@ArtVoro, we have a checklist of things that the reviewers will look for, and I can already tell that your documentation will raise some flags, since there isn't any.  :-)  I can see that you have a ``doc`` folder so I'm sure you're building it and hosting it somewhere, but there is no link to this in your readme or anywhere on the github page.  Could you maybe address this first, so the reviewers and I can start digging in to this package?

**Comment by danielskatz** [comment]
@jgostick - You could ask shantenujha if someone in his Rutgers/BNL group could review this, or bieniekmateusz or someone else in the same UCL group

**Comment by danielskatz** [comment]
Also, perhaps someone from https://github.com/orgs/MolSSI/people

**Comment by jgostick** [comment]
@ArtVovo, I should also add that your package name is essentially invisible to google since people have run molecular dynamics simulations on actual pyrex brand glass, and that is the only hits I'm getting.  I'm sure you are aware of this, but maybe consider a name change before JOSS chisels it in stone?

**Comment by ArtVoro** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/S0009-2614(99)01123-9 is OK
- 10.1063/1.2056540 is OK
- 10.1002/jcc.20291 is OK
- 10.1073/pnas.1111471108 is OK
- 10.1021/acs.jpcb.6b13105 is OK
-  10.25080/Majora-629e541a-00e  is OK
- 10.1002/jcc.21787 is OK
- 10.1093/bioinformatics/btx789 is OK
- 10.5281/zenodo.2654393 is OK
- 10.1371/journal.pone.0242072 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ArtVoro** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03287/joss.03287/10.21105.joss.03287.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03287/joss.03287/10.21105.joss.03287.pdf) :page_facing_up: :point_left:

**Comment by ArtVoro** [comment]
> @ArtVoro, we have a checklist of things that the reviewers will look for, and I can already tell that your documentation will raise some flags, since there isn't any. :-) I can see that you have a `doc` folder so I'm sure you're building it and hosting it somewhere, but there is no link to this in your readme or anywhere on the github page. Could you maybe address this first, so the reviewers and I can start digging in to this package?

@jgostick i will try to fix it asap. until 2 days ago the documentation was just the doc strings of the py files.

> @ArtVovo, I should also add that your package name is essentially invisible to google since people have run molecular dynamics simulations on actual pyrex brand glass, and that is the only hits I'm getting. I'm sure you are aware of this, but maybe consider a name change before JOSS chisels it in stone?

@jgostick i will discuss some alternative names with my colleagues.

**Comment by jgostick** [comment]
Good stuff.  RE: name, ``pyrexmd`` might be enough?

**Comment by ArtVoro** [comment]
funny i was thinking the same. typically people in this field use REMD for Replica Exchange Molecular Dynamics but i really love REX so i tryed to stick to that.

**Comment by ArtVoro** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03287/joss.03287/10.21105.joss.03287.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03287/joss.03287/10.21105.joss.03287.pdf) :page_facing_up: :point_left:

**Comment by ArtVoro** [comment]
@jgostick 

1) i renamed the package to `pyrexMD` and fixed all files where i call it
2) i managed to build some api doc with sphinx, will add some stuff later to pep it up a bit
3) i uploaded the doc to github pages and linked it to README

**Comment by ArtVoro** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03287/joss.03287/10.21105.joss.03287.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03287/joss.03287/10.21105.joss.03287.pdf) :page_facing_up: :point_left:

**Comment by ArtVoro** [comment]
@jgostick I added more stuff to docs and reworked the doc tree, should be good now i guess. 

does the package renaming matter and i have to resubmit or is everything fine as it is?

**Comment by ArtVoro** [comment]
i went through the reviewer list and picked some random persons related to MD stuff:

Sulstice, pszi1ard, malramsay64, HaoZeke, jmborr

**Comment by jgostick** [comment]
Great.  I will contact reviewers, and once I've secured a few I will start the review process.  Might take a week or so.

**Comment by jgostick** [comment]
@whedon add @janash as reviewer

**Comment by whedon** [comment]
OK, @janash is now a reviewer

**Comment by jgostick** [comment]
@whedon add @rosecers as reviewer

**Comment by whedon** [comment]
OK, @rosecers is now a reviewer

**Comment by jgostick** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3325.

**Comment by jgostick** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1258

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.34 s (296.4 files/s, 185050.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            24           4781             72          19894
JavaScript                      14           2405           2473           9211
Python                          28           2562           5606           7582
SVG                              1              0              0           2671
CSS                              5            208             45            810
Markdown                         3            176              0            499
Jupyter Notebook                 9              0           2934            344
YAML                             4             18             43            275
TeX                              1             24              0            199
reStructuredText                 8             41             71             43
DOS Batch                        1              8              1             26
make                             1              4              7              9
INI                              1              1              0              8
Bourne Shell                     1              1              0              4
-------------------------------------------------------------------------------
SUM:                           101          10229          11252          41575
-------------------------------------------------------------------------------


Statistical information for the repository '36af739276601c6bc55016be' was
gathered on 2021/08/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ArtVoro                          1            72             12            0.10
Arthur                          79         28523           9930           44.68
Arthur Voronin                  85         28922          18599           55.22

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
ArtVoro                      63           87.5          1.3                4.76
Arthur                    13517           47.4          3.6                9.42
Arthur Voronin            16259           56.2          0.0               16.64
```
