### ISSUE TITLE
[PRE REVIEW]: iharm3D: Vectorized General Relativistic Magnetohydrodynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3288]
**Submitting author:** @bprather (<a href="http://orcid.org/0000-0002-0393-7734">Ben S. Prather</a>)
**Repository:** <a href="https://github.com/AFD-Illinois/iharm3d/" target ="_blank">https://github.com/AFD-Illinois/iharm3d/</a>
**Version:** v3.6-alpha
**Editor:** @eloisabentivegna
**Reviewers:** @bgiacoma, @cpalenzuela
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c1516163ae242984700ebc6e3044f3f5/status.svg)](https://joss.theoj.org/papers/c1516163ae242984700ebc6e3044f3f5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c1516163ae242984700ebc6e3044f3f5"><img src="https://joss.theoj.org/papers/c1516163ae242984700ebc6e3044f3f5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c1516163ae242984700ebc6e3044f3f5/status.svg)](https://joss.theoj.org/papers/c1516163ae242984700ebc6e3044f3f5)
```

**Author instructions**

Thanks for submitting your paper to JOSS @bprather. **Currently, there isn't an JOSS editor assigned** to your paper.

@bprather if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (1073.0 files/s, 166692.1 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
C                                30           1139            853           5237
Python                           31            954            756           4029
C/C++ Header                     14            185            343            643
Bourne Shell                     18            196             88            509
make                              1             32             24             91
Markdown                          1             10              0             53
Bourne Again Shell                3             28             35             19
--------------------------------------------------------------------------------
SUM:                             98           2544           2099          10581
--------------------------------------------------------------------------------


Statistical information for the repository 'a5d9b8b23b93cb5f08372a3b' was
gathered on 2021/05/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ben Prather                    474         62033          36164           80.63
Ben Ryan                        12          8992           6631           12.83
Charles F Gammie                 1             8              0            0.01
Charles F. Gammie                1          5879              0            4.83
George N. Wong                   2             6              4            0.01
George Wong                      4            71             22            0.08
Josh Dolence                     6          1075            341            1.16
Vedant Dhruv                     5            73             21            0.08
cfgammie                         1             2              1            0.00
e-petersen                       1             1              1            0.00
jdolence                         2            60            399            0.38

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ben Prather               11363           18.3         32.5               13.17
Ben Ryan                   2683           29.8         42.3               16.73
George Wong                  74          104.2          7.0                5.41
Vedant Dhruv                 53           72.6          8.3                5.66
cfgammie                      1           50.0         29.7              100.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3288 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03288/joss.03288/10.21105.joss.03288.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03288/joss.03288/10.21105.joss.03288.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper-branch
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1186/s40668-017-0020-2 is OK
- 10.1093/mnras/stx364 is OK
- 10.1086/374594 is OK
- 10.1086/422244 is OK
- 10.1086/154565 is OK
- 10.1088/0004-637X/807/1/31 is OK
- 10.1126/sciadv.aaz1310 is OK
- 10.1111/j.1365-2966.2012.22002.x is OK
- 10.1006/jcph.2000.6519 is OK
- 10.3847/0067-0049/225/2/22 is OK
- 10.1093/mnras/sts632 is OK
- 10.1093/mnras/stt2479 is OK
- 10.1007/BF00165988 is OK
- 10.1093/mnras/stw1526 is OK
- 10.3847/2041-8213/ab1141 is OK
- 10.3847/2041-8213/ab0f43 is OK
- 10.3847/2041-8213/ab0e85 is OK
- 10.3847/2041-8213/ab0c57 is OK
- 10.3847/2041-8213/ab0c96 is OK
- 10.3847/2041-8213/ab0ec7 is OK
- 10.1146/annurev-astro-082812-141003 is OK
- 10.1093/mnras/stx3162 is OK
- 10.1086/500349 is OK
- 10.1093/mnras/208.4.721 is OK
- 10.3847/1538-4357/aa6a52 is OK
- 10.3847/1538-4365/ab29fd is OK
- 10.12942/lrr-2013-1 is OK
- 10.1111/j.1745-3933.2010.00958.x is OK
- 10.3847/1538-4357/ab86ac is OK
- 10.1146/annurev.aa.19.090181.001033 is OK
- 10.1146/annurev.aa.33.090195.002445 is OK
- 10.1146/annurev.astro.34.1.703 is OK
- 10.1086/170270 is OK
- 10.1016/j.jpdc.2014.07.003 is OK
- 10.1093/pasj/55.6.L69 is OK
- 10.1007/s41115-017-0002-8 is OK
- 10.1093/mnras/staa826 is OK
- 10.1086/176343 is OK
- 10.1088/0264-9381/24/12/S17 is OK
- 10.1007/BF00642237 is OK
- 10.1088/0004-637X/701/2/1175 is OK
- 10.1088/0004-637X/752/2/123 is OK
- 10.1051/0004-6361/201526630 is OK
- 10.3847/0004-637X/822/1/34 is OK
- 10.1088/0264-9381/32/17/175009 is OK
- 10.1093/mnras/stv2084 is OK
- 10.1088/0067-0049/201/2/9 is OK
- 10.1088/0004-637X/796/1/22 is OK
- 10.1086/497294 is OK
- 10.1086/308344 is OK
- 10.1016/j.jcp.2003.09.016 is OK
- 10.1086/500349 is OK
- 10.1088/0004-637X/755/1/51 is OK
- 10.1088/0004-637X/692/1/411 is OK
- 10.1088/0264-9381/31/6/065013 is OK
- 10.3847/2041-8213/aaa756 is OK
- 10.3847/2041-8213/ab0ec7 is OK
- 10.3847/2041-8213/ab0c96 is OK
- 10.3847/2041-8213/ab0c57 is OK
- 10.3847/2041-8213/ab0e85 is OK
- 10.3847/2041-8213/ab0f43 is OK
- 10.3847/2041-8213/ab1141 is OK
- 10.3847/2041-8213/abe4de is OK
- 10.3847/1538-4357/ab96c6 is OK
- 10.3847/2041-8213/abe71d is OK
- 10.3847/1538-4357/abac0d is OK

MISSING DOIs

- 10.3847/1538-4357/abee13 may be a valid DOI for title: The Role of Adaptive Ray Tracing in Analyzing Black Hole Structure
- 10.1093/mnras/staa955 may be a valid DOI for title: Large-Scale Poloidal Magnetic Field Dynamo Leads to Powerful Jets in GRMHD Simulations of Black Hole Accretion with Toroidal Field
- 10.1073/pnas.1812491116 may be a valid DOI for title: Thermal disequilibration of ions and electrons by collisionless plasma turbulence
- 10.3847/1538-4357/ab0c0c may be a valid DOI for title: A Resolution Study of Magnetically Arrested Disks
- 10.1093/mnras/staa2692 may be a valid DOI for title: Decomposing the Internal Faraday Rotation of Black Hole Accretion Flows
- 10.1109/tpds.2020.3010016 may be a valid DOI for title: K-Athena: a performance portable structured grid finite volume magnetohydrodynamics code

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@bprather - if you have time, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. You could also remove any entries from your bib file that are not actually referenced, if there are any, which will make this process easier.  Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @eloisabentivegna - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @eloisabentivegna as editor

**Comment by whedon** [comment]
@eloisabentivegna has been invited to edit this submission.

**Comment by bprather** [comment]
@whedon check references

**Comment by eloisabentivegna** [comment]
> 👋 @eloisabentivegna - would you be able to edit this submission?

Sure thing!

**Comment by eloisabentivegna** [comment]
@whedon assign @eloisabentivegna as editor

**Comment by whedon** [comment]
OK, the editor is @eloisabentivegna

**Comment by bprather** [comment]
@eloisabentivegna Thanks for taking this on!

@danielskatz is there something I'm missing activating whedon?  In any case I've taken another look at the references and I believe all the missing DOIs should be fixed in 'joss-paper-branch'

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper-branch

I'm not sure why this didn't work - let's just try it again.  If it fails, there's perhaps a problem in the bib file that is causing it to fail silently.  If this happens, we might try to generate the PDF and see if that tells us the error

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper-branch
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3847/1538-4365/ab29fd is OK
- 10.12942/lrr-2013-1 is OK
- 10.1093/mnras/sts632 is OK
- 10.1093/mnras/stt2479 is OK
- 10.1007/BF00165988 is OK
- 10.1093/mnras/stw1526 is OK
- 10.3847/2041-8213/ab1141 is OK
- 10.3847/2041-8213/ab0f43 is OK
- 10.3847/2041-8213/ab0e85 is OK
- 10.3847/2041-8213/ab0c57 is OK
- 10.3847/2041-8213/ab0c96 is OK
- 10.3847/2041-8213/ab0ec7 is OK
- 10.1146/annurev-astro-082812-141003 is OK
- 10.1093/mnras/stx3162 is OK
- 10.1086/500349 is OK
- 10.1093/mnras/208.4.721 is OK
- 10.3847/1538-4357/aa6a52 is OK
- 10.1006/jcph.2000.6519 is OK
- 10.3847/0067-0049/225/2/22 is OK
- 10.1186/s40668-017-0020-2 is OK
- 10.1093/mnras/stx364 is OK
- 10.1086/374594 is OK
- 10.1086/422244 is OK
- 10.1086/154565 is OK
- 10.1088/0004-637X/807/1/31 is OK
- 10.1111/j.1365-2966.2012.22002.x is OK
- 10.1126/sciadv.aaz1310 is OK
- 10.1111/j.1745-3933.2010.00958.x is OK
- 10.3847/1538-4357/ab86ac is OK
- 10.1088/0264-9381/32/17/175009 is OK
- 10.3847/0004-637X/822/1/34 is OK
- 10.1051/0004-6361/201526630 is OK
- 10.1088/0004-637X/752/2/123 is OK
- 10.1088/0004-637X/701/2/1175 is OK
- 10.1007/BF00642237 is OK
- 10.1088/0264-9381/24/12/S17 is OK
- 10.1086/176343 is OK
- 10.1093/mnras/staa826 is OK
- 10.1007/s41115-017-0002-8 is OK
- 10.1093/pasj/55.6.L69 is OK
- 10.1016/j.jpdc.2014.07.003 is OK
- 10.1086/170270 is OK
- 10.1146/annurev.astro.34.1.703 is OK
- 10.1146/annurev.aa.33.090195.002445 is OK
- 10.1146/annurev.aa.19.090181.001033 is OK
- 10.3847/2041-8213/aaa756 is OK
- 10.1088/0264-9381/31/6/065013 is OK
- 10.1088/0004-637X/692/1/411 is OK
- 10.1088/0004-637X/755/1/51 is OK
- 10.1016/j.jcp.2003.09.016 is OK
- 10.1086/308344 is OK
- 10.1086/497294 is OK
- 10.1088/0004-637X/796/1/22 is OK
- 10.1088/0067-0049/201/2/9 is OK
- 10.1093/mnras/stv2084 is OK
- 10.1093/mnras/staa955 is OK
- 10.1073/pnas.1812491116 is OK
- 10.3847/1538-4357/ab0c0c is OK
- 10.1093/mnras/staa2692 is OK
- 10.1109/TPDS.2020.3010016 is OK
- 10.3847/1538-4357/abee13 is OK
- 10.3847/2041-8213/ab0ec7 is OK
- 10.3847/2041-8213/ab0c96 is OK
- 10.3847/2041-8213/ab0c57 is OK
- 10.3847/2041-8213/ab0e85 is OK
- 10.3847/2041-8213/ab0f43 is OK
- 10.3847/2041-8213/ab1141 is OK
- 10.3847/2041-8213/abe4de is OK
- 10.3847/1538-4357/ab96c6 is OK
- 10.3847/2041-8213/abe71d is OK
- 10.3847/1538-4357/abac0d is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by bprather** [comment]
Thanks!  I guess @whedon just doesn't like me...

**Comment by eloisabentivegna** [comment]
@bgiacoma, @pmoesta, would you be able to review this submission?

**Comment by bgiacoma** [comment]
> @bgiacoma, @pmoesta, would you be able to review this submission?

@eloisabentivegna can I have more details? Do I have to review a paper or the code? What is the deadline?

**Comment by eloisabentivegna** [comment]
@bgiacoma, I will send you an email with all the details. In the meantime, you can take a look here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

**Comment by bgiacoma** [comment]
@eloisabentivegna I received the email and I also had a look at the guidelines. Are the authors the same ones listed as contributors in the github repository of the code? Just to be sure that there are no conflict of interests.

**Comment by eloisabentivegna** [comment]
@bgiacoma, you can take a look at the [paper draft](https://github.com/openjournals/joss-papers/blob/joss.03288/joss.03288/10.21105.joss.03288.pdf). The author list usually coincides with the set of code authors, but sometimes there are reasons why it does not. The author list in the paper is the one you should keep in mind (although check the [JOSS COI policy](https://github.com/openjournals/joss/blob/master/COI.md) for sources of conflict that go beyond direct collaboration with the individual authors).

**Comment by bgiacoma** [comment]
@eloisabentivegna thanks, I checked the list of authors in the draft and I do not see any conflict of interests.

**Comment by eloisabentivegna** [comment]
@TomGoffrey, would you be able to provide a review for this submission?

**Comment by eloisabentivegna** [comment]
@tomidakn, @felker, would you be able to provide a review for this submission to JOSS?

**Comment by felker** [comment]
Unfortunately I cannot, but I would suggest to the authors to change the reference for Athena++: https://ui.adsabs.harvard.edu/abs/2020ApJS..249....4S/abstract

See details here: https://github.com/PrincetonUniversity/athena

**Comment by bprather** [comment]
@whedon generate pdf from branch joss-paper-branch

@felker Thanks! Apologies for the omission, it should be fixed now.

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03288/joss.03288/10.21105.joss.03288.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03288/joss.03288/10.21105.joss.03288.pdf) :page_facing_up: :point_left:

**Comment by tomidakn** [comment]
I'm sorry but I am very busy and cannot review it.

**Comment by pmoesta** [comment]
sorry for the delay but I am currently also unable to review this.

Philipp

**Comment by eloisabentivegna** [comment]
@whedon add @bgiacoma as reviewer

**Comment by whedon** [comment]
OK, @bgiacoma is now a reviewer

**Comment by eloisabentivegna** [comment]
@whedon add @cpalenzuela as reviewer

**Comment by whedon** [comment]
OK, @cpalenzuela is now a reviewer

**Comment by eloisabentivegna** [comment]
@bgiacoma, @cpalenzuela, thanks for accepting to review this submission! I will now close the pre-review issue and start the actual review.

**Comment by eloisabentivegna** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3336.
