### ISSUE TITLE
[PRE REVIEW]: bsym - a basic symmetry module

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#329]
**Submitting author:** @bjmorgan (<a href="http://orcid.org/0000-0002-3056-8233">Benjamin J. Morgan</a>)
**Repository:** <a href="https://github.com/bjmorgan/bsym" target ="_blank">https://github.com/bjmorgan/bsym</a>
**Version:** v1.0.b1
**Editor:** @labarba
**Reviewer:** @aronwalsh

**Author instructions**

Thanks for submitting your paper to JOSS @bjmorgan. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bjmorgan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @labarba - the submitting author suggested you as an editor.

**Comment by bjmorgan** [comment]
Potential reviewers:

From the JOSS list:
- khinsen
- jochym

Possible other reviewers:
- Adam Jackson: https://github.com/ajjackson
- [Aron Walsh](http://www.imperial.ac.uk/people/a.walsh): https://github.com/aronwalsh
- [Paul Erhart](https://www.chalmers.se/en/staff/Pages/Paul-Erhart.aspx): https://gitlab.com/erhart

**Comment by labarba** [comment]
Thank you , @bjmorgan, for suggesting reviewers… most helpful!

I was about to send an email to request a review from Dr. Kristin A. Persson (or someone she might recommend). Seem appropriate?
http://perssongroup.lbl.gov/people.html

**Comment by labarba** [comment]
In the meantime, I wonder if you could take the time to expand a little the description in the paper. We (the JOSS editors) are in the process of adding more guidance for authors, including a better indication of expected paper length. We think it's hard to get a picture of the functionality of the software, and also include a statement of need, in less than 250 words. One reason is that JOSS is welcoming software from a wide variety of fields, and we need the papers to illustrate the purpose of the software, for diverse, non-specialist readers.

**Comment by bjmorgan** [comment]
Dr. Persson would be a very appropriate suggestion.

**Comment by bjmorgan** [comment]
@labarba I have rewritten my `paper.md` to give a more detailed explanation of the intended purpose of the software.

https://github.com/bjmorgan/bsym/commit/25eca0997802ae5cbe72ea29875c5204dcbdb6e2

**Comment by labarba** [comment]
I am currently waiting on email response for reviewer assignment.

**Comment by labarba** [comment]
Update — I have contacted two potential reviewers, who have now both declined. I will look into the author-recommended reviewers now.

**Comment by labarba** [comment]
@whedon assign @aronwalsh as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @aronwalsh

**Comment by labarba** [comment]
@whedon start review magicword=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/370. Feel free to close this issue now!
