### ISSUE TITLE
[PRE REVIEW]: demographicx: A Python package for estimating gender and ethnicity using deep learning transformers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3299]
**Submitting author:** @daniel-acuna (<a href="http://orcid.org/0000-0002-7765-1595">Daniel E. Acuna</a>)
**Repository:** <a href="https://github.com/sciosci/demographicx" target ="_blank">https://github.com/sciosci/demographicx</a>
**Version:** 0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/73c63bdd5c907017f15c09e7d70ea82e/status.svg)](https://joss.theoj.org/papers/73c63bdd5c907017f15c09e7d70ea82e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/73c63bdd5c907017f15c09e7d70ea82e"><img src="https://joss.theoj.org/papers/73c63bdd5c907017f15c09e7d70ea82e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/73c63bdd5c907017f15c09e7d70ea82e/status.svg)](https://joss.theoj.org/papers/73c63bdd5c907017f15c09e7d70ea82e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @daniel-acuna. **Currently, there isn't an JOSS editor assigned** to your paper.

@daniel-acuna if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (166.3 files/s, 13775.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           8            160            120            433
Markdown                         3             51              0            139
TeX                              1             15              4             72
-------------------------------------------------------------------------------
SUM:                            12            226            124            644
-------------------------------------------------------------------------------


Statistical information for the repository 'fff43f5e46c9dea33b9ac6ce' was
gathered on 2021/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel Acuna                     4           186            147           29.44
LiamLiang                        7           727             53           68.97
jim                              4             9              9            1.59

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel Acuna                177           95.2          0.2                2.82
Lizhen Liang                532          100.0          0.2                9.77
jim                           4           44.4          0.4                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.31219/osf.io/ybfk6 is OK
- 10.1145/1557019.1557032 is OK
- 10.1126/science.1196783 is OK
- 10.1038/504211a is OK
- 10.13012/B2IDB-9087546_V1 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1145/3461702.3462616 is INVALID
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03299/joss.03299/10.21105.joss.03299.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03299/joss.03299/10.21105.joss.03299.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @daniel-acuna, thanks for resubmitting this (for reference, the original rejected submission was #3263). However, at a bit over 400 lines of code, your submission is still quite on the small side—we flag anything under 1000 for review by the editorial board to see if this meets our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) requirements.

We will review this and get back to you in a week or so.

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by daniel-acuna** [comment]
Thanks so much for the consideration @kyleniemeyer! We thought this software would fit under the [Co-publication of science](https://joss.readthedocs.io/en/latest/submitting.html#co-publication-of-science-methods-and-software) criteria: 
```JOSS considers submissions for which the implementation of the software itself reflects a substantial scientific effort. This may be represented by the design of the software, the implementation of the algorithms, creation of tutorials, or any other aspect of the software. We ask that authors indicate whether related publications (published, in review, or nearing submission) exist as part of submitting to JOSS.```  because it is part of the AIES 2021 paper https://osf.io/75qfs/ presented yesterday in the conference.

Sincerely,
Daniel

**Comment by kyleniemeyer** [comment]
@daniel-acuna yes, the issue is mainly the relatively small size of the software package. Also, it looks to me like the software is mostly based on a pre-trained machine learning model, which would [not be in scope](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software). But, others may have a different view, hence the review by the board overall.

**Comment by arfon** [comment]
@daniel-acuna – thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by daniel-acuna** [comment]
> @daniel-acuna – thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.
> 
> One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

Thanks for the time to look into it! We'll create this id for our repo and share the manuscript in some other way.
