### ISSUE TITLE
[PRE REVIEW]: Spectrum: Spectral Analysis in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#330]
**Submitting author:** @cokelaer (<a href="http://orcid.org/0000-0001-6286-1138">Thomas Cokelaer</a>)
**Repository:** <a href="https://github.com/cokelaer/spectrum" target ="_blank">https://github.com/cokelaer/spectrum</a>
**Version:** 0.6.2
**Editor:** @arfon
**Reviewer:** @eteq

**Author instructions**

Thanks for submitting your paper to JOSS @cokelaer. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@cokelaer if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jakevdp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @jakevdp - the submitting author suggested you as an editor.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@eteq - would you be willing to review this submission for JOSS?

**Comment by eteq** [comment]
@arfon - yes, can do.

**Comment by arfon** [comment]
@whedon assign @eteq as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @eteq

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/348. Feel free to close this issue now!
