### ISSUE TITLE
[PRE REVIEW]: VecComp: A Python package for Quantitative Vector Field Comparison Metrics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3300]
**Submitting author:** @MatthiasProbst (<a href="http://orcid.org/0000-0001-8729-0482">Matthias Probst</a>)
**Repository:** <a href="https://git.scc.kit.edu/da4323/VecComp" target ="_blank">https://git.scc.kit.edu/da4323/VecComp</a>
**Version:** v.0.2.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e62d7f7ff70da480f4953e063461ada0/status.svg)](https://joss.theoj.org/papers/e62d7f7ff70da480f4953e063461ada0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e62d7f7ff70da480f4953e063461ada0"><img src="https://joss.theoj.org/papers/e62d7f7ff70da480f4953e063461ada0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e62d7f7ff70da480f4953e063461ada0/status.svg)](https://joss.theoj.org/papers/e62d7f7ff70da480f4953e063461ada0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @MatthiasProbst. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kyleniemeyer.

@MatthiasProbst if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (297.8 files/s, 47427.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            334            613            736
TeX                              3             57             10            376
Markdown                         3             33              0            128
Jupyter Notebook                 1              0            178             83
-------------------------------------------------------------------------------
SUM:                            16            424            801           1323
-------------------------------------------------------------------------------


Statistical information for the repository '30a5b66e6d87acff54590c3c' was
gathered on 2021/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Matthias Probst                 49          4089           2910           88.14
uyegh                           20           723            219           11.86

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Matthias Probst            1636           40.0          0.1                4.83
uyegh                        47            6.5          0.3                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03300/joss.03300/10.21105.joss.03300.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03300/joss.03300/10.21105.joss.03300.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1007/978-3-540-89689-0_23 may be a valid DOI for title: Measuring the similarity of vector fields using global distributions
- 10.1136/neurintsurg-2014-011468 may be a valid DOI for title: Computational fluid dynamics with stents: quantitative comparison with particle image velocimetry for three commercial off the shelf intracranial stents
- 10.1007/s10872-017-0419-z may be a valid DOI for title: Validation of gridded data set of global surface wind/wind-stress vector field
- 10.1007/s00348-020-2897-9 may be a valid DOI for title: Quantitative metrics for comparison of in-cylinder velocity fields using particle image velocimetry
- 10.2172/809603 may be a valid DOI for title: Verification, validation, and predictive capability in computational engineering and physics
- 10.1007/bf03181944 may be a valid DOI for title: Unsteady flow visualization at part-load conditions of a radial diffuser pump: by PIV and CFD
- 10.1115/1.4037792 may be a valid DOI for title: Methodology for computational fluid dynamic validation for medical use: application to intracranial aneurysm
- 10.3174/ajnr.a3793 may be a valid DOI for title: Mind the gap: impact of computational fluid dynamics solution strategy on prediction of intracranial aneurysm hemodynamics and rupture status indicators

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hello @MatthiasProbst, thanks for your interest in JOSS. Because of the relatively small size of your submission, the editorial board is going to review your submission to see if it meets our standards for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). We will review and get back to you in a week or so.

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
:wave: @MatthiasProbst – thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
