### ISSUE TITLE
[PRE REVIEW]: LDDS: Python package for computing and visualizing Lagrangian Descriptors for Dynamical Systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3301]
**Submitting author:** @Shibabrat (<a href="http://orcid.org/0000-0001-7964-2513">Shibabrat Naik</a>)
**Repository:** <a href="https://github.com/champsproject/ldds" target ="_blank">https://github.com/champsproject/ldds</a>
**Version:** v0.1.0
**Editor:** @richardjgowers
**Reviewers:** @nicoguaro, @jmbr
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/708c2c717f803733ce017abb10f06030/status.svg)](https://joss.theoj.org/papers/708c2c717f803733ce017abb10f06030)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/708c2c717f803733ce017abb10f06030"><img src="https://joss.theoj.org/papers/708c2c717f803733ce017abb10f06030/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/708c2c717f803733ce017abb10f06030/status.svg)](https://joss.theoj.org/papers/708c2c717f803733ce017abb10f06030)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Shibabrat. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dpsanders.

@Shibabrat if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3301 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (366.0 files/s, 93000.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                12              0           6577            749
Python                          13            515           1068            744
TeX                              1             61              0            563
Markdown                         5            167              0            352
reStructuredText                 9            192            174            165
YAML                             2              8             11             32
DOS Batch                        1              8              1             26
make                             1              4              7              9
Bourne Shell                     1              1              0              1
-------------------------------------------------------------------------------
SUM:                            45            956           7838           2641
-------------------------------------------------------------------------------


Statistical information for the repository 'd3ed551376e6408aca0c7b70' was
gathered on 2021/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Broncio                         58          3041            992            6.29
Víctor                           1             0            165            0.26
shibabrat                       29         28165          28485           88.35
vkrajnak                        76          1990           1284            5.11

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Broncio                     930           30.6          4.8               12.04
shibabrat                   345            1.2          3.3               28.41
vkrajnak                   1052           52.9          3.8                6.84
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/RevModPhys.64.795 is OK
- 10.1111/j.1365-2966.2005.09237.x is OK
- 10.1063/1.166509 is OK
- 10.1063/1.4915831 is OK
- 10.5281/zenodo.4539666 is OK
- 10.1007/BF00375090 is OK
- 10.1134/S1560354716060034 is OK
- 10.5281/zenodo.3958985 is OK
- 10.1016/j.compfluid.2016.07.007 is OK
- 10.1016/j.jocs.2014.12.002 is OK
- 10.1063/1.4795749 is OK
- 10.1017/jfm.2020.737 is OK
- 10.1142/S0218127420300086 is OK
- 10.1142/S0218127420500765 is OK
- 10.1088/1751-8121/ab8b75 is OK
- 10.1039/D0CP01362E is OK
- 10.1007/s00382-019-04832-y is OK
- 10.1007/s00382-019-04833-x is OK
- 10.1103/PhysRevE.100.022204 is OK
- 10.1142/S021812741750225X is OK
- 10.1016/j.cnsns.2019.104907 is OK
- 10.1175/JAS-D-11-0142.1 is OK
- 10.1134/S1560354718050052 is OK
- 10.1016/j.marpolbul.2016.08.018 is OK
- 10.4249/scholarpedia.6327 is OK
- 10.1002/9780470977859 is OK
- 10.1016/j.physd.2005.10.007 is OK
- 10.1016/j.cnsns.2015.02.022 is OK
- 10.1142/S0218127417300014 is OK
- 10.1038/s41598-018-23028-8 is OK
- 10.1088/1751-8121/ab8b75 is OK

MISSING DOIs

- 10.1201/9781003069515-39 may be a valid DOI for title: Transport in Hamiltonian systems
- 10.1007/978-1-4612-4312-0 may be a valid DOI for title: Normally hyperbolic invariant manifolds in dynamical systems
- 10.1016/0167-2789(90)90040-v may be a valid DOI for title: Geometry and dynamics of stable and unstable cylinders in  Hamiltonian systems
- 10.1017/s0022112090000167 may be a valid DOI for title: An analytical study of transport, mixing and chaos in an unsteady vortical flow
- 10.1016/j.cnsns.2013.05.002 may be a valid DOI for title: Lagrangian Descriptors: A method for Revealing Phase Space Structures of General Time Dependent Dynamical Systems
- 10.1175/jas-d-12-0274.1 may be a valid DOI for title: Isentropic transport within the Antarctic polar night vortex: Rossby wave breaking evidence and Lagrangian structures.
- 10.1103/physreve.99.032221 may be a valid DOI for title: Unveiling the chaotic structure in phase space of molecular systems using Lagrangian descriptors
- 10.1142/s0218127416300366 may be a valid DOI for title: Lagrangian Descriptors for Stochastic Differential Equations: A Tool for Revealing the Phase Portrait of Stochastic Dynamical Systems
- 10.1039/c7cp05912d may be a valid DOI for title: Detecting reactive islands using Lagrangian descriptors and the relevance to transition path sampling
- 10.1016/j.cplett.2017.09.008 may be a valid DOI for title: Obtaining time-dependent multi-dimensional dividing surfaces using Lagrangian descriptors
- 10.1063/1.4997379 may be a valid DOI for title: Chemical dynamics between wells across a time-dependent barrier: Self-similarity in the Lagrangian descriptor and reactive basins
- 10.1103/physrevlett.115.148301 may be a valid DOI for title: Lagrangian descriptors of thermalized transition states on time-varying energy surfaces
- 10.1103/physreve.96.022222 may be a valid DOI for title: Lagrangian descriptors of driven chemical reaction manifolds
- 10.1039/c5cp06624g may be a valid DOI for title: Deconstructing field-induced ketene isomerization through Lagrangian descriptors
- 10.1007/s12043-008-0103-3 may be a valid DOI for title: Visual explorations of dynamics: The standard map
- 10.1086/109234 may be a valid DOI for title: The Applicability of the Third Integral Of Motion: Some Numerical Experiments

INVALID DOIs

- https://doi.org/10.1016/j.ijmecsci.2017.10.040 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cnsns.2019.105033 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cplett.2020.137199 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cnsns.2020.105331 is INVALID because of 'https://doi.org/' prefix
```

**Comment by kyleniemeyer** [comment]
@whedon invite @richardjgowers as editor

@richardjgowers this is a bit outside your area, but could you edit this submission?

**Comment by whedon** [comment]
@richardjgowers has been invited to edit this submission.

**Comment by vkrajnak** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03301/joss.03301/10.21105.joss.03301.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03301/joss.03301/10.21105.joss.03301.pdf) :page_facing_up: :point_left:

**Comment by vkrajnak** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03301/joss.03301/10.21105.joss.03301.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03301/joss.03301/10.21105.joss.03301.pdf) :page_facing_up: :point_left:

**Comment by richardjgowers** [comment]
@kyleniemeyer yeah I'm a little busy this week but I can get the ball rolling this weekend.

**Comment by broncio123** [comment]
Hi,

We would like to suggest as potential reviewers:

* Brandon Behring, we couldn't find his email. Only contact through [Linkedin](https://www.linkedin.com/in/brandon-behring-a1738419b/)
* Josh Karpel, josh.karpel@gmail.com
* Ingmar Schoegl, ischoegl@lsu.edu
* Niall McGinness, njwmcginness@gmail.com
* David Ignacio Cortes, dic1e13@soton.ac.uk
* Nicolás Guarín-Zapata, nicoguarin@gmail.com
* Jun Zhong, jun_zhong@brown.edu

**Comment by broncio123** [comment]
> PDF failed to compile for issue #3301 with the following error:
> 
> ```
>  /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
> 	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
> 	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
> 	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
> 	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
> 	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
> 	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
> 	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
> 	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
> 	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
> 	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
> 	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'
> ```

Added date to header of `paper.md`

**Comment by broncio123** [comment]
> ```
> Reference check summary (note 'MISSING' DOIs are suggestions that need verification):
> 
> OK DOIs
> 
> - 10.1103/RevModPhys.64.795 is OK
> - 10.1111/j.1365-2966.2005.09237.x is OK
> - 10.1063/1.166509 is OK
> - 10.1063/1.4915831 is OK
> - 10.5281/zenodo.4539666 is OK
> - 10.1007/BF00375090 is OK
> - 10.1134/S1560354716060034 is OK
> - 10.5281/zenodo.3958985 is OK
> - 10.1016/j.compfluid.2016.07.007 is OK
> - 10.1016/j.jocs.2014.12.002 is OK
> - 10.1063/1.4795749 is OK
> - 10.1017/jfm.2020.737 is OK
> - 10.1142/S0218127420300086 is OK
> - 10.1142/S0218127420500765 is OK
> - 10.1088/1751-8121/ab8b75 is OK
> - 10.1039/D0CP01362E is OK
> - 10.1007/s00382-019-04832-y is OK
> - 10.1007/s00382-019-04833-x is OK
> - 10.1103/PhysRevE.100.022204 is OK
> - 10.1142/S021812741750225X is OK
> - 10.1016/j.cnsns.2019.104907 is OK
> - 10.1175/JAS-D-11-0142.1 is OK
> - 10.1134/S1560354718050052 is OK
> - 10.1016/j.marpolbul.2016.08.018 is OK
> - 10.4249/scholarpedia.6327 is OK
> - 10.1002/9780470977859 is OK
> - 10.1016/j.physd.2005.10.007 is OK
> - 10.1016/j.cnsns.2015.02.022 is OK
> - 10.1142/S0218127417300014 is OK
> - 10.1038/s41598-018-23028-8 is OK
> - 10.1088/1751-8121/ab8b75 is OK
> 
> MISSING DOIs
> 
> - 10.1201/9781003069515-39 may be a valid DOI for title: Transport in Hamiltonian systems
> - 10.1007/978-1-4612-4312-0 may be a valid DOI for title: Normally hyperbolic invariant manifolds in dynamical systems
> - 10.1016/0167-2789(90)90040-v may be a valid DOI for title: Geometry and dynamics of stable and unstable cylinders in  Hamiltonian systems
> - 10.1017/s0022112090000167 may be a valid DOI for title: An analytical study of transport, mixing and chaos in an unsteady vortical flow
> - 10.1016/j.cnsns.2013.05.002 may be a valid DOI for title: Lagrangian Descriptors: A method for Revealing Phase Space Structures of General Time Dependent Dynamical Systems
> - 10.1175/jas-d-12-0274.1 may be a valid DOI for title: Isentropic transport within the Antarctic polar night vortex: Rossby wave breaking evidence and Lagrangian structures.
> - 10.1103/physreve.99.032221 may be a valid DOI for title: Unveiling the chaotic structure in phase space of molecular systems using Lagrangian descriptors
> - 10.1142/s0218127416300366 may be a valid DOI for title: Lagrangian Descriptors for Stochastic Differential Equations: A Tool for Revealing the Phase Portrait of Stochastic Dynamical Systems
> - 10.1039/c7cp05912d may be a valid DOI for title: Detecting reactive islands using Lagrangian descriptors and the relevance to transition path sampling
> - 10.1016/j.cplett.2017.09.008 may be a valid DOI for title: Obtaining time-dependent multi-dimensional dividing surfaces using Lagrangian descriptors
> - 10.1063/1.4997379 may be a valid DOI for title: Chemical dynamics between wells across a time-dependent barrier: Self-similarity in the Lagrangian descriptor and reactive basins
> - 10.1103/physrevlett.115.148301 may be a valid DOI for title: Lagrangian descriptors of thermalized transition states on time-varying energy surfaces
> - 10.1103/physreve.96.022222 may be a valid DOI for title: Lagrangian descriptors of driven chemical reaction manifolds
> - 10.1039/c5cp06624g may be a valid DOI for title: Deconstructing field-induced ketene isomerization through Lagrangian descriptors
> - 10.1007/s12043-008-0103-3 may be a valid DOI for title: Visual explorations of dynamics: The standard map
> - 10.1086/109234 may be a valid DOI for title: The Applicability of the Third Integral Of Motion: Some Numerical Experiments
> 
> INVALID DOIs
> 
> - https://doi.org/10.1016/j.ijmecsci.2017.10.040 is INVALID because of 'https://doi.org/' prefix
> - https://doi.org/10.1016/j.cnsns.2019.105033 is INVALID because of 'https://doi.org/' prefix
> - https://doi.org/10.1016/j.cplett.2020.137199 is INVALID because of 'https://doi.org/' prefix
> - https://doi.org/10.1016/j.cnsns.2020.105331 is INVALID because of 'https://doi.org/' prefix
> ```

Fixed DOIs in `paper.bib`

**Comment by vkrajnak** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3301 with the following error: 
```
 Error reading bibliography file paper.bib:
(line 483, column 9):
unexpected "N"
expecting space, ",", white space or "}"
Looks like we failed to compile the PDF

```

**Comment by vkrajnak** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03301/joss.03301/10.21105.joss.03301.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03301/joss.03301/10.21105.joss.03301.pdf) :page_facing_up: :point_left:

**Comment by vkrajnak** [comment]
The paper is all good now.

**Comment by richardjgowers** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by richardjgowers** [comment]
@nicoguaro @davidcortesortuno would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by nicoguaro** [comment]
@richardjgowers, I think that I can review it.

**Comment by Shibabrat** [comment]
Hi @kyleniemeyer @richardjgowers, can we help with moving this pre-review to the next step? We appreciate your time and consideration in finding the reviewers. 

Sincerely,
Authors

**Comment by richardjgowers** [comment]
@whedon add @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, @nicoguaro is now a reviewer

**Comment by richardjgowers** [comment]
@Shibabrat I'm trying a few more people to try and get a second reviewer for this, thanks for your patience.

**Comment by richardjgowers** [comment]
@jmbr would you be interested in reviewing this?

**Comment by jmbr** [comment]
@richardjgowers Yes, count me in.

**Comment by richardjgowers** [comment]
@whedon add @jmbr as reviewer

**Comment by whedon** [comment]
OK, @jmbr is now a reviewer

**Comment by richardjgowers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3482.
