### ISSUE TITLE
[PRE REVIEW]: Nominally: A Name Parser for Record Linkage

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3302]
**Submitting author:** @vaneseltine (<a href="http://orcid.org/0000-0002-9520-1360">Matthew VanEseltine</a>)
**Repository:** <a href="https://github.com/vaneseltine/nominally" target ="_blank">https://github.com/vaneseltine/nominally</a>
**Version:** v1.1.0
**Editor:** @majensen
**Reviewers:** @sara-02, @sap218
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d340ccbed7e8775b9fc3f4d5ee137fa0/status.svg)](https://joss.theoj.org/papers/d340ccbed7e8775b9fc3f4d5ee137fa0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d340ccbed7e8775b9fc3f4d5ee137fa0"><img src="https://joss.theoj.org/papers/d340ccbed7e8775b9fc3f4d5ee137fa0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d340ccbed7e8775b9fc3f4d5ee137fa0/status.svg)](https://joss.theoj.org/papers/d340ccbed7e8775b9fc3f4d5ee137fa0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @vaneseltine. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @lorenanicole.

@vaneseltine if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (617.4 files/s, 75224.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             8              0              0           2041
Python                          21            354            195           1492
Markdown                         4             83              0            339
SVG                              2              0              0            192
reStructuredText                 5             89             47            177
TeX                              1              6              0             61
YAML                             1              1              0             40
-------------------------------------------------------------------------------
SUM:                            42            533            242           4342
-------------------------------------------------------------------------------


Statistical information for the repository 'e18b800ec2334a8f7b5a7996' was
gathered on 2021/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Aru Sahni                        1             1              1            0.01
Brian S. Corbin                  1            82             60            0.38
Derek                           39           935            615            4.18
Derek Gulbranson               147          6896           2543           25.48
Edward Betts                     2             3              2            0.01
Matt VanEseltine               208         11492          14227           69.44
Matthew VanEseltine              5            78             31            0.29
Peter Scott                      4            38             13            0.14
Simeon Visser                    1             3              3            0.02
TyVik                            1             6              6            0.03
abnerjacobsen                    2             4              0            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Derek Gulbranson             10            0.1         59.8               20.00
Matt VanEseltine           2027           17.6         19.5                6.66
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-642-31164-2_3 is OK
- 10.25080/Majora-92bf1922-00a is OK
- 10.21987/70kd-x544 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03302/joss.03302/10.21105.joss.03302.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03302/joss.03302/10.21105.joss.03302.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @vaneseltine, thanks for your interest in JOSS. Due to low editor availability in this area right now, we have to put your submission on a waitlist. Once an appropriate editor becomes available, we will assign them and move to finding reviewers. In the meantime, if you could suggest some potential reviewers, that would help speed up the process. Thanks!

**Comment by sara-02** [comment]
@kyleniemeyer @vaneseltine I would like to review this package whenever this gets off the waitlist.

**Comment by majensen** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @majensen

**Comment by majensen** [comment]
@sara-02 are you still interested in reviewing [this work](#3302) for JOSS? Thx

**Comment by danielskatz** [comment]
@majensen - thanks!  When you take something from the waiting list, can you also remove the tag, just to keep things clean?

**Comment by majensen** [comment]
@danielskatz sure - sorry about that!

**Comment by danielskatz** [comment]
no worries, just trying to distribute work as we go forward in these overloaded times

**Comment by sara-02** [comment]
> @sara-02 are you still interested in reviewing [this work](#3302) for JOSS? Thx
 Hey @majensen Yes, I am interested in helping with this. However, I am available to review post 27th June onwards.

**Comment by majensen** [comment]
That sounds good @sara-02

**Comment by majensen** [comment]
whedon assign @sara-02 as reviewer

**Comment by majensen** [comment]
@sap218 would you be able to review [this work](#3302) for JOSS? I could use your expertise here.
Thanks for the consideration --@majensen

**Comment by majensen** [comment]
@whedon assign @sara-02 as reviewer

**Comment by whedon** [comment]
OK, @sara-02 is now a reviewer

**Comment by sap218** [comment]
@majensen sorry for the delay - do you still need me as a reviewer?

**Comment by majensen** [comment]
@sap218 yes please! (If you are available)

**Comment by sap218** [comment]
@majensen Yep! I can review! (if you could send me a set of reviewer guidelines to follow - that would be great!)

**Comment by majensen** [comment]
@sap218 that is great. Please have a look at https://joss.readthedocs.io/en/latest/reviewer_guidelines.html and https://joss.readthedocs.io/en/latest/review_criteria.html. A checklist that covers the review areas will show up in the review issue (which will be created once I put the paper in review.) You can check these off as you go through at the top of the review thread.
Very much appreciated!

**Comment by majensen** [comment]
@whedon add @sap218 as reviewer

**Comment by whedon** [comment]
OK, @sap218 is now a reviewer

**Comment by majensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3440.

**Comment by majensen** [comment]
@vaneseltine @sara-02 @sap218 - please join the official review discussion at the new Github issue #3440. Thanks!
