### ISSUE TITLE
[PRE REVIEW]: spopt: a python package for solving spatial optimization problems in PySAL

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3303]
**Submitting author:** @xf37 (<a href="http://orcid.org/0000-0001-7253-3154">Xin Feng</a>)
**Repository:** <a href="https://github.com/pysal/spopt" target ="_blank">https://github.com/pysal/spopt</a>
**Version:** v0.1.1
**Editor:** @vissarion
**Reviewers:** @ArikaLZ, @samuel-rosa 
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1413cf2c0cf3c561386949f2e1208563/status.svg)](https://joss.theoj.org/papers/1413cf2c0cf3c561386949f2e1208563)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1413cf2c0cf3c561386949f2e1208563"><img src="https://joss.theoj.org/papers/1413cf2c0cf3c561386949f2e1208563/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1413cf2c0cf3c561386949f2e1208563/status.svg)](https://joss.theoj.org/papers/1413cf2c0cf3c561386949f2e1208563)
```

**Author instructions**

Thanks for submitting your paper to JOSS @xf37. **Currently, there isn't an JOSS editor assigned** to your paper.

@xf37 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (488.9 files/s, 185784.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              2              0             15           8419
Python                          29           1066           2633           2811
Jupyter Notebook                13              0           9542            641
YAML                            11              7             14            319
Markdown                         3             55              0            164
TeX                              2             20              2            157
CSS                              1             11              3             64
reStructuredText                 5             67             89             58
DOS Batch                        1              8              1             27
make                             1              6              6             16
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            69           1240          12305          12677
-------------------------------------------------------------------------------


Statistical information for the repository 'fae4d82e93e72006bb15854f' was
gathered on 2021/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
James Gaboardi                  35          1217            408            3.60
Serge                            1             7             14            0.05
Serge Rey                       23          2663            296            6.56
Xin Feng                        27         21564            353           48.62
eli knaap                        9            39          17963           39.93
rwei5                            6           304            254            1.24

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
James Gaboardi              934           76.7          9.0                4.60
Serge Rey                  2140           80.4          4.3                9.58
Xin Feng                   3386           15.7          3.7                7.03
eli knaap                    18           46.2          2.0               27.78
rwei5                        32           10.5         20.0               18.75
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3303 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (6de427152a8b225b8de3949c/paper/paper.md): mapping values are not allowed in this context at line 20 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kyleniemeyer** [comment]
Hi @xf37, I think the issue with your paper is in the YAML block at the top—there is an indentation error with the `orcid` field for Sergio Rey.

**Comment by kyleniemeyer** [comment]
@whedon invite @vissarion as editor

Hi @vissarion, could you edit this submission?

**Comment by whedon** [comment]
@vissarion has been invited to edit this submission.

**Comment by jGaboardi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03303/joss.03303/10.21105.joss.03303.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03303/joss.03303/10.21105.joss.03303.pdf) :page_facing_up: :point_left:

**Comment by vissarion** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @vissarion

**Comment by vissarion** [comment]
:wave: @apulverizer, @samuel-rosa, @michstrauch, @ncxiao, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by vissarion** [comment]
Hi, @rowanc1, @sarats, @MichaelHoltonPrice, @PaulDebus, would any of you be willing to review this submission for JOSS?

**Comment by vissarion** [comment]
@whedon add @ArikaLZ as reviewer

**Comment by whedon** [comment]
OK, @ArikaLZ is now a reviewer

**Comment by samuel-rosa** [comment]
@whedon assign me as reviewer

**Comment by whedon** [comment]
I'm sorry @samuel-rosa, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by samuel-rosa** [comment]
Hi @vissarion, you can count on me to review this paper.

**Comment by whedon** [comment]
OK, @samuel-rosa  is now a reviewer

**Comment by vissarion** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3330.
