### ISSUE TITLE
[PRE REVIEW]: LCIA Formatter

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3304]
**Submitting author:** @WesIngwersen (<a href="http://orcid.org/0000-0002-9614-701X">Wesley Ingwersen</a>)
**Repository:** <a href="https://github.com/USEPA/LCIAformatter" target ="_blank">https://github.com/USEPA/LCIAformatter</a>
**Version:** v1.0.0
**Editor:** @csoneson
**Reviewers:** @tngTUDOR, @mfastudillo
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2903a4c2b79558927543544f5b01819a/status.svg)](https://joss.theoj.org/papers/2903a4c2b79558927543544f5b01819a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2903a4c2b79558927543544f5b01819a"><img src="https://joss.theoj.org/papers/2903a4c2b79558927543544f5b01819a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2903a4c2b79558927543544f5b01819a/status.svg)](https://joss.theoj.org/papers/2903a4c2b79558927543544f5b01819a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @WesIngwersen. **Currently, there isn't an JOSS editor assigned** to your paper.

@WesIngwersen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (549.7 files/s, 51708.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          20            354            229           1507
TeX                              1             24              0            183
Markdown                         4             29              0            136
JSON                             1              1              0             54
YAML                             1              7              0             16
-------------------------------------------------------------------------------
SUM:                            27            415            229           1896
-------------------------------------------------------------------------------


Statistical information for the repository '80f8d7b86b1552caf619554c' was
gathered on 2021/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
BMorelli                         8           264             44            6.55
Ben Young                      114          1329            655           42.19
TAHottle                         3            45             22            1.42
WesIngwersen                    22           130             66            4.17
hottleta                         1             5              1            0.13
msrocka                         30          1619            523           45.55

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
BMorelli                    124           47.0          3.2               10.48
Ben Young                   915           68.8          5.2               13.11
WesIngwersen                 78           60.0         16.9                6.41
hottleta                     26          520.0         14.2               11.54
msrocka                     947           58.5         21.0                4.01
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3304 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ecolecon.2008.01.019 is OK
- 10.1007/s11367-017-1354-3 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK

MISSING DOIs

- 10.1007/s10098-010-0338-9 may be a valid DOI for title: TRACI 2.0: the tool for the reduction and assessment of chemical and other environmental impacts 2.0

INVALID DOIs

- 10.23719/1522445 is INVALID
- 10.23719/1522444 is INVALID
- 10.23719/1522413 is INVALID
- 10.23719/1522414 is INVALID
```

**Comment by kyleniemeyer** [comment]
Hi @WesIngwersen, thanks for your interest in JOSS. Due to low editor availability in this area, I am placing your submission on a waitlist for now; once an appropriate editor becomes available, we will get this assigned and move the process forward.

In the meantime, you could address the issues with the references raised above, and also provide reviewer suggestions. Thanks!

**Comment by kyleniemeyer** [comment]
@WesIngwersen regarding the paper generation error, I think you cannot have an empty `orcid` field for an author, so you should just remove that for someone that does not have an ORCID. 

Also, I am not sure that the corresponding author footnote will work. @openjournals/dev is that correct?

**Comment by WesIngwersen** [comment]
FYI co-author @bl-young

**Comment by WesIngwersen** [comment]
@kyleniemeyer, I removed the empty `orcid` field for Michael Srocka with [this commit](https://github.com/USEPA/LCIAformatter/commit/4a43a0c6ee7db3f254d69a109188ed030cdf264f)
and removed the corresponding author note with [this commit](https://github.com/USEPA/LCIAformatter/commit/5ec5dde087c17dea0f17b8dad9bfd16255c07ce9)

**Comment by danielskatz** [comment]
You can use the command `@whedon check references` to check the references, and the command `@whedon generate pdf` to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03304/joss.03304/10.21105.joss.03304.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03304/joss.03304/10.21105.joss.03304.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
Note that there are some potential reference problems flagged above too...

**Comment by WesIngwersen** [comment]
Recommended reviewer:  

1. Chris Mutel, author of [Brightway: An open source framework for Life Cycle Assessment](https://joss.theoj.org/papers/10.21105/joss.00236) and two other JOSS articles
2. James Joyce, author of [Lcopt - An interactive tool for creating fully parameterised Life Cycle Assessment (LCA) foreground models](https://joss.theoj.org/papers/10.21105/joss.00339)
3. Konstantin Stadler, author of [The country converter coco - a Python package for converting country names between different classification schemes](https://joss.theoj.org/papers/10.21105/joss.00332)

All 3 recommended reviewers are PhD level domain experts (in life cycle assessment), Python developers, and have published in JOSS

**Comment by WesIngwersen** [comment]
> Note that there are some potential reference problems flagged above too...

@danielskatz @kyleniemeyer  Regarding DOI issues.  I will address the missing DOI (actually others can be added).  The invalid DOIs are for 4 datasets that are data products of the LCIA formatter software and currently in the cue in the EPA data review/publication system. They should be through that process and registered within a week. I will report back on them once they are registered.

**Comment by WesIngwersen** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10098-010-0338-9 is OK
- 10.1007/s11367-016-1246-y is OK
- 10.1007/s11367-019-01583-0 is OK
- 10.1016/j.ecolecon.2008.01.019 is OK
- 10.1007/s11367-017-1354-3 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK

MISSING DOIs

- None

INVALID DOIs

- 10.23719/1522445 is INVALID
- 10.23719/1522444 is INVALID
- 10.23719/1522413 is INVALID
- 10.23719/1522414 is INVALID
```

**Comment by WesIngwersen** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10098-010-0338-9 is OK
- 10.1007/s11367-016-1246-y is OK
- 10.1007/s11367-019-01583-0 is OK
- 10.1016/j.ecolecon.2008.01.019 is OK
- 10.1007/s11367-017-1354-3 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.23719/1522445 is OK
- 10.23719/1522444 is OK
- 10.23719/1522413 is OK
- 10.23719/1522414 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by WesIngwersen** [comment]
@danielskatz  All DOIs are now active so reference issues are resolved.  FYI co-author @bl-young

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by danielskatz** [comment]
👋 @csoneson - Would you be able to edit this submission?

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03304/joss.03304/10.21105.joss.03304.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03304/joss.03304/10.21105.joss.03304.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋🏻 @cmutel, @pjamesjoyce, @konstantinstadler - would (two of) you be willing to review this submission for JOSS? 

> LCIA Formatter
> This paper describes a USEPA LCA ecosystem tool 'LCIA formatter' that extracts LCIA information from original source methods and converts the data for interoperability with the rest of the USEPA LCA ecosystem tools.

**Comment by konstantinstadler** [comment]
@csoneson : I am on my last days before my vacation so I can not commit to this now. However, it is a very interesting piece of software. If you struggle to find reviewers you can ping me again on the 26th July and I would be happy to do a review then.

**Comment by csoneson** [comment]
@konstantinstadler - thank you! Enjoy your holidays and thanks for the offer - I'll keep you posted!

**Comment by cmutel** [comment]
@csoneson I have a conflict of interest, so don't feel comfortable being a reviewer here.

Here are some possible alternatives: 
@mfastudillo @tngTUDOR @aleksandra-kim

**Comment by csoneson** [comment]
@cmutel - no problem, thanks for the quick response! 

@mfastudillo @tngTUDOR @aleksandra-kim - would one or two of you be up for reviewing this submission for JOSS?

> LCIA Formatter
> This paper describes a USEPA LCA ecosystem tool 'LCIA formatter' that extracts LCIA information from original source methods and converts the data for interoperability with the rest of the USEPA LCA ecosystem tools.

**Comment by tngTUDOR** [comment]
I'm available and willing to review.

**Comment by csoneson** [comment]
Excellent, thank you @tngTUDOR! Once we have secured one more reviewer I will open the actual review issue where you'll find more information, review check list etc.

**Comment by mfastudillo** [comment]
I am available too

**Comment by csoneson** [comment]
Brilliant, thanks @mfastudillo! 
So this means that we have our two reviewers - I'll assign you now and open the review issue.

**Comment by csoneson** [comment]
@whedon assign @tngTUDOR as reviewer

**Comment by whedon** [comment]
OK, @tngTUDOR is now a reviewer

**Comment by csoneson** [comment]
@whedon add @mfastudillo as reviewer

**Comment by whedon** [comment]
OK, @mfastudillo is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3392.
