### ISSUE TITLE
[PRE REVIEW]: Estimating the environmental footprint of food products from packaging data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3306]
**Submitting author:** @GustaveCoste (<a href="http://orcid.org/0000-0001-5867-0507">Gustave Coste</a>)
**Repository:** <a href="https://framagit.org/GustaveCoste/off-product-environmental-impact/" target ="_blank">https://framagit.org/GustaveCoste/off-product-environmental-impact/</a>
**Version:** 1.0.0
**Editor:** @vissarion
**Reviewers:** @marvinjonathcn, @jrising
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/749da99fa06fcde2ee4a2604f196ac64/status.svg)](https://joss.theoj.org/papers/749da99fa06fcde2ee4a2604f196ac64)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/749da99fa06fcde2ee4a2604f196ac64"><img src="https://joss.theoj.org/papers/749da99fa06fcde2ee4a2604f196ac64/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/749da99fa06fcde2ee4a2604f196ac64/status.svg)](https://joss.theoj.org/papers/749da99fa06fcde2ee4a2604f196ac64)
```

**Author instructions**

Thanks for submitting your paper to JOSS @GustaveCoste. **Currently, there isn't an JOSS editor assigned** to your paper.

@GustaveCoste if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3306 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=25.12 s (2.7 files/s, 154478.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              0              0        1935753
JSON                             7              0              0        1935708
Python                          34            946           1005           2727
SVG                              8              0              0           2334
reStructuredText                11            196            278            224
HTML                             1             15              0            217
Markdown                         1             47              0            144
CSS                              2             21             10             82
make                             1              4              6              9
YAML                             1              3              6              7
-------------------------------------------------------------------------------
SUM:                            68           1232           1305        3877205
-------------------------------------------------------------------------------


Statistical information for the repository 'f43c509dbbcba9b87d381165' was
gathered on 2021/05/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Gustave Coste                  153          4182            928          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Gustave Coste              4678          111.9          1.6               13.17
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03306/joss.03306/10.21105.joss.03306.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03306/joss.03306/10.21105.joss.03306.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @vissarion as editor

Hi @vissarion, apologies for two invitations in short order, but could you edit this submission as well? The connection with optimization seemed to put this in your wheelhouse.

**Comment by whedon** [comment]
@vissarion has been invited to edit this submission.

**Comment by vissarion** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @vissarion

**Comment by vissarion** [comment]
:wave: @sandyjmacdonald, @nicolasfauchereau, @OliverSchmitz, @jrising, @TimHessels, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by jrising** [comment]
@vissarion I could probably do this, but not for a few weeks. Is end-of-June too late?

**Comment by vissarion** [comment]
> @vissarion I could probably do this, but not for a few weeks. Is end-of-June too late?

No, we are still under covid-19 special occasion.

**Comment by sandyjmacdonald** [comment]
@vissarion I'm not sure I'd have the specialist knowledge to review it, I'm afraid!

**Comment by vissarion** [comment]
@whedon add @jrising as reviewer

**Comment by whedon** [comment]
OK, @jrising is now a reviewer

**Comment by vissarion** [comment]
> @vissarion I'm not sure I'd have the specialist knowledge to review it, I'm afraid!

OK, thanks for the reply!

**Comment by vissarion** [comment]
Hi, @joeweaver, @jmp75, @marvinjonathcn, @katmratliff, @simonom, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by marvinjonathcn** [comment]
Hi @vissarion , I would like to be a reviewer for this research. I would have no problems.

**Comment by vissarion** [comment]
@whedon assign @marvinjonathcn as reviewer

**Comment by whedon** [comment]
OK, @marvinjonathcn is now a reviewer

**Comment by vissarion** [comment]
@whedon add @jrising as reviewer

**Comment by whedon** [comment]
OK, @jrising is now a reviewer

**Comment by katmratliff** [comment]
Hi @vissarion I am sorry but I will not be able to complete the review in a timely manner.

**Comment by vissarion** [comment]
@whedon start review

**Comment by joeweaver** [comment]
I'm interested, but not sure I have the time. I'll have a final answer by
the end of the day today (UK time).

**Comment by OliverSchmitz** [comment]
@vissarion sorry, but the topic is not my expertise. Apologies for the late reply

**Comment by simonom** [comment]
Thanks @vissarion<https://github.com/vissarion>, I would like to review.

Kind regards,
Simon O'Meara

National Centre for Atmospheric Science Postdoctoral Research Associate
________________________________

**Comment by joeweaver** [comment]
I will not be able to review this in a timely manner, sorry.
