### ISSUE TITLE
[PRE REVIEW]: SummationByPartsOperators.jl: A Julia library of provably stable discretization techniques with mimetic properties

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3315]
**Submitting author:** @ranocha (<a href="http://orcid.org/0000-0002-3456-2277">Hendrik Ranocha</a>)
**Repository:** <a href="https://github.com/ranocha/SummationByPartsOperators.jl" target ="_blank">https://github.com/ranocha/SummationByPartsOperators.jl</a>
**Version:** v0.5.1
**Editor:** @VivianePons
**Reviewers:** @dawbarton, @kellertuer
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c1bc6f211c4cce38bfdd0d312816bc69/status.svg)](https://joss.theoj.org/papers/c1bc6f211c4cce38bfdd0d312816bc69)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c1bc6f211c4cce38bfdd0d312816bc69"><img src="https://joss.theoj.org/papers/c1bc6f211c4cce38bfdd0d312816bc69/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c1bc6f211c4cce38bfdd0d312816bc69/status.svg)](https://joss.theoj.org/papers/c1bc6f211c4cce38bfdd0d312816bc69)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ranocha. **Currently, there isn't an JOSS editor assigned** to your paper.

@ranocha if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (649.9 files/s, 157509.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           57           1721           1149          15741
Markdown                        14            347              0           1270
YAML                             8             27             24            248
Jupyter Notebook                 5              0            474            238
TOML                             3              4              0             70
JSON                             1              0              0             14
-------------------------------------------------------------------------------
SUM:                            88           2099           1647          17581
-------------------------------------------------------------------------------


Statistical information for the repository '846f4b1b726a2b63f87cc1d4' was
gathered on 2021/05/26.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3315 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4540467 is OK
- 10.4208/cicp.OA-2020-0119 is OK
- 10.5281/zenodo.3908803 is OK
- 10.1007/s10915-021-01463-6 is OK
- 10.1007/s10915-021-01454-7 is OK
- 10.5281/zenodo.3699173 is OK
- 10.1137/19M1290346 is OK
- 10.5281/zenodo.3464243 is OK
- 10.1093/imanum/drz070 is OK
- 10.1007/s42967-019-00057-2 is OK
- 10.5281/zenodo.3375170 is OK
- 10.1007/s10915-018-00902-1 is OK
- 10.5281/zenodo.4054366 is OK
- 10.5281/zenodo.3996439 is OK
- 10.5334/jors.151 is OK
- 10.1137/141000671 is OK
- 10.1109/HPTCDL.2014.10 is OK
- 10.5281/zenodo.1161724 is OK
- 10.1016/j.jcp.2013.12.041 is OK
- 10.1016/j.jcp.2018.06.010 is OK
- 10.1016/j.jcp.2017.01.042 is OK
- 10.21105/joss.02018 is OK
- 10.1109/JPROC.2004.840301 is OK

MISSING DOIs

- 10.1016/j.jcp.2021.110467 may be a valid DOI for title: A purely hyperbolic discontinuous Galerkin approach for self-gravitating gas dynamics

INVALID DOIs

- 0.21105/joss.02520 is INVALID
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03315/joss.03315/10.21105.joss.03315.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03315/joss.03315/10.21105.joss.03315.pdf) :page_facing_up: :point_left:

**Comment by ranocha** [comment]
Potential reviewers are
- ChrisRackauckas (Julia, differential equations)
- dpsanders (Julia, numerics)
- dawbarton (Julia, differential equations)
- ysimillides (Julia, differential equations)
- kellertuer (Julia, mathematics)
- crstnbr (Julia, mathematics)

**Comment by ranocha** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4540467 is OK
- 10.4208/cicp.OA-2020-0119 is OK
- 10.5281/zenodo.3908803 is OK
- 10.1007/s10915-021-01463-6 is OK
- 10.1007/s10915-021-01454-7 is OK
- 10.5281/zenodo.3699173 is OK
- 10.1137/19M1290346 is OK
- 10.5281/zenodo.3464243 is OK
- 10.1093/imanum/drz070 is OK
- 10.1007/s42967-019-00057-2 is OK
- 10.5281/zenodo.3375170 is OK
- 10.1007/s10915-018-00902-1 is OK
- 10.5281/zenodo.4054366 is OK
- 10.1016/j.jcp.2021.110467 is OK
- 10.5281/zenodo.3996439 is OK
- 10.5334/jors.151 is OK
- 10.1137/141000671 is OK
- 10.1109/HPTCDL.2014.10 is OK
- 10.5281/zenodo.1161724 is OK
- 10.21105/joss.02520 is OK
- 10.1016/j.jcp.2013.12.041 is OK
- 10.1016/j.jcp.2018.06.010 is OK
- 10.1016/j.jcp.2017.01.042 is OK
- 10.21105/joss.02018 is OK
- 10.1109/JPROC.2004.840301 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ranocha** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03315/joss.03315/10.21105.joss.03315.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03315/joss.03315/10.21105.joss.03315.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@ranocha – thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by ranocha** [comment]
Hi! Is there anything I can do to help and support the process?

**Comment by danielskatz** [comment]
no, we just need to wait for other papers to be published, and more editors to be brought on, both of which are happening currently

**Comment by danielskatz** [comment]
👋 @VivianePons - Would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @VivianePons as editor

**Comment by whedon** [comment]
@VivianePons has been invited to edit this submission.

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by VivianePons** [comment]
@whedon set @dawbarton as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by VivianePons** [comment]
@whedon assign @dawbarton as reviewer

**Comment by whedon** [comment]
OK, @dawbarton is now a reviewer

**Comment by VivianePons** [comment]
@whedon add @kellertuer as reviewer

**Comment by whedon** [comment]
OK, @kellertuer is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3454.
