### ISSUE TITLE
[PRE REVIEW]: oce: an R package for Oceanographic Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3319]
**Submitting author:** @dankelley (<a href="http://orcid.org/0000-0001-7808-5911">Dan E. Kelley</a>)
**Repository:** <a href="https://github.com/dankelley/oce" target ="_blank">https://github.com/dankelley/oce</a>
**Version:** 1.5-0
**Editor:** @kthyng
**Reviewers:** @gonzalobravoargentina, @diodon
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4e11074685a0c614345560332cfd27e8/status.svg)](https://joss.theoj.org/papers/4e11074685a0c614345560332cfd27e8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4e11074685a0c614345560332cfd27e8"><img src="https://joss.theoj.org/papers/4e11074685a0c614345560332cfd27e8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4e11074685a0c614345560332cfd27e8/status.svg)](https://joss.theoj.org/papers/4e11074685a0c614345560332cfd27e8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dankelley. **Currently, there isn't an JOSS editor assigned** to your paper.

@dankelley if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1175/2008JTECHO615.1 is OK
- 10.1016/S0098-3004(02)00013-4 is OK
- 10.5670/oceanog.2010.21 is OK
- 10.3389/fmars.2021.635922 is OK
- 10.1080/07055900.2012.707610 is OK

MISSING DOIs

- 10.1002/wics.1212 may be a valid DOI for title: The Comprehensive R Archive Network

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.64 s (578.4 files/s, 179758.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           574          30744           7802         126495
R                              232           2544          31194          43835
SQL                              1              0              0          15232
PO File                          4           6250            681          14182
C++                             29            296            873           3398
C                                8            158            501           1732
Markdown                        31            557              0           1677
XML                              4              0              2           1371
Fortran 77                       4              8            198           1248
Rmd                              8            462           1707            454
CSS                              3             99             48            428
JavaScript                       4             64             34            266
YAML                             8             46             14            257
make                            33             34              2            243
TeX                              1             12              0            127
MATLAB                           1             17             41             87
C/C++ Header                     1              8              0             43
Python                           1              6              5             24
SVG                              1              0              1             11
Bourne Shell                     3              3             23              8
-------------------------------------------------------------------------------
SUM:                           951          41308          43126         211118
-------------------------------------------------------------------------------


Statistical information for the repository '99955edda87d311e1384bfbf' was
gathered on 2021/05/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Clark Richards                   5           406             49            0.68
Dan Kelley                     414         29260          24020           79.84
Dan.Kelley@Dal.Ca               38          2380           1117            5.24
Dirk Eddelbuettel                1            39             39            0.12
dan.kelley@dal.ca                2             2             13            0.02
dankelley                       82          5151           4260           14.10

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Clark Richards              352           86.7         12.1                9.09
Dan Kelley                    9            0.0        133.5               11.11
Dan.Kelley@Dal.Ca           736           30.9        142.6               20.11
Dirk Eddelbuettel            39          100.0          0.0                0.00
dankelley                  6332          122.9         55.7               22.30
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03319/joss.03319/10.21105.joss.03319.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03319/joss.03319/10.21105.joss.03319.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@dankelley - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by dankelley** [comment]
Dear editor,

As a response to the first comment in this issue, we are putting below a list of three possible reviewers, with GitHub username followed by full name.  We can supply more names, if needed.  In selecting these names, we have tried to span a range of researchers at different stages of their careers, and with different backgrounds.

Please note that we examined the spreadsheet of those who have agreed to review for JOSS, but found none with both R experience and oceanographic experience.  This is why we widened our search.  With any luck, our suggestions for reviewers might lead to more entries in your list of potential reviewers.

1. erinann Erin LaBrecque

2. SeascapeScience Nick Record

3. gonzalobravoargentina Gonzalo Bravo

**Comment by dankelley** [comment]
Dear editor, a citation for Hornik's paper on CRAN has been added, as suggested by the JOSS bot. This is my first experience with that bot, and so I am writing this note instead of just the next line, to update the submission. I hope that's within protocol.  Dan.

@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

☝️ @dankelley – the commands to Whedon need to be the first line of a message but it's encouraged for authors to interact with the bot too!

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03319/joss.03319/10.21105.joss.03319.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03319/joss.03319/10.21105.joss.03319.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@kthyng - given the other just took, would you want to take this one too?  No is a fine answer :)

**Comment by kthyng** [comment]
Sure, I'll just be a bit slow with all the other papers I'm handling too.

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kthyng** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kthyng

**Comment by kthyng** [comment]
Hi @dankelley and welcome to JOSS! I am happy to see your submission! Sorry for the delay, I am handling a lot of papers right now and had some summer travel too. Let's see if we can get some reviewers. Thanks for the list — I'll start from there (esp since I don't know so many R people).

**Comment by kthyng** [comment]
@erinann and @gonzalobravoargentina — Are you interested in reviewing this submission for JOSS, the Journal of Open Source Software? This is an open review which takes place on github with issues. You can learn more about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. I would hope you could start the review in the next few weeks with the intention of being through the typically iterative process in 4-6 weeks. Thanks for your consideration.

**Comment by gonzalobravoargentina** [comment]
Hi @kthyng,
I'm very honoured with the invitation. 
Although I am intermediate R used, I have used the Oce package rather well and think I can give some humble contributions. However if others reviewers with more programing experience are available I got not problem in leaving my place.  
Thanks

**Comment by kthyng** [comment]
Hi @gonzalobravoargentina — sounds like you will be a good reviewer then. We look forward to your feedback on the package!

**Comment by kthyng** [comment]
@whedon assign @gonzalobravoargentina as reviewer

**Comment by whedon** [comment]
OK, @gonzalobravoargentina is now a reviewer

**Comment by kthyng** [comment]
Hi @SeascapeScience! Are you interested in reviewing this submission for JOSS, the Journal of Open Source Software? This is an open review which takes place on github with issues. You can learn more about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. I would hope you could start the review in the next few weeks with the intention of being through the typically iterative process in 4-6 weeks. Thanks for your consideration.

**Comment by gonzalobravoargentina** [comment]
Hi @kthyng 
Perhaps @diodon could be a good reviewer.
Cheers

**Comment by kthyng** [comment]
Thanks for the suggestion @gonzalobravoargentina.

@diodon — Are you interested in reviewing this submission for JOSS, the Journal of Open Source Software? This is an open review which takes place on github with issues. You can learn more about the process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. I would hope you could start the review in the next few weeks with the intention of being through the typically iterative process in 4-6 weeks. Thanks for your consideration.

**Comment by diodon** [comment]
Hi @kthyng, thank you for the invitation. I'm quite busy the next 2-3 weeks but after I can review the paper. I'm quite familiar with the oce package so I will be glad to look at the submission. If the proposed time frame is good for you, then I can do it.
Cheers, EKS

**Comment by kthyng** [comment]
Ok sounds great @diodon! I'll add you and start the review and just go ahead with it as soon as you can. Thank you!

**Comment by kthyng** [comment]
@whedon add @diodon as reviewer

**Comment by whedon** [comment]
OK, @diodon is now a reviewer

**Comment by kthyng** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3594.

**Comment by SeascapeScience** [comment]
Hi Kristen,

For some reason this didn’t come through in my github notifications, and I’m just seeing it now in my email.

I’m guessing I’m too late, but please consider me as a potential reviewer in the future.

Cheers,
Nick

**Comment by kthyng** [comment]
Thanks for the response @SeascapeScience! If you're interested, you could sign up to be a reviewer here: https://joss.theoj.org/reviewer-signup.html
