### ISSUE TITLE
[PRE REVIEW]: AdaptiveResonance.jl: A Julia implementation of Adaptive Resonance Theory (ART) algorithms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3320]
**Submitting author:** @AP6YC (<a href="http://orcid.org/0000-0003-2442-8901">Sasha Petrenko</a>)
**Repository:** <a href="https://github.com/AP6YC/AdaptiveResonance.jl" target ="_blank">https://github.com/AP6YC/AdaptiveResonance.jl</a>
**Version:** 0.2.2
**Editor:** @adi3
**Reviewers:** @aaronpeikert, @hayesall
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4db5d132c25546b235f167cbbfdd4af5/status.svg)](https://joss.theoj.org/papers/4db5d132c25546b235f167cbbfdd4af5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4db5d132c25546b235f167cbbfdd4af5"><img src="https://joss.theoj.org/papers/4db5d132c25546b235f167cbbfdd4af5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4db5d132c25546b235f167cbbfdd4af5/status.svg)](https://joss.theoj.org/papers/4db5d132c25546b235f167cbbfdd4af5)
```

**Author instructions**

Thanks for submitting your paper to JOSS @AP6YC. **Currently, there isn't an JOSS editor assigned** to your paper.

@AP6YC if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (1378.6 files/s, 129587.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           24            432            462           2048
Markdown                         7             99              0            259
YAML                             6             23            132            164
TeX                              1              7              0             97
TOML                             2              4              0             33
-------------------------------------------------------------------------------
SUM:                            40            565            594           2601
-------------------------------------------------------------------------------


Statistical information for the repository '6e9e5813a4207fd7ea8065a1' was
gathered on 2021/05/29.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201629272 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.1016/j.neunet.2012.09.017 is OK
- 10.1037/0033-295X.87.1.1 is OK
- 10.1016/j.neunet.2019.09.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3320 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by arfon** [comment]
@AP6YC - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

While you're waiting, please fix up your paper (the affiliations aren't formatted properly). See the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) for how to structure your paper metadata. You can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by AP6YC** [comment]
@whedon generate pdf

**Comment by AP6YC** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201629272 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.1016/j.neunet.2012.09.017 is OK
- 10.1037/0033-295X.87.1.1 is OK
- 10.1016/j.neunet.2019.09.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03320/joss.03320/10.21105.joss.03320.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03320/joss.03320/10.21105.joss.03320.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @adi3 as editor

:wave: @adi – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@adi3 has been invited to edit this submission.

**Comment by adi3** [comment]
@whedon assign @adi3 as editor

**Comment by whedon** [comment]
OK, the editor is @adi3

**Comment by adi3** [comment]
@AP6YC - Looks like I got two papers from you! Same instructions as before :)

To get things going, could you please suggest 5-6 reviewers from [this](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) list that you consider appropriate to vet this paper? While selecting, you should confirm that the domain expertise of the reviewer matches the subject matter of your paper and software.

Thank you!

**Comment by adi3** [comment]
@AP6YC - Checkin back on this. We are waiting on your response to proceed with this review. Thanks!

**Comment by adi3** [comment]
👋🏼 @AP6YC, do you have any updates for us?

**Comment by AP6YC** [comment]
@adi3 Thank you for pinging me! I do sincerely apologize for the great delay.

After going through the list and selecting based upon Julia and domain knowledge, I have selected the following 6 reviewers (listed by username):

- ChrisRackauckas
- malmaud
- degleris1
- rMassimiliano
- aaronpeikert
- szkafander

**Comment by adi3** [comment]
@AP6YC no problem, thank you for the list!

@ChrisRackauckas @malmaud @degleris1 @rMassimiliano @aaronpeikert @szkafander - Would any of you be interested in reviewing this paper? We'd greatly appreciate your help!

**Comment by ChrisRackauckas** [comment]
Too busy right now.

**Comment by adi3** [comment]
@szkafander - are you ok reviewing this one?

**Comment by szkafander** [comment]
@adi3 I will have to pass on this, sorry.

**Comment by adi3** [comment]
@degleris1 @aaronpeikert - Checking in again whether either of you would be willing to review this paper? We would really appreciate your help!

**Comment by adi3** [comment]
@AP6YC - Can you please search for a few more reviewers in the [reviewers list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/) so we could move this along? Thanks!

**Comment by degleris1** [comment]
@adi3 Apologies, I am unavailable at the moment.

**Comment by aaronpeikert** [comment]
I am currently on vacation. But could review this paper in the week from the 16th August.

A note, though, I am unfamiliar with the review process of JOSS and I am an early career researcher so my experience with reviewing is meagre.
Anyhow, I am quite willing to invest some time to learn how it’s done.

**Comment by adi3** [comment]
@aaronpeikert Thank you for the offer! I don't have an issue with waiting till you're back from your vacation. Our review process is pretty well documented and you will be provided with a specific checklist + instructions on how to conduct the review, but in any case, I will be around to guide you through it or have any questions :)

I'll go ahead and assign you as a reviewer on this paper. The actual review will kick off only once we find a second reviewer, upon which you will receive further instructions on how to proceed.

**Comment by adi3** [comment]
@whedon assign @aaronpeikert as reviewer

**Comment by whedon** [comment]
OK, @aaronpeikert is now a reviewer

**Comment by adi3** [comment]
@juliohm @mskwark @brunaw @hayesall @ahwillia - Are you available to review this paper? We'd greatly appreciate your help!

**Comment by juliohm** [comment]
I would love to review the package but I am incredibly busy in the next months. Thank you for pinging.

**Comment by ahwillia** [comment]
I am also unavailable unfortunately.

**Comment by hayesall** [comment]
@adi3 I can review.

**Comment by adi3** [comment]
@hayesall thank you for stepping up!

**Comment by adi3** [comment]
@whedon add @hayesall as reviewer

**Comment by whedon** [comment]
OK, @hayesall is now a reviewer

**Comment by adi3** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3671.
