### ISSUE TITLE
[PRE REVIEW]: ClusterValidityIndices.jl: Batch and Incremental Metrics for Unsupervised Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3321]
**Submitting author:** @AP6YC (<a href="http://orcid.org/0000-0003-2442-8901">Sasha Petrenko</a>)
**Repository:** <a href="https://github.com/AP6YC/ClusterValidityIndices.jl" target ="_blank">https://github.com/AP6YC/ClusterValidityIndices.jl</a>
**Version:** 0.1.5
**Editor:** @adi3
**Reviewers:** @rMassimiliano, @malmaud
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/49689a7f5baf94f5d403a18a73b2d99e/status.svg)](https://joss.theoj.org/papers/49689a7f5baf94f5d403a18a73b2d99e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/49689a7f5baf94f5d403a18a73b2d99e"><img src="https://joss.theoj.org/papers/49689a7f5baf94f5d403a18a73b2d99e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/49689a7f5baf94f5d403a18a73b2d99e/status.svg)](https://joss.theoj.org/papers/49689a7f5baf94f5d403a18a73b2d99e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @AP6YC. **Currently, there isn't an JOSS editor assigned** to your paper.

@AP6YC if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (1301.7 files/s, 130488.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           21            321            352           1977
Markdown                         7            199              0            551
YAML                             6              9             46            167
TeX                              1              4              0             54
TOML                             2              4              0             25
-------------------------------------------------------------------------------
SUM:                            37            537            398           2774
-------------------------------------------------------------------------------


Statistical information for the repository 'ebc7bf8e69ef49de9d2741fd' was
gathered on 2021/05/29.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ACCESS.2020.2969849 is OK
- 10.1016/j.neunet.2012.09.017 is OK
- 10.1037/0033-295X.87.1.1 is OK
- 10.1016/j.neunet.2019.09.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3321 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by arfon** [comment]
@AP6YC - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

While you're waiting, please fix up your paper (the affiliations aren't formatted properly). See the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) for how to structure your paper metadata. You can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by AP6YC** [comment]
@arfon You've got it! I totally understand the backlog. I just appreciate any attention that you are able to give and when you are able to give it, especially in these strange and challenging times.

**Comment by AP6YC** [comment]
I have made some changes to the affiliations field and will attempt to rerun here:
@whedon generate pdf
@whedon check references

**Comment by AP6YC** [comment]
@whedon generate pdf

**Comment by AP6YC** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ACCESS.2020.2969849 is OK
- 10.1016/j.neunet.2012.09.017 is OK
- 10.1037/0033-295X.87.1.1 is OK
- 10.1016/j.neunet.2019.09.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03321/joss.03321/10.21105.joss.03321.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03321/joss.03321/10.21105.joss.03321.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @adi3 as editor

:wave: @adi3 - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@adi3 has been invited to edit this submission.

**Comment by adi3** [comment]
@whedon assign @adi3 as editor

**Comment by whedon** [comment]
OK, the editor is @adi3

**Comment by adi3** [comment]
Hi @AP6YC, I will be the editor for this paper.

To get things going, could you please suggest 5-6 reviewers from [this](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) list that you consider appropriate to vet this paper? While selecting, you should confirm that the domain expertise of the reviewer matches the subject matter of your paper and software.

Thank you!

**Comment by adi3** [comment]
@AP6YC - Checking back on this. We are waiting on your response to proceed with this review. Thanks!

**Comment by adi3** [comment]
👋🏼 @AP6YC, do you have any updates for us?

**Comment by AP6YC** [comment]
@adi3 As in the other thread, thank you for pinging me! I do sincerely apologize for the great delay.

Because this project requires similar domain knowledge, I am listing the same 6 reviewers as in AdaptiveResonance.jl (listed by username):

- ChrisRackauckas
- malmaud
- degleris1
- rMassimiliano
- aaronpeikert
- szkafander

If you wish, I am more than happy to select a separate group of reviewers. Thank you again for your patience.

**Comment by adi3** [comment]
@ChrisRackauckas @malmaud @degleris1 @rMassimiliano @aaronpeikert @szkafander - This is a separate paper from the other request. Both papers cover similar topics, so you can choose which one you'd like to review (if not both!). Do let us know if you can become a reviewer for this one :)

**Comment by ChrisRackauckas** [comment]
Too busy right now.

**Comment by rMassimiliano** [comment]
Hi @adi3 I am happy to review this.

**Comment by adi3** [comment]
@rMassimiliano wonderful, thank you!

**Comment by adi3** [comment]
@whedon assign @rMassimiliano as reviewer

**Comment by whedon** [comment]
OK, @rMassimiliano is now a reviewer

**Comment by malmaud** [comment]
@adi3 I can review this.

**Comment by szkafander** [comment]
@adi3 I am happy to review this.

**Comment by adi3** [comment]
@whedon add @malmaud as reviewer

**Comment by whedon** [comment]
OK, @malmaud is now a reviewer

**Comment by adi3** [comment]
@szkafander - thank you! We have the reviewers for this paper, but can I assign you the [sister paper](https://github.com/openjournals/joss-reviews/issues/3320#issuecomment-885493943) for this project? I'll message you on there.

**Comment by adi3** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3527.
