### ISSUE TITLE
[PRE REVIEW]: ogs6py and VTUinterface: streamlining OpenGeoSys workflows in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3327]
**Submitting author:** @joergbuchwald (<a href="http://orcid.org/0000-0001-5174-3603">Jörg Buchwald</a>)
**Repository:** <a href="https://github.com/joergbuchwald/joss_ogs6py_VTUinterface" target ="_blank">https://github.com/joergbuchwald/joss_ogs6py_VTUinterface</a>
**Version:** v0.31
**Editor:** @leouieda
**Reviewers:** @cpgr, @TobbeTripitaka, @akaszynski 
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6ddcac13634c6373e6e808952fdf4abc/status.svg)](https://joss.theoj.org/papers/6ddcac13634c6373e6e808952fdf4abc)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6ddcac13634c6373e6e808952fdf4abc"><img src="https://joss.theoj.org/papers/6ddcac13634c6373e6e808952fdf4abc/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6ddcac13634c6373e6e808952fdf4abc/status.svg)](https://joss.theoj.org/papers/6ddcac13634c6373e6e808952fdf4abc)
```

**Author instructions**

Thanks for submitting your paper to JOSS @joergbuchwald. **Currently, there isn't an JOSS editor assigned** to your paper.

@joergbuchwald if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (667.1 files/s, 69383.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          29            224            605           2555
XML                             14              4             14           1633
Markdown                         6            314              0            652
TeX                              1              3              0            182
Jupyter Notebook                 1              0            945            118
YAML                             3             10              6             68
reStructuredText                17             60            116             28
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            73            627           1694           5271
-------------------------------------------------------------------------------


Statistical information for the repository 'a5a52fd3a534b3e402c0573c' was
gathered on 2021/06/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dmitri Naumov                    1           272              0            2.33
Joerg Buchwald                  10           262            142            3.46
Jörg Buchwald                   12          1517            105           13.91
Thomas Fischer                   4           151             18            1.45
Thomas Nagel                     1            15              0            0.13
joerg                           24           766           1154           16.46
joergbuchwald                   91          4546           2716           62.26

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dmitri Naumov               243           89.3          2.8                5.76
Jörg Buchwald                94            6.2         25.4                3.19
Thomas Fischer              137           90.7         18.1               10.95
Thomas Nagel                 15          100.0          0.2                6.67
joerg                       178           23.2         18.9                0.00
joergbuchwald              2717           59.8          4.0                7.25
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03327/joss.03327/10.21105.joss.03327.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03327/joss.03327/10.21105.joss.03327.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ijrmms.2021.104683 is OK
- 10.1016/j.ijrmms.2020.104481 is OK
- 10.1016/j.ijrmms.2021.104662 is OK
- 10.1007/s11242-019-01310-1 is OK
- 10.5281/zenodo.4745399 is OK

MISSING DOIs

- 10.1016/b978-012387582-2/50038-1 may be a valid DOI for title: Paraview: An end-user tool for large data visualization
- 10.1016/j.ijheatmasstransfer.2021.121127 may be a valid DOI for title: Improved predictions of thermal fluid pressurization in hydro-thermal models based on consistent incorporation of thermo-mechanical effects in anisotropic porous media
- 10.1109/38.865875 may be a valid DOI for title: Visualizing with VTK: a tutorial
- 10.21105/joss.01450 may be a valid DOI for title: PyVista: 3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK)
- 10.1109/mcse.2011.35 may be a valid DOI for title: Mayavi: 3D visualization of scientific data
- 10.1002/nme.2579 may be a valid DOI for title: Gmsh: A 3-D finite element mesh generator with built-in pre-and post-processing facilities

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@joergbuchwald can you check those missing/invalid DOI's :point_up:, you can call `@whedon generate pdf` here to update the paper

**Comment by Kevin-Mattheus-Moerman** [comment]
@jedbrown this looks like your cup of tea :tea:, since it looks like you have a lot on your plate I'll add the `waitlisted` label for now until you are available.

**Comment by Kevin-Mattheus-Moerman** [comment]
@joergbuchwald I have just added the waitlisted label. This is because the JOSS editors in this domain are currently all assigned to several other submissions. We will resume review of this work once one of them becomes available.

**Comment by joergbuchwald** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03327/joss.03327/10.21105.joss.03327.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03327/joss.03327/10.21105.joss.03327.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @leouieda - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @leouieda as editor

**Comment by whedon** [comment]
@leouieda has been invited to edit this submission.

**Comment by leouieda** [comment]
Hi @danielskatz I can take this on

**Comment by leouieda** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by leouieda** [comment]
@joergbuchwald thank you for your patience so far! I'll do a first pass on the paper and then start looking for reviewers.

**Comment by leouieda** [comment]
👋🏽 hi @joergbuchwald this submission is a little bit unusual since it is reporting on two separate software packages. I've been reading through your paper and project documentation to get a better idea for both of them. Could you please briefly explain your reasoning for including both of them in a single paper? To be clear, this is unusual but not prohibited so I'm just trying to better understand your paper.

**Comment by joergbuchwald** [comment]
Hi @leouieda thank you for the question. Both packages evolved together as pre- and post-processing utils for OGS. However, the application field of VTUinterface is somewhat broader, as also other simulation software are using VTU and PVD as output formats, so it made sense for us to have separate packages. For this paper, the original idea was to sell the pre- and postprocessing of OGS in python as one workflow to demonstrate what can be done with OGS in one single jupyter notebook. I also think, the advantages of using ogs6py for people who are used to using paraview for data analysis might not be obvious at first sight. It really comes with simple access to VTU and PVD data.
Which is why we wanted to present an entire workflow as demonstrated in this (jupyter notbook)[https://github.com/joergbuchwald/ogs6py/blob/master/paper/paper_ogs6py_vtuio.ipynb]. However, this was too long for the JOSS word limit, so we needed to shorten the paper and therefore the original idea got possibly also a bit lost.

**Comment by nagelt** [comment]
@leouieda Leonardo, any chance we can move this forward? Can we help in any way?

**Comment by TobbeTripitaka** [comment]
Sure. I'm also happy to review this.

**Comment by leouieda** [comment]
@cpgr @TobbeTripitaka @akaszynski thank you for agreeing to review! I will add you as reviewers and start the review process. This discussion will move to another issue where instructions will be posted.

**Comment by leouieda** [comment]
@whedon assign @cpgr as reviewer

**Comment by whedon** [comment]
OK, @cpgr is now a reviewer

**Comment by leouieda** [comment]
@whedon add @TobbeTripitaka as reviewer

**Comment by whedon** [comment]
OK, @TobbeTripitaka is now a reviewer

**Comment by leouieda** [comment]
@whedon add @akaszynski  as reviewer

**Comment by whedon** [comment]
OK, @akaszynski  is now a reviewer

**Comment by leouieda** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3673.
