### ISSUE TITLE
[PRE REVIEW]: Biosensor Framework: A C# Library for Affective Computing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3328]
**Submitting author:** @wsarce (<a href="http://orcid.org/0000-0003-0819-0710">Walker Arce</a>)
**Repository:** <a href="https://github.com/Munroe-Meyer-Institute-VR-Laboratory/Biosensor-Framework" target ="_blank">https://github.com/Munroe-Meyer-Institute-VR-Laboratory/Biosensor-Framework</a>
**Version:** v1.0.0
**Editor:** @osorensen
**Reviewers:** @professoralkmin, @AustinTSchaffer
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ce2098ed62af72faa9a4817dabdc34e3/status.svg)](https://joss.theoj.org/papers/ce2098ed62af72faa9a4817dabdc34e3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ce2098ed62af72faa9a4817dabdc34e3"><img src="https://joss.theoj.org/papers/ce2098ed62af72faa9a4817dabdc34e3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ce2098ed62af72faa9a4817dabdc34e3/status.svg)](https://joss.theoj.org/papers/ce2098ed62af72faa9a4817dabdc34e3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @wsarce. **Currently, there isn't an JOSS editor assigned** to your paper.

@wsarce if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (510.7 files/s, 136142.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C#                              28            489           1410           3326
Markdown                         5           1265              0           2337
XML                              4             21              0           1569
MSBuild script                   3              7              0            349
TeX                              1              0              0            156
-------------------------------------------------------------------------------
SUM:                            41           1782           1410           7737
-------------------------------------------------------------------------------


Statistical information for the repository '7ef76bbe73f27ecefdc9365f' was
gathered on 2021/06/01.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03328/joss.03328/10.21105.joss.03328.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03328/joss.03328/10.21105.joss.03328.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1145/3242969.3242985 may be a valid DOI for title: Introducing wesad, a multimodal dataset for wearable stress and affect detection
- 10.1109/tits.2005.848368 may be a valid DOI for title: Detecting stress during real-world driving tasks using physiological sensors
- 10.1007/978-3-319-91262-2_16 may be a valid DOI for title: Towards the development of sensor platform for processing physiological data from wearable sensors
- 10.1145/3027063.3053140 may be a valid DOI for title: Indexing cognitive load using blood volume pulse features
- 10.1016/j.trf.2019.09.015 may be a valid DOI for title: HeartPy: A novel heart rate algorithm for the analysis of noisy signals
- 10.24251/hicss.2020.456 may be a valid DOI for title: Objective measurement of physician stress in the emergency department using a wearable sensor
- 10.37896/jxu15.3/018 may be a valid DOI for title: Development and evaluation of an ambulatory stress monitor based on wearable sensors
- 10.1109/10.979357 may be a valid DOI for title: An advanced detrending method with application to HRV analysis
- 10.3390/s121217620 may be a valid DOI for title: A wireless accelerometer-based body posture stability detection system and its application for meditation practitioners
- 10.1080/19315864.2019.1595233 may be a valid DOI for title: Identification of post-traumatic stress disorder in individuals with autism spectrum disorder and intellectual disability: A systematic review
- 10.1002/aur.1433 may be a valid DOI for title: The relationship between stress and social functioning in adults with autism spectrum disorder and without intellectual disability
- 10.1145/3136755.3143025 may be a valid DOI for title: Using mobile virtual reality to empower people with hidden disabilities to overcome their barriers
- 10.1089/cyber.2019.0093 may be a valid DOI for title: Virtual reality air travel training with children on the autism spectrum: A preliminary report
- 10.1186/s12984-015-0010-z may be a valid DOI for title: Natural interfaces and virtual environments for the acquisition of street crossing and path following skills in adults with Autism Spectrum Disorders: a feasibility study

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@wsarce Thanks for this submission. Can you work on adding those potentially missing DOI's (check if the suggested ones are correct) ?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arokem this looks like something you could handle, and you were suggested as editor. I see however you are handling several other submission. I'll therefore assign the `waitlisted` label here for now until you or another editor in this domain becomes available.

**Comment by arokem** [comment]
Sorry - I am slammed with other things right now, so would rather not take this on right now.

**Comment by kthyng** [comment]
@meg-simula could you edit this submission?

**Comment by kthyng** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by meg-simula** [comment]
Have to decline this one I'm afraid, not in my area of expertise.

**Comment by kthyng** [comment]
@meg-simula fair enough, thanks for letting me know!

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
@wsarce, I am now the editor of this submission. If you have any suggestions for reviewers, please metion them in this thread (without the @).

**Comment by osorensen** [comment]
@anki-xyz, @jackbrookes, @shanamatthews, @professoralkmin: would any of you be interested in reviewing this article for JOSS?

**Comment by professoralkmin** [comment]
@osorensen I'm interested (and it is always an honor) to review an article for JOSS. However, I can only start this review next week. Is there a problem?

**Comment by osorensen** [comment]
Thanks @professoralkmin, starting next week is perfectly fine.

**Comment by osorensen** [comment]
@whedon add @professoralkmin as reviewer

**Comment by whedon** [comment]
OK, @professoralkmin is now a reviewer

**Comment by professoralkmin** [comment]
@osorensen Thanks! Count on me to this review and others! :)

**Comment by osorensen** [comment]
@professoralkmin, perfect! We're waiting for another reviewer before starting the review process.

**Comment by osorensen** [comment]
@AustinTSchaffer, @RcSepp; would any of you be willing to review this manuscript for the Journal of Open Source Software?

**Comment by anki-xyz** [comment]
I would love to, but beyond my area of expertise.

**Comment by osorensen** [comment]
@anki-xyz, that is fine. Thanks for responding :-)

**Comment by AustinTSchaffer** [comment]
@osorensen sure! I can help take a look. I'm pretty familiar with C#, but I'm new to this whole thing. What can I do to assist with reviewing this?

**Comment by osorensen** [comment]
@AustinTSchaffer , thanks! We'll start a review issue, and there you will hopefully be guided through the process.

**Comment by osorensen** [comment]
@whedon add @AustinTSchaffer as reviewer

**Comment by whedon** [comment]
OK, @AustinTSchaffer is now a reviewer

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3455.
