### ISSUE TITLE
[PRE REVIEW]: pyAudioProcessing: Audio Processing, Feature Extraction and building Machine Learning Models from Audio Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3334]
**Submitting author:** @jsingh811 (<a href="http://orcid.org/0000-0002-5442-3004">Jyotika Singh</a>)
**Repository:** <a href="https://github.com/jsingh811/pyAudioProcessing" target ="_blank">https://github.com/jsingh811/pyAudioProcessing</a>
**Version:** v1.1.8
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f69b5634ff1e5b1458d9739b64e070e2/status.svg)](https://joss.theoj.org/papers/f69b5634ff1e5b1458d9739b64e070e2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f69b5634ff1e5b1458d9739b64e070e2"><img src="https://joss.theoj.org/papers/f69b5634ff1e5b1458d9739b64e070e2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f69b5634ff1e5b1458d9739b64e070e2/status.svg)](https://joss.theoj.org/papers/f69b5634ff1e5b1458d9739b64e070e2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jsingh811. **Currently, there isn't an JOSS editor assigned** to your paper.

@jsingh811 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (323.2 files/s, 47023.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            176            349            926
Markdown                         6            224              0            850
YAML                             2              7              4             44
TeX                              1              3              0             36
-------------------------------------------------------------------------------
SUM:                            18            410            353           1856
-------------------------------------------------------------------------------


Statistical information for the repository '4d093a96625b7d2b2d816fdb' was
gathered on 2021/06/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christian Clauss                 1             1              1            0.09
Jyotika Singh                   36          1807            356           99.91

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Christian Clauss              1          100.0          1.2                0.00
Jyotika Singh              1450           80.2          3.7               10.69
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ICASSP.2013.6639061 is OK
- 10.1007/978-81-322-3592-7_9 is OK
- 10.1109/ICGCCEE.2014.6921394 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3334 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by jsingh811** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3334 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by jsingh811** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03334/joss.03334/10.21105.joss.03334.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03334/joss.03334/10.21105.joss.03334.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jsingh811 thanks for this submission. I've flagged this submission for scope review by our editorial board. This is common for submissions [around 1000 lines of code](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). 

In the mean time, would you be able to add a bit more detail in the statement of need section in relation to other existing/related software packages? It would be good to mention and cite a few of key references, including to other software addressing related needs. If you briefly summarize their use and functionality it will be more clear what your submission offers on top of those or how it differs from them.

**Comment by Kevin-Mattheus-Moerman** [comment]
@faroit it would be great if you could weigh in for the scope review on this submission.

**Comment by jsingh811** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03334/joss.03334/10.21105.joss.03334.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03334/joss.03334/10.21105.joss.03334.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @jsingh811. The editorial board is finding this submission to be borderline. Part of what is holding it back from getting over the bar of [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) is that the general packaging for the software isn't all that great. I think if you could improve the documentation, including clear tutorials/examples, and especially if you could beef up the functionality of the package, then it would cross the bar to be in scope. I would like to essentially reject now but encourage resubmission after you address these comments with improvements in the software. If you choose to do this, please link to this issue at the time you resubmit so everyone can remember what the situation was. Feel free to ask questions if you have them, but for now I will proceed with the process I've laid out.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
