### ISSUE TITLE
[PRE REVIEW]: MATRIX: Multi-phAse Transits Recovery from Injected eXoplanets.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3335]
**Submitting author:** @martindevora (<a href="http://orcid.org/0000-0003-2007-6144">Martín Dévora Pajares</a>)
**Repository:** <a href="https://github.com/PlanetHunters/tkmatrix" target ="_blank">https://github.com/PlanetHunters/tkmatrix</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/eb38a570b10e668815cb7ec4364941e2/status.svg)](https://joss.theoj.org/papers/eb38a570b10e668815cb7ec4364941e2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/eb38a570b10e668815cb7ec4364941e2"><img src="https://joss.theoj.org/papers/eb38a570b10e668815cb7ec4364941e2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/eb38a570b10e668815cb7ec4364941e2/status.svg)](https://joss.theoj.org/papers/eb38a570b10e668815cb7ec4364941e2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @martindevora. **Currently, there isn't an JOSS editor assigned** to your paper.

@martindevora if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (482.0 files/s, 54529.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5             48             37            812
TeX                              1             21              0            264
Markdown                         2             45              0            120
Jupyter Notebook                 2              0            214            103
YAML                             4              1             36             74
Bourne Shell                     1              1              0             19
INI                              1              1              0             14
-------------------------------------------------------------------------------
SUM:                            16            117            287           1406
-------------------------------------------------------------------------------


Statistical information for the repository 'a265e782cb35e75b63f70a16' was
gathered on 2021/06/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Fran Pozuelos Romero             3             7             12            0.58
LuisCerdenoMota                  7            81             19            3.05
martin.dvpj                     54          2007           1151           96.37

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Fran Pozuelos Romero          2           28.6          2.5                0.00
LuisCerdenoMota              46           56.8          2.4               10.87
martin.dvpj                 849           42.3          0.9                3.65
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3335 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201834672 is OK
- 10.3847/1538-3881/ab3984 is OK
- 10.1117/1.JATIS.1.1.014003 is OK
- 10.1126/science.1185402 is OK
- 10.1051/0004-6361/201834672 is OK
- 10.1051/0004-6361/201628579 is OK
- 10.1051/0004-6361/202038047 is OK
- 10.1051/0004-6361/202038616 is OK
- 10.1093/mnras/staa138 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see what is wrong with this paper? :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@martindevora you can work on fixing the above paper error and you can call `@whedon generate pdf` here to update the paper. 

Note I have added the `query-scope` label to this submission. This is very [common for submission of this size](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). The editorial board will review if this work is in scope which should take about a week to complete.

**Comment by martindevora** [comment]
hello @Kevin-Mattheus-Moerman , if the query-scope is related to the lines of code, I separated a base code from this project because I wanted to reuse it in a different repository, which I intend to publish too. The project name is lcbuilder under https://github.com/PlanetHunters/lcbuilder . In terms of scholarly effort I think that we would comply with the requirements, but I will listen what you have to say as it is the first time I'm publishing an article as first author.

I tried to compile the paper a few days ago and it worked, I don't know what might be happening. I will review it.

**Comment by martindevora** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03335/joss.03335/10.21105.joss.03335.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03335/joss.03335/10.21105.joss.03335.pdf) :page_facing_up: :point_left:

**Comment by martindevora** [comment]
it seemed that an empty orcid field was causing issues with the article generation, now it seems to be wrking

**Comment by kthyng** [comment]
Here is cloc for the 2nd repo mentioned:
```
(myenv) kthyng@adams ~ % cloc ~/Downloads/lcbuilder-main.zip
      30 text files.
      30 unique files.                              
      10 files ignored.

github.com/AlDanial/cloc v 1.90  T=0.10 s (267.0 files/s, 59115.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSV                              1              0              0           4555
Python                          22             95            119            951
Bourne Shell                     1              1              0             19
INI                              1              1              0             13
Markdown                         1              0              0              2
-------------------------------------------------------------------------------
SUM:                            26             97            119           5540
-------------------------------------------------------------------------------
```

**Comment by kthyng** [comment]
@martindevora Both of these repositories individually are pretty borderline and may not pass the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) bar. However, combined they are probably fine. Would you want to combine these two packages together for the review?

**Comment by martindevora** [comment]
Hi @kthyng What do you mean by combining the packages?

**Comment by kthyng** [comment]
At times in the past, we have considered two repositories together as a single JOSS submission, if they are complementary. This has made sense when the individual repositories are too small individually but do contribute to greater functionality together. What do you think?

**Comment by martindevora** [comment]
@whedon generate pdf

**Comment by martindevora** [comment]
@kthyng please let me know if it is clear enough now or you feel like some additional statements are needed. Now we are mentioning the package twice in the paper as a by-product of the same work (in the Summary and in the first sections). I'm sorry for the misunderstanding.

**Comment by danielskatz** [comment]
@martindevora - I'm sorry to say that the discussion of the editors has led to a decision that this is not in scope for JOSS - comments include the size of the codebase as seeming too small, the code seeming to brittle and not reusuable, the statement of need not demonstrating a real use case (it emphasizes injection and recovery, but it seems more to be a transit search pipeline), and the packaging, documentation, and testing needing work. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by martindevora** [comment]
@danielskatz I would like you to provide precise hints to better understand your statements. We took some effort to adapt our project to comply with the JOSS requirements, though it seems that we didn't do well. It is fair to me that you reject the paper, but the way you have provided the preliminary feedback which led to reject the paper is not giving any useful information that could help us to adhere better to the JOSS standards for future possible submissions. I mean, if I took a look at the JOSS requirements I'd say that we were fairly close to the paper to be accepted for review, but it seems that we missed something or some things that we did not understand well and I'd like to improve our understanding of the situation.

With all the respect, thanking your effort and sorry for the inconveniences.
Kind regards,
Martín.

**Comment by danielskatz** [comment]
@martindevora - thanks for your kindly-written concern. These decisions are never easy to explain, unfortunately, as they come from the editorial board, made of human beings who each have their own opinions and styles.  The comment I provided summarizes individual comments from editors. I'll ask that if any of our astronomy-focused members of the editorial board (@arfon @dfm @xuanxu) want to provide any more information and guidance, they could do so here.
