### ISSUE TITLE
[PRE REVIEW]: Osmenrich: An R package to enrich geocoded data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3338]
**Submitting author:** @leonardovida (<a href="http://orcid.org/0000-0002-0461-016X">Leonardo Vida</a>)
**Repository:** <a href="https://github.com/sodascience/osmenrich" target ="_blank">https://github.com/sodascience/osmenrich</a>
**Version:** v1.2.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8a437dbfbc3c638270eef3c7c0955df7/status.svg)](https://joss.theoj.org/papers/8a437dbfbc3c638270eef3c7c0955df7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8a437dbfbc3c638270eef3c7c0955df7"><img src="https://joss.theoj.org/papers/8a437dbfbc3c638270eef3c7c0955df7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8a437dbfbc3c638270eef3c7c0955df7/status.svg)](https://joss.theoj.org/papers/8a437dbfbc3c638270eef3c7c0955df7)
```

**Author instructions**

Thanks for submitting your paper to JOSS @leonardovida. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@leonardovida if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "--446" (NAME) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:author=>["Edzer Pebesma"], :title=>["{Simple Features for R: Standardized Support for Spatial Vector Data}"], :year=>"2018", :journal=>["{The R Journal}"], :doi=>["10.32614/RJ-2018-009"], :url=>["https://doi.org/10.32614/RJ-2018-009"], :pages=>"439"}]

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (1039.3 files/s, 128621.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               11             74            363            721
Markdown                         4             99              0            362
Rmd                              4            240            476            287
YAML                             3             23              6            181
Ruby                             1             28             12            106
TeX                              1              9              0             69
JSON                             1              0              0             38
-------------------------------------------------------------------------------
SUM:                            25            473            857           1764
-------------------------------------------------------------------------------


Statistical information for the repository 'adb7cc3d25bbb59c7a6a1d24' was
gathered on 2021/06/08.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03338/joss.03338/10.21105.joss.03338.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03338/joss.03338/10.21105.joss.03338.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @leonardovida and thanks for your submission! It is a bit on the small side, so I have tagged it for the editorial board to check it for being in scope for the journal. This process will take 1-2 weeks. Thanks.

**Comment by leonardovida** [comment]
Hi @kthyng, thank you for the answer and for the update!

**Comment by danielskatz** [comment]
@leonardovida - While the scope discussion progresses, you could work on error(s) in your .bib file that whedon found. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by leonardovida** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00305 is OK
- 10.32614/RJ-2018-009 is OK
- 10.21105/joss.01686 is OK
- 10.18637/jss.v059.i10 is OK

MISSING DOIs

- 10.1016/j.cageo.2004.03.012 may be a valid DOI for title: Multivariable geostatistics in S: the gstat package

INVALID DOIs

- None
```

**Comment by leonardovida** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00305 is OK
- 10.32614/RJ-2018-009 is OK
- 10.21105/joss.01686 is OK
- 10.18637/jss.v059.i10 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.cageo.2004.03.012 is INVALID because of 'https://doi.org/' prefix
```

**Comment by leonardovida** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00305 is OK
- 10.32614/RJ-2018-009 is OK
- 10.21105/joss.01686 is OK
- 10.18637/jss.v059.i10 is OK
- 10.1016/j.cageo.2004.03.012 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by leonardovida** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03338/joss.03338/10.21105.joss.03338.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03338/joss.03338/10.21105.joss.03338.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @leonardovida - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
