### ISSUE TITLE
[PRE REVIEW]: "JEOL_eds: A Python package to read and process binary EDS data acquired by JEOL's __Analysis Station__ software"

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3339]
**Submitting author:** @ialxn (<a href="http://orcid.org/0000-0002-9389-9849">Ivo Alxneit</a>)
**Repository:** <a href="https://github.com/ialxn/JEOL_eds" target ="_blank">https://github.com/ialxn/JEOL_eds</a>
**Version:** v1.7.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/50b14daf73e205a8e7d6fff549a99791/status.svg)](https://joss.theoj.org/papers/50b14daf73e205a8e7d6fff549a99791)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/50b14daf73e205a8e7d6fff549a99791"><img src="https://joss.theoj.org/papers/50b14daf73e205a8e7d6fff549a99791/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/50b14daf73e205a8e7d6fff549a99791/status.svg)](https://joss.theoj.org/papers/50b14daf73e205a8e7d6fff549a99791)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ialxn. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @jni.

@ialxn if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (143.4 files/s, 35259.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            317           1035            868
Markdown                         1             43              0            196
-------------------------------------------------------------------------------
SUM:                            10            360           1035           1064
-------------------------------------------------------------------------------


Statistical information for the repository '9a2a9e6f03d8270d7bc8ff0f' was
gathered on 2021/06/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ivo Alxneit                    154          3389           1168          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ivo Alxneit                2220           65.5          2.9               14.55
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3339 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @ialxn and thanks for your submission! It is a bit on the small side, so I have tagged it for the editorial board to check it for being in scope for the journal. This process will take 1-2 weeks. Thanks.

**Comment by kthyng** [comment]
@whedon generate pdf from branch JOSS_submitted

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03339/joss.03339/10.21105.joss.03339.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03339/joss.03339/10.21105.joss.03339.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @ialxn - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
