### ISSUE TITLE
[PRE REVIEW]: Sequana: a set of flexible genomic pipelines for processing and reporting NGS analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#334]
**Submitting author:** @cokelaer (<a href="http://orcid.org/0000-0001-6286-1138">Thomas Cokelaer</a>)
**Repository:** <a href="https://github.com/sequana/sequana/" target ="_blank">https://github.com/sequana/sequana/</a>
**Version:** 0.4.1
**Editor:** @pjotrp
**Reviewer:** @bow

**Author instructions**

Thanks for submitting your paper to JOSS @cokelaer. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@cokelaer if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@pjotrp - the submitting author suggested you as a potential editor.

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@cokelaer thank you for your submission! I'll be looking for a reviewer soon. In the mean time can you help out with a few things? I can't find the paper.md and paper.bib files. Can you point them to me? Also can you make the LICENSE file standard - if it is it will show up on github with the right license icon. Thanks!

**Comment by cokelaer** [comment]
@ pjotrp
I've fixed the LICENSE and the icon now appears on github. 
As for the paper.md and paper.bib, what do mean exactly ? Where shall I provide those files and what should be the content ? thanks

**Comment by pjotrp** [comment]
Best is to check one of the existing publication. See https://github.com/genenetwork/genenetwork2/tree/master/doc/joss/2016

**Comment by cokelaer** [comment]
Do the paper.bib and paper.md must be in the repository of the software or can they be put elsewhere ? Sequana is an organisation and we put the software in sequana/sequana but for papers, we'd like to keep it separate for instance in ./sequana/resources . Would it be fine with your policy ?

**Comment by arfon** [comment]
> Would it be fine with your policy?

I *think* this is going to break some of our submission tooling (i.e. it's expected that the paper be in the software repository being reviewed). Let me check and get back to you.

For reference, some authors have made a folder in `docs` e.g..`docs/paper/paper.md` - might something like this work for you?

**Comment by pjotrp** [comment]
As the final paper gets generated from the source tree it is tied to the commit of that release. You *can* remove the paper from the source tree once it is published. It will be in that particular source release and git history. So it is not intrusive. Makes sense to tie it to the project, right?

**Comment by cokelaer** [comment]
okay, that's fine, I will add a ./joss directory in  the ./doc 
thanks

**Comment by cokelaer** [comment]
FYI we have added a paper.bib paper.md in https://github.com/sequana/sequana/tree/master/doc/joss

**Comment by pjotrp** [comment]
That looks great. @bow since since this is a snakemake application would you care to review this JOSS submission?

**Comment by bow** [comment]
@pjotrp & @cokelaer I'd be happy to review the submission. I would need a week's time, if that's ok.

**Comment by pjotrp** [comment]
No problem. Thanks @bow.

**Comment by pjotrp** [comment]
@whedon assign @bow as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @bow

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/352. Feel free to close this issue now!
