### ISSUE TITLE
[PRE REVIEW]: Kinetics Toolkit: An Open-Source Python Package to Facilitate Research in Biomechanics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3340]
**Submitting author:** @felixchenier (<a href="http://orcid.org/0000-0002-2085-6629">Félix Chénier</a>)
**Repository:** <a href="https://github.com/felixchenier/kineticstoolkit_joss" target ="_blank">https://github.com/felixchenier/kineticstoolkit_joss</a>
**Version:** 0.5.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/23b5d4d922e898d1c003148837af81bd/status.svg)](https://joss.theoj.org/papers/23b5d4d922e898d1c003148837af81bd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/23b5d4d922e898d1c003148837af81bd"><img src="https://joss.theoj.org/papers/23b5d4d922e898d1c003148837af81bd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/23b5d4d922e898d1c003148837af81bd/status.svg)](https://joss.theoj.org/papers/23b5d4d922e898d1c003148837af81bd)
```

**Author instructions**

Thanks for submitting your paper to JOSS @felixchenier. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@felixchenier if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (423.7 files/s, 48828.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              1             17              0            275
Markdown                         2             56              0             90
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                             4             74              4            383
-------------------------------------------------------------------------------


Statistical information for the repository 'ad5879798430abfbed222896' was
gathered on 2021/06/08.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jbiomech.2004.05.042 is OK
- 10.21105/joss.02431 is OK
- 10.1016/j.cmpb.2016.11.007 is OK
- 10.21105/joss.02562 is OK
- 10.1109/SII.2019.8700380 is OK
- 10.1098/rsos.140449 is OK
- 10.1371/journal.pcbi.1006223 is OK
- 10.1016/j.piutam.2011.04.023 is OK
- 10.21105/joss.00927 is OK
- 10.1101/2021.02.27.432868 is OK
- 10.21105/joss.02911 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5334/jors.148 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03340/joss.03340/10.21105.joss.03340.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03340/joss.03340/10.21105.joss.03340.pdf) :page_facing_up: :point_left:

**Comment by felixchenier** [comment]
Hi @kthyng 
Here: https://github.com/felixchenier/kineticstoolkit

**Comment by felixchenier** [comment]
I checked at the list and I think these persons who I don't know may be relevant for this review:

alcantarar
ixjlyons
melund

then

CELavecchia
anmuller
BabakNSafa
cpontonn

then

trallard
moorepants

**Comment by kthyng** [comment]
Hi @felixchenier — can you resubmit your submission but with https://github.com/felixchenier/kineticstoolkit as the input url associated with your submission instead of the paper url? Usually the JOSS paper just sits in the software repo in a subdirectory or in a branch. Please copy over your helpful list of reviewer suggestions, too. I will withdraw your current submission now to start this process.

**Comment by kthyng** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.

**Comment by felixchenier** [comment]
Hi @kthyng 
OK, this is done, I just resubmitted it. Sorry for my misunderstanding.
