### ISSUE TITLE
[PRE REVIEW]: OSTIR: open source translation initiation rate prediction

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3342]
**Submitting author:** @jeffreybarrick (<a href="http://orcid.org/0000-0003-0888-7358">Jeffrey Barrick</a>)
**Repository:** <a href="https://github.com/barricklab/ostir" target ="_blank">https://github.com/barricklab/ostir</a>
**Version:** v1.0.4
**Editor:** @csoneson
**Reviewers:** @ayush9pandey, @standage
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/43d02b32408a161e608b886f63e753c1/status.svg)](https://joss.theoj.org/papers/43d02b32408a161e608b886f63e753c1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/43d02b32408a161e608b886f63e753c1"><img src="https://joss.theoj.org/papers/43d02b32408a161e608b886f63e753c1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/43d02b32408a161e608b886f63e753c1/status.svg)](https://joss.theoj.org/papers/43d02b32408a161e608b886f63e753c1)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jeffreybarrick. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @fboehm.

@jeffreybarrick if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (296.0 files/s, 79036.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5            405            229           1417
Markdown                         3             54              0            238
R                                1             49             55            129
TeX                              1              0              1             93
-------------------------------------------------------------------------------
SUM:                            10            508            285           1877
-------------------------------------------------------------------------------


Statistical information for the repository '37ef3bf7b1608e79344c4f0a' was
gathered on 2021/06/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Cameron                          8            97             61            1.36
Cameron Roots                   15           554            711           10.91
Jeffrey Barrick                 11           654            391            9.01
croots                          21          2274           3492           49.72
jeffreybarrick                   4          3244            120           29.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Cameron                     199          205.2          2.6                6.53
Cameron Roots               140           25.3          4.6                8.57
Jeffrey Barrick             559           85.5          1.4               11.63
croots                     1153           50.7          6.4               10.32
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/nbt.1568 is OK
- 10.1016/B978-0-12-385120-8.00002-4 is OK
- 10.1093/nar/gkt1139 is OK
- 10.1021/acssynbio.0c00394 is OK
- 10.1093/bioinformatics/btq458 is OK
- 10.1186/1748-7188-6-26 is OK
- 10.1038/s41592-018-0046-7 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1002/jcc.215966 is INVALID
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03342/joss.03342/10.21105.joss.03342.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03342/joss.03342/10.21105.joss.03342.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@csoneson is this near your field of expertise and could you edit it?

**Comment by kthyng** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋🏻 @jeffreybarrick - I will handle your submission and start by finding some suitable reviewers. If you have any suggestions (e.g., from the list linked in the first post above), please let me know!

**Comment by jeffreybarrick** [comment]
@csoneson - Thanks! Here are some reviewers we'd suggest from the list: rpetit3, ayush9pandey, standage, mjsull

**Comment by csoneson** [comment]
👋🏻 @rpetit3, @ayush9pandey - would you be interested in reviewing this submission for JOSS? 

> OSTIR: open source translation initiation rate prediction

**Comment by rpetit3** [comment]
@csoneson Unfortunately, I'm going to have to pass this time. I've just started a new job and am a bit stretched for time.

**Comment by csoneson** [comment]
Thank you both for your quick replies! @ayush9pandey - I'll assign you now, and we'll start the review once we have secured a second reviewer. 
@rpetit3 - no problem, good luck with the new job!

**Comment by csoneson** [comment]
@whedon assign @ayush9pandey as reviewer

**Comment by whedon** [comment]
OK, @ayush9pandey is now a reviewer

**Comment by csoneson** [comment]
👋🏻 @standage - would you be interested in reviewing this submision for JOSS? 

> OSTIR: open source translation initiation rate prediction

**Comment by standage** [comment]
@csoneson I'm on a review panel through June 16th, so I wouldn't be able to get to this until later next week. But if that's ok with everybody I'd be happy to review this.

**Comment by csoneson** [comment]
@standage That's all good - thanks a lot!

**Comment by csoneson** [comment]
@whedon add @standage as reviewer

**Comment by whedon** [comment]
OK, @standage is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3362.
