### ISSUE TITLE
[PRE REVIEW]: Kinetics Toolkit: An Open-Source Python Package to Facilitate Research in Biomechanics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3343]
**Submitting author:** @felixchenier (<a href="http://orcid.org/0000-0002-2085-6629">Félix Chénier</a>)
**Repository:** <a href="https://github.com/felixchenier/kineticstoolkit" target ="_blank">https://github.com/felixchenier/kineticstoolkit</a>
**Version:** 5.0.1
**Editor:** @meg-simula
**Reviewers:** @alcantarar, @melund
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/05a091aa8cf7171d42d56e636c6d79fd/status.svg)](https://joss.theoj.org/papers/05a091aa8cf7171d42d56e636c6d79fd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/05a091aa8cf7171d42d56e636c6d79fd"><img src="https://joss.theoj.org/papers/05a091aa8cf7171d42d56e636c6d79fd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/05a091aa8cf7171d42d56e636c6d79fd/status.svg)](https://joss.theoj.org/papers/05a091aa8cf7171d42d56e636c6d79fd)
```

**Author instructions**

Thanks for submitting your paper to JOSS @felixchenier. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@felixchenier if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3343 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=3.73 s (57.6 files/s, 208444.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              0         681057
HTML                           123          16364            366          45354
JavaScript                      13           2405           2470           9210
Python                          35           2192           3831           5198
SVG                              1              0              0           2671
CSS                              5            194             35            779
Jupyter Notebook                21              0           4382            645
Markdown                         3             16              0             53
reStructuredText                 9             79            207             42
DOS Batch                        1              8              1             26
YAML                             1              1              0             15
make                             1              4              7              9
INI                              1              0              0              2
-------------------------------------------------------------------------------
SUM:                           215          21263          11299         745061
-------------------------------------------------------------------------------


Statistical information for the repository '7360dfe8be563ad9bdca8769' was
gathered on 2021/06/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Félix Chénier                122         43979          26994          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Félix Chénier           25306           57.5          6.7               15.62
```

**Comment by kthyng** [comment]
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03343/joss.03343/10.21105.joss.03343.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03343/joss.03343/10.21105.joss.03343.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@meg-simula is this type of biomechanics closer to your area of expertise?

**Comment by kthyng** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by meg-simula** [comment]
@whedon assign @meg-simula as editor

**Comment by whedon** [comment]
OK, the editor is @meg-simula

**Comment by felixchenier** [comment]
Good morning @meg-simula 
Thanks for being part of this amazing journal.
I'm wondering if my submission has been forgotten since it's been in pre-review for a while, but I understand we are in a pandemic summer so I don't expect things to go fast. I was just wondering.
Thank you again,
Felix Chenier

**Comment by felixchenier** [comment]
Good morning @kthyng

I don't know if this is standard since I this is my first submission to JOSS, but my manuscript has been in pre-review for nearly 2 months and I couldn't receive news from the editor (@meg-simula).

If this is standard or to be expected during this pandemic summer, please disregard this message.

Thank you and best regards,

Félix Chénier

**Comment by meg-simula** [comment]
@felixchenier Thank you for the submission! I have been out of office due to summer holidays, hence the delayed handling (not at all standard handling time). Will have a look shortly.

**Comment by meg-simula** [comment]
@felixchenier Thanks again for your submission of Kinetics toolkit; it looks well within the JOSS scope. 

If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition,[ this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by felixchenier** [comment]
Hi @meg-simula 

Here is the list you asked for. I wrote it for on a previous submission for Kinetics Toolkit, I'm not **that** fast :-)

alcantarar
ixjlyons
melund

then

CELavecchia
anmuller
BabakNSafa
cpontonn

then

trallard
moorepants

**Comment by meg-simula** [comment]
:wave: @moorepants, would you be available to review this submission for JOSS? Feel free to revisit the reviewer guidelines here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .

**Comment by meg-simula** [comment]
:wave: @alcantarar, would you be available to review this submission for JOSS? Feel free to revisit the reviewer guidelines here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .

**Comment by alcantarar** [comment]
@meg-simula Sure, I can review this submission.

**Comment by meg-simula** [comment]
Great, thanks @alcantarar !

**Comment by meg-simula** [comment]
@whedon assign @alcantarar as reviewer

**Comment by whedon** [comment]
OK, @alcantarar is now a reviewer

**Comment by felixchenier** [comment]
Good morning @meg-simula 

Just a reminder that this manuscript has now been in pre-review for three months. I certainly don't want to look insistant, it is simply a reminder.

Thank you

**Comment by moorepants** [comment]
No I can't, as I have a large review obligation elsewhere at the moment.

**Comment by meg-simula** [comment]
:wave: @ixjlyons or @melund, would either of you be available to review this submission for JOSS? Feel free to revisit the reviewer guidelines here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html .

**Comment by melund** [comment]
@meg-simula Sure, I can do the review.

**Comment by Kevin-Mattheus-Moerman** [comment]
@meg-simula I can suggest `modenaxe` as a reviewer too.

**Comment by meg-simula** [comment]
@melund Great!

**Comment by meg-simula** [comment]
@whedon add @melund as reviewer

**Comment by whedon** [comment]
OK, @melund is now a reviewer

**Comment by meg-simula** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3714.
