### ISSUE TITLE
[PRE REVIEW]: Lcopt - An interactive tool for creating fully parameterised Life Cycle Assessment (LCA) foreground models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#335]
**Submitting author:** @pjamesjoyce (<a href="http://orcid.org/0000-0002-9560-3132">P. James Joyce</a>)
**Repository:** <a href="https://github.com/pjamesjoyce/lcopt" target ="_blank">https://github.com/pjamesjoyce/lcopt</a>
**Version:** v0.4.0
**Editor:** @katyhuff
**Reviewer:** @amoeba

**Author instructions**

Thanks for submitting your paper to JOSS @pjamesjoyce. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@pjamesjoyce if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @katyhuff it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @katyhuff - the submitting author suggested you as an editor.

**Comment by pjamesjoyce** [comment]
Hi all, perhaps @amoeba (who reviewed the Brightway LCA software #236) would be an option to review if they have time?

**Comment by katyhuff** [comment]
@amoeba would you be willing to review this submission? You did a great job with the Brigthway2 paper! I hope you'll let me know if you can take this on.

Alternatively, @cmutel, you might also be a great reviewer for this submission.  I recognize that, given the relationship of this submission to Brightway2, I can imagine you may have a conflict of interest. However, if you feel you can give an unconflicted review, I think the submission would benefit from someone with a strong knowledge of this software. Please let me know if you could give an unconflicted review and would be willing to do so.

**Comment by amoeba** [comment]
@katyhuff Sure. I can look at this this weekend or earlier. I would love it if @cmutel could at least comment on the correctness of this software, which I can't do confidently due to my lack of experience with LCA. I'm happy to be the reviewer though.

**Comment by katyhuff** [comment]
@whedon assign @amoeba as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @amoeba

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by katyhuff** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/339. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Thanks @amoeba ! You're assigned as the reviewer. Now you (and, if willing to help, @cmutel) can conduct this review over in #339. Please let me know if you have any questions!

**Comment by cmutel** [comment]
Thanks for the invite - I would be able to do this, but only after returning from vacation on August 8th.
