### ISSUE TITLE
[PRE REVIEW]: mcboost: Multi-Calibration Boosting for R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3352]
**Submitting author:** @pfistfl (<a href="http://orcid.org/0000-0001-8867-762X">Florian Pfisterer</a>)
**Repository:** <a href="https://github.com/mlr-org/mcboost" target ="_blank">https://github.com/mlr-org/mcboost</a>
**Version:** v0.3.0
**Editor:** @osorensen
**Reviewers:** @mwt, @OwenWard
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/19899bbe517d82bb1d5c7dbb2e8c539f/status.svg)](https://joss.theoj.org/papers/19899bbe517d82bb1d5c7dbb2e8c539f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/19899bbe517d82bb1d5c7dbb2e8c539f"><img src="https://joss.theoj.org/papers/19899bbe517d82bb1d5c7dbb2e8c539f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/19899bbe517d82bb1d5c7dbb2e8c539f/status.svg)](https://joss.theoj.org/papers/19899bbe517d82bb1d5c7dbb2e8c539f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @pfistfl. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @terrytangyuan.

@pfistfl if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (1399.2 files/s, 137739.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               22            180            687           1125
Markdown                         6            141              0            458
JSON                             1              0              0            367
Rmd                              3            245            406            354
YAML                             2             25             28             99
TeX                              1             23              2             85
SVG                              8              0              0              8
-------------------------------------------------------------------------------
SUM:                            43            614           1123           2496
-------------------------------------------------------------------------------


Statistical information for the repository 'b607b070fa73e64281152abc' was
gathered on 2021/06/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41467-020-18297-9 is OK
- 10.1093/jamia/ocaa283 is OK
- 10.1109/FOCS.2019.00016 is OK
- 10.1145/3306618.3314287 is OK
- 10.21105/joss.01903 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03352/joss.03352/10.21105.joss.03352.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03352/joss.03352/10.21105.joss.03352.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @pfistfl and thanks for your submission! Since it is a bit on the small side, I have triggered a process for the editorial board to check to make sure it is in scope. This process should take 1-2 weeks. Thanks for your patience.

**Comment by danielskatz** [comment]
👋 @pfistfl - the editors have decided this is in scope, so we will accept it for review. However, due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

**Comment by arfon** [comment]
@whedon invite @osorensen as editor

:wave: @osorensen – would you be willing to edit this submission for JOSS?

**Comment by osorensen** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
I'm sorry @osorensen, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by osorensen** [comment]
Yes, @arfon, I'm willing. Seems like @whedon doesn't know I'm an editor yet though.

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
I'm sorry @osorensen, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by arfon** [comment]
> I'm sorry @osorensen, I'm afraid I can't do that. That's something only editors are allowed to do.

@whedon clearly woke up with an improved attitude this morning 😆

**Comment by osorensen** [comment]
@pfistfl, I am now the editor for this submission. If you have any suggestions for potential reviewers, please mention them in this thread (without the @).

**Comment by osorensen** [comment]
@mwt, @dbarneche, @OwenWard, @BrandonEdwards: would any of you be interested in reviewing this JOSS paper?

**Comment by mwt** [comment]
@osorensen Sure. I'm happy to try reviewing it.

**Comment by dbarneche** [comment]
Apologies I am unavailable to review papers until the 16th of August.

**Comment by osorensen** [comment]
@whedon add @mwt as reviewer

**Comment by whedon** [comment]
OK, @mwt is now a reviewer

**Comment by osorensen** [comment]
@dbarneche, that's absolutely fine. Thanks for your quick response!

**Comment by OwenWard** [comment]
@osorensen sure, I'm happy to do it.

**Comment by osorensen** [comment]
@whedon add @OwenWard as reviewer

**Comment by whedon** [comment]
OK, @OwenWard is now a reviewer

**Comment by mwt** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by mwt** [comment]
Are we ready to change this from pre-review to review? I'm guessing we need to do that to make the checklist appear, but I haven't done this before.

**Comment by osorensen** [comment]
@mwt, thanks for following up :)

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3453.
