### ISSUE TITLE
[PRE REVIEW]: mpi4jax: Zero-copy MPI communication of JAX arrays

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3353]
**Submitting author:** @dionhaefner (<a href="http://orcid.org/0000-0002-4465-7317">Dion Häfner</a>)
**Repository:** <a href="https://github.com/mpi4jax/mpi4jax-joss" target ="_blank">https://github.com/mpi4jax/mpi4jax-joss</a>
**Version:** v0.3.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a67d513bb0d8feda89963971454813f1/status.svg)](https://joss.theoj.org/papers/a67d513bb0d8feda89963971454813f1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a67d513bb0d8feda89963971454813f1"><img src="https://joss.theoj.org/papers/a67d513bb0d8feda89963971454813f1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a67d513bb0d8feda89963971454813f1/status.svg)](https://joss.theoj.org/papers/a67d513bb0d8feda89963971454813f1)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dionhaefner. **Currently, there isn't an JOSS editor assigned** to your paper.

@dionhaefner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (631.6 files/s, 53688.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2             60              0            161
TeX                              1             19              0            149
YAML                             2              4              4             28
-------------------------------------------------------------------------------
SUM:                             5             83              4            338
-------------------------------------------------------------------------------


Statistical information for the repository '8879a82de3727476559b9c73' was
gathered on 2021/06/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03353/joss.03353/10.21105.joss.03353.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03353/joss.03353/10.21105.joss.03353.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5194/gmd-11-3299-2018 is OK
- 10.1016/j.softx.2019.100311 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2010.118 is OK
- 10.1103/PhysRevLett.126.036401 is OK
- 10.1137/141000671 is OK

MISSING DOIs

- 10.3389/fnbot.2019.00006 may be a valid DOI for title: A Differentiable Physics Engine for Deep Learning in Robotics

INVALID DOIs

- https://doi.org/10.1016/j.jpdc.2005.03.010 is INVALID because of 'https://doi.org/' prefix
```

**Comment by kthyng** [comment]
Hi @dionhaefner and thanks for your submission. What is the software repo that you want reviewed?

**Comment by dionhaefner** [comment]
👋 @kthyng, thanks for having us!

That would be [mpi4jax/mpi4jax](https://github.com/mpi4jax/mpi4jax).

**Comment by kthyng** [comment]
Ok great! The easiest thing to do here is: I will "withdraw" the current submission, and ask you to resubmit this software but using that github url that points to the software itself. Please do this when you can, I'll withdraw now.

**Comment by kthyng** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
