### ISSUE TITLE
[PRE REVIEW]: Sync Toolbox: A Python Package for Efficient, Robust, and Accurate Music Synchronization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3354]
**Submitting author:** @yiitozer (<a href="http://orcid.org/0000-0003-2235-8655">Yigitcan Özer</a>)
**Repository:** <a href="https://github.com/meinardmueller/synctoolbox" target ="_blank">https://github.com/meinardmueller/synctoolbox</a>
**Version:** 1.0.0
**Editor:** @faroit
**Reviewers:** @lutzhamel, @magdalenafuentes
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/97fee2c5ecea5fdff5f866ce7f529daf/status.svg)](https://joss.theoj.org/papers/97fee2c5ecea5fdff5f866ce7f529daf)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/97fee2c5ecea5fdff5f866ce7f529daf"><img src="https://joss.theoj.org/papers/97fee2c5ecea5fdff5f866ce7f529daf/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/97fee2c5ecea5fdff5f866ce7f529daf/status.svg)](https://joss.theoj.org/papers/97fee2c5ecea5fdff5f866ce7f529daf)
```

**Author instructions**

Thanks for submitting your paper to JOSS @yiitozer. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @faroit.

@yiitozer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (458.0 files/s, 187436.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      14           2405           2473           9211
HTML                            18           2314             51           3366
SVG                              1              0              0           2671
Python                          15            586            878           1236
CSS                              4            191             35            757
Jupyter Notebook                 3              0            810            239
Markdown                         1             23              0             31
DOS Batch                        1              8              1             26
reStructuredText                 9             23             43             23
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            67           5554           4298          17569
-------------------------------------------------------------------------------


Statistical information for the repository 'be5b082dd3501fd44e4fc67c' was
gathered on 2021/06/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Michael Krause                   6         18821           2032          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael Krause            16789           89.2          0.0               16.02
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3354 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03354/joss.03354/10.21105.joss.03354.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03354/joss.03354/10.21105.joss.03354.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @faroit are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @faroit as editor

**Comment by whedon** [comment]
@faroit has been invited to edit this submission.

**Comment by faroit** [comment]
@kthyng I would be happy to edit this. 

Just a disclosure: I had one [paper published](https://qmro.qmul.ac.uk/xmlui/handle/123456789/26103) with @meinardmueller (the first author of this submission) 4 years ago and we were both employed by the same institution at that time. Other than that, I don't see any part of the [JOSS COI policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy) that would speak against me here plus I feel more than certain that I can edit this unbiased.

**Comment by kthyng** [comment]
Thank you for stating this @faroit. I'm comfortable with you proceeding as editor in this case.

**Comment by faroit** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @faroit

**Comment by yiitozer** [comment]
Dear JOSS team,

Thank you for starting the prereview process.

I would suggest as possible reviewers faroit, brunaw, expectopatronum and lutzhamel.

**Comment by faroit** [comment]
👋  Hi @yiitozer @meinardmueller, thanks for your submission to JOSS! I will be serving as the editor for this (so I obviously won't review myself). We'll use this issue to identify reviewers and resolve technical issues. Thanks for the list of potential reviewers you provided. That looks good to me, I would also like to add @ magdalenafuentes if you agree that would be a good fit as well.

**Comment by arfon** [comment]
:wave: @meinardmueller @yiitozer – I just took a cursory look at the paper and the software repository here and wondered if there was a reason for the authorship order, especially given that it looks like @yiitozer made the majority of the code contributions here?

Just to be clear, JOSS doesn't police authorship decisions, but we do flag when things look anomalous.

<img width="924" alt="Screenshot 2021-06-11 at 20 13 35" src="https://user-images.githubusercontent.com/4483/121738566-472d9c80-caf2-11eb-82cb-a7a2bc20f68e.png">

**Comment by yiitozer** [comment]
>  Hi @yiitozer @meinardmueller, thanks for your submission to JOSS! I will be serving as the editor for this (so I obviously won't review myself). We'll use this issue to identify reviewers and resolve technical issues. Thanks for the list of potential reviewers you provided. That looks good to me. I would also like to add @ magdalenafuentes if you agree that would be a good fit as well.

Hi @faroit, thank you for taking care of this! I agree that @magdalenafuentes would be a great fit. Thanks for your suggestion.

**Comment by meinardmueller** [comment]
> 👋 @meinardmueller @yiitozer @ahnonay – I just took a cursory look at the paper and the software repository here and wondered if there was a reason for the authorship order, especially given that it looks like @ahnonay made the majority of the code contributions here?
> 
> Just to be clear, JOSS doesn't police authorship decisions, but we do flag when things look anomalous.
> 
> <img alt="Screenshot 2021-06-11 at 20 13 35" width="924" src="https://user-images.githubusercontent.com/4483/121738566-472d9c80-caf2-11eb-82cb-a7a2bc20f68e.png">

Dear @arfon, many thanks for asking concerning the authorship order. Yes, there are some reasons that we want to explain briefly. The Sync Toolbox is a long-term project, which beginnings go back to 2006. The first synchronization procedures were developed by the first author @meinardmueller, resulting in internal research source code. This code has been successively expanded by various people from the first author's research group, resulting in an internal MATLAB toolbox. The internal toolbox was now re-implemented in Python mainly by @yiitozer and @ahnonay The JOSS paper itself was written mainly by @meinardmueller. Regardless of the respective contributions, the code and the paper's markdown was pushed to github by @ahnonay and @yiitozer; we did not care about github commit numbers or any other metrics. Internally, we discussed and agreed on the author order as stated in the paper. We want to apologize if we have deviated from git conventions, and we hope that these explanations clarify your question.

**Comment by faroit** [comment]
👋  @magdalenafuentes @expectopatronum @lutzhamel - would any of you be willing to review this submission for JOSS? The JOSS review process takes place on GitHub and focuses on the software and a short paper. We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The software under review is [Sync Toolbox: A Python Package for Efficient, Robust, and Accurate Music Synchronization ](https://github.com/meinardmueller/synctoolbox).

This issue is a "pre-review" issue in which reviewers are assigned. Once sufficient reviewers are recruited we will open a dedicated review issue where the review will take place.

**Comment by arfon** [comment]
Got it. Thanks for the explanation @meinardmueller.

**Comment by lutzhamel** [comment]
Hi,  I'd be happy to act as a reviewer if you still need one for this
project.

**Comment by whedon** [comment]
OK, @lutzhamel is now a reviewer

**Comment by magdalenafuentes** [comment]
Hi @faroit, sorry for the late reply, I'm currently on vacation until next week and just saw the invite. I'd be happy to review this submission

**Comment by faroit** [comment]
@magdalenafuentes great news. Thanks  a lot. Enjoy your vacation

**Comment by faroit** [comment]
@whedon add @magdalenafuentes as reviewer

**Comment by whedon** [comment]
OK, @magdalenafuentes is now a reviewer

**Comment by faroit** [comment]
alright, I had another quick look at the paper. Looks all good to me. We can start the review process

**Comment by faroit** [comment]
@whedon check references

**Comment by arfon** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by faroit** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by arfon** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by arfon** [comment]
@yiitozer – please merge this PR to fix your paper: https://github.com/meinardmueller/synctoolbox/pull/1

**Comment by yiitozer** [comment]
Thank you @arfon, I merged your pull request.

**Comment by faroit** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-319-21945-5 is OK
- 10.1109/ICASSP.2016.7471739 is OK
- 10.1109/TASLP.2020.3030485 is OK
- 10.25080/Majora-7b98e3ed-003 is OK
- 10.5281/zenodo.1416951 is OK
- 10.5281/zenodo.4245470 is OK

MISSING DOIs

- 10.1109/icassp.2009.4959972 may be a valid DOI for title: High Resolution Audio Synchronization Using Chroma Onset Features

INVALID DOIs

- None
```

**Comment by faroit** [comment]
@yiitozer can you please add the missing DOIs before we can proceed with the review?

**Comment by yiitozer** [comment]
hello @faroit, I added the missing DOIs, for some references, no DOIs are available.

**Comment by faroit** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3434.
