### ISSUE TITLE
[PRE REVIEW]: Lumen: A software for the interactive visualization of probabilistic models together with data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3355]
**Submitting author:** @nandaloo (<a href="http://orcid.org/0000-0002-6687-8209">Philipp Lucas</a>)
**Repository:** <a href="https://github.com/lumen-org/lumen" target ="_blank">https://github.com/lumen-org/lumen</a>
**Version:** v0.9
**Editor:** @vissarion
**Reviewers:** @crhea93, @szkafander
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2/status.svg)](https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2"><img src="https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2/status.svg)](https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nandaloo. **Currently, there isn't an JOSS editor assigned** to your paper.

@nandaloo if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jmva.2020.104601 is OK
- 10.7717/peerj-cs.55 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- 10.1109/iccvw.2011.6130310 may be a valid DOI for title: Sum-Product Networks: A New Deep Architecture
- 10.1109/2945.981851 may be a valid DOI for title: Polaris: A System for Query, Analysis, and Visualization of Multidimensional Relational Databases

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=9.33 s (14.4 files/s, 9650.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      86           7669          19336          36625
SVG                             36             36             36          16233
CSS                              4            903            220           7898
Markdown                         4            221              0            510
TeX                              1             16              0            165
HTML                             1             22             30             91
JSON                             2              1              0             74
-------------------------------------------------------------------------------
SUM:                           134           8868          19622          61596
-------------------------------------------------------------------------------


Statistical information for the repository '0d8ae95c487b6de423fd64be' was
gathered on 2021/06/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
=                                7            96             23            0.06
Andreas Goral                    2           318              0            0.16
Christoph Saffer                 3            12             11            0.01
Joachim Giesen                   2             8              7            0.01
Philipp Lucas                  729        132104          68882           99.61
Schmalwasser                    11           151             70            0.11
asver12                          1            31             63            0.05

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
=                            86           89.6         19.5                4.65
Christoph Saffer              3           25.0         30.7                0.00
Joachim Giesen                1           12.5         41.7                0.00
Philipp Lucas             63457           48.0         28.9               15.70
Schmalwasser                 53           35.1         21.7                3.77
asver12                      30           96.8         21.2                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03355/joss.03355/10.21105.joss.03355.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03355/joss.03355/10.21105.joss.03355.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @nandaloo and thanks for your submission. We have a backlog of submissions that I am adding this submission to. When an editor with relevant expertise is available, they will take this on. Thanks for your patience.

**Comment by nandaloo** [comment]
Hi @kthyng,
thanks a lot!
I had a look at the list of available reviewers, and here are some suggestions. I looked more into matching topics than into matching programming languages:

- Carter Rhea (crhea93)
- Pál Tóth (szkafander)
- Abhishek Dutta (thelinuxmaniac)
- Matthew Graham (matt-graham)
- maximtrp
- prasantapal

**Comment by vissarion** [comment]
Hi, @kthyng, @nandaloo I am happy to edit this submission.

**Comment by vissarion** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @vissarion

**Comment by vissarion** [comment]
Hi, @crhea93, @szkafander, @thelinuxmaniac as suggested by @nandaloo and verified by myself this submission could be interesting for you.

Would you be willing to review this submission for JOSS? 

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by crhea93** [comment]
Yes I will be happy to review this work.

**Comment by szkafander** [comment]
Happy to!

**Comment by szkafander** [comment]
Dear Vissarion,

I am happy to review this submission.

Kind regards,

Paul

**Comment by vissarion** [comment]
@whedon assign @crhea93 and @szkafander as reviewers

**Comment by whedon** [comment]
OK, @crhea93 and @szkafander is now a reviewer

**Comment by vissarion** [comment]
@whedon assign @crhea93 as reviewer

**Comment by whedon** [comment]
OK, @crhea93 is now a reviewer

**Comment by vissarion** [comment]
@whedon add @szkafander as reviewer

**Comment by whedon** [comment]
OK, @szkafander is now a reviewer

**Comment by vissarion** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3395.
