### ISSUE TITLE
[PRE REVIEW]: TweetClip: A command line tool for streamlining Twitter JSON data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3356]
**Submitting author:** @republicof1 (<a href="http://orcid.org/0000-0002-6608-9648">Benjamin Green</a>)
**Repository:** <a href="https://github.com/Republicof1/TweetClip" target ="_blank">https://github.com/Republicof1/TweetClip</a>
**Version:** v2.6.6
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/73622458805351cf7a55be291c0bb265/status.svg)](https://joss.theoj.org/papers/73622458805351cf7a55be291c0bb265)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/73622458805351cf7a55be291c0bb265"><img src="https://joss.theoj.org/papers/73622458805351cf7a55be291c0bb265/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/73622458805351cf7a55be291c0bb265/status.svg)](https://joss.theoj.org/papers/73622458805351cf7a55be291c0bb265)
```

**Author instructions**

Thanks for submitting your paper to JOSS @republicof1. **Currently, there isn't an JOSS editor assigned** to your paper.

@republicof1 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.32 s (84.0 files/s, 275025.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                             14              2             12          86088
C#                               5            238            152           1284
Markdown                         4            102              0            405
JSON                             3              0              0             74
MSBuild script                   1              4              0             13
-------------------------------------------------------------------------------
SUM:                            27            346            164          87864
-------------------------------------------------------------------------------


Statistical information for the repository 'e6805094cb9917b41b5c650b' was
gathered on 2021/06/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #3356 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
Hi @Republicof1 and thanks for your submission. I am going to trigger a scope query for it to have the editorial board check to make sure it is in scope before we proceed, the main trigger at this point being its relatively small size. This will take 1-2 weeks; thanks for your patience.

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS.md. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3356 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (cdfbf7d3c37de382ad434eef/paper.md): could not find expected ':' while scanning a simple key at line 20 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch JOSS.md

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS.md. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3356 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (e930cc8cf264d9f3d86ec0a9/paper.md): could not find expected ':' while scanning a simple key at line 20 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
@whedon check references from branch JOSS.md

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch JOSS.md
```

**Comment by danielskatz** [comment]
👋 @Republicof1 - as you might have seen, there are a bunch of issues here:

1.  there is no open source license that whedon is detecting, and this is a requirement for JOSS to review the submission
2. the paper does not compile. It looks like there's a problem in line 20 of the .md file, which is probably not following the example paper we provided in https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography
3. Your paper also does not have any references, which is extremely unusual.

I'm going to reject the submission for not, and suggest you fix these and resubmit.  Please see https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles for how you can check this before submitting.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by Republicof1** [comment]
Thanks for the feedback I'll look into the issues and I apologise for oversights that were in this submission.

On point 1, does the license need to be within the same branch as the paper? There is a license in the main branch. 

I will attempt to submit again after through review

**Comment by danielskatz** [comment]
The LICENSE should be fine where it is - I'm not sure why whedon didn't see it.
