### ISSUE TITLE
[PRE REVIEW]: mpi4jax: Zero-copy MPI communication of JAX arrays

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3357]
**Submitting author:** @dionhaefner (<a href="http://orcid.org/0000-0002-4465-7317">Dion Häfner</a>)
**Repository:** <a href="https://github.com/mpi4jax/mpi4jax" target ="_blank">https://github.com/mpi4jax/mpi4jax</a>
**Version:** v0.3.0
**Editor:** @kellyrowland
**Reviewers:** @1313e, @csadorf
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3e6d19d9cccf7620aeaf142feaa9dfb5/status.svg)](https://joss.theoj.org/papers/3e6d19d9cccf7620aeaf142feaa9dfb5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3e6d19d9cccf7620aeaf142feaa9dfb5"><img src="https://joss.theoj.org/papers/3e6d19d9cccf7620aeaf142feaa9dfb5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3e6d19d9cccf7620aeaf142feaa9dfb5/status.svg)](https://joss.theoj.org/papers/3e6d19d9cccf7620aeaf142feaa9dfb5)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dionhaefner. **Currently, there isn't an JOSS editor assigned** to your paper.

@dionhaefner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (725.0 files/s, 103966.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          44           1620           1510           4475
Cython                           5            385             80           1032
YAML                             9             72             10            258
reStructuredText                 8            217            246            153
Bourne Shell                     2             28             85            147
TOML                             1              5              2             38
DOS Batch                        1              8              1             26
Markdown                         1              5              0             17
diff                             1              3             13             13
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            73           2347           1954           6168
-------------------------------------------------------------------------------


Statistical information for the repository '1e33973f4f1511d5a0adc669' was
gathered on 2021/06/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Clemens Giuliani                 2           562             49            4.35
Dion Häfner                     57          8326           2750           78.87
Filippo Vicentini               33          1945            411           16.78

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Clemens Giuliani            247           44.0          5.2                4.45
Dion Häfner                6590           79.1          3.4                9.74
Filippo Vicentini           768           39.5          2.0                6.64
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3357 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@dionhaefner can you put your paper in a branch of mpi4jax if you don't want it in your main repo?

**Comment by dionhaefner** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by dionhaefner** [comment]
Seems like whedon is down, I'll try again later.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
I don't think `@whedon` is down, since it is starting to compile the .md, it's just not finishing, and it's not reporting an error, which probably indicates a bug, so I'm pinging @openjournals/dev here to look into this

**Comment by dionhaefner** [comment]
That's strange, it still worked fine yesterday.

**Comment by danielskatz** [comment]
The preview service seems to hang on it too, so my guess is there's something subtly wrong in the paper/references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03357/joss.03357/10.21105.joss.03357.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03357/joss.03357/10.21105.joss.03357.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
Not sure what was going on here but Whedon seems to be alive again.

**Comment by danielskatz** [comment]
@dionhaefner - thanks for your submission.
Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

**Comment by arfon** [comment]
@whedon assign @kellyrowland as editor

**Comment by whedon** [comment]
OK, the editor is @kellyrowland

**Comment by arfon** [comment]
:zap: thanks to @kellyrowland for agreeing to handle this submission for us!

**Comment by kellyrowland** [comment]
Hi @dionhaefner 👋  if you have any suggestions for potential reviewers, please mention them here in this thread (without tagging them with an @).

**Comment by dionhaefner** [comment]
I don't know anyone first-hand. CC @PhilipVinc, maybe he knows someone.

People from the reviewer list that look relevant:
- pragyansmita
- marksantcroos
- iljah
- diegoenry
- leios
- sarats
- zhampel
- StewMH

**Comment by kellyrowland** [comment]
Thanks! I'm going to reach out to a few folks further down the list to spread out reviewing opportunities, but the expertise list here is a big help.

Hi @csadorf and @1313e 👋 would you be available and willing to review this JOSS submission?

**Comment by 1313e** [comment]
Yup, I would be willing to review this.

**Comment by csadorf** [comment]
@kellyrowland Yes, I am available.

**Comment by kellyrowland** [comment]
Great, thank you both!

**Comment by kellyrowland** [comment]
@whedon add @1313e as reviewer

**Comment by whedon** [comment]
OK, @1313e is now a reviewer

**Comment by kellyrowland** [comment]
@whedon add @csadorf as reviewer

**Comment by whedon** [comment]
OK, @csadorf is now a reviewer

**Comment by kellyrowland** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3419.
