### ISSUE TITLE
[PRE REVIEW]: grapesAgri1-Collection of shiny applications for data analysis in Agriculture-Part 1

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3359]
**Submitting author:** @pratheesh3780 (<a href="http://orcid.org/0000-0003-3290-0436">Pratheesh P Gopinath</a>)
**Repository:** <a href="https://github.com/pratheesh3780/grapesAgri1" target ="_blank">https://github.com/pratheesh3780/grapesAgri1</a>
**Version:** v1.0.0
**Editor:** @fabian-s
**Reviewers:** @adithirgis, @elimillera
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247/status.svg)](https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247"><img src="https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247/status.svg)](https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247)
```

**Author instructions**

Thanks for submitting your paper to JOSS @pratheesh3780. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@pratheesh3780 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (501.5 files/s, 156639.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               12            461            487           4298
Rmd                              6            113            100           1031
TeX                              1             23              0            181
Markdown                         3             52              0            125
-------------------------------------------------------------------------------
SUM:                            22            649            587           5635
-------------------------------------------------------------------------------


Statistical information for the repository '3359859ebf9fd8add314dfb2' was
gathered on 2021/06/11.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03359/joss.03359/10.21105.joss.03359.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03359/joss.03359/10.21105.joss.03359.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1093/oso/9780190222055.003.0002 may be a valid DOI for title: Exploratory Data Analysis

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @pratheesh3780 and thanks for your submission. We currently have a backlog of submissions that I am adding this to. It will be handled as soon as an editor with relevant expertise is available. Thanks for your patience.

**Comment by arfon** [comment]
@whedon invite @fabian-s as editor

:wave: @fabian-s – I realize this is somewhat outside your field, but we don't really have an 'ideal' editor for this submission 😅 . As such, would you be willing to edit this for us?

**Comment by whedon** [comment]
@fabian-s has been invited to edit this submission.

**Comment by fabian-s** [comment]
sure -- 
@whedon assign me as editor

**Comment by fabian-s** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @fabian-s

**Comment by fabian-s** [comment]
@dlebauer @KristinaRiemer @adithirgis --

would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Thank you for considering this!

**Comment by adithirgis** [comment]
Hi @fabian-s, 

Thanks for inviting, I can review this submission.

**Comment by fabian-s** [comment]
@whedon add @adithirgis as reviewer

**Comment by whedon** [comment]
OK, @adithirgis is now a reviewer

**Comment by elimillera** [comment]
Hello @fabian-s ,

I am able to review. Thanks!

**Comment by fabian-s** [comment]
@whedon add @elimillera as reviewer

**Comment by whedon** [comment]
OK, @elimillera is now a reviewer

**Comment by fabian-s** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3437.
