### ISSUE TITLE
[PRE REVIEW]: Django Remote Submission

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#336]
**Submitting author:** @ricleal (<a href="http://orcid.org/0000-0002-9931-8304">Ricardo Miguel Ferraz Leal</a>)
**Repository:** <a href="https://github.com/ornl-ndav/django-remote-submission" target ="_blank">https://github.com/ornl-ndav/django-remote-submission</a>
**Version:** v0.11.1
**Editor:** @arfon
**Reviewer:** @djmitche

**Author instructions**

Thanks for submitting your paper to JOSS @ricleal. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ricleal if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#author_guidelines). In particular, this item:

> - Your software should have a research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)?

Many thanks!

**Comment by ricleal** [comment]
Arfon,

This software is part of our scientific pipeline.
It is used to submit asynchronously to a cluster (using ssh) python scripts. In our case, we have a user friendly web interface and all the complex fitting routines are submitted to this cluster. Once the fitting routine is finished the results are transparently sent back to the user.
Let me know if this is enough to clarify the research application of this software.
Thank you

**Comment by arfon** [comment]
Thanks @ricleal. Since you submitted this package we've expanded a little on the requirements for the `paper.md` file. Could you take a look at the [updated guidelines](http://joss.theoj.org/about#paper_structure) and expand a little on what you have?

In the meantime, I'll look for a reviewer.

**Comment by arfon** [comment]
👋 @adrn - would you be willing to review this submission for JOSS?

**Comment by adrn** [comment]
Howdy! I'm not so familiar with Django, so I don't think I'd be a good fit – sorry!

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
👋 @djmitche - would you be willing to review this submission for JOSS?

**Comment by djmitche** [comment]
Yes, I will have a look.

**Comment by arfon** [comment]
@whedon assign @djmitche as reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @djmitche as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @djmitche

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/366. Feel free to close this issue now!

**Comment by arfon** [comment]
@djmitche please head over to #366 for the actual review will happen.
