### ISSUE TITLE
[PRE REVIEW]: Abmarl: Connecting Agent-Based Simulations with Multi-Agent Reinforcement Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3360]
**Submitting author:** @rusu24edward (<a href="http://orcid.org/0000-0003-1033-439X">Edward Rusu</a>)
**Repository:** <a href="https://github.com/LLNL/Abmarl/" target ="_blank">https://github.com/LLNL/Abmarl/</a>
**Version:** 0.1.2
**Editor:** @drvinceknight
**Reviewers:** @seba-1511, @abhiramm7
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122/status.svg)](https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122"><img src="https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122/status.svg)](https://joss.theoj.org/papers/449c5d79d407dc2e0dbbbb0dae55e122)
```

**Author instructions**

Thanks for submitting your paper to JOSS @rusu24edward. **Currently, there isn't an JOSS editor assigned** to your paper.

@rusu24edward if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3360 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Edward Rusu, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (555.6 files/s, 83003.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          94           2095           1891          10787
reStructuredText                 9            321            649            522
Markdown                         2             35              0            130
YAML                             5             21             19            111
TeX                              1              8              0             72
Bourne Shell                     1             31            242             41
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           114           2523           2809          11698
-------------------------------------------------------------------------------


Statistical information for the repository '639faa6a81af447592e23eb3' was
gathered on 2021/06/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Eddie Rusu                     421         31301          17013           98.20
Edward Rusu                      2           646            181            1.68
glatt1                           1            39             21            0.12

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Eddie Rusu                14757           47.1          1.5                6.27
glatt1                       16           41.0          4.0                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1613/jair.3912 may be a valid DOI for title: The Arcade Learning Environment: An Evaluation Platform for General Agents

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @rusu24edward and thanks for your submission. We currently have a backlog of submissions that I am adding this to. It will be handled as soon as an editor with relevant expertise is available. Thanks for your patience.

**Comment by rusu24edward** [comment]
Potential relevant reviewers, as per whedon's instructions above: satpreetsingh, seba-1511, abhiramm7, bozutemiz, mhetrerajat, giodegas, ionlights.

I'm not sure why the pdf did not build because it builds fine in my GitHub Action. I also don't understand the missing DOI error...

Thanks!

**Comment by rusu24edward** [comment]
Also, as I mentioned in the submission, please review the branch Abmarl-87-interface-release, since this is the release and the extra content on main is not.

**Comment by arfon** [comment]
@whedon assign @drvinceknight as editor

**Comment by whedon** [comment]
OK, the editor is @drvinceknight

**Comment by arfon** [comment]
Thanks to @drvinceknight for agreeing to take this submission on 🙇

**Comment by drvinceknight** [comment]
@whedon generate pdf from branch Abmarl-87-interface-release

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch Abmarl-87-interface-release. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3360 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Edward Rusu, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by drvinceknight** [comment]
@rusu24edward I cannot seem able to find the `` branch so that might be why `whedon` cannot generate the pdf. Can you confirm I've got the  name of the branch correct and that it's on the main repo. Here's a screenshot where I cannot seem to find it:

![CleanShot 2021-06-22 at 09 25 43](https://user-images.githubusercontent.com/2131546/122890833-f44ab500-d33b-11eb-9b1a-8de43361e5c1.png)

**Comment by rusu24edward** [comment]
@whedon generate pdf from branch abmarl-87-interface-release

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch abmarl-87-interface-release. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3360 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Edward Rusu, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by rusu24edward** [comment]
@drvinceknight I'm sorry, I did not realize that github was sensitive to capitalization in the branch name. The name of the branch is `abmarl-87-interface-release`. I've attempted compilation just now, and received the same error as before. This is strange to me because the pdf will compile with the GitHub action... I'll look into resolving this issue, any tips?

**Comment by rusu24edward** [comment]
@whedon generate pdf from branch abmarl-87-interface-release

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch abmarl-87-interface-release. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03360/joss.03360/10.21105.joss.03360.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03360/joss.03360/10.21105.joss.03360.pdf) :page_facing_up: :point_left:

**Comment by rusu24edward** [comment]
@drvinceknight I believe I've fixed the pdf compilation issue. I had forgotten to add an `index` field under the affiliation. It looks like the paper has compiled correctly now.

**Comment by drvinceknight** [comment]
That's great thank you.

**Comment by drvinceknight** [comment]
@satpreetsingh @seba-1511  @abhiramm7 @bozutemiz 'm pinging you to ask if you would be able to assist with reviewing this submissions to JOSS (The Journal of Open Source Software).

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: “Abmarl: Connecting Agent-Based Simulations with Multi-Agent Reinforcement Learning". You can find more information at the top of this Github issue.

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by seba-1511** [comment]
Yes, I should be able to review this submission. When's the review due?

**Comment by rusu24edward** [comment]
My hope is to have it done as soon as possible :)

**Comment by drvinceknight** [comment]
> Yes, I should be able to review this submission. When's the review due?

Thanks @seba-1511! There is no specific due date, I understand how busy everyone is and really appreciate your work on it. I'll add you as a review now.

**Comment by drvinceknight** [comment]
@whedon assign @seba-1511 as reviewer

**Comment by whedon** [comment]
OK, @seba-1511 is now a reviewer

**Comment by drvinceknight** [comment]
Once a second reviewed has been assigned I will start the review.

**Comment by rusu24edward** [comment]
@satpreetsingh @abhiramm7 @bozutemiz, is one of you available to take on this review as the second reviewer? I would really appreciate it :)

**Comment by abhiramm7** [comment]
@rusu24edward yeah, I can review it :)

**Comment by drvinceknight** [comment]
@abhiramm7 thank you.

**Comment by drvinceknight** [comment]
@whedon add @abhiramm7 as reviewer

**Comment by whedon** [comment]
OK, @abhiramm7 is now a reviewer

**Comment by drvinceknight** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3424.

**Comment by drvinceknight** [comment]
The review will now take place on #3424 where there are guidelines but if there is anything I can assist with please let me know.
