### ISSUE TITLE
[PRE REVIEW]: pyAudioProcessing: Audio Processing, Feature Extraction and Building Machine Learning Models from Audio Data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3361]
**Submitting author:** @jsingh811 (<a href="http://orcid.org/0000-0002-5442-3004">Jyotika Singh</a>)
**Repository:** <a href="https://github.com/jsingh811/pyAudioProcessing" target ="_blank">https://github.com/jsingh811/pyAudioProcessing</a>
**Version:** v1.1.9
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c9a0d4a0b9cb2b486c1f0e7a8c224f20/status.svg)](https://joss.theoj.org/papers/c9a0d4a0b9cb2b486c1f0e7a8c224f20)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c9a0d4a0b9cb2b486c1f0e7a8c224f20"><img src="https://joss.theoj.org/papers/c9a0d4a0b9cb2b486c1f0e7a8c224f20/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c9a0d4a0b9cb2b486c1f0e7a8c224f20/status.svg)](https://joss.theoj.org/papers/c9a0d4a0b9cb2b486c1f0e7a8c224f20)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jsingh811. **Currently, there isn't an JOSS editor assigned** to your paper.

@jsingh811 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (418.4 files/s, 58627.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          10            201            381           1107
Markdown                         9            276              0            961
TeX                              1             17              0             85
YAML                             2              7              4             44
-------------------------------------------------------------------------------
SUM:                            22            501            385           2197
-------------------------------------------------------------------------------


Statistical information for the repository '21844528bb025975c2eff186' was
gathered on 2021/06/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Christian Clauss                 1             1              1            0.08
Jyotika Singh                   41          2088            399           99.92

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Christian Clauss              1          100.0          2.4                0.00
Jyotika Singh              1688           80.8          3.6               10.55
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ICASSP.2013.6639061 is OK
- 10.1007/978-81-322-3592-7_9 is OK
- 10.1109/ICGCCEE.2014.6921394 is OK
- 10.5281/zenodo.4792298 is OK
- 10.13140/RG.2.2.15872.97287 is OK
- 10.5281/ZENODO.4915746 is OK

MISSING DOIs

- 10.1371/journal.pone.0144610 may be a valid DOI for title: pyAudioAnalysis: An Open-Source Python Library for Audio Signal Analysis

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03361/joss.03361/10.21105.joss.03361.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03361/joss.03361/10.21105.joss.03361.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Note that this is a resubmission of #3334. We had asked for more thorough packaging and if possible some more functionality in the code. This is the follow up resubmission.

**Comment by kthyng** [comment]
Hi @jsingh811 and thanks for this resubmission! I'll ping the editorial board for input to follow up on the previous conversation. Thank you.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by jsingh811** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03361/joss.03361/10.21105.joss.03361.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03361/joss.03361/10.21105.joss.03361.pdf) :page_facing_up: :point_left:

**Comment by jsingh811** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03361/joss.03361/10.21105.joss.03361.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03361/joss.03361/10.21105.joss.03361.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission is not in scope for review by JOSS. This does not mean that it is not software that is useful in research, but just that JOSS does not consider it in scope for review as research software. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.  

Some of the comments on this submission include that the update from the previous submission is minor, audio format conversion is done by another package, and many changes seem to just be splitting lines of code. The inclusion of pre-trained models was a factor towards going ahead with the review, but was not viewed as a sufficient. Overall, this did not seem to be a sufficiently "significant contribution to the available open source that either enables some new research challenges to be addressed or makes addressing research challenges significantly better"

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
