### ISSUE TITLE
[PRE REVIEW]: OSCILOS_brass: an acoustic solver for brass instruments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3364]
**Submitting author:** @AlexanderMacL (<a href="http://orcid.org/0000-0002-5835-216X">Alexander MacLaren</a>)
**Repository:** <a href="https://github.com/MorgansLab/OSCILOS_brass/" target ="_blank">https://github.com/MorgansLab/OSCILOS_brass/</a>
**Version:** v1.0
**Editor:** @vissarion
**Reviewers:** @astanziola, @drewbitllama
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6b3f5b373f35401ced225474bb953221/status.svg)](https://joss.theoj.org/papers/6b3f5b373f35401ced225474bb953221)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6b3f5b373f35401ced225474bb953221"><img src="https://joss.theoj.org/papers/6b3f5b373f35401ced225474bb953221/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6b3f5b373f35401ced225474bb953221/status.svg)](https://joss.theoj.org/papers/6b3f5b373f35401ced225474bb953221)
```

**Author instructions**

Thanks for submitting your paper to JOSS @AlexanderMacL. **Currently, there isn't an JOSS editor assigned** to your paper.

@AlexanderMacL if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (312.3 files/s, 42277.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                          20            496            519           2042
Markdown                         3             11              0             46
-------------------------------------------------------------------------------
SUM:                            23            507            519           2088
-------------------------------------------------------------------------------


Statistical information for the repository '1a23ff14ee8b671e90963e9c' was
gathered on 2021/06/14.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3364 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon check references from branch Paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch Paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1121/1.4822479 is OK
- 10.1016/j.combustflame.2015.06.020 is OK
- 10.1080/00102202.2019.1583221 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch Paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch Paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03364/joss.03364/10.21105.joss.03364.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03364/joss.03364/10.21105.joss.03364.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @vissarion - I wonder if you would be able to edit this submission

**Comment by danielskatz** [comment]
@whedon invite @vissarion as editor

**Comment by whedon** [comment]
@vissarion has been invited to edit this submission.

**Comment by vissarion** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @vissarion

**Comment by vissarion** [comment]
:wave: @astanziola, @krystophny, @pharshalp would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by astanziola** [comment]
Hello! Happy to review :)

**Comment by vissarion** [comment]
@whedon add @astanziola as reviewer

**Comment by whedon** [comment]
OK, @astanziola is now a reviewer

**Comment by krystophny** [comment]
Sorry, I'm too busy right now to do another review.

**Comment by vissarion** [comment]
Hi, @dbuscombe-usgs, @sptennak, @steffilazerte, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by steffilazerte** [comment]
I don't have MATLAB, so I think that means I can't install/run the software... right?

**Comment by dbuscombe-usgs** [comment]
Sorry I won't and can't review Matlab code. Not open source, in my opinion

**Comment by vissarion** [comment]
> I don't have MATLAB, so I think that means I can't install/run the software... right?

Unfortunately, yes.

**Comment by steffilazerte** [comment]
Okay, then no review from me either, sorry!

**Comment by vissarion** [comment]
Hi @DongYang-IC, @jingxuanLI, @Chluz would any of you be willing to review this submission for JOSS?

**Comment by vissarion** [comment]
@steffilazerte @dbuscombe-usgs thanks for your responses, I understand that having a version of MATLAB installed is an obstacle towards reviewing this package.

**Comment by pharshalp** [comment]
@vissarion sorry about the delayed response. Unfortunately, I won't be able to help since I do not have access to MATLAB.

**Comment by vissarion** [comment]
> @vissarion sorry about the delayed response. Unfortunately, I won't be able to help since I do not have access to MATLAB.

No problem, thanks for the reply! Please feel free to remove `matlab` your preferred languages from [this list](https://bit.ly/joss-reviewers) if this is a permanent issue.

**Comment by vissarion** [comment]
Hi @nikunjragh, @torbenwendt, @augucarv, I think this JOSS submission is relevant to your interests. Would you like to review it?

**Comment by nikunjragh** [comment]
Hi @vissarion - Just seeing JOSS for the first time and this is a brilliant effort; I am very tied up currently but Drew Allen (@drewbitllama) could be a great fit for reviewing this.

**Comment by vissarion** [comment]
@AlexanderMacL as you realize it is hard to find a second reviewer (I have also sent several emails) could you please recommend a few names to help proceeding with this submission?

**Comment by drewbitllama** [comment]
Hi Vissarion,

I apologize, I just saw this email now—I’d be happy to review the paper if
you still need reviewers.

Cheers,
Drew

**Comment by vissarion** [comment]
@drewbitllama sure!

**Comment by vissarion** [comment]
@whedon add @drewbitllama as reviewer

**Comment by whedon** [comment]
OK, @drewbitllama is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3732.
