### ISSUE TITLE
[PRE REVIEW]: pointcloudset: Efficient analysis of large datasets of point clouds recorded over time

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3365]
**Submitting author:** @tgoelles (<a href="http://orcid.org/0000-0002-3925-6260">Thomas Goelles</a>)
**Repository:** <a href="https://github.com/virtual-vehicle/pointcloudset/" target ="_blank">https://github.com/virtual-vehicle/pointcloudset/</a>
**Version:** 0.2.2
**Editor:** @hugoledoux
**Reviewers:** @RonaldEnsing, @hechth
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f6558092a8f2c2c2d767d2c4881a2050/status.svg)](https://joss.theoj.org/papers/f6558092a8f2c2c2d767d2c4881a2050)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f6558092a8f2c2c2d767d2c4881a2050"><img src="https://joss.theoj.org/papers/f6558092a8f2c2c2d767d2c4881a2050/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f6558092a8f2c2c2d767d2c4881a2050/status.svg)](https://joss.theoj.org/papers/f6558092a8f2c2c2d767d2c4881a2050)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tgoelles. **Currently, there isn't an JOSS editor assigned** to your paper.

@tgoelles if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.36 s (230.7 files/s, 373574.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          54            902            825           2703
YAML                             6             26              9            251
Jupyter Notebook                 4              0         128911            165
reStructuredText                 8             86             76            109
Dockerfile                       1              9             27             56
JSON                             2              0              0             55
Markdown                         3             18              0             44
make                             2             11              7             31
DOS Batch                        1              8              1             26
SVG                              1              0              0             21
INI                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            83           1060         129856           3464
-------------------------------------------------------------------------------


Statistical information for the repository '527200dcb71d92862ec7172f' was
gathered on 2021/06/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Birgit Schlager                 66          1396            704           13.91
Sarah Haas                       7            56             18            0.49
Thomas Gölles                   16            95             38            0.88
tgoelles                        10           178            317            3.28
thomasgoelles                  208          7288           5002           81.41
tobiashammer                     1             2              2            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Birgit Schlager             806           57.7          1.7               12.78
tgoelles                     89           50.0          2.0                8.99
thomasgoelles              3533           48.5          3.2                3.28
tobiashammer                  2          100.0          0.7                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3365 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.1364/OPN.29.1.000026 is OK
- 10.1109/MCE.2016.2556878 is OK
- 10.23919/VLSIC.2019.8777993 is OK

MISSING DOIs

- 10.25080/majora-7b98e3ed-013 may be a valid DOI for title:  Dask: Parallel Computation with Blocked algorithms and Task Scheduling 

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03365/joss.03365/10.21105.joss.03365.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03365/joss.03365/10.21105.joss.03365.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@tgoelles - thanks for your submission.
Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

In addition, you could work on the possibly missing DOI that whedon suggests, but note that it may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by tgoelles** [comment]
@whedon check references

**Comment by tgoelles** [comment]
@whedon check references

**Comment by arfon** [comment]
@whedon invite @hugoledoux as editor

:wave: @hugoledoux – would you be willing to edit this submission for us?

**Comment by whedon** [comment]
@hugoledoux has been invited to edit this submission.

**Comment by hugoledoux** [comment]
@whedon assign @hugoledoux as editor

**Comment by whedon** [comment]
OK, the editor is @hugoledoux

**Comment by hugoledoux** [comment]
@hechth would you be willing to review this? You seem a good fit.

**Comment by hugoledoux** [comment]
@whedon add @RonaldEnsing as reviewer

**Comment by whedon** [comment]
OK, @RonaldEnsing is now a reviewer

**Comment by hugoledoux** [comment]
@whedon add @hechth as reviewer

**Comment by whedon** [comment]
OK, @hechth is now a reviewer

**Comment by hugoledoux** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3471.
