### ISSUE TITLE
[PRE REVIEW]: OGRe: An Object-Oriented General Relativity Package for Mathematica

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3366]
**Submitting author:** @bshoshany (<a href="http://orcid.org/0000-0003-2222-127X">Barak Shoshany</a>)
**Repository:** <a href="https://github.com/bshoshany/OGRe" target ="_blank">https://github.com/bshoshany/OGRe</a>
**Version:** v1.5
**Editor:** @VivianePons
**Reviewers:** @kostunin, @amelialdrew
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/068573253d55b405eb934bc915e72134/status.svg)](https://joss.theoj.org/papers/068573253d55b405eb934bc915e72134)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/068573253d55b405eb934bc915e72134"><img src="https://joss.theoj.org/papers/068573253d55b405eb934bc915e72134/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/068573253d55b405eb934bc915e72134/status.svg)](https://joss.theoj.org/papers/068573253d55b405eb934bc915e72134)
```

**Author instructions**

Thanks for submitting your paper to JOSS @bshoshany. **Currently, there isn't an JOSS editor assigned** to your paper.

@bshoshany if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (104.7 files/s, 93872.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Mathematica                      1            155            487           1852
Markdown                         2             34              0            162
-------------------------------------------------------------------------------
SUM:                             3            189            487           2014
-------------------------------------------------------------------------------


Statistical information for the repository 'c43fa7ff9603233426ad4461' was
gathered on 2021/06/14.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3366 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by bshoshany** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03366/joss.03366/10.21105.joss.03366.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03366/joss.03366/10.21105.joss.03366.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @VivianePons - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @VivianePons as editor

**Comment by whedon** [comment]
@VivianePons has been invited to edit this submission.

**Comment by bshoshany** [comment]
I went over the list of people who have already agreed to review for JOSS. The following potential reviewers listed Mathematica as one of their programming languages and wrote astronomy as one of their domains (so they should have knowledge of general relativity):
1. danehkar
2. kostunin
3. bradkav
4. eschnett (note: I have worked with him in the past, so that may be a conflict of interest)

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by kostunin** [comment]
> I went over the list of people who have already agreed to review for JOSS. The following potential reviewers listed Mathematica as one of their programming languages and wrote astronomy as one of their domains (so they should have knowledge of general relativity):
> 
>     1. danehkar
> 
>     2. kostunin
> 
>     3. bradkav
> 
>     4. eschnett (note: I have worked with him in the past, so that may be a conflict of interest)

Thanks for inviting me as referee of this paper. I think my knowledge is not complete enough to cover the full content of the paper, however I will try to read a draft and give a feedback on parts which I have expertise in!

**Comment by VivianePons** [comment]
@whedon assign @kostunin as reviewer

**Comment by whedon** [comment]
OK, @kostunin is now a reviewer

**Comment by VivianePons** [comment]
Thank you @kostunin . Once we launch the review, you will get a checklist to help you go through. If ever there is an item where you don't feel competent, you just let me know and we'll decide how to handle it.

**Comment by VivianePons** [comment]
@whedon add @amelialdrew as reviewer

**Comment by whedon** [comment]
OK, @amelialdrew is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3416.
