### ISSUE TITLE
[PRE REVIEW]: Survival: Survival Analysis in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3368]
**Submitting author:** @derrynknife (<a href="http://orcid.org/0000-0002-6636-6318">Derryn Knife</a>)
**Repository:** <a href="https://github.com/derrynknife/SurPyval" target ="_blank">https://github.com/derrynknife/SurPyval</a>
**Version:** 0.4.0
**Editor:** @dfm
**Reviewers:** @CamDavidsonPilon, @MatthewReid854
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5a41c8e82b8327b9a3575f9c41f73ab9/status.svg)](https://joss.theoj.org/papers/5a41c8e82b8327b9a3575f9c41f73ab9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5a41c8e82b8327b9a3575f9c41f73ab9"><img src="https://joss.theoj.org/papers/5a41c8e82b8327b9a3575f9c41f73ab9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5a41c8e82b8327b9a3575f9c41f73ab9/status.svg)](https://joss.theoj.org/papers/5a41c8e82b8327b9a3575f9c41f73ab9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @derrynknife. **Currently, there isn't an JOSS editor assigned** to your paper.

@derrynknife if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (1033.5 files/s, 113977.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          45            974            736           3818
reStructuredText                17            564            585            353
Markdown                         2             54              0            127
TeX                              1             10              0            113
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            67           1614           1329           4446
-------------------------------------------------------------------------------


Statistical information for the repository 'f7924326e1c4c134dd90e2c0' was
gathered on 2021/06/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Derryn Knife                   201         39433          33910           99.73
Knife                            3           103             98            0.27

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Derryn Knife               5440           13.8          8.8                7.90
Knife                        88           85.4          4.5               11.36
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03368/joss.03368/10.21105.joss.03368.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03368/joss.03368/10.21105.joss.03368.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1111/j.1541-0420.2006.00589_9.x may be a valid DOI for title: Survival analysis: techniques for censored and truncated data
- 10.1111/j.2517-6161.1976.tb01597.x may be a valid DOI for title: The empirical distribution function with arbitrarily grouped, censored and truncated data
- 10.1080/00224065.1969.11980344 may be a valid DOI for title: Hazard plotting for incomplete failure data
- 10.1214/aos/1176344247 may be a valid DOI for title: Nonparametric inference for a family of counting processes
- 10.21105/joss.01317 may be a valid DOI for title: lifelines: survival analysis in Python
- 10.1115/1.4010337 may be a valid DOI for title: A statistical distribution function of wide applicability

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@derrynknife - thanks for your submission.

Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋  @dfm - is this a submission that you could edit?

**Comment by danielskatz** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by derrynknife** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1111/j.1541-0420.2006.00589_9.x may be a valid DOI for title: Survival analysis: techniques for censored and truncated data
- 10.1111/j.2517-6161.1976.tb01597.x may be a valid DOI for title: The empirical distribution function with arbitrarily grouped, censored and truncated data
- 10.1080/00224065.1969.11980344 may be a valid DOI for title: Hazard plotting for incomplete failure data
- 10.1214/aos/1176344247 may be a valid DOI for title: Nonparametric inference for a family of counting processes
- 10.21105/joss.01317 may be a valid DOI for title: lifelines: survival analysis in Python
- 10.1115/1.4010337 may be a valid DOI for title: A statistical distribution function of wide applicability

INVALID DOIs

- None
```

**Comment by derrynknife** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/b97377 is OK
- 10.1111/j.2517-6161.1976.tb01597.x is OK
- 10.1080/00224065.1969.11980344 is OK
- 10.1214/aos/1176344247 is OK
- 10.21105/joss.01317 is OK
- 10.1115/1.4010337 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by derrynknife** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03368/joss.03368/10.21105.joss.03368.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03368/joss.03368/10.21105.joss.03368.pdf) :page_facing_up: :point_left:

**Comment by derrynknife** [comment]
Thanks @danielskatz, I've updated the references and pdf as Whedon suggested.

Totally understand that editing will be harder given the state of affairs in the world!

@dfm looking forward to your comments as well.

Thanks team!

**Comment by dfm** [comment]
@whedon assign me as editor

I'm on holiday with limited internet so I'll be back online with more feedback/searching for reviewers next week. Thanks for your patience!

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@whedon assign @CamDavidsonPilon as reviewer

Thanks Cameron for agreeing to act as a reviewer! As soon as I have a second reviewer lined up, we'll get things started in a new issue.

**Comment by whedon** [comment]
OK, @CamDavidsonPilon is now a reviewer

**Comment by dfm** [comment]
@whedon add @MatthewReid854 as reviewer

@MatthewReid854 has agreed to be our second reviewer - thanks Matt!!

I'll get the review started in a new issue thread and you'll see more info over there, but don't hesitate to ask if you have any questions.

**Comment by whedon** [comment]
OK, @MatthewReid854 is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3484.
