### ISSUE TITLE
[PRE REVIEW]: Building, Importing, and Exporting GEXF Graph Files with rgexf

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3369]
**Submitting author:** @gvegayon (<a href="http://orcid.org/0000-0002-3171-0844">George Vega Yon</a>)
**Repository:** <a href="https://github.com/gvegayon/rgexf/" target ="_blank">https://github.com/gvegayon/rgexf/</a>
**Version:** 0.16.1
**Editor:** @fabian-s
**Reviewers:** @jonjoncardoso, @corneliusfritz
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/369e7a58e1da094aee98c874c26e5f68/status.svg)](https://joss.theoj.org/papers/369e7a58e1da094aee98c874c26e5f68)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/369e7a58e1da094aee98c874c26e5f68"><img src="https://joss.theoj.org/papers/369e7a58e1da094aee98c874c26e5f68/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/369e7a58e1da094aee98c874c26e5f68/status.svg)](https://joss.theoj.org/papers/369e7a58e1da094aee98c874c26e5f68)
```

**Author instructions**

Thanks for submitting your paper to JOSS @gvegayon. **Currently, there isn't an JOSS editor assigned** to your paper.

@gvegayon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (903.8 files/s, 154678.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              2              5              1           1896
R                               28            756           1189           1853
JavaScript                       5             90             96           1244
XML                              2              0              0            903
Markdown                         6            200              0            653
CSS                              2             71             15            198
Python                           1             21              1            131
TeX                              1             13              0            131
YAML                             5             35             14             89
Rmd                              2             46             90             65
HTML                             1              0              0             62
make                             2             12              0             34
Dockerfile                       1              4              0              8
-------------------------------------------------------------------------------
SUM:                            58           1253           1406           7267
-------------------------------------------------------------------------------


Statistical information for the repository 'fe995e8b54f95f7c478db87b' was
gathered on 2021/06/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
George G. Vega Yon               6          1802            535           86.85
George Vega Yon                  3           106             19            4.65
Joshua                           1           229              0            8.51

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
George G Vega Yon          1583          100.0         27.1                6.19
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00814 is OK
- 10.1093/femsec/fiaa255 is OK
- 10.18637/jss.v093.i11 is OK
- 10.1038/nature23902 is OK
- 10.1038/nature25474 is OK
- 10.1038/s41598-018-24733-0 is OK
- 10.1109/WI.2016.0087 is OK

MISSING DOIs

- 10.1093/bioinformatics/btq675 may be a valid DOI for title: Cytoscape 2.8: new features for data integration and network visualization

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03369/joss.03369/10.21105.joss.03369.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03369/joss.03369/10.21105.joss.03369.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@gvegayon - please add a section entitle "Statement of Need" to your paper, and please explain what types of research (in some example fields) this software supports/enables.

**Comment by danielskatz** [comment]
In addition, you could work on the possibly missing DOI that whedon suggests, but note that this may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @will-rowe - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @will-rowe as editor

**Comment by whedon** [comment]
@will-rowe has been invited to edit this submission.

**Comment by gvegayon** [comment]
👋🏼 I think anyone of the following would be good reviewers: jonjoncardoso, vc1492a, akbaritabar, and justinchuntingho

**Comment by gvegayon** [comment]
@danielskatz Just pushed a new version with the statement of need and the fixed DOI. Thanks!

**Comment by danielskatz** [comment]
Thanks - I'll run the commands I mentioned now, though you could also do this if any further changes are needed

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btq675 is OK
- 10.21105/joss.00814 is OK
- 10.1093/femsec/fiaa255 is OK
- 10.18637/jss.v093.i11 is OK
- 10.1038/nature23902 is OK
- 10.1038/nature25474 is OK
- 10.1038/s41598-018-24733-0 is OK
- 10.1109/WI.2016.0087 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03369/joss.03369/10.21105.joss.03369.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03369/joss.03369/10.21105.joss.03369.pdf) :page_facing_up: :point_left:

**Comment by gvegayon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03369/joss.03369/10.21105.joss.03369.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03369/joss.03369/10.21105.joss.03369.pdf) :page_facing_up: :point_left:

**Comment by will-rowe** [comment]
Sorry for the slow reply @danielskatz - I'm moving house and am due to go on annual leave for 2 weeks. Could we find another editor for this one?

**Comment by danielskatz** [comment]
We can try - worst case it will still be looking for an editor in 2 weeks, so keep it in mind when you are free again :)

**Comment by danielskatz** [comment]
I'll put it on the waiting list for now, since we are short of editors currently (but are working to resolve this issue)

**Comment by arfon** [comment]
@whedon invite @fabian-s as editor

:wave: @fabian-s – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@fabian-s has been invited to edit this submission.

**Comment by fabian-s** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @fabian-s

**Comment by fabian-s** [comment]
@jonjoncardoso @vc1492a @jankatins would any of you be willing to review this submission for JOSS? 
 
 We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html
 
Thank you for considering this!

**Comment by vc1492a** [comment]
@fabian-s thanks for reaching out! I am afraid my R language experience these days is pretty limited (although it used to be much better), and think another reviewer may be better positioned to do a thorough review on this one. Good luck!

**Comment by jonjoncardoso** [comment]
Hi @fabian-s, yes I'm happy to review this submission. The only thing is I will only be able to properly review it from Wednesday next week onwards if that is okay. Not sure if there is a deadline here for reviewers.

**Comment by fabian-s** [comment]
@vc1492a sure, thanks for the quick response.

@jonjoncardoso, thanks for taking this on!
starting next week is perfectly fine, first we need to find more reviewers anyway.

**Comment by fabian-s** [comment]
@whedon add @jonjoncardoso as reviewer

**Comment by whedon** [comment]
OK, @jonjoncardoso is now a reviewer

**Comment by fabian-s** [comment]
@whedon remind @fabian-s in 2 days

**Comment by whedon** [comment]
Sorry, I can't set reminders on PRE-REVIEW issues.

**Comment by fabian-s** [comment]
@briatte would you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Thank you for considering this!

**Comment by fabian-s** [comment]
@whedon add @corneliusfritz as reviewer

**Comment by whedon** [comment]
OK, @corneliusfritz is now a reviewer

**Comment by fabian-s** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3456.
