### ISSUE TITLE
[PRE REVIEW]: Pipengine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#337]
**Submitting author:** @fstrozzi (<a href="http://orcid.org/0000-0002-6845-6982">Francesco Strozzi</a>)
**Repository:** <a href="https://github.com/fstrozzi/bioruby-pipengine" target ="_blank">https://github.com/fstrozzi/bioruby-pipengine</a>
**Version:** 0.9.3
**Editor:** @biorelated
**Reviewer:** @yannickwurm 

**Author instructions**

Thanks for submitting your paper to JOSS @fstrozzi. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@fstrozzi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @pjotrp - the submitting author suggested you as the editor.

**Comment by pjotrp** [comment]
It could be perceived I have a conflict of interest here. @biorelated can you be the editor of this Ruby submission?

**Comment by biorelated** [comment]
@pjotrp @arfon no problem.

**Comment by biorelated** [comment]
@krother, @amoeba would you be willing and happy to review this work?

**Comment by biorelated** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by biorelated** [comment]
@whedon assign @biorelated as editor

**Comment by whedon** [comment]
OK, the editor is @biorelated

**Comment by pjotrp** [comment]
Thanks @biorelated. Would be good to get one of the Ruby crowd. How about asking one of the users https://github.com/fstrozzi/bioruby-pipengine/stargazers?

**Comment by amoeba** [comment]
Hey @biorelated I may not be able to get to this for a few weeks due to travel. If another reviewer can be be found that would be preferable but I will make a reminder to check back here when my schedule unsticks itself.

**Comment by biorelated** [comment]
Thank you @amoeba. noted.

**Comment by biorelated** [comment]
Dear Yannick (@yannickwurm), 
Would you be willing to review the work by @fstrozzi (Francesco Strozzi) on PipEngine. Many thanks and looking forward to hearing from you.

**Comment by yannickwurm** [comment]
Apologies for delay in replying @biorelated . I'm happy to do the review.

**Comment by biorelated** [comment]
@whedon assign @yannickwurm  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @yannickwurm

**Comment by biorelated** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by biorelated** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/341. Feel free to close this issue now!
