### ISSUE TITLE
[PRE REVIEW]: see: An R Package for Visualizing Statistical Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3372]
**Submitting author:** @strengejacke (<a href="http://orcid.org/0000-0002-8895-3206">Daniel Lüdecke</a>)
**Repository:** <a href="https://github.com/easystats/see/" target ="_blank">https://github.com/easystats/see/</a>
**Version:** 0.6.5
**Editor:** @fboehm
**Reviewers:** @MatthewSmith430, @jakobbossek
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4dd01f36f46a378d882d29baa6702c90/status.svg)](https://joss.theoj.org/papers/4dd01f36f46a378d882d29baa6702c90)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4dd01f36f46a378d882d29baa6702c90"><img src="https://joss.theoj.org/papers/4dd01f36f46a378d882d29baa6702c90/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4dd01f36f46a378d882d29baa6702c90/status.svg)](https://joss.theoj.org/papers/4dd01f36f46a378d882d29baa6702c90)
```

**Author instructions**

Thanks for submitting your paper to JOSS @strengejacke. **Currently, there isn't an JOSS editor assigned** to your paper.

@strengejacke if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (1413.0 files/s, 200783.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                              100           1318           2127           6157
SVG                             25              0              0           4521
XML                              1              0            129           1787
Rmd                             10            778            936           1196
Markdown                         5            453              0            898
YAML                             4             42              4            261
TeX                              1             15              0            124
-------------------------------------------------------------------------------
SUM:                           146           2606           3196          14944
-------------------------------------------------------------------------------


Statistical information for the repository 'b9dfb94545163888f7c6575f' was
gathered on 2021/06/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel                           6           248            448           77.68
Dominique Makowski               1           200              0           22.32

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3372 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by IndrajeetPatil** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03372/joss.03372/10.21105.joss.03372.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03372/joss.03372/10.21105.joss.03372.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@strengejacke - thanks for your submission.
Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

**Comment by fboehm** [comment]
@danielskatz - I'd be happy to serve as editor for this submission.

**Comment by danielskatz** [comment]
Thanks @fboehm - can you go ahead and take it then, via the command ```@whedon assign me as editor```, and then remove the waitlisted tag?  (You can always do this with any paper that's not undergoing scope review (with the `query-scope` tag)

**Comment by fboehm** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by strengejacke** [comment]
May I suggest some reviewers (no specific order):

- JohnCoene
- trinker
- garretrc
- MatthewSmith430
- cdcrabtree
- jakobbossek
- tweed1e

**Comment by fboehm** [comment]
:wave: @trinker & @JohnCoene & @garretrc & @MatthewSmith430, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html
Thank you for considering this!

**Comment by fboehm** [comment]
Thank you, @strengejacke, for the reviewer suggestions! Once we find two reviewers, the official review can begin.

**Comment by MatthewSmith430** [comment]
@fboehm Happy to review this. What would be the timeline for completing the review?

**Comment by fboehm** [comment]
Thank you, @MatthewSmith430 ! We'd like to complete the review in the next month or so. Once I find a second reviewer, we can begin the review.

**Comment by fboehm** [comment]
@whedon assign @MatthewSmith430 as reviewer

**Comment by whedon** [comment]
OK, @MatthewSmith430 is now a reviewer

**Comment by fboehm** [comment]
@cdcrabtree, @jakobbossek, @tweed1e - would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html
Thank you for considering this!

**Comment by jakobbossek** [comment]
@fboehm Happy to support with the review 👍

**Comment by fboehm** [comment]
Thank you, @jakobbossek ! I'll get the review started.

**Comment by fboehm** [comment]
@whedon add @jakobbossek as reviewer

**Comment by whedon** [comment]
OK, @jakobbossek is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3393.
