### ISSUE TITLE
[PRE REVIEW]: Datum: Creating and loading TFRecord datasets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3373]
**Submitting author:** @n3011 (<a href="http://orcid.org/0000-0002-0059-2822">Mrinal Haloi</a>)
**Repository:** <a href="https://github.com/openAGI/datum" target ="_blank">https://github.com/openAGI/datum</a>
**Version:** 1.1.0
**Editor:** @jmschrei
**Reviewers:** @pmeier, @younglululu
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5893594a099431c37c47276d6cb09119/status.svg)](https://joss.theoj.org/papers/5893594a099431c37c47276d6cb09119)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5893594a099431c37c47276d6cb09119"><img src="https://joss.theoj.org/papers/5893594a099431c37c47276d6cb09119/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5893594a099431c37c47276d6cb09119/status.svg)](https://joss.theoj.org/papers/5893594a099431c37c47276d6cb09119)
```

**Author instructions**

Thanks for submitting your paper to JOSS @n3011. **Currently, there isn't an JOSS editor assigned** to your paper.

@n3011 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (1064.4 files/s, 95535.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          52            702           1554           2714
Bourne Shell                     6            109             75            394
Markdown                         6            140              0            381
XML                              2              0              0            126
YAML                             4             12              0             76
-------------------------------------------------------------------------------
SUM:                            70            963           1629           3691
-------------------------------------------------------------------------------


Statistical information for the repository 'c3afc3b8a798c6a96dc0286e' was
gathered on 2021/06/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ishant Mrinal Haloi             13          5102            132          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ishant Mrinal Haloi        4970           97.4          0.2               18.91
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3373 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03373/joss.03373/10.21105.joss.03373.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03373/joss.03373/10.21105.joss.03373.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@n3011 - thanks for your submission.
Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

**Comment by kyleniemeyer** [comment]
Hi @jmschrei, apologies for repeated requests, but could you also edit this one for us?

**Comment by kyleniemeyer** [comment]
@whedon invite @jmschrei as editor

**Comment by whedon** [comment]
@jmschrei has been invited to edit this submission.

**Comment by jmschrei** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jmschrei

**Comment by jmschrei** [comment]
Hi @pmeier and @saran-nns, would either of you be able to serve as a reviewer for this submission? Thanks!

**Comment by pmeier** [comment]
@jmschrei In general, yes. I don't have any experience with `tensorflow` or the `tfrecords` data / file format though. Any review that I could provide would be limited to how the API of `datum` wraps these two. Maybe @n3011 can give some context if that would be enough.

**Comment by jmschrei** [comment]
Personally, I think that it would be valuable to get feedback from someone outside the immediate use-case (i.e., tensorflow/tfrecords) as long as it's from someone in the general area (deep learning in Python). But yes, @n3011 do you think that @pmeier would have sufficient expertise to review this?

**Comment by pmeier** [comment]
> do you think that @pmeier would have sufficient expertise to review this?

To give a little more context, I am the maintainer of [PyTorch's vision datasets](https://github.com/pytorch/vision). Thus, if no specific knowledge about `tensorflow` / `tfrecords` is required, I'm confident I can provide good feedback.

**Comment by n3011** [comment]
@jmschrei  This project is developed specifically for TensorFlow developers. A reviewer with experience in Tensorflow would have been nice.  It solves some teething issues related to creating and loading tfrecords files. 
@pmeier Just to give some context, Tensorflow uses the tfrecord format to store dataset samples in binary protocol buffer format, which reduces read overheads when dealing with thousands of files for large datasets.  But creating and loading tfrecord files involve writing a lot of code. `Datum` is developed to minimize the efforts required to create and load TFRecord dataset. Also, it is tightly integrated with `tf.data` API, which makes it easier to deal with large datasets for distributed training. 

Overall, I also agree that a deep learning developer with a slight understanding of Tensorflow can also review this.

**Comment by jmschrei** [comment]
I think that @pmeier would be a good reviewer, but that we should also get someone with experience in TensorFlow as well. @n3011 do you have any recommendations on people outside this project that might provide good feedback?

**Comment by jmschrei** [comment]
@whedon add @pmeier as reviewer

**Comment by whedon** [comment]
OK, @pmeier is now a reviewer

**Comment by jmschrei** [comment]
@whedon add @younglululu as reviewer

**Comment by whedon** [comment]
OK, @younglululu is now a reviewer

**Comment by jmschrei** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3446.
