### ISSUE TITLE
[PRE REVIEW]: Cutepeaks: A modern viewer for Sanger trace file

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3378]
**Submitting author:** @dridk (<a href="http://orcid.org/0000-0002-4563-7537">sacha schutz</a>)
**Repository:** <a href="https://github.com/labsquare/CutePeaks" target ="_blank">https://github.com/labsquare/CutePeaks</a>
**Version:** 0.2.3
**Editor:** @lpantano
**Reviewers:** @tobiasrausch, @wdecoster
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fe7efe76ee476b41dcd997fdbe8e19ec/status.svg)](https://joss.theoj.org/papers/fe7efe76ee476b41dcd997fdbe8e19ec)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fe7efe76ee476b41dcd997fdbe8e19ec"><img src="https://joss.theoj.org/papers/fe7efe76ee476b41dcd997fdbe8e19ec/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fe7efe76ee476b41dcd997fdbe8e19ec/status.svg)](https://joss.theoj.org/papers/fe7efe76ee476b41dcd997fdbe8e19ec)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dridk. **Currently, there isn't an JOSS editor assigned** to your paper.

@dridk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (1537.7 files/s, 160423.1 lines/s)
-----------------------------------------------------------------------------------
Language                         files          blank        comment           code
-----------------------------------------------------------------------------------
C++                                 24            819            234           2636
C/C++ Header                        24            316            243           1179
Qt Linguist                          1              0              0            184
SVG                                  1              1              1            121
Markdown                             2             38              0             85
YAML                                 2              7             37             43
TeX                                  1              1              0             26
ProGuard                             1             20              5             24
Qt Project                           1             11              1             18
Windows Resource File                1              0              0              1
-----------------------------------------------------------------------------------
SUM:                                58           1213            521           4317
-----------------------------------------------------------------------------------


Statistical information for the repository '3b8aab436439e6df51acb48e' was
gathered on 2021/06/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Anne-Sophie Denommé-             5            39             35            0.06
Charles                          1           391              0            0.30
Olivier Gueudelot                1            78              5            0.06
dridk                          107         67049           3462           53.27
sacha schutz                    40          1252          60016           46.29
yschutz                          2            21             17            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Anne-Sophie Denommé-         23           59.0         47.0                0.00
Charles                     391          100.0          0.0                0.00
Olivier Gueudelot            37           47.4         49.5                0.00
dridk                      4961            7.4         44.3                9.94
yschutz                      15           71.4         41.4               40.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1186/s12864-020-6635-8 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03378/joss.03378/10.21105.joss.03378.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03378/joss.03378/10.21105.joss.03378.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@dridk - thanks for your submission.
Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

**Comment by dridk** [comment]
Potential reviewer:

##  in genetic : 
- Adrianzo
- afrubin
- martinmodrak
- tomsing1
- wdecoster
- standage

## Graphics user interface with Qt
- RDastgh1
- otre99
- 1313e

**Comment by lpantano** [comment]
@whedon assign @lpantano as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by danielskatz** [comment]
Thanks @lpantano - just FYI, for submissions with a `waitlisted` tag, you should also remove that tag when you take on a submission.

**Comment by lpantano** [comment]
@otre99, would you like to review this tool? thanks!

**Comment by lpantano** [comment]
@dridk, could you add or point in the readme to the docs for a quick start steps by step. I see that you have examples in the repository, and I found that reviewer is faster if you add documentation to show how to load an exmaple, and the few features that you can do with your tool. Thanks!

**Comment by dridk** [comment]
@lpantano Done ! https://github.com/labsquare/CutePeaks/commit/f09e4fd464dce80883e200ecda6847e267f3fca4. 
By the way, you have a binary available for each platform. It should be easy to run it :https://labsquare.github.io/CutePeaks/

**Comment by otre99** [comment]
I'd love to help you, but I can't at the moment. I'm sorry about that

**Comment by lpantano** [comment]
@RDastgh1, would you like to review this tool for JOSS?

**Comment by lpantano** [comment]
@tobiasrausch, would you like to review this tool for JOSS? Read more about the criteria here:  (https://joss.readthedocs.io/en/latest/review_criteria.html) Thanks!

**Comment by tobiasrausch** [comment]
Hi @lpantano, 
Thanks, I can help reviewing this paper.
Best, Tobias

**Comment by lpantano** [comment]
@whedon assign @tobiasrausch as reviewer

**Comment by whedon** [comment]
OK, @tobiasrausch is now a reviewer

**Comment by lpantano** [comment]
Thank you @tobiasrausch!, bear with me meanwhile I find the second reviewer.

**Comment by lpantano** [comment]
@whedon add @wdecoster as reviewer

**Comment by whedon** [comment]
OK, @wdecoster is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3457.
