### ISSUE TITLE
[PRE REVIEW]: pollucheck v1.0: A package to explore open-source air pollution data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3381]
**Submitting author:** @adithirgis (<a href="http://orcid.org/0000-0002-1764-1379">Adithi Upadhya</a>)
**Repository:** <a href="https://github.com/adithirgis/pollucheck" target ="_blank">https://github.com/adithirgis/pollucheck</a>
**Version:** 1.0.0
**Editor:** @ajstewartlang
**Reviewers:** @nmstreethran, @ibarraespinosa
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6844e6db054970a02c1ddbcf9e9f0cc2/status.svg)](https://joss.theoj.org/papers/6844e6db054970a02c1ddbcf9e9f0cc2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6844e6db054970a02c1ddbcf9e9f0cc2"><img src="https://joss.theoj.org/papers/6844e6db054970a02c1ddbcf9e9f0cc2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6844e6db054970a02c1ddbcf9e9f0cc2/status.svg)](https://joss.theoj.org/papers/6844e6db054970a02c1ddbcf9e9f0cc2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @adithirugis. **Currently, there isn't an JOSS editor assigned** to your paper.

@adithirugis if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.25 s (111.4 files/s, 385191.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                            13            211              0          93166
R                                7             49             58           2251
Markdown                         6            268              0            590
TeX                              1              6              0             53
Rmd                              1             64            127              1
-------------------------------------------------------------------------------
SUM:                            28            598            185          96061
-------------------------------------------------------------------------------


Statistical information for the repository 'ee500a9f67f58750d4004f0a' was
gathered on 2021/06/18.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.envsoft.2011.09.008 is OK
- 10.21105/joss.00333 is OK

MISSING DOIs

- 10.1093/cvr/cvaa092 may be a valid DOI for title: Air pollution health impacts: the knowns and unknowns for reliable global burden calculations
- 10.21105/joss.02250 may be a valid DOI for title: mmaqshiny v1. 0: R-Shiny package to explore Air-Quality Mobile-Monitoring data

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03381/joss.03381/10.21105.joss.03381.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03381/joss.03381/10.21105.joss.03381.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@adithirugis - thanks for your submission.
Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by adithirgis** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.envsoft.2011.09.008 is OK
- 10.21105/joss.00333 is OK

MISSING DOIs

- 10.1093/cvr/cvaa092 may be a valid DOI for title: Air pollution health impacts: the knowns and unknowns for reliable global burden calculations
- 10.21105/joss.02250 may be a valid DOI for title: mmaqshiny v1. 0: R-Shiny package to explore Air-Quality Mobile-Monitoring data

INVALID DOIs

- None
```

**Comment by adithirgis** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.envsoft.2011.09.008 is OK
- 10.21105/joss.00333 is OK

MISSING DOIs

- 10.1093/cvr/cvaa092 may be a valid DOI for title: Air pollution health impacts: the knowns and unknowns for reliable global burden calculations
- 10.21105/joss.02250 may be a valid DOI for title: mmaqshiny v1. 0: R-Shiny package to explore Air-Quality Mobile-Monitoring data

INVALID DOIs

- None
```

**Comment by adithirgis** [comment]
> @adithirugis - thanks for your submission.
> Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.
> 
> In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

Hi @danielskatz, 

Thank you, we will wait for the review to start.
 Just to confirm, I added missing doi's in the paper.bib file I still get missing doi's when I try this command `@whedon check references`. Anything I am missing?

**Comment by adithirgis** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/cvr/cvaa092 is OK
- 10.1016/j.envsoft.2011.09.008 is OK
- 10.21105/joss.00333 is OK
- 10.21105/joss.02250 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by adithirgis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03381/joss.03381/10.21105.joss.03381.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03381/joss.03381/10.21105.joss.03381.pdf) :page_facing_up: :point_left:

**Comment by adithirgis** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/cvr/cvaa092 is OK
- 10.18637/jss.v027.i03 is OK
- 10.1016/j.envsoft.2011.09.008 is OK
- 10.21105/joss.00333 is OK
- 10.21105/joss.02250 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by adithirgis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03381/joss.03381/10.21105.joss.03381.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03381/joss.03381/10.21105.joss.03381.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @ajstewartlang as editor

:wave: @ajstewartlang - would you be willing to take on one more submission for us? No worries if you'd rather not at this stage!

**Comment by whedon** [comment]
@ajstewartlang has been invited to edit this submission.

**Comment by ajstewartlang** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @ajstewartlang

**Comment by ajstewartlang** [comment]
@whedon assign @nmstreethran as reviewer

**Comment by whedon** [comment]
OK, @nmstreethran is now a reviewer

**Comment by ajstewartlang** [comment]
@whedon add @ibarraespinosa as reviewer

**Comment by whedon** [comment]
OK, @ibarraespinosa is now a reviewer

**Comment by ajstewartlang** [comment]
Many thanks @nmstreethran and @ibarraespinosa for your speedy responses and agreeing to review this submission - it's very much appreciated. I'll open the review issue now...

**Comment by ajstewartlang** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3435.
