### ISSUE TITLE
[PRE REVIEW]: Epimargin: A Toolkit for Epidemiological Estimation, Prediction, and Policy Evaluation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3382]
**Submitting author:** @satejsoman (<a href="http://orcid.org/0000-0001-8450-7025">Satej Soman</a>)
**Repository:** <a href="https://github.com/COVID-IWG/epimargin" target ="_blank">https://github.com/COVID-IWG/epimargin</a>
**Version:** v0.5.2
**Editor:** @Nikoleta-v3
**Reviewers:** @wxwx1993, @dilawar
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3353609dae03b32322ea1160826f2ad8/status.svg)](https://joss.theoj.org/papers/3353609dae03b32322ea1160826f2ad8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3353609dae03b32322ea1160826f2ad8"><img src="https://joss.theoj.org/papers/3353609dae03b32322ea1160826f2ad8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3353609dae03b32322ea1160826f2ad8/status.svg)](https://joss.theoj.org/papers/3353609dae03b32322ea1160826f2ad8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @satejsoman. **Currently, there isn't an JOSS editor assigned** to your paper.

@satejsoman if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (774.7 files/s, 103835.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         119           2485           1505          11985
SVG                              6              0              5           1304
Markdown                         6             87              0            274
R                                1             10             11             77
TeX                              1              8              0             75
-------------------------------------------------------------------------------
SUM:                           133           2590           1521          13715
-------------------------------------------------------------------------------


Statistical information for the repository 'b775097e32b38e1ae80a422f' was
gathered on 2021/06/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Caitlin Loftus                  12           517            125            1.19
Nicholas Marchio                 7           533            321            1.59
Steven Buschbach                 2           761             32            1.47
manasip5                         1            23              0            0.04
satej soman                    187         33042          18522           95.71

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Caitlin Loftus              292           56.5         11.9                4.79
Steven Buschbach            724           95.1         10.7               13.40
satej soman               14959           45.3          5.1                9.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1101/2020.09.08.20190629 may be a valid DOI for title: Model-informed COVID-19 vaccine prioritization strategies by age and serostatus
- 10.2139/ssrn.3748704 may be a valid DOI for title: Systems Architecture for Real Time Epidemiological Prediction and Control
- 10.3386/w27532 may be a valid DOI for title: Adaptive control of COVID-19 outbreaks in india: Local, gradual, and trigger-based exit paths from lockdown

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03382/joss.03382/10.21105.joss.03382.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03382/joss.03382/10.21105.joss.03382.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@satejsoman - thanks for your submission.
Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.


In the meantime, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by satejsoman** [comment]
@danielskatz thanks for letting me know! I'll add the missing DOIs shortly.

**Comment by satejsoman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2020.09.08.20190629 is OK
- 10.2139/ssrn.3748704 is OK
- 10.3386/w27532 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by satejsoman** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03382/joss.03382/10.21105.joss.03382.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03382/joss.03382/10.21105.joss.03382.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @Nikoleta-v3 as editor

:wave: @Nikoleta-v3 – I realise this is somewhat outside your area of specialism but would you be willing to edit this for us?

**Comment by whedon** [comment]
@Nikoleta-v3 has been invited to edit this submission.

**Comment by Nikoleta-v3** [comment]
@arfon Yes 👍🏻 😄

**Comment by Nikoleta-v3** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Nikoleta-v3

**Comment by Nikoleta-v3** [comment]
@satejsoman  thank you again for your submission with JOSS, if you have not already done so, could you take a look through https://bit.ly/joss-reviewers to suggest some potential reviewers 😄

**Comment by satejsoman** [comment]
hi @Nikoleta-v3! here are some potential reviewers, based on language + expertise:
- edrictam
- dilawar
- ayush9pandey
- wxwx1993
- BrandonEdwards
- nhtran93
- krother
- Genomematt

Let me know if you need more suggestions

**Comment by Nikoleta-v3** [comment]
Thank you for the suggestions 😃

**Comment by Nikoleta-v3** [comment]
:wave: @edrictam & @ayush9pandey & @wxwx1993 & @BrandonEdwards, would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission I'd like you to review is titled: "Epimargin: A Toolkit for Epidemiological Estimation, Prediction, and Policy Evaluation". You can find more information at the top of this Github issue 🆙 

Please let me know if you're available :smile: Thank you!

**Comment by satejsoman** [comment]
Hi @Nikoleta-v3, should we ask the next group of reviewers if they're available?

**Comment by wxwx1993** [comment]
I am happy to provide the review for this submission for JOSS. Could you please let me know the deadline and any additional requirements?

**Comment by Nikoleta-v3** [comment]
Thank you @wxwx1993 😄

The official reviewing guidelines for JOSS are available here: https://joss.readthedocs.io/en/latest/review_checklist.html 

The reviews are checklist-driven. As you can see the current issue is labeled a `pre review` issue. Once we find a second reviewer this issue will be closed, and we will open the `review` issue. There you will find a checklist that you need to complete as a reviewer. The checklist is there mainly to help/guide you. 

If you have any issues you want to raise regarding the submission feel free to open issues in the original repository and/or comment on the `review` issue. Hope this information helps! 

Now regarding deadlines. Though there is not a hard deadline I would appreciate receiving your review within a reasonable time.  I could set a 2 weeks reminder for you once the review process begins.

**Comment by Nikoleta-v3** [comment]
👋 @dilawar & @nhtran93 & @krother & @Genomematt, would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission I'd like you to review is titled: "Epimargin: A Toolkit for Epidemiological Estimation, Prediction, and Policy Evaluation". You can find more information at the top of this Github issue 🆙

Please let me know if you're available 😄 Thank you!

**Comment by dilawar** [comment]
I am happy to review this submission. 

PS: This will be my first review.

**Comment by Nikoleta-v3** [comment]
Thank you @dilawar 😄 That's absolutely fine! 🎉 

You can see my message to above regarding the reviewing process: https://github.com/openjournals/joss-reviews/issues/3382#issuecomment-876987050, and you will always be able to ping me if you have any questions/concerns.

**Comment by Nikoleta-v3** [comment]
@whedon assign @wxwx1993 as reviewer

**Comment by whedon** [comment]
OK, @wxwx1993 is now a reviewer

**Comment by Nikoleta-v3** [comment]
@whedon add @dilawar as reviewer

**Comment by whedon** [comment]
OK, @dilawar is now a reviewer

**Comment by Nikoleta-v3** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3464.
