### ISSUE TITLE
[PRE REVIEW]: eeg-preprocessing: A framework for semiautomatic preprocessing of EEG/MEG data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3385]
**Submitting author:** @weiglszonja (<a href="http://orcid.org/0000-0001-6615-1360">Anna Szonja Weigl</a>)
**Repository:** <a href="https://github.com/weiglszonja/eeg-preprocessing" target ="_blank">https://github.com/weiglszonja/eeg-preprocessing</a>
**Version:** v0.2.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/cbef6f0c9e8e6e915d2d800166c365ff/status.svg)](https://joss.theoj.org/papers/cbef6f0c9e8e6e915d2d800166c365ff)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cbef6f0c9e8e6e915d2d800166c365ff"><img src="https://joss.theoj.org/papers/cbef6f0c9e8e6e915d2d800166c365ff/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cbef6f0c9e8e6e915d2d800166c365ff/status.svg)](https://joss.theoj.org/papers/cbef6f0c9e8e6e915d2d800166c365ff)
```

**Author instructions**

Thanks for submitting your paper to JOSS @weiglszonja. **Currently, there isn't an JOSS editor assigned** to your paper.

@weiglszonja if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/fnins.2013.00267 is OK
- 10.1016/0013-4694(89)90180-6 is OK
- 10.1016/j.neuroimage.2017.06.030 is OK
- 10.3389/fninf.2015.00016 is OK
- 10.1145/358669.358692 is OK
- 10.1162/neco.1995.7.6.1129 is OK
- 10.1142/9789812818041_0008 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (304.4 files/s, 91461.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           8            125            102            324
Markdown                         2             68              0            273
Jupyter Notebook                 2              0           3862            159
TeX                              1              6              0             99
YAML                             4             10              5             75
-------------------------------------------------------------------------------
SUM:                            17            209           3969            930
-------------------------------------------------------------------------------


Statistical information for the repository '4573e0329dd75cfe9805710f' was
gathered on 2021/06/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
weiglszonja                     44          1355            804          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
weiglszonja                 551           40.7          0.6                4.54
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03385/joss.03385/10.21105.joss.03385.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03385/joss.03385/10.21105.joss.03385.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @weiglszonja - I'm sorry, but this submission has far too little code to meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work. We would also consider a future resubmission of an extended package with more code and more effort.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
