### ISSUE TITLE
[PRE REVIEW]: bmgarch: An R-Package for Bayesian Multivariate GARCH models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3387]
**Submitting author:** @ph-rast (<a href="http://orcid.org/0000-0003-3630-6629">Philippe Rast</a>)
**Repository:** <a href="https://github.com/ph-rast/bmgarch" target ="_blank">https://github.com/ph-rast/bmgarch</a>
**Version:** v1.0.1
**Editor:** @jbytecode
**Reviewers:** @ChristopherLucas, @mwt
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fc0db2c4d3bbf1eb18611131f848ed5a/status.svg)](https://joss.theoj.org/papers/fc0db2c4d3bbf1eb18611131f848ed5a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fc0db2c4d3bbf1eb18611131f848ed5a"><img src="https://joss.theoj.org/papers/fc0db2c4d3bbf1eb18611131f848ed5a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fc0db2c4d3bbf1eb18611131f848ed5a/status.svg)](https://joss.theoj.org/papers/fc0db2c4d3bbf1eb18611131f848ed5a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ph-rast. **Currently, there isn't an JOSS editor assigned** to your paper.

@ph-rast if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (253.9 files/s, 33242.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               17            261            764           1347
Markdown                         4            116              0            887
TeX                              2             25              0            178
YAML                             3             30             28            134
Rmd                              1             53            115             70
Lisp                             2              2              0             27
C++                              1              6              2             12
C/C++ Header                     1              0              1              0
-------------------------------------------------------------------------------
SUM:                            31            493            910           2655
-------------------------------------------------------------------------------


Statistical information for the repository '6dda6573d55e087d93bf1a25' was
gathered on 2021/06/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Philippe Rast                    5          6592           6571          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Philippe Rast                21            0.3          5.5               14.29
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/0304-4076(86)90063-1 is OK
- 10.2307/2109358 is OK
- 10.1080/00949655.2020.1783262 is OK
- 10.1515/snde-2012-0065 is OK
- 10.1016/J.IJFORECAST.2017.08.003 is OK
- 10.2307/1912773 is OK
- 10.1198/073500102288618487 is OK
- 10.1017/S0266466600009063 is OK
- 10.1037/met0000357 is OK
- 10.1214/17-BA1091 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03387/joss.03387/10.21105.joss.03387.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03387/joss.03387/10.21105.joss.03387.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @ph-rast - I (and whedon) don't see a license for this code. JOSS requires software to have an OSI-approved license for it to be reviewed

**Comment by jbytecode** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jbytecode

**Comment by jbytecode** [comment]
Hi @ph-rast

Thank you for the submission. 

- As @danielskatz stated, please set a valid OSI-approved license (see the list in https://opensource.org/licenses/category)
- Could you please take a look through https://bit.ly/joss-reviewers to suggest some potential reviewers?

**Comment by ph-rast** [comment]
Hi @jbytecode ,
I now include a license, GPL3.0.

Suggested reviewers: 
- ChristopherLucas
- pedro-teles-fonseca
- Medewitt

**Comment by jbytecode** [comment]
@ph-rast Thank you. This list very helpful as the suggested reviewers have R and Econometrics in their preferred language and research interest.

**Comment by jbytecode** [comment]
@ChristopherLucas @pedro-teles-fonseca @Medewitt 

Hi! Would you willing to assist in reviewing this submission?

**Comment by jbytecode** [comment]
@ptfonseca Hi, would you willing to assist in reviewing this submission for JOSS?

**Comment by ChristopherLucas** [comment]
> @ChristopherLucas @pedro-teles-fonseca @medewitt
> 
> Hi! Would you willing to assist in reviewing this submission?

I'm happy to

**Comment by jbytecode** [comment]
@whedon assign @ChristopherLucas as reviewer

**Comment by whedon** [comment]
OK, @ChristopherLucas is now a reviewer

**Comment by jbytecode** [comment]
@ChristopherLucas thank you for the response. The process will start after we set the second reviewer. Meanwhile, you can have a look at the [reviewing guide](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) of JOSS if you are not familiar with the system.

**Comment by jbytecode** [comment]
Dear @zedtaha, I am just pinging you to ask if you would be willing to assist in reviewing this submission for JOSS?

**Comment by jbytecode** [comment]
Hi @mwt, would you be willing to assist in reviewing this submission for JOSS?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "bmgarch: An R-Package for Bayesian Multivariate GARCH models". You can find more information at the top of this Github issue.

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by mwt** [comment]
Hi @jbytecode. Sure, I'm happy to give it a try. I also just started reviewing #3352 just so you know. I should be able to do both unless I am underestimating how much time this takes.

I am a little concerned by:
> Please add following citation when referring to to this package:
> 
> Rast, P., Martin, S. R., Liu, S., & Williams, D. R. (in press). A New Frontier for Studying Within-Person Variability: Bayesian Multivariate Generalized Autoregressive Conditional Heteroskedasticity Models. *Psychological Methods*. [https://doi.org/10.1037/met0000357](https://doi.org/10.1037/met0000357)

Because I thought that you're not supposed to publish code in JOSS that is published elsewhere.

**Comment by jbytecode** [comment]
Dear @mwt, 

It is not problem to have two distinct reviewing jobs at the same time. The deadline is not rigid so we can wait a little while. 

The citation you have mentioned is a research paper. It is usual to have a research published somewhere else and submit a paper about its software and repository in JOSS. Thank you very much for your attention and reminder.

**Comment by jbytecode** [comment]
@whedon add @mwt as reviewer

**Comment by whedon** [comment]
OK, @mwt is now a reviewer

**Comment by jbytecode** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3452.
