### ISSUE TITLE
[PRE REVIEW]: Inteq: Solve Volterra and Fredholm integral equations in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3388]
**Submitting author:** @mwt (<a href="http://orcid.org/0000-0003-0319-3891">Matthew Wildrick Thomas</a>)
**Repository:** <a href="https://github.com/mwt/inteq" target ="_blank">https://github.com/mwt/inteq</a>
**Version:** v0.2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/44c2fe3bd3636e2509ef6ab6a3bdd22d/status.svg)](https://joss.theoj.org/papers/44c2fe3bd3636e2509ef6ab6a3bdd22d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/44c2fe3bd3636e2509ef6ab6a3bdd22d"><img src="https://joss.theoj.org/papers/44c2fe3bd3636e2509ef6ab6a3bdd22d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/44c2fe3bd3636e2509ef6ab6a3bdd22d/status.svg)](https://joss.theoj.org/papers/44c2fe3bd3636e2509ef6ab6a3bdd22d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mwt. **Currently, there isn't an JOSS editor assigned** to your paper.

@mwt if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (278.2 files/s, 18926.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              4              0             21           1008
Python                           9             97            155            177
reStructuredText                 6             70             36             78
Markdown                         2             15              0             55
TeX                              1              3              0             42
DOS Batch                        1              8              1             26
make                             1              4              7              9
YAML                             1              3              6              7
TOML                             1              0              0              6
JSON                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            27            200            226           1411
-------------------------------------------------------------------------------


Statistical information for the repository '1a1095aac5afb6a2b9ce5341' was
gathered on 2021/06/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Matthew Thomas                  18           519             90          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Matthew Thomas              429           82.7          0.1               18.65
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1093/comjnl/12.4.393 may be a valid DOI for title: Numerical methods for Volterra integral equations of the first kind

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03388/joss.03388/10.21105.joss.03388.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03388/joss.03388/10.21105.joss.03388.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @mwt - I'm sorry to say that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by mwt** [comment]
@danielskatz Was this because of the age and number of commits? The code dates back to a 2019 working paper on lobbying. It was eventually wrapped up into the `allpy` package for solving all-pay auctions/contests. It was then split off so that people outside of auction/contest theory can use it. So, the number of commits and initial date are misleading. The first commit is a working package and most of later commits are for the documentation.

There are two ways that I can think of the increase the scholarly effort of the submission.

1. I could make a combined submission of `allpy` and `inteq`. However, they are in different repositories.
2. There is a planned update that solves vie and fie of the second type. This should double the functionality of the package. I could resubmit `inteq` after this.

Is it likely that one or both of these would make the submission acceptable?

**Comment by danielskatz** [comment]
See

> Total lines of code (LOC). Submissions under 1000 LOC will usually be flagged, those under 300 LOC will be desk rejected.

in https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort
