### ISSUE TITLE
[REVIEW]: Lcopt - An interactive tool for creating fully parameterised Life Cycle Assessment (LCA) foreground models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#339]
**Submitting author:** @pjamesjoyce (<a href="http://orcid.org/0000-0002-9560-3132">P. James Joyce</a>)
**Repository:** <a href="https://github.com/pjamesjoyce/lcopt" target ="_blank">https://github.com/pjamesjoyce/lcopt</a>
**Version:** v0.4.2
**Editor:** @katyhuff
**Reviewer:** @amoeba
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.848529" target="_blank">10.5281/zenodo.848529</a>

## Status

[![status](http://joss.theoj.org/papers/c0b544bee185c9ac75e96d24b8573547/status.svg)](http://joss.theoj.org/papers/c0b544bee185c9ac75e96d24b8573547)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c0b544bee185c9ac75e96d24b8573547"><img src="http://joss.theoj.org/papers/c0b544bee185c9ac75e96d24b8573547/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c0b544bee185c9ac75e96d24b8573547/status.svg)](http://joss.theoj.org/papers/c0b544bee185c9ac75e96d24b8573547)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pjamesjoyce/lcopt" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@amoeba, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @katyhuff know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pjamesjoyce/lcopt">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.4.2)?
- [x] **Authorship:** Has the submitting author (@pjamesjoyce) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @amoeba it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by cmutel** [comment]
I can participate in this review, but currently on vacation without a computer or reliable internet until August 8th.

**Comment by amoeba** [comment]
Thanks @cmutel. I'm going through the basics right now and would really appreciate it if you could check whatever you have time for but at least the functionality item of the review checklist. I should be able to do the rest.

**Comment by amoeba** [comment]
I had a chance to sit down with this over the weekend and things are looking great. I'm not quite done but I expect to be able to finish it by the end of the week here.

**Comment by amoeba** [comment]
Hey @pjamesjoyce this looks great now. Thanks for responding to the two issues I raised on the repository. I've checked off everything in the reviewer checklist, including the functionality item. If @cmutel could take a second look, I would very much appreciate the help with that item. Otherwise, everything looks great.

Kudos for the extensive documentation and creating a very nice interactive tool. It looks like it represents a great deal of work and I had no troubles using it.

@katyhuff I give this submission an Accept. With respect to functionality, I've verified the software does what it says it does to the best of my knowledge but I accept that my knowledge of LCA is limited. If you'd prefer to get a topical expert review from @cmutel I'd gladly change withhold my Accept until that's been done. What do you think?

**Comment by katyhuff** [comment]
Thanks @amoeba for your review efforts and @pjamesjoyce for your prompt cooperation! I would love it if @cmutel could give this a final expert glance. I think has just gotten back into a space with internet in the last few days.

**Comment by cmutel** [comment]
@amoeba @katyhuff I have filed some issues on the project page; I am also getting some errors when running stuff, but still need to figure out if that is a misconfiguration on my end.

**Comment by katyhuff** [comment]
Thanks @cmutel. When those have been resolved, can you and @pjamesjoyce update us here?

**Comment by pjamesjoyce** [comment]
I've referenced the issues to here so they're all in one place. 
I've left pjamesjoyce/lcopt#10 open as it included changes to the docs so whether it's resolved is subjective rather than technical. If @cmutel and/or @amoeba could take a quick look and close the issue if it's ok that'd be great.

**Comment by amoeba** [comment]
That all looks great. Thanks for helping out @cmutel. And thanks for the quick responses to edits, @pjamesjoyce. I'm good here and I approve this submission. cc @katyhuff 

And, as I said before, this is a really well put-together piece of software, especially the polished nature of the UI and the highly-detailed docs. Well done!

**Comment by katyhuff** [comment]
Thank you @amoeba and @cmutel for your thorough review. And, of course, thank you @pjamesjoyce , for your submission.

@pjamesjoyce -  At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by pjamesjoyce** [comment]
Thanks everyone (@katyhuff, @amoeba, @cmutel)!

Here's the DOI of the Zenodo archive -  10.5281/zenodo.848529

[![DOI](https://zenodo.org/badge/76573839.svg)](https://zenodo.org/badge/latestdoi/76573839)

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.848529 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.848529" target="_blank">10.5281/zenodo.848529</a> is the archive.

**Comment by katyhuff** [comment]
@arfon we are ready to accept this paper, thanks!

**Comment by arfon** [comment]
@amoeba many thanks for your review here and to @katyhuff for editing this submission ✨ 

@pjamesjoyce - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00339 ⚡️ 🚀 💥

**Comment by pjamesjoyce** [comment]
Thank you all for your time and effort. Much appreciated! :smiley:
