### ISSUE TITLE
[REVIEW]: Lumen: A software for the interactive visualization of probabilistic models together with data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3395]
**Submitting author:** @nandaloo (<a href="http://orcid.org/0000-0002-6687-8209">Philipp Lucas</a>)
**Repository:** <a href="https://github.com/lumen-org/lumen" target ="_blank">https://github.com/lumen-org/lumen</a>
**Version:** v1.0
**Editor:** @vissarion
**Reviewers:** @crhea93, @szkafander
**Archive:** <a href="https://doi.org/10.5281/zenodo.5069308" target="_blank">10.5281/zenodo.5069308</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2/status.svg)](https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2"><img src="https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2/status.svg)](https://joss.theoj.org/papers/e21fbec25f69775b55809c88ca7fe0d2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/lumen-org/lumen" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@crhea93 & @szkafander, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @vissarion know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lumen-org/lumen">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nandaloo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lumen-org/lumen">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@nandaloo) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @crhea93, @szkafander it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jmva.2020.104601 is OK
- 10.7717/peerj-cs.55 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- 10.1109/iccvw.2011.6130310 may be a valid DOI for title: Sum-Product Networks: A New Deep Architecture
- 10.1109/2945.981851 may be a valid DOI for title: Polaris: A System for Query, Analysis, and Visualization of Multidimensional Relational Databases

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=9.30 s (14.4 files/s, 9690.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      86           7669          19336          36625
SVG                             36             36             36          16233
CSS                              4            903            220           7898
Markdown                         4            221              0            510
TeX                              1             16              0            165
HTML                             1             22             30             91
JSON                             2              1              0             74
-------------------------------------------------------------------------------
SUM:                           134           8868          19622          61596
-------------------------------------------------------------------------------


Statistical information for the repository '38a9d228f4dd2342e8abb74f' was
gathered on 2021/06/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
=                                7            96             23            0.06
Andreas Goral                    2           318              0            0.16
Christoph Saffer                 3            12             11            0.01
Joachim Giesen                   2             8              7            0.01
Philipp Lucas                  729        132104          68882           99.61
Schmalwasser                    11           151             70            0.11
asver12                          1            31             63            0.05

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
=                            86           89.6         19.5                4.65
Christoph Saffer              3           25.0         30.7                0.00
Joachim Giesen                1           12.5         41.7                0.00
Philipp Lucas             63457           48.0         28.9               15.70
Schmalwasser                 53           35.1         21.7                3.77
asver12                      30           96.8         21.2                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jmva.2020.104601 is OK
- 10.7717/peerj-cs.55 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- 10.1109/iccvw.2011.6130310 may be a valid DOI for title: Sum-Product Networks: A New Deep Architecture
- 10.1214/aoms/1177704472 may be a valid DOI for title: On estimation of a probability density function and mode
- 10.1109/2945.981851 may be a valid DOI for title: Polaris: A System for Query, Analysis, and Visualization of Multidimensional Relational Databases

INVALID DOIs

- None
```

**Comment by vissarion** [comment]
@nandaloo there are some missing DOIs @whedon found, please fix them.

@crhea93 it seems that you finished your review! Do you have any comments, issues, concerns?

**Comment by crhea93** [comment]
@vissarion yes that is correct -- I finished the review. I am very impressed by the software. Although the install seemed daunting at first, it went smoothly and rather quickly. The authors did a good job of putting together a comprehensive manual - I was able to get everything running in no time and was able to play around quite a bit with the software with minimal background knowledge.

**Comment by szkafander** [comment]
@vissarion I can't seem to edit the checklist - forgot to accept the invitation. Could you please reinvite me?

**Comment by vissarion** [comment]
@whedon add @szkafander as reviewer

**Comment by whedon** [comment]
OK, @szkafander is now a reviewer

**Comment by nandaloo** [comment]
@vissarion I update the bibliography file. For one of the papers there is not DOI available, but I added a link to the arXiv preprint version.

@crhea93 Thanks a lot! :-)

**Comment by szkafander** [comment]
@vissarion I completed the review. The software works as intended. As far as I can tell, it indeed fills a gap in the probabilistic modeling field. Installation works. The backend often fails on Windows due to a concurrency bug, but works OK on other systems; nevertheless, this is not directly related to Lumen. The references are not rendered in the paper, but that should be easy to fix. Overall very impressed with the package.

**Comment by nandaloo** [comment]
@szkafander Thank you so much for your effort, in particular trying it out on multiple systems. regarding the references: I just test-compiled the paper with https://whedon.theoj.org/ - which did work and render the references correctly.

**Comment by nandaloo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: :point_left:

**Comment by vissarion** [comment]
@whedon remove @szkafander as reviewer

**Comment by whedon** [comment]
OK, @szkafander is no longer a reviewer

**Comment by vissarion** [comment]
@whedon add @szkafander as reviewer

**Comment by whedon** [comment]
OK, @szkafander is now a reviewer

**Comment by vissarion** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: :point_left:

**Comment by vissarion** [comment]
@whedon remove @szkafander as reviewer

**Comment by whedon** [comment]
OK, @szkafander is no longer a reviewer

**Comment by vissarion** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: :point_left:

**Comment by vissarion** [comment]
@whedon add @szkafander as reviewer

**Comment by whedon** [comment]
OK, @szkafander is now a reviewer

**Comment by vissarion** [comment]
There is an issue with szkafander that appear twice in the paper as reviewer. I will try to find a solution. 

In the meantime @nandaloo could you please make a tagged release and report the number. Also please create an archive (e.g. in zenodo) and report the DOI and link here. The archive should have the same title and the same list of authors as the paper.

**Comment by vissarion** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: :point_left:

**Comment by nandaloo** [comment]
@vissarion I made a *tagged release* with number v1.0 located at https://github.com/lumen-org/lumen/releases/tag/v1.0
 Also, I *uploaded it at zenodo* under DOI 10.5281/zenodo.5069308. The url is https://doi.org/10.5281/zenodo.5069308

**Comment by vissarion** [comment]
@whedon set 10.5281/zenodo.5069308 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5069308" target="_blank">10.5281/zenodo.5069308</a> is the archive.

**Comment by vissarion** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by vissarion** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jmva.2020.104601 is OK
- 10.7717/peerj-cs.55 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- 10.1109/iccvw.2011.6130310 may be a valid DOI for title: Sum-Product Networks: A New Deep Architecture
- 10.1109/2945.981851 may be a valid DOI for title: Polaris: A System for Query, Analysis, and Visualization of Multidimensional Relational Databases

INVALID DOIs

- None
```

**Comment by vissarion** [comment]
@nandaloo thanks. Please checkout the missing DOIs found above, it seems that @whedon suggestions are correct!

**Comment by nandaloo** [comment]
@vissarion I update the bibliography file as follows: 
- added missing DOI for the paper "Polaris: A System for Query, Analysis, and Visualization of Multidimensional Relational Databases":
- I added a link to the arXiv preprint version for the paper "Sum-Product Networks: A New Deep Architecture". Whdeom suggested a DOI, but that one is for a workshop version of the paper. The actual publication is under conference proceedings of UAI - and has no DOI.

**Comment by vissarion** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jmva.2020.104601 is OK
- 10.7717/peerj-cs.55 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/2945.981851 is OK

MISSING DOIs

- 10.1109/iccvw.2011.6130310 may be a valid DOI for title: Sum-Product Networks: A New Deep Architecture

INVALID DOIs

- None
```

**Comment by vissarion** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: :point_left:

**Comment by vissarion** [comment]
> @vissarion I update the bibliography file as follows:
> 
>     * added missing DOI for the paper "Polaris: A System for Query, Analysis, and Visualization of Multidimensional Relational Databases":
> 
>     * I added a link to the arXiv preprint version for the paper "Sum-Product Networks: A New Deep Architecture". Whdeom suggested a DOI, but that one is for a workshop version of the paper. The actual publication is under conference proceedings of UAI - and has no DOI.

Thanks, I see.

I found two more papers that have available DOIs as well as open access versions; see https://github.com/lumen-org/lumen/issues/106

After fixing that I am ready to recommend acceptance.

**Comment by nandaloo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: :point_left:

**Comment by nandaloo** [comment]
@vissarion I mixed #106 and also added more missing DOIs. All references now include the DOIs or have none. Thank you!

**Comment by vissarion** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: :point_left:

**Comment by vissarion** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jmva.2020.104601 is OK
- 10.7717/peerj-cs.55 is OK
- 10.1214/aoms/1177705052 is OK
- 10.1214/aoms/1177704472 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1111/rssa.12378 is OK
- 10.1201/b16018 is OK
- 10.1109/2945.981851 is OK
- 10.4232/1.12796 is OK

MISSING DOIs

- 10.1109/iccvw.2011.6130310 may be a valid DOI for title: Sum-Product Networks: A New Deep Architecture

INVALID DOIs

- None
```

**Comment by vissarion** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jmva.2020.104601 is OK
- 10.7717/peerj-cs.55 is OK
- 10.1214/aoms/1177705052 is OK
- 10.1214/aoms/1177704472 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1111/rssa.12378 is OK
- 10.1201/b16018 is OK
- 10.1109/2945.981851 is OK
- 10.4232/1.12796 is OK

MISSING DOIs

- 10.1109/iccvw.2011.6130310 may be a valid DOI for title: Sum-Product Networks: A New Deep Architecture

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2438

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2438, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@nandaloo Things are looking good! Small comment: Some capitalization isn't correct in your references. Please check carefully, but in particular I saw "python" and "bayesian" not capitalized. You can preserve it using {} around characters, words, or phrases.

**Comment by nandaloo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03395/joss.03395/10.21105.joss.03395.pdf) :page_facing_up: :point_left:

**Comment by nandaloo** [comment]
@kthyng Thanks for the hint. I fixed the .bib according to https://stackoverflow.com/questions/2800527/preserving-all-capitalization-in-bibtex

**Comment by arfon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.jmva.2020.104601 is OK
- 10.7717/peerj-cs.55 is OK
- 10.1214/aoms/1177705052 is OK
- 10.1214/aoms/1177704472 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1111/rssa.12378 is OK
- 10.1201/b16018 is OK
- 10.1109/2945.981851 is OK
- 10.4232/1.12796 is OK

MISSING DOIs

- 10.1109/iccvw.2011.6130310 may be a valid DOI for title: Sum-Product Networks: A New Deep Architecture

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2455

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2455, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1416438126755651585) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2456
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03395](https://doi.org/10.21105/joss.03395)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@crhea93, @szkafander – many thanks for your reviews here and to @vissarion for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@nandaloo – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03395/status.svg)](https://doi.org/10.21105/joss.03395)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03395">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03395/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03395/status.svg
   :target: https://doi.org/10.21105/joss.03395
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03395/status.svg)](https://doi.org/10.21105/joss.03395)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
