### ISSUE TITLE
[PRE REVIEW]: Leafmap: A Python package for interactive mapping and geospatial analysis with minimal coding in a Jupyter environment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3396]
**Submitting author:** @giswqs (<a href="http://orcid.org/0000-0001-5437-4073">Qiusheng Wu</a>)
**Repository:** <a href="https://github.com/giswqs/leafmap" target ="_blank">https://github.com/giswqs/leafmap</a>
**Version:** v0.3.2
**Editor:** @ajstewartlang
**Reviewers:** @TomasBeuzen, @TomasBeuzen, @martinfleis
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b081afbd9bdaa4386475c787db8e370c/status.svg)](https://joss.theoj.org/papers/b081afbd9bdaa4386475c787db8e370c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b081afbd9bdaa4386475c787db8e370c"><img src="https://joss.theoj.org/papers/b081afbd9bdaa4386475c787db8e370c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b081afbd9bdaa4386475c787db8e370c/status.svg)](https://joss.theoj.org/papers/b081afbd9bdaa4386475c787db8e370c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @giswqs. **Currently, there isn't an JOSS editor assigned** to your paper.

@giswqs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.rse.2017.06.031 is OK
- 10.21105/joss.02272 is OK
- 10.5334/jors.148 is OK
- 10.5281/zenodo.4569086 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.35 s (236.3 files/s, 194765.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             6              0              0          50166
Python                          15           1573           1782           6213
XML                              2              0              0           1636
Markdown                        23            253              0            676
Jupyter Notebook                24              0           4369            479
YAML                             9             25             10            278
HTML                             2              3              0             65
TeX                              1              4              0             59
-------------------------------------------------------------------------------
SUM:                            82           1858           6161          59572
-------------------------------------------------------------------------------


Statistical information for the repository '077d67467841899ebe1a98ed' was
gathered on 2021/06/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kharude, Sachin                  7          1145            131           11.60
Nahid Pervez                     3            32              4            0.33
Qiusheng Wu                     45          9258            433           88.08

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kharude, Sachin             707           61.7          0.4                3.54
Nahid Pervez                 29           90.6          0.4                6.90
Qiusheng Wu                8832           95.4          0.8                6.13
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03396/joss.03396/10.21105.joss.03396.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03396/joss.03396/10.21105.joss.03396.pdf) :page_facing_up: :point_left:

**Comment by ajstewartlang** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @ajstewartlang

**Comment by ajstewartlang** [comment]
@whedon assign @martinfleis as reviewer

**Comment by whedon** [comment]
OK, @martinfleis is now a reviewer

**Comment by giswqs** [comment]
Potential reviewers: chrieke, robbibt, TomasBeuzen, davemlz

**Comment by ajstewartlang** [comment]
Many thanks for those suggestions @giswqs

**Comment by ajstewartlang** [comment]
@whedon assign @TomasBeuzen as reviewer

**Comment by whedon** [comment]
OK, @TomasBeuzen is now a reviewer

**Comment by ajstewartlang** [comment]
@whedon add @TomasBeuzen as reviewer

**Comment by whedon** [comment]
OK, @TomasBeuzen is now a reviewer

**Comment by ajstewartlang** [comment]
@whedon add @martinfleis as reviewer

**Comment by whedon** [comment]
OK, @martinfleis is now a reviewer

**Comment by ajstewartlang** [comment]
Many thanks for agreeing to review this submission @martinfleis and @TomasBeuzen - I'll start the review process now...

**Comment by ajstewartlang** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3414.
