### ISSUE TITLE
[REVIEW]: ACEInhibPKPD: An open-source MATLAB app for a pharmacokinetic/pharmacodynamic model of ACE inhibition

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#340]
**Submitting author:** @ashleefv (<a href="http://orcid.org/0000-0001-9059-5703">Ashlee N. Ford Versypt</a>)
**Repository:** <a href="https://github.com/ashleefv/ACEInhibPKPD" target ="_blank">https://github.com/ashleefv/ACEInhibPKPD</a>
**Version:** v1.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @sdelandtsheer
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.885362" target="_blank">10.5281/zenodo.885362</a>

## Status

[![status](http://joss.theoj.org/papers/a22d6875fa1e1d04cf0c6ba1eec9111a/status.svg)](http://joss.theoj.org/papers/a22d6875fa1e1d04cf0c6ba1eec9111a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a22d6875fa1e1d04cf0c6ba1eec9111a"><img src="http://joss.theoj.org/papers/a22d6875fa1e1d04cf0c6ba1eec9111a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a22d6875fa1e1d04cf0c6ba1eec9111a/status.svg)](http://joss.theoj.org/papers/a22d6875fa1e1d04cf0c6ba1eec9111a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ashleefv/ACEInhibPKPD" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@sdelandtsheer, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ashleefv/ACEInhibPKPD">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@ashleefv) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @sdelandtsheer it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by sdelandtsheer** [comment]
@wedon commands

**Comment by sdelandtsheer** [comment]
@wedon commands

**Comment by sdelandtsheer** [comment]
@wedon commands

**Comment by danielskatz** [comment]
you've missed the h in @whedon 
and also, reviewers shouldn't need to interact with @whedon - it's more for editors
If you are done with your review, you can let the editor know by just adding a comment to the issue.

**Comment by sdelandtsheer** [comment]
Hi @Kevin-Mattheus-Moerman I have one remark:
There is documentation missing for the function _run_PKPD_without_GUI_. The input/output should be specified clearly, this is the function to run the simulations from the command line. I also recommend making the last three arguments optional.
The app is otherwise well documented, functional, and can be accepted when this is corrected as far as I am concerned.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @sdelandtsheer for the fast review. @ashleefv can you work on these comments and formulate a reply?

**Comment by sdelandtsheer** [comment]
Hi, any news on this? Can I help clarifying something?

**Comment by Kevin-Mattheus-Moerman** [comment]
@ashleefv can you respond to @sdelandtsheer 's comments?

**Comment by arfon** [comment]
@Kevin-Mattheus-Moerman @danielskatz - it looks like the review checklist is missing from this thread. Did one of you accidentally delete it?

**Comment by arfon** [comment]
> @Kevin-Mattheus-Moerman @danielskatz - it looks like the review checklist is missing from this thread. Did one of you accidentally delete it?

Well that's very strange. The top of the issue thread wasn't rendering for me just before. Ignore me!

**Comment by ashleefv** [comment]
I made the requested changes in *run_PKPD_without_GUI*.m and committed
those changes.

Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State
University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences
Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu
Ford Versypt Lab Website <https://sites.google.com/site/ashleefordversypt/>

**Comment by ashleefv** [comment]
@Kevin-Mattheus-Moerman <https://github.com/kevin-mattheus-moerman>
@sdelandtsheer <https://github.com/sdelandtsheer> I made the requested
changes in *run_PKPD_without_GUI*.m and committed those changes.

Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State
University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences
Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu
Ford Versypt Lab Website <https://sites.google.com/site/ashleefordversypt/>

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @ashleefv. @sdelandtsheer are you happy with how your comments were addressed?

**Comment by sdelandtsheer** [comment]
Thanks @ashleefv for making the changes. This is now a well-documented function. @Kevin-Mattheus-Moerman I am happy indeed.

**Comment by sdelandtsheer** [comment]
I checked the last box. Should be good to go.

**Comment by Kevin-Mattheus-Moerman** [comment]
:rocket: :cake: Thanks @sdelandtsheer for the review!!! 

@arfon - we are ready to accept this submission.

**Comment by sdelandtsheer** [comment]
@Kevin-Mattheus-Moerman Happy to help. Thank you for considering Matlab code in your journal. Feel free to contact me if needed.

**Comment by Kevin-Mattheus-Moerman** [comment]
:wave: @arfon can you help process the acceptance of this paper?

**Comment by arfon** [comment]
@ashleefv - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

I note there is already a DOI present in the README but this doesn't seem to have the JOSS-specific stuff present (e.g. the `paper.md` and `paper.bib` files).

**Comment by ashleefv** [comment]
@arfon I updated the DOI with the revisions and the paper.md and paper.bib
files.

https://doi.org/10.5281/zenodo.885362


Ashlee N. Ford Versypt, Ph.D.
Assistant Professor, School of Chemical Engineering, Oklahoma State
University
Member, Harold Hamm Diabetes Center, University of Oklahoma Health Sciences
Center
420 Engineering North, OSU, Stillwater, OK 74078
Ph: 405-744-5280
ashleefv@okstate.edu
Ford Versypt Lab Website <https://sites.google.com/site/ashleefordversypt/>

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.885362 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.885362" target="_blank">10.5281/zenodo.885362</a> is the archive.

**Comment by arfon** [comment]
@sdelandtsheer - many thanks for your review and to @Kevin-Mattheus-Moerman for editing this submission ✨ 

@ashleefv - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00340 ⚡️ 🚀 💥
