### ISSUE TITLE
[PRE REVIEW]: Finnish Media Scrapers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3400]
**Submitting author:** @jiemakel (<a href="http://orcid.org/0000-0002-8366-8414">Eetu Mäkelä</a>)
**Repository:** <a href="https://github.com/hsci-r/finnish-media-scrapers" target ="_blank">https://github.com/hsci-r/finnish-media-scrapers</a>
**Version:** v1.0.1
**Editor:** @ajstewartlang
**Reviewers:** @sara-shiho, @pmyteh
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0bdd0f947b2d986b4acc4b9b6737dde8/status.svg)](https://joss.theoj.org/papers/0bdd0f947b2d986b4acc4b9b6737dde8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0bdd0f947b2d986b4acc4b9b6737dde8"><img src="https://joss.theoj.org/papers/0bdd0f947b2d986b4acc4b9b6737dde8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0bdd0f947b2d986b4acc4b9b6737dde8/status.svg)](https://joss.theoj.org/papers/0bdd0f947b2d986b4acc4b9b6737dde8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jiemakel. **Currently, there isn't an JOSS editor assigned** to your paper.

@jiemakel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1177/1464884920985724 is OK
- 10.1111/j.1460-2466.2011.01596.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (1114.1 files/s, 61375.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          18            231            195            916
YAML                             5              7             13            103
Markdown                         3             52              0             82
reStructuredText                 4             45             78             53
TeX                              1              2              0             35
DOS Batch                        1              8              1             26
make                             1              4              7              9
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            34            349            294           1230
-------------------------------------------------------------------------------


Statistical information for the repository 'e38ed8a81cee6f9eaa6510f2' was
gathered on 2021/06/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Eetu Mäkelä                     39          2535           2260           75.99
Pihla Toivanen                  38          1291            224           24.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Eetu Mäkelä                1278           50.4          0.4                7.98
Pihla Toivanen               64            5.0          1.5                6.25
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03400/joss.03400/10.21105.joss.03400.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03400/joss.03400/10.21105.joss.03400.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @ajstewartlang, could you edit this submission? This looks to align with your interests in open and reproducible research.

**Comment by kyleniemeyer** [comment]
@whedon invite @ajstewartlang as editor

**Comment by whedon** [comment]
@ajstewartlang has been invited to edit this submission.

**Comment by ajstewartlang** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @ajstewartlang

**Comment by ajstewartlang** [comment]
@whedon assign @sara-shiho as reviewer

**Comment by whedon** [comment]
OK, @sara-shiho is now a reviewer

**Comment by ajstewartlang** [comment]
@whedon add @pmyteh as reviewer

**Comment by whedon** [comment]
OK, @pmyteh is now a reviewer

**Comment by ajstewartlang** [comment]
Many thanks @Sara-ShiHo and @pmyteh for agreeing to review this submission. It's very much appreciated! I'll open the review issue now - just ping me if you have any questions...

**Comment by ajstewartlang** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3504.
