### ISSUE TITLE
[PRE REVIEW]: SHINE_color: controlling low-level properties of colorful images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3401]
**Submitting author:** @RodDalBen (<a href="http://orcid.org/0000-0003-2185-8762">Rodrigo Dal Ben</a>)
**Repository:** <a href="https://github.com/RodDalBen/SHINE_color" target ="_blank">https://github.com/RodDalBen/SHINE_color</a>
**Version:** 0.0.2
**Editor:** @ajstewartlang
**Reviewers:** @spitschan, @takuma929, @da5nsy
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/476db28d3743e31ff8a08ef3aa5b0dca/status.svg)](https://joss.theoj.org/papers/476db28d3743e31ff8a08ef3aa5b0dca)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/476db28d3743e31ff8a08ef3aa5b0dca"><img src="https://joss.theoj.org/papers/476db28d3743e31ff8a08ef3aa5b0dca/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/476db28d3743e31ff8a08ef3aa5b0dca/status.svg)](https://joss.theoj.org/papers/476db28d3743e31ff8a08ef3aa5b0dca)
```

**Author instructions**

Thanks for submitting your paper to JOSS @RodDalBen. **Currently, there isn't an JOSS editor assigned** to your paper.

@RodDalBen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.dcn.2019.100616 is OK
- 10.1080/15248372.2015.1135801 is OK
- 10.1038/nn.4615 is OK
- 10.3758/s13428-018-01193-y is OK
- 10.1111/desc.12281 is OK
- 10.1002/wcs.1323 is OK
- 10.1016/j.cognition.2021.104643 is OK
- 10.3758/BRM.42.3.671 is OK
- 10.1111/desc.12780 is OK
- 10.1177/2331216519887815 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (681.0 files/s, 62995.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                          24            194           1013           1077
TeX                              1              0              0            170
Markdown                         2             34              0             79
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            28            229           1017           1344
-------------------------------------------------------------------------------


Statistical information for the repository 'cb46c587b6aba063215cc532' was
gathered on 2021/06/25.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03401/joss.03401/10.21105.joss.03401.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03401/joss.03401/10.21105.joss.03401.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @ajstewartlang - I hope this isn't overloading you as you just start out, but this submission looks to be right up your alley. Could you edit this one? (Last ask for now, promise!)

**Comment by kyleniemeyer** [comment]
@whedon invite @ajstewartlang as editor

**Comment by whedon** [comment]
@ajstewartlang has been invited to edit this submission.

**Comment by ajstewartlang** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @ajstewartlang

**Comment by ajstewartlang** [comment]
@whedon assign @spitschan as reviewer

**Comment by whedon** [comment]
OK, @spitschan is now a reviewer

**Comment by ajstewartlang** [comment]
@whedon add @takuma929 as reviewer

**Comment by whedon** [comment]
OK, @takuma929 is now a reviewer

**Comment by ajstewartlang** [comment]
@whedon add @da5nsy as reviewer

**Comment by whedon** [comment]
OK, @da5nsy is now a reviewer

**Comment by ajstewartlang** [comment]
Many thanks @spitschan @takuma929 and @da5nsy for agreeing to review this submission - it's much appreciated - I'll open the review issue now...

**Comment by ajstewartlang** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3449.
