### ISSUE TITLE
[PRE REVIEW]: SIMSOPT: A flexible framework for stellarator optimization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3402]
**Submitting author:** @landreman (<a href="http://orcid.org/0000-0002-7233-577X">Matt Landreman</a>)
**Repository:** <a href="https://github.com/hiddenSymmetries/simsopt" target ="_blank">https://github.com/hiddenSymmetries/simsopt</a>
**Version:** v0.3.06
**Editor:** @dfm
**Reviewers:** @ZedThree, @StanczakDominik
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e77833c25c371a0845e24eee55188e16/status.svg)](https://joss.theoj.org/papers/e77833c25c371a0845e24eee55188e16)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e77833c25c371a0845e24eee55188e16"><img src="https://joss.theoj.org/papers/e77833c25c371a0845e24eee55188e16/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e77833c25c371a0845e24eee55188e16/status.svg)](https://joss.theoj.org/papers/e77833c25c371a0845e24eee55188e16)
```

**Author instructions**

Thanks for submitting your paper to JOSS @landreman. **Currently, there isn't an JOSS editor assigned** to your paper.

@landreman if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3402 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.22 s (912.2 files/s, 136176.7 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           99           3356           5207          11495
C/C++ Header                     31            430            202           2588
C++                              20            234             31           2518
reStructuredText                 20            490            359           1189
YAML                              8            167            185            648
SparForte                         5             12              0            629
Markdown                          5             59              1            172
INI                               1             10              0             81
Bourne Again Shell                8             45             73             78
CMake                             1             14             14             62
DOS Batch                         1              8              1             26
CSS                               2              2             12             24
make                              1              5              7             12
Bourne Shell                      1              0              2              3
TOML                              1              0              0              3
--------------------------------------------------------------------------------
SUM:                            204           4832           6094          19528
--------------------------------------------------------------------------------


Statistical information for the repository 'b399e0fa6dbe9b4fc3db916b' was
gathered on 2021/06/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrew Giuliani                 84          6965           4537           13.54
Bharat Kumar Medasan             8           117            286            0.47
Bharat Medasani                127         13490           2649           19.00
Caoxiang Zhu                     9           281             40            0.38
Elizabeth                        6          1083             84            1.37
Florian Wechsung               154         19068           8759           32.76
Matt Landreman                 139         13785           7993           25.64
Rogerio Jorge                   65          3110           1642            5.59
Zhisong Qu                       1             5              3            0.01
ejpaul                           5           649            402            1.24

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrew Giuliani            2378           34.1          2.2               12.99
Bharat Medasani            6169           45.7          3.0               17.41
Florian Wechsung           8672           45.5          2.5                4.59
Matt Landreman             6859           49.8          5.6               19.03
Rogerio Jorge              1984           63.8          1.6                9.63
Zhisong Qu                    2           40.0          5.3                0.00
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3402 with the following error: 
```
 [WARNING] Duplicate link reference '[//]' at line 65 column 1
Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.292 ...@umd.edu}{\nolinkurl{mattland@umd.edu}}}}

Looks like we failed to compile the PDF

```

**Comment by kyleniemeyer** [comment]
Hi @landreman, thanks for your submission to JOSS! It looks like there is a compilation error in your paper—I don't think we support a footnote in the author list like that (since that is YAML, not Markdown/LaTeX).

Unfortunately, we have extremely limited editor availability to handle submissions right now, and so we need to put your submission on our waitlist untill an appropriate editor becomes available. Thanks for your patience!

**Comment by landreman** [comment]
@whedon generate pdf from branch joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03402/joss.03402/10.21105.joss.03402.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03402/joss.03402/10.21105.joss.03402.pdf) :page_facing_up: :point_left:

**Comment by landreman** [comment]
Sorry about that compile error - it compiled fine using the Docker approach before we submitted. I fixed the error so it now compiles via whedon.

**Comment by arfon** [comment]
@whedon invite @dfm as editor

:wave: @dfm – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
@whedon assign me as editor

Sure - I'm happy to edit!

@landreman: let me know if you have any reviewer recommendations from [our main list of volunteers](https://bit.ly/joss-reviewers) or if there's anyone else who you think would be particularly well suited (include their github handle, but don't @ them because then they'll get inundated with notifications :D). I'll do a first pass of editing and start recruiting reviewers next week.

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by landreman** [comment]
@dfm thank you for serving as editor. For possible reviewers, you could look at the lead developers for https://github.com/boutproject/BOUT-dev/graphs/contributors (ZedThree, bendudson, d7919, ...) or https://github.com/bendudson/freegs/graphs/contributors or https://github.com/PlasmaPy/PlasmaPy/graphs/contributors (namurphy, StanczakDominik, ...). We could also look at the speakers at http://meetings.aps.org/Meeting/DPP20/Session/JM10 and http://meetings.aps.org/Meeting/DPP20/Session/NM10

**Comment by dfm** [comment]
@landreman: Just a quick update that I'm still working on recruiting reviewers and I'll keep you posted as I find them. Thanks for your patience!

**Comment by dfm** [comment]
@whedon assign @ZedThree as reviewer

@ZedThree has agreed to review this submission - thanks Peter! Please let me know if you have any questions as we progress.

I'm still working on finding a second reviewer and I'll get the review started as soon as we get our second volunteer. Thanks all for your patience!

**Comment by whedon** [comment]
OK, @ZedThree is now a reviewer

**Comment by dfm** [comment]
@whedon add @StanczakDominik as reviewer

Thanks Dominik for agreeing to be our second reviewer!

I'm going to start the review in a new thread so let's head over there to get started. Please let me know if any of you have issues or questions as we go.

**Comment by whedon** [comment]
OK, @StanczakDominik is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3525.
