### ISSUE TITLE
[PRE REVIEW]: caracas: Computer algebra in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3403]
**Submitting author:** @mikldk (<a href="http://orcid.org/0000-0002-0234-0266">Mikkel Meyer Andersen</a>)
**Repository:** <a href="https://github.com/r-cas/caracas" target ="_blank">https://github.com/r-cas/caracas</a>
**Version:** v1.1.1
**Editor:** @Nikoleta-v3
**Reviewers:** @EduPH, @MikeLydeamore
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974/status.svg)](https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974"><img src="https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974/status.svg)](https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mikldk. **Currently, there isn't an JOSS editor assigned** to your paper.

@mikldk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (1296.1 files/s, 259089.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            91           4519           1155          16491
R                               37            933           1679           2372
Markdown                         5            178              0            630
Rmd                              8            322            563            620
CSS                              4             99             48            431
JavaScript                       3             64             32            256
YAML                             3             23              8            192
TeX                              1              7              0             69
Python                           1             22              7             52
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                           154           6167           3493          21124
-------------------------------------------------------------------------------


Statistical information for the repository '82bddeb0ee27a9908c0290b1' was
gathered on 2021/06/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Mikkel Meyer Anderse             6           456             23          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mikkel Meyer Anderse        433           95.0          3.5                9.01
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01763 is OK
- 10.1007/3-540-45470-5_29 is OK
- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03403/joss.03403/10.21105.joss.03403.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03403/joss.03403/10.21105.joss.03403.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hey @mikldk - as you know we are slammed right now, so I have to put this on the waitlist until one of our math-y editors become available.

**Comment by kyleniemeyer** [comment]
@dpsanders Do you have bandwidth to edit this submission from @mikldk?

**Comment by mikldk** [comment]
Of course @kyleniemeyer :+1: .

Reviewer suggestions:

* MikeLydeamore
* EduPH
* trashbirdecology
* wrathematics

**Comment by arfon** [comment]
@whedon invite @Nikoleta-v3 as editor

:wave: @Nikoleta-v3 - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@Nikoleta-v3 has been invited to edit this submission.

**Comment by Nikoleta-v3** [comment]
👋🏻 @arfon Yes, I am happy to be the editor for this submission.

**Comment by Nikoleta-v3** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Nikoleta-v3

**Comment by Nikoleta-v3** [comment]
:wave:  @MikeLydeamore &  @EduPH & @trashbirdecology & @wrathematics, I'm pinging you to ask if you would be able to assist with reviewing this submissions to JOSS? 

The submission I'd like you to review is titled: "Computer algebra in R". You can find more information at the top of this Github issue, and as a reminder the guidelines can be found at https://joss.readthedocs.io/en/latest/review_criteria.html

Please let me know if you're available :smile: Thank you!

**Comment by EduPH** [comment]
Yes, I am available :)

**Comment by Nikoleta-v3** [comment]
Thank you @EduPH 😄 🙏🏻

**Comment by Nikoleta-v3** [comment]
@whedon assign @EduPH as reviewer

**Comment by whedon** [comment]
OK, @EduPH is now a reviewer

**Comment by MikeLydeamore** [comment]
I am also available.

**Comment by Nikoleta-v3** [comment]
@whedon add @MikeLydeamore as reviewer

**Comment by whedon** [comment]
OK, @MikeLydeamore is now a reviewer

**Comment by Nikoleta-v3** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3438.

**Comment by Nikoleta-v3** [comment]
@EduPH and @MikeLydeamore thank you again both for agreeing to review! 

The review will now be taking place on #3438, there are details there with next steps but please ping me if I can answer any questions you might have.

**Comment by trashbirdecology** [comment]
Looks like you've found reviewers. Apologies for lack of response was on leave. Good luck!

**Comment by Nikoleta-v3** [comment]
No problem at all @trashbirdecology 😄 Thank you for getting back to me.
