### ISSUE TITLE
[PRE REVIEW]: bfit: A Python Application For Beta-Detected NMR

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3405]
**Submitting author:** @dfujim (<a href="http://orcid.org/0000-0003-2847-2053">Derek Fujimoto</a>)
**Repository:** <a href="https://github.com/dfujim/bfit" target ="_blank">https://github.com/dfujim/bfit</a>
**Version:** v4.9.1
**Editor:** @lucydot
**Reviewers:** @nicksisco1932
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2/status.svg)](https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2"><img src="https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2/status.svg)](https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dfujim. **Currently, there isn't an JOSS editor assigned** to your paper.

@dfujim if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3405 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (66d36d9d04c0274c38dccbc8/paper/paper.md): mapping values are not allowed in this context at line 4 column 26 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (534.8 files/s, 130843.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          66           3649           3579          10681
C/C++ Header                     3             42            120            514
Markdown                         5             73              0            245
TeX                              2             33              6            153
Cython                           1             28             56             64
C++                              1              9             12             34
YAML                             1              5              2             24
-------------------------------------------------------------------------------
SUM:                            79           3839           3775          11715
-------------------------------------------------------------------------------


Statistical information for the repository 'b7d2154d09d333d8518ff347' was
gathered on 2021/06/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Derek Fujimoto                 869         30005          11785           98.69
Ryan M. L. McFadden              4           136             12            0.35
β-NMR Group                      4           351             55            0.96

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Derek Fujimoto            18246           60.8         15.2               15.10
Ryan M. L. McFadden         120           88.2          3.6               20.83
β-NMR Group                 274           78.1          8.5               17.15
```

**Comment by kyleniemeyer** [comment]
Hi @dfujim, thanks for your submission to JOSS. 

Unfortunately, we have extremely limited editor availability to handle submissions right now, and so we need to put your submission on our waitlist untill an appropriate editor becomes available. Thanks for your patience!

**Comment by kyleniemeyer** [comment]
In the meantime, it looks like your paper ran into some compilation errors. I think you might need to remove the comments from the file, I don't know if our parser can handle those.

**Comment by dfujim** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03405/joss.03405/10.21105.joss.03405.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03405/joss.03405/10.21105.joss.03405.pdf) :page_facing_up: :point_left:

**Comment by dfujim** [comment]
@kyleniemeyer ok strange it was the comments thing. The [preview service](https://whedon.theoj.org/) handles them just fine.

**Comment by kthyng** [comment]
Is this close enough to your wheelhouse @pdebuyl?

**Comment by kthyng** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by pdebuyl** [comment]
Hi @kthyng I'll be off until begin august. I also fear that it will be difficult for me to find reviewers, as it is out of my typical areas, so I'd prefer to skip this submission if someone else is available. Else, I can pick it up in august.

**Comment by kthyng** [comment]
Fair enough @pdebuyl. I think I saw another submission you'd be a good fit for in which case I'll invite you there. You could put up an [ooo](https://joss.readthedocs.io/en/latest/editing.html#out-of-office) for the time you'll be out if you'd like to, also.

**Comment by kthyng** [comment]
Hi @rkurchin and welcome to JOSS! Are you interested in taking on this submission?

**Comment by kthyng** [comment]
@whedon invite @rkurchin as editor

**Comment by whedon** [comment]
@rkurchin has been invited to edit this submission.

**Comment by rkurchin** [comment]
Willing to give it a go, but I don't really know anything about NMR or that particular characterization community, so I wouldn't be able to do a great job of suggesting reviewers if obvious candidates from the list can't do it. I'll leave it up to you, feel free to assign me if you think it's the best fit.

**Comment by kthyng** [comment]
Ok understandable! We will keep this submission on the waitlist for now. Thanks @rkurchin.

**Comment by danielskatz** [comment]
👋 @meg-simula - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by danielskatz** [comment]
👋 @lucydot - Would this be something you could edit as your first JOSS editing assignment?

**Comment by danielskatz** [comment]
@whedon invite @lucydot as editor

If so, you can use `@whedon assign me as editor` to assign yourself, or let us know if not

**Comment by whedon** [comment]
@lucydot has been invited to edit this submission.

**Comment by lucydot** [comment]
Hi @danielskatz I'm happy to try, though I am not familiar with subject area. Looking at the conversation above it may not fit neatly into any editors area of expertise - if this is the case I'm happy to take it on and do my best to find suitable reviewers.

**Comment by danielskatz** [comment]
@lucydot - great - please go ahead, and feel free to chat with me and others on slack if you need help with reviewers

**Comment by lucydot** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by lucydot** [comment]
@whedon assign @lucydot as editor

**Comment by whedon** [comment]
OK, the editor is @lucydot

**Comment by lucydot** [comment]
@whedon check repository

**Comment by lucydot** [comment]
Hi @dfujim I'll be your editor for this submission 👋 

If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list ](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822)of people have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by whedon** [comment]
Wordcount for `paper.md` is 876

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.24 s (325.5 files/s, 80929.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          66           3722           3624          10887
C/C++ Header                     3             42            120            514
Markdown                         5             70              0            238
TeX                              2             33              6            153
Cython                           1             28             56             64
C++                              1              9             12             34
YAML                             1              5              2             24
-------------------------------------------------------------------------------
SUM:                            79           3909           3820          11914
-------------------------------------------------------------------------------


Statistical information for the repository 'fd6a5214b58d0c10d56958c4' was
gathered on 2021/07/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Derek Fujimoto                 905         30523          11979           98.71
Ryan M. L. McFadden              4           136             12            0.34
β-NMR Group                      4           351             55            0.94

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Derek Fujimoto            18570           60.8         16.1               15.04
Ryan M. L. McFadden         120           88.2          5.1               20.83
β-NMR Group                 274           78.1         10.0               17.15
```

**Comment by nicksisco1932** [comment]
Yes, looks interesting.

**Comment by dfujim** [comment]
@lucydot Standouts from the end of the list include villaa (Nuclear Physics, Particle Physics) and benjaminbolling (materials chemistry, physics). 

Our experiment is somewhat unique in that we are investigating material properties with an NMR probe, but we do so with particle/nuclear physics methods. The technique is similar to muon spin rotation, but much less common. Apart from our lab, I think only [ISOLDE](https://isolde.cern/) is actively conducting implanted-ion beta-NMR experiments. 

That being said, I don't think you actually need all too much topic-specific knowledge to review the software. Since our experiments cover a wide range of topics (superconductivity, soft matter, biological processes, battery materials, heterostructures, etc), the software is very general purpose to accommodate each experiment and is mostly concerned with basic data analysis.

**Comment by jpata** [comment]
> @jpata would you be able to review given your experience with data pipelines for large experimental collaborations?

@lucydot I can review this paper, I will look at it this week.

**Comment by lucydot** [comment]
Hi @dfujim thanks for adding some useful context to the discussion. @jpata and @nicksisco1932 thanks for accepting the invitation to review 🎈 

@whedon assign @jpata as reviewer
@whedon assign @nicksisco1932 as reviewer

@whedon start review

**Comment by whedon** [comment]
OK, @jpata is now a reviewer

**Comment by lucydot** [comment]
@whedon assign @nicksisco1932 as reviewer

**Comment by whedon** [comment]
OK, @nicksisco1932 is now a reviewer

**Comment by lucydot** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3598.
