### ISSUE TITLE
[PRE REVIEW]: pytreegrav: a fast Python gravity solver

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3406]
**Submitting author:** @mikegrudic (<a href="http://orcid.org/0000-0002-1655-5604">Michael Grudi´c</a>)
**Repository:** <a href="https://github.com/mikegrudic/pytreegrav" target ="_blank">https://github.com/mikegrudic/pytreegrav</a>
**Version:** 0.23
**Editor:** @dfm
**Reviewers:** @adrn, @maxwelltsai
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99/status.svg)](https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99"><img src="https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99/status.svg)](https://joss.theoj.org/papers/8345d6e5664943ae019a0d80a5eece99)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mikegrudic. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dfm.

@mikegrudic if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (616.2 files/s, 80187.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          10            174            259            857
TeX                              1             27              0            263
Markdown                         2             65              0            143
Jupyter Notebook                 1              0            237             50
TOML                             1              0              0              6
YAML                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            16            266            496           1320
-------------------------------------------------------------------------------


Statistical information for the repository '5e2ee44121e109444e4a943b' was
gathered on 2021/06/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex Gurvich                     6           848            553           26.76
Ben Keller                       4            33             16            0.94
Michael Grudic                  10           499             59           10.66
Mike Grudic                     22          1633           1156           53.27
Mike Grudić                      7           250            187            8.35
omgspace                         1             0              2            0.04

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alex Gurvich                124           14.6          0.5                8.87
Ben Keller                   18           54.5          0.1                0.00
Michael Grudic               45            9.0         46.0                0.00
Mike Grudic                1098           67.2          0.4                5.83
Mike Grudić                   5            2.0         19.7               20.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2833157.2833162 is OK
- 10.1016/S1384-1076(96)00009-7 is OK
- 10.1093/mnras/staa2578 is OK
- 10.1006/jcph.1994.1050 is OK
- 10.1093/mnras/71.5.460 is OK
- 10.1088/0004-637X/762/2/109 is OK
- 10.1093/mnras/sty2303 is OK
- 10.1093/mnras/stz3527 is OK
- 10.1046/j.1365-8711.1999.02613.x is OK
- 10.1093/mnras/stv195 is OK
- 10.1111/j.1365-2966.2005.09655.x is OK
- 10.1093/mnras/stu1421 is OK
- 10.1093/mnras/sty1690 is OK
- 10.1140/epjp/i2011-11055-3 is OK
- 10.1038/324446a0 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03406/joss.03406/10.21105.joss.03406.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03406/joss.03406/10.21105.joss.03406.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @mikegrudic, thanks for your interest in JOSS. 

Unfortunately, we have extremely limited editor availability to handle submissions right now, and so we need to put your submission on our waitlist untill an appropriate editor becomes available. Thanks for your patience!

**Comment by kthyng** [comment]
Hi @dfm would this be a good fit for you?

**Comment by kthyng** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
@whedon assign me as editor

Sure - I'm happy to edit! I'm a bit behind on things so I'll take a first pass of the paper and repo around the middle of next week, and then start recruiting reviewers.

In the meantime, @mikegrudic, let me know if you have any reviewer recommendations from our [main list of volunteers](https://bit.ly/joss-reviewers) or if there's anyone else who you think would be particularly well suited (include their github handle, but don't @ them because then they'll get inundated with notifications :D).

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by mikegrudic** [comment]
ngoldbaum and 

> @whedon assign me as editor
> 
> Sure - I'm happy to edit! I'm a bit behind on things so I'll take a first pass of the paper and repo around the middle of next week, and then start recruiting reviewers.
> 
> In the meantime, @mikegrudic, let me know if you have any reviewer recommendations from our [main list of volunteers](https://bit.ly/joss-reviewers) or if there's anyone else who you think would be particularly well suited (include their github handle, but don't @ them because then they'll get inundated with notifications :D).

Thanks! On the list, some potential reviewers I see who would likely be knowledgeable about the algorithms and applications of the package would be ngoldbaum and zingale.

**Comment by dfm** [comment]
@mikegrudic: I wanted to drop a line here to let you know that I'm still working on recruiting reviewers. It's going a little slower than usual (probably because it's August!) but I'll keep you posted. Thanks for your patience!

**Comment by mikegrudic** [comment]
OK thanks np!

**Comment by dfm** [comment]
@whedon add @adrn as reviewer

@adrn has agreed to review - thanks Adrian! I'm still working on recruiting a second, hopefully soon. I'll keep you all posted and then we'll start the review process as soon as I have a second reviewer assigned.

**Comment by whedon** [comment]
OK, @adrn is now a reviewer

**Comment by dfm** [comment]
@whedon add @maxwelltsai as reviewer

Maxwell with be our second reviewer - thanks!!

I'll start the review now and share more info in the main review thread. Please let me know if you have any questions as the review progresses.

**Comment by whedon** [comment]
OK, @maxwelltsai is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3675.
