### ISSUE TITLE
[PRE REVIEW]: DRT: A rapid coastal foredune evolution prediction tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3407]
**Submitting author:** @ncohn (<a href="http://orcid.org/0000-0003-4287-039X">Nicholas Cohn</a>)
**Repository:** <a href="https://github.com/erdc/dune-response-tool/" target ="_blank">https://github.com/erdc/dune-response-tool/</a>
**Version:** v1.0
**Editor:** @kbarnhart
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3706f536a589ae8af681d1d3eb4da76c/status.svg)](https://joss.theoj.org/papers/3706f536a589ae8af681d1d3eb4da76c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3706f536a589ae8af681d1d3eb4da76c"><img src="https://joss.theoj.org/papers/3706f536a589ae8af681d1d3eb4da76c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3706f536a589ae8af681d1d3eb4da76c/status.svg)](https://joss.theoj.org/papers/3706f536a589ae8af681d1d3eb4da76c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ncohn. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kbarnhart.

@ncohn if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (552.4 files/s, 70583.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                           6            260            363            978
Markdown                         2             24              0             69
TeX                              1              6              0             57
XML                              5              0              0             32
-------------------------------------------------------------------------------
SUM:                            14            290            363           1136
-------------------------------------------------------------------------------


Statistical information for the repository '9afc2f07fca371b850de8bb8' was
gathered on 2021/06/25.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2112/jcoastres-d-13-00178.1 is OK
- 10.1016/j.coastaleng.2011.09.003 is OK
- 10.5066/F7GF0S0Z is OK

MISSING DOIs

- 10.3133/ofr20141088 may be a valid DOI for title: Hurricane Sandy: observations and analysis of coastal change

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03407/joss.03407/10.21105.joss.03407.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03407/joss.03407/10.21105.joss.03407.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @kbarnhart as editor

Hi @kbarnhart, do you have the bandwidth to edit this submission?

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by ncohn** [comment]
Github handles for possible reviewers:
ciarletd
csherwood-usgs
KristenSplinter
bartvanwesten
conlin-matt
Sierd

**Comment by kbarnhart** [comment]
@kyleniemeyer can do. 

@ncohn it will probably be in the middle of next week when I start actively handling this.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
@ncohn Thanks for your submission to JOSS. I’ve done an initial review of the software and consulted with the rest of the editorial board. Based on this initial review my decision is to reject the submission with a recommendation to resubmit after the following issues have been considered and addressed:

1. The software lacks documentation besides the text in the GUI itself. Documentation should be provided for both the GUI and the core scripts and reflect both the standard and advanced model attributes. See [this section](https://joss.readthedocs.io/en/latest/review_criteria.html#documentation) of the JOSS documentation on the extent of documentation expected. 
2. No description of how the software can be tested is provided. Documentation should indicate how to verify the software is working correctly. Such tests might include, but not necessarily be limited to, verification that the considered morphodynamic models are implemented correctly. 
3. Installation instructions are insufficient. Provide information to support a user who does not know how to install a Matlab application. Additionally, my attempt to install the application indicated a path error for the dependency .xlsx files. This may have been user error (this was the first time I’ve installed a Matlab App, but instructions for such a user should be provided).
4. It is not clear this application is designed for maintainable extension. Is the package designed to support extension to include, for example, additional morphodynamic models for erosion and accretion beyond the two included?
5. Many parameter values are hard coded into the provided scripts (for example, in the erosion, accretion, and gridding scripts). Where appropriate these inputs should be user-defined, or at a minimum documented. While it is of course reasonable to provide defaults for most of these parameters, providing a complete programmatic API which exposes these parameters is important for extensibility. 
6. Other key elements required by JOSS are missing. For example, no community guidelines are provided. As per the JOSS documentation, please review the [Review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html) in advance of resubmitting.

If you have any questions or clarifications, feel free to follow up here or directly at krbarnhart@usgs.gov

**Comment by kbarnhart** [comment]
@openjournals/joss-eics: I've recommended that this submission be rejected.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by ncohn** [comment]
Thanks for looking at this initial submission @kbarnhart. We had tested on
numerous internal computers ahead of time, but looks like there is a
pathing issue related to the .xlsx file we'll almost certainly have to
resolve that went unnoticed. As for the other items, sorry if there was
confusion on our part that was required. We will correct accordingly if we
decide to resubmit to JOSS. Really appreciate all your detailed feedback on
this!
Regards,
Nick

**Comment by kbarnhart** [comment]
@ncohn glad the feedback was helpful. Looking forward to seeing this resubmitted. It looks to be a great tool and a valuable contribution. If you have any questions or clarifications as you prepare to resubmit, feel free to discuss here or open a pre-submission inquiry [here](https://github.com/openjournals/joss/issues/new?title=Pre-submission%20enquiry) and tag me.
