### ISSUE TITLE
[PRE REVIEW]: mol-ellipsize: A Python package for molecular size calculation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3408]
**Submitting author:** @andrewtarzia (<a href="http://orcid.org/0000-0001-8797-8666">Andrew Tarzia</a>)
**Repository:** <a href="https://github.com/andrewtarzia/mol-ellipsize" target ="_blank">https://github.com/andrewtarzia/mol-ellipsize</a>
**Version:** 1.0.1
**Editor:** @jmschrei
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/de074e370c1bc741e5ef59207641cbe3/status.svg)](https://joss.theoj.org/papers/de074e370c1bc741e5ef59207641cbe3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/de074e370c1bc741e5ef59207641cbe3"><img src="https://joss.theoj.org/papers/de074e370c1bc741e5ef59207641cbe3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/de074e370c1bc741e5ef59207641cbe3/status.svg)](https://joss.theoj.org/papers/de074e370c1bc741e5ef59207641cbe3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @andrewtarzia. **Currently, there isn't an JOSS editor assigned** to your paper.

@andrewtarzia if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.47 s (487.6 files/s, 1610.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            184            181            744
JSON                           701              0              0            704
TeX                              1             23              0            232
YAML                             2              1              4            110
Markdown                         1             25              0             82
reStructuredText                 1             25             21             35
-------------------------------------------------------------------------------
SUM:                           718            258            206           1907
-------------------------------------------------------------------------------


Statistical information for the repository 'f5544efb87af5c36d78f020f' was
gathered on 2021/06/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrew Tarzia                   15          1188            231          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrew Tarzia              1109           93.4         -0.4                6.76
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.micromeso.2012.06.031 is OK
- 10.1093/nar/28.1.27 is OK
- 10.1093/nar/gkv1070 is OK
- 10.1093/nar/gkw1092 is OK
- 10.1021/jacs.5b08746 is OK
- 10.1016/j.desal.2016.02.005 is OK
- 10.1039/B802426J is OK
- 10.1038/ncomms8240 is OK
- 10.1021/jz300855a is OK
- 10.1021/jz402019d is OK
- 10.1021/ja973906m is OK
- 10.1021/acs.jcim.5b00654 is OK
- 10.1002/047002903X.ch1 is OK
- 10.1021/acs.nanolett.9b02730 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03408/joss.03408/10.21105.joss.03408.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03408/joss.03408/10.21105.joss.03408.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @andrewtarzia, thanks for your interest in JOSS. 

Unfortunately, we have extremely limited editor availability to handle submissions right now, and so we need to put your submission on our waitlist untill an appropriate editor becomes available. Thanks for your patience!

**Comment by jmschrei** [comment]
@assign me as editor

**Comment by jmschrei** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jmschrei

**Comment by jmschrei** [comment]
Howdy, I'll be serving as the editor for this submission. Let's grab some reviewers!

**Comment by jmschrei** [comment]
Hi @bjmorgan and @richardjgowers, would either of you be able to serve as a reviewer for this submission?

**Comment by bjmorgan** [comment]
@jmschrei Afraid I won't have time to review this at present.

**Comment by richardjgowers** [comment]
@jmschrei yeah sure

**Comment by richardjgowers** [comment]
@jmschrei from quickly looking through the package, it seems a little light, I think maybe a scope check would be a good idea

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@andrewtarzia – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime in the next couple of weeks.

**Comment by danielskatz** [comment]
@andrewtarzia - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by andrewtarzia** [comment]
That's disappointing. Is it possible to get further information into the decision?

**Comment by andrewtarzia** [comment]
@danielskatz

**Comment by danielskatz** [comment]
We examined the amount of code and number of commits and development time, etc. - the items under https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort
