### ISSUE TITLE
[PRE REVIEW]: RHRT: An R package to assess Heart Rate Turbulence

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3409]
**Submitting author:** @VBlesius (<a href="http://orcid.org/0000-0002-2391-242X">Valeria Blesius</a>)
**Repository:** <a href="https://github.com/VBlesius/RHRT" target ="_blank">https://github.com/VBlesius/RHRT</a>
**Version:** 1.0
**Editor:** @bmcfee
**Reviewers:** @brunaw, @rrrlw
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4800b5bdbe2b9a090e4fbd7def7fa45e/status.svg)](https://joss.theoj.org/papers/4800b5bdbe2b9a090e4fbd7def7fa45e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4800b5bdbe2b9a090e4fbd7def7fa45e"><img src="https://joss.theoj.org/papers/4800b5bdbe2b9a090e4fbd7def7fa45e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4800b5bdbe2b9a090e4fbd7def7fa45e/status.svg)](https://joss.theoj.org/papers/4800b5bdbe2b9a090e4fbd7def7fa45e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @VBlesius. **Currently, there isn't an JOSS editor assigned** to your paper.

@VBlesius if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (874.1 files/s, 108736.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               16            151            586            864
HTML                             1             34              2            408
Markdown                         4            172              4            396
TeX                              1              5              0             93
Rmd                              2            110            223             39
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            25            473            819           1818
-------------------------------------------------------------------------------


Statistical information for the repository '037f6511f3de6b85e5d82340' was
gathered on 2021/06/25.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #3409 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
Hi @VBlesius, thanks for your interest in JOSS!

Unfortunately, we have extremely limited editor availability to handle submissions right now, and so we need to put your submission on our waitlist untill an appropriate editor becomes available. Thanks for your patience!

Also, I think you need to change your paper and ref filenames to `paper.md` and `paper.bib` for our bot to find it.

**Comment by VBlesius** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03409/joss.03409/10.21105.joss.03409.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03409/joss.03409/10.21105.joss.03409.pdf) :page_facing_up: :point_left:

**Comment by VBlesius** [comment]
Unfortunately there don't seem to be reviewers that use R with a focus on health informatics / cardiology. The reviewers with the closest research interests could be:
    - shahmoradi
    - Path2Genome
    - carleshf
    - sachsmc
    - rrrlw
    - Suresh-lab
    - Gweissman
    - darokun
    - stensy
    - acolum
    - Rmadillo
    - Jminnier
    - pacoramon
    - peterakirk

**Comment by kthyng** [comment]
Hi @bmcfee! Are you interested in taking on this submission? I thought you may have relevant expertise from the signal processing side.

**Comment by kthyng** [comment]
@whedon invite @bmcfee as editor

**Comment by whedon** [comment]
@bmcfee has been invited to edit this submission.

**Comment by bmcfee** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
OK, the editor is @bmcfee

**Comment by bmcfee** [comment]
@kthyng Sure thing, will be on it tomorrow AM.

**Comment by bmcfee** [comment]
@VBlesius :wave: I'm tracking down editors now.  Meanwhile, I've noticed that the repo doesn't have explicit license file (see [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html#general-checks)), though GPLv2 is noted in the readme.  Otherwise, everything seems to be in good shape.

**Comment by bmcfee** [comment]
@whedon add @brunaw as reviewer

**Comment by whedon** [comment]
OK, @brunaw is now a reviewer

**Comment by VBlesius** [comment]
Hi @bmcfee !

> I'm tracking down reviewers now.
Thanks a lot!

> Meanwhile, I've noticed that the repo doesn't have explicit license file (see [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html#general-checks)), though GPLv2 is noted in the readme.
Right, thank you for the hint! I have added a licence file to the repo.

**Comment by bmcfee** [comment]
@whedon add @rrrlw as reviewer

**Comment by bmcfee** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3540.
