### ISSUE TITLE
[PRE REVIEW]: The MarINvaders Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3410]
**Submitting author:** @rlonka (<a href="http://orcid.org/0000-0002-5815-8682">Radek Lonka</a>)
**Repository:** <a href="https://gitlab.com/marinvaders/marinvaders" target ="_blank">https://gitlab.com/marinvaders/marinvaders</a>
**Version:** v0.3.1
**Editor:** @osorensen
**Reviewers:** @callumrollo, @ethanwhite
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b/status.svg)](https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b"><img src="https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b/status.svg)](https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b)
```

**Author instructions**

Thanks for submitting your paper to JOSS @rlonka. **Currently, there isn't an JOSS editor assigned** to your paper.

@rlonka if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3391/ai.2014.9.4.01 is OK
- 10.3389/fmars.2014.00032 is OK
- 10.1890/070064 is OK
- 10.1038/ncomms14435 is OK
- 10.1111/gcb.15333 is OK
- 10.1641/B570707 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (309.8 files/s, 43886.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          11            315            513           1128
Markdown                        11            281              0            491
XML                              3              1              0            300
TeX                              1             12              0            136
YAML                             3             13              0            118
Jupyter Notebook                 1              0            922             20
-------------------------------------------------------------------------------
SUM:                            30            622           1435           2193
-------------------------------------------------------------------------------


Statistical information for the repository 'c52ad20fe25147e6a2ad35b8' was
gathered on 2021/06/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Konstantin Stadler              66          2655           2016           21.04
Radek Lonka                    138         12329           5201           78.95
Radek lonka                      1             1              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Konstantin Stadler         1121           42.2          1.7                4.28
Radek Lonka                 835            6.8          5.4               13.89
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03410/joss.03410/10.21105.joss.03410.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03410/joss.03410/10.21105.joss.03410.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @rlonka, thanks for your interest in JOSS! 

Unfortunately, we have extremely limited editor availability to handle submissions right now, and so we need to put your submission on our waitlist untill an appropriate editor becomes available. Thanks for your patience!

**Comment by Kevin-Mattheus-Moerman** [comment]
@marcosvital @KristinaRiemer both of you seem at capacity at the moment but let me know if you can take this on as editor once you are available. Thanks.

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03410/joss.03410/10.21105.joss.03410.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03410/joss.03410/10.21105.joss.03410.pdf) :page_facing_up: :point_left:

**Comment by osorensen** [comment]
@rlonka, I'm now the editor for this submission. If you know of any potential reviewers, could you please state their GitHub usernames in this thread (without the leading @ before the username)?

**Comment by osorensen** [comment]
@callumrollo, @alesarrett, @molgor, @ethanwhite, @giskid, @evaristor, would any of you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by callumrollo** [comment]
@osorensen I'm happy to review this

**Comment by osorensen** [comment]
@whedon add @callumrollo as reviewer

**Comment by whedon** [comment]
OK, @callumrollo is now a reviewer

**Comment by ethanwhite** [comment]
@osorensen I'm happy to review this

**Comment by osorensen** [comment]
@whedon add @ethanwhite as reviewer

**Comment by whedon** [comment]
OK, @ethanwhite is now a reviewer

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3575.
