### ISSUE TITLE
[PRE REVIEW]: rfasst: An R tool to estimate air pollution impacts on health and agriculture

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3411]
**Submitting author:** @jonsampedro (<a href="http://orcid.org/0000-0002-2277-1530">Jon Sampedro</a>)
**Repository:** <a href="https://github.com/JGCRI/rfasst" target ="_blank">https://github.com/JGCRI/rfasst</a>
**Version:** v1.1
**Editor:** @dhhagan
**Reviewers:** @nanhung, @ibarraespinosa
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d/status.svg)](https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d"><img src="https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d/status.svg)](https://joss.theoj.org/papers/5929b37e7cba14d15a73639ac949059d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jonsampedro. **Currently, there isn't an JOSS editor assigned** to your paper.

@jonsampedro if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (473.0 files/s, 144700.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               14           1589           2343           3742
Markdown                         4             63              0            191
XML                              1             11              0            189
Rmd                              4            161            193            136
YAML                             5             27              1            122
TeX                              1             10              0             93
-------------------------------------------------------------------------------
SUM:                            29           1861           2537           4473
-------------------------------------------------------------------------------


Statistical information for the repository '2e30e49c6506ba90686739e3' was
gathered on 2021/06/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Zarrar Khan                      2             0            848           56.80
samp699                          2           645              0           43.20

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03411/joss.03411/10.21105.joss.03411.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03411/joss.03411/10.21105.joss.03411.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5194/gmd-12-677-2019 is OK

MISSING DOIs

- 10.1016/j.envint.2020.105513 may be a valid DOI for title: Health co-benefits and mitigation costs as per the Paris Agreement under different technological pathways for energy supply
- 10.1016/s2542-5196(18)30029-9 may be a valid DOI for title: Health co-benefits from air pollution and mitigation costs of the Paris Agreement: a modelling study
- 10.1002/essoar.10501661.1 may be a valid DOI for title: Future impacts of ozone driven damages on agricultural systems
- 10.2172/1036082 may be a valid DOI for title: GCAM 3.0 agriculture and land use: data sources and methods
- 10.1016/j.atmosenv.2008.10.033 may be a valid DOI for title: The global impact of ozone on agricultural crop yields under current and future air quality legislation
- 10.5194/gmd-12-1443-2019 may be a valid DOI for title: Global emissions pathways under different socioeconomic scenarios for use in CMIP6: a dataset of harmonized emissions trajectories through the end of the century

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @jonsampedro, thanks for your interest in JOSS!

Unfortunately, we have extremely limited editor availability to handle submissions right now, and so we need to put your submission on our waitlist untill an appropriate editor becomes available. Thanks for your patience!

Also, it looks like some references in your paper may be missing some DOIs—could you add those?

**Comment by jonsampedro** [comment]
Hello @kyleniemeyer, no problem, thanks for the quick response! 

I have added the missing DOIs to the paper. Thanks!

**Comment by arfon** [comment]
@whedon invite @dhhagan as editor

:wave: @dhhagan – as it looks like https://github.com/openjournals/joss-reviews/issues/3224#issuecomment-869559410 is about to wrap up 🎉, would you be willing to edit this submission for us?

**Comment by whedon** [comment]
@dhhagan has been invited to edit this submission.

**Comment by dhhagan** [comment]
@arfon sure thing.

**Comment by dhhagan** [comment]
@whedon assign @dhhagan as editor

**Comment by whedon** [comment]
OK, the editor is @dhhagan

**Comment by dhhagan** [comment]
Hi @jonsampedro - Everything looks in line, so I am going to start looking for reviewers. I will let you know as soon as I've found a couple and we will kick this process off!

**Comment by jonsampedro** [comment]
Perfect @dhhagan , thank you.

**Comment by dhhagan** [comment]
👋  @richardsc, @PharaohCola13, @molgor, @nanhung : are any of you currently available and interested in reviewing this paper?

**Comment by nanhung** [comment]
Hi @dhhagan - Yes, I can do this.

**Comment by dhhagan** [comment]
@nanhung awesome! I will add you as a reviewer now.

**Comment by dhhagan** [comment]
@whedon add @nanhung as a reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by dhhagan** [comment]
@whedon assign @nanhung as reviewer

**Comment by whedon** [comment]
OK, @nanhung is now a reviewer

**Comment by dhhagan** [comment]
Hey @samjsilva91 - do you have time for this review or know any other AQ R users that would be a good fit? Thanks!

**Comment by samjsilva91** [comment]
Hi @dhhagan, I have an institutional conflict with JCGRI. Sorry!

**Comment by jonsampedro** [comment]
Hello @dhhagan , I just wanted to check the status of this review. Thanks!

**Comment by dhhagan** [comment]
👋  @ibarraespinosa @meenakshi-kushwaha are either of you free/interested in reviewing this manuscript? Thanks!

**Comment by ibarraespinosa** [comment]
Cool Cool! I will make a fair review and not be guided by the infamous [reviewer 2](https://twitter.com/grumpyreviewer2?lang=pt).
