### ISSUE TITLE
[PRE REVIEW]: robomit: Robustness Checks for Omitted Variable Bias

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3413]
**Submitting author:** @seschaub (<a href="http://orcid.org/0000-0001-8477-3737">Sergei Schaub</a>)
**Repository:** <a href="https://github.com/seschaub/robomit" target ="_blank">https://github.com/seschaub/robomit</a>
**Version:** 1.0.6
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c70b004f43b40981378a475550268835/status.svg)](https://joss.theoj.org/papers/c70b004f43b40981378a475550268835)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c70b004f43b40981378a475550268835"><img src="https://joss.theoj.org/papers/c70b004f43b40981378a475550268835/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c70b004f43b40981378a475550268835/status.svg)](https://joss.theoj.org/papers/c70b004f43b40981378a475550268835)
```

**Author instructions**

Thanks for submitting your paper to JOSS @seschaub. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @sbenthall.

@seschaub if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (465.2 files/s, 156059.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                3            298            768            579
TeX                              1             21              0             95
Rmd                              1             56            123             57
Markdown                         1              5              0             11
-------------------------------------------------------------------------------
SUM:                             6            380            891            742
-------------------------------------------------------------------------------


Statistical information for the repository 'cdf464ffbd4eb4663dce47dd' was
gathered on 2021/06/25.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3413 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
Hi @seschaub, thanks for your interest in JOSS. 

Due to the relatively small size of your submission, the editorial board is going to review this to see if it meets our requirements for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
PDF failed to compile for issue #3413 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by danielskatz** [comment]
👋 @seschaub - We're going to reject this submission for a couple of reasons:
1. There is no paper - see https://joss.readthedocs.io/en/latest/submitting.html#typical-paper-submission-flow
2. The work does not appear to meet the [JOSS Substantial scholarly effort criteria](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) - it's quite small and only has a small number of commits over a very short period

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
