### ISSUE TITLE
[PRE REVIEW]: daiR: an R package for OCR with Google Document AI

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3420]
**Submitting author:** @Hegghammer (<a href="http://orcid.org/0000-0001-6253-1518">Thomas Hegghammer</a>)
**Repository:** <a href="https://github.com/Hegghammer/daiR" target ="_blank">https://github.com/Hegghammer/daiR</a>
**Version:** v.0.9.1
**Editor:** @Nikoleta-v3
**Reviewers:** @cjbarrie , @shivam11
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b627ff1a4da50b1103c6eb5e0042cefd/status.svg)](https://joss.theoj.org/papers/b627ff1a4da50b1103c6eb5e0042cefd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b627ff1a4da50b1103c6eb5e0042cefd"><img src="https://joss.theoj.org/papers/b627ff1a4da50b1103c6eb5e0042cefd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b627ff1a4da50b1103c6eb5e0042cefd/status.svg)](https://joss.theoj.org/papers/b627ff1a4da50b1103c6eb5e0042cefd)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Hegghammer. **Currently, there isn't an JOSS editor assigned** to your paper.

@Hegghammer if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.29 s (138.6 files/s, 18284.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               15            681            820           2061
Markdown                         5             89              0            266
YAML                             5             34              2            247
Rmd                              6            287            483            216
TeX                              1              9              0             70
JSON                             7              0              0              7
CSS                              1              0              0              6
-------------------------------------------------------------------------------
SUM:                            40           1100           1305           2873
-------------------------------------------------------------------------------


Statistical information for the repository '4ee84c294e8b936d92361ba5' was
gathered on 2021/06/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
hegghammer                       2           484            484          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3420 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:204:in `block in parse_authors': Author (Thomas Hegghammer) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.31235/osf.io/6zfvs may be a valid DOI for title: OCR with Tesseract, Amazon Textract, and Google Document AI: A Benchmarking Experiment
- 10.33011/computel.v1i.345 may be a valid DOI for title: OCR evaluation tools for the 21st century

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@Hegghammer – thanks for your submission to JOSS. It looks like the YAML header of your file isn't formatted quite right, please take a look at the example and modify accordingly: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

Also, please take a look at the DOI suggestions from Whedon and update your BibTeX file if they look correct.

Finally, we're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by Hegghammer** [comment]
Dear Arfon Smith,
Many thanks for the quick response. I have addressed the YAML and DOI
issues, and updated versions of paper.md and paper.bib are now in the
Github repository.
No problem at all with the backlog. JOSS is already lightyears ahead of the
journals I normally deal with in terms of efficiency.
Thanks again and all the best,
Thomas Hegghammer

**Comment by arfon** [comment]
@whedon invite @Nikoleta-v3 as editor

:wave: @Nikoleta-v3 – I realize this is a little different, but we don't really have an 'ideal' editor for this submission. Would you be willing to take this one on?

**Comment by whedon** [comment]
@Nikoleta-v3 has been invited to edit this submission.

**Comment by Nikoleta-v3** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @Nikoleta-v3

**Comment by Nikoleta-v3** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03420/joss.03420/10.21105.joss.03420.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03420/joss.03420/10.21105.joss.03420.pdf) :page_facing_up: :point_left:

**Comment by Nikoleta-v3** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.31235/osf.io/6zfvs is OK
- 10.33011/computel.v1i.345 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Nikoleta-v3** [comment]
@Hegghammer thank you again for your submission with JOSS, if you have not already done so, could you take a look through https://bit.ly/joss-reviewers to suggest some potential reviewers 😄

**Comment by Hegghammer** [comment]
Thank you for considering the manuscript! My suggestions, in order of
perceived topic fit:

   - lmullen
   - josiahparry
   - neuroimaginador
   - adamhsparks

Best,
Thomas

**Comment by Nikoleta-v3** [comment]
👋 @lmullen & @josiahparry & @adamhsparks & @neuroimaginador, would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission I'd like you to review is titled: "daiR: an R package for OCR with Google Document AI". You can find more information at the top of this Github issue 🆙

Please let me know if you're available 😄 Thank you!

**Comment by lmullen** [comment]
With apologies, I'm not available at this time. Best wishes for the review.

**Comment by adamhsparks** [comment]
Sorry, I can't do this right now.

**Comment by Nikoleta-v3** [comment]
Thank you both for letting us know 😃👍🏻

**Comment by JosiahParry** [comment]
Hi Team, nor can I. My apologies.

**Comment by Nikoleta-v3** [comment]
No worries at all @JosiahParry 😄 thank you for getting back to me.

**Comment by Nikoleta-v3** [comment]
👋 @Athanasiamo & @cjbarrie & @LogIN- would any of you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission I'd like you to review is titled: "daiR: an R package for OCR with Google Document AI". You can find more information at the top of this Github issue 🆙

Please let me know if you're available 😄 Thank you!

**Comment by cjbarrie** [comment]
Happy to do so!

**Comment by Nikoleta-v3** [comment]
Thank you! 😄

**Comment by Nikoleta-v3** [comment]
@whedon assign @cjbarrie  as reviewer

**Comment by whedon** [comment]
OK, @cjbarrie  is now a reviewer

**Comment by Nikoleta-v3** [comment]
👋🏻 @expectopatronum & @hiendn & @shivam11 would any of you be willing to review this submission for JOSS?

Currently looking for one more reviewer! The submission I'd like you to review is titled: "daiR: an R package for OCR with Google Document AI". You can find more information at the top of this Github issue 🆙

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Please let me know if you're available 😄 Thank you!

**Comment by expectopatronum** [comment]
Hey! My vacation will start soon so I am not available at this time. Sorry!

**Comment by Nikoleta-v3** [comment]
That's okay! Enjoy your holiday and thank you for getting back to me @expectopatronum 😄

**Comment by cjbarrie** [comment]
Could you send the reviewer invite link again? Just checking in to review now and realize the invitation link has expired. My apologies for this.

**Comment by danielskatz** [comment]
@whedon re-invite @cjbarrie as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@cjbarrie please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by shivam11** [comment]
Yes, I am available.RegardsShivam    On Tuesday, July 20, 2021, 12:25:34 PM GMT+4, Nikoleta Glynatsi ***@***.***> wrote:  
 
 


👋🏻 @expectopatronum & @hiendn & @shivam11 would any of you be willing to review this submission for JOSS?

Currently looking for one more reviewer! The submission I'd like you to review is titled: "daiR: an R package for OCR with Google Document AI". You can find more information at the top of this Github issue 🆙
 
We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Please let me know if you're available 😄 Thank you!

**Comment by Nikoleta-v3** [comment]
Fantastic, thank you @shivam11.

**Comment by Nikoleta-v3** [comment]
@whedon add @shivam11  as reviewer

**Comment by Nikoleta-v3** [comment]
@whedon add @shivam11 as reviewer

**Comment by whedon** [comment]
OK, @shivam11 is now a reviewer

**Comment by Nikoleta-v3** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3538.
