### ISSUE TITLE
[PRE REVIEW]: Madym: A C++ toolkit for quantitative DCE-MRI analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3421]
**Submitting author:** @michaelberks (<a href="http://orcid.org/0000-0003-4727-2006">Michael Berks</a>)
**Repository:** <a href="https://gitlab.com/manchester_qbi/manchester_qbi_public/madym_cxx/" target ="_blank">https://gitlab.com/manchester_qbi/manchester_qbi_public/madym_cxx/</a>
**Version:** v4.15.0
**Editor:** @emdupre
**Reviewers:** @agahkarakuzu, @matteomancini
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e04f2517a022cc6d1de7681ecf147dae/status.svg)](https://joss.theoj.org/papers/e04f2517a022cc6d1de7681ecf147dae)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e04f2517a022cc6d1de7681ecf147dae"><img src="https://joss.theoj.org/papers/e04f2517a022cc6d1de7681ecf147dae/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e04f2517a022cc6d1de7681ecf147dae/status.svg)](https://joss.theoj.org/papers/e04f2517a022cc6d1de7681ecf147dae)
```

**Author instructions**

Thanks for submitting your paper to JOSS @michaelberks. **Currently, there isn't an JOSS editor assigned** to your paper.

@michaelberks if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by arfon** [comment]
@whedon generate pdf from branch JOSS_submission_4.15.0

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS_submission_4.15.0. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/jmri.1880070113 is OK
- 10.1002/mrm.22005 is OK

MISSING DOIs

- 10.1038/nrclinonc.2012.2 may be a valid DOI for title: Dynamic contrast-enhanced MRI in clinical trials of antivascular therapies
- 10.1038/s41467-018-07174-1 may be a valid DOI for title: Plasma Tie2 is a tumor vascular response biomarker for VEGF inhibitors in metastatic colorectal cancer
- 10.1038/jcbfm.1983.1 may be a valid DOI for title: Graphical evaluation of blood-to-brain transfer constants from multiple-time uptake data
- 10.1002/mrm.28798 may be a valid DOI for title: A model selection framework to quantify microvascular liver function in gadoxetate-enhanced MRI: Application to healthy liver, diseased tissue, and hepatocellular carcinoma

INVALID DOIs

- https://doi.org/10.1002/mrm.27939 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03421/joss.03421/10.21105.joss.03421.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03421/joss.03421/10.21105.joss.03421.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03421/joss.03421/10.21105.joss.03421.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03421/joss.03421/10.21105.joss.03421.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.95 s (104.5 files/s, 280494.8 lines/s)
-----------------------------------------------------------------------------------
Language                         files          blank        comment           code
-----------------------------------------------------------------------------------
C++                                 94          42357         109980         273921
HTML                                 1           7301              0          45503
C/C++ Header                        73           9705          31461          20891
Qt                                   2              0              0           2302
Python                               9            441            830           1317
CMake                                8            176            161            799
Markdown                             4             56              0            181
YAML                                 2             10              5            142
TeX                                  1             11              0            114
Dockerfile                           3             16             10             87
Bourne Shell                         2              0              0             11
DOS Batch                            2              0              0             10
JSON                                 1              0              0              8
TOML                                 1              0              0              7
Windows Resource File                1              0              0              1
-----------------------------------------------------------------------------------
SUM:                               204          60073         142447         345294
-----------------------------------------------------------------------------------


Statistical information for the repository '7d49a16b858e5d907662e543' was
gathered on 2021/06/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Michael Berks                   23        169135           2774           94.43
michaelberks                    36          6883           3252            5.57
momeemb2                         1             3              1            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael Berks            469418          277.5          0.1               34.44
```

**Comment by arfon** [comment]
@michaelberks – thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon I'm currently handling 7 submissions but once I've processed a few and if this still needs an editor I might be able to help. I've handled quite a few MRI papers.

**Comment by michaelberks** [comment]
@arfon and @Kevin-Mattheus-Moerman . Thanks both for the information, I understand the situation.

Looking at the whedon auto summary on the references, shall I add the missing the DOIs it has found (and correct the invalidly formatted DOI) now? I'll make the edit paper.bib directly on the paper submission branch (JOSS_submission_4.1.5.0).

**Comment by Kevin-Mattheus-Moerman** [comment]
@michaelberks yes you can fix those issues and update the paper draft at any time by calling `@whedon generate pdf`.

**Comment by arfon** [comment]
@whedon invite @emdupre as editor

:wave: @emdupre – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@emdupre has been invited to edit this submission.

**Comment by emdupre** [comment]
@whedon assign @emdupre as editor

**Comment by whedon** [comment]
OK, the editor is @emdupre

**Comment by emdupre** [comment]
Hi @michaelberks, thank you for submitting to JOSS ! I'll be acting as editor for this submission -- though thank you, @Kevin-Mattheus-Moerman, for offering your help, here !

If you have any recommendations for appropriate reviewers, please let us know.

**Comment by emdupre** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03421/joss.03421/10.21105.joss.03421.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03421/joss.03421/10.21105.joss.03421.pdf) :page_facing_up: :point_left:

**Comment by emdupre** [comment]
Hi @oesteban  :wave: 
Any chance you'd be available and willing to edit this submission for the Journal of Open Source Software ?

**Comment by emdupre** [comment]
Hi @tianxzhu :wave: 
Any chance you'd be available and willing to edit this submission for the Journal of Open Source Software ?

**Comment by danielskatz** [comment]
Hi @emdupre - I think you might be asking for reviewers, not editors?

**Comment by emdupre** [comment]
Ah sorry, yes ! That was an accident. Will fix now.

**Comment by michaelberks** [comment]
@emdupre great thank-you.

Can I check the policy re version increments (or point me in the direction of link on the JOSS wesbite - apologies if I've missed).

I've been maintaining Madym user automated semantic versioning. When I submitted a few weeks ago it was version 4.15.0. However a user found a small bug in the Dicom converter tool, which I've fixed, bumping the version to 4.15.1. I think I read one of the reviewer checks was to verify that the repo version matches the version given on the submission form, which is obviously no longer the case.

More generally, what I should I do if other fixes come up during the submission process (or I get round to adding some requested features).

**Comment by emdupre** [comment]
I can [update the submitted software version](https://joss.readthedocs.io/en/latest/whedon.html?highlight=version#changing-the-software-version) with whedon if there's a particular verison that reviewer's should be aware of. There's not [a specific check](https://joss.readthedocs.io/en/latest/review_checklist.html#review-checklist) that the version matches the submitted version during review, as -- as you mention -- it might be incrementing.

More generally, then, fixes coming up during the submission process is expected -- and the sign of a good review ! After reviews, [we'll ask](https://joss.readthedocs.io/en/latest/editing.html?highlight=version#message-to-authors-at-the-end-of-a-review) that you create and archive a version of your software that will be associated with the publication. This is the version check that we will look at most carefully !

**Comment by emdupre** [comment]
Hi @agahkarakuzu :wave:  Any chance you'd be available and willing to review this submission for the Journal of Open Source Software ?

**Comment by agahkarakuzu** [comment]
Hi @emdupre thank you for the invitation! 

I am available next week onwards, if that makes a reasonable timeline, happy to review this submission.

**Comment by emdupre** [comment]
Thank you, @agahkarakuzu ! I'll add you as a reviewer on this submission now.

**Comment by emdupre** [comment]
@whedon add @agahkarakuzu as reviewer

**Comment by whedon** [comment]
OK, @agahkarakuzu is now a reviewer

**Comment by emdupre** [comment]
Hi @Lestropie @mfroeling @grlee77 @jdtournier @matteomancini :wave:  

Would you be willing to review _Madym: A C++ toolkit for quantitative DCE-MRI analysis_  for [JOSS (the Journal of Open Source Software)](https://github.com/openjournals/joss-reviews/issues/joss.theoj.org/) ? 

The [review](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on [the software](https://gitlab.com/manchester_qbi/manchester_qbi_public/madym_cxx/) and this short paper:
https://github.com/openjournals/joss-papers/blob/joss.03421/joss.03421/10.21105.joss.03421.pdf

If you're available to review this work, please let me know and I'll add you as a reviewer. Once I have sufficient reviewers I'll open a dedicated review issue.

Thanks!

**Comment by matteomancini** [comment]
Hi @emdupre thanks for inviting me!
I'd be glad to review this software/paper.

**Comment by emdupre** [comment]
Thank you, @matteomancini ! I'll add you as a reviewer on this submission now.

**Comment by emdupre** [comment]
@whedon add @matteomancini as reviewer

**Comment by whedon** [comment]
OK, @matteomancini is now a reviewer

**Comment by grlee77** [comment]
I appreciate the offer, but do not have the bandwidth to do a solid review at the moment.

**Comment by Lestropie** [comment]
Eager to review for JOSS at some point, but am already behind schedule on a couple of others 😩

**Comment by jdtournier** [comment]
HI @emdupre, I'm sorry, I won't be able to review this, I'm about to go on leave. Do keep me in mind for future reviews though!

**Comment by emdupre** [comment]
Thank you @jdtournier @Lestropie and @grlee77 for letting me know !

**Comment by emdupre** [comment]
@agahkarakuzu @matteomancini Thanks again for agreeing to review this submission. I'll go ahead and start the review now !

**Comment by emdupre** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3523.
