### ISSUE TITLE
[PRE REVIEW]: Statsomat/EDAPY: A Shiny app for automated EDA with Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3422]
**Submitting author:** @reyar (<a href="http://orcid.org/0000-0001-8904-1631">Denise Welsch</a>)
**Repository:** <a href="https://github.com/Statsomat/EDAPY" target ="_blank">https://github.com/Statsomat/EDAPY</a>
**Version:** v1.0-beta
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/572e105da35183ff773097a7821d3828/status.svg)](https://joss.theoj.org/papers/572e105da35183ff773097a7821d3828)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/572e105da35183ff773097a7821d3828"><img src="https://joss.theoj.org/papers/572e105da35183ff773097a7821d3828/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/572e105da35183ff773097a7821d3828/status.svg)](https://joss.theoj.org/papers/572e105da35183ff773097a7821d3828)
```

**Author instructions**

Thanks for submitting your paper to JOSS @reyar. **Currently, there isn't an JOSS editor assigned** to your paper.

@reyar if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (367.7 files/s, 78410.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            19            834             50           4255
Rmd                              6            301            382            774
R                                5            204             36            389
Markdown                         2             22              0             77
JavaScript                       1             19              1             64
TeX                              2              9              0             47
-------------------------------------------------------------------------------
SUM:                            35           1389            469           5606
-------------------------------------------------------------------------------


Statistical information for the repository '6ca87ded6829fabe7ddfa03d' was
gathered on 2021/06/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Denise Welsch                    1            84              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Denise Welsch                84          100.0          0.0                1.19
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1201/9781003097471 may be a valid DOI for title: R Markdown Cookbook

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03422/joss.03422/10.21105.joss.03422.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03422/joss.03422/10.21105.joss.03422.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@reyar – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@reyar - thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion and is also out of scope as a wrapper for an underlying piece of software.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
