### ISSUE TITLE
[PRE REVIEW]: physical_validation: A Python package to assess the physical validity of molecular simulation results

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3423]
**Submitting author:** @ptmerz (<a href="http://orcid.org/0000-0002-7045-8725">Pascal T. Merz</a>)
**Repository:** <a href="https://github.com/shirtsgroup/physical_validation" target ="_blank">https://github.com/shirtsgroup/physical_validation</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/aa957fee7e0869eb0f7ba2d2cca92260/status.svg)](https://joss.theoj.org/papers/aa957fee7e0869eb0f7ba2d2cca92260)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/aa957fee7e0869eb0f7ba2d2cca92260"><img src="https://joss.theoj.org/papers/aa957fee7e0869eb0f7ba2d2cca92260/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/aa957fee7e0869eb0f7ba2d2cca92260/status.svg)](https://joss.theoj.org/papers/aa957fee7e0869eb0f7ba2d2cca92260)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ptmerz. **Currently, there isn't an JOSS editor assigned** to your paper.

@ptmerz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3423 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=5.49 s (17.1 files/s, 19131.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          63           1539           4448          83981
reStructuredText                 6            169            125            577
Jupyter Notebook                 4              0          13620            299
YAML                            16             30             13            141
Markdown                         3             18              0             64
DOS Batch                        1              8              1             27
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                            94           1768          18213          85099
-------------------------------------------------------------------------------


Statistical information for the repository 'd34ce0a657be8c4ceb646da4' was
gathered on 2021/06/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
MKiesel                          1             5              0            0.00
Matt Thompson                    1            58            391            0.31
Matthew W. Thompson              2             1             95            0.07
Michael Shirts                   4           125             97            0.15
Pascal Merz                    256        107565          24488           90.98
Pascal T. Merz                   1             5              5            0.01
SimonBoothroyd                   4          4755           1473            4.29
Theodore Fobe                    1             8              8            0.01
Wei-Tse Hsu                      1            10              9            0.01
mrshirts                        41          4744           1303            4.17

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
MKiesel                       4           80.0          1.5                0.00
Matt Thompson                57           98.3          1.8               98.25
Michael Shirts               17           13.6         54.4               11.76
Pascal Merz               85781           79.7          2.7                1.56
SimonBoothroyd             4078           85.8         13.4                9.54
Theodore Fobe                 8          100.0         12.1                0.00
Wei-Tse Hsu                   9           90.0          3.3                0.00
mrshirts                     14            0.3        107.0               14.29
```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03423/joss.03423/10.21105.joss.03423.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03423/joss.03423/10.21105.joss.03423.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@ptmerz – thanks for your submission to JOSS. Could you say a little more about the relationship between this submission and your previous paper about this software? https://doi.org/10.1371/journal.pone.0202764

JOSS does publish followup papers (2nd, 3rd etc.) for the same software package, provided that there have been substantial enhancements made to the package between submissions.

**Comment by arfon** [comment]
Also, it looks like your citations aren't rendering properly – you can read how to fix them [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html).

Finally, we're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by danielskatz** [comment]
👋 @ptmerz - I don't see any response from you to these above requests from @arfon.  I'm going to mark this as rejected later this week unless I hear back from you before then.

**Comment by danielskatz** [comment]
@whedon reject

due to lack of response from the author - it can be resubmitted if the author so desires (but if so, the author should mention this issue)

**Comment by whedon** [comment]
Paper rejected.

**Comment by ptmerz** [comment]
Hi @danielskatz and @arfon,

Apologies for the late reply, I am just returning from vacation. I will resubmit later this week, unless this can be reopened.

**Comment by danielskatz** [comment]
Please resubmit, taking into account the comments in this issue.  Specifically
- Discuss the relationship between this submission and your previous paper about this software - https://doi.org/10.1371/journal.pone.0202764 
- Fix the citations as mentioned in https://github.com/openjournals/joss-reviews/issues/3423#issuecomment-869123580
- Mention this issue (`https://github.com/openjournals/joss-reviews/issues/3423`)
