### ISSUE TITLE
[PRE REVIEW]: SiSyPHE: A Python package for the Simulation of Systems of Particles with High Efficiency

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3425]
**Submitting author:** @antoinediez (<a href="http://orcid.org/0000-0002-4454-8452">Antoine Diez</a>)
**Repository:** <a href="https://github.com/antoinediez/Sisyphe" target ="_blank">https://github.com/antoinediez/Sisyphe</a>
**Version:** v0.1.5
**Editor:** @pdebuyl
**Reviewers:** @lorenzo-rovigatti, @junghans
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/aef04ea8a4e78bcf320cb93e747c8bae/status.svg)](https://joss.theoj.org/papers/aef04ea8a4e78bcf320cb93e747c8bae)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/aef04ea8a4e78bcf320cb93e747c8bae"><img src="https://joss.theoj.org/papers/aef04ea8a4e78bcf320cb93e747c8bae/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/aef04ea8a4e78bcf320cb93e747c8bae/status.svg)](https://joss.theoj.org/papers/aef04ea8a4e78bcf320cb93e747c8bae)
```

**Author instructions**

Thanks for submitting your paper to JOSS @antoinediez. **Currently, there isn't an JOSS editor assigned** to your paper.

@antoinediez if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (566.6 files/s, 228162.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            27           3451             81          10525
JavaScript                      14           2404           2467           9203
Python                          21           1206           2156           3274
SVG                              2              0              0           2672
CSS                              9            200             57           1154
TeX                              1             55              4            570
reStructuredText                28           2577           2288            470
Markdown                         2             46              0            129
Jupyter Notebook                10              0           1959             88
DOS Batch                        1              8              1             26
make                             1              5              7             11
YAML                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           117           9956           9027          28131
-------------------------------------------------------------------------------


Statistical information for the repository 'fb6fe8b3a67292372981de6d' was
gathered on 2021/06/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Antoine Diez                    32         40852          17140          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Antoine Diez              23712           58.0          0.1               17.24
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03425/joss.03425/10.21105.joss.03425.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03425/joss.03425/10.21105.joss.03425.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/0021-9991(87)90140-9 is OK
- 10.1103/PhysRevLett.75.1226 is OK
- 10.1142/S0218202508003005 is OK
- 10.1007/s11537-007-0647-x is OK
- 10.1007/978-0-8176-4946-3_12 is OK
- 10.1007/s00205-014-0800-7 is OK
- 10.1142/S0218202516500330 is OK
- 10.1142/S0218202519500374 is OK
- 10.1142/S021820252040014X is OK
- 10.1002/pamm.201800291 is OK
- 10.1142/S0218202517400061 is OK
- 10.1137/18M1192184 is OK
- 10.1073/pnas.1806579115 is OK
- 10.1016/j.physrep.2012.03.004 is OK
- 10.1214/15-AIHP701 is OK
- 10.1109/ICNN.1995.488968 is OK
- 10.1103/PhysRevE.77.046113 is OK
- 10.1007/s10955-014-1119-3 is OK
- 10.1103/PhysRevE.58.4828 is OK
- 10.1073/pnas.1202032109 is OK
- 10.1103/PhysRevE.92.032722 is OK
- 10.1007/978-1-4757-3437-9 is OK
- 10.1109/78.984773 is OK
- 10.3182/20090706-3-FR-2004.00129 is OK
- 10.1198/106186004X12803 is OK

MISSING DOIs

- 10.1007/bfb0093177 may be a valid DOI for title: Asymptotic Behaviour of some interacting particle systems; McKean-Vlasov and Boltzmann models
- 10.4310/cms.2009.v7.n2.a9 may be a valid DOI for title: Emergence of time-asymptotic flocking in a stochastic Cucker-Smale system
- 10.1016/j.jfa.2014.02.030 may be a valid DOI for title: On Kac’s chaos and related problems
- 10.1080/07362994.2018.1486202 may be a valid DOI for title: McKean–Vlasov limit for interacting systems with simultaneous jumps
- 10.1142/9789813272880_0206 may be a valid DOI for title: Mathematical models of collective dynamics and self-organization
- 10.1007/978-3-030-15096-9_2 may be a valid DOI for title: Alignment of Self-propelled Rigid Bodies: From Particle Systems to Macroscopic Equations
- 10.1214/aoap/1028903535 may be a valid DOI for title: Measure-valued processes and interacting particle systems. Application to nonlinear filtering problems
- 10.1016/j.jcp.2019.108877 may be a valid DOI for title: Random batch methods (RBM) for interacting particle systems

INVALID DOIs

- None
```

**Comment by arfon** [comment]
:wave: @antoinediez - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by antoinediez** [comment]
@whedon generate pdf

**Comment by antoinediez** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03425/joss.03425/10.21105.joss.03425.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03425/joss.03425/10.21105.joss.03425.pdf) :page_facing_up: :point_left:

**Comment by antoinediez** [comment]
@whedon check references

**Comment by antoinediez** [comment]
@whedon check references

**Comment by kthyng** [comment]
Hi @pdebuyl this was the other submission I mentioned that looked like a good fit for you. Can you take this on when you are back in the office in August?

**Comment by kthyng** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by pdebuyl** [comment]
Hi @kthyng I'd be happy to edit this!

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@antoinediez I'll start looking for reviewers in august, sorry for the delay.

**Comment by pdebuyl** [comment]
@whedon assign @lorenzo-rovigatti as reviewer

**Comment by whedon** [comment]
OK, @lorenzo-rovigatti is now a reviewer

**Comment by antoinediez** [comment]
Hi @pdebuyl and @lorenzo-rovigatti ! 👋

Sorry for the late answer and thank you very much for having accepted to edit and review this work. 

@pdebuyl if you are looking for a second reviewer, based on the list provided and on the keywords, may I suggest (without any specific order):
- vyasr
- schroedtert
- dalg24
- csadorf
- Christovis
- junghans
- rusu24edward

**Comment by pdebuyl** [comment]
Thanks @antoinediez for the suggestsions. I was waiting for another reviewer's reply but will contact other candidates anyway.

**Comment by pdebuyl** [comment]
@junghans would you review the article "SiSyPHE: A Python package for the Simulation of Systems of Particles with High Efficiency" for the Journal of Open Source Software ?

**Comment by junghans** [comment]
@pdebuyl I am happy to.

**Comment by pdebuyl** [comment]
Thanks a lot @junghans !

**Comment by pdebuyl** [comment]
@whedon add @junghans as reviewer

**Comment by whedon** [comment]
OK, @junghans is now a reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3653.
