### ISSUE TITLE
[PRE REVIEW]: trackdown: An R Package for Enhancing Collaborative Writing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3427]
**Submitting author:** @ClaudioZandonella (<a href="http://orcid.org/0000-0001-7721-6318">Claudio Zandonella Callegher</a>)
**Repository:** <a href="https://github.com/ekothe/trackdown" target ="_blank">https://github.com/ekothe/trackdown</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/86aaab7d1396eb8de04fc41687623ef1/status.svg)](https://joss.theoj.org/papers/86aaab7d1396eb8de04fc41687623ef1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/86aaab7d1396eb8de04fc41687623ef1"><img src="https://joss.theoj.org/papers/86aaab7d1396eb8de04fc41687623ef1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/86aaab7d1396eb8de04fc41687623ef1/status.svg)](https://joss.theoj.org/papers/86aaab7d1396eb8de04fc41687623ef1)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ClaudioZandonella. **Currently, there isn't an JOSS editor assigned** to your paper.

@ClaudioZandonella if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (336.7 files/s, 249344.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                            35             25             14          45903
R                               19            840           1424           1876
Markdown                         9            368              0           1718
HTML                             1             90              5            336
Rmd                              7            245            393             49
TeX                              1              3              0             29
-------------------------------------------------------------------------------
SUM:                            72           1571           1836          49911
-------------------------------------------------------------------------------


Statistical information for the repository '4e9af402d65b0b57fafcbf3d' was
gathered on 2021/06/28.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03427/joss.03427/10.21105.joss.03427.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03427/joss.03427/10.21105.joss.03427.pdf) :page_facing_up: :point_left:

**Comment by ClaudioZandonella** [comment]
Potential Reviewers

considering Rmarkdown aspects 
- dvanic
- aaronpeikert

considering API aspects
- josiahparry
- pachamaltese

**Comment by arfon** [comment]
@ClaudioZandonella - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by arfon** [comment]
@whedon invite @csoneson as editor

:wave: @csoneson – would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
👋🏻 @ClaudioZandonella - thanks for your submission! To help us judge whether this is in scope to be considered by JOSS, would you mind providing a bit more details on where you see `trackdown` fall within our [definition of research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software)? Thanks!

**Comment by csoneson** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by ClaudioZandonella** [comment]
Hi @csoneson, thanks for the quick replay. 

`trackdown` provides a simple solution for collaborative writing and editing of reproducible documents. This is very useful for researchers from any field when they have to create reports or journal articles regarding their experiments. Thus, I think `trackdown` falls within your definition of research software because it "supports the execution of research experiments". 

Of course, this is a kind of wide interpretation, but writing and the dissemination of research results is still an important part of the experiments and research activity more in general.

I really hope that the aim of the package is of your interest. Please let me know if I should be more precise.

**Comment by arfon** [comment]
@ClaudioZandonella  – Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it does not meet our criteria of [research software](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
