### ISSUE TITLE
[PRE REVIEW]: prisonbrief: An R package that returns tidy data from the World Prison Brief website

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#343]
**Submitting author:** @danilofreire (<a href="http://orcid.org/0000-0002-4712-6810">Danilo Freire</a>)
**Repository:** <a href="https://github.com/danilofreire/prisonbrief" target ="_blank">https://github.com/danilofreire/prisonbrief</a>
**Version:** v0.1.0
**Editor:** @karthik
**Reviewer:** @benmarwick

**Author instructions**

Thanks for submitting your paper to JOSS @danilofreire. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@danilofreire if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @openjournals/ropensci - would this be a good candidate for rOpenSci?

**Comment by maelle** [comment]
Thanks @arfon, after discussion no.

**Comment by danilofreire** [comment]
Thanks @arfon and @maelle for considering the package for rOpenSci. That was very nice of you!

@arfon, I was also reading the list of potential reviewers and I thought that maybe @jsta would be a good fit. He wrote he is comfortable reviewing api wrappers in R, and that's basically what our package does. Also, @benmarwick stated that he has an interest in social sciences, which is the main area of our article. We would be very happy to have them reviewing our code. Of course, we are open to any suggestion you may have. Many thanks!

**Comment by karthik** [comment]
@danilofreire Thank you for the submission. I read over the paper in the repo and it reads very much like a vignette on how to use the package. Your paper.md must provide a high level description of what the software does and what some of the potential research applications are. You an still have a detailed vignette describing exactly how to use the software.

**Comment by danilofreire** [comment]
@karthik Thank you for your comment. I have just submitted a new version of paper.md. It now includes only a high-level description of the package and some potential applications as requested.

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
@danilofreire Thanks. I've reached out to Ben to see if he would serve as reviewer. Will update this thread when I know more.

**Comment by benmarwick** [comment]
Happy to help with reviewing this.

**Comment by karthik** [comment]
@whedon assign @benmarwick as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @benmarwick

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/361. Feel free to close this issue now!

**Comment by danilofreire** [comment]
Thanks very much @karthik and @benmarwick. Happy to read your comments.
