### ISSUE TITLE
[PRE REVIEW]: NiTransforms: A Python tool to read, represent, manipulate, and apply n-dimensional spatial transforms

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3432]
**Submitting author:** @mgxd (<a href="http://orcid.org/0000-0002-7252-7771">Mathias Goncalves</a>)
**Repository:** <a href="https://github.com/poldracklab/nitransforms" target ="_blank">https://github.com/poldracklab/nitransforms</a>
**Version:** 21.0.0
**Editor:** @osorensen
**Reviewers:** @robbisg, @PeerHerholz
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/10870dbd43c36af2f836e7d3b98d2336/status.svg)](https://joss.theoj.org/papers/10870dbd43c36af2f836e7d3b98d2336)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/10870dbd43c36af2f836e7d3b98d2336"><img src="https://joss.theoj.org/papers/10870dbd43c36af2f836e7d3b98d2336/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/10870dbd43c36af2f836e7d3b98d2336/status.svg)](https://joss.theoj.org/papers/10870dbd43c36af2f836e7d3b98d2336)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mgxd. **Currently, there isn't an JOSS editor assigned** to your paper.

@mgxd if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.591597 is OK
- 10.1016/j.neuroimage.2012.01.021 is OK
- 10.1016/j.neuroimage.2011.09.015 is OK
- 10.1016/j.media.2007.06.004 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1002/(SICI)1099-1492(199706/08)10:4/5	extless171::AID-NBM453	extgreater3.0.CO;2-L is INVALID
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (395.9 files/s, 119105.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          25            772            911           2479
SVG                              4              1              1           1368
YAML                             5             31              7            389
Jupyter Notebook                 3              0           7278            238
make                             1             30              6            148
Dockerfile                       1             18             15            125
Markdown                         2             17              0            100
reStructuredText                 4             16             28             77
TeX                              1              5              0             70
TOML                             1              1              0              9
-------------------------------------------------------------------------------
SUM:                            47            891           8246           5003
-------------------------------------------------------------------------------


Statistical information for the repository 'b83accd8702a0f05b7606131' was
gathered on 2021/06/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Chris Markiewicz                 2             6              2            0.08
Mathias Goncalves                1             1              1            0.02
Oscar Esteban                   16           337             90            4.29
Stefano Moia                     1             1              0            0.01
mathiasg                        43          1873            181           20.66
oesteban                        66          4791           2591           74.24
smoia                            4            42             27            0.69

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Chris Markiewicz              4           66.7         15.4                0.00
Oscar Esteban              3486         1034.4         16.2               12.65
mathiasg                    657           35.1         10.7               11.42
smoia                        15           35.7         19.5                6.67
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03432/joss.03432/10.21105.joss.03432.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03432/joss.03432/10.21105.joss.03432.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@mgxd – thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by arfon** [comment]
@whedon invite @emdupre as editor

:wave: @emdupre – would you be able to take on this submission for us?

**Comment by whedon** [comment]
@emdupre has been invited to edit this submission.

**Comment by arfon** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
@PeerHerholz, @snastase, would any of you be interested in reviewing this paper for the Journal of Open Source Software?

**Comment by osorensen** [comment]
@mgxd, I am now the editor for this submission. Please let me know if you have any suggestions for reviewers.

**Comment by PeerHerholz** [comment]
Ahoi hoi @osorensen,

thx for the tag. I would be very interested in reviewing this important addition to the `python-neuroimaging` software stack. However, only if the folks involved think that I would be a fitting reviewer of course.

Cheers, Peer

**Comment by mgxd** [comment]
Sounds great @osorensen

@PeerHerholz we would love to have you as a reviewer 😄

**Comment by osorensen** [comment]
@PeerHerholz , thanks!

**Comment by osorensen** [comment]
@whedon add @PeerHerholz as reviewer

**Comment by whedon** [comment]
OK, @PeerHerholz is now a reviewer

**Comment by PeerHerholz** [comment]
Ahoi hoi @osorensen,

I was looking for the review issue but then realized that the review wasn't started yet :man_facepalming:. 
This will be done once there are more reviewers, eh?

Cheers, Peer

**Comment by osorensen** [comment]
Yes @PeerHerholz, that's correct :-) Review has not started yet

**Comment by osorensen** [comment]
@nicksisco1932, @robbisg, @DrMarc, would any of you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by robbisg** [comment]
Hi everyone, thanks for considering me as a potential reviewer. I'd be happy to review the software and help the python neuroimaging community.

**Comment by osorensen** [comment]
Thanks @robbisg !

**Comment by osorensen** [comment]
@whedon assign @robbisg as reviewer

**Comment by whedon** [comment]
OK, @robbisg is now a reviewer

**Comment by osorensen** [comment]
@whedon add @PeerHerholz as reviewer

**Comment by whedon** [comment]
OK, @PeerHerholz is now a reviewer

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3459.

**Comment by snastase** [comment]
I'd love to review this, but I'm a little backed up right now—probably wouldn't get to it for another week or two. Let me know if you end up needing another reviewer!

**Comment by osorensen** [comment]
@snastase, thanks, that's absolutely fine. We've started the review with two other reviewers, so I'll get back to you at a later submission.
