### ISSUE TITLE
[PRE REVIEW]: Radial Interstices Enable Speedy Low-volume Imaging

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3433]
**Submitting author:** @spinicist (<a href="http://orcid.org/0000-0001-7640-5520">Tobias Wood</a>)
**Repository:** <a href="https://github.com/spinicist/riesling" target ="_blank">https://github.com/spinicist/riesling</a>
**Version:** v0.4
**Editor:** @emdupre
**Reviewers:** @uecker , @MartinK84
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/09eb68046190ebfb292ab67a52a37ce1/status.svg)](https://joss.theoj.org/papers/09eb68046190ebfb292ab67a52a37ce1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/09eb68046190ebfb292ab67a52a37ce1"><img src="https://joss.theoj.org/papers/09eb68046190ebfb292ab67a52a37ce1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/09eb68046190ebfb292ab67a52a37ce1/status.svg)](https://joss.theoj.org/papers/09eb68046190ebfb292ab67a52a37ce1)
```

**Author instructions**

Thanks for submitting your paper to JOSS @spinicist. **Currently, there isn't an JOSS editor assigned** to your paper.

@spinicist if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/nbm.4493 is OK
- 10.1002/mrm.23041 is OK
- 10.1002/mrm.1241 is OK
- 10.1002/mrm.22595 is OK

MISSING DOIs

- 10.1016/j.pnmrs.2021.03.002 may be a valid DOI for title: Silent Zero TE MR Neuroimaging: Current State-of-the-Art and Future Directions

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3433 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Florian Wiesinger, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (2170.2 files/s, 132554.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             62            526            122           4422
C/C++ Header                    43            223             75           1211
YAML                             2             18              1            170
CMake                            1              9              6            139
reStructuredText                 6             80             33            116
Markdown                         4             38              0            114
TeX                              1              7              0             92
MATLAB                           3             26             60             60
JSON                             1              0              0             20
Python                           1             15             30             10
Bourne Shell                     1              2              4              6
-------------------------------------------------------------------------------
SUM:                           125            944            331           6360
-------------------------------------------------------------------------------


Statistical information for the repository '61f3c6d241ad2080ccef9305' was
gathered on 2021/06/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Emil                             1             7              7            0.06
Emil Ljungberg                  14           612             84            3.19
Tobias Wood                    100         13618           7512           96.75

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Emil Ljungberg              240           39.2          2.4                4.17
Tobias Wood                6394           47.0          1.9                3.43
```

**Comment by arfon** [comment]
@spinicist - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

In the meantime, changing the paper header to quote the affiliations for Florian Wiesinger should fix your paper compilation:

```
  - name: Florian Wiesinger
    orcid: 0000-0002-5597-6057
    affiliation: "1,2"
```

**Comment by spinicist** [comment]
@wehdon generate pdf

**Comment by spinicist** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03433/joss.03433/10.21105.joss.03433.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03433/joss.03433/10.21105.joss.03433.pdf) :page_facing_up: :point_left:

**Comment by spinicist** [comment]
@arfon Thanks, I have fixed the PDF. Any idea of the likely wait?

**Comment by arfon** [comment]
Likely a couple of weeks. We have a new editor joining who I think should be able to take this submission on.

**Comment by spinicist** [comment]
Great, thanks again.

**Comment by arfon** [comment]
@whedon invite @osorensen as editor

:wave: @osorensen – would you be able to take this submission on for us too? (Last one for now I promise!)

**Comment by whedon** [comment]
@osorensen has been invited to edit this submission.

**Comment by osorensen** [comment]
@whedon add @osorensen as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by osorensen** [comment]
@whedon command

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by osorensen** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
@spinicist I am now the editor for this submission. If you have any suggestions for potential reviewers, please mention them by GitHub username in this thread (without the @).

**Comment by spinicist** [comment]
Hello,

From the recon side you could try jtamir, martink84, uecker, or any of the other contributors to BART (https://github.com/mrirecon/bart/graphs/contributors) or SigPy (https://github.com/mikgroup/sigpy/graphs/contributors).

You could also try agahkarakuzu from qMRLab (https://github.com/mikgroup/sigpy/graphs/contributors)

Thanks

**Comment by osorensen** [comment]
@jtamir, @martink84, @uecker, @agahkarakuzu, @frankong, would any of you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by arfon** [comment]
@whedon assign @emdupre as editor

Following discussions with @emdupre and @osorensen offline, swapping editors here.

**Comment by whedon** [comment]
OK, the editor is @emdupre

**Comment by MartinK84** [comment]
I would be available as a reviewer and have experience in the relevant field (working with 3D non-cartesian MRI data and have used comparable toolboxes such as BART). I have to warn, however, that I'm very busy at the moment and will probably need several weeks to be able to finish reviewing this contribution thoroughly.

**Comment by emdupre** [comment]
Hi @spinicist, thanks for your submission to JOSS ! As @arfon mentioned above, we've swapped handling editors, here, so I'll be acting as editor for your submission.

@MartinK84, thank you for your willingness to review ! I'll wait a bit longer to see if other reviewers might have more availability, but I will of course keep you up to date.

**Comment by uecker** [comment]
I am also happy to review this (but not sure what I have to do...)

**Comment by emdupre** [comment]
Thanks for your willingness to review, @uecker  ! You can find more information on the JOSS review process on [the JOSS documentation](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html), including the [checklist we ask you to complete](https://joss.readthedocs.io/en/latest/review_checklist.html) during a review. 

If that all sounds alright to you, I can add you as a reviewer on this submission.

**Comment by emdupre** [comment]
Hi @spinicist ! While we're waiting to confirm the reviewers, a few quick notes from me:

- The abbreviation RIESLING is not defined in the paper, although I assume it stands for your title "Radial Interstices Enable Speedy Low-volume Imaging." Please clarify or otherwise make this explicit in the text.
- Your paper doesn't yet have a [Statement of Need section](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), which will help to explain why this software is useful to the field.
- The current Summary section lacks a broader introduction for the non-specialist reader. Important terms like Zero Echo Time are considered but not defined. 

Please check the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) for an idea of the level of detail that we expect here !

**Comment by spinicist** [comment]
Hello,

We have expanded the paper and included the acronym definition. The statement of need has been split out of the summary and clarified. Echo Time (TE) is a general MRI term, and the cited paper for ZTE is a comprehensive review of how it may be reduced to zero.

**Comment by emdupre** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03433/joss.03433/10.21105.joss.03433.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03433/joss.03433/10.21105.joss.03433.pdf) :page_facing_up: :point_left:

**Comment by emdupre** [comment]
Hi @uecker , have you had a chance to confirm that you're OK to review ? I can assign you as a reviewer, if so.

**Comment by emdupre** [comment]
Hi @neurolabusc :wave: Any chance you'd be available and willing to review this submission for the Journal of Open Source Software ?

**Comment by agahkarakuzu** [comment]
@emdupre I can help with the review of this submission, sorry I am late for the party a bit.

**Comment by neurolabusc** [comment]
@emdupre I feel this work is outside my expertise. I do think reviewers like Uecker from the BART project would be ideal. You might also want to consider the developers of [mripy](https://github.com/peng-cao/mripy).

**Comment by uecker** [comment]
@emdupre.  Yey, I can review this work.

**Comment by emdupre** [comment]
Thank you, @uecker ! I'll add you as a reviewer now.

Thanks, too, @neurolabusc for your quick response and for sharing mripy !

From an offline discussion, I'm going to avoid assigning you as a reviewer here, @agahkarakuzu, so you're not over-committed with concurrent JOSS reviews. 

@MartinK84, would you still be willing to review ? I know that you said you might need a several week delay -- would you be able to give a more concrete estimate of that timeline (e.g. one month) ? I appreciate any additional detail you could offer, here !

**Comment by emdupre** [comment]
@whedon add @uecker  as reviewer

**Comment by whedon** [comment]
OK, @uecker  is now a reviewer

**Comment by MartinK84** [comment]
@emdupre I am confident that I will be able to finish the review within 4 weeks and would still be willing to do it.

**Comment by emdupre** [comment]
Thank you, @MartinK84 ! 

As JOSS is still in [reduced service mode](https://blog.joss.theoj.org/#reduced-service-mode), a month would be a very reasonable timeline, here.  I'll go ahead and add you as a reviewer to the submission now !

**Comment by emdupre** [comment]
@whedon add @MartinK84 as reviewer

**Comment by whedon** [comment]
OK, @MartinK84 is now a reviewer

**Comment by emdupre** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3500.
