### ISSUE TITLE
[REVIEW]: grapesAgri1-Collection of shiny applications for data analysis in Agriculture-Part 1

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3437]
**Submitting author:** @pratheesh3780 (<a href="http://orcid.org/0000-0003-3290-0436">Pratheesh P Gopinath</a>)
**Repository:** <a href="https://github.com/pratheesh3780/grapesAgri1" target ="_blank">https://github.com/pratheesh3780/grapesAgri1</a>
**Version:** v1.0.0
**Editor:** @fabian-s
**Reviewer:** @adithirgis, @elimillera
**Archive:** <a href="https://doi.org/10.5281/zenodo.5106216" target="_blank">10.5281/zenodo.5106216</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247/status.svg)](https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247"><img src="https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247/status.svg)](https://joss.theoj.org/papers/7d63999d1569093e17dbdbfb3a5f5247)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pratheesh3780/grapesAgri1" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@adithirgis & @elimillera, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @fabian-s know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pratheesh3780/grapesAgri1">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pratheesh3780) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pratheesh3780/grapesAgri1">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@pratheesh3780) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @adithirgis, @elimillera it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (506.7 files/s, 150602.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               12            461            483           4404
Rmd                              6            114             99           1031
TeX                              1             23              0            181
Markdown                         3             61              0            169
YAML                             2             15              3             89
-------------------------------------------------------------------------------
SUM:                            24            674            585           5874
-------------------------------------------------------------------------------


Statistical information for the repository '293108d842f7f519c6c77503' was
gathered on 2021/07/01.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03437/joss.03437/10.21105.joss.03437.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03437/joss.03437/10.21105.joss.03437.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1093/oso/9780190222055.003.0002 may be a valid DOI for title: Exploratory Data Analysis

INVALID DOIs

- None
```

**Comment by adithirgis** [comment]
Started review here - https://github.com/pratheesh3780/grapesAgri1/issues/1

**Comment by pratheesh3780** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03437/joss.03437/10.21105.joss.03437.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03437/joss.03437/10.21105.joss.03437.pdf) :page_facing_up: :point_left:

**Comment by pratheesh3780** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03437/joss.03437/10.21105.joss.03437.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03437/joss.03437/10.21105.joss.03437.pdf) :page_facing_up: :point_left:

**Comment by adithirgis** [comment]
Hi @fabian-s and @pratheesh3780,

I have completed the review. The package is very useful! 

Thanks so much for inviting me. 
Adithi

**Comment by fabian-s** [comment]
thank you @adithirgis for your quick and thorough review and thank you @pratheesh3780  for your equally quick and constructive replies! :+1:

**Comment by elimillera** [comment]
@adithirgis @fabian-s 
My review is done.

Both https://github.com/pratheesh3780/grapesAgri1/issues/4 and https://github.com/pratheesh3780/grapesAgri1/issues/3 are small issues that don't effect functionality. I also have some small comments in https://github.com/pratheesh3780/grapesAgri1/pull/6. 

 I would think https://github.com/pratheesh3780/grapesAgri1/issues/2 is the only issue that I would want resolved before release.
 
 Thank you for the invitation and your work on the application!

**Comment by pratheesh3780** [comment]
@whedon generate pdf

**Comment by fabian-s** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1093/oso/9780190222055.003.0002 may be a valid DOI for title: Exploratory Data Analysis

INVALID DOIs

- None
```

**Comment by fabian-s** [comment]
thank you @elimillera  for your quick and thorough review, we appreciate it a lot!

**Comment by fabian-s** [comment]
@pratheesh3780 

1. do you want to work on the coding issues (https://github.com/pratheesh3780/grapesAgri1/issues/5, https://github.com/pratheesh3780/grapesAgri1/issues/4) raised by @elimillera before we define the JOSS release of your package? Not required, up to you. (The JOSS paper will point to the version of your package that was available at publication, so it might be a good idea to improve the code first..)
2. please see my proofreading edits at https://github.com/pratheesh3780/grapesAgri1/pull/7 and merge the ones that seem reasonable to you
3. the "missing DOI" whedon complains about is a false positive, just ignore that.

**Comment by pratheesh3780** [comment]
@fabian-s 
1. As the app is stable and working fine, I don't intend to make those changes. Though it is a valuable suggestion.
2. Proofreading edits were merged
3. ok

This was my first experience  with JOSS. Such a developer friendly platform. Future of scientific journals is here. I enjoyed the entire review process and valuable suggestions from @adithirgis  and @elimillera . Learned a lot.

Thank you!

**Comment by pratheesh3780** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03437/joss.03437/10.21105.joss.03437.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03437/joss.03437/10.21105.joss.03437.pdf) :page_facing_up: :point_left:

**Comment by fabian-s** [comment]
@pratheesh3780 

Ok, great! 

Please issue a new [tagged release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) of the software  and archive it (on Zenodo, figshare, or other), then please post the version number and archive DOI  here in this comment thread.

**Comment by pratheesh3780** [comment]
@fabian-s 
Please see the Release details
Version 1.1.0 
DOI: 10.5281/zenodo.5106216

Thank you!

**Comment by fabian-s** [comment]
@pratheesh3780 :

seems like your Zenodo archive doesn't have correct metadata yet: 

Authors are given as  "pratheesh3780; Eli Miller; Fabian Scheipl; Adithi R. Upadhya",
should be "Pratheesh P. Gopinath, Rajender Parsad, Brigit Joseph, Adarsh V. S." (same as your JOSS paper)

Title is "pratheesh3780/grapesAgri1: grapesAgri1- Collection of R-shiny Package for Agricultural Data Analysis Part 1"
should be "grapesAgri1- Collection of R-shiny Package for Agricultural Data Analysis" (same as your JOSS paper)

Please fix ASAP and let me know here once that's done.

**Comment by pratheesh3780** [comment]
@fabian-s 
extremely sorry for this.
Corrections were made
Version 1.1.0 
DOI: 10.5281/zenodo.5106216

**Comment by fabian-s** [comment]
@whedon set 10.5281/zenodo.5106216 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5106216" target="_blank">10.5281/zenodo.5106216</a> is the archive.

**Comment by fabian-s** [comment]
@whedon set <v1.0.0> as version

**Comment by whedon** [comment]
OK. <v1.0.0> is the version.

**Comment by fabian-s** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by fabian-s** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2452

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2452, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1093/oso/9780190222055.003.0002 may be a valid DOI for title: Exploratory Data Analysis

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@pratheesh3780 – could you merge this last PR which has a few more minor changes for readability: https://github.com/pratheesh3780/grapesAgri1/pull/8

**Comment by pratheesh3780** [comment]
@arfon  changes were merged! Thank You!

**Comment by pratheesh3780** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03437/joss.03437/10.21105.joss.03437.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03437/joss.03437/10.21105.joss.03437.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1093/oso/9780190222055.003.0002 may be a valid DOI for title: Exploratory Data Analysis

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2459

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2459, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1416667538801545216) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2460
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03437](https://doi.org/10.21105/joss.03437)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@adithirgis, @elimillera – many thanks for your reviews here and to @fabian-s for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@pratheesh3780  – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03437/status.svg)](https://doi.org/10.21105/joss.03437)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03437">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03437/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03437/status.svg
   :target: https://doi.org/10.21105/joss.03437
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03437/status.svg)](https://doi.org/10.21105/joss.03437)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by arfon** [comment]
Also, congrats to @fabian-s on editing his first paper for JOSS 🥳
