### ISSUE TITLE
[REVIEW]: caracas: Computer algebra in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3438]
**Submitting author:** @mikldk (<a href="http://orcid.org/0000-0002-0234-0266">Mikkel Meyer Andersen</a>)
**Repository:** <a href="https://github.com/r-cas/caracas" target ="_blank">https://github.com/r-cas/caracas</a>
**Version:** v1.1.1
**Editor:** @Nikoleta-v3
**Reviewer:** @EduPH, @MikeLydeamore
**Archive:** <a href="https://doi.org/10.5281/zenodo.5070324" target="_blank">10.5281/zenodo.5070324</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974/status.svg)](https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974"><img src="https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974/status.svg)](https://joss.theoj.org/papers/fc8a642838e52d656317ce8386e2d974)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/r-cas/caracas" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@EduPH & @MikeLydeamore, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @Nikoleta-v3 know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/r-cas/caracas">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mikldk) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/r-cas/caracas">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mikldk) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @EduPH, @MikeLydeamore it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (1235.1 files/s, 246900.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            91           4519           1155          16491
R                               37            933           1679           2372
Markdown                         5            178              0            630
Rmd                              8            322            563            620
CSS                              4             99             48            431
JavaScript                       3             64             32            256
YAML                             3             23              8            192
TeX                              1              7              0             69
Python                           1             22              7             52
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                           154           6167           3493          21124
-------------------------------------------------------------------------------


Statistical information for the repository '03af5f61901eeeae44db9dd8' was
gathered on 2021/07/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Mikkel Meyer Anderse             6           456             23          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mikkel Meyer Anderse        433           95.0          3.5                9.01
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01763 is OK
- 10.1007/3-540-45470-5_29 is OK
- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03438/joss.03438/10.21105.joss.03438.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03438/joss.03438/10.21105.joss.03438.pdf) :page_facing_up: :point_left:

**Comment by MikeLydeamore** [comment]
@Nikoleta-v3 I have completed my review and have no comments on the work. The software runs as expected and the paper meets the recommended guidelines.

**Comment by EduPH** [comment]
I agree with @MikeLydeamore . @Nikoleta-v3, the software was revised and all the review tasks were satisfied.

**Comment by mikldk** [comment]
Thanks both. I will start preparing a release at Zenodo etc.

**Comment by Nikoleta-v3** [comment]
Thank you both for your reviews  🙌🏻  @mikldk please hold fire. I would like to have a final read through the paper 😄 👍🏻

**Comment by Nikoleta-v3** [comment]
@mikldk I opened some minor issues https://github.com/r-cas/caracas/issues/49 & https://github.com/r-cas/caracas/issues/50 (this is mostly nitpicking and spelling)

**Comment by mikldk** [comment]
@Nikoleta-v3 : Thanks for catching these. I fixed [#49](https://github.com/r-cas/caracas/issues/49) in [379fb1](https://github.com/r-cas/caracas/commit/379fb1fa76a317edaa33681e65294c447aedba15) and [#50](https://github.com/r-cas/caracas/issues/50) in [ac6f07](https://github.com/r-cas/caracas/commit/ac6f07086525b94a63122b5fa3f3a83d64d3938e).

**Comment by Nikoleta-v3** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03438/joss.03438/10.21105.joss.03438.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03438/joss.03438/10.21105.joss.03438.pdf) :page_facing_up: :point_left:

**Comment by Nikoleta-v3** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01763 is OK
- 10.1007/3-540-45470-5_29 is OK
- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- 10.1007/978-3-211-73265-6_1 may be a valid DOI for title: Maple

INVALID DOIs

- None
```

**Comment by Nikoleta-v3** [comment]
Thank you @mikldk 👍🏻 Everything looks good to me. 

`whedon` is suggesting the doi of this [book](https://link.springer.com/chapter/10.1007%2F978-3-211-73265-6_1) (which discusses both Maple and Mathematica) for the Maple reference. But your  current citations for both Maple and Mathematica are inline with the softwares' guidelines 👍🏻 

At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by mikldk** [comment]
* The tagged release is `v.1.1.1` (as stated in the submission): <https://github.com/r-cas/caracas/releases/tag/v1.1.1>
* DOI: [10.5281/zenodo.5070324](https://doi.org/10.5281/zenodo.5070324)
* Zenodo: <https://zenodo.org/record/5070324>

**Comment by mikldk** [comment]
@Nikoleta-v3 Thanks, including agreeing on the references. I now made a release and made it available on Zenodo, cf. above.

**Comment by Nikoleta-v3** [comment]
@whedon set 10.5281/zenodo.5070324 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5070324" target="_blank">10.5281/zenodo.5070324</a> is the archive.

**Comment by Nikoleta-v3** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01763 is OK
- 10.1007/3-540-45470-5_29 is OK
- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- 10.1007/978-3-211-73265-6_1 may be a valid DOI for title: Maple

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2434

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2434, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by Nikoleta-v3** [comment]
`joss-eics` team 👋🏻 

Regarding the missing `doi`: 

> Thank you @mikldk 👍🏻 Everything looks good to me.
> 
> `whedon` is suggesting the doi of this [book](https://link.springer.com/chapter/10.1007%2F978-3-211-73265-6_1) (which discusses both Maple and Mathematica) for the Maple reference. But your current citations for both Maple and Mathematica are inline with the softwares' guidelines 👍🏻
> 
> At this point could you:
> 
> * [x]  Make a tagged release of your software, and list the version tag of the archived version here.
> * [x]  Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
> * [x]  Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
> * [x]  Please list the DOI of the archived version here.
> 
> I can then move forward with accepting the submission.

**Comment by mikldk** [comment]
@Nikoleta-v3 Thanks. I'm not sure if the waitlist label should be removed?

**Comment by Nikoleta-v3** [comment]
I have removed the label just to be sure 😄 Nevertheless, `@openjournals/joss-eics` have been pinned by `whedon`. I am assuming it's only a matter of days until the paper is published

**Comment by kthyng** [comment]
Hi @mikldk! A few comments on your paper before we wrap up:
* there is an errant space in the last sentence in the "summary" section.
* Please go through your references in detail to fix capitalization. You can preserve capitalization in bibtex using {} around characters, words, and phrases. For example, R, and Python are not always capitalized, but please check all entries.

**Comment by kthyng** [comment]
(otherwise we are ready to go)

**Comment by mikldk** [comment]
@kthyng Thanks. I'll make the changes and ping you once they're good to go.

**Comment by mikldk** [comment]
@kthyng Thanks. I have now fixed these in https://github.com/r-cas/caracas/commit/53ff25db23928a3de035b817c1b1f94b1f99a4a8 . As this is only in the paper I am not sure if I should make a new Zenodo release or just keep the "old" one (with reviewed software, but out-of-sync paper source)?

**Comment by danielskatz** [comment]
You can choose - we don't require the paper source be in the repo at all, so either way is ok.

**Comment by mikldk** [comment]
@danielskatz Then we'll just use the current archive/release 👍.

**Comment by mikldk** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03438/joss.03438/10.21105.joss.03438.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03438/joss.03438/10.21105.joss.03438.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2463

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2463, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1417105701042900997) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2464
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03438](https://doi.org/10.21105/joss.03438)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01763 is OK
- 10.1007/3-540-45470-5_29 is OK
- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- 10.1007/978-3-211-73265-6_1 may be a valid DOI for title: Maple

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
Congratulations to @mikldk (Mikkel Meyer Andersen) and co-author!

And thanks to @Nikoleta-v3 for editing, and @EduPH and @MikeLydeamore for reviewing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03438/status.svg)](https://doi.org/10.21105/joss.03438)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03438">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03438/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03438/status.svg
   :target: https://doi.org/10.21105/joss.03438
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03438/status.svg)](https://doi.org/10.21105/joss.03438)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by mikldk** [comment]
Thanks to you all, @Nikoleta-v3, @EduPH, @MikeLydeamore, @danielskatz, @kthyng 🥇.
