### ISSUE TITLE
[PRE REVIEW]: The psyplot interactive visualization framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#344]
**Submitting author:** @Chilipp (<a href="http://orcid.org/0000-0001-6171-7716">Philipp S. Sommer</a>)
**Repository:** <a href="https://github.com/Chilipp/psyplot.git" target ="_blank">https://github.com/Chilipp/psyplot.git</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @Fil

**Author instructions**

Thanks for submitting your paper to JOSS @Chilipp. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Chilipp if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by Chilipp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
👋 @fil - would you be willing to review this submission for JOSS?

**Comment by Fil** [comment]
Yes 👌🏼

PS: Maybe this issue could show the actual URL for the paper <http://joss.theoj.org/papers/3535c28017003f0b5fb63b1b64118b60> ?

**Comment by arfon** [comment]
> PS: Maybe this issue could show the actual URL for the paper http://joss.theoj.org/papers/3535c28017003f0b5fb63b1b64118b60 

That's a good idea. The main review issue (which we're about to switch to) _does_ have the URL linked to from the status badge but I agree it would be good to have that here too.

**Comment by arfon** [comment]
@whedon assign @Fil as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @Fil

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/363. Feel free to close this issue now!

**Comment by arfon** [comment]
@Fil - please head over to #363 for the actual review.
