### ISSUE TITLE
[PRE REVIEW]: pipra: pixel-precise annotator for semantic segmentation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3441]
**Submitting author:** @anki-xyz (<a href="http://orcid.org/0000-0003-3643-7776">Andreas M. Kist</a>)
**Repository:** <a href="https://github.com/anki-xyz/pipra" target ="_blank">https://github.com/anki-xyz/pipra</a>
**Version:** v.0.3.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/24ee6b73d3937ef7ce73b2e4af2afa84/status.svg)](https://joss.theoj.org/papers/24ee6b73d3937ef7ce73b2e4af2afa84)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/24ee6b73d3937ef7ce73b2e4af2afa84"><img src="https://joss.theoj.org/papers/24ee6b73d3937ef7ce73b2e4af2afa84/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/24ee6b73d3937ef7ce73b2e4af2afa84/status.svg)](https://joss.theoj.org/papers/24ee6b73d3937ef7ce73b2e4af2afa84)
```

**Author instructions**

Thanks for submitting your paper to JOSS @anki-xyz. **Currently, there isn't an JOSS editor assigned** to your paper.

@anki-xyz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (339.4 files/s, 51009.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           6            287            272            731
Markdown                         1             29              0             67
DOS Batch                        1              8              1             26
reStructuredText                 1             20             18             24
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            10            348            298            857
-------------------------------------------------------------------------------


Statistical information for the repository 'ce9686ade9f10270424f7a18' was
gathered on 2021/07/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
anki                             1           149             43           11.64
anki-xyz                        22          1321            137           88.36

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
anki                        135           90.6         24.5               17.04
anki-xyz                   1155           87.4          3.2               15.41
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3441 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
👋🏻 @anki-xyz – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03441/joss.03441/10.21105.joss.03441.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03441/joss.03441/10.21105.joss.03441.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2020.02.12.945956 is OK

MISSING DOIs

- 10.1038/s41597-020-0526-3 may be a valid DOI for title: BAGLS, a multihospital benchmark for automatic glottis segmentation
- 10.1044/2021_jslhr-20-00498 may be a valid DOI for title: A Deep Learning Enhanced Novel Software Tool for Laryngeal Dynamics Analysis

INVALID DOIs

- None
```

**Comment by anki-xyz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by anki-xyz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2020.02.12.945956 is OK
- 10.1038/s41597-020-0526-3 is OK
- 10.1044/2021_JSLHR-20-00498 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1145/2833157.2833162 is OK
- 10.1145/1015706.1015720 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03441/joss.03441/10.21105.joss.03441.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03441/joss.03441/10.21105.joss.03441.pdf) :page_facing_up: :point_left:

**Comment by anki-xyz** [comment]
@arfon thanks! Let me know if I can provide any further information

**Comment by arfon** [comment]
@anki-xyz – Thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.
 
We'd welcome a resubmission in the future if this software was expanded to be more comprehensive in features.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
