### ISSUE TITLE
[PRE REVIEW]: GeoClimate : a Geospatial processing toolbox for environmental and climate studies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3442]
**Submitting author:** @ebocher (<a href="http://orcid.org/0000-0002-4936-7079">Erwan Bocher</a>)
**Repository:** <a href="https://github.com/orbisgis/geoclimate/" target ="_blank">https://github.com/orbisgis/geoclimate/</a>
**Version:** 1.0.0-SNAPSHOT
**Editor:** @elbeejay
**Reviewers:** @abhishekvp, @omshinde, @arbennett
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2b216ea704e5ee9d61a8208463c17ce1/status.svg)](https://joss.theoj.org/papers/2b216ea704e5ee9d61a8208463c17ce1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2b216ea704e5ee9d61a8208463c17ce1"><img src="https://joss.theoj.org/papers/2b216ea704e5ee9d61a8208463c17ce1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2b216ea704e5ee9d61a8208463c17ce1/status.svg)](https://joss.theoj.org/papers/2b216ea704e5ee9d61a8208463c17ce1)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ebocher. **Currently, there isn't an JOSS editor assigned** to your paper.

@ebocher if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by arfon** [comment]
@ebocher - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by ebocher** [comment]
@arfon  thanks for the comment.  @hugoledoux  will be a very good candidate to review the paper.
Best regards

**Comment by kthyng** [comment]
@whedon check repo

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kthyng** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.92 s (104.1 files/s, 165298.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              5             14             16          78777
SVG                              1              1              1          44890
Groovy                          37           1848           3232          15668
JSON                            32              5              0           4734
Scheme                           3              1              0            799
Maven                            5             29              7            761
SQL                              6            196            297            702
Markdown                         4             86              0            228
TeX                              1             11              0            147
YAML                             2              4              4             38
-------------------------------------------------------------------------------
SUM:                            96           2195           3557         146744
-------------------------------------------------------------------------------


Statistical information for the repository '79ba885c5d60828236c95119' was
gathered on 2021/07/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bocher                           2             4              4            0.12
Elisabeth Le Saux                2           626            409           15.44
Palominos Sylvain                4             8             50            0.87
ebocher                         25          1389           1029           36.07
gpetit                          22          1652            343           29.76
jeremy                           1            22             22            0.66
jeremy-b                        50           604            441           15.59
nahtanojoal                      4            94              6            1.49

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
ebocher                     368           26.5          7.1                3.53
gpetit                      623           37.7         24.7               44.78
jeremy-b                    202           33.4         17.8                2.48
nahtanojoal                   2            2.1         26.5                0.00
```

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3442 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (b6385f2dafbdfd845db88e95/docs/articles/joss/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by ebocher** [comment]
@kthyng 
Just to inform you that the PDF compiles using github action : https://github.com/orbisgis/geoclimate/actions/runs/989591342

**Comment by arfon** [comment]
@ebocher - please remove the blank ORCID lines from your paper by merging this pull request: https://github.com/orbisgis/geoclimate/pull/609

Also it looks like you're not citing your references properly. The section in your `paper.md` after the `# References` heading should be empty and citations to other works will automatically appear in there if you cite them in the paper text. You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

**Comment by ebocher** [comment]
thanks @arfon I will fix it

**Comment by j3r3m1** [comment]
> @ebocher - please remove the blank ORCID lines from your paper by merging this pull request: [orbisgis/geoclimate#609](https://github.com/orbisgis/geoclimate/pull/609)

Done

> Also it looks like you're not citing your references properly. The section in your `paper.md` after the `# References` heading should be empty and citations to other works will automatically appear in there if you cite them in the paper text. You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

The reason was that we put footnote in the reference section since it did not work otherwise. I removed them and add them in the body of the article but I am not sure it works as expected. You can let us know before we merge or we can merge and then see. The pull request is here:
orbisgis/geoclimate#610

**Comment by kthyng** [comment]
Hi @fraukewiese are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @fraukewiese as editor

**Comment by whedon** [comment]
@fraukewiese has been invited to edit this submission.

**Comment by ebocher** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03442/joss.03442/10.21105.joss.03442.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03442/joss.03442/10.21105.joss.03442.pdf) :page_facing_up: :point_left:

**Comment by fraukewiese** [comment]
I will be OoO until beginning of August, so I would prefer if somebody else could edit this submission.

**Comment by danielskatz** [comment]
👋 @elbeejay - Would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @elbeejay as editor

**Comment by whedon** [comment]
@elbeejay has been invited to edit this submission.

**Comment by elbeejay** [comment]
@whedon assign @elbeejay as editor

**Comment by whedon** [comment]
OK, the editor is @elbeejay

**Comment by elbeejay** [comment]
Hi @ebocher, is there API documentation somewhere in your wiki? One of the [JOSS review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#api-documentation) is for the software to have some documentation of at least the core API functions. I apologize if I've missed seeing it in the wiki. 

Secondly, can you recommend any reviewers that would be a good fit to review this work? A list of folks that have expressed a willingness to review for JOSS is available [here](https://bit.ly/joss-reviewers), but feel free to also recommend people not on this list. Please do not tag potential reviewers in this thread but rather provide their GitHub handle without the "@" symbol (e.g. "elbeejay" for me). 

Thanks and feel free to reach out with any questions about the process.

- Jay

**Comment by ebocher** [comment]
Hi @elbeejay ,

Thanks for the comments.
All GeoClimate algorithms are documented in the code using the javadoc syntax. Here you have an example : https://github.com/orbisgis/geoclimate/blob/master/geoindicators/src/main/groovy/org/orbisgis/geoclimate/geoindicators/BlockIndicators.groovy#L12

About potential reviewers there are  sjsrey, nuest, sgrieve, hugoledoux.

Note I will be OoO until middle of August

Best regards

Erwan

**Comment by elbeejay** [comment]
:wave: @nuest, @sgrieve, @abhishekvp, @omshinde, @arbennett, @oh-dechema, @jblindsay would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission is "GeoClimate: a Geospatial processing toolbox for environmental and climate studies". I am reaching out to you based on your experience with GIS and geospatial methods and/or expertise in Java/Groovy. 

This is a pre-review issue which is used to find reviewers. Once 3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks, although this can be extended if needed. If you are not able to review and have someone to recommend, please mention them here (in this case please mention their GitHub handle without the "@" symbol).

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) before the review process starts. 

Thank you, feel free to reach out if you have any questions about the JOSS review process. Please do not feel any pressure to accept this review request if you do not have the time or do not feel comfortable reviewing this software package, we appreciate and respect our peer-reviewers' time. 

-Jay

**Comment by abhishekvp** [comment]
Hi! thanks for the review invitation @elbeejay. I looked through the journal's conflict of interest policy. I declare that I do not have any conflict of interest. I hereby agree to review this submission for JOSS. Thanks!

**Comment by elbeejay** [comment]
@whedon add @abhishekvp as reviewer

**Comment by whedon** [comment]
OK, @abhishekvp is now a reviewer

**Comment by omshinde** [comment]
Hi @elbeejay! Thanks for the review invitation. I confirm that I do not hold any conflict of interest for this submission and would be happy to review this submission for JOSS. Regards!

**Comment by nuest** [comment]
@elbeejay Thanks for considering me - I am not able to perform a review at this point in time, as I'm taking a leave of absence until March next year.

**Comment by arbennett** [comment]
Hi @elbeejay - I would be happy to review this! I also do not hold any conflict of interest for this submission.

**Comment by elbeejay** [comment]
Great, thank you all. We will move this forward to review.

**Comment by elbeejay** [comment]
@whedon add @omshinde as reviewer

**Comment by whedon** [comment]
OK, @omshinde is now a reviewer

**Comment by elbeejay** [comment]
@whedon add @arbennett as reviewer

**Comment by whedon** [comment]
OK, @arbennett is now a reviewer

**Comment by elbeejay** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3541.
