### ISSUE TITLE
[PRE REVIEW]: Reel1.0 - A visualization tool for evaluating powder diffraction refinements

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3443]
**Submitting author:** @fgjorup (<a href="http://orcid.org/0000-0003-3902-0247">Frederik Holm Gjørup</a>)
**Repository:** <a href="https://github.com/fgjorup/Reel/" target ="_blank">https://github.com/fgjorup/Reel/</a>
**Version:** v.1.1.1
**Editor:** @rkurchin
**Reviewers:** @cmbiwer, mikapfl
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054/status.svg)](https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054"><img src="https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054/status.svg)](https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054)
```

**Author instructions**

Thanks for submitting your paper to JOSS @fgjorup. **Currently, there isn't an JOSS editor assigned** to your paper.

@fgjorup if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (148.7 files/s, 79194.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            275            220           5642
Qt                               1              0              0            732
Markdown                         1             10              0             27
DOS Batch                        2              0              0             19
-------------------------------------------------------------------------------
SUM:                            13            285            220           6420
-------------------------------------------------------------------------------


Statistical information for the repository '33153b005484da6d0915ff11' was
gathered on 2021/07/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Frederik                         1             0           6702           14.27
Frederik Holm Gjørup            17         11786          13655           54.18
fgjorup                          6         14761             53           31.55

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Frederik Holm Gjørup       6137           52.1          1.5                2.70
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3443 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch JOSS-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3443 with the following error: 
```
 ORCID looks malformed
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (0000-0003-3902-0247, 0000-0002-8022-5538, 0000-0001-6805-1232) for Frederik H. Gjørup , Mathias Mørch, & Mogens Christensen (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by arfon** [comment]
@fgjorup - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by fgjorup** [comment]
My suggestions for potential reviewers from the provided list, based on the topics _materials science, diffraction, neutrons, x-ray, and python_:
benjaminbolling
cmbiwer
pgg1610
jwuttke
mikapfl
KedoKudo
cmbiwer
stuartcampbell
marcocamma
taw10
yxqd

**Comment by kthyng** [comment]
Hi @rkurchin! I found another that may fit with your expertise. What do you think?

**Comment by kthyng** [comment]
@whedon invite @rkurchin as editor

**Comment by whedon** [comment]
@rkurchin has been invited to edit this submission.

**Comment by rkurchin** [comment]
@whedon assign @rkurchin as editor

**Comment by whedon** [comment]
OK, the editor is @rkurchin

**Comment by rkurchin** [comment]
@cmbiwer, @mikapfl, would you be willing to review this submission for JOSS?

We carry out our checklist-driven reviews here in GitHub issues according to [these guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html). You can find out more about this submission in the first comment in this issue. Note that our editorial robot whedon is having trouble compiling the PDF right now, but if you hop over to [the submission branch of their repo](https://github.com/fgjorup/Reel/tree/JOSS-submission) you can see the manuscript as well.

**Comment by rkurchin** [comment]
@fgjorup, could you please correct the ORCID issue referenced above? Currently, your author/ORCID list is formatted thusly:
```
  - name: Frederik H. Gjørup , Mathias Mørch, & Mogens Christensen
    orcid: 0000-0003-3902-0247, 0000-0002-8022-5538, 0000-0001-6805-1232
    affiliation: "1"
```
I believe replacing it with the following should fix it:
```
  - name: Frederik H. Gjørup
    orcid: 0000-0003-3902-0247
    affiliation: "1"

  - name: Mathias Mørch
    orcid: 0000-0002-8022-5538
    affiliation: "1"

  - name: Mogens Christensen
    orcid: 0000-0001-6805-1232
    affiliation: "1"
```

**Comment by mikapfl** [comment]
Hi,

I haven't done any Rietveld refinement myself, so I can't really review the scientific usefulness of the software and how it relates to the wider ecosystem of powder diffraction analysis software. If that is fine with you, I would be happy to do a review. (-:

Cheers,

Mika

**Comment by cmbiwer** [comment]
Hi, I have worked on several visualization tools/automation tools for diffraction analysis and Rietveld analysis, and I am available to review this submission.

**Comment by rkurchin** [comment]
@whedon assign @cmbiwer as reviewer

**Comment by whedon** [comment]
OK, @cmbiwer is now a reviewer

**Comment by rkurchin** [comment]
Thanks, Christopher! And thanks for info, Mika, I'll try one or two other people and come back to you if need be. :)

**Comment by rkurchin** [comment]
@stuartcampbell, would you be able/willing to review this submission to JOSS?

We carry out our checklist-driven reviews here in GitHub issues according to these guidelines. You can find out more about this submission in the first comment in this issue. Note that our editorial robot whedon is having trouble compiling the PDF right now, but if you hop over to the submission branch of their repo you can see the manuscript as well.

**Comment by rkurchin** [comment]
@marcocamma, would you be able/willing to review this submission to JOSS?

We carry out our checklist-driven reviews here in GitHub issues according to these guidelines. You can find out more about this submission in the first comment in this issue. Note that our editorial robot whedon is having trouble compiling the PDF right now, but if you hop over to the submission branch of their repo you can see the manuscript as well.

**Comment by rkurchin** [comment]
@mikapfl, you still game to take this one? It seems Christopher can cover the Rietveld-specific stuff, and I think your broader perspective could be helpful. I'll wait for a confirmation from you that it's still okay.

**Comment by rkurchin** [comment]
> @fgjorup, could you please correct the ORCID issue referenced above? Currently, your author/ORCID list is formatted thusly:
> 
> ```
>   - name: Frederik H. Gjørup , Mathias Mørch, & Mogens Christensen
>     orcid: 0000-0003-3902-0247, 0000-0002-8022-5538, 0000-0001-6805-1232
>     affiliation: "1"
> ```
> 
> I believe replacing it with the following should fix it:
> 
> ```
>   - name: Frederik H. Gjørup
>     orcid: 0000-0003-3902-0247
>     affiliation: "1"
> 
>   - name: Mathias Mørch
>     orcid: 0000-0002-8022-5538
>     affiliation: "1"
> 
>   - name: Mogens Christensen
>     orcid: 0000-0001-6805-1232
>     affiliation: "1"
> ```

@fgjorup, we should be close to having two reviewers and being ready to move this to the review stage, if you could resolve this so that we can build a proof, that would be great!

**Comment by mikapfl** [comment]
@rkurchin Sure, I would be happy to do a review!

**Comment by fgjorup** [comment]
@rkurchin I believe I have fixed the issue, though I may have missed something? I'm currently out of office, but I'll do my best to help remotely.

________________________________

**Comment by rkurchin** [comment]
@whedon add mikapfl as reviewer

**Comment by whedon** [comment]
OK, mikapfl is now a reviewer

**Comment by rkurchin** [comment]
@whedon generate pdf from branch JOSS-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03443/joss.03443/10.21105.joss.03443.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03443/joss.03443/10.21105.joss.03443.pdf) :page_facing_up: :point_left:

**Comment by rkurchin** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3546.
