### ISSUE TITLE
[PRE REVIEW]: array_split: Multi-dimensional array partitioning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#345]
**Submitting author:** @Shane-J-Latham (<a href="http://orcid.org/0000-0001-8033-4665">Shane J. Latham</a>)
**Repository:** <a href="https://github.com/array-split/array_split" target ="_blank">https://github.com/array-split/array_split</a>
**Version:** 0.5.0
**Editor:** @arfon
**Reviewer:** @dvalters

**Author instructions**

Thanks for submitting your paper to JOSS @Shane-J-Latham. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Shane-J-Latham if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](http://joss.theoj.org/about#paper_structure) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by Shane-J-Latham** [comment]
Hi @arfon, thanks for taking the time to look at this.

> Could you confirm here that there is a research application

I would say it is a tool for "enabling research", particularly in HPC where
you want to calculate domain-decomposition for data-parallelism
(for large-image processing, say)...
If you don't think this is a fit for JOSS, happy to withdraw.

Thanks again.

**Comment by arfon** [comment]
Thanks @Shane-J-Latham. It sounds like this submission falls into the ['utility package' category](http://joss.theoj.org/about#submission_requirements) which _is_ acceptable as long as it's not a very small contribution.

👍 I'm happy to proceed with this submission.

**Comment by dvalters** [comment]
@arfon I think this is quite an interesting submission (I can see applications of it for research as a utility package). I'd be interested in reviewing it but would not be able to start until end of next week.

**Comment by arfon** [comment]
> I'd be interested in reviewing it but would not be able to start until end of next week.

OK no problem.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @dvalters as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dvalters

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/373. Feel free to close this issue now!

**Comment by arfon** [comment]
@dvalters @Shane-J-Latham - see you over in #373 for the actual review.
