### ISSUE TITLE
[PRE REVIEW]: popoff: POtential Parameter Optimisation for Force-Fields

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3451]
**Submitting author:** @LMMorgan (<a href="http://orcid.org/0000-0002-6432-3760">Lucy M. Morgan</a>)
**Repository:** <a href="https://github.com/LMMorgan/PopOff" target ="_blank">https://github.com/LMMorgan/PopOff</a>
**Version:** v1.0.0
**Editor:** @dpsanders
**Reviewers:** @marshallmcdonnell, @lscalfi
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/20aac788629856e4d0aba5f6940df285/status.svg)](https://joss.theoj.org/papers/20aac788629856e4d0aba5f6940df285)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/20aac788629856e4d0aba5f6940df285"><img src="https://joss.theoj.org/papers/20aac788629856e4d0aba5f6940df285/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/20aac788629856e4d0aba5f6940df285/status.svg)](https://joss.theoj.org/papers/20aac788629856e4d0aba5f6940df285)
```

**Author instructions**

Thanks for submitting your paper to JOSS @LMMorgan. **Currently, there isn't an JOSS editor assigned** to your paper.

@LMMorgan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0022-3719/18/6/010 is OK
- 10.1021/acsaem.9b01870 is OK
- 10.1021/ja0434073 is OK
- 10.1021/am504351p is OK
- 10.1063/1.367521 is OK
- 10.1143/JPSJS.79SA.59 is OK
- 10.1021/jp984398l is OK
- 10.1021/jp506025k is OK
- 10.1039/C9CP01585J is OK
- 10.1098/rspa.1924.0082 is OK
- 10.1098/rspa.1938.0173 is OK
- 10.1039/a606455h is OK
- 10.1080/13642819608239107 is OK
- 10.1088/1361-651x/aa6ecf is OK
- 10.1088/0965-0393/25/1/014001 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03451/joss.03451/10.21105.joss.03451.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03451/joss.03451/10.21105.joss.03451.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (880.2 files/s, 116323.8 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           36            543            811           2475
XML                               1              0            129           1790
TeX                               1             17              0            192
Jupyter Notebook                  5              0           1023            179
reStructuredText                  8            114             78            158
Bourne Again Shell                1             31              9            141
Markdown                          3             42              0            117
DOS Batch                         1              8              1             26
YAML                              1              1              4             18
make                              1              4              7              9
JSON                              2              0              0              2
--------------------------------------------------------------------------------
SUM:                             60            760           2062           5107
--------------------------------------------------------------------------------


Statistical information for the repository 'b544612265ee1677c90b071f' was
gathered on 2021/07/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Benjamin Morgan                  1           232              0            1.50
LMMorgan                         4             7            254            1.68
Lucy Morgan                     81          9128           5697           95.71
Pezhman Zarabadi-Poo             1            24              0            0.15
Thomas Young Cluster             2           121             15            0.88
connorourke                      1             8              4            0.08

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
LMMorgan                      2           28.6          1.4                0.00
Lucy Morgan                3803           41.7          9.4                6.21
Pezhman Zarabadi-Poo         24          100.0          0.3                8.33
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @dpsanders as editor

**Comment by whedon** [comment]
@dpsanders has been invited to edit this submission.

**Comment by dpsanders** [comment]
@whedon assign @dpsanders as editor

**Comment by whedon** [comment]
OK, the editor is @dpsanders

**Comment by LMMorgan** [comment]
I have been through the list of potential reviews and selected 5 which seem relevant. Their usernames are:
1. lscalfi
2. marshallmcdonnell
3. masrul
4. amandadumi
5. p-snft

**Comment by LMMorgan** [comment]
Good evening @dpsanders,

I was wondering if there is any update on the progress of this submission? Have any potential reviews accepted?

Best regards,
Lucy

**Comment by dpsanders** [comment]
👋 @LMMorgan: Apologies for the delay in getting to this. This looks like a nice package and paper!

Here are some initial comments:

- I suggest to reorder the text so that a non-specialist reader immediately understands the context, e.g. by putting the Statement of Need first

- Please explain what VASP and LAMMPS are, with references, and what they output that you then fit.

- Do you have references to the research applications?

- differentail -> differential (line 68)

- I don’t see where the docs are for the package. Maybe this is just a missing link from the GitHub repo, since there is a `docs` folder?

**Comment by dpsanders** [comment]
Also I personally like to see a small working example of the package in the paper, with example output.

**Comment by dpsanders** [comment]
Also there seems to be some inconsistency in the capitalisation of `PopOff` vs `popoff`.

**Comment by LMMorgan** [comment]
Hi @dpsanders thank you for getting back to me. I understand you are all quite busy after the hiatus and things are likely to be fairly slow.

In regards to your comments. I shall start addressing your points this week. I am not sure where the docs link has disappeared to.

A quick query, when you say "a small working example of the package in the paper, with example output", do you mean you would like a working example directory in the repo? (I should be able to do this fairly swiftly for Na3OCl or another structure) I have not seen anyone present a working example written into the paper before, but if the latter is what you are asking for, could you send an example where this has been done, so to use as a guide.

Many thanks,
Lucy

**Comment by LMMorgan** [comment]
Dear @dpsanders,

I have reordered the text and explained VASP and LAMMPS, with references. I have also added the missing `docs` link in the repo (it got missed off the previous commit) and I have adding the input and output files for an example (Na3OCl) to `userguides/example_Na3OCl`.

In regards to `PopOff` vs `popoff`, the lower case is used in code snippets as this in how the directories are labelled, and the capitalised is use in text as the formal acronym for the code. I think there was one place where this was incorrect and I have now corrected it.

I have also added a guide to compiling the cod and prerequisites in a conda environment for use on HPCs, as it can be challenging to compile LAMMPS with a python interface if you don't know what you are doing.

Please let me know if there are any other updates you would like.

Kind regards,
Lucy

**Comment by dpsanders** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3451 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:749:in `rescue in transmit': Timed out connecting to server (RestClient::Exceptions::OpenTimeout)
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:119:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:13:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:59:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'
/app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:947:in `initialize': execution expired (Net::OpenTimeout)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:947:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	from /app/vendor/bundle/ruby/2.6.0/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:119:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:13:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:59:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by dpsanders** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03451/joss.03451/10.21105.joss.03451.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03451/joss.03451/10.21105.joss.03451.pdf) :page_facing_up: :point_left:

**Comment by dpsanders** [comment]
👋 @LMMorgan: Apologies for the delay in getting to this.

The paper is much improved, thanks! I think that`popoff` in the title itself should be `PopOff`?

I now see the docs link in the repo, thanks.
I see that the example notebooks require a VASP license and an HPC. 
Is it possible to run a simpler example using only open-source software? This is not a requirement for acceptance in JOSS, but would definitely make the paper more broadly useful.

Thanks!

**Comment by dpsanders** [comment]
👋 @lscalfi, @marshallmcdonnell: Would you be available and willing to review this submission for [JOSS](https://joss.theoj.org/), the Journal of Open Source Software? Reviews are focused on the software and take place via GitHub issues. Thanks!

**Comment by marshallmcdonnell** [comment]
@dpsanders Yes, I'd be happy to be a reviewer for this submission!
Thanks for the opportunity.

**Comment by lscalfi** [comment]
@dpsanders yes I would be happy to!

**Comment by dpsanders** [comment]
@whedon add @marshallmcdonnell as reviewer

**Comment by whedon** [comment]
OK, @marshallmcdonnell is now a reviewer

**Comment by dpsanders** [comment]
@whedon add @lscalfi as reviewer

**Comment by whedon** [comment]
OK, @lscalfi is now a reviewer

**Comment by dpsanders** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3747.

**Comment by dpsanders** [comment]
Many thanks @lscalfi and @marshallmcdonnell for agreeing to review this submission. Please head over to #3747, where you will find a checklist to guide the review process!

**Comment by LMMorgan** [comment]
> I see that the example notebooks require a VASP license and an HPC.
> Is it possible to run a simpler example using only open-source software? This is not a requirement for acceptance in JOSS, but would definitely make the paper more broadly useful.

Hi @dpsanders, thank you for the update. The example I have given includes the VASP input files so there is no requirement to have a licence to run the example. If a user wanted to run their own potential fit from their dataset, they would need a vast licence or convert their output to a `vasprun.xml` format. I am hoping to generalise the input to include open-source in the next version of the code.

@marshallmcdonnell and @lscalfi, thank you for agreeing to be reviewers. I look forward to hearing from you.

Kind regards,
Lucy
