### ISSUE TITLE
[PRE REVIEW]: ELIXIR TeSS: The Training eSupport System

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#346]
**Submitting author:** @njall (<a href="http://orcid.org/0000-0002-2627-0231">Niall Beard</a>)
**Repository:** <a href="https://github.com/ElixirUK/TeSS" target ="_blank">github.com/ElixirUK/TeSS</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @njall. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@njall if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)?

Many thanks!

**Comment by arfon** [comment]
👋 @njall - please see my comment above.

**Comment by arfon** [comment]
@labarba - I'm wondering whether this would be a better submission for JOSE?

**Comment by njall** [comment]
@arfon apologies for not seeing your previous comment. I understand it TeSS might not meet JOSS' criteria, JOSE does sound like a great fit

**Comment by arfon** [comment]
> @arfon apologies for not seeing your previous comment. I understand it TeSS might not meet JOSS' criteria, JOSE does sound like a great fit

OK great. I'm going to close this issue now. Please keep an eye on http://jose.theoj.org for when they might be open for submissions.
