### ISSUE TITLE
[PRE REVIEW]: sandpyper: A Python package for UAV-SfM beach volumetric and behavioural analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3462]
**Submitting author:** @npucino (<a href="http://orcid.org/0000-0001-6260-6647">Nicolas Pucino</a>)
**Repository:** <a href="https://github.com/npucino/sandpyper.git" target ="_blank">https://github.com/npucino/sandpyper.git</a>
**Version:** v0.1.1
**Editor:** @kbarnhart
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8d672154d54178855364e7ba06f3f8a6/status.svg)](https://joss.theoj.org/papers/8d672154d54178855364e7ba06f3f8a6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8d672154d54178855364e7ba06f3f8a6"><img src="https://joss.theoj.org/papers/8d672154d54178855364e7ba06f3f8a6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8d672154d54178855364e7ba06f3f8a6/status.svg)](https://joss.theoj.org/papers/8d672154d54178855364e7ba06f3f8a6)
```

**Author instructions**

Thanks for submitting your paper to JOSS @npucino. **Currently, there isn't an JOSS editor assigned** to your paper.

@npucino if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (389.1 files/s, 272323.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          11           1281           1112           3644
Jupyter Notebook                11              0          23918           1052
Markdown                        16            170              0            405
TeX                              1              7              0            384
YAML                             6             24             10            175
HTML                             1              2              0              9
-------------------------------------------------------------------------------
SUM:                            46           1484          25040           5669
-------------------------------------------------------------------------------


Statistical information for the repository '3aed8cfcba580a498ed182a7' was
gathered on 2021/07/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nicolas Pucino                  83          7677           2054           84.52
npucino                         16          1078            704           15.48

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Nicolas Pucino             5529           72.0          0.5                6.04
npucino                     508           47.1          3.1               17.13
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1111/0031-868x.00152 may be a valid DOI for title: Application of Digital Photogrammetry to Complex Topography for Geomorphological Research
- 10.1038/s41598-021-83477-6 may be a valid DOI for title: Citizen science for monitoring seasonal-scale beach erosion and behaviour with aerial drones
- 10.1016/j.ecolecon.2006.10.022 may be a valid DOI for title: The coasts of our world: Ecological, economic and social importance
- 10.1016/j.ocecoaman.2018.01.001 may be a valid DOI for title: National sediment compartment framework for Australian coastal management
- 10.1016/j.isprsjprs.2015.02.009 may be a valid DOI for title: UAV photogrammetry for topographic monitoring of coastal areas

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03462/joss.03462/10.21105.joss.03462.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03462/joss.03462/10.21105.joss.03462.pdf) :page_facing_up: :point_left:

**Comment by npucino** [comment]
Hi,
please find here a list of potential reviewers:

1. TomasBeuzen
2. elbeejay
3. chrisleaman
4. hugoledoux
5. sgrieve

Thanks,
Nick

**Comment by Kevin-Mattheus-Moerman** [comment]
@npucino thanks for this submission. Would you be able to check those missing DOI's :point_up:, you can edit the paper and update it here by calling `@whedon generate pdf`.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @kbarnhart as editor

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by npucino** [comment]
Thanks @Kevin-Mattheus-Moerman for handle my submission. I actually already updated the bip file but forgot to call whedon. I do it now. Thanks, Nick

**Comment by npucino** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03462/joss.03462/10.21105.joss.03462.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03462/joss.03462/10.21105.joss.03462.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/0031-868x.00152 is OK
- 10.1371/journal.pone.0118571 is OK
- 10.1890/10-1510.1 is OK
- 10.1038/s41598-021-83477-6 is OK
- 10.1016/j.earscirev.2017.04.011 is OK
- 10.1016/j.ecolecon.2006.10.022 is OK
- 10.1016/j.ocecoaman.2018.01.001 is OK
- 10.1016/j.isprsjprs.2015.02.009 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kbarnhart** [comment]
@Kevin-Mattheus-Moerman yes I can handle this.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
@npucino I'll start actively handling this in the next few days.

**Comment by kbarnhart** [comment]
@npucino I wanted to check in with two clarification questions. First, it seems like many of your functions have docstrings, but I can't seem to find API-level documentation. Does it exist somewhere that I've been unable to find?

The [JOSS documentation regarding API documentation](https://joss.readthedocs.io/en/latest/review_criteria.html#api-documentation) states:

> Reviewers should check that the software API is documented to a suitable level.
> 
> **Good**: All functions/methods are documented including example inputs and outputs
> **OK**: Core API functionality is documented
> **Bad** (not acceptable): API is undocumented
 

Second, it does not seem like this package has any tests (the file `tests/test_sandpyper.py` lacks content). Is there another place where you have written tests for this package?
 

The [JOSS documentation regarding tests](https://joss.readthedocs.io/en/latest/review_criteria.html#tests) states:


> Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.
> 
> **Good**: An automated test suite hooked up to an external service such as Travis-CI or similar
> **OK**: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)
> **Bad** (not acceptable): No way for you, the reviewer, to objectively assess whether the software works


Documentation should indicate how to verify the software is working correctly. Such tests might include, but not necessarily be limited to, verification that the algorithms for change detection are implemented correctly.

**Comment by npucino** [comment]
Hi @kbarnhart , thanks for handling my submission.
Here is the API level documentation https://npucino.github.io/sandpyper/, it is in the README file of the project.
For the automated tests, I just noticed that it is empty. I wanted to implement some tests but then I preferred do the tests using GitHub actions and workflows (here: https://github.com/npucino/sandpyper/actions). These automated tests are used to check if the package can be build in different operating systems and python versions. I have also created jupyter notebooks examples to follow and check if the package works and added some datasets to work with (https://github.com/npucino/sandpyper/blob/master/doc_data.rar).

Thanks for your time!
Nick

**Comment by kbarnhart** [comment]
@npucino thank you for those clarifications. Based on my initial review of the software and consultation with the rest of the editorial board, my decision is to reject the submission with a recommendation that your resubmit after the following issues have been considered and addressed:

1. Creation of tests for the package. Documentation should indicate how a user can verify the software is working correctly. Such tests should cover the core functionality of the software. They might include, but not necessarily be limited to, verification that the considered analyses are implemented correctly. Verification that Jupyter notebooks can run without error are certainly a reasonable part of a test suite, but are not sufficient as they do not verify that the core algorithms are implemented correctly. 

2. Expansion of the documentation to describe in more detail many of the expected inputs and outputs. 
    
    a. Many of your functions take geodatabases, pandas dataframes, and/or dictionaries as inputs. The documentation should provide information about what those objects need to look like (e.g., a dataframe with a specific set of columns and rows, a geodatabase with the following elements, named in a particular way), and a dictionary with the following structure.
    
    b. Similarly, some functions take file path strings as inputs. More detail should be provided in the documentation on how the indicated directory is structured. 

3. Revision of the Jupyter notebooks to address the following concerns:
    
    a. Provide instruction regarding how to use the test data. Looking at doc_data.rar, I see you’ve prepared this test data, but there is no discussion of how to use it. I’d recommend you revise the documentation to describe what is in this extracted folder. The notebooks can be revised to extract these files if not yet extracted and then use the file paths to this data rather than file paths on your system. 
    
    b. Notebooks provide a good skeleton outline on how sandpyper can be used, but provide insufficient explanation of what the methods are. An example where you do a good job with this well is in the Volumetrics notebook where you explaining how mean elevation change is calculated. This level of explanation should exist throughout the notebooks. 
    
    c. Notebooks have errors, and indicate cells run out of sequence.

4. A few less critical points, but things I’d recommend addressing before resubmitting. 
    
    a. Expand the paper to contrast this package with existing tools. The other tool I immediately think of is the [Digital Shoreline Analysis System](https://www.usgs.gov/centers/whcmsc/science/digital-shoreline-analysis-system-dsas?qt-science_center_objects). 
    b. Some docstrings appear malformed. 

If you have any questions or clarifications, feel free to follow up here or directly at krbarnhart@usgs.gov

**Comment by kbarnhart** [comment]
@openjournals/joss-eics: I've recommended that this submission be rejected.

**Comment by npucino** [comment]
Dear @kbarnhart , thanks for the time spent in reviewing my submission. I really appreciate your feedbacks and agree with the points you raised for the rejection. I will work on those points and resubmit as soon as I fixed it. Thanks again for this learning experience! Regards, Nick

**Comment by kbarnhart** [comment]
@npucino I'm glad to here this feedback was helpful. I look forward to seeing this resubmitted.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
