### ISSUE TITLE
[PRE REVIEW]: lhorizon: geometry and targeting via JPL Horizons

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3463]
**Submitting author:** @m-stclair (<a href="http://orcid.org/0000-0002-7877-3148">Michael St. Clair</a>)
**Repository:** <a href="https://github.com/MillionConcepts/lhorizon" target ="_blank">https://github.com/MillionConcepts/lhorizon</a>
**Version:** 1.0.0
**Editor:** @arfon
**Reviewers:** @malmans2, @steo85it
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/df75367d9476f77b878c08e009b764ee/status.svg)](https://joss.theoj.org/papers/df75367d9476f77b878c08e009b764ee)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/df75367d9476f77b878c08e009b764ee"><img src="https://joss.theoj.org/papers/df75367d9476f77b878c08e009b764ee/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/df75367d9476f77b878c08e009b764ee/status.svg)](https://joss.theoj.org/papers/df75367d9476f77b878c08e009b764ee)
```

**Author instructions**

Thanks for submitting your paper to JOSS @m-stclair. **Currently, there isn't an JOSS editor assigned** to your paper.

@m-stclair if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3463 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Michael Clair, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (670.9 files/s, 91508.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          24            254            529           1591
Markdown                         4            249              0            821
HCL                              1            180              0            427
Jupyter Notebook                 3              0            460            123
TeX                              1             11              1             90
YAML                             2              0              0             38
-------------------------------------------------------------------------------
SUM:                            35            694            990           3090
-------------------------------------------------------------------------------


Statistical information for the repository 'ebd247b1fcf2357c405f86da' was
gathered on 2021/07/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
m-stclair                        1           309             22            0.90
michael                          2           691              2            1.89
mstclair@millionconc            23         18486          17088           97.20

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
mstclair@millionconc       2374           12.8          0.8               10.11
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3847/1538-3881/aafc33 is OK
- 10.3847/1538-3881/aabc4f is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.21105/joss.02050 is INVALID because of 'https://doi.org/' prefix
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@m-stclair thanks for this submission. I believe the paper compilation might have been unsuccessful due to the formatting of the affiliations. I attempted a fix which you can review and accept here: https://github.com/MillionConcepts/lhorizon/pull/3). 

Also please check the invalid DOI listed :point_up:.

You can call `@whedon generate pdf` here to update the paper.

**Comment by Kevin-Mattheus-Moerman** [comment]
@m-stclair our editors and this domain are currently handling many other submissions. I have therefore assigned the `waitlisted` label to this submission. We will assign  handling editor as soon as one becomes available. Thank you for your patience.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon this looks like something you could potentially handle or suggest another editor for.

**Comment by m-stclair** [comment]
Thank you for your notes! I have merged your fix and fixed the DOI, and the paper now appears to compile successfully.

**Comment by m-stclair** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03463/joss.03463/10.21105.joss.03463.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03463/joss.03463/10.21105.joss.03463.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@m-stclair – could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by m-stclair** [comment]
@arfon 

I think any of these people might be good candidates:

malmans2
AndrewAnnex
steo85it
nmstreethran
patrickcgray
semiautomaticgit
usethedata

**Comment by arfon** [comment]
:wave: @malmans2 @AndrewAnnex @steo85it – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is [_lhorizon: geometry and targeting via JPL Horizons_](https://github.com/MillionConcepts/lhorizon), a Python package for interacting with the JPL Horizons service.

**Comment by AndrewAnnex** [comment]
hey @arfon, I would love to be reviewer but I have worked on proposals with/contributed code to @MillionConcepts and @m-stclair, and so I think I have a personal association COI with the company and first author, and this project also lists SpiceyPy as a dependency. 

That said the most recent proposal I was listed on with @m-stclair was not funded (IIRC also in 2019). Let me know if you have any questions.

**Comment by arfon** [comment]
> hey @arfon, I would love to be reviewer but I have worked on proposals with/contributed code to @MillionConcepts and @m-stclair, and so I think I have a personal association COI with the company and first author, and this project also lists SpiceyPy as a dependency.

Got it, thanks @AndrewAnnex. I'll keep looking for alternative reviewers for now then.

**Comment by malmans2** [comment]
Hi @arfon, I'm happy to review this!

(Solar system dynamics is not really my field though, just in case you have other reviewers in mind that are also target audience)

**Comment by arfon** [comment]
Thanks @malmans2!

I'll go ahead and add you as a review now but won't actually start the review until we have a second reviewer signed up.

**Comment by arfon** [comment]
@whedon add @malmans2 as reviewer

**Comment by whedon** [comment]
OK, @malmans2 is now a reviewer

**Comment by steo85it** [comment]
Hi @arfon, happy to review this.
-------- Messaggio originale --------Da: Arfon Smith ***@***.***> Data: 14/07/21  6:11 AM  (GMT-05:00) A: openjournals/joss-reviews ***@***.***> Cc: Stefano Bertone ***@***.***>, Mention ***@***.***> Oggetto: Re: [openjournals/joss-reviews] [PRE REVIEW]: lhorizon: geometry and targeting via JPL Horizons (#3463) 

👋 @malmans2 @AndrewAnnex @steo85it – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is lhorizon: geometry and targeting via JPL Horizons, a Python package for interacting with the JPL Horizons service.

**Comment by arfon** [comment]
@whedon add @steo85it as reviewer

**Comment by whedon** [comment]
OK, @steo85it is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3495.

**Comment by arfon** [comment]
@malmans2, @steo85it – many thanks for agreeing to review here! See you over in #3495 where the actual review will take place.
