### ISSUE TITLE
[PRE REVIEW]: NoisySignalIntegration.jl: A Julia package for uncertainty evaluation of numeric integrals

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3468]
**Submitting author:** @nluetts (<a href="http://orcid.org/0000-0001-8459-1714">Nils Lüttschwager</a>)
**Repository:** <a href="https://github.com/nluetts/NoisySignalIntegration.jl" target ="_blank">https://github.com/nluetts/NoisySignalIntegration.jl</a>
**Version:** v0.2.1
**Editor:** @jbytecode
**Reviewers:** @myousefi2016, @mseri
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8d555b9e8738857733e2dad881f27088/status.svg)](https://joss.theoj.org/papers/8d555b9e8738857733e2dad881f27088)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8d555b9e8738857733e2dad881f27088"><img src="https://joss.theoj.org/papers/8d555b9e8738857733e2dad881f27088/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8d555b9e8738857733e2dad881f27088/status.svg)](https://joss.theoj.org/papers/8d555b9e8738857733e2dad881f27088)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nluetts. **Currently, there isn't an JOSS editor assigned** to your paper.

@nluetts if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (969.4 files/s, 105795.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           19            394            108           1647
Markdown                         9            298              0            859
TOML                             2              4              0             46
YAML                             1              2              0             25
-------------------------------------------------------------------------------
SUM:                            31            698            108           2577
-------------------------------------------------------------------------------


Statistical information for the repository '1fce88bc47e1e6fc9a7eabd2' was
gathered on 2021/07/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3468 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03468/joss.03468/10.21105.joss.03468.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03468/joss.03468/10.21105.joss.03468.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @jbytecode as editor

**Comment by whedon** [comment]
@jbytecode has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jbytecode I would be grateful if you could help with this submission. Note if you have been invited for a `waitlisted` submission those take precedence and need to be handled first.

**Comment by jbytecode** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jbytecode

**Comment by jbytecode** [comment]
Dear @Kevin-Mattheus-Moerman, 

I gladly accept to handle this submission. Thank you.

**Comment by jbytecode** [comment]
Dear @nluetts,

Do you have suggestions for the potential reviewers for your submission? You can use the [list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit) and filter some proper reviewers. If you use this list, please start your search from the bottom of the list.

**Comment by nluetts** [comment]
Dear @jbytecode,

thank you for handling my submission. I went through the list and suggest the following potential reviewers:

* [qpmnguyen](https://github.com/qpmnguyen) (entry 1599)
* [rchg](https://github.com/rchg) (entry 1103)
* [ali-ramadhan](https://github.com/ali-ramadhan) (entry 733)

**Comment by jbytecode** [comment]
Hi @qpmnguyen and @rchg, would you be willing to assist in reviewing this submission for JOSS?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "NoisySignalIntegration.jl: A Julia package for uncertainty evaluation of numeric integrals". You can find more information at the top of this Github issue.

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by jbytecode** [comment]
Hi @myousefi2016, @ranocha, @mvaldes 👋👋👋

Would you be willing to assist in reviewing this submission for JOSS (Journal of Open Source Software) ?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "NoisySignalIntegration.jl: A Julia package for uncertainty evaluation of numeric integrals". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3468).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by myousefi2016** [comment]
Hi @jbytecode

Thanks for inviting me to review this open-source research software. I would be happy to help.

Best,

Mehrdad

**Comment by jbytecode** [comment]
@whedon add @myousefi2016 as reviewer

@myousefi2016 thank you for accepting! the review process will start after we assign the second reviewer. please keep on touch!

**Comment by whedon** [comment]
OK, @myousefi2016 is now a reviewer

**Comment by jbytecode** [comment]
Hi @mseri 👋👋👋

Would you be willing to assist in reviewing this submission for JOSS (Journal of Open Source Software) ?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "NoisySignalIntegration.jl: A Julia package for uncertainty evaluation of numeric integrals". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3468).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by mseri** [comment]
Hi @jbytecode, I would be happy to help

**Comment by jbytecode** [comment]
@whedon add @mseri as reviewer

**Comment by whedon** [comment]
OK, @mseri is now a reviewer

**Comment by jbytecode** [comment]
@whedon start review

@myousefi2016 and @mseri thank you for accepting to be reviewers. Our bot, Whedon, will not create a new issue for reviewing. In this page, there will be 20 checkboxes for each reviewer. These boxes indicate the corresponding reviewing task. Please have a look at the [Reviewing Guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) page. 

Please do not hesitate to ask me anything.

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3526.
