### ISSUE TITLE
[PRE REVIEW]: buildH: Build hydrogen atoms from united-atom molecular dynamics of lipids and calculate the order parameters

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3469]
**Submitting author:** @patrickfuchs (<a href="http://orcid.org/0000-0001-7117-994X">Patrick Fuchs</a>)
**Repository:** <a href="https://github.com/patrickfuchs/buildH" target ="_blank">https://github.com/patrickfuchs/buildH</a>
**Version:** v1.5.0
**Editor:** @richardjgowers
**Reviewers:** @lilyminium, @ojeda-e, @blakeaw
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/694be62b08a4d47dc7dd695a418f6938/status.svg)](https://joss.theoj.org/papers/694be62b08a4d47dc7dd695a418f6938)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/694be62b08a4d47dc7dd695a418f6938"><img src="https://joss.theoj.org/papers/694be62b08a4d47dc7dd695a418f6938/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/694be62b08a4d47dc7dd695a418f6938/status.svg)](https://joss.theoj.org/papers/694be62b08a4d47dc7dd695a418f6938)
```

**Author instructions**

Thanks for submitting your paper to JOSS @patrickfuchs. **Currently, there isn't an JOSS editor assigned** to your paper.

@patrickfuchs if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/acs.jctc.7b00643 is OK
- 10.1021/acs.jpcb.5b04878 is OK
- 10.1039/C6CP04883H is OK
- 10.1021/acs.jpcb.9b06091 is OK
- 10.1186/1758-2946-3-33 is OK
- 10.1021/ct3003157 is OK
- 10.1021/jp410344g is OK
-  10.25080/Majora-629e541a-00e  is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1145/2833157.2833162 is OK
- 10.12688/f1000research.11407.1 is OK
- 10.1371/journal.pcbi.1005412 is OK
- 10.1021/jp101759q is OK
- 10.1039/C0SM00457J is OK
- 10.1007/978-1-59745-519-0_7 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/0010-4655(95)00042-E is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.softx.2015.06.001 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0006-3495(95)80350-4 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0006-3495(97)78845-3 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/jcc.21787 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S0304-4157(97)00008-7 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/S1359-0294(00)00058-3 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.5281/zenodo.4748646 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (725.6 files/s, 84863.4 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code
---------------------------------------------------------------------------------------
Python                                  19            603           1476           1570
Markdown                                18            434              0            941
Windows Module Definition               13              1              0            771
JSON                                    14              0              0            563
TeX                                      1             24              0            292
YAML                                     7             32             26            162
Jupyter Notebook                         5              0           3531             92
reStructuredText                        13             50             58             67
make                                     2             20             10             37
---------------------------------------------------------------------------------------
SUM:                                    92           1164           5101           4495
---------------------------------------------------------------------------------------


Statistical information for the repository 'f1d0cb1f2b2136ce24de6660' was
gathered on 2021/07/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
ABacle                           6           313             83            2.42
Abacle                           1            84              0            0.51
Hubert                          85          5342           3209           52.24
Pierre Poulain                  18           414            340            4.61
patrickfuchs                    97          3667           2917           40.22

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Hubert                     3324           62.2          8.3               17.33
Pierre Poulain              185           44.7          5.6               29.19
patrickfuchs                140            3.8          7.8                8.57
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03469/joss.03469/10.21105.joss.03469.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03469/joss.03469/10.21105.joss.03469.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@patrickfuchs thank you for your submission to JOSS. Can you please check those invalid DOI's :point_up: 
Note that you can call `@whedon generate pdf` to update the paper and `@whedon check references` to update the reference check.

**Comment by Kevin-Mattheus-Moerman** [comment]
@patrickfuchs I have added the `waitlisted` label to this submission as all editors in this domain are currently preoccupied with other submissions. We will assign an editor once one becomes available. 

@richardjgowers perhaps you could handle this submission once you are available?

**Comment by richardjgowers** [comment]
Yeah I can take this.

**Comment by patrickfuchs** [comment]
Thank you @Kevin-Mattheus-Moerman and @richardjgowers for handling and editing the submission of our submission. 
I have fixed the DOI's.

**Comment by patrickfuchs** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/acs.jctc.7b00643 is OK
- 10.1021/acs.jpcb.5b04878 is OK
- 10.1039/C6CP04883H is OK
- 10.1021/acs.jpcb.9b06091 is OK
- 10.1016/0010-4655(95)00042-E is OK
- 10.1016/j.softx.2015.06.001 is OK
- 10.1016/S0006-3495(95)80350-4 is OK
- 10.1186/1758-2946-3-33 is OK
- 10.1016/S0006-3495(97)78845-3 is OK
- 10.1021/ct3003157 is OK
- 10.1021/jp410344g is OK
-  10.25080/Majora-629e541a-00e  is OK
- 10.1002/jcc.21787 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1145/2833157.2833162 is OK
- 10.12688/f1000research.11407.1 is OK
- 10.1371/journal.pcbi.1005412 is OK
- 10.1021/jp101759q is OK
- 10.1016/S0304-4157(97)00008-7 is OK
- 10.1016/S1359-0294(00)00058-3 is OK
- 10.1039/C0SM00457J is OK
- 10.1007/978-1-59745-519-0_7 is OK
- 10.5281/zenodo.4748646 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by patrickfuchs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03469/joss.03469/10.21105.joss.03469.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03469/joss.03469/10.21105.joss.03469.pdf) :page_facing_up: :point_left:

**Comment by patrickfuchs** [comment]
Regarding potential reviewers, those with keywords Python and Molecular Dynamics or Molecular Simulations should be well suited. For example, we spotted these ones: joaorodrigues, diegoenry, fdroessler, khinsen, pszi1ard, rvhonorato, xyzmjf, junghans.

**Comment by Kevin-Mattheus-Moerman** [comment]
@richardjgowers great. Feel free to assign yourself at any time or let me know when I can assign you.

**Comment by kthyng** [comment]
Ok I am going to just go ahead and assign. Thanks @richardjgowers!

**Comment by kthyng** [comment]
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment]
OK, the editor is @richardjgowers

**Comment by richardjgowers** [comment]
@whedon add @lilyminium as reviewer

**Comment by whedon** [comment]
OK, @lilyminium is now a reviewer

**Comment by richardjgowers** [comment]
@ojeda-e @blakeaw would you be interested in reviewing this?

**Comment by ojeda-e** [comment]
Yes, absolutely @richardjgowers Sounds great.

**Comment by richardjgowers** [comment]
@whedon add @ojeda-e as reviewer

**Comment by whedon** [comment]
OK, @ojeda-e is now a reviewer

**Comment by blakeaw** [comment]
Sure, @richardjgowers.

**Comment by richardjgowers** [comment]
@whedon add @blakeaw as reviewer

**Comment by whedon** [comment]
OK, @blakeaw is now a reviewer

**Comment by richardjgowers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3521.
