### ISSUE TITLE
[PRE REVIEW]: sacio: A library for Seismic Analysis Code data files

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3470]
**Submitting author:** @savage13 (<a href="http://orcid.org/0000-0002-9252-6282">Brian Savage</a>)
**Repository:** <a href="https://github.com/savage13/sacio" target ="_blank">https://github.com/savage13/sacio</a>
**Version:** 1.0.2
**Editor:** @danielskatz
**Reviewers:** @chad-iris, @cja12, @jkmacc-LANL
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/46f90cf1fcfd3850e8a54ddd7f2af5d9/status.svg)](https://joss.theoj.org/papers/46f90cf1fcfd3850e8a54ddd7f2af5d9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/46f90cf1fcfd3850e8a54ddd7f2af5d9"><img src="https://joss.theoj.org/papers/46f90cf1fcfd3850e8a54ddd7f2af5d9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/46f90cf1fcfd3850e8a54ddd7f2af5d9/status.svg)](https://joss.theoj.org/papers/46f90cf1fcfd3850e8a54ddd7f2af5d9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @savage13. **Currently, there isn't an JOSS editor assigned** to your paper.

@savage13 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2172/110248 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.24 s (948.7 files/s, 184976.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           115            417           1044          13126
C                               17           1070           4695           9423
Bourne Shell                     8            724           1057           5513
JavaScript                      73            100            187           2043
CSS                              4            338             80           1664
C/C++ Header                     7            163           1019           1191
m4                               2             93             21            837
XML                              1              5              8            182
Markdown                         2             39              0             92
make                             1             18              2             49
TeX                              1              3              0             27
YAML                             1              1              0              3
-------------------------------------------------------------------------------
SUM:                           232           2971           8113          34150
-------------------------------------------------------------------------------


Statistical information for the repository '9617adc67a4be9cabd821a29' was
gathered on 2021/07/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Brian Savage                    75         23852           3876          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Brian Savage              19976           83.7          6.5               33.46
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03470/joss.03470/10.21105.joss.03470.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03470/joss.03470/10.21105.joss.03470.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@savage13 thanks for this submission. 

- [ ] Check `...released as under an...`, this should probably read `...released under an...`
- [ ] Please work to expand your statement of need to specifically state what scientific research this work enables. Also expand the paper in general with a more detailed discussion of related scientific research and or scientific research that already used this work. Use citations to the literature in this expanded text. See also our guidelines: https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain.

**Comment by Kevin-Mattheus-Moerman** [comment]
I have added the `waitlisted` label to this submission as all our editors in this domain are currently handling other papers. We will assign an editor as soon as one becomes available. Thank you for your patience. 

@kbarnhart do you think you could edit this work once you are available?

**Comment by kbarnhart** [comment]
@Kevin-Mattheus-Moerman I think it would be better to find an editor with more C experience than me (I have none). If there isn't anyone with both language experience and domain experience, I could certainly assist someone else with domain context, reviewer recommendations, etc. I think @leouieda would likely be the most appropriate editor for this.

**Comment by savage13** [comment]
Fixed the following two items:

* [x]  Check `...released as under an...`, this should probably read `...released under an...`
 
* [x]  Please work to expand your statement of need to specifically state what scientific research this work enables. Also expand the paper in general with a more detailed discussion of related scientific research and or scientific research that already used this work. Use citations to the literature in this expanded text. See also our guidelines: https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain.

A paragraph was added to the beginning of the 'Statement of Need' with example research applications of this library.

**Comment by leouieda** [comment]
@kbarnhart @Kevin-Mattheus-Moerman thanks for the ping. I've got my hands full at the moment but could take this on in about a month if that's OK.

**Comment by danielskatz** [comment]
👋  @rkurchin - would you be able to edit this submission?  (Note that @kbarnhart has [volunteered to help find reviewers](https://github.com/openjournals/joss-reviews/issues/3470#issuecomment-878339073))

**Comment by danielskatz** [comment]
@whedon invite @rkurchin as editor

**Comment by whedon** [comment]
@rkurchin has been invited to edit this submission.

**Comment by rkurchin** [comment]
I don't know C or anything about seismic analysis, so I doubt I'm a good fit either...

**Comment by Kevin-Mattheus-Moerman** [comment]
@jedbrown is this something you could handle as editor? It looks like you are also at capacity at the moment but let me know if you could take this on. Thanks.

**Comment by danielskatz** [comment]
I'll take this on, with help accepted from @kbarnhart on reviewers

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @savage13 - sorry for the delay, but now we'll make this move forward.

Do you have reviewer suggestions?  If so, please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by danielskatz** [comment]
👋 @kbarnhart - Can I get your help/suggestions on reviewers for this, as you mentioned earlier?

**Comment by savage13** [comment]
Going through the list or people, I might suggest jkmacc-LANL, krischer, or anowacki.  
- jkmacc-LANL has domain specific knowledge but lacks C expertise
- krischer knows C and understands the domain
- anowacki has domain knowledge but does not know C

Let me know if you need additional possible reviewers.

**Comment by danielskatz** [comment]
👋 @krischer - You appear to be uniquely qualified to review this submission (of the list of JOSS potential reviewers).  Are you able to help us and take on this review?

**Comment by danielskatz** [comment]
👋 @jkmacc-LANL & @anowacki - though you didn't list C expertise, do you think you have enough C skill to review this submission?

**Comment by anowacki** [comment]
@danielskatz To be honest, I don't think I do, sorry.  Apologies not to be able to help on this occasion.

**Comment by kbarnhart** [comment]
Some other recommendations @danielskatz.
- [Robert Herrmann @ SLU]( https://www.slu.edu/arts-and-sciences/earth-atmospheric-sciences/faculty/herrmann-robert.php)
- [Charles Amon @ Penn State]( http://eqseis.geosc.psu.edu/cammon/)
- [Chad Trabant at IRIS](https://www.iris.edu/hq/staff/employee/trabant) chad-iris
- jkmacc-LANL (listed above already) and mbegnaud (contributors to [pySAC](https://github.com/LANL-Seismoacoustics/pysac))

**Comment by danielskatz** [comment]
👋 @chad-iris and @mbegnaud - Would one or both of you be able to review this submission to JOSS?

**Comment by danielskatz** [comment]
👋 @cja12 - would you (or perhaps a member of your group) be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by danielskatz** [comment]
@chad-iris - That's great.  I'll add you as a reviewer, and once we get another reviewer, we'll start the review - you can certainly wait to start

**Comment by danielskatz** [comment]
@whedon assign @chad-iris as reviewer

**Comment by whedon** [comment]
OK, @chad-iris is now a reviewer

**Comment by danielskatz** [comment]
👋 @krischer, @jkmacc-LANL, @mbegnaud, @cja12 - I'm just checking with you again to see if one of you could be the second reviewer for this JOSS submission

**Comment by mbegnaud** [comment]
> 👋 @chad-iris and @mbegnaud - Would one or both of you be able to review this submission to JOSS?

I am unable to review the submission at this time. Apologies.

**Comment by danielskatz** [comment]
Thanks for the reply @mbegnaud

**Comment by cja12** [comment]
This is a very busy time of the year with classes starting. I can try to review this package, but cannot do anything extensive.

> On Aug 16, 2021, at 8:42 AM, Daniel S. Katz ***@***.***> wrote:
> 
> 
> 👋 @krischer, @jkmacc-LANL, @mbegnaud, @cja12 - I'm just checking with you again to see if one of you could be the second reviewer for this JOSS submission
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> 

================================i====================================
Charles J. Ammon, Department of Geosciences
Penn State University / 440 Deike Bldg / University Park, PA 16802
VOICE: (814) 865 2310  / FAXES: (814) 863 7823 or (814) 863 8724
http://eqseis.geosc.psu.edu/~cammon/
http://www.personal.psu.edu/faculty/c/j/cja12/

**Comment by danielskatz** [comment]
@cja12 & @jkmacc-LANL - thanks to both of you for volunteering. Given your comments, I will add both of you, along with @chad-iris who is already enlisted - I think the three of you will be a great team for this review

**Comment by danielskatz** [comment]
@whedon add @cja12 as reviewer

**Comment by whedon** [comment]
OK, @cja12 is now a reviewer

**Comment by danielskatz** [comment]
@whedon add @jkmacc-LANL as reviewer

**Comment by whedon** [comment]
OK, @jkmacc-LANL is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3619.

**Comment by cja12** [comment]
Hi,

I am sorry. Please remove me from this review process. This is a mess and now I am being spammed continuously with emails from your system. I don’t have time to navigate such a convoluted review process.

Chuck Ammon


> On Aug 16, 2021, at 8:42 AM, Daniel S. Katz ***@***.***> wrote:
> 
> 
> 👋 @krischer, @jkmacc-LANL, @mbegnaud, @cja12 - I'm just checking with you again to see if one of you could be the second reviewer for this JOSS submission
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> 

================================i====================================
Charles J. Ammon, Department of Geosciences
Penn State University / 440 Deike Bldg / University Park, PA 16802
VOICE: (814) 865 2310  / FAXES: (814) 863 7823 or (814) 863 8724
http://eqseis.geosc.psu.edu/~cammon/
http://www.personal.psu.edu/faculty/c/j/cja12/
