### ISSUE TITLE
[PRE REVIEW]: home2park: An R package to assess the spatial provision of urban parks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3486]
**Submitting author:** @xp-song (<a href="http://orcid.org/0000-0002-8825-195X">Xiao Ping Song</a>)
**Repository:** <a href="https://github.com/ecological-cities/home2park" target ="_blank">https://github.com/ecological-cities/home2park</a>
**Version:** v0.1.0
**Editor:** @martinfleis
**Reviewers:** @aelissa, @nickbearman
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/16d81fa40c903d4cd5dfa91900b55bb0/status.svg)](https://joss.theoj.org/papers/16d81fa40c903d4cd5dfa91900b55bb0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/16d81fa40c903d4cd5dfa91900b55bb0"><img src="https://joss.theoj.org/papers/16d81fa40c903d4cd5dfa91900b55bb0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/16d81fa40c903d4cd5dfa91900b55bb0/status.svg)](https://joss.theoj.org/papers/16d81fa40c903d4cd5dfa91900b55bb0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @xp-song. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @KristinaRiemer.

@xp-song if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3486 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (728.9 files/s, 178483.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            34           1805            484           6847
JavaScript                      12            797            543           3866
Markdown                         6            291              0           1057
CSS                              6            157             77           1045
R                               19            566           1595            998
XML                              2              0              2            525
Rmd                              4            351            398            307
YAML                             5             24              2            183
TeX                              1              0              0            106
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            90           3991           3102          14945
-------------------------------------------------------------------------------


Statistical information for the repository '37370b6240173585d70f0c1a' was
gathered on 2021/07/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
xpsong                           2          5242             24          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
xpsong                     5218           99.5          0.0               10.44
```

**Comment by kthyng** [comment]
@xp-song I think your paper needs to be named `paper.md` to be found. Mote info [here](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).

**Comment by kthyng** [comment]
Since this software is on the small side (<1000 lines of code), I am pinging the editorial board to make sure it is in scope in terms of [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This process will take 1-2 weeks.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by xp-song** [comment]
> @xp-song I think your paper needs to be named `paper.md` to be found. Mote info [here](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).

Hi @kthyng, thank you for looking into our work. I've fixed this in commit [06f7047](https://github.com/ecological-cities/home2park/commit/06f70477262169855daa371c552f10057e5559a7)

**Comment by xp-song** [comment]
> @xp-song if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

Here are several reviewer suggestions based on the provided list:

- Jeffrey Hollister ([jhollist](https://github.com/jhollist)) - work on spatial ecology and environmental sciences, and experience in GIS and spatial statistics in R.
- Bryce Mecum ([amoeba](https://github.com/amoeba)) - experience in spatial data manipulation in R.
- Daniel Nüst ([nuest](https://github.com/nuest)) - experience in GIS and spatiotemporal data in R.
- Virgilio Gómez-Rubio ([becarioprecario](https://github.com/becarioprecario)) - work on GIS and spatial statistics in R.

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03486/joss.03486/10.21105.joss.03486.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03486/joss.03486/10.21105.joss.03486.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@xp-song - I'm unsure if this is limited to use in Singapore - can you explain if this is correct or not?

**Comment by xp-song** [comment]
@danielskatz The package can be used anywhere (user provided data), and functions are included to download/process OSM data. So out of the box, it may be used anywhere where OSM is available. The example provided is for the city of Singapore

**Comment by danielskatz** [comment]
This has passed the scope query, but we don't have editors in this area currently available, so we'll put in on the waiting list for a little bit

**Comment by xp-song** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@Kevin-Mattheus-Moerman
@KristinaRiemer
@Nikoleta-v3
@VivianePons
@adi3
@ajstewartlang
@arfon
@arokem
@bmcfee
@cMadan
@csoneson
@danielskatz
@dfm
@dhhagan
@diehlpk
@dpsanders
@drvinceknight
@elbeejay
@eloisabentivegna
@emdupre
@fabian-s
@faroit
@fboehm
@fraukewiese
@galessiorob
@gkthiruvathukal
@hugoledoux
@jbytecode
@jedbrown
@jgostick
@jmschrei
@jni
@katyhuff
@kbarnhart
@kellyrowland
@kthyng
@kyleniemeyer
@leouieda
@lorenanicole
@lpantano
@lucydot
@luizirber
@majensen
@marcosvital
@mbobra
@meg-simula
@melissawm
@mikldk
@mjsottile
@oliviaguest
@osorensen
@pdebuyl
@pibion
@poulson
@richardjgowers
@rkurchin
@sbenthall
@sjpfenninger
@taless474
@terrytangyuan
@timtroendle
@vissarion
@will-rowe
@xuanxu
```

**Comment by xp-song** [comment]
@danielskatz The research areas that [home2park](https://ecological-cities.github.io/home2park/) intersect with include topics such as GIS/geospatial analysis (e.g. spatial equity/statistics), human ecology (e.g. human–nature interactions, recreation/leisure), as well as city/urban planning (e.g. landscape ecology/patterns). Some suggested editors are listed below, hope this helps:

- Kristina Riemer ([KristinaRiemer](https://github.com/KristinaRiemer)) - background in environmental science, and ecology with extensive experience in R (spatial data, ecosystem modelling)
- Marcos Vital ([@marcosvital](https://github.com/marcosvital)) - extensive work in R and ecology
- Hugo Ledoux ([hugoledoux)](https://github.com/hugoledoux)) - extensive work on GIS, geoinformation and their application

**Comment by danielskatz** [comment]
>we don't have editors in this area currently available

"available" is the key word here, meaning free to take on another paper, but thanks for making these explicit suggestions.

**Comment by arfon** [comment]
@whedon invite @martinfleis as editor

:wave: @martinfleis – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@martinfleis has been invited to edit this submission.

**Comment by martinfleis** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @martinfleis

**Comment by martinfleis** [comment]
👋 Hi @xp-song, I'll be editing your paper. 

While I try to get in touch with potential reviewers, can you expand the paper to follow the guidelines?

- The Summary section of your paper should summarise the package. In its current form, it serves as an introduction and a problem statement more than a summary. It should contain a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- Add State of the field section. You should describe how this software compares to other commonly-used packages, at least within the R ecosystem (and potentially other).

See the [submitting guidelines](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) and a [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html#software-paper) for details.

Thank you!

**Comment by martinfleis** [comment]
@whedon assign @aelissa as reviewer

**Comment by whedon** [comment]
OK, @aelissa is now a reviewer

**Comment by martinfleis** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03486/joss.03486/10.21105.joss.03486.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03486/joss.03486/10.21105.joss.03486.pdf) :page_facing_up: :point_left:

**Comment by xp-song** [comment]
> 👋 Hi @xp-song, I'll be editing your paper.
> 
> While I try to get in touch with potential reviewers, can you expand the paper to follow the guidelines?
> 
> * The Summary section of your paper should summarise the package. In its current form, it serves as an introduction and a problem statement more than a summary. It should contain a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience.
> * Add State of the field section. You should describe how this software compares to other commonly-used packages, at least within the R ecosystem (and potentially other).
> 
> See the [submitting guidelines](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) and a [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html#software-paper) for details.
> 
> Thank you!

Thanks for pointing these out, I've updated the paper and added some links to documentation.

**Comment by xp-song** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03486/joss.03486/10.21105.joss.03486.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03486/joss.03486/10.21105.joss.03486.pdf) :page_facing_up: :point_left:

**Comment by martinfleis** [comment]
@whedon add @nickbearman as reviewer

**Comment by whedon** [comment]
OK, @nickbearman is now a reviewer

**Comment by martinfleis** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3609.
