### ISSUE TITLE
[PRE REVIEW]: Inscriptis - A Python-based HTML to text conversion library optimized for knowledge extraction from the Web

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3487]
**Submitting author:** @AlbertWeichselbraun (<a href="http://orcid.org/0000-0001-6399-045X">Albert Weichselbraun</a>)
**Repository:** <a href="https://github.com/weblyzard/inscriptis/" target ="_blank">https://github.com/weblyzard/inscriptis/</a>
**Version:** v2.0.0
**Editor:** @sbenthall
**Reviewers:** @reality, @rlskoeser
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6039d24c1ea4541fd544dfc398dcb5ca/status.svg)](https://joss.theoj.org/papers/6039d24c1ea4541fd544dfc398dcb5ca)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6039d24c1ea4541fd544dfc398dcb5ca"><img src="https://joss.theoj.org/papers/6039d24c1ea4541fd544dfc398dcb5ca/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6039d24c1ea4541fd544dfc398dcb5ca/status.svg)](https://joss.theoj.org/papers/6039d24c1ea4541fd544dfc398dcb5ca)
```

**Author instructions**

Thanks for submitting your paper to JOSS @AlbertWeichselbraun. **Currently, there isn't an JOSS editor assigned** to your paper.

@AlbertWeichselbraun if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (1606.0 files/s, 111098.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            44            283             79           2602
Python                          50            828           1010           2035
JSON                            13              2              0            251
TeX                              1             38              0            246
reStructuredText                 5            168            143            240
Markdown                         2             88              0            234
YAML                             3             15             32             76
INI                              1              7              0             55
Bourne Shell                     1              8             11             17
make                             2              4              6             16
Dockerfile                       1              3              2             10
-------------------------------------------------------------------------------
SUM:                           123           1444           1283           5782
-------------------------------------------------------------------------------


Statistical information for the repository '4052ecee83af3d31b1884119' was
gathered on 2021/07/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Albert Weichselbraun           240         12158           6538           98.13
Fabian Odoni                     1             6              4            0.05
Max Goebel                       1             1              1            0.01
fabian                           2            18              6            0.13
k3njiy                           4           143            151            1.54
max                              2            15             12            0.14

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Albert Weichselbraun       3845           31.6          8.6               13.99
Fabian Odoni                  1           16.7         51.3                0.00
fabian                       15           83.3         38.9               26.67
k3njiy                       11            7.7          0.0                9.09
max                           1            6.7         31.5                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s11042-019-08328-z is OK
- 10.3115/v1/D14-1162 is OK
- 10.1109/JSYST.2015.2466439 is OK
- 10.1016/j.ins.2014.03.096 is OK
- 10.3390/fi13030059 is OK
- 10.1145/3430937 is OK
- 10.1080/14740338.2018.1531847 is OK
- 10.1080/00437956.1954.11659520 is OK

MISSING DOIs

- 10.1109/hicss.2016.133 may be a valid DOI for title: Extracting Opinion Targets from Environmental Web Coverage and Social Media Streams

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03487/joss.03487/10.21105.joss.03487.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03487/joss.03487/10.21105.joss.03487.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@sbenthall Would you be able to take this submission on?

**Comment by kthyng** [comment]
@whedon invite @sbenthall as editor

**Comment by whedon** [comment]
@sbenthall has been invited to edit this submission.

**Comment by AlbertWeichselbraun** [comment]
Dear all,

Michael Reiss (m.reiss@ikmz.uzh.ch) who is a research and teaching associate at the University of Zurich's Department of Communication and Media Research (IKMZ) might be a good fit.
(he was the first person to request information on how to cite Inscriptis in his work).

From the JOSS reviewer list, reviewers with good Python skills and an interest in Computational Analytics, Natural Language Processing and/or Social Sciences should be a good choice as well. I have located four additional potential reviewers based on these criteria and their position in the reviewer list (preferring reviewers at the bottom of the list):
- ajoer (a.jorgensen@uva.nl)
- hugo.sanjurjo@deusto.es
- alexhanna (alex.hanna@gmail.com)
- mbod (mbod@asc.upenn.edu)

Cheers, 
  Albert :)

**Comment by sbenthall** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @sbenthall

**Comment by sbenthall** [comment]
@ajoer @alexhanna @mbod would you be able to review this package?

**Comment by alexhanna** [comment]
Don't quite have the cycles for this now, thanks though.

**Comment by sbenthall** [comment]
@reality would you be able to review this package?

**Comment by sbenthall** [comment]
@nmstreethran would you be able to review this package?

**Comment by reality** [comment]
@sbenthall Sorry for the delayed response. Yes, I would be happy to review this package.

**Comment by nmstreethran** [comment]
@sbenthall Sorry, I am unable to review at the moment.

**Comment by sbenthall** [comment]
Thank you @reality I'll assign you as a reviewer.

**Comment by sbenthall** [comment]
@whedon assign @reality as reviewer

**Comment by whedon** [comment]
OK, @reality is now a reviewer

**Comment by sbenthall** [comment]
@rlskoeser would you be able to review this package?

**Comment by sbenthall** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03487/joss.03487/10.21105.joss.03487.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03487/joss.03487/10.21105.joss.03487.pdf) :page_facing_up: :point_left:

**Comment by rlskoeser** [comment]
@sbenthall yes, I'd be glad to review this package.

**Comment by sbenthall** [comment]
Thank you, @rlskoeser

**Comment by sbenthall** [comment]
@whedon add @rlskoeser as reviewer

**Comment by whedon** [comment]
OK, @rlskoeser is now a reviewer

**Comment by sbenthall** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3557.
