### ISSUE TITLE
[PRE REVIEW]: MapAgora: an R package to gather data about nonprofit organizations and their activity

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3488]
**Submitting author:** @milandv (<a href="http://orcid.org/0000-0001-7363-8089">Milan de Vries</a>)
**Repository:** <a href="https://github.com/snfagora/MapAgora" target ="_blank">https://github.com/snfagora/MapAgora</a>
**Version:** v0.0.5
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a27b49a757c925ea9a62b7f6de2fc85e/status.svg)](https://joss.theoj.org/papers/a27b49a757c925ea9a62b7f6de2fc85e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a27b49a757c925ea9a62b7f6de2fc85e"><img src="https://joss.theoj.org/papers/a27b49a757c925ea9a62b7f6de2fc85e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a27b49a757c925ea9a62b7f6de2fc85e/status.svg)](https://joss.theoj.org/papers/a27b49a757c925ea9a62b7f6de2fc85e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @milandv. **Currently, there isn't an JOSS editor assigned** to your paper.

@milandv if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (1348.1 files/s, 222109.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            55           2589            691           7402
R                               13            389            619            847
CSS                              3             99             48            428
Markdown                         4            145              0            271
JavaScript                       4             64             34            266
Rmd                              3             58            116             35
TeX                              1              2              0             24
YAML                             2              6              6             18
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            86           3352           1515           9302
-------------------------------------------------------------------------------


Statistical information for the repository '72587c84de0fa0168a4f5cb2' was
gathered on 2021/07/12.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jae Yeon Kim                     4           460              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jae Yeon Kim                460          100.0          0.3               10.87
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.31219/osf.io/g9d8u may be a valid DOI for title: Computational Social Science for Nonprofit Studies: Developing a Toolbox and Database for the Field
- 10.2307/2585829 may be a valid DOI for title: A Nation of Organizers: The Institutional Origins of Civic Voluntarism in the United States

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3488 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:204:in `block in parse_authors': Author (Milan de Vries) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kthyng** [comment]
Hi @milandv and thanks for your submission. Since it is on the small side (<1000 lines of code), I am pinging the editorial board to make sure it is in scope in terms of [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This process will take 1-2 weeks.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@milandv - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.  If you were to add analysis functions, and explain how these could be used for a set of research questions, the software could be reconsidered in a future submission.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
