### ISSUE TITLE
[PRE REVIEW]: ‘SRS’ R package and ‘q2-srs’ QIIME 2 plugin: normalization of microbiome data using scaling with ranked subsampling (SRS)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3489]
**Submitting author:** @vitorheidrich (<a href="http://orcid.org/0000-0001-6617-9187">Vitor Heidrich</a>)
**Repository:** <a href="https://github.com/vitorheidrich/SRS_q2-srs_info" target ="_blank">https://github.com/vitorheidrich/SRS_q2-srs_info</a>
**Version:** 0.2.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/aa10a016d3226cdaf35b1ca129e87a71/status.svg)](https://joss.theoj.org/papers/aa10a016d3226cdaf35b1ca129e87a71)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/aa10a016d3226cdaf35b1ca129e87a71"><img src="https://joss.theoj.org/papers/aa10a016d3226cdaf35b1ca129e87a71/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/aa10a016d3226cdaf35b1ca129e87a71/status.svg)](https://joss.theoj.org/papers/aa10a016d3226cdaf35b1ca129e87a71)
```

**Author instructions**

Thanks for submitting your paper to JOSS @vitorheidrich. **Currently, there isn't an JOSS editor assigned** to your paper.

@vitorheidrich if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (485.0 files/s, 30314.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2             38              0             89
TeX                              1              7              0             78
R                                1              6             10             22
-------------------------------------------------------------------------------
SUM:                             4             51             10            189
-------------------------------------------------------------------------------


Statistical information for the repository 'd8be971ef919a442b7552de9' was
gathered on 2021/07/12.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.7717/peerj.9593 may be a valid DOI for title: Improved normalization of species count data in ecology by scaling with ranked subsampling (SRS): application to microbial communities
- 10.1038/nrmicro.2017.87 may be a valid DOI for title: Embracing the unknown: disentangling the complexities of the soil microbiome
- 10.1128/mbio.00525-18 may be a valid DOI for title: Identifying and overcoming threats to reproducibility, replicability, robustness, and generalizability in microbiome research

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03489/joss.03489/10.21105.joss.03489.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03489/joss.03489/10.21105.joss.03489.pdf) :page_facing_up: :point_left:

**Comment by vitorheidrich** [comment]
> ```
> Reference check summary (note 'MISSING' DOIs are suggestions that need verification):
> 
> OK DOIs
> 
> - None
> 
> MISSING DOIs
> 
> - 10.7717/peerj.9593 may be a valid DOI for title: Improved normalization of species count data in ecology by scaling with ranked subsampling (SRS): application to microbial communities
> - 10.1038/nrmicro.2017.87 may be a valid DOI for title: Embracing the unknown: disentangling the complexities of the soil microbiome
> - 10.1128/mbio.00525-18 may be a valid DOI for title: Identifying and overcoming threats to reproducibility, replicability, robustness, and generalizability in microbiome research
> 
> INVALID DOIs
> 
> - None
> ```

The suggested DOIs are correct

**Comment by vitorheidrich** [comment]
> ```
> Software report (experimental):
> 
> github.com/AlDanial/cloc v 1.88  T=0.01 s (485.0 files/s, 30314.4 lines/s)
> -------------------------------------------------------------------------------
> Language                     files          blank        comment           code
> -------------------------------------------------------------------------------
> Markdown                         2             38              0             89
> TeX                              1              7              0             78
> R                                1              6             10             22
> -------------------------------------------------------------------------------
> SUM:                             4             51             10            189
> -------------------------------------------------------------------------------
> 
> 
> Statistical information for the repository 'd8be971ef919a442b7552de9' was
> gathered on 2021/07/12.
> No commited files with the specified extensions were found.
> ```

As mentioned in the note to the editor, the Git repository associated with this submission contains only files associated with the manuscript. The files associated with each package can be found in their particular repositories (as described in the README of the manuscript repository). Therefore, I am running `cloc` in the software repositories below.

**'SRS' R package**
```
      12 text files.
      10 unique files.                              
       9 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.06 s (64.3 files/s, 17630.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                3            127             35            907
Markdown                         1              8              0             19
-------------------------------------------------------------------------------
SUM:                             4            135             35            926
-------------------------------------------------------------------------------
```
**'q2-srs' QIIME 2 plugin**
```
      14 text files.
      14 unique files.                              
       4 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.02 s (482.3 files/s, 22493.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5             34             23            208
Markdown                         1             27              0             85
R                                2             16             13             73
YAML                             1              6              0             25
DOS Batch                        1              0              0              2
Bourne Shell                     1              0              0              1
-------------------------------------------------------------------------------
SUM:                            11             83             36            394
-------------------------------------------------------------------------------
```

**Comment by arfon** [comment]
Running `cloc` to help understand the size/scope/level of effort in the respective projects here:

```
cloc SRS/
      12 text files.
      10 unique files.                              
       9 files ignored.

github.com/AlDanial/cloc v 1.86  T=0.02 s (184.9 files/s, 50663.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                3            127             35            907
Markdown                         1              8              0             19
-------------------------------------------------------------------------------
SUM:                             4            135             35            926
-------------------------------------------------------------------------------
```

```
cloc q2-srs
      14 text files.
      14 unique files.                              
       3 files ignored.

github.com/AlDanial/cloc v 1.86  T=0.03 s (466.4 files/s, 20520.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5             34             23            208
Markdown                         1             27              0             85
R                                2             16             13             73
YAML                             1              6              0             25
TeX                              1              2              0             13
DOS Batch                        1              0              0              2
Bourne Shell                     1              0              0              1
-------------------------------------------------------------------------------
SUM:                            12             85             36            407
-------------------------------------------------------------------------------
```

**Comment by vitorheidrich** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.7717/peerj.9593 is OK
- 10.1038/s41587-019-0209-9 is OK
- 10.1038/nrmicro.2017.87 is OK
- 10.1371/journal.pcbi.1003531 is OK
- 10.1038/s41579-018-0046-8 is OK
- 10.1128/mbio.00525-18 is OK
- 10.1038/nature11053 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by vitorheidrich** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03489/joss.03489/10.21105.joss.03489.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03489/joss.03489/10.21105.joss.03489.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Thanks @arfon and @vitorheidrich. Counting both together, this is still on the small side for a submission so I will ping the editorial board to make it is in in scope. This will take 1-2 weeks.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
