### ISSUE TITLE
[PRE REVIEW]: TidyTensor: Utilities for multidimensional arrays as named hierarchical structures

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3492]
**Submitting author:** @oneilsh (<a href="http://orcid.org/0000-0001-6220-7080">Shawn T. O&#39;Neil</a>)
**Repository:** <a href="https://github.com/oneilsh/tidytensor" target ="_blank">https://github.com/oneilsh/tidytensor</a>
**Version:** v0.9.1
**Editor:** @taless474
**Reviewers:** @nhejazi, @omid-s
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb/status.svg)](https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb"><img src="https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb/status.svg)](https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb)
```

**Author instructions**

Thanks for submitting your paper to JOSS @oneilsh. **Currently, there isn't an JOSS editor assigned** to your paper.

@oneilsh if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.37 s (237.4 files/s, 107907.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            28            684             93          23438
JavaScript                       8           2155           1972           7201
R                               32            353           1415           1209
CSS                              5            107             52            471
SVG                              2              0              1            299
Rmd                              1            123            168            173
Markdown                         4             78              0            172
YAML                             6             16              6            116
XML                              1              0              0             87
TeX                              1              9              0             60
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            89           3525           3707          33227
-------------------------------------------------------------------------------


Statistical information for the repository '59cb418af8a06e2a2effd353' was
gathered on 2021/07/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Shawn O'Neil                     3         22695              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Shawn O'Neil              11367           50.1          0.0               17.40
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.5334/jors.148 may be a valid DOI for title: xarray: ND labeled arrays and datasets in Python

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03492/joss.03492/10.21105.joss.03492.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03492/joss.03492/10.21105.joss.03492.pdf) :page_facing_up: :point_left:

**Comment by oneilsh** [comment]
Possible reviewers from the google sheet and their interests/programming language preferences: JohnCoene, neuroimaginador, agisga. Possibilities not listed in the sheet include contributors to R deep/machine learning and/or 'tidy' infrastructure, e.g. https://github.com/rstudio/keras/graphs/contributors and https://github.com/tidymodels/tidymodels/graphs/contributors. I don't know any of these folks personally or from other collaborations.

**Comment by danielskatz** [comment]
👋 @taless474 - would you be able to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @taless474 as editor

**Comment by whedon** [comment]
@taless474 has been invited to edit this submission.

**Comment by taless474** [comment]
@danielskatz , thanks for bringing this to my attention. Yes, I like to.

**Comment by danielskatz** [comment]
@taless474 - thanks.  I'll do this for you now, but in the future, you can use the same command I'm going to use, or even replace your account name simply by `me`

**Comment by danielskatz** [comment]
@whedon assign @taless474 as editor

**Comment by whedon** [comment]
OK, the editor is @taless474

**Comment by taless474** [comment]
@omid-s, @kellieotto, @nhejazi Would you be interested in reviewing this?

**Comment by taless474** [comment]
@agisga Would you be interested in reviewing this?

**Comment by taless474** [comment]
@saniavn I guess this is related to your field. Would you be interested in reviewing this?

**Comment by nhejazi** [comment]
Sure, I’d be happy to co-review this submission

**Comment by omid-s** [comment]
Sure @taless474, I'd be happy to co-review this submission as well.

**Comment by taless474** [comment]
@whedon assign @nhejazi as reviewer
@whedon assign @omid-s as reviewer

**Comment by whedon** [comment]
OK, @nhejazi is now a reviewer

**Comment by taless474** [comment]
@whedon assign @omid-s as reviewer

**Comment by whedon** [comment]
OK, @omid-s is now a reviewer

**Comment by taless474** [comment]
@whedon assign @nhejazi as reviewer

**Comment by whedon** [comment]
OK, @nhejazi is now a reviewer

**Comment by taless474** [comment]
@whedon add @omid-s as reviewer

**Comment by whedon** [comment]
OK, @omid-s is now a reviewer

**Comment by taless474** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3543.
