### ISSUE TITLE
[PRE REVIEW]: BisPy: Bisimulation in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3493]
**Submitting author:** @fAndreuzzi (<a href="http://orcid.org/0000-0002-9508-7801">Francesco Andreuzzi</a>)
**Repository:** <a href="https://github.com/fAndreuzzi/BisPy" target ="_blank">https://github.com/fAndreuzzi/BisPy</a>
**Version:** 0.2.0
**Editor:** @mjsottile
**Reviewers:** @zoometh, @mschordan, @jonjoncardoso
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9d9c3ca0715d482938b5a450525cefa0/status.svg)](https://joss.theoj.org/papers/9d9c3ca0715d482938b5a450525cefa0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9d9c3ca0715d482938b5a450525cefa0"><img src="https://joss.theoj.org/papers/9d9c3ca0715d482938b5a450525cefa0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9d9c3ca0715d482938b5a450525cefa0/status.svg)](https://joss.theoj.org/papers/9d9c3ca0715d482938b5a450525cefa0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @fAndreuzzi. **Currently, there isn't an JOSS editor assigned** to your paper.

@fAndreuzzi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (629.8 files/s, 80906.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          34           1168           1218           3694
Markdown                         2             77              0            254
reStructuredText                13            112            148            192
TeX                              1              7              0             74
YAML                             2              6              6             48
DOS Batch                        1              8              1             26
make                             1              4              7              9
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            55           1382           1380           4303
-------------------------------------------------------------------------------


Statistical information for the repository '3063ec0fbb6af9ebc92943e3' was
gathered on 2021/07/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Francesco Andreuzzi              4           204            100            0.60
francescoandreuzzi             399         28541          22022           99.40

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Francesco Andreuzzi        6104         2992.2          3.7               10.98
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1007/3-540-44585-4_8 may be a valid DOI for title: A fast bisimulation algorithm
- 10.1109/swat.1971.10 may be a valid DOI for title: Depth-first search and linear graph algorithms
- 10.1016/b978-0-12-417750-5.50022-1 may be a valid DOI for title: An n log n algorithm for minimizing states in a finite automaton
- 10.1137/0216062 may be a valid DOI for title: Three partition refinement algorithms
- 10.1007/978-3-540-77050-3_17 may be a valid DOI for title: An incremental bisimulation algorithm
- 10.1016/0898-1221(81)90008-0 may be a valid DOI for title: A strong-connectivity algorithm and its applications in data flow analysis
- 10.1145/800221.806724 may be a valid DOI for title: CCS expressions, finite state processes, and three problems of equivalence

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03493/joss.03493/10.21105.joss.03493.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03493/joss.03493/10.21105.joss.03493.pdf) :page_facing_up: :point_left:

**Comment by fAndreuzzi** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by fAndreuzzi** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/3-540-44585-4_8 is OK
- 10.1023/A:1027328830731 is OK
- 10.1137/0201010 is OK
- 10.1137/0216062 is OK
- 10.1007/978-3-540-77050-3_17 is OK
- 10.1016/0898-1221(81)90008-0 is OK
- 10.1016/0890-5401(90)90025-D is OK

MISSING DOIs

- None

INVALID DOIs

- 10.5555/891883 is INVALID
```

**Comment by fAndreuzzi** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/3-540-44585-4_8 is OK
- 10.1023/A:1027328830731 is OK
- 10.1137/0201010 is OK
- 10.1016/B978-0-12-417750-5.50022-1 is OK
- 10.1137/0216062 is OK
- 10.1007/978-3-540-77050-3_17 is OK
- 10.1016/0898-1221(81)90008-0 is OK
- 10.1016/0890-5401(90)90025-D is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by fAndreuzzi** [comment]
I suggest jonjoncardoso, zoometh, jkbren, TomKellyGenetics, vinodkahuja, sudarshansudarshan (**graph theory**).

**Comment by kthyng** [comment]
Hi @mjsottile would you be a good fit for this submission?

**Comment by kthyng** [comment]
@whedon invite @mjsottile as editor

**Comment by whedon** [comment]
@mjsottile has been invited to edit this submission.

**Comment by fAndreuzzi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03493/joss.03493/10.21105.joss.03493.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03493/joss.03493/10.21105.joss.03493.pdf) :page_facing_up: :point_left:

**Comment by mjsottile** [comment]
@kthyng Sorry for the delay - my mail filter shuffled the invite into a folder I don't read daily.  I'd be happy to handle this submission.

**Comment by mjsottile** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by fAndreuzzi** [comment]
Hi @mjsottile, thank you for accepting to review my submission.

**Comment by mjsottile** [comment]
Hi @fAndreuzzi  : I have found one reviewer via email and will reach out to others on here to find one or two more.  In the meantime, I looked at the paper and it has a few typos (e.g., line 41 - I assume "parse" should be "sparse"?).  I would recommend doing a proofreading pass to find simple errors like that.  It might also be worth adding a small example in the paper that demonstrates the package so a reader can get a sense for it without having to go look at code right away.

I expect I will be able to start the formal review soon once I have the additional reviewer(s).

**Comment by mjsottile** [comment]
:wave: Hello @jkbren,  @zoometh, @jonjoncardoso : you were suggested by the author of this submission to the Journal of Open Source Software (JOSS) as potential reviewers. Would you be interested in providing a review? If you haven't reviewed for JOSS before, you can see the review criteria here : https://joss.readthedocs.io/en/latest/review_criteria.html

Please let me know if you are interested or have any questions.

**Comment by fAndreuzzi** [comment]
> I would recommend doing a proofreading pass to find simple errors like that.

Thank you, I will review the paper again to fix this kind of typo.

>  It might also be worth adding a small example

Sure, I'm going to add a meaningful example.

**Comment by fAndreuzzi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03493/joss.03493/10.21105.joss.03493.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03493/joss.03493/10.21105.joss.03493.pdf) :page_facing_up: :point_left:

**Comment by zoometh** [comment]
@mjsottile thank you for the proposal, I'll do the review

**Comment by fAndreuzzi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03493/joss.03493/10.21105.joss.03493.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03493/joss.03493/10.21105.joss.03493.pdf) :page_facing_up: :point_left:

**Comment by jonjoncardoso** [comment]
Yes, you can count me in for the review

**Comment by fAndreuzzi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03493/joss.03493/10.21105.joss.03493.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03493/joss.03493/10.21105.joss.03493.pdf) :page_facing_up: :point_left:

**Comment by mjsottile** [comment]
Hi @fAndreuzzi  : let me know when you've finished updating the paper so I can start the review.

**Comment by fAndreuzzi** [comment]
Hi @mjsottile, I finished updating the paper, let me know if there's something else I should do.

**Comment by mjsottile** [comment]
@whedon assign @zoometh as reviewer

**Comment by whedon** [comment]
OK, @zoometh is now a reviewer

**Comment by mjsottile** [comment]
@whedon add @mschordan as reviewer

**Comment by whedon** [comment]
OK, @mschordan is now a reviewer

**Comment by mjsottile** [comment]
@whedon add @jonjoncardoso as reviewer

**Comment by whedon** [comment]
OK, @jonjoncardoso is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3519.
