### ISSUE TITLE
[PRE REVIEW]: A Fast Iterative Method Python package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3494]
**Submitting author:** @thomgrand (<a href="http://orcid.org/0000-0002-6787-2570">Thomas Grandits</a>)
**Repository:** <a href="https://github.com/thomgrand/fim-python" target ="_blank">https://github.com/thomgrand/fim-python</a>
**Version:** v1.0
**Editor:** @xuanxu
**Reviewers:** @lucaferranti, @RobertRosca
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0e163634b23cde8c673ca689430e7641/status.svg)](https://joss.theoj.org/papers/0e163634b23cde8c673ca689430e7641)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0e163634b23cde8c673ca689430e7641"><img src="https://joss.theoj.org/papers/0e163634b23cde8c673ca689430e7641/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0e163634b23cde8c673ca689430e7641/status.svg)](https://joss.theoj.org/papers/0e163634b23cde8c673ca689430e7641)
```

**Author instructions**

Thanks for submitting your paper to JOSS @thomgrand. **Currently, there isn't an JOSS editor assigned** to your paper.

@thomgrand if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (841.3 files/s, 83367.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          18            445            614           1294
YAML                             5             31             69            167
Markdown                         2             43              0            108
reStructuredText                 5             67             59             88
Cython                           1             15             40             76
TeX                              1              6              0             70
CUDA                             1              8              9             61
-------------------------------------------------------------------------------
SUM:                            33            615            791           1864
-------------------------------------------------------------------------------


Statistical information for the repository 'fc88d2a5d318fe65a2454c55' was
gathered on 2021/07/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Thomas Grandits                  6          2627            274          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Thomas Grandits            2353           89.6          0.0               13.43
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/100788951 is OK
- 10.1137/120881956 is OK
- 10.1016/j.jcp.2020.109700 is OK

MISSING DOIs

- 10.4310/cdm.1997.v1997.n1.a2 may be a valid DOI for title: Partial differential equations and Monge-Kantorovich mass transfer
- 10.1073/pnas.93.4.1591 may be a valid DOI for title: A fast marching level set method for monotonically advancing fronts

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03494/joss.03494/10.21105.joss.03494.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03494/joss.03494/10.21105.joss.03494.pdf) :page_facing_up: :point_left:

**Comment by thomgrand** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03494/joss.03494/10.21105.joss.03494.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03494/joss.03494/10.21105.joss.03494.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @xuanxu - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @xuanxu as editor

**Comment by whedon** [comment]
@xuanxu has been invited to edit this submission.

**Comment by xuanxu** [comment]
@whedon Assign me as editor

**Comment by whedon** [comment]
OK, the editor is @xuanxu

**Comment by xuanxu** [comment]
@lucaferranti, @breezykermo would you be willing to review this paper? I think your knowledge of computational methods and Python makes both of you a good fit for this submission.

**Comment by lucaferranti** [comment]
Hi @xuanxu , I am willing to review this paper. I have read the JOSS Conflict of Interest policy and I confirm that I have no COIs with this review. 😄

**Comment by xuanxu** [comment]
@whedon assign @lucaferranti as reviewer

**Comment by whedon** [comment]
OK, @lucaferranti is now a reviewer

**Comment by xuanxu** [comment]
@lucaferranti great, thanks! I'll start the review issue once we have the second reviewer. Stay tuned!

**Comment by xuanxu** [comment]
👋 @mgalloy would you be willing to review this paper? I think your knowledge of math, CUDA and Python makes you a good fit for this submission.

**Comment by mgalloy** [comment]
@xuanxu This sounds like a fun one, but unfortunately, I cannot in the near future.

**Comment by xuanxu** [comment]
👋 @RobertRosca would you be willing to review this paper? I think your knowledge of Python and HPC makes you a good fit for this submission.

**Comment by RobertRosca** [comment]
Hey @xuanxu, sure I'd be happy to review this! I'll try and look at this today and tomorrow, or next week.

**Comment by xuanxu** [comment]
@whedon add @RobertRosca as reviewer

**Comment by whedon** [comment]
OK, @RobertRosca is now a reviewer

**Comment by xuanxu** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3641.
