### ISSUE TITLE
[PRE REVIEW]: pyTEF: A Python package for the Total Exchange Flow (TEF) analysis framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3498]
**Submitting author:** @florianboergel (<a href="http://orcid.org/0000-0003-3294-667X">Florian Börgel</a>)
**Repository:** <a href="https://github.com/florianboergel/pyTEF" target ="_blank">https://github.com/florianboergel/pyTEF</a>
**Version:** v.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/f85ea6bb7e27bfa67549317db3146fba/status.svg)](https://joss.theoj.org/papers/f85ea6bb7e27bfa67549317db3146fba)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/f85ea6bb7e27bfa67549317db3146fba"><img src="https://joss.theoj.org/papers/f85ea6bb7e27bfa67549317db3146fba/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/f85ea6bb7e27bfa67549317db3146fba/status.svg)](https://joss.theoj.org/papers/f85ea6bb7e27bfa67549317db3146fba)
```

**Author instructions**

Thanks for submitting your paper to JOSS @florianboergel. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kthyng.

@florianboergel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (351.6 files/s, 205762.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             6           1075             85           6997
Jupyter Notebook                 6              0           7400           1142
Python                           6            109            105            680
YAML                             5             14             10            143
TeX                              1              9              0             94
Markdown                         3             52              0             90
INI                              1             13              0             62
make                             1             11              0             26
JSON                             2              0              0             23
-------------------------------------------------------------------------------
SUM:                            31           1283           7600           9257
-------------------------------------------------------------------------------


Statistical information for the repository '9661171f57f3d727be114b89' was
gathered on 2021/07/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Flo                             12          1621           1098           42.19
Florian Börgel                   1            64              0            0.99
Marvin Lorenz                    7           185           1144           20.62
florian.boergel                  1           277              0            4.30
florianboergel                   9          1560            495           31.89

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Marvin Lorenz               145           78.4          1.4                6.90
florianboergel              749           48.0          1.3               11.62
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.5334/jors.148 is OK

MISSING DOIs

- 10.1175/2011jpo4517.1 may be a valid DOI for title: Calculating estuarine exchange flow using isohaline coordinates
- 10.5194/os-15-601-2019 may be a valid DOI for title: Numerical issues of the Total Exchange Flow (TEF) analysis framework for quantifying estuarine circulation
- 10.1175/jpo-d-17-0266.1 may be a valid DOI for title: Estuarine Exchange Flow is Related to Mixing through the Salinity Variance Budget
- 10.3402/tellusa.v29i2.11337 may be a valid DOI for title: A theoretical framework for the description of estuaries
- 10.1029/2019jc015527 may be a valid DOI for title: Numerical Study of the Exchange Flow of the Persian Gulf Using an Extended Total Exchange Flow Analysis Framework

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03498/joss.03498/10.21105.joss.03498.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03498/joss.03498/10.21105.joss.03498.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @florianboergel and thanks for your submission! Because your submission is relatively small, I have pinged the editorial board to check to see if it is in scope. Specifically, we do this when a submission is around or below 1000 lines of code. While this process will take 1-2 weeks and has not occurred yet, since yours is quite a bit smaller than that, I do not expect it to make it through; sorry. 

However, since I know about this work, I wanted to give some thoughts now while I have the chance as rotating managing editor for JOSS this week. Could you expand the scope of the package over time to include more functionality? I know the TEF analysis is being used to calculate budgets — perhaps you could include more of the work necessary for that in this package. Or, more work related to the greater problem of numerical mixing. Another way to think about it could be: what are the obvious next future steps you'd want for this package? Then maybe resubmit next year (or after a reasonable amount of time), after there has been some substantial development of the package functionality.

**Comment by danielskatz** [comment]
@florianboergel - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Additional issues are the lack of packaging and the lack of tests. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
