### ISSUE TITLE
[REVIEW]: UglyMol: a WebGL macromolecular viewer focused on the electron density

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#350]
**Submitting author:** @wojdyr (<a href="http://orcid.org/0000-0003-3980-4092">Marcin Wojdyr</a>)
**Repository:** <a href="https://github.com/uglymol/uglymol" target ="_blank">https://github.com/uglymol/uglymol</a>
**Version:** v0.5.7
**Editor:** @arokem
**Reviewer:** @luizirber
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1009695" target="_blank">10.5281/zenodo.1009695</a>

## Status

[![status](http://joss.theoj.org/papers/5238e51e3dec64ff2814a09ed171c775/status.svg)](http://joss.theoj.org/papers/5238e51e3dec64ff2814a09ed171c775)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/5238e51e3dec64ff2814a09ed171c775"><img src="http://joss.theoj.org/papers/5238e51e3dec64ff2814a09ed171c775/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/5238e51e3dec64ff2814a09ed171c775/status.svg)](http://joss.theoj.org/papers/5238e51e3dec64ff2814a09ed171c775)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/uglymol/uglymol" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@luizirber, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arokem know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/uglymol/uglymol">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.7)?
- [x] **Authorship:** Has the submitting author (@wojdyr) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @luizirber it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arokem** [comment]
Ping! @luizirber: have you had a chance to take a look?

**Comment by luizirber** [comment]
Hi! Sorry for the delay. A few comments:

## Version
- [ ] Tag latest version (0.5.7) on GitHub

## Community guidelines
- [ ] Install instructions could be listed in the README instead of only in the wiki
- [ ] "How to modify UglyMol?" could become the CONTRIBUTING file in GitHub

## Paper

- [ ] The last paragraph is a bit hard to read. Maybe make a markdown list?

I really liked the FAQ in the wiki! Lots of good info there.

**Comment by arokem** [comment]
@wojdyr : have you had a chance to take a look at these comments?

**Comment by wojdyr** [comment]
Thank you for the review and sorry it took me a while to get back to it.

### Version
 yes, indeed, I didn't realize that I'm not pushing tags to the remote repository. I just pushed all the previous tags.

### Community guidelines: 
* I keep the README file intentionally very short, hoping that it will make people more likely to read it.
* the CONTRIBUTING file is probably a good idea, I just added initial version of it to the repository

### Paper

I reworded the last paragraph.

Thanks for taking time to review the paper and the software.

**Comment by arokem** [comment]
@luizirber : does now meet all the requirements?

**Comment by luizirber** [comment]
Yup! I checked all the boxes, I think it is good to go!

💯 Thanks for the changes, @wojdyr

**Comment by wojdyr** [comment]
Thank you @luizirber and @arokem !

 @whedon set 10.5281/zenodo.1009695 as archive

**Comment by wojdyr** [comment]
@whedon set 10.5281/zenodo.1009695 as archive

**Comment by whedon** [comment]
I'm sorry @wojdyr, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by arokem** [comment]
@whedon set 10.5281/zenodo.1009695 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1009695" target="_blank">10.5281/zenodo.1009695</a> is the archive.

**Comment by arokem** [comment]
Congratulations! 

@arfon: this paper is ready to go!

**Comment by arfon** [comment]
@luizirber many thanks for your review and to @arokem for editing this submission ✨ 

@wojdyr - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00350 ⚡️ 🚀 💥

**Comment by wojdyr** [comment]
Thank you all!

The paper (both pdf and html) has mis-formatted author list in bibliography.
For example, this entry in the bib file:

    author = {Paul Emsley and Bernhard Lohkamp and William G. Scott and Kevin Cowtan}

is shown as:

    Emsley, Paul, Bernhard Lohkamp, William G. Scott, and Kevin Cowtan.

The first author (in each entry) has the first name second; other authors have the first name first.

**Comment by arfon** [comment]
@wojdyr - yeah, I've seen this before and to be honest I'm not exactly sure what's going on. If you're interested in digging into this the command we're using to compile the PDF (with Pandoc) is [here](https://github.com/openjournals/whedon/blob/master/lib/whedon/processor.rb#L155-L164).
