### ISSUE TITLE
[PRE REVIEW]: mednoise: a python package for medical image processing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3503]
**Submitting author:** @ravibandaru-lab (<a href="http://orcid.org/0000-0001-7109-9894">Ravi Bandaru</a>)
**Repository:** <a href="https://github.com/mednoise/mednoise" target ="_blank">https://github.com/mednoise/mednoise</a>
**Version:** v.1.2.4
**Editor:** @osorensen
**Reviewers:** @kasbohm, @ethanknights
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e334cd1cbcdde8c9aa37254eb5c6bfec/status.svg)](https://joss.theoj.org/papers/e334cd1cbcdde8c9aa37254eb5c6bfec)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e334cd1cbcdde8c9aa37254eb5c6bfec"><img src="https://joss.theoj.org/papers/e334cd1cbcdde8c9aa37254eb5c6bfec/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e334cd1cbcdde8c9aa37254eb5c6bfec/status.svg)](https://joss.theoj.org/papers/e334cd1cbcdde8c9aa37254eb5c6bfec)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ravibandaru-lab. **Currently, there isn't an JOSS editor assigned** to your paper.

@ravibandaru-lab if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.12688/f1000research.29032.1 is OK
- 10.5281/zenodo.5043456 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.media.2020.101759 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.zemedi.2018.11.002 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (208.4 files/s, 68974.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           6            483           1404           1546
Markdown                         2             32              0             75
TeX                              1              0              0             70
YAML                             1              2              3             19
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            11            517           1407           1716
-------------------------------------------------------------------------------


Statistical information for the repository '15b30f8b907e146b80d3b287' was
gathered on 2021/07/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ravi Bandaru                    23          5974           2543          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ravi Bandaru               3433           57.5          0.0                4.54
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3503 with the following error: 
```
 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (https://orcid.org/0000-0001-7109-9894) for Ravi Bandaru (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by ravibandaru-lab** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by ravibandaru-lab** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.media.2020.101759 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.12688/f1000research.29032.1 is OK
- 10.5281/zenodo.5043456 is OK
- 10.1016/j.zemedi.2018.11.002 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by ravibandaru-lab** [comment]
@whedon generate paper

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by ravibandaru-lab** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03503/joss.03503/10.21105.joss.03503.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03503/joss.03503/10.21105.joss.03503.pdf) :page_facing_up: :point_left:

**Comment by ravibandaru-lab** [comment]
Hello! Thanks for processing me submission. Here are some potential reviewers I am thinking about:

1. sealhuang
2. oesteban
3. abhishekbajpayee
4. yxpd
5. glemaitre

**Comment by arfon** [comment]
@whedon invite @jni as editor

:wave: @jni – would you be able to edit this submission for us?

**Comment by whedon** [comment]
@jni has been invited to edit this submission.

**Comment by jni** [comment]
@arfon no rest for the wicked ey? 😂 I apologise, I must decline, as I am trying to close some loops before going on leave next month. 🙏 (The editor dashboard was down for me yesterday but I've made a note there now.)

**Comment by ravibandaru-lab** [comment]
@arfon Hello! 😄 Any luck on finding an editor?

**Comment by danielskatz** [comment]
👋 @ravibandaru-lab - sorry, but we're going to put this on our waiting list until a suitable editor is available

**Comment by kyleniemeyer** [comment]
@whedon invite  @cMadan as editor

Hi @cMadan, could you edit this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@cMadan :wave: Could you help handle this one?

**Comment by arfon** [comment]
@whedon invite @osorensen as editor

:wave: @osorensen - would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@osorensen has been invited to edit this submission.

**Comment by osorensen** [comment]
@whedon adding @osorensen as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
@sealhuang @oesteban @abhishekbajpayee @yxpd @glemaitre would any of you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by osorensen** [comment]
@ethanknights @fredrmag @markushs would any of you be interested in reviewing this submission to the Journal of Open Source Software? It seems to be within your areas of expertise.

**Comment by cMadan** [comment]
@kyleniemeyer @Kevin-Mattheus-Moerman, just seeing this now. It looks like `whedon` hadn't sent me an invitation email.

**Comment by osorensen** [comment]
@kasbohm, would you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by kasbohm** [comment]
Sure @osorensen!

**Comment by osorensen** [comment]
@whedon add @kasbohm as reviewer

**Comment by whedon** [comment]
OK, @kasbohm is now a reviewer

**Comment by osorensen** [comment]
Thanks @kasbohm, we'll wait for another potential reviewer to respond, and then you'll get instructions how to proceed.

**Comment by markushs** [comment]
> @ethanknights @fredrmag @markushs would any of you be interested in reviewing this submission to the Journal of Open Source Software? It seems to be within your areas of expertise.

Sorry @osorensen, busy August

**Comment by osorensen** [comment]
No problem @markushs. Thanks for responding!

**Comment by ethanknights** [comment]
Sure @osorensen

**Comment by osorensen** [comment]
@whedon add @ethanknights as reviewer

**Comment by whedon** [comment]
OK, @ethanknights is now a reviewer

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3597.
