### ISSUE TITLE
[PRE REVIEW]: BFClust: a python package for pangenome clustering with confidence scores

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3505]
**Submitting author:** @dsurujon (<a href="http://orcid.org/0000-0001-7964-3057">Defne Surujon</a>)
**Repository:** <a href="https://github.com/dsurujon/BFClust-python" target ="_blank">https://github.com/dsurujon/BFClust-python</a>
**Version:** 0.1.26
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1620e161877ad5ac45826f3108371685/status.svg)](https://joss.theoj.org/papers/1620e161877ad5ac45826f3108371685)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1620e161877ad5ac45826f3108371685"><img src="https://joss.theoj.org/papers/1620e161877ad5ac45826f3108371685/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1620e161877ad5ac45826f3108371685/status.svg)](https://joss.theoj.org/papers/1620e161877ad5ac45826f3108371685)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dsurujon. **Currently, there isn't an JOSS editor assigned** to your paper.

@dsurujon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/nar/gkx977 is OK
- 10.1093/bioinformatics/btv421 is OK
- 10.1093/gigascience/giz119 is OK
- 10.1186/S13059-020-02090-4 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1099/mgen.0.000231 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (278.8 files/s, 18960.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          10            119             34            458
Markdown                         2             41              0            119
TeX                              1              9              0             91
YAML                             1              1              0             80
-------------------------------------------------------------------------------
SUM:                            14            170             34            748
-------------------------------------------------------------------------------


Statistical information for the repository 'c25ec614a295435c50e5767b' was
gathered on 2021/07/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Defne                            8          1051            445          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Defne                       611           58.1          0.7                6.55
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03505/joss.03505/10.21105.joss.03505.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03505/joss.03505/10.21105.joss.03505.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @dsurujon - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by dsurujon** [comment]
@danielskatz thanks for the heads up, looking forward to hearing back

**Comment by danielskatz** [comment]
@dsurujon - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
