### ISSUE TITLE
[PRE REVIEW]: CleanX: A Python library for data cleaning of large sets of radiology images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3506]
**Submitting author:** @drcandacemakedamoore  (<a href="http://orcid.org/0000-0003-1672-7565">Candace Makeda Moore</a>)
**Repository:** <a href="https://github.com/drcandacemakedamoore/cleanX" target ="_blank">https://github.com/drcandacemakedamoore/cleanX</a>
**Version:** v0.1.7
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/245efedf5d9acbbc38a25bddc2988e6d/status.svg)](https://joss.theoj.org/papers/245efedf5d9acbbc38a25bddc2988e6d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/245efedf5d9acbbc38a25bddc2988e6d"><img src="https://joss.theoj.org/papers/245efedf5d9acbbc38a25bddc2988e6d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/245efedf5d9acbbc38a25bddc2988e6d/status.svg)](https://joss.theoj.org/papers/245efedf5d9acbbc38a25bddc2988e6d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @drcandacemakedamoore . **Currently, there isn't an JOSS editor assigned** to your paper.

@drcandacemakedamoore  if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (400.7 files/s, 168133.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            477            782           1732
Markdown                         5             99              0            189
YAML                             3             10              8            162
Jupyter Notebook                 2              0           7956            145
TeX                              1              9              0             57
Bourne Shell                     2              3              0             32
DOS Batch                        1              8              1             26
reStructuredText                 1             10              5             19
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            28            620           8759           2371
-------------------------------------------------------------------------------


Statistical information for the repository 'd4e558d1a7d758873693f1a4' was
gathered on 2021/07/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Candace Makeda Moore           141         17388          15014           94.46
Oleg Sivokon                    33          1253            636            5.51
andrew-f-murphy                  2             5              5            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Candace Makeda Moore       1939           11.2          1.7               10.11
Oleg Sivokon               1048           83.6          0.8                7.73
andrew-f-murphy               4           80.0          2.8              100.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2207243.2207253 is OK
- 10.18637/jss.v059.i10 is OK
- 10.1007/978-3-319-94878-2_6 is OK
- 10.1007/s00330-020-07453-w is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3506 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Candace Moore,, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
👋 @drcandacemakedamoore - note that your paper doesn't compile, but the error message indicates the likely problem.  Please feel free to make changes to your .md file, then use the command `@whedon generate pdf` to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by drcandacemakedamoore** [comment]
Actually, we just discovered some major problems with the build we want to fix instead of making installation instructions that are too different from the typical. I will withdraw and re-submit.

**Comment by danielskatz** [comment]
ok, thanks

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.

**Comment by drcandacemakedamoore** [comment]
To whom it may concern,

I resubmitted my paper on July 31st. I know it may take some time to
review, but I wanted to make sure it will actually go into the review
because I don't see it. In my previous two submissions, I could see it
after a few days.

Please advise.
Moore

**Comment by danielskatz** [comment]
It was submitted 4 days ago (including the weekend), but the associate-editor-in-chief on duty has been busy and hasn't started the pre-review process yet - I think they will very soon.

**Comment by Kevin-Mattheus-Moerman** [comment]
@drcandacemakedamoore I am on duty this week and have just triggered the pre-review issues there. I'll be looking for a handling editor next.

**Comment by drcandacemakedamoore** [comment]
Thank you so much. I see it did not build the PDF, and I will try to fix it
today.

Thanks again,
Dr. Moore
