### ISSUE TITLE
[REVIEW]: Nimbus: a Ruby gem to implement Random Forest algorithms in a genomic selection context

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#351]
**Submitting author:** @xuanxu (<a href="http://orcid.org/0000-0001-7699-3983">Juanjo Bazán</a>)
**Repository:** <a href="https://github.com/xuanxu/nimbus" target ="_blank">https://github.com/xuanxu/nimbus</a>
**Version:** 2.3.0
**Editor:** @pjotrp
**Reviewer:** @fstrozzi
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.845342" target="_blank">10.5281/zenodo.845342</a>

## Status

[![status](http://joss.theoj.org/papers/a8c2b2c1b4c3635fb95e303218457bef/status.svg)](http://joss.theoj.org/papers/a8c2b2c1b4c3635fb95e303218457bef)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a8c2b2c1b4c3635fb95e303218457bef"><img src="http://joss.theoj.org/papers/a8c2b2c1b4c3635fb95e303218457bef/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a8c2b2c1b4c3635fb95e303218457bef/status.svg)](http://joss.theoj.org/papers/a8c2b2c1b4c3635fb95e303218457bef)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/xuanxu/nimbus" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@fstrozzi, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @pjotrp know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xuanxu/nimbus">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (2.3.0)?
- [x] **Authorship:** Has the submitting author (@xuanxu) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @fstrozzi it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by fstrozzi** [comment]
The authors developed a Ruby package enabling random forest based classification for genomics selection data. The package is well written, quite easy to use and overall it seems a solid piece of software addressing specific analysis using SNPs data. The package is answering all JOSS requirements, although minor revisions are envisaged (marked as checkboxes below). 

## Code 

* the code is clean, and commented.
* rdoc is available online
* installation of the software works smoothly using RubyGem and there are no dependencies issues that I can envisage
* rspec automated tests are provided and the repository is linked to Travis CI

## Functionalities

* examples works fine with no errors following Readme instructions and using the example data provided into the repository

- [ ]  automated tests fail, an [issue](https://github.com/xuanxu/nimbus/issues/4) has been opened on the repository to inspect this

## Paper

- [ ]  The paper describes clearly the background of random forests algorithm and the use of Nimbus, but the statements of need could be improved by describing what Nimbus adds to existing random forest classifiers available for genomics selection, and highlighting what are the strong points of Nimbus and the reason why it was developed (e.g. simplicity to use, better fit for specific use cases, better performance etc.)

- [ ] Minor grammar and typing errors (can be easily spotted using a word processor, Markdown isn't very helpful with this)

**Comment by pjotrp** [comment]
@fstrozzi thanks for your thorough review! @xuanxu looks like these are minor fixes. Ping us when you are done or respond here.

**Comment by xuanxu** [comment]
Thanks for the review @fstrozzi!  
I've add some details to the paper summary to highlight the strong points and improve the statement of need. And also corrected some typos.

**Comment by fstrozzi** [comment]
Hi @xuanxu,
the new version of the paper.md looks good (only a couple of typos left, in the second paragraph "accomodate" should be "accommodate" and in the very last line "use" should be "used"). I have also closed the issue on the repository since after the last exchanges we had, the tests run fine also on my end now. 

@pjotrp from my point of view all the points raised were addressed.

**Comment by xuanxu** [comment]
Nice! 
Both typos fixed.

**Comment by pjotrp** [comment]
@arfon we are ready!

**Comment by arfon** [comment]
@xuanxu - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by xuanxu** [comment]
@arfon - Done: [DOI: 10.5281/zenodo.845342](https://doi.org/10.5281/zenodo.845342)

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.845342" target="_blank">10.5281/zenodo.845342</a> is the archive.

**Comment by arfon** [comment]
@fstrozzi - many thanks for your review and to @pjotrp for editing this submission ✨ 

@xuanxu - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00351 ⚡️ 🚀 💥

**Comment by xuanxu** [comment]
Yay! Thank you @fstrozzi, @pjotrp & @arfon 🎉
