### ISSUE TITLE
[PRE REVIEW]: DBSP_DRP: A Python package for automated spectroscopic data reduction of DBSP data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3511]
**Submitting author:** @finagle29 (<a href="http://orcid.org/0000-0003-1118-3132">Milan Roberson</a>)
**Repository:** <a href="https://github.com/finagle29/DBSP_DRP/" target ="_blank">https://github.com/finagle29/DBSP_DRP/</a>
**Version:** v0.9.0
**Editor:** @arfon
**Reviewers:** @crhea93, @arjunsavel
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8d33523aaa8283d0547994eb51b4407f/status.svg)](https://joss.theoj.org/papers/8d33523aaa8283d0547994eb51b4407f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8d33523aaa8283d0547994eb51b4407f"><img src="https://joss.theoj.org/papers/8d33523aaa8283d0547994eb51b4407f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8d33523aaa8283d0547994eb51b4407f/status.svg)](https://joss.theoj.org/papers/8d33523aaa8283d0547994eb51b4407f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @finagle29. **Currently, there isn't an JOSS editor assigned** to your paper.

@finagle29 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1158

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (530.2 files/s, 42773.8 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           28            582            427           2333
reStructuredText                 11            163            212            246
Markdown                          2             31              0            197
YAML                              6             29             11            166
TeX                               1              0              0            119
Bourne Shell                      3             16              8             42
CSS                               2              4              0             34
DOS Batch                         1              8              1             26
Dockerfile                        1             11             11             26
JavaScript                        1              3              0             13
make                              1              4              7              9
Bourne Again Shell                1              0              7              7
TOML                              1              0              0              7
--------------------------------------------------------------------------------
SUM:                             59            851            684           3225
--------------------------------------------------------------------------------


Statistical information for the repository 'd82d8114dda9467f36b0747f' was
gathered on 2021/07/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Milan Roberson                 184          5523           2220          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Milan Roberson             3303           59.8          5.2                8.39
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.02308 is OK
- 10.1086/131027 is OK
- 10.3847/1538-4357/ab8943 is OK
- 10.3847/1538-4357/abbd98 is OK
- 10.3847/1538-4357/abaeec is OK
- 10.3847/1538-4357/abb45c is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03511/joss.03511/10.21105.joss.03511.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03511/joss.03511/10.21105.joss.03511.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @xuanxu - if you could also take this one, that would be great, or let me know if you can just take one, which one you prefer

**Comment by danielskatz** [comment]
@whedon invite @xuanxu as editor

**Comment by whedon** [comment]
@xuanxu has been invited to edit this submission.

**Comment by xuanxu** [comment]
@danielskatz sorry, right now I can't take this one

**Comment by danielskatz** [comment]
@finagle29 - I'm going to put this on our waiting list until a suitable editor is available.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @finagle29 – could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by finagle29** [comment]
:wave: @arfon, I think crhea93, arjunsavel, and olebole would be good candidates to review this submission

**Comment by arfon** [comment]
:wave: @olebole, @arjunsavel, @crhea93 – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration here is [_DBSP_DRP: A Python package for automated spectroscopic data reduction of DBSP data_](https://github.com/finagle29/DBSP_DRP/).

**Comment by crhea93** [comment]
@arfon it would be my pleasure.

**Comment by arjunsavel** [comment]
@arfon happy to do so!

**Comment by arfon** [comment]
Wonderful, thanks both!

**Comment by arfon** [comment]
@whedon add @crhea93 as reviewer

**Comment by whedon** [comment]
OK, @crhea93 is now a reviewer

**Comment by arfon** [comment]
@whedon add @arjunsavel as reviewer

**Comment by whedon** [comment]
OK, @arjunsavel is now a reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3612.

**Comment by arfon** [comment]
@crhea93, @arjunsavel – see you both over in #3612 where the actual review will take place.
