### ISSUE TITLE
[PRE REVIEW]: WODEN: A CUDA-enabled package to simulate low-frequency radio interferometric data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3517]
**Submitting author:** @JLBLine (<a href="http://orcid.org/0000-0002-9130-5920">Jack L. B. Line</a>)
**Repository:** <a href="https://github.com/JLBLine/WODEN" target ="_blank">https://github.com/JLBLine/WODEN</a>
**Version:** v1.0.0
**Editor:** @dfm
**Reviewers:** @plaplant, @mkolopanis
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/bbc90ec4cd925ade93ed0781e571d247/status.svg)](https://joss.theoj.org/papers/bbc90ec4cd925ade93ed0781e571d247)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/bbc90ec4cd925ade93ed0781e571d247"><img src="https://joss.theoj.org/papers/bbc90ec4cd925ade93ed0781e571d247/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/bbc90ec4cd925ade93ed0781e571d247/status.svg)](https://joss.theoj.org/papers/bbc90ec4cd925ade93ed0781e571d247)
```

**Author instructions**

Thanks for submitting your paper to JOSS @JLBLine. **Currently, there isn't an JOSS editor assigned** to your paper.

@JLBLine if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1091

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/JSTSP.2008.2005327 is OK
- 10.1017/pasa.2012.007 is OK
- 10.1017/PASA.2020.18 is OK
- 10.1093/mnras/stab1560 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1051/0004-6361/201322068 is OK
- 10.1017/pasa.2017.54 is OK
- 10.1093/mnras/stu1368 is OK
- 10.1093/mnras/stx1547 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.78 s (273.7 files/s, 102382.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                    27            564           2136          47666
C                               54           2592           2308           9239
SVG                              4              0             69           3539
CUDA                             5            789            220           3484
Python                          29            865           1027           2386
reStructuredText                36            426            277            645
CMake                           16            109            109            613
Bourne Shell                    29             82             27            280
TeX                              1              9              0            188
JSON                             8              0              0            164
Markdown                         3             40              0            145
make                             1              4              7              9
YAML                             1              4             10              7
-------------------------------------------------------------------------------
SUM:                           214           5484           6190          68365
-------------------------------------------------------------------------------


Statistical information for the repository 'e61244a56c36d418556774b0' was
gathered on 2021/07/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
JLBLine                        117         35977          13797           95.94
Jack Line                       10          1231            665            3.65
Tony Farlie                      2           181             32            0.41

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
JLBLine                   68783          191.2          2.1                8.27
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03517/joss.03517/10.21105.joss.03517.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03517/joss.03517/10.21105.joss.03517.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@JLBLine - thanks for your submission.
Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

**Comment by JLBLine** [comment]
Roger that @danielskatz, no problem. Looking through the list of potential reviewers, I picked out a number who are both astronomers and have CUDA listed in their languages: devanshkv, Fipanther, adam-m-jcbs, hopefully that helps

**Comment by danielskatz** [comment]
Thanks - the editor will follow-up with you on this.

**Comment by arfon** [comment]
@whedon invite @dfm as editor

:wave: @dfm – would you be willing to take this submission on?

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by dfm** [comment]
@whedon assign me as editor

Sure - I'm happy to edit! I'll be offline next week and have several reviews in progress, but I'll aim to get the process started the following week. Thanks for your patience!

**Comment by dfm** [comment]
@whedon add @plaplant as reviewer

Thanks Paul for agreeing to review this submission! I'm still working on recruiting a second reviewer, but as soon as I do I'll get the review started properly.

**Comment by whedon** [comment]
OK, @plaplant is now a reviewer

**Comment by dfm** [comment]
@whedon add @mkolopanis as reviewer

Matthew has agreed to be our second reviewer - thanks!!

I'll start the review shortly and share more info in the main review issue thread. Please get in touch if you have any questions as we go.

**Comment by whedon** [comment]
OK, @mkolopanis is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3676.
