### ISSUE TITLE
[PRE REVIEW]: Luci: A Python package for SITELLE spectral analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3518]
**Submitting author:** @crhea93 (<a href="http://orcid.org/0000-0003-2001-1076">Carter Rhea</a>)
**Repository:** <a href="https://github.com/crhea93/LUCI" target ="_blank">https://github.com/crhea93/LUCI</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/bf30bb06b79e3803a8375b140d44950e/status.svg)](https://joss.theoj.org/papers/bf30bb06b79e3803a8375b140d44950e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/bf30bb06b79e3803a8375b140d44950e"><img src="https://joss.theoj.org/papers/bf30bb06b79e3803a8375b140d44950e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/bf30bb06b79e3803a8375b140d44950e/status.svg)](https://joss.theoj.org/papers/bf30bb06b79e3803a8375b140d44950e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @crhea93. **Currently, there isn't an JOSS editor assigned** to your paper.

@crhea93 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 925

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "@" (AT) [#<BibTeX::Bibliography data=[4]>, "@", #<BibTeX::Entry >, {:title=>["{ORBS}: A data reduction software for the imaging Fourier transform spectrometers {SpIOMM} and {SITELLE}"], :volume=>["8451"], :url=>["https://www.spiedigitallibrary.org/conference-proceedings-of-spie/8451/84513K/ORBS--A-data-reduction-software-for-the-imaging-Fourier/10.1117/12.925420.short"], :doi=>["10.1117/12.925420"], :shorttitle=>["{ORBS}"], :abstract=>["{SpIOMM} (Spectromètre-Imageur de l'Observatoire du Mont Mégantic) is still the only operational astronomical Imaging Fourier Transform Spectrometer ({IFTS}) capable of obtaining the visible spectrum of every source of light in a field of view of 12 arc-minutes. Even if it has been designed to work with both outputs of the Michelson interferometer, up to now only one output has been used. Here we present {ORBS} (Outils de Réduction Binoculaire pour {SpIOMM}/{SITELLE}), the reduction software we designed in order to take advantage of the two output data. {ORBS} will also be used to reduce the data of {SITELLE} (Spectromètre-Imageur pour l' Étude en Long et en Large des raies d' Émissions) \\{ the direct successor of {SpIOMM}, which will be in operation at the Canada-France- Hawaii Telescope ({CFHT}) in early 2013. {SITELLE} will deliver larger data cubes than {SpIOMM} (up to 2 cubes of 34 Go each). We thus have made a strong effort in optimizing its performance efficiency in terms of speed and memory usage in order to ensure the best compliance with the quality characteristics discussed with the {CFHT} team. As a result {ORBS} is now capable of reducing 68 Go of data in less than 20 hours using only 5 Go of random-access memory ({RAM}).}, eventtitle = {Software and Cyberinfrastructure for Astronomy {II}}, pages = {84513K}, booktitle = {Software and Cyberinfrastructure for Astronomy {II}}, publisher = {International Society for Optics and Photonics}, author = {Martin, T. and Drissen, L. and Joncas, G.}, urldate = {2020-07-02}, date = {2012}, file = {Snapshot:/home/carterrhea/Zotero/storage/F6DUW88N/12.925420.html:text/html}, "]}]

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.39 s (272.3 files/s, 120746.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      15           2517           2695           9876
HTML                            18           2144             55           3504
SVG                              1              0              0           2671
Jupyter Notebook                26              0          15827           2392
Python                          13            256            807           1449
CSS                              4            191             35            757
reStructuredText                14            366            297            404
YAML                             2              6             10            212
TeX                              2             12              0            191
Markdown                         2             41              0            146
XML                              6              0              0             84
DOS Batch                        1              8              1             26
make                             1              6              7             12
INI                              1              0              0              6
-------------------------------------------------------------------------------
SUM:                           106           5547          19734          21730
-------------------------------------------------------------------------------


Statistical information for the repository '264234fcccae31c1aacc0e3a' was
gathered on 2021/07/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Carter Rhea                     41         34012           1268          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Carter Rhea               32744           96.3          0.3               17.57
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03518/joss.03518/10.21105.joss.03518.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03518/joss.03518/10.21105.joss.03518.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @openjournals/dev  - any ideas on the bib problem here?

**Comment by danielskatz** [comment]
👋 @crhea93 - Thanks for your submission - due to a lack of available editors in the topic area, I'm going to put it on our waiting list, hopefully just for a short time.  Also note that we need to have an explicit Statement of Need section in the paper, so please add one, and then use `@whedon generate pdf` as the first line in a new comment to regenerate the PDF

**Comment by danielskatz** [comment]
Also, the comment in the paper "At her heart, LUCI is nothing more than a wrapper for a scipy.optimize.minimize function call" concerns me a little, so I'm going to ask other editors to look at the scope of this to ensure it is suitable for review by JOSS.

**Comment by danielskatz** [comment]
@whedon scope check

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@whedon scope queury

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by crhea93** [comment]
@danielskatz Thank you for the information! I will add the  Statement of Need. 

As for the comment, it was perhaps a gross oversimplification, but the essence of all fitting code is a single function call to fit a spectrum. That being said, LUCI does a considerable amount of work to get the spectra into the proper format (including several steps of corrections) and a large amount of post-processing.

**Comment by crhea93** [comment]
I've updated that particular sentence to reflect my previous statement.

**Comment by crhea93** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03518/joss.03518/10.21105.joss.03518.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03518/joss.03518/10.21105.joss.03518.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "@" (AT) [#<BibTeX::Bibliography data=[4]>, "@", #<BibTeX::Entry >, {:title=>["{ORBS}: A data reduction software for the imaging Fourier transform spectrometers {SpIOMM} and {SITELLE}"], :volume=>["8451"], :url=>["https://www.spiedigitallibrary.org/conference-proceedings-of-spie/8451/84513K/ORBS--A-data-reduction-software-for-the-imaging-Fourier/10.1117/12.925420.short"], :doi=>["10.1117/12.925420"], :shorttitle=>["{ORBS}"], :abstract=>["{SpIOMM} (Spectromètre-Imageur de l'Observatoire du Mont Mégantic) is still the only operational astronomical Imaging Fourier Transform Spectrometer ({IFTS}) capable of obtaining the visible spectrum of every source of light in a field of view of 12 arc-minutes. Even if it has been designed to work with both outputs of the Michelson interferometer, up to now only one output has been used. Here we present {ORBS} (Outils de Réduction Binoculaire pour {SpIOMM}/{SITELLE}), the reduction software we designed in order to take advantage of the two output data. {ORBS} will also be used to reduce the data of {SITELLE} (Spectromètre-Imageur pour l' Étude en Long et en Large des raies d' Émissions) \\{ the direct successor of {SpIOMM}, which will be in operation at the Canada-France- Hawaii Telescope ({CFHT}) in early 2013. {SITELLE} will deliver larger data cubes than {SpIOMM} (up to 2 cubes of 34 Go each). We thus have made a strong effort in optimizing its performance efficiency in terms of speed and memory usage in order to ensure the best compliance with the quality characteristics discussed with the {CFHT} team. As a result {ORBS} is now capable of reducing 68 Go of data in less than 20 hours using only 5 Go of random-access memory ({RAM}).}, eventtitle = {Software and Cyberinfrastructure for Astronomy {II}}, pages = {84513K}, booktitle = {Software and Cyberinfrastructure for Astronomy {II}}, publisher = {International Society for Optics and Photonics}, author = {Martin, T. and Drissen, L. and Joncas, G.}, urldate = {2020-07-02}, date = {2012}, file = {Snapshot:/home/carterrhea/Zotero/storage/F6DUW88N/12.925420.html:text/html}, "]}]

**Comment by arfon** [comment]
Something in the BibTeX is tripping up Whedon. Removing [this line](https://github.com/crhea93/LUCI/blob/main/Luci.bib#L80) from `Luci.bib` should fix things.

**Comment by crhea93** [comment]
@arfon I have updated the bib file. Thank you immensely for diagnosing that issue!

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/mnras/stz627 is OK
- 10.1093/mnras/stw2315 is OK
- 10.1111/j.1365-2966.2006.10859.x is OK
- 10.1086/130766 is OK
- 10.1117/12.925420 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.1086/670067 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋 @crhea93 - I'm sorry to say that after discussion amongst the JOSS editors, we have decided not to review this submission as written because we don't believe it is packaged appropriately for further maintenance, sustainable, and community use/contributions.  We do, however, appreciate the examples and documentation.  We would welcome a resubmission if the packaging is improved.  https://packaging.python.org might be a useful reference.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by crhea93** [comment]
@danielskatz Thank you very much for your consideration. I would like to resubmit after completing the requirements. I would just like to be certain that I am addressing the correct issue. The problem with the submission is that the software is not properly packaged, is that correct? Are the installation instructions included on the Github repo not sufficient? I've had several users successfully install and use the software with ease. I've also had successful pull requests from other users.

**Comment by danielskatz** [comment]
The primary issue that came up in the editor discussion was packaging, with the site provided (https://packaging.python.org) suggested as a reference for how packaging can be done for python. Having software on github with installation instructions is not the same as having packaged software.

**Comment by danielskatz** [comment]
You will to resubmit - just as you did initially.  And please mention this issue in the resubmission.

**Comment by crhea93** [comment]
Great! Thank you very much!

**Comment by dfm** [comment]
@crhea93: I would say that there are several remaining issues with the repo. There are several copies of the source (at `LUCI` and `src/LUCI`), many temp files that should not be checked into version control (e.g. `.ipynb_checkpoints`, `dist`, `__pycache__`, and many others), and some issues with the packaging (what are the relationships between `ML`, `Notebooks`, `Examples`, `Data` directories and are they required for use of the package). I'd recommend spending some time getting things set up in a way that follows the standard practices of Python packaging (it's not enough to just have a PyPI install!) before resubmitting.

**Comment by crhea93** [comment]
@dfm Thank you for taking the time to look over the repo. I very much appreciate the guidance! I will work on cleaning this up before submitting it.
