### ISSUE TITLE
[PRE REVIEW]: elmada: Dynamic electricity carbon emission factors and prices for Europe

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3528]
**Submitting author:** @mfleschutz (<a href="http://orcid.org/0000-0002-8516-9635">Markus Fleschutz</a>)
**Repository:** <a href="https://github.com/DrafProject/elmada" target ="_blank">https://github.com/DrafProject/elmada</a>
**Version:** v0.0.6
**Editor:** @fraukewiese
**Reviewers:** @nmstreethran, @olejandro 
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/9a6bf04b8a7bbc6b29b2ad79103acf42/status.svg)](https://joss.theoj.org/papers/9a6bf04b8a7bbc6b29b2ad79103acf42)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/9a6bf04b8a7bbc6b29b2ad79103acf42"><img src="https://joss.theoj.org/papers/9a6bf04b8a7bbc6b29b2ad79103acf42/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/9a6bf04b8a7bbc6b29b2ad79103acf42/status.svg)](https://joss.theoj.org/papers/9a6bf04b8a7bbc6b29b2ad79103acf42)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mfleschutz. **Currently, there isn't an JOSS editor assigned** to your paper.

@mfleschutz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 480

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.apenergy.2021.117040 is OK
- 10.5281/zenodo.5126771 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (376.5 files/s, 94902.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              5              0             33           7892
Python                          33            920            423           2827
Markdown                         5            190              0            523
YAML                             4              9              4            120
HTML                             1              7              0             51
TeX                              1              5              0             45
JSON                             1              0              0             28
TOML                             1              1              1             18
INI                              1              0              2             10
-------------------------------------------------------------------------------
SUM:                            52           1132            463          11514
-------------------------------------------------------------------------------


Statistical information for the repository '9ec23e61ec74125d60b5b612' was
gathered on 2021/07/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
flma0001                        46          6772           2602          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
flma0001                   4170           61.6          0.9                7.22
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03528/joss.03528/10.21105.joss.03528.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03528/joss.03528/10.21105.joss.03528.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @fraukewiese - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @fraukewiese as editor

**Comment by whedon** [comment]
@fraukewiese has been invited to edit this submission.

**Comment by arfon** [comment]
> 👋 @fraukewiese - would you be able to edit this submission?

Just an FYI that @fraukewiese is OoO until 3 August so might be a little slow to respond here :-)

**Comment by danielskatz** [comment]
I think this is still the best option for this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @fraukewiese as editor

**Comment by whedon** [comment]
@fraukewiese has been invited to edit this submission.

**Comment by fraukewiese** [comment]
@whedon assign me as editor

**Comment by nmstreethran** [comment]
@fraukewiese Yes, I'd be happy to review this submission.

**Comment by fraukewiese** [comment]
Great! Thanks @nmstreethran 
I will add you as a reviewer now but won't actually start the review until we have a second reviewer signed up.

**Comment by fraukewiese** [comment]
@whedon add @nmstreethran as reviewer

**Comment by whedon** [comment]
OK, @nmstreethran is now a reviewer

**Comment by fraukewiese** [comment]
@milicag , @ckaldemeyer – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is elmada: Dynamic electricity carbon emission factors and prices for Europe

**Comment by fraukewiese** [comment]
For information: I am contacting milicag and ckaldemeyer now per Mail to find out whether they could review, if not I will ask other reviewer.

**Comment by fraukewiese** [comment]
ckaldemeyer cannot review this (answer by Mail) and I do not receive an answer from milicag (also by Mail), so I will ask other potential reviewer now.

**Comment by fraukewiese** [comment]
@olejandro : would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: [https://joss.readthedocs.io/en/latest/reviewer_guidelines.html](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

The submission under review here is [elmada: Dynamic electricity carbon emission factors and prices for Europe](https://github.com/DrafProject/elmada)

**Comment by olejandro** [comment]
@fraukewiese Yes, I'd be happy to. What's the timeframe?

**Comment by fraukewiese** [comment]
Great, thanks @olejandro ! 
We aim for the review process to be completed within about 4-6 weeks but it is necessary to make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by fraukewiese** [comment]
@whedon add @olejandro  as reviewer

**Comment by whedon** [comment]
OK, @olejandro  is now a reviewer

**Comment by fraukewiese** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3625.

**Comment by fraukewiese** [comment]
@olejandro  , @nmstreethran  – thanks a lot for agreeing to review here! See you over in #3625 where the actual review will take place.
