### ISSUE TITLE
[PRE REVIEW]: xicorr: A Python package of a novel tie-breaking correlation metric

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3529]
**Submitting author:** olgabot (<a href="http://orcid.org/0000-0003-4412-7970">Olga Botvinnik</a>)
**Repository:** <a href="https://github.com/czbiohub/xicor/" target ="_blank">https://github.com/czbiohub/xicor/</a>
**Version:** v0.1.0dev0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/24958dc9740d21180f79d7c2cbd73bfb/status.svg)](https://joss.theoj.org/papers/24958dc9740d21180f79d7c2cbd73bfb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/24958dc9740d21180f79d7c2cbd73bfb"><img src="https://joss.theoj.org/papers/24958dc9740d21180f79d7c2cbd73bfb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/24958dc9740d21180f79d7c2cbd73bfb/status.svg)](https://joss.theoj.org/papers/24958dc9740d21180f79d7c2cbd73bfb)
```

**Author instructions**

Thanks for submitting your paper to JOSS olgabot. **Currently, there isn't an JOSS editor assigned** to your paper.

olgabot if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 598

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (318.4 files/s, 80490.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              2              0             55           2834
Python                           6             78             67            285
Markdown                         4             62              0            190
Jupyter Notebook                 1              1            602             50
YAML                             2              1              4             28
TeX                              1              2              0             19
make                             1              6              0             14
-------------------------------------------------------------------------------
SUM:                            17            150            728           3420
-------------------------------------------------------------------------------


Statistical information for the repository '8a62b2fa50a6ac2ffd5993e9' was
gathered on 2021/07/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Phoenix Logan                    1             1              2            0.30
phoenixAja                      10           357            124           48.63
pranathi.vemuri                 13           152             87           24.17
pranathivemuri                   2           266              0           26.90

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Phoenix Logan               167        16700.0          9.8                5.39
pranathivemuri              263           98.9          7.0               13.31
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3529 with the following error: 
```
 [WARNING] Could not convert image '/tmp/tex2pdf.-64197d0ebb59bcef/6b7b63c5835497424d5a4176bfacba42326736aa.svg': check that rsvg-convert is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
[WARNING] Could not convert image '/tmp/tex2pdf.-64197d0ebb59bcef/5ad71c88f3ac6b7e9941081e3b99341bb11f49c7.svg': check that rsvg-convert is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.-64197d0ebb59bc
ef/6b7b63c5835497424d5a4176bfacba42326736aa.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.398 ...63c5835497424d5a4176bfacba42326736aa.svg}

Looks like we failed to compile the PDF

```

**Comment by danielskatz** [comment]
👋 @olgabot - I'm sorry to say that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.  Alternatively, if you add additional code and functions, we would be happy to consider review of a more substantive package.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
