### ISSUE TITLE
[PRE REVIEW]: gmm_diag and gmm_full: C++ classes for multi-threaded Gaussian mixture models and Expectation-Maximisation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#353]
**Submitting author:** @conradsnicta (<a href="http://orcid.org/0000-0002-0049-4501">Conrad Sanderson</a>)
**Repository:** <a href="https://github.com/conradsnicta/armadillo-gmm" target ="_blank">https://github.com/conradsnicta/armadillo-gmm</a>
**Version:** v7.960
**Editor:** @arfon
**Reviewer:** @jordigh

**Author instructions**

Thanks for submitting your paper to JOSS @conradsnicta. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@conradsnicta if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of JOSS reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
👋 @jordigh - would you be willing to review this submission for JOSS?

**Comment by jordigh** [comment]
Ohai. So, a long time I ago I stopped paying attention to JOSS notifications because it was too much of a firehose, and I recently unsubscribed. Getting individually approached for one revision at a time, however, seems much more manageable. This submission does look like something I can work on.

Sorry, I've been out of the loop. Do we have a rubric somewhere that I can use to evaluate this submission?

**Comment by arfon** [comment]
> This submission does look like something I can work on.

Great, thanks!

> Getting individually approached for one revision at a time, however, seems much more manageable.

Yes, we've improved our workflow a fair bit since you probably unsubscribed 😁 

> Sorry, I've been out of the loop. Do we have a rubric somewhere that I can use to evaluate this submission?

Yes. I'll make the review issue now with the checklist and see you over there.

**Comment by arfon** [comment]
@whedon assign @jordigh as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jordigh

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/365. Feel free to close this issue now!

**Comment by arfon** [comment]
@jordigh - please head over to #365 for the actual submission review.
