### ISSUE TITLE
[PRE REVIEW]: BioProv - A provenance library for bioinformatics workflows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3531]
**Submitting author:** @vinisalazar (<a href="http://orcid.org/0000-0002-8362-3195">Vinícius Salazar</a>)
**Repository:** <a href="https://github.com/vinisalazar/BioProv/" target ="_blank">https://github.com/vinisalazar/BioProv/</a>
**Version:** v0.1.23
**Editor:** @jmschrei
**Reviewers:** @maximtrp, @Zethson
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3614862df6bf7936838eaa786664deea/status.svg)](https://joss.theoj.org/papers/3614862df6bf7936838eaa786664deea)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3614862df6bf7936838eaa786664deea"><img src="https://joss.theoj.org/papers/3614862df6bf7936838eaa786664deea/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3614862df6bf7936838eaa786664deea/status.svg)](https://joss.theoj.org/papers/3614862df6bf7936838eaa786664deea)
```

**Author instructions**

Thanks for submitting your paper to JOSS @vinisalazar. **Currently, there isn't an JOSS editor assigned** to your paper.

@vinisalazar if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (404.6 files/s, 66434.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          26           1008           1283           3809
Markdown                         5            108              0            333
YAML                             7             17             16            244
reStructuredText                 7             60            110             76
Jupyter Notebook                 2              0            860             67
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            49           1205           2277           4564
-------------------------------------------------------------------------------


Statistical information for the repository 'c67002abd0319f5890ccd4d3' was
gathered on 2021/07/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vini Salazar                   519         12583           6617           95.88
jvfe                            23           622            202            4.12

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vini Salazar               5640           44.8          6.6               10.71
jvfe                        446           71.7          5.4                4.04
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3531 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3531 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Vinícius Salazar, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/nmeth.3176 is OK
- 10.1145/2457317.2457365 is OK
- 10.1093/bib/bbm015 is OK
- 10.1093/bioinformatics/btp163 is OK
- 10.1109/IPDPSW.2014.65 is OK
- 10.1007/978-3-319-22885-3_29 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1186/1471-2105-14-S11-S6 is OK
- 10.1038/nbt.3820 is OK
- 10.1093/nar/gkh340 is OK
- 10.1038/nbt.3772 is OK
- 10.1186/1471-2105-11-119 is OK
- 10.1093/bioinformatics/bts480 is OK
- 10.1093/nar/gkw1009 is OK
- 10.1371/journal.pbio.2002050 is OK
- 10.1504/ijbpim.2010.033176 is OK
- 10.1186/s12859-017-1747-0 is OK
- 10.1093/nar/gki198 is OK
- 10.1093/gigascience/giz095 is OK
- 10.1038/sdata.2017.114 is OK
- 10.14778/3229863.3236265 is OK
- 10.1093/bib/bbm015 is OK
- 10.1371/journal.pcbi.1005510 is OK

MISSING DOIs

- 10.1093/nar/gkaa554 may be a valid DOI for title: The Galaxy platform for accessible, reproducible and collaborative biomedical analyses: 2018 update
- 10.1007/s10723-012-9227-2 may be a valid DOI for title: A provenance-based adaptive scheduling heuristic for parallel scientific workflows in clouds
- 10.1007/3-540-44503-x_20 may be a valid DOI for title: Why and Where: A Characterization of Data Provenance

INVALID DOIs

- 10.2200/S00528ED1V01Y201308WEB007 is INVALID
```

**Comment by danielskatz** [comment]
👋 @vinisalazar - note that your paper does not compile. Please follow the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` after making changes to the .md file or when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
👋 @jmschrei - Is this a paper you would be able to edit?

**Comment by danielskatz** [comment]
@whedon invite @jmschrei as editor

**Comment by whedon** [comment]
@jmschrei has been invited to edit this submission.

**Comment by jmschrei** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jmschrei

**Comment by jmschrei** [comment]
@krother and  @genomematt, would either of you be able to serve as a reviewer for this submission?

**Comment by vinisalazar** [comment]
Hi @danielskatz and @jmschrei. Thank you for the prompt handling of the paper. I will make the changes as soon as possible and report back here. Have a nice weekend!

Best,
Vini

**Comment by vinisalazar** [comment]
@whedon check references

**Comment by jmschrei** [comment]
@rcannood and @maximtrp, would either of you be able to serve as a reviewer for this submission?

**Comment by maximtrp** [comment]
@jmschrei Yes, I will be glad to

**Comment by vinisalazar** [comment]
Hi, I'm not sure why the @whedon command did not work. The references and compilation should be ok now.

**Comment by jmschrei** [comment]
@whedon add @maximtrp as reviewer

**Comment by whedon** [comment]
OK, @maximtrp is now a reviewer

**Comment by jmschrei** [comment]
@hadrieng and @kanekalla, would either of you be able to serve as a reviewer for this submission?

**Comment by jmschrei** [comment]
@zethson and @jkanche, would either of you be available to serve as a reviewer for this submission?

**Comment by Zethson** [comment]
Yes. But I'll be away for 1 month. If this is not an issue I can do it.

**Comment by jmschrei** [comment]
No problem. Thanks for agreeing!

**Comment by whedon** [comment]
OK, @Zethson is now a reviewer

**Comment by jmschrei** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3622.
