### ISSUE TITLE
[PRE REVIEW]: bumbl: An R package for modeling growth-switchpoint-decline in bumblebee colony size

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3532]
**Submitting author:** @Aariq (<a href="http://orcid.org/0000-0002-7430-7879">Eric R. Scott</a>)
**Repository:** <a href="https://github.com/Aariq/bumbl" target ="_blank">https://github.com/Aariq/bumbl</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/7a652c8b3ef4356bfd675f1ebb7375a4/status.svg)](https://joss.theoj.org/papers/7a652c8b3ef4356bfd675f1ebb7375a4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7a652c8b3ef4356bfd675f1ebb7375a4"><img src="https://joss.theoj.org/papers/7a652c8b3ef4356bfd675f1ebb7375a4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7a652c8b3ef4356bfd675f1ebb7375a4/status.svg)](https://joss.theoj.org/papers/7a652c8b3ef4356bfd675f1ebb7375a4)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Aariq. **Currently, there isn't an JOSS editor assigned** to your paper.

@Aariq if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 845

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (591.1 files/s, 78641.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         8            342              0            879
R                               10            114            252            648
XML                              1              0              2            441
Rmd                              5            245            496            371
YAML                             4             20              6            119
TeX                              2              9              0             47
-------------------------------------------------------------------------------
SUM:                            30            730            756           2505
-------------------------------------------------------------------------------


Statistical information for the repository 'f334f684fd49f61a549065c1' was
gathered on 2021/07/23.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/ele.12581 is OK
- 10/bqhp9z is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03532/joss.03532/10.21105.joss.03532.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03532/joss.03532/10.21105.joss.03532.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @Aariq - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
👋 @Aariq - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

I also apologize for the longer-than-expected decision process.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by Aariq** [comment]
Thanks, I understand. Out of curiosity, was this decision based in part on
me being the sole author, or was it just the relatively small amount of
code? I understand if you can't say.

**Comment by danielskatz** [comment]
You being sole author was not a factor.
