### ISSUE TITLE
[PRE REVIEW]: Lidium: a 3D point cloud processing software for TLS LiDAR data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3533]
**Submitting author:** @nsviel (<a href="http://orcid.org/0000-0002-4608-5850">Nathan</a>)
**Repository:** <a href="https://github.com/nsviel/Lidium" target ="_blank">https://github.com/nsviel/Lidium</a>
**Version:** v1.0.0
**Editor:** @martinfleis
**Reviewers:** @lachlangrose, @hechth
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6e5678fe608197d111a04ea96325b20e/status.svg)](https://joss.theoj.org/papers/6e5678fe608197d111a04ea96325b20e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6e5678fe608197d111a04ea96325b20e"><img src="https://joss.theoj.org/papers/6e5678fe608197d111a04ea96325b20e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6e5678fe608197d111a04ea96325b20e/status.svg)](https://joss.theoj.org/papers/6e5678fe608197d111a04ea96325b20e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nsviel. **Currently, there isn't an JOSS editor assigned** to your paper.

@nsviel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 753

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.06 s (449.5 files/s, 195855.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   386          19139          28944         105824
C++                             76           6595           7002          37384
make                             1            683            253           1342
CMake                            9             60             35            461
JSON                             1              0              0            357
Markdown                         2             26              0             65
TeX                              1              7              0             56
F#                               1              2              0              7
Bourne Shell                     1              6              9              6
-------------------------------------------------------------------------------
SUM:                           478          26518          36243         145502
-------------------------------------------------------------------------------


Statistical information for the repository 'ed9754aa71c91554bcb35193' was
gathered on 2021/07/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
nsviel                           3        104831           2026          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
nsviel                   204699          195.3          0.0               18.10
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3533 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (441ad72063ca845d42acc5a5/paper/paper.md): could not find expected ':' while scanning a simple key at line 22 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
@whedon check references

**Comment by danielskatz** [comment]
👋 @nsviel - note that your paper does not compile. Please follow the [example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography). I also suspect there is something incorrect in your .bib file, since the check references command isn't returning. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` after making changes to the .md file or when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
Additionally due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

**Comment by nsviel** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/s151128099 is OK

MISSING DOIs

- 10.1016/j.isprsjprs.2020.11.015 may be a valid DOI for title: Radiometric Correction of Laser Scanning Intensity Data Applied For Terrestrial Laser Scanning.
- 10.1109/icra.2011.5980567 may be a valid DOI for title: 3D is here: Point Cloud Library (PCL)

INVALID DOIs

- None
```

**Comment by nsviel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03533/joss.03533/10.21105.joss.03533.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03533/joss.03533/10.21105.joss.03533.pdf) :page_facing_up: :point_left:

**Comment by nsviel** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/s151128099 is OK

MISSING DOIs

- 10.1109/icra.2011.5980567 may be a valid DOI for title: 3D is here: Point Cloud Library (PCL)

INVALID DOIs

- https://doi.org/10.1016/j.isprsjprs.2020.11.015 is INVALID because of 'https://doi.org/' prefix
```

**Comment by nsviel** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/s151128099 is OK

MISSING DOIs

- 10.1109/icra.2011.5980567 may be a valid DOI for title: 3D is here: Point Cloud Library (PCL)

INVALID DOIs

- https://doi.org/10.1016/j.isprsjprs.2020.11.015 is INVALID because of 'https://doi.org/' prefix
```

**Comment by nsviel** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "DOI" (NAME) [#<BibTeX::Bibliography data=[3]>, "@", #<BibTeX::Entry >, {:author=>["Radu Bogdan Rusu and Steve Cousins"], :title=>["{3D is here: Point Cloud Library (PCL)}"], :booktitle=>["{IEEE International Conference on Robotics and Automation (ICRA)}"], :month=>["May 9-13"], :year=>["2011"], :address=>["Shanghai, China"]}]

**Comment by nsviel** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.isprsjprs.2020.11.015 is OK
- 10.3390/s151128099 is OK
- 10.1109/ICRA.2011.5980567 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by nsviel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03533/joss.03533/10.21105.joss.03533.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03533/joss.03533/10.21105.joss.03533.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @martinfleis as editor

:wave: @martinfleis – I realize this might be a little out of your comfort zone regarding programming languages etc. but I wonder if you'd be willing to take this submission on for us?

**Comment by martinfleis** [comment]
@whedon assign me as editor

@arfon It is on the very edge of the comfort zone :).

**Comment by whedon** [comment]
OK, the editor is @martinfleis

**Comment by martinfleis** [comment]
@whedon assign @lachlangrose as reviewer

**Comment by whedon** [comment]
OK, @lachlangrose is now a reviewer

**Comment by martinfleis** [comment]
@whedon add @hechth as reviewer

**Comment by whedon** [comment]
OK, @hechth is now a reviewer

**Comment by martinfleis** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3623.
