### ISSUE TITLE
[PRE REVIEW]: The Python Sky Model 3 software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3534]
**Submitting author:** @zonca (<a href="http://orcid.org/0000-0001-6841-1058">Andrea Zonca</a>)
**Repository:** <a href="https://github.com/galsci/pysm" target ="_blank">https://github.com/galsci/pysm</a>
**Version:** 3.3.1
**Editor:** @christinahedges
**Reviewers:** @patricialarsen, @smsharma
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8f2d6c3bbf6cbeffbb403a1207fa8de7/status.svg)](https://joss.theoj.org/papers/8f2d6c3bbf6cbeffbb403a1207fa8de7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8f2d6c3bbf6cbeffbb403a1207fa8de7"><img src="https://joss.theoj.org/papers/8f2d6c3bbf6cbeffbb403a1207fa8de7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8f2d6c3bbf6cbeffbb403a1207fa8de7/status.svg)](https://joss.theoj.org/papers/8f2d6c3bbf6cbeffbb403a1207fa8de7)
```

**Author instructions**

Thanks for submitting your paper to JOSS @zonca. **Currently, there isn't an JOSS editor assigned** to your paper.

@zonca if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1150

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (639.8 files/s, 103335.1 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           42            820           1400           2965
Jupyter Notebook                  8              0           4416            527
reStructuredText                  9            152             26            313
TeX                               1              8              0            186
DOS Batch                         1             21              1            150
make                              1             22              5            106
INI                               1             14              0             90
YAML                              3             12             22             85
Markdown                          1             22              0             74
Bourne Shell                      2              0              0             12
Bourne Again Shell                1              1              5              5
TOML                              1              2              0              5
--------------------------------------------------------------------------------
SUM:                             71           1074           5875           4518
--------------------------------------------------------------------------------


Statistical information for the repository '47b8990881cbbcdb2803be82' was
gathered on 2021/07/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrea Zonca                   218          6873           3271           79.11
Ben Thorne                      21           706            173            6.86
NicolettaK                       1            21             15            0.28
Xavier Garrido                   3            51             27            0.61
ben thorne                      11          1345            340           13.14

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrea Zonca               4696           68.3         23.0               12.18
Ben Thorne                  102           14.4         29.2               14.71
NicolettaK                   17           81.0         11.5                0.00
Xavier Garrido               41           80.4         16.1                4.88
ben thorne                  329           24.5         25.7               15.20
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1086/427976 is OK
- 10.21105/joss.01298 is OK
- 10.1093/mnras/stx949 is OK
- 10.1088/0067-0049/208/2/20 is OK
- 10.1145/2833157.2833162 is OK
- 10.1051/0004-6361/201321494 is OK
- 10.1051/0004-6361/201322068 is OK
- 10.3847/1538-3881/aabc4f is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03534/joss.03534/10.21105.joss.03534.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03534/joss.03534/10.21105.joss.03534.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@zonca - thanks for your submission.
Due to a current shortage of editors (that we are working to resolve), I'm going to put it on our waiting list until an appropriate editor is available.

**Comment by zonca** [comment]
thanks @danielskatz
Can I post a pre-print of the paper to the Arxiv in the meantime?

**Comment by danielskatz** [comment]
Yes, that's fine.  Also, be aware that you need to have an open source license - I see what I think is a BSD 3-clause license in a subdirectory, which JOSS did not find, so this is technically ok.  Normally, this would be in the top level of the repo and would be called LICENSE so that GitHub knows it is there and labels the repo correctly and JOSS knows it's there.  This placement is not required by JOSS, but is a common practice.

**Comment by zonca** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by zonca** [comment]
thanks @danielskatz, I moved the license to the root of the repository, I don't know how to tell whedon to check again.

I also published the preprint to Arxiv: https://arxiv.org/abs/2108.01444

**Comment by danielskatz** [comment]
Thanks - hopefully a suitable editor will become available soon.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @zonca – many thanks for your submission to JOSS! Could you take a look a [this list of potential reviewers](https://bit.ly/joss-reviewers) and identify a few people who would be good candidates to review this submission?

**Comment by zonca** [comment]
thanks @arfon!

first choice would be cosmology + python, specific CMB knowledge first: Pqrs6, sibirrer, smsharma, benjaminrose, danehkar, yymao, aureliocarnero, changhoonhahn, Christovis, rmorgan10, villaa

**Comment by zonca** [comment]
@arfon no answers, do you plan to ask someone else? Thanks!

**Comment by sibirrer** [comment]
sorry for not having responded @arfon ! I am currently overwhelmed with other tasks and have to pass on this (very nice) software review.

**Comment by arfon** [comment]
:wave: @aureliocarnero @Pqrs6 @sibirrer – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under consideration here is [_The Python Sky Model 3 software_](https://github.com/galsci/pysm).

**Comment by arfon** [comment]
@whedon assign @christinahedges as editor

**Comment by whedon** [comment]
OK, the editor is @christinahedges

**Comment by arfon** [comment]
:wave: @zonca – @christinahedges has kindly agreed to take on editing this submission. Thanks @christinahedges ✨

**Comment by christinahedges** [comment]
👋 @zonca - thanks for your submission and patience! I'm going to be your new editor now and we'll find some reviewers for your submission and get your review started ASAP.

**Comment by christinahedges** [comment]
@whedon assign @patricialarsen as reviewer

**Comment by whedon** [comment]
OK, @patricialarsen is now a reviewer

**Comment by christinahedges** [comment]
@whedon add @smsharma as reviewer

**Comment by whedon** [comment]
OK, @smsharma is now a reviewer

**Comment by christinahedges** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3783.
