### ISSUE TITLE
[PRE REVIEW]: tidygeocoder: An R package for geocoding

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3535]
**Submitting author:** @jessecambon (<a href="http://orcid.org/0000-0001-6854-1514">Jesse Cambon</a>)
**Repository:** <a href="https://github.com/jessecambon/tidygeocoder" target ="_blank">https://github.com/jessecambon/tidygeocoder</a>
**Version:** v1.0.3
**Editor:** @elbeejay
**Reviewers:** @cole-brokamp, @tsamsonov
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7/status.svg)](https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7"><img src="https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7/status.svg)](https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jessecambon. **Currently, there isn't an JOSS editor assigned** to your paper.

@jessecambon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3535 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.20 s (877.7 files/s, 229442.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      24           3075           3499          14545
HTML                            31           1823            423           9689
R                               88           2076           2076           6389
CSS                              9            112             94            853
Rmd                              6            245            400            455
Markdown                         5             76              0            259
JSON                             2              1              0            173
YAML                             3             23              3            155
XML                              1              0              0             66
SVG                              9              0              1             19
-------------------------------------------------------------------------------
SUM:                           178           7431           6496          32603
-------------------------------------------------------------------------------


Statistical information for the repository '81bdb298c2d30237a36d2246' was
gathered on 2021/07/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jesse Cambon                    12         67978          15249          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jesse Cambon              52377           77.0          1.8               17.35
```

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by danielskatz** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03535/joss.03535/10.21105.joss.03535.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03535/joss.03535/10.21105.joss.03535.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4686074 is OK
- 10.18637/jss.v059.i10 is OK
- 10.21105/joss.01686 is OK
- 10.1007/s13187-020-01951-7 is OK
- 10.1101/2021.03.02.21252766 is OK
- 10.31234/osf.io/3vsxc is OK
- 10.2139/ssrn.3747263 is OK
- 10.1080/15230406.2013.777138 is OK
- 10.26833/ijeg.629381 is OK
- 10.1101/2021.06.02.21258249 is OK
- 10.32469/10355/81561 is OK
- 10.1201/b22052 is OK
- 10.1201/9780429200717 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
👋  @elbeejay - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @elbeejay as editor

**Comment by whedon** [comment]
@elbeejay has been invited to edit this submission.

**Comment by elbeejay** [comment]
@whedon assign @elbeejay as editor

**Comment by whedon** [comment]
OK, the editor is @elbeejay

**Comment by elbeejay** [comment]
Hi @jessecambon, thank you for submitting `tidygeocoder` to JOSS. Per the top post in this thread:

> if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

In the meantime I'll have a pre-review look through the repository to see if there are any changes that should be made prior to sending this out for review. 

Feel free to reach out with any questions.

-Jay

**Comment by jessecambon** [comment]
Thanks @elbeejay. Here are few potential reviewers (they have R listed as a primary language and spatial listed as a domain):

nickbearman ateucher yongzesong GISerDaishaoqing nuest giskid sjsrey

**Comment by elbeejay** [comment]
:wave: @nickbearman, @tsamsonov, @cole-brokamp, @GISerDaishaoqing would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The submission is "tidygeocoder: An R package for geocoding." I am reaching out to you all based on your experience with R and geospatial methods.

This is a pre-review issue which is used to find reviewers. Once 3 reviewers have been found I'll start the review on a dedicated GitHub issue. At present we are asking reviewers to complete reviews in 6 weeks, although this can be extended if needed. If you are not able to review and have someone to recommend, please mention them here (in this case please mention their GitHub handle without the "@" symbol).

If you are interested in reviewing, I would recommend looking over the journal's [conflict of interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html?#joss-conflict-of-interest-policy) before the review process starts.

Thank you, feel free to reach out if you have any questions about the JOSS review process. Please do not feel any pressure to accept this review request if you do not have the time or do not feel comfortable reviewing this software package, we appreciate and respect our peer-reviewers' time.

-Jay

**Comment by cole-brokamp** [comment]
I am willing to review this submission, thanks.

**Comment by tsamsonov** [comment]
Thanks for invitation! The topic is interesting, and I would be glad to review the paper.

**Comment by elbeejay** [comment]
Thank you both, we will begin the review now.

**Comment by elbeejay** [comment]
@whedon add @cole-brokamp as reviewer

**Comment by whedon** [comment]
OK, @cole-brokamp is now a reviewer

**Comment by elbeejay** [comment]
@whedon add @tsamsonov as reviewer

**Comment by whedon** [comment]
OK, @tsamsonov is now a reviewer

**Comment by elbeejay** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3544.
