### ISSUE TITLE
[PRE REVIEW]: sorn: A Python package for Self Organizing Recurrent Neural Network

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3536]
**Submitting author:** @saran-nns (<a href="http://orcid.org/0000-0002-7314-0261">Saranraj Nambusubramaniyan</a>)
**Repository:** <a href="https://github.com/Saran-nns/sorn/" target ="_blank">https://github.com/Saran-nns/sorn/</a>
**Version:** 0.4.9
**Editor:** @rkurchin
**Reviewers:** @janfreyberg, @janfb
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/7dc447f7a0d17d774b59c8ee15c223c2/status.svg)](https://joss.theoj.org/papers/7dc447f7a0d17d774b59c8ee15c223c2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/7dc447f7a0d17d774b59c8ee15c223c2"><img src="https://joss.theoj.org/papers/7dc447f7a0d17d774b59c8ee15c223c2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/7dc447f7a0d17d774b59c8ee15c223c2/status.svg)](https://joss.theoj.org/papers/7dc447f7a0d17d774b59c8ee15c223c2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @saran-nns. **Currently, there isn't an JOSS editor assigned** to your paper.

@saran-nns if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1639

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.18 s (386.8 files/s, 167719.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      14           2289           2323           8445
HTML                            15           2375             42           4927
SVG                              1              0              0           2671
Python                           8           1087            981           2148
CSS                              6            183             43            725
Markdown                         3            173              0            393
reStructuredText                11            115             81            231
TeX                              1              4              0             53
YAML                             5             17             24             47
INI                              1             11              0             27
DOS Batch                        1              8              1             26
make                             1              4              7              9
Dockerfile                       1              5              6              6
-------------------------------------------------------------------------------
SUM:                            68           6271           3508          19708
-------------------------------------------------------------------------------


Statistical information for the repository '8f697d6ef64a9b5981e1fca8' was
gathered on 2021/07/25.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Saran-nns                       70         19862           4382           72.44
Saranraj Nambusubram            17          3533            210           11.18
saran_nns                        6          2694           2788           16.38

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Saran-nns                 17744           89.3          5.3               15.63
Saranraj Nambusubram        965           27.3          0.6               11.40
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1371/journal.pcbi.1002848 may be a valid DOI for title: Network self-organization explains the statistics and dynamics of synaptic connection strengths in cortex
- 10.1371/journal.pone.0178683 may be a valid DOI for title: Criticality meets learning: Criticality signatures in a self-organizing recurrent neural network

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03536/joss.03536/10.21105.joss.03536.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03536/joss.03536/10.21105.joss.03536.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @Saran-nns - please add an explicit Statement of Need section to your paper.  In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
Also, I see some possible grammar problems in the paper - you might want to run it through a grammar checker

**Comment by danielskatz** [comment]
👋 @rkurchin - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @rkurchin as editor

**Comment by whedon** [comment]
@rkurchin has been invited to edit this submission.

**Comment by Saran-nns** [comment]
@whedon check references

**Comment by rkurchin** [comment]
@whedon assign me as editor

Hi Daniel, sure, I can take this one!

**Comment by whedon** [comment]
OK, the editor is @rkurchin

**Comment by rkurchin** [comment]
Hi @Saran-nns, I'll be editing this submission. Could you kindly take a look at [this list](https://bit.ly/joss-reviewers) of JOSS reviewers and identify a few that you think might be appropriate? Thanks!

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1371/journal.pcbi.1002848 is OK
- 10.1371/journal.pone.0178683 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Saran-nns** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03536/joss.03536/10.21105.joss.03536.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03536/joss.03536/10.21105.joss.03536.pdf) :page_facing_up: :point_left:

**Comment by Saran-nns** [comment]
Hi @rkurchin, thank you. I suggest, @rougier  @KirstensGitHub @mvandam @janfb @agricolab @AlexChristensen

**Comment by rkurchin** [comment]
Thanks! @KirstensGitHub and @agricolab, would you be willing to review this submission to JOSS?

We carry out our checklist-driven reviews here in GitHub issues according to these guidelines. You can find out more about this submission in the first comment in this issue.

**Comment by agricolab** [comment]
Dear @rkurchin and dear authors. Thanks for the invitation to review. I would be delighted to review, but currently have to decline due to time constraints.

**Comment by rkurchin** [comment]
Hi @AlexChristensen, would you be willing to review this submission to JOSS?

JOSS publishes articles about open source research software. It is a free, open-source, community driven and developer-friendly online journal (no publisher is seeking to raise revenue from the volunteer labor of researchers!). The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged.

JOSS reviews involve downloading and installing the software, and inspecting the repository and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html. Editors and reviewers post comments on the Review issue (this is the "pre-review" issue), and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to satisfy the review).

**Comment by AlexChristensen** [comment]
Hi @rkurchin,

Although I am familiar with neural networks, I do not feel I have the expertise to sufficiently evaluate the Python code. My experience is in the application of Python functions, but I have little experience writing Python code. 

I appreciate the invitation and look forward to seeing @Saran-nns's result.

**Comment by rkurchin** [comment]
Hi @janfreyberg, would you be willing to review this submission to JOSS?

JOSS publishes articles about open source research software. It is a free, open-source, community driven and developer-friendly online journal (no publisher is seeking to raise revenue from the volunteer labor of researchers!). The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged.

JOSS reviews involve downloading and installing the software, and inspecting the repository and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html. Editors and reviewers post comments on the Review issue (this is the "pre-review" issue), and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to satisfy the review).

**Comment by janfreyberg** [comment]
Hi @rkurchin, I'd be glad to, looking forward to it

**Comment by rkurchin** [comment]
Hi @janfb, would you be willing to review this submission to JOSS?

JOSS publishes articles about open source research software. It is a free, open-source, community driven and developer-friendly online journal (no publisher is seeking to raise revenue from the volunteer labor of researchers!). The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged.

JOSS reviews involve downloading and installing the software, and inspecting the repository and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html. Editors and reviewers post comments on the Review issue (this is the "pre-review" issue), and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to satisfy the review).

**Comment by janfb** [comment]
Hi @rkurchin yes I'd be happy to review

**Comment by rkurchin** [comment]
@whedon assign @janfb as reviewer

**Comment by whedon** [comment]
OK, @janfb is now a reviewer

**Comment by rkurchin** [comment]
@whedon assign @janfreyberg as reviewer

**Comment by whedon** [comment]
OK, @janfreyberg is now a reviewer

**Comment by rkurchin** [comment]
@whedon add @janfb as reviewer

**Comment by whedon** [comment]
OK, @janfb is now a reviewer

**Comment by rkurchin** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3545.
