### ISSUE TITLE
[REVIEW]: Bruker2nifti: Magnetic Resonance Images converter from Bruker ParaVision to Nifti format

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#354]
**Submitting author:** @SebastianoF (<a href="http://orcid.org/0000-0001-9279-4765">Sebastiano Ferraris</a>)
**Repository:** <a href="https://github.com/SebastianoF/bruker2nifti" target ="_blank">https://github.com/SebastianoF/bruker2nifti</a>
**Version:** 1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @rougier
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.846814" target="_blank">10.5281/zenodo.846814</a>

## Status

[![status](http://joss.theoj.org/papers/2ee6a3a3b1a4d8df1633f601bf2b0ffe/status.svg)](http://joss.theoj.org/papers/2ee6a3a3b1a4d8df1633f601bf2b0ffe)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2ee6a3a3b1a4d8df1633f601bf2b0ffe"><img src="http://joss.theoj.org/papers/2ee6a3a3b1a4d8df1633f601bf2b0ffe/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2ee6a3a3b1a4d8df1633f601bf2b0ffe/status.svg)](http://joss.theoj.org/papers/2ee6a3a3b1a4d8df1633f601bf2b0ffe)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/SebastianoF/bruker2nifti" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@rougier, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @Kevin-Mattheus-Moerman know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/SebastianoF/bruker2nifti">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [x] **Authorship:** Has the submitting author (@SebastianoF) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @rougier it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
:wave: @SebastianoF @rougier @dzhoshkun @neurolabusc @effigies the review is happening here!

**Comment by Kevin-Mattheus-Moerman** [comment]
@rougier you are officially assigned and can tick the boxes at the top of this review issue. However others are invited to review the same aspects and leave comments here as well. Thanks!

**Comment by dzhoshkun** [comment]
@Kevin-Mattheus-Moerman Thanks! Looking forward to the feedback.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @rougier as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rougier

**Comment by rougier** [comment]
I've started the review and reported minor issues on the project repository. I think the submission is in good shape and I'm now waiting for author corrections before finishing the review.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @rougier!

**Comment by rougier** [comment]
I finished the review and @SebastianoF made all the changes, I think it can be accepted and is now ready for publication. See:

* https://github.com/SebastianoF/bruker2nifti/issues/17
* https://github.com/SebastianoF/bruker2nifti/issues/18
* https://github.com/SebastianoF/bruker2nifti/issues/20
* https://github.com/SebastianoF/bruker2nifti/issues/21
* https://github.com/SebastianoF/bruker2nifti/issues/22
* https://github.com/SebastianoF/bruker2nifti/issues/23
* https://github.com/SebastianoF/bruker2nifti/issues/24

One remaining question is the possibility to update the submission with version 1.0.1 that is Python 3 compatible. I think it would be better to publish this version (which is also back compatible with Python 2.7).

Last very minor point is the PDF output missing from the source repo but JOSS will recompile it anyway, no?

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @rougier. Are we good to tick the last box? @arfon can you answer the PDF query 

> Last very minor point is the PDF output missing from the source repo but JOSS will recompile it anyway, no?

**Comment by Kevin-Mattheus-Moerman** [comment]
@SebastianoF I've some minor editorial comments on your paper below. Feel free to disagree. 

I suggest you change
> usually entails the image conversion from the native 

to: 
> usually entails the conversion of image data from the native

I suggest you change:
> The Bruker ParaVision proprietary software is not currently providing the tools for the data conversion to a suitable open formats for research, such as nifti [@cox2004sort], for which most of the available tools for medical image analysis are implemented.

to:
> The proprietary Bruker ParaVision software currently does not provide the tools for conversion of the data to suitable and open formats for research, such as nifti [@cox2004sort], for which most of the available tools for medical image analysis are implemented. 

In the following the sentence does not read well and and use of capital letters seems odd:
> ... and to parse every Parameter Files of the Bruker ParaVision format into python dictionaries...

Should this instead become?:
> ... and to parse all parameter files for the Bruker ParaVision format into python dictionaries...

Could the following sentence: 
> Lastly it is meant to be a starting point where to integrate possible future variations in Bruker hardware and ParaVision software future releases. 

Be rephrased to something like:
> Lastly it is meant to be a starting point to integrate possible future variations in Bruker hardware and ParaVision software.

**Comment by SebastianoF** [comment]
@Kevin-Mattheus-Moerman thanks, it flows better now.

**Comment by Kevin-Mattheus-Moerman** [comment]
:rocket: Thanks. @SebastianoF and @rougier. 

@arfon all boxes are ticked, and we are happy to accept this submission. Over to you.

**Comment by arfon** [comment]
> Last very minor point is the PDF output missing from the source repo but JOSS will recompile it anyway, no?

Yep, I'll compile that shortly.

@SebastianoF - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by SebastianoF** [comment]
@arfon Hi, .zip uploaded to [https://zenodo.org/record/846814](https://zenodo.org/record/846814).
The DOI is [10.5281/zenodo.846814](https://zenodo.org/badge/DOI/10.5281/zenodo.846814.svg)
Thanks!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.846814 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.846814" target="_blank">10.5281/zenodo.846814</a> is the archive.

**Comment by arfon** [comment]
@rougier - many thanks for your review here and to @Kevin-Mattheus-Moerman for editing this submission ✨ 

@SebastianoF - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00354 ⚡️ 🚀 💥

**Comment by SebastianoF** [comment]
@Kevin-Mattheus-Moerman @rougier @arfon 🚀 🚀 🚀 Thanks everyone! Best review-experience ever. Code have improved dramatically and I have learned a lot! 
All the best

**Comment by Kevin-Mattheus-Moerman** [comment]
Fantastic, congratulations @SebastianoF :cake: ! Thanks @rougier :+1:

**Comment by dzhoshkun** [comment]
@Kevin-Mattheus-Moerman @rougier @arfon Many thanks for your efforts and esp. the useful feedback we've received as part of the review process. Cheers.
