### ISSUE TITLE
[REVIEW]: TidyTensor: Utilities for multidimensional arrays as named hierarchical structures

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3543]
**Submitting author:** @oneilsh (<a href="http://orcid.org/0000-0001-6220-7080">Shawn T. O&#39;Neil</a>)
**Repository:** <a href="https://github.com/oneilsh/tidytensor" target ="_blank">https://github.com/oneilsh/tidytensor</a>
**Version:** v1.0.0
**Editor:** @taless474
**Reviewer:** @nhejazi, @omid-s
**Archive:** <a href="https://doi.org/10.5281/zenodo.5555276" target="_blank">10.5281/zenodo.5555276</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb/status.svg)](https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb"><img src="https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb/status.svg)](https://joss.theoj.org/papers/07ef2e53d083c0eea30c0d08eef0f1cb)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/oneilsh/tidytensor" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nhejazi & @omid-s, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @taless474 know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/oneilsh/tidytensor">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@oneilsh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/oneilsh/tidytensor">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@oneilsh) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nhejazi, @omid-s it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 448

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.58 s (154.4 files/s, 68276.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            28            684             93          22340
JavaScript                       8           2155           1972           7201
R                               32            353           1415           1209
CSS                              5            107             52            471
SVG                              2              0              1            299
Markdown                         4             78              0            173
Rmd                              1            123            168            173
YAML                             6             16              6            116
XML                              1              0              0             87
TeX                              1              9              0             60
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            89           3525           3707          32130
-------------------------------------------------------------------------------


Statistical information for the repository 'd279adb08f7d1814ce53a323' was
gathered on 2021/07/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Shawn O'Neil                     3         22695              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Shawn O'Neil              11367           50.1          0.0               17.40
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.5334/jors.148 may be a valid DOI for title: xarray: ND labeled arrays and datasets in Python

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03543/joss.03543/10.21105.joss.03543.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03543/joss.03543/10.21105.joss.03543.pdf) :page_facing_up: :point_left:

**Comment by taless474** [comment]
@oneilsh Would you please add the missing DOI?
(There is a Reference check error two cells above)

**Comment by oneilsh** [comment]
@taless474 done :) (I think)

**Comment by taless474** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5334/jors.148 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by taless474** [comment]
@nhejazi , @omid-s  how is the review going?

**Comment by oneilsh** [comment]
Hi @taless474, quick question: I just noticed a couple of minor typos in the documentation. Should I fix them right away or not make any adjustments to the codebase while the review is ongoing?

**Comment by taless474** [comment]
Hi @oneilsh. Please go ahead and make a pull request, so the reviewers realize what the recent changes are if they were reviewing those parts.

**Comment by taless474** [comment]
@nhejazi, @omid-s How is the review going?

**Comment by omid-s** [comment]
Execute my belated reply, just saw the messages here :/. I will be done soon :)

**Comment by omid-s** [comment]
Hi @oneilsh, there are two license files, repo's [license](https://github.com/oneilsh/tidytensor/blob/master/LICENSE) link goes to a file with two lines that sets copy right to you, though I can see another "[license.md](https://github.com/oneilsh/tidytensor/blob/master/LICENSE.md)" that has a brief MIT Licence description, I was wondering which one are you planning to keep?

**Comment by oneilsh** [comment]
Hi @omid-s, I believe that's an artifact of R's restrictions on the LICENSE file not containing the actual text of the license, whereas LICENSE.md is used more commonly as an optional extra. This [gitlab issue](https://gitlab.com/gitlab-org/gitlab/-/issues/15053) describes some frustrations developers have had there with the duplicate. 

LICENSE + LICENSE.md is how [`usethis::use_mit_license()`](https://usethis.r-lib.org/reference/licenses.html) set it up. If you think I should remove the extra `LICENSE.md` I can do so, just let me know. Thanks!

**Comment by omid-s** [comment]
> Hi @omid-s, thank you for the thorough review! I've made a branch with the fixes, here's a quick link to the compiled paper: https://github.com/oneilsh/tidytensor/suites/3607702673/artifacts/87088522 If it looks good I will merge it in and close the issue.

It's all looking Great @oneilsh :) Thanks for the updates.

**Comment by nhejazi** [comment]
Hi @oneilsh, great work on `tidytensor`! My apologies for the delay in getting to this review. I've just gone through most of the package documentation and items in the review checklist. I opened two issues in the `tidytensor` repo as part of the review; happy to discuss their contents in those issues. I have a bit more work to do in going through the package functionality but expect to have the first pass of this review completed tomorrow.

**Comment by nhejazi** [comment]
I've completed my review and believe that the submission (both software and paper) meets all of the requirements, so I am recommending that this work be published in JOSS.

**Comment by oneilsh** [comment]
Thank you @nhejazi for the thorough review and suggestions for improvements!

**Comment by oneilsh** [comment]
@taless474 I am curious about continuing improvements to the package post-publication; is there any best practice I should follow when making updates? Is the JOSS publication tied to a particular version of the package perhaps, such that creating a new version for changes post-review would make it obvious that those updates weren't part of the review? (I'm thinking especially around continuing documentation improvements e.g. updates to README.md, which I wouldn't normally mint a new version number for, but could.)

**Comment by taless474** [comment]
@oneilsh, I apologize for my belated response. I am reviewing reviews and will comment as soon as possible.

**Comment by oneilsh** [comment]
Hi @taless474, just checking in to see how the review is going.

**Comment by kyleniemeyer** [comment]
OK, everything looks fine to me. @oneilsh, can you please do the following?

- [ ] confirm the final reviewed version number here
- [ ] archive your repository on Zenodo or Figshare and provide the DOI here

**Comment by oneilsh** [comment]
Ok, v1.0.0 created with minor doc improvements and DOI 10.5281/zenodo.5555276. Thank you again!

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5555276" target="_blank">10.5281/zenodo.5555276</a> is the archive.

**Comment by kyleniemeyer** [comment]
@whedon accept

**Comment by kyleniemeyer** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by kyleniemeyer** [comment]
Congratulations @oneilsh on your article's publication in JOSS!

Many thanks to @nhejazi and @omid-s for reviewing this submission, and @taless474 for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03543/status.svg)](https://doi.org/10.21105/joss.03543)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03543">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03543/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03543/status.svg
   :target: https://doi.org/10.21105/joss.03543
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03543/status.svg)](https://doi.org/10.21105/joss.03543)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
