### ISSUE TITLE
[REVIEW]: tidygeocoder: An R package for geocoding

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3544]
**Submitting author:** @jessecambon (<a href="http://orcid.org/0000-0001-6854-1514">Jesse Cambon</a>)
**Repository:** <a href="https://github.com/jessecambon/tidygeocoder" target ="_blank">https://github.com/jessecambon/tidygeocoder</a>
**Version:** v1.0.3
**Editor:** @elbeejay
**Reviewer:** @cole-brokamp, @tsamsonov
**Archive:** <a href="https://doi.org/10.5281/zenodo.4686074" target="_blank">10.5281/zenodo.4686074</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7/status.svg)](https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7"><img src="https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7/status.svg)](https://joss.theoj.org/papers/c3cf0ab0d656d6398ada74dea81c5fb7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jessecambon/tidygeocoder" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@cole-brokamp & @tsamsonov, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @elbeejay know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jessecambon/tidygeocoder">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jessecambon) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jessecambon/tidygeocoder">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@jessecambon) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] #3674
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cole-brokamp, @tsamsonov it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3544 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.29 s (624.5 files/s, 163244.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      24           3075           3499          14545
HTML                            31           1823            423           9689
R                               88           2076           2076           6389
CSS                              9            112             94            853
Rmd                              6            245            400            455
Markdown                         5             76              0            259
JSON                             2              1              0            173
YAML                             3             23              3            155
XML                              1              0              0             66
SVG                              9              0              1             19
-------------------------------------------------------------------------------
SUM:                           178           7431           6496          32603
-------------------------------------------------------------------------------


Statistical information for the repository 'b068bcfca21bdd1afd433314' was
gathered on 2021/07/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jesse Cambon                    12         67978          15249          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jesse Cambon              52377           77.0          1.8               17.35
```

**Comment by elbeejay** [comment]
@cole-brokamp and @tsamsonov thanks for agreeing to review this submission to JOSS. We are currently asking reviewers to try and complete their reviews in 6 weeks. 

The JOSS review process is entirely open and transparent, and takes place on GitHub. Review comments can be made as issues in the tidygeocoder repository, please link this review issue when doing so (paste `https://github.com/openjournals/joss-reviews/issues/3544` into the issue).

For reference, here are links to the JOSS documentation that may be helpful as you conduct your reviews:
- [JOSS Review Criteria](https://joss.readthedocs.io/en/latest/review_criteria.html)
- [JOSS Review Checklist](https://joss.readthedocs.io/en/latest/review_checklist.html)

Please feel free to ping me (@elbeejay) if you have any questions/concerns. Thanks again for agreeing to review for JOSS.

**Comment by elbeejay** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03544/joss.03544/10.21105.joss.03544.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03544/joss.03544/10.21105.joss.03544.pdf) :page_facing_up: :point_left:

**Comment by elbeejay** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4686074 is OK
- 10.18637/jss.v059.i10 is OK
- 10.21105/joss.01686 is OK
- 10.1007/s13187-020-01951-7 is OK
- 10.1101/2021.03.02.21252766 is OK
- 10.31234/osf.io/3vsxc is OK
- 10.2139/ssrn.3747263 is OK
- 10.1080/15230406.2013.777138 is OK
- 10.26833/ijeg.629381 is OK
- 10.1101/2021.06.02.21258249 is OK
- 10.32469/10355/81561 is OK
- 10.1201/b22052 is OK
- 10.1201/9780429200717 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by elbeejay** [comment]
:wave: @cole-brokamp @tsamsonov we are nearing the halfway point in the review process so I just wanted to check in with you both. 

Let me know if there are any questions about conducting a JOSS review and I'll do my best to provide clarification. Thanks again for agreeing to review for JOSS.

**Comment by cole-brokamp** [comment]
Hi @elbeejay, I've initiated my review.  These are two very minor changes that can hopefully be addressed easily.

**Comment by cole-brokamp** [comment]
I've completed my review.  As long as the markdown file in the repo makes it into the final PDF here, I am all good to go.  Thanks.

**Comment by elbeejay** [comment]
Great, thanks @cole-brokamp!

**Comment by elbeejay** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03544/joss.03544/10.21105.joss.03544.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03544/joss.03544/10.21105.joss.03544.pdf) :page_facing_up: :point_left:

**Comment by jessecambon** [comment]
We updated the paper to include a comparison to other R packages (state of the field).

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03544/joss.03544/10.21105.joss.03544.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03544/joss.03544/10.21105.joss.03544.pdf) :page_facing_up: :point_left:

**Comment by tsamsonov** [comment]
I've completed my review. Everything is good, I think.

All the best, Tim

**Comment by elbeejay** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by elbeejay** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4686074 is OK
- 10.18637/jss.v059.i10 is OK
- 10.21105/joss.01686 is OK
- 10.1007/s13187-020-01951-7 is OK
- 10.1101/2021.03.02.21252766 is OK
- 10.31234/osf.io/3vsxc is OK
- 10.2139/ssrn.3747263 is OK
- 10.1080/15230406.2013.777138 is OK
- 10.26833/ijeg.629381 is OK
- 10.1101/2021.06.02.21258249 is OK
- 10.32469/10355/81561 is OK
- 10.1201/b22052 is OK
- 10.1201/9780429200717 is OK

MISSING DOIs

- 10.32614/rj-2013-014 may be a valid DOI for title: ggmap: Spatial Visualization with ggplot2

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03544/joss.03544/10.21105.joss.03544.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03544/joss.03544/10.21105.joss.03544.pdf) :page_facing_up: :point_left:

**Comment by elbeejay** [comment]
Hi @jessecambon and coauthors, I'm pleased to see that the reviewers have completed their review of your package. I have a few minor clarifications and changes of my own to request. 

- As you can see in the reference check above, whedon has flagged the DOI for `ggmap` as missing. Please check that you are correctly citing that package. There appear to be multiple accepted ways of citing it: [method 1](https://journal.r-project.org/archive/2013/RJ-2013-014/index.html) and [method 2](https://cran.r-project.org/web/packages/ggmap/citation.html). I suggest using the method with the DOI suggested by whedon above.
- I noticed that the first sentence of the paper has a reference to a Zenodo archive of this software. Please remove this citation as the JOSS paper will serve as a connection to the published version of `tidygeocoder` and will include metadata and a link to a tagged version in Zenodo (more on this below).

Once you have made the above changes, there are just a few things I need from you to set the metadata and mark this as "ready for publication"; please:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

Given that the software (as far as I am aware) did not actually change as a part of this review, these steps may already be complete. I just ask that you double-check the metadata to ensure everything is correct, and then list the requested items here. I will then move forward with accepting the submission, thanks!

**Comment by jessecambon** [comment]
Hi @elbeejay, thanks. I've made those two changes and the Zenodo archive is here : https://zenodo.org/record/4686074#.YTdlIfxKiV5 (github release v1.0.3). I double checked Zenodo metadata and it is correct.

**Comment by elbeejay** [comment]
@whedon set 10.5281/zenodo.4686074 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4686074" target="_blank">10.5281/zenodo.4686074</a> is the archive.

**Comment by elbeejay** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by elbeejay** [comment]
@whedon check references from branch joss

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v059.i10 is OK
- 10.21105/joss.01686 is OK
- 10.1007/s13187-020-01951-7 is OK
- 10.1101/2021.03.02.21252766 is OK
- 10.31234/osf.io/3vsxc is OK
- 10.2139/ssrn.3747263 is OK
- 10.1080/15230406.2013.777138 is OK
- 10.26833/ijeg.629381 is OK
- 10.1101/2021.06.02.21258249 is OK
- 10.32469/10355/81561 is OK
- 10.1201/b22052 is OK
- 10.1201/9780429200717 is OK
- 10.32614/RJ-2013-014 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03544/joss.03544/10.21105.joss.03544.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03544/joss.03544/10.21105.joss.03544.pdf) :page_facing_up: :point_left:

**Comment by elbeejay** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3544 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by elbeejay** [comment]
@whedon recommend-accept from branch joss

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v059.i10 is OK
- 10.21105/joss.01686 is OK
- 10.1007/s13187-020-01951-7 is OK
- 10.1101/2021.03.02.21252766 is OK
- 10.31234/osf.io/3vsxc is OK
- 10.2139/ssrn.3747263 is OK
- 10.1080/15230406.2013.777138 is OK
- 10.26833/ijeg.629381 is OK
- 10.1101/2021.06.02.21258249 is OK
- 10.32469/10355/81561 is OK
- 10.1201/b22052 is OK
- 10.1201/9780429200717 is OK
- 10.32614/RJ-2013-014 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2571

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2571, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss 
```

**Comment by elbeejay** [comment]
@jessecambon and co-authors: I've recommended that your submission be accepted and published. Final steps will be handled by one of the EiCs. Many thanks to both @cole-brokamp and @tsamsonov for their reviews.

**Comment by arfon** [comment]
@whedon accept deposit=true from branch joss

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1435866535768301576) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2573
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03544](https://doi.org/10.21105/joss.03544)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@cole-brokamp, @tsamsonov  – many thanks for your reviews here and to @elbeejay  for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

Also, congratulations to @elbeejay on editing their first JOSS submission ✨ 

@jessecambon – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03544/status.svg)](https://doi.org/10.21105/joss.03544)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03544">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03544/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03544/status.svg
   :target: https://doi.org/10.21105/joss.03544
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03544/status.svg)](https://doi.org/10.21105/joss.03544)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
