### ISSUE TITLE
[REVIEW]: Reel1.0 - A visualization tool for evaluating powder diffraction refinements

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3546]
**Submitting author:** @fgjorup (<a href="http://orcid.org/0000-0003-3902-0247">Frederik Holm Gjørup</a>)
**Repository:** <a href="https://github.com/fgjorup/Reel/" target ="_blank">https://github.com/fgjorup/Reel/</a>
**Version:** v1.2.0
**Editor:** @rkurchin
**Reviewer:** @cmbiwer, @mikapfl
**Archive:** <a href="https://doi.org/10.6084/m9.figshare.16817929" target="_blank">10.6084/m9.figshare.16817929</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054/status.svg)](https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054"><img src="https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054/status.svg)](https://joss.theoj.org/papers/95de1942ca8f4bbf3c4fad168d641054)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fgjorup/Reel/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@cmbiwer & @mikapfl, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @rkurchin know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fgjorup/Reel/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fgjorup) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fgjorup/Reel/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fgjorup) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cmbiwer, @mikapfl it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.22 s (59.3 files/s, 31563.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            275            220           5642
Qt                               1              0              0            732
Markdown                         1             10              0             27
DOS Batch                        2              0              0             19
-------------------------------------------------------------------------------
SUM:                            13            285            220           6420
-------------------------------------------------------------------------------


Statistical information for the repository '7cb6826d67a65cd13483005c' was
gathered on 2021/07/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Frederik                         1             0           6702           14.27
Frederik Holm Gjørup            17         11786          13655           54.18
fgjorup                          6         14761             53           31.55

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Frederik Holm Gjørup       6137           52.1          1.5                2.70
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3546 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by mikapfl** [comment]
@fgjorup Could you describe how your co-authors contributed to the work? The git history doesn't show contributions from other people than you, but git histories of course only show one side of a larger work.

**Comment by rkurchin** [comment]
@whedon generate pdf from branch JOSS-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSS-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03546/joss.03546/10.21105.joss.03546.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03546/joss.03546/10.21105.joss.03546.pdf) :page_facing_up: :point_left:

**Comment by rkurchin** [comment]
@fgjorup, reminder to answer @mikapfl's question when you get a chance, as well as the issue he opened on your repository: https://github.com/fgjorup/Reel/issues/3

@cmbiwer, please reach out if you have any questions about getting your review started.

**Comment by fgjorup** [comment]
> @fgjorup Could you describe how your co-authors contributed to the work? The git history doesn't show contributions from other people than you, but git histories of course only show one side of a larger work.

@mikapfl of course. 

Professor Mogens Christensen is the supervisor of the project and has primarily contributed with scientific background, funding, and proof-reading of the paper. 

Mathias Mørch has taken part in designing the layout of the interface and has been the primary tester of the program. He has also taken part in defining the format of the _.xyy_ input files and has provided the test files available in the repository.

Naturally, the above contributions have not been logged by Github.

I hope that answers your question, otherwise I will gladly elaborate.

**Comment by fgjorup** [comment]
> @fgjorup, reminder to answer @mikapfl's question when you get a chance, as well as the issue he opened on your repository: [fgjorup/Reel#3](https://github.com/fgjorup/Reel/issues/3)
> 
> @cmbiwer, please reach out if you have any questions about getting your review started.

@rkurchin, sorry for the delay, I am finally back in the office from my vacation. Please let me know if there is anything else I need to address.

**Comment by rkurchin** [comment]
Thanks for checking in! I think you're all set, we're just waiting for @mikapfl and @cmbiwer to continue their reviews, so do be on the lookout for any further comments/questions from them either here or as issues/PR's in your repo.

**Comment by cmbiwer** [comment]
I will be take a deeper look this Friday.

**Comment by mikapfl** [comment]
@fgjorup Could you provide a set of example files which I could use to run the program? I unfortunately don't have a set of XRD data files which would lend itself to an analysis with Reel.

**Comment by fgjorup** [comment]
@mikapfl  There should already be a test_files folder in the Joss-submission repo, I hope those will do the trick.

**Comment by cmbiwer** [comment]
I have finished taking a look at the software and can type up the checklist and my comments about the functionality, documentation, paper, and software sometime this week.

Though, there were a few crashes/errors I encountered. Either myself or @mikapfl have already made issues on the GitHub repo. I'd suggest those are address (i.e. issues #4 and #6).

**Comment by rkurchin** [comment]
Hi all, I see some issues have been closed. @cmbiwer and @mikapfl, are those resolved to your satisfaction? Don't forget to progress through the reviewer checklists!

@fgjorup, there's at least one issue still open as of now.

**Comment by cmbiwer** [comment]
> ## Review checklist for @cmbiwer
> ### Conflict of interest
> * [X]  I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.
> 
> ### Code of Conduct
> * [X]  I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).
> 
> ### General checks
> * [X]  **Repository:** Is the source code for this software available at the [repository url](https://github.com/fgjorup/Reel/)?
> * [X]  **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
> * [X]  **Contribution and authorship:** Has the submitting author (@fgjorup) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
> * [X]  **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)
> 
> ### Functionality
> * [X]  **Installation:** Does installation proceed as outlined in the documentation?
> * [X]  **Functionality:** Have the functional claims of the software been confirmed?
> * [X]  **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
> 
> ### Documentation
> * [ ]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
> * [X]  **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
> * [ ]  **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
> * [X]  **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
> * [X]  **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
> * [ ]  **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
> 
> ### Software paper
> * [X]  **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
> * [ ]  **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
> * [ ]  **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
> * [X]  **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
> * [X]  **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

I've filled out the checklist above. Overall, I believe the software fills a need and it is easy to imagine the software to be useful to scientists. Several other projects have developed or are developing similar 2D heatmap visualizations in some fashion. So I would say the functionality is recognized as an important development by the community already. I liked the user interface to Reel and I would say the author has created a nice-looking software product. However, this project is still missing some key items that are explicitly outlined in the checklist. Notably, there is no no community guidelines and the paper could give a bit clearer picture of Reel to the reader.

There is no community guidelines for contribution. The lack of community guidelines and no documentation of the code itself or inline comments will probably not invite much open-source contributions.

I would say the JOSS paper manuscript itself doesn't give a non-familiar reader a clear image of what Reel does. I think the text in the summary is very nice. However, an image of the GUI (like in their documentation) would give a reader of the actual paper a much better idea what Reel is in its statement of need. There also isn't a discussion of example usage or what real problems could be solved (for example identifying where a phase change happens, etc.). The authors mention refinement programs but don't really state much about the current state of visualization in the field which is the intent of Reel.

The instructions do show the users to manually load up the software and verify its functionality, so it does meet the JOSS requirements. However, there were a number of issues already and perhaps some kind of automated testing would be beneficial to maintaining this project.

I'd say Reel is a nice program, but its still missing some of the review checklist items. The author has already address several issues in the repo, perhaps they could address these final missing items as well.

**Comment by fgjorup** [comment]
Hi @rkurchin  and @cmbiwer
I have added a line about contact on contribution in the README.md, I hope that satisfies the requirements.

Regarding the manuscript, I would be happy to include an image of the GUI, perhaps with a comparison to other common visualization tools in the community. I will also expand a bit on the statement of need, how I expect the community to use the software, and how it compares to what is already available.

Should I already now revise the manuscript, or should I wait for feedback from @mikapfl ?

**Comment by rkurchin** [comment]
Up to you! @mikapfl, I think it would be useful for @fgjorup to have some of your feedback as well, here...any thoughts?

**Comment by mikapfl** [comment]
Hi,

regarding the manuscript, I think the summary is already good and for me there is no need to replicate things already found in the docs. However, if I understand correctly, Reel is rather one building block in a "pipeline" - while it is possible to view raw measurements, it really shines when viewing refinement results. In the docs, there is a list of supported file formats, maybe you could explain in the paper the ecosystem more, in particular which refinement software is "supported" by Reel and which hole Reel fills in the whole pipeline.

I will write a bit more regarding the other (non-paper) parts of the checklist and/or open more issues later.

Cheers,

Mika

**Comment by mikapfl** [comment]
Regarding your changes in the `JOSS-submission` branch, do you intend to merge this into master? At the moment, people just landing on Reel's github presence don't get the various enhancements you already implemented.

**Comment by mikapfl** [comment]
Hi,

I've updated my checklist and reported some installation problems that should be rather straight-forward to fix.

I think Reel 1.0 is a fairly intuitively usable software which can be useful for analysis of preliminary results at the beamline as well as later on in the refinement process. However, I think to make Reel a solid foundation for future updates and maintenance, it needs automated tests. I don't agree with @cmbiwer that the instructions provided in the documentation fulfil the criteria for either automated tests or even clearly described steps for manual testing. A key functionality of Reel is that, according to the documentation, it is possible to analyse data supplied in 6 different formats, but at the moment, only the Reel custom format can be tested using the given instructions and data. Even there, expected test results are not clearly defined, so that more subtle errors can't be detected. As proper reading of file formats is often a source of errors, but also crucial for users, I think that testing should be done (preferably automatically) using all supported file formats. This is even possible with standard python tools for unit testing by testing the reading functions directly, so that more advanced testing tools for graphical user interfaces are not necessary.

Additionally, either automated tests or clear descriptions how to perform manual tests should be provided for testing Reel in a defined python environment. Some libraries Reel uses are under quite active development, and issues like https://github.com/fgjorup/Reel/issues/11 can be caught and fixed in time using testing strategies with clearly defined python environments.

Cheers,

Mika

**Comment by rkurchin** [comment]
👋 @fgjorup, reminder to respond to these when you have some time!

**Comment by fgjorup** [comment]
I will be out of country most of next week, but I will try to find some spare time to look at it!

**Comment by rkurchin** [comment]
@fgjorup, hope you had a nice trip. Here's a little reminder to respond to the comments above! :)

**Comment by fgjorup** [comment]
Thank you @rkurchin , we had a very productive trip to Sweden, where we managed to do some very exciting science at the new DanMAX beamline.

Inspired by both @cmbiwer  and @mikapfl, I have updated the paper.md, so it now includes a figure of the interface, a flowchart-figure, and a figure comparing other visualization option in the field. I have also expanded on the _Statement of Need_ and added a _Statement of Field_.

I will try to get around to addressing the remaining issues and look in to testing, as @mikapfl points out.

**Comment by rkurchin** [comment]
Thanks @mikapfl for your thorough and thoughtful review! Just to explicitly confirm, are you now happy to accept this submission as it currently stands?

@cmbiwer, how are things looking on your end?

**Comment by mikapfl** [comment]
> Thanks @mikapfl for your thorough and thoughtful review! Just to explicitly confirm, are you now happy to accept this submission as it currently stands?

yes

**Comment by rkurchin** [comment]
@whedon check references

**Comment by fgjorup** [comment]
Great news @rkurchin ! My colleague, @moerch, should have taken care of the "editorial feedback", so the manuscript should be ready. Regarding merging, which makes the most sense? I would like the archived and tagged release to include the changes in the JOSS branch, so would you prefer I merged the branch before acceptance?

**Comment by fgjorup** [comment]
@whedon generate pdf from branch JOSS-submission

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03546/joss.03546/10.21105.joss.03546.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03546/joss.03546/10.21105.joss.03546.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
OK. v1.2.0 is the version.

**Comment by rkurchin** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1107/S1600576718000183 is OK
- 10.1016/0921-4526(93)90108-I is OK
- 10.1524/9783486992540-020 is OK
- 10.1371/journal.pone.0199239 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1449283419406577667) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2688
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03546](https://doi.org/10.21105/joss.03546)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@cmbiwer, @mikapfl – many thanks for your reviews here and to @rkurchin for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@fgjorup – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03546/status.svg)](https://doi.org/10.21105/joss.03546)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03546">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03546/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03546/status.svg
   :target: https://doi.org/10.21105/joss.03546
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03546/status.svg)](https://doi.org/10.21105/joss.03546)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
