### ISSUE TITLE
[PRE REVIEW]: bmm: Bayesian Map-matching

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3548]
**Submitting author:** @SamDuffield (<a href="http://orcid.org/0000-0002-8656-8734">Samuel Duffield</a>)
**Repository:** <a href="https://github.com/SamDuffield/bmm" target ="_blank">https://github.com/SamDuffield/bmm</a>
**Version:** v1.1
**Editor:** @taless474
**Reviewers:** @georgiastuart, @matt-graham
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/59abd48ba401a3256f38e635bebd3a64/status.svg)](https://joss.theoj.org/papers/59abd48ba401a3256f38e635bebd3a64)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/59abd48ba401a3256f38e635bebd3a64"><img src="https://joss.theoj.org/papers/59abd48ba401a3256f38e635bebd3a64/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/59abd48ba401a3256f38e635bebd3a64/status.svg)](https://joss.theoj.org/papers/59abd48ba401a3256f38e635bebd3a64)
```

**Author instructions**

Thanks for submitting your paper to JOSS @SamDuffield. **Currently, there isn't an JOSS editor assigned** to your paper.

@SamDuffield if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 344

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.16 s (30.9 files/s, 156155.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              0         176329
Python                          25            944           1137           2831
TeX                              1             26              0            185
Markdown                         2             26              0             88
reStructuredText                 4             49             28             55
DOS Batch                        1              8              1             26
YAML                             1              4              7             11
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            36           1061           1180         179534
-------------------------------------------------------------------------------


Statistical information for the repository '51c42ec1184ce2b457202735' was
gathered on 2021/07/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Sam Duffield                    95         15624          13211           71.19
SamDuffield                     59          7081           4591           28.81

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Sam Duffield               4912           31.4         11.5                9.83
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK
- 10.5281/zenodo.3946761 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/TITS.2013.2262376 is OK
- 10.1080/13658816.2017.1400548 is OK
- 10.1145/2093973.2094062 is OK
- 10.1145/1653771.1653818 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.compenvurbsys.2017.05.004 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03548/joss.03548/10.21105.joss.03548.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03548/joss.03548/10.21105.joss.03548.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @SamDuffield, thanks for your interest in JOSS. We don't have any editors in this area with availability right now, so your submission will be placed in our waitlist until someone opens up.

In the meantime, your article is *extremely* short. Although JOSS articles are indeed short, we typically expect 250-1000 words—I would not usually count the Acknowledgments section, which is around the same length as the main content of your article. 

Actually, it looks like some of what is in that section should actually belong in the main part of the article, since it is describing dependencies and things that your software is built on. Could you perhaps move that content (and anything else along those lines) to the main text? I think you could also explain how the software works in a bit more detail.

**Comment by SamDuffield** [comment]
Hi @kyleniemeyer! Thanks for your comments - I have moved the dependencies into the summary and extended the paper to properly describe the core functionality of the package.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03548/joss.03548/10.21105.joss.03548.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03548/joss.03548/10.21105.joss.03548.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK
- 10.5281/zenodo.3946761 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/TITS.2013.2262376 is OK
- 10.1080/13658816.2017.1400548 is OK
- 10.1145/2093973.2094062 is OK
- 10.1145/1653771.1653818 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.compenvurbsys.2017.05.004 is INVALID because of 'https://doi.org/' prefix
```

**Comment by kyleniemeyer** [comment]
Thanks @SamDuffield! One more minor thing: it looks like one of your DOIs has the prefix in the `doi` field, could you fix that?

**Comment by SamDuffield** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- doi.org/10.1016/j.compenvurbsys.2017.05.004 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5281/zenodo.3509134 is OK
- 10.5281/zenodo.3946761 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/TITS.2013.2262376 is OK
- 10.1080/13658816.2017.1400548 is OK
- 10.1145/2093973.2094062 is OK
- 10.1145/1653771.1653818 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by SamDuffield** [comment]
@kyleniemeyer looks ok now!

**Comment by taless474** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by taless474** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @taless474

**Comment by taless474** [comment]
@kaheetonaa, @nickbearman, @1tylermitchell will you be able to review this?

**Comment by taless474** [comment]
@bitasd will you be able to review this?

**Comment by nickbearman** [comment]
Hi @taless474 no, sorry I can't review this as I can't review Python at the moment. Can you update my details to reflect this (i.e. remove Python) or let me know how to do that? Thanks.

**Comment by taless474** [comment]
@nickbearman, of course :+1
Thank you

**Comment by 1tylermitchell** [comment]
@taless474 I cannot do a review at the moment. I should also be tutored through the experience for the first time I think :)

**Comment by taless474** [comment]
@kbevers, @alesarrett will you be able to review this?

**Comment by kbevers** [comment]
@taless474 Sorry, this seems to be out of my area of expertise.

**Comment by alesarrett** [comment]
> @kbevers, @alesarrett will you be able to review this?
I'm sorry but I don't feel able to review it.

**Comment by taless474** [comment]
@SamDuffield Could you please suggest some reviewers to us?
Also, I believe a simple informal abstract might help here. I read the paper and, my understanding differs from what I get from the Bayesian Map-matching title.

**Comment by SamDuffield** [comment]
possibly tsamsonov, georgiastuart or matt-graham?

@taless474 where should I write the abstract?

**Comment by taless474** [comment]
@tsamsonov, @georgiastuart will you be able to review this?

**Comment by taless474** [comment]
> @taless474 where should I write the abstract?
I would appreciate a paragraph here.
Thank you

**Comment by georgiastuart** [comment]
Sure, I glanced at the repo and docs really quickly and it looks like I have the knowledge to evaluate it.

**Comment by taless474** [comment]
@whedon assign @georgiastuart as reviewer

**Comment by whedon** [comment]
OK, @georgiastuart is now a reviewer

**Comment by taless474** [comment]
@matt-graham will you be able to review this?

**Comment by matt-graham** [comment]
Yes I would be happy to review this.

**Comment by SamDuffield** [comment]
**Abstract**

`bmm`: Bayesian Map-matching

Map-matching is defined as the task of converting an ordered series of noisy, unconstrained GPS coordinates into a series of connected edges that represent the route taken constrained to a predefined road network. `bmm` represents a Python package for map-matching in dense, urban networks that combines a Bayesian state-space model with particle smoothing (or sequential Monte Carlo) to provide map-matching inference with uncertainty quantification in both offline and online settings.

**Comment by taless474** [comment]
@whedon add @matt-graham as reviewer

**Comment by whedon** [comment]
OK, @matt-graham is now a reviewer

**Comment by taless474** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3651.
