### ISSUE TITLE
[PRE REVIEW]: cerf: A Python package to evaluate the feasibility and costs of power plant siting for alternate futures

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3549]
**Submitting author:** @crvernon (<a href="http://orcid.org/0000-0002-3406-6214">Chris Vernon</a>)
**Repository:** <a href="https://github.com/IMMM-SFA/cerf" target ="_blank">https://github.com/IMMM-SFA/cerf</a>
**Version:** v2.0.0
**Editor:** @fraukewiese
**Reviewers:** @lisazeyen , @willu47 
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/28fee3407bbbef020fb4bb19bd451407/status.svg)](https://joss.theoj.org/papers/28fee3407bbbef020fb4bb19bd451407)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/28fee3407bbbef020fb4bb19bd451407"><img src="https://joss.theoj.org/papers/28fee3407bbbef020fb4bb19bd451407/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/28fee3407bbbef020fb4bb19bd451407/status.svg)](https://joss.theoj.org/papers/28fee3407bbbef020fb4bb19bd451407)
```

**Author instructions**

Thanks for submitting your paper to JOSS @crvernon. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @timtroendle.

@crvernon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1163

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41560-020-00686-5 is OK
- 10.1016/j.rser.2018.09.022 is OK
- 10.1016/j.techfore.2013.08.025 is OK
- 10.1038/s41467-021-21785-1 is OK
- 10.1016/j.gloenvcha.2015.09.019 is OK
- 10.5334/jors.227 is OK
- 10.1007/s10584-012-0618-y is OK
- 10.1016/j.esr.2019.100411 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.1038/s41467-018-08275-7 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.apenergy.2019.114267 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (603.4 files/s, 122323.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                            10            157             24           5908
Python                          23           1004            902           1495
SVG                              4              4              4            298
reStructuredText                10            311            503            246
CSS                              2             54             11            244
TeX                              1             11              0            133
Markdown                         2             29              0             78
XML                              3              0              0             50
DOS Batch                        1              8              1             26
Jupyter Notebook                 1              0            221             15
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            58           1582           1673           8502
-------------------------------------------------------------------------------


Statistical information for the repository 'b88375c28a20e3a69f3505be' was
gathered on 2021/07/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Chris Vernon                     3           490             14            0.63
Nino Zuljevic                    1          3276              2            4.10
Vernon                           7           437             62            0.62
Vernon, Chris R                  9           673            199            1.09
crvernon                       149         36821          38019           93.56

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vernon                        2            0.5         40.4                0.00
crvernon                   3399            9.2          4.3               15.77
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03549/joss.03549/10.21105.joss.03549.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03549/joss.03549/10.21105.joss.03549.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @crvernon, thanks for your submission to JOSS! We do not have an editor available in this area right now, so I'm going to put your submission on our waitlist until someone opens up.

In the meantime, could you resolve that DOI error mentioned above?

**Comment by kyleniemeyer** [comment]
@whedon invite @fraukewiese as editor

Hi @fraukewiese, I think you are still out for a few more days, but this looks like it might be a good submission for you!

**Comment by whedon** [comment]
@fraukewiese has been invited to edit this submission.

**Comment by crvernon** [comment]
No problem @kyleniemeyer I'll fix the DOI in the morning.  Here are a few suggestions for reviewers from the JOSS list (not tagged):  `willu47`, `fwitte`, and `milicag`

Thanks!

**Comment by crvernon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by crvernon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03549/joss.03549/10.21105.joss.03549.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03549/joss.03549/10.21105.joss.03549.pdf) :page_facing_up: :point_left:

**Comment by crvernon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41560-020-00686-5 is OK
- 10.1016/j.rser.2018.09.022 is OK
- 10.1016/j.techfore.2013.08.025 is OK
- 10.1038/s41467-021-21785-1 is OK
- 10.1016/j.gloenvcha.2015.09.019 is OK
- 10.5334/jors.227 is OK
- 10.1007/s10584-012-0618-y is OK
- 10.1016/j.esr.2019.100411 is OK
-  10.25080/Majora-92bf1922-00a  is OK
- 10.1038/s41467-018-08275-7 is OK
- 10.1016/j.apenergy.2019.114267 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by crvernon** [comment]
@kyleniemeyer @fraukewiese the invalid DOI has now been repaired.  Thanks!

**Comment by fraukewiese** [comment]
Yes I can edit this paper.

**Comment by fraukewiese** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @fraukewiese

**Comment by fraukewiese** [comment]
@lisazeyen, @willu47, @fwitte
– would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: [https://joss.readthedocs.io/en/latest/reviewer_guidelines.html](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

The submission under review here is [cerf: A Python package to evaluate the feasibility and costs of power plant siting for alternate futures](https://github.com/IMMM-SFA/cerf)

**Comment by fwitte** [comment]
Hi @fraukewiese,
I will have a look at the submission and give you a feedback at the end of this week as I am out of office currently.
Best regards

**Comment by lisazeyen** [comment]
Hey @fraukewiese ,
I can have a look at the submission at end of this week as well if you need another reviewer. 
Best,

**Comment by fraukewiese** [comment]
Great, thanks a lot @lisazeyen . Yes, we need two reviewers for the paper. So I will start the review as soon as we have two reviewers signed up. I will wait for the response from @fwitte end of this week if he can can review this submission.

**Comment by fraukewiese** [comment]
@fwitte : Did you find the chance to have a look whether you could be a reviewer for this submission?

**Comment by fwitte** [comment]
Hi @fraukewiese,
I have some experience in this field, but am much more focused on the engineering thermodynamics and economics of individual power plants. Therefore, I feel, that I would not be an adequate reviewer for this publication. I suggest you reach out to e.g. `@simnh` as potential reviewer instead, as he did somewhat related research in the German/European power system. He might be interested even though he is not (yet) on the list of potential reviewers. But thank you for reaching out.
Have a nice day

**Comment by fraukewiese** [comment]
Thanks @fwitte

**Comment by fraukewiese** [comment]
@willu47 : Did you find the chance to have a look whether you could be a reviewer for this submission to JOSS?

We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is cerf: A Python package to evaluate the feasibility and costs of power plant siting for alternate futures

**Comment by willu47** [comment]
@fraukewiese 👍🏻 - yes, I am able to perform this review and I am a suitable reviewer - researching spatial electrification pathways, energy-water nexus and multi-scale modelling.

If you need other reviewers, I would recommend any of the following: czor847, ElcoK, tomalrussell (untagged)

**Comment by fraukewiese** [comment]
@whedon add @lisazeyen  as reviewer

**Comment by whedon** [comment]
OK, @lisazeyen  is now a reviewer

**Comment by fraukewiese** [comment]
@whedon add @willu47  as reviewer

**Comment by whedon** [comment]
OK, @willu47  is now a reviewer

**Comment by fraukewiese** [comment]
@willu47 Thank you very much for your suggestions. You are two reviewer, so that is fine for now. So I might come back to your suggestions in case we need more reviewers, but start the review with the two of you now.

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3601.

**Comment by fraukewiese** [comment]
@lisazeyen , @willu47  – thanks a lot for agreeing to review here! See you over in #3601 where the actual review will take place.
