### ISSUE TITLE
[REVIEW]: visdat: Visualising Whole Data Frames

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#355]
**Submitting author:** @njtierney (<a href="http://orcid.org/0000-0003-1460-8722">Nicholas John Tierney</a>)
**Repository:** <a href="https://github.com/ropensci/visdat" target ="_blank">https://github.com/ropensci/visdat</a>
**Version:** v0.2.0
**Editor:** @arfon
**Reviewer:** @arfon
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.845960" target="_blank">10.5281/zenodo.845960</a>

## Status

[![status](http://joss.theoj.org/papers/c85f57adbc565b064fb4bfc9b59a1b2a/status.svg)](http://joss.theoj.org/papers/c85f57adbc565b064fb4bfc9b59a1b2a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c85f57adbc565b064fb4bfc9b59a1b2a"><img src="http://joss.theoj.org/papers/c85f57adbc565b064fb4bfc9b59a1b2a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c85f57adbc565b064fb4bfc9b59a1b2a/status.svg)](http://joss.theoj.org/papers/c85f57adbc565b064fb4bfc9b59a1b2a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ropensci/visdat" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@arfon, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ropensci/visdat">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.0)?
- [x] **Authorship:** Has the submitting author (@njtierney) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
Hi @njtierney, many thanks for your submission. This should be quick as you've already been through the rOpenSci process.

A couple of issues with your submission `paper.md`:

It looks like you've got a couple of different paper files, `paper.Rmd` and `paper.md`. We need the file to be named `paper.md` and for the YAML header to be formatted correctly as per [this example](https://github.com/arfon/fidgit/blob/master/paper/paper.md).

In addition, the markdown citations don't seem to be being picked up correctly (see the pandoc errors below)

```
pandoc-citeproc: reference dplyr not found
pandoc-citeproc: reference Rcore not found
pandoc-citeproc: reference ggplot2 not found
```

Finally, the current paper reads a little too much like technical documentation (i.e. naming methods etc) which is not the purpose of the JOSS paper (this material should be in the technical documentation). Please take a look at [this guidance](https://github.com/openjournals/joss/blob/487e1fe646ff0deb5a7f3b1649c3456ef0eafa64/app/views/home/about.html.erb#L73-L77) as to what your paper should contain 😄

**Comment by njtierney** [comment]
Hi @arfon !

OK sure thing, I'm reviewing these changes at the moment and will have something to you at the end of next week at the latest.

Question - is it OK if I use `paper.Rmd` (to generate a figure), which will generate `paper.md`, and then I edit that as per the guidelines?

Cheers! :)

**Comment by arfon** [comment]
> Question - is it OK if I use `paper.Rmd` (to generate a figure), which will generate `paper.md`, and then I edit that as per the guidelines?

I think that should be OK. Our automated submission tooling will pick up any file named `paper.md` so just make sure that is the one that has the JOSS paper in.

**Comment by njtierney** [comment]
Hi @arfon !

I've submitted the changes for the [paper.md](https://github.com/ropensci/visdat/blob/master/paper/paper.md) - do you still get the same pandoc citation errors?

**Comment by arfon** [comment]
> I've submitted the changes for the paper.md - do you still get the same pandoc citation errors?

It looks good now, thanks!

At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by njtierney** [comment]
Yup!

Here is the DOI link: https://zenodo.org/badge/latestdoi/50553382

And the release: https://github.com/ropensci/visdat/releases/tag/v0.2.1

Is that the info that you need?

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.845960 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.845960" target="_blank">10.5281/zenodo.845960</a> is the archive.

**Comment by arfon** [comment]
@njtierney - your paper is now accepted into JOSS. Your DOI is http://dx.doi.org/10.21105/joss.00355 ⚡️ 🚀 💥
