### ISSUE TITLE
[PRE REVIEW]: TraViA: a Traffic data Visualization and Annotation tool in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3550]
**Submitting author:** @OlgerSiebinga (<a href="http://orcid.org/0000-0002-5614-1262">Olger Siebinga</a>)
**Repository:** <a href="https://github.com/tud-hri/travia" target ="_blank">https://github.com/tud-hri/travia</a>
**Version:** v1.0.0
**Editor:** @danielskatz
**Reviewers:** @rusu24edward, @tomalrussell
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fb238ebde08f03c9c2767bd049333ef6/status.svg)](https://joss.theoj.org/papers/fb238ebde08f03c9c2767bd049333ef6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fb238ebde08f03c9c2767bd049333ef6"><img src="https://joss.theoj.org/papers/fb238ebde08f03c9c2767bd049333ef6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fb238ebde08f03c9c2767bd049333ef6/status.svg)](https://joss.theoj.org/papers/fb238ebde08f03c9c2767bd049333ef6)
```

**Author instructions**

Thanks for submitting your paper to JOSS @OlgerSiebinga. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @galessiorob.

@OlgerSiebinga if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 976

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (567.3 files/s, 66473.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          44            744            606           3074
Qt                               5             16             48           1280
Markdown                         2             82              0            232
TeX                              1              0              0            105
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            53            843            658           4709
-------------------------------------------------------------------------------


Statistical information for the repository '2cb6a1ab8e84d37ecd19d250' was
gathered on 2021/07/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Olger Siebinga                   1          4424              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Olger Siebinga             4424          100.0          0.0                3.71
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ITSC.2018.8569552 is OK
- 10.1016/j.trc.2019.11.023 is OK
- 10.21949/1504477 is OK
- 10.1073/pnas.1820676116 is OK
- 10.1016/j.trc.2015.07.007 is OK

MISSING DOIs

- 10.1093/gao/9781884446054.article.t067397 may be a valid DOI for title: pickle

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03550/joss.03550/10.21105.joss.03550.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03550/joss.03550/10.21105.joss.03550.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @OlgerSiebinga, thanks for your interest in JOSS! 

Visualization-only software does not always meet our requirements for research software be in scope (based [our definition](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software)), so I'm going to send this out to the editorial board for a scope check, before we move forward.

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@OlgerSiebinga - this paper has passed the scope review, and the AEiC on duty should now work on finding an editor

**Comment by danielskatz** [comment]
Actually, I can take is as editor

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @OlgerSiebinga - Do you have any suggestions for potential reviewers?  If so, then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by OlgerSiebinga** [comment]
Hi @danielskatz, 
Good to hear that the paper has passed the scope review. As for potential reviewers, I looked at the list and found some people with domains/topics that seem relevant. I could not find any reviewers on the list that specified the exact topics of the paper, but here are my best results:

- MrMallIronmaker
- wiljnich; wiljnichepa
- 11michalis11
- rusu24edward
- nickbearman
- papachristoumarios
- bmoradi93
- arunmano121
- mponce0
- zeroset
- 1313e

Besides the potential reviewers on the list, another option would be one of the people that were involved in gathering the data (e.g. robertkrajewski one of the authors of HighD). But I don't know if they would be willing to review.

**Comment by danielskatz** [comment]
👋  @robertkrajewski, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews of open source software and short papers here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by danielskatz** [comment]
👋 @bastilam, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews of open source software and short papers here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by danielskatz** [comment]
👋 @MrMallIronmaker, wiljnichepa, 11michalis11 - Would one or two of you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
👋 @MrMallIronmaker, @wiljnichepa, @11michalis11 - Would one or two of you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
👋 @rusu24edward, @nickbearman, @papachristoumarios - Would one or two of you be willing to review this JOSS submission?

**Comment by nickbearman** [comment]
Sorry @danielskatz I can't currently do Python. How can I update my profile to reflect this? very happy to do R papers!
Thanks.

**Comment by danielskatz** [comment]
> Sorry @danielskatz I can't currently do Python. How can I update my profile to reflect this? very happy to do R papers!
> Thanks.

@arfon - can you help with this update request?

**Comment by rusu24edward** [comment]
@danielskatz I can review it.

**Comment by arfon** [comment]
> @arfon - can you help with this update request?

Done.

**Comment by danielskatz** [comment]
thanks @rusu24edward - I'll add you as a reviewer, but we won't start until I find one more reviewer as well

**Comment by danielskatz** [comment]
@whedon assign @rusu24edward as reviewer

**Comment by whedon** [comment]
OK, @rusu24edward is now a reviewer

**Comment by danielskatz** [comment]
@bmoradi93, @arunmano121, @mponce0 - Would one or two of you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
👋 @tomalrussell - you've been recommended to me as a potential second reviewer for this submission by a new JOSS editor, @martinfleis.  We carry out our checklist-driven reviews of open source software and short papers here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html  Would you be willing to review this submission?

**Comment by tomalrussell** [comment]
Hi @danielskatz I'd be happy to take a look at this.

**Comment by danielskatz** [comment]
Thanks very much @tomalrussell  - I'll add you, and then will start a review issue where the actual review will take place.

**Comment by danielskatz** [comment]
@whedon add @tomalrussell as reviewer

**Comment by whedon** [comment]
OK, @tomalrussell is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3607.

**Comment by arunmano121** [comment]
@danielskatz - I can review this if you are still looking for reviewers.

**Comment by danielskatz** [comment]
Thanks for volunteering @arunmano121, but I think 2 reviewers are enough at this point.
