### ISSUE TITLE
[PRE REVIEW]: Octo-Tiger: a fully 3D adaptive multigrid astrophysics code accelerated using the asynchronous many-task runtime HPX

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3552]
**Submitting author:** @dmarce1 (<a href="http://orcid.org/0000-0002-2782-315X">Dominic Marcello</a>)
**Repository:** <a href="https://github.com/STEllAR-GROUP/octotiger/" target ="_blank">https://github.com/STEllAR-GROUP/octotiger/</a>
**Version:** 1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/43b0956973751a4599ec39f455976be0/status.svg)](https://joss.theoj.org/papers/43b0956973751a4599ec39f455976be0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/43b0956973751a4599ec39f455976be0"><img src="https://joss.theoj.org/papers/43b0956973751a4599ec39f455976be0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/43b0956973751a4599ec39f455976be0/status.svg)](https://joss.theoj.org/papers/43b0956973751a4599ec39f455976be0)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dmarce1. **Currently, there isn't an JOSS editor assigned** to your paper.

@dmarce1 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3552 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.27 s (959.7 files/s, 175663.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             85           2416           2628          21152
C/C++ Header                   110           2029           1974          12986
CMake                           11            159            279           1355
Groovy                           4             22             44            786
YAML                             3             16             29            273
Markdown                         9             75              0            259
Bourne Shell                    17            117             54            250
INI                             14             18              0            183
TeX                              2             34              0            128
Python                           1             16              0             43
DOS Batch                        1             10              0             39
make                             1              7              5             12
CUDA                             1              3              0              4
-------------------------------------------------------------------------------
SUM:                           259           4922           5013          37470
-------------------------------------------------------------------------------


Statistical information for the repository '97fd9dc24176411e9b0e8200' was
gathered on 2021/07/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bryce Adelstein-Lelb            46          4730           4806            3.07
David Pfander                   12          4059            872            1.59
Dominic Marcello              1028         87385          63189           48.41
Gregor Daiss                    11            56             24            0.03
Gregor Daiß                    650         60349          38342           31.73
Hartmut Kaiser                  72          3996           2456            2.07
John Biddiscombe                 3           210            121            0.11
Kevin Huck                       2             5              3            0.00
Parsa Amini                     39          4458           3485            2.55
Patrick                          2            27            219            0.08
Patrick Diehl                   20          6342          15625            7.06
Sagiv Shiber                     3            26             27            0.02
Theresa Pollinger                1            11             17            0.01
Thomas Heller                   29          1087            819            0.61
dmarce1                         73          4445           2670            2.29
fire                             1            32             33            0.02
pfandedd                         6           234             48            0.09
shibersag                       17           583            250            0.27

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Bryce Adelstein-Lelb        277            5.9         51.7               16.97
David Pfander               974           24.0         47.1               65.71
Dominic Marcello          20078           23.0         32.0                4.53
Gregor Daiß               16334           27.1         13.8               12.87
Hartmut Kaiser             1168           29.2         54.2               13.53
John Biddiscombe             24           11.4         56.4                0.00
Kevin Huck                    3           60.0         56.2               66.67
Parsa Amini                3197           71.7         28.9               15.45
Patrick                     204          755.6         24.6               77.94
Patrick Diehl               502            7.9         22.7               88.05
Sagiv Shiber                 15           57.7         21.6                0.00
Theresa Pollinger            10           90.9         16.1               10.00
Thomas Heller               197           18.1         52.7                6.60
fire                         19           59.4         51.8                0.00
pfandedd                      1            0.4         56.0                0.00
shibersag                   471           80.8         16.5                8.92
```

**Comment by kyleniemeyer** [comment]
Hello @dmarce1, thanks for your submission to JOSS. It looks like whedon cannot find your paper—is it in a branch?

Also, I noticed in your submission notes that you have recently published a methods paper on this software. I assume this is https://doi.org/10.1093/mnras/stab937.

Since that article is entirely about the software as well, publishing in JOSS would constitute duplicate publication about the software. I'm going to ping the rest of the editorial board / EICs about this, though.

**Comment by diehlpk** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03552/joss.03552/10.21105.joss.03552.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03552/joss.03552/10.21105.joss.03552.pdf) :page_facing_up: :point_left:

**Comment by diehlpk** [comment]
@kyleniemeyer I would like to elaborate on the methods paper. This paper has a high focus on the astrophysics aspects of the code, and the code was validated and benchmarked against other codes. As you can see at looking at the authors lists, not many names pop up in the list of GitHub contributors in that paper. The computer science details, especially the GPU acceleration, was only briefly mentioned for one compute kernel. However, we ported more kernels to the GPU and added Kokkos integration to Octo-Tiger. The new version support preliminary support of AMD GPU's, and we started to add vectorization for the novel Arm64fx architecture. The list of the JOSS paper reflects more the computer science team of Octo-Tiger. So our intent was to have the JOSS paper next to the method paper since this paper was only for the astrophysics aspects of the code and not about the many computer science contributions.

In addition, we really look forward to getting some feedback on the code since  we hope that we will get some new users in the near future.

**Comment by kyleniemeyer** [comment]
@whedon query scope

Thanks @diehlpk for the additional context. I do think that this one is still a bit fuzzy, so I'm going to get more feedback from the rest of the editorial board via a scope query (not for the content of the software itself, which is clearly in scope for JOSS).

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@diehlpk & @dmarce1  - The editorial board has decided that there isn't a sufficient scholarly contribution in this submission compared to the recently published paper. If you feel the computer science contributions were not sufficiently recognized in the original paper, and some authors were left out, you might want to submit a computer science paper to a computer science journal.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
