### ISSUE TITLE
[PRE REVIEW]: R-Opitools – An Opinion Analytical Tool for Big Digital Text Document (DTD)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3553]
**Submitting author:** @MAnalytics (<a href="http://orcid.org/0000-0002-9006-4934">Monsuru Adepeju</a>)
**Repository:** <a href="https://github.com/MAnalytics/opitools" target ="_blank">https://github.com/MAnalytics/opitools</a>
**Version:** v1.8.0
**Editor:** @ajstewartlang
**Reviewers:** @cjbarrie, @justinchuntingho
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e6f8bffc4d91defe1e1e058e070d94d3/status.svg)](https://joss.theoj.org/papers/e6f8bffc4d91defe1e1e058e070d94d3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e6f8bffc4d91defe1e1e058e070d94d3"><img src="https://joss.theoj.org/papers/e6f8bffc4d91defe1e1e058e070d94d3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e6f8bffc4d91defe1e1e058e070d94d3/status.svg)](https://joss.theoj.org/papers/e6f8bffc4d91defe1e1e058e070d94d3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @MAnalytics. **Currently, there isn't an JOSS editor assigned** to your paper.

@MAnalytics if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 501

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (618.9 files/s, 102681.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1             43              2           1189
R                               17            344            811            974
Rmd                              1            129            196            138
Markdown                         4             68              0            123
TeX                              2             17              0            114
-------------------------------------------------------------------------------
SUM:                            25            601           1009           2538
-------------------------------------------------------------------------------


Statistical information for the repository 'db15047b8977f1a62e34c51f' was
gathered on 2021/07/30.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3389/frobt.2018.00138 is OK
- 10.21105/joss.00764 is OK
- 10.4236/jgis.2021.132008 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03553/joss.03553/10.21105.joss.03553.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03553/joss.03553/10.21105.joss.03553.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hello @MAnalytics, thanks for your interest in JOSS. I noticed that this is a resubmission of #3083 (cc @kthyng). Can you please summarize the changes you have made in response to the original feedback?

**Comment by kyleniemeyer** [comment]
@whedon invite @ajstewartlang as editor

@ajstewartlang could you edit this submission?

**Comment by whedon** [comment]
@ajstewartlang has been invited to edit this submission.

**Comment by MAnalytics** [comment]
> Hello @MAnalytics, thanks for your interest in JOSS. I noticed that this is a resubmission of #3083 (cc @kthyng). Can you please summarize the changes you have made in response to the original feedback?

Hello @kyleniemeyer @kthyng ,

The major criticism of the original submission was that the code was too narrow in scope; that it was too specific to one example application, and may be difficult for uptake in other areas. Consequently, I made the following changes:

#1. Modularizing the function 'opi_impact.R' by extracting (or separating) a new function 'word_imp.R' that will allow a text document (on any subject) to be explored for new themes from within the document. 

#2. Provided two additional application examples of the codes in broader application areas (i.e. marketing & politics) to demonstrate the generalization of the new submission (please see the 'README.md' & the Vignette).

#3. The text of the paper and (many of) the documentation of the codes have been re-written in accordance to the changes made.
 
I hope this explanation answers your question.

Thank you very much,

Monsuru

**Comment by danielskatz** [comment]
As another JOSS AEiC, I don't think this is enough of a change to justify a new paper under JOSS's [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion, but let's make this a formal discussion by the editors.  You will hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by MAnalytics** [comment]
Dear @danielskatz @kyleniemeyer @kthyng ,

I greatly appreciate your suggestion.

Based on my understanding, the original submission was deemed substantial, but (in fact) the only critic was that it seems too specific to one subject area (law enforcements) upon which the method (in a journal article) was originally published (https://www.scirp.org/journal/paperinformation.aspx?paperid=107836). However, I warmly welcome the formal discussion against the criterion. 

Thanks as I anticipate your favourable feedback.
M.A.

**Comment by danielskatz** [comment]
When you say "the original submission", can you point to the specific work, so we can be sure we are talking about the same thing.

**Comment by danielskatz** [comment]
Sorry, I was confusing this submission with another.

**Comment by danielskatz** [comment]
I think it would be helpful if the paper discussed some of the use cases at a high level - basically, I think the paper should give some examples of who would use the software and for what, as part of the statement of need section.

**Comment by MAnalytics** [comment]
> I think it would be helpful if the paper discussed some of the use cases at a high level - basically, I think the paper should give some examples of who would use the software and for what, as part of the statement of need section.

@danielskatz @kyleniemeyer Sorry for the delay in response. I have now modified the statement of need section to include application areas of the software and some examples. Thanks. 
MA

**Comment by MAnalytics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03553/joss.03553/10.21105.joss.03553.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03553/joss.03553/10.21105.joss.03553.pdf) :page_facing_up: :point_left:

**Comment by MAnalytics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03553/joss.03553/10.21105.joss.03553.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03553/joss.03553/10.21105.joss.03553.pdf) :page_facing_up: :point_left:

**Comment by MAnalytics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03553/joss.03553/10.21105.joss.03553.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03553/joss.03553/10.21105.joss.03553.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@MAnalytics - this paper has passed the scope review, and the AEiC on duty should now work on finding an editor

**Comment by MAnalytics** [comment]
@danielskatz @kyleniemeyer Great news! Thank you very much. I greatly appreciate the efforts.

**Comment by Kevin-Mattheus-Moerman** [comment]
@lorenanicole is this something you could review once you are available?

**Comment by Kevin-Mattheus-Moerman** [comment]
@MAnalytics I have `waitlisted` this submission. This is because we currently do not have an editor available in this domain. We well assign a handling editor as soon as a suitable one becomes available.

**Comment by danielskatz** [comment]
@whedon assign @ajstewartlang as editor
(based on previous discussion and slack comments)

**Comment by whedon** [comment]
OK, the editor is @ajstewartlang

**Comment by ajstewartlang** [comment]
@whedon assign @cjbarrie as reviewer

**Comment by whedon** [comment]
OK, @cjbarrie is now a reviewer

**Comment by ajstewartlang** [comment]
@whedon add @justinchuntingho as reviewer
