### ISSUE TITLE
[PRE REVIEW]: CellPyLib: A Python Library for working with Cellular Automata

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3555]
**Submitting author:** @lantunes (<a href="http://orcid.org/0000-0002-4867-5635">Luis Antunes</a>)
**Repository:** <a href="https://github.com/lantunes/cellpylib" target ="_blank">https://github.com/lantunes/cellpylib</a>
**Version:** v1.0.0
**Editor:** @jbytecode
**Reviewers:** @blsqr, @szhorvat
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fdb54d9515fc7bed89268c15373b95fc/status.svg)](https://joss.theoj.org/papers/fdb54d9515fc7bed89268c15373b95fc)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fdb54d9515fc7bed89268c15373b95fc"><img src="https://joss.theoj.org/papers/fdb54d9515fc7bed89268c15373b95fc/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fdb54d9515fc7bed89268c15373b95fc/status.svg)](https://joss.theoj.org/papers/fdb54d9515fc7bed89268c15373b95fc)
```

**Author instructions**

Thanks for submitting your paper to JOSS @lantunes. **Currently, there isn't an JOSS editor assigned** to your paper.

@lantunes if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 854

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (599.1 files/s, 56776.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          26            419            388           1924
Markdown                         2            122              0            296
reStructuredText                 6             90             92            122
TeX                              1              5              0             65
DOS Batch                        1              8              1             26
make                             1              5              7             16
YAML                             1              2              0             13
-------------------------------------------------------------------------------
SUM:                            38            651            488           2462
-------------------------------------------------------------------------------


Statistical information for the repository '4abf187ae07eb9399360e525' was
gathered on 2021/08/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Luis Antunes                    49         17349          14689           99.75
Martin Neumayer                  3            76              5            0.25

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Luis Antunes               2659           15.3         33.8                5.38
Martin Neumayer              72           94.7          4.7                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- 10.1016/0167-2789(90)90064-v may be a valid DOI for title: Computation at the Edge of Chaos: Phase Transitions and Emergent Computation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03555/joss.03555/10.21105.joss.03555.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03555/joss.03555/10.21105.joss.03555.pdf) :page_facing_up: :point_left:

**Comment by lantunes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03555/joss.03555/10.21105.joss.03555.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03555/joss.03555/10.21105.joss.03555.pdf) :page_facing_up: :point_left:

**Comment by lantunes** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1142/4702 is OK
- 10.1016/0167-2789(90)90064-v is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.25088/complexsystems.26.4.319 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lantunes** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by lantunes** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 890

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (796.8 files/s, 68963.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          37            518            479           2603
Markdown                         2            122              0            298
reStructuredText                17            283            436            282
TeX                              1              7              0             87
DOS Batch                        1              8              1             26
make                             1              5              7             16
YAML                             1              2              0             13
-------------------------------------------------------------------------------
SUM:                            60            945            923           3325
-------------------------------------------------------------------------------


Statistical information for the repository '839295253f9d4e51122c6ea1' was
gathered on 2021/08/02.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Luis Antunes                    53         18235          14706           99.75
Martin Neumayer                  3            76              5            0.25

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Luis Antunes               3528           19.3         25.4                5.10
Martin Neumayer              72           94.7          4.7                0.00
```

**Comment by lantunes** [comment]
After looking through the list of JOSS reviewers, I believe the following people would be best suited for this submission: 
`martibosch`
`blsqr`
`amcasari`
`JJ`
`szhorvat`
`mzamoraz`
`Datseris`

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @meg-simula as editor

@meg-simula is this something you could handle as editor? I realize it may be somewhat off topic but it looks like it should go to an applied mathematics person and you are currently the only available person in this domain.

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by arfon** [comment]
@whedon invite @jbytecode as editor

:wave: @jbytecode – any chance you could handle this submission for us?

**Comment by whedon** [comment]
@jbytecode has been invited to edit this submission.

**Comment by jbytecode** [comment]
@whedon assign me as editor 

Hi @arfon, of course, I gladly accept to be editor of this submission.

**Comment by whedon** [comment]
OK, the editor is @jbytecode

**Comment by jbytecode** [comment]
@lantunes could be please add correct metadata including authors ORCID in paper.md?

**Comment by jbytecode** [comment]
👋👋👋 @martibosch, @blsqr, @amcasari 👋👋👋

Would you be willing to assist in reviewing this submission for JOSS (Journal of Open Source Software)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "CellPyLib: A Python Library for working with Cellular Automata". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3555).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by lantunes** [comment]
@jbytecode Thank you for agreeing to edit this submission! I have updated `paper.md` so that it includes `orcid` in the metadata section. Please let me know if there is any other metadata that needs to be added.

**Comment by blsqr** [comment]
Hi everyone 👋

I'd be happy to review this submission. However, I cannot actively participate before 26th August – if that's ok, sign me up.

> assist in reviewing

What does *assist* entail in this context? Is there a distinction between reviewing and assisting?

**Comment by jbytecode** [comment]
@whedon add @blsqr as reviewer

Dear @blsqr, the term `assist in reviewing` means `being a reviewer`. Thank you for accepting our invitation. 

In JOSS, assigning adequate number of viewers may take time so we can wait for your availability.

**Comment by whedon** [comment]
OK, @blsqr is now a reviewer

**Comment by jbytecode** [comment]
👋👋👋 @szhorvat  👋👋👋

Would you be willing to assist in reviewing this submission for JOSS (Journal of Open Source Software)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "CellPyLib: A Python Library for working with Cellular Automata". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3555).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by whedon** [comment]
OK, @szhorvat is now a reviewer

**Comment by jbytecode** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3608.

**Comment by martibosch** [comment]
Hello!

I see that there are already 2 reviewers assigned, but I'd also be happy to review this if you are up for taking 3 reviewers - this looks very interesting and it might actually be useful for my future research. I should note that I am quite familiar with land use/land cover CA but not so much about other applications - although I have read a few articles about their historical origins and first applications (e.g., artificial life).

Best,
Martí

**Comment by jbytecode** [comment]
@martibosch you are now the third reviewer. Please keep track of the reviewing issue.

@szhorvat Thank you! Your deadline is still reasonable for us. 

Here is the reviewing issue: https://github.com/openjournals/joss-reviews/issues/3608
