### ISSUE TITLE
[PRE REVIEW]: diman: A Clojure package for dimensional analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3558]
**Submitting author:** @lungsi (<a href="http://orcid.org/0000-0002-1607-0164">B. Lungsi Sharma</a>)
**Repository:** <a href="https://github.com/neuralgraphs/diman" target ="_blank">https://github.com/neuralgraphs/diman</a>
**Version:** v1.0.5
**Editor:** @mjsottile
**Reviewers:** @oyvinht, @khinsen
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/90d6831ce9f27346f4bd809923412257/status.svg)](https://joss.theoj.org/papers/90d6831ce9f27346f4bd809923412257)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/90d6831ce9f27346f4bd809923412257"><img src="https://joss.theoj.org/papers/90d6831ce9f27346f4bd809923412257/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/90d6831ce9f27346f4bd809923412257/status.svg)](https://joss.theoj.org/papers/90d6831ce9f27346f4bd809923412257)
```

**Author instructions**

Thanks for submitting your paper to JOSS @lungsi. **Currently, there isn't an JOSS editor assigned** to your paper.

@lungsi if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1053

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (1055.4 files/s, 103782.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Clojure                         42            263            307           2711
AsciiDoc                         5            230              0            762
reStructuredText                 5            327             73            584
Markdown                         3             39              0            146
TeX                              1              6              0             59
-------------------------------------------------------------------------------
SUM:                            56            865            380           4262
-------------------------------------------------------------------------------


Statistical information for the repository 'b13bfc2d0176afaf1cd8f82c' was
gathered on 2021/08/03.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03558/joss.03558/10.21105.joss.03558.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03558/joss.03558/10.21105.joss.03558.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lungsi** [comment]
@whedon Based on the [programming languages listed](https://bit.ly/joss-reviewers) (either under "preferred" or "other" languages) below are some of the potential reviewers

- **oyvinht**
- **jonahbenton**
- **RuneBlaze**
- **chlalanne**
- **daviddewhurst**

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@lungsi unfortunately all editors that could handle this submission are currently preoccupied with other submission. We will list this submission as `waitlisted` for the moment until an editor becomes available. We apologize for this delay and thank you for your patience.

**Comment by Kevin-Mattheus-Moerman** [comment]
@marcosvital @VivianePons @mjsottile @vissarion @Nikoleta-v3 I have waitlisted this submission for now since you all seem per-occupied with other submissions. Let me know if this is something you think you could edit when you are available. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @fabian-s as editor

**Comment by whedon** [comment]
@fabian-s has been invited to edit this submission.

**Comment by fabian-s** [comment]
Sorry, I'd rather not -- don't know any Clojure, don't understand what this is supposed to be about.

**Comment by Nikoleta-v3** [comment]
👋🏻 @Kevin-Mattheus-Moerman - unfortunately I do not know any Clojure either 😕

**Comment by mjsottile** [comment]
@Kevin-Mattheus-Moerman I'm not available now, but if this paper still needs an editor when one of the other submissions I'm handling is complete I can do it.  I'm familiar with Clojure and relatives.

**Comment by danielskatz** [comment]
👋 @mjsottile - since one of your submissions seems to be somewhat paused, I wonder if you could take this and get it started, with the knowledge that it might slow down if they other one restarts?

**Comment by mjsottile** [comment]
@danielskatz That works.  I'll be in and out over the next two weeks, but should be available enough to get the review started.

**Comment by mjsottile** [comment]
@whedon assign @mjsottile as editor

**Comment by whedon** [comment]
OK, the editor is @mjsottile

**Comment by mjsottile** [comment]
@lungsi I plan to solicit reviewers soon, but am busy until next week.  I also wanted to give some preliminary feedback about your write up related to grammatical issues so that you could fix it before the reviewers take a look.  Expect more from me in a few days.

**Comment by lungsi** [comment]
Thank you @mjsottile Looking forward to your feedback.

**Comment by mjsottile** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03558/joss.03558/10.21105.joss.03558.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03558/joss.03558/10.21105.joss.03558.pdf) :page_facing_up: :point_left:

**Comment by mjsottile** [comment]
Hi @lungsi - I see that you've started making grammatical updates.  It looks like you've addressed a number of the issues that I was going to point out.  Let me know when you are done making changes so I can invite reviewers.

**Comment by lungsi** [comment]
Hi @mjsottile, Thank you. I was about to generate the pdf. Please go ahead with the invitations.

**Comment by oyvinht** [comment]
Dear Matthew Sottile,I would be happy to do this review.-- Kind regards Øyvin Halfdan Thuv Department of Computer Science and Computer Engineering The Arctic University of Norway

**Comment by mjsottile** [comment]
@whedon assign @oyvinht as reviewer

**Comment by whedon** [comment]
OK, @oyvinht is now a reviewer

**Comment by mjsottile** [comment]
:wave: @RuneBlaze - you were suggested by the author of this submission to the Journal of Open Source Software (JOSS) as potential reviewers. Would you be interested in providing a review? If you haven't reviewed for JOSS before, you can see the review criteria here : https://joss.readthedocs.io/en/latest/review_criteria.html

Please let me know if you are interested or have any questions.

**Comment by RuneBlaze** [comment]
@mjsottile Sorry but I have more homework to do/experiments to run than expected recently. I also know nothing dimensional analysis.

**Comment by mjsottile** [comment]
:wave: @khinsen Based on your areas of expertise I believe you may be a good fit to provide a review for this JOSS submission.  Please let me know if you are interested and have time.  Thanks!

**Comment by khinsen** [comment]
@mjsottile This looks interesting indeed! I'd be happy to review, starting in about a week.

**Comment by mjsottile** [comment]
@whedon add @khinsen as reviewer

**Comment by whedon** [comment]
OK, @khinsen is now a reviewer

**Comment by mjsottile** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3735.

**Comment by mjsottile** [comment]
@whedon add @oyvinht as reviewer

**Comment by whedon** [comment]
OK, @oyvinht is now a reviewer
