### ISSUE TITLE
[PRE REVIEW]: ORION2: A magnetohydrodynamics code for star formation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3559]
**Submitting author:** @soffner (<a href="http://orcid.org/0000-0003-1252-9916">Stella Offner</a>)
**Repository:** <a href="https://bitbucket.org/orionmhdteam/orion2_release1/src/master/" target ="_blank">https://bitbucket.org/orionmhdteam/orion2_release1/src/master/</a>
**Version:** v1.0.0
**Editor:** @dfm
**Reviewers:** @zingale, @changgoo
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c8c824a316e16f6929ad490ee93d9f5d/status.svg)](https://joss.theoj.org/papers/c8c824a316e16f6929ad490ee93d9f5d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c8c824a316e16f6929ad490ee93d9f5d"><img src="https://joss.theoj.org/papers/c8c824a316e16f6929ad490ee93d9f5d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c8c824a316e16f6929ad490ee93d9f5d/status.svg)](https://joss.theoj.org/papers/c8c824a316e16f6929ad490ee93d9f5d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @soffner. **Currently, there isn't an JOSS editor assigned** to your paper.

@soffner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 814

**Comment by whedon** [comment]
PDF failed to compile for issue #3559 with the following error: 
```
 Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
Invalid ORDIC digit (x)
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (xxxx-xxxx-xxxx-xxxx) for Pak Shing Li (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/mnras/stz653 is OK
- 10.1093/mnras/stx2611 is OK
- 10.1093/mnras/stv1437 is OK
- 10.1088/0004-637X/747/1/22 is OK
- 10.1016/j.jcp.2007.07.035 is OK
- 10.1016/j.jcp.2007.09.032 is OK
- 10.1086/421935 is OK
- 10.1088/0004-637X/745/2/139 is OK
- 10.1086/305329 is OK
- 10.1086/310975 is OK
- 10.1088/0004-637X/740/2/107 is OK
- 10.1088/0004-637X/811/2/146 is OK
- 10.1086/426051 is OK
- 10.1086/590238 is OK
- 10.1088/0004-6256/136/1/404 is OK
- 10.1088/0004-637X/703/1/131 is OK
- 10.1088/0004-637X/693/1/914 is OK
- 10.1088/0004-637X/704/2/L124 is OK
- 10.1093/mnras/stu052 is OK
- 10.1038/nature13662 is OK
- 10.1088/0004-637X/783/1/50 is OK
- 10.1038/s41550-018-0566-1 is OK
- 10.3847/1538-4357/ab584b is OK

MISSING DOIs

- 10.1016/s0377-0427(99)00156-9 may be a valid DOI for title: Star formation with 3-D adaptive mesh refinement: the collapse and fragmentation of molecular clouds.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.65 s (882.4 files/s, 271977.5 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
C++                             516          32029          31720         184833
C/C++ Header                    504          17559          35231          64419
C                               127           6463          10161          21534
Python                           46           1326           1426           5013
Fortran 77                       15            325           3158           4388
IDL                              50           1707           2938           4257
Perl                             25            900           1755           3580
make                             79            857            931           1599
SWIG                              7            827              0           1472
reStructuredText                 33            697            171           1057
HTML                              1            390              1            881
INI                              14            248              0            824
Bourne Shell                     17             99            114            560
Bourne Again Shell                3             57            170            439
TeX                               1             45              0            427
diff                              1             34            160            232
MATLAB                            1             24              5            134
Markdown                          1             16              0            111
C Shell                           8             28              3            103
awk                               1              1              4             37
Fortran 90                        1              6              0             28
CMake                             1              5             11             10
--------------------------------------------------------------------------------
SUM:                           1452          63643          87959         295938
--------------------------------------------------------------------------------


Statistical information for the repository 'ff21fd31d97ce34ab8922504' was
gathered on 2021/08/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Offner                           1        298269              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Stella Offner            298269          100.0          0.0               15.55
```

**Comment by soffner** [comment]
@whedon generate pdf


@whedon commands

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03559/joss.03559/10.21105.joss.03559.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03559/joss.03559/10.21105.joss.03559.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@soffner since all editors in this domain are currently preoccupied with other submissions I have assigned the `waitlisted` label here for now. We will assign an editor as soon as one becomes available. Thanks for your patience.

**Comment by dfm** [comment]
@whedon assign me as editor

Sorry about the delay! I'm happy to edit, but as @Kevin-Mattheus-Moerman mentioned, things are a little backed up at the moment so it'll be a week or two before I can get the process started. Thanks for your patience!

In the meantime, @soffner I'm a little confused about the relationship between paper authorship and commit history. I assume that the bulk of the code was written outside of version control? Would you mind clarifying the history of the project, the role/contribution of other authors, and the plans for future open development of the software?

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by soffner** [comment]
Hi @dfm. Thanks for agreeing to edit!

Regarding the version and commit history -- ORION2 was developed in a
private repository, developed and maintained by a relatively small
collaboration. It was private because of functionality (the radiative
transfer module) that was developed through collaboration with researchers
at LLNL, which has fairly strict release restrictions. In order to make
ORION2 public we needed to strip out all the embargoed code and code that
is still under active development and then migrate this cleaned version to
a public repository.

Regarding the authorship. PS Li is responsible for implementing the most
major component of the released ORION2, which is the ideal AMR MHD method,
which is why he is first author on the JOSS paper. The rest of the
contributors are listed alphabetically. I am the corresponding author (and
the one mostly responsible for the public branch), since I have been
leading the collaboration through the steps necessary for public release.

Let me know if you have any other questions.

**Comment by dfm** [comment]
@soffner: I'm really sorry about the slow response over here! I've been working on recruiting reviewers, but things have been slow (in large part my fault!) so hopefully I'll have two lined up soon. Thanks for your patience!

In response to your comments above:

1. I can see some inconsistency between the closed development model that you describe and the [JOSS "Community guidelines" checklist requirement](https://joss.readthedocs.io/en/latest/review_checklist.html#documentation), but this is certainly manageable. Perhaps you can double check that the workflow for submitting contributions, issues, and support requests is documented and available to potential reviewers?
2. We also have [a checklist item related to authorship](https://joss.readthedocs.io/en/latest/review_checklist.html#general-checks) where reviewers might need a little more info. One approach that has worked in the past is to open an issue on the source repository and have a public discussion/sign-off from the co-authors about the contribution history.

Thanks again for your patience and I'll keep you up to date on the reviewer search.

**Comment by soffner** [comment]
Hi @dfm

Thanks. Any luck in the reviewer search?

For (1) I think we can be more explicit in the documentation about how to
submit issues. Right now it mentions our google group email (which reaches
all the current developers) but doesn't mention submitting a ticket to the
repository. Do you want me to make a change now to the documentation?

(2) I don't totally understand what you are suggesting in your point (2).
You want all the coauthors to acknowledge their contributions by commenting
on the repository?

Thanks.
Stella

**Comment by dfm** [comment]
@whedon add @zingale as reviewer

Mike has agreed to be one of our reviewers - thanks!! I'm hoping to have another on lined up soon so we can finally get started. Thanks again @soffner for your patience.

**Comment by whedon** [comment]
OK, @zingale is now a reviewer

**Comment by soffner** [comment]
Great!

@dfm I addressed one of your recent comments and I'm consulting with the
rest of the developer team on how to address the other.

**Comment by dfm** [comment]
@whedon add @changgoo as reviewer

And... we have our second reviewer. Thanks Chang-Goo!

I'll get the review started in a new issue thread with more information. Thanks all for agreeing to participate in this review process and let me know if you have any questions, comments, or issues as we go. I'm here to help!

**Comment by whedon** [comment]
OK, @changgoo is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3771.
