### ISSUE TITLE
[PRE REVIEW]: schwimmbad: A uniform interface to parallel processing pools in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#356]
**Submitting author:** @adrn (<a href="http://orcid.org/0000-0003-0872-7098">Adrian Price-Whelan</a>)
**Repository:** <a href="https://github.com/adrn/schwimmbad" target ="_blank">https://github.com/adrn/schwimmbad</a>
**Version:** v0.2.1
**Editor:** @danielskatz
**Reviewer:** @jmjwozniak

**Author instructions**

Thanks for submitting your paper to JOSS @adrn. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@adrn if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @labarba - the submitting authors suggested you as the editor.

**Comment by danielskatz** [comment]
I'm also interested in this one and could possibly suggest a reviewer

**Comment by labarba** [comment]
I'm editing two other new submissions (where contacted reviewers have not responded yet), so if @danielskatz wants to take this one, be my guest.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
@whedon assign @jmjwozniak as reviewer

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/357. Feel free to close this issue now!
