### ISSUE TITLE
[PRE REVIEW]: CleanX: A Python library for data cleaning of large sets of radiology images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3560]
**Submitting author:** @drcandacemakedamoore  (<a href="http://orcid.org/0000-0003-1672-7565">Candace Makeda Moore</a>)
**Repository:** <a href="https://github.com/drcandacemakedamoore/cleanX" target ="_blank">https://github.com/drcandacemakedamoore/cleanX</a>
**Version:** v0.1.9
**Editor:** @cMadan
**Reviewers:** @henrykironde, @anki-xyz
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/47ee52ff835dcd67c1f0b4c9cb74225a/status.svg)](https://joss.theoj.org/papers/47ee52ff835dcd67c1f0b4c9cb74225a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/47ee52ff835dcd67c1f0b4c9cb74225a"><img src="https://joss.theoj.org/papers/47ee52ff835dcd67c1f0b4c9cb74225a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/47ee52ff835dcd67c1f0b4c9cb74225a/status.svg)](https://joss.theoj.org/papers/47ee52ff835dcd67c1f0b4c9cb74225a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @drcandacemakedamoore . **Currently, there isn't an JOSS editor assigned** to your paper.

@drcandacemakedamoore  if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 829

**Comment by whedon** [comment]
PDF failed to compile for issue #3560 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Candace Moore,, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2207243.2207253 is OK
- 10.18637/jss.v059.i10 is OK
- 10.1007/978-3-319-94878-2_6 is OK
- 10.1007/s00330-020-07453-w is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (262.1 files/s, 161779.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          20            811           1270           3036
CSS                              1            191             32            680
Jupyter Notebook                 4              0          17553            387
YAML                             3             11             10            205
Markdown                         5            103              0            202
TeX                              1              9              0             57
Bourne Shell                     2              3              0             32
DOS Batch                        1              8              1             26
reStructuredText                 2             14              8             24
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            40           1154          18881           4658
-------------------------------------------------------------------------------


Statistical information for the repository '82d1d6bd98d10a8eddf63301' was
gathered on 2021/08/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Candace Makeda Moore           176         17910          15261           86.76
Oleg Sivokon                    69          3759           1291           13.21
andrew-f-murphy                  2             5              5            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Candace Makeda Moore       2070           11.6          2.0                9.42
Oleg Sivokon               3043           81.0          0.6                7.66
andrew-f-murphy               4           80.0          3.5              100.00
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@drcandacemakedamoore your paper failed to compile. I think this is because of the use of comma's in the author names. 

I think this pull-request should fix it: 
https://github.com/drcandacemakedamoore/cleanX/pull/30

Let me know if you'd prefer to have the `, MD` etc. part back in, then we'll trouble shoot this further to try to include it.

**Comment by drcandacemakedamoore** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3560 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Candace Moore, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by wvxvw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3560 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:60:in `build_affiliation_string': undefined method `split' for [1, 3]:Array (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03560/joss.03560/10.21105.joss.03560.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03560/joss.03560/10.21105.joss.03560.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@drcandacemakedamoore thanks for fixing it. It looks like what I proposed was not it, it was actually `"1,3"` as you fixed it. Feel free to put the `, MD` back if you like.

**Comment by Kevin-Mattheus-Moerman** [comment]
@drcandacemakedamoore I have `waitlisted` this submission since no editors in this domain are currently available. We will assign one as soon as one becomes available. Apologies and thank you for your patience.

**Comment by Kevin-Mattheus-Moerman** [comment]
Note for AEiC on call: If no alternative handling editor becomes available within 2 weeks I can take this one.

**Comment by drcandacemakedamoore** [comment]
Thanks, we are constantly adding things. Will the editors look only at the current released version? And if so, should we release a new version in about two weeks when you may review, and let you know?

**Comment by arfon** [comment]
@whedon invite @cMadan as editor

:wave: @cMadan – any chance you could edit this submission for us?

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by arfon** [comment]
@whedon invite @cMadan as editor

(Debugging an issue with email invites for @cMadan)

**Comment by whedon** [comment]
@cMadan has been invited to edit this submission.

**Comment by cMadan** [comment]
Emails recieved! In the other issue, `whedon` never replied to the invite request.

**Comment by cMadan** [comment]
@whedon assign @cMadan as editor

@arfon, happy to take this one!

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by cMadan** [comment]
@drcandacemakedamoore, it sounds like you have some updates on the go. Ideally the JOSS reviewers will review a stable version of the code, suggest some improvements, and then a version with those changes will be the archived version that the JOSS publication is associated with. From your earlier question, I wonder if it would it be better to wait for before we start the review?

**Comment by drcandacemakedamoore** [comment]
I will freeze updating everything on the Main branch to make this easier. The only important changes were to dramatically improve the documentation (we found some problems that Sphinx had made us, and fixed them). I would like to move forward with the review as this is re-submission after substantial work, and we anticipate that work will continue for years as dependencies change.

**Comment by cMadan** [comment]
@drcandacemakedamoore, thanks for clarifying that--and for mentioning this was a re-submission, I read over those past issues now.

Can you suggest some potential reviewers? (See guidance included in the first comment in this issue.)

**Comment by drcandacemakedamoore** [comment]
I hope this can be an OK place in the thread to mention potential reviewers. I believe that from the list provided those with user names "fernandoandreotti" and "anki-xyz" may be good leads for potential reviewers.

**Comment by henrykironde** [comment]
Happy to be part of the reviewers under software but not the domain-specific part of the submission

**Comment by cMadan** [comment]
@henrykironde, that would be much appreciated, thank you!

**Comment by cMadan** [comment]
@whedon add @henrykironde as reviewer

**Comment by whedon** [comment]
OK, @henrykironde is now a reviewer

**Comment by cMadan** [comment]
@fernandoandreotti @anki-xyz, would either of you be available and interested in reviewing this submission?

**Comment by anki-xyz** [comment]
I can review it, but I'm currently on holidays; will be back in September, if this is not an issue.

**Comment by cMadan** [comment]
@anki-xyz, that would be great, thank you! I have no problem with you starting the review in September. I will assign you as a reviewer and start the review issue, but feel free to start when you are back from holidays.

**Comment by cMadan** [comment]
@whedon add @anki-xyz as reviewer

**Comment by whedon** [comment]
OK, @anki-xyz is now a reviewer

**Comment by cMadan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3632.
