### ISSUE TITLE
[PRE REVIEW]: regioncode: Convert Region Names and Division Codes of China Over Years

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3561]
**Submitting author:** @GohUnTsuan  (<a href="http://orcid.org/0000-0002-9354-2313">Wenquan Wu</a>)
**Repository:** <a href="https://github.com/sammo3182/regioncode" target ="_blank">https://github.com/sammo3182/regioncode</a>
**Version:** 0.1.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/403558b309b939530915c028cc67615f/status.svg)](https://joss.theoj.org/papers/403558b309b939530915c028cc67615f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/403558b309b939530915c028cc67615f"><img src="https://joss.theoj.org/papers/403558b309b939530915c028cc67615f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/403558b309b939530915c028cc67615f/status.svg)](https://joss.theoj.org/papers/403558b309b939530915c028cc67615f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @GohUnTsuan . **Currently, there isn't an JOSS editor assigned** to your paper.

@GohUnTsuan  if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00848 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 942

**Comment by Kevin-Mattheus-Moerman** [comment]
@GohUnTsuan thanks for this submission to JOSS. Given the small size of this submission I've flagged it for additional scope review by our editorial board. In particular since the core functionality appears to captured by by ~350 lines of R and ~266 lines of JavaScript. This additional scope review is customary for submissions of this size ([see our guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)), and should take about a week.

**Comment by arfon** [comment]
@GohUnTsuan - thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
