### ISSUE TITLE
[PRE REVIEW]: The Neuroimaging Data Model (NIDM) Linear Regression Tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3562]
**Submitting author:** @AKUMAR0019 (<a href="http://orcid.org/0000-0001-8076-7620">Ashmita Kumar</a>)
**Repository:** <a href="https://github.com/AKUMAR0019/PyNIDM" target ="_blank">https://github.com/AKUMAR0019/PyNIDM</a>
**Version:** v.3.8.2
**Editor:** @osorensen
**Reviewers:** @htwangtw, @robbisg
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/194b71c9943d2550be0df98ce62373df/status.svg)](https://joss.theoj.org/papers/194b71c9943d2550be0df98ce62373df)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/194b71c9943d2550be0df98ce62373df"><img src="https://joss.theoj.org/papers/194b71c9943d2550be0df98ce62373df/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/194b71c9943d2550be0df98ce62373df/status.svg)](https://joss.theoj.org/papers/194b71c9943d2550be0df98ce62373df)
```

**Author instructions**

Thanks for submitting your paper to JOSS @AKUMAR0019. **Currently, there isn't an JOSS editor assigned** to your paper.

@AKUMAR0019 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1611

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (485.6 files/s, 156703.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          75           2759           4099          10589
JavaScript                       8           2166           2178           8618
CSS                              4            323             42           1026
reStructuredText                 3            416            672            992
HTML                             3            340              6            543
TeX                              1             21              0            389
YAML                             4              8              2            349
Markdown                         6             41              0            115
DOS Batch                        1              8              1             27
Dockerfile                       1             12              0             26
Bourne Shell                     4              4             17             10
make                             1              4              6             10
-------------------------------------------------------------------------------
SUM:                           111           6102           7023          22694
-------------------------------------------------------------------------------


Statistical information for the repository 'eda0f32c87ed35d77a7a9abd' was
gathered on 2021/08/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
AKUMAR0019                      52          5086           3571           15.10
Al                               2           326             39            0.64
Al Crowely                       2           451            144            1.04
Al Crowley                      27          4134            958            8.88
Ashmita Kumar                   16          1615            329            3.39
David Keator                   295         28591           7923           63.69
Dorota Jarecka                  25           436            971            2.45
Michael Hanke                    1            19             12            0.05
Nazek Queder                     1             1              1            0.00
Sanu Ann                         6          2380            113            4.35
Satrajit Ghosh                   5            75             23            0.17
Tom Gillespie                    1             2              1            0.01
Tristan Glatard                  5            65              7            0.13
dorota                           1             4              3            0.01
maxbachmann                      1             2              2            0.01
natachaperez                     1            45              2            0.08
tiborauer                        1             2              2            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
AKUMAR0019                 3082           60.6          1.5                6.91
Al                           94           28.8         20.9                1.06
Al Crowley                 3661           88.6         15.5                7.27
David Keator              20815           72.8         31.7               20.12
Dorota Jarecka              346           79.4         44.7               12.72
Sanu Ann                   2297           96.5         38.0               10.19
Satrajit Ghosh               54           72.0         43.5               11.11
Tristan Glatard              26           40.0         45.3               23.08
dorota                        4          100.0         35.4               25.00
tiborauer                     2          100.0         23.1                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1038/sdata.2016.102 may be a valid DOI for title: Sharing brain mapping statistical results with the neuroimaging data model
- 10.1016/j.neuroimage.2013.05.094 may be a valid DOI for title: Towards structured sharing of raw and derived neuroimaging data across existing resources

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03562/joss.03562/10.21105.joss.03562.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03562/joss.03562/10.21105.joss.03562.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@AKUMAR0019 Thanks for this submission to JOSS. I will be reviewing this work for scope and will look for a handling editor. In the mean time can you check those DOI's :point_up:

**Comment by Kevin-Mattheus-Moerman** [comment]
@emdupre this looks like something you might be able to handle but I have `waitlisted` this submission for now since you seem to be at capacity in terms of handling submission. Let me know if once you available this is something you could help with. Thanks.

**Comment by AKUMAR0019** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03562/joss.03562/10.21105.joss.03562.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03562/joss.03562/10.21105.joss.03562.pdf) :page_facing_up: :point_left:

**Comment by AKUMAR0019** [comment]
> @AKUMAR0019 Thanks for this submission to JOSS. I will be reviewing this work for scope and will look for a handling editor. In the mean time can you check those DOI's ☝️.
> 
> You can call the following to update the paper:
> `whedon generate pdf`

Thank you so much! Those DOIs were correct, and I've had whedon update the paper.

**Comment by AKUMAR0019** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by AKUMAR0019** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1038/sdata.2016.102 may be a valid DOI for title: Sharing brain mapping statistical results with the neuroimaging data model
- 10.1016/j.neuroimage.2013.05.094 may be a valid DOI for title: Towards structured sharing of raw and derived neuroimaging data across existing resources

INVALID DOIs

- None
```

**Comment by AKUMAR0019** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1038/sdata.2016.102 may be a valid DOI for title: Sharing brain mapping statistical results with the neuroimaging data model
- 10.1016/j.neuroimage.2013.05.094 may be a valid DOI for title: Towards structured sharing of raw and derived neuroimaging data across existing resources

INVALID DOIs

- None
```

**Comment by AKUMAR0019** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1038/sdata.2016.102 may be a valid DOI for title: Sharing brain mapping statistical results with the neuroimaging data model
- 10.1016/j.neuroimage.2013.05.094 may be a valid DOI for title: Towards structured sharing of raw and derived neuroimaging data across existing resources

INVALID DOIs

- None
```

**Comment by AKUMAR0019** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "month" (NAME) [#<BibTeX::Bibliography data=[9]>, "@", #<BibTeX::Entry >, {:title=>["Towards structured sharing of raw and derived neuroimaging data across existing resources"], :author=>["Keator, D B and Helmer, K and Steffener, J and Turner, J A and Van Erp, T G M and Gadde, S and Ashish, N and Burns, G A and Nichols, B N"], :abstract=>["Data sharing efforts increasingly contribute to the acceleration of scientific discovery. Neuroimaging data is accumulating in distributed domain-specific databases and there is currently no integrated access mechanism nor an accepted format for the critically important meta-data that is necessary for making use of the combined, available neuroimaging data. In this manuscript, we present work from the Derived Data Working Group, an open-access group sponsored by the Biomedical Informatics Research Network (BIRN) and the International Neuroimaging Coordinating Facility (INCF) focused on practical tools for distributed access to neuroimaging data. The working group develops models and tools facilitating the structured interchange of neuroimaging meta-data and is making progress towards a unified set of tools for such data and meta-data exchange. We report on the key components required for integrated access to raw and derived neuroimaging data as well as associated meta-data and provenance across neuroimaging resources. The components include (1) a structured terminology that provides semantic context to data, (2) a formal data model for neuroimaging with robust tracking of data provenance, (3) a web service-based application programming interface (API) that provides a consistent mechanism to access and query the data model, and (4) a provenance library that can be used for the extraction of provenance data by image analysts and imaging software developers. We believe that the framework and set of tools outlined in this manuscript have great potential for solving many of the issues the neuroimaging community faces when sharing raw and derived neuroimaging data across the various existing database systems for the purpose of accelerating scientific discovery."], :journal=>["Neuroimage"], :volume=>"82", :pages=>["647--661"], :doi=>["{10.1016/j.neuroimage.2013.05.094}"]}]

**Comment by AKUMAR0019** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "month" (NAME) [#<BibTeX::Bibliography data=[9]>, "@", #<BibTeX::Entry >, {:title=>["Towards structured sharing of raw and derived neuroimaging data across existing resources"], :author=>["Keator, D B and Helmer, K and Steffener, J and Turner, J A and Van Erp, T G M and Gadde, S and Ashish, N and Burns, G A and Nichols, B N"], :abstract=>["Data sharing efforts increasingly contribute to the acceleration of scientific discovery. Neuroimaging data is accumulating in distributed domain-specific databases and there is currently no integrated access mechanism nor an accepted format for the critically important meta-data that is necessary for making use of the combined, available neuroimaging data. In this manuscript, we present work from the Derived Data Working Group, an open-access group sponsored by the Biomedical Informatics Research Network (BIRN) and the International Neuroimaging Coordinating Facility (INCF) focused on practical tools for distributed access to neuroimaging data. The working group develops models and tools facilitating the structured interchange of neuroimaging meta-data and is making progress towards a unified set of tools for such data and meta-data exchange. We report on the key components required for integrated access to raw and derived neuroimaging data as well as associated meta-data and provenance across neuroimaging resources. The components include (1) a structured terminology that provides semantic context to data, (2) a formal data model for neuroimaging with robust tracking of data provenance, (3) a web service-based application programming interface (API) that provides a consistent mechanism to access and query the data model, and (4) a provenance library that can be used for the extraction of provenance data by image analysts and imaging software developers. We believe that the framework and set of tools outlined in this manuscript have great potential for solving many of the issues the neuroimaging community faces when sharing raw and derived neuroimaging data across the various existing database systems for the purpose of accelerating scientific discovery."], :journal=>["Neuroimage"], :volume=>"82", :pages=>["647--661"], :doi=>["10.1016/j.neuroimage.2013.05.094"]}]

**Comment by AKUMAR0019** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/sdata.2016.102 is OK
- 10.1016/j.neuroimage.2013.05.094 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by AKUMAR0019** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03562/joss.03562/10.21105.joss.03562.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03562/joss.03562/10.21105.joss.03562.pdf) :page_facing_up: :point_left:

**Comment by AKUMAR0019** [comment]
I'm sorry for all of the comments! I wasn't sure how to test the paper, so I used whedon.

**Comment by emdupre** [comment]
> @emdupre this looks like something you might be able to handle but I have waitlisted this submission for now since you seem to be at capacity in terms of handling submission. Let me know if once you available this is something you could help with. Thanks.

Thanks for the thought, @Kevin-Mattheus-Moerman ! I am at capacity right now but would be happy to take this on as things move off my docket in the next few weeks. I'll flag, though, that I work directly with one of the co-authors (Poline) and so have a COI on this submission. Let me know how you'd like to proceed !

**Comment by emdupre** [comment]
> I'm sorry for all of the comments! I wasn't sure how to test the paper, so I used whedon.

Just to note that there's a Whedon preview service, if you haven't seen it already ! https://whedon.theoj.org

**Comment by Kevin-Mattheus-Moerman** [comment]
@emdupre given your perceived COI I will look for a different editor for this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@fabian-s is this something your could help edit?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @fabian-s as editor

**Comment by whedon** [comment]
@fabian-s has been invited to edit this submission.

**Comment by fabian-s** [comment]
Sorry, I'd rather not -- I don't know Python, I don't do Neuroimaging.

**Comment by osorensen** [comment]
@Kevin-Mattheus-Moerman, I'd be happy to edit this submission.

**Comment by danielskatz** [comment]
@osorensen - feel free to assign this to yourself, using `@whedon assign me as editor` (and feel free to do this going forward when you see something that is of interest to you, as long as it's not undergoing scope review)

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
@AKUMAR0019, I'm now the editor for this submission. If you know of any potential reviewers, please mention their GitHub username in this thread (without the leading @).

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03562/joss.03562/10.21105.joss.03562.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03562/joss.03562/10.21105.joss.03562.pdf) :page_facing_up: :point_left:

**Comment by osorensen** [comment]
@kasbohm, @devDonnn, @sealhuang, @snastase, @dr-xenia, would any of you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by AKUMAR0019** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by AKUMAR0019** [comment]
> @AKUMAR0019, I'm now the editor for this submission. If you know of any potential reviewers, please mention their GitHub username in this thread (without the leading @).

Thank you @osorensen for agreeing to edit this paper!

**_A list of potential reviewers:_**
robbisg
htwangtw
SRSteinkamp
richford
62442katieb
a3sha2
peerherholz
Remi-Gau
matteomancini
dr-xenia
mwegrzyn
mih
JonathanReardon
sealhuang

**Comment by osorensen** [comment]
@robbisg @htwangtw @JonathanReardon would any of you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by htwangtw** [comment]
@osorensen I am interested but I am only available after the 17th of August. Is that okay?

**Comment by osorensen** [comment]
@htwangtw thanks, that's very ok!

**Comment by osorensen** [comment]
@whedon add @htwangtw as reviewer

**Comment by whedon** [comment]
OK, @htwangtw is now a reviewer

**Comment by robbisg** [comment]
I can review as well.

**Comment by osorensen** [comment]
@whedon add @robbisg as reviewer

**Comment by whedon** [comment]
OK, @robbisg is now a reviewer

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3578.

**Comment by kasbohm** [comment]
Late to the party, but let me know if still needed.

**Comment by osorensen** [comment]
@kasbohm , thanks, I have another submission which I'll ask you to review :-)
