### ISSUE TITLE
[PRE REVIEW]: GRChombo: An adaptable numerical relativity code for fundamental physics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3564]
**Submitting author:** @kaclough (<a href="http://orcid.org/0000-0001-8841-1522">Katy Clough</a>)
**Repository:** <a href="https://github.com/GRChombo/GRChombo" target ="_blank">https://github.com/GRChombo/GRChombo</a>
**Version:** v1.0.0
**Editor:** @rkurchin
**Reviewers:** @sbozzolo, @rashti-alireza
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/af52e7f1b7637bfa68818fde7c1a34de/status.svg)](https://joss.theoj.org/papers/af52e7f1b7637bfa68818fde7c1a34de)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/af52e7f1b7637bfa68818fde7c1a34de"><img src="https://joss.theoj.org/papers/af52e7f1b7637bfa68818fde7c1a34de/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/af52e7f1b7637bfa68818fde7c1a34de/status.svg)](https://joss.theoj.org/papers/af52e7f1b7637bfa68818fde7c1a34de)
```

**Author instructions**

Thanks for submitting your paper to JOSS @kaclough. **Currently, there isn't an JOSS editor assigned** to your paper.

@kaclough if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3564 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch feature/joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3564 with the following error: 
```
 [WARNING] Could not convert image '/tmp/tex2pdf.-910049fd98066eeb/11175fff957ea55b1b4fc79f2f159eec4a610f19.svg': check that rsvg-convert is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
[WARNING] Could not convert image '/tmp/tex2pdf.-910049fd98066eeb/5db88c1ff9382018bf57ef54739d009f5b49ead3.svg': check that rsvg-convert is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.-910049fd98066e
eb/11175fff957ea55b1b4fc79f2f159eec4a610f19.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.698 ...5fff957ea55b1b4fc79f2f159eec4a610f19.svg}

Looks like we failed to compile the PDF

```

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you advise how to fix this compilation error :point_up_2:

**Comment by danielskatz** [comment]
My guess, from the error message, is that there's a problem with an svg image - since I see 2 such errors, and I see two svg images in https://github.com/GRChombo/GRChombo/tree/feature/joss_paper/figures, my thought is that JOSS doesn't handle svg images and that these images could be converted to pngs by the authors.

**Comment by mirenradia** [comment]
This is rather strange since the [GitHub action run](https://github.com/GRChombo/GRChombo/actions/runs/1093660595) to build a preview of the paper passed successfully as well as the docker image. Is it possible to make these consistent with the actual PDF generator?

For now, I will convert the SVG images to PNGs.

**Comment by mirenradia** [comment]
> For now, I will convert the SVG images to PNGs.

Done.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch feature/joss_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch feature/joss_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03564/joss.03564/10.21105.joss.03564.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03564/joss.03564/10.21105.joss.03564.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@eloisabentivegna this sounds like your cup of tea, once you are available, do you think you can help edit this submission? Thanks.

**Comment by arfon** [comment]
@whedon invite @rkurchin as editor

:wave: @rkurchin – I realize this is somewhat left-field for you but would you be willing to edit this submission for us? Our ideal editor (@eloisabentivegna has just gone out on maternity leave 👶).

**Comment by whedon** [comment]
@rkurchin has been invited to edit this submission.

**Comment by rkurchin** [comment]
@whedon assign me as editor

Haha, sure, as long as we have some editors closer to this area than I am, it should be okay!

**Comment by whedon** [comment]
OK, the editor is @rkurchin

**Comment by rkurchin** [comment]
👋  Hi @KAClough, I'll be editing this submission! As noted above in the first comment, please do let us know if you have any potential reviewers in mind (don't tag them with @, just post the GitHub username in plaintext).

**Comment by KAClough** [comment]
Hi @rkurchin, thanks for being our editor! I will have a think about reviewers and let you know some suggestions shortly.

**Comment by rkurchin** [comment]
Hi again @KAClough, just checking in and reminding about this! If you don't have particular suggestions, I can take my best guess and invite folks, but you know your own work best. :)

**Comment by KAClough** [comment]
Hi @rkurchin sorry for being slow - looking at the spreadsheet of reviewers I think the top ones would be shreyasbapat or sbozzolo, if they'd be willing to do it. If not I can take another look - the key elements are probably the C/C++ nature of the code, and an understanding of numerical relativity, although cosmological or hydrodynamical simulations obey similar equations so that would be sufficient too.

**Comment by rkurchin** [comment]
👋 Hi there @shreyasbapat and @sbozzolo, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Please feel free to let me know if you have any questions about the process.

**Comment by Sbozzolo** [comment]
Hi @rkurchin, this seems like a great submission for my expertise. (This would be my first review for JOSS.)

**Comment by rkurchin** [comment]
@whedon add @sbozzolo as reviewer

**Comment by whedon** [comment]
OK, @sbozzolo is now a reviewer

**Comment by rkurchin** [comment]
👋 @adam-m-jcbs, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Please feel free to let me know if you have any questions about the process.

**Comment by rkurchin** [comment]
👋 @rashti-alireza, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Please feel free to let me know if you have any questions about the process.

**Comment by rashti-alireza** [comment]
Hi Rachel,
Sure.
Please let me know how I can access the code and the pertinent information.
Thanks.


*Kind regards,*
*Alireza Rashti.*

**Comment by rkurchin** [comment]
@whedon add @rashti-alireza as reviewer

**Comment by whedon** [comment]
OK, @rashti-alireza is now a reviewer

**Comment by rkurchin** [comment]
@rashti-alireza, now that we have two reviewers, I'll start the review process, which will open up a new GitHub issue that will have a checklist for both you and @Sbozzolo to fill out that should also help guide you through the review process expectations. If anything is unclear, feel free to comment over there with questions!

**Comment by rkurchin** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3703.
