### ISSUE TITLE
[PRE REVIEW]: NCBITaxonomy.jl - rapid biological names finding and reconciliation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3565]
**Submitting author:** @tpoisot (<a href="http://orcid.org/0000-0002-0735-5184">Timothée Poisot</a>)
**Repository:** <a href="https://github.com/EcoJulia/NCBITaxonomy.jl" target ="_blank">https://github.com/EcoJulia/NCBITaxonomy.jl</a>
**Version:** v0.2.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a8f488d7c2348763735cd545e7d0604c/status.svg)](https://joss.theoj.org/papers/a8f488d7c2348763735cd545e7d0604c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a8f488d7c2348763735cd545e7d0604c"><img src="https://joss.theoj.org/papers/a8f488d7c2348763735cd545e7d0604c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a8f488d7c2348763735cd545e7d0604c/status.svg)](https://joss.theoj.org/papers/a8f488d7c2348763735cd545e7d0604c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tpoisot. **Currently, there isn't an JOSS editor assigned** to your paper.

@tpoisot if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 70

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1101/2021.01.14.426572 is OK
- 10.1111/2041-210X.13440 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (1830.3 files/s, 79095.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           20            166             23            799
Markdown                        13            152              0            500
YAML                             4              6              0             98
TOML                             3              2              0             30
TeX                              1              4              0             21
JSON                             1              0              0             14
-------------------------------------------------------------------------------
SUM:                            42            330             23           1462
-------------------------------------------------------------------------------


Statistical information for the repository 'e1544d48fadc72194afe8523' was
gathered on 2021/08/04.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03565/joss.03565/10.21105.joss.03565.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03565/joss.03565/10.21105.joss.03565.pdf) :page_facing_up: :point_left:

**Comment by tpoisot** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by tpoisot** [comment]
@whedon generate pdf from branch joss/initial

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03565/joss.03565/10.21105.joss.03565.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03565/joss.03565/10.21105.joss.03565.pdf) :page_facing_up: :point_left:

**Comment by tpoisot** [comment]
**Ed. note** the "Download article proof" link is the wrong version, but "View article proof..." is :heavy_check_mark: 

**Possible reviewers**
- nicksisco1932
- qpmnguyen
- sckott

**Comment by Kevin-Mattheus-Moerman** [comment]
> Ed. note the "Download article proof" link is the wrong version, but "View article proof..." is 
@tpoisot Can you explain the difference. They should be the same, and I have not noticed a difference. If this is true I had to get our tech support to have a look at this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@tpoisot I have flagged this submission for additional scope review, to ensure it conforms to our ["substantial scholarly effort criteria"](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This is typical for submissions of this size, i.e. where the core functionality appears to be captured by <= 1000 lines a of code.

**Comment by tpoisot** [comment]
> > Ed. note the "Download article proof" link is the wrong version, but "View article proof..." is 
> 
> @tpoisot Can you explain the difference. They should be the same, and I have not noticed a difference. If this is true I had to get our tech support to have a look at this. 

This might have been a cache issue, they're the same on my end now too

**Comment by tpoisot** [comment]
> @tpoisot I have flagged this submission for additional scope review, to ensure it conforms to our ["substantial scholarly effort criteria"](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This is typical for submissions of this size, i.e. where the core functionality appears to be captured by <= 1000 lines of code. This scope review should take about a week.

Can you give some more details as to what the review criteria are?

**Comment by danielskatz** [comment]
They are in the link you quoted.

**Comment by tpoisot** [comment]
@danielskatz I was wondering about the specific info you're looking for when submissions are under 1000 sloc (out of curiosity)

**Comment by danielskatz** [comment]
See the other bullets in that list

**Comment by arfon** [comment]
@tpoisot – Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by whedon** [comment]
Paper rejected.

**Comment by tpoisot** [comment]
@arfon we would like to appeal this decision - what is the process?

**Comment by tpoisot** [comment]
@arfon - this software has received improved functionalities in the last year, and notably been used in two massive data crunching projects that I think showcase its usefulness. Is there a possibility to resubmit it? We have already updated the text to argue why this isn't a minor utility, but rather a potential cornerstone of projects where a lots of names need to cleaned under different scenarios of ambiguities/issues.

**Comment by tpoisot** [comment]
@arfon - just a bump, would appreciate a response on this to decide whether to resubmit at JOSS or somewhere else
