### ISSUE TITLE
[PRE REVIEW]: eyecite: A tool for parsing legal citations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3566]
**Submitting author:** @mattdahl (<a href="http://orcid.org/0000-0001-8437-1455">Matthew Dahl</a>)
**Repository:** <a href="https://github.com/freelawproject/eyecite" target ="_blank">https://github.com/freelawproject/eyecite</a>
**Version:** v2.2.0
**Editor:** @danielskatz
**Reviewers:** @cmaimone, @step21
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764/status.svg)](https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764"><img src="https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764/status.svg)](https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mattdahl. **Currently, there isn't an JOSS editor assigned** to your paper.

@mattdahl if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (311.0 files/s, 57134.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          18            478           1039           2564
reStructuredText                 1            147              7            363
YAML                             5             29              3            150
Markdown                         2             29              0             72
TOML                             1             10              5             64
-------------------------------------------------------------------------------
SUM:                            27            693           1054           3213
-------------------------------------------------------------------------------


Statistical information for the repository '522322a7a6adbed019dbf248' was
gathered on 2021/08/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Faiz Surani                      5           195             30            1.87
Jack Cushman                    49          5495           3728           76.48
Matt Dahl                       12          2229             80           19.15
Michael Lissner                 14            48            127            1.45
Mike Lissner                     1            18              0            0.15
vvilliam                         8            83             27            0.91

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Faiz Surani                 130           66.7          0.6               20.00
Jack Cushman               3222           58.6          1.8               16.36
Matt Dahl                   703           31.5          3.3               29.30
Michael Lissner              21           43.8          3.7                4.76
vvilliam                      5            6.0          4.6                0.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3566 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by mattdahl** [comment]
Please be advised that the paper is not in our main branch; you can find it here instead: https://github.com/freelawproject/eyecite/tree/joss-paper/joss

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03566/joss.03566/10.21105.joss.03566.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03566/joss.03566/10.21105.joss.03566.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@mattdahl see above that is how you can also generate/update the paper from that branch later if needed :point_up_2:

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielskatz given your work on citations for software / software for citations, would this be something you could help edit once you are available?

**Comment by Kevin-Mattheus-Moerman** [comment]
@mattdahl I have added the `waitlisted` label to this submission just now because all of our editors in this domain are currently not available (handling many other submissions). We will assign one as soon as one becomes available. Thanks for your patience.

**Comment by danielskatz** [comment]
@Kevin-Mattheus-Moerman - ok, while this isn't exactly my area, I might be closer than any of our other editors

**Comment by danielskatz** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @mattdahl - Can you suggest some potential reviewers by mentioning them here in this thread, ideally by github username if known (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by mattdahl** [comment]
Hi @danielskatz, here are a couple of people from that spreadsheet that I think might be suitable based of their listed areas of expertise:

- step21 (`law, computable law,  language design, logic, knowledge management, document management, general data gathering and analysis`)
- cmaimone (Python, `Social science, text analysis, general data manipulation, data visualization`)
- pmyteh (Python, `Computational social science, especially focused towards communication and political science, and particularly packages focused on text analysis`)
- cjbarrie (Python, `Social science, APIs, text analysis`)
- rlskoeser (Python, `web applications, data modeling and munging, text indexing and parsing, digital humanities`)

Please let us know if you'd like us to generate more candidates. Thanks!

**Comment by danielskatz** [comment]
@step21 - Would you be willing to review this JOSS submission?

**Comment by danielskatz** [comment]
@cmaimone - I know you are currently reviewing another JOSS submission, but would you also be willing to review this one?

**Comment by danielskatz** [comment]
👋 @pmyteh & @cjbarrie - would either or both of you be available to review this JOSS submission?

**Comment by pmyteh** [comment]
I'm sorry - I'm overloaded ATM so must decline.

**Comment by danielskatz** [comment]
no worries @pmyteh - thanks for getting back to me

**Comment by cmaimone** [comment]
I can review it - I think my other review is close to done

**Comment by danielskatz** [comment]
Thanks very much @cmaimone - I'll add you, and once we get another reviewer, we'll get started on the review

**Comment by danielskatz** [comment]
@whedon assign @cmaimone as reviewer

**Comment by whedon** [comment]
OK, @cmaimone is now a reviewer

**Comment by step21** [comment]
In case you need more reviewers, I can review from 18th onward.

**Comment by danielskatz** [comment]
@step21 - thanks very much; we do need a second reviewer.  I'll assign you and we can get started, though please don't feel you have to start until you are ready.

**Comment by danielskatz** [comment]
@whedon add @step21 as reviewer

**Comment by whedon** [comment]
OK, @step21 is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3617.
