### ISSUE TITLE
[REVIEW]: The MarINvaders Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3575]
**Submitting author:** @rlonka (<a href="http://orcid.org/0000-0002-5815-8682">Radek Lonka</a>)
**Repository:** <a href="https://gitlab.com/marinvaders/marinvaders" target ="_blank">https://gitlab.com/marinvaders/marinvaders</a>
**Version:** 0.3.2
**Editor:** @osorensen
**Reviewer:** @callumrollo, @ethanwhite
**Archive:** <a href="https://doi.org/10.5281/zenodo.4621392" target="_blank">10.5281/zenodo.4621392</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b/status.svg)](https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b"><img src="https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b/status.svg)](https://joss.theoj.org/papers/c58c4413c262a95ff649ec789c53942b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/marinvaders/marinvaders" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@callumrollo & @ethanwhite, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @osorensen know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/marinvaders/marinvaders">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] #3577
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/marinvaders/marinvaders">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rlonka) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @callumrollo, @ethanwhite it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 920

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (257.2 files/s, 36431.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          11            315            513           1128
Markdown                        11            281              0            491
XML                              3              1              0            300
TeX                              1             12              0            136
YAML                             3             13              0            118
Jupyter Notebook                 1              0            922             20
-------------------------------------------------------------------------------
SUM:                            30            622           1435           2193
-------------------------------------------------------------------------------


Statistical information for the repository 'bdf8fee9be06fb5702096a2d' was
gathered on 2021/08/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Konstantin Stadler              66          2655           2016           21.04
Radek Lonka                    138         12329           5201           78.95
Radek lonka                      1             1              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Konstantin Stadler         1121           42.2          1.7                4.28
Radek Lonka                 835            6.8          5.4               13.89
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03575/joss.03575/10.21105.joss.03575.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03575/joss.03575/10.21105.joss.03575.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3391/ai.2014.9.4.01 is OK
- 10.3389/fmars.2014.00032 is OK
- 10.1890/070064 is OK
- 10.1038/ncomms14435 is OK
- 10.1111/gcb.15333 is OK
- 10.1641/B570707 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by callumrollo** [comment]
Authorship: Both Radek Lonka and Konstantin Stadler have contributed significantly to the codebase. The contribution of Francesca Verones to this submission is unclear. Could the lead author please clarify this?

**Comment by rlonka** [comment]
> Authorship: Both Radek Lonka and Konstantin Stadler have contributed significantly to the codebase. The contribution of Francesca Verones to this submission is unclear. Could the lead author please clarify this?

Francesca Verones, as PI of the ATLANTIS project, had the idea of creating such a package. She has the overall scientific lead of the marinvaders project. She identified the relevant data sources and did integration and usability tests of the overall package, in particular in regard to scientific soundness.

**Comment by callumrollo** [comment]
Issue with installation guidelines, conda command does not work:

`conda update -c conda-forge MarINvaders`

I think this should be 

`conda install -c conda-forge MarINvaders`

**Comment by callumrollo** [comment]
Comments on software paper:

- There is no discussion of similar software, is the first of it's kind? Are there any software packages with functionality that overlaps with marinvaders?
- Line 7 "Alien species are considered the most difficult to reverse pressure" I'm not sure what this means? Maybe "Ecosystem pressures from alien species are considered the most difficult to reverse?"
- Line 11~~and since then became~~ >> and has since become
- Line 16 ~~they~~ >> the databases
- Line 41 as *an* ecoregion level
- Line 60  ~~an intersect~~ >> an intersection, or a combination perhaps?
- Line 66 where in the source code are these manual matchings documented?
- Line 68 *results*
- Line 74 *assesses*
- Dead hyperlink in reference "Ecosystems and human well-being: synthesis"
- Malformed hyperlink in "World register of marine specie"

**Comment by ethanwhite** [comment]
Overall this software paper looks great and appropriate for JOSS. Nice work @rlonka!

In addition to @callumrollo's comments, all of which I agree with, I have the following additions:

## Installation

* I think there is a missing dependency for the conda installation. When I installed into a fresh conda environment and then tried to load the package I received the following error. `ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.`. Manually installing `openpyxl` solved the issue.

## Documentation

* Link to "example/tutorial notebook" on the main documentation page currently 404s

## Software paper

* The summary would benefit from a few additional sentences describing the high-level functionality of the software. It currently focuses on the need, but never really discusses what the software does.
* An optional note for the author's consideration on terminology. My impression (as a non-expert) is that at least in the US there has been a shift away from describing species as "alien" and towards describing them as "non-native" or "non-indigenous" (see some discussion here https://www.smithsonianmag.com/science-nature/why-scientists-are-starting-rethink-how-they-talk-about-alien-species-180967761/). The authors may want to consider a similar shift in language.

**Comment by osorensen** [comment]
Thanks to @ethanwhite and @callumrollo for responding so quickly! @rlonka, please address the issues raised by the reviewers and report on the progress in this thread.

**Comment by konstantinstadler** [comment]
@ethanwhite : many thanks for the update on the non-native vs alien terminology. 
We discussed the issue among all authors and would prefer to keep the alien terminology
as this is the term used both in WoRMS (e.g. https://www.marinespecies.org/aphia.php?p=taxdetails&id=145721#distributions), WRiMS (http://www.marinespecies.org/introduced/terminology.php) and Molnar which all build the backbone of our database.

**Comment by ethanwhite** [comment]
> We discussed the issue among all authors and would prefer to keep the alien terminology

Sounds good. Like I said I'm definitely not an expert here so just wanted to draw your attention to the discussion so you could consider it.

**Comment by konstantinstadler** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03575/joss.03575/10.21105.joss.03575.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03575/joss.03575/10.21105.joss.03575.pdf) :page_facing_up: :point_left:

**Comment by callumrollo** [comment]
Looks great! Thanks @konstantinstadler . A few small typos I spotted:

- 9 and *are* expected
- 20 This allows *the user* to
- 43 available *that* automatically
- 44 *harmonizes*

The authors have addressed all my concerns for this project. I am happy to accept it @osorensen

**Comment by ethanwhite** [comment]
I concur with @callumrollo. Great work @konstantinstadler! All of my concerns have been addressed and I support accepted of this paper.

**Comment by konstantinstadler** [comment]
Hi. Thanks, we were just preparing a longer reply thanking you for the great review - apparently a bit to slow 😉.

We will fix the remaining spelling mistakes ASAP  (the missing module for install via conda - openpxyl - is fixed now in 0.3.2).

Thanks again for helping to improve the module and article!

**Comment by rlonka** [comment]
Thanks @ethanwhite @callumrollo and @osorensen for your time and valuable comments which helped us to improve the work!

**Comment by konstantinstadler** [comment]
Fixed spelling:
@whedon generate pdf

**Comment by konstantinstadler** [comment]
@osorensen :  Version 0.3.2 is now also archived on Zenodo:
https://doi.org/10.5281/zenodo.4621392

**Comment by konstantinstadler** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03575/joss.03575/10.21105.joss.03575.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03575/joss.03575/10.21105.joss.03575.pdf) :page_facing_up: :point_left:

**Comment by osorensen** [comment]
@konstantinstadler, thanks again for this submission to JOSS. The paper is very well written, but I noticed one small typo when reading through it:

- Line 77: change "a overview" to "an overview".

**Comment by osorensen** [comment]
@whedon set 10.5281/zenodo.4621392 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4621392" target="_blank">10.5281/zenodo.4621392</a> is the archive.

**Comment by osorensen** [comment]
@whedon set 0.3.2 as version

**Comment by whedon** [comment]
OK. 0.3.2 is the version.

**Comment by osorensen** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3391/ai.2014.9.4.01 is OK
- 10.3389/fmars.2014.00032 is OK
- 10.1890/070064 is OK
- 10.1038/ncomms14435 is OK
- 10.1111/gcb.15333 is OK
- 10.1641/B570707 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by konstantinstadler** [comment]
> @konstantinstadler and @rlonka, thanks again for this submission to JOSS. The paper is very well written, but I noticed one small typo when reading through it:
> 
>     * Line 77: change "a overview" to "an overview".

Thanks! Still did not find a good grammar checker for vim ;-)

Anyway, fixed now

**Comment by konstantinstadler** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03575/joss.03575/10.21105.joss.03575.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03575/joss.03575/10.21105.joss.03575.pdf) :page_facing_up: :point_left:

**Comment by osorensen** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3391/ai.2014.9.4.01 is OK
- 10.3389/fmars.2014.00032 is OK
- 10.1890/070064 is OK
- 10.1038/ncomms14435 is OK
- 10.1111/gcb.15333 is OK
- 10.1641/B570707 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3575 with the following error: 
```
 
```

**Comment by osorensen** [comment]
Thank you very much @callumrollo and @ethanwhite for you reviewing for JOSS!

**Comment by osorensen** [comment]
> PDF failed to compile for issue #3575 with the following error:
> 
> ```
>  
> ```

@openjournals/jose-eics, running recommend-accept generated this empty error message, so I'll ask whedon to generate pdf proofs.

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03575/joss.03575/10.21105.joss.03575.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03575/joss.03575/10.21105.joss.03575.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Ok everything looks good!

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1428823998452862980) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2517
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03575](https://doi.org/10.21105/joss.03575)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @rlonka! Many thanks to editor @osorensen and reviewers @callumrollo and @ethanwhite for your hard work, time, and expertise!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03575/status.svg)](https://doi.org/10.21105/joss.03575)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03575">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03575/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03575/status.svg
   :target: https://doi.org/10.21105/joss.03575
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03575/status.svg)](https://doi.org/10.21105/joss.03575)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by konstantinstadler** [comment]
Fantastic. Was a pleasant experience again. Many thanks to all involved!
