### ISSUE TITLE
[PRE REVIEW]: Nempy: A Python package for modelling the Australian National Electricity Market dispatch procedure

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3576]
**Submitting author:** @nick-gorman (<a href="http://orcid.org/0000-0002-6505-761X">Nicholas Gorman</a>)
**Repository:** <a href="https://github.com/UNSW-CEEM/nempy" target ="_blank">https://github.com/UNSW-CEEM/nempy</a>
**Version:** v1.0.1
**Editor:** @timtroendle
**Reviewers:** @noah80, @robinroche
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/70ac80e2603b4eef6157d9d783ac0f8e/status.svg)](https://joss.theoj.org/papers/70ac80e2603b4eef6157d9d783ac0f8e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/70ac80e2603b4eef6157d9d783ac0f8e"><img src="https://joss.theoj.org/papers/70ac80e2603b4eef6157d9d783ac0f8e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/70ac80e2603b4eef6157d9d783ac0f8e/status.svg)](https://joss.theoj.org/papers/70ac80e2603b4eef6157d9d783ac0f8e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nick-gorman. **Currently, there isn't an JOSS editor assigned** to your paper.

@nick-gorman if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3576 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.57 s (112.4 files/s, 204530.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              4              0          93528
Python                          46           3347           7224           5812
SVG                              2              0              0           5223
HTML                             1             91              0            365
Markdown                         1             47              0            264
reStructuredText                 8             98             92            201
YAML                             1              0              2             51
DOS Batch                        1              8              1             26
make                             1              4              7              9
INI                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            64           3599           7326         105482
-------------------------------------------------------------------------------


Statistical information for the repository '467f795aa49a818c50452716' was
gathered on 2021/08/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ben Elliston                     1            10             39            0.10
Nicholas Gorman                  2           459            150            1.23
Nick                            26          8124           6965           30.38
Nick Gorman                      2           356            505            1.73
nick-gorman                    111         24034           9032           66.57

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ben Elliston                  3           30.0          1.2                0.00
nick-gorman               16380           68.2          3.1                6.53
```

**Comment by nick-gorman** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03576/joss.03576/10.21105.joss.03576.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03576/joss.03576/10.21105.joss.03576.pdf) :page_facing_up: :point_left:

**Comment by nick-gorman** [comment]
Some potentially relevant reviewers are: mewilhel, noah80, willu47, milicag, ralphevins, blthayer, robinroche

**Comment by arfon** [comment]
@nick-gorman - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by arfon** [comment]
@whedon invite @timtroendle as editor

:wave: @timtroendle – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@timtroendle has been invited to edit this submission.

**Comment by timtroendle** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @timtroendle

**Comment by timtroendle** [comment]
Hi @nick-gorman, I will start looking for reviewers. Thank you for you suggestions! You will be notified once we start the review.

**Comment by timtroendle** [comment]
:wave: @noah80, @mewilhel & @robinroche, would any of you be willing to review this submission for JOSS?

**Comment by noah80** [comment]
Yeah, I can review this.

**Comment by robinroche** [comment]
Yes, I can review the submission but I will need a few weeks.

**Comment by timtroendle** [comment]
That's great, thanks @noah80 and @robinroche . We are still in reduced service mode in which we ask reviewers to complete their review within six weeks.

**Comment by timtroendle** [comment]
@whedon add @noah80 as reviewer

**Comment by whedon** [comment]
OK, @noah80 is now a reviewer

**Comment by timtroendle** [comment]
@whedon add @robinroche as reviewer

**Comment by whedon** [comment]
OK, @robinroche is now a reviewer

**Comment by timtroendle** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3596.
