### ISSUE TITLE
[PRE REVIEW]: iheatmapr: Interactive complex heatmaps in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#358]
**Submitting author:** @AliciaSchep (<a href="http://orcid.org/0000-0002-3915-0618">Alicia Schep</a>)
**Repository:** <a href="https://github.com/ropensci/iheatmapr" target ="_blank">https://github.com/ropensci/iheatmapr</a>
**Version:** v0.3.2
**Editor:** @karthik
**Reviewer:** @rlbarter

**Author instructions**

Thanks for submitting your paper to JOSS @AliciaSchep. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@AliciaSchep if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @karthik - the submitting author suggested you as an editor.

**Comment by karthik** [comment]
Sure, I'm happy to edit.

**Comment by karthik** [comment]
@whedon assign @karthik as editor

**Comment by whedon** [comment]
OK, the editor is @karthik

**Comment by karthik** [comment]
👋  @AliciaSchep. Thanks for the submission! I'm reaching out to a few reviewers now and will update the thread and soon as I am able. Stay tuned. 📻

**Comment by karthik** [comment]
@whedon assign @rlbarter as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rlbarter

**Comment by karthik** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/359. Feel free to close this issue now!
