### ISSUE TITLE
[PRE REVIEW]: Methodnet: Formal Semantic Representations of Methods in Automatic Control

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3580]
**Submitting author:** @Rojetto (<a href="http://orcid.org/0000-0003-0031-538X">Robert Heedt</a>)
**Repository:** <a href="https://github.com/TUD-RST/methodnet/" target ="_blank">https://github.com/TUD-RST/methodnet/</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6db7addb57c6aa532fd0608f29683992/status.svg)](https://joss.theoj.org/papers/6db7addb57c6aa532fd0608f29683992)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6db7addb57c6aa532fd0608f29683992"><img src="https://joss.theoj.org/papers/6db7addb57c6aa532fd0608f29683992/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6db7addb57c6aa532fd0608f29683992/status.svg)](https://joss.theoj.org/papers/6db7addb57c6aa532fd0608f29683992)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Rojetto. **Currently, there isn't an JOSS editor assigned** to your paper.

@Rojetto if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 465

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03580/joss.03580/10.21105.joss.03580.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03580/joss.03580/10.21105.joss.03580.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ICSTCC50638.2020.9259657 is OK
- 10.1007/s13218-020-00678-3 is OK
- 10.21105/joss.01182 is OK

MISSING DOIs

- 10.1017/s095679681300018x may be a valid DOI for title: Idris, a General-Purpose Dependently Typed Programming Language: Design and Implementation
- 10.1007/978-3-642-04652-0_5 may be a valid DOI for title: Dependently Typed Programming in Agda
- 10.52846/stccj.2021.1.1.11 may be a valid DOI for title: Tool-based Support for the FAIR Principles for Control Theoretic Results: The "Automatic Control Knowledge Repository"
- 10.1016/j.artmed.2017.07.002 may be a valid DOI for title: Owlready: Ontology-oriented programming in Python with automatic classification and high level constructs for biomedical ontologies

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.27 s (35.4 files/s, 201598.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       2            882           4547         226097
CSS                              1             70             71          12248
SVG                              3              0              0           4893
JSON                             5              2              0           2348
YAML                             4             12              0           2134
Python                          15            319            171            885
TypeScript                       3             63             24            500
HTML                             3             45              2            206
TeX                              1             40              0            186
Markdown                         5             39              0            112
INI                              3             29              0             66
-------------------------------------------------------------------------------
SUM:                            45           1501           4815         249675
-------------------------------------------------------------------------------


Statistical information for the repository '0c75b8f157adbfd2acda2b1e' was
gathered on 2021/08/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Carsten Knoll                    3           634             11            0.23
Robert Heedt                    63        182376          95617           99.77

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Carsten Knoll               591           93.2          3.9               12.35
Robert Heedt             232310          127.4          5.9                2.01
```

**Comment by arfon** [comment]
@Rojetto – due to the relatively small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@Rojetto – thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
