### ISSUE TITLE
[PRE REVIEW]: AuditoryStimuli.jl: A Julia package for generating real-time auditory stimuli

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3582]
**Submitting author:** @rob-luke (<a href="http://orcid.org/0000-0002-4930-8351">Robert Luke</a>)
**Repository:** <a href="https://github.com/rob-luke/AuditoryStimuli.jl" target ="_blank">https://github.com/rob-luke/AuditoryStimuli.jl</a>
**Version:** v0.0.11
**Editor:** @bmcfee
**Reviewers:** @vahid-sb, @jongwook
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b91a016d27744caa7bce0ad558c177ba/status.svg)](https://joss.theoj.org/papers/b91a016d27744caa7bce0ad558c177ba)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b91a016d27744caa7bce0ad558c177ba"><img src="https://joss.theoj.org/papers/b91a016d27744caa7bce0ad558c177ba/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b91a016d27744caa7bce0ad558c177ba/status.svg)](https://joss.theoj.org/papers/b91a016d27744caa7bce0ad558c177ba)
```

**Author instructions**

Thanks for submitting your paper to JOSS @rob-luke. **Currently, there isn't an JOSS editor assigned** to your paper.

@rob-luke if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (1154.3 files/s, 77644.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           13            345             74           1029
Markdown                        12            178              0            457
YAML                             7              9              9            142
TOML                             2              4              0             40
-------------------------------------------------------------------------------
SUM:                            34            536             83           1668
-------------------------------------------------------------------------------


Statistical information for the repository 'cfb2199ca75b40d04a165589' was
gathered on 2021/08/06.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3582 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch manuscript

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch manuscript. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03582/joss.03582/10.21105.joss.03582.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03582/joss.03582/10.21105.joss.03582.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @bmcfee as editor

:wave: @bmcfee - would you be able to handle this submission for us?

**Comment by whedon** [comment]
@bmcfee has been invited to edit this submission.

**Comment by bmcfee** [comment]
:+1: sure, happy to!

**Comment by bmcfee** [comment]
@whedon assign @bmcfee as editor

**Comment by whedon** [comment]
OK, the editor is @bmcfee

**Comment by rob-luke** [comment]
Thanks @arfon and @bmcfee. I'm excited to go through this process together.

**Comment by bmcfee** [comment]
:wave: hi @rob-luke !  I'll be tracking down reviewers over the coming days.

**Comment by bmcfee** [comment]
@whedon add @vahid-sb as reviewer

**Comment by whedon** [comment]
OK, @vahid-sb is now a reviewer

**Comment by rob-luke** [comment]
Thanks for accepting to review @vahid-sb. I look forward to your feedback.

**Comment by vahid-sb** [comment]
Hi @rob-luke. My pleasure to go through your code and make any suggestions to improve the code and documentation, if I can. but please note that as I told @bmcfee, for work-related reasons, it might be a bit slow, but hopefully not too slow.

**Comment by rob-luke** [comment]
We are all volunteering our time for these open-source endeavours, I appreciate your effort, there is no rush from me.

**Comment by bmcfee** [comment]
Just chiming in here to say that I'm still working on finding another reviewer, but hope to have a positive response soon.

**Comment by rob-luke** [comment]
Thanks @bmcfee

**Comment by bmcfee** [comment]
@whedon add @jongwook as reviewer

**Comment by whedon** [comment]
OK, @jongwook is now a reviewer

**Comment by bmcfee** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3613.
