### ISSUE TITLE
[PRE REVIEW]: obscura: A modular C++ tool and library for the direct detection of (sub-GeV) dark matter via nuclear and electron recoils

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3583]
**Submitting author:** @temken (<a href="http://orcid.org/0000-0002-4251-2229">Timon Emken</a>)
**Repository:** <a href="https://github.com/temken/obscura" target ="_blank">https://github.com/temken/obscura</a>
**Version:** v0.1.1
**Editor:** @lucydot
**Reviewers:** @rafaelab @villaa
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9/status.svg)](https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9"><img src="https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9/status.svg)](https://joss.theoj.org/papers/fd8076268036956d3bf08193c4fc2db9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @temken. **Currently, there isn't an JOSS editor assigned** to your paper.

@temken if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1207

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (859.1 files/s, 123476.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             33            747            588           5969
C/C++ Header                    16            261            126            696
reStructuredText                14            486            502            513
CMake                            3             38             32            311
TeX                              1             26              0            215
Markdown                         3             60              0            131
YAML                             3             14             22             76
DOS Batch                        1              8              1             26
Python                           1             15             30             10
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            76           1659           1308           7956
-------------------------------------------------------------------------------


Statistical information for the repository '7563f745ed1678322e43eab0' was
gathered on 2021/08/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Timon Emken                    176         16450           8061          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Timon Emken                8442           51.3          8.4                8.81
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03583/joss.03583/10.21105.joss.03583.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03583/joss.03583/10.21105.joss.03583.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.physrep.2004.08.031 is OK
- 10.1038/s41586-018-0542-z is OK
- 10.1103/PhysRevResearch.2.033195 is OK
- 10.1103/PhysRevD.33.3495 is OK
- DOI:10.5281/zenodo.4559874 is OK
- 10.1103/PhysRevD.85.076007 is OK
- 10.1007/JHEP05(2016)046 is OK
- 10.1140/epjc/s10052-018-6513-6 is OK
- 10.1140/epjc/s10052-017-5155-4 is OK
- 10.1103/PhysRevD.31.3059 is OK
- 10.1103/PhysRevD.101.055004 is OK
- 10.1103/PhysRevD.80.083502 is OK
- 10.1016/S0927-6505(96)00047-3 is OK
- 10.1103/PhysRevD.33.2071 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@temken – thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by danielskatz** [comment]
👋 @lucydot - do you think you could edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @lucydot as editor

**Comment by whedon** [comment]
@lucydot has been invited to edit this submission.

**Comment by dpsanders** [comment]
Ah thanks, I'll do that.

**Comment by lucydot** [comment]
Hi @temken I'll be your editor for this submission 👋

Do you have any suggestions for potential reviewers? If so it'd be useful if you could mention them here in this thread (without tagging them with an @). In addition, [this list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) of people have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by temken** [comment]
Hi @lucydot,

I would suggest bradkav, villaa, or rafaelab based on the list.

Thanks for taking care of my submission!

**Comment by lucydot** [comment]
Excellent, thanks @temken - 

Hello @villaa and @rafaelab 👋 are you available for review?

@villaa I think this may be your first review with JOSS so I've sent you an email with a little bit more information about the process.

**Comment by rafaelab** [comment]
Hi @lucydot 
I can review it.

**Comment by villaa** [comment]
Hi @lucydot, I can also review it.

**Comment by lucydot** [comment]
Hi @rafaelab and @villaa that's great! 

I'll assign you as reviewers and then ask our bot Whedon to start a review issue thread (this is the _pre_-review thread). If you're new to the JOSS review process, be sure to read the instructions at the top of that new thread.

We're asking for reviews to be complete within a 4-6 week period. As the review is usually an iterative process (rather than something you do in one sitting) it's best for reviews to start earlier in that timeline.

**Comment by lucydot** [comment]
@whedon assign @rafaelab @villaa as reviewers

**Comment by whedon** [comment]
OK, @rafaelab @villaa is now a reviewer

**Comment by lucydot** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3725.
