### ISSUE TITLE
[PRE REVIEW]: Fresa: a plant propagation algorithm for black-box single and multiple objective optimization

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3584]
**Submitting author:** @ericsfraga (<a href="http://orcid.org/0000-0002-5732-6082">Eric S Fraga</a>)
**Repository:** <a href="https://github.com/ericsfraga/Fresa.jl" target ="_blank">https://github.com/ericsfraga/Fresa.jl</a>
**Version:** v7.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d70d962bec16a0c4214897e5ac0e49d2/status.svg)](https://joss.theoj.org/papers/d70d962bec16a0c4214897e5ac0e49d2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d70d962bec16a0c4214897e5ac0e49d2"><img src="https://joss.theoj.org/papers/d70d962bec16a0c4214897e5ac0e49d2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d70d962bec16a0c4214897e5ac0e49d2/status.svg)](https://joss.theoj.org/papers/d70d962bec16a0c4214897e5ac0e49d2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ericsfraga. **Currently, there isn't an JOSS editor assigned** to your paper.

@ericsfraga if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (570.5 files/s, 60639.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                            8             43            232            750
TOML                             2              9              1             28
-------------------------------------------------------------------------------
SUM:                            10             52            233            778
-------------------------------------------------------------------------------


Statistical information for the repository '6768d4d48cce3dc674e2fb93' was
gathered on 2021/08/06.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3584 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03584/joss.03584/10.21105.joss.03584.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03584/joss.03584/10.21105.joss.03584.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@ericsfraga – due to the relatively small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
👋 @ericsfraga - I'm sorry for the delay, and also to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by ericsfraga** [comment]
Okay, thank you. No worries. I do believe that this software represents a substantial scholarly effort but I am obviously biased. ;-)
