### ISSUE TITLE
[PRE REVIEW]: HydDown: A Python package for calculation of hydrogen (or other gas) pressure vessel filling and discharge

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3585]
**Submitting author:** @andr1976 (<a href="http://orcid.org/0000-0003-0475-323X">Anders Andreasen</a>)
**Repository:** <a href="https://github.com/andr1976/HydDown" target ="_blank">https://github.com/andr1976/HydDown</a>
**Version:** v0.15.1
**Editor:** @fraukewiese
**Reviewers:** @mefuller, @bocklund
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25/status.svg)](https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25"><img src="https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25/status.svg)](https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25)
```

**Author instructions**

Thanks for submitting your paper to JOSS @andr1976. **Currently, there isn't an JOSS editor assigned** to your paper.

@andr1976 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1175

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (974.2 files/s, 108966.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          14            393            129           1786
TeX                              3            109            171           1307
YAML                            32             19             42            981
Markdown                         4            356              0            852
TOML                             1              0              0              6
DOS Batch                        1              0              0              1
-------------------------------------------------------------------------------
SUM:                            55            877            342           4933
-------------------------------------------------------------------------------


Statistical information for the repository '6603ea3b1ad66de78d4ca50a' was
gathered on 2021/08/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Anders Andreasen                 8            21             16            0.52
andr1976                       113          4707           2408           99.48

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
andr1976                   2308           49.0          3.1                3.99
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3585 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:204:in `block in parse_authors': Author (Anders Andreasen) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.5154096 is OK
- 10.1016/j.psep.2016.10.008 is OK
- 10.3390/safety4010011 is OK
- 10.1299/jtst.2.180 is OK
- 10.1299/jtst.3.241 is OK
- 10.1021/i260011a004 is OK
- 10.1021/ie4033999 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1016/j.ijhydene.2021.04.037 is OK

MISSING DOIs

- 10.1109/mcse.2011.37 may be a valid DOI for title: The NumPy Array: A Structure for Efficient Numerical Computation
- 10.1109/mcse.2007.55 may be a valid DOI for title: Matplotlib: A 2D graphics environment
- 10.25080/majora-92bf1922-00a may be a valid DOI for title:  Data Structures for Statistical Computing in Python 

INVALID DOIs

- https://doi.org/10.1016/j.ijhydene.2014.03.028 is INVALID because of 'https://doi.org/' prefix
- 10.18260/1-2–2911 is INVALID
- https://doi.org/10.1016/j.ces.2015.01.019 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/aic.690480223 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.psep.2019.10.035 is INVALID because of 'https://doi.org/' prefix
```

**Comment by arfon** [comment]
@andr1976 – your author entry is missing an affiliation, and your affiliation missing an index. Please check out of the example paper to see how this YAML should be structured: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by andr1976** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by andr1976** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3585 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:204:in `block in parse_authors': Author (Anders Andreasen) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by andr1976** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03585/joss.03585/10.21105.joss.03585.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03585/joss.03585/10.21105.joss.03585.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon invite @timtroendle as editor

:wave: @timtroendle – I realize I've just invited you on another submission too but any chance you could take this one on also?

**Comment by whedon** [comment]
@timtroendle has been invited to edit this submission.

**Comment by andr1976** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.5154096 is OK
- 10.1016/j.psep.2016.10.008 is OK
- 10.3390/safety4010011 is OK
- 10.1299/jtst.2.180 is OK
- 10.1299/jtst.3.241 is OK
- 10.1021/i260011a004 is OK
- 10.1016/j.ijhydene.2014.03.028 is OK
- 10.1021/ie4033999 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/mcse.2007.55  is OK
- 10.25080/majora-92bf1922-00a is OK
- 10.1016/j.ijhydene.2021.04.037 is OK
- 10.1016/j.ces.2015.01.019 is OK
- 10.1002/aic.690480223 is OK
- 10.1016/j.psep.2019.10.035 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by andr1976** [comment]
@arfon @timtroendle I have just noticed the JOSE sister journal to JOSS. I believe JOSS is a good fit for the submitted paper, however considering the "applied" nature of my code and it's applicability (also for teaching/education), I think it might be justified to question it as "research code" as such and you may argue that JOSE might be an equally good or better fit. Anyway, I still think JOSS is the right choice, but I will leave it for you to decide, and will accept your judment on this. Preferably before the formal review is started.

**Comment by andr1976** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03585/joss.03585/10.21105.joss.03585.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03585/joss.03585/10.21105.joss.03585.pdf) :page_facing_up: :point_left:

**Comment by andr1976** [comment]
Suggestion for reviewers (from list), fwitte, noah80, bocklund, mefuller

**Comment by arfon** [comment]
> @arfon @timtroendle I have just noticed the JOSE sister journal to JOSS. I believe JOSS is a good fit for the submitted paper, however considering the "applied" nature of my code and it's applicability (also for teaching/education), I think it might be justified to question it as "research code" as such and you may argue that JOSE might be an equally good or better fit. Anyway, I still think JOSS is the right choice, but I will leave it for you to decide, and will accept your judment on this. Preferably before the formal review is started.

@andr1976 - thanks for flagging this. I'll query the scope here which will give the rest of the JOSS editorial team a chance to give feedback on this matter. This will take a week or so.

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by andr1976** [comment]
@arfon any updates on this?

**Comment by kthyng** [comment]
Hi @andr1976 — the editorial board is fine with this as a JOSS submission, so I have removed the `query-scope` label.

**Comment by kthyng** [comment]
@fraukewiese would this submission be a good fit for you?

**Comment by kthyng** [comment]
@whedon invite @fraukewiese as editor

**Comment by whedon** [comment]
@fraukewiese has been invited to edit this submission.

**Comment by andr1976** [comment]
Hi @kthyng, Thanks!

**Comment by fraukewiese** [comment]
Hi, yes I can take this :)

**Comment by fraukewiese** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @fraukewiese

**Comment by fraukewiese** [comment]
@mefuller , @noah80
– would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: [https://joss.readthedocs.io/en/latest/reviewer_guidelines.html](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html)

**Comment by mefuller** [comment]
Sure - I'd be happy to review

**Comment by fraukewiese** [comment]
Great! Thanks @mefuller !

I will add you as a reviewer now but won't actually start the review until we have a second reviewer signed up.

**Comment by fraukewiese** [comment]
@whedon add @mefuller as reviewer

**Comment by whedon** [comment]
OK, @mefuller is now a reviewer

**Comment by andr1976** [comment]
@fraukewiese, noah80 has not replied I assume, would you consider asking some of the other proposed reviewers?

**Comment by fraukewiese** [comment]
@bocklund – would you be willing to review this submission for JOSS?
The submission under review here is 
[HydDown: A Python package for calculation of hydrogen (or other gas) pressure vessel filling and discharge](https://github.com/andr1976/HydDown)

**Comment by bocklund** [comment]
@fraukewiese, I'd be happy to review HydDown.

**Comment by fraukewiese** [comment]
@bocklund Great, thank you very much!

**Comment by fraukewiese** [comment]
@whedon add @bocklund as reviewer

**Comment by whedon** [comment]
OK, @bocklund is now a reviewer

**Comment by fraukewiese** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3695.

**Comment by fraukewiese** [comment]
@mefuller  , @bocklund  – thanks a lot for agreeing to review here! See you over in #3695 where the actual review will take place.

**Comment by andr1976** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1179

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (604.1 files/s, 57242.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          14            393            129           1786
Markdown                         5            380              0           1029
YAML                            33             21             46           1013
TeX                              2             57              0            445
TOML                             1              0              0              6
DOS Batch                        1              0              0              1
-------------------------------------------------------------------------------
SUM:                            56            851            175           4280
-------------------------------------------------------------------------------


Statistical information for the repository '5166bfd53d01bbbb935194f6' was
gathered on 2021/09/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Anders Andreasen                11            30             25            0.77
andr1976                       113          4707           2408           99.23

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
andr1976                   2308           49.0          4.3                3.99
```
