### ISSUE TITLE
[PRE REVIEW]: SPAM : an Open Source Code for Stopping Power of Protons and Alpha particles in Ambiant Matter

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3586]
**Submitting author:** @michaeltouati (<a href="http://orcid.org/0000-0001-7590-0941">Michael Touati</a>)
**Repository:** <a href="https://github.com/michaeltouati/SPAM" target ="_blank">https://github.com/michaeltouati/SPAM</a>
**Version:** v1.0.0
**Editor:** @lucydot
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a473bd641429cfea4d89d489478b08bf/status.svg)](https://joss.theoj.org/papers/a473bd641429cfea4d89d489478b08bf)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a473bd641429cfea4d89d489478b08bf"><img src="https://joss.theoj.org/papers/a473bd641429cfea4d89d489478b08bf/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a473bd641429cfea4d89d489478b08bf/status.svg)](https://joss.theoj.org/papers/a473bd641429cfea4d89d489478b08bf)
```

**Author instructions**

Thanks for submitting your paper to JOSS @michaeltouati. **Currently, there isn't an JOSS editor assigned** to your paper.

@michaeltouati if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1092

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (112.6 files/s, 88616.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            188            942           3905
TeX                              1             27              0            332
Markdown                         2             20              0             97
-------------------------------------------------------------------------------
SUM:                             7            235            942           4334
-------------------------------------------------------------------------------


Statistical information for the repository '6079202304953a3ccea78e08' was
gathered on 2021/08/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Michael Touati                   1          5035              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael Touati             5035          100.0          0.0               18.71
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRev.57.485 is OK
- 10.1093/jicru/os25.2.Report49 is OK
- 10.1103/PhysRev.101.778 is OK
- 10.1103/PhysRevLett.11.26 is OK
- 10.1002/andp.19334080303 is OK
- 10.1080/14786440509463378 is OK
- 10.1103/PhysRev.88.851 is OK
- 10.1103/PhysRevB.26.6067 is OK
- 10.1103/PhysRev.88.1283 is OK
- 10.1016/0375-9474(68)90485-5 is OK
- 10.1103/PhysRevA.28.1147 is OK
- 10.1103/PhysRevA.46.5761 is OK
- 10.1103/PhysRevB.26.6067 is OK
- 10.1515/zna-1947-0302 is OK
- 10.1103/PhysRev.78.526 is OK
- 10.1098/rspa.1932.0044 is OK

MISSING DOIs

- 10.1007/978-3-642-52619-0_3 may be a valid DOI for title: Quantenmechanik der Ein- und Zwei-Elektronen Probleme
- 10.2307/3576096 may be a valid DOI for title: Bragg’s Rule of Stopping Power Additivity: A Compilation and Summary of Results
- 10.6028/nist.ir.4550 may be a valid DOI for title: Stopping power of fast charged particles in heavy elements

INVALID DOIs

- https://doi.org/10.1016/0168-583X(85)90705-0 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/0168-583X(87)90568-4 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/0029-554X(70)90141-2 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/0009-2614(75)85560-6 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03586/joss.03586/10.21105.joss.03586.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03586/joss.03586/10.21105.joss.03586.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@michaeltouati - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by arfon** [comment]
@whedon invite @lucydot as editor

:wave: @lucydot – would you be able to edit this submission for JOSS?

**Comment by whedon** [comment]
@lucydot has been invited to edit this submission.

**Comment by lucydot** [comment]
Hello @arfon it's outside of my physics area but yes I can give it a whirl if there is not a better matched editor who is available - feel free to assign to me.

**Comment by arfon** [comment]
Thanks @lucydot for being willing to take this one on 🎉👍😁

**Comment by arfon** [comment]
@whedon assign @lucydot as editor

**Comment by whedon** [comment]
OK, the editor is @lucydot

**Comment by lucydot** [comment]
Hi @michaeltouati 👋 Thanks for your submission to JOSS. I have taken a look at the repository and discussed it with the wider editorial team. We have decided that the submission needs substantial work before we can move to review stage, so we will reject at this stage, with an invitation to re-submit.

Before re-submission you may find [this page](https://joss.readthedocs.io/en/latest/review_criteria.html) useful - it outlines the review criteria. In particular, we would encourage you to:
- expand documentation beyond the README
- include testing, or outline manual steps that can be take for the user to verify the functionality of the software
- highlight how this software compares to other commonly-used packages in this research area. For example, what is unique about this piece of software? Is the underlying algorithm implemented elsewhere? (if the unique contribution is the GUI only then this submission may not be in-scope for JOSS).

It may also be useful to take a look at some of the accepted submissions listed [here](https://joss.theoj.org/). Although practice will vary from domain to domain, it should give you a rough indication of what the editorial team and reviewers will be looking for whilst assessing the submission.

If I can clarify anything then please let me know.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
