### ISSUE TITLE
[PRE REVIEW]: AstronomicAL: an interactive dashboard for visualisation, integration and classification of data with Active Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3588]
**Submitting author:** @grant-m-s (<a href="http://orcid.org/0000-0002-8885-4443">Grant Stevens</a>)
**Repository:** <a href="https://github.com/grant-m-s/astronomicAL" target ="_blank">https://github.com/grant-m-s/astronomicAL</a>
**Version:** v1.0.0
**Editor:** @crvernon
**Reviewers:** @crhea93, @rmorgan10
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104/status.svg)](https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104"><img src="https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104/status.svg)](https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104)
```

**Author instructions**

Thanks for submitting your paper to JOSS @grant-m-s. **Currently, there isn't an JOSS editor assigned** to your paper.

@grant-m-s if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (380.5 files/s, 99071.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          22           2341           1023           6664
reStructuredText                16            528            650            418
JSON                             3              0              0            290
Markdown                         1             20              0             32
Jupyter Notebook                 1              0            162             28
DOS Batch                        1              8              1             26
YAML                             2              3              5             18
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            47           2904           1848           7485
-------------------------------------------------------------------------------


Statistical information for the repository '01983bc8b4532cd31e66f079' was
gathered on 2021/08/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Grant Stevens                  226         16604           6576          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Grant Stevens             10028           60.4          3.4                2.76
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3588 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3588 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by grant-m-s** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03588/joss.03588/10.21105.joss.03588.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03588/joss.03588/10.21105.joss.03588.pdf) :page_facing_up: :point_left:

**Comment by grant-m-s** [comment]
possible reviewers: smith42 crhea93 rmorgan10 arunmano121 a-slide

**Comment by arfon** [comment]
@grant-m-s – thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

**Comment by crvernon** [comment]
👋 @grant-m-s I'll be your editor for this submission.  Thanks for recommending potential reviewers!

**Comment by crvernon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @crvernon

**Comment by crvernon** [comment]
:wave: @rmorgan10 @crhea93 - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by crhea93** [comment]
@crvernon Yes please!

**Comment by crvernon** [comment]
Excellent @crhea93!  I'll sign you up.  Thank you!

**Comment by crvernon** [comment]
@whedon assign @crhea93 as reviewer

**Comment by whedon** [comment]
OK, @crhea93 is now a reviewer

**Comment by crvernon** [comment]
:wave: @smith42 - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by rmorgan10** [comment]
@crvernon Sorry for the delay! If the offer is still available, I would be happy to review AstronomicAL :)

**Comment by crvernon** [comment]
No problem @rmorgan10, the offer is still open and I'll assign you as a reviewer.  Thanks!

**Comment by crvernon** [comment]
@whedon add @rmorgan10 as reviewer

**Comment by whedon** [comment]
OK, @rmorgan10 is now a reviewer

**Comment by crvernon** [comment]
Alright @rmorgan10 @crhea93 @grant-m-s I am going to close this Pre-Review and kick off the full review which you should receive a notification for.  We aim for reviews to be completed within about 2-4 weeks. Thanks!

**Comment by crvernon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3635.
