### ISSUE TITLE
[PRE REVIEW]: beamshapes: a Python package to generate directivity patterns for various sound source models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3590]
**Submitting author:** @thejasvibr (<a href="http://orcid.org/0000-0001-5360-4383">Beleyur Thejasvi</a>)
**Repository:** <a href="https://github.com/thejasvibr/bat_beamshapes.git" target ="_blank">https://github.com/thejasvibr/bat_beamshapes.git</a>
**Version:** v0.2.0
**Editor:** @faroit
**Reviewers:** @nils-werner, @hagenw
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/820fd37f8255a8c533d6cc4c9475ecb5/status.svg)](https://joss.theoj.org/papers/820fd37f8255a8c533d6cc4c9475ecb5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/820fd37f8255a8c533d6cc4c9475ecb5"><img src="https://joss.theoj.org/papers/820fd37f8255a8c533d6cc4c9475ecb5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/820fd37f8255a8c533d6cc4c9475ecb5/status.svg)](https://joss.theoj.org/papers/820fd37f8255a8c533d6cc4c9475ecb5)
```

**Author instructions**

Thanks for submitting your paper to JOSS @thejasvibr. **Currently, there isn't an JOSS editor assigned** to your paper.

@thejasvibr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1075

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.18 s (330.5 files/s, 223081.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             2           3522              4          25979
Python                          32            969           1913           2056
TeX                              2             51             21            438
Jupyter Notebook                 5              0           4112            403
reStructuredText                10            218            165            231
Markdown                         5             92              0            191
DOS Batch                        1              8              1             26
YAML                             1              3              0              9
make                             1              4              7              9
Rmd                              1             22             47              0
-------------------------------------------------------------------------------
SUM:                            60           4889           6270          29342
-------------------------------------------------------------------------------


Statistical information for the repository '93412b0adb1201981142ff45' was
gathered on 2021/08/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
tbeleyur                        12          1141            135           10.99
thejasvi                        75          7135           3167           88.72
thejasvibr                       1            32              2            0.29

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
tbeleyur                    259           22.7          8.2                6.95
thejasvi                   4679           65.6          2.4               19.90
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- 10.1016/c2017-0-01630-0 may be a valid DOI for title: Acoustics: Sound Fields, Transducers and Vibration
- 10.1121/1.1912304 may be a valid DOI for title: Acoustical beam patterns for bats: some theoretical considerations
- 10.1007/bf00610475 may be a valid DOI for title: Sound radiation patterns in the frequency domain of cries from a Vespertilionid bat
- 10.1098/rspb.2008.1505 may be a valid DOI for title: Echolocating bats emit a highly directional sonar sound beam in the field
- 10.1121/10.0001376 may be a valid DOI for title: High resolution three-dimensional beam radiation pattern of harbour porpoise clicks with implications for passive acoustic monitoring
- 10.1038/nature11664 may be a valid DOI for title: Convergent acoustic field of view in echolocating bats
- 10.1073/pnas.1422843112 may be a valid DOI for title: Bats adjust their mouth gape to zoom their biosonar field of view
- 10.1121/1.3519408 may be a valid DOI for title: A method for estimating the orientation of a directional sound source from source directivity and multi-microphone recordings: Principles and application
- 10.1016/j.beproc.2019.103996 may be a valid DOI for title: Sound radiation pattern of the advertisement call of the highly territorial poison frog Allobates femoralis
- 10.1007/bf00657481 may be a valid DOI for title: Sound pressure levels and radiation patterns of the vocalizations of some North American frogs and toads
- 10.1016/j.anbehav.2008.07.005 may be a valid DOI for title: Acoustic directionality of red-winged blackbird (Agelaius phoeniceus) song relates to amplitude and singing behaviours
- 10.2307/1367730 may be a valid DOI for title: The importance of directional sound radiation in avian vocalization
- 10.1098/rspb.2009.1519 may be a valid DOI for title: Birds adjust acoustic directionality to beam their antipredator calls to predators and conspecifics
- 10.2307/3676376 may be a valid DOI for title: Directionality of blackbird vocalization. Implications for vocal communication and its further study
- 10.1007/s00265-006-0343-5 may be a valid DOI for title: Differences in acoustic directionality among vocalizations of the male red-winged blackbird (Agelaius pheoniceus) are related to function in communication
- 10.1046/j.1439-0361.2002.02045.x may be a valid DOI for title: Sound radiation patterns in nightingale (Luscinia megarhynchos) songs

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03590/joss.03590/10.21105.joss.03590.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03590/joss.03590/10.21105.joss.03590.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@thejasvibr - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

If you want to fix the DOIs while you're waiting (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by faroit** [comment]
@arfon I think is relatively close to my areas of expertise so I can edit this submission

**Comment by arfon** [comment]
@whedon assign @faroit as editor

**Comment by whedon** [comment]
OK, the editor is @faroit

**Comment by arfon** [comment]
Thanks @faroit!

**Comment by thejasvibr** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by thejasvibr** [comment]
@whedon suggested reviewers are DrMarc, pharshalp, astanziola

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by thejasvibr** [comment]
Thanks for agreeing to edit @faroit. Suggested reviewers from my side are DrMarc, pharshalp, astanziola

**Comment by faroit** [comment]
Hi @thejasvibr, sorry for the long waiting time. I wanted to make sure that I have enough bandwidth to probably maintain the editing process before kicking this off.

> Thanks for agreeing to edit @faroit. Suggested reviewers from my side are DrMarc, pharshalp, astanziola

I think that sounds good, I would also like to include an audio researcher who isn't that much familiar with animal sounds but general dsp and python: I would `nils-werner` if there is not conflict of interest.

In the meantime, I suggest you can already work on the missing DOI as pointed out by @arfon

**Comment by thejasvibr** [comment]
Hi @faroit, 
Thanks for getting back - no worries at all. No objections to ```nils-werner```, don't see a conflict of interest and would be great to have someone who's not from the same field as reviewer. 

Will start working on the missing DOIs!

**Comment by faroit** [comment]
👋  @nils-werner @DrMarc - would any of you be willing to review this submission for JOSS? The JOSS review process takes place on GitHub and focuses on the software and a short paper. We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The software under review is [beamshapes: a Python package to generate directivity patterns for various sound source models](https://github.com/thejasvibr/bat_beamshapes.git).

This issue is a "pre-review" issue in which reviewers are assigned. Once sufficient reviewers are recruited we will open a dedicated review issue where the review will take place.

**Comment by nils-werner** [comment]
Yes, I would be willing to review it.

**Comment by faroit** [comment]
@whedon add @nils-werner as reviewer

**Comment by whedon** [comment]
OK, @nils-werner is now a reviewer

**Comment by hagenw** [comment]
I would also be willing to review.

**Comment by faroit** [comment]
@whedon add @hagenw as reviewer

**Comment by whedon** [comment]
OK, @hagenw is now a reviewer

**Comment by faroit** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK

MISSING DOIs

- 10.1016/c2011-0-05897-0 may be a valid DOI for title: Acoustics: sound fields and transducers
- 10.1016/c2017-0-01630-0 may be a valid DOI for title: Acoustics: Sound Fields, Transducers and Vibration
- 10.1121/1.1912304 may be a valid DOI for title: Acoustical beam patterns for bats: some theoretical considerations
- 10.1007/bf00610475 may be a valid DOI for title: Sound radiation patterns in the frequency domain of cries from a Vespertilionid bat
- 10.1098/rspb.2008.1505 may be a valid DOI for title: Echolocating bats emit a highly directional sonar sound beam in the field
- 10.1121/10.0001376 may be a valid DOI for title: High resolution three-dimensional beam radiation pattern of harbour porpoise clicks with implications for passive acoustic monitoring
- 10.3389/conf.fnbeh.2012.27.00243 may be a valid DOI for title: Convergent acoustic field of view in echolocating bats
- 10.1073/pnas.1422843112 may be a valid DOI for title: Bats adjust their mouth gape to zoom their biosonar field of view
- 10.1121/1.3519408 may be a valid DOI for title: A method for estimating the orientation of a directional sound source from source directivity and multi-microphone recordings: Principles and application
- 10.1016/j.beproc.2019.103996 may be a valid DOI for title: Sound radiation pattern of the advertisement call of the highly territorial poison frog Allobates femoralis
- 10.1007/bf00657481 may be a valid DOI for title: Sound pressure levels and radiation patterns of the vocalizations of some North American frogs and toads
- 10.1016/j.anbehav.2008.07.005 may be a valid DOI for title: Acoustic directionality of red-winged blackbird (Agelaius phoeniceus) song relates to amplitude and singing behaviours
- 10.2307/1367730 may be a valid DOI for title: The importance of directional sound radiation in avian vocalization
- 10.1098/rspb.2009.1519 may be a valid DOI for title: Birds adjust acoustic directionality to beam their antipredator calls to predators and conspecifics
- 10.2307/3676376 may be a valid DOI for title: Directionality of blackbird vocalization. Implications for vocal communication and its further study
- 10.1007/s00265-006-0343-5 may be a valid DOI for title: Differences in acoustic directionality among vocalizations of the male red-winged blackbird (Agelaius pheoniceus) are related to function in communication
- 10.1046/j.1439-0361.2002.02045.x may be a valid DOI for title: Sound radiation patterns in nightingale (Luscinia megarhynchos) songs

INVALID DOIs

- None
```

**Comment by thejasvibr** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "doi" (NAME) [#<BibTeX::Bibliography data=[18]>, "@", #<BibTeX::Entry >, {:title=>["Birds adjust acoustic directionality to beam their antipredator calls to predators and conspecifics"], :author=>["Yorzinski, Jessica L and Patricelli, Gail L"], :journal=>["Proceedings of the Royal Society B: Biological Sciences"], :volume=>["277"], :number=>["1683"], :pages=>["923--932"], :year=>["2010"], :publisher=>["The Royal Society"]}]

**Comment by thejasvibr** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/c2011-0-05897-0 is OK
- 10.1016/c2017-0-01630-0 is OK
- 10.1121/1.1912304 is OK
- 10.1007/bf00610475 is OK
- 10.1121/10.0001376 is OK
- 10.1038/nature11664 is OK
- 10.1073/pnas.1422843112 is OK
- 10.1121/1.3519408 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1016/j.beproc.2019.103996 is OK
- 10.1007/bf00657481 is OK
- 10.1016/j.anbehav.2008.07.005 is OK
- 10.2307/1367730 is OK
- 10.1098/rspb.2009.1519 is OK
- 10.2307/3676376 is OK
- 10.1007/s00265-006-0343-5 is OK
- 10.1046/j.1439-0361.2002.02045.x is OK

MISSING DOIs

- 10.1098/rspb.2008.1505 may be a valid DOI for title: Echolocating bats emit a highly directional sonar sound beam in the field

INVALID DOIs

- None
```

**Comment by thejasvibr** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/c2011-0-05897-0 is OK
- 10.1016/c2017-0-01630-0 is OK
- 10.1121/1.1912304 is OK
- 10.1007/bf00610475 is OK
- 10.1098/rspb.2008.1505  is OK
- 10.1121/10.0001376 is OK
- 10.1038/nature11664 is OK
- 10.1073/pnas.1422843112 is OK
- 10.1121/1.3519408 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.7717/peerj-cs.103 is OK
- 10.1016/j.beproc.2019.103996 is OK
- 10.1007/bf00657481 is OK
- 10.1016/j.anbehav.2008.07.005 is OK
- 10.2307/1367730 is OK
- 10.1098/rspb.2009.1519 is OK
- 10.2307/3676376 is OK
- 10.1007/s00265-006-0343-5 is OK
- 10.1046/j.1439-0361.2002.02045.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by thejasvibr** [comment]
@faroit apologies for the delay in DOI correction - they seem to be all fixed now. 
Hello @hagenw and @nils-werner many thanks for agreeing to review - looking forward to hearing from you!

**Comment by faroit** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03590/joss.03590/10.21105.joss.03590.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03590/joss.03590/10.21105.joss.03590.pdf) :page_facing_up: :point_left:

**Comment by faroit** [comment]
@thejasvibr paper looks good so far. We can start the review process

**Comment by faroit** [comment]
@whend start review

**Comment by faroit** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3740.
