### ISSUE TITLE
[PRE REVIEW]: Feature-engine: A Python package for feature engineering for machine learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3592]
**Submitting author:** @solegalli (<a href="http://orcid.org/0000-0003-3734-8628">Soledad</a>)
**Repository:** <a href="https://github.com/feature-engine/feature_engine" target ="_blank">https://github.com/feature-engine/feature_engine</a>
**Version:** v1.1.1
**Editor:** @osorensen
**Reviewers:** @Jose-Augusto-C-M, @papachristoumarios, @bobturneruk
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/cb8978d632aabe0bff7c3c3d7f72c419/status.svg)](https://joss.theoj.org/papers/cb8978d632aabe0bff7c3c3d7f72c419)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cb8978d632aabe0bff7c3c3d7f72c419"><img src="https://joss.theoj.org/papers/cb8978d632aabe0bff7c3c3d7f72c419/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cb8978d632aabe0bff7c3c3d7f72c419/status.svg)](https://joss.theoj.org/papers/cb8978d632aabe0bff7c3c3d7f72c419)
```

**Author instructions**

Thanks for submitting your paper to JOSS @solegalli. **Currently, there isn't an JOSS editor assigned** to your paper.

@solegalli if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3592 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.35 s (582.3 files/s, 69856.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         118           3806           5560           9397
reStructuredText                72           1496           2056           1400
Markdown                         6             88              0            242
YAML                             2             17             10            152
INI                              2             22              0             62
CSS                              1              5              0             15
make                             1              4              6             10
HTML                             1              1              0              3
-------------------------------------------------------------------------------
SUM:                           203           5439           7632          11281
-------------------------------------------------------------------------------


Statistical information for the repository 'ca23521356c3a354c2f6f5ed' was
gathered on 2021/08/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrew Tan                       1             3              5            0.02
Arthur Cabral                    1             1              1            0.00
Ashok kumar                      2             3              3            0.01
ChristopherGS                    1            65            323            0.89
Gleb Levitskiy                   1            36              8            0.10
Indy Navarro Vidal               1            84             46            0.30
Karthik Kothareddy               2           145             10            0.36
Kishan Manani                    2             2              2            0.01
Michał Gromiec                   3           718             10            1.67
Miguel Trejo Marrufo             2           655             72            1.67
NicoGalli                        1           393             58            1.04
Nodar Okroshiashvili             1            41             50            0.21
Sana Ben Driss                   2           827              2            1.91
Soledad Galli                   35         24112          11757           82.50
Surya Krishnamurthy              2           233              3            0.54
Tejash Shah                      1           243              4            0.57
hectorpatino                     1           396              1            0.91
piecot                           1             1              1            0.00
pradumna123                      1           224              0            0.52
solegalli                        1          2937              0            6.76

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrew Tan                    3          100.0          3.2                0.00
Ashok kumar                   1           33.3          7.9                0.00
ChristopherGS                 1            1.5         20.6              100.00
Indy Navarro Vidal           84          100.0          3.9                0.00
Michał Gromiec               18            2.5         12.0               11.11
Miguel Trejo Marrufo        655          100.0          0.8                8.85
NicoGalli                   289           73.5          9.3               12.80
Nodar Okroshiashvili         41          100.0          9.3                0.00
Sana Ben Driss              534           64.6          8.9               16.29
Soledad Galli             16622           68.9          7.3                9.29
hectorpatino                313           79.0          3.4                7.67
pradumna123                 202           90.2          6.8                7.92
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03592/joss.03592/10.21105.joss.03592.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03592/joss.03592/10.21105.joss.03592.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @solegalli  – thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.

For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

In the interim though, please updated your reference keys so they match between your Markdown doc and references (e.g., change `@pandas:2010` in your `paper.md` to `@pandas` in `paper.bib`).

Also, could you explain why there is only a single author for this paper when there look to have been significant contributions made by others? Has the authorship of this paper been discussed anywhere before submission?

**Comment by solegalli** [comment]
Hi @arfon thanks a lot for starting the process.

The reference keys were updated as requested.

At the moment, I am the founder, main developer and maintainer of the project. More details about the governance can be found [here](https://feature-engine.readthedocs.io/en/latest/governance.html).

The community is growing and we have growing support from users, fortunately, which is quite encouraging, but we are not at a stage yet, where we have a committee who makes joint decisions. 

In the submitted article, I followed the initiative of 2 other Python open source software libraries for machine learning, which, while had support from the community at time of publication, the authors of the article where the founders and maintainers of the project. See for example [yellowbricks](https://joss.theoj.org/papers/10.21105/joss.01075) and [mlxtend](https://www.theoj.org/joss-papers/joss.00638/10.21105.joss.00638.pdf).

I cc here @ChristopherGS who has supported the project from the beginning as explained in the acknowledgements section.

Thanks a lot

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
@solegalli I am now the editor for this submission. If you have any suggestions for reviewers, could you please mention their username in this thread (without the leadning '@')?

**Comment by osorensen** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3592 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by osorensen** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03592/joss.03592/10.21105.joss.03592.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03592/joss.03592/10.21105.joss.03592.pdf) :page_facing_up: :point_left:

**Comment by osorensen** [comment]
@solegalli, please also update the BibTeX entry for the Zenode archive of the package, to:

```
@misc{https://doi.org/10.5281/zenodo.5167307,
  doi = {10.5281/ZENODO.5167307},
  url = {https://zenodo.org/record/5167307},
  author = {Galli,  Soledad and {Michał Gromiec} and Samiullah,  Christopher and Kumar,  Ashok and Kothareddy,  Karthik and Manani,  Kishan and Marrufo,  Miguel Trejo and Driss,  Sana Ben and Krishnamurthy,  Surya and {Pradumna123} and Tan,  Andrew and Cabral,  Arthur and Levitskiy,  Gleb and {Indy Navarro Vidal} and {NicoGalli} and Okroshiashvili,  Nodar and Suwandi,  Richard Cornelius and {Tejash Shah} and {Wahe3bru} and Sohayb,  El Amraoui and {Hectorpatino} and {Piecot}},
  title = {feature-engine/feature_engine: v1.1.1},
  publisher = {Zenodo},
  year = {2021},
  copyright = {Open Access}
}
```

If possible, please also change the GitHub usernames appearing in this citation (Pradumna123, Wahe3bru) to the authors' real names.

After you've done this, feel free to run "(at)whedon generate pdf from branch paper" as a comment in this issue, to see how the resulting paper looks.

**Comment by osorensen** [comment]
@Jose-Augusto-C-M @bobturneruk @JYProjs @papachristoumarios @ftarlaci @TahiriNadia would any of you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by Jose-Augusto-C-M** [comment]
I will do my best. But I may take some time, it's my first time reviewing a work of this kind, there's is much to read and understand. Is there any guidance of evaluation of such repositories?

**Comment by osorensen** [comment]
Thanks a lot, @Jose-Augusto-C-M! We have reviewer guidelines here https://joss.readthedocs.io/en/latest/reviewer_guidelines.html, which describe how to do this. In addition, the review will be in a GitHub issue, where you have a checklist to follow (see an example here https://github.com/openjournals/joss-reviews/issues/3459). In addition to that, you are welcome to contact me any time in the review process.

**Comment by osorensen** [comment]
@whedon add @Jose-Augusto-C-M as reviewer

**Comment by whedon** [comment]
OK, @Jose-Augusto-C-M is now a reviewer

**Comment by papachristoumarios** [comment]
@osorensen I can review this article. It's my first time reviewing for JOSS and may take some time. I will also read the aforementioned review guidelines.

**Comment by osorensen** [comment]
Thanks @papachristoumarios!

**Comment by osorensen** [comment]
@whedon add @papachristoumarios as reviewer

**Comment by whedon** [comment]
OK, @papachristoumarios is now a reviewer

**Comment by osorensen** [comment]
@papachristoumarios and @Jose-Augusto-C-M I'll wait for a third reviewer before starting a new review issue.

**Comment by bobturneruk** [comment]
Also a first timer, but the checklist looks to make the process objective and straightforward. I've used similar checklists. I'm happy to review.

**Comment by osorensen** [comment]
Thanks @bobturneruk !

**Comment by osorensen** [comment]
@whedon add @bobturneruk as reviewer

**Comment by whedon** [comment]
OK, @bobturneruk is now a reviewer

**Comment by osorensen** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3642.

**Comment by TahiriNadia** [comment]
> @Jose-Augusto-C-M @bobturneruk @JYProjs @papachristoumarios @ftarlaci @TahiriNadia would any of you be interested in reviewing this submission to the Journal of Open Source Software?

First timer at JOSS, but the checklist makes the process seem objective and straightforward. I would be happy to review.

**Comment by osorensen** [comment]
Thanks a lot @TahiriNadia. Since we already have three reviewers assigned, I'll keep you in mind until next submission, and ask you again then.

**Comment by ftarlaci** [comment]
If you still need more reviewers, I would be happy to help as well.

**Comment by osorensen** [comment]
Thanks @ftarlaci, I'll keep you in mind next time :-)

**Comment by TahiriNadia** [comment]
> Thanks a lot @TahiriNadia. Since we already have three reviewers assigned, I'll keep you in mind until next submission, and ask you again then.

Thank you @osorensen :-)

**Comment by solegalli** [comment]
> 
> 
> @solegalli I am now the editor for this submission. If you have any suggestions for reviewers, could you please mention their username in this thread (without the leadning '@')?

Hi @osorensen apologies for the delayed response. I was on holidays until today. I see that you found reviewers already. Thank you so much! I look forward to the feedback.

Regards.

**Comment by solegalli** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03592/joss.03592/10.21105.joss.03592.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03592/joss.03592/10.21105.joss.03592.pdf) :page_facing_up: :point_left:

**Comment by solegalli** [comment]
> 
> 
> @solegalli, please also update the BibTeX entry for the Zenode archive of the package, to something like this, making sure all contributor names are included.
> 
> ```
> @misc{cite_key,
>   doi = {10.5281/ZENODO.5167307},
>   url = {https://zenodo.org/record/5167307},
>   author = {Galli,  Soledad and {Michał Gromiec} and Samiullah,  Christopher and Kumar,  Ashok and Kothareddy,  Karthik and Manani,  Kishan and Marrufo,  Miguel Trejo and Driss,  Sana Ben and Krishnamurthy,  Surya and {Pradumna123} and Tan,  Andrew and Cabral,  Arthur and Levitskiy,  Gleb and {Indy Navarro Vidal} and {NicoGalli} and Okroshiashvili,  Nodar and Suwandi,  Richard Cornelius and {Tejash Shah} and {Wahe3bru} and Sohayb,  El Amraoui and {Hectorpatino} and {Piecot}},
>   title = {feature-engine/feature_engine: v1.1.1},
>   publisher = {Zenodo},
>   year = {2021},
>   copyright = {Open Access}
> }
> ```
> 
> If possible, please also change the GitHub usernames appearing in this citation (Pradumna123, Wahe3bru) to the authors' real names.
> 
> After you've done this, feel free to run "(at)whedon generate pdf from branch paper" as a comment in this issue, to see how the resulting paper looks.

Done! thank you for the patience.

**Comment by osorensen** [comment]
Thanks @solegalli. I recompiled the paper over in #3642 .
