### ISSUE TITLE
[PRE REVIEW]: Vulwebaju: platform that automates setting up your pen-testing lab.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3593]
**Submitting author:** @aju100 (<a href="http://orcid.org/0000-0002-8019-6394">Aju Tamang</a>)
**Repository:** <a href="https://github.com/Aju100/VulWebaju" target ="_blank">https://github.com/Aju100/VulWebaju</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/85f4f085b999cd0420923215e2001b7d/status.svg)](https://joss.theoj.org/papers/85f4f085b999cd0420923215e2001b7d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/85f4f085b999cd0420923215e2001b7d"><img src="https://joss.theoj.org/papers/85f4f085b999cd0420923215e2001b7d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/85f4f085b999cd0420923215e2001b7d/status.svg)](https://joss.theoj.org/papers/85f4f085b999cd0420923215e2001b7d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @aju100. **Currently, there isn't an JOSS editor assigned** to your paper.

@aju100 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (407.7 files/s, 43930.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Bourne Shell                     1             33             31            231
Markdown                         2             41              0             82
YAML                             1              2              0             11
-------------------------------------------------------------------------------
SUM:                             4             76             31            324
-------------------------------------------------------------------------------


Statistical information for the repository '6c7c671349f0288c34c030b2' was
gathered on 2021/08/09.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3593 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by arfon** [comment]
:wave: @Aju100 – many thanks for this submission to JOSS. Unfortunately at ~200 LOC (Bash) this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by Aju100** [comment]
Thank you @arfon for the feedbacks. I appreciated it.
