### ISSUE TITLE
[PRE REVIEW]: spant: An R package for magnetic resonance spectroscopy analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3595]
**Submitting author:** @martin3141 (<a href="http://orcid.org/0000-0002-2089-3956">Martin Wilson</a>)
**Repository:** <a href="https://github.com/martin3141/spant" target ="_blank">https://github.com/martin3141/spant</a>
**Version:** v1.14.0
**Editor:** @chartgerink
**Reviewers:** @a3sha2, @joaomcteixeira
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d93ddd36875ce2183eee6e12598bf7b2/status.svg)](https://joss.theoj.org/papers/d93ddd36875ce2183eee6e12598bf7b2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d93ddd36875ce2183eee6e12598bf7b2"><img src="https://joss.theoj.org/papers/d93ddd36875ce2183eee6e12598bf7b2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d93ddd36875ce2183eee6e12598bf7b2/status.svg)](https://joss.theoj.org/papers/d93ddd36875ce2183eee6e12598bf7b2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @martin3141. **Currently, there isn't an JOSS editor assigned** to your paper.

@martin3141 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 542

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.47 s (796.3 files/s, 182364.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                           302          14582           4169          46695
R                               44           2529           3539           9222
Fortran 77                       2             47           1186           1362
XML                              1              0              0            825
CSS                              4             99             49            431
Markdown                         4             65              0            357
JavaScript                       7             69             45            307
TeX                              1             22              0            214
Rmd                              8            119            314            182
YAML                             3             17              4             97
SVG                              1              0              1             11
C                                1              2              1              7
-------------------------------------------------------------------------------
SUM:                           378          17551           9308          59710
-------------------------------------------------------------------------------


Statistical information for the repository '921374ab4b7797ffb4374e10' was
gathered on 2021/08/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Martin Wilson                   16           888            181          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Martin Wilson               707           79.6         12.4               13.01
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03595/joss.03595/10.21105.joss.03595.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03595/joss.03595/10.21105.joss.03595.pdf) :page_facing_up: :point_left:

**Comment by martin3141** [comment]
suggested reviewers : Øystein Sørensen (osorensen), Elizabeth DuPre (emdupre), Christopher R. Madan (cMadan)

**Comment by martin3141** [comment]
Please note, for some reason my automatic spellchecker wasn't working at submission and I've since fixed a couple of mistakes. Not sure how to regenerate the proof.

**Comment by chartgerink** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03595/joss.03595/10.21105.joss.03595.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03595/joss.03595/10.21105.joss.03595.pdf) :page_facing_up: :point_left:

**Comment by martin3141** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by martin3141** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
> @whedon generate pdf

:wave: @chartgerink – is this a submission you think you'd be able to take on for us?

**Comment by chartgerink** [comment]
I was browsing around a bit, discovering everything 😊 

It's a bit outside of my area but I'd be happy to get out of my comfort zone as you mentioned would be good!

**Comment by arfon** [comment]
@whedon assign @chartgerink as editor

> It's a bit outside of my area but I'd be happy to get out of my comfort zone as you mentioned would be good!
 
 Thanks @chartgerink – I'll take you up on your kind offer :-)

**Comment by whedon** [comment]
OK, the editor is @chartgerink

**Comment by chartgerink** [comment]
Pinged a few people to review - awaiting their response. 😊

**Comment by chartgerink** [comment]
@whedon add @a3sha2 as reviewer

Still looking for a second reviewer.

**Comment by whedon** [comment]
OK, @a3sha2 is now a reviewer

**Comment by chartgerink** [comment]
@whedon add @joaomcteixeira as reviewer.

**Comment by whedon** [comment]
OK, @joaomcteixeira is now a reviewer

**Comment by chartgerink** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3646.

**Comment by a3sha2** [comment]
@whedon review start

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by a3sha2** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @a3sha2, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by danielskatz** [comment]
@a3sha2 - I'm not sure what are you trying to do.  The review is taking place in https://github.com/openjournals/joss-reviews/issues/3646 now.  And this issue for the pre-review should remain closed, since the "action" has moved to the review issue.
