### ISSUE TITLE
[REVIEW]: bfit: A Python Application For Beta-Detected NMR

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3598]
**Submitting author:** @dfujim (<a href="http://orcid.org/0000-0003-2847-2053">Derek Fujimoto</a>)
**Repository:** <a href="https://github.com/dfujim/bfit" target ="_blank">https://github.com/dfujim/bfit</a>
**Version:** 4.14.1
**Editor:** @lucydot
**Reviewers:** @nicksisco1932, @jpata
**Archive:** <a href="https://doi.org/10.5281/zenodo.5519795" target="_blank">10.5281/zenodo.5519795</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2/status.svg)](https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2"><img src="https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2/status.svg)](https://joss.theoj.org/papers/742ff627aec73ce2a647bbede7c73fc2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dfujim/bfit" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nicksisco1932 @jpata, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lucydot know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @nicksisco1932
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/dfujim/bfit">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dfujim/bfit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dfujim) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] #3600
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] #3599
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @jpata
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/dfujim/bfit">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dfujim/bfit">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@dfujim) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nicksisco1932 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 876

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.phpro.2012.04.027 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1016/S0168-9002(97)00048-X is OK
- 10.7566/JPSCP.21.011049 is OK
- 10.1016/j.phpro.2012.04.042 is OK
- 10.1016/j.nima.2014.07.029 is OK
- 10.1016/S0921-4526(00)00328-8 is OK
- 10.1016/j.ssnmr.2015.02.004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.20 s (390.9 files/s, 97517.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          67           3787           3658          11104
C/C++ Header                     3             42            120            514
Markdown                         5             70              0            238
TeX                              2             33              6            153
Cython                           1             28             56             64
C++                              1              9             12             34
YAML                             1              5              2             24
-------------------------------------------------------------------------------
SUM:                            80           3974           3854          12131
-------------------------------------------------------------------------------


Statistical information for the repository '54cd98c3123f5405473fcaf4' was
gathered on 2021/08/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Derek Fujimoto                 930         30946          12086           98.73
Ryan M. L. McFadden              4           136             12            0.34
β-NMR Group                      4           351             55            0.93

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Derek Fujimoto            18886           61.0         16.3               14.96
Ryan M. L. McFadden         120           88.2          5.5               20.83
β-NMR Group                 274           78.1         10.5               17.15
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03598/joss.03598/10.21105.joss.03598.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03598/joss.03598/10.21105.joss.03598.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
OK, @jpata is now a reviewer

**Comment by lucydot** [comment]
👋 @jpata @nicksisco1932 Thanks again for agreeing to review. Reviewer checklists have been generated for you above, feel free to get started whenever is convenient for you in the nearest few weeks. I'll check back in regularly, and do not hesitate to ask if you have questions.

**Comment by lucydot** [comment]
@jpata @nicksisco1932 a quick pointer on the JOSS review process. It is best to raise any issues during the review process in the software repository (https://github.com/dfujim/bfit) and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below.

**Comment by lucydot** [comment]
Hello - just an update to let you know that I will be out of office from the end of today (UK time) until the 30th of August, I will check back here at that date.

**Comment by lucydot** [comment]
Hi @nicksisco1932 how is your review going? I can see that @dfujim has responded to some of the points you raised [here](https://github.com/dfujim/bfit/commit/c335e7d8938663fe12c61afaceaaca3e1d081e8a). If you have any other issues to raise as part of the review process, open them up on the [repository issues page](https://github.com/dfujim/bfit/issues). It'd be  great to hear a summary of your thoughts on the software so far.

@jpata have you had a chance to start the review yet? Let me know if there is anything I can clarify regarding the review process.

**Comment by jpata** [comment]
I have reviewed the package as of [v4.12.0](https://github.com/dfujim/bfit/tree/4.12.0) and the [paper](https://github.com/openjournals/joss-reviews/issues/3598#issuecomment-896177757).

In general, it looks like an impressive piece of work and suitable for JOSS in my opinion.

I have left two clarifying issues on the [bfit](https://github.com/dfujim/bfit) repo, and I have a minor question:
- [ ] https://github.com/dfujim/bfit/issues/105
- [ ] https://github.com/dfujim/bfit/issues/106
- [ ] In terms of specifics of large collaborations, it may be useful to acknowledge the relevant collaboration (TRIUMF) and software/analysis groups within the collaboration in case this software has profited from discussions and feedback internal to the collaboration.

After the above points are clarified/solved, I will be happy to recommend it for publication. 

(apologies for the delay on my side due to vacation)

**Comment by dfujim** [comment]
I have added to the acknowledgements as per your suggestion (76da12f9e894a8d9ec26914ee3c96135694f98c9)

**Comment by jpata** [comment]
> I can see that the issues you raised are now closed. Are you happy to recommend for publication?

Yes, all the issues I raised were resolved promptly and I'm happy to recommend this for publication!

**Comment by nicksisco1932** [comment]
I am happy with this as well, I didn't get any alerts so sorry if I was delaying anything. It performed as advertised and is well documented. All the best.

**Comment by lucydot** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03598/joss.03598/10.21105.joss.03598.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03598/joss.03598/10.21105.joss.03598.pdf) :page_facing_up: :point_left:

**Comment by lucydot** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.phpro.2012.04.027 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1016/S0168-9002(97)00048-X is OK
- 10.7566/JPSCP.21.011049 is OK
- 10.1016/j.phpro.2012.04.042 is OK
- 10.1016/j.nima.2014.07.029 is OK
- 10.1016/S0921-4526(00)00328-8 is OK
- 10.1016/j.ssnmr.2015.02.004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by lucydot** [comment]
Hello @dfujim  - congratulations, we are very close to accepting `bfit` for publication 🎈 

Please could you i) issue a new tagged release of the software (if changes have been made); ii) archive it (on, for example, Zenodo); iii) report the version number and archive DOI here on the thread.

**Comment by lucydot** [comment]
@jpata @nicksisco1932 thank-you for reviewing for JOSS ✨

**Comment by dfujim** [comment]
@lucydot thanks!

version: 4.14.1
doi: 10.5281/zenodo.5519795

**Comment by lucydot** [comment]
Hi @dfujim apologies for the late reply. We have a preference for the Zenodo archive to be named the same as the JOSS paper (e.g., bfit: A Python Application For Beta-Detected NMR). Is it possible to rename accordingly? I'll then recommend acceptance to the editor-in-chiefs.

**Comment by dfujim** [comment]
@lucydot ok, done!

**Comment by lucydot** [comment]
@whedon set 10.5281/zenodo.5519795 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5519795" target="_blank">10.5281/zenodo.5519795</a> is the archive.

**Comment by lucydot** [comment]
@whedon set 4.14.1 as version

**Comment by whedon** [comment]
OK. 4.14.1 is the version.

**Comment by lucydot** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.phpro.2012.04.027 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1016/S0168-9002(97)00048-X is OK
- 10.7566/JPSCP.21.011049 is OK
- 10.1016/j.phpro.2012.04.042 is OK
- 10.1016/j.nima.2014.07.029 is OK
- 10.1016/S0921-4526(00)00328-8 is OK
- 10.1016/j.ssnmr.2015.02.004 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2638

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2638, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by lucydot** [comment]
We are there! It has now been passed to one of the editor-in-chiefs for final processing 🎈

**Comment by danielskatz** [comment]
@whedon accept deposit=true

Looks good to me!

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1443634683615526916) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2639
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03598](https://doi.org/10.21105/joss.03598)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @dfujim (Derek Fujimoto)!!

And thanks to @nicksisco1932 and @jpata for reviewing, and @lucydot for editing!
We couldn't do this without you!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03598/status.svg)](https://doi.org/10.21105/joss.03598)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03598">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03598/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03598/status.svg
   :target: https://doi.org/10.21105/joss.03598
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03598/status.svg)](https://doi.org/10.21105/joss.03598)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by dfujim** [comment]
Great, thanks everyone!
