### ISSUE TITLE
Submission: gwdegree: A Shiny App to Aid Interpretation of Geometrically-Weighted Degree Estimates in Exponential Random Graph Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#36]
**Submitting author:** @michaellevy (<a href="http://orcid.org/0000-0002-4188-2527">Michael Levy</a>)
**Repository:** <a href="https://github.com/michaellevy/gwdegree" target ="_blank">https://github.com/michaellevy/gwdegree</a>
**Version:** v0.1.1
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.57495" target ="_blank">http://dx.doi.org/10.5281/zenodo.57495</a>

## Status

[![status](http://joss.theoj.org/papers/0f4eda35180f77176ce495cd4d711075/status.svg)](http://joss.theoj.org/papers/0f4eda35180f77176ce495cd4d711075)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0f4eda35180f77176ce495cd4d711075"><img src="http://joss.theoj.org/papers/0f4eda35180f77176ce495cd4d711075/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0f4eda35180f77176ce495cd4d711075/status.svg)](http://joss.theoj.org/papers/0f4eda35180f77176ce495cd4d711075)
```

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/michaellevy/gwdegree">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00036.pdf](https://github.com/openjournals/joss-reviews/files/355831/10.21105.joss.00036.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by amoeba** [comment]
✋ I can review this today.

**Comment by amoeba** [comment]
Grade: 2 (Minor revisions)

General comments:

The software is easy to use and I was pleased to find a high level of attention to detail on the design of the interactive tool and the accompanying writing. The software works and works well. I can see clear research application.


Specific notes requiring action:

- **License:** Repository does contain a plain-text `LICENSE` file but the file does not contain the text of an OSI-approved license. The `DESCRIPTION` file does, however. @arfon How is JOSS handling this case, which seems to apply to submissions of R packages that must go through submission to CRAN?
- **Version:** The GitHub repository does not have any releases. Submitted version is 0.1.0, CRAN version is 0.1.1. @arfon do we need to get the JOSS version in line with the CRAN version? I tested the CRAN-submitted 0.1.1 version.
- **Installation:**: While the software does install as described in the documentation (README.md in the repo), the information was hard to find. Suggest breaking the README into sections, including a section for 'Installation' or at least putting the installation information in an easier to find location.
- **Performance:** No specific performance claims were made, and I find the application performs adequately and I would expect the software to have acceptable performance on other computers.
- **Example usage:** The software is an interactive tool and I found the tool contained in-context instruction on usage.
- **Functionality documentation:** See above.
- **Community guidelines:**: No on (1), (2), and (3). Suggest adding these sections to README.
- **Paper**:
  - Paper contains "Use" instructions, which — according to my maybe-wrong interpretation of — the [JOSS Reviewer Guidelines](http://joss.theoj.org/about#reviewer_guidelines) forbid. Suggest removing the "Use" paragraph from the paper.


Comments on the README.me in the repo:

- README references 'tabs' but if the user starts with the readme, they haven't seen the app (and its tabs). Consider explaining or showing the app before referencing the tabs.
- The link "There is a working version online", 404s. Suggest fixing link.
- As noted specifically above, I would suggest breaking the README up into a few major sections, covering installation, usage, a high-level overview of the software, and the community guidelines sections. The writing you have is already very good.

Please let me know if I can explain anything in more detail. Thanks!

**Comment by michaellevy** [comment]
Thanks for the quick review, @amoeba! I think I've addressed all these things in michaellevy/gwdegree@dbdbc47. A couple points:

- v0.1.0 is what I originally submitted, but v0.1.1 (current on CRAN and GitHub) is much prefered. Recognizing the journal wants to review just one version, I hope this can be accommodated.

- I left the LICENSE file as is, per CRAN's protocol; not sure if it would bother anyone to include the text of the license there. Happy to test this on my next update.

**Comment by amoeba** [comment]
Grade: 1 (Accept)

I reviewed your changes and they address all of my concerns. Thanks!

I subsequently checked off the remaining items on the Reviewer questions checklist. In #37, it seems like JOSS may be okay with R packages that are on CRAN following the CRAN guidelines, which you have done. I've checked off the corresponding list item. It really does look like CRAN will reject a submission that includes the text of a license in a `LICENSE` file.

@arfon I reviewed v 0.1.1, and this submission is for 0.1.0. Can we just change this submission to be for 0.1.1 and be done?

**Comment by arfon** [comment]
> - I left the LICENSE file as is, per CRAN's protocol; not sure if it would bother anyone to include the text of the license there. Happy to test this on my next update.

This is OK I think @michaellevy 

Thanks for the rapid review @amoeba!

> @arfon I reviewed v 0.1.1, and this submission is for 0.1.0. Can we just change this submission to be for 0.1.1 and be done?

Sounds good to me.

@michaellevy - I think the final thing here is to make an archive of the software in Zenodo/figshare/other similar service and update this thread with the archive DOI.

**Comment by michaellevy** [comment]
Great! Here is the archive: [![DOI](https://zenodo.org/badge/23239/michaellevy/gwdegree.svg)](https://zenodo.org/badge/latestdoi/23239/michaellevy/gwdegree)

Thanks @arfon and @amoeba, this whole process has been smooth, fast, and edifying.

**Comment by arfon** [comment]
@michaellevy - this is now accepted into JOSS! Your DOI will be http://dx.doi.org/10.21105/joss.00036 . The Crossref processing queues are a little backed up right now but the DOI should be live in the next couple of hours ⚡ 🚀 💥
