### ISSUE TITLE
[PRE REVIEW]: latentcor: An R Package for estimating latent correlations from mixed data types

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3602]
**Submitting author:** @muellsen (<a href="http://orcid.org/0000-0002-3821-7083">Christian Lorenz Müller</a>)
**Repository:** <a href="https://github.com/mingzehuang/latentcor" target ="_blank">https://github.com/mingzehuang/latentcor</a>
**Version:** v1.0.0
**Editor:** @crvernon
**Reviewers:** @corybrunson, @rmflight 
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4a6c419d1fb73148cbf13881b97c5ba9/status.svg)](https://joss.theoj.org/papers/4a6c419d1fb73148cbf13881b97c5ba9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4a6c419d1fb73148cbf13881b97c5ba9"><img src="https://joss.theoj.org/papers/4a6c419d1fb73148cbf13881b97c5ba9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4a6c419d1fb73148cbf13881b97c5ba9/status.svg)](https://joss.theoj.org/papers/4a6c419d1fb73148cbf13881b97c5ba9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @muellsen. **Currently, there isn't an JOSS editor assigned** to your paper.

@muellsen if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1567

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (449.1 files/s, 71869.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             8            332             92           1825
R                               11             73            266            557
XML                              1              0              2            441
CSS                              3             99             48            428
JavaScript                       4             64             34            266
Markdown                         2             59              0            193
TeX                              2              6              0            162
YAML                             3             23              2            115
Rmd                              1            146            452             64
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            36            802            897           4062
-------------------------------------------------------------------------------


Statistical information for the repository '6dc6361899e5e8c324e4d44e' was
gathered on 2021/08/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Mingze Huang                     3         35945          35581          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mingze Huang                364            1.0          0.0                9.34
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03602/joss.03602/10.21105.joss.03602.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03602/joss.03602/10.21105.joss.03602.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@muellsen – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by irinagain** [comment]
@whedon generate pdf

**Comment by irinagain** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/biomet/asaa007 is OK
- 10.1080/00401706.2012.727746 is OK
- 10.1111/rssb.12168 is OK
- 10.1080/10618600.2021.1882468 is OK
- 10.21105/joss.02306 is OK
- 10.3389/fgene.2019.00516 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by crvernon** [comment]
@mingzehuang @irinagain  @muellsen The JOSS editorial board reviewed your submission and found that it does meet our standards to proceed to review.  I'll be taking this on as your topic editor.

**Comment by crvernon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @crvernon

**Comment by crvernon** [comment]
@mingzehuang @irinagain @muellsen  The first step in this pre-review is to find at least 2 reviewers. If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this [list of people](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by muellsen** [comment]
@crvernon This is amazing 

> @mingzehuang @irinagain @muellsen The JOSS editorial board reviewed your submission and found that it does meet our standards to proceed to review. I'll be taking this on as your topic editor.

@crvernon Thanks so much for these great news! We'll discussing tomorrow potential reviewers and get back to you!

**Comment by muellsen** [comment]
> @mingzehuang @irinagain @muellsen The first step in this pre-review is to find at least 2 reviewers. If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this [list of people](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

 Two potential reviewers (based on packages related to ours) could be:  corybrunson rmflight

**Comment by crvernon** [comment]
:wave: @corybrunson @rmflight - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by rmflight** [comment]
Sure @crvernon, I think I can review this, as long as I'm not trying to completely match the theoretical explanations in the package vignette to the code.

What kind of timeframe are we looking for a first review?

**Comment by corybrunson** [comment]
@crvernon i would be glad to! I can get through preliminaries today and complete initial issues within 3 weeks.

**Comment by crvernon** [comment]
@rmflight We aim for reviews to be completed within about 2-4 weeks.  I'll get the full review kicked off if you are good with that time frame.  Sound ok?

**Comment by crvernon** [comment]
@whedon assign @corybrunson as reviewer

**Comment by whedon** [comment]
OK, @corybrunson is now a reviewer

**Comment by crvernon** [comment]
@whedon add @rmflight  as reviewer

**Comment by whedon** [comment]
OK, @rmflight  is now a reviewer

**Comment by crvernon** [comment]
Alright @corybrunson @rmflight @muellsen  I am going to close this Pre-Review and kick off the full review which you should receive a notification for.  Thanks!

**Comment by crvernon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3634.
