### ISSUE TITLE
[PRE REVIEW]: ESVM : An Electrostatic Vlasov-Maxwell Open-source Code

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3604]
**Submitting author:** @michaeltouati (<a href="http://orcid.org/0000-0001-7590-0941">Michael Touati</a>)
**Repository:** <a href="https://github.com/michaeltouati/ESVM" target ="_blank">https://github.com/michaeltouati/ESVM</a>
**Version:** v1.0.0
**Editor:** @danielskatz
**Reviewers:** @tclune, @TomGoffrey
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d0f6a6298710d69b63a8a62d843f8f88/status.svg)](https://joss.theoj.org/papers/d0f6a6298710d69b63a8a62d843f8f88)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d0f6a6298710d69b63a8a62d843f8f88"><img src="https://joss.theoj.org/papers/d0f6a6298710d69b63a8a62d843f8f88/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d0f6a6298710d69b63a8a62d843f8f88/status.svg)](https://joss.theoj.org/papers/d0f6a6298710d69b63a8a62d843f8f88)
```

**Author instructions**

Thanks for submitting your paper to JOSS @michaeltouati. **Currently, there isn't an JOSS editor assigned** to your paper.

@michaeltouati if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1039

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.48 s (8.1 files/s, 1395.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                       7             89            183            946
Python                           2             41             30            573
Markdown                         1             15              0             88
make                             1             31             31             37
TeX                              1              1              0              0
-------------------------------------------------------------------------------
SUM:                            12            177            244           1644
-------------------------------------------------------------------------------


Statistical information for the repository 'd96029d4d8fac1c3f7e74601' was
gathered on 2021/08/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
michaeltouati                    3          1288            644          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael Touati              644          100.0          0.0                4.66
```

**Comment by arfon** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by arfon** [comment]
Thanks @danielskatz!

**Comment by danielskatz** [comment]
@michaeltouati - I'll be editing your submission. The first step is to find at least 2 reviewers. If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by danielskatz** [comment]
👋 @rouson & @tclune - Would one of you be able to review this submission for JOSS? I'm particularly looking for one reviewer with expertise in Fortran good/best practices around packaging, testing, distribution, etc. Or do you have suggestions for someone else in this area?

**Comment by danielskatz** [comment]
👋 @rouson & @tclune - just checking with you again on this...

**Comment by danielskatz** [comment]
@michaeltouati -Again, the first step is to find at least 2 reviewers. If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by tclune** [comment]
@danielskatz I was hoping @rouson would blink first.  :-)     I'm a bit swamped at work over the next couple of weeks  - if the review can be delayed until early/mid September, you can consider me signed on.

**Comment by michaeltouati** [comment]
Dear Tom,

I can recommend this list of potential reviewer :

- @sigvaldm ***@***.*** ***@***.***>)
- @CFGrote ***@***.*** ***@***.***>)
- @joglekara ***@***.*** ***@***.***>)
- @TomGoffrey ***@***.*** ***@***.***>)

Thanking you,
Best regards,
Michaël

**Comment by danielskatz** [comment]
👋 @sigvaldm, @CFGrote, @joglekara, @TomGoffrey - Would one of you be willing to review this submission to JOSS?

**Comment by danielskatz** [comment]
👋 @tclune - we can wait a bit to get started, so I'll accept your "volunteering" :)
I'll add you as a reviewer, though we won't start the formal review until there's also a second reviewer, and I won't expect you to start immediately after that in any case.

**Comment by danielskatz** [comment]
@whedon assign @tclune as reviewer

**Comment by whedon** [comment]
OK, @tclune is now a reviewer

**Comment by TomGoffrey** [comment]
@danielskatz Sure, I can take a look.

**Comment by danielskatz** [comment]
@TomGoffrey - thanks very much - I'll add you and will start the review.

**Comment by danielskatz** [comment]
@whedon add @TomGoffrey as reviewer

**Comment by whedon** [comment]
OK, @TomGoffrey is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3618.

**Comment by rouson** [comment]
@danielskatz sorry for the delay.  If it's not too late, I would like to review this submission too.

**Comment by danielskatz** [comment]
Ok, I'll add you in https://github.com/openjournals/joss-reviews/issues/3618 - see you over there
