### ISSUE TITLE
[PRE REVIEW]: stochvolTMB: An R-package for likelihood estimation of stochastic volatility models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3614]
**Submitting author:** @JensWahl (<a href="http://orcid.org/0000-0002-3812-5111">Jens Christian Wahl</a>)
**Repository:** <a href="https://github.com/JensWahl/stochvolTMB.git" target ="_blank">https://github.com/JensWahl/stochvolTMB.git</a>
**Version:** v0.2.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2b5fbf91076fa880aeb6541d919de74f/status.svg)](https://joss.theoj.org/papers/2b5fbf91076fa880aeb6541d919de74f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2b5fbf91076fa880aeb6541d919de74f"><img src="https://joss.theoj.org/papers/2b5fbf91076fa880aeb6541d919de74f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2b5fbf91076fa880aeb6541d919de74f/status.svg)](https://joss.theoj.org/papers/2b5fbf91076fa880aeb6541d919de74f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @JensWahl. **Currently, there isn't an JOSS editor assigned** to your paper.

@JensWahl if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 873

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (399.6 files/s, 81696.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              0             21           2450
HTML                             1            347              5           1459
Markdown                         5            192              0            778
R                               18            340            269            724
TeX                              3             17              0            201
C++                              3             64             34            135
Rmd                              3            129            234             80
YAML                             1             14              0             65
make                             1              0              1              5
-------------------------------------------------------------------------------
SUM:                            37           1103            564           5897
-------------------------------------------------------------------------------


Statistical information for the repository 'ded86199df04783dc4694dce' was
gathered on 2021/08/14.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jens Christian Wahl              3           184              5           19.81
JensWahl                        26           410            355           80.19

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jens Christian Wahl           1            0.5         17.3                0.00
JensWahl                    232           56.6         16.7               14.66
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03614/joss.03614/10.21105.joss.03614.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03614/joss.03614/10.21105.joss.03614.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v070.i05 is OK
- 10.18637/jss.v069.i05 is OK
- 10.1080/07474930600713424 is OK
- 10.2307/2297980 is OK

MISSING DOIs

- 10.1007/978-1-4612-0919-5_38 may be a valid DOI for title: Information theory and an extension of the maximum likelihood principle

INVALID DOIs

- https://doi.org/10.1016/j.csda.2013.10.005 is INVALID because of 'https://doi.org/' prefix
```

**Comment by arfon** [comment]
@JensWahl – due to the relatively small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by JensWahl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03614/joss.03614/10.21105.joss.03614.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03614/joss.03614/10.21105.joss.03614.pdf) :page_facing_up: :point_left:

**Comment by JensWahl** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18637/jss.v070.i05 is OK
- 10.18637/jss.v069.i05 is OK
- 10.1080/07474930600713424 is OK
- 10.2307/2297980 is OK
- 10.1007/978-1-4612-0919-5_38 is OK
- 10.1016/j.csda.2013.10.005 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@JensWahl - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
