### ISSUE TITLE
[PRE REVIEW]: Bam-readcount - rapid generation of basepair-resolution sequence metrics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3615]
**Submitting author:** @chrisamiller (<a href="http://orcid.org/0000-0003-4266-6700">Christopher A. Miller</a>)
**Repository:** <a href="https://github.com/genome/bam-readcount" target ="_blank">https://github.com/genome/bam-readcount</a>
**Version:** 1.0
**Editor:** @lpantano
**Reviewers:** @friedue
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1bcbb483ff8b512cc4598e44807ce8a2/status.svg)](https://joss.theoj.org/papers/1bcbb483ff8b512cc4598e44807ce8a2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1bcbb483ff8b512cc4598e44807ce8a2"><img src="https://joss.theoj.org/papers/1bcbb483ff8b512cc4598e44807ce8a2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1bcbb483ff8b512cc4598e44807ce8a2/status.svg)](https://joss.theoj.org/papers/1bcbb483ff8b512cc4598e44807ce8a2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @chrisamiller. **Currently, there isn't an JOSS editor assigned** to your paper.

@chrisamiller if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3615 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (887.3 files/s, 82996.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CMake                           20            210            404            960
Python                           5            112            223            914
C++                              8            140            111            846
Markdown                         5            100              0            169
C/C++ Header                     5             29              0            128
XSLT                             1              5              0            112
Perl                             2             24              0             96
Dockerfile                       1              9              6             27
YAML                             1              0              0             21
diff                             1              4             16             10
Bourne Shell                     1              0              0              1
-------------------------------------------------------------------------------
SUM:                            50            633            760           3284
-------------------------------------------------------------------------------


Statistical information for the repository 'f0cffad0752c12cffc3802f3' was
gathered on 2021/08/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ajay Khanna                      9           110             47            2.84
Chris Miller                     2             9              1            0.18
Dave Larson                     57          1358            866           40.30
Morgan Taschuk                   1             1              1            0.04
Sam Brightman                    1             4              4            0.14
Travis Abbott                   16          1133            986           38.39
dlarson                          7           973             26           18.10

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ajay Khanna                  92           83.6         13.3               16.30
Chris Miller                  7           77.8         78.8                0.00
Dave Larson                 865           63.7         83.8                6.47
Morgan Taschuk                1          100.0         72.7                0.00
Sam Brightman                 4          100.0         58.8                0.00
Travis Abbott               546           48.2        102.9                9.89
```

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03615/joss.03615/10.21105.joss.03615.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03615/joss.03615/10.21105.joss.03615.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1101/2020.12.16.423064 may be a valid DOI for title: HTSlib: C library for reading/writing high-throughput sequencing data
- 10.1111/gcb.15291 may be a valid DOI for title: Rapid genomic and phenotypic change in response to climate warming in a widespread plant invader
- 10.1186/s12920-019-0508-5 may be a valid DOI for title: NeoMutate: an ensemble machine learning framework for the prediction of somatic mutations in cancer
- 10.1093/bioinformatics/btw536 may be a valid DOI for title: SiNVICT: ultra-sensitive detection of single nucleotide variants and indels in circulating tumour DNA
- 10.1038/s41375-018-0193-y may be a valid DOI for title: Discriminating a common somatic ASXL1 mutation (c.1934dup; p.G646Wfs*12) from artifact in myeloid malignancies using NGS
- 10.1182/blood-2017-03-735654 may be a valid DOI for title: The NCI Genomic Data Commons as an engine for precision medicine
- 10.1002/0471250953.bi1504s44 may be a valid DOI for title: Using VarScan 2 for Germline Variant Calling and Somatic Mutation Detection
- 10.1101/2021.05.06.21256753 may be a valid DOI for title: A direct capture method for purification and detection of viral nucleic acid enables epidemiological surveillance of SARS-CoV-2
- 10.1038/s41598-020-64708-8 may be a valid DOI for title: Detection of low-frequency resistance-mediating SNPs in next-generation sequencing data of Mycobacterium tuberculosis complex strains with binoSNP
- 10.1093/bioinformatics/bty518 may be a valid DOI for title: appreci8: a pipeline for precise variant calling integrating 8 tools
- 10.1101/mcs.a002444 may be a valid DOI for title: Resistance-promoting effects of ependymoma treatment revealed through genomic analysis of multiple recurrences in a single patient
- 10.1038/s41588-018-0257-y may be a valid DOI for title: A deep learning approach to automate refinement of somatic variant calling from cancer sequencing data
- 10.1093/bioinformatics/bty316 may be a valid DOI for title: CONICS integrates scRNA-seq with DNA sequencing to map gene expression to tumor sub-clones

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@chrisamiller - thanks for your submission to JOSS. We're currently managing a large backlog of submissions and the editor most appropriate for your area is already rather busy.  For now, we will need to waitlist this paper and process it as the queue reduces. Thanks for your patience!

While you wait, if you want to fix the DOIs (noting that Whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by chrisamiller** [comment]
Happy to utilize one of the other editors with genomics experience, if that helps things. Yes, we'll get the dois cleaned up - thank you!

**Comment by kthyng** [comment]
@lpantano Would you be able to edit this submission?

**Comment by kthyng** [comment]
@whedon invite @lpantano as editor

**Comment by whedon** [comment]
@lpantano has been invited to edit this submission.

**Comment by lpantano** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @lpantano

**Comment by apldx** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3615 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by apldx** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03615/joss.03615/10.21105.joss.03615.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03615/joss.03615/10.21105.joss.03615.pdf) :page_facing_up: :point_left:

**Comment by apldx** [comment]
@whedon check references

**Comment by lpantano** [comment]
@whedon check references from custom branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by lpantano** [comment]
hi @chrisamiller, would you suggest any reviewer from the list? i keep looking for reviewers meanwhile. thanks!

**Comment by chrisamiller** [comment]
From a quick look, it seems like any of these folks would have the relevant expertise:

standage
afrubin
will-rowe
ctb
iskandr
kortschak
VivekTodur

**Comment by lpantano** [comment]
@kortschak, would you like and have time to review this tool? Thanks!

**Comment by kortschak** [comment]
i'm afraid that I don't have time to do this right now.

**Comment by lpantano** [comment]
Hi @oliviamr and @iskandr, would you like and have time to review this tool? Thanks! 
As a reminder, our review process happens in github, [read more](https://joss.readthedocs.io/en/latest/review_criteria.html). JOSS encourages best practices and helps the reviewer with a list to go over during the process to make it as easier as possible.

**Comment by lpantano** [comment]
@whedon assign @friedue as reviewer

**Comment by whedon** [comment]
OK, @friedue is now a reviewer

**Comment by lpantano** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3722.
