### ISSUE TITLE
[PRE REVIEW]: OpenCMP: An Open-Source Computational Multiphysics Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3626]
**Submitting author:** @nasserma (<a href="http://orcid.org/0000-0002-1772-0376">Nasser Mohieddin Abukhdeir</a>)
**Repository:** <a href="https://github.com/uw-comphys/opencmp" target ="_blank">https://github.com/uw-comphys/opencmp</a>
**Version:** 1.0
**Editor:** @lucydot
**Reviewers:** @bonh, @WilkAndy
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/efe19348de7efe519e1db433f5692960/status.svg)](https://joss.theoj.org/papers/efe19348de7efe519e1db433f5692960)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/efe19348de7efe519e1db433f5692960"><img src="https://joss.theoj.org/papers/efe19348de7efe519e1db433f5692960/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/efe19348de7efe519e1db433f5692960/status.svg)](https://joss.theoj.org/papers/efe19348de7efe519e1db433f5692960)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nasserma. **Currently, there isn't an JOSS editor assigned** to your paper.

@nasserma if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3626 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.26 s (380.6 files/s, 61381.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          57           2512           4654           5947
reStructuredText                39            798            692           1302
Markdown                         2             24              0             19
make                             1              4              6              9
-------------------------------------------------------------------------------
SUM:                            99           3338           5352           7277
-------------------------------------------------------------------------------


Statistical information for the repository '2a3949ee24af691dd6e60f26' was
gathered on 2021/08/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
elizabethmonte                   6         17212           4099          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
elizabethmonte            13113           76.2          1.3               24.41
```

**Comment by kthyng** [comment]
@whedon generate pdf from branch publications

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03626/joss.03626/10.21105.joss.03626.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03626/joss.03626/10.21105.joss.03626.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@lucydot Would you be willing to take on this submission? Looks like a reasonable fit.

**Comment by kthyng** [comment]
@whedon invite @lucydot as editor

**Comment by whedon** [comment]
@lucydot has been invited to edit this submission.

**Comment by lucydot** [comment]
Hi @kthyng I am happy to be assigned to this submission - though please note that I am out of office from end of today until the 30th of August. If that delay is ok your end, please do assign this to me.

**Comment by kthyng** [comment]
Thanks @lucydot! Yes, let's just have you pick this up when you return to the office.

**Comment by kthyng** [comment]
@whedon assign @lucydot as editor

**Comment by whedon** [comment]
OK, the editor is @lucydot

**Comment by lucydot** [comment]
Hi @nasserma I'll be your editor for this submission 👋

Do you have any suggestions for potential reviewers? If so it'd be useful if you could mention them here in this thread (without tagging them with an @). In addition, [this list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) of people have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by nasserma** [comment]
Hello @lucydot, thanks for agreeing to be the editor for our submission. We have gone through the list of reviewers you provided and, in reverse order from their appearance on the list:

1481) TJFord
1360) jamiebramwell
1093) bonh
451) mikaem
351) ctdegroot
302) highlando

**Comment by lucydot** [comment]
Hi @nasserma thanks for the suggestions.

Hi @highlando and @jamiebramwell :wave: are you available to review this submission? Seems that you both have the Python and domain specific expertise needed.

**Comment by lucydot** [comment]
Hi @highlando thanks for your prompt reply. I'll ask some other potential reviewers if they can start sooner - thanks, Lucy.

Hi @ctdegroot and @TJFord 👋 are either of you available to review this submission?

**Comment by ctdegroot** [comment]
Unfortunately I am not available at this time

**Comment by lucydot** [comment]
Thanks for letting us know @ctdegroot. 

Hi @bonh 👋 are you available to review this submission?

**Comment by bonh** [comment]
Hi @lucydot ! This looks really interesting and I would enjoy reviewing it.

**Comment by lucydot** [comment]
Excellent thanks @bonh

**Comment by lucydot** [comment]
@whedon assign @bonh as reviewer

**Comment by whedon** [comment]
OK, @bonh is now a reviewer

**Comment by lucydot** [comment]
@WilkAndy has also agreed to be reviewer 🎈

**Comment by lucydot** [comment]
@whedon add @WilkAndy as reviewer

**Comment by whedon** [comment]
OK, @WilkAndy is now a reviewer

**Comment by lucydot** [comment]
I'll ask our bot Whedon to start a review issue thread (this is the pre-review thread) - the review guidelines will be listed at the top of that new thread.

@WilkAndy @bonh thank-you for agreeing to review. We're asking for reviews to be complete within a 4-6 week period. As the review is usually an iterative process (rather than something you do in one sitting) it's best for reviews to start earlier in that timeline.

**Comment by lucydot** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3742.
