### ISSUE TITLE
[PRE REVIEW]: Automatic image-based phytoplankton classification tool

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3627]
**Submitting author:** @mcf1110 (<a href="http://orcid.org/0000-0002-5118-2399">Matheus Campos Fernandes</a>)
**Repository:** <a href="https://github.com/mcf1110/planktool" target ="_blank">https://github.com/mcf1110/planktool</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6ac8b955f9261023a001406824325453/status.svg)](https://joss.theoj.org/papers/6ac8b955f9261023a001406824325453)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6ac8b955f9261023a001406824325453"><img src="https://joss.theoj.org/papers/6ac8b955f9261023a001406824325453/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6ac8b955f9261023a001406824325453/status.svg)](https://joss.theoj.org/papers/6ac8b955f9261023a001406824325453)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mcf1110. **Currently, there isn't an JOSS editor assigned** to your paper.

@mcf1110 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 781

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (445.3 files/s, 40914.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          12            266            365            613
HTML                             1              2              0            105
JavaScript                       1              9              0             89
Markdown                         2             32              0             88
YAML                             1              0              0             58
TeX                              1              3              0             24
-------------------------------------------------------------------------------
SUM:                            18            312            365            977
-------------------------------------------------------------------------------


Statistical information for the repository '6db86f2b432cfe947bb9d595' was
gathered on 2021/08/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Matheus Fernandes                1          1342              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Matheus Fernandes          1342          100.0          0.0                8.27
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3627 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (6f6c27c44ac9d75436eb54d9/paper.md): mapping values are not allowed in this context at line 11 column 57 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by mcf1110** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3627 with the following error: 
```
 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.294 ...inkurl{fernandes.matheus@ufabc.edu.br}}}}

Looks like we failed to compile the PDF

```

**Comment by mcf1110** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03627/joss.03627/10.21105.joss.03627.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03627/joss.03627/10.21105.joss.03627.pdf) :page_facing_up: :point_left:

**Comment by mcf1110** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @mcf1110 and thanks for your submission. I have run the "query scope" command which will ping the editorial board to check to see if this submission is in scope. In particular, the concern is whether it is enough of [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This process will take 1-2 weeks, thanks for your patience.

**Comment by danielskatz** [comment]
👋 @mcf1110 - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
