### ISSUE TITLE
[PRE REVIEW]: Simframe: A Python Framework for Scientific Simulations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3628]
**Submitting author:** @stammler (<a href="http://orcid.org/0000-0002-1589-1796">Sebastian Markus Stammler</a>)
**Repository:** <a href="https://github.com/stammler/simframe" target ="_blank">https://github.com/stammler/simframe</a>
**Version:** 0.5.4
**Editor:** @taless474
**Reviewers:** @schruste, @lucaferranti
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0ef61e034c57445e846b2ec383c920a6/status.svg)](https://joss.theoj.org/papers/0ef61e034c57445e846b2ec383c920a6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0ef61e034c57445e846b2ec383c920a6"><img src="https://joss.theoj.org/papers/0ef61e034c57445e846b2ec383c920a6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0ef61e034c57445e846b2ec383c920a6/status.svg)](https://joss.theoj.org/papers/0ef61e034c57445e846b2ec383c920a6)
```

**Author instructions**

Thanks for submitting your paper to JOSS @stammler. **Currently, there isn't an JOSS editor assigned** to your paper.

@stammler if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 858

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.18 s (440.3 files/s, 228734.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          67           1050           1650           3056
Jupyter Notebook                 7              0          35289            782
Markdown                         2             37              0             84
DOS Batch                        1              8              1             26
reStructuredText                 2             15             23             14
YAML                             1              4              7              9
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            81           1118          36977           3980
-------------------------------------------------------------------------------


Statistical information for the repository '31f0c4ccfe890da12b1c1b73' was
gathered on 2021/08/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Sebastian Stammler             107          9220           3570           98.89
birnstiel                        3           127             17            1.11

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Sebastian Stammler         5661           61.4          7.9                6.41
Til Birnstiel                95          100.0         12.2               24.21
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3628 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by birnstiel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03628/joss.03628/10.21105.joss.03628.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03628/joss.03628/10.21105.joss.03628.pdf) :page_facing_up: :point_left:

**Comment by stammler** [comment]
Potential reviewers may be: schruste, lucaferranti, felipefr, justinsgray, sigvaldm, ketch, nespinoza.

**Comment by kthyng** [comment]
Hi @taless474! Would this submission be a good fit for you?

**Comment by kthyng** [comment]
@whedon invite @taless474 as editor

**Comment by whedon** [comment]
@taless474 has been invited to edit this submission.

**Comment by taless474** [comment]
> Hi @taless474! Would this submission be a good fit for you?

Yes, I like it :+1

**Comment by taless474** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @taless474

**Comment by taless474** [comment]
@schruste, @ketch will you be able to review this?

**Comment by schruste** [comment]
Yes, I can do that.

**Comment by ketch** [comment]
I read the paper and I have to say, respectfully, that I am opposed to the promotion of this package.  As the authors state, there are already plenty of existing packages that fulfill this function.  In fact, those packages do it much better than this one.  The package under consideration claims to be helpful for "beginners", but it mainly gives those beginners a set options most of which should never be used by anyone. Beginners would, in my opinion, be much better off using one of the standard existing packages that focus on state-of-the-art methods and have a lot more (numerical and mathematical) functionality.

I'm sure the authors won't be pleased to hear this.  I do respect what they are doing and it is fine to do it.  I just wouldn't recommend that other people use it.

As far as I know, the kind of evaluation I'm doing here is not what is asked for as a reviewer for JOSS, so I think it's best if I don't review this package further.

**Comment by danielskatz** [comment]
👋@stammler & @taless474 - based on the comment from @ketch above, let's hold off on reviewing this and do a scope query so editors can make sure it's reasonable for us to review this.  I'll start the process, and it should take a week or two. Because doing this after an editor has been assigned is a little awkward, I'm also going to put a reminder in for 2 weeks for now to make sure we don't drop this.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@whedon remind @openjournals/joss-eics in 2 weeks

**Comment by whedon** [comment]
Sorry, I can't set reminders on PRE-REVIEW issues.

**Comment by stammler** [comment]
Thank you, @danielskatz, for letting us know about the query scope.

And thank you for your sincere comment, @ketch. No offense taken.

Since we think that there might be a slight misunderstanding on the scope of the software we feel the need to clarify that the point of `simframe` is _not_ the integration schemes provided by it, but _mainly_ the framework around it.
With `simframe` it is possible to easily set up data structures for scientific simulations and assign update functions (i.e. how to recalculate one quantity from the rest of the data of the frame) or to define derivatives of the fields, which are then automatically integrated.

The simple integration schemes we provided are just included so the users have some default options to start with. It is a matter of minutes to implement custom integrations schemes as is also described in the documentation. If someone wants to use the more elaborate methods `solve_ivp` or `odeint` of SciPy, this can be done easily. However, in contrast to those methods, `simframe` is less of a black box, and more of a toolbox.

The point of `simframe` is the organization of a scientific simulation or scientific data and the calculation of derived quantities (including the I/O) and the integration is just a convenient extra feature. If the problem does not require integration, it is entirely possible to use `simframe` in a scientific context without integrating anything at all due to its modular structure and its update functionality. `simframe` is, for example, already used by the [DustPy](https://stammler.github.io/dustpy/) project to calculate the evolution of dust in protoplanetary disks and with it there are already at least [eight peer-reviewed publications](https://stammler.github.io/dustpy/A_publications.html) that make use of `simframe`.

We hope this additional information can be helpful for the decision towards a possible JOSS publication.

**Comment by birnstiel** [comment]
Since the reminder didn't seem to work: any news from the editorial review?

**Comment by danielskatz** [comment]
Sorry @birnstiel - this got a little lost (and thanks for reminding us) - I hope we'll finish the discussion soon.

**Comment by danielskatz** [comment]
👋 @openjournals/joss-eics, just a ping that we should try to finish this soon - I put a note in slack to try to move it forward again

**Comment by danielskatz** [comment]
After some editorial discussion, we have decided to proceed with the review.

**Comment by stammler** [comment]
Since we haven't heard anything since the last message, we just wanted to quickly ask if there is anything we have to do right now or is everything set?

**Comment by kyleniemeyer** [comment]
@whedon add @schruste as reviewer

**Comment by whedon** [comment]
OK, @schruste is now a reviewer

**Comment by taless474** [comment]
@ctdegroot Are you interested in reviewing this?

**Comment by taless474** [comment]
@felipefr Are you interested in reviewing this?

**Comment by taless474** [comment]
@lucaferranti, @justinsgray, @sigvaldm, is any of you interested in reviewing this?

**Comment by lucaferranti** [comment]
@taless474 yes I can review this

**Comment by taless474** [comment]
@whedon add @lucaferranti as reviewer

**Comment by whedon** [comment]
OK, @lucaferranti is now a reviewer

**Comment by taless474** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3882.

**Comment by JustinSGray** [comment]
I can review this

**Comment by taless474** [comment]
Thank you for your response @JustinSGray. I think we are set for now.
