### ISSUE TITLE
[PRE REVIEW]: TX2: Transformer eXplainability and eXploration

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3629]
**Submitting author:** @WildfireXIII (<a href="http://orcid.org/0000-0002-5036-5433">Nathan Martindale</a>)
**Repository:** <a href="https://github.com/ORNL/tx2" target ="_blank">https://github.com/ORNL/tx2</a>
**Version:** 2021.8.0
**Editor:** @fabian-s
**Reviewers:** @assenmacher-mat, @sara-02
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b7c161917e5a31af052a597bf98f0e94/status.svg)](https://joss.theoj.org/papers/b7c161917e5a31af052a597bf98f0e94)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b7c161917e5a31af052a597bf98f0e94"><img src="https://joss.theoj.org/papers/b7c161917e5a31af052a597bf98f0e94/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b7c161917e5a31af052a597bf98f0e94/status.svg)](https://joss.theoj.org/papers/b7c161917e5a31af052a597bf98f0e94)
```

**Author instructions**

Thanks for submitting your paper to JOSS @WildfireXIII. **Currently, there isn't an JOSS editor assigned** to your paper.

@WildfireXIII if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1341

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (363.6 files/s, 178472.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      15           2516           2689           9868
HTML                            12           1495             36           2909
SVG                              1              0              0           2671
Python                           9            402            512           1630
CSS                              5            183             36            734
Jupyter Notebook                 2              0           2621            302
Markdown                         5             69              0            177
reStructuredText                 8            121            152            164
TeX                              1             17              0             96
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            60           4815           6054          18586
-------------------------------------------------------------------------------


Statistical information for the repository 'c260b34fd16b20d75fbf28c8' was
gathered on 2021/08/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Martindale, Nathan               7          2146             68           12.25
Nathan Martindale               16         15697            158           87.75

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Martindale, Nathan        17617          820.9          0.5               17.03
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18653/v1/P19-3007 is OK
- 10.1145/3366424.3383542 is OK

MISSING DOIs

- 10.18653/v1/2020.emnlp-demos.15 may be a valid DOI for title: The Language Interpretability Tool: Extensible, Interactive Visualizations and Analysis for NLP Models

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03629/joss.03629/10.21105.joss.03629.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03629/joss.03629/10.21105.joss.03629.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @fabian-s and @ajstewartlang! Are either of you reasonable fits for this submission? I am thinking @fabian-s from the machine learning side or @ajstewartlang from the language side.

**Comment by fabian-s** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @fabian-s

**Comment by fabian-s** [comment]
@kthyng sure, I'll do it

**Comment by fabian-s** [comment]
hey there, @richardlitt @desilinguist @assenmacher-mat
would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by RichardLitt** [comment]
Can’t this time. Thanks for asking.

**Comment by desilinguist** [comment]
Sorry, I’ll also have to pass this time.
________________________________

**Comment by fabian-s** [comment]
@jkahn @fil would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by fabian-s** [comment]
@whedon add @assenmacher-mat as reviewer

**Comment by whedon** [comment]
OK, @assenmacher-mat is now a reviewer

**Comment by Fil** [comment]
I don't have time right now, sorry!

**Comment by sara-02** [comment]
@fabian-s I am interested in reviewing this package, I am available post 8th Spetember.

**Comment by fabian-s** [comment]
@sara-02 thanks, that's soon enough.

**Comment by fabian-s** [comment]
@whedon add @sara-02 as reviewer

**Comment by whedon** [comment]
OK, @sara-02 is now a reviewer

**Comment by fabian-s** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3652.
