### ISSUE TITLE
[REVIEW]: The psyplot interactive visualization framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#363]
**Submitting author:** @Chilipp (<a href="http://orcid.org/0000-0001-6171-7716">Philipp S. Sommer</a>)
**Repository:** <a href="https://github.com/Chilipp/psyplot.git" target ="_blank">https://github.com/Chilipp/psyplot.git</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @Fil
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.845455" target="_blank">10.5281/zenodo.845455</a>

## Status

[![status](http://joss.theoj.org/papers/3535c28017003f0b5fb63b1b64118b60/status.svg)](http://joss.theoj.org/papers/3535c28017003f0b5fb63b1b64118b60)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3535c28017003f0b5fb63b1b64118b60"><img src="http://joss.theoj.org/papers/3535c28017003f0b5fb63b1b64118b60/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3535c28017003f0b5fb63b1b64118b60/status.svg)](http://joss.theoj.org/papers/3535c28017003f0b5fb63b1b64118b60)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Chilipp/psyplot.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@Fil, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Chilipp/psyplot.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@Chilipp) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @Fil it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@Fil - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by Fil** [comment]
@arfon this is my first review, so maybe my question is obvious: where is the "thing" that I'm reviewing? (not the software, which I found, but the paper that will be published — probably something named `paper.md`)

**Comment by arfon** [comment]
Hi @Fil. JOSS reviews are primarily about the software (https://github.com/Chilipp/psyplot.git). We also ask that you check that the associated paper (https://github.com/Chilipp/psyplot/blob/master/paper.md) meets the [recommended structure/content requirements](http://joss.theoj.org/about#paper_structure).

**Comment by Fil** [comment]
Yes absolutely. I'm mostly offline atm so was doing the simple admin things — will do the install later next week

**Comment by Fil** [comment]
@chilipp I've followed the installation procedure (conda in a virtualenv) and I can't seem to get the plot as a graphics. Here's what I get in a jupyter notebook (after `conda install nb_conda`).

<img width="1111" alt="capture d ecran 2017-08-17 a 09 10 35" src="https://user-images.githubusercontent.com/7001/29400172-88ebceba-832c-11e7-9556-247a268a32f5.png">

I was hoping to get the map as in the example http://psyplot.readthedocs.io/en/latest/getting_started.html

Alternatively, I couldn't find how to launch the psyplot gui (from http://psyplot.readthedocs.io/projects/psyplot-gui/en/latest/getting_started.html).

**Comment by Fil** [comment]
With psyplot-gui running, I was able to get the map plotted, and change its projection as in the example.

<img width="1344" alt="capture d ecran 2017-08-17 a 09 24 16" src="https://user-images.githubusercontent.com/7001/29400486-e02b0f50-832d-11e7-8f31-1b06473bcdde.png">

Minor corrections to the install procedure to explain if it is possible to use from jupyter notebook, and how to launch the gui would be welcome.

**Comment by Chilipp** [comment]
@Fil , thanks a lot for the feedback and your typo corrections! 

I added notes to the docs of psyplot, which should solve this problem (see the 2 first notes in the [Getting started](http://psyplot.readthedocs.io/en/latest/getting_started.html) example. Additionally I included a [section in the psyplot-gui docs](http://psyplot.readthedocs.io/projects/psyplot-gui/en/latest/getting_started.html#starting-the-gui) on how to start the GUI.

**Comment by Fil** [comment]
About the "Community Guidelines" item: the package's README only hints a github issues; it could say a bit more clearly how to contribute, and for example if pull requests, examples, and documentation are welcome.

**Comment by Fil** [comment]
About "References", please fix the references DOI:
- xarray according to http://xarray.pydata.org/en/stable/faq.html#how-should-i-cite-xarray
- matplotlib according to http://ieeexplore.ieee.org/document/4160265/

**Comment by Fil** [comment]
all set @arfon (@whedon too 🤖)
thank you @Chilipp for your patience

**Comment by Chilipp** [comment]
Thanks for your comments and your time!

**Comment by arfon** [comment]
@Chilipp - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by Chilipp** [comment]
@arfon, I will use Zenodo for it. However I encountered a bug on their page. A couple of months ago, the psyplot repository has been deleted and created new from scratch. Now I cannot enable it again for Zenodo.

I contacted Zenodo and would like to wait for their response. Otherwise I could only provide a DOI of the [psyplot-conda](https://github.com/Chilipp/psyplot-conda) repository, which provides the installers for psyplot.

**Comment by arfon** [comment]
> I contacted Zenodo and would like to wait for their response. Otherwise I could only provide a DOI of the psyplot-conda repository, which provides the installers for psyplot.

Agreed. Let's wait for their response here.

**Comment by Chilipp** [comment]
@arfon, I thought a bit more about it and I now think that it makes the most sense to use the DOI for psyplot-conda I just created

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.845455.svg)](https://doi.org/10.5281/zenodo.845455)

This would be the best for the JOSS paper, I think, because this archive then also includes the plugins psy-simple, psy-maps and psy-reg and the GUI, plus the installers, which have also been tested by @Fil.

**Comment by Chilipp** [comment]
@whedon set 10.5281/zenodo.845455 as archive

**Comment by whedon** [comment]
I'm sorry @Chilipp, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.845455 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.845455" target="_blank">10.5281/zenodo.845455</a> is the archive.

**Comment by arfon** [comment]
@Fil - many thanks for your review here ✨ 

@Chilipp - your paper now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00363 ⚡️ 🚀 💥

**Comment by Chilipp** [comment]
Great! Many thanks from me, too @arfon and @Fil
