### ISSUE TITLE
[PRE REVIEW]: cRacklet: a spectral boundary integral method library for interfacial rupture simulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3630]
**Submitting author:** @tiburoch (<a href="http://orcid.org/0000-0002-2495-8841">Thibault Roch</a>)
**Repository:** <a href="https://gitlab.com/cracklet/cracklet.git" target ="_blank">https://gitlab.com/cracklet/cracklet.git</a>
**Version:** 1.0.0
**Editor:** @diehlpk
**Reviewers:** @KParas, @srmnitc
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2cbf53837479d66e53519db2ee14bea7/status.svg)](https://joss.theoj.org/papers/2cbf53837479d66e53519db2ee14bea7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2cbf53837479d66e53519db2ee14bea7"><img src="https://joss.theoj.org/papers/2cbf53837479d66e53519db2ee14bea7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2cbf53837479d66e53519db2ee14bea7/status.svg)](https://joss.theoj.org/papers/2cbf53837479d66e53519db2ee14bea7)
```

**Author instructions**

Thanks for submitting your paper to JOSS @tiburoch. **Currently, there isn't an JOSS editor assigned** to your paper.

@tiburoch if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1411

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/0022-5096(60)90013-2 is OK
- 10.1016/S0065-2156(08)70121-2 is OK
- 10.1029/JB084iB05p02161 is OK
- 10.1029/JB088iB12p10359 is OK
- 10.1016/0022-5096(95)00043-I is OK
- 10.1023/A:1007535703095 is OK
- 10.1007/s10704-014-9967-z is OK
- 10.1002/2013JB010586 is OK
- 10.1103/PhysRevLett.119.144101 is OK
- 10.1103/PhysRevE.98.063002 is OK
- 10.1103/PhysRevLett.121.234302 is OK
- 10.1103/PhysRevX.9.041043 is OK
- 10.1016/j.jmps.2019.103806 is OK
- 10.1016/j.epsl.2019.115978 is OK
- 10.1016/j.jmps.2020.103967 is OK
- 10.1115/1.2834197 is OK
- 10.1038/s41467-021-22806-9 is OK
- 10.25080/Majora-4af1f417-011 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (1167.0 files/s, 159993.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             56           1612           2219           5106
C/C++ Header                    42            876           2485           3200
CMake                           35            241           1053            835
MATLAB                           8            256           1074            659
Python                           8            291            251            566
SVG                              1              0              0            565
Fortran 77                       1             50             57            305
TeX                              1             22              0            273
reStructuredText                10            206            128            270
Markdown                         2            101              0            251
YAML                             1              9              1             79
Bourne Shell                     2              7              0             69
Dockerfile                       1              4              2             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           169           3679           7277          12213
-------------------------------------------------------------------------------


Statistical information for the repository '0022b818e0b70dc12f87d176' was
gathered on 2021/08/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Fabian Barras                   15         12034           2321           63.27
Thibault Roch                   98          6644           1518           35.97
Thibault.Roch                    6           150             23            0.76

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Fabian Barras             10741           89.3         39.1               22.87
Thibault Roch              5865           88.3          7.7               41.14
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03630/joss.03630/10.21105.joss.03630.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03630/joss.03630/10.21105.joss.03630.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@diehlpk I see that you are full up on papers right now, but two are also nearing their end and this submission looks like a good fit for you. Are you willing to take it on?

**Comment by kthyng** [comment]
@whedon invite @diehlpk as editor

**Comment by whedon** [comment]
@diehlpk has been invited to edit this submission.

**Comment by kthyng** [comment]
@tiburoch I saw your note about which version to review. I don't know of a better way to make this information known than to be sure to tell the reviewers when they are about to start their reviews.

**Comment by diehlpk** [comment]
> @diehlpk I see that you are full up on papers right now, but two are also nearing their end and this submission looks like a good fit for you. Are you willing to take it on?

@kthyng Sure, I can take it, but I have a paper deadline coming up soon and start editing the paper in 10 days.

**Comment by diehlpk** [comment]
@whedon assign @diehlpk as editor

**Comment by whedon** [comment]
OK, the editor is @diehlpk

**Comment by kthyng** [comment]
Thanks @diehlpk — and good luck on your paper!

**Comment by diehlpk** [comment]
@tiburoch Would you mind recommending some reviewers?

**Comment by diehlpk** [comment]
> @KParas Starting after 10 September is fine. If you could finish your review within two months from 10 September would be great.

Are you still interested?

**Comment by KParas** [comment]
> 
> 
> > @KParas Starting after 10 September is fine. If you could finish your review within two months from 10 September would be great.
> 
> Are you still interested?

@diehlpk Yes. I hope to stick by the proposed deadline.

**Comment by diehlpk** [comment]
@whedon assign @KParas as reviewer

**Comment by whedon** [comment]
OK, @KParas is now a reviewer

**Comment by diehlpk** [comment]
Hi @pragyansmita @nnadeau @ctdegroot @srmnitc @shibabrat @remram44 would you be interested in reviewing this paper?

**Comment by srmnitc** [comment]
@diehlpk Thank you for considering me. Unfortunately I cannot accept due to other commitments. I can only start on 15th of October, I assume that this is too late.

**Comment by diehlpk** [comment]
> @diehlpk Thank you for considering me. Unfortunately I cannot accept due to other commitments. I can only start on 15th of October, I assume that this is too late.

@srmnitc Not that would not be too late.

**Comment by srmnitc** [comment]
> > @diehlpk Thank you for considering me. Unfortunately I cannot accept due to other commitments. I can only start on 15th of October, I assume that this is too late.
> 
> @srmnitc Not that would not be too late.

@diehlpk In that case, I can review this submission. I will start the review from 15th Oct.

**Comment by diehlpk** [comment]
@whedon add @srmnitc as reviewer

**Comment by whedon** [comment]
OK, @srmnitc is now a reviewer

**Comment by diehlpk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3724.
