### ISSUE TITLE
[PRE REVIEW]: RADstackshelpR: an R package for streamlining the de novo optimization of Stacks parameters

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3633]
**Submitting author:** @DevonDeRaad (<a href="http://orcid.org/0000-0003-3105-985X">Devon DeRaad</a>)
**Repository:** <a href="https://github.com/DevonDeRaad/RADstackshelpR" target ="_blank">https://github.com/DevonDeRaad/RADstackshelpR</a>
**Version:** 0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ed6751c615af185057dc9d03eb1e5fb8/status.svg)](https://joss.theoj.org/papers/ed6751c615af185057dc9d03eb1e5fb8)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ed6751c615af185057dc9d03eb1e5fb8"><img src="https://joss.theoj.org/papers/ed6751c615af185057dc9d03eb1e5fb8/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ed6751c615af185057dc9d03eb1e5fb8/status.svg)](https://joss.theoj.org/papers/ed6751c615af185057dc9d03eb1e5fb8)
```

**Author instructions**

Thanks for submitting your paper to JOSS @DevonDeRaad. **Currently, there isn't an JOSS editor assigned** to your paper.

@DevonDeRaad if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 632

**Comment by whedon** [comment]
PDF failed to compile for issue #3633 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Devon DeRaad, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (695.1 files/s, 100057.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            16            691            196           3170
CSS                              3             99             48            428
R                               16            134            293            427
Rmd                              4            134            356            411
Markdown                         4             78              0            378
JavaScript                       4             64             34            266
TeX                              1              6              0             83
Bourne Shell                     1             10             32             80
YAML                             2             10              0             45
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            52           1226            960           5299
-------------------------------------------------------------------------------


Statistical information for the repository '93b4c0081a8770367a20f859' was
gathered on 2021/08/19.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Devon DeRaad                     9          1444           1056          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Devon DeRaad                388           26.9          0.4                9.79
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1534/g3.111.000240 is OK
- 10.1111/1755-0998.12549 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1111/2041-210X.12775 is INVALID because of 'https://doi.org/' prefix
```

**Comment by kthyng** [comment]
Hi @DevonDeRaad and thanks for your submission. For the line count the package is at, I need to query the editorial board to see if people think the submission is in scope in terms of [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by DevonDeRaad** [comment]
Hi @kthyng thank you so much for the quick response to this! Although the total line count of R code for the package is limited, I'm hoping that the significant effort made to integrate these functions within the context of existing bash pipelines, and give multiple extensively documented examples of this usage, represents substantial scholarly effort. Either way, I look forward to any feedback the editorial board can offer.

**Comment by DevonDeRaad** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03633/joss.03633/10.21105.joss.03633.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03633/joss.03633/10.21105.joss.03633.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @DevonDeRaad - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
