### ISSUE TITLE
[REVIEW]: AstronomicAL: an interactive dashboard for visualisation, integration and classification of data with Active Learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3635]
**Submitting author:** @grant-m-s (<a href="http://orcid.org/0000-0002-8885-4443">Grant Stevens</a>)
**Repository:** <a href="https://github.com/grant-m-s/astronomicAL" target ="_blank">https://github.com/grant-m-s/astronomicAL</a>
**Version:** v1.0
**Editor:** @crvernon
**Reviewer:** @crhea93, @rmorgan10
**Archive:** <a href="https://doi.org/10.5281/zenodo.5396671" target="_blank">10.5281/zenodo.5396671</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104/status.svg)](https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104"><img src="https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104/status.svg)](https://joss.theoj.org/papers/2dc5147d2c434806e2c8b8126c132104)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/grant-m-s/astronomicAL" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@crhea93 & @rmorgan10, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @crvernon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @crhea93
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/grant-m-s/astronomicAL">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/grant-m-s/astronomicAL">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@grant-m-s) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @rmorgan10
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/grant-m-s/astronomicAL">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/grant-m-s/astronomicAL">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@grant-m-s) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @crhea93, @rmorgan10 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3635 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (381.1 files/s, 99228.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          22           2341           1023           6664
reStructuredText                16            528            650            418
JSON                             3              0              0            290
Markdown                         1             20              0             31
Jupyter Notebook                 1              0            162             28
DOS Batch                        1              8              1             26
YAML                             2              3              5             18
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            47           2904           1848           7484
-------------------------------------------------------------------------------


Statistical information for the repository '42ba3ed564252039c49c17fb' was
gathered on 2021/08/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Grant Stevens                  226         16604           6576          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Grant Stevens             10028           60.4          3.4                2.76
```

**Comment by crvernon** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: :point_left:

**Comment by crvernon** [comment]
@whedon check references

**Comment by crvernon** [comment]
@crhea93 @rmorgan10 @grant-m-s :wave: the review takes place in this issue.  Thanks!

**Comment by crvernon** [comment]
Also, please don't forget to add a link to this review issue in any issues or pull requests you may generate in the https://github.com/grant-m-s/astronomicAL repository.  This will help everyone have a single point of reference.

**Comment by grant-m-s** [comment]
Thanks @crvernon for setting this up and thanks @crhea93 and @rmorgan10 for agreeing to review AstronomicAL. If either of you have any questions I'll be happy to answer them.

**Comment by rmorgan10** [comment]
Hi All!

@grant-m-s I would like to first congratulate you on an awesome software package! `astronomicAL` is really cool and a great addition to the field as a whole. I've identified 4 small things that will help me to check off all the remaining boxes above:

1. Changes to the paper to clarify the state of the field and the statement of need in grant-m-s/AstronomicAL#9
1. Updates to the installation instructions in grant-m-s/AstronomicAL#10
1. Clarity on contributing and bug reporting in grant-m-s/AstronomicAL#11
1. Verifying the functionalities in the testing suite in grant-m-s/AstronomicAL#12

On all these issues, let's iterate on them in your repo, and when they have been resolved you can close them.

Overall the tutorials are very thorough, the code is sufficiently documented, and I found `astronomicAL` easy to use. Great work!

**Comment by crvernon** [comment]
:mega:  Mid-week rally!  Just checking in to see how things are going.  

🙌 Thanks for getting the ball rolling @rmorgan10 !

:open_hands: @crhea93 I am happy to answer any question you may have as well!  

Great work on this review so far!

**Comment by crhea93** [comment]
@grant-m-s WHAT A PACKAGE! This is extremely impressive work! The documentation is absolutely spot on -- I was able to answer any questions I had about the software and how best to use it by scrolling through the readthedocs pages. 

I've added an additional installation issue to the existing GitHub issue created by @rmorgan10 #11

Since I am unable to install the software at the moment, I cannot complete my assessment of its functionality. Once we get that squared away, I'll be able to finish up my review :)

**Comment by crvernon** [comment]
@crhea93 I believe you accidentally linked to issue number 11 in the JOSS repository registry instead of one of the issues that is currently in the author's repository here:  https://github.com/grant-m-s/AstronomicAL/issues

Would you mind  editing your comment to reference the issue in the author's repo that you are referring to?  Thanks!

**Comment by crhea93** [comment]
My apologies! It should be all set now :D

**Comment by grant-m-s** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: :point_left:

**Comment by crhea93** [comment]
@crvernon My review is complete. I wholeheartedly suggest JOSS publishes this work!

**Comment by crvernon** [comment]
:clap: Thanks @crhea93 for your volunteering your time and providing a thoughtful review!

**Comment by rmorgan10** [comment]
@crvernon Mine is all done too. Congrats @grant-m-s on a fantastic package!

**Comment by crvernon** [comment]
:clap: Thanks so much @rmorgan10 !  Your time and effort in reviewing this submission is greatly appreciated!

**Comment by grant-m-s** [comment]
Thank you @rmorgan10 and @crhea93 . I really appreciate your feedback and making my first review such a pleasant experience. Thanks again @crvernon managing everything.

**Comment by grant-m-s** [comment]
@crvernon  what’s the next step in the process?

**Comment by crvernon** [comment]
@grant-m-s - I'll take a look at the paper document later today and build a list of any edits I think need to be made (if there are any).  

Once I deem everything is good to go, I'll get you to generate a release and an accompanying DOI as linked with a service like Zenodo that corresponds to the final review version. 

Lastly, once all has been accounted for, I'll make my recommendation to the editor-in-chief and they will conduct a final pass and move forward with full acceptance and publication if they are in agreement with my recommendation.

**Comment by crvernon** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: :point_left:

**Comment by crvernon** [comment]
@whedon check references

**Comment by crvernon** [comment]
@grant-m-s your `joss-paper-branch` is 9 commits behind and 5 commits ahead of the `master` branch.  Some of your changes per review comments were only made to the `master` and the paper directory resides on the `joss-paper-branch`.  Are you planning on merging `joss-paper-branch` into `master`?

**Comment by crvernon** [comment]
@grant-m-s - In your [Citing the Software](https://astronomical.readthedocs.io/en/latest/content/other/citing.html#id9) documentation, you mention that:

> astronomicAL has also been published as an arXiv_ preprint.

Could you please give me a link to that preprint?

**Comment by grant-m-s** [comment]
@crvernon That was added at the beginning of the docs being created as we assumed we would upload but we never actually did. Would you rather that I remove that?

**Comment by grant-m-s** [comment]
and I will merge the paper into master now.

**Comment by crvernon** [comment]
Yes, if the `arXiv` submission was never made it would be good to remove this to support the originality of this work.  Thank you!

**Comment by grant-m-s** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: :point_left:

**Comment by grant-m-s** [comment]
@crvernon all merged and updated the citation page.

**Comment by crvernon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4581995 is OK
- 10.5281/zenodo.3987379 is OK
- 10.5281/zenodo.4573728 is OK
- 10.1051/0004-6361/201730763 is OK
- 10.1086/176166 is OK
- 10.3847/1538-4365/ab929e is OK

MISSING DOIs

- 10.3115/1613715.1613855 may be a valid DOI for title: An analysis of active learning strategies for sequence labeling tasks
- 10.1093/mnras/stz2816 may be a valid DOI for title: Galaxy Zoo: probabilistic morphology through Bayesian CNNs and active learning
- 10.1038/s41587-020-0521-4 may be a valid DOI for title: Active machine learning helps drug hunters tackle biology.

INVALID DOIs

- None
```

**Comment by crvernon** [comment]
@grant-m-s - Your paper is looking great!  Here are several things I would like you to address from my review of your paper before we move on:

- [ ] Please check the missing DOI in the references (see the above `whedon check references` output ☝️)
- [ ] Please review any other references to ensure that you have added in their DOI to the citation if there is one available.  Sometimes these get excluded from citation exports.
- [ ] Figure 1 is placed in the document before it is referred to in the text
- [ ] Figures 1 and 3 are never referenced in the text
- [ ] Please take one last look at your author names and their affiliations to make sure all is well before we move forward

**Comment by grant-m-s** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: :point_left:

**Comment by grant-m-s** [comment]
@crvernon so I've added all doi's I can find, its mainly the software packages that dont have a zenodo that I'm missing.

I've referenced all the figures in the text now.

Figure 1 is still ahead in the text as I believe it fits much better there rather than half way through the section. Let me know if that's against any style requirements.

Authors and Affiliations are all good.

**Comment by crvernon** [comment]
@grant-m-s - I think the figure referencing looks good.

**Comment by crvernon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4581995 is OK
- 10.5281/zenodo.3987379 is OK
- 10.5281/zenodo.4573728 is OK
- 10.2200/S00429ED1V01Y201207AIM018 is OK
- 10.1051/0004-6361/201730763 is OK
- 10.1086/176166 is OK
- 10.3847/1538-4365/ab929e is OK
- 10.5281/zenodo.4724125 is OK
- 10.3115/1613715.1613855 is OK
- 10.1093/mnras/stz2816 is OK
- 10.1038/s41587-020-0521-4 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.5555/1699510.1699549 is INVALID
- 10.5555/3305381.3305504 is INVALID
```

**Comment by grant-m-s** [comment]
hmm both seem to be ACM doi's that aren't matched anywhere else besides the ACM website.

should I remove them?

**Comment by crvernon** [comment]
Yes, please remove them.  It looks like those repos only site the tag on GitHub and not a DOI.  Please pull the two invalid ones and we will proceed.

**Comment by grant-m-s** [comment]
ok they've now been removed

**Comment by crvernon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4581995 is OK
- 10.5281/zenodo.3987379 is OK
- 10.5281/zenodo.4573728 is OK
- 10.2200/S00429ED1V01Y201207AIM018 is OK
- 10.1051/0004-6361/201730763 is OK
- 10.1086/176166 is OK
- 10.3847/1538-4365/ab929e is OK
- 10.5281/zenodo.4724125 is OK
- 10.3115/1613715.1613855 is OK
- 10.1093/mnras/stz2816 is OK
- 10.1038/s41587-020-0521-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by crvernon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03635/joss.03635/10.21105.joss.03635.pdf) :page_facing_up: :point_left:

**Comment by crvernon** [comment]
@grant-m-s we are almost there!  Next is just setting up the archive for your new release.  Since there have not been any releases yet in your repo, here are a few pointers:

- I find Zenodo easy to use to mint a DOI (permanent archive identifier) for each GitHub release.  You will likely need to create a free Zenodo account and link your GitHub repository to it.  Then once linked, you can conduct your release on GitHub and it will automatically trigger Zenodo to mint a DOI for you.  If you want the DOI as a badge, you can add that as well.  There are other options for creating a permanent archive resulting in a DOI for your code as well.  Don't hesitate to reach out if you have questions.
- We want to make sure the archival has the correct metadata that JOSS requires.  This includes a title that matches the paper title and a correct author list.  

So here is what we have left to do:
- [ ] Conduct a GitHub release of the current reviewed version of the software you now have on the `master` and archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) to ensure it has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here

I can then move forward with accepting the submission.

**Comment by grant-m-s** [comment]
@crvernon  10.5281/zenodo.5396671

**Comment by crvernon** [comment]
@whedon set v1.0 as version

**Comment by whedon** [comment]
OK. v1.0 is the version.

**Comment by crvernon** [comment]
@whedon set 10.5281/zenodo.5396671 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5396671" target="_blank">10.5281/zenodo.5396671</a> is the archive.

**Comment by crvernon** [comment]
🎉  @grant-m-s thanks for putting together a really nice software product!  Thanks to @crhea93 and @rmorgan10 for a constructive and timely review!

I am recommending that your submission be accepted.  An EIC will review this shortly and confirm final publication if all goes well.

**Comment by crvernon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4581995 is OK
- 10.5281/zenodo.3987379 is OK
- 10.5281/zenodo.4573728 is OK
- 10.2200/S00429ED1V01Y201207AIM018 is OK
- 10.1051/0004-6361/201730763 is OK
- 10.1086/176166 is OK
- 10.3847/1538-4365/ab929e is OK
- 10.5281/zenodo.4724125 is OK
- 10.3115/1613715.1613855 is OK
- 10.1093/mnras/stz2816 is OK
- 10.1038/s41587-020-0521-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2566

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2566, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1433890582418661377) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2567
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03635](https://doi.org/10.21105/joss.03635)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congratulations @grant-m-s on your article's publication in JOSS!

Many thanks to @crhea93 and @rmorgan10 for reviewing this, and @crvernon for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03635/status.svg)](https://doi.org/10.21105/joss.03635)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03635">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03635/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03635/status.svg
   :target: https://doi.org/10.21105/joss.03635
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03635/status.svg)](https://doi.org/10.21105/joss.03635)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by grant-m-s** [comment]
@crvernon If I were to also upload this to Arxiv, am I able to upload the paper with JOSS branding? (For example the main paper pdf or the local docker created version). Thanks!

**Comment by crvernon** [comment]
@grant-m-s I think this is more of a question for the arXiv staff to determine permissiveness.  Your JOSS paper is now licensed as follows (and as listed on your publication):

> Authors of papers retain copyright and release the work under a Creative Commons Attribution 4.0 International License ([CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)).

Have a great day!
