### ISSUE TITLE
[PRE REVIEW]: Opfi: A Python package for identifying gene clusters in large genomics and metagenomics data sets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3636]
**Submitting author:** @alexismhill3 (<a href="http://orcid.org/0000-0002-5382-8851">Alexis Hill</a>)
**Repository:** <a href="https://github.com/wilkelab/Opfi" target ="_blank">https://github.com/wilkelab/Opfi</a>
**Version:** 0.1.0
**Editor:** @csoneson
**Reviewers:** @Thomieh73, @afrubin
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/cc0a3b03e9cff97e5f93e1a3a8a1808d/status.svg)](https://joss.theoj.org/papers/cc0a3b03e9cff97e5f93e1a3a8a1808d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cc0a3b03e9cff97e5f93e1a3a8a1808d"><img src="https://joss.theoj.org/papers/cc0a3b03e9cff97e5f93e1a3a8a1808d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cc0a3b03e9cff97e5f93e1a3a8a1808d/status.svg)](https://joss.theoj.org/papers/cc0a3b03e9cff97e5f93e1a3a8a1808d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @alexismhill3. **Currently, there isn't an JOSS editor assigned** to your paper.

@alexismhill3 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1401

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1186/2042-5783-2-3 is OK
- 10.1038/nrg1709 is OK
- 10.1186/1471-2105-10-421 is OK
- 10.1038/nbt.3988 is OK
- 10.1038/s41592-021-01101-x is OK
- 10.1093/nar/gkz310 is OK
- 10.1093/nar/gky383 is OK
- 10.1093/nar/gkz192 is OK
- 10.1186/1471-2105-8-18 is OK
- 10.1093/bioinformatics/btaa213 is OK
- 10.1101/2021.08.16.456562 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.38 s (433.2 files/s, 69467.5 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
C++                              85           2266            585          12905
Python                           38           1095           1366           4350
C/C++ Header                     19            261             61           1418
Markdown                          5            109              0            305
XML                               1              0              0            210
TeX                               1             10              0            179
reStructuredText                  8            202            244            177
YAML                              3             11             12            103
Jupyter Notebook                  1              0            302             77
make                              2             12              8             28
Bourne Again Shell                1              1              0              4
--------------------------------------------------------------------------------
SUM:                            164           3967           2578          19756
--------------------------------------------------------------------------------


Statistical information for the repository '086c9f502c228c3ab453d0fb' was
gathered on 2021/08/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alexis Hill                    146         23336           3224           72.53
Jim Rybarski                   159          7274           2786           27.47

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alexis Hill               19831           85.0         17.4                5.03
Jim Rybarski               4476           61.5         12.2                8.80
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03636/joss.03636/10.21105.joss.03636.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03636/joss.03636/10.21105.joss.03636.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @lpantano, could you take on this submission?

**Comment by kthyng** [comment]
@whedon invite @lpantano as editor

**Comment by whedon** [comment]
@lpantano has been invited to edit this submission.

**Comment by kthyng** [comment]
I'm sorry, I shouldn't have invited @lpantano as the editor because there is a waitlisted paper should maybe could edit instead, which has been waiting longer. I will add this submission to the waitlist while we wait for available editors with relevant expertise.

**Comment by danielskatz** [comment]
👋 @csoneson - Do you think you edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @csoneson as editor

**Comment by whedon** [comment]
@csoneson has been invited to edit this submission.

**Comment by csoneson** [comment]
@whedon assign @csoneson as editor

**Comment by whedon** [comment]
OK, the editor is @csoneson

**Comment by csoneson** [comment]
👋🏻 @alexismhill3 - I will handle your submission, and start by finding two suitable reviewers. If you have any suggestions (e.g., from the list linked in the first post above), please feel free to list them here (without tagging them with `@`). Thanks!

**Comment by alexismhill3** [comment]
Hi @csoneson, from the list it looks like ctb, afrubin, Nazeeefa, will-rowe, karinlag, tkchafin, and mberacochea would be some good choices.

**Comment by csoneson** [comment]
👋🏻 @mberacochea, @tkchafin, @karinlag - would (two of) you be interested in reviewing this submission for JOSS?

> Opfi: A Python package for identifying gene clusters in large genomics and metagenomics data sets

**Comment by csoneson** [comment]
👋🏻 @afrubin - would you be interested in reviewing this submission for JOSS? 

> Opfi: A Python package for identifying gene clusters in large genomics and metagenomics data sets

**Comment by afrubin** [comment]
@csoneson I would be happy to review this paper.

**Comment by csoneson** [comment]
@afrubin Brilliant, thanks! Since we now have two reviewers on board, I'll start the review issue.

**Comment by csoneson** [comment]
@whedon assign @Thomieh73 as reviewer

**Comment by whedon** [comment]
OK, @Thomieh73 is now a reviewer

**Comment by csoneson** [comment]
@whedon add @afrubin as reviewer

**Comment by whedon** [comment]
OK, @afrubin is now a reviewer

**Comment by csoneson** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3678.
