### ISSUE TITLE
[PRE REVIEW]: BCImat: a Matlab-based framework for Intracortical Brain-Computer Interfaces and their simulation with an artificial spiking neural network

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3638]
**Submitting author:** @eferrea (<a href="http://orcid.org/0000-0003-1352-4789">Enrico Ferrea</a>)
**Repository:** <a href="https://github.com/eferrea/BCI-Master" target ="_blank">https://github.com/eferrea/BCI-Master</a>
**Version:** v.1.0.0
**Editor:** @oliviaguest
**Reviewers:** @mstimberg, @puolival
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b6f403bdc8f1b9c96698feca6a466169/status.svg)](https://joss.theoj.org/papers/b6f403bdc8f1b9c96698feca6a466169)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b6f403bdc8f1b9c96698feca6a466169"><img src="https://joss.theoj.org/papers/b6f403bdc8f1b9c96698feca6a466169/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b6f403bdc8f1b9c96698feca6a466169/status.svg)](https://joss.theoj.org/papers/b6f403bdc8f1b9c96698feca6a466169)
```

**Author instructions**

Thanks for submitting your paper to JOSS @eferrea. **Currently, there isn't an JOSS editor assigned** to your paper.

@eferrea if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1175

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1126/science.aaa5417 is OK
- 10.1016/S0140-6736(17)30601-3 is OK
- 10.1016/S0140-6736(12)61816-9 is OK
- 10.1038/nn.3265 is OK
- 10.1038/nature11076 is OK
- 10.1073/pnas.0808113105 is OK
- 10.1038/nature10845 is OK
- 10.1038/nature13665 is OK
- 10.1016/j.neuron.2014.08.038 is OK

MISSING DOIs

- 10.1101/2021.02.16.431440 may be a valid DOI for title: Statistical determinants of visuomotor adaptation in a virtual reality three-dimensional environment
- 10.1523/jneurosci.02-11-01527.1982 may be a valid DOI for title: On the relations between the direction of two-dimensional arm movements and cell discharge in primate motor cortex
- 10.1109/thms.2020.2968411 may be a valid DOI for title: Brain–computer interface software: A review and discussion

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (199.1 files/s, 21903.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                          16            371            342           1071
C++                              4            216            121            488
XML                              3              0              0            176
TeX                              1             13              0            173
Markdown                         2             53              0             95
C/C++ Header                     1              9             10             20
YAML                             1              1              4             18
DOS Batch                        1              0              0              9
-------------------------------------------------------------------------------
SUM:                            29            663            477           2050
-------------------------------------------------------------------------------


Statistical information for the repository '2787c4b2ee638f8994e798fc' was
gathered on 2021/08/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
nerofumo82                      10           918             54          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
nerofumo82                  864           94.1          0.1               15.39
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03638/joss.03638/10.21105.joss.03638.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03638/joss.03638/10.21105.joss.03638.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi  and thanks for your submission. I have pinged the greater editorial board to make sure this submission is in scope, particularly in terms of [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). This process usually takes 1-2 weeks; thanks for your patience.

**Comment by eferrea** [comment]
@kthyng thanks for your answer. Just few words: this work was started in the lab back to 2015 and was updated among the years to perform state of the art brain computer interface experiments for motor control. It also contains implementations of several BCI functionalities the details of which can be hardly found in papers. It is widely used from people in our lab and we hope that other people can benefit from it.

**Comment by kthyng** [comment]
@eferrea Thanks for that additional information — editors will see it when they look through to vote.

**Comment by kyleniemeyer** [comment]
Hi @eferrea, we are going to move ahead with review of this submission. As we are finding an editor, it looks like your software package is missing a clear open source license (usually expressed via a `LICENSE` file at the top level of the repo). Can you choose one and add it?

**Comment by kyleniemeyer** [comment]
@eferrea could you also recommend some potential reviewers? Ideally from our [reviewer list](https://bit.ly/joss-reviewers) but also potentially domain experts you are aware of. Thanks!

**Comment by kyleniemeyer** [comment]
@whedon invite @oliviaguest as editor

@oliviaguest could you edit this one?

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by eferrea** [comment]
Hi @kyleniemeyer, I added the LICENSE file to the repository. Additional potential reviewers are Agricolab, TomDonoghue and JanCBrammer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@oliviaguest could you help edit this submission? If not, @cMadan is this something you could edit?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@cMadan if @oliviaguest cannot take this, is this something you could help with?

**Comment by eferrea** [comment]
Hi @Kevin-Mattheus-Moerman, I was also suggesting other potential reviewers: Agricolab, TomDonoghue and JanCBrammer. Best

**Comment by danielskatz** [comment]
@whedon invite @oliviaguest as editor

**Comment by whedon** [comment]
@oliviaguest has been invited to edit this submission.

**Comment by oliviaguest** [comment]
@whedon assign @oliviaguest as editor

**Comment by whedon** [comment]
OK, the editor is @oliviaguest

**Comment by oliviaguest** [comment]
Hi all, sorry for late reply. I can take this over. 😊

**Comment by eferrea** [comment]
Hi @oliviaguest thanks for accepting editing  I would suggest Agricolab, TomDonoghue and JanCBrammer as potential reviewers. Thanks again

**Comment by oliviaguest** [comment]
@Agricolab, @TomDonoghue and @JanCBrammer, would any or all of you be able to review this for us?

**Comment by TomDonoghue** [comment]
Thanks for the invite! This project looks interesting, but I don't use Matlab anymore (don't have a license / wouldn't be able to test the code), so I won't be able to do a proper review here.

**Comment by JanCBrammer** [comment]
Thanks for the request! Unfortunately, I'm too swamped atm to properly review this. Also don't have a Matlab licence anymore and it's been quite a while since I did anything with it (will take Matlab off my language list in the reviewer sheet 🙈 ).

**Comment by eferrea** [comment]
Hi @oliviaguest , other potential reviewers are mstimberg, katschueler and vahid-sb .
Thanks.

**Comment by agricolab** [comment]
Sorry for the late reply. I am busy with parental leave, and moving and won't be able to review in time. Hope you find reviewers.

**Comment by oliviaguest** [comment]
@mstimberg, @katschueler, and/or @vahid-sb: do any of you three have the time and expertise to review this submission for JOSS? 😊

**Comment by oliviaguest** [comment]
@mstimberg oh, that's very kind of you. I am happy for you to decide here how you feel about reviewing this and I am sure your review will be appreciated, useful, and constructive no matter what.

**Comment by eferrea** [comment]
Thanks @mstimberg for taking the review.

**Comment by oliviaguest** [comment]
@mstimberg wait, please ☺️

**Comment by oliviaguest** [comment]
hey @ahwillia do you think you might be able to review this? 😊

**Comment by ahwillia** [comment]
Sorry - I also don't have a MATLAB license, and I'm moving across the country in 2 weeks so I don't think I have the bandwidth. I'm not sure I have other reviewers I could suggest, but let me know if you'd like help on that front...

**Comment by eferrea** [comment]
Hi @oliviaguest , other potential reviewers are puolivali, wmvanvliet and EtienneCmb.
Thanks,

**Comment by oliviaguest** [comment]
@puolivali do you think you may have the time and space to review this for us? 😊

**Comment by puolival** [comment]
@oliviaguest I would be happy to review this submission if the schedule isn't tight. I am currently reviewing many manuscripts for a conference, and would be free to start working on this after Dec 17th. Does that work for you?

**Comment by oliviaguest** [comment]
@whedon add @puolival as reviewer

**Comment by whedon** [comment]
OK, @puolival is now a reviewer

**Comment by oliviaguest** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3956.

**Comment by oliviaguest** [comment]
@eferrea @mstimberg @puolival please move to #3956 where the review itself will take place! 😊
