### ISSUE TITLE
[PRE REVIEW]: Heta compiler: a software tool for the development of large-scale QSP models and compilation into simulation formats

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3639]
**Submitting author:** @metelkin (<a href="http://orcid.org/0000-0001-6612-5373">Evgeny Metelkin</a>)
**Repository:** <a href="https://github.com/hetalang/heta-compiler" target ="_blank">https://github.com/hetalang/heta-compiler</a>
**Version:** v0.6.6
**Editor:** @fboehm
**Reviewers:** @martinmodrak, @elimillera
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ebff76c368d3adb720afe414ef6b29fb/status.svg)](https://joss.theoj.org/papers/ebff76c368d3adb720afe414ef6b29fb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ebff76c368d3adb720afe414ef6b29fb"><img src="https://joss.theoj.org/papers/ebff76c368d3adb720afe414ef6b29fb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ebff76c368d3adb720afe414ef6b29fb/status.svg)](https://joss.theoj.org/papers/ebff76c368d3adb720afe414ef6b29fb)
```

**Author instructions**

Thanks for submitting your paper to JOSS @metelkin. **Currently, there isn't an JOSS editor assigned** to your paper.

@metelkin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.40 s (558.9 files/s, 61695.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                     133           1272           1203          11144
JSON                            54             73              0           7004
XML                             10            147             10           1871
Markdown                         8            299              0            879
YAML                            10             12              6            316
Julia                            2             30             26             83
R                                3             14             12             52
C++                              1             10              7             31
MATLAB                           1              0              0              7
-------------------------------------------------------------------------------
SUM:                           222           1857           1264          21387
-------------------------------------------------------------------------------


Statistical information for the repository '38049e50adf1b1127b72aaba' was
gathered on 2021/08/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Evgeny Metelkin                696         34481          21318           98.32
metelkin                         5           897             54            1.68

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Evgeny Metelkin           13667           39.6         13.7               10.05
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3639 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kthyng** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03639/joss.03639/10.21105.joss.03639.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03639/joss.03639/10.21105.joss.03639.pdf) :page_facing_up: :point_left:

**Comment by metelkin** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03639/joss.03639/10.21105.joss.03639.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03639/joss.03639/10.21105.joss.03639.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@metelkin - thanks for your submission.  Because the code size is not clear, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  You should hear back in a week or so.

Can you help by explaining specifically what code is part of the submission that would be reviewed?

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
I guess I should have read https://hetalang.github.io/#/heta-compiler/ - now I see that the Heta compiler has been written in NodeJS environment, which I think answer my question about the source code. And given this, I think my question about code size is also answered.  So I'll stop the scope query, and work on finding an editor next.

**Comment by danielskatz** [comment]
@fboehm - do you think you could edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @fboehm as editor

**Comment by whedon** [comment]
@fboehm has been invited to edit this submission.

**Comment by fboehm** [comment]
Yes, @danielskatz , I'm happy to edit this submission.

**Comment by fboehm** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @fboehm

**Comment by fboehm** [comment]
@metelkin - thanks for your submission. Do you have any suggestions for reviewers? I'm happy to invite them.

**Comment by metelkin** [comment]
Hi @fboehm. Thank you for your editing. 
I look through the list of people who have already agreed to review for JOSS. I guess potential reviewers might be

sahilseth
louiejtaylor
camillescott
zfrenchee
RuneBlaze
jmcgonigle
smsaladi
dvanic
carleshf
jkanche

**Comment by fboehm** [comment]
:wave: @camillescott and @louiejtaylor - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by metelkin** [comment]
Hi @fboehm. Do we have progress with reviewers? I can search for other people if it is required.

**Comment by fboehm** [comment]
:wave: @lgerosa and @bence-szalai - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks for considering this.

**Comment by fboehm** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by fboehm** [comment]
@VivekTodur - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks for considering this.

**Comment by fboehm** [comment]
:wave: @zfrenchee and @RuneBlaze - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks for considering this.

**Comment by fboehm** [comment]
:wave: @jmcgonigle, @smsaladi, @dvanic, @carleshf, @jkanche - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks for considering this.

**Comment by fboehm** [comment]
@metelkin - yes, please feel free to suggest additional reviewers. Please feel free to include possible reviewers who don't have a github account. Thanks again!

**Comment by metelkin** [comment]
Hi @fboehm. I'll try for the last time with guys from the GitHub community.
 
alexey0308
stjordanis
lptolik
step-by-step
Ahmed7emdan
KirillZubov
timknab
dkolobok
billdenney

**Comment by jkanche** [comment]
Hello @fboehm Unfortunately i don't have any expertise in this particular topic.

**Comment by RuneBlaze** [comment]
Hi @fboehm. Sorry I am currently occupied with classes and passing my qualification exams🤦

**Comment by dvanic** [comment]
Hi @fboehm - sorry, I don't have expertise in this topic!

**Comment by fboehm** [comment]
@jkanche, @RuneBlaze, and @dvanic - Thanks for the replies. I completely understand and wish you the best :)

**Comment by fboehm** [comment]
@lptolik and @Ahmed7emdan - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks for considering this.

**Comment by fboehm** [comment]
@KirillZubov - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks for considering this.

**Comment by fboehm** [comment]
@timknab - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks for considering this.

**Comment by fboehm** [comment]
@billdenney - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks for considering this.

**Comment by fboehm** [comment]
@bovee - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks for considering this. I think that your expertise in javascript and bioinformatics would be quite useful for reviewing this submission. Thanks again!

**Comment by fboehm** [comment]
:wave: @serine, @siravan, @betteridiot, @arose, and @martinmodrak - would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html. Thanks for considering this. I think that your expertise in javascript and biology would be quite useful for reviewing this submission. Thanks again!

**Comment by arose** [comment]
Hi @fboehm - sorry, not my area of expertise!

**Comment by billdenney** [comment]
Hi @fboehm , Unfortunately, I don't have the bandwidth right now for review.

**Comment by fboehm** [comment]
Thanks for the replies, @arose and @billdenney ! I hope that we might work together on a future submission.

**Comment by martinmodrak** [comment]
Hi, the application area is mostly outside my expertise, but I can review the software engineering aspects of the work, if that's enough.

**Comment by betteridiot** [comment]
@fboehm Like @billdenney, I do not have the bandwidth for this right now. I am sorry.

**Comment by fboehm** [comment]
@martinmodrak - Thanks so much! Yes, it would be great if you can review the software engineering aspects of the work. That would be very helpful, indeed! I want to find a second reviewer before we proceed. I hope that we can start the review in the next week or so. So you don't need to do anything immediately - I'll let you know when we can officially start the review. Thanks again!

**Comment by fboehm** [comment]
@whedon assign @martinmodrak as reviewer

**Comment by whedon** [comment]
OK, @martinmodrak is now a reviewer

**Comment by fboehm** [comment]
@betteridiot - No problem. I really appreciate the reply. I hope that we might work together on a future submission. Thanks again!

**Comment by fboehm** [comment]
@whedon add @elimillera as reviewer

**Comment by whedon** [comment]
OK, @elimillera is now a reviewer

**Comment by fboehm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3708.
