### ISSUE TITLE
[PRE REVIEW]: Gala: A Python package for galactic dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#364]
**Submitting author:** @adrn (<a href="http://orcid.org/0000-0003-0872-7098">Adrian Price-Whelan</a>)
**Repository:** <a href="https://github.com/adrn/gala" target ="_blank">https://github.com/adrn/gala</a>
**Version:** v0.2.1
**Editor:** @arfon
**Reviewer:** @crawfordsm

**Author instructions**

Thanks for submitting your paper to JOSS @adrn. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@adrn if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @astrofrog - would you be willing to review this submission for JOSS?

**Comment by astrofrog** [comment]
I'm on vacation for a couple of weeks, so I don't have time to review this at the moment.

**Comment by arfon** [comment]
👋 @crawfordsm - would you be willing to review this submission for JOSS?

**Comment by crawfordsm** [comment]
I'd been looking at this code recently so I'd be happy to although I'll likely not get to it before next week.  If that is okay, then I'd be happy to be a review for it.

**Comment by arfon** [comment]
> I'd been looking at this code recently so I'd be happy to although I'll likely not get to it before next week. If that is okay, then I'd be happy to be a review for it.

⚡️ excellent. Thanks!

**Comment by arfon** [comment]
@whedon assign @crawfordsm as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @crawfordsm

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/388. Feel free to close this issue now!

**Comment by arfon** [comment]
@crawfordsm see you over in #388 for the actual JOSS review.
