### ISSUE TITLE
[PRE REVIEW]: meddocr: Facilitating clinical documentation for research using R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3640]
**Submitting author:** @DanJMulder (<a href="http://orcid.org/0000-0003-2974-855X">Daniel J Mulder</a>)
**Repository:** <a href="https://github.com/DanJMulder/meddocr" target ="_blank">https://github.com/DanJMulder/meddocr</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fdf667bb6f6d167e74e6892bc08cae3f/status.svg)](https://joss.theoj.org/papers/fdf667bb6f6d167e74e6892bc08cae3f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fdf667bb6f6d167e74e6892bc08cae3f"><img src="https://joss.theoj.org/papers/fdf667bb6f6d167e74e6892bc08cae3f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fdf667bb6f6d167e74e6892bc08cae3f/status.svg)](https://joss.theoj.org/papers/fdf667bb6f6d167e74e6892bc08cae3f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @DanJMulder. **Currently, there isn't an JOSS editor assigned** to your paper.

@DanJMulder if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 905

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (185.5 files/s, 98868.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                1            335            127           1533
Markdown                         2             32              0             77
TeX                              1              2              0             26
-------------------------------------------------------------------------------
SUM:                             4            369            127           1636
-------------------------------------------------------------------------------


Statistical information for the repository '283a2de0e163ec998e30628d' was
gathered on 2021/08/20.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1093/jamia/ocv180 may be a valid DOI for title: Extracting information from the text of electronic medical records to improve case detection: a systematic review
- 10.1155/2018/4302425 may be a valid DOI for title: Data Processing and Text Mining Technologies on Electronic Medical Records: A Review

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03640/joss.03640/10.21105.joss.03640.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03640/joss.03640/10.21105.joss.03640.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@DanJMulder - thanks for your submission.  Due to the lack of packaging of the code, and the fact that it's not clear if this is research software, the editors will now discuss if submission criterion for review by JOSS.  You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@DanJMulder – many thanks for your submission to JOSS. After review by the JOSS editorial team, this submission has been deemed out of scope for us, not meeting [out definitions of research software](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
