### ISSUE TITLE
[PRE REVIEW]: Fiscore Package: Effective Protein Structural Data Visualisation and Exploration

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3643]
**Submitting author:** @AusteKan (<a href="http://orcid.org/0000-0001-6829-4082">Austė  Kanapeckaitė</a>)
**Repository:** <a href="https://github.com/AusteKan/JOSS_Fiscore" target ="_blank">https://github.com/AusteKan/JOSS_Fiscore</a>
**Version:** V0.1.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/175e5748bba224b099f375ae64d4309f/status.svg)](https://joss.theoj.org/papers/175e5748bba224b099f375ae64d4309f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/175e5748bba224b099f375ae64d4309f"><img src="https://joss.theoj.org/papers/175e5748bba224b099f375ae64d4309f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/175e5748bba224b099f375ae64d4309f/status.svg)](https://joss.theoj.org/papers/175e5748bba224b099f375ae64d4309f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @AusteKan. **Currently, there isn't an JOSS editor assigned** to your paper.

@AusteKan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1529

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (38.2 files/s, 35476.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1            306              5           2280
TeX                              1             13              0            101
Markdown                         1             37              0             41
-------------------------------------------------------------------------------
SUM:                             3            356              5           2422
-------------------------------------------------------------------------------


Statistical information for the repository '98a422ce28fbb9200f6c8fe1' was
gathered on 2021/08/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3643 with the following error: 
```
 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (https://orcid.org/0000-0001-6829-4082) for Austė Kanapeckaitė [correspoding author] (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/07391102.2020.1854859 is OK
- 10.1016/j.cbpa.2011.05.020 is OK
- 10.1016/j.cclet.2020.03.028 is OK
- 10.1214/13-STS452 is OK

MISSING DOIs

- None

INVALID DOIs

-  https://doi.org/10.1002/prot.22193 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1007/978-1-4899-7488-4 is INVALID because of 'https://doi.org/' prefix
```

**Comment by danielskatz** [comment]
@AusteKan - there are a couple of problems with your submission:
1. There's no software, just a paper - please put this paper in the repository with the software, and resubmit that repository.
2. The paper doesn't compile - see https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles
3. Some DOIs are invalid - please remove the 'https://doi.org/' prefix from these DOIs

Given this, I'm going to reject the paper as submitted, but please fix these issues and resubmit.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by AusteKan** [comment]
Dear Daniel,

Thank you for your swift reply and apologies for the issues, I will resolve
that and resubmit. Also, thank you very much for kindly pointing out what
needs to be fixed.

Best wishes,
Auste
