### ISSUE TITLE
[PRE REVIEW]: QXTools: A Julia framework for distributed quantum circuit simulation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3644]
**Submitting author:** @nmoran (<a href="http://orcid.org/0000-0002-2619-5040">Niall Moran</a>)
**Repository:** <a href="https://github.com/JuliaQX/QXTools.jl" target ="_blank">https://github.com/JuliaQX/QXTools.jl</a>
**Version:** 0.2.3
**Editor:** @jarvist
**Reviewers:** @goerz, @obliviateandsurrender
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e1fbf3f328575f56512cc9b17f709dd5/status.svg)](https://joss.theoj.org/papers/e1fbf3f328575f56512cc9b17f709dd5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e1fbf3f328575f56512cc9b17f709dd5"><img src="https://joss.theoj.org/papers/e1fbf3f328575f56512cc9b17f709dd5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e1fbf3f328575f56512cc9b17f709dd5/status.svg)](https://joss.theoj.org/papers/e1fbf3f328575f56512cc9b17f709dd5)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nmoran. **Currently, there isn't an JOSS editor assigned** to your paper.

@nmoran if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (939.4 files/s, 75841.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           16            253            156           1221
Markdown                         7            108              0            313
YAML                             4              7             16            160
SVG                              1              0              0            133
TOML                             2              5              0             50
-------------------------------------------------------------------------------
SUM:                            30            373            172           1877
-------------------------------------------------------------------------------


Statistical information for the repository 'bd669d88b4fdc7ae662f778b' was
gathered on 2021/08/22.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3644 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment]
@nmoran - where is the JOSS paper in your repository?
See https://joss.readthedocs.io/en/latest/submitting.html#typical-paper-submission-flow and https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by nmoran** [comment]
@danielskatz apologies I see that I gave the URL to the repository with the software and not the paper. Paper is at [https://github.com/nmoran/juliaqx_joss](https://github.com/nmoran/juliaqx_joss).

Is it possible to change the URL or do I need to re-submit?

**Comment by danielskatz** [comment]
Ideally you would put the paper in the software repository, at least in a branch

**Comment by nmoran** [comment]
Thanks, have created a joss-paper branch and added the files there.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03644/joss.03644/10.21105.joss.03644.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03644/joss.03644/10.21105.joss.03644.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.22331/q-2020-10-11-341 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@whedon invite @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
@Kevin-Mattheus-Moerman has been invited to edit this submission.

**Comment by danielskatz** [comment]
👋 @Kevin-Mattheus-Moerman - I wonder if you can take this, in part based on your Julia knowledge?

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielskatz sorry this is too far out of scope for me. Perhaps @melissawm might be suitable to handle this one?

**Comment by danielskatz** [comment]
👋 @melissawm  - I wonder if you can take this, as suggested to @Kevin-Mattheus-Moerman?

**Comment by danielskatz** [comment]
@whedon invite @melissawm as editor

**Comment by whedon** [comment]
@melissawm has been invited to edit this submission.

**Comment by jarvist** [comment]
As Melissa WM appears to be busy, I am happy to edit this paper.

**Comment by jarvist** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @jarvist

**Comment by jarvist** [comment]
Great! :rocket:

**Comment by jarvist** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by jarvist** [comment]
OK, a couple of potential reviewers invited by email.

**Comment by jarvist** [comment]
@whedon add @goerz as reviewer

Thank you for agreeing to review Michael!

**Comment by whedon** [comment]
OK, @goerz is now a reviewer

**Comment by jarvist** [comment]
@whedon add @obliviateandsurrender as reviewer

Thanks for agreeing to review Utkarsh!

**Comment by whedon** [comment]
OK, @obliviateandsurrender is now a reviewer

**Comment by jarvist** [comment]
@whedon start review

Great! I think we should be good to go now.

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3711.
