### ISSUE TITLE
[PRE REVIEW]: UndersmoothedUnfolding: Undersmoothed uncertainty quantification for unfolding in ROOT

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3645]
**Submitting author:** @jlylekim (<a href="http://orcid.org/0000-0002-4774-5750">Junhyung Lyle Kim</a>)
**Repository:** <a href="https://github.com/jlylekim/UndersmoothedUnfolding" target ="_blank">https://github.com/jlylekim/UndersmoothedUnfolding</a>
**Version:** v1.0.0
**Editor:** @danielskatz
**Reviewers:** @matthewfeickert
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a/status.svg)](https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a"><img src="https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a/status.svg)](https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @jlylekim. **Currently, there isn't an JOSS editor assigned** to your paper.

@jlylekim if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 764

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (430.5 files/s, 148707.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              3            393           1229           2900
reStructuredText                 7             89             57            165
C/C++ Header                     1             39            169            156
make                             2             61             96            128
TeX                              1             11              0             93
Markdown                         2             30              0             76
Python                           1             46             98             36
-------------------------------------------------------------------------------
SUM:                            17            669           1649           3554
-------------------------------------------------------------------------------


Statistical information for the repository '1c517b1420aba53d2e097bb6' was
gathered on 2021/08/22.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Lyle Kim                        14         13779          13235           99.99
Mikael Kuusela                   1             1              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Lyle Kim                    544            3.9          3.8               49.63
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1142/S0217751X20501456 is OK

MISSING DOIs

- 10.1214/15-aoas857 may be a valid DOI for title: Statistical unfolding of elementary particle spectra: Empirical Bayes estimation and bias-corrected uncertainty quantification
- 10.1214/17-aoas1053 may be a valid DOI for title: Shape-constrained uncertainty quantification in unfolding steeply falling elementary particle spectra
- 10.1088/1748-0221/7/10/t10003 may be a valid DOI for title: TUnfold, an algorithm for correcting migration effects in high energy physics

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03645/joss.03645/10.21105.joss.03645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03645/joss.03645/10.21105.joss.03645.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @dpsanders - would you be able to edit this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @dpsanders as editor

**Comment by whedon** [comment]
@dpsanders has been invited to edit this submission.

**Comment by danielskatz** [comment]
@jlylekim - While we find an editor, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by jlylekim** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "year" (NAME) [#<BibTeX::Bibliography data=[3]>, "@", #<BibTeX::Entry >, {:title=>["TUnfold, an algorithm for correcting migration effects in high energy physics"], :author=>["Schmitt, Stefan"], :journal=>["Journal of Instrumentation"], :volume=>["7"], :number=>["10"], :pages=>["T10003"], :doi=>["10.1088/1748-0221/7/10/T10003"]}]

**Comment by jlylekim** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1214/15-AOAS857 is OK
- 10.5075/epfl-thesis-7118 is OK
- 10.1214/17-AOAS1053 is OK
- 10.1088/1748-0221/7/10/T10003 is OK
- 10.1016/S0168-9002(97)00048-X is OK
- 10.1142/S0217751X20501456 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jlylekim** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03645/joss.03645/10.21105.joss.03645.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03645/joss.03645/10.21105.joss.03645.pdf) :page_facing_up: :point_left:

**Comment by jlylekim** [comment]
> **Submitting author:** @jlylekim ([Junhyung Lyle Kim](http://orcid.org/0000-0002-4774-5750))
> **Repository:** https://github.com/jlylekim/UndersmoothedUnfolding
> **Version:** v1.0.0
> **Editor:** Pending
> **Reviewer:** Pending
> **Managing EiC:** Daniel S. Katz
> 
> **⚠️ JOSS reduced service mode ⚠️**
> 
> Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).
> 
> ## Status
> [![status](https://camo.githubusercontent.com/219d74fa68a2ca533e081ba527eb82ef4d989284783c31767043ee40be9e757f/68747470733a2f2f6a6f73732e7468656f6a2e6f72672f7061706572732f66616333656635343930636365316232656431393364306264636433656139612f7374617475732e737667)](https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a)
> 
> Status badge code:
> 
> ```
> HTML: <a href="https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a"><img src="https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a/status.svg"></a>
> Markdown: [![status](https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a/status.svg)](https://joss.theoj.org/papers/fac3ef5490cce1b2ed193d0bdcd3ea9a)
> ```
> 
> **Author instructions**
> 
> Thanks for submitting your paper to JOSS @jlylekim. **Currently, there isn't an JOSS editor assigned** to your paper.
> 
> @jlylekim if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
> 
> **Editor instructions**
> 
> The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:
> 
> ```
> @whedon commands
> ```

Thank you for pointing out the missing DOIs--they are added in the .bib file.

Also, here is a list of potential reviewers:
andrewfowlie
ghammad
rafaelab

Thank you,
Lyle

**Comment by andrewfowlie** [comment]
Looks interesting and I’m in general willing and able to contribute, but  I’m afraid my schedule is too hectic right now.

**Comment by danielskatz** [comment]
@jlylekim - do you have any other suggestions for reviewers?  (they don't have to be from our list, as long as they are knowledgable and not conflicted)

**Comment by matthewfeickert** [comment]
Hi @jlylekim. Before the review gets started please read through the [JOSS Review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html). At the moment there are parts of your submission that don't address requirements there, so it will help speed up the review if you can address them ahead of time.

You're also vendoring ROOT's `TUnfold` in [`TUnfoldV17.cxx`](https://github.com/jlylekim/UndersmoothedUnfolding/blob/349d4d95363eaea2cabd377576caa1a82b036a38/TUnfoldV17.cxx) (which is fine given that [ROOT is licensed under LGPL](https://github.com/root-project/root/blob/9d6cd4cdc00e0b4c55f531ee3777445b1d3c4c60/LICENSE) &mdash; though note that your LICENSE is just a template and not actually filled in)

```
///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
// Junhyung Lyle Kim, Rice University and Mikael Kuusela, Carnegie Mellon University //
// Date: 1/17/2020                                                                   //
// Modified from TUnfoldV17.cxx (version 17.8) by Stefan Schmitt                     //
//                                                                                   //
// Our contribution starts from line XXX to line YYY                                 //
// The rest is from the original TUnfold (version 17.8)                              //
//                                                                                   //
// Our modiciation and its documentation can be found in                             //
// https://jlylekim.github.io/UndersmoothedUnfolding/                                //
//                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
```

and so submitting code from lines [`3706` to `3877` in `TUnfoldV17.cxx`](https://github.com/jlylekim/UndersmoothedUnfolding/blob/349d4d95363eaea2cabd377576caa1a82b036a38/TUnfoldV17.cxx#-L3706-L3877).

I'll defer to @danielskatz and others editors here, but before this goes forward to a full review it would be helpful to understand if this meets the [scholarly effort criteria for JOSS](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) as this is a short extension to ROOT.

**Comment by danielskatz** [comment]
@matthewfeickert - I took 2900 LOC of C++ to be a substantial contribution, and extending an existing package is not a problem.  But now I see that what you are saying is that the contribution is actually just 150 LOC. Is this correct?

**Comment by matthewfeickert** [comment]
> But now I see that what you are saying is that the contribution is actually just 150 LOC. Is this correct?

Yes. As far as I can tell from visual inspection and the code comments, the contribution that differs from `TUnfold` `v17.8` (`TUnfold` is distributed on Stefan Schmitt's website https://www.desy.de/~sschmitt/tunfold.html and we normally see it vendored in ROOT) are [these 171 lines](https://github.com/jlylekim/UndersmoothedUnfolding/blob/349d4d95363eaea2cabd377576caa1a82b036a38/TUnfoldV17.cxx#-L3706-L3877).

**Comment by danielskatz** [comment]
👋 @jlylekim - please confirm that this is correct

**Comment by jlylekim** [comment]
Hi @danielskatz and @matthewfeickert,

Yes, if we restrict the LOC to `TUnfoldV17.cxx` file, then it’s true that the implementation of our main algorithm is from line 3706 to line 3877.

However, if we may add a bit more context:    

1. `UndersmoothedUnfolding` implements a recently proposed modification of Tikhonov-regularized unfolding so that nominal uncertainty quantification is achieved in a fully data-driven manner which is not possible in existing implementations.

2. The reason why we started from `TUnfold` and `ROOT` (instead of implementing from scratch) is because those provide the existing standard implementation of Tikhonov regularization for the high-energy physics unfolding problem. If we provided something in Python, for instance, our implementation of the same final functionality would contain many more lines of new code because we would need to implement the standard functionality provided by `TUnfold` first, but it would be harder from the target users' perspective.

3. More specifically, the way `UndersmoothedUnfolding` works is that, starting from an initial estimate of the regularization strength, `UndersmoothedUnfolding` provides a principled and fully data-driven approach to gradually decrease the regularization strength so that nominal empirical coverage is achieved. The implemented algorithm can be understood as a meta-algorithm that requires other algorithms for estimating the initial regularization strength, for computing the unfolded solution for a given regularization strength, computing stable matrix inverses, etc. We could have implemented these other algorithms ourselves and have many more lines in our source code. However, since `TUnfold` and `ROOT` are the standard libraries for this type of problems with tried and tested implementations of these requisite subalgorithms, we felt that it is more appropriate to base our implementation on these existing packages.

In sum, while the total LOC in `TUnfoldV17.cxx` may seem small, we believe it is mainly due to the nature of our method being a meta-algorithm. This is why we provide two demo files (which contain 623 lines of additional code), one for Gaussian peaks case and the other for steeply falling spectrum case, demonstrating (i) the applicability of `UndersmoothedUnfolding` in different unfolding scenarios, (ii) the failure of existing algorithms in the same scenarios, and (iii) the flexibility that `UndersmoothedUnfolding` can be used starting from virtually any initial estimate (e.g., `TUnfold::scanLcurve`).

We hope this clarifies some concerns raised by the reviewers.

**Comment by danielskatz** [comment]
@jlylekim - While I appreciate your comments, and particularly that you are extending an existing code, we are still going to reject this as not meeting the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by rafaelab** [comment]
@danielskatz @jlylekim 
Sorry for the late reply. I just came back from vacation.
I see this has already been sorted :)
