### ISSUE TITLE
[PRE REVIEW]: Fiscore Package: Effective protein structural data visualisation and exploration

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3647]
**Submitting author:** @AusteKan (<a href="http://orcid.org/0000-0001-6829-4082">Austė  Kanapeckaitė</a>)
**Repository:** <a href="https://github.com/AusteKan/Fiscore" target ="_blank">https://github.com/AusteKan/Fiscore</a>
**Version:** V0.1.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/cd690c3a6f955e0dc5846eb9c16e2fe9/status.svg)](https://joss.theoj.org/papers/cd690c3a6f955e0dc5846eb9c16e2fe9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cd690c3a6f955e0dc5846eb9c16e2fe9"><img src="https://joss.theoj.org/papers/cd690c3a6f955e0dc5846eb9c16e2fe9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cd690c3a6f955e0dc5846eb9c16e2fe9/status.svg)](https://joss.theoj.org/papers/cd690c3a6f955e0dc5846eb9c16e2fe9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @AusteKan. **Currently, there isn't an JOSS editor assigned** to your paper.

@AusteKan if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1517

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (157.3 files/s, 35817.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                             1            306              5           2280
Markdown                         3            173              0            559
R                               14            196            368            255
TeX                              1             17              0            107
Rmd                              1            130            137             22
-------------------------------------------------------------------------------
SUM:                            20            822            510           3223
-------------------------------------------------------------------------------


Statistical information for the repository '05afa50dcd0954fd7b6301f0' was
gathered on 2021/08/23.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/07391102.2020.1854859 is OK
- 10.1016/j.cbpa.2011.05.020 is OK
- 10.1016/j.cclet.2020.03.028 is OK
- 10.1002/prot.22193 is OK
- 10.1007/978-1-4899-7488-4 is OK
- 10.1214/13-STS452 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03647/joss.03647/10.21105.joss.03647.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03647/joss.03647/10.21105.joss.03647.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @AusteKan - I'm sorry to say that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Note specifically "Total lines of code (LOC). Submissions under 1000 LOC will usually be flagged, those under 300 LOC will be desk rejected." Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
