### ISSUE TITLE
[PRE REVIEW]: PDLSM-FEM: Solver of Coupled Peridynamics Least Squares Minimization with Finite Element Method

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3648]
**Submitting author:** @QibangLiu  (<a href="http://orcid.org/0000-0001-7935-7907">Qibang Liu</a>)
**Repository:** <a href="https://github.com/QibangLiu/PDLSM-FEM_mpi" target ="_blank">https://github.com/QibangLiu/PDLSM-FEM_mpi</a>
**Version:** v1.0
**Editor:** @prashjha
**Reviewers:** @TLCFEM, @karthikncsu, @Balaje
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e429ae33fb3c06beb9a315f22354262f/status.svg)](https://joss.theoj.org/papers/e429ae33fb3c06beb9a315f22354262f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e429ae33fb3c06beb9a315f22354262f"><img src="https://joss.theoj.org/papers/e429ae33fb3c06beb9a315f22354262f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e429ae33fb3c06beb9a315f22354262f/status.svg)](https://joss.theoj.org/papers/e429ae33fb3c06beb9a315f22354262f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @QibangLiu . **Currently, there isn't an JOSS editor assigned** to your paper.

@QibangLiu  if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 551

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (890.3 files/s, 201112.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             30            930           2024          10106
C/C++ Header                    29            129            166            880
TeX                              1             27              0            249
CMake                            4             13             36             81
Markdown                         1             17              0             25
-------------------------------------------------------------------------------
SUM:                            65           1116           2226          11341
-------------------------------------------------------------------------------


Statistical information for the repository 'f247d4748bf3308995971202' was
gathered on 2021/08/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
QibangLiu                       21         16580           2345          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
QibangLiu                 14235           85.9          2.2               20.79
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.2514/6.2017-5141 is OK
- 10.2514/6.2018-5109 is OK
- 10.1061/9780784481899.082 is OK
- 10.1109/IROS.2017.8206022 is OK
- 10.1177/0956059919845330 is OK
- 10.23919/ACC.2017.7963738 is OK
- 10.1007/s11044-019-09666-4 is OK
- 10.1260/0266-3511.30.3-4.221 is OK
- 10.2514/6.2003-1978 is OK
- 10.21105/joss.01042 is OK
- 10.1016/S0065-2156(09)43002-3 is OK
- 10.1007/s10659-007-9125-1 is OK
- 10.1007/s00466-017-1469-1 is OK
- 10.1016/j.cma.2014.06.016 is OK
- 10.1016/j.cma.2019.01.032 is OK
- 10.1016/j.engfracmech.2020.107483 is OK
- 10.1007/s10704-012-9745-8 is OK
- 10.1007/978-1-4614-8465-3 is OK
- 10.1016/j.engfracmech.2021.107862 is OK

MISSING DOIs

- 10.2172/1895 may be a valid DOI for title: Reformulation of elasticity theory for discontinuities and long-range forces

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3648 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
👋 @QibangLiu - Please note that your paper does not compile.  Your header has a lot of blank lines that may be causing problems.  Please follow the example in https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

In addition, you could work on the possibly missing DOI that whedon suggests, but note that this may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again

When you have made changes to the paper, use command `@whedon generate pdf` to make a new PDF.

Whedon commands need to be the first entry in a new comment.

**Comment by QibangLiu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3648 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
Please remove the orcid line for X.J. Jin - this should only be there when an author has an ORCID.

**Comment by QibangLiu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3648 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:204:in `block in parse_authors': Author (Qibang Liu) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by QibangLiu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3648 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (a3fa7d39ffc860e27cc6d7bb/JOSS_paper/paper.md): could not find expected ':' while scanning a simple key at line 17 column 4 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by QibangLiu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03648/joss.03648/10.21105.joss.03648.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03648/joss.03648/10.21105.joss.03648.pdf) :page_facing_up: :point_left:

**Comment by QibangLiu** [comment]
@danielskatz Thanks. It's compiled now.

**Comment by QibangLiu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3648 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:204:in `block in parse_authors': Author (Qibang Liu) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by QibangLiu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03648/joss.03648/10.21105.joss.03648.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03648/joss.03648/10.21105.joss.03648.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @prashjha - would you be able to review this submission for JOSS?

**Comment by danielskatz** [comment]
@whedon invite @prashjha as editor

**Comment by whedon** [comment]
@prashjha has been invited to edit this submission.

**Comment by prashjha** [comment]
@danielskatz thanks!

**Comment by prashjha** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @prashjha

**Comment by prashjha** [comment]
@whedon assign me as reviewer

**Comment by whedon** [comment]
OK, me is now a reviewer

**Comment by prashjha** [comment]
@whedon remove me as reviewer

**Comment by whedon** [comment]
OK, me is no longer a reviewer

**Comment by prashjha** [comment]
@whedon assign @prashjha as reviewer

**Comment by whedon** [comment]
OK, @prashjha is now a reviewer

**Comment by prashjha** [comment]
Hey @karthikncsu, would you be interested in reviewing this submission for JOSS (Journal of Open Source Software)? In JOSS, reviews are open and transparent. As a reviewer, you have to assess the submission using a checklist. You can find more information about the reviewing process here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html# If you need any help, let me know.

**Comment by danielskatz** [comment]
Hi @prashjha - I'm a bit confused by what's going on here. Normally in JOSS, the editor finds at least 2 reviewers, but is not one of the reviewers.

**Comment by prashjha** [comment]
@danielskatz I found the submission interesting enough so counted me as a reviewer and requested another person to be second reviewer. Is it not okay? This is done I think in couple of cases before.

**Comment by danielskatz** [comment]
We normally only have the editor act as a reviewer if we lose a reviewer during the process and need someone to step in.  Ideally, the two reviewers and the editor are separate people to have two independent points of view and a neutral editor to make the process work. Unless there's a reason you can't find 2 reviewers, you should.

**Comment by karthikncsu** [comment]
Hi @prashjha, I am interested in reviewing the repo.

**Comment by prashjha** [comment]
Hi @karthikncsu thank you for agreeing to be a reviewer.

**Comment by prashjha** [comment]
@whedon add @karthikncsu as reviewer

**Comment by whedon** [comment]
OK, @karthikncsu is now a reviewer

**Comment by prashjha** [comment]
@danielskatz I see.

**Comment by prashjha** [comment]
@whedon remove @prashjha as reviewer

**Comment by whedon** [comment]
OK, @prashjha is no longer a reviewer

**Comment by prashjha** [comment]
Hi @bhajay, would you be interested in reviewing this submission?

**Comment by prashjha** [comment]
@karthikncsu just wanted to let you know that we will begin the review when we also have the second reviewer.

**Comment by prashjha** [comment]
Hi @jakryd, would you be interested in reviewing this submission?

**Comment by prashjha** [comment]
Hi @JaroslavHron, any chance you could review this submission?

**Comment by prashjha** [comment]
Hello @TLCFEM, would you be interested in reviewing this submission?

**Comment by prashjha** [comment]
Hi @Balaje, any chance you could review this submission?

**Comment by TLCFEM** [comment]
> Hello @TLCFEM, would you be interested in reviewing this submission? 

👌👌👌

**Comment by prashjha** [comment]
I am assuming @TLCFEM you are okay with being a reviewer. :)

**Comment by prashjha** [comment]
@whedon assign @TLCFEM as reviewer

**Comment by whedon** [comment]
OK, @TLCFEM is now a reviewer

**Comment by prashjha** [comment]
@whedon add @karthikncsu as reviewer

**Comment by whedon** [comment]
OK, @karthikncsu is now a reviewer

**Comment by Balaje** [comment]
> Hi @Balaje, any chance you could review this submission?

Yes, I am interested in reviewing this repo.

**Comment by prashjha** [comment]
Hi @Balaje, great. Thanks for your response. :)

Hey @QibangLiu, looks like we have enough reviewers to start the review. We wait for one more day and then start the process.

**Comment by prashjha** [comment]
@whedon add @Balaje as reviewer

**Comment by whedon** [comment]
OK, @Balaje is now a reviewer

**Comment by QibangLiu** [comment]
@prashjha Thanks.

**Comment by JaroslavHron** [comment]
Hi - I see you have enough reviewer. If needed I can do the review too.

**Comment by prashjha** [comment]
@JaroslavHron thanks. Since we have 3 reviewers already, it will be better if we wait to get another submission to get your reviews. I appreciate the response. :)

**Comment by prashjha** [comment]
Hi @bhajay and @jakryd, we now have three reviewers so please ignore my request.

**Comment by prashjha** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3668.
