### ISSUE TITLE
[PRE REVIEW]: sandpyper: A Python package for UAV-SfM beach volumetric and behavioural analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3654]
**Submitting author:** @npucino (<a href="http://orcid.org/0000-0001-6260-6647">Nicolas Pucino</a>)
**Repository:** <a href="https://github.com/npucino/sandpyper" target ="_blank">https://github.com/npucino/sandpyper</a>
**Version:** v1.0.0
**Editor:** @crvernon
**Reviewers:** @dbuscombe-usgs, @chrisleaman
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ff00f33cd9152b1834727ffb8be4122a/status.svg)](https://joss.theoj.org/papers/ff00f33cd9152b1834727ffb8be4122a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ff00f33cd9152b1834727ffb8be4122a"><img src="https://joss.theoj.org/papers/ff00f33cd9152b1834727ffb8be4122a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ff00f33cd9152b1834727ffb8be4122a/status.svg)](https://joss.theoj.org/papers/ff00f33cd9152b1834727ffb8be4122a)
```

**Author instructions**

Thanks for submitting your paper to JOSS @npucino. **Currently, there isn't an JOSS editor assigned** to your paper.

@npucino if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1349

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/0031-868x.00152 is OK
- 10.1371/journal.pone.0118571 is OK
- 10.1890/10-1510.1 is OK
- 10.1038/s41598-021-83477-6 is OK
- 10.1016/j.earscirev.2017.04.011 is OK
- 10.1016/j.ecolecon.2006.10.022 is OK
- 10.1016/j.ocecoaman.2018.01.001 is OK
- 10.1016/j.isprsjprs.2015.02.009 is OK
- 10.21105/joss.01890 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.59 s (65.7 files/s, 87890.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           6           1709           1175           4856
Markdown                        17            286              0            654
Jupyter Notebook                 7              0          42186            625
TeX                              1              9              0            404
YAML                             6             25             10            191
JavaScript                       1              1              0             19
HTML                             1              2              0              9
-------------------------------------------------------------------------------
SUM:                            39           2032          43371           6758
-------------------------------------------------------------------------------


Statistical information for the repository '15836406812b91115fdd1441' was
gathered on 2021/08/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nicolas Pucino                 187         18307          11042           94.22
npucino                         17          1078            724            5.78

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Nicolas Pucino             7760           42.4          0.4                5.66
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03654/joss.03654/10.21105.joss.03654.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03654/joss.03654/10.21105.joss.03654.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @crvernon - Would you be able to edit this JOSS submission?

**Comment by danielskatz** [comment]
@whedon invite @crvernon as editor

**Comment by whedon** [comment]
@crvernon has been invited to edit this submission.

**Comment by crvernon** [comment]
@danielskatz - I'll be happy to take this on, thanks!

**Comment by crvernon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @crvernon

**Comment by crvernon** [comment]
:wave: @npucino - I'll be your topic editor for this submission.  

The first step in this pre-review is to find at least 2 reviewers. If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this [list of people](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit?usp=sharing) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by npucino** [comment]
Thank you Daniel, thank you Chris, for taking care of my submission!
Here is a list of potential reviewers of this code, taken from the JOSS list:
- dbuscombe-usgs
- TomasBeuzen
- chrisleaman
- pwernette

Have a nice day,
Nick

**Comment by crvernon** [comment]
:wave: @dbuscombe-usgs @TomasBeuzen - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by chrisleaman** [comment]
@crvernon - keen to take a look at this, sign me up!

**Comment by crvernon** [comment]
@whedon add @chrisleaman as reviewer

**Comment by whedon** [comment]
OK, @chrisleaman is now a reviewer

**Comment by crvernon** [comment]
Alright @dbuscombe-usgs @chrisleaman @npucino I am going to close this Pre-Review and kick off the full review which you should receive a notification for. Thanks!

**Comment by crvernon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3666.
