### ISSUE TITLE
[PRE REVIEW]: DAQari: Browser-based real-time data acquisition solution

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3655]
**Submitting author:** @nravanelli (<a href="http://orcid.org/0000-0002-4894-9552">Nicholas Ravanelli</a>)
**Repository:** <a href="https://github.com/nravanelli/DAQari" target ="_blank">https://github.com/nravanelli/DAQari</a>
**Version:** v1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ac2ab1df9ac70eed788d6c2ad0a84b12/status.svg)](https://joss.theoj.org/papers/ac2ab1df9ac70eed788d6c2ad0a84b12)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ac2ab1df9ac70eed788d6c2ad0a84b12"><img src="https://joss.theoj.org/papers/ac2ab1df9ac70eed788d6c2ad0a84b12/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ac2ab1df9ac70eed788d6c2ad0a84b12/status.svg)](https://joss.theoj.org/papers/ac2ab1df9ac70eed788d6c2ad0a84b12)
```

**Author instructions**

Thanks for submitting your paper to JOSS @nravanelli. **Currently, there isn't an JOSS editor assigned** to your paper.

@nravanelli if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 717

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.17 s (215.4 files/s, 138722.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              4              0              1           9562
CSS                             16           3679             66           8181
JavaScript                      11            109             97            892
HTML                             1             36              6            345
Markdown                         2             36              0            100
TeX                              1              4              0             34
Arduino Sketch                   1              9             10             20
-------------------------------------------------------------------------------
SUM:                            36           3873            180          19134
-------------------------------------------------------------------------------


Statistical information for the repository 'e8070a9c4bc8e341803afb54' was
gathered on 2021/08/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
nravanelli                      11          5448           4350          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
nravanelli                 1098           20.2          0.4                8.83
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1021/acs.jchemed.6b00262 is OK
- 10.1119/1.4978720 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03655/joss.03655/10.21105.joss.03655.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03655/joss.03655/10.21105.joss.03655.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @nravanelli - thanks for your submission.  Due to the relatively small amount of code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  I'm also unsure if this meets our [definition of research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software). You should hear back in a week or so.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by nravanelli** [comment]
Thanks @danielskatz for the update. I appreciate the consideration by the editorial board and would be happy to address any concerns they may have, whether it is further documentation or additional requirements.

This is a piece of software that I developed for my lab to record analog signals (human temperature regulation: thermocouples/thermistors/humidity sensors) without the need for expensive DAQ units.

**Comment by nravanelli** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03655/joss.03655/10.21105.joss.03655.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03655/joss.03655/10.21105.joss.03655.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@nravanelli – Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
