### ISSUE TITLE
[PRE REVIEW]: Devicely: A Python package for reading, timeshifting and writing sensor data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3656]
**Submitting author:** @arianesasso (<a href="http://orcid.org/0000-0002-3669-4599">AM Sasso, A Sasso</a>)
**Repository:** <a href="https://github.com/hpi-dhc/devicely/" target ="_blank">https://github.com/hpi-dhc/devicely/</a>
**Version:** v1.1.0
**Editor:** @prashjha
**Reviewers:** @luciorq, @djmitche
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3abafc8a04e02d7c61d0bf4fb714af28/status.svg)](https://joss.theoj.org/papers/3abafc8a04e02d7c61d0bf4fb714af28)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3abafc8a04e02d7c61d0bf4fb714af28"><img src="https://joss.theoj.org/papers/3abafc8a04e02d7c61d0bf4fb714af28/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3abafc8a04e02d7c61d0bf4fb714af28/status.svg)](https://joss.theoj.org/papers/3abafc8a04e02d7c61d0bf4fb714af28)
```

**Author instructions**

Thanks for submitting your paper to JOSS @arianesasso. **Currently, there isn't an JOSS editor assigned** to your paper.

@arianesasso if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1009

**Comment by whedon** [comment]
PDF failed to compile for issue #3656 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (b615f0cce7a668304bf3fbfd/inst/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (398.5 files/s, 212746.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      14           2405           2473           9213
HTML                             7            998             21           4161
SVG                              1              0              0           2671
Python                          14            399            452           1799
CSS                              4            191             35            757
TeX                              2             40             11            213
Markdown                         4             66              0            189
reStructuredText                 3             50             20             88
Jupyter Notebook                 1              0           2885             66
YAML                             1              8              0             47
TOML                             1              3              0             36
DOS Batch                        1              8              1             26
JSON                             1              0              0             14
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            55           4172           5905          19289
-------------------------------------------------------------------------------


Statistical information for the repository 'b08d775bb19d948eda4e4b0d' was
gathered on 2021/08/24.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ariane Morassi Sasso            47           953            662            3.15
Ariane Morassi-Sasso             3            20             19            0.08
Ariane Sasso                     9           568              6            1.12
Jost Morgenstern                 2            12              3            0.03
jostmorgenstern                 64         32444          16585           95.63

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ariane Morassi Sasso        631           66.2          1.2                6.97
jostmorgenstern           16110           49.7          7.3               15.94
```

**Comment by danielskatz** [comment]
@arianesasso - your header has some indentation that is not consistent - please make sure to make it consistent; see the [sample paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) if needed. Please feel free to make changes to your .md file, then use the command `@whedon generate pdf` to try to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
@whedon check references

**Comment by danielskatz** [comment]
After the paper builds, you could also use `@whedon check references` to check the references.  I'm not sure why it's not working now, but perhaps it's related to the pdf problem.

**Comment by arianesasso** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03656/joss.03656/10.21105.joss.03656.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03656/joss.03656/10.21105.joss.03656.pdf) :page_facing_up: :point_left:

**Comment by arianesasso** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/s18061714 is OK
- 10.1038/s41569-021-00522-7 is OK
- 10.1038/s41551-020-00640-6 is OK
- 10.21105/joss.02106 is OK
- 10.21105/joss.01663 is OK
- 10.21105/joss.01867 is OK
- 10.21105/joss.01778 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arianesasso** [comment]
@whedon generate pdf

@danielskatz Thank you for the help! I think now it is ready. I would suggested as reviewers (from the list): hooman650, acolum, nirum

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03656/joss.03656/10.21105.joss.03656.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03656/joss.03656/10.21105.joss.03656.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @prashjha - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @prashjha as editor

**Comment by whedon** [comment]
@prashjha has been invited to edit this submission.

**Comment by prashjha** [comment]
Hi @djmitche, would you be interested in reviewing this submission?

**Comment by prashjha** [comment]
Hi @cbrueffer, any chance you could review this submission?

**Comment by prashjha** [comment]
Hi @Chilipp, any chance you could review this submission?

**Comment by Chilipp** [comment]
Hey @prashjha, thanks for asking! Unfortunately I am totally blocked within the next 4 weeks due to too many other tasks and vacation.

Cheers

**Comment by prashjha** [comment]
Hi @Chilipp, I see. Thanks for letting me know. Have a good one!

**Comment by prashjha** [comment]
Hi @tupi, would you be interested in reviewing this submission?

**Comment by prashjha** [comment]
Hello @TomKellyGenetics, this submission may be of interest to you. Any chance you could do the review?

**Comment by cbrueffer** [comment]
Hi @prashjha, I'm already overcommitted at the moment, sorry.

**Comment by prashjha** [comment]
Hi @cbrueffer, no worries. Thanks for letting me know. Good luck. :)

**Comment by djmitche** [comment]
> Hi @djmitche, would you be interested in reviewing this submission?

Sure!

**Comment by prashjha** [comment]
@djmitche awesome. Thanks. :)
We will wait for another reviewer and then start the review.

**Comment by TomKellyGenetics** [comment]
Sorry I've recently started a new job and can't take this on at the moment. Wish the authors all the best with their submission.

**Comment by prashjha** [comment]
@TomKellyGenetics no worries and thanks for letting me know! Good luck with your new job. :)

**Comment by prashjha** [comment]
Hey @luciorq, would you like to review this submission?

**Comment by prashjha** [comment]
Hi @sridhar0605, any chance you could review this submission?

**Comment by luciorq** [comment]
> Hey @luciorq, would you like to review this submission?

Sure, count on me @prashjha! I will go through the process as soon as possible.

**Comment by prashjha** [comment]
@luciorq thank you! I will go ahead and start the review. :)

**Comment by prashjha** [comment]
Hello @tupi and @sridhar0605, we now have two reviewers so please ignore my requests. :)

**Comment by prashjha** [comment]
@arianesasso hello, we have two reviewers so starting the review. Please keep an eye on any comments or issues created by reviewers during the review process.

**Comment by prashjha** [comment]
@whedon start review

**Comment by whedon** [comment]
It looks like you don't have an editor and reviewer assigned yet so I can't start the review. Try one or more of these commands:

```
# Change editorial assignment
@whedon assign @username as editor

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer
```

**Comment by prashjha** [comment]
@wheddon assign @djmitche as reviewer

**Comment by prashjha** [comment]
@whedon add @luciorq as reviewer

**Comment by whedon** [comment]
OK, @luciorq is now a reviewer

**Comment by whedon** [comment]
OK, @djmitche is now a reviewer

**Comment by prashjha** [comment]
@whedon start review

**Comment by sridhar0605** [comment]
Hello all, 
Apologies @prashjha completely missed this, will keep an eye out for next one. 
-S

**Comment by prashjha** [comment]
Hi @sridhar0605 no worries :)
