### ISSUE TITLE
[PRE REVIEW]: serp: An R package for smoothing in ordinal regression

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3657]
**Submitting author:** @ejikeugba (<a href="http://orcid.org/0000-0003-2572-0023">Ejike Ugba</a>)
**Repository:** <a href="https://github.com/ejikeugba/serp" target ="_blank">https://github.com/ejikeugba/serp</a>
**Version:** v.0.2.0
**Editor:** @Bisaloo
**Reviewers:** @bernardsilenou, @wesleyburr
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6ebd3b75ea792be908f0dadebd7cf81c/status.svg)](https://joss.theoj.org/papers/6ebd3b75ea792be908f0dadebd7cf81c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6ebd3b75ea792be908f0dadebd7cf81c"><img src="https://joss.theoj.org/papers/6ebd3b75ea792be908f0dadebd7cf81c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6ebd3b75ea792be908f0dadebd7cf81c/status.svg)](https://joss.theoj.org/papers/6ebd3b75ea792be908f0dadebd7cf81c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ejikeugba. **Currently, there isn't an JOSS editor assigned** to your paper.

@ejikeugba if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Downloading of the repository (to analyze the language) for issue #3657 failed with the following error: 
```
 
```

**Comment by whedon** [comment]
Downloading of the repository (to check the bibtex) failed for issue #3657 failed with the following error: 
```

```

**Comment by whedon** [comment]
PDF failed to compile for issue #3657 with the following error: 
```
 
```

**Comment by danielskatz** [comment]
👋 @openjournals/dev - can you check on this?  The repo looks fine to me

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1543

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (679.2 files/s, 91927.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               15            129            617           1808
TeX                              1             67              0            259
Markdown                         4             69              0            210
YAML                             5             45              9            201
Rmd                              1             27             71              7
-------------------------------------------------------------------------------
SUM:                            26            337            697           2485
-------------------------------------------------------------------------------


Statistical information for the repository '24760cb484bfcc6b2f78a3c5' was
gathered on 2021/08/25.
No commited files with the specified extensions were found.
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3657 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:204:in `block in parse_authors': Author (Ejike R. Ugba) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.4137/cin.s20806 may be a valid DOI for title: Ordinalgmifs: An R package for ordinal regression in highdimensional data settings
- 10.18637/jss.v033.i01 may be a valid DOI for title: Regularization paths for generalized linear models via coordinate descent
- 10.2307/2288515 may be a valid DOI for title: Advanced Econometrics: A Bridge to the Literature
- 10.1007/bf02985802 may be a valid DOI for title: The Elements of Statistical Learning: Data Mining, Inference and Prediction
- 10.1080/00401706.2000.10485983 may be a valid DOI for title: Ridge Regression: Biased Estimation for Nonorthogonal Problems
- 10.1002/wics.1296 may be a valid DOI for title: Bias in parametric estimation: reduction and useful side-effects
- 10.4135/9781412983273.n1 may be a valid DOI for title: Generalized Linear Models
- 10.4135/9781412983273.n1 may be a valid DOI for title: Generalized linear models
- 10.2307/2347760 may be a valid DOI for title: Partial proportional odds models for ordinal response variables
- 10.3390/stats4030037 may be a valid DOI for title: Smoothing in Ordinal Regression: An Application to Sensory Data
- 10.1080/01621459.2016.1180986 may be a valid DOI for title: Smoothing parameter and model selection for general smooth models
- 10.1111/j.1467-9868.2005.00503.x may be a valid DOI for title: Regularization and variable selection via the elastic net

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@ejikeugba - your paper header has at least one problem; see the [sample paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) if needed. Please feel free to make changes to your .md file, then use the command `@whedon generate pdf` to try to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment]
After the paper builds, you also could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF.

**Comment by danielskatz** [comment]
I think the problem in the paper is the indentation - please follow the sample paper's indentation.

**Comment by ejikeugba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03657/joss.03657/10.21105.joss.03657.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03657/joss.03657/10.21105.joss.03657.pdf) :page_facing_up: :point_left:

**Comment by ejikeugba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.4137/cin.s20806 may be a valid DOI for title: Ordinalgmifs: An R package for ordinal regression in highdimensional data settings
- 10.2307/2288515 may be a valid DOI for title: Advanced Econometrics: A Bridge to the Literature
- 10.1007/bf02985802 may be a valid DOI for title: The Elements of Statistical Learning: Data Mining, Inference and Prediction
- 10.1080/00401706.2000.10485983 may be a valid DOI for title: Ridge Regression: Biased Estimation for Nonorthogonal Problems
- 10.1002/wics.1296 may be a valid DOI for title: Bias in parametric estimation: reduction and useful side-effects
- 10.2307/2347760 may be a valid DOI for title: Partial proportional odds models for ordinal response variables
- 10.3390/stats4030037 may be a valid DOI for title: Smoothing in Ordinal Regression: An Application to Sensory Data
- 10.1080/01621459.2016.1180986 may be a valid DOI for title: Smoothing parameter and model selection for general smooth models
- 10.1111/j.1467-9868.2005.00503.x may be a valid DOI for title: Regularization and variable selection via the elastic net

INVALID DOIs

- None
```

**Comment by ejikeugba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/9780470594001 is OK
- doi.org/10.4137/CIN.S20806 is OK
- 10.1080/00401706.2000.10485983 is OK
- 10.1002/wics.1296 is OK
- 10.2307/2347760 is OK
- 10.1177/1471082X16642560 is OK
- 10.3390/stats4030037 is OK
- 10.1080/01621459.2016.1180986 is OK
- 10.1111/j.1467-9868.2005.00503.x is OK

MISSING DOIs

- 10.2307/2288515 may be a valid DOI for title: Advanced Econometrics: A Bridge to the Literature
- 10.1007/bf02985802 may be a valid DOI for title: The Elements of Statistical Learning: Data Mining, Inference and Prediction

INVALID DOIs

- None
```

**Comment by Bisaloo** [comment]
Hi @DominiqueMakowski :wave:, I think you could bring some interesting insights given your work on statistical R packages. Would you be interested in reviewing this package for JOSS?

**Comment by Bisaloo** [comment]
@whedon add @bernardsilenou as reviewer

**Comment by Bisaloo** [comment]
Hi @LucyMcGowan :wave:, I saw some of your posts on twitter and you would seem like a great fit to review this submission. Would you be available?

**Comment by DominiqueMakowski** [comment]
Hey @Bisaloo thanks for the invite :) I quickly checked the package and because it is focused on a particular type of model (which I have no experience with) I don't feel confident in reviewing it (since I mostly dabble in general post-processing). Apologies and don't hesitate next time!

**Comment by ejikeugba** [comment]
@bernardsilenou thanks for accepting to review this submission.
@bisaloo, thanks for the progress thus far. While we await LucyMcGowan's reply, could we also check wesleyburr, OwenWard, or mariobecerra. They all seem to be suitable for this submission.

**Comment by Bisaloo** [comment]
Thanks for the suggestions! Looking at their GitHub profiles, they all seem to be able to produce an interesting review for this paper indeed.

@wesleyburr, @OwenWard, @mariobecerra, would one of you be available to review this R package for JOSS. So you don't have to scroll, [this is the manucript](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03657/joss.03657/10.21105.joss.03657.pdf) and [this is the package itself](https://github.com/ejikeugba/serp).

Thanks :slightly_smiling_face:

**Comment by wesleyburr** [comment]
@Bisaloo - yes, I can review this, so long as you're ok if I leave it until September 20-24. I'm a bit swamped with the start of term and other commitments next week.

**Comment by Bisaloo** [comment]
Hi @wesleyburr :wave:, thanks for your quick answer! 

> @Bisaloo - yes, I can review this, so long as you're ok if I leave it until September 20-24. I'm a bit swamped with the start of term and other commitments next week.

Yes, it's fine. The other reviewer, Bernard Silenou, is not available until September 20 either so we can start the review at this moment. I'll still launch the review process but I have noted you will not be able to start right now. I'll ping you as a reminder on September 20.

**Comment by Bisaloo** [comment]
@whedon add @wesleyburr as reviewer

**Comment by whedon** [comment]
OK, @wesleyburr is now a reviewer

**Comment by Bisaloo** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3705.
