### ISSUE TITLE
[REVIEW]: Django Remote Submission

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#366]
**Submitting author:** @ricleal (<a href="http://orcid.org/0000-0002-9931-8304">Ricardo Miguel Ferraz Leal</a>)
**Repository:** <a href="https://github.com/ornl-ndav/django-remote-submission" target ="_blank">https://github.com/ornl-ndav/django-remote-submission</a>
**Version:** v0.11.1
**Editor:** @arfon
**Reviewer:** @djmitche
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.848749" target="_blank">10.5281/zenodo.848749</a>

## Status

[![status](http://joss.theoj.org/papers/98bd10d0cf254c881f5716318e8ceb6d/status.svg)](http://joss.theoj.org/papers/98bd10d0cf254c881f5716318e8ceb6d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/98bd10d0cf254c881f5716318e8ceb6d"><img src="http://joss.theoj.org/papers/98bd10d0cf254c881f5716318e8ceb6d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/98bd10d0cf254c881f5716318e8ceb6d/status.svg)](http://joss.theoj.org/papers/98bd10d0cf254c881f5716318e8ceb6d)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/ornl-ndav/django-remote-submission" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@djmitche, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ornl-ndav/django-remote-submission">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.11.1)?
- [x] **Authorship:** Has the submitting author (@ricleal) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @djmitche it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@djmitche - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by djmitche** [comment]
*  Version: https://github.com/ornl-ndav/django-remote-submission/issues/33
* References:  I think this is OK, but there are no DOIs.  All of the referenced software (Django, Redis, Celery) probably doesn't have a DOI. @arfon am I missing anything there?

(I will continue later)

**Comment by ricleal** [comment]
Thanks @arfon and @djmitche for putting effort into reviewing this.
I was away the last few days but will have a look at the updated guidelines and expand a little on how this peace of software enables and addresses research challenges.
Thanks again

**Comment by djmitche** [comment]
While you're thinking about that, I'm also curious what value this adds over Celery itself.  The code may demonstrate that to me when I dig in, so I apologize if the question seems ignorant.

**Comment by ricleal** [comment]
Not ignorant at all. Celery is just an asynchronous job queue. We have build around that. Django uses the Database to provide data to views and hence to the browser. Our Jobs besides running our scientific routines must be constantly writing to the DB (e.g. changing the status of the job - submitted, failed, etc - as well writing the routine stdout/err, etc) so the browser can track the job and show as much information as possible.
A Job includes thus the ssh/sftp to the cluster, the database updates and the launching of the scientific routine itself. This Job is what we submit to Celery.
Hope that was clear.

**Comment by ricleal** [comment]
`paper.md` and `paper.bib` have been updated.

**Comment by djmitche** [comment]
Awesome, thanks for the updates!

**Comment by djmitche** [comment]
That's almost all the checkmarks (just **Version** left)!

This is a really nice piece of software, and *extremely* nicely packaged for re-use.  A few minor details which would make this a little stronger, but do not detract from an "accept" grade:
 * The documentation mixes developer-oriented stuff (how to run tests, how to release) with user-oriented stuff (model, tasks, etc.), and in fact the user-oriented stuff appears last.  A little reorganization there could help a new user to quickly find the information they need and not skim the release process wondering "how does this help me??"
 * The tests don't pass for me.  I expect it's something with my SSH config, and I [filed an issue](https://github.com/ornl-ndav/django-remote-submission/issues/39) about it.  I can see that the test pass in Travis so I trust that they are good tests!

**Comment by djmitche** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by djmitche** [comment]
Oh, and I apologize for the slew of pull requests (5 PRs, 2 issues) -- I take the view that if it's easier for me to just fix something, then that's the appropriate way to provide feedback :)

**Comment by ricleal** [comment]
Thanks for the feedback. I will address all the issues tomorrow.

**Comment by djmitche** [comment]
OK, that's everything.  I don't know what happens next (it's my first JOSS review)..

**Comment by ricleal** [comment]
Great. I've been trying to reproduce your test failures but without success... I will try in a empty docker container later. Also I will try to get the `extras_require` in `setup.py` as you suggested. This was an issue that should have been addressed long time ago...

**Comment by djmitche** [comment]
To be clear regarding the review, those were just suggestions for further improvement -- this is a strong "accept" for JOSS right now.

**Comment by ricleal** [comment]
Sure. I just want to make it as user friendly as possible so other people can use it.
I forgot to mention. I also updated/restructured the documentation as suggested.

**Comment by djmitche** [comment]
Oh, I hadn't looked until now -- that's *much* better!

**Comment by ricleal** [comment]
Just a quick heads up:
- I have added Acknowledgments section to the paper (a required statement that I forgot...)
- Since this contribution was accepted shouldn't the ticket be closed?

**Comment by djmitche** [comment]
@arfon ^^

**Comment by ricleal** [comment]
Done. Here it goes:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.848749.svg)](https://doi.org/10.5281/zenodo.848749)

I will update the Zenodo metadata once it gets published.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.848749 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.848749" target="_blank">10.5281/zenodo.848749</a> is the archive.

**Comment by arfon** [comment]
@djmitche many thanks for your review ✨ 

@ricleal - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00366 ⚡️ 🚀 💥
