### ISSUE TITLE
[PRE REVIEW]: text2map: R Tools for Text Matrices

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3660]
**Submitting author:** @dustinstoltz (<a href="http://orcid.org/0000-0002-4774-0765">Dustin Stoltz</a>)
**Repository:** <a href="https://gitlab.com/culturalcartography/text2map" target ="_blank">https://gitlab.com/culturalcartography/text2map</a>
**Version:** 0.1.0
**Editor:** @chartgerink
**Reviewers:** @alexanderfurnas, @mbod
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/feca193c948441faa6ccc14312b3d169/status.svg)](https://joss.theoj.org/papers/feca193c948441faa6ccc14312b3d169)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/feca193c948441faa6ccc14312b3d169"><img src="https://joss.theoj.org/papers/feca193c948441faa6ccc14312b3d169/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/feca193c948441faa6ccc14312b3d169/status.svg)](https://joss.theoj.org/papers/feca193c948441faa6ccc14312b3d169)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dustinstoltz. **Currently, there isn't an JOSS editor assigned** to your paper.

@dustinstoltz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by chartgerink** [comment]
@whedon add @alexanderfurnas as reviewer

**Comment by whedon** [comment]
OK, @alexanderfurnas is now a reviewer

**Comment by chartgerink** [comment]
@whedon add @mbod as reviewer

**Comment by whedon** [comment]
OK, @mbod is now a reviewer

**Comment by chartgerink** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3741.
