### ISSUE TITLE
[REVIEW]: infer: An R package for tidyverse-friendly statistical inference

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3661]
**Submitting author:** @simonpcouch (<a href="http://orcid.org/0000-0001-5676-5107">Simon Couch</a>)
**Repository:** <a href="https://github.com/tidymodels/infer" target ="_blank">https://github.com/tidymodels/infer</a>
**Version:** v1.0.1
**Editor:** @csoneson
**Reviewer:** @prdm0, @kellieotto
**Archive:** <a href="https://doi.org/10.5281/zenodo.5504495" target="_blank">10.5281/zenodo.5504495</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/70a4889b1d9f812568dffad86566e86e/status.svg)](https://joss.theoj.org/papers/70a4889b1d9f812568dffad86566e86e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/70a4889b1d9f812568dffad86566e86e"><img src="https://joss.theoj.org/papers/70a4889b1d9f812568dffad86566e86e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/70a4889b1d9f812568dffad86566e86e/status.svg)](https://joss.theoj.org/papers/70a4889b1d9f812568dffad86566e86e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/tidymodels/infer" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@prdm0 & @kellieotto, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @prdm0
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/tidymodels/infer">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/tidymodels/infer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@simonpcouch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @kellieotto
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/tidymodels/infer">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/tidymodels/infer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@simonpcouch) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by kellieotto** [comment]
@csoneson @simonpcouch: I've gone through the review checklist and just left two issues pertaining to functionality documentation, https://github.com/tidymodels/infer/issues/415 and https://github.com/tidymodels/infer/issues/416. I'll take another look when those are resolved.

**Comment by csoneson** [comment]
Thank you @kellieotto!

**Comment by simonpcouch** [comment]
Thank you @kellieotto! These are really helpful. Getting started on your feedback this morning.

**Comment by simonpcouch** [comment]
Okay, addressed in tidymodels/infer#418 and tidymodels/infer#417, respectively. Thanks again!

**Comment by kellieotto** [comment]
Looks great! I recommend this package be accepted.

**Comment by prdm0** [comment]
Dear @csoneson and @simonpcouch, at issue [#420](https://github.com/tidymodels/infer/issues/420) I leave my review for the paper. Beforehand I accept the paper, but I would be happy to see at least a prototype of my suggestion implemented. Best regards.

**Comment by simonpcouch** [comment]
Just left a reply to your issue, @prdm0! Thank you for your review.

**Comment by prdm0** [comment]
Dear @simonpcouch , thanks for your reply. I've added a counterargument that is actually a hint of a glimpse of future improvement. Finally, @csoneson , I recommend this package be accepted.

**Comment by csoneson** [comment]
Thanks @prdm0 for your thoughtful review!

@simonpcouch - as the reviewers both recommend accepting the submission, I will take a quick look as well and get back to you shortly with the next steps.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03661/joss.03661/10.21105.joss.03661.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03661/joss.03661/10.21105.joss.03661.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/00224065.2020.1848366 is OK
- 10.1080/10691898.2020.1730734 is OK
- 10.1080/10691898.2020.1804497 is OK
- 10.1080/10986065.2021.1922856 is OK
- 10.1080/26939169.2021.1920866 is OK
- 10.1089/cell.2020.0078 is OK
- 10.1002/etc.4978 is OK
- 10.1016/j.bbrc.2021.03.129 is OK
- 10.21105/joss.01686 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
👋🏻 @simonpcouch - I went through the submission and it looks good to me! Only a couple of things related to the references:

* There's a missing space between Modern and Dive in Ismay & Kim (2019)
* Could you provide more info/a link for Downey (2016)?
* I'd recommend adding references for the packages mentioned in the "Comparison to other packages" section

Could you fix these and ask whedon to generate a new proof (with @whedon generate pdf)?

The next steps would then be to:
- [ ] Make a tagged release of the software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service
- [ ] Check that the archival deposit (e.g., in Zenodo) has the correct metadata. In particular, the title and author list should be identical to those of the paper. You can also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by simonpcouch** [comment]
Thank you, @csoneson! I've made each of the changes you've suggested, with one exception: the authors of the book do indeed spell ModernDive [without a space](https://moderndive.com/).

I just reached out to the admins of the tidymodels GitHub org to enable Zenodo's access to `tidymodels/infer`. I'll drop a note here once we've made it through each of the steps you've listed to generate an archive + DOI!

**Comment by simonpcouch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3661 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `initialize': No such file or directory @ rb_sysopen - 8b99d8036efb903b37a7fd2c/figs/paper/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:66:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by simonpcouch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03661/joss.03661/10.21105.joss.03661.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03661/joss.03661/10.21105.joss.03661.pdf) :page_facing_up: :point_left:

**Comment by simonpcouch** [comment]
Okay, the DOI should be good to go! The DOI of the archived version, with correct metadata, is here: 10.5281/zenodo.5504495

**Comment by simonpcouch** [comment]
Ah, and the version tag is `v1.0.1`.

**Comment by csoneson** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.5504495 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5504495" target="_blank">10.5281/zenodo.5504495</a> is the archive.

**Comment by csoneson** [comment]
Great, thanks @simonpcouch! Just one final tiny detail...could you please case protect the final "R" in the title of Pruim et al (so it shows up as 'R' instead of 'r')? Then I'll pass the submission on for the final steps.

**Comment by simonpcouch** [comment]
Thank you, @csoneson! Just made that edit—your attention to detail is much appreciated.

**Comment by simonpcouch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03661/joss.03661/10.21105.joss.03661.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03661/joss.03661/10.21105.joss.03661.pdf) :page_facing_up: :point_left:

**Comment by csoneson** [comment]
Perfect - I'm going to hand this over now to the associate EiC on rotation for the final steps.

**Comment by csoneson** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/00224065.2020.1848366 is OK
- 10.1080/10691898.2020.1730734 is OK
- 10.1080/10691898.2020.1804497 is OK
- 10.1080/10986065.2021.1922856 is OK
- 10.1080/26939169.2021.1920866 is OK
- 10.1089/cell.2020.0078 is OK
- 10.1002/etc.4978 is OK
- 10.1016/j.bbrc.2021.03.129 is OK
- 10.21105/joss.01686 is OK
- 10.21105/joss.03236 is OK
- 10.21105/joss.02445 is OK

MISSING DOIs

- 10.32614/rj-2017-024 may be a valid DOI for title: The mosaic Package: Helping Students to ‘Think with Data’ Using R

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2587

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2587, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by simonpcouch** [comment]
Ah, that new flag for the missing `mosaic` DOI is correct. Just fixed!

**Comment by simonpcouch** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/00224065.2020.1848366 is OK
- 10.1080/10691898.2020.1730734 is OK
- 10.1080/10691898.2020.1804497 is OK
- 10.1080/10986065.2021.1922856 is OK
- 10.1080/26939169.2021.1920866 is OK
- 10.1089/cell.2020.0078 is OK
- 10.1002/etc.4978 is OK
- 10.1016/j.bbrc.2021.03.129 is OK
- 10.21105/joss.01686 is OK
- 10.32614/RJ-2017-024 is OK
- 10.21105/joss.03236 is OK
- 10.21105/joss.02445 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by simonpcouch** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03661/joss.03661/10.21105.joss.03661.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03661/joss.03661/10.21105.joss.03661.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1438610557687541763) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2588
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03661](https://doi.org/10.21105/joss.03661)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by Kevin-Mattheus-Moerman** [comment]
@simonpcouch congratulations on getting this work published in JOSS

@csoneson, thanks for editing! 

@prdm0, @kellieotto thanks a lot for your help reviewing this work!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03661/status.svg)](https://doi.org/10.21105/joss.03661)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03661">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03661/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03661/status.svg
   :target: https://doi.org/10.21105/joss.03661
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03661/status.svg)](https://doi.org/10.21105/joss.03661)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by simonpcouch** [comment]
Thank you, all!🦋
