### ISSUE TITLE
[PRE REVIEW]: AuDoLab: Automatic document labelling and classification for extremely unbalanced data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3663]
**Submitting author:** @ArneTillmann (<a href="http://orcid.org/0000-0002-2761-4518">Arne Matthias Tillmann</a>)
**Repository:** <a href="https://github.com/ArneTillmann/AuDoLab" target ="_blank">https://github.com/ArneTillmann/AuDoLab</a>
**Version:** v1.0.7
**Editor:** @arfon
**Reviewers:** @linuxscout
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ac8cf139139dbe55e00e7cc820459cee/status.svg)](https://joss.theoj.org/papers/ac8cf139139dbe55e00e7cc820459cee)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ac8cf139139dbe55e00e7cc820459cee"><img src="https://joss.theoj.org/papers/ac8cf139139dbe55e00e7cc820459cee/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ac8cf139139dbe55e00e7cc820459cee/status.svg)](https://joss.theoj.org/papers/ac8cf139139dbe55e00e7cc820459cee)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ArneTillmann. **Currently, there isn't an JOSS editor assigned** to your paper.

@ArneTillmann if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by ArneTillmann** [comment]
👋 @danielskatz, 
 
> 👋 @ArneTillmann - Your paper header includes AAS info. Is this associated with a AAS paper? If not, please remove that part of the paper source.
> 
> In addition, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references` to check again, and the command `@whedon generate pdf` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

Ofc I will make those changes to the paper asap.

Thank you very much

**Comment by ArneTillmann** [comment]
Hi @danielskatz and @galessiorob,
our suggenstions for potential reviewers are:
linuxscout
sara-02
trallard
aozorahime
Please let us know and we are happy to suggest further potential reviewers.
Thank you very much

**Comment by ArneTillmann** [comment]
@danielskatz 
regarding the DOIs I will take out the flagged once. I couldn't find any other.

**Comment by arfon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
:wave: @linuxscout @pmyteh @cmaimone – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is [_AuDoLab: Automatic document labelling and1 classification for extremely unbalanced data_](https://github.com/ArneTillmann/AuDoLab).

**Comment by arfon** [comment]
:wave: @ArneTillmann I will be the editor for this paper. Thanks so much for your suggestions for reviewers!

While we wait to hear back from possible reviewers could you merge this PR with a few minor changes to your paper here: https://github.com/ArneTillmann/AuDoLab/pull/31

**Comment by ArneTillmann** [comment]
@arfon Thank you for editing our paper. I merged the changes. 
I am looking foward to the reviews.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03663/joss.03663/10.21105.joss.03663.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03663/joss.03663/10.21105.joss.03663.pdf) :page_facing_up: :point_left:

**Comment by cmaimone** [comment]
I have another review that I haven't started yet, and another one still pending the other reviewer's completion. So I can't take this on at the moment

**Comment by pmyteh** [comment]
I'm afraid I'm in the same place: one JOSS review just completed, a second one embarrassingly outstanding and two new requests! So I must regretfully decline.

**Comment by linuxscout** [comment]
Salam,
I'm in, I accept to review this paper.

**Comment by arfon** [comment]
> Salam,
> I'm in, I accept to review this paper.

:zap: thanks @linuxscout! I'll go ahead and add you here but won't open the actual review until I've found a second reviewer.

@cmaimone @pmyteh – thanks for the responses, and apologies for asking you to review. I didn't realize you were already working on reviews for us ✨

**Comment by arfon** [comment]
@whedon add @linuxscout as reviewer

**Comment by whedon** [comment]
OK, @linuxscout is now a reviewer

**Comment by ArneTillmann** [comment]
Hi @linuxscout 
thanks for reviewing our work.
do you have a suggestion for a second reviewer?

**Comment by arfon** [comment]
:wave: @mbod @sptennak @esadr – would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is [_AuDoLab: Automatic document labelling and1 classification for extremely unbalanced data_](https://github.com/ArneTillmann/AuDoLab).

**Comment by ChrisW09** [comment]
@arfon To speed up the process a bit, we could also search for other potential reviewers and suggest them to you? thanks! chris

**Comment by arfon** [comment]
> @arfon To speed up the process a bit, we could also search for other potential reviewers and suggest them to you? thanks! chris

Certainly! I'm more than happy to hear your recommendations 😄 🙇

**Comment by ArneTillmann** [comment]
I went through the list and found these reviewers:
desilinguist, sjvrijn, alexhanna, ahurriyetoglu and UTH-Tuan

**Comment by ChrisW09** [comment]
@arfon Hopefully one of the reviewers that @ArneTillmann suggested will be curious to review our paper and also find the time... 😄

**Comment by arfon** [comment]
:wave: @UTH-Tuan – you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is [_AuDoLab: Automatic document labelling and1 classification for extremely unbalanced data_](https://github.com/ArneTillmann/AuDoLab).

**Comment by arfon** [comment]
> desilinguist, sjvrijn, alexhanna, ahurriyetoglu and UTH-Tuan

BTW, most of these folks are already actively reviewing a JOSS submission so I don't want to ask them to review a second paper at this time. Thanks for the suggestions though!

**Comment by ChrisW09** [comment]
@arfon This makes a lot of sense. Anyway, we also will search for further potential reviewers. Hopefully, we can start with the review soon. Thank you!

**Comment by linuxscout** [comment]
Salam,
Where is the review checklist?
Thanks

**Comment by ArneTillmann** [comment]
@arfon, how about pps121?

**Comment by ChrisW09** [comment]
@linuxscout Salam, we are still searching for a second reviewer before the review can start. Hopefully, we will find someone soon. Thank you for taking the time to review our paper!  @arfon Do you perhaps also have suggestions for further potential reviewers. thanks.

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3719.

**Comment by arfon** [comment]
I've gone ahead and started the review while I keep looking for a second reviewer. @linuxscout - please head over to #3719 where the review checklist is available for you to work through.

**Comment by arfon** [comment]
:wave: @pps121 – would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The submission under review here is [_AuDoLab: Automatic document labelling and1 classification for extremely unbalanced data_](https://github.com/ArneTillmann/AuDoLab).

**Comment by ChrisW09** [comment]
@arfon great, thank you! @linuxscout we are very much looking forward to the review!

**Comment by pps121** [comment]
Hi,

Yes I have started to review the paper. I will finish the review soon.
Thanks.

Parthapratimsaha

**Comment by ChrisW09** [comment]
@arfon @linuxscout We have a second reviewer with @pps121. @arfon Could you please add @pps121 to the review? thank you all!

**Comment by arfon** [comment]
> @arfon @linuxscout We have a second reviewer with @pps121. @arfon Could you please add @pps121 to the review? thank you all!

:+1: I added them over in #3719. @pps121 – please take a look at the review checklist you will find over there.
