### ISSUE TITLE
[PRE REVIEW]: ShUShER: private browser-based placement of sensitive genome samples on phylogenetic trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3664]
**Submitting author:** @amkram (<a href="http://orcid.org/0000-0003-3630-3209">Alexander Kramer</a>)
**Repository:** <a href="https://github.com/amkram/shusher" target ="_blank">https://github.com/amkram/shusher</a>
**Version:** v0.5.0
**Editor:** @mikldk
**Reviewers:** @kblin, @bede
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/03edfaa561a1cfbc53be7d98c8461cf3/status.svg)](https://joss.theoj.org/papers/03edfaa561a1cfbc53be7d98c8461cf3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/03edfaa561a1cfbc53be7d98c8461cf3"><img src="https://joss.theoj.org/papers/03edfaa561a1cfbc53be7d98c8461cf3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/03edfaa561a1cfbc53be7d98c8461cf3/status.svg)](https://joss.theoj.org/papers/03edfaa561a1cfbc53be7d98c8461cf3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @amkram. **Currently, there isn't an JOSS editor assigned** to your paper.

@amkram if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by mikldk** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mikldk

**Comment by mikldk** [comment]
@amkram - thank you for the submission.

Do you have any suggestions for reviewers ([here](https://bit.ly/joss-reviewers) is a list of potential reviewers)?

**Comment by amkram** [comment]
Hi @mikldk,

Here are some suggestions for potential reviewers: `kblin`, `bede`, `iimog`, `Gab0`

Thanks!

**Comment by mikldk** [comment]
@kblin, @bede: Would you be interested in reviewing this submission to [The Journal of Open Source Software](https://joss.theoj.org/)? Reviews are open and based on a checklist. The reviewer guidelines are available here: <https://joss.readthedocs.io/en/latest/reviewer_guidelines.html>. If you have any questions or concerns please let me know.

**Comment by bede** [comment]
Happy to review, as it seems is @kblin

**Comment by mikldk** [comment]
@whedon add @kblin as reviewer

**Comment by whedon** [comment]
OK, @kblin is now a reviewer

**Comment by mikldk** [comment]
@whedon add @bede as reviewer

**Comment by whedon** [comment]
OK, @bede is now a reviewer

**Comment by mikldk** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3677.
