### ISSUE TITLE
[PRE REVIEW]: cppTPSA/pyTPSA: a C++/Python package for truncated power series algebra

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3665]
**Submitting author:** @zhanghe9704 (<a href="http://orcid.org/0000-0001-7701-4118">He Zhang</a>)
**Repository:** https://github.com/zhanghe9704/tpsa
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @pibion
**Reviewers:** @dtabell, @chrisrogers1234
**Managing EiC:** Daniel S. Katz

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/1fa756415c650531cdfd292233b4cc8d/status.svg)](https://joss.theoj.org/papers/1fa756415c650531cdfd292233b4cc8d)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/1fa756415c650531cdfd292233b4cc8d"><img src="https://joss.theoj.org/papers/1fa756415c650531cdfd292233b4cc8d/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/1fa756415c650531cdfd292233b4cc8d/status.svg)](https://joss.theoj.org/papers/1fa756415c650531cdfd292233b4cc8d)
```

**Author instructions**

Thanks for submitting your paper to JOSS @zhanghe9704. **Currently, there isn't an JOSS editor assigned** to your paper.

@zhanghe9704 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by zhanghe9704** [comment]
@whedon check references

He Zhang
Computational Accelerator Physicist
Center for Advanced Science of Accelerators
Jefferson Lab
(O) 757-269-6657
www.hezhang.us

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1063/1.41975 is OK
- 10.1023/A:1024467732637 is OK
- 10.1016/j.nima.2011.01.053 is OK
- 10.1016/s1076-5670(08)x7018-1 is OK
- 10.2172/812598 is OK
- 10.1016/j.nima.2005.11.109 is OK
- 10.2514/6.2018-0398 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by zhanghe9704** [comment]
@whedon generate pdf

He Zhang
Computational Accelerator Physicist
Center for Advanced Science of Accelerators
Jefferson Lab
(O) 757-269-6657
www.hezhang.us

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03665/joss.03665/10.21105.joss.03665.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03665/joss.03665/10.21105.joss.03665.pdf) :page_facing_up: :point_left:

**Comment by meg-simula** [comment]
In light of the delay in response in just this editor request, I think I will have to pass on this one...

**Comment by kyleniemeyer** [comment]
@meg-simula if you are willing, I don't think checking in once a week or so is too slow of a response time, and fine with me!

**Comment by arfon** [comment]
> Thanks to Dr. Lingyun Yang for providing his tpsa code.

@zhanghe9704 - I noticed this comment in your README and wondered if you had considered including them as an author of your submission?

**Comment by arfon** [comment]
@whedon invite @pibion as editor

:wave: @pibion – would you be willing to edit this submission for JOSS?

**Comment by whedon** [comment]
@pibion has been invited to edit this submission.

**Comment by zhanghe9704** [comment]
Hello Dr. Smith,

Indeed I was hesitant about whether to include Lingyun as an author. The
reason that I didn't are (1) Lingyun's code was included in the previous
versions of MAD-X so it has been published somewhere else as part of the
MAD-X; and (2) except for the two files used in the cppTPSA repository He
has not been involved in the work of the two repositories of the paper,
although I did contact him and get his permission before I put the codes on
GitHub.

If you think it's better to include him as an author, I can contact him.

Thanks and best regards,

He Zhang
Computational Accelerator Physicist
Center for Advanced Science of Accelerators
Jefferson Lab
(O) 757-269-6657
www.hezhang.us

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by Kevin-Mattheus-Moerman** [comment]
@meg-simula if you are able to it would be great if you could help with this submission. Let us know if you can or elaborate on your comment above :point_up:.  No worries if you cannot. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon sorry I see you just invited @pibion also. For some reason I missed that, I think my window here had not been refreshed yet. Well hopefully either @pibion or @meg-simula can handle this submission. Apologies for the confusion.

**Comment by meg-simula** [comment]
Not available for this one, my apologies.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @pibion as editor

**Comment by whedon** [comment]
@pibion has been invited to edit this submission.

**Comment by pibion** [comment]
Hi all, I'm at limited bandwidth for the next week and a half.  @zhanghe9704 do you have any recommended reviewers for this submission?  If you do we can get started with invitations to them.

**Comment by zhanghe9704** [comment]
Hello,

When I submitted the paper, I looked through the reviewer list. To speak
frankly, I don't know who is familiar with this topic of TPSA/DA. Outside
the list, I can think of a few persons.

Axel Huelb at Lawrence Berkeley National Laboratory,
https://github.com/ax3l
Stephen Coleman at Radiasoft, https://github.com/sjcrs

The above two are experts in computational particle beam dynamics and
accelerator modeling.

Alex Wittig at  the University of Southampton, https://github.com/abgandar

Dr. Wittig is an expert on TPSA/DA. He has contributed codes to COSY
Infinity and DACE.  We had worked in the same group for about five years as
graduate students from 2006 to 2011.

Best,

He Zhang
Computational Accelerator Physicist
Center for Advanced Science of Accelerators
Jefferson Lab
(O) 757-269-6657
www.hezhang.us

**Comment by arfon** [comment]
> Hi all, I'm at limited bandwidth for the next week and a half. @zhanghe9704 do you have any recommended reviewers for this submission? If you do we can get started with invitations to them.
 
Sounds like you're OK to take this on, albeit with a short delay. As such, I'm going to go ahead and assign this one to you, thanks!

**Comment by arfon** [comment]
@whedon assign @pibion as editor

**Comment by whedon** [comment]
OK, the editor is @pibion

**Comment by sjcrs** [comment]
I'd like to help, but I think I have a COI - my company works with He Zhang's JSPEC code, and have publications in progress that may involve him as an author (He, I'll be sending you an email about that soon).

**Comment by pibion** [comment]
@sjcrs no worries, that's very helpful, thank you!

**Comment by zhanghe9704** [comment]
Happy new year to everyone!
Just want to follow up on the review progress of this submission. Is there
anything I could/should do to help? Thanks.

Best regards,

He Zhang
Computational Accelerator Physicist
Center for Advanced Science of Accelerators
Jefferson Lab
(O) 757-269-6657
www.hezhang.us


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ax3l** [comment]
Hi, I am sorry that I fully missed the ping earlier in the thread. I have a big backlog on GitHub notifications (about 400), I am sorry for that.

I pinged Robert Ryne and David Sagan on your request, but don't know their schedules. I also asked other people on our team if they can help out.

With the topic of the submission, I might be able to do the technical review but would have to read into the domain science part (I am a Laser-Plasma accelerator person by training).

**Comment by pibion** [comment]
@ax3l thank you for responding!  If @zhanghe9704 could comment here - would it be useful to have someone do the technical review, somewhat separate from the domain science?

That could be nice, as that could potentially reduce the work someone would need to do.

**Comment by pibion** [comment]
@zhanghe9704 apologies for the long delay - I'm sending emails again to find reviewers now that people are coming back from the holidays somewhat.

**Comment by zhanghe9704** [comment]
Hello,

Thanks for all your replies. I understand everyone is very busy especially
at the end of the year. I'm not in a hurry but I'm glad to see it starts to
move forward again.

I think a technical review will be very helpful. Actually, the current
version of the lib includes only the mathematical implementation of TPSA
and does not have any specific application in accelerator physics.

Best regards,

He Zhang
Computational Accelerator Physicist
Center for Advanced Science of Accelerators
Jefferson Lab
(O) 757-269-6657
www.hezhang.us

**Comment by pibion** [comment]
@zhanghe9704 thanks for this input!  @ax3l it sounds like you'd be valuable as a reviewer if you're available.  Please let me know if you think this is something you would like to take on.

**Comment by zhanghe9704** [comment]
Good morning,
Just want to ask if there is any update in this review. Thanks.

He Zhang

**Comment by zhanghe9704** [comment]
Hello,

Could anyone give me some update on this review? Thanks a lot!
Have a good weekend!

He

**Comment by pibion** [comment]
@zhanghe9704 apologies for the extremely slow start.  I've been having a hard time finding reviewers and am increasing my emailing rate to 15 potential editors per week.

One of the ways I find people to email is through related papers - so if you could refer me to papers that are related to this work that would be helpful!

**Comment by pibion** [comment]
@ax3l would you be interested and able to be a reviewer for this paper?  Your technical perspective would be a useful one!

**Comment by zhanghe9704** [comment]
Here is a paper on the tpsa package used in MAD-X:

https://cds.cern.ch/record/2141771/files/mopje039.pdf

He

**Comment by pibion** [comment]
@zhanghe9704 just wanted to let you know I'm still looking for reviewers.  Once we find one person we can start the review.  Do you have any more relevant papers you could recommend?

**Comment by pibion** [comment]
@zhanghe9704 additional thoughts on how to recruit folks would also be welcome.  In some cases I've had success asking people to ask their grad students if reviewing is something they would like to do.  My impression is that most of the people I've been contacting are staff scientists and don't have students.

I've found a few university programs but haven't heard back.  If you know of anyone with grad students that might be helpful.

**Comment by pibion** [comment]
@jbengsston would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by zhanghe9704** [comment]
Hello,

Professor Yue Hao at Michigan State University may be able to help. His
information can be found here: https://pa.msu.edu/profile/haoy/

Best,
He

**Comment by zhanghe9704** [comment]
Hello,

Just want to know if there's any progress? Thanks. Have a nice day!

He Zhang
Computational Accelerator Physicist
Center for Advanced Science of Accelerators
Jefferson Lab
(O) 757-269-6657
www.hezhang.us

**Comment by pibion** [comment]
@zhanghe9704 apologies for the delayed response - it's been a busy week.  The current update is: still trying to find reviewers.  I'm starting to think I need to visit a few places and lurk in the hallways.

I'll say a little more about the issues I'm running into in case you have any thoughts.  A few people have expressed interest, but don't feel like they're expert enough in this particular area to review.  The department heads/group leads I've contacted haven't responded - my hope was that they might know of enthusiastic students or postdocs who might be interested and have time.

**Comment by zhanghe9704** [comment]
Hello  @pibion,

Thanks for your reply. Have you contacted Prof. Yue Hao ***@***.***)
at Michigan State University? He may be able to help find a reviewer.

Dr. Ji Qiang ***@***.***) at Lawrence Berkeley National Lab may also be
able to help.

Another idea is to contact the developers or users of the DACE library:
https://github.com/dacelib/dace. I  think they should know about TA/TPSA.
COI: You may find Alex Wittig as the main developer of DACE. We graduated
from the same group with the same Ph.D. adviser. We actually sit in the
same office for about six years.

Best regards,
He Zhang
Computational Accelerator Physicist
Center for Advanced Science of Accelerators
Jefferson Lab
(O) 757-269-6657
www.hezhang.us

**Comment by sjcrs** [comment]
My colleague Dan Abell @dtabell is experienced with TPSA and would be willing to review the article

**Comment by pibion** [comment]
@sjcrs thank you!

**Comment by pibion** [comment]
@dtabell, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html.

Please let me know if you have any questions, I'm happy to communicate in whatever way works best for you - just let me know!

**Comment by dtabell** [comment]
@pibion  Yes. I am willing to review this submission. I see the paper has languished for lack of a reviewer. I will endeavor to have this done before the end of the month. Will that suit?

**Comment by pibion** [comment]
@editorialbot add @dtabell as reviewer

**Comment by pibion** [comment]
@dtabell end of month is a great time scale, thank you for volunteering as a reviewer!

@arfon I would like to start this review now even though we still need to add a second reviewer - this would let us take advantage of @dtabell 's current availability.  What do you think?

**Comment by arfon** [comment]
> @arfon I would like to start this review now even though we still need to add a second reviewer - this would let us take advantage of @dtabell 's current availability. What do you think?

Sorry I missed this. Yes, I agree you should move this forward while looking for another reviewer.

**Comment by pibion** [comment]
@arfon thank you!

**Comment by pibion** [comment]
@dtabell are you still available to review?  If so I'll start the review now!

**Comment by arfon** [comment]
@pibion – it looks like you might need to find new reviewers here. This might be a good source of candidates: https://github.com/topics/power-series

**Comment by arfon** [comment]
:wave: @pibion – this submission is still waiting to go out for review. How are you getting on finding a second reviewer?

**Comment by zhanghe9704** [comment]
Hello,

Just want to ask if there's any updates and if there's anything I can help
with.

Best regards,
He Zhang

**Comment by pibion** [comment]
@zhanghe9704 I believe I've found a second reviewer, checking in with him on when he can start!

**Comment by pibion** [comment]
@editorialbot assign @chrisrogers1234 as reviewer

**Comment by pibion** [comment]
@editorialbot commands

**Comment by pibion** [comment]
@editorialbot add @chrisrogers1234 as reviewer

**Comment by pibion** [comment]
@chrisrogers1234 welcome!  I'm going to go ahead and start this review.  We'll be joined by a second reviewer shortly, but we don't need to wait to move forward.

**Comment by pibion** [comment]
@editorialbot start review

**Comment by arfon** [comment]
@editorialbot generate pdf
