### ISSUE TITLE
Reviewer

### ISSUE THREAD

**Issue by AnsleyManke** [openjournals/joss-reviews#367]
I am willing to be a reviewer

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
Hi @AnsleyManke - please fill in the form here: http://joss.theoj.org/reviewer-signup.html
