### ISSUE TITLE
[PRE REVIEW]: GemGIS - Spatial Data Processing for Geomodeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3670]
**Submitting author:** @AlexanderJuestel (<a href="http://orcid.org/0000-0003-0980-7479">Alexander Jüstel</a>)
**Repository:** <a href="https://github.com/cgre-aachen/gemgis" target ="_blank">https://github.com/cgre-aachen/gemgis</a>
**Version:** v1.0.0
**Editor:** @crvernon
**Reviewers:** @omshinde, @kanishkan91
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/5855a6fc36e3a33c4014b3afa535b348/status.svg)](https://joss.theoj.org/papers/5855a6fc36e3a33c4014b3afa535b348)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/5855a6fc36e3a33c4014b3afa535b348"><img src="https://joss.theoj.org/papers/5855a6fc36e3a33c4014b3afa535b348/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/5855a6fc36e3a33c4014b3afa535b348/status.svg)](https://joss.theoj.org/papers/5855a6fc36e3a33c4014b3afa535b348)
```

**Author instructions**

Thanks for submitting your paper to JOSS @AlexanderJuestel. **Currently, there isn't an JOSS editor assigned** to your paper.

@AlexanderJuestel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1103

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4569086 is OK
- 10.5281/zenodo.4459137 is OK
- 10.21105/joss.01450 is OK
- 10.5281/zenodo.4572994 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5194/gmd-14-5063-2021 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3670 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.22 s (125.0 files/s, 134313.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          24           6936          10103          13180
Jupyter Notebook                79              0         124078           6520
Markdown                        10            346              0           1050
reStructuredText                24            614            413            677
YAML                             7             19             17            141
TeX                              1              9              0            109
XML                              6              0              0             73
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                           153           7936         134619          21785
-------------------------------------------------------------------------------


Statistical information for the repository 'a200906e55b060be3df63f14' was
gathered on 2021/08/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alexander Jüstel               186         49255          27160           80.07
AlexanderJuestel                50          1944            342            2.40
Arthur Endlein                   2           103              1            0.11
Florian Wellmann                 2            22             11            0.03
Miguel de la Varga               4            52              4            0.06
alexander.juestel               66         11476           5070           17.34

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alexander Jüstel          28000           56.8          7.7               12.45
AlexanderJuestel            457           23.5         11.5               14.44
Arthur Endlein               49           47.6         13.1               14.29
Miguel de la Varga           13           25.0         12.3                0.00
alexander.juestel          1700           14.8         13.1               13.71
```

**Comment by arfon** [comment]
:wave: @AlexanderJuestel, thanks for your submission to JOSS. It looks like the `paper.md` needs a little work. In particular, every author needs an affiliation, and ORCIDs can't be blank (but you can just remove the line if an author doesn't have one).

You can check the paper compiles after making changes with `@whedon generate pdf`

**Comment by crvernon** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @crvernon

**Comment by crvernon** [comment]
:wave: @AlexanderJuestel - I'll be your topic editor for this submission.

The first step in this pre-review will be to see to the comment above about getting the paper in a format that we can compile. 
 Next we can find at least 2 reviewers and get the review started. If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this list of people have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).  Thanks!

**Comment by crvernon** [comment]
Also, I noticed that `Miguel de la Varga` has made commits to your repository.  Is there a reason that they are not included in the author list?

**Comment by AlexanderJuestel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03670/joss.03670/10.21105.joss.03670.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03670/joss.03670/10.21105.joss.03670.pdf) :page_facing_up: :point_left:

**Comment by AlexanderJuestel** [comment]
@crvernon, thanks for being the topic editor. The changes suggested by @arfon were implemented. The article is compiling now. I also added @leguark (Miguel de la Varga) as author, thanks for pointing that out. 

As reviewers, I would like to suggest **martinfleis** as he is the author of the GeoPandas package, which is extensively used in GemGIS, and **banesullivan** as we use his PyVista package as well.

**Comment by crvernon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4569086 is OK
- 10.5281/zenodo.4459137 is OK
- 10.21105/joss.01450 is OK
- 10.5281/zenodo.4572994 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.5194/gmd-14-5063-2021 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by crvernon** [comment]
:wave:   @martinfleis @banesullivan - Would either of you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by crvernon** [comment]
Thanks for getting back go us so quickly @martinfleis !

**Comment by crvernon** [comment]
:wave: @omshinde - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by omshinde** [comment]
Hi @crvernon 
Thanks for the mention. I would be happy to review the submission on "GemGIS - Spatial Data Processing for Geomodeling". Kindly assign me as a reviewer. Regards.

**Comment by crvernon** [comment]
Thanks @omshinde !  I'll add you.  Once we get one more reviewer to sign on, we will get things started.

**Comment by crvernon** [comment]
@whedon assign @omshinde as reviewer

**Comment by whedon** [comment]
OK, @omshinde is now a reviewer

**Comment by sgrieve** [comment]
@crvernon I'm afraid I don't have any capacity this month. Apologies!

**Comment by crvernon** [comment]
@sgrieve no problem.  Thanks for the response!

**Comment by crvernon** [comment]
:wave: @Scivision or @kbevers - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by kbevers** [comment]
Sorry, I won't be able to do a review at this time

**Comment by crvernon** [comment]
Thanks for your fast reply @kbevers !

**Comment by crvernon** [comment]
:wave: @Zac-HD or @hobu - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by Zac-HD** [comment]
Sorry, I'm swamped at the moment - new job next week *and* thesis review imminent 😅

**Comment by crvernon** [comment]
Thanks for the quick reply @Zac-HD and no problem!  Best wishes for your upcoming endeavors!

**Comment by hobu** [comment]
Sorry, I also don't have cycles for this. Looks interesting though!

**Comment by crvernon** [comment]
No problem @hobu - best wishes!

**Comment by crvernon** [comment]
:wave: @martibosch , @AndrewAnnex , or @evetion - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by AndrewAnnex** [comment]
@crvernon sorry it's a very busy time for me late in my PhD

**Comment by crvernon** [comment]
No problem @AndrewAnnex , best wishes!

**Comment by martibosch** [comment]
Hello @crvernon, thank you for considering me but I am afraid that I will have to decline your kind invitation since I am also very busy at the moment and I further have another JOSS review pending. Best,

Martí

**Comment by crvernon** [comment]
No problem @martibosch ! Thanks for your quick reply!

**Comment by crvernon** [comment]
@kanishkan91 - Would you be willing to review this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by kanishkan91** [comment]
@crvernon I can start the review on Monday and take two weeks from there. If this sounds good, sign me up!

**Comment by crvernon** [comment]
@whedon add @kanishkan91 as reviewer

**Comment by whedon** [comment]
OK, @kanishkan91 is now a reviewer

**Comment by crvernon** [comment]
Alright @omshinde @kanishkan91 @AlexanderJuestel - I am going to close this Pre-Review and kick off the full review which you should receive a notification for.  Thanks!

**Comment by crvernon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3709.
