### ISSUE TITLE
[PRE REVIEW]: AMAT: A Python package for rapid conceptual design of aerocapture and atmospheric Entry, Descent, and Landing (EDL) missions in a Jupyter environment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3681]
**Submitting author:** @athulpg007 (<a href="http://orcid.org/0000-0002-9326-3293">Athul Pradeepkumar Girija</a>)
**Repository:** <a href="https://github.com/athulpg007/AMAT" target ="_blank">https://github.com/athulpg007/AMAT</a>
**Version:** v2.1.8
**Editor:** @jbytecode
**Reviewers:** @astrojuanlu, @helgee
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229/status.svg)](https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229"><img src="https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229/status.svg)](https://joss.theoj.org/papers/57c18b7854b74d83e75250857716e229)
```

**Author instructions**

Thanks for submitting your paper to JOSS @athulpg007. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @mbobra.

@athulpg007 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@whedon check repository

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1142

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=5.92 s (32.4 files/s, 16718.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            75          11312             75          41553
JavaScript                      11           2144           2126           8152
Jupyter Notebook                63              0          14124           5419
Python                          18           1973           3746           3902
SVG                              1              0              0           2671
CSS                              4            164             34            641
TeX                              1             25              0            195
Markdown                         2             96              0            179
reStructuredText                14            138            144            167
DOS Batch                        1              8              1             26
make                             1              4              7              9
YAML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                           192          15864          20257          62917
-------------------------------------------------------------------------------


Statistical information for the repository '802b3327ffc8e347dc61b644' was
gathered on 2021/09/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Athul P. Girija                 30         46315          25145          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Athul P. Girija           29348           63.4          8.8               13.79
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03681/joss.03681/10.21105.joss.03681.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03681/joss.03681/10.21105.joss.03681.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @jbytecode as editor

Hi @jbytecode, could you edit this one? I realize the application may be a bit outside your wheelhouse, but the statistical side of things seems right. Thanks

**Comment by whedon** [comment]
@jbytecode has been invited to edit this submission.

**Comment by jbytecode** [comment]
@whedon assign me as editor

@kyleniemeyer of course. thank you!

**Comment by whedon** [comment]
OK, the editor is @jbytecode

**Comment by jbytecode** [comment]
@athulpg007 👋 Do you have any suggestions for potential reviewers?  If yes, please mention them here in this thread (without tagging them with an @ - we don't want to disturb them). In addition, this [list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) of people have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/AERO.2010.5447017 is OK
- 10.1109/AERO.2002.1035313 is OK
- 10.2514/6.2003-2172 is OK
- 10.2514/1.2589 is OK
- 10.2514/1.A34121 is OK
- 10.2514/1.A34056 is OK
- 10.2514/1.A34719 is OK
- 10.2514/1.A34529 is OK
- 10.2514/1.A33997 is OK
- 10.2514/6.2007-605 is OK
- 10.2514/1.A34703 is OK
- 10.2514/1.13095 is OK

MISSING DOIs

- 10.17226/13117 may be a valid DOI for title: Vision and Voyages for Planetary Science in the Decade 2013-2022

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
@athulpg007 could you please also correct the missing DOI issue as whedon reported above? (`10.17226/13117`)

**Comment by athulpg007** [comment]
@jbytecode suggested reviewers: Juanlu001, steo85it (close match of domains from the list)

updated missing DOI

**Comment by athulpg007** [comment]
Additional suggestion for reviewer: salbert21 (has domain experience in atmospheric entry and aerocapture)

**Comment by jbytecode** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/AERO.2010.5447017 is OK
- 10.1109/AERO.2002.1035313 is OK
- 10.17226/13117 is OK
- 10.2514/6.2003-2172 is OK
- 10.2514/1.2589 is OK
- 10.2514/1.A34121 is OK
- 10.2514/1.A34056 is OK
- 10.2514/1.A34719 is OK
- 10.2514/1.A34529 is OK
- 10.2514/1.A33997 is OK
- 10.2514/6.2007-605 is OK
- 10.2514/1.A34703 is OK
- 10.2514/1.13095 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment]
👋👋👋 @astrojuanlu  👋👋👋

👋👋👋 @steo85it  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_AMAT: A Python package for rapid conceptual design of aerocapture and atmospheric Entry, Descent, and Landing (EDL) missions in a Jupyter environment_". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3681).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by astrojuanlu** [comment]
Happy to review for JOSS again! 😃

**Comment by jbytecode** [comment]
@whedon add @astrojuanlu as reviewer

**Comment by whedon** [comment]
OK, @astrojuanlu is now a reviewer

**Comment by athulpg007** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/AERO.2010.5447017 is OK
- 10.1109/AERO.2002.1035313 is OK
- 10.17226/13117 is OK
- 10.2514/6.2003-2172 is OK
- 10.2514/1.2589 is OK
- 10.2514/1.A34121 is OK
- 10.2514/1.A34056 is OK
- 10.2514/1.A34719 is OK
- 10.2514/1.A34529 is OK
- 10.2514/1.A33997 is OK
- 10.2514/6.2007-605 is OK
- 10.2514/1.A34703 is OK
- 10.2514/1.13095 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by athulpg007** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03681/joss.03681/10.21105.joss.03681.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03681/joss.03681/10.21105.joss.03681.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment]
👋👋👋 @RobertRosca  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_AMAT: A Python package for rapid conceptual design of aerocapture and atmospheric Entry, Descent, and Landing (EDL) missions in a Jupyter environment_". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3681).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by athulpg007** [comment]
@jbytecode salbert21 is willing to be a reviewer if needed. If the editor wishes, please tag him. I could also review the list shared earlier suggest more reviewers, if needed. Let me know, thanks!

**Comment by jbytecode** [comment]
@athulpg007 just because we have invited someone else, it is convenient to wait a little bit to  get a response. salbert21 seems to be a relatively young researcher so you can prepare a suggestion sublist using the reviewer list if we fail to get a response later.

**Comment by athulpg007** [comment]
Sure, we will do that. Thanks!

**Comment by steo85it** [comment]
Hi! I won't be able to review the code at this time, sorry...

**Comment by jbytecode** [comment]
@steo85it thank you for informing us. hope we can work together in the future.

**Comment by steo85it** [comment]
Sure, with pleasure! Just a mix of bad timing and "not so well known" topic.

**Comment by jbytecode** [comment]
@athulpg007 do you have any other suggestions for potential reviewers? Of course, I can also search for a suitable reviewer, but if you have a suggestion, I would like to consider it.

**Comment by athulpg007** [comment]
@jbytecode Here is a list of additional suggestions for reviewers (from the list):
 -- helgee
 -- crbinz
 -- s-m-e

**Comment by jbytecode** [comment]
👋👋👋 @helgee  👋👋👋

Would you be willing to assist in reviewing this submission for **JOSS** (**Journal of Open Source Software**)?

JOSS publishes articles about open source research software. The submission I'd like you to review is titled: "_AMAT: A Python package for rapid conceptual design of aerocapture and atmospheric Entry, Descent, and Landing (EDL) missions in a Jupyter environment_". You can find more information at the top of this Github issue (https://github.com/openjournals/joss-reviews/issues/3681).

The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

**Comment by astrojuanlu** [comment]
Come to the dark side @helgee, we have cookies 🍪

**Comment by RobertRosca** [comment]
Hey! Oooh, this seems super interesting, I'm up for reviewing it but I already have https://github.com/openjournals/joss-reviews/issues/3641#issuecomment-914074505 waiting and haven't had a chance to look at it yet since I've been pretty busy.

I'll do my best to finish #3641 asap and if I manage to do it before somebody is found for this, then I'll accept.

**Comment by jbytecode** [comment]
Dear @RobertRosca, thank you for the response. Please follow this thread and let us know your status if we haven't been able to find a suitable reviewer yet.

**Comment by helgee** [comment]
Count me in 👍

**Comment by jbytecode** [comment]
@whedon add @helgee as reviewer

**Comment by whedon** [comment]
OK, @helgee is now a reviewer

**Comment by jbytecode** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3710.
