### ISSUE TITLE
[PRE REVIEW]: Development of a Java library for 3D Euclidean geometry

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3682]
**Submitting author:** @agdturner (<a href="http://orcid.org/0000-0002-6098-6313">Andy Turner</a>)
**Repository:** <a href="https://github.com/agdturner/agdt-java-vector3D" target ="_blank">https://github.com/agdturner/agdt-java-vector3D</a>
**Version:** v0.7
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/cd189fa38e3d5f8b691b181f31795926/status.svg)](https://joss.theoj.org/papers/cd189fa38e3d5f8b691b181f31795926)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/cd189fa38e3d5f8b691b181f31795926"><img src="https://joss.theoj.org/papers/cd189fa38e3d5f8b691b181f31795926/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/cd189fa38e3d5f8b691b181f31795926/status.svg)](https://joss.theoj.org/papers/cd189fa38e3d5f8b691b181f31795926)
```

**Author instructions**

Thanks for submitting your paper to JOSS @agdturner. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @hugoledoux.

@agdturner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1008

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (370.6 files/s, 130519.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                            29            704           4344           7375
Maven                            1              6             81            207
Markdown                         2             46              0            151
TeX                              1              3              0             32
JSON                             2              0              0             30
YAML                             1              3              0             30
XML                              1              0             12              6
-------------------------------------------------------------------------------
SUM:                            37            762           4437           7831
-------------------------------------------------------------------------------


Statistical information for the repository '80514befc19a3865c12fd175' was
gathered on 2021/09/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andy Turner                    130         28278          15855          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andy Turner               12423           43.9          7.4               35.08
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3682 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by kyleniemeyer** [comment]
Hi @agdturner, thanks for your submission to JOSS! Regarding the compilation error, can you uncomment the bibliography line in the header of the paper?

Also, just FYI, when you have multiple citations that should be included together (e.g., like "[1,2,3]"), the appropriate citation command would be `[@author1:2001; @author2:2001]`.

Also, can you please make explicit the open-source license via a `LICENSE` file in the repository?

Due to low editor availability in this area right now, I'm going to put this on our waitlist, and we will assign an editor when one becomes available.

**Comment by agdturner** [comment]
Thank you @kyleniemeyer for helping me fix the bibliography referencing.

I have added a LICENSE file as requested.

No worries if takes a while, hopefully someone will be interested before too long. I am continuing to develop the code as and when, so I'm hoping there will be improvements by the time anyone is available to review. Since I pushed the submit button I have added some functionality for rays and have been improving test coverage. I am assuming it is okay to amend the paper if I make significant progress worth reporting and that a later version of the code can be reviewed in due course.

Best wishes,

Andy

**Comment by agdturner** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03682/joss.03682/10.21105.joss.03682.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03682/joss.03682/10.21105.joss.03682.pdf) :page_facing_up: :point_left:

**Comment by agdturner** [comment]
I have looked through the reviewer list. These are the usernames of those that might be interested:
Rgcjk
dvberkel
neurons
fiveop
danehkar
MikeLydeamore
shah314
ali-ramadhan
jordanperr
bonh
DanielMyshkin
junliu2050
g4brielvs
benjaminbolling
nnadeau
motib

**Comment by agdturner** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by kyleniemeyer** [comment]
@agdturner not a problem to make changes, especially now while we are waiting for an editor to become available. 

Once the review starts, it would probably be best to hold off on making any major changes to the main branch/release version. Later, if you release a new major version of the software with substantial changes (e.g., significant new features), JOSS would consider reviewing that for a second publication.

**Comment by agdturner** [comment]
Hi @kyleniemeyer, I think I should make a major change from a left handed coordinate system to a right handed one. The choice is arbitrary, I made my choice based on intuition screens and graphs, and whilst I can argue the case for this, I now realise (thanks to this video https://youtu.be/BoHQtXpWG2Y), that it is normal in physics to use a right handed coordinate system and so I am likely to put off physicists if I persist with left handedness. This change to right handedness also fits better with what geographers typically use, as in a projected left handed coordinate system with x representing longitude (that increases to the West) and y representing latitude (that increases to the North), the z would come out from the plane, which is more normal in terms of considering heights as we typically measure how high or deep something is from sea level. I should have reflected more before changing things based on my intuition (I had originally began with a right handed coordinate system) and appreciated the rules of thumb in physics. Hopefully I will be in time to have turned everything around before reviewers are lined up (not only do I need to change the code, but also the paper to reflect this change). Sorry about this confusion. Best wishes, Andy

**Comment by kyleniemeyer** [comment]
@agdturner no problem! I'm going to label this submission as "paused" while you are working on those changes, just to indicate that we shouldn't proceed beyond finding the editor quite yet. Let us know in here when your work is done and we can move forward.

**Comment by danielskatz** [comment]
Hi @agdturner - Given that there's really been nothing done here yet on the JOSS side, and there is work needed on the side of the author, I'm going to mark this as withdrawn.

Please feel free to resubmit when you are ready.  (Also, it's nice to see you here :) )

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
