### ISSUE TITLE
[PRE REVIEW]: BioPsyKit: A Python package for the analysis of biopsychological data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3683]
**Submitting author:** @richrobe (<a href="http://orcid.org/0000-0003-0272-5403">Robert Richer</a>)
**Repository:** <a href="https://github.com/mad-lab-fau/BioPsyKit" target ="_blank">https://github.com/mad-lab-fau/BioPsyKit</a>
**Version:** 0.3.0
**Editor:** @osorensen
**Reviewers:** @zen-juen, @espenhgn
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4769dbce3a25db943d7e3a23578becd1/status.svg)](https://joss.theoj.org/papers/4769dbce3a25db943d7e3a23578becd1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4769dbce3a25db943d7e3a23578becd1"><img src="https://joss.theoj.org/papers/4769dbce3a25db943d7e3a23578becd1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4769dbce3a25db943d7e3a23578becd1/status.svg)](https://joss.theoj.org/papers/4769dbce3a25db943d7e3a23578becd1)
```

**Author instructions**

Thanks for submitting your paper to JOSS @richrobe. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @chartgerink.

@richrobe if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3683 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.37 s (389.5 files/s, 130272.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         109           6218          12893          20028
Jupyter Notebook                14              0           6325           1366
Markdown                         4            155             31            391
YAML                             4             21             10            123
TOML                             2              5              1             86
SVG                              2              0              0             42
DOS Batch                        1              8              1             26
reStructuredText                 6             20             23             25
make                             1              6              8             15
-------------------------------------------------------------------------------
SUM:                           143           6433          19292          22102
-------------------------------------------------------------------------------


Statistical information for the repository '7e0bd8828850a376e3328c09' was
gathered on 2021/09/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Janis Zenkner                    2          3107             24            3.14
Martin Ullrich                   2            13              7            0.02
Rebecca Lennartz                31          1045            849            1.90
Robert Richer                  688         64010          27168           91.38
Victoria Müller                 24          1733            589            2.33
danielkrauss2                   16           982            255            1.24

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Janis Zenkner              1541           49.6          1.9                5.00
Martin Ullrich               11           84.6          0.7                9.09
Rebecca Lennartz            963           92.2          1.5                3.01
Robert Richer             36310           56.7          4.2                8.53
Victoria Müller              37            2.1          8.2                5.41
danielkrauss2               277           28.2          3.1                7.94
```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03683/joss.03683/10.21105.joss.03683.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03683/joss.03683/10.21105.joss.03683.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @chartgerink as editor

Hi @chartgerink, can you edit this submission for us?

**Comment by whedon** [comment]
@chartgerink has been invited to edit this submission.

**Comment by chartgerink** [comment]
Sorry @kyleniemeyer, can't this time — have two papers pending and still getting the hang of this 😊

**Comment by richrobe** [comment]
Reviewer suggestions:
SachaEpskamp
DominiqueMakowski

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
Hello @richrobe, I'm the editor for this submission now. Thanks for suggesting potential reviewers.

**Comment by osorensen** [comment]
@SachaEpskamp @DominiqueMakowski would you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by DominiqueMakowski** [comment]
Thanks @osorensen for the invite, and hi @richrobe and @SachaEpskamp nice seeing y'all here ☺️ 

May I recommend my ECR colleague @zen-juen to officially take this review instead of me?

**Comment by osorensen** [comment]
> Thanks @osorensen for the invite, and hi @richrobe and @SachaEpskamp nice seeing y'all here ☺️
> 
> May I recommend my ECR colleague @zen-juen to officially take this review instead of me?

Thanks for the recommendation @DominiqueMakowski! 

@zen-juen, would you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by SachaEpskamp** [comment]
Sorry I am on leave and cannot do reviews at this point. I also don't really know Python..

**Comment by osorensen** [comment]
Thanks for your quick response @SachaEpskamp!

**Comment by osorensen** [comment]
@espenhgn @torbjone would any of you be interested in reviewing this submission to the Journal of Open Source Software? It seems to be within your areas of expertise.

**Comment by zen-juen** [comment]
Thanks for recommending @DominiqueMakowski! I will be happy to review this submission @osorensen

**Comment by torbjone** [comment]
Hi, thanks for the invitation, @osorensen, but sadly I have to decline, maybe next time :-)

**Comment by osorensen** [comment]
That's very fine @torbjone. Thanks for responding quickly!

**Comment by osorensen** [comment]
@whedon add @zen-juen as reviewer

**Comment by whedon** [comment]
OK, @zen-juen is now a reviewer

**Comment by espenhgn** [comment]
> @espenhgn @torbjone would any of you be interested in reviewing this submission to the Journal of Open Source Software? It seems to be within your areas of expertise.

Hi @osorensen, I think I can do this if you need another reviewer.

**Comment by osorensen** [comment]
Thanks @espenhgn, that would be great!

**Comment by osorensen** [comment]
@whedon add @espenhgn as reviewer

**Comment by whedon** [comment]
OK, @espenhgn is now a reviewer

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3702.
