### ISSUE TITLE
[PRE REVIEW]: ROCK: digital normalization of whole genome sequencing data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3684]
**Submitting author:** @alex2cris (<a href="http://orcid.org/0000-0002-8212-5215">alexis criscuolo</a>)
**Repository:** <a href="https://gitlab.pasteur.fr/vlegrand/ROCK" target ="_blank">https://gitlab.pasteur.fr/vlegrand/ROCK</a>
**Version:** v_1.9.4
**Editor:** @luizirber
**Reviewers:** @hiraksarkar
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/02122fbaa0ad80447b29eb7973e727e4/status.svg)](https://joss.theoj.org/papers/02122fbaa0ad80447b29eb7973e727e4)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/02122fbaa0ad80447b29eb7973e727e4"><img src="https://joss.theoj.org/papers/02122fbaa0ad80447b29eb7973e727e4/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/02122fbaa0ad80447b29eb7973e727e4/status.svg)](https://joss.theoj.org/papers/02122fbaa0ad80447b29eb7973e727e4)
```

**Author instructions**

Thanks for submitting your paper to JOSS @alex2cris. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @csoneson.

@alex2cris if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1929

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.ygeno.2013.07.011 is OK
- 10.12688/f1000research.6924.1 is OK
- 10.1016/j.jalgor.2003.12.001 is OK
- 10.1038/s41598-019-41502-9 is OK
- 10.3390/electronics8070779 is OK
- 10.1093/bioinformatics/btw832 is OK
- 10.1186/s12859-017-1724-7 is OK
- 10.1371/journal.pone.0101271 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (809.3 files/s, 255189.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Bourne Shell                     9            811           1638           7333
C++                             18            670            773           2647
m4                               2            108             22            976
C/C++ Header                    16            394            389            739
Markdown                         2             93              0            212
TeX                              1             10              0             91
make                             4             23              2             54
YAML                             1              3              0             25
XML                              1              0              0             15
-------------------------------------------------------------------------------
SUM:                            54           2112           2824          12092
-------------------------------------------------------------------------------


Statistical information for the repository '1a471d6c8eb31bcc79f8127b' was
gathered on 2021/09/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nicolas Joly                     7            36             16            0.23
Veronique Legrand              166         15790           6409           99.76
Véronique Legrand                1             1              1            0.01

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Veronique Legrand          5612           35.5         31.4               25.41
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03684/joss.03684/10.21105.joss.03684.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03684/joss.03684/10.21105.joss.03684.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @alex2cris, thanks for your submission to JOSS! Due to low editor availability in this area right now, I am putting this on our waitlist. We will assign an editor as soon as one becomes available.

**Comment by luizirber** [comment]
@kyleniemeyer I can edit this submission

**Comment by kyleniemeyer** [comment]
@whedon assign @luizirber as editor

Thanks @luizirber!

**Comment by whedon** [comment]
OK, the editor is @luizirber

**Comment by alex2cris** [comment]
@VeroniqueLegrand @tkergrohen the review of ROCK takes place in this issue

**Comment by luizirber** [comment]
> @VeroniqueLegrand @tkergrohen the review of ROCK takes place in this issue

not quite; this issue is the preparation for the review, which will be opened when we find reviewers (hopefully soon =])

**Comment by ctb** [comment]
I'm available!

**Comment by luizirber** [comment]
@whedon assign @ctb as reviewer

**Comment by whedon** [comment]
OK, @ctb is now a reviewer

**Comment by luizirber** [comment]
@whedon assign @hiraksarkar as reviewer

**Comment by whedon** [comment]
OK, @hiraksarkar is now a reviewer

**Comment by luizirber** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3790.

**Comment by luizirber** [comment]
Oh no, whedon dropped ctb as a reviewer, can this be fixed @kyleniemeyer ?

**Comment by kyleniemeyer** [comment]
(... @luizirber which you said, and I somehow missed. Need to finish my coffee... ☕ )
