### ISSUE TITLE
[PRE REVIEW]: Tagging Latency Estimator: A Standalone Software for Estimating Latency of Event-Related Potentials in P300-based Brain-Computer Interfaces

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3685]
**Submitting author:** @ (<a href="http://orcid.org/0000-0002-7515-0690">Grégoire CATTAN</a>)
**Repository:** <a href="https://gitlab.com/programgreg/tagginglatencyestimator" target ="_blank">https://gitlab.com/programgreg/tagginglatencyestimator</a>
**Version:** v0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/872b0e4ef9a1237f1996e02d88a724f6/status.svg)](https://joss.theoj.org/papers/872b0e4ef9a1237f1996e02d88a724f6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/872b0e4ef9a1237f1996e02d88a724f6"><img src="https://joss.theoj.org/papers/872b0e4ef9a1237f1996e02d88a724f6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/872b0e4ef9a1237f1996e02d88a724f6/status.svg)](https://joss.theoj.org/papers/872b0e4ef9a1237f1996e02d88a724f6)
```

**Author instructions**

Thanks for submitting your paper to JOSS @. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @emdupre.

@ if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 444

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (844.6 files/s, 69866.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C#                              20            223             30           1238
JSON                             4              0              0            512
TeX                              1             15              0            181
Unity-Prefab                     1              0              0            102
Markdown                         2             23              0             57
YAML                             1              1              0             17
-------------------------------------------------------------------------------
SUM:                            29            262             30           2107
-------------------------------------------------------------------------------


Statistical information for the repository '2f6665b2441f8ce8b3229e90' was
gathered on 2021/09/03.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03685/joss.03685/10.21105.joss.03685.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03685/joss.03685/10.21105.joss.03685.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
Desk rejecting as the author hasn't supplied a GitHub handle.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by gcattan** [comment]
Hi, 
Sorry. It was not clear to me what was a GitHub handle.
Please find my GitHub account here:

https://github.com/gcattan

... and also my GitLab where this repository belongs:

https://gitlab.com/programgreg
