### ISSUE TITLE
[PRE REVIEW]: RandomForestsGLS: An R package for Random Forests for dependent data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3686]
**Submitting author:** @ArkajyotiSaha (<a href="http://orcid.org/0000-0001-9671-8196">Arkajyoti Saha</a>)
**Repository:** <a href="https://github.com/ArkajyotiSaha/RandomForestsGLS" target ="_blank">https://github.com/ArkajyotiSaha/RandomForestsGLS</a>
**Version:** v0.1.2
**Editor:** @fabian-s
**Reviewers:** @mnwright, @pdwaggoner
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/8c02fcd364d7c57b0936715328dda548/status.svg)](https://joss.theoj.org/papers/8c02fcd364d7c57b0936715328dda548)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/8c02fcd364d7c57b0936715328dda548"><img src="https://joss.theoj.org/papers/8c02fcd364d7c57b0936715328dda548/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/8c02fcd364d7c57b0936715328dda548/status.svg)](https://joss.theoj.org/papers/8c02fcd364d7c57b0936715328dda548)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ArkajyotiSaha. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @osorensen.

@ArkajyotiSaha if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 2766

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (766.1 files/s, 112859.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              2            304             55            980
R                               11             92             42            547
Markdown                         2             77              0            141
Rmd                              1            102            143            137
TeX                              1             11              0            101
C                                1              4              4             20
C/C++ Header                     1             11             12             16
-------------------------------------------------------------------------------
SUM:                            19            601            256           1942
-------------------------------------------------------------------------------


Statistical information for the repository '9743ea41bbb4224771f8ad1a' was
gathered on 2021/09/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Arkajyoti Saha                   4          1837            431          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Arkajyoti Saha             1406           76.5          0.6                5.12
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/01621459.2015.1044091 is OK

MISSING DOIs

- 10.1080/01621459.2021.1950003 may be a valid DOI for title: Random forests for spatially dependent data
- 10.1007/bf00058655 may be a valid DOI for title: Bagging predictors
- 10.1007/978-3-030-56485-8_3 may be a valid DOI for title: Random forests
- 10.1080/10106049.2019.1595177 may be a valid DOI for title: Geographical random forests: a spatial extension of the random forest algorithm to address spatial heterogeneity in remote sensing and population modelling
- 10.1109/99.660313 may be a valid DOI for title: OpenMP: an industry standard API for shared-memory programming

INVALID DOIs

- https://doi.org/10.1016/j.najef.2018.06.013 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03686/joss.03686/10.21105.joss.03686.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03686/joss.03686/10.21105.joss.03686.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon invite @fabian-s as editor

Hi @fabian-s, could you edit this submission?

**Comment by whedon** [comment]
@fabian-s has been invited to edit this submission.

**Comment by kyleniemeyer** [comment]
Hi @ArkajyotiSaha, as we are identifying an editor for you submission, could you review and resolve the DOI issues in your article raised above?

**Comment by ArkajyotiSaha** [comment]
Hi @kyleniemeyer, I believe I have solved the raised issues. Please let me if any additional changes are required. Thanks!

**Comment by kyleniemeyer** [comment]
@whedon generate PDF

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03686/joss.03686/10.21105.joss.03686.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03686/joss.03686/10.21105.joss.03686.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/01621459.2021.1950003 is OK
- 10.1007/bf00058655 is OK
- 10.1023/A:1010933404324 is OK
-  10.7717/peerj.5518 is OK
- 10.1080/10106049.2019.1595177 is OK
- 10.1016/j.najef.2018.06.013 is OK
- 10.1080/01621459.2015.1044091 is OK
- 10.1109/99.660313 is OK
- 10.1201/9781315139470 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@ArkajyotiSaha - before this submission is sent out for review, could you please clarify exactly what this statement means, and which code this refers to (from the README)?

> Some code blocks are borrowed from the R packages: spNNGP: Spatial Regression Models for Large Datasets using Nearest Neighbor Gaussian Processes https://CRAN.R-project.org/package=spNNGP and randomForest: Breiman and Cutler's Random Forests for Classification and Regression https://CRAN.R-project.org/package=randomForest

Also, could you say more about what the current paper "Saha, Arkajyoti, Sumanta Basu, and Abhirup Datta. "Random forests for spatially dependent data." Journal of the American Statistical Association (2021): 1-19." discusses?

**Comment by fabian-s** [comment]
@whedon assign @fabian-s as editor

**Comment by whedon** [comment]
OK, the editor is @fabian-s

**Comment by ArkajyotiSaha** [comment]
@arfon I have made the changes in README (under Note) to discuss in details the parts of codes which were borrowed from both the packages under consideration. In the overview section of the README, I have also briefly discussed what does our paper "Saha, Arkajyoti, Sumanta Basu, and Abhirup Datta. "Random forests for spatially dependent data." Journal of the American Statistical Association (2021): 1-19." discuss and how does that relate to the package. Please let me know if any additional changes are required.

**Comment by arfon** [comment]
Thanks @ArkajyotiSaha. @fabian-s – please take a look at the authors note in the README [here](https://github.com/ArkajyotiSaha/RandomForestsGLS#note) about code reuse. Given the relatively small size of this submission, I believe that this submission may fall foul of our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

@fabian-s – let me know if you'd like help making this assessment.

**Comment by fabian-s** [comment]
after reviewing the code, I think I  have to agree with @arfon  's assessment.

**Comment by fabian-s** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by ArkajyotiSaha** [comment]
@fabian-s Attached herewith is a brief summary of the novelty of the code and the method that might be helpful in this review process. 

The package implements the RF-GLS algorithm (which is a novel algorithm proposed in "Saha, Arkajyoti, Sumanta Basu, and Abhirup Datta. "Random forests for spatially dependent data." Journal of the American Statistical Association (2021): 1-19.") in R which is a novel Random Forest for correlated data. This method incorporates the correlation structure of the data in regression tree partition and node representative determination by replacing the OLS cost function used in RF with a GLS cost function. Presently there is no package in R that explicitly accounts for a parsimonious modeling of the correlation structure and functional value (mean) estimation for new covariate values in correlated data. 

1. Since we use a regression tree, the basic tool and structure is similar to that of Breiman and Cutler's classic Random Forest implemented in `randomForest`. We use just the skeleton of regression trees and associate RF in `randomForest`, as that structure is identical across all regression trees. **The cost function implementation, node representative determination, bootstrapping for each of the regression trees, choice of acceptable splits are handled in a entirely different ways in these two packages and the respective codes in our package are built from scratch with a number of novel implementation optimizations, detailed in the software paper.**

2. Here we model the correlation structure with nearest neighbor Gaussian process (NNGP), which makes the proposed approach scalable. NNGP is implemented in R `spNNGP` in the context of linear models. Here, we use the structure of the code for correlation computation under NNGP, which is identical across all approaches using the NNGP structure. Using NNGP in the cost function used in `findBestSplit` leads to **clever implementation of serial cost function evaluation while searching through possible acceptable gaps, which are built from scratch as these are novel methods with optimized implementation techniques.**

I would be happy to provide with additional details on the novelties of the code and/or the method for the review process. Please let me know.

**Comment by fabian-s** [comment]
@ArkajyotiSaha thank you for the clarifications.
We're waiting until the end of this week for more feedback from the other editors before we decide whether to begin the review process.

**Comment by danielskatz** [comment]
The editors' scope discussion has found this work to be in scope.

**Comment by fabian-s** [comment]
@cole-brokamp would you be willing to review this implementation of random forests for dependent/spatial data for JOSS?

**Comment by fabian-s** [comment]
@whedon add @mnwright as reviewer

thank you marvin!

**Comment by whedon** [comment]
OK, @mnwright is now a reviewer

**Comment by cole-brokamp** [comment]
@fabian-s I'm currently tied up reviewing for some other journals.  Sorry to decline!

**Comment by fabian-s** [comment]
hi, @robohyun66 @njehazi 
would any of you be willing to review this submission for JOSS? 
We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by fabian-s** [comment]
@pdwaggoner @matloff
would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by pdwaggoner** [comment]
Hi @fabian-s - thanks for the invite. I'd be happy to review. I have already gotten into the paper. The package and paper are great. I look forward to submitting my review shortly along with some comments. Thanks!

**Comment by fabian-s** [comment]
thanks @pdwaggoner, that's great!

**Comment by fabian-s** [comment]
@whedon add @pdwaggoner as reviewer

**Comment by whedon** [comment]
OK, @pdwaggoner is now a reviewer

**Comment by fabian-s** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3780.
