### ISSUE TITLE
[PRE REVIEW]: slant: A Python package for identifying and quantifying bias in texts

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3687]
**Submitting author:** @cdcrabtree (<a href="http://orcid.org/0000-0001-5144-8671">Charles Crabtree</a>)
**Repository:** <a href="https://github.com/williamwmarx/slant" target ="_blank">https://github.com/williamwmarx/slant</a>
**Version:** v0.1.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b88c8cfba9d6738e9b5aa7ddc87593b9/status.svg)](https://joss.theoj.org/papers/b88c8cfba9d6738e9b5aa7ddc87593b9)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b88c8cfba9d6738e9b5aa7ddc87593b9"><img src="https://joss.theoj.org/papers/b88c8cfba9d6738e9b5aa7ddc87593b9/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b88c8cfba9d6738e9b5aa7ddc87593b9/status.svg)](https://joss.theoj.org/papers/b88c8cfba9d6738e9b5aa7ddc87593b9)
```

**Author instructions**

Thanks for submitting your paper to JOSS @cdcrabtree. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @lorenanicole.

@cdcrabtree if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 527

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (634.6 files/s, 56476.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           8            182            357            486
Markdown                         3             42              0            200
TeX                              1              2              0             27
TOML                             1              3              0             18
JSON                             1              1              0             16
SVG                              1              0              0              1
-------------------------------------------------------------------------------
SUM:                            15            230            357            748
-------------------------------------------------------------------------------


Statistical information for the repository '9b801d46abd9697ae7a28db1' was
gathered on 2021/09/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
wwm                              3          1133            108          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
wwm                        1025           90.5          0.0               10.44
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1017/pan.2021.16 may be a valid DOI for title: Placebo Selection in Survey Experiments: An Agnostic Approach

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03687/joss.03687/10.21105.joss.03687.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03687/joss.03687/10.21105.joss.03687.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi @cdcrabtree, thanks for your interest in JOSS. Due to the relatively small size of your software package, the editorial board is going to review your submission to see if it satisfies our requirement for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). We will get back to you hopefully within a week or two with our decision, or with any additional questions.

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
Thanks for your submission to JOSS @cdcrabtree. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
