### ISSUE TITLE
[PRE REVIEW]: electiondata: a Python package for consolidating, checking, analyzing, visualizing and exporting election results

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3688]
**Submitting author:** @sfsinger19103 (<a href="http://orcid.org/0000-0002-1373-9619">Stephanie Singer</a>)
**Repository:** <a href="https://github.com/ElectionDataAnalysis/electiondata" target ="_blank">https://github.com/ElectionDataAnalysis/electiondata</a>
**Version:** v2.0.0
**Editor:** @ajstewartlang
**Reviewers:** @vaneseltine, @andrewheiss
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/27e248fc1e46488384e884dc242aac80/status.svg)](https://joss.theoj.org/papers/27e248fc1e46488384e884dc242aac80)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/27e248fc1e46488384e884dc242aac80"><img src="https://joss.theoj.org/papers/27e248fc1e46488384e884dc242aac80/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/27e248fc1e46488384e884dc242aac80/status.svg)](https://joss.theoj.org/papers/27e248fc1e46488384e884dc242aac80)
```

**Author instructions**

Thanks for submitting your paper to JOSS @sfsinger19103. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @lorenanicole.

@sfsinger19103 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3688 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment]
@whedon generate pdf from branch joss-submission

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-submission. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03688/joss.03688/10.21105.joss.03688.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03688/joss.03688/10.21105.joss.03688.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon check repository

**Comment by kyleniemeyer** [comment]
@openjournals/dev any idea why whedon is stalling on the repository check?

**Comment by kyleniemeyer** [comment]
@whedon invite @ajstewartlang as editor

Hi @ajstewartlang, would you be interested in editing this submission for us?

**Comment by whedon** [comment]
@ajstewartlang has been invited to edit this submission.

**Comment by sfsinger19103** [comment]
zen-juen
peanutfun

hknd23


cjbarrie

vaneseltine

vinodkahuja

**Comment by arfon** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=64.99 s (8.2 files/s, 1150.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              2              0              2          38058
Python                          19           1385           3961          24655
INI                            504             84              0           5769
Markdown                         5            236              0            632
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                           531           1705           3963          69115
-------------------------------------------------------------------------------


Statistical information for the repository '160bf67000b12fdf17f4195d' was
gathered on 2021/09/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bryan Loy                       10           963             45            0.36
Eric Tsai                      383         30013          10090           14.22
Jon Wolgamott                   51          6517           5328            4.20
Nick Hershman                    5           485            126            0.22
Raghu                           15           340            169            0.18
Raghu Srungavarapu              17           848            109            0.34
Raghu-Srungavarapu               4           311              0            0.11
Stephanie Frank Sing             2            62            237            0.11
Stephanie Singer              1625        105358          73830           63.52
Todd Graham                     12          1320             25            0.48
ekmeyerson                      22           933             35            0.34
raghu-srungavarapu-b             2             6              1            0.00
sfsinger19103                  518         29534          15419           15.93
wonderbug2020                    2             3              1            0.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Eric Tsai                 10202           34.0          9.3                1.45
Raghu                        12            3.5         13.2               16.67
Raghu-Srungavarapu            1            0.3          8.4              100.00
Stephanie Singer          19778           18.8          2.9                6.20
sfsinger19103                 8            0.0         10.2                0.00
```

**Comment by ajstewartlang** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @ajstewartlang

**Comment by ajstewartlang** [comment]
@whedon assign @vaneseltine as reviewer

**Comment by whedon** [comment]
OK, @vaneseltine is now a reviewer

**Comment by ajstewartlang** [comment]
@whedon add @andrewheiss as reviewer

**Comment by whedon** [comment]
OK, @andrewheiss is now a reviewer

**Comment by ajstewartlang** [comment]
Many thanks @vaneseltine and @andrewheiss for agreeing to review this submission - it's very much appreciated - I'll open the review issue now...

**Comment by ajstewartlang** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3739.
