### ISSUE TITLE
[PRE REVIEW]: Nextclade: clade assignment, mutation calling and quality control for viral genomes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3691]
**Submitting author:** @rneher (<a href="http://orcid.org/0000-0003-2525-1407">Richard Neher</a>)
**Repository:** <a href="https://github.com/nextstrain/nextclade" target ="_blank">https://github.com/nextstrain/nextclade</a>
**Version:** v1.3.0
**Editor:** @kellyrowland
**Reviewers:** @kevinlibuit, @DavidNickle
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b0e8e7f231ddfc61616de6b56f32b79f/status.svg)](https://joss.theoj.org/papers/b0e8e7f231ddfc61616de6b56f32b79f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b0e8e7f231ddfc61616de6b56f32b79f"><img src="https://joss.theoj.org/papers/b0e8e7f231ddfc61616de6b56f32b79f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b0e8e7f231ddfc61616de6b56f32b79f/status.svg)](https://joss.theoj.org/papers/b0e8e7f231ddfc61616de6b56f32b79f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @rneher. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @will-rowe.

@rneher if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1366

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/0022-2836(81)90087-5 is OK
- 10.21105/joss.02906 is OK
- 10.1093/bioinformatics/bty407 is OK
- 10.1038/s41588-021-00862-7 is OK
- 10.1093/bioinformatics/bty191 is OK
- 10.1093/molbev/mst010 is OK
- 10.1038/s41564-021-00932-w is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03691/joss.03691/10.21105.joss.03691.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03691/joss.03691/10.21105.joss.03691.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=6.56 s (312.7 files/s, 84154.0 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code
---------------------------------------------------------------------------------------
JSON                                    40              0              0         145110
C++                                    671          23576          18754         122987
C/C++ Header                           501          26164          30133         110318
TypeScript                             341           3078            513          16037
Markdown                               143           4662              0          13575
Python                                  33           1984           3786           7857
CMake                                  120           1064           1230           5034
SVG                                     13              3              3           2076
Bourne Shell                            31            471            329           2004
YAML                                    40            255            134           1823
C                                        4            160            100           1300
Windows Module Definition               16            166            109           1114
make                                     9            193            143            800
Sass                                    13            165             19            757
JavaScript                              22            104             77            694
diff                                    17            121            437            398
XML                                      7              7             10            387
Dockerfile                               4             50             11            195
Bourne Again Shell                       1             20              8            165
Objective-C                              3             61             41            150
SWIG                                     1             21              3            142
Windows Resource File                    3             68             89            139
reStructuredText                         5            133            140            124
TeX                                      1             11              0            121
DOS Batch                                4             26             46             83
CSS                                      3             14              3             60
Bazel                                    2              5              0             44
PowerShell                               1             12              0             23
Meson                                    1              4              0             19
HTML                                     2              2              0             18
---------------------------------------------------------------------------------------
SUM:                                  2052          62600          56118         433554
---------------------------------------------------------------------------------------


Statistical information for the repository 'c0994c5a88584900827e007c' was
gathered on 2021/09/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Cornelius Roemer                 6           108              3            0.03
Richard Neher                   32           800            266            0.25
eharkins                         1             1              2            0.00
ivan-aksamentov                399        388631          41665           99.73

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Richard Neher                69            8.6          9.8               11.59
eharkins                      1          100.0          0.4                0.00
ivan-aksamentov          348419           89.7          3.5               17.08
```

**Comment by kyleniemeyer** [comment]
Hi @rneher, thanks for your interest in JOSS! Unfortunately, due to low editor availability in this area, I need to put your submission on our waitlist. Once an editor is able to handle this one, we'll get it assigned and moving forward.

**Comment by rneher** [comment]
Thanks, @kyleniemeyer. I can suggest a few reviewers if this helps:

pvanheus
kevinlibuit
EduanWilkinson

let me know if there is anything else I can do to help.

**Comment by arfon** [comment]
@whedon invite @kellyrowland as editor

:wave: @kellyrowland – would you be willing to take this submission on for us?

**Comment by whedon** [comment]
@kellyrowland has been invited to edit this submission.

**Comment by kellyrowland** [comment]
Yep, I can take this on.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @kellyrowland as editor

**Comment by whedon** [comment]
OK, the editor is @kellyrowland

**Comment by kellyrowland** [comment]
Thanks for the reviewer suggestions, @rneher !

Hello @pvanheus @kevinlibuit @EduanWilkinson 👋 - would you be interested in and available to review this paper for JOSS? We require a minimum of two reviewers per paper.

**Comment by kevinlibuit** [comment]
Kelly,

Yes! Would be more than happy to contribute to the review of this
manuscript.

Best,

Kevin

**Comment by kellyrowland** [comment]
Great! Thanks very much.

**Comment by kellyrowland** [comment]
@whedon add @kevinlibuit as reviewer

**Comment by whedon** [comment]
OK, @kevinlibuit is now a reviewer

**Comment by kellyrowland** [comment]
Hi @dcnickle @Maghnuso - would either of you be willing and available to review this submission to JOSS? I see that you were the reviewers on the paper for the Augur software package, which is used and referenced here.

**Comment by DavidNickle** [comment]
Hi Kelly,

Yes - I can review this.

David

**Comment by kellyrowland** [comment]
Great, thanks so much!

**Comment by kellyrowland** [comment]
@whedon add @dcnickle as reviewer

**Comment by whedon** [comment]
OK, @dcnickle is now a reviewer

**Comment by kellyrowland** [comment]
@DavidNickle - I just caught that your account here in this issue is different than the one I originally pinged. Do you have a preference for which to use as the reviewer assignment?

**Comment by DavidNickle** [comment]
Yes - that was an error. Let’s stick with ***@***.*** ***@***.***>.

Thank you,

David

**Comment by kellyrowland** [comment]
@DavidNickle can you please specify which Github handle to use, by name? Your above response is showing as the obscured address

> \*\*\*@\*\*\*.\*\*\* \*\*\*@\*\*\*.\*\*\*>.

and I can't tell which account to use.

**Comment by kellyrowland** [comment]
Yep, I can see the email address, thanks. The JOSS workflow bot expects Github handles directly as input, however - is either account okay to reach you at that address? I don't mean to belabor the question, just trying to make sure everything's lined up correctly here before we move things over to the review issue.

**Comment by DavidNickle** [comment]
Yes either is fine.  I am currently working for a small biotech that uses Git Lab and I think I confused the system by logging in on the wrong account.  But both work.

Thanks,

David

**Comment by kellyrowland** [comment]
Thanks for the clarification!

**Comment by whedon** [comment]
OK, @dcnickle is no longer a reviewer

**Comment by kellyrowland** [comment]
@whedon add @dcnickle as reviewer

**Comment by kellyrowland** [comment]
@whedon remove @dcnickle as reviewer

**Comment by whedon** [comment]
OK, @dcnickle is no longer a reviewer

**Comment by kellyrowland** [comment]
@whedon add @DavidNickle as reviewer

**Comment by whedon** [comment]
OK, @DavidNickle is now a reviewer

**Comment by kellyrowland** [comment]
@whedon start review

**Comment by Maghnuso** [comment]
Hi Kelly,
Are you still looking for another reviewer? I’m on parental leave at the moment so I might pass on this one, but if you are in a bind, do let me know and I can probably fit it in. 
Best,
Maghnus

**Comment by kellyrowland** [comment]
Hi @Maghnuso - thanks for your reply! We are all set with two reviewers here, so please do take the time off with your growing family (congrats!).

**Comment by EduanWilkinson** [comment]
@kellyrowland I would be happy to help with the review process. 

Please advise with regards to how the GitHub review process works.

Regards,

**Comment by DavidNickle** [comment]
Hi Kelly,

I finished the review.  Not sure it is showing as done.  I could have done something wrong.

David

**Comment by kellyrowland** [comment]
Hi David,

I can see your post over in the review issue, thanks - I'll go ahead and mark the checkboxes off over in that issue.

**Comment by kellyrowland** [comment]
Hi @EduanWilkinson we can add you as a third reviewer over in the review issue, sure.

The workflow would go as follows:

In the review issue at https://github.com/openjournals/joss-reviews/issues/3773 , I would @ whedon, the JOSS bot, and have it add you as a reviewer on the paper. This will send you an invite to the repository, which you'll need to accept to proceed with the review process.

Once you've been added as a reviewer and accepted the repo invite, you'll be assigned to the Github issue, where you'll have a set of 20 checkboxes to work through. You can take a look at the checkboxes in the issue linked previously; each reviewer is asked to work through this same set of checkboxes to ensure software functionality and documentation and review the associated paper.

Any questions or feedback for the authors can be raised on the software repo or in the review issue; reviewers and authors are encouraged to iterate as needed to arrive at a software and paper state appropriate for publication in JOSS. Once all reviewers have completed their reviews, I'll have the authors release a tagged version of the software to go with the paper and then ping the JOSS editors-in-chief to finish out the publication.

Please let me know if you have any questions about the above and if you are interested in and able to carry out the review - we can add you as a third reviewer on the submission.

**Comment by EduanWilkinson** [comment]
@whedon I accept to review the paper. Could you add me as a reviewer please?

Eduan

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```
