### ISSUE TITLE
[PRE REVIEW]: UnlockNN: Uncertainty quantification for neural network models of chemical systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3692]
**Submitting author:** @a-ws-m (<a href="http://orcid.org/0000-0001-7525-1419">Alexander Moriarty</a>)
**Repository:** <a href="https://github.com/a-ws-m/unlockNN/" target ="_blank">https://github.com/a-ws-m/unlockNN/</a>
**Version:** v2.0.2
**Editor:** @osorensen
**Reviewers:** @TahiriNadia, @pmeier, @Het-Shah
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b00df538a159c4b6816ec24d4d1716fb/status.svg)](https://joss.theoj.org/papers/b00df538a159c4b6816ec24d4d1716fb)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b00df538a159c4b6816ec24d4d1716fb"><img src="https://joss.theoj.org/papers/b00df538a159c4b6816ec24d4d1716fb/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b00df538a159c4b6816ec24d4d1716fb/status.svg)](https://joss.theoj.org/papers/b00df538a159c4b6816ec24d4d1716fb)
```

**Author instructions**

Thanks for submitting your paper to JOSS @a-ws-m. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @rkurchin.

@a-ws-m if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 554

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (783.2 files/s, 75042.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          16            408            521           1165
Jupyter Notebook                 1              0            538            379
TeX                              1             16              0            227
Markdown                         4             42              0            159
YAML                             6             15             17            129
reStructuredText                 8             76             55            125
SVG                              1              1              1             53
DOS Batch                        1              8              1             26
INI                              1              2              1             22
JSON                             2              0              0             17
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            42            572           1141           2311
-------------------------------------------------------------------------------


Statistical information for the repository 'cbd31df85bc6df9ab94bd54e' was
gathered on 2021/09/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alex Moriarty                  184          6006           2821           52.15
a-ws-m                         155          3504           4595           47.85

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
a-ws-m                     2094           59.8          1.3                9.89
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-018-0337-2 is OK
- 10.1021/acs.chemmater.9b01294 is OK
- 10.1038/s41524-020-00406-3 is OK
- 10.1021/acs.jctc.7b00577 is OK
- 10.1557/mrc.2019.78 is OK
- 10.1038/s41524-017-0056-5 is OK
- 10.1038/s41524-019-0221-0 is OK
- 10.1063/1.5019779 is OK
- 10.1103/PhysRevLett.120.145301 is OK
- 10.1038/ncomms11241 is OK

MISSING DOIs

- 10.1088/2632-2153/ab7e1a may be a valid DOI for title: Methods for Comparing Uncertainty Quantifications for Material Property Predictions

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03692/joss.03692/10.21105.joss.03692.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03692/joss.03692/10.21105.joss.03692.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
Hi  @a-ws-m, thanks for your interest in JOSS! Unfortunately due to low editor availability in this area, I have to put your submission on our waitlist. We'll get it assigned and moving forward as soon as someone opens up to handle this.

In the meantime, could you take a look at that DOI issue in the article? Any reviewer suggestions could share would be much appreciated as well.

**Comment by a-ws-m** [comment]
Thanks @kyleniemeyer, I've fixed that DOI issue. One potential reviewer could be JaGeo (though she doesn't appear on the list; I'll have a look through that, too).

**Comment by osorensen** [comment]
@whedon assign @osorensen as editor

**Comment by whedon** [comment]
OK, the editor is @osorensen

**Comment by osorensen** [comment]
@ftarlaci @TahiriNadia @JaGeo; would you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by JaGeo** [comment]
Thank you very much for inviting me. Just on Friday, I have accepted another review and I have also submitted one. This is a very interesting task but it might currently take quite long for me to complete it.

**Comment by osorensen** [comment]
That is understandable. Thanks for you quick response @JaGeo .

**Comment by TahiriNadia** [comment]
Thank you @osorensen. I am interested in reviewing the paper. As this is my first for this journal, would it be possible to give me the link for the directions (containing the evaluation grid)?

**Comment by osorensen** [comment]
Thanks @TahiriNadia! Yes, I will make sure you get the necessary instructions. Once we have another reviewer confirmed, I will start a review issue where on GitHub where the review will be conducted, and where I'll make sure you get the necessary instructions.

**Comment by osorensen** [comment]
@whedon add @TahiriNadia as reviewer

**Comment by whedon** [comment]
OK, @TahiriNadia is now a reviewer

**Comment by osorensen** [comment]
@FranciscoReveriano @pmeier @Het-Shah would any of you be interested in reviewing this submission to the Journal of Open Source Software?

**Comment by pmeier** [comment]
@osorensen Depends on what you are looking for. I have no experience with _variational Gaussian processes_ (VGPs), which seem to play a major part in the package. Willing to look into them though.

**Comment by osorensen** [comment]
@pmeier, thanks for responding so quickly. From your GitHub profile, you seem highly competent in software for machine learning, and I hence think you would be a very good reviewer for this submission. In the typical JOSS papers the underlying methodology should be described elsewhere and referenced, so the reviewers don't necessarily need to be experts on all those aspects.

If that sounds fine with you I'll add you as a reviewer.

**Comment by Het-Shah** [comment]
@osorensen Thank you for the request to review. I agree with @pmeier, I do not have experience with VGPs. I am willing to have a look through the work if a reviewer is still needed.

**Comment by TahiriNadia** [comment]
@osorensen Can you tell me how many days we have to revise the article? please.

**Comment by osorensen** [comment]
> @osorensen Can you tell me how many days we have to revise the article? please.

@TahiriNadia, I hope that you can starting with the review within 2-3 weeks, but we try to be flexible in these special times. It is very hard to say how long the review process will last. In JOSS reviews we typically let the submitting authors improve the software based on the reviewers' feedback, so it may be that you first do an initial review, and then come back in a month or so to evaluate whether the software has been approved according to your suggestions.

**Comment by osorensen** [comment]
@whedon add @pmeier as reviewer

**Comment by whedon** [comment]
OK, @pmeier is now a reviewer

**Comment by osorensen** [comment]
@whedon add @Het-Shah as reviewer

**Comment by whedon** [comment]
OK, @Het-Shah is now a reviewer

**Comment by osorensen** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3700.

**Comment by ftarlaci** [comment]
Sorry I missed this. Since you have found enough reviewers for this submission, please consider me for future submissions. Thank you!

**Comment by osorensen** [comment]
> Sorry I missed this. Since you have found enough reviewers for this submission, please consider me for future submissions. Thank you!

Thanks @ftarlaci, I'll get back to you later :)
