### ISSUE TITLE
[PRE REVIEW]: Biomarker-NLP: A Python Package for Mining Biomarker Information for FDA-Approved Targeted Cancer Therapies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3693]
**Submitting author:** @Damonlin11 (<a href="http://orcid.org/0000-0001-6348-5015">Junxia Lin</a>)
**Repository:** <a href="https://github.com/Damonlin11/FDA-approved-Targeted-Therapies-Label-Extraction" target ="_blank">https://github.com/Damonlin11/FDA-approved-Targeted-Therapies-Label-Extraction</a>
**Version:** v0.0.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6e375251e512b4e01b666d49ff8448f2/status.svg)](https://joss.theoj.org/papers/6e375251e512b4e01b666d49ff8448f2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6e375251e512b4e01b666d49ff8448f2"><img src="https://joss.theoj.org/papers/6e375251e512b4e01b666d49ff8448f2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6e375251e512b4e01b666d49ff8448f2/status.svg)](https://joss.theoj.org/papers/6e375251e512b4e01b666d49ff8448f2)
```

**Author instructions**

Thanks for submitting your paper to JOSS @Damonlin11. **Currently, there isn't an JOSS editor assigned** to your paper.

@Damonlin11 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 899

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.18653/v1/w19-5034 is OK
- 10.1371/journal.pone.0189663 is OK

MISSING DOIs

- 10.5860/choice.44-2734 may be a valid DOI for title: DailyMed

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.18 s (260.4 files/s, 100222.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           8           1226           1786           4988
TeX                             25            454           1158           3238
Jupyter Notebook                 1              0           3671           1121
Markdown                         3             63              0            178
make                             2             22             12             50
DOS Batch                        2             17              2             47
reStructuredText                 5             11             25             15
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            47           1793           6654           9643
-------------------------------------------------------------------------------


Statistical information for the repository '2035196819749f7b9d6e06c7' was
gathered on 2021/09/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
JunxiaLin                       20         33861          25861          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
JunxiaLin                  8000           23.6          0.4                6.54
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03693/joss.03693/10.21105.joss.03693.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03693/joss.03693/10.21105.joss.03693.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@Damonlin11 – many thanks for your submission to JOSS. I'm flagging this submission for a scope review by the broader JOSS editorial team as it looks a little unusual for us:

- We don't generally publish API/model wrappers for ML models. 
- A significant amount of the source code in this submission looks to be associated with the work done to [train the model](https://github.com/Damonlin11/FDA-approved-Targeted-Therapies-Label-Extraction/blob/main/biomarker_nlp/src/biomarker_nlp/negation_negbert.py) 
- The software looks like it could do with a fair amount of work on the packaging/presentation side of things.

This scope review will likely take a couple of weeks so sit tight for now :-)

**Comment by arfon** [comment]
@Damonlin11 – after review by the JOSS editorial team, this submission has been deemed out of scope for JOSS due to the reasons I outline above. 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
