### ISSUE TITLE
[PRE REVIEW]: W2W: A Python package that injects WUDAPT’s Local Climate Zone information in WRF

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3696]
**Submitting author:** @matthiasdemuzere (<a href="http://orcid.org/0000-0003-3237-4077">Matthias Demuzere</a>)
**Repository:** <a href="https://github.com/matthiasdemuzere/w2w" target ="_blank">https://github.com/matthiasdemuzere/w2w</a>
**Version:** v0.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/3c8fefc91d6659a1d2b5aa31d53dda83/status.svg)](https://joss.theoj.org/papers/3c8fefc91d6659a1d2b5aa31d53dda83)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/3c8fefc91d6659a1d2b5aa31d53dda83"><img src="https://joss.theoj.org/papers/3c8fefc91d6659a1d2b5aa31d53dda83/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/3c8fefc91d6659a1d2b5aa31d53dda83/status.svg)](https://joss.theoj.org/papers/3c8fefc91d6659a1d2b5aa31d53dda83)
```

**Author instructions**

Thanks for submitting your paper to JOSS @matthiasdemuzere. **Currently, there isn't an JOSS editor assigned** to your paper.

@matthiasdemuzere if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1800

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (133.4 files/s, 54115.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1            230            147            841
TeX                              1             39              0            334
Markdown                         2             78              0            182
YAML                             1              0              0            177
-------------------------------------------------------------------------------
SUM:                             5            347            147           1534
-------------------------------------------------------------------------------


Statistical information for the repository '426857cdc67156e0a9afe2b5' was
gathered on 2021/09/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel Argüeso                   1             1              1            0.15
matthiasdemuzere                 3          1259             41           99.85

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Daniel Argüeso                1          100.0          0.0                0.00
matthiasdemuzere           1217           96.7          0.0               10.76
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/joc.3746 is OK
- 10.1175/BAMS-D-11-00019.1 is OK
- 10.1029/2020GL088758 is OK
- 10.1023/A:1019207923078 is OK
- 10.1007/s00704-009-0142-9 is OK
- 10.1023/A:1016099921195 is OK
- 10.1016/j.uclim.2020.100584 is OK
- 10.3390/atmos11121349 is OK
- 10.1371/journal.pone.0214474 is OK
- 10.1038/s41597-020-00605-z is OK
- 10.3389/fenvs.2021.637455 is OK
- 10.5065/1dfh-6p97 is OK
- 10.1175/BAMS-D-16-0236.1 is OK
- 10.1016/j.uclim.2016.04.001 is OK
- 10.1002/joc.5447 is OK
- 10.1007/s00704-019-02881-1 is OK
- 10.1016/j.uclim.2019.100460 is OK
- 10.1016/j.uclim.2020.100616 is OK
- 10.1016/j.atmosres.2020.105220 is OK
- 10.1088/1748-9326/ac0377 is OK
- 10.1186/s40562-018-0126-7 is OK
- 10.1175/JAMC-D-17-0328.1 is OK

MISSING DOIs

- 10.1002/essoar.10506675.1 may be a valid DOI for title: Exploring the effects of rooftop mitigation strategies on urban temperatures and energy consumption

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03696/joss.03696/10.21105.joss.03696.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03696/joss.03696/10.21105.joss.03696.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@matthiasdemuzere – due to the relatively small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by matthiasdemuzere** [comment]
> if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @)

The two people that are best positioned to review this software are Alberto Martilli (https://github.com/albertomartilli) and Oscar Brousse (https://github.com/oscarbrousse), the authors of the Fortran-based Wudapt-to-Wrf packages that was launched in 2016.

**Comment by matthiasdemuzere** [comment]
> @matthiasdemuzere – due to the relatively small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. 

Ok, interesting. I did not realize about this size criterion.

In my defence: this code does exactly what is mentioned under the "substantial scholarly effort" section: it makes addressing research challenges significantly better. In this particular case: inserting detailed information on urban form and functions into the globally most widely used weather and climate model WRF. Many researchers have used the old approach (citation in the draft are not exhaustive). In addition, the authors of the original, less-flexible Fortran-based package are thrilled to have this software available, as they currently have to (manually) support a lot of researchers asking them questions about the implementation of their routine. I provided their names as potential reviewers, I am sure they can confirm the above.

> If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.
> 
> @whedon generate pdf
> @whedon check references

This JOSS procedure is new to me. So some questions:
- Should I fix the missing DOIs in the doc that is in my original repo?
- where exactly should I execute these whedon statements?

Thanks for the understanding and support.

**Comment by matthiasdemuzere** [comment]
> MISSING DOIs
> 
> - 10.1002/essoar.10506675.1 may be a valid DOI for title: Exploring the effects of rooftop mitigation strategies on urban temperatures and energy consumption
> 
> INVALID DOIs
> 
> - None


I just checked the above missing DOI. It is actually fine, it refers to the [pre-print of a paper]https://www.essoar.org/doi/10.1002/essoar.10506675.1) that is currently still under review.

So I assume nothing needs to be done here?

**Comment by arfon** [comment]
> In my defence: this code does exactly what is mentioned under the "substantial scholarly effort" section: it makes addressing research challenges significantly better. In this particular case: inserting detailed information on urban form and functions into the globally most widely used weather and climate model WRF. Many researchers have used the old approach (citation in the draft are not exhaustive). In addition, the authors of the original, less-flexible Fortran-based package are thrilled to have this software available, as they currently have to (manually) support a lot of researchers asking them questions about the implementation of their routine. I provided their names as potential reviewers, I am sure they can confirm the above.

Thanks for the additional context @matthiasdemuzere. The editorial team will use this when making their assessment.

> So I assume nothing needs to be done here?

:+1: yep, I think we're good for now.

**Comment by matthiasdemuzere** [comment]
> Thanks for the additional context @matthiasdemuzere. The editorial team will use this when making their assessment.

perfect, thanks.

There is one additional item I would like to mention, something I was reminded about by my co-author @dargueso.

Initially we had a private repo for this development, as it is part of a larger research project. This repo was launched March 8, and has 54 commits from all co-authors involved. Yet as we noticed there was already a big interest in this tool, we decided to move it to a seperate public repo, so that beta testers could already use it. This was done on June 10, and hence the commit statistics of this repo do not reflect the real time-investment of this development. If needed, I could add yourself or someone of the editorial team to the private repo, so that this information can be assessed.

A beta version of this tool has so far been tested over various regions/cities (including Perth, Rome, Zaragoza, Kuala Lumpur, London, Barcelona, Santiago de Chili, Oslo), by various users.

**Comment by danielskatz** [comment]
> > MISSING DOIs
> > 
> > * 10.1002/essoar.10506675.1 may be a valid DOI for title: Exploring the effects of rooftop mitigation strategies on urban temperatures and energy consumption
> > 
>
> I just checked the above missing DOI. It is actually fine, it refers to the [pre-print of a paper](https://www.essoar.org/doi/10.1002/essoar.10506675.1) that is currently still under review.
> 
> So I assume nothing needs to be done here?

The current version of the work has a DOI, so that DOI should be listed in the bibtex.  The peer-review status of the work isn't important to this decision, though it may (or may not) be important to the authors when choosing to include the work as a reference.  Once the work is included, its identifier should also be included.  If it is peer-reviewed and published while the review of the JOSS paper is underway, the DOI can be updated at the time.

**Comment by jedbrown** [comment]
I see this project is linked from [WUDAPT's website](https://www.wudapt.org/wudapt-to-wrf/), representing an endorsement by that community. (The link from w2w's README to www.wudapt.org is broken, BTW.)

I think this project needs to be packaged properly (pip and/or conda installable). That'll also mean `w2w_requirements.txt` needs to stop referring to internal conda files, among other things. It needs automated tests and improved documentation (like an example workflow a prospective user can follow before trying it on "real" data, and that may instill some practices that are good for provenance).

I'm curious to what extent WUDAPT formats may change over time, and if the tool can be robust to such changes, perhaps with lightweight validity checks to help catch breakage before running a WRF simulation.

**Comment by kthyng** [comment]
Hi @matthiasdemuzere and thanks for your submission. @jedbrown's input is similar to what several other editors said in regard to the fit of this submission: while the lines of code is a bit low, in particular the lack of packaging makes it too hard for other people to use, and represents what the readme describes as this being still in "beta" stage. Submission to JOSS seems a bit preemptive at this point. We encourage you to resubmit (please link to this issue at that time) after some further development, preferably at a stage when you would feel comfortable moving on from calling this beta software, as a guideline.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by matthiasdemuzere** [comment]
All,

Thanks for the assessment and the constructive feedback. I'll look into all of this with my co-authors, and will re-submit once we have implemented the requested developments.
