### ISSUE TITLE
[PRE REVIEW]: epyc: Computational experiment management in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3697]
**Submitting author:** @simoninireland (<a href="http://orcid.org/0000-0001-9633-2103">Simon Dobson</a>)
**Repository:** <a href="https://github.com/simoninireland/epyc" target ="_blank">https://github.com/simoninireland/epyc</a>
**Version:** 1.5.1
**Editor:** @ajstewartlang
**Reviewers:** @zbeekman, @lorenzo-rovigatti
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e04fc3a2b4f40a6f091c8d0ea5ae15b6/status.svg)](https://joss.theoj.org/papers/e04fc3a2b4f40a6f091c8d0ea5ae15b6)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e04fc3a2b4f40a6f091c8d0ea5ae15b6"><img src="https://joss.theoj.org/papers/e04fc3a2b4f40a6f091c8d0ea5ae15b6/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e04fc3a2b4f40a6f091c8d0ea5ae15b6/status.svg)](https://joss.theoj.org/papers/e04fc3a2b4f40a6f091c8d0ea5ae15b6)
```

**Author instructions**

Thanks for submitting your paper to JOSS @simoninirelland. **Currently, there isn't an JOSS editor assigned** to your paper.

@simoninirelland if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 932

**Comment by whedon** [comment]
PDF failed to compile for issue #3697 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (12d2d1afab5693829881d04c/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 10 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (700.1 files/s, 211327.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          32           1598           2614           4360
reStructuredText                55           1209            971           1429
make                             2             53             63            219
Jupyter Notebook                 1              0          15440            172
Markdown                         1             24              0            129
TeX                              1              5              0             54
YAML                             1              1              0             29
INI                              1              1              0              5
-------------------------------------------------------------------------------
SUM:                            94           2891          19088           6397
-------------------------------------------------------------------------------


Statistical information for the repository '2552254fd299320433f10b57' was
gathered on 2021/09/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Simon Dobson                   202         13072           4989           86.84
simoninireland                  26          1442           1296           13.16

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Simon Dobson               8572           65.6         19.1               17.09
```

**Comment by arfon** [comment]
:wave: @simoninireland – looks like there are some whitespace issues with your `paper.md` YAML header (see how GitHub is rendering here: https://github.com/simoninireland/epyc/blob/master/paper.md). Could you please fix it up and test here with `@whedon generate pdf`

**Comment by simoninireland** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #3697 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (2c21eac8dfa904e260a147b1/paper.md): found a tab character that violate intendation while scanning a plain scalar at line 10 column 11 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by simoninireland** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03697/joss.03697/10.21105.joss.03697.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03697/joss.03697/10.21105.joss.03697.pdf) :page_facing_up: :point_left:

**Comment by simoninireland** [comment]
@arfon That would have been Emacs tabify doing its thing... Fixed now :-)

**Comment by arfon** [comment]
@whedon invite @ajstewartlang as editor

:wave: @ajstewartlang – this looks like it could be up your street. Do you think you could handle this submission for us?

**Comment by whedon** [comment]
@ajstewartlang has been invited to edit this submission.

**Comment by ajstewartlang** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @ajstewartlang

**Comment by zbeekman** [comment]
I'd be happy to be a reviewer for this if it suites the editor (@ajstewartlang) & author (@simoninireland).

**Comment by ajstewartlang** [comment]
@whedon assign @zbeekman as reviewer

**Comment by whedon** [comment]
OK, @zbeekman is now a reviewer

**Comment by zbeekman** [comment]
@ajstewartlang Anything I can do to help get this review going? Suggest fellow reviewers etc? I seem to recall that the submitting author (@simoninireland) can also peruse [the list of potential reviewers](https://bit.ly/joss-reviewershttps://bit.ly/joss-reviewers) and suggest them here. In past reviews I've always been invited by an @ mention in the comments.

**Comment by ajstewartlang** [comment]
If you could @zbeekman that would be super helpful. I've emailed a couple of possible reviewers but haven't yet had responses - I appreciate people are understandably quite busy at the moment so if you or @simoninireland spotted some potential reviewers in that [list](https://bit.ly/joss-reviewershttps://bit.ly/joss-reviewers), that would be great thanks.

**Comment by zbeekman** [comment]
I'll give @simoninireland some time to peruse the list and suggest names here, and by midweek if we don't have more yet I'll drop some @ mentions of potential reviewers that look appropriate.

**Comment by ajstewartlang** [comment]
@lorenzo-rovigatti I've emailed you too in case you have GH notifications turned off - would you perhaps be able to review this submission?

**Comment by lorenzo-rovigatti** [comment]
Sure! I'll be happy to review the submission, it looks neat.

**Comment by ajstewartlang** [comment]
@whedon add @lorenzo-rovigatti as reviewer

**Comment by whedon** [comment]
OK, @lorenzo-rovigatti is now a reviewer

**Comment by ajstewartlang** [comment]
Many thanks for agreeing to review this submission @zbeekman and @lorenzo-rovigatti - it's very much appreciated! I'll start the review now...

**Comment by ajstewartlang** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3764.
