### ISSUE TITLE
[PRE REVIEW]: PyGEE-SWToolbox: A Python Jupyter Notebook toolbox for interactive surface water mapping and analysis using Google Earth Engine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3698]
**Submitting author:** @collinsowusu (<a href="http://orcid.org/0000-0001-6754-9311">Collins Owusu</a>)
**Repository:** <a href="https://github.com/collinsowusu/PyGEE-SWToolbox" target ="_blank">https://github.com/collinsowusu/PyGEE-SWToolbox</a>
**Version:** v1.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fccaf0d4815c087016e9ec500babf02f/status.svg)](https://joss.theoj.org/papers/fccaf0d4815c087016e9ec500babf02f)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fccaf0d4815c087016e9ec500babf02f"><img src="https://joss.theoj.org/papers/fccaf0d4815c087016e9ec500babf02f/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fccaf0d4815c087016e9ec500babf02f/status.svg)](https://joss.theoj.org/papers/fccaf0d4815c087016e9ec500babf02f)
```

**Author instructions**

Thanks for submitting your paper to JOSS @collinsowusu. **Currently, there isn't an JOSS editor assigned** to your paper.

@collinsowusu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 712

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1080/01431160600589179 is OK
- 10.1016/j.jag.2019.101973 is OK
- 10.21105/joss.02305 is OK
- 10.21105/joss.03168 is OK
- 10.1016/j.rse.2019.04.015 is OK
- 10.1016/j.rse.2020.111664 is OK
- 10.1016/j.rse.2017.06.031 is OK
- 10.1080/01431169608948714 is OK
- 10.1080/15481603.2019.1685198 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.rse.2013.08.029 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (247.4 files/s, 86068.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                 1              0            418            812
Python                           1             66            157            250
Markdown                         2             49              0            183
TeX                              1              9              0            142
XML                              1              0              0              1
-------------------------------------------------------------------------------
SUM:                             6            124            575           1388
-------------------------------------------------------------------------------


Statistical information for the repository 'c65cb3dde3bcd316e630f012' was
gathered on 2021/09/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
CollinsOwusu                     3           190             79           42.63
collinsowusu                     1           362              0           57.37

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
CollinsOwusu                116           61.1          1.5                7.76
collinsowusu                357           98.6          0.0               20.73
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03698/joss.03698/10.21105.joss.03698.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03698/joss.03698/10.21105.joss.03698.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@collinsowusu – many thanks for your submission to JOSS. I'm flagging this for a scope query by our wider editorial team (this will likely take 7-10 days) because this submission is a little unusual for us (primarily in the form of a notebook).

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arfon** [comment]
@collinsowusu – after review by the JOSS editorial team, this submission has been deemed out of scope for JOSS as we don't consider Jupyter notebooks software, and the other Python code associated with this submission has been judged to not reach our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

To encourage reuse by others, you might want to consider extracting the logic out of your notebook and building out a more substantial Python library for others to use.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
