### ISSUE TITLE
[REVIEW]: bsym - a basic symmetry module

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#370]
**Submitting author:** @bjmorgan (<a href="http://orcid.org/0000-0002-3056-8233">Benjamin J. Morgan</a>)
**Repository:** <a href="https://github.com/bjmorgan/bsym" target ="_blank">https://github.com/bjmorgan/bsym</a>
**Version:** v1.0.b1
**Editor:** @labarba
**Reviewer:** @aronwalsh
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.845328" target="_blank">10.5281/zenodo.845328</a>

## Status

[![status](http://joss.theoj.org/papers/6696543fc631bf66feb99a9cde808a39/status.svg)](http://joss.theoj.org/papers/6696543fc631bf66feb99a9cde808a39)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/6696543fc631bf66feb99a9cde808a39"><img src="http://joss.theoj.org/papers/6696543fc631bf66feb99a9cde808a39/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/6696543fc631bf66feb99a9cde808a39/status.svg)](http://joss.theoj.org/papers/6696543fc631bf66feb99a9cde808a39)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bjmorgan/bsym" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@aronwalsh, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bjmorgan/bsym">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.b1)?
- [x] **Authorship:** Has the submitting author (@bjmorgan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @aronwalsh it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by aronwalsh** [comment]
bsym is a python based symmetry module with applications in the molecular and materials domain. The code installed simply using `pip3 install bsym` and tests completed using `python3 -m unittest discover`. I found the source code to well written and documented. I particularly liked the jupyter notebook example, which introduces the background and functionality.  The code is useful pedagogically and could be employed for teaching group theory, but also for practical research in materials science.  I raised three minor issues on the repository tracker: https://github.com/bjmorgan/bsym/issues

**Comment by labarba** [comment]
Thanks for the lightning-fast review, @aronwalsh !! 
I see that you have checked off all the items in the reviewer checklist. Do I take it that your recommendation is to _Accept_ the submission, at this point? That is, we trust the authors to address the issues you posted on their repo, as they are minor, and proceed?

**Comment by aronwalsh** [comment]
No problem, I download the code yesterday and played around. Yes I recommend accept.

**Comment by labarba** [comment]
@arfon : This submission is ready for acceptance.

@aronwalsh : Thank you for your contribution to JOSS, and do consider submitting your research software!

@bjmorgan : Your next step is to make the software archive (if you haven't already done so), and please post the DOI of the archive here.

**Comment by bjmorgan** [comment]
@aronwalsh Thank you for the speedy review. 
@labarba I will address the issues raised in the review, and then generate an archived release.

**Comment by bjmorgan** [comment]
The issues raised by @aronwalsh have been responded to / addressed:

https://github.com/bjmorgan/bsym/issues/1
https://github.com/bjmorgan/bsym/issues/2
https://github.com/bjmorgan/bsym/issues/3

Changes:
- A bug, where submodules were not installing correctly using `pip`, has been fixed.
- The full configuration degeneracy is now preserved over a series of site substitutions.
- Examples using the `pymatgen` interface to auto-generate `SymmetryGroup` and `ConfigurationSpace` objects have been added to the example Jupyter notebook.

**Comment by bjmorgan** [comment]
@labarba 

- DOI of the submitted version, v1.0.b1: [10.5281/zenodo.833875](https://doi.org/10.5281/zenodo.833875)
- DOI of the "as accepted" version, v1.0.1: [10.5281/zenodo.845328](https://doi.org/10.5281/zenodo.845328)

**Comment by arfon** [comment]
@bjmorgan - it looks like there are a couple of issues with your paper with the citations, can you check the bibtex entries are correctly named please:

```
pandoc-citeproc: reference MorganEtAl_JMaterChemA2016 not found
pandoc-citeproc: reference LurchEtAl_ModelSimulMaterSciEng2009 not found
```

Also, there's a typo in the metadata of your paper. The first line is quoted with a beginning `'` and ending `"` which needs fixing:

```
title: 'bsym: A basic symmetry module"
```

**Comment by bjmorgan** [comment]
@arfon These should be fixed now. `pandoc --filter pandoc-citeproc paper.md -o paper.pdf` runs without errors.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.845328 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.845328" target="_blank">10.5281/zenodo.845328</a> is the archive.

**Comment by arfon** [comment]
@aronwalsh many thanks for your review here and to @labarba for editing this submission ✨ 

@bjmorgan - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00370 ⚡️ 🚀 💥
