### ISSUE TITLE
[PRE REVIEW]: DRSP-Sim: A Simulator for Ride-Sharing with Pooling: Joint Matching, Pricing, Route Planning, and Dispatching

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3704]
**Submitting author:** @marina-haliem (<a href="http://orcid.org/0000-0002-9782-6591">Marina Haliem</a>)
**Repository:** <a href="https://github.itap.purdue.edu/Clan-labs/Dynamic-RideSharing-Pooling-Simulator" target ="_blank">https://github.itap.purdue.edu/Clan-labs/Dynamic-RideSharing-Pooling-Simulator</a>
**Version:** v1
**Editor:** @martinfleis
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/22c1ea01f61f9edf995afb6b50738cf1/status.svg)](https://joss.theoj.org/papers/22c1ea01f61f9edf995afb6b50738cf1)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/22c1ea01f61f9edf995afb6b50738cf1"><img src="https://joss.theoj.org/papers/22c1ea01f61f9edf995afb6b50738cf1/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/22c1ea01f61f9edf995afb6b50738cf1/status.svg)](https://joss.theoj.org/papers/22c1ea01f61f9edf995afb6b50738cf1)
```

**Author instructions**

Thanks for submitting your paper to JOSS @marina-haliem. **Currently, there isn't an JOSS editor assigned** to your paper.

@marina-haliem if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1528

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (563.3 files/s, 64579.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          42            753            958           3366
TeX                              1             16              0            184
Markdown                         2             57              0            166
YAML                             1             14              4             74
XML                              3              0              0             26
-------------------------------------------------------------------------------
SUM:                            49            840            962           3816
-------------------------------------------------------------------------------


Statistical information for the repository 'dfab41dd1ab3f1ecbb22b9ef' was
gathered on 2021/09/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Marina Wagdy Wadea H            17         15361           1240          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Haliem, Marina Wagdy          4          100.0          4.8                0.00
Marina Wagdy Wadea H       5073           33.0          0.7               17.94
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03704/joss.03704/10.21105.joss.03704.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03704/joss.03704/10.21105.joss.03704.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TITS.2021.3096537 is OK
- 10.1145/3408308.3431114 is OK
- 10.1007/s11116-019-10012-y is OK

MISSING DOIs

- 10.1109/infocom.2018.8485988 may be a valid DOI for title: MOVI: A model-free approach to dynamic fleet management
- 10.1109/tits.2019.2931830 may be a valid DOI for title: Deeppool: Distributed model-free algorithm for ride-sharing using deep reinforcement learning
- 10.1016/j.trc.2020.02.008 may be a valid DOI for title: Trip-based graph partitioning in dynamic ridesharing
- 10.1016/j.cor.2016.07.020 may be a valid DOI for title: Multi-directional local search for a bi-objective dial-a-ride problem in patient transportation
- 10.1007/s12469-016-0139-6 may be a valid DOI for title: Scheduling constraints in dial-a-ride problems with transfers: a metaheuristic approach incorporating a cross-route scheduling procedure with postponement opportunities
- 10.1016/j.ejor.2012.05.028 may be a valid DOI for title: Optimization for dynamic ride-sharing: A review
- 10.1145/3385958.3430484 may be a valid DOI for title: A distributed model-free ride-sharing algorithm with pricing using deep reinforcement learning
- 10.1109/tits.2020.3048361 may be a valid DOI for title: Flexpool: A distributed model-free deep reinforcement learning algorithm for joint passengers and goods transportation
- 10.1109/tits.2021.3083740 may be a valid DOI for title: A distributed model-free algorithm for multi-hop ride-sharing using deep reinforcement learning

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon invite @martinfleis as editor

:wave: @martinfleis – I realize this might be somewhat outside your field but I _think_ you're our editor closest to this area. Would you be willing to take this submission on for us?

**Comment by whedon** [comment]
@martinfleis has been invited to edit this submission.

**Comment by arfon** [comment]
@marina-haliem – please add an OSI-approved license to your project. Also, please fix the DOIs (noting that Whedon's suggestions are not always right), using the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by martinfleis** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @martinfleis

**Comment by martinfleis** [comment]
Hi @marina-haliem,

I'll be editing your submission. I have a few points on top of those mentioned by @arfon above:

1) I see that your repository is on a private Github Enterprise server. Please note, that JOSS [requires](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) that the submission must:

```
  - Be stored in a repository that can be cloned without registration.
  - Be stored in a repository that is browsable online without registration.
  - Have an issue tracker that is readable without registration.
  - Permit individuals to create issues/file tickets against your repository.
```

While the first three points seem to be fine, the repository requires a Purdue account to create an issue. You will need to either change the settings (If that is possible) or move the repository to a different service (as Github.com or Gitlab.com).

2) I would suggest expanding the documentation. The only documentation I can see so far is the ReadMe file that jumps straight into very specific details and does not contain any Getting started section or Installation instructions and doesn't explain the design of the software or its API. It is also missing Community guidelines.

3) I am not sure if the software contains tests and if so, how to run them. Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.

```
Good: An automated test suite hooked up to continuous integration (GitHub Actions, Circle CI, or similar)
OK: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)
Bad (not acceptable): No way for the reviewer to objectively assess whether the software works
```

I would ask you to resolve the first two issues before I'll invite reviewers as they would need to open issues in the repository and assess the software against its (currently missing) documentation.

You can check the [JOSS review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html) and our [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html) to better understand JOSS submission requirements.

**Comment by arfon** [comment]
@whedon withdraw 

Closing in favour of https://github.com/openjournals/joss-reviews/issues/3712.

**Comment by whedon** [comment]
Paper withdrawn.
