### ISSUE TITLE
[PRE REVIEW]: skater: An R package for SNP-based Kinship Analysis, Testing, and Evaluation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3706]
**Submitting author:** @stephenturner (<a href="http://orcid.org/0000-0001-9140-9028">Stephen Turner</a>)
**Repository:** <a href="https://github.com/signaturescience/skater/" target ="_blank">https://github.com/signaturescience/skater/</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/11d0ad7a19c6c01430f994fb959e5d0e/status.svg)](https://joss.theoj.org/papers/11d0ad7a19c6c01430f994fb959e5d0e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/11d0ad7a19c6c01430f994fb959e5d0e"><img src="https://joss.theoj.org/papers/11d0ad7a19c6c01430f994fb959e5d0e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/11d0ad7a19c6c01430f994fb959e5d0e/status.svg)](https://joss.theoj.org/papers/11d0ad7a19c6c01430f994fb959e5d0e)
```

**Author instructions**

Thanks for submitting your paper to JOSS @stephenturner. **Currently, there isn't an JOSS editor assigned** to your paper.

@stephenturner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1086/519795 is OK
- 10.1093/bioinformatics/btq559 is OK
- 10.1101/gr.081398.108 is OK
- 10.1016/j.ajhg.2020.02.010 is OK
- 10.1016/j.ajhg.2020.02.012 is OK
- 10.1534/genetics.117.1122 is OK
- 10.1101/2021.06.25.449870 is OK
- 10.1371/journal.pgen.1007979 is OK
- 10.21105/joss.01686 is OK
- 10.1159/000363105 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (571.0 files/s, 88267.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            29           1421            367           4838
R                               11            153            781            559
XML                              1              0              2            441
CSS                              3             99             48            428
JavaScript                       4             64             34            266
TeX                              1             48              0            174
Rmd                              4            189            360            158
Markdown                         3             44              0             93
YAML                             4              9              4             66
SVG                              9              0              1             19
-------------------------------------------------------------------------------
SUM:                            69           2027           1597           7042
-------------------------------------------------------------------------------


Statistical information for the repository '8095a6019611567b6de3740c' was
gathered on 2021/09/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Stephen Turner                   1           364              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Stephen Turner              364          100.0          0.0                9.34
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03706/joss.03706/10.21105.joss.03706.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03706/joss.03706/10.21105.joss.03706.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope 

@stephenturner – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week. If you want to fix the DOIs (noting that whedon's suggestions are not always right), you can, then use the following commands (one at a time, as the first line of a new comment) to regenerate the PDF and check the references.

@whedon generate pdf
@whedon check references

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by stephenturner** [comment]
Thanks @arfon -- let me know if this passes editorial review, and I'll start looking through the list of reviewers. Thanks!

**Comment by arfon** [comment]
@stephenturner – thanks for your submission to JOSS. Unfortunately, after review by the JOSS editorial team we've determined that this submission doesn't meet our [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by stephenturner** [comment]
Could someone here please help me understand the rejection? The [# LOC in the analysis above](https://github.com/openjournals/joss-reviews/issues/3706#issuecomment-916260157) does not fall below the [LOC limit for a desk rejection](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). Thank you!
