### ISSUE TITLE
[PRE REVIEW]: LaplaceInterpolation.jl: A Julia package for fast interpolation on a grid interpolation on a grid 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3707]
**Submitting author:** @lootie (<a href="http://orcid.org/0000-0003-3996-773X">Charlotte Haley</a>)
**Repository:** <a href="https://github.com/vishwas1984/LaplaceInterpolation.jl" target ="_blank">https://github.com/vishwas1984/LaplaceInterpolation.jl</a>
**Version:** v0.1
**Editor:** @VivianePons
**Reviewers:** @wkearn, @eviatarbach
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/00d8d848d3644d8ac98f746ad236a6e3/status.svg)](https://joss.theoj.org/papers/00d8d848d3644d8ac98f746ad236a6e3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/00d8d848d3644d8ac98f746ad236a6e3"><img src="https://joss.theoj.org/papers/00d8d848d3644d8ac98f746ad236a6e3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/00d8d848d3644d8ac98f746ad236a6e3/status.svg)](https://joss.theoj.org/papers/00d8d848d3644d8ac98f746ad236a6e3)
```

**Author instructions**

Thanks for submitting your paper to JOSS @lootie. **Currently, there isn't an JOSS editor assigned** to your paper.

@lootie if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 931

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.51 s (93.5 files/s, 314241.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                12              0         155843           1814
Julia                           21            346            163           1450
Markdown                         4            103              0            587
Python                           3            158            175            339
TeX                              1             11              0            116
YAML                             4              5              4            110
TOML                             3              3              0             44
-------------------------------------------------------------------------------
SUM:                            48            626         156185           4460
-------------------------------------------------------------------------------


Statistical information for the repository 'f29192abbed95d9658232ed1' was
gathered on 2021/09/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Charlotte Haley                 11          1063            421           95.25
Vishwas Rao                      3            52             22            4.75

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Charlotte Haley             669           62.9          1.2               26.46
Vishwas Rao                   3            5.8          1.8                0.00
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03707/joss.03707/10.21105.joss.03707.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03707/joss.03707/10.21105.joss.03707.pdf) :page_facing_up: :point_left:

**Comment by lootie** [comment]
License file added to repo (gnu GPL v2.0).

**Comment by arfon** [comment]
@whedon invite @VivianePons as editor

:wave: @VivianePons - would you be willing to edit this submission for us?

**Comment by whedon** [comment]
@VivianePons has been invited to edit this submission.

**Comment by VivianePons** [comment]
@whedon set @VivianePons as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by VivianePons** [comment]
@whedon assign @VivianePons as editor

**Comment by whedon** [comment]
OK, the editor is @VivianePons

**Comment by VivianePons** [comment]
Hi @lootie glad to see you again! I'd be happy to handle your submission ;) 

Do you have any suggestions for reviewers?

**Comment by lootie** [comment]
Hi @VivianePons great to work with you again. For reviewers, I'll suggest wkearn and ysimillides.

**Comment by wkearn** [comment]
I'd be happy to review this submission.

**Comment by VivianePons** [comment]
Thanks, that's perfect!

**Comment by VivianePons** [comment]
@whedon add @wkearn as reviewer

**Comment by whedon** [comment]
OK, @wkearn is now a reviewer

**Comment by VivianePons** [comment]
@whedon add @eviatarbach as reviewer

**Comment by whedon** [comment]
OK, @eviatarbach is now a reviewer

**Comment by VivianePons** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3766.
