### ISSUE TITLE
[REVIEW]: Production Function Estimation in R: The prodest Package

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#371]
**Submitting author:** @GabrieleRovigatti (<a href="http://orcid.org/0000-0003-4021-3070">Gabriele Rovigatti</a>)
**Repository:** <a href="https://github.com/GabrieleRovigatti/prodest" target ="_blank">https://github.com/GabrieleRovigatti/prodest</a>
**Version:** v0.1.1
**Editor:** @leeper
**Reviewer:** @sebastianbarfort
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1004765" target="_blank">10.5281/zenodo.1004765</a>

## Status

[![status](http://joss.theoj.org/papers/fd6b1f48e1f78d1a06f8d6f40cbfc987/status.svg)](http://joss.theoj.org/papers/fd6b1f48e1f78d1a06f8d6f40cbfc987)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/fd6b1f48e1f78d1a06f8d6f40cbfc987"><img src="http://joss.theoj.org/papers/fd6b1f48e1f78d1a06f8d6f40cbfc987/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/fd6b1f48e1f78d1a06f8d6f40cbfc987/status.svg)](http://joss.theoj.org/papers/fd6b1f48e1f78d1a06f8d6f40cbfc987)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/GabrieleRovigatti/prodest/tree/master/prodest" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@sebastianbarfort, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/GabrieleRovigatti/prodest/tree/master/prodest">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.1)?
- [x] **Authorship:** Has the submitting author (@GabrieleRovigatti) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @sebastianbarfort it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by leeper** [comment]
@sebastianbarfort are you satisfied with the responses to issues you raised? Or are further changes needed?

**Comment by sebastianbarfort** [comment]
I'm super satisfied. Thanks for quick responses @GabrieleRovigatti, it's a great package!

**Comment by leeper** [comment]
@sebastianbarfort Great. Thanks for your review!

@GabrieleRovigatti Everything looks complete to me.

@arfon Over to you.

**Comment by leeper** [comment]
@sebastianbarfort Forgot to mention - if you're interested in reviewing for JOSS again in the future, would you mind adding your info to the reviewer pool by submitting a PR with your details in this file: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by GabrieleRovigatti** [comment]
Hi @sebastianbarfort, hi @leeper , 

just to thank you guys for the time you dedicated to the review!

**Comment by GabrieleRovigatti** [comment]
Hi @arfon, just checking in to see whether there is any news on the publication process.

**Comment by arfon** [comment]
@GabrieleRovigatti - I can't find the paper (`paper.md`) associated with this submission in the repository. Can you point me to it please?

**Comment by arfon** [comment]
@GabrieleRovigatti if [this](https://github.com/GabrieleRovigatti/prodest/blob/master/prodest/paper/prodest.md) is the paper, please rename these files to `paper.md` and `paper.bib`

**Comment by GabrieleRovigatti** [comment]
@arfon done. Sorry for the misunderstanding

**Comment by arfon** [comment]
@GabrieleRovigatti - please merge this PR https://github.com/GabrieleRovigatti/prodest/pull/6 and then could you please make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by GabrieleRovigatti** [comment]
@arfon the DOI is  10.5281/zenodo.1004765  - how do I update the thread with it? thanks

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1004765 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1004765" target="_blank">10.5281/zenodo.1004765</a> is the archive.

**Comment by arfon** [comment]
@sebastianbarfort - many thanks for your review and to @leeper for editing this submission ✨ 

@GabrieleRovigatti - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00371 ⚡️ 🚀 💥

**Comment by GabrieleRovigatti** [comment]
@arfon, @leeper, @sebastianbarfort thank you all guys for the review process, it has been fruitful for the command implementation and interesting for me to see how you work.
