### ISSUE TITLE
[PRE REVIEW]: DRSP-Sim: A Simulator for Ride-Sharing with Pooling: Joint Matching, Pricing, Route Planning, and Dispatching

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3712]
**Submitting author:** @marina-haliem (<a href="http://orcid.org/0000-0002-9782-6591">Marina Haliem</a>)
**Repository:** <a href="https://github.com/marina-haliem/Dynamic-RideSharing-Pooling-Simulator" target ="_blank">https://github.com/marina-haliem/Dynamic-RideSharing-Pooling-Simulator</a>
**Version:** v1.1
**Editor:** @martinfleis
**Reviewers:** @RafalKucharskiPK, @1tylermitchell
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4f1fc8e4cc30a2a620950b66cc07d5f7/status.svg)](https://joss.theoj.org/papers/4f1fc8e4cc30a2a620950b66cc07d5f7)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4f1fc8e4cc30a2a620950b66cc07d5f7"><img src="https://joss.theoj.org/papers/4f1fc8e4cc30a2a620950b66cc07d5f7/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4f1fc8e4cc30a2a620950b66cc07d5f7/status.svg)](https://joss.theoj.org/papers/4f1fc8e4cc30a2a620950b66cc07d5f7)
```

**Author instructions**

Thanks for submitting your paper to JOSS @marina-haliem. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @martinfleis.

@marina-haliem if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1528

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (564.0 files/s, 65310.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          42            753            958           3366
Markdown                         2             71              0            198
TeX                              1             16              0            194
YAML                             1             14              4             74
XML                              3              0              0             26
-------------------------------------------------------------------------------
SUM:                            49            854            962           3858
-------------------------------------------------------------------------------


Statistical information for the repository 'f334ddf2be2061a05141a8ec' was
gathered on 2021/09/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Marina Wagdy Wadea H            17         15361           1240          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Haliem, Marina Wagdy          4          100.0          4.8                0.00
Marina Wagdy Wadea H       5073           33.0          0.7               17.94
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/INFOCOM.2018.8485988 is OK
- 10.1109/TITS.2019.2931830 is OK
- 10.1073/pnas.1611675114 is OK
- 10.1016/j.cor.2016.07.020 is OK
- 10.1007/s12469-016-0139-6 is OK
- 10.1016/j.ejor.2012.05.028 is OK
- 10.1145/3385958.3430484 is OK
- 10.1109/TITS.2021.3096537 is OK
- 10.1109/TITS.2020.3048361 is OK
- 10.1109/tits.2021.3083740 is OK
- 10.1145/3408308.3431114 is OK
- 10.1007/s11116-019-10012-y is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.trc.2020.02.008 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03712/joss.03712/10.21105.joss.03712.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03712/joss.03712/10.21105.joss.03712.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon assign @martinfleis as editor

**Comment by whedon** [comment]
OK, the editor is @martinfleis

**Comment by arfon** [comment]
:wave: @martinfleis – the authors of #3704 decided to resubmit incorporating your feedback from that pre-review issue. As such, I've gone ahead and closed the old issue in favour of this one.

**Comment by martinfleis** [comment]
Thank you for the changes @marina-haliem!

If you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Comment by marina-haliem** [comment]
Hi @martinfleis,
I had replied via email last week, but not sure if you saw that so I am sending it here again.

We don't really have any suggestions for reviewers and we are open to any. From this list, I think these can be the most related to the field are:
- vasudev-sharma
- smith42
- anki-xyz
- FranciscoReveriano
- bmoradi93

Best Regards,
Marina

**Comment by martinfleis** [comment]
@whedon assign @RafalKucharskiPK as reviewer

**Comment by whedon** [comment]
OK, @RafalKucharskiPK is now a reviewer

**Comment by RafalKucharskiPK** [comment]
Dear @marina-haliem 
 I cloned the repo, downloaded the data (from https://purr.purdue.edu/publications/3843/1), created conda env, installed most of dependencies and run `simulator_driver.py`.
 
 Minor issues that I managed to overcome:
1. you require pandas==0.22 - which is ancient - 2017(!), and it clashed with many of my other packages, I used lates pandas and so far it went OK.
2. The `db.sqlite3` path is your local path, I changed it to "data\db": 
![image](https://user-images.githubusercontent.com/20555451/134348441-ffc89cf0-d2f4-4f18-8d3c-735cb3fc9ba7.png)

3. The default simulation takes 8 days (in simulation) one day takes ca. one hour on my laptop - way too long for a quickstart, please provide a toy example for first users.

Nonetheless it did not work for me, after a single day the error occured. Then I changed to one day in config, and again after a day passed I receive:
```
Traceback (most recent call last):
  File "/Users/rkucharski/Documents/GitHub/Dynamic-RideSharing-Pooling-Simulator/simulator_driver.py", line 159, in <module>
    Sim_experiment.simulator.step()
  File "/Users/rkucharski/Documents/GitHub/Dynamic-RideSharing-Pooling-Simulator/simulator/simulator.py", line 71, in step
    if vehicle.agent_type == agent_codes.dqn_agent:
AttributeError: 'Vehicle' object has no attribute 'agent_type'

Process finished with exit code 1 
```
 so please create a stable version to reproduce.

PS. On the main github page I am missing quick walkthrough tutorial for first users, e.g. now I first see how to set 'OSRM' which happens to be not needed, but only later I see where is the data bundle to run simulations.

Good luck!

**Comment by martinfleis** [comment]
@RafalKucharskiPK Thanks for a speedy start! Just note that we are still in the pre-review phase and the proper review with checklists and detailed instructions will start as soon as we'll confirm a second reviewer.

**Comment by martinfleis** [comment]
@whedon add @1tylermitchell as reviewer

**Comment by whedon** [comment]
OK, @1tylermitchell is now a reviewer

**Comment by martinfleis** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3761.
