### ISSUE TITLE
[PRE REVIEW]: react-simplified: an easy to use JavaScript UI library with automatic state and property management

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3713]
**Submitting author:** @eidheim (<a href="http://orcid.org/0000-0001-5355-6326">Ole Christian Eidheim</a>)
**Repository:** <a href="https://gitlab.com/eidheim/react-simplified" target ="_blank">https://gitlab.com/eidheim/react-simplified</a>
**Version:** v3.0.2
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2eb16785598ee50478ff158fb9c87eac/status.svg)](https://joss.theoj.org/papers/2eb16785598ee50478ff158fb9c87eac)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2eb16785598ee50478ff158fb9c87eac"><img src="https://joss.theoj.org/papers/2eb16785598ee50478ff158fb9c87eac/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2eb16785598ee50478ff158fb9c87eac/status.svg)](https://joss.theoj.org/papers/2eb16785598ee50478ff158fb9c87eac)
```

**Author instructions**

Thanks for submitting your paper to JOSS @eidheim. **Currently, there isn't an JOSS editor assigned** to your paper.

@eidheim if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1130

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (383.3 files/s, 50497.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       6            150             55            883
JSON                             3              0              0            339
Markdown                         2             53              0            273
TeX                              1             11              0            109
TypeScript                       1             11             34             22
YAML                             1              5              0             21
HTML                             1              0              0             10
-------------------------------------------------------------------------------
SUM:                            15            230             89           1657
-------------------------------------------------------------------------------


Statistical information for the repository 'bbd5f22d4e3e2dd18da55f77' was
gathered on 2021/09/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ole Christian Eidhei             1           123              0            4.42
eidheim                         64          1812            847           95.58

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
eidheim                    1088           60.0         20.5                5.06
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.tcs.2004.12.030 is OK
- 10.1109/IRI.2007.4296688 is OK
- 10.1145/2980991 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03713/joss.03713/10.21105.joss.03713.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03713/joss.03713/10.21105.joss.03713.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@whedon query scope

@eidheim – due to the relatively small size of this code, and whether or not this fits within our [definition of research software ](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) the editors will now discuss if this submission is in scope for us. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by eidheim** [comment]
Thank you for considering this submission @arfon. I agree that the library is not targeting a specific research field, but rather several fields that are in need of an UI library in their work. I would still argue that this submission meets the JOSS review criteria, such as for instance the previous [gtk-fortran](https://joss.theoj.org/papers/10.21105/joss.01109) publication at JOSS.

**Comment by arfon** [comment]
@eidheim – many thanks for your submission to JOSS. After review by the editorial board, we've determined that this kind of generalist package web development library does not meet our definition of [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) classified as out of scope for us.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
