### ISSUE TITLE
[PRE REVIEW]: shinyJackpot: Visualizing lottery gambling in a large Canadian city

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3716]
**Submitting author:** @andr3wli (<a href="http://orcid.org/0000-0001-9033-1433">Andrew Li</a>)
**Repository:** <a href="https://github.com/andr3wli/shinyapps" target ="_blank">https://github.com/andr3wli/shinyapps</a>
**Version:** 0.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6e1940640d65f265c0f5bf2ceddf938c/status.svg)](https://joss.theoj.org/papers/6e1940640d65f265c0f5bf2ceddf938c)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6e1940640d65f265c0f5bf2ceddf938c"><img src="https://joss.theoj.org/papers/6e1940640d65f265c0f5bf2ceddf938c/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6e1940640d65f265c0f5bf2ceddf938c/status.svg)](https://joss.theoj.org/papers/6e1940640d65f265c0f5bf2ceddf938c)
```

**Author instructions**

Thanks for submitting your paper to JOSS @andr3wli. **Currently, there isn't an JOSS editor assigned** to your paper.

@andr3wli if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1161

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (244.9 files/s, 22720.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               16            303            301           1490
Markdown                         7            109              0            212
TeX                              1             14              1            132
CSS                              1              2              2             21
Rmd                              3             27             70              4
make                             1              1              0              2
-------------------------------------------------------------------------------
SUM:                            29            456            374           1861
-------------------------------------------------------------------------------


Statistical information for the repository 'dd448f615dc7be2c8d7dc86b' was
gathered on 2021/09/11.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01686 is OK

MISSING DOIs

- 10.18637/jss.v040.i03 may be a valid DOI for title: Dates and times made easy with lubridate
- 10.1007/s10899-010-9194-0 may be a valid DOI for title: Lottery gambling: A review
- 10.1093/esr/jcn063 may be a valid DOI for title: The inequality of fair play: lottery gambling and social stratification in Germany
- 10.3386/w2246 may be a valid DOI for title: Implicit taxation in lottery finance
- 10.1177/109114218701500306 may be a valid DOI for title: The redistributive effects of lotteries: Evidence from Canada
- 10.1177/074391569801700202 may be a valid DOI for title: A longitudinal analysis of income-based tax regressivity of state-sponsored lotteries
- 10.1007/s10899-009-9122-3 may be a valid DOI for title: Can demographic variables predict lottery and pari-mutuel losses? An empirical investigation
- 10.1111/add.15252 may be a valid DOI for title: Relationships between socio-economic status and lottery gambling across lottery types: neighborhood-level evidence from a large city

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03716/joss.03716/10.21105.joss.03716.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03716/joss.03716/10.21105.joss.03716.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@andr3wli – many thanks for your submission to JOSS. After review by the editorial board, we've determined that this kind of visualisation package does not meet our definition of [research software](https://joss.readthedocs.io/en/latest/submitting.html#what-we-mean-by-research-software) classified as out of scope for us.

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
